### ISSUE TITLE
Unit Test fails on expect_failures in output with precondition

### ISSUE THREAD

**Issue by heldersepu** [hashicorp/terraform#34641] opened 2024-02-09 00:04 UTC
### Terraform Version

```shell
Terraform v1.7.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
variable "x" {
  type = string
}

output "validation" {
  value = var.x
  precondition {
    condition     = var.x != "test"
    error_message = "test"
  }
}
```

test
```terraform
run "ok" {
  command = plan
  variables {
    x = "foo"
  }
  assert {
    condition     = output.validation == "foo"
    error_message = "test"
  }
}

run "bad" {
  command = plan
  variables {
    x = "test"
  }
  expect_failures = [
    var.x
  ]
}

```

### Debug Output

```
> terraform test

main.tftest.hcl... in progress
  run "ok"... pass
  run "bad"... fail
╷
│ Error: Module output value precondition failed
│ 
│   on main.tf line 9, in output "validation":
│    9:     condition     = var.x != "test"
│     ├────────────────
│     │ var.x is "test"
│ 
│ test
╵
╷
│ Error: Missing expected failure
│ 
│   on main.tftest.hcl line 18, in run "bad":
│   18:     var.x
│ 
│ The checkable object, var.x, was expected to report an error but did not.
╵
main.tftest.hcl... tearing down
main.tftest.hcl... fail

Failure! 1 passed, 1 failed.
```

### Expected Behavior

The expect_failures should catch the error

### Actual Behavior

Error is showing in the console but the expect_failures test fails

### Steps to Reproduce

just `terraform test` on that sample code

**Comment by heldersepu** [comment] 2024-02-09 00:27
... and that is just a simple test, I understand the same validation can be done with 
```terraform
variable "x" {
  type = string
  validation {
    condition = ...
  }
}
``` 
and yes the tests will work fine with that ...

I was doing more complex validation on multiple variables that needed the precondition on output, that is when I ran into this issue, see this for another example:
https://github.com/heldersepu/hs-scripts/tree/master/TerraForm/var_complex_validation

**Comment by liamcervante** [comment] 2024-02-09 13:57
Hi @heldersepu, thanks for filing this.

In your second run block, you are expecting a failure from `var.x` and not `output.validation`. You must expect the failure against the item that has the custom condition.

The following works for me:

```hcl
run "bad" {
  command = plan
  variables {
    x = "test"
  }
  expect_failures = [
    output.validation
  ]
}
```

I'll close this as working as intended! Feel free to reopen if I've missed anything or misunderstood something.

Thanks again!

**Closed** 2024-02-09 13:57 UTC
Labels: bug, new, working as designed
