### ISSUE TITLE
Unable to use variables in lists

### ISSUE THREAD

**Issue by gurjeet** [hashicorp/terraform#24933] opened 2020-05-12 20:15 UTC
### Terraform Version
```
$ terraform -v
Terraform v0.12.24
+ provider.cloudflare v2.6.0
```

### Terraform Configuration Files
None.

### Debug Output

Pasting debug output here instead of in a Gist, since the log output is short.

```
$ TF_LOG=trace terraform plan -var "cloudflare_api_token=faXfQcRoQCaO6OTqgMOY312qR1A7qZFPwxeXFjSAUn"
2020/05/12 13:08:24 [INFO] Terraform version: 0.12.24
2020/05/12 13:08:24 [INFO] Go runtime version: go1.13.8
2020/05/12 13:08:24 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan", "-var", "cloudflare_api_token=faXfQcRoQCaO6OTqgMOY312qR1A7qZFPwxeXFjSAUn"}
2020/05/12 13:08:24 [DEBUG] Attempting to open CLI config file: /Users/gurjeetsingh/.terraformrc
2020/05/12 13:08:24 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/05/12 13:08:24 [INFO] CLI command args: []string{"plan", "-var", "cloudflare_api_token=<redacted>"}

Error: Variables not allowed

  on dns.tf line 30, in variable "all_records":
  30:     ["A",    "@",   "${var.gitlab_pages_ipv4_address}", true],

Variables may not be used here.


Error: Variables not allowed

  on dns.tf line 31, in variable "all_records":
  31:     ["A",    "www", "${var.gitlab_pages_ipv4_address}", true ],

Variables may not be used here.

```

### Crash Output
N/A

### Expected Behavior
The plan and apply subcommands should succeed.

### Actual Behavior
Please see the debug output pasted above for the errors thrown.

### Steps to Reproduce
Here's the .tf file to that caused this error:

```
terraform {
  required_version = "~> 0.12"
  required_providers {
    cloudflare = "~> 2.0"
  }
}

provider "cloudflare" {
  version = "~> 2.0"
  api_token = var.cloudflare_api_token
}

variable "cloudflare_api_token" {
  # Terraform will prompt for the token.
  type = string
  description = "Provide the token that has at least {\"Permissions\": \"Zone.DNS\", \"Resources\": \"All zones\"}"
}

variable "cf_zone_id" {
    default = "redacted"
}

variable "gitlab_pages_ipv4_address" {
  default = "35.185.44.232"
}

variable "all_records" {
  default = [
    # Record type, record name, IP Address/value, is-proxied?
    ["A",    "@",   "${var.gitlab_pages_ipv4_address}", true],
    ["A",    "www", "${var.gitlab_pages_ipv4_address}", true ],
  ]
}

resource "cloudflare_record" "root-level" {
  count   = length(var.all_records)
  zone_id = var.cf_zone_id
  type    = var.all_records[count.index][0]
  name    = var.all_records[count.index][1]
  value   = var.all_records[count.index][2]
  proxied = var.all_records[count.index][3]
}


```
### Additional Context
None.

### References
I tried finding other similar reports in issues and on the internet, but did not find any that matched my specific usage of variables in lists.

**Comment by apparentlymart** [comment] 2020-05-12 20:56
Hi @gurjeet,

The reason for this error is not that you used a variable inside a _list_, but that you used a variable inside the `default` value of another variable. Variable defaults must always be constant values, and cannot include references to other objects such as variables or resources.

It looks like your goal here was to build a data structure dynamically from a number of your input variables. The intended way to do that in Terraform is to use [local values](https://www.terraform.io/docs/configuration/locals.html), which are conceptually similar to local symbols inside a function in a general-purpose programming language. Continuing that analogy, input variables are conceptually similar to function arguments.

Here's an example of using a local value instead of a variable to represent your derived data structure:

```hcl
locals {
  all_records = [
    # Record type, record name, IP Address/value, is-proxied?
    ["A", "@", var.gitlab_pages_ipv4_address, true],
    ["A", "www", var.gitlab_pages_ipv4_address, true],
  ]
}

resource "cloudflare_record" "root-level" {
  count   = length(local.all_records)
  zone_id = var.cf_zone_id
  type    = local.all_records[count.index][0]
  name    = local.all_records[count.index][1]
  value   = local.all_records[count.index][2]
  proxied = local.all_records[count.index][3]
}
```

Because Terraform is working as designed here, I'm going to close this issue. If you have any follow-up questions about local values or input variables, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core).

**Closed by apparentlymart** 2020-05-12 20:56 UTC
