### ISSUE TITLE
Failure to enumerate resource from zero to four

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform#26039] opened 2020-08-28 15:56 UTC
### Terraform Version

```
0.12.29
```

### Terraform Configuration Files

```terraform
variable "directory_service_directories" {
  type = map(object({
    ...
    ssm_documents = map(object({
      ...
    }))
    ...
  }))

directory_service_directories = # length of var is 4 with 2 keys --> value ssm_documents length 2, and 2 keys --> value ssm_documents length 0 (2*2+2*0=4)

locals {
  ssm_documents = flatten([
    for dir_key, dir in var.directory_service_directories : [
      for doc_key, doc in dir.ssm_documents : {
        new_key          = "domain-join_${aws_directory_service_directory.directory_service_directories[dir_key].id}_${regex("^(\\w+)", dir_key)[0]}_${doc_key}"
        ...
      }
    ]
  ])
}

resource "aws_ssm_document" "ssm_documents" {
  for_each = { for doc in local.ssm_documents : doc.new_key => doc }

  ...
}
```

### Debug Output

n/a

### Crash Output

n/a

### Expected Behavior

Terraform enumerates a resource from zero to four.

### Actual Behavior

>Error: Invalid for_each argument

>  on ../terraform-aws-ds/ad.tf line 41, in resource "aws_ssm_document" "ssm_documents":
  41:   for_each = { for doc in local.ssm_documents : doc.new_key => doc }

> The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

There are two issues with this error message:
- It can be readily calculated at `plan` time that there will be four resources, and not an unknown number.
- The error claims the issue can be avoided if the dependent resources are created first. However, the `aws_directory_service_directory.directory_service_directories` are all created and in the state, so this message is stating an inaccurate workaround.

### Steps to Reproduce

`terraform plan`

### Additional Context

I would very much appreciate a workaround for this in the interim please and thank you.

### References

n/a

**Comment by jbardin** [comment] 2020-08-31 21:40
Hi @mschuchard,

While you generally shouldn't reference resources through in `count` or `for_each` expressions, you are correct that if the resources are created already it should still be able to plan correctly. Is it possible to test your configuration on 0.13, which can handle more of these edge cases? If it's still not working with 0.13, it would help to have a complete reproduction case here to work with.

Thanks!

**Comment by jbardin** [comment] 2020-10-05 22:29
Since we haven't hear back in a while, and don't have a reproduction case, I'm going to close this out for now.
If you have more information, please feel free to respond here or file a new issue.

Thanks!

**Closed by jbardin** 2020-10-05 22:29 UTC
Labels: bug, waiting for reproduction, waiting-response

**Comment by mschuchard** [comment] 2020-10-06 11:30
That is ok. I was just looking at my workaround for the bug yesterday and still could not muster time to update this issue. The bug seems like it would take a good deal of time to fix, and the workaround is going fine for now. Thanks!
