### ISSUE TITLE
Volume tags not set properly

### ISSUE THREAD

**Issue by Sabotier** [hashicorp/terraform#24738] opened 2020-04-22 18:14 UTC
Hi,

I am running Terraform 0.12.24.
I have an AWS instances with additionnal volumes. The tag names on the additionnal volume are not the same as the tag on the root volume.
Every time I run, Terraform detects that the tags are not set properly. The first time, it will set all the tag to the same as the root volume. The second run will detect that the tags are not right and will change them back. The next run, they get changed again.

I have attached screen shots of the volumes tags, the plans and applys outputs.

Thanks in advance

![after applying plan 1](https://user-images.githubusercontent.com/64159601/80018004-6824cf80-84a3-11ea-9b1b-580c021949a3.png)
![after applying plan 2](https://user-images.githubusercontent.com/64159601/80018005-68bd6600-84a3-11ea-9c2c-1f29e5d347fc.png)
[apply 1.txt](https://github.com/hashicorp/terraform/files/4518176/apply.1.txt)
[apply 2.txt](https://github.com/hashicorp/terraform/files/4518177/apply.2.txt)
![original](https://user-images.githubusercontent.com/64159601/80018007-68bd6600-84a3-11ea-8958-9994ee796e30.png)
[plan 1.txt](https://github.com/hashicorp/terraform/files/4518178/plan.1.txt)
[plan 2.txt](https://github.com/hashicorp/terraform/files/4518179/plan.2.txt)

**Comment by danieldreier** [comment] 2020-04-22 19:13
Hi! Thanks for reporting this. In order to reproduce this, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I don't have any of your terraform code, and so I'm stuck.  

Can you please restate your reproduction case such that I can copy-paste it and run it locally?

**Comment by danieldreier** [comment] 2020-05-20 01:24
I'm going to close this for now because the information is insufficient to quickly reproduce the problem. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

If you would like to put the work into creating a full reproduction case, I'm happy to re-open the issue and then try to reproduce it.

**Closed by danieldreier** 2020-05-20 01:24 UTC
Labels: waiting-response
