### ISSUE TITLE
Ordering of dependencies isn't detected after removed resource B and the reference of resource B in resource A from tfconfig

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/terraform#24608] opened 2020-04-09 03:25 UTC
### Terraform Version

```
terraform v0.12.24
```

### Terraform Configuration Files

```hcl
resource "B" "test" {
  name = "abc"
}

resource "A" "test" {
  name  = "cdf"
  resource_B_id = B.test.id
}
```

### Crash Output

Error: Error deleting `B` "abc" (Resource Group "test-rg"): xxxx.xxxxClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="`B CannotBeDeleted`" Message="`B` /subscriptions/xxxx-xxx-xxx-xx/resourceGroups/test-rg/providers/Microsoft.xxxx/xxx/abc can not be deleted since it is still allocated to resource /subscriptions/xxxx-xxx-xxx-xx/resourceGroups/test-rg/providers/Microsoft.xxx/xxx/`A`. In order to delete the `B`, disassociate/detach the `B` from the resource `A`.  To learn how to do this, see aka.ms/delete B." Details=[]

### Expected Behavior

1. resource `A` should be updated to disassociate with B first.
2. then delete resource `B`.

### Actual Behavior

Terraform would delete resource `B` first before updates `A`. Seems terraform core doesn't detect dependency relation between A and B.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` with below tfconfig
```hcl
resource "B" "test" {
  name = "abc"
}

resource "A" "test" {
  name = "cdf"
  resource_B_id = B.test.id
}
```
3. `terraform apply` with below tfconfig
```hcl
resource "A" "test" {
  name = "cdf"
}
```

**Comment by danieldreier** [comment] 2020-04-09 18:23
Hi @neil-yechenwei can you provide a reproduction case that uses a real provider, ideally `null_resource`? I'm not quite sure what issue you're pointing to here, and as-is this results in:

```
Provider "B" not available for installation.

A provider named "B" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Provider "A" not available for installation.

A provider named "A" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".
```

**Comment by neil-yechenwei** [comment] 2020-04-10 01:07
Here is the real case. 

### Affected Resource(s)



* `azurerm_public_ip`
* `azurerm_nat_gateway`

### Terraform Configuration Files



```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "neil-pip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  public_ip_address_ids   = [azurerm_public_ip.test.id]
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```

### Panic Output



D:\natgateway>terraform apply --auto-approve
azurerm_resource_group.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg]
azurerm_public_ip.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/publicIPAddresses/neil-pip]
azurerm_virtual_network.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/virtualNetworks/neil-vnet]
azurerm_nat_gateway.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/natGateways/neil-gateway]
azurerm_subnet.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/virtualNetworks/neil-vnet/subnets/neil-subnet]
azurerm_subnet_nat_gateway_association.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/virtualNetworks/neil-vnet/subnets/neil-subnet]
azurerm_public_ip.test: Destroying... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/publicIPAddresses/neil-pip]

Error: Error deleting Public IP "neil-pip" (Resource Group "neil-nat-rg"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/publicIPAddresses/neil-pip can not be deleted since it is still allocated to resource /subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/natGateways/neil-gateway. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]

### Expected Behavior
`azurerm_nat_gateway` resource should be updated first, then delete `azurerm_public_ip` resource.

### Actual Behavior


Terraform would delete `azurerm_public_ip` resource before updates `azurerm_nat_gateway`.

### Steps to Reproduce



1. Run `terraform apply --auto-approve` with below tfconfig.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "neil-pip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  public_ip_address_ids   = [azurerm_public_ip.test.id]
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```
2. Run `terraform apply --auto-approve` with below tfconfig:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```

**Comment by danieldreier** [comment] 2020-04-10 01:32
Thanks @neil-yechenwei - this is definitely helpful. Based on this information, this looks to me like an issue with the AzureRM provider rather than terraform core, because AzureRM is where the [implicit dependencies](https://learn.hashicorp.com/terraform/azure/dependencies_az) would get set such that this resource ordering happens as you expect. 

I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AzureRM provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Closed** 2020-04-10 02:20 UTC
Labels: provider/azurerm
