### ISSUE TITLE
Nested modules and first level resources not honoring when using --target=module.A

### ISSUE THREAD

**Issue by beenanner** [hashicorp/terraform#15622] opened 2017-07-24 17:16 UTC
### Terraform Version
➜  terraform-module-issue git:(master) terraform -v
Terraform v0.9.11

### Terraform Configuration Files
https://github.com/beenanner/terraform-module-issue
and
https://github.com/beenanner/terraform-module-issue-module

### Debug Output

Output of the following commands
`terraform plan -var image=ubuntu-1604-lts` = correct
`terraform plan` = correct
`terraform plan -target=module.instances` = incorrect
`terraform plan -target=module.instances.google_compute_instance.compute` = correct
`terraform plan -target=module.instances.module.compute` = correct

https://gist.github.com/beenanner/010085f044b6738231b41ada752bb121

### Expected Behavior
`terraform plan -target=module.instances` should produce a diff where the image or count of compute instances are identified as will be changed.

### Actual Behavior
What actually happened?
Does not detect changes in the variables.
"No change. Infastructure is up-to-date"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. Make a change to the terraform.tfvars image
1. `terraform plan -target=module.instances`
1. Shows no changes to be made
1. `terraform plan -target= module.instances.module.compute`
1. Shows changes will be made.

### References
- https://github.com/hashicorp/terraform/issues/12009

**Comment by apparentlymart** [comment] 2017-07-24 18:08
Hi @beenanner! Sorry things aren't working as expected here.

I think what you're saying here is that when you run `terraform plan -target=module.instances` you expect the resources in your `module.instances.module.compute` to be targeted.

If so, I can confirm that this was changed for 0.10.0 and will be included in the final release of this when it comes out. You can see a preview of this functionality in the `0.10.0-rc1` release, but I suggest trying that only on test configurations since it will "upgrade" the state such that it is no longer compatible with `0.9` releases.

There's more information on this change [in the upgrade guide](https://github.com/hashicorp/terraform/blob/v0.10.0-rc1/website/upgrade-guides/0-10.html.markdown#recursive-module-targeting-with--target).

**Closed** 2017-07-24 18:09 UTC
Labels: cli, enhancement

**Comment by beenanner** [comment] 2017-07-25 03:44
Thanks @apparentlymart for the quick response! I'll check it out.
