### ISSUE TITLE
Terraform import failing with error "The count value depends on resource attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by jippolito-nasuni** [hashicorp/terraform#33168] opened 2023-05-09 15:21 UTC
### Terraform Version

```shell
terraform version 1.4.2
```

### Terraform Configuration Files

resource "aws_vpc_dhcp_options" "dns_resolver_usw2" {
  domain_name         = "us-west-2.compute.internal"
  domain_name_servers = ["AmazonProvidedDNS"]
  provider            = aws.usw2
}

 
- module that creates subnets, route tables and associations.
module networking_uswest2 {

   private_subnets   = ["1.1.1.0/24", "1.1.2.0/24", "1.1.3.0/24"]
   public_subnets    = ["1.1.11.0/24", "1.1.12.0/24", "1.1.13.0/24"]
   dhcp_options_id      = aws_vpc_dhcp_options.dns_resolver_usw2.id

   depends_on = [aws_vpc_dhcp_options.dns_resolver_usw2]
}

### Debug Output

Error: Invalid count argument

   on modules/vpc/networking/lock/route_tables.tf line 59, in resource "aws_route_table_association" "lock_subnet_public_rt_assoc":
   59:   count          = length(aws_subnet.lock_public_subnets)

 The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.

### Expected Behavior

I should just be able to import the aws_vpc_dhcp_options without an error. 

### Actual Behavior

I am trying import a resource _aws_vpc_dhcp_options_.  Later, there is a module that needs the id of the _aws_vpc_dhcp_options_ resource for the _aws_route_table_association_ that has a count, but I am not trying to import the _aws_route_table_association_ value nor apply it yet.  

I cannot import a resource that another resource will be dependent on later when I try to import it.  

### Steps to Reproduce

terraform import aws_vpc_dhcp_options.dns_resolver_usw2 dopt-XXXXX

### Additional Context

_I can run a terraform plan successfully and it does plan all the expected resources.  Not sure why I cant import them in the same order I would expect the plan to apply them_

### References

https://github.com/hashicorp/terraform/issues/30672

**Comment by jbardin** [comment] 2023-05-09 15:48
Duplicate of #24690

**Closed by jbardin** 2023-05-09 15:48 UTC
Labels: bug, new
