### ISSUE TITLE
Computed values changing are not triggering updates

### ISSUE THREAD

**Issue by jefferai** [hashicorp/terraform#1112] opened 2015-03-03 20:09 UTC
I'm not sure when this started happening, but I'm seeing it now with all of my `Computed` values: the computed value changes, but nothing happens. This is on c220e6770697c869fec0fd651ef002c717d4eaaf.

Relevant bits of schema:

```
            "active": &schema.Schema{
                Type:     schema.TypeBool,
                Computed: true,
                ForceNew: true,
            },

            "freshest_image": &schema.Schema{
                Type:     schema.TypeString,
                Computed: true,
                ForceNew: true,
            },
```

Walking through, pay attention to the values of `active` and `freshest_image` as they are what I'll be toggling:

```
$ terraform apply
docker_container.aiab: Refreshing state... (ID: ba242ee105e19406e71e3d323f03f038e6fb5fc0da17ce7ed161ccb0a88e47af)
docker_container.ramlsnarf: Refreshing state... (ID: f9b8d4318ecdf9098d6d8af8d49dfdb3e3af17917ca852333b4a3e1e49e1be78)
docker_container.registry: Refreshing state... (ID: 5856cdbd25bbbfa69a63a869a4e2f328f0bd0fa2e30a7a24c1c86f876495e88e)
docker_container.docbrowse: Creating...
  active:                            "" => "<computed>"
  computed_command.#:                "" => "<computed>"
  computed_dns.#:                    "" => "<computed>"
  computed_domainname:               "" => "<computed>"
  computed_env.#:                    "" => "<computed>"
  computed_hostname:                 "" => "<computed>"
  computed_image:                    "" => "<computed>"
  computed_ports.#:                  "" => "<computed>"
  computed_publish_all_ports:        "" => "<computed>"
  computed_volumes.#:                "" => "<computed>"
  env.#:                             "" => "2"
  env.2496310269:                    "" => "SERVICE_NAME=docbrowse"
  env.3674977573:                    "" => "SERVICE_443_NAME=sdocbrowse"
  freshest_image:                    "" => "<computed>"
  hostname:                          "" => "docbrowse"
  image:                             "" => "nginx-autoindex"
  name:                              "" => "docbrowse"
  ports.#:                           "" => "1"
  ports.3440484515.external:         "" => ""
  ports.3440484515.internal:         "" => "80"
  ports.3440484515.ip:               "" => "0.0.0.0"
  ports.3440484515.protocol:         "" => "tcp"
  publish_all_ports:                 "" => "1"
  volumes.#:                         "" => "1"
  volumes.1174768279.container_path: "" => "/usr/share/nginx/html"
  volumes.1174768279.from_container: "" => ""
  volumes.1174768279.host_path:      "" => "/tank/persist/ramlsnarf/docbase"
  volumes.1174768279.read_only:      "" => "1"
docker_container.docbrowse: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

```
$ terraform show
<snipped>
docker_container.docbrowse:
  id = f86220eca89e86ffd46c1efcb583cbc8d7f06ea0974b0408c6586bb4e463b32a
  active = false
  computed_command.# = 3
  computed_command.0 = nginx
  computed_command.1 = -g
  computed_command.2 = daemon off;
  computed_dns.# = 0
  computed_domainname =
  computed_env.# = 4
  computed_env.1827816 = PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  computed_env.1928297579 = NGINX_VERSION=1.7.10-1~wheezy
  computed_env.2496310269 = SERVICE_NAME=docbrowse
  computed_env.3674977573 = SERVICE_443_NAME=sdocbrowse
  computed_hostname = docbrowse
  computed_image = 4358dccaa0e278b0c952d74c7cd4644f1823abd7b5130d5f8ef43a27fe71cfb8
  computed_ports.# = 0
  computed_publish_all_ports = true
  computed_volumes.# = 2
  computed_volumes.210635644.container_path = /var/cache/nginx
  computed_volumes.210635644.from_container =
  computed_volumes.210635644.host_path = /tank/docker/graph/vfs/dir/0110207e963de64385ddc43be33e474a207b636dffd6bdea9ed5e919c31655fc
  computed_volumes.210635644.read_only = false
  computed_volumes.2645884045.container_path = /usr/share/nginx/html
  computed_volumes.2645884045.from_container =
  computed_volumes.2645884045.host_path = /tank/persist/ramlsnarf/docbase
  computed_volumes.2645884045.read_only = false
  env.# = 2
  env.2496310269 = SERVICE_NAME=docbrowse
  env.3674977573 = SERVICE_443_NAME=sdocbrowse
  freshest_image = 4358dccaa0e278b0c952d74c7cd4644f1823abd7b5130d5f8ef43a27fe71cfb8
  hostname = docbrowse
  image = nginx-autoindex
  name = docbrowse
  ports.# = 1
  ports.3440484515.external = 0
  ports.3440484515.internal = 80
  ports.3440484515.ip = 0.0.0.0
  ports.3440484515.protocol = tcp
  publish_all_ports = true
  volumes.# = 1
  volumes.1174768279.container_path = /usr/share/nginx/html
  volumes.1174768279.from_container =
  volumes.1174768279.host_path = /tank/persist/ramlsnarf/docbase
  volumes.1174768279.read_only = true
<snipped>
```

Now I've changed the image and the running container state, such that `freshest_image` and `active` will no longer be the same, but `terraform plan` shows that nothing needs to happen:

```
$ terraform plan
Refreshing Terraform state prior to plan...

docker_container.ramlsnarf: Refreshing state... (ID: f9b8d4318ecdf9098d6d8af8d49dfdb3e3af17917ca852333b4a3e1e49e1be78)
docker_container.registry: Refreshing state... (ID: 5856cdbd25bbbfa69a63a869a4e2f328f0bd0fa2e30a7a24c1c86f876495e88e)
docker_container.aiab: Refreshing state... (ID: ba242ee105e19406e71e3d323f03f038e6fb5fc0da17ce7ed161ccb0a88e47af)
docker_container.docbrowse: Refreshing state... (ID: f86220eca89e86ffd46c1efcb583cbc8d7f06ea0974b0408c6586bb4e463b32a)

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

And you can see that in fact both of those values have changed:

```
$ terraform show
<snipped>
docker_container.docbrowse:
  id = f86220eca89e86ffd46c1efcb583cbc8d7f06ea0974b0408c6586bb4e463b32a
  active = false
  computed_command.# = 3
  computed_command.0 = nginx
  computed_command.1 = -g
  computed_command.2 = daemon off;
  computed_dns.# = 0
  computed_domainname =
  computed_env.# = 4
  computed_env.1827816 = PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  computed_env.1928297579 = NGINX_VERSION=1.7.10-1~wheezy
  computed_env.2496310269 = SERVICE_NAME=docbrowse
  computed_env.3674977573 = SERVICE_443_NAME=sdocbrowse
  computed_hostname = docbrowse
  computed_image = 4358dccaa0e278b0c952d74c7cd4644f1823abd7b5130d5f8ef43a27fe71cfb8
  computed_ports.# = 0
  computed_publish_all_ports = true
  computed_volumes.# = 2
  computed_volumes.210635644.container_path = /var/cache/nginx
  computed_volumes.210635644.from_container =
  computed_volumes.210635644.host_path = /tank/docker/graph/vfs/dir/0110207e963de64385ddc43be33e474a207b636dffd6bdea9ed5e919c31655fc
  computed_volumes.210635644.read_only = false
  computed_volumes.2645884045.container_path = /usr/share/nginx/html
  computed_volumes.2645884045.from_container =
  computed_volumes.2645884045.host_path = /tank/persist/ramlsnarf/docbase
  computed_volumes.2645884045.read_only = false
  env.# = 2
  env.2496310269 = SERVICE_NAME=docbrowse
  env.3674977573 = SERVICE_443_NAME=sdocbrowse
  freshest_image = d1cf83baff830327d5f8258170ec9c7dabb0f794be678c135bcb479735dffc4e
  hostname = docbrowse
  image = nginx-autoindex
  name = docbrowse
  ports.# = 1
  ports.3440484515.external = 0
  ports.3440484515.internal = 80
  ports.3440484515.ip = 0.0.0.0
  ports.3440484515.protocol = tcp
  publish_all_ports = true
  volumes.# = 1
  volumes.1174768279.container_path = /usr/share/nginx/html
  volumes.1174768279.from_container =
  volumes.1174768279.host_path = /tank/persist/ramlsnarf/docbase
  volumes.1174768279.read_only = true
<snipped>
```

**Comment by mitchellh** [comment] 2015-03-04 01:22
This is working as I'd expect: `ForceNew` says that when the value is set, a new creation will be forced. This only takes place when the value is set in the configuration. When you do a `refresh`, it is updating the state to match the real world state. 

I'm not sure how it was doing what you expected before, but this is certainly the correct behavior in this case. 

I'll tag this as "thinking" to brainstorm how to come up with the solution you want, which I'm guessing is to recycle the container if there is a new image.

**Comment by jefferai** [comment] 2015-03-04 12:39
What you just described is not how it had behaved for me in the past nor what has been suggested to me (by @phinze for instance) in the past in chat about how to accomplish this.

I'm not sure how the configuration is relevant here. Computed values aren't supposed to be set in the configuration. That's the point, right?

Really ForceNew isn't the problem here. The problem is that action is not being taken when the Computed value changes. ForceNew should only affect which action, not whether it happens.

**Comment by mitchellh** [comment] 2015-03-04 16:36
I apologize for the mixed signals, but this was never supposed to work like this in its current state, hence I think the tags thinking and enhancement are still correct. I'm not disagreeing with you that it is useful, it just wasn't built to work this way and we need to think about how to make it work. 

You're right, ignore my comment about config, I didn't notice that this doesn't have `Optional` or `Required` set. But despite that, my comment above still stands that this was a permutation we didn't plan for. 

So the tag will sit, and we'll get to this when we get a chance.

This isn't an easy thing to make just work. The issue is that when you do a refresh (`Read` operation), it is _overwriting_ the existing state to sync it with the remote world. We never compare those states. The only way a diff is ever made is comparing config to the state, not state to state, or anything of that sort. So this is a fundamental change in Terraform and requires a lot more design thought.

Thanks for the report, we agree its useful!

**Comment by jefferai** [comment] 2015-03-04 21:13
I had a long conversation on IRC with @phinze about this today and (along with a lot of philosophical discussion about Terraform) we agreed upon a way forward for now (which basically relies on making a docker_image resource, which will only do the R part of CRUD) -- there are some discoverability issues with doing the right thing here, but decent documentation and examples should be able to help.

Without rehashing the entire conversation, I do encourage you to think of Terraform as more than just a way to instrument production hardware -- in fact, we are *not* going to be using it in production in favor of a Docker cluster manager, but we *do* want to use it in development to help developers and QA manage their resources for development and test. This might not be the normal use-case thought of for Terraform, but with Docker providing a works-the-same ideal from dev through production, a Docker provider really can (and should) be targeting the full stack. (Of course, the provider can *also* work on production hosts in a number of ways -- uploading config files and running Terraform locally, setting DOCKER_HOST to a tcp:// value, using Swarm, etc. -- the ways you'd normally think of using Terraform).

The other thing he asked me was why Terraform instead of Fig (now Compose). There are several answers to this, but one of the most important was "because we thought it worked this way" based on Terraform's claim of idempotency. In truth, Terraform is sort of half-idempotent: given the same configuration file and no change in resource state it's idempotent, but it can't allow for a workflow where same input always results in the same output. I understand the arguments that "Terraform isn't Ansible", but that doesn't mean there can't be some overlap. Ansible has a Docker module too, but we'd *much* rather be using Terraform -- and if you think about it from a developer/QA perspective and how Terraform is configured and run vs. Ansible, it is probably immediately clear why.

**Comment by phinze** [comment] 2015-11-23 22:15
Circling around to some issues here, restating the missing behavior for clarification.

Given a field defined in the schema as:

```go
"foo": &schema.Schema{
  // ...
  Computed: true,
  ForceNew: true,
}
```

A `terraform refresh` that detects a _change_ to "foo" should trigger replacement of the resource on the following `terraform apply`.

Given a lack of `ForceNew`:

```go
"foo": &schema.Schema{
  // ...
  Computed: true,
}
```

A `terraform refresh` that detects a change to "foo" should result in the Update function for that resource being called on the following `terraform apply` (I think?).

@mitchellh @jefferai Let me know if that sounds right to you.

**Comment by mitchellh** [comment] 2016-11-10 02:48
Its been awhile and hilariously we all work for HashiCorp now.

This hasn't come up since and I still believe a year later that the current behavior is right. Closing!

**Closed by mitchellh** 2016-11-10 02:48 UTC
Labels: core, enhancement, thinking
