### ISSUE TITLE
Running "terraform -version" with CHECKPOINT_DISABLE set to 1 on windows takes long and makes network requests

### ISSUE THREAD

**Issue by grazioli-nc** [hashicorp/terraform#29758] opened 2021-10-14 11:17 UTC
### Terraform Version

```
Terraform v1.0.8
on windows_amd64

Windows 10 Enterprise / 19043.1237
```

### Terraform Configuration Files

```terraform
# C:\Users\%username%\AppData\Roaming\terraform.rc
disable_checkpoint = true
```

### Debug Output

```bash
PS C:\Users\%username%> terraform -version
2021-10-14T12:53:46.389+0200 [DEBUG] Adding temp file log sink: C:\Users\%username%\AppData\Local\Temp\terraform-log907791419
2021-10-14T12:53:46.390+0200 [INFO]  Terraform version: 1.0.8
2021-10-14T12:53:46.390+0200 [INFO]  Go runtime version: go1.16.4
2021-10-14T12:53:46.390+0200 [INFO]  CLI args: []string{"C:\\Windows\\system32\\terraform.exe", "-version"}
2021-10-14T12:53:46.390+0200 [TRACE] Stdout is a terminal of width 206
2021-10-14T12:53:46.390+0200 [TRACE] Stderr is a terminal of width 206
2021-10-14T12:53:46.390+0200 [TRACE] Stdin is a terminal
2021-10-14T12:53:46.392+0200 [DEBUG] Attempting to open CLI config file: C:\Users\%username%\AppData\Roaming\terraform.rc
2021-10-14T12:53:46.392+0200 [INFO]  Loading CLI configuration from C:\Users\%username%\AppData\Roaming\terraform.rc
2021-10-14T12:53:46.403+0200 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-10-14T12:53:46.403+0200 [DEBUG] ignoring non-existing provider search directory C:\Users\%username%\AppData\Roaming\terraform.d\plugins
2021-10-14T12:53:46.404+0200 [DEBUG] ignoring non-existing provider search directory C:\Users\%username%\AppData\Roaming\HashiCorp\Terraform\plugins
2021-10-14T12:53:46.404+0200 [INFO]  Checkpoint disabled. Not running.
2021-10-14T12:53:46.404+0200 [INFO]  CLI command args: []string{"version", "-version"}
Terraform v1.0.8
on windows_amd64
```

### Crash Output

/

### Expected Behavior

Running `terraform -version` inside `cmd.exe` or `powershell.exe` with `CHECKPOINT_DISABLE` set to `1` should show immediately the used terraform version and not doing some network calls as documented here:
https://www.terraform.io/docs/cli/commands/index.html#upgrade-and-security-bulletin-checks

### Actual Behavior

Running `terraform -version` inside `cmd.exe` or `powershell.exe` with `CHECKPOINT_DISABLE` set to `1` takes 90s until showing the output and does some network calls.

![image](https://user-images.githubusercontent.com/75689648/137307021-66e4fb09-e7c2-41d7-9eec-130eaefea367.png)

### Steps to Reproduce

Run `terraform -version` inside `cmd.exe` or `powershell.exe` and take a look into `Procmon64.exe`.
![image](https://user-images.githubusercontent.com/75689648/137305407-200c87f8-da1d-49aa-97e4-b03ce0d9020b.png)

### Additional Context

/

### References

/

**Comment by grazioli-nc** [comment] 2021-10-15 08:35
Hi @alisdair, thanks for the quick response. We are able to reproduce the issue on other company computers. But you are right, seems to be an internal issue with our security software. We are investigating internally for the root cause and I will drop a short update here, as soon as we were able to fix the issue. Might could be helpful for others.

**Comment by apparentlymart** [comment] 2021-11-17 00:19
Hi @grazioli-nc!

Thanks for confirming that it seems to be caused by security software. Unfortunately that is a common problem, because security software often hooks into Windows system calls in unpredictable ways, which can cause it to seem like Terraform is running code that is not part of its process image.

I'm going to close this issue just to reflect that you found a solution to it. If you'd still like to add some more information here then please feel free! Our bot will lock the issue about a month from now, but until then you should be able to still add comments even though the issue is closed. Thanks!

**Closed by apparentlymart** 2021-11-17 00:19 UTC
Labels: bug, windows, waiting-response, waiting for reproduction
