### ISSUE TITLE
null_resource in state file but not in state list command

### ISSUE THREAD

**Issue by jbruett** [hashicorp/terraform#29025] opened 2021-06-24 00:36 UTC
### Terraform Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.46.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

### Terraform Configuration Files

```terraform
# resource "null_resource" "rds_cluster_s3import" {
#   provisioner "local-exec" {
#     command = "aws rds add-role-to-db-cluster --db-cluster-identifier ${module.aurora_cluster.this_rds_cluster_id} --feature-name s3Import --role-arn ${aws_iam_role.life-it-awd-role.arn} --region ${var.primary_region}"
#   }
# }
```

### Expected Behavior

We can cleanly init the config

### Actual Behavior
```
Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Finding hashicorp/random versions matching "3.0.1"...
- Installing hashicorp/aws v3.46.0...
- Installed hashicorp/aws v3.46.0 (self-signed, key ID 34365D9472D7468F)
- Installing hashicorp/random v3.0.1...
- Installed hashicorp/random v3.0.1 (self-signed, key ID 34365D9472D7468F)
<info removed for brevity>
Error: Could not load plugin

Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/hashicorp/null" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/null"
```

### Steps to Reproduce

1. `terraform init --upgrade`

### Additional Context

When I pull the repo that holds this code locally and run `terraform state list` it doesn't show the null_resource.  If I run `state pull` I can find the resource in state

```
    {
      "mode": "managed",
      "type": "null_resource",
      "name": "rds_cluster_s3import",
      "provider": "provider[\"registry.terraform.io/hashicorp/null\"]",
      "instances": []
    },
```

I also cannot run a `state rm` against the resource

At this point I believe the only option is to do a `state pull`, manually edit the file and then `state push` it back so that TF doesn't make any mistake about the existence of that resource

**Comment by jbardin** [comment] 2021-06-24 17:35
Hi @jbruett,

It looks like the state has an an empty resource which was not cleaned out correctly once all instances were removed. I do see that you are using an old version of 0.14, and would suggest at least updating to the final release of 0.14 to resolve any issues known at that time. With the latest 0.14, you should be able to run refresh or apply, which may write a new state and clean out that empty resource, but the details which clean that out may not have been included intil 1.0.

If you are not able to update terraform at the moment, then manually removing that empty resource object from the state could be an acceptable workaround.

Since this should no longer be a problem with the current version of Terraform, I'm going to close this out. If you can still reproduce this problem after updating Terraform, feel free to reply here, open a new issue or ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-06-24 17:35 UTC
Labels: bug, new
