### ISSUE TITLE
Null provider is not downloaded

### ISSUE THREAD

**Issue by johan-horst** [hashicorp/terraform#27160] opened 2020-12-07 12:18 UTC
Hi there,

### Terraform Version
0.13.4

### Debug Output

Terraform Init
Initializing modules...
- connect-forwarder in modules\cfinternalapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for fhir-streamer-proxy...
- fhir-streamer-proxy in .terraform\modules\fhir-streamer-proxy\Terraform\modules\cfapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for kafdrop...
- kafdrop in .terraform\modules\kafdrop\Terraform\modules\cfapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for kafka-api...
- kafka-api in .terraform\modules\kafka-api\Terraform\modules\cfapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for logging...
- logging in .terraform\modules\logging\Terraform\modules\logging

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding philips-software/hsdp versions matching ">= 0.6.8"...
- Finding philips-labs/cloudfoundry versions matching ">= 0.1206.0, >= 0.1206.0, >= 0.1206.0, >= 0.1206.0, >= 0.1206.0, >= 0.1206.0"...
- Finding latest version of hashicorp/random...
- Installing philips-software/hsdp v0.7.3...
- Installed philips-software/hsdp v0.7.3 (self-signed, key ID C0E4EB79E9E6A23D)
- Installing philips-labs/cloudfoundry v0.1206.2...
- Installed philips-labs/cloudfoundry v0.1206.2 (self-signed, key ID C0E4EB79E9E6A23D)
- Installing hashicorp/random v3.0.0...
- Installed hashicorp/random v3.0.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/random: version = "~> 3.0.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraform Get Update
- connect-forwarder in modules\cfinternalapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for fhir-streamer-proxy...
- fhir-streamer-proxy in .terraform\modules\fhir-streamer-proxy\Terraform\modules\cfapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for kafdrop...
- kafdrop in .terraform\modules\kafdrop\Terraform\modules\cfapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for kafka-api...
- kafka-api in .terraform\modules\kafka-api\Terraform\modules\cfapp
Downloading git@github.com:philips-internal/peha-hsdp-tf.git?ref=v0.1.1 for logging...
- logging in .terraform\modules\logging\Terraform\modules\logging
Terraform Validate

Success! The configuration is valid, but there were some validation warnings as shown above.

Terraform Create/Select Workspace
Switched to workspace "testing".
Terraform Refresh

Error: Could not load plugin

Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/hashicorp/null" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/null"

### Expected Behavior
I should not need to reinitialize.

### Actual Behavior
I am asked to reinitialize.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`

### Workaround

In order to continue I found a workaround by adding the following to my 
- provider.tf (provider definitions)
```
provider "null"{
}
 ```

- terraform.tf (contains list of all required providers)
```
null = {
     source = "hashicorp/null"
}
```

**Comment by alisdair** [comment] 2020-12-09 15:38
Hi @johanhorst-at-philips, thanks for reporting this. We can't reproduce this issue without more details. Can you supply a small configuration which demonstrates this issue?

Please also let us know what the output of `terraform providers` shows. This should indicate where the requirement for the null provider is coming from. Thanks!

**Comment by mildwonkey** [comment] 2021-04-30 16:03
I'm going to close this, since there hasn't been a response, but if you are still experiencing a problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by mildwonkey** 2021-04-30 16:03 UTC
Labels: bug, v0.13, waiting for reproduction, waiting-response
