### ISSUE TITLE
Allow variables in module's source field

### ISSUE THREAD

**Issue by iloveicedgreentea** [hashicorp/terraform#26619] opened 2020-10-17 02:08 UTC
### Current Terraform Version
```
Terraform v0.13.4
```

### Use-cases
Using separate modules but all having the same variables. I can make a map variable with the key of each module name and then only have one module resource instead of one per module. I want the source field to be able to use each.key so I can programmatically generate the module source from the variable key e.g. each.key == "module1" so "./modules/${each.key}" would become ./modules/module1 

### Proposal
```hcl
module "function" {
  for_each = var.enabled_modules
  source   = "./modules/${each.key}"
```

**Comment by pkolyvas** [comment] 2020-10-20 23:14
I'm going to close this as a duplicate of #25587.

**Closed by pkolyvas** 2020-10-20 23:14 UTC
Labels: enhancement, new
