### ISSUE TITLE
Cancelling a terraform plan when using powershell core in VS Code

### ISSUE THREAD

**Issue by jshinevar** [hashicorp/terraform#26596] opened 2020-10-15 15:37 UTC
I have noticed that when I am testing my code if I try to cancel a terraform plan by using ctrl-c (on a Windows 10 Machine using VS Code and Powershell core) the terminal itself crashes and closes.  I would think that if a command is canceled it should gracefully quit and return to the command prompt.

**Comment by apparentlymart** [comment] 2020-10-17 00:39
Hi @jshinevar! Sorry for the odd behavior, and thanks for reporting it.

Unfortunately with what you've shared here I'm not sure how to proceed with this issue. Taking what you said at face value it sounds like you're describing a bug in your terminal or in Visual Studio Code; Terraform doesn't itself have any control over what happens after its process terminates.

If the behavior you are seeing seems to be caused by Terraform rather than by the terminal, can you say a little more about what leads you to that conclusion, and how we might see the same behavior? Since this case involves multiple pieces of software working together, perhaps an efficient way to understand what you're seeing here would be for you to share a screencast video of it, which will hopefully give us a better foundation for digging further into the problem.

Thanks again!

**Comment by apparentlymart** [comment] 2020-12-02 02:09
Hi @jshinevar,

I didn't hear from you again after my previous question, so I'm going to close this in the hope that you found an answer elsewhere. If you want to discuss this further or have any other questions, please start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!

**Closed by apparentlymart** 2020-12-02 02:09 UTC
Labels: bug, new, waiting-response
