### ISSUE TITLE
crash on "unexpected EOF" error on v0.11.8 on a custom provider

### ISSUE THREAD

**Issue by jp-ig1** [hashicorp/terraform#19218] opened 2018-10-30 11:52 UTC
Hello,

I am doing a custom provider to interact with an OpenNebula cloud. A provider already exists but it is old and don't use Go bindings from OpenNebula.
I faced an issue when I run my very simple configuration file. It failsafter template creation and during VM creation.
It seems the issue is locatied in the provider plugin (wrong casting between int and uint) from the crash.log file.

It is my first issue on Terraform. If I missed something I am able to add information.

Thank you for your help

Regards

Jean-Philippe

### Terraform Version

```
2018/10/30 12:27:37 [INFO] Terraform version: 0.11.8  7a5c1d221ac209bbac66947c369815cd9ca70ed5
```

### Terraform Configuration Files

```
provider "opennebula" { 
    endpoint = "http:/XXXXXXXXX" 
    username = "XXXXXXXXX" 
    password = "XXXXXXXXX" 
} 
 
data "template_file" "bsmall" { 
    template = "${file("bsmall_template.txt")}" 
    vars = { 
        CUSTOM_ATTRIBUTE_VALUE = "bsmall" 
    } 
} 
 
resource "opennebula_template" "tpl" { 
    name = "jp bsmall" 
    description = "${data.template_file.bsmall.rendered}" 
    permissions = "644" 
} 
 
resource "opennebula_vm" "vm" { 
    name = "jp bsmall vm" 
    template_id = "${opennebula_template.tpl.id}" 
    permissions = "644" 
} 
 
output "bsmall_template_id" { 
  value = "${opennebula_template.tpl.id}" 
} 
 
output "bsmall_template_desc" { 
  value = "${opennebula_template.tpl.description}" 
} 
 
output "bsmall_vm_id" { 
  value = "${opennebula_vm.vm.id}" 
} 

```

### Crash Output

https://gist.github.com/jp-ig1/2434c206ae2e2693e9f14e301a5af16e

### Expected Behavior

Template created
VM is correctly created as template instantiation on OpeN Nebula environment

### Actual Behavior

Template is created
VM is not instantiate from template because of crash of terraform

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Additional Context

I am currently doing a custom OpenNebula provider on v0.11 Terraform release. 
I amr running command manually as I just started my development

### References

I am not sure. If there are, I am sorry to reopen a similar case.

**Comment by jp-ig1** [comment] 2018-10-30 14:03
Update: I fix issue in my provider. However a crash is not normal, That is why I let it open

**Comment by snimark** [comment] 2018-11-06 18:58
i have the same thing for **terraform 0.11.10** and **provider aws 1.42.0**.

i was getting this with terraform 0.11.8 and provider aws 1.42.0. i deleted my `.terraform` directory, upgraded my terraform to 0.11.10, and `terraform init` the directory again.

crash log: [crash.log](https://github.com/hashicorp/terraform/files/2554608/crash.log)

what was changed in the provider to fix this?

**Comment by apparentlymart** [comment] 2018-11-06 20:22
Hi @jp-ig1!

Terraform expects providers to be implemented correctly and not crash. "Unexpected EOF" is the expected behavior if a provider process crashes, since it will not cleanly close the communication channel between Terraform Core and the provider. As you noticed, the bug is directly within the provider code (per the stack trace) and so the only resolution here is to fix the provider code to be correct.

Terraform runs provider plugins as child processes so that if they crash Terraform can still handle the error cleanly and ensure that the final state is saved, but it is always the responsibility of the provider code to behave correctly and not crash. Since Terraform's behavior here is as expected, I'm going to close this out. Thanks for reporting it to make sure, though!

---

@snimark per the above, a panic within a provider should generally be recorded in an issue within that provider's own repository, but I happen to know in that particular case that the issue you've hit is within the provider SDK (a shared library used by all of the providers) and has been fixed in `master`, so will be included in the forthcoming provider releases that will coincide with the release of Terraform Core v0.12.0.

The usual cause of that crash is either that you've assigned a string value where a map was expected or you've used attribute syntax (with an equals sign) where block syntax is expected, both of which are not being caught by validation due to the bug that has since been fixed. If you need further guidance on what might be incorrect in your configuration, please open an issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) including the relevant parts of your configuration and the AWS provider team should be able to help identify the problem.

**Closed by apparentlymart** 2018-11-06 20:22 UTC

**Comment by snimark** [comment] 2018-11-06 20:53
thanks for the tip here. i will check my scripting to see if i have one of the two scenarios you pointed out. i appreciate the explanation to all this. it is very helpful.

**Comment by jp-ig1** [comment] 2018-11-07 08:20
Hi @apparentlymart ,

Thank you for taking time to answer to my question. Indeed, I fixed my issue and I never faced this behavior. I understand better Terraform behavior thanks to your message.

Regards

Jean-Philippe
