### ISSUE TITLE
provider/aws: Add support for Elasticache Read Replica

### ISSUE THREAD

**Issue by sukritpol** [hashicorp/terraform#3289] opened 2015-09-20 06:03 UTC
i want to use elasticache  read replica but bot support 
how can i user this resource

**Comment by radeksimko** [comment] 2015-09-20 08:11
See https://github.com/hashicorp/terraform/pull/2945

**Comment by sukritpol** [comment] 2015-09-21 03:01
thank radeksimko  
I mean not found official terraform 
I must add code form link and compile  it work

**Comment by stack72** [comment] 2016-07-27 18:59
Closing this as a duplicate of #4361

I am going to track the progress on this in that ticket going forward.

**Closed** 2016-07-27 20:02 UTC
Labels: enhancement, new-resource, provider/aws
