### ISSUE TITLE
tf0.13.0 Invalid resource instance data in state (aws_instance)

### ISSUE THREAD

**Issue by julienpierini** [hashicorp/terraform#25897] opened 2020-08-18 12:54 UTC
Hi,

Since the new terraform version 0.13.0, I get an error on plan, destroy and apply.

I use the public module : https://github.com/terraform-aws-modules/terraform-aws-ec2-instance (version 2.0 and 2.15)
config used : 
```
terraform {
  required_version = ">= 0.13.0, < 0.14"

  required_providers {
    aws = ">= 3.0, < 4.0"
  }
}
```
Error message :
```
Error: Invalid resource instance data in state

  on .terraform/modules/ec2/terraform-aws-ec2-instance-2.15.0/main.tf line 5:
   5: resource "aws_instance" "this" {

Instance module.ec2.aws_instance.this[0] data could not be decoded from the
state: unsupported attribute "network_interface_id".
```

Resolution :
Use prior version of terraform, works with 1.29.0 :
```
terraform {
  required_version = ">= 0.12.9, < 0.14"

  required_providers {
    aws = ">= 3.0, < 4.0"
  }
}
```

**Comment by mildwonkey** [comment] 2020-08-19 15:56
Hi @julienpierini , I'm sorry you're experiencing this behavior.

This appears to be a duplicate of #25752, which has been fixed. The fix will be included in v0.13.1, which is not yet released but we expect to do so next week. 

If you still have a problem after the next release, please open a new issue. Thank you!

**Closed by mildwonkey** 2020-08-19 15:56 UTC
Labels: bug, duplicate
