### ISSUE TITLE
Empty dynamic block being generated when conditional is an empty map check

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform#24496] opened 2020-03-29 15:30 UTC
Version: v0.12.23

code:
```hcl
variable environment {
  default = {}
}


resource aws_lambda_function this {
  function_name = "test-function"
  s3_bucket = "test-bucket"
  s3_key = "test-function.zip"
  handler = "lambda_function.lambda_handler"
  role = "test-role-arn"
  description = "Managed by Terraform"
  runtime = "python3.8"

  dynamic environment {
    for_each = var.environment != {} ? ["1"] : []

    content {
      variables = var.environment
    }
}
```

tf plan output:
```hcl
+ environment {}
```

expected: no empty environment block being created

if I replace variable.environment default to [] and dynamic.environment.for_each to `var.environment != [] ? ["1"] : []` then it works as expected

Is there something happening here that I'm not understanding, or is this a bug?

**Comment by danieldreier** [comment] 2020-04-01 01:30
@lijok as-is, the provided code produces a `Blocks of type "dynamic" are not expected here.` error. Can you please provide a more complete example that produces the output you describe?

**Comment by lijok** [comment] 2020-04-01 08:09
updated with full resource

**Comment by danieldreier** [comment] 2020-04-01 18:41
@lijok thanks! I'm not sure I understand the context you're expecting this to run in. I ran the following:
Case 1:
```
variable environment {
  default = {}
}

provider "aws" {
  region  = "us-west-2"
}

resource aws_lambda_function this {
  function_name = "test-function"
  s3_bucket = "test-bucket"
  s3_key = "test-function.zip"
  handler = "lambda_function.lambda_handler"
  role = "test-role-arn"
  description = "Managed by Terraform"
  runtime = "python3.8"

  dynamic environment {
    for_each = var.environment != {} ? ["1"] : []

    content {
      variables = var.environment
    }
  }
}
```
and got the following output:
```
terraform-v0.12.23 plan  -out tf.plan      
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-west-2

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_lambda_function.this will be created
  + resource "aws_lambda_function" "this" {
      + arn                            = (known after apply)
      + description                    = "Managed by Terraform"
      + function_name                  = "test-function"
      + handler                        = "lambda_function.lambda_handler"
      + id                             = (known after apply)
      + invoke_arn                     = (known after apply)
      + last_modified                  = (known after apply)                                                                                                                                                 + memory_size                    = 128
      + publish                        = false
      + qualified_arn                  = (known after apply)                                                                                                                                                 + reserved_concurrent_executions = -1
      + role                           = "test-role-arn"
      + runtime                        = "python3.8"
      + s3_bucket                      = "test-bucket"
      + s3_key                         = "test-function.zip"
      + source_code_hash               = (known after apply)
      + source_code_size               = (known after apply)
      + timeout                        = 3
      + version                        = (known after apply)

      + tracing_config {
          + mode = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------
```

For the second case, the code is:
```
variable environment {
  default = []
}

provider "aws" {
  region  = "us-west-2"
}

resource aws_lambda_function this {
  function_name = "test-function"
  s3_bucket = "test-bucket"
  s3_key = "test-function.zip"
  handler = "lambda_function.lambda_handler"
  role = "test-role-arn"
  description = "Managed by Terraform"
  runtime = "python3.8"

  dynamic environment {
    #for_each = var.environment != {} ? ["1"] : []
    for_each = var.environment != [] ? ["1"] : []

    content {
      variables = var.environment
    }
  }
}
```
In the second case, my output is:
```
terraform-v0.12.23 plan -out tf.plan

provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-west-2

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_lambda_function.this will be created
  + resource "aws_lambda_function" "this" {
      + arn                            = (known after apply)
      + description                    = "Managed by Terraform"
      + function_name                  = "test-function"
      + handler                        = "lambda_function.lambda_handler"
      + id                             = (known after apply)
      + invoke_arn                     = (known after apply)
      + last_modified                  = (known after apply)
      + memory_size                    = 128
      + publish                        = false
      + qualified_arn                  = (known after apply)
      + reserved_concurrent_executions = -1
      + role                           = "test-role-arn"
      + runtime                        = "python3.8"
      + s3_bucket                      = "test-bucket"
      + s3_key                         = "test-function.zip"
      + source_code_hash               = (known after apply)
      + source_code_size               = (known after apply)
      + timeout                        = 3
      + version                        = (known after apply)

      + tracing_config {
          + mode = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
------------------------------------------------------------------------
```
These look the same to me. Are you working on the case where the resource already exists? I think I'm probably just not understanding what you're running - can you please be more explicit?

**Comment by lijok** [comment] 2020-04-01 19:11
@danieldreier Thanks for looking into this
I tried to reproduce this from ground up, and the unexpected behaviour happens with your Case 1 if you add `type = map(string)` to the variable environment

```hcl
➜  tf ls
main.tf
➜  tf cat main.tf
variable environment {
  type = map(string)
  default = {}
}

provider "aws" {
  region  = "us-west-2"
}

resource aws_lambda_function this {
  function_name = "test-function"
  s3_bucket = "test-bucket"
  s3_key = "test-function.zip"
  handler = "lambda_function.lambda_handler"
  role = "test-role-arn"
  description = "Managed by Terraform"
  runtime = "python3.8"

  dynamic environment {
    for_each = var.environment != {} ? ["1"] : []

    content {
      variables = var.environment
    }
  }
}
➜  tf      
➜  tf terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_lambda_function.this will be created
  + resource "aws_lambda_function" "this" {
      + arn                            = (known after apply)
      + description                    = "Managed by Terraform"
      + function_name                  = "test-function"
      + handler                        = "lambda_function.lambda_handler"
      + id                             = (known after apply)
      + invoke_arn                     = (known after apply)
      + last_modified                  = (known after apply)
      + memory_size                    = 128
      + publish                        = false
      + qualified_arn                  = (known after apply)
      + reserved_concurrent_executions = -1
      + role                           = "test-role-arn"
      + runtime                        = "python3.8"
      + s3_bucket                      = "test-bucket"
      + s3_key                         = "test-function.zip"
      + source_code_hash               = (known after apply)
      + source_code_size               = (known after apply)
      + timeout                        = 3
      + version                        = (known after apply)

      + environment {}

      + tracing_config {
          + mode = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

**Comment by danieldreier** [comment] 2020-04-01 23:46
Great! I've reproduced this on my side. With `type = map(string)` added in, the extra empty environment shows up. Without it, none. I'm also curious about this, and will escalate this for engineering input because I'm in over my head on understanding why this is happening. 

While I'm waiting for that input, can you help me understand whether this is causing you a problem  or if it's more of a curiosity? It looks cosmetic to me, but maybe there's something in your workflow that makes this more of a problem than I'm understanding.

**Comment by lijok** [comment] 2020-04-02 08:16
Thanks @danieldreier 
As I'm new to terraform, it was a problem for an hour or so as I thought I was misunderstanding how the dynamic block worked, but since then I've just changed the conditional to use a list and the default for the variable to be a null and it works just fine, so at this point, it's more of a curiosity

**Comment by danieldreier** [comment] 2020-04-02 23:11
Thanks for clarifying, @lijok. Although that extra empty environment is an oddity, I don't think this quite constitutes a defect since it doesn't cause any practical problems, and so I'm going to close this out.

**Closed by danieldreier** 2020-04-02 23:11 UTC
Labels: additional triage needed, v0.12
