### ISSUE TITLE
The "count" value depends on resource attributes that cannot be determined until apply. Looks like a bug

### ISSUE THREAD

**Issue by borei74** [hashicorp/terraform#32993] opened 2023-04-06 01:17 UTC
### Terraform Version

```shell
[dan@borei soleks]$ terraform version
Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.76.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/vault v3.14.0

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

I have terraform module to provision group of the servers (nomad agents in my case)
```
module "nomad-servers" {
  source = "../../modules/nomad/agent-group"

  name_prefix = "nomad-agent"
  agent_type = "server"
  
  vpc_id = module.nomad-vpc.vpc_id
  group_size = 3
  ami_name = "nomad-base-image-202302060605"
  instance_type = "t3.micro"
  subnets = module.nomad-vpc.public_subnets_ids

  target_group_arn = module.nomad-servers-http-tg.arn
  target_group_arn_p = true
....
```
Using **target_group_arn** variable as following:
```
variable "target_group_arn" {
  description = "Nomad agent target group ARN"
  type = string
  default = ""
}

resource "aws_lb_target_group_attachment" "nomad-agent-tg-attachment" {
 # count = var.target_group_arn_p  ?  var.group_size*length(var.subnets) : 0
 count = var.target_group_arn != null  ?  var.group_size*length(var.subnets) : 0
  
  target_group_arn = var.target_group_arn
  target_id = aws_instance.nomad-agent-instance[count.index].id
}
```

### Debug Output

Plan: 33 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid count argument
│
│   on ../../modules/nomad/agent-group/main.tf line 82, in resource "aws_lb_target_group_attachment" "nomad-agent-tg-attachment":
│   82:  count = var.target_group_arn != null  ?  var.group_size*length(var.subnets) : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the
│ -target argument to first apply only the resources that the count depends on.
╵

### Expected Behavior

I don't see any reason why **count** is not defined. Changing calculation for **count** to different expression:
```
count = var.target_group_arn_p  ?  var.group_size*length(var.subnets) : 0
```
works as expected.
But **var.target_group_arn** and **var.target_group_arn_p** are absolutely identical from the language semantic - they are both input variables for the module. The only difference is **var.target_group_arn** is used in the code.

### Actual Behavior

**count** can't be defined.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by liamcervante** [comment] 2023-04-06 09:16
Hi @borei74, thanks for filing this!

I see your definitions here:
```
  target_group_arn = module.nomad-servers-http-tg.arn
  target_group_arn_p = true
```

The value for `target_group_arn_p` is known during the planning phase, while the value for `target_group_arn` relies on the output of another module which (I imagine) will be be computing the ARN for the target group during the apply phase. What Terraform is saying here is that it doesn't know whether `target_group_arn` is null or not during the plan as it has to wait for the value from somewhere else, and therefore it cannot tell whether the count should be 0 or if it should be `var.group_size*length(var.subnets)` and therefore can't create a complete plan for you.

If you used the `-target=` argument to create the resources within the `nomad-servers-http-rg` module first, and then attempted a complete plan again it should succeed. Or if you commented out/removed the problematic module, ran a full plan/apply once, then reintroduced the module and applied again, you should see a successful plan.

I'm going to close this issue as working as intended, but feel free to reopen it if I've made an incorrect assumption somewhere. And I'll keep monitoring it if you have any follow up questions!

**Closed by liamcervante** 2023-04-06 09:16 UTC
Labels: bug, new
