### ISSUE TITLE
Moving resources to modules can result in "Provider produced inconsistent result after apply"

### ISSUE THREAD

**Issue by mattlqx** [hashicorp/terraform#25003] opened 2020-05-20 17:22 UTC
We've hit this on two different providers (vault and aws) this last week as we've created some resources to do something in a project and then see a clear pattern and move those resources to a module. Converting the project(s) that use the standalone resources to the module can cause these provider inconsistency errors as Terraform doesn't recognize these resources to be the same thing and then tries to delete the standalone resources and create the modularized resources in parallel, which can often lead to the creation happening first and the delete occurring after and causes the inconsistency when later referenced.

### Terraform Version
```
Terraform v0.12.25
+ provider.aws v2.61.0
+ provider.bigip v1.1.0
+ provider.chef v0.2.0
+ provider.consul v2.6.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.vault v2.10.0
+ provider.vsphere v1.18.1
```

### Terraform Configuration Files
Here's an example of one of the resources that we moved to its own module (there are other resources too, but this is the one that leads to inconsistency from the destroy/create race):

```hcl
resource "vault_approle_auth_backend_role" "approle" {
  provider = vault.local
  count    = var.instance_count > 0 ? 1 : 0

  backend            = "approle"
  role_name          = "instance-${lower(local.role)}-${var.region}-${var.service_provider}"
  token_policies     = concat(["chef"], var.vault_policies)
  secret_id_ttl      = 0
  secret_id_num_uses = 0
  token_ttl          = 600
}
```

### Debug Output
Relevant part of the run output is:
```
module.instance.vault_approle_auth_backend_role.approle[0]: Destroying... [id=auth/approle/role/instanceA]
module.instance.module.vault_approle.vault_approle_auth_backend_role.approle[0]: Creating...
module.instance.vault_approle_auth_backend_role.approle[0]: Destruction complete after 0s
```

And the run fails with:
```
Error: Provider produced inconsistent result after apply

When applying changes to
module.instance.module.vault_approle.vault_approle_auth_backend_role.approle[0],
provider "registry.terraform.io/-/vault" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior
Terraform would hopefully have recognized that the resource it was trying to create was the same as the resource it was trying to destroy. Many resources in the Terraform universe effectively have their name as their primary key. The `vault_approle_auth_backend_role` resource is one of those.

### Actual Behavior
Terraform tries to destroy and create the same resource in parallel leading to unpredicable results that Terraform identifies but fails to recover from. In some cases, the state must be altered to remove the resource as it can cause plan failures if like in this case the resource is referenced elsewhere as part of a tuple.

### Steps to Reproduce
1. Create a resource that a provider identifies by name as its primary key (i.e. a resource that ends up being identified by its name).
1. Apply the project.
1. Move the resource to a module and include it in the same project.
1. Apply the project again.

### Additional Context
I recognize this is a hard problem to solve and the official recommendation is probably to remove the resources first with an apply and then include the module and apply again. Or use a different name/identifier on the modularized resources to prevent the race. Or rename the resources in the state.

It would be preferred however if Terraform could recognize resources that would yield the same object on the provider and make this operation atomic during an apply, or even better shuffle the state data so that the resource is moved internally and no provider operations would be required.

**Comment by danieldreier** [comment] 2020-06-15 22:04
@apparentlymart can you please help triage this? I am uncertain about the expected behavior here and whether the error pointing the user to the provider issue tracker is valid or not. Specifically, I'm unsure whether this is a bug or an enhancement request and would appreciate help categorizing it.

**Comment by mildwonkey** [comment] 2020-08-27 15:10
Hi @mattlqx , sorry for the long silence on this issue. I'd like to first ask if this is still an issue for you, and then try and reproduce it locally. I'm also curious about how you moved the resource - did you try to use `terraform state mv` to move the existing resource instead of letting terraform delete and recreate it? 

if this is still an issue for you, please update this with a complete configuration that we can use to reproduce it. It would help if you can do so using a provider like `null` or `random`.

Thanks, and sorry again!

**Comment by jbardin** [comment] 2020-10-05 22:24
What is happening here is that terraform is attempting to create and delete the same remote object, at the same time, in 2 different places in the configuration.  The only safe way to do this are the methods recommended in the original post. Otherwise, there is no way for terraform to correlate the two resource, nor can terraform have any way to know they could possibly refer to the same external resource.

Since the actionable use case here appears to be the ability to move the resource in the state while changing the configuration, I'm going to close this in favor of #9048, where we're tracking the proposal to rename resources via the configuration.

**Closed by jbardin** 2020-10-05 22:24 UTC
Labels: waiting-response
