### ISSUE TITLE
vsphere provider does not delete vm if machine is powered off

### ISSUE THREAD

**Issue by pandrew** [hashicorp/terraform#3966] opened 2015-11-18 17:24 UTC
Im trying to create a vm using the following information 

```
# Configure the vSphere Provider
provider "vsphere" {
  user           = "root"
  password       = "password"
  vcenter_server = "ip"
}

# Create a virtual machine
resource "vsphere_virtual_machine" "web" {
  name   = "terraform_web"
  vcpu   = 2
  memory = 4096

  network_interface {
    label = "VM Network"
  }

  disk {
    size = 1
    iops = 500
  }
}
```

using ESXI 6.0.0 2809111
terraform build: 0.6.7-dev 24ee56326d1b7eccda046524fe7129302d6556fd

The vm is created but does not powered on and upon deleting with terraform plan -destroy, terraform plan apply it is not being deleted. It fails by informing me that it cant be destroyed while being powered off and looking at the code it seems as it assumes it is powered on and therefore cant shutdown while already powered off.

**Comment by chrislovecnm** [comment] 2015-11-19 21:10
@tkak / @pietern can we destroy a powered off vm with govomi?  I can test when I have bandwidth.  

@apparentlymart  this is as designed, and would be a new feature.  A feature that we should have eventually, but it is based on how the govomi api will react.

**Comment by pietern** [comment] 2015-11-19 21:18
@chrislovecnm Yes, no problem. This must be something where it tries to power off first, which fails if it is already powered off. You have to check for this if you're using the bare govmomi API.

**Comment by chrislovecnm** [comment] 2015-11-19 23:23
@pietern THANKS!  Yah this is the way it is coded, and it would be good to have feedback from @tkak on what he thinks

**Comment by chrislovecnm** [comment] 2015-12-02 19:39
@apparentlymart can you change this to a feature request?  It is functioning as designed...

**Comment by pandrew** [comment] 2015-12-02 20:57
@chrislovecnm What do i need to do to make it boot in the first place? There´s no logic for to handle both powered on and off states when destroying the plan.

**Comment by chrislovecnm** [comment] 2015-12-03 16:15
@pandrew 'make it boot in the first place' - what do you mean?

**Comment by pandrew** [comment] 2015-12-03 16:21
@chrislovecnm in my case the example above does not power on the vm in esxi. I assume terraform would do that after it had created the vm. The only option i found in the docs was a boot_delay option.

**Comment by chrislovecnm** [comment] 2015-12-03 17:07
@pandrew we are calling poweron https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L1138 when you create vm from a template.

Are you meaning to create a vm from a template??  I am not seeing the `template` option in your tf file.  The way you have setup your tf file creates a shell of a vm in order to use PIX or another network install.

**Comment by pandrew** [comment] 2015-12-03 17:16
Yes, i was going to boot from pxe but it did not poweron. I tried the same terraform template with 0.6.8 and still nothing happens. And when using destroy i get:

```
vsphere_virtual_machine.web: Refreshing state... (ID: terraform_web)
vsphere_virtual_machine.web: Destroying...
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.web: The attempted operation cannot be performed in the current state (Powered off).
```

**Comment by chrislovecnm** [comment] 2015-12-03 18:55
That code path does not power on the virtual machine ;) @tkak would need to comment why.

**Comment by chrislovecnm** [comment] 2015-12-03 18:57
It is the 'createVirtualMchine' vs the deploy template method we have...

**Comment by kc11381** [comment] 2015-12-06 16:25
Hi Chris,

Can we have something like : 

In the method : func resourceVSphereVirtualMachineDelete(d *schema.ResourceData, meta interface{}) error {

if vm_mo.Runtime.PowerState == "poweredOn" {
                task, err := vm.PowerOff(context.TODO())
                if err != nil {
                        return err
                }

                err = task.Wait(context.TODO())
                if err != nil {
                        return err
                }
        }

        task, err := vm.Destroy(context.TODO())
        if err != nil {
                return err
        }

I guess it will solve the problem. Please correct me here.

**Comment by chrislovecnm** [comment] 2015-12-06 19:08
@kc11381 it would be helpful for @tkak to pipe in here.  To me the code looks fine, and if you want to start working on a pull request that would be awesome!  

It would be good to find out from @tkak why we are not powering on pxe machines.  Or if we should have it as an option.

**Comment by tkak** [comment] 2015-12-07 01:39
@chrislovecnm The reason is because I get MAC address of the new VM before power on to identify the target VM and run kickstart. So, the power on feature doesn't include the terraform provider in the current version. If the power on feature should include the terraform provider, we should add the power state option or time delay option. 
And, the method for creating a new empty virtual machine with PXE boot is a limited use case. I think most users uses the deploying method with a template. So, I'm thinking about updating a default example.

@kc11381 Thank you for your code. It would be very helpful if you could submit PR!

**Comment by kc11381** [comment] 2015-12-07 12:36
@chrislovecnm and @tkak I am new to using git and also to open source community. I try to submit the code asap. Thank you.

**Comment by chrislovecnm** [comment] 2015-12-07 17:25
@kc11381 no problem

Here is what you want to do:

1. Fork the terraform to your account
2. Create a new branch
3. Make changes
4. Create a test
5. Submit a pull request 


https://help.github.com/articles/using-pull-requests/
Here are some instructions

**Comment by chrislovecnm** [comment] 2016-04-15 21:13
@kc11381 are you able to assist??

@jen20 @catsby can you retag as enhancement?  This is running as designed.

**Comment by chrislovecnm** [comment] 2016-04-19 17:57
@stack72 see above comment.  Sorry for the spam, but I be grooming ... I be jamming

**Comment by aheeren** [comment] 2016-04-21 15:38
Fixed in https://github.com/hashicorp/terraform/pull/6283

**Closed** 2016-04-21 16:27 UTC
Labels: bug, provider/vsphere
