### ISSUE TITLE
Terraform Crash report on interpolation

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#30467] opened 2022-02-03 15:47 UTC
Terraform 1.1.4

Trying to iterate through a map of different variable types, take the list values, and flatten them:

I tried this:

```
flatten([ for k, v in local.mymap : v if type(v) == "list" ])

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I cant really send through the contents of map as its all sensitive data - but some values are maps, and some are strings.

**Comment by jbardin** [comment] 2022-02-03 15:56
Hi @gtmtech,

Thanks for filing the issue. It's understandable if you can't supply the actual data, but I think we're going to need a little more information to diagnose the problem. A crash is always accompanied by a stack trace showing exactly where the crash took place, could you please add that output to the issue? If you have an example of the data, that might be useful as well.

Thanks!

**Comment by jbardin** [comment] 2022-02-03 19:22
Someone submitted the same crash along with the the complete output, so I'll closing this as a duplicate of #30470

Thanks!

**Closed by jbardin** 2022-02-03 19:22 UTC
Labels: bug, waiting-response, new, waiting for reproduction
