### ISSUE TITLE
HEREDOC doesn't terminate correctly

### ISSUE THREAD

**Issue by bspaans** [hashicorp/terraform#4835] opened 2016-01-26 14:26 UTC
Hi all,

I'm building Terraform from master and ran into a regression. It looks like HEREDOC strings aren't parsed correctly when the terminal is followed by a space. 

Minimal test case:

```
resource "whatever" "whatever" {
  userdata = <<EOF
test
EOF 
}
```

(NB. the last EOF is following by a space).
Running terraform plan against this gives me:

```
Error loading config: Error parsing /Users/bspaans/src/workspace/terraform/test.tf: At 6:1: heredoc not terminated
```

This used to work because our code is littered with it (apparently). 

Thanks, 
Bart

**Comment by bspaans** [comment] 2016-01-26 14:30
For reference I built e10d7740b393452d379a885cac66d0dea56bba84, although I'm guessing this has to do with the HCL update.

**Comment by phinze** [comment] 2016-01-26 21:10
Hi @bspaans, thanks for the report!

Looks like these whitespace followed heredoc terminators snuck in thanks to a bug in the old HCL parser.

I took a quick look at whether we should reproduce the original behavior, but reviewing a few other heredoc implementations, the consistent behavior I found was that the heredoc terminates only when a line contains the terminator with no trailing space.

So while I'm sorry that we caused you trouble, I think its probably better for us to preserve the current behavior than to try to emulate the old bug in the new parser.

I'm going to close this issue, but feel free to follow up if you'd like to discuss further! :+1:

**Closed by phinze** 2016-01-26 21:10 UTC
Labels: bug, core

**Comment by bspaans** [comment] 2016-01-27 11:05
Hi @phinze, thanks for your quick reply. The change on our side was easy enough so it's not a big issue. I had a quick look at the HCL source and it'd make the code a bit convoluted so I understand the decision. Thanks for looking into it. 

Cheers,
Bart

**Comment by joestump** [comment] 2017-03-13 23:12
It'd be nice to have a saner error message on this. Just spent half an hour pulling my hair out at what appeared to be valid heredocs (to those of us that haven't reviewed multiple heredoc implementations anyways). Removing the trailing space fixed it.

**Comment by apparentlymart** [comment] 2017-03-14 15:26
@joestump that seems like a great idea! Would you mind opening a fresh issue for that? Comments on closed issues are easy to miss and lose track of, so I worry that if we just leave this here it will be forgotten.

**Comment by mikemcguire** [comment] 2017-07-06 02:46
I just wanted to add a comment here for posterity.
Had a similar issue, and ended up here. If the close of your heredoc is the last line in your file it will throw this error. Adding an empty line at the end of the file fixes.
