### ISSUE TITLE
provider/aws: add support for ecs_service deployment configuration

### ISSUE THREAD

**Issue by nemski** [hashicorp/terraform#4847] opened 2016-01-27 03:20 UTC
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_paramters.html

Specifically the `maximumPercent` and `minimumHealthyPercent` values

**Comment by aldarund** [comment] 2016-01-27 13:07
ye, need that too. But there already ticket for this - https://github.com/hashicorp/terraform/issues/4456

**Comment by radeksimko** [comment] 2016-01-27 13:14
Hi @nemski ,
@aldarund is right, I will close this as a duplicate of the mentioned issue.

**Closed by radeksimko** 2016-01-27 13:14 UTC
Labels: enhancement, provider/aws
