### ISSUE TITLE
backend/remote: cannot perform local operations (state rm / taint) when the workspace uses version constraints

### ISSUE THREAD

**Issue by qwerty1979bg** [hashicorp/terraform#27628] opened 2021-01-29 11:38 UTC
### Terraform Version

```
Terraform v0.14.5
```

### Terraform Configuration Files

The Terraform code in the workspace does not matter, a simple "null_resource" is enough.

```terraform
resource "null_resource" "test" {
}
```

The following is the code needed to create the workspace with the version constraint:

```terraform
resource "tfe_workspace" "test" {
  name         = "test-workspace"
  organization = "test-org"
  terraform_version = "~> 0.14.0"
}
```

### Expected Behavior

A Terraform "state rm" or "taint" should succeed.

### Actual Behavior

terraform state rm null_resource.test

```
Error: Error looking up workspace

Invalid Terraform version: Malformed version: ~> 0.14.0

Error loading the state: Error checking remote Terraform version
```

### Steps to Reproduce

1. Create a Terraform Cloud workspace with version constraint
(Note: That cannot be done via the Web UI, only via the API / tfe provider)

2. Set your local Terraform to use the remote backend

3. Create a sample resource

4. Execute a "state rm" or "taint" command

### Additional Context

Is that even expected to work ?

Terraform Cloud seems to properly pick up the Terraform version during a run, although the workspace settings is constrained in showing only specific versions or "latest"

![image](https://user-images.githubusercontent.com/42143379/106269983-f51c6680-6235-11eb-8d84-75dd032072a8.png)

The workspace overview (beta) seem to correctly pick it up, tho:

![image](https://user-images.githubusercontent.com/42143379/106270501-c652c000-6236-11eb-96be-84e3c84ffe75.png)

It works with Terraform v0.14.0 and I guess the version constraints introduced in v0.14.1 "broke" it.

`-ignore-remote-version` does not seem to help

### References

#26947 #27353 #27480

**Comment by jbardin** [comment] 2021-01-29 15:07
Hi @qwerty1979bg 

This appears to be an issue with the TFE provider itself. I'll tag this to transfer the issue to their repo, in the meantime you may be able to work around the issue for now by removing the space in the constraint string: `"~>0.14.0"`.

**Comment by qwerty1979bg** [comment] 2021-01-29 15:25
@jbardin 

The TFE provider is able to create / modify a workspace with a version constraint string, i.e. "~> 0.14.0".
By "issue with the TFE provider itself", do you mean that it is not supposed to be able to set workspaces like that ? :)

The remote backend version check seems to be expecting only specific Terraform versions and not a version constraint string.

**Comment by jbardin** [comment] 2021-01-29 15:32
@qwerty1979bg, I believe this is just a bug parsing the constraint string in some context, however I don't think that is happening within terraform itself. Since the constraint here is being set through the TFE provider, that would be the next logical place to move the issue for further investigation.

**Comment by chrisarcand** [comment] 2021-01-29 15:43
This is not a problem with the provider, actually.

The issue is (as with the other bugs around the version checking that we've seen recently) that the Terraform version (the literal field in the API on a workspace) is not _an actual valid version string_ but instead can be a constraint _or_ a magical `latest` string, which is then used to resolve a real Terraform version on execution.

In other words, it is happening in Terraform itself where the version check occurs, but it's hardly Terraform's fault as the workspace should logically return a real, resolved version and not a constraint.

**Comment by jbardin** [comment] 2021-01-29 15:48
That makes sense now. Thanks @chrisarcand!

**Comment by chrisarcand** [comment] 2021-01-29 16:03
Reopening to track, as this is a real problem with the version checking we do here in the remote backend - but note that it may take more than anything that can be done here alone 👍🏻

**Comment by qwerty1979bg** [comment] 2021-01-29 16:11
@chrisarcand , I think we already have provisions for the magic "latest" version and actually parsing the version constraint makes sense from a user perspective.

I do agree that it might benefit from a more top-down approach, with corresponding changes in the Terraform Cloud / Enterprise Web UI, documentation, etc.

**Comment by ebdmuir** [comment] 2021-09-07 12:19
Hey guys, I keep running into this - do we have any programatic workaround to update the remote version to the local one or am I stuck manually updating the terraform versions for my workspaces?

**Comment by rosstimson** [comment] 2022-05-06 09:46
Yeah, we've tried switching workspaces to pessimistic version constraints and then realised all state manipulation commands seemed broken and we landed here.  This was with Terraform v1.1.9.  It'd be good to get an update on this issue.

**Comment by crw** [comment] 2022-05-12 22:00
Thanks for the report! This is fixed in the `cloud` state storage mechanism, which is the recommended configuration for using Terraform Cloud and Terraform Enterprise. Please see this migration guide to make the switch: https://www.terraform.io/cli/cloud/migrating

I am going to close this issue as it is fixed using the correct configuration, but please let me know if you think there is an outstanding issue that I missed. Thanks again for the report!

**Closed by crw** 2022-05-12 22:00 UTC
Labels: bug, backend/remote, v0.14
