### ISSUE TITLE
terraform plan generates wrong output for removing all AWS IAM users.

### ISSUE THREAD

**Issue by hanninen** [hashicorp/terraform#3510] opened 2015-10-15 11:49 UTC
When using the aws_iam_user resource and use that to create multiple users from a comma delimited variable value, the `terraform plan` command fails destroy all users, when the variable value is emptied.

Terraform gets confused, when the variable is empty and tries to according to the plan output to destroy & create the first user and destroy the second user.

Using Terraform v0.6.3
#### terraform.tfvars with users

```
region = "eu-west-1"
allowed_account_id = "123456789012"
user_names = "example+1@example.com,example+2@example.com"
```
#### main.tf

```
provider "aws" {
    region = "${var.region}"
    allowed_account_ids = ["${var.allowed_account_id}"]
}

resource "aws_iam_user" "example_user" {
    name = "${element(split(",", var.user_names), count.index)}"
    path = "${var.user_path}"

    count = "${length(split(",", var.user_names))}"
}
```

Executing `terraform plan` & `terraform apply` to create the user accounts.

```
$ terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_iam_user.example_user.0
    arn:       "" => "<computed>"
    name:      "" => "example+1@example.com"
    path:      "" => "/"
    unique_id: "" => "<computed>"

+ aws_iam_user.example_user.1
    arn:       "" => "<computed>"
    name:      "" => "example+2@example.com"
    path:      "" => "/"
    unique_id: "" => "<computed>
```

```
$ terraform apply
aws_iam_user.example_user.0: Creating...
  arn:       "" => "<computed>"
  name:      "" => "example+1@example.com"
  path:      "" => "/"
  unique_id: "" => "<computed>"
aws_iam_user.example_user.1: Creating...
  arn:       "" => "<computed>"
  name:      "" => "example+2@example.com"
  path:      "" => "/"
  unique_id: "" => "<computed>"
aws_iam_user.example_user.0: Creation complete
aws_iam_user.example_user.1: Creation complete

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```
#### terraform.tfvars without users

```
region = "eu-west-1"
allowed_account_id = "123456789012"
user_names = ""
```

Executing `terraform plan` and `terraform apply` to remove the user accounts. The plan output shows that it would destroy and create the first user, which shows the bug. When running the apply command, terraform destroys both users and fails then, as it probably detects that the plan was wrong and should not create the first user again.

```
$ terraform plan
Refreshing Terraform state prior to plan...

aws_iam_user.example_user.1: Refreshing state... (ID: example+2@example.com)
aws_iam_user.example_user: Refreshing state... (ID: example+1@example.com)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

-/+ aws_iam_user.example_user
    arn:       "arn:aws:iam::123456789012:user/example+1@example.com" => "<computed>"
    name:      "example+1@example.com" => "" (forces new resource)
    path:      "/" => "/"
    unique_id: "AIDAIOZEJYMVVGIF25BOI" => "<computed>"

- aws_iam_user.example_user.1


Plan: 0 to add, 1 to change, 1 to destroy.
```

```
$ terraform apply
aws_iam_user.example_user.1: Refreshing state... (ID: example+2@example.com)
aws_iam_user.example_user: Refreshing state... (ID: example+1@example.com)
aws_iam_user.example_user: Destroying...
aws_iam_user.example_user.1: Destroying...
aws_iam_user.example_user: Destruction complete
aws_iam_user.example_user.1: Destruction complete
Error applying plan:

1 error(s) occurred:

* aws_iam_user.example_user: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by catsby** [comment] 2016-12-19 22:16
Hello – after long last, I've reviewed this issue and have decided to close it. I was not able to reproduce the issue on v0.8.1, and we've also added validation to the username for `iam_user` to not allow the empty set (`""`). 

Sorry for the trouble!

**Closed by catsby** 2016-12-19 22:16 UTC
Labels: bug, provider/aws
