### ISSUE TITLE
Resource node has no configuration attached when using "apply planfile"

### ISSUE THREAD

**Issue by cappetta** [hashicorp/terraform#21515] opened 2019-05-30 03:34 UTC
I'm seeing 2 issues in CI after upgrading to v0.12.  Not sure if they are both related to the apply graph builder but sharing the [CICD build link](https://circleci.com/gh/cappetta/CyberRange/338)

I believe this is reproduced by  `terraform plan -out <file> `  then `terraform apply  <outfile> `  - I've reproduced it locally, then updated my circleci config file to eliminate the apply <outfile> with a normal apply `--auto-approve` and the build is passing again

### 
`
Error: Resource node has no configuration attached

The graph node for
module.staging-infrastructure.module.secdevops.aws_instance.sc[0] has no
configuration attached to it. This suggests a bug in Terraform's apply graph
builder; please report it!
`

### And this error about a non-empty state: 
`
Error: orphan resource module.staging-infrastructure.module.secdevops.data.aws_ami.seed_ubuntu1604 still has a non-empty state after apply; this is a bug in Terraform

**Comment by unbkbl** [comment] 2019-05-30 12:39
I have the same problem in a CI/CD pipeline running in AzureDevops. I use the Terraform task from https://marketplace.visualstudio.com/items?itemName=ArkiaConsulting.terraform-extension

When I run a terraform plan and terraform apply from my laptop I don't that problem 

I'm also using v0.12

`Error: orphan resource module.dc_uat.module.dataprovider-engine-publisher.azurerm_function_app.function still has a non-empty state after apply; this is a bug in Terraform



Error: orphan resource module.dc_uat.module.uefa-integration.azurerm_app_service.app_service still has a non-empty state after apply; this is a bug in Terraform`

**Comment by apparentlymart** [comment] 2019-05-30 13:31
Hi @cappetta, @unbkbl! Sorry for these strange errors, and thanks for reporting them.

If either of you are able to reproduce this when running Terraform with the environment variable `TF_LOG=trace` set, it'd be helpful to be able to see that full trace log (via a [gist](https://gist.github.com/), because traces are too long/verbose for github comments) so we can understand better how Terraform got itself into that "should never happen" situation.

**Comment by cappetta** [comment] 2019-05-30 14:11
No worries, glad to share the trace logging - [here's a gist](https://gist.github.com/cappetta/93c9493483870663bd818de20a47b9b1)

**Comment by apparentlymart** [comment] 2019-05-30 14:17
Thanks @cappetta! We'll take a deeper look at this soon.

The first thing that seems strange to me is that the error message is talking about an orphan resource but the address it gives is for a data resource (with `data.` prefix) rather than a managed resource, and that is curious because the idea of "orphan" (in this sense, at least) is supposed to apply only to managed resources that have been removed from the configuration since last apply.

I suspect (but have not yet confirmed) that the main error here is the one about the node having no configuration attached, and then this other error is showing up because the first error prevented Terraform from properly processing the data resource. We'll see when we debug further whether that is accurate.

**Comment by andresvia** [comment] 2019-05-30 22:22
@apparentlymart I have uploaded [a second trace](https://gist.github.com/andresvia/b3066f1d79e7d8fcc6991589ccd0b1fd ) thanks.

**Comment by apparentlymart** [comment] 2019-06-01 17:25
Hi @andresilva! Thanks for reporting that. Indeed, it does seem like something a little different, so let's open a new issue for that one and we can try to debug it separately.

**Comment by jogleasonjr** [comment] 2019-06-03 16:37
Hi @apparentlymart 

I am experiencing the same issue deploying a small piece of Azure infrastructure. Here's a [gist](https://gist.githubusercontent.com/jogleasonjr/b4c79171881de455e3ed25c38ea742a0/raw/da636170f702a47073fddc93bfb880ff10edf805/tf_rft_log_2019-06-04.txt) of the output. Happy to provide any other information you need.

**Comment by jogleasonjr** [comment] 2019-06-03 16:45
Hi @apparentlymart

I am experiencing the same issue deploying a small piece of Azure infrastructure. Here's a [gist](https://gist.githubusercontent.com/jogleasonjr/da14630060d113297fed22316b0731fc/raw/15791914268045c27c418ea49e142f794ac85112/tf_rft_log_2019-06-04.txt) of the output. Happy to provide any other information you need.

**Comment by simoncocking** [comment] 2019-06-07 00:57
I've raised an issue (which appears to be a dupe of this one) with full trace/plan outputs:

https://github.com/hashicorp/terraform/issues/21624

**Comment by bohdanyurov-gl** [comment] 2019-06-09 03:14
Also affects us with dozens of projects. Only one module is affected though, I'm going to check what exactly leads to this error.

I can also confirm that omitting plan argument (doing plan again on apply) helps.

**Comment by bohdanyurov-gl** [comment] 2019-06-11 20:33
I've found root cause for one of our modules:

```
variable "ansible_variables" {
  type    = map(string)
  default = []

  description = "Map of additional ansible variables"
}
```

->

```
variable "ansible_variables" {
  type    = map(string)
  default = {}

  description = "Map of additional ansible variables"
}
```

@apparentlymart After I've changed this input variable to correct default value issue has gone (for this particular module). I am curious why this single line has broken whole module subtree state in plan.

**Comment by bohdanyurov-gl** [comment] 2019-06-12 09:51
I've managed to find another reason in second module: duplicated outputs. Removing duplicated one fixed whole module. Looks like terraform somehow hides the real error message + destroys whole submodule plan.

**Comment by markmsmith** [comment] 2019-06-20 01:17
I'm seeing this problem as well.  You can reproduce it using the RDS Postgres example found here:
https://github.com/terraform-aws-modules/terraform-aws-rds/tree/master/examples/complete-postgres  
I raised an issue on that project, but it seems like it may actually be a terraform 0.12 bug, since converting the same example to 0.11 syntax and running it with terraform 0.11.14 works correctly.  You can see my example with log output referenced from the issue here:
https://github.com/terraform-aws-modules/terraform-aws-rds/issues/134

**Comment by poolski** [comment] 2019-06-25 10:35
I also have this issue when upgrading from 0.11.13 to 0.12.3. Nothing changed in our infrastructure but a `terraform apply` returns a string of this. 

This isn't an apply from a file, just a CLI `terraform apply` with no other extras.

```
...
Error: orphan resource module.development.module.service1.aws_launch_configuration.this still has a non-empty state after apply; this is a bug in Terraform

Error: orphan resource module.development.module.service2.aws_autoscaling_group.this still has a non-empty state after apply; this is a bug in Terraform

Error: orphan resource module.development.module.service3.aws_launch_configuration.this still has a non-empty state after apply; this is a bug in Terraform

Error: orphan resource module.development.module.service4.aws_launch_configuration.this still has a non-empty state after apply; this is a bug in Terraform
...
```

**Comment by mfortin** [comment] 2019-06-27 16:15
Also observing the same.
```
Error: orphan resource module.cluster.module.batch_environment.aws_iam_role_policy_attachment.batch-instance-policy-role-attachment still has a non-empty state after apply; this is a bug in Terraform

Error: Resource node has no configuration attached

The graph node for
module.cluster.module.batch_environment.aws_iam_role_policy_attachment.batch-spot-fleet-service-policy-attachment[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: orphan resource module.cluster.module.batch_environment.aws_iam_role.batch-instance-role still has a non-empty state after apply; this is a bug in Terraform

Error: Resource node has no configuration attached

The graph node for
module.cluster.module.batch_environment.aws_batch_job_queue.cloudos-batch-spot-queue[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: orphan resource module.cluster.module.batch_environment.aws_iam_role_policy_attachment.batch-service-policy-attachment still has a non-empty state after apply; this is a bug in Terraform

Error: orphan resource module.cluster.module.batch_environment.aws_batch_compute_environment.cloudos-batch-env still has a non-empty state after apply; this is a bug in Terraform

Error: orphan resource module.cluster.module.batch_environment.aws_iam_role.batch-service-role still has a non-empty state after apply; this is a bug in Terraform

Error: Resource node has no configuration attached

The graph node for
module.cluster.module.batch_environment.aws_launch_template.batch_launch_template_spot[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: orphan resource module.cluster.module.batch_environment.aws_launch_template.batch_launch_template still has a non-empty state after apply; this is a bug in Terraform

Error: Resource node has no configuration attached

The graph node for
module.cluster.module.batch_environment.aws_iam_role.batch-spot-fleet-service-role[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: orphan resource module.cluster.module.batch_environment.aws_iam_instance_profile.batch-instance-role-profile still has a non-empty state after apply; this is a bug in Terraform

Error: Resource node has no configuration attached

The graph node for
module.cluster.module.batch_environment.aws_batch_compute_environment.cloudos-batch-env-spot[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: orphan resource module.cluster.module.batch_environment.aws_batch_job_queue.cloudos-batch-queue still has a non-empty state after apply; this is a bug in Terraform

Error: orphan resource module.cluster.module.batch_environment.aws_iam_policy.batch-instance-policy still has a non-empty state after apply; this is a bug in Terraform

Error: orphan resource module.cluster.module.batch_environment.aws_iam_role_policy_attachment.batch-instance-role-policy-attachment still has a non-empty state after apply; this is a bug in Terraform
```

All of my resources in that module are using a count to enable/disable creation. This is the only modules that is giving me these issues.

**Comment by sroze** [comment] 2019-07-03 09:05
Same is happening here with 0.12.3. `terraform apply -auto-approve` made it work (vs `terraform plan --out X && terraform apply X`)

**Comment by mfortin** [comment] 2019-07-04 20:25
thanks @sroze this helped me figure out 2 bugs I had in my terraform module. I now only get the 
`Error: orphan resource module.cluster.module.batch_environment.resource.name still has a non-empty state after apply; this is a bug in Terraform`
when I run `terraform plan --out PLAN && terraform apply PLAN`

**Comment by alexpekurovsky** [comment] 2019-07-08 09:02
Sharing my solution: https://github.com/hashicorp/terraform/issues/21624#issuecomment-509141859

The issue is in the module, just Terraform doesn't tell exactly where it is and fails all resources

**Comment by DMonCode** [comment] 2019-07-11 18:50
Ran into same issue with Terraform Enterprise. I then tried to run the job from my work station. If I run using `terraform plan -out MYPLAN` and then use `terraform apply MYPLAN` it fails. If I run `terraform apply` it succeeds.

**Closed** 2019-07-17 01:47 UTC
Labels: bug, core
