### ISSUE TITLE
-target option throws a terraform crash

### ISSUE THREAD

**Issue by wolfwolker** [hashicorp/terraform#25307] opened 2020-06-19 07:52 UTC
Hi there,

Trying to run a portion of my code with the -target option, no matter if it is a module or a resource, no matter if I run plan, apply or destroy, always throws the same terraform crash.

Tried with terraform0.13 beta1 and beta 2 in linux x64, with same results.

```
goroutine 219 [running]:
github.com/hashicorp/terraform/instances.(*expanderModule).moduleInstances(0xc00098e440, 0xc000582b30, 0x1, 0x1, 0xc0012c9b50, 0x0, 0x4, 0x4f21f8, 0x0, 0x16)
	/home/circleci/project/project/instances/expander.go:267 +0xb72
github.com/hashicorp/terraform/instances.(*Expander).ExpandModule(0xc00098e460, 0xc000582b30, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/project/instances/expander.go:116 +0x108
github.com/hashicorp/terraform/terraform.(*nodeExpandModuleVariable).DynamicExpand(0xc0001c6440, 0x23ae440, 0xc0006afc70, 0x1, 0x1, 0x1)
	/home/circleci/project/project/terraform/node_module_variable.go:42 +0x94
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1d18b20, 0xc0001c6440, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:84 +0x4d8
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000b866c0, 0x1d18b20, 0xc0001c6440, 0xc0007cb380)
	/home/circleci/project/project/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x11d7



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by quentin9696** [comment] 2020-06-19 14:14
Same for me !

**Comment by jeremykatz** [comment] 2020-06-19 22:54
I see a crash if the target is a dependency of a module. It's possible that being a dependency of any resource is sufficient.

https://github.com/hashicorp/terraform/issues/25319

**Comment by jbardin** [comment] 2020-06-25 15:06
We won't be able to test this without a reproduction case, so since it's the same use case, I'll close this as a duplicate of #25307.

**Closed by jbardin** 2020-06-25 15:06 UTC
Labels: core, crash, v0.13
