### ISSUE TITLE
Init requests version for Terraform Provider

### ISSUE THREAD

**Issue by ivan-m** [hashicorp/terraform#17473] opened 2018-03-01 04:27 UTC
```
Terraform v0.11.3
```

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 0.10"
}

data "terraform_remote_state" "vpc" {
  backend = "s3"

  config {
    bucket = ...
    key    = ...
    region = ...
  }
}
```

### Debug Output

_Does not seem relevant; can attach if required._

### Crash Output

N/A

### Expected Behavior

AFAICT there shouldn't be any suggestion to specify a version for the `"terraform"` provider.

### Actual Behavior

```
$ terraform init
[snip]
The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.terraform: version = "~> 1.0"
[snip]
```

So I add to my `.tf` file:
```hcl
provider "terraform" {
  version = "~> 1.0"
}
```

`terraform init` is then happy, but:

```
$ terraform plan
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.terraform: this provider is built in to Terraform and so it does not support version constraints

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".


Error: error satisfying plugin requirements
```

### Steps to Reproduce

1. (Implicitly) use the `"terraform"` provider
2. `terraform init`
3. Get told to add a version to the provider
4. Add a provider block with a version for the `"terraform"` provider.
5. `terraform plan`

### References

- #16994

**Comment by jbardin** [comment] 2018-03-01 14:38
Hi @ivan-m,

I believe this is a duplicate of #17233, and terraform is probably finding an old provider binary in it's search path.

Can you provide the log output from the `init` command, which might show why terraform is reporting that the provider is missing a version constraint?

**Comment by ivan-m** [comment] 2018-03-09 05:51
[`terraform init` output](https://gist.github.com/ivan-m/a204fe2cbf299af49f3ee3e6f7e09464)

**Comment by apparentlymart** [comment] 2018-03-09 16:57
Hi @ivan-m! Thanks for that additional information.

In that log output I see lines like this:

```
[DEBUG] found valid plugin: "terraform", "1.0.2", "/nix/store/bsk5z0nbpb0mnbh1wq9hbyia519bin85-tf-plugin-env/bin/terraform-provider-terraform_v1.0.2"
```

This confirms @jbardin's theory about this being caused by there being an old, separated provider binary that is confusing Terraform's installer now that the `terraform` plugin is built in to Terraform itself (as of v0.11).

I'm going to close this one just to consolidate into #17233, where this is already being discussed. Sorry for this confusing bug, and thanks for reporting it.

**Closed by apparentlymart** 2018-03-09 16:57 UTC
Labels: bug, cli
