### ISSUE TITLE
source="aliyun/alicloud" is unavailable when using Terraform Module

### ISSUE THREAD

**Issue by xiaozhu36** [hashicorp/terraform#33393] opened 2023-06-19 15:05 UTC
### Terraform Version

```shell
$ terraform version
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/aliyun/alicloud v1.204.0
+ provider registry.terraform.io/hashicorp/alicloud v1.206.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    alicloud = {
      source = "aliyun/alicloud"
      version = "1.204.0"
    }
  }
}

// defines a module and it supports to create resource alicloud_quotas_template_quota, 
// and it is available since v1.206.0. The module configurations as following:
// resource "alicloud_quotas_template_quota" "default" {
//   quota_action_code = "q_desktop-count"
//   product_code      = "gws"
//   notice_type       = 3
//   dimensions {
//     key   = "regionId"
//     value = "cn-hangzhou"
//   }
//   desire_value   = 1001
//   env_language   = "zh"
//   quota_category = "CommonQuota"
// }

module "quota" {
  source = "./modules/quotas"
}
```

### Debug Output

https://gist.github.com/xiaozhu36/e4b539c8b76318dca71c24ac870e0178

### Expected Behavior

```
╷
│ Error: Invalid resource type
│ 
│   on modules/quotas/main.tf line 1, in resource "alicloud_quotas_template_quota" "default":
│    1: resource "alicloud_quotas_template_quota" "default" {
│ 
│ The provider aliyun/alicloud does not support resource type "alicloud_quotas_template_quota".
╵
```

### Actual Behavior

```
Terraform will perform the following actions:

  # module.quota.alicloud_quotas_template_quota.default will be created
  + resource "alicloud_quotas_template_quota" "default" {
      + desire_value      = 1001
      + env_language      = "zh"
      + id                = (known after apply)
      + notice_type       = 3
      + product_code      = "gws"
      + quota_action_code = "q_desktop-count"
      + quota_category    = "CommonQuota"

      + dimensions {
          + key   = "regionId"
          + value = "cn-hangzhou"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

──────
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment] 2023-06-20 12:33
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

I'm confused by your expected behavior, it looks like you wrote he error you are receiving there. The problem is most likely you have not added the `required_providers` block to the modules, so the modules are resolving the providers in the default `hashicorp` namespace.

Thanks!

**Closed by jbardin** 2023-06-20 12:33 UTC
Labels: bug, new
