### ISSUE TITLE
Allow provider to be dynamic (for_each or count)

### ISSUE THREAD

**Issue by jontreynes** [hashicorp/terraform#27448] opened 2021-01-08 16:53 UTC
### Current Terraform Version

```
0.14.3
```

### Use-cases

Some providers such as the panos provider https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs, only allow you to work with one instance/node per provider. You may need to define many nodes.

It would simpler to define X number of instances if the provider block allowed for for_each or count just as resource blocks do. One could then set a dynamic set of aliases per provider

Today, if you try for_each in a provider block, you will receive

`The provider argument name "for_each" is reserved for use by Terraform in a
future version.`

### Attempted Solutions

```
provider "azurerm" {
  for_each = var.pr
  alias = "rg1"
  tags {
    mytag = each.value["name"]
  }
}

❯ terraform init
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Reserved argument name in provider block

  on module\m1\palo.tf line 11, in provider "azurerm":
  11:   for_each = var.pr

The provider argument name "for_each" is reserved for use by Terraform in a
future version.
```

and

```
provider "azurerm" {
  for_each = var.pr
  alias = each.value["name"]
  tags {
    mytag = each.value["name"]
  }
}

❯ terraform init
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid provider configuration alias

An alias must be a valid name. A name must start with a letter or underscore
and may contain only letters, digits, underscores, and dashes.


Error: Reserved argument name in provider block

  on module\m1\palo.tf line 11, in provider "azurerm":
  11:   for_each = var.pr

The provider argument name "for_each" is reserved for use by Terraform in a
future version.


Error: Variables not allowed

  on module\m1\palo.tf line 12, in provider "azurerm":
  12:   alias = each.value["name"]

Variables may not be used here.


Error: Unsuitable value type

  on module\m1\palo.tf line 12, in provider "azurerm":
  12:   alias = each.value["name"]

Unsuitable value: value must be known
```

### References
https://www.terraform.io/docs/configuration/meta-arguments/for_each.html#limitations-on-values-used-in-for_each

**Comment by jbardin** [comment] 2021-01-08 16:59
Duplicate of #24476, and linking to the closely related #25244

Thanks!

**Closed by jbardin** 2021-01-08 16:59 UTC
Labels: enhancement, new

**Comment by jontreynes** [comment] 2021-01-08 17:01
ah thank you! @jbardin
