### ISSUE TITLE
 CRLF '\r' must change to LF  for bootstrap.sh - if terraform is executed from windows [GCP]

### ISSUE THREAD

**Issue by anborg** [hashicorp/terraform#25507] opened 2020-07-07 21:43 UTC
Hi Tf, 

Summary: 

I run "terraform apply" from windows machine (the files edited using intellij).  The GCP compute instance makes use of a bootstrap.sh startup script.   I expect terraform to translate CRLF to LF when it reaches the GCP-compute instance. But looks like terraform is not doing the transform? 

**Expectation** 

1. Issue 1: . terraform must translate CRLF to LF, if executed from windows machine - so '\r' not found wont happen
2. Issue 2:  if exit status of startup script is error, perhaps terraform must terminate instance-creation - as system is not in a desired state. 
3. Issue 3: For startup script.sh redability, terraform may need to support multi line unix commands with "\" line ending char.

```
Jul  7 21:34:36 entsearch GCEMetadataScripts[633]: 2020/07/07 21:34:36 GCEMetadataScripts: startup-script: Reading state information...
Jul  7 21:34:36 entsearch GCEMetadataScripts[633]: 2020/07/07 21:34:36 GCEMetadataScripts: startup-script: E: Unable to locate package software-properties-common
Jul  7 21:34:36 entsearch GCEMetadataScripts[633]: 2020/07/07 21:34:36 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 5: $'\r': command not found
Jul  7 21:34:36 entsearch GCEMetadataScripts[633]: 2020/07/07 21:34:36 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 7: $'\r': command not found
Jul  7 21:34:36 entsearch GCEMetadataScripts[633]: 2020/07/07 21:34:36 GCEMetadataScripts: startup-script: Warning: apt-key output should not be parsed (stdout is not a terminal)
Jul  7 21:34:36 entsearch GCEMetadataScripts[633]: 2020/07/07 21:34:36 GCEMetadataScripts: startup-script: gpg: invalid option "-#015"


Debian GNU/Linux 9 entsearch ttyS0

entsearch login: Jul  7 21:34:40 entsearch systemd[1]: Time has been changed
Jul  7 21:34:40 entsearch systemd[1]: apt-daily-upgrade.timer: Adding 57min 30.645381s random time.
Jul  7 21:34:40 entsearch systemd[1]: apt-daily.timer: Adding 8h 48min 15.848808s random time.
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: (23) Failed writing body
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 9: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 10: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 12: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: Warning: apt-key output should not be parsed (stdout is not a terminal)
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 14: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 15: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 17: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: sudo: add-apt-repository: command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 19: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 20: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 22: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: E: Invalid operation update
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 24: $'\r': command not found
Jul  7 21:35:41 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:41 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 25: $'\r': command not found
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: Reading package lists...

.
.
.


Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: Package docker-ce is not available, but is referred to by another package.
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: This may mean that the package is missing, has been obsoleted, or
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: is only available from another source
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script:
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: E: Package 'docker-ce' has no installation candidate
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: E: Unable to locate package docker-ce-cli
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: E: Unable to locate package containerd.io
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: E: Couldn't find any package by glob 'containerd.io
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script:    '
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: E: Couldn't find any package by regex 'containerd.io
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script:    '
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 27: $'\r': command not found
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 28: $'\r': command not found
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 30: $'\r': command not found
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script:                                  Dload  Upload   Total   Spent    Left  Speed
Jul  7 21:35:42 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:42 GCEMetadataScripts: startup-script: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100   638  100   638    0     0   2616      0 --:--:-- --:--:-- --:--:--  2625
Jul  7 21:35:43 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:43 GCEMetadataScripts: startup-script: #015  9 11.6M    9 1137k    0     0  1978k      0  0:00:06 --:--:--  0:00:06 1978k#015100 11.6M  100 11.6M    0     0  15.4M      0 --:--:-- --:--:-- --:--:-- 58.7M
Jul  7 21:35:43 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:43 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 32: $'\r': command not found
Jul  7 21:35:43 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:43 GCEMetadataScripts: startup-script: /tmp/metadata-scripts832804331/startup-script: line 34: $'\r': command not found
Jul  7 21:35:43 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:43 GCEMetadataScripts: startup-script exit status 127
Jul  7 21:35:43 entsearch systemd[1]: Started Google Compute Engine Startup Scripts.
Jul  7 21:35:43 entsearch GCEMetadataScripts[633]: 2020/07/07 21:35:43 GCEMetadataScripts: Finished running startup scripts.
```
When I add #/bin/sh I see the below error
```sh
Jul  7 22:12:21 entsearch GCEMetadataScripts[640]: 2020/07/07 22:12:21 GCEMetadataScripts: startup-script: /bin/bash: /tmp/metadata-scripts602162914/startup-script: /bin/sh^M: bad interpreter: No such file or directory
```

```sh
# scripts/bootstrap.sh
sudo apt-get update -yq
sudo apt-get install -yq  apt-transport-https ca-certificates curl gnupg-agent software-properties-common

#Add Docker’s official GPG key

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -


#Verify that you now have the key with the fingerprint 9DC8 5822

sudo apt-key fingerprint 0EBFCD88


#Use the following command to set up the stable repository.

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian  $(lsb_release -cs)  stable"


#Install docker

sudo apt-get -yq update

#A multiline "\" must be supported for readablity
sudo apt-get -yq install docker-ce docker-ce-cli containerd.io 


#install docker compose

sudo curl -L "https://github.com/docker/compose/releases/download/1.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
```

main.tf
```tf
resource "google_compute_instance" "vm_instance" {
  #name = "entsearch-${random_id.instance_id.hex}"
  name = "entsearch"
  zone = var.zone
  machine_type = var.machine_docker_webapps

  tags = ["search", "bar"]
  labels = {
    environment = var.deploy_env
    apps = "elastic-stack"
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
      size = 50 
    }
  }

  //ssh keys for login
  metadata = {
    ssh-keys = "${var.ssh_username}:${file(var.ssh_pubkey_file)}"
  }
  metadata_startup_script = file("./scripts/bootstrap.sh")

```

![image](https://user-images.githubusercontent.com/56970398/86843152-2b18b400-c074-11ea-9049-d42953634537.png)

If I open the .sh file in notepad++ and force unix ending, the script has no issue executing. 
![image](https://user-images.githubusercontent.com/56970398/86851338-d29be380-c080-11ea-9bff-54c0edd08763.png)

**Comment by apparentlymart** [comment] 2020-07-08 22:03
Hi @anborg,

When reading a file from disk using `file` Terraform intentionally returns the unicode characters given in the file without any line-ending translation, because the goal is for it to behave the same way regardless of where you are running Terraform and Terraform itself doesn't know what operating system your remote server is running.

The `metadata_startup_script` in particular is, from the perspective of both Terraform and Google Cloud Platform, just an opaque string that is interpreted only by some software you have installed in the virtual machine image. That's often, but not necessarily, `cloud-init`. Terraform and the Google Cloud Platform provider can't know that the software in the VM expects Unix line endings, and so it will just send whatever you've configured it to send.

Therefore if you want the result of reading your file to use Unix line endings then you should save the file with Unix line endings. As you found with that Notepad++ setting, Terraform will then read the file with the necessary line endings and send it with exactly the same line endings to the remote server.

The configuration section you took a screenshot of is referring to the syntax of `.tf` files, not of external files you load with the `file` function, and when it says "automatic configuration formatting tools" it means tools like the `terraform fmt` command, not Terraform's main behavior.

Because Terraform is behaving as designed here, I'm going to close this issue. I hope the above explains why Terraform is designed the way it is. If you have any further questions, feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!

**Closed by apparentlymart** 2020-07-08 22:03 UTC
