### ISSUE TITLE
Error refreshing datasource without dependencies change

### ISSUE THREAD

**Issue by hfgbarrigas** [hashicorp/terraform#24899] opened 2020-05-08 11:15 UTC
### Terraform Version
0.12.24

### Terraform Configuration Files
```hcl

resource "time_rotating" "rsa1" {
  rotation_minutes = 1
}

resource "null_resource" "create-local-file" {
  command = " ssh-keygen -t rsa -b 2048 -f $KEY_PATH/$KEY_NAME -N '' "
  environment = {
      KEY_PATH = path.module
      KEY_NAME = time_rotating.rsa1.unix
    }
  triggers = {
    timestamp = time_rotating.rsa1.unix
  }
}

data "template_file" "local-file-contents" {
  template = file("${path.module}/${time_rotating.rsa1.unix}")
  vars = {
    timestamp = time_rotating.rsa1.unix
    null      = null_resource.rsa1.id
  }
}

```

### Crash Output
FIRST RUN:
![image](https://user-images.githubusercontent.com/10131599/81398315-e7133c80-9120-11ea-8bbf-80065e439bcf.png)

SECOND RUN (with `file` function and not removing the files):
![image](https://user-images.githubusercontent.com/10131599/81399373-cc41c780-9122-11ea-9345-673d97cbf19d.png)

THIRD RUN (with `file` function and removing the files):
![image](https://user-images.githubusercontent.com/10131599/81399188-7cfb9700-9122-11ea-8eb5-1339bd5c2052.png)

It appears that although dependencies have no changes terraform still refreshes the datasource that depends on a file that will never exist until there are changes.

### Expected Behavior
No datasource refresh since the dependencies had no changes.

### Actual Behavior
Datasource gets refreshed and fails since the file is only created when the dependency changes.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### References
[11806](https://github.com/hashicorp/terraform/issues/11806)

**Comment by apparentlymart** [comment] 2020-05-12 21:14
Hi @hfgbarrigas,

I replied to your comment in #11806 before I saw you'd made a separate issue for the same problem. I'm going to copy the same response here to help anyone who finds this issue in future...

---

The behavior you saw there is as intended, because [the `file` function](https://www.terraform.io/docs/configuration/functions/file.html) is for reading files that exist statically as part of the configuration, not for files that are generated dynamically during a Terraform run. Terraform reads the file proactively during initial configuration decoding so that it can use the result as part of static validation.

Although I'd recommend avoiding generating local files on disk if you can, in unusual situations where you can't avoid it you can read the contents of a file using [the `local_file` data source] instead, which (because it's a data source, rather than an intrinsic function) will take its action during the graph walk, not during initial configuration loading.

```hcl
resource "time_rotating" "rsa1" {
  rotation_minutes = 1
}

resource "null_resource" "create_template_file" {
  triggers = {
    filename = time_rotating.rsa1.unix
  }
  provisioner "local-exec" {
    # I added this because I assume you're intending to run
    # a local command to generate this file. You can refer
    # to self.triggers.filename in the provisioner configuration
    # to get the filename populated above.
  }
}

data "local_file" "generated_template" {
  filename = "${path.module}/${null_resource.create_template_file.triggers.filename}"
}

data "template_file" "result" {
  template = data.local_file.generated_template.content
  vars = {
    id = null_resource.rsa1.id
  }
}
```

---

Because Terraform is working as designed here, I'm going to close this out. If you have any follow-up questions about this behavior or my example above, please feel free to create an issue in [the community forum](https://discuss.hashicorp.com/c/terraform-core) and I'll follow up with you there.

**Closed by apparentlymart** 2020-05-12 21:14 UTC
