### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by duzitong** [hashicorp/terraform#35632] opened 2024-08-23 03:33 UTC
### Terraform Version

```shell
Terraform v1.9.5 on windows_amd64
```

### Terraform Configuration Files

Code is located in Azure DevOps, which is hard to share. This issue is relevant to oidc authentication for azurerm backend.

```yml
  - task: AzureCLI@2
    displayName: 'terraform apply'
    inputs:
      azureSubscription: ${{ parameters.azureConnectionName }}
      scriptType: ps
      addSpnToEnvironment: true
      useGlobalConfig: true
      scriptLocation: inlineScript
      inlineScript: |
        $env:ARM_USE_AZUREAD = 'true'
        $env:ARM_SUBSCRIPTION_ID = az account show --query id --output tsv
        $env:ARM_TENANT_ID = $env:tenantId
        $env:ARM_CLIENT_ID = $env:servicePrincipalId
        $env:ARM_USE_OIDC = 'true'
        $env:ARM_OIDC_TOKEN_FILE_PATH = "$(System.DefaultWorkingDirectory)/${{ parameters.stage }}/${{ parameters.siteId }}/${{ parameters.siteId }}.token"
        $env:OIDC_REQUEST_URL = "${env:SYSTEM_OIDCREQUESTURI}?api-version=7.1&serviceConnectionId=${env:AZURESUBSCRIPTION_SERVICE_CONNECTION_ID}"
        $env:ADO_ACCESS_TOKEN = "$(System.AccessToken)"
        echo "##[command]Start refresh oidc token job"
        $job = Start-Job { $(System.DefaultWorkingDirectory)/.azure/refresh_oidc_token.ps1 $env:ARM_OIDC_TOKEN_FILE_PATH }
        echo "Wait until token file is created"
        while (-not (Test-Path $env:ARM_OIDC_TOKEN_FILE_PATH)) {
          sleep 5
          echo "Check whether refresh oidc token job is running"
          if ($job.State -ne "Running") {
            Receive-Job -Job $job
            throw "Failed to refresh oidc token"
          }
        }
        echo "##[command]terraform apply -auto-approve -input=false ${{ parameters.siteId }}.tfplan"
        terraform apply -auto-approve -input=false ${{ parameters.siteId }}.tfplan
        echo "Stop oidc token job"
        Stop-Job -Job $job
      workingDirectory: "${{ parameters.stage }}/${{ parameters.siteId }}"
```

### Debug Output

```log
module.base.module.hci.azapi_update_resource.deploymentsetting[0]: Still creating... [2h34m48s elapsed]
module.base.module.hci.azapi_update_resource.deploymentsetting[0]: Still creating... [2h34m58s elapsed]
module.base.module.hci.azapi_update_resource.deploymentsetting[0]: Still creating... [2h35m8s elapsed]
module.base.module.hci.azapi_update_resource.deploymentsetting[0]: Still creating... [2h35m18s elapsed]
module.base.module.hci.azapi_update_resource.deploymentsetting[0]: Creation complete after 2h35m19s [id=/subscriptions/***/resourceGroups/iao2357-rg/providers/Microsoft.AzureStackHCI/clusters/iao2357-cl/deploymentSettings/default]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: runtime error: invalid memory address or nil pointer dereference
goroutine 626 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:84 +0x1ac
panic({0x3635ae0?, 0x5eb2eb0?})
	runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0xc000c12000, {0xc00294c000, 0x19fb6, 0x1a000})
	github.com/hashicorp/terraform/internal/backend/remote-state/azure@v0.0.0-00010101000000-000000000000/client.go:92 +0x603
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0xc000c052c0, 0x39e9620?)
	github.com/hashicorp/terraform/internal/states/remote/state.go:213 +0x763
github.com/hashicorp/terraform/internal/backend/local.(*StateHook).PostStateUpdate(0xc000bfe4b0, 0xc0010903a8)
	github.com/hashicorp/terraform/internal/backend/local/hook_state.go:60 +0x296
github.com/hashicorp/terraform/internal/terraform.updateStateHook.func1({0x44843e0?, 0xc000bfe4b0?})
	github.com/hashicorp/terraform/internal/terraform/update_state_hook.go:16 +0x28
github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).Hook(0x5fff380?, 0xc00239cd70)
	github.com/hashicorp/terraform/internal/terraform/eval_context_builtin.go:110 +0x71
github.com/hashicorp/terraform/internal/terraform.updateStateHook({0x448f408, 0xc000dc8d20})
	github.com/hashicorp/terraform/internal/terraform/update_state_hook.go:15 +0xcd
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc002398740, {0x448f408, 0xc000dc8d20})
	github.com/hashicorp/terraform/internal/terraform/node_resource_apply_instance.go:389 +0x1d47
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).Execute(0x18?, {0x448f408?, 0xc000dc8d20?}, 0x80?)
	github.com/hashicorp/terraform/internal/terraform/node_resource_apply_instance.go:145 +0x9a
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0005b08c0, {0x448f408, 0xc000dc8d20}, {0x1e8fea74508, 0xc002398740})
	github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:153 +0xbb
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x3b4cf20, 0xc002398740})
	github.com/hashicorp/terraform/internal/terraform/graph.go:143 +0x83d
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc001125080, {0x3b4cf20, 0xc002398740}, 0xc000db1480)
	github.com/hashicorp/terraform/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 194
	github.com/hashicorp/terraform/internal/dag/walk.go:307 +0xff3
```

### Expected Behavior

Long running apply operation can succeed.

### Actual Behavior

Apply failed after 2.5 hours.

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

I'm trying to use [Azure DevOps workload Identity federation service connection](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/configure-workload-identity?view=azure-devops) to authenticate in ADO pipeline. My infrastructure takes more than 1 hour to apply. The oidc token life span is 1 hour. Therefore, apply will fail after 1 hour if using OIDC token directly.

I added another background job to refresh the OIDC token every 30 minutes into a file `$env:ARM_OIDC_TOKEN_FILE_PATH`. The long running creation succeeds. But when terraform tries to persist this state to azurerm blob state, terraform crashes. (Check Debug output)

The Azure DevOps pipeline step is pasted below.

```yml
  - task: AzureCLI@2
    displayName: 'terraform apply'
    inputs:
      azureSubscription: ${{ parameters.azureConnectionName }}
      scriptType: ps
      addSpnToEnvironment: true
      useGlobalConfig: true
      scriptLocation: inlineScript
      inlineScript: |
        $env:ARM_USE_AZUREAD = 'true'
        $env:ARM_SUBSCRIPTION_ID = az account show --query id --output tsv
        $env:ARM_TENANT_ID = $env:tenantId
        $env:ARM_CLIENT_ID = $env:servicePrincipalId
        $env:ARM_USE_OIDC = 'true'
        $env:ARM_OIDC_TOKEN_FILE_PATH = "$(System.DefaultWorkingDirectory)/${{ parameters.stage }}/${{ parameters.siteId }}/${{ parameters.siteId }}.token"
        $env:OIDC_REQUEST_URL = "${env:SYSTEM_OIDCREQUESTURI}?api-version=7.1&serviceConnectionId=${env:AZURESUBSCRIPTION_SERVICE_CONNECTION_ID}"
        $env:ADO_ACCESS_TOKEN = "$(System.AccessToken)"
        echo "##[command]Start refresh oidc token job"
        $job = Start-Job { $(System.DefaultWorkingDirectory)/.azure/refresh_oidc_token.ps1 $env:ARM_OIDC_TOKEN_FILE_PATH }
        echo "Wait until token file is created"
        while (-not (Test-Path $env:ARM_OIDC_TOKEN_FILE_PATH)) {
          sleep 5
          echo "Check whether refresh oidc token job is running"
          if ($job.State -ne "Running") {
            Receive-Job -Job $job
            throw "Failed to refresh oidc token"
          }
        }
        echo "##[command]terraform apply -auto-approve -input=false ${{ parameters.siteId }}.tfplan"
        terraform apply -auto-approve -input=false ${{ parameters.siteId }}.tfplan
        echo "Stop oidc token job"
        Stop-Job -Job $job
      workingDirectory: "${{ parameters.stage }}/${{ parameters.siteId }}"
```

**Comment by liamcervante** [comment] 2024-08-23 06:42
Duplicate of #35476

**Closed by liamcervante** 2024-08-23 06:42 UTC
Labels: bug, backend/azure, new, duplicate
