### ISSUE TITLE
terraform 0.13beta2 attempts to use `-/gsuite` instead of `deviavir/gsuite`

### ISSUE THREAD

**Issue by lizthegrey** [hashicorp/terraform#25338] opened 2020-06-22 18:05 UTC
### Terraform Version

```
~/bin/terraform version
Terraform v0.13.0-beta2
+ provider registry.terraform.io/-/archive v1.3.0
+ provider registry.terraform.io/-/null v2.1.2
+ provider registry.terraform.io/-/template v2.1.2
+ provider registry.terraform.io/deviavir/gsuite v0.1.47
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    gsuite = {
      source  = "deviavir/gsuite"
      version = "0.1.47"
    }
    archive = {
      source = "hashicorp/archive"
    }
    aws = {
      source = "hashicorp/aws"
    }
    null = {
      source = "hashicorp/null"
    }
    template = {
      source = "hashicorp/template"
    }
  }
}

provider "gsuite" {
  credentials             = var.gsuite_credentials
  impersonated_user_email = "lizf@honeycomb.io"
  oauth_scopes = [
    "https://www.googleapis.com/auth/admin.directory.user",
    "https://www.googleapis.com/auth/admin.directory.userschema",
  ]
}
```

### Debug Output
```
- Finding latest version of -/gsuite...
2020/06/22 14:04:25 [DEBUG] GET https://registry.terraform.io/v1/providers/-/gsuite/versions
2020/06/22 14:04:25 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/gsuite/versions
```

### Expected Behavior

The "missing" `registry.terraform.io/-/gsuite` should map to `registry.terraform.io/deviavir/gsuite v0.1.47`

### Actual Behavior

```
- Finding latest version of -/gsuite...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/gsuite:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/gsuite
```

### Steps to Reproduce

1. `terraform init`

### Additional Context

Terraform 0.13beta2 bug

### References

n/a

**Comment by lizthegrey** [comment] 2020-06-22 18:08
also happens when gsuite version number is changed to `0.1.52` from `0.1.47`

**Comment by alisdair** [comment] 2020-06-22 18:37
@lizthegrey Thanks for reporting this issue!

I've tried to reproduce the bug using the configuration from your report, using Terraform 0.13.0-beta2, but `init` succeeds:

```shellsession
$ terraform-0.13.0-beta2 init

Initializing the backend...

Initializing provider plugins...
- Finding deviavir/gsuite versions matching "0.1.47"...
- Installing deviavir/gsuite v0.1.47...
- Installed deviavir/gsuite v0.1.47 (self-signed, key ID AD9970F98EB884FD)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Does your full configuration use nested modules? If so, this may be a duplicate of #25312 which was just fixed today in #25334.

**Comment by lizthegrey** [comment] 2020-06-22 18:49
yes, the full configuration has `terraform/version.tf` and `terraform/base/version.tf` and I'm running `terraform init` inside of the `base/` directory.

However, only the `base/version.tf` mentions gsuite provider.

**Comment by alisdair** [comment] 2020-06-23 15:14
While I haven't been able to reproduce this exact issue myself, from my understanding of what's happening here I think this issue is likely the same as #25346.

My assumptions are:

- You have some previous state from the `gsuite` provider
- This state was created with v0.12 with the provider manually installed locally

If that's correct, then the fix should be migrating the provider name in your state using the `terraform state replace-provider` command. That is:

```
terraform state replace-provider -- -/gsuite registry.terraform.io/deviavir/gsuite
```

Once complete, run `terraform init`, which should now succeed, and then `terraform plan`, `apply`, and so on should work as normal.

Could you try this and let us know whether or not it fixes the issue? Thanks in advance!

**Comment by lizthegrey** [comment] 2020-06-23 15:15
> While I haven't been able to reproduce this exact issue myself, from my understanding of what's happening here I think this issue is likely the same as #25346.
> 
> My assumptions are:
> 
> * You have some previous state from the `gsuite` provider
> * This state was created with v0.12 with the provider manually installed locally
> 
> If that's correct, then the fix should be migrating the provider name in your state using the `terraform state replace-provider` command. That is:
> 
> ```
> terraform state replace-provider -- -/gsuite registry.terraform.io/deviavir/gsuite
> ```
> 
> Once complete, run `terraform init`, which should now succeed, and then `terraform plan`, `apply`, and so on should work as normal.
> 
> Could you try this and let us know whether or not it fixes the issue? Thanks in advance!

Nailed the reproduction and similar bug. I'll try your fix.

**Comment by alisdair** [comment] 2020-07-01 19:34
[We've improved the 0.13 upgrade guide to clarify this problem](https://github.com/hashicorp/terraform/blob/master/website/upgrade-guides/0-13.html.markdown). I'm closing this issue for now, but please let us know if the above fix doesn't work once you have a chance to test it.

**Closed by alisdair** 2020-07-01 19:34 UTC
Labels: reproduced, v0.13
