### ISSUE TITLE
When there is not enough memory,  terraform exits with a long error trace

### ISSUE THREAD

**Issue by kpanic9** [hashicorp/terraform#30550] opened 2022-02-18 04:00 UTC
### Terraform Version

```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.74.3

Your version of Terraform is out of date! The latest version
is 1.1.6. You can update by downloading from https://www.terraform.io/downloads.html
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Terraform should log a more understandable error message.

### Actual Behavior

Terraform command exists without unlocking the state lock and outputs below error message.
```
[14m]/working/scs-env/corp/master/security (SCS-1391_update_corp_accounts_to_Terraform_0.14)$ terraform apply
Acquiring state lock. This may take a few moments...
2022/02/17 13:44:33 [INFO] Terraform version: 0.14.11  
2022/02/17 13:44:33 [INFO] Go runtime version: go1.15.6
2022/02/17 13:44:33 [INFO] CLI args: []string{"terraform", "apply"}
2022/02/17 13:44:33 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2022/02/17 13:44:33 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2022/02/17 13:44:33 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2022/02/17 13:44:33 [DEBUG] ignoring non-existing provider search directory /root/.terraform.d/plugins
2022/02/17 13:44:33 [DEBUG] ignoring non-existing provider search directory /root/.local/share/terraform/plugins
2022/02/17 13:44:33 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2022/02/17 13:44:33 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2022/02/17 13:44:33 [INFO] CLI command args: []string{"apply"}
2022/02/17 13:44:33 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 2493291232
2022/02/17 13:44:33 [TRACE] Preserving existing state lineage "49d4e39d-dabb-4a1c-ff88-789eb7f8b828"
2022/02/17 13:44:33 [TRACE] Preserving existing state lineage "49d4e39d-dabb-4a1c-ff88-789eb7f8b828"
2022/02/17 13:44:33 [TRACE] Meta.Backend: working directory was previously initialized for "s3" backend
2022/02/17 13:44:33 [TRACE] Meta.Backend: using already-initialized, unchanged "s3" backend configuration
2022/02/17 13:44:33 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2022/02/17 13:44:33 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/02/17 13:44:35 [TRACE] Meta.Backend: instantiated backend of type *s3.Backend
2022/02/17 13:44:35 [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2022/02/17 13:44:35 [TRACE] getproviders.SearchLocalDirectory: .terraform/providers is a symlink to .terraform/providers
2022/02/17 13:44:35 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v3.74.1 for darwin_amd64 at .terraform/providers/registry.terraform.io/hashicorp/aws/3.74.1/darwin_amd64
2022/02/17 13:44:35 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v3.74.1 for linux_amd64 at .terraform/providers/registry.terraform.io/hashicorp/aws/3.74.1/linux_amd64
2022/02/17 13:44:35 [TRACE] providercache.fillMetaCache: ignoring .terraform/providers/registry.terraform.io/hashicorp/aws/3.74.1/darwin_amd64 because it is for darwin_amd64, not linux_amd64
2022/02/17 13:44:35 [TRACE] providercache.fillMetaCache: including .terraform/providers/registry.terraform.io/hashicorp/aws/3.74.1/linux_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 3.74.1
2022/02/17 13:44:38 [DEBUG] checking for provisioner in "."
2022/02/17 13:44:38 [DEBUG] checking for provisioner in "/usr/local/bin"
2022/02/17 13:44:38 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2022/02/17 13:44:38 [TRACE] Meta.Backend: backend *s3.Backend does not support operations, so wrapping it in a local backend
2022/02/17 13:44:38 [INFO] backend/local: starting Apply operation
2022/02/17 13:44:38 [TRACE] backend/local: requesting state manager for workspace "default"
2022/02/17 13:44:39 [TRACE] backend/local: requesting state lock for workspace "default"
o:Acquiring state lock. This may take a few moments...
e:
Error: Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
Lock Info:
  ID:        xxxx-xxxx-xxxx-xxxx-xxxx
  Path:      S3_BUCKET_NAME/FOLDER/terraform.tfstate
  Operation: OperationTypeApply
  Who:       root@<container-id>
  Version:   0.14.11
  Created:   2022-02-17 02:43:31.050881 +0000 UTC
  Info:      


Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
```

### Steps to Reproduce

Run 'terraform plan' or 'terraform apply' from a Docker container/instance which doesn't have enough memory where there are large amount of resources managed by terraform.

**Comment by jbardin** [comment] 2022-02-28 18:50
HI @kpanic9,

Can you confirm if this i still an issue when using a current Terraform release? Terraform is now executed slightly differently, and the log output is no longer handled across multiple processes.

**Comment by kpanic9** [comment] 2022-03-01 10:33
Hi @jbardin
Unfortunately we are still using Terraform 0.14 and haven't started migrating to Terraform v1. I'll provide an update as soon as we start the work. 
Meantime if anyone using Terraform latest version can update the issue that would be great.

**Comment by jbardin** [comment] 2022-03-01 21:37
Thanks @kpanic9,

Since this appears to be a result of the process handling within the docker container, and Terraform v1.1 is not going to be sending core logs between any process showing no output in an overly constrained environment, I'm going to close this for now. That's not to say that it would be impossible to get unexpected output from a provider process in similar circumstances, but if that is because the terraform process was terminated unexpectedly due to system limitations, that output is beyond our control.

If you find that there is still a problem after upgrading feel free to reply here or file a new issue with the reproduction case.

Thanks!

**Closed by jbardin** 2022-03-01 21:37 UTC
Labels: bug, confirmed
