### ISSUE TITLE
Terraform remote status for config information

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/terraform#4494] opened 2016-01-04 18:47 UTC
There is currently no command to view the existing remote configuration on a terraform project. A command such as `terraform remote status` would be helpful to see how the remote config was set up, especially since `terraform remote config` is pretty much a set it and forget it command.

It would be helpful if the status showed if remote storage is enabled, what kind of backend was used, and any backend-specific config with the sensitive data scrubbed. For example, if the S3 backend was used it would be helpful to know what `bucket` and `key` (path to the state file) was used for that specific project.

I realize that this information is already captured in `terraform.tfstate`, but it would be more convenient if there was a CLI command that would directly output this.

**Comment by jen20** [comment] 2016-01-04 20:17
Hi @cleung2010! I agree this would be a useful addition to the command line interface of Terraform. @phinze @catsby do you know if there were concerns about implementing this in the past?

**Comment by MikeSchuette** [comment] 2016-01-06 23:17
This seems to be a dupe of #3991

**Comment by phinze** [comment] 2016-01-07 14:28
Good call @MikeSchuette -> merging with #3991

**Closed by phinze** 2016-01-07 14:28 UTC
Labels: core, enhancement
