### ISSUE TITLE
Terraform Commands docs are not versioned

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform#22953] opened 2019-09-30 14:37 UTC
https://www.terraform.io/docs/commands/index.html is not versioned. There are constantly flag additions/removals - for example #22951, command additions/removals - for example terraform 0.12checklist exists in v0.11, but does not exist in terraform v0.12.

**Comment by mildwonkey** [comment] 2019-09-30 16:45
Hi @ialidzhikov ! Thanks for opening this. It's certainly something we're aware of - and sorry about!

I am going to close this as a duplicate of #12941. I suggest that you go and add a 👍 to that issue - thanks!

**Closed by mildwonkey** 2019-09-30 16:45 UTC
Labels: enhancement
