### ISSUE TITLE
Crashing on `terraform init` when run in python subprocess

### ISSUE THREAD

**Issue by aloey** [hashicorp/terraform#24420] opened 2020-03-20 17:06 UTC
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
# providers.tf
provider "aws" {
  region  = "us-east-1"
}
```
```hcl
# main.tf
resource "random_string" "random" {
  length = 16
  special = false
  lower=true
  upper=false
  number=false
}

variable "default_tags" {
  type    = "map"
  default = {
    "tag_1" = "has_a_value_1"
    "tag_2" = "has_a_value_2"
    "tag_3" = "has_a_value_3"
    "tag_4" = "has_a_value_4"
    "tag_5" = "has_a_value_5"
    "tag_6" = "has_a_value_6"
    "tag_7" = "has_a_value_7"
    "tag_8" = "has_a_value_8"
    "tag_9" = "has_a_value_9"
    "tag_10" = "has_a_value_10"
    "tag_11" = "has_a_value_11"
    "tag_12" = "has_a_value_12"
    "tag_13" = "has_a_value_13"
    "tag_14" = "has_a_value_14"
    "tag_15" = "has_a_value_15"
    "tag_16" = "has_a_value_16"
    "tag_17" = "has_a_value_17"
    "tag_18" = "has_a_value_18"
    "tag_19" = "has_a_value_19"
    "tag_20" = "has_a_value_20"
    "tag_21" = "has_a_value_21"
    "tag_22" = "has_a_value_22"
    "tag_23" = "has_a_value_23"
    "tag_24" = "has_a_value_24"
    "tag_25" = "has_a_value_25"
    "tag_26" = "has_a_value_26"
    "tag_27" = "has_a_value_27"
    "tag_28" = "has_a_value_28"
    "tag_29" = "has_a_value_29"
    "tag_30" = "has_a_value_30"
    "tag_31" = "has_a_value_31"
    "tag_32" = "has_a_value_32"
    "tag_33" = "has_a_value_33"
    "tag_34" = "has_a_value_34"
    "tag_35" = "has_a_value_35"
    "tag_36" = "has_a_value_36"
    "tag_37" = "has_a_value_37"
    "tag_38" = "has_a_value_38"
    "tag_39" = "has_a_value_39"
    "tag_40" = "has_a_value_40"
    "tag_41" = "has_a_value_41"
    "tag_42" = "has_a_value_42"
    "tag_43" = "has_a_value_43"
    "tag_44" = "has_a_value_44"
    "tag_45" = "has_a_value_45"
    "tag_46" = "has_a_value_46"
    "tag_47" = "has_a_value_47"
    "tag_48" = "has_a_value_48"
    "tag_49" = "has_a_value_49"
  }
}


resource "aws_s3_bucket" "aws_s3_bucket" {
  count  = "2"
  bucket = "${random_string.random.result}-${count.index}"
  acl    = "private"

  versioning {
    enabled = false
  }

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "POST"]
    allowed_origins = ["{some_url}"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }

  tags = var.default_tags
}
```

### Crash Output

https://gist.github.com/aloey/1d5930f535b4b14007b34dc68d43f4ae

### Expected Behavior

No crash happens

### Actual Behavior

Crashes

### Steps to Reproduce

`terraform init`

### Additional Context

I am running this in a python subprocess in the following code and it is only when it is run this way the crash happens. I have tried using the terraform cli in my terminal with the same .tf files and no crash happens.
```python
import subprocess

process = ['/usr/local/bin/terraform', 'init']
cwd = '{absolute_path_to_directory_that_contains_above .tf files}'
env = {
    'AWS_ACCESS_KEY_ID': '{aws_access_key}',
    'AWS_SECRET_ACCESS_KEY': '{aws_secret}'
}
proc = subprocess.Popen(process, bufsize=8192, stdin=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env)

output = []
proc.wait()

while True:
    proc.poll()

    stdout, stderr = proc.communicate()
    if stdout:
       output.append(stdout.decode('utf-8'))
    if stderr:
       output.append(stderr.decode('utf-8'))

    if proc.returncode is not None:
        break
    time.sleep(0.01)

    if proc.returncode != 0:
        raise Exception("Error initializing terraform")
```

**Comment by danieldreier** [comment] 2020-05-13 20:24
I just verified this and was able to reproduce it on 0.12.25.

**Comment by danieldreier** [comment] 2020-05-13 23:22
@aloey based on the workaround suggested in #23840, I was able to work around this by setting HOME explicitly:

```python
import subprocess

process = ['/usr/local/bin/terraform', 'init']
cwd = '/Users/danieldreier/ws/src/repro/24420'
env = {
    'AWS_ACCESS_KEY_ID': '{aws_access_key}',
    'AWS_SECRET_ACCESS_KEY': '{aws_secret}',
    'HOME': '/Users/danieldreier'
}
proc = subprocess.Popen(process, bufsize=8192, stdin=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env)

output = []
proc.wait()

while True:
    proc.poll()

    stdout, stderr = proc.communicate()
    if stdout:
       output.append(stdout.decode('utf-8'))
    if stderr:
       output.append(stderr.decode('utf-8'))

    if proc.returncode is not None:
        break
    time.sleep(0.01)

    if proc.returncode != 0:
        raise Exception("Error initializing terraform")
```

I'll still queue this up for us, but I wanted to offer you that workaround in the meantime. Thank you for reporting this!

**Comment by danieldreier** [comment] 2020-05-13 23:23
@aloey I'm going to close this in favor of https://github.com/hashicorp/terraform/issues/23840 because they actually found the root issue, which is that HOME is unset. Thank you for reporting this!

**Closed by danieldreier** 2020-05-13 23:23 UTC
Labels: bug, cli, crash, reproduced
