### ISSUE TITLE
Allow variable for dynamic provider alias in TF Resource(s)

### ISSUE THREAD

**Issue by dsantanu** [hashicorp/terraform#27387] opened 2020-12-31 08:03 UTC
### Current Terraform Version
```
Terraform v0.12.29
```

### Use-cases
Under `AWS Organization` we have an `IAM` account and a bunch of other member-accounts. The goal is to create the groups and roles in member/target accounts to allow role-switch between accounts. 
It configures the `IAM` account with all of the groups for the IAM users to assume and switch roles from one to another in various remote account(s). And then deploy the Role(s) and associated Policies in the individual remote/target account that required for switching roles.

In order to run TF on individual target a/c, I need to create an IAM user, a KMS key and a S3 bucket (for state-files) at the minimum in each account and currently there is no way to automate that part, using the single codebase without repeating code as  the `provider` value in resource cannot take a variable and/or `for_each` cannot be used in the `provider "aws" {...}` block.

### Attempted Solutions
The member a/c information comes from the `target_accounts` hash:
```
// Target a/c config
target_accounts = {
  Master = {
    account_id  = "111111111111"
    ....
  }
  Bootstrap = {
    account_id  = "222222222222"
    ....
  } 
}
```
And from there one should be able to iterate over that hash and dynamically generate the provider block, using something like this:  
```
// AWS Members' account
provider "aws" {
  for_each = var.target_accounts
  region   = var.region
  profile  = var.profile
  alias    = "A${each.value.account_id}"

  assume_role {
    role_arn    = "arn:aws:iam::${each.value.account_id}:role/OrganizationAccountAccessRole"
    external_id = "MemberAccess"
  }
}
```
and use that to create, say, IAM user in each member account like this:
```
resource "aws_iam_user" "tf_runner" {
  for_each = var.target_accounts
  name     = "${each.key}_Runner"
  path     = "/"

  force_destroy = true
  provider      = "aws.A${each.value.account_id}"
}
```
Right now it's not possible to do either. The individual `provider` block still can be generated in a .tf file using a wrapper script outside of TF, if it's really super hard to provide the support for `for_each` and/or `count` but not being able to pass the `provider` string as a variable in resource, forces us bloating up the code with a lot of duplication to do the same thing for each account for each AWS service. It also need modifying the core code-base every time an element is added or removed from the `target_accounts` hash, which is not really efficient and opens up door for copy/paste errors.
  
### Proposal
Please allow:
1. Use of variable in the `provider` alias in Resources
2. Additionally, use of `count`/`for_each` in the provider block 

### References
- #11578
- #1819
- #9448
- #3656

**Comment by jbardin** [comment] 2021-01-04 13:43
Marking as a duplicate of #25244

Thanks!

**Closed by jbardin** 2021-01-04 13:43 UTC
Labels: enhancement, new
