### ISSUE TITLE
On modification of Lambda Function unexpected EOF

### ISSUE THREAD

**Issue by moesy** [hashicorp/terraform#7928] opened 2016-08-03 01:24 UTC
Hi there,
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- aws_lambda_function
### Terraform Configuration Files

```
resource "aws_lambda_function" "lambda_function" {
    filename = "${var.payload}"
    function_name = "${var.function_name}"
    description = "${var.function_description}"
    handler = "${var.lambda_handler}"
    role = "${aws_iam_role.lambda_iam_role.arn}"
    memory_size = 128
    runtime = "python2.7"
    timeout = "${var.lambda_function_timeout}"
    source_code_hash = "${base64sha256(file("${var.payload}"))}"
}

```
### Expected Behavior

My lambda function should be updated using my new payload as it did on the initial tf-apply.
### Actual Behavior

What actually happened?

aws_lambda_function.lambda_function: Modifying...
  source_code_hash: "SIkayO24CKhOw44UsmJApujG38OezkjupMOvCv6Gv4o=" => "QNmgKwmlmZoBFftRmLgd71ZAGPKZtI1Yn2hr1M70Bx8="
Error applying plan:                                                                                                                                                                                                

1 error(s) occurred:                                                                                                                                                                                                
- aws_lambda_function.lambda_function: unexpected EOF  

Terraform does not automatically rollback in the face of errors.  
Instead, your Terraform state file has been partially updated with  
any resources that successfully completed. Please address the error  
above and apply again to incrementally change your infrastructure.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
on a fresh resource
1. `terraform apply`
2. make some changes rezip the payload
3. Terraform apply

**Comment by radeksimko** [comment] 2016-08-03 18:09
Hi @moesy,
`var.payload` - I assume that's a path to a file, not an _actual payload_ (i.e. content of a file)?

**Comment by moesy** [comment] 2016-08-03 19:05
@radeksimko correct it is the path to the zip file.

**Comment by radeksimko** [comment] 2016-08-03 19:13
@moesy I see, to better understand the problem & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by moesy** [comment] 2016-08-06 22:33
@radeksimko Thank you I will, I'm away from the system that is running that project but will update back here in the next day or 2.

**Comment by mitchellh** [comment] 2016-12-01 14:45
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!

**Closed by mitchellh** 2016-12-01 14:45 UTC
Labels: bug, provider/aws, waiting-response

**Comment by mdlavin** [comment] 2017-12-07 12:44
I was hitting an 'unexpected EOF' failure modifying an existing lambda as well, and it seems to have been caused by trying to move the lambda from being associated with a VPC to not. Once I kept the vpc_config values the same, the modification was successful.

**Comment by moesy** [comment] 2017-12-08 05:00
@mdlavin that is interesting to know, I don't deploy functions to lambda in this manner anymore but I don't believe I was deploying in a VPC.
