### ISSUE TITLE
output command includes "EOT"

### ISSUE THREAD

**Issue by tgross** [hashicorp/terraform#27451] opened 2021-01-08 19:41 UTC
While testing Terraform 0.15-alpha against Nomad's nightly E2E tests, I encountered an unexpected change in the output of `terraform output`. We use `terraform output` in a subshell to load environment variables obtained from Terraform data into our test environment: [outputs.tf#L41-L52](https://github.com/hashicorp/nomad/blob/v1.0.1/e2e/terraform/outputs.tf#L41-L52). But the output of `terraform output` has changed to include the literal `EOT`:

### Terraform Configuration Files

The actual files are in the link above, but a minimal reproduction is:

```terraform
output "environment" {
  description = "demonstrating the bug"
  value       = <<EOM
some value
EOM
}
```

Note that the template literal marker I've used here is `EOM` and not `EOT`, but `EOT` is always what's being output.

### Expected Behavior

```
$ $(terraform output environment)
$ echo $NOMAD_E2E
1
```

### Actual Behavior

The output of `terraform output` now includes the string literal "EOT":

```
$ $(terraform output environment)
zsh: command not found: <<EOT

$ terraform output environment
<<EOT
export NOMAD_ADDR=http://<redacted>:4646
export CONSUL_HTTP_ADDR=http://<redacted>:8500
export VAULT_ADDR=http://<redacted>:8200
export NOMAD_E2E=1
export NOMAD_TOKEN=

export VAULT_TOKEN=<redacted>



EOT

```

### Steps to Reproduce

```
$ terraform init
$ terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

environment = <<EOT
some value

EOT
$ terraform output environment
<<EOT
some value

EOT
```

**Comment by alisdair** [comment] 2021-01-08 19:55
Hi @tgross, thanks for reporting this.

Terraform is behaving as designed here. The `output` command is intended for human-readable output of any HCL value, which means that you should be able to copy the value into a Terraform configuration and use it directly. As a result, a multi-line string is output using the heredoc syntax by default.

The heredoc terminator literal is `EOT` here because that is the standard one used in documentation. The delimiter used in configuration (if the output is for some reason a literal value) is not available at this point, so can't be used.

For your specific use case, it looks like you want the multi-line string output without surrounding quotes or heredoc syntax. In that case, try using [the new `-raw` flag for the `terraform output` command](https://www.terraform.io/docs/commands/output.html#raw):

```shellsession
$ tf apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

environment = <<EOT
export NOMAD_ADDR=http://<redacted>:4646
export CONSUL_HTTP_ADDR=http://<redacted>:8500
export VAULT_ADDR=http://<redacted>:8200
export NOMAD_E2E=1
export NOMAD_TOKEN=

EOT
$ tf output -raw environment
export NOMAD_ADDR=http://<redacted>:4646
export CONSUL_HTTP_ADDR=http://<redacted>:8500
export VAULT_ADDR=http://<redacted>:8200
export NOMAD_E2E=1
export NOMAD_TOKEN=
```

I hope this makes sense! I'm closing this issue for now as I don't think there's a bug here.

**Closed by alisdair** 2021-01-08 19:55 UTC
Labels: bug, new

**Comment by tgross** [comment] 2021-01-08 20:06
Thanks @alisdair! With some testing of older versions it looks like I just missed that change between TF0.13 and TF0.14 😊
