### ISSUE TITLE
Upgrade to 0.13 with Custom Provider Fails Looking for Unknown Provider

### ISSUE THREAD

**Issue by kevinbirch** [hashicorp/terraform#26134] opened 2020-09-04 16:19 UTC
### Terraform Version

```
$ terraform version
Terraform v0.13.2
+ provider registry.terraform.io/-/google v3.37.0
+ provider registry.terraform.io/-/google-beta v3.37.0
+ provider registry.terraform.io/-/helm v1.3.0
+ provider registry.terraform.io/-/kubernetes v1.13.1
+ provider registry.terraform.io/-/local v1.4.0
+ provider registry.terraform.io/-/mysql v1.9.0
+ provider registry.terraform.io/-/null v2.1.2
+ provider registry.terraform.io/-/postgresql v1.7.1
+ provider registry.terraform.io/-/random v2.3.0
+ provider registry.terraform.io/-/tls v2.2.0
+ provider registry.terraform.io/hashicorp/google v3.37.0
+ provider registry.terraform.io/hashicorp/google-beta v3.37.0
+ provider registry.terraform.io/hashicorp/helm v1.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.1
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0
+ provider registry.terraform.io/terraform-providers/postgresql v1.7.1
+ provider terraform.mydomain.com/maven/hush v1.0.0
```

### Terraform Configuration Files

```terraform
terraform {
  backend "gcs" {
    bucket = "mybucket"
    prefix = "prefix"
  }

  required_version = ">= 0.13"

  required_providers {
    google = {
      source = "hashicorp/google"
    }
    google-beta = {
      source = "hashicorp/google-beta"
    }
    hush = {
      source  = "terraform.mydomain.com/maven/hush"
      version = "1.0.0"
    }
  }
}
```

### Debug Output

https://gist.github.com/kevinbirch/ae7ea166e1e16f50739a07bb2eb33b24

### Expected Behavior

The init command should have completed successfully.

### Actual Behavior

The following error is shown:

```
Error: Failed to install provider

Error while installing hashicorp/hush: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/hush
```

### Steps to Reproduce

1.  `terraform 0.13upgrade`
2.  Update `terraform` block
2.  `terraform init`

### Additional Context

I have a custom provider called “hush” and it is vendored in the git repo. This repo has several root modules and I’ve successfully migrated most of those to 0.13, but one is not working.

I’ve tried running `init` both using the existing `.terraform` data and with a clean slate, both fail with the same error. 

Trying to replace this mystery provider fails:

```
$ terraform state replace-provider registry.terraform.io/hashicorp/hush terraform.mydomain.com/maven/hush
No matching resources found.
```

So, I have no idea where the hashicorp/hush reference originates. It doesn’t seem to be in the state file (I did a `state pull` and searched the file), and it’s not in my .tf files.

The one thing that is different about this root module than the others that worked is that this one uses another module which also has a provider configuration.

Here is the output from `terraform providers`:

```
*$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/google]
├── provider[registry.terraform.io/hashicorp/google-beta]
├── provider[terraform.mydomain.com/maven/hush] 1.0.0
├── module.bq_agent_looker
│   └── provider[registry.terraform.io/hashicorp/google]
├── module.bq_fivetran
│   ├── provider[registry.terraform.io/hashicorp/google]
│   └── provider[registry.terraform.io/hashicorp/random]
├── module.common
├── module.dbt_environment
│   ├── provider[registry.terraform.io/hashicorp/hush]
│   ├── provider[registry.terraform.io/hashicorp/tls]
│   └── provider[registry.terraform.io/hashicorp/google]
├── module.research
│   ├── provider[registry.terraform.io/hashicorp/google-beta]
│   ├── provider[registry.terraform.io/hashicorp/google]
│   ├── provider[registry.terraform.io/hashicorp/random]
│   ├── module.notebooks_agent
│       └── provider[registry.terraform.io/hashicorp/google]
│   ├── module.research_vpc
│       ├── provider[registry.terraform.io/hashicorp/random]
│       └── provider[registry.terraform.io/hashicorp/google]
│   └── module.common
└── module.system
    ├── provider[registry.terraform.io/hashicorp/google]
    ├── module.cloud-sql-proxy-agent
        └── provider[registry.terraform.io/hashicorp/google]
    ├── module.dbt
        ├── provider[registry.terraform.io/terraform-providers/postgresql]
        ├── provider[registry.terraform.io/hashicorp/random]
        ├── provider[registry.terraform.io/hashicorp/google]
        ├── provider[registry.terraform.io/hashicorp/helm]
        ├── provider[registry.terraform.io/hashicorp/kubernetes]
        ├── provider[registry.terraform.io/hashicorp/local]
        ├── provider[registry.terraform.io/hashicorp/null]
        ├── module.postgres
            ├── provider[registry.terraform.io/hashicorp/google]
            └── provider[registry.terraform.io/hashicorp/random]
        ├── module.private-service
            ├── provider[registry.terraform.io/hashicorp/google]
            └── provider[registry.terraform.io/hashicorp/random]
        ├── module.base-monitoring
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.dbt-cluster
            ├── provider[registry.terraform.io/hashicorp/google]
            ├── provider[registry.terraform.io/hashicorp/google-beta]
            ├── provider[registry.terraform.io/hashicorp/random]
            └── module.common
        ├── module.dbt_a
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.dbt_nfs-client-provisioner
            └── provider[registry.terraform.io/hashicorp/helm]
        ├── module.gcs_agent
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.gke_agent
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.dbt-workers
            ├── provider[registry.terraform.io/hashicorp/google-beta]
            ├── provider[registry.terraform.io/hashicorp/random]
            └── provider[registry.terraform.io/hashicorp/google]
        └── module.bastion
            ├── provider[registry.terraform.io/hashicorp/google-beta]
            ├── provider[registry.terraform.io/hashicorp/random]
            ├── provider[registry.terraform.io/hashicorp/google]
            ├── module.agent
                └── provider[registry.terraform.io/hashicorp/google]
            └── module.managed-instance-group
                ├── provider[registry.terraform.io/hashicorp/random]
                └── provider[registry.terraform.io/hashicorp/google]
    ├── module.looker
        ├── provider[registry.terraform.io/hashicorp/random]
        ├── provider[registry.terraform.io/hashicorp/google]
        ├── provider[registry.terraform.io/hashicorp/google-beta]
        ├── provider[registry.terraform.io/terraform-providers/mysql]
        ├── module.agent
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.bastion
            ├── provider[registry.terraform.io/hashicorp/google-beta]
            ├── provider[registry.terraform.io/hashicorp/random]
            ├── provider[registry.terraform.io/hashicorp/google]
            ├── module.agent
                └── provider[registry.terraform.io/hashicorp/google]
            └── module.managed-instance-group
                ├── provider[registry.terraform.io/hashicorp/google]
                └── provider[registry.terraform.io/hashicorp/random]
        ├── module.dns
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.managed-instance-group
            ├── provider[registry.terraform.io/hashicorp/google]
            └── provider[registry.terraform.io/hashicorp/random]
        ├── module.mysql
            ├── provider[registry.terraform.io/hashicorp/random]
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.private-service
            ├── provider[registry.terraform.io/hashicorp/google]
            └── provider[registry.terraform.io/hashicorp/random]
        └── module.vpc
            ├── provider[registry.terraform.io/hashicorp/google]
            └── provider[registry.terraform.io/hashicorp/random]
    └── module.bq
        ├── provider[registry.terraform.io/hashicorp/google]
        ├── provider[registry.terraform.io/hashicorp/random]
        ├── module.bq_agent_dbt_deployment
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.bq_agent_dbt_development
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.bq_agent_api
            └── provider[registry.terraform.io/hashicorp/google]
        ├── module.bq_agent_braze
            └── provider[registry.terraform.io/hashicorp/google]
        └── module.bq_agent_dataset_owner
            └── provider[registry.terraform.io/hashicorp/google]

Providers required by state:

    provider[registry.terraform.io/-/mysql]

    provider[registry.terraform.io/-/kubernetes]

    provider[registry.terraform.io/-/tls]

    provider[registry.terraform.io/-/random]

    provider[registry.terraform.io/-/postgresql]

    provider[registry.terraform.io/-/google-beta]

    provider[registry.terraform.io/-/helm]

    provider[registry.terraform.io/-/local]

    provider[registry.terraform.io/-/google]

    provider[registry.terraform.io/-/null]

    provider[terraform.mydomain.com/maven/hush]
```

**Comment by alisdair** [comment] 2020-09-04 20:34
From your `terraform providers` output:

```
Providers required by configuration:
.
(…)
├── module.dbt_environment
│   ├── provider[registry.terraform.io/hashicorp/hush]
```

This module is where the reference to `hashicorp/hush` is coming from. At a guess, maybe the module has some resources or data sources using the `hush` provider.

Every module which uses a non-default provider must have a `required_providers` block which maps the local name to the full provider source. This is because it's totally valid to have two modules which both have providers called `hush`, but from different sources.

The fix for this should be to add the `required_providers` block to your `dbt_environment` module:

```hcl
terraform {
  required_providers {
    hush = {
      source  = "terraform.mydomain.com/maven/hush"
    }
  }
```

Hope this helps, and sorry about the confusion! I'm closing this issue as it looks like Terraform is working as designed, but please do respond if this doesn't fix the issue and I'll be happy to look further.

**Closed by alisdair** 2020-09-04 20:34 UTC
Labels: bug, new

**Comment by kevinbirch** [comment] 2020-09-07 19:38
Thanks for the help, that was the problem!
