### ISSUE TITLE
Terraform import chomps trailing newlines on command line arguments

### ISSUE THREAD

**Issue by knl** [hashicorp/terraform#22391] opened 2019-08-08 12:09 UTC
### Terraform Version
```
$ terraform -v
Terraform v0.12.6
```

### Terraform Configuration Files
Installed the latest version of https://github.com/tweag/terraform-provider-secret.

```hcl
provider "secret" {}

resource "secret_resource" "newlines" {}
```

```
$ xxd file_ending_with_newline
00000000: 736f 6d65 0a74 6578 740a 0a              some.text..
```

### Debug Output

https://gist.github.com/knl/fe92e317f0e707e77e7902a7667538a4

### Expected Behavior

The import should've imported the value with newlines at the end.

```
$ TF_LOG=debug terraform import secret_resource.newlines "$(cat file_ending_with_newline)"
...
secret_resource.newlines: Importing from ID "some\ntext\n\n"...
...
```

### Actual Behavior
The newlines were chomped, as shown in the gist, but repeating the important parts here:

```
$ TF_LOG=debug terraform import secret_resource.newlines "$(cat file_ending_with_newline)"
...
secret_resource.newlines: Importing from ID "some\ntext"...
...
```

### Steps to Reproduce

```
$ mkdir -p /tmp/terraform-bug
$ cd /tmp/terraform-bug
$ go get -u -v github.com/tweag/terraform-provider-secret
$ mkdir -p terraform.d/plugins/darwin_amd64
$ cp ~/go/bin/terraform-provider-secret terraform.d/plugins/darwin_amd64/
$ echo "some\ntext\n\n" > file_ending_with_newline
$ cat <<EOD >main.tf
provider "secret" {}

resource "secret_resource" "newlines" {}
EOD
terraform init
terraform import secret_resource.newlines "$(cat file_ending_with_newline)"
```

**Comment by apparentlymart** [comment] 2024-07-16 22:47
Hi @knl! Sorry for the very late response on this one... I'm not sure what happened back in 2019 that caused this to have a "question" label but not be treated as such. :confounded: 

Unfortunately I believe the handling of evaluating that interpolation and incorporating it into the command line belongs to your shell rather than to Terraform. I was able to reproduce it on my system using both Terraform _and_ using other commands like `echo`.

I created my own file with multiple newlines at the end of it and then ran `TF_LOG=trace terraform version "$(cat file-with-trailing-newlines)"`, relying on the fact that current `terraform version` silently ignores any arguments:

```
2024-07-16T15:27:57.138-0700 [INFO]  Terraform version: 1.8.0 dev
2024-07-16T15:27:57.138-0700 [DEBUG] using github.com/hashicorp/go-tfe v1.41.0
2024-07-16T15:27:57.138-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.2-0.20240214205714-fe0951f68911
2024-07-16T15:27:57.138-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-07-16T15:27:57.138-0700 [DEBUG] using github.com/zclconf/go-cty v1.14.1
2024-07-16T15:27:57.138-0700 [INFO]  Go runtime version: go1.21.5
2024-07-16T15:27:57.138-0700 [INFO]  CLI args: []string{"terraform", "version", "hello\nworld"}
```

The last line of this output (which I truncated, since the remaining log lines are irrelevant) indicates that the argument passed to Terraform already had the trailing newlines (after "world") removed.

I also confirmed this with `echo`:

```shellsession
$ cat file-with-trailing-newlines 
hello
world



$ echo "$(cat file-with-trailing-newlines)"
hello
world
$
```

Note that `echo` by default adds its own newline character to the end of what it is printing, so the second command above seems to have treated the interpolation the same way as using the similar interpolation with Terraform: only the newline between `hello` and `world` was preserved by my shell.

I'm using Bash as my shell here, and for Bash the language feature we're using is called [Command Substitution](https://tldp.org/LDP/abs/html/commandsub.html) and its documentation confirms that it strips trailing newlines, which I think makes sense because it's most commonly used to capture the output of commands that generate a result that ends with a newline character.

This also seems to be true for the simpler form that relies only on I/O redirection:

```shellsession
$ echo "$(<file-with-trailing-newlines)"
hello
world
```

I don't know of any alternative solution for Bash that can be done in a single statement, but writing an inline string that ends with multiple newlines seems to demonstrate that Terraform is only making use of what the shell passed it and isn't actually "chomping" the arguments itself:

```shellsession
$ TF_LOG=trace terraform version 'hello
> world
> 
> 
> '
2024-07-16T15:46:00.694-0700 [INFO]  Terraform version: 1.8.0 dev
2024-07-16T15:46:00.695-0700 [DEBUG] using github.com/hashicorp/go-tfe v1.41.0
2024-07-16T15:46:00.695-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.2-0.20240214205714-fe0951f68911
2024-07-16T15:46:00.695-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-07-16T15:46:00.695-0700 [DEBUG] using github.com/zclconf/go-cty v1.14.1
2024-07-16T15:46:00.695-0700 [INFO]  Go runtime version: go1.21.5
2024-07-16T15:46:00.695-0700 [INFO]  CLI args: []string{"terraform", "version", "hello\nworld\n\n\n"}
```

Therefore unfortunately I don't think there's anything we can do in Terraform itself to achieve the behavior you wanted. The problem here is in your shell, not in Terraform. Therefore I'm going to close this. Sorry again for the very, very slow response!

**Closed by apparentlymart** 2024-07-16 22:47 UTC
Labels: bug, cli, v0.12
