### ISSUE TITLE
Terraform import aws_instance -- keep when planning

### ISSUE THREAD

**Issue by ajcrites** [hashicorp/terraform#9057] opened 2016-09-26 16:21 UTC
If you `terraform import` an `aws_instance` (and possibly other resources), Terraform will plan to destroy the resource if there is no configuration for it.

This makes sense, but even if you have a corresponding configuration for the same resource (matching name, tags, security groups, etc.) Terraform will still plan to destroy this resource and create a new one from the configuration.

There should be a way to match imported resources with corresponding configuration so future changes do not impact the resource.

### Terraform Version
0.7.4

### Affected Resource(s)
`aws_instance`, but may be an issue in Terraform core.

### Terraform Configuration Files
https://gist.github.com/ajcrites/b05b0b02535048e93fc8fb36a241d50e

### Debug Output
https://gist.github.com/ajcrites/373fedc8d38dade5a777380e095fe756

### Expected Behavior
When you `terraform import` a resource and you `plan` with a configuration for it, the resource should be kept and not destroyed and recreated.

### Actual Behavior
`terraform plan` will plan to destroy the imported resource and create a new one from configuration

### Steps to Reproduce
1. `terraform import` an aws_instance into an existing state file
2. `terraform plan` with the same state file

Terraform will plan to destroy the imported resource and create a new one from configuration *even* if the resource should match the configuration.

**Comment by apparentlymart** [comment] 2016-09-27 05:31
Hi @ajcrites! Sorry for the confusing behavior here.

It looks like what happened here is that you've imported the resource into the root module but added its configuration into a child module called "base":

```
- aws_instance.clinipak_server

+ module.base.aws_instance.clinipak_server
```

Terraform sees these as two different resources.

To avoid this, you can write out that full path `module.base.aws_instance.clinipak_server` as the target address in the import command:

```
terraform import module.base.aws_instance.clinipak_server i-03bfed86619c425ba
```

Since you already have this in your state file, you can alternatively move the state into the child module without re-importing it:

```
terraform state mv aws_instance.clinipak_server module.base.aws_instance.clinipak_server
```

I'm going to close this out because it seems like Terraform is working the way it was intended, even though the behavior is clearly not super-intuitive in this case. Feel free to re-open if I've misunderstood the problem or if my suggestions don't work out.

**Closed by apparentlymart** 2016-09-27 05:31 UTC
Labels: question
