### ISSUE TITLE
Crash on using tab completion

### ISSUE THREAD

**Issue by squeegibo** [hashicorp/terraform#31132] opened 2022-05-25 22:54 UTC
### Terraform Version

```
Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.13.0
```

### Terraform Configuration Files

```terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2.13.0"
    }
  }
}

provider "docker" {}

resource "docker_image" "nginx" {
  name         = "nginx:latest"
  keep_locally = false
}

resource "docker_container" "nginx" {
  image = docker_image.nginx.latest
  name  = "tutorial"
  ports {
    internal = 80
    external = 8000
  }
}
```

### Debug Output

Stack trace:
runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x251f100, 0xc00005c468})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/mitchellh/cli.(*CLI).processArgs(0xc0000aa000)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:688 +0x9ec
github.com/mitchellh/cli.(*CLI).init(0xc0000aa000)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:392 +0x3e9
sync.(*Once).doSlow(0xc000058004?, 0x34?)
        /usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/mitchellh/cli.(*CLI).Subcommand(...)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:276
main.realMain()
        /home/circleci/project/project/main.go:240 +0xfb5
main.main()

### Expected Behavior

I'm not sure what I expected, because I'm new to Terraform. I was following the tutorial and tried to tab-complete the destroy command on the command line and it crashed. I guess I expected it to either tab-complete or not, but not crash.

### Actual Behavior

I hit tab and got a stack trace and block saying 
bash: compgen: warning: -C option may not
work as you expect

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
followed by the stack trace

### Steps to Reproduce

I downloaded and installed docker and terraform on Ubuntu, following the "getting started" instructions for each. I initialized with
sudo terraform init
checked that the NGINX server was running by looking at the website and running
sudo terraform ps
walked away for a while, found my ssh session had crashed so reconnected and reconnected to the GNU screen session I was running everything in, and tried to stop the container with sudo terraform destroy, but hit tab after
sudo terraform des<TAB>
and that's when it crashed

### Additional Context

I'm running all the commands in a GNU screen session
My login is not in the docker group, so I'm running all the commands using sudo
I'm running Ubuntu 20.04.4 LTS

**Comment by moss2k13** [comment] 2022-05-26 09:48
I can confirm it crashes on ubuntu 22, but I'm not able to say whether the stack trace means the same cause:

### Versions
```
 2022-05-26 11:32:01 ⌚  PF-3ASX5A in ~
○ → lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

# it fails on a snap version 1.2.1 as well
 2022-05-26 11:34:15 ⌚  PF-3ASX5A in ~
○ → apt list --installed terraform
Listing... Done
terraform/jammy,now 1.2.1 amd64 [installed]
N: There are 59 additional versions. Please use the '-a' switch to see them.

 2022-05-26 11:34:28 ⌚  PF-3ASX5A in ~
○ → cat /etc/apt/sources.list.d/archive_uri-https_apt_releases_hashicorp_com-jammy.list 
deb [arch=amd64] https://apt.releases.hashicorp.com jammy main
# deb-src [arch=amd64] https://apt.releases.hashicorp.com jammy main

2022-05-26 11:34:28 ⌚  PF-3ASX5A in ~
○ → terraform --version
Terraform v1.2.1
on linux_amd64
````

### Steps to Reproduce
I've switched to root user to check whether it is related but it fails on root as well:
```
root@PF-3ASX5A:~# curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
root@PF-3ASX5A:~# apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
root@PF-3ASX5A:~# apt-get update && sudo apt-get install terraform

root@PF-3ASX5A:~# terraform -install-autocomplete

root@PF-3ASX5A:~# exit

sudo su -

# i'm hitting tab here to trigger completion
root@PF-3ASX5A:~# terraform 
```

### Debug Output
I've switched to root user to check whether it is related but it fails on root as well:
```
# i'm hitting tab here to trigger completion
root@PF-3ASX5A:~# terraform 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x251f100, 0xc000158240})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/mitchellh/cli.(*CLI).processArgs(0xc0000f3180)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:688 +0x9ec
github.com/mitchellh/cli.(*CLI).init(0xc0000f3180)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:392 +0x3e9
sync.(*Once).doSlow(0xc00004e024?, 0x5?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/mitchellh/cli.(*CLI).Subcommand(...)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:276
main.realMain()
	/home/circleci/project/project/main.go:240 +0xfb5
main.main()
	/home/circleci/project/project/main.go:58 +0x19

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by jbardin** [comment] 2022-05-26 13:01
Thanks for filing the issue @squeegibo!
Duplicate of #31126

**Closed by jbardin** 2022-05-26 13:01 UTC
Labels: bug, new
