### ISSUE TITLE
terraform remote config with s3

### ISSUE THREAD

**Issue by elisehuard** [hashicorp/terraform#5692] opened 2016-03-17 13:28 UTC
Hi, thank you for all the good work.

I am at a loss as to how to use remote config with s3, which would be the easiest for us at the moment.
I'm using version 0.6.13 of terraform, and I have existing, quite complex infrastructure, with the state saved locally in terraform.tfstate

Then I try to switch to remote:

```
➜  terraboot git:(master) ✗ terraform remote config --backend=s3 --backend-config="bucket=kixi-terraform" --backend-config="key=kixi-infra/terraform.tfstate" --backend-config="region=eu-central-1"
Remote state management enabled
Remote state configured and pulled.
➜  terraboot git:(master) ✗ aws s3 cp s3://kixi-terraform/kixi-infra/terraform.tfstate terraform.tfstate.remote
download: s3://kixi-terraform/kixi-infra/terraform.tfstate to ./terraform.tfstate.remote
➜  terraboot git:(master) ✗ diff .terraform/terraform.tfstate terraform.tfstate.remote
➜  terraboot git:(master) ✗ terraform remote push
Failed to read state: Unknown refresh result: Local and remote state conflict, manual resolution required
```

basically, whatever I do after having set up the remote config, it fails with

```
Failed to read state: Unknown refresh result: Local and remote state conflict, manual resolution required
```

Even though there is no difference.

Doing --pull=false as some others suggested just postpones the problem, which occurs whenever I do anything, whether plan, apply, push or pull.  What am I missing or misunderstanding?

**Comment by coen-hyde** [comment] 2016-03-17 16:18
I don't know what is breaking here but I would check your state files to ensure the remote state is configured properly. There should be a section that looks like this:

```json
    "remote": {
        "type": "s3",
        "config": {
            "bucket": "kixi-terraform",
            "key": "kixi-infra/terraform.tfstate",
            "region": "eu-central-1"
        }
    },
```

**Comment by jeroenjacobs1205** [comment] 2016-03-18 09:09
Did you upload the state file manually before executing the remote config command? Because you shouldn't do that. During the configuration of remote config, terraform will do the initial push.

**Comment by elisehuard** [comment] 2016-03-18 10:19
@jeroenjacobs1205 no I didn't , I only used aws cli to compare the state terraform put on s3 later.

**Comment by ftx** [comment] 2016-05-11 08:16
Hello,

I've the exactly same problem, my tfstate are the same localy and on remote S3....
The file is upload with "terraform remote config", no manually.

**Comment by apparentlymart** [comment] 2017-04-04 23:42
Hi @elisehuard, and everyone else who commented here! Sorry for this issue, and sorry we let it languish for so long.

In the mean time since this issue was opened there were several fixes to the robustness of remote state, culminating in a re-architecture of how remote state works in version 0.9. I can't say for certain that this specific issue was fixed since it looks like there were some contextual details at play that I can't replicate to reproduce, but the portion of the code that generated this error (which managed rationalizing the remote persisted state with the local cache) is no longer present since the local state cache doesn't exist at all as of 0.9.

There is also now an explicit interactive workflow from migration from local to remote state as part of the `terraform init` command, rather than it simply piggy-backing onto `terraform remote config` as before.

So while I hesitate slightly given that we weren't able to definitively explain this, I'm going to close this under the assumption that the new remote architecture in 0.9 has addressed it. If anyone encounters strange behavior using the new remote backends system in 0.9, it'd be great if you could open a fresh issue describing the problem so that we can triage and address it separately. Thanks!

**Closed by apparentlymart** 2017-04-04 23:42 UTC
Labels: bug, core
