### ISSUE TITLE
base64 operations should be symmetrical.

### ISSUE THREAD

**Issue by ronjarrell** [hashicorp/terraform#25777] opened 2020-08-07 19:46 UTC
### Terraform Version
0.12.29

```
...
```

### Terraform Configuration Files

```terraform
base64decode(filebase64("/tmp/tf/raw"))
```

### Expected Behavior

Expected the binary blob back.

### Actual Behavior

Result of decoding the string is not valid utf-8

### Steps to Reproduce

Reproduced using terraform console.

### Additional Context

It shouldn't be possible to base64 encode a string that terraform is unwilling to decode again.

In our usecase we're using google kms to encrypt a secret, then base64 encoding the output so we can store it in the tf file.  This has worked just fine for a couple of years, even in 12.*.  But this particular secret for some reason won't base64decode.  unix base64 can decode it, and both unix base64 and tf base64 encode it to the same string.

I'm aware of the Issue #21669, but, again, if terraform can encode it, it should be able to decode it, or refuse to encode it. 

### References

- #21669
[blob.zip](https://github.com/hashicorp/terraform/files/5043377/blob.zip)

**Comment by danieldreier** [comment] 2020-08-10 17:00
I reproduced this using
```hcl
locals {
  example = base64decode(filebase64("${path.module}/example.file"))
}
```

and placing the contents of the downloaded `blob.zip`in `example.file`.

I got:

```

Error: Error in function call

  on repro.tf line 2, in locals:
   2:   example = base64decode(filebase64("${path.module}/example.file"))
    |----------------
    | path.module is "."

Call to function "base64decode" failed: the result of decoding the provided
string is not valid UTF-8.

```

**Comment by mildwonkey** [comment] 2020-08-20 13:45
This is a tricky one, but this is the expected [and documented](https://www.terraform.io/docs/configuration/functions/base64decode.html) behavior:

> Strings in the Terraform language are sequences of unicode characters rather than bytes, so this function will also interpret the resulting bytes as UTF-8. If the bytes after Base64 decoding are not valid UTF-8, this function produces an error.

The problem is not that terraform cannot decode the encoded value, but that the *result* of that decoding is not a string, which is not a surprise when you are encoding a zip file:

```
openssl base64 -in example.file -out encoded
openssl base64 -in  encoded -d
PK
o}Qщ.}}rawUT	�-_�-_ux
                        �
�m�U��o�S<n�����`Z,~(�t _�c��8�s'"��zڣ�2:��LɒuT���ˎ��9`��N�SѢ��n~9J�+�PK
o}Qщ.}}��rawUT�-_ux
                   �PKI�
```

As martin already stated in [the linked issue](https://github.com/hashicorp/terraform/issues/21669#issuecomment-500896874), we are not going to change this behavior, so I am going to close this issue. Thanks!

**Closed by mildwonkey** 2020-08-20 13:45 UTC
Labels: bug, confirmed, v0.12, v0.13

**Comment by ronjarrell** [comment] 2020-09-04 22:39
It actually wan't encoding a zip flle, it was encoding the output from a kms encrypt on google, the zip file just contained the blob that provided the example.

I fully understand your stance on decoding.  My point was you *encoded* it in the first place, but you can't *decode* it?  It's entirely unexpected that I can base64encode a string  in terraform that base64decode tells me is an invalid string.  It must have been an invalid string on the way *in* too!
