### ISSUE TITLE
sometimes terraform apply is not returning errors 

### ISSUE THREAD

**Issue by shaykeren** [hashicorp/terraform#22749] opened 2019-09-10 07:41 UTC
v0.11.11
**output.tf**
```
output "name" {
  value = "${var.name}"
}
```
**variables.test.tfvars**
`name = "${asdsd"`

**variables.tf**
`variable "name" {}`

**Steps to Reproduce**
run the following command repeatedly until you'll get the real error (see below)
`terraform apply -var-file=variables.test.tfvars -no-color -auto-approve`

Apply command should fail because the variable value is not valid, but sometimes the real error is not being returned.

**Expected error :** 
invalid value "variables.test.tfvars" for flag -var-file: Error parsing variables.test.tfvars: At 2:1: literal not terminated

**Comment by teamterraform** [comment] 2019-09-10 16:48
Hi @shaykeren,

Interpolation syntax is not supported inside `.tfvars` files in Terraform 0.11, because root variable values are always literals. Terraform 0.11 simply doesn't evaluate interpolation in these values _at all_, so there is no error to report here.

Terraform 0.12 _does_ parse interpolation sequences in `.tfvars` files, but will return an error if any interpolation sequences refer to functions or other variables. It will also catch the syntax error you were looking for here:

```
Error: Extra characters after interpolation expression

  on terraform.tfvars line 1:
   1: name = "${asdsd"

Expected a closing brace to end the interpolation expression, but found extra
characters.
```

Since Terraform 0.11 is behaving as designed and since Terraform 0.12 _does_ behave the way you expected, we're going to close this now. Terraform 0.11's behavior is now frozen because Terraform 0.11 is no longer under active development. Thanks for reporting it!

**Closed by teamterraform** 2019-09-10 16:48 UTC
Labels: bug, config, v0.11
