### ISSUE TITLE
depends_on fails parsing if points to a resources with count = 0

### ISSUE THREAD

**Issue by synhershko** [hashicorp/terraform#15741] opened 2017-08-05 19:23 UTC
This:

```
resource "aws_emr_cluster" "querying" {
  count = 0

  name          = "Querying"
  release_label = "emr-5.7.0"
  applications  = ["Hadoop", "Hive", "Presto"]

  ec2_attributes {
    subnet_id                         = "${aws_subnet.main.id}"
    emr_managed_master_security_group = "${aws_security_group.allow_all.id}"
    emr_managed_slave_security_group  = "${aws_security_group.allow_all.id}"
    instance_profile                  = "${aws_iam_instance_profile.emr_profile.arn}"
    key_name                          = "${var.keyname}"
  }

  master_instance_type = "m4.large"
  core_instance_type   = "m4.xlarge"
  core_instance_count  = 2

  tags {
    name     = "querying"
  }

  service_role = "${aws_iam_role.iam_emr_service_role.arn}"
}

resource "aws_emr_instance_group" "querying-task-nodes" {
  name                      = "task"
  cluster_id                = "${aws_emr_cluster.querying.id}"
  instance_type             = "m4.xlarge"
  instance_count            = 0

  depends_on = ["aws_emr_cluster.querying"]
}
```

When run with `terraform plan` or `terraform apply` will fail with:

```
aws_emr_instance_group.querying-task-nodes: Resource 'aws_emr_cluster.querying' not found for variable 'aws_emr_cluster.querying.id'
```

Because `aws_emr_cluster.querying` has count = 0 (thus not represented in the planned work graph).

**Comment by chrismathias** [comment] 2018-03-16 14:11
Hi,
Would also like to have this feature. Currently we have to use dirty workarounds.
In our case, we want to have our resources only recognize the dependency when count != 0 . 
Hence, +1 to this request.

**Comment by apparentlymart** [comment] 2018-10-27 02:03
Hi @synhershko! Sorry for the unexpected behavior, and for the slow response.

The reason for this error is not actually the `depends_on` argument, but rather the reference to `aws_emr_cluster.querying.id` in `cluster_id`. Since no cluster was created, it's not possible to refer to its id.

The usual way to express this is to also set `count` on the other resource, so it won't be created either if the cluster isn't created. In Terraform v0.11 and earlier this is annoying to express because of limitations of the `count` argument, but in Terraform v0.12.0-alpha1 I was able to plan the following adaptation of your configuration (I had to replace some references to other objects with placeholders since they weren't in your example):

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_emr_cluster" "querying" {
  count = 0

  name          = "Querying"
  release_label = "emr-5.7.0"
  applications  = ["Hadoop", "Hive", "Presto"]

  ec2_attributes {
    subnet_id                         = "subnet-123"
    emr_managed_master_security_group = "sg-123"
    emr_managed_slave_security_group  = "sg-123"
    instance_profile                  = "placeholder"
    key_name                          = "placeholder"
  }

  master_instance_type = "m4.large"
  core_instance_type   = "m4.xlarge"
  core_instance_count  = 2

  tags = {
    name = "querying"
  }

  service_role = "placeholder"
}

resource "aws_emr_instance_group" "querying-task-nodes" {
  count = length(aws_emr_cluster.querying)

  name           = "task"
  cluster_id     = aws_emr_cluster.querying[count.index].id
  instance_type  = "m4.xlarge"
  instance_count = 0
}
```

Notice that the instance group now has the same count as the cluster, so it won't  be created if the cluster isn't created. `cluster_id` must also refer to the `count.index` index of that resource since when `count` is set the resource block produces a list of resources rather than a single resource.

The fixes and features that make this work are already in `master` in preparation for the v0.12.0 release and were included in the alpha1 build, and so I'm going to close this out. Sorry again for the slow response!

**Closed by apparentlymart** 2018-10-27 02:03 UTC
Labels: bug, config
