### ISSUE TITLE
local_file cannot create files

### ISSUE THREAD

**Issue by p0fi** [hashicorp/terraform#24668] opened 2020-04-14 21:18 UTC
Hi, 
it seems that the local_file provider is unable to create any files on macOS 10.15.4 (19E287)
### Terraform Version

```
0.12.24
```

### Terraform Configuration Files

```hcl
resource "local_file" "default" {
  content = "random text here"
  filename = "${path.module}/.archive/index.js"
}
```
### Expected Behavior

The file named `index.js` should have been created in `/.archive` of the module path.
### Actual Behavior

No file was created whatsoever 
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
### Additional Context

running on macOS 10.15.4 (19E287)

**Comment by danieldreier** [comment] 2020-04-14 21:49
Hi @p0fi! I happen to also have macOS 10.15.4 on my workstation, so this was an easy one to try and reproduce. Here's what I did:

```hcl
resource "local_file" "default" {
  content = "random text here"
  filename = "${path.module}/output.txt"
}
```
```
❯ terraform --version
Terraform v0.12.24
❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "local" (hashicorp/local) 1.4.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.local: version = "~> 1.4"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
src/repro/24668
❯ terraform apply -auto-approve
local_file.default: Creating...
local_file.default: Creation complete after 0s [id=d3478ca1ac457c6940cf420e2313ddcfa43cb57a]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
❯ cat output.txt
random text here%
```

Do you have any more details of your case that might make it reproducible? I also tried adding a subdirectory in to the path and terraform also created it successfully, so I'm a bit stumped on reproducing this one.

**Comment by p0fi** [comment] 2020-04-14 22:15
Oh well I need to correct myself here. I really thought it has nothing to do with the `archive_file` block which is supposed to archive the file created with `local_file` but it seems to be exactly the case here.

The full example would be

```hcl
resource "local_file" "default" {
  content = "random text here"
  filename = "${path.module}/.archive/index.js"
}

data "archive_file" "default" {
  type        = "zip"
  source_file = "${path.module}/.archive/index.js"
  output_path = "${path.module}/.archive/index.zip"
  
  depends_on = [
    local_file.default
  ]
}
```

It seems that the `depends_on` block is ignored and the `archive_file` block is produced before the `local_file` exists. What is strange is that not the `archive_file` block throws an error telling that there is no such file to archive here but the resource which wants to use that archive says it cant find the archive. 

But if I for example specify a completely non existent `source_file` in the `archive_file` it says it can't find that file and errors out. If I keep the `depends_on` but specify a non existent file it also does not error out on archive creation.

**Comment by danieldreier** [comment] 2020-04-14 22:30
@p0fi I'm still not able to reproduce this locally! Here's what I'm doing:

```
bash-3.2$ rm -rf .archive .terraform terraform.tfstate
bash-3.2$ cat repro.tf
resource "local_file" "default" {
  content = "random text here"
  filename = "${path.module}/.archive/index.js"
}

data "archive_file" "default" {
  type        = "zip"
  source_file = "${path.module}/.archive/index.js"
  output_path = "${path.module}/.archive/index.zip"

  depends_on = [
    local_file.default
  ]
}
bash-3.2$ terraform -version
Terraform v0.12.24
bash-3.2$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "archive" (hashicorp/archive) 1.3.0...
- Downloading plugin for provider "local" (hashicorp/local) 1.4.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.archive: version = "~> 1.3"
* provider.local: version = "~> 1.4"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
bash-3.2$ find .                                                                                                                                              
.
./.terraform
./.terraform/plugins
./.terraform/plugins/darwin_amd64
./.terraform/plugins/darwin_amd64/lock.json
./.terraform/plugins/darwin_amd64/terraform-provider-local_v1.4.0_x4
./.terraform/plugins/darwin_amd64/terraform-provider-archive_v1.3.0_x4
./repro.tf
bash-3.2$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.archive_file.default will be read during apply
  # (config refers to values not yet known)
 <= data "archive_file" "default"  {
      + id                  = (known after apply)
      + output_base64sha256 = (known after apply)
      + output_md5          = (known after apply)
      + output_path         = "./.archive/index.zip"
      + output_sha          = (known after apply)
      + output_size         = (known after apply)
      + source_file         = "./.archive/index.js"
      + type                = "zip"
    }

  # local_file.default will be created
  + resource "local_file" "default" {
      + content              = "random text here"
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "./.archive/index.js"
      + id                   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

local_file.default: Creating...
local_file.default: Creation complete after 0s [id=d3478ca1ac457c6940cf420e2313ddcfa43cb57a]
data.archive_file.default: Refreshing state...

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
bash-3.2$ find .
.
./terraform.tfstate
./.archive
./.archive/index.js
./.archive/index.zip
./.terraform
./.terraform/plugins
./.terraform/plugins/darwin_amd64
./.terraform/plugins/darwin_amd64/lock.json
./.terraform/plugins/darwin_amd64/terraform-provider-local_v1.4.0_x4
./.terraform/plugins/darwin_amd64/terraform-provider-archive_v1.3.0_x4
./repro.tf
bash-3.2$ unzip ./.archive/index.zip
Archive:  ./.archive/index.zip
  inflating: index.js
bash-3.2$ cat index.js
random text here
```

That zip archive is definitely being created, at least using this reproduction process. Any other steps on your side that may be needed?

**Comment by p0fi** [comment] 2020-04-15 06:35
Okay this pretty much embarrassed me that I did not think further but I made a completely new file just like you and tried to produce a minimum working sample.

Here you go:

```hcl
resource "local_file" "default" {
  content = "random text here"
  filename = "${path.module}/.archive/index.js"
}

data "archive_file" "default" {
  type        = "zip"
  source_file = local_file.default.filename
  output_path = "${path.module}/.archive/index.zip"

    depends_on = [
    local_file.default
  ]
}

output "test" {
  value = filebase64sha256(data.archive_file.default.output_path)
}
```

```bash
$ terraform apply -auto-approve
local_file.default: Refreshing state... [id=d3478ca1ac457c6940cf420e2313ddcfa43cb57a]

Error: Error in function call

  on main.tf line 22, in output "test":
  22:   value = filebase64sha256(data.archive_file.default.output_path)
    |----------------
    | data.archive_file.default.output_path is "./.archive/index.zip"

Call to function "filebase64sha256" failed: no file exists at
.archive/index.zip.
```

If I remove the output or change it not to use `filebase64sha256` but some kind of attribute of the  `archive_file` block like its `output_path` it works just fine. It seems that the `filebase64sha256` is the problem here.

**Comment by danieldreier** [comment] 2020-04-17 00:08
@p0fi please don't feel embarrassed! I'm happy to troubleshoot together. I appreciate you iterating on a good reproduction case here. In this case, I think you're right that this is essentially the same enhancement request that you linked in #22036. 

Terraform functions don't participate in the dependency graph: the [file function documentation](https://www.terraform.io/docs/configuration/functions/file.html) reads:

> Functions do not participate in the dependency graph, so this function cannot be used with files that are generated dynamically during a Terraform operation. We do not recommend using dynamic local files in Terraform configurations, but in rare situations where this is necessary you can use [the local_file data source](https://www.terraform.io/docs/providers/local/d/file.html) to read files while respecting resource dependencies.

As a result, the `filebase64sha256` function, like all functions, is evaluated at the very beginning before that file exists. This is a known, expected behavior, though I get why it's not necessarily obvious.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core. I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

I'm going to close this, because the community forum is probably the right place to get help figuring out a workaround. They're very friendly and some engineers on the core team participate there as well. Feel free to leave a note here or contact me at ddreier@hashicorp.com to re-open this if you're confident that there is in fact a bug and would like to keep working up a reproduction case.

**Closed by danieldreier** 2020-04-17 00:08 UTC
