### ISSUE TITLE
Terraform validates null values before creating them

### ISSUE THREAD

**Issue by leonarac** [hashicorp/terraform#32444] opened 2022-12-30 00:44 UTC
### Terraform Version

```shell
Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.36.0    
+ provider registry.terraform.io/hashicorp/local v2.2.3   
+ provider registry.terraform.io/hashicorp/random v3.4.3  
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```
resource "aws_glue_crawler" "crawler" {
  for_each = var.crawler_list
  database_name = each.value.database_name
  name          = "${var.environment}_${each.value.crawler_name}"
  role          = var.crawler_role_arn

  dynamic "dynamodb_target" {
    for_each = each.value.dynamodb_target.dynamodb_create_target ? [{data_target = { for key, value in each.value["dynamodb_target"] : key => value }}][0] : {}
    content {
      path = lookup(dynamodb_target.value, "dynamodb_target_path", null)
    }
  }
}
```
```
variables.tf

```
```
variable "crawler_list" {
  description = "crawler list"
  type = map(object({
    database_name = string
    crawler_name  = string
    s3_target = optional(object({
      s3_create_target = optional(bool,false)
      s3_target_path = optional(string, "")
      s3_exclusions  = optional(list(string),[])
    }))
    dynamodb_target = optional(object({
      dynamodb_create_target = optional(bool,false)
      dynamodb_target_path = optional(string, "")
    }))
    jdbc_target = optional(object({
      jdbc_create_target = optional(bool,false)
      jdbc_connection_name = optional(string, "")
      jdbc_target_path     = optional(string, "")
      jdbc_exclusions      = optional(list(string),[])
    }))
  }))
}
```

```
file.tfvars
```

```
crawler_list = {
  dynamodb_gen_companies = {
    database_name = "general"
    crawler_name  = "companies_crawler"
    dynamodb_target = {
      dynamodb_create_target = true
      dynamodb_target_path   = "gen_companies"
    }
  }
```

### Debug Output

```
Error: Attempt to get attribute from null value
│
│   on modules\crawlers\main.tf line 15, in resource "aws_glue_crawler" "crawler":
│   15:     for_each = each.value.s3_target.s3_create_target ? [{data_target = { for key, value in each.value["s3_target"] : key => value }}][0] : {}
│     ├────────────────
│     │ each.value.s3_target is null
│
│ This value is null, so it does not have any attributes.
╵
╷

```
### Expected Behavior

```
module.crawlers.aws_glue_crawler.crawler["geographies"] will be created
  + resource "aws_glue_crawler" "crawler" {
      + arn           = (known after apply)
      + database_name = "dm_web"
      + id            = (known after apply)
      + name          = "geographies_crawler"
      + role          = (known after apply)
      + tags_all      = (known after apply)

      + dynamodb_target {
          + path     = "dim_geographies"
          + scan_all = true
        }
    }

```
### Actual Behavior

```
Error: Attempt to get attribute from null value
│
│   on modules\crawlers\main.tf line 15, in resource "aws_glue_crawler" "crawler":
│   15:     for_each = each.value.s3_target.s3_create_target ? [{data_target = { for key, value in each.value["s3_target"] : key => value }}][0] : {}
│     ├────────────────
│     │ each.value.s3_target is null
│
│ This value is null, so it does not have any attributes.
╵
╷


```
### Steps to Reproduce

1. terraform init
2. terraform validate
3. terraform plan -var-file=file.tfvars

### Additional Context

with version 1.3.3 it works correctly

```
  # module.crawlers.aws_glue_crawler.crawler["geographies"] will be created
  + resource "aws_glue_crawler" "crawler" {
      + arn           = (known after apply)
      + database_name = "dm_web"
      + id            = (known after apply)
      + name          = "geographies_crawler"
      + role          = (known after apply)
      + tags_all      = (known after apply)

      + dynamodb_target {
          + path     = "dim_geographies"
          + scan_all = true
        }
    }

```

**Comment by liamcervante** [comment] 2023-01-02 13:36
Hi @leonarac, thanks for the report.

I haven't been able to reproduce this, even with your reproduction case. I am able to get a similar error if I set my `dynamodb_target` value to null in the input variable.

I wonder if there's been some mixup in your config however, I can see the error messages refer to the `s3_target` being null, but your config makes no reference to the `s3_target` attribute. I suspect that somewhere else in your config you are referring to the `s3_target` attribute to the same way and that's where this error is being produced.

If I'm right about that, I think you'll be able to fix it by setting the default values explicitly as empty objects. You should do this for all your `*_target` variable entries. For example:

```
    s3_target = optional(object({
      s3_create_target = optional(bool,false)
      s3_target_path = optional(string, "")
      s3_exclusions  = optional(list(string),[])
    }), {})
```

If that does fix it, then this comment in another issue explains the apparent regression: https://github.com/hashicorp/terraform/issues/32417#issuecomment-1359198255.

There was a downstream bug that meant null and empty objects where retaining optional metadata about themselves, when they shouldn't have been. This was causing several crashes throughout terraform but did also have the occasional side effect of something working where it shouldn't, making it an example of a useful bug. The fix I suggested for you above (explicitly setting the default to be an empty object instead of null) means that Terraform will correctly apply the default attributes which should clear up the error for you.

I will leave this issue open to give you time to respond in case my assumptions in this comment are not correct (or my proposed fix doesn't work). If I don't hear anything, I'll eventually come back and close this issue as working as intended.

**Comment by leonarac** [comment] 2023-01-02 18:35
I hope you are very well, that was indeed what I already verified with version 1.3.6 and performed terraform plan and apply correctly !!! Thanks !!

**Closed** 2023-01-03 08:23 UTC
Labels: bug, working as designed
