### ISSUE TITLE
aws_route53_record is modified with every apply

### ISSUE THREAD

**Issue by adamgotterer** [hashicorp/terraform#9675] opened 2016-10-27 22:28 UTC
### Terraform Version
0.7.5 and 0.7.7

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "letmein" {
  zone_id = "${aws_route53_zone.internal.zone_id}"
  name = "letmein"
  type = "A"

  alias {
    name = "${aws_elb.bastion.dns_name}"
    zone_id = "${aws_elb.bastion.zone_id}"
    evaluate_target_health = true
  }
}
```

### Expected Behavior
It correctly sets route53 record, but every apply causes a modification from terraform.

### Actual Behavior
```
~ module.vpc.aws_route53_record.letmein
    alias.1189324327.evaluate_target_health: "true" => "false"
    alias.1189324327.name:                   "bastion-XXXXXX.us-east-1.elb.amazonaws.com" => ""
    alias.1189324327.zone_id:                "XXXXXXXXX" => ""
    alias.4023677436.evaluate_target_health: "" => "true"
    alias.4023677436.name:                   "" => "Bastion-XXXXXX.us-east-1.elb.amazonaws.com"
    alias.4023677436.zone_id:                "" => "XXXXXXXXX"
```

**Comment by stack72** [comment] 2016-10-28 15:24
Hi @adamgotterer 

thanks for the issue report here - I am actively working on fixing this now - I am going to close this as a dupe of #9628 - please keep an eye on that issue for updates 

Thanks

Paul

**Closed** 2016-10-28 15:24 UTC
Labels: bug, provider/aws
