### ISSUE TITLE
Terraform Test command does not source Variables from automatic variable files / definition files within test directory

### ISSUE THREAD

**Issue by Mechanolatry** [hashicorp/terraform#34689] opened 2024-02-16 15:06 UTC
### Terraform Version

```shell
Terraform v1.7.3
on windows_amd64
```

### Terraform Configuration Files

[Git Repo](https://github.com/Mechanolatry/Terraform-Test-Variable-File-Bug)

### Debug Output

[trace.log](https://gist.github.com/Mechanolatry/c2d2de47ab0050858785a38de9dfb572)

### Expected Behavior

As per [documentation](https://developer.hashicorp.com/terraform/language/tests#specify-variables-with-the-command-line-or-definition-files)
> Terraform will automatically load any variables defined in the automatic variable files within a test directory. 

The test directory has been configured as per the [recommendation](https://developer.hashicorp.com/terraform/cli/commands/test#example-test-directory-structure-and-commands)

Failing test `./tests/validvarfromfile.tftest.hcl` should use the variable that has been defined in the `./tests/terraform.tfvars` file but it does not.

### Actual Behavior

Variables are *not* loaded from automatic variable files within the test directory (the directory containing the tests).

**NOTE** If the automatic variable file is moved to the module root directory (where the `terraform test` command is run) then the variables are loaded from the file, which is incorrect based upon the documentation

### Steps to Reproduce

1. terraform init
2. terraform test

**Comment by liamcervante** [comment] 2024-02-19 09:29
Hi @Mechanolatry, thanks for filing this.

This is a duplicate of https://github.com/hashicorp/terraform/issues/34664, and will be fixed in the next patch release which should arrive on Wednesday.

Thanks again.

**Closed by liamcervante** 2024-02-19 09:29 UTC
Labels: bug, new

**Comment by liamcervante** [comment] 2024-02-19 09:30
You can work around this for the time being by specifying the `-var-file` argument and pointing to the relevant variable files.
