### ISSUE TITLE
Crash report (v0.4.2)

### ISSUE THREAD

**Issue by samjuvonen** [hashicorp/terraform#1766] opened 2015-04-30 22:52 UTC
Got this crash report on both 0.3.7 and latest. This might be a problem with my .tf but filing issue as exhorted by terraform.

**EDIT by @catsby: moved crash log into gist here: https://gist.github.com/catsby/f94e3cd46a8fbacc185f **

**Comment by catsby** [comment] 2015-05-01 21:38
Hey @samjuvonen thanks for reporting this. Do you have a trimmed down config (minus any secrets) that reproduces this? I'm not sure by your crash report if it's related to subnets or security groups, and any config will help track that down (again, minus any secret info).

Thanks!

**Comment by clivecrous** [comment] 2015-05-05 08:46
I too am experiencing what I think might be the same crash

```
aws_security_group.afb-cards-ussd: Refreshing state... (ID: sg-a99c1bc4)
aws_instance.staging-app-01: Refreshing state... (ID: i-d1db5f07)
aws_instance.staging-app-02: Refreshing state... (ID: i-d3db5f05)
aws_elb.staging-lb: Refreshing state... (ID: staging-lb)
aws_eip.staging-ip: Refreshing state... (ID: 107.20.226.131)
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

panic: runtime error: invalid memory address or nil pointer dereference
2015/05/05 10:42:33 terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x5b2f7]
2015/05/05 10:42:33 terraform-provider-aws: 
...
```

Here is my full config (with keys obfuscated), busy trying out terraform, this is only slightly different from example walk throughs, crash caused by executing `terraform plan` (on OSX with terraform 0.4.2):
```
provider "aws" {
    access_key = "***"
    secret_key = "***"
    region = "us-east-1"
}

resource "aws_security_group" "http-and-ssh" {
    name = "http-and-ssh"
    description = "HTTP and SSH access"

    ingress {
        from_port = 22
        to_port = 22
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }

    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_eip" "staging-ip" {
    instance = "${aws_elb.staging-lb.id}"
}

resource "aws_elb" "staging-lb" {
  name = "staging-lb"

  availability_zones = ["${aws_instance.staging-app-01.availability_zone}","${aws_instance.staging-app-02.availability_zone}"]

  listener {
    instance_port = 80
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }

  instances = ["${aws_instance.staging-app-01.id}","${aws_instance.staging-app-01.id}"]
}


resource "aws_instance" "staging-app-01" {
    ami = "ami-aa7ab6c2"
    instance_type = "t1.micro"
    security_groups = ["${aws_security_group.http-and-ssh.name}"]
}

resource "aws_instance" "staging-app-02" {
    ami = "ami-aa7ab6c2"
    instance_type = "t1.micro"
    security_groups = ["${aws_security_group.http-and-ssh.name}"]
}
```

**Comment by clivecrous** [comment] 2015-05-05 08:57
In case this is useful information:

I manually removed the EIP from amazon, then manually edited it out of terraform.tfstate, also commented it out of my tf file and the crashing has ended.

**Comment by catsby** [comment] 2015-05-08 21:15
Hello –

I can't reproduce this on the latest version, 0.5.0, though I get a different error. In the config you shared, the `instance`you have in your `aws_eip` resource is pointing to the `id` of your `aws_elb` resource, and should point to one of your `aws_instance` resources.

- https://terraform.io/docs/providers/aws/r/eip.html

Please let me know if, pending that change, if you continue to be able to reproduce this issue. Otherwise I'll close the issue on Monday. 

Thanks!

**Comment by clivecrous** [comment] 2015-05-08 21:33
Doh! Thanks

**Comment by catsby** [comment] 2015-05-11 15:13
No worries, thanks for following up :smile:

**Closed by catsby** 2015-05-11 15:13 UTC
Labels: bug, provider/aws, waiting-response
