### ISSUE TITLE
Have 0.12upgrade fix git+ssh url syntax

### ISSUE THREAD

**Issue by Xopherus** [hashicorp/terraform#23736] opened 2019-12-20 16:28 UTC
### Current Terraform Version

```
0.12.17
```

### Use-cases

My company centralizes our terraform modules in a single GitHub repo. Each module is self-contained in its own subfolder in this repo. Since registries were not introduced until recently, we had to use git+ssh URLs in order to fetch them in other projects. 0.12 broke the URL syntax, reversing the ordering of the ref + subfolders. 

```
# works in 0.11
git::ssh://git@github.com/my-org/terraform-modules.git?ref=master//my-module

# works in 0.12
git::ssh://git@github.com/my-org/terraform-modules.git//my-module?ref=master
```

### Attempted Solutions

We've been able to manually correct this for now. Using a private registry would also help, but that is a lot more work.

### Proposal

Have `terraform 0.12upgrade` automatically detect git+ssh URLs and fix them if they are using incompatible syntax.

**Comment by teamterraform** [comment] 2019-12-21 00:39
Hi @Xopherus! Thanks for this feature request.

The `terraform 0.12upgrade` tool was designed to deal with changes to the configuration language itself. While it's true that 0.12 also accidentally fixed the bug that was allowing the sub-path to appear as part of the `ref` argument in a module source address, since that wasn't part of the language changes intentionally included in 0.12 the upgrade tool does not include it.

The upgrade tool was frozen shortly after the release of Terraform 0.12, and we do not intend to make any further changes to it to ensure that anyone who has used that tool to upgrade will have gotten consistent results. Any further automatic migration would need to be done via separate tooling. We don't intend to produce any such tooling built in to Terraform itself, but it is in principle possible to implement it outside of Terraform by following a strategy similar to the community tool [`terraform-clean-syntax`](https://github.com/apparentlymart/terraform-clean-syntax).

Because the upgrade tool is frozen, we're going to close this now. Thanks again for this feature request, and sorry for the inadvertent change of behavior of this feature in 0.12.

**Closed by teamterraform** 2019-12-21 00:39 UTC
Labels: enhancement
