### ISSUE TITLE
Computed resource attribute changes not propagating through to outputs or other resources

### ISSUE THREAD

**Issue by harryw** [hashicorp/terraform#28702] opened 2021-05-14 15:16 UTC
### Terraform Version

```
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.40.0
```

I've tested this on 0.12, 0.13, 0.14 and 0.15. This problem does not appear on 0.12 or 0.13, but does show up in 0.14 and 0.15.

### Terraform Configuration Files

```terraform
provider "aws" {
  region = "us-east-1"
}

variable "param_value" {
  default = "1"
}

resource "aws_ssm_parameter" "example" {
  name = "/tftest/example"
  type = "String"
  value = var.param_value
}

output "param_version" {
  value = aws_ssm_parameter.example.version
}
```

### Debug Output

https://gist.github.com/harryw/f18c83d6a0618239e5aa8224e8e0a7eb

Some details related to AWS credentials/signatures have been redacted, but nothing significant to this issue.

### Expected Behavior

Changes to the variable 'param_value' should result in a change to the output 'param_version' after `terraform apply`.

### Actual Behavior

Changes to the variable 'param_value' trigger updates to the resource, and its version attribute is updated, but the output 'param_value' does not get updated. A subsequent `terraform refresh` or `terraform apply` updates the output.

I've found that the new computed attribute value is also not propagated as expected when passed into another resource, but that's not demonstrated in this example.

### Steps to Reproduce

1. `terraform init`

2. `terraform apply`

```
aws_ssm_parameter.example: Creating...
aws_ssm_parameter.example: Creation complete after 2s [id=/tftest/example]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

param_version = 1
```

3. Change 'param_value' variable to value '2'

4. `terraform apply`

```
aws_ssm_parameter.example: Refreshing state... [id=/tftest/example]
aws_ssm_parameter.example: Modifying... [id=/tftest/example]
aws_ssm_parameter.example: Modifications complete after 2s [id=/tftest/example]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

param_version = 1
```

5. `terraform show`

```
# aws_ssm_parameter.example:
resource "aws_ssm_parameter" "example" {
    arn       = "arn:aws:ssm:us-east-1:331529535674:parameter/tftest/example"
    data_type = "text"
    id        = "/tftest/example"
    name      = "/tftest/example"
    tags      = {}
    tags_all  = {}
    tier      = "Standard"
    type      = "String"
    value     = (sensitive value)
    version   = 2
}


Outputs:

param_version = 1
```

6. `terraform refresh`

```
aws_ssm_parameter.example: Refreshing state... [id=/tftest/example]

Outputs:

param_version = 2
```

### Additional Context

I tried to reproduce this using a simpler resource like null_resource or local_file, but those resources don't get updated in-place, they get replaced, and this problem does not show up on creation, only on update. I've used the aws_ssm_parameter resource because it's simple, updated in-place and I'm familiar with the AWS provider. I first ran into this problem with a custom provider so I'm fairly confident it's not an issue specific to the AWS provider - that's why I haven't raised this issue on the AWS provider repo.

**Comment by apparentlymart** [comment] 2021-05-14 18:59
Hi @harryw! Thanks for reporting this.

I think the clue to the cause here is the following message in the trace logs:

```
2021-05-14T15:55:58.703+0100 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value for aws_ssm_parameter.example, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .version: was cty.NumberIntVal(1), but now cty.NumberIntVal(2)
```

The provider here has violated the rules in [the resource instance change lifecycle](https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md) by returning a different value after apply than it promised during planning.

As the log message implies, Terraform considers this to be an error but there is a pragmatic exception here fore providers "using the legacy plugin SDK" because there were already situations like this in released providers before we added the explicit check for it.

In order to get the expected behavior here, the provider will need to include extra logic to ensure that it produces an accurate plan. The provider would need to detect when you've made a change which the remote system treats as a new version. If so, it should then report in the plan that `version` is either specifically the number 2 or, if it can't predict what the new version number will be, an "unknown value" which Terraform will then show in the plan as `(known after apply)`.

The log warning above suggests that Terraform Core is behaving as intended here, and so I don't think there's anything we could do to improve this situation in _this_ repository and so I'm going to close this. I think what you're describing might already be captured as hashicorp/terraform-provider-aws#12213, but if not then I'd suggest opening an issue in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws) to discuss this further with the AWS provider team. I think the likely fix on the provider side would be to add another rule to [this resource type's `CustomizeDiff` function](https://github.com/hashicorp/terraform-provider-aws/blob/27a50522f2becdbbac0a788f6f715049b343f33c/aws/resource_aws_ssm_parameter.go#L102-L112) which detects a version-incrementing change and includes that effect in the planned new object.

Thanks again!

**Closed by apparentlymart** 2021-05-14 18:59 UTC
Labels: bug, new

**Comment by harryw** [comment] 2021-05-14 20:36
Thanks @apparentlymart, that is very helpful! As mentioned, I first saw this on a custom provider so I've been pretty unfortunate in picking another resource with the exact same (mis)behaviour in the AWS provider! I'm sorry to have raised this in the wrong place, then. Thanks for pointing out the existing issue on the AWS provider, that saves me the trouble of re-raising this. And this should give me enough clues to fix the issue in my own provider. Much obliged 👍

**Comment by apparentlymart** [comment] 2021-05-14 22:24
I noticed the discussion in hashicorp/terraform-provider-aws#12213 mentioned that `aws_s3_bucket_object` already deals with a similar situation with S3 object versioning. I've not looked closely at that myself, but it might serve as a good example for implementing something similar in your own provider.

If you run into troubles implementing it, you could start a topic about it in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where we can have more open-ended conversations about different topics than here in GitHub. Several Terraform team members participate in the forum, including myself.
