### ISSUE TITLE
Terraform destroy broken when using data sources

### ISSUE THREAD

**Issue by dhawal55** [hashicorp/terraform#8461] opened 2016-08-24 23:16 UTC
Terraform destroy throws invalid cycle dependency errors when using terraform_remote_state and template_file. It worked fine with v0.6 but after i upgraded to v0.7.1 and changed terraform_remote_state, template_file from `resource` to `data`, it breaks.
### Terraform Version

v0.7.1
### Affected Resource(s)

Multiple resources
### Terraform Configuration Files

```
data "terraform_remote_state" "shared" {
    backend = "s3"
    config {
        bucket = "${var.s3_bucket_name}"
        key = "${var.remote_state_location}/shared/terraform.tfstate"
    }
}

resource "aws_autoscaling_group" "workers" {
    name = "${var.aws_resource_name_prefix}-workers-asg"

    availability_zones = [ "${split(",", var.availability_zones)}" ]
    vpc_zone_identifier = [ "${split(",", var.ec2_instance_subnet_ids)}" ]
    launch_configuration = "${aws_launch_configuration.workers.id}"

    max_size = "${var.workers_cluster_size_max}"
    min_size = "${var.workers_cluster_size_min}"
    desired_capacity = "${var.workers_cluster_size_min}"
    health_check_grace_period = "300"
    health_check_type = "EC2"
    default_cooldown = "120"
    termination_policies = [ "NewestInstance" ]
    lifecycle {
        create_before_destroy = true
    }
}

resource "aws_launch_configuration" "workers" {
    name_prefix = "${var.aws_resource_name_prefix}-workers-launch_config"
    image_id = "${var.coreos_ami_id}"
    instance_type = "${var.ec2_instance_type}"
    iam_instance_profile = "${aws_iam_instance_profile.workers.name}"
    key_name = "${var.ec2_key_name}"
    security_groups = [
        "${data.terraform_remote_state.shared.cluster_members_sg_id}",
        "${data.terraform_remote_state.shared.worker_instances_sg_id}",
        "${var.nat_security_group_id}"
    ]
    user_data = "${data.template_file.cloud_config.rendered}"

    lifecycle {
        create_before_destroy = true
    }
}

resource "null_resource" "cloud_config" {
    provisioner "local-exec" {
        command = "mkdir -p ${var.build_dir}/config-drive/openstack/latest; cat << EOF > ${var.build_dir}/config-drive/openstack/latest/user_data \n${data.template_file.cloud_config.rendered}\nEOF"
    }
}

data "template_file" "cloud_config" {
    template = "${file("templates/cloud_config.yaml.tmpl")}"

    vars {
        autoscaling_group_name = "${var.autoscaling_group_name}"
        aws_region = "${var.aws_region}"
        # TODO: this is going to break. likely soon.
        availability_zone = "${var.availability_zones}"
        proxy_for_node = "${var.proxy_for_node}"
        s3_bucket = "${var.s3_bucket_name}"
        s3_url_stack_bin = "${var.s3_url_stack_bin}"
        s3_url_stack_certs_workers = "${var.s3_url_stack_certs_workers}"
        hyperkube_image = "${var.hyperkube_image}"
        k8s_release = "${var.k8s_release}"
        awscli_image = "${var.awscli_image}"
        private_fqdn = "${var.private_fqdn}"
        apiserver_service_ip = "${var.apiserver_service_ip}"
        cluster_dns_service_ip = "${var.cluster_dns_service_ip}"
        cluster_dns_domain = "${var.cluster_dns_domain}"
        docker_registry_cidr_blocks = "${var.docker_registry_cidr_blocks}"
        coreos_channel = "${var.coreos_channel}"
    }
}

```
### Debug Output

When trying to delete the stack, i get the following error:

```
Errors:

  * 1 error(s) occurred:

* Cycle: aws_cloudwatch_metric_alarm.scale-in, aws_autoscaling_policy.scale-in, aws_autoscaling_policy.scale-out, data.terraform_remote_state.shared (destroy), data.terraform_remote_state.shared, aws_launch_configuration.workers (destroy), data.template_file.cloud_config (destroy), data.template_file.cloud_config, aws_launch_configuration.workers, aws_autoscaling_group.workers, aws_cloudwatch_metric_alarm.scale-out, aws_autoscaling_group.workers (destroy)
```
### Expected Behavior

Terraform resource should be deleted as was the case in v0.6
### Actual Behavior

Getting cycle dependency error.

![terraform_view](https://cloud.githubusercontent.com/assets/3484309/17951319/182ecc20-6a16-11e6-8233-7816fd91c9f8.png)

**Comment by apparentlymart** [comment] 2016-08-25 01:36
Hi @dhawal55! Sorry for the issue here.

In your old config where this was all resources, did you have the `create_before_destroy` lifecycle rule set on `template_file.cloud_config` and `terraform_remote_state.shared` along with all the other resources?

If so, I suspect this is a new example of an old (somewhat-longstanding) Terraform bug where strange things happen if `create_before_destroy` resources mix with non-`create_before_destroy` resources, since `create_before_destroy` causes the edge between some of the graph nodes gets inverted.

The usual fix for this is to add `create_before_destroy` to more resources, but sadly that won't work here because data resources don't support `lifecycle`. I think the issue here is that data resources are acting a little *too much* like managed resources... we're generating "destroy" nodes for them even though destroying isn't actually a meaningful operation for data resources.

The fix here is probably to tweak slightly how the graph gets generated for data sources. Unfortunately I don't have a quick workaround for you other than to continue using the `resource` form of these (which is deprecated, but should still work) until we get this fixed.

**Comment by dhawal55** [comment] 2016-08-25 02:27
Hey @apparentlymart, thank you for the quick reply. Yes, i was using the `create_before_destroy` lifecycle rule set on `template_file.cloud_config` and `terraform_remote_state.shared` earlier. 

I tried to use the old `resource` form. It works for `template_file.cloud_config` but doesn't work for `terraform_remote_state.shared`. I can't access `output` attribute for `terraform_remote_state` when using the resource form. Here's the error i get:

```
* Resource 'terraform_remote_state.shared' does not have attribute 'output.http_router_internal_elb_sg_id' for variable 'terraform_remote_state.shared.output.http_router_internal_elb_sg_id'
* Resource 'terraform_remote_state.shared' does not have attribute 'output.services_internal_elb_sg_id' for variable 'terraform_remote_state.shared.output.services_internal_elb_sg_id'
* Resource 'terraform_remote_state.shared' does not have attribute 'output.services_internal_elb_sg_id' for variable 'terraform_remote_state.shared.output.services_internal_elb_sg_id'
* Resource 'terraform_remote_state.shared' does not have attribute 'output.cluster_members_sg_id' for variable 'terraform_remote_state.shared.output.cluster_members_sg_id'
```

**Comment by apparentlymart** [comment] 2016-08-25 14:17
@dhawal55 I think along with the change to being a data source the `terraform_remote_state` resource in particular also had a change (related to supporting arrays/maps, rather than data sources) so that its exported attributes are top-level rather than nested in the `output` map as before.

So I think you would need to write the interpolations the 0.7 way even though you're writing it as a `resource` block as you would for 0.6: `${terraform_remote_state.shared.http_router_internal_elb_sg_id}`.

Sorry that these two changes ended up colliding... the backward-compatibility shim for making it to continue to work as a `resource` isn't able to also shim the other breaking changes to the implementation that happened in 0.7. :tired_face:

**Comment by bacoboy** [comment] 2016-09-12 17:49
Any update on this?

**Comment by iroller** [comment] 2016-09-13 02:33
That is a nasty bug. Is there any workaround for terraform 0.7.3? I've tried terraform_remote_state both as a resource and as a data and none of them work. Getting ` Resource 'terraform_remote_state' does not have attribute...`

**Comment by mitchellh** [comment] 2016-09-13 17:14
Hey, I'm taking a look at this. Your repro case doesn't work! It references a lot of variables that don't exist, the LC and ASG are never referenced, etc. Do you mind posting a minimal case that can be reproduced? Thanks!

**Comment by StefanSmith** [comment] 2016-09-13 21:20
I'm seeing this as well. Here's a very simple example that's failing on v0.7.3:

```
provider "aws" {
  region = "us-east-1"
}

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_instance" "my_instance" {
  ami = "ami-123"
  instance_type = "t2.nano"
  availability_zone = "${data.aws_availability_zones.available.names[0]}"

  lifecycle {
    create_before_destroy = true
  }
}
```

Running ```terraform graph -draw-cycles -verbose | dot -Tpng``` produces:

![with-create-before-destroy](https://cloud.githubusercontent.com/assets/227291/18491715/a316e4d2-79ff-11e6-83e7-1342d31a1a63.png)

If the ```lifecycle``` block is removed from ```aws_instance```, running ```terraform graph -draw-cycles -verbose | dot -Tpng``` produces:

![without-create-before-destroy](https://cloud.githubusercontent.com/assets/227291/18491712/9f4dfdd6-79ff-11e6-8a9b-9a7792051512.png)

**Comment by bacoboy** [comment] 2016-09-21 04:12
Any updates on this?  Doesn't look like it made it into 0.7.4...

**Comment by dhawal55** [comment] 2016-10-06 19:02
Any updates? Did it make it to 0.7.5?

**Comment by bacoboy** [comment] 2016-10-13 14:09
@mitchellh you still working on this?  Any updates/timelines for those watching this item...  Thanks!

**Comment by dweomer** [comment] 2016-10-27 16:13
This likely won't work for everyone but I was able to work around this by using `jsonencode` on an inline `map` definition (for injecting json config into Consul):
```
module "consul" {
  source = "consul"

  consul_host_count              = "${var.cluster_size}"
  consul_host_private_ipv4_addrs = "${module.telegraf.host_private_ipv4_addrs}"
  consul_host_public_ipv4_addrs  = "${module.telegraf.host_public_ipv4_addrs}"

  consul_ops_login    = "${module.telegraf.ops_login}"
  consul_ops_key_file = "${module.telegraf.ops_key_file}"

  consul_datacenter  = "${var.consul_datacenter}"
  consul_domain      = "${var.consul_domain}"
  consul_encrypt_key = "${var.consul_encrypt_key}"

  consul_configs = {
    # inline map moots a graph cycle during destroy: https://github.com/hashicorp/terraform/issues/8461
    acl = "${jsonencode(map(
      "acl_datacenter", var.consul_datacenter,
      "acl_master_token", var.consul_acl_master_token,
      "acl_default_policy", var.consul_acl_default_policy,
      "acl_down_policy", var.consul_acl_down_policy,
      "acl_token", var.consul_acl_master_token
    ))}"
  }
}
```
This same module would give me the above-mentioned graph-cycle-on-destroy when the `consul_configs["acl"]` was defined with the content of a `template_file` or `jsonencode` on an output map from a `null_data_source`.

**Comment by igormoochnick** [comment] 2016-11-02 19:49
+1

**Comment by LeSingeFou** [comment] 2016-11-14 17:22
+1 (with consul)

**Comment by kostyrevaa** [comment] 2016-11-26 23:47
@StefanSmith it works for me with terraform v0.7.13

**Comment by 2rs2ts** [comment] 2016-11-29 17:11
I think this issue was affecting us (not sure) but it went away with terraform v0.7.11.

**Comment by stack72** [comment] 2017-03-02 11:39
Closed as of an earlier version of terraform in the 0.7.1x series

**Closed by stack72** 2017-03-02 11:39 UTC
Labels: bug, core
