### ISSUE TITLE
Multiple conditional failure

### ISSUE THREAD

**Issue by russmac** [hashicorp/terraform#18737] opened 2018-08-25 09:49 UTC
### Terraform Version

```
Terraform v0.11.8
+ provider.aws v1.32.0
+ provider.template v1.0.0
```
This fails to set count 1, I have a similar problem with others.

### Terraform Configuration Files
```hcl
# The commented & uncommented conditionals fail
// Public zone host.sub.domain
data "aws_route53_zone" "alb-r53-domain-hz-lookup" {
  count        = "${ var.alb == true && var.route53_cname != "" && length(split(".", var.route53_cname)) == 3 && var.private_zone == false ? 1 : 0}"
//  count        = "${ var.alb && var.route53_cname != "" && length(split(".", var.route53_cname)) == 3 && var.private_zone == false ? 1 : 0}"
//  count        = "${ var.alb == true && length(split(".", var.route53_cname)) == 3 && var.private_zone == false ? 1 : 0}"
  name         = "${element(split(".", var.route53_cname), 1)}.${element(split(".", var.route53_cname), 2)}"
}

resource "aws_route53_record" "alb-r53-cname" {
  count   = "${ var.alb == true && var.route53_cname != "" && length(split(".", var.route53_cname)) == 3  && var.private_zone == false ? 1 : 0}"
//  count   = "${ var.alb && var.route53_cname != "" && length(split(".", var.route53_cname)) == 3  && var.private_zone == false ? 1 : 0}"
//  count   = "${ var.alb && length(split(".", var.route53_cname)) == 3  && var.private_zone == false ? 1 : 0}"
  zone_id = "${data.aws_route53_zone.alb-r53-domain-hz-lookup.zone_id}"
  name    = "${var.route53_cname}"
  type    = "CNAME"
  ttl     = "60"
  records = ["${aws_lb.ecs-alb.dns_name}"]
}
```
I have also tried explicit var.alb == true and a myriad of parentheses placements

I have more complex conditionals working correctly, It seems to only be an issue with route53 resources:
```hcl
count   = "${ ( var.alb == true && var.alb_ssl == false ) || ( var.alb == true && var.lb_internal == true ) ? 1 : 0}"

# Trying to copy this logic ( in case its an issue with more then 2 things compared ) in the count for the route53 resource results in a 0 count as the others..
count        = "${ ( var.alb == true && var.route53_cname != "" ) && ( length(split(".", var.route53_cname)) == 3 && var.private_zone == false ) ? 1 : 0}"
```

If I set count 1 on this resource and change the module instantiation to only use host.sub.domain CNAMES, Everything works as expected 

### Expected Behavior
Count set to 1

### Actual Behavior
Count is not set to 1

### Steps to Reproduce
`terraform apply`

**Comment by russmac** [comment] 2018-08-26 10:37
I reduced the conditional complexity all the way down to `var.alb && var.route53_cname != ""` and still could not get a 1 count on the lookup or record resource above.

I ended up refactoring to this to try to use less functions , or at least different ones (which finally set count = 1 ) without changing variable defaults or params parsed and the true /empty string evaluation of var.alb and route53_cname would of been unchanged (if correct) so this still seems like a bug to me.

```hcl
data "aws_route53_zone" "alb-r53-domain-hz-lookup" {
  count  = "${ var.alb && var.route53_cname != "" ? 1 : 0}"
  name   = "${replace(var.route53_cname, "/^\\w+\\./", "")}."
  vpc_id = "${ var.lb_internal ? var.vpc_id : "" }"
}


resource "aws_route53_record" "alb-r53-cname" {
  count  = "${ var.alb && var.route53_cname != "" ? 1 : 0}"
  zone_id = "${data.aws_route53_zone.alb-r53-domain-hz-lookup.zone_id}"
  name    = "${var.route53_cname}"
  type    = "CNAME"
  ttl     = "60"
  records = ["${aws_lb.ecs-alb.dns_name}"]
}
```

**Comment by mildwonkey** [comment] 2019-06-25 14:55
Hi @russmac , sorry for the long, long silence on this issue.
Terraform's handling of both conditionals and booleans has changed in Terraform 0.12. I've tried to reproduce your configuration and it seems to be working, or at least I'm not getting any errors. Based on this, I am going to close this issue. If you have any problems after upgrading to 0.12 please open a new issue. 
Thanks!

**Closed by mildwonkey** 2019-06-25 14:55 UTC
Labels: bug, config
