### ISSUE TITLE
Terraform to run EC2 in the order defined in main.tf

### ISSUE THREAD

**Issue by saikumar-123** [hashicorp/terraform#24671] opened 2020-04-15 04:39 UTC
I am trying deploy 4 EC2 instances which has there own Ansible playbook to execute in userdata(local-exec). When I tried to launch , all of them started at same time and failed with ssh connection failure on the second instance.

Later I have added depends_on for second resource to dependent on first, third to depend on 1st and 2nd and fourth to depend on 1,2,3.

Now I land at cycle error. 

Can somebody suggests how to run them in sequence. The first instances variables will be used by second, third uses 1st and 2nd ,4th uses the 1,2,3 instances values. So I need to them to execute in the sequence defined in main.tf.

**Comment by danieldreier** [comment] 2020-04-16 23:48
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). 

I'm closing this issue because it doesn't follow the issue template we provide. Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, and then the Terraform maintainers will review it. Thanks!

Beyond using the template, it would help if you could make the following improvements to your issue when you re-file it:

- Add in a detailed reproduction case so I can reproduce this on my own workstation, and use GitHub's [text formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax). You can do `markdown` and code formatting to make your code easier to read, which makes it easier for us to understand the issue. Please use markdown to format terraform code like this:
```HCL
resource "null_resource" "example" {
  name = "hello-world"
}
```
Please format terminal output for readability, like:
```shellsession
❯ terraform validate
Success! The configuration is valid.
```
- please provide all of the files involved in reproducing your example. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

**Closed by danieldreier** 2020-04-16 23:48 UTC

**Comment by saikumar-123** [comment] 2020-04-24 07:19
Here is the template I am having issues with.

Main.tf - Tries to launch 4 EC2 instances. But all of them need to be executed in sequential order defined in main.tf.  I have issues finding the depends_on conditions. 


provider "aws" {
  region  = "us-east-1"
  shared_credentials_file = "/home/sai.d/.aws/credentials"
  profile                 = "default"

}
resource "aws_instance" "ansible-elastic" {
	ami = "${var.ami_id}"
	instance_type = "${var.elastic_instance_type}"
        key_name = "${var.key_name}"
	subnet_id = "subnet-0de41be2xxxxxxxx"
	iam_instance_profile = "ec2_role_for_maagc"
	root_block_device {
            volume_type= "standard"
            volume_size = "30"
          }
	tags = { Name = "Enabling-elasticsearch" }
	security_groups = "${compact(split(",", var.security_groups["security_groups"]))}"
	
        provisioner "local-exec" {
           command = " echo 'elastic_server_ip: ${aws_instance.ansible-elastic.private_ip}' > elk-vars.yml"
        }
	provisioner "local-exec" {
          command = "ansible-playbook --private-key=/home/sai.d/maagcpoc.pem -u ec2-user -i ${aws_instance.ansible-elastic.private_ip}, playbooks/elastic.yml --extra-vars '@elk-vars.yml'"
	}
}

resource "aws_instance" "ansible-kibana" {
        ami = "${var.ami_id}"
        instance_type = "${var.kibana_instance_type}"
        key_name = "${var.key_name}"
        subnet_id = "subnet-0de41xxxxxxxxxxx"
        iam_instance_profile = "ec2_role_for_maagc"
        root_block_device {
            volume_type= "standard"
            volume_size = "30"
          }
        tags = { Name = "Enabling-kibana" }
        security_groups = "${compact(split(",", var.security_groups["security_groups"]))}"

        provisioner "local-exec" {
           command = " echo 'kibana_server_ip: ${aws_instance.ansible-kibana.private_ip}' > elk-vars.yml"
        }

        provisioner "local-exec" {
          command = "ansible-playbook --private-key=/home/sai.d/maagcpoc.pem -u ec2-user -i ${aws_instance.ansible-logstash.private_ip}, playbooks/kibana.yml --extra-vars '@elk-vars.yml'"
        }
        depends_on = [aws_instance.ansible-elastic]
}

resource "aws_instance" "ansible-beats" {
        ami = "${var.ami_id}"
        instance_type = "${var.beats_instance_type}"
        key_name = "${var.key_name}"
        subnet_id = "subnet-0de41bexxxxxxxxx"
        iam_instance_profile = "ec2_role_for_maagc"
        root_block_device {
            volume_type= "standard"
            volume_size = "30"
          }
        tags = { Name = "Enabling-beats" }
        security_groups = "${compact(split(",", var.security_groups["security_groups"]))}"

        provisioner "local-exec" {
           command = " echo 'beats_server_ip: ${aws_instance.ansible-beats.private_ip}' > elk-vars.yml"
        }

        provisioner "local-exec" {
          command = "ansible-playbook --private-key=/home/sai.d/maagcpoc.pem -u ec2-user -i ${aws_instance.ansible-beats.private_ip}, playbooks/beats.yml --extra-vars '@elk-vars.yml'"
        }
        depends_on = [aws_instance.ansible-elastic,aws_instance.ansible-kibana]
}


resource "aws_instance" "ansible-logstash" {
        ami = "${var.ami_id}"
        instance_type = "${var.logstash_instance_type}"
        key_name = "${var.key_name}"
        subnet_id = "subnet-0de41bexxxxxxxxxx"
        iam_instance_profile = "ec2_role_for_maagc"
        root_block_device {
            volume_type= "standard"
            volume_size = "30"
          }
        tags = { Name = "Enabling-logstash" }
        security_groups = "${compact(split(",", var.security_groups["security_groups"]))}"

        provisioner "local-exec" {
           command = " echo 'logstash_server_ip: ${aws_instance.ansible-logstash.private_ip}' > elk-vars.yml"
        }

        provisioner "local-exec" {
          command = "ansible-playbook --private-key=/home/sai.d/maagcpoc.pem -u ec2-user -i ${aws_instance.ansible-logstash.private_ip}, playbooks/logstash.yml --extra-vars '@elk-vars.yml'"
        }
        depends_on = [aws_instance.ansible-elastic,aws_instance.ansible-kibana,aws_instance.ansible-beats]
}
