### ISSUE TITLE
Terraform release as well as providers sometimes fail to download in DevOps pipeline

### ISSUE THREAD

**Issue by karlschriek** [hashicorp/terraform#31341] opened 2022-06-29 13:34 UTC
We run terraform builds in a fully automated manner within CI/CD pipelines (in Azure DevOps). These pipelines run in stateless agents, which at every commit will more or less do the following:

1. Download the terraform CLI from https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip.
2. Run `terraform init` (which downloads all the providers from the hashicorp registry)
3. Run `terraform apply.`

This workflow has been working without any issues until today when we started (only sometimes) getting the following errors:

When downloading the CLI (this error has only occurred once so far):
```bash
Downloading: https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip
##[error]Error: Failed to download Terraform from url https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip. Error Error: connect ETIMEDOUT 199.232.58.49:443
```

When running `terraform init` and downloading the providers. Sometimes with only a handful of providers, sometimes with all of them, something with none. Here is a sample error:

```bash
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/external v2.2.2: Get
│ "[https://releases.hashicorp.com/terraform-provider-external/2.2.2/terraform-provider-external_2.2.2_linux_amd64.zip"](https://releases.hashicorp.com/terraform-provider-external/2.2.2/terraform-provider-external_2.2.2_linux_amd64.zip%22):
│ dial tcp 199.232.58.49:443: i/o timeout
╵
```

Setting TF_LOG to debug reveals:

```bash
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2022-06-29T08:14:08.168Z [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/external/versions: retrying in 1s (1 left)
2022-06-29T08:14:09.168Z [INFO]  Previous request to the remote registry failed, attempting retry.
```

Which seems to suggest it might have something to do with this issue: https://github.com/hashicorp/terraform/issues/27742. But it doesn't make sense that this hasn't happened before, and also the intermittent nature seems to suggest that instead some kind of rate limits are being hit, although the error message doesn't specify that. I can imagine this being possible though given that we are continuously redownloading things.

Running `terraform init` locally on the exact same configuration has so far not caused any issues (although I have not yet tried to simulate breaking some kind of limits here).

Does the terraform registry have rate limits per downloading IP? I have not been able to find any documentation on this. And if so, what is the recommended solution to this?

**Comment by illrill** [comment] 2022-06-29 14:03
Experiencing the same type of issues from Azure Pipelines  since ~2 hours ago.

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/google v4.27.0: Get
│ "[https://releases.hashicorp.com/terraform-provider-google/4.27.0/terraform-provider-google_4.27.0_linux_amd64.zip"](https://releases.hashicorp.com/terraform-provider-google/4.27.0/terraform-provider-google_4.27.0_linux_amd64.zip%22):
│ dial tcp 199.232.58.49:443: i/o timeout
╵
```
```
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/kubernetes v2.11.0: could not query
│ provider registry for registry.terraform.io/hashicorp/kubernetes: the
│ request failed after 2 attempts, please try again later: Get
│ "[https://registry.terraform.io/v1/providers/hashicorp/kubernetes/2.11.0/download/linux/amd64"](https://registry.terraform.io/v1/providers/hashicorp/kubernetes/2.11.0/download/linux/amd64%22):
│ net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)
╵
```

I'm running the jobs from Microsoft-hosted Ubuntu agents:
```
Agent name: 'Azure Pipelines 77'
Agent machine name: 'fv-az102-414'
Current agent version: '2.204.0'
Operating System
Ubuntu
20.04.4
LTS
Virtual Environment
Environment: ubuntu-20.04
Version: 20220626.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220626.1/images/linux/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220626.1
Virtual Environment Provisioner
1.0.0.0-main-20220531-1
Current image version: '20220626.1'
```

**Comment by boris-mandilov** [comment] 2022-06-29 14:50
Same issue. Using Azure Pipelines, Microsoft hosted agents:
`
│ net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/tls v3.4.0: could not query provider
│ registry for registry.terraform.io/hashicorp/tls: the request failed after
│ 2 attempts, please try again later: Get
│ "[https://registry.terraform.io/v1/providers/hashicorp/tls/3.4.0/download/linux/amd64"](https://registry.terraform.io/v1/providers/hashicorp/tls/3.4.0/download/linux/amd64%22):
│ net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/time v0.7.2: could not query provider
│ registry for registry.terraform.io/hashicorp/time: the request failed after
│ 2 attempts, please try again later: Get
│ "[https://registry.terraform.io/v1/providers/hashicorp/time/0.7.2/download/linux/amd64"](https://registry.terraform.io/v1/providers/hashicorp/time/0.7.2/download/linux/amd64%22):
│ net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/external v2.2.2: Get
│ "[https://releases.hashicorp.com/terraform-provider-external/2.2.2/terraform-provider-external_2.2.2_linux_amd64.zip"](https://releases.hashicorp.com/terraform-provider-external/2.2.2/terraform-provider-external_2.2.2_linux_amd64.zip%22):
│ dial tcp 199.232.58.49:443: i/o timeout
`

**Comment by karlschriek** [comment] 2022-06-29 18:04
Also opened an issue here on the Azure DevOps board: https://developercommunity.visualstudio.com/t/Microsoft-hosted-agents-suddenly-failing/10083966?space=21&entry=problem&q=terraform+suddenly. Please upvote / add comments to get Microsoft's attention.

Also, could someone from Hashicorp give an opinion on whether something changed on their side that might have triggered this?

**Comment by beginner-academy** [comment] 2022-06-29 20:17
We are also seeing this issue for the last 6 hours, If we do the nslookup

nslookup releases.hashicorp.com                                                 
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
releases.hashicorp.com	canonical name = c.sni.global.fastly.net.
Name:	c.sni.global.fastly.net
Address: 199.232.**54**.49

Looks like IP address got changed, but it is not yet reflected.

**Comment by pp-csievering** [comment] 2022-06-29 20:20
Same issue for us, using self hosted VMs but using azure dns servers.

**Comment by crw** [comment] 2022-06-30 00:05
Thanks for reporting this issue. I am checking internally to see if there is an explanation for this issue. Thanks for your patience.

**Comment by rajeev-maven** [comment] 2022-06-30 13:22
Same issue:   failed to instantiate provider "registry.terraform.io/hashicorp/time" to
│ obtain schema: unknown provider "registry.terraform.io/hashicorp/time"

**Comment by crw** [comment] 2022-06-30 17:57
Apologies for the late update; this is being treated as an incident internally and an investigation is underway. This issue does seem to be specifically impacting users of Azure DevOps. Thanks for your patience.

**Comment by rajeev-maven** [comment] 2022-07-01 06:05
> Apologies for the late update; this is being treated as an incident internally and an investigation is underway. This issue does seem to be specifically impacting users of Azure DevOps. Thanks for your patience.

We are getting this issue in Gitlab pipeline.

**Comment by CalebAlbers** [comment] 2022-07-06 22:15
Hi all,

Thanks for your patience as we've been working on this internally. Most people are reporting that the issue has been resolved. Could I ask you to comment here on if you are still receiving the error?

The following is what we've found in working with our upstream network provider:

```
* TLS session established successfully and HTT2 Header frame confirms response by 200 OK.
* According to what we are seeing in testing, as soon as the object begins to transfer OpenSSL rejects it due to the bad Hashing/MAC (message authentication code) received.
* Based on the cipher suite the SHA256 is used for MAC.
* This can be due to corruption of data whilst at transit or and intermediary (such as WAF, Firewall, Proxy...etc) manipulating the data ultimately changing the MAC.
```

If you are able to reproduce the error, could you let me know if you are seeing the issue on a specific environment (e.g., only on Azure DevOps, etc) and if the error persists if using the `--http1.1` switch on `curl` requests?

**Comment by awendt** [comment] 2022-09-23 12:27
@CalebAlbers Just found this now. We are seeing this constantly on our Github workflows. This is particularly bad on some days but even on good days, it's **always there.**

From the number of reactions on #20992, we are not the only ones suffering from this. Please also see https://github.com/hashicorp/terraform/issues/20992#issuecomment-1256020389 for the variety of reasons we see `Error: Failed to install provider`.

It would be good if Terraform retried to download the provider on those errors.

Thanks!

**Comment by dalvarezquiroga** [comment] 2023-01-17 14:49
+1 with same problem, network issues from provider registry...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 4.50"...
- Finding latest version of hashicorp/archive...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: could not query provider registry for registry.terraform.io/hashicorp/aws: the request failed after 2
│ attempts, please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/aws/versions": net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)
╵
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/archive: could not query provider registry for registry.terraform.io/hashicorp/archive: the request failed after
│ 2 attempts, please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/archive/versions": net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)

I tried to download previous version of the provider but same issue.. even if you retry more than 10 times manually.

**Comment by crw** [comment] 2023-05-25 22:41
As the original issue was fixed, I am going to close this issue. Please open any new incidents of this issue as a new ticket. Thanks!

Original incident link: https://hashicorp.statuspage.io/incidents/9y53m05h3jdn

**Closed by crw** 2023-05-25 22:41 UTC
Labels: bug, new, v1.1
