### ISSUE TITLE
Referencing resource instances created by "for_each" 

### ISSUE THREAD

**Issue by webshammo** [hashicorp/terraform#28129] opened 2021-03-17 19:21 UTC
### Terraform Version
Exists in 0.12.29 and 0.13.5

```
### Terraform Configuration Files
make_volume.tf
locals {
  subnet = "192.168.55.0/24"
  dc_name = "test"
  machine_list = [ "machine01", "machine02", "console01", "console02" ]
}

resource "oci_core_instance" "default_instance" {
  compartment_id      = "ocid1.compartment.oc1..aaaaaaaa52ntj3tblrojlly4tr44qidviwjppur7hjag4wj2nn2dp5cei7aa"
  shape = "VM.Standard2.24"
  source_details {
    source_id = "ocid1.image.oc1.phx.aaaaaaaaaatftuwr77yxlf5teft5ebn5c2uswq6dzkmb56ylppbkeaux6mvq"
    source_type = "image"
  }

  create_vnic_details {
    subnet_id = local.subnet
    assign_public_ip = false
    hostname_label = each.value
  }
  display_name = each.value 
  for_each = { for v in local.dc_name == "internal_production" ? [] : local.machine_list: v => v }
}

resource "oci_core_volume" "default_docker_block_volume" {
  compartment_id      = "ocid1.compartment.oc1..aaaaaaaa52ntj3tblrojlly4tr44qidviwjppur7hjag4wj2nn2dp5cei7aa"
  display_name = "${each.value} /var/lib/docker"
  size_in_gbs = 222
  # hack for now for the zero length list.   Change back to var.machine_list when the infernal internal_produciton is gone
  for_each = { for v in (var.dc_name == "internal_production" ? [] : var.machine_list): v => v }
}

resource "oci_core_volume_attachment" "default_docker_block_volume_attachment" {
  attachment_type = "paravirtualized"
  instance_id = oci_core_instance.default_instance[each.key].id
  volume_id = oci_core_volume.default_docker_block_volume[each.key].id
  device = "/dev/oracleoci/oraclevdk"
  # hack for now for the zero length list.   Change back to var.machine_list when the infernal internal_produciton is gone
  for_each = { for v in var.dc_name == "internal_production" ? [] : var.machine_list: v => v }
}

```

### Debug Output
https://gist.github.com/webshammo/46abba8db4c2b331f7d5811062ec038e

### Crash Output
Error finding things in list created, no crash.

### Expected Behavior
When creating default_docker_block_volume_attachment, it should be able to look up the default_docker_block_volume and images it just created

### Actual Behavior
even tho the debug output shows the full list of default_docker_block_volume, creating default_docker_block_volume_attachment fails because it thinks default_docker_block_volume only has one element.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Additional Context
running in a wrapper script shepherd that controls flocks.  I believe I have narrowed this down to terraform tho.

### References

- #22407 seems to have the same behavior

**Comment by jbardin** [comment] 2021-03-17 20:03
Hi @webshammo 

Thanks for filing the issue. This looks similar to many of the refresh-time bugs that were fixed with the 0.14 release. Can you verify that 0.14 fixes the issue you have here?

**Comment by webshammo** [comment] 2021-03-26 01:47
Due to my company restrictions, I cannot.   I have rewritten my code to use copy paste of many blocks and some count =.   here and there.   sad times.

**Comment by jbardin** [comment] 2021-03-26 13:51
Thanks @webshammo, hopefully you will be able to update soon. Since this error is specifically happening during `refresh`, and there is no longer a separate refresh phase of operation in terraform, it's likely that the situation has been resolved in some manner. 

If you find you can reproduce the issue in a current release, please feel free to file a new issue. If you have more questions, [the community forum](https://discuss.hashicorp.com/c/terraform-core) is a better location where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-03-26 13:51 UTC
Labels: bug, v0.13, waiting for reproduction
