### ISSUE TITLE
Terraform Cloud and Terraform 0.14.5 crashes on plan

### ISSUE THREAD

**Issue by arnvid** [hashicorp/terraform#27682] opened 2021-02-04 00:16 UTC
### Terraform Version
Terraform Cloud - Terraform 0.14.5

```
...
```

### Terraform Configuration Files
This was a working workspace and I changed a sensitive variable - and now the workspace crashes.

module "idio_integration" {
  count = var.idio_enable ? 1 : 0
  source  = "app.terraform.io/<TFCORG>/iam-role-idio/aws"
  version = "0.0.2"
  account_id  = var.idio_account_id
  external_id = var.idio_external_id
}

```terraform
...
```

### Debug Output
Terraform v0.14.5
Configuring remote state backend...
Initializing Terraform configuration...
2021/02/04 00:00:01 [INFO] Terraform version: 0.14.5  
2021/02/04 00:00:01 [INFO] Go runtime version: go1.15.6

2021/02/04 00:00:12 [TRACE] vertex "module.idio_integration[0].data.aws_iam_policy_document.iam-role-idio_iam_assume_role_policy": visit complete
panic: value is marked, so must be unmarked first

### Crash Output
panic: value is marked, so must be unmarked first

goroutine 5389 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2c61c20, 0xc00095e820, 0x2557180, 0xc0018f0980, 0xc002ca9290)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/value_ops.go:1045 +0x4f
github.com/hashicorp/terraform/plans/objchange.setElementCompareValues(0xc0014be9b0, 0x2c61c20, 0xc00095e820, 0x2557180, 0xc0018f0980, 0x0, 0x2c61c20, 0xc00095f390, 0x2557180)
	/home/circleci/project/project/plans/objchange/objchange.go:297 +0x67
github.com/hashicorp/terraform/plans/objchange.proposedNewObject(0xc0014be960, 0x2c61be0, 0xc00095e850, 0x2462380, 0xc00330cc90, 0x2c61be0, 0xc00095f7d0, 0x2462380, 0xc00358c0c0, 0x2c61ae0, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:237 +0x193c
github.com/hashicorp/terraform/plans/objchange.ProposedNewObject(0xc0014be960, 0x2c61be0, 0xc00095e850, 0x2462380, 0xc00330cc90, 0x2c61be0, 0xc00095f7d0, 0x2462380, 0xc00358c0c0, 0xc00095e850, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:42 +0x11f
github.com/hashicorp/terraform/plans/objchange.proposedNewObject(0xc001b60ae0, 0x2c61be0, 0xc00095ea00, 0x2462380, 0xc00330cd50, 0x2c61be0, 0xc00095f870, 0x2462380, 0xc00358cb70, 0x5, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:145 +0xb9f
github.com/hashicorp/terraform/plans/objchange.ProposedNewObject(0xc001b60ae0, 0x2c61be0, 0xc00095ea00, 0x2462380, 0xc00330cd50, 0x2c61be0, 0xc00095f870, 0x2462380, 0xc00358cb70, 0x2462380, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:42 +0x11f
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc0026b5a90, 0x2c9d2e0, 0xc0020efc70, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval_read_data_plan.go:118 +0x140f
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xc001a4a790, 0x2c9d2e0, 0xc0020efc70, 0x0, 0x282cefe)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:87 +0x4b4
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc001a4a790, 0x2c9d2e0, 0xc0020efc70, 0xc002352002, 0x24afca0, 0x27bfba0)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:41 +0x11f
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc001c845b0, 0x2c9d2e0, 0xc0020efc70, 0x7f5bcb56eb08, 0xc001a4a790, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x27bfba0, 0xc001a4a790, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0009bf560, 0x27bfba0, 0xc001a4a790, 0xc001f9a240)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x124

### Expected Behavior
Not to crash

### Actual Behavior
Panic

### Steps to Reproduce
1. Queue Plan

### Additional Context

We can disable the module and re-run it and it runs. Enabling it again it runs.. any extra runs after it crashes.
Disabled the count and it still happens.

**Comment by jbardin** [comment] 2021-02-04 13:53
Thanks for filing the issue @arnvid, this looks like a duplicate of #27565

**Closed by jbardin** 2021-02-04 13:53 UTC
Labels: bug, new

**Comment by arnvid** [comment] 2021-02-04 14:06
@jbardin - our variable is not marked as sensitive in the Terraform "code" but only in terraform cloud.
