### ISSUE TITLE
nested dynamic block can't use variable for for_each

### ISSUE THREAD

**Issue by thllxb** [hashicorp/terraform#31089] opened 2022-05-20 02:04 UTC
### Terraform Version

```
$ terraform -v
Terraform v1.2.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.6.0
```

### Terraform Configuration Files

```terraform
variable "ip_rules" {
  type    = list(string)
  default = ["1.2.3.4/32"]
}
variable "virtual_networks" {
  default = []
  type    = list(string)
}

resource "azurerm_container_registry" "acr" {
  location            = "eastus"
  name                = "my-acr"
  resource_group_name = "my-rg"
  sku                 = "Premium"

  dynamic "network_rule_set" {
    for_each = [1]
    content {
      default_action = "Deny"

      dynamic "ip_rule" {
        for_each = var.ip_rules
        content {
          action   = "Allow"
          ip_range = ip_rule.value
        }
      }
      dynamic "virtual_network" {
        for_each = var.virtual_networks
        content {
          action    = "Allow"
          subnet_id = virtual_network.value
        }
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/thllxb/bd04b73ae3d717f56edc30889543cce2

### Expected Behavior

Dynamic blocks `ip_rule` and `virtual_network` created accordinglydingly
### Actual Behavior

```
│ Error: Unknown variable
│
│   on main.tf line 32, in resource "azurerm_container_registry" "acr":
│   32:         for_each = var.ip_rules
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on main.tf line 39, in resource "azurerm_container_registry" "acr":
│   39:         for_each = var.virtual_networks
│
│ There is no variable named "var".
```
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment] 2022-05-20 14:51
Duplicate of #22340

**Closed by jbardin** 2022-05-20 14:51 UTC
Labels: bug, new
