### ISSUE TITLE
Gradual apply

### ISSUE THREAD

**Issue by shvar** [hashicorp/terraform#4338] opened 2015-12-16 13:17 UTC
Sometimes, when you type `terraform plan`, you see that a lot of resources are going through recreation process. It could be useful to have an opportunity to do that gradual.

For example, we can add option `terraform apply -gradual N`, where `N` is maximum number of simultaneously recreating resources. This would cover following scenarios:
- Let's assume, there is number of workers in the cloud, and the task is to upgrade them from one base image to another. Doing a rolling upgrade after changing source in the resource looks to be the best way to dealing with that.
- In case, when somebody is not 100% sure what he is doing, it's a good opportunity to press `control + c` and watch the metrics.
- All tweaks that you forget to add to your provisioner would pop up immediately and you'll be able to automate that without loosing all disks. :blush: 

And anyway it will decrease fear of using terraform by newbies. What do you think?

Maybe also it could make sense to add option `-max-destroy M`, where `M` is maximum number of resources that should be destroyed during apply process.

**Comment by afeld** [comment] 2017-11-19 18:17
A bit late, but have you looked into [the `-target` option of `terraform apply`](https://www.terraform.io/docs/commands/apply.html#target-resource)? Might help with part of the use case, at least.

**Comment by afeld** [comment] 2017-11-19 18:20
See also: #4149

**Comment by teamterraform** [comment] 2019-07-19 23:07
Hi @shvar! Sorry for the long silence here.

As @afeld mentioned, [targeting](https://www.terraform.io/docs/commands/plan.html#resource-targeting) is the feature we eventually implemented to meet use-cases like this. It's a little different than what you proposed, but for exceptional circumstances or unusual needs it can give you the ability to ask Terraform to only do part of the work it would normally do, by performing all of the actions leading to the actions of a particular set of resources.

There's also an option [`-parallelism`](https://www.terraform.io/docs/commands/plan.html#parallelism-n) which lets you control the maximum number of operations Terraform will try to run concurrently during an apply operation. That's not strictly related to what you were thinking about, but we're mentioning it here because concurrency control is another reason why someone might want to "gradually apply".

We're going to close this now because the `-target` option was intended to meet use-cases like what you described, though indeed it meets them in a slightly different way than you suggested. Thanks for sharing these use-cases, and sorry again for the long delay in responding.

**Closed by teamterraform** 2019-07-19 23:07 UTC
Labels: core, enhancement
