### ISSUE TITLE
0.10.3 crash with consul backend

### ISSUE THREAD

**Issue by michaelw** [hashicorp/terraform#16010] opened 2017-09-03 02:41 UTC
### Terraform Version
Terraform v0.10.3 (Darwin)

### Terraform Configuration Files
```hcl
terraform {
  backend "consul" {
    address = "consul.service.consul:8500"
    path    = "test/terraform_state"
  }
}
```

### Debug Output
```
2017/09/02 19:35:49 [INFO] Terraform version: 0.10.3  1511d447e78d8106787875265f96d3a3a03005d5
2017/09/02 19:35:49 [INFO] Go runtime version: go1.9
2017/09/02 19:35:49 [INFO] CLI args: []string{"/private/tmp/terraform", "init"}
2017/09/02 19:35:49 [DEBUG] Attempting to open CLI config file: /Users/mweber/.terraformrc
2017/09/02 19:35:49 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/09/02 19:35:49 [INFO] CLI command args: []string{"init"}
2017/09/02 19:35:49 [DEBUG] command: loading backend config file: /tmp/foo
2017/09/02 19:35:49 [DEBUG] command: no data state file found for backend config

Initializing the backend...
2017/09/02 19:35:49 [DEBUG] New state was assigned lineage "b3969968-866e-40fd-8e2c-f1c4f0b8fdce"
2017/09/02 19:35:49 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1afb7af]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).clientRaw(0xc4202e8f80, 0x2deed8d, 0x4, 0x2705600)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:152 +0x3af
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).configure(0xc4202e8f80, 0x41e9de0, 0xc4202e70b0, 0x270d740, 0xc4202cfa50)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:116 +0x9f
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).(github.com/hashicorp/terraform/backend/remote-state/consul.configure)-fm(0x41e9de0, 0xc4202e70b0, 0x270d740, 0xc4202cfa50)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:96 +0x3e
github.com/hashicorp/terraform/helper/schema.(*Backend).Configure(0xc4202e8f60, 0xc4202e6c60, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/backend.go:80 +0x186
github.com/hashicorp/terraform/command.(*Meta).backendInitFromConfig(0xc420001500, 0xc4202e8dc0, 0x3, 0xc420000180, 0xc420056080, 0x3)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:1356 +0x1b1
github.com/hashicorp/terraform/command.(*Meta).backend_C_r_s(0xc420001500, 0xc4202e8dc0, 0x41ecb00, 0xc42005bf80, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:959 +0x8b
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc420001500, 0xc4201c9ae8, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:384 +0xee6
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc420001500, 0xc42064dae8, 0x28, 0xc4200191a0, 0x28, 0xc420019170)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:88 +0x83c
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc420001500, 0xc42000a070, 0x0, 0x0, 0xc4202ce050)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:200 +0xd32
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202730e0, 0xc4202730e0, 0xc4201c9cf8, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:188 +0xac0
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:95 +0xbb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:31 +0x38
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1afb7af]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).clientRaw(0xc4202e8f80, 0x2deed8d, 0x4, 0x2705600)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:152 +0x3af
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).configure(0xc4202e8f80, 0x41e9de0, 0xc4202e70b0, 0x270d740, 0xc4202cfa50)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:116 +0x9f
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).(github.com/hashicorp/terraform/backend/remote-state/consul.configure)-fm(0x41e9de0, 0xc4202e70b0, 0x270d740, 0xc4202cfa50)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:96 +0x3e
github.com/hashicorp/terraform/helper/schema.(*Backend).Configure(0xc4202e8f60, 0xc4202e6c60, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/backend.go:80 +0x186
github.com/hashicorp/terraform/command.(*Meta).backendInitFromConfig(0xc420001500, 0xc4202e8dc0, 0x3, 0xc420000180, 0xc420056080, 0x3)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:1356 +0x1b1
github.com/hashicorp/terraform/command.(*Meta).backend_C_r_s(0xc420001500, 0xc4202e8dc0, 0x41ecb00, 0xc42005bf80, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:959 +0x8b
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc420001500, 0xc4201c9ae8, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:384 +0xee6
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc420001500, 0xc42064dae8, 0x28, 0xc4200191a0, 0x28, 0xc420019170)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:88 +0x83c
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc420001500, 0xc42000a070, 0x0, 0x0, 0xc4202ce050)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:200 +0xd32
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202730e0, 0xc4202730e0, 0xc4201c9cf8, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:188 +0xac0
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:95 +0xbb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:31 +0x38

```

### Expected Behavior
terraform should not crash.  Note that reverting to 0.10.2 fixes the issue.

### Actual Behavior
terraform crashes, regardless of key present or absent in consul KV store.

### Steps to Reproduce
1. `terraform init`

### References
Might be related to the issue below, but with a tiny repro config (see above):
- #16001

**Comment by maxadamo** [comment] 2017-09-03 19:14
got the same, with Consul

**Comment by saneax** [comment] 2017-09-04 11:55
Similar to that got error, while following the documentation on getting started and at the stage of 'remote backends' - I tried to add this -
terraform {                                                                        
  backend "consul" {                                                               
    address = "demo.consul.io"                                                     
    path    = "getting-started-gfg3hcigUx5Y"                                       
    lock    = false                                                                
  }                                                                                
}

=======logs below=======
terraform init
Downloading modules...
Get: git::https://github.com/hashicorp/consul.git

Initializing the backend...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef93af]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).clientRaw(0xc4203a2de0, 0x21ec627, 0x4, 0x1b03880)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:152 +0x3af
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).configure(0xc4203a2de0, 0x35e5b80, 0xc4203ac360, 0x1b0b900, 0xc4203a73d0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:116 +0x9f
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).(github.com/hashicorp/terraform/backend/remote-state/consul.configure)-fm(0x35e5b80, 0xc4203ac360, 0x1b0b900, 0xc4203a73d0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:96 +0x3e
github.com/hashicorp/terraform/helper/schema.(*Backend).Configure(0xc4203a2dc0, 0xc42036df20, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/backend.go:80 +0x186
github.com/hashicorp/terraform/command.(*Meta).backendInitFromConfig(0xc420060300, 0xc4202f9740, 0x3, 0xc420000180, 0xc42005a080, 0x3)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:1356 +0x1b1
github.com/hashicorp/terraform/command.(*Meta).backend_C_r_s(0xc420060300, 0xc4202f9740, 0x35e87e0, 0xc420397f80, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:959 +0x8b
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc420060300, 0xc4201d3ae8, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:384 +0xee6
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc420060300, 0xc4201d3ae8, 0x28, 0xc4203766f0, 0x28, 0xc4203766c0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:88 +0x83c
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc420060300, 0xc42000a070, 0x0, 0x0, 0xc420243210)
        /opt/gopath/src/github.com/hashicorp/terraform/command/init.go:200 +0xd32
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc420259440, 0xc420259440, 0xc4201d3cf8, 0x1)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:188 +0xac0
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:95 +0xbb
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:31 +0x38

**Comment by jbardin** [comment] 2017-09-05 18:19
duplicate of #15972

**Closed by jbardin** 2017-09-05 18:19 UTC
Labels: backend/consul, bug, crash, regression
