### ISSUE TITLE
template for loop trailing comma in JSON

### ISSUE THREAD

**Issue by wburn-sierra-cedar** [hashicorp/terraform#23282] opened 2019-11-04 21:51 UTC
### Terraform Version

```
Terraform v0.12.12
+ provider.aws v2.33.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2
```

### Terraform Configuration Files

```
mount_map = [
   {
      path = "/foo"
      source = "module.foo.source_id"
   },
     path = "/bar"
     source = "module.bar.source_id"
   }
]
```

### Crash Output

```
Error: ECS Task Definition container_definitions is invalid: Error decoding JSON: invalid character ']' looking for beginning of value
```

### Steps to Reproduce

```
      "mountPoints": [
      %{ for mount in mount_map }
          {
           "sourceVolume": "${mount.source}",
           "containerPath": "${mount.path}"
          },
      %{ endfor }
      ]
```

### Additional Context

something like:

```
      "mountPoints": [
      %{ for mount in mount_map }
          {
           "sourceVolume": "${mount.source}",
           "containerPath": "${mount.path}"
          },
     %{ if last.mount }
           {
           "sourceVolume": "${mount.source}",
           "containerPath": "${mount.path}"
          }
     %{ endif }
      %{ endfor }
      ]

   ```

or a way to count the loop iteration and catch the last iteration to ensure there is no trailing comma.  I tried putting each element into a list and using join.

**Comment by teamterraform** [comment] 2019-11-05 22:59
Hi @wburn-sierra-cedar,

Terraform has a function `jsonencode` for automatically generating syntactically-correct JSON:

```
  "mountPoints": ${jsonencode([
    for mount in mount_map : {
      sourceVolume  = mount.source
      containerPath = mount.path
    }
  ])}
```

We do not recommend using the template language to construct JSON manually from strings. Although above we showed an example of generating just part of your JSON using `jsonencode`, because we were working with only the snippet you shared, we'd actually recommend generating the entire JSON result (in your case, the whole `container_definitions` argument value) using a single `jsonencode` call, since that will generally be more readable because it will not have visual noise to handle JSON serialization concerns like trailing commas.

```hcl
  container_definitions = jsonencode({
    # ...
  })
```

If the JSON definition is large enough that you want to factor it out into a separate template file (with [the `templatefile` function](https://www.terraform.io/docs/configuration/functions/templatefile.html)) to avoid a very long `container_definitions` argument in the configuration, you can write a template whose entire content is a `jsonencode` result:

```
${jsonencode({
  # ...
}}
```

We think this would allow you to meet the use-case you described here. Could you give it a try and let us know how how it looks? Thanks!

**Comment by wburn-sierra-cedar** [comment] 2019-11-08 02:16
I have taken your advice and combined the entire content into one JSON file. 

```
    "logConfiguration": {
        "logDriver": "${log_driver}",
        "options": {
          "awslogs-group": "${app_log_name}",
          "awslogs-create-group": "${create_group}",
          "awslogs-region": "${region}",
          "awslogs-stream-prefix": "${stream_prefix}"
        }
    },
      "portMappings" : [
      %{ for port in container_ports}
          "ContainerPort: ${port}",
          "hostPort:  ${port}",
          "Protocol: ${protocol}",
      %{ endfor } 
      ],
      "mountPoints": [
      %{ for mount in mount_map }
        {
          "sourceVolume": "${mount.source}",
          "containerPath": "${mount.path}"
        }
      %{ endfor }
      ]
   },
   {
    "name": "${name_admin}",
    "image": "${docker_image_admin}",
    "essential": ${essential_admin
```

I am a little confused as to where I add the jsonencode call.

```
 web_app_template = templatefile(${jsonencode({var.container_def_web_app,

Expected the start of an expression, but found an invalid expression token.
````

or if I include it at the top of the template file

```
Call to function "templatefile" failed:
templates/containers/ps_ecs_container_def_web_app.json.tmpl:6,20-21:
Invalid character; This character is not used within the language., and 15
other diagnostic(s).

```

```
${jsonencode ({

  {
      "name": "${name_web}",
      "image": "${docker_image}",
      "essential": ${essential},
      "privileged": ${privileged},
      "cpu": ${container_cpu},
      "command" : [
```
Thank you for your help in this matter.

Cheers,

Will

**Comment by teamterraform** [comment] 2019-11-08 17:52
Hi @wburn-sierra-cedar,

Your second attempt of putting the `jsonencode` call into the template file is the right idea. The reason for the error is that you then need to write the argument to `jsonencode` in [Terraform expression syntax](https://www.terraform.io/docs/configuration/expressions.html), not in [_template_ syntax](https://www.terraform.io/docs/configuration/expressions.html#string-templates). That means that you don't need to use the `${` `}` interpolation markers, because those are for transitioning from template mode into expression mode but we're already in expression mode here.

As an example I've adapted the snippet you shared. Of course this is incomplete just like your example, so you'll need to apply similar changes to the rest of the file.

```
${jsonencode({
  "name": name_web,
  "image": docker_image,
  "essential": essential,
  "privileged": privileged,
  "cpu": container_cpu,
  "command" : [
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions, and it seems like Terraform is behaving as intended here so we're going to close this out. However, if you do have follow-up questions please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core), where both Terraform team members and community members are ready to help. Thanks!

**Closed by teamterraform** 2019-11-08 17:52 UTC
Labels: config, enhancement

**Comment by wburn-sierra-cedar** [comment] 2019-11-11 20:00
Thank you for the information.  That was very helpful.  Unfortunately I am still seeing an error trying to get this templatefile function with jsonencode to work.  Can you please tell me what I am doing incorrectly?

Thank you,

Will

```
 ${jsonencode({
    "name":  name_web
  }}
```

```
  web_app_noha_template = templatefile(var.container_def_web_app_admin,
      {
          name_web         = "foo"
      })
```

**Comment by wburn-sierra-cedar** [comment] 2019-11-20 22:30
Thank you!  That was very helpful information. 

Cheers,

Will
