### ISSUE TITLE
feature request: ability to switch HCL examples between HCL, JSON, YAML in docs

### ISSUE THREAD

**Issue by lsh-0** [hashicorp/terraform#18412] opened 2018-07-08 05:43 UTC
HCL is a hurdle to getting started with Terraform. 

It would be useful to see the equivalent representations of HCL in JSON and YAML in the documentation whenever there are HCL examples.

**Comment by apparentlymart** [comment] 2018-07-09 23:46
Hi @lsh-0! Thanks for this suggestion.

We've looked into this a little before and the main limitation for now is that the way we build the documentation (from Markdown files) doesn't give us a good way to support multi-syntax code snippets.

However, we would like to do this eventually, and so once we're able to spend some more time on the build tooling for the website I expect we'll look into this again and see if we can figure something out.

Please note that Terraform only supports HCL native syntax and HCL's JSON variant; there is currently no YAML serialization of Terraform configuration, and we have no plans to add one. We also don't suggest any human ever write JSON configuration for Terraform directly; that format is there only to have something that is easy to generate programmatically.

**Comment by lsh-0** [comment] 2018-07-10 00:48
Thanks for the reply.

I'm currently cutting and pasting using this: https://www.hcl2json.com/

You needn't incorporate the JSON into the docs at all, just a button that calls a translation service.

**Comment by tj** [comment] 2018-08-03 23:26
I'm surprised there's no interesting in maintaining a normalized view of what resources and their inputs/outputs are available, this would be a huge benefit for a project I'm working on, but then you could automate the docs as well. I was surprised to see they're all manual markdown—I'd be happy to help on this front if there was interest.

**Comment by apparentlymart** [comment] 2018-08-06 21:58
Hi @tj,

One of the other Terraform teams at HashiCorp has been working on a mechanism to extract schema information from the providers programmatically, with the goal of eventually generating the reference portions of the documentation.

Our examples are intentionally hand-written so that we can curate how things are presented to emphasize the common case, show different valid permutations, etc. Of course, that doesn't mean that we couldn't _in principle_ put a bit more mechanism around them such as e.g. automatically transforming a hand-written HCL example into its equivalent JSON example at build time and allow choice between them.

That third-party service hcl2json.com is one way to get this done, but I expect it will run into some problems: in general it's not possible to convert one-to-one from native syntax to JSON without knowing a particular application's (i.e. Terraform's) configuration structure, because HCL defines only the low-level grammar and it's up to Terraform itself to decide how to interpret it. In Terraform 0.11 there are only a few small cases where Terraform dictates a special interpretation of the JSON, but this will become more prevalent as we incorporate the new features coming in [the next major release](https://www.hashicorp.com/blog/terraform-0-1-2-preview).

Terraform could potentially have such a conversion tool built into it that would be able to use its own knowledge of the Terraform language to correctly handle the different situations. We don't have plans to add such a thing immediately because the next major release is already quite large in scope, but we may well do in a later release and then we could use that same codepath to potentially generate JSON examples in the Terraform docs.

**Comment by tj** [comment] 2018-08-16 00:26
Awesome thanks! I'll keep an eye on the project, I'd love to support the full suite of providers, we're just manually mapping a few for now.

**Comment by laurapacilio** [comment] 2021-07-07 15:05
Hi All! Wanted to check in to see if it was okay to close this request/where it stands, since it's been a few years now. Let me know - thank you!

**Comment by lsh-0** [comment] 2021-07-08 09:58
thanks for following up.

> It would be useful to see the equivalent representations of HCL in JSON and YAML in the documentation whenever there are HCL examples.

and

> ... it's been a few years now. Let me know

Age is not a good reason to close a ticket. If the feature is not going to be implemented, that's fine, I have no expectations. This was purely a nice-to-have ticket and I'm grateful for @apparentlymart's response.

When I do use Terraform I find I'm still translating HCL to JSON. We don't use HCL and can't emit it from Terraform template generating code except as JSON or blobs of raw text with placeholders, so documentation [like this](https://www.terraform.io/docs/language/meta-arguments/for_each.html#basic-syntax) would still benefit from translation into JSON, especially now that HCL is [1:1 compatible](https://www.hashicorp.com/blog/terraform-0-12-reliable-json-syntax).

Please close the ticket if this won't happen.

**Comment by apparentlymart** [comment] 2021-07-09 00:29
This issue is in an awkward situation because we use issues in this repository to track bugs and feature requests related to Terraform CLI and, by extension, to the subset of the docs on the website that are related to Terraform CLI and maintained in this repository.

However, the overall technology of the website is not under the control of the Terraform Core team, and so there's nothing directly that folks who work in this repository can do to make this possible. Instead, the web development team at HashiCorp would be responsible for adding a mechanism to the shared website tech platform to be able to present examples in multiple languages at once and only _then_ could we start to use that mechanism where it makes sense.

A further complication compared to the time of my last reply is that most of the "meaty" examples of using Terraform live in the Terraform provider documentation, and that now lives in [Terraform Registry](https://registry.terraform.io/browse/providers) and so isn't included in the main Terraform website at all. Terraform Registry is a separate platform in its own right, maintained by yet another team with their own set of priorities again! And so I think in order to _really_ get the benefit of multi-language docs it would be more impactful for Terraform Registry to support it, and then for provider developers to update docs to make use of it (whether manually or via some automatic process, TBD).

While I don't like to just declare something as "someone else's problem", in this case I think it truly is out of our hands to fully meet this request. The good news is that I've heard from the web development team that the new website framework (already in use for some other HashiCorp product sites) _does_ have a means to write code snippets in multiple languages, so once they are able to migrate [terraform.io](https://terraform.io/) to that new platform that will in some sense get the ball rolling for us to start using it where it makes sense in the main Terraform language documentation. I'm not aware of the Terraform Registry team's plans to support a similar idea in the provider documentation, but I know the problem is on their radar.

So with all of that said, I think it makes sense to close this issue not because the request will never be met but because this idea is already tracked in the (non-public) queues for the teams who are actually empowered to implement it, and so I expect it'll happen in due course once the relevant teams are able to prioritize it against their other work. Issues that are just proxies for tickets tracked elsewhere tend to just get forgotten and grow stale, as this one evidently has. Given that, I'm going to close this out but we will still watch the progress of our colleagues on other teams and likely make more specific issues/PRs in this repository once there's some specific work we can carry out.

Thanks again for raising this!

**Closed by apparentlymart** 2021-07-09 00:29 UTC
Labels: documentation, enhancement
