### ISSUE TITLE
TERRAFORM CRASH while performing 'terraform plan -destroy'

### ISSUE THREAD

**Issue by pantovad** [hashicorp/terraform#32842] opened 2023-03-14 15:43 UTC
### Terraform Version

```shell
terraform -version
Terraform v1.4.0
on linux_amd64
```

### Terraform Configuration Files

```
terraform {
        required_version = "1.4.0"
        backend "pg" {
    schema_name = "cicd"
    conn_str = "postgres://10.150.0.60/terraform_phoenix?sslmode=disable"
  }
  required_providers {
    openstack = {
      source = "terraform-provider-openstack/openstack"
      version = "1.50.0"
    }
    null = {
      source = "hashicorp/null"
    }
  }
}

provider "openstack" {
  tenant_name = "cicd"
  use_octavia = true
  region = "RegionOne"
}

```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
        /home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000570140, {0x2ccf8f8, 0xc0009b6d00}, {0x2ccf8f8, 0xc0009b6d40}, 0xc000c36d80, 0xc0009b6cc0)
        /home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
```

### Expected Behavior

should perform 'terraform plan -destroy'

### Actual Behavior

terraform crashes

### Steps to Reproduce

1. terraform init
2. terraform plan -destroy

**Comment by jbardin** [comment] 2023-03-14 15:47
Duplicate of #32810

**Closed by jbardin** 2023-03-14 15:47 UTC
Labels: bug, new
