### ISSUE TITLE
Import successful but module does not appear in the status file

### ISSUE THREAD

**Issue by DavidGonzalezTR** [hashicorp/terraform#28849] opened 2021-06-01 08:40 UTC
### Terraform Version

```
Terraform v0.15.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

```terraform
...
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform import module.sql_server.azurerm_monitor_diagnostic_setting.logsanalytics_sqlserver[0] /subscriptions/xxxxxxxxxx-xxxx-xxxx-Xxxxx-xxxxxxx/resourceGroups/location-data-rg/providers/Microsoft.Sql/servers/sql-server/databases/'{master}|{logsanalyticsName}'
3. We receibe the message that import went correctlly:

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

4.- Then when I run a 'terraform plan' same module (module.sql_server.azurerm_monitor_diagnostic_setting.logsanalytics_sqlserver[0] )appears to add. 
After checking the terraform status file, the section of that module is not imported

**Comment by alisdair** [comment] 2021-06-01 12:54
I think this is a duplicate of #28637, which has been fixed in #28808. The issue in this case is that the import fails, but Terraform reports success. The fix will ship in the next Terraform release.

I'm marking this closed as a duplicate, but if you're sure this isn't the same bug, please supply a small configuration reproducing the issue and I'll  be happy to reopen and investigate.

**Closed by alisdair** 2021-06-01 12:54 UTC
Labels: bug, new
