### ISSUE TITLE
Proxy settings not honored for registry check

### ISSUE THREAD

**Issue by springfan** [hashicorp/terraform#24569] opened 2020-04-06 16:14 UTC
Versions:
2020/04/06 18:09:12 [INFO] Terraform version: 0.12.24  
2020/04/06 18:09:12 [INFO] Go runtime version: go1.12.13

Proxies are set via http_proxy, https_proxy and no_proxy.

Curl requset to endpoint works:
```
+ curl https://registry.terraform.io/.well-known/terraform.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    62  100    62    0     0    547      0 --:--:-- --:--:-- --:--:--   548
{"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
```

But not with terraform:

```
2020/04/06 18:09:13 [DEBUG] plugin requirements: "openstack"="~> 1.26"
2020/04/06 18:09:13 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/04/06 18:09:13 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json

[0m[1mInitializing provider plugins...[0m
- Checking for available provider plugins...
2020/04/06 18:09:13 [DEBUG] Failed to request discovery document: Get https://registry.terraform.io/.well-known/terraform.json: dial tcp: lookup registry.terraform.io on 160.50.250.2:53: no such host
[31m
[0m[1m[31mRegistry service unreachable.[0m[31m

This may indicate a network issue, or an issue with the requested Terraform Registry.
```

**Comment by danieldreier** [comment] 2020-04-09 22:58
Hi @springfan I just tried to reproduce this and was unable to. I'm using terraform 0.12.24. Here's what I did:

1. I installed `mitmproxy` on my OS X workstation. mitmproxy is an open source proxy that can decrypt HTTPS traffic.
2. I ran `mitmproxy`. It listens on localhost port 8080 by default.
3. I added the mitmproxy SSL CA cert on my system and marked it as trusted in keychain access.
4. I ran `curl --proxy http://localhost:8080 http://registry.terraform.io/.well-known/terraform.json` to confirm that my proxy was working.
5. I created a new folder and a file named `repro.tf` with the following contents:
```terraform
esource "null_resource" "A" {
  name = "abc"
}
```
6. I ran `rm -rf .terraform ; http_proxy=http://localhost:8080 TF_LOG=TRACE terraform init` from that new folder. Among other output, I got the following that confirmed to me that traffic is flowing through my proxy:
```
2020/04/09 15:38:08 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
- Checking for available provider plugins...
2020/04/09 15:38:08 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2020/04/09 15:38:09 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/null/versions"
2020/04/09 15:38:09 [DEBUG] GET https://registry.terraform.io/v1/providers/-/null/versions
2020/04/09 15:38:09 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/null/versions
2020/04/09 15:38:09 [DEBUG] fetching provider location from "https://registry.terraform.io/v1/providers/hashicorp/null/2.1.2/download/darwin/amd64"
2020/04/09 15:38:09 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/null/2.1.2/download/darwin/amd64
2020/04/09 15:38:09 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/null/2.1.2/download/darwin/amd64
2020/04/09 15:38:09 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-null/2.1.2/terraform-provider-null_2.1.2_SHA256SUMS
2020/04/09 15:38:09 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-null/2.1.2/terraform-provider-null_2.1.2_SHA256SUMS.sig
2020/04/09 15:38:09 [DEBUG] verified GPG signature with key from HashiCorp Security <security@hashicorp.com>
```
The process ran successfully and concluded with the expected `Terraform has been successfully initialized!` message.

During this process, I saw the following flows through my `mitmproxy` output:
```
Flows
> 12:09:34 GET  HTTP      registry.terraform.io /.well-known/terraform.json                                                                         200 …plication/json   62b 181ms  15:38:08 GET  HTTPS     registry.terraform.io /.well-known/terraform.json                                                                         200 …plication/json   65b 148ms
  15:38:09 GET  HTTPS     registry.terraform.io /v1/providers/-/null/versions                                                                       200 …plication/json  244b 136ms  15:38:09 GET  HTTPS     registry.terraform.io /v1/providers/hashicorp/null/2.1.2/download/darwin/amd64                                            200 …plication/json 1.68k 135ms
  15:38:09 GET  HTTPS    releases.hashicorp.com /terraform-provider-null/2.1.2/terraform-provider-null_2.1.2_SHA256SUMS                             200      text/plain  600b 135ms  15:38:09 GET  HTTPS    releases.hashicorp.com /terraform-provider-null/2.1.2/terraform-provider-null_2.1.2_SHA256SUMS.sig                         200 …n/octet-stream  287b 135ms
  15:38:09 HEAD HTTPS    releases.hashicorp.com /terraform-provider-null/2.1.2/terraform-provider-null_2.1.2_darwin_amd64.zip                       200    [no content]       130ms  15:38:09 GET  HTTPS    releases.hashicorp.com /terraform-provider-null/2.1.2/terraform-provider-null_2.1.2_darwin_amd64.zip                       206 application/zip 6.69m 4.26s
```

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug, please help by providing more details about an environment I can set up locally to reproduce this failure more. If you can, I may be able get it on our backlog.

Based on my work so far, I recommend you take this to the community forum for assistance in troubleshooting. I'm going to close this for now, because I think the community forum is the right approach. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you'd rather work up a reproduction case here.

**Closed by danieldreier** 2020-04-09 22:58 UTC
