### ISSUE TITLE
Fails to refresh state SNS subscription deletions

### ISSUE THREAD

**Issue by tj** [hashicorp/terraform#4888] opened 2016-01-28 21:58 UTC
I had some weird issues with SNS topic subscriptions not registering properly unless managed from the UI, so I deleted those at some point and now TF is freaking out. I tried tainting, removing them from config, refreshing state, but the errors won't go away:

```
* aws_sns_topic_subscription.checker: NotFound: Subscription does not exist
	status code: 404, request id: b8ca0c27-1a62-57b3-8b96-43038a0ead86
```

Shouldn't terraform just detect that it's gone and create it? I'm not sure if this is a bug or just a UX issue. I swear I've deleted things plenty in the past and have TF bring it back up.

**Comment by stack72** [comment] 2016-01-28 22:54
@tj thanks for the bug report - I have opened a [PR](#4891) that should fix this now. Basically, when Terraform was not finding the SNS Topic, it wasn't marking it as deleted from it's state.

**Comment by radeksimko** [comment] 2016-01-28 23:22
Reproduced, @stack72 's PR is fixing it.

**Comment by tj** [comment] 2016-01-28 23:53
What would you suggest in the meantime before a new release?

**Comment by radeksimko** [comment] 2016-01-29 07:06
@tj You could just [taint](https://www.terraform.io/docs/commands/taint.html) the resource:

```
terraform taint aws_sns_topic_subscription.checker
```

**Closed** 2016-01-29 11:03 UTC
Labels: bug, provider/aws

**Comment by tj** [comment] 2016-02-01 17:12
@radeksimko hmm that still gives me the same errors

**Comment by stack72** [comment] 2016-02-01 17:42
@tj my fix hasn't been released yet. It will be in 0.6.11

**Comment by tj** [comment] 2016-02-01 17:46
@stack72 oh no I was referring to the commands above to taint it and re-create

**Comment by radeksimko** [comment] 2016-02-01 20:12
I think the problem is that then you'll be getting the error from the delete API method instead of read...
Some APIs allow you to _delete deleted resources_ - i.e. don't error if the resource doesn't exist anymore (not sure if it's right or wrong behaviour). This probably isn't the case.

So unfortunately it's not easily solvable until the bug is fixed, but the release is just coming out, so hopefully you should see it in couple of hours.

**Comment by tj** [comment] 2016-02-05 18:23
@radeksimko hmm so I tried with 0.6.11 and still get:

```
* aws_sns_topic_subscription.reporter: NotFound: Subscription does not exist
	status code: 404, request id: f28bb78e-928d-53f1-8cf5-f8a078fb803f
* aws_sns_topic_subscription.checker: NotFound: Subscription does not exist
	status code: 404, request id: 50e327be-4a14-54ed-b8ef-6890a0620178
```

**Comment by tj** [comment] 2016-02-05 18:29
Still can't destroy _everything_ either

**Comment by radeksimko** [comment] 2016-02-06 23:37
@tj It works for me:

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_sns_topic" "checker" {
  name = "tf-checker-topic"
}

output "arn" {
  value = "${aws_sns_topic.checker.arn}"
}
```

```
$ terraform apply
```
```
aws_sns_topic.checker: Creating...
  arn:    "" => "<computed>"
  name:   "" => "tf-checker-topic"
  policy: "" => "<computed>"
aws_sns_topic.checker: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

Outputs:

  arn = arn:aws:sns:us-west-2:111111111111:tf-checker-topic
```
```
$ aws --region=us-west-2 sns delete-topic --topic-arn=arn:aws:sns:us-west-2:111111111111:tf-checker-topic
```
```
$ terraform plan
```
```
Refreshing Terraform state prior to plan...

aws_sns_topic.checker: Refreshing state... (ID: arn:aws:sns:us-west-2:111111111111:tf-checker-topic)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_sns_topic.checker
    arn:    "" => "<computed>"
    name:   "" => "tf-checker-topic"
    policy: "" => "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.
```

It you keep having issues, either with this resource or different one, please open a new issue and attach a repro case & terraform version. If we're able to reproduce it, we should be able to fix it. Thanks!

**Comment by jakshi** [comment] 2016-10-14 04:03
Have the same issue with aws_cloudfront_distribution resource in terraform 0.7.5
The simplest way to fix that - just remove the resource directly from terraform.tfstate file
