### ISSUE TITLE
Terraform crash: v1.1.0

### ISSUE THREAD

**Issue by posquit0** [hashicorp/terraform#30150] opened 2021-12-13 09:14 UTC
### Terraform Version

It works with terraform version `v1.0.11`.

```
> tf version
Terraform v1.1.0
on darwin_amd64
```

### Terraform Configuration Files

- I cannot upload, this is for company workspace.

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 1431 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:44 +0xb5
panic({0x2e20fa0, 0x4ae4070})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc004bbf270, {{}, 0x4d, {0xc000c23a58, 0x18}, {0xc00005bc00, 0x4}}, {0xc00326d080, 0x20, 0x4})
	/Users/distiller/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x52, {0xc000739ce0, 0x0, 0xc000641200}, {{}, 0x4d, {0xc000c23a58, 0x18}, {0xc00005bc00, 0x4}}, ...)
	/Users/distiller/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc001d59a40, {0xc000739ce0, 0x1, 0x1}, {{}, 0x4d, {0xc000c23a58, 0x18}, {0xc00005bc00, 0x4}}, ...)
	/Users/distiller/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc001de8da0, {{}, {0xc000739ce0, 0x1, 0x1}, {{}, 0x4d, {0xc000c23a58, 0x18}, {0xc00005bc00, ...}}})
	/Users/distiller/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc0049dc160, {0x36f1e20, 0xc000cc2e00})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc0049dc160, {0x36f1e20, 0xc000cc2e00})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x36f1e20, 0xc000cc2e00}, 0x0)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000cc20e0, {0x36f1e20, 0xc000cc2e00}, {0xdaad440, 0xc0049dc160})
	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x3158c00, 0xc0049dc160})
	/Users/distiller/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0010ddaa0, {0x3158c00, 0xc0049dc160}, 0xc0058a5680)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0xf85
```

**Comment by jbardin** [comment] 2021-12-13 13:49
Duplicate of #30110

**Closed by jbardin** 2021-12-13 13:49 UTC
Labels: bug, new
