### ISSUE TITLE
variables in module source

### ISSUE THREAD

**Issue by till** [hashicorp/terraform#27956] opened 2021-03-02 17:37 UTC
### Current Terraform Version

```
❯ terraform version
Terraform v0.14.3
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.35.0
+ provider registry.terraform.io/terraform-providers/ignition v1.2.1

Your version of Terraform is out of date! The latest version
is 0.14.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use-cases

We are setting up different environments with Terraform and while we would like to continue iterating on our Terraform related setup, we can't role out everything to already setup environments to update them constantly. This is why we decided to version (`git tag`) our terraform modules and currently install them like so:

```tf
module "foobar" {
  source = "git@github.com:org/terraform-repo//foobar?ref=a.b.c"`
}
```

### Attempted Solutions

I can provide multiple entry points (as in `.tf` files) depending on when infrastructure was created. This works, but I can't really _DRY_. And end up repeating boilerplate. It's doable of course, but being allowed to use a variable in `source` would make this part a lot shorter and more maintainable.

My current solution revolves around either using sub directories where I duplicate the boilerplate and symlink parts of it "in" to keep it lean. I've been also considering another `Makefile` to chain it all together. But that ends up being complicated as well at some point.

### Proposal

I'd like to be able to inject the source via a variable, or a variable into the source.

```tf
# I can provide a default, but override via .tfvars 
variable "module_version" {
  default = "1.0.0"
}

module "foobar" {
  source = "git@github.com:organisation/repository//foobar-module?ref=${var.module_version}"`
}

# as an alternative, the complete URI to the module
module "foobar" {
  source = var.module_source`
}
```

### References

- #1145
- #1439

---

Wanted to add how much I already love what modules has become. It's come along way from when I first started toying with this and supports us on an almost daily basis in our work.

**Comment by jbardin** [comment] 2021-03-02 17:52
Duplicate of #14745

**Closed by jbardin** 2021-03-02 17:52 UTC
Labels: enhancement, new
