### ISSUE TITLE
Race condition when recreating aws_subnet

### ISSUE THREAD

**Issue by brainsik** [hashicorp/terraform#5198] opened 2016-02-18 20:01 UTC
Terraform v0.6.11 on OS X 10.11.3
### Goal

Change the names of some subnets not in use.
### What I did

In the configuration, I changed the name of the subnets.
### What I expected

The old subnets would be destroyed and then the new subnets created.
### What happened

The old subnets are sent "Destroying…" commands, but before it finishes "Creating…" commands are sent to make the new subnets. This results in the creates failing due to a conflict with the CIDRs still being in use. See the [gist of the output](https://gist.github.com/brainsik/f3d61f46f7efcb3938fd).

**Comment by johanngeir** [comment] 2016-03-05 01:04
Same behaviour with Openstack subnets.  Needs second run to recover.

**Comment by teamterraform** [comment] 2019-07-19 23:27
Hi @brainsik! Sorry for the long silence here.

In the mean time since this issue was opened, the AWS provider (now in [its own repository](https://github.com/terraform-providers/terraform-provider-aws)) has mechanisms in many of its resource type implementations to work around problems like this, which tend to be caused by eventual consistency in the remote API where the destroy call returns success but the destroy is not actually fully committed across the whole remote system.

In this particular case it looks like something went wrong with Terraform itself, because the output does indeed indicate that Terraform began the create before the destroy completed. However, we've not seen an issue like that in a long time so we're forced to assume that this bug must've been fixed somewhere since 0.6.11 without realizing there was this issue tracking it.

We're going to close this now because the core side of this problem doesn't seem to exist anymore. That doesn't mean that the "eventual consistency" issues are fixed across all resource types in all providers though, and so if you do still see issues of this kind it'd be best to start by opening in issue in the repository of the specific provider, and let the provider team escalate here if the problem seems to be with Terraform Core.

**Closed by teamterraform** 2019-07-19 23:27 UTC
Labels: bug, core, provider/aws
