### ISSUE TITLE
Terraform does not respect gitconfig

### ISSUE THREAD

**Issue by okgolove** [hashicorp/terraform#28968] opened 2021-06-16 13:48 UTC
I want to config SSH settings for git using gitconfig files and make Terraform using these settings but currently Terraform completely ignores gitconfig. 

### Terraform Version

```
Terraform v1.0.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
module "test" {
  source = "git@github.com:terraform-aws-modules/terraform-aws-vpc.git"
}
```

### Debug Output
https://gist.github.com/okgolove/2392f3245375aae488a21bcffd50cbcb

### Expected Behavior

Terraform fails with `permission denied` error but ssh command settings are used by Terraform and there are verbose logs

### Actual Behavior

Terraform fails with `permission denied` error, no ssh command verbose output, so, settings from gitconfig are ignored

### Steps to Reproduce
1. `git config --global core.sshCommand "ssh -vvv"`
2. `terraform init`
3. `terraform apply`
4. There is an error `git@github.com: Permission denied (publickey).` but no ssh command verbose output

### Additional Context

Is you set GIT_SSH_COMMAND variable directly everything works and an verbose output is shown:
```
GIT_SSH_COMMAND="ssh -vvv" terraform init
```

**Comment by mildwonkey** [comment] 2021-06-18 15:06
Hi @okgolove ! 

This appears to be an issue with the upstream go-getter library. This library (eventually) calls `git` directly, so *most* of the time it will honor any  .gitconfig settings. However there is an exception (according to [this go-getter issue](https://github.com/hashicorp/go-getter/issues/299): any ssh setting in configuration gets overridden, while any existing `GIT_SSH_COMMAND` environment variable is not (more details are in the linked issue).

I'll label this so we can keep track of it. Thanks, and sorry for the unexpected behavior!

**Comment by okgolove** [comment] 2021-06-19 08:16
@mildwonkey thanks for the description.
Hope https://github.com/hashicorp/go-getter/pull/300 one day this one will be merged :)

**Comment by mvoitko** [comment] 2022-02-08 14:57
The same problem appears with url config in gitconfig.

**Comment by DanHam** [comment] 2022-03-05 23:12
@mildwonkey 

Hi Kristen, 

Any chance of you nudging the right people to get https://github.com/hashicorp/go-getter/pull/300 merged? 

The fix for the upstream library has been sitting unloved for over a year! It's a small change that would make a big difference for a lot of folks bitten by this bug! 

It's taken an inordinate amount of time to troubleshoot and find the root cause of this issue!

Merging the fix and updating Terraform to use the newer version of go-getter would be very much appreciated!

**Comment by n0rig** [comment] 2022-03-22 18:45
@mildwonkey / @DanHam any update on getting https://github.com/hashicorp/go-getter/pull/300 merged?

**Comment by raffraffraff** [comment] 2023-03-15 11:07
I hate to bump issue threads (small audience, sorry guys...)  but is there any update on this? Our team are about to moved to github.com and I'm documenting the client setup. This is horrible. We are using `.gitconfig` in our codebases, but this totally breaks our terraform modules that are sourced using git. This forces us to try to implement overrides via `.ssh/config`, but that's nasty since they are based on the hostname (which is _always_ github.com).

**Comment by DanHam** [comment] 2023-03-17 19:39
@raffraffraff

It took just over 2 years 2 months.... but the upstream fix in hashicorp/go-getter#300 has just been merged! :tada:

All we need to do now is wait:

* For someone to release a new version of go-getter with the needed fix
* For someone here to then update the version of go-getter used by terraform in go.mod
* For a version of Terraform to then be released with the fix

**Comment by theherk** [comment] 2023-03-17 19:43
hashicorp/go-getter#300 is finally merged. Praise be to @kmoe.

**Comment by maunzCache** [comment] 2023-04-24 07:20
So that means updating the dependency of go-getter would be sufficient to mark this one as fixed?

**Comment by DanHam** [comment] 2023-04-24 08:21
@maunzCache 

Unfortunately, no - Please see my comment above https://github.com/hashicorp/terraform/issues/28968#issuecomment-1474323708 for the steps required to fix this.

**Comment by crw** [comment] 2023-04-24 22:21
Just FYI the blocker right now is getting the Nomad team to sign off on the change, as we share the `go-getter` v1 dependency.

**Comment by kewalaka** [comment] 2023-04-27 23:40
does this have a bearing on git config settings relating to git http urls as well?  I'm troubleshooting why this snippet isn't working & wondered if this bug is significant?

```git config --global url."https://${SYSTEM_ACCESSTOKEN}@dev.azure.com".insteadOf "https://dev.azure.com"```

**Comment by cyberaleksa** [comment] 2023-07-26 13:32
Are there any news when this will get merged?

**Comment by crw** [comment] 2023-07-26 18:45
Following up in https://github.com/hashicorp/nomad/issues/16541#issuecomment-1652317641.

**Comment by tgross** [comment] 2023-07-26 20:02
Hello from Nomad Engineering! :wave: Apologies for the hold-up from our end. `go-getter` v1.7.2 has been released: https://github.com/hashicorp/go-getter/releases/tag/v1.7.2

**Comment by maunzCache** [comment] 2023-07-27 14:55
Sorry for the noise but github really needs a crying emoji for this. Thanks a lot @tgross

**Comment by xsaero00** [comment] 2023-10-04 22:11
Now that TF 1.6 is releases the git config settings work but it ignoring the `GIT_SSH_COMMAND` variable. I don't know if this is intended behavior but it broke my processes.

Now I do both to make sure it works:
```
export GIT_SSH_COMMAND="ssh -i /my/ssh_key"
git config --global core.sshCommand "$GIT_SSH_COMMAND"
```

**Comment by crw** [comment] 2023-10-04 22:17
@xsaero00 I would imagine that is unintended, although I have not deeply examined the source. Since the original issue is resolved, I am going to close this issue; please open a new issue with the new problem. Thanks for reporting it!

**Closed by crw** 2023-10-04 22:17 UTC
Labels: bug, upstream, v1.0

**Comment by StephenKing** [comment] 2023-10-05 09:26
Reported in https://github.com/hashicorp/terraform/issues/33985
