### ISSUE TITLE
Associating an AWS instance with a pre-allocated EIP

### ISSUE THREAD

**Issue by bts** [hashicorp/terraform#1273] opened 2015-03-21 18:55 UTC
For organizations that need to whitelist AWS IP addresses to access private services, it would be very useful if it were possible to associate an instance with a pre-allocated EIP. As it stands, the `aws_eip` resource currently only supports allocation of, not association to existing, EIP addresses.

**Comment by avdhoot** [comment] 2015-03-26 09:37
+1 Any update :)

**Comment by phinze** [comment] 2015-03-26 15:49
Pretty sure this is actually an expression of a special case of #581, if you could "import" an existing EIP into terraform config, you'd be able to make this association normally.

This is still something we'll eventually support, but in the meantime I did want to mention that there's a workaround available, outlined here:

https://www.dark.ca/2015/01/27/handling-extant-resources-in-terraform/

Closing as a dup of #581 - feel free to follow up and/or reopen if you disagree. :ok_hand:

**Closed by phinze** 2015-03-26 15:49 UTC
Labels: enhancement, provider/aws

**Comment by JesperTerkelsen** [comment] 2015-10-12 14:59
Well you could add the concept of an ``EIP_ATTACHMENT`` like there is for ``AWS_VOLUME_ATTACHMENT``

**Comment by davehodgson** [comment] 2016-02-04 21:15
+1 Jesper, I was looking for exactly this functionality due to wanting a public EIP that is known prior to building an OpenVPN server so I can provide the config file with its public facing IP in the user_data

**Comment by Gary-Armstrong** [comment] 2016-02-24 01:23
I also would like to be able to retain a static EIP even in cases where I destroy the associated instance.

**Comment by jmahowald** [comment] 2016-02-26 06:22
Regarding @davehodgson issue. I just ran into this tonight. At least for my case, it was pretty straightforward.  This was my diff to fix my version of openvpn server (which I do hope to open source soon)

```
-      "sudo docker run --volumes-from ovpn-data --rm gosuri/openvpn ovpn_genconfig -p ${var.vpc_base_ip}.0.0/16 -u udp://${aw
s_instance.nat.public_ip}",
+      "sudo docker run --volumes-from ovpn-data --rm gosuri/openvpn ovpn_genconfig -p ${var.vpc_base_ip}.0.0/16 -u udp://${aw
s_eip.nat.public_ip}",

+resource "aws_eip" "nat" {}

output "nat_ip" {
-  value = "${aws_instance.nat.public_ip}"
+  value = "${aws_eip.nat.public_ip}"
}
```

**Comment by cobrien71** [comment] 2016-02-26 19:09
Ditto (re Gary-Armstrong)

**Comment by ebpitts** [comment] 2016-03-18 19:53
I don't think #581 is a duplicate of this.

Like several people have mentioned , we do not want terraform to be able to release EIPs. We assign EIPs when our partners (internal or external to our company) require us to provide IP addresses to them so they can whitelist traffic from us. Thus we allocate EIPs manually and don't want to import them into our terraform config like that workaround suggests, because then `terraform destroy` would release them.

What we wish terraform could do is associate an existing EIP with a terraform-created instance.

**Comment by Gary-Armstrong** [comment] 2016-03-18 20:34
I'm fine with TF managing my EIP, I just want to have them persist when the instance they are assigned to is terminated.

Ideally, I'd like to be able to attach a TF-defined EIP to a TF-defined ENI and have that ENI/EIP pair persist independently through instance termination.  I do have my reasons, of course.

**Comment by ydaetskcoR** [comment] 2016-03-22 12:06
It would be nice if you could specify an EIP allocation id to attach to an EC2 instance upon instance creation like you can with NAT gateways.

That way you could have something like this:

```
project_root/
├── eip/
│   └── eip.tf
└── instance/
    └── instance.tf
```

##### eip.tf:

```
resource "aws_eip" "instance" {
    vpc = true
}

output "eip_id" {
  value = "${aws_eip.instance.id}"
}
```

##### instance.tf:

```
resource "terraform_remote_state" "remote_state" {
  backend = "s3"
  config {
    bucket = "mybucketname"
    key    = "name_of_key_file"
  }
}

resource "aws_instance" "instance" {
    ami = "ami-abcdef12"
    instance_type = "t2.micro"
    allocation_id = "${terraform_remote_state.remote_state.output.eip_id}"
    tags {
        Name = "instance"
    }
}
```

This enables you to destroy the instance, freeing the EIP back to the pool and then when you rebuild the instance the EIP would be re-associated. Equally, if you didn't want TF to manage the EIP at all you could simply do this:

```
resource "aws_instance" "instance" {
    ami = "ami-abcdef12"
    instance_type = "t2.micro"
    allocation_id = "eipalloc-3840215d"
    tags {
        Name = "instance"
    }
}
```

**Comment by ydaetskcoR** [comment] 2016-03-22 13:13
Looking at it https://github.com/hashicorp/terraform/pull/5236 seems to provide this functionality

**Comment by jkinred** [comment] 2016-04-07 14:05
Yes #5236 implements this and my "manual" testing works. I just got stuck with the integration test and the PR stalled.
