### ISSUE TITLE
grpc: received message larger than max

### ISSUE THREAD

**Issue by tebriel** [hashicorp/terraform#21709] opened 2019-06-12 21:46 UTC
### Terraform Version

```
Terraform v0.12.2
+ provider.archive v1.2.1
+ provider.aws v2.14.0
+ provider.local v1.2.2
+ provider.template v2.1.1
```

### Terraform Configuration Files

```hcl
// Nothing exceptionally important at this time
```

### Debug Output

https://gist.github.com/tebriel/08f699ce69555a2670884343f9609feb

### Crash Output

No crash

### Expected Behavior

It should've completed the plan

### Actual Behavior

```
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9761610 vs. 4194304)
```

### Steps to Reproduce

terraform plan on my medium sized project.

### Additional Context

Running within make, but has same profile outside of make. This applies fine in 0.11.14.

**Comment by apparentlymart** [comment] 2019-06-12 23:53
Hi @tebriel,

This message is returned if either a request to or a response from a plugin exceeds 4 megabytes. From the logs it seems that the resource `data.local_file.requirements` is the one affected. Is the file you are trying to read close to 4MB in size? (allowing some margin for the small amount of overhead caused by the other parts of the RPC response message)

**Comment by tebriel** [comment] 2019-06-12 23:56
It is. I’ll switch to uploading it to s3 and giving the lambda the destination of the s3 object. that’s some tech debt I’ve been meaning to tackle. Is there still a bug here? Am I reading the file in wrong? This works in 0.11.14. Thanks for your help!

________________________________

**Comment by apparentlymart** [comment] 2019-06-13 00:01
This is indeed a difference in behavior from Terraform 0.11, though not a difference I'd consider a bug because we were not intentionally supporting returning large files in the old provider protocol: it was just working because we didn't yet have a safety check to protect against a provider returning oversize messages to Terraform Core.

I think the action here would be to update the `local` provider to have its own maximum file size (smaller than the one enforced by the gRPC transport, so this error can't be hit) and to document that maximum size in the documentation. Those changes would need to happen in the local provider's own repository, so I'm going to ask our bot to transfer the issue over there.

**Comment by tebriel** [comment] 2019-06-13 00:07
okay thanks, as a workaround I've changed my `data.local_file` object to a `locals` because all I was really using it for was the filename reference anyways (tl;dr I was using it wrong anyways). TF Plan now succeeds without the `data.local_file` object, thanks!!

**Comment by jbardin** [comment] 2019-06-13 00:09
Note that we increased the max message size to 64mb, so this should not be a common occurrence. It would still be better to catch this in a more user friendly way however.

**Comment by tebriel** [comment] 2019-06-13 00:10
@jbardin the file is 9.3M on disk, so does that 64mb apply here?

**Comment by jbardin** [comment] 2019-06-13 00:36
Ah, I forgot it was only for the `GetSchema` call, since some providers could generate very large schemas. It wasn't globally applied, since we don't really want providers relying on large payloads that are going to be stored in state.

**Comment by apparentlymart** [comment] 2019-06-13 15:51
Sorry... I inadvertently selected the local _backend_ rather than the local _provider_ in my haste yesterday. I've now relabeled this, and so the bot should open an equivalent issue over in the local provider repository and close this one in the near future.

**Closed** 2019-06-13 16:20 UTC
Labels: provider/local
