### ISSUE TITLE
crash log: provider vsphere - Terraform v0.6.12

### ISSUE THREAD

**Issue by user419** [hashicorp/terraform#5422] opened 2016-03-02 15:41 UTC
```
$ terraform --version
Terraform v0.6.12
```

Using vsphere 6.0

Crash log:
https://gist.github.com/user419/2d581a8b8b3c05958bdc

**Comment by jen20** [comment] 2016-03-03 15:38
Relevant section of log:

```
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: 2016/03/02 16:36:42 [ERROR] ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: [signal 0xb code=0x1 addr=0x0 pc=0xfe029]
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere:
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: goroutine 63 [running]:
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: panic(0xd59800, 0xc82000a0d0)
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: 	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/object.(*Task).WaitForResult(0x0, 0x1e132e8, 0xc82000af40, 0x0, 0x0, 0x68, 0x0, 0x0)
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/object/task.go:50 +0x39
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/object.(*Task).Wait(0x0, 0x1e132e8, 0xc82000af40, 0x0, 0x0)
2016/03/02 16:36:42 [DEBUG] terraform-provider-vsphere: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/object/task.go:45 +0x4d
```

**Comment by jen20** [comment] 2016-03-03 15:39
Hi @user419, thanks for opening this issue - we'll get this addressed.

**Comment by chrislovecnm** [comment] 2016-04-16 19:57
@user419 what is your vsphere version and licensing level??  This may be a fun one to reproduce.  Are you able to help with debugging?

**Comment by skuenzli** [comment] 2016-04-21 05:10
I reproduced the same stacktrace with:

* terraform versions: 0.6.10 and 0.6.14
* VMWare ESXi 6.0:
```
root@bda8e2819ec3:/terraform/vmware# /govc_linux_amd64 about -u 'https://userid@ip.address/sdk'
Name:         VMware ESXi
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        3029758
OS type:      vmnix-x86
API type:     HostAgent
API version:  6.0
Product ID:   embeddedEsx
UUID:
```
* license info:
```
root@bda8e2819ec3:/terraform/vmware# /govc_linux_amd64 license.list -u 'https://userid@ip.address/sdk'
Key:                           Edition:                   Used:  Total:
license-key  esx.hypervisor.cpuPackage  2      0
```

**Comment by skuenzli** [comment] 2016-05-07 01:43
The issue was that the ESXi server I was working with had a trial license, which apparently does not include API access. A 60-day 'Full' trial license 'fixed' things.

**Comment by chrislovecnm** [comment] 2016-05-07 02:33
@skuenzil so that was the cause only part of the issue ;) Need to fix the panic that occurred. ;)

Please keep this bug open!

**Comment by skuenzli** [comment] 2016-05-07 02:45
oh for sure -- it's pretty-silly for the panic to occur, especially since it comes from govmomi.

**Comment by chrislovecnm** [comment] 2016-05-07 02:47
@skuenzli It may have been fixed ... we are running a REALLY old version.  Currently testing the version bump.

**Comment by chrislovecnm** [comment] 2016-06-02 18:50
@jen20 @stack72 this is in the api code, not ours.  It is a licensing issue that we have seen a few times. You mind closing?

**Comment by stack72** [comment] 2016-06-02 19:19
This is no longer an issue as this was to do with the ESXi license

**Closed by stack72** 2016-06-02 19:19 UTC
Labels: bug, crash, provider/vsphere
