### ISSUE TITLE
Terraform is not able to enable Availability Zones in an Existing Azure AKS cluster

### ISSUE THREAD

**Issue by dilip-panwar-by** [hashicorp/terraform#27362] opened 2020-12-24 10:14 UTC
<!--
Terraform Version: 
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.33.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1

I am using `azurerm_kubernetes_cluster` resource for managging AKS cluster. I have a AKS cluster with below config:
```
kubernetes_vm_size    = "Standard_B2ms" # 2 vCPU / 8 GB RAM - https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-b-series-burstable
kubernetes_version  = "1.18.10"
node_count            = 1
enable_auto_scaling   = true
min_node_count        = 2
max_node_count        = 4
aks_load_balancer_sku = "Standard"

```
I am trying to upgrade my cluster to have availability zones and for that I have defined availability zones like this: `availability_zones    = ["1", "2", "3"]` . Below is code snippet:
```
resource "azurerm_kubernetes_cluster" "aks" {
  name                = local.cluster_name
  location            = var.location
  resource_group_name = var.resource_group_name
  dns_prefix          = "aks-${var.environment_type}"
  kubernetes_version  = var.kubernetes_version

  default_node_pool {
    name                 = "default"
    node_count           = var.node_count
    vm_size              = var.vm_size
    enable_auto_scaling  = var.enable_auto_scaling
    min_count            = var.min_node_count
    max_count            = var.max_node_count
    orchestrator_version = var.kubernetes_version
    vnet_subnet_id       = var.aks_subnet_id
    availability_zones   = var.availability_zones
  }

  addon_profile {
    ### The following addons are explicitly defined to their default values as Terraform (or the Azure provider) doesn't
    ### seem to handle implicit default values properly in all cases.  This can lead to unnecessary resource destruction
    ### and re-creation when values aren't changed in future plans.
    aci_connector_linux {
      enabled = false
    }
    azure_policy {
      enabled = false
    }
    http_application_routing {
      enabled = false
    }
    kube_dashboard {
      enabled = true
    }
    ### END DEFAULT DECLARATIONS

    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.aks-logs-workspace.id
    }
  }

  role_based_access_control {
    enabled = true
  }

  identity {
    type = "SystemAssigned"
  }

  tags = var.tags

  lifecycle {
    ignore_changes = [default_node_pool.0.node_count]
  }

  ### Network Configuration
  network_profile {
    network_plugin     = "kubenet"
    load_balancer_sku  = var.aks_load_balancer_sku
    dns_service_ip     = var.aks_dns_service_ip
    docker_bridge_cidr = var.aks_docker_bridge_cidr
    service_cidr       = var.aks_service_cidr
  }
}
```
With the above code when I am doing  `terraform plan` I get the below output:
![image](https://user-images.githubusercontent.com/69232967/103081275-a4459c80-45fd-11eb-8efc-f0a0f518ba32.png)

and after `terraform apply` I get below output:
![image](https://user-images.githubusercontent.com/69232967/103081396-de16a300-45fd-11eb-8cce-08d5058571be.png)

Now, if I do `terraform plan` again, it will still show the same execution plan since the availability zone is not enabled on AKS cluster.
AFAIK, if someone wants to enable the availability zone in VM scale sets in Azure, VMSS needs to be created again which means, through update it is not supported.

Can you please look into this issue and help us.

**Comment by danieldreier** [comment] 2020-12-25 23:08
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). 

I'm closing this issue because it doesn't follow the issue template we provide. Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, and then the Terraform maintainers will review it. Thanks!

Beyond using the template, it would help if you could make the following improvements to your issue when you re-file it:

- use a short issue description as a title
- use GitHub's [text formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax). You can do `markdown` and code formatting to make your code easier to read, which makes it easier for us to understand the issue. Please use markdown to format terraform code like this:
```HCL
resource "null_resource" "example" {
  name = "hello-world"
}
```
Please format terminal output for readability, like:
```shellsession
❯ terraform validate
Success! The configuration is valid.
```
- please provide all of the files involved in reproducing your example. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

**Closed by danieldreier** 2020-12-25 23:08 UTC
Labels: bug, new
