### ISSUE TITLE
Module to Module Dependency Creates a Cycle

### ISSUE THREAD

**Issue by rcha86** [hashicorp/terraform#11416] opened 2017-01-25 20:03 UTC
We are leveraging modules as a pattern for code reuse. For example, we create separate aws_launch_configurations for our different servers where the big differences might be just the number or type of server but the rest remains the same. The output from the launch config module is passed to another module where we create aws_autoscaling_groups, i.e. the launch config is tied to the autoscaling group.

This seems to cause cycles when trying to apply a change to the launch configuration, such as a new AMI or a change to the instance type or a new user_data.

### Terraform Version
0.8.4

### Affected Resource(s)
- aws_launch_configuration
- aws_autoscaling_group
- module

### Terraform Configuration Files
```hcl
module "launch-config" {
}
module "web-app" {
  launch-configuration = "${module.launch-config.config-name}"
}

# within the web-app module
resource "aws_autoscaling_group" "web-server-app" {
   name = "${var.app-name}-${var.environment}-${var.launch-configuration}"
   launch_configuration = "${var.launch-configuration}"
}
```

### Error message
Error message when applying
```bash
Cycle: module.web-app.aws_autoscaling_group.web-server-app, module.web-app.aws_autoscaling_group.web-server-app (destroy), module.launch-config.aws_launch_configuration.web-server (destroy), module.launch-config.output.config-name, module.web-app.var.launch-configuration
```

### Expected Behavior
The change to the launch config from the module propagates to the module where the launch config is used and applied successfully.

### Actual Behavior
The apply fails because terraform calculates a cycle.

### Workaround
If the module that uses the work around references a null_data_source with the launch config name, then there is no cycle.
```hcl
module "launch-config" {
}
data "null_data_source" "launch-config" {
  inputs = {
    config-name = "${module.launch-config.config-name}"
  }
}
module "web-app" {
  launch-configuration = "${data.null_data_source.launch-config.inputs["config-name"]}"
}

# within the web-app module
resource "aws_autoscaling_group" "web-server-app" {
   name = "${var.app-name}-${var.environment}-${var.launch-configuration}"
   launch_configuration = "${var.launch-configuration}"
}
```

**Comment by mitchellh** [comment] 2017-02-07 21:52
I believe this was caused by #11753 and should be fixed now. I'm unable to reproduce it locally.

If you have a reproduction case still after the above PR, please reopen a new issue and let us know! Thanks!

**Closed by mitchellh** 2017-02-07 21:52 UTC
Labels: bug, core
