### ISSUE TITLE
Interpolation/Expressions v0.12

### ISSUE THREAD

**Issue by infa-stopiwal** [hashicorp/terraform#21411] opened 2019-05-23 16:04 UTC
In version 0.11.x I had this line in aws_elb resource

```
subnets = ["${compact(split(",", var.subnets["subnets_db"]))}"]
```

Under v0.12, that same interpolation syntax fails with this error
```
Error: Incorrect attribute value type

  on main.tf line 61, in resource "aws_elb" "elasticsearch":
  61:   subnets = ["${compact(split(",", var.subnets["subnets_db"]))}"]

Inappropriate value for attribute "subnets": element 0: string required.
```

This is what is in my vars file:

```
variable "subnets" {
  type = "map"
  description = "All DB subnets"
  default = {
    subnets_db         = "subnet-00abc123,subnet-00xyz456"
  }
}
```

What am I doing wrong under the new version?

**Comment by mildwonkey** [comment] 2019-05-23 16:48
Hi @infa-stopiwal! Thanks for reporting this.

Can you please share some more of your configuration file - everything will help, but specifically I"d like to see that that `"aws_elb" "elasticsearch"` block ? I tried to reproduce this locally and wasn't able to, but that's very likely because I'm using a contrived example.

Here's what I tried, just so you can see:
```hcl
variable "subnets" {
  type = "map"
  description = "All DB subnets"
  default = {
    subnets_db         = "subnet-00abc123,subnet-00xyz456"
  }
}


locals {
  subnets = ["${compact(split(",", var.subnets["subnets_db"]))}"]
}

output "local" {
  value = local.subnets
}
```

And output:
```
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

local = [
  [
    "subnet-00abc123",
    "subnet-00xyz456",
  ],
]
```

**Comment by infa-stopiwal** [comment] 2019-05-23 17:30
@mildwonkey this is what the aws_elb block looks like (I don't have any config file for Terraform). I am truly surprised this is working for you!!!

```
resource "aws_elb" "elasticsearch" {
  name = "${var.project}-${var.env}-blue-es"
  internal = true
  subnets = "[${compact(split(",", var.subnets["subnets_db"]))}]"
  security_groups = ["${data.terraform_remote_state.clusters_sg.outputs.elasticsearch_sg_id}"]
  cross_zone_load_balancing = true
  idle_timeout = 600
  connection_draining = true
  connection_draining_timeout = 300

  access_logs {
    bucket = "${data.aws_s3_bucket.elb_logs.bucket}"
    bucket_prefix = "${var.project}-${var.env}-blue-elasticsearch"
    interval = "60"
  }

  listener {
    lb_port = 9200
    lb_protocol = "tcp"
    instance_port = 9200
    instance_protocol = "tcp"
  }

  listener {
    lb_port = 9300
    lb_protocol = "tcp"
    instance_port = 9300
    instance_protocol = "tcp"
  }

  listener {
    lb_port = 9400
    lb_protocol = "tcp"
    instance_port = 9400
    instance_protocol = "tcp"
  }

  health_check {
    healthy_threshold = 2
    unhealthy_threshold = 5
    timeout = 3
    target = "TCP:9200"
    interval = 5
  }

  tags = {
    ALERTGROUP      = "${upper(var.alert_group)}"
    APPLICATIONENV  = "${upper(var.env)}"
    BILLING         = "${var.billing_code}"
    BUSINESSENTITY  = "${upper(var.business_entity)}"
    BUSINESSUNIT    = "${upper(var.business_unit)}"
    CONSUL          = "${var.consul_endpoint}"
    OWNEREMAIL      = "${upper(var.owner_email)}"
    POD             = "${upper(var.pod)}"
    RUNNINGSCHEDULE = "${var.running_schedule}"
    SERVICENAME     = "${upper(var.elasticsearch["master_service_name"])}"
  }
}
```

**Comment by apparentlymart** [comment] 2019-05-23 17:42
Hi @infa-stopiwal!

Based on the fact that your configuration still includes interpolation sequences for all expressions, it looks like you didn't run [the upgrade tool](https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-configuration) to have it make an initial pass to update things for 0.12.

The problem you've hit here looks like one that the upgrade tool can't always solve (it doesn't always have enough information) but if you still see the problem after running the upgrade tool you can find more information on next steps in the upgrade guide section [Referring to List Variables](https://www.terraform.io/upgrade-guides/0-12.html#referring-to-list-variables).

If you've not seen the upgrade guide yet, I'd suggest [reading it from the beginning](https://www.terraform.io/upgrade-guides/0-12.html) (rather than skipping straight to the sections I indicated here) because there are some other recommendations in there for preparations that can make the upgrade process go more smoothly.

**Comment by infa-stopiwal** [comment] 2019-05-23 17:52
Thanks @apparentlymart I  did read through the upgrade docs and upgraded in line with whats in that document.

As a side node I was able to fix the problematic line from:
```
subnets = ["${compact(split(",", var.subnets["subnets_db"]))}"]
```

to

```
subnets = "${compact(split(",", var.subnets["subnets_db"]))}"
```

Note the missing "[ ]". This is because split and compact already output a list.

**Comment by apparentlymart** [comment] 2019-05-23 17:58
It sounds like the change described in [Referring to List Variables](https://www.terraform.io/upgrade-guides/0-12.html#referring-to-list-variables) did indeed solve the problem for you here, so I'm going to close this out. Thanks for following up!

**Closed by apparentlymart** 2019-05-23 17:58 UTC
Labels: question

**Comment by andreme** [comment] 2019-07-19 04:28
@apparentlymart The docs have it wrong: https://www.terraform.io/docs/providers/aws/r/lb.html

**Comment by teamterraform** [comment] 2019-07-19 20:58
Hi @andreme! Thanks for pointing that out.

That documentation belongs to the AWS provider, so it would be a great help if you could open an issue for it in [the AWS provider's repository](https://github.com/terraform-providers/terraform-provider-aws).

**Comment by christhomas** [comment] 2019-07-21 09:33
yeah, I remove the [] from the expression and mine started to work too, same problem, thanks!
