### ISSUE TITLE
Terraform crashes when running terraform init on version 1.9.3-1 in arch linux

### ISSUE THREAD

**Issue by suryanarayanan035** [hashicorp/terraform#35532] opened 2024-08-03 14:14 UTC
### Terraform Version

```shell
Terraform v1.9.3
on linux_amd64
```

### Terraform Configuration Files

 ------- seperate FILE -----

```
terraform {
        required_providers {
                docker = {
                        source="kreuzwerker/docker"
                        version = "3.0.2"
                }
        }
}
```
 ------- seperate FILE -----
```
resource "docker_container" "chat_backend" {
        name = "chat_backend"
        image = docker_image.chat_backend.image_id
        env = {
                ENV="development"
        }
        volumes = {
                container_path = "/app"
                host_path = "../"
                volume_name = "chat-backend"
        }
        networks_advanced = {
                name = "chat_network"
        }
        ports = {
                internal = 3000
                external = 3000
        }
}

resource "docker_container" "chat_database" {
        name = "chat_database"
        image = docker_image.chat_database.image_id
        volumes = {
                container_path = "/data"
                host_path = "../chat_database"
                volume_name = "chat-database"
        }
        command = "redis-server"
        networks_advanced = {
                name = "chat_network"
        }
        ports = {
                internal = 3001
                external = 3001
        }
}
```
 ------- seperate FILE -----
```
terraform {
        required_providers {
                docker = {
                        source="kreuzwerker/docker"
                        version="3.0.2"
                }
        }
}

resource "docker_image" "chat_backend" {
        name = "chat-backend"
        build {
                context = "../"
        }
}

resource "docker_image" "chat_database" {
        name = "redis"
        image = "redis:7.4"
}
```
 --------------- Seperate File -----------
```
terraform {
        required_providers {
                docker = {
                        source = "kreuzwerker/docker"
                        version = "3.0.2"
                {
        }
}

resource "docker_network" "chat_network" {
        name = "chat_network"
        driver = "bridge"
}
resource "docker_volume" "chat_database" {
        name = "chat_database"
}

resource "docker_volume" "chat_backend" {
        name = "chat_backend"
}
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        github.com/hashicorp/terraform/internal/logging/panic.go:84 +0x18b
panic({0x575ecc3a7800?, 0x575ece1d3a40?})
        runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/configs.NewModule({0xc000593ec0, 0x4, 0x1?}, {0x0, 0x0, 0x1?})
        github.com/hashicorp/terraform/internal/configs/module.go:142 +0xa90
github.com/hashicorp/terraform/internal/configs.NewModuleWithTests(...)
        github.com/hashicorp/terraform/internal/configs/module.go:102
github.com/hashicorp/terraform/internal/configs.(*Parser).LoadConfigDirWithTests(0xc0005932e0, {0x575ecc001c80, 0x1}, {0x575ecb768f9f?, 0x0?})
        github.com/hashicorp/terraform/internal/configs/parser_config_dir.go:73 +0x39b
github.com/hashicorp/terraform/internal/command.(*Meta).loadSingleModuleWithTests(0xc0006028c0, {0xc000084054?, 0xc000646f60?}, {0x575ecb768f9f, 0x5})
        github.com/hashicorp/terraform/internal/command/meta_config.go:108 +0xac
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0006028c0, {0xc000074050?, 0x0?, 0x0?})
        github.com/hashicorp/terraform/internal/command/init.go:163 +0xe7e
github.com/hashicorp/cli.(*CLI).Run(0xc000203180)
        github.com/hashicorp/cli@v1.1.6/cli.go:265 +0x5b8
main.realMain()
        github.com/hashicorp/terraform/main.go:339 +0x1e6b
main.main()
        github.com/hashicorp/terraform/main.go:64 +0x13

```

### Expected Behavior

TErraform init should have successfully completed without any isssue and all the necessary provider packages should have been installed.

### Actual Behavior

Presented with the error mentione

### Steps to Reproduce

Step 1: Create terraform files given in the terraform config files section
Step 2: Terraform init

I faced this issue in arch linux.

**Comment by liamcervante** [comment] 2024-08-05 10:28
Hi @suryanarayanan035, thanks for filing this! The underlying issue here is that you have three `required_providers` block defined within the same module. You can only define this block once.

Removing the duplicate `required_providers` blocks should resolve this for you. Terraform definitely shouldn't be crashing though, and should be reporting an error message explaining this so we'll put a fix together that improves the experience for you here.

**Comment by liamcervante** [comment] 2024-08-05 10:45
Also of note, is a syntax error . I've managed to replicate this when using the fourth file as an override for the third file. It no longer crashes once that typo is resolved in the override file. Running `terraform fmt` discovers and highlights the syntax error.

The crash occurs because the `required_providers` block in the override file is only partially loaded and is missing the source information associated with it. Then later when the duplicates are discovered, Terraform attempts to access the nil source information of the badly configured `required_providers` block and crashes.

**Comment by liamcervante** [comment] 2024-08-05 11:18
Okay, I misread some things and have been able to replicate this without using `_override` files now. But, the root cause is the same - still the misconfigured `terraform` block. The order the files are processed is important as well - if the file with the misconfigured `terraform` block is processed first, then we see the crash. Otherwise, it handles the invalid configuration properly and simply shows the error messages.

**Closed** 2024-08-06 08:38 UTC
Labels: bug, confirmed, explained
