### ISSUE TITLE
config: Passing map to object causes Terraform panic in interpolationWalker.Primitive

### ISSUE THREAD

**Issue by dgarstang** [hashicorp/terraform#14764] opened 2017-05-23 17:17 UTC
Code:

```
variable "ingress_rules" {
  type = "map"
  default = {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["1.1.1.1/32"]
  }
}
```

```
resource "aws_security_group" "security_group" {
  name        = "${var.service}-${var.environment}"
  description = "${var.service}-${var.environment}"
  ingress "${var.ingress_rules}"
  tags {
    Name = "${var.service}-${var.environment}"
    Environment = "${var.environment}"
  }
}
```

results in:
```
panic: reflect.Value.SetMapIndex: value of type map[string]interface {} is not assignable to type string

goroutine 213 [running]:
reflect.Value.assignTo(0x53608a0, 0xc4208929c0, 0x15, 0x5d81e91, 0x19, 0x5004740, 0x0, 0x5004740, 0xc4204fc3f0, 0x98)
	/opt/go/src/reflect/value.go:2175 +0x307
reflect.Value.SetMapIndex(0x53608a0, 0xc420854488, 0x195, 0x53608a0, 0xc4208929c0, 0x15, 0x52a3fa0, 0xc4204fc400, 0x94)
	/opt/go/src/reflect/value.go:1468 +0xb4
github.com/hashicorp/terraform/config.(*interpolationWalker).Primitive(0xc420574600, 0x5004740, 0xc4204fc3f0, 0x98, 0xc420574600, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/config/interpolate_walk.go:189 +0x38a
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkPrimitive(0x5004740, 0xc4204fc3f0, 0x98, 0x5932ec0, 0xc420574600, 0x3d094f4cc00, 0x


0)


	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:240 +0x80


github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x5004740, 0xc4204fc3f0, 0x98, 0x5932ec0, 0xc420574600, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:171 +0x23f
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkMap(0x53608a0, 0xc420854488, 0x195, 0x5932ec0, 0xc420574600, 0x3d094f4cc00, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:213 +0x270
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x53608a0, 0xc420854488, 0x195, 0x5932ec0, 0xc420574600, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:174 +0x2f8
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkSlice(0x4f8e580, 0xc420890d20, 0x97, 0x5932ec0, 0xc420574600, 0x97, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:272 +0x202
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x52a3fa0, 0xc4204fc350, 0x94, 0x5932ec0, 0xc420574600, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:177 +0x4e8
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkMap(0x53608a0, 0xc420892690, 0x15, 0x5932ec0, 0xc420574600, 0x3d094f4cc00, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:222 +0x2d2
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x53608a0, 0xc420892690, 0x15, 0x5932ec0, 0xc420574600, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:174 +0x2f8
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.Walk(0x53608a0, 0xc420892690, 0x5932ec0, 0xc420574600, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:84 +0x131
github.com/hashicorp/terraform/config.(*RawConfig).interpolate(0xc420814ea0, 0xc420461f50, 0xc420814ed8, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/raw_config.go:233 +0xea
github.com/hashicorp/terraform/config.(*RawConfig).Interpolate(0xc420814ea0, 0xc4208924e0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/raw_config.go:138 +0xe5
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).Interpolate(0xc420804000, 0xc420814ea0, 0xc4200d0780, 0x0, 0x0, 0x2e)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:304 +0x10f
github.com/hashicorp/terraform/terraform.(*EvalInterpolate).Eval(0xc420890940, 0x86f2ea0, 0xc420804000, 0x2, 0x2, 0x5d0de10, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_interpolate.go:14 +0x4b
github.com/hashicorp/terraform/terraform.EvalRaw(0x86c02c0, 0xc420890940, 0x86f2ea0, 0xc420804000, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc420890960, 0x86f2ea0, 0xc420804000, 0x2, 0x2, 0x5d0de10, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/hashicorp/terraform/terraform.EvalRaw(0x86c0580, 0xc420890960, 0x86f2ea0, 0xc420804000, 0x529faa0, 0xc4204612aa, 0x5004740, 0xc4204614a0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.Eval(0x86c0580, 0xc420890960, 0x86f2ea0, 0xc420804000, 0xc420890960, 0x86c0580, 0xc420890960, 0xc420478ea0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x5aa8d80, 0xc4208542a0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xd4d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc42026f420, 0x5aa8d80, 0xc4208542a0, 0xc4205bfb00)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x392
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x9ca



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by apparentlymart** [comment] 2017-05-23 17:45
Hi @dgarstang! Sorry for this crash.

What you're trying to do here isn't _intended_ to work, but indeed it should definitely not be crashing. I expect we will "fix" this by making it generate a proper error message, rather than making it do what you wanted here, unfortunately. :disappointed: 

Dynamically-generating nested blocks in resources is something that's been on our radar for a while, tracked in #7034. We'll be considering this and many other use-cases in some forthcoming language design work.

**Comment by radeksimko** [comment] 2017-08-04 14:44
This looks like a duplicate of #15319 - do you mind me closing it in favour of that issue @apparentlymart ?

**Comment by apparentlymart** [comment] 2017-08-08 01:17
Ahh yes, good catch @radeksimko. I'll close this one to consolidate the discussion in #15319 since it looks like @jbardin already did some investigation work over there.

**Closed by apparentlymart** 2017-08-08 01:17 UTC
Labels: bug, core, crash, waiting-response
