### ISSUE TITLE
0.6.7- No tags applying on aws_spot_instance_request

### ISSUE THREAD

**Issue by stolinzeev** [hashicorp/terraform#4057] opened 2015-11-25 08:12 UTC
```hcl
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "eu-west-1"
}

resource "aws_spot_instance_request" "server" {
  ami = "xxxxxxx"
  instance_type = "m3.large"
  spot_price = "0.3"
  wait_for_fulfillment = true
  key_name = "xxxxxxxx"
  iam_instance_profile = "xxxxxxx"
  security_groups = [
    "xxxxxxx"
  ]
  user_data = "${file("xxxxxxxxxxxxx.txt")}"

  tags {
    Name = "xxxxxxxx"
  }
}
resource "aws_route53_record" "server" {
  zone_id = "Z3B9RV5H90BA7G"
  name = "xxxxxxxx"
  type = "CNAME"
  ttl = "60"
  records = ["${aws_spot_instance_request.server.public_dns}"]
}
```

**Comment by baskaran-md** [comment] 2015-12-02 21:48
As far as I tested, these tags will be applied only on the spot requests, and not the actual instances created by these spot requests. 

Probably, terraform needs to apply the same tags to those instances launched by spot requests.

**Comment by baskaran-md** [comment] 2015-12-02 21:51
Duplicate of Issue #3263

**Comment by phinze** [comment] 2016-01-06 15:24
Closing as dup of #3263

**Closed by phinze** 2016-01-06 15:24 UTC
Labels: bug, provider/aws
