### ISSUE TITLE
Task in VSTS pipeline not work for terraform install - still here

### ISSUE THREAD

**Issue by JerryWang20** [hashicorp/terraform#31026] opened 2022-05-10 14:30 UTC
i still see the issue and can be reproduced in our VSTS site, is there any content change or format change for "https://releases.hashicorp.com/terraform/"?

================
Suddenly, the url of "https://releases.hashicorp.com/terraform/" does not return the value which cause install terraform in the pipeline to be fail

error trace as :

##[debug]Env:INPUT_VERSION: '0.14.9'
##[debug]GET https://releases.hashicorp.com/terraform/ with 0-byte payload
##[debug]received -1-byte response of content type text/html
##[debug]Caught exception from task script.

**Comment by jbardin** [comment] 2022-05-10 15:39
Duplicate of #31024

**Closed by jbardin** 2022-05-10 15:39 UTC
Labels: bug, new
