### ISSUE TITLE
`terraform show` missing schema for provider

### ISSUE THREAD

**Issue by anubbhavm** [hashicorp/terraform#24166] opened 2020-02-19 20:09 UTC
### Terraform Version

```
0.12.20
```

### Terraform Configuration Files

```hcl
module "healthcare_raw_dataset" {
  source = "../../modules/healthcare"

  org            = var.org_name
  classification = var.classification
  purpose        = "raw"
  env            = var.env

  project  = module.restricted_lake_project.project_id
  location = var.healthcare_location

  fhir_stores = [{
    name = "fhir"
  }]
  hl7_v2_stores = [{
    name = "hl7"
  }]
}

resource "google_healthcare_dataset" "dataset" {
  provider  = google-beta
  name      = lower(join("-", [var.org, var.classification, var.purpose, var.location, var.env]))
  project   = var.project
  location  = var.location
  time_zone = var.time_zone
}
resource "google_healthcare_fhir_store" "fhir_stores" {
  provider = google-beta
  for_each = {
    for s in var.fhir_stores :
    s.name => s
  }
  name = format("%s-%s", google_healthcare_dataset.dataset.name, each.value.name)
  dynamic "notification_config" {
    for_each = lookup(each.value, "notification_config", null) != null ? [each.value.notification_config] : []
    content {
      pubsub_topic = lookup(each.value.notification_config, "pubsub_topic", "")
    }
  }
  dataset = google_healthcare_dataset.dataset.id
}

resource "google_healthcare_hl7_v2_store" "hl7_v2_stores" {
  provider = google-beta
  for_each = {
    for s in var.hl7_v2_stores :
    s.name => s
  }
  name = format("%s-%s", google_healthcare_dataset.dataset.name, each.value.name)
  dynamic "notification_config" {
    for_each = lookup(each.value, "notification_config", null) != null ? [each.value.notification_config] : []
    content {
      pubsub_topic = lookup(each.value.notification_config, "pubsub_topic", "")
    }
  }
  dataset = google_healthcare_dataset.dataset.id
}

```

### Expected Behavior
`terraform show` should output the schema

### Actual Behavior
module.healthcare_raw_dataset.google_healthcare_dataset.dataset:
missing schema for provider "google" resource type google_healthcare_dataset

module.healthcare_raw_dataset.google_healthcare_fhir_store.fhir_stores["fhir"]:
missing schema for provider "google" resource type google_healthcare_fhir_store

module.healthcare_raw_dataset.google_healthcare_hl7_v2_store.hl7_v2_stores["hl7"]:
missing schema for provider "google" resource type google_healthcare_hl7_v2_store

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform show`

**Comment by apparentlymart** [comment] 2020-06-22 19:01
Hi @anubbhavm! Sorry for this odd behavior, and thanks for reporting it.

The problem here seems to be arising from the fact that these resources have `provider = google-beta` set, which is the correct way to use the `google-beta` provider but `terraform show` doesn't seem to be handling it correctly: it's apparently trying to request the schema from the `google` provider instead, presumably because it's relying on the `google_` prefix on the resource type name rather than consulting the provider address recorded in the state (which is derived from the `provider` argument in the configuration).

On the plus side, I suspect this has already been fixed as a side-effect of the refactoring we did of how providers relate to resources in order to support a decentralized namespace for providers in Terraform 0.13. That work has essentially replaced the previous logic for understanding the relationships between resources and providers to use fully-qualified provider source addresses internally. The `terraform show` command is therefore now using that new mechanism to find the schema, rather than the buggy way it was working before:

https://github.com/hashicorp/terraform/blob/43737f2f4f15eec0f1e7594d6fd1366819d069f3/command/format/state.go#L144-L152

Since the code that was responsible for this bug has changed significantly in the v0.13 work, and I was unable to reproduce the issue as stated on a v0.13.0 prerelease build, I'm going to close this out. If someone in the future sees a similar error on Terraform v0.13 or later, please open a _new issue_ for that, completing the issue template, because we'll need a fresh set of logs/etc generated by the new v0.13 logic in order to investigate it.

Thanks again for reporting this!

**Closed by apparentlymart** 2020-06-22 19:01 UTC
Labels: bug, cli, v0.12
