### ISSUE TITLE
openstack_compute_floatingip_v2 always recreates FIP when using pool id instead pool name

### ISSUE THREAD

**Issue by Kiemes** [hashicorp/terraform#9952] opened 2016-11-08 13:00 UTC
### Terraform Version
0.7.9

### Affected Resource(s)
openstack_compute_floatingip_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_floatingip_v2" "lifecycle_floating_ip" {
  region = "${var.region_name}"
  pool   = "${var.ext_net_id}"
}
```

### Expected/Actual Behavior
We know that according to the [documentation](https://www.terraform.io/docs/providers/openstack/r/compute_floatingip_v2.html) the pool value should be a pool name and not the pool id as we used it by mistake. When using the pool id, the FIP is created correctly as the [OpenStack API](http://developer.openstack.org/api-ref/compute/?expanded=create-allocate-floating-ip-address-detail) also allows a pool id (even if not mentioned explicitly). But it is recreated on every run of `terraform  apply` and not  just kept as it is, when it's already there.

Expected behavior would be that there either is an error message when a non-existent name is used (such as the pool id), or that the state check works with the id as well, and the floating IP is not recreated when it already exists.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with a configuration containing a floating IP  and the pool referenced with the id
2. `terraform apply` on the same configuration

**Comment by jtopjian** [comment] 2016-11-08 15:28
Thank you for reporting this. This is definitely not expected behavior.

I have a few questions:

1. Does this happen when you use the `openstack_networking_floatingip_v2` resource? If your OpenStack environment uses Neutron (which I imagine it would nowadays), both resources interact with Neutron an the same floating IP pool in the end.

2. Can you tell me more about your OpenStack environment (what release, what Neutron driver, etc) as well as provide a full Terraform configuration of how this is being triggered?

Thanks again! Hopefully we can sort this out.

**Comment by beyhan** [comment] 2016-11-09 15:26
@jtopjian 
Hi, we verified 1):
When using `openstack_networking_floatingip_v2`, the expected error message is actually raised.
```
openstack_networking_floatingip_v2.lifecycle_floating_ip: Creating...
  address:   "" => "<computed>"
  fixed_ip:  "" => "<computed>"
  pool:      "" => "90e5af93-b59b-46ab-8a3e-0febe1a6b9ad"
  port_id:   "" => "<computed>"
  region:    "" => <redacted>
  tenant_id: "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* openstack_networking_floatingip_v2.lifecycle_floating_ip: No network found with name: 90e5af93-b59b-46ab-8a3e-0febe1a6b9ad

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

On 2):
You are right, we are using Neutron. We tested that in two Liberty and two Mitaka installations. 3 are Open vSwitch, the other, I don't know. But same behavior on all four installations.

For the test, the full Terraform configuration is
```
provider "openstack" {
  auth_url    = <redacted>
  user_name   = <redacted>
  password    = <redacted>
  tenant_name = <redacted>
  domain_name = <redacted>
  insecure = <redacted>
}

resource "openstack_networking_floatingip_v2" "lifecycle_floating_ip" {
  region = <redacted>
  pool   = "90e5af93-b59b-46ab-8a3e-0febe1a6b9ad"
}
```

**Comment by jtopjian** [comment] 2017-03-12 03:25
Hi all,

I just had a chance to revisit this and verify some things:

* Yes, the `openstack_networking_floatingip_v2` resource correctly handles the case where a _name_ could not be found.
* The `openstack_compute_floatingip_v2` resource does not.

The `openstack_compute_floatingip_v2` resource uses Nova-only APIs and, long story short, it's a bit of a hassle to add the ID-to-name functionality to it. This is already done in the `openstack_compute_instance_v2` resource and occasionally issues are reported due to some OpenStack clouds disabling access to that API. That Nova API has also been marked as deprecated, so it's only a matter of time before it doesn't work at all.

The best thing to do is to use the `openstack_networking_floatingip_v2` resource, especially since you're using Neutron. The only reason someone would have to use `openstack_compute_floatingip_v2` is if they were still using nova-network instead of Neutron.

Recently, an `openstack_networking_network_v2` data source was added to Terraform. This allows querying for a network. I've just opened up a PR (#12615) to add the ability to do ID-to-name translations:

```hcl
data "openstack_networking_network_v2" "floating_pool" {               
  network_id = "6e1bcab2-94c2-4d2c-8ee4-c53d43f12dc4"                  
}                                                                      
                                                                       
resource "openstack_compute_floatingip_v2" "lifecycle_floating_ip" {   
  pool = "${data.openstack_networking_network_v2.floating_pool.name}"
}                                                                      
```

So if you still want to use `openstack_compute_floatingip_v2` with a network ID, this would be the best way to do it.

Let me know if you have any questions or need any clarification or more details :)

Thanks,
Joe

**Comment by Kiemes** [comment] 2017-03-13 08:13
You are right, we are using Neutron, that is why we could change safely to `openstack_networking_floatingip_v2`. We do not have any issues with this anymore, but I think we should do something about it anyway.

The issue actually was not necessarily about adding the support for pool ID. I just wanted to raise the awareness of the current behaviour which might lead people into trouble, as it did with us.

As I wrote above, raising an error when using a non-existent name would be fine with me as well. For  that you would not need the hassling ID-to-name functionality. This leads to pool id not working explicitly. At the moment, it is implicitly broken.

**Comment by jtopjian** [comment] 2017-03-13 15:35
> The issue actually was not necessarily about adding the support for pool ID. 

Yep, I understand. However, that was the quick and easy way to resolve this problem. It did two things:

1. Retain your previous configuration of using `${var.ext_net_id}` rather than introduce a new `${var.floating_pool_name}`
2. Provided a roundabout way to verify if a pool name actually exists.

Now, I get that the most straightforward and logical solution is to simply check and see if the user input matches correctly to a valid pool name. To do that, I'd have to add support for [`os-floating-ip-pool`](https://developer.openstack.org/api-ref/compute/#floating-ip-pools-os-floating-ip-pools-deprecated) to Gophercloud first, and then to the `openstack_compute_floatingip_v2` resource. I can certainly keep this in mind to do, but it's going to be a lower priority compared to some other work. I'd be more than happy to assist anyone else who wanted to do this work before I get to it, though. :)

I hope that makes sense?

**Closed** 2017-06-13 18:05 UTC
Labels: provider/openstack
