### ISSUE TITLE
all route_rules gets recreated if there is any change in one of the route_rule

### ISSUE THREAD

**Issue by vineethng** [hashicorp/terraform#32991] opened 2023-04-05 21:48 UTC
### Terraform Version

```shell
Terraform v1.4.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/oci v4.115.0


I have tried this on all the versions after 1.4.0, event tried terraform_1.5.0-alpha20230405
```

### Terraform Configuration Files

terraform {
  required_version = "1.4.0"
  backend "consul" {
    address = "x.x.x.x:x"
    path    = "terraform-main.tfstate"
  }
}
provider "oci" {
  tenancy_ocid         = "${var.tenancy_ocid}"
  user_ocid            = "${var.user_ocid}"
  fingerprint          = "${var.fingerprint}"
  private_key_path     = "${var.private_key_path}"
  private_key_password = "${var.private_key_password}"
  region               = "${var.region}"
}

### Debug Output

Debug output

### Expected Behavior

terraform plan should show the changes for one route rule.

### Actual Behavior

All route rule are getting removed and added with the below optional attribute
 + route_type        = (known after apply)

### Steps to Reproduce

1. terraform init
2. make changes to one of the 10 route rules
3. terraform apply

### Additional Context

I tried this in 1.3.9, there is working fine. terraform apply will show only change in the one route rule

**Comment by liamcervante** [comment] 2023-04-06 09:23
Hi @vineethng, thanks for filing this!

Are you able to share config that includes the route rules you have plus another showing the change you made? That would make it easier for us to replicate the issue.

Thanks!

**Comment by vineethng** [comment] 2023-04-06 13:28
terraform {
  required_version = "1.3.9"
  backend "consul" {
    address = "x.x.x.x:x"
    path    = "terraform-main.tfstate"
  }
}

provider "oci" {
  tenancy_ocid         = "${var.tenancy_ocid}"
  user_ocid            = "${var.user_ocid}"
  fingerprint          = "${var.fingerprint}"
  private_key_path     = "${var.private_key_path}"
  private_key_password = "${var.private_key_password}"
  region               = "${var.region}"
}

module "private-route-table" {
  source = "../../blue_prints/route-table"
  compartment_id = "${var.parent_compartment_id}"
  route_rules = "${local.route_rules_pvt_routing}"
  route_table_display_name = "rt-${var.vcn_display_name}"
  vcn_id = "${module.vcn.vcn_id}"
  tags_cost_tracking = local.tags_cost_tracking_apps
}

locals {
  route_rules_pvt_routing = [
    {network_entity_id = "${module.vcn.drg_id}" , destination ="${var.cidr_dev.app_dev}", destination_type = "${var.destination_type_CIDR}", description = "Routing description dev"},
{network_entity_id = "${module.vcn.drg_id}" , destination ="${var.cidr_dev.app_qa}", destination_type = "${var.destination_type_CIDR}", description = "Routing description qa"}
  ]
}

I upgraded the terraform version to 1.4.0 and made a change in the description of the route rule.

locals {
  route_rules_pvt_routing = [
    {network_entity_id = "${module.vcn.drg_id}" , destination ="${var.cidr_dev.app_dev}", destination_type = "${var.destination_type_CIDR}", description = "Routing description dev updated"},
{network_entity_id = "${module.vcn.drg_id}" , destination ="${var.cidr_dev.app_qa}", destination_type = "${var.destination_type_CIDR}", description = "Routing description qa"}
  ]
}

The output of the plan is given below.

      - route_rules {
          - description       = "Routing description qa" -> null
          - destination       = "x.x.x.x/x" -> null
          - destination_type  = "CIDR_BLOCK" -> null
          - network_entity_id = "ocid1.drg.oc1...." -> null
        }
      - route_rules {
          - description       = "Routing description dev" -> null
          - destination       = "x.x.x.x/x" -> null
          - destination_type  = "CIDR_BLOCK" -> null
          - network_entity_id = "ocid1.drg.oc1...." -> null
        }
      + route_rules {
          + cidr_block        = (known after apply)
          + description       = "Routing description qa"
          + destination       = "x.x.x.x/x"
          + destination_type  = "CIDR_BLOCK"
          + network_entity_id = "ocid1.drg.oc1...."
          + route_type        = (known after apply)
        }
      + route_rules {
          + cidr_block        = (known after apply)
          + description       = "Routing description dev updated"
          + destination       = "x.x.x.x/x"
          + destination_type  = "CIDR_BLOCK"
          + network_entity_id = "ocid1.drg.oc1...."
          + route_type        = (known after apply)
        }

What I noticed is that the state files are not getting updated with the value of route_type.

**Comment by jbardin** [comment] 2023-04-10 21:19
@vineethng,

What we would need to see is the source of the `private-route-table` where the `route_rules` are defined, modified, or assigned to a resource configuration block. 

One guess as to what is happening here is that this is a set type resource attribute with invalid values assigned by the provider leading to unexpected behavior when Terraform needs to plan the changes. if that is the case, then I would expect to see `WARN` lines in the log corresponding to these values during the plan.

**Comment by liamcervante** [comment] 2023-04-11 10:42
So, I have been able to confirm:

1. `route_rules` is indeed a set: https://github.com/oracle/terraform-provider-oci/blob/251cef11d1bf556d4c1690a80cd45c0fc1ff68d9/internal/service/core/core_route_table_resource.go#L62
2. The `oci` provider can return null for both [`route_type`](https://github.com/oracle/terraform-provider-oci/blob/251cef11d1bf556d4c1690a80cd45c0fc1ff68d9/internal/service/core/core_route_table_resource.go#L419) and [`cidr_block`](https://github.com/oracle/terraform-provider-oci/blob/251cef11d1bf556d4c1690a80cd45c0fc1ff68d9/internal/service/core/core_route_table_resource.go#L409)
3. Both of these attributes are marked as being computed: https://github.com/oracle/terraform-provider-oci/blob/251cef11d1bf556d4c1690a80cd45c0fc1ff68d9/internal/service/core/core_route_table_resource.go#L101

So, what's happening here is that the values for those attributes are null in both the current state and the plan but the plan is reporting that they will be computed so Terraform assumes those values will change from null to something concrete and renders the plan as such. Since it is a set and Terraform can't tell that items in a set are being updated, it reports everything that's changed as being deleted and new items added.

I have been able to replicate this with the tfcoremock provider by telling it to return null values for computed attributes. But, this happens for me in `v1.3.9` and `v1.4.*` so there might be something I'm missing which I'll keep looking for. Either way, I'm not sure whether this is a problem for Terraform Core or the provider - should the provider be declaring these attributes as computed at all, especially if it is going to returning their value as null? Possibly it should be returning a sensible default for all values marked as computed? Or do we need to change something in Terraform so that it knows the difference between this value is null and won't be recomputed and this value is null and will be recomputed. I'm not sure right now.

We did update the renderer in 1.4.* so maybe the old renderer could tell the difference between actually null, and null and will be computed. For now, I will keep investigating to see if I can replicate the behaviour change from v3 to v4 with a simpler config.

**Comment by liamcervante** [comment] 2023-04-11 10:43
I've marked this as confirmed, in that it's either a problem with the new renderer or a problem in the provider.

We might still redirect this to the team at Oracle.

**Comment by jbardin** [comment] 2023-04-11 14:34
I have confirmed the change in behavior with v1.4, but I doubt there's anything we can do at this point.

Terraform v1.4 actually plans the correct value, but the legacy SDK is interpreting that identical prior value as a change, resulting in the output shown. While Terraform v1.3 was creating a less-precise plan (which included the change!), the legacy SDK just happened to turn that planned value into a value identical to the prior state, resulting in what appeared to be no change.

Looking at the OCI provider code, the `route_rules` are always handled as a complete set, so I would expect that even though there is extra output shown in the diff, the end result will behave identically. Since this is a misbehavior of the legacy SDK which can only arise with certain combinations of optional+computed string attributes, we can probably only mark this as an unfortunate behavior that will be fixed once they migrate to the new provider framework.

**Closed** 2023-04-11 15:36 UTC
Labels: bug, confirmed, explained
