### ISSUE TITLE
Crash when evaluating plan of azurerm_monitor_diagnostic_categories

### ISSUE THREAD

**Issue by jeromewaibel** [hashicorp/terraform#26095] opened 2020-09-02 13:25 UTC
### Terraform Version

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/azurerm v2.25.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "= 0.13.1"

  required_providers {
    azurerm = "= 2.25"
  }
}

resource "azurerm_resource_group" "this" {
  name     = "jerome-test-rg"
  location = "westeurope"
}

resource "azurerm_databricks_workspace" "this" {
  name                = "jerome-test-db"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location
  sku                 = "standard"
}

data "azurerm_monitor_diagnostic_categories" "this" {
  resource_id = azurerm_databricks_workspace.this.id
}
```

### Crash Output

```
panic: not a collection type

goroutine 136 [running]:
github.com/zclconf/go-cty/cty.Type.ElementType(0x2ce50a0, 0xc0006f4340, 0xc00069deb8, 0x8)
        /home/circleci/project/project/vendor/github.com/zclconf/go-cty/cty/collection.go:25 +0xba
github.com/hashicorp/terraform/terraform.createEmptyBlocks(0xc00087a690, 0x2ce50a0, 0xc0006f4358, 0x2300040, 0xc0014bfe60, 0x2ce50a0, 0xc0006f44a8, 0x2300040, 0xc0014ea7e0)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:242 +0x202
github.com/hashicorp/terraform/terraform.dataObjectHasChanges(0xc00087a690, 0x2ce50a0, 0xc0006f4358, 0x2300040, 0xc0014bfe60, 0x2ce50a0, 0xc0006f44a8, 0x2300040, 0xc0014ea7e0, 0x0, ...)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:211 +0x19e
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc0014cc000, 0x2d26860, 0xc0005f9520, 0x1, 0x1, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:107 +0x1238
github.com/hashicorp/terraform/terraform.EvalRaw(0x2c7d420, 0xc0014cc000, 0x2d26860, 0xc0005f9520, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000cb30a0, 0x2d26860, 0xc0005f9520, 0x1, 0x1, 0x6, 0xc000651970)
        /home/circleci/project/project/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2c7ce80, 0xc000cb30a0, 0x2d26860, 0xc0005f9520, 0x22b4bc0, 0x3fa2622, 0x2214980, 0xc00011e710)
        /home/circleci/project/project/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.Eval(0x2c7ce80, 0xc000cb30a0, 0x2d26860, 0xc0005f9520, 0xc000cb30a0, 0x2c7ce80, 0xc000cb30a0, 0x0)
        /home/circleci/project/project/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2645300, 0xc00099bd70, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:73 +0xc77
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000651860, 0x2645300, 0xc00099bd70, 0xc000126c00)
        /home/circleci/project/project/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x11d7
```
### Expected Behavior

Anything but a crash.

### Actual Behavior

Crash.

### Steps to Reproduce

1. terraform init
2. terraform apply
3. terraform apply

Second apply will try to refresh its state and crash.

**Comment by jbardin** [comment] 2020-09-02 16:50
Duplicate of #26011

**Closed by jbardin** 2020-09-02 16:50 UTC
Labels: bug, new
