### ISSUE TITLE
Terraform recreates google_compute_instance resource with random even if random is not changed

### ISSUE THREAD

**Issue by zbikmarc** [hashicorp/terraform#13417] opened 2017-04-06 09:40 UTC
Hi,

it looks like terraform is forcing to recreate instance with random name included, even if random is not changed. It looks like name is forcing to rebuild.
```
name:  "instance-22d20367" => "instance-${element(random_id.server-suffix.*.hex, count.index)}" (forces new resource)
```

### Terraform Version
0.9.2

### Affected Resource(s)
at least:
- google_compute_instance

### Terraform Configuration Files
```hcl
variable "provider-credentials" {}
variable "provider-project" {}
variable "region" {}
variable "zone" {}
variable "subnetwork" {}
variable "subnetwork_project" {}
variable "size" {}

provider "google" {
  credentials = "${file(var.provider-credentials)}"
  project     = "${var.provider-project}"
  region      = "${var.region}"
}

resource "random_id" "server-suffix" {
  count       = "${var.size}"
  byte_length = 4
}

resource "google_compute_instance" "instance" {
  count = "${var.size}"

  name         = "instance-${element(random_id.server-suffix.*.hex, count.index)}"
  machine_type = "n1-standard-1"
  zone         = "${var.zone}"

  disk = {
    image = "centos-7"
    type  = "pd-ssd"
  }

  network_interface {
    subnetwork         = "${var.subnetwork}"
    subnetwork_project = "${var.subnetwork_project}"
  }
}
```

### Debug Output
Debug output of plan when size is changed from 1 to 2: https://gist.github.com/zbikmarc/f6ef5ac6d416157822ed6c7914b9513e

### Expected Behavior
Terraform should not recreate instance if name is not changed, even if it uses random - which does not change in this case.

### Actual Behavior
Terraform destroys instance-{random_here} even if {random_here} is not changed.

```
-/+ google_compute_instance.instance.0
    can_ip_forward:                         "false" => "false"
    create_timeout:                         "4" => "4"
    disk.#:                                 "1" => "1"
    disk.0.auto_delete:                     "true" => "true"
    disk.0.disk_encryption_key_sha256:      "" => "<computed>"
    disk.0.image:                           "centos-7" => "centos-7"
    disk.0.type:                            "pd-ssd" => "pd-ssd"
    machine_type:                           "n1-standard-1" => "n1-standard-1"
    metadata_fingerprint:                   "-hvVEUF_j_4=" => "<computed>"
    name:                                   "instance-22d20367" => "instance-${element(random_id.server-suffix.*.hex, count.index)}" (forces new resource)
    network_interface.#:                    "1" => "1"
    network_interface.0.address:            "10.206.250.72" => "<computed>"
    network_interface.0.name:               "nic0" => "<computed>"
    network_interface.0.subnetwork:         "REGULAR_PROJECT" => "REGULAR_PROJECT"
    network_interface.0.subnetwork_project: "XPN_PROJECT" => "XPN_PROJECT"
    self_link:                              "https://www.googleapis.com/compute/v1/projects/REGULAR_PROJECT/zones/us-central1-a/instances/instance-22d20367" => "<computed>"
    tags_fingerprint:                       "42WmSpB8rSM=" => "<computed>"
    zone:                                   "us-central1-a" => "us-central1-a"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Copy provided Terraform config file`
1.1 `optionally remove xpn networks if needed`
1. `terraform apply`
1. `change size to bigger one`
1. `terraform plan or apply`

**Comment by paddycarver** [comment] 2017-04-26 22:44
Hey @zbikmarc! Sorry for the long delay on a response to this. It confounded me for a bit, and I kept chasing red herrings trying to find a root cause.

This is essentially the same bug as #13763, which itself is a manifestation of #3449. Basically, because you're using `element`, Terraform sees that the list is changed, and assumes everything changes. @apparentlymart explained it _much_ better than I can in #13763, so I'm just going to borrow his explanation:

> The problem is that currently Terraform isn't able to understand that `element` only refers to the `count.index` element of the list, and so it assumes that because the list contains something computed the result must itself be computed, causing Terraform to think that the name has updated for all of your addresses.

A workaround that worked in my reproduction of the issue is to run

> terraform plan -out=tfplan -target=random_id.server-suffix

And make sure it only intends to add the new random_id. Then run `terraform apply tfplan`. Then a normal plan/apply cycle should only add the new instance, because Terraform already has the ID, so the list isn't changing.

I'm going to go ahead and close this issue, but if you have questions or this doesn't work for you, feel free to comment. Also, it looks like @apparentlymart has a fix for this opened as hashicorp/hil#51, so if that gets merged, this will become unnecessary in the future.

**Closed by paddycarver** 2017-04-26 22:44 UTC
Labels: provider/google-cloud

**Comment by zbikmarc** [comment] 2017-05-11 13:19
I would like to just add supplementary information to this.
To make this working one need to target both relevant resources. So in this case both: `google_compute_instance.instance` and `random_id.server-suffix`.

```bash
terraform plan -out=tfplan -target=random_id.server-suffix -target=google_compute_instance.instance -var size={new_size_here}
```
and then
```bash 
terraform apply tfplan
```
Without `-target=google_compute_instance.instance` it changes only `random_id.server-suffix` without touching `google_compute_instance.instance`.

**Comment by zbikmarc** [comment] 2017-05-11 14:12
Very strange thing, it works for sizing up, but not sizing down...

Size up: https://gist.github.com/zbikmarc/243ea801aa7577fb6cbe4c5ceaa9ac30
Size down: https://gist.github.com/zbikmarc/7959e91aaf98a1cc56cd8a9a2fe3839b
