### ISSUE TITLE
diffs didn't match during apply for aws_autoscaling_group with load_balancers that gets its name from template_file

### ISSUE THREAD

**Issue by kiich** [hashicorp/terraform#8135] opened 2016-08-11 15:24 UTC
### Terraform Version

Terraform v0.6.15
### Affected Resource(s)
- aws_auto_scaling_group
- aws_elb

I'm using template_file to work around the fact i can not create a variable from another variable using the following:

**resource "template_file" "CLUSTER_ID" {
  template = "${environment_and_cluster_id}"
    vars {
        environment_and_cluster_id = "${var.ENVIRONMENT}-${var.CLUSTER_NAME}"
    }
}**

and then i use the above in my elb:

**resource "aws_elb" "kubernetes-masters" {
  connection_draining = true
  name = "${template_file.CLUSTER_ID.rendered}-masters-balancer"
[...]**

which then gets used in auto_scaling_group resource:

**resource "aws_autoscaling_group" "kubernetes-master-group" {
  health_check_grace_period = 300
  health_check_type = "EC2"
  launch_configuration      = "${aws_launch_configuration.kubernetes-master-group.name}"
  min_size                  = "${var.NUMBER_OF_MASTERS}"
  max_size                  = "${var.NUMBER_OF_MASTERS}"
  default_cooldown          = 10
  name                      = "${template_file.CLUSTER_ID.rendered}-master-group"
  load_balancers = ["${aws_elb.kubernetes-masters.name}"]**

the above works with `terraform plan` but when i apply, i get:

```
Error applying plan:

1 error(s) occurred:

* aws_autoscaling_group.kubernetes-master-group: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

```

```
Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_autoscaling_group.kubernetes-master-group
    Mismatch reason: attribute mismatch: load_balancers.2247416251
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"launch_configuration":*terraform.ResourceAttrDiff{Old:"", New:"${aws_launch_configuration.kubernetes-master-group.name}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.#":*terraform.ResourceAttrDiff{Old:"", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "max_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.776695200.value":*terraform.ResourceAttrDiff{Old:"", New:"dev", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "load_balancers.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1588516840.key":*terraform.ResourceAttrDiff{Old:"", New:"Type", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.776695200.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"${template_file.CLUSTER_ID.rendered}-master-group", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "tag.4033810759.value":*terraform.ResourceAttrDiff{Old:"", New:"DO NOT REMOVE THIS TAG AS IT IS NEEDED BY K8S", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "desired_capacity":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "availability_zones.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.~4101362645.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.~4101362645.value":*terraform.ResourceAttrDiff{Old:"", New:"${template_file.CLUSTER_ID.rendered}-master", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "force_delete":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "metrics_granularity":*terraform.ResourceAttrDiff{Old:"", New:"1Minute", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "wait_for_capacity_timeout":*terraform.ResourceAttrDiff{Old:"", New:"10m", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.~4101362645.key":*terraform.ResourceAttrDiff{Old:"", New:"Name", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1588516840.value":*terraform.ResourceAttrDiff{Old:"", New:"kubernetes-master", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "load_balancers.2247416251":*terraform.ResourceAttrDiff{Old:"", New:"${template_file.CLUSTER_ID.rendered}-masters-balancer", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.4033810759.key":*terraform.ResourceAttrDiff{Old:"", New:"dev-KubernetesCluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "min_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.776695200.key":*terraform.ResourceAttrDiff{Old:"", New:"Environment", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.4033810759.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "health_check_type":*terraform.ResourceAttrDiff{Old:"", New:"EC2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "health_check_grace_period":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "default_cooldown":*terraform.ResourceAttrDiff{Old:"", New:"10", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1588516840.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"tag.776695200.value":*terraform.ResourceAttrDiff{Old:"", New:"dev", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1404178446.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "launch_configuration":*terraform.ResourceAttrDiff{Old:"", New:"dev-kubernetes-master-group-m5yzx3lkn5eipcrvkr6v65b2ba", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.#":*terraform.ResourceAttrDiff{Old:"", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "vpc_zone_identifier.2217186662":*terraform.ResourceAttrDiff{Old:"", New:"subnet-be5835c8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1588516840.key":*terraform.ResourceAttrDiff{Old:"", New:"Type", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.4033810759.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"dev-kubernetes-master-group", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "tag.1588516840.value":*terraform.ResourceAttrDiff{Old:"", New:"kubernetes-master", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "wait_for_capacity_timeout":*terraform.ResourceAttrDiff{Old:"", New:"10m", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1588516840.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.776695200.key":*terraform.ResourceAttrDiff{Old:"", New:"Environment", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "load_balancers.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.776695200.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "min_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "desired_capacity":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "health_check_type":*terraform.ResourceAttrDiff{Old:"", New:"EC2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1404178446.value":*terraform.ResourceAttrDiff{Old:"", New:"dev-kubernetes-master", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.1404178446.key":*terraform.ResourceAttrDiff{Old:"", New:"Name", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "metrics_granularity":*terraform.ResourceAttrDiff{Old:"", New:"1Minute", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.4033810759.key":*terraform.ResourceAttrDiff{Old:"", New:"dev-KubernetesCluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tag.4033810759.value":*terraform.ResourceAttrDiff{Old:"", New:"DO NOT REMOVE THIS TAG AS IT IS NEEDED BY K8S", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "health_check_grace_period":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "availability_zones.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "force_delete":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "max_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "load_balancers.1186868677":*terraform.ResourceAttrDiff{Old:"", New:"dev-kubernetes-masters-balancer", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "default_cooldown":*terraform.ResourceAttrDiff{Old:"", New:"10", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.`
```

if i change the name in the elb to NOT use the template rendered value, i.e. 

**resource "aws_elb" "kubernetes-masters" {
  connection_draining = true
  name = "${var.ENVIRONMENT}-${var.CLUSTER_NAME}-masters-balancer"**

it all works fine.
### Expected Behavior

apply should work after plan
### Actual Behavior

apply failed with the above message.

**Comment by mitchellh** [comment] 2016-11-17 17:47
Hello! This should be fixed in later versions of Terraform (0.7.11 at time of writing). 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 17:47 UTC
Labels: bug, provider/aws
