### ISSUE TITLE
Reading value from map is broken

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#6701] opened 2016-05-17 00:31 UTC
I've just built Terraform from the master branch in order to play with list variables. I've noticed that default values for `map` variables don't seem to work as expected (or, rather, don't seem to be working as they do in version 0.6.16). The following code snippet reproduces the issue:

```
variable "map" {
  type = "map"

  default = {
    x = "foo"
  }
}

resource "template_file" "test" {
  template = "${file("${path.module}/test.json")}"

  vars {
    x = "${var.map.x}"
  }
}
```

In Terraform 0.6.16, `terraform plan` produces the following output:

```
+ template_file.test
    rendered: "" => "<computed>"
    template: "" => "{}\n"
    vars.#:   "" => "1"
    vars.x:   "" => "foo"
```

At `HEAD` of the master branch:

```
Error running plan: 1 error(s) occurred:

* 1:3: unknown variable accessed: var.map.x in:

${var.map.x}
```

**Comment by joshuaspence** [comment] 2016-05-17 00:32
Changing `"${var.map.x}"` to `"${lookup(var.map, "x")}"` seems to work.

**Comment by apparentlymart** [comment] 2016-05-17 03:40
Hi @joshuaspence! Thanks for reporting this compatibility break.

I believe it's intended that in the new implementation you can use `var.map["x"]` since the expression system has first-class support for indexing.

Might be that we just want to document this compatibility break here, since I think we want to encourage moving to the indexing syntax.

**Comment by jen20** [comment] 2016-05-17 06:32
Hi @joshuaspence! This is an intended breakage - the `var.map.key` syntax for accessing maps was an unfortunate side effect of the way maps were implemented. The 0.7 "way" is to use indexing (`${var.map["key"]}`) or `lookup` as @apparentlymart says. The documentation for this has not been completely updated yet - I'm working on that prior to the first drop of the 0.7 RC series. I'm going to tag this as a "documentation" rather than "bug" since it is intended behaviour. Thanks for reporting!

**Comment by glasser** [comment] 2016-05-17 21:47
At the very least, it would be great to mention this in CHANGELOG.md in the BACKWARDS INCOMPATIBILITIES section!

**Comment by glasser** [comment] 2016-05-17 21:48
It also might be nice to change the "unknown variable accessed" message to, if it detects a missing variable of the form `var.x.y`, suggest the new syntax?

**Comment by jrnt30** [comment] 2016-05-18 14:46
Would it be worth while considering adding functionality to "fmt" or another sub-command that would allow for a migration of the syntax similar to how some resources manage differences between versions?  

I understand there are some complications with things like remotely referenced modules that may make this more difficult (i.e. a module that is trying to serve both 0.6 and 0.7 would have breaking syntax for one user or the other) but it would be nice to offer an easier upgrade path. 

I could attempt a quick hack at this but it would seem a more holistic solution of managing the "minimum" version of Terraform and ensuring the TF file meets that requirement would be a better long term solution.  I know there are several conversations around a "terraform" config block that is included in the TF itself which would seem to fit well here also.

**Comment by glasser** [comment] 2016-06-08 23:24
See #7086, though it would still be nice to improve the error message.

**Comment by jen20** [comment] 2016-06-09 10:19
Hi @jrnt30! As of 0.7 there is a check to ensure that state files are not used with older versions of Terraform. I agree that merging #7086 is a good idea though! I'm not sure offhand whether it's possible to improve the error message here without a great deal of reworking the interpolation system - I will investigate however.

**Comment by glasser** [comment] 2016-06-09 14:50
I would think you'd just find where the error is generated and see if the variable name has an extra dot in it?

**Comment by jrnt30** [comment] 2016-06-10 22:52
@jen20 Understood and thanks for the clarification.  My suggestion may have been a bit muddled.  What I was proposing was a "migration" feature to allow for a project to update breaking changes like this (even if the feature was initially a "mistake" a lot of are using it because it worked and seemed intuitive :) ) 

I was looking at the HCL project and was thinking it might be possible with a set of custom AST Walkers to provide different migration strategies, but that too would require a non-trivial amount of work.  

Just trying to brainstorm some ideas to mass update these cases in an easy to use manner for some of our projects (and client's projects).  Will probably give some nasty sed logic a look in the meantime

**Comment by phinze** [comment] 2016-08-02 20:59
The error message here is now spruced up 👍 

```
Error loading config: Error loading /tmp/err/main.tf: Error reading config for template_file[test]: Invalid dot index found: 'var.map.x'. Values in maps and lists can be referenced using square bracket indexing, like: 'var.mymap["key"]' or 'var.mylist[1]'. in:

${var.map.x}
```

**Closed by phinze** 2016-08-02 20:59 UTC
Labels: core, documentation

**Comment by chiefy** [comment] 2016-08-11 13:15
This still needs documentation, see-also: #7953
