### ISSUE TITLE
Inconsistent object types error is ambiguous

### ISSUE THREAD

**Issue by rpili1313** [hashicorp/terraform#26977] opened 2020-11-19 08:04 UTC
Hi,

I'm trying to build an expression but it fails with following error:

**The true and false result expressions must have consistent types. The given expressions are object and object, respectively.**

My code:

`variable "virtual_machine_extensions" {
  default = null
}`

`for_each = var.virtual_machine_extensions_data != null ? var.virtual_machine_extensions_data : {}`

When the variable is not used, everything works but if the variable has a value as:

```
virtual_machine_extensions = {
    extension02 = {
        name                          = "xxxxx"
        virtual_machine_key   = "xxxxx"
        publisher                    = "x.xxxx"
        type                             = "xxxx"
        type_handler_version  = "xxx"
        auto_upgrade_minor_version    = true
        settings                      = {
                                            "xxxxxx": "xxxxxx",
                                            "xxxxxxx": "xxxxxxx",
                                            "properties": { xxxxxxx}
                                              }
        protected_settings            = null
}
```   

It seems the settings part in the variable is the problem.

**Comment by jbardin** [comment] 2020-11-19 14:14
Hi @rpili1313 

Thanks filing the issue. The error here is correct that the types do not match, but the error text is unfortunately rather ambiguous. The summarized description of the types here does not make it clear how they differ, and we can probably improve that in cases like this. 

What you can do in this case is to define the correct type for the variable, to avoid it being inferred as a single `object` type. While it could be preferable to define all the fields precisely, you can test this out using the `type = map(any)` syntax, which will force the map type and still infer the type of the value it contains. You should be aware however, that using `map(any)` can make it easy to inadvertently assign incompatible types in other places, so defining the complete type should be don eventually.  If you have more usage questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks

**Comment by alisdair** [comment] 2021-02-23 18:25
Closing as duplicate of #23364.

**Closed by alisdair** 2021-02-23 18:25 UTC
Labels: config, enhancement
