### ISSUE TITLE
lookup() default boolean value always evaluates to false when using strings

### ISSUE THREAD

**Issue by dylanrhysscott** [hashicorp/terraform#18878] opened 2018-09-17 11:02 UTC
When using a lookup for a boolean value in a map the default always evaluates to false when using an explicit string of "0" or "1". However passing in a variable as a default boolean evaluates fine.

### Terraform Version
```
0.11.8
```

### Terraform Configuration Files

```
variable "ec2_instance" {
type = list
default =  [
    {
      name = "test-instance-1"
      ... # Omitted for brevity
    }
  ] 
}

variable "disable_api_termination" {
  type = "string"
  default = true
}

resource "aws_instance" "ec2_instance_bad" {
  ... # Omitted for brevity
  disable_api_termination = "${lookup(var.ec2_instance[count.index], "disable_api_termination", "1")}" # Always evaluates to false even though the default is true
  ...
}

resource "aws_instance" "ec2_instance_good" {
  ... # Omitted for brevity
  disable_api_termination = "${lookup(var.ec2_instance[count.index], "disable_api_termination", var.disable_api_termination)}" # Evaluates correctly as it is using a variable not relying on a string
  ...
}


```

### Crash Output
No crashes

### Expected Behavior
lookup() should evaluate a true value when the default is used

### Actual Behavior
lookup() always evaluates to false even though the default is true - Terraform appears to silently fail to coerce "1" to true with no errors so defaults to false

### Steps to Reproduce
Unfortunately I cannot provide full config files for this but it can be reproduced by creating an EC2 instance and attempting to lookup a boolean using the default parameter

### Additional Context
N/A

### References
N/A

**Comment by dylanrhysscott** [comment] 2018-09-17 11:06
This seems to also happen to integer values - Default values always evaluate to 0

**Comment by mildwonkey** [comment] 2018-09-19 20:46
hi @dylanrhysscott !
I'm sorry you've run across this unexpected behavior. It's a known limitation with the current versions of terraform, and it's stumped me more than once in the past!

The core team is hard at work on the next major release of terraform, [0.12](https://www.hashicorp.com/blog/terraform-0-1-2-preview), which included an enhanced type system that will greatly improve things. I expect that integers and booleans will "just work" the way you expect with that release. 

I'll label this issue so we can check on it after the 0.12 release and make sure there aren't any lingering oddities. Thanks!

**Comment by mildwonkey** [comment] 2019-06-25 14:42
Hello!
I am going to close this issue since most of the involved code paths have been re-written for terraform 0.12. 
I was able to confirm that the example code here evaluates correctly in terraform 0.12:

```
  # aws_instance.ec2_instance_bad[0] will be created
  + resource "aws_instance" "ec2_instance_bad" {
      + ami                          = "ami-1233454565432"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + disable_api_termination      = true
       ... etc
```

If you see any further problems, please open a new issue. Thanks!

**Closed by mildwonkey** 2019-06-25 14:42 UTC
Labels: bug, config
