### ISSUE TITLE
aws: Unexpected EOF during apply causes resource to be deleted from state file

### ISSUE THREAD

**Issue by veqryn** [hashicorp/terraform#9592] opened 2016-10-25 14:44 UTC
I recently downloaded v0.7.6 and ran apply against my terraform scripts, and it gave an EOF error and deleted the entire aws beanstalk block out of the statefile.  Subsequent runs attempted to create a new beanstalk environment.
I upgraded to v0.7.7 and still had the issue, it happens on every run.
I believe that v0.7.3 did not have this issue.
My aws beanstalk resource has not changed during the upgrade from v0.7.3 to v0.7.6

### Terraform Version
v0.7.6
v0.7.7

### Affected Resource(s)
aws_elastic_beanstalk_environment (only this one got deleted from my state file)
aws_sqs_queue
aws_db_subnet_group

### Terraform Configuration Files
https://gist.github.com/veqryn/b2baf6835d7e4791e135973b1e06c510

### Debug Output
```
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/25 08:31:53 [DEBUG] Elastic Beanstalk optionSettingValueHash(map[string]interface {}{"namespace":"aws:elasticbeanstalk:environment", "name":"ServiceRole", "value":"stage-elasticbeanstalk-service-role", "resource":""}): ServiceRole: hk=aws:elasticbeanstalk:environment:ServiceRole=stage-elasticbeanstalk-service-role,hc=2606590167
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/25 08:31:53 [DEBUG] Removing Beanstalk setting: (aws:elb:policies::ConnectionDrainingTimeout)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/25 08:31:53 [DEBUG] Removing Beanstalk setting: (aws:autoscaling:launchconfiguration::MonitoringInterval)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/25 08:31:53 [DEBUG] Removing Beanstalk setting: (aws:autoscaling:launchconfiguration::SSHSourceRestriction)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/25 08:31:53 [DEBUG] Removing Beanstalk setting: (aws:elb:loadbalancer::LoadBalancerHTTPSPort)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: panic:[31mError applying plan:
 runtime error: slice bounds out of range
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: goroutine 3416 [running]:
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: panic(0x2942c80, 0xc0420040a0)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/go/src/runtime/panic.go:500 +0x1af
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsElasticBeanstalkEnvironmentUpdate(0xc045a9cae0, 0x26a02c0, 0xc042327680, 0x0, 0x415858)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go:358 +0x734
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0460982a0, 0xc04665b220, 0xc0459c82a0, 0x26a02c0, 0xc042327680, 0x1, 0xc0447527e0, 0x18)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:168 +0x206
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc046296c00, 0xc0465e2040, 0xc04665b220, 0xc0459c82a0, 0x0, 0xe1105e, 0xc0445bc300)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:178 +0xa2
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc046036fa0, 0xc0450c4400, 0xc0459c7c10, 0x0, 0x0)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:460 +0x5e
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: reflect.Value.call(0xc042049560, 0xc04611ddb8, 0x13, 0x2f043d0, 0x4, 0xc045013ed0, 0x3, 0x3, 0xc04650c9c0, 0x0, ...)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/go/src/reflect/value.go:434 +0x5cf
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: reflect.Value.Call(0xc042049560, 0xc04611ddb8, 0x13, 0xc045013ed0, 0x3, 0x3, 0x0, 0xc04650c9c0, 0xc04650c960)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/go/src/reflect/value.go:302 +0xab
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: net/rpc.(*service).call(0xc0455f8cc0, 0xc0455f8c80, 0xc0455fe628, 0xc045744780, 0xc0455ef1c0, 0x26a2180, 0xc0450c4400, 0x16, 0x26a21c0, 0xc0459c7c10, ...)
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/go/src/net/rpc/server.go:383 +0x14f
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: created by net/rpc.(*Server).ServeCodec
2016/10/25 08:31:53 [DEBUG] plugin: terraform.exe: 	/opt/go/src/net/rpc/server.go:477 +0x428
2016/10/25 08:31:53 [DEBUG] root.beanstalk: eval: *terraform.EvalWriteState
2016/10/25 08:31:53 [DEBUG] root.beanstalk: eval: *terraform.EvalApplyProvisioners
2016/10/25 08:31:53 [DEBUG] root.beanstalk: eval: *terraform.EvalIf
2016/10/25 08:31:53 [DEBUG] root.beanstalk: eval: *terraform.EvalWriteState
2016/10/25 08:31:53 [DEBUG] root.beanstalk: eval: *terraform.EvalWriteDiff
2016/10/25 08:31:53 [DEBUG] root.beanstalk: eval: *terraform.EvalApplyPost
2016/10/25 08:31:53 [ERROR] root.beanstalk: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
2016/10/25 08:31:53 [ERROR] root.beanstalk: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
2016/10/25 08:31:53 [ERROR] root.beanstalk: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:
2016/10/25 08:31:53 [ERROR] root.beanstalk: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
2016/10/25 08:31:53 [TRACE] [walkApply] Exiting eval tree: aws_elastic_beanstalk_environment.beanstalk_env
2016/10/25 08:31:53 [DEBUG] vertex provider.module.beanstalk.aws (close), got dep: module.beanstalk.aws_elastic_beanstalk_environment.beanstalk_env
...
2016/10/25 08:31:53 [DEBUG] vertex root, got dep: module.servers.plan-destroy
2016/10/25 08:31:53 [TRACE] Preserving existing state lineage "6aae6a9a-2b57-436f-92c5-539834b678b4"
2016/10/25 08:31:53 [TRACE] Preserving existing state lineage "6aae6a9a-2b57-436f-92c5-539834b678b4"
2016/10/25 08:31:53 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc04336c6c0),
  Bucket: "ca-consumer-api-remote-data",
  ContentLength: 143236,
  ContentType: "application/json",
  Key: "infrastructure/terraform/stage/terraform.tfstate"
}
2016/10/25 08:31:53 [DEBUG] plugin: C:\Users\cduncan\programs\terraform\terraform.exe: plugin process exited
2016/10/25 08:31:54 [DEBUG] plugin: waiting for all plugin processes to complete...
2016/10/25 08:31:54 [DEBUG] plugin: C:\Users\cduncan\programs\terraform\terraform.exe: plugin process exited

```

### Expected Behavior
Should work and also not delete my resources.

### Actual Behavior
`terraform apply`
```
module.beanstalk.aws_elastic_beanstalk_environment.beanstalk_env: Modifying...
  setting.#:                    "56" => "57"
...
Error applying plan:

3 error(s) occurred:

* aws_sqs_queue.sqs_organizer_dead_letter: unexpected EOF
* aws_db_subnet_group.rds_subnet_group_organizer: unexpected EOF
* aws_elastic_beanstalk_environment.beanstalk_env: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Important Factoids
Every time I refresh or apply my terraform configs, terraform incorrectly shows that it needs to update beanstalk.
I was going to make a separate issue about it.
It has always been that way (from 0.6 onward), so I don't believe that it affects this bug.

**Comment by thomaschaaf** [comment] 2016-10-26 13:00
This is probably related to: https://github.com/hashicorp/terraform/issues/9259 and is fixed in the master

**Comment by jbardin** [comment] 2016-10-27 14:29
Yes, this looks like it's fixed on master.

@veqryn, I can reopen this if you still have a case that reproduces the error, but marking it as closed for now.

**Closed by jbardin** 2016-10-27 14:29 UTC
Labels: bug, provider/aws

**Comment by spanktar** [comment] 2016-10-27 18:47
Wondering if this affects other resources as well.  I'm experiencing the same problem with `aws_elasticache_replication_group`. Unexpected EOF error (on success) causes the state file to no longer have the resource. Filing a ticket specifically for this.

**Comment by veqryn** [comment] 2016-10-28 00:44
@spanktar 
@jbardin 
I think the fact that terraform is deleting stuff out of the state file is a `core` issue.
The particular errors in particular resources that lead it to do so are separate (ie: We should be able to get an EOF error or other error when applying a change, and just have that resource fail without being deleted from the state file).
