### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by alijnmerchant21** [hashicorp/terraform#27641] opened 2021-01-30 10:41 UTC
### Terraform Version

Terraform v0.14.5

### Terraform Configuration Files

main.tf

### Debug Output
Could not retrieve the list of available versions for provider
terraform-providers/docker: could not query provider registry for
registry.terraform.io/terraform-providers/docker: the request failed after 2
attempts, please try again later: Get
"https://registry.terraform.io/v1/providers/terraform-providers/docker/versions":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)

### Steps to Reproduce
Following this tutorial.
Error is thrown when running - terraform init
https://learn.hashicorp.com/tutorials/terraform/install-cli?in=terraform/aws-get-started

**Comment by mildwonkey** [comment] 2021-02-08 14:28
Hi @alijnmerchant21 , I'm sorry you ran into this issue!

I am unable to reproduce this locally. Is it still a problem for you? It is possible that there was a network or registry issue when you were trying this that has since been resolved.


```
terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of terraform-providers/docker...
- Installing terraform-providers/docker v2.7.2...
- Installed terraform-providers/docker v2.7.2 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.


Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/terraform-providers/docker:
- For users on Terraform 0.13 or greater, this provider has moved to
kreuzwerker/docker. Please update your source in required_providers.

Terraform has been successfully initialized!
```

**Comment by mildwonkey** [comment] 2021-02-17 17:48
This has been waiting awhile now, so I am going to close it. Please open a new issue if necessary, thanks!

**Closed by mildwonkey** 2021-02-17 17:48 UTC
Labels: bug, new, v0.14, waiting-response
