### ISSUE TITLE
Allow target flag to use wildcards

### ISSUE THREAD

**Issue by yissachar** [hashicorp/terraform#5427] opened 2016-03-02 19:28 UTC
Currently the target flag requires two pieces of information to run, e.g.

`-target=aws_route53_zone.main`

If I have multiple resources they can be passed in with multiple target flags:

`-target=aws_route53_zone.main -target=aws_route53_zone.other -target=aws_route53_zone.third`

However this can get tedious fast if there are many resources.

If wildcards are allowed things can be greatly simplified. For instance, the above could be shortened to:

`-target=aws_route53_zone.*`

**Comment by phinze** [comment] 2016-03-04 23:23
Yep it's a good idea - such a good idea we have it another issue! :smile: 

Closing as dupe of https://github.com/hashicorp/terraform/issues/2444

**Closed by phinze** 2016-03-04 23:23 UTC
Labels: core, enhancement
