### ISSUE TITLE
crashed when resource does not exist

### ISSUE THREAD

**Issue by vicfl** [hashicorp/terraform#12788] opened 2017-03-16 23:45 UTC
### Terraform Version
Terraform v0.9.0 (MacOs Sierra)

### Affected Resource(s)
When you try to reference a resource which is actually generated by a module and does not exist you get this crashed, however under 0.8.6 you can get the exact details about which resource has not been created. 

### Panic Output
```
goroutine 432 [running]:
github.com/hashicorp/terraform/config/module.(*Tree).Validate(0xc42039b180, 0xc42042f170, 0x8)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:358 +0xe65
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc420432360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/context.go:644 +0xd0
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc4200a70e0, 0xc4200b4630, 0x2, 0x2, 0x3, 0xc420130440, 0x2)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_local.go:82 +0x262
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc4200a70e0, 0x6ff44a0, 0xc420084260, 0xc4200b4630, 0xc4203abe30)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:57 +0x22f
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opPlan)-fm(0x6ff44a0, 0xc420084260, 0xc4200b4630, 0xc4203abe30)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:224 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc4200a70e0, 0xc42042eba0, 0xc42042eb90, 0x6ff44a0, 0xc420084260, 0xc4200b4630, 0xc4203abe30)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:246 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:247 +0x192
```

### Expected Behavior
Terraform should tell you which resource does not exist (or give you a hint such as in 0.8.6)

### Actual Behavior
Crashed

### Steps to Reproduce
execute terraform plan

**Comment by mitchellh** [comment] 2017-03-17 02:10
Do you have a reproduction example we can run? Using your basic description of "reference a resource which is actually generated by a module and does not exist" I was unable to reproduce this. I'm probably just missing something. :)

**Comment by vicfl** [comment] 2017-03-17 02:21
Sure, sorry about that I can't use same code but I was able to reproduce this issue on this small example:

example1.tf

```
resource "aws_instance" "web" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  security_groups = ["${module.my_security_groups.my_sg.id}"]

  tags {
    Name = "HelloWorld"
  }
}
```

output
```
panic: module not found in children: my_security_groups

goroutine 420 [running]:
github.com/hashicorp/terraform/config/module.(*Tree).Validate(0xc420018960, 0xc4204010b0, 0x8)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:358 +0xe65
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc4204826c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/context.go:644 +0xd0
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc42008eb40, 0xc420151b80, 0x2, 0x2, 0x3, 0xc420474a80, 0x2)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_local.go:82 +0x262
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc42008eb40, 0x6ff44a0, 0xc420012560, 0xc420151b80, 0xc420479710)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:57 +0x22f
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opPlan)-fm(0x6ff44a0, 0xc420012560, 0xc420151b80, 0xc420479710)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:224 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc42008eb40, 0xc420400ae0, 0xc420400ad0, 0x6ff44a0, 0xc420012560, 0xc420151b80, 0xc420479710)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:246 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:247 +0x192
```

**Comment by mitchellh** [comment] 2017-03-17 02:24
Got it reproduced. Thanks. Looks like our validation is failing when you reference a non-existent module!

**Comment by vicfl** [comment] 2017-03-17 02:27
no worries, sorry about my poor first description and I am glad you are able to reproduce it :). Just let me know if you need anything else.

**Comment by mitchellh** [comment] 2017-03-17 03:19
PR has the fix, will be released tomorrow.

**Comment by vicfl** [comment] 2017-03-17 03:24
Legend! thanks!

**Closed** 2017-03-17 06:33 UTC
Labels: bug, core
