### ISSUE TITLE
Changing the volume size on the root block device does not result in a detected change

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/terraform#2653] opened 2015-07-08 15:47 UTC
I have an EC2 instance with a 30 GB hard drive which is too small, so I added this to my `aws_instance`:

```
    root_block_device {
        volume_size = 80
    }
```

`terraform plan` reports no detected changes.

**Comment by catsby** [comment] 2015-07-08 19:58
Hey @jkodroff – thanks for writing in. This is intended behavior that is documented here:

- https://terraform.io/docs/providers/aws/r/instance.html

(see the note on `changes to *_block_device`)

To apply the changes, you need to explicitly taint the resource:

    $ terraform taint <aws_instance.instance_name>

For more background and rational, the behavior was introduced in https://github.com/hashicorp/terraform/pull/1445 .

I'm sorry for any trouble/hassle or otherwise confusion when running into this. I'm going to close the issue for now, feel free to follow up if you have other questions.

**Closed by catsby** 2015-07-08 19:58 UTC
