### ISSUE TITLE
upgrading to v0.15.4 results in crashes with segfault when running `terraform apply`

### ISSUE THREAD

**Issue by morsecodist** [hashicorp/terraform#28771] opened 2021-05-20 15:40 UTC
### Terraform Version

```
v0.15.4
```

### Terraform Configuration Files

My project is quite large and private and I have no idea which portion might be relevant.

### Debug Output

I don't want to risk uploading sensitive information.

### Crash Output
```
terraform apply
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbdf185]

goroutine 1240 [running]:
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).planDestroy(0xc00049ce00, 0x2cef4c0, 0xc000e9e2a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/terraform/node_resource_abstract_instance.go:402 +0x185
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc000b8d640, 0x2cef4c0, 0xc000e9e2a0, 0x40ac08, 0x27fd220, 0xc000d78c50)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:126 +0x538
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0xc000b8d640, 0x2cef4c0, 0xc000e9e2a0, 0x7febd59f8202, 0xc000d78ce8, 0x40bb05, 0x24a95e0)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0xb3
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000f468f0, 0x2cef4c0, 0xc000e9e2a0, 0x7febd59f82b0, 0xc000b8d640, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:129 +0xbf
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1(0x27fd220, 0xc000b8d640, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000a158c0, 0x27fd220, 0xc000b8d640, 0xc002418a00)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0x1246




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.551093595.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.551093595.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected Behavior

`terraform apply` would apply instead of crashing

### Actual Behavior

Terraform crashed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

I tried deleting any local terraform state and that did not help. Downgrading to `v0.15.3` worked. I am on Linux Mint.

**Comment by jbardin** [comment] 2021-05-20 15:51
Thanks @morsecodist! Duplicate of #28763

**Closed by jbardin** 2021-05-20 15:51 UTC
Labels: bug, new
