### ISSUE TITLE
Terraform crash when running vnet-peering module 

### ISSUE THREAD

**Issue by slabarca** [hashicorp/terraform#26068] opened 2020-09-01 01:21 UTC
### Terraform Version

```
...Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0
```

### Terraform Configuration Files

```terraform
main.tf
...# Multi\Same subscription peering

data "azurerm_virtual_network" "vnet1" {
  provider            = azurerm
  name                = var.vnet_names[0]
  resource_group_name = var.resource_group_names[0]
}
data "azurerm_virtual_network" "vnet2" {
  provider            = azurerm.dst
  name                = var.vnet_names[1]
  resource_group_name = var.resource_group_names[1]
}
resource "azurerm_virtual_network_peering" "peer_1" {
  name                         = var.vnet_peering_names[1]
  resource_group_name          = var.rg_name
  virtual_network_name         = data.azurerm_virtual_network.vnet1.name
  remote_virtual_network_id    = data.azurerm_virtual_network.vnet2.id
  allow_virtual_network_access = var.allow_virtual_network_access
  allow_forwarded_traffic      = var.allow_forwarded_traffic
  use_remote_gateways          = var.use_remote_gateways
}
resource "azurerm_virtual_network_peering" "peer_2" {
  provider                     = azurerm.dst
  name                         = var.vnet_peering_names[0]
  resource_group_name          = var.resource_group_names[1]
  virtual_network_name         = data.azurerm_virtual_network.vnet2.name
  remote_virtual_network_id    = data.azurerm_virtual_network.vnet1.id
  allow_virtual_network_access = var.allow_virtual_network_access
  allow_forwarded_traffic      = var.allow_forwarded_traffic
  allow_gateway_transit        = var.allow_gateway_transit
}

Variables.tf
variable "sp_service_key" {}
variable "dst_sp_service_key" {}
variable "vnet_peering_names" {
  type        = list
  description = "Name of the virtual network peerings to created in both virtual networks provided in list format."
}
variable "rg_name" {
  description = "Name of new resource group."
  type        = string
}
variable "vnet_names" {
  type        = list
  description = "Names of the both virtual networks peered provided in list format."
}
variable "resource_group_names" {
  type        = list
  description = "Names of both Resources groups of the respective virtual networks provided in list format"
}
variable "allow_cross_subscription_peering" {
  description = "Boolean flag indicating if the peering is done across different subscriptions. Need to provide both Subscription ID's if this is set to true. Defaults to false."
  default     = true
}
variable "allow_virtual_network_access" {
  description = "Allow communication between two vnets"
  type        = string
}
variable "allow_forwarded_traffic" {
  description = "allow forwarded traffic not originating from local vnet "
  type        = string
}
variable "use_remote_gateways" {
  description = "allow local peer to use remote peer gateway"
  default     = false
}
variable "allow_gateway_transit" {
  description = "allow remote peer to transit gateway"
  default     = false
}

```
### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
### Additional Context

No

**Comment by jbardin** [comment] 2020-09-01 16:16
Hi @slabarca,

Without the crash output it's hard to know what is going on. I'm guessing this is a duplicate of #26011, but if that's not the case, feel free to add the missing information and we can look into thus further.

**Closed by jbardin** 2020-09-01 16:16 UTC
Labels: bug, new
