### ISSUE TITLE
Terraform failing to error on imbalanced brackets

### ISSUE THREAD

**Issue by Jonty** [hashicorp/terraform#5372] opened 2016-02-29 16:20 UTC
If closing brackets are imbalanced terraform simply ignores everything up to the next closing bracket rather than throwing an error.

This terraform configuration will fail to parse EIP2 and will only create EIP1 - obviously if EIP2 already exists it will be destroyed instead. Note the lack of a closing bracket on EIP1:
````
resource "aws_eip" "EIP1" {
  count = "1"

resource "aws_eip" "EIP2" {
  count = "1"
}
````

**Expected behaviour:** Terraform throws a parse error due to imbalanced brackets.

**Actual behaviour:** Running `terraform graph` on this outputs the following:
````
digraph {
	compound = "true"
	newrank = "true"
	subgraph "root" {
		"[root] aws_eip.EIP1" [label = "aws_eip.EIP1", shape = "box"]
		"[root] provider.aws" [label = "provider.aws", shape = "diamond"]
		"[root] aws_eip.EIP1" -> "[root] provider.aws"
	}
}
````
Note that EIP2 is totally missing and no error has been thrown.

**Comment by keymon** [comment] 2016-02-29 17:03
This is other test case:

``` 
resource "aws_eip" "EIP1" { a { a { a { a { a {
            count = "1"

resource "aws_eip" "EIP2" {
      count = "1"
}
``` 

I think the issue is once you are in [Parser.objectType](https://github.com/hashicorp/hcl/blob/1c284ec98f4b398443cbabb0d9197f7f4cc0077c/hcl/parser/parser.go#L233), any `STRING LBRACE` will happily be processed.

**Comment by Jonty** [comment] 2016-03-01 11:57
My example should be fixed by bumping the [hcl dependency version](https://github.com/hashicorp/hcl/issues/88), however I suspect @keymon's wil not be.

**Comment by mitchellh** [comment] 2016-03-01 18:34
I verified both cases are fixed upstream: https://github.com/hashicorp/hcl/commit/71c7409f1abba841e528a80556ed2c67671744c3 (the other test case was earlier as @Jonty pointed).

We need to update the dependency.

**Comment by phinze** [comment] 2016-03-01 18:50
Alrighty - master should have this fixed now. Heading over to the changelog now to note the bugfix.

**Closed by phinze** 2016-03-01 18:50 UTC
Labels: bug, core

**Comment by Jonty** [comment] 2016-03-01 19:31
Fantastic - thanks @mitchellh, @phinze!
