### ISSUE TITLE
Unable to init basic project 

### ISSUE THREAD

**Issue by anastazya** [hashicorp/terraform#26828] opened 2020-11-05 18:19 UTC
Hey, i literally just downloaded terraform and wanted to run a simple test, but hit a stone wall. 
I'm getting this on "sudo terraform init" 

2020/11/05 20:15:28 [INFO] Terraform version: 0.13.5  
2020/11/05 20:15:28 [INFO] Go runtime version: go1.14.7
2020/11/05 20:15:28 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/11/05 20:15:28 [DEBUG] Attempting to open CLI config file: /var/root/.terraformrc
2020/11/05 20:15:28 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/05 20:15:28 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/05 20:15:28 [DEBUG] ignoring non-existing provider search directory /var/root/.terraform.d/plugins
2020/11/05 20:15:28 [DEBUG] ignoring non-existing provider search directory /var/root/Library/Application Support/io.terraform/plugins
2020/11/05 20:15:28 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/05 20:15:28 [INFO] CLI command args: []string{"init"}

Initializing the backend...
2020/11/05 20:15:28 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/11/05 20:15:28 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/11/05 20:15:28 [DEBUG] New state was assigned lineage "62a44efc-5bb4-8080-8619-b42245fc549a"
2020/11/05 20:15:28 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/11/05 20:15:28 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/11/05 20:15:28 [DEBUG] checking for provisioner in "."
2020/11/05 20:15:28 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/11/05 20:15:28 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2020/11/05 20:15:28 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/11/05 20:15:28 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/11/05 20:15:28 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/11/05 20:15:28 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/11/05 20:15:28 [TRACE] statemgr.Filesystem: read nil snapshot
2020/11/05 20:15:28 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins

2020/11/05 20:15:28 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins
Initializing provider plugins...
2020/11/05 20:15:28 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/11/05 20:15:28 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
- Finding latest version of terraform-providers/docker...
2020/11/05 20:15:31 [ERR] Checkpoint error: Get "https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=475579f9-f09d-257b-3378-835cb1f7144f&version=0.13.5": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
terraform-providers/docker: could not connect to registry.terraform.io: Failed
to request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": net/http: request
canceled while waiting for connection (Client.Timeout exceeded while awaiting
headers)

I just tried to follow the documentation here : https://learn.hashicorp.com/tutorials/terraform/install-cli

Docker is installed, running and tested ( i had many other tests with various images and i know how to use Docker )

Is it a problem, or i'm just too dumb ?

LE : 

One check later, and it's not my internet connection 

Q :
curl -k https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=475579f9-f09d-257b-3378-835cb1f7144f&version=0.13.5

A: 

[1] 1309
[2] 1310
[3] 1311

{"product":"terraform","current_version":"0.13.5","current_release":1603310232,"current_download_url":"https://releases.hashicorp.com/terraform/0.13.5/","current_changelog_url":"https://github.com/hashicorp/terraform/blob/v0.13.5/CHANGELOG.md","project_website":"https://www.terraform.io","alerts":[]}

**Comment by alisdair** [comment] 2020-11-05 20:19
Hi @anastazya, thanks for reporting this. Since it looks like you're running on macOS, I think this is a duplicate of #26532—the root cause being a DNS configuration problem. The linked issue has some suggestions for workarounds, but the real fix will be to update our macOS builds to change the CGO_ENABLED flag.

We're tracking that work on the other issue, so I'm closing this as a duplicate.

**Closed by alisdair** 2020-11-05 20:19 UTC
Labels: bug, new
