### ISSUE TITLE
Support local variables in terraform test files

### ISSUE THREAD

**Issue by alexharv074** [hashicorp/terraform#35242] opened 2024-05-26 01:41 UTC
### Terraform Version

```shell
1.8.4
```

### Use Cases

Given a large test case as the following:

```hcl
variables {
  account_id                  = "123456789012"
  db_name                     = "example_db"
  postgres_cf_stack_name      = "example_stack"
  secret_lambda_cf_stack_name = "example_stack"
}

run "test_locals__default_privileges" {
  command = plan

  variables {
    # Code is performing a Cartesian Product,
    # pairing all attributes in var.roles and 
    # then merging defaults.
    roles = [
      {
        name     = "admin_role",
        database = "production_db"
      },
      {
        name     = "user_role",
        database = "development_db"
      }
    ]
  }

  assert {
    condition = jsonencode(local.default_privileges) == jsonencode([
      {
        owner = "admin_role"
        role = {
          bypass_row_level_security = false
          connection_limit          = -1
          create_database           = false
          create_role               = false
          database                  = "production_db"
          database_privileges       = ["CONNECT", "CREATE", "TEMPORARY"]
          encrypted_password        = true
          inherit                   = true
          login                     = true
          name                      = "admin_role"
          password_rotation         = false
          replication               = false
          revoke_public             = false
          roles                     = null
          schema                    = "public"
          search_path               = null
          sequence_privileges       = ["USAGE", "SELECT", "UPDATE"]
          superuser                 = false
          table_privileges          = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
          valid_until               = "infinity"
          with_grant_option         = "false"
        }
      },
      {
        owner = "admin_role"
        role = {
          bypass_row_level_security = false
          connection_limit          = -1
          create_database           = false
          create_role               = false
          database                  = "development_db"
          database_privileges       = ["CONNECT", "CREATE", "TEMPORARY"]
          encrypted_password        = true
          inherit                   = true
          login                     = true
          name                      = "user_role"
          password_rotation         = false
          replication               = false
          revoke_public             = false
          roles                     = null
          schema                    = "public"
          search_path               = null
          sequence_privileges       = ["USAGE", "SELECT", "UPDATE"]
          superuser                 = false
          table_privileges          = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
          valid_until               = "infinity"
          with_grant_option         = "false"
        }
      },
      {
        owner = "user_role"
        role = {
          bypass_row_level_security = false
          connection_limit          = -1
          create_database           = false
          create_role               = false
          database                  = "production_db"
          database_privileges       = ["CONNECT", "CREATE", "TEMPORARY"]
          encrypted_password        = true
          inherit                   = true
          login                     = true
          name                      = "admin_role"
          password_rotation         = false
          replication               = false
          revoke_public             = false
          roles                     = null
          schema                    = "public"
          search_path               = null
          sequence_privileges       = ["USAGE", "SELECT", "UPDATE"]
          superuser                 = false
          table_privileges          = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
          valid_until               = "infinity"
          with_grant_option         = "false"
        }
      },
      {
        owner = "user_role"
        role = {
          bypass_row_level_security = false
          connection_limit          = -1
          create_database           = false
          create_role               = false
          database                  = "development_db"
          database_privileges       = ["CONNECT", "CREATE", "TEMPORARY"]
          encrypted_password        = true
          inherit                   = true
          login                     = true
          name                      = "user_role"
          password_rotation         = false
          replication               = false
          revoke_public             = false
          roles                     = null
          schema                    = "public"
          search_path               = null
          sequence_privileges       = ["USAGE", "SELECT", "UPDATE"]
          superuser                 = false
          table_privileges          = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
          valid_until               = "infinity"
          with_grant_option         = "false"
        }
      },
    ])
    error_message = "Expected a default_privileges to be a Cartesian product of var.roles."
  }
}
```

This code involves a lot of duplication and is sadly necessary in order to satisfy that the test illustrates what the code-under-test (not shown) is really doing. 

Normally I would then prefer to refactor out this duplication using something like a variable or a fixture but there seems to be currently no way to do this in `terraform test`.

### Attempted Solutions

I have tried this:

```hcl
variables {
  account_id                  = "123456789012"
  db_name                     = "example_db"
  postgres_cf_stack_name      = "example_stack"
  secret_lambda_cf_stack_name = "example_stack"
}

locals {
  base_role = {
    bypass_row_level_security = false

    connection_limit    = -1
    create_database     = false
    create_role         = false
    database_privileges = ["CONNECT", "CREATE", "TEMPORARY"]
    encrypted_password  = true
    inherit             = true
    login               = true
    password_rotation   = false
    replication         = false
    revoke_public       = false
    roles               = null
    schema              = "public"
    search_path         = null
    sequence_privileges = ["USAGE", "SELECT", "UPDATE"]
    superuser           = false
    table_privileges    = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
    valid_until         = "infinity"
    with_grant_option   = "false"
  }
}

run "test_locals__default_privileges" {
  command = plan

  variables {
    # Code is performing a Cartesian Product,
    # pairing all attributes in var.roles and 
    # then merging defaults.
    roles = [
      {
        name     = "admin_role",
        database = "production_db"
      },
      {
        name     = "user_role",
        database = "development_db"
      }
    ]
  }

  assert {
    condition = jsonencode(local.default_privileges) == jsonencode([
      {
        owner = "admin_role"
        role = merge(local.base_role, {
          database = "production_db"
          name     = "admin_role"
        })
      },
      {
        owner = "admin_role"
        role = merge(local.base_role, {
          database = "development_db"
          name     = "user_role"
        })
      },
      {
        owner = "user_role"
        role = merge(local.base_role, {
          database = "production_db"
          name     = "admin_role"
        })
      },
      {
        owner = "user_role"
        role = merge(local.base_role, {
          database = "development_db"
          name     = "user_role"
        })
      }
    ])
    error_message = "Expected a default_privileges to be a Cartesian product of var.roles."
  }
}
```

However, that leads to an error like:

```
│ Error: Unsupported block type
│ 
│   on tests/test_locals.tftest.hcl line xxx:
│  xxx: locals {
│ 
│ Blocks of type "locals" are not expected here.
╵
```

### Proposal

Support defining new local variables in terraform test.

### References

n/a

**Comment by liamcervante** [comment] 2024-05-27 09:36
Hi @alexharv074, I'm going to close this request as a duplicate of #34629.

However, I think in your use-case you can simply move your definition of `base_role` into the variables block and then refer to it directly in the assertions with `var.base_role` instead of `local.base_role`. Terraform test doesn't yet have a concept of "local variables" and "input variables" in the same way that regular Terraform does, instead it treats the existing `variables` block much more like regular Terraform already treats the `locals` block.

**Closed by liamcervante** 2024-05-27 09:36 UTC
Labels: enhancement, new

**Comment by alexharv074** [comment] 2024-05-27 11:15
Ah thank you @liamcervante ! I would have assumed that those vars could only override vars defined in the module but that does indeed work!
