### ISSUE TITLE
First deployment after upgrade to 0.13 produces "timeouts" error

### ISSUE THREAD

**Issue by Chanonry** [hashicorp/terraform#25887] opened 2020-08-17 18:54 UTC
### Terraform Version
```
Terraform v0.13.0
+ provider registry.terraform.io/-/aws v3.2.0
+ provider registry.terraform.io/-/null v2.1.2
+ provider registry.terraform.io/hashicorp/aws v3.2.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```

### Terraform Configuration Files
```
resource "aws_default_security_group" "default" {
  vpc_id = aws_default_vpc.default.id
  ingress {
    protocol  = -1
    self      = true
    from_port = 0
    to_port   = 0
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

```

### Debug Output

2020/08/17 19:24:35 [TRACE] eval: *terraform.EvalModuleCallArgument
2020/08/17 19:24:35 [ERROR] eval: *terraform.EvalOpFilter, err: Invalid resource instance data in state: Instance module.ecs-cluster.aws_default_security_group.default data could not be decoded from the state: unsupported attribute "timeouts".
2020/08/17 19:24:35 [ERROR] eval: *terraform.EvalSequence, err: Invalid resource instance data in state: Instance module.ecs-cluster.aws_default_security_group.default data could not be decoded from the state: unsupported attribute "timeouts".
2020/08/17 19:24:35 [TRACE] [walkValidate] Exiting eval tree: module.ecs-cluster.output.security-group-id
2020/08/17 19:24:35 [TRACE] eval: *terraform.EvalSequence
2020/08/17 19:24:35 [TRACE] vertex "module.ecs-cluster.output.security-group-id": visit complete

### Expected Behavior
No error for on resource already created under 0.12.

### Actual Behavior

Error: Invalid resource instance data in state

  on .terraform/modules/ecs-cluster/ecs/ecs-cluster.tf line 26:
  26: resource "aws_default_security_group" "default" {

Instance module.ecs-cluster.aws_default_security_group.default data could not
be decoded from the state: unsupported attribute "timeouts".

### Steps to Reproduce

terraform init -reconfigure  ( due to "failed to decode current backend config")
terraform get -update
terraform init
terraform plan -var-file dev.tfvars -out dev.plan

### Additional Context

Was running 0.12 but had one error with an unhelpful response. As part of debugging that error I upgraded to 0.13. Went through the 0.13upgrade stuff. Was forced to reconfigure the backend (hopefully not having lost state ?!) then got this error.

What's the timeouts all about?  Not declared or referenced in my module.

**Comment by jbardin** [comment] 2020-08-18 14:21
Hi @Chanonry,

Thanks for reporting the issue, this appears to be a duplicate of #25752.

**Closed by jbardin** 2020-08-18 14:21 UTC
Labels: bug, new
