### ISSUE TITLE
`known after apply` returned when using `for` with `can` and a map value is unknown

### ISSUE THREAD

**Issue by shoekstra** [hashicorp/terraform#34222] opened 2023-11-11 18:27 UTC
### Terraform Version

```shell
Terraform v1.6.3
on darwin_arm64
```

### Terraform Configuration Files

```terraform
variable "value" {
  type = string
}

locals {
  my = {
    something = {
      otherthing = {
        key = "key", value = var.value
      }
    }
  }

  result = {
    for k, v in local.my : k => v if can(v.otherthing)
  }
}
```

### Expected Behavior

Terraform should be able to produce value:

```hcl
{
  "something" = {
    "otherthing" = {
      "key" = "key"
      "value" = (known after apply)
    }
  }
}
```

### Actual Behavior

Terraform cannot produce value:

```hcl
(known after apply)
```

### Steps to Reproduce

Via console:

```terraform
> local.result
(known after apply)

> { for k, v in local.my : k => v if can(local.my[k].otherthing) }
(known after apply)

> { for k, v in local.my : k => v }
{
  "something" = {
    "otherthing" = {
      "key" = "key"
      "value" = (known after apply)
    }
  }
}
```

### References

This may be related or a duplicate of #31868 but my syntax is a bit different (and using `can`).

**Comment by shoekstra** [comment] 2023-11-11 18:37
Below is the error I get in my plan:

```
Error: Invalid for_each argument

...

The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys
that will identify the instances of this resource.

When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map
values.

Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to
fully converge.
```

I created this issue because the error mentions "Terraform cannot determine the full set of keys" but the keys are known, the example code above replicates the issue.

**Comment by jbardin** [comment] 2023-11-13 14:14
Hi @shoekstra,

Thanks for filing the issue. This indeed is a duplicate of https://github.com/hashicorp/terraform/issues/31868, `can` and `try` both use the same underling logic to check the result of their arguments. The language cannot ensure that an unknown result from `can` will always be successful, because further index or attribute access can't be checked until all intermediate values are known, so the result must be `unknown`. For example:

```
resource "terraform_data" "x" {
  input = "{}"
}

locals {
  something = {
    otherthing = jsondecode(terraform_data.x.output)
  }
}

output "result" {
  value = can(local.something.otherthing.nope)
}
```

Until `otherthing` is known, `can` can't determine if there will be a "nope" attribute in the resulting object.

**Closed by jbardin** 2023-11-13 14:14 UTC
Labels: bug, new
