### ISSUE TITLE
we can read all TF_state data via terraform_remote_state , not only outputs 

### ISSUE THREAD

**Issue by slawekgh** [hashicorp/terraform#25284] opened 2020-06-18 08:29 UTC
If using "terraform_remote_state" we can read only "output" section from terraform code 

but from curl level or Consul-WEB-UI level we can read all TF-state, even passwords and sensitive data 

This case is related of course to consul as a backend for tf-state , in consul there is only option to define policy for the whole key, not for the part part the key (part means for example only outputs section)

**Comment by apparentlymart** [comment] 2020-06-24 23:27
Hi @slawekgh,

Indeed, the statement you've made here is true: the terraform state includes information about all of the objects Terraform is managing, along with the root module outputs. Terraform state exists primarily to allow Terraform to detect differences on the next `terraform plan`, and its use with the `terraform_remote_state` data source is more of a convenient side-effect.

It's not clear from your message exactly what you are requesting here. If you're looking for a way to share data between different Terraform configurations that _doesn't_ imply sharing the entire state, then since you are using Consul already I would suggest that you use [the `consul_key_prefix` resource](https://www.terraform.io/docs/providers/consul/r/key_prefix.html) to write the data you intend to share explicitly into Consul from the producing configuration, and then use [the `consul_key_prefix` data source](https://www.terraform.io/docs/providers/consul/d/key_prefix.html) to read them back out in the consuming configuration. This is a more explicit way to share data between Terraform configurations, and also has the advantage that other parts of your system than Terraform can _also_ access the data Terraform wrote into Consul, such as applications configured using [consul-template](https://github.com/hashicorp/consul-template).

You can optionally also encapsulate how the data is read by writing a [data-only module](https://www.terraform.io/docs/modules/composition.html#data-only-modules): your consuming configurations can then use the shared module instead of the `consul_key_prefix` data source directly, and thus you can change where that data comes from in future if needed by updating the module.

**Comment by slawekgh** [comment] 2020-06-26 09:03
thanks! works great :

```
resource "consul_keys" "app" {
  token      = "xxx"

  key {
    path  = "consul/.../key" 
    value = join(", ", flatten(vra7_dep.ubuntu[*].resource_configuration.*.ip_address)[*])  
  }
}
```

and then separate consul policy and separate consul token

**Comment by jantman** [comment] 2020-11-16 19:52
I believe this issue can probably be considered a dupe of https://github.com/hashicorp/terraform/issues/18603

**Closed** 2024-08-28 16:51 UTC
Labels: enhancement, duplicate
