### ISSUE TITLE
Ugly provider error messages without context information

### ISSUE THREAD

**Issue by djakielskiadesso** [hashicorp/terraform#27444] opened 2021-01-08 10:52 UTC
Hey,

my problem is to find out the reason for some creepy error messeges wich seemingly produced by an provider while executing a terrafom plan. Without having context information, debugging gets very hard and you dont know the source of trubble. 

For example:
```
Error: dial tcp :0: connect: can't assign requested address
```
It could be helm, kubernetes, uptimerobot, nexus, aws or postgres provider. Even enabeling terraform debug log dosen't gets more information.

### Current Terraform Version
```
Terraform v0.13.6
+ provider registry.terraform.io/cyrilgdn/postgresql v1.7.2
+ provider registry.terraform.io/datadrivers/nexus v1.10.5
+ provider registry.terraform.io/devkoriel/keycloak v2.0.1
+ provider registry.terraform.io/hashicorp/aws v3.23.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/louy/uptimerobot v0.5.1
+ provider registry.terraform.io/taiidani/jenkins v0.6.0
```

### Use-cases
- Debugging ugly error messages generated by provider.
- Find breaking errors without debugging or try and error the hole code

### Attempted Solutions
Catch provider errors and exceptions to produce error messages with context information. 
```
An Error in provider xxxx: dial tcp :0: connect: can't assign requested address
{Terraform code stack trace}
on main.tf
  provider "xxxx" {
     connection_string="......"
  }

An Error on module.x.provider_resource.name: dial tcp :0: connect: can't assign requested address
{Terraform code stack trace}
on resource.tf
  resource "provider_resource" "name" {
     connection_string="......"
  }
```

**Comment by jbardin** [comment] 2021-01-08 13:23
Hi @djakielskiadesso,

Thanks for filing the issue. We have merged many changes to the handling of provider crashes and diagnostics since v0.13.6, but I'm not sure if that would cover the case you have here. Can you show an example of how you generated the this error? 

Thanks!

**Comment by djakielskiadesso** [comment] 2021-01-11 10:56
Hi @jbardin,

it's not so easy to find the source of trouble. If i found the reason, i will get you an code example.

But i found another exaple of the aws provider for resource aws_api_gateway_integration.
![Bildschirmfoto 2021-01-11 um 11 50 42](https://user-images.githubusercontent.com/52488859/104172035-e1829a80-5403-11eb-8288-dc4dcbc4cee0.png)
Wich resource mean or on wich line of code?
StackTrace?

**Comment by jbardin** [comment] 2021-01-11 17:39
Hi @djakielskiadesso, it would be great if you could provide a configuration which reproduces the error you see with the latest version of terraform. If the provider is panicking, then it should be handled much better in the current development release. If there is a recoverable error situation where we need to add more context, we need to see where that is happening exactly. 

Thanks!

**Comment by jbardin** [comment] 2021-04-01 20:01
Since we don't have a reproduction case here, I'm going to close this out.
The 0.15 release has numerous fixes around reporting errors in providers, and will hopefully remedy the situation.
If there is still a problem when using the latest release of terraform and providers, feel free to reply here with more information or file a new issue.

Thanks!

**Closed by jbardin** 2021-04-01 20:01 UTC
Labels: enhancement, v0.13, waiting for reproduction
