### ISSUE TITLE
Terraform plan always shows a need to recreate EC2 instance

### ISSUE THREAD

**Issue by wkoszek** [hashicorp/terraform#26370] opened 2020-09-24 21:40 UTC
### Terraform Version

```
infra/tf/prod]$ terraform version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v3.3.0
```

### Terraform Configuration Files

```terraform
terraform {
	backend "remote" {
		organization = "my_company"

		workspaces {
			name = "master"
		}
	}
}



provider "aws" {
	profile = "default"
	region  = "us-east-2"
}

resource "aws_key_pair" "ssh_key_wkoszek" {
	key_name   = "ssh_key_wkoszek"
	public_key = "ssh-rsa AAAAB3NzaC..... my key pair"
}


# Not used for simplicity
data "aws_ami" "ubuntu" {
	most_recent = true

	filter {
		name   = "name"
		values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
	}

	filter {
		name   = "virtualization-type"
		values = ["hvm"]
	}

	# Canonical
	owners = ["099720109477"]
}

## **************************************************** # KMS

resource "aws_kms_key" "company_kms_tf" {
	description             = "company_kms_tf"
}

## **************************************************** VPCS
resource "aws_vpc" "sm_vpc_prod" {			# VPC
	cidr_block       = "10.0.0.0/16"
	instance_tenancy = "default"
	tags = {
		Name = "sm_vpc_prod"
	}
	enable_dns_hostnames = true
}

resource "aws_main_route_table_association" "sm_vpc_prod_rta" {
	vpc_id         = aws_vpc.sm_vpc_prod.id
	route_table_id = aws_route_table.sm_prod_route_table.id
}

resource "aws_internet_gateway" "prod_vpc_igw" {	# IGW
	vpc_id = aws_vpc.sm_vpc_prod.id
	tags = {
		Name = "sm_vpc_prod"
	}

	depends_on = [
		aws_vpc.sm_vpc_prod,
	]
}

resource "aws_subnet" "sm_prod_subnet_az1" {		# SUBNET
	vpc_id                  = aws_vpc.sm_vpc_prod.id
	cidr_block              = "10.0.1.0/24"
	availability_zone = "us-east-2a"

	map_public_ip_on_launch = true

	tags = {
		Name = "sm_prod_subnet_az1"
	}
	depends_on = [
		aws_internet_gateway.prod_vpc_igw
	]
}

resource "aws_subnet" "sm_prod_subnet_az2" {		# SUBNET
	vpc_id                  = aws_vpc.sm_vpc_prod.id
	cidr_block              = "10.0.2.0/24"
	availability_zone = "us-east-2b"

	map_public_ip_on_launch = true

	tags = {
		Name = "sm_prod_subnet_az2"
	}
	depends_on = [
		aws_internet_gateway.prod_vpc_igw
	]
}

resource "aws_subnet" "sm_prod_subnet_az3" {		# SUBNET
	vpc_id                  = aws_vpc.sm_vpc_prod.id
	cidr_block              = "10.0.3.0/24"
	availability_zone = "us-east-2c"

	map_public_ip_on_launch = true

	tags = {
		Name = "sm_prod_subnet_az3"
	}
	depends_on = [
		aws_internet_gateway.prod_vpc_igw
	]
}

resource "aws_route_table" "sm_prod_route_table" {	# ROUTE TABLE
	vpc_id = aws_vpc.sm_vpc_prod.id

	route {
		cidr_block = "0.0.0.0/0"
		gateway_id = aws_internet_gateway.prod_vpc_igw.id
	}

	tags = {
		Name = "sm_prod_route_table"
	}

	depends_on = [
		aws_vpc.sm_vpc_prod,
		aws_internet_gateway.prod_vpc_igw,
	]
}

resource "aws_route_table_association" "sm_prod_rta1" {		# RT ASSOC
	subnet_id      = aws_subnet.sm_prod_subnet_az1.id
	route_table_id = aws_route_table.sm_prod_route_table.id
	depends_on = [
		aws_subnet.sm_prod_subnet_az1,
		aws_route_table.sm_prod_route_table,
	]
}

resource "aws_route_table_association" "sm_prod_rta2" {		# RT ASSOC
	subnet_id      = aws_subnet.sm_prod_subnet_az2.id
	route_table_id = aws_route_table.sm_prod_route_table.id
	depends_on = [
		aws_subnet.sm_prod_subnet_az2,
		aws_route_table.sm_prod_route_table,
	]
}

resource "aws_route_table_association" "sm_prod_rta3" {		# RT ASSOC
	subnet_id      = aws_subnet.sm_prod_subnet_az3.id
	route_table_id = aws_route_table.sm_prod_route_table.id
	depends_on = [
		aws_subnet.sm_prod_subnet_az3,
		aws_route_table.sm_prod_route_table,
	]
}

## **************************************************** INSTANCES

resource "aws_instance" "prod_server_sftp" {
	ami           = "ami-07efac79022b86107" # ubuntu 20.04 lts ssd
	instance_type = "t2.micro"
	subnet_id  = aws_subnet.sm_prod_subnet_az1.id

	root_block_device {
		encrypted = true
		kms_key_id = aws_kms_key.company_kms_tf.id

		volume_size = 20
	}

	tags = {
		Name = "prod_sftp"
	}

	key_name = "ssh_key_wkoszek"
}

resource "aws_eip_association" "prod_server_sftp_eip_assoc" {
	instance_id   = aws_instance.prod_server_sftp.id
	allocation_id = aws_eip.sftp_ip.id
}
```

There's another file that has IP definitions:

```
resource "aws_eip" "sftp_ip" {
  tags = {
    Name = "sftp_ip"
    madewith = "terraform"
  }
  vpc = true
}
```

And I tried `vpc = true` and `vpc = false` here.

### Debug Output

https://gist.githubusercontent.com/wkoszek/fb6da1078c81028bcb4c6dae0d9d5ea7/raw/33a2a266ae0848296dcd0324a484f913619e6970/tf_bug_1

btw, I encrypted it via:

```
keybase follow hashicorp
keybase pgp pull
keybase pgp encrypt  -i typescript hashicorp > tf_buf_1.txt
```

### Expected Behavior

When I run:

```
terraform plan
terraform apply
terraform plan
```
I'd expect 2nd "plan" won't have anything to do. However "plan" always shows that the EC2 instance needs to be recreated.

### Actual Behavior

Running "terraform plan" always shows EC2 must be recreated.

### Steps to Reproduce

```
terraform plan
terraform apply
terraform plan
terraform plan
terraform plan
terraform plan

```

**Comment by jbardin** [comment] 2020-09-25 12:48
Hi @wkoszek 

The plan output shows the change happening because `kms_key_id` is changing. In your config you are referencing the `aws_kms_key.company_kms_tf.id` when I believe you should be referencing the `.arn` or `.key_id`, which are the attributes referenced in the documentation. If this is intended to work with the `.id` attribute, I would suggest filing an issue with the AWS provider.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by jbardin** 2020-09-25 12:48 UTC
Labels: bug, new

**Comment by jbardin** [comment] 2020-09-25 21:20
Hi @wkoszek, normally we do, but that capability is not working at the moment. It would be more expedient to open an issue directly. 

Note that there's not much the provider itself can do here to indicate an error, as everything was working as designed. They may however be able to fix the inconsistency in the `aws_kms_key` `id` field so that it does not change unexpectedly like this when it is referenced inadvertently.
