### ISSUE TITLE
Bug: aws_iam_policy_document inconsistent plan output with other policy definition options

### ISSUE THREAD

**Issue by DaKaZ** [hashicorp/terraform#27282] opened 2020-12-14 23:38 UTC
Terraform is incorrectly updating an `aws_iam_policy` or `aws_iam_policy_role` resource when the resource is built using a `aws_iam_policy_document` data source that includes a reference to a managed resource WHEN the managed resource is update.  This does NOT happy when the policy is defined inline OR the policy references a data source instead of a managed resource.

As can be seen in the Steps to Reproduce below, if you define the policy any way OTHER than by using the `aws_iam_policy_document` the behavior is consistent, I believe the behavior should be consistent for every case.

### Terraform Version

I have tested with v0.12.29, 0.13.5 and v0.14.2
```
% terraform --version
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.21.0
```

### Terraform Configuration Files

```terraform
resource "aws_dynamodb_table" "test" {
  name           = "TestTable"
  billing_mode   = "PROVISIONED"
  read_capacity  = 1
  write_capacity = 1
  hash_key       = "pk"
  range_key      = "sk"

  attribute {
    name = "pk"
    type = "S"
  }

  attribute {
    name = "sk"
    type = "S"
  }

  global_secondary_index {
    name               = "TestTableGSI"
    hash_key           = "sk"
    range_key          = "pk"
    write_capacity     = 2
    read_capacity      = 1
    projection_type    = "ALL"
  }
}

data aws_iam_policy_document dyanmo_lambda_role {
  version = "2012-10-17"
  statement {
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
    actions = [
      "sts:AssumeRole"
    ]
  }
}

resource aws_iam_role test_role {
  name = "test-role-for-cj"
  assume_role_policy = data.aws_iam_policy_document.dyanmo_lambda_role.json
}

# This fails on update:
#
data aws_iam_policy_document test_policy_doc {
  version = "2012-10-17"
  statement {
    effect = "Allow"
    actions = [ "dynamodb:*" ]
    resources = [
      aws_dynamodb_table.test.arn,
      "${aws_dynamodb_table.test.arn}/index/TestTableGSI"
    ]
  }
}

resource aws_iam_role_policy test_policy {
  name = "s3-test-policy"
  role = aws_iam_role.test_role.id
  policy = data.aws_iam_policy_document.test_policy_doc.json
}
```

### Debug Output

Debug output is not necessary 

### Crash Output

There is no crash

### Expected Behavior

The aws_iam_policy should not change when an update to a referenced resource is made

### Actual Behavior

Terraform shows the policy as being updated in place and shows the policy as `known after update`:
```
  # aws_iam_role_policy.test_policy will be updated in-place
  ~ resource "aws_iam_role_policy" "test_policy" {
        id     = "test-role-for-cj:s3-test-policy"
        name   = "s3-test-policy"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "dynamodb:*"
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws:dynamodb:us-west-2:<redacted>:table/TestTable/index/TestTableGSI",
                          - "arn:aws:dynamodb:us-west-2:<redacted>:table/TestTable",
                        ]
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }
```

### Steps to Reproduce

1. Create the resources for this terraform file using `terraform apply` for configuration shown above:
2. Change the `read_capacity_units` for the GSI on the dynamodb table from 1 to 2
3. Run `terraform plan` and note that the IAM policy doc is being updated and that we don't know that the doc will look like.

---

Now, if you replace the section AFTER the comment `This fails on update:` with EITHER of these to three options, the policy is NOT updated (which is the correct and expected behavior):

Option 1:
```
data aws_dynamodb_table selected_table {
  name = "TestTable"
}

data aws_iam_policy_document test_policy_doc {
  version = "2012-10-17"
  statement {
    effect = "Allow"
    actions = [ "dynamodb:*" ]
    resources = [
      data.aws_dynamodb_table.selected_table.arn,
      "${data.aws_dynamodb_table.selected_table.arn}/index/TestTableGSI"
    ]
  }
}

resource aws_iam_role_policy test_policy {
  name = "s3-test-policy"
  role = aws_iam_role.test_role.id
  policy = data.aws_iam_policy_document.test_policy_doc.json
}
```

Option 2:
```
resource aws_iam_role_policy test_policy {
  name = "s3-test-policy"
  role = aws_iam_role.test_role.id
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",      
      "Action": "dynamodb:*",      
      "Resource": [        
        "${aws_dynamodb_table.test.arn}/index/TestTableGSI",        
        "${aws_dynamodb_table.test.arn}"      
      ]    
    }  
  ]
}
POLICY
}
```

Option 3:
```
resource aws_iam_role_policy test_policy {
  name = "s3-test-policy"
  role = aws_iam_role.test_role.id
  policy = jsonencode({
    version = "2012-10-17"
    statement = [{
      effect = "Allow"
      actions = [ "dynamodb:*" ]
      resources = [
        aws_dynamodb_table.test.arn,
        "${aws_dynamodb_table.test.arn}/index/TestTableGSI"
      ]
    }]
  })
}
```

### Additional Context

None

### References

None

**Comment by apparentlymart** [comment] 2020-12-15 00:10
Hi @DaKaZ!

I understand that you are seeing some different behaviors depending on how you structure the configuration, but it isn't clear to me _why_ the others should be different because the plan output you included in your writeup seems like the correct behavior here: the provider has indicated that the ARN isn't known yet, and so consequently any policy document that includes the ARN must be unknown too.

Your "option 1" is different because you've asked Terraform to _do_ something different: rather than create a DynamoDB table and then use its ARN, you've told Terraform to assume that a DynamoDB table _already exists_ and go read its ARN. That would presumably fail if the table didn't already exist, but indeed it can work for you when it _does_ already exist because you've not told Terraform that there's a relationship between that data resource and `aws_dynamodb_table.test`.

I would expect options 2 and 3 to behave in a similar way to what you initially tried, because they too include an ARN that isn't yet known into a policy document. If you're seeing those succeed then I'd be interested to see the full plan output for those two cases, to understand how Terraform is predicting the ARN in those situations.

The root cause for these behaviors of unknown policy is that the AWS provider is written to mark the `arn` attribute as unknown until the table has been created. Based on the example table ARNs shown in your plan output it does seem like the ARN format is systematic and so in principle the AWS provider could predict its final value during planning (by concatenating your AWS account id and the table name with some constant string parts). However, that's a change that would need to happen in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws) rather than here, and the AWS provider team may well have a good reason for the current behavior that I'm not aware of due to my unfamiliarity with the DynamoDB API. If there isn't already an issue about this then you could perhaps open one to discuss the possibility, if you like.

**Comment by DaKaZ** [comment] 2020-12-15 14:57
Hi @apparentlymart,

Thank you for the extremely prompt and thorough reply.  Unfortunately I must have done a bad job at articulating the issue.  The issue is not at resource CREATE time (I fully understand and expect the policy to be unknown until after apply), the issue is with the behavior when we later UPDATE the referenced resource.

You see, the behavior is different when we define the policy using `data aws_iam_policy_document` with a reference to the managed resource (the dynamo table in this case) versus defining the policy inline.  Changing the RCUs on the table (or any attribute that does not recreate the table) has no effect on the ARN, and our expected output should aways be:
```
Terraform will perform the following actions:

  # aws_dynamodb_table.test will be updated in-place
  ~ resource "aws_dynamodb_table" "test" {
        id             = "TestTable"
        name           = "TestTable"
        tags           = {}
        # (7 unchanged attributes hidden)


      - global_secondary_index {
          - hash_key           = "sk" -> null
          - name               = "TestTableGSI" -> null
          - non_key_attributes = [] -> null
          - projection_type    = "ALL" -> null
          - range_key          = "pk" -> null
          - read_capacity      = 1 -> null
          - write_capacity     = 1 -> null
        }
      + global_secondary_index {
          + hash_key           = "sk"
          + name               = "TestTableGSI"
          + non_key_attributes = []
          + projection_type    = "ALL"
          + range_key          = "pk"
          + read_capacity      = 1
          + write_capacity     = 2
        }


        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
This expected output can be seen in all 3 options but NOT in the original configuration using `aws_iam_policy_document` with a direct reference to the dynamodb table.  This tells me there is likely something wrong with how the references are evaluated in `aws_iam_policy_document` versus the other approaches that it incorrectly thinks the policy is being updated. 

So again, the steps to reproduce are:
1. Create all the resources
2. Update something on the referenced resource (I choose to change the RCUs in this example)
3. Run `terraform plan`

In all cases, if the referenced resource is only updated and the ARN has not changed, I believe we should NOT see the IAM policy updated.  The expected output should be what I show above (only one change to the dynamo table)

**Comment by jbardin** [comment] 2020-12-15 15:43
Hi @DaKaZ,

If I understand your reply correctly, and the original configuration with the `aws_iam_policy_document.test_policy_doc` data source is causing unexpected changes, which looks like another case of the behavior described in #27171. You can test this out by indirectly referencing `aws_dynamodb_table.test.arn` from `data.aws_iam_policy_document.test_policy_doc` through a local value, something like:

```
locals {
  aws_dynamodb_table_test = aws_dynamodb_table.test.arn
}

data aws_iam_policy_document test_policy_doc {
  version = "2012-10-17"
  statement {
    effect = "Allow"
    actions = [ "dynamodb:*" ]
    resources = [
      local.aws_dynamodb_table_test,
      "${aws_dynamodb_table.test.arn}/index/TestTableGSI"
    ]
  }
}
```

**Comment by DaKaZ** [comment] 2020-12-15 20:22
@jbardin i think you are correct, what you describe as:

> What happens now is referencing a managed resource from a data source creates an implied depends_on dependency, so that any change in the referenced resource forces the data source to be deferred until apply. Because this is treated like depends_on, it means it should act only on a direct reference to another managed resource. What this also means is that you can work around the behavior by making the reference indirectly.

is exactly what I am seeing.  Thanks for suggestion on the local, I'll add that as `option 4` to our work arounds 😂

**Comment by jbardin** [comment] 2020-12-17 17:59
Thanks @DaKaZ! Since this is a known behavior rather than a bug (and documented in the linked issue as well), I'll close the issue for now.

**Closed by jbardin** 2020-12-17 17:59 UTC
Labels: bug, new
