### ISSUE TITLE
Add support for DynamoDB TTL

### ISSUE THREAD

**Issue by danthegoodman** [hashicorp/terraform#12530] opened 2017-03-08 16:30 UTC
AWS recently announced the ability to set a TTL on items in a DynamoDB. It requires an additional property to be set for the dynamo table, which I'd like to control via Terraform.

### Affected Resource(s)
- `aws_dynamodb_table`

### References
https://aws.amazon.com/about-aws/whats-new/2017/02/amazon-dynamodb-now-supports-automatic-item-expiration-with-time-to-live-ttl/

**Comment by glasser** [comment] 2017-03-08 20:28
Yeah, I'd use this too.

I guess we'd add a time_to_live_attribute string which names the attribute to use for this? And would we want to have every Read call invoke DescribeTimeToLive even if time_to_live_attribute isn't set, in order to turn it off if it's there?

**Comment by TenOs** [comment] 2017-03-14 19:05
+1

**Comment by rog555** [comment] 2017-03-17 10:32
+1

**Comment by umeat** [comment] 2017-03-20 02:37
+1

**Comment by roylines** [comment] 2017-03-28 06:37
+1

**Comment by apparentlymart** [comment] 2017-04-04 00:48
Hi @danthegoodman! Thanks for this feature request.

@glasser, your characterization of the implementation approach feels write to me. Based on a quick skim of the API docs for this, I think the right mapping would be a new `ttl` block in the resource which mirrors the structure of [`TimeToLiveSpecification`](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TimeToLiveSpecification.html):

```hcl
ttl {
  attribute_name = "foo"
  enabled = true
}
```

As @glasser noted, it would be important to call [`DescribeTimeToLive`](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeTimeToLive.html) during `Read` in order to update Terraform's state to match the real resource. Additionally, it looks like changes to the TTL config apply asynchronously so to preserve Terraform's expected behavior (resource changes aren't complete until they are confirmed committed to the real API) it will be necessary for `Update` to poll `DescribeTimeToLive` until `TimeToLiveStatus` settles on either "ENABLED" or "DISABLED" (depending on what direction we're moving in).

The Terraform team isn't likely to work on this in the near future, but if someone had the time and motivation to write a pull request for it we'd be happy to review it.

**Comment by marksailes** [comment] 2017-04-07 13:09
+1

**Comment by joshdurbin** [comment] 2017-04-11 23:02
+1

**Comment by joncarter51** [comment] 2017-04-19 15:18
+1

**Comment by radeksimko** [comment] 2017-05-14 15:45
Merged and released in `0.9.5`:
https://github.com/hashicorp/terraform/pull/14104

**Closed by radeksimko** 2017-05-14 15:45 UTC
Labels: enhancement, provider/aws
