### ISSUE TITLE
compact() function not behaving as expected

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#34636] opened 2024-02-08 12:13 UTC
### Terraform Version

```shell
Terraform v1.7.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.35.0
```

### Terraform Configuration Files

I am creating two AWS target groups that will be attached to an AWS autoscaling group.

I create a target group and then attach to the ASG something like this:

```
target_group_arns = [
  aws_lb_target_group.alb_target_group01.arn
]
```

Later I create a new target group and alter my code like this:

```
target_group_arns = [
  aws_lb_target_group.alb_target_group01.arn,
  aws_lb_target_group.alb_target_group02.arn,
]
```

and it works fine in the first apply.

However, if remove my second target group and remove it from the list above and apply, so I get back to just one target group.  

And then I add the target group back again and alter my list like this:

```
  target_group_arns = compact([
    aws_lb_target_group.alb_target_group01.arn,
    aws_lb_target_group.alb_target_group02.arn,
  ])
```
The the first apply creates the second target group but the list does not seem to recognize a new target group is in place.  I need to run a second apply.

It seems the ```compact()``` function somehow makes terraform not update the list with the second target group on a first apply.

### Debug Output

N/A

### Expected Behavior

```compact()``` function should work as expected.

### Actual Behavior

```compact()``` function acting strange.

### Steps to Reproduce

```terraform apply```

### Additional Context

N/A

### References

N/A

**Comment by heldersepu** [comment] 2024-02-08 14:22
From the documentation:
> `compact` takes a list of strings and returns a new list with any null or empty string elements removed.
https://developer.hashicorp.com/terraform/language/functions/compact

Why will you apply compact there?
if one of the items in the list was null or empty that will explain the described behavior

**Comment by scott-doyland-burrows** [comment] 2024-02-08 15:12
> From the documentation:
> 
> > `compact` takes a list of strings and returns a new list with any null or empty string elements removed.
> > https://developer.hashicorp.com/terraform/language/functions/compact
> 
> Why will you use `compact` there? if one of the items in the list was null or empty that will explain the described behavior

The code was simplified to show the issue.  My actual code does some conditionals to work out which target groups we are passing to the autoscaling group and it uses ```compact()``` to help with that, and I noticed this didn't work as expected.

I realised the issue was with ```compact()```.

In the simplified code I am passing in two items both of which have a value as obviously it is derived from a terraform resource earlier in the apply.  But it having an issue as I described.

**Comment by jbardin** [comment] 2024-02-08 16:13
Hi @scott-doyland-burrows,

The difference here is that because the `aws_lb_target_group.alb_target_group02.arn` to be created is not yet known, the result of `compact` cannot be known. So in the first case you are sending a list with a single arn plus an unknown value, while in the second you are sending an entirely unknown value.

Now that in and of itself should not require applying twice, so I think what you are seeing is a bug with the provider primarily caused by the legacy SDK. That field is likely optiona+computed, and being mishandled when there are no values to compare in the set.

**Comment by scott-doyland-burrows** [comment] 2024-02-08 17:29
Thanks for the reply.

The actual live code looks like this:

```
target_group_arns = compact([
  module.alb.default_target_group_arn,
  aws_lb_target_group.alb_target_group.arn,
  var.s2s_vpn != null ? join("", module.alb_internal.*.default_target_group_arn) : ""
])
```

So sometimes we need to attach that third target group that has the conditional, and sometimes not (depending on whether that target group is created).

I inherited the code, but I can see the reasoning for the ```compact``` was to remove the ```""``` so we didn't try to attach a target group named ```""``` to the autoscaling group.  

But we it does't really work as intended I can remove the ```compact``` because terraform actually is happy to attach a target group named ```""``` to the autoscaling group, which makes the plan/apply look odd, but has no actual effect on AWS.

And is maybe a better solution than two applies.

**Comment by jbardin** [comment] 2024-02-08 17:44
The fact that `""` works is probably also an indicator this is a problem with the legacy SDK, which had no way to differentiate between empty and unset values. I'm not sure what the logic of the `join` function is supposed to be, as  would assume concatenating multiple arn's does not result in a valid value.

Since this does not appear to be a bug in the Terraform CLI, I'm going to close the issue for now. If you want to follow up with the provider, there are probably related issues already open, but not likely to be fully remedied until the resource is migrated from the legacy SDK.

Thanks!

**Closed by jbardin** 2024-02-08 17:44 UTC
Labels: bug, new
