### ISSUE TITLE
provider/cloudflare - terraform deduces hashicorp/cloudflare for a community provider even with an explicit source directive

### ISSUE THREAD

**Issue by beaudryj** [hashicorp/terraform#31905] opened 2022-09-29 16:20 UTC
### Terraform Version

```shell
terraform version
Terraform v1.3.1
on darwin_arm64
```

### Terraform Configuration Files

```terraform
terraform {
    required_version = ">= 0.14.0"

    backend "remote" {
        // Backend configuration
    }

    required_providers {
        cloudflare = {
            source = "registry.terraform.io/cloudflare/cloudflare"
            version = "2.18.0"
        }

        aws = {
            source = "hashicorp/aws"
            version = "3.26.0"
        }
    }
}

provider "aws" {
    region = "us-east-2"
    access_key = var.aws_access_key_id
    secret_key = var.aws_secret_access_key
}

provider "cloudflare" {
    api_token = var.cloudflare_api_token
}
```

### Debug Output

--

### Expected Behavior

Terraform apply and plan steps should not result in an error.

### Actual Behavior

On running terraform init without the cloudflare data source, the initialization/plan succeed. However, when the data block is added, I am greeted with the following:

```
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Finding latest version of hashicorp/cloudflare...
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/tls from the dependency lock file
- Reusing previous version of cloudflare/cloudflare from the dependency lock file
- Installing cloudflare/cloudflare v2.18.0...
- Installed cloudflare/cloudflare v2.18.0 (signed by a HashiCorp partner, key ID DE413CEC881C3283)
- Installing hashicorp/aws v3.26.0...
- Installed hashicorp/aws v3.26.0 (signed by HashiCorp)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
- Installing hashicorp/tls v3.0.0...
- Installed hashicorp/tls v3.0.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/cloudflare: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/cloudflare

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

Did you intend to use cloudflare/cloudflare? If so, you must specify that
source address in each module which requires that provider. To see which
modules are currently depending on hashicorp/cloudflare, run the following
command:
    terraform providers
```

### Steps to Reproduce

Copy and paste the configuration file and run terraform plan or terraform init.

### References

https://github.com/hashicorp/terraform/issues/27701

**Comment by beaudryj** [comment] 2022-09-29 16:20
This is literally the Same Scenario as - https://github.com/hashicorp/terraform/issues/27701 the provider resolution or pass to the child module was broken between Terraform - 1.2.X and 1.3.X

**Comment by beaudryj** [comment] 2022-09-29 16:25
![image](https://user-images.githubusercontent.com/2633564/193086085-ededee12-e676-41c5-b32d-8fdfb8f97945.png)
![image](https://user-images.githubusercontent.com/2633564/193086490-667a7c54-a472-405e-98a3-d1daa840fbc2.png)

**Comment by beaudryj** [comment] 2022-09-29 16:25
![Screen Shot 2022-09-29 at 12 22 22 PM](https://user-images.githubusercontent.com/2633564/193086594-6da68e1c-3bf5-4862-b4f6-fbfffeaf1d1e.png)
![Screen Shot 2022-09-29 at 12 24 46 PM](https://user-images.githubusercontent.com/2633564/193086600-15d192d4-2908-4bbe-a21b-a73451c6fb82.png)

**Comment by jbardin** [comment] 2022-09-29 17:08
Hi @beaudryj,

The most common cause of this issue is a nested module which is missing the `cloudflare` provider in its `required_providers`. Can you show the output of `terraform providers`?

**Comment by beaudryj** [comment] 2022-09-29 17:09
https://github.com/hashicorp/terraform/issues/27701

**Comment by beaudryj** [comment] 2022-09-29 17:09
![image](https://user-images.githubusercontent.com/2633564/193095343-f007740f-4253-49e2-a76c-4476d64e8bf5.png)

**Comment by beaudryj** [comment] 2022-09-29 17:10
they are showing as correct yet on a plan its clearly trying to reference hashicorp/cloudflare which does not actually exist 
but terraform init successfully pulls down cloudflare/cloudflare

**Comment by apparentlymart** [comment] 2022-09-29 17:23
Hi @beaudryj!

In your original message you mention adding a data resource, but there isn't a `data` block in the configuration example you shared. Can you also share the configuration for that `data` block, and let us know which of your modules you added it to? My goal here is to find a suitable subset of your configuration that will allow us to observe the same problem on our own systems so we can debug it. Thanks!

**Comment by beaudryj** [comment] 2022-09-29 17:37
My Code is obviously more complex than this, but this is a rough sample

Root Module: 

```
module "bifrost" {
  source                = "./mymodulesource"
  domain.             = var.domain
  providers = {
    cloudflare = cloudflare
  }
}

variable "domain" {
  type = example.com
}

# Cloudflare
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}
```


Module
```
data "cloudflare_zone" "domain" {
  name = var.domain
}

variable "domain" {
  type = example.com
}

# Cloudflare
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}
```

**Comment by apparentlymart** [comment] 2022-09-29 17:59
Thanks for that example, @beaudryj.

There were some errors in the example but I was able to see what you meant and correct them myself. Here's the configuration I tried with:

```hcl
# Root module

module "bifrost" {
  source = "./mymodulesource"
  domain = var.domain
  providers = {
    cloudflare = cloudflare
  }
}

variable "domain" {
  type = string
}

# Cloudflare
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}
```

```hcl
# Child module

data "cloudflare_zone" "domain" {
  name = var.domain
}

variable "domain" {
  type = string
}

# Cloudflare
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}
```

Unfortunately when I try this with `terraform init` I get the behavior you expected:

```
$ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding cloudflare/cloudflare versions matching "~> 3.0"...
- Installing cloudflare/cloudflare v3.24.0...
- Installed cloudflare/cloudflare v3.24.0 (signed by a HashiCorp partner, key ID DE413CEC881C3283)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

```
$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/cloudflare/cloudflare] ~> 3.0
└── module.bifrost
    └── provider[registry.terraform.io/cloudflare/cloudflare] ~> 3.0
```

```
$ cat .terraform.lock.hcl 
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/cloudflare/cloudflare" {
  version     = "3.24.0"
  constraints = "~> 3.0"
  hashes = [
    "h1:r5Gq0/YygOE9EHmvKs1ir/d4zyIfPTNfIPFMy2M7UNA=",
    "zh:190408c7f17a4bcb6eef4faaf3cbcd7bc71ffe2da0bae53bf198267b386e1eca",
    "zh:2a17671e6d567c488c4b748a318ff3a49ce5a395b2a850ce18327ac110f24ca4",
    "zh:2d00a73e3baa3c620d10cdc448c04210c11d3dbdfc7b327d225cb9e37c760d65",
    "zh:328238bb6541b7373ffb499826def6a5105a23f4362d275aea08f4be18a5456b",
    "zh:360c01f73fb1aae93021957fcd384cda7f675d77918ff29563644d2cced5537c",
    "zh:4a8a8b81429d25c8480fac90bae06132b0be3d506941b14cbc383ce71a66e7b5",
    "zh:62991a8f5eab1d30ffdfe2ef440cda200230ca39338df478ef26f1da7ea7b13b",
    "zh:7c8b54bebd905cdc995a77665f7ea2fe9a416446c78a7630b79c66eb4285ae61",
    "zh:8ba7d300a3a01d71ff932674b8669ce4c06ca6e6b1ad4bc6814decde0885292c",
    "zh:95277d0edd3caab4ba47becf6aecbc27df25df6f3a630972efa4626d38fa570f",
    "zh:cef1d2f45d731e60fca9bf42eafdc4a3e78954882c4d1f26f8e4bf985db854ce",
    "zh:e9724344b49945fcbb87f336c958c0fbb00fe524c1cb59545417f81a442b43d9",
    "zh:ed314269d7e343c84433d285f6865191441b706a35ee2083f4d1f454aa33d06f",
    "zh:feaa86c9f0101ae10eb7491f262ed85e9d7a235763faec6e143a5563747dd4af",
  ]
}
```

This configuration therefore unfortunately seems to lack whatever is causing the problem on your system.

Can you try reproducing with the same configuration I shared above, and confirm whether it also works for you? If it _does_ work, can you try gradually adding more parts of your real configuration to it until you're able to see it fail in the way you originally described?

Thanks!

**Comment by beaudryj** [comment] 2022-09-29 18:10
@apparentlymart the issue is not with the init, it is with a plan

**Comment by beaudryj** [comment] 2022-09-29 18:26
interestingly... we rolled back terraform on the version of our runners to 1.2.7 ran an apply and now running a plan on 1.3.0 and it seems to have corrected. Curious if the reference was somehow stale and righted ?

**Comment by apparentlymart** [comment] 2022-09-29 20:07
Hi @beaudryj!

The original issue comment showed an error from `terraform init`, rather than an error from `terraform plan`.

It sounds like it's not going to be possible to achieve a reproduction at this point, because even your local configuration can no longer reproduce it. For that reason, I'm going to close this issue. However, if you encounter this again and are able to share a configuration and reproduction steps that show it then we'd be happy to investigate some more in a new issue.

Terraform defaulting to `hashicorp/cloudflare` is the expected behavior in several cases, so it's possible that you accidentally ended up in one of those situations but then also unknowingly resolved it. I don't see any way for us to determine whether that's true at this point, so I think the best we can do is wait to see if this comes up again.

Sorry for the unsatisfying conclusion! Thanks for reporting this nonetheless, and hopefully we'll get an opportunity to debug this some more at a later date.

**Closed by apparentlymart** 2022-09-29 20:07 UTC
Labels: bug, waiting-response, new, waiting for reproduction
