### ISSUE TITLE
Terraform Show fails on empty plan

### ISSUE THREAD

**Issue by SubatomicHero** [hashicorp/terraform#23204] opened 2019-10-28 12:01 UTC
### Terraform Version
```
Terraform v0.12.12
```

### Terraform Configuration Files
Any would expose this

### Crash Output
https://gist.github.com/SubatomicHero/009916180b419b184ddb55a123ca4f0a

### Expected Behavior
Show should give a JSON regardless of the plan being empty/non-empty

### Steps to Reproduce
1. `terraform init`
2. `terraform workspace select ...`
3. `terraform plan -out plan.tfplan`
4. `terraform show -json ./plan.tfplan`

**Comment by SubatomicHero** [comment] 2019-10-28 13:51
I can confirm this issue is also present on a plan with changes to apply. I have attached a gist to a crash log https://gist.github.com/SubatomicHero/b3b608d4b7b0cb603adbc86df312865a

**Comment by mildwonkey** [comment] 2019-11-14 22:01
Hi, thanks for reporting this!

I'm unable to reproduce a crash with just an empty plan using terraform 0.12.12, and also with current versions. Can you please share more information about your terraform configuration, or provide a reproduction case?

This is what I tried, based on your comment about the empty plan:

main.tf
```hcl
provider "random" {}
```

output of `terraform show json -tf.plan`
```bash
{"format_version":"0.1","terraform_version":"0.12.12","planned_values":{"root_module":{}},"configuration":{"provider_config":{"random":{"name":"random"}},"root_module":{}}}
```

I tried again with a legitimately empty plan file, which gave an expected error:
```
# touch fake.plan
# terraform show -json fake.plan
Terraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

State read error: Error reading fake.plan as a statefile: no state

Plan read error: zip: not a valid zip file
```

I'd like to take a look at this, if you could help me reproduce the crash. Thanks!

**Comment by mildwonkey** [comment] 2019-12-11 20:07
Hi @SubatomicHero ! I am going to close this issue since there hasn't been a response, but please do open a new GH issue with detailed reproduction steps if you are still seeing this problem. Cheers!

**Closed by mildwonkey** 2019-12-11 20:07 UTC
Labels: bug, cli, crash, v0.12
