### ISSUE TITLE
Two different replacement styles for the same operation

### ISSUE THREAD

**Issue by bchen421** [hashicorp/terraform#25188] opened 2020-06-09 16:37 UTC
### Terraform Version

```
0.12.24 and 0.12.26
```

### Expected Behavior
We recently upgraded from earlier versions of 0.12 _(pre 0.12.16)_ to 0.12.24.  The behaviour for an RDS instance when wrapped in a module when the db_snapshot_identifier has gone from destroy and then create to create_before_destroy.  We have tested extensively and believe it's due to a recent bug fix in 0.12.16.  You can see a terraform plan output for RDS resources undergoing the same operation for an RDS instance inside a module and as a raw resource below

### Actual Behavior
Using a resource and changing db snapshot identifier
```An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
  # aws_db_instance.bchen must be replaced
-/+ resource "aws_db_instance" "bchen" {
```
Using a module with ONLY an rds instance in the module and changing the db snapshot identifier
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+/- create replacement and then destroy
Terraform will perform the following actions:
  # module.postgres.aws_db_instance.postgres must be replaced
+/- resource "aws_db_instance" "postgres" {
```

The same terraform plan run for two rds instances, one in a module and one via a raw resource
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
+/- create replacement and then destroy
```

### Steps to Reproduce
Change db_snapshot_identifier for an RDS instance created inside a module fails with
```
Error: Error creating DB Instance: DBInstanceAlreadyExists: DB Instance already exists
	status code: 400, request id: c001be95-565c-48c6-8af7-361e4ac01a00
```

### Additional Context

Believe this bug was newly introduced with this patch in 0.12.16
https://github.com/hashicorp/terraform/pull/23399

We have also attempted to setting a lifecycle of `create_before_destroy` to false inside the module for the rds resource already

**Comment by apparentlymart** [comment] 2020-06-09 22:25
Hi @bchen421! Thanks for reporting this.

Can you write a minimal Terraform configuration that illustrates the behavior you're describing and share it in a comment here, along with the `terraform plan` output you saw when you tried it?

You can use [`null_resource`](https://www.terraform.io/docs/providers/null/resource.html) as a placeholder resource type to avoid creating any real objects; although that will never return the "DBInstanceAlreadyExists" error you saw (because that is RDS specific) it will still be treated the same by Terraform for the purpose of deciding whether to use "destroy and then create replacement" or "create replacement and then destroy".

Thanks!

**Comment by bchen421** [comment] 2020-06-10 01:49
FYI I tested with a null resource and a module for null resource and it's not reproducible.  Getting you real terraform with some values changed

**Comment by bchen421** [comment] 2020-06-10 02:02
https://github.com/bchen421/test-replace
pretty much copy paste of
rds being created with a resource
rds being created with a module
our providers.tf
snippet of our locals.tf
and copy paste of our rds module

**Comment by bchen421** [comment] 2020-06-10 02:08
full Plan change output with some things redacted
```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
+/- create replacement and then destroy

Terraform will perform the following actions:

  # aws_db_instance.bchen must be replaced
-/+ resource "aws_db_instance" "bchen" {
      ~ address                               = "<REDACTED>"" -> (known after apply)
        allocated_storage                     = 50
        allow_major_version_upgrade           = false
        apply_immediately                     = true
      ~ arn                                   = "<REDACTED>" -> (known after apply)
        auto_minor_version_upgrade            = true
      ~ availability_zone                     = "us-east-1a" -> (known after apply)
        backup_retention_period               = 1
        backup_window                         = "07:00-07:30"
      ~ ca_cert_identifier                    = "rds-ca-2019" -> (known after apply)
      + character_set_name                    = (known after apply)
        copy_tags_to_snapshot                 = true
        db_subnet_group_name                  = "infra-uat-db-subnets"
        deletion_protection                   = false
      - enabled_cloudwatch_logs_exports       = [] -> null
      ~ endpoint                              = "<REDACTED>" -> (known after apply)
        engine                                = "postgres"
        engine_version                        = "11.4"
      ~ hosted_zone_id                        = "<REDACTED>" -> (known after apply)
        iam_database_authentication_enabled   = true
      ~ id                                    = "bchen" -> (known after apply)
        identifier                            = "bchen"
      + identifier_prefix                     = (known after apply)
        instance_class                        = "db.m5.large"
      - iops                                  = 0 -> null
      + kms_key_id                            = (known after apply)
      ~ license_model                         = "postgresql-license" -> (known after apply)
        maintenance_window                    = "sun:08:00-sun:10:00"
      - max_allocated_storage                 = 0 -> null
        monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
        multi_az                              = false
        name                                  = "postgres"
      ~ option_group_name                     = "default:postgres-11" -> (known after apply)
      ~ parameter_group_name                  = "default.postgres11" -> (known after apply)
        password                              = (sensitive value)
        performance_insights_enabled          = false
      + performance_insights_kms_key_id       = (known after apply)
      ~ performance_insights_retention_period = 0 -> (known after apply)
        port                                  = 5432
        publicly_accessible                   = false
      ~ replicas                              = [] -> (known after apply)
      ~ resource_id                           = "REDACTED"" -> (known after apply)
      - security_group_names                  = [] -> null
        skip_final_snapshot                   = true
      ~ snapshot_identifier                   = "arn:aws:rds:us-east-1:<REDACTED>:snapshot:<REDACTED>" -> "arn:aws:rds:us-east-1:<REDACTED>:snapshot:<REDACTED>" # forces replacement
      ~ status                                = "available" -> (known after apply)
      - storage_encrypted                     = false -> null
        storage_type                          = "gp2"
      - tags                                  = {} -> null
      + timezone                              = (known after apply)
        username                              = "postgres"
        vpc_security_group_ids                = [
            "sg-<REDACTED>",
            "sg-<REDACTED>",
        ]
    }

  # module.postgres.aws_db_instance.postgres must be replaced
+/- resource "aws_db_instance" "postgres" {
      ~ address                               = "<REDACTED>" -> (known after apply)
        allocated_storage                     = 50
        allow_major_version_upgrade           = false
        apply_immediately                     = true
      ~ arn                                   = "arn:aws:rds:us-east-1:<REDACTED>:db:<REDACTED>" -> (known after apply)
        auto_minor_version_upgrade            = true
      ~ availability_zone                     = "us-east-1c" -> (known after apply)
        backup_retention_period               = 7
        backup_window                         = "07:00-07:30"
        ca_cert_identifier                    = "rds-ca-2019"
      + character_set_name                    = (known after apply)
        copy_tags_to_snapshot                 = true
        db_subnet_group_name                  = "infra-uat-db-subnets"
        deletion_protection                   = false
      - enabled_cloudwatch_logs_exports       = [] -> null
      ~ endpoint                              = "<REDACTED>" -> (known after apply)
        engine                                = "postgres"
        engine_version                        = "11.4"
        final_snapshot_identifier             = "<REDACTED>"
      ~ hosted_zone_id                        = "<REDACTED>" -> (known after apply)
        iam_database_authentication_enabled   = true
      ~ id                                    = "<REDACTED>" -> (known after apply)
        identifier                            = "<REDACTED>"
      + identifier_prefix                     = (known after apply)
        instance_class                        = "db.m5.large"
        iops                                  = 0
      + kms_key_id                            = (known after apply)
      ~ license_model                         = "postgresql-license" -> (known after apply)
        maintenance_window                    = "sun:08:00-sun:10:00"
      - max_allocated_storage                 = 0 -> null
        monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
        multi_az                              = false
        name                                  = "postgres"
      ~ option_group_name                     = "default:postgres-11" -> (known after apply)
      ~ parameter_group_name                  = "default.postgres11" -> (known after apply)
        password                              = (sensitive value)
        performance_insights_enabled          = false
      + performance_insights_kms_key_id       = (known after apply)
      ~ performance_insights_retention_period = 0 -> (known after apply)
        port                                  = 5432
        publicly_accessible                   = false
      ~ replicas                              = [] -> (known after apply)
      ~ resource_id                           = "<REDACTED>" -> (known after apply)
      - security_group_names                  = [] -> null
        skip_final_snapshot                   = true
      ~ snapshot_identifier                   = "arn:aws:rds:us-east-1:<REDACTED>:snapshot:<REDACTED"" -> "arn:aws:rds:us-east-1:<REDACTED>:snapshot:<REDACTED>" # forces replacement
      ~ status                                = "available" -> (known after apply)
      - storage_encrypted                     = false -> null
        storage_type                          = "gp2"
        tags                                  = {
            "sr_app"    = "<REDACTED>"
            "sr_env"    = "<REDACTED>"
            "sr_group"  = "<REDACTED>"
            "sr_org"    = "<REDACTED>"
            "sr_region" = "<REDACTED>"
        }
      + timezone                              = (known after apply)
        username                              = "postgres"
        vpc_security_group_ids                = [
            "sg-<REDACTED>",
            "sg-<REDACTED>",
        ]
    }

Plan: 2 to add, 0 to change, 2 to destroy.
```

**Comment by bchen421** [comment] 2020-06-10 02:10
basically, when we have an automated process change the value in our `auto.tfvars.json` for the value of the source db snapshot identifier this is what we see

**Comment by jbardin** [comment] 2020-06-11 16:16
Hi @bchen421 

This sounds like the result of the `create_before_destroy` fixes that happened during the 0.12 release (#22937 and #22976). The specific patch I think would be effecting you was fixing the problem that `create_before_destroy` dependencies were not properly tracked across module boundaries. Besides not following the specified replacement ordering, failing to re-order these operations causes cycles when replacing multiple instances in the dependency chain. 

If you have any `create_before_destroy` resources that transitively depend on the `aws_db_instance` in the module, the `aws_db_instance` itself must also be handled as `create_before_destroy` to ensure correct ordering and to prevent dependency cycles. You can't override this, because doing so is likely to prevent the entire operation from working at all.

Hopefully that provides enough background to help you track down the changes in behavior with you configuration. If you do find a way to reproduce unexpected behavior, please feel free to post it here.

**Comment by bchen421** [comment] 2020-06-11 18:12
Got it!  I understand where it's coming from, I understand why you would add those relationships.  Was unaware of transitive dependencies and `create_before_destroy` propagation.  I believe I know where it's coming from and I will get a working example for you.

That's understandable from a graph generation perspective I think? But from a practical perspective, if I am correct we have:

• instance of rds db called postgres inside a module
• we have ecs service with task definition that uses the FQDN / dns name attribute of the postgres instance as an output to generate the db connection string programatically, it's injected into our container via ECS and an environment variable (using terraform as a poor mans service discovery kinda)

our ecs service task definitions have a create before destroy block because the aws provider supports a name prefix and we leverage that for no downtime deployments and configuration changes for our apps that are in containers.  But because of that, when I go to change my RDS instance snapshot id, the rds instance is now forced to be create_before_destroy without the ability to override.

From a theoretical perspective, I can kinda understand the rationale, but from a practical usage perspective, it seems a tiny bit overrestrictive.

Thanks for the explanation, will def try and get a working example over to you all :)

**Comment by bchen421** [comment] 2020-06-11 18:19
Here's a code snippet of how we're using our rds module output as an input to our ECS containers by injecting it as an env var _(some values redacted)_
```
  env_vars = <<ENV
    { "name": "ENVIRONMENT", "value": "${var.env}" },
    { "name": "VERSION", "value": "${var.event_response_service-version}"},
    { "name": "VAULT_ADDR", "value": "https://<REDACTED>" },
    { "name": "<REDACTED>", "value": "https://${aws_route53_record.api.name}/api/" },
    { "name": "EVENT_RESPONSE_URL", "value": "${local.event_response_url}" },
    { "name": "DB_HOST", "value": "${module.postgres.postgres_address}" },
    { "name": "DB_NAME", "value": "<REDACTED>" },
    { "name": "DB_USER", "value": "<REDACTED>" },
    { "name": "OKTA_AUTH_SERVER", "value": "${local.okta_auth_server_id}" },
    { "name": "AWS_DB_ACCESS_ROLE_ARN", "value": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/<REDACTED>" },
    { "name": "AWS_DB_ACCESS_ROLE_SESSION_NAME", "value": "REDACTED>-${var.env}" }
  ENV
```

The ecs service and task definition module has a `create_before_destroy` block in the `aws_ecs_task_definition` as that is where the environment variables are rendered into our docker json for ecs to consume.  Am I correct in this assessment based on what's above?  And it would make sense that the new db resource I made to test did not exhibit this behaviour since noone was actually using that new rds db resource I created.

**Comment by bchen421** [comment] 2020-06-17 15:39
FYI, confirmed it's the issue.
RDS instance created in a module with an output of the endpoint address
ECS service and task def with create_before_destroy uses the RDS instance output as an environment variable
This makes the RDS instance also create before destroy

Is this intended behaviour?  Feels awkward to propagate that to an upstream dependency

**Comment by jbardin** [comment] 2020-06-17 16:46
Yes, this is the intended behavior. The ordering imposed by `create_before_destroy` must be propagated upstream in order to satisfy the `create_before_destroy` behavior. Depending on the operations involved you will end up with one of two error conditions; there is a dependency cycle that can't be resolved, or the dependency is updated/replaced too early which will fail for many combinations of resources.  

The order of operations should be identical whether the resource are in the same module, or they are spread across modules. 

Since this is working as designed, I'm going to close this out now. It's probably better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) for further discussion, where there are more people ready to help with direct experience using these specific resources and providers.

**Closed by jbardin** 2020-06-17 16:46 UTC
Labels: bug, core, v0.12
