### ISSUE TITLE
0.13.x: Destroying resource with -target doesn't destroy resources defined in data blocks in module that depends on targeted resource

### ISSUE THREAD

**Issue by 9numbernine9** [hashicorp/terraform#26116] opened 2020-09-03 15:41 UTC
### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.25.0
```

### Terraform Configuration Files
```terraform
### main.tf
provider "azurerm" {
  version = "~> 2.25.0"
  features {}
}

resource "azurerm_resource_group" "outer_rg" {
  name     = "outer_rg"
  location = "eastus"
}

module "testmodule" {
  source = "./testmodule"
  rg_name = azurerm_resource_group.outer_rg.name
  depends_on = [azurerm_resource_group.outer_rg]
}

### testmodule/main.tf
variable "rg_name" {
  description = "Resource group name"
}

data "azurerm_resource_group" "data_rg" {
  name = var.rg_name
}

resource "azurerm_resource_group" "inner_rg" {
  name = "inner_rg"
  location = "eastus"
}

```

### Expected Behavior
```terraform
terraform apply
terraform destroy -target=azurerm_resource_group.outer_rg
terraform state list
# Expecting no output here
```

### Actual Behavior
```
$ terraform state list
module.testmodule.data.azurerm_resource_group.data_rg
```

### Steps to Reproduce
```terraform
terraform init
terraform apply
terraform destroy -target=azurerm_resource_group.outer_rg
terraform state list
```

### Additional Context
Hello!

I am experimenting with using `depends_on` statements in modules in Terraform `0.13.x`. One thing I noticed is that if a module's declaration depends on a resource and that resource is destroyed with `terraform destroy -target=azurerm_resource_group.outer_rg` (e.g.), any `data` blocks that are defined _inside_ of the module will have resources left over when inspecting the output of `terraform state list` once the `destroy` is complete. Although this isn't necessarily the end of the world, it is kind of annoying: subsequent `terraform apply`s will fail because it will try to refresh the `module.testmodule.data.azurerm_resource_group.data_rg` resource that is believed to still exist. 

I'm not necessarily sure if this is a bug or not, but it does seem to possibly be slightly surprising - if I have a module and destroy the thing that module depends on, shouldn't everything inside the module be destroyed too? In my 'mental model' of modules, there isn't a real reason to keep that `data` resource around - it only exists inside of that module to look up some value for further resource declarations.

**Comment by alisdair** [comment] 2020-09-17 15:31
Hi @9numbernine9, thanks for reporting this. I'm able to reproduce the issue with your configuration and reproduction steps with Terraform 0.13.3.

While I understand your surprise at this behaviour, I don't believe that this is a bug. My understanding is that module `depends_on` is intended to delay the evaluation of a module, not create destroy edges that would be followed as part of a targeted destroy. The use of module `depends_on` is intended only to ensure that operations are executed in the required order, so I'm not surprised that the data source is not removed from state.

Resource targeting and especially targeted destroy are tools intended to be used in exceptional circumstances, so they may have a few rough edges. We recommend that users avoid using targeted destroy wherever possible.

I'm leaving this open and will ask other core team members to confirm or correct my understanding here.

**Comment by alisdair** [comment] 2020-09-18 19:55
We discussed this behaviour internally, and I wanted to share some of the outcomes.

Most importantly, targeted destroy does not affect data sources, even without the complication of a module or `depends_on`. Consider this configuration:

```hcl
resource "null_resource" "a" {
}

data "null_data_source" "b" {
  inputs = { a: null_resource.a.id }
}
```

- `terraform init`, `terraform apply -auto-approve`
- `terraform destroy -target null_resource.a` does not destroy the data source

While it's a rough edge, this is considered reasonable behaviour for targeted destroy, which as I mentioned above is _not_ recommended as part of a main workflow. It's definitely not ideal, but the concept of `-target` in general is one that we would eventually like to make obsolete.

We do not intend to change the behaviour of targeted destroy with regards to data sources, and instead will focus on the other improvements which should make it unnecessary. As a result, I'm going to close this issue as "working as designed", for want of a more useful thing to do.

Thanks again for reporting the issue, and I hope this explains what's happening under the hood!

**Closed by alisdair** 2020-09-18 19:55 UTC
Labels: bug, confirmed

**Comment by 9numbernine9** [comment] 2020-09-20 15:39
Hi @alisdair ! Thanks for taking the time to discuss internally and respond. 

I definitely agree that targeted destroy also shouldn't be part of a regular workflow (and it's not part of mine - hopefully I didn't give the impression that it was!). This was a scenario where I was trying out a module written by someone else that I didn't directly control, so I was going through a loop of "test a few things, clean up what I did, try it slightly differently" and noticed the _slightly_ surprising behaviour that I mentioned in the original issue. It's not a big deal because `terraform state rm` on the "leftover" `data` state cleans things up easily, but it is something to watch out for.

Again, thanks for clarifying things. Hopefully future users with the same question can read the discussion on this issue and also be less surprised going forward. :)
