### ISSUE TITLE
VPC import provider alias

### ISSUE THREAD

**Issue by egustafsson** [hashicorp/terraform#18280] opened 2018-06-18 19:57 UTC
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.21.0
```

### Terraform Configuration Files

```
provider "aws" {
  alias = "oregon"
  region     = "us-west-2"
}

resource "aws_vpc" "devvpc" {
  provider   = "aws.oregon"
  cidr_block = "172.31.0.0/16"

  tags = {
    Environment = "Development"
  }

}
```

### Crash Output
```
$terraform import  aws_vpc.devvpc vpc-xxxxxx
aws_vpc.devvpc: Importing from ID "vpc-xxxxxx"...
aws_vpc.devvpc: Import complete!
  Imported aws_vpc (ID: vpc-xxxxxx)
aws_vpc.devvpc: Refreshing state... (ID: vpc-xxxxxx)

Error: aws_vpc.devvpc (import id: vpc-xxxxxx): 1 error(s) occurred:

* import aws_vpc.devvpc result: vpc-xxxxxx: import aws_vpc.devvpc (id: vpc-xxxxxx): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

### Steps to Reproduce
```
$terraform init
$teraform import aws_vpc.devvpc vpc-xxxxxx

```
To solve this issue I had to change my main.tf to use us-west-2 change my vpc-peering.tf so the devvpc resource wasn't using the aliased provider. 

main.tf
```
provider "aws" {
  region = "us-west-2"
}
```
vpc-peering.tf
```
resource "aws_vpc" "devvpc" {
//  provider   = "aws.oregon"
  cidr_block = "172.31.0.0/16"

  tags = {
    Environment = "Development"
  }
}
```

```
$ terraform import  aws_vpc.devvpc vpc-xxxxxx
aws_vpc.devvpc: Importing from ID "vpc-xxxxxx"...
aws_vpc.devvpc: Import complete!
  Imported aws_vpc (ID: vpc-xxxxxx)
aws_vpc.devvpc: Refreshing state... (ID: vpc-xxxxxx)

Import successful!
```

Now after that I had to edit the terraform.tfstate file and change 
                    "provider": "provider.aws"
 to 
                    "provider": "provider.aws.oregon"
and change back my main.tf to have us-east-2 and set back provider = "aws.oregon" for my devvpc. 

Now when I run a terraform plan it successfully refreshing the state of my devvpc and does not try to destroy or change it. 

It seems that aws_vpc import does not properly handle aliased aws providers.

**Comment by jbardin** [comment] 2018-06-18 22:36
Hi @egustafsson,

Sorry about the confusion here. The `import` command can't currently determine the correct provider form the configuration, and you need to use the `-provider` flag. 

Does it work if you run `terraform import -provider aws.oregon aws_vpc.devvpc vpc-xxxxxx`?

**Comment by egustafsson** [comment] 2018-06-18 22:39
I will try,  I got 3 other vpcs that I need to import.

didn't see anything on the provider flag in import but might be my fault.

**Comment by gwvandesteeg** [comment] 2018-11-29 01:52
SImilar case, problem seems to be that terraform import doesn't understand/use the specified provider in the resource.  Manually specifying the provider on the command line using the -provider flag cause the import to work correctly.

**Comment by mildwonkey** [comment] 2019-01-03 15:43
There hasn't been activity on this issue for awhile and the question was answered (specifying -provider on the command line), so I will close this issue. Thanks!

**Closed by mildwonkey** 2019-01-03 15:43 UTC

**Comment by gwvandesteeg** [comment] 2019-01-04 00:12
The problem is quite simple terraform import doesn't adhere to the explicitly configured provider specified on the resource when doing an import of the resource.
It'll use the default provider, or the one specified on the command line from the import, not anything specified in the terraform config on the actual resource being imported.

**Comment by jbardin** [comment] 2019-01-04 00:23
Hi @wvandesteeg,

We already have #17139 and #18257 open regarding using the configured providers during import.
