### ISSUE TITLE
yamlencode wrong indentation when use local_file

### ISSUE THREAD

**Issue by rlanore** [hashicorp/terraform#31957] opened 2022-10-06 16:33 UTC
### Terraform Version

```shell
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.2.3
```

### Terraform Configuration Files

```terraform
variable "yaml_list" {
  type = list(object({
    key = string
    operator = string
    value = string
    effect = string
  }))

  default = [
    {
      key: "akey"
      operator: "Equal"
      value: "true"
      effect: "something"
    }
  ] 
}

output "log3" {
    value = "${yamlencode(var.yaml_list)}"
}

# Generate ansible var files
resource "local_file" "test" {
  content = <<-CONF
    ansible_variables:
      ${yamlencode(var.yaml_list)}
    CONF
  filename = "./rendred_file"
}
```

### Debug Output

https://gist.github.com/rlanore/decd814774fc4bb0f6d1a736202df8ea

### Expected Behavior

cat rendred_file
```
ansible_variables:
  - "effect": "something"
    "key": "akey"
    "operator": "Equal"
    "value": "true"
```

### Actual Behavior

cat rendred_file
```
ansible_variables:
  - "effect": "something"
  "key": "akey"
  "operator": "Equal"
  "value": "true"
```

### Steps to Reproduce

terrafrom init
terraform apply

**Comment by crw** [comment] 2022-10-06 18:52
Thanks for this report!

**Comment by alisdair** [comment] 2022-10-06 19:01
`yamlencode` is working correctly here. The problem is that the configuration concatenates the `yamlencode` output with another string, and this is what causes the indentation problem.

Instead of using string concatenation with `yamlencode` or `jsonencode`, always pass a complete value to be encoded. In this example, the following configuration works as I believe you intended:

```hcl
resource "local_file" "test" {
  content = yamlencode({ "ansible_variables" = var.yaml_list })
  filename = "./rendred_file"
}
```

Note that the indentation doesn't completely match your desired output, but I believe it is semantically correct YAML representing the data you intended to write out to the file.

Hope this helps! This doesn't represent a bug in Terraform, so I'm going to close this issue.

**Closed by alisdair** 2022-10-06 19:01 UTC
Labels: bug, provider/local, new

**Comment by rlanore** [comment] 2022-10-07 07:06
Thanks for quick reply. My use case is working
