### ISSUE TITLE
for-expression doesn't perform eager evaluation

### ISSUE THREAD

**Issue by ChernikovP** [hashicorp/terraform#24026] opened 2020-02-04 15:20 UTC
### Terraform Version

```
$ terraform --version
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-1"
}

data "aws_vpc" "selected" {
  default = true
}

data "aws_subnet_ids" "selected" {
  vpc_id = data.aws_vpc.selected.id
}

locals {
  apps = {
    foo = { lb = "foo-alb" }
    bar = { lb = null }
  }

  lbs = { for label, config in local.apps : label => config.lb }
}

resource "aws_security_group" "lb" {
  name   = "default-sg"
  vpc_id = data.aws_vpc.selected.id

  ingress {
    protocol    = "tcp"
    from_port   = 80
    to_port     = 80
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_alb" "all" {
  for_each = local.lbs

  name            = each.value
  subnets         = data.aws_subnet_ids.selected.ids
  security_groups = [aws_security_group.lb.id]
}

output "lbs_to_create" {
  value = local.lbs
}

output "lb_created" {
  value = { for label, res in aws_alb.all : label => res.name }
}
```

### Debug Output

See the gist - https://gist.github.com/ChernikovP/2e4e31cda259895e1c61a9c4d55e751a

### Expected Behavior

As `{foo = "foo-alb", bar = null }` evaluates to `{ foo = "foo" }`, only `foo` LB should be created.

### Actual Behavior

`for` expression seems to be evaluated on the fly within `for_each`, thus `foo` and `bar` LBs are created.

```
Terraform will perform the following actions:

  # aws_alb.all["bar"] will be created
  + resource "aws_alb" "all" {
     ...
    }

  # aws_alb.all["foo"] will be created
  + resource "aws_alb" "all" {
     ...
    }

  # aws_security_group.lb will be created
  + resource "aws_security_group" "lb" {
     ...
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```
See the discrepancy in outputs:

```
Outputs:

lb_created = {
  "bar" = "tf-lb-20200204150544436100000001"
  "foo" = "foo-alb"
}
lbs_to_create = {
  "foo" = "foo-alb"
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Explicitly adding `if` condition:

```
lbs = { for label, config in local.apps : label => config.lb if config.lb != null }
```

solves the problem.

**Comment by teamterraform** [comment] 2020-02-05 01:48
Hi @ChernikovP,

Sorry you were having difficulty here. The way maps are displayed can be confusing, since keys with null values are elided in the output. Since the rest of this is more a statement about how the language works, which in this case appears to be working as designed, we can close this as a duplicate of #23451 covering the output discrepancy.

**Closed by teamterraform** 2020-02-05 01:48 UTC
