### ISSUE TITLE
Terraform crash v1.1.0

### ISSUE THREAD

**Issue by addyb77** [hashicorp/terraform#33567] opened 2023-07-24 13:29 UTC
### Terraform Version

```shell
Terraform v1.5.3
on windows_amd64
```

### Terraform Configuration Files

NA

### Debug Output

NA

### Expected Behavior

Successful push to production master

### Actual Behavior

```Step #1: !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Step #1: 
Step #1: Terraform crashed! This is always indicative of a bug within Terraform.
Step #1: Please report the crash with Terraform[1] so that we can fix this.
Step #1: 
Step #1: When reporting bugs, please include your terraform version, the stack trace
Step #1: shown below, and any additional information which may help replicate the issue.
Step #1: 
Step #1: [1]: https://github.com/hashicorp/terraform/issues
Step #1: 
Step #1: !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Step #1: 
Step #1: runtime error: invalid memory address or nil pointer dereferencegoroutine 309 [running]:
Step #1: runtime/debug.Stack()
Step #1: 	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
Step #1: runtime/debug.PrintStack()
Step #1: 	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
Step #1: github.com/hashicorp/terraform/internal/logging.PanicHandler()
Step #1: 	/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
Step #1: panic({0x221d240, 0x3ed5b10})
Step #1: 	/usr/local/go/src/runtime/panic.go:1038 +0x215
Step #1: github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc001e4d270, {{}, 0x4d, {0xc0008c8620, 0x1e}, {0xc0008c4708, 0x4}}, {0xc000633300, 0x30, 0x4})
Step #1: 	/home/circleci/project/project/internal/instances/expander.go:392 +0x95
Step #1: github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x3c, {0xc00083c660, 0x0, 0xc00080f000}, {{}, 0x4d, {0xc0008c8620, 0x1e}, {0xc0008c4708, 0x4}}, ...)
Step #1: 	/home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
Step #1: github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc000ce0b58, {0xc00083c660, 0x1, 0x1}, {{}, 0x4d, {0xc0008c8620, 0x1e}, {0xc0008c4708, 0x4}}, ...)
Step #1: 	/home/circleci/project/project/internal/instances/expander.go:385 +0x293
Step #1: github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc000d0a460, {{}, {0xc00083c660, 0x1, 0x1}, {{}, 0x4d, {0xc0008c8620, 0x1e}, {0xc0008c4708, ...}}})
Step #1: 	/home/circleci/project/project/internal/instances/expander.go:157 +0x16f
Step #1: github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc001dff870, {0x2aecc00, 0xc0005a08c0})
Step #1: 	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
Step #1: github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc001dff870, {0x2aecc00, 0xc0005a08c0})
Step #1: 	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
Step #1: github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc0005a08c0}, 0xc0)
Step #1: 	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
Step #1: github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0005a0a80, {0x2aecc00, 0xc0005a08c0}, {0x7f745d3b7fa0, 0xc001dff870})
Step #1: 	/home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
Step #1: github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc001dff870})
Step #1: 	/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
Step #1: github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000fc59e0, {0x2553ec0, 0xc001dff870}, 0xc001d81440)
Step #1: 	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
Step #1: created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
Step #1: 	/home/circleci/project/project/internal/dag/walk.go:304 +0xf85
Step #1: google_service_account.this: Refreshing state... [id=projects/gc-p-prj-thyme-0001-9439/serviceAccounts/gc-p-businessobjects-sa@gc-p-prj-thyme-0001-9439.iam.gserviceaccount.com]
Step #1: time=2023-07-24T13:06:36Z level=error msg=Module /workspace/org/prd/veeam_backup/compute has finished with an error: 1 error occurred:
Step #1: 	* exit status 11
```

### Steps to Reproduce

git add .
git commit -m "change description"
git push -u origin master

### Additional Context

Our GCP environment is built with terraform/terragrunt. 
We clone the repo locally and use git with VS code to make changes and push the code to cloud build which activates the relevant trigger and pushes either to test branches (Plan) or master (Plan, apply)

We have several triggers for various folders (prod, test, rnd, infrastructure) all triggers apart from prod work.
We recently created a redhat linux vm which was fine, these errors occurred when pushing a change for a boot disk increase (from 100GB to 500GB)

**Comment by jbardin** [comment] 2023-07-24 13:38
Duplicate of #30110

**Closed by jbardin** 2023-07-24 13:38 UTC
Labels: bug, new
