### ISSUE TITLE
Support RDS cluster storage encryption

### ISSUE THREAD

**Issue by bsiegel** [hashicorp/terraform#5491] opened 2016-03-07 18:19 UTC
Looks like this was added to `aws_rds_db_instance` in #1041. It would be good to have this exposed for the `aws_rds_cluster` / `aws_rds_cluster_instance` resources as well. However it looks like both CreateDBCluster and CreateDBInstance methods have a StorageEncrypted flag, and I'm not clear on how those are supposed to interact. Ideally, the user would specify `storage_encrypted` on the `aws_rds_cluster` resource, and then any instances attached to that cluster would have that value computed.

**Comment by catsby** [comment] 2016-03-07 19:12
Hey @bsiegel – I think this is actually a duplicate of an issue I opened awhile back, https://github.com/hashicorp/terraform/issues/4414 . I'm going too close this in favor of that one. Thanks!

**Closed by catsby** 2016-03-07 19:12 UTC
Labels: enhancement, provider/aws

**Comment by bsiegel** [comment] 2016-03-07 19:14
@catsby Ah yep, I did some searching but didn't happen upon the correct set of keywords needed to find that issue. Thanks!
