### ISSUE TITLE
plan errors on linting issue

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#25249] opened 2020-06-15 16:34 UTC
### Terraform Version
```
tf --version
Terraform v0.12.24
+ provider.aws v2.60.0
+ provider.null v2.1.2
```

### Terraform Configuration Files

```
resource aws_backup_plan main {
  name = "${local.prefix}-${data.aws_region.current.name}-backup-plan"
  rule {
    rule_name         = "monthly_backup"
    target_vault_name = var.source_vault_name
    schedule          = "cron(0 0 1 * ?)"
    lifecycle { cold_storage_after = "1"
                delete_after = "180" }
  }
}
```

error:

```
$ tf plan

Error: Invalid single-argument block definition

  on ../../../../modules/ebs_replicator/aws_backup.tf line 31, in resource "aws_backup_plan" "main":
  31:
  32:
```

but this works:
```
      lifecycle {
                  cold_storage_after = "1"
                  delete_after = "180"
                }
```

### Additional Context

`terraform fmt` does resolve syntax issue. `plan` and `apply` work after

### References

- https://github.com/hashicorp/terraform/issues/22086

**Comment by danieldreier** [comment] 2020-06-15 21:03
@drewmullen I have reproduced the behavior you're describing, but I think that this is a formatting opinion that you disagree with rather than a bug. 

The next line of the error message is:
```
An argument definition on the same line as its containing block creates a
single-line block definition, which must also be closed on the same line.
Place the block's closing brace immediately after the argument definition.
```

Terraform intentionally has strongly opinionated formatting. The advantage of having opinionated formatting is that all Terraform code is relatively easily readable to experienced Terraform users, even across different codebases. When people switch companies or collaborate on open source Terraform codebases, they don't have to agree on syntax conventions, and don't have to re-learn norms, because `terraform fmt` specifies the standard. This is based on our positive experiences with the Go programming language, which does the same thing. In many cases, Terraform is a tool that people only pick up every few weeks or months, so not having to learn syntax conventions is more useful than flexibility.

Conversely, the downside is that when people have a personal preference for a different style, they are not accommodated. This is an intentional design decision to make Terraform easier to adopt and more portable, and the disadvantages are worth the benefit.

#22086 already tracks the request for changing that opinion to allow one-off blocks. I think it's a reasonable request and people are making a plausible case there. I encourage you to upvote it. I'm going to close this, because having two different issues open that track the same request will divide the upvotes and make it less likely that either one gets to the top of the list.

**Closed by danieldreier** 2020-06-15 21:03 UTC
