### ISSUE TITLE
terraform remote push --force complains about conflicts

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#8020] opened 2016-08-06 00:38 UTC
``` sh
% terraform remote push --help
Usage: terraform push [options]
...
-force                 Forces the upload of the local state, ignoring any
                          conflicts. This should be used carefully, as force pushing  
                          can cause remote state information to be lost.

% terraform remote push
Failed to read state: Unknown refresh result: Local and remote state conflict, manual resolution required

% terraform remote push --force
Failed to read state: Unknown refresh result: Local and remote state conflict, manual resolution required

% terraform remote push -force
Failed to read state: Unknown refresh result: Local and remote state conflict, manual resolution required

% sudo rm -rf /
```
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- aws_db_instance
- sanity
### Expected Behavior

The config should have pushed to the remote
### Actual Behavior

The config did not push to the remote
### Steps to Reproduce
1. Set up remote configuration
2. Delete a resource from the tfstate file
3. Run `terraform remote push --force`

**Comment by eherot** [comment] 2017-03-02 16:22
This seems to be a duplicate of #5663

**Comment by apparentlymart** [comment] 2017-04-05 00:21
Hi @jleclanche! Sorry for the trouble here and sorry we let this issue languish for so long.

The remote state system was totally redesigned in 0.9, so there's no longer a local state cache and no longer a `terraform remote push` command. I'm sorry we never got to the bottom of what was causing your issue here, but at least as of 0.9 it should have become a moot point, so I'm going to close this.

If anyone encounters similar-looking issues in version 0.9.0 or above I'd encourage them to open a fresh new issue so we can triage and address it separately, since the relevant parts of Terraform are now considerably different than they were in v0.7.0.

**Closed by apparentlymart** 2017-04-05 00:21 UTC
Labels: bug, core
