### ISSUE TITLE
plugin/discovery: Retry signature/provider download

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#20992] opened 2019-04-11 16:17 UTC
Sometimes CDN or S3 misbehave and fail to serve provider binary.

```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "packet" (1.7.2)...
- Downloading plugin for provider "local" (1.2.0)...
- Downloading plugin for provider "template" (2.1.0)...

Error installing provider "random": error fetching checksums signature: 502 Bad Gateway.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

- Downloading plugin for provider "tls" (1.2.0)...
```

### Current Terraform Version

0.12 (7df3275120cf3aef592a8cdb2cbfbf36faecba44)

### Use-cases

Survive temporary outage of Registry/CDN/S3 and avoid the need for manual retry in most cases.

### Attempted Solutions

Retrying `terraform init` manually.

### Proposal

Automatically retry signature and provider download on retryable HTTP codes and/or headers.

### References

https://github.com/hashicorp/go-getter/issues/92

**Comment by apparentlymart** [comment] 2019-04-11 16:31
Thanks for pointing this out, @radeksimko.

I assume given the error message you've shared here that this was based on a real-world problem you hit. My usual instinct is that if something unexpected happens it's best to bail out and report as much detail as possible to the user so that they can react rather than trying to paper over it, but in this situation it does indeed look like there's an opportunity for a compromise: retry a few times, probably with a shorter timeout (so we don't block for a long time before showing an error) and _then_ return the error from the last attempt, if none succeed.

I expect that at least some of the time an error like this will be persistent, because there's an outage in either the CDN or the underlying storage, and so retrying _forever_ would not be practical, but that doesn't mean we can't retry just once or twice quickly to see if the problem is transient.

I don't think this is something we should make user-configurable, since it's an edge-case anyway: instead, we should just find a suitable compromise for number of retries and timeout and run with it, erring on the side of returning an error relatively quickly if there's a long-lived problem, since the user can always retry manually by running `terraform init` again if our retry behavior isn't aggressive enough.

**Comment by radeksimko** [comment] 2019-04-11 17:11
> I expect that at least some of the time an error like this will be persistent, because there's an outage in either the CDN or the underlying storage, and so retrying forever would not be practical, but that doesn't mean we can't retry just once or twice quickly to see if the problem is transient.

👍Agreed.

> I don't think this is something we should make user-configurable, since it's an edge-case anyway

Makes sense.

**Comment by awendt** [comment] 2022-09-23 10:03
Random transient failures we regularly see during CI builds:

- `connection reset by peer`
- `Get "https://registry.terraform.io/.well-known/terraform.json": net/http: request canceled while waiting for connection`
- `bad response code: 503`

**Comment by apparentlymart** [comment] 2022-10-05 02:09
Hi all!

This issue is describing the behavior of some client code that hasn't existed in Terraform since Terraform v0.13. This older version of the provider installer directly scraped indexes from `releases.hashicorp.com`, rather than using the Terraform Registry.

Current Terraform releases have a completely different provider installer that uses the Terraform Registry, and it includes some retry logic to try up to three times to download index metadata from the registry before giving up. Therefore if folks are seeing timeout-related or other network-related problems with current Terraform then I'm afraid we'll need to start over with a fresh bug report capturing the details about that, since anything we would learn from the information in this issue is only applicable to an obsolete version of Terraform.

For that reason I'm going to close this issue but I'd encourage anyone who is experiencing connectivity problems during provider installation to first check out #27379 and see if your problem seems aligned with that one -- specifically, that the requests are eventually working but are slower than what you see from other software running on the same computer. If your experience doesn't match that, then I'd encourage you to [open a new bug report issue](https://github.com/hashicorp/terraform/issues/new?assignees=&labels=bug%2Cnew&template=bug_report.yml) and share the information requested in the issue template so that we can try to see where the problem is arising and determine how best to solve it.

Thanks!

**Closed by apparentlymart** 2022-10-05 02:09 UTC
Labels: enhancement
