### ISSUE TITLE
Using yamldecode together with coalesce produces error "all arguments must have the same type" when yaml has lists inside

### ISSUE THREAD

**Issue by pavol-antalik-vacuumlabs** [hashicorp/terraform#32944] opened 2023-03-30 07:33 UTC
### Terraform Version

```shell
Terraform v1.4.2
on linux_amd64
```

### Terraform Configuration Files

```terraform
locals {
  test = coalesce(yamldecode(file("test.yaml"))["environments"], {})
}
```

### Debug Output

Trace output:
https://gist.github.com/pavol-antalik-vacuumlabs/f7dfd356656749aa1f6df5af3bde512e

Yaml that works with terraform coalesce:
https://gist.github.com/pavol-antalik-vacuumlabs/d52752f96c26aa6038292c4d78d7cf6e

Yaml that produces error with terraform coalesce ("type: postgres" missing in dev):
https://gist.github.com/pavol-antalik-vacuumlabs/1588e7e66ee1390e4ab33ce1d6513cc9

Yaml without listst that works with terraform coalesce ("type: postgres" missing in dev):
https://gist.github.com/pavol-antalik-vacuumlabs/e7e8d61deca1cc653edbd97281e69a6f

### Expected Behavior

Terraform should load valid .yaml file - **that contains lists somewhere in the structure** - using _yamldecode_ function without errors, so it can be further used in _coalesce_ function, even when different branches of the yaml configuration (dev, stage) do not contain the same parameters.

### Actual Behavior

If the valid .yaml file **contains lists**, and the branches (dev, stage) do not contain EXACTLY the same parameters (regardless of the values, see the "type: postgress" in the gists), the _yamldecode_ seems to fail and the value used in _coalesce_ is the evaluated as invalid, resulting in empty local variable value.

If the .yaml file **does NOT contain lists**, even when not having all the parameters in all branches, the content of the .yaml file is loaded and the value is used in _coalesce_ without problems.

Using just _yamldecode_ function without _coalesce_ does not produce visible errors and the content of the .yaml file is loaded into a local variable without problems, regardless of **used lists** and missing parameters in some of the branches.

(Example of yaml files are referenced as gists in Debug Output section)

### Steps to Reproduce

terraform init
terraform console

**Comment by jbardin** [comment] 2023-03-30 13:12
Hi @pavol-antalik-vacuumlabs,

Because the nested values in the yaml map are comprised of different structures, there is not going to be a way for `yamldecode` to always infer the correct expected type for all operations. The `coalesce` function must always return a single type so that references to it can be properly evaluated. The structures are different in the non-working cases, so are decoding into different _object_ types, which have no way to be unified such that `coalesce` can return a single type. Another issue here is that the second parameter you have given to `coalesce` is an empty object, which is only equivalent to another empty object. When dealing with the absence of data, you should prefer `null`.

If there is a single schema type which the yaml file must correspond to, one way to work around this would be to define a variable type in a module, with `optional` used for any attributes that may be missing, and then have that module only return the converted variable value. This is a bit more work to define, but does ensure that all values always exactly match the expected type.

Because yaml (and json) do not have the same type system as Terraform, there is always going to be some friction when converting from untyped data. Since this is working as designed, I'm going to close the issue out for now. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2023-03-30 13:12 UTC
Labels: bug, new, working as designed
