### ISSUE TITLE
Terraform is not usable for multi-region infrastructure as code

### ISSUE THREAD

**Issue by jeffrey-aguilera** [hashicorp/terraform#33516] opened 2023-07-12 19:51 UTC
### Terraform Version

```shell
v1.5.3
```

### Use Cases

I have a module that creates a bucket with a particular setup. It is parametrized by the bucket name and the provider (as proxy to account/region). I want to instantiate multiple modules for a collection of regions, each of which has an associated provider.

### Attempted Solutions
```
module "buckets" {
  for_each = toset(local.regions)

  source = "../../modules/bucket"
  providers = {
    aws = aws[each.value]
  }

  bucket = "${terraform.workspace}-${each.value}"
}
```

### Proposal

Allow module invocations to select providers dynamically as in the example.

Note that repeating the module invocations manually is not really a workaround, as there is no module.buckets resource that contains all the created bucket, e.g., that could be used for setting up replication groups.

**Comment by crw** [comment] 2023-07-12 22:25
Thanks for this request! I believe this is a duplicate of https://github.com/hashicorp/terraform/issues/24476. If this looks correct, please let me know.

**Comment by crw** [comment] 2023-07-14 21:04
Indeed, this is a duplicate of #24476. Thanks!

**Closed by crw** 2023-07-14 21:04 UTC
Labels: enhancement, new
