### ISSUE TITLE
Dependencies between instances of the same for_each

### ISSUE THREAD

**Issue by marino-serna** [hashicorp/terraform#31325] opened 2022-06-27 16:43 UTC
### Current Terraform Version

1.2.3

### Use-cases
Deploy a list of elements that are dependent of each-other.

For example, to deploy a list of views from BigQuery, of which some the views read from other views. It is not possible to create some of the views until the rest views are ready.

I have similar examples with other resources, but this is the simplest.

### Attempted Solutions

I have tried to include a dynamic dependency in the depends_on, but only static lists are allowed

`depends_on = [google_bigquery_dataset.sub-product-dataset, google_bigquery_table.tables, google_bigquery_table.views[each.value.depends_on].id]
`
I have tried to include a false dependency, that is not use but require the previous step to be process:

`description = true? each.value.view_description : (join(", ", [for view in each.value.depends_on: google_bigquery_table.views[view].id]))`

but a cycle error is provided:

Error: Cycle: google_bigquery_table.views["basic_view"], google_bigquery_table.views["basic_view_2"]

Which only make sense if terraform ignore the instances and wait for the full component -also match some comments that I read about it-

```
resource "google_bigquery_table" "views" {
  depends_on = [google_bigquery_dataset.sub-product-dataset, google_bigquery_table.tables]
  // depends_on = [google_bigquery_dataset.sub-product-dataset, google_bigquery_table.tables, google_bigquery_table.views[each.value.depends_on].id]
  for_each = var.views
  dataset_id = google_bigquery_dataset.sub-product-dataset.dataset_id
  table_id = each.value.view_name

  //description = each.value.view_description
  description = true? each.value.view_description : (join(", ", [for view in each.value.depends_on: google_bigquery_table.views[view].id]))

  labels = local.labels
  deletion_protection = false

  view{
    query = data.local_file.views[each.key].content
    use_legacy_sql = false
  }
}
```

```
views = {
"example_1_view" = {
    view_name = "example_1_view"
    view_description = "Fake view used as an example of a basic view"
    view_query_path = "sql/example_1_view.sql"
    // depends_on = "None"
    depends_on = []
},
"example_view_2" = {
    view_name = "example_view_2"
    view_description = "Fake view used as an example of a basic view with dependencies"
    view_query_path = "sql/example_view_2.sql"
    // depends_on = "example_1_view"
    depends_on = ["example_1_view"]
},
}
```

### Proposal
Make the dependencies dependent of each instance, instead of each block of code.

It is ok for me to use either the first solution, cleaner and more elegant but limited to one element, or the second trick but at least to have a functional alternative that don’t require to create one component for each view (instead of the array).

**Comment by jbardin** [comment] 2022-06-27 16:54
Duplicate of #23735

**Closed by jbardin** 2022-06-27 16:54 UTC
Labels: enhancement, new
