### ISSUE TITLE
Error: Too many server_side_encryption_configuration blocks

### ISSUE THREAD

**Issue by anauecuri** [hashicorp/terraform#28087] opened 2021-03-15 13:11 UTC
Hi everyone,

Trying to run a pipeline using Jenkins and now I am receiving the error below:

```
[1m[31mError: [0m[0m[1mToo many server_side_encryption_configuration blocks[0m

[0m  on  line 0:
  (source code not available)

No more than 1 "server_side_encryption_configuration" blocks are allowed
```

I am not using dynamic block for this...my code is as follows below:

```
resource "aws_s3_bucket" "site" {
  bucket = "brb-miniapp-service-recharge-${var.env}"
  acl    = "private"
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}
```

I am doing the same for other systems here and all of them ran without any problem.

My code has not any duplicate block regarding server_side_encryption and I guess this must be a bug...

I also tried to delete my workspace and recreated again but without success.

**Comment by jbardin** [comment] 2021-03-15 14:39
Hi @anauecuri,

Unfortunately it's not possible to debug this issue with the information provided. Please add the versions of terraform and providers being used, as well as all the necessary configuration to recreate the issue. If you are not using the latest releases, please check if the issue is resolved with updated versions as well.

Thanks!

**Comment by anauecuri** [comment] 2021-03-15 16:15
Hi @jbardin , thanks for yor time!
See below the configuration regarding the service with error.
I am using provider.aws: version = "~> 3.32" and Terraform 0.12

cloudfront config
`resource "aws_cloudfront_origin_access_identity" "origin_access_identity" {
  comment = "cloudfront origin access identity"
}
resource "aws_cloudfront_distribution" "website_cdn" {
  enabled      = true
  price_class  = (var.env == "prd" ? "PriceClass_All" : "PriceClass_100")
  http_version = "http1.1"
  aliases      = ["${var.aliases}"]
  origin {
    origin_id   = "origin-bucket-${aws_s3_bucket.site.id}"
    domain_name = "brb-frontend-static-${var.env}.s3.${var.region}.amazonaws.com"
    s3_origin_config {
      origin_access_identity = "${aws_cloudfront_origin_access_identity.origin_access_identity.cloudfront_access_identity_path}"
    }
  }
  
  default_root_object = "index.html"

  logging_config {
    include_cookies = true
    bucket          = "${aws_s3_bucket.log.bucket_domain_name}"
    prefix          = "cdn"
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "origin-bucket-${aws_s3_bucket.site.id}"
    min_ttl          = "0"
    default_ttl      = "3600"  //3600
    max_ttl          = "86400" //86400
    // This redirects any HTTP request to HTTPS. Security first!
    viewer_protocol_policy = "allow-all"
    compress               = true
    forwarded_values {
      query_string = true
      cookies {
        forward = "none"
      }
    }
  }
  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }
  viewer_certificate {
    acm_certificate_arn = "${data.aws_acm_certificate.cert.arn}"
    ssl_support_method  = "sni-only"
    cloudfront_default_certificate = true
    minimum_protocol_version = "TLSv1.2_2019"
  }
}
output "cdn_output" {
  value = "${aws_cloudfront_distribution.website_cdn.domain_name}"
}
output "cdn_id" {
  value = "${aws_cloudfront_distribution.website_cdn.id}"
}

resource "null_resource" "site_files" {
 triggers = {
   build_number = "${timestamp()}"
 }
 provisioner "local-exec" {
   command = "/usr/local/bin/aws s3 sync ../application/dist/hyaku/ s3://brb-frontend-static-${var.env}/ --profile ${var.profile}"
 }
 provisioner "local-exec" {
   command = "/usr/local/bin/aws cloudfront create-invalidation --distribution-id ${aws_cloudfront_distribution.website_cdn.id} --paths '/*' --profile ${var.profile}"
 }

}`

S3 config
`data "aws_iam_policy_document" "s3_policy" {
  statement {
    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.site.arn}/*"]

    principals {
      type        = "AWS"
      identifiers = ["${aws_cloudfront_origin_access_identity.origin_access_identity.iam_arn}"]
    }
  }

  statement {
    actions   = ["s3:ListBucket"]
    resources = ["${aws_s3_bucket.site.arn}"]

    principals {
      type        = "AWS"
      identifiers = ["${aws_cloudfront_origin_access_identity.origin_access_identity.iam_arn}"]
    }
  }
}

resource "aws_s3_bucket_policy" "s3_policy" {
  bucket = "${aws_s3_bucket.site.id}"
  policy = "${data.aws_iam_policy_document.s3_policy.json}"
}

resource "aws_s3_bucket" "site" {
  bucket = "brb-frontend-static-${var.env}"
  acl    = "private"
  server_side_encryption_configuration {
     rule {
       apply_server_side_encryption_by_default {
         sse_algorithm = "AES256"
       }
     }
   }
  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "POST"]
    allowed_origins = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

resource "aws_s3_bucket" "log" {
  bucket = "brb-frontend-static-${var.env}-logs"
  acl    = "log-delivery-write"
  server_side_encryption_configuration {
     rule {
       apply_server_side_encryption_by_default {
         sse_algorithm = "AES256"
       }
     }
   }
  lifecycle_rule {
      id      = "seven_days_retention"
      prefix  = "cdn/"
      enabled = true

      expiration {
          days = 7
      }
  }
}`

ACM config
`data "aws_acm_certificate" "cert" {
  provider = "aws"
  domain   = "${var.domain}"
  statuses = ["ISSUED"]
  most_recent = true
}`

Route 53 config
`data "aws_route53_zone" "primary" {
  name         = "${var.domain}"
  private_zone = false
}

resource "aws_route53_record" "web" {
  zone_id = "${data.aws_route53_zone.primary.zone_id}"
  name    = "web.${data.aws_route53_zone.primary.name}"
  type    = "CNAME"
  ttl     = "5"
  records        = ["${aws_cloudfront_distribution.website_cdn.domain_name}"]
}
`

Please, do not hesitate in contact me for further information.

**Comment by jbardin** [comment] 2021-03-15 17:12
Thanks for the extra configuration @anauecuri. I agree the configuration does not look like it should be able to cause this error, so I suspect this is an issue that is happening in combination with some unexpected behavior from the provider as well. There have been a lot of changes to Terraform since 0.12, and many fixes specifically related to block validation. Can you verify that this is still a problem in the current release?

Thanks!

**Comment by anauecuri** [comment] 2021-03-15 17:59
@jbardin , thanks again for your reply ... I will try to use the current version and check if the problem desappears.
Just for you know ... I have similar configuration to other services and all of them are running as expected.
I also tried to remove the server_side_encryption_configuration configuration block and I received the same error.
I suspect that might be a cache issue.
Anyway, I will return to you soon with the result of the use of the current version.

**Comment by anauecuri** [comment] 2021-03-16 11:49
Hi @jbardin , unfortunately my manager did not allow me to upgrade terraform version because this may impact other services so we need to evaluate the risks to do this.
So based on my last message can you check if there is something else that we can consider besides the version upgrade?

**Comment by jbardin** [comment] 2021-03-16 16:13
Until I have a reproduction it's hard to say what could be going on here, and I don't yet see a way to reproduce it. Judging by the type of error, I would bet there's a good chance it's fixed in newer version of Terraform, which means we first have to reproduce this in 0.12 to be certain. 

If the state is somehow corrupt, possible caused by a bug in an even older version of terraform, you could refresh the state and see if that helps. You may also want to inspect the state manually and see what that block actually contains, which should   only be:

```
          "server_side_encryption_configuration": [
            {
              "rule": [
                {
                  "apply_server_side_encryption_by_default": [
                    {
                      "kms_master_key_id": "",
                      "sse_algorithm": "AES256"
                    }
                  ]
                }
              ]
            }
          ],
```

**Comment by Tbohunek** [comment] 2021-04-07 09:48
@anauecuri could you give us `terraform state show aws_s3_bucket.site` (make sure to anonymize it)?

**Comment by jbardin** [comment] 2021-05-14 13:57
We have not heard back in a while, so I'm going to close this out. If this turns out to be reproducible with the latest Terraform release, please feel free to update the issue or open a new issue with all the requested information.

Thanks!

**Closed by jbardin** 2021-05-14 13:57 UTC
Labels: bug, v0.12, waiting for reproduction
