### ISSUE TITLE
Terraform v0.14.0 Panic with templatefile and sensitive variable

### ISSUE THREAD

**Issue by DarkMukke** [hashicorp/terraform#27253] opened 2020-12-11 06:12 UTC
It worked fine before i marked a variable as sensitive, not sure if the panic is related. 

### Terraform Version
```
v0.14.0
```

### Crash Output
```
Error: Error in function call

  on ../vault-config/helm.tf line 9, in resource "helm_release" "vault_config":
   9:     templatefile("${path.module}/values.yaml.tpl", {
  10:       node_selector = var.node_selector
  11:       cluster_name = var.cluster_name
  12:       extra_args = var.extra_args
  13:       image = format("%s:%s", var.terraform_image, var.terraform_tag)
  14:       consul_acl_token = var.consul_acl_token
  15:     })
    |----------------
    | path.module is "../vault-config"
    | var.cluster_name is "hb-mvp-ruben"
    | var.consul_acl_token is (sensitive value)
    | var.extra_args is "-var  dynamodb_role_arn='arn:aws:iam::123456789:role/vault_dynamodb20200715145628837100000001 -var dynamodb_role_name='vault_dynamodb20200715145628837100000001' -var         aws_region='eu-west-2'"
    | var.node_selector is "base"
    | var.terraform_image is "123456789.dkr.ecr.eu-west-2.amazonaws.com/terraform"
    | var.terraform_tag is "light"

Call to function "templatefile" failed: panic in function implementation:
value is marked, so must be unmarked first
goroutine 3113 [running]:
runtime/debug.Stack(0xc002473d68, 0x2f6d360, 0x37a3a70)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/zclconf/go-cty/cty/function.errorForPanic(...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/error.go:44
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues.func1(0xc002474780,
0xc002474790)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/function.go:217
+0x7f
panic(0x2f6d360, 0x37a3a70)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.AsString(0x384a680, 0xc000050400,
0x3142500, 0xc000f85bc0, 0x384a680, 0xc000050400)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/value_ops.go:1229 +0x4f
github.com/hashicorp/hcl/v2/hclsyntax.(*TemplateExpr).Value(0xc0006cfbc0,
0xc00226eb20, 0x3423b44, 0xa, 0xc00228f9d8, 0x1, 0x0, 0xf, 0x10)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression_template.go:83
+0xcc5
github.com/hashicorp/terraform/lang/funcs.MakeTemplateFileFunc.func2(0x3849380,
0xc0006cfbc0, 0x384a780, 0xc0022508c0, 0x304d3a0, 0xc002263140, 0x0, 0x0,
0x384a680, 0xc000050400, ...)
        /home/circleci/project/project/lang/funcs/filesystem.go:145 +0x66a
github.com/hashicorp/terraform/lang/funcs.MakeTemplateFileFunc.func3(0xc00222c440,
0x2, 0x2, 0x49312d0, 0xc00230c5d0, 0x0, 0x0)
        /home/circleci/project/project/lang/funcs/filesystem.go:169 +0x1d2
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues(0xc002231b90,
0xc00222c440, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/function.go:221
+0x454
github.com/zclconf/go-cty/cty/function.Function.Call(0xc002231b90,
0xc00222c440, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/function.go:228
+0xb5
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc00137e5a0,
0xc00226e220, 0x1, 0xc00226e880, 0xc002262ff0, 0x18, 0x18, 0x1013cdd,
0xc001597768)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:412
+0x10c5
github.com/hashicorp/hcl/v2/hclsyntax.(*TupleConsExpr).Value(0xc000d8b900,
0xc00226e220, 0x0, 0x6, 0xc0033ddc38, 0xc000ad4101, 0x3342ac0, 0xc00226e860,
0x2f6d360)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:712
+0xf0
github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc001de0960,
0xc000a90e40, 0x0, 0x0, 0x0, 0xc00226e220, 0x384a680, 0xc000050400, 0x0, 0x0,
...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/spec.go:205 +0x2ac
github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc00131d3b0,
0xc000a90e40, 0x0, 0x0, 0x0, 0xc00226e220, 0xc00086aed0, 0x20, 0x20,
0xc00226e260, ...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/spec.go:79 +0x237
github.com/hashicorp/hcl/v2/hcldec.decode(0x3849600, 0xc00226e260, 0x0, 0x0,
0x0, 0xc00226e220, 0x384a440, 0xc00131d3b0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/decode.go:21 +0x11b
github.com/hashicorp/hcl/v2/hcldec.Decode(...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/public.go:15
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc003347c70,
0x3848e80, 0xc002231c50, 0xc000b012f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/circleci/project/project/lang/eval.go:67 +0x2ac
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc002ad9520,
0x3848e80, 0xc002231c50, 0xc000b012f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/circleci/project/project/terraform/eval_context_builtin.go:280 +0x1ad
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc002477a98,
0x3885cc0, 0xc002ad9520, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval_diff.go:156 +0x27c
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0014cf320,
0x3885cc0, 0xc002ad9520, 0x0, 0x40000)
        /home/circleci/project/project/terraform/node_resource_plan_instance.go:207
+0x58d
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc0014cf320,
0x3885cc0, 0xc002ad9520, 0xc00252a002, 0x309ac60, 0x33aa5e0)
        /home/circleci/project/project/terraform/node_resource_plan_instance.go:39
+0xd2
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc0023ae5b0,
0x3885cc0, 0xc002ad9520, 0xf1fbc80, 0xc0014cf320, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x33aa5e0,
0xc0014cf320, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000b790e0,
0x33aa5e0, 0xc0014cf320, 0xc0020bb000)
        /home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x1246
.
```

But then running a separate test 

`test.tf`
```terraform
variable "my_name" {
  type = string
}

variable "my_password" {
  type = string
  sensitive = true
}

resource "local_file" "test" {
  filename = "name.txt"
  content = templatefile("test.tpl", {
    the_password = var.my_name
  })
}

resource "local_file" "test_senssitive" {
  filename = "text.txt"
  content = templatefile("test.tpl", {
    the_password = var.my_password
  })
}
```

`test.tpl`
```hcl
${the_password}
```

Works fine, so i don't get it.

When I remove the `sensitive = true` from the variable definition, it works fine.

**Comment by alisdair** [comment] 2020-12-11 15:25
Hi @DarkMukke, thanks for reporting this.

Like you, I was unable to reproduce the bug with the configuration you gave. From reading the stack trace, I think this is most likely a case of doubly-marked variables: a `sensitive` variable set as an input to a module with a `sensitive` variable. That bug was fixed in #27131, released as part of 0.14.1.

This allowed me to reproduce the same crash with 0.14.0 and the following configuration.

main.tf

```hcl
variable "password" {
  type = string
  sensitive = true
  default = "password"
}

module "tmpl" {
  source = "./tmpl"
  password = var.password
}
```

tmpl/main.tf

```hcl
variable "password" {
  type = string
  sensitive = true
}

resource "local_file" "test" {
  filename = "${path.module}/test.txt"
  content = templatefile("${path.module}/test.tpl", {
    password = var.password
  })
}
```

tmpl/test.tpl

```hcl
${password}
```

Can you try upgrading to the 0.14.2 release and see if the issue is fixed for you?

**Comment by DarkMukke** [comment] 2020-12-14 08:46
Spot on on the sensitive chain, i should have explained it better, it was a sensitive value in a wrapper module that was calling another module that also had the variable set as sensitive.

Testing with v0.14.2 it works as expected.

**Closed** 2020-12-14 08:46 UTC
Labels: bug, crash, explained, new, v0.14

**Comment by schnerring** [comment] 2021-01-04 05:54
I'm on v0.14.3 and reproduced the error:

Given the file `main.tf`:

```
variable "k3os" {
  type = object({
    k3s_args            = list(string)
    ssh_authorized_keys = list(string)
  })
  default = {
    k3s_args            = []
    ssh_authorized_keys = []
  }
  sensitive = true
}

output "k3os" {
  value     = templatefile("./k3os.tpl.yaml", { k3os = var.k3os })
  sensitive = true
}
```

and `k3os.tpl.yaml`:

```
k3os:
  k3s_args:
    - server
%{ if length(k3os.k3s_args) > 0 }
  %{ for k3s_arg in k3os.k3s_args ~}
    - ${k3s_arg}
  %{ endfor ~}
%{ endif }
```

I get the error:

```
Error: Error in function call

  on main.tf line 14, in output "template":
  14:   value = templatefile(
  15:     "./template.tpl.yaml",
  16:     {
  17:       k3os = var.k3os
  18:     }
  19:   )
    |----------------
    | var.k3os is (sensitive value)

Call to function "templatefile" failed: panic in function implementation:
value is marked, so must be unmarked first
goroutine 85 [running]:
runtime/debug.Stack(0xc000a6ee98, 0x237d540, 0x2bb5840)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/zclconf/go-cty/cty/function.errorForPanic(...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/function/error.go:44
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues.func1(0xc000a701f8,
0xc000a70208)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/function/function.go:217
+0x7f
panic(0x237d540, 0x2bb5840)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.ElementIterator(0x2c5c400, 0xc000a54ba0,
0x2551bc0, 0xc000a54be0, 0x2551b01, 0xc000a54be0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/value_ops.go:1111 +0x4f
github.com/hashicorp/hcl/v2/hclsyntax.(*TemplateJoinExpr).Value(0xc00009fa00,
0xc000a54440, 0x2, 0x2, 0x0, 0x0, 0x237d540, 0xc00009f9b0, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.1/hclsyntax/expression_template.go:156
+0x190
github.com/hashicorp/hcl/v2/hclsyntax.(*TemplateExpr).Value(0xc000a59e60,
0xc000a54440, 0x2428b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x18)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.1/hclsyntax/expression_template.go:33
+0x157
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc0001db730,
0xc000a54440, 0xd, 0xd, 0x0, 0x0, 0x237d540, 0xc00009f970, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.1/hclsyntax/expression.go:546
+0x59
github.com/hashicorp/hcl/v2/hclsyntax.(*TemplateExpr).Value(0xc000a59f80,
0xc000a54440, 0x2829346, 0x5, 0xc000a751c0, 0x1, 0x0, 0x5, 0x8)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.1/hclsyntax/expression_template.go:33
+0x157
github.com/hashicorp/terraform/lang/funcs.MakeTemplateFileFunc.func2(0x2c5af80,
0xc000a59f80, 0x2c5c380, 0xc00009f8b0, 0x245cee0, 0xc000a50780, 0x0, 0x0, 0x0,
0x0, ...)
        /home/circleci/project/project/lang/funcs/filesystem.go:145 +0x66a
github.com/hashicorp/terraform/lang/funcs.MakeTemplateFileFunc.func3(0xc000a01140,
0x2, 0x2, 0x3d43538, 0xc0009f2048, 0x0, 0x0)
        /home/circleci/project/project/lang/funcs/filesystem.go:169 +0x1d2
github.com/zclconf/go-cty/cty/function.Function.ReturnTypeForValues(0xc000a50330,
0xc000a01140, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/function/function.go:221
+0x454
github.com/zclconf/go-cty/cty/function.Function.Call(0xc000a50330,
0xc000a01140, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/function/function.go:228
+0xb5
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0008bc2d0,
0xc000a54120, 0x0, 0xc0009f3900, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.1/hclsyntax/expression.go:442
+0x10c5
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0000b55e0, 0x2c5ae00,
0xc0008bc2d0, 0x2c5c2c0, 0x3d43538, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/circleci/project/project/lang/eval.go:171 +0x1b7
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc000a4e340,
0x2c5ae00, 0xc0008bc2d0, 0x2c5c2c0, 0x3d43538, 0x0, 0x0, 0x66, 0x400, 0x66,
...)
        /home/circleci/project/project/terraform/eval_context_builtin.go:287 +0xbb
github.com/hashicorp/terraform/terraform.(*NodeApplyableOutput).Execute(0xc000a00c00,
0x2c97980, 0xc000a4e340, 0xc00003a002, 0x24aa880, 0x2683e80)
        /home/circleci/project/project/terraform/node_output.go:273 +0x60d
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000a03a00,
0x2c97980, 0xc000a4e340, 0x7fd769b0d248, 0xc000a00c00, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2683e80,
0xc000a00c00, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000a414a0,
0x2683e80, 0xc000a00c00, 0xc000a00fc0)
        /home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x1246
.
```

The error only seems to occur for `object` type variables that are `sensitive`. Without `object`s, it works:

```
variable "password" {
  default   = "secret"
  sensitive = true
}

output "password" {
  value     = templatefile("./password.tpl.yaml", { password = var.password })
  sensitive = true
}
```

```
${password}
```

**Comment by alisdair** [comment] 2021-01-04 19:05
@schnerring Thanks for your additional report. I believe that is a duplicate of #27336, which has a pending fix in the upstream library.
