### ISSUE TITLE
for_each invalid argument on destroy, for already destroyed resources

### ISSUE THREAD

**Issue by phyber** [hashicorp/terraform#32221] opened 2022-11-15 13:43 UTC
### Terraform Version

```shell
Terraform v1.3.4
on linux_amd64
```

### Terraform Configuration Files

```terraform
# Code taken from AWS ACM validation example, since actual module is just doing this.
# It's hard to come up with a real test with an object that applies successfully but fails to destroy, sorry.

resource "aws_acm_certificate" "example" {
  domain_name       = "example.com"
  validation_method = "DNS"
}

data "aws_route53_zone" "example" {
  name         = "example.com"
  private_zone = false
}

resource "aws_route53_record" "example" {
  for_each = {
    for dvo in aws_acm_certificate.example.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = data.aws_route53_zone.example.zone_id
}

resource "aws_acm_certificate_validation" "example" {
  certificate_arn         = aws_acm_certificate.example.arn
  validation_record_fqdns = [for record in aws_route53_record.example : record.fqdn]
}
```

### Debug Output

It's not easy for me to share the whole output (because business restrictions), but I've included what I believe is related to the issue. Feel free to ask for other segments.

https://gist.github.com/phyber/6e157cc33726e5d29cf8152e5450cb40

### Expected Behavior

Terraform should have been able to plan a follow-up destroy correctly.

### Actual Behavior

Terraform complains about the `for_each` value only being known after apply, for resources that were already destroyed.

### Steps to Reproduce

1. Successfully apply some Terraform with AWS Route 53 domain validation and some additional Terraform resources.
2. Destroy the infrastructure
   - Have something in the infrastructure fail to destroy after the ACM and associated Route 53 resources were successfully destroyed, in our case, some unrelated Kubernetes resource failed to destroy
3. Attempt to plan a destroy again
4. Terraform should now complain about the _already destroyed_ `aws_route53_record` resources that use the `for_each`

### Additional Context

Terraform is running via Terraform Cloud, and the state is being managed there. I have confirmed that the resources being complained about are no longer in the state after they were successfully destroyed. The cause of the destroy plan failing was an unrelated Kubernetes resource error.

After this no Route 53 resources are present in the state, but attempting another destroy plan makes Terraform complain about the `for_each` argument of resources that were already successfully destroyed.

I would have expected Terraform to be smart enough to realise those resources are no longer in the state, that the `for_each` no longer matters, and to continue planning to destroy the resources that really are still in the state.

**Comment by jbardin** [comment] 2022-11-15 13:45
Thanks for filing issue @phyber!
Closing as duplicate of #32185

**Closed by jbardin** 2022-11-15 13:45 UTC
Labels: bug, new

**Comment by phyber** [comment] 2022-11-15 13:48
Thanks for the pointer to the other issue, I did search before hand but my search-foo failed me :)
