### ISSUE TITLE
Minimum and maximum healthy percent options for aws_ecs_service

### ISSUE THREAD

**Issue by anosulchik** [hashicorp/terraform#4949] opened 2016-02-02 10:44 UTC
Looks like terraform aws_ecs_service resource doesn't support min and max healthy percent:

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-service.html
https://www.terraform.io/docs/providers/aws/r/ecs_service.html

These options are pretty much important to control deployment flow and make sure that certain number of containers are serving traffic during deployment of new version. AWS makes it possible to set these values either during ecs service creation or during its update (e.g. when new revision of task definition is specified for service).

Thank you!

**Comment by radeksimko** [comment] 2016-02-02 11:17
I'm going to close this one as a duplicate of https://github.com/hashicorp/terraform/issues/4456

Reopen if you disagree. :wink:

**Closed by radeksimko** 2016-02-02 11:17 UTC
Labels: enhancement, provider/aws
