### ISSUE TITLE
Terraform refresh leave holes that terraform count try to fill by destroying and recreating resources.

### ISSUE THREAD

**Issue by michaelcourcy** [hashicorp/terraform#21292] opened 2019-05-13 23:18 UTC
### Terraform Version

```
terraform -v
Terraform v0.11.8
+ provider.aws v1.38.0

Your version of Terraform is out of date! The latest version
is 0.11.13. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files

```hcl
esource "aws_instance" "ose_node_app" {
  count         = "${local.instance_number["app_node"]}"
  ami           = "${data.aws_ami.redhat.id}"
  instance_type = "${local.instance_type["app_node"]}"
  //iam_instance_profile = "${aws_iam_instance_profile.node_profile.id}"

  subnet_id         = "${element(aws_subnet.openshift_subnet.*.id, count.index)}"
  availability_zone = "${element(var.azs, count.index)}"

  vpc_security_group_ids = ["${local.app_node}"]
  //key_name = "${aws_key_pair.openshift_terraform.id}"
  key_name          = "${var.openshift_terraform_key_name}"
  source_dest_check = false


  root_block_device {
    volume_size = 20
    volume_type = "gp2"
  }

  tags = "${merge(
    local.common_tags,
    map(
    "Name"          ,"ose-apps-${element(var.azs, count.index)}-${var.env}" ,
    "OpenShiftType" , "node-app" 
    )
  )}"
}
```

### Expected Behavior
We destroy manually some nodes, we decrease the count according to the new number and  did a terraform refresh to realign the state. We expect then that running a terraform plan lead to "nothing to change"

### Actual Behavior
But we saw this instead
```
+ aws_instance.ose_node_app[9]
+ aws_instance.ose_node_app[10]
+ aws_instance.ose_node_app[12]
+ aws_instance.ose_node_app[15]
+ aws_instance.ose_node_app[16]
+ aws_instance.ose_node_app[17]
 
……
 
  - aws_instance.ose_node_app[27]
  - aws_instance.ose_node_app[28]
  - aws_instance.ose_node_app[29]
  - aws_instance.ose_node_app[39]
  - aws_instance.ose_node_app[41]
  - aws_instance.ose_node_app[43]
```

Obviously terraform does not like the holes that refresh leave in the tfstate. And it try to recreate a sequential array of instance by destroying the higher index and recreating the lower.   

### Steps to Reproduce
1. Create a 3 instance 1, 2 and 3 with count 
2. remove 2 using aws console 
3. Refresh the state 
4. Run terraform plan, 3 will be destroyed the 2 will be created

**Comment by apparentlymart** [comment] 2019-07-12 00:35
Hi @michaelcourcy! Sorry for this annoying behavior.

Terraform tracks individual instances by index, so unfortunately what you saw here is intended behavior, although indeed it is annoying in the specific case where you're trying to shrink a set of instances while keeping ones later in the list.

The answer for this today is to explicitly tell Terraform your intentions by running `terraform state mv`. For example:

```
terraform state mv aws_instance.ose_node_app[27] aws_instance.ose_node_app[9]
terraform state mv aws_instance.ose_node_app[28] aws_instance.ose_node_app[10]
terraform state mv aws_instance.ose_node_app[29] aws_instance.ose_node_app[11]
etc, etc
```

These commands tell Terraform that it should use the new lower indices to refer to these objects, which changes the default behavior of assuming that you want to delete them because their indices are greater than or equal to the count.

The future better fix for this is described in #17179: that feature will allow you to instead give each instance its own name, independent of the others, and so changes to the number of instances will be reflected by adding and removing instances by name, rather than by renumbering. The `count` feature is built under the assumption that all of your instances are equivalent and so deleting just the last one is equivalent to deleting any other one, while `for_each` gives you more control over how Terraform tracks each one and thus more control over what Terraform will create, update, and delete when the number changes.

Since #17179 is already covering the `for_each` feature, and since what you've described here is `count` working as intended (annoying as that might be for your specific situation), I'm going to close this out just to consolidate the discussion into #17179. The resource `for_each` feature is being implemented right now, so it'll be included in a near future release.

**Closed by apparentlymart** 2019-07-12 00:35 UTC
