### ISSUE TITLE
Web identity authentication support for S3 module

### ISSUE THREAD

**Issue by melcloud** [hashicorp/terraform#26292] opened 2020-09-18 11:27 UTC
### Current Terraform Version

```
$ terraform --version
Terraform v0.13.3
```

### Use-cases
We currently uploads private Terraform modules to S3 bucket for internal usage. During `terraform init`, modules are downloaded from S3 through ec2 instance metadata. Recently, we switched build agent to EKS and use `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` to allow build agent to assume role with correct permissions. This works great for `terraform plan` and `terraform apply`. However, terraform failed to download modules from S3 because S3 module source doesn't support web identity based assume role.

### Attempted Solutions
We currently have customised script which calls aws cli to assume role manually during `terraform init`. 

### Proposal
Terraform S3 module source should support AWS Web identity assume role. This is available for all other terraform operations

### References
The backend assume role seems to be addressed by [this commit](https://github.com/hashicorp/terraform/commit/8f430b4b1e633ba6c1f549312a031c12dd525313). Maybe the same should be done for S3 module source?

**Comment by sdwerwed** [comment] 2021-03-17 14:53
@melcloud same for use using terraform in eks for atlantis, did you find any solution to this?

**Comment by md5** [comment] 2022-08-24 15:43
This functionality is handled in the `go-getter` module. Here is a related issue in that module, which is where I believe this would actually need to be fixed: https://github.com/hashicorp/go-getter/issues/313

**Comment by md5** [comment] 2022-08-24 15:44
From that issue on `go-getter`, it looks like this issue may actually be a duplicate of https://github.com/hashicorp/terraform/issues/28101 (or vice versa)

**Comment by crw** [comment] 2022-08-26 01:07
Agreed, closing as duplicate of #28101. Thanks @md5!

**Closed by crw** 2022-08-26 01:07 UTC
Labels: enhancement, modules, duplicate
