### ISSUE TITLE
Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.

### ISSUE THREAD

**Issue by MotorCityCobra** [hashicorp/terraform#32917] opened 2023-03-25 02:00 UTC
### Terraform Version

```shell
Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.
```

### Terraform Configuration Files

The most recent in 1.4.2

### Debug Output

Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.

### Expected Behavior

No error

### Actual Behavior

Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment] 2023-03-27 12:45
Duplicate of #24168

**Closed by jbardin** 2023-03-27 12:45 UTC
Labels: bug, new
