### ISSUE TITLE
null_resource is being triggered without any changes in the instance.

### ISSUE THREAD

**Issue by debojitkakoti** [hashicorp/terraform#21295] opened 2019-05-14 08:30 UTC
### Terraform Version

```
Terraform v0.11.13
```

### Terraform Configuration Files

```hcl
resource "aws_instance" "scylla" {
	ami = "${local.scylla_ami}"
	instance_type = "${var.aws_instance_type}"
	key_name = "${var.key_pair_name}"
	monitoring = true
	availability_zone = "${element(local.aws_az, count.index % length(local.aws_az))}"
	subnet_id = "${element(var.subnet_ids, count.index)}"
	user_data = "${format(join("\n", var.scylla_args), local.cluster_name)}"

	vpc_security_group_ids = ["${aws_security_group.cluster.id}"]

	credit_specification {
		cpu_credits = "unlimited"
	}

	tags = "${merge(local.aws_tags, map("type", "scylla"))}"
	count = "${var.cluster_count}"

	depends_on = [
		"aws_security_group.cluster"
	]
}


resource "null_resource" "scylla_schema" {
	triggers {
		id = "${element(aws_instance.scylla.*.id, 0)}"
	}

	connection {
		type = "ssh"
		host = "${element(aws_instance.scylla.*.private_ip, 0)}"
		user = "centos"
		private_key = "${file("${var.private_key}")}"
		timeout = "5m"
	}

	provisioner "remote-exec" {
		inline = [
			"chmod +x /tmp/provision-scylla-schema.sh",
			"sudo /tmp/provision-scylla-schema.sh"
		]
	}

	depends_on = ["null_resource.scylla_start"]
}
```

### Expected Behavior
Created 2 instances and null_resource is being triggered, because  trigger is on first instance id
`triggers {
		id = "${element(aws_instance.scylla.*.id, 0)}"
	}` , then increase instances to 3, it should not trigger because there is no changes in the first instnce.

### Actual Behavior

The null_resouce is being triggered when I increase the instances count from 2 to 3 or 3 to 4, but there is no changes detected in the first instance.

**Comment by jbardin** [comment] 2019-05-16 01:15
Hi @debojitkakoti,

Sorry about the confusion here. This is the unfortunately the expected behavior in Terraform 0.11, because the result of `element(aws_instance.scylla.*.id, 0)` is unknown when planning, so Terraform needs to plan that the `null_resource` will be replaced. 

In 0.12, the improvements to the configuration language allow precise evaluation of the individual elements of the reference in the triggers value you have here, and it can determine when there is no change expected. You can see this with a simplified config by changing the count parameter:

```
resource "null_resource" "one" {
  count = 1
}

resource "null_resource" "two" {
  triggers = {
    id = null_resource.one[0].id
  }
}
```

Closing this since it's fixed in master and will be included in the next release.

**Closed by jbardin** 2019-05-16 01:15 UTC
