### ISSUE TITLE
With GCP, when updating an instance_group, do not remove manually-added instances

### ISSUE THREAD

**Issue by drich10** [hashicorp/terraform#11204] opened 2017-01-13 22:54 UTC
### Terraform Version
0.8.3

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance_group

It is surprising behavior to have this happen, especially if the instances section within the instance_group has not been provided. At the very least, it would be nice to be able to specify a "do not remove extra instances" configuration.

One use case for this is when setting up an infrastructure that will be dynamically spawning VMs and placing them in instance groups. When we update the infrastructure with `terraform apply`, those dynamically-spawned instances are removed and lose connectivity.

**Comment by Dnefedkin** [comment] 2017-01-27 18:54
@drich10  could you please clarify what do you mean by "manually-added instances"? 

Do you mean something outside of you google_compute_instance_group declaration? E.g. example below defines  instance-1 and instance-2 that are the part of demo instance group. So Terraform state is not aware of any additional instances that you might have added to the demo instance group outside of Terraform.

resource "google_compute_instance_group" "demo" {
  name        = "demo-unmanaged-instance-group"

  instances = [
    "${google_compute_instance.instance-1.self_link}",
    "${google_compute_instance.instance-2.self_link}"
  ]
 ...
}

**Comment by drich10** [comment] 2017-01-27 18:57
Yes exactly as you described @Dnefedkin

**Comment by paddyforan** [comment] 2017-01-30 07:18
Hey @drich10! Thanks for the bug report. By design, Terraform considers itself the sole owner of any resources in your state file, and happily (and intentionally!) undoes any changes made outside of Terraform to bring them back in line with your config.

That said, the fact that you didn't specify any instances for the instance group would mean, in my mind at least, that Terraform has no opinion about what the instances should look like, and shouldn't overwrite changes with a reality you never specified.

The actual implementation of the fix may be tricky--I'm not sure whether we have a way to tell whether `instances` is specified and empty, or whether it's just not specified--but I'll follow up on this and see if we can't get things working in a less surprising manner.

**Comment by drich10** [comment] 2017-01-30 23:40
@paddyforan sounds good to me!

Thanks so much 😄

**Comment by paddyforan** [comment] 2017-03-13 19:13
Hey there @drich10! Sorry for the long delay on a reply to this, I've been investigating and seeking feedback internally.

I'm also afraid I'm going to have to disagree with myself. The more I investigate this:

> That said, the fact that you didn't specify any instances for the instance group would mean, in my mind at least, that Terraform has no opinion about what the instances should look like, and shouldn't overwrite changes with a reality you never specified.

The more I'm convinced I was wrong. When you remove an attribute (like `instances`, in this case), Terraform interprets it as being set to an empty value. Originally I thought Terraform should ignore it, but I'm coming across more and more places where that offers a worse user experience. The big one is when you set an attribute, the obvious thing to do when setting it to the zero value is to just delete the attribute, but that would not actually unset the attribute if my logic above held. Similarly, a set-then-unset attribute would leave part of your infrastructure defined, but not in code anywhere, which breaks the Infrastructure as Code purpose of Terraform.

So after a lot of conversations and thinking about the user experience of this one, I'm going to have to say this is Terraform working as intended, and close with a wontfix. I don't, however, want to come across as arbitrarily declaring an end to the discussion. I'm open to reconsidering this issue further (I, clearly, am capable of making mistakes), so feel free to reply in the comments if you feel strongly about this. If you do, specific use cases that are not possible with Terraform because of this are an especially good argument to deploy. :) We're pretty UX-driven.

So! Going to close this now, but thank you for opening an issue, and for your patience. I'm sorry for the confusion around this, it's not an easy area to reason about UX in.

**Closed by paddyforan** 2017-03-13 19:13 UTC
Labels: bug, provider/google-cloud

**Comment by drich10** [comment] 2017-03-20 16:22
Totally understand, thanks for the thoughtful explanation! If I land on a more concrete/blocking use case I'll update here.
