### ISSUE TITLE
"diffs didn't match during apply" when updating ECS service

### ISSUE THREAD

**Issue by rbuels** [hashicorp/terraform#9055] opened 2016-09-26 15:12 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
### Terraform Version

0.7.4
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_ecs_service

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
### Terraform Configuration Files

https://www.dropbox.com/s/cz7n88ae79sy3k8/us-east-1.tech_products.tar.gz.crypt?dl=0
(encrypted with hashicorp gpg key)
### Debug Output

```
Please include the following information in your report:

    Terraform Version: 0.7.4
    Resource ID: aws_ecs_service.service.1
    Mismatch reason: attribute mismatch: task_definition
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"task_definition":*terraform.ResourceAttrDiff{Old:"arn:aws:ecs:us-east-1:397090398856:task-definition/precision-enrollment-INSERT-GREEN-TAG-HERE:18", New:"${element(aws_ecs_task_definition.service_task.*.arn,count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```
### Expected Behavior

A clean apply
### Actual Behavior

Error applying plan
### Steps to Reproduce

Hard to say, just seem to hit this sometimes when updating ECS service names.

**Comment by rbuels** [comment] 2016-09-26 15:15
One little factoid: if I do a terraform refresh, then apply again, the second apply completes without error.

**Comment by mitchellh** [comment] 2016-11-17 00:46
Hello! This should be fixed in later versions of Terraform. 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 00:46 UTC
Labels: bug, provider/aws
