### ISSUE TITLE
AWS ELB Cant Get Attribute

### ISSUE THREAD

**Issue by saulshanabrook** [hashicorp/terraform#2830] opened 2015-07-23 08:37 UTC
I have set up a route53 alias to point to an ELB, as [in the example](https://www.terraform.io/docs/providers/aws/r/route53_record.html). This worked great for creating it. However, I modified some parts of the records, and now when i try `terraform refresh` I get:

```
Error configuring: 12 error(s) occurred:

* Resource 'aws_elb.external' does not have attribute 'zone_id' for variable 'aws_elb.external.zone_id'
* Resource 'aws_elb.external' does not have attribute 'dns_name' for variable 'aws_elb.external.dns_name'
* Resource 'aws_elb.external' does not have attribute 'zone_id' for variable 'aws_elb.external.zone_id'
* Resource 'aws_elb.external' does not have attribute 'dns_name' for variable 'aws_elb.external.dns_name'
* Resource 'aws_elb.external' does not have attribute 'zone_id' for variable 'aws_elb.external.zone_id'
* Resource 'aws_elb.frontend' does not have attribute 'dns_name' for variable 'aws_elb.frontend.dns_name'
* Resource 'aws_elb.frontend' does not have attribute 'zone_id' for variable 'aws_elb.frontend.zone_id'
* Resource 'aws_elb.external' does not have attribute 'dns_name' for variable 'aws_elb.external.dns_name'
* Resource 'aws_elb.external' does not have attribute 'dns_name' for variable 'aws_elb.external.dns_name'
* Resource 'aws_elb.external' does not have attribute 'zone_id' for variable 'aws_elb.external.zone_id'
* Resource 'aws_elb.external' does not have attribute 'zone_id' for variable 'aws_elb.external.zone_id'
* Resource 'aws_elb.external' does not have attribute 'dns_name' for variable 'aws_elb.external.dns_name'
```

I am confused what the problem is, because it was able to create the route53 records correctly, using those variables.

**Comment by saulshanabrook** [comment] 2015-07-23 08:44
I tried deleting the ELBs and records manually and removing them from the state, so it has to recreate them, but I am getting the same error.

**Comment by saulshanabrook** [comment] 2015-07-23 08:48
OK I managed to work around this by removing all the route53 parts, creating the ELBs, then adding them back in. Then I didn't get that error.

This might have to do with the fact that I am creating the route53 items in a module, passing in the ELB info, like this:

```
module "first" {
  source = "./public-route"
  zone_id = "ddd"
  name = "domain.com"

  alias_name = "${aws_elb.external.dns_name}"
  alias_zone_id = "${aws_elb.external.zone_id}"
}

module "secnd" {
  source = "./public-route"
  zone_id = "ddd"
  name = "calls-api"

  alias_name = "${aws_elb.external.dns_name}"
  alias_zone_id = "${aws_elb.external.zone_id}"
}
```

**Comment by apparentlymart** [comment] 2015-07-23 15:50
Within the ``./public-route`` module, are you accessing these values as (e.g.) ``${var.alias_name}}`` rather than explicitly ``${aws_elb.external.dns_name}``? The resource namespace is separate for each module, so the child module only has access to the data passed in via its variables.

**Comment by saulshanabrook** [comment] 2015-07-24 21:30
Yes in the module I am accessing them as vars. It does work some of the time, like I mentioned in the previous comment, so the syntax is correct, it just fails on updating.

**Comment by appdynamics-ops** [comment] 2015-07-31 22:31
So, you have to create your environment, then create more of your environment, there's gotta be a better way than this. I'm having the same issue.

**Comment by josh-padnick** [comment] 2015-08-05 23:14
I can confirm we're having the same issue as well.  Even adding an explicit `depends_on = ["resource_type.resource_name"]` doesn't solve the problem.  This looks like a bug, and is potentially the same issue as reported in #2859 and #2583.  It appears related to modules.

I've been able to deterministically reproduce the bug as follows:

**Works fine:**
- Module A
  - Invokes Module B
    - Creates Resource 1

**Causes error:**
- Module A
  - Invokes Module B
    - Creates Resource 1
    - Invokes Module C
      -  with Parameter whose value is a property on Resource 1

Interestingly, there's even a param passed into Module A that now fails once I invoke Module C.

I can't share my Terraform templates publicly, but if a specific person wants to see them, I'd be happy to share.

**Comment by shanielh** [comment] 2015-08-31 07:42
@josh-padnick I managed to create a simple reproduction of the bug. 

[Debug log of destroy command](https://github.com/shanielh/terraform_module_bug/blob/master/main/debug.txt),

The repository contains everything needed for reproduction : 
https://github.com/shanielh/terraform_module_bug/tree/master/main

**Comment by trentonstrong** [comment] 2015-09-25 15:38
This issue effects us quite a bit and slows down development with Terraform, since the workarounds require a lot of commenting and manual state management.  

Would be willing to dive deeper on the issue if I could be pointed in the right direction!

**Comment by ajk8** [comment] 2016-08-23 18:06
It's now coming up on a year since the last comment, and I just hit this bug again (TF version 0.7.1).  In my case, I am not using variables, but directly accessing `aws_elb` resources which are _internal to the module_.  This prevents me from abstracting out repeated collections of resources into self-contained modules.  Instead what I have is hundreds of lines of copy-paste and find-and-replace (from `iam` all the way up through `route53`), which I would prefer to avoid.  Manual state management is a complete non-starter.  Any chance that we're going to see a fix?

**Comment by mitchellh** [comment] 2016-10-26 01:11
I ran the reproduction that @shanielh posted and I can confirm older versions failed but the latest Terraform version succeeds so this was fixed at some point. 

@ajk8 Could you open a new issue with a reproduction since the above repro is now fixed?

**Closed by mitchellh** 2016-10-26 01:11 UTC
Labels: bug, core

**Comment by guildencrantz** [comment] 2016-11-14 20:53
Did this break again? Because literally using the [Alias record](https://www.terraform.io/docs/providers/aws/r/route53_record.html) example is failing with `Terraform v0.7.10`.

```
mhenkel@C02RP5M7G8WP مثابرة ~/pfpt/src/efp-aws-kafka-zookeeper/kafka/t
cat t.tf
resource "aws_elb" "main" {
  name = "foobar-terraform-elb"
  availability_zones = ["us-east-1c"]

  listener {
    instance_port = 80
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
}

resource "aws_route53_record" "www" {
  zone_id = "${aws_route53_zone.primary.zone_id}"
  name = "example.com"
  type = "A"

  alias {
    name = "${aws_elb.main.dns_name}"
    zone_id = "${aws_elb.main.zone_id}"
    evaluate_target_health = true
  }
}
mhenkel@C02RP5M7G8WP مثابرة ~/pfpt/src/efp-aws-kafka-zookeeper/kafka/t
terraform plan
module root: 1 error(s) occurred:

* resource 'aws_route53_record.www' config: unknown resource 'aws_route53_zone.primary' referenced in variable aws_route53_zone.primary.zone_id
mhenkel@C02RP5M7G8WP مثابرة ~/pfpt/src/efp-aws-kafka-zookeeper/kafka/t
terraform -v                                                                                                                                                                                             ⏎
Terraform v0.7.10
```

**Comment by mitchellh** [comment] 2016-11-14 23:03
The example is just referencing something that doesn't exist for example reasons (our examples aren't fully complete cause it can require many more resources). In this case, you're referencing a non-existent zone.
