### ISSUE TITLE
Terraform crashes during Plan

### ISSUE THREAD

**Issue by rohanvirmani** [hashicorp/terraform#29743] opened 2021-10-12 19:16 UTC
### Terraform Version

```
Terraform version 0.14.5
...
```

### Terraform Configuration Files

```terraform
...
```

### Crash Output
2021/10/07 12:07:33 [TRACE] vertex "module.data.data.terraform_remote_state.pod_bootstrap": visit complete
2021/10/07 12:07:33 [TRACE] vertex "module.data.data.terraform_remote_state.pod_bootstrap": dynamic subgraph completed successfully
2021/10/07 12:07:33 [TRACE] vertex "module.data.data.terraform_remote_state.pod_bootstrap": visit complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x1a2fada]

goroutine 313 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Get(0xc0007681e0, 0x17, 0x2f66cfb, 0x1b)
	/home/circleci/project/project/backend/remote-state/azure/client.go:42 +0x17a
github.com/hashicorp/terraform/states/remote.(*State).refreshState(0xc0005503c0, 0x19, 0xc000c48e20)
	/home/circleci/project/project/states/remote/state.go:111 +0x3f
github.com/hashicorp/terraform/states/remote.(*State).RefreshState(0xc0005503c0, 0x0, 0x0)
	/home/circleci/project/project/states/remote/state.go:104 +0x73
github.com/hashicorp/terraform/builtin/providers/terraform.dataSourceRemoteStateRead(0x3365180, 0xc000872aa0, 0x2b63c40, 0xc001a79e30, 0x14, 0x5387d8ead, 0xc04fe4b149c16598, 0xc00084e100, 0xc000950000, 0xc000082080, ...)
	/home/circleci/project/project/builtin/providers/terraform/data_source_state.go:122 +0xa0f
github.com/hashicorp/terraform/builtin/providers/terraform.(*Provider).ReadDataSource(0xc000d2a800, 0xc0000494a0, 0x16, 0x3365180, 0xc000872aa0, 0x2b63c40, 0xc001a79e30, 0x33650c0, 0x4460a08, 0x0, ...)
	/home/circleci/project/project/builtin/providers/terraform/provider.go:80 +0x225
github.com/hashicorp/terraform/terraform.(*evalReadData).readDataSource(0xc000ad3a90, 0x33a1580, 0xc001a1c1a0, 0x3365180, 0xc000872680, 0x2b63c40, 0xc001a79d10, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/terraform/eval_read_data.go:115 +0xad5
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc000ad3a90, 0x33a1580, 0xc001a1c1a0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/eval_read_data_plan.go:107 +0x1267
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xc000ab4a20, 0x33a1580, 0xc001a1c1a0, 0x0, 0xc000950000)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:87 +0x4d4
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc000ab4a20, 0x33a1580, 0xc001a1c1a0, 0xc001a50002, 0x2bb16e0, 0x2ec0ca0)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:41 +0x13e
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc001cda0d0, 0x33a1580, 0xc001a1c1a0, 0x250302b1d98, 0xc000ab4a20, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xc3
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2ec0ca0, 0xc000ab4a20, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x97e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000172ae0, 0x2ec0ca0, 0xc000ab4a20, 0xc00122a1c0)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x1246

### Expected Behavior
Terraform should plan the data portion of our infrastructure code. It only happens in certain environments which all share the same code base.

First we deploy our release pipeline and TF panics and crashes like below. Afterwards we see the blob in Azure is locked and leased until we release the lock, re-run and the same scenario repeats itself.
---------------------
728Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2021-10-12T14:09:26.5047277Z ##[error][ d:\_wf\09\r8\a\.terraform\terraform.exe plan -var sub=app105 -var pod_name=Prod ] panic: runtime error: invalid memory address or nil pointer dereference
2021-10-12T14:09:26.5051567Z ##[error][signal 0xc0000005 code=0x0 addr=0x10 pc=0x1e2fada]

**Comment by jbardin** [comment] 2021-10-12 19:30
Hi @rohanvirmani,

Thanks for filing the issue. This looks like a duplicate of #26702, so I'm going to close it.
If you can reproduce the crash with a current Terraform release, please feel free to re-file the issue with the updated stack trace, also including the configuration and steps to reproduce it.

Thanks!

**Closed by jbardin** 2021-10-12 19:30 UTC
Labels: bug, new
