### ISSUE TITLE
Add support for modifiable EBS volumes

### ISSUE THREAD

**Issue by snicko** [hashicorp/terraform#11948] opened 2017-02-14 22:21 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.6

### Affected Resource(s)
- aws_ebs_volume

Please add support for modifiable EBS volumes ( https://aws.amazon.com/blogs/aws/amazon-ebs-update-new-elastic-volumes-change-everything/ ).

**Comment by stack72** [comment] 2017-02-15 10:28
Hi @snicko 

Thanks for the request here - I am going to close this as a duplicate of #11931 

Paul

**Closed** 2017-02-15 10:28 UTC
Labels: enhancement, provider/aws
