### ISSUE TITLE
Someone has deleted terraform 0.12.24

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#27871] opened 2021-02-22 17:54 UTC
Can it be put back please?

This https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip is 404 not found

Referenced from here:

https://releases.hashicorp.com/terraform/0.12.24/

**Comment by danieldreier** [comment] 2021-02-22 17:56
Hi! The release was not deleted intentionally - there has been an ongoing outage impacting releases.hashicorp.com and registry downloads. I suspect that it is the root cause of what you're seeing. Engineers have a good understanding of what happened and are working on a fix. The best option for you is probably to wait for engineers on our side to fix this.

**Comment by danieldreier** [comment] 2021-02-22 18:06
The root cause here is an incident in the releases.hashicorp.com and registry infrastructure. I'm going to close this and related issues and consolidate any ongoing discussion into https://github.com/hashicorp/terraform/issues/27872. Please do let us know in that issue if you are still having trouble downloading Terraform or providers.

**Closed by danieldreier** 2021-02-22 18:06 UTC
Labels: bug, new
