### ISSUE TITLE
Variables are not interpolated if their values start with a number

### ISSUE THREAD

**Issue by luhkevin** [hashicorp/terraform#17351] opened 2018-02-14 19:18 UTC
~If I capitalize a variable, it won't interpolate at all.~

EDIT: Actually, it seems like it's not the issue of the variable name being capitalized.
From my testing, it seems like if the value of the variable starts with a number, it does not get interpolated correctly

E.g.

```
resource "azurerm_resource_group" "test" {
  name     = "mytest${var.TEST_ID}"
}
```

If `TEST_ID=2e41885`, the name just evaluates to `mytest` when I run `terraform plan`.
If `TEST_ID=e241885`, the name evaluates correctly.

I'm on Terraform v0.10.8

**Comment by apparentlymart** [comment] 2018-02-20 23:07
Hi @luhkevin! Sorry for this problem and thanks for reporting it.

This issue has also been reported in #17396. Although you reported it first, since the other issue has more extensive reproduction steps I'm going to take the unusual step of closing this one to consolidate discussion over there.

Thanks again for reporting this. We'll take a look at it soon.

**Closed by apparentlymart** 2018-02-20 23:07 UTC

**Comment by luhkevin** [comment] 2018-02-20 23:39
No problem. Glad to see I'm not crazy :D
