### ISSUE TITLE
Terraform aws-provider ignores all tags starting with "aws"

### ISSUE THREAD

**Issue by paulka** [hashicorp/terraform#14308] opened 2017-05-09 10:22 UTC
Terraform has a check to make sure it doesn't apply AWS specific tags. These tags start with "aws:". Terraform does a RegEx check on Tag names in the form of `^aws:*`. Matching tags are ignored during an Apply.

This RegEx used by Terraform appears to be incorrect. It will match 'aws' followed by *none* or more colons. It should be 'aws" followed by *at least one* colon.

The correct RegEx would likely be along the lines of `^aws:`

### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
This seems to affect most taggable AWS resources. 

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "${var.aws_region}"
}

resource "aws_vpc" "default" {
  cidr_block       = "xx.y.0.0/16"
  instance_tenancy = "default"
  enable_classiclink = "false"
  enable_dns_hostnames = "true"
  enable_dns_support = "true"

  tags {
    Name = "VPC Name String"
    aws_cost_role = "bar"
    aws_cost_allocation = "foo"
  }
}
```

### Debug Output
```
2017/05/09 10:37:42 [DEBUG] apply: aws_vpc.default: executing Apply
aws_vpc.default: Modifying... (ID: vpc-yyyy725)
  tags.%:                   "1" => "3"
  tags.aws_cost_allocation: "" => "foo"
  tags.aws_cost_role:       "" => "bar"
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] No meta timeoutkey found in Apply()
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Matching ^aws:* with Name
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Matching ^aws:* with Name
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Matching ^aws:* with aws_cost_role
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Found AWS specific tag aws_cost_role (val: bar), ignoring.
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Matching ^aws:* with aws_cost_allocation
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Found AWS specific tag aws_cost_allocation (val: foo), ignoring.
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Matching ^aws:* with Name
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Waiting for state to become: [success]
2017/05/09 10:37:42 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/09 10:37:42 [DEBUG] Creating tags: [{
2017/05/09 10:37:42 [DEBUG] plugin: terraform:   Key: "Name",
2017/05/09 10:37:42 [DEBUG] plugin: terraform:   Value: "VPC Name String"
2017/05/09 10:37:42 [DEBUG] plugin: terraform: }] for vpc-yyyy725
```

### Expected Behavior
The tags `aws_cost_role` and `aws_cost_allocation` should have been set against the VPC resource. 

### Actual Behavior
Terraform incorrectly identified the `aws_cost_role` and `aws_cost_allocation` tags as AWS specific, and ignored them.

### Steps to Reproduce
1. `terraform apply` the above config.

**Comment by grubernaut** [comment] 2017-05-09 16:28
Duplicate of #14247

**Closed** 2017-05-09 17:19 UTC
Labels: bug, provider/aws
