### ISSUE TITLE
Terraform crash - value is marked, so must be unmarked first (terraform validate)

### ISSUE THREAD

**Issue by dariuswatson** [hashicorp/terraform#34040] opened 2023-10-10 02:39 UTC
### Terraform Version

```shell
Dev = Terraform v1.5.4
Stage & Prod = Terraform v1.3.2
```

### Terraform Configuration Files

```terraform

terraform {
  required_version = ">= 1.5.4"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.39.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.15.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.2.3"
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = "~> 2.2.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0.4"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.4.3"
    }
  }
}
```

### Debug Output

```bash
% tf validate

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 5517 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x164
panic({0x104d468a0?, 0x105336060?})
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x26c
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/Users/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.AsString({{{0x105373b88?, 0x14000010c69?}}, {0x104fd39a0?, 0x14005ebd518?}})
	/Users/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_ops.go:1385 +0x54
github.com/zclconf/go-cty/cty.Value.Range({{{0x105373b88?, 0x14000010c69?}}, {0x104fd39a0?, 0x14005ebd518?}})
	/Users/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_range.go:53 +0x25c
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0x1400071fa40, 0x14005ebd500)
	/Users/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:746 +0x9dc
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalExpr(0x14006c04870, {0x105374258?, 0x1400071fa40}, {{0x1053743a8?, 0x106b30580?}})
	/Users/runner/work/terraform/terraform/internal/lang/eval.go:175 +0x17c
github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).EvaluateExpr(0x14005349758?, {0x105374258, 0x1400071fa40}, {{0x1053743a8?, 0x106b30580?}}, {0x0?, 0x0?})
	/Users/runner/work/terraform/terraform/internal/terraform/eval_context_builtin.go:289 +0x84
github.com/hashicorp/terraform/internal/terraform.(*NodeLocal).Execute(0x12e2bcbb0?, {0x10538e450, 0x1400608f340}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_local.go:158 +0x440
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14002370120, {0x10538e450, 0x1400608f340}, {0x12eaa5e78, 0x1400693da10})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xa0
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x1051100a0, 0x1400693da10})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x280
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14006f84780, {0x1051100a0, 0x1400693da10}, 0x14006f9bb00)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2a8
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 3153
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xb0c
```

### Last week all the TF steps were successful 

- Was looking to upgrade terraform versions starting in Dev and notice the `terraform validate` is crashing
-  Checkout out the other environment not updated but still seeing this when running `terraform validate`

### Actual Behavior

Getting Error: Terraform crashed! This is always indicative of a bug within Terraform.

### Steps to Reproduce

1. terraform init 
2. terraform plan
3. terraform apply (works without error)
4. terraform validate (crash)

### Additional Context

- when checking out unchanged terraform workspace (Stage & Prod) still getting error on `terraform validate`

**Comment by pavan-kovi** [comment] 2023-10-10 03:47
@dariuswatson, I have similar crash issues while working with terraform resource "aws_db_instance".

Following 3 properties led to crash:

   password                                           = var.manage_master_user_password ? null : var.password
   manage_master_user_password        = var.manage_master_user_password ? var.manage_master_user_password : null
   master_user_secret_kms_key_id         = var.manage_master_user_password ? var.master_user_secret_kms_key_id : null

Changing the code to the following has resolved the crash. We are Investigating further. 

  password                                         = var.password
  manage_master_user_password      = var.manage_master_user_password
  master_user_secret_kms_key_id       = var.master_user_secret_kms_key_id

**Comment by DenisBalan** [comment] 2023-10-10 06:41
It was fixed as part of #33977

**Comment by liamcervante** [comment] 2023-10-10 07:50
Given the older versions, this could also be a duplicate of #32956.

@dariuswatson, can you try running `terraform validate` using `v1.6.0`? That could help us discover whether this is a new bug or something we've already fixed in an earlier version. I suspect this is something that has already been addressed.

I'll close this as a duplicate, but feel free to reopen if you can replicate this on the latest release.

Thanks!

**Closed by liamcervante** 2023-10-10 07:50 UTC
Labels: bug, new

**Comment by liamcervante** [comment] 2023-10-10 14:17
Thanks @dariuswatson, looking at that stack track I do think this is a duplicate of #33977. The good news is this will be fixed in the next patch release. Thanks for verifying!

**Comment by dariuswatson** [comment] 2023-10-10 18:54
Thanks @liamcervante! 

I can confirm that after upgrading everything to Terraform version `1.6.1` I am no longer receiving the crash error for any steps
