### ISSUE TITLE
Crash when acting upon powered off VM

### ISSUE THREAD

**Issue by bpoland** [hashicorp/terraform#13803] opened 2017-04-20 14:51 UTC
### Terraform Version
Terraform version: 0.9.3  1601af7a076fd03fe940455db7fd01dfa747c795

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files
```hcl
provider "vsphere" {
  user                 = "${var.vsphere_user}"
  password             = "${var.vsphere_password}"
  vsphere_server       = "${var.vsphere_server}"
  allow_unverified_ssl = "${var.vsphere_allow_unverified_ssl}"
}

resource "vsphere_virtual_machine" "dest_image" {
  name         = "${var.vsphere_dest_image_name}"
  folder       = "${var.vsphere_root_folder}/${var.vsphere_dest_image_folder}"
  vcpu         = "${var.vsphere_dest_image_vcpu}"
  memory       = "${var.vsphere_dest_image_memory}"
  domain       = "${var.vsphere_dest_image_domain}"
  datacenter   = "${var.vsphere_datacenter}"
  cluster      = "${var.vsphere_cluster}"
  dns_suffixes = ["${var.vsphere_dest_image_domain}"]
  dns_servers  = ["${var.vsphere_dns_servers}"]

  network_interface {
    label = "${var.vsphere_network}"
  }

  disk {
    datastore = "${var.vsphere_datastore}"
    template  = "${var.vsphere_root_folder}/${var.vsphere_source_image_folder}/${var.vsphere_source_image_name}"
  }
  
  connection {
    type = "ssh"
    user = "${var.vsphere_image_username}"
    password = "${var.vsphere_image_password}"
  }
}

```

### Debug Output
I believe it's in the panic output below, here is the regular output:

$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

vsphere_virtual_machine.dest_image: Refreshing state... (ID: bp-vm-01)
Error refreshing state: 1 error(s) occurred:

* vsphere_virtual_machine.dest_image: vsphere_virtual_machine.dest_image: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2017/04/20 10:32:49 [DEBUG] plugin: terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3cdc5c9]
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 
2017/04/20 10:32:49 [DEBUG] plugin: terraform: goroutine 47 [running]:
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineRead(0xc42023a380, 0x4daa380, 0xc4204ef650, 0x1, 0x77c2d80)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:1030 +0x18a9
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420421d40, 0xc4201a0410, 0x4daa380, 0xc4204ef650, 0xc42043fd10, 0xc42042d301, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42026b1f0, 0xc4201a03c0, 0xc4201a0410, 0x7f42dc212000, 0x0, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017/04/20 10:32:49 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4200af140, 0xc4203f2060, 0xc4203f2c90, 0x0, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017/04/20 10:32:49 [DEBUG] plugin: terraform: reflect.Value.call(0xc42035d920, 0xc42000c5a0, 0x13, 0x4e8780f, 0x4, 0xc4206c6f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/04/20 10:32:49 [DEBUG] plugin: terraform: reflect.Value.Call(0xc42035d920, 0xc42000c5a0, 0x13, 0xc420643f20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/04/20 10:32:49 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc4204dcf40, 0xc4204dcf00, 0xc4201450f8, 0xc420521300, 0xc420434860, 0x4078040, 0xc4203f2060, 0x16, 0x4078080, 0xc4203f2c90, ...)
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/04/20 10:32:49 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/04/20 10:32:49 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/04/20 10:32:49 [ERROR] root: eval: *terraform.EvalRefresh, err: vsphere_virtual_machine.dest_image: unexpected EOF
2017/04/20 10:32:49 [ERROR] root: eval: *terraform.EvalSequence, err: vsphere_virtual_machine.dest_image: unexpected EOF
2017/04/20 10:32:49 [TRACE] [walkRefresh] Exiting eval tree: vsphere_virtual_machine.dest_image
2017/04/20 10:32:49 [DEBUG] dag/walk: upstream errored, not walking "output.dest_image_ip"
2017/04/20 10:32:49 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/04/20 10:32:49 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/04/20 10:32:49 [WARN] plugin: error closing client during Kill: connection is shut down
2017/04/20 10:32:49 [DEBUG] plugin: terraform: plugin process exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Panic Output
https://gist.github.com/bpoland/5c9055b1c64e82654e5d928609d2cda3

### Expected Behavior
Shouldn't crash.  Should refresh successfully since the VM still exists it's just powered off.

### Actual Behavior
Terraform crashed

### Steps to Reproduce
1. `terraform refresh`

### Important Factoids
Only seems to happen if the VM has been sitting there for a while.  A newly created and shut down VM does not have this issue

### References
Seems potentially related to this: https://github.com/hashicorp/terraform/issues/4302

**Comment by bpoland** [comment] 2017-04-25 13:43
I think this may be related to a reboot of virtualcenter.  It seems like if vCenter needs to be rebooted then all VMs deployed before the reboot that are powered off encounter this issue.  So maybe some ID that terraform uses to reference the VM gets invalidated when vCenter is restarted?

**Comment by bpoland** [comment] 2017-04-25 13:47
And VMs (deployed before vCenter reboot) that are powered on also have issues, terraform just hangs trying to refresh their state.  Seems to be related to this: https://github.com/hashicorp/terraform/issues/7479

In both cases, powering the VM on (if it's powered off) or rebooting it (if it's powered on) seems to allow terraform to work again.

**Comment by matt-deboer** [comment] 2017-06-08 21:16
I can confirm this same behavior in `0.9.8`; we also recently rebooted vCenter, although I'm not positive that's a direct cause.

What's interesting is that although we only had a single vm in `powered off` state, a terraform refresh of about 50 vms showed a random number of vms in error; likely based on the time at which the

Only after individually running a `terraform plan -target {vm}` for each vm, did we find that one was the culprit.

Here is the associated stack trace:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
data.template_file.cloud_config: Refreshing state...
vsphere_virtual_machine.agent.6: Refreshing state... (ID: example-agent-7)
Error refreshing state: 1 error(s) occurred:
* module.vmware_agent_a1.vsphere_virtual_machine.agent: 1 error(s) occurred:
* module.vmware_agent_a1.vsphere_virtual_machine.agent[6]: vsphere_virtual_machine.agent.6: unexpected EOF
panic: runtime error: index out of range
2017/06/08 20:08:22 [DEBUG] plugin: terraform:
2017/06/08 20:08:22 [DEBUG] plugin: terraform: goroutine 59 [running]:
2017/06/08 20:08:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineRead(0xc420475f10, 0x545d980, 0xc420322e30, 0x1, 0x82173e0)
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:1089 +0x384c
2017/06/08 20:08:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420384c00, 0xc4201b8fa0, 0x545d980, 0xc420322e30, 0xc4205bbc40, 0xc420175501, 0x0)
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2017/06/08 20:08:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420372e70, 0xc4201b8f00, 0xc4201b8fa0, 0x7fd723b50e10, 0x0, 0x0)
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017/06/08 20:08:22 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4203a7b80, 0xc420323160, 0xc4203d20e0, 0x0, 0x0)
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017/06/08 20:08:22 [DEBUG] plugin: terraform: reflect.Value.call(0xc42032fa40, 0xc4201c0350, 0x13, 0x55480a3, 0x4, 0xc420039f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/go/src/reflect/value.go:434 +0x91f
2017/06/08 20:08:22 [DEBUG] plugin: terraform: reflect.Value.Call(0xc42032fa40, 0xc4201c0350, 0x13, 0xc420769720, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/go/src/reflect/value.go:302 +0xa4
2017/06/08 20:08:22 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420119e40, 0xc420119e00, 0xc420241a40, 0xc420176500, 0xc4204f3280, 0x463b6a0, 0xc420323160, 0x16, 0x463b6e0, 0xc4203d20e0, ...)
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/go/src/net/rpc/server.go:387 +0x144
2017/06/08 20:08:22 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/06/08 20:08:22 [DEBUG] plugin: terraform:  /opt/go/src/net/rpc/server.go:481 +0x404
2017/06/08 20:08:22 [ERROR] root.vmware_agent_a1: eval: *terraform.EvalRefresh, err: vsphere_virtual_machine.agent.6: unexpected EOF
2017/06/08 20:08:22 [ERROR] root.vmware_agent_a1: eval: *terraform.EvalSequence, err: vsphere_virtual_machine.agent.6: unexpected EOF
2017/06/08 20:08:22 [TRACE] [walkRefresh] Exiting eval tree: module.vmware_agent_a1.vsphere_virtual_machine.agent[6]
2017/06/08 20:08:22 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited
2017/06/08 20:08:22 [DEBUG] dag/walk: upstream errored, not walking "provider.vsphere (close)"
2017/06/08 20:08:22 [DEBUG] dag/walk: upstream errored, not walking "module.vmware_agent_a1.output.ips"
2017/06/08 20:08:22 [DEBUG] dag/walk: upstream errored, not walking "output.a1_agent_ips"
2017/06/08 20:08:22 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/06/08 20:08:22 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/06/08 20:08:22 [WARN] plugin: error closing client during Kill: connection is shut down
2017/06/08 20:08:22 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/06/08 20:08:22 [ERR] plugin: plugin server: accept unix /tmp/plugin438251367: use of closed network connection
2017/06/08 20:08:22 [DEBUG] plugin: terraform: template-provider (internal) 2017/06/08 20:08:22 [ERR] plugin: plugin server: accept unix /tmp/plugin619221656: use of closed network connection
2017/06/08 20:08:22 [DEBUG] plugin: terraform: template-provider (internal) 2017/06/08 20:08:22 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/06/08 20:08:22 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2017/06/08 20:08:22 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/06/08 20:08:22 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/06/08 20:08:22 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/06/08 20:08:22 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited
2017/06/08 20:08:22 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited
2017/06/08 20:08:22 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
`

**Comment by matt-deboer** [comment] 2017-06-09 03:49
So, after a quick bit of code, it's easy enough to check and avoid the invalid array access...but then we end up in the condition where terraform wants to re-create the resource, because it thinks that it currently has `0` active NICs.

The larger problem is that `powered_on` is not an attribute of the resource, and one or more other attributes cannot be accurately read unless `powered_on` is `true`. 

My suggested way to solve it--add a new `assure_powered_on` boolean attribute on `vsphere_virtual_machine`:
* when `false` (default):  if machine is powered off, an error is thrown describing the vm that is 
* when `true`: if the machine is powered off, assure that the vm is in `powered on` state before proceeding.

This is a bit irregular in that we would be potentially modifying the state of a resource (from powered off' to 'powered on') as a prerequisite to a read operation (insert quantum entanglement comparison here), but it would be an opt-in configuration.

Thoughts?

We could actually combine

**Comment by alternico** [comment] 2017-06-10 17:03
Hi there,

I can confirm that I have the same issue that you guys have mentioned.
I am running terraform 0.9.8.
Thanks

**Closed** 2017-06-13 20:27 UTC
Labels: crash, provider/vsphere
