### ISSUE TITLE
Confirmation message during migrating backend is confusing

### ISSUE THREAD

**Issue by synthdnb** [hashicorp/terraform#15710] opened 2017-08-03 07:55 UTC
Today, I had to change my terraform backend state's path name because our project's codename has been changed, and when I executed `terraform init` after changing my backend path, I got this message.

```
Do you want to copy state from "s3" to "s3"?
  Pre-existing state was found in "s3" while migrating to "s3". No existing
  state was found in "s3". Do you want to copy the state from "s3" to
  "s3"? Enter "yes" to copy and "no" to start with an empty state.
```

It is very confusing to find out whether "s3" is old or new one.
I think suffixing (old), (new) to messages will help distinguishing and prevent accidents.

**Comment by apparentlymart** [comment] 2017-08-05 18:38
Thanks for pointing this out, @synthdnb.

I think it would be helpful for us to be able to ask a backend for a concise string representation of the state storage location so we can include it in messages like this. We had a similar problem with printing out the state location in the `apply` output. For S3 in particular it could be an `s3://` URL as seen in the AWS SDK, I think.

**Comment by mildwonkey** [comment] 2020-08-27 15:48
I'm going to close this as it appears to be a duplicate of another closed (fixed) issue: https://github.com/hashicorp/terraform/issues/16729

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!

**Closed by mildwonkey** 2020-08-27 15:48 UTC
Labels: bug, cli, v0.11
