### ISSUE TITLE
Continually modify ephemeral_block_device.*.no_device on plan/apply

### ISSUE THREAD

**Issue by Gary-Armstrong** [hashicorp/terraform#10842] opened 2016-12-19 18:37 UTC
After successful plan/apply moving from v0.7.7 to v0.8.1, each plan will do:
```
~ aws_instance.compute.0
    ephemeral_block_device.3710187412.no_device: "false" => ""
    ephemeral_block_device.430514000.no_device:  "false" => ""
```
This happens on all existing instances with ephemeral devices.

### Terraform Version
v0.8.1 after v0.7.7
Also v0.9.2

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
This code is unchanged.
```hcl
  ephemeral_block_device = {
    device_name = "/dev/sdb"
    virtual_name = "ephemeral0"
  }
  ephemeral_block_device = {
    device_name = "/dev/sdc"
    virtual_name = "ephemeral1"
  }
```
I didn't change it because the docs say that `no_device` is optional.

### Debug Output
https://gist.github.com/Gary-Armstrong/3c52ada53bf6f165542a3bc3c8b57455

### Expected Behavior
TF should not change `no_device` every time.

### Actual Behavior
TF will change `no_device` on every plan.  Output seems OK:
```
  ephemeral_block_device.3710187412.device_name = /dev/sdc
  ephemeral_block_device.3710187412.no_device = false
  ephemeral_block_device.3710187412.virtual_name = ephemeral1
  ephemeral_block_device.430514000.device_name = /dev/sdb
  ephemeral_block_device.430514000.no_device = false
  ephemeral_block_device.430514000.virtual_name = ephemeral0
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by jbardin** [comment] 2016-12-19 20:45
Hi @Gary-Armstrong,

Thanks for the bug report. Unfortunately, I'm not able to reproduce this with what's provided here. As far as I can see, `ephemeral_block_device*.no_device: "false" => ""` should not show as a diff. 

Can you possibly provide the state file (please check for sensitive data),  or the block from the state for the affected instances? Is there anything else you can provide that may be unique about your configuration?

**Comment by Gary-Armstrong** [comment] 2016-12-20 16:50
@jbardin Thanks for the response.  I'll be happy to provide any & all info that I can.

I scrubbed the state file:
https://gist.github.com/Gary-Armstrong/375e1ed4dc6949185f80de716c15c433

I suppose a unique element could be that these are all pre-existing instances, but honestly that does not seem at all unique.  Some of these instances carried block devices forward in the AMI snapshot, but others were built from a bare-bones AMI.  I'm not sure what else might be remotely of interest.

**Comment by Gary-Armstrong** [comment] 2016-12-20 16:52
BTW I included the entire state because:
1. This affects every instance
2. No idea what might be relevant
Apologies for the eyestrain :)

**Comment by jbardin** [comment] 2016-12-20 22:57
Thanks for the added info, however I still can't reproduce the issue.

Looking again at the logs, I'm guessing it might be an interaction with `ignore_changes`. Could you provide a full config for one of the effected instances?

**Comment by Gary-Armstrong** [comment] 2016-12-21 15:37
Sure.  You will see that I added `ephemeral_block_device` to the growing list of things to ignore.
```
resource "aws_instance" "compute" {
  count = "${var.compute_count}"

  ami = "${var.compute_ami}"

	availability_zone = "${var.region}${var.wxmix_zone}"

	instance_type = "${var.compute_instance_type}"

  vpc_security_group_ids = [ "${aws_security_group.wxmix_admin_sg.id}",
                             "${aws_security_group.wxmix_sg.id}" ]

  subnet_id = "${aws_subnet.wxmix_public_sn.id}"
	associate_public_ip_address = false
	source_dest_check = true

  private_ip = "${element(split(",",var.compute_private_ips), count.index)}"

  iam_instance_profile = "${aws_iam_instance_profile.wxmix_profile.name}"

  key_name = "${var.keypair_name}"

  user_data = "${element(data.template_file.bootstrap-compute.*.rendered, count.index)}"

  lifecycle {
    ignore_changes = [
      "user_data",
      "ephemeral_block_device",
      "associate_public_ip_address"
    ]
  }

  tags {
    Name = "${var.project}-${var.environment}-${var.region}-compute-${format("%03d", count.index)}"
    Billing = "WxMix"
  }

  # x1.32xlarge ephemeral count = 2
  # r3.8xlarge ephemeral count = 2
  ephemeral_block_device = {
    device_name = "/dev/sdb"
    virtual_name = "ephemeral0"
  }
  ephemeral_block_device = {
    device_name = "/dev/sdc"
    virtual_name = "ephemeral1"
  }
}
```

**Comment by Gary-Armstrong** [comment] 2017-03-28 14:20
Using 0.9, made a new instance last week.  I removed the ephemeral from the ignore list:
```
  lifecycle {
    ignore_changes = [
      "user_data",
      "associate_public_ip_address"
    ]
```
This is because I kinda forgot why it was in there and I was trying the thing where TF will resize an instance with just a Stop/Start.  Of course if I had give it another 30 seconds of consideration, I'd have realized that the new instance type would still have one ephemeral instead of the desired two.

I then just tainted the instance and let TF recreate it with two ephemerals.  That was all fine, until today when I moved from 0.9.0 to 0.9.2 and just did a plan:
```
~ aws_instance.viewer
    ephemeral_block_device.#:                       "2" => "2"
    ephemeral_block_device.3710187412.device_name:  "/dev/sdc" => "/dev/sdc"
    ephemeral_block_device.3710187412.no_device:    "false" => ""
    ephemeral_block_device.3710187412.virtual_name: "ephemeral1" => "ephemeral1"
    ephemeral_block_device.430514000.device_name:   "/dev/sdb" => "/dev/sdb"
    ephemeral_block_device.430514000.no_device:     "false" => ""
    ephemeral_block_device.430514000.virtual_name:  "ephemeral0" => "ephemeral0"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Besides the obvious, I'm curious about the `~` behavior in this case.  You can't add an ephemeral to an existing AWS instance.  I don't want to try experiments on this instance.

**Comment by jbardin** [comment] 2017-03-28 15:17
@Gary-Armstrong, Thanks for the update!

I think this narrows down what's going on here, and it looks like it was almost fixed by the `ignore_changes` refactor in the last release. Let me see if I can reproduce this again.

**Comment by Gary-Armstrong** [comment] 2017-03-28 16:51
Hey, thanks to you for working on this.  I'm just the guy complaining.
Let me know if you need additional info.

**Comment by jbardin** [comment] 2017-03-28 20:16
@Gary-Armstrong: I'm willing to bet that if go to the AWS console, you'll find that this instance has a public IP address even though that field if set to `false`, which is why you had to put it in `ignore_changes`. This is issue #8244.

The `associate_public_ip_address` triggers a diff showing all attributes changing, because the instance would need to be replaced.  After filtering the ignored field and diffs caused by replacement, we are left with the diff above, because `no_device:     "false" => ""` is not empty. 

At first glance, it appears that `no_device` is never read from AWS (because it normally does have to), nor does it have a configuration default, so tagging this as definitively an AWS bug. ;)

**Comment by Gary-Armstrong** [comment] 2017-03-29 20:59
It certainly does have a public IP because I assigned a EIP to it.  I have another issue opened on that causing `-/+` on every TF run.

**Comment by ata-sql** [comment] 2017-05-30 09:19
I have the same issue for about half a year.
`
~ aws_instance.ajg-backup-ireland
    ephemeral_block_device.#:                       "3" => "3"
    ephemeral_block_device.2340069903.device_name:  "/dev/sdd" => "/dev/sdd"
    ephemeral_block_device.2340069903.no_device:    "false" => ""
    ephemeral_block_device.2340069903.virtual_name: "ephemeral2" => "ephemeral2"
    ephemeral_block_device.3710187412.device_name:  "/dev/sdc" => "/dev/sdc"
    ephemeral_block_device.3710187412.no_device:    "false" => ""
    ephemeral_block_device.3710187412.virtual_name: "ephemeral1" => "ephemeral1"
    ephemeral_block_device.430514000.device_name:   "/dev/sdb" => "/dev/sdb"
    ephemeral_block_device.430514000.no_device:     "false" => ""
    ephemeral_block_device.430514000.virtual_name:  "ephemeral0" => "ephemeral0"
`

**Closed** 2017-06-13 19:20 UTC
Labels: bug, provider/aws
