### ISSUE TITLE
terraform_remote_state shows the entire map, not just outputs

### ISSUE THREAD

**Issue by bentterp** [hashicorp/terraform#20276] opened 2019-02-08 12:45 UTC
### Terraform Version

```
0.12.0 (built from master)
```

### Terraform Configuration Files

```hcl
data "terraform_remote_state" "infra" {
  backend = "azurerm"
  config = {
    storage_account_name  = "###############"
    container_name        = "############"
    key                   = "#######################"
    subscription_id       = "#######################"
    resource_group_name   = "DemoRG"
  }
}

output "terraform_remote_state_infra" {
  value = data.terraform_remote_state.infra
```

### Debug Output

https://gist.github.com/bentterp/1a2925508f5ed156a34f45d97731198f

### Expected Behavior

terraform_remote_state_infra = {
    "nwk" = {
      "asg_pubhost" = "/subscriptions/####################"
       "intern_dns" = {
        "id" = "/subscriptions/####################"
    etc etc etc

### Actual Behavior

terraform_remote_state_infra = {
  "backend" = "azurerm"
  "config" = {
    "container_name" = "###########"
    "key" = "#########################"
    "resource_group_name" = "###############"
    "storage_account_name" = "#####################"
    "subscription_id" = "#####################"
  }
  "outputs" = {
    "nwk" = {
      "asg_pubhost" = "/subscriptions/####################"
       "intern_dns" = {
        "id" = "/subscriptions/####################"
    etc etc etc

**Comment by radeksimko** [comment] 2019-02-12 16:14
This may be related to https://github.com/hashicorp/terraform/pull/20243

**Comment by apparentlymart** [comment] 2019-02-13 02:12
Hi @bentterp! Thanks for reporting this.

What you've seen here is the intended behavior. Since `data.terraform_remote_state.infra` identifies the entire resource, the result of that expression is an object representation of the entire resource.

To get just the outputs, you can use the `outputs` attribute:

```hcl
output "terraform_remote_state_infra" {
  value = data.terraform_remote_state.infra.outputs
}
```

This is actually one of the reasons (though not the only reason) for the change that was documented by #20243, since otherwise there would be no way to address just the outputs as an expression.

Since this is behaving as intended, I'm going to close this out. The documentation for `terraform_remote_state` will be updated as part of release preparation, so we can mention there this new capability of accessing all of the outputs together as a single object, which wasn't possible in Terraform 0.11.

**Closed by apparentlymart** 2019-02-13 02:12 UTC
Labels: config

**Comment by radeksimko** [comment] 2019-02-13 08:14
> The documentation for `terraform_remote_state` will be updated as part of release preparation

That was updated already via https://github.com/hashicorp/terraform/pull/20247
