### ISSUE TITLE
Error: Inconsistent conditional result types

### ISSUE THREAD

**Issue by Geartrixy** [hashicorp/terraform#22450] opened 2019-08-13 16:42 UTC
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.23.0
```

### Terraform Configuration Files

```hcl

# child module
resource "aws_lb_listener" "https" {
  count              = var.lb_https_listener == true ? 1 : 0
  load_balancer_arn  = aws_lb.application_loadbalancer.arn
  port               = var.lb_https_listener_port
  protocol           = "HTTPS"

  default_action {
    target_group_arn = var.lb_https_offloading == true ?  aws_lb_target_group.tg_http[0].arn : aws_lb_target_group.tg_https[0].arn
  
    type             = "forward"
  }

  certificate_arn    = var.certificate_arn
}


resource "aws_lb_listener_rule" "https" {
  count              = (var.lb_https_listener == true ? (var.lb_https_offloading == true ? length(var.http_target_group_parameters) : length(var.https_target_group_parameters)) : 0)
  listener_arn       = aws_lb_listener.https[0].arn

  action {
    type             = "forward"
    target_group_arn = var.lb_https_offloading == true ?  element(aws_lb_target_group.tg_http.*.arn, count.index) : element(aws_lb_target_group.tg_https.*.arn, count.index)
  }

  condition {
    field            = "host-header"
    values           = var.lb_https_offloading == true ? lookup(element(var.http_target_group_parameters, count.index), "host_headers", "missing_host_header") : lookup(element(var.https_target_group_parameters, count.index), "host_headers", "missing_host_header")
  }

  lifecycle {
    create_before_destroy = true
  }
}

# root module
# variables declared with defaults

variable "http_target_group_parameters" {
  #https://github.com/terraform-providers/terraform-provider-aws/pull/8268
  type = list(any)
  default = [
    {
    # example configuration
    #   target_group = "my-target-group-http"
    #   host_headers = ["mywebsite.com"]
    #   port         = "80"
    }
  ]
}

variable "https_target_group_parameters" {
#https://github.com/terraform-providers/terraform-provider-aws/pull/8268
  type = list(any)
  default = [
    {
    # example configuration
    #   target_group = "my-target-group-https"
    #   host_headers = ["mywebsite.com"]
    #   port         = "443"
    }
  ]
}

# main.tf (relevant lines)
http_target_group_parameters           = var.ext_http_target_group_parameters

#tfvars 
ext_http_target_group_parameters = [
  {
    target_group = "group1-ext-http"
    host_headers = ["mysite1.com"]
    port         = "10001"
  },
  {
    target_group = "group2-ext-http"
    host_headers = ["mysite2.com"]
    port         = "10002"
  },
  {
    target_group = "group3-ext-http"
    host_headers = ["mysite3.com"]
    port         = "10003"
  },
  {
    target_group = "group4-ext-http"
    host_headers = ["mysite4.com"]
    port         = "10004"
  },
]
```

### Expected Behavior

Both sides of the conditional are a list of maps (so the same type) on the line:

```hcl
values           = var.lb_https_offloading == true ? lookup(element(var.http_target_group_parameters, count.index), "host_headers", "missing_host_header") : lookup(element(var.https_target_group_parameters, count.index), "host_headers", "missing_host_header")
```

But each has a varying amount of elements (maps in the list) which causes a problem. As "https_target_group_parameters" was not set, the default list value contains one element, an empty map. The "http_target_group_parameters" has been set, containing a list of 4 maps.

As I understood, only the side of the conditional which equates to true is evaluated, so the other side should not be inspected, but it looks like it is?
### Actual Behaviour

```
Error: Inconsistent conditional result types

  on ..\..\terraform-library\my-module\alb_https_listeners.tf line 32, in resource "aws_lb_listener_rule" "https":
  32:     values           = var.lb_https_offloading == true ? lookup(element(var.http_target_group_parameters, count.index), "host_headers", "missing_host_header") : lookup(element(var.https_target_group_parameters, count.index), "host_headers", "missing_host_header")
    |----------------
    | count.index is 1
    | var.http_target_group_parameters is list of object with 4 elements
    | var.https_target_group_parameters is list of object with 1 element
    | var.lb_https_offloading is true

The true and false result expressions must have consistent types. The given
expressions are tuple and string, respectively.


Error: Inconsistent conditional result types

  on ..\..\terraform-library\my-module\alb_https_listeners.tf line 32, in resource "aws_lb_listener_rule" "https":
  32:     values           = var.lb_https_offloading == true ? lookup(element(var.http_target_group_parameters, count.index), "host_headers", "missing_host_header") : lookup(element(var.https_target_group_parameters, count.index), "host_headers", "missing_host_header")
    |----------------
    | count.index is 3
    | var.http_target_group_parameters is list of object with 4 elements
    | var.https_target_group_parameters is list of object with 1 element
    | var.lb_https_offloading is true

The true and false result expressions must have consistent types. The given
expressions are tuple and string, respectively.


Error: Inconsistent conditional result types

  on ..\..\terraform-library\my-module\alb_https_listeners.tf line 32, in resource "aws_lb_listener_rule" "https":
  32:     values           = var.lb_https_offloading == true ? lookup(element(var.http_target_group_parameters, count.index), "host_headers", "missing_host_header") : lookup(element(var.https_target_group_parameters, count.index), "host_headers", "missing_host_header")
    |----------------
    | count.index is 0
    | var.http_target_group_parameters is list of object with 4 elements
    | var.https_target_group_parameters is list of object with 1 element
    | var.lb_https_offloading is true

The true and false result expressions must have consistent types. The given
expressions are tuple and string, respectively.


Error: Inconsistent conditional result types

  on ..\..\terraform-library\my-module\alb_https_listeners.tf line 32, in resource "aws_lb_listener_rule" "https":
  32:     values           = var.lb_https_offloading == true ? lookup(element(var.http_target_group_parameters, count.index), "host_headers", "missing_host_header") : lookup(element(var.https_target_group_parameters, count.index), "host_headers", "missing_host_header")
    |----------------
    | count.index is 2
    | var.http_target_group_parameters is list of object with 4 elements
    | var.https_target_group_parameters is list of object with 1 element
    | var.lb_https_offloading is true

The true and false result expressions must have consistent types. The given
expressions are tuple and string, respectively.
```

### Steps to Reproduce

terraform apply

**Comment by Geartrixy** [comment] 2019-08-13 16:47
On a side note I also tried setting:

```hcl
type = list(any)
```
to

```hcl
type = list(map(any))
```

but this threw an error 🙃

**Comment by teamterraform** [comment] 2019-08-13 22:48
Hi @Geartrixy!

While it is true that Terraform only evaluates the value on the chosen side of the conditional, Terraform does still require both sides to be convertible to some common type so that Terraform can know what the result type will be even if it doesn't yet know which of the expressions will be selected. The error you're seeing is a static type checking error during validation, not an evaluation error.

For simpler types Terraform is able to figure out the common base type for both of the operands automatically, but in this case it seems that Terraform isn't finding a solution automatically and so it will need some help from you by specifying a more specific type constraint on your two variables. A fully-specified type constraint is one that doesn't include [the `any` placeholder](https://www.terraform.io/docs/configuration/types.html#dynamic-types-the-quot-any-quot-constraint) at all, and thus avoids Terraform having to try to infer which type you intended that to be a placeholder for.

In this case, I think the fully-specified type constraint for your data structure is the following:

```hcl
  type = list(object({
    target_group = string
    host_headers = list(string)
    port         = number
  })
```

With that fully-specified type constraint on both of the variables, Terraform will be forced to use the same type for both `var.http_target_group_parameters` and `var.https_target_group_parameters`, whereas using `any` can lead to Terraform selecting different types for each. With both of the lists having the same element type, `var.http_target_group_parameters[count.index]` and `var.https_target_group_parameters[count.index]` will both have the same type too, and thus your conditional should validate as expected.

As a nice side-effect, this fully-specified type constraint can also serve as more precise documentation for what sort of value is expected for these input variables, enumerating each of the required object attributes explicitly and thus allowing Terraform to check that they've all been set correctly and report an error inside the calling `module` block if not.

Since Terraform seems to be working as designed here (its automatic type inference mechanism doesn't have enough information to resolve this automatically in this case), we're going to close this out now. If you have any follow-up questions, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!

**Closed by teamterraform** 2019-08-13 22:48 UTC

**Comment by Geartrixy** [comment] 2019-08-14 10:14
Thanks for the speedy response and detailed explanation. The new declaration solved the issue 👍 

Thanks again!
Geartrixy
