### ISSUE TITLE
Unable to use for expressions with TypeSets with computed attributes

### ISSUE THREAD

**Issue by matpimenta** [hashicorp/terraform#26419] opened 2020-09-29 20:20 UTC
### Terraform Version

```
v0.13.3
```

###### 

### Terraform Configuration Files

Terraform configuration & script files are [here](https://github.com/matpimenta/terraform-issue-reproductions/tree/master/typeset-computed-id-dependencies/for-expression). I've added a lot more details & information to the following sections.

But, in a nutshell, the issue requires running `terraform apply` 2 times.

First we apply this configuration:

```terraform
terraform {
  required_providers {
    fastly = {
      source = "fastly/fastly"
    }
  }
  required_version = ">= 0.13"
}

provider "fastly" {
}

resource "fastly_service_v1" "myservice" {
  name          = "test-service"
  force_destroy = true

  domain {
    name = "demo.000000001-notexample.com"
  }

  backend {
    address = "127.0.0.1"
    name    = "backend"
  }

}
```

Next, we amend the configuration to add a nested block (*TypeSet*) with a Computed attribute, which is then referenced by another resource using a *for expression*.

```terraform
terraform {
  required_providers {
    fastly = {
      source = "fastly/fastly"
    }
  }
  required_version = ">= 0.13"
}

provider "fastly" {
}

resource "fastly_service_v1" "myservice" {
  name          = "test-service"
  force_destroy = true

  domain {
    name = "demo.000000001-notexample.com"
  }

  backend {
    address = "127.0.0.1"
    name    = "backend"
  }

  # Added dictionary
  dictionary {
    name = "My Dictionary"
    # dictionary is a TypeSet and has a Computed ID field called dictionary_id 
  }

}

# Added dictionary items
resource "fastly_service_dictionary_items_v1" "items" {
  service_id    = fastly_service_v1.myservice.id
  dictionary_id = { for s in fastly_service_v1.myservice.dictionary : s.name => s.dictionary_id }["My Dictionary"]
}

```

### Debug Output

[Trace logs](https://github.com/matpimenta/terraform-issue-reproductions/blob/master/typeset-computed-id-dependencies/for-expression/for-expression-trace.log.encrypted.saltpack) for *TypeSet* using *for expressions* 

### Crash Output

Terraform doesn't crash.

### Expected Behavior

Terraform should notice that the attribute `fastly_service_v1.myservice.dictionary.dictionary_id` is not yet known and defer the evaluation of the for expression in the `fastly_service_dictionary_items_v1` resource. However, this doesn't happen if the `fastly_service_v1.myservice` already exists in the state (created by a previous `terraform apply`).

Note that Terraform does notice the implited dependency between the values when applying the second configuration from scratch (with no previous state). It does also work when replacing the for expression with a `for_each` attribute as shown [here](https://github.com/matpimenta/terraform-issue-reproductions/tree/master/typeset-computed-id-dependencies/for_each). 

Lastly and most interestingly, the *for expression* works when an `if` is added to the expression and it's wrapped around a `lookup` function as shown [here](https://github.com/matpimenta/terraform-issue-reproductions/tree/master/typeset-computed-id-dependencies/if-lookup)

### Actual Behavior

Terraform returns the following error:

```
Error: Invalid index

  on main.tf line 37, in resource "fastly_service_dictionary_items_v1" "items":
  37:     dictionary_id = {for s in fastly_service_v1.myservice.dictionary : s.name => s.dictionary_id}["My Dictionary"]
    |----------------
    | fastly_service_v1.myservice.dictionary is empty set of object

The given key does not identify an element in this collection value.
```

### Steps to Reproduce

The full configuration and steps are at [here](https://github.com/matpimenta/terraform-issue-reproductions/tree/master/typeset-computed-id-dependencies/for-expression)

I've used the Fastly provider because *TypeSet* nested blocks with computed attributes are required to reproduce this.

The simplified steps are:

1. `terraform init`
2.  using *main-step1.tf*, run: 
   `terraform apply`
   The main resource `fastly_service_v1` is applied **without nested block** and the resource that references it.
3. using *main-step2.tf*, run:
   `terraform apply`
   The main resource `fastly_service_v1` is **modified** with a new nested block and **at the same time**, the resource `fastly_service_dictionary_items_v1`is added. This resource contains a reference to the nested block.
   This step fails with the message above

### Additional Context

Nested *TypeList* blocks with computed attributes also have similar behaviour. However, they still have problems when changed to `for_each` attributes.

The steps to reproduce the issue for *TypeList* are [here](https://github.com/matpimenta/terraform-issue-reproductions/tree/master/typelist-computed-id-dependencies/index-lookup) and there's debug logs are [here](https://github.com/matpimenta/terraform-issue-reproductions/blob/master/typelist-computed-id-dependencies/index-lookup/index-lookup-trace.log.encrypted.saltpack)

The Terraform output is:

```Error: Invalid index
  on main.tf line 43, in resource "fastly_service_waf_configuration" "waf":
  43:   waf_id = fastly_service_v1.myservice.waf[0].waf_id
    |----------------
    | fastly_service_v1.myservice.waf is empty list of object

The given key does not identify an element in this collection value.
```

### References

* Similar issue raised for *TypeList*s: https://github.com/hashicorp/terraform/issues/23488

**Comment by jbardin** [comment] 2020-10-01 14:49
Hi @matpimenta 

Thanks for filing the issue withe the excellent example.
I believe this can only happen during refresh, where the configuration and the state do not align, but there has not yet been a plan generated to allow the interpolation to know that there will be new values for `dictionary`.

In 0.14 there will no longer be a separate refresh walk, and from my testing I cannot reproduce the above error condition. Would it be possible for you to try this by building terraform from master, or with one of our early 0.14 alpha builds (https://releases.hashicorp.com/terraform/0.14.0-alpha20200923/ is the most current at the moment)?

Thanks!

**Comment by matpimenta** [comment] 2020-10-06 19:44
Hi @jbardin, thanks for your quick reply and apologies for my delayed response.

I've tested with `Terraform v0.14.0-alpha20200923` and I can confirm that the issue with _for expressions_ goes aways when using `TypeSet`. :) 

For `TypeList`, I'm now getting a different error message from the one above (`...fastly_service_v1.myservice.waf is empty list of object...`) when executing the same configuration.

New error message:
```
fastly_service_v1.myservice: Refreshing state... [id=0lNVC5nYjsQzik3Dv3MEyD]

Error: "waf_id": required field is not set

  on main.tf line 42, in resource "fastly_service_waf_configuration" "waf":
  42: resource "fastly_service_waf_configuration" "waf" {

```
I've uploaded a new trace log for it [here](https://github.com/matpimenta/terraform-issue-reproductions/blob/master/typelist-computed-id-dependencies/index-lookup/index-lookup-trace-2.log.encrypted.saltpack)

Let me know if you need any more details
Thanks

**Comment by jbardin** [comment] 2020-10-08 21:20
Hi @matpimenta 

Thanks for the update!
That error unfortunately looks like it is being caused by the legacy plugin SDK, and its lack of ability to deal with certain aspects of nested blocks. The planned value for `waf_id` from `fastly_service_v1` is `null`, hence the validation for your 
`fastly_service_waf_configuration` is failing saying `waf_id` is unset. I'm not sure if there is a workaround at all for this, as I don't believe you could override it with `CustomizeDiff` either. Until we have a new SDK that can better handle more complex nested data, the easiest workaround may be to simply document that this type of change would take multiple steps to add to the configuration.

I didn't see an exact reference to this problem in the plugin-sdk issues, but even if it was raised there, there's likely not much that can be done as the legacy SDK is basically frozen for compatibility reasons until a new SDK can be developed. 

Since the original error has been fixed from the core side, I'm going to close this out for now.

Thanks!

**Closed by jbardin** 2020-10-08 21:20 UTC
Labels: bug, config, v0.13, waiting-response
