### ISSUE TITLE
Planable import get unexpected update action when import resource with sensitive datasource filed.

### ISSUE THREAD

**Issue by chenzejun** [hashicorp/terraform#33597] opened 2023-07-27 09:01 UTC
### Terraform Version

```shell
1.5.2
```

### Terraform Configuration Files

```
resource "kubernetes_namespace" "ns" {
  lifecycle {
    ignore_changes = [
      wait_for_default_service_account,
      timeouts
    ]
  }
  metadata {
    name = "namespace-test"
  }
}

data "kubernetes_secret" "src" {
  metadata {
    name      = "secret-src"
    namespace = kubernetes_namespace.ns.metadata[0].name
  }
}

resource "kubernetes_secret" "src" {
  lifecycle {
    ignore_changes = [
      wait_for_service_account_token,
      timeouts
    ]
  }
  metadata {
    name      = "secret-src"
    namespace = kubernetes_namespace.ns.metadata[0].name
  }
  data = {
    username = "admin"
    password = "password"
  }
  type = "kubernetes.io/basic-auth"
}

resource "kubernetes_secret" "dst" {
  lifecycle {
    ignore_changes = [
      wait_for_service_account_token,
      timeouts
    ]
  }
  metadata {
    name      = "secret-dst"
    namespace = kubernetes_namespace.ns.metadata[0].name
  }
  data = data.kubernetes_secret.src.data
  type = "kubernetes.io/basic-auth"
}

import {
  to = kubernetes_namespace.ns
  id = "namespace-test"
}

import {
  to = kubernetes_secret.src
  id = "namespace-test/secret-src"
}

import {
  to = kubernetes_secret.dst
  id = "namespace-test/secret-dst"
}
```

### Debug Output

https://gist.github.com/chenzejun/09d481ab4b71cef076fa42732617100e

### Expected Behavior

Plan: 3 to import, 0 to add, 0 to change, 0 to destroy.

### Actual Behavior

Plan: 3 to import, 0 to add, 1 to change, 0 to destroy.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by kmoe** [comment] 2023-07-27 09:23
Thanks for filing this. 

What is the unexpected update change? Can you post the plan?

While I'm not particularly familiar with Kubernetes, this config appears to define a Terraform data source and resource (`data.kubernetes_secret.src` and `kubernetes_secret.src`) for the same remote object, which is not recommended, and can lead to unexpected behaviour.

**Comment by chenzejun** [comment] 2023-07-27 09:49
thanks @kmoe! I simplify my configration to clarify problem.
```

data "kubernetes_namespace" "ns" {
  metadata {
    name      = "namespace-test"
  }
}

data "kubernetes_secret" "src" {
  metadata {
    name      = "secret-src"
    namespace = data.kubernetes_namespace.ns.id
  }
}

resource "kubernetes_secret" "dst" {
  lifecycle {
    ignore_changes = [
      wait_for_service_account_token,
      timeouts
    ]
  }

  metadata {
    name      = "secret-dst"
    namespace = data.kubernetes_namespace.ns.id
  }
  data = data.kubernetes_secret.src.data

  type = "kubernetes.io/basic-auth"
}

import {
  to = kubernetes_secret.dst
  id = "namespace-test/secret-dst"
}

```

and I get the plan:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:     

  # kubernetes_secret.dst will be updated in-place
  # (imported from "namespace-test/secret-dst")
  ~ resource "kubernetes_secret" "dst" {
        data      = (sensitive value)
        id        = "namespace-test/secret-dst"
        immutable = false
        type      = "kubernetes.io/basic-auth"

        metadata {
            annotations      = {}
            generation       = 0
            labels           = {}
            name             = "secret-dst"
            namespace        = "namespace-test"
            resource_version = "8297"
            uid              = "e37e5b60-dddb-4605-9142-4123457b31b1"
        }

        timeouts {}
    }

Plan: 1 to import, 0 to add, 1 to change, 0 to destroy.
```
here is the plan, no changes of resources were shown in the plan

```
{
    "format_version": "1.2",
    "terraform_version": "1.5.2",
    "planned_values": {
        "root_module": {
            "resources": [
                {
                    "address": "kubernetes_secret.dst",
                    "mode": "managed",
                    "type": "kubernetes_secret",
                    "name": "dst",
                    "provider_name": "registry.terraform.io/hashicorp/kubernetes",
                    "schema_version": 0,
                    "values": {
                        "binary_data": null,
                        "data": {
                            "password": "password",
                            "username": "admin"
                        },
                        "id": "namespace-test/secret-dst",
                        "immutable": false,
                        "metadata": [
                            {
                                "annotations": {},
                                "generate_name": "",
                                "generation": 0,
                                "labels": {},
                                "name": "secret-dst",
                                "namespace": "namespace-test",
                                "resource_version": "8297",
                                "uid": "e37e5b60-dddb-4605-9142-4123457b31b1"
                            }
                        ],
                        "timeouts": {
                            "create": null
                        },
                        "type": "kubernetes.io/basic-auth",
                        "wait_for_service_account_token": null
                    },
                    "sensitive_values": {
                        "data": true,
                        "metadata": [
                            {
                                "annotations": {},
                                "labels": {}
                            }
                        ],
                        "timeouts": {}
                    }
                }
            ]
        }
    },
    "resource_changes": [
        {
            "address": "kubernetes_secret.dst",
            "mode": "managed",
            "type": "kubernetes_secret",
            "name": "dst",
            "provider_name": "registry.terraform.io/hashicorp/kubernetes",
            "change": {
                "actions": [
                    "update"
                ],
                "before": {
                    "binary_data": null,
                    "data": {
                        "password": "password",
                        "username": "admin"
                    },
                    "id": "namespace-test/secret-dst",
                    "immutable": false,
                    "metadata": [
                        {
                            "annotations": {},
                            "generate_name": "",
                            "generation": 0,
                            "labels": {},
                            "name": "secret-dst",
                            "namespace": "namespace-test",
                            "resource_version": "8297",
                            "uid": "e37e5b60-dddb-4605-9142-4123457b31b1"
                        }
                    ],
                    "timeouts": {
                        "create": null
                    },
                    "type": "kubernetes.io/basic-auth",
                    "wait_for_service_account_token": null
                },
                "after": {
                    "binary_data": null,
                    "data": {
                        "password": "password",
                        "username": "admin"
                    },
                    "id": "namespace-test/secret-dst",
                    "immutable": false,
                    "metadata": [
                        {
                            "annotations": {},
                            "generate_name": "",
                            "generation": 0,
                            "labels": {},
                            "name": "secret-dst",
                            "namespace": "namespace-test",
                            "resource_version": "8297",
                            "uid": "e37e5b60-dddb-4605-9142-4123457b31b1"
                        }
                    ],
                    "timeouts": {
                        "create": null
                    },
                    "type": "kubernetes.io/basic-auth",
                    "wait_for_service_account_token": null
                },
                "after_unknown": {},
                "before_sensitive": {
                    "binary_data": true,
                    "data": true,
                    "metadata": [
                        {
                            "annotations": {},
                            "labels": {}
                        }
                    ],
                    "timeouts": {}
                },
                "after_sensitive": {
                    "binary_data": true,
                    "data": true,
                    "metadata": [
                        {
                            "annotations": {},
                            "labels": {}
                        }
                    ],
                    "timeouts": {}
                },
                "importing": {
                    "id": "namespace-test/secret-dst"
                }
            }
        }
    ],
    "prior_state": {
        "format_version": "1.0",
        "terraform_version": "1.5.2",
        "values": {
            "root_module": {
                "resources": [
                    {
                        "address": "data.kubernetes_namespace.ns",
                        "mode": "data",
                        "type": "kubernetes_namespace",
                        "name": "ns",
                        "provider_name": "registry.terraform.io/hashicorp/kubernetes",
                        "schema_version": 0,
                        "values": {
                            "id": "namespace-test",
                            "metadata": [
                                {
                                    "annotations": {},
                                    "generation": 0,
                                    "labels": {},
                                    "name": "namespace-test",
                                    "resource_version": "8204",
                                    "uid": "6595b7d5-565c-498b-94f8-64b5f516bc6d"
                                }
                            ],
                            "spec": [
                                {
                                    "finalizers": [
                                        "kubernetes"
                                    ]
                                }
                            ]
                        },
                        "sensitive_values": {
                            "metadata": [
                                {
                                    "annotations": {},
                                    "labels": {}
                                }
                            ],
                            "spec": [
                                {
                                    "finalizers": [
                                        false
                                    ]
                                }
                            ]
                        }
                    },
                    {
                        "address": "data.kubernetes_secret.src",
                        "mode": "data",
                        "type": "kubernetes_secret",
                        "name": "src",
                        "provider_name": "registry.terraform.io/hashicorp/kubernetes",
                        "schema_version": 0,
                        "values": {
                            "binary_data": null,
                            "data": {
                                "password": "password",
                                "username": "admin"
                            },
                            "id": "namespace-test/secret-src",
                            "immutable": false,
                            "metadata": [
                                {
                                    "annotations": {},
                                    "generate_name": "",
                                    "generation": 0,
                                    "labels": {},
                                    "name": "secret-src",
                                    "namespace": "namespace-test",
                                    "resource_version": "8207",
                                    "uid": "f96b2f7a-1c49-4d5f-9a5d-bc32e0d93a83"
                                }
                            ],
                            "type": "kubernetes.io/basic-auth"
                        },
                        "sensitive_values": {
                            "binary_data": true,
                            "data": true,
                            "metadata": [
                                {
                                    "annotations": {},
                                    "labels": {}
                                }
                            ]
                        }
                    },
                    {
                        "address": "kubernetes_secret.dst",
                        "mode": "managed",
                        "type": "kubernetes_secret",
                        "name": "dst",
                        "provider_name": "registry.terraform.io/hashicorp/kubernetes",
                        "schema_version": 0,
                        "values": {
                            "binary_data": null,
                            "data": {
                                "password": "password",
                                "username": "admin"
                            },
                            "id": "namespace-test/secret-dst",
                            "immutable": false,
                            "metadata": [
                                {
                                    "annotations": {},
                                    "generate_name": "",
                                    "generation": 0,
                                    "labels": {},
                                    "name": "secret-dst",
                                    "namespace": "namespace-test",
                                    "resource_version": "8297",
                                    "uid": "e37e5b60-dddb-4605-9142-4123457b31b1"
                                }
                            ],
                            "timeouts": {
                                "create": null
                            },
                            "type": "kubernetes.io/basic-auth",
                            "wait_for_service_account_token": null
                        },
                        "sensitive_values": {
                            "binary_data": true,
                            "data": true,
                            "metadata": [
                                {
                                    "annotations": {},
                                    "labels": {}
                                }
                            ],
                            "timeouts": {}
                        }
                    }
                ]
            }
        }
    },
    "configuration": {
        "provider_config": {
            "kubernetes": {
                "name": "kubernetes",
                "full_name": "registry.terraform.io/hashicorp/kubernetes",
                "expressions": {
                    "config_context": {
                        "constant_value": "minikube"
                    },
                    "config_path": {
                        "constant_value": "../config"
                    }
                }
            }
        },
        "root_module": {
            "resources": [
                {
                    "address": "kubernetes_secret.dst",
                    "mode": "managed",
                    "type": "kubernetes_secret",
                    "name": "dst",
                    "provider_config_key": "kubernetes",
                    "expressions": {
                        "data": {
                            "references": [
                                "data.kubernetes_secret.src.data",
                                "data.kubernetes_secret.src"
                            ]
                        },
                        "metadata": [
                            {
                                "name": {
                                    "constant_value": "secret-dst"
                                },
                                "namespace": {
                                    "references": [
                                        "data.kubernetes_namespace.ns.id",
                                        "data.kubernetes_namespace.ns"
                                    ]
                                }
                            }
                        ],
                        "type": {
                            "constant_value": "kubernetes.io/basic-auth"
                        }
                    },
                    "schema_version": 0
                },
                {
                    "address": "data.kubernetes_namespace.ns",
                    "mode": "data",
                    "type": "kubernetes_namespace",
                    "name": "ns",
                    "provider_config_key": "kubernetes",
                    "expressions": {
                        "metadata": [
                            {
                                "name": {
                                    "constant_value": "namespace-test"
                                }
                            }
                        ]
                    },
                    "schema_version": 0
                },
                {
                    "address": "data.kubernetes_secret.src",
                    "mode": "data",
                    "type": "kubernetes_secret",
                    "name": "src",
                    "provider_config_key": "kubernetes",
                    "expressions": {
                        "metadata": [
                            {
                                "name": {
                                    "constant_value": "secret-src"
                                },
                                "namespace": {
                                    "references": [
                                        "data.kubernetes_namespace.ns.id",
                                        "data.kubernetes_namespace.ns"
                                    ]
                                }
                            }
                        ]
                    },
                    "schema_version": 0
                }
            ]
        }
    },
    "relevant_attributes": [
        {
            "resource": "data.kubernetes_secret.src",
            "attribute": [
                "data"
            ]
        },
        {
            "resource": "data.kubernetes_namespace.ns",
            "attribute": [
                "id"
            ]
        }
    ],
    "timestamp": "2023-07-27T09:47:19Z"
}
```

**Comment by chenzejun** [comment] 2023-07-27 10:21
I guess this is the root cause, emmm

https://github.com/hashicorp/terraform/blob/f397954c5229d3768b9380238f4fd7d1bd9f2188/internal/terraform/node_resource_abstract_instance.go#L1096

**Comment by jbardin** [comment] 2024-02-29 21:31
Closed via #34567

**Closed by jbardin** 2024-02-29 21:31 UTC
Labels: bug, new

**Comment by chenzejun** [comment] 2024-03-05 01:40
@jbardin  The fix https://github.com/hashicorp/terraform/pull/34567 seems have some breaking change 
The sensitive value will be exposed if we use sensitive data source in a insensitive value. see this test case:
![s](https://github.com/hashicorp/terraform/assets/26278304/e1f01e89-751b-43d3-abad-87bef0feb6dd)

**Comment by jbardin** [comment] 2024-03-05 16:43
Thanks @chenzejun! Looks like sensitivity handling for data sources was also lacking (and lacking unit tests), and the the change removed something which was fixing up the data sources as a side-effect. I'll have a new PR up soon before the beta.

**Comment by chenzejun** [comment] 2024-03-08 07:42
hi @jbardin The issue seems to still exist
![image](https://github.com/hashicorp/terraform/assets/26278304/998ced46-ccc5-4476-a6ce-25a3d3e93d28)

**Comment by chenzejun** [comment] 2024-03-08 07:44
Hey @jbardin , I have a fix on it, Would like to have a look when you are avaliable?
https://github.com/hashicorp/terraform/pull/34795

**Comment by jbardin** [comment] 2024-03-08 13:27
Hi @chenzejun,

That is the correct result for this operation. The `data` field is taking on the sensitive mark from the data source schema, and the plan is reflecting that. This must be an "update" because what Terraform is storing is different from what the provider returned for `tfcoremock_secret_resource.example` (changes in state are always shown as "updates", because they must be applied in order to update the stored state).

Your PR is altering what the provider returned. The refreshed state should only ever reflect what the provider alone has knowledge of, the remote state combined with the provider schema.

**Comment by chenzejun** [comment] 2024-03-09 14:32
Hi @jbardin  Thanks for your reply!
If that's the case, it would be a little peculiar to import a resource like tfcoremock_secret_resource.example(which use sensitive value by datasource), the plan shows an update action but in fact nothing will be changed, either resource and state file(It was empty at the beginning). 
From a user's perspective, I may worry about whether this import operation is safe for me, what will happen to my resources ?

**Comment by jbardin** [comment] 2024-03-11 13:42
We tried to make it as clear as possible with the message adjoining the attribute, explaining that it's not shown because the configuration made it sensitive, and `"The value is unchanged"`. Since Terraform cannot apply any changes not accounted for in the plan, and there are no other changes, then nothing else will happen to this resource. It has to be a somewhat generic message, because it's something that can happen in normal plans, and we want the import+plan path to work the same as a update+plan because an import action may trigger updates.

This is not a problem with the plan data, but there may be a way to render this different for the edge case of a newly imported resource, with a sensitive config value, assigned to a non-sensitive attribute; but that is a rather small use case and we need to see what the trade-off might be in the code. Feel free to file a separate issue for that and we can look into it.
