### ISSUE TITLE
Use `terraform state` commands outside of the terraform run files

### ISSUE THREAD

**Issue by 92kz1h** [hashicorp/terraform#17966] opened 2018-04-30 12:08 UTC
I tried asking around on Gitter but it doesn't appear to be something with an immediate "oh, you just need to do x" solution.

### Terraform Version

```
Terraform v0.11.2
+ provider.aws v1.14.1
+ provider.template v1.0.0
```

#### main.tf

```hcl
terraform {
  required_version = "~> 0.11.2"

  backend "s3" {
    bucket               = "MY-BUCKET"
    region               = "eu-west-1"
    key                  = "terraform.tfstate"
    encrypt              = "true"
    workspace_key_prefix = "environment"
  }
}
provider "aws" {
  version = "~> 1.14.0"
  region  = "${var.region}"
}

resource "aws_eip" "my_eip" {}
```

#### variables.tfvars

```
variable "region" {
  default = "eu-west-1"
}
```

### Steps to Reproduce

With a directory structure like:

```
terraform-project/
terraform-project/my-run
terraform-project/my-run/main.tf
terraform-project/my-run/variables.tfvars
```

From the `terraform-project` directory run:

```
terraform init my-run
terraform workspace select my-workspace my-run
terraform plan -var-file=my-run/variables.tfvars my-run
terraform apply -var-file=my-run/variables.tfvars my-run
```

The directory structure of this is now:

```
terraform-project/
terraform-project/.terraform
terraform-project/.terraform/terraform.tfstate
terraform-project/my-run
terraform-project/my-run/main.tf
terraform-project/my-run/variables.tfvars
```

Now, still outside of the `terraform-project/my-run` directory, but still inside the `terraform-project` directory I want to access the state of `my-workspace`.

I have tried many combinations of `terraform state list my-run`, `terraform state list -state=.terraform`, changing directory into `my-run` and running it from there.

### Expected Behavior

I should be able to query the state from outside the directory. With other commands, as demonstrated above, you can access a specific `[dir-or-plan]` just by putting it on the end, and even with `terraform import` you can pass `-config=<dir-or-plan>` to specify where you're referencing.

### Actual Behavior

If you run `terraform state list` in the root of the project (`terraform-project`) then it complains that you must init the project before you can continue.

### Additional Context

The work around right now appears to not run the lifecycle outside of the directory with the run scripts, so I had to:

```
cd my-run
terraform init
terraform workspace select my-workspace
terraform plan -var-file=variables.tfvars
```

then I can use `terraform state list` like usual.

**Comment by jbardin** [comment] 2018-04-30 13:57
Hi @92kz1h,

Thanks for filing the issue. If I understand correctly, this is a duplicate of #17378.

**Comment by 92kz1h** [comment] 2018-04-30 14:48
Thanks for getting back to me, it looks like this is at the very least similar to #17378.

To clarify your response regarding the `-config` flag being legacy. Are you suggesting that the "`dir-or-path`" properties of TF CLI commands are going to be be depreciated in an upcoming release? Because my understanding of the [existing documentation](https://www.terraform.io/docs/commands/apply.html) is that this workflow is actively encouraged.

**Comment by jbardin** [comment] 2018-04-30 15:01
Hi @92kz1h,

I'm not sure what you mean by "actively encouraged" in the docs page, but I think the documentation almost always demonstrates running commands against the current working directory, leaving the `dir-or-path` as an option for pre-existing workflows.

As for the `dir-or-path` option's existence and behavior on the cli, any changes there are yet to be determined, and work cleaning up on the general UI is planned for a future major release. As it stands now, since terraform is reliant on the current working directory for it's internal storage, it's usually better to run terraform against the current directory in all cases.

**Comment by 92kz1h** [comment] 2018-04-30 15:37
I understood it as actively encouraged because the documentation discusses its usage without any kind of discouragement against its usage. From the `terraform apply` page I linked above:

>"_However, a path to another configuration or an execution plan can be provided. Explicit execution plans files can be used to split plan and apply into separate steps within [automation systems](https://www.terraform.io/guides/running-terraform-in-automation.html)._"

Seeing as this `dir-or-path` pattern is on all the basic commands (`init`, `plan`, `apply`, `workspace`, `destroy`) and works with `import` without any kind of warning against it there is no reason to believe it's not a pattern that you endorse. I've been using Terraform for months before I even hit an issue with `state`.

**Comment by jbardin** [comment] 2018-04-30 15:52
Thanks @92kz1h,

It's always helps to get the perspective from new users that aren't already familiar with the internals of terraform. Since the documentation will need to be updated regardless of which direction the UI takes in future versions, and 17378 sufficiently covers the missing `state` functionality, we can close this out for now.

**Closed by jbardin** 2018-04-30 15:52 UTC
Labels: question, waiting-response
