### ISSUE TITLE
Terraform gets confused by multiple policy attachments for same policy

### ISSUE THREAD

**Issue by MFAnderson** [hashicorp/terraform#11873] opened 2017-02-10 22:36 UTC
We're trying to modularize some code setting policies for a number of roles across multiple environments. In some environments the policies are the same for multiple roles. Terraform will quite happily apply this and AWS ends up in the correct state, but terraform appears to get stuck in a loop of thinking that there is a change to be made to the policy attachments although the current state of the AWS account accurately reflects the state defined in the HCL. The obvious solution that we're going with in the short term is to not modularize this code and instead just put both roles in a single policy attachment, but thought we would report it anyways.

### Terraform Version
0.8.6

### Affected Resource(s)
- aws_iam_policy_attachment

### Terraform Configuration Files
```hcl
resource "aws_iam_role" "infra_ops" {
    provider = "aws.infra"
    name = "Ops"
    assume_role_policy = "${data.aws_iam_policy_document.assume_role_policy.json}"
}
resource "aws_iam_role" "infra_dev_admin" {
    provider = "aws.infra"
    name = "DevAdmin"
    assume_role_policy = "${data.aws_iam_policy_document.assume_role_policy.json}"
}
resource "aws_iam_policy_attachment" "infra_ops" {
    provider = "aws.infra"
    name = "infra_ops_attachment"
    roles = ["${aws_iam_role.infra_ops.name}"]
    policy_arn = "arn:aws:iam::aws:policy/PowerUserAccess"
}

resource "aws_iam_policy_attachment" "infra_dev_admin" {
    provider = "aws.infra"
    name = "infra_dev_admin_attachment"
    roles = ["${aws_iam_role.infra_dev_admin.name}"]
    policy_arn = "arn:aws:iam::aws:policy/PowerUserAccess"
}
```

### Expected Behavior
`terraform plan` after `terraform apply` should show no changes to be made

### Actual Behavior
perpetual loop of Terraform wanting to apply a change. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`
3. repeat

**Comment by grubernaut** [comment] 2017-02-13 15:09
Hi @MFAnderson, thanks for the issue!

This, unfortunately, is not a bug. The `aws_iam_policy_attachment` resource can only be used once PER policy resource, as the resource manages all of the role attachments for that IAM Policy. The best workaround for this issue is to create individual policies for each role attachment that you're wanting to attach. 
For example (using the config pasted above):
```
resource "aws_iam_role" "infra_ops" {
    provider = "aws.infra"
    name = "Ops"
    assume_role_policy = "${data.aws_iam_policy_document.assume_role_policy.json}"
}
resource "aws_iam_role" "infra_dev_admin" {
    provider = "aws.infra"
    name = "DevAdmin"
    assume_role_policy = "${data.aws_iam_policy_document.assume_role_policy.json}"
}

resource "aws_iam_policy" "infra_ops" {
  name = "infra_ops_policy"
  path = "/"
  description = "Power User Access"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "NotAction": ["iam:*", "organizations:*"],
      "Resource": "*"
    },{
      "Effect": "Allow",
      "Action": "organizations:DescribeOrganization",
      "Resource": "*"
    }
  ]
}
EOF
}

resource "aws_iam_policy" "infra_dev_admin" {
  name = "infra_dev_admin"
  path = "/"
  description = "Power User Access"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "NotAction": ["iam:*", "organizations:*"],
      "Resource": "*"
    },{
      "Effect": "Allow",
      "Action": "organizations:DescribeOrganization",
      "Resource": "*"
    }
  ]
}
EOF
}

resource "aws_iam_policy_attachment" "infra_ops" {
    provider = "aws.infra"
    name = "infra_ops_attachment"
    roles = ["${aws_iam_role.infra_ops.name}"]
    policy_arn = "${aws_iam_policy.infra_ops.arn}"
}

resource "aws_iam_policy_attachment" "infra_dev_admin" {
    provider = "aws.infra"
    name = "infra_dev_admin_attachment"
    roles = ["${aws_iam_role.infra_dev_admin.name}"]
    policy_arn = "${aws_iam_policy.infra_dev_admin.arn}"
}
```

This will prevent Terraform from "clobbering" the policy attachments as you're seeing above. We do mention this in the documentation for the `aws_iam_policy_attachment` resource, as it's a commonly discovered issue. Closing for now, but happy to discuss further!

**Closed by grubernaut** 2017-02-13 15:09 UTC

**Comment by johnculkin** [comment] 2018-02-26 22:31
Any good examples that work with AWS Managed Policies? We'd like to attach multiple managed policies to a role.

**Comment by bflad** [comment] 2018-02-27 14:07
Hi @johnculkin, personally I would recommend using one of the following resources for attaching multiple AWS managed policies to a group, role, or user:
* [`aws_iam_group_policy_attachment`](https://www.terraform.io/docs/providers/aws/r/iam_group_policy_attachment.html)
* [`aws_iam_role_policy_attachment`](https://www.terraform.io/docs/providers/aws/r/iam_role_policy_attachment.html)
* [`aws_iam_user_policy_attachment`](https://www.terraform.io/docs/providers/aws/r/iam_user_policy_attachment.html)

e.g.

```hcl
resource "aws_iam_role_policy_attachment" "example-CloudWatchEventsFullAccess" {
    role       = "${aws_iam_role.example.name}"
    policy_arn = "arn:aws:iam::aws:policy/CloudWatchEventsFullAccess"
}

resource "aws_iam_role_policy_attachment" "example-SageMakerFullAccess" {
    role       = "${aws_iam_role.example.name}"
    policy_arn = "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
}
```

**Comment by brandonparncutt** [comment] 2018-03-05 20:19
I'm seeing 'terraform plan' fail when declaring aws_iam_role_policy_attachment resources for role resources in the same template. This happens even when I explicitly specify a depends_on statement for the roles:

**Comment by ketzacoatl** [comment] 2018-06-18 12:01
In case anyone runs into this in the future, here is the solution we came up with. For our situation, we wanted to use one of the Managed Policies, and we didn't really want to have to monitor the policy for changes. The solution here is based on idea that we will give each env/project a separate copy of a managed AWS policy, but we'll use the original policy as the source for the copy, and we do it in a way that if the managed policy is updated, we'll get notified of the update and see it in the plan.

```hcl
resource "aws_iam_role" "enhanced_policy_role" {
  name = "${var.name_prefix}-enhanced-monitoring-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "monitoring.rds.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

# we lookup the existing "AWS managed" policy, to use that as the source for our own copy of that policy
data "aws_iam_policy" "AmazonRDSEnhancedMonitoringRole" {
  arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

resource "aws_iam_policy" "copyAmazonRDSEnhancedMonitoringRole" {
  name        = "${var.name_prefix}-AmazonRDSEnhancedMonitoringRole"
  path        = "/"
  description = "Copy of the AWS Managed 'AmazonRDSEnhancedMonitoringRole', for ${var.name_prefix}"

  policy = "${data.aws_iam_policy.AmazonRDSEnhancedMonitoringRole.policy}"

}

# IAM attachment of the AmazonRDSEnhancedMonitoringRole policy to the rds role created above
resource "aws_iam_policy_attachment" "rds-role-attach" {
  name       = "${var.name_prefix}-enhanced-monitoring-attachment"
  policy_arn = "${aws_iam_policy.copyAmazonRDSEnhancedMonitoringRole.arn}"

  roles = [
    "${aws_iam_role.enhanced_policy_role.name}",
  ]
}
```

**Comment by DanielMarquard** [comment] 2018-06-29 18:40
@brandonparncutt I have a very similar problem. For me, both `aws_iam_role_policy_attachment` and aws_iam_policy_attachment` complain that the `aws_iam_policy` I've defined could not be found.

**Comment by andrewandante** [comment] 2018-07-06 08:44
@DanielMarquard I had the same thing - turns out I had trailing commas in my JSON, which were silently failing and causing the policy to not be created. I found this by commenting out my attachment blocks, and running `plan` again. I'd suggest double-checking your JSON syntax in your policy definitions 😄

**Comment by agalazis** [comment] 2018-08-16 06:50
I do think that this should be reopened since the error messages are misleading I would prefer some invalid  JSON for template message

**Comment by flmmartins** [comment] 2018-10-31 11:18
I have a bunch of AWS-pre-defined policies I need to attach at once. I used aws_iam_policy_attachment and it was flopping: sometimes it applied a policy, sometimes not...

I am using looping and I didn't create a JSON because I thought this is too overkill and also because pre-defined AWS policies can be pretty big and can change over time.

Now I am using aws_iam_group_policy_attachment as suggested by @bflad. The flopping stopped a little but not completely it seems:

```
resource "aws_iam_group_policy_attachment" "attach-group-policy" {
  provider = "aws.run_as_local_user"
  count = "${length(var.policies)}"
  policy_arn = "${element(var.policies, count.index)}"
  group = "${aws_iam_group.group.name}"
}
```
Call:

```
module "group" {
  source = "../group"

  region = "${var.default_region}"
  group_name = "${local.group}"
  policies = [
                "arn:aws:iam::aws:policy/AmazonS3FullAccess",
                "arn:aws:iam::aws:policy/AmazonEC2FullAccess",
                "arn:aws:iam::aws:policy/AmazonRoute53FullAccess",
                "arn:aws:iam::aws:policy/IAMFullAccess",
                "arn:aws:iam::aws:policy/AmazonVPCFullAccess",
                "arn:aws:iam::aws:policy/AWSCertificateManagerReadOnly"]
}
```

**Comment by apparentlymart** [comment] 2018-10-31 15:03
Hi all,

It looks like the problem you've all seen with the "invalid JSON" error message appearing has the same root cause as #16332, which I believe we've fixed in master for inclusion the forthcoming v0.12.0 release.

**Comment by github4es** [comment] 2019-12-16 22:14
Do we know if there have been any updates on attaching both a managed policy and a custom one to the same role?
