### ISSUE TITLE
Cannot use a module output as list input for another module with ${length(...)}

### ISSUE THREAD

**Issue by maruina** [hashicorp/terraform#8494] opened 2016-08-26 14:52 UTC
Hi there,

I'm trying to pass various modules' output as input to other modules as a list, but I have an error when I try to count the list length. It works if I hardcode the module outputs.

### Terraform Version
`Terraform v0.7.2`

### Affected Resource(s)

Core?

### Terraform Configuration Files
`main.tf`
```hcl
variable "environment" {
  default = "Development"
}

variable "vpc_name" {
  default = "Development"
}

module "test_bucket" {
  source = "modules/s3"

  bucket        = "my-test-bucket"
  environment   = "${var.environment}"
  force_destroy = "true"
  vpc_name      = "${var.vpc_name}"
}

module "test_user" {
  source = "modules/user"

  name          = "bob@example.com"
  user_policies = ["${module.test_bucket.write_policy}"]
}
```
`modules/s3/main.tf`
```hcl
variable "bucket" {
  type = "string"
}

variable "acl" {
  type    = "string"
  default = "private"
}

variable "vpc_name" {
  type = "string"
}

variable "manager" {
  type    = "string"
  default = "Terraform"
}

variable "environment" {
  type = "string"
}

variable "versioning_enabled" {
  type    = "string"
  default = "true"
}

variable "force_destroy" {
  type    = "string"
  default = "false"
}

output "read_policy" {
  value = "${aws_iam_policy.read.arn}"
}

output "write_policy" {
  value = "${aws_iam_policy.write.arn}"
}

resource "aws_s3_bucket" "bucket" {
  bucket = "${var.bucket}"
  acl    = "${var.acl}"

  tags {
    VPC         = "${var.vpc_name}"
    Manager     = "${var.manager}"
    Environment = "${var.environment}"
  }

  versioning {
    enabled = "${var.versioning_enabled}"
  }
}

resource "aws_iam_policy" "read" {
  name = "${lower(replace(var.bucket,".","-"))}-read"

  policy = <<EOP
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
      	"s3:ListBucket",
      	"s3:GetBucketLocation",
      	"s3:GetObject",
      	"s3:GetObjectVersion"
      ],
      "Effect": "Allow",
      "Resource": "${aws_s3_bucket.bucket.arn}"
    }
  ]
}
EOP
}

resource "aws_iam_policy" "write" {
  name = "${lower(replace(var.bucket,".","-"))}-write"

  policy = <<EOP
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["*"],
      "Effect": "Allow",
      "Resource": "${aws_s3_bucket.bucket.arn}"
    }
  ]
}
EOP
}
```
`modules/user/main.tf`
```hcl
variable "name" {
  type = "string"
}

variable "force_destroy" {
  type    = "string"
  default = "true"
}

variable "user_policies" {
  type    = "list"
  default = []
}

resource "aws_iam_user" "user" {
  name          = "${var.name}"
  force_destroy = "${var.force_destroy}"
}

resource "aws_iam_user_policy_attachment" "user" {
  count      = "${length(var.user_policies)}"
  user       = "${aws_iam_user.user.name}"
  policy_arn = "${element(var.user_policies, count.index)}"
}
```

### Expected Behavior
```bash
+ module.test_user.aws_iam_user_policy_attachment.user
    policy_arn: "arn:aws:iam::<ARN>:policy/<POLICY>"
    user:       "bob@example.com"
```

### Actual Behavior
```bash
Error configuring: 1 error(s) occurred:

* strconv.ParseInt: parsing "${length(var.user_policies)}": invalid syntax
```

### Steps to Reproduce
1.  Copy the above code
2. `terraform plan`

### Important Factoids
Other working configurations
```hcl
  user_policies = []
```
that doesn't add any policy, and
```hcl
  user_policies = ["arn:aws:iam::<ARN>:policy/<POLICY>"]
```
If I hardcode the policy, it works.

**Comment by martin-flaregames** [comment] 2016-08-29 14:38
this may be a duplicate of issues [8524](https://github.com/hashicorp/terraform/issues/8524) and [8415](https://github.com/hashicorp/terraform/issues/8415).

I'm afraid that this is also related with the old limitation that you cannot refer other resources for calculating the count property.

**Comment by maruina** [comment] 2016-08-30 13:38
I found a workaround! If I create a new variable with the explicit list length, it works!
`main.tf`
```hcl
module "test_user" {
  source = "modules/user"

  name          = "bob@example.com"
  counter       = 1
  user_policies = ["${module.test_bucket.write_policy}"]
}
```
`modules/user/main.tf`
```hcl
variable "name" {
  type = "string"
}

variable "force_destroy" {
  type    = "string"
  default = "true"
}

variable "counter" {
  default = 0
}

variable "user_policies" {
  type    = "list"
  default = []
}

resource "aws_iam_user" "user" {
  name          = "${var.name}"
  force_destroy = "${var.force_destroy}"
}

resource "aws_iam_user_policy_attachment" "user" {
  count      = "${var.counter}"
  user       = "${aws_iam_user.user.name}"
  policy_arn = "${element(var.user_policies, count.index)}"
}
```

**Comment by mitchellh** [comment] 2016-08-31 19:21
Dup of #3888! I've been tracking these down since there are so many so similar and while some are unique this appears to be fully related to #3888.

**Closed by mitchellh** 2016-08-31 19:21 UTC
Labels: bug, core
