### ISSUE TITLE
It happened crash after upgrade the version to 1.8.0

### ISSUE THREAD

**Issue by jinsekim** [hashicorp/terraform#34976] opened 2024-04-11 07:19 UTC
### Terraform Version

```shell
1.8.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: no expansion has been registered for module.cert_lb
goroutine 19550 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:84 +0x18b
panic({0x7213d00?, 0xc00592bef0?})
	/Users/runner/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandAbsModuleCall(0x734ed40?, {{0x0, 0x0, 0x0}, {{}, {0xc00013c8d0, 0x7}}})
	/Users/runner/work/terraform/terraform/internal/instances/expander.go:171 +0x265
github.com/hashicorp/terraform/internal/terraform.(*evaluationStateData).GetModule(0xc00159d560, {{}, {0xc00013c8d0?, 0x4a5f547?}}, {{0xc00072a970, 0xf}, {0x3b, 0x1e, 0x892}, {0x3b, ...}})
	/Users/runner/work/terraform/terraform/internal/terraform/evaluate.go:398 +0x788
github.com/hashicorp/terraform/internal/lang.(*Scope).evalContext(0xc00159d5f0, {0xc00aa8d320, 0x5, 0x5}, {0x0, 0x0})
	/Users/runner/work/terraform/terraform/internal/lang/eval.go:381 +0x1112
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalContext(...)
	/Users/runner/work/terraform/terraform/internal/lang/eval.go:245
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalBlock(0xc00159d5f0, {0x78fb640, 0xc002ac4730}, 0xc004d29980)
	/Users/runner/work/terraform/terraform/internal/lang/eval.go:58 +0xc5
github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).EvaluateBlock(0x1?, {0x78fb8d0, 0xc00123edc0}, 0xc004d29980, {0x0?, 0x0?}, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...})
	/Users/runner/work/terraform/terraform/internal/terraform/eval_context_builtin.go:315 +0x145
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc005e24248, {0x791b128, 0xc000e2ec30}, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0?})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_abstract_instance.go:808 +0xb8b
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc005dd7340, {0x791b128, 0xc000e2ec30})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:250 +0x1395
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x18?, {0x791b128?, 0xc000e2ec30?}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:75 +0x8a
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc003821cc0, {0x791b128, 0xc000e2ec30}, {0x554ec930, 0xc005dd7340})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:153 +0xbb
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x7880a60, 0xc005dd7340})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:112 +0x62a
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc005d896e0, {0x7880a60, 0xc005dd7340}, 0xc00579f1c0)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 15667
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xff3
```

### Expected Behavior

Nothing should have happened.

### Actual Behavior

It happened crash

### Steps to Reproduce

terraform plan

**Comment by liamcervante** [comment] 2024-04-11 12:24
Hi @georgepstaylor, thanks for the info! Do you have a reproducible config for the crash? I haven't been able to reproduce it yet so can't provide any guidance or potential workarounds at the moment. Thanks!

**Comment by jinsekim** [comment] 2024-04-11 14:18
```
resource "aws_route53_record" "cert_lb" {
  provider = aws.route53
  zone_id  = local.service_dns_zone_id
  name     = format("cert-%s.%s", var.aws_region, local.service_dns_name)
  type     = "A"

  alias {
    name                   = module.cert_lb["nlb"].dns
    zone_id                = module.cert_lb["nlb"].zone_id
    evaluate_target_health = false
  }
}
```
@liamcervante I did run to the route53 record code. The 1.8.0 version had a crash problem. However, the 1.7.5 version did not have any issues.

**Comment by liamcervante** [comment] 2024-04-11 14:25
Thanks @jinsekim, are there any other resources within the same module as that resource? Can you share the `module` block that calls it as well.

Based on the stack trace, I think Terraform is trying to access an output of the module before the module has executed. So the contents of the module, the module call itself, and anything referencing the module call would be helpful. Hopefully, it's not complicated!

Thanks!

**Comment by georgepstaylor** [comment] 2024-04-11 14:30
> Hi @georgepstaylor, thanks for the info! Do you have a reproducible config for the crash? I haven't been able to reproduce it yet so can't provide any guidance or potential workarounds at the moment. Thanks!

Hi @liamcervante.

https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/delius-core 
The project here causes a crash when applying.

```

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: no expansion has been registered for module.environment_dev[0].module.oracle_db_primary
goroutine 6115 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:84 +0x18b
panic({0x2e00120?, 0xc00a84ce10?})
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandAbsModuleCall(0x2f3a180?, {{0xc007b6c9c0, 0x1, 0x2}, {{}, {0xc0012e1f08, 0x11}}})
	/home/runner/work/terraform/terraform/internal/instances/expander.go:171 +0x265
github.com/hashicorp/terraform/internal/terraform.(*evaluationStateData).GetModule(0xc00d85e5a0, {{}, {0xc0012e1f08?, 0x7?}}, {{0xc00098cea0, 0x26}, {0x64, 0x5e, 0xc4d}, {0x64, ...}})
	/home/runner/work/terraform/terraform/internal/terraform/evaluate.go:398 +0x788
github.com/hashicorp/terraform/internal/lang.(*Scope).evalContext(0xc00d85e630, {0xc00d955488, 0x3, 0x3}, {0x0, 0x0})
	/home/runner/work/terraform/terraform/internal/lang/eval.go:381 +0x1112
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalContext(...)
	/home/runner/work/terraform/terraform/internal/lang/eval.go:245
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalExpr(0xc00d85e630, {0x3d75c00, 0xc000c12ae0}, {{0x3d75ce0?, 0x5891580?}})
	/home/runner/work/terraform/terraform/internal/lang/eval.go:170 +0x9e
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).evalModuleVariable(0xc009daaee0, {0x3d984a8?, 0xc0006bdd10?}, 0xd8?)
	/home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:275 +0x1a5
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0xc009daaee0, {0x3d984a8, 0xc0006bdd10}, 0x1)
	/home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:214 +0x1c8
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc004d688c0, {0x3d984a8, 0xc0006bdd10}, {0x7f5f296fbd00, 0xc009daaee0})
	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:153 +0xbb
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x31d97a0, 0xc009daaee0})
	/home/runner/work/terraform/terraform/internal/terraform/graph.go:112 +0x62a
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000f66780, {0x31d97a0, 0xc009daaee0}, 0xc009df00c0)
	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 3929
	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xff3
```

The module source can be found here: https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/delius-core/modules/components/oracle_db_instance

Not sure if that's helpful?

**Comment by arkaitzj** [comment] 2024-04-11 16:16
Observing the same issue in TerraformCloud, workspaces fixed to 1.7.5 doing ok but those at "latest" are crashing with "no expansion..." on module "terraform-aws-modules/rds-aurora/aws"

**Comment by liamcervante** [comment] 2024-04-11 16:16
Is there anything particular about the commands you execute that cause the crash? Is it just a normal `terraform plan` operation, or is this during the apply stage? And, are you planning/applying this with an empty state file, or do you have partial state that is being updated?

**Comment by arkaitzj** [comment] 2024-04-11 16:21
@liamcervante its just a PR plan using TerraformCloud, I just had a the dev workspace pinned to 1.7.5 and stage,prod where pinned latest. stage and prod started failing today when just re-running master branch, with no changes.
There was ongoing state in TFC.

**Comment by georgepstaylor** [comment] 2024-04-11 16:25
> Is there anything particular about the commands you execute that cause the crash? Is it just a normal `terraform plan` operation, or is this during the apply stage? And, are you planning/applying this with an empty state file, or do you have partial state that is being updated?

This only occurs during the apply stage - plan goes through just fine. State is stored in S3.

**Comment by MatLambethMS** [comment] 2024-04-11 21:07
+ 1 from me. We are seeing the same on a `terraform plan`.

**Comment by jinsekim** [comment] 2024-04-12 05:04
@liamcervante If it not using a module, this problem will not happen in the terraform plan. But I can't apply for the terraform plan because of our production environment.

**Comment by MatLambethMS** [comment] 2024-04-12 08:34
Thanks @liamcervante. Yes, this pattern is a perfect match for my code set failing under 1.8.0.

**Comment by georgepstaylor** [comment] 2024-04-12 09:20
> Thanks everyone for your input! We do have a small potential reproduction case:
> 
> ```
> # ./mod/main.tf
> 
> output "out" {
>   value = "test"
> }
> ```
> 
> ```
> # ./main.tf
> 
> 
> data "http" "get" {
>   url = "https://httpbin.org/delay/1?pause=1"
> }
> 
> 
> module "a" {
>   depends_on = [data.http.get]
>   source     = "./mod"
> }
> 
> output "value" {
>   value = try(module.a.NOT_AN_OUTPUT, null)
> }
> ```
> 
> This results in the same stack trace as reported in this thread. This is likely caused by the invalid reference within the `try(...)` function not properly registering itself as a dependent on the module. Unfortunately, this particular reproduction doesn't match the pattern of some of the examples shared in this thread but hopefully they'll have the same root cause.
> 
> I will keep looking to see if I can cause the panic with an alternate reference pattern while also looking to fix the reproduction case we have found. In the mean time, if anyone can produce a similar sized reproduction that shows a reference outside the `try` function that would help me confirm any fix for this covers everything.
> 
> Thanks!

I've checked my failing codebase and I confident there's no `try` used - The only evidence of any dependencies within a function is `length(module.<name>)`

**Comment by liamcervante** [comment] 2024-04-12 10:54
@georgepstaylor, I'm inclined to agree in that I think there is something else triggering this in your case. Luckily, I do have another potential reproduction that I think matches your config:

```
# ./mod/main.tf

#
# Nothing, just an empty file.
#
```

```
# ./main.tf

module "a" {
  source     = "./mod"
  count = 1
}

resource "tfcoremock_simple_resource" "resource" {
    number = length(module.a)
}
```

In this case the crash is triggered during `terraform apply` instead of during `terraform plan`, which I think matches the behaviour you are seeing. It's my belief that the empty module simulates a module that has no changes, which causes it not to execute at all during the apply operation and then when the resource (or in your case second module) attempts to reference it we get the crash as it seemingly doesn't exist.

**Comment by liamcervante** [comment] 2024-04-12 11:08
In both of these cases, the triggering commit is https://github.com/hashicorp/terraform/commit/9851cd45.

Essentially we now require the modules to be properly evaluated before things can reference them, while previously we were looking at the in-memory state file directly. In both cases the triggering thing is that the parent module is either not referenced correctly (because the output doesn't exist) or is not being executed (because it has no changes), both of which mean the reference is being evaluated without the module being referenced getting processed first.

This wasn't exposed before because we were just inspecting the state, so it didn't matter that the module itself wasn't being processed as in both cases whatever values in the state were acceptable and correct.

We will have these fixed for the next `v1.8.1` release. Thanks everyone for your feedback, comments and reproductions!

**Comment by arkaitzj** [comment] 2024-04-12 11:10
Thanks @liamcervante, when could we expect the releases of 1.8.1?

**Comment by liamcervante** [comment] 2024-04-12 11:35
> when could we expect the releases of 1.8.1

We're aiming for Wednesday 17th April (next week), but that could be delayed depending on how long the fix for this takes.

**Comment by georgepstaylor** [comment] 2024-04-12 11:45
> @georgepstaylor, I'm inclined to agree in that I think there is something else triggering this in your case. Luckily, I do have another potential reproduction that I think matches your config:
> 
> ```
> # ./mod/main.tf
> 
> #
> # Nothing, just an empty file.
> #
> ```
> 
> ```
> # ./main.tf
> 
> module "a" {
>   source     = "./mod"
>   count = 1
> }
> 
> resource "tfcoremock_simple_resource" "resource" {
>     number = length(module.a)
> }
> ```
> 
> In this case the crash is triggered during `terraform apply` instead of during `terraform plan`, which I think matches the behaviour you are seeing. It's my belief that the empty module simulates a module that has no changes, which causes it not to execute at all during the apply operation and then when the resource (or in your case second module) attempts to reference it we get the crash as it seemingly doesn't exist.

That matches up with exactly the situation we've got - thanks for looking into this!

**Closed** 2024-04-15 08:28 UTC
Labels: bug, confirmed, explained
