### ISSUE TITLE
Support for AzureRM Resource Extensions 

### ISSUE THREAD

**Issue by Felivel** [hashicorp/terraform#6156] opened 2016-04-13 13:27 UTC
I think it would be great if Terraform supported Resource Extensions, to configure the virtual machines in AzureRM. Is there something in the works for this feaute? What the current solution to provision and configure machines in Azure RM?

```
{
  "id":"/subscriptions/########-####-####-####-############/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{virtualMachineName}/extensions/{extensionName}",
  "name": "extensionName",
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "location": "westus",
  "properties": {
    "publisher": "Microsoft.OSTCExtensions",
    "type": "CustomScriptForLinux",
    "typeHandlerVersion": "1.2",
    "settings": {
      "fileUris": [ "scriptFilePpath"],
      "commandToExecute": "command"
    }
  }
}
```
More info here:
https://msdn.microsoft.com/en-us/library/azure/mt163680.aspx

Thanks,
Felivel

**Comment by Felivel** [comment] 2016-04-13 13:29
This is related to issues #6117  #5820

**Comment by stack72** [comment] 2016-04-13 15:09
Hi @Felivel 

I am going to close this as a duplicate of #5820 - having 1 place to track it all will be much better to keep everyone informed
 
It will be taken care of as soon as some bugs are fixed in the VM resource

Thanks

Paul

**Closed by stack72** 2016-04-13 15:09 UTC
