### ISSUE TITLE
Cannot create EC2 tags containing "."

### ISSUE THREAD

**Issue by justinsb** [hashicorp/terraform#7079] opened 2016-06-08 16:12 UTC
I'm trying to create an EBS volume with a tag "a.b" = "c"

However, it looks like the value is not recognized when the key has a dot.  A tag is created with the correct name but an empty value.  I've tried escaping the dot but can't find the magic syntax.

Here's a short repro:

```
resource "aws_ebs_volume" "myvolume" {
  availability_zone = "us-east-1b"
  size = 20
  type = "gp2"

  tags = {
    "a.b" = "c"
  }
}
```

```
 ~/bin/terraform/terraform plan
...
+ aws_ebs_volume.myvolume
    availability_zone: "" => "us-east-1b"
    encrypted:         "" => "<computed>"
    iops:              "" => "<computed>"
    kms_key_id:        "" => "<computed>"
    size:              "" => "20"
    snapshot_id:       "" => "<computed>"
    tags.#:            "" => "1"
    tags.a.b:          "" => ""
    type:              "" => "gp2"


Plan: 1 to add, 0 to change, 0 to destroy.
```

After `terraform apply`, `aws ec2 describe-volumes` shows

```
    {
            "AvailabilityZone": "us-east-1b", 
            "Attachments": [], 
            "Tags": [
                {
                    "Value": "", 
                    "Key": "a.b"
                }
            ], 
            "Encrypted": false, 
            "VolumeType": "gp2", 
            "VolumeId": "vol-e9cdf967", 
            "State": "available", 
            "Iops": 60, 
            "SnapshotId": "", 
            "CreateTime": "2016-06-08T16:10:16.686Z", 
            "Size": 20
        }

```

The value should be `c`, but is empty.

Changing the key to `ab` (no dot) works correctly.

**Comment by radeksimko** [comment] 2016-06-08 17:43
Thanks for the report, I'm closing as a duplicate of https://github.com/hashicorp/terraform/issues/2143
I think this may actually be fixed in `master` (& `0.7.0rc`), but we'll need to verify before closing https://github.com/hashicorp/terraform/issues/2143

**Closed by radeksimko** 2016-06-08 17:43 UTC
Labels: bug, core
