### ISSUE TITLE
Terraform DNS issue ? socket is not connected

### ISSUE THREAD

**Issue by imsathyakumar** [hashicorp/terraform#33039] opened 2023-04-14 16:49 UTC
### Terraform Version

```shell
Terraform v1.4.5
on darwin_arm64
```

### Terraform Configuration Files

```terraform
resource "aws_s3_bucket" "test_tf" {
  bucket = "this-is-for-testing-socket-issues"
}

terraform {

  required_version = ">= 0.13.1"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">=3.70.0"
    }
  }
}
```

### Debug Output

```
2023-04-14T09:42:16.270-0700 [INFO]  Terraform version: 1.4.5
2023-04-14T09:42:16.271-0700 [DEBUG] using github.com/hashicorp/go-tfe v1.18.0
2023-04-14T09:42:16.271-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
2023-04-14T09:42:16.271-0700 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-04-14T09:42:16.271-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-04-14T09:42:16.271-0700 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-04-14T09:42:16.271-0700 [INFO]  Go runtime version: go1.19.6
2023-04-14T09:42:16.271-0700 [INFO]  CLI args: []string{"/opt/homebrew/Cellar/tfenv/3.0.0/versions/1.4.5/terraform", "init"}
2023-04-14T09:42:16.271-0700 [TRACE] Stdout is a terminal of width 190
2023-04-14T09:42:16.271-0700 [TRACE] Stderr is a terminal of width 190
2023-04-14T09:42:16.271-0700 [TRACE] Stdin is a terminal
2023-04-14T09:42:16.271-0700 [DEBUG] Attempting to open CLI config file: /Users/sathkuma/.terraformrc
2023-04-14T09:42:16.271-0700 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-04-14T09:42:16.271-0700 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-04-14T09:42:16.271-0700 [DEBUG] ignoring non-existing provider search directory /Users/sathkuma/.terraform.d/plugins
2023-04-14T09:42:16.271-0700 [DEBUG] ignoring non-existing provider search directory /Users/sathkuma/Library/Application Support/io.terraform/plugins
2023-04-14T09:42:16.271-0700 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2023-04-14T09:42:16.272-0700 [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2023-04-14T09:42:16.279-0700 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2023-04-14T09:42:16.279-0700 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2023-04-14T09:42:16.280-0700 [DEBUG] New state was assigned lineage "45496f12-30d0-5a4c-d261-8cbebf7c0f82"
2023-04-14T09:42:16.280-0700 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2023-04-14T09:42:16.280-0700 [TRACE] Meta.Backend: instantiated backend of type <nil>
2023-04-14T09:42:16.280-0700 [DEBUG] checking for provisioner in "."
2023-04-14T09:42:16.280-0700 [DEBUG] checking for provisioner in "/opt/homebrew/Cellar/tfenv/3.0.0/versions/1.4.5"
2023-04-14T09:42:16.280-0700 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2023-04-14T09:42:16.280-0700 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-04-14T09:42:16.280-0700 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-04-14T09:42:16.280-0700 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-04-14T09:42:16.280-0700 [TRACE] statemgr.Filesystem: read nil snapshot

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 3.70.0"...
2023-04-14T09:42:16.282-0700 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2023-04-14T09:42:16.283-0700 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: could not connect to registry.terraform.io: failed to request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": write tcp [2600:1700:42d1:47c0:e970:ac3d:167d:7ff0]:49978->[2600:9000:20be:ce00:16:1aa3:1440:93a1]:443: write: socket is not
│ connected
╵
```

### Expected Behavior

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

### Actual Behavior

```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 3.70.0"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: could not connect to registry.terraform.io: failed to request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": write tcp [2600:1700:42d1:47c0:e970:ac3d:167d:7ff0]:49907->[2600:9000:20be:e00:16:1aa3:1440:93a1]:443: write: socket is not
│ connected
╵
```

### Steps to Reproduce

When the `terraform init` is run on a local network, it works as expected. The moment our Corporate VPN is connected, we are going through the `socket is not connected` issue. The "https://registry.terraform.io/.well-known/terraform.json" is reachable from `curl` and through the `browser`, but fails only when called from `terraform` cli.

### References

https://github.com/hashicorp/terraform/issues/14821

**Comment by apparentlymart** [comment] 2023-04-15 00:36
Hi @imsathyakumar,

I see that on you system Terraform resolved `registry.terraform.io` to an IPv6 IP address. Does your corporate VPN support IPv6?

Unfortunately we can't typically help with connectivity problems on specific networks because we cannot access those networks to debug. It may be better to contact your IT department and ask for their help to diagnose this. If their conclusion is that Terraform is misbehaving in some specific way that is making this fail then we can hopefully attempt to solve that misbehavior, but we cannot determine what that misbehavior might be, or whether the problem is actually elsewhere, such as a lack of IPv6 support on your network.

Thanks!

**Comment by drowley** [comment] 2023-04-17 04:48
I ran into this problem on OSX and a company VPN.  I suspect the root cause is the VPN handling of ipv6, which isn't going to get resolved quickly.  In the mean time, I ping the host for the ipv4 address, then add that to my /etc/hosts

**Comment by crw** [comment] 2023-04-17 22:30
Thanks for the confirmation! I'll close this issue since it does not seem to be a Terraform-specific issue. Thanks!

**Closed by crw** 2023-04-17 22:30 UTC
Labels: bug, waiting-response, new
