### ISSUE TITLE
Terraform crash when terraform apply with empty map

### ISSUE THREAD

**Issue by chfrodin** [hashicorp/terraform#21315] opened 2019-05-15 07:15 UTC
### Terraform Version

```
Terraform v0.12.0-rc1
+ provider.azurerm v1.27.1
```

### Terraform Configuration Files

```hcl

main.tf:
connection_string {
    name  = var.connection_string_name
    type  = var.connection_string_type
    value = var.connection_string_value
  }

variables.tf:
variable "connection_string_name" {
  description = "The name of the Connection String."
  type = string
  default = null
}
variable "connection_string_type" {
  description = "The type of the Connection String. Possible values are APIHub, Custom, DocDb, EventHub, MySQL, NotificationHub, PostgreSQL, RedisCache, ServiceBus, SQLAzure and SQLServer."
  type = string
  default = null
}
variable "connection_string_value" {
  description = "The value for the Connection String."
  type = string
  default = null
}
```

### Crash Output

https://gist.github.com/chfrodin/b905187aead298d48b94b43f063e1510

### Expected Behavior

Terraform apply should have created the resource azurerm_function_app with connection string as null.
### Actual Behavior

Crash during creation of resource
### Steps to Reproduce

terraform apply

**Comment by jbardin** [comment] 2019-05-15 13:05
Hi @chfrodin,

Thanks for reporting this. We'll have to see what we can do in the sdk to make it easier for the provider to handle this case and prevent a crash, but I don't think the config you have here is going to do what you intended.

This configuration is not setting a `null``connection_string`, it's setting a single `connection_string` block containing 3 `null` values. You may be able to solve this using a [dynamic block](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) to only conditionally set the entire `connection_string`.

**Comment by apparentlymart** [comment] 2019-05-15 14:08
From looking at [the relevant code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.27.1/azurerm/resource_arm_function_app.go#L679-L697), it seems like `d.Get("connection_string")` is returning a slice with a `nil` value inside it, which I assume is a result of the SDK shim logic turning the block with everything null inside into a null block, although in this particular case a non-null map with the arguments all absent inside is probably what this provider code was expecting. :confounded: 

With that said, this seems like something where if we were to change the shim logic here we'd probably create a regression in some other provider that is making an opposite assumption, so the safest answer here would be to change the logic for this in the Azure provider to check whether the value is `nil` and treat it like an empty map if so, since then we can fix this specific crash without risk of impacting already-working code in another provider.

**Comment by jbardin** [comment] 2019-05-15 15:05
Looking at the azure provider code, it isn't doing anything unusual, so moving the fix to the provider would mean requiring all providers to make a special case for nil when accessing blocks.

While 0.11 doesn't have the concept of `null`, it does allow a construct which can approximate this behavior. I'll see if we can't generate the same diff and determine what the existing behavior should look like.

**Comment by jbardin** [comment] 2019-05-15 15:26
Interestingly 0.11 will produce the same error, so a fix for this in the protocol shims may cause an issue. 

What is not being caught is that the fields are required, but unset when it comes time to apply, which we should be able to catch in validation at some point.

**Comment by apparentlymart** [comment] 2019-05-15 16:21
If this was already failing before, I think that's all the more reason to just patch the provider here. If this problem were common we'd see it come up in other situations too. I'd rather just patch the one instance we know about than try to fix this generally when the behavior was pre-existing and so possibly other providers are depending on it somehow.

**Comment by jbardin** [comment] 2019-05-15 16:34
The difference here is with the addition of the `null` concept, which makes it easier for the completely empty value to make it through where it's not expected. In 0.11 there would be no way to assign a value as unset, so the situation is very unlikely to arise.

One reason this config isn't rejected outright is related to #21225; the validated config shows the values as being unknown rather than unset. A new idea that we could explore which wasn't easily achievable in the old API, is to revalidate one all values are known. This would prevent the class of errors caused by invalid interpolated values (now including `null`) from being applied at all.

**Closed** 2019-06-07 20:43 UTC
Labels: provider-sdk
