### ISSUE TITLE
"for_each" not working in a scenario from terraform docs

### ISSUE THREAD

**Issue by michal-rybinski** [hashicorp/terraform#27044] opened 2020-11-26 12:41 UTC
### Terraform Version

```
Terraform v0.13.5

hashicorp/aws: version = "~> 3.17.0"
MacOS 11
```

### Terraform Configuration Files

```terraform
data "aws_subnet_ids" "mg_vpc_subnet_ids" {
  vpc_id = aws_vpc.mg_vpc.id
}

resource "aws_route_table_association" "mg_route_table_association" {
  for_each       = data.aws_subnet_ids.mg_vpc_subnet_ids.ids
  subnet_id      = each.value
  route_table_id = aws_route_table.mg_route_table.id
}
```

### Expected Behavior

terraform plan/apply succeeds

### Actual Behavior

```
Error: Invalid for_each argument

  on ../../../modules/MediaGuardVPC/main.tf line 73, in resource "aws_route_table_association" "mg_route_table_association":
  73:   for_each       = data.aws_subnet_ids.mg_vpc_subnet_ids.ids

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

### Steps to Reproduce

1. terraform init
2. terraform plan
3. no profit...

### Additional Context

I've encountered strange terraform behaviour and am not sure why.

I am writing a module that spins up a VPC with network plumbing and along those things are route table and route table association where I use for_each to iterate through subnets in vpc.
What I am trying looks exactly like it is described in the example which is in terraform docs (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet_ids):

```
data "aws_subnet_ids" "private" {
  vpc_id = var.vpc_id

  tags = {
    Tier = "Private"
  }
}

resource "aws_instance" "app" {
  for_each      = data.aws_subnet_ids.example.ids
  ami           = var.ami
  instance_type = "t2.micro"
  subnet_id     = each.value
}
```
(apart from the error in docs refering to example instead of private)

When trying to run terraform plan, my code generates the error posted above, I am a bit at a loss of why it is not able to calculate it.

### References

I've been redirected from aws provider to here as they do not see it being connected with the provider itself.
https://github.com/hashicorp/terraform-provider-aws/issues/16437

Thanks,
Michal

**Comment by alisdair** [comment] 2020-11-26 15:30
Hi @michal-rybinski, thanks for the report.

I'm not able to reproduce this issue on Terraform 0.13.5. Here's what I did:

Created a VPC with some subnets using this configuration:

```hcl
provider "aws" {
  region = "us-east-1"
}

locals {
  cidrs = {
    backend: "10.0.0.0/24",
    database: "10.0.1.0/24",
    frontend: "10.0.2.0/24",
  }
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Tier = "Private"
  }
}

resource "aws_subnet" "main" {
  for_each = local.cidrs
  vpc_id     = aws_vpc.main.id
  cidr_block = each.value

  tags = {
    Name = each.key
  }
}

output "vpc_id" {
  value = aws_vpc.main.id
}
```

Manually copied over the output of the VPC ID to a configuration like the one in your reproduction case:

```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_subnet_ids" "private" {
  vpc_id = "vpc-032a14ec310fc3afe"
}

resource "aws_instance" "app" {
  for_each      = data.aws_subnet_ids.private.ids
  ami           = "ami-0f40c8f97004632f9"
  instance_type = "t3.micro"
  subnet_id     = each.value
}
```

Ran `terraform plan`, which refreshed the data source and rendered a plan:

```shellsession
$ terraform-0.13.5 plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_subnet_ids.private: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_instance.app["subnet-01c7a5b8ed425bac6"] will be created
  + resource "aws_instance" "app" {
      + ami                          = "ami-0f40c8f97004632f9"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)

# (logs truncated…)
```

Are you able to reproduce the issue with a similar reduced configuration? If so, please let me know what changes to make, and I'll try to reproduce again.

As noted in the reply to your AWS provider issue, improving the use of data sources during plan has been a focus of the 0.14 work. If possible, please try out [the 0.14.0-rc1 release](https://releases.hashicorp.com/terraform/0.14.0-rc1/) (with a scrap/test configuration) to see if it fixes your issue—I hope it will!

**Comment by michal-rybinski** [comment] 2020-11-26 15:50
Hi alisdair,

Thank you for looking into it.

Couple of points here.
- my code is the one creating route table associations, not the one from docs creating ec2 instance which I've provided for reference
- my code is in one file inside a module and the idea is to have all resources created at the same time, hence the situation that all resources are being resolved inside a one terraform plan run and the vpc/subnets do not exist before the run
- I am not using static local variables but pulling data from data source to create subnets - that's something I haven't provided info on and I am sorry as this might be important in this case

```
data "aws_availability_zones" "available" {}

resource "aws_subnet" "mg_subnet" {
  count                   = length(data.aws_availability_zones.available.names)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  cidr_block              = "${substr(var.cidr_block,0,5)}.${count.index}.0/24"
  vpc_id                  = aws_vpc.mg_vpc.id
  map_public_ip_on_launch = var.public_ip_on_launch

  tags = {
    Name                  = "Subnet ${data.aws_availability_zones.available.names[count.index]}"
    Creator               = var.creator
  }
}
```
could you please take those into account and re run your tests?

Thanks,
Michal

**Comment by alisdair** [comment] 2020-11-26 19:18
It's difficult to understand what the issue you're seeing is without a complete reproduction. If you can find a small but complete configuration which demonstrates the issue, we can continue to look into this.

From your last comment, it sounds like your module is creating managed resources, and also attempting to read from a data source which depends on those managed resources. We recommend against doing this, as it does not work reliably (as you've seen).

If the resources are managed by your module, you can use those managed resources as the value for your `for_each` argument, rather than using a data source. If that makes sense but it's not clear how to actually do it, I would recommend [posting a thread on our discussion forum asking for advice](https://discuss.hashicorp.com/c/terraform-core/27).

As far as I understand it, this doesn't seem like a bug in Terraform, so I'm going to close this issue for now. If I've misunderstood and you can supply a reproduction case, I'd be happy to reopen and investigate.

**Closed by alisdair** 2020-11-26 19:18 UTC
Labels: bug, waiting for reproduction

**Comment by michal-rybinski** [comment] 2020-11-30 13:45
I've cut unnecessary stuff and the whole 
module now looks like below:

**main.tf**
```
###### VPC ######

resource "aws_vpc" "mg_vpc" {
  cidr_block                       = var.cidr_block
  instance_tenancy                 = var.tenancy
  enable_dns_support               = var.dns_support
  enable_dns_hostnames             = var.dns_hostnames
  assign_generated_ipv6_cidr_block = var.assign_ipv6
}


###### SUBNETS ######

data "aws_availability_zones" "available" {}

resource "aws_subnet" "mg_subnet" {
  count                   = length(data.aws_availability_zones.available.names)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  cidr_block              = "${substr(var.cidr_block,0,5)}.${count.index}.0/24"
  vpc_id                  = aws_vpc.mg_vpc.id
  map_public_ip_on_launch = var.public_ip_on_launch
}


###### INTERNET GATEWAY ######

resource "aws_internet_gateway" "mg_vpc_igw" {
  vpc_id = aws_vpc.mg_vpc.id
}


###### ROUTE TABLE AND DEFAULT ROUTE ######

resource "aws_route_table" "mg_route_table" {
  vpc_id       = aws_vpc.mg_vpc.id
}

resource "aws_route" "mg_default_route_igw" {
  route_table_id            = aws_route_table.mg_route_table.id
  destination_cidr_block    = "0.0.0.0/0"
  gateway_id                = aws_internet_gateway.mg_vpc_igw.id
  depends_on                = [aws_route_table.mg_route_table,aws_internet_gateway.mg_vpc_igw]
}


###### ROUTE TABLE ASSOCIATIONS TO SUBNETS ######

data "aws_subnet_ids" "mg_vpc_subnet_ids" {
  vpc_id = aws_vpc.mg_vpc.id
}

resource "aws_route_table_association" "mg_route_table_association" {
  for_each       = data.aws_subnet_ids.mg_vpc_subnet_ids.ids
  subnet_id      = each.value
  route_table_id = aws_route_table.mg_route_table.id
}


######
```


**input.tf**
```
variable "client_id"                 {}
variable "creator"                   {}
variable "cidr_block"                { default = "10.50.0.0/16" }
variable "tenancy"                   { default = "default" }
variable "dns_support"               { default = "true" }
variable "dns_hostnames"             { default = "true" }
variable "assign_ipv6"               { default = "false" }
variable "public_ip_on_launch"       { default = "true" }
```

and the invocation of it: 

**vpc.tf**
```
module "mg_vpc" {
  source = "../../../modules/mgVPC"

  ## the ID of a client to create the VPC for (mandatory)
  client_id           = "666666"

  ## VPC creator (mandatory) VPC creator
  creator             = "john@smith.com"
}
```

The result:

```
bash-3.2$ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/aws v3.17.0

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/aws: version = "~> 3.17.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
bash-3.2$
bash-3.2$ terraform plan
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.mg_vpc.data.aws_availability_zones.available: Refreshing state...

------------------------------------------------------------------------

Error: Invalid for_each argument

  on ../../../modules/mgVPC/main.tf line 54, in resource "aws_route_table_association" "mg_route_table_association":
  54:   for_each       = data.aws_subnet_ids.mg_vpc_subnet_ids.ids

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

Releasing state lock. This may take a few moments...
bash-3.2$
```

I am guessing it should be fairly easy to reproduce from it?

**Comment by michal-rybinski** [comment] 2020-11-30 14:55
if I change the **ROUTE TABLE ASSOCIATIONS TO SUBNETS** part to use count without "data" resource:

```terraform
###### ROUTE TABLE ASSOCIATIONS TO SUBNETS ######

resource "aws_route_table_association" "mg_route_table_association" {
  count          = length(data.aws_availability_zones.available.names)
  subnet_id      = element(aws_subnet.mg_subnet.*.id, count.index)
  route_table_id = aws_route_table.mg_route_table.id
}
```

it compiles fine and works as expected, but I still fail to grasp why it doesn't work same way when using for_each... I guess that's just the way it is...

**Comment by ChristophShyper** [comment] 2020-12-03 10:30
According to https://github.com/hashicorp/terraform/issues/26078#issuecomment-710060287 they abandoned this functionality with 0.13:
```
With how Terraform works at present, we consider this sort of configuration to be incorrect. Using resource computed outputs as arguments to count and for_each is not recommended. Instead, using variables or derived local values which are known at plan time is the preferred approach. If you choose to go ahead with using computed values for count/for_each, this will sometimes require you to work around this using -target as illustrated above.
```

**Comment by michal-rybinski** [comment] 2020-12-03 10:40
great.. thanks Krzysiek!
