### ISSUE TITLE
lbaas API version

### ISSUE THREAD

**Issue by russStarr** [hashicorp/terraform#3598] opened 2015-10-22 16:34 UTC
I am using the following TF (v0.6.5) configuration to test the creation of an LBaaS pool and VIP.

```
resource "openstack_lb_pool_v1" "pool_1" {
  region = "RegionOne"
  name = "my_lbaas_pool"
  protocol = "TCP"
  subnet_id = "0b5381a8-46a8-4375-97c2-c7e326f30e0e"
  lb_method = "ROUND_ROBIN"
  member {
    address = "192.168.40.10"
    port = 80
    admin_state_up = "true"
  }
}

resource "openstack_lb_vip_v1" "vip_1" {
  name = "my_lbaas_vip"
  subnet_id = "0b5381a8-46a8-4375-97c2-c7e326f30e0e"
  protocol = "HTTP"
  port = 80
  pool_id = "${openstack_lb_pool_v1.pool_1.id}"
}
```

My OpenStack environment is Juno with LBaaS v1.0 API. Here is the error I get from my `terraform apply` command.

```
Error applying plan:

1 error(s) occurred:

* openstack_lb_pool_v1.pool_1: Error creating OpenStack LB pool: Expected HTTP response code [201 202] when accessing [POST http://1.1.1.1:9696/v2.0/lb/pools], but got 404 instead
{"NeutronError": {"message": "An unknown exception occurred.", "type": "NotFound", "detail": ""}}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

If I am reading the POST URL accurately, it seems to be using the v2.0 LBaaS API.

**Comment by jtopjian** [comment] 2015-11-01 00:47
I think the v2.0 in the URL is referring to the Neutron v2 API, not specifically LBaaS. Since you're using Juno, you should be using LBaaS v1.

Can you confirm that LBaaS works outside of Terraform?

If you use the Neutron command-line tool, you can use the `--debug` flag to see what URLs are being accessed. For example:

```shell
$ neutron --debug lb-pool-create ...
```

**Comment by jtopjian** [comment] 2016-05-28 22:54
@russStarr Revisiting this question... I can confirm that the URL you gave is for LBaaS v1.0. The LBaaS v1 API used `/lb/` while the v2 API uses `/lbaas/`. Both are an extension of the Neutron v2 API, so both will have `/v2.0` in their URLs.

I'm going to close this issue, but please feel free to re-open if you have any questions!

**Closed by jtopjian** 2016-05-28 22:54 UTC
Labels: provider/openstack, waiting-response
