### ISSUE TITLE
for_each cannot iterate through fileset in .tf.json

### ISSUE THREAD

**Issue by alanyee** [hashicorp/terraform#27727] opened 2021-02-10 00:47 UTC
### Terraform Version

```
Terraform v0.14.6
```

### Terraform Configuration Files

config.tf.json
```json
"aws_s3_bucket_object": {
  "file": {
    "for_each": "fileset(\"example/\", \"**\")"
```
config.tf
```terraform
resource "aws_s3_bucket_object" "file" {
  for_each = fileset("example/", "**")
  #...
}
```

### Expected Behavior
```
Success! The configuration is valid.
```

### Actual Behavior
```
"for_each": "fileset(\"static-website-example/\", \"**\")",

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type
string.
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. Create a `.tf.json` supplying `fileset` to `for_each`
1. `terraform init`
1.  `terraform validate` or `terraform apply`

**Comment by apparentlymart** [comment] 2021-02-10 01:03
Hi @alanyee,

It looks like you've set `for_each` here to a literal string which just happens to contain something that resembles Terraform expression syntax. Terraform therefore can't tell that you intend for it to evaluate that as an expression and use the result: it's just taking the string literally, which is therefore not a valid `for_each` value.

The [Expression Mapping](https://www.terraform.io/docs/language/syntax/json.html#expression-mapping) section of the JSON syntax documentation describes how the JSON variant of the language considers any JSON string presented in an expression context to be a [string template](https://www.terraform.io/docs/language/expressions/strings.html#string-templates), and also discusses the special rule for when the template consists _only_ of a single interpolation sequence, which causes Terraform to skip trying to convert the interpolation result to a string as it normally would.

Based on that, you should be able to write your `for_each` expression like this:

```json
{
  "for_each": "${fileset(\"example/\", \"**\")}"
}
```

If you have any further questions about this, I'd recommend starting a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), where it's easier to have open-ended discussions about various topics. Since Terraform was behaving as intended in your case, I'm going to close this issue. Thanks!

**Closed by apparentlymart** 2021-02-10 01:03 UTC
Labels: bug, new
