### ISSUE TITLE
Crash on Arch Linux performing tab completion

### ISSUE THREAD

**Issue by ericx** [hashicorp/terraform#31172] opened 2022-06-01 12:56 UTC
### Terraform Version

```
Terraform v1.2.1
on linux_amd64

```

### Terraform Configuration Files

```terraform
[blank -- brand new install]
```

### Expected Behavior

Not entirely sure. 
Ran "terraform -install-autocomplete"
Simply tabbed after "terraform" to see what  would be displayed and it crashed.

### Actual Behavior

$ terraform 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:55 +0x153
panic({0x558ef47a0ec0, 0xc0000528d0})
	runtime/panic.go:844 +0x258
github.com/mitchellh/cli.(*CLI).processArgs(0xc0001968c0)
	github.com/mitchellh/cli@v1.1.3/cli.go:688 +0x9ec
github.com/mitchellh/cli.(*CLI).init(0xc0001968c0)
	github.com/mitchellh/cli@v1.1.3/cli.go:392 +0x3e9
sync.(*Once).doSlow(0xc00005a024?, 0xb?)
	sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/mitchellh/cli.(*CLI).Subcommand(...)
	github.com/mitchellh/cli@v1.1.3/cli.go:276
main.realMain()
	github.com/hashicorp/terraform/main.go:240 +0xfb5
main.main()
	github.com/hashicorp/terraform/main.go:58 +0x19
^C
[Exit 130 (INT)]

### Steps to Reproduce

1. `pacman -S terraform`
2. `terraform -install-autocomplete`
3. `terraform [tab]`

### Additional Context

$ hostnamectl 
 Static hostname: ericx-office2
       Icon name: computer
      Machine ID: 0a5ae3740a454cfc8036352d9588f7ea
         Boot ID: 95873992c82445caa2d5f90ff2126eb7
Operating System: Arch Linux                      
          Kernel: Linux 5.18.1-zen1-1-zen
    Architecture: x86-64
 Hardware Vendor: Dell Inc.
  Hardware Model: Precision 3930 Rack
Firmware Version: 2.14.0

**Comment by kmoe** [comment] 2022-06-01 14:41
Duplicate of https://github.com/hashicorp/terraform/issues/31126.

**Closed by kmoe** 2022-06-01 14:41 UTC
Labels: bug, new
