### ISSUE TITLE
`terraform` unnecessarily defers data source read

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/terraform#29484] opened 2021-08-30 22:54 UTC
### Terraform Version

```
$ terraform version
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files
```terraform
locals {
  data = {
    a = "foo",
    b = "bar",

    # run terraform apply, then uncomment this out and run plan again
    # c = "baz",
  }
}

resource "null_resource" "test" {
  for_each = local.data

  triggers = {
    value = each.value
  }
}

# note the difference between this and null_data_source.for_each_local_var
data "null_data_source" "for_each_resource" {
  for_each = null_resource.test

  inputs = {
    computed_id = each.value.id
  }
}

locals {
  mapped_resource = {
    for k, v in local.data :
    k => {
      id = null_resource.test[k].id
    }
  }
}

# note the difference between this and null_data_source.for_each_resource
data "null_data_source" "for_each_local_var" {
  for_each = local.mapped_resource

  inputs = {
    computed_id = each.value.id
  }
}

```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior

Only `data.null_data_source.for_each_resource["c"]` should have been read during apply.

### Actual Behavior

Every `data.null_data_source.for_each_resource` is read during apply. See the following `terraform plan`:

```
$ terraform plan
null_resource.test["a"]: Refreshing state... [id=1790816938278639581]
null_resource.test["b"]: Refreshing state... [id=3574636991380461719]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.null_data_source.for_each_local_var["c"] will be read during apply
  # (config refers to values not yet known)
 <= data "null_data_source" "for_each_local_var"  {
      + has_computed_default = (known after apply)
      + id                   = (known after apply)
      + inputs               = {
          + "computed_id" = (known after apply)
        }
      + outputs              = (known after apply)
      + random               = (known after apply)
    }

  # data.null_data_source.for_each_resource["a"] will be read during apply
  # (config refers to values not yet known)
 <= data "null_data_source" "for_each_resource"  {
      ~ has_computed_default = "default" -> (known after apply)
      ~ id                   = "static" -> (known after apply)
      ~ outputs              = {
          - "computed_id" = "1790816938278639581"
        } -> (known after apply)
      ~ random               = "145559916517236951" -> (known after apply)
        # (1 unchanged attribute hidden)
    }

  # data.null_data_source.for_each_resource["b"] will be read during apply
  # (config refers to values not yet known)
 <= data "null_data_source" "for_each_resource"  {
      ~ has_computed_default = "default" -> (known after apply)
      ~ id                   = "static" -> (known after apply)
      ~ outputs              = {
          - "computed_id" = "3574636991380461719"
        } -> (known after apply)
      ~ random               = "2581874170056093043" -> (known after apply)
        # (1 unchanged attribute hidden)
    }

  # data.null_data_source.for_each_resource["c"] will be read during apply
  # (config refers to values not yet known)
 <= data "null_data_source" "for_each_resource"  {
      + has_computed_default = (known after apply)
      + id                   = (known after apply)
      + inputs               = {
          + "computed_id" = (known after apply)
        }
      + outputs              = (known after apply)
      + random               = (known after apply)
    }

  # null_resource.test["c"] will be created
  + resource "null_resource" "test" {
      + id       = (known after apply)
      + triggers = {
          + "value" = "baz"
        }
    }
```

Note that `null_data_source.for_each_local_var` works as expected, as only `data.null_data_source.for_each_local_var["c"]` is read during the apply.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Uncomment `c` from `local.data`
4. `terraform plan`

### Additional Context

I've attached a more complex example as well, it features the same bug but happens when used with modules: [terraform-data-source-bug-complex.zip](https://github.com/hashicorp/terraform/files/7079984/terraform-data-source-bug-complex.zip).

In this example, you'll notice that `data.null_data_source.inside_module_b_direct` must always be read during apply, while `data.null_data_source.inside_module_b_local` does not. It's considerably puzzling why an indirect reference via a `local` variable seems to fix the issue.

Either way, hopefully both the complex and simple (above) examples demonstrate the issue at hand - `terraform` seems to force data sources to be read during apply _even when their values are statically known_. Unfortunately this caused a lot of noise in our terraform plans when we happened upon this; fortunately it appears that the `local` workaround mentioned in the "complex" example solves the issue for us.

### References

- #28084

**Comment by jbardin** [comment] 2021-08-31 15:36
Hi @ericnorris,

Thanks for filing the issue with the full reproductions! This is the expected behavior in this context, and is the unfortunate consequence of needing to handle some backwards compatibility constraints resolved in #25961.  

Adding a reference to a managed resource from a data source is equivalent to adding that resource in `depends_on`, which means any change in that resource results in deferring the data source itself. The workaround is to make the reference indirect through a local value like you have shown. There's not much we can do here in the v1.0 lifecycle, but perhaps there's a better way to indicate this in the documentation, so I'll re-label this accordingly.

**Comment by ericnorris** [comment] 2021-08-31 18:17
Thanks for the quick reply @jbardin.

I believe your explanation makes sense, though it took me a while to figure out why this behavior appeared after a recent refactor in our Terraform configuration codebase. Previously we were reading the value through a module `output`, which I expect has the same behavior as reading through a `local` value.

That said, I'm not 100% sure this isn't a bug, since it has to do with `for_each`. For example:

```terraform
resource "null_resource" "test_a" {
  triggers = {
    value = "foo"
  }
}

data "null_data_source" "test_a" {
  inputs = {
    computed_id = null_resource.test_a.id
  }
}
```

Running `terraform apply` and then `terraform plan` shows no changes, and doesn't force a deferred data source read, as I would expect.

What seems to be happening in the `for_each` case is that _all_ instances of the resource are considered changed, even when only one of them is actually changing, which then means that all of the data sources that depend on the matching resource are forced to do a deferred read. This, to me, is unexpected - none of the `a` or `b` values in my original example are changing, so you'd think that `null_resource.test["a"]` and `null_resource.test["b"]` would be considered unchanged, and the implicit `depends_on` by the data source wouldn't matter.

Does that make sense?

**Comment by jbardin** [comment] 2021-08-31 19:23
Dependencies are determined at the resource level, rather than the instance level, so because the data source depends on `null_resource.test` as a whole, any changes in `null_resource.test` instances are going will imply that all the data source instances need to wait for the changes to be applied.

The last example works the same way, in that if there were any changes to `null_resource.test_a` the data source would need to wait until apply to be read.

**Comment by ericnorris** [comment] 2021-08-31 22:22
I think I know the answer to this one, but I've got one more clarifying question for you @jbardin; thanks for your time so far.

While your last response makes sense, what remains confusing to me is that if you look at the "complex" example, the _inside_ of `module-b` has the same shape as the resources in my last code snippet.

For example, `main.tf`:

```terraform
locals {
  data = {
    a = "foo",
    b = "bar",

    # run terraform apply, then uncomment this out and run plan again
    # c = "baz",
  }
}

module "test_a" {
  source   = "./module-a"
  for_each = local.data

  value = each.value
}

module "test_b" {
  source   = "./module-b"
  for_each = module.test_a

  id = each.value.null_resource.id
}
```

...and `module-b/main.tf`:

```terraform
variable "id" {
  type = string
}

resource "null_resource" "inside_module_b_one" {
  triggers = {
    id_from_previous_computed_source = var.id
  }
}

data "null_data_source" "inside_module_b_direct" {
  inputs = {
    computed_from_id = null_resource.inside_module_b_one.id
  }
}

# ...
```

I expect you would say this is still expected, but hopefully you can see how that's still confusing - the contents of the module look like something that doesn't exhibit the behavior (a data source that depends on a single resource, no `for_each`), but because the containing module depends on a `for_each`'d module (or is itself a `for_each`'d module?), it unfortunately is affected. Is that correct?

If so, perhaps this is also interesting - reading the `module-a` outputs through a `local` value and passing it into `module-b` makes no difference, the `local` value workaround _must_ be inside of `module-b`, as indicated in the example.

**Comment by jbardin** [comment] 2021-09-01 16:23
Thanks @ericnorris,

I agree that is a bit more puzzling, and definitely hard to see why it should happen that way during planning. This is a combination of a couple things, but starts with the basis that _nothing_ is expanded yet during the plan, so there are no module instances either. We then have one module which uses the other module in a `for_each` expression, which means that all instances of `test_b` have the chance of depending on all instances of `test_a` in order to process the instance expansion. The node for that `for_each` expression is where this extra dependency stems from, and causes all the data sources to effectively be dependent on any changes in all `test_a` instances when referencing `each.value.null_resource.id`.

These inter-module-instance dependencies were narrowed down in #28267, but the specific case you have here was allowed to continue due to interaction with `depends_on` at higher module levels. I'll have to look into whether we could narrow things down further, but it will take some careful consideration about the interaction with  `depends_on`.

Thanks!

**Comment by ericnorris** [comment] 2021-09-01 18:12
Great! I'm hopeful that this can be narrowed down further, but I understand that there are a number of complicating factors. I'll keep an eye on this issue for any changes.

Thanks for answering all my questions so far, and looking into this!

**Comment by jbardin** [comment] 2021-09-30 13:18
I noticed this detail is already mentioned in the docs, so the documentation portion is taken care of. I do however have a possible improvement in the dependency tracking, so leaving as a bug until I can determine if we can make the change.

**Closed** 2021-10-04 15:39 UTC
Labels: bug, core
