### ISSUE TITLE
Provisioner Connections using SSH fail to connect to MFA enabled systems

### ISSUE THREAD

**Issue by jadams-av** [hashicorp/terraform#16032] opened 2017-09-06 19:12 UTC
Hello,

We're seeing an issue with provisioner connections when attempting to run terraform apply against systems whose SSH daemon configuration includes google authenticator MFA. 

The typical lifecycle is that terraform apply can successfully provision the system, because the system starts as generic ubuntu with stock SSH. As part of the terraform apply, SSH is then configured to include MFA. Once this is complete, any subsequent terraform provisioner connections are no longer able to connect to the system.

I've confirmed that the ssh user/key combination used by terraform works "by hand", both before and after MFA is enabled, so that is not the issue.

### Terraform Version
v0.9.8

### Terraform Configuration Files
```
resource "null_resource" "provisioning" {
   depends_on = ["aws_instance.ec2_instance","aws_eip.system"]
   triggers {
     puppetrole_version = "${file("${path.module}/../breadcrumb.txt")}"
   }
   connection {
     user = "tf-user"
     host = "${aws_eip.system.public_ip}"
     private_key = "${file("${var.key_path}/${var.key_name}.pem")}"
   }

   provisioner "file" {
     source = "${path.module}/../target/"
     destination = "/tmp/"
   }

   provisioner "remote-exec" {
     inline = [
       "sudo -S dpkg -i /tmp/*.deb",
       "rm -rf /tmp/*.deb"
     ]
   }

}
```

### Debug Output

> null_resource.provisioning: Provisioning with 'file'...
> 2017/08/11 16:14:44 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:44 connecting to TCP connection for SSH
> 2017/08/11 16:14:44 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:44 handshaking with SSH
> 2017/08/11 16:14:45 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:45 handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
> 2017/08/11 16:14:45 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:45 Retryable error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
> 2017/08/11 16:14:48 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:48 connecting to TCP connection for SSH
> 2017/08/11 16:14:48 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:48 handshaking with SSH
> 2017/08/11 16:14:49 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:49 handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> 2017/08/11 16:14:49 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:49 Retryable error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> 2017/08/11 16:14:49 [DEBUG] dag/walk: vertex "root", waiting for: "provider.null (close)"
> 2017/08/11 16:14:49 [DEBUG] dag/walk: vertex "provisioner.remote-exec (close)", waiting for: "null_resource.provisioning"
> 2017/08/11 16:14:49 [DEBUG] dag/walk: vertex "provider.null (close)", waiting for: "null_resource.provisioning"
> 2017/08/11 16:14:49 [DEBUG] dag/walk: vertex "provisioner.file (close)", waiting for: "null_resource.provisioning"
> 2017/08/11 16:14:49 [DEBUG] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "null_resource.provisioning"
> 2017/08/11 16:14:52 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:52 connecting to TCP connection for SSH
> 2017/08/11 16:14:52 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:52 handshaking with SSH
> 2017/08/11 16:14:52 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:52 handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> 2017/08/11 16:14:52 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/08/11 16:14:52 Retryable error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> 2017/08/11 16:14:54 [DEBUG] dag/walk: vertex "root", waiting for: "provider.null (close)"
> 2017/08/11 16:14:54 [DEBUG] dag/walk: vertex "provisioner.file (close)", waiting for: "null_resource.provisioning"
> 2017/08/11 16:14:54 [DEBUG] dag/walk: vertex "provisioner.remote-exec (close)", waiting for: "null_resource.provisioning"
> 2017/08/11 16:14:54 [DEBUG] dag/walk: vertex "provider.null (close)", waiting for: "null_resource.provisioning"
> 2017/08/11 16:14:54 [DEBUG] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "null_resource.provisioning"
> 

### Expected Behavior
Terraform should connect to the system via the SSH, and apply any changes

### Actual Behavior
The SSH connection fails

### Steps to Reproduce

1. Verify terraform provisioner connection is able to connect to a system via SSH using keys.
2. Configure SSH for MFA on remote system, exempting the terraform user from MFA:
https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04
3. Verify terraform provisioner connection is no longer able to connect to a system via SSH using keys.

### Important Factoids
The remote system has google-authenticator MFA installed and enabled. However, the user account used by Terraform does not require MFA.

A success login by the terraform SSH user looks like:

```
bamboo@bambooagent:/mnt/bamboo-ebs/bamboo-agent/build-dir/terraform/dev-system$ ssh -i tf-user.pem tf-user@the.remote.system
Authenticated with partial success.
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1028-aws x86_64)

  * Documentation:  https://help.ubuntu.com
  * Management:     https://landscape.canonical.com
  * Support:        https://ubuntu.com/advantage

   Get cloud support with Ubuntu Advantage Cloud Guest:
     http://www.ubuntu.com/business/services/cloud

10 packages can be updated.
9 updates are security updates.


Last login: Fri Aug 11 16:09:50 2017 from some.other.system
```
Of note is the "Authenticated with partial success." line, which is what I suspect is somehow interfering with terraform's ability to complete the SSH connection, though I'm unsure of how or why.

**Comment by apparentlymart** [comment] 2017-09-15 00:15
Hi @jadams-av! Sorry for this weird interaction.

I must admit that I'm not very familiar with this Google Authenticator PAM module, but based on a quick read of how it works (which I may misunderstand, since I didn't go deep) I think perhaps the problem is the way `AuthenticationMethods` is configured, to require the `publickey` _and_ either `password` or `keyboard-interactive` authentication, whereas the configuration here only provides a key. 

Since Terraform wants to use SSH non-interactively, it doesn't have full support for `keyboard-interactive`, though it tries to fake it by sending a configured password (via the `password` attribute in the `connection` block) in response to all prompts. Unfortunately I expect that the "password" needed here is the six-digit MFA token, and thus setting a password won't help. Maybe worth a try though... if your Terraform user doesn't have an MFA key set, perhaps the `nullok` setting will allow it to pass through.

I'm rusty on PAM but after some digging I found [an article that shows how to make exceptions at the PAM layer](https://techblog.jeppson.org/2016/02/linux-two-factor-user-exception/), via something like this:

```
# Everyone must satisfy pam_unix
auth        required    pam_unix.so

# For users in /etc/non_mfa_users, that's sufficient
auth        sufficient  pam_listfile.so onerr=fail item=user sense=allow file=/etc/non_mfa_users

# Users not in that file must also use Google Authenticator (no nullok)
auth        required   pam_google_authenticator.so
```

I don't have a suitable system to try this out, but my hope is that then you could safely set `AuthenticationMethods` like this:

```
AuthenticationMethods publickey publickey,password publickey,keyboard-interactive
```

...and then users in the `non_mfa_users` file (including the Terraform user) would get through with just a key, skipping `pam_google_authenticator` entirely, while other users trying to do that would fail _that_ method (because PAM will reject it) and their clients will move on to trying `publickey,password` and `publickey,keyboard-interactive` and succeed with one of them.

Unfortunately this isn't a configuration I have direct experience with, so the above is just a best guess. I hope there's something useful here!

**Comment by jadams-av** [comment] 2017-09-18 15:11
Thanks for the feedback, and my apologies for not making it more clear that terraform SSH provisioner user was already configured and verified as exempt from the MFA requirement. Didn't mean to send anyone on a rabbit trail of google authenticator configuration.

To recap the setup:  A user that is exempt from the MFA requirement, from a host with both the Terraform code and the SSH private key, accessing a target host that has the public key and is configured with the google authenticator MFA pam module, including a no-mfa group.

SSH scenario: Using a regular SSH client, the user login to the remote host succeeds without requiring any additional interaction. (example in the **Important Factoids** above)

Terraform scenario: Using the Terraform provisioner connection configured with the same user and key as the SSH scenario, the login to the remote host fails. (example in the **Debug Output** above)

Happy to provide any additional information that may prove useful. Thanks!

**Comment by ashanir** [comment] 2018-09-11 09:38
Is this issue fixed ? I am facing the same problem. It would be great if I can get a work around.

**Comment by ashanir** [comment] 2018-09-11 13:16
@apparentlymart  Using `AuthenticationMethods publickey publickey,keyboard-interactive` actually disables mfa for all users (probably because `publickey`  is a proper subset of `publickey,keyboard-interactive` ) and using `AuthenticationMethods publickey,keyboard-interactive` works fine with console users (e.g. ec2-user and other system users are able to logon without mfa from console and with mfa for remaining users) but terraform fails to ssh into the system. Thanks for the suggestion anyway. I am looking for work around to meet security compliance requirements.

**Comment by domnagar** [comment] 2018-09-11 21:43
Hi everyone.  Just want to know if this issue has been fixed.

I saw a couple of topics similar to this but no resolution.

Just thought I would share my workaround for this.  It seems to work for me with OpenSSH_7.4p1 on my bastion server.

Openssh has a match condition which you can assign to a user to override the default behavior.  After following the instructions for setting up MFA with the google authenticator,
at the bottom of my /etc/ssh/sshd_config file, I have the following:

`# Only allow publickey and Google MFA
AuthenticationMethods publickey,keyboard-interactive
Match User terraform
	AuthenticationMethods publickey
`
where "terraform" is the login that my terraform plan uses to connect to the bastion server.

I've tested this configuration with the command line login as well as running terraform.

Hopefully the issue gets fixed soon as I would like to not have to add exceptions in the sshd_config file.

**Comment by ashanir** [comment] 2018-09-12 10:36
@domnagar Thanks ! The workaround worked for me !

**Comment by teamterraform** [comment] 2019-08-29 20:41
Hi all!

As @apparentlymart noted above, Terraform expects to be able to authenticate non-interactively with the remote SSH server, and thus cannot authenticate to an account that requires MFA or other similar interactive prompts.

In order to use Terraform provisioners, you must therefore configure OpenSSH appropriately to accept public key authentication alone for the user you plan to have Terraform log in as. From the comments above, it seems that there is a known solution to do that, and so we're going to close this out now.

Please note that Terraform offers provisioners as a pragmatic last resort for situations where no other option is available. If at all possible, it's better to pre-configure your instances as part of a custom machine image, and then pass any dynamic data determined by Terraform via a mechanism like EC2 `user_data`, GCP metadata, etc. That way the virtual machine can begin its work immediately on boot, rather than waiting for Terraform to connect over SSH. This also avoids the need to configure remote SSH access to the virtual machine, because all of the required information can instead be transmitted via the respective provider API.

**Closed by teamterraform** 2019-08-29 20:41 UTC
Labels: bug, provisioner/file, provisioner/remote-exec, v0.9
