### ISSUE TITLE
Strange treatment of hex variable with single e and otherwise digits

### ISSUE THREAD

**Issue by estelendur** [hashicorp/terraform#19406] opened 2018-11-19 20:27 UTC
When trying to tag an image with a six-digit SHA earlier, I got some super weird output.
### Terraform Version

```
Terraform v0.11.10
```

### Terraform Configuration Files
Here's a minimal example that is blatantly misusing the beginning example from the Getting Started. :)

```hcl
 provider "aws" {                   
   region = "us-east-1"             
 }                                  
                                    
 resource "aws_instance" "example" {
   ami = "ami-${var.ami_tag}"       
   instance_type = "t2.micro"       
 }                                  
                                    
 variable ami_tag {
  type = "string"
}                

```
### Behavior

If I run `terraform plan` with the minimal example above and enter `3e24567` as the ami_tag value when prompted, in the output I get the expected result of
```
[...]
ami:          "ami-3e24567"
[...]
```
If I run `terraform plan --var 'ami_tag=[...]'` I get some varying results:

| Input | Output |
| ---- | ----- |
| `'ami_tag=3e2'` | `"ami-3e2"` |
|`'ami_tag=3f24567'` | `"ami-3f24567"` |
| `'ami_tag=3e2456b'` | `"ami-3e2456b"` |
| `'ami_tag=e324567'` | `"ami-e324567"` |
| `'ami_tag=e'` | `"ami-e"` |
| `'ami_tag="3e24567"'` | `"ami-3e24567"` |
| `'ami_tag=3e24567'` | `"ami-"` |
| `'ami_tag=324567e'` | `"ami-"` |
| `'ami_tag=324e'` | `"ami-"` |
| `'ami_tag=3e'` | `"ami-"` |
| `'ami_tag=3e307'` | `"ami-3e307"` |
| `'ami_tag=3e308'` | `"ami-"` |

### Steps to Reproduce

1. `terraform init`
2. `terraform plan --var 'ami_tag=3e24567'`

### Speculation
It looks like Terraform is interpreting the SHA with a digit in position 1, a single e somewhere else, and only digits otherwise, as an exponential number briefly before converting it to a string to use as a variable, and over a certain size it's overflowing and turning into an empty string.

**Comment by apparentlymart** [comment] 2018-11-19 22:48
Hi @estelendur! Sorry for this very strange behavior, and thank you for reporting it.

I believe this is the same root cause as #15626, and I verified a few weeks ago that it is fixed in the v0.12.0-alpha1 build. This fix is in master and ready to be included in the v0.12.0 release.

In looking at the other issue, I didn't actually notice that this was probably caused by incorrectly assuming the value is a scientific notation number, but now that you say it I agree that this very likely the cause: the old variable values parser used the HCL parser for reading in values to allow for list/map values, and so HCL's number parsing rules could apply here.

That also explains why it is fixed for v0.12.0: in the new implementation we use the HCL parser only when the variable has collection type, parsing primitive-typed variables instead as literal strings.

This explanation also suggests a possible workaround of providing the value already in quotes like `'ami_tag="3e308"'`, which the HCL parser should then interpret as a string, but that won't be forward-compatible with v0.12.0 since the new parsing rules will interpret it as a literal string with quotes in it.

Thanks for reporting this and for the good detective work in figuring out the cause! Since there's already a fix for this merged I'm going to close this out, but it's very nice to have an explanation for it.

**Closed by apparentlymart** 2018-11-19 22:48 UTC
