### ISSUE TITLE
0.15.4 Crashing on plan with no log

### ISSUE THREAD

**Issue by travertischio** [hashicorp/terraform#28826] opened 2021-05-27 16:35 UTC
### Terraform Version

```
0.15.4
```

### Crash Output
https://gist.github.com/travertischio/4460b72bc45c74c2b52eafd6195a7ae5

### Expected Behavior
The plan should have continued checking resource state

### Actual Behavior
Terraform crashed

### Steps to Reproduce
terraform init
terraform plan

This is on only one of our projects. Using the same terraform version did not result in a crash for other projects.

### Additional Context
This is only happening in one of our terraform projects so far

**Comment by jbardin** [comment] 2021-05-27 17:10
Thanks @travertischio, duplicate of #28763

**Closed by jbardin** 2021-05-27 17:10 UTC
Labels: bug, new
