### ISSUE TITLE
Feature Request: Github provider

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#3544] opened 2015-10-19 11:11 UTC
Excellent API library is provided in google/go-github.

Would be very helpful to have a Github provider in terraform to maintain Teams <-> Project ACLs and Webhooks / integrations

**Comment by apparentlymart** [comment] 2015-10-20 01:29
Nice idea! A while back I built [an out-of-tree plugin for Beanstalk](https://github.com/saymedia/terraform-beanstalk), which is an alternative hosted solution for source control repositories... having github support so we can manage our github teams (for open source projects) in the same way as we manage our beanstalk teams (for internal-only projects) would be awesome.

**Comment by ejholmes** [comment] 2015-10-27 21:14
:+1: would be great to have support for updating github webhooks with terraform.

**Comment by catsby** [comment] 2015-12-15 20:42
Hey Friends – I'm going to close this as a duplicate of #1731; if you're interested, please track that issue.

Thanks!

**Closed by catsby** 2015-12-15 20:42 UTC
Labels: enhancement
