### ISSUE TITLE
terraform version takes over one second to run

### ISSUE THREAD

**Issue by kollektiv** [hashicorp/terraform#27059] opened 2020-11-30 22:52 UTC
### Terraform Version

```
v0.12.29 and v0.13.5
```

### Terraform Configuration Files

.terraformrc
```terraform
disable_checkpoint = true
disable_checkpoint_signature = true
```

### Debug Output

```
$ export CHECKPOINT_DISABLE=1

$ time terraform version
Terraform v0.12.29

real    0m1.326s
user    0m0.313s
sys     0m0.860s
```

```
$ export CHECKPOINT_DISABLE=1

$ time terraform version
Terraform v0.13.5

real    0m1.285s
user    0m0.315s
sys     0m0.833s
```

### Expected Behavior

`terraform version` outputs almost immediately

### Actual Behavior

`terraform version` takes over one second to run. 

### Steps to Reproduce

Time running `terraform version`. Run `terraform fmt` on a small file

### Additional Context

The `terraform version` commands takes a long time to run, as well as other terraform commands, such as `fmt` on a very small file

**Comment by jbardin** [comment] 2020-12-01 13:59
Hi @kollektiv 

Can you add the output with `TF_LOG=trace`? The logs will show more details about what terraform is doing along with timestamps.

Thanks!

**Comment by kollektiv** [comment] 2020-12-01 19:22
Hi @jbardin

Here's the output with `TF_LOG=trace`

```
$ TF_LOG=trace time terraform version
2020/12/01 11:20:20 [INFO] Terraform version: 0.12.29
2020/12/01 11:20:20 [INFO] Go runtime version: go1.12.13
2020/12/01 11:20:20 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/2.0.0/versions/0.12.29/terraform", "version"}
2020/12/01 11:20:20 [DEBUG] Attempting to open CLI config file: /Users/user/.terraformrc
2020/12/01 11:20:20 Loading CLI configuration from /Users/user/.terraformrc
2020/12/01 11:20:20 [INFO] CLI command args: []string{"version"}
2020/12/01 11:20:20 [INFO] Checkpoint disabled. Not running.
Terraform v0.12.29
2020/12/01 11:20:20 [DEBUG] checking for provider in "."
2020/12/01 11:20:20 [DEBUG] checking for provider in "/usr/local/Cellar/tfenv/2.0.0/versions/0.12.29"
2020/12/01 11:20:20 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
        0.92 real         0.24 user         0.44 sys
```

**Comment by kollektiv** [comment] 2020-12-01 19:24
The above output is terraform installed using `tfenv`. I am trying now with terraform downloaded from terraform.io/downloads.html and it is a lot faster

```
$ TF_LOG=trace time ./terraform version
2020/12/01 11:23:15 [INFO] Terraform version: 0.13.5
2020/12/01 11:23:15 [INFO] Go runtime version: go1.14.7
2020/12/01 11:23:15 [INFO] CLI args: []string{"/Users/user/Downloads/terraform", "version"}
2020/12/01 11:23:15 [DEBUG] Attempting to open CLI config file: /Users/user/.terraformrc
2020/12/01 11:23:15 Loading CLI configuration from /Users/user/.terraformrc
2020/12/01 11:23:15 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/12/01 11:23:15 [DEBUG] ignoring non-existing provider search directory /Users/user/.terraform.d/plugins
2020/12/01 11:23:15 [DEBUG] ignoring non-existing provider search directory /Users/user/Library/Application Support/io.terraform/plugins
2020/12/01 11:23:15 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/12/01 11:23:15 [INFO] Checkpoint disabled. Not running.
2020/12/01 11:23:15 [INFO] CLI command args: []string{"version"}
Terraform v0.13.5
        0.04 real         0.03 user         0.02 sys
```

**Comment by jbardin** [comment] 2020-12-01 19:38
Thanks @kollektiv 

Since there's nothing in the log output that appears to be delaying execution, and it only happens with `tfenv`, it would appear that the delay is caused by something unique to your system. There's not much we can do in terraform to change the result here, so I'm going to close this. If you have more information showing terraform can effect the execution somehow, feel free to respond here and we can re-evaluate the issue.

Thanks!

**Closed by jbardin** 2020-12-01 19:38 UTC
Labels: bug

**Comment by kollektiv** [comment] 2020-12-01 19:45
Hi @jbardin, it's something caused by `tfenv`. `tfenv` will install a wrapper script around terraform. I'll dig into what's the delay in the wrapper script. Thanks for looking!
