### ISSUE TITLE
Route53 records with aliases to the same zone constantly updated (0.7.5)

### ISSUE THREAD

**Issue by robkinyon** [hashicorp/terraform#9363] opened 2016-10-14 01:43 UTC
When using a aws_route53_record that has an alias to another record in the same zone, the alias section is updated on zero change.

### Terraform Version
0.7.5

### Affected Resource(s)
- aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "foo-bar-com" {
  zone_id = "${aws_route53_zone.bar-com.zone_id}"
  name = "foo.bar.com."
  type = "A"

  alias {
    name = "other.bar.com."
    zone_id = "${aws_route53_zone.bar-com.zone_id}"
    evaluate_target_health = false
  }

  depends_on = [
    "aws_route53_record.other-bar-com",
  ]
}
```

### Expected Behavior
When running `terraform plan` on zero change to this record, Terraform should not report any changes to this record.

### Actual Behavior
```
~ aws_route53_record.foo-bar-com
    alias.1936666417.evaluate_target_health: "" => "false"
    alias.1936666417.name:                   "" => "other.bar.com."
    alias.1936666417.zone_id:                "" => "Z00A0A00A000AA"
    alias.3384870725.evaluate_target_health: "false" => "false"
    alias.3384870725.name:                   "other.bar.com" => ""
    alias.3384870725.zone_id:                "Z00A0A00A000AA" => ""
```
(I obviously modified the zone ID)

### Steps to Reproduce
1. `terraform plan`

**Comment by apparentlymart** [comment] 2016-10-14 04:35
Hi! Sorry for the issue here.

I think this is a diff normalization issue. It looks like when we read the alias back from the Route53 API it is trimming off the trailing period in your config.

We should fix this by having Terraform mirror this normalization behavior, but in the mean time you should be able to work around it by removing there period from your config so Terraform won't see it as a change.

**Comment by kwilczynski** [comment] 2016-10-14 13:50
@robkinyon @apparentlymart there is work started to resolve this issue in the #8517. I apologise for the delay with this.

**Comment by apparentlymart** [comment] 2016-10-14 15:09
Great, @kwilczynski! In that case, I'm going close this to consolidate the discussion in #8511.

Please let me know if this other issue doesn't seem to actually be a duplicate of yours, @robkinyon.

**Closed by apparentlymart** 2016-10-14 15:09 UTC
Labels: bug, provider/aws
