### ISSUE TITLE
Cycle error removing resources when running apply, v0.12.20

### ISSUE THREAD

**Issue by HayleyMa** [hashicorp/terraform#28470] opened 2021-04-21 16:24 UTC
Plan executes with no errors:
`Plan: 0 to add, 0 to change, 10 to destroy.`

Error when running apply:
`Error: Cycle: data.consul_key_prefix.subnet_nums (destroy), data.azurerm_shared_image.windows (destroy), local.shared_subscription_id, provider.azurerm.shared, data.azurerm_storage_account.chef_files (destroy), data.azurerm_recovery_services_vault.default (destroy), local.images_subscription_id, provider.azurerm.images, data.azurerm_shared_image.linux (destroy), azurerm_backup_policy_vm.backup_policy (destroy), data.template_file.windows_instance_bootstrap (destroy), data.vault_generic_secret.chef_files (destroy), data.azurerm_virtual_network.default (destroy), azurerm_availability_set.default (destroy), azurerm_network_security_group.default (destroy), azurerm_application_security_group.default (destroy), azurerm_resource_group.default (destroy), azurerm_network_interface_application_security_group_association.default[0] (destroy), azurerm_backup_protected_vm.attach_vm[0] (destroy), azurerm_virtual_machine.windows[0] (destroy), azurerm_network_interface.default[0] (destroy), azurerm_virtual_machine_extension.customscript[0] (destroy), local.acct_env, local.subscription_id, provider.azurerm, data.azurerm_subnet.default (destroy), data.consul_key_prefix.globals_general (destroy), local.region_code, local.vault_addr, provider.vault, data.vault_generic_secret.azure (destroy)`

Looks like it is trying to destroy data, but it should only be destroying resources

**Comment by plainsane** [comment] 2021-04-21 16:32
I’m also having general graph issues when destroying resources on an apply.  On 0.12.29 the plan works but then I fail with cycles during the apply.

**Comment by HayleyMa** [comment] 2021-04-21 16:34
The apply also works for me when I target each resource

**Comment by jbardin** [comment] 2021-04-22 12:47
Hi @HayleyMa,

Without any configuration present it's hard to provide direction here, but the problem is likely related to the provider configuration referring to data source values shared with other resources. What you have may actually be a valid configuration, but certain circumstances like this were not resolvable in older versions of terraform. I suggest updating to a more current release, as these specific issues have been addressed in 0.14 and 0.15. 

Since there is no further development happening on the 0.12 release, I'm going to close this issue. If you have further questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help

Thanks!

**Closed by jbardin** 2021-04-22 12:47 UTC
