### ISSUE TITLE
[07.10&previous] data.template_file not scoped when in module, cycle

### ISSUE THREAD

**Issue by vfabrizi** [hashicorp/terraform#10018] opened 2016-11-10 12:07 UTC
### Terraform Version
0.7.10 but already detected in 0.7.8 and possibly previous versions.

### Affected Resource(s)
data.template_file

### Terraform Configuration Files
https://github.com/vfabrizi/terraformissue
7.10debug.log
cycle.[dot,png]
cycle_different_resources_names.[dot,png]

### Debug Output
euvfabrizi:stack vfabrizi$ terraform plan 
Error configuring: 3 error(s) occurred:

* Cycle: module.stack_ext_ssl.data.template_file.user_data_files (destroy), data.template_file.user_data_var (destroy), data.template_file.user_data_var, module.stack_ext_ssl.var.user_data, module.stack_ext_ssl.data.template_file.user_data_vars (destroy), data.template_file.user_data_file (destroy), data.template_file.user_data_file
* Cycle: module.stack_ext_ssl.data.template_file.iam_role_vars (destroy), data.template_file.iam_role_var (destroy), data.template_file.iam_role_var, module.stack_ext_ssl.var.iam_role, module.stack_ext_ssl.data.template_file.iam_role_files (destroy), data.template_file.iam_role_file (destroy), data.template_file.iam_role_file
* Cycle: module.stack_ext_ssl.data.template_file.iam_role_policy_vars (destroy), data.template_file.iam_role_policy_file (destroy), data.template_file.iam_role_policy_file, module.stack_ext_ssl.var.iam_role_policy, module.stack_ext_ssl.data.template_file.iam_role_policy_files (destroy), data.template_file.iam_role_policy_var (destroy), data.template_file.iam_role_policy_var
euvfabrizi:stack vfabrizi$ 

### Expected Behavior
The scope of data resources should be limited to the module where they are created, either it is a module or a root/aggregation project. Especially when they have different names or are not even referenced by other resources inside the same module.

### Actual Behavior
if a data.file_template resource is created in a root project, and the project reference a module which contains another data.file_template resource, Terraform cycle as it consider all the data.file_template as they were the same instance, even though the name is different.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Two graph are provided, one with data resources with the same name, the other with resources with different name. It may be that Terraform does not scope the data.template_file depending on them being in a module or not, but data resources with different names should (I guess) being treated as different and independent.

cycle.[dot,png]
cycle_different_resources_names.[dot,png]

The behaviour persist even if the data.template_file reference different filenames.
I've also tried with the -Xnew-apply flag, but I'm not sure if it applies after 0.7.8 .

Vi.

**Comment by mitchellh** [comment] 2016-11-11 04:37
Hi! Your configuration appears incomplete and its holding me back from being able to reproduce this. Without a reproduction I unfortunately won't be able to fix this. :( Is there any way you can create an isolated reproduction case? Thanks!

**Comment by vfabrizi** [comment] 2016-11-11 11:42
Hi Mitchell,

here's the reduced and isolated version:
https://github.com/vfabrizi/10018terraform
7.10debug.log
cycle.dot
cycle.png

As in the previous example, running terraform apply from the module will give no cycle problem, while applying from the root/aggregation project will produce cycles.

You'll find three cycle, but they are basically the same as the pattern is repeated thrice.

Also, differentiating the resource by name between the root project and the module does not make things better, so it's not name clashing, and I suspect terraform is reusing resource from a common pool, even though that would not explain how the cycle are assembled, given that they stick by resource name. Sorry for not taking a look at the source code.

You should be able to run the example without any modification whatsoever. If that's not the case give me more indication.

Thanks,

Vincenzo.

**Comment by mitchellh** [comment] 2016-11-11 16:19
Got it reproduced. Thanks @vfabrizi, I'll take a closer look from here.

**Comment by mitchellh** [comment] 2016-11-11 16:38
Minimal repro for later:

#### main.tf

```
variable "user_data" {}

module "child" {
  source = "./module"

  user_data       = "${element(concat(data.template_file.user_data_var.*.rendered, data.template_file.user_data_file.*.rendered), 0)}"
}

data "template_file" "user_data_file" {
  template = "foo"
  count    = "${replace(replace(var.user_data, "/.+/", "0"), "/^$/", "1") }"
}

data "template_file" "user_data_var" {
  template = "${var.user_data}"
  count    = "${replace(replace(var.user_data, "/.+/", "1"), "/^$/", "0") }"
}
```

#### module/main.tf

```
variable "user_data" {}

data "template_file" "user_data_file" {
  template = "Foo"
  count    = "${ replace(replace(var.user_data, "/.+/", "0"), "/^$/", "1") }"
}
```

**Comment by mitchellh** [comment] 2016-11-11 16:54
So this is a known cycle right now and there are dups for this but I can't find them. Since we have a good repro here I'm going to keep this up!

**Comment by apparentlymart** [comment] 2017-04-05 17:53
Hi @vfabrizi! Sorry this sat here neglected so long.

In 0.8 and 0.9 there were various changes to how Terraform constructs graphs, which have tended to fix weird issues like this. With that in mind, I tried Mitchell's minimal reproduction case on v0.9.3 and indeed it appears that the error no longer occurs. So while I can't point to exactly which change has fixed this, it does appear to now be fixed.

This is long enough ago that I expect you probably don't have your original config around anymore to fully verify, but if you or anyone else encounters similar issues in 0.9 it would be best to open fresh issues for these since the relevant parts of Terraform have changed pretty considerably since 0.7.10 and so any problems are likely to have a different root cause and so will need fresh debugging work. I'm going to close this now. Thanks for opening this, and again sorry it took so long to resolve it!

**Closed by apparentlymart** 2017-04-05 17:53 UTC
Labels: bug, core

**Comment by vfabrizi** [comment] 2017-04-05 19:10
Hi Martin, 

thanks for looking into it. I have a pretty different templating system now, so it's probably not relevant anymore. Still, I'll spend some time in order to try to recreate it and give you a nod if the issue is still around.

Thanks for all your work.

Vi.
