### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Jithinxavi** [hashicorp/terraform#4337] opened 2015-12-16 10:23 UTC
Everything works perfectly, suddenly I got this error.

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectItem(0xc8200f6de0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:154 +0x423
github.com/hashicorp/hcl/hcl/parser.(*Parser).objectList(0xc8200f6de0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:69 +0xc1
github.com/hashicorp/hcl/hcl/parser.(*Parser).Parse(0xc8200f6de0, 0xc8200cb1e0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:52 +0x100
github.com/hashicorp/hcl/hcl/parser.Parse(0xc820332300, 0x2e5, 0x300, 0xc820332300, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/hcl/parser/parser.go:39 +0x185
github.com/hashicorp/hcl.Parse(0xc820332000, 0x2e5, 0x2e5, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/hcl/parse.go:17 +0x89
github.com/hashicorp/terraform/config.loadFileHcl(0xc8201568d0, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader_hcl.go:155 +0x2d6
github.com/hashicorp/terraform/config.loadTree(0xc8201568d0, 0x2c, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/import_tree.go:47 +0x313
github.com/hashicorp/terraform/config.LoadFile(0xc8201568d0, 0x2c, 0xc820131080, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:39 +0x3b
github.com/hashicorp/terraform/config.LoadDir(0xc820016004, 0x1f, 0x10, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:91 +0x38c
github.com/hashicorp/terraform/config/module.NewTreeModule(0x0, 0x0, 0xc820016004, 0x1f, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:40 +0x41
github.com/hashicorp/terraform/command.(*Meta).Context(0xc820084a00, 0xc820016004, 0x1f, 0xf6c660, 0x11, 0x0, 0xa, 0x4, 0x43ba01, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:148 +0x509
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc820084a00, 0xc8200cfeb0, 0x0, 0x0, 0xc82000ddc8)
        /opt/gopath/src/github.com/hashicorp/terraform/command/apply.go:103 +0xd46
github.com/mitchellh/cli.(*CLI).Run(0xc820130fd0, 0xc820156390, 0x0, 0x0)
        /opt/gopath/src/github.com/mitchellh/cli/cli.go:112 +0x655
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:146 +0xb08
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:82 +0xa88
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:18 +0x18

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select, locked to thread]:
runtime.gopark(0x108fd18, 0xc820026f28, 0xeb3fb8, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026f28, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026f28)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 9 [chan receive]:
main.makeShutdownCh.func1(0xc820018d80, 0xc820018d20)
        /opt/gopath/src/github.com/hashicorp/terraform/commands.go:134 +0x36
created by main.makeShutdownCh
        /opt/gopath/src/github.com/hashicorp/terraform/commands.go:137 +0x100

goroutine 10 [semacquire]:
sync.runtime_Syncsemacquire(0xc82010a400)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc82010a3f0)
        /usr/local/go/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc82010a3c0, 0xc820159000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc820028158, 0xc820159000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc82007a900, 0x0)
        /usr/local/go/src/bufio/scan.go:180 +0x877
github.com/hashicorp/terraform/command.(*Meta).flagSet.func1(0xc82007a900, 0xc820084a00)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:323 +0x25
created by github.com/hashicorp/terraform/command.(*Meta).flagSet
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:326 +0x5d5



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Version - Terraform v0.6.8

**Comment by radeksimko** [comment] 2015-12-16 10:36
Hi @Jithinxavi , thanks for the report.

Would you mind sharing the used Terraform code (minus any secrets) which is causing this crash? It may help us reproducing this bug.

**Comment by Jithinxavi** [comment] 2015-12-16 10:48
Found the issues, I just add new variable like below

variable = "darby_route53_zone_id" {
        description = "R53 Hosted zone ID"
        default = "<id>"
}

then after I declared the same, removed the spaces in description & default. then it looks good.

variable "route_zone" {
  description = "R53 Hosted zone ID"
  default = "<id>"
}

HCL is following any indentation?

**Comment by jen20** [comment] 2015-12-16 14:20
Hi @Jithinxavi! This is definitely a bug - the only place indentation should make any difference is in HEREDOC style strings. It's hard to tell from your example how you are indenting - could you wrap your examples in [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) in order that we can reproduce this?

**Comment by phinze** [comment] 2015-12-16 21:33
( edited @Jithinxavi's last comment to add the fenced code blocks, since the whitespace was already there :+1: )

**Comment by phinze** [comment] 2015-12-16 21:41
Reproduced with the first example above, it's not the indentation that's causing the panic, but rather the stray `=` between `variable` and `"darby_route53_zone_id"`

**Comment by phinze** [comment] 2015-12-18 17:01
This is the same crash as #4350 - just confirmed it's fixed now, and with https://github.com/hashicorp/hcl/pull/77 we'll also have error messages that point to the position of the issue.

With the linked PR, the error you'd get for that config is:

```
Error loading config: Error loading main.tf: At 1:12: root.Variable: not an object type for map (*ast.LiteralType)
```

Still a confusing error message, but the exact position of the stray equals sign is mentioned, so that's much better! :grinning:

**Closed by phinze** 2015-12-18 17:01 UTC
Labels: bug, core, crash
