### ISSUE TITLE
azurerm can not adjust vm-size after deploy

### ISSUE THREAD

**Issue by clintonm9** [hashicorp/terraform#6517] opened 2016-05-06 13:51 UTC
When using the asurerm provider and changing the vm_size, I get an error.

Config:
https://gist.github.com/clintonm9/421a3c04570c5b5d4d0ad99fe2f6eb1f

Changing vm_size from A0 to a A1

```
~ azurerm_virtual_machine.test
    vm_size: "Standard_A0" => "Standard_A1"
```

If I try and apply I get the following error:
https://gist.github.com/clintonm9/d922299a29d723cdb1def97c076ad1e0

Error from Azure Audit Log:
```
statusCode:Conflict serviceRequestId:f498a6c8-6e7a-420f-9788-400f18078921 statusMessage:{"error":{"code":"PropertyChangeNotAllowed","target":"adminPassword","message":"Changing property 'adminPassword' is not allowed."}}
```

**Comment by stack72** [comment] 2016-05-06 14:07
Hi @clintonm9 

Thanks for the report here. Let me have a look at this and see if i can work out what the issue is here. This could be something in the SDK that is stopping hte upgrade but I need to have a look at this and see first

I will keep you informed

P.

**Comment by stack72** [comment] 2016-05-06 21:02
@clintonm9 This is being tracked in a rollup issue (#6526) - so i am going to close this so i can track things there

**Closed by stack72** 2016-05-06 21:02 UTC
Labels: bug, provider/azurerm
