### ISSUE TITLE
Ternary Operator Converts Local Type

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform#31412] opened 2022-07-08 21:32 UTC
### Terraform Version

```
Terraform v1.2.4
on windows_amd64
```

### Terraform Configuration Files

```terraform
locals {
  // This is just an example; this value would be passed as a variable to a module
  example = {
    string_field1 = "foo"
    string_field2 = "bar"
    number_field  = 999
  }

  // The default that I want to use if `example` is `null`
  default = {}

  // If the example value is not null, use it; otherwise, use the default value
  value = local.example != null ? local.example : local.default
}

output "original" {
  value = local.example
}

output "after_ternary" {
  value = local.value
}

```

### Expected Behavior

The `original` and `after_ternary` outputs should be identical, since `local.value` would have been assigned the value of `local.example`.

### Actual Behavior

It converted the `number_field` to a string value:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

after_ternary = tomap({
  "number_field" = "999"
  "string_field1" = "foo"
  "string_field2" = "bar"
})
original = {
  "number_field" = 999
  "string_field1" = "foo"
  "string_field2" = "bar"
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

I'm aware that this is because it's trying to ensure that both sides of the ternary are of the same type, so it converts the `local.example` object to a `map(string)`. The problem here is that `{}` is ambiguous, as it could be a `map(any)` OR an `object(...)`, but Terraform is _assuming_ that it's a `map(string)`. As far as I can tell, there's no workaround for this either, as there's no `toobject()` function to inform Terraform that `{}` should be treated as an object instead of a `map(string)`.

It would seem that, if the ternary operator wants to do a conversion to make both sides the same type, it should convert the value with an ambiguous type (`{}`) before converting a known type (`number` to `string`, in this case).

@apparentlymart This seems like the kind of issue where you would know exactly why it handles it this way, if it can be modified, and if there's any workaround.

**Comment by KyleKotowick** [comment] 2022-07-08 22:09
Well, after battling with this for a while, I did actually find a workaround.

```
locals {
  // This is just an example; this value would be passed as a variable to a module
    example = {
      string_field1 = "foo"
      string_field2 = "bar"
      number_field  = 999
    }
  
  // The default that I want to use if `example` is `null`
  default = {}
  
  // Convert the objects to strings for the Ternary to be happy, then convert back to an object
  value_workaround = jsondecode(local.example != null ? jsonencode(local.example) : jsonencode(local.default))
}

output "after_ternary_workaround" {
  value = local.value_workaround
}
```

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

after_ternary_workaround = {
  "number_field" = 999
  "string_field1" = "foo"
  "string_field2" = "bar"
}
```

I should write a book on the hacky ways I've [brute-forced Terraform](https://registry.terraform.io/modules/Invicton-Labs/deepmerge/null/latest) to do what I want over the years...

**Comment by apparentlymart** [comment] 2022-07-08 23:15
Hi @KyleKotowick,

Terraform concluded that you meant a map here because there is no single object type that both results could convert to. An object type with three attributes and an object type with no attributes are two different types.

The following would be a suitable "default value" to use when your main value is null:

```hcl
  default = {
    string_field1 = tostring(null)
    string_field2 = tostring(null)
    number_field  = tonumber(null)
  }
```

Thanks to the explicit type conversions, the above value has the same object type as your `local.example`, and would therefore avoid Terraform having to use a map type as an approximation that both of these values can convert to.

Alternatively, you can use [the `coalesce` function](https://www.terraform.io/language/functions/coalesce) which is specifically aimed at the problem of providing fallback values to use when an input value is null:

```hcl
  value = coalesce(local.example, local.default)
```

A caveat with this approach is that if you do this then your output value `after_ternary` will not have a consistent return type, and so any time you use it in the calling module you'll need to take care to handle both of the possible types it could take, and in any case where Terraform doesn't have enough information to decide the "null-ness" of `local.example` the output value's type will not be known at all, which will lead to type mismatch errors being detected during the apply step instead of the planning step. (That caveat applies to your approach of using `jsonencode` too, since these two expressions are functionally equivalent.)

Given all of this, it seems like Terraform is behaving as intended here, and there are at least three other possible expressions that can produce a result that avoids the unwanted conversion to map, and so I'm going to close this. Thanks for sharing your workaround, too!

**Closed by apparentlymart** 2022-07-08 23:15 UTC
Labels: bug, new
