### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by maksagit** [hashicorp/terraform#27511] opened 2021-01-14 11:45 UTC
### Terraform Version
```
> terraform --version
Terraform v0.14.4 
```

### Crash Output
``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x189fada] `

goroutine 433 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Get(0xc001304000, 0x17, 0x2dd1161, 0x1b)
        /home/circleci/project/project/backend/remote-state/azure/client.go:42 +0x17a
github.com/hashicorp/terraform/states/remote.(*State).refreshState(0xc000309ce0, 0x0, 0xc000b597c0)
        /home/circleci/project/project/states/remote/state.go:111 +0x3f
github.com/hashicorp/terraform/states/remote.(*State).RefreshState(0xc000309ce0, 0x0, 0x0)
        /home/circleci/project/project/states/remote/state.go:104 +0x73
github.com/hashicorp/terraform/builtin/providers/terraform.dataSourceRemoteStateRead(0x31cea40, 0xc000cf0070, 0x29ce7e0, 0xc00178a510, 0x14, 0x24637998d, 0xbff828f663211e48, 0xc001562070, 0xc000864000, 0xc00008a080, ...)
        /home/circleci/project/project/builtin/providers/terraform/data_source_state.go:122 +0xa0f
github.com/hashicorp/terraform/builtin/providers/terraform.(*Provider).ReadDataSource(0xc0013c20e0, 0xc0005db060, 0x16, 0x31cea40, 0xc000cf0070, 0x29ce7e0, 0xc00178a510, 0x31ce980, 0x42c7968, 0x0, ...)
        /home/circleci/project/project/builtin/providers/terraform/provider.go:80 +0x225
github.com/hashicorp/terraform/terraform.(*evalReadData).readDataSource(0xc0010c3a90, 0x320adc0, 0xc0014720d0, 0x31cea40, 0xc000b8bea0, 0x29ce7e0, 0xc00178a270, 0x0, 0x0, 0x0, ...)
        /home/circleci/project/project/terraform/eval_read_data.go:115 +0xad5
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc0010c3a90, 0x320adc0, 0xc0014720d0, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:107 +0x1267
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xc0010f9730, 0x320adc0, 0xc0014720d0, 0x0, 0xc000864000)
        /home/circleci/project/project/terraform/node_resource_plan_instance.go:87 +0x4d4
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc0010f9730, 0x320adc0, 0xc0014720d0, 0xc000bd6002, 0x2a1c300, 0x2d2b3e0)
        /home/circleci/project/project/terraform/node_resource_plan_instance.go:41 +0x13e
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000d07520, 0x320adc0, 0xc0014720d0, 0x1c6ee4685e8, 0xc0010f9730, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph_walk_context.go:127 +0xc3
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2d2b3e0, 0xc0010f9730, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:59 +0x97e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0002d7aa0, 0x2d2b3e0, 0xc0010f9730, 0xc0011451c0)
        /home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x1246
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment] 2021-03-01 13:25
Duplicate of #26702

**Closed by jbardin** 2021-03-01 13:25 UTC
Labels: backend/azure, bug, crash, v0.14
