### ISSUE TITLE
for_each on array literal panics

### ISSUE THREAD

**Issue by fierro-fuego** [hashicorp/terraform#22313] opened 2019-08-02 18:53 UTC
### Terraform Version

```
Terraform v0.12.6
```

### Terraform Configuration Files

```hcl
resource "google_compute_address" "istio-lb-ips" {
  for_each = ["pilot", "policy", "telemetry", "zipkin", "grafana", "jaeger", "prometheus"]

  name = "name"
  address_type = "INTERNAL"
  region = "us-west2"
  project = var.project
}
```

### Crash Output
```
panic: not a string

goroutine 4693 [running]:
github.com/zclconf/go-cty/cty.Value.AsString(...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:1026
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x2e278a0, 0xc001d04ea0, 0x25cba80, 0xc001d04ec0, 0x7)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:1095 +0x38a
github.com/hashicorp/terraform/terraform.evaluateResourceForEachExpressionKnown(0x7292618, 0xc0002114a0, 0x2e594c0, 0xc0024fd110, 0x2d6e6f6974636172, 0x2d676e6967617473, 0x7365726774736f70, 0x100b609, 0xc0033c16b8)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_for_each.go:84 +0x5bd
github.com/hashicorp/terraform/terraform.(*EvalValidateResource).validateForEach(0xc0025cf770, 0x2e594c0, 0xc0024fd110, 0x7292618, 0xc0002114a0, 0x0, 0x62612d6f666f2d65, 0x6f69746361727473)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_validate.go:572 +0x59
github.com/hashicorp/terraform/terraform.(*EvalValidateResource).Eval(0xc0025cf770, 0x2e594c0, 0xc0024fd110, 0x2, 0x2, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_validate.go:394 +0x1b57
github.com/hashicorp/terraform/terraform.EvalRaw(0x2de5e80, 0xc0025cf770, 0x2e594c0, 0xc0024fd110, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc00199a580, 0x2e594c0, 0xc0024fd110, 0x2, 0x2, 0x1ad38c5, 0x2de5e80)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2de5de0, 0xc00199a580, 0x2e594c0, 0xc0024fd110, 0x26826a0, 0x3e03465, 0x25ef1a0, 0xc001409980)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2de5de0, 0xc00199a580, 0x2e594c0, 0xc0024fd110, 0xc00199a580, 0x2de5de0, 0xc00199a580, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x28e1c20, 0xc000cf2b38, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000ca4380, 0x28e1c20, 0xc000cf2b38, 0xc0020d6440)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b
```

### Expected Behavior

`terraform validate` succeeds
### Actual Behavior

panic
### Steps to Reproduce

1. Copy resource definition above into `main.tf` and run `terraform init`
2. `terraform validate`

**Comment by jcarrothers-sap** [comment] 2019-08-02 19:00
This is the same issue that I actually just came to report.  Here is my own minimal reproduction scenario:

### Terraform Configuration Files
```
variable "variable_without_defined_type" {
  #type = set(string)
  default = [
    "test1",
    "test2",
  ]
}

data "template_file" "init" {
  for_each = var.variable_without_defined_type
  template = each.value
}
```
### Crash Output
```
panic: not a string

goroutine 56 [running]:
github.com/zclconf/go-cty/cty.Value.AsString(...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:1026
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x2228cc0, 0xc000322420, 0x19cd420, 0xc000322440, 0x2)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:1095 +0x38a
github.com/hashicorp/terraform/terraform.evaluateResourceForEachExpressionKnown(0x2227980, 0xc0003ad080, 0x225a540, 0xc0003b9520, 0x1, 0x1, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_for_each.go:84 +0x5bd
github.com/hashicorp/terraform/terraform.(*NodeRefreshableDataResource).DynamicExpand(0xc0000ba718, 0x225a540, 0xc0003b9520, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/node_data_refresh.go:41 +0x1ce
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1ce3460, 0xc0000ba718, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:103 +0x8b1
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0003d0100, 0x1ce3460, 0xc0000ba718, 0xc0004146c0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b
```
### Workaround

If I uncomment the `type = set(string)` line, then everything work correct.  

It appears that when you pass a list type to `for_each` without explicitly telling it that it is a list, then you get a crash.  If you explicitly define it as a list, you get an error that looks like this:
```
Error: Invalid for_each argument

  on minimal.tf line 10, in data "template_file" "init":
  10:   for_each = var.variable_without_defined_type
```

**Comment by jcarrothers-sap** [comment] 2019-08-02 19:03
@fierro-fuego I would suggest that a better title for this issue report is: `for_each crash when passed non-explict list`, or something along those lines.

**Comment by fierro-fuego** [comment] 2019-08-02 19:04
just updated this, I realized it only fails for me when passed an array literal

**Comment by fierro-fuego** [comment] 2019-08-02 19:08
I think this constraint makes sense; if TF is now using `for_each` keys as part of resource identifiers, the type must be a map or set to ensure no duplicates.  However, this is not explicitly documented and should be caught during `terraform validate`.

**Comment by jcarrothers-sap** [comment] 2019-08-02 19:12
Oh, I agree the constraint makes complete sense, but Terraform should provide a friendly error message, not an ugly crash. :)

**Comment by teamterraform** [comment] 2019-08-02 19:19
Hi folks, thank you for the report and we are sorry for the crash. 

We've already fixed this bug in master and it will be in the next release. I will leave this issue open for now in the hopes that others will find it before opening new ones. Thanks!

**Comment by bentterp** [comment] 2019-08-03 08:12
> resource "google_compute_address" "istio-lb-ips" {
>   for_each = ["pilot", "policy", "telemetry", "zipkin", "grafana", "jaeger", "prometheus"]
> 
>   name = "name"
>   address_type = "INTERNAL"
>   region = "us-west2"
>   project = var.project
> }

I think you want to use ```name = each.key``` here.

**Comment by pselle** [comment] 2019-08-22 21:20
Terraform 0.12.7 (with this fix) is now released! https://github.com/hashicorp/terraform/blob/v0.12.7/CHANGELOG.md

**Closed by pselle** 2019-08-22 21:20 UTC
Labels: bug, crash
