### ISSUE TITLE
Crash when completion of `terraform workspace select`

### ISSUE THREAD

**Issue by gion-xy** [hashicorp/terraform#30376] opened 2022-01-20 06:31 UTC
### Terraform Version

```
Terraform v1.1.4
on darwin_arm64
```

### Terraform Configuration Files

(probably this is reproducable with no conf files)

### Debug Output

https://gist.github.com/gion-xy/ab0d6719d8c0f40f7aa3a975375679f6

### Expected Behavior

show available workspaces

### Actual Behavior

crash

### Steps to Reproduce

use shell completion at `terraform workspace select `, or execute `COMP_LINE="terraform workspace select " terraform`

**Comment by alisdair** [comment] 2022-01-21 15:39
Thanks for reporting this. I can reproduce the panic with `COMP_LINE="terraform workspace select " terraform`, no configuration or `terraform init` required.

**Comment by alisdair** [comment] 2022-01-21 17:00
I just spotted that this is a duplicate of #30193, so will track over there.

**Closed by alisdair** 2022-01-21 17:00 UTC
Labels: bug, crash, cli, confirmed, v1.1
