### ISSUE TITLE
Escaping interpolation fails on AWS policy variable

### ISSUE THREAD

**Issue by rlister** [hashicorp/terraform#2965] opened 2015-08-07 20:49 UTC
Using terraform_0.6.2_darwin_amd64 with `aws_iam_group_policy` provider.

I have some AWS IAM code inside a heredoc as follows:

```
"arn:aws:iam::123456789:user/${aws:username}"
```

Terraform throws the following syntax error:

```
Error loading config: Error loading /Users/ric/code/ops/tf/iam/group_policies/Developers.tf: Error reading config for aws_iam_group_policy[Manage-Personal-MFA]: parse error: syntax error
```

If I escape the `$` as `$$`, as per the interpolation docs, terraform apply now runs happily and updates the resource. However, it fails to unescape the double `$$` on writing, leaving it in the updated resource.

**Comment by rlister** [comment] 2015-08-08 02:52
Update: I tried switching this from heredocs to normal strings to work around the issue, but ran into the same problem. My best guess is that the IAM policy syntax `${aws:username}` is a little too confusing for terraform/hcl, and causes the attempt to escape with `$${aws:username}` to fail. Likely lexing the `${...}` has a higher priority.

For now I have implemented a workaround by actually interpolating the desired AWS syntax as a variable:

```
variable "aws_username" {
  default = "${aws:username}"
}
```

then doing e.g.:

```
      "Resource": [
        "arn:aws:s3:::${var.aws_username}-*/*"
      ]
```

**Comment by mwarkentin** [comment] 2015-10-19 23:26
@rlister Just came across this same issue, and found your reports on this and https://github.com/dtan4/terraforming/issues/108. A quick experiment seemed to indicate that moving the policies into `.json` files and importing using `file()` seems to work: `policy = "${file("policies/asv_custodian_describe_only.json")}"`

Hope that helps.

**Comment by apparentlymart** [comment] 2015-10-20 00:03
As well as fixing Terraform so that escaping dollar signs actually works, I also have #3124 awaiting review that provides a logical resource to help construct IAM policy documents using Terraform syntax. It works around this issue by having the user specify `&{...}`-style interpolations where the value should be processed by IAM rather than Terraform, and then it converts that to `${...}`-style before writing to the AWS API.

Once that's merged it might give you an alternative way to solve this problem.

**Comment by rlister** [comment] 2015-10-20 13:18
Cool news, so we have two usable workarounds and a fix in the works :-)

**Comment by fabian-dev** [comment] 2016-05-12 06:42
Escaping the terraform interpolation within the IAM policy worked perfectly well for us with terraform 0.6.16. 
I think this issue is solved.

```
resource "aws_iam_group_policy" "enforce_mfa" {
  name = "enforce_mfa_policy"
  group = "${aws_iam_group.devops_group.name}"
  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowIndividualUserToSeeTheirAccountInformation",
            "Effect": "Allow",
            "Action": [
                "iam:ChangePassword",
                [snip]
            ],
            "Resource": [
                "arn:aws:iam::${var.account_id}:user/$${aws:username}"
            ]
        }
    ]
}
EOF
}
```

**Comment by tomdavidson** [comment] 2017-02-09 03:08
still broken in 0.8.6

```js
      "Resource": [
        "arn:aws:iam::${accoutn_id}:mfa/*",
        "arn:aws:iam::${accoutn_id}:user/$${aws:username}"
      ]
```

```hcl
data "template_file" "user_iam_admin_allow" {
  template = "${file("${path.module}/policy.json")}"

  vars {
    account_id = "${data.aws_caller_identity.current.account_id}"
  }
}
```

> data.template_file.user_iam_admin_allow: failed to render : parse error at 37:57: expected "}" but found ":"

**Comment by dirkjansteltenpool** [comment] 2017-03-06 19:49
For me it is working in terraform 0.8.4 see https://github.com/hashicorp/terraform/issues/5016

**Comment by apparentlymart** [comment] 2017-03-06 20:29
@tomdavidson I think something else is going on in your case... possibly an escaping issue with an embedded template in the `template_file` data source? Would you mind filing a separate issue for that, since I think it's a different root cause than what was being worked on here.

I'm going to close this one because, as @dirkjansteltenpool noted, the original problem this issue was about has since been fixed by the rewrite of the interpolation language parser.

**Closed by apparentlymart** 2017-03-06 20:29 UTC
Labels: bug, provider/aws
