### ISSUE TITLE
import-if-exist

### ISSUE THREAD

**Issue by gh-siyengar** [hashicorp/terraform#29837] opened 2021-10-30 12:24 UTC
### Current Terraform Version
1.0.0

### Use-cases
If there is a resource already existing, it should allow you to import the resource into the state file if the flag import-if-exist is set to true.

### Attempted Solutions
At the moment we create a separate import statement in the form of shell script for all the resources identified as existing and execute the shell script.

### Proposal
A variable import-if-exist can do the trick.
**import-if-exist = true**

### References
NONE

**Comment by jbardin** [comment] 2021-11-01 13:43
Duplicate of #29160

**Closed by jbardin** 2021-11-01 13:43 UTC
Labels: enhancement, new
