### ISSUE TITLE
thetradedesk/lambdabased is erroring out

### ISSUE THREAD

**Issue by puneet-traceable** [hashicorp/terraform#33117] opened 2023-04-28 20:06 UTC
### Terraform Version

```shell
Terraform v1.4.5
on darwin_arm64
```

### Terraform Configuration Files

```
We are using lambdabase to trigger a lambda function in aws, but this provider is erroring out from yesterday
```

### Debug Output

- Installed hashicorp/null v3.2.1 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│
│ Error while installing thetradedesk/lambdabased v0.1.2: could not query provider registry for registry.terraform.io/thetradedesk/lambdabased: failed to retrieve authentication checksums for provider: 404 Not
│ Found returned from github.com

### Expected Behavior

`terraform init` should succeed with provider being available.

### Actual Behavior

it errors out with error
```
- Installed hashicorp/null v3.2.1 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│
│ Error while installing thetradedesk/lambdabased v0.1.2: could not query provider registry for registry.terraform.io/thetradedesk/lambdabased: failed to retrieve authentication checksums for provider: 404 Not
│ Found returned from github.com
```

### Steps to Reproduce

1. terraform init with lambdabase provider

**Comment by crw** [comment] 2023-04-28 22:33
As far as I can tell, the source code / repository no longer exists at GitHub: https://github.com/orgs/thetradedesk/repositories?type=all -- that account may have decided to stop supporting that provider.

**Comment by apparentlymart** [comment] 2023-05-01 16:05
Indeed, this error message suggests that the failure occurred trying to retrieve information about the provider from its GitHub releases, which is where release artifacts for community providers are typically shared.

It seems that this provider's GitHub repository is no longer available on GitHub, and so the entry in Terraform Registry is pointing to a repository that doesn't exist. Maintainers of community providers are empowered to remove their repositories if they choose to since they retain ownership of them, so probably the best we could do here is remove the corresponding entry from `registry.terraform.io` to avoid pointing to a repository that no longer exists. However, before we do that we might wish to try to make contact with the developer to understand if they removed this intentionally or not... this could be a situation where somebody accidentally made a public repository private, for example, which I think would appear indistinguishable from the repository being deleted for anyone outside of that GitHub organization.

**Comment by crw** [comment] 2023-05-02 23:39
I notified the Registry team of the state of this provider (when I wrote my original comment). Since there is nothing more the Terraform Core team can do to resolve this issue and the reason for the problem is out of our hands, I am going to close this issue. Thanks for reporting it, @puneet-traceable, and I am sorry this provider seems to no longer be supported.

**Closed by crw** 2023-05-02 23:39 UTC
Labels: bug, registry, new
