### ISSUE TITLE
Allow Function and Dynamic Values in Generating Configuration from Imports

### ISSUE THREAD

**Issue by zliang-akamai** [hashicorp/terraform#33880] opened 2023-09-12 21:28 UTC
### Terraform Version

```shell
Terraform v1.5.7
on darwin_arm64
```

### Use Cases

We would like to import some resources based on ids stored in another resource.

### Attempted Solutions

Run `terraform plan -generate-config-out=generated.tf` with the following config.

```terraform
terraform {
  required_providers {
    linode = {
      source = "linode/linode"
    }
  }
}

provider "linode" {
}

resource "linode_instance" "test_instance" {
  label      = "simple_instance"
  region     = "us-southeast"
  type       = "g6-nanode-1"
  private_ip = true

  config {
    label  = "test-config-1"
    kernel = "linode/grub2"
    interface {
      purpose = "public"
    }
    interface {
      purpose = "vlan"
      label   = "test-vlan1"
    }
    devices {
      sda {
        disk_label = "test-disk"
      }
      sdb {
        disk_label = "test-swap"
      }
    }
  }

  disk {
    label      = "test-swap"
    size       = 1024
    filesystem = "swap"
  }

  disk {
    label            = "test-disk"
    size             = 24576
    filesystem       = "ext4"
    authorized_users = ["my_linode_username"]
    root_pass        = "this_is_not_a_safe_password"
    image            = "linode/ubuntu22.04"
  }
}

import {
  to = linode_instance_disk.test_imported_disk
  id = join(",", [linode_instance.test_instance.id, tostring(linode_instance.test_instance.disk.1.id)])
}

import {
  to = linode_instance_disk.test_imported_disk_swap
  id = join(",", [linode_instance.test_instance.id, tostring(linode_instance.test_instance.disk.0.id)])
}
```

But got the errors:

```
╷
│ Error: Unsuitable value type
│ 
│   on main.tf line 61, in import:
│   61:   id = join(",", [linode_instance.test_instance.id, tostring(linode_instance.test_instance.disk.1.id)])
│ 
│ Unsuitable value: value must be known
╵
╷
│ Error: Function calls not allowed
│ 
│   on main.tf line 61, in import:
│   61:   id = join(",", [linode_instance.test_instance.id, tostring(linode_instance.test_instance.disk.1.id)])
│ 
│ Functions may not be called here.
╵
╷
│ Error: Unsuitable value type
│ 
│   on main.tf line 66, in import:
│   66:   id = join(",", [linode_instance.test_instance.id, tostring(linode_instance.test_instance.disk.0.id)])
│ 
│ Unsuitable value: value must be known
╵
╷
│ Error: Function calls not allowed
│ 
│   on main.tf line 66, in import:
│   66:   id = join(",", [linode_instance.test_instance.id, tostring(linode_instance.test_instance.disk.0.id)])
│ 
│ Functions may not be called here.
```

### Proposal

The id values referred were already in the state files, I would suggest allow the config generating operation access the state.

**Comment by jbardin** [comment] 2023-09-13 13:04
Duplicate of #33228

**Closed by jbardin** 2023-09-13 13:04 UTC
Labels: enhancement, import, new
