### ISSUE TITLE
Feature: Support service principal client certificate as a login mechanism for azure backend

### ISSUE THREAD

**Issue by weaktyper** [hashicorp/terraform#25167] opened 2020-06-06 21:31 UTC
### Current Terraform Version

```
Terraform v0.12.25
+ provider.azurerm v2.11.0
```

### Background

According to the [azure backend documentation](https://www.terraform.io/docs/backends/types/azurerm.html), the following parameters can be used to authenticate as a service principal:

```
resource_group_name - (Required) The Name of the Resource Group in which the Storage Account exists.

client_id - (Optional) The Client ID of the Service Principal. This can also be sourced from the ARM_CLIENT_ID environment variable.

client_secret - (Optional) The Client Secret of the Service Principal. This can also be sourced from the ARM_CLIENT_SECRET environment variable.

subscription_id - (Optional) The Subscription ID in which the Storage Account exists. This can also be sourced from the ARM_SUBSCRIPTION_ID environment variable.

tenant_id - (Optional) The Tenant ID in which the Subscription exists. This can also be sourced from the ARM_TENANT_ID environment variable.
```

However, the following parameters are not supported:

```
client_certificate_path     = var.client_certificate_path
client_certificate_password = var.client_certificate_password
```

### Attempted Solutions

- Attempted to login with the client certificate and then use the backend via cli. Doesn't work.

### Proposal

Please allow using the following parameters in the configuration with a service principal client certificate along the lines of the provider authentication mechanism - see [docs here](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_certificate.html)

```
client_certificate_path     = var.client_certificate_path
client_certificate_password = var.client_certificate_password
```

By not making it possible to use the `client_certificate_path` and `client_certificate_password`, it makes this way of logging in less useful. I would prefer not to be forced to use one mechanism for a backend authnetication and another distinct one as the provider login. Right now, I resorted to a `sas_token` but I'd prefer to keep it simple and use certs if possible.

**Comment by tombuildsstuff** [comment] 2020-06-25 09:55
Duplicate of #24179 - would you mind subscribing to that for updates?

**Closed by tombuildsstuff** 2020-06-25 09:55 UTC
Labels: backend/azure, enhancement
