### ISSUE TITLE
TF 1.3:  "allow-missing-config" still needed for importing resources with calculated indexes?

### ISSUE THREAD

**Issue by rramge** [hashicorp/terraform#31703] opened 2022-08-29 11:36 UTC
### Terraform Version

```shell
Terraform v1.3.0-alpha20220817
```

### Terraform Configuration Files

```terraform
module "tos-mgmt-spoke" {
  source = "../../modules/terraform-opentelekomcloud-vpc"

  vpc_name = "tos-mgmt-spoke"
  vpc_cidr = "172.22.33.0/24"

  subnets = {

    cce = {
      name       = "tos-cce"
      cidr       = "172.22.33.0/25"
      gateway_ip = "172.22.33.1"
      dns_list   = ["53.250.28.170", "53.250.44.170"]
    }

    vms = {
      name       = "tos-vms"
      cidr       = "172.22.33.128/25"
      gateway_ip = "172.22.33.129"
      dns_list   = ["53.250.28.170", "53.250.44.170"]
    }
  }
}

```

VPC Module:  [https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-vpc](https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-vpc)

### Debug Output

-

### Expected Behavior

1. terraform apply
2. Check with terraform state list
3. terraform state rm  'module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]'
4. terraform import 'module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]' <id>`

 should remove the resource from the statefile (step 3), and then import the existing resource into the statefile again (step 4)

### Actual Behavior

```
╷
│ Error: Invalid index
│ 
│   on ../../modules/terraform-opentelekomcloud-vpc/locals.tf line 2, in locals:
│    2:   subnet_names = var.subnets == null ? [] : [for index, subnet in var.subnets :opentelekomcloud_vpc_subnet_v1.this[index].name]
│     ├────────────────
│     │ opentelekomcloud_vpc_subnet_v1.this is object with 1 attribute "cce"
│ 
│ The given key does not identify an element in this collection value.

```

Seems like an import is only possible if the index is hardcoded in the module.

### Steps to Reproduce

1. terraform apply
2. Check with terraform state list
3. terraform state rm  'module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]'
4. terraform import 'module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]' <id>

### Additional Context

In the past, you had a similar problem in Issue #26258 (https://github.com/hashicorp/terraform/issues/26258). 
Back then, you introduced the command line option "-allow-missing-config". But with Terraform 1.3 you remove it again (see Changelog, https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md)

Oh well, and with Version 1.3, the error I mention here occurs and I can't find a proper workaround for resolving the issue. I guess that -allow-missing-config would have helped here. So please check and, if necessary, re-evaluate.

**Comment by jbardin** [comment] 2022-08-29 13:53
Hi @rramge,

Thanks for filing the issue. would it possible to create a more self-contained example of the problem you are seeing? Importing a single resource instance using `for_each` should work without any special handling now. Testing a similar module structure, removing a single instance, then re-importing it works with the current development branch of Terraform, so I suspect there is something slightly different in your particular case.

**Comment by rramge** [comment] 2022-08-30 07:04
Hi @jbardin,

thanks so much for your answer :-)  I'll try to elaborate in more detail here and give a step-by-step example.

Given the following module, which is very simple:

```
//------------ VPC ------------------------------------------------------------

resource "opentelekomcloud_vpc_v1" "this" {

  name   = var.vpc_name
  cidr   = var.vpc_cidr
  shared = var.vpc_is_shared

  tags = var.tags
}

//------------ Subnet ---------------------------------------------------------

resource "opentelekomcloud_vpc_subnet_v1" "this" {
  for_each = var.subnets != null ? var.subnets : {}

  name              = each.value["name"]
  cidr              = each.value["cidr"]
  gateway_ip        = each.value["gateway_ip"]
  availability_zone = each.value["az"]
  dhcp_enable       = each.value["has_dhcp"]
  dns_list          = each.value["dns_list"]
  ntp_addresses     = each.value["ntp_server"]
  primary_dns       = null
  secondary_dns     = null
  vpc_id            = opentelekomcloud_vpc_v1.this.id
  tags              = var.tags
}
```

Let's call it and create 1 VPC with 2 subnets:

```
module "tos-mgmt-spoke" {
  source = "../../modules/terraform-opentelekomcloud-vpc"

  vpc_name = "tos-mgmt-spoke"
  vpc_cidr = "172.22.33.0/24"

  subnets = {
    cce = {
      name       = "tos-cce"
      cidr       = "172.22.33.0/25"
      gateway_ip = "172.22.33.1"
      dns_list   = ["53.250.28.170", "53.250.44.170"]
    },
    vms = {
      name       = "tos-vms"
      cidr       = "172.22.33.128/25"
      gateway_ip = "172.22.33.129"
      dns_list   = ["53.250.28.170", "53.250.44.170"]
    }
  }
}
```

State is then as expected:

```
[rramge@ol9 12]$ tf state list
module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]
module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["vms"]
module.tos-mgmt-spoke.opentelekomcloud_vpc_v1.this
[rramge@ol9 12]$ 
```

If we now delete a subnet from the state and import it again, everything is fine. So far, so good, out lab is set up.

**Let's reproduce the error now.**

Suppose you need an output, which gives you a map with the subnet index as name and the ID as value:

```
Changes to Outputs:
  + subnet_list = {
      + "tos-cce" = "1d66c7ae-abbc-4635-b70f-b652a70deff4"
      + "tos-vms" = "b3ca7745-1516-44bd-9493-77e447ed25ed"
    }
```

So, we need to build the map using the zipmap() function and we create a locals.tf:

```
locals {
  subnet_names = var.subnets == null ? [] : [for index, subnet in var.subnets : opentelekomcloud_vpc_subnet_v1.this[index].name]

  subnet_ids   = var.subnets == null ? [] : [for index, subnet in var.subnets : opentelekomcloud_vpc_subnet_v1.this[index].id]

  subnet_list      = zipmap(local.subnet_names, local.subnet_ids)
}
```

together with the outputs.tf:

```
output "subnet_list" {
  value       = local.subnet_list
  description = "A map of subnet names and their icorresponding subnet IDs."
}
```

Now, do the following steps:

1.` tf destroy`  - Destroy everything
2. `tf apply` - Create everything
3. `tf state list` - to check, it should look like this now:

```
[rramge@ol9 12]$ tf state list
module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]
module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["vms"]
module.tos-mgmt-spoke.opentelekomcloud_vpc_v1.this
[rramge@ol9 12]$ 
```

4. Delete ONE of the subnets and import it again. Note: **This will work as expected**, so I don't quote it here.
5. Delete BOTH of the subnets:

```
[rramge@ol9 12]$ tf state rm module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this[\"cce\"]
Removed module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]
Successfully removed 1 resource instance(s).
[rramge@ol9 12]$ tf state rm module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this[\"vms\"]Removed module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["vms"]
Successfully removed 1 resource instance(s).
[rramge@ol9 12]$ 
```

6. Now try to import the subnet again, exactly like you did in step 4. **This will NOT work** and deliver the following error collection:

```
rramge@ol9 12]$ tf import module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this[\"cce\"] 07a3d64b-7f62-4641-a68d-85e7cdf55010
module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]: Importing from ID "07a3d64b-7f62-4641-a68d-85e7cdf55010"...
module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]: Import prepared!
  Prepared opentelekomcloud_vpc_subnet_v1 for import
module.tos-mgmt-spoke.opentelekomcloud_vpc_subnet_v1.this["cce"]: Refreshing state... [id=07a3d64b-7f62-4641-a68d-85e7cdf55010]
╷
│ Error: Invalid index
│ 

│   on ../../modules/terraform-opentelekomcloud-vpc/locals.tf line 2, in locals:
│    2:   subnet_names = var.subnets == null ? [] : [for index, subnet in var.subnets : opentelekomcloud_vpc_subnet_v1.this[index].name]
│     ├────────────────
│     │ opentelekomcloud_vpc_subnet_v1.this is object with 1 attribute "cce"
│ 
│ The given key does not identify an element in this collection value.
╵

╷
│ Error: Invalid index
│ 
│   on ../../modules/terraform-opentelekomcloud-vpc/locals.tf line 3, in locals:
│    3:   subnet_ids   = var.subnets == null ? [] : [for index, subnet in var.subnets : opentelekomcloud_vpc_subnet_v1.this[index].id]
│     ├────────────────
│     │ opentelekomcloud_vpc_subnet_v1.this is object with 1 attribute "cce"
│ 
│ The given key does not identify an element in this collection value.
╵

╷
│ Error: Invalid index
│ 
│   on ../../modules/terraform-opentelekomcloud-vpc/locals.tf line 4, in locals:
│    4:   subnet_uuids = var.subnets == null ? [] : [for index, subnet in var.subnets : opentelekomcloud_vpc_subnet_v1.this[index].subnet_id]
│     ├────────────────
│     │ opentelekomcloud_vpc_subnet_v1.this is object with 1 attribute "cce"
│ 
│ The given key does not identify an element in this collection value.
╵

╷
│ Error: Invalid index
│ 
│   on ../../modules/terraform-opentelekomcloud-vpc/locals.tf line 5, in locals:
│    5:   subnet_cidrs = var.subnets == null ? [] : [for index, subnet in var.subnets : opentelekomcloud_vpc_subnet_v1.this[index].cidr]
│     ├────────────────
│     │ opentelekomcloud_vpc_subnet_v1.this is object with 1 attribute "cce"
│ 
│ The given key does not identify an element in this collection value.
╵

[rramge@ol9 12]$ 
```

Hope this helps,

Ralf

**Comment by jbardin** [comment] 2022-08-30 13:19
Thank you @rramge, deleting both subnets is the key difference here. That issue is not related to missing configuration, as you do actually have the configuration for Terraform the reference. The problem is the same as referenced in #28188, where missing values from an expanded resources can cause evaluation of dependencies to fail. The change that necessitated removing `-allow-missing-config` is part of the first steps to allowing more complex imports like that to work.

**Comment by jbardin** [comment] 2022-08-30 13:39
Duplicate of #28188

**Closed by jbardin** 2022-08-30 13:39 UTC
Labels: bug, waiting for reproduction
