### ISSUE TITLE
Terraform 0.13.0 crash with non-existent backend config file

### ISSUE THREAD

**Issue by shurrman** [hashicorp/terraform#26395] opened 2020-09-28 11:47 UTC
I use backend config files for S3 backend, that look like this:
```
key = "terraform/terraform.prod.proxy.tfstate"
dynamodb_table = "lock-proxy-prod"

```

When I misspelled config file name (i.e. missing file), I was getting TF crash (see the log below).
Putting file in place fixes the issue.

```
2020/09/28 13:47:07 [INFO] Terraform version: 0.13.0  
2020/09/28 13:47:07 [INFO] Go runtime version: go1.14.2
2020/09/28 13:47:07 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init", "-reconfigure", "-backend-config=./config-production.hcl"}
2020/09/28 13:47:07 [DEBUG] Attempting to open CLI config file: /home/aaa/.terraformrc
2020/09/28 13:47:07 Loading CLI configuration from /home/aaa/.terraformrc
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory /home/aaa/.terraform.d/plugins
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory /home/aaa/.local/share/terraform/plugins
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory /home/aaa/.local/share/flatpak/exports/share/terraform/plugins
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory /var/lib/flatpak/exports/share/terraform/plugins
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2020/09/28 13:47:07 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2020/09/28 13:47:07 [INFO] CLI command args: []string{"init", "-reconfigure", "-backend-config=./config-production.hcl"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1ffcab5]

goroutine 1 [running]:
github.com/hashicorp/terraform/command.(*InitCommand).backendConfigOverrideBody(0xc0004a1a40, 0x26d82cb, 0xf, 0xc00046e2c0, 0xc000797d70, 0xc00059f980, 0x29, 0x0, 0x0, 0x17762fa700000000)
        /home/circleci/project/project/command/init.go:862 +0x8b5
github.com/hashicorp/terraform/command.(*InitCommand).initBackend(0xc0004a1a40, 0xc0000b85a0, 0x26d82cb, 0xf, 0xc00046e2c0, 0x1, 0x0, 0x0, 0x0, 0xc00012bb60, ...)
        /home/circleci/project/project/command/init.go:374 +0x4a6
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0004a1a40, 0xc000140060, 0x2, 0x2, 0xc00064c130)
        /home/circleci/project/project/command/init.go:227 +0xeb1
github.com/mitchellh/cli.(*CLI).Run(0xc000726000, 0xc000726000, 0xc0004ebd48, 0x1)
        /home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
        /home/circleci/project/project/main.go:106 +0xde
main.main()
        /home/circleci/project/project/main.go:42 +0x3a

```

**Comment by danieldreier** [comment] 2020-09-29 00:46
Hi! Thanks for reporting this. I think this is probably a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I tried - I put the reproduction case I made up on https://github.com/danieldreier/terraform-issue-reproductions/tree/master/26395, but I'm getting the expected error message of `Error: Failed to read file`, and so I'm stuck.  

Can you please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would be a PR against that GitHub repo so I can directly clone it and run it and see the issue for myself.

**Comment by mildwonkey** [comment] 2021-04-30 16:14
I'm going to close this, since we weren't able to get a reproduction, but if you are still experiencing a reproducible problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by mildwonkey** 2021-04-30 16:14 UTC
Labels: bug, crash, v0.13, waiting for reproduction
