### ISSUE TITLE
aws_route53_record alias always detects changes if using upper case

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform#9411] opened 2016-10-17 19:32 UTC
### Terraform Version
0.7.6

### Affected Resource(s)
`aws_route53_record` (using an `alias`)

### Expected Behavior
Since DNS names are not case sensitive, case changes in alias name should not cause updates.

### Actual Behavior
Terraform detects a difference on every run.

Right now I workaround this by using something similar to the following:

```hcl
resource "aws_route53_record" "name" {
  alias {
    name = "${lower("MYNAME")}"
  }
}
```

But it should just be built in to the resource.

**Comment by paultyng** [comment] 2016-10-17 19:34
This is mostly an issue due to `aws_alb.dns_name` giving mixed case values.

**Comment by jbardin** [comment] 2016-10-19 21:24
Hi,

Thanks for filing this with the workaround! Though this is probably expected, it should either document the issue specifically, or have the provider normalize the values.

**Comment by alexraju** [comment] 2016-10-28 10:47
The issue may be similar to what I'm facing: 

```
resource "aws_route53_record" "record" {
  zone_id = "${var.hosted_zone_id}"
  name = "${var.dns_record_name}.${var.domain_name}"
  type = "A"

  alias {
    name = "${aws_alb.abc.dns_name}"
    zone_id = "${aws_alb.abc.zone_id}"
    evaluate_target_health = false
  }
}
```


```
terraform plan

~ module.dcos.aws_route53_record.master_record
    alias.123123124123.evaluate_target_health: "" => "false"
    alias.123123124123.name:                             "" => "internal-ab-234-Master-terra-4444444.ap-northeast-1.elb.amazonaws.com"
    alias.123123124123.zone_id:                "" => "XXXXXXXXXXXXXX"
    alias.66765543.evaluate_target_health:  "false" => "false"
    alias.66765543.name:                    "internal-ab-234-master-terra-4444444.ap-northeast-1.elb.amazonaws.com" => ""
    alias.66765543.zone_id:                 "XXXXXXXXXXXXXX" => ""

```

**Comment by stack72** [comment] 2016-10-28 15:29
Hi @paultyng 

Thanks for the issue here - I am actively trying to fix a number of issues with the Alias name - I am going to close this as a dupe of #9628 as that is where i started looking at my investigations

Thanks again

Sorry it is causing you issues

Paul

**Closed** 2016-10-28 15:29 UTC
Labels: bug, provider/aws
