### ISSUE TITLE
Terraform registry not publishing latest module version

### ISSUE THREAD

**Issue by bharathkkb** [hashicorp/terraform#34186] opened 2023-11-03 16:38 UTC
### Terraform Version

```shell
N/A
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

We have a module https://github.com/terraform-google-modules/terraform-google-sql-db which has a newer 17.0 release but it is not being picked up by the registry in https://registry.terraform.io/modules/GoogleCloudPlatform/sql-db/google/latest. The registry is using the `GoogleCloudPlatform` namespace as this was a repo migrated from `GoogleCloudPlatform` org to `terraform-google-modules`. The repo redirect is still in place https://github.com/GoogleCloudPlatform/terraform-google-sql-db.

### Actual Behavior

Latest module version is not picked up.

### Steps to Reproduce

N/A

**Comment by g-awmalik** [comment] 2023-11-03 22:06
Resolved by manually invoking the sync from the registry.

**Comment by jbardin** [comment] 2023-11-06 14:46
This was probably caused by the GitHub outage on Friday. Going to close this for now.

Thanks!

**Closed by jbardin** 2023-11-06 14:46 UTC
Labels: bug, registry, new
