### ISSUE TITLE
Upgrade terraform to 1.2.0 or higher, terraform bash completion is broken.

### ISSUE THREAD

**Issue by kyleli666** [hashicorp/terraform#31142] opened 2022-05-28 09:49 UTC
Ubuntu 20 or 22, upgrade terraform from 1.1.9 to 1.2.0 or higher.
```
apt upgrade
```
Then, terraform bash completion is broken.

### Terraform Version

```
Terraform v1.2.1
on linux_amd64
```
v1.2.0 also has this issue.

### Terraform Configuration Files

```terraform
...
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x251f100, 0xc000620000})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/mitchellh/cli.(*CLI).processArgs(0xc0001ec3c0)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:688 +0x9ec
github.com/mitchellh/cli.(*CLI).init(0xc0001ec3c0)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:392 +0x3e9
sync.(*Once).doSlow(0xc000050034?, 0xc?)
        /usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/mitchellh/cli.(*CLI).Subcommand(...)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.3/cli.go:276
main.realMain()
        /home/circleci/project/project/main.go:240 +0xfb5
main.main()
        /home/circleci/project/project/main.go:58 +0x19
```
### Expected Behavior

Press "tab" after "terraform", commands should show up.
### Actual Behavior

Press "tab" after "terraform", the above "Debug output" showed up.
### Steps to Reproduce

In Ubuntu 20 or 22, install terraform , with the official repo
```
apt install terraform
```
Copy `complete -C /usr/bin/terraform terraform` to .bashrc.
Restart the terminal, run terraform and press `tab`
```
terraform <tab>
```

**Comment by kmoe** [comment] 2022-05-30 11:21
Thanks for filing this issue. Duplicate of https://github.com/hashicorp/terraform/issues/31126.

**Closed by kmoe** 2022-05-30 11:21 UTC
Labels: bug, new
