### ISSUE TITLE
[BUG]:  runtime error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by diegotony** [hashicorp/terraform#33811] opened 2023-09-06 12:28 UTC
### Terraform Version

```shell
Terraform v1.4.0
```

## code
```terraform
provider "aws" {
  region = "us-east-1"
}

locals {
  tags = {
    "Name"   = "${var.redshift_name}"
    "nombre" = "${var.redshift_name}"
  }

  iam_role = [
    aws_iam_role.this.arn
  ]
}


variable "redshift_name" {
  type        = string
  description = "Nombre del clúster de Redshift"
}


variable "redshift_node_type" {
  type        = string
  description = "Tipo de nodo para el clúster de Redshift"
  default     = "dc2.large"
}


variable "redshift_cluster_type" {
  type        = string
  description = "Tipo de clúster de Redshift"
  default     = "multi-node"
}


variable "redshift_number_of_nodes" {
  type        = number
  description = "Número de nodos para el clúster de Redshift"
  default     = 3
}


variable "redshift_port" {
  type        = number
  description = "Puerto utilizado para la conexión al clúster de Redshift"
  default     = 5439
}


variable "redshift_database_name" {
  type        = string
  description = "Nombre de la base de datos en el clúster de Redshift"
  default     = "datalake"
}


variable "redshift_master_username" {
  type        = string
  description = "Nombre de usuario maestro del clúster de Redshift"
  default     = "admin"
}


variable "redshift_master_password" {
  type        = string
  description = "Contraseña del usuario maestro del clúster de Redshift"
  default     = "Admin123"
}


variable "redshift_encrypted" {
  type        = bool
  description = "Indica si el clúster de Redshift debe estar encriptado"
  default     = true
}

variable "redshift_snapshot_skip_final_snapshot" {
  type        = bool
  description = "Indica si se debe omitir la creación de una instantánea final al eliminar el clúster de Redshift"
  default     = true
}

variable "redshift_snapshot_automated_snapshot_retention_period" {
  type        = number
  description = "Período de retención de instantáneas automáticas (en días) para el clúster de Redshift"
  default     = 7
}


variable "redshift_snapshot_preferred_maintenance_window" {
  type        = string
  description = "Ventana de mantenimiento preferida para el clúster de Redshift"
  default     = "Sun:00:00-Sun:03:00"
}


variable "redshift_vpc_publicly_accessible" {
  type        = bool
  description = "Indica si el clúster de Redshift debe ser accesible públicamente"
  default     = false
}


variable "vpc_security_group_ids" {
  type        = list(any)
  description = "Lista de IDs de grupos de seguridad de VPC asociados al clúster de Redshift"
  default     = []
}


variable "iam_role_arns" {
  type        = list(any)
  description = "Roles de IAM asociados al clúster de Redshift"
  default     = []
}

variable "tags" {
  type        = any
  description = "Etiquetas adicionales para el clúster de Redshift"
}

variable "vpc_id" {
  type        = string
  description = "ID de la VPC en la que se debe crear el clúster de Redshift"
}


variable "subnet_ids" {
  type        = list(string)
  description = "Lista de IDs de subredes en las que se debe crear el clúster de Redshift"
}


variable "parameters" {
  type        = list(object({ name = string, value = string }))
  description = "Lista de parámetros de configuración para el clúster de Redshift"
  default = [
    { name = "require_ssl", value = "true" },
    { name = "enable_user_activity_logging", value = "true" },
    { name = "query_group", value = "example" },
  ]
}

#* Logging

variable "logging" {
  type = object({
    enable = bool, 
    bucket_name = optional(string), 
    s3_key_prefix = optional(string)
  }) 
}




resource "aws_iam_role" "this" {
  name =  "${var.redshift_name}_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Action = "sts:AssumeRole",
        Effect = "Allow",
        Principal = {
          Service = "redshift.amazonaws.com"
        }
      }
    ]
  })

  tags = merge(
    var.tags,
    {
      "nombre" = "${var.redshift_name}-role"
      "Name"   = "${var.redshift_name}-role"
    },
  )
}

resource "aws_iam_role_policy_attachment" "redshift_athena_full_policy" {
  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"
}

resource "aws_iam_role_policy_attachment" "redshift_glue_policy" {
  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
}

resource "aws_iam_role_policy_attachment" "redshift_glue_console_policy" {
  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess"

}

resource "aws_redshift_parameter_group" "this" {
  name   = "${var.redshift_name}-custom-parameter-group"
  family = "redshift-1.0"

dynamic "parameter" {
    for_each = var.parameters
    content {
        name = parameter.value["name"]
        value = parameter.value["value"]
    }
}

  tags = merge(
    var.tags, local.tags
  )

}

resource "aws_security_group" "this" {
  name        = "${var.redshift_name}-security-group"
  description = "Redshift Security Group for ${var.redshift_name}"
  vpc_id      = var.vpc_id

  ingress {
    from_port   = 5439 # Puerto por defecto de Redshift
    to_port     = 5439
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"] # Cambia esto para restringir el acceso
  }
  tags = var.tags
}

resource "aws_redshift_subnet_group" "this" {
  name       = "${var.redshift_name}-subnet-group"
  description = "My Redshift Subnet Group for ${var.redshift_name}"
  subnet_ids = var.subnet_ids
  tags = var.tags
}


resource "aws_redshift_cluster" "this" {

  depends_on = [
    aws_iam_role.this,
    aws_redshift_parameter_group.this,
  ]

  cluster_identifier = var.redshift_name
  node_type          = var.redshift_node_type
  cluster_type       = var.redshift_cluster_type
  number_of_nodes    = var.redshift_number_of_nodes
  port               = var.redshift_port

  database_name                = var.redshift_database_name
  master_username              = var.redshift_master_username
  master_password              = var.redshift_master_password
  encrypted                    = var.redshift_encrypted
  cluster_parameter_group_name = aws_redshift_parameter_group.this.name

  
  logging {
    enable = var.logging.enable    
    bucket_name        =  var.logging.bucket_name
    s3_key_prefix      = var.logging.s3_key_prefix
  }

  #* snapshots
  skip_final_snapshot                 = var.redshift_snapshot_skip_final_snapshot
  final_snapshot_identifier           = var.redshift_name
  automated_snapshot_retention_period = var.redshift_snapshot_automated_snapshot_retention_period
  preferred_maintenance_window        = var.redshift_snapshot_preferred_maintenance_window

  #* Network
  publicly_accessible       = var.redshift_vpc_publicly_accessible
  cluster_subnet_group_name = aws_redshift_subnet_group.this.name
  vpc_security_group_ids    = concat([aws_security_group.this.id], var.vpc_security_group_ids)

  #* IAM
  iam_roles = concat([aws_iam_role.this.arn], var.iam_role_arns)

  #! TAGS
  tags = merge(
    var.tags, local.tags
  )
}

```

## Module

```terraform
data "aws_vpc" "vpc" {
  tags = {
    Name = "TEST"
  }
}


data "aws_subnets" "public" {
  filter {
    name   = "vpc-id"
    values = [
      data.aws_vpc.vpc.id
    ]
  }
  tags = {
    Tier = "Test"
  }
}

module "poc" {
    source = "./redshift_module/"
    redshift_name = "testredshift"
    vpc_id = data.aws_vpc.vpc.id
    subnet_ids = data.aws_subnets.public.ids
    logging = {
      enable = false
    }
    tags = {
      Terraform   = "yes"
      environment = "staging"
    }
}

```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
runtime error: invalid memory address or nil pointer dereference
goroutine 24 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
	/home/circleci/project/project/internal/plans/plan.go:[100](https://gitlab.com/cencosud-ds/cencommerce/iac/dev-platform/-/jobs/5028704131#L100) +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000900960, {0x2ccf8f8, 0xc000b74140}, {0x2ccf8f8, 0xc000b74180}, 0xc00027f560, 0xc000b74100)
	/home/circleci/project/project/internal/backend/local/backend_plan.go:[104](https://gitlab.com/cencosud-ds/cencommerce/iac/dev-platform/-/jobs/5028704131#L104) +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a

### Expected Behavior

plan should review resource changes

### Actual Behavior

throws a terraform crash error

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

Im creating a redshift module

**Comment by jbardin** [comment] 2023-09-06 13:54
Duplicate of #32810

**Closed by jbardin** 2023-09-06 13:54 UTC
Labels: bug, new
