### ISSUE TITLE
Outputs are removed from state file after a targeted apply

### ISSUE THREAD

**Issue by tmichel** [hashicorp/terraform#12140] opened 2017-02-21 16:42 UTC
### Terraform Version

```
$ terraform -v
Terraform v0.8.7
```

### Affected Resource(s)

It affects all outputs that are not touched by the current targets.

### Expected Behavior

After a targeted apply the outputs that have not changed should still be there.

This breaks the `terraform output` command as well as the `terraform_remote_state` data source.

### Actual Behavior

After the apply outputs that have previously existed should still exist in the state file.

```
# module.foo does not have any outputs but there are other outputs defined for
# the root module
$ terraform apply -target module.foo

$ terraform output
The state file has no outputs defined. Define an output
in your configuration with the `output` directive and re-run
`terraform apply` for it to become available.
```

### Steps to Reproduce

1. `terraform apply -target <any resource>`
2. `terraform output`

### References

This might be related to #10911

**Comment by personias** [comment] 2017-03-13 19:56
+1
I get the same results when I run 
`terraform output -module=module.foo `

This works fine in 0.8.5

**Comment by wr0ngway** [comment] 2017-03-16 19:40
As a workaround, running refresh after your targeted apply will put the outputs back.

**Comment by dcosson** [comment] 2017-03-17 21:04
I'm also seeing this issue, pretty sure it was working fine in 0.8.5 but on 0.8.8 I get this bug.

@wr0ngway Thanks for posting, the workaround of running `terraform refresh` works to put the outputs back.

**Comment by bondyk** [comment] 2017-03-24 13:00
I'm having the same issue with terraform 0.8.7. Running `terraform refresh` fixes the problem.

**Comment by lconnell** [comment] 2017-05-23 13:57
Same issue here on 0.9.5. I have been executing a **refresh**, but this is inconvenient and takes too much time on larger environments. When using **-target**, it should not overwrite what already exists.

No developer comments?

**Comment by agurinov** [comment] 2017-05-23 15:07
Same problem
terraform 0.9.5

**Comment by julianalves** [comment] 2017-06-30 11:00
Same problem!

**Comment by apparentlymart** [comment] 2017-06-30 17:51
Hi everyone! Sorry for the issue here.

I think this is the same issue as was being discussed in #14186, which we fixed in #14378, and in turn released in version 0.9.6. If one of you could give this a try in 0.9.6 or newer and see if the problem still persists, that'd be much appreciated.

**Comment by agurinov** [comment] 2017-07-02 10:29
There is no issue in 0.9.6 for me
Thanks!

**Comment by apparentlymart** [comment] 2017-07-02 14:53
Thanks for testing @agurinov! In that case, I'm going to close this.

As some context on what we did here: in #14378 we added a new capability to the targeting system to allow certain graph node types to be _implicitly_ targeted if anything they depend on is targeted, and then made outputs behave in this way. This means that if an output `foo` depends on a resource `aws_instance.foo`, the output will be targeted implicitly if `aws_instance.foo` is targeted. This then ensures the expected behavior: an output value is updated any time something it depends on is updated, but skipped if nothing it depends on has been targeted.

If anyone still sees problems that seems similar to this, I'd ask that they open a new top-level issue for it with some reproduction details, since the details are likely to be different even if symptoms are similar.

**Closed by apparentlymart** 2017-07-02 14:53 UTC
Labels: bug, core
