### ISSUE TITLE
Terraform 0.13.0: plan shows ID changes in data sources

### ISSUE THREAD

**Issue by sblask** [hashicorp/terraform#25912] opened 2020-08-19 04:41 UTC
### Terraform Version

```
$ terraform version
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/vault v2.12.2
```

### Expected Behavior

`terraform plan -out plan` should show no changes.

### Actual Behavior

Since upgrading to Terraform 0.13.0 I get something like this:
```
 <= data "aws_availability_zones" "default"  {
        group_names = [
            "ap-southeast-2",
        ]
      ~ id          = "2020-08-19 03:57:14.226776 +0000 UTC" -> "2020-08-19 03:57:30.667586 +0000 UTC"
        names       = [
            "ap-southeast-2a",
            "ap-southeast-2b",
            "ap-southeast-2c",
        ]
        zone_ids    = [
            "apse2-az1",
            "apse2-az3",
            "apse2-az2",
        ]
    }
```

`terraform apply plan` does not fix the problem, in fact, it doesn't do anything.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -out plan`

**Comment by mildwonkey** [comment] 2020-08-19 18:20
hi @sblask , I'm sorry you're experiencing this issue. It is a duplicate of https://github.com/hashicorp/terraform/issues/25812, and the problem should be be fixed in the next terraform release. I am going to close this as a duplicate. Thanks, and sorry again!

**Closed by mildwonkey** 2020-08-19 18:20 UTC
Labels: bug, new
