### ISSUE TITLE
Add Tags Support for Inline AWS EBS Device

### ISSUE THREAD

**Issue by tylerFowler** [hashicorp/terraform#4919] opened 2016-01-30 23:39 UTC
I noticed that when you define an EBS device inline with an aws instance like so:

```
resource "aws_instance" "web" {
  # definition...
  ebs_block_device {
    # EBS info...
  }
}
```

You cannot specify tags, whereas if you look at the created resource in the AWS console it definitely supports tags. Perhaps this is because double nested blocks aren't supported but in any case I'd really like to see it supported.

**Comment by cloudynetwork** [comment] 2016-04-05 01:21
I second this. Please add tagging for inline EBS devices.

**Comment by cloudynetwork** [comment] 2016-05-09 22:18
Any news on if or when this may get implemented? There really is no practical way to tag EBS volumes right now...and tagging EBS volumes is a big part of providing a quality environment!

**Comment by igorlg** [comment] 2016-05-09 22:18
+1! Please, this feature is quite important for us!

**Comment by djmjmurphy** [comment] 2016-06-27 18:20
+1
We need this as well for chargebacks and iam permissions.  It would also be helpful if the ebs_block_device supported counts.

**Comment by stack72** [comment] 2016-11-14 12:37
Hi @tylerFowler 

Apologies for the delay in responding here - this is already a requested feature in #4919 - I am going to close this as a duplicate of that so that we can track all information in this issue

Thanks again

Paul

**Closed** 2016-11-14 12:37 UTC
Labels: enhancement, provider/aws
