### ISSUE TITLE
Splat expressions evaluates differently from equivalent for

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#32103] opened 2022-10-27 17:13 UTC
### Terraform Version

```shell
Terraform v1.3.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/googleworkspace v0.7.0
```

### Terraform Configuration Files

```terraform
locals {
  managers = [
    "foo@google.com",
    "bar@google.com",
  ]
}

resource "googleworkspace_group_member" "manager" {
  for_each = toset(local.managers)

  group_id = "foobar@google.com"
  email    = each.value
  role     = "MANAGER"
}

output "managers" {
  value = googleworkspace_group_member.manager[*].email
  # value = [for manager in googleworkspace_group_member.manager : manager.email]
}
```

### Debug Output

<details>
  <summary>Output</summary>

```
TF_LOG=debug terraform plan
2022-10-27T12:02:28.132-0500 [INFO]  Terraform version: 1.3.3
2022-10-27T12:02:28.133-0500 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2022-10-27T12:02:28.133-0500 [DEBUG] using github.com/hashicorp/hcl/v2 v2.14.1
2022-10-27T12:02:28.133-0500 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2022-10-27T12:02:28.133-0500 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2022-10-27T12:02:28.133-0500 [DEBUG] using github.com/zclconf/go-cty v1.11.1
2022-10-27T12:02:28.133-0500 [INFO]  Go runtime version: go1.19.1
2022-10-27T12:02:28.133-0500 [INFO]  CLI args: []string{"/usr/local/Cellar/tfenv/3.0.0/versions/1.3.3/terraform", "plan"}
2022-10-27T12:02:28.133-0500 [DEBUG] Attempting to open CLI config file: /Users/foo/.terraformrc
2022-10-27T12:02:28.133-0500 [INFO]  Loading CLI configuration from /Users/foo/.terraformrc
2022-10-27T12:02:28.133-0500 [DEBUG] checking for credentials in "/Users/foo/.terraform.d/plugins"
2022-10-27T12:02:28.133-0500 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2022-10-27T12:02:28.133-0500 [DEBUG] will search for provider plugins in /Users/foo/.terraform.d/plugins
2022-10-27T12:02:28.135-0500 [DEBUG] ignoring non-existing provider search directory /Users/foo/Library/Application Support/io.terraform/plugins
2022-10-27T12:02:28.135-0500 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2022-10-27T12:02:28.135-0500 [INFO]  CLI command args: []string{"plan"}
2022-10-27T12:02:28.136-0500 [DEBUG] New state was assigned lineage "1bdb7ea5-1309-b704-1f85-62e15116d29e"
2022-10-27T12:02:28.200-0500 [DEBUG] checking for provisioner in "."
2022-10-27T12:02:28.200-0500 [DEBUG] checking for provisioner in "/usr/local/Cellar/tfenv/3.0.0/versions/1.3.3"
2022-10-27T12:02:28.200-0500 [DEBUG] checking for provisioner in "/Users/foo/.terraform.d/plugins"
2022-10-27T12:02:28.200-0500 [INFO]  backend/local: starting Plan operation
2022-10-27T12:02:28.202-0500 [DEBUG] created provider logger: level=debug
2022-10-27T12:02:28.202-0500 [INFO]  provider: configuring client automatic mTLS
2022-10-27T12:02:28.223-0500 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace args=[.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace]
2022-10-27T12:02:28.226-0500 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace pid=79331
2022-10-27T12:02:28.226-0500 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace
2022-10-27T12:02:28.239-0500 [INFO]  provider.terraform-provider-googleworkspace: configuring server automatic mTLS: timestamp=2022-10-27T12:02:28.239-0500
2022-10-27T12:02:28.277-0500 [DEBUG] provider: using plugin: version=5
2022-10-27T12:02:28.277-0500 [DEBUG] provider.terraform-provider-googleworkspace: plugin address: address=/var/folders/j4/ll69y0wd7vxfq18p5vfq2szc4kfcs7/T/plugin679556806 network=unix timestamp=2022-10-27T12:02:28.277-0500
2022-10-27T12:02:28.309-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-10-27T12:02:28.310-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace pid=79331
2022-10-27T12:02:28.310-0500 [DEBUG] provider: plugin exited
2022-10-27T12:02:28.310-0500 [DEBUG] Building and walking validate graph
2022-10-27T12:02:28.310-0500 [DEBUG] ProviderTransformer: "googleworkspace_group_member.manager" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/hashicorp/googleworkspace"]
2022-10-27T12:02:28.311-0500 [INFO]  ReferenceTransformer: reference not found: "each.value"
2022-10-27T12:02:28.311-0500 [DEBUG] ReferenceTransformer: "googleworkspace_group_member.manager" references: [local.managers (expand)]
2022-10-27T12:02:28.311-0500 [DEBUG] ReferenceTransformer: "local.managers (expand)" references: []
2022-10-27T12:02:28.311-0500 [DEBUG] ReferenceTransformer: "output.managers (expand)" references: [googleworkspace_group_member.manager]
2022-10-27T12:02:28.311-0500 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/hashicorp/googleworkspace\"]" references: []
2022-10-27T12:02:28.311-0500 [DEBUG] Starting graph walk: walkValidate
2022-10-27T12:02:28.311-0500 [DEBUG] created provider logger: level=debug
2022-10-27T12:02:28.311-0500 [INFO]  provider: configuring client automatic mTLS
2022-10-27T12:02:28.319-0500 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace args=[.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace]
2022-10-27T12:02:28.322-0500 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace pid=79332
2022-10-27T12:02:28.322-0500 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace
2022-10-27T12:02:28.336-0500 [INFO]  provider.terraform-provider-googleworkspace: configuring server automatic mTLS: timestamp=2022-10-27T12:02:28.336-0500
2022-10-27T12:02:28.379-0500 [DEBUG] provider: using plugin: version=5
2022-10-27T12:02:28.380-0500 [DEBUG] provider.terraform-provider-googleworkspace: plugin address: address=/var/folders/j4/ll69y0wd7vxfq18p5vfq2szc4kfcs7/T/plugin036403451 network=unix timestamp=2022-10-27T12:02:28.379-0500
2022-10-27T12:02:28.418-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-10-27T12:02:28.420-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace pid=79332
2022-10-27T12:02:28.420-0500 [DEBUG] provider: plugin exited
2022-10-27T12:02:28.420-0500 [INFO]  backend/local: plan calling Plan
2022-10-27T12:02:28.420-0500 [DEBUG] Building and walking plan graph for NormalMode
2022-10-27T12:02:28.420-0500 [DEBUG] ProviderTransformer: "googleworkspace_group_member.manager (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/hashicorp/googleworkspace"]
2022-10-27T12:02:28.420-0500 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/hashicorp/googleworkspace\"]" references: []
2022-10-27T12:02:28.420-0500 [INFO]  ReferenceTransformer: reference not found: "each.value"
2022-10-27T12:02:28.420-0500 [DEBUG] ReferenceTransformer: "googleworkspace_group_member.manager (expand)" references: [local.managers (expand)]
2022-10-27T12:02:28.420-0500 [DEBUG] ReferenceTransformer: "local.managers (expand)" references: []
2022-10-27T12:02:28.420-0500 [DEBUG] ReferenceTransformer: "output.managers (expand)" references: [googleworkspace_group_member.manager (expand)]
2022-10-27T12:02:28.420-0500 [DEBUG] Starting graph walk: walkPlan
2022-10-27T12:02:28.420-0500 [DEBUG] created provider logger: level=debug
2022-10-27T12:02:28.420-0500 [INFO]  provider: configuring client automatic mTLS
2022-10-27T12:02:28.427-0500 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace args=[.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace]
2022-10-27T12:02:28.430-0500 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace pid=79333
2022-10-27T12:02:28.430-0500 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace
2022-10-27T12:02:28.443-0500 [INFO]  provider.terraform-provider-googleworkspace: configuring server automatic mTLS: timestamp=2022-10-27T12:02:28.442-0500
2022-10-27T12:02:28.484-0500 [DEBUG] provider: using plugin: version=5
2022-10-27T12:02:28.484-0500 [DEBUG] provider.terraform-provider-googleworkspace: plugin address: address=/var/folders/j4/ll69y0wd7vxfq18p5vfq2szc4kfcs7/T/plugin741310536 network=unix timestamp=2022-10-27T12:02:28.484-0500
2022-10-27T12:02:28.519-0500 [DEBUG] Resource instance state not found for node "googleworkspace_group_member.manager[\"bar@google.com\"]", instance googleworkspace_group_member.manager["bar@google.com"]
2022-10-27T12:02:28.519-0500 [DEBUG] Resource instance state not found for node "googleworkspace_group_member.manager[\"foo@google.com\"]", instance googleworkspace_group_member.manager["foo@google.com"]
2022-10-27T12:02:28.520-0500 [INFO]  ReferenceTransformer: reference not found: "local.managers"
2022-10-27T12:02:28.520-0500 [INFO]  ReferenceTransformer: reference not found: "each.value"
2022-10-27T12:02:28.520-0500 [DEBUG] ReferenceTransformer: "googleworkspace_group_member.manager[\"bar@google.com\"]" references: []
2022-10-27T12:02:28.520-0500 [INFO]  ReferenceTransformer: reference not found: "local.managers"
2022-10-27T12:02:28.520-0500 [INFO]  ReferenceTransformer: reference not found: "each.value"
2022-10-27T12:02:28.520-0500 [DEBUG] ReferenceTransformer: "googleworkspace_group_member.manager[\"foo@google.com\"]" references: []
2022-10-27T12:02:28.520-0500 [DEBUG] refresh: googleworkspace_group_member.manager["foo@google.com"]: no state, so not refreshing
2022-10-27T12:02:28.520-0500 [DEBUG] refresh: googleworkspace_group_member.manager["bar@google.com"]: no state, so not refreshing
2022-10-27T12:02:28.522-0500 [WARN]  Provider "registry.terraform.io/hashicorp/googleworkspace" produced an invalid plan for googleworkspace_group_member.manager["bar@google.com"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .delivery_settings: planned value cty.StringVal("ALL_MAIL") for a non-computed attribute
      - .type: planned value cty.StringVal("USER") for a non-computed attribute
2022-10-27T12:02:28.522-0500 [WARN]  Provider "registry.terraform.io/hashicorp/googleworkspace" produced an invalid plan for googleworkspace_group_member.manager["foo@google.com"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .delivery_settings: planned value cty.StringVal("ALL_MAIL") for a non-computed attribute
      - .type: planned value cty.StringVal("USER") for a non-computed attribute
2022-10-27T12:02:28.522-0500 [ERROR] vertex "output.managers" error: Unsupported attribute
2022-10-27T12:02:28.522-0500 [ERROR] vertex "output.managers (expand)" error: Unsupported attribute
2022-10-27T12:02:28.522-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-10-27T12:02:28.524-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/googleworkspace/0.7.0/darwin_amd64/terraform-provider-googleworkspace pid=79333
2022-10-27T12:02:28.524-0500 [DEBUG] provider: plugin exited
2022-10-27T12:02:28.524-0500 [INFO]  backend/local: plan operation completed
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 17, in output "managers":
│   17:   value = googleworkspace_group_member.manager[*].email
│ 
│ This object does not have an attribute named "email".
```
</details>

### Expected Behavior

Per https://developer.hashicorp.com/terraform/language/expressions/splat, having the output value be `googleworkspace_group_member.manager[*].email` should have worked in the same way that `[for manager in googleworkspace_group_member.manager : manager.email]` successfully works

### Actual Behavior

With `googleworkspace_group_member.manager[*].email` for the output value, it fails with
```
│ Error: Unsupported attribute
│ 
│   on main.tf line 17, in output "managers":
│   17:   value = googleworkspace_group_member.manager[*].email
│ 
│ This object does not have an attribute named "email".
```
With `[for manager in googleworkspace_group_member.manager : manager.email]` as the output value, it plans successfully

### Steps to Reproduce

1. terraform init
2. terraform plan

**Comment by apparentlymart** [comment] 2022-10-27 22:26
Hi @joe-a-t,

The splat operator `[*]` is equivalent to `for` only if the left-hand operand is a "list-like" value, as described in [Splat Expressions with Maps](https://developer.hashicorp.com/terraform/language/expressions/splat#splat-expressions-with-maps):

> The splat expression patterns shown above apply only to lists, sets, and tuples. To get a similar result with a map or object value you must use [`for` expressions](https://developer.hashicorp.com/terraform/language/expressions/for).
>
> Resources that use the for_each argument will appear in expressions as a map of objects, so you can't use splat expressions with those resources. For more information, see [Referring to Resource Instances](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#referring-to-instances).

What happened here is that you've activated the behavior described in [Single Values as Lists](https://developer.hashicorp.com/terraform/language/expressions/splat#single-values-as-lists). That heading is a bit misleading because when it says "Single Values" it really means "anything other than a list, tuple, or set" as mentioned in the first paragraph of the section.

> Splat expressions have a special behavior when you apply them to a value that isn't a list, set, or tuple.
>
> If the value is anything other than a null value then the splat expression will transform it into a single-element list, or more accurately a single-element tuple value. If the value is null then the splat expression will return an empty tuple.

In other words, the expression you showed evaluated as follows:

* `googleworkspace_group_member.manager[*]` produced a tuple containing the map representing all of the instances of `googleworkspace_group_member.manager`
* The `.email` operator then tried to look up a key called "email" in that map, which didn't exist because your `local.managers` does not contain an element with the value `"email"`.

This special behavior of `[*]` is essentially here just to preserve how splat behaved in Terraform v0.11 and earlier (which is before Terraform supported `for_each`), and module authors often rely on it to concisely translate from an optional variable which might be null into a tuple of zero or one elements, as described in the paragraph that starts with "This special behavior can be useful for...".

Terraform behaves as designed here. The design was from an earlier time and is perhaps a bit regrettable in retrospect, but nonetheless it is protected by [the v1.x Compatibility Promises](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises) and so cannot be changed. Therefore I'm going to close this issue.

The `for` expression syntax is the more general solution which works in a similar way for collection and structural types of all kinds. Alternatively, some authors prefer to use the `values` function to obtain a list of only the values from the map and then apply the splat expression to that intermediate result:

```hcl
output "managers" {
  value = values(googleworkspace_group_member.manager)[*].email
}
```

The above is functionally equivalent to the `for` expression you wrote, but does the work in two steps (projecting map to list and then from list to list) rather than just one step (projecting directly from map to list).

Thanks!

**Closed by apparentlymart** 2022-10-27 22:26 UTC
Labels: bug, new

**Comment by joe-a-t** [comment] 2022-10-28 15:51
Hey @apparentlymart, thanks a lot for that explanation. Could we re-open this as an "Improve error messaging" ticket? Would be possible and make sense to swallow the `Error: Unsupported attribute` and instead output something that says "Cannot use splat with a map, use a `for` with the map instead or change the map to a list if you would still like to use splat"? Not sure how possible it would be to automatically detect this use case and replace the error when it occurs or not

**Comment by apparentlymart** [comment] 2022-10-28 23:53
I'm afraid I'm not sure there's anything we can do to improve the messaging here, because your usage of the splat operator was technically valid. It only failed because you then tried to use that result in a way that doesn't make sense for what the operator actually does in that case... notice that it's the `.email` attribute access that failed, not the `[*]` operator.
