### ISSUE TITLE
Terraform-Bundle error w/ v0.13.1

### ISSUE THREAD

**Issue by Gaveno** [hashicorp/terraform#25885] opened 2020-08-17 17:01 UTC
Error: "Failed to read config: At 6:10: root.providers.tower: not an object type for struct (*ast.ListType)" occurs when trying to create a bundle package using the latest github commits.
Provider binary has been tested and is working correctly.
![Bundle_error_file](https://user-images.githubusercontent.com/14030808/90423031-02270e00-e079-11ea-96c4-2223e67f7611.PNG)

Version 0.13.0 works
Version 0.13.1 does not work

**Comment by mildwonkey** [comment] 2020-08-18 20:35
Hi @Gaveno ! Thanks for reporting this!

`terraform-bundle` has a new configuration file structure which was introduced in v0.13.0 to support terraform's new provider source concept - documented [here](https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle#usage), so your configuration will need to be updated. The directory layout has changed as well, so you will need to review the [custom plugins](https://github.com/hashicorp/terraform/blob/master/tools/terraform-bundle/README.md#custom-plugins) section of that document.

Also, `terraform-bundle` and the terraform version you are bundling need to have the same version, by which I mean: 
To bundle terraform v0.12, build `terraform-bundle` from a v0.12 tag; to bundle terraform v0.13, build `terraform-bundle` from a v0.13 tag, etc. I'm quite surprised to hear that your config file worked in `terraform-bundle` built from terraform v0.13.0 and will need to look into that.

I would also like to apologize; I have remembered and forgotten to write a `terraform-bundle` specific Changelog more times then I want to admit, and I will assign myself this issue in part to make sure I do exactly that!

**Comment by mildwonkey** [comment] 2020-08-19 12:58
@Gaveno: I am going to close this issue since terraform-bundle is working as designed with the proper version of terraform. If you have more questions about the changes, the [community forum](https://discuss.hashicorp.com/c/terraform-core/27) is your best place to ask. If you identify a bug with terraform-bundle (or terraform), you can open a new issue using the "bug" template and filling out all the requested information. Thanks!

**Closed by mildwonkey** 2020-08-19 12:58 UTC
Labels: documentation, explained, v0.13
