### ISSUE TITLE
'terraform import' does not evaluate variables and fails on complex setups

### ISSUE THREAD

**Issue by schuettecarsten** [hashicorp/terraform#24985] opened 2020-05-18 19:31 UTC
### Terraform Version

```
Terraform v0.12.25
+ provider.azurerm v2.9.0
```

### Expected Behavior

When I run `terraform apply`, I get the following output. Unfortunately, these two resources already exist. and I need to import them. But import fails as shown below, showing some errors that variables could not be evaluated.

```
Terraform will perform the following actions:

  # module.p1-abc.module.vm01.azurerm_virtual_machine_data_disk_attachment.data_disk[0] will be created
  + resource "azurerm_virtual_machine_data_disk_attachment" "data_disk" {
      + caching                   = "ReadOnly"
      + create_option             = "Attach"
      + id                        = (known after apply)
      + lun                       = 0
      + managed_disk_id           = "/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/disks/abcp1vm01_DataDisk_0"
      + virtual_machine_id        = "/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/virtualMachines/abcp1vm01"
      + write_accelerator_enabled = false
    }

  # module.p1-abc.module.vm01.azurerm_virtual_machine_data_disk_attachment.data_disk[1] will be created
  + resource "azurerm_virtual_machine_data_disk_attachment" "data_disk" {
      + caching                   = "ReadOnly"
      + create_option             = "Attach"
      + id                        = (known after apply)
      + lun                       = 1
      + managed_disk_id           = "/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/disks/abcp1vm01_DataDisk_1"
      + virtual_machine_id        = "/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/virtualMachines/abcp1vm01"
      + write_accelerator_enabled = false
    }
```

And then, on apply:

```
Error: A resource with the ID "/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/virtualMachines/abcp1vm01/dataDisks/abcp1vm01_DataDisk_0" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_machine_data_disk_attachment" for more information.

  on ..\sharedmodules\vm_windows\vm-datadisks.tf line 1, in resource "azurerm_virtual_machine_data_disk_attachment" "data_disk":
   1: resource "azurerm_virtual_machine_data_disk_attachment" "data_disk" {



Error: A resource with the ID "/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/virtualMachines/abcp1vm01/dataDisks/abcp1vm01_DataDisk_1" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_machine_data_disk_attachment" for more information.

  on ..\sharedmodules\vm_windows\vm-datadisks.tf line 1, in resource "azurerm_virtual_machine_data_disk_attachment" "data_disk":
   1: resource "azurerm_virtual_machine_data_disk_attachment" "data_disk" {
```

When I try to import these resources, I use the following command:

```
terraform import module.p1-abc.module.vm01.azurerm_virtual_machine_data_disk_attachment.data_disk[0] /subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/virtualMachines/abcp1vm01/dataDisks/abcp1vm01_DataDisk_0
```

And I get the output/error:

```
module.p1-abc.module.vm01.azurerm_virtual_machine_data_disk_attachment.data_disk[0]: Importing from ID "/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/virtualMachines/abcp1vm01/dataDisks/abcp1vm01_DataDisk_0"...
module.p1-abc.module.vm01.azurerm_virtual_machine_data_disk_attachment.data_disk[0]: Import prepared!
  Prepared azurerm_virtual_machine_data_disk_attachment for import
module.p1-abc.module.vm01.azurerm_virtual_machine_data_disk_attachment.data_disk[0]: Refreshing state... [id=/subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.Compute/virtualMachines/abcp1vm01/dataDisks/abcp1vm01_DataDisk_0]

Error: Missing map element

  on ..\sharedmodules\resource_groups\locals.tf line 2, in locals:
   2:   location     = var.location != "" ? var.location : var.environment.location
    |----------------
    | var.environment is empty map of dynamic

This map does not have an element with the key "location".


Error: Missing map element

  on ..\sharedmodules\resource_groups\locals.tf line 3, in locals:
   3:   project_name = var.project_name != "" ? var.project_name : var.environment.project_name
    |----------------
    | var.environment is empty map of dynamic

This map does not have an element with the key "project_name".
```

I am wondering why terraform is able to apply/plan the setup, but cannot import a resource?
Please note that the subscription ID was replaced with <REMOVED> here.

**Comment by danieldreier** [comment] 2020-05-18 20:37
Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. The errors you're showing suggest a misconfiguration, but it's hard for me to say that confidently because I haven't actually seen the code you're trying to run.

It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug, please help by providing more details about an environment I can set up locally to reproduce this failure more. If you can, I may be able get it on our backlog.

Based on my work so far, I recommend you take this to the community forum for assistance in troubleshooting. I'm going to close this for now, because I think the community forum is the right approach. If you're really confident this is a bug, feel free to contact me at ddreier@hashicorp.com to re-open this and we can work up a reproduction case.

**Closed by danieldreier** 2020-05-18 20:37 UTC

**Comment by schuettecarsten** [comment] 2020-05-19 06:55
I will contact you directly with an reproduceable case. Because this requires access to a running Azure subscription, I cannot post the details here.

**Comment by martinverner** [comment] 2020-05-27 08:00
I have the exact same issue. Running a plan is fine and Terraform wish to create already created resources. When I try to import the resource I get the "...is empty map of dynamic" error. The map, or value, is not empty.
Did you guys figure out the issue?

**Comment by martinverner** [comment] 2020-05-27 08:02
It could be related to the count on the resource ("[0]"). We have that too on the failing import.

**Comment by martinverner** [comment] 2020-05-27 08:29
I am now fairly sure this is a bug in Terraform.
If I hardcode a value to the "...is empty map of dynamic" instead of reading the value from the .auto.tfvars file import works as well. The plan worked all the time, but import do not. Something is wrong.
