### ISSUE TITLE
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by dtherhtun** [hashicorp/terraform#28675] opened 2021-05-11 15:19 UTC
### Terraform Version

```
0.15.2
```

### Terraform Configuration Files

```terraform
resource "vault_mount" "es" {
  path = "database"
  type = "database"
}

resource "vault_database_secret_backend_connection" "es" {
  allowed_roles     = var.es.allowed_roles
  backend           = vault_mount.es.path
  name              = "elasticdb"
  verify_connection = false

  elasticsearch {
    password = var.es.password
    url      = var.es.url
    username = var.es.username
  }
}

resource "vault_database_secret_backend_role" "es" {
  backend             = vault_mount.es.path
  name                = "elasticsearch-role"
  db_name             = vault_database_secret_backend_connection.es.name
  creation_statements = var.es.creation_statements
}

variable "es" {
  description = "Group of elasticsearch variables"
  type = object({
    url                 = string
    username            = string
    password            = string
    allowed_roles       = list(string)
    creation_statements = list(string)
  })
}

es = {
  url                 = "http://localhost:9200/"
  username            = "elastic"
  password            = "1234"
  allowed_roles       = ["dev", "prod"]
  creation_statements = ["CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';"]
}
```

### Crash Output

```
Terraform v0.15.2
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
vault_auth_backend.aws: Refreshing state... [id=aws]
vault_mount.ssh: Refreshing state... [id=ssh]
vault_mount.es: Refreshing state... [id=elasticsearch]
vault_github_auth_backend.github: Refreshing state... [id=github]
vault_jwt_auth_backend.oidc: Refreshing state... [id=oidc]
vault_aws_auth_backend_role.aws: Refreshing state... [id=auth/aws/role/test-role]
vault_ssh_secret_backend_role.otp: Refreshing state... [id=ssh/roles/otp]
vault_policy.ssh_client_access: Refreshing state... [id=ssh_clients]
vault_github_user.github["dtherhtun"]: Refreshing state... [id=auth/github/map/users/dtherhtun]
vault_jwt_auth_backend_role.oidc["oidc_admin"]: Refreshing state... [id=auth/oidc/role/oidc_admin]
vault_jwt_auth_backend_role.oidc["oidc_devs"]: Refreshing state... [id=auth/oidc/role/oidc_devs]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # vault_database_secret_backend_connection.es will be created
  + resource "vault_database_secret_backend_connection" "es" {
      + allowed_roles     = [
          + "dev",
          + "prod",
        ]
      + backend           = "database"
      + id                = (known after apply)
      + name              = "elasticdb"
      + verify_connection = false

      + elasticsearch {
          + password = (sensitive value)
          + url      = "http://localhost:9200/"
          + username = "elastic"
        }
    }

  # vault_database_secret_backend_role.es will be created
  + resource "vault_database_secret_backend_role" "es" {
      + backend             = "database"
      + creation_statements = [
          + "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';",
        ]
      + db_name             = "elasticdb"
      + id                  = (known after apply)
      + name                = "elasticsearch-role"
    }

  # vault_mount.es will be updated in-place
  ~ resource "vault_mount" "es" {
        id                        = "elasticsearch"
      ~ path                      = "elasticsearch" -> "database"
        # (8 unchanged attributes hidden)
    }

  # vault_ssh_secret_backend_role.otp will be updated in-place
  ~ resource "vault_ssh_secret_backend_role" "otp" {
      + allowed_extensions       = "permit-pty,permit-port-forwarding"
        id                       = "ssh/roles/otp"
        name                     = "otp"
      + ttl                      = "30m"
        # (14 unchanged attributes hidden)
    }

Plan: 2 to add, 2 to change, 0 to destroy.
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 2)
Output: panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.GetAttr(0x2c6b4b0, 0xc000a9e360, 0x0, 0x0, 0xc0006da540, 0xd, 0x0, 0x1, 0x203000, 0x203000)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.3/cty/value_ops.go:760 +0x416
github.com/hashicorp/terraform/configs/configschema.(*Block).ValueMarks(0xc0004246f0, 0x2c6b4b0, 0xc000a9e360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0, ...)
	/home/circleci/project/project/configs/configschema/marks.go:33 +0x545
github.com/hashicorp/terraform/command/jsonplan.(*plan).marshalResourceChanges(0xc000480b40, 0xc000e91e30, 0xc0008da840, 0x0, 0x0)
	/home/circleci/project/project/command/jsonplan/plan.go:218 +0x1825
github.com/hashicorp/terraform/command/jsonplan.Marshal(0xc0008e7860, 0xc000749290, 0xc000ebcc00, 0xc0008da840, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/command/jsonplan/plan.go:124 +0x23f
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc00044a000, 0xc00004c0b0, 0x1, 0x2, 0xc000426170)
	/home/circleci/project/project/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc00042c280, 0xc000424000, 0x27e9055, 0x4)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x554
main.main()
	/home/circleci/project/project/main.go:58 +0x25




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.042135583.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.042135583.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
### Additional Context

I already tested on my laptop with a local vault server. it is ok. It is only happening in terraform cloud.

**Comment by jbardin** [comment] 2021-05-11 15:30
Duplicate of #28631
Please upgrade to Terraform v0.15.3

Thanks!

**Closed by jbardin** 2021-05-11 15:30 UTC
Labels: bug, new

**Comment by dtherhtun** [comment] 2021-05-11 16:41
Thanks!
