### ISSUE TITLE
v1.10.0 panic with templatefile on terraform validate

### ISSUE THREAD

**Issue by akettmann-id** [hashicorp/terraform#36147] opened 2024-12-02 17:44 UTC
### Terraform Version

```shell
$ terraform version
Terraform v1.10.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.6.0
```

### Terraform Configuration Files

```terraform
# Generates a ZIP file from a local JavaScript file
data "archive_file" "lambda_zip" {
  type = "zip"
  source {
    content  = templatefile("${path.module}/scripts/auth_handler.py", var.basic_auth_creds)
    filename = "auth_handler.py"
  }
  output_path = "${path.module}/lambda_function.zip"
}
variable "basic_auth_creds" {
  type = object({
    username = string
    password = string
  })
  default = {
    username = "secretname"
    password = "idproject"
  }
}
```

### Debug Output

Note, this is running `terraform validate` not terraform plan or apply.

https://gist.github.com/akettmann-id/73c5aa6a0a144eaa06fdf8352b090822

### Expected Behavior

Validation completes successfully. 

### Actual Behavior

Panic error

```
$ terraform validate
╷
│ Error: Error in function call
│ 
│   on modules/https_lb/password_protection_lambda.tf line 5, in data "archive_file" "lambda_zip":
│    5:     content  = templatefile("${path.module}/scripts/auth_handler.py", var.basic_auth_creds)
│     ├────────────────
│     │ while calling templatefile(path, vars)
│     │ path.module is "modules/https_lb"
│     │ var.basic_auth_creds is a object
│ 
│ Call to function "templatefile" failed: panic in function implementation: can't use ElementIterator on unknown value
│ goroutine 266 [running]:
│ runtime/debug.Stack()
│       runtime/debug/stack.go:26 +0x5e
│ github.com/zclconf/go-cty/cty/function.errorForPanic(...)
│       github.com/zclconf/go-cty@v1.15.1-0.20241111215639-63279be090d7/cty/function/error.go:44
│ github.com/zclconf/go-cty/cty/function.Function.Call.func2()
│       github.com/zclconf/go-cty@v1.15.1-0.20241111215639-63279be090d7/cty/function/function.go:349 +0x9b
│ panic({0x3050be0?, 0x3ddadb0?})
│       runtime/panic.go:785 +0x132
│ github.com/zclconf/go-cty/cty.Value.ElementIterator({{{0x3e20e90?, 0xc000a2dba0?}}, {0x315d760?, 0x5a112e0?}})
│       github.com/zclconf/go-cty@v1.15.1-0.20241111215639-63279be090d7/cty/value_ops.go:1193 +0xd1
│ github.com/zclconf/go-cty/cty.Value.AsValueMap({{{0x3e20e90?, 0xc000a2dba0?}}, {0x315d760?, 0x5a112e0?}})
│       github.com/zclconf/go-cty@v1.15.1-0.20241111215639-63279be090d7/cty/value_ops.go:1455 +0x99
│ github.com/hashicorp/terraform/internal/lang/funcs.MakeTemplateFileFunc.makeRenderTemplateFunc.func4({0x3e21108, 0xc00089b9e0}, {{{0x3e20e90?,
│ 0xc000a2dba0?}}, {0x315d760?, 0x5a112e0?}})
│       github.com/hashicorp/terraform/internal/lang/funcs/string.go:322 +0xea
│ github.com/hashicorp/terraform/internal/lang/funcs.MakeTemplateFileFunc.func3({0xc004625f00?, 0xc000a2dba0?, 0x315d760?}, {{0x3e21598?,
│ 0x5a43160?}})
│       github.com/hashicorp/terraform/internal/lang/funcs/filesystem.go:148 +0x245
│ github.com/zclconf/go-cty/cty/function.Function.Call({0x3e20e90?}, {0xc004625f00, 0x2, 0x2})
│       github.com/zclconf/go-cty@v1.15.1-0.20241111215639-63279be090d7/cty/function/function.go:353 +0x6bf
│ github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc00039f3b0, 0xc004107b90)
│       github.com/hashicorp/hcl/v2@v2.23.0/hclsyntax/expression.go:528 +0x1acf
│ github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc000add0b0, 0xc000add080?, {0xc0056f48f8?, 0x60?, 0x28?}, 0xc004107b90)
│       github.com/hashicorp/hcl/v2@v2.23.0/hcldec/spec.go:220 +0x1fc
│ github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc000add080, 0xc0029ae600, {0x5a43160, 0x0, 0x0}, 0xc004107b90)
│       github.com/hashicorp/hcl/v2@v2.23.0/hcldec/spec.go:94 +0x1f8
│ github.com/hashicorp/hcl/v2/hcldec.decode({0x3e22ad0, 0xc004122a40}, {0x5a43160, 0x0, 0x0}, 0xc004107b90, {0x3e21618, 0xc000add080}, 0x0)
│       github.com/hashicorp/hcl/v2@v2.23.0/hcldec/decode.go:24 +0x10f
│ github.com/hashicorp/hcl/v2/hcldec.(*BlockSetSpec).decode(0xc0031f31d0, 0xc0029ae4e0, {0xc000deb9e0?, 0xd?, 0x28?}, 0xc004107b90)
│       github.com/hashicorp/hcl/v2@v2.23.0/hcldec/spec.go:767 +0x1ff
│ github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc0031f2e40, 0xc0029ae4e0, {0x0, 0x0, 0x0}, 0xc004107b90)
│       github.com/hashicorp/hcl/v2@v2.23.0/hcldec/spec.go:94 +0x1f8
│ github.com/hashicorp/hcl/v2/hcldec.decode({0x3e22ad0, 0xc0041229e0}, {0x0, 0x0, 0x0}, 0xc004107b90, {0x3e21618, 0xc0031f2e40}, 0x0)
│       github.com/hashicorp/hcl/v2@v2.23.0/hcldec/decode.go:24 +0x10f
│ github.com/hashicorp/hcl/v2/hcldec.Decode(...)
│       github.com/hashicorp/hcl/v2@v2.23.0/hcldec/public.go:18
│ github.com/hashicorp/terraform/internal/lang.(*Scope).EvalBlock(0xc000b82090, {0x3e21060, 0xc004a1f720}, 0xc000adc8a0)
│       github.com/hashicorp/terraform/internal/lang/eval.go:75 +0x207
│ github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc000c67f20?, {0x3e21390, 0xc000a3cb00}, 0xc000adc8a0,
│ {0x0?, 0x0?}, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...})
│       github.com/hashicorp/terraform/internal/terraform/eval_context_builtin.go:324 +0x145
│ github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).validateResource(0xc000f1e250, {0x3e48bb8, 0xc0048b4200})
│       github.com/hashicorp/terraform/internal/terraform/node_resource_validate.go:425 +0xf06
│ github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).Execute(0xc000f1e250, {0x3e48bb8, 0xc0048b4200}, 0x50?)
│       github.com/hashicorp/terraform/internal/terraform/node_resource_validate.go:56 +0xb8
│ github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc00090a420, {0x3e48bb8, 0xc0048b4200}, {0x7b50827ae090,
│ 0xc000f1e250})
│       github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:161 +0xb5
│ github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x36b4c40, 0xc000f1e250})
│       github.com/hashicorp/terraform/internal/terraform/graph.go:143 +0x7c3
│ github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0007a8f60, {0x36b4c40, 0xc000f1e250}, 0xc0005e1ac0)
│       github.com/hashicorp/terraform/internal/dag/walk.go:384 +0x2d1
│ created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 1
│       github.com/hashicorp/terraform/internal/dag/walk.go:307 +0xfb3
│ .
╵
```

### Steps to Reproduce

1. create main.tf in empty directory
2. create `scripts` directory
3. create file named `auth_handler.py` inside of the `scripts` directory, content unnecessary 
4. `terraform validate`

### Additional Context

Validates properly on terraform 1.9.8-1 or:

```
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.6.0

Your version of Terraform is out of date! The latest version
is 1.10.0. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by jbardin** [comment] 2024-12-02 18:33
Duplicate of #36110

**Closed by jbardin** 2024-12-02 18:33 UTC
Labels: bug, new
