### ISSUE TITLE
Applying non-empty plan file results in no changes made

### ISSUE THREAD

**Issue by Indigenuity** [hashicorp/terraform#24111] opened 2020-02-13 23:11 UTC
### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.41.0
+ provider.cloudflare v2.1.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
resource "null_resource" "targeted_redis_migration_resource" {
  depends_on = [
    aws_route53_record.redis,
//    <... other resources with no changes >
  ]
}

data "aws_instance" "redis" {
  instance_id = "i-somebogusid"
}

resource "aws_route53_record" "redis" {
  zone_id         = aws_route53_zone.some_zone.id
  name            = "redis"
  type            = "CNAME"
  ttl             = var.route53_record_ttl
  records         = [data.aws_instance.redis.private_dns]
  allow_overwrite = true
}
```

### Debug Output
Apologies, I was on tight deadline to update a live environment and was unable to reproduce with debug logs

### Expected Behavior
```
$ terraform plan -out planned -target=null_resource.targeted_redis_migration_resource
...
Plan: 0 to add, 1 to change, 0 to destroy.

$ terraform apply "planned"
...
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
### Actual Behavior
```
$ terraform plan -out planned -target=null_resource.targeted_redis_migration_resource
...
Plan: 0 to add, 1 to change, 0 to destroy.

$ terraform apply "planned"
...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

$ terraform apply -target=null_resource.targeted_redis_migration_resource
...
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Additional Context
The exact scenario I encountered was described much better by someone in a past ticket: https://github.com/hashicorp/terraform/issues/20567 .  Like in that case, I was able to successfully apply changes by skipping the `plan -out` step and going straight to `apply`, typing "yes" when prompted.

In that case, there was an odd interaction with `count`.  I was not using `count` at all, so that can't be the culprit here.

**Comment by Indigenuity** [comment] 2020-02-18 20:14
An additional wrinkle here: I encountered this issue once again during another migration in a production environment.  This time was a bit different.  Both workflows of `plan -> apply` and just straight `apply` failed to actually enact any changes.  It wasn't until I switched the target of the apply to individual resources that it did anything.  I.e. this didn't work:
```
$ terraform apply -target=null_resource.targeted_redis_migration_resource
...
Plan: 0 to add, 1 to change, 0 to destroy.
...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
But this did work:
```
terraform apply -target=aws_route53_record.redis
...
Plan: 0 to add, 1 to change, 0 to destroy.
...
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

I realize that both the `target` flag and the use of `null_resource` as an organizational unit are not terraform best practices.  But this behavior isn't just inconvenient; it's plain incorrect.  

I'm happy to try further to reproduce this behavior in a non-production environment if it would be useful, but so far I've been unsuccessful in doing so.  It feels fairly non-deterministic.

**Comment by Indigenuity** [comment] 2020-02-21 18:49
I'm completely unfamiliar with the terraform codebase, but if someone could give me a few tips on where to start looking for hunting down this bug, I'd love to give it a try.  Just seems like the core contributors are a bit too swamped to get to things like this

**Comment by apparentlymart** [comment] 2020-06-19 02:21
Hi @Indigenuity! Thanks for reporting this, and sorry for the slow response.

I understand that you've attempted to reproduce this outside of your production environment, and weren't able to. Unfortunately that means we won't be able to reproduce it either, and so sadly we won't be able to investigate this issue further unless someone is able to offer a reproduction case that doesn't depend on any remote cloud services. However, I will leave the issue open for now in case you or someone else _is_ able to replicate it in a reproducible way.

One situation where this could arise legitimately is when a plan includes a change from a known value to a "known after apply" value, but then at apply time the new value turns out to be the same as the old value after all. Terraform's plan gives you the _conservative_ count of the number of resource instances that _might_ change, but when more information is learned at apply time Terraform can find that a change is not actually necessary after all.

However, it doesn't seem like that's what's going on in your case because you saw it produce a real change when you ran `terraform apply` directly, rather than applying a saved plan file. I'm not sure what would cause a difference of this sort between those two usage patterns, and so I don't know where further to investigate without having a working example to debug with.

Thanks again for reporting this, and sorry we can't take any action based on it right now.

**Comment by mildwonkey** [comment] 2021-04-30 16:10
I'm going to close this, since we weren't able to get a reproduction, but if you are still experiencing a reproducible problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by mildwonkey** 2021-04-30 16:10 UTC
Labels: bug, core, v0.12, waiting for reproduction
