### ISSUE TITLE
Terraform 1.0.1 crashes

### ISSUE THREAD

**Issue by evilr00t** [hashicorp/terraform#29045] opened 2021-06-28 10:29 UTC
Terraform 1.0.1 crashes, on 1.0.0 problem does not appear. Same code etc.

I'm using Terraform Cloud so it's impossible(?) to get crash log. 

What other details would be beneficial? I've run `TF_LOG=debug` but does not seem to give more output.

```
Failed running command "cd '/terraform/01_computing' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 2)
Output: panic: value is marked, so must be unmarked first

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2cbab70, 0xc0025be3e0, 0x25536a0, 0xc00259ae88, 0x2cbab01)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1050 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc0025be8f0, 0x1, 0x1, 0x2cbab70, 0xc0025be3e0, 0x25536a0, 0xc00259ae88, 0x2c84028, 0xc00259b170, 0xc00259ae88, ...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:144 +0x2e8
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x2cbab38, 0xc0025be430, 0x245fdc0, 0xc0025a97d0, 0x2c84028, 0xc00259b170, 0xc0025be880, ...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x2cbab38, 0xc0025be430, 0x245fdc0, 0xc0025a97d0, 0xc00216ef20, 0x1, 0x1, 0x2c1a2c0, 0x1, 0xc002417f40, ...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:236 +0xc5
github.com/hashicorp/terraform/internal/command/jsonstate.marshalResources(0xc0029a8810, 0xc001c0d280, 0x3, 0x4, 0xc001048e30, 0xc002464a40, 0x0, 0xc000073c00, 0x0, 0xc002bacde8)
        /home/circleci/project/project/internal/command/jsonstate/state.go:333 +0xe07
github.com/hashicorp/terraform/internal/command/jsonstate.marshalModules(0xc000cea0e0, 0xc001048e30, 0xc0013679e0, 0x1, 0x1, 0xc002bad1a8, 0xc0024dd500, 0x1, 0x1, 0x0, ...)
        /home/circleci/project/project/internal/command/jsonstate/state.go:254 +0x538
github.com/hashicorp/terraform/internal/command/jsonstate.marshalModules(0xc000cea0e0, 0xc001048e30, 0xc001443200, 0x12, 0x20, 0xc002bad1a8, 0x31, 0x42, 0x0, 0x0, ...)
        /home/circleci/project/project/internal/command/jsonstate/state.go:262 +0x48f
github.com/hashicorp/terraform/internal/command/jsonstate.marshalModules(0xc000cea0e0, 0xc001048e30, 0xc000b36ea0, 0x4, 0x4, 0xc002bad1a8, 0x0, 0x1, 0x0, 0x0, ...)
        /home/circleci/project/project/internal/command/jsonstate/state.go:262 +0x48f
github.com/hashicorp/terraform/internal/command/jsonstate.marshalRootModule(0xc000cea0e0, 0xc001048e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/circleci/project/project/internal/command/jsonstate/state.go:234 +0x8c9
github.com/hashicorp/terraform/internal/command/jsonstate.(*state).marshalStateValues(0xc002012c60, 0xc000cea0e0, 0xc001048e30, 0x0, 0x5)
        /home/circleci/project/project/internal/command/jsonstate/state.go:166 +0x14a
github.com/hashicorp/terraform/internal/command/jsonstate.Marshal(0xc00063ee10, 0xc001048e30, 0x0, 0x0, 0x0, 0x0, 0x219f5b5)
        /home/circleci/project/project/internal/command/jsonstate/state.go:146 +0xf8
github.com/hashicorp/terraform/internal/command/jsonplan.Marshal(0xc00060c4e0, 0xc000c86dc0, 0xc00063ee10, 0xc001048e30, 0x0, 0x0, 0xc00127ed80, 0x4, 0x4)
        /home/circleci/project/project/internal/command/jsonplan/plan.go:152 +0x633
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0xc00015a000, 0xc00004c0b0, 0x1, 0x2, 0xc00013a170)
        /home/circleci/project/project/internal/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc000140280, 0xc000138000, 0x282e5dd, 0x4)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
        /home/circleci/project/project/main.go:115 +0x554
main.main()
        /home/circleci/project/project/main.go:58 +0x25




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.395804936.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.395804936.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by blakemorgan** [comment] 2021-06-28 14:03
Possible duplicate of #29042?

**Comment by mildwonkey** [comment] 2021-06-28 15:20
Hi @blakemorgan ! Since the stack traces in both panics are the same, I will indeed close this as a duplicate of #29042. Thanks!

**Closed by mildwonkey** 2021-06-28 15:20 UTC
Labels: bug, new
