### ISSUE TITLE
`terraform show -json` does not properly escape newline (`\n`) characters

### ISSUE THREAD

**Issue by ghostsquad** [hashicorp/terraform#25986] opened 2020-08-25 06:44 UTC
When using a data resource that outputs json, such as `data.aws_iam_policy_document`. The embedded json contains newline `\n` characters, which are kept when running `terraform show` without being escaped. The resulting output is not valid json.

### Terraform Version
```
0.13.0
```

### Expected Behavior

`terraform show -json` produces valid json, even if there is nested json.

### Actual Behavior

I must run `terraform show -json | tr '\n' '\\n'` in order to get a valid result.

**Comment by alisdair** [comment] 2020-08-25 12:45
Thanks for reporting this! I'm not able to reproduce the problem locally. Here's my attempt at a reduced reproduction:

main.tf:
```hcl
output "json-with-newlines" {
  value = <<EOF
{
  "this": "is a JSON document",
  "it": "has some newlines"
}
EOF
}
```

- `terraform init && terraform apply`
- `terraform show -json`

The output is:

```json
{"format_version":"0.1","terraform_version":"0.13.1","values":{"outputs":{"json-with-newlines":{"sensitive":false,"value":"{\n  \"this\": \"is a JSON document\",\n  \"it\": \"has some newlines\"\n}\n"}},"root_module":{}}}
```

Formatted with `jq`:

```json
{
  "format_version": "0.1",
  "terraform_version": "0.13.1",
  "values": {
    "outputs": {
      "json-with-newlines": {
        "sensitive": false,
        "value": "{\n  \"this\": \"is a JSON document\",\n  \"it\": \"has some newlines\"\n}\n"
      }
    },
    "root_module": {}
  }
}
```

As you can see, it appears to be valid.

Can you help us reproduce this by submitting a minimal configuration which demonstrates the problem? Ideally, please restrict yourself to using the simple providers like `null` or `file`.

**Comment by ghostsquad** [comment] 2020-09-12 03:40
I'll get to this over the weekend. thanks for your patience, please don't close this. For reference, I'm actually using `.tf.json` files, which might be the cause here..

**Comment by ghostsquad** [comment] 2020-12-15 04:13
This appears to be exclusive to the `aws_iam_policy_document` resource. I can't reproduce it elsewhere.

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/903488/102169759-c560fd00-3e47-11eb-95bb-b3a1ea6db731.png">

I can't seem to produce a minimal example of this either.

**Comment by ghostsquad** [comment] 2020-12-15 04:14
this is the output from

```
terraform plan -out=tfplan
terraform show -json ./tfplan
```

**Comment by ghostsquad** [comment] 2020-12-15 04:23
the specific policy isn't even written by me, it's here:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L43

**Comment by ghostsquad** [comment] 2020-12-15 04:31
this happens it seems also with some template files.

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/903488/102171278-09a1cc80-3e4b-11eb-8e49-b8ab972475ac.png">

**Comment by alisdair** [comment] 2020-12-15 14:38
Thanks for the additional information! Unfortunately without a full configuration which reproduces the issue, I don't think we'll be able to figure out what's happening here. Can you provide a small reproduction case for either of the two instances you found?

**Comment by ghostsquad** [comment] 2020-12-15 16:56
I will pair down the existing code and post it.

**Comment by mildwonkey** [comment] 2021-04-30 16:12
I'm going to close this, since we weren't able to get a reproduction, but if you are still experiencing this problem please open a new issue with the reproduction, or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by mildwonkey** 2021-04-30 16:12 UTC
Labels: bug, v0.13, waiting for reproduction
