### ISSUE TITLE
Issue importing an aws_appautoscaling_policy for a DynamoDB Table

### ISSUE THREAD

**Issue by scampuza** [hashicorp/terraform#21152] opened 2019-04-29 23:50 UTC
Hi there,

I´m using Terraform v0.11.11 with the AWS Provider to import some existing resources into the Terraform state.

Trying to import some existing DynamoDB aws_appautoscaling_policy policies, I´m getting the following errors:

terraform import aws_appautoscaling_policy.dynamodb_table_read_policy dynamodb/table/visitors/dynamodb:table:ReadCapacityUnits/DynamoDBReadCapacityUtilization:table/visitors

Error: aws_appautoscaling_policy.dynamodb_table_read_policy (import id: dynamodb/table\/visitors/dynamodb:table:ReadCapacityUnits/DynamoDBReadCapacityUtilization:table\/visitors): 1 error(s) occurred:

* import aws_appautoscaling_policy.dynamodb_table_read_policy result: visitors: aws_appautoscaling_policy.dynamodb_table_read_policy: Failed to read scaling policy: Error retrieving scaling policies: ValidationException: 1 validation error detected: Value 'DynamoDBReadCapacityUtilization:table\' at 'scalableDimension' failed to satisfy constraint: Member must satisfy enum value set: [dynamodb:table:ReadCapacityUnits, dynamodb:index:ReadCapacityUnits, rds:cluster:ReadReplicaCount, elasticmapreduce:instancefleet:SpotCapacity, appstream:fleet:DesiredCapacity, dynamodb:index:WriteCapacityUnits, elasticmapreduce:instancefleet:OnDemandCapacity, rds:cluster:Capacity, dynamodb:table:WriteCapacityUnits, custom-resource:ResourceType:Property, sagemaker:variant:DesiredInstanceCount, ec2:spot-fleet-request:TargetCapacity, elasticmapreduce:instancegroup:InstanceCount, ecs:service:DesiredCount]
	status code: 400, request id: 3ffdf95e-6ad8-11e9-ae6d-234730bc25aa

According to the Terraform official documentation

https://www.terraform.io/docs/providers/aws/r/appautoscaling_policy.html

The right way for importing this kind of resources is as follows:

Application AutoScaling Policy can be imported using the service-namespace , resource-id, scalable-dimension and policy-name separated by /.

$ terraform import aws_appautoscaling_policy.test-policy service-namespace/resource-id/scalable-dimension/policy-name

But seems like I´m having issues because in my particular case, I have some / in some of the parameters:

"name": "DynamoDBReadCapacityUtilization:table/visitors",
"resource_id": "table/visitors"

I´ve tried even Escaping those forward slashes and using double and single quotes for the parameters, with the same result.

I would really appreciate some help with this issue.

Thanks a lot !

**Comment by zarnovican** [comment] 2019-05-30 12:08
This issue is IMHO a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/8306.

**Closed** 2019-05-31 17:20 UTC
Labels: provider/aws
