### ISSUE TITLE
Data sources incorrectly inherit the dependencies from the module

### ISSUE THREAD

**Issue by nozaq** [hashicorp/terraform#30585] opened 2022-02-25 17:23 UTC
### Terraform Version

```
Terraform v1.1.6
on linux_amd64
```

### Terraform Configuration Files

[This repo](https://github.com/nozaq/expand-poc) contains the test project. The below diagram shows a brief structure of it.
![overview](https://raw.githubusercontent.com/nozaq/expand-poc/main/error/overview.png)

### Debug Output

[link](https://github.com/nozaq/expand-poc/blob/main/error/debug.log)

### Expected Behavior

`terraform plan` succeeds without any error.

### Actual Behavior

The following error returned.

```
│ Error: Invalid for_each argument
│
│   on modules/foo/main.tf line 5, in data "null_data_source" "bar":
│    5:   for_each = toset([data.null_data_source.foo.random])
│     ├────────────────
│     │ data.null_data_source.foo.random is a string, known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply only the resources that the for_each depends on.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

The direct cause of this error is that `module.a.data.null_data_source.foo` is not a known value when `for_each` expression is evaluated [here](https://github.com/hashicorp/terraform/blob/main/internal/terraform/eval_for_each.go#L95). This occurs because `data.null_data_source.foo` depends on `null_resource.this` in the parent module through `[root] module.a(expand)` node. [terraform graph output](https://github.com/nozaq/expand-poc/blob/main/error/graph.png) shows this dependency. I believe `data.null_data_source.foo` should have no dependencies in this case so that it can be read during the plan.

I also created [another test project](https://github.com/nozaq/expand-poc/tree/main/success) which is very similar to the project above, but passing `null_resource.this` to `module.a` as an input argument instead of defining `depends_on` meta-argument. 
In this project, `module.a.data.null_data_source.foo` does not depend on `null_resource.this`([terraform graph output](https://github.com/nozaq/expand-poc/blob/main/success/graph.png)) because `module.a` depends on `null_resource.this` through `[root] module.a.var.input(expand)` node and `data.null_data_source.foo` doesn't have an edge to it. `terraform plan` succeeds without any error in this project.

**Comment by crw** [comment] 2022-02-25 22:51
Thanks for the thorough report!

**Comment by apparentlymart** [comment] 2022-02-26 00:51
Hi @nozaq! Thanks for reporting this, and again thanks for being so thorough in describing it.

What you've shown here seems like the intended behavior to me, though: you've told Terraform that everything inside this module should wait until `null_resource.this` is ready, and in this case that includes `module.a.data.null_data_source.foo`.

With these placeholder resource types that don't really do anything it obviously doesn't really matter what order these things happen in, but if the data source were a real one that fetches information about `null_resource.this` then it would be incorrect for Terraform to evaluate it during the plan phase, because that object would not have been created yet.

An important tradeoff with using `depends_on` for an entire module is that you give Terraform very coarse information about the dependencies. The other example you shared shows one way to explain the required dependencies to Terraform more precisely, which then allowed it to work. Without that extra detail, Terraform is forced to generate a very pessimistic dependency graph in order to make sure to cover whatever objects inside the module the dependency is intended to product, even though you didn't tell Terraform which specific objects the dependency was intended for.

With all of that said then, I don't think we'll be able to change the behavior you reported, since it is an intended consequence of handling the dependency graph you described. If you are satisfied with the second approach you took, where you described the dependencies more precisely, then I would suggest using that approach. If that other approach can't actually solve your corresponding problem in your real infrastructure (as opposed to this contrived example case) then I'd love to hear a little more about the real case so that we might think about other ways to solve your problem, without breaking the guarantees that module-level `depends_on` is intended to provide.

Thanks!

**Comment by nozaq** [comment] 2022-02-26 01:36
@apparentlymart 
Thank you for detailed exaplation! It does make sense now given the `depends_on`'s guarantee level, which I didn't understand correctly.

It's quite possible to circumvent this limitation in my case, but let me describe my actual use-case just for clarifying more context.
Below data sources and resources were defined in `module.a` instead of `null_data_source` instances.

```hcl
data "aws_subnets" "default" {
  filter {
    name   = "default-for-az"
    values = [true]
  }
}

data "aws_subnet" "default" {
  for_each = toset(data.aws_subnets.default.ids)
  id       = each.value
}

resource "aws_default_subnet" "default" {
  for_each = data.aws_subnet.default

  availability_zone       = each.value.availability_zone
  map_public_ip_on_launch = false
  ...
}
```

It tried to find availability_zones in the provider region, then automatically harden all default subnets in each availability zone. The problem was `data.aws_subnet.default`'s `for_each` evauluation fails if the module call to `module.a` contains any `depeneds_on` for resources defined in the parent module.
Given the module's `depends_on` guarantee though, I guess the better way is to use the dependency inversion approach, i.e. moving `data.aws_subnets` and `data.aws_subnet` to the parent module then pass their results to `module.a` as input arguments.

Thanks again for you guys for quickly checking-in, it really helped!

**Comment by crw** [comment] 2022-03-02 20:31
Going to go ahead and close this issue since it seems there is no work to be done, or that can be done. Thanks again for the report!

**Closed by crw** 2022-03-02 20:31 UTC
Labels: bug
