### ISSUE TITLE
Terraform 0.12 crashes after adding providers

### ISSUE THREAD

**Issue by achinthagunasekara** [hashicorp/terraform#24290] opened 2020-03-05 02:52 UTC
I'm in the middle of upgrading from Terraform 0.11 to 0.12.

I have observed this issue in few environments now.  First I upgraded from Terraform 0.11 to 0.12.

```
terraform init
terraform 0.12upgrade
```

After the upgrade I tried running a plan

```
terraform plan
```

However ran into the following issue

```
Error: Provider configuration not present

To work with module.analytics-kafka-zookeeper.data.aws_route53_zone.selected
its original provider configuration at
module.analytics-kafka-zookeeper.provider.aws.main is required, but it has
been removed. This occurs when a provider configuration is removed while
objects created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.analytics-kafka-zookeeper.data.aws_route53_zone.selected, after which
you can remove the provider configuration again.


Error: Provider configuration not present

To work with module.solr-files-zookeeper.aws_route53_record.zookeeper its
original provider configuration at
module.solr-files-zookeeper.provider.aws.main is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.solr-files-zookeeper.aws_route53_record.zookeeper, after which you can
remove the provider configuration again.
```

After looking for a solution, I came across https://github.com/hashicorp/terraform/issues/21472

As per above issue, I made some changes to my Terraform files by,

* Adding a block that looks like the following to each problematic module

```
provider "aws" {
  alias = "aws.main
}
```

* And passing in the provider to to above modules using a block that looks like

```
module "baz" {
  source "./baz"
  key = "value"
  ...
  providers = {
    aws.main = "aws.main
  }
}
```

However when I run a plan now I get a Terraform crash message.

```
panic: inconsistent list element types (cty.List(cty.String) then cty.List(cty.DynamicPseudoType))

goroutine 2972 [running]:
github.com/zclconf/go-cty/cty.ListVal(0xc004840180, 0x2, 0x2, 0xc001c0aa80, 0xc006176660, 0x22e45e0, 0xc000858d70)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/value_init.go:166 +0x4bf
github.com/zclconf/go-cty/cty/convert.conversionTupleToList.func2(0x22e46e0, 0xc001c0a8a0, 0x1a14fe0, 0xc001c0a8c0, 0xc001911740, 0x1, 0x1, 0xc0029d6000, 0x10, 0x10, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion_collection.go:267 +0x54a
github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x22e46e0, 0xc001c0a8a0, 0x1a14fe0, 0xc001c0a8c0, 0x0, 0x0, 0x0, 0xc0074ebe30, 0xc001911730, 0x22e45e0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:46 +0x1ad
github.com/zclconf/go-cty/cty/convert.retConversion.func1(0x22e46e0, 0xc001c0a8a0, 0x1a14fe0, 0xc001c0a8c0, 0xc001911730, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:179 +0x6b
github.com/zclconf/go-cty/cty/convert.Convert(0x22e46e0, 0xc001c0a8a0, 0x1a14fe0, 0xc001c0a8c0, 0x22e45e0, 0xc0008492a0, 0x0, 0x22e46e0, 0xc001c0a8a0, 0x1a14fe0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/public.go:51 +0x1af
github.com/hashicorp/terraform/terraform.(*EvalModuleCallArgument).Eval(0xc004b88740, 0x2317d80, 0xc0034b81a0, 0x2, 0x2, 0xc0035be000, 0x53)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_variable.go:77 +0x160
github.com/hashicorp/terraform/terraform.EvalRaw(0x22a2180, 0xc004b88740, 0x2317d80, 0xc0034b81a0, 0x3e, 0x0, 0x0, 0x3e)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc004432f90, 0x2317d80, 0xc0034b81a0, 0x2, 0x2, 0xc003183b38, 0x42b8a1)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x22a21c0, 0xc004432f90, 0x2317d80, 0xc0034b81a0, 0x14, 0xbf90372adbe1de8e, 0xca70c97e, 0x3e)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0021a4020, 0x2317d80, 0xc0034b81a0, 0x2, 0x2, 0xecc5d5, 0x22a2860)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x22a2320, 0xc0021a4020, 0x2317d80, 0xc0034b81a0, 0x1ad02c0, 0x32f6465, 0x1a39aa0, 0xc001314c10)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x22a2320, 0xc0021a4020, 0x2317d80, 0xc0034b81a0, 0xc0021a4020, 0x22a2320, 0xc0021a4020, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1c86280, 0xc001b46300, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00183f000, 0x1c86280, 0xc001b46300, 0xc0013b4740)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by pselle** [comment] 2020-03-06 19:09
@achinthagunasekara 

The panic shouldn't happen, but to get you moving forward have you tried making your alias name without `aws`, and updating your provider block that you pass to the module to define the `aws` provider to point to it? Here's your example with that updated:

```
provider "aws" {
  alias = "main"
}

module "baz" {
  source "./baz"
  key = "value"
  ...
  providers = {
    aws = aws.main
  }
}
```

**Comment by achinthagunasekara** [comment] 2020-03-10 22:34
I got this going by passing in the providers as per https://github.com/hashicorp/terraform/issues/21472
🙇

**Comment by pselle** [comment] 2020-03-11 19:39
@achinthagunasekara Could you confirm if you're still seeing an issue/close this issue if it's not relevant anymore?

**Comment by achinthagunasekara** [comment] 2020-03-11 20:00
I can get around by passing in the providers and making sure not passing in a list of lists where it expect to have a list of stings.

However it should not panic if I pass in a list of lists and give me a proper error message. Only way I knew I was passing in the wrong data type was by going through the crash.log.

**Comment by danieldreier** [comment] 2020-05-13 20:31
@achinthagunasekara it looks to me like the `panic: inconsistent list element types` is still probably valid issue. If you're willing to provide a reproduction case I can try to get work planned for this; I've seen other similar issues reported and am wondering if they are related. Since I don't have the code you used to trigger this crash, it would be helpful if you could work up a simple reproduction case, ideally just using null_resource in order to isolate it from potential issues with providers and to make it easier to reproduce with fewer external test fixtures. Is that something you can help with?

**Comment by apparentlymart** [comment] 2020-07-08 22:47
Hi againm @achinthagunasekara!

We didn't hear back from you after @danieldreier's comment, and I share his expectation that this issue is describing the same root cause as #21588, which has now been fixed in the main branch in preparation for inclusion in the forthcoming Terraform v0.13.0 release. In Terraform v0.13.0 it will either succeed in the conversion were possible or produce a proper error message if the requested conversion (from tuple to list) is not possible.

Since we suspect this is the same issue, and because it sounds like you already found a solution to make your configuration work in spite of this crashing bug, I'm going to close this now. Thanks for reporting it, and for sharing updates when you learned more information.

**Closed by apparentlymart** 2020-07-08 22:47 UTC
Labels: bug, crash, v0.12, waiting-response
