### ISSUE TITLE
TF12 does not update .tfstate with trigger values from null_resource/local-exec provisioner

### ISSUE THREAD

**Issue by lvaylet** [hashicorp/terraform#23994] opened 2020-01-30 13:42 UTC
### Terraform Version

```
Terraform v0.12.19
+ provider.google v2.20.1
+ provider.google-beta v2.20.1
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Terraform Configuration Files

The following code allowed us to provision a public DNS zone in GCP with Terraform 0.11.14, with no warnings in the output:

```hcl
resource "null_resource" "update_dns_public_parent_zone" {
  count = "${var.dns_public_zone_enabled}"

  provisioner "local-exec" {
    command = "bash setup-public-dns.sh ${google_project.main.project_id} ${var.env} ${var.sia} create"
  }

  provisioner "local-exec" {
    when    = "destroy"
    command = "bash setup-public-dns.sh ${google_project.main.project_id} ${var.env} ${var.sia} destroy"
  }
}
```

Based on [this discussion](https://discuss.hashicorp.com/t/how-to-rewrite-null-resource-with-local-exec-provisioner-when-destroy-to-prepare-for-deprecation-after-0-12-8/4580), we decided to adjust it as follows during our migration to Terraform 12, in order to suppress a "dependency cycle" warning:

```hcl
resource "null_resource" "update_dns_public_parent_zone" {
  count = var.dns_public_zone_enabled ? 1 : 0

  triggers = {
    project_id = google_project.main.project_id
    env        = var.env
    sia        = var.sia
  }

  provisioner "local-exec" {
    command = "bash setup-public-dns.sh ${self.triggers.project_id} ${self.triggers.env} ${self.triggers.sia} create"
  }

  provisioner "local-exec" {
    when    = destroy
    command = "bash setup-public-dns.sh ${self.triggers.project_id} ${self.triggers.env} ${self.triggers.sia} destroy"
  }
}
```

### Expected Behavior

We expected Terraform 12 to catch up automatically and adjust the state to include the current values of the triggers, so that subsequent `terraform plan` or `terraform apply` operations run successfully.

### Actual Behavior

A `terraform plan` highlighted the need to replace (i.e. destroy/create) the current resource:

```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # null_resource.update_dns_public_parent_zone[0] must be replaced
-/+ resource "null_resource" "update_dns_public_parent_zone" {
      ~ id       = "4670899766326446933" -> (known after apply)
      + triggers = {
          + "env"        = "tra"
          + "project_id" = "irn-00000-tra-dd"
          + "sia"        = "tst"
        } # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------
```

That sounds appropriate, but then `terraform apply` failed with:

```
google_dns_managed_zone.dns_public[0]: Refreshing state... [id=tst-tra-gcp-renault-com]
null_resource.update_dns_public_parent_zone[0]: Refreshing state... [id=4670899766326446933]
null_resource.update_dns_public_parent_zone[0]: Destroying... [id=4670899766326446933]

Error: 3 problems:

- Attempt to get attribute from null value: This value is null, so it does not have any attributes.
- Attempt to get attribute from null value: This value is null, so it does not have any attributes.
- Attempt to get attribute from null value: This value is null, so it does not have any attributes.
```

Looking at the `.tfstate` file, the values of the triggers are indeed missing:

```hcl
"attributes": {
  "id": "2514821770887579416",
  "triggers": null
},
```

We had to edit the `.tfstate` file manually and add the values of the triggers, resulting in:

```hcl
"attributes": {
  "id": "5683210273853386785",
  "triggers": {
    "env": "tra",
    "project_id": "irn-00000-tra-c3",
    "sia": "test"
  }
},
```

Then `terraform apply` (and any subsequent operation) works as expected.

### Steps to Reproduce

1. `tfenv use 0.11.14` on macOS to work with Terraform 0.11.14
1. `terraform init`
1. `terraform apply` with `var.dns_public_zone_enabled = true`to actually call the `null_resource` provisioner
1. `tfenv use 0.12.19` to switch to Terraform 0.12.19
1. `terraform init`
1. `terraform plan` to get the "resource replacement" plan above
1. `terraform apply` to fail with the "null value, no attributes" error above
1. edit the .tfstate file and add the values of the triggers
1. `terraform apply` to succeed (as expected initially)

### Additional Context

Is this workaround (editing the .tfstate) acceptable and official? Are there any other way to update the state with the values of the required triggers?

**Comment by jbardin** [comment] 2020-01-31 17:43
Hi @lvaylet,

Sorry about this somewhat confusing behavior. Destroy provisioners are a little strange, in that they live in the current _configuration_, but they are destroying something from the current _state_. This means that the `self` value the destroy provisioner is seeing can only be the value which is stored already in the state. Since the stored value did not have the `triggers` map, the destroy provisioner has no access to it. 

What you can do here is to apply the `null_resource` config as desired without the provisioners first, which will write the new values to the state, then add the provisioners to the configuration.

Since this is working as intended, I'm going to close it out. Further discussion and questions can be moved to the [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!

**Closed by jbardin** 2020-01-31 17:43 UTC
