### ISSUE TITLE
Terraform console crash

### ISSUE THREAD

**Issue by phosphre** [hashicorp/terraform#18173] opened 2018-06-01 20:24 UTC
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
In tf console this produced the crash:
> data.aws_vpc.glider.id

based on a module containing main.tf, data.tf, vars.tf and output.tf.

main.tf:
provider "aws" {
    version = "~> 1.21"
    region  = "${var.aws_region}"
}

terraform {
    backend "s3" {}
}

data.tf:
data "aws_vpc" "glider" {
    tags {
        name = "Name"
        value = "pi-vpc-${var.aws_region}"
    }
}

vars.tf:
variable "aws_region" {}

output.tf:
output "mon_vpc" {
    value = "${data.aws_vpc.glider.id}"
}

This module is checked into its own git repo.  I then use terragrunt to call this cfg.  In the environments repo, I have this:

terraform.tfvars:
terragrunt = {
    terraform {
        source = "git::ssh://git@bitbucket.org/phosphre/path.to.my.modules.git//consul"
    }

    include = {
        path = "${find_in_parent_folders()}"
    }
}

aws_region = "eu-west-1"
## end of terraform.tfvars file

and in the parent folder of the environment module (4 folders above):

terragrunt = {
    remote_state {
        backend = "s3"
        config {
            bucket         = "my.bucket"
            key            = "${path_relative_to_include()}/terraform.tfstate"
            region         = "eu-west-1"
            encrypt        = true
            dynamodb_table = "my.ddb.lock.table"
        }
    }

    terraform {
        # Force Terraform to keep trying to acquire a lock for
        # up to 20 minutes if someone else already has the lock
        extra_arguments "retry_lock" {
            commands  = ["${get_terraform_commands_that_need_locking()}"]
            arguments = ["-lock-timeout=20m"]
        }
    }
}

```

### Debug Output

https://gist.github.com/phosphre/ac1509cbc92470f0b6845d883f6e060b

### Crash Output

https://gist.github.com/phosphre/ac1509cbc92470f0b6845d883f6e060b

### Expected Behavior

I was either expecting terraform to interpolate the data source reference 

data.aws_vpc.glider.id

by using my configured aws account config and the local tf cfg and going to aws where the vpc exists, query the tag content and return the vpc ID, or provide a meaningful error, with most expected output being the latter given this was my first ever tf console experience.

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
...

### Steps to Reproduce

1. terraform console
2. tf prompt> data.aws_vpc.glider.id

### Additional Context

Terragrunt is in the mix.
When I run a terragrunt get, plan, apply I get no error, but I also note that the output I was expecting does not get output.  This is how I came to use the console.

**Comment by apparentlymart** [comment] 2018-10-31 18:28
Hi @phosphre! Sorry for this crash, and for the delayed response.

This seems to be the same root cause as for #16445, which has now been fixed. The fix will be included in the forthcoming v0.12.0 release of Terraform.

Thanks for reporting this, and sorry again for the delayed response.

**Closed by apparentlymart** 2018-10-31 18:28 UTC
Labels: config, crash
