### ISSUE TITLE
Crash doing route-53 commands in AWS

### ISSUE THREAD

**Issue by nateww** [hashicorp/terraform#17113] opened 2018-01-16 16:18 UTC
### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.7.0
```

### Terraform Configuration Files
```hcl
# Raw domain redirects to WWW
resource "aws_route53_record" "domain" {
  zone_id = "${aws_route53_zone.sofiqa-public.zone_id}"
  name    = "sofiqa.net"
  type    = "A"

  alias {
    name                   = "${data.terraform_remote_state.prod-env.dns_www-sofi-com_name}"
    zone_id                = "${data.terraform_remote_state.prod-env.dns_www-sofi-com_zone-id}"
    evaluate_target_health = false
  }
}
```

The above are new lines, but they are assentially a copy of the following lines in the same file, that worked fine.
```
# WWW
resource "aws_route53_record" "www" {
  zone_id = "${aws_route53_zone.sofiqa-public.zone_id}"
  name    = "www.sofiqa.net"
  type    = "A"

  alias {
    name                   = "${data.terraform_remote_state.prod-env.dns_www-sofi-com_name}"
    zone_id                = "${data.terraform_remote_state.prod-env.dns_www-sofi-com_zone-id}"
    evaluate_target_health = false
  }
}
```

### Crash Output
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.7.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.7"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.prod-env: Refreshing state...
aws_route53_zone.sofiqa-public: Refreshing state... (ID: Z307MDGZ9RTBVD)
panic: Unknown: <invalid reflect.Value>

goroutine 253 [running]:
github.com/hashicorp/terraform/builtin/providers/terraform.flatten(0xc4208f67e0, 0xc420262930, 0x7, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:48 +0x4ed
github.com/hashicorp/terraform/builtin/providers/terraform.remoteStateFlatten(0xc4205ab468, 0xc4205ab468)
        /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:21 +0x117
github.com/hashicorp/terraform/builtin/providers/terraform.dataSourceRemoteStateRead(0xc4207d8c40, 0x0, 0x0, 0xc4207d8c40, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/data_source_state.go:125 +0x832
github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc4207d8070, 0xc4201d69a0, 0x0, 0x0, 0xc42030e7d8, 0xc420483b01, 0xc420402870)
        /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:292 +0x8b
github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc4207d80e0, 0xc420528050, 0xc4201d69a0, 0x0, 0xc00, 0x44)
        /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x9a
github.com/hashicorp/terraform/terraform.(*EvalReadDataApply).Eval(0xc4201d6680, 0x4abfb00, 0xc42041d860, 0x2, 0x2, 0x3321d2c, 0x4)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_read_data.go:122 +0x100
github.com/hashicorp/terraform/terraform.EvalRaw(0x4aa2f40, 0xc4201d6680, 0x4abfb00, 0xc42041d860, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x173
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc4201d66a0, 0x4abfb00, 0xc42041d860, 0x2, 0x2, 0x3321d2c, 0x4)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x7e
github.com/hashicorp/terraform/terraform.EvalRaw(0x4aa3140, 0xc4201d66a0, 0x4abfb00, 0xc42041d860, 0x2d3aea0, 0x4ac1485, 0x2b234e0, 0xc4206d8a10)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x173
github.com/hashicorp/terraform/terraform.Eval(0x4aa3140, 0xc4201d66a0, 0x4abfb00, 0xc42041d860, 0xc4201d66a0, 0x4aa3140, 0xc4201d66a0, 0x1085d74)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x322ce20, 0xc4205fa608, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xd0d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc4207d82a0, 0x322ce20, 0xc4205fa608, 0xc420402b80)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x3c1
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x1364



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
```
https://gist.github.com/nateww/92e628e49197235da63b2791f96ae4f6

### Expected Behavior
It should have created a new Route53 record.

### Actual Behavior
crash

### Steps to Reproduce
1. `terraform init`
2. `terraform plan -out plan.tmp`

**Comment by jbardin** [comment] 2018-01-23 17:45
Hi @nateww,

Thanks for reporting this. The crash here appears to be coming from the `terraform_remote_state`, but I'm not sure how it's getting an invalid value.

Can you show the configuration for `data.terraform_remote_state.prod-env`, and if possible the `Outputs` stored in that remote state?

**Comment by jbardin** [comment] 2018-01-25 16:13
Coming back to this now, I see that the invalid state was immediately after a refresh, which means this is most likely a duplicate of #17152.

**Comment by saj** [comment] 2018-02-05 07:27
@jbardin I don't think this is a dupe of #17152.  We were seeing the same behaviour on 0.11.3 -- which included a patch for #17152.

The problem, in our case, ultimately boiled down to the shape of an (unused) output variable in a `terraform_remote_state` data source.

This is what we had:

```hcl
output "redacted" {
  value = "${formatlist("%s", aws_instance.redacted.*.private_ip)}"
}
```

The value should have been wrapped in a list:

```hcl
output "redacted" {
  value = ["${formatlist("%s", aws_instance.redacted.*.private_ip)}"]
}
```

(I do not know why someone put a `formatlist()` there.)

This is a bug, but I'm not sure how to phrase it in terms of Terraform nomenclature.  The program should recognise the type error and report the problematic variable name to the user.

**Comment by jbardin** [comment] 2018-02-05 15:07
Thanks @saj!

This does look like it's config related, especially since format list shouldn't be wrapped in square brackets. 

You're right that it's not related to that other issue, I must have had the wrong stack trace open in my editor when I wrote that.

**Comment by danieldreier** [comment] 2020-06-17 00:29
@nateww are you still seeing this on Terraform 0.12.26 or in an 0.13.0 beta?

**Comment by nateww** [comment] 2020-06-17 00:39
@danieldreier - I don't know, as this bug was reported 2.5 years ago, and I no longer work at the place where I experienced this bug.

**Comment by danieldreier** [comment] 2020-06-17 00:54
Thanks @nateww. I apologize for how long it's taken to respond to this and I appreciate that you reported it. I've been going through our backlog of crashes and am down to the last few, including yours.

Since nobody else has upvoted this, I'm going to assume it's been resolved in the meantime, so I'll close it.

**Closed by danieldreier** 2020-06-17 00:54 UTC
Labels: config, crash
