### ISSUE TITLE
Provider inheritance issue, provider loses configuration on nested module.

### ISSUE THREAD

**Issue by ThelonKarrde** [hashicorp/terraform#30849] opened 2022-04-12 18:43 UTC
### Terraform Version

```
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/tls v3.2.1
```

### Terraform Configuration Files

```terraform
# Root module provider configuration (custom region)
provider "aws" {
  region = "us-west-1"
  alias  = "aws-us-west-1"
}

# First nested module declaration in the root module
module "cl_aws_us_west_1_test" {
  providers = {
    aws        = aws.aws-us-west-1
    kubernetes = kubernetes.cl_aws_us_west_1_test
    helm       = helm.cl_aws_us_west_1_test
  }
  source                              = "./modules/eks"
# ...
}

# Declaration of `required_providers` in `./modules/eks`
terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "2.4.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.8.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "4.4.0"
    }
  }
}

# Declaration another nested module in `./modules/eks/efs.tf`
module "efs" {
  providers = {
    aws        = aws
    helm       = helm
    kubernetes = kubernetes
  }
  source                           = "../efs-csi-driver"
# ...
}

# Alternative tested configuration
module "efs" {
  source                           = "../efs-csi-driver"
# ...

# Declaration of `required_providers` in  `../efs-csi-driver`
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.4.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.4.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.8.0"
    }
    random = {
      source = "hashicorp/random"
      version = "3.1.2"
    }
  }
}

# Resource wtihing `../efs-csi-driver` which uses "aws" provider
data "aws_iam_policy_document" "efs_csi_driver" { ... }
}
```

### Expected Behavior

Just creating a new resource using a passed/inherited provider.

### Actual Behavior

Getting an error on `terraform plan`:
```
module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]: Refreshing state... [id=es-test-test-us-west-1-eks-efs-csi-driver-123456]
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.
│ 
╵
╷
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│ 
╵
Releasing state lock. This may take a few moments...
make: *** [plan] Error 1
```

So for some reason, it does not pass the configuration of the root `aws` provider to the nested module.
__If__ I set the environment variable in the console to `AWS_REGION=us-west-1` error disappears by itself. But that means that instead of providing a configuration block `aws` provider uses the default configuration of the AWS CLI set which is misbehavior to me.

### Steps to Reproduce

Configuration above.

### Additional Context

This code was already deployed, but later provider blocks were moved.

**Comment by jbardin** [comment] 2022-04-12 21:23
Hi @ThelonKarrde,

Thanks for filing the issue. If I take the configuration as shown here, any aws resources in the `efs` module do get a correctly configured provider. The `providers` command gives the following output:

```
% terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws]
└── module.cl_aws_us_west_1_test
    ├── provider[registry.terraform.io/hashicorp/aws] 4.4.0
    └── module.efs
        └── provider[registry.terraform.io/hashicorp/aws] 4.4.0
```

Can you try to reduce your config to a minimal example which can reproduce the issue?

Thanks!

**Comment by ThelonKarrde** [comment] 2022-04-12 21:49
Just to compare here is a `terraform providers` output on my side:
```

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws]
├── provider[registry.terraform.io/hashicorp/kubernetes]
├── provider[registry.terraform.io/hashicorp/helm]
└── module.cl_aws_us_west_1_test
    ├── provider[registry.terraform.io/hashicorp/aws] 4.4.0
    ├── provider[registry.terraform.io/hashicorp/helm] 2.4.1
    ├── provider[registry.terraform.io/hashicorp/kubernetes] 2.8.0
    ├── module.efs
    │   ├── provider[registry.terraform.io/hashicorp/aws] 4.4.0
    │   ├── provider[registry.terraform.io/hashicorp/helm] 2.4.1
    │   ├── provider[registry.terraform.io/hashicorp/kubernetes] 2.8.0
    │   └── provider[registry.terraform.io/hashicorp/random] 3.1.2
    ├── module.eks
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    │   ├── provider[registry.terraform.io/hashicorp/tls] >= 2.2.0
    │   ├── module.eks_managed_node_group
    │       ├── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
    │       ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    │       └── module.user_data
    │           └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
    │   ├── module.fargate_profile
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    │   └── module.self_managed_node_group
    │       ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0
    │       ├── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
    │       └── module.user_data
    │           └── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
    └── module.vpc
        └── provider[registry.terraform.io/hashicorp/aws] >= 3.63.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/aws]

    provider[registry.terraform.io/hashicorp/helm]

    provider[registry.terraform.io/hashicorp/kubernetes]

    provider[registry.terraform.io/hashicorp/tls]
```

Here is a reduced example with the exactly the same structure and inheritance as in full code:
```
.
├── ./modules
│   ├── ./modules/efs
│   │   ├── ./modules/efs/efs.tf
│   │   └── ./modules/efs/efs_providers.tf
│   └── ./modules/eks
│       ├── ./modules/eks/eks.tf
│       └── ./modules/eks/eks_providers.tf
├── ./providers.tf
└── ./root.tf

# ./root.tf
module "eks" {
    source = "./modules/eks"
    providers = {
        aws = aws.aws-us-west-1
    }
}

# ./providers.tf
provider "aws" {
  region = "us-west-1"
  alias  = "aws-us-west-1"
}

# ./modules/eks/eks.tf
module "efs" {
  source = "../efs"
  providers = {
    aws = aws
  }
}


# ./modules/eks/eks_providers.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.4.0"
    }
  }
}

# ./modules/efs/efs.tf
data "aws_availability_zones" "available" {}


# ./modules/efs/efs_providers.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.4.0"
    }
  }
}
```

**Comment by jbardin** [comment] 2022-04-13 12:42
Thanks @ThelonKarrde,

That example matches what I created from the initial config, but when run in isolation it does not produce an error. The output indicates the provider configuration error is happening while accessing the `aws_iam_role_policy_attachment.efs_csi_driver` resource. Can you check if that resource is configured to use the same provider instance? 

Another option is that a misconfiguration was somehow saved into the state, and that resource is pointing to an un-configured provider (though I'm not sure how that would happen without a corresponding provider block, I'm unable to get a missing provider from state to fail like this even when deliberately misconfigured).

If your minimal example reproduces the error, the output from `TF_LOG_CORE=trace` may help debug the issue.

Thanks!

**Comment by ThelonKarrde** [comment] 2022-04-13 14:51
@jbardin the configuration of `aws_iam_role_policy_attachment.efs_csi_driver` is pretty usual so it's not pointed to any custom provider.
```
resource "aws_iam_role_policy_attachment" "efs_csi_driver" {
  count      = var.enabled ? 1 : 0
  role       = element(aws_iam_role.efs_csi_driver, 0).name
  policy_arn = element(aws_iam_policy.efs_csi_driver, 0).arn
}
```

I do think that it might be related to misconfiguration written into the state because I moved provider blocks, but it was blocks related to `kubernetes` and `helm` providers, not to `aws` provider.


Here is a trace of a related section of output:
<details>
<summary><b>Trace</b></summary>


```

2022-04-13T09:45:49.738-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Called downstream: tf_provider_addr=provider tf_req_id=<redacted> @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:558 @module=sdk.proto tf_resource_type=aws_iam_role_policy_attachment tf_rpc=ReadResource tf_proto_version=5 timestamp=2022-04-13T09:45:49.738-0500
2022-04-13T09:45:49.738-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Called downstream: tf_provider_addr=provider tf_req_id=<redacted> @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:558 @module=sdk.proto tf_resource_type=aws_iam_role_policy_attachment tf_rpc=ReadResource tf_proto_version=5 timestamp=2022-04-13T09:45:49.738-0500
2022-04-13T09:45:49.738-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Served request: tf_resource_type=aws_iam_role_policy_attachment tf_rpc=ReadResource @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:564 @module=sdk.proto tf_proto_version=5 tf_provider_addr=provider tf_req_id=<redacted> timestamp=2022-04-13T09:45:49.738-0500
2022-04-13T09:45:49.738-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Served request: tf_resource_type=aws_iam_role_policy_attachment tf_rpc=ReadResource @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:564 @module=sdk.proto tf_proto_version=5 tf_provider_addr=provider tf_req_id=<redacted> timestamp=2022-04-13T09:45:49.738-0500
2022-04-13T09:45:49.739-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to refreshState for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.739-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to refreshState for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.739-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.739-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.740-0500 [TRACE] Re-validating config for "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]"
2022-04-13T09:45:49.740-0500 [TRACE] Re-validating config for "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]"
2022-04-13T09:45:49.740-0500 [TRACE] GRPCProvider: ValidateResourceConfig
2022-04-13T09:45:49.740-0500 [TRACE] GRPCProvider: ValidateResourceConfig
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Received request: tf_provider_addr=provider tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:495 @module=sdk.proto tf_proto_version=5 tf_rpc=ValidateResourceTypeConfig timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Received request: tf_provider_addr=provider tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:495 @module=sdk.proto tf_proto_version=5 tf_rpc=ValidateResourceTypeConfig timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Calling downstream: @module=sdk.proto tf_proto_version=5 tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:502 tf_rpc=ValidateResourceTypeConfig tf_provider_addr=provider timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Called downstream: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:508 tf_provider_addr=provider tf_req_id=<redacted> tf_rpc=ValidateResourceTypeConfig @module=sdk.proto tf_proto_version=5 tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Calling downstream: @module=sdk.proto tf_proto_version=5 tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:502 tf_rpc=ValidateResourceTypeConfig tf_provider_addr=provider timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Called downstream: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:508 tf_provider_addr=provider tf_req_id=<redacted> tf_rpc=ValidateResourceTypeConfig @module=sdk.proto tf_proto_version=5 tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Served request: tf_resource_type=aws_iam_role_policy_attachment tf_rpc=ValidateResourceTypeConfig @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:514 tf_provider_addr=provider tf_req_id=<redacted> @module=sdk.proto tf_proto_version=5 timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Served request: tf_resource_type=aws_iam_role_policy_attachment tf_rpc=ValidateResourceTypeConfig @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:514 tf_provider_addr=provider tf_req_id=<redacted> @module=sdk.proto tf_proto_version=5 timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] GRPCProvider: PlanResourceChange
2022-04-13T09:45:49.741-0500 [TRACE] GRPCProvider: PlanResourceChange
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Received request: tf_provider_addr=provider tf_req_id=<redacted> tf_rpc=PlanResourceChange @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:570 @module=sdk.proto tf_proto_version=5 tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Received request: tf_provider_addr=provider tf_req_id=<redacted> tf_rpc=PlanResourceChange @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:570 @module=sdk.proto tf_proto_version=5 tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Calling downstream: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:577 @module=sdk.proto tf_proto_version=5 tf_rpc=PlanResourceChange tf_provider_addr=provider tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Calling downstream: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:577 @module=sdk.proto tf_proto_version=5 tf_rpc=PlanResourceChange tf_provider_addr=provider tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Called downstream: tf_req_id=<redacted> tf_rpc=PlanResourceChange @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:583 @module=sdk.proto tf_provider_addr=provider tf_proto_version=5 tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.741-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Called downstream: tf_req_id=<redacted> tf_rpc=PlanResourceChange @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:583 @module=sdk.proto tf_provider_addr=provider tf_proto_version=5 tf_resource_type=aws_iam_role_policy_attachment timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.742-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Served request: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:589 tf_provider_addr=provider @module=sdk.proto tf_proto_version=5 tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment tf_rpc=PlanResourceChange timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.742-0500 [TRACE] provider.terraform-provider-aws_v4.4.0_x5: Served request: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:589 tf_provider_addr=provider @module=sdk.proto tf_proto_version=5 tf_req_id=<redacted> tf_resource_type=aws_iam_role_policy_attachment tf_rpc=PlanResourceChange timestamp=2022-04-13T09:45:49.741-0500
2022-04-13T09:45:49.742-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.742-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.742-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.742-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.743-0500 [TRACE] writeChange: recorded NoOp change for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.743-0500 [TRACE] writeChange: recorded NoOp change for module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]": visit complete
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver[0]": visit complete
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver": dynamic subgraph completed successfully
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver": dynamic subgraph completed successfully
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver": visit complete
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver (expand)": dynamic subgraph completed successfully
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver": visit complete
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver (expand)": dynamic subgraph completed successfully
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver (expand)": visit complete
2022-04-13T09:45:49.743-0500 [TRACE] vertex "module.cl_aws_us_west_1_test.module.efs.aws_iam_role_policy_attachment.efs_csi_driver (expand)": visit complete
2022-04-13T09:45:49.743-0500 [TRACE] dag/walk: upstream of "module.cl_aws_us_west_1_test.module.efs (close)" errored, so skipping
2022-04-13T09:45:49.743-0500 [TRACE] dag/walk: upstream of "module.cl_aws_us_west_1_test.module.efs (close)" errored, so skipping
2022-04-13T09:45:49.743-0500 [TRACE] dag/walk: upstream of "module.cl_aws_us_west_1_test (close)" errored, so skipping
2022-04-13T09:45:49.743-0500 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"].aws-us-west-1 (close)": starting visit (*terraform.graphNodeCloseProvider)
2022-04-13T09:45:49.743-0500 [TRACE] dag/walk: upstream of "module.cl_aws_us_west_1_test (close)" errored, so skipping
2022-04-13T09:45:49.743-0500 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"].aws-us-west-1 (close)": starting visit (*terraform.graphNodeCloseProvider)
2022-04-13T09:45:49.743-0500 [TRACE] GRPCProvider: Close
2022-04-13T09:45:49.743-0500 [TRACE] GRPCProvider: Close
2022-04-13T09:45:49.744-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-04-13T09:45:49.744-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-04-13T09:45:49.749-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/4.4.0/darwin_arm64/terraform-provider-aws_v4.4.0_x5 pid=17748
2022-04-13T09:45:49.749-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/4.4.0/darwin_arm64/terraform-provider-aws_v4.4.0_x5 pid=17748
2022-04-13T09:45:49.749-0500 [DEBUG] provider: plugin exited
2022-04-13T09:45:49.749-0500 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"].aws-us-west-1 (close)": visit complete
2022-04-13T09:45:49.749-0500 [TRACE] dag/walk: upstream of "root" errored, so skipping
2022-04-13T09:45:49.749-0500 [DEBUG] provider: plugin exited
2022-04-13T09:45:49.749-0500 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"].aws-us-west-1 (close)": visit complete
2022-04-13T09:45:49.749-0500 [TRACE] dag/walk: upstream of "root" errored, so skipping
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/aws"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/cloudinit"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/helm"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/aws"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/cloudinit"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/helm"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/kubernetes"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/random"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/kubernetes"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/random"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/tls"
2022-04-13T09:45:49.751-0500 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/tls"
2022-04-13T09:45:49.763-0500 [INFO]  backend/local: plan operation completed
2022-04-13T09:45:49.763-0500 [INFO]  backend/local: plan operation completed

Error: Invalid provider configuration

Provider "registry.terraform.io/hashicorp/aws" requires explicit
configuration. Add a provider block to the root module and configure the
provider's required arguments as described in the provider documentation.


Error: Invalid provider configuration

Provider "registry.terraform.io/hashicorp/aws" requires explicit
configuration. Add a provider block to the root module and configure the
provider's required arguments as described in the provider documentation.


Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found

  with provider["registry.terraform.io/hashicorp/aws"],
  on <empty> line 0:
  (source code not available)


Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found

  with provider["registry.terraform.io/hashicorp/aws"],
  on <empty> line 0:
  (source code not available)
```
</details>

**Comment by jbardin** [comment] 2022-04-13 14:59
Sorry, that log does not contain the data I was looking for. Can you provide the complete log output using `TF_LOG_CORE=trace`?

**Comment by ThelonKarrde** [comment] 2022-04-13 16:10
Since trace is a little bit chunky here it's in gist (with TF_LOG=trace): https://gist.github.com/ThelonKarrde/a724bf75327e13d533583654b89ef5fc

**Comment by ThelonKarrde** [comment] 2022-04-13 16:11
Oh, wait, it's less than a third part of a log. I will paste it somehow else

**Comment by jbardin** [comment] 2022-04-13 16:26
The output might be significantly less with the `TF_LOG_CORE` variable, since I'm only looking for the CLI handling of the configuration, and we don't need the provider output.

**Comment by jbardin** [comment] 2022-04-13 17:14
It should be less than the complete log, but how much depends on a lot of factors, i.e. some providers are extremely chatty in the logs. Regardless, we are looking for how the configured providers are resolved in your case, which may be explained in the logs. the provider address from the state from the failing resource in combination with the configuration may also give us a means to reproduce the error.

**Comment by jbardin** [comment] 2022-04-14 15:56
Hi @ThelonKarrde,

Thanks for the logs. The data here suggests that the error is with some resources in the root module, not with a nested module. We know that `provider["registry.terraform.io/hashicorp/aws"].aws-us-west-1` is configured, so that leaves the non-aliased `provider["registry.terraform.io/hashicorp/aws"]` as the one missing configuration. The resources which depends on this provider are in the root module:

```
data.aws_eks_cluster.cl_aws_us_west_1_test
data.aws_eks_cluster_auth.cl_aws_us_west_1_test
```

Is it possible you forgot to specify a `provider` for these in the config?

**Comment by ThelonKarrde** [comment] 2022-04-14 16:00
Yeap, that was it! Thanks!

My understanding was that if there are no other explicitly defined providers of the same type data/resource will pickup the only defined as a default one.

Leaving fix for history:
```
# Cluster data for kubernetes and helm providers
data "aws_eks_cluster" "cl_aws_us_west_1_test" {
  provider = aws.aws-us-west-1
  name     = module.cl_aws_us_west_1_test.cluster_id
}

# Cluster auth for kubernetes and helm providers
data "aws_eks_cluster_auth" "cl_aws_us_west_1_test" {
  provider = aws.aws-us-west-1
  name     = module.cl_aws_us_west_1_test.cluster_id
}
```

**Comment by jbardin** [comment] 2022-04-14 16:06
Thanks for confirming!

**Closed by jbardin** 2022-04-14 16:06 UTC
Labels: bug, new, waiting for reproduction
