### ISSUE TITLE
scaleway_volume_attachment for more than one volume fail

### ISSUE THREAD

**Issue by dcharbonnier** [hashicorp/terraform#9473] opened 2016-10-20 09:35 UTC
Adding more than one volume to a server fail, the state the server is not ready when the first attachment finish and the second result in a 
```
* scaleway_volume_attachment.agent-volume-attachment.1: StatusCode: 400, Type: invalid_request_error, APIMessage: server is being stopped or rebooted
```

**Comment by nicolai86** [comment] 2016-10-20 17:41
duplicate of #9417

**Comment by jbardin** [comment] 2016-10-20 20:24
Closing as a duplicate of 9417

**Closed by jbardin** 2016-10-20 20:24 UTC
