### ISSUE TITLE
Terraform 0.14 breaks for_each workflow consuming existing sensitive module outputs

### ISSUE THREAD

**Issue by umglurf** [hashicorp/terraform#27239] opened 2020-12-10 16:59 UTC
With 0.14, for_each on a map that has objects where one or more of the values is sensitive no longer works, while it worked in 0.13. A working example to show this issue is provided below

### Terraform Version

```
Terraform v0.14.2
```

### Terraform Configuration Files

```terraform
module "input" {
  source   = "./modules/input"
}

locals {
  config = {
    test = {
      token = module.input.token
    }
  }
}

module "test" {
  source   = "./modules/test"
  projects = ["project1"]
  config   = local.config
}
```
module input:
```terraform
locals {
  token = "foo"
}

output "token" {
  value     = local.token
  sensitive = true
}
```
module test:
```terraform
variable "projects" {
  type = list(string)
}

variable "config" {
  type = map(object({
    token = string
  }))
}

resource "null_resource" "project" {
  for_each = { for e in setproduct(var.projects, keys(var.config)) : "${e[0]}-${e[1]}" => e }
  # do something with token here
}
```

### Debug Output

N/A

### Crash Output

N/A
### Expected Behavior

Terraform should have been able to run plan/apply as it does in 0.13

### Actual Behavior

```
Error: Invalid for_each argument

  on modules/test/main.tf line 12, in resource "null_resource" "project":
  12:   for_each = { for e in setproduct(var.projects, keys(var.config)) : "${e[0]}-${e[1]}" => e }

Sensitive variable, or values derived from sensitive variables, cannot be used
as for_each arguments. If used, the sensitive value could be exposed as a
resource instance key.

```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

#27180

**Comment by danieldreier** [comment] 2020-12-10 17:05
To clarify, I think the key issue in this use case is that you previously had already defined a sensitive output prior to 0.14 and so are seeing a behavior change with no clear workaround in 0.14.

**Comment by danieldreier** [comment] 2020-12-10 17:10
I've copied this reproduction case into https://github.com/danieldreier/terraform-issue-reproductions/tree/master/27239 and can confirm that it behaves as described in 0.14.2. I think the behavior is expected, but the breaking interaction with previously-defined sensitive variables warrants some consideration as to how to avoid a breaking upgrade in this use case.

**Comment by umglurf** [comment] 2020-12-10 17:30
@danieldreier that is correct

**Comment by pselle** [comment] 2020-12-14 21:55
@umglurf Unfortunately it does appear that your workflow has been impacted by 0.14's enhanced sensitivity tracking behavior (tracking the sensitivity of values throughout the plan).

There's an issue besides the sensitive outputs, which is that functions are called. I've opened #27280 to clarify that currently, when you call a function in Terraform with sensitive arguments, the result is generally sensitive. So, even though you are calling functions and at the end result, no sensitive data is in the resulting value, the way things currently work, because a function was called with sensitive arguments, its return value is sensitive.

I say "generally" because while this is true now, these functions could, in some cases, be updated to allow for sensitive inputs and return appropriate results -- but that is not true currently, and is actually on a per-function basis.

 This does mean that some configurations that relied on sensitive outputs will need to be updated.

To work with sensitive values to determine the number of resources managed by Terraform, you will be able to use `count` (which has a bug in the current released version, but will be fixed in the next), as using `count` won't print out any sensitive values to the UI.

**Comment by umglurf** [comment] 2020-12-15 06:09
@pselle I will need to find some workaround then. I hope at some point there will be a solution for this, is this can make it difficult to use for_each, which is unfortunate, as it is often superior to count.

**Closed** 2020-12-15 16:46 UTC
Labels: bug, confirmed, new, v0.14

**Comment by pselle** [comment] 2020-12-15 19:21
@umglurf Yes, agree, `for_each` has much nicer ergonomics than `count` in many cases.

Since you are going to look for a workaround, I suggest focusing on what you can do with expressions rather than functions (since functions generally will always return sensitive values, currently). I don't like even making this suggestion, because you will likely end up with some complex expressions over using a function call, but I want to point it out:

You can use a for expression to, for example, replicate the behavior of the `keys()` function without handing off to HCL:

```
> local.baz
{
  "a" = (sensitive)
  "b" = "dog"
}
> {for k, v in local.baz: k => k }
{
  "a" = "a"
  "b" = "b"
}
```

In your use case, you could see what kind of transformation you could make to get the value you had previously in your `for_each` argument.

**Comment by umglurf** [comment] 2020-12-16 03:51
@pselle Thanks for this, this worked in my workflow with minimal changes. Maybe this should be added to the documentation about sensitive values?

**Comment by pselle** [comment] 2020-12-16 16:13
@umglurf Thanks for trying it out and letting me know! And yes 🤔 I am thinking of perhaps a few more places (such as the `for_each` docs as well) that could benefit from a nod in the documentation. Thanks!

**Comment by Matthewsre** [comment] 2021-01-07 19:58
@pselle I ran into this issue and the workaround does not work if the value being iterated over is passed into a module

```
Error: Invalid for_each argument

  on ..\..\modules\traffic\main.tf line 34, in resource "azurerm_traffic_manager_endpoint" "microservice_function":
  34:   for_each = var.http_target == "function" ? var.function_apps : {}

Sensitive values, or values derived from sensitive values, cannot be used as
for_each arguments. If used, the sensitive value could be exposed as a
resource instance key.
```

This is the error I am getting when using the solution suggested:

```
Error: Invalid for_each argument

  on ..\..\modules\traffic\main.tf line 34, in resource "azurerm_traffic_manager_endpoint" "microservice_function":
  34:   for_each = var.http_target == "function" ? { for function in var.function_apps : function.id => { id = function.id, location = function.location } } : {}

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

```

You can see the implementation here:
https://github.com/Matthewsre/terraform-azurerm-microservices/blob/280e1370ad552e7bc0db4e28db8ee1583d128e0f/modules/traffic/main.tf#L34

If you look in the master branch you will see that this was working correctly when in the same module:
NOTE: I had to flag the return value as sensitive to be able to return it
https://github.com/Matthewsre/terraform-azurerm-microservices/blob/b8b418238c247d251aedbec60cd9619f6c2ec7f2/modules/microservice/main.tf#L436

Seems like the entire output value must be marked as sensitive instead of just honoring the existing marked outputs.

Any suggestions to help unblock me on this issue?

**Comment by pselle** [comment] 2021-01-07 20:18
@Matthewsre You're getting a different error from sensitivity when you use the suggestion, which suggests that it's avoided the sensitivity issue :) 

> The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.

Depending on what you're passing to the module as the `var.function_apps` or `var.http_target` argument, have you tried using `-target` as suggested? (the source reference here is pointing to the `for_each` line, not necessarily the object that it's depending on, which might be a source of confusion)

**Comment by Matthewsre** [comment] 2021-01-07 21:41
@pselle Thank you for the quick reply! I don't think I articulated very well, so I'll take another stab.

I can take a collection of resources like azurerm_function_app.microservice and use it in the same module (microservice) in a for_each with no problem.

I have broken that out into a second module (traffic) that will be called after the first module (microservice) with output results from the first module.

## Issue 1
When turning azurerm_function_app.microservice into an output variable to use I can only proceed by setting sensitive = true, which flags the entire object as sensitive instead of just the existing sensitive properties. (Seems like this should be cascading instead of flagging the entire object).

Because of the sensitive flag I am no longer able to pass the output from the first module of azurerm_function_app.microservice into the second module and use it with for_each.

## Issue 2
Any operations I try to perform to include just the values I need that are not sensitive breaks the ability for Terraform to predict how many instances will be created. There might be a way to do this, but I can't seem to figure it out. 

* Is there any guidance anywhere that indicates which operations/functions will break prediction and which ones won't?

This should be able to run in a pipeline without breaking up the targets and I am doing the same things with azurerm_app_service between these modules without issue because it does not have any sensitive values.

---

Does that help bring clarity to the issue I am running into and do you have any suggestions for working around this?

**Comment by pselle** [comment] 2021-01-08 17:33
Thanks for adding the edit that you figured out issue 2! For issue 1, I'll offer some context that may or may not be helpful as to "why does the whole output need to be sensitive" -- when we denote in state which values are sensitive (so that we know what values are sensitive when loading a prior state), for resources, we know _what attributes_ within the resource, but for outputs, there is only one value (much as if a resource had one attribute) and it's either sensitive or not.

So to issue 1, one idea is you could add another output where you apply the appropriate transformation to the value so that it doesn't contain any sensitive data, thus doesn't need `sensitive = true` on the output.
