### ISSUE TITLE
Terraform crash when backend secret_suffix ends with "-[1-9]"

### ISSUE THREAD

**Issue by tschneider-aneo** [hashicorp/terraform#35956] opened 2024-11-06 13:29 UTC
### Terraform Version

```shell
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.1
+ provider registry.terraform.io/hashicorp/null v3.2.3
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 2.21.1"
    }
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}

terraform {
  backend "kubernetes" {
  }
}

resource "null_resource" "example" {
  provisioner "local-exec" {
    command = "echo 'foobar'"
  }
}
```

### Debug Output

https://gist.github.com/tschneider-aneo/111f80d3f6566277d489b3078957277e

### Expected Behavior

My backend secret suffix gets correctly created as "foo-3"

### Actual Behavior

Terraform somehow considers the "-[1-9]" ending as an index for an object of length 1, resulting in an index out of range Terraform crash

### Steps to Reproduce

terraform init -upgrade -reconfigure -backend-config="secret_suffix=foo-2"

**Comment by idsulik** [comment] 2024-11-07 06:55
The reason for this issue is explained here https://github.com/hashicorp/terraform/issues/35641#issuecomment-2325149637  
The question is why the `secret_suffix` validator(https://github.com/hashicorp/terraform/pull/35666) skipped the case

**Comment by liamcervante** [comment] 2024-11-07 08:10
I will close this as a duplicate of https://github.com/hashicorp/terraform/issues/35641.

**Closed by liamcervante** 2024-11-07 08:10 UTC
Labels: bug, backend/k8s, new
