### ISSUE TITLE
Terraform apply error

### ISSUE THREAD

**Issue by yangzhares** [hashicorp/terraform#8982] opened 2016-09-22 09:08 UTC
hi there,

here are error info when i executed terraform apply, please help check

```
Error applying plan:

2 error(s) occurred:

* openstack_compute_instance_v2.instance.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.3
    Resource ID: openstack_compute_instance_v2.instance.0
    Mismatch reason: attribute mismatch: floating_ip
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"volume.1490182712.volume_id":*terraform.ResourceAttrDiff{Old:"d9e25e91-9bd8-4b8c-b411-d0479ef3cc0f", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "volume.~1575295281.id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "volume.~1575295281.volume_id":*terraform.ResourceAttrDiff{Old:"", New:"${element(openstack_blockstorage_volume_v1.blockstorage.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "volume.~1575295281.device":*terraform.ResourceAttrDiff{Old:"", New:"/dev/vdb", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "floating_ip":*terraform.ResourceAttrDiff{Old:"10.225.1.248", New:"${ element(split(\",\", var.floating_ips), count.index) }", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* openstack_compute_instance_v2.instance.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.3
    Resource ID: openstack_compute_instance_v2.instance.1
    Mismatch reason: attribute mismatch: floating_ip
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"volume.~1575295281.device":*terraform.ResourceAttrDiff{Old:"", New:"/dev/vdb", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "floating_ip":*terraform.ResourceAttrDiff{Old:"10.225.1.249", New:"${ element(split(\",\", var.floating_ips), count.index) }", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "volume.3200704502.volume_id":*terraform.ResourceAttrDiff{Old:"178f485f-c8cf-441c-8a0e-a058c5c5850a", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "volume.~1575295281.id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "volume.~1575295281.volume_id":*terraform.ResourceAttrDiff{Old:"", New:"${element(openstack_blockstorage_volume_v1.blockstorage.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

the scenario is that at the beginning i created two openstack vm instances, and then i modified instance number to 3, and run terraform plan and terraform apply again. it triggered this issue happened.

**Comment by mitchellh** [comment] 2016-11-17 00:47
Hello! This should be fixed in later versions of Terraform. 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 00:47 UTC
Labels: bug, provider/openstack
