### ISSUE TITLE
The Terraform Registry displays inconsistent and wrong `source` information for submodules

### ISSUE THREAD

**Issue by directionless** [hashicorp/terraform#31017] opened 2022-05-06 21:29 UTC
I'm trying to use several submodules on the terraform registry, and I've noticed that they have the wrong source information. 

https://registry.terraform.io/modules/terraform-google-modules/vm/google/latest/submodules/mig says to use `"terraform-google-modules/vm/google/modules/mig"`

https://registry.terraform.io/modules/hashicorp/consul/aws/latest/submodules/consul-client-security-group-rules has an automated box that suggests `"hashicorp/consul/aws/modules/consul-client-security-group-rules"`, but then has a README that says `"git::git@github.com:hashicorp/terraform-aws-vault.git//modules/vault-cluster?ref=v0.0.1"`

After getting some help from [the community](https://discuss.hashicorp.com/t/using-a-registry-module-results-in-cannot-detect-a-supported-external-module-source-errors/39186) I see that there's a special `//` form for submodule. I see that this is documented as [sub-directory](https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories), but I never found that because elsewhere it's called a "submodule"

Ultimately, the correct source seems to be `terraform-google-modules/vm/google//modules/mig`, but it took me several hours to determine that. 

### Terraform Version

This is a registry website issue, but:
```
$ terraform version
Terraform v1.1.9
on darwin_arm64
```

### Debug Output
```
│ Error: Invalid module source address
│ 
│ Module "mig" (declared at main.tf line 12) has invalid source address
│ "terraform-google-modules/vm/google/modules/mig": Terraform cannot detect a supported external module
│ source type for terraform-google-modules/vm/google/modules/mig.
```
### References

* https://discuss.hashicorp.com/t/using-a-registry-module-results-in-cannot-detect-a-supported-external-module-source-errors/39186

**Comment by apparentlymart** [comment] 2022-05-10 17:42
Sorry for these installation instructions @directionless, and thanks for reporting it.

I told the Terraform Registry maintainers about this issue and they have now pushed a fix to report the correct path. It looks like this was an accidental regression that came in a recent update to how Terraform Registry reports installation instructions for submodules.

On [the submodule detail page you linked in your issue](https://registry.terraform.io/modules/terraform-google-modules/vm/google/latest/submodules/mig) I now see what seems like a correct source address for that module:

```hcl
module "vm_mig" {
  source  = "terraform-google-modules/vm/google//modules/mig"
  version = "7.7.0"
  # insert the 4 required variables here
}
```

They've also put in place a new unit test to catch similar regressions in the future.

Thanks again for reporting this!

**Closed by apparentlymart** 2022-05-10 17:42 UTC
Labels: bug, registry

**Comment by directionless** [comment] 2022-05-12 03:14
That looks so much better. Thank you so much for fixing it!
