### ISSUE TITLE
helper/schema: Crash when S3 bucket object ref'd in ResourceData.get

### ISSUE THREAD

**Issue by N4R3N** [hashicorp/terraform#15367] opened 2017-06-22 13:57 UTC
### Terraform Version
v0.9.8

### Crash Log

```
data.aws_s3_bucket_object.lambda - *terraform.NodeRefreshableDataResourceInstance
2017/06/22 13:53:56 [DEBUG] dag/walk: added new vertex: "data.aws_s3_bucket_object.lambda"
2017/06/22 13:53:56 [DEBUG] dag/walk: walking "data.aws_s3_bucket_object.lambda"
2017/06/22 13:53:56 [DEBUG] vertex 'root.data.aws_s3_bucket_object.lambda': walking
2017/06/22 13:53:56 [DEBUG] vertex 'root.data.aws_s3_bucket_object.lambda': evaluating
2017/06/22 13:53:56 [TRACE] [walkRefresh] Entering eval tree: data.aws_s3_bucket_object.lambda
2017/06/22 13:53:56 [DEBUG] root: eval: *terraform.EvalSequence
2017/06/22 13:53:56 [DEBUG] root: eval: *terraform.EvalWriteState
2017/06/22 13:53:56 [DEBUG] root: eval: *terraform.EvalInterpolate
2017/06/22 13:53:56 [DEBUG] Interpolating computed list element attribute code_bucket_id (1)
2017/06/22 13:53:56 [DEBUG] root: eval: *terraform.EvalIf
2017/06/22 13:53:56 [DEBUG] root: eval: terraform.EvalNoop
2017/06/22 13:53:56 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/06/22 13:53:56 [DEBUG] root: eval: *terraform.EvalReadDataDiff
2017/06/22 13:53:56 [DEBUG] plugin: terraform: panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 
2017/06/22 13:53:56 [DEBUG] plugin: terraform: goroutine 92 [running]:
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc4202fd5e0, 0xc42061c3b0, 0x1, 0x1, 0xc42061c312, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:480 +0x311
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc4202fd5e0, 0x554bfc9, 0x6, 0x401201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:451 +0x135
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc4202fd5e0, 0x554bfc9, 0x6, 0x40eed2, 0xc4208e7cb0, 0x30, 0x30, 0x5306240)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:428 +0x61
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc4208e3e60, 0x554bfc9, 0x6, 0xc42091c1e0, 0xc4208f9620, 0xc4202fd5e0, 0x5306200, 0x0, 0x0)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:1051 +0xb5
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc4208e3e60, 0x554bfc9, 0x6, 0xc42091c1e0, 0xc42061e540, 0xc4202fd5e0, 0x0, 0x7fafc6c82400, 0x6fc23a6a7)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:685 +0x43b
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc4208e3e60, 0x0, 0xc4208e7b00, 0x0, 0x0, 0x18)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:389 +0x1c2
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc42090ce40, 0x0, 0xc4208e7b00, 0x14, 0xc420871978, 0xc4208e7c01)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:211 +0x15b
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataDiff(0xc4202de380, 0xc4208b1e50, 0xc4208e7b00, 0x7fafc6c824b0, 0x0, 0x0)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:368 +0x83
2017/06/22 13:53:56 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataDiff(0xc4202c9460, 0xc42061c0b0, 0xc42061c360, 0x0, 0x0)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:554 +0x4e
2017/06/22 13:53:56 [DEBUG] plugin: terraform: reflect.Value.call(0xc42086b320, 0xc4203fe730, 0x13, 0x55480a3, 0x4, 0xc420773f20, 0x3, 0x3, 0x0, 0xc42077ee01, ...)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/06/22 13:53:56 [DEBUG] plugin: terraform: reflect.Value.Call(0xc42086b320, 0xc4203fe730, 0x13, 0xc42077ef20, 0x3, 0x3, 0xc42077ef68, 0x601e93, 0xc4202fbc00)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/06/22 13:53:56 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420208900, 0xc420208880, 0xc4203bc3c0, 0xc4205e5600, 0xc420492dc0, 0x463b620, 0xc42061c0b0, 0x16, 0x463b660, 0xc42061c360, ...)
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/06/22 13:53:56 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/06/22 13:53:56 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/06/22 13:53:56 [DEBUG] plugin: /terraform/terraform: plugin process exited
2017/06/22 13:53:56 [ERROR] root: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2017/06/22 13:53:56 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2017/06/22 13:53:56 [TRACE] [walkRefresh] Exiting eval tree: data.aws_s3_bucket_object.lambda
2017/06/22 13:53:56 [DEBUG] dag/walk: upstream errored, not walking "provider.aws (close)"
2017/06/22 13:53:56 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/06/22 13:53:56 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/06/22 13:53:56 [WARN] plugin: error closing client during Kill: connection is shut down
2017/06/22 13:53:56 [DEBUG] plugin: terraform: terraform-provider (internal) 2017/06/22 13:53:56 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/06/22 13:53:56 [DEBUG] plugin: /terraform/terraform: plugin process exited
```

### Expected Behavior
Moan about object not found.

### Actual Behavior
Crash

### Steps to Reproduce
Create aws_s3_bucket_object with out the actual object present in S3. Try deploying aws_lambda_function and Terraform crashes

**Comment by grubernaut** [comment] 2017-06-28 15:17
Re-opening as a `core` bug

**Comment by radeksimko** [comment] 2017-08-04 14:37
This looks like duplicate of https://github.com/hashicorp/terraform/issues/9488

**Comment by radeksimko** [comment] 2017-08-04 14:40
@jbardin are you happy for me to close this in favour of the mentioned issue?

**Comment by jbardin** [comment] 2017-08-04 14:59
:+1: Not much to go on here, but the crash looks the same

**Closed by jbardin** 2017-08-04 14:59 UTC
Labels: bug, core, crash, waiting-response
