### ISSUE TITLE
Crash when using consul backend

### ISSUE THREAD

**Issue by lunderhage** [hashicorp/terraform#16030] opened 2017-09-06 14:48 UTC
### Terraform Version
Terraform v0.10.3

### Terraform Configuration Files
crash.tf
```hcl
terraform {
  backend "consul" {
    address = "1.2.3.4:8500"
    path    = "terraform/example"
  }
}
```

### Debug Output
https://gist.github.com/lunderhage/2413c977c58b2e83b750692cc7171469

### Crash Output
https://gist.github.com/lunderhage/e668186ec75469251cb8000b2f943cda

### Expected Behavior
Terraform initiates correctly without crashing.

### Actual Behavior
Terraform crashes, giving no clear hint on why.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. Create a project using crash.tf above.
3. `terraform init`
4. Enjoy the crash log.

### Important Factoids
I am running terraform in an alpine:3.6 container. Crash does not occur in Terraform 0.10.2.

**Comment by jbardin** [comment] 2017-09-06 22:21
duplicate of #15972

**Closed by jbardin** 2017-09-06 22:21 UTC
