### ISSUE TITLE
If I use `-target` option terreform does not show changes to Outputs

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#34802] opened 2024-03-08 20:15 UTC
### Terraform Version

```shell
Terraform v1.7.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

### Terraform Configuration Files

```tf
@@ -36,7 +36,7 @@ resource "aws_instance" "db_a" {
   ...
   subnet_id                   = aws_subnet.a_prd_plntr.id
-  associate_public_ip_address = true
+  associate_public_ip_address = false
   iam_instance_profile        = aws_iam_instance_profile.db.name
   depends_on                  = [aws_internet_gateway.prd_plntr]

@@ -66,9 +66,6 @@ USER_DATA
-output "db_a_addr" {
-  value = "db-a.prd.plntr.ca: ${aws_instance.db_a.public_ip}"
-}
```

### Debug Output

If I run `terraform plan` we can see:
```
...  # aws_sns_topic_subscription.notify-ops will be created
  + resource "aws_sns_topic_subscription" "notify-ops" {
      + arn                             = (known after apply)
      + confirmation_timeout_in_minutes = 1
      + confirmation_was_authenticated  = (known after apply)
      + endpoint                        = "aws***"
      + endpoint_auto_confirms          = false
      + filter_policy_scope             = (known after apply)
      + id                              = (known after apply)
      + owner_id                        = (known after apply)
      + pending_confirmation            = (known after apply)
      + protocol                        = "email"
      + raw_message_delivery            = false
      + topic_arn                       = "arn:aws:sns:us-east-1:***:notify-ops"
    }

Plan: 12 to add, 7 to change, 6 to destroy.

Changes to Outputs:
  - db_a_addr   = "db-a.prd.***" -> null
  - db_c_addr   = "db-c.prd.***" -> null
  - res-12_addr = "res-12.prd.***" -> null
  - res-13_addr = "res-13.prd.***" -> null
  - www-5_addr  = "www-5.prd.***" -> null
  - www-7_addr  = "www-7.prd.***" -> null

```

### Expected Behavior

the `Outputs` section should be shown when `-target` is used and there is changes to it.

### Actual Behavior

But when I run command witih `-target` option I do not see 
```
Changes to Outputs:
  - db_a_addr   = "db-a.prd.***" -> null
  - db_c_addr   = "db-c.prd.***" -> null
  - res-12_addr = "res-12.prd.***" -> null
  - res-13_addr = "res-13.prd.***" -> null
  - www-5_addr  = "www-5.prd.***" -> null
  - www-7_addr  = "www-7.prd.***" -> null
```

It is not clear how to target it:
```
╷
│ Error: Invalid target "db_a_addr"
│
│ Resource specification must include a resource type and name.
╵

For more help on using this command, run:
  terraform plan -help
```

### Steps to Reproduce

1. AWS_PROFILE=root-acc terraform plan 
2. AWS_PROFILE=root-acc terraform plan -target aws_launch_template.www ... -out ips 
3. Compare the output

**Comment by jbardin** [comment] 2024-03-08 20:29
Duplicate of #29108

**Closed by jbardin** 2024-03-08 20:29 UTC
Labels: bug, new
