### ISSUE TITLE
Got checksum error while using aws provider 2.67.0

### ISSUE THREAD

**Issue by changyong** [hashicorp/terraform#25328] opened 2020-06-22 03:27 UTC
### Terraform Version

```
Terraform v0.10.7
```

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "2.67.0"
}
```

### Expected Behavior

Run `terraform init` successfully

### Actual Behavior

```
terraform init -backend-config=key=eu-central-1/qad3/webapp/terraform.tfstate -backend-config=region=us-west-2 -backend-config=profile=stg -backend-config=dynamodb_table=terraform_locks -backend-config=encrypt=true -backend-config=bucket=zias-terraform -lock-timeout=20m

....

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "null" (2.1.2)...
- Downloading plugin for provider "aws" (2.67.0)...

Error installing provider "aws": Checksums did not match.
Expected: f4f9cac0380cf90a14ba1b0d22499d5e3f1176080d7d78fd81e7a7e4c8e13a38
Got: 94fc742989ade558b5660652e2f0733b576ce4418271700de41861d5c4606855.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_386
```

### Steps to Reproduce

terraform init

### Additional Context

The `terraform init` will succeed if it set AWS provider to use 2.66.0

```
provider "aws" {
  version = "2.67.0"
}
```

**Comment by sepulworld** [comment] 2020-06-22 17:17
Getting same error but with Kubernetes provider

**Comment by sepulworld** [comment] 2020-06-22 17:20
Same error for me as well.

```- Downloading plugin for provider "aws" (hashicorp/aws) 2.67.0...
Error installing provider "aws": Checksums did not match for /tmp/getter048684685/archive.
Expected: f4f9cac0380cf90a14ba1b0d22499d5e3f1176080d7d78fd81e7a7e4c8e13a38
Got: 94fc742989ade558b5660652e2f0733b576ce4418271700de41861d5c4606855
*sha256.digest.
Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.
This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.
If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_386
Error: Checksums did not match for /tmp/getter048684685/archive.
Expected: f4f9cac0380cf90a14ba1b0d22499d5e3f1176080d7d78fd81e7a7e4c8e13a38
Got: 94fc742989ade558b5660652e2f0733b576ce4418271700de41861d5c4606855
*sha256.digest
```

**Comment by jbardin** [comment] 2020-06-22 17:36
Hello,

There appears to have been an issue with an AWS provider release, which may have been updated in place. The current checksums file matches correctly, and the cache may need to be purged. 

This appears to be a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/13877

Thanks!

**Closed by jbardin** 2020-06-22 17:36 UTC
