### ISSUE TITLE
AWS Route 53 records overwriting each other

### ISSUE THREAD

**Issue by benzimmer** [hashicorp/terraform#330] opened 2014-09-27 15:04 UTC
I have a scenario where I need to create two DNS A records for one subdomain. Currently I try to do it this way:

```
resource "aws_route53_zone" "cdn" {
    name = "cdn.example.com"
}

resource "aws_route53_record" "cdn1" {
    zone_id = "${aws_route53_zone.cdn.zone_id}"
    name = "cdn.example.com"
    type = "A"
    ttl = "60"
    records = [
        "${resource1.ipv4_address}"
    ]
}

resource "aws_route53_record" "cdn2" {
    zone_id = "${aws_route53_zone.cdn.zone_id}"
    name = "cdn.example.com"
    type = "A"
    ttl = "60"
    records = [
        "${resource2.ipv4_address}"
    ]
}
```

What I expect are two records, one for each resource IP. What I end up with is one DNS record for the resource that is created second. Is there any way to tell terraform that these are two different records and not just one?

(If I create this by hand in the aws console, this works as expected)

**Comment by pearkes** [comment] 2015-02-26 23:05
Reproduced, working on a fix..

**Comment by trentio** [comment] 2015-04-21 20:40
Hey all,  I was wondering if there was any forward activity on this. We are running into the same issue and are looking into putting some time in getting it to work if there hasn't.

**Comment by catsby** [comment] 2015-04-21 21:09
Hey @trentio – I've not managed to look into this yet, and won't be able too this week. If you have time, we'd love a contribution :smile:

**Comment by jfromaniello** [comment] 2015-06-04 21:43
I'd also love to see this happen. I have a deployment that involves creating records in route 53 with the latency based strategy and another domain with the geoip strategy.

I wish I could help but my go-foo is very weak

**Comment by mechastorm** [comment] 2015-06-11 12:26
I seem to encountering the same issue. 

I am an existing legacy (outside of terraform) Route53 record with weighted latency with a weight of 100. I was planning to setup a brand new Route53 record managed by Terraform with a weight of 0, and then manage the transition to the new stack manually as I test it.

My current Route53 record looks like this (with some values replaced)
https://gist.github.com/mechastorm/03bd141a2d219f004e30

And my output log is like this
https://gist.github.com/mechastorm/d368f3f8c2c64689b8bc

**Comment by jwestboston** [comment] 2015-07-15 19:30
Very curious about this bug.  Probably a precursor to having Geo/Latency records in AWS managed by Terraform.

**Comment by jwestboston** [comment] 2015-07-16 21:08
Hey @benzimmer I've noticed that Terraform functions properly if you make use of the Weighted record type (by setting weight = N in your resource).  Then terraform and AWS and everybody is happy.  Lets you have the two different resources pointing at the same record.

Perhaps give that a whirl?

**Comment by alexintel** [comment] 2015-09-15 23:21
+1

**Comment by catsby** [comment] 2016-06-09 15:31
Hello friends –

Route53 Records recently received a bit of an overhaul with regards to weighted, latency, geo location, and failover records in #6954. These new bits will be released in v0.7.0, which we have a release candidate available for. 

In the meantime, check out the docs for the upcoming features!

- https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/aws/r/route53_record.html.markdown

**Closed by catsby** 2016-06-09 15:31 UTC
Labels: enhancement, provider/aws

**Comment by ranrub** [comment] 2016-06-13 22:42
Hi @catsby , I tried with terraform 0.7 rc2, same behavior. route53 records with the same name which should be created side by side due to weighted routing policy, are overwriting eachother, so that only one is created eventually.

**Comment by catsby** [comment] 2016-06-14 20:04
Hey @ranrub, do you have a configuration that demonstrates this that I can use to debug?

**Comment by petestorey26** [comment] 2016-08-15 14:25
I've got the same issue - I'm trying to setup two A records for www.domain.com, one being PRIMARY and one SECONDARY for a failover, but one overwrites the other when applying, so if I 'apply', then immediately 'plan', I see it trying to reverse the changes it's just made (flip flopping between having a primary and secondary).

```
# www
resource "aws_route53_record" "www-kangocover-com-au" {
   zone_id = "${aws_route53_zone.kangocover.id}"
   name = "www.kangocover.com.au"
   type = "A"
   ttl = "600"
   health_check_id = "${aws_route53_health_check.nginx_a_health.id}"
   failover_routing_policy = {
       type = "PRIMARY"
   }
   set_identifier = "www-kango"
   records = ["${data.terraform_remote_state.main_config.nginx-a-ip}"]
} 

# www-failover
resource "aws_route53_record" "www-kangocover-com-au-2" {
   zone_id = "${aws_route53_zone.kangocover.id}"
   name = "www.kangocover.com.au"
   type = "A"
   ttl = "600"
   failover_routing_policy = {
       type = "SECONDARY"
   }
   set_identifier = "www-kango"
   records = ["${data.terraform_remote_state.main_config.nginx-b-ip}"]
}
```

...results in an apply of
```
aws_route53_record.kangocover-com-au-2: Modifying...
  failover_routing_policy.0.type: "PRIMARY" => "SECONDARY"
  health_check_id:                "a75c4d56-dbef-44bd-8635-03f01c885e78" => ""
  records.1991398507:             "52.63.219.47" => ""
  records.622985031:              "" => "52.62.227.36"
aws_route53_record.www-kangocover-com-au-2: Modifying...
  failover_routing_policy.0.type: "PRIMARY" => "SECONDARY"
  health_check_id:                "a75c4d56-dbef-44bd-8635-03f01c885e78" => ""
  records.1991398507:             "52.63.219.47" => ""
  records.622985031:              "" => "52.62.227.36"
```

which picks up the -2 resource twice, interestingly then plan results in
```
~ aws_route53_record.kangocover-com-au
    failover_routing_policy.0.type: "SECONDARY" => "PRIMARY"
    health_check_id:                "" => "a75c4d56-dbef-44bd-8635-03f01c885e78"
    records.1991398507:             "" => "52.63.219.47"
    records.622985031:              "52.62.227.36" => ""

~ aws_route53_record.www-kangocover-com-au
    failover_routing_policy.0.type: "SECONDARY" => "PRIMARY"
    health_check_id:                "" => "a75c4d56-dbef-44bd-8635-03f01c885e78"
    records.1991398507:             "" => "52.63.219.47"
    records.622985031:              "52.62.227.36" => ""
```

**Comment by petestorey26** [comment] 2016-08-15 14:33
Right, strike that (though might be useful for someone else..!):

I _thought_ the set_identifier was supposed to be the same for both of the records in the primary and secondary resources, but they should be different!  RTFM I suppose.  Perhaps could be made clear in the docs of https://www.terraform.io/docs/providers/aws/r/route53_record.html though.
