### ISSUE TITLE
Instance cannot be destroyed error prevents the output that allows to see what causes the instance destruction

### ISSUE THREAD

**Issue by ilya-scale** [hashicorp/terraform#31332] opened 2022-06-28 12:47 UTC
### Terraform Version

1.2.1

### Description

Right now when an instance is being destroyed, all we get in the console is `Error: Instance cannot be destroyed`. Since there can be multiple dependencies that lead to one of the property change that lead to instance being destroyed it is very non-obvious often why this is happening.

So perhaps terraform can be altered to instead of throwing this error at once generate a full plan that will show what causes this and only in the end add this error to the log so that both the plan and the error is visible (and not generate the plan file of course in this case).

**Comment by jbardin** [comment] 2022-06-28 13:34
Duplicate of #16392 and #30271

**Closed by jbardin** 2022-06-28 13:34 UTC
Labels: bug, new
