### ISSUE TITLE
Import aws_resource_groups_group

### ISSUE THREAD

**Issue by leedahl** [hashicorp/terraform#34452] opened 2023-12-22 17:38 UTC
### Terraform Version

```shell
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/aws...
- Finding latest version of hashicorp/template...
- Installing hashicorp/aws v5.31.0...
- Installed hashicorp/aws v5.31.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)
```

### Terraform Configuration Files

```terraform
import {
  to = aws_resourcegroups_group.hd_application
  id = data.aws_ssm_parameter.aws_application.value
}

resource "aws_resourcegroups_group" "hd_application" {
  name = "HD"
}
```

### Debug Output

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.terraform_remote_state.vpc: Reading...
data.aws_iam_instance_profile.batch_instance_role: Reading...
data.aws_iam_role.batch_role: Reading...
data.aws_ssm_parameter.efs_id: Reading...
data.aws_iam_role.spot_fleet_role: Reading...
data.aws_ssm_parameter.aws_application: Reading...
data.aws_ami.blue-hd-batch-ami: Reading...
data.aws_ami.green-hd-batch-ami: Reading...
data.aws_iam_policy_document.spot-fleet-role-doc[0]: Reading...
data.aws_iam_policy_document.batch-admin-role-doc[0]: Reading...
data.aws_iam_policy_document.spot-fleet-role-doc[0]: Read complete after 0s [id=296567195]
data.aws_iam_policy_document.batch-assume-role-doc[0]: Reading...
data.aws_iam_policy_document.batch-assume-role-doc[0]: Read complete after 0s [id=1558451045]
data.aws_iam_policy.spot_fleet_tagging_policy[0]: Reading...
data.aws_iam_policy_document.batch-admin-role-doc[0]: Read complete after 0s [id=3731193336]
data.terraform_remote_state.vpc: Read complete after 0s
data.aws_ssm_parameter.aws_application: Read complete after 1s [id=/HDTools/devint/awsApplication]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 986 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2c1da20?, 0x3994900?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:920 +0x270
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.AsString({{{0x39d4a70?, 0xc0001a94c9?}}, {0x2ebd840?, 0xc00403f5a8?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/value_ops.go:1385 +0x47
github.com/zclconf/go-cty/cty/gocty.fromCtyString({{{0x39d4a70?, 0xc0001a94c9?}}, {0x2ebd840?, 0xc00403f5a8?}}, {0x2c1da20?, 0xc0066c4120?, 0xc003fd1440?}, {0xc0028c6d10, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/gocty/out.go:245 +0x5f
github.com/zclconf/go-cty/cty/gocty.fromCtyValue({{{0x39d4a70, 0xc0001a94c9}}, {0x2ebd840, 0xc00403f5a8}}, {0x2b891a0?, 0xc0066c4120?, 0x410785?}, {0xc0028c6d10, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/gocty/out.go:87 +0x70b
github.com/zclconf/go-cty/cty/gocty.FromCtyValue({{{0x39d4a70?, 0xc0001a94c9?}}, {0x2ebd840?, 0xc00403f5a8?}}, {0x2b891a0?, 0xc0066c4120?})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/gocty/out.go:43 +0xca
github.com/hashicorp/terraform/internal/terraform.evaluateImportIdExpression({0x39d4f78, 0xc0007fbc80}, {0x39f2880?, 0xc000a500e0?})
	/home/runner/work/terraform/terraform/internal/terraform/eval_import.go:57 +0x35a
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc003d6a790, {0x39f2880, 0xc000a500e0})
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:168 +0x476
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x7f613c02dbb0?, {0x39f2880?, 0xc000a500e0?}, 0x0?)
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:74 +0x8a
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0063466c0, {0x39f2880, 0xc000a500e0}, {0x7f613c7eefe8, 0xc003d6a790})
	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x31f3420, 0xc003d6a790})
	/home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000953740, {0x31f3420, 0xc003d6a790}, 0xc003fdb900)
	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 862
	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8
time=2023-12-22T17:31:35Z level=error msg=terraform invocation failed in /home/ubuntu/workspace/ContentHubHD/HD.Infrastructure.BaseAmi-V2/commdata-live-01/mx-content-ap-dev-01/us-east-1/dev/services/devint/HDTools-Build-Batch-Compute/.terragrunt-cache/uANcUOYOHX0qGdYjxdVFi0Kq4L0/wNwxoYngZUdpodujXR8kyNDjbZw prefix=[/home/ubuntu/workspace/ContentHubHD/HD.Infrastructure.BaseAmi-V2/commdata-live-01/mx-content-ap-dev-01/us-east-1/dev/services/devint/HDTools-Build-Batch-Compute] 
time=2023-12-22T17:31:35Z level=error msg=1 error occurred:
	* [/home/ubuntu/workspace/ContentHubHD/HD.Infrastructure.BaseAmi-V2/commdata-live-01/mx-content-ap-dev-01/us-east-1/dev/services/devint/HDTools-Build-Batch-Compute/.terragrunt-cache/uANcUOYOHX0qGdYjxdVFi0Kq4L0/wNwxoYngZUdpodujXR8kyNDjbZw] exit status 11

### Expected Behavior

Update the import block

### Actual Behavior

Crashed

### Steps to Reproduce

1. terraform init
2. terraform plan

**Comment by jbardin** [comment] 2023-12-22 18:50
Hi @leedahl,

Are you certain you are using the latest Terraform release? This appears at first glance to be a duplicate of #33977.

**Comment by leedahl** [comment] 2023-12-22 20:13
I think it may be user error as I thing I may have had the wrong value for id.  Anyway, what I wanted to do was create and AWS Application with resource groups.  I don't think terraform currently supports the Service Catalog AppRegistry function.  You can probably close this ticket.

**Comment by jbardin** [comment] 2023-12-22 20:19
Thanks @leedahl. A panic is always a bug in Terraform, so if you can reproduce this in a current release, feel free to reply here and we can try and debug this further.

Thanks!

**Closed by jbardin** 2023-12-22 20:19 UTC
Labels: bug, new
