### ISSUE TITLE
Enable Mono Infrastructure Repositories

### ISSUE THREAD

**Issue by simwak** [hashicorp/terraform#28768] opened 2021-05-20 14:25 UTC
### Current Terraform Version
```
Terraform v0.15.3
on linux_amd64
```

### Use-cases
If you have a repository with terraform files with a pipeline, you can simply comment out a resource, for example a "aws_route53_record".  This resource will be deleted as expected when the pipeline triggers `terraform apply`.

We now want one repository with our whole infrastructure in one state, so all clusters, DNS, VMs etc. We are using modules to reference to different repositories with templates for for example a EKS cluster. If we define the module with the EKS cluster template we can set all nessarary values with no effort. That's also the case for the AWS provider (region). With the decision that providers should only be in the root module, we need to extract it and double these in the mono repo for each cluster, as they can be in different regions which is again more effort as needed. But that's not possible with the Helm provider, as the Helm provider needs the credentials from the freshly created EKS cluster. We now output these credentials from the module and reference it in a Helm provider in the root module. But because the Helm provider now references the module and the module references the Helm provider, we are unable to delete them with terraform apply. We need to manually execute "terraform destroy -target module.eks-cluster" which is not ideal for a pipeline.

**At the current state, mono infrastructure repos are not possible with providers that have resource specific data (e.g. credentials).**

### Attempted Solutions
Our solution would be a custom Helm provider which sets the credentials in the `helm_release` resource instead of the provider, so we don't need to define the provider somewhere in our `.tf` files and only have them in `required_providers`.

### Proposal
Completely removing the `provider` block and setting these values in the resources or make providers in modules possible, so we can delete a module even if the provider is not defined anymore as we are able to do with normal resources.

### References
Currently none.

**Comment by jbardin** [comment] 2021-05-20 20:18
Hi @simwak,

Thanks for the proposal. Terraform itself doesn't enforce what a provider requires for it's configuration, and what you propose is possible with providers currently, it's just usually inconvenient from a users perspective to set individual credentials for each resource and not generally done. 

The desire to be able to combine multiple layers of configuration into a since configuration where providers depend on other resources is well known, and we are using issue #4149 to track some possible solutions to that. Since the proposed solution here is not something we can change in Terraform itself, and this use case is something we are following up on in the linked issue, I'm going to close this as a duplicate of #4149.

Thanks!

**Closed by jbardin** 2021-05-20 20:18 UTC
Labels: enhancement, new
