### ISSUE TITLE
untaint command not working on command line

### ISSUE THREAD

**Issue by phanindra2407** [hashicorp/terraform#16977] opened 2017-12-22 20:24 UTC
Hello @ketzacoatl @phinze @jbardin @svanharmelen 

 I am working with terraform 0.10.7

I am trying to untaint a null resource in my module.
My folder structure as below

Aurora-db
|
|-----aurora_db.tf
modules
|
|----aurora_db.tf

module "aurora" {
  source = "../modules/aurora_db"

}
in module i have a resource as follow

resource "null_resource"  "framework_exec" {

}
it is tainted and run everytime other resources are updated , so i wanted to untaint this resource . I used
sh "terrafor init.............."
 sh "terraform untaint -no-color -module=aurora_db null_resource.framework_exec"
sh "terraform plan ..............."
sh "terraform apply ................."

it gave me the error as

 [31mThe untaint command expects exactly one argument.[0m[0m
[31mUsage: terraform untaint [options] name

Please let me know whatcould be the issue here

**Comment by tombuildsstuff** [comment] 2018-01-03 09:52
Hey @phanindra2407 

Thanks for opening this issue.

Taking a look at the code in the `aurora_db.tf` in the root:

```
module "aurora" {
  source = "../modules/auroradb"
}
```

The `taint` and `untaint` commands use the friendly name for the module, which in this case is `aurora`. As such you should be able to use the following commands to taint and untaint respectively:

```
$ terraform taint -module=aurora null_resource.framework_exec
The resource null_resource.framework_exec in the module root.aurora has been marked as tainted!
```

```
$ terraform untaint -module=aurora null_resource.framework_exec
The resource null_resource.framework_exec in the module root.aurora has been successfully untainted!
```

I'm going to close this issue for the moment (since it's a question and not a bug in Terrafom) - however would you be able to confirm if that solves your issue?

Thanks!

**Closed by tombuildsstuff** 2018-01-03 09:52 UTC
Labels: question

**Comment by phanindra2407** [comment] 2018-01-05 19:00
@tombuildsstuff  sorry for the late reply , it worked thank you
