### ISSUE TITLE
Allow custom environment variable mapping in variable block

### ISSUE THREAD

**Issue by zpatrick** [hashicorp/terraform#11296] opened 2017-01-19 21:22 UTC
It would be nice to allow an optional override of the default `TF_VAR_` environment variable mapping inside the `variable` block:

```
variable "endpoint" {
  default = "abc"
  env     = "ENDPOINT"
}
```

My use case: It becomes tedious keeping multiple environment variables in sync when working with terraform + another tool (or set of tools) that use environment variables for configuration. Today, I need to make sure `ENDPOINT=abc` is set for tool x, and `TF_VAR_endpoint=abc` is set for terraform. Allowing this override would remove this (albeit small) pain point.

I'd be happy to tackle this feature - but first wanted to get input from some of the core members in case this has deeper implications I'm not seeing.

**Comment by grubernaut** [comment] 2017-01-20 15:42
Duplicate of #62, closing for now. I believe @mitchellh may have more to add, but it's definitely a topic that's talked about internally quite often. There are still a few core issues with adding environment variable interpolation at this stage. It's definitely something we wish to target in the future, as it's a heavily requested feature. Thanks!

**Closed by grubernaut** 2017-01-20 15:42 UTC
