### ISSUE TITLE
Add AWS API Gateway Usage Plan support

### ISSUE THREAD

**Issue by przemos** [hashicorp/terraform#11022] opened 2017-01-04 10:51 UTC
Hi,

API Gateway is evolving really fast and new features are arriving at a quick pace. One of the abilities usage plan provides and is quite important is securing your API with a key. 

http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-usage-plans-with-rest-api.html

Would it be possible to add support for defining usage plans?

**Comment by sebolabs** [comment] 2017-01-11 16:02
+1

**Comment by madpawel** [comment] 2017-01-11 18:31
+1

**Comment by ianxharris** [comment] 2017-01-11 18:43
+1

**Comment by wbadowski** [comment] 2017-01-12 08:18
+1

**Comment by svanzoest** [comment] 2017-01-15 01:57
relates to #8532

**Comment by stack72** [comment] 2017-02-08 15:41
Hi all

This is a duplicate of #8532

Going to close this one and direct all requested etc to that issue

Thanks

Paul

**Closed by stack72** 2017-02-08 15:41 UTC
Labels: enhancement, provider/aws
