### ISSUE TITLE
provisioner "chef" stop working in v 0.11.5 

### ISSUE THREAD

**Issue by binlialfie** [hashicorp/terraform#17703] opened 2018-03-27 10:31 UTC
### Terraform Version

```
terraform -v
Terraform v0.11.5

terraform -v
Terraform v0.11.0
+ provider.aws v1.12.0
+ provider.chef v0.1.0
+ provider.null v1.0.0
+ provider.random v1.1.0

Your version of Terraform is out of date! The latest version
is 0.11.5. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files

```hcl

```

### Actual Behavior

my chef bootstrap works well in v0.11.0 with own cookbook, I can see everything (chef node register, chef-client install, and chef-client run) happening when I run `terraform apply`

once update to v0.11.5, running exactly the same code (TF and chef cookbooks), 

module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef): Connecting to remote host via SSH...
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef):   Host: [35.178.60.2]
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef):   User: centos
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef):   Password: false
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef):   Private key: true
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef):   SSH Agent: true
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef):   Checking Host Key: false
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef): Connected!
module.newProj.aws_volume_attachment.spot_exsit_ebs-attachment (chef): Cleanup user key...

then whole process stops, no chef bootstrap running/debugging notes, no node registration, install, run....

I then revert back to v0.11.0, chef bootstrap working again......

### Steps to Reproduce

you can reproduce the issue as described above.

**Comment by jbardin** [comment] 2018-03-27 14:45
Hi @binlialfie,

Thanks for filing the issue. This looks to be a duplicate of #17638, which should be fixed in master.

**Closed by jbardin** 2018-03-27 14:45 UTC
