### ISSUE TITLE
panic occurs when nested object declared in schema

### ISSUE THREAD

**Issue by yufeiminds** [hashicorp/terraform#29538] opened 2021-09-06 07:29 UTC
### Module version

```
➜ terraform -version
Terraform v1.0.6
on darwin_amd64
+ provider hashicorp.com/edu/hashicups v0.3.2
```

### Relevant provider source code

```go
// Order Resource schema
func (r resourceOrderType) GetSchema(_ context.Context) (schema.Schema, []*tfprotov6.Diagnostic) {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": {
				Type: types.StringType,
				// When Computed is true, the provider will set value --
				// the user cannot define the value
				Computed: true,
			},
			"last_updated": {
				Type:     types.StringType,
				Computed: true,
			},
			"items": {
				// If Required is true, Terraform will throw error if user
				// doesn't specify value
				// If Optional is true, user can choose to supply a value
				Required: true,
				Attributes: schema.ListNestedAttributes(map[string]schema.Attribute{
					"quantity": {
						Type:     types.NumberType,
						Required: true,
					},
					"coffee": {
						Required: true,
						Attributes: schema.SingleNestedAttributes(map[string]schema.Attribute{
							"id": {
								Type:     types.NumberType,
								Required: true,
							},
							"name": {
								Type:     types.StringType,
								Computed: true,
							},
							"teaser": {
								Type:     types.StringType,
								Computed: true,
							},
							"description": {
								Type:     types.StringType,
								Computed: true,
							},
							"price": {
								Type:     types.NumberType,
								Computed: true,
							},
							"image": {
								Type:     types.StringType,
								Computed: true,
							},
							"ingredients": {
								Optional: true,
								Attributes: schema.ListNestedAttributes(map[string]schema.Attribute{
									"ingredient_id": {
										Type:     types.NumberType,
										Optional: true,
									},
									"name": {
										Type:     types.StringType,
										Optional: true,
									},
									"quantity": {
										Type:     types.NumberType,
										Optional: true,
									},
									"unit": {
										Type:     types.StringType,
										Optional: true,
									},
								}, schema.ListNestedAttributesOptions{}),
							},
						}),
					},
				}, schema.ListNestedAttributesOptions{}),
			},
		},
	}, nil
}
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    hashicups = {
      version = "~> 0.3.1"
      source  = "hashicorp.com/edu/hashicups"
    }
  }
}
provider "hashicups" {
  username = "education"
  password = "test123"
  host     = "http://localhost:19090"
}

resource "hashicups_order" "edu" {
  items = [{
    coffee = {
      id = 3

      ingredients = [{
        name = "sugar"
      }]

    }
    quantity = 2
    }, {
    coffee = {
      id = 1
    }
    quantity = 2
    }
  ]
}

output "edu_order" {
  value = hashicups_order.edu
}

```

### Debug Output

[Crash Log on Gist](https://gist.github.com/yufeiminds/67973778e3c0f700f960013eaed3dc1e#file-crash-951271563-log)

### Expected Behavior

No crash for nested objects.

### Actual Behavior

```
hashicups_order.edu: Refreshing state... [id=1]
panic: inconsistent list element types (cty.Object(map[string]cty.Type{"coffee":cty.Object(map[string]cty.Type{"description":cty.String, "id":cty.Number, "image":cty.String, "ingredients":cty.List(cty.Object(map[string]cty.Type{"ingredient_id":cty.Number, "name":cty.String, "quantity":cty.Number, "unit":cty.String})), "name":cty.String, "price":cty.Number, "teaser":cty.String}), "quantity":cty.Number}) then cty.Object(map[string]cty.Type{"coffee":cty.Object(map[string]cty.Type{"description":cty.String, "id":cty.Number, "image":cty.String, "ingredients":cty.List(cty.ObjectWithOptionalAttrs(map[string]cty.Type{"ingredient_id":cty.Number, "name":cty.String, "quantity":cty.Number, "unit":cty.String}, []string{"ingredient_id", "name", "quantity", "unit"})), "name":cty.String, "price":cty.Number, "teaser":cty.String}), "quantity":cty.Number}))

goroutine 131 [running]:
github.com/zclconf/go-cty/cty.ListVal(0xc0003569c0, 0x2, 0x2, 0x2f88240, 0xc00039cfc0, 0x37babf8, 0xc000353940)
	/Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.9.1/cty/value_init.go:166 +0x57e
github.com/hashicorp/terraform/internal/plans/objchange.proposedNewNestedType(0xc0004704e0, 0x37bab88, 0xc000353c00, 0x2e66040, 0xc00000e2b8, 0x37bab88, 0xc000353a00, 0x2e66040, 0xc00000e288, 0xc00000e288, ...)
	/Users/distiller/project/project/internal/plans/objchange/objchange.go:346 +0x6d3
github.com/hashicorp/terraform/internal/plans/objchange.proposedNewAttributes(0xc000907380, 0x37babf8, 0xc000353c10, 0x2f88240, 0xc00039cc00, 0x37babf8, 0xc000353a30, 0x2f88240, 0xc00039c990, 0x0)
	/Users/distiller/project/project/internal/plans/objchange/objchange.go:295 +0x49a
github.com/hashicorp/terraform/internal/plans/objchange.proposedNew(0xc0009073e0, 0x37babf8, 0xc000353c10, 0x2f88240, 0xc00039cc00, 0x37babf8, 0xc000353a30, 0x2f88240, 0xc00039c990, 0x20, ...)
	/Users/distiller/project/project/internal/plans/objchange/objchange.go:80 +0x165
github.com/hashicorp/terraform/internal/plans/objchange.ProposedNew(0xc0009073e0, 0x37babf8, 0xc000353c10, 0x2f88240, 0xc00039cc00, 0x37babf8, 0xc000353a30, 0x2f88240, 0xc00039c990, 0x0, ...)
	/Users/distiller/project/project/internal/plans/objchange/objchange.go:42 +0x11f
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc000737340, 0x37ec5a0, 0xc0001d2b60, 0x0, 0xc0003dfa40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/distiller/project/project/internal/terraform/node_resource_abstract_instance.go:732 +0xdab
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0002f90e0, 0x37ec5a0, 0xc0001d2b60, 0x100c408, 0x32fd020, 0xc000a1bc50)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:196 +0x8cb
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0xc0002f90e0, 0x37ec5a0, 0xc0001d2b60, 0xd6ddc02, 0xc000a1bce8, 0x100d305, 0x2fd3580)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:54 +0xb3
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0006588f0, 0x37ec5a0, 0xc0001d2b60, 0xd6ddc30, 0xc0002f90e0, 0x0, 0x0, 0x0)
	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:129 +0xbf
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1(0x32fd020, 0xc0002f90e0, 0x0, 0x0, 0x0)
	/Users/distiller/project/project/internal/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0003df200, 0x32fd020, 0xc0002f90e0, 0xc0006d32c0)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0x1246




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.951271563.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.951271563.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce

Pre-requirements: Start the hashicups server according to []

1. Clone my fork: [yufeiminds/terraform-provider-hashicups-pf](https://github.com/yufeiminds/terraform-provider-hashicups-pf)
2. `make install`
3. `cd examples && terraform init`
4. `terraform apply`
5. See the panic that occurs

### References

- https://github.com/hashicorp/terraform/issues/27275
- https://github.com/hashicorp/terraform/issues/27269
- https://github.com/hashicorp/terraform/issues/26195
- https://github.com/hashicorp/terraform/issues/28171

**Comment by yufeiminds** [comment] 2021-09-08 05:21
Okay, thank you, Paddy.

**Comment by jbardin** [comment] 2021-09-08 16:00
Hi @yufeiminds,

Thanks for filing the issue with the complete example. While I am amble to reproduce a similar panic with the given provider and config, I cannot reproduce the same issue as shown here.

The stack trace I'm getting looks like the result of incorrect data coming back from the provider, which would need to be fixed in the SDK. The stack trace in this issue is different however, and appears to be the result of terraform incorrectly decoding the config or existing state which we would like to fix here too.

Can you confirm if there is any existing state in your local reproduction, or if there are any other steps you may have taken outside of the shat is shown above?

Thanks!

**Comment by yufeiminds** [comment] 2021-09-09 07:23
Thanks for your reply.

I had removed state files and re-exec `make`, `terraform init` and `terraform plan`. It still crashed. 

Here are my all steps:

```shell
# Build provider
git clone git@github.com:yufeiminds/terraform-provider-hashicups-pf.git
cd terraform-provider-hashicups-pf
make

# Setup server
cd docker_compose && docker-compose up -d && cd -
curl -X POST localhost:19090/signup -d '{"username":"education", "password":"test123"}'
export HASHICUPS_TOKEN="token at previous step"

# Execute Plan
cd examples
terraform init
terraform plan
```

**Comment by jbardin** [comment] 2021-09-09 13:41
Thanks for added details @yufeiminds!

That still leaves me with a different stack trace than shown above, triggered during the decoding of the provider response:

```
panic: inconsistent list element types (cty.Object(map[string]cty.Type{"coffee":cty.Object(map[string]cty.Type{"description":cty.String, "id":cty.Number, "image":cty.String, "ingredients":cty.List(cty.Object(map[string]cty.Type{"ingredient_id":cty.Number, "name":cty.String, "quantity":cty.Number, "unit":cty.String})), "name":cty.String, "price":cty.Number, "teaser":cty.String}), "quantity":cty.Number}) then cty.Object(map[string]cty.Type{"coffee":cty.Object(map[string]cty.Type{"description":cty.String, "id":cty.Number, "image":cty.String, "ingredients":cty.List(cty.ObjectWithOptionalAttrs(map[string]cty.Type{"ingredient_id":cty.Number, "name":cty.String, "quantity":cty.Number, "unit":cty.String}, []string{"ingredient_id", "name", "quantity", "unit"})), "name":cty.String, "price":cty.Number, "teaser":cty.String}), "quantity":cty.Number}))

goroutine 118 [running]:
github.com/zclconf/go-cty/cty.ListVal({0x14000737780, 0x2, 0x2})
	/Users/jbardin/go/pkg/mod/github.com/zclconf/go-cty@v1.9.1/cty/value_init.go:166 +0x4e4
github.com/zclconf/go-cty/cty/msgpack.unmarshalList(0x14000796768, {{0x102a4bf70, 0x140009f8fc0}}, {0x14000a83210, 0x1, 0x1})
	/Users/jbardin/go/pkg/mod/github.com/zclconf/go-cty@v1.9.1/cty/msgpack/unmarshal.go:161 +0x4e8
github.com/zclconf/go-cty/cty/msgpack.unmarshal(0x14000796768, {{0x102a4bf00, 0x140009f8fd0}}, {0x14000a83210, 0x1, 0x1})
	/Users/jbardin/go/pkg/mod/github.com/zclconf/go-cty@v1.9.1/cty/msgpack/unmarshal.go:52 +0x464
github.com/zclconf/go-cty/cty/msgpack.unmarshalObject(0x14000796768, 0x14000b566f0, {0x0, 0x0, 0x0})
	/Users/jbardin/go/pkg/mod/github.com/zclconf/go-cty@v1.9.1/cty/msgpack/unmarshal.go:297 +0x500
github.com/zclconf/go-cty/cty/msgpack.unmarshal(0x14000796768, {{0x102a4bf70, 0x14000a83200}}, {0x0, 0x0, 0x0})
	/Users/jbardin/go/pkg/mod/github.com/zclconf/go-cty@v1.9.1/cty/msgpack/unmarshal.go:60 +0x6b4
github.com/zclconf/go-cty/cty/msgpack.Unmarshal({0x14000398200, 0xf7, 0x100}, {{0x102a4bf70, 0x14000a83200}})
	/Users/jbardin/go/pkg/mod/github.com/zclconf/go-cty@v1.9.1/cty/msgpack/unmarshal.go:22 +0xc8
github.com/hashicorp/terraform/internal/plugin6.decodeDynamicValue(0x14000123bc0, {{0x102a4bf70, 0x14000a83200}})
	/Users/jbardin/terraform/internal/plugin6/grpc_provider.go:612 +0xcc
github.com/hashicorp/terraform/internal/plugin6.(*GRPCProvider).PlanResourceChange(0x14000899a80, {{0x140004e9b80, 0xf}, {{{0x102a4bf70, 0x140009f8ce0}}, {0x0, 0x0}}, {{{0x102a4bf70, 0x140009f9830}}, {0x10266f620, ...}}, ...})
	/Users/jbardin/terraform/internal/plugin6/grpc_provider.go:426 +0x724
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0x140009f2000, {0x102aadf20, 0x140002902a0}, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0})
	/Users/jbardin/terraform/internal/terraform/node_resource_abstract_instance.go:755 +0xdac
...
```

The panic message however is the similar, and will have a related root cause. It seems that the response from the provider is not properly encoded, however that should only result in an error, not a panic, so we need to fix that in the cty package too.

I would really like to get a reproduction of the original stack trace shown above too, so if you have any more details there it would be a great help. Now that the class of error is evident, we may be able to uncover where the error lies in Terraform by manually auditing the code too.

Thanks!

**Comment by jbardin** [comment] 2021-09-09 21:25
OK, I think I have a handle on the full scope here, and can narrow this down completely to the core implementation. Not only will the fix take care of the panic shown above, it should also completely rule out the original panic so there is no need to investigate further. Once we have a fix in place we can do some more tests with the plugin framework to verify the results.

**Comment by yufeiminds** [comment] 2021-09-10 03:25
Thanks a lot. I look forward to your fixes. Any more questions, please let me know. 🤝

**Closed** 2021-09-13 12:58 UTC
Labels: bug, core, crash, config

**Comment by yufeiminds** [comment] 2021-09-17 10:20
It is worked for me. Thanks a lot.
