### ISSUE TITLE
Panic on remote backend

### ISSUE THREAD

**Issue by dadgar** [hashicorp/terraform#24822] opened 2020-04-30 17:31 UTC
### Terraform Version
```
0.12.24
```

### Terraform Configuration Files
Not sure it is relevant for this error. Can probably get if needed

### Debug Output
Wasn't able to reproduce to have debug output

### Crash Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1015b4b]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote.(*Remote).Operation(0xc0005544d0, 0x236e180, 0xc0000d8078, 0xc0003d2000, 0x8709e5, 0x1bfeb20, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/remote/backend.go:673 +0x3eb
github.com/hashicorp/terraform/command.(*Meta).RunOperation(0xc00038c380, 0x7f2a2e413288, 0xc0005544d0, 0xc0003d2000, 0x1, 0x1, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/meta.go:285 +0x83
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc00038c380, 0xc0000e8020, 0x3, 0x3, 0xc0000c2590)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/apply.go:203 +0xe7c
github.com/mitchellh/cli.(*CLI).Run(0xc000124640, 0xc000124640, 0xc00053bd90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:239 +0xc33
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:103 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:39 +0x3b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Exited with code exit status 2
```

Wasn't able to capture the crash log unfortunately.

### Expected Behavior
A normal Terraform Apply

### Actual Behavior
Terraform panicked. 

### Steps to Reproduce
Terraform apply using TFC for state storage.

### Additional Context
Terraform plan was run before and it did not fail.

**Comment by danieldreier** [comment] 2020-04-30 17:45
Hi @dadgar - thanks for reporting this. I think this is probably a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. 

Here's what I did to try and reproduce this:
```hcl
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "danieldreier"

    workspaces {
      name = "gh24822"
    }
  }
}

resource "null_resource" "cluster" {
  provisioner "local-exec" {
    command = "echo 'hello world'"
  }
}
```

I already had my credentials in a config file, so I ran an init and an apply:
```
terraform init
Initializing the backend...
Do you want to copy existing state to the new backend?
  Pre-existing state was found while migrating the previous "local" backend to the
  newly configured "remote" backend. No existing state was found in the newly
  configured "remote" backend. Do you want to copy this state to the new "remote"
  backend? Enter "yes" to copy and "no" to start with an empty state.

  Enter a value: yes

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.null: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
src/repro/24822 took 3s
```

I ran another apply after that to confirm and got the same successful output.

As-is, I don't know what you're doing differently from me to reproduce this error, and so I'm stuck. Can you please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies.

**Comment by dzirg44** [comment] 2020-05-01 21:02
have the same
```
Terraform v0.12.24
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
+ provider.tls v2.1.1
+ provider.vault v2.10.0
```
OS - macosx
but in my case it happens only when i use HTTP_PROXY env variables
```
2020/05/01 23:48:16 [DEBUG] checking for provisioner in "."
2020/05/01 23:48:16 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/05/01 23:48:16 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2020/05/01 23:48:16 [DEBUG] checking for provisioner in "/Users/myuser/.terraform.d/plugins"
2020/05/01 23:48:16 [DEBUG] checking for provisioner in "/Users/myuser/.terraform.d/plugins/darwin_amd64"
2020/05/01 23:48:16 [TRACE] Meta.Backend: backend *remote.Remote supports operations
2020/05/01 23:48:17 [INFO] backend/local: starting Apply operation
2020/05/01 23:48:17 [TRACE] backend/local: requesting state manager for workspace "default"
2020/05/01 23:48:17 [TRACE] backend/local: requesting state lock for workspace "default"
2020/05/01 23:48:17 [TRACE] backend/local: reading remote state for workspace "default"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1bf609d]

goroutine 120 [running]:
github.com/hashicorp/terraform/backend/remote.(*Remote).retryLogHook(0xc0002211e0, 0x1, 0x0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/backend/remote/backend.go:492 +0x8d
github.com/hashicorp/go-tfe.(*Client).retryHTTPBackoff(0xc0003fe000, 0x5f5e100, 0x17d78400, 0x1, 0x0, 0xc0001330e0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/pkg/mod/github.com/hashicorp/go-tfe@v0.3.27/tfe.go:252 +0xd3
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000051980, 0xc000260da0, 0xc0000ca070, 0x1, 0x0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.5.2/client.go:440 +0x1bf
github.com/hashicorp/go-tfe.(*Client).do(0xc0003fe000, 0x2ee90a0, 0xc0000ca070, 0xc000260da0, 0x29e39e0, 0xc00003af60, 0x0, 0x0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/pkg/mod/github.com/hashicorp/go-tfe@v0.3.27/tfe.go:427 +0x174
github.com/hashicorp/go-tfe.(*stateVersions).Download(0xc00000e170, 0x2ee90a0, 0xc0000ca070, 0xc000786480, 0x220, 0xc00027a150, 0x0, 0x0, 0x58, 0x200)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/pkg/mod/github.com/hashicorp/go-tfe@v0.3.27/state_version.go:214 +0x1bb
github.com/hashicorp/terraform/backend/remote.(*remoteClient).Get(0xc0000c8200, 0xc0001a77d0, 0x10ecdea, 0x0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/backend/remote/backend_state.go:38 +0x1f7
github.com/hashicorp/terraform/state/remote.(*State).refreshState(0xc00057e0f0, 0xc0001a78e8, 0x10edce0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/state/remote/state.go:95 +0x38
github.com/hashicorp/terraform/state/remote.(*State).RefreshState(0xc00057e0f0, 0x0, 0x0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/state/remote/state.go:88 +0x79
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc000490a90, 0xc000270000, 0x1, 0x1, 0x3, 0xc00021a300, 0x1, 0x3, 0x57)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/backend/local/backend_local.go:53 +0x4c4
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc000490a90, 0x2ee9060, 0xc000482200, 0x2ee9060, 0xc000482340, 0xc000270000, 0xc000482180)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/backend/local/backend_apply.go:53 +0x302
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc00024c1c0, 0xc00024c1d0, 0xc00024c1e0, 0xc000270000, 0xc000490a90, 0xc000482180, 0xc00024c1b0, 0x2ee9060, 0xc000482200, 0x2ee9060, ...)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/backend/local/backend.go:350 +0x1c0
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/backend/local/backend.go:334 +0x366
```
also i have another terraform configuration with HTTP_PROXY but this configuration works.

**Comment by danieldreier** [comment] 2020-05-02 00:46
@dzirg44 thanks for reporting that error! I took a look at your log output, and it that looks to me like a different failure mode. In @dadgar's original error report, it fails with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1015b4b]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote.(*Remote).Operation(0xc0005544d0, 0x236e180, 0xc0000d8078, 0xc0003d2000, 0x8709e5, 0x1bfeb20, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/remote/backend.go:673 +0x3eb
```

in yours, it's failing with:
```
2020/05/01 23:48:17 [TRACE] backend/local: reading remote state for workspace "default"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1bf609d]

goroutine 120 [running]:
github.com/hashicorp/terraform/backend/remote.(*Remote).retryLogHook(0xc0002211e0, 0x1, 0x0)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/backend/remote/backend.go:492 +0x8d

``` 
@dadgar's crash is failing on `remote.(*Remote).Operation` whereas yours is failing on `remote.(*Remote).retryLogHook`. You can also see that the errors are at different lines in `backend.go`. Since these will likely have different fixes, it will confuse troubleshooting to investigate them both on one issue.

@dzirg44 can you please open a different GitHub issue report and move your issue there?

**Comment by dzirg44** [comment] 2020-05-02 05:18
@danieldreier , sure.

**Comment by danieldreier** [comment] 2020-05-13 19:04
@dadgar have you seen this issue come up again?

**Comment by dadgar** [comment] 2020-05-13 19:34
@danielbryantuk No, not that I am aware of.

**Comment by danielbryantuk** [comment] 2020-05-14 09:11
Hi @dadgar, I think you tagged me by mistake :-)

**Comment by dadgar** [comment] 2020-05-14 12:39
@danielbryantuk Sorry about that!

**Comment by danieldreier** [comment] 2020-06-15 23:56
@dadgar I'm going to close this, because without a reproduction case, there just isn't enough information available to work on this, and having in-actionable crashes makes it harder for our engineers to find workable issues. I do still believe that this is a real issue, and I suspect that https://github.com/hashicorp/terraform/issues/24971 is the same.

If you run into this again, please do reach out and let me know, especially if you can reproduce it. I suspect that there is a transient network issue that terraform reacts to poorly, based on the other issue report, but it's very hard to build reproduction cases for issues like that.

**Closed by danieldreier** 2020-06-15 23:56 UTC
Labels: backend/remote, bug, crash, v0.12
