### ISSUE TITLE
plan operation: Real and shadow diffs do not match!

### ISSUE THREAD

**Issue by rata** [hashicorp/terraform#10222] opened 2016-11-18 15:22 UTC
Hi there,

### Terraform Version
Terraform v0.7.11. Also happened in 0.7.10

### Affected Resource(s)
- aws_eip

But it had happened with several other resources too.

### Panic Output
```
+ module.app11_agenda.aws_eip.static_ip
    allocation_id:     "<computed>"
    association_id:    "<computed>"
    domain:            "<computed>"
    instance:          "i-085e0bbdfd1b26b95"
    network_interface: "<computed>"
    private_ip:        "<computed>"
    public_ip:         "<computed>"
    vpc:               "true"


Plan: 1 to add, 0 to change, 0 to destroy.
Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!

You can report an issue at: https://github.com/hashicorp/terraform/issues

1 error(s) occurred:

* plan operation: Real and shadow diffs do not match! Real diff:

module.app11_agenda:
  CREATE: aws_eip.static_ip
    allocation_id:     "" => "<computed>"
    association_id:    "" => "<computed>"
    domain:            "" => "<computed>"
    instance:          "" => "i-085e0bbdfd1b26b95"
    network_interface: "" => "<computed>"
    private_ip:        "" => "<computed>"
    public_ip:         "" => "<computed>"
    vpc:               "" => "true" (forces new resource)
module.search.search:

Shadow diff:

module.app11_agenda:
  CREATE: aws_eip.static_ip
    allocation_id:     "" => "<computed>"
    association_id:    "" => "<computed>"
    domain:            "" => "<computed>"
    instance:          "" => "i-085e0bbdfd1b26b95"
    network_interface: "" => "<computed>"
    private_ip:        "" => "<computed>"
    public_ip:         "" => "<computed>"
    vpc:               "" => "true" (forces new resource)


This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.
```

Let me know if you want me to test some version to see if this stop happening, or how I can help. Thanks!

**Comment by rata** [comment] 2016-11-18 15:28
Here there is another example, using a dyn_record, in case it helps:

```
* plan operation: Real and shadow diffs do not match! Real diff:

module.app11_agenda:
  UPDATE: dyn_record.hostname
    value: "54.146.44.63" => "IPX"
module.search.search:

Shadow diff:

module.app11_agenda:
  UPDATE: dyn_record.hostname
    value: "54.146.44.63" => "IPX"



This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.
```
(replaced the new IP with "IPX", but it is the same IP address the two times)

**Comment by harshal-shah** [comment] 2016-11-19 14:06
I am also getting similar message on 0.7.11 version of terraform. 

~~~
2 error(s) occurred:

* plan operation: Real and shadow states do not match! Real state:

google_compute_firewall.default:
  ID = tf-k8s-firewall
  allow.# = 2
  allow.1050511137.ports.# = 4
~~~

**Comment by mitchellh** [comment] 2016-11-23 17:27
@rata What is `module.search.search`? Is that an empty module? What does it look like in your state file?

**Comment by rata** [comment] 2016-11-26 18:20
@mitchellh is another (non empty) module that creates an aws instance and a dyn hostname record. 

The module search is like this:
```
module "search" {
  source                  = "../aws-server-chef/"
  name                    = "${var.name}"
  env                     = "${var.env}"
  restorando_ops_path     = "${var.restorando_ops_path}"
  bin_path                = "${var.bin_path}"
  chef_run_list           = "${var.chef_run_list}${var.extra_chef_run_list}"
  instance_type           = "${var.instance_type}"
  disable_api_termination = "${var.disable_api_termination}"
  chef_attr_extra         = "${var.chef_attr_extra}"
  root_block_type = "gp2"
  root_block_size = "${var.root_block_size}"
}
```

And the aws-server-chef is:
```
resource "aws_instance" "srv" {
 ... some stuff here...
}

resource "dyn_record" "hostname" {
   .. stuff...
}

# Hack for dependency, for more infor see:
# https://github.com/hashicorp/terraform/issues/1178#issuecomment-207369534
resource "null_resource" "dummy_dependency" {
  depends_on = ["aws_instance.srv"]
}
```

In the tfstate it looks like:
```
        {
            "path": [
                "root",
                "search",
                "search"
            ],
            "outputs": { .... },
            "resources": {
                "aws_instance.srv": { ... }
                "dyn_record.hostname": { ... }
                "null_resource.dummy_dependency": {
                    "type": "null_resource",
                    "depends_on": [
                        "aws_instance.srv"
                    ],
                    "primary": {
                        "id": "3828481430691578169",
                        "attributes": {
                            "id": "3828481430691578169"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                }
            },
            "depends_on": []
        }
```

Is this enough info? Do you need the whole tfstate thing? How can I help? :)

**Comment by sriney-boc** [comment] 2016-11-28 18:28
I'm getting a similar issue specifically when I target a resource or module.  A straight plan with -target results in the state error.

This worked with 0.7.8.

**Comment by mitchellh** [comment] 2016-11-28 20:51
Hm, I'm still having trouble reproducing this. @rata can you reproduce this with `terraform plan -refresh=false`? If so, if you could email me your state + config then I can reproduce it and fix this. If there is sensitive info in there you can change it (just tell me what has changed). I can reproduce it w/o any internet access (I'm not asking for ANY account access at all) so as long as I can get the state + config that'd be gold.

**Comment by rata** [comment] 2016-11-29 00:07
@mitchellh it's public holiday here today, but will try to reproduce tomorrow. Thanks!

**Comment by rata** [comment] 2016-11-29 17:57
@mitchellh can't seem to easily reproduce now. Will continue trying, but it happened tons of times in the past week (don't know why doesn't happen now).

@sriney-boc can you reproduce and facilitate the tfstate, just in case?

**Comment by mitchellh** [comment] 2016-11-29 18:00
@rata Got it yes I believe you that it really exists, no doubt there. I'm just trying to get a repro so I can get a fix going. :)

**Comment by rata** [comment] 2016-11-29 18:07
@mitchellh yes, that was what I was trying to provide, but with no luck now :-(. Let me know if you find a repro so I don't keep trying to get one when you find it :)

**Comment by sriney-boc** [comment] 2016-11-29 18:12
I upgraded to 0.7.13 to get the verbose dump to a log.  I reproduce it
regularly, I'll review a log and try to scrub it properly. and share.

**Comment by mitchellh** [comment] 2016-11-29 18:13
@sriney-boc Note above that we'll need the state to reproduce. To check:

I should be able to download the state + some config, run `terraform plan -refresh=false` (no intenet connection) and have the error reproduce. If it doesn't, then it probably won't help too much. :(

**Comment by micahlmartin** [comment] 2016-12-08 13:34
@mitchellh I'm getting this consistently too. I'm trying to associate 3 EIP's with with a single interface. If I don't specify `-target=` then it appears to succeed fine but only 2 of 3 associates are created. If I sepecify them with `-target` it will show that it needs to create the other two, but everytime I run it it appears to create them but doesn't, and shows the `Real and shadow states` message. I'm happy to send the state and config files if you let me know where to upload them.

**Comment by mitchellh** [comment] 2016-12-09 03:54
@micahlmartin This would be a huge help. If you can upload them publicly thats great but if its more private feel free to email me directly (my email is visible from my profile).

**Comment by paguilera** [comment] 2016-12-09 19:10
Before I write a dupe, I'm seeing something that generally matches. The first difference I see, though, is in the first error message. It's not a "plan opperation" and is a "apply operation: Real and shadow states do not match!" instead.

**Comment by radeksimko** [comment] 2017-02-08 14:48
Hi folks,
just circling back to an older issue here...

@mitchellh did you receive any details from @micahlmartin ? 
@micahlmartin are you still experiencing this issue in the latest release? If not - can we close this?

No matter how much I believe that a bug may exist, if there's no way to reproduce I'm afraid we cannot fix it.

Thanks!

**Comment by mitchellh** [comment] 2017-02-08 17:18
We can close this just because #11733 which doesn't solve the problem but it won't show up anymore. We still run them as unit tests so if it pops up there we'll find it.

**Closed by mitchellh** 2017-02-08 17:18 UTC
Labels: bug, core, waiting-response
