### ISSUE TITLE
leftover module in tfstate after failure then successful deletion of AWS LB

### ISSUE THREAD

**Issue by aidanhmiles** [hashicorp/terraform#23826] opened 2020-01-09 23:06 UTC
Hi,

I got this output in a recent run of `terraform apply`. 
```
Error: leftover module module.fh_appserver in state that should have been removed; this is a bug in Terraform and should be reported
```
It's not causing issues but just wanted to share. I also wanted to ask if I should manually remove the leftover items from my tfstate (pertinent bits are attached below).

### Terraform Version

```
Terraform v0.12.19
+ provider.aws v2.37.0
```

### Steps to Reproduce
1. have an AWS LB with deletion protection enabled
2. remove it (and any related resources like eips or instances) from main.tf
3. all resources but the LB should be deleted
4. manually disable deletion protection in the console or via AWS API
5. re-run terraform apply
6. LB is deleted, error message appears

### Additional Context

The items left in my .tfstate file are:
```
    {
      "module": "module.fh_appserver",
      "mode": "managed",
      "type": "aws_eip_association",
      "name": "eip_assoc",
      "each": "list",
      "provider": "provider.aws",
      "instances": []
    },
    {
      "module": "module.fh_appserver",
      "mode": "managed",
      "type": "aws_instance",
      "name": "app",
      "each": "list",
      "provider": "provider.aws",
      "instances": []
    },
    {
      "module": "module.fh_appserver",
      "mode": "managed",
      "type": "aws_lb_target_group_attachment",
      "name": "app",
      "each": "list",
      "provider": "provider.aws",
      "instances": []
    }
```

**Comment by jbardin** [comment] 2020-01-10 15:14
Duplicate of #23821

**Closed by jbardin** 2020-01-10 15:14 UTC
