### ISSUE TITLE
<resource> still contains unknown values during apply - AWS MalformedPolicyDocument

### ISSUE THREAD

**Issue by ElvenSpellmaker** [hashicorp/terraform#31064] opened 2022-05-17 22:39 UTC
Hi there, we're getting this strange error when trying to apply our config since being refactored out into a module.

As this code spans multiple providers, such as `hashicorp/aws` and `hashicorp/random` I'm really not sure where this belongs, but want to get the ball rolling.
Also the error appears to be due to `compact(...)` being called too early (before the ARNs are generated) which to me seems like the automatic dependency additions aren't quite right, as the module in question should be dependent on the other module called and so it might a core terraform issue.

Error Output:
```
╷
│ Error: configuration for module.primary_vault.aws_instance.vault still contains unknown values during apply (this is a bug in Terraform; please report it!)
│
│
╵
╷
│ Error: error creating IAM Policy pam20220517173548904900000008: MalformedPolicyDocument: Policy statement must contain resources.
│       status code: 400, request id: 076cb56a-481f-41a6-be94-349f451fa20e
│
│   with module.primary_vault.aws_iam_policy.vault,
│   on ..\vault\vaultmachine_iam.tf line 31, in resource "aws_iam_policy" "vault":
│   31: resource "aws_iam_policy" "vault" {
│
╵

```

TF snippets:
```
module "vault_pwd" {
  for_each    = local.password_obj
  source      = "../../../../libs/infra/terraform-aws-config-params"
  ...
  value       = random_password.vault[each.key].result
}
```
Basically we call out to an internal module in the repository to upload some passwords generated using `hashicorp/random` to ssm, these 4 passwords get passed into the `module.primary_vault` as separate string parameters in the form of:
```
module "primary_vault" {
  source = "../vault"
...
  ssm_master_password_name       = module.vault_pwd.master_pwd.arn
  ssm_param2                     = module.vault_pwd.param2.arn
  ssm_param3                     = module.vault_pwd.param3.arn
  ssm_param4                     = module.vault_pwd.param4.arn
...
}
...
```

The module `vault_pwd` has an output called `arn` which is the ARN of the uploaded password in SSM Parameter store.

Inside the module `module.primary_vault` these are used in a locals function like so:
```
locals {
  vault_ssm_parameters = compact([
    var.ssm_master_password_name,
    var.ssm_param2,
    var.ssm_param3,
    var.ssm_param4,
  ])
}
```
The reasoning for the compact, is for non-primary Vaults not all of the 4 password ARNs are needed and so they shouldn't get added to the policy.

This is then used in the policy like so:
```
data "aws_iam_policy_document" "vault" {
...
statement {
    effect = "Allow"

    sid = "SSM"

    actions = [
      "ssm:GetParameters",
    ]

    resources = local.vault_ssm_parameters
  }
...
}
```

It seems to me from a first glance that the `compact(...)` is running _too early_ and the policy data document should have an implicit `depends_on` to the `vault_pwd` parent module. Instead it ends up as an empty array as it's run before the ARNs are generated by the other module.

Here's a crude paint diagram to explain further:
![image](https://user-images.githubusercontent.com/2286713/168923219-0da0ba88-2210-4952-bfe9-e25c6b53e5a9.png)

### Terraform Version

```
1.1.x
```

### Terraform Configuration Files

Example above, but may need to provide more concrete files later.

### Debug Output
N/A?

### Expected Behavior
Apply to work as expected and create all resources.

### Actual Behavior
Apply creates 94/98 resources and bombs out on the Policy document as it's missing Resources.

Oddly, if you _re-run_ terraform apply it will apply cleanly.

### Steps to Reproduce
`terraform init`
`terraform apply`

### Additional Context
N/A

### References
None that I know of currently.

**Comment by jbardin** [comment] 2022-05-18 17:14
Hi @ElvenSpellmaker,

Thanks for filing the issue. There is definitely _something_ going wrong here, since there should be no unknown values when applying resources, but I don't think there's enough here to begin to diagnose the problem. A provider shouldn't be able to cause this without first triggering other errors, so I'm going to start with the premise that it is a core problem.

Would it be possible to get a complete configuration which causes the issue? The trace logs from applying may prove useful as well if possible. I can't think of any changes in the forthcoming v1.2 which could affect this, but it wouldn't hurt to try a replicate it with the v1.2-rc2 (or final once it's released).

Thanks!

**Comment by ElvenSpellmaker** [comment] 2022-05-19 13:55
@jbardin Hey, yeah I thought that might not be enough to go on.

I'll try to reproduce the bug and get the tracelog for you, and I'll try using the new 1.2 release which should be easy to install with `tfenv`.

BTW using a `depends_on` explicitly seems to deal with it, which to me does indeed indicate a core issue.

About giving the config, what's the best way to share (lots) of files without making them public? Not that this code is super secret but it's for my client so yeah.

**Comment by jbardin** [comment] 2022-05-19 15:59
Hi @ElvenSpellmaker,

You could do a few things, the Hashicorp public key is published in a few places (see https://www.hashicorp.com/security), and you could encrypt the data with that. You can encrypt or send it directly to me or others here using KeyBase. You can make a private GitHub repo and add me as a user.

Thanks!

**Comment by ElvenSpellmaker** [comment] 2022-05-20 20:19
Hey @jbardin, I've created a private repo and have pushed the code which causes the issue and uploaded an encrypted trace to the repo too.
It's possible it can be reproduced with smaller code but I've uploaded everything as-is for now.

Note: I tried 1.2.0 which has now been released but it still throws the same error as you expected.

Let me know if you need anything else, there's a small `README.md` in the repo to help out.

**Comment by jbardin** [comment] 2022-05-24 15:55
Thanks for the config and logs @ElvenSpellmaker!

This one looks like it's going to be a bit difficult to spin up a replication outside of that environment, but I'll continue to dig into it and try to replicate the bug.

A couple ideas which may provide us with useful info in the meantime -- If you are comfortable building Terraform (basically just `go install` with the latest go release), you can build from the `v1.2` branch to get a slightly better diagnostic message, or we can wait for a `v1.2.2` release. That might help narrow down the source of the unknown value you are getting, but I'm afraid it's just going to point at `user_data` which is composed of many resource values 😖 

The fact that adding the module `depends_on` is curious, because while that can sometimes force the ordering of resource evaluation for dependencies not visible in the configuration, there still shouldn't be any references to unknown values during apply. Something that might help us is running the apply with the `depends_on` workaround, and attach the log output for that too (you can use `TF_LOG_CORE=trace` to skip all the provider logs and reduce the sensitive info). This may provide a way to cross reference which dependency is missing.

**Comment by jbardin** [comment] 2024-03-11 18:47
Closing since we didn't get a reproduction, and current releases may not have the same behavior. If this is reproducible with a current release, please include the information here, or open a new issue.

Thanks!

**Closed by jbardin** 2024-03-11 18:47 UTC
Labels: bug, core, waiting for reproduction, v1.1
