### ISSUE TITLE
`defaults` function results in unknown value when object has `optional(list(any))` attribute

### ISSUE THREAD

**Issue by alisdair** [hashicorp/terraform#29511] opened 2021-09-02 15:33 UTC
### Terraform Version

```
Terraform v1.1.0-dev
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  experiments = [module_variable_optional_attrs]
}

variable "foo" {
  type = object({
    a = string
    b = optional(bool)
    c = optional(list(any))
  })
  default = {
    a = "alpha"
  }
}

locals {
  foo = defaults(var.foo, {
    b = true
  })
}

output "foo" {
  value = local.foo
}
```

### Expected Behavior

Running `terraform apply` should

```
Outputs:

foo = {
  "a" = "alpha"
  "b" = true
  "c" = tolist([])
}
```

### Actual Behavior

The output value is null/missing.

### Steps to Reproduce

1. `terraform apply -auto-approve`
2. Look at the output

### Additional Context

If you change the type of `c` to `optional(list(string))`, you see the expected behaviour.

Also, it appears that the local value is unknown:

```shellsession
$ echo local.foo | terraform console
(known after apply)
```

### References

Discovered when responding to #29488.

**Comment by dmikalova** [comment] 2021-11-11 05:15
This is indirectly mentioned in the [defaults](https://www.terraform.io/docs/language/functions/defaults.html) documentation: "The defaults function expects that the input_value argument will be the value of an input variable with an exact type constraint (not containing any)" - however I was not expecting that it would make the whole object `null`. I would either expect the above, or for terraform to error out like it does if you try to apply a defaults to an `any` type: 

```
│ Error: Invalid function argument
│ 
│   on main.tf line 17, in output "out":
│   17:     null = defaults(var.example_null, { optional = "y" })
│ 
│ Invalid value for "defaults" parameter: .optional: cannot apply defaults to
│ dynamic.
```

**Comment by apparentlymart** [comment] 2022-09-16 01:39
I'm going to close this now since the `defaults` function didn't make it into the stable version of this feature and so any misbehavior it had is now moot.

If anyone sees something similar in the final release of the feature using the _built-in_ defaults mechanism, please open a new issue to discuss it; we'll need to start fresh with a new reproduction case in terms of the final implementation of the feature. Thanks!

**Closed by apparentlymart** 2022-09-16 01:39 UTC
Labels: bug, confirmed, experiment/module_variable_optional_attrs, v1.1
