### ISSUE TITLE
Cannot initialise with remote backend (Required token could not be found)

### ISSUE THREAD

**Issue by olegkorol** [hashicorp/terraform#23173] opened 2019-10-24 11:55 UTC
### Terraform Version

```
Terraform v0.12.12
+ provider.google v2.16.0
+ provider.google-beta v2.16.0
```

### Terraform Configuration Files

```hcl
# main.tf
terraform {
  required_version = "~> 0.12.0"
  backend "remote" {
    organization = "my-org"
    hostname = "app.terraform.io"
    workspaces {
      prefix = "my-org-"
    }
  }
}

# .terraformrc
credentials "app.terraform.io" {
  token = "xxx.atlasv1.yyy"
  # this being a team or user token (not an organisation token)
}
```

### Crash Output

```
$ terraform init
Initializing the backend...

Error: Required token could not be found
Make sure you configured a credentials block for app.terraform.io in your CLI Config File.
```

### Expected Behavior

The initialisation should be successful, since the backend and the credentials have been defined.

### Actual Behavior

It crashes and says that no credentials were defined.

### Steps to Reproduce

1. Use the `main.tf` and `.terraformrc` files as specified above.
2. Run `terraform init`.

### Additional Context

If I specify the token inside `main.tf` it works though:

```hcl
terraform {
  required_version = "~> 0.12.0"
  backend "remote" {
    organization = "my-org"
    hostname = "app.terraform.io"
    workspaces {
      prefix = "my-org-"
    }
    token = "xxx.atlasv1.yyy"
  }
}
```

**Comment by keithhubner** [comment] 2019-11-07 09:47
Any update on this as it's causing issues setting up Terraform Cloud

**Comment by jamie3** [comment] 2019-11-26 17:23
Do an `export TF_LOG=debug` and run it again. See if the init is picking up the `terraformrc` file.

**Comment by danieldreier** [comment] 2019-12-03 18:21
@keithhubner I have confirmed with terraform 0.12.17 that I am able to use a `.terraformrc` file with a token and the init is successful. I'm going to close this because I don't think that this is a bug in terraform core. Terraform Cloud Support at tf-cloud@hashicorp.support should be better able to help you troubleshoot than we can here. 

If you are confident there's a bug, please do re-open it and let me know, but also reach out to Terraform Cloud support, because they will be able to work with us to show the reproduction case.

**Closed by danieldreier** 2019-12-03 18:21 UTC
Labels: backend/remote, bug, v0.12
