### ISSUE TITLE
.tfstate retains terraform_version after backend upgrade

### ISSUE THREAD

**Issue by samirageb** [hashicorp/terraform#13078] opened 2017-03-26 17:58 UTC
### Terraform Version
0.9.1

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_machine
- azurerm_resource_group
- azurerm_public_ip
- azurerm_network_interface

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

I configure the `ARM_ACCESS_KEY` as an environment variable

### Terraform Configuration Files
```hcl
variable "azure_subscription_id"        { }
variable "azure_client_id"              { }
variable "azure_client_secret"          { }
variable "azure_tenant_id"              { }
variable "azure_spn_client_id"          { }
variable "azure_spn_secret"             { }
variable "azure_spn_domain"             { }

variable "tag_creator"                  { }
variable "tag_env"                      { }
variable "tag_role"                     { }

variable "ip_dns_label"                 { }
variable "location"                     { }
variable "image_uri"                    { }
variable "pub_ip_allocation"            { }
variable "prv_ip_allocation"            { }
variable "ssh_cert"                     { }
variable "subnet"                       { }
variable "sys_name"                     { }
variable "westus_c"                     { }
variable "vhd_storage_account"          { }
variable "vm_size_map" { 
    type = "map"
}

# Remote state data source
terraform {
  backend "azure" {
    # TF state file to be stored remotely. terraform.tfstate should remain the suffix
    key = "webrtc-prod-westus.terraform.tfstate"
  }
}

# Configure the Microsoft Azure Provider
provider "azurerm" {
  subscription_id = "${var.azure_subscription_id}"
  client_id       = "${var.azure_client_id}"
  client_secret   = "${var.azure_client_secret}"
  tenant_id       = "${var.azure_tenant_id}"
}


resource "azurerm_resource_group" "default" {
    name            = "${var.tag_role}-${var.tag_env}-${var.westus_c}-Rg"
    location        = "${var.location}"

    lifecycle { prevent_destroy = true }

    tags {
        Creator     = "${var.tag_creator}"
        Environment = "${var.tag_env}"
        Role        = "${var.tag_role}"
    }
}

resource "azurerm_public_ip" "default" {
    name                            = "${var.tag_role}-${var.tag_env}-SPip"
    location                        = "${var.location}"
    resource_group_name             = "${azurerm_resource_group.default.name}"
    public_ip_address_allocation    = "${var.pub_ip_allocation}"
    domain_name_label               = "${var.ip_dns_label}"

    lifecycle { prevent_destroy = true }

    tags {
        Creator     = "${var.tag_creator}"
        Environment = "${var.tag_env}"
        Role        = "${var.tag_role}"
    }
}

resource "azurerm_network_interface" "default" {
    name                = "${var.tag_role}-nic0"
    location            = "${var.location}"
    resource_group_name = "${azurerm_resource_group.default.name}"

    ip_configuration {
        name = "ipconfig"
        subnet_id = "subscriptions/${var.azure_subscription_id}/resourceGroups/Infra-${var.tag_env}-${var.westus_c}-Rg/providers/Microsoft.Network/virtualnetworks/${var.tag_env}-${var.westus_c}-VNet/subnets/${var.subnet}"
        private_ip_address_allocation = "${var.prv_ip_allocation}"
        public_ip_address_id = "${azurerm_public_ip.default.id}"
    }

    lifecycle { prevent_destroy = false }

    tags {
        Creator     = "${var.tag_creator}"
        Environment = "${var.tag_env}"
        Role        = "${var.tag_role}"
    }
}

resource "azurerm_virtual_machine" "default" {
    name                    = "${var.sys_name}-Vm"
    location                = "${var.location}"
    resource_group_name     = "${azurerm_resource_group.default.name}"
    network_interface_ids   = ["${azurerm_network_interface.default.id}"]
    vm_size                 = "${var.vm_size_map["prod.webrtc"]}"

    #VIP as it removes orphaned VHDs
    delete_os_disk_on_termination = true

    lifecycle { 
        ignore_changes  = [ "storage_os_disk.vhd_uri" ]
    }

    storage_os_disk {
        name            = "osdisk"
        os_type         = "linux"
        image_uri       = "${var.image_uri}"
        vhd_uri         = "https://${var.vhd_storage_account}.blob.core.windows.net/${lower(var.tag_role)}-${lower(var.tag_env)}/${var.tag_role}-osdisk.145.vhd"
        caching         = "None"
        create_option   = "FromImage"
    }

    os_profile {
        #All computernames are lowercase
        computer_name   = "${lower(var.sys_name)}"

        admin_username = "ubuntu"
        #Required but should be ignored since we use SSH keys
        admin_password = "Password1234!"

        #Used by application to orient itself (which environment it's in, what the IP is, etc.)
        custom_data = ""
    }

    os_profile_linux_config {
        #All computernames are lowercase
        disable_password_authentication = true
        
        #ssh_keys
        ssh_keys {
            path = "/home/ubuntu/.ssh/authorized_keys"
            key_data = "${var.ssh_cert}"
        }
    }

    tags {
        Creator     = "${var.tag_creator}"
        Environment = "${var.tag_env}"
        Role        = "${var.tag_role}"
        OSType      = "Linux"
        SourceVhd   = "${var.image_uri}"
    }
}
```

azure_backend.hcl
```hcl
# Default backend file for Terraform

storage_account_name = "infdevopswestus"
container_name       = "terraform-state"
```

### Debug Output
https://gist.github.com/samirageb/88f061fd2e51046da90e803cea9016cf

### Panic Output
none

### Expected Behavior
` "terraform_version": "0.9.1" ` when looking at the .tfstate file stored in the remote backend

### Actual Behavior
`"terraform_version": "0.8.7"` essentially no change to the remote state file in terms of minimum version of TF allowed

### Steps to Reproduce
1. `terraform init` with existing .terraform directory containing legacy .tfstate file
2. Answering yes/no (no change with either scenario) to the 'copy state' question
3. Answering yes/no (no change with either scenario)  to the pre-existing state question

### Important Factoids
Windows environment, using ConEmu (non-administrative) as terminal. If I use DOS Administrative prompt or Powershell shell, behavior gets non-sensical giving me errors.

```
>terraform init -backend-config=../azure_backend.hcl
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.


Error initializing new backend:
Error configuring the backend "azure": Failed to configure remote backend "azure
": missing 'resource_group_name' configuration

Please update the configuration in your Terraform files to fix this error
then run this command again.
```
The output below is when the exact same commands & TF configuration are run with nothing but a terminal change to ConEmu. After going through the migration questions, I'm greeted with this output in ConEmu.
```
Successfully configured the backend "azure"! Terraform will automatically
use this backend unless the backend configuration changes.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### References
none

**Comment by jbardin** [comment] 2017-03-30 15:15
Hi @samirageb,

Thanks for reporting the issue. 
There appears to be 2 separate issues here, the version isn't updated during migration, and you are having a problem when using the windows commandline. 

Is the lack of TFVersion update directly causing a problem? We're not modifying the state during migration, so that field isn't set. It would be updated on the command could modify the state file. This is an easy fix if we absolutely need it, but I'm not aware of any issue requiring update of the version. 

As for the second issue, could that be caused by the windows cli lexing of the `=` in the flag, amd/or the `../` in the path which isn't a correct windows path separator?

**Comment by samirageb** [comment] 2017-03-30 15:37
@jbardin The lack of the TFVersion update does not appear to produce any problem I'm aware of, other than it creating some confusion on whether the init performed as expected. 

Regarding the second point, good catch on the forward vs. backslash... I will verify and report back on whether that was the issue. It seems likely.

**Comment by jbardin** [comment] 2017-03-31 18:14
Closing this assuming it was a problem parsing the `-backend-config=../azure_backend.hcl` flag. 
If you can reproduce an issue with the CLI we can reopen this.

**Closed by jbardin** 2017-03-31 18:14 UTC
Labels: bug, core
