### ISSUE TITLE
[REG 1.3.9->1.4.0] Some attributes are marked as sensitive for no reason

### ISSUE THREAD

**Issue by orgads** [hashicorp/terraform#32920] opened 2023-03-27 09:05 UTC
### Terraform Version

```shell
Terraform v1.4.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.49.0
```

### Terraform Configuration Files

servicebus/servicebus.tf:
```terraform
resource "azurerm_servicebus_namespace" "servicebus" {
  name = "example-servicebus"
  location = "germanywestcentral"
  resource_group_name = "example-rg"
  sku = "Standard"
}

output "servicebus" {
  value = azurerm_servicebus_namespace.servicebus
}
```

main.tf:
```terraform
provider "azurerm" {
  features {}
}

module "servicebus" {
  source = "./servicebus"
}

resource "azurerm_servicebus_topic" "test" {
  name         = "test"
  namespace_id = module.servicebus.servicebus.id
}
```

### Debug Output

```
# azurerm_servicebus_topic.test will be updated in-place
  ~ resource "azurerm_servicebus_topic" "test" {
        id                                      = "/subscriptions/.../resourceGroups/example-rg/providers/Microsoft.ServiceBus/namespaces/example-servicebus/topics/test"
        name                                    = "test"
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change. The value is unchanged.
      ~ namespace_id                            = (sensitive value)
        # (11 unchanged attributes hidden)
    }
```

### Expected Behavior

It is not sensitive, and should not be considered as sensitive at any point

### Actual Behavior

It is stored as sensitive, and the following warning appears on each apply:
```
Warning: this attribute value will no longer be marked as sensitive
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform apply`

### Additional Context

It only happens when the resource is exported from a module, if I move it to the main module, it works as expected.

This is a regression in 1.4. It works as expected with 1.3.9, and breaks with 1.4.0.

### References

- https://github.com/hashicorp/terraform-provider-azurerm/issues/21130

**Comment by jbardin** [comment] 2023-03-27 12:28
Duplicate of #32880

**Closed by jbardin** 2023-03-27 12:28 UTC
Labels: bug, new

**Comment by orgads** [comment] 2023-03-27 12:31
Thank you!
