### ISSUE TITLE
-target does not source child modules

### ISSUE THREAD

**Issue by Mongey** [hashicorp/terraform#5190] opened 2016-02-18 15:58 UTC
We recently ran into an this issue as discussed in https://github.com/hashicorp/terraform/pull/1820#issuecomment-181475499 by @apparentlymart 

> ... Nested modules don't target in the way I initially expected.
> 
>   Given the following module tree:
> - root
>   - foo
>     - bar
>     - baz
> 
> I initially expected that targeting module.foo would target all of the resources in bar and baz, but it appears that in fact it targets only the resources directly in foo. In my case there was actually nothing in foo except the declarations of bar and baz, so the -target plan appeared to do nothing, just like what is seen in the other examples above.
> 
> I suspect that this is at least what's going on for @maxenglander, since his dc0 module seems to have various sub-modules within.
> 
> The workaround for me was to target bar and baz explicitly by writing out their full names. This was easy (if annoying) in my case because I had relatively few nested modules, but it'd be more intuitive/consistent if targeting a module would also implicitly target all of its descendant modules, thus working on an entire sub-tree of the module hierarchy.

**Comment by phinze** [comment] 2016-02-19 19:14
Thanks for filing this as a separate issue @Mongey - those long-tail threads have valuable details in them that can get lost in the cracks sometimes. :+1: 

Agreed that the behavior should definitely be that targeting a module implicitly targets its sub-modules. Treating this as a POLA violation and therefore a bug.

**Comment by BabakMN** [comment] 2016-09-02 06:02
Any updates on this issue? I can confirm it's present in `v0.7.0`.

**Comment by ketzacoatl** [comment] 2016-09-08 10:54
@phinze, I am seeing this behavior for top-level modules as well as child-modules. Should I create a separate issue for the top-level modules escaping `-target`, or leave it all as one here?

**Comment by sean-brandt** [comment] 2016-09-17 13:35
Some progress here would be great! Having to script terraform to do this sort of thing is certainly an anti-pattern.

**Comment by pikeas** [comment] 2017-03-03 00:46
Bug still present in 0.8.7.

**Comment by dcosson** [comment] 2017-03-22 00:57
Any chance of getting the fix in #9236 reviewed/merged?

**Comment by don-code** [comment] 2017-03-23 22:13
I've found a workaround in the meantime: by exporting at least one parameter from the affected resources from a lower-level module, and consuming it from the higher-level module, `--target` works as expected.

In my case I'm creating TXT records in private DNS of those garbage outputs, but your use case may vary.

**Comment by pepov** [comment] 2017-04-27 09:15
@don-code true, but it only works for the resources that have been referenced from the higher level. All the non-referenced lower level resources are skipped in the plan/apply in my experience.

**Comment by pikeas** [comment] 2017-05-12 00:48
Bug still present in 0.9.4. According to #9236 this will "hopefully" be fixed in 0.10.

**Comment by ChristopheSchmitz** [comment] 2017-05-31 13:39
Yea, very dangerous bug, we got bitten too. Hope this bug will get some love from the terraform team soon :)

**Comment by RulerOf** [comment] 2017-06-02 19:25
We just experienced this, too

```
15:21 $ terraform --version
Terraform v0.9.6
```

**Comment by camjackson** [comment] 2017-07-24 12:40
In case anyone missed it, looks like this is resolved in #15314, but it constitutes a breaking change so it won't be released until 0.10. So good news and bad news.

Does anyone know when 0.10 is expected to land?

**Comment by grubernaut** [comment] 2017-07-24 15:23
Hey @camjackson we don't have a solid date set for the 0.10 release, but there are a couple beta releases and an RC release out if you wish to test this further! 

Looks like this was fixed in #15314, closing.

**Closed by grubernaut** 2017-07-24 15:23 UTC
Labels: bug, core
