### ISSUE TITLE
provider/aws ignores value in tags with keys containing a dot

### ISSUE THREAD

**Issue by thegedge** [hashicorp/terraform#2494] opened 2015-06-25 19:35 UTC
For example, create a simple VPC:
```
resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"
  enable_dns_support = true
  enable_dns_hostnames = true
}
```
Now go to the AWS console and add a `foo.bar` tag to the VPC with some value, say `spam and eggs`. Now add `foo.bar = "spam and eggs"` to `aws_vpc.default.tags` and you'll see that terraform appears to ignore the value and want to empty the tag. 

Tested against d2d9ec328bcd8cff4b8baf8dd8ca286d2fb466c9.

**Comment by phinze** [comment] 2015-06-26 15:35
Hi there - this is a duplicate of #2143 which has a decent amount of discussion around the issue.

**Closed by phinze** 2015-06-26 15:35 UTC
