### ISSUE TITLE
Cannot delete LC because it is attached to an ASG, then diffs not matching during apply

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#2421] opened 2015-06-22 18:24 UTC
Here is the output from Terraform:

```
$ terraform apply -var service="mobilecloud" -var environment="dev"     -var-file=mobilecloud_war.tfvars.json     -var-file=mobilecloud_playbook.tfvars.json     -var-file=terraform.tfvars.json
template_file.mobilecloud-bootstrap: Refreshing state... (ID: 965096b3e01fdeed1caa33c524d2a49bf89ff7b8b4165a7c8e9fa05183988166)
aws_iam_role.mobilecloud: Refreshing state... (ID: mobilecloud-dev)
aws_security_group.mobilecloud: Refreshing state... (ID: sg-6134d006)
terraform_remote_state.mobilecloud: Refreshing state... (ID: 2015-06-22 17:25:01.106471772 +0000 UTC)
aws_iam_instance_profile.mobilecloud: Refreshing state... (ID: mobilecloud-dev)
aws_iam_role_policy.mobilecloud: Refreshing state... (ID: mobilecloud-dev:mobilecloud-dev-deploy_from_s3)
aws_launch_configuration.mobilecloud: Refreshing state... (ID: terraform-sc6vr6s4ufauzcsbegbxafnuzi)
aws_autoscaling_group.mobilecloud: Refreshing state... (ID: mobilecloud-dev-ASG)
aws_launch_configuration.mobilecloud: Destroying...
aws_launch_configuration.mobilecloud: Error: 1 error(s) occurred:

* ResourceInUse: Cannot delete launch configuration terraform-sc6vr6s4ufauzcsbegbxafnuzi because it is attached to AutoScalingGroup mobilecloud-dev-ASG
	status code: 400, request id: [c73d2eb0-1903-11e5-833e-6f4fd440d3f1]
Error applying plan:

3 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* ResourceInUse: Cannot delete launch configuration terraform-sc6vr6s4ufauzcsbegbxafnuzi because it is attached to AutoScalingGroup mobilecloud-dev-ASG
	status code: 400, request id: [c73d2eb0-1903-11e5-833e-6f4fd440d3f1]
* 1 error(s) occurred:

* template_file.mobilecloud-bootstrap: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* 1 error(s) occurred:

* aws_autoscaling_group.mobilecloud: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by joekhoobyar** [comment] 2015-06-22 18:27
Here is the ``infastructure.tf`` file:

```
provider "aws" {
	region     = "${var.aws_region}"
}

resource "terraform_remote_state" "mobilecloud" {
	backend = "s3"
	config {
		bucket = "devops-terraform-state"
		key = "mobilecloud-deploy-${var.environment}"
		region = "${var.aws_region}"
	}
}

# Mobile cloud IAM role needed to download deployment artifacts from S3.
resource "aws_iam_role" "mobilecloud" {
    name = "mobilecloud-${var.environment}"
    assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow",
            "Sid": ""
        }
    ]
}
EOF
}

resource "aws_iam_role_policy" "mobilecloud" {
    name = "mobilecloud-${var.environment}-deploy_from_s3"
    role = "${aws_iam_role.mobilecloud.id}"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::ellucian-mobile"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:HeadObject"
            ],
            "Resource": [
                "arn:aws:s3:::ellucian-mobile/*"
            ]
        }
    ]
}
EOF
}

resource "aws_iam_instance_profile" "mobilecloud" {
    name = "mobilecloud-${var.environment}"
    roles = ["${aws_iam_role.mobilecloud.name}"]
}

# Mobile cloud bootstrapping script.
resource "template_file" "mobilecloud-bootstrap" {
	filename = "templates/bootstrap.sh"
	
	vars {
		playbook_s3_url = "${var.mobilecloud_playbook_url}"
		war_build_number = "${var.mobilecloud_war_build_number}"
        deploy_environment = "${var.environment}"
	}
}

# Mobile cloud security group
resource "aws_security_group" "mobilecloud" {
    name = "mobilecloud-${var.environment}"
    description = "Enables access to mobilecloud server(s)"
    vpc_id = "${var.aws_vpc_id}"

    ingress {
        from_port = 22
        to_port = 22
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }
    ingress {
        from_port = 8080
        to_port = 8080
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }

    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_autoscaling_group" "mobilecloud" {
	availability_zones          = ["us-east-1a", "us-east-1e","us-east-1d","us-east-1c"]
	vpc_zone_identifier         = ["subnet-33402009", "subnet-846e62c2", "subnet-a329cad4", "subnet-c7301cef"]
	name                        = "mobilecloud-${var.environment}-ASG"
	min_size                    = 2
	max_size                    = 2
	desired_capacity            = 2
	launch_configuration        = "${aws_launch_configuration.mobilecloud.id}"
	load_balancers              = ["mobileCloud-${var.environment}"]
	force_delete                = true
	
	tag {
		key = "Name"
		value = "mobilecloud-${var.environment}"
        propagate_at_launch = true
    }
	tag {
		key = "service"
		value = "mobilecloud"
        propagate_at_launch = true
    }
	tag {
		key = "environment"
		value = "${var.environment}"
        propagate_at_launch = true
    }
	tag {
		key = "buildNumber"
		value = "${var.build_number}"
        propagate_at_launch = true
    }
}

# Mobile cloud ASG and LC
resource "aws_launch_configuration" "mobilecloud" {
#	name                        = "mobilecloud-${var.environment}-LC"
	image_id                    = "${var.ami_id}"
	instance_type               = "t2.small"
	iam_instance_profile        = "${aws_iam_instance_profile.mobilecloud.name}"
	associate_public_ip_address = true
	key_name                    = "${var.aws_key_name}"
	security_groups             = ["${aws_security_group.mobilecloud.id}"]
	
	user_data                   = "${template_file.mobilecloud-bootstrap.rendered}"
	
#	lifecycle {
#		create_before_destroy = true
#	}
}
```

**Comment by joekhoobyar** [comment] 2015-06-22 18:27
Here is the ``variables.tf`` file:

```
# AWS Variables
variable "aws_region" {
    default = "us-east-1"
}

# AMI that is used to launch instances.
variable "ami_id" {}

# VPC used to contain infrastructure
variable "aws_vpc_id" {
	default = "vpc-5961ae3c"
}

# Key name of the key-pair that is used to launch instances.
variable "aws_key_name" {
    default = "mobileKeyPair"
}

# Load balancers that instances are launched behind.
variable "load_balancer" {
	default = {
		dev        = "mobileCloud-dev"
		staging    = "mobileCloud-staging"
		production = "mobileCloud-production"
	}
}

# CI/CD Variables
variable "environment" {
	default = "dev"
}
variable "build_number" {
	default = "Unspecified"
}
variable "mobilecloud_playbook_url" {
	default = "s3://ellucian-mobile/jobs/ansible-playbook-mobilecloud-deploy/9/ansible-playbook-mobilecloud-deploy-0.2-full.zip"
}
variable "mobilecloud_war_build_number" {
	default = "23"
}
```

**Comment by sheldonh** [comment] 2015-06-23 10:42
Duplicate of #2385, albeit with more detail provided.

**Comment by joekhoobyar** [comment] 2015-06-23 18:12
#2438 still exhibiting the behavior demonstrated in this ticket.

**Comment by delianides** [comment] 2015-07-08 15:52
+1 for this but I didn't see any reference to the second issue mentioned in the title. According to my log [output](https://gist.github.com/delianides/23ee95c77ade5c9738b4) the issue with the diff fell onto the vpc identifier [#92](https://gist.github.com/delianides/23ee95c77ade5c9738b4#file-gistfile1-txt-L92). However if I rerun the apply it runs successfully.

**Comment by gtmtech** [comment] 2015-07-12 16:19
+1 for this

**Comment by catsby** [comment] 2015-08-06 21:47
Hey @joekhoobyar – looking at your configuration, I see you have the `lifecycle` block commented out in your launch configuration, is there a reason for that?

The command you're running is `apply`, what changes were being made here? Launch configurations should have `create_before_destroy = true` specified if you want to update them, when using with an Auto Scaling Group. I recently replied to this issue as well (https://github.com/hashicorp/terraform/issues/2493) highlighting that for anything that is `create_before_destroy` and also references another resource, those resources must as well have `create_before_destroy` specified.

**Comment by catsby** [comment] 2015-08-07 17:18
I'm going to close this now.  PR #2944, documenting this issue with `create_before_destroy` depending on non-create-before-destroy resources, was merged.

Unfortunately, at this time you cannot use the `create_before_destroy = true` key in the lifecycle block on a resource if it depends on other resources that are not also `create_before_destroy = true`. To enable this behavior, all resources that are referenced must also contain that block, and so on up the dependency graph. 

Please let me know if you have further questions. Thanks!

**Closed by catsby** 2015-08-07 17:18 UTC
Labels: bug, provider/aws
