### ISSUE TITLE
recreate s3 bucket 

### ISSUE THREAD

**Issue by payamzowghi** [hashicorp/terraform#12272] opened 2017-02-27 07:04 UTC
Hi there,
I created my s3 bucket with terraform and then deleted it in aws manually. now, I'd like to recreate s3 bucket with terraform again. I couldn't.
I got this error:
Error reloading remote state: NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: 40AA4833A5DD557B
but I can launch new bucket manually.I'm confused.
 
Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by stack72** [comment] 2017-02-27 14:30
Hi @payamzowghi 

thanks for opening an issue here - I have been trying to recreate it as follows:

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_s3_bucket" "bucket" {
	bucket = "tf-test-bucket-xdgwsgwergwe"
	acl = "private"
}
```

I terraform applied this and I can see the bucket in the console. I then deleted the bucket from the console. A terraform plan then showed me this:

```
+ aws_s3_bucket.bucket
    acceleration_status:                "<computed>"
    acl:                                "public-read"
    arn:                                "<computed>"
    bucket:                             "tf-test-bucket-xdgwsgwergwe"
    bucket_domain_name:                 "<computed>"
    force_destroy:                      "false"
    hosted_zone_id:                     "<computed>"
    region:                             "<computed>"
    request_payer:                      "<computed>"
    versioning.#:                       "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.
```

It immediately told me it was going to recreate it. This is because we look for the following in the code:

```
var err error
	_, err = s3conn.HeadBucket(&s3.HeadBucketInput{
		Bucket: aws.String(d.Id()),
	})
	if err != nil {
		if awsError, ok := err.(awserr.RequestFailure); ok && awsError.StatusCode() == 404  {
			log.Printf("[WARN] S3 Bucket (%s) not found, error code (404)", d.Id())
			d.SetId("")
			return nil
		} else {
			// some of the AWS SDK's errors can be empty strings, so let's add
			// some additional context.
			return fmt.Errorf("error reading S3 bucket \"%s\": %s", d.Id(), err)
		}
	}
```

So we do check for a missing bucket (via the 404 check) and we try to recreate it when that happens

Can you reliably reproduce this?

Thanks

Paul

**Comment by stack72** [comment] 2017-02-28 22:05
Hi @payamzowghi 

I am going to close this out for now - please do let me know if you can recreate this

Thanks

Paul

**Closed by stack72** 2017-02-28 22:05 UTC
Labels: bug, provider/aws, waiting-response

**Comment by payamzowghi** [comment] 2017-02-28 22:12
sorry for delay, yes I could recreate S3 bucket.thanks

**Comment by stack72** [comment] 2017-02-28 22:14
@payamzowghi 

So is this still an error for you? Or has it worked as expected now?

**Comment by payamzowghi** [comment] 2017-02-28 22:17
it has worked as expected, actually I found out the issue.

**Comment by stack72** [comment] 2017-02-28 22:21
thanks :)
