### ISSUE TITLE
Variable validation for objects allowing additional fields when being passed through an intermediary module

### ISSUE THREAD

**Issue by zoonage** [hashicorp/terraform#34298] opened 2023-11-24 15:21 UTC
### Terraform Version

```shell
Terraform v1.6.4
on darwin_arm64
```

### Terraform Configuration Files

`./m1/m2/m2.tf`

```
variable "obj" {
  type = map(object({name = string}))
}

output "obj" {
  value = var.obj
}
```

`./m1/m1.tf`

```
variable "obj" {
  default = {}
}

output "m2" {
  value = module.m2
}

module "m2" {
  source = "./m2"
  obj = var.obj
}

```

`bug.tf`

```
output "m1" {
  value = module.m1
}

module "m1" {
  source = "./m1"
  obj = {
    abc = {notname = "123", name = "456"}
  }
}
```

### Debug Output

```
> TF_LOG=debug terraform validate
[INFO]  Terraform version: 1.5.7
[DEBUG] using github.com/hashicorp/go-tfe v1.26.0
[DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
[DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
[DEBUG] using github.com/zclconf/go-cty v1.12.2
[INFO]  Go runtime version: go1.21.1
[INFO]  CLI args: []string{"terraform", "validate"}
[DEBUG] Attempting to open CLI config file: /Users/***/.terraform.d/config.tf
[INFO]  Loading CLI configuration from /Users/***/.terraform.d/config.tf
[DEBUG] Not reading CLI config directory because config location is overridden by environment variable
[DEBUG] ignoring non-existing provider search directory terraform.d/plugins
[DEBUG] ignoring non-existing provider search directory /Users/***/.terraform.d/plugins
[DEBUG] ignoring non-existing provider search directory /Users/***/Library/Application Support/io.terraform/plugins
[DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
[INFO]  CLI command args: []string{"validate"}
[DEBUG] checking for provisioner in "."
[DEBUG] checking for provisioner in "/opt/homebrew/bin"
[DEBUG] Building and walking validate graph
[DEBUG] ReferenceTransformer: "module.m1.var.obj (expand)" references: []
[DEBUG] ReferenceTransformer: "module.m1 (expand)" references: []
[DEBUG] ReferenceTransformer: "module.m1 (close)" references: []
[DEBUG] ReferenceTransformer: "module.m1.module.m2 (expand)" references: []
[DEBUG] ReferenceTransformer: "module.m1.module.m2 (close)" references: []
[DEBUG] ReferenceTransformer: "module.m1.module.m2.var.obj (expand)" references: [module.m1.var.obj (expand)]
[DEBUG] Starting graph walk: walkValidate
Success! The configuration is valid.

```

### Expected Behavior

Terraform validate fails due to an invalid type being passed to `m2` (`""` does not match `object({name = string})`)

### Actual Behavior

Terraform validate succeeds with no type error

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### Additional Context

Attached is a minimal setup showing the bug

[terraformbug.tar.gz](https://github.com/hashicorp/terraform/files/13460519/terraformbug.tar.gz)

**Comment by apparentlymart** [comment] 2023-11-27 17:14
Hi @zoonage,

The behavior you have observed is the intended behavior. Terraform has a structural type system, and part of that is that an object type constraint specifies a set of attributes that are required and accepts any object which has at least those attributes. This serves to reduce coupling between modules, since each module can specify only the subset of attributes it needs and the caller can pass a superset value to all modules with compatible type constraints. This is often used, for example, to depend only on the subset of attributes that are common across both a managed resource type and a data source, so that a module can accept both.

These values are still subject to type conversion and so you will find that inside the module the finalized value for the variable will have only the attributes you specified, with the others having been discarded as irrelevant to the current module.

This behavior is as designed and is also protected by the Terraform v1.x compatibility promises, and so the design cannot change to work the way you expected. Therefore I'm going to close this issue. Thanks!

**Closed by apparentlymart** 2023-11-27 17:14 UTC
Labels: bug, new
