### ISSUE TITLE
Terraform recreating all resources post reapply for same plan

### ISSUE THREAD

**Issue by Murudkar** [hashicorp/terraform#29566] opened 2021-09-10 22:26 UTC
### Terraform Version

```
0.14.11
```

### Expected Behavior
Terraform should not be recreating the created resources again. 

### Actual Behavior
Terraform recreates all resources, even the one not managed by Kubernetes provider. 

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. terraform plan -out=plan.out
2. _terraform apply plan.out_

### Additional Context
We are using terraform in automation, where a generated plan in applied. We are using "kubernetes" "kubernetes_deployment" resources which places pods. This is alongside with other resources from AWS provider ( example S3 ... )

Apply fails as pods take time to comeup. which is expected. Post if we apply the same _terraform apply plan.out_ on same plan, it tries to recreates all resources.

Verified state file exists and have all the resources there, using S3 as backend. 

Note: Second time we are not running "terraform plan -out=plan.out"  , but directly applying the same plan again.

**Comment by jbardin** [comment] 2021-09-12 14:46
Duplicate of #24078

**Closed by jbardin** 2021-09-12 14:46 UTC
Labels: bug, new
