### ISSUE TITLE
Fetches same module multiple times

### ISSUE THREAD

**Issue by dtolnay** [hashicorp/terraform#8555] opened 2016-08-30 17:52 UTC
### Terraform Version

0.7.2

### Terraform Configuration Files

```hcl
module "a" {
  source = "git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test//b?ref=master"
}

module "b" {
  source = "git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test//a?ref=master"
}

# in codecommit: empty files a/main.tf and b/main.tf
```

### Expected Behavior

Both are the same repo so it should be cloned once.

### Actual Behavior

```
$ terraform get
Get: git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test?ref=master
Get: git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test?ref=master
```

CodeCommit is slow so this is problematic when we keep dozens of modules in the same repo.

### Steps to Reproduce

1. Create "test" repo in CodeCommit containing a branch "master" with empty files `a/main.tf` and `b/main.tf`.
2. Create a local directory containing `main.tf` with the contents above.
3. [Set up gitconfig to work with CodeCommit](http://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html).
4. `terraform get`

**Comment by mitchellh** [comment] 2016-08-30 21:42
Currently this is how Terraform works internally since we ran into other issues caused by sharing the same directory. Its not ideal but it works. We're planning on reworking the ".terraform/modules" directory and when we do so I'll plan in how we can properly support a single clone per repo. 

Closing as "working as intended" for now. Sorry!

**Closed by mitchellh** 2016-08-30 21:42 UTC
Labels: bug, core

**Comment by dtolnay** [comment] 2016-08-30 21:44
@mitchellh the issue was about *fetching* multiple times, not storing multiple copies in ".terraform/modules". I agree that sharing the same directory is complicated but I think we can fix this to fetch just once and make copies locally.

**Comment by mitchellh** [comment] 2016-08-30 21:57
All of the above is definitely fixable and on the radar to be fixed: both fetching only once as well as storing only once (if possible, i.e. same ref). 

However, there are a few choices here:

  1. Clone multiple times, store multiple times (current) - Poor UX when slow servers, unnecessary network usage, unnecessary storage usage.

  1. Clone once, store multiple times (copies) - Not a bad situation, but would require a bunch of changes we have planned in the larger scope or rethinking `.terraform/modules`. This will probably happen!

  1. Clone once, store once (for the same ref) - We ran into really terrible issues here that we fixed in 0.7.2 (see changelog). Fixable by rethinking how we keep an inventory in `.terraform/modules`. Should be fixed alongside above.

  1. Clone multiple times, store once - Doesn't make sense

So we're heading towards (2)! I only closed this since I don't consider the behavior to actually be buggy at the moment since we specifically introduced this behavior in 0.7.2 to fix much worse issues (panics, crashes when modifying modules, not updating in some cases too).

**Comment by felipe-vvoosh** [comment] 2017-11-27 00:58
I don't think this one should be closed...

**Comment by felipe-vvoosh** [comment] 2017-11-27 00:59
I'm having to wait lots of time as sometimes I need to remove .terraform folder to force the changes to be seen.

**Comment by syquus** [comment] 2018-04-11 08:50
This shouldn't be closed. It's a real Issue that is still there on TF 0.11.6

**Comment by tamsky** [comment] 2019-10-11 03:35
@mitchellh 
> All of the above is definitely fixable and on the radar to be fixed: both fetching only once as well as storing only once (if possible, i.e. same ref).

This issue was closed as "working as intended" (maybe because the title made it seem like a bug, which it wasn't.)
A separate Feature Request was filed in #17088 and was closed as a duplicate.

Can we please keep one of these open as a feature request and community point of contact as you make progress on this Feature Request, namely reducing module source cloning costs?

Thanks!
