### ISSUE TITLE
s3 backend workspace list not showing all when > 1000 state files across workspaces

### ISSUE THREAD

**Issue by mgresko** [hashicorp/terraform#23468] opened 2019-11-22 14:52 UTC
### Terraform Version

```
11.14 (also appears in 12.x)
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

workspace list should show all workspaces

### Actual Behavior
Latest workspaces are missing, when workspaces do exist they periodically fail to pull remote state.  Since files are return by date it is ever changing.

### Steps to Reproduce
1. `Have state bucket with more than 1000 state files`
2. `terraform init`
3. `terraform apply`

### Additional Context
The issue appears to be in the fact that https://github.com/hashicorp/terraform/blob/b5508b91422427bee4a07d6f6174ae37934c94e6/backend/remote-state/s3/backend_state.go#L32 calls s3.ListObjects which limits the return to 1000.  This is further confirmed in the debug output I see `<MaxKeys>1000</MaxKeys><IsTruncated>true</IsTruncated>`.  This call needs to be using s3.ListObjectsV2Pages.

**Comment by mgresko** [comment] 2019-11-22 14:54
Needs to look similar to this.
```go
	params := &s3.ListObjectsV2Input{
		Bucket: &b.bucketName,
		Prefix: aws.String(prefix),
	}

	wss := []string{backend.DefaultStateName}
	err := b.s3Client.ListObjectsV2Pages(params,
		func(resp *s3.ListObjectsV2Output, lastPage bool) bool {
			for _, obj := range resp.Contents {
				ws := b.keyEnv(*obj.Key)
				if ws != "" {
					wss = append(wss, ws)
				}
			}
			return true
		})
```

**Comment by teamterraform** [comment] 2019-12-09 16:41
Closing as duplicate of https://github.com/hashicorp/terraform/issues/15968

**Closed by teamterraform** 2019-12-09 16:41 UTC
Labels: backend/s3, bug, v0.12
