### ISSUE TITLE
Terraform State File module inconsistent ordering

### ISSUE THREAD

**Issue by Velyks** [hashicorp/terraform#22287] opened 2019-08-01 11:59 UTC
### Terraform Version
```
Terraform v0.12.4
+ provider.aws v2.12.0
+ provider.random v2.1.2
+ provider.template v2.1.2
```

### Expected Behavior
When a terraform state change is made I expect the serial to be incremented and the relevant state changes to be made so that a diff between the new and previous state shows only the changes made.

### Actual Behavior
When Terraform changes the state file it is re-ordering the json elements seemingly randomly such that running `terraform refresh` causes a very extensive diff to be generated, rather than just incrementing the serial and updating the timestamps.

### Steps to Reproduce
1. `terraform refresh` OR `terraform apply`

**Comment by teamterraform** [comment] 2019-08-01 12:57
Hi @Velyks !

It would help if you provided some additional information, such as snippets of output that show the differences vs. what you expect to see. It's not clear from this issue what state representation you are describing: are you diffing the `terraform.tfstate` file? Comparing the output of `terraform state show`? Output of `apply`? Etc.

The `terraform.tfstate` file is not optimized for external consumption, by either human eyes or third-party tools. There are various cli tools and outputs that are designed as such, and may have inconsistent ordering that we can look into.

**Comment by Velyks** [comment] 2019-08-01 13:24
This is all to do with the `terraform.tfstate` file. Looking a bit further into it on my side it seems that it's the order of modules inside the tfstate file.

When running anything that modifies the `terraform.tfstate` file (terraform apply, terraform refresh etc) looks to be putting modules in a different order.

I've made a quick test terraform folder that contains a file that makes three instances of a simple module that holds one random number.
```hcl
provider "random" {
  version = "= 2.1.2"
}

module "Random1" {
  source = "./module"
}

module "Random2" {
  source = "./module"
}

module "Random3" {
  source = "./module"
}
```

When applied you end up with this terraform.tfstate file:
```json
{
  "version": 4,
  "terraform_version": "0.12.4",
  "serial": 6,
  "lineage": "fa573762-6048-c6a5-f8c3-61e6c55515cd",
  "outputs": {},
  "resources": [
    {
      "module": "module.Random3",
      "mode": "managed",
      "type": "random_integer",
      "name": "random",
      "provider": "provider.random",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1",
            "keepers": null,
            "max": 2,
            "min": 1,
            "result": 1,
            "seed": null
          }
        }
      ]
    },
    {
      "module": "module.Random2",
      "mode": "managed",
      "type": "random_integer",
      "name": "random",
      "provider": "provider.random",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "2",
            "keepers": null,
            "max": 2,
            "min": 1,
            "result": 2,
            "seed": null
          }
        }
      ]
    },
    {
      "module": "module.Random1",
      "mode": "managed",
      "type": "random_integer",
      "name": "random",
      "provider": "provider.random",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "2",
            "keepers": null,
            "max": 2,
            "min": 1,
            "result": 2,
            "seed": null
          }
        }
      ]
    }
  ]
}
```

When you run `terraform refresh` making no changes to the .tf file the `terraform.tfstate` file changes to:
```json
{
  "version": 4,
  "terraform_version": "0.12.4",
  "serial": 7,
  "lineage": "fa573762-6048-c6a5-f8c3-61e6c55515cd",
  "outputs": {},
  "resources": [
    {
      "module": "module.Random1",
      "mode": "managed",
      "type": "random_integer",
      "name": "random",
      "provider": "provider.random",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "2",
            "keepers": null,
            "max": 2,
            "min": 1,
            "result": 2,
            "seed": null
          }
        }
      ]
    },
    {
      "module": "module.Random3",
      "mode": "managed",
      "type": "random_integer",
      "name": "random",
      "provider": "provider.random",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1",
            "keepers": null,
            "max": 2,
            "min": 1,
            "result": 1,
            "seed": null
          }
        }
      ]
    },
    {
      "module": "module.Random2",
      "mode": "managed",
      "type": "random_integer",
      "name": "random",
      "provider": "provider.random",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "2",
            "keepers": null,
            "max": 2,
            "min": 1,
            "result": 2,
            "seed": null
          }
        }
      ]
    }
  ]
}
```

The modules have changed order and have created a diff.

**Comment by teamterraform** [comment] 2019-08-01 13:33
Thanks for the response! The terraform team makes no promises about the internals of the `terraform.tfstate` file - it is intended to be used by Terraform, and not anything else. We will not be making changes to this format which only support use by third parties.

As an alternative, you can run [`terraform show -json`](https://www.terraform.io/docs/commands/show.html#json-output) and save the output of that instead. It was designed to have consistent ordering of resources - if you find any inconsistencies, that is a bug we will address. 

I am going to leave this open for now. If you find the output for `terraform show -json` meets your needs, we can close this. Thanks!

**Comment by Velyks** [comment] 2019-08-01 13:36
This is a change from terraform 0.11 where the modules retained some sort of consistent order. I understand that terraform.tfstate is internal but we use git to keep track of it between multiple developers.

Could this possibly be looked at as a simple feature request? It isn't really a change in format.

**Comment by teamterraform** [comment] 2019-08-01 13:59
No, we will not consider feature requests for the tfstate file. 
I have already suggested a workaround: commit the output of terraform show -json and diff that instead. We _will_ consider feature requests (and fix bugs) for that command's output.

**Comment by kmoe** [comment] 2019-08-01 14:06
Using git to share Terraform state between multiple developers sounds like it could lead to some frustration! @Velyks, have you looked into using a backend for state management, so your state file is shared via Consul, S3, or another remote service?

https://www.terraform.io/docs/state/remote.html
https://www.terraform.io/docs/backends/types/index.html

**Comment by Velyks** [comment] 2019-08-01 14:11
Yes we have, git is the most appropriate for our situation. Committing the output of terraform show -json is not a workaround as that doesn't provide the functionality required to share state between developers.

**Comment by teamterraform** [comment] 2019-08-01 14:26
The functionality required to share state between developers is provided by Terraform's remote state feature, as @kmoe explained above. The Terraform state file is not intended for this use, and we believe it is working as intended.

**Closed by teamterraform** 2019-08-01 14:26 UTC
Labels: bug
