### ISSUE TITLE
Terraform doesn't react on plan/destroy/apply commands after i once stopped destroying in the middle of the process

### ISSUE THREAD

**Issue by Bushmeniov** [hashicorp/terraform#28277] opened 2021-04-04 19:05 UTC
Hi. Recently i was destroying my deployment resources on AWS via python-terraform wrapper. But, i intentionally interrupted it in half path . After it, when i again wanted to destroy my deployment - terraform said me, that i have "locked process with some uuid". I tried to kill that proccess with force-unlock command, but it didn't help. Moreover, now i have very strange situation.. When i want to activate commands like : destroy, plan, apply terraform don't write me any info in console (console don't show any signs, that terraform are running - empty line, which lasts forever). 
I tried to delete terraform, all state files, lock files, backup files, providers - but it does help nothing. Also, tried to create another project (i had a believe, that new project - would give terraform a new life), but it  doesn't help.
Commands like terraform init, validate, refresh, providers .. work well
All this situations reprodeuce in the same way with simple cli, which also doesn't want to react on specified commands before.

how can i force delete/dawloand or refresh again terraform, to get terraform "OOTB" ? or, may be some ideas, how can i detect the problem, which made me stuck ?

```
os: linux
terrafrom: v0.14.9
python-terraform: 0.10.1
python: 3.7
terraform-provider-aws_v3.35.0_x5 / linux amd64
```

**Comment by jbardin** [comment] 2021-04-05 13:09
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by jbardin** 2021-04-05 13:09 UTC
Labels: bug, new

**Comment by Bushmeniov** [comment] 2021-04-05 13:53
> Hello!
> 
> We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.
> 
> Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

terraform doesn't react on any my plan/destroy/apply commands. I think it's kind of bug. It's doesn't give me any info about commands status. NO RESPONSE

**Comment by jbardin** [comment] 2021-04-05 14:04
Hi @Bushmeniov,

You may be correct that the situation you have is caused by a bug, but we don't have enough information here to know what could be going wrong. There are more people in the support forums who may be able to help you debug the problem, and provide you with what you need to fill in the required information in the issue template.

Thanks!
