### ISSUE TITLE
Deprecation messages for data source attributes do not show in terraform plan

### ISSUE THREAD

**Issue by maastha** [hashicorp/terraform#35454] opened 2024-07-14 15:19 UTC
### Terraform Version

```shell
Terraform v1.9.2
on darwin_arm64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.17.0
```

### Terraform Configuration Files

```terraform
data "mongodbatlas_advanced_cluster" "replicasetMultiCloud" {
	project_id = mongodbatlas_advanced_cluster.replicasetMultiCloud.project_id
	name 	     = mongodbatlas_advanced_cluster.replicasetMultiCloud.name
}

output "repSpecIDReplicaset" {
  value = data.mongodbatlas_advanced_cluster.replicasetMultiCloud.replication_specs[0].id  //This `id` attribute has been marked as deprecated in the schema
}
```

### Debug Output

https://gist.github.com/maastha/5af8c7b6b789489af75195b89f118532 

### Expected Behavior

Terraform should show deprecation warnings for attributes in data sources that are marked as Deprecated in the schema if they are being referenced in Terraform configuration files similar to resource attribute deprecations.

### Actual Behavior

No deprecation message is shown if outputting a deprecated attribute from the data source.

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

We are working on deprecating some attributes for a resource & it's corresponding data source in our provider. The resource & data source are based in Plugin SDKv2.
During testing we noticed that any attribute marked as deprecated in the data source does not show a deprecation warning even if that attribute is being referenced in terraform config whereas deprecation in resource for all attributes works as expected and user can see a deprecation warning.

**Comment by jbardin** [comment] 2024-07-15 12:56
Hi @maastha,

Thanks for filing the issue. The deprecation message for computed attributes currently only serves as documentation, so Terraform is working as designed in this instance. Terraform does not have the needed metadata necessary to provide the warning when the resource value is being evaluated elsewhere in the configuration.

Thanks

**Comment by jbardin** [comment] 2024-07-15 12:56
Duplicate of #7569

**Closed by jbardin** 2024-07-15 12:56 UTC
Labels: enhancement, new
