### ISSUE TITLE
aws_instance: change instance type causes instance destroy/create

### ISSUE THREAD

**Issue by partamonov** [hashicorp/terraform#2423] opened 2015-06-22 19:00 UTC
Currently if you change aws instance(ebs root storage) type this will cause instance re-creation.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-resize.html
But AWS allows to change instance type only by stopping it, changing instance size and start it. CFN also in case of change of instance size just stop, change and start instance

**Comment by julienlavergne** [comment] 2015-06-25 13:18
@partamonov several improvements must be done about aws_instance resources and other dependencies; currently terraform have an approach where several resources modified need to be recreated.

**Comment by catsby** [comment] 2015-12-02 21:50
Hey @partamonov – I'm going to close this as a duplicate of #1887 and/or #1579 . The need to manage stop or other state like this noted there. Thanks!

**Closed by catsby** 2015-12-02 21:50 UTC
Labels: bug, provider/aws

**Comment by tomstachura** [comment] 2016-11-14 23:06
Is this in a plan to be fixed? It would be great if the instance survived.

**Comment by salewski** [comment] 2017-04-02 14:24
For folks landing here from a google search: it looks like this feature was implemented in issue #9157 (see pull #11998), which was included in the `terraform-0.8.8` release (2017-03-02).
