### ISSUE TITLE
template_file resource "primary" ends up null in tfstate file

### ISSUE THREAD

**Issue by chiefy** [hashicorp/terraform#2939] opened 2015-08-05 13:07 UTC
We are using TF in a team setting, and one of my co-workers ended up getting his tfstate file like this yesterday:

![template is null](https://www.dropbox.com/s/crijgqbyl5ui5ns/template_null.png?dl=1)

Unfortunately, I have no idea how he did this, but it took me about an hour to figure out because literally every TF command I tried ended up spitting out
```
Resource 'template_file.user-data-script' does not have attribute 'rendered' for variable 'template_file.user-data-script.rendered'
```

The solution was to go in and manually edit the `.tfstate` file, I moved an old deposed template resource into the primary and everything started working again.

Again, I cannot reproduce, but just wanted to document this happening in case it pops up again.

**Comment by ketzacoatl** [comment] 2015-08-26 01:22
I have run into this quite a few times, and I'm not sure how to reproduce. I have fixed/resolved the issue with manual tweaks to the state file, though I do not (right now) remember what those updates were.

**Comment by ketzacoatl** [comment] 2015-08-26 01:39
@phinze / @mitchellh, Could this be a bug with resource dependency resolution? It seems as though it is.

I have a `template_file` resource which is provided as a variable (input string) to a module, and which ends up being `user_data` for instances created. If I provide the module with `user_data = "foobar"`, instead of `user_data = "${template_file.leaders-init.rendered}"`, I can successfully target the template:

```
ᐅ terraform plan -target=template_file.leaders-init
Refreshing Terraform state prior to plan...

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ template_file.leaders-init
    filename:              "" => "scripts/init-leaders.tpl"
    rendered:              "" => "<computed>"
    vars.#:                "" => "10"
    ...

Plan: 1 to add, 0 to change, 0 to destroy.
```

...when I leave the `"${template_file.leaders-init.rendered}"`, Terraform gets stuck:

```
ᐅ terraform plan -target=template_file.leaders-init
Error configuring: 1 error(s) occurred:

* Resource 'template_file.leaders-init' does not have attribute 'rendered' for variable 'template_file.leaders-init.rendered'
```

**Comment by zoltrain** [comment] 2015-09-07 14:09
I've also just run into this issue, it does seem related to resource dependencies when using raw resources, who's values are passed to modules.

I get it when trying to create a Route 53 DNS record (I have a DNS module for reuse) that depends on ELB endpoint value from a resource that's not a module. It seems the only way to guarantee that the right order of creation is either, make everything a resource in a flat way (no modules) and explicitly handle the depends, or make EVERYTHING a module. Is depends_on going to add module -> resource, resource -> module bindings in the future?

**Comment by phinze** [comment] 2015-09-08 14:43
This definitely has the feel of a core bug. Tagged as such.

If anybody managed to get this narrowed down to a repro case please do share! In the meantime I'll keep an eye out for it in personal TF usage and report back if I can reproduce.

**Comment by phinze** [comment] 2015-09-08 15:43
Looks like https://github.com/hashicorp/terraform/issues/3182 has a reproducible relevant scenario which should help us get some debugging done. :+1:

**Comment by ketzacoatl** [comment] 2015-09-09 19:05
@phinze I would share more code, but it is a bit buried in code that is not yet open-sourced. I will see if I can reproduce the bug with one of my modules that could be more easily shared. Glad to see we have some traction either way!

**Comment by ketzacoatl** [comment] 2015-09-18 14:04
@phinze, would it help if I spent the time to get some code online for you, based on what I am doing? Looking over the code in the referenced issue, I might be doing something functionally the same within Terraform (to trip the same bug), but my code and logic is different. In short: I have a bunch of TF modules which accept a `user_data` variable, and which I often supply as a rendered template. So the template is outside the module and passed in, the stuff that uses the template is inside the module.

**Comment by ketzacoatl** [comment] 2015-09-18 20:01
On a related note, when I issue a `terraform destroy -force` in this environment, the destroy succeeds, nothing is left at AWS.. but TF throws a bunch of errors, related to the template file:

```
aws_vpc.my_app: Destroying...
aws_vpc.my_app: Destruction complete
Error applying plan:

14 error(s) occurred:

* Resource 'template_file.leaders-init' does not have attribute 'rendered' for variable 'template_file.leaders-init.rendered'
* Resource 'aws_vpc.my_app' does not have attribute 'id' for variable 'aws_vpc.my_app.id'
* Resource 'aws_vpc.my_app' does not have attribute 'id' for variable 'aws_vpc.my_app.id'
* Resource 'aws_vpc.my_app' does not have attribute 'id' for variable 'aws_vpc.my_app.id'
* Resource 'aws_vpc.my_app' does not have attribute 'id' for variable 'aws_vpc.my_app.id'
* Resource 'aws_vpc.my_app' does not have attribute 'id' for variable 'aws_vpc.my_app.id'
* Resource 'aws_vpc.my_app' does not have attribute 'id' for variable 'aws_vpc.my_app.id'
* Resource 'aws_security_group.a-app' does not have attribute 'id' for variable 'aws_security_group.a-app.id'
* Resource 'aws_security_group.b-app' does not have attribute 'id' for variable 'aws_security_group.b-app.id'
* Resource 'aws_security_group.q-inbound' does not have attribute 'id' for variable 'aws_security_group.q-inbound.id'
* Resource 'aws_route_table.my_app' does not have attribute 'id' for variable 'aws_route_table.my_app.id'
* Resource 'aws_route_table.my_app' does not have attribute 'id' for variable 'aws_route_table.my_app.id'
* Resource 'aws_route_table.my_app' does not have attribute 'id' for variable 'aws_route_table.my_app.id'
* Resource 'aws_route_table.my_app' does not have attribute 'id' for variable 'aws_route_table.my_app.id'
```

**Comment by melutzke** [comment] 2016-08-11 00:50
Ran into this issue today, after a successful deploy, the primary field had been written out to file as null, had to substitute in an old deposed section of json.

**Comment by mitchellh** [comment] 2016-10-25 19:33
#3182 is fixed which we felt this was related to, and there are other newer issues that have simiar error messages. Because there is no clean repro here and its been so long I'm going to close this issue and move on to the newer ones. If you see it again please open an issue and please try to get a repro!

Note that "lost state" would be a top top priority issue in any case so any repro will be prioritized. At this point there we aren't hearing of these issues.

**Closed by mitchellh** 2016-10-25 19:33 UTC
Labels: bug, core
