### ISSUE TITLE
AzureRM 2.x Required Field Not Utilized Within Terraform Required Providers Block

### ISSUE THREAD

**Issue by AErmie** [hashicorp/terraform#25332] opened 2020-06-22 14:07 UTC
### Terraform Version
```
terraform_0.13.0-beta2_windows_amd64
```

### Terraform Configuration Files
```
provider "azurerm" {
  version = ">= 2.0.0"
  features {}
}

terraform {
  required_version = ">=0.13.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.0.0"
      features {}
    }
}
```

### Crash Output
Error: "features": required field is not set

### Expected Behavior
The required_providers block should also accept the 'features{}' required field (as the azurerm provider block above demonstrates)

### Actual Behavior
Field not detected inside of required_providers

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
The features{} element is required for v2 of the AzureRM provider.

**Comment by jbardin** [comment] 2020-06-22 15:32
Hi @AErmie 

Thanks for filing this, but i suspect there's something else at play in your configuration. the `required_provider` block does not take a provider configuration, it only defines what providers are required, and a `features` block is not a valid attribute there. While not the best error, the unexpected block shown above should return an error like

```
Error: Missing key/value separator

  on main.tf line 12, in terraform:
   9:     azurerm = {
  10:       source  = "hashicorp/azurerm"
  11:       version = ">= 2.0.0"
  12:       features {}

Expected an equals sign ("=") to mark the beginning of the attribute value.
```

I suspect you have a default provider being created in the config somewhere. Could you possibly try to make a self-contained reproduction?

**Comment by AErmie** [comment] 2020-06-23 12:07
Hey @jbardin 
I took the 'features {}' line out of the required_providers block and kept it as part of my provider declaration, like so... 

```
provider "azurerm" {
  version = ">= 2.0.0"
  features {}
}

terraform {
  required_version = ">= 0.13.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.0.0"
    }
  }
}
```

... which resolves that issue, but now throws an error with the provider installation... 
```
Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 2.0.0, >= 2.0.0"...
- Installing hashicorp/azurerm v2.15.0...

Error: Failed to install provider

Error while installing hashicorp/azurerm v2.15.0: open
.terraform\plugins\registry.terraform.io\hashicorp\azurerm\2.15.0\windows_amd64\terraform-provider-azurerm_v2.15.0_x5.exe:
The system cannot find the path specified.
```

Is this a known issue with v0.13 and the latest AzureRM provider?

**Comment by jbardin** [comment] 2020-06-23 13:08
Thanks @AErmie 

That's a different error, which I haven't seen yet. It doesn't look to be specific to the azurerm provider. Can you try with another provider on your system and see if you get the same results. 

If you still cannot install the plugins, please file a new issue with the config and the trace logs so we can take a look. I'll close this issue out since it's not related to the installation error.

**Closed by jbardin** 2020-06-23 13:08 UTC
Labels: v0.13
