### ISSUE TITLE
Map variable erroring as list type

### ISSUE THREAD

**Issue by jamtur01** [hashicorp/terraform#9152] opened 2016-09-30 18:47 UTC
### Terraform Version

Terraform v0.7.4

### Affected Resource(s)

map syntax

(example taken from https://www.terraform.io/intro/getting-started/variables.html)

### Terraform Configuration Files

variables.tf

```hcl
variable "region" {}
variable "ami" {
  type = "map"
}
```

terraform.tfvars

```hcl
region = "us-east-1"
ami = {
  us-east-1 = "ami-0d729a60"
  us-west-1 = "ami-7c4b331c"
}
```

base.tf

```hcl
resource "aws_instance" "base" {
  ami           = "${lookup(var.ami, var.region)}"
  instance_type = "t1.micro"
}
```

### Debug Output

https://gist.github.com/jamtur01/c236a946bad601391dd2777f2667789d

### Expected Behavior

Map key returned as attribute value.

### Actual Behavior

```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* variable ami should be type map, got list
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Configuration files listed.

2. `terraform plan`

### Note

If I change the variable definition to:

```hcl
variable "region" {}
variable "ami" {
  type = "map"
  default = {}
}
```

Then the variable works.

**Comment by jamtur01** [comment] 2016-09-30 19:05
Suspect related to:

#9012 and #9079 

And maybe a duplicate of #8057 ?

**Comment by jbardin** [comment] 2016-10-03 14:25
Hi @jamtur01,

Thanks for the issue with the clear reproduction! This may be tangentially related to 9012, but it is a duplicate of 8057, and the can be fixed with the same workaround for now.

Closing as duplicate of #8057

**Closed by jbardin** 2016-10-03 14:25 UTC
Labels: bug, core
