### ISSUE TITLE
S3 bucket with policy is always changed

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#5613] opened 2016-03-14 00:39 UTC
I have some Terraform code which looks like this (I have simplified it in an attempt to provide a MWE):

```
resource "aws_s3_bucket" "test" {
  bucket = "test-mzxdksdrdjkags"
  policy = <<EOF
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::test-mzxdksdrdjkags/*"
    }
  ]
}
EOF
}
```

Every time than I run `terraform plan` or `terraform apply`, changes are reported:

```
~ aws_s3_bucket.test
    policy: "{\"Statement\":[{\"Action\":\"s3:*\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":\"arn:aws:s3:::test-mzxdksdrdjkags/*\",\"Sid\":\"\"}],\"Version\":\"2008-10-17\"}" => "{\"Statement\":[{\"Action\":\"s3:*\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":\"arn:aws:s3:::test-mzxdksdrdjkags/*\"}],\"Version\":\"2008-10-17\"}"


Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by Shruti29** [comment] 2016-03-14 08:53
Not sure if the issue here is with the terraform.
In your template file, if you change your template file to 
`resource "aws_s3_bucket" "test" {`
  `  bucket = "test-mzxdksdrdjkags"`
  `  policy = <<EOF`
`   {`
 `     "Version": "2008-10-17",`
 `     "Statement": [`
   `    {`
      `    "Sid":"",`
     `     "Effect": "Allow",`
      `    "Principal": "*",`
     ` "Action": "s3:*",`
      `"Resource": "arn:aws:s3:::test-mzxdksdrdjkags/*"`
   ` }`
  `]`
`}`
`EOF`
`}`

**Comment by catsby** [comment] 2016-03-14 14:38
Hello – As @Shruti29 points out, the empty `"Sid":""` is necessary here. I believe it's this way if you were to create it via the web console as well.

Sorry for the trouble, but this looks like a policy formatting issue and not Terraform issue, so I'm going to close this. Let us know if you have other questions

**Closed by catsby** 2016-03-14 14:38 UTC
Labels: bug, provider/aws

**Comment by joshuaspence** [comment] 2016-03-15 00:22
Even with `"Sid": ""` I still have the same issue.

**Comment by joshuaspence** [comment] 2016-03-15 00:48
I think it's more than just `"Sid": ""`, let me experiment.

**Comment by joshuaspence** [comment] 2016-03-15 00:49
It seems that specifying actions as an array also causes issues:

```
resource "aws_s3_bucket" "test" {
  bucket = "test-mzxdksdrdjkags"
  policy = <<EOF
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": "*",
      "Action": [
        "s3:GetObject",
        "s3:GetObjectVersion"
      ],
      "Resource": "arn:aws:s3:::test-mzxdksdrdjkags/*"
    }
  ]
}
EOF
}
```

**Comment by l2ol33rt** [comment] 2016-06-02 01:01
Im seeing a similar issue on `v0.6.16`:
```
resource "aws_s3_bucket" "mybucket" {
    bucket = "mybucket.com"
    acl = "public-read"
    policy = <<POLICY
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":["arn:aws:s3:::mybucket.com/*"]
    }
  ]
}
POLICY
    website {
        index_document = "index.html"
    }
}
```

Output from a plan after its already been applied:
```
Path: plan.state

~ aws_s3_bucket.mybucket
    policy: "{\"Statement\":[{\"Action\":\"s3:GetObject\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":\"arn:aws:s3:::mybucket.com/*\",\"Sid\":\"\"}],\"Version\":\"2012-10-17\"}" => "{\"Statement\":[{\"Action\":[\"s3:GetObject\"],\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::mybucket.com/*\"],\"Sid\":\"\"}],\"Version\":\"2012-10-17\"}"
```

I originally had a `sid` and changed it to empty but that didnt seem to help.

Terraform v0.6.16

**Comment by jaygorrell** [comment] 2016-06-02 20:22
This is a duplicate of #4948 for anyone trying to track it down.
