### ISSUE TITLE
terraform v0.13.5 crash with terraform plan

### ISSUE THREAD

**Issue by rukawata** [hashicorp/terraform#26990] opened 2020-11-20 05:45 UTC
### Terraform Version

```
v0.13.5
```

### Terraform Configuration Files

```terraform
...
```
https://github.com/Azure/sap-hana/tree/kimforss_add_separator_where_missing

### Crash Output

https://gist.github.com/rukawata/8f34ce3853f8cfecd5a0d74e9beef0d2

### Expected Behavior

Not crash.

### Actual Behavior

Terraform crash.

### Steps to Reproduce

1. terraform apply
1. terraform plan

**Comment by jbardin** [comment] 2020-11-24 21:40
Duplicate of #26702

**Closed by jbardin** 2020-11-24 21:40 UTC
Labels: backend/azure, bug
