### ISSUE TITLE
Local provider resource types unknown to Terraform init

### ISSUE THREAD

**Issue by birchb1024** [hashicorp/terraform#26659] opened 2020-10-21 02:46 UTC
### Terraform Version
```
Terraform v0.13.3
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.13.0"
  required_providers {
    alpha = {
      source = "github.com/mobfox/alpha"
      version = ">=0.0.1"
    }
  }
}

provider "alpha" {
  environment = {
    servername = "api.example.com"
    api_token = "redacted"
  }
  executor = "python3"
  script = "hello_world.py"
  id_key = "id"
}

resource "json-file" "h" {
  // FAILS without this line: provider = alpha // because Terraform does not scan local providers for resource types.
  executor = "python3"
  script = "hello_world.py"
  id_key = "id"
  data = jsonencode({
      "name": "test-terraform-test-43",
      "created-by" : "Elvis Presley",
      "where" : "gracelands"
    })
}

```

### Debug Output
```
$ TF_LOG=trace terraform init
2020/10/21 13:24:17 [INFO] Terraform version: 0.13.3  
2020/10/21 13:24:17 [INFO] Go runtime version: go1.14.7
2020/10/21 13:24:17 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/10/21 13:24:17 [DEBUG] Attempting to open CLI config file: /home/bbirch1/.terraformrc
2020/10/21 13:24:17 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/10/21 13:24:17 [DEBUG] checking for credentials in "/home/bbirch1/.terraform.d/plugins"
2020/10/21 13:24:17 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/10/21 13:24:17 [DEBUG] will search for provider plugins in /home/bbirch1/.terraform.d/plugins
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: /home/bbirch1/.terraform.d/plugins is a symlink to /home/bbirch1/.terraform.d/plugins
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: found github.com/mobfox/alpha v0.0.1 for linux_amd64 at /home/bbirch1/.terraform.d/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: found github.com/mobfox/multiverse v0.0.1 for linux_amd64 at /home/bbirch1/.terraform.d/plugins/github.com/mobfox/multiverse/0.0.1/linux_amd64
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/terraform-providers/azuredevops v0.0.1 for linux_amd64 at /home/bbirch1/.terraform.d/plugins/registry.terraform.io/terraform-providers/azuredevops/0.0.1/linux_amd64
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/terraform-providers/multiverse v0.0.1 for linux_amd64 at /home/bbirch1/.terraform.d/plugins/registry.terraform.io/terraform-providers/multiverse/0.0.1/linux_amd64
2020/10/21 13:24:17 [DEBUG] ignoring non-existing provider search directory /home/bbirch1/.local/share/terraform/plugins
2020/10/21 13:24:17 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2020/10/21 13:24:17 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2020/10/21 13:24:17 [INFO] CLI command args: []string{"init"}

Initializing the backend...
2020/10/21 13:24:17 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/10/21 13:24:17 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/10/21 13:24:17 [DEBUG] New state was assigned lineage "0c0fdac8-4570-532b-1ebe-f2571f6c67d9"
2020/10/21 13:24:17 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/10/21 13:24:17 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/10/21 13:24:17 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: found github.com/mobfox/alpha v0.0.1 for linux_amd64 at .terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64
2020/10/21 13:24:17 [TRACE] getproviders.SearchLocalDirectory: found github.com/mobfox/multiverse v0.0.1 for linux_amd64 at .terraform/plugins/github.com/mobfox/multiverse/0.0.1/linux_amd64
2020/10/21 13:24:17 [TRACE] providercache.fillMetaCache: including .terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64 as a candidate package for github.com/mobfox/alpha 0.0.1
2020/10/21 13:24:17 [TRACE] providercache.fillMetaCache: including .terraform/plugins/github.com/mobfox/multiverse/0.0.1/linux_amd64 as a candidate package for github.com/mobfox/multiverse 0.0.1
2020/10/21 13:24:18 [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/plugins
2020/10/21 13:24:18 [DEBUG] checking for provisioner in "."
2020/10/21 13:24:18 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/10/21 13:24:18 [DEBUG] checking for provisioner in "/home/bbirch1/.terraform.d/plugins"
2020/10/21 13:24:18 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2020/10/21 13:24:18 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/10/21 13:24:18 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/10/21 13:24:18 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/10/21 13:24:18 [TRACE] statemgr.Filesystem: read snapshot with lineage "97b447f4-a139-a4e1-0bef-c422f8f276e0" serial 3
2020/10/21 13:24:18 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/10/21 13:24:18 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins

Initializing provider plugins...
2020/10/21 13:24:18 [TRACE] getproviders.SearchLocalDirectory: found github.com/mobfox/alpha v0.0.1 for linux_amd64 at .terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64
2020/10/21 13:24:18 [TRACE] getproviders.SearchLocalDirectory: found github.com/mobfox/multiverse v0.0.1 for linux_amd64 at .terraform/plugins/github.com/mobfox/multiverse/0.0.1/linux_amd64
2020/10/21 13:24:18 [TRACE] providercache.fillMetaCache: including .terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64 as a candidate package for github.com/mobfox/alpha 0.0.1
2020/10/21 13:24:18 [TRACE] providercache.fillMetaCache: including .terraform/plugins/github.com/mobfox/multiverse/0.0.1/linux_amd64 as a candidate package for github.com/mobfox/multiverse 0.0.1
2020/10/21 13:24:18 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/10/21 13:24:18 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
- Using previously-installed github.com/mobfox/alpha v0.0.1
- Using previously-installed github.com/mobfox/multiverse v0.0.1
- Finding latest version of hashicorp/json-file...
2020/10/21 13:24:18 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/json-file/versions
2020/10/21 13:24:18 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/json-file/versions
2020/10/21 13:24:18 [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/plugins
2020/10/21 13:24:18 [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/plugins
2020/10/21 13:24:18 [DEBUG] GET https://registry.terraform.io/v1/providers/-/json-file/versions
2020/10/21 13:24:18 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/json-file/versions

Error: Failed to install provider                                                                                                                                                             

Error while installing hashicorp/json-file: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/json-file
```

### Expected Behavior
I had expected that `terraform init` would load the local plugins and interrogate them to discover what resource types it provides, since this is in the `schema.Provider ResourcesMap`. However the logs seem to show it does not load the plugins even if it knows there is a new binary. 

I would expect to see lines showing the plugin has started in the init log such as these
```
2020-10-21T13:43:16.950+1100 [DEBUG] plugin: starting plugin: path=.terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64/terraform-provider-alpha args=[.terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64/terraform-provider-alpha]
2020-10-21T13:43:16.951+1100 [DEBUG] plugin: plugin started: path=.terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64/terraform-provider-alpha pid=52611
2020-10-21T13:43:16.951+1100 [DEBUG] plugin: waiting for RPC address: path=.terraform/plugins/github.com/mobfox/alpha/0.0.1/linux_amd64/terraform-provider-alpha
2020-10-21T13:43:16.969+1100 [DEBUG] plugin.terraform-provider-alpha: 2020/10/21 13:43:16 multiverse provider name : alpha
2020-10-21T13:43:16.970+1100 [DEBUG] plugin.terraform-provider-alpha: 2020/10/21 13:43:16 provider alpha has resource alpha
2020-10-21T13:43:16.970+1100 [DEBUG] plugin.terraform-provider-alpha: 2020/10/21 13:43:16 provider alpha has resource json-file
```
These lines came from `terraform plan` the last three lines are from my fmt.log() statements.

### Actual Behavior
`terraform init` throws an error as above.

### Steps to Reproduce
1. Install a new provider binary that has multiple resource types locally. 
2. have a TF file which uses one of the resource types where resource type name is not equal to provider name
3. terraform init

### Workarounds
I found that adding the provider in the resource block fixes the issue, but this is annoying and unnecessary. It does show that `init` parses the user code, but ignores the plugins!
```
resource "json-file" "h" {
  provider = alpha // because Terraform does not scan local providers for resource types.
```

This did not work: `rm -rf ~/.terraform.d/`

### Additional Context
My provider is based on the multiverse provider.

**Comment by alisdair** [comment] 2020-10-21 16:15
Hi @birchb1024, thanks for reporting this.

I don't think this is related to the provider being locally installed, but is instead a bug in the provider. [Terraform requires that all resources are prefixed with the provider name](https://www.terraform.io/docs/extend/best-practices/naming.html#resource-names):

> Resource names are nouns, since resource blocks each represent a single object Terraform is managing. Resource names must always start with their containing provider's name followed by an underscore, so a resource from the provider `postgresql` might be named `postgresql_database`.

Note that it is also conventional to use underscores to join words, not dashes. I'd suggest the correct name for this resource type would be `alpha_json_file`.

I'm going to close this issue because I believe Terraform is working as intended. If I've misunderstood something, just let me know and we can reopen it.

**Closed by alisdair** 2020-10-21 16:15 UTC
Labels: bug, new

**Comment by birchb1024** [comment] 2020-10-23 01:29
OK Thanks for your response. Maybe I will submit a feature issue for removing the provider name from resource names. Note that the above is just a convention - the `provider = ` clause is always available to mavericks. :-)
