### ISSUE TITLE
Text file busy with TF_PLUGIN_CACHE_DIR set if provider is running

### ISSUE THREAD

**Issue by finnag** [hashicorp/terraform#32919] opened 2023-03-26 20:48 UTC
### Terraform Version

```shell
Terraform v1.4.2
on linux_amd64

Also fails with v1.5.0dev , main at 9d93415d4ca7f
```

### Terraform Configuration Files

```terraform
data "external" dummy {
  program = [ "sh", "-c", "sleep 5; echo {}" ]
}
```

### Debug Output

https://gist.github.com/finnag/d63edf7e4eaf36f7434af40e8354d784

### Expected Behavior

It should not have tried to overwrite the running binary with the same content again...

### Actual Behavior

It tried to overwrite the binary of a provider that was already running, and got

```
 Error: Failed to install provider
│ 
│ Error while installing hashicorp/external v2.3.1: open
│ /home/finnag/terraform-bug-repro/cachedir/registry.terraform.io/hashicorp/external/2.3.1/linux_amd64/terraform-provider-external_v2.3.1_x5:
│ text file busy
╵
```

### Steps to Reproduce

```sh
mkdir terraform-bug-repro
cd terraform-bug-repro
mkdir d1 d2
cat > d1/bug.tf << EOF
data "external" dummy {
  program = [ "sh", "-c", "sleep 5; echo {}" ]
}
EOF
cp d1/bug.tf d2/bug.tf
mkdir cachedir
TF_PLUGIN_CACHE_DIR=`pwd`/cachedir
export TF_PLUGIN_CACHE_DIR

( cd d1 && terraform init && terraform plan ) & sleep 2; ( cd d2 && TF_LOG=trace terraform init)
```

### References

#32915

**Comment by jbardin** [comment] 2023-03-27 12:48
Duplicate of #32915

**Closed by jbardin** 2023-03-27 12:48 UTC
Labels: bug, new
