### ISSUE TITLE
Multiple terraform_remote_state instances do not work

### ISSUE THREAD

**Issue by jambt** [hashicorp/terraform#17451] opened 2018-02-27 13:48 UTC
Hi,

I experienced a problem using multiple instances of terraform_remote_state as described below.
### Terraform Version
```
Terraform v0.11.3
```

### Terraform Configuration Files
```hcl
variable "storage_account_name" {}
variable "container_name" {}
variable "access_key" {}

data "terraform_remote_state" "global" {
  backend = "azure"

  config {
    storage_account_name = "${var.storage_account_name}"
    container_name = "${var.container_name}"
    access_key = "${var.access_key}"
    key = "global.tfstate"
  }
  depends_on = ["data.terraform_remote_state.prod"]
}

data "terraform_remote_state" "prod" {
  backend = "azure"

  config {
    storage_account_name = "${var.storage_account_name}"
    container_name = "${var.container_name}"
    access_key = "${var.access_key}"
    key = "prod.tfstate"
  }
}


output "test_global" {
  value = "${data.terraform_remote_state.global.storage_name}"
}
output "test_prod" {
  value = "${data.terraform_remote_state.prod.storage_name}"
}
```

### Debug Output
https://gist.github.com/jambt/3fea8c2850a210a33fa05118959acb8e

### Expected Behavior
Get two storage names (one of `prod`, one of `global`)

### Actual Behavior
An error message is shown:
    

> * output.test_global: Resource 'data.terraform_remote_state.global' does not have attribute 'storage_name' for variable 'data.terraform_remote_state.global.storage_name'

### Steps to Reproduce
1. Create two different remote states both having an output "storage_name"
2. Create a new folder with the above terraform file
3. `terraform init`
4. `terraform apply`

### Additional Context
Using only one remote_state (with the respective output), yields the desired output.

Some observations:

I get a different failures, if I remove the `depends_on` configuration in the remote state, since both states are fetched concurrently. This results in problems.

Whenever the first output (`global`) is removed, `terraform apply` results in the expected for the `prod` value and a scheduled "read (<=)" action on `global`.

**Comment by jbardin** [comment] 2018-02-27 16:43
Duplicate of #17316

**Closed by jbardin** 2018-02-27 16:43 UTC
