### ISSUE TITLE
kubernets backend has error when secret_suffix ends with -<number> 

### ISSUE THREAD

**Issue by greenkiwi** [hashicorp/terraform#33995] opened 2023-10-06 00:57 UTC
### Terraform Version

```shell
1.6.0
```

### Terraform Configuration Files

```terraform
  backend "kubernetes" {
    secret_suffix     = "sbx-390"
    namespace         = "terraform"
  }
```

### Debug Output
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: index out of range [390] with length 1
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2fb0420?, 0xc000e7d7d0?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*RemoteClient).getSecrets(0xc000603740)
	/home/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/client.go:109 +0x6c5
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*RemoteClient).Get(0x60?)
	/home/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/client.go:54 +0x25
github.com/hashicorp/terraform/internal/states/remote.(*State).refreshState(0xc0006037a0)
	/home/runner/work/terraform/terraform/internal/states/remote/state.go:138 +0x28
github.com/hashicorp/terraform/internal/states/remote.(*State).RefreshState(0xc00083f020?)
	/home/runner/work/terraform/terraform/internal/states/remote/state.go:1[31](https://github.com/turo/dev-sbx-deployments/actions/runs/6411568781/job/17407278639?pr=390#step:9:32) +0x79
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*Backend).StateMgr(0x38c9540?, {0x317d2c5?, 0x7?})
	/home/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/backend_state.go:89 +0x70
github.com/hashicorp/terraform/internal/backend/local.(*Local).StateMgr(0xc0008f16c0?, {0x317d2c5?, 0xc000d48140?})
	/home/runner/work/terraform/terraform/internal/backend/local/backend.go:245 +0x382
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0008f16c0, {0xc000050070, 0x0, 0x0})
	/home/runner/work/terraform/terraform/internal/command/init.go:222 +0x1470
github.com/mitchellh/cli.(*CLI).Run(0xc000743900)
	/home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.realMain()
	/home/runner/work/terraform/terraform/main.go:[33](https://github.com/turo/dev-sbx-deployments/actions/runs/6411568781/job/17407278639?pr=390#step:9:34)9 +0x1eab
main.main()
	/home/runner/work/terraform/terraform/main.go:64 +0x13
Error: Terraform exited with code 11.
Error: Process completed with exit code 1.
```

### Expected Behavior

I would expect that the new feature allowing for larger state files through using multiple secrets would take the secret suffix into account before deciding that it is a multi-segment state file.

### Actual Behavior

We see the following error.  It appears that it is reading in the -390 from the secret suffix part of the name and using that as an index for an array access.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: index out of range [390] with length 1
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2fb0420?, 0xc000e7d7d0?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*RemoteClient).getSecrets(0xc000603740)
	/home/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/client.go:109 +0x6c5
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*RemoteClient).Get(0x60?)
	/home/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/client.go:54 +0x25
github.com/hashicorp/terraform/internal/states/remote.(*State).refreshState(0xc0006037a0)
	/home/runner/work/terraform/terraform/internal/states/remote/state.go:138 +0x28
github.com/hashicorp/terraform/internal/states/remote.(*State).RefreshState(0xc00083f020?)
	/home/runner/work/terraform/terraform/internal/states/remote/state.go:1[31](https://github.com/turo/dev-sbx-deployments/actions/runs/6411568781/job/17407278639?pr=390#step:9:32) +0x79
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*Backend).StateMgr(0x38c9540?, {0x317d2c5?, 0x7?})
	/home/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/backend_state.go:89 +0x70
github.com/hashicorp/terraform/internal/backend/local.(*Local).StateMgr(0xc0008f16c0?, {0x317d2c5?, 0xc000d48140?})
	/home/runner/work/terraform/terraform/internal/backend/local/backend.go:245 +0x382
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0008f16c0, {0xc000050070, 0x0, 0x0})
	/home/runner/work/terraform/terraform/internal/command/init.go:222 +0x1470
github.com/mitchellh/cli.(*CLI).Run(0xc000743900)
	/home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.realMain()
	/home/runner/work/terraform/terraform/main.go:[33](https://github.com/turo/dev-sbx-deployments/actions/runs/6411568781/job/17407278639?pr=390#step:9:34)9 +0x1eab
main.main()
	/home/runner/work/terraform/terraform/main.go:64 +0x13
Error: Terraform exited with code 11.
Error: Process completed with exit code 1.
```

### Steps to Reproduce

1. run terraform 1.6 
2. configure k8s access -- I used docker for desktop local k8s for this
3. create namespace `terraform` -- `kubectl create ns terraform`
4. use the following config file
```
terraform {
  required_version = ">= 1.1.0, < 2.0.0"

  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">=2.12.1"
    }
  }

  backend "kubernetes" {
    secret_suffix     = "sbx-390"
    config_path      = "~/.kube/config"
    namespace         = "terraform"
  }
}

provider "kubernetes" {
}
```
5. run `terraform init`

See error:
```
❯ terraform init

Initializing the backend...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: index out of range [390] with length 1
goroutine 1 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x3bbc880?, 0xc000530450?})
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*RemoteClient).getSecrets(0xc000a4afc0)
        /Users/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/client.go:109 +0x6c5
github.com/hashicorp/terraform/internal/backend/remote-state/kubernetes.(*RemoteClient).Get(0x3d93953?)
        /Users/runner/work/terraform/terraform/internal/backend/remote-state/kubernetes/client.go:54 +0x25
github.com/hashicorp/terraform/internal/states/remote.(*State).refreshState(0xc000a4b020)
        /Users/runner/work/terraform/terraform/internal/states/remote/state.go:138 +0x28
github.com/hashicorp/terraform/internal/states/remote.(*State).RefreshState(0xc0005cc380?)
        /Users/runner/work/terraform/terraform/internal/states/remote/state.go:131 +0x79
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0005cc380, {0xc0001ca010, 0x0, 0x0})
        /Users/runner/work/terraform/terraform/internal/command/init.go:228 +0x150c
github.com/mitchellh/cli.(*CLI).Run(0xc00063ac80)
        /Users/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.realMain()
        /Users/runner/work/terraform/terraform/main.go:339 +0x1eab
main.main()
        /Users/runner/work/terraform/terraform/main.go:64 +0x13
```

### Additional Context

It appears to be a direct result of this feature:

> backend/kubernetes: The Kubernetes backend is no longer limited to storing states below 1MiB in size, and can now scale by splitting state across multiple secrets. (https://github.com/hashicorp/terraform/pull/29678)

### References

https://github.com/hashicorp/terraform/pull/29678

**Comment by crw** [comment] 2023-10-06 22:14
FYI k8s backend [CODEOWNERS](https://github.com/hashicorp/terraform/blob/main/CODEOWNERS) @jrhouston @alexsomesan. Thanks!

**Comment by bschaatsbergen** [comment] 2024-09-02 18:22
Hey @greenkiwi 👋🏼, thank you for raising this issue and helping us identify it. Your feedback is incredibly valuable. I’ve pinpointed the cause of the error you encountered in #35641 and will be addressing it with a pull request shortly. Thanks again!

**Comment by crw** [comment] 2024-09-03 16:44
As this will be fixed as part of https://github.com/hashicorp/terraform/issues/35641, closing as a duplicate (although we recognize this issue came earlier). Thanks very much for the report!

**Closed by crw** 2024-09-03 16:44 UTC
Labels: bug, backend/k8s, new
