### ISSUE TITLE
terraform crashed!

### ISSUE THREAD

**Issue by 23karishma** [hashicorp/terraform#4030] opened 2015-11-24 06:05 UTC
terraform0.6.7 crashed while launching the aws instance. Failure happened during terraform plan.

**Comment by radeksimko** [comment] 2015-11-24 07:41
Hi @23karishma ,
would you mind attaching the crash log (minus any secrets)? It's usually placed in your work directory as `crash.log`.

I'm afraid we're not able to reproduce this without the log.

**Comment by phinze** [comment] 2015-12-09 16:34
Hi @23karishma, if you have that crash log please follow up, but for now I'm going to close this out since there's not much we can do without it. Hopefully was just a bug that was fixed in 0.6.8! :grinning:

**Closed by phinze** 2015-12-09 16:34 UTC
Labels: bug, crash, waiting-response

**Comment by 23karishma** [comment] 2015-12-10 05:10
Hello,

Sorry, but log i cant provide you.
But i got this bug when i was trying to come up with some new instance in
aws, My control node was aws node only,and its failed during terraform
plan. Then i have installed the older version of terraform and worked
perfectly for me.

Thanks,
Karishma

**Comment by phinze** [comment] 2015-12-10 16:14
Thanks for following up, @23karishma - if your control node was an AWS node that bug is almost definitely fixed in 0.6.8 :+1:
