### ISSUE TITLE
Cloudformation with Terraform: Error: aws_cloudformation_stack.s3_endpoint_cf: parameters (subnet_ids): '' expected type 'string', got unconvertible type '[]interface {}' 

### ISSUE THREAD

**Issue by AleksandarTokarev** [hashicorp/terraform#24673] opened 2020-04-15 09:10 UTC
### Terraform Version
Terraform v0.11.2
+ provider.aws v2.57.0
### Terraform Configuration Files
```
variable "subnet_ids" {
  type = "list"

  default = [
    "subnet-xx",
    "subnet-yy",
    "subnet-zz"
  ]

resource "aws_cloudformation_stack" "s3_endpoint_cf" {
  name = "alex-api-16-test"
  tags = "${local.tagging_standard_tags}"

  parameters = {
    subnetids = ["${var.subnet_ids}"]
  }

  template_body = <<STACK
  {
  "Parameters" : {
      "subnetids" : {
        "Type" : "List<AWS::EC2::Subnet::Id>",
        "Description" : "Enter the CIDR block for the VPC. Default is 10.0.0.0/16."
      }
    },
    "Resources": {
        "HttpApi": {
        "Type": "AWS::ApiGatewayV2::Api",
        "Properties": {
            "Name": "HTTP Proxy",
            "Description": "HTTP proxy",
            "ProtocolType": "HTTP"
            }
        },
        "HttpApiRoute": {
          "Type": "AWS::ApiGatewayV2::Route",
          "Properties": {
              "ApiId": {
                  "Ref": "HttpApi"
              },
              "RouteKey": "ANY /{proxy+}",
              "AuthorizationType": "NONE",
              "Target": {
                "Fn::Join": [
                    "/",
                    [
                        "integrations",
                        {
                            "Ref": "HttpApiIntegration"
                        }
                    ]
                ]
            }
          }
        },
        "HttpApiIntegration": {
          "Type": "AWS::ApiGatewayV2::Integration",
          "Properties": {
              "ApiId": {
                  "Ref": "HttpApi"
              },
              "Description": "HTTP Private Integration",
              "IntegrationType": "HTTP_PROXY",
              "ConnectionType": "VPC_LINK",
              "ConnectionId": {
                "Ref": "HttpVpcLink"
              },
              "IntegrationUri": "arnOfListener",
              "PayloadFormatVersion": "1.0",
              "IntegrationMethod": "ANY"
          }
        },
        "HttpApiStage": {
        "Type": "AWS::ApiGatewayV2::Stage",
        "Properties": {
            "StageName": "$default",
            "Description": "Default Stage",
            "AutoDeploy": "true",
            "ApiId": {
                "Ref": "HttpApi"
            }
          }
        },
        "HttpVpcLink": {
          "Type" : "AWS::ApiGatewayV2::VpcLink",
          "Properties" : {
              "Name" : "HTTP 12",
              "SubnetIds" : { "Ref" : "subnetids" },
              "SecurityGroupIds" : [ "sg-xx"]
            }
        }
    }
  }
  STACK
}

}
```

### Crash Output
Error: aws_cloudformation_stack.s3_endpoint_cf: parameters (subnet_ids): '' expected type 'string', got unconvertible type '[]interface {}'
### Expected Behavior
SubnetIds should have been populated with the array of subnets ["subnet-xx", "subnet-yy","subnet-zz"]

### Actual Behavior
Terraform fails

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

###Additional Context
running on macOS 
Here is my use case. I want to create the new API Gatewayv2 using Cloudformation, and i want to pass the subnet id's that i have defined as a list. If i set the subnetids inline like this
```"SubnetIds" : [ "subnet-xx","subnet-yy", "subnet-zz"],```
, everything is fine, but obviously when trying to pass it as a variable it does not work.
Even if i use (without [] it is the same)
``` 
parameters = {
    subnetids = "${var.subnet_ids}"
  }
```
I found a workaround by using
```
parameters = {
    subnetids = "${join(", ", var.subnet_ids)}"
  }
```
but this is not really a clean solution.
I am limited to terraform 0.11.2 because our Jenkins runs on that version.
Any help?
Thanks a lot

**Comment by danieldreier** [comment] 2020-04-16 23:46
We are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. We're actively working on Terraform 0.13. I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now.

I think your best way to get help is to try reproducing this with Terraform 0.12.24. If you can reproduce the same error, we can move this over to the AWS provider, and maybe get it fixed. In the meantime, I'm hesitant to send them an issue that only happens with 0.11. Is that something you feel able to try?

**Comment by apparentlymart** [comment] 2020-06-26 00:20
Hi @AleksandarTokarev!

We didn't hear back from you after @danieldreier's last comment, so I'm going to close this issue for now. If you're able to try this out with Terraform 0.12 or later and see a similar problem, I recommend opening an issue for it in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws), because this issue seems to be specific to the `aws_cloudformation_stack` resource type and would thus need to be addressed by the AWS provider maintainers rather than the Terraform Core maintainers. Thanks!

**Closed by apparentlymart** 2020-06-26 00:20 UTC
Labels: waiting-response
