### ISSUE TITLE
terraform plan shows wrong number of things to add at the end 

### ISSUE THREAD

**Issue by alexd765** [hashicorp/terraform#15565] opened 2017-07-17 08:45 UTC
## Issue

Terraform plan tells you the number of things it wants to create at the end. This number is wrong for us by a factor of 2 recently.

## Terraform Version
v0.9.11

It worked as expected on v0.9.3. I don't know about the versions in between.

## Example
```
+ aws_instance.new-worker.1
    ami:                                       "ami-bfc722c6"
    associate_public_ip_address:               "<computed>"
    availability_zone:                         "<computed>"
    ebs_block_device.#:                        "<computed>"
    ephemeral_block_device.#:                  "<computed>"
    iam_instance_profile:                      "worker-staging"
    instance_state:                            "<computed>"
    instance_type:                             "t2.small"
    ipv6_address_count:                        "<computed>"
    ipv6_addresses.#:                          "<computed>"
    key_name:                                  "staging_terraform_ssh"
    network_interface.#:                       "<computed>"
    network_interface_id:                      "<computed>"
    placement_group:                           "<computed>"
    primary_network_interface_id:              "<computed>"
    private_dns:                               "<computed>"
    private_ip:                                "<computed>"
    public_dns:                                "<computed>"
    public_ip:                                 "<computed>"
    root_block_device.#:                       "1"
    root_block_device.0.delete_on_termination: "true"
    root_block_device.0.iops:                  "<computed>"
    root_block_device.0.volume_size:           "50"
    root_block_device.0.volume_type:           "gp2"
    security_groups.#:                         "1"
    security_groups.1741186181:                "worker-staging"
    source_dest_check:                         "true"
    subnet_id:                                 "<computed>"
    tags.%:                                    "2"
    tags.Name:                                 "new-worker2"
    tags.Role:                                 "new-worker"
    tenancy:                                   "<computed>"
    volume_tags.%:                             "<computed>"
    vpc_security_group_ids.#:                  "<computed>"

~ aws_route53_record.new-worker.0
    records.#: "" => "<computed>"

+ aws_route53_record.new-worker.1
    fqdn:      "<computed>"
    name:      "new-worker2"
    records.#: "<computed>"
    ttl:       "300"
    type:      "A"
    zone_id:   "Z3IH0Y00N6F6RO"


Plan: 4 to add, 1 to change, 0 to destroy.
```

### Expected Behavior
 2 to add, ...

### Actual Behavior
4 to add, ...

**Comment by apparentlymart** [comment] 2017-07-17 21:18
Hi @alexd765! Thanks for reporting this and sorry for the confusing behavior.

This regression was fixed in #15344, and the fix is included in the current 0.10 beta and will, therefore, be in the 0.10.0 final release soon.

The underlying issue here is that Terraform is inadvertently counting any resources it refreshes in this tally, which in the normal case (where things are refreshed implicitly as part of `plan`) causes the value to be double what is expected. So I can confirm that it's an entirely cosmetic issue and doesn't affect what Terraform will actually do when applied, but I do understand that it's disconcerting to see Terraform give inconsistent output like this.

Since there's already a fix merged for this, I'm going to close it. Thanks again for reporting it.

**Closed by apparentlymart** 2017-07-17 21:18 UTC
