### ISSUE TITLE
Generic `deepmerge()` function

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform#31815] opened 2022-09-19 16:08 UTC
### Terraform Version

```shell
1.2.9
```

### Use Cases

Merging of files read via jsondecode and yamldecode, merge of nested maps and objects tree typically used for configuration or lookups 

### Attempted Solutions

- `merge()`: does not recursively merge values that are objects and maps

- Kyle Kotowik's `deepmerge` module: is computationally intensive (since the tree must be flattened, merged, then re-created) and is currently not usable if `infracost` is used for PR costing

- Provider: not attempted yet but it is a fallback solution if this proposal is not accepted, because more work to create and maintain than the proposed builtin, and more work to use (since will have to add a provider, define data source etc)

### Proposal

The `deepmerge(list_of_items_to_merge, merge_config})` would behave like this: 

Takes a list of items to merge `[item1, item2, ...]`, and an optional merge-configuration object `{list_merge_strategy="replace", type_mismatch_strategy="complex_wins"}`, and returns a single item that is a merge of all items, based on the merge configuration.

The merge algorithm for `list_of_items_to_merge` is as follows: 

- items of different types are handled based on the `type_mismatch_strategy`:
      - `complex_wins`: object and map win over lists which win over literals; _the losers are removed from the merge_; 
      - `abort`: abort the terraform plan or apply
- if all items are literals, the rightmost item is used
- if the remaining items are lists, the `list_merge_strategy` specified (which defaults to "replace") is applied:
      - `replace`: the list of the right most argument applies
      - `concat`: the sequence of lists is concatenated in the same order as arguments
      - `merge`: each list is appended with `null` so they all have the same length, then the `deepmerge()` is applied to each slice through the lists
- if the remaining items are maps or objects (the most common case), if more than one defines the same key or attribute, the `deepmerge()` is applied to the sequence of associated values across all the items

This is backwards compatible with all versions of terraform, and should cover 99% of use cases. 

Examples: 

`deepmerge([a, b, c, d])`:
- if a, b, c, d are all literals (string, bool, number), then d is return
- if all items are lists, then they are all merged according to `list_merge_strategy`
- if a and b are lists and c and d are literals, then c and d are discarded and a and b are merged according to `list_merge_strategy`
- if a and b are maps or objects then c and d are discarded and for each key in a, b, `deepmerge()` is called on the corresponding list of associated values, and objects that don't have the key are not included. So if `a` has `key1` and `key2`, and `b` has `key1` and `key3`, then the set of keys of the result is `(key1, key2, key3)` and there will be 3 calls to `deepmerge()`:  `deepmerge([a.key1, b.key1])`, `deepmerge([a.key2])`, and `deepmerge([b.key3])` (the merge-config is passed to these but left out here for simplicity)
- if all objects are maps or objects then the previous rule is applied to all items instead of just a and b

### References

Many threads of discussion about this on community forum and github issues related to `merge()`. Also, the table in https://github.com/hashicorp/terraform/issues/24987#issuecomment-719089236.

**Comment by crw** [comment] 2022-09-19 20:46
Thanks for gathering these requirements from the issues.

**Comment by sftim** [comment] 2022-12-02 17:27
I'd expect `deepmerge()` to take items with the same top-level as its arguments. Otherwise it will not have an interface that matches `merge()`.

Example documentation:
> `deepmerge` takes an arbitrary number of maps or objects, and returns a single map or object that contains a merged set of elements from all arguments. If the elements are maps or objects, this function performs a deep merge; if they are plain types (strings, numbers, or bools) then the behavior is the same as `merge`
> 
> If more than one given map or object defines the same key or attribute, then the one that is later in the argument sequence takes precedence. If the argument types do not match, the resulting type will be an object matching the type structure of the attributes after the merging rules have been applied.

**Comment by schollii** [comment] 2022-12-07 03:25
I don't understand the statement, so I'm not sure what might need changing.

**Comment by sftim** [comment] 2022-12-07 09:40
I'm saying that `deepmerge` should have the same interface as `merge`.

**Comment by schollii** [comment] 2022-12-07 10:59
I think you cannot have same interface as merge AND support multiple ways of deep merging, without resorting to multiple deepmerge functions. 

Could a deepmerge function check the first argument (a map) for a certain structure, like the presence of a key "_options_", if the map fits it uses it to choose the merge behavior and applies merge to remainder of map args. The docs would still be straightforward addition to what you wrote: "... If the first arg is a map that satisfis certain conditions, it will be used to control the merge of lists/map/object elements of the map args, instead of being included in the merge.

**Comment by sftim** [comment] 2022-12-07 11:44
The first argument could be a _list_ of merge options and then still support every input that `merge` can accept.

**Comment by schollii** [comment] 2022-12-07 14:15
That works, although using a map has several advantages over a list:

- it is optional since it is of the same type as the remaining args ... Or can a function be coded so as to accept a first arg of 2 types and take action accordingly? 
-  each option is optional : with a list the options are positional, whereas with a map they are named, this allows you to specify only those options that are different from the default, not possible with list 

It would be nice to not have to specify the options at all, and to be able to only specify those that need to be.

**Comment by yordis** [comment] 2023-07-02 07:08
Hey peeps, any updates over here?

**Comment by aladdin-atypon** [comment] 2023-10-25 15:30
Ping!

**Comment by crw** [comment] 2023-10-25 21:11
This would likely need to be implemented as a provider (external) function, if or when that becomes a possibility. Please see: https://github.com/hashicorp/terraform/issues/27696.

**Comment by crw** [comment] 2024-03-06 23:52
Thank you for your continued interest in this issue. 

[Terraform version 1.8](https://github.com/hashicorp/terraform/blob/v1.8.0-beta1/CHANGELOG.md) launches with support of provider-defined functions. It is now possible to implement your own functions! We would love to see this implemented as a provider-defined function. 

Please see the [provider-defined functions documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions) to learn how to implement functions in your providers. If you are new to provider development, learn how to [create a new provider](https://developer.hashicorp.com/terraform/plugin/framework) with the Terraform Plugin Framework. If you have any questions, please visit the [Terraform Plugin Development category in our official forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

We hope this feature unblocks future function development and provides more flexibility for the Terraform community. Thank you for your continued support of Terraform!

**Comment by hegerdes** [comment] 2024-04-14 17:05
It is great to see the possibility to implement this via provider functions and I really believe these can be useful for provider specific tasks but recursive merge is a generic problem and it seems like that hashicorp just outsources the problem to the providers. 

Creating providers with a specific resource to solve such a problem was possible before and has been done by people, the problem is that this open the door for non standard implementations for the same function/task. Deep merge is not an obscure function and people wanting this since TF v0.12.16 (2020 #24987) with 129 upvotes since locked.

Having a great standard library that solves a common problems that everybody has is impotent, failing this results in so much effort and 100 different implementations from each provider that sort of do the same - except when they dont. In the extrem the results can be seen in the javerscript world.

Sad to see that the built in functions in terraform are kind of limited and dont get the attention they deserve.

**Comment by sftim** [comment] 2024-04-14 20:31
I actually expect that either Terraform or OpenTofu (or both) will make some of the built-in functions be syntactic sugar for functions from a built-in provider. For example, `base64decode` as an alias for `provider::base64::decode`.
If I guessed right and that is the direction of travel, having deep merge live in a provider makes a lot of sense.

**Comment by isometry** [comment] 2024-04-14 20:53
I've successfully drafted a `terraform-provider-deepmerge` using the new provider functionality in Terraform 1.8.0. It uses mergo under the hood and currently exposes two functions: `provider::deepmerge::replace` (mergo with "WithOverride" for recursive merge-like behaviour), and `provider::deepmerge::append` (mergo with both "WithOverride" and "WithAppendSlice") to have lists append rather than overwrite. At present, no special support for merging of Sets (they're just treated as dumb lists), nor any advanced merge-lists-by-key logic.
Any thoughts on the function naming or basic functionality before I publish?

**Comment by isometry** [comment] 2024-04-14 21:12
> I actually expect that either Terraform or OpenTofu (or both) will make some of the built-in functions be syntactic sugar for functions from a built-in provider. For example, `base64decode` as an alias for `provider::base64::decode`.

To be fair, ~95% of Terraforms built-in functions are already just calls to the function library in go-cty[1] (including the existing `merge`[2]). Those wanting a builtin `deepmerge` should probably contribute an implementation there rather than here.

[1]: https://github.com/hashicorp/terraform/blob/main/internal/lang/functions.go
[2]: https://github.com/zclconf/go-cty/blob/main/cty/function/stdlib/collection.go

**Comment by olivers-xaxis** [comment] 2024-04-15 00:31
> I've successfully drafted a `terraform-provider-deepmerge` using the new provider functionality... 
> Any thoughts on the function naming or basic functionality before I publish?

Would it make sense for your provider to be slightly higher level, eg "tree" and provide functions related to tree structures, like deepmerge() would be the first function. Community could contribute more, making "tree" the go-to provider for all tree related processing. 

Otherwise we could end up with a pile of tiny providers, but maybe that's not such a bad thing either.

**Comment by schollii** [comment] 2024-04-15 00:33
> I've successfully drafted a `terraform-provider-deepmerge` using the new provider functionality... 
> Any thoughts on the function naming or basic functionality before I publish?

Nice! Would it make sense for your provider to be slightly higher level, eg "tree" and provide functions related to tree structures, like deepmerge() would be the first function. Community could contribute more, making "tree" the go-to provider for all tree related processing. 

Otherwise we could end up with a pile of tiny providers, but maybe that's not such a bad thing either.

**Comment by luis-guimaraes-exoawk** [comment] 2024-04-15 10:54
> > I actually expect that either Terraform or OpenTofu (or both) will make some of the built-in functions be syntactic sugar for functions from a built-in provider. For example, `base64decode` as an alias for `provider::base64::decode`.
> 
> To be fair, ~95% of Terraforms built-in functions are already just calls to the function library in go-cty[1](https://github.com/hashicorp/terraform/blob/main/internal/lang/functions.go) (including the existing `merge`[2](https://github.com/zclconf/go-cty/blob/main/cty/function/stdlib/collection.go)). Those wanting a builtin `deepmerge` should probably start by contributing an implementation there rather than here.

This seems like the correct answer to this problem. It would help standardize a deepmerge function instead of relying on providers to implement it "correctly".

**Comment by isometry** [comment] 2024-04-15 21:17
I've published an initial implementation with `mergo` semantics at https://registry.terraform.io/providers/isometry/deepmerge/latest

Code is at https://github.com/isometry/terraform-provider-deepmerge, contributions welcome!

`tfplugindocs` generated documentation "isn't great", and I haven't spent the time to work out how to bend it to my will yet, but usage is simple:

```hcl
output "test" {
  value = provider::deepmerge::mergo(local.map1, local.map2)
}
```

An arbitrary number of arbitrarily deep maps are theoretically supported, with similar merge logic to the built-in `merge` by default (i.e. key-values overridden with priority to the right). As it's invalid to merge a string with a map, I've tried a "options-pattern" approach to overriding mergo behaviour: you can provide any combination of the additional arguments `"no_override"` (to merge without override, i.e. priority to the left) and `"append_lists"` (to have list values append rather than replace; alias `"append"`). Position doesn't matter, and other strings will throw the error "unrecognised option".

**Comment by luis-guimaraes-exoawk** [comment] 2024-04-16 08:54
@isometry Yeah...
I have no issue with your implementation, seems like a sane one :smile: . I was just pushing to get a standard one so we can avoid similarly named providers/functions with different behaviours. If we can make your provider a "standard" one, it probably won't be an issue!

**Comment by apparentlymart** [comment] 2024-05-29 23:12
Hi all,

As discussed over in the earlier issue on this subject https://github.com/hashicorp/terraform/issues/24987#issuecomment-719089236, we chose to encourage implementing this in external providers rather than as a builtin because there seems to be no strong consensus for what exactly the "deep merge" operation implies, and so it seems that multiple implementations is both inevitable and desirable to meet the different use-cases that led to those differing definitions of the function in other languages.

I see that the `mergo` function in `isometry/deepmerge` is aiming to deal with multiple variations at once using special string arguments, which is an interesting approach! I've not tried that provider directly myself, but those who were interested in this issue might wish to study it to see if it meets their needs. If you have a need it doesn't meet then you still have the option of implementing your own provider with different behavior if you wish.

Since there is now at least one provider offering an answer to this, I'm going to close this issue. Thanks!

**Closed by apparentlymart** 2024-05-29 23:12 UTC
Labels: enhancement, functions, new
