### ISSUE TITLE
file(path) - flag for lazy evaluation of file's existence

### ISSUE THREAD

**Issue by stephanlindauer** [hashicorp/terraform#10878] opened 2016-12-21 13:14 UTC
### Affected Resource(s)
- file(path)

### Expected Behavior
I'd like to have a flag that I can set so Terraform doesn't abort `terraform apply` if the referenced file doesn't exist (yet), while they will be available at the point in time, when they are actually needed (because I run a local_exec before that). In my current setup ( https://github.com/stephanlindauer/terra-aws-core-kube ), I need to put dummy files to satisfy this requirement. It would be nice to have an optional parameter that enables lazy evaluation of whether that file exists at the point in time where it's actually needed.
`file(path,false)` or something like this.

### Actual Behavior
`terraform apply` fails

### Steps to Reproduce
reference a file that doesn't exist with `file(path)`, then `terraform apply`

**Comment by apparentlymart** [comment] 2016-12-21 15:45
Hi @stephanlindauer. Thanks for creating this feature request!

The idiom of using a `local-exec` to write a file to disk to later read with `file` is generally a workaround for some other missing functionality in Terraform, so I'd be interested to delve a little more into what you're trying to do here and whether there's a higher-level Terraform feature that would serve the need better.

Looking at your repo, one example I see is hitting the discovery endpoint on `etcd`. It would seem reasonable to me for Terraform to have a resource to interact with the etcd discovery service directly, removing the need for you to run `curl` and redirect to a file.

The other thing I see in your repo is a script that generates TLS certificates. We added [the TLS provider](https://www.terraform.io/docs/providers/tls/index.html) to Terraform to allow certificates to be generated inline without the need to shell out to other programs, though I do see that you have some extra steps to interact with `kubectl` to configure all of those certs; would this use-case be served by Terraform having its own Kubernetes provider, I wonder?

In 0.8 we added an "escape hatch" to allow running external programs to gather data without the need to temporarily stash the data into an on-disk file, in the form of [the `external` data source](https://www.terraform.io/docs/providers/external/data_source.html). Unfortunately it seems like a poor fit for both of your use-cases as-is because they are both stateful things: do some work once and retain the result for future runs. It was my intent to in future create an `external` *resource* too, which would then allow stateful things to be represented; I just wanted to see how/whether the data source would be used first before getting into that more complex scenario.

In general I'd prefer to see Terraform add features that allow us to avoid the need to write temporary files to disk rather than create features to make temporary files smoother to use. Perhaps the above features are not the right ones, but I think we can find a cleaner way to model your use-cases here than `local-exec`+`file(..)`.

**Comment by stephanlindauer** [comment] 2017-03-14 23:20
hi martin, thanks for your extensive feedback.

i think there are probably a lot of very similar use-cases that have nothing to do with certs or kubernetes. for me having more flexible options for `local-exec`+`file(..)` makes terraform more equipped for situations where it doesn't (yet or ever) supply an out-of-the-box feature for that exact use-case.
using build-in features is a good thing if it exactly fits the requirements, if not, its always nice to have a richer set of options to "freestyle".

so thanks for looking into use-case and potentially putting it into consideration for future features.

**Comment by munnerz** [comment] 2017-05-22 19:10
I'd like to add my support for this.

I have a template_dir resource, and then a `null_resource` with local_exec in, and a `count` of the number of items I want to do something with (each of which exist in template_dir). This means the null_resource runs once per item I care about within the templare_dir (some of those files may be ignored, depending on users tfvars).

I would like to only run the `null_resource` stage *if* the particular file within the `template_dir` has changed, however currently I rely upon `template_dir.name.id` to detect changes to files, which unfortunately also takes account of the file metadata as it takes the sha sum of a tar file of each directory contained within it (see: https://github.com/hashicorp/terraform/blob/master/builtin/providers/template/resource_template_dir.go#L179).

An alternative to this, given I know the name of the file in question that I want to check the hash of, is for me to prepend the `destination_dir` of the `template_dir` to the files name, and using the sha256 of this file as a trigger for my null_resource. This works great, except when the resource doesn't exist in the first place, as Terraform will fail.

If we were able to set a flag as this issue proposed, I'd be able to deal with this case easily.

Alternatively for my single use-case, I'm not 100% of how evaluation in Terraform works, but something like the following may work if there were to be a `file_exists` function:

```
triggers {
    something = "${file_exists("${template_dir.dir.destination_dir}/${element(var.active, count.index)}") ? file("${template_dir.dir.destination_dir}/${element(var.active, count.index)}") : "" }"
```

Although that does depend on Terraform not evaluating `file("${template_dir.dir.destination_dir}/${element(var.active, count.index)}")` if file_exists returns false.

**Comment by apparentlymart** [comment] 2017-05-22 21:40
In the mean time Terraform has got [the `local` provider](https://www.terraform.io/docs/providers/local/index.html) which currently has a resource for creating a file on local disk.

Creating a companion `local_file` data source would be the most robust way to solve this problem, I think. That way it can participate in the dependency graph so that it can be scheduled properly with respect to the resource that contains the provisioner that creates the file in question.

With the benefit of hindsight, the `file` interpolation function may have been a mistake since functions don't participate in the graph, but it at least remains a convenient way to get files that are statically available alongside the configuration, such as templates.

**Comment by so0k** [comment] 2017-08-31 12:33
@apparentlymart - we are seeing some very strange behaviour with the `local_file` resource and `template_file` data source.

We are trying to generate the same template `count` times and concatenate the rendered output into a `local_file` as follows:

```hcl
data "template_file" "namespaces" {
  count = "${length(var.namespaces)}"
  template = "${file("${path.module}/resources/namespace.tpl")}"
  vars {
    namespace = "${element(var.namespaces, count.index)}"
  }
}
resource "local_file" "bootstrap_namespaces" {
  content  = "${join("---\n", data.template_file.namespaces.*.rendered)}"
  filename = "${var.output_dir}/namespaces.yaml"
}
```

on the first `terraform apply`, the file would be created correctly - however, on the 2nd `terraform apply` - the file would be deleted. Every odd run the file would be created and every even run it would be deleted. Are there existing issues to track that observed this behaviour?

**Comment by so0k** [comment] 2017-08-31 12:51
oops, I wasn't able to reproduce the behaviour in a test project outside of our current project.. so maybe it's something else, I'll clarify when I found out the cause

**Comment by so0k** [comment] 2017-09-01 04:20
Sorry to hijacking this thread (although it's related to `lazy eval`). We were able to reproduce the behaviour I described above... the cause was interaction between `template_dir` and `local_file`

1. `template_dir` resource generated rendered templates in target directory, but one of the files needed to be the concatenated result of source templates based on a count, so we handled that file separately
1. `local_file` generated that additional file into the `template_dir` target directory

The result was that on the first run, `template_dir` generated the target directory and `local_file` added the additional file (there's a race condition here actually, but we can force the dependency)

on the second run, refresh tainted the `template_dir` resource, but the `local_file` was untainted, so it re-rendered the `template_dir` without the `local_file` in it - clearing the local file (forcing dependencies didn't prevent this, **how are resources tainted down the dependency chain?**)

on the third run, refresh tainted the `local_file`, but the `template_dir` was fine, so the `local_file` was created again - which would cause the next run to act like the second run described above.

rinse, repeat.

So, I'm not sure if a `lazy eval` flag would help with this scenario?

To fix it, we had to live with handling specially rendered files differently and separate the target directories. After some restructuring, that works for us (but may not work for everyone).

**Comment by apparentlymart** [comment] 2017-09-01 05:06
Hi @so0k,

What you described here sounds like a different problem. Sorry for the weirdness.

The `template_dir` data source is not strictly compliant with the expectations for a data source since, for pragmatic reasons, it creates persistent data on disk rather than just loading and returning data. Terraform is assuming it is a well-behaved data source while in practice it's a bit of a cheat.

The different approach you described of keeping the two resources separate is the approach I would recommend here. In an ideal world this data source would not create anything on disk at all, but that's not really possible within current constraints, so it's best to act _as if_ it is a pure data source, not expecting its result to persist between runs.

If you'd like to did into this some more I think it would be best to make a new issue in the template provider's repository so we can keep this issue focused.

**Comment by so0k** [comment] 2017-09-01 06:53
Thank you @apparentlymart - again, sorry for polluting this thread with a different problem, somehow my keywords for my issue turned up this thread, so hopefully others with the same issue who land here can resolve their issue through my explanation. Also note we found an alternative fix (which I edited in to the comment above). I will now stop posting in this thread :)

**Comment by piotr-napadlek** [comment] 2018-01-25 14:06
Hi, any progress on this one? In our project we rely on some jar existence and their checksums to push them to ecr (with the help of null_resource local_exec). 
Everything is ok when we build and deploy in a pipeline, but the problem starts when we want to clean and destroy the infrastructure. Terraform complains that the file does not exist. Somehow it feels strange that terraform tries to destroy a resource that never existed (null_resource). I would need to check if the file exists, something like mentioned above:
```
triggers {
    something = "${file_exists("${template_dir.dir.destination_dir}/${element(var.active, count.index)}") ? file("${template_dir.dir.destination_dir}/${element(var.active, count.index)}") : "" }"
}
```
Any ideas for a workaround?

**Comment by digitalkaoz** [comment] 2018-02-05 09:45
```hcl
triggers {
   something = "${! file_exists("foo.zip")}"
}
```

would be awesome!

**Comment by apparentlymart** [comment] 2018-02-06 16:35
Hi all,

Sorry I didn't spot this issue when we were releasing it, but [the `local_file` data source](https://www.terraform.io/docs/providers/local/d/file.html) I mentioned above has since been implemented, in `local` provider v1.1.0.

This data source gives a new way to read files that is a node in the dependency graph and thus it can have a dependency on some other resource that creates the file.

Unfortunately we're not totally out of the woods yet due to the need to implement something like the proposal in #17034 before this would be fully usable. In the mean time it's possible to use `depends_on` within the `data "local_file"` block but it will create a "perma-diff" for the reasons discussed in #17034:

```hcl
resource "null_resource" "example" {
  provisioner "local-exec" {
    command = "echo hello >${path.module}/hello.txt"
  }
}

data "local_file" "example" {
  filename = "${path.module}/hello.txt"
  depends_on = ["null_resource.example"]
}

output "example" {
  value = "${data.local_file.example.content}"
}
```

The above may work for you if you are willing to tolerate the "perma-diff" it will create for `data.local_file.example`. That's generally annoying in any sort of automated workflow though, and so we are planning to do something like #17034 once we get done with our current focus on improving the configuration language syntax and move on to addressing some issues with the CLI workflow.

**Comment by matti** [comment] 2018-04-16 12:00
@apparentlymart Doesn't that example explode if `"${path.module}/hello.txt"` is removed?

I managed finally to do this without external data source by first creating an empty file with `null_file` resource, then running the provisioner and then reading data with `local_file` datasource and storing the output in resource triggers (and then lifecycle ignoring them).  The "perma-diff" does happen on subsequent applies if the file is missing, but atleast now I get provisioner output as requested here https://github.com/hashicorp/terraform/issues/6830

**Comment by nhi-vanye** [comment] 2018-05-14 02:49
I have another specific use case regarding TLS.

Using TLS provider to create the certificates used to deploy a CoreOS environment with embedded consul & nomad.

After nomad is functional, it then registers some jobs with nomad.


This all worked - but then we wanted to run the consul and nomad clusters under TLS. 

The TLS certificates and created and deployed to the hosts as part of provisioning process, but the nomad provider needs a path to the CA file. At that point the nomad provider is failing because the ca file is not yet present.

```
Error: Error running plan: 1 error(s) occurred:

* provider.nomad: failed to configure Nomad API: tls: failed to find any PEM data in certificate input
```

I don't have a workaround yet (except disabling TLS)

**Comment by joestump** [comment] 2018-05-15 17:59
Running into this with provisioning Lambda ZIP files as well. I need to use `file()` with [`source_code_hash`](https://www.terraform.io/docs/providers/aws/r/lambda_function.html#source_code_hash) to trigger updates.

**Comment by af6140** [comment] 2018-06-06 14:00
This is a really desired feature. But step back and take a look, maybe we need null_resource to be able to run even in plan mode in some case to prepare all needed local files.

Or we need global before/after hooks that in both plan and apply mode.

**Comment by af6140** [comment] 2018-06-06 14:02
My use case is that I need to download a file from remote resources and provide the local file to aws lambda function resource. Ideally, in plan mode, the file can be downloaded ( and verified), since it's an external resource.

**Comment by cablespaghetti** [comment] 2018-10-15 12:12
Same use case as above. Currently I'm wrapping terraform in a shell script which downloads all the Lambda .jar files using Maven. I'd really like to run the maven command inside terraform but I haven't found a way that will work. :(

**Comment by msmans** [comment] 2018-12-19 08:01
Not sure if something similar is mentioned anywhere, but my workaround for now, is to make `file()` depend on the `null_resource` through interpolation. Everything works fine after this. Here's an example:

```tf
resource "null_resource" "ssh_key_pair" {
  provisioner "local-exec" {
    command = <<EOF
set -ex
ssh-keygen ... -f "${path.module}/id_rsa"
gcloud kms encrypt ... --ciphertext-file="${path.module}/id_rsa.enc"
rm -f "${path.module}/id_rsa"
EOF       
  }
}

resource "kubernetes_secret" "ssh_key" {
  data {
    id_rsa.enc = "${file(replace("${path.module}/id_rsa.enc*${null_resource.ssh_key_pair.id}", "/[*].*/", ""))}"
  }
}
```

**Comment by m4h3** [comment] 2019-01-04 11:04
Thank you @msmans . This is effectively working for me and it's quite readable in terms of TF workarounds !

**Comment by teamterraform** [comment] 2019-07-20 01:20
Hi all!

Terraform 0.12 now includes [`fileexists`](https://www.terraform.io/docs/configuration/functions/fileexists.html), as was discussed earlier in this issue.

As mentioned on the documentation page, this can now be used to conditionally access a file:

```hcl
fileexists("custom-section.sh") ? file("custom-section.sh") : local.default_content
```

Over the years this issue seems to have grown to include a number of other things, but it seems like the remaining gap is represented by #17034, so we're going to close this one out to consolidate. If you are working with files that are generated as a side-effect of `terraform apply` then the `local_file` data source is still best way to deal with that, since then Terraform use the normal dependency graph to discover when the file is safe to read. The lack of #17034 still makes it awkward to represent that dependency, but we'll track that over in that issue.

Thanks for the great discussion here, and sorry for the long delay since the last response to it.

**Closed by teamterraform** 2019-07-20 01:20 UTC
Labels: config, enhancement
