### ISSUE TITLE
Terraform Plan/Apply should not upgrade the terraform state snapshot

### ISSUE THREAD

**Issue by kennethtxytqw** [hashicorp/terraform#24271] opened 2020-03-04 07:42 UTC
### Terraform Version

```
0.12.7
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output
```
Error: state snapshot was created by Terraform v0.12.9, which is newer than current v0.12.7; upgrade to Terraform v0.12.9 or greater to work with this state
```

### Expected Behavior
`terraform plan` and `terraform apply` should not upgrade the state snapshot if it did not make any changes.

### Actual Behavior

Simply using `terraform plan` could upgrade the state snapshot.

### Steps to Reproduce

1. terraform0.12.7 init
1. terraform0.12.9 plan
1. terraform0.12.7 plan

**Comment by jbardin** [comment] 2020-03-04 15:57
Hi @kennethtxytqw,

Do you have an example of a situation where plan alone updated the state version? That is not indented, but I haven't seen a way to reproduce that yet. Taking a basic config and running the steps above should not produce an error.

The change via apply is expected, as there is no guarantee that apply won't alter the state. Even if there are no resource changes, there may be structural changes required, new output values, schema updates for providers, etc.

As for the details of handling state version, we started an issue to track the discussion in #23697.

**Comment by danieldreier** [comment] 2020-04-28 00:16
I'm going to close this issue because it's been waiting for a response since March 4th. If you're still having an issue where the plan alone updated state, please feel free to let us know. That would be a surprise to me and I'd consider it a bug. Please make sure to link this issue if you file a new one so that we have that context.

**Closed by danieldreier** 2020-04-28 00:16 UTC
Labels: cli, waiting-response
