### ISSUE TITLE
`terraform plan` crash

### ISSUE THREAD

**Issue by erikbryant** [hashicorp/terraform#25024] opened 2020-05-22 21:38 UTC
### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.63.0
+ provider.datadog v2.7.0
+ provider.okta v3.2.0
+ provider.pagerduty v1.7.1
+ provider.sumologic (unversioned)
+ provider.vault v2.11.0

Your version of Terraform is out of date! The latest version
is 0.12.25. You can update by downloading from https://www.terraform.io/downloads.html
```

### Crash Output

Terraform output https://gist.github.com/erikbryant/2abb57b8da91a544ed75f43138df8613

crash.log https://gist.github.com/erikbryant/cf3cea67bd624094f6c1083f1b577fb5

### Expected Behavior

This was an attempt to run `terraform plan`. It should have generated a plan.

### Actual Behavior

Terraform crashed.

### Steps to Reproduce
`terraform init`

`terraform plan`

I am unable to reproduce this issue.

I suspect that it had to do with me losing connection to my WiFi. While I was waiting for the plan to finish my computer went to sleep. I woke it up and terraform displayed:

```
There was an error connecting to the remote backend. Please do not exit
Terraform to prevent data loss! Trying to restore the connection...
```

Some fairly long amount of time passed (maybe a minute) and then the crash notification displayed.

**Comment by erikbryant** [comment] 2020-05-22 21:42
If the terraform configs would be useful I can attempt to package up the relevant ones. We have a pretty large corpus (we really like terraform).

**Comment by danieldreier** [comment] 2020-05-29 01:01
Hi! Thanks for reporting this. Based on your logs, you definitely had a real crash, and I'd like to fix it, but I don't know how to reproduce it, and without a reproduction case, there's no way to fix it, and so I'm a bit stuck on what to do next on this one.

It sounds to me like there's an edge case where if you lose network connectivity while writing to the remote backend, terraform crashes. I'm not sure whether we actually need your specific terraform configs, but we'd definitely need some kind of reproduction case.

Can you help clarify exactly what your backend config is? Is this against Terraform Enterprise or Terraform Cloud?

**Comment by erikbryant** [comment] 2020-06-01 03:22
@danieldreier Thanks for looking at this. I know the info is a little skimpy. If I can get some time this week I'll try to reproduce the crash.

We are using Terraform Enterprise.

**Comment by erikbryant** [comment] 2020-06-04 19:13
I have tried several more times (with the latest local client), but am not able to reproduce this.

I should add that our Terraform Enterprise installation is running Terraform version 0.12.24

**Comment by danieldreier** [comment] 2020-06-05 23:15
@erikbryant I really appreciate you trying to get the reproduction. Without a full, ready-to-use reproduction case, this is unlikely to get solved, because there's just no way for us to cause this same crash.

I'm going to close this for now because the information is insufficient to quickly reproduce the problem. I do believe you're probably having a legitimate issue and I would like to fix it, but I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

If you do later end up able to create a full reproduction case, I'm happy to re-open the issue and then try to reproduce it. Feel free to reach out at ddreier@hashicorp.com if you do! I'd love to fix this, just don't know how to right now.

**Closed by danieldreier** 2020-06-05 23:15 UTC
