### ISSUE TITLE
Add flag to disable "Noting changes made outside of Terraform" feature from Terraform 0.15.4

### ISSUE THREAD

**Issue by kemmemha** [hashicorp/terraform#28918] opened 2021-06-10 07:47 UTC
We upgraded from Terraform 0.15.3 to Terraform 1.0.0.

The "Noting changes made outside of Terraform"-feature that was introduced with Terraform 0.15.4 has the potential to increase logs tremendously.

In our case this is around 200% more logs in our CI pipeline than it was with Terraform 0.15.3. Due to the huge amount of logs the oversight with `terraform plan` is a lot harder to understand now. By design some changes are excluded by `lifecycle_ignore` because it is changed by an automation on our side. Sadly those changes are logged as well now.

**Comment by jbardin** [comment] 2021-06-10 12:44
Duplicate of #28803

**Closed by jbardin** 2021-06-10 12:44 UTC
Labels: enhancement, new
