### ISSUE TITLE
TF 15 creates a lot of changes hidden by sensitive value, compared to TF14

### ISSUE THREAD

**Issue by esn89** [hashicorp/terraform#28839] opened 2021-05-28 21:28 UTC
### Terraform Version

```
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.69.0
+ provider registry.terraform.io/hashicorp/google-beta v3.69.0
```

### Terraform Configuration Files
```
resource "google_service_account" "myapp" {
  account_id   = "myapp-prod1
  project      = data.terraform_remote_state.projects.outputs.project_id
  display_name = "service account for myapp"
}

resource "google_service_account_key" "myapp" {
  service_account_id = google_service_account.myapp.email
}

resource "kubernetes_secret" "my_service_account_key" {
  metadata {
    name      = "my-service-account-key"
    namespace = kubernetes_namespace.myspecialnamespace.metadata.0.name
  }

  data = {
    "key.json" = base64decode(google_service_account_key.myapp.private_key)
  }
}

data "vault_generic_secret" "application_cert" {
  path = "super/secret/path/in/vault/that/has/never/changed"
}

resource "kubernetes_secret" "application_cert" {
  metadata {
    name      = "application-server-cert"
    namespace = kubernetes_namespace.application.metadata.0.name
  }

  type = "tls"

  data = {
    "tls.crt" = data.vault_generic_secret.application_cert.data["cert"]
  }
}


```

Output:

```terraform
  # kubernetes_secret.my_service_account_key will be updated in-place
  ~ resource "kubernetes_secret" "my_service_account_key" {
      ~ data = (sensitive value)
        id   = "myproject/my-service-account-key"
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

  # kubernetes_secret.application_cert will be updated in-place
  ~ resource "kubernetes_secret" "application_cert" {
      ~ data = (sensitive value)
        id   = "application/application-server-cert"
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

```

### Debug Output
Debug returns cleanly

### Expected Behavior
I expect TF 15 to have the same output as TF 14 and show that nothing has changed.

This is the TF14 output:

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behavior
There are a total of 65 changes to the resources here, and Terraform 15 is reporting:

```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
```
and
```Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
```
When in fact nothing has changed.  A plan with TF 14 shows everything in sync.  What's more is that because it is covered up with `sensitive value`, I cannot see what exactly is being changed.

### Steps to Reproduce
Deploy with TF 14
Then plan with TF 15.

### Additional Context
I use Terragrunt, but that shouldn't be a cause.

**Comment by eric-kinsa** [comment] 2021-06-01 02:59
I'm also experiencing this same issue. On v0.14.11, I get "No changes". If I upgrade to v0.15.4, I get changes for several ECS and RDS resources that pull from a data source of a secret.

Resources:
```
data "aws_secretsmanager_secret" "app" {
  name = "${var.env}/${var.app}"
}

data "aws_secretsmanager_secret_version" "app" {
  secret_id = data.aws_secretsmanager_secret.app.id
}

resource "aws_rds_cluster" "app_db_cluster" {
  count                           = var.db_cluster
  cluster_identifier              = "${var.app}-${var.env}-cluster"
  storage_encrypted               = true
  engine                          = "aurora-mysql"
  engine_version                  = var.engine_version
  enabled_cloudwatch_logs_exports = ["audit", "error", "general", "slowquery"]
  copy_tags_to_snapshot           = true
  backup_retention_period         = var.backup_retention_period
  master_username                 = jsondecode(data.aws_secretsmanager_secret_version.app.secret_string)["DATABASE_USERNAME"]
  master_password                 = jsondecode(data.aws_secretsmanager_secret_version.app.secret_string)["DATABASE_PASSWORD"]
  skip_final_snapshot             = false
  deletion_protection             = true
  db_subnet_group_name            = var.env
  iam_roles                       = [data.aws_iam_role.rds.arn]
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.db_param.name
  apply_immediately               = true
  tags = {
    environment = var.env
    service     = var.app
    terraform   = "true"
  }
  vpc_security_group_ids = [
    data.aws_security_group.rds.id
  ]
}
```
Changes using v0.15.4:
```
# module.app-service.aws_rds_cluster.app_db_cluster[0] will be updated in-place
  ~ resource "aws_rds_cluster" "app_db_cluster" {
      + global_cluster_identifier           = ""
        id                                  = "app-sandbox-cluster"
      # Warning: this attribute value will be marked as sensitive and will not
      # display in UI output after applying this change. The value is unchanged.
       ~ master_username                     = (sensitive value)
      ~ master_password                     = (sensitive value)
      + replication_source_identifier       = ""
        tags                                = {
            "environment" = "sandbox"
            "service"     = "app"
            "terraform"   = "true"
        }
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

**Comment by alisdair** [comment] 2021-06-01 13:01
I think this issue is a duplicate of #28593, where Terraform needs to update the state due to the new way sensitive attribute values are marked as sensitive. You can verify this by completing the `terraform apply` with Terraform 0.15, after which I believe you should not see this diff in sensitive values.

I'm closing this as a duplicate. If this doesn't seem to be the case, please let me know what behaviour you see after completing an `apply`.

**Closed by alisdair** 2021-06-01 13:01 UTC
Labels: bug, new

**Comment by esn89** [comment] 2021-06-01 19:08
@alisdair 

Thanks.  I suppose in the future, those changes to be marked as sensitive can have warnings similar to:
```
      # Warning: this attribute value will be marked as sensitive and will not
      # display in UI output after applying this change. The value is unchanged.
      ~ name     = (sensitive)
      # Warning: this attribute value will be marked as sensitive and will not
      # display in UI output after applying this change. The value is unchanged.
      ~ password = (sensitive value)
```

I see this message show up for some changes, but not for some.

**Comment by alisdair** [comment] 2021-06-01 19:24
Hmm. Anything which has no underlying changes should already show that message. If you don't see it for an attribute value which displays as `sensitive`, it should have changed (although perhaps in a way which is unimportant). For the configuration you reported, this may be caused by a refresh on the `google_service_account` or `vault_generic_secret` resources.

I tried to find a way to reproduce the behaviour you describe with these resources but was unsuccessful. If you are able to find a small but complete reproduction case of this behaviour, while the underlying sensitive value is _not_ changing, that would be very helpful and I'd be happy to investigate the bug.
