### ISSUE TITLE
TF_X_CONCISE_DIFF should always be optional

### ISSUE THREAD

**Issue by jacobkretz** [hashicorp/terraform#27996] opened 2021-03-05 15:58 UTC
### Current Terraform Version

```
0.14.7
```

### Use-cases

Running Terraform in automation/build server should not default to or should always have the ability to show ALL diffs including unchanged ones when running plan or apply.
### Attempted Solutions

Currently turning TF_X_CONCISE_DIFF to 0 on the build server.
### Proposal

Ensure that verbose logging functionality for plan and apply, especially on a build server helps ensure plan review is well understood.  This can be accomplished by simply keeping both the concise and verbose diff outputs and toggling a new environment variable(or keeping TF_CONCISE_DIFF) or integrating with TF_IN_AUTOMATION.

**Comment by jchristner-trustwave** [comment] 2021-05-28 20:02
I agree.   In our situation, a concise diff is problematic when updating an aws_ecs_task_definition json blob for the container_definitions variable, and that blob contains multiple containers (sidecars).   It's not possible to tell which sidecar/container definition a change is in without the full context of the full json blob.     While the non-concise diff may be huge, it's still needed to validate the correct changes are being applied.   The option to control that should remain.

**Comment by jbardin** [comment] 2021-10-21 12:29
@imaginarynik, There was nothing dropped per se, the new diff renderer completed testing and became the default. The `TF_X_` prefix only applies to active experimental features, and is never intended to be used outside of testing them out. While we don't detect and error on unused environment variables, [experimental language features](https://www.terraform.io/docs/language/settings/index.html#experimental-language-features) are only to be used for testing and are not valid in configuration once the experiment has concluded.

**Comment by jacobkretz** [comment] 2021-10-21 14:45
So has the toggling of CONCISE_DIFF been removed? Or is there another way to disable it?

**Comment by jbardin** [comment] 2021-10-21 14:54
There is currently only one diff renderer, so there is nothing to disable here. Since issue amounts to a request for a more verbose output, we can close this for now as a duplicate of #27547.

Thanks!

**Closed by jbardin** 2021-10-21 14:54 UTC
Labels: enhancement, new
