### ISSUE TITLE
Enhancement: allow variables to be used in import block

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform#33383] opened 2023-06-16 09:58 UTC
### Terraform Version

```shell
1.5.0
```

### Use Cases

To be able to conditionally import a resource or another depending on the selected workspace.

### Attempted Solutions

```terraform
import {
  id = "${terraform.workspace == "dev" ? "mydevbucket" : "mystagebucket"}"
  to = aws_s3_bucket.bucket
}
```

```bash
$ terraform plan -generate-config-out=generated_resources.tf
```

> │ Error: Variables not allowed
│
│   on main.tf line 2, in import:
│    2:   id = "${terraform.workspace == "dev" ? "mydevbucket" : "mystagebucket"}"
│
│ Variables may not be used here.

### Proposal

I think there should be a way to programmatically import a resource based on the selected workspace. Either this or https://github.com/hashicorp/terraform/issues/33380 should be implemented

**Comment by jbardin** [comment] 2023-06-16 13:20
Duplicate of #33228

**Closed by jbardin** 2023-06-16 13:20 UTC
Labels: enhancement, new
