### ISSUE TITLE
Many string enums in AzureRM provider think the property has changed if the casing is different than expected

### ISSUE THREAD

**Issue by StephenWeatherford** [hashicorp/terraform#14188] opened 2017-05-03 19:26 UTC
### Terraform Version
0.9.4

### Affected Resource(s)
Multiple

### Expected Behavior
Either the properties should accept only a single case, or else the behavior should be idempotent no matter which casing the template uses.  
Example: azurerm_virtual_machine_scale_set.agentpool.sku.tier accepts either "standard" or "Standard", and it shouldn't matter which is actually used.

### Actual Behavior
Example: azurerm_virtual_machine_scale_set.agentpool.sku.tier accepts either "standard" or "Standard", but if "standard" is used, the next tf plan will think a change occurred when none has.

### Steps to Reproduce
See #11626 for an example.

We need to go through all the enum-style string properties and verify casing is handled correctly.

**Comment by StephenWeatherford** [comment] 2017-05-03 19:28
@abhijeetgaiha is planning on working on this.

**Comment by abhijeetgaiha** [comment] 2017-05-04 09:44
Which is the more appropriate approach, restricting the input or making the behavior idempotent?

**Comment by tombuildsstuff** [comment] 2017-05-04 14:01
@StephenWeatherford @abhijeetgaiha thanks for raising this!

The convention is to make this case-insensitive - the Resource Schema exposes a `DiffSuppressFunc` property which allows us to handle this by assigning a Diff function. [Here's an example](https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_loadbalancer_rule.go#L75) of how we're using an `ignoreCaseDiffSuppressFunc` to do this in the Load Balancer Rule resource :)

Hope that helps :)

**Comment by StephenWeatherford** [comment] 2017-05-04 19:42
@tombuildsstuff Thanks!  Is there a reason to also use a state func (ignoreCaseStateFunc), or does that not matter, as long as we have the ignore-case-diff function?

**Comment by tombuildsstuff** [comment] 2017-05-04 21:48
@StephenWeatherford it's optional - so I believe you should be able to get away without it :)
(it's used should you wish to modify the data stored in the `*.tfstate` file, for example base64 encoding a large string to compress space in the state etc)

**Comment by abhijeetgaiha** [comment] 2017-05-11 12:25
@tombuildsstuff Can we have DiffSuppressFunc on individual fields on map and set types? It doesn't seem to be the case.

**Comment by tombuildsstuff** [comment] 2017-05-12 08:37
@abhijeetgaiha I believe so, however a Set has a Hash associated with it, which will need to be updated to take that into account, potentially through a state migration. Here's an example in a [list](https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_loadbalancer.go#L75), [set](https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_network_interface_card.go#L86) and whilst I can't find an example with a Map within the AzureRM Provider, it should work AFAIK.

Have you got a example of where you're seeing issues?

**Comment by abhijeetgaiha** [comment] 2017-05-12 09:18
@tombuildsstuff While trying out a fix for #11626, I added the function for the sku [property](https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_virtual_machine_scale_set.go#L52), but it had no effect on the diff. The hash value might be the cause of that, as you suggest.

**Comment by abhijeetgaiha** [comment] 2017-05-12 10:21
@tombuildsstuff I think the hash was the issue. After making some changes there, the diff is working correctly. Thanks! 👍

**Comment by stack72** [comment] 2017-06-01 16:49
Closed via #14861

**Closed by stack72** 2017-06-01 16:49 UTC
Labels: bug, provider/azurerm
