### ISSUE TITLE
Cycle error when referencing same block, but not same instance

### ISSUE THREAD

**Issue by fsoikin** [hashicorp/terraform#26697] opened 2020-10-24 02:58 UTC
### Terraform Version
```
Terraform v0.13.5                                     
+ provider registry.terraform.io/hashicorp/aws v3.12.0
```

### Terraform Configuration Files
```terraform
locals {
  resources_map = {
    "foo" = { parent_name = "", path_part = "foo" }
    "foo/bar" = { parent_name = "foo", path_part = "bar" }
    "foo/bar/baz" = { parent_name = "foo/bar", path_part = "baz" }
  }
}

resource "aws_api_gateway_rest_api" "api" {
  name = "Test"
}

resource "aws_api_gateway_resource" "res" {
  for_each = local.resources_map
  rest_api_id = aws_api_gateway_rest_api.api.id
  parent_id = (
    each.value.parent_name == "" ?
      aws_api_gateway_rest_api.api.root_resource_id :
      aws_api_gateway_resource.res[each.value.parent_name].id
  )
  path_part = each.value.path_part
}
```

### Debug Output
[tf.txt](https://github.com/hashicorp/terraform/files/5432325/tf.txt)

### Crash Output
None

### Expected Behavior
Three AWS API Gateway resouces are planned for creation

### Actual Behavior
```
Error: Cycle: aws_api_gateway_resource.res["foo/bar/baz"], aws_api_gateway_resource.res["foo/bar"], aws_api_gateway_resource.res["foo"]
```

Even though each resource instance only references _another_ instance, never itself, Terraform apparently applies the concept of loop to blocks, not to instances. But at the same time, the error message does talk about a cycle in instances, not blocks.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Workaround
I was able to make this work by giving each nesting level its own resource block, i.e.:

```
resource "aws_api_gateway_resource" "res1" {
  for_each = {for k, v in local.resources_map: k => v if length(split("/", k)) == 1}
  rest_api_id = aws_api_gateway_rest_api.api.id
  parent_id = aws_api_gateway_rest_api.api.root_resource_id
  path_part = each.value.path_part
}
resource "aws_api_gateway_resource" "res2" {
  for_each = {for k, v in local.resources_map: k => v if length(split("/", k)) == 2}
  rest_api_id = aws_api_gateway_rest_api.api.id
  parent_id = aws_api_gateway_resource.res1[each.value.parent_name].id
  path_part = each.value.path_part
}
resource "aws_api_gateway_resource" "res3" {
  for_each = {for k, v in local.resources_map: k => v if length(split("/", k)) == 3}
  rest_api_id = aws_api_gateway_rest_api.api.id
  parent_id = aws_api_gateway_resource.res2[each.value.parent_name].id
  path_part = each.value.path_part
}
```

This works as intended (as long as there are at least as many levels as the longest path in `resources_map`), but unfortunately I then have to attach four other objects to each resource (i.e. `aws_api_gateway_method`, `aws_api_gateway_method_response`, `aws_api_gateway_integration`, and `aws_api_gateway_integration_response`), for thus is structured API of the the almighty AWS, and it gets _really_ long and typo-prone.

**Comment by jbardin** [comment] 2020-10-26 14:45
Hi @fsoikin 

Sorry about the confusion here, but this is the expected outcome. There is processing that must be done for resources as a whole, i.e. the single block declared in the configuration, and hence referenced within that block will create a dependency cycle. 

This are not immediately apparent to users in come cases however, and the error output is often not very helpful, because it can only reference the internal structures terraform uses for performing actions based on the configuration. 

I'm going to start grouping these issues together so we can try and improve the user experience for resolving the cycle in general. Marking as a duplicate of #26150 

Thanks!

**Closed by jbardin** 2020-10-26 14:45 UTC
Labels: bug, new

**Comment by fsoikin** [comment] 2020-10-26 14:48
Wait @jbardin, but then, is there no way to automate creation of these hierarchical structures, like API Gateway resources? Is there some other way I can do the same thing?

**Comment by jbardin** [comment] 2020-10-26 15:16
@fsoikin, The only solution we have for this type of nested resource would be to generate the configuration itself with the desired hierarchy of resources, see also #23735. In some cases the provider may chose to create an additional single resource type that can encapsulate multiple conceptual instances in a single resource block and link them together as needed, but can be difficult to manage, especially with the legacy SDK.

**Comment by fsoikin** [comment] 2020-10-26 18:01
I see. Thank you for the clarification. 
Separate script for generating the Terraform code is what I'm currently doing. Good to know this is the official recommendation.
