### ISSUE TITLE
Ability to import the whole Route53 zone with all records

### ISSUE THREAD

**Issue by MaximF** [hashicorp/terraform#20161] opened 2019-01-30 22:49 UTC
I wanted to be able to import the whole Route53 zone with all the records and its health checks etc.
While digging through the documentation I got an impression that I could import records individually, one after another, and I have to explicitly specify them in my empty TF configuration.

So far, a request like `terraform import aws_route53_zone.<MY_ZONE> <ZONEID>`  returns basic information about zone itself:

```
"aws_route53_zone.<MY_ZONE>": {
    "type": "aws_route53_zone",
    "depends_on": [],
    "primary": {
        "id": "<ZONEID>",
        "attributes": {
            "comment": "",
            "delegation_set_id": "",
            "id": "<ZONEID>",
            "name": "<ZONENAME>.",
            "name_servers.#": "4",
            "name_servers.0": "ns-0001.awsdns-04.org",
            "name_servers.1": "ns-0002.awsdns-63.co.uk",
            "name_servers.2": "ns-0003.awsdns-62.com",
            "name_servers.3": "ns-0004.awsdns-06.net",
            "tags.%": "0",
            "vpc.#": "0",
            "vpc_id": "",
            "vpc_region": "",
            "zone_id": "<ZONEID>"
        },
        "meta": {},
        "tainted": false
    },
```

With AWS CLI it coudl be done as easy as this:
```
aws route53 list-resource-record-sets --hosted-zone-id <ZONEID`
```

It would be nice to have functionality like that in Terraform as well.

I'm also wondering what is a current workaround for that case, and how can one import DNS records all at once.

Thanks!

**Comment by apparentlymart** [comment] 2019-01-30 23:53
Hi @MaximF,

At present the `terraform import` command supports only one resource at a time, but is intended to be callable by wrapper scripts that can consult local manifest files or call APIs to batch-import things.

In this case, you could write a small script to take the output of the AWS CLI command you indicated and call `terraform import ...` in a loop, generating the resource names in a way that makes sense for your environment. That is, choosing a mapping from the DNS-oriented record names to Terraform's resource names (the second quoted argument in the `resource` block header), where only identifiers are allowed.

**Comment by MaximF** [comment] 2019-02-02 20:11
Thank you @apparentlymart 
I'll work around the wrapping script solution for now.
Do you have any plans on implementing this feature down the road?

**Comment by MaximF** [comment] 2019-02-03 17:06
It looks like the Health Checks migration is quite a tricky part.
Those have the unique IDs in each account and migrating them as is doesn't work. 

It requires to run multi steps to do it properly:

1. Make Health Checks and DNS records dumps with AWS CLI
2. Parse Healt Check JSON output and generate new TF config
3. Apply TF to the new account to create Health Checks only
4. Write a script that could correlate IDs between imported and newly created Health Checks
5. Convert DNS dump into Terraform config and properly update Health Check references 
6. Apply TF config for DNS records.


That sounds like quite tricky path. I'm wondering if there are ways to cut the cornerson this migration process?

**Comment by apparentlymart** [comment] 2019-02-04 05:04
Given that DNS records are not a stateful object, could you perhaps instead use the data export to generate a Terraform configuration (using normal string templating in a language of your choice), create an entirely new copy of your DNS zone, and then configure the new nameservers with your registrar?

Import can be important for stateful object, like long-running "pet" servers or container objects like EC2 VPCs, but for simple objects it is often simpler to just recreate them gradually in Terraform, deleting the old infrastructure once it has been successfully replaced.

**Comment by biggiemac** [comment] 2019-04-23 22:12
Question, in the import example above, is <MY_ZONE> a string of the zone name that's visible in the Route53 Domain Name field? I can't seem to get import to work correctly.

**Comment by MaximF** [comment] 2019-04-25 02:33
@biggiemac, that is just the name used to identify the terraform `aws_route53_zone` resource call

**Comment by biggiemac** [comment] 2019-04-25 02:49
@MaximF The current error I get back from the import states "Error: resource address "aws_route53_zone.my_zone_name" does not exist in the configuration." I assume I can just add this in configuration, then re-run the import?

**Comment by MaximF** [comment] 2019-04-25 02:53
Yes, you have to create an empty resource with that name first.
Here is a page explaining necessary preparation steps for resource importing: https://www.terraform.io/docs/import/usage.html

**Comment by pselle** [comment] 2021-01-13 20:08
Closing this as a duplicate of https://github.com/hashicorp/terraform/issues/22219 and likely other similar bulk import issues.

**Closed by pselle** 2021-01-13 20:08 UTC
Labels: enhancement
