### ISSUE TITLE
terraform plan fails on an index() call after updating for_each argument

### ISSUE THREAD

**Issue by lag13** [hashicorp/terraform#26513] opened 2020-10-08 08:52 UTC
Apologies in advance if this is not actually a bug but the behavior felt odd to me so I figured it wouldn't hurt to make the issue.

### Terraform Version
```
$ terraform version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.2.0
```

### Terraform Configuration Files
These files can be obtained by cloning this repo: https://github.com/lag13/terraform-bug

Running the `./run.sh` script will let you reproduce the issue. The base terraform file looks like this:

```terraform
provider "aws" {
  region  = "us-east-1"
  version = "~>3.2.0"
}

variable "domain_name" {
  default = "a.com"
}

variable "subject_alternative_names" {
  default = []
}

resource "aws_acm_certificate" "cert" {
  domain_name               = var.domain_name
  subject_alternative_names = var.subject_alternative_names
  validation_method         = "DNS"
}

locals {
  dvo_domain_names = [for dvo in aws_acm_certificate.cert.domain_validation_options: dvo.domain_name]
}

resource "aws_security_group" "sg" {
  for_each = toset(var.subject_alternative_names)
  # Adding this contains protection seems to help get through the plan
  # and onto the apply which then works as expected.
  # name = contains(local.dvo_domain_names, each.key) ? "testing-${each.key}-${index(local.dvo_domain_names, each.key)}" : "THIS_VALUE_WONT_GET_USED"
  name = "testing-${each.key}-${index(local.dvo_domain_names, each.key)}"
}
```

### Debug Output
Here's a gist for the `terraform apply` that fails: https://gist.github.com/lag13/f622afd3e65dbf6e9eef3f84b138a9f1

### Expected Behavior
The 3rd (and last) `terraform apply` from the `run.sh` script is how I would expect terraform to work. The plan looked like this:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_acm_certificate.cert must be replaced
-/+ resource "aws_acm_certificate" "cert" {
      ~ arn                       = "arn:aws:acm:us-east-1:OMIT:certificate/36482091-160a-4173-a7dd-2bdefd71fb3f" -> (known after apply)
        domain_name               = "a.com"
      ~ domain_validation_options = [
          - {
              - domain_name           = "a.com"
              - resource_record_name  = "_26e6648b0a76113f94b31d20b85ef00b.a.com."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_032b4176b70bd1f72215cee4d31b9164.bsgbmzkfwj.acm-validations.aws."
            },
            {
                domain_name           = "a.com"
                resource_record_name  = (known after apply)
                resource_record_type  = (known after apply)
                resource_record_value = (known after apply)
            },
            {
                domain_name           = "b.com"
                resource_record_name  = (known after apply)
                resource_record_type  = (known after apply)
                resource_record_value = (known after apply)
            },
        ]
      ~ id                        = "arn:aws:acm:us-east-1:OMIT:certificate/36482091-160a-4173-a7dd-2bdefd71fb3f" -> (known after apply)
      ~ status                    = "PENDING_VALIDATION" -> (known after apply)
      ~ subject_alternative_names = [ # forces replacement
          + "b.com",
        ]
      - tags                      = {} -> null
      ~ validation_emails         = [] -> (known after apply)
        validation_method         = "DNS"

      - options {
          - certificate_transparency_logging_preference = "ENABLED" -> null
        }
    }

  # aws_security_group.sg["b.com"] will be created
  + resource "aws_security_group" "sg" {
      + arn                    = (known after apply)
      + description            = "Managed by Terraform"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "testing-b.com-1"
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + vpc_id                 = (known after apply)
    }

Plan: 2 to add, 0 to change, 1 to destroy.
```

### Actual Behavior
```
Error: Error in function call

  on main.tf line 29, in resource "aws_security_group" "sg":
  29:   name = "testing-${each.key}-${index(local.dvo_domain_names, each.key)}"
    |----------------
    | each.key is "b.com"
    | local.dvo_domain_names is tuple with 1 element

Call to function "index" failed: item not found.
```

### Steps to Reproduce
Run `./run.sh` from https://github.com/lag13/terraform-bug

**Comment by jbardin** [comment] 2020-10-08 19:31
Hi @lag13,

Thanks for reporting this. This is a longstanding problem with the refresh phase of Terraform, caused by certain types of changes that are not reconcilable when the state and configuration don't agree. 

Terraform 0.14 removes the refresh phase entirely, reading the resources on demand and eliminating this class of error entirely. If you want to test this out, you can build from master or try one of the alpha release on https://releases.hashicorp.com/terraform/.

Thanks!

**Comment by lag13** [comment] 2020-10-08 20:03
oh cool! Glad y'all know about it. I was going little crazy there wondering if this was an actual issue or not.

Feel free to close this out then! I eagerly await the the release of Terraform 0.14.

Thanks for all the work you do.

**Comment by jbardin** [comment] 2020-10-08 21:42
Thanks @lag13! I'll close this out for now, but if you find this is still an issue later on, please feel free to reply and re-open.

Thanks!

**Closed by jbardin** 2020-10-08 21:42 UTC
Labels: bug, confirmed, v0.13, waiting-response
