### ISSUE TITLE
Allow variables to be arrays

### ISSUE THREAD

**Issue by piavlo** [hashicorp/terraform#1168] opened 2015-03-10 12:15 UTC
currently variables are required to be strings
I want to use variable as list for example

`blocks = [ "1.1.1.1/24", "2.2.2.2/24" ]`
and the just use it as 
`cidr_blocks = ${var.blocks}`

currently i have to do
`block_a = "1.1.1.1/24"`
`block_b = "2.2.2.2/24"`
and
`cidr_blocks = [ "${var.block_a}", "${var.block_b}" ]`

not to mention that each time i add/remove block, it's PITA to go and update all security groups

**Comment by willmcg** [comment] 2015-03-10 17:30
+1  This would make the configurations cleaner more maintainable and this is exactly my use case as well.

**Comment by radeksimko** [comment] 2015-03-10 23:11
Known issue: https://github.com/hashicorp/terraform/issues/57

I suggest closing this as a duplicate and keep commenting the first issue.

**Comment by phinze** [comment] 2015-03-11 20:40
Thanks for the report - you can read more of the workaround mentioned over in #57 using `split/join`, but we're definitely going to keep working on it.

Closing as duplicate of #57 to consolidate the conversation. :+1:

**Closed by phinze** 2015-03-11 20:40 UTC
