### ISSUE TITLE
"Error: unable to verify checksum" across the board with plans

### ISSUE THREAD

**Issue by matthewcummings** [hashicorp/terraform#27870] opened 2021-02-22 17:38 UTC
Just started seeing this across the board with all plans/applies. I'm guessing that this is related to other outage type issues that people have reported.

```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...

Error verifying checksum for provider "datadog"
The checksum for provider distribution from the Terraform Registry
did not match the source. This may mean that the distributed files
were changed after this version was released to the Registry.


Error verifying checksum for provider "aws"
The checksum for provider distribution from the Terraform Registry
did not match the source. This may mean that the distributed files
were changed after this version was released to the Registry.


Error verifying checksum for provider "null"
The checksum for provider distribution from the Terraform Registry
did not match the source. This may mean that the distributed files
were changed after this version was released to the Registry.


Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to DataDog/datadog. Please update your source in required_providers.



Error: unable to verify checksum



Error: unable to verify checksum



Error: unable to verify checksum
````

**Comment by aaronmell** [comment] 2021-02-22 17:47
Having the same issue

**Comment by aaronmell** [comment] 2021-02-22 17:51
FYI, status.hashicorp.com is reporting a cloud outage. This may be related.

**Comment by vvscher** [comment] 2021-02-22 17:52
Same for me - everything got red.
Any advice would be great

**Comment by danieldreier** [comment] 2021-02-22 17:54
Hi! There is an ongoing outage impacting releases.hashicorp.com and registry downloads. I suspect that it is the root cause of what you're seeing - it's the same 403 error other folks have reported. Engineers have a good understanding of what happened and are working on a fix. The best option for you is probably to wait for engineers on our side to fix this.

**Comment by danieldreier** [comment] 2021-02-22 18:07
Hi! I really appreciate everyone reporting this. The root cause here is an incident in the releases.hashicorp.com and registry infrastructure. I'm going to close this and related issues and consolidate any ongoing discussion into https://github.com/hashicorp/terraform/issues/27872. Please do let us know in that issue if you are still having trouble downloading Terraform or providers.

**Closed by danieldreier** 2021-02-22 18:07 UTC
Labels: bug, new

**Comment by matthewcummings** [comment] 2021-02-22 19:28
@danieldreier thank you for the quick follow up. I hope you're all doing well today.
