### ISSUE TITLE
command/meta: SIGSEGV error when trying to split remote state using terraform state mv

### ISSUE THREAD

**Issue by adamar** [hashicorp/terraform#15483] opened 2017-07-06 06:26 UTC
Hi,

I have a large terraform state file that I want to break into smaller pieces. Ive created a subdirectory and moved a module resource declaration into it. Ive also init'd a new terraform env in this sub directory as well as doing a terraform state push to create the backend in `s3`/`dynamodb`.

but.... When I attempt to do a state mv from the large environment in the base directory to the new environment in the sub-directory I get a `SIGSEV`.

### Terraform Version
```
$> terraform -v
Terraform v0.9.8
```

### Steps to Reproduce
1. Create a new environment configuration
```
$> mkdir new-env && cd  new-env
$> terraform init \
    -backend-config="bucket= terraform-state" \
    -backend-config="key=new-env/terraform.tfstate" \
    -backend-config="region=us-east-1"
$> terraform state push
```

2. Move state from existing backend to newly created backend state in `new-env`
```
$> terraform state mv -state=.terraform/terraform.tfstate \
    -state-out=new-env/.terraform/terraform.tfstate \
    module.app module.app
```

### Notes
 - The [docs](https://www.terraform.io/docs/commands/state/mv.html) mention that the state option is ignored when used with remote state
> -state=path - Path to the state file. Defaults to "terraform.tfstate". *Ignored when remote state is used.*
> -state-out=path - Path to the state file to write to. If this isn't specified the state specified by -state will be used. This can be a new or existing path. *Ignored when remote state is used.*

But how else can we reference the source and destination state we want to move to and from?

 - Issue 13506 appears related but they are able proceed once the state is initialized.

### Terraform Config + Error Output

Example of SIGSEV output:
https://gist.github.com/adamar/fe09ee8b990b6c1a45b020f6fc8c12d3

Example of TF code used to generate this issue:
https://gist.github.com/adamar/c5b5f5d13a0553fe53014d4f07469cf8

### Possibly Related Issues
[13506](https://github.com/hashicorp/terraform/issues/13506)

**Comment by radeksimko** [comment] 2017-08-04 14:46
I'm tempted to close this as a duplicate of #13506 - do you agree @apparentlymart ?

**Comment by apparentlymart** [comment] 2017-08-07 22:58
Hi @adamar! Sorry for this crash, and thanks for reporting it.

This does look similar to #13506. That other issue was resolved by initializing the backend, but I suspect this one traces back to the same root cause since the `-state` option effectively overrides the current backend config and so is probably entering the same strange codepath.

Given that it seems like the same root cause I think we should consolidate discussion into #13506 for now, and so I'm going to close this. I believe @jbardin was looking into this or some similar problem (with weird behavior of the `terraform state` commands when not working directly with remote state) and so he may have a temporary workaround to suggest. (Which I guess we should share in the other issue, since I'm about to close this one!)

**Closed by apparentlymart** 2017-08-07 22:58 UTC
Labels: bug, cli, crash, waiting-response
