### ISSUE TITLE
Terraform allows aws resource use without defining `provier "aws"`

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform#6183] opened 2016-04-14 21:56 UTC
Hi there,

Came across this actually a couple of times. In some regards, it is nice that using AWS resources clues terraform in to "hey, we're using the terraform provider!" however if you use environment variables, and write  a plan to override those variables and omit the provider, you are in a lost world of hurt.

Ideally it would be nice if Terraform notices that you've defined aws resources, that it depends on or requires you to declare the provider "aws" explicitly.

### Terraform Version
v0.6.14

### Affected Resource(s)
- aws_*
- aws provider

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_security_group" "agroup" {
  name = "Name of a group"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Terraform should have error messaged that `provider "aws"` was not defined

### Actual Behavior
Assumes `provider "aws"` and will use environment variables without notification, or prompt for minimum requirements to the provider

### Steps to Reproduce
Please list the steps requires to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by catsby** [comment] 2016-04-18 20:48
Hello @mengesb –

Thanks for taking the time to open an issue here! Let’s see if I can help
explain some things, and I do have a question for you. But first..

The ability to omit the provider block is intentional. When Terraform runs, the
needed Providers are determined based on the configuration, and are loaded and
configured.

In the case of AWS, most fields are optional in order to allow various and
flexible usage, one of which being Environment Variables as you pointed out. By
being able derive the correct credentials, by environment variables or perhaps
the default AWS Credentials File location, helps make complicated
infrastructures span several different files. As the provider block can only be
defined *once*, you’re able to split your infrastructure in a logical
separation of resources/files and know they’ll all pick up the same
credentials. This is even more necessary when modules come into play, and you
may not have direct access the definitions of those resources.

I’d like to better understand your ask here, specifically regarding this:

> if you use environment variables, and write a plan to override those variables
and omit the provider, you are in a lost world of hurt.

I’m not quite sure I follow your example here, can you elaborate so I can
better understand? Do you have infrastructure that is configured, but some
manipulation of environment variables is happing in the plan phase that is
causing Terraform to lose track of that infrastructure?

Let us know more and we’ll take another look here, and thanks again for writing
in!

**Comment by mengesb** [comment] 2016-04-18 21:11
So the situation I had with this was that a module of my plan didn't define the provider. The other modules, however, did. The plan was setup such that you can pass items to the provider and potentially deploy different modules to different aws regions, however because this particular module didn't define the provider, it used the 'aws' provider with my shell environment variables, not even a previous invocation of the other module's provider values. I'm sure this is by design, but that omission on my part led to lost moments and big confusion.

```hcl
variable "region" = "us-east-1"
module "one" { #defined provider "aws"
region = "${var.region}"
...
}
module "two" { #didn't define provider "aws"
region = "${var.region}"
...
} 
```

In the above, say my `AWS_DEFAULT_REGION` is `us-west-1`, then I'd have module one complete, however module two would complete or error because of a provider omission if there were region-specific inputs. In my case, I had VPC stuff to provide, so the provided VPC resulted in an HTTP400, but I was under the mistaken belief that the provider was there so I was highly confused as to why module one would complete without issue, but module two failed but used the same data that my module one succeeded with.

My fix was simple indeed, specify the provider in the module where it was missing, and life was good, but unfortunately the real message 'missing provider' was hidden and only visible by running that module independently (since in my case it was a full plan, I downloaded and attempted to run it - finally seeing that the provider wasn't there). I think at this point I got an error that the provider wasn't there, but I'm not entirely sure I recollect at this point.

See where one can get lost? a previous declaration in a module of the plan invoked the provider, but in the absence of providing the values in a different module, it adopted for my shell environment variables. I do know this was a syntactical mistake on my part, however it seems precarious to make the assumption versus require explicit declaration.

To be honest, I'm not sure what the fix really would be. There's a fine line between helping the user and filling in the gaps on their behalf, and then there's filling in their gaps which allows them to drive right off the incomplete bridge into an abyss of confusion leaving them wonder how they got there.

**Comment by mitchellh** [comment] 2016-08-26 00:40
I'm with you here that I don't know what the right answer is, but not requiring `provider` declarations is an intentional feature that we don't want to roll back. Even if we required a `provider` block, the same behavior would've happened: it would've stated it is using AWS and would've automatically used your env vars.

I think the right answer here is probably just some better UX around first-run and notifying the user what providers will be used. Regardless, given the lack of other issues on this topic and the fact that this is working as intended, I'm going to close this.

I understand how in your scenario it wasn't clear and how we could probably do better, but it is fairly low priority for us. Sorry!

**Closed by mitchellh** 2016-08-26 00:40 UTC
Labels: bug, core

**Comment by mengesb** [comment] 2016-08-26 22:52
No worries. All OK. Thanks for cleaning this up
