### ISSUE TITLE
Removed fields appear in state for resources but not data sources

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform#21347] opened 2019-05-17 02:31 UTC
### Terraform Version

```
Terraform v0.12.0-rc1
+ provider.google (unversioned)
```

### Terraform Configuration Files

```hcl
resource "google_container_cluster" "kubes" {
  name               = "cluster-test-dsjlf"
  location           = "us-central1-a"
  initial_node_count = 1
}

data "google_container_cluster" "kubes" {
  name     = "${google_container_cluster.kubes.name}"
  location = "${google_container_cluster.kubes.zone}"
}
```

### Debug Output

not relevant, but can be gotten if needed

### Expected Behavior

`enable_tpu` (among other removed fields) should not be in state. If it is in state, then it should be in state for both the resource and the datasource, instead of just the resource.

### Actual Behavior

`enable_tpu` shows as null in state for the data source, and false for the resource. Output from `terraform show` has `enable_tpu` only for the resource:
https://gist.github.com/danawillow/4d249a2d8b156c8a9d473dc11ffcfd66

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform show`

### Additional Context

We have some tests in the Google provider that create a resource and a matching datasource and check that their states match. This is causing those tests to fail, since it shows up as missing (or possibly empty) in one but present in the other. It's not hard to workaround (by explicitly ignoring removed fields), but it would be nice not to have to do that.

**Comment by jbardin** [comment] 2019-05-17 14:01
Hi @danawillow,

Thanks for finding this! This was _almost_ taken care of by #21273 and #21305 (which are post rc1). However, because the fix was operating on the raw schema `cty.Type` rather than the `schema.Schema`, it fails to handle the `Removed` field. 

I'll re-work that patch to clean out those attributes during state upgrade as well.

**Comment by jbardin** [comment] 2019-05-17 19:25
Hi @danawillow,

Coming back to this change, I just realized that this is through acceptance tests, and the state is being created by the test itself, so I doubt the state upgraders are going to be able to take care of it. 

Running the config you provided also stored `null` in the `enable_tpu` field for both the resource and the data source. Can you point be to a specific test that this is failing for you? I have a feeling it's more likely the shims in the test harness that is filling in the computed value with the zero value equivalent.

**Comment by danawillow** [comment] 2019-05-17 19:45
Got it. My output above was by running the CLI, but if it's fixed there in those PRs you pointed to, then neat!

As for the failing test, it's `TestAccContainerClusterDatasource_zonal`.

**Comment by jbardin** [comment] 2019-05-17 23:26
Hi @danawillow,

While I don't think it just directly because of the referenced PRs, I confirmed that resource is testing as expected now with regards to Removed fields, but failing for another reason.

That test produces a perpetual diff, because the `master_auth.0.client_certificate_config.0.issue_client_certificate` field is forcing a new resource each time.

The config being tested sets the `master_auth` block, which means that it is specifying that the `client_certificate_config` does not exist in the config. The resource itself however is setting `client_certificate_config.0.issue_client_certificate` value on every read `Read`. Terraform is going to propose a change to remove that every time, which will include the `ForceNew`. 

Looking at the schema, it appears that the intent is to have `client_certificate_config` marked as `Computed` as well, which will fix the problem because terraform core will them accept that new value from the provider. This is the particular solution I used to make the test pass.

**Comment by danawillow** [comment] 2019-05-24 20:41
Thanks @jbardin! We're on an up-to-date sdk now and I see the problem no longer affects the boolean fields, but still affects lists:
```
testing.go:568: Step 0 error: Check failed: Check 1/1 error: pod_security_policy_config.# is ; want 0
```

And yeah, the client certificate thing is probably this open issue: https://github.com/terraform-providers/terraform-provider-google/issues/3369. I haven't looked into it at all but I know Riley has spent a fair bit of time investigating, so if you have a suggestion that might be a good place for it (although my guess is it's more complicated than it initially looks)

**Comment by jbardin** [comment] 2019-06-03 21:19
Hi @danawillow!

It looks like that other issue around empty and unset lists is sorted out (of course really comes back to `helper/schema` not being able to reliably differentiate between unset and empty). Feel free to reply here if there's still anything unresolved, but I'm going to close this for now.

**Closed by jbardin** 2019-06-03 21:19 UTC
Labels: bug, provider-sdk
