### ISSUE TITLE
terraform-12-rc1 fmt doesn't remove empty newlines

### ISSUE THREAD

**Issue by sudoforge** [hashicorp/terraform#21360] opened 2019-05-20 00:32 UTC
### Terraform Version

```
→ terraform-12-rc1 version
Terraform v0.12.0-rc1
```

### Terraform Configuration Files

```hcl
resource "github_team" "foo" {
  name =       "Foo"
  privacy = "closed"


}
```

### Debug Output

```
→ TF_LOG=trace tf12 fmt
2019/05/19 17:19:10 [INFO] Terraform version: 0.12.0 rc1
2019/05/19 17:19:10 [INFO] Go runtime version: go1.12.1
2019/05/19 17:19:10 [INFO] CLI args: []string{"/Users/username/.local/bin/terraform-12-rc1", "fmt"}
2019/05/19 17:19:10 [DEBUG] Attempting to open CLI config file: /Users/username/.terraformrc
2019/05/19 17:19:10 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/19 17:19:10 [INFO] CLI command args: []string{"fmt"}
2019/05/19 17:19:10 [TRACE] terraform fmt: looking for files in .
2019/05/19 17:19:10 [TRACE] terraform fmt: Formatting foo.tf
```

### Crash Output

N/A

### Expected Behavior

- The file should be formatted the same as in `v0.11.13` and below.

### Actual Behavior

- Newlines between the closing brace and last content line of the resource block remain behind.

### Steps to Reproduce

1. Create a file with the contents above.
2. `terraform init`
3. `terraform fmt`

```shell
→ cat foo.tf
resource "github_team" "foo" {
  name =       "Foo"
  privacy = "closed"


}

→ terraform-12-rc1 fmt
foo.tf

→ cat foo.tf
resource "github_team" "foo" {
  name    = "Foo"
  privacy = "closed"


}
```

**Comment by apparentlymart** [comment] 2019-05-20 00:46
Hi @sudoforge! Thanks for reporting this.

For Terraform v0.12 we've intentionally "weakened" the formatter somewhat, because the pre-0.12 formatter's implementation approach often led to non-convergence and outright undesirable behavior. 

Since we were forced to start over with the new parser in v0.12 anyway, we decided to make the first new version focus only on vertical spacing -- a relatively easy problem to contend with -- and then gradually improve it in later versions to carefully add other useful behaviors without re-introducing all of the pre-0.12 bugs.

For the moment then, the new behavior you've seen is intentional and is what will ship in v0.12. For now, `terraform fmt` will not add or remove newlines at all. We'll see about reintroducing this in a later release, when there's time to more thoroughly consider and test any new behavior.

Since this is intended behavior for now, and we have no plans to change it in the short term, I'm going to close this out. We'll make other issues later when it's time to consider specific additional functionality, but 100% parity with Terraform 0.11's `terraform fmt` is not a goal. Thanks for reporting this, though!

**Closed by apparentlymart** 2019-05-20 00:46 UTC

**Comment by sudoforge** [comment] 2019-05-20 00:52
@apparentlymart I must have missed that in the discussions around `0.12.0`, my apologies. Thanks for the informative comment -- I imagine you meant that the first new version of `fmt` will focus on _horizontal_ spacing, not _vertical_, right?

**Comment by apparentlymart** [comment] 2019-05-20 01:13
Sorry, yes... I did indeed mean _horizontal_ spacing.
