### ISSUE TITLE
terraform crash when destroying instances in +/- replacement

### ISSUE THREAD

**Issue by chrisrlong** [hashicorp/terraform#10342] opened 2016-11-24 14:30 UTC
### Terraform Version
Terraform v0.8.0-rc1 (aac47ecf8421da8573155951e36ce5c1aa3fd3a2) windows amd64

### Affected Resource(s)
- aws_instance
   destroying a replaced instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "bastion" {
  count = "${length(compact(split(",", var.azs)))}"
  ami = "${var.ec2_ami}"
  instance_type = "t2.micro"
  key_name = "x"
  subnet_id = "${element(split(",", var.public_subnets), count.index)}"
  vpc_security_group_ids = ["${split(",", var.security_groups)}"]
  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      "vpc_security_group_ids"
    ]
  }
  connection {
    private_key = "${file("keys/x.pem")}"
    user = "x"
  }
  provisioner "remote-exec" {
    inline = [
...
    ]
  }
  provisioner "chef" {
...
}
```

### Panic Output
module.bastion.aws_instance.bastion.0 (deposed #0): Destruction complete
module.bastion.aws_instance.bastion.1 (deposed #0): Still destroying... (29s elapsed)
panic: runtime error: index out of range

goroutine 17952 [running]:
panic(0x2feacc0, 0xc042010050)
        /opt/go/src/runtime/panic.go:500 +0x1af
github.com/hashicorp/terraform/terraform.(*EvalWriteStateDeposed).Eval.func1(0xc042a2a120, 0xc0428e91a0, 0xc04237f180)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_state.go:163 +0x187
github.com/hashicorp/terraform/terraform.writeInstanceToState(0x51a2ec0, 0xc042482000, 0xc04237f180, 0x16, 0xc0421481d1, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_state.go:208 +0x1f1
github.com/hashicorp/terraform/terraform.(*EvalWriteStateDeposed).Eval(0xc042504d80, 0x51a2ec0, 0xc042482000, 0x2, 0x2, 0xc042a6bcf0, 0xc)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_state.go:167 +0xd3
github.com/hashicorp/terraform/terraform.EvalRaw(0x51885e0, 0xc042504d80, 0x51a2ec0, 0xc042482000, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x186
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0428c2020, 0x51a2ec0, 0xc042482000, 0x2, 0x2, 0xc042b2d320, 0xc)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0x73
github.com/hashicorp/terraform/terraform.EvalRaw(0x5188220, 0xc0428c2020, 0x51a2ec0, 0xc042482000, 0x33, 0x0, 0x0, 0x33)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x186
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc042008240, 0x51a2ec0, 0xc042482000, 0x2, 0x2, 0xc042b2d2f0, 0xc)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x53
github.com/hashicorp/terraform/terraform.EvalRaw(0x5187fe0, 0xc042008240, 0x51a2ec0, 0xc042482000, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x186
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc042c6daa0, 0x51a2ec0, 0xc042482000, 0x2, 0x2, 0xc042b2d230, 0xc)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0x73
github.com/hashicorp/terraform/terraform.EvalRaw(0x5188220, 0xc042c6daa0, 0x51a2ec0, 0xc042482000, 0x5188220, 0xc042c6daa0, 0xc04239d590, 0x23)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x186
github.com/hashicorp/terraform/terraform.Eval(0x5188220, 0xc042c6daa0, 0x51a2ec0, 0xc042482000, 0xc042c6daa0, 0x5188220, 0xc042c6daa0, 0x38838a0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x5a
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x307b7e0, 0xc042a62540, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:301 +0xe83
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc0421492b0, 0xc042330870, 0xc0421492c0, 0xc0420e26f0, 0xc0421492d0, 0x307b7e0, 0xc042a62540, 0xc042afcc00, 0xc042afcd20)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:246 +0x258
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
        /opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:255 +0x6ad

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Expected Behavior
Terraform would finish destroying the instance and exit gracefully

### Actual Behavior
Please see above panic output.

### Steps to Reproduce

1. `terraform apply`

In this case terraform is replacing 2 ec2 instances. apply will complete on the second run. Also the state file is not updated on the crashed run, so although the servers were created the next plan/apply does not detect the instances and was to create as new  (not +/-).

**Comment by mitchellh** [comment] 2016-11-29 17:24
This is actually a dup of #10338 (caused by the same thing).

This will be fixed by that PR refed there.

**Closed by mitchellh** 2016-11-29 17:24 UTC
Labels: bug, core, crash
