### ISSUE TITLE
Call to function "element" failed: cannot read elements from set of string

### ISSUE THREAD

**Issue by pradeep151287** [hashicorp/terraform#22392] opened 2019-08-08 12:09 UTC
### Terraform Version

```
Terraform v0.12.5
+ provider.aws v2.23.0
```

### Terraform Configuration Files

```hcl
data "aws_subnet_ids" "subnet" {
  vpc_id = ""
}

output "sub2" {
  value = element(data.aws_subnet_ids.subnet1.ids,0)
}
```

### Expected Behavior

element would have shown index 0 value 
### Actual Behavior

data.aws_subnet_ids.subnet1: Refreshing state...
data.aws_subnet_ids.subnet: Refreshing state...

Error: Error in function call

  on output.tf line 10, in output "sub2":
  10:   value = element(data.aws_subnet_ids.subnet1.ids,0)
    |----------------
    | data.aws_subnet_ids.subnet1.ids is set of string with 6 elements

Call to function "element" failed: cannot read elements from set of string.
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by pradeep151287** [comment] 2019-08-08 12:10
Expected Behavior
element should show index 0 vaule 

Actual Behavior:

data.aws_subnet_ids.subnet1: Refreshing state...
data.aws_subnet_ids.subnet: Refreshing state...

Error: Error in function call

  on output.tf line 10, in output "sub2":
  10:   value = element(data.aws_subnet_ids.subnet1.ids,0)
    |----------------
    | data.aws_subnet_ids.subnet1.ids is set of string with 6 elements

Call to function "element" failed: cannot read elements from set of string.

**Comment by apparentlymart** [comment] 2019-08-09 00:53
Hi @pradeep151287,

As the error message mentioned, `data.aws_subnet_ids.subnet1.ids` is a [set](https://www.terraform.io/docs/configuration/types.html#set-) value, which means it's an unordered collection of unique strings.

The `aws_subnet_ids` data source uses a set type for this result because the ids it's returning are not in any specific order, and so without additional information there is no way to decide which one is "first" and thus which one should be returned at index zero.

To select a single "first" element from this set requires the items to be placed in some order. If you don't actually care which of the six subnet ids you get and are just looking for any single subnet in a particular VPC then a straightforward answer is to first [sort the subnet ids lexically](https://www.terraform.io/docs/configuration/functions/sort.html) and then take the first one from that sorted result:

```hcl
output "sub2" {
  value = sort(data.aws_subnet_ids.subnet1.ids)[0]
}
```

(I also switched to using the index syntax with `[0]` rather than the `element` function, because using the `element` function to index a list is a deprecated form kept only for compatibility with Terraform 0.11 and earlier.)

If sorting and taking the first result is not precise enough for what you need here then you may need to impose some additional filters on the `aws_subnet_ids` data source to select only the single subnet you want to use, or at least to reduce the resultset further such that `sort` _is_ a suitable solution.

Terraform does not perform this conversion automatically because it can't be sure that sorting is the desired behavior, and because writing `sort(...)` explicitly in your configuration will make it clearer to future readers of this configuration that it's taking the first result _after lexical sorting_. With that said, Terraform is working as intended here, and so I'm going to close this issue.

If you have any follow-up questions, feel free to ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are generally monitored only by our few core maintainers.

**Closed by apparentlymart** 2019-08-09 00:53 UTC
Labels: config, question
