### ISSUE TITLE
provider within a module does not transfer the default_tags if the module provider gets an alias

### ISSUE THREAD

**Issue by purplexed** [hashicorp/terraform#29500] opened 2021-09-01 15:10 UTC
### Terraform Version
```
Terraform v1.0.3
```

### Terraform Configuration Files

This is the module main.tf config file 
```modules/module_1/main.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 2.7.0"
      configuration_aliases = [ aws.cloudwatch]
    }
  }
}
```

The following is the main project main.tf config file:
```project/main.tf
variable "app" {
  default = "my-awesome-app"
}

provider "aws" {
  default_tags {
    tags = {
      App       = var.app
    }
  }
  region = var.region
}

provider "aws" {
  default_tags {
    tags = {
      App       = "${var.app}-sandbox"
    }
  }
  alias  = "sandbox"
  region = var.region
}
```

And lastly, this is how 2 resources are created in the project repo:
```project/cloudwatch.tf
module "cloudwatch" {
  source = "git::ssh:/git@my-repo/modules.git//modules/module_1?ref=develop"
  providers = {
    aws.cloudwatch = aws
  }
}

module "cloudwatch-sandbox" {
  source = "git::ssh:/git@my-repo/modules.git//modules/module_1?ref=develop"
  providers = {
    aws.cloudwatch = aws.sandbox
  }
}
```
### Debug Output
No error

### Crash Output
No crash

### Expected Behavior
I'd expect the non-sandbox resources (the ones being created with the `aws.cloudwatch = aws` provider) that are declared within the `cloudwatch.tf` module to be tagged with the tag `App=my-awesome-app`. Similarly, I would expect that the sandbox resources  (the ones being created with the `aws.cloudwatch = aws.sandbox` provider) to be tagged with the tag `App=my-awesome-app-sandbox`.

### Actual Behavior
All resources for both the non-sandbox and the sandbox modules are being tagged with the tags from the `aws` provider, thus applying the `App=my-awesome-app` tag in both cases.

### Steps to Reproduce
Use the scripts as mentioned above, but add a resources under the `modules/module_1/main.tf` in order to check out the applied tags.

### Additional Details
If I won't use an alias in the provider within the `modules/module_1/main.tf` and I declare the modules as following

```project/cloudwatch.tf
module "cloudwatch" {
  source = "git::ssh:/git@my-repo/modules.git//modules/module_1?ref=develop"
  providers = {
    aws = aws
  }
}

module "cloudwatch-sandbox" {
  source = "git::ssh:/git@my-repo/modules.git//modules/module_1?ref=develop"
  providers = {
    aws = aws.sandbox
  }
}
```

it works as expected, but I get the respective terraform warning:

```
Module module.module_1 does not declare a provider named aws.cloudwatch. If you wish to specify a provider configuration for the module, add an entry for aws.cloudwatch in the required_providers block within the module.
```

### References
There is a chance the issue above is related to the following tickets:
- #29225 (Closed, but not implemented)
- #19932
- #24476

**Comment by apparentlymart** [comment] 2021-09-01 15:36
Hi @purplexed! Thanks for reporting this.

In this particular case the debug output that we request in our issue template is how we'd usually understand which provider configuration Terraform connected each resource to, so in order to proceed here I think we'll either need to see that, or alternatively there's a more fiddly but also more selective way to get that information, since you were already able to get a successful apply, albeit with a different result than you expected:

* Run `terraform state pull` to retrieve the latest internal state snapshot, which happens to be serialized in JSON as an implementation detail, so we can manually inspect it for debugging purposes here.
* In the resulting JSON data structure (which you might wish to pretty-print first, in case it's hard to read), look through the structure to find the resource objects that seem to match up with the resources whose final tags didn't match what you set in `default_tags`. (This'll be under the top-level property "resources", and you can recognize it by matching the type, name and module address.)
* Identify the `provider` property of the resource(s) in question, which records which provider configuration Terraform most recently used to make changes to that resource.

Based on what you've shared here, I'd expect each of them to have one of the following values to record that it was associated with one of your provider configurations in the root module:

* `provider["registry.terraform.io/hashicorp/aws"]` (the default, unaliased configuration)
* `provider["registry.terraform.io/hashicorp/aws"].sandbox` (your additional aliased configuration)

Based on what you described, I assume that what you'd expect to see here is that all of the resources belonging to `module.cloudwatch` would record `provider["registry.terraform.io/hashicorp/aws"]`, while all of the resources belonging to `module.cloudwatch-sandbox` would record `provider["registry.terraform.io/hashicorp/aws"].sandbox`.

The reason this is important is that it can help to determine whether the problem is that Terraform selected the wrong provider configuration for these resources, or whether what happened is something more specific to this provider.

Alternatively, if you can share the debug log output originally requested (in a [GitHub Gist](https://gist.github.com/)) then we should be able to infer similar information from the details in that log, which includes the process of associating resources with provider configurations.

**Comment by purplexed** [comment] 2021-09-01 16:14
Hey @apparentlymart , thanks a lot for your prompt reply.

The output of the statefile looks as follows, without any `default_tags` field, but a `tags_all` instead:

```
{
  "version": 4,
  "terraform_version": "1.0.3",
  "serial": 8,
  "lineage": "97b79cec-f719-5233-4ff3-ebe6d88e03c9",
  "outputs": {},
  "resources": [
    {
      "module": "module.cloudwatch",
      "mode": "managed",
      "type": "aws_cloudwatch_event_rule",
      "name": "event-rule",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:events:REGION:ACCOUNT_ID:rule/my-awesome-app",
            "description": "Captures S3 Put events",
            "event_bus_name": "default",
            "event_pattern": "{\"detail\":{\"eventName\":[\"PutObject\",\"CompleteMultipartUpload\"],\"eventSource\":[\"s3.amazonaws.com\"],\"requestParameters\":{\"bucketName\":[\"my-bucket\"],\"key\":[{\"prefix\":\"raw\"}]}},\"detail-type\":[\"AWS API Call via CloudTrail\"],\"source\":[\"aws.s3\"]}",
            "id": "my-awesome-app",
            "is_enabled": true,
            "name": "my-awesome-app",
            "name_prefix": "",
            "role_arn": "",
            "schedule_expression": "",
            "tags": null,
            "tags_all": {
              "App": "my-awesome-app"
            }
          },
          "sensitive_attributes": [],
          "private": "mypriv"
        }
      ]
    },
    {
      "module": "module.cloudwatch-sandbox",
      "mode": "managed",
      "type": "aws_cloudwatch_event_rule",
      "name": "event-rule",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:events:REGION:ACCOUNT_ID:rule/my-awesome-app-sandbox",
            "description": "Captures S3 Put events",
            "event_bus_name": "default",
            "event_pattern": "{\"detail\":{\"eventName\":[\"PutObject\",\"CompleteMultipartUpload\"],\"eventSource\":[\"s3.amazonaws.com\"],\"requestParameters\":{\"bucketName\":[\"my-bucket\"],\"key\":[{\"prefix\":\"raw\"}]}},\"detail-type\":[\"AWS API Call via CloudTrail\"],\"source\":[\"aws.s3\"]}",
            "id": "my-awesome-app-sandbox",
            "is_enabled": true,
            "name": "my-awesome-app-sandbox",
            "name_prefix": "",
            "role_arn": "",
            "schedule_expression": "",
            "tags": null,
            "tags_all": {
              "App": "my-awesome-app"
            }
          },
          "sensitive_attributes": [],
          "private": "mypriv"
        }
      ]
    }
  ]
}
```

Hope this helps!

**Comment by jbardin** [comment] 2021-09-01 17:17
Hi @purplexed,

Thanks, that shows the instances in both modules are using the default `aws` provider. Seeing how moth modules have the same source, and these are the same instance within the module, there would be no way for the resources to have different providers, since the latter would have to set `provider = aws.cloudwatch` in the `aws_cloudwatch_event_rule` configuration in order to use the alias.

Can you show a more complete example with the module contents for that resource?

**Comment by purplexed** [comment] 2021-09-02 09:35
Hey @jbardin , sure thing. The code I have are as follows:

```tree
.
├── modules
│   └── module_1
│       ├── cloudwatch-resources.tf
│       ├── main.tf
│       └── vars.tf
└── platform
    ├── cloudwatch.tf
    ├── main.tf
    ├── terraform.tfstate
    ├── terraform.tfstate.backup
    └── vars.tf
```

```modules/module_1/cloudwatch-resources.tf
resource "aws_cloudwatch_event_rule" "event-rule" {
  name        = var.name
  description = "Captures S3 Put events"

  event_pattern = <<PATTERN
{
  "source": ["aws.s3"],
  "detail-type": ["AWS API Call via CloudTrail"],
  "detail": {
    "eventSource": ["s3.amazonaws.com"],
    "eventName": ["PutObject","CompleteMultipartUpload"],
    "requestParameters": {
      "bucketName": ["my-bucket"],
      "key": [{
        "prefix": "raw"
      }]
    }
  }
}
PATTERN
}
```

```modules/module_1/main.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 2.7.0"
      configuration_aliases = [ aws.cloudwatch]
    }
  }
}
```


```modules/module_1/vars.tf
variable "name" {}
```

```platform/cloudwatch.tf
module "cloudwatch" {
  source = "../modules/module_1"
  providers = {
    aws.cloudwatch = aws
  }
  name = var.app
}

module "cloudwatch-sandbox" {
  source = "../modules/module_1"
  providers = {
    aws.cloudwatch = aws.sandbox
  }
  name = "${var.app}-sandbox"
}
```

```platform/main.tf
provider "aws" {
  default_tags {
    tags = {
      App       = var.app
    }
  }
  region = var.region
}

provider "aws" {
  default_tags {
    tags = {
      App       = "${var.app}-sandbox"
    }
  }
  alias  = "sandbox"
  region = var.region
}
```

```platform/vars.tf
variable "app" {
  default = "my-awesome-app"
}

variable "region" {
  default = "MYREGION"
}
```

Please let me know if you'd need more details.

**Comment by jbardin** [comment] 2021-09-02 14:47
Thanks @purplexed,

The `aws_cloudwatch_event_rule` resource does not declare a specific provider, so it use the default `aws` provider rather than `aws.cloudwatch`. If you want it to use the aliased provider name, you must declare that with the `provider = aws.cloudwatch` argument.

Since terraform is working as expected here I'm going to close the issue. If you have any follow up question feel free to reply here, or ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-09-02 14:47 UTC
Labels: bug, waiting-response, new

**Comment by purplexed** [comment] 2021-09-02 17:53
Hey @jbardin , thanks fr your reply.
Since the module `"cloudwatch-sandbox"` is built using a specific provider, and it should be passing that through to the `aws_cloudwatch_event_rule` resource, right?

For example, the following changes work as expected, passing the sandbox tag of the `App` through:
**modules/module_1/main.tf**
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 2.7.0"
    }
  }
}
```

**platform/cloudwatch.tf**
```
module "cloudwatch" {
  source = "../modules/module_1"
  providers = {
    aws.cloudwatch = aws
  }
  name = var.app
}

module "cloudwatch-sandbox" {
  source = "../modules/module_1"
  providers = {
    aws.cloudwatch = aws.sandbox
  }
  name = "${var.app}-sandbox"
}
```

These changes would tag the `aws_cloudwatch_event_rule` that is created from the `cloudwatch-sandbox` module as `App=my-awesome-app-sandbox`, which is what's expected from the above as well.

**Comment by jbardin** [comment] 2021-09-02 20:32
@purplexed, within the module block, specifying a mapping of 
```
  providers = {
    aws.cloudwatch = aws
  }
```
roughly means "references to the `aws.cloudwatch` provider within the module will use this `aws` provider".
If the resources do not specify the `aws.cloudwatch` provider, they are not going to use that provider configuration.

If you want the `aws` provider within the module to use the `aws.cloudwatch` provider from the root module, the configuration which you already confirmed works is the correct way to do it, e.g.
```
  providers = {
    aws = aws.sandbox
  }
```

**Comment by purplexed** [comment] 2021-09-03 14:56
Hey @jbardin , apologies I pasted the wrong block of code 🤦‍♂️; edited to show the correct one.

Using the recommended way works, but I get the following warning:
```
Module module.module_1 does not declare a provider named aws.cloudwatch. If you wish to specify a provider configuration for the module, add an entry for aws.cloudwatch in the required_providers block within the module.
```
This is the reason why I changed the
```
  providers = {
    aws = aws.sandbox
  }
```
to
```
  providers = {
    aws.cloudwatch = aws.sandbox
  }
```
So, it's either the warning or the `aws.cloudwatch` provider in the module defaulting to the `aws` provider in the `main.tf`.

**Comment by jbardin** [comment] 2021-09-03 15:24
That error is what you would see if you attempted to assign a provider to the `aws.cloudwatch` alias but it was not declared within the module, so I'm not sure you would get that error when assigning only to `aws`. Also, the `module_1` config shown here does declare the `aws.cloudwatch` alias, so I don't think you are getting that error from the given configuration.
