### ISSUE TITLE
crash in module loading during init

### ISSUE THREAD

**Issue by PLJumpstart** [hashicorp/terraform#30090] opened 2021-12-05 19:06 UTC
```
user@DESKTOP-S2DH27D:~/OCI/terraform/stage$ fg
terraform init
unexpected fault address 0xc6ca407000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc6ca407000 pc=0x46ecef]

goroutine 1 [running]:
runtime.throw(0x2830a60, 0x5)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0c49d0a38 sp=0xc0c49d0a08 pc=0x4366b2
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0xc0c49d0a70 sp=0xc0c49d0a38 pc=0x44d328
runtime.memmove(0xc6a589e000, 0xc58cfac000, 0x1188f1fe0)
        /usr/local/go/src/runtime/memmove_amd64.s:425 +0x50f fp=0xc0c49d0a78 sp=0xc0c49d0a70 pc=0x46ecef
runtime.growslice(0x25ad740, 0xc58cfac000, 0x2ec2855, 0x2ec2855, 0x2ec2856, 0xc1d794bc71, 0x1, 0x3ce7b90)
        /usr/local/go/src/runtime/slice.go:237 +0x1a5 fp=0xc0c49d0ae0 sp=0xc0c49d0a78 pc=0x44e745
github.com/hashicorp/hcl/v2/hclsyntax.(*tokenAccum).emitToken(0xc0c49d0f28, 0xc000000051, 0x964bc6e, 0x964bc72)
        /home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.10.0/hclsyntax/token.go:151 +0x34b fp=0xc0c49d0bf0 sp=0xc0c49d0ae0 pc=0x885dcb
github.com/hashicorp/hcl/v2/hclsyntax.scanTokens.func1(...)
        scan_tokens.rl:348
github.com/hashicorp/hcl/v2/hclsyntax.scanTokens(0xc1ce300000, 0xd333800, 0xd333801, 0xc00004e990, 0xb, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        NONE:5 +0x138f fp=0xc0c49d0f98 sp=0xc0c49d0bf0 pc=0x87b06f
github.com/hashicorp/hcl/v2/hclsyntax.LexConfig(0xc1ce300000, 0xd333800, 0xd333801, 0xc00004e990, 0xb, 0x1, 0x1, 0x0, 0x4eb965, 0x243f420, ...)
        /home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.10.0/hclsyntax/public.go:126 +0x96 fp=0xc0c49d1020 sp=0xc0c49d0f98 pc=0x878c56
github.com/hashicorp/hcl/v2/hclsyntax.ParseConfig(0xc1ce300000, 0xd333800, 0xd333801, 0xc00004e990, 0xb, 0x1, 0x1, 0x0, 0xe5af55, 0xc00004e990, ...)
        /home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.10.0/hclsyntax/public.go:18 +0x9e fp=0xc0c49d1150 sp=0xc0c49d1020 pc=0x877b7e
github.com/hashicorp/hcl/v2/hclparse.(*Parser).ParseHCL(0xc0c49d12d0, 0xc1ce300000, 0xd333800, 0xd333801, 0xc00004e990, 0xb, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.10.0/hclparse/parser.go:57 +0xda fp=0xc0c49d11e0 sp=0xc0c49d1150 pc=0x9dc8fa
github.com/hashicorp/terraform-config-inspect/tfconfig.loadModule(0x2ca4088, 0x3db2308, 0x282db7d, 0x1, 0x20, 0xc000052004, 0x20, 0x2cd0f20)
        /home/circleci/go/pkg/mod/github.com/hashicorp/terraform-config-inspect@v0.0.0-20210209133302-4fd17a0faac2/tfconfig/load_hcl.go:38 +0x327 fp=0xc0c49d1450 sp=0xc0c49d11e0 pc=0xe5c1a7
github.com/hashicorp/terraform-config-inspect/tfconfig.LoadModuleFromFilesystem(0x2ca4088, 0x3db2308, 0x282db7d, 0x1, 0x20, 0x282db7d, 0x1, 0x0)
        /home/circleci/go/pkg/mod/github.com/hashicorp/terraform-config-inspect@v0.0.0-20210209133302-4fd17a0faac2/tfconfig/load.go:27 +0x67 fp=0xc0c49d14e0 sp=0xc0c49d1450 pc=0xe5b087
github.com/hashicorp/terraform-config-inspect/tfconfig.LoadModule(...)
        /home/circleci/go/pkg/mod/github.com/hashicorp/terraform-config-inspect@v0.0.0-20210209133302-4fd17a0faac2/tfconfig/load.go:14
github.com/hashicorp/terraform/internal/earlyconfig.LoadModule(0x282db7d, 0x1, 0x20, 0x282db7d, 0x1, 0x1)
        /home/circleci/project/project/internal/earlyconfig/module.go:11 +0x51 fp=0xc0c49d1538 sp=0xc0c49d14e0 pc=0xe71671
github.com/hashicorp/terraform/internal/command.(*Meta).loadSingleModuleEarly(0xc000292000, 0xc000052004, 0x20, 0xc0008b3ef0, 0xc41b7de000, 0x1b7e576, 0x1e1fc00)
        /home/circleci/project/project/internal/command/meta_config.go:113 +0x5e fp=0xc0c49d15a8 sp=0xc0c49d1538 pc=0x218639e
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc000292000, 0xc000140010, 0x0, 0x0, 0xc0005be3a0)
        /home/circleci/project/project/internal/command/init.go:154 +0xa85 fp=0xc0c49d18f0 sp=0xc0c49d15a8 pc=0x2167925
github.com/mitchellh/cli.(*CLI).Run(0xc000597cc0, 0xc0005c0810, 0x282f31d, 0x4)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a fp=0xc0c49d1a38 sp=0xc0c49d18f0 pc=0xdac2ba
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:384 +0x1112 fp=0xc0c49d1e30 sp=0xc0c49d1a38 pc=0x21de612
main.realMain(0x0)
        /home/circleci/project/project/main.go:115 +0x554 fp=0xc0c49d1f70 sp=0xc0c49d1e30 pc=0x21dd334
main.main()
        /home/circleci/project/project/main.go:58 +0x25 fp=0xc0c49d1f88 sp=0xc0c49d1f70 pc=0x21dcdc5
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0c49d1fe0 sp=0xc0c49d1f88 pc=0x438ef6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0c49d1fe8 sp=0xc0c49d1fe0 pc=0x46d9e1

goroutine 5 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000b0000)
        /home/circleci/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
        /home/circleci/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x68

goroutine 13 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x3d7ec20)
        /home/circleci/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1018 +0x8b
created by k8s.io/klog.init.0
        /home/circleci/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:404 +0x6c

goroutine 14 [syscall, 7 minutes]:
os/signal.signal_recv(0x2c8a298)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
[crash.975071695.log](https://github.com/hashicorp/terraform/files/7656624/crash.975071695.log)

        /usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 22 [chan send, 7 minutes]:
main.makeShutdownCh.func1(0xc00013c900, 0xc00005c4e0)
        /home/circleci/project/project/commands.go:423 +0x4c
created by main.makeShutdownCh
        /home/circleci/project/project/commands.go:420 +0xf2




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.975071695.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.975071695.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
pjoyce@DESKTOP-S2DH27D:~/OCI/terraform/stage$
```

**Comment by jbardin** [comment] 2021-12-06 14:00
Hi @PLJumpstart,

Thanks for filing the issue! Can you provide any more information about the configuration that generated the crash, and verify if the crash is still present in the latest release?

Thanks!

**Comment by PLJumpstart** [comment] 2021-12-06 14:13
Sure
I am running on Windows 10 ubuntu shell (standard with windoz)I am building an OCI (oracle) set up with a a network, 2 sub nets, compute instance and DB server and other stuff like bastion . load balancer etc
All was working fine.  Then I needed some help and got a colleague to help me remotely.
He got it working with the same files on his machine.  Then this is probably where it got screwed.
As the setup is new - and he created it with apply - there was a state file.  I took a copy of the state file and dropped it in the root folder and ran tfinit and thats what screwed it.
I realised that this was probably pretty dumb and tried init etc, then deleted the state files and lock file and it is completely screwed now.So, init will not run now.  I think I will have to re-install TF and manually delete ALL of the infrastructure and start from scratch - which is a total PITA.
I am happy to provide more info if you wish.
Also - same scripts workd fin on an other tenancy -

And yeah - dumb on my side - but it really should not seize up like that IMO.
paul

Want private search? duckduckgo  or www.qwant.com
 

    On Monday, December 6, 2021, 02:00:53 PM GMT, James Bardin ***@***.***> wrote:  
 
 


Hi @PLJumpstart,

Thanks for filing the issue! Can you provide any more information about the configuration that generated the crash, and verify if the crash is still present in the latest release?

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jbardin** [comment] 2021-12-06 15:45
Thanks @PLJumpstart,

The crash is happening when initially loading the configuration, so I don't think removing recreating the infrastructure is going to solve the problem. Have you verified this still happens against the latest release (even better would be v1.1.0-rc1) and can you provide a configuration example which causes the crash? The logs output from `init` when setting `TF_LOG=trace` may be helpful as well.

**Comment by PLJumpstart** [comment] 2021-12-06 16:11
Hi James
Ok - I will see if I can easily upgrade and try again.
Can I use apt without getting the full HC repo?
thankspaul

Want private search? duckduckgo  or www.qwant.com
 

    On Monday, December 6, 2021, 03:46:01 PM GMT, James Bardin ***@***.***> wrote:  
 
 


Thanks @PLJumpstart,

The crash is happening when initially loading the configuration, so I don't think removing recreating the infrastructure is going to solve the problem. Have you verified this still happens against the latest release (even better would be v1.1.0-rc1) and can you provide a configuration example which causes the crash? The logs output from init when setting TF_LOG=trace may be helpful as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PLJumpstart** [comment] 2021-12-06 20:27
James
Just for FYI
I upgraded all (sudo apt upgrade)
Then I ran 

terraform init -upgrade
and got this line repeating for ever 


│ Error: Invalid character
│
│ On tf-stage.tf line 14027: This character is not used within the language.
╵

╷
│ Error: Invalid character
│
│ On tf-stage.tf line 14027: This character is not used within the language.
╵

╷
│ Error: Invalid character
│
│ On tf-stage.tf line 14027: This character is not used within the language.
╵

p

Want private search? duckduckgo  or www.qwant.com
 

    On Monday, December 6, 2021, 03:46:01 PM GMT, James Bardin ***@***.***> wrote:  
 
 


Thanks @PLJumpstart,

The crash is happening when initially loading the configuration, so I don't think removing recreating the infrastructure is going to solve the problem. Have you verified this still happens against the latest release (even better would be v1.1.0-rc1) and can you provide a configuration example which causes the crash? The logs output from init when setting TF_LOG=trace may be helpful as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jbardin** [comment] 2021-12-06 20:33
Thanks for the update @PLJumpstart, It looks like the cause of the crash has been fixed in the interim, so the error output should now allow you to track down the invalid configuration.

**Comment by PLJumpstart** [comment] 2021-12-06 22:52
Don't be in such a rush !
***@***.***:~/OCI/terraform/stage$ terraform --version
Terraform v1.0.11
on linux_amd64
***@***.***:~/OCI/terraform/stage$ setenv TF_LOG=TRACE
setenv: command not found
***@***.***:~/OCI/terraform/stage$ export TF_LOG=TRACE
***@***.***:~/OCI/terraform/stage$ terraform init
2021-12-06T22:43:12.170Z [DEBUG] Adding temp file log sink: /tmp/terraform-log808749427
2021-12-06T22:43:12.171Z [INFO]  Terraform version: 1.0.11
2021-12-06T22:43:12.171Z [INFO]  Go runtime version: go1.16.4
2021-12-06T22:43:12.171Z [INFO]  CLI args: []string{"/usr/bin/terraform", "init"}
2021-12-06T22:43:12.171Z [TRACE] Stdout is a terminal of width 211
2021-12-06T22:43:12.171Z [TRACE] Stderr is a terminal of width 211
2021-12-06T22:43:12.171Z [TRACE] Stdin is a terminal
2021-12-06T22:43:12.171Z [DEBUG] Attempting to open CLI config file: /home/pjoyce/.terraformrc
2021-12-06T22:43:12.171Z [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021-12-06T22:43:12.172Z [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-12-06T22:43:12.203Z [DEBUG] ignoring non-existing provider search directory /home/pjoyce/.terraform.d/plugins
2021-12-06T22:43:12.203Z [DEBUG] ignoring non-existing provider search directory /home/pjoyce/.local/share/terraform/plugins
2021-12-06T22:43:12.203Z [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021-12-06T22:43:12.203Z [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2021-12-06T22:43:12.203Z [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2021-12-06T22:43:12.223Z [INFO]  CLI command args: []string{"init"}
unexpected fault address 0xc51b28d000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc51b28d000 pc=0x46e80f]

goroutine 1 [running]:
runtime.throw(0x2728646, 0x5)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000134a70 sp=0xc000134a40 pc=0x4366b2
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0xc000134aa8 sp=0xc000134a70 pc=0x44d328
runtime.memmove(0xc4d2e6a000, 0xc37433a000, 0x15eb2ffc0)
        /usr/local/go/src/runtime/memmove_amd64.s:425 +0x50f fp=0xc000134ab0 sp=0xc000134aa8 pc=0x46e80f
runtime.growslice(0x24d4440, 0xc37433a000, 0x3a732aa, 0x3a732aa, 0x3a732ab, 0xc00bc77e2e, 0x1, 0x20db9d3)
        /usr/local/go/src/runtime/slice.go:237 +0x1a5 fp=0xc000134b18 sp=0xc000134ab0 pc=0x44e745
github.com/hashicorp/hcl/v2/hclsyntax.(*tokenAccum).emitToken(0xc000134f60, 0xc00001f4a9, 0xb257e2e, 0xb257e2f)
        ***@***.***/hclsyntax/token.go:151 +0x34b fp=0xc000134c28 sp=0xc000134b18 pc=0x88696b
github.com/hashicorp/hcl/v2/hclsyntax.scanTokens.func1(...)
        scan_tokens.rl:348
github.com/hashicorp/hcl/v2/hclsyntax.scanTokens(0xc000a20000, 0xd333800, 0xd333801, 0xc000122a00, 0xb, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        scan_tokens.rl:303 +0x44bf fp=0xc000134fd0 sp=0xc000134c28 pc=0x87ed3f
github.com/hashicorp/hcl/v2/hclsyntax.LexConfig(0xc000a20000, 0xd333800, 0xd333801, 0xc000122a00, 0xb, 0x1, 0x1, 0x0, 0x4eab85, 0x2364ce0, ...)
        ***@***.***/hclsyntax/public.go:126 +0x96 fp=0xc000135058 sp=0xc000134fd0 pc=0x8797f6
github.com/hashicorp/hcl/v2/hclsyntax.ParseConfig(0xc000a20000, 0xd333800, 0xd333801, 0xc000122a00, 0xb, 0x1, 0x1, 0x0, 0xe613b5, 0xc000122a00, ...)
        ***@***.***/hclsyntax/public.go:18 +0x9e fp=0xc000135188 sp=0xc000135058 pc=0x87871e
github.com/hashicorp/hcl/v2/hclparse.(*Parser).ParseHCL(0xc000135308, 0xc000a20000, 0xd333800, 0xd333801, 0xc000122a00, 0xb, 0x0, 0x0, 0x0, 0x0)
        ***@***.***/hclparse/parser.go:57 +0xda fp=0xc000135218 sp=0xc000135188 pc=0x9e1ffa
github.com/hashicorp/terraform-config-inspect/tfconfig.loadModule(0x2b9c6c8, 0x3c95d18, 0x272576d, 0x1, 0x20, 0xc000052004, 0x20, 0x2bc4210)
        ***@***.***/tfconfig/load_hcl.go:38 +0x327 fp=0xc000135488 sp=0xc000135218 pc=0xe62607
github.com/hashicorp/terraform-config-inspect/tfconfig.LoadModuleFromFilesystem(0x2b9c6c8, 0x3c95d18, 0x272576d, 0x1, 0x20, 0x272576d, 0x1, 0x0)
        ***@***.***/tfconfig/load.go:27 +0x67 fp=0xc000135518 sp=0xc000135488 pc=0xe614e7
github.com/hashicorp/terraform-config-inspect/tfconfig.LoadModule(...)
        ***@***.***/tfconfig/load.go:14
github.com/hashicorp/terraform/internal/earlyconfig.LoadModule(0x272576d, 0x1, 0x20, 0x272576d, 0x1, 0x0)
        /home/circleci/project/project/internal/earlyconfig/module.go:11 +0x51 fp=0xc000135570 sp=0xc000135518 pc=0xe77ad1
github.com/hashicorp/terraform/internal/command.(*Meta).loadSingleModuleEarly(0xc00033c000, 0xc000052004, 0x20, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/internal/command/meta_config.go:113 +0x5e fp=0xc0001355e0 sp=0xc000135570 pc=0x20b22fe
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc00033c000, 0xc00004c050, 0x0, 0x0, 0xc0000994f0)
        /home/circleci/project/project/internal/command/init.go:155 +0xae5 fp=0xc0001358f0 sp=0xc0001355e0 pc=0x2093865
github.com/mitchellh/cli.(*CLI).Run(0xc0001cc280, 0xc000120900, 0x2726f08, 0x4)
        ***@***.***/cli.go:262 +0x41a fp=0xc000135a38 sp=0xc0001358f0 pc=0xdb271a
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:384 +0x1112 fp=0xc000135e30 sp=0xc000135a38 pc=0x210a572
main.realMain(0x0)
        /home/circleci/project/project/main.go:115 +0x554 fp=0xc000135f70 sp=0xc000135e30 pc=0x2109294
main.main()
        /home/circleci/project/project/main.go:58 +0x25 fp=0xc000135f88 sp=0xc000135f70 pc=0x2108d25
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000135fe0 sp=0xc000135f88 pc=0x438ef6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000135fe8 sp=0xc000135fe0 pc=0x46d501

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000198d80)
        ***@***.***/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
        ***@***.***/stats/view/worker.go:34 +0x68

goroutine 20 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x3c65220)
        ***@***.***/klog.go:1018 +0x8b
created by k8s.io/klog.init.0
        ***@***.***/klog.go:404 +0x6c

goroutine 22 [syscall, 5 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 49 [chan receive, 5 minutes]:
main.makeShutdownCh.func1(0xc00005ef60, 0xc00005c420)
        /home/circleci/project/project/commands.go:422 +0x34
created by main.makeShutdownCh
        /home/circleci/project/project/commands.go:420 +0xf2




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.377928758.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.377928758.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
***@***.***:~/OCI/terraform/stage$



Want private search? duckduckgo  or www.qwant.com
 

    On Monday, December 6, 2021, 08:33:40 PM GMT, James Bardin ***@***.***> wrote:  
 
 


Closed #30090.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jbardin** [comment] 2021-12-07 20:45
Sorry, since there was only error output shown I thought you meant the panic was no longer present.
Can you show what in the referenced file is causing this panic?

**Comment by PLJumpstart** [comment] 2021-12-07 21:29
Hi James
When I delete a file called tf-stage.tf  (quite large relatively) it all started to work again.
So I am carrying on now.
Sorry - I don't know what the issue was.
paul

Want private search? duckduckgo  or www.qwant.com
 

    On Tuesday, December 7, 2021, 08:45:55 PM GMT, James Bardin ***@***.***> wrote:  
 
 


Sorry, since there was only error output shown I thought you meant the panic was no longer present.
Can you show what in the referenced file is causing this panic?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jbardin** [comment] 2021-12-07 21:32
Thanks for following up. I'll close the issue then, but if you do find the reason, feel free to update here and we can evaluate.

**Closed by jbardin** 2021-12-07 21:32 UTC
Labels: bug, crash

**Comment by PLJumpstart** [comment] 2021-12-07 21:34
OK npand thank you for taking the time to look into this
paul

Want private search? duckduckgo  or www.qwant.com
 

    On Tuesday, December 7, 2021, 09:32:30 PM GMT, James Bardin ***@***.***> wrote:  
 
 


Thanks for following up. I'll close the issue then, but if you do find the reason, feel free to update here and we can evaluate.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
