### ISSUE TITLE
DigitalOcean provisioning is unusable

### ISSUE THREAD

**Issue by fernandobixly** [hashicorp/terraform#4455] opened 2015-12-29 01:21 UTC
Currently, provisioning with DigitalOcean is extremely unreliable. While trying to perform any action on DigitalOcean, API calls will fail spuriously with the following error:

Error retrieving droplet: Get https://api.digitalocean.com/v2/droplets/<id>: net/http: TLS handshake timeout

Errors occur unpredictably on any of the API endpoints, to the point that a terraform apply run creating three droplets does not succeed, thus making the provider unusable.

I have tested with parallelism=1, and the problem persists.

**Comment by adamhub** [comment] 2015-12-29 01:30
Same problem here. Thanks for a great project thought!

**Comment by simonmorley** [comment] 2016-01-07 16:49
+1

**Comment by phillbaker** [comment] 2016-01-08 18:20
On the DigitalOcean side, we're aware of the issue and have tracked it down to what looks like a cause (over aggressive filtering of requests). I'll leave an update here when we've confirmed a fix.

**Comment by phillbaker** [comment] 2016-01-11 21:42
We think we've resolved this - @adamhub @simonmorley still having issues?

**Comment by adamhub** [comment] 2016-01-11 22:01
@phillbaker We had to move on to another platform, sorry. No more time to test this issue.

**Comment by simonmorley** [comment] 2016-01-11 22:43
We were actually having this issue directly on London DO servers and have moved all to the NY ones. Will try again when I have a mo

**Comment by phillbaker** [comment] 2016-01-16 16:48
@simonmorley did you have a chance to check out this issue again?

**Comment by simonmorley** [comment] 2016-01-16 16:49
Actually I just tried and got a whole new error from DO.

Could not even SSH to the server after approx. 1 min. Created one in NY, no
problems.

Emailed DO, their response... No issues their side, must be client
configuration...



Simon Morley

Big Chief | PolkaSpots Supafly Wi-Fi
Bigger Chief | Cucumber Tony

simon@PolkaSpots.com
Linkedin: I'm on it again and it still sucks
020 7183 1471

🚀💥

**Comment by bryanl** [comment] 2016-04-30 13:59
Hello, I'm curious if this is still the case? A few months back, we submitted a change to replace the hashicorp built DigitalOcean client with a DigitalOcean maintained version. Throughout multiple projects, I provision hundreds of Droplets at week with Terraform with great success.

**Comment by fernandobixly** [comment] 2016-05-02 18:20
We have not tested this at all since moving to Kubernetes on GCE. We no longer have the setup to test this.

**Comment by troyswanson** [comment] 2016-06-02 16:05
I've been testing Terraform with DigitalOcean and it's been working extremely well. I have been able to create SSH key and Droplet resources, as well as use the `file` and `remote-exec` provisioners.

I haven't tried using Floating IPs yet, however.

**Comment by stack72** [comment] 2016-07-14 17:42
Hi all

Checking in here to try and work out if this is still an issue for anyone? We currently have a nightly test suite running for Terraform that creates/  updates and destroys DO droplets and we don't get any issues

Anyone still seeing this issue?

Paul

**Comment by goloroden** [comment] 2016-07-20 19:31
I do not exactly get this error, but DO provisioning is extremely unreliable for me, too.

When creating droplets, ~50% of the times Terraform does not recognize a fully started and available droplet as started and available and keeps on waiting … until you abort the process by pressing `<Ctrl>+<C>` twice (the first time it says that it is trying to shutdown gracefully which only leads to more waiting).

If you then rerun `plan` and / or `apply`, Terraform creates another droplet.

When you later `destroy` everything, the initially created droplet is not being destroyed, probably because Terraform never added it to its internal state.

So, to cut a long story short: No, DO provisioning is still not reliable.

**Comment by jamesjuran2** [comment] 2016-11-22 21:44
I've been using Terraform with DO pretty extensively for the past four weeks and have not had any stability problems like this. @goloroden are you still having this issue with 0.7.10 or later?

**Comment by goloroden** [comment] 2016-11-23 05:35
Unfortunately, I can't tell.

Due to the stability issues (we also had some other problems with stability at DO) we switched to AWS which really runs smoothly.

Maybe I'll give it a try at a later point in time again.

**Comment by stack72** [comment] 2016-11-23 06:17
Thanks for coming back to us on this one - as we can't recreate this, I'm going to close it for now

Any issues, please recomment

Thanks

Paul

**Closed by stack72** 2016-11-23 06:17 UTC
Labels: bug, provider/digitalocean, waiting-response

**Comment by dave-lew99** [comment] 2018-11-14 12:59
We're having similar issues with DO and Terraform (also, packer to a lesser extent). API calls frequently time out or return error responses - these aren't handled very well (should terraform retry an API call?). It seems that DO, in FRA at least, is pretty unstable.

**Comment by vesper8** [comment] 2019-04-14 17:10
wow.. issue first brought up 4 years ago.. still happening to me now.. constant TLS handshake timeout.. GJ DigitalOcean
