### ISSUE TITLE
Terraform help message when Strings are not in double-quotes.

### ISSUE THREAD

**Issue by theguyoverthere** [hashicorp/terraform#18260] opened 2018-06-15 11:38 UTC
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.23.0
```

### Terraform Configuration Files

```
#terraform.tfvars:
ami           = 'ami-f5ea9f8a'
instance_type = 't2.micro'
key_name      = 'demo'
```

### Debug Output
[Debug Output](https://gist.github.com/theguyoverthere/b967f04b6cfdb079f8db6cb40b1bde69)

### Expected Behavior
Enhancement Request: Running `terraform validate` should produce an error stating that Strings in Terraform.tfvars could not be parsed properly because they're not in double quotes.

### Actual Behavior
The default `terraform validate help` message is returned.
```
Usage: terraform validate [options] [dir]

  Validate the terraform files in a directory. Validation includes a
  basic check of syntax as well as checking that all variables declared
  in the configuration are specified in one of the possible ways:

      -var foo=...
      -var-file=foo.vars
      TF_VAR_foo environment variable
      terraform.tfvars
      default value

  If dir is not specified, then the current directory will be used.

Options:

  -check-variables=true If set to true (default), the command will check
                        whether all required variables have been specified.

  -no-color             If specified, output won't contain any color.

  -var 'foo=bar'        Set a variable in the Terraform configuration. This
                        flag can be set multiple times.

  -var-file=foo         Set variables in the Terraform configuration from
                        a file. If "terraform.tfvars" is present, it will be
                        automatically loaded if this flag is not specified.
```

### Steps to Reproduce

1. Create  variables in terraform.tfvars with single quotes instead of double quotes.
2. `terraform init`
3. `terraform validate`

**Comment by apparentlymart** [comment] 2018-10-31 19:17
Hi @theguyoverthere!

The problem with `tfvars` syntax errors not being reported properly has been fixed in master ready for inclusion in the forthcoming v0.12.0 release, so this will at least produce a real error after that.

However, we don't yet have a special case for single quotes, and I agree that it would be good polish to have the parser detect that and return a special error about it that mentions specifically that strings must be in double quotes in this language.

```
$ terraform apply

Error: Invalid expression

  on terraform.tfvars line 2:
   2: ami           = 'ami-f5ea9f8a'

Expected the start of an expression, but found an invalid expression token.
```

The opening `'` is underlined when rendered in a terminal to indicate which token is problematic, but it would be better to have the paragraph underneath talk specifically about quoted strings.

We probably won't get to this in time for the v0.12.0 final release because there's lots of other work to be done before that, but I'll leave this open here to remind us to polish this up in a later release. Thanks for opening this, and sorry for the slow response.

**Comment by theguyoverthere** [comment] 2018-11-09 15:43
I'm glad this was taken up. Thanks!

**Comment by mildwonkey** [comment] 2020-08-27 16:21
I can confirm that this has been fixed (at some point 😁 ):

```

Error: Invalid character

  on terraform.tfvars line 1:
   1: ami           = 'ami-f5ea9f8a'

Single quotes are not valid. Use double quotes (") to enclose strings.
```

**Closed by mildwonkey** 2020-08-27 16:21 UTC
Labels: cli, config

**Comment by theguyoverthere** [comment] 2020-08-30 08:28
Cheers!  😄
