### ISSUE TITLE
Avoidable: “ "for_each" depends on resource attributes that cannot be determined until apply ”

### ISSUE THREAD

**Issue by gui-don** [hashicorp/terraform#29957] opened 2021-11-16 23:29 UTC
Hello 👋

### Terraform Version

1.0.10

### Actual Behavior

Here is the situation, with a working code and not working code at the same place:

```
###
# MODULE CALL
###

resource "random_string" "this" {
  length  = 8
  upper   = false
  special = false
}

#
# Raise a:
# The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the for_each depends on.
#
# I know why: because the key depends on the random_string resource
module "failing" {
  source = "../../"

  test = {
    "${random_string.this.result}.example.org" = {
      comment      = "${random_string.this.result}.example.org zone"
    }
  }
}

module "working" {
  source = "../../"

  test = {
    "static.example.org" = {
      comment      = "${random_string.this.result}.example.org zone"
    }
  }
}

###
# MODULE 
###

variable "test" {
  type = map(object({
    comment = string
  }))
}

resource "aws_route53_zone" "test" {
  for_each = var.test

  name    = each.key
  comment = each.value.comment
}
```

### Expected Behavior

I believe the situation above is avoidable.
In the expression `"${random_string.this.result}.example.org"`:

 - `.example.org` is a guaranted non-empty string…
 -  …concatenated with `random_string.this.result`, a guaranted - maybe empty - string.

Then I don't see any situation where the entire `map` number of elements couldn't be pre-processed by Terraform. Maybe I'm missing something or maybe there is a work around to this situation (if there is, please update the documentation!).

I'd like to mention the usage of `-target` is problematic in many cases (if I remember correctly, people at Hashicorp wrote a blog article on that subject) and that I believe fixing this error when possible would be a huge improvement for automation, to avoid the dirty workaround like asking the users of Terraform modules the number of elements that their list arguments contain… You know, that workaround:

```
variable "my_list" {
  description = "Your list of things"
}

variable "my_list_count" {
  description = "How many things your list contain. You as a human can infer that number, but sometimes Terraform cannot ;)"
}
```

Many thanks for your help.

**Comment by apparentlymart** [comment] 2021-11-17 01:11
Hi @gui-don! Thanks for reporting this.

For `for_each` in particular, there are two things Terraform needs to know: the number of elements in the map, _and_ the exact keys of the map elements, because the resource instances will each be identified by a map key.

So with that said, while I agree with you that in principle Terraform could determine that the map will have one element, it doesn't seem to have enough information to determine what the key of that element would be, and thus to determine what the instance key of that single instance would be. Therefore Terraform is working as intended, in this case.

(I expect this ends up getting reported as a problem of map _length_ because Terraform represents any map constructed with unknown keys as a wholly-unknown map, as a way to deal with the fact that there would be no way to enumerate its actual keys in that case. But that's an implementation detail of the general problem that we need to know exactly what all of the instance keys will be in order to record the action for each instance in the plan.)

Since the example you've given here seems to be contrived just to show the situation, I'm not sure what other approach to suggest. If you can share a real example using actual resource types in a realistic scenario then it would be easier to understand what problem you are intending to solve here, and thus determine whether there's an existing answer with today's Terraform or if you are describing a new use-case that this issue could represent.

**Comment by gui-don** [comment] 2021-11-17 05:18
Thanks for your answer! I understand it’s not a bug per se, however I would like to maybe spark a discussion on why it's a painful "feature".

### First, why do I need `for_each` instead of `count`

Using `count` leads to unwanted destroys in case of refactoring. Let's say I have three zones:
- zoneA.example.org (index 0)
- zoneB.example.org (index 1)
- zoneC.example.org (index 2)

If I want to get rid of `zoneB.example.org`, Terraform will try to destroy the third zone: `zoneC.example.org`, to change its index to 1 in the statefile. As domain names are critical for services, it leads to downtime.
As you know, using `for_each` solves that problem by using string indexes instead of integers.

I want to add it’s not only a problem for domain name but many other resources, leading me to the conclusion `for_each`es are preferred over `counts` most of the time, as long as the index names are smart.


### Why do I need dynamic keys for `for_each`es

I see two use cases:

1. In a CI/CD context (see the example above with the `random` resource), adding a random parts to the name allow some resilience to parallel testing. Resources sometimes needs to be unique (like domain names), thus, static names leads to "duplicated" resources failures. Randomizing names is not a bulletproof solution, but it works well enough. I don't see a viable alternative.

2. I may want to use the result of another resource as a sub zone, for instance in AWS, using the region name: `us1.example.org`. One can argue that I can simply write it as is, but it’s duplication. In my region example, I already specified the region in my provider. Duplication is evil: people forget the places they need to change things, it begets bugs and convoluted code.

### Why I think Terraform lexer/parser/pre-processor should improve

There are many legitimate cases where Terraform cannot know for sure how many elements are contained in a map or a list. I just want to clarify I'm not pointing these cases.

However, the example I give makes Terraform module writing really painful. It forces developers to use tricks - like the `my_list_count` example I gave and above all: **it forces to duplicate the code**:
- `my_list_count` itself is a form of duplication, because the module user needs to write the same information twice: the list and the count of the list (which is funny for a human, because it seems weird to have to write: "this 2 element list really have **2** elements").
- Sometimes, developers simply duplicate resources names and IDs to avoid the dire Terraform "cannot process count".

I guess I'm far from the only one seeing that issue, so that would mean either 1. Terraform has a very good reason to behave like this that I ignore. or 2. It is very hard to refactor the pre-processor to make it handle these cases.

Is there already some discussions on the matter?

**Comment by apparentlymart** [comment] 2021-11-17 17:31
Hi @gui-don,

I think the main problem here isn't imagining what it would be like to not have this constraint but rather to think though _concretely_ how we might achieve that. It's a fundamental assumption today that resource instances have wholly-known, stable identifiers that Terraform can use to track them. If I knew an answer to that then I would certainly investigate it, but I don't personally have any design ideas on how to address it.

The key requirement we need to meet is that we must always be able to correlate resource instances declared in the configuration with resource instances already recorded in the state. Today we achieve that by requiring that resource instances have wholly-known, stable identifiers throughout the workflow. If we allowed the identifiers from configuration to be partially unknown we would need to devise some other strategy for deciding whether the not-fully-known identifier in the configuration correlates with an existing identifier recorded in the state, not just for initial creation (the easy case) but also for ongoing updates over time.

For today our recommendation is to generally treat instance keys in a similar way as resource names: they are an identifier unique to this particular module instance, and only need to be unique within that module instance's namespace. Sometimes it's convenient to use identifiers from the remote system itself as instance keys, but that isn't always practical, as is true for your example here where you want to use the externally-visible DNS name as the identifier even though you have the conflicting requirement to decide that DNS name dynamically.

If you instead separate the idea of the local name the Terraform module calls it from what the remote system (DNS broadly, in this case) calls it, the Terraform-local identifier can potentially remain stable as the remote system identifier changes, creating the continuity necessary to update an object in-place over time.

If you have a concrete idea for how exactly Terraform could handle correlating state instances with configuration instances without actually knowing the configuration instance address then I'd love to discuss that further. Otherwise, we can just let this issue represent the use-case of dynamically-chosen instance addresses in the hope that someone will later devise a design to solve it.

**Comment by gui-don** [comment] 2021-11-17 18:38
```
For today our recommendation is to generally treat instance keys in a similar way as resource names
```

That makes a lot of sense.

I feel like the error:
```
"for_each" depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created.
```
could be more accurate. The issue is clear now but I feel I was misdirected by this error: I initially thought the number of element couldn't be processed whereas the issue is that `for_each` map keys must be wholly-known, stable identifiers.

---

*caveat: I do not know Terraform inner workings much, so I will likely say uneducated things here.*

To allow dynamic resources names, I guess we should change the "*when*" Terraform correlates state and configuration, from "compile time" to "runtime". Something like this:

1. Read identifiers in the statefile
2. Parse the HCL code to gather identifiers. 3 possible cases here:
    1. identifier is stable, well-known. We can correlate state and configuration.
    2. identifier is dynamic, but depends on an already known resource attribute. We can correlate state and configuration.
    3. identifier is dynamic and depends on an unknown resource attribute. We cannot correlate, so we need a strategy: why not hash the `for_each` content (the static and dynamic part) to store a *temporary* in memory.
 3. *Here is the algorithm for Terraform to determine resources dependencies*
 4. Apply
 5. Replace temporary `hashes` in memory with the now well-known resource attributes

Would that make any sense?

**Comment by jbardin** [comment] 2021-11-19 14:23
Filling in some details to give an idea of the complexity involved:

- 2.ii.: Resource attributes are not guaranteed to be uniquely identifying, so there is no way to correlate them without a stable identifier.
- 2.iii.: Hashing `<unknown>-static` and <unknown>-static` is not going to make the two values differentiable until the `<unknown>` portion is known.

Taking the next logical step returns us to the first last bullet here, where attributes are not guaranteed to be unique, and in many cases any unique values are likely also unknown, otherwise they could be used as `for_each` keys (in other words, if you have known, unique values to work with, why not use those as the `for_each` keys?).

Allowing unknown values for individual resource addresses also has the problem of how to deal with conflicts once the value is known. During the apply process, what do you do when you realize you have created conflict in instance addresses? Was that conflict supposed to update a previously stored resource which you already delete? Do you have multiple instances of what should be one instance, or do you have multiple individual instances which should not have the same address? Do you fail and try to undo what was applied. What do you do with the ambiguous references within the configuration?

Being able to plan all individual resources, and guarantee that only what is planned will be applied is fundamental to the operation of Terraform as it was envisioned. While a tool could be probably devised that answers the above questions, it would be very different from Terraform as it currently exists.

While it's still a good idea to ponder future ideas, I think in this case it may be more productive to work from the existing constraints, and figure out why your configuration can't be made to satisfy those constraints, and how the tooling can help assist you to a working configuration.

**Comment by gui-don** [comment] 2021-11-19 17:03
Many thanks for your all your answers. I appreciate you took the time to make in-depth explanations.

**Closed** 2021-11-19 17:03 UTC
Labels: bug, new

**Comment by apparentlymart** [comment] 2021-11-19 17:07
The current error message about `for_each` is honestly just a minor evolution of a pre-existing one for `count` and I think this language about "how many" just carried over from that other message.

I do agree that we could potentially be clearer in the error message about what Terraform actually needs here, though we do need to be careful not to go too far into the implementation detail weeds if what we're describing doesn't actually help the typical reader find a resolution. (By "find a resolution" I mean to find a different way to write their configuration to work with Terraform today, rather than to ponder new designs for Terraform that might have different constraints.)

For my part I'll look out to see if similar questions arise again that might be attributable to that error message. So far I think you're the only person who has thought deeply enough about what the message is stating to formulate a potential feature request based on it, so honestly I think we probably wouldn't prioritize spending time considering a more elaborate error message for that case _today_, but if we find this arising many times then we could use the various examples to try to decide what sort of extra nuance the error message could benefit from to get the point across succinctly, without extraneous detail.

Thanks again for raising this!

**Comment by shaunc** [comment] 2021-11-30 15:55
1. I thnk the error message is a bug -- I filed [this](https://github.com/hashicorp/terraform/issues/30039) because in one case `count` works while `for_each` doesn't. An error message that says something like `for_each requires keys that can be used as identifiers at planning time` might be better.

2. One resolution would be to actually support the solution suggested by the error message: use target. Currently this doesn't seem to work if the values are derived from a `data` element, say. Perhaps there could be some way of writing a map into state: `apply -target foo.bah.local.some_map` such that its value could be used for planning. (Maybe declaring as "local_state" rather than a regular local would be more transparent.)

3. Perhaps there could be an option to apply (`--iterative`?) that would iteratively generate partial plans, then continue after application, when necessary intermediates could be calculated.
