### ISSUE TITLE
Using Keystone v3 token with openstack provider returns error requiring password

### ISSUE THREAD

**Issue by delias-** [hashicorp/terraform#6458] opened 2016-05-03 16:40 UTC
Attempting to use openstack provider with "token" to create an instance returns the following error:

```
Error refreshing state: 1 error(s) occurred:

* You must provide a password to authenticate
```

### Terraform Version
terraform -v
Terraform v0.6.15

### OS Version
CentOS 6.6, 2.6.32-504.30.3.el6.x86_64

### Affected Resource(s)
Please list the resources as a list, for example:
- terraform-provider-openstack

### Debug Output
https://gist.github.com/delias-/4c945e7aa97c63cd80d28b270783b391

### Expected Behavior
A plan should be generated.

### Actual Behavior
Terraform outputs an error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1 . Use a tf file like this example:
```
[myUser@myHost ~]$ cat example.tf

provider "openstack" {
  auth_url = "https://devcloud.mycorp.com:5000/v3"
  domain_name = "development"
  tenant_name = "dev2"
  token = "<X-Subject-Token Here generated out of band from keystone api>"
}

resource "openstack_compute_instance_v2" "myUniqInstance" {
  region = "dev"
  name = "myUniqInstance"
  image_name = "centos6-latest"
  flavor_name = "dev.tiny"
  network = { name = "dev-internal-net" }
}
```
2 . `terraform plan`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/terraform/issues/5802

**Comment by jtopjian** [comment] 2016-05-04 04:31
@delias- Thank you for opening this issue and including a lot of great information to work with! 

I've made a slight edit to the title to mention that this seems to be a Keystone v3 issue.

**Comment by jtopjian** [comment] 2016-05-14 00:32
I believe I've found the root cause: https://github.com/rackspace/gophercloud/pull/574

Once that's merged in, I'll be able to re-evaluate with Terraform.

**Closed** 2016-06-27 04:53 UTC
Labels: bug, provider/openstack
