### ISSUE TITLE
Indexed module not detected during `terraform apply`

### ISSUE THREAD

**Issue by kappmeier** [hashicorp/terraform#24951] opened 2020-05-14 10:02 UTC
### Terraform Version
```
Terraform v0.12.25
+ provider.azurerm v1.40.0
```
Also Terraform `v0.12.20` fails.

#### Main Terraform configuration

Required Terraform configuration to produce the issue:
```hcl
# A module is required. Module definition below.
module "managed_disk" {
  source = "./module"

  resource_group = azurerm_resource_group.main
}

variable "prefix" {
  description = "Prefix for resources"
}

resource "azurerm_resource_group" "main" {
  name     = "RG-${var.prefix}"
  location = "West Europe"
}

resource "azurerm_virtual_network" "main" {
  name                = "${var.prefix}-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_subnet" "internal" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "main" {
  name                = "${var.prefix}-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = azurerm_subnet.internal.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_virtual_machine" "main" {
... # See https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html
}

resource "azurerm_virtual_machine_data_disk_attachment" "map_disk" {
  managed_disk_id    = module.managed_disk[0].id
  virtual_machine_id = azurerm_virtual_machine.main.id
  lun                = "0"
  caching            = "ReadWrite"
}
```

#### Module
```hcl
output "id" {
  description = "Managed disk ids"
  value = azurerm_managed_disk.managed_disk[*].id
}

variable "resource_group" {
  description = "Resource group "
  type = object({
    location = string
    name     = string
  })
}

resource "azurerm_managed_disk" "managed_disk" {
  count = 1

  name                 = "test-managed-disk-${count.index}"
  location             = var.resource_group.location
  resource_group_name  = var.resource_group.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 64
  zones                = [1]
}
```

### Debug Output
https://gist.github.com/kappmeier/d9df8c12558356b80690f371ab32607d

### Expected Behavior
Error during apply that it is not possible to reference and deployment doesn't start. Some error messages along the lines of the following made up snippet:
```bash
$ terraform apply
var.prefix
  Prefix for resources

  Enter a value: kappmeier


Error: Invalid index

  on main.tf line 78, in resource "azurerm_virtual_machine_data_disk_attachment" "map_disk":
  78:   managed_disk_id    = module.managed_disk[0].id
    |----------------
    | module.managed_disk is not indexable (or similar)

It is not possible to access a collection value.
```

### Actual Behavior
Deployment starts and fails with the nice hint to report a bug.
```bash
$ terraform apply
var.prefix
  Prefix for resources

  Enter a value: kappmeier

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_network_interface.nic will be created
  + resource "azurerm_network_interface" "nic" {
...
    }

  # azurerm_resource_group.main will be created
  + resource "azurerm_resource_group" "main" {
...
    }

  # azurerm_subnet.internal will be created
  + resource "azurerm_subnet" "internal" {
...
    }

  # azurerm_virtual_machine.main will be created
  + resource "azurerm_virtual_machine" "main" {
...
    }

  # azurerm_virtual_machine_data_disk_attachment.map_disk will be created
  + resource "azurerm_virtual_machine_data_disk_attachment" "map_disk" {
...
    }

  # azurerm_virtual_network.network will be created
  + resource "azurerm_virtual_network" "network" {
...
    }

  # module.managed_disk.azurerm_managed_disk.managed_disk[0] will be created
  + resource "azurerm_managed_disk" "managed_disk" {
...
    }

Plan: 7 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_resource_group.main: Creating...
azurerm_resource_group.main: Creation complete after 1s [id=/????????-????-????-????-????????????/resourceGroups/RG-kappmeier]
azurerm_virtual_network.network: Creating...
module.managed_disk.azurerm_managed_disk.managed_disk[0]: Creating...
module.managed_disk.azurerm_managed_disk.managed_disk[0]: Creation complete after 1s [id=/subscriptions/????????-????-????-????-????????????/resourceGroups/RG-kappmeier/providers/Microsoft.Compute/disks/test-managed-disk-0]
azurerm_virtual_network.network: Creation complete after 12s [id=/subscriptions/????????-????-????-????-????????????/resourceGroups/RG-kappmeier/providers/Microsoft.Network/virtualNetworks/kappmeier-network]
azurerm_subnet.internal: Creating...
azurerm_subnet.internal: Creation complete after 1s [id=/subscriptions/????????-????-????-????-????????????/resourceGroups/RG-kappmeier/providers/Microsoft.Network/virtualNetworks/kappmeier-network/subnets/internal]
azurerm_network_interface.nic: Creating...
azurerm_network_interface.nic: Creation complete after 1s [id=/subscriptions/????????-????-????-????-????????????/resourceGroups/RG-kappmeier/providers/Microsoft.Network/networkInterfaces/kappmeier-nic]
azurerm_virtual_machine.main: Creating...
azurerm_virtual_machine.main: Creation complete after 1m44s [id=/subscriptions/????????-????-????-????-????????????/resourceGroups/RG-kappmeier/providers/Microsoft.Compute/virtualMachines/kappmeier-main]
azurerm_virtual_machine_data_disk_attachment.map_disk: Creating...

Error: configuration for azurerm_virtual_machine_data_disk_attachment.map_disk still contains unknown values during apply (this is a bug in Terraform; please report it!)
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by danieldreier** [comment] 2020-05-18 23:00
Hi! Thanks for reporting this. I think this is probably a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. When tried to run the provided code, I hit a validation error, which makes me think that this is not quite what you're seeing the issue with:
```
Error: Unsupported argument

  on 24951.tf line 5, in module "managed_disk":
   5:   resource_group = azurerm_resource_group.main

An argument named "resource_group" is not expected here.
``` 

I put the reproduction case for this in a [github repo](https://github.com/danieldreier/terraform-issue-reproductions/tree/master/24951). Can you please make a PR that gets it to the state where I can run this and reproduce the issue you're seeing?

**Comment by kappmeier** [comment] 2020-05-20 22:48
I have created a PR, it should reproduce the issue now. I have also updated the description accordingly. If anything else fails, please let me know.

Sorry for the inconvenience.

**Comment by danieldreier** [comment] 2020-06-05 01:13
hey, I'm sorry for how long this took to respond to. I've confirmed that your PR fixed the syntax, and just discovered that I no longer have a valid azure subscription for testing these issues! I am getting that fixed and then will come back to this.

**Comment by crw** [comment] 2024-08-28 17:02
I am going to close this issue as it is likely no longer valid due to age. I could not find the mentioned PR. Please open a new issue if this is still a problem. Thanks very much!

**Closed by crw** 2024-08-28 17:02 UTC
Labels: bug, provider/azurerm
