### ISSUE TITLE
AWS Instance Data Resource failing via JSON syntax

### ISSUE THREAD

**Issue by dgarstang** [hashicorp/terraform#15647] opened 2017-07-27 16:05 UTC
Trying to use a data source in JSON format. 

See https://github.com/hashicorp/terraform/issues/13037. I've tried to approximate my code based around that solution, but I'm receiving a ""data" must be followed by a name" error.

```
{
   "data": [
      {
         "aws_ami": [
            {
               "image_id": {
                  "filter": {
                     "name": "name",
                     "values": [
                        "widgetcorp-base-centos7-67"
                     ]
                  },
                  "most_recet": true,
                  "owners": [
                     "0"
                  ]
               }
            }
         ],
         "aws_iam_policy_document": [
            {
               "artifact_store": {
                  "statement": {
                     "actions": [
                        "s3:GetObject",
                        "s3:ListBucket"
                     ],
                     "effect": "Allow",
                     "resources": [
                        "arn:aws:s3:::foo-artifacts-store",
                        "arn:aws:s3:::foo-artifacts-store/*"
                     ],
                     "sid": "Stmt1495472332000"
                  }
               },
               "assume_role": {
                  "statement": {
                     "actions": [
                        "sts:AssumeRole"
                     ],
                     "principals": {
                        "identifiers": [
                           "ec2.amazonaws.com"
                        ],
                        "type": "service"
                     },
                     "sid": ""
                  }
               }
            }
         ]
      }
   ],
   "provider": {
      "aws": {
         "region": "eu-central-1"
      }
   },
   "terraform": {
      "backend": {
         "s3": {
            "bucket": "foo-tfstate",
            "key": "usprod/1/widgetcorp-alpha.tfstate",
            "region": "us-west-1"
         }
      }
   }
}
```

Error:
```
Error loading files Error loading /Users/douglasgarstang/git/terraform/terraform-alpha/main.tf: -: "data" must be followed by a name
```

**Comment by dgarstang** [comment] 2017-07-27 20:15
So, does this basically mean that the data type is unusable in JSON format?

**Comment by apparentlymart** [comment] 2017-07-27 22:29
Hi @dgarstang,

I've not had a chance to repro this yet; since you already saw and tried the sort of transform I suggested in #13037, it does feel like something weird is going on here. AFAICR we haven't significantly changed the relevant configuration parsing code since I posted that comment in March, but indeed I don't see any significant difference between what you shared here and what I shared in that other comment, so at first glance it looks like there may have been some sort of regression here, which we'll look into in more detail soon.

**Comment by dgarstang** [comment] 2017-07-27 23:25
Thanks for looking at this. Found a fix. The statement {} entries need to be replaced with statement [{}] entries, as I guess there could be multiple statements in a policy doc.

**Comment by apparentlymart** [comment] 2017-07-28 19:20
Thanks for following up, @dgarstang. Really weird that changing the presentation of the `statement` blocks would affect the parsing of the top-level `data` block!

Making the JSON config parser behave more consistently, and settling on a specific required structure, are definitely big goals for the configuration language improvements we're currently starting to flesh out. It's still early, but currently we've been leaning towards making the required structure more restrictive (at the expense of some compatibility) to remove ambiguity and thus allow us to document the required structure more precisely and allow the parser to produce better feedback when it's unable to interpret the structure. We'll share more details on this once things are more concrete.

I'm glad you found a way to write it in the mean time. Sorry again for the weirdness here.

**Comment by apparentlymart** [comment] 2018-10-27 01:52
Hi @dgarstang!

This is also the same root cause as #13911, which is now fixed in `master` in preparation for the forthcoming v0.12.0 release. Thanks for reporting this, and sorry for the slow response.

**Closed by apparentlymart** 2018-10-27 01:52 UTC
Labels: bug, config
