### ISSUE TITLE
Resources to manage AWS vpn connections, customer and virtual gateways

### ISSUE THREAD

**Issue by cransom** [hashicorp/terraform#1011] opened 2015-02-19 20:14 UTC
Just a feature request:
We'd like to manage more of the AWS stack in terraform, which includes attaching virtual gateways to our VPC and then also building the required customer gateway and vpn connections to connect to that virtual gateway.

**Comment by EvanKrall** [comment] 2015-03-12 03:05
Duplicate of #551?

**Comment by mitchellh** [comment] 2015-04-30 03:22
Fixed by #1746, at least for customer gateways

**Comment by radeksimko** [comment] 2015-09-16 22:12
Since all mentioned resources have been already implemented

 - `aws_customer_gateway`
 - `aws_vpn_connection`
 - `aws_vpn_connection_route`
 - `aws_vpn_gateway`

I'm closing this issue. Reopen if you think something VPN-related is missing, or better, open a new issue with more specific description of what exactly is missing. :wink:

**Closed by radeksimko** 2015-09-16 22:12 UTC
Labels: enhancement, provider/aws
