### ISSUE TITLE
Error when increasing the result_count of random_shuffle

### ISSUE THREAD

**Issue by mouglou** [hashicorp/terraform#25067] opened 2020-05-28 22:06 UTC
### Terraform Version
v0.12.24

### Terraform Configuration Files
```hcl
data "google_compute_zones" "available" {
}
variable "cluster_size" {
  description = "The size of the cassandra cluster (number of VMs)"
  type = number
  default = 3
}
resource "random_shuffle" "gce_zones" {
  input             = data.google_compute_zones.available.names
  result_count = var.cluster_size
}
resource "google_compute_disk" "cassandra" {
  count  = var.cluster_size
  name   = "node-00${count.index + 1}"
  type   = "pd-ssd"
  size   = "200"
  zone   = random_shuffle.gce_zones.result[count.index]
  image  = "https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20200403"
  labels = {
    deployer = "terraform"
  }
}
```
### Crash Output
```
 Error: Invalid index
   on .terraform/modules/gce_cassandra_lunashared_dsm_luna2-core_live/main.tf line 11, in resource "google_compute_disk" "cassandra":
   11:   zone   = random_shuffle.gce_zones.result[count.index]
     |----------------
     | count.index is 3
     | random_shuffle.gce_zones.result is list of string with 3 elements
 The given key does not identify an element in this collection value.
 Error: Invalid index
   on .terraform/modules/gce_cassandra_lunashared_dsm_luna2-core_live/main.tf line 11, in resource "google_compute_disk" "cassandra":
   11:   zone   = random_shuffle.gce_zones.result[count.index]
     |----------------
     | count.index is 4
     | random_shuffle.gce_zones.result is list of string with 3 elements
 The given key does not identify an element in this collection value.
```

### Expected Behavior
By increasing the "cluster_size" variable, we expect to create 2 new google_compute_disk.
In the inital setup, we created 3 drive:
node-001
node-002
node-003
Now we change the value for 5 to create node-004 and node-005. These drive are sourced by google_compute_instance later.

### Actual Behavior
After setting the value to 5, when our CI is running the "terraform plan" command, it fail.
It seems that the random_shuffle keep the inital value (3) and didn't recognize the new value.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
Terraform is running within Gitlab CI. The idea is to create a cluster with a specific size, and if more resources are needed, just increase the number of node, always using the random_shuffle to create them in dfferent zones.

**Comment by danieldreier** [comment] 2020-05-29 00:17
Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug, please help by providing more details about an environment I can set up locally to reproduce this failure more. If you can, I may be able get it on our backlog. Specifically, if this is indeed a bug in result_count or in how references are made, I think it should be fairly straightforward for you to work up a reproduction case using `null_resource` so that we can reproduce this without needing to create infrastructure in GCP.

Based on my work so far, I recommend you take this to the community forum for assistance in troubleshooting. I'm going to close this for now, because I think the community forum is the right approach. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you'd rather work up a reproduction case here.

**Closed by danieldreier** 2020-05-29 00:17 UTC
