### ISSUE TITLE
Terraform hangs on any command (0.6.3)

### ISSUE THREAD

**Issue by Deserved** [hashicorp/terraform#3317] opened 2015-09-24 14:26 UTC
Hello,

I am experiencing some hanging issues, and I could not find any answer in this git issue tracker on my problem.

I am running Ubuntu 14.04 LTS (64bit) 
I installed https://dl.bintray.com/mitchellh/terraform/terraform_0.6.3_linux_amd64.zip
My AWS access key and secret key have administrator full access policy.

When I run _terraform plan_ or _terraform refresh_ it just hangs for 20 or more minutes with no response. 

I repeatedly get following 2 lines:

```
2015/09/24 14:49:42 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:42 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
```

Log entries are below:

```
2015/09/24 14:49:07 [INFO] Terraform version: 0.6.3  234f49a2c93fecdecd803d7562e0d394dd12ae42+CHANGES
2015/09/24 14:49:07 Detected home directory from env var: /home/catalin
2015/09/24 14:49:07 [DEBUG] Discovered plugin: atlas = /home/catalin/software/terraform/terraform-provider-atlas
2015/09/24 14:49:07 [DEBUG] Discovered plugin: aws = /home/catalin/software/terraform/terraform-provider-aws
2015/09/24 14:49:07 [DEBUG] Discovered plugin: azure = /home/catalin/software/terraform/terraform-provider-azure
2015/09/24 14:49:07 [DEBUG] Discovered plugin: cloudflare = /home/catalin/software/terraform/terraform-provider-cloudflare
2015/09/24 14:49:07 [DEBUG] Discovered plugin: cloudstack = /home/catalin/software/terraform/terraform-provider-cloudstack
2015/09/24 14:49:07 [DEBUG] Discovered plugin: consul = /home/catalin/software/terraform/terraform-provider-consul
2015/09/24 14:49:07 [DEBUG] Discovered plugin: digitalocean = /home/catalin/software/terraform/terraform-provider-digitalocean
2015/09/24 14:49:07 [DEBUG] Discovered plugin: dme = /home/catalin/software/terraform/terraform-provider-dme
2015/09/24 14:49:07 [DEBUG] Discovered plugin: dnsimple = /home/catalin/software/terraform/terraform-provider-dnsimple
2015/09/24 14:49:07 [DEBUG] Discovered plugin: docker = /home/catalin/software/terraform/terraform-provider-docker
2015/09/24 14:49:07 [DEBUG] Discovered plugin: google = /home/catalin/software/terraform/terraform-provider-google
2015/09/24 14:49:07 [DEBUG] Discovered plugin: heroku = /home/catalin/software/terraform/terraform-provider-heroku
2015/09/24 14:49:07 [DEBUG] Discovered plugin: mailgun = /home/catalin/software/terraform/terraform-provider-mailgun
2015/09/24 14:49:07 [DEBUG] Discovered plugin: null = /home/catalin/software/terraform/terraform-provider-null
2015/09/24 14:49:07 [DEBUG] Discovered plugin: openstack = /home/catalin/software/terraform/terraform-provider-openstack
2015/09/24 14:49:07 [DEBUG] Discovered plugin: template = /home/catalin/software/terraform/terraform-provider-template
2015/09/24 14:49:07 [DEBUG] Discovered plugin: terraform = /home/catalin/software/terraform/terraform-provider-terraform
2015/09/24 14:49:07 [DEBUG] Discovered plugin: chef = /home/catalin/software/terraform/terraform-provisioner-chef
2015/09/24 14:49:07 [DEBUG] Discovered plugin: file = /home/catalin/software/terraform/terraform-provisioner-file
2015/09/24 14:49:07 [DEBUG] Discovered plugin: local-exec = /home/catalin/software/terraform/terraform-provisioner-local-exec
2015/09/24 14:49:07 [DEBUG] Discovered plugin: remote-exec = /home/catalin/software/terraform/terraform-provisioner-remote-exec
2015/09/24 14:49:07 Detected home directory from env var: /home/catalin
2015/09/24 14:49:07 [DEBUG] Attempting to open CLI config file: /home/catalin/.terraformrc
2015/09/24 14:49:07 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2015/09/24 14:49:07 Detected home directory from env var: /home/catalin
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.ConfigTransformer:

aws_instance.example
provider.aws
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.OrphanTransformer:

aws_instance.example
provider.aws
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.AddOutputOrphanTransformer:

aws_instance.example
provider.aws
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.MissingProviderTransformer:

aws_instance.example
provider.aws
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.ProviderTransformer:

aws_instance.example
  provider.aws
provider.aws
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.DisableProviderTransformer:

aws_instance.example
  provider.aws
provider.aws
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.MissingProvisionerTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.ProvisionerTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.VertexTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.FlattenTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.ProxyTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.RootTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.TargetsTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.PruneProviderTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.PruneProvisionerTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.DestroyTransformer:

aws_instance.example
  aws_instance.example (destroy tainted)
  aws_instance.example (destroy)
  provider.aws
aws_instance.example (destroy tainted)
  provider.aws
aws_instance.example (destroy)
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.CreateBeforeDestroyTransformer:

aws_instance.example
  aws_instance.example (destroy tainted)
  aws_instance.example (destroy)
  provider.aws
aws_instance.example (destroy tainted)
  provider.aws
aws_instance.example (destroy)
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.PruneDestroyTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.PruneNoopTransformer:

aws_instance.example
  provider.aws
provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.CloseProviderTransformer:

aws_instance.example
  provider.aws
provider.aws
provider.aws (close)
  aws_instance.example
  provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.CloseProvisionerTransformer:

aws_instance.example
  provider.aws
provider.aws
provider.aws (close)
  aws_instance.example
  provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.RootTransformer:

aws_instance.example
  provider.aws
provider.aws
provider.aws (close)
  aws_instance.example
  provider.aws
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  aws_instance.example
  provider.aws (close)
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [TRACE] Graph after step *terraform.TransitiveReductionTransformer:

aws_instance.example
  provider.aws
provider.aws
provider.aws (close)
  aws_instance.example
provisioner.chef
provisioner.file
provisioner.local-exec
provisioner.remote-exec
root
  provider.aws (close)
  provisioner.chef
  provisioner.file
  provisioner.local-exec
  provisioner.remote-exec
2015/09/24 14:49:07 [INFO] Starting graph walk: walkValidate
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.local-exec: walking
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.local-exec: evaluating
2015/09/24 14:49:07 [DEBUG] root: eval: *terraform.EvalInitProvisioner
2015/09/24 14:49:07 [DEBUG] Starting plugin: /home/catalin/software/terraform/terraform-provisioner-local-exec []string{"/home/catalin/software/terraform/terraform-provisioner-local-exec"}
2015/09/24 14:49:07 [DEBUG] vertex root.provider.aws: walking
2015/09/24 14:49:07 [DEBUG] vertex root.provider.aws: evaluating
2015/09/24 14:49:07 [DEBUG] root: eval: *terraform.EvalSequence
2015/09/24 14:49:07 [DEBUG] root: eval: *terraform.EvalInitProvider
2015/09/24 14:49:07 [DEBUG] Starting plugin: /home/catalin/software/terraform/terraform-provider-aws []string{"/home/catalin/software/terraform/terraform-provider-aws"}
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.chef: walking
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.chef: evaluating
2015/09/24 14:49:07 [DEBUG] root: eval: *terraform.EvalInitProvisioner
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.file: walking
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.file: evaluating
2015/09/24 14:49:07 [DEBUG] root: eval: *terraform.EvalInitProvisioner
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.remote-exec: walking
2015/09/24 14:49:07 [DEBUG] vertex root.provisioner.remote-exec: evaluating
2015/09/24 14:49:07 [DEBUG] root: eval: *terraform.EvalInitProvisioner
2015/09/24 14:49:07 [DEBUG] Waiting for RPC address for: /home/catalin/software/terraform/terraform-provider-aws
2015/09/24 14:49:07 [DEBUG] Waiting for RPC address for: /home/catalin/software/terraform/terraform-provisioner-local-exec
2015/09/24 14:49:08 terraform-provisioner-local-exec: 2015/09/24 14:49:08 Plugin address: unix /tmp/tf-plugin581441487
2015/09/24 14:49:08 [DEBUG] Starting plugin: /home/catalin/software/terraform/terraform-provisioner-chef []string{"/home/catalin/software/terraform/terraform-provisioner-chef"}
2015/09/24 14:49:08 [DEBUG] Waiting for RPC address for: /home/catalin/software/terraform/terraform-provisioner-chef
2015/09/24 14:49:09 terraform-provisioner-chef: 2015/09/24 14:49:09 Plugin address: unix /tmp/tf-plugin577312122
2015/09/24 14:49:09 [DEBUG] Starting plugin: /home/catalin/software/terraform/terraform-provisioner-remote-exec []string{"/home/catalin/software/terraform/terraform-provisioner-remote-exec"}
2015/09/24 14:49:09 [DEBUG] Waiting for RPC address for: /home/catalin/software/terraform/terraform-provisioner-remote-exec
2015/09/24 14:49:09 terraform-provider-aws: 2015/09/24 14:49:09 Plugin address: unix /tmp/tf-plugin831863232
2015/09/24 14:49:09 [DEBUG] root: eval: terraform.EvalNoop
2015/09/24 14:49:09 [DEBUG] root: eval: *terraform.EvalOpFilter
2015/09/24 14:49:09 [DEBUG] root: eval: *terraform.EvalSequence
2015/09/24 14:49:09 [DEBUG] root: eval: *terraform.EvalGetProvider
2015/09/24 14:49:09 [DEBUG] root: eval: *terraform.EvalInterpolate
2015/09/24 14:49:09 [DEBUG] root: eval: *terraform.EvalBuildProviderConfig
2015/09/24 14:49:09 [DEBUG] root: eval: *terraform.EvalValidateProvider
2015/09/24 14:49:10 terraform-provisioner-remote-exec: 2015/09/24 14:49:10 Plugin address: unix /tmp/tf-plugin031736255
2015/09/24 14:49:10 [DEBUG] Starting plugin: /home/catalin/software/terraform/terraform-provisioner-file []string{"/home/catalin/software/terraform/terraform-provisioner-file"}
2015/09/24 14:49:10 [DEBUG] Waiting for RPC address for: /home/catalin/software/terraform/terraform-provisioner-file
2015/09/24 14:49:10 terraform-provisioner-file: 2015/09/24 14:49:10 Plugin address: unix /tmp/tf-plugin247283143
2015/09/24 14:49:10 [DEBUG] vertex root, got dep: provisioner.file
2015/09/24 14:49:10 [DEBUG] vertex root, got dep: provisioner.local-exec
2015/09/24 14:49:10 [DEBUG] vertex root, got dep: provisioner.remote-exec
2015/09/24 14:49:12 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:12 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
2015/09/24 14:49:15 [DEBUG] vertex root, waiting for: provider.aws (close)
2015/09/24 14:49:17 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:17 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
2015/09/24 14:49:20 [DEBUG] vertex root, waiting for: provider.aws (close)
2015/09/24 14:49:22 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:22 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
2015/09/24 14:49:25 [DEBUG] vertex root, waiting for: provider.aws (close)
2015/09/24 14:49:27 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:27 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
2015/09/24 14:49:30 [DEBUG] vertex root, waiting for: provider.aws (close)
2015/09/24 14:49:32 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:32 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
2015/09/24 14:49:35 [DEBUG] vertex root, waiting for: provider.aws (close)
2015/09/24 14:49:37 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:37 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
2015/09/24 14:49:40 [DEBUG] vertex root, waiting for: provider.aws (close)
2015/09/24 14:49:42 [DEBUG] vertex aws_instance.example, waiting for: provider.aws
2015/09/24 14:49:42 [DEBUG] vertex provider.aws (close), waiting for: aws_instance.example
```

**Comment by stack72** [comment] 2015-09-24 14:45
@Deserved what are you trying to get terraform to manage? What does the .tf file look like?

**Comment by Deserved** [comment] 2015-09-24 14:56
I am just trying to see how terrafrom commands work, what output do and etc. basically running sample code from here https://terraform.io/intro/getting-started/build.html  

My *.tf file looks like that:
```
provider "aws" {
  access_key = ""
  secret_key = ""
  region = "eu-west-1"
}

resource "aws_instance" "example" {
  ami = "ami-408c7f28"
  instance_type = "t1.micro"
}
```

**Comment by mnylen** [comment] 2015-09-24 15:34
For me, terraform seems to hang on any command when I forget to export the aws credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) before running terraform. Might this be the same?

**Comment by Deserved** [comment] 2015-09-24 15:52
I am not exporting AWS credentials as env variables, they kept withing .tf

**Comment by apparentlymart** [comment] 2015-09-24 18:49
When the credentials aren't set explicitly Terraform tries to reach out to the EC2 metadata endpoints to get instance credentials, which can cause Terraform to appear to hang if you're not actually running it on an EC2 instance, since the metadata multicast address is (usually) not resolvable outside EC2.

**Comment by Deserved** [comment] 2015-09-24 22:50
Credentials are set explicitly within .tf file:

```
provider "aws" {
  access_key = "<key here>"
  secret_key = "<secret here>"
  region = "eu-west-1"
}
```

And terraform is installed on local machine.

**Comment by Deserved** [comment] 2015-09-24 23:06
Apart port 80 and 22, is there any other ports that terraform uses?

**Comment by nikhilv** [comment] 2015-09-28 06:00
I'm also running into this issue but think it may be related to my internet connection

At home my terraform files were working fine and I could `terraform plan`. 

However, when I tether using my mobile phone terraform hangs and prints the following to stdout when debugging is enabled: ' [DEBUG] vertex root, waiting for: provider.aws (close)'

If I ssh into an ec2 instance and use the same terraform files then I do not get the error

Here is a repro, you'll need to fill in your own subnet id:
https://gist.github.com/nikhilv/3ec35fac10f83b4fb6e8

TO REPRODUCE:
0) Tether via tmobile?
1) Save https://gist.github.com/nikhilv/3ec35fac10f83b4fb6e8 and fill in your EC2 credentials and subnet id.
2) Terraform plan

EXPECTED:
terraform plan returns with result

ACTUAL:
Program hangs indefinitely

**Comment by adaptemy-repo** [comment] 2015-09-28 16:03
In my case, it works at home, but not at work, in latter I have sometime poor connection, is there any time -out setup?

**Comment by wirescrossed** [comment] 2015-09-28 19:24
I am also getting this issue on OS X. It hangs 1 out of 3 times or so on terraform plan.

**Comment by Deserved** [comment] 2015-10-01 12:18
Can it be assigned as bug, or what information should we provide?

**Comment by wirescrossed** [comment] 2015-10-01 14:19
I know this is certainly not a solution however I switched to a Centos workstation built with Vagrant. I will see if I have the same problem on a fresh OS X install soon.

**Comment by catsby** [comment] 2015-10-02 16:08
Hello –

This seems like an internet connectivity issue, or a less likely but possible region specific issue in AWS. 
I'm unable to reproduce these symptoms, and I run dozens of plans/applies daily. I put together an example based off of the one contributed by @nikhilv , you can see it here:

- https://gist.github.com/catsby/2bbcae801f0dc1790cd1

While my example uses `us-west-2`, I get the same behavior with `eu-west-1`.

**Comment by wnkz** [comment] 2015-10-28 17:06
Same issue here :+1:

**Comment by jwadolowski** [comment] 2015-12-03 11:56
It seems that's the same case as described here: https://github.com/hashicorp/terraform/issues/4043#issuecomment-161608689

Could you please test how it works when all the traffic to `169.254.0.0/16` is disabled?

**Comment by apparentlymart** [comment] 2015-12-04 21:07
I encountered an issue with a similar symptom yesterday... it's definitely not the same thing since the details are different, but I wanted to note it here since this issue seems to attract search results for Terraform hanging and other folks might have the same issue as me:

If you have remote state enabled, Terraform will try to refresh the remote state on all of the interesting commands (`get`, `refresh`, `plan` and `apply` at least). My remote state was on a server that requires a VPN tunnel to access, and there was an outage on that VPN tunnel so all of Terraform's request packets were being dropped silently at the gateway, which caused Terraform to hang seemingly-indefinitely.

This hang was much earlier in startup than what others in this issue have described, since the remote state refresh seems to happen before the providers are instantiated.

**Comment by mitchellh** [comment] 2016-12-01 14:14
Going to close this broad issue and request that specific hang cases be submitted as new issues. 

It has been almost a year since the last comment. I don't not believe that there are hanging issues but many mentioned here are probably now invalid so let's just start over as we find them.

**Closed by mitchellh** 2016-12-01 14:14 UTC
Labels: bug, waiting-response
