### ISSUE TITLE
tectonic deployment: etcd vms did not get deployed and unable to access console

### ISSUE THREAD

**Issue by sriramnulu** [hashicorp/terraform#17284] opened 2018-02-06 13:55 UTC
Hi All,

we have installed tectonic on vmware environment by following the below link
https://coreos.com/tectonic/docs/latest/install/vmware/vmware-terraform.html

we did not observe any failures when  "terraform apply ../../platforms/vmware" was run.

In the terraform.tfvar files we metioned 2-masters, 2-workers and 3-etcd hosts. But after deployment we have 1-master and 2-worker nodes. 
Terraform did not deploy etcd vms.

On the deployed master kube-api service is not coming up.
Below is the output:

host@VM1:~# ssh core@controllers.biarcatectonic.com and logged into master node.
when checked the bootkube status in the master node it is in start state but was not coming to Active state. 

Output of the bootkube status in master node:

core@bcluster-master-0 ~ $ systemctl status bootkube
● bootkube.service - Bootstrap a Kubernetes cluster
   Loaded: loaded (/etc/systemd/system/bootkube.service; static; vendor preset: disabled)
   Active: activating (start) since Tue 2018-02-06 12:00:24 UTC; 8min ago
 Main PID: 774 (bash)
    Tasks: 5 (limit: 32768)
   CGroup: /system.slice/bootkube.service
           ├─774 /usr/bin/bash /opt/tectonic/bootkube.sh
           └─787 /run/torcx/bin/docker run --volume /opt/tectonic:/assets --volume /etc/kubernetes:/etc/kubernetes --network=host --entrypoint=/bootkube quay.io/coreos/bootkube:v0.8.1 start --asset

Feb 06 12:07:58 bcluster-master-0 bash[774]: W0206 12:07:58.736157       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:01 bcluster-master-0 bash[774]: W0206 12:08:01.808213       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:08 bcluster-master-0 bash[774]: W0206 12:08:08.720245       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:11 bcluster-master-0 bash[774]: W0206 12:08:11.792106       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:18 bcluster-master-0 bash[774]: W0206 12:08:18.704207       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:21 bcluster-master-0 bash[774]: W0206 12:08:21.776282       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:28 bcluster-master-0 bash[774]: W0206 12:08:28.688069       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:31 bcluster-master-0 bash[774]: W0206 12:08:31.760214       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:38 bcluster-master-0 bash[774]: W0206 12:08:38.736192       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 12:08:41 bcluster-master-0 bash[774]: W0206 12:08:41.808197       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0

Tried restarting the bootkube service but resulted the below error.

bcluster-master-0 core # systemctl status bootkube
● bootkube.service - Bootstrap a Kubernetes cluster
   Loaded: loaded (/etc/systemd/system/bootkube.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-02-06 13:23:40 UTC; 10min ago
  Process: 3471 ExecStart=/usr/bin/bash /opt/tectonic/bootkube.sh (code=exited, status=1/FAILURE)
 Main PID: 3471 (code=exited, status=1/FAILURE)

Feb 06 13:23:37 bcluster-master-0 bash[3471]: W0206 13:23:37.427334       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 13:23:40 bcluster-master-0 bash[3471]: W0206 13:23:40.499254       1 create.go:40] Unable to determine api-server readiness: API Server http status: 0
Feb 06 13:23:40 bcluster-master-0 bash[3471]: E0206 13:23:40.499282       1 create.go:65] API Server is not ready: timed out waiting for the condition
Feb 06 13:23:40 bcluster-master-0 bash[3471]: Error: API Server is not ready: timed out waiting for the condition
Feb 06 13:23:40 bcluster-master-0 bash[3471]: Tearing down temporary bootstrap control plane...
Feb 06 13:23:40 bcluster-master-0 bash[3471]: Error: API Server is not ready: timed out waiting for the condition
Feb 06 13:23:40 bcluster-master-0 bash[3471]: API Server is not ready: timed out waiting for the condition
Feb 06 13:23:40 bcluster-master-0 systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
Feb 06 13:23:40 bcluster-master-0 systemd[1]: bootkube.service: Failed with result 'exit-code'.
Feb 06 13:23:40 bcluster-master-0 systemd[1]: Failed to start Bootstrap a Kubernetes cluster.
bcluster-master-0 core #

when we ran "kubectl cluster-info" on host we got the below error
host@VM1:~/tectonic_1.8.4-tectonic.3/build/bcluster# kubectl cluster-info
Kubernetes master is running at https://controllers.biarcatectonic.com:443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp 10.1.24.64:443: getsockopt: no route to host

Also tried to access the tectonic cluster using https://controllers.biarcatectonic.com:443 and were unable to connect. Is this because
of kube-api service not running on master node?

Here we am attaching the terraform.tfvar(in .txt as could not attach tfvar extension) file and the DNS entries screenshot.

Could some one help us why etcd vms were not created and why we were unable to connect to tectonic console as well as unable to get cluster-info 
with kubectl.
![dns_config](https://user-images.githubusercontent.com/27193751/35862954-72c17e6c-0b73-11e8-86c4-7d22b47a64ff.png)
![nodes](https://user-images.githubusercontent.com/27193751/35862955-730083be-0b73-11e8-8832-93b1efab2a73.png)
[terraform.txt](https://github.com/hashicorp/terraform/files/1699284/terraform.txt)

**Comment by apparentlymart** [comment] 2018-02-06 16:39
Hi @sriramnulu! Sorry things didn't work out here.

Unfortunately the Terraform team at HashiCorp doesn't have deep expertise with CoreOS Tectonic, so we're not sure where to start with this problem. I'd suggest talking to the team behind [the Tectonic installer](https://github.com/coreos/tectonic-installer) first to see if they have ideas, and if they determine that a Terraform bug is the cause then we'd be more than happy to look into that issue and try to resolve it.

I'm going to close this for now, until we get some input from the CoreOS Tectonic Installer team. Thanks for opening this issue and sorry we can't help with it here.

**Closed by apparentlymart** 2018-02-06 16:39 UTC
