### ISSUE TITLE
Filter syntax issue with google cloud provider

### ISSUE THREAD

**Issue by frasercarter** [hashicorp/terraform#26722] opened 2020-10-27 21:56 UTC
### Terraform Version

```
ohmyzsh! ❯ terraform -v

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0

    provider registry.terraform.io/hashicorp/google v3.38.0
    provider registry.terraform.io/hashicorp/google-beta v3.38.0
    provider registry.terraform.io/hashicorp/random v2.3.0

```

### Terraform Configuration Files

```terraform
data "google_projects" "reports_prod" {
  filter = "parent.id:(${local.join}) labels.environment:prod lifecycleState:ACTIVE"
  }

locals {
  filter = "parent.id:(${local.join}) labels.environment:prod lifecycleState:ACTIVE" # To confirm syntax
  join = join(",",["${google_folder.data_reports.folder_id}","${google_folder.data.folder_id}"])
}
```

### Expected Behavior

```
ohmyzsh! ❯ terraform console
> local.filter
parent.id:(000000000000,000000000001) labels.environment:prod lifecycleState:ACTIVE

ohmyzsh! ❯ 
gcloud projects list --filter="parent.id:(000000000000,000000000001) labels.environment:prod lifecycleState:ACTIVE"
PROJECT_ID           NAME                        PROJECT_NUMBER
sensitive-000000   Sensitive - Prod      999999999991
sensitive-000001    Sensitive - Dev       999999999992
```

### Actual Behavior

```
Error: Error retrieving projects: googleapi: Error 400: field [filter] has issue [invalid syntax]
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "invalid syntax",
        "field": "filter"
      }
    ]
  }
]
```

### Additional Context

Experienced with below resource however may affect more if its a filter validation issue; when trying to use parenthesis in a filter to query 2 or more parent.ids (in this instance folders) the API reports an error in the syntax, however the same syntax string is used with the gcloud command and successfully returns the expected projects nested under those parent ids.
* google_projects

linked from: [https://github.com/hashicorp/terraform-provider-google/issues/7636](https://github.com/hashicorp/terraform-provider-google/issues/7636)

**Comment by alisdair** [comment] 2020-10-28 13:38
@frasercarter Thanks for reporting this!

I can't see anything that could be caused by Terraform core here. You could verify that by hard-coding the `filter` attribute of the data source to the same string you passed to `gcloud` on the command-line. If you remove the HCL interpolation and it still fails, then it seems like a provider bug, and I'd encourage re-opening the upstream issue with that information.

Could you try that and report back?

**Comment by pselle** [comment] 2021-03-12 20:28
Since this issue has been open as waiting for reproduction and waiting for response for four months, I'm going to close it as there is not yet further action to take on this issue.

**Closed by pselle** 2021-03-12 20:28 UTC
Labels: bug, v0.13, waiting for reproduction, waiting-response
