### ISSUE TITLE
ELB creation failed due to VPC having unattached internet gateway

### ISSUE THREAD

**Issue by willmcg** [hashicorp/terraform#1283] opened 2015-03-24 14:17 UTC
I'm running into issues with creation of ELB where the VPC containing the subnets across which it is balancing load has not yet had its internet gateway attached.

    * Resource 'aws_internet_gateway.igw' not found for variable 'aws_internet_gateway.igw.id'
    * Resource 'aws_internet_gateway.igw' not found for variable 'aws_internet_gateway.igw.id'
    * Resource 'aws_internet_gateway.igw' not found for variable 'aws_internet_gateway.igw.id'
    ...
    * Error creating ELB: VPC vpc-beac11db has no internet gateway

I even tried adding an explicit dependency in the ELB configuration to no avail:

    depends_on = [
        "aws_internet_gateway.igw"
    ]

This looks suspiciously like an eventual consistency problem with reporting of the internet gateway attachment to the VPC because all the VPC subnets have an explicit depends_on on the internet gateway so it should already be attached. Immediately re-running the terraform apply succeeds.

Every VPC subnet has this explicit dependency on the IGW:

    depends_on = [
        "aws_internet_gateway.igw"
    ]

**Comment by willmcg** [comment] 2015-03-24 15:06
Oh... and this is with Terraform from the master branch synced up yesterday.

**Comment by radeksimko** [comment] 2015-03-24 15:32
Would you mind isolating that issue and attaching a minimal example TF code that may cause that error?

**Comment by willmcg** [comment] 2015-03-24 15:37
I'm trying to pair down to a minimal test case for reproduction. Currently its part of a much larger config :-)

**Comment by willmcg** [comment] 2015-03-24 16:09
Here is a fairly minimal test case that fails pretty much every time for me...

    provider "aws" {
        access_key = "REDACTED"
        secret_key = "REDACTED"
        region     = "us-west-2"
    }

    resource "aws_vpc" "vpc" {
        cidr_block           = "10.0.0.0/16"
        enable_dns_support   = true
        enable_dns_hostnames = true
        tags {
            Name = "vpc"
        }
    }

    resource "aws_internet_gateway" "igw" {
        vpc_id = "${aws_vpc.vpc.id}"
        tags {
            Name = "igw"
        }
    }

    resource "aws_subnet" "subnet" {
        count                   = 1
        vpc_id                  = "${aws_vpc.vpc.id}"
        cidr_block              = "10.0.${count.index}.0/24"
        map_public_ip_on_launch = false
        tags {
            Name = "mysn-${count.index}"
        }
        depends_on = [
            "aws_internet_gateway.igw"
        ]
    }

    resource "aws_security_group" "elb" {
        name        = "myelb"
        description = "ELB SG"
        vpc_id      = "${aws_vpc.vpc.id}"
        egress {
            from_port = "443"
            to_port   = "443"
            protocol  = "tcp"
            cidr_blocks = [
                "10.0.0.0/16"
            ]
        }
        tags {
            Name = "elb"
        }
        depends_on = [
            "aws_subnet.subnet"
        ]
    }

    resource "aws_elb" "elb" {
        name = "myelb"
        cross_zone_load_balancing = true
        subnets = [
            "${aws_subnet.subnet.*.id}"
        ]
        security_groups = [
            "${aws_security_group.elb.id}"
        ]
        listener {
            lb_port           = 8888
            lb_protocol       = "tcp"
            instance_port     = 443
            instance_protocol = "tcp"
        }
        health_check {
            healthy_threshold   = 5
            unhealthy_threshold = 5
            target              = "TCP:443"
            interval            = 30
            timeout             = 10
        }
    }

Here is the output from the apply:

    $ terraform apply .
    aws_vpc.vpc: Creating...
      cidr_block:                "" => "10.0.0.0/16"
      default_network_acl_id:    "" => "<computed>"
      default_security_group_id: "" => "<computed>"
      enable_dns_hostnames:      "" => "1"
      enable_dns_support:        "" => "1"
      main_route_table_id:       "" => "<computed>"
      tags.#:                    "" => "1"
      tags.Name:                 "" => "vpc"
    aws_vpc.vpc: Error: 1 error(s) occurred:

    * Fields for multiple attribute types specified: enableDnsHostnames, enableDnsSupport
    aws_subnet.subnet: Creating...
      availability_zone:       "" => "<computed>"
      cidr_block:              "" => "10.0.0.0/24"
      map_public_ip_on_launch: "" => "0"
      tags.#:                  "" => "1"
      tags.Name:               "" => "mysn-0"
      vpc_id:                  "" => "vpc-59a4193c"
    aws_subnet.subnet: Creation complete
    aws_security_group.elb: Creating...
      description:                         "" => "ELB SG"
      egress.#:                            "" => "1"
      egress.1829582617.cidr_blocks.#:     "" => "1"
      egress.1829582617.cidr_blocks.0:     "" => "10.0.0.0/16"
      egress.1829582617.from_port:         "" => "443"
      egress.1829582617.protocol:          "" => "tcp"
      egress.1829582617.security_groups.#: "" => "0"
      egress.1829582617.self:              "" => "0"
      egress.1829582617.to_port:           "" => "443"
      name:                                "" => "myelb"
      owner_id:                            "" => "<computed>"
      tags.#:                              "" => "1"
      tags.Name:                           "" => "elb"
      vpc_id:                              "" => "vpc-59a4193c"
    aws_security_group.elb: Creation complete
    aws_elb.elb: Creating...
      availability_zones.#:                        "" => "<computed>"
      cross_zone_load_balancing:                   "" => "1"
      dns_name:                                    "" => "<computed>"
      health_check.#:                              "" => "1"
      health_check.2189893475.healthy_threshold:   "" => "5"
      health_check.2189893475.interval:            "" => "30"
      health_check.2189893475.target:              "" => "TCP:443"
      health_check.2189893475.timeout:             "" => "10"
      health_check.2189893475.unhealthy_threshold: "" => "5"
      instances.#:                                 "" => "<computed>"
      internal:                                    "" => "<computed>"
      listener.#:                                  "" => "1"
      listener.1553031545.instance_port:           "" => "443"
      listener.1553031545.instance_protocol:       "" => "tcp"
      listener.1553031545.lb_port:                 "" => "8888"
      listener.1553031545.lb_protocol:             "" => "tcp"
      listener.1553031545.ssl_certificate_id:      "" => ""
      name:                                        "" => "myelb"
      security_groups.#:                           "" => "1"
      security_groups.4005005733:                  "" => "sg-9ed0edfb"
      subnets.#:                                   "" => "1"
      subnets.531788431:                           "" => "subnet-1bf33d42"
    aws_elb.elb: Error: 1 error(s) occurred:

    * Error creating ELB: VPC vpc-59a4193c has no internet gateway
    Error applying plan:

    2 error(s) occurred:

    * 1 error(s) occurred:

    * 1 error(s) occurred:

    * Fields for multiple attribute types specified: enableDnsHostnames, enableDnsSupport
    * 1 error(s) occurred:

    * 1 error(s) occurred:

    * Error creating ELB: VPC vpc-59a4193c has no internet gateway

    Terraform does not automatically rollback in the face of errors.
    Instead, your Terraform state file has been partially updated with
    any resources that successfully completed. Please address the error
    above and apply again to incrementally change your infrastructure.

**Comment by willmcg** [comment] 2015-03-24 16:11
Also not sure what this message is all about:

    * Fields for multiple attribute types specified: enableDnsHostnames, enableDnsSupport

**Comment by willmcg** [comment] 2015-03-24 16:25
Looks like something is busted when both of the VPC DNS options are specified.

If I comment out either one of the DNS options the apply completes successfully first time:

    resource "aws_vpc" "vpc" {
        cidr_block           = "10.0.0.0/16"
        enable_dns_support   = true
    #    enable_dns_hostnames = true
        tags {
            Name = "vpc"
        }
    }

**Comment by kendawg2** [comment] 2015-03-25 20:44
@willmcg This should be fixed with PR #1304

**Comment by catsby** [comment] 2015-03-27 14:19
I believe this to be fixed with #1304. I can't reproduce it with the provided configuration (everything creates as expected).

Let me know if you're still running into this, and thanks!

**Closed by catsby** 2015-03-27 14:19 UTC
Labels: bug, provider/aws
