### ISSUE TITLE
aws_subnet cidr_block not utilizing cidrsubnet correctly

### ISSUE THREAD

**Issue by msmith86** [hashicorp/terraform#23704] opened 2019-12-17 14:28 UTC
### Terraform Version

```
terraform -v
Terraform v0.12.6
+ provider.aws v2.42.0
```

### Terraform Configuration Files

```hcl
resource "aws_subnet" "subnets" {
  count  = "${var.num_subnets}"
  vpc_id = "${data.aws_vpc.vpc_to_use_2.id}"

  cidr_block        = cidrsubnet("${var.subnet_base_address}/${var.subnet_size}",1,count.index) 
  availability_zone = "${format("%s%s", var.region, element(var.az_list, count.index))}"
}
module "test_subnets" {
  source              = "../Resources/Subnets"
  serverStartNumber   = 20
  environment         = "prod"
  app_name            = "test"
  subnet_base_address = "10.125.32.32"
  subnet_size         = 27
  num_subnets         = 2
}

```

### Debug Output

```
terraform plan -target=module.test_subnets
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.test_subnets.data.aws_availability_zones.az_list: Refreshing state...
module.test_subnets.data.aws_vpc.vpc_to_use_2: Refreshing state...


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  !# module.test_subnets.aws_subnet.subnets[0] will be created
  + resource "aws_subnet" "subnets" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-east-1a"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.125.32.32/28"
      + id                              = (known after apply)
      + ipv6_cidr_block                 = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
    }

  !# module.test_subnets.aws_subnet.subnets[1] will be created
  + resource "aws_subnet" "subnets" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-east-1b"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.125.32.48/28"
      + id                              = (known after apply)
      + ipv6_cidr_block                 = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

===========
Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

!Releasing state lock. This may take a few moments...

==========
terraform plan -target=module.test_subnets
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.test_subnets.data.aws_vpc.vpc_to_use_2: Refreshing state...
module.test_subnets.data.aws_availability_zones.az_list: Refreshing state...

==========

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  !# module.test_subnets.aws_subnet.subnets[0] will be created
  + resource "aws_subnet" "subnets" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-east-1a"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.125.32.0/27"
      + id                              = (known after apply)
      + ipv6_cidr_block                 = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
    }

  !# module.test_subnets.aws_subnet.subnets[1] will be created
  + resource "aws_subnet" "subnets" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-east-1b"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.125.32.32/27"
      + id                              = (known after apply)
      + ipv6_cidr_block                 = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

==========

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

!Releasing state lock. This may take a few moments.
```
..
### Crash Output

No Crash

### Expected Behavior

We expect the resource to create the subnets in the desired IP space.

### Actual Behavior

We have IP space that needs to be consumed by applications but Terraform is unable to build the subnets. We currently use 10.125.32.0/28 and 10.125.32.16/28 and 10.125.33.0/25. I have been trying to get Terraform to start at 10.125.32.32/27 but will only start there if I use a /28.

When running terraform plan -target=module.test_subnets we are unable to consume IP space for a /27 if we desire it to start at any network other than a .0. This halts us from being able to utilize IP space if we want terraform to create the subnets. We have changed the above configuration to include {var.subnet_size - 1} due to the newbit of cidrsubnet but still doesnt change the output.

If I specifically put the starting 10.125.32.32/27 as the cidr_block in the resource I am able to have Terraform correctly create the subnet but I only get 1 subnet.

### Steps to Reproduce

terraform init
terraform plan -target=module.test_subnets

### Additional Context

Utilizing Terragrunt but only when actually applying. Doing testing with terraform plan -target=module.test_subnets

**Comment by teamterraform** [comment] 2019-12-17 15:51
> We have IP space that needs to be consumed by applications but Terraform is unable to build the subnets. We currently use 10.125.32.0/28 and 10.125.32.16/28 and 10.125.33.0/25. I have been trying to get Terraform to start at 10.125.32.32/27 but will only start there if I use a /28.

Hello, it's unclear what you mean by "trying to get Terraform to start" -- you say no crash happens, so what is happening that is different from your expectations? Is your question that you think https://www.terraform.io/docs/configuration/functions/cidrsubnet.html is producing incorrect output based on the arguments you're providing?

**Comment by msmith86** [comment] 2019-12-17 18:11
"trying to get Terraform to start" should have been "getting Terraform to begin creation of the cidr block".

Terraform should be building 2 subnets based on my count argument. If you look at my terraform plan that I provided above you will see that when the cidr block is set to /27 and told to create 10.125.32.32/27 and 10.125.32.64/27 (both of which are valid networks) it always tries to build 10.125.32.0/27 and 10.125.32.32/27 resulting in a conflict for the first subnet as we have already consumed 10.125.32.0 wiht a /28 in the VPC.

The problem here is that when I utilize cidrsubnet (which I am of the understanding is needed to create multiple subnets based on given count) is always trying to start at X.X.X.0 instead of the given start point. The only way I could get it to start on a final octet network is with a /28.

To me it looks like the output is wrong for cidrsubnet unless I am expecting/understanding the wrong output with that function.

**Comment by msmith86** [comment] 2019-12-20 15:02
Hello All,

Any update or suggestions about this behavior? I had to work around this by starting at the next available X.X.X.0 network. While this gets my current deployment rolling, it doesnt resolve my issue with being unable to consume the IP space desired.

Thank you.

**Comment by teamterraform** [comment] 2019-12-21 01:37
Hi @msmith86,

If we put the original range you started with into `ipcalc` we can see the binary representation, which is easier to think about while debugging this:

```
$ ipcalc 10.125.32.32/27
Address:   10.125.32.32         00001010.01111101.00100000.001 00000
Netmask:   255.255.255.224 = 27 11111111.11111111.11111111.111 00000
Wildcard:  0.0.0.31             00000000.00000000.00000000.000 11111
=>
Network:   10.125.32.32/27      00001010.01111101.00100000.001 00000
HostMin:   10.125.32.33         00001010.01111101.00100000.001 00001
HostMax:   10.125.32.62         00001010.01111101.00100000.001 11110
Broadcast: 10.125.32.63         00001010.01111101.00100000.001 11111
Hosts/Net: 30                    Class A, Private Internet
```

Calling `cidrsubnet("10.125.32.32/27", 1, 0)` asks Terraform to extend the prefix by one additional bit, making a `/28` prefix, and set the additional bit to zero. That gives `10.125.32.32/28`, which we can also look at in `ipcalc`:

```
$ ipcalc 10.125.32.32/28
Address:   10.125.32.32         00001010.01111101.00100000.0010 0000
Netmask:   255.255.255.240 = 28 11111111.11111111.11111111.1111 0000
Wildcard:  0.0.0.15             00000000.00000000.00000000.0000 1111
=>
Network:   10.125.32.32/28      00001010.01111101.00100000.0010 0000
HostMin:   10.125.32.33         00001010.01111101.00100000.0010 0001
HostMax:   10.125.32.46         00001010.01111101.00100000.0010 1110
Broadcast: 10.125.32.47         00001010.01111101.00100000.0010 1111
Hosts/Net: 14                    Class A, Private Internet
```

As expected, the address is now occupying one additional bit, and that additional bit is set to zero.

Likewise, telling Terraform to set the new bit to 1 produces `10.125.32.48/28`:

```
$ ipcalc 10.125.32.48/28
Address:   10.125.32.48         00001010.01111101.00100000.0011 0000
Netmask:   255.255.255.240 = 28 11111111.11111111.11111111.1111 0000
Wildcard:  0.0.0.15             00000000.00000000.00000000.0000 1111
=>
Network:   10.125.32.48/28      00001010.01111101.00100000.0011 0000
HostMin:   10.125.32.49         00001010.01111101.00100000.0011 0001
HostMax:   10.125.32.62         00001010.01111101.00100000.0011 1110
Broadcast: 10.125.32.63         00001010.01111101.00100000.0011 1111
Hosts/Net: 14                    Class A, Private Internet
```

Again, we can see that the only difference relative to the first `/27` example is the additional bit in the address which is set to 1 this time.

So it seems that `cidrsubnet` is behaving the way we intended here, but we're still not sure we're fully understanding how to relate that to what you're trying to achieve. `cidrsubnet` and the other `cidr...` functions are for systematic allocation of addresses under a particular prefix, but it seems like you're trying to assign _specific_ ranges to work around existing allocations made elsewhere, in which case it's likely better for you to build your module to take a map of cidr range strings directly rather than trying to calculate them:

```hcl
variable "subnet_prefixes" {
  # a map from availability zone names to subnet addresses
  type = map(string)
}

resource "aws_subnet" "subnets" {
  for_each = toset(var.subnet_prefixes)

  vpc_id = data.aws_vpc.vpc_to_use_2.id

  cidr_block        = each.value
  availability_zone = each.key
}
```

It may be possible to systematize your allocations if you can describe the allocation scheme in a systematic way that doesn't include exceptions for existing allocations. However, we use our GitHub issues for tracking bugs in Terraform rather than for general help, so if you're interested in investigating that further we'd ask that you start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Because `cidrsubnets` seems to be behaving in the way it was designed to behave, we're going to close this issue.

If you can explain what you're trying to achieve in the community forum, hopefully one of the participants in the forum can offer some suggestions of different ways to achieve it. Thanks!

**Closed by teamterraform** 2019-12-21 01:37 UTC
