### ISSUE TITLE
Delete unused S3 folder/objects 

### ISSUE THREAD

**Issue by higee** [hashicorp/terraform#20668] opened 2019-03-13 10:32 UTC
### Current Terraform Version

```
0.11.11
```

### Use-cases

My pipeline is as follows.

<img src="https://user-images.githubusercontent.com/16909821/54270796-8326cf80-4580-11e9-85e4-f5eca3be3f5a.png" width="400" height="70">

#### 1) Without prefix

I first tried with following config (I just pasted `firehose` config to make things simple)

```
$ cat main.tf
>>>
                                ⋮

resource "aws_kinesis_firehose_delivery_stream" "firehose" {
  name          = "test"
  destination   = "s3"

  kinesis_source_configuration {
    kinesis_stream_arn       = "${aws_kinesis_stream.kinesis.arn}"
    role_arn                 = "${aws_iam_role.admin.arn}"
  }

  s3_configuration {
    role_arn     = "${aws_iam_role.admin.arn}"
    bucket_arn   = "${aws_s3_bucket.s3.arn}"
  }
}
                               ⋮
```

Everything was fine as was written in [Terraform documentation](https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html#prefix)

![image](https://user-images.githubusercontent.com/16909821/54271495-eb29e580-4581-11e9-85ac-c7f2b334988d.png)

#### 2) With prefix

Some time later, we decided to store stream-data under a folder, `data`, by enabling `prefix` option in following way. 

```
$ cat main.tf
>>>
                                ⋮

resource "aws_kinesis_firehose_delivery_stream" "firehose" {
  name          = "test"
  destination   = "s3"

  kinesis_source_configuration {
    kinesis_stream_arn       = "${aws_kinesis_stream.kinesis.arn}"
    role_arn                 = "${aws_iam_role.admin.arn}"
  }

  s3_configuration {
    role_arn     = "${aws_iam_role.admin.arn}"
    bucket_arn   = "${aws_s3_bucket.s3.arn}"
    prefix       = "data/"
  }
}
                               ⋮
```

What I got is as follows.

![image](https://user-images.githubusercontent.com/16909821/54272070-2d075b80-4583-11e9-907e-73bfd560abe7.png)

### Attempted Solutions

Couldn't find any.

### Proposal

What I was expecting was having `2019` folder removed recursively and just have `data` folder remained since `prefix` has been added.

![image](https://user-images.githubusercontent.com/16909821/54272222-7f487c80-4583-11e9-956e-687cd8e85faf.png)

**Comment by apparentlymart** [comment] 2019-03-13 15:51
Hi @higee,

In this case, the Terraform resource is representing the instructions to Kinesis Firehose about where to put new data that arrives. Terraform itself is managing only Kinesis Firehose, and then Firehose in turn manages the S3 and other objects you've instructed it to create for you.

Terraform will, by design, only make changes to the objects it is directly managing. If you want Firehose to rename or delete existing objects when the S3 configuration changes, that is a feature request for Kinesis Firehose itself, which you will need to discuss with its product team at AWS. If they implement such a feature then we (via the AWS provider's own repository, not this one) can make sure Terraform supports it.

Since this request is not within Terraform's scope, I'm going to close it. If the Firehose team adds a feature for this that requires Terraform changes to support, please then open an issue in the AWS provider's own repository, not this one which is for Terraform Core.

**Closed by apparentlymart** 2019-03-13 15:51 UTC
Labels: enhancement

**Comment by higee** [comment] 2019-03-14 15:34
Hi @apparentlymart,

Yeah that's clear enough. Thanks :)
