### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by Andrew-J-MacKenzie** [hashicorp/terraform#31402] opened 2022-07-08 03:39 UTC
### Terraform Version
```
Terraform version
1.0.1
...
```

### Terraform Configuration Files

!!!!!!!!!!!!!!!!!!!!!!!!!!!  TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.803796799.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.803796799.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform v1.0.1
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
{"@level":"info","@message":"Terraform 1.0.1","@module":"terraform.ui","@timestamp":"2022-07-07T20:29:34.571995Z","terraform":"1.0.1","type":"version","ui":"0.1.0"}
{"@level":"info","@message":"module.lmtaextractorfunction.azurerm_function_app.AED-Lmta-Function: Plan to update","@module":"terraform.ui","@timestamp":"2022-07-07T20:29:57.289516Z","change":{"resource":{"addr":"module.lmtaextractorfunction.azurerm_function_app.AED-Lmta-Function","module":"module.lmtaextractorfunction","resource":"azurerm_function_app.AED-Lmta-Function","implied_provider":"azurerm","resource_type":"azurerm_function_app","resource_name":"AED-Lmta-Function","resource_key":null},"action":"update"},"type":"planned_change"}
{"@level":"info","@message":"Plan: 0 to add, 1 to change, 0 to destroy.","@module":"terraform.ui","@timestamp":"2022-07-07T20:29:57.289563Z","changes":{"add":0,"change":1,"remove":0,"operation":"plan"},"type":"change_summary"}
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 2)
Output: panic: value is marked, so must be unmarked first

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2cbab70, 0xc0013373b0, 0x25536a0, 0xc000918b70, 0x2cbab01)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1050 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc000e4ca10, 0x1, 0x1, 0x2cbab70, 0xc0013373b0, 0x25536a0, 0xc000918b70, 0x2c84028, 0xc0009191a0, 0xc000918b70, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:144 +0x2e8
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x2cbab38, 0xc0013374a0, 0x245fdc0, 0xc0010c9b00, 0x2c84028, 0xc0009191a0, 0xc000e4c550, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x2cbab38, 0xc0013374a0, 0x245fdc0, 0xc0010c9b00, 0xc000d54d80, 0x4, 0x4, 0x2c1a2c0, 0x1, 0xc001395580, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:236 +0xc5
github.com/hashicorp/terraform/internal/command/jsonstate.marshalResources(0xc001a0e960, 0xc0009711c0, 0x1, 0x1, 0xc000407ab0, 0x8a3285, 0x0, 0x0, 0x0, 0xc001bcb0b0)
	/home/circleci/project/project/internal/command/jsonstate/state.go:333 +0xe07
github.com/hashicorp/terraform/internal/command/jsonstate.marshalModules(0xc00052eee8, 0xc000407ab0, 0xc00088f500, 0xa, 0x10, 0xc001bcb1a8, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/internal/command/jsonstate/state.go:254 +0x538
github.com/hashicorp/terraform/internal/command/jsonstate.marshalRootModule(0xc00052eee8, 0xc000407ab0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/internal/command/jsonstate/state.go:234 +0x8c9
github.com/hashicorp/terraform/internal/command/jsonstate.(*state).marshalStateValues(0xc001b073b0, 0xc00052eee8, 0xc000407ab0, 0x0, 0x0)
	/home/circleci/project/project/internal/command/jsonstate/state.go:166 +0x14a
github.com/hashicorp/terraform/internal/command/jsonstate.Marshal(0xc0019be690, 0xc000407ab0, 0x0, 0x0, 0x0, 0x0, 0x219f5b5)
	/home/circleci/project/project/internal/command/jsonstate/state.go:146 +0xf8
github.com/hashicorp/terraform/internal/command/jsonplan.Marshal(0xc000b76a90, 0xc0008a2e60, 0xc0019be690, 0xc000407ab0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/command/jsonplan/plan.go:152 +0x633
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0xc00041a000, 0xc000140070, 0x1, 0x2, 0xc000406170)
	/home/circleci/project/project/internal/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc000408280, 0xc000404000, 0x282e5dd, 0x4)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x554
main.main()
	/home/circleci/project/project/main.go:58 +0x25

**Comment by jbardin** [comment] 2022-07-08 13:32
Duplicate of #29042. Please update to a current Terraform release.

**Closed by jbardin** 2022-07-08 13:32 UTC
Labels: bug, new
