### ISSUE TITLE
Feature request: Allow interpolations in module source parameter

### ISSUE THREAD

**Issue by ssanpietro-gr** [hashicorp/terraform#26544] opened 2020-10-10 16:37 UTC
### Current Terraform Version
```
Terraform v0.13.4
```

### Use cases

I've got a terraform stack which needs to create AWS secrets in multiple different places: I create some RDS DB instances and for each instance, I create a secret which has the login credentials for that DB; and I also need to create secrets for completely unrelated API login information elsewhere in the terraform code.

I'm using a secrets module I've written and stored in github to do this. However, because I'm calling this module in multiple places, keeping the versions correct is very brittle and wet. As I understand it, the point of modules is to do what functions do in programming languages: abstract away common tasks to avoid code duplication. But because I have to hard code the version and git repo URL in each of these module calls, I'm bound to get out of sync somewhere. I think interpolation would greatly help make this code maintainable.

### Proposal

I would like to have a single yaml file with all of my module configuration info in it:

`modules.yaml`:
```
secrets:
  repo: git@github.com:mysecretsmodule.git
  reference: v1.4.0

rds:
  repo: git@github.com:myrdsmodule.git
  reference: v1.11.2
```

And then reference these version configurations wherever I call a module:

`locals.tf`:
```
module_configs = yamldecode(file("modules.yaml"))
```

`main.tf`:
```
module "secret" {
  source             = "${local.module_configs["secrets"]["repo"]}?ref=${local.module_configs["secrets"]["reference"]}"
  ...
}
```

Without the ability to do this, it's extremely difficult to ensure that all module calls are using the correct versions. On top of this, it would just be much easier to have all module version info in one place, similar to a `requirements.txt` file in python, rather than have to dig through the code to find out what versions are being used.

### References

This issue was discussed in #1439 and #18063, but both of those are marked as issues/bugs and have been closed as won't fix. I couldn't find a feature request on this issue, so I'm opening one here.

**Comment by udayanms** [comment] 2020-10-14 15:11
this is definitely important feature.

**Comment by pkolyvas** [comment] 2020-10-20 23:13
Closing this as a duplicate of #25587 

I agree it's an important feature but it's not on our pre-1.0 roadmap.

**Closed by pkolyvas** 2020-10-20 23:13 UTC
Labels: enhancement, new
