### ISSUE TITLE
Error while make apply

### ISSUE THREAD

**Issue by LMadhavi** [hashicorp/terraform#3374] opened 2015-10-01 01:47 UTC
In Terraform v0.5.3, I am getting the following error: 

```
${var.subnet_id}
2015/09/30 18:39:07 [ERROR] root.cloudera.consul: eval: *terraform.EvalSequence, err: 1:3: unknown variable accessed: var.subnet_id in:
${var.subnet_id}
2015/09/30 18:39:07 waiting for all plugin processes to complete...
2015/09/30 18:39:07 [DEBUG] /home/parallels/bin/terraform-provisioner-remote-exec: plugin process exited
2015/09/30 18:39:07 [DEBUG] /home/parallels/bin/terraform-provisioner-file: plugin process exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
make: *** [apply] Error 1
```

**Comment by phinze** [comment] 2015-10-12 11:44
Hi @LMadhavi - the latest version of Terraform is `v0.6.3` can you update to that and follow up if you still get the error?

**Comment by catsby** [comment] 2016-07-20 16:56
Going to close this for now, the issue is quite old and we're up to v0.6.16 at time of writing. Please let us know if you still have issues!

**Closed by catsby** 2016-07-20 16:56 UTC
Labels: bug, core, waiting-response
