### ISSUE TITLE
`terraform state mv` doesn't seem to work when the target is in an empty module

### ISSUE THREAD

**Issue by Ahimta** [hashicorp/terraform#21551] opened 2019-06-01 01:54 UTC
### Terraform Version

```
Terraform v0.12.0
+ provider.aws v2.12.0
```

##### main.tf
```hcl
provider "aws" {
  version = "2.12.0"
  region  = "us-east-1"
}

resource "aws_ecs_cluster" "cluster" {
  name = "cluster"
}

module "compute" {
  source = "./modules/compute"
}
```

##### ./modules/compute/main.tf
```hcl
<empty file>
```

Now I run the following and all is well:
1. `terraform init`
2. `terraform apply` (and confirm changes and they are applied successfully).

##### main.tf
```hcl
provider "aws" {
  version = "2.12.0"
  region  = "us-east-1"
}

module "compute" {
  source = "./modules/compute"
}
```

##### ./modules/compute/main.tf
```hcl
resource "aws_ecs_cluster" "cluster" {
  name = "cluster"
}
```

Now I want to move `aws_ecs_cluster.cluster` to `module.compute.aws_cluster.cluster`
using the following:
```bash
terraform state mv aws_ecs_cluster.cluster module.compute.aws_ecs_cluster.cluster
```
But I get the following error message:
```
Error: Invalid target address

Cannot move to module.compute.aws_ecs_cluster.cluster: module.compute does not
exist in the current state.
```

There's a workaround, however. And it's something like this:
1. Create any resource in the new module `compute` and run `terraform apply` to make sure the module is added to the state.
2. Now `terraform state mv aws_ecs_cluster.cluster module.compute.aws_ecs_cluster.cluster` works successfully` and the hack resource can be safely removed.

### Debug Output

```
2019/06/01 04:35:52 [INFO] Terraform version: 0.12.0  
2019/06/01 04:35:52 [INFO] Go runtime version: go1.12.4
2019/06/01 04:35:52 [INFO] CLI args: []string{"/home/abdullah/.local/bin/terraform", "state", "mv", "aws_ecs_cluster.cluster", "module.compute.aws_ecs_cluster.cluster"}
2019/06/01 04:35:52 [DEBUG] Attempting to open CLI config file: /home/abdullah/.terraformrc
2019/06/01 04:35:52 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/06/01 04:35:52 [INFO] CLI command args: []string{"state", "mv", "aws_ecs_cluster.cluster", "module.compute.aws_ecs_cluster.cluster"}
2019/06/01 04:35:52 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2019/06/01 04:35:52 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2019/06/01 04:35:52 [DEBUG] New state was assigned lineage "5e00ebb1-faec-75c6-7f12-8e61b859e7b7"
2019/06/01 04:35:52 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2019/06/01 04:35:52 [TRACE] Meta.Backend: instantiated backend of type <nil>
2019/06/01 04:35:52 [DEBUG] checking for provider in "."
2019/06/01 04:35:52 [DEBUG] checking for provider in "/home/abdullah/.local/bin"
2019/06/01 04:35:52 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/06/01 04:35:52 [DEBUG] found provider "terraform-provider-aws_v2.12.0_x4"
2019/06/01 04:35:52 [DEBUG] found valid plugin: "aws", "2.12.0", "/home/abdullah/Documents/Projects/terraform-state-mv-bug/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.12.0_x4"
2019/06/01 04:35:52 [DEBUG] checking for provisioner in "."
2019/06/01 04:35:52 [DEBUG] checking for provisioner in "/home/abdullah/.local/bin"
2019/06/01 04:35:52 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2019/06/01 04:35:52 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2019/06/01 04:35:52 [TRACE] backend/local: CLI option -backup is overriding state backup path to -
2019/06/01 04:35:52 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at 
2019/06/01 04:35:52 [DEBUG] checking for provider in "."
2019/06/01 04:35:52 [DEBUG] checking for provider in "/home/abdullah/.local/bin"
2019/06/01 04:35:52 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/06/01 04:35:52 [DEBUG] found provider "terraform-provider-aws_v2.12.0_x4"
2019/06/01 04:35:52 [DEBUG] found valid plugin: "aws", "2.12.0", "/home/abdullah/Documents/Projects/terraform-state-mv-bug/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.12.0_x4"
2019/06/01 04:35:52 [DEBUG] checking for provisioner in "."
2019/06/01 04:35:52 [DEBUG] checking for provisioner in "/home/abdullah/.local/bin"
2019/06/01 04:35:52 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2019/06/01 04:35:52 [TRACE] backend/local: CLI option -backup is overriding state backup path to -
2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: preparing to manage state snapshots at terraform.tfstate
2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: existing snapshot has lineage "634b0aab-bf57-5afa-7641-241d7ac690b8" serial 1
2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: locking terraform.tfstate using fcntl flock
2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: writing lock metadata to .terraform.tfstate.lock.info
2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: reading latest snapshot from terraform.tfstate
2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: read snapshot with lineage "634b0aab-bf57-5afa-7641-241d7ac690b8" serial 1
2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info

Error: Invalid target address

2019/06/01 04:35:52 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
Cannot move to module.compute.aws_ecs_cluster.cluster: module.compute does not
exist in the current state.
```

### Expected Behavior

`terraform state mv aws_ecs_cluster.cluster module.compute.aws_ecs_cluster.cluster` should have worked even the `compute` module is empty and at least confirm with the user to create it because  the module purpose, in this case, was to refactor/break-down the original configuration. Unless, of course, this behavior is intentional.

### Actual Behavior

`terraform state mv aws_ecs_cluster.cluster module.compute.aws_ecs_cluster.cluster` fails when the `compute` module has no resources and a bogus resource had to be created to workaround this.

### Steps to Reproduce

Above closer to the configuration:sweat_smile:.

### Additional Context

Nope.

### References

- #21346 looks very close but I'm not really sure and feel free to mark my issue as duplicate and close it if you see fit:sweat_smile:. On the other hand, this issue uses the latest `0.12.0` while the other one uses `0.12.0-rc1` and this one has a workaround too:sunglasses:.

**Comment by mildwonkey** [comment] 2019-06-03 12:46
Hi @Ahimta,
This does look like a duplicate of #21346 (which is still open), so I am going to close this one, but thank you for the excellent write-up and I'm sorry you've experienced this odd behavior.

**Closed by mildwonkey** 2019-06-03 12:46 UTC
