### ISSUE TITLE
variable type validation skipped with unknown values

### ISSUE THREAD

**Issue by amgiunta** [hashicorp/terraform#21968] opened 2019-07-03 20:26 UTC
Hi,

I have recently run into an issue with Terraform where defining multiple providers crashes the program. I need to define multiple providers to provision resources on specific accounts. I was following the official [Terraform documentation](https://www.terraform.io/docs/configuration/modules.html). I am using a .tfvars file to set up the configuration below (which I have not listed because there are secret keys within it). 

### Terraform Version
v0.12.3

### Configuration

```hcl
provider "aws" {
    alias = "sandbox"
    access_key = "${var.sandbox_credentials.client_id}"
    secret_key = "${var.sandbox_credentials.secret_key}"
    region     = "${var.sandbox_credentials.region}"
}

provider "aws" {
    alias = "tools"
    access_key = "${var.tools_credentials.client_id}"
    secret_key = "${var.tools_credentials.secret_key}"
    resion = "${var.tools_credentials.region}"
}
```

### Debug Output
https://gist.github.com/amgiunta/22fd7a126415514d092c6f84c7debd63

### Crash Output
https://gist.github.com/amgiunta/36c4d6f15b02bf6409a824bbf4700ff4

### Expected Behavior
Terraform should've at least configured the providers.

### Actual Behavior
Terraform prompts for info about an already existing provider and crashes given any input.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment] 2019-07-05 12:46
Hi @amgiunta,

Thanks for filing the issue. The crash doesn't appear to be related to the providers, it happens when evaluating `module.codepipeline.var.artifact_store_info`. Is it possible to show some more of the configuration to try and reproduce the crash?

**Comment by amgiunta** [comment] 2019-07-05 13:11
Hi @jbardin,

Thanks for reaching out. I have created a gist for my [codepipeline template.](https://gist.github.com/amgiunta/853d8704aef573508cab1147169db6d5). artifact_store_info is a map that i use to pass the module information about the location, type, and encryption key data of the codepipeline artifact bucket.

The map I'm passing looks like:
`artifact_store_info = {
        location = "${data.aws_s3_bucket.artifact_store.bucket}"
        type     = "S3"

        encryption_key = {
            id = "${data.aws_kms_key.kms_key.arn}"
            type = "KMS"
        }
    }`

**Comment by jbardin** [comment] 2019-07-05 13:31
Thanks for the update @amgiunta,

What is triggering the crash is that you have a variable with a `type = map`, but you're passing in a map with mixed value types. If the value types are not consistent, you will have to define an `object` structure to match the expected variable arguments, or you can leave it undefined to be inferred at runtime. 

The config also doesn't appear to have been upgraded per the [0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html). It would interesting to know if the `0.12upgrade` tool would catch offer any assistance here as well.

**Comment by amgiunta** [comment] 2019-07-05 13:52
Thanks @jbardin,

Apply is now validating the config successfully.
I changed my definition to look like
`variable "artifact_store_info" {
    type = object({location=string, type=string, encryption_key=list(map(string))})
    description = "Information related to the desired artifact store resource"
}`

and I'm passing the data like so:
`artifact_store_info = {
        location = "${data.aws_s3_bucket.artifact_store.bucket}"
        type     = "S3"

        encryption_key = [{
            id = "${data.aws_kms_key.kms_key.arn}"
            type = "KMS"
        }]
    }`

Thanks again for your help! I hope this bug report helps you and your team as well.
Have a great day!

**Comment by danieldreier** [comment] 2020-06-11 21:03
This issue looks like a likely duplicate of https://github.com/hashicorp/terraform/issues/24229 and https://github.com/hashicorp/terraform/issues/21588#issuecomment-592149310 and is solved by https://github.com/hashicorp/terraform/pull/24983 in 0.13.0. I'm going to close this for now, but @amgiunta if this seems wrong please reach out to me (ddreier@hashicorp.com) and I'm happy to re-open this.

**Closed by danieldreier** 2020-06-11 21:03 UTC
Labels: bug, crash, v0.12
