### ISSUE TITLE
Name prefix fields + length limits = no flexibility.

### ISSUE THREAD

**Issue by tecnobrat** [hashicorp/terraform#13995] opened 2017-04-26 16:01 UTC
Hello,

When using `name_prefix` on a number of resource types, we end up in a situation where we have no flexibility on naming.

For instance, `aws_alb` only allows a 32 character limit on the name of the resource.

The `name_prefix` always adds 26 characters, which means I only have 6 characters for my prefix.

My suggestion is that the `PrefixedUniqueId` method accept a max length value, and then instead of just adding 26 characters, it adds "enough characters to be max length".

That way my prefix can be `somecrazyprefix-` the method understands I've used 16 characters, and only adds 16 more to the end, which is now a 32 character length string.

**Comment by joshuaspence** [comment] 2017-05-04 13:56
Dupe of #12947

**Comment by apparentlymart** [comment] 2017-05-30 23:01
Hi @tecnobrat! Sorry for the silence here.

As @joshuaspence pointed out, this is a duplicate of #12947 so I'm going to close this to consolidate any further discussion over there.

**Closed by apparentlymart** 2017-05-30 23:01 UTC
Labels: core, enhancement
