### ISSUE TITLE
azure vm backup case sensitivity

### ISSUE THREAD

**Issue by alexgoldberg1961** [hashicorp/terraform#29077] opened 2021-07-01 14:24 UTC
### Terraform Version

```
1.0.1
```

### Terraform Configuration Files

```
resource "azurerm_backup_protected_vm" "backup" {
	count                   = var.enable_backup ? var.number_of_nodes : 0
	resource_group_name     = var.backup_resource_group_name
	recovery_vault_name     = var.backup_vault_name
	backup_policy_id        = var.backup_policy_id
	source_vm_id            = element(azurerm_virtual_machine.vm_node.*.id, count.index)
}

...
```

### Expected Behavior

No changes to resource "azurerm_backup_protected_vm" "backup" {} should have been identified
### Actual Behavior

changes to resource "azurerm_backup_protected_vm" "backup" {} have been identified
### Steps to Reproduce

  # module.windowsservers.azurerm_backup_protected_vm.backup[0] will be updated in-place
  ~ resource "azurerm_backup_protected_vm" "backup" {
      ~ backup_policy_id    = "/subscriptions/1234-456-789/resourceGroups/DEV-VM-BACKUPS-RG/providers/Microsoft.RecoveryServices/vaults/DEV-VM-BACKUPS/backupPolicies/StandardNonProductionRetentionPolicy" -> "/subscriptions/1234-456-789/resourcegroups/dev-vm-backups-rg/providers/microsoft.recoveryservices/vaults/dev-vm-backups/backuppolicies/standardnonproductionretentionpolicy"
        id                  = "/subscriptions/1234-456-789/resourceGroups/DEV-VM-BACKUPS-RG/providers/Microsoft.RecoveryServices/vaults/DEV-VM-BACKUPS/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;DEV-VNX-VM-RG;vnxd001/protectedItems/VM;iaasvmcontainerv2;DEV-VNX-VM-RG;vnxd001"
        tags                = {}
        # (3 unchanged attributes hidden)
    }

module.windowsservers.azurerm_backup_protected_vm.backup[0]: Still modifying... [id=/subscriptions/1234-456-789...DEV-VM-RG;vnxd001, 20s elapsed]
module.windowsservers.azurerm_backup_protected_vm.backup[0]: Modifications complete after 21s [id=/subscriptions/1234-456-789/resourceGroups/DEV-VM-BACKUPS-RG/providers/Microsoft.RecoveryServices/vaults/DEV-VM-BACKUPS/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;DEV-VNX-VM-RG;vnxd001/protectedItems/VM;iaasvmcontainerv2;DEV-VNX-VM-RG;vnxd001]

### Additional Context

If I run terraform plan right after the apply, the changes to backup resource are once again identified.

**Comment by apparentlymart** [comment] 2021-07-01 17:42
Hi @alexgoldberg1961,

What you've described here is, from the generic Terraform perspective, the problem of differentiating "drift" from "normalization". "Drift" is the situation where the object has changed in a way that is functionally different than what you declared, while "normalization" is where the object has changed in some cosmetic way that is immaterial to the behavior of the object.

In Terraform's architecture, it's the provider's responsibility to distinguish these two situations. In the situation you've shown here it seems like the Azure provider is classifying these changes in case as drift rather than normalization, and thus planning to change the value to remediate that.

From looking in the Azure provider repository I see terraform-providers/terraform-provider-azurerm#8009 which seems to be representing the same problem you've encountered here. It seems like that discussion concluded that the root cause was upstream in the Azure API, tracked at Azure/azure-rest-api-specs#10357.

Given that, it seems that Terraform is working as intended here and the Azure provider team is aware of this bug but is blocked on an upstream fix from the Azure team. For that reason, I'm going to close this issue. It seems like the Azure provider team plans to address this bug once the upstream API is behaving correctly, and so you might want to follow the upstream API issue to see the progress there.

In the meantime, a typical workaround for this sort of misclassification is to change your module to produce the normalized form that the provider or remote API is expecting. In this case, I guess that would mean changing `var.backup_policy_id` to be written in the same case that the remote API is expecting. If you have any follow-up questions about that then I'd suggest starting a topic in [the Azure provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

Thanks!

**Closed by apparentlymart** 2021-07-01 17:42 UTC
Labels: bug, new
