### ISSUE TITLE
Terraform Random Integer 0.12 update

### ISSUE THREAD

**Issue by ss-sierra-cedar** [hashicorp/terraform#24633] opened 2020-04-10 17:43 UTC
### Terraform Version

```
Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.aws v2.55.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
...
```

### Terraform Configuration Files

```hcl
resource "random_integer" "lc-string-ecs-clstr-gateway" {
  count = var.gateway ? 1 : 0
  min   = 1111
  max   = 9999

  keepers = {
    insttype_gw      = var.insttype_gw
    image_id         = var.ami_id
    user_data        = data.template_file.user_data_gateway[0].rendered
    root_volume_type = var.root_volume_type_gw
    root_volume_size = var.root_volume_size_gw
    ebs_volume_type  = var.ebs_volume_type_gw
    ebs_volume_size  = var.ebs_volume_size_gw
    ebs_encrypted    = var.ebs_volume_encrypt_gw ? 1 : 0
  }
}

resource "aws_launch_configuration" "lc-ecs-clstr-gateway" {
  count                = var.gateway ? 1 : 0
  name                 = "${local.gateway_cluster}-${random_integer.lc-string-ecs-clstr-gateway[0].result}"
  image_id             = var.ami_id
  instance_type        = var.insttype_gw
  iam_instance_profile = var.ec2_profile_name
  key_name             = var.key_name
  security_groups      = [var.sg_ecs_gw_instance_id]
  user_data            = data.template_file.user_data_gateway[0].rendered

  lifecycle {
    create_before_destroy = true
  }

  root_block_device {
    volume_type           = var.root_volume_type_gw
    volume_size           = var.root_volume_size_gw
    delete_on_termination = var.root_delete_on_termination
  }

  ebs_block_device {
    device_name           = "/dev/xvdcz"
    volume_type           = var.ebs_volume_type_gw
    volume_size           = var.ebs_volume_size_gw
    encrypted             = var.ebs_volume_encrypt_gw
    delete_on_termination = var.ebs_delete_on_termination
  }
}
...
```

### Expected Behavior

We are in the process of upgrading from 0.11 to 0.12, we are using the same values for the resources. The expected behavior was to just to go to refreshing state but it is rebuilding the resources. 
### Actual Behavior

It is forcing a replacement for the resources. 
### Steps to Reproduce

We ran terraform 0.11 first and ran a terraform 0.12 plan over it. 
### Additional Context

+/- resource "random_integer" "lc-string-ecs-clstr-gateway" {
      ~ id      = "3055" -> (known after apply)
      ~ keepers = {
          - "ebs_encrypted"    = "1"
          - "ebs_volume_size"  = "100"
          - "ebs_volume_type"  = "gp2"
          - "image_id"         = "ami-"
          - "insttype_gw"      = "t2.medium"
          - "root_volume_size" = "40"
          - "root_volume_type" = "gp2"
          - "user_data"        = <<~EOT
                <SNIP>
        } -> (known after apply) # forces replacement

**Comment by danieldreier** [comment] 2020-04-10 22:24
Hello @ss-sierra-cedar! We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

This does look like a frustrating issue, but we aren't categorically treating all 0.11 -> 0.12 upgrade difficulties as bugs, and this issue tracker isn't a place where we are able to provide upgrade support outside of fixing bugs, because we have a small team and a large number of users. In this case, because there's a bit of logic in here, and you don't have log output, I can't clearly see that there's a bug in Terraform core vs expected changes between 0.11 and 0.12.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. When you post there, I encourage you to add log output to your description, and to simplify your reproduction case as much as possible to narrow in on exactly what 0.11 -> 0.12 changes might be causing this.

2. Alternatively, if you can provide a simplified, full example here of a terraform config that I can run to reproduce an issue in which valid 0.12 terraform code recreates a resource instead of updating it, I may be able to confirm that this is a defect in core or the AWS provider and get it on our backlog.

I'm going to close this for now, because I think the community forum is the right approach. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you're confident it's a bug and would rather work up a reproduction case here.

**Closed by danieldreier** 2020-04-10 22:24 UTC
