### ISSUE TITLE
Ability to pass terraform variable in backend prefix

### ISSUE THREAD

**Issue by mejuhi** [hashicorp/terraform#33639] opened 2023-08-07 08:06 UTC
### Terraform Version

```shell
Terraform v1.3.8
hashicorp/google v4.72.0
hashicorp/google-beta v4.72.0
```

### Use Cases

Ability to configure backend path based on terraform variable at run time.

for eg: right now the configuration on main.tf looks something like this 
```
terraform {
  backend "gcs" {
    prefix = "states/int/v1/int-name"
  }
}
```

### Attempted Solutions

tried using terraform variable, but it is not accepted as acceptable syntax touse variables in backend path

### Proposal

would be nice if we could use something like this:

```
terraform {
  backend "gcs" {
    prefix = "states/int/v1/var.int"
  }
}
```

**Comment by jbardin** [comment] 2023-08-07 12:37
Duplicate of #17288

**Closed by jbardin** 2023-08-07 12:37 UTC
Labels: enhancement, new
