### ISSUE TITLE
random_integer result attribute string instead of int?

### ISSUE THREAD

**Issue by dawidpogorzelski** [hashicorp/terraform#20886] opened 2019-04-01 15:44 UTC
### Terraform Version

```
0.11.13
```

### Terraform Configuration Files

```hcl

resource "random_integer" "servername" {
  min = 1
  max = 9999
}

resource "google_compute_disk" "disk" {
  name  = "${format("foo-${lookup(var.somevar, "short_name")}-g%04d-data", random_integer.servername.result)}"
  type  = "pd-ssd"
  size  = 256
}
```
### Expected Behavior

I expected google_compute_disk to be created with the following name 
```
foo-bar-g0656-data
```

### Actual Behavior

* google_compute_disk.disk: Error creating Disk: googleapi: Error 400: Invalid value for field 'resource.name': 'foo-bar-g%!d(string=0656)-data'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid

**Comment by apparentlymart** [comment] 2019-04-01 21:15
Hi @dawidpogorzelski! Sorry for this strange behavior and thanks for reporting it.

In Terraform v0.11 unfortunately the provider protocol is built in such a way that provider results can only be strings, lists of strings, or maps of strings, with the provider converting everything to those constraints after it applies the requested change. This behavior is therefore the result expected by design, but for sure it is counter-intuitive and particularly unfortunate in this context where the `format` function is also currently unable to perform an automatic conversion.

To work around this for now, I think adding zero to the result should cause a numeric conversion:

```hcl
  name  = "${format("foo-${lookup(var.somevar, "short_name")}-g%04d-data", random_integer.servername.result + 0)}"
```

The addition operator knows it needs to convert both of its arguments to numbers and so it will do so, while the 0.11 implementation of `format` unfortunately just expects values to arrive in the correct type and does not perform automatic conversions.

The better news is that both of these problems are fixed already in the `master` branch for inclusion in the forthcoming v0.12.0 release: providers are now able to return values of any type supported in the language, including numbers directly, _and_ [the `format` function](https://www.terraform.io/docs/configuration/functions/format.html) interprets `%d` as a request to first convert the argument to an integer (if it isn't already) and _then_ format it. The release cycle for v0.12.0 is ongoing as I write this, so beta2 will be coming soon and eventually the final release.

Because this is already fixed in the `master` branch, I'm going to close this out. Thanks again for reporting this!

**Closed by apparentlymart** 2019-04-01 21:15 UTC
Labels: bug, config
