### ISSUE TITLE
Support renaming / moving resources within the state

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#591] opened 2014-11-21 07:29 UTC
I refactored some of my configuration into a module.  This destroyed everything in my root module and re-created it.

This might be acceptable, albeit annoying.  However if that's the case there's a second issue.

It'll attempt to create the new security group from the module first and then destroy the old one.  However that'll cause duplicate security group errors from AWS.

**Comment by ketzacoatl** [comment] 2015-03-28 05:54
My workflow also includes various tricks and hacks to work around `terraform apply` wanting to destroy my resources as they grow and evolve in my attempts to apply better practices through Terraform. On quite a few instances I have even modified the state file to simplify the work in migrating/renaming/etc.

Having first-class support in Terraform, for renaming/migrating/exporting/importing resources would be fantastic!

**Comment by mitchellh** [comment] 2015-05-08 02:07
This should be fixed in 0.5

**Comment by toddmichael** [comment] 2015-05-20 23:50
@mitchellh forgive my ignorance here, but how is this fixed 0.5.0?  I've just learned to appreciate the magic of modules and am trying to migrate existing mess over to that.  When I run `terraform plan` in my new module driven configuration directory the output suggests that it's going to newly create everything.  If I run `terraform plan -state=/path/to/existing_terraform.tfstate` the output suggests its going to destroy and recreate everything.  I looked through closed issues related to modules, but wasn't able to find anything.

**Comment by ketzacoatl** [comment] 2015-05-29 17:25
@toddmichael, You might be able to work this out by careful use of the `lifecycle` block ([doc](http://www.terraform.io/docs/configuration/resources.html#lifecycle)).

It isn't pretty.. but another option to do this type of migration with existing infrastructure.. run this elsewhere, get the `.tfstate` file that comes out, and then use that to update the `.tfstate` you have for the production environment.. you would want need to do a lot of moving stuff around to make this work.

**Comment by phinze** [comment] 2015-07-10 18:31
Reopening this since we could still use a first class "migrate" or "rename" operation to support config rearranging without resource replacement.

**Comment by clumsysnake** [comment] 2015-09-28 15:14
+1.

terraform rename <resource_type> <old identifer> <new identifier>
terraform rename aws_security_group olddepartment newdepartment

**Comment by josephholsten** [comment] 2015-09-30 22:04
Perhaps we could rename this to "support renaming resources"? Anyone feeling up to spiking an implementation to see what it would look like?

**Comment by jasonkuhrt** [comment] 2015-10-01 14:51
Could we leverage a VCS diff to automate tracking the state remapping? Sounds hairy, but before Terraform existed the problem it solves did too.

**Comment by conorgil** [comment] 2015-11-19 18:19
Any update on the status of this issue? Renaming resources when trying to migrate to using modules is really causing lots of problems for my team.

**Comment by hd-deman** [comment] 2015-12-02 11:42
@mitchellh ping

**Comment by phinze** [comment] 2015-12-04 13:02
This is definitely still an issue on our radar. Today resource renames can be performed by advanced users by cracking open the state JSON and shuffling things around. Terraform should be able to do this work for us.

**Comment by apparentlymart** [comment] 2015-12-04 20:54
This seems to have the same kinda of UX trickiness as the idea of importing external resources to be managed by terraform (#581): namely that both the state and the config need to be updated at once, and Terraform currently knows how to update its state but it doesn't know how to update a user-provided configuration.

Perhaps a common building block for these would be a `gofix`-like infrastructure that allows mechanical adjustments to Terraform configs while otherwise preserving their structure. If the community is willing to embrace [the `hclfmt` conventions](https://github.com/fatih/hclfmt) to the same extent as the Go community embraced `go fmt`, then having Terraform auto-generate or update portions of config should be feasible and effective.

**Comment by phinze** [comment] 2015-12-05 00:00
Bingo! The amazing work @fatih kicked off for us in `hcl`-land enables us to write config, which was a major barrier to config portions of import and rename.

I think rename can still be valuable as a state-only operation, which is what I was picturing as an initial implementation. I still think that should be the first goal, but getting to the point where Terraform can shift your config around for you as well is going to be amazing.

**Comment by fwisehc** [comment] 2016-05-19 01:56
@phinze - Any progress on this?  Modifying to json by hand is tricky particularly with the equality checks between remote and cached versions.

**Comment by iroller** [comment] 2016-06-30 18:59
Also interested in being able to rename/refactor modules and keep the resources unchanged.

**Comment by stack72** [comment] 2016-07-27 01:20
hi all

Terraform 0.7 has support for moving items in state. This is from the cli help:

```
% terraform state mv --help                                                                                    
Usage: terraform state mv [options] ADDRESS ADDRESS

  Move an item in the state to another location or to a completely different
  state file.

  This command is useful for module refactors (moving items into a module),
  configuration refactors (moving items to a completely different or new
  state file), or generally renaming of resources.

  This command creates a timestamped backup of the state on every invocation.
  This can't be disabled. Due to the destructive nature of this command,
  the backup is ensured by Terraform for safety reasons.

  If you're moving from one state file to a different state file, a backup
  will be created for each state file.

Options:

  -backup=PATH        Path where Terraform should write the backup for the original
                      state. This can't be disabled. If not set, Terraform
                      will write it to the same path as the statefile with
                      a backup extension.

  -backup-out=PATH    Path where Terraform should write the backup for the destination
                      state. This can't be disabled. If not set, Terraform
                      will write it to the same path as the destination state
                      file with a backup extension. This only needs
                      to be specified if -state-out is set to a different path
                      than -state.

  -state=PATH         Path to a Terraform state file to use to look
                      up Terraform-managed resources. By default it will
                      use the state "terraform.tfstate" if it exists.

  -state-out=PATH     Path to the destination state file to move the item
                      to. This defaults to the same statefile. This will
                      overwrite the destination state file.
```

this should solve the issue going forward :)

Paul

**Closed by stack72** 2016-07-27 01:20 UTC
Labels: core, enhancement

**Comment by davedash** [comment] 2016-07-27 04:23
What format is the `ADDRESS`?  I've seen multiple types of `ADDRESS` used on the CLI.

**Comment by conorgil** [comment] 2016-07-27 18:43
Awesome! Does this support remote state files? We are using S3 right now. Would we have to copy files locally for this command to work?

**Comment by counterbeing** [comment] 2016-11-01 03:40
@davedash ADDRESS is something like `aws_s3_bucket.my_fancy_bucket`

**Comment by apparentlymart** [comment] 2016-11-01 04:15
@conorgil it should work as long as you enable remote state before executing the state mgmt commands.

**Comment by RichardBronosky** [comment] 2017-02-08 19:01
I just confirmed:
1. It works with the S3 remote state backend.
1. The `ADDRESS` needed to reference an existing resource is that which is revealed via `terraform plan`
1. You can rename a defined resource to a yet-to-be-defined name

**Comment by Lewiscowles1986** [comment] 2019-11-13 11:09
Is this still the best known way to manage? A rename key on resources I'd think would be as-good. It would be n+1 to check the name provided and the renamed key. I suppose the caveat would then be that users need to update source code so that after successful run rename becomes name.
