### ISSUE TITLE
Missing Terraform version 1.6.5 in APT repository

### ISSUE THREAD

**Issue by cesarjorgemartinez** [hashicorp/terraform#34326] opened 2023-11-29 17:22 UTC
### Terraform Version

```shell
Terraform 1.6.5
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

None

### Expected Behavior

get 1.6.5 version

### Actual Behavior

Missing 1.6.5 version

### Steps to Reproduce

terraform --version
Terraform v1.6.4
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.6.5

sudo apt-get update
sudo apt-cache madison terraform | grep 1.6.5

### Additional Context

None

### References

None

**Comment by apparentlymart** [comment] 2023-11-29 17:53
Hi @cesarjorgemartinez,

There is currently a known fault with the Apt and RPM repositories which is preventing them from synchronizing with the latest releases. The HashiCorp release engineering team is working on it, although since I'm not on that team myself I don't have any more details to share at the moment.

I recommend staying on Terraform v1.6.4 until the problem is repaired and the new version becomes available.

**Comment by liamcervante** [comment] 2023-11-30 15:25
Hi @cesarjorgemartinez, this should be fixed now. Please leave a comment here if you have further problems.

**Closed by liamcervante** 2023-11-30 15:25 UTC
Labels: bug, new
