### ISSUE TITLE
Terraform v1.1.0 crashes when a for_each in a root module calls a child module containing a for_each

### ISSUE THREAD

**Issue by lepagea01** [hashicorp/terraform#30139] opened 2021-12-10 17:58 UTC
### Terraform Version
```
Terraform v1.1.0
on darwin_arm64
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.29
+ provider registry.terraform.io/hashicorp/azuread v2.12.0
+ provider registry.terraform.io/hashicorp/azurerm v2.88.1
+ provider registry.terraform.io/microsoft/azuredevops v0.1.8
```

### Terraform Configuration Files
_Root module:_
```
module "snowflake_provisioned_user" {
  source = "../../modules/snowflake-provisioned-user"
  providers = {
    snowflake.securityadmin = snowflake.securityadmin
  }

  for_each = { for user in local.snowflake_users : user.mail => user }

  common_roles                = [module.snowflake_account.user_role_name]
  data_retention_time_in_days = var.data_retention_time_in_days
  default_warehouse_name      = module.snowflake_account.user_warehouse_name
  user                        = each.value
}

```
_Child module:_
```
resource "snowflake_schema_grant" "all" {
  provider = snowflake.securityadmin
  for_each = toset(local.schema_privileges)

  database_name = snowflake_database.database.name
  schema_name   = "PUBLIC"
  privilege     = each.key
  roles         = [snowflake_role.role.name]
  shares        = []
}
```

### Debug Output
Please find below the crash report produced by terraform (plan operation) as well as some preceding lines:
```
2021-12-10T12:36:09.462-0500 [TRACE] GRPCProvider: ReadResource
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-conn-query [query SHOW GRANTS OF ROLE "PROVISIONEDUSER" err <nil> duration 116.731791ms args {}]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-rows-next [err <nil> duration 3µs]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-rows-next [err <nil> duration 1.583µs]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-rows-next [err <nil> duration 1.042µs]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-rows-next [err <nil> duration 1.042µs]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-rows-next [err <nil> duration 1µs]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-rows-next [err <nil> duration 1.125µs]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [INFO]  provider.terraform-provider-snowflake_v0.25.29: 2021/12/10 12:36:09 [DEBUG] sql-rows-next [err EOF duration 166ns]: timestamp=2021-12-10T12:36:09.466-0500
2021-12-10T12:36:09.466-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to refreshState for module.snowflake_provisioned_user["user@someDomain"].snowflake_role_grants.role_grants["PROVISIONEDUSER"]
2021-12-10T12:36:09.466-0500 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for module.snowflake_provisioned_user["user@someDomain"].snowflake_role_grants.role_grants["PROVISIONEDUSER"]
2021-12-10T12:36:09.466-0500 [TRACE] vertex "module.snowflake_provisioned_user[\"user@someDomain\"].snowflake_role_grants.role_grants[\"PROVISIONEDUSER\"] (orphan)": visit complete
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 894 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x88
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x20
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:44 +0xe0
panic({0x102517a00, 0x103cd4910})
        /usr/local/go/src/runtime/panic.go:1038 +0x21c
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0x0, {{}, 0x4d, {0x140001e0e58, 0x16}, {0x14000784d87, 0x3}}, {0x14000b82080, 0x1, 0x4})
        /Users/distiller/project/project/internal/instances/expander.go:392 +0x44
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x0, {0x14000e32ca0, 0x0, 0x0}, {{}, 0x4d, {0x140001e0e58, 0x16}, {0x14000784d87, 0x3}}, ...)
        /Users/distiller/project/project/internal/instances/expander.go:387 +0x26c
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x14000117728, {0x14000e32ca0, 0x1, 0x1}, {{}, 0x4d, {0x140001e0e58, 0x16}, {0x14000784d87, 0x3}}, ...)
        /Users/distiller/project/project/internal/instances/expander.go:385 +0x204
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0x140008a6ce0, {{}, {0x14000e32ca0, 0x1, 0x1}, {{}, 0x4d, {0x140001e0e58, 0x16}, {0x14000784d87, ...}}})
        /Users/distiller/project/project/internal/instances/expander.go:157 +0x11c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0x1400242e250, {0x102979620, 0x1400216e0e0})
        /Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:204 +0x160
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0x1400242e250, {0x102979620, 0x1400216e0e0})
        /Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x640
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x1400242e250, {0x102979620, 0x1400216e0e0}, 0x2)
        /Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x94
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14001413ce0, {0x102979620, 0x1400216e0e0}, {0x12b989f40, 0x1400242e250})
        /Users/distiller/project/project/internal/terraform/graph_walk_context.go:133 +0x9c
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x102840300, 0x1400242e250})
        /Users/distiller/project/project/internal/terraform/graph.go:74 +0x244
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14000fc0000, {0x102840300, 0x1400242e250}, 0x140013ae300)
        /Users/distiller/project/project/internal/dag/walk.go:381 +0x31c
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /Users/distiller/project/project/internal/dag/walk.go:304 +0xe0c
```

### Expected Behavior
Terraform plan resumes.

### Actual Behavior
Terraform plan crashes.

In details, I have this root module that calls a child module, _snowflake-provisioned-user_, for each relevant user. The child module will provision various object in Snowflake such as a user database and various privileges. For instance, default privileges on the PUBLIC schema of the user database. Such privileges are hard-coded in a list local to the child module while the user list is derived from a variable of the parent module. The code snippets above illustrate the whole idea.

Terraform plan actually crashes when I remove a user from the user list, which would lead the child module to drop related objects and privileges in Snowflake. When adding a user to the user list, everything works fine and I obtain the expected results. As for example, here's an instance available in the current state file:

```
module.snowflake_provisioned_user["user@someDomain"].snowflake_schema_grant.all["CREATE EXTERNAL TABLE"]
```
The problem occurs when I remove the user ("user@someDomain" in the example) from the user list.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan -var-file=...`

### Additional Context
To the best of my knowledge, prior to v1.1.0, say last week, things seemed OK.

Note that I have tried to isolate the problem. For instance, the child module manages multiple objects in Snowflake and if I comment the part of the child module having the ```for_each```, things run smoothly. ```for-each``` is key here. I have tried replacing such a ```for_each``` with a ```count```, alas, without any success. 

Note also that the issue is not related to the ```snowflake_schema_grant``` resource itself. Other resource types will make terraform crash as soon as a ```for_each``` is involved.

Please, let me know if I can forward additional material or provide answers to further questions.

Regards,

AL

__Update 12/10/2021__
Far from me the idea of misleading anyone but I ran my configuration on an Ubuntu agent in Azure DevOps and terraform crashes as well. Since this agent normally runs terraform v1.0.11 (as per [these specifications](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)), the issue is not especially related to v1.1.0.

**Comment by crw** [comment] 2021-12-11 00:51
Thanks for the report, @lepagea01. At this time, we believe this to be a duplicate of https://github.com/hashicorp/terraform/issues/30110. If you think this is in error, please re-open and let me know. We appreciate your report, it helps deepen our understanding of this issue.

**Closed by crw** 2021-12-11 00:51 UTC
Labels: bug, new

**Comment by lepagea01** [comment] 2021-12-11 14:58
Hi,

Yes, I read issue hashicorp/terraform#30110 prior to logging mine and though things seemed very similar, I wasn't sure then whether the problem somehow had to do with the providers used (aws vs azuread + snowflake). You are most likely right and  will look carefully for PRs and releases linked to issue hashicorp/terraform#30110.

Now, if it can help in your investigations, please note that I dug a little bit deeper and tried various tests. For instance:

- Removing any item from the inner loop, i.e. ```for_each``` in the child module (say, dropping a privilege in my use case) works fine and terraform produces a plan successfully.
- Removing at once all the resources provisioned by the child module, say, by commenting its call in the parent module, works as well: the plan produced will properly list all the resources that will be destroyed.

Thank you for your time and feedback.

AL
