### ISSUE TITLE
Improve error messages regarding missing keys in self.triggers when using provisioner

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/terraform#27969] opened 2021-03-03 18:52 UTC
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "null_resource" "demo" {
  triggers = {
    foo = "this is a typo"
  }
  provisioner "local-exec" {
    command = "echo ${self.triggers.bar}"
  }
}
```

### Debug Output
Not applicable

### Panic Output
Not applicable

### Expected Behavior
Error message should contain the name of the resource or some other information useful in identifying the error.

### Actual Behavior

```
$ terraform apply
Error: Missing map element: This map does not have an element with the key "bar".
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None

### References
None

**Comment by apparentlymart** [comment] 2021-03-05 01:11
Thanks for reporting this, @dekimsey!

As far as I can tell, this error message is _originating_ in a context where it does have the necessary information we typically expect to see in a Terraform diagnostic message, over in [the HCL repository](https://github.com/hashicorp/hcl/blob/main/ops.go#L231-L238). Given that, it seems like the problem here is not with the generation itself but with some intermediate system inadvertently discarding all of the metadata in favor of a plain string representation of the error message.

With that said then, I think addressing this would involve looking through everything in the call chain involved in evaluating that `command` argument to look for a case where a function is incorrectly transforming a "diagnostics" object into a Go `error` value, and thus forcing it to be reduced to a contextless string.

There were some changes to how the built-in provisioners interact with the rest of Terraform in the forthcoming v0.15 release though, so it would probably be worth first trying to reproduce this in v0.15.0-beta1 in case those changes had a bonus of removing whatever layer was causing this degraded error message. :crossed_fingers:

**Comment by apparentlymart** [comment] 2021-03-05 01:12
Since the presentation of this message doesn't seem to match our design intent (the system generating the message seems to be _trying_ to return a rich message with source location information) I'm going to reclassify this one as a bug.

**Comment by alisdair** [comment] 2021-03-05 13:07
This is indeed fixed in a build from the main branch. Here's the error now:

```
╷
│ Error: Missing map element
│
│   on main.tf line 6, in resource "null_resource" "demo":
│    6:     command = "echo ${self.triggers.bar}"
│     ├────────────────
│     │ self.triggers is map of string with 1 element
│
│ This map does not have an element with the key "bar".
╵
```

**Closed by alisdair** 2021-03-05 13:07 UTC
Labels: bug, new, v0.14
