### ISSUE TITLE
0.12.16 breaks conditional defined variables when variables are mutually exclusive

### ISSUE THREAD

**Issue by GeKasap** [hashicorp/terraform#23445] opened 2019-11-21 09:32 UTC
### Terraform Version

```
Terraform v0.12.16
```

### Terraform Configuration Files

https://github.com/GeKasap/terraform-google-network/blob/master/network.tf
```hcl
resource "google_compute_firewall" "vpc_firewall_allow" {
....
  source_tags = var.allow_rules[count.index].name == "source_tags" ? var.allow_rules[count.index].list : []
  source_ranges = var.allow_rules[count.index].name == "source_ranges" ? var.allow_rules[count.index].list : []
...
}
```
### Debug Output

https://gist.github.com/GeKasap/8031af3a2856e51828aa59cede5e877c
### Expected Behavior

This should work as `case` and only one variable should be set. The rest should be treated as undefined variables. This code was to avoid writing separate blocks of firewall rules e.g. for `source_tags` and `source_ranges`. This code was working fine with `Terraform 0.12.0`. TF in that case should check only the variables that have a value assigned.
### Actual Behavior

These variables are mutually exclusive, but the tf is not checking if a value is assigned or not, the mutual exclusive check is done before. I have also updated my code to assign null values instead of empty lists, but the behavior remains the same. According to https://www.terraform.io/docs/configuration/expressions.html#null 
```
null: a value that represents absence or omission. If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met. 
```

```hcl
resource "google_compute_firewall" "vpc_firewall_allow" {
....
  source_tags = var.allow_rules[count.index].name == "source_tags" ? var.allow_rules[count.index].list : null
  source_ranges = var.allow_rules[count.index].name == "source_ranges" ? var.allow_rules[count.index].list : null
...
}
```

**Comment by jbardin** [comment] 2019-11-21 14:06
Hi @GeKasap,

The second form you've shown would be more correct, since assigning an empty value could be considered assignment, and subject to the "conflicts with" check. This part of the validation happens in the provider sdk, can you confirm if your google provider version changed as well, or was the only change the Terraform binary itself?

**Comment by GeKasap** [comment] 2019-11-22 14:23
Thanks for the reply. Yes and now.
I mean I have tried both with the old google plugin version `2.20.0` and the new one `3.0.0` and the behavior is the same. With terraform `0.12.0` works but with `0.12.16` fails.

**Comment by jbardin** [comment] 2019-11-22 14:38
Thanks @GeKasap! I'll verify if core is doing everything correctly and transfer this to he provider sdk if it looks correct here.

**Comment by jbardin** [comment] 2019-11-22 22:48
Hi @GeKasap,

The conditionals as written (with `null`) do not send anything directly to the provider that would fail this validation. It looks like a likely possibility here is that the provider is writing out something to the conflicting fields, since they are both also marked as `Computed`. I'm going to bump this over to them, since both core and the SDK appear to be working as intended.

**Closed** 2019-11-22 23:20 UTC
Labels: provider/google
