### ISSUE TITLE
terraform_remote_state for gcs backend is not workspace-aware.

### ISSUE THREAD

**Issue by majelbstoat** [hashicorp/terraform#17153] opened 2018-01-22 01:37 UTC
### Terraform Version
Terraform v0.11.2
+ provider.google v1.5.0

### Terraform Configuration Files
When using `terraform workspace select staging`, setting the backend in  `common.tf` like this:

```hcl
terraform {
  backend "gcs" {
    project = "app"
    bucket  = "my-bucket"
    prefix  = "terraform/state"
  }
}

output "my_value" {
  value = "something"
}
```
Creates `gs://app/my-bucket/terraform/state/staging.tfstate` as expected

When trying to reference that in another location, using the same workspace:

```hcl
data "terraform_remote_state" "common" {
  backend = "gcs"

  config {
    project = "app"
    bucket  = "my-bucket"
    prefix  = "terraform/state"
  }
}

resource "some_resource" "name" {
  val = "${data.terraform_remote_state.common.my_value}"
}
```

There is an error: `Resource 'data.terraform_remote_state.common' does not have attribute 'my_value'`.

### Expected Behavior
This output should have been found and correctly referenced.

### Actual Behavior
The value cannot be found.

### Additional Context
This can be fixed by using the full path, instead of the prefix. For example:

```hcl
data "terraform_remote_state" "common" {
  backend = "gcs"

  config {
    bucket = "my-bucket"
    path   = "terraform/state/${terraform.workspace}.tfstate"
  }
}

resource "some_resource" "name" {
  val = "${data.terraform_remote_state.common.my_value}"
}
```

works as expected. However, `path` is deprecated, and `prefix` should be used instead.

**Comment by jbardin** [comment] 2018-01-22 22:28
Hi @majelbstoat,

The workspace has to be explicitly passed to the `terraform_remote_state` data type, in order for it to be possible to access a different remote workspace name.

```
data "terraform_remote_state" "common" {
  backend = "gcs"
  workspace = "${terraform.workspace}"

  config {
    project = "app"
    bucket  = "my-bucket"
    prefix  = "terraform/state"
  }
}
```

The `teraform-provider` specific docs however do need to be updated to reflect the change from `environment` to `workspace`.

**Comment by majelbstoat** [comment] 2018-01-22 23:30
Fantastic, thanks so much. Will check tonight and confirm.

**Comment by downspot** [comment] 2018-02-08 17:52
Tried changing from environment to workspace but it doesn't work:

Config:
```data "terraform_remote_state" "network" {
  backend       = "s3"
  workspace   = "${terraform.workspace}"
  config {
    bucket = "${var.state_bucket}"
    key    = "terraform.tfstate"
    region = "${var.region}"
  }
}
```

Error:
```
1 error(s) occurred:

* data.terraform_remote_state.network: : invalid or unknown key: workspace
1 error(s) occurred:

* data.terraform_remote_state.network: : invalid or unknown key: workspace
```

**Comment by downspot** [comment] 2018-02-08 19:19
I'll open a ticket for S3 but basically on the initial creation of my infrastructure the local state file is being created properly but the remote isn't, it winds up with a blank state as such:

```
{
    "version": 3,
    "serial": 1,
    "lineage": "9eaeb21e-34c0-492b-aa75-44bab92773cb",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```

**Comment by nycjv321** [comment] 2018-07-08 03:57
@midN I'm able to reproduce it with s3 as well. Should this be documented as a separate issue? btw... Thank you for the workaround!

**Comment by gswallow** [comment] 2018-10-24 20:07
The documentation on this is really poor: https://www.terraform.io/docs/providers/terraform/d/remote_state.html

Nowhere on this page does it say to configure a workspace.

**Comment by mildwonkey** [comment] 2020-08-27 15:58
I am going to close this issue; both the remote backend and documentation have changed quite a bit since the original issue was opened.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!

**Closed by mildwonkey** 2020-08-27 15:58 UTC
Labels: backend/gcs, documentation
