### ISSUE TITLE
Lock Files, Plugin Cache and using several architectures fails `terraform init`

### ISSUE THREAD

**Issue by LDVSOFT** [hashicorp/terraform#29958] opened 2021-11-16 23:41 UTC
So, since I am using several stacks of Terraform configuration quite regularly and their plugins in use are mostly the same, I didn't want providers to be downloaded for each one, so I enabled plugin cache directory (see below). Also, at some point in time I started using lock files instead of relying on using `version = "= x.y"` to always reuse the same version.

Since we use Terraform on several machines, and some developers are using different architectures (I'm using Linux Amd64, my colleague is using Darwin Amd64, more architectures might come with M1), I expect lock files to support being used on several architectures. Documentation states that even though `h1`s only for current architectures are populated, since `zh`s are always present they are enough to check either plugin for a new architecture already matches known hashes, so that Terraform can append new `h1` hash on a first download. Sounds great, actually (or one can assume we can remember `h1`s directly, but it's not my expertise).

The only problem is that, somehow, Terraform always does a little different thing for me:
1. When I run `terraform init` that resolved to a plugin version that is not in the cache, Terraform actually does it's job: it downloads the plugin, populates the lock file with all `zh`s and a single `h1`. If I will use this lock file on a different machine everything works as expected.
2. When I run `terraform init` for the same plugin version in another directory, it is accessed from the cache, **and only h1 hash is written into the lock file**.
3. When my colleague will run `terraform init` on the second stack with my lock file (if I commit it into VCS), they will get an error.

As I have found out, instead of trying to use different hardware I can emulate the behaviour by just running `terraform providers lock -platform=darwin_amd64`, where platform can be anything but not the current one.

### Terraform Version
```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

Also I've seen this on a lot of versions, since, I think, around 0.15.

### Terraform Configuration Files
There is nothing relevant beyond version requirements:
```terraform
terraform {
  required_version = ">= 1.0.4"
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.1"
    }
  }
}
```

Relevant `~/.terraformrc`:
```terraform
plugin_cache_dir = "$HOME/.cache/terraform/plugin-cache"
```

### Debug Output
[This Gist includes all logs](https://gist.github.com/LDVSOFT/a479c71855bdd8b964d725fd93d9e146)

### Expected Behavior
`terraform init` should populate lock file well enough for future use or switch to redownloading plugin in case lock file doesn't provide enough information.

### Actual Behavior
Terraform disrupts developer experience by forcing to do `terraform providers lock -platform=…` with every platform in use so that `terraform init` wouldn't fail in the future.

### Steps to Reproduce
_Here I assume that I'm running on linux_amd64, and I'm using darwin_amd64 and darwin_arm64 as different achitectures. However, I experienced this bug with other combinations, I don't think exact platforms are relevant here._
1. Create `~/.terraformrc` file with line above, create given directory / check that it's empty.
2. Create an empty directory `a` with `versions.tf` file as above.
3. `terraform init` in it. Should work like a charm.
4. Open `.terraform.lock.hcl` to see that there are a lot of hash lines.
5. `terraform providers lock -platform=darwin_amd64`. Works, lock file is updated with a new `h1` hash.
5. Create an empty direcory `b` with the same `versions.tf` file.
6. `terraform init` in it. Should work.
7. However, `terraform.lock.hcl` only contains a single `h1` hash.
8. `terraform providers lock -platform=darwin_arm64`. **Fails**:
   ```
   ╷
   │ Error: Could not retrieve providers for locking
   │
   │ Terraform failed to fetch the requested providers for darwin_arm64 in order
   │ to calculate their checksums: some providers could not be installed:
   │ - registry.terraform.io/hashicorp/null: the current package for
   │ registry.terraform.io/hashicorp/null 3.1.0 doesn't match any of the
   │ checksums previously recorded in the dependency lock file.
   ╵
   ```

### Additional Context
I am sorry, this can be already discussed in another Cache+Lock-related issue, but I haven't seen exactly my case being described.  I am opening this one with the exact reproducible case.

### References
For a lot of time I was following #28041 for this problem, but it seems to me it has lost the direction I am interested in.

**Comment by apparentlymart** [comment] 2021-11-17 01:21
Hi @LDVSOFT! Thanks for raising this.

Unfortunately what you've described here is the current expected behavior of Terraform: if you activate any configuration that prevents Terraform from accessing the origin registry then it won't have access to the official signed checksums from the registry and thus it must conservatively only record what it can determine from the information already available locally.

In your case, you've enabled the plugin cache and therefore effectively disabled Terraform accessing the registry to reinstall the same version of a previously-seen provider, which causes this problem.

`terraform providers lock` is the current way to get a comprehensive set of checksums in any situation where you can't or don't want to use the default provider installation behaviors, which would normally be able to populate the lock file manually. I think #27388 is covering that concern.

Towards the end of your comment here you also mentioned `terraform providers lock` returning an error, which does seem different than what was discussed before. Based on your reproduction steps I think that happened because in your step 5 you only included `darwin_amd64`, and so you generated a lock file that only supports that platform. To get a successful result from that series of steps you would need to include all of the different platforms your team uses in your initial `terraform providers lock` call, which would then generate a sufficient lock file for everyone on your team.

**Comment by LDVSOFT** [comment] 2021-11-17 15:01
Thank you, @apparentlymart, for explaining the current situation for me.

I find it a bit misleading that the _cache_ for plugins _prevents_ accessing the origin registry, it's strange. A lot of other tools use dependency caching by default and also support version or/and integrity locking (Maven, Gradle, Pip, NPM, Yarn, Cargo come to my mind), but when those miss out on information they don't hesitate accessing the origin. Maybe just store validated hashes (`zh`s for now) in the cache too? In my eyes, the cache is helping with storage space & network traffic and is not a source of trust for any user beyond local machine, so it will fit there. 

I don't know how exactly Terraform operates it's cache from a security standpoint (especially since the whole process of unzipping the distribution), so I don't insist on anything.

At least the docs can be improved with a notice about the behaviour: as opposed to `provider_installation` that obviously intervents into where plugins are installed from. Users may end up with very non-trivial problems from lock files and will blame those, not the cache.

**Comment by Phylu** [comment] 2021-11-25 11:07
I ran in the very same issue during a different workflow in a similar situation:
- We have different repositories which all use the same provider version. To prevent re-downloading it for every repository, I am using the `plugin_cache_dir`.
- We have 4 different architectures (`darwin_amd64`, `darwin_arm64`, `linux_adm64` & `linux_arm64`), for local developers and our pipeline servers.

On a version update
- we update the `versions.tf` file
- Run `terraform init --upgrade`
- Run `providers lock -platform=darwin_amd64 -platform=darwin_arm64 -platform=linux_arm64 -platform=linux_amd64`.

Then providers lock command fails with `Terraform failed to fetch the requested providers for darwin_arm64 in order to calculate their checksums`.

I agree with @LDVSOFT here. It would be great to have the possibility to use the `providers lock` command in addition with the plugin cache directory.

**Comment by apparentlymart** [comment] 2021-11-30 00:32
Based on the discussion here so far, it seems like there may be a more tactical fix that we could employ to smooth out this `terraform providers lock` workflow in the meantime, until the registry can be updated to support the new-style hashing scheme:

Based on my testing, it seems like `terraform providers lock` can only add new checksums to an _existing_ lock entry if there's already a saved checksum matching each of the downloaded packages. That means it's able to "upgrade" an existing entry from the `zh:` scheme to the `h1:` scheme, but it fails with the error discussed above if there is no existing `zh:` checksum to correlate with.

That rule makes sense for the "trust on first use" (TOFU) paradigm of `terraform init`, but it's not so obviously a correct behavior for `terraform providers lock` whose explicit purpose is to add new checksums to the lock file. Instead, it seems to me like `terraform providers lock` should do as it's told and just add the requested package checksums, regardless of what was already in the file for that provider before.

A detail here is to think through what extra output, if any, `terraform providers lock` ought to produce in that case. In the case where there was _no_ existing entry for a particular provider this command will happily record an entirely new set of checksums without any special notice, and so arguably it could do the same for newly-discovered checksums of an existing provider, but since this behavior would differ from the TOFU behavior of `terraform init` it might be better to be a bit more "chatty" in that situation and announce what happened:

```
hashicorp/null v3.1.0 for darwin_amd64 checksum not previously known; now recorded in the lock file
```

For consistency, it may be best for the command to be a little more chatty in general by saying _something_ about all of the packages it considers:

```
hashicorp/null v3.1.0 for linux_amd64 checksum already tracked in the lock file
hashicorp/aws v2.0.0 checksums recorded for all requested platforms
```

From a practical standpoint I do expect that most folks will not carefully inspect the output here, but in some environments there is a policy to be extra careful with adding new checksums to the lock file and so by prompting about it we at least give the _opportunity_ to notice that something unusual happened. While it would be possible to see _some_ information by looking directly at the diff for `.terraform.lock.hcl`, that just records an undifferentiated set of checksums and so can't explain where each of the new checksums came from.

---

I have a slightly shorter _contrived_ reproduction case here which I'm sharing just in the hope that it's useful to others who might work on this issue. This is not a realistic user pattern, but allows quickly getting into the same situation this issue is about without a bunch of fiddly system configuration.

First, create a Terraform configuration which refers to the `null` provider. For example:

```hcl
provider "null" {
}
```

In the same directory, create a `.terraform.lock.hcl` file with the following content:

```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/null" {
  version = "3.1.0"
  hashes = [
    "h1:invalid",
  ]
}
```

The `h1:invalid` here is standing in for the hash of the package for whatever platform the user initially ran `terraform init` on, which therefore doesn't cover any packages for other platforms.

In that directory, run `terraform providers lock` with any explicit platform selections you like:

```shellsession
$ terraform providers lock -platform=linux_amd64
- Fetching hashicorp/null 3.1.0 for linux_amd64...
╷
│ Error: Could not retrieve providers for locking
│ 
│ Terraform failed to fetch the requested providers for linux_amd64
│ in order to calculate their checksums: some providers could not be
│ installed:
│ - registry.terraform.io/hashicorp/null: the current package for
│ registry.terraform.io/hashicorp/null 3.1.0 doesn't match any of the
│ checksums previously recorded in the dependency lock file.
╵
```

If we were to implement the TOFU exception I described above, I'd expect `terraform providers lock` to instead just add the new checksums to the existing block in the lock file, preserving the existing ones:

```diff
--- .terraform.lock.hcl
+++ .terraform.lock.hcl
@@ -5,5 +5,6 @@
   version = "3.1.0"
   hashes = [
     "h1:invalid",
+    "h1:vpC6bgUQoJ0znqIKVFevOdq+YQw42bRq0u+H3nto8nA=",
   ]
 }
```

Of course, exactly what output the command would produce in the terminal in this case remains to be decided. I trust that if someone picks up this issue to work on they will try some different permutations and see what level of "chattiness" feels most appropriate and most consistent, and record that rationale as a comment in the implementation so that we can refer to it again in future.

**Comment by danielcompton** [comment] 2021-12-13 19:00
The docs for [dependency lock](https://www.terraform.io/docs/language/dependency-lock.html) say:

> If you install a provider from an origin registry which provides checksums that are signed with a cryptographic signature, Terraform will treat all of the signed checksums as valid as long as one checksum matches. **The lock file will therefore include checksums for both the package you installed for your current platform and any other packages that might be available for other platforms.**

I might be misunderstanding the docs, but it doesn't seem like this is currently happening? It seems like the lock file only gets checksums for other platforms when you run `terraform providers lock` with other platforms?

**Comment by apparentlymart** [comment] 2021-12-13 20:32
Hi @danielcompton,

The current provider registry protocol only returns checksums compatible with the `zh:` scheme, and so until there's a new version of the registry protocol which can return `h1:` checksums (which is a change outside the direct scope of Terraform CLI) there is no way to calculate those except to download the packages and calculate them client-side, which is what `terraform providers lock` does.

The automatic "upgrade" from an existing `zh:` to its corresponding `h1:` as described in that documentation section is the compromise to allow this to work with the current registry protocol in the common case where folks are installing directly from provider registries. Things get more complex when the original installation is from somewhere _other than_ an origin registry, because in that case Terraform doesn't even have access to the `zh:` checksums (they come from the origin registry, signed by the author), and so it can only record `h1:` checksums for exactly the packages it has access to.

**Comment by bflad** [comment] 2021-12-17 04:36
I ran into an almost identical situation as @jeff-french above in https://github.com/hashicorp/terraform/issues/29958#issuecomment-992603708, running `darwin_amd64` locally while attempting to use Terraform Cloud which is based on `linux_amd64`. I'm using a shared provider cache because I'm constantly working with a lot of various Terraform configurations and really do not want to re-download providers constantly. 

What really confused me was that none of the error messages were particularly helpful in pointing me in the right direction for solving the issue.

```console
$ cat .terraformrc
plugin_cache_dir = "/Users/bflad/.terraform.d/plugin-cache"

$ tree /Users/bflad/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/random/3.1.0/
/Users/bflad/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/random/3.1.0/
└── darwin_amd64
    └── terraform-provider-random_v3.1.0_x5

1 directory, 1 file

$ terraform init

Initializing Terraform Cloud...

Initializing provider plugins...
- Finding hashicorp/random versions matching "3.1.0"...
- Using hashicorp/random v3.1.0 from the shared cache directory

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform Cloud has been successfully initialized!

You may now begin working with Terraform Cloud. Try running "terraform plan" to
see any changes that are required for your infrastructure.

If you ever set or change modules or Terraform Settings, run "terraform init"
again to reinitialize your working directory.

$ cat .terraform.lock.hcl 
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/random" {
  version     = "3.1.0"
  constraints = "3.1.0"
  hashes = [
    "h1:rKYu5ZUbXwrLG1w81k7H3nce/Ys6yAxXhWcbtk36HjY=",
  ]
}

$ terraform apply
Running apply in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

To view this run in a browser, visit:
https://app.terraform.io/app/bflad-hashicorp/onedotonedemo-moved/runs/run-xGmjEfin46ajHgQr

Waiting for the plan to start...

Terraform v1.1.0
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:

Initializing Terraform Cloud...

Initializing provider plugins...
- Reusing previous version of hashicorp/random from the dependency lock file
- Installing hashicorp/random v3.1.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/random v3.1.0: the current package for
│ registry.terraform.io/hashicorp/random 3.1.0 doesn't match any of the
│ checksums previously recorded in the dependency lock file
╵

```

The `terraform init` command didn't provide any warning that I would not be able to use Terraform Cloud immediately. When receiving the `terraform apply` error, there was not an indication where this lock file was located (only the local init message mentions `.terraform.lock.hcl`) or to use the `terraform providers lock` command to potentially fix the issue. There was also no specific recommendation _how_ to fix this for the platform it was running on (Terraform Cloud's `linux_amd64`).

Maybe the checksum mismatch error could include some additional diagnostic information, such as:

```text
Error while installing hashicorp/random v3.1.0: the current package for
registry.terraform.io/hashicorp/random 3.1.0 doesn't match any of the
checksums previously recorded in the dependency lock file (.terraform.lock.hcl)

Use the `terraform providers lock` command to include all necessary
platforms where Terraform will be executed. Ensure the current platform,
linux_amd64, is included.
```

Deleting `.terraform.lock.hcl` and running `terraform providers lock -platform=darwin_amd64 -platform=linux_amd64` fixed my situation, given the current behaviors.

**Comment by Tensho** [comment] 2021-12-30 12:22
Have the same experience. Would be cool to have a `provider lock` suggestion in CLI output as @bflad mentioned above.

**Comment by LDVSOFT** [comment] 2022-05-20 09:10
Given that the core issue is in the registry API, is there a public tracker for it?

**Comment by crw** [comment] 2022-06-17 18:53
@LDVSOFT The Registry team does not have any public trackers visible for their issues. I often leave these core issues open as trackers, even though the fix may not live in this codebase.

**Comment by LDVSOFT** [comment] 2022-07-15 09:52
Don't you mind adding v1.2 tag too? Issue it still relevant.

**Comment by liamcervante** [comment] 2022-07-20 12:48
Hi everyone! I'm closing this issue now as the following changes have been made:

- `terraform providers lock` no longer checks the existing checksums, so it can now always be used to append checksums for the target platform to the lock file whereas before the lock file had to be removed and then recreated.
- `terraform init` will print a warning telling the user to use `terraform providers lock` if it fails to download the signed hashes from the registry.
- `terraform init` will now provide a direct link into the providers checksum verification documentation whenever it fails to initialise because of a checksum mismatch. This documentation contains an explanation and provides more context around when it is appropriate to use `terraform providers lock` to fix the failure.

I think these changes should address the points of action raised by @apparentlymart [here](https://github.com/hashicorp/terraform/issues/29958#issuecomment-982164017) and by @bflad [here](https://github.com/hashicorp/terraform/issues/29958#issuecomment-996431545). These changes in the next terraform release (v1.2.6).

Thanks!

**Closed by liamcervante** 2022-07-20 12:48 UTC
Labels: bug, confirmed, explained, v1.0, v1.1, v1.2

**Comment by LDVSOFT** [comment] 2022-07-24 09:38
I've got a couple of questions regarding recent actions:
* Could running `terraform providers lock` result in provider/modules update since it ignores checksums? It still follows chosen version, right?
* Also, @crw mentioned that this issue can be used a public ticket for  `h1` support in registry to solve the root cause (where lock files don't actually contain verifiable checksums before those are actually installed once), shouldn't it not be close / new issue opened up?
Anyway, thanks for all your work.

**Comment by crw** [comment] 2022-07-25 17:26
> Also, @crw mentioned that this issue can be used a public ticket for h1 support in registry to solve the root cause (where lock files don't actually contain verifiable checksums before those are actually installed once), shouldn't it not be close / new issue opened up?

@LDVSOFT thanks for the question. The scope of this issue seems to have wandered around a bit from the original request, but as I understand it the Terraform Core (CLI) team has resolved the issue as described and as is addressable by the Core team. With regards to the Registry portion of this thread, let me check with the Registry team. Possibly we can open a new tracker issue. Overall I would like to avoid opening Registry issues on the Core repository, however if there is a strong need we can do so.

**Comment by liamcervante** [comment] 2022-07-26 08:37
> Could running terraform providers lock result in provider/modules update since it ignores checksums? It still follows chosen version, right?

Yeah, `terraform providers lock` won't update the version even if it doesn't verify the checksums, the version is specified in a separate field in the file. If there is no existing lock file it will choose the latest possible based on the constraints. If there is a lock file then it uses the version specified in the lock file. You still need to run `terraform init -upgrade` if you want to update the lock file with a new version.

**Comment by wyardley** [comment] 2022-07-28 05:19
As of 1.2.6, I'm now seeing really messy warnings in our CI pipelines (which uses a plugin cache for speed while validating a bunch of configs), which are really annoying, especially since we don't even use lockfiles.

```

Initializing provider plugins...
- Finding hashicorp/google versions matching "4.29.0"...
- Using hashicorp/google v4.29.0 from the shared cache directory

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.


Warnings:

- Incomplete lock file information for providers

To see the full warning notes, run Terraform without -compact-warnings.
```

Note: we don't use lockfiles, but since Terraform has dismissed ideas of having an option to disable reading or generating them (e.g., https://github.com/hashicorp/terraform/issues/29760), there's no option to simply skip them.
