### ISSUE TITLE
 Incorrect attribute value type(Tuple)

### ISSUE THREAD

**Issue by judika03** [hashicorp/terraform#25049] opened 2020-05-27 03:37 UTC
### Terraform Version

```
... Terraform v0.12.21
```

### Terraform Configuration Files

```hcl
...
data "google_compute_instance_group" "ig" {
    count   = length(var.ig)
    name     = var.ig[count.index]
    zone = "us-central1-a"
    project = var.network_project == "" ? var.project : var.network_project
}

resource "google_compute_region_backend_service" "default" {
  project          = var.project
  name             = var.health_check["type"] == "tcp" ? "${var.name}-with-tcp-hc" : "${var.name}-with-http-hc"
  region           = var.region
  protocol         = var.ip_protocol
  timeout_sec      = 10
  session_affinity = var.session_affinity
  backend {
    group          = data.google_compute_instance_group.ig[*] 
    
  }
  
  health_checks = [var.health_check["type"] == "tcp" ? google_compute_health_check.tcp[0].self_link : google_compute_health_check.http[0].self_link]
}

variable "ig" {
  description = "A list of databases to be created in your cluster"
  type = list(string)
  default = ["codg","saydlog"]
}
```

### Crash Output

    | data.google_compute_instance_group.ig is tuple with 2 elements
### Expected Behavior

How to get value from data data "google_compute_instance_group" "ig" to another resource to get value count index? and instance group has multiple group name and the value can get value to  data.google_compute_instance_group.ig[*]

**Comment by danieldreier** [comment] 2020-05-27 17:11
Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug, please help by providing more details about an environment I can set up locally to reproduce this failure more. The output you provided isn't actually an error, so I'd need more details on what error or crash you're seeing that you're reporting as a bug.

Based on my work so far, I recommend you take this to the community forum for assistance in troubleshooting. I'm going to close this for now, because I think the community forum is the right approach. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you'd rather work up a reproduction case here.

**Closed by danieldreier** 2020-05-27 17:11 UTC
