### ISSUE TITLE
Quiet flag for plan command

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#16468] opened 2017-10-26 23:59 UTC
Currently, `terraform plan` outputs a lot of "noise". For example:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.foundation: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
data.template_file.bootstrap: Refreshing state...
```

Often when making changes to our Terraform code, I will run `terraform plan` before and after making the change and compare the output in order to verify that the change is working as intended. This output, however, makes it harder for me to do so. It would be great if there was a `-quiet` flag that could be used to suppress this output.

**Comment by apparentlymart** [comment] 2017-10-27 18:19
Hi @joshuaspence!

I'm not sure why you're seeing the same resource mentioned multiple times for refreshing. That's some strange behavior that I don't have any explanation for. The output here should be more like:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.foundation: Refreshing state...
data.external.ec2_instance_info: Refreshing state...
data.template_file.bootstrap: Refreshing state...
```

With that said, I think if we were to do this we'd want to use a more specific option name, like maybe `-refresh=quiet` as an alternative to `-refresh=false`, since "quiet" isn't really clear about what exactly it silences. I'd love to first be able to explain why the output here is so repetitive, though... :thinking:

**Comment by joshuaspence** [comment] 2017-10-29 05:42
Oh, it's not really the same resource... we have a module that we use which essentially provides a wrapper around the `aws_instance` resource. Two of the things that this module does is lookup the current on-demand price for the specified instance type (this is `data.external.ec2_instance_info`) and provide a bootstrap script that we use for provisioning the instances (`data.template_file.bootstrap`). So the repeated resources in the provided output are all coming from a different resource being created with our module. Although, this presents another issue, perhaps, in that the output doesn't provide fully-qualified resource names which can make it hard to debug.

**Comment by apparentlymart** [comment] 2017-10-29 14:31
Oh, aha! So this is another place we need to update the output to use the resource addressing syntax. (We did this for apply and plan output in a recent release, but missed "refresh" I suppose.)

**Comment by tdmalone** [comment] 2019-04-20 08:47
fwiw, [Landscape](https://github.com/coinbase/terraform-landscape/) is a good solution to this:

```
$ terraform plan | landscape
No changes.
```

**Comment by ezh** [comment] 2019-05-15 09:45
We have a lot of resources too. And our build pipeline consists from group of Terraform parts. _It is very difficult to review multiple plans across hundreds of lines._

Landscape is ruby tool. We have CI and also allow different engineers to run our pipeline too. They all have different environments on their workplaces. Installation of one more tool for large team of poorly connected people with absolutely different technical skills is a pain. We are using only Gradle + Terraform. Landscape is suitable only for advanced users.

**Comment by tdmalone** [comment] 2019-05-16 03:20
> Landscape is suitable only for advanced users.

I beg to differ - it's quite simple, as I showed in my example above.
Though I understand it would be much nicer to have it as a native Terraform solution - nevertheless that's probably not going to happen soon so it's instead available today in a third-party tool 😄 

If installing Ruby is a problem, stick it in a Docker container. In fact, a [Dockerfile is provided](https://github.com/coinbase/terraform-landscape#docker). You could use Bash aliases to make the `docker run -i --rm landscape` shorter and easier to remember too.

**Comment by acdha** [comment] 2019-11-05 14:59
> With that said, I think if we were to do this we'd want to use a more specific option name, like maybe -refresh=quiet as an alternative to -refresh=false, since "quiet" isn't really clear about what exactly it silences. 

This is exactly what I was hoping to find — I'm running Terraform against a large number of AWS accounts and refreshes account for almost all of the output produced. It'd be really nice if there was a way to have that be silent unless an error occurs.

**Comment by phalverson** [comment] 2020-01-22 18:41
You could redirect the output to script variable or temp file, then if the return status is non-zero echo it to stderr, e.g. something like
```
$ response=$(terraform plan 2>&1) || echo $response 1>&2
```

**Comment by jclynny** [comment] 2020-01-26 14:54
Is there any update on this request?  I also find plans to be quite noisy, including when you're rendering a local file.  +1

**Comment by sumanmukherjee03** [comment] 2020-04-27 21:03
+1 to this as well. we generate a `tfplan` while running plan. so, if there's an optional way to suppress the logging on stdout that'll be very nice indeed.

**Comment by ktdasher1** [comment] 2020-06-16 02:53
+1 agreed there is not much value of this output to the standard user

**Comment by nwsparks** [comment] 2020-07-01 13:12
This is useful with https://terraform-compliance.com/ as it requires you to generate a plan file to test against. Helps cut back on the noise when you need to run plans against multiple envs are part of the test suite.

**Comment by acurvers** [comment] 2020-12-10 11:21
+1 there is not much value of this output to the standard user

**Comment by joeaawad** [comment] 2020-12-10 23:53
FYI to people in this thread - with 0.14 refactoring the way that plans refresh the current state, [@jbardin noted a few downsides](https://github.com/hashicorp/terraform/issues/27214#issuecomment-742581355) to the refresh then plan workflow and [@apparentlymart provided this alternative](https://github.com/hashicorp/terraform/issues/27214#issuecomment-742809948) that avoids those downsides. For local development, creating an alias for this command will provide the same functionality that people currently get from refreshing before planning.

```bash
terraform plan -out=tfplan >/dev/null && terraform show tfplan && rm tfplan
```

**Comment by acdha** [comment] 2020-12-12 04:00
> FYI to people in this thread - with 0.14 refactoring the way that plans refresh the current state, [@jbardin noted a few downsides](https://github.com/hashicorp/terraform/issues/27214#issuecomment-742581355) to the refresh then plan workflow and [@apparentlymart provided this alternative](https://github.com/hashicorp/terraform/issues/27214#issuecomment-742809948) that avoids those downsides. For local development, creating an alias for this command will provide the same functionality that people currently get from refreshing before planning.
> 
> ```shell
> terraform plan -out=tfplan >/dev/null && terraform show tfplan && rm tfplan
> ```

n.b. this has a few drawbacks since anything which causes a prompt will display on stdin and the process will appear to have hung. I also changed it so the `rm` is always run to avoid leaving `tfplan` files behind:

```shell
terraform plan -input=false -out=tfplan >/dev/null && terraform show tfplan ; rm tfplan
``` 

(You could probably avoid the temporary file by duplicating stdout before redirecting it but that doesn't seem worth the loss of clarity)

**Comment by NeckBeardPrince** [comment] 2021-09-30 16:22
Any update on this?

**Comment by torbendury** [comment] 2022-02-23 07:45
Is there anything happening? Although we're not seeing the same resource multiple times in the logs, we have several hundred resources that are being refreshed which is spamming the CI logs.

**Comment by gforien** [comment] 2022-08-02 08:50
Any updates on this ? 🙏 

This flag would be really useful instead of a shell alias for 2 reasons
- We already use aliases in some cases to work with many workspaces. This would be adding more complexity.
- In other cases we use terragrunt to deal with many workspaces, and there is no alias for this. If the problem is not fixed in Terraform code, it cannot be dealt in other open-source project which rely on Terraform.

The logs become especially long and unreadable when
- working with many workspaces
- working with AWS Lambda functions & Steps functions

This also cause unintended limitations in the CI
- in some cases, we have a GHA bot outputting the TF plans in the comments of a PR. The plan itself is only 70 lines long, but we can have 500+ lines of refreshing. This cause the plan to exceed the max comment size and to be discarded altogether.
- See also [this issue](https://github.com/hashicorp/setup-terraform/issues/24) where the TF plan is too long to be passed between steps in the CI

**Comment by crw** [comment] 2022-08-12 22:28
Thanks for the continued feedback on this issue. This issue appears to be a precursor to a subsequent issue on the same topic, which has more recent consideration on the topic: https://github.com/hashicorp/terraform/issues/27214. Unfortunately 27214 likely should have been marked as a duplicate of this issue, but given that it was missed at the time, I am going to take the ahistorical action of marking this issue as a duplicate of 27214 so that we can consolidate the feedback. Thanks for your patience here, and please let me know if I missed something that distinguishes these two issues.

**Closed by crw** 2022-08-12 22:28 UTC
Labels: enhancement, cli
