### ISSUE TITLE
Crash Log: TF Apply Post 0.7.12 Upgrade (Possibly Lambda Related)

### ISSUE THREAD

**Issue by jvasallo** [hashicorp/terraform#10321] opened 2016-11-23 17:54 UTC
Hi folks,

I just updated to Terraform 0.7.12 and I appear to be getting a crash every time I run a Terraform apply. I upgraded after some issues with 0.7.11 and waiting for success on creating firehose resources via Terraform. I don't suspect this is the issue however and feel it could be related to lambda in `provider/aws`.

### Terraform Version

Terraform v0.7.12

### Affected Resource(s)
This is an issue against the terraform apply command. Terraform crashes every apply on the same spot.

### Terraform Configuration Files
N/A

### Debug Output
Refer to crash.log

### Panic Output
https://gist.github.com/jvasallo/83205430ee8ca0dc72451891bcd11410

### Expected Behavior
Not exactly sure, but I would have suspected show of all the resources that match the top level resource. At the very least it should toss an error instead of crash?

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
`terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by jvasallo** [comment] 2016-11-23 17:55
I have the full crash.log if necessary, I just don't feel particularly comfortable sharing the whole log publicly.

**Comment by Ninir** [comment] 2016-11-23 18:46
Hi @jvasallo 
It has been fixed in https://github.com/hashicorp/terraform/pull/10306 and will be in the next released (will be out very soon since it has a regression).

Switch back to 0.7.11 for now I suggest :)

**Comment by mitchellh** [comment] 2016-11-23 19:43
Out in 0.7.13. We're very sorry about that. :(

**Closed by mitchellh** 2016-11-23 19:43 UTC

**Comment by jvasallo** [comment] 2016-11-23 22:31
Thanks for the fast feedback folks and no worries! I'll search better next time.
