### ISSUE TITLE
docker images for terraform 1.5.* have broken python3 (pyexpat XML_SetReparseDeferralEnabled: symbol not found)

### ISSUE THREAD

**Issue by REW1L** [hashicorp/terraform#35715] opened 2024-09-11 16:16 UTC
### Terraform Version

```shell
1.5.* (e.g. 1.5.7)
```

### Terraform Configuration Files

Not applicable

### Debug Output
```
$ docker run -it --rm --entrypoint "" hashicorp/terraform:1.5.7 /bin/sh
# apk add python3
# python3
Python 3.11.10 (main, Sep 11 2024, 10:00:27) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyexpat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Error relocating /usr/lib/python3.11/lib-dynload/pyexpat.cpython-311-x86_64-linux-musl.so: XML_SetReparseDeferralEnabled: symbol not found

# apk add aws-cli
# aws --version

Error relocating /usr/lib/python3.11/lib-dynload/pyexpat.cpython-311-x86_64-linux-musl.so: XML_SetReparseDeferralEnabled: symbol not found
```

### Expected Behavior

pyexpat can be imported
The version of aws-cli is printed and aws-cli is actually working

### Actual Behavior

Error relocating /usr/lib/python3.11/lib-dynload/pyexpat.cpython-311-x86_64-linux-musl.so: XML_SetReparseDeferralEnabled: symbol not found

### Steps to Reproduce
```
# apk add aws-cli
# aws --version
```

### Additional Context

It happened after an alpine python3 release 2024-09-11 10:00:27 https://pkgs.alpinelinux.org/packages?name=python3&branch=v3.18&repo=main&arch=x86_64&maintainer=

The same commands work well with alpine:3.18.3 docker image that seems to be used during the build of terraform:1.5.7 docker image

**Comment by jbardin** [comment] 2024-09-11 16:41
Hi @REW1L,

The Dockerfile for the build wasn't changed during that time, so any differences would be solely from the upstream image. Your above example works correctly if the package is updated, and I also confirmed that newer images have already updated the problematic packages.

Closing since there's nothing the Terraform CLI can do to fix the old docker image.

**Closed by jbardin** 2024-09-11 16:41 UTC
Labels: bug, new

**Comment by jbardin** [comment] 2024-09-11 17:55
@REW1L, Terraform is currently releasing from the v1.9 branch for normal maintenance, and recent prior versions are typically only ever released for exceptional security related issues, so I wouldn't expect to see any v1.5 releases.

Given the number of possible packages that one could install into the alpine image even with only the default repos, we can't cut new Terraform releases to update the image each time a bug is found in a package. The only artifact from the Terraform release is a single binary which is copied into a Docker image for the convenience of some use cases. Users who want better control over the runtime environment can copy that same binary into an image under their control.
