### ISSUE TITLE
External Data Source - json: cannot unmarshal array into Go value of type string

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform#12256] opened 2017-02-26 02:03 UTC
### Terraform Version
0.8.7

### Affected Resource(s)
- [external](https://www.terraform.io/docs/providers/external/data_source.html)

### Terraform Configuration Files
```hcl
data "external" "create_policy" {
  program = ["bash", "${path.module}/create_policy.sh"]
}
```

**create_policy.sh**
```bash
#!/bin/bash
set -e
# This works
jq -n --arg foobaz "$FOOBAZ" '{"foobaz":$foobaz}'
# This throws an error
jq -n '{"Version":"2008-10-17","Statement":[{"Sid":"repo_policy","Effect":"Allow","Principal":{"AWS":["arn:aws:iam::${account_id}:root","arn:aws:iam::${account_id}:role/ecr_restricted_admin"]},"Action":"*"}]}'
```
### Expected Behavior
Terraform shouldn't thrown an error when the the bash script is producing a valid json

```bash
$ bash modules/ecr/create_policy.sh  | jq .
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "repo_policy",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::${account_id}:root",
          "arn:aws:iam::${account_id}:role/ecr_restricted_admin"
        ]
      },
      "Action": "*"
    }
  ]
}
```

### Actual Behavior
```sh
* data.external.create_policy: command "bash" produced invalid JSON: json: cannot unmarshal array into Go value of type string
```

### Steps to Reproduce
Create the resource and the script files and run `terraform plan`

**Comment by apparentlymart** [comment] 2017-02-26 15:09
Hi again, @vikas027!

This issue is essentially the same thing as #12249: the result from the process is subject to the same restriction that Terraform's internal schema is not able to represent maps with differently-typed keys, so currently only string values are supported.

This restriction may be lifted in future if Terraform's core becomes able to represent arbitrarily-typed map members or some other dynamic-object-like type, but for now this is the intended behavior and documented as such, with the workaround being the inverse of what I suggested in #12249: the external program should return a delimited string and then you can use the Terraform `split` function to recover the original list.

**Comment by apparentlymart** [comment] 2017-02-26 15:11
Given that they are both blocked by the same core improvement, I'm going to close this to consolidate the discussion over in #12249. Supporting arbitrary data here is something I'd like to see, but we'll need to see if Terraform core can support the dynamic typing behavior we need here.

**Closed by apparentlymart** 2017-02-26 15:11 UTC
Labels: enhancement, provider/external
