### ISSUE TITLE
Allow interactive input variables to be hidden

### ISSUE THREAD

**Issue by gudlyf** [hashicorp/terraform#31568] opened 2022-08-03 18:55 UTC
### Current Terraform Version

```
Terraform v1.2.6
on darwin_amd64
```

### Use-cases

There are times when a sensitive input variable must be entered manually during a `terraform plan/apply` operation. Despite the variable being marked `sensitive`, typing this variable value in the CLI still displays what is typed, therefore exposing the value to onlookers.

### Attempted Solutions

Setting the variable setting to `sensitive = true` does not solve this issue.

### Proposal

When a variable is marked `sensitive`, also do not echo its input in the CLI, instead displaying a `*` for each character entered.

```
$ terraform plan
var.password
  Enter a value: **********
```

### References

- #23022

**Comment by jbardin** [comment] 2022-08-03 19:42
Duplicate of #28122

**Closed by jbardin** 2022-08-03 19:42 UTC
Labels: enhancement, new
