### ISSUE TITLE
same error in both 0.6.14 and  0.6.15 try to achieve rolling deployment  

### ISSUE THREAD

**Issue by cloudeng** [hashicorp/terraform#6435] opened 2016-05-02 04:33 UTC
Error applying plan:

1 error(s) occurred:
- aws_autoscaling_notification.asg_notifications: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

```
Terraform Version: 0.6.14
Resource ID: aws_autoscaling_notification.asg_notifications
Mismatch reason: attribute mismatch: group_names.3042354854
Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"notifications.3298075921":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_TERMINATE_ERROR", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "group_names.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "group_names.3042354854":*terraform.ResourceAttrDiff{Old:"", New:"${aws_launch_configuration.launch_config.name}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "notifications.#":*terraform.ResourceAttrDiff{Old:"", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "notifications.4098158487":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_LAUNCH", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "notifications.753791182":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_LAUNCH_ERROR", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "topic_arn":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:sns:us-east-1:869499070373:raven-autoscaling-notification", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "notifications.3116970575":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_TERMINATE", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"notifications.4098158487":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_LAUNCH", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "notifications.753791182":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_LAUNCH_ERROR", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "group_names.1339058992":*terraform.ResourceAttrDiff{Old:"", New:"load-notification-deliverypu6hxnwzpjec3ahfoa6mvgut3m", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "notifications.#":*terraform.ResourceAttrDiff{Old:"", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "notifications.3116970575":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_TERMINATE", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "notifications.3298075921":*terraform.ResourceAttrDiff{Old:"", New:"autoscaling:EC2_INSTANCE_TERMINATE_ERROR", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "topic_arn":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:sns:us-east-1:869499070373:raven-autoscaling-notification", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "group_names.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
```

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jrnt30** [comment] 2016-05-03 13:11
@cloudeng I'm curious, does your configuration actually reference the `aws_launch_configuration` resource for the `groups_names` attribute as the diff suggests?  I believe this should referencing the `aws_autoscaling_group` resource not the  `aws_launch_configuration` resource. 

If so, does changing this fix your issue properly?  

Relevant Diff Extract: 
```
"group_names.3042354854":*terraform.ResourceAttrDiff{Old:"", New:"${aws_launch_configuration.launch_config.name}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}
 ```

**Comment by cloudeng** [comment] 2016-05-03 17:52
@jrnt30 following is the template I am using to do rolling deployment its working  after removing aws_autoscaling_notification  without any issues 


``` terraform 
provider "aws" {
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    region     = "${var.aws_region}"
}

resource "aws_autoscaling_group" "main_asg" {
  lifecycle { create_before_destroy = true   }
  availability_zones = ["${split(",", var.availability_zones)}"]
  name                        = "${aws_launch_configuration.launch_config.name}"
  desired_capacity            = "${var.asg_desired_capacity}"
  health_check_grace_period   = "${var.health_check_grace_period}"
  health_check_type           = "${var.health_check_type}"
  launch_configuration        = "${aws_launch_configuration.launch_config.id}"
  load_balancers              = ["${split(",", var.load_balancer_names)}"]
  max_size                    = "${var.asg_max_number_of_instances}"
  min_size                    = "${var.asg_min_number_of_instances}"
  vpc_zone_identifier         = ["${split(",", var.private_subnet_ids)}"]
  wait_for_elb_capacity       = "${var.wait_for_elb_capacity}"
  tag {
    key = "Name"
    value = "${var.service_name}"
    propagate_at_launch = true
  }
  tag{
  key   = "Env"
  value = "${var.env}"
  propagate_at_launch = true
  }
}

resource "aws_launch_configuration" "launch_config" {
  name_prefix           = "${var.service_name}"
  image_id              = "${var.ami_id}"
  instance_type         = "${var.instance_type}"
  key_name              = "${var.key_name}"
  security_groups       = ["${var.security_groups}"]
  iam_instance_profile  = "${var.iam_instance_profile}"
  user_data             = "${var.user_data}"
  root_block_device { delete_on_termination = true }
  lifecycle {
     create_before_destroy = true
   }
}

// notifications when there is change in autoscaling
resource "aws_autoscaling_notification" "asg_notifications" {
  group_names = [ "${aws_autoscaling_group.main_asg.name}"     ]
  notifications  = [
             "autoscaling:EC2_INSTANCE_LAUNCH",
             "autoscaling:EC2_INSTANCE_LAUNCH_ERROR",
             "autoscaling:EC2_INSTANCE_TERMINATE",
             "autoscaling:EC2_INSTANCE_TERMINATE_ERROR"
          ]
topic_arn = "arn:aws:sns:${var.aws_region}:${var.aws_account_id}:${var.topic_name}"
lifecycle {
   create_before_destroy = true
 }
}

**Comment by paddyforan** [comment] 2016-11-10 20:27
Hi @cloudeng! Apologies for the long wait to get this fixed. I've just tried a minimal reproduction using terraform 0.7.10, and I can't seem to get this bug to pop up again. Here's the config I'm using:

```tf
provider "aws" {
  region = "us-west-2"
}

resource "aws_autoscaling_group" "foo" {
  lifecycle {
    create_before_destroy = true
  }

  availability_zones   = ["us-west-2a"]
  name                 = "${aws_launch_configuration.foo.name}"
  launch_configuration = "${aws_launch_configuration.foo.id}"
  max_size             = 2
  min_size             = 1
}

resource "aws_launch_configuration" "foo" {
  name_prefix   = "foo"
  image_id      = "ami-4fccb37f"
  instance_type = "m1.small"

  lifecycle {
    create_before_destroy = true
  }
}

// notifications when there is change in autoscaling
resource "aws_autoscaling_notification" "foo" {
  group_names = ["${aws_autoscaling_group.foo.name}"]

  notifications = [
    "autoscaling:EC2_INSTANCE_LAUNCH",
    "autoscaling:EC2_INSTANCE_LAUNCH_ERROR",
    "autoscaling:EC2_INSTANCE_TERMINATE",
    "autoscaling:EC2_INSTANCE_TERMINATE_ERROR",
  ]

  topic_arn = "${aws_sns_topic.foo.arn}"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_sns_topic" "foo" {
	name = "foo"
}
```

Because it's been so long and I can't get the issue to pop up again, I'm going to go ahead and close this, as I suspect the bug was fixed. If, however, you're still running into the error, or run into it again, please feel free to just comment here and we'll reopen the issue and try to track it down.

**Closed by paddyforan** 2016-11-10 20:27 UTC
Labels: bug, provider/aws
