### ISSUE TITLE
Yamlencode function includes heredoc anchors in output

### ISSUE THREAD

**Issue by rojopolis** [hashicorp/terraform#27251] opened 2020-12-11 01:32 UTC
### Terraform Version

```
0.14.0 - 0.14.2
```

### Terraform Configuration Files

```terraform
output "yaml" {
  value = yamlencode({ foo = "bar" })
}
```

### Expected Behavior

Output valid yaml as previous Terraform versions do.

### Actual Behavior

```
tf output yaml
<<EOT
"foo": "bar"

EOT

```

### Steps to Reproduce

terraform init
terraform apply
terraform output yaml

**Comment by danieldreier** [comment] 2020-12-11 14:44
Thank you for reporting this! I've reproduced this exactly as reported in 0.14.2.

**Comment by alisdair** [comment] 2020-12-11 15:36
Hi @rojopolis, thanks for reporting this.

The `yamlencode` function returns a string, which is then displayed by `terraform output` as a heredoc because it has multiple lines. We changed the format of `terraform output` in 0.14 to make it clearer what type values were, and to allow the output value to be used directly in HCL.

It sounds like you're trying to use this output in an automated setting, where the heredoc markers make this difficult. We do not support using the `terraform output` text UI in automation, and instead suggest using the stable JSON output. For example:

```shellsession
$ terraform output -json yaml | jq -r
"foo": "bar"

```

In an upcoming 0.14 patch release we are also adding a `-raw` flag to `terraform output`, which would also be an option here:

```shellsession
$ terraform output -raw yaml
"foo": "bar"
```

See #27212 for more details on `-raw`.

I'm marking this closed as Terraform is working as designed, and there are two workarounds described above. Thanks again for reporting!

**Closed by alisdair** 2020-12-11 15:36 UTC
Labels: bug, confirmed, v0.14
