### ISSUE TITLE
Cycle Error: Implementing secrets manager to secure access_key and secret_key under provider.aws

### ISSUE THREAD

**Issue by salazro** [hashicorp/terraform#33074] opened 2023-04-23 02:05 UTC
### Terraform Version

```shell
$ terraform version
Terraform v1.4.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.63.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  access_key = local.db_creds.access_key
  secret_key = local.db_creds.secret_key
  region = "us-east-1"

}


data "aws_secretsmanager_secret_version" "current" {
  secret_id = "github_actions"

}

locals {
  db_creds = jsondecode(data.aws_secretsmanager_secret_version.current.secret_string)

}
```

### Debug Output

<script src="https://gist.github.com/salazro/d6f88eb81a74040ca56df95f30ec31c9.js"></script>

### Expected Behavior

Terraform plan should complete

### Actual Behavior

$ terraform plan
╷
│ Error: Cycle: data.aws_secretsmanager_secret_version.current, local.db_creds (expand), provider["registry.terraform.io/hashicorp/aws"]
│
│
╵

### Steps to Reproduce

$ terraform init
2023-04-22T21:04:44.614-0500 [INFO]  Terraform version: 1.4.5
2023-04-22T21:04:44.614-0500 [DEBUG] using github.com/hashicorp/go-tfe v1.18.0
2023-04-22T21:04:44.614-0500 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
2023-04-22T21:04:44.614-0500 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-04-22T21:04:44.614-0500 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-04-22T21:04:44.614-0500 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-04-22T21:04:44.614-0500 [INFO]  Go runtime version: go1.19.6
2023-04-22T21:04:44.614-0500 [INFO]  CLI args: []string{"C:\\Users\\rdsal\\.tfenv\\versions\\1.4.5\\terraform.exe", "init"}
2023-04-22T21:04:44.614-0500 [TRACE] Stdout is a terminal of width 78
2023-04-22T21:04:44.614-0500 [TRACE] Stderr is a terminal of width 78
2023-04-22T21:04:44.614-0500 [TRACE] Stdin is a terminal
2023-04-22T21:04:44.615-0500 [DEBUG] Attempting to open CLI config file: C:\Users\rdsal\AppData\Roaming\terraform.rc
2023-04-22T21:04:44.615-0500 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-04-22T21:04:44.616-0500 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-04-22T21:04:44.616-0500 [DEBUG] ignoring non-existing provider search directory C:\Users\rdsal\AppData\Roaming\terraform.d\plugins
2023-04-22T21:04:44.616-0500 [DEBUG] ignoring non-existing provider search directory C:\Users\rdsal\AppData\Roaming\HashiCorp\Terraform\plugins
2023-04-22T21:04:44.616-0500 [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2023-04-22T21:04:44.617-0500 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2023-04-22T21:04:44.617-0500 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2023-04-22T21:04:44.617-0500 [DEBUG] New state was assigned lineage "9b62d98b-3666-33c4-a85d-b0b9cda40480"
2023-04-22T21:04:44.617-0500 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2023-04-22T21:04:44.617-0500 [TRACE] Meta.Backend: instantiated backend of type <nil>
2023-04-22T21:04:44.618-0500 [TRACE] providercache.fillMetaCache: scanning directory .terraform\providers
2023-04-22T21:04:44.618-0500 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.63.0 for windows_amd64 at .terraform\providers\registry.terraform.io\hashicorp\aws\4.63.0\windows_amd64
2023-04-22T21:04:44.618-0500 [TRACE] providercache.fillMetaCache: including .terraform\providers\registry.terraform.io\hashicorp\aws\4.63.0\windows_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 4.63.0
2023-04-22T21:04:45.179-0500 [DEBUG] checking for provisioner in "."
2023-04-22T21:04:45.179-0500 [DEBUG] checking for provisioner in "C:\\Users\\rdsal\\.tfenv\\versions\\1.4.5"
2023-04-22T21:04:45.180-0500 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2023-04-22T21:04:45.180-0500 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-04-22T21:04:45.180-0500 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-04-22T21:04:45.180-0500 [TRACE] statemgr.Filesystem: read snapshot with lineage "94d93f52-d34e-1b6f-19dd-bb64500a134c" serial 2

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
2023-04-22T21:04:45.180-0500 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2023-04-22T21:04:45.180-0500 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2023-04-22T21:04:45.285-0500 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-04-22T21:04:45.285-0500 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-04-22T21:04:45.389-0500 [TRACE] providercache.fillMetaCache: scanning directory .terraform\providers
2023-04-22T21:04:45.390-0500 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.63.0 for windows_amd64 at .terraform\providers\registry.terraform.io\hashicorp\aws\4.63.0\windows_amd64
2023-04-22T21:04:45.390-0500 [TRACE] providercache.fillMetaCache: including .terraform\providers\registry.terraform.io\hashicorp\aws\4.63.0\windows_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 4.63.0
- Using previously-installed hashicorp/aws v4.63.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by liamcervante** [comment] 2023-04-24 09:56
Hi @salazro, unfortunately the approach you've tried here isn't going to work. The AWS provider requires those credentials to initialise, it cannot retrieve credentials first and then initialise itself. This is what the error message about the cycle is trying to say.

I see you maybe trying to access these from github actions, might I suggest having a look at the [aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) composite action and configuring your repository with access to AWS using the [Github OIDC provider](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services). The Terraform AWS provider will be able to consume the credentials configured by the `configure-aws-credentials` action.

As a further alternative, you might be interested in having a look at [Terraform Cloud](https://developer.hashicorp.com/terraform/cloud-docs) which can handle Github integration and access permissions for you. TFC might be able to do most of the heavy lifting depending on your use case. There is a free tier, so you can try it out if you want.

I will close this as issue as working as intended, but will keep an eye on it if you have any other questions.

**Closed** 2023-04-24 09:57 UTC
Labels: bug, working as designed

**Comment by salazro** [comment] 2023-04-25 18:31
Thanks for the response.
