### ISSUE TITLE
Incorrect behavior during terraform plan -destroy

### ISSUE THREAD

**Issue by Raviadonis** [hashicorp/terraform#24975] opened 2020-05-17 08:34 UTC
Hello there!

I'm creating some resources in AWS Cloud and checking some random terraform behaviours. While running `terraform plan -destroy` with the backup state file, I could see some weird behaviour.

### Terraform Version

```
Terraform v0.12.25
+ provider.aws v2.62.0
```

### Terraform Configuration Files

```
# create the VPC
resource "aws_vpc" "My_VPC" {
  cidr_block = var.vpcCIDRblock
  tags = {
    Name = "My VPC"
  }
}


# create the Subnet
resource "aws_subnet" "My_VPC_Subnet" {
  vpc_id                  = aws_vpc.My_VPC.id
  cidr_block              = var.subnetCIDRblock
  map_public_ip_on_launch = var.mapPublicIP
  availability_zone       = var.availabilityZone
  tags = {
    Name = "My VPC Subnet_Sample"
  }
}


# Create the Security Group
resource "aws_security_group" "My_VPC_Security_Group" {
  vpc_id      = aws_vpc.My_VPC.id
  name        = "My VPC Security Group"
  description = "My VPC Security Group"

  # allow ingress of port 22
  ingress {
    cidr_blocks = var.ingressCIDRblock
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
  }

  # allow egress of all ports
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    Name        = "My VPC Security Group"
    Description = "My VPC Security Group"
  }
}

# Create the Internet Gateway
resource "aws_internet_gateway" "My_VPC_GW" {
  vpc_id = aws_vpc.My_VPC.id
  tags = {
    Name = "My VPC Internet Gateway"
  }
}

# Create the Route Table
resource "aws_route_table" "My_VPC_route_table" {
  vpc_id = aws_vpc.My_VPC.id
  tags = {
    Name = "My VPC Route Table"
  }
}

# Create the Internet Access
resource "aws_route" "My_VPC_internet_access" {
  route_table_id         = aws_route_table.My_VPC_route_table.id
  destination_cidr_block = var.destinationCIDRblock
  gateway_id             = aws_internet_gateway.My_VPC_GW.id
}

# Associate the Route Table with the Subnet
resource "aws_route_table_association" "My_VPC_association" {
  subnet_id      = aws_subnet.My_VPC_Subnet.id
  route_table_id = aws_route_table.My_VPC_route_table.id
}


```

### Debug Output

Debug output of `terraform plan -destroy`

https://gist.github.com/Raviadonis/7598272d3be02f788068bd366f910091

### Expected Behavior

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_vpc.My_VPC: Refreshing state... [id=vpc-05a5bb4bb6c0d799c]
aws_route_table.My_VPC_route_table: Refreshing state... [id=rtb-0639d1bfd29d7f7f0]
aws_subnet.My_VPC_Subnet: Refreshing state... [id=subnet-097308ff1f43aa886]
aws_internet_gateway.My_VPC_GW: Refreshing state... [id=igw-0c4fbbaacf229e763]
aws_security_group.My_VPC_Security_Group: Refreshing state... [id=sg-02c2702f11ed5e420]
aws_route_table_association.My_VPC_association: Refreshing state... [id=rtbassoc-0f97b2a72cec030c8]
aws_route.My_VPC_internet_access: Refreshing state... [id=r-rtb-0639d1bfd29d7f7f01080289494]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behavior
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_vpc.My_VPC: Refreshing state... [id=vpc-05a5bb4bb6c0d799c]
aws_route_table.My_VPC_route_table: Refreshing state... [id=rtb-0639d1bfd29d7f7f0]
aws_subnet.My_VPC_Subnet: Refreshing state... [id=subnet-097308ff1f43aa886]
aws_internet_gateway.My_VPC_GW: Refreshing state... [id=igw-0c4fbbaacf229e763]
aws_security_group.My_VPC_Security_Group: Refreshing state... [id=sg-02c2702f11ed5e420]
aws_route_table_association.My_VPC_association: Refreshing state... [id=rtbassoc-0f97b2a72cec030c8]
aws_route.My_VPC_internet_access: Refreshing state... [id=r-rtb-0639d1bfd29d7f7f01080289494]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # aws_route_table_association.My_VPC_association will be destroyed
  - resource "aws_route_table_association" "My_VPC_association" {
      - id             = "rtbassoc-0f97b2a72cec030c8" -> null
      - route_table_id = "rtb-0639d1bfd29d7f7f0" -> null
      - subnet_id      = "subnet-097308ff1f43aa886" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Steps to Reproduce

Steps which I followed to check the random behaviour

1. `terraform init`
2. `terraform apply -auto-approve`
3. `terraform destroy -auto-approve`
4. `rm -f terraform.tfstate`
5. `mv terraform.tfstate.backup terraform.tfstate`
6. `terraform plan -destroy`

### Additional Context

During the 3rd step from above `aws_route_table_association` resource was getting destroyed. But, if I try with the backup state file each time, it says 1 resource to destroy. It's weird for me.

**Comment by danieldreier** [comment] 2020-05-18 21:35
@Raviadonis thanks for reporting this. I'm curious what's going on here. I tried running this in order to reproduce it locally, and there are a bunch of undeclared variables, so this reproduction case isn't quite done:
```
Error: Reference to undeclared input variable

  on repro.tf line 23, in resource "aws_subnet" "My_VPC_Subnet":
  23:   cidr_block              = var.subnetCIDRblock

An input variable with the name "subnetCIDRblock" has not been declared. This
variable can be declared with a variable "subnetCIDRblock" {} block.


Error: Reference to undeclared input variable

  on repro.tf line 24, in resource "aws_subnet" "My_VPC_Subnet":
  24:   map_public_ip_on_launch = var.mapPublicIP

An input variable with the name "mapPublicIP" has not been declared. This
variable can be declared with a variable "mapPublicIP" {} block.


Error: Reference to undeclared input variable

  on repro.tf line 25, in resource "aws_subnet" "My_VPC_Subnet":
  25:   availability_zone       = var.availabilityZone
```

I re-purposed an existing simple terraform config and put together what I think is an equivalent test case at https://github.com/danieldreier/terraform-issue-reproductions/tree/master/24975. You can git clone it and run `./run.sh` to run what I think is a functional equivalent. In that, I was not able to confirm the behavior you're describing.

Can you please make a PR against that repo to update the test case with one that shows this issue?

**Comment by Raviadonis** [comment] 2020-05-22 12:35
Hello Daniel!
I ended up with the same behavior. Created a PR with updated code which shows the behavior. Please take a look at it.

**Comment by Raviadonis** [comment] 2020-05-30 16:33
@danieldreier Did you get a chance to try out the solution for the above error?

**Comment by danieldreier** [comment] 2020-05-30 16:52
I haven’t had time but it’s still on my list!

**Comment by danieldreier** [comment] 2020-06-05 01:07
@Raviadonis I've merged your reproduction case PR, run it, and got the same error:

```
Error: Reference to undeclared resource

  on 24975.tf line 87, in resource "aws_route_table_association" "My_VPC_association":
  87:   subnet_id      = aws_subnet.My_VPC_Subnet.id

A managed resource "aws_subnet" "My_VPC_Subnet" has not been declared in the
root module.
```

The reason for this is that the only `aws_subnet` in that example is called `example`, not `My_VPC_Subnet`. I've fixed this, and pushed the reproduction case back into the GH repo. Now that I have done that, I see the same behavior you're describing. In fact, when I actually run a `terraform destroy` using the backed-up state file, it shows as destroyed. I have updated `run.sh` to show a more obvious version of this, where one last resource is repeatedly destroyed when repeatedly recovering the backup state file and re-running destroy.

Can you help me triage - is this actually causing you a practical problem or is it a matter of curiosity? We've got a big influx of 0.13-beta1 issues, so I'm trying to prioritize this against those and am hesitant to pull engineers into a curiosity at the cost of triaging potentially major bugs.

**Comment by Raviadonis** [comment] 2020-06-07 15:23
@danieldreier Thanks for taking your time. Currently this is not blocking any of my productivity and just an intense desire to know how it works. You can put it in the backlog and take it later.

**Comment by danieldreier** [comment] 2020-06-09 00:19
@Raviadonis I suspect that this is specific to the AWS provider's implementation of `aws_route_table_association`. I took a quick look in their source and couldn't figure it out, so  I'll label this so the issue is migrated over to the AWS provider team, and hopefully they'll be able to answer.

**Closed** 2020-06-09 00:20 UTC
Labels: provider/aws
