### ISSUE TITLE
Terraform crash checkable object status report for unexpected checkable object

### ISSUE THREAD

**Issue by BeneHa** [hashicorp/terraform#35525] opened 2024-08-01 11:12 UTC
### Terraform Version

```shell
Terraform v1.9.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.113.0
+ provider registry.terraform.io/hashicorp/random v3.6.2
```

### Terraform Configuration Files

```terraform
variable "maximum_shortname_length" {
  type        = number
  description = "The maximum length until which a name is interpreted as shortname and thus environments are shortened."
  default = 24

  validation {
    condition     = var.maximum_shortname_length > 0 && var.maximum_shortname_length <= 260
    error_message = "The maximum shortname length must be positive and must not exceed the maximum default length for names of 260."
  }
}
```

### Debug Output
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: checkable object status report for unexpected checkable object module.function.module.slot_endpoint.module.naming_notunique.var.maximum_shortname_length
goroutine 126892 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        github.com/hashicorp/terraform/internal/logging/panic.go:84 +0x198
panic({0x105f0e800?, 0x140021edee0?})
        runtime/panic.go:770 +0x124
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0x14000caec30, {0x1066141d0, 0x140039dc120}, 0x6, 0x0, 0x50)
        github.com/hashicorp/terraform/internal/checks/state_report.go:106 +0x2a8
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x1063ddc00?, {0x1066141d0?, 0x140039dc120?}, 0x14004a75178?, 0x0?, 0x0?)
        github.com/hashicorp/terraform/internal/checks/state_report.go:71 +0xd4
github.com/hashicorp/terraform/internal/terraform.evalVariableValidations({{0x14001eb4c60, 0x3, 0x3}, {{}, {0x14002280870, 0x18}}}, {0x10662cb08, 0x14003be14a0}, {0x1400085aa68, 0x1, ...}, ...)
        github.com/hashicorp/terraform/internal/terraform/eval_variable.go:290 +0xbe8
github.com/hashicorp/terraform/internal/terraform.(*nodeVariableValidation).Execute(0x14001941080, {0x10662cb08, 0x14002d191d0}, 0x0?)
        github.com/hashicorp/terraform/internal/terraform/node_variable_validation.go:110 +0x198
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14000594c80, {0x10662cb08, 0x14002d191d0}, {0x12f49d628, 0x14001941080})
        github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:153 +0xa8
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x106272b40, 0x14001941080})
        github.com/hashicorp/terraform/internal/terraform/graph.go:135 +0x65c
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14001e72540, {0x106272b40, 0x14001941080}, 0x14007574400)
        github.com/hashicorp/terraform/internal/dag/walk.go:384 +0x2a8
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 126135
        github.com/hashicorp/terraform/internal/dag/walk.go:307 +0xc30
```
### Expected Behavior

The module creates a names for relevant Azure resources. It is used hundreds of times across organization and never causes any issues until now in this special case.

### Actual Behavior

Error shown above.

### Steps to Reproduce

This is part of a big composition with multiple submodules, I cannot easily create a reproducible example of it.

**Comment by crw** [comment] 2024-08-01 23:34
Thanks for this report!

**Comment by liamcervante** [comment] 2024-08-02 08:32
Hi @BeneHa - is this occurring during normal Terraform plan or apply operations? I'm wondering if it might be related to https://github.com/hashicorp/terraform/issues/35503 which was occurring during destroy operations. Thanks!

**Comment by BeneHa** [comment] 2024-08-02 08:38
Hi @liamcervante , this happened during a normal plan operation. I guess it is related to resources being deployed conditionally (with count = ... ? 0 : 1) and terraform tries to get a value from a submodule of the conditionally deployed module which is not created in one case which causes the crash.

**Comment by liamcervante** [comment] 2024-08-02 13:55
This may be a duplicate of https://github.com/hashicorp/terraform/issues/35477, but I don't really have enough information about either ticket to know for sure.

**Comment by liamcervante** [comment] 2024-08-05 14:37
I'm going to close this as a duplicate of https://github.com/hashicorp/terraform/issues/35477 and continue the discussion over there.

**Closed by liamcervante** 2024-08-05 14:37 UTC
Labels: bug, new
