### ISSUE TITLE
remote state: version upgrades are causing local/remote conflicts

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#6695] opened 2016-05-16 21:03 UTC
Hey guys, looks like since the state version is changing with 0.7 (guessing there has been some changes that have warranted the increment of the version number), I'm getting a local/remote state conflict now when I'm attempting to use version 1 remote states.

Guessing we need some functionality to ensure that on a `terraform remote config` for version 1 remote states that remote state is re-pushed right away, to avoid the conflict.

### Terraform Version
Terraform v0.7.0-dev (6bcd95547632044042761123dbfa2d88b85591c9)

### Affected Resource(s)
Remote state (S3 specifically)

### Terraform Configuration Files
NA

### Debug Output
https://gist.github.com/vancluever/3c2b72c8db1554514e99ce58c280fbbe

### Expected Behavior
Terraform should have proceeded as per normal, or more specifically, performed the appropriate operations and then pushed the remote state, naturally upgrading it.

### Actual Behavior
See debug output. This happens on any TF operation.

### Steps to Reproduce
 * Ensure you have a pre-0.7 remote state
 * `terraform remote config` the state, ensure you have no remote state to push before doing
 * Run `terraform plan`, or `terraform apply`

### Important Factoids 

The only difference between the states (based off a diff on the 2 JSON docs) is the version number:

```
$ diff terraform.tfstate terraform.tfstate.v1
2c2
<     "version": 2,
---
>     "version": 1,
```

**Comment by vancluever** [comment] 2016-05-16 22:15
**Workaround**: After digging in the code, the issue basically boils down to the checking that [state.RefreshState()](https://github.com/hashicorp/terraform/blob/d1ac7d3b2e1be2f32092275340f33a2d73f7b31a/state/cache.go#L77) does on the cached versus the durable state. One of the conditions for passing is a local (cached) serial that is greater than the remote, so a easy way to work around this is:

 * `terraform remote config` as above
 * Increment your local `.terraform/terraform.tfstate` serial
 * `terraform remote push`

**Comment by jbardin** [comment] 2016-06-28 19:08
Hi @vancluever 

I'm fairly certain this was a transient bug during the 1->2->3 migration of state version. Note that state version 2 wasn't in any terraform release.

Can you see if you can still reproduce this with the latest build?

Thanks!

**Comment by jbardin** [comment] 2016-06-29 14:02
As of #7402, we now increment the state Serial whenever we upgrade so I'm marking this as resolved. We can open a new issue if there is another conflict, since we should no longer see matching serial numbers with different versions.

**Closed by jbardin** 2016-06-29 14:02 UTC
Labels: bug, core, release-0.7
