### ISSUE TITLE
Failed to download module

### ISSUE THREAD

**Issue by Bathlamos** [hashicorp/terraform#26030] opened 2020-08-28 02:13 UTC
### Terraform Version
Tested on both 0.13.1 and 0.13.0

### Terraform Configuration Files

```terraform
module "s3_some_name" {
  source  = "trussworks/s3-private-bucket/aws"
  version = "2.0.1"
  bucket  = "some-name"
}

module "aurora_production_serverless" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "2.22.0"

  name                  = "some-name"
  engine                = "aurora-postgresql"
  engine_mode           = "serverless"
  engine_version        = "10.7"
  replica_scale_enabled = false
  replica_count         = 0

  backtrack_window = 10 # ignored in serverless

  vpc_id               = aws_vpc.main.id
  db_subnet_group_name = aws_db_subnet_group.default.name
  monitoring_interval  = 60
  instance_type        = "db.r4.large"
  apply_immediately    = true
  skip_final_snapshot  = true
  storage_encrypted    = true
  deletion_protection  = true
  username             = "postgres"
  password             = "some-password"
  port                 = 5432
  database_name        = "some-name"

  scaling_configuration = {
    auto_pause               = true
    max_capacity             = 384
    min_capacity             = 2
    seconds_until_auto_pause = 300
    timeout_action           = "ForceApplyCapacityChange"
  }
}
```

### Debug Output
```
Terraform v0.13.1
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2020/08/28 01:49:33 [INFO] Terraform version: 0.13.1  
2020/08/28 01:49:33 [INFO] Go runtime version: go1.14.7
2020/08/28 01:49:33 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init", "-input=false"}
2020/08/28 01:49:33 [DEBUG] Attempting to open CLI config file: /tmp/cli.tfrc
2020/08/28 01:49:33 Loading CLI configuration from /tmp/cli.tfrc
2020/08/28 01:49:33 [DEBUG] Not reading CLI config directory because config location is overridden by environment variable
2020/08/28 01:49:33 [DEBUG] Using modified User-Agent: HashiCorp Terraform/0.13.1 (+https://www.terraform.io) TFC/60e80493dd
2020/08/28 01:49:33 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/08/28 01:49:33 [DEBUG] ignoring non-existing provider search directory /home/terraform/.terraform.d/plugins
2020/08/28 01:49:33 [DEBUG] ignoring non-existing provider search directory /home/terraform/.local/share/terraform/plugins
2020/08/28 01:49:33 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2020/08/28 01:49:33 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2020/08/28 01:49:33 [INFO] CLI command args: []string{"init", "-input=false"}
2020/08/28 01:49:33 [DEBUG] Using modified User-Agent: Terraform/0.13.1 TFC/60e80493dd
2020/08/28 01:49:33 [DEBUG] Using modified User-Agent: HashiCorp Terraform/0.13.1 (+https://www.terraform.io) TFC/60e80493dd
2020/08/28 01:49:33 [DEBUG] Using modified User-Agent: Terraform/0.13.1 TFC/60e80493dd
2020/08/28 01:49:33 [DEBUG] Using modified User-Agent: HashiCorp Terraform/0.13.1 (+https://www.terraform.io) TFC/60e80493dd
2020/08/28 01:49:33 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
Initializing modules...
2020/08/28 01:49:33 [DEBUG] Module installer: begin aws
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws is not yet installed
2020/08/28 01:49:33 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws prior to install of aws
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws has local path "./aws"
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws uses directory from parent: aws
2020/08/28 01:49:33 [DEBUG] Module installer: aws installed at aws
- aws in aws
2020/08/28 01:49:33 [DEBUG] Module installer: begin aws.db_name
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name is not yet installed
2020/08/28 01:49:33 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws.db_name prior to install of aws.db_name
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name is a registry module at terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] aws.db_name listing available versions of terraform-aws-modules/rds-aurora/aws at registry.terraform.io
2020/08/28 01:49:33 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/08/28 01:49:33 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2020/08/28 01:49:33 [DEBUG] fetching module versions from "https://registry.terraform.io/v1/modules/terraform-aws-modules/rds-aurora/aws/versions"
2020/08/28 01:49:33 [DEBUG] GET https://registry.terraform.io/v1/modules/terraform-aws-modules/rds-aurora/aws/versions
2020/08/28 01:49:33 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/terraform-aws-modules/rds-aurora/aws/versions
2020/08/28 01:49:33 [DEBUG] found available version "2.23.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.22.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.20.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.19.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.3.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.0.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.16.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.2.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.21.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.17.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.21.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.9.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.11.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.14.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.15.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.15.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.6.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.13.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.12.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.8.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.5.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.6.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.18.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.1.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.10.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.13.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.14.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.12.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.7.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.0.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.19.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.4.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.8.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.9.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.16.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.10.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.20.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "2.7.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.18.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.17.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "0.0.1" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.3.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.11.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.5.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.4.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] found available version "1.1.0" for terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [DEBUG] looking up module location from "https://registry.terraform.io/v1/modules/terraform-aws-modules/rds-aurora/aws/2.23.0/download"
2020/08/28 01:49:33 [DEBUG] GET https://registry.terraform.io/v1/modules/terraform-aws-modules/rds-aurora/aws/2.23.0/download
2020/08/28 01:49:33 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/terraform-aws-modules/rds-aurora/aws/2.23.0/download
Downloading terraform-aws-modules/rds-aurora/aws 2.23.0 for aws.db_name...
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name terraform-aws-modules/rds-aurora/aws 2.23.0 is available at "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz"
2020/08/28 01:49:33 [DEBUG] will download "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz?archive=tar.gz" to .terraform/modules/aws.db_name
2020/08/28 01:49:33 [TRACE] fetching "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz?archive=tar.gz" to ".terraform/modules/aws.db_name"
2020/08/28 01:49:33 [DEBUG] Module installer: begin aws.db_name
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name is not yet installed
2020/08/28 01:49:33 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws.db_name prior to install of aws.db_name
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name is a registry module at terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [TRACE] aws.db_name using already found available versions of terraform-aws-modules/rds-aurora/aws at registry.terraform.io
Downloading terraform-aws-modules/rds-aurora/aws 2.23.0 for aws.db_name...
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name terraform-aws-modules/rds-aurora/aws 2.23.0 is available at "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz"
2020/08/28 01:49:33 [DEBUG] will download "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz?archive=tar.gz" to .terraform/modules/aws.db_name
2020/08/28 01:49:33 [TRACE] fetching "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz?archive=tar.gz" to ".terraform/modules/aws.db_name"
2020/08/28 01:49:33 [DEBUG] Module installer: begin aws.db_name
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name is not yet installed
2020/08/28 01:49:33 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws.db_name prior to install of aws.db_name
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name is a registry module at terraform-aws-modules/rds-aurora/aws
2020/08/28 01:49:33 [TRACE] aws.db_name using already found available versions of terraform-aws-modules/rds-aurora/aws at registry.terraform.io
Downloading terraform-aws-modules/rds-aurora/aws 2.23.0 for aws.db_name...
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.db_name terraform-aws-modules/rds-aurora/aws 2.23.0 is available at "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz"
2020/08/28 01:49:33 [DEBUG] will download "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz?archive=tar.gz" to .terraform/modules/aws.db_name
2020/08/28 01:49:33 [TRACE] fetching "https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz?archive=tar.gz" to ".terraform/modules/aws.db_name"
2020/08/28 01:49:33 [DEBUG] Module installer: begin aws.bastion
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.bastion is not yet installed
2020/08/28 01:49:33 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws.bastion prior to install of aws.bastion
2020/08/28 01:49:33 [TRACE] ModuleInstaller: aws.bastion address "github.com/terraform-community-modules/tf_aws_bastion_s3_keys" will be handled by go-getter
2020/08/28 01:49:33 [DEBUG] will download "github.com/terraform-community-modules/tf_aws_bastion_s3_keys" to .terraform/modules/aws.bastion
2020/08/28 01:49:33 [TRACE] go-getter detectors rewrote "github.com/terraform-community-modules/tf_aws_bastion_s3_keys" to "git::https://github.com/terraform-community-modules/tf_aws_bastion_s3_keys.git"
2020/08/28 01:49:33 [TRACE] fetching "git::https://github.com/terraform-community-modules/tf_aws_bastion_s3_keys.git" to ".terraform/modules/aws.bastion"
Downloading github.com/terraform-community-modules/tf_aws_bastion_s3_keys for aws.bastion...
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.bastion "github.com/terraform-community-modules/tf_aws_bastion_s3_keys" was downloaded to .terraform/modules/aws.bastion
2020/08/28 01:49:34 [DEBUG] Module installer: aws.bastion installed at .terraform/modules/aws.bastion
2020/08/28 01:49:34 [DEBUG] Module installer: begin aws.platform
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.platform is not yet installed
2020/08/28 01:49:34 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws.platform prior to install of aws.platform
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.platform has local path "./platform"
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.platform uses directory from parent: aws/platform
- aws.bastion in .terraform/modules/aws.bastion
2020/08/28 01:49:34 [DEBUG] Module installer: aws.platform installed at aws/platform
2020/08/28 01:49:34 [DEBUG] Module installer: begin aws.bucket_name
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.bucket_name is not yet installed
2020/08/28 01:49:34 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws.bucket_name prior to install of aws.bucket_name
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.bucket_name is a registry module at trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] aws.bucket_name listing available versions of trussworks/s3-private-bucket/aws at registry.terraform.io
- aws.platform in aws/platform
2020/08/28 01:49:34 [DEBUG] fetching module versions from "https://registry.terraform.io/v1/modules/trussworks/s3-private-bucket/aws/versions"
2020/08/28 01:49:34 [DEBUG] GET https://registry.terraform.io/v1/modules/trussworks/s3-private-bucket/aws/versions
2020/08/28 01:49:34 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/trussworks/s3-private-bucket/aws/versions
2020/08/28 01:49:34 [DEBUG] found available version "2.0.9" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.1" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.10" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.3" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.4" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.7.3" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.8" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.7" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.6" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.5" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "2.0.2" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.5.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.6.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.7.2" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.7.1" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.4.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.7.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.3.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.2.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.1.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] found available version "1.0.0" for trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [DEBUG] looking up module location from "https://registry.terraform.io/v1/modules/trussworks/s3-private-bucket/aws/2.0.1/download"
2020/08/28 01:49:34 [DEBUG] GET https://registry.terraform.io/v1/modules/trussworks/s3-private-bucket/aws/2.0.1/download
2020/08/28 01:49:34 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/modules/trussworks/s3-private-bucket/aws/2.0.1/download
Downloading trussworks/s3-private-bucket/aws 2.0.1 for aws.bucket_name...
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.bucket_name trussworks/s3-private-bucket/aws 2.0.1 is available at "https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz//*?archive=tar.gz"
2020/08/28 01:49:34 [DEBUG] will download "https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz?archive=tar.gz" to .terraform/modules/aws.bucket_name
2020/08/28 01:49:34 [TRACE] fetching "https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz?archive=tar.gz" to ".terraform/modules/aws.bucket_name"
2020/08/28 01:49:34 [DEBUG] Module installer: begin aws.bucket_name
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.bucket_name is not yet installed
2020/08/28 01:49:34 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/aws.bucket_name prior to install of aws.bucket_name
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.bucket_name is a registry module at trussworks/s3-private-bucket/aws
2020/08/28 01:49:34 [TRACE] aws.bucket_name using already found available versions of trussworks/s3-private-bucket/aws at registry.terraform.io
2020/08/28 01:49:34 [TRACE] ModuleInstaller: aws.bucket_name trussworks/s3-private-bucket/aws 2.0.1 is available at "https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz//*?archive=tar.gz"
2020/08/28 01:49:34 [DEBUG] will download "https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz?archive=tar.gz" to .terraform/modules/aws.bucket_name
2020/08/28 01:49:34 [TRACE] fetching "https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz?archive=tar.gz" to ".terraform/modules/aws.bucket_name"
Downloading trussworks/s3-private-bucket/aws 2.0.1 for aws.bucket_name...
2020/08/28 01:49:34 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:67)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:27) source
code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "bucket_name"
(aws/s3.tf:12) source code from
"https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "bucket_name" (aws/s3.tf:1) source
code from
"https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:67)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:67)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:27) source
code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:67)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:27) source
code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:67)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:27) source
code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:67)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:27) source
code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "bucket_name"
(aws/s3.tf:12) source code from
"https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:107)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:67)
source code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "db_name" (aws/rds.tf:27) source
code from
"https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/archive/v2.23.0.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "bucket_name"
(aws/s3.tf:12) source code from
"https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz//*?archive=tar.gz":
bad response code: 403.


Error: Failed to download module

Could not download module "bucket_name" (aws/s3.tf:1) source
code from
"https://github.com/trussworks/terraform-aws-s3-private-bucket/archive/v2.0.1.tar.gz//*?archive=tar.gz":
bad response code: 403.
```

### Expected Behavior
Modules are downloaded without error

### Actual Behavior
The module download step fails while running `terraform init`. This happens both locally and on Terraform Cloud, and without any changes in the code. The local invocation started working again after ~5hrs, again, without any changes made.

Tried upgrading Terraform from 0.13.0 to 0.13.1, as well as change the version of both faulty modules, without success. It's been more than 24hrs since I started seeing this error. Running older versions of my infrastructure code that used to be successful on Terraform Cloud are now emitting the same errors

### Steps to Reproduce
1. Run `terraform init` using Terraform Cloud

### Additional Context
I'm happy to provide additional context on my account so that the exact runs can be identified.

### References
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/672
- https://github.com/hashicorp/terraform/issues/23829
- https://github.com/hashicorp/terraform/issues/18459

**Comment by jkodroff** [comment] 2020-08-28 13:01
Same issue here, but I'm seeing it with Atlantis 0.15/TF 0.13.1 and cannot reproduce the error on my local machine.

Quite the noodle-scratcher.

**Comment by alisdair** [comment] 2020-08-28 14:44
This is indeed a problem with the Terraform Registry's upstream provider, which is being worked on. Updates on this will be posted here: https://status.hashicorp.com/incidents/z42xmmmjt0rm

Closing as it's not a Terraform core bug. Thank you for reporting!

**Closed by alisdair** 2020-08-28 14:44 UTC
Labels: bug, new

**Comment by justincampbell** [comment] 2020-08-28 19:18
@jkodroff Would you happen to be running Atlantis in AWS us-east-2?

**Comment by jkodroff** [comment] 2020-08-28 20:25
Why yes I would!
