### ISSUE TITLE
Computed maps are assumed to be an immutable set of keys.

### ISSUE THREAD

**Issue by zaphar** [hashicorp/terraform#18863] opened 2018-09-14 16:01 UTC
While debugging a weird problem with the terraform provider for aws I think I've traced it to an interaction with terraform's state tracking of computed maps and string interpolation.

First a description of the problem, aws cloudformation stacks can have outputs. Those outputs can change over time without destroying or recreating the stack. The provider treats those outputs as a computed map. When you create a new stack and reference a key in the computed resource everything is fine. The diff shows that you are creating a new computed map and you can create the new stack.

However if you add a new output to the stack and try to reference that output anywhere in an interpolated variable then the interpolation will fail claiming the key does not exist in the map. This means you are stuck in a somewhat confusing set of steps to work around it by creating the outputs and running an apply before you can reference them.

From my reading of the code it seems there are three options to fix. 2 of them modify the way terraform works. And one of them works around it with the creation of a new resource.

The two options that change terraform are:

1. Add a notion in the terraform schema datamodel to support a map of keys => computed values. This would allow providers to give a way for users to tell terraform the keys they expect so that interpolation is possible.

2. Make string interpolation for computed maps more forgiving at the plan stage assuming that the new key will exist at apply stage at the expense of some safety.

If these are not possible then providers will need to create new resource types that are more like data providers in reality but allow you to specify the dependencies between them.

I guess now that I'm thinking about it a 4'th option that terraform could do is allow data providers to specify a dependency on a resource. That one seems really funky though.

**Comment by zaphar** [comment] 2018-09-19 06:59
Any feedback on this would be greatly appreciated. I'm sure the AWS integration folks would also appreciate feedback as well.

**Comment by mildwonkey** [comment] 2018-09-19 17:30
Hey @zaphar,
I have some vague feedback - it's not going to address your specific question but it's good information for you to have. 

If you don't already know, the terraform core team is hard at work on [terraform 0.12](https://www.hashicorp.com/blog/terraform-0-1-2-preview). Among other improvements, we are implementing a much more robust [type system](https://www.hashicorp.com/blog/terraform-0-12-rich-value-types). I highly recommend that you check out the blog posts. 

We don't have a specific release date just yet, but it's been our focus for several months and you'll find that there are many open terraform issues that pertain to how terraform deals with complex types, many of which will be fixed when 0.12 is released.

**Comment by zaphar** [comment] 2018-09-20 18:03
That's good news. If you need any early adopter/testing to verify that it fixes problems like the above let me know.

**Comment by apparentlymart** [comment] 2018-09-22 01:06
Hi @zaphar!

From reading your description of what happened it sounds like something happened out of order, causing Terraform to try to evaluate an expression referring to a new key before that new key was already stored in the state. Terraform's dependency graph should avoid this happening most of the time, but it sounds like you've found a situation where Terraform is making a poor assumption and evaluating an expression too early.

Thinking through the sequence of steps that Terraform would take here, I think I have a sense of what the problem is: the set of outputs is determined by some parts of the template JSON, but since neither Terraform nor the AWS provider currently interpret the template themselves, the provider can't predict during plan which output keys will be present after apply.

We _do_ have a mechanism in the provider SDK for dealing with this problem: the provider can implement logic to add additional annotations to the plan if it is able to predict changes to `Computed` attributes based on the changes to configuration attributes.

This means that _in principle_ the provider could its own parsing of the template to see which outputs are present in the new template, and then give Terraform Core an updated _planned_ value that reflects what it learned, allowing expressions to be evaluated as expected (though some of the keys may not have a known value yet, until after apply).

The challenge with this _particular_ situation (assuming we were okay with the provider parsing the CF template) is the `template_url` argument, which specifies the template _indirectly_ and thus prevents the AWS provider from seeing its source code.

To get this right, then, I think the provider would need to create a CloudFormation _changeset_ during plan, use the metadata about that changeset to update the computed attributes, and then execute that changeset during apply. This would have some nice advantages, such as allowing the Terraform diff to also summarize the changes that cloudformation _itself_ will make, but it would also leave a trail of abandoned changeset objects behind if users run `terraform plan` a lot during development, which is a common and recommended behavior.

The remaining "blunt" approach here would be for the provider to just mark the whole map as "computed" each time `template_body` or `template_url` are changed. That would mean that any expressions like `aws_cloudformation_stack.foo.outputs["bar"]` would itself return an unknown value (shown as `<computed>` in the diff for 0.11 and earlier), rather than failing, but with a significant cost: any other resource argument where an output is referenced would itself show as unknown during plan, which may cause objects to be replaced unnecessarily.

So with all of that said: this is technically an AWS provider bug, but it doesn't seem like there is a great solution to it within our current constraints, and I don't think Terraform 0.12 improvements are going to make any significant impact here; the provider just isn't able to give Terraform the additional information required for a correct result here.

**Comment by mildwonkey** [comment] 2019-07-02 17:10
Hi @zaphar !
Now that terraform 0.12 has released, we finally have a chance to re-review issues such as this one.
As @apparentlymart said in the previous comment, this situation is fundamentally up to the AWS provider to handle, not something that can be fixed by terraform core. 

A quick search turned up [an existing aws provider issue](https://github.com/terraform-providers/terraform-provider-aws/issues/5885), so I am going to close this.

Thank you!

**Closed by mildwonkey** 2019-07-02 17:10 UTC
Labels: bug, config, provider-sdk, thinking
