### ISSUE TITLE
mock_provider "tfe"

### ISSUE THREAD

**Issue by diogonborges** [hashicorp/terraform#34601] opened 2024-01-31 17:43 UTC
### Terraform Version

```shell
Terraform v1.7.2
on windows_386
+ provider registry.terraform.io/hashicorp/aws v5.34.0
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/tfe v0.51.1
```

### Terraform Configuration Files

```terraform
# main.tf

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    tfe = {
      version = "~> 0.51.1"
    }
  }
}

data "tfe_outputs" "my_output" {
  organization = "my-org"
  workspace    = "my-workspace"
}

module "credentials" {
  source = "./modules/s3_data"

  data_bucket_name = "my_company_bucket_name"
}

resource "local_file" "credentials_json" {
  filename = "credentials.json"
  content  = jsonencode(module.credentials.data)
}

output "some_prop" {
  value = data.tfe_outputs.my_output.values.bar
}
```

```terraform
# ./modules/s3_data/main.tf

variable "data_bucket_name" {
  type = string
}

data "aws_s3_object" "data_bucket" {
  bucket = var.data_bucket_name
  key    = "credentials.json"
}

output "data" {
  value = jsondecode(data.aws_s3_object.data_bucket.body)
}

```

```terraform
# main.tftest.hcl

mock_provider "aws" {
  override_data {
    target = module.credentials.data.aws_s3_object.data_bucket
    values = {
      body = "{\"username\":\"username\",\"password\":\"password\"}"
    }
  }
}

mock_provider "tfe" {
   override_data {
    target = data.tfe_outputs.my_output
    values = {
      body = "\"values\" : [\"bar\": \"dummy\" ]"
    }
  }
}

run "test" {
  assert {
    condition     = jsondecode(local_file.credentials_json.content).username == "username"
    error_message = "incorrect username"
  }

  assert {
    condition     = output.some_prop == "dummy"
    error_message = "incorrect override"
  }
}


```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

unknown complex type: dynamic
goroutine 307 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x81
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:16 +0x18
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x159
panic({0x2a91300, 0xfffb248})
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x23f
github.com/hashicorp/terraform/internal/moduletest/mocking.GenerateValueForType({{0x3671820, 0x4e938c0}})
        /home/runner/work/terraform/terraform/internal/moduletest/mocking/generate.go:105 +0x87b
github.com/hashicorp/terraform/internal/moduletest/mocking.GenerateValueForAttribute(0xff83fa0)
        /home/runner/work/terraform/terraform/internal/moduletest/mocking/generate.go:61 +0x320
github.com/hashicorp/terraform/internal/moduletest/mocking.MockedData.makeKnown({{{{0x0, 0x0}}, {0x0, 0x0}}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}}}, ...)
        /home/runner/work/terraform/terraform/internal/moduletest/mocking/values.go:203 +0x468
github.com/hashicorp/terraform/internal/moduletest/mocking.populateComputedValues.func1({0xfffb238, 0x1, 0x1}, {{{0x3671820, 0x4e938c0}}, {0x0, 0x0}})
        /home/runner/work/terraform/terraform/internal/moduletest/mocking/values.go:118 +0x247
github.com/zclconf/go-cty/cty.(*postorderTransformer).Exit(0xfffb218, {0xfffb238, 0x1, 0x1}, {{{0x3671820, 0x4e938c0}}, {0x0, 0x0}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/walk.go:94 +0x54
github.com/zclconf/go-cty/cty.transform({0xfffb238, 0x1, 0x1}, {{{0x3671820, 0x4e938c0}}, {0x0, 0x0}}, {0x365b7e8, 0xfffb218})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/walk.go:233 +0xd9a
github.com/zclconf/go-cty/cty.transform({0x0, 0x0, 0x0}, {{{0x3671520, 0xfffb0e8}}, {0x2a2f4c0, 0x11cc0880}}, {0x365b7e8, 0xfffb218})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/walk.go:220 +0x1028
github.com/zclconf/go-cty/cty.Transform(...)
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/walk.go:122
github.com/hashicorp/terraform/internal/moduletest/mocking.populateComputedValues({{{0x3671520, 0xfffb0e8}}, {0x2a2f4c0, 0x11cc0880}}, {{{{0x0, 0x0}}, {0x0, 0x0}}, {{0x0, 0x0}, ...}}, ...)
        /home/runner/work/terraform/terraform/internal/moduletest/mocking/values.go:90 +0x417
github.com/hashicorp/terraform/internal/moduletest/mocking.ComputedValuesForDataSource(...)
        /home/runner/work/terraform/terraform/internal/moduletest/mocking/values.go:47
github.com/hashicorp/terraform/internal/providers.(*Mock).ReadDataSource(0xf4769a0, {{0xe9e1da0, 0xb}, {{{0x3671520, 0xfffb0e8}}, {0x2a2f4c0, 0x11cc0880}}, {{{0x3671820, 0x4e938c0}}, {0x0, ...}}})
        /home/runner/work/terraform/terraform/internal/providers/mock.go:277 +0x37b
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).readDataSource(0x11ca2900, {0x367d1ac, 0xe9ab300}, {{{0x3671520, 0xfffb058}}, {0x2a2f4c0, 0x11cc0840}})
        /home/runner/work/terraform/terraform/internal/terraform/node_resource_abstract_instance.go:1562 +0x1192
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).planDataSource(0x11ca2900, {0x367d1ac, 0xe9ab300}, 0x45, 0x0)
        /home/runner/work/terraform/terraform/internal/terraform/node_resource_abstract_instance.go:1802 +0x1327
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xe9756e0, {0x367d1ac, 0xe9ab300})
        /home/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:105 +0x3c1
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0xe9756e0, {0x367d1ac, 0xe9ab300}, 0x2)
        /home/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:77 +0xa8
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xe97ea50, {0x367d1ac, 0xe9ab300}, {0x2e8d9958, 0xe9756e0})
        /home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:148 +0xb2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2e95620, 0xe9756e0})
        /home/runner/work/terraform/terraform/internal/terraform/graph.go:87 +0x3e6
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xe88dac0, {0x2e95620, 0xe9756e0}, 0xeb2df20)
        /home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x24f
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 286
        /home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xcee

### Expected Behavior

tfe is allow to be mocked

### Actual Behavior

terraform crash

### Steps to Reproduce

terraform init
terraform test

**Comment by liamcervante** [comment] 2024-02-01 09:48
Hi @diogonborges, thanks for filing this!

The root cause for this is the dynamic types that the `tfe_outputs` block is expecting data for the `values` and `nonsensitive_values` attributes. The mocking framework isn't handling these types properly and is crashing as a result of that. This is something I'll fix for an upcoming release. The mocking framework won't be able to generate values for dynamic attributes as it doesn't know the required types, so I think the right thing to do will be to have the framework report an error asking the user to always explicitly provide values for these attributes.

You can make this work in the meantime, while we wait for the fix to be merged and released, by making sure your `override_data` block for the `tfe_outputs` is providing values for all the dynamic attributes;

```hcl
mock_provider "tfe" {
   override_data {
    target = data.tfe_outputs.my_output
    values = {
        values = {
            bar: "dummy"
        }
        nonsensitive_values = {
            bar: "dummy"
        }
    }
  }
}
```

Hopefully this unblocks you!

**Closed** 2024-02-02 08:49 UTC
Labels: bug, confirmed, explained, terraform test
