### ISSUE TITLE
only evaluate the part of a ternary statement that is used

### ISSUE THREAD

**Issue by dansteen** [hashicorp/terraform#11574] opened 2017-01-31 19:31 UTC
### Terraform Version
0.8.5

### Affected Resource(s)
not a specific reasource, but rather the way ternary operations are processed

### Terraform Configuration Files
```
# we only build the the sns topics if the sns_env is the same as the env
resource "aws_sns_topic" "api" {
  count = "${var.env == var.sns_env ? 1 : 0}"
  name = "${var.name}-${var.env}"
}

resource "consul_keys" "api" {
  token = "${var.consul_token}"
  # host url
  key {
    delete = "true"
    path  = "service/app/${var.name}/${var.env}"
    value = "${var.env == var.sns_env ? "${aws_sns_topic.api.arn}" : "none" }"
  }
```

### Expected Behavior
I would expect it not to attempt to evaluate `${aws_sns_topic.api.arn}` in a case where `var.env != var.sns_env`.   That way, if that resource is not created things will still work.

### Actual Behavior
Instead it attempts to evaluate both parts of the ternary results, and I get the following error in a case where `var.env != var.sns_env`:

`* consul_keys.api_sns: resource count can't reference resource variable: aws_sns_topic.api.arn`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Thanks!

**Comment by osterman** [comment] 2017-05-05 23:44
I have this problem as well... We use `count` to enable/disable a resource. Unfortunately, it's not working. This snippet is taken from a `null_resource.trigger`:

```
green_arn_1 = "${aws_elasticsearch_domain.search.count > 0 ? aws_elasticsearch_domain.search.arn : ""}"
```

Error:
```
* null_resource.search: Resource 'aws_elasticsearch_domain.search' not found for variable 'aws_elasticsearch_domain.search.arn'
```

**Comment by dayglojesus** [comment] 2017-05-12 21:53
Obligatory me too post...

We began using this for an AMI auto-select feature in `0.8.4` and discovered this behaviour after upgrading to `0.9.5`.

```
variable "ami" {
  default = ""
}

data "aws_ami" "current_ami" {
  most_recent = true

  filter {
    name   = "tag:os"
    values = ["centos"]
  }

  owners = ["self"]
}

resource "aws_instance" "test" {

  ami = "${var.ami == "" ? data.aws_ami.current_ami.id : var.ami}"

}
```
Results in:
```
1 error(s) occurred:

* aws_instance.test: 1 error(s) occurred:

* aws_instance.test: At column 3, line 1: true and false expression types must match; have type unknown and type string in:

${var.ami == "" ? data.aws_ami.current_ami.id : var.ami}
```

It's a bit of a showstopper for us.

**Comment by apparentlymart** [comment] 2017-05-12 22:24
@dayglojesus in your case I think you are seeing #14399 rather than this issue. That was just a straight regression in the latest release, and a fix is ready for the next release.

**Comment by dayglojesus** [comment] 2017-05-12 22:42
@apparentlymart ah, good to know. thanks!

**Comment by holmesb** [comment] 2017-07-04 16:39
Another example:
```
variable "env" {
  default = "non-prod"
}
variable "vpc_id" {
  default = "vpc-abcd1234"
}
resource "aws_vpc" "mod" {
  count                 = "${var.env == "prod" ? 1 : 0}"
  cidr_block          = "10.0.0.0/24"
}
resource "aws_route_table" "public" {
  vpc_id            = "${var.env == "prod" ? aws_vpc.mod.id : var.vpc_id}"
}
```
Get error: Resource 'aws_vpc.mod' not found for variable 'aws_vpc.mod.id'

**Comment by hroussez** [comment] 2017-11-01 20:49
I'm running into a similar issue. My code looks like:
```
variable "enabled" {
  default = false
}

resource "aws_lb" "main" {
  ...
}

resource "aws_lb" "extra" {
  count = "${var.enabled}"
  ...
}

output "extra_dns_name" {
  value = "${var.enabled ? aws_lb.extra.dns_name : aws_lb.main.dns_name}"
}
```

I get the following error:
```
* output.extra_dns_name: Resource 'aws_lb.extra' not found for variable 'aws_lb.extra.dns_name'
```


Should I be doing it differently, or should we work on this issue?

**Comment by fractos** [comment] 2017-11-09 16:00
Just hit this too... massively annoying.  (0.9.10 and 0.10.3). Modified from the original code but it demonstrates the point:

```
data "aws_db_instance" "mydb" {
  count                  = "${var.use_db == true ? 1 : 0}"
  db_instance_identifier = "db-whatever"
}

data "template_file" "task_worker" {
  template = "${file("./task-definitions/worker.jsontemplate")}"

  vars {
    database_host            = "${var.use_db == true ? data.aws_db_instance.mydb.address : ""}"
  }
}
```
gives

```
Error running plan: 1 error(s) occurred:

* data.template_file.task_worker: 1 error(s) occurred:

* data.template_file.task_worker: Resource 'data.aws_db_instance.mydb' not found for variable 'data.aws_db_instance.mydb.address'
```

**Comment by JoseIbanez** [comment] 2017-11-13 17:37
Just tested in `v0.10.8` for a counter:

```
resource "aws_route" "route-n" {
  count                   = "${length(var.nfvs)}"
  route_table_id          = "${aws_route_table.RT_OUT.*.id[count.index]}"
  destination_cidr_block  = "99.99.0.1/32"
  network_interface_id    = "${count.index + 1  < length(var.nfvs) ? aws_network_interface.eni_OUT.*.id[count.index+1] : aws_network_interface.RO_eni_OUT.id }"
}
```
i get this error:

```
Error: Error running plan: 1 error(s) occurred:
* aws_route.route-n: 1 error(s) occurred:
* aws_route.route-n[1]: index 2 out of range for list aws_network_interface.eni_OUT.*.id (max 2) in:
${count.index + 1  < length(var.nfvs) ? aws_network_interface.eni_OUT.*.id[count.index+1] : aws_network_interface.RO_eni_OUT.id }
```

**Comment by m4ce** [comment] 2018-01-08 19:48
Same problem here with index out of range ...

**Comment by apparentlymart** [comment] 2018-01-10 00:49
Hi @dansteen, and everyone else here! Sorry about this limitation and thanks for reporting it.

This is the same issue being discussed in #11566. As mentioned there, a new version of the interpolation evaluator is coming which fixes this and many other limitations. Since we already have that issue open I'm going to close this one just to consolidate the discussion over there. That issue also contains some example workarounds for certain situations, which may be useful in the short term.

**Closed by apparentlymart** 2018-01-10 00:49 UTC
Labels: config, enhancement

**Comment by s2504s** [comment] 2018-02-14 17:53
As workaround I use method `join` 
```
resource "aws_sns_topic" "api" {
  count = "${var.env == var.sns_env ? 1 : 0}"
  name = "${var.name}-${var.env}"
}
If using:
resource "consul_keys" "api" {
  token = "${var.consul_token}"
  # host url
  key {
    delete = "true"
    path  = "service/app/${var.name}/${var.env}"
    value = "${var.env == var.sns_env ? "${join("", aws_sns_topic.api.*.arn)}" : "none" }"
  }
```
