### ISSUE TITLE
Terraform crashed!! When trying to deploy a VM in azure devops

### ISSUE THREAD

**Issue by chandan8893** [hashicorp/terraform#26072] opened 2020-09-01 04:43 UTC
<!--
Hi ,

 !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

##[error]Terraform command 'plan' failed with exit code '2'.

steps:

terraform init
terraform validate
terraform plan

Where plan is failing with the exit code 2..

When can we expect the resolution for the issue

**Comment by chandan8893** [comment] 2020-09-01 04:45
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!


##[error]Terraform command 'plan' failed with exit code '2'.

**Comment by roberthstrand** [comment] 2020-09-01 08:48
What version of Terraform are you running? If running the latest, there seem to be some issues with crashing in 0.13.1. Try pinning the version to 0.13.0 to see if that helps.

You should probably also upload the log file (make sure it doesn't contain private information) to make it easier to help you.

**Comment by AnnaProgrammer** [comment] 2020-09-01 15:45
2020-09-01T15:41:51.3884313Z   on main.tf line 2, in terraform:
2020-09-01T15:41:51.3897557Z    2:   required_version = "0.13.0"
2020-09-01T15:41:51.3898151Z 
2020-09-01T15:41:51.3899442Z This configuration does not support Terraform version 0.13.1. To proceed,
2020-09-01T15:41:51.3900330Z either choose another supported Terraform version or update this version
2020-09-01T15:41:51.3901528Z constraint. Version constraints are normally set for good reason, so updating
2020-09-01T15:41:51.3904367Z the constraint may lead to other errors or unexpected behavior.

**Comment by jbardin** [comment] 2020-09-01 16:04
Hi @chandan8893,

There isn't enough info here to what is actually going on. There a good chance this is a duplicate of #26011, but if it is not, please open a new issue with the information requested in the issue template.

**Closed by jbardin** 2020-09-01 16:04 UTC
Labels: bug, new
