### ISSUE TITLE
aws_route53_record.riemann_private: diffs didn't match during apply

### ISSUE THREAD

**Issue by jamtur01** [hashicorp/terraform#10863] opened 2016-12-20 14:22 UTC
### Terraform Version

v0.8.1

### Affected Resource(s)

- aws_route53_record

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "riemann_private" {
  zone_id = "${data.aws_route53_zone.environment.zone_id}"
  name    = "riemann.${data.aws_route53_zone.environment.name}"
  type    = "A"
  ttl     = "300"
  records = ["${aws_eip.riemann.private_ip}"]
}
```

### Debug Output

https://gist.github.com/jamtur01/51fcde74f87857f8d87044ccc797204d

**Comment by mitchellh** [comment] 2016-12-20 17:54
Hm, I can't reproduce this given your configuration directly. 

Based on the debug log it appears that between plan and apply the "private_ip" attribute of the EIP changed. Do you recall how this might have happened? (Specifically, it changed from 115 to 225)

**Comment by jamtur01** [comment] 2016-12-20 18:20
No idea - I am the only one running Terraform. And I am not manually changing anything.

**Comment by mitchellh** [comment] 2016-12-20 18:25
Yeah really strange... I wonder if it somehow changed over in AWS. It is a very small window though so I'm unsure how that happens. Let me dig in a bit and see if I can tease out a repro.

**Comment by mitchellh** [comment] 2016-12-21 19:03
Been giving this a shot this morning and haven't been able to get it to come up. Is this a repeatable, reproducible thing for you? Otherwise, I may just close this for now until we see another example and try to gather more information... Unfortunately with the information I have now I just haven't been able to get it to go. o.O Very odd. Sorry @jamtur01

**Closed by mitchellh** 2016-12-21 19:03 UTC
Labels: bug, core, waiting-response
