### ISSUE TITLE
Plan is ignored and the resource is not created claiming "each.value cannot be used in this context"

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#35762] opened 2024-09-23 12:05 UTC
### Terraform Version

```shell
1.5.0
AWS provider 5.68.0
```

### Terraform Configuration Files

```terraform
resource "aws_route53_record" "validation" {
  for_each = {
    for dvo in local.dvo : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }
  allow_overwrite = true
  name = each.value.name
  records = [each.value.record]
  ttl = 60
  type = each.value.type
  zone_id = data.aws_route53_zone.domain.id
}
```

### Debug Output

The resource is planned to be created:

```none
  # module.admin_domain.module.deployment-domain.aws_route53_record.validation["xxx"] will be created
  + resource "aws_route53_record" "validation" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z097755631MBEGKCJSTH0"
    }
```

### Expected Behavior

The resource is created.

### Actual Behavior

The resource is not created and TF doesn't try to do that with the following error:

```none
╷
│ Error: each.value cannot be used in this context
│ 
│   on .terraform/modules/admin_domain.deployment-domain/main.tf line 42, in resource "aws_route53_record" "validation":
│   42:   name = each.value.name
│ 
│ A reference to "each.value" has been used in a context in which it is
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
╵
```

### Steps to Reproduce

plan to a file
apply from the plan file

The problem is that it sees the required value in `for_each` while planning, but doesn't see it on applying.

**Comment by jbardin** [comment] 2024-09-23 12:44
Hi @speller,

Thanks for filing the issue. Can you verify that you experience the same problem with a current Terraform release? At a minimum you should not be using v1.5.0 for anything, the final patch release in that version was v1.5.7, but there could also have been some relevant changes between that and the current v1.9.6.

If this is still happening, we're going to need some more context to try and replicate the issue. Can you create a minimal reproducible example? The trace logs from the apply step may also help if that's not possible.

Thanks!

**Comment by jbardin** [comment] 2024-09-23 19:32
@speller I don't think the plan alone is sufficient, from what you describe it's a result of something which _isn't_ in the plan. So also having the configuration which reproduces the problem along with the trace logs from the cli, but whatever data you can provide will help! If email works for you, you can use my username `@hashicorp.com`.

**Comment by speller** [comment] 2024-09-24 02:00
I have a strange behavior on my local and in the ci/cd pipeline. On my local, it works. In the pipeline, it doesn't. I checked the module parameters and they look okay in the pipeline. This module has been working for a long time already with no issues. But in the current deployment refactoring, it stopped working.

**Comment by jbardin** [comment] 2024-09-24 17:53
(from the data shared out of band) I still don't have access to any of the gitlab modules, so it's hard to determine exactly how the data is flowing. I don't think the `each.value cannot be used in this context` is the relevant error here though, you have a concrete error from one resource in the failing output:

```
╷
│ Error: waiting for Auto Scaling Group (rev_mage2_13300_new_mk-1-20240924014857365600000004) capacity satisfied: timeout while waiting for state to become 'ok' (last state: 'want at least 1 healthy instance(s) registered to Load Balancer, have 0', timeout: 5m0s)
│
│   with module.service-mock[0].module.mock.aws_autoscaling_group.service[0],
│   on .terraform/modules/service-mock.mock/main.tf line 93, in resource "aws_autoscaling_group" "service":
│   93: resource "aws_autoscaling_group" "service" {
│
```

There's probably a bug there still, but it's that we reached the evaluation of the `for_each` expression at all after the error was returned -- I don't think the each.value output is your actual problem. I would focus on the autoscaling group problem first, and not worry about the each.value issue unless you can get that error in isolation.

**Comment by speller** [comment] 2024-09-26 02:40
@jbardin all modules including the main configuration are in the plan file archive in the `tfconfig` directory.
I have sent you my data as is. If I delete this autoscaling group, the issue is the same. But as I mentioned in a follow-up email, I solved it by cutting upper-case symbols from being passed to AWS route53 and certificate stuff. It looks like an issue in the AWS plugin that is messing up the core TF code.

**Comment by jbardin** [comment] 2024-09-26 15:07
Thanks @speller. I'll close this for now, since it's going to be hard to trace problems caused by a legacy provider misbehavior through modules we don't have.

**Closed by jbardin** 2024-09-26 15:07 UTC
Labels: bug, new, waiting for reproduction
