### ISSUE TITLE
Terraform treats 'for' attribute in complex variable type as invalid 'for' expression

### ISSUE THREAD

**Issue by atikhono** [hashicorp/terraform#32284] opened 2022-11-24 12:03 UTC
### Terraform Version

```shell
Terraform v1.3.5
on darwin_amd64
```

### Terraform Configuration Files

```terraform
variable "rules" {
  type = object({
    for         = string
    labels      = map(string)
    annotations = map(string)
  })
}

output "rules" {
  value = var.rules
}
```

### Debug Output

```
2022-11-24T14:59:25.189+0300 [INFO]  Terraform version: 1.3.5
2022-11-24T14:59:25.189+0300 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2022-11-24T14:59:25.189+0300 [DEBUG] using github.com/hashicorp/hcl/v2 v2.15.0
2022-11-24T14:59:25.189+0300 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2022-11-24T14:59:25.189+0300 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2022-11-24T14:59:25.189+0300 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2022-11-24T14:59:25.189+0300 [INFO]  Go runtime version: go1.19.3
2022-11-24T14:59:25.189+0300 [INFO]  CLI args: []string{"/usr/local/Cellar/tfenv/2.0.0/versions/1.3.5/terraform", "plan"}
2022-11-24T14:59:25.189+0300 [DEBUG] Attempting to open CLI config file: /Users/atikhonova/.terraformrc
2022-11-24T14:59:25.190+0300 [INFO]  Loading CLI configuration from /Users/atikhonova/.terraformrc
2022-11-24T14:59:25.190+0300 [DEBUG] Explicit provider installation configuration is set
2022-11-24T14:59:25.190+0300 [INFO]  CLI command args: []string{"plan"}
╷
│ Error: Invalid type specification
│ 
│   on main.tf line 2, in variable "rules":
│    2:   type = object({
│    3:     for         = string
│    4:     labels      = map(string)
│    5:     annotations = map(string)
│    6:   })
│ 
│ Object type constructor requires a map whose keys are attribute names and whose values are the corresponding attribute types.
╵
╷
│ Error: Invalid 'for' expression
│ 
│   on main.tf line 3, in variable "rules":
│    2:   type = object({
│    3:     for         = string
│ 
│ For expression requires variable name after 'for'.
╵
```

### Expected Behavior

Terraform should process the variable declaration and ask or input ("var.rules")

### Actual Behavior

Terraform failed with error "Invalid 'for' expression"

### Steps to Reproduce

1. Put the provided configuration file in main.tf file
2. `terraform plan`

**Comment by lowryxiao** [comment] 2022-11-25 06:33
Hi @atikhono
Guess all you want to do is creating a variable(rules) with the input from stdin and showing it as output, right?
Let’s make it simple for its structure.
like this one:

`
# cat main.tf                                                                                                                                                  
variable "rules" {
  type = object({
    for         = string
  })
}
output "rules" {
  value = var.rules
}
`

My 2 cents for this error is you use the reserved keyword(for) of terraform, if you rename it to as other name, like for1 it works.

`
# cat main.tf                                                                                                                                                  
variable "rules" {
  type = object({
    for         = string
  })
}
output "rules" {
  value = var.rules
}
`

`
terraform plan                                                                                                                                                ✔ | fcp-dev ⎈
2022-11-25T13:48:07.518+0800 [INFO]  Terraform version: 1.3.5
2022-11-25T13:48:07.519+0800 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2022-11-25T13:48:07.519+0800 [DEBUG] using github.com/hashicorp/hcl/v2 v2.15.0
2022-11-25T13:48:07.519+0800 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2022-11-25T13:48:07.519+0800 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2022-11-25T13:48:07.519+0800 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2022-11-25T13:48:07.519+0800 [INFO]  Go runtime version: go1.19.3
2022-11-25T13:48:07.519+0800 [INFO]  CLI args: []string{"terraform", "plan"}
2022-11-25T13:48:07.519+0800 [DEBUG] Attempting to open CLI config file: /Users/fenxiao/.terraformrc
2022-11-25T13:48:07.519+0800 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2022-11-25T13:48:07.519+0800 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2022-11-25T13:48:07.519+0800 [DEBUG] ignoring non-existing provider search directory /Users/fenxiao/.terraform.d/plugins
2022-11-25T13:48:07.519+0800 [DEBUG] ignoring non-existing provider search directory /Users/fenxiao/Library/Application Support/io.terraform/plugins
2022-11-25T13:48:07.519+0800 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2022-11-25T13:48:07.519+0800 [INFO]  CLI command args: []string{"plan"}
2022-11-25T13:48:07.521+0800 [DEBUG] New state was assigned lineage "c0b0d50e-f484-a103-4aa1-8e9e16b0e445"
2022-11-25T13:48:07.521+0800 [DEBUG] checking for provisioner in "."
2022-11-25T13:48:07.523+0800 [DEBUG] checking for provisioner in "/usr/local/bin"
2022-11-25T13:48:07.523+0800 [INFO]  backend/local: starting Plan operation
2022-11-25T13:48:07.542+0800 [DEBUG] backend/local: will prompt for input of unset required variables [rules]
2022-11-25T13:48:07.542+0800 [DEBUG] command: asking for input: "var.rules"
var.rules
  Enter a value: {"for1"="test"}

2022-11-25T13:48:08.835+0800 [DEBUG] Building and walking validate graph
2022-11-25T13:48:08.835+0800 [DEBUG] ReferenceTransformer: "var.rules" references: []
2022-11-25T13:48:08.835+0800 [DEBUG] ReferenceTransformer: "output.rules (expand)" references: [var.rules]
2022-11-25T13:48:08.835+0800 [DEBUG] Starting graph walk: walkValidate
2022-11-25T13:48:08.836+0800 [INFO]  backend/local: plan calling Plan
2022-11-25T13:48:08.836+0800 [DEBUG] Building and walking plan graph for NormalMode
2022-11-25T13:48:08.836+0800 [DEBUG] ReferenceTransformer: "var.rules" references: []
2022-11-25T13:48:08.836+0800 [DEBUG] ReferenceTransformer: "output.rules (expand)" references: [var.rules]
2022-11-25T13:48:08.836+0800 [DEBUG] Starting graph walk: walkPlan
2022-11-25T13:48:08.836+0800 [DEBUG] building apply graph to check for errors
2022-11-25T13:48:08.836+0800 [DEBUG] ReferenceTransformer: "var.rules" references: []
2022-11-25T13:48:08.836+0800 [DEBUG] ReferenceTransformer: "output.rules (expand)" references: [var.rules]
2022-11-25T13:48:08.836+0800 [INFO]  backend/local: plan operation completed

Changes to Outputs:
  + rules = {
      + for1 = "test"
    }

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure
`

**Comment by apparentlymart** [comment] 2022-11-28 18:19
Hi @atikhono!

As @lowryxiao noted, `for` at the beginning of an object constructor is a reserved word which tells Terraform that this is a `for` expression instead of a normal object constructor.

There are two different ways to "escape" that behavior that don't require renaming your attribute:

* Reorder the attributes so that `for` isn't the first one in the sequence. This token is reserved only in the first position, so if you place any other attribute first then Terraform will understand it as an attribute name.
* Write `"for"` (in quotes) instead of `for`, which then makes it clear to Terraform that you intend to use the literal name `for` instead of the reserved keyword `for` in this position.

However, because each user of this module will need to remember to do one of the two options above each time they assign a value to this input variable, it may be better for usability to select a different name that doesn't have this ambiguity.

**Comment by crw** [comment] 2022-12-03 01:29
Closing per "working as designed" designation.

**Closed by crw** 2022-12-03 01:29 UTC
Labels: bug, config, working as designed
