### ISSUE TITLE
Force recreation of dependent resources within loop construct

### ISSUE THREAD

**Issue by yangmillstheory** [hashicorp/terraform#13698] opened 2017-04-17 00:54 UTC
### Terraform Version
```
test terraform -v
Terraform v0.9.2

Your version of Terraform is out of date! The latest version
is 0.9.3. You can update by downloading from www.terraform.io
```

### Affected Resource(s)
Terraform core.

### Terraform Configuration Files
`alb/main.tf`
```hcl
variable "names" {
  type = "list"
}

resource "aws_alb_target_group" "default" {
  count    = "${length(var.names)}"
  name     = "${element(var.names, count.index)}-default"
  port     = 80
  protocol = "HTTP"
  vpc_id   = "vpc-936943f7"

  health_check {
    path = "/ping"
  }
}

resource "aws_alb" "api" {
  count    = "${length(var.names)}"
  name     = "${element(var.names, count.index)}"
  internal = true
  subnets  = ["subnet-5fa21207", "subnet-f3166785", "subnet-f3166785"]
}

resource "aws_alb_listener" "api_http" {
  count             = "${length(var.names)}"
  load_balancer_arn = "${element(aws_alb.api.*.arn, count.index)}"
  port              = "80"
  protocol          = "HTTP"

  default_action {
    target_group_arn = "${element(aws_alb_target_group.default.*.arn, count.index)}"
    type             = "forward"
  }

  lifecycle = {
    create_before_destroy = true
  }
}
```
***

`main.tf`

```hcl
provider "aws" {
  region  = "us-west-2"
  profile = "yangmillstheory"
}

module "alb" {
  source = "./alb"

  names = [
    "foo",
    "bar",
  ]
}
```
### Debug Output
[This is the output of `terraform plan` when adding another ALB.](https://gist.github.com/yangmillstheory/0fa18495000cd2f6b88ec88e1d80346c)

### Expected Behavior
The plan should be purely additive.

### Actual Behavior
The existing ALB listeners are force-recreated (because Terraform can't tell which ARNs have changed?). 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Add one ALB name to `main.tf`, `"baz"` as in the gist above.
2. `terraform plan`

### Important Factoids

* my AWS account has almost no resources, haven't run anything on it
* at work, this causes minor outages when adding/removing/modifying ALBs, since we run health checks on our ALBs periodically

***

Is there a way to make the plan purely additive?

**Comment by grubernaut** [comment] 2017-04-17 14:16
Hi @yangmillstheory, thanks for the issue!

Currently this is a dupe of #3449, closing as such. Happy to discuss further as well. Thanks!

**Closed by grubernaut** 2017-04-17 14:16 UTC
