### ISSUE TITLE
Resource still contains unknown values during apply

### ISSUE THREAD

**Issue by Dharmendrajoga** [hashicorp/terraform#28435] opened 2021-04-19 08:35 UTC
Here is the error log, Can someone please help here

module.pubsub_destination.google_pubsub_topic.topic: Creation complete after 7s [id=projects/nike-mcep-sbx/topics/Project-factory-pub-sub]
Error: configuration for module.log_export.google_logging_project_sink.sink[0] still contains unknown values during apply (this is a bug in Terraform; please report it!)

**Comment by jbardin** [comment] 2021-04-19 13:01
Hi @Dharmendrajoga,

Thanks for filing the issue, however we need much more information to start diagnosing the problem here. Can you please edit the entry to include the information requested in the issue template? If you are not sure how to go about troubleshooting, support is available in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by Dharmendrajoga** [comment] 2021-04-19 14:36
module "log_export" {
  source  = "terraform-google-modules/log-export/google"
  version = "5.1.0"

  destination_uri = module.pubsub_destination[0].destination_uri
  filter          = var.log_filter
  log_sink_name   = var.sink_name
  parent_resource_id     = var.parent_resource_id

  unique_writer_identity = true
}

**Comment by jbardin** [comment] 2021-04-19 17:45
Hi @Dharmendrajoga,

Unfortunately that module block is not sufficient to reproduce or diagnose the error.
You may want to test your configuration with the latest v0.15 release to verify that the issue isn't already fixed. If the issue still persists, a complete configuration showing how all the module inputs are derived would help, as well as the steps used to reproduce the issue.

**Comment by jbardin** [comment] 2021-05-14 13:34
Closing as we have no reproduction. If this issue is still reproducible with the latest release of Terraform, please file a new issue with the requested information in the issue template.

Thanks!

**Closed by jbardin** 2021-05-14 13:34 UTC
Labels: bug, new, waiting for reproduction, waiting-response
