### ISSUE TITLE
panic: not a collection type - on azurerm cognitive services

### ISSUE THREAD

**Issue by psteinds** [hashicorp/terraform#26023] opened 2020-08-27 18:05 UTC
### Terraform Version

```
0.13.1
```

### Terraform Configuration Files

```terraform
resource "azurerm_cognitive_account" "redactedtextanalytics" {
  name                = "redatctedtextanalytics"
  resource_group_name = data.azurerm_resource_group.myresourcegroup.name
  location            = "East US 2"
  kind                = "TextAnalytics"

  sku_name = "S2"

  tags = {
    createdby = "terraform"
  }
}
```

### Debug Output

```
Acquiring state lock. This may take a few moments...
data.azurerm_resource_group.myresourcegroup: Refreshing state... [id=/subscriptions/redacted/resourceGroups/myresourcegroup]
azurerm_cognitive_account.caname: Refreshing state... [id=/subscriptions/redacted/resourceGroups/myresourcegroup/providers/Microsoft.CognitiveServices/accounts/caname]
panic: not a collection type
goroutine 96 [running]:
github.com/zclconf/go-cty/cty.Type.ElementType(0x38e45e0, 0xc0004f0cd8, 0xc000481aa0, 0x8)
	github.com/zclconf/go-cty@v1.5.1/cty/collection.go:25 +0xba
github.com/hashicorp/terraform/terraform.createEmptyBlocks(0xc000fb4090, 0x38e45e0, 0xc0004f0ce8, 0x2efeb80, 0xc0013fa390, 0x38e45e0, 0xc0004f0d68, 0x2efeb80, 0xc0019450e0)
	github.com/hashicorp/terraform/terraform/eval_read_data_plan.go:242 +0x202
github.com/hashicorp/terraform/terraform.dataObjectHasChanges(0xc000fb4090, 0x38e45e0, 0xc0004f0ce8, 0x2efeb80, 0xc0013fa390, 0x38e45e0, 0xc0004f0d68, 0x2efeb80, 0xc0019450e0, 0x0, ...)
	github.com/hashicorp/terraform/terraform/eval_read_data_plan.go:211 +0x19e
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc000f62000, 0x3926080, 0xc000a51ee0, 0x1, 0x1, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval_read_data_plan.go:107 +0x1238
github.com/hashicorp/terraform/terraform.EvalRaw(0x387c8c0, 0xc000f62000, 0x3926080, 0xc000a51ee0, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc00095f6a0, 0x3926080, 0xc000a51ee0, 0x1, 0x1, 0x6, 0xc00005d010)
	github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x387c320, 0xc00095f6a0, 0x3926080, 0xc000a51ee0, 0x2eb3460, 0x4b98942, 0x2e12f00, 0xc000516ef0)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.Eval(0x387c320, 0xc00095f6a0, 0x3926080, 0xc000a51ee0, 0xc00095f6a0, 0x387c320, 0xc00095f6a0, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x32443e0, 0xc0005165c0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/graph.go:73 +0xc77
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00005cf00, 0x32443e0, 0xc0005165c0, 0xc000d70200)
	github.com/hashicorp/terraform/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	github.com/hashicorp/terraform/dag/walk.go:309 +0x11d7
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
### Crash Output

https://gist.github.com/psteinds/6d06371345096452fff6406ba44466a7

### Expected Behavior

Like with version 0.12.28 it should successfully poll the existing infrastructure.

### Actual Behavior

terraform crashed when it got a response from the azure api.

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

This works (doesn't crash) on terraform version 0.12.28 with the same version of the azurerm provider (provider.azurerm v2.25.0. which is the latest as of this writing)

**Comment by alisdair** [comment] 2020-08-27 18:08
Thanks for reporting this! The issue looks like a duplicate of #26011, so I'm closing to keep the discussion focused over there.

**Closed by alisdair** 2020-08-27 18:08 UTC
Labels: bug, new

**Comment by rcyrus** [comment] 2020-08-27 19:20
I also have this issue on a fresh project and have additional anecdotal info. 

First `terraform apply` on a "virgin" resource group works fine. If i run `terraform plan` or `apply` after resource creation I get this same crash. 

Also, since this is a fresh project I didn't notice any problems until I added data elements to my configuration. If i remove them then everything works fine again. 

My data elements use `azurerm_subnet` resource. 

Terraform v0.13.1
Azurerm 2.24.0
