### ISSUE TITLE
on-destroy remote-exec provisioner can not be executed within an aws_cloudformation_stack resource

### ISSUE THREAD

**Issue by AlexSH001** [hashicorp/terraform#26194] opened 2020-09-10 02:51 UTC
### Terraform Version

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/aws v3.5.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.1.2
...
```

### Terraform Configuration Files

```terraform
resource "aws_cloudformation_stack" "bastion_stack" {
#...
  provisioner "remote-exec" {
    when = destroy
    connection {
      type        = "ssh"
      user        = "centos"
      private_key = file(var.ssh_private_key_file)
      host        = self.outputs["BastionHostIP"]
      agent       = false
    }
    inline = [
      "./cleanup.sh",
    ]
}
```

### Debug Output

```
Error: Invalid reference from destroy provisioner
in resource "aws_cloudformation_stack" "bastion_stack":
24: private_key = file(var.ssh_private_key_file)
Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.
References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.
```
### Expected Behavior

It should be able to execute on-destroy remote-exec provisioner in aws_cloudformation_stack

### Actual Behavior

remote-exec not be executed
### Steps to Reproduce

`terraform destroy`

### Additional Context

I tried to upgrade the terraform from 0.12.12 to a newer one, currently it ls 0.13.1.
And previously, it worked in a non_resource to clean up some addition infras when destroy, for which were not created by terraform.
After upgrade, it told me that it was not allowed to refer some other resource when destroy, it should be within the particular resource. so I moved it to the resource which provisioning a bastion that I need it to run the clean up script. Failed with errors.

**Comment by alisdair** [comment] 2020-09-17 17:12
Hi @AlexSH001, thanks for reporting this issue.

This is intentional behaviour, added in #23559 as a deprecation and converted to an error in #24083. [We added a section to the 0.13 upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html#destroy-time-provisioners-may-not-refer-to-other-resources) which suggests a migration path forward for users who need destroy provisioners, using `null_resource`.

I'm marking this as closed because I believe it is working as intended.

**Closed by alisdair** 2020-09-17 17:12 UTC
Labels: bug, new
