### ISSUE TITLE
Terraform crashed on plan of resources dependent on locally calculated counts

### ISSUE THREAD

**Issue by lisajluo** [hashicorp/terraform#24014] opened 2020-02-03 02:20 UTC
### Terraform Version
```
Terraform v0.12.20
+ provider.archive v1.3.0
+ provider.aws v2.47.0
+ provider.cloudflare v2.1.0
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Terraform Configuration Files
I'm attempting to create a TF module for API gateway integrated with lambdas (a nested module). Since module count is not currently supported, I'm working around this by providing a list of lambda attributes to the lambda module. Unfortunately, TF bugs out on this count, despite it being completely calculable within locals (I tested this by commenting out all the resources and outputing the local values). In an attempt to deploy the resources after uncommenting various bits at a time (since I can't target the locals), Terraform crashed.

The first error:
```
Error: Invalid count argument

  on .terraform/modules/edge_use1.api_gateway.integrated_lambdas/logs.tf line 10, in resource "aws_cloudwatch_log_group" "lambda":
  10:   count             = length(local.lambda_list)
```

This is the calculable local:

```
  # Create a list of size 1 to make count calculations easier
  lambda_list = var.lambda_list == null ? [{
    name                           = var.name
    source_files                   = var.source_files
    source_dir                     = var.source_dir
    zip_file                       = var.zip_file
    handler                        = var.handler
    environment                    = var.environment
    schedule_expression            = var.schedule_expression
    event_pattern                  = var.event_pattern
    runtime                        = var.runtime
    timeout                        = var.timeout
    publish                        = var.publish
    memory                         = var.memory
    reserved_concurrent_executions = var.reserved_concurrent_executions
    single_invocation_payload      = var.single_invocation_payload
  }] : var.lambda_list
```

This seems to work fine if the lambda module is top-level, but not when nested within another module.

### Crash Output
[Attached.](https://gist.github.com/lisajluo/0697eb906a9f3912d76af7f3b88f1f2d)

**Comment by jbardin** [comment] 2020-02-03 22:52
Hi @lisajluo,

Thanks for the crash report. Unfortunately we're going to need a more complete configuration to fully diagnose the error.

The crash is happening in a list of objects, where the `query_string` attribute is a different type in different objects, going from a dynamic type to a boolean.  Would it be possible to include more information about the config to try and reproduce this?

**Comment by lisajluo** [comment] 2020-02-04 00:57
Hi @jbardin ,

Unfortunately I've backed out of the majority of the config changes (mostly due to blocking on the count calculation, which would still be an issue even if the crash were resolved), but I'll try to repro as much as I can here:

Since module count is still not supported (separate from the count calculation issue above :) ), I worked around that by creating a list input to pass to the lambda module. This looked like so:

```
  type = list(object({
    query_string                   = map(any)
    path                           = string
    http_method                    = string
    name                           = string
    source_files                   = list(string)
    source_dir                     = string
    handler                        = string
    environment                    = map(string)
    schedule_expression            = string
    event_pattern                  = string
    runtime                        = string
    timeout                        = number
    publish                        = bool
    memory                         = number
    reserved_concurrent_executions = number
    single_invocation_payload      = string
    zip_file                       = string
  }))
```

I then passed in lambdas that looked like so:

```
locals {
  default_lambda_attributes = {
    source_dir                     = null
    zip_file                       = "${path.module}/../../../package.zip"
    source_files                   = []
    runtime                        = "python3.8"
    timeout                        = 30
    publish                        = true
    memory                         = null
    reserved_concurrent_executions = null
    single_invocation_payload      = null
    event_pattern                  = null
    schedule_expression            = null
    environment = {
      PGUSER     = var.database_user
      PGPASSWORD = var.database_password
      PGHOST     = var.database_host
      PGPORT     = var.database_port
      PGDATABASE = var.database_name
    }
    query_string = {}
    path        = null
    http_method = null
  }
}

...

 module "api_gateway" {
   source = "..."

  lambdas = [for lambda in [
    {
      name        = "..."
      path        = "/path/{uuid}/"
      http_method = "POST"
      handler     = "..."
    },
  ] : merge(local.default_lambda_attributes, lambda)]
}
```

I don't believe I'd gotten to the point of populating `query_strings` yet, but was just passing in an empty map by default (see above) at the point of the crash, but I can't be sure. If I did pass in a map, I would have been attempting to pass in a map of string to bool like so:

```
query_strings = {
  "uuid" = true
}
```

Wasn't sure if it would coerce properly, but if not I was planning to convert to map(string) in the next step. Is that what caused the crash?

**Comment by jbardin** [comment] 2020-02-04 22:06
Thanks for the update. 

Changes are this was caused by the input passing through the `merge` function, and containing a value somewhere that was not yet known during plan.

If the type was actually resolvable, the issue I just opened at #24024  should take care of it, so I'll close this as a duplicate for now.

Thanks!

**Closed by jbardin** 2020-02-04 22:06 UTC
Labels: config, crash
