### ISSUE TITLE
hashicorp/terraform:full still 0.13.4 instead of 0.13.5

### ISSUE THREAD

**Issue by bnelson729** [hashicorp/terraform#26918] opened 2020-11-13 01:47 UTC
hashicorp/terraform:full was deployed most recently with 0.13.4 instead of the same version as hashicorp/terraform:latest which is 0.13.5.

**Comment by jbardin** [comment] 2020-11-13 18:53
Duplicate of #26903

**Closed by jbardin** 2020-11-13 18:53 UTC
