### ISSUE TITLE
The format of the plan output has changed since v0.14

### ISSUE THREAD

**Issue by hieki** [hashicorp/terraform#27585] opened 2021-01-25 08:05 UTC
### Terraform Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~>3.0"
    }
  }

  required_version = ">=0.14.5"
}

resource "null_resource" "foo" {}

```

### Expected Behavior
I think the diff output should be separated by hyphens.

### Actual Behavior
Since v0.14, the hyphen separator on one side has disappeared.

But I don't know if this is the change that was supposed to happen.
At least the output comment of the deprecated https://github.com/hashicorp/terraform-github-actions plan was broken.

### Steps to Reproduce

1. `tfenv use 0.14.5`
2. `terraform init`
3. 
```
terraform plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.foo will be created
  + resource "null_resource" "foo" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```
4. `tfenv use 0.13.6` and edit `required_version = ">=0.13.6"`
5. `terraform init`
6. 
```
terraform plan

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.foo will be created
  + resource "null_resource" "foo" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### References
v0.14 includes improvements to the plan output.
- https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-general-availability

**Comment by pselle** [comment] 2021-01-25 16:42
@hieki Hello! We have indeed changed the plan output in the 0.14 release -- plan output is not considered a stable interface, we recommend using `-json` formats if you need consistent machine-readable output. Could you elaborate on what bug you are reporting?

**Comment by hieki** [comment] 2021-01-26 06:42
Thanks for responding, @pselle

Up to Terraform v0.13, this is the output of the plan.

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------ # This hyphen separator has disappeared in v0.14

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.foo will be created
  + resource "null_resource" "foo" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

This change in output becomes a problem when you create a parser such as https://github.com/hashicorp/terraform-github-actions/blob/master/src/terraform_plan.sh#L30

However, I agree with the opinion that it is not correct to expect a certain format for human-readable output.

I found out that I could do this.

```
terraform plan -out=output
terraform show output

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.foo will be created
  + resource "null_resource" "foo" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
``` 

This will mechanically output the differences between human readable plan.

**Comment by pselle** [comment] 2021-01-26 16:41
Thank you for the clarification! Yes, I believe we intended to remove that as part of the larger goal of having more concise plan output in the human-readable plan. Glad that saving the plan is working for your use case. I'm closing this as "working as designed" as I don't believe we have plans to add back that delineation.

**Closed by pselle** 2021-01-26 16:41 UTC
Labels: bug, working as designed
