### ISSUE TITLE
Unexpected type change when iterating over map

### ISSUE THREAD

**Issue by sjauld** [hashicorp/terraform#34557] opened 2024-01-23 01:04 UTC
### Terraform Version

```shell
Terraform v1.7.0
on linux_amd64
```

### Terraform Configuration Files

```tf
locals {
  input = {
    fruit  = "apple"
    number = 6
    static = [{
      "number" = 1
      "string" = "one"
    }]
    to_be_extended = [
      { name = "anne" },
      { name = "bob" },
    ]
  }

  output = { for k, v in local.input :
  k => k == "to_be_extended" ? concat(v, [{ name = "carol" }]) : v }
}

output "input" {
  value = local.input
}

output "output" {
  value = local.output
}
```

### Debug Output

```
Outputs:

input = {
  "fruit" = "apple"
  "number" = 6
  "static" = [
    {
      "number" = 1
      "string" = "one"
    },
  ]
  "to_be_extended" = [
    {
      "name" = "anne"
    },
    {
      "name" = "bob"
    },
  ]
}
output = {
  "fruit" = "apple"
  "number" = 6
  "static" = tolist([
    tomap({
      "number" = "1"
      "string" = "one"
    }),
  ])
  "to_be_extended" = tolist([
    {
      "name" = "anne"
    },
    {
      "name" = "bob"
    },
    {
      "name" = "carol"
    },
  ])
}
```

### Expected Behavior

The value of output.static[0].number should be 1 (e.g. an int64).

### Actual Behavior

The value of output.static[0].number is "1" (e.g. a string).

### Steps to Reproduce

1. `terraform apply`

**Comment by jbardin** [comment] 2024-01-23 14:49
Hi @sjauld,

A `map` type can only contain a single element type, so there is no way for an iteration over a map to return both a `number` and a `string`. Since automatic conversion to `string` is allowed, Terraform converts the object literal to a `map(string)`, implicitly converting the `1` to `"1"` in order to arrive at a consistent result for the expression. These automatic conversions can be surprising at times, and we're looking into adding explicit type constraints for output values to help users ensure the resulting type is exactly what they expect.

Since Terraform is working as designed, and this does not represent a bug I'm going to close the issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2024-01-23 14:49 UTC
Labels: bug, new
