### ISSUE TITLE
Ternary operator doesn't work for some objects

### ISSUE THREAD

**Issue by r-bennett** [hashicorp/terraform#26096] opened 2020-09-02 13:41 UTC
### Terraform Version

```
Terraform v0.13.1
```
Also applies to `v0.12.28`.

### Terraform Configuration Files

```terraform
locals {
  condition = true

  a = {
    foo = "hodor"
    bar = ["frodo"]
  }

  b = {
    baz = "hodor"
  }

  c = local.condition ? local.a : local.b
}
```

### Expected Behavior
`local.c` should have been assigned the value from `local.a`

### Actual Behavior
```
$ terraform plan

Error: Inconsistent conditional result types

  on config.tf line 13, in locals:
  13:   c = local.condition ? local.a : local.b
    |----------------
    | local.a is object with 2 attributes
    | local.b is object with 1 attribute "baz"
    | local.condition is true

The true and false result expressions must have consistent types. The given
expressions are object and object, respectively.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
(with just the config listed above)

### References
- #12453 has a lot of similar issues, but claims to have been fixed. This subcase doesn't appear to have been fixed though.

The issue is also reproducible with objects whose values are maps (rather than objects whose values are lists as in the example here).

My specific use-case for this is a resource which uses `for_each` on an object, where in certain cases I want to disable creating any of the resources at all
i.e. `for_each = var.disabling_condition ? {} : var.map_of_stuff`
I can work around this by changing it to use a set of keys in the `for_each` then using the key to index into my object, but it would be better if the ternary operator just worked consistently

**Comment by r-bennett** [comment] 2020-09-02 15:30
Seems I've got my terminology a little muddled between maps and objects here, although the following config also uses different objects but does work:

```
locals {
  condition = true

  a = {
    foo = "hodor"
    bar = 12
  }

  b = {
    baz = "hodor"
  }

  c = local.condition ? local.a : local.b
}
```

**Comment by alisdair** [comment] 2020-09-02 18:13
Thanks for reporting this!

The issue here is that the conditional operator's arguments must be of the same type. You are providing arguments of type `object({ foo = string, bar = number})` and `object({ baz = string })`, which are incompatible. Terraform does not have a "generic object" type that these can be unified to.

As a result, this is working as currently designed. I think this specific report is a duplicate of #23364, but see also #19898 for an enhancement request which might address your underlying use case.

**Closed by alisdair** 2020-09-02 18:13 UTC
Labels: bug, new

**Comment by r-bennett** [comment] 2020-09-02 21:08
I can see the logic in it not working for different objects, but I think you misread my comment - that example you rewrote _does_ work, but if you replace the number with a list of strings it no longer does

**Comment by alisdair** [comment] 2020-09-02 21:24
Whoops, sorry about that! I did misread your comment.

What's happening there is a little more subtle: because the attribute values are all primitives, the two `object(…)` types are being unified into a `map(string)`. You can verify that by checking the result of the conditional statement. Take this slight modification of your original configuration:

```hcl
locals {
  condition = true

  a = {
    foo = "hodor"
    bar = 12
  }

  b = {
    baz = "hodor"
  }
}

output "c" {
  value = local.condition ? local.a : local.b
}
```

```shellsession
$ terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

c = {
  "bar" = "12"
  "foo" = "hodor"
}
```

As you can see, `c.bar` is `"12"`, not `12`, because the ternary result value has been coerced into a `map(string)` so that the types are unified.

This is definitely a confusing edge of the language and type system, especially when type coercion is involved. If possible, I think we would like to eventually address the underlying issue by implementing the optional object arguments (described in #19898).

**Comment by r-bennett** [comment] 2020-09-10 16:57
Thanks for the explanation, that makes sense. Optional args and partial defaults would be a super useful feature to have, we've got a lot of loose typing in our modules at the moment
