### ISSUE TITLE
Allow move block to refactor resources into a module

### ISSUE THREAD

**Issue by jantman** [hashicorp/terraform#30943] opened 2022-04-27 15:17 UTC
### Current Terraform Version

```
1.1.7
```

### Use-cases

I have a number of terraform projects, both older projects and small projects, which currently don't use modules; they have all resources directly in `.tf` files in the root module. I'd now like to refactor these resources into a reusable module. To make this module reusable, I want it to be an external module retrieved via git.

### Attempted Solutions

I attempted to create a module for the resources and use `move` blocks to handle the state move. i.e., in the simplest case where I just moved a single `aws_s3_bucket` resource into its own module. Starting with something like:

```hcl
resource "aws_s3_bucket" "bucket" {
 bucket = "mybucket"
 acl    = "private"
}
```

I attempted to refactor this resource into a module and updated my code to the following:

```hcl
moved {
  from = aws_s3_bucket.bucket
  to   = module.mymodule.aws_s3_bucket.bucket
}

module "mymodule" {
  source      = "git::ssh://git@git.example.com/TerraformModules/mymodule.git//infra?ref=initial"
  bucket_name = "mybucket"
}
```

However, this fails with the error:

```
Error: Cross-package move statement

  on main.tf line 5:
   5: moved {

This statement declares a move to an object declared in external module
package
"git::ssh://git@git.example.com/TerraformModules/mymodule.git//infra?ref=initial".
Move statements can be only within a single module package.
```

### Proposal

I think that use of the `move` block to refactor a resource _from the root module into any other module_ should be allowed.

I completely understand the reasoning behind not allowing refactoring between packages. However, it seems that the use case of moving a resource from the root module/configuration _into_ an (external) module is both quite common for people with older terraform configurations as well as for configurations that grow organically. Personally, I'd say that the vast majority of my terraform refactoring has been cases where I started creating resources in the root module and then realized I needed something similar in another place and should refactor the resources out into an external module.

The current workaround is to use `terraform state mv`, which is certainly viable but is problematic for organizations trying to run all terraform in a CI/CD system and not having humans manually running terraform commands.

**Comment by jbardin** [comment] 2022-04-27 15:38
Duplicate of #30153

**Closed by jbardin** 2022-04-27 15:38 UTC
Labels: enhancement, new
