### ISSUE TITLE
"google_compute_instance_group_manager" should support creating Regional Instance Group.

### ISSUE THREAD

**Issue by baskaran-md** [hashicorp/terraform#8925] opened 2016-09-19 22:37 UTC
### Terraform Version
Terraform v0.7.3

### Affected Resource(s)
- google_compute_instance_group_manager

### Terraform Configuration Files
```hcl
resource "google_compute_instance_group_manager" "instance_group_manager" {
  name               = "igm-${google_compute_instance_template.foobar.name}"
  instance_template  = "${google_compute_instance_template.foobar.self_link}"
  base_instance_name = "instance-group-manager"
  zone               = "us-west1-a"
  target_size        = "1"
}
```

The `google_compute_instance_group_manager` supports only `zone`. However, from the GCP console, we can create region level Instance Group. 

**Quoting from Ref[1]**
> ### Zonal versus regional instance groups
> 
> It is possible to create a managed instance group with only instances from a single zone, or you can create a regional managed instance group, which contains instances spread across multiple zones in a single region.
> 
> When designing a robust application, Google recommends using regional managed instance groups so that your application can handle extreme scenarios such as a single zone failure

This might need enhancement from Google side as well, as in **Ref[2] - API for InstanceGroupManager**, I could not the payload taking region information.

### References
[1] https://cloud.google.com/compute/docs/instance-groups/
[2] https://cloud.google.com/compute/docs/reference/latest/instanceGroupManagers#methods

**Comment by baskaran-md** [comment] 2016-09-19 22:37
@evandbrown Please review it.

**Comment by evandbrown** [comment] 2016-09-20 16:55
@baskaran-md makes sense! I'll add this to the backlog.

**Comment by evandbrown** [comment] 2016-09-20 16:56
Also, this is a duplicate of #8866

**Closed by evandbrown** 2016-09-20 16:56 UTC
Labels: enhancement, provider/google-cloud

**Comment by baskaran-md** [comment] 2016-09-21 05:21
ack.
