### ISSUE TITLE
terraform init --backend-config=<nonexistant file> crashes

### ISSUE THREAD

**Issue by bedge** [hashicorp/terraform#25852] opened 2020-08-14 13:44 UTC
### Terraform Version

```
[I] ➜ terraform --version
Terraform v0.13.0
```

### Debug Output 

Initial crash:
```
+ rm -rf .terraform
+ terraform init --backend-config=../../backends/xec.sh/variables.tfvars
2020/08/14 06:40:09 [INFO] Terraform version: 0.13.0
2020/08/14 06:40:09 [INFO] Go runtime version: go1.14.2
2020/08/14 06:40:09 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init", "--backend-config=../../backends/xec.sh/variables.tfvars"}
2020/08/14 06:40:09 [DEBUG] Attempting to open CLI config file: /Users/edgeb1/.terraformrc
2020/08/14 06:40:09 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory /Users/edgeb1/.terraform.d/plugins
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory /Users/edgeb1/Library/Application Support/io.terraform/plugins
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/08/14 06:40:09 [INFO] CLI command args: []string{"init", "--backend-config=../../backends/xec.sh/variables.tfvars"}
Initializing modules...
2020/08/14 06:40:09 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2020/08/14 06:40:09 [DEBUG] Module installer: begin cloudwatch
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cloudwatch is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/cloudwatch prior to install of cloudwatch
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cloudwatch has local path "../../../modules/cloudwatch/metric-alarm"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cloudwatch uses directory from parent: ../../../modules/cloudwatch/metric-alarm
2020/08/14 06:40:09 [DEBUG] Module installer: cloudwatch installed at ../../../modules/cloudwatch/metric-alarm
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle prior to install of oracle
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle has local path "../../../modules/rds-oracle"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle uses directory from parent: ../../../modules/rds-oracle
- cloudwatch in ../../../modules/cloudwatch/metric-alarm
2020/08/14 06:40:09 [DEBUG] Module installer: oracle installed at ../../../modules/rds-oracle
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_kms_key
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_kms_key is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_kms_key prior to install of oracle_kms_key
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_kms_key has local path "../../../modules/kms-key"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_kms_key uses directory from parent: ../../../modules/kms-key
- oracle in ../../../modules/rds-oracle
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_kms_key installed at ../../../modules/kms-key
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg prior to install of oracle_sg
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg has local path "../../../modules/security-group"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg uses directory from parent: ../../../modules/security-group
- oracle_kms_key in ../../../modules/kms-key
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg installed at ../../../modules/security-group
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bastion is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_bastion prior to install of oracle_sg_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bastion has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bastion uses directory from parent: ../../../modules/security-group-rules
- oracle_sg in ../../../modules/security-group
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_bastion installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_bioprod
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bioprod is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_bioprod prior to install of oracle_sg_bioprod
- oracle_sg_bastion in ../../../modules/security-group-rules
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bioprod has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bioprod uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_bioprod installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_hyperdesign is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_hyperdesign prior to install of oracle_sg_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_hyperdesign has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_hyperdesign uses directory from parent: ../../../modules/security-group-rules
- oracle_sg_bioprod in ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_hyperdesign installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_operations is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_operations prior to install of oracle_sg_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_operations has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_operations uses directory from parent: ../../../modules/security-group-rules
- oracle_sg_hyperdesign in ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_operations installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_selection_pipeline is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_selection_pipeline prior to install of oracle_sg_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_selection_pipeline has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_selection_pipeline uses directory from parent: ../../../modules/security-group-rules
- oracle_sg_operations in ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_selection_pipeline installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bastion is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_bastion prior to install of oracle_sg_ssl_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bastion has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bastion uses directory from parent: ../../../modules/security-group-rules
- oracle_sg_selection_pipeline in ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_bastion installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_bioprod
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bioprod is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_bioprod prior to install of oracle_sg_ssl_bioprod
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bioprod has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bioprod uses directory from parent: ../../../modules/security-group-rules
- oracle_sg_ssl_bastion in ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_bioprod installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_hyperdesign is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_hyperdesign prior to install of oracle_sg_ssl_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_hyperdesign has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_hyperdesign uses directory from parent: ../../../modules/security-group-rules
- oracle_sg_ssl_bioprod in ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_hyperdesign installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_operations is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_operations prior to install of oracle_sg_ssl_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_operations has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_operations uses directory from parent: ../../../modules/security-group-rules
- oracle_sg_ssl_hyperdesign in ../../../modules/security-group-rules
- oracle_sg_ssl_operations in ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_operations installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_selection_pipeline is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_selection_pipeline prior to install of oracle_sg_ssl_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_selection_pipeline has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_selection_pipeline uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_selection_pipeline installed at ../../../modules/security-group-rules
- oracle_sg_ssl_selection_pipeline in ../../../modules/security-group-rules
2020/08/14 06:40:09 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Initializing the backend...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2bfc425]

goroutine 1 [running]:
github.com/hashicorp/terraform/command.(*InitCommand).backendConfigOverrideBody(0xc000322a80, 0x32d6888, 0xf, 0xc00010f5a0, 0xc0003a46f0, 0xc00060b170, 0x29, 0x0, 0x0, 0x17762fa700000000)
        /home/circleci/project/project/command/init.go:862 +0x8b5
github.com/hashicorp/terraform/command.(*InitCommand).initBackend(0xc000322a80, 0xc0008447e0, 0x32d6888, 0xf, 0xc00010f5a0, 0x1, 0x0, 0x0, 0x0, 0xc0000b5a90, ...)
        /home/circleci/project/project/command/init.go:374 +0x4a6
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000322a80, 0xc00004c1d0, 0x1, 0x1, 0xc00028bca0)
        /home/circleci/project/project/command/init.go:227 +0xeb1
github.com/mitchellh/cli.(*CLI).Run(0xc0004ffa40, 0xc0004ffa40, 0xc0006bfd48, 0x1)
        /home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
        /home/circleci/project/project/main.go:106 +0xde
main.main()
        /home/circleci/project/project/main.go:42 +0x3a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2bfc425]

goroutine 1 [running]:
github.com/hashicorp/terraform/command.(*InitCommand).backendConfigOverrideBody(0xc000322a80, 0x32d6888, 0xf, 0xc00010f5a0, 0xc0003a46f0, 0xc00060b170, 0x29, 0x0, 0x0, 0x17762fa700000000)
        /home/circleci/project/project/command/init.go:862 +0x8b5
github.com/hashicorp/terraform/command.(*InitCommand).initBackend(0xc000322a80, 0xc0008447e0, 0x32d6888, 0xf, 0xc00010f5a0, 0x1, 0x0, 0x0, 0x0, 0xc0000b5a90, ...)
        /home/circleci/project/project/command/init.go:374 +0x4a6
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000322a80, 0xc00004c1d0, 0x1, 0x1, 0xc00028bca0)
        /home/circleci/project/project/command/init.go:227 +0xeb1
github.com/mitchellh/cli.(*CLI).Run(0xc0004ffa40, 0xc0004ffa40, 0xc0006bfd48, 0x1)
        /home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
        /home/circleci/project/project/main.go:106 +0xde
main.main()
        /home/circleci/project/project/main.go:42 +0x3a



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues
```

-->

### Crash Output
```
[I] ➜ cat crash.log
2020/08/14 06:40:09 [INFO] Terraform version: 0.13.0
2020/08/14 06:40:09 [INFO] Go runtime version: go1.14.2
2020/08/14 06:40:09 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init", "--backend-config=../../backends/xec.sh/variables.tfvars"}
2020/08/14 06:40:09 [DEBUG] Attempting to open CLI config file: /Users/edgeb1/.terraformrc
2020/08/14 06:40:09 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory /Users/edgeb1/.terraform.d/plugins
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory /Users/edgeb1/Library/Application Support/io.terraform/plugins
2020/08/14 06:40:09 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/08/14 06:40:09 [INFO] CLI command args: []string{"init", "--backend-config=../../backends/xec.sh/variables.tfvars"}
2020/08/14 06:40:09 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2020/08/14 06:40:09 [DEBUG] Module installer: begin cloudwatch
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cloudwatch is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/cloudwatch prior to install of cloudwatch
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cloudwatch has local path "../../../modules/cloudwatch/metric-alarm"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cloudwatch uses directory from parent: ../../../modules/cloudwatch/metric-alarm
2020/08/14 06:40:09 [DEBUG] Module installer: cloudwatch installed at ../../../modules/cloudwatch/metric-alarm
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle prior to install of oracle
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle has local path "../../../modules/rds-oracle"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle uses directory from parent: ../../../modules/rds-oracle
2020/08/14 06:40:09 [DEBUG] Module installer: oracle installed at ../../../modules/rds-oracle
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_kms_key
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_kms_key is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_kms_key prior to install of oracle_kms_key
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_kms_key has local path "../../../modules/kms-key"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_kms_key uses directory from parent: ../../../modules/kms-key
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_kms_key installed at ../../../modules/kms-key
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg prior to install of oracle_sg
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg has local path "../../../modules/security-group"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg uses directory from parent: ../../../modules/security-group
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg installed at ../../../modules/security-group
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bastion is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_bastion prior to install of oracle_sg_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bastion has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bastion uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_bastion installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_bioprod
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bioprod is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_bioprod prior to install of oracle_sg_bioprod
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bioprod has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_bioprod uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_bioprod installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_hyperdesign is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_hyperdesign prior to install of oracle_sg_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_hyperdesign has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_hyperdesign uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_hyperdesign installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_operations is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_operations prior to install of oracle_sg_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_operations has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_operations uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_operations installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_selection_pipeline is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_selection_pipeline prior to install of oracle_sg_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_selection_pipeline has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_selection_pipeline uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_selection_pipeline installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bastion is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_bastion prior to install of oracle_sg_ssl_bastion
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bastion has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bastion uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_bastion installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_bioprod
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bioprod is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_bioprod prior to install of oracle_sg_ssl_bioprod
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bioprod has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_bioprod uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_bioprod installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_hyperdesign is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_hyperdesign prior to install of oracle_sg_ssl_hyperdesign
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_hyperdesign has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_hyperdesign uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_hyperdesign installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_operations is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_operations prior to install of oracle_sg_ssl_operations
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_operations has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_operations uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_operations installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: begin oracle_sg_ssl_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_selection_pipeline is not yet installed
2020/08/14 06:40:09 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/oracle_sg_ssl_selection_pipeline prior to install of oracle_sg_ssl_selection_pipeline
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_selection_pipeline has local path "../../../modules/security-group-rules"
2020/08/14 06:40:09 [TRACE] ModuleInstaller: oracle_sg_ssl_selection_pipeline uses directory from parent: ../../../modules/security-group-rules
2020/08/14 06:40:09 [DEBUG] Module installer: oracle_sg_ssl_selection_pipeline installed at ../../../modules/security-group-rules
2020/08/14 06:40:09 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2bfc425]

goroutine 1 [running]:
github.com/hashicorp/terraform/command.(*InitCommand).backendConfigOverrideBody(0xc000322a80, 0x32d6888, 0xf, 0xc00010f5a0, 0xc0003a46f0, 0xc00060b170, 0x29, 0x0, 0x0, 0x17762fa700000000)
        /home/circleci/project/project/command/init.go:862 +0x8b5
github.com/hashicorp/terraform/command.(*InitCommand).initBackend(0xc000322a80, 0xc0008447e0, 0x32d6888, 0xf, 0xc00010f5a0, 0x1, 0x0, 0x0, 0x0, 0xc0000b5a90, ...)
        /home/circleci/project/project/command/init.go:374 +0x4a6
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000322a80, 0xc00004c1d0, 0x1, 0x1, 0xc00028bca0)
        /home/circleci/project/project/command/init.go:227 +0xeb1
github.com/mitchellh/cli.(*CLI).Run(0xc0004ffa40, 0xc0004ffa40, 0xc0006bfd48, 0x1)
        /home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
        /home/circleci/project/project/main.go:106 +0xde
main.main()
        /home/circleci/project/project/main.go:42 +0x3a
```

### Expected Behavior
Warn of missing file?"

### Actual Behavior
segfault

**Comment by mildwonkey** [comment] 2020-08-14 13:48
This is a duplicate of https://github.com/hashicorp/terraform/issues/25822, so I will close this to consolidate conversation.

**Closed by mildwonkey** 2020-08-14 13:48 UTC
Labels: bug, new
