### ISSUE TITLE
Inconsistent content between 2 instanciations of the same fetched module

### ISSUE THREAD

**Issue by NikolaLohinski** [hashicorp/terraform#31589] opened 2022-08-05 17:00 UTC
### Terraform Version
```
Terraform v1.2.6
on linux_amd64
```

### Terraform Configuration Files
```terraform

# /home/user/test/main.tf
module "first_module" {
  source = "/tmp/mock_module"
}

module "second_module" {
  source = "/tmp/mock_module"
}
```

```terraform
# /tmp/mock_module/main.tf
resource "null_resource" "mock" {
  triggers = {
    "content" = file("${path.module}/.ignored-file")
  }
}
```

```
# /tmp/mock_module/.ignored-file
foo bar
```

### Debug Output
Only copy pasting relevant part (quite short) as the rest is useless for this bug.

```
# in /home/user/test
$ TF_LOG=trace terraform init
...
Initializing modules...
2022-08-05T18:44:00.815+0200 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2022-08-05T18:44:00.815+0200 [DEBUG] Module installer: begin first_module
2022-08-05T18:44:00.815+0200 [TRACE] ModuleInstaller: first_module is not yet installed
2022-08-05T18:44:00.815+0200 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/first_module prior to install of first_module
2022-08-05T18:44:00.815+0200 [TRACE] ModuleInstaller: first_module address "file:///tmp/mock_module" will be handled by go-getter
Downloading file:///tmp/mock_module for first_module...
2022-08-05T18:44:00.815+0200 [TRACE] getmodules: fetching "file:///tmp/mock_module" to ".terraform/modules/first_module"
2022-08-05T18:44:00.816+0200 [TRACE] ModuleInstaller: first_module "file:///tmp/mock_module" was downloaded to .terraform/modules/first_module
2022-08-05T18:44:00.817+0200 [DEBUG] Module installer: first_module installed at .terraform/modules/first_module
- first_module in .terraform/modules/first_module
2022-08-05T18:44:00.817+0200 [DEBUG] Module installer: begin second_module
2022-08-05T18:44:00.817+0200 [TRACE] ModuleInstaller: second_module is not yet installed
2022-08-05T18:44:00.817+0200 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/second_module prior to install of second_module
2022-08-05T18:44:00.817+0200 [TRACE] ModuleInstaller: second_module address "file:///tmp/mock_module" will be handled by go-getter
Downloading file:///tmp/mock_module for second_module...
2022-08-05T18:44:00.817+0200 [TRACE] getmodules: copying previous install of "file:///tmp/mock_module" from .terraform/modules/first_module to .terraform/modules/second_module
2022-08-05T18:44:00.818+0200 [TRACE] ModuleInstaller: second_module "file:///tmp/mock_module" was downloaded to .terraform/modules/second_module
2022-08-05T18:44:00.818+0200 [DEBUG] Module installer: second_module installed at .terraform/modules/second_module
- second_module in .terraform/modules/second_module
2022-08-05T18:44:00.819+0200 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
...
```

The issue lies in:
```
2022-08-05T18:44:00.817+0200 [TRACE] getmodules: copying previous install of "file:///tmp/mock_module" from .terraform/modules/first_module to .terraform/modules/second_module
```
not copying files with leading dot `.`

### Expected Behavior
Expected behavior is for `terraform apply` to work nicely creating 2 instanciations of the same `/tmp/mock_module`

### Actual Behavior
```
# in /home/user/test
$ terraform apply
│ Error: Invalid function argument
│ 
│   on .terraform/modules/second_module/main.tf line 3, in resource "null_resource" "mock":
│    3:     "content" = file("${path.module}/.ignored-file")
│     ├────────────────
│     │ path.module is ".terraform/modules/second_module"
│ 
│ Invalid value for "path" parameter: no file exists at ".terraform/modules/second_module/.ignored-file"; this function works only with files that are
│ distributed as part of the configuration source code, so if this file will be created by a resource in this configuration you must instead obtain this
│ result from an attribute of that resource.
╵
```
When inspecting `.terraform/modules`, it looks like one of the 2 modules is missing the `.ignored-file`

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
This is not an issue when referencing a module with a relative path, but happens also for modules coming from registries. Most likely the issues happens whenever the modules needs to be fetched from somewhere, and the fetching is avoided by copying when the module is used more than once.

**Comment by jbardin** [comment] 2022-08-05 17:08
Duplicate of #30740

**Closed by jbardin** 2022-08-05 17:08 UTC
Labels: bug, new
