### ISSUE TITLE
cannot add instances to existing ELB

### ISSUE THREAD

**Issue by markmaas** [hashicorp/terraform#6391] opened 2016-04-28 10:44 UTC
Hi List,

When I add more instances via `aws_instance`, I want those instances to be added to the ELB created with `aws_elb`. So I change the "count" from 1 to 2 and expect the new instance to be added to the elb.

But it crashes (Look at the gist link).

When I destroy it all, and then "apply" it (with now a count of 2) everything is ago and shows no problems.
### Terraform Version

Terraform v0.6.15
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_elb
### Terraform Configuration Files

``` hcl
# ELB
resource "aws_elb" "nvb" {
  name = "dev-nvb-elb"
  subnets = [ "${split(",", module.vpc.public_subnets)}"]

  listener {
    instance_port = 80
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
  instances = ["${aws_instance.haproxy01.*.id}", "${aws_instance.haproxy02.*.id}", "${aws_instance.haproxy03.*.id}" ]
  cross_zone_load_balancing = true
  idle_timeout = 400
  connection_draining = true
  connection_draining_timeout = 400

  tags {
    Name = "dev-nvb-elb"
    Env = "development"
  }
}

# Public side
resource "aws_instance" "haproxy01" {
    ami = "${lookup(var.aws_amis, var.aws_region)}"
    instance_type = "t1.micro"
    key_name = "${aws_key_pair.ansible_bootstrap.id}"
    subnet_id = "${element(split(",", module.vpc.public_subnets), 0)}"
    count = 2
    tags {
        Name = "haproxy-1a-${count.index}"
        Env = "development"
    }
}
```
### Debug Output

https://gist.github.com/markmaas/a605b3e5b426c041b4ec5ec48d538d7a
### Expected Behavior

add the newly created instance to the aws elb
### Actual Behavior

terraform stops running and leaves the environment in a unknown state.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
0. Create more instances
1. `terraform apply`
2. Now Terraform stops working
3. `terraform destroy`
4. `terraform apply`
5. Now there is no problem.
6. Change the count, down or up
7. Try `terraform apply`
8. things break again.
9. If you wait a minute and try again: It WILL work!
### Important Factoids

Everything is in a VPC, and spread across AZ's

Thanks,
Mark

**Comment by paddyforan** [comment] 2016-11-07 17:38
Hi Mark! Thanks for reporting the issue, and really sorry for the problems. I'm taking a look into this, but noticed your gist link is 404ing. I'll try to reproduce this, but is this still an issue for you? If so, could you update with a new gist link? Sorry for the inconvenience.

**Comment by paddyforan** [comment] 2016-11-08 22:43
Hey @markmaas, I've been unable to successfully reproduce this. And without the log output, it's unlikely I'll be able to help much.

For posterity, here's the plan I was trying to reproduce with:

```tf
provider "aws" {
  region = "us-west-2"
}

resource "aws_elb" "foo" {
  name = "foo"

  listener {
    instance_port     = 80
    instance_protocol = "http"
    lb_port           = 80
    lb_protocol       = "http"
  }

  instances                   = ["${aws_instance.foo01.*.id}"]
  cross_zone_load_balancing   = true
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400
  availability_zones          = ["us-west-2a"]

  tags {
    Name = "dev-nvb-elb"
    Env  = "development"
  }
}

resource "aws_instance" "foo01" {
  ami               = "ami-4fccb37f"
  availability_zone = "us-west-2a"
  instance_type     = "m1.small"
  count             = 1

  tags {
    Name = "foo-${count.index}"
  }
}
```

I'd apply that, and watch it spin up both resources. Then I'd increment the count to 2, and plan that. It showed that the number of instances in the load balancer would change, and it would spin up a new instance. So I applied that, and can verify that's what happened. So it seems to be working, unless I've misunderstood. It's entirely plausible that the bug got fixed in the time period between you opening the issue and me starting to reproduce it; sorry for the long wait.

I'm going to go ahead and close this as I can't reproduce it and am not confident it still exists. But if you run into it, or have your log output still, feel free to comment and we'll get this reopened and look into it again.

**Closed by paddyforan** 2016-11-08 22:43 UTC
Labels: bug, crash, provider/aws
