### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Riinkesh** [hashicorp/terraform#34206] opened 2023-11-08 11:30 UTC
### Terraform Version

```shell
1.4.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 46 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0xc009a09da0?)
/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000fa0320, {0x2ccf8f8, 0xc0006d1000}, {0x2ccf8f8, 0xc0006d10c0}, 0xc000ffe5a0, 0xc0006d0f80)
/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
Operation failed: failed running terraform plan (exit 11)

### Expected Behavior

Terraform init & plan should have run for the aws provider

### Actual Behavior

Terraform Crash

### Steps to Reproduce

1. terraform init
2. 2. terraform plan

### Additional Context

Terraform crashed

**Comment by jbardin** [comment] 2023-11-08 13:06
Duplicate of #32810

**Closed by jbardin** 2023-11-08 13:06 UTC
Labels: bug, new
