### ISSUE TITLE
Impossible to destroy resources

### ISSUE THREAD

**Issue by Bowbaq** [hashicorp/terraform#21333] opened 2019-05-16 12:04 UTC
### Terraform Version

```
Terraform v0.11.13
+ provider.aws v1.60.0
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Terraform Configuration Files
Not particularly relevant, we have a few modules w/ AWS resources and a few resources outside modules. We output some of the module's outputs at the root level

### Expected Behavior
`terraform destroy` works even if resources are partially destroyed due to a previous failure

### Actual Behavior
1. `terraform destroy` failed due to a transient failure in AWS
```
Error: Error applying plan:

1 error(s) occurred:

* aws_s3_bucket_policy.model_uploads (destroy): 1 error(s) occurred:

* aws_s3_bucket_policy.model_uploads: Error deleting S3 policy: OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
	status code: 409, request id: 1CA6A65987C5258B, host id: cC06UVHR4G3WkIzQp5DWL6lk0/d8w6BCrz5CQzknQHzEyRVCJLpYluwL0GHOKz7RGgCnizctoQ0=
```
2. Subsequent `terraform destroy` calls fail
```
terraform destroy
Acquiring state lock. This may take a few moments...
data.template_file.hosts[0]: Refreshing state...
data.template_file.kube2iam: Refreshing state...
data.template_file.hosts[1]: Refreshing state...
data.template_file.cert-manager-issuer: Refreshing state...
data.template_file.hosts[2]: Refreshing state...
data.terraform_remote_state.frontend: Refreshing state...
data.terraform_remote_state.vpc: Refreshing state...
data.terraform_remote_state.vpc: Refreshing state...
data.template_file.init_replicaset_member[1]: Refreshing state...
data.template_file.init_replicaset_member[0]: Refreshing state...
data.template_file.init_replicaset_member[2]: Refreshing state...
data.template_file.run: Refreshing state...
data.aws_ami.kubernetes: Refreshing state...
data.aws_iam_policy_document.consul: Refreshing state...
data.aws_kms_key.kms_key: Refreshing state...
data.terraform_remote_state.backend_lambdas: Refreshing state...
data.terraform_remote_state.vault: Refreshing state...
data.aws_iam_policy_document.kops_fix_kms_key_permissions: Refreshing state...
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

Releasing state lock. This may take a few moments...

Error: Error applying plan:

2 error(s) occurred:

* module.kops.output.zone_id: Resource 'aws_route53_zone.cluster' does not have attribute 'id' for variable 'aws_route53_zone.cluster.id'
* module.kops.output.zone_ns: Resource 'aws_route53_zone.cluster' does not have attribute 'name_servers' for variable 'aws_route53_zone.cluster.name_servers'
```
3. As it happens, the initial destroy in fact worked, there are no more resources in the state
```
terraform state list
# no output
```
4. `terraform plan -destroy` works and shows there is nothing to do
```
terraform plan -destroy
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.vpc: Refreshing state...
data.template_file.hosts[0]: Refreshing state...
data.template_file.cert-manager-issuer: Refreshing state...
data.template_file.hosts[1]: Refreshing state...
data.template_file.hosts[2]: Refreshing state...
data.template_file.kube2iam: Refreshing state...
data.terraform_remote_state.frontend: Refreshing state...
data.terraform_remote_state.vpc: Refreshing state...
data.template_file.init_replicaset_member[0]: Refreshing state...
data.template_file.init_replicaset_member[1]: Refreshing state...
data.template_file.init_replicaset_member[2]: Refreshing state...
data.template_file.run: Refreshing state...
data.aws_iam_policy_document.consul: Refreshing state...
data.aws_ami.kubernetes: Refreshing state...
data.aws_kms_key.kms_key: Refreshing state...
data.terraform_remote_state.backend_lambdas: Refreshing state...
data.terraform_remote_state.vault: Refreshing state...
data.aws_iam_policy_document.kops_fix_kms_key_permissions: Refreshing state...

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### References
May be related to:
- https://github.com/hashicorp/terraform/issues/21096

**Comment by gomker** [comment] 2019-09-27 16:12
I found this as I have a different `destroy` issue related to `data` resources

 I wanted to note I have ran into your problem specifically relate.d to the error
```
 Error deleting S3 policy: OperationAborted: A conflicting conditional operation is currently in progress 
```
Delelting and recreating S3 buckets has a lag due to the DNS naming - it takes some time, about 30 minutes - in order for a cycle to complete and that name to be available again. I ran into this same problem during develeopment. I ended up moving my S3 bucket managment to ansible to avoid race conditions with Terraform

**Comment by apparentlymart** [comment] 2020-06-30 22:42
Hi @Bowbaq! Sorry for the long silence here.

The codepath that generated the errors like "Resource A does not have attribute B for variable C" was removed as part of the configuration language rewrite in Terraform 0.12, so unfortunately we cannot reproduce the behavior you reported with current Terraform versions. I share your sense that this may be related to #21096, and so I'm going to close this issue to consolidate with that one.

We're currently working on some research related to #21096 in the hope of addressing it in the next major release (though we won't know for sure until the research is complete).

Thanks for reporting this!

**Closed by apparentlymart** 2020-06-30 22:42 UTC
Labels: bug, core, v0.11
