### ISSUE TITLE
`terraform output` adds double-quotes

### ISSUE THREAD

**Issue by CyrusJavan** [hashicorp/terraform#27007] opened 2020-11-21 00:28 UTC
### Terraform Version

```
Terraform v0.14.0-rc1
```

### Terraform Configuration Files

```terraform
output "AVIATRIX_CONTROLLER_IP" {
  value = "1.1.1.1"
}
```

### Debug Output

https://gist.github.com/CyrusJavan/6b95537d05bea31fe944f34ffd853ad9

### Expected Behavior

`terraform output` prints the output without added quotes.
```
terraform0.13.4 output AVIATRIX_CONTROLLER_IP 
1.1.1.1

```
### Actual Behavior

`terraform output` adds double-quotes around the printed output.
```
terraform0.14.0-rc1 output AVIATRIX_CONTROLLER_IP
"1.1.1.1"

```

### Steps to Reproduce

```
terraform0.14.0-rc1 output AVIATRIX_CONTROLLER_IP
```
### Additional Context

This breaks my acceptance test script. I `terraform apply` some test infra, use `terraform output` to grab some values in a script which are then save to env vars. Those env vars are read in my acceptance tests and `printf`-ed into double quotes in the acceptance test like so `controller_ip = "%s"`. Adding quotes to `terraform output` totally bricks my script as the quotes create invalid syntax.

**Comment by jbardin** [comment] 2020-11-23 13:32
Duplicate of #26831

**Closed by jbardin** 2020-11-23 13:32 UTC
Labels: bug, new
