### ISSUE TITLE
Lack of tags causes terraform to attempt to add tags on the second apply

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#29119] opened 2021-07-08 13:00 UTC
```
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.48.0
```

Terraform has issues with tags.  I am not using tags at all.  But on a second apply, terraform wants to add tags of ```{}```
If I do use tags in my code, then the issue does not occur.
Here is the code:
```
resource "aws_default_vpc" "aws_default_vpc" {
}

resource "aws_security_group" "aws_security_group" {
  name        = "name"
  description = "desc"
  vpc_id      = aws_default_vpc.aws_default_vpc.id
}
```
Here are three apply's run - no changes to the code were made:
```
terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_default_vpc.aws_default_vpc will be created
  + resource "aws_default_vpc" "aws_default_vpc" {
      + arn                              = (known after apply)
      + assign_generated_ipv6_cidr_block = (known after apply)
      + cidr_block                       = (known after apply)
      + default_network_acl_id           = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_group_id        = (known after apply)
      + dhcp_options_id                  = (known after apply)
      + enable_classiclink               = (known after apply)
      + enable_classiclink_dns_support   = (known after apply)
      + enable_dns_hostnames             = (known after apply)
      + enable_dns_support               = true
      + id                               = (known after apply)
      + instance_tenancy                 = (known after apply)
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      + main_route_table_id              = (known after apply)
      + owner_id                         = (known after apply)
      + tags_all                         = (known after apply)
    }

  # aws_security_group.aws_security_group will be created
  + resource "aws_security_group" "aws_security_group" {
      + arn                    = (known after apply)
      + description            = "desc"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "name"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags_all               = (known after apply)
      + vpc_id                 = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_default_vpc.aws_default_vpc: Creating...
aws_default_vpc.aws_default_vpc: Still creating... [10s elapsed]
aws_default_vpc.aws_default_vpc: Creation complete after 11s [id=[redacted]
aws_security_group.aws_security_group: Creating...
aws_security_group.aws_security_group: Creation complete after 1s [id=redacted]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```
```
terraform apply

aws_default_vpc.aws_default_vpc: Refreshing state... [id=redacted]
aws_security_group.aws_security_group: Refreshing state... [id=redacted]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_default_vpc.aws_default_vpc has been changed
  ~ resource "aws_default_vpc" "aws_default_vpc" {
        id                               = "redacted"
      + tags                             = {}
        # (13 unchanged attributes hidden)
    }
  # aws_security_group.aws_security_group has been changed
  ~ resource "aws_security_group" "aws_security_group" {
        id                     = "redacted"
        name                   = "name"
      + tags                   = {}
        # (8 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

```
terraform apply

aws_default_vpc.aws_default_vpc: Refreshing state... [id=redacted]
aws_security_group.aws_security_group: Refreshing state... [id=redacted

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by jbardin** [comment] 2021-07-08 14:17
Hi,

Since the plan message in both cases states `No changes. Your infrastructure matches the configuration.`, it appears to be a duplicate of #29121. 

Thanks

**Closed by jbardin** 2021-07-08 14:17 UTC
Labels: bug, new

**Comment by scott-doyland-burrows** [comment] 2021-07-08 14:27
I am not sure why this is immediately closed?

Terraform never used to work in this way.  In the past, if I did not use tags, then Terraform did not update the statefile on a second apply.

Tags are optional.  Terraform should not be out of sync immediately after the first apply.
Terraform and/or the provider should set the statefile correctly on the first apply.
