### ISSUE TITLE
aws_eip_association.eip_assoc: unexpected EOF

### ISSUE THREAD

**Issue by dvela2** [hashicorp/terraform#7910] opened 2016-08-02 02:44 UTC
Version: **Terraform v0.6.16**

Encountering issue applying terraform plan although seems to the changes from the plan 

Applying terraform plan produces an error although seems the changes has take effect. part of error provided below

> Proceed with the above changes? [y/N] y
> cd src/xxxxxx/environments/xxxx/monitoring; \
> 	terraform apply -backup=- -input=false terraform.tfplan; \
> 	cat terraform.tfstate | jq --arg generated "@generated" '{($generated): "true"} + .' > terraform.tfstate.tmp; \
> 	mv -f terraform.tfstate.tmp terraform.tfstate
> aws_eip_association.eip_assoc: Creating...
>   allocation_id:        "" => "<computed>"
>   instance_id:          "" => "i-xxxxxxx"
>   network_interface_id: "" => "<computed>"
>   private_ip_address:   "" => "<computed>"
>   public_ip:            "" => "X.X.X.X"
> Error applying plan:
> 
> 1 error(s) occurred:
> 
> * aws_eip_association.eip_assoc: unexpected EOF
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
> panic: runtime error: invalid memory address or nil pointer dereference
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x1553e4]
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: goroutine 47 [running]:
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: panic(0xff93a0, 0xc82000a100)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:481 +0x3e6
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsEipAssociationCreate(0xc820415e60, 0xc8ece0, 0xc820098000, 0x0, 0x0)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_eip_association.go:99 +0x9e4
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc820423100, 0xc8205d7b60, 0xc820660590, 0xc8ece0, 0xc820098000, 0xc8205d7c01, 0x0, 0x0)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:146 +0x29e
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc820459c80, 0xc820755380, 0xc8205d7b60, 0xc820660590, 0x1, 0x0, 0x0)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:162 +0x1ed
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Apply(0xc82000fc40, 0xc82065cac0, 0xc820660650, 0x0, 0x0)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:323 +0x76
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: reflect.Value.call(0xf32ba0, 0x123e2b8, 0x13, 0x12f6628, 0x4, 0xc82075ded8, 0x3, 0x3, 0x0, 0x0, ...)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:435 +0x120d
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: reflect.Value.Call(0xf32ba0, 0x123e2b8, 0x13, 0xc82075ded8, 0x3, 0x3, 0x0, 0x0, 0x0)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:303 +0xb1
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc8203a3f00, 0xc8203a3ec0, 0xc8203ee448, 0xc8201a3500, 0xc82000fc60, 0xc8fb80, 0xc82065cac0, 0x16, 0xc8fbe0, 0xc820660650, ...)
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
> 2016/08/02 09:24:46 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:477 +0x49d
> 2016/08/02 09:24:46 [DEBUG] root: eval: *terraform.EvalWriteState
> 2016/08/02 09:24:46 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
> 2016/08/02 09:24:46 [DEBUG] root: eval: *terraform.EvalIf
> 2016/08/02 09:24:46 [DEBUG] root: eval: *terraform.EvalWriteDiff
> 2016/08/02 09:24:46 [DEBUG] root: eval: *terraform.EvalIf
> 2016/08/02 09:24:46 [DEBUG] root: eval: *terraform.EvalWriteState
> 2016/08/02 09:24:46 [DEBUG] root: eval: *terraform.EvalApplyPost
> 2016/08/02 09:24:46 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
> 
> * aws_eip_association.eip_assoc: unexpected EOF
> 2016/08/02 09:24:46 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
> 
> * aws_eip_association.eip_assoc: unexpected EOF
> 2016/08/02 09:24:46 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:
> 
> * aws_eip_association.eip_assoc: unexpected EOF
> 2016/08/02 09:24:46 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
> 
>

**Comment by stack72** [comment] 2016-08-02 04:24
Hi @dvela2 

Apologies you are getting this error, please can you post the terraform config that is causing the error? Please remember to take out any secret information :)

Paul

**Comment by dvela2** [comment] 2016-08-02 05:18
as requested
> module "module_iam" {
>   source      = "../../../modules/iam"
>   stack_name  = "${var.stack_name}"
>   ext_role = "rolename"
> }
> 
> module "rolename_instance" {
>   source                = "../../../modules/instance"
>   ami                   = "${var.amis.rolename}"
>   availability_zone     = "${lookup(var.availability_zones, var.region)}"
>   instance_type         = "${var.instance_types.rolename}"
>   security_groups       = "${var.security_group_names.secgroup}"
>   common_security_group = "${var.common_security_group}"
>   iam_instance_profile  = "${module.module_iam.instance_profile}"
> 
>   name         = "Instance_name"
>   puppet_realm = "${var.stack_name}"
>   ext_role  = "rolename"
>   region       = "${var.region}"
> }
> 
> resource "aws_eip_association" "eip_assoc" {
>   instance_id = "${module.rolename_instance.id}"
>   public_ip   = "${var.eip.rolename}"
> }
> 
> resource "aws_route53_record" "rolename" {
>   zone_id = "${var.external_route53_zone_id}"
>   name    = "rolename"
>   type    = "CNAME"
>   ttl     = 60
>   records = ["${var.eip.rolename}"]
> }
>

**Comment by kwilczynski** [comment] 2016-08-02 20:48
@dvela2 do you get EIP associated despite the error? Have you seen any other warnings or errors in the output (other than the panic/crash above)?

Does this happen always? What region? I've tried to reproduce this, but I cannot get it to break like that.

It seem to break on `d.SetId(*resp.AssociationId)` , where `resp.AssociationId` is a pointer to a string value, and might be `nil` causing the nil pointer deference error while setting the resource ID. There is an error check in place just after the request is made, thus I wonder if the API responds fine but it gets eventually consistent (which does happen with the AWS APIs quite often) and the actual response is not yet populated.

Are building Terraform from the source, by any chance? I was thinking, that perhaps if you have you have the time, then would you mind adding something like this:

`log.Printf("[DEBUG] EIP association response: %#v", resp)`

Just before setting the ID here: [resource_aws_eip_association.go#L99](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_eip_association.go#L99)

I wonder what would be in the response struct there in your case.

**Comment by dvela2** [comment] 2016-08-03 05:14
Yup, EIP gets associated despite the error and seems to work fine without any issue.

**Comment by kwilczynski** [comment] 2016-08-03 06:04
@dvela2 I see. I asked as this is very suspicious. EIP association resource is not new and there are tests executing each time there is a commit. Given, that this is about setting up the very ID of the resource, should it be failing before, then someone would notice and fix it.

I personally cannot reproduce this.

**Comment by dvela2** [comment] 2016-08-09 08:23
have you tried it without vpc?

**Comment by kwilczynski** [comment] 2016-08-09 09:06
@dvela2 yes.

Given the following Terraform template:

```
data "aws_ami" "test" {
  most_recent = true
  filter {
    name = "name"
    values = ["ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-*"]
  }
  filter {
    name = "virtualization-type"
    values = [
      "hvm"
    ]
  }
  owners = [
    "099720109477"
  ]
}

resource "aws_eip" "test" {}

resource "aws_instance" "test" {
    ami = "${data.aws_ami.test.id}"
    instance_type = "t2.micro"
}

resource "aws_eip_association" "test" {
  instance_id = "${aws_instance.test.id}"
  public_ip = "${aws_eip.test.public_ip}"
}
```

No issues during a few cycles of plan, apply and destroy.

```
data.aws_ami.test: Refreshing state...
aws_eip.test: Creating...
  allocation_id:     "" => "<computed>"
  association_id:    "" => "<computed>"
  domain:            "" => "<computed>"
  instance:          "" => "<computed>"
  network_interface: "" => "<computed>"
  private_ip:        "" => "<computed>"
  public_ip:         "" => "<computed>"
aws_instance.test: Creating...
  ami:                      "" => "ami-cbdd50dc"
  availability_zone:        "" => "<computed>"
  ebs_block_device.#:       "" => "<computed>"
  ephemeral_block_device.#: "" => "<computed>"
  instance_state:           "" => "<computed>"
  instance_type:            "" => "t2.micro"
  key_name:                 "" => "<computed>"
  network_interface_id:     "" => "<computed>"
  placement_group:          "" => "<computed>"
  private_dns:              "" => "<computed>"
  private_ip:               "" => "<computed>"
  public_dns:               "" => "<computed>"
  public_ip:                "" => "<computed>"
  root_block_device.#:      "" => "<computed>"
  security_groups.#:        "" => "<computed>"
  source_dest_check:        "" => "true"
  subnet_id:                "" => "<computed>"
  tenancy:                  "" => "<computed>"
  vpc_security_group_ids.#: "" => "<computed>"
aws_eip.test: Creation complete
aws_instance.test: Still creating... (10s elapsed)
aws_instance.test: Still creating... (20s elapsed)
aws_instance.test: Still creating... (30s elapsed)
aws_instance.test: Creation complete
aws_eip_association.test: Creating...
  allocation_id:        "" => "<computed>"
  instance_id:          "" => "i-4fc8e0d1"
  network_interface_id: "" => "<computed>"
  private_ip_address:   "" => "<computed>"
  public_ip:            "" => "52.207.92.122"
aws_eip_association.test: Creation complete

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

No issues.

Make sure that your connection to their API end-point is stable, and that you do not have any proxies (nothing like e.g. WebSense, etc.) and caching standing between you and Amazon AWS.

**Comment by dvela2** [comment] 2016-08-12 00:23
@kwilczynski 

Sorry i forgot to mention that i am associating an existing EIP.

**Comment by stack72** [comment] 2016-08-16 08:08
Hi @dvela2 

Just had a look through this - from what i can reproduce, @kwilczynski's example seems solid to me. In order to try and diagnose this more, can you tell me what is happening here?

```
Proceed with the above changes? [y/N] y
cd src/xxxxxx/environments/xxxx/monitoring; \
terraform apply -backup=- -input=false terraform.tfplan; \
cat terraform.tfstate | jq --arg generated "@generated" '{($generated): "true"} + .' > terraform.tfstate.tmp; \
mv -f terraform.tfstate.tmp terraform.tfstate
```

could this be the cause of your woes?

P.

**Comment by dvela2** [comment] 2016-08-16 08:25
will try review our settings again. but im not sure if this causes the error. BTW did an update and my version is now **Terraform v0.7.0** but same issue was encountered

**Comment by stack72** [comment] 2016-08-16 08:29
Looking again at your code:

```
resource "aws_eip_association" "eip_assoc" {
  instance_id = "${module.rolename_instance.id}" 
  public_ip = "${var.eip.rolename}"
}
```

What does var.eip.rolename evaluate to be?

**Comment by dvela2** [comment] 2016-08-16 08:35
var.eip.rolename is the reserve EIP that will be associated   to the module.rolename_instance.id instance

**Comment by stack72** [comment] 2016-08-16 08:42
ok, using a public_ip launches your instance into EC2-Classic - is that your expected behaviour?

**Comment by dvela2** [comment] 2016-08-16 08:48
nope. basically the first block spins up the instance then after that associate the reserve EIP to the instance

module "rolename_instance" {
  source                 = "../../../modules/instance"
  ami                    = "${lookup(var.amis, "webapp")}"
  availability_zones     = ["${var.availability_zones[var.region]}"]
  instance_type          = "${lookup(var.instance_types, "webapp")}"
  security_groups        = ["${aws_security_group. webapp.name}"]
}
resource "aws_eip_association" "eip_assoc" {
  instance_id = "${element(module. rolename_instance.id, 0)}"
  public_ip   = "${lookup(var.eip, "webapp")}"
}

**Comment by stack72** [comment] 2016-08-16 08:50
My apologies, I should have been more clear here. What i mean is, you only use `public_ip` in an EIP association when the instance is being launched into EC2-Classic. If you are trying to launch into a VPC then this will not be correct:

(https://www.terraform.io/docs/providers/aws/r/eip_association.html#public_ip)
```
public_ip - (Optional) The Elastic IP address. This is required for EC2-Classic.
```

**Comment by dvela2** [comment] 2016-08-16 08:57
yup im doing the test without VPC so that should work right?

**Comment by kwilczynski** [comment] 2016-08-16 09:07
@dvela2 your code sample is very similar to the example I posted. Would be be able to add the following before the resource that causes panic? Most likely above the EC2 instance block.

```
resource "null_resource" "test" {
  provisioner "local-exec" {
    command = "echo \"${lookup(var.eip, "webapp")}\""
  }
}
```

It would be nice to see what is being passed.

**Comment by dvela2** [comment] 2016-08-17 04:44
```
Plan: 2 to add, 0 to change, 0 to destroy.

Proceed with the above changes? [y/N] y
cd src/xxx/environments/xxx/xxx; \
	terraform apply -backup=- -input=false terraform.tfplan; \
	cat terraform.tfstate | jq --arg generated "@generated" '{($generated): "true"} + .' > terraform.tfstate.tmp; \
	mv -f terraform.tfstate.tmp terraform.tfstate
null_resource.testing: Creating...
null_resource.testing: Provisioning with 'local-exec'...
null_resource.testing (local-exec): Executing: /bin/sh -c "echo "123.123.123.123""
null_resource.testing (local-exec): 123.123.123.123
null_resource.testing: Creation complete
aws_route53_record.ss4: Creating...
  fqdn:               "" => "<computed>"
  name:               "" => "webapp"
  records.#:          "" => "1"
  records.2884576248: "" => "123.123.123.123"
  ttl:                "" => "60"
  type:               "" => "CNAME"
  zone_id:            "" => "xxxxx"
aws_eip_association.assoc: Creating...
  allocation_id:        "" => "<computed>"
  instance_id:          "" => "i-XXXXX"
  network_interface_id: "" => "<computed>"
  private_ip_address:   "" => "<computed>"
  public_ip:            "" => "123.123.123.123"
Error applying plan:

1 error(s) occurred:

* aws_eip_association.assoc: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2016/08/17 12:43:16 [DEBUG] plugin: terraform: [signal 0xb code=0x1 addr=0x0 pc=0x43f914]
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 
2016/08/17 12:43:16 [DEBUG] plugin: terraform: goroutine 149 [running]:
2016/08/17 12:43:16 [DEBUG] plugin: terraform: panic(0x2fb1ba0, 0xc8200100f0)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:481 +0x3e6
2016/08/17 12:43:16 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsEipAssociationCreate(0xc82090c960, 0x253e380, 0xc8201ea000, 0x0, 0x0)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_eip_association.go:99 +0x9e4
2016/08/17 12:43:16 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc820537bc0, 0xc82021ba40, 0xc82073faa0, 0x253e380, 0xc8201ea000, 0xc8206b3301, 0x0, 0x0)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:162 +0x29a
2016/08/17 12:43:16 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc82026b860, 0xc82021ba00, 0xc82021ba40, 0xc82073faa0, 0x1, 0x0, 0x0)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:176 +0x1ed
2016/08/17 12:43:16 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc8202180c0, 0xc82073f440, 0xc82073aea0, 0x0, 0x0)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:460 +0x76
2016/08/17 12:43:16 [DEBUG] plugin: terraform: reflect.Value.call(0x2c6c380, 0x36505b8, 0x13, 0x37c3bf8, 0x4, 0xc82066ded8, 0x3, 0x3, 0x0, 0x0, ...)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:435 +0x120d
2016/08/17 12:43:16 [DEBUG] plugin: terraform: reflect.Value.Call(0x2c6c380, 0x36505b8, 0x13, 0xc82066ded8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:303 +0xb1
2016/08/17 12:43:16 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc820214b40, 0xc8202148c0, 0xc820410d30, 0xc8201aaa80, 0xc8201a3da0, 0x2540ae0, 0xc82073f440, 0x16, 0x2540b40, 0xc82073aea0, ...)
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
2016/08/17 12:43:16 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2016/08/17 12:43:16 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x49d
2016/08/17 12:43:16 [DEBUG] root: eval: *terraform.EvalWriteState
2016/08/17 12:43:16 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/08/17 12:43:16 [DEBUG] root: eval: *terraform.EvalIf
2016/08/17 12:43:16 [DEBUG] root: eval: *terraform.EvalWriteState
2016/08/17 12:43:16 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/08/17 12:43:16 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/08/17 12:43:16 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_eip_association.assoc: unexpected EOF
2016/08/17 12:43:16 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_eip_association.assoc: unexpected EOF
2016/08/17 12:43:16 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* aws_eip_association.assoc: unexpected EOF
2016/08/17 12:43:16 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_eip_association.assoc: unexpected EOF
2016/08/17 12:43:16 [TRACE] [walkApply] Exiting eval tree: aws_eip_association.assoc
2016/08/17 12:43:16 [DEBUG] vertex provider.aws (close), got dep: aws_eip_association.assoc
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: provider.aws (close)
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.module.user_data.provider.template
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.module.user_data.var.puppet_realm
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.aws_instance.instance
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.module.user_data.var.puppet_branch
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.provider.template (disabled)
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.output.availability_zone
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: var.stack_name
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.module.user_data.var.puppet_role
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: provisioner.local-exec
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.output.private_ip
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_instance.var.puppet_branch
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_iam.var.puppet_role
2016/08/17 12:43:16 [DEBUG] vertex root, got dep: module.ss4_iam.plan-destroy
2016/08/17 12:43:16 [DEBUG] plugin: /opt/terraform/terraform: plugin process exited
2016/08/17 12:43:16 [DEBUG] plugin: waiting for all plugin processes to complete...
2016/08/17 12:43:16 [DEBUG] plugin: /opt/terraform/terraform: plugin process exited
2016/08/17 12:43:16 [DEBUG] plugin: /opt/terraform/terraform: plugin process exited
2016/08/17 12:43:16 [DEBUG] plugin: /opt/terraform/terraform: plugin process exited
2016/08/17 12:43:16 [DEBUG] plugin: /opt/terraform/terraform: plugin process exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
make: *** [src/xxx/environments/xxx/xxx] Error 1
```

**Comment by kwilczynski** [comment] 2016-08-18 11:31
@dvela2 in all the honesty, I am puzzled.

Can you do me a favour and try my example (the one I included in one of the comments above). You can try the simple example with and/or without manually setting the EIP (referencing it, rather).

But, please DO NOT use your magic with `jq`, etc. I am thinking, that whatever you are doing to the state it might be causing this.

**Comment by dvela2** [comment] 2016-08-19 07:40
Take out "jq" in my plan and error seems to persist  and nothing change in the error.

**Comment by kwilczynski** [comment] 2016-09-22 17:47
@dvela2 hello there! Are you still having an issue with this?

**Comment by catsby** [comment] 2016-10-14 22:03
Closing for now, pleas let us know if you are still running into this!

**Closed by catsby** 2016-10-14 22:03 UTC
Labels: bug, crash, provider/aws, waiting-response

**Comment by rainkinz** [comment] 2016-10-29 16:25
I have the same issue when trying to associate an existing eip:

crash.log: https://gist.github.com/rainkinz/8da26dd707c57cc26c71082017acb4f6

Terraform configuration:
```
resource "aws_instance" "web" {
  ami = "${var.aws_ami_id}"

  instance_type = "m3.large"

  availability_zone = "us-east-1b"

  key_name = "${var.key_name}"

  iam_instance_profile = "Prod-Webserver"

  # TODO: Change to a VPC
  # vpc_security_group_ids = ["${aws_security_group.main_security_group.id}"]

  security_groups = ["redacted"]

  # The connection block tells our provisioner how to communicate with the 
  # resource (instance)
  connection {
    user = "someuser"

    # The connection will use the local SSH agent for authentication.
    private_key = "${file(var.private_key_path)}"
  }

  tags {
    Name = "web7"
  }

}

resource "aws_eip_association" "web7" {
  public_ip = "54.123.456.789"
  instance_id = "${aws_instance.web.id}"
}

```
