### ISSUE TITLE
An expression was successfully parsed, but extra characters were found after it

### ISSUE THREAD

**Issue by judika03** [hashicorp/terraform#24893] opened 2020-05-07 15:54 UTC
### Terraform Version

-->

```
v0.12.21

```

### Terraform Configuration Files

```hcl
...
resource "google_sql_user" "additional_users" {
  count   = length(var.additional_users)
  project = "kskkss"
  name    = var.additional_users[count.index]["name"]
  password = "dkdkdk"
  host     = djdjdj"
  instance   = google_sql_database_instance.master.name
  depends_on = [google_sql_database.default]
}

variable "additional_users" {
  description = "A list of users to be created in your cluster"
  type = list(map(string))
  default= []
}

```

### Debug Output

Error: Extra characters after expression

  on  line 1:
  (source code not available)

An expression was successfully parsed, but extra characters were found after
it.

### Steps to Reproduce

I have a "user database" module which is create database to provider cloud.

 I want to pass user database  from root module to  database module so anyone can add username for lopping adding user database with count .

**Comment by danieldreier** [comment] 2020-05-08 01:17
It looks to me like your reproduction case is missing quotes before the `djdjdj`. If you're missing that in your original code, that could be the cause of the error you're running into.

**Comment by apparentlymart** [comment] 2020-06-26 00:41
Hi @judika03,

We didn't hear back from you after @danieldreier's recent comment, so I'm going to close this under the assumption that his answer helped you avoid the error that you reported. If not, please share your latest configuration (including the fix previously suggested) and the new error message you're seeing (even if it's similar or identical to the previous one) and we can try to investigate further. Thanks!

**Closed by apparentlymart** 2020-06-26 00:41 UTC
Labels: waiting-response
