### ISSUE TITLE
aws: iam_group_membership Dropping and Recreating (when it doesn't need to)

### ISSUE THREAD

**Issue by GoatWalker** [hashicorp/terraform#4578] opened 2016-01-08 17:27 UTC
I'm using the aws provider and I want to add 3 users(alice,bob,charlie), 2 groups (group1, group2), and assign all three users to group1 and also assign alice and bob to group2.

When I run terraform the first time in an empty AWS account everything is created as expected(file and gist links to follow so it can be reproduced). When nothing changes and I run terraform a second time with same input it wants to drop and re-create the group memberships. The end state of AWS is no users are assigned to any group, but all three users and both groups remain in AWS.  Now if I run terraform again with same input a third time it puts AWS into the correct state, that is the user, groups, and group membership are setup as I described in my first paragraph.

Now my hope would be on any run after the first one with this scenario that when nothing has changed and input is the same that terraform would detect 0 changes and do nothing.

Files to reproduce:
**variables.tf ->** https://gist.github.com/henkbl/082f2902e67b4426b2ef

```hcl
variable "user_names" {
  description = "User names to create user accounts from"
}

variable "group_names" {
  description = "The group names to create groups from"
}

variable "group_membership_names" {
  description = "The group names to create group memberships from"
}

variable "user_membership_names" {
  description = "User names to create user/group memberships from"
}
```

**example.tf ->** https://gist.github.com/henkbl/00b987fc6d3483adf882

```hcl
provider "aws" {
    access_key = "YOURS"
    secret_key = "YOURS"
    region = "us-east-1"
}

resource "aws_iam_user" "user" {
  name = "${element(split(",", var.user_names), count.index)}"
  path = "/users/"
  count = "${length(split(",", var.user_names))}"
}

resource "aws_iam_group" "group" {
    name = "${element(split(",", var.group_names), count.index)}"
    path = "/groups/"
    count = "${length(split(",", var.group_names))}"
}

resource "aws_iam_group_membership" "mb" {
  name       = "group_membership"
  users      = ["${element(split(",", var.user_membership_names), count.index)}"]
  group      = "${element(split(",", var.group_membership_names), count.index)}"
  count      = "${length(split(",", var.group_membership_names))}"
  depends_on = ["aws_iam_group.group","aws_iam_user.user"]
}
```

**Command line call ->** https://gist.github.com/henkbl/2cc060347c4a415169f4
```
terraform plan -var 'user_names=bob,alice,charlie' -var 'group_names=group1,group2' -var 'group_membership_names=group1,group2,group1,group2,group1' -var 'user_membership_names=bob,bob,alice,alice,charlie'
```

Not in the command line call string that variables group_membership_names and user_membership_names is a mapping from user to group. The order matters as the first entry in  group_membership_names matches to the first entry in user_membership_names and the second matches the second and so on.

How To Reproduce(I'm pasting plan output before I run apply for each step below just to show easy to read output):
**1. Run Command line call string (Everything is created as expected)**
```
> terraform plan -var 'user_names=bob,alice,charlie' -var 'group_names=group1,group2' -var 'group_membership_names=group1,group2,group1,group2,group1' -var 'user_membership_names=bob,bob,alice,alice,charlie'
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_iam_group.group.0
    arn:       "" => "<computed>"
    name:      "" => "group1"
    path:      "" => "/groups/"
    unique_id: "" => "<computed>"

+ aws_iam_group.group.1
    arn:       "" => "<computed>"
    name:      "" => "group2"
    path:      "" => "/groups/"
    unique_id: "" => "<computed>"

+ aws_iam_group_membership.mb.0
    group:            "" => "group1"
    name:             "" => "group_membership"
    users.#:          "" => "1"
    users.4123767104: "" => "bob"

+ aws_iam_group_membership.mb.1
    group:            "" => "group2"
    name:             "" => "group_membership"
    users.#:          "" => "1"
    users.4123767104: "" => "bob"

+ aws_iam_group_membership.mb.2
    group:           "" => "group1"
    name:            "" => "group_membership"
    users.#:         "" => "1"
    users.663665735: "" => "alice"

+ aws_iam_group_membership.mb.3
    group:           "" => "group2"
    name:            "" => "group_membership"
    users.#:         "" => "1"
    users.663665735: "" => "alice"

+ aws_iam_group_membership.mb.4
    group:            "" => "group1"
    name:             "" => "group_membership"
    users.#:          "" => "1"
    users.1859863974: "" => "charlie"

+ aws_iam_user.user.0
    arn:       "" => "<computed>"
    name:      "" => "bob"
    path:      "" => "/users/"
    unique_id: "" => "<computed>"

+ aws_iam_user.user.1
    arn:       "" => "<computed>"
    name:      "" => "alice"
    path:      "" => "/users/"
    unique_id: "" => "<computed>"

+ aws_iam_user.user.2
    arn:       "" => "<computed>"
    name:      "" => "charlie"
    path:      "" => "/users/"
    unique_id: "" => "<computed>"


Plan: 10 to add, 0 to change, 0 to destroy.
```

**2. Run Command line call string again(Look in AWS and no one belongs to any groups).**
```
> terraform plan -var 'user_names=bob,alice,charlie' -var 'group_names=group1,group2' -var 'group_membership_names=group1,group2,group1,group2,group1' -var 'user_membership_names=bob,bob,alice,alice,charlie'
Refreshing Terraform state prior to plan...

aws_iam_user.user.1: Refreshing state... (ID: alice)
aws_iam_user.user.0: Refreshing state... (ID: bob)
aws_iam_group.group.0: Refreshing state... (ID: group1)
aws_iam_user.user.2: Refreshing state... (ID: charlie)
aws_iam_group.group.1: Refreshing state... (ID: group2)
aws_iam_group_membership.mb.0: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.4: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.3: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.2: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.1: Refreshing state... (ID: group_membership)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ aws_iam_group_membership.mb.0
    users.#:          "3" => "1"
    users.1859863974: "charlie" => ""
    users.4123767104: "bob" => "bob"
    users.663665735:  "alice" => ""

~ aws_iam_group_membership.mb.1
    users.#:          "2" => "1"
    users.4123767104: "bob" => "bob"
    users.663665735:  "alice" => ""

~ aws_iam_group_membership.mb.2
    users.#:          "3" => "1"
    users.1859863974: "charlie" => ""
    users.4123767104: "bob" => ""
    users.663665735:  "alice" => "alice"

~ aws_iam_group_membership.mb.3
    users.#:          "2" => "1"
    users.4123767104: "bob" => ""
    users.663665735:  "alice" => "alice"

~ aws_iam_group_membership.mb.4
    users.#:          "3" => "1"
    users.1859863974: "charlie" => "charlie"
    users.4123767104: "bob" => ""
    users.663665735:  "alice" => ""


Plan: 0 to add, 5 to change, 0 to destroy.
```

**3. Run Command line call string again(Look in AWS users are now assigned to correct groups)**
```
> terraform plan -var 'user_names=bob,alice,charlie' -var 'group_names=group1,group2' -var 'group_membership_names=group1,group2,group1,group2,group1' -var 'user_membership_names=bob,bob,alice,alice,charlie'
Refreshing Terraform state prior to plan...

aws_iam_group.group.1: Refreshing state... (ID: group2)
aws_iam_user.user.0: Refreshing state... (ID: bob)
aws_iam_group.group.0: Refreshing state... (ID: group1)
aws_iam_user.user.2: Refreshing state... (ID: charlie)
aws_iam_user.user.1: Refreshing state... (ID: alice)
aws_iam_group_membership.mb.2: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.4: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.3: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.0: Refreshing state... (ID: group_membership)
aws_iam_group_membership.mb.1: Refreshing state... (ID: group_membership)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ aws_iam_group_membership.mb.0
    users.#:          "0" => "1"
    users.4123767104: "" => "bob"

~ aws_iam_group_membership.mb.1
    users.#:          "0" => "1"
    users.4123767104: "" => "bob"

~ aws_iam_group_membership.mb.2
    users.#:         "0" => "1"
    users.663665735: "" => "alice"

~ aws_iam_group_membership.mb.3
    users.#:         "0" => "1"
    users.663665735: "" => "alice"

~ aws_iam_group_membership.mb.4
    users.#:          "0" => "1"
    users.1859863974: "" => "charlie"


Plan: 0 to add, 5 to change, 0 to destroy.
```

Thanks 
Bob

**Comment by henkbl** [comment] 2016-01-08 21:13
Forget to mention I did this on 0.6.8.

**Comment by stack72** [comment] 2016-02-28 01:57
Hi @GoatWalker - I have just been able to reproduce this exactly as you have mentioned. I will start having a look as to why this is the case

**Comment by rainmanh** [comment] 2016-04-25 13:21
Terraform v0.6.15 in here.
And I am experiencing the same issues.
Terraform seems to understand the users better if doing something as the following:
````
users = ["${aws_iam_user.iam_users_production.*.name}"]
````
Obviously the users have been created into another block and can recognise it's own indexing.
When applying a list it produces the issues described by @GoatWalker .

**Comment by catsby** [comment] 2016-05-02 22:43
Hello all – 

I apologize for the silence here. I’ve read up on the issue and can explain the root cause here and provide a workaround.

The provided configuration is attempting to manage users to groups dynamically via variables, however, it’s dynamically creating a `aws_iam_group_membership` _per user_, which is the crux of the reoccurring plan we’re seeing. The `aws_iam_group_membership` resource is designed to manage the entire user membership of a group, not simply attach a user to a group. In this case, we have 5 `aws_iam_group_membership` being created, one per each user, trying to manage just two groups, so there is overlap. Each `aws_iam_group_membership` is wanting to ensure only the users it has are attached to the group in question, so that’s why we see them wanting to remove the others users:

```
~ aws_iam_group_membership.mb.0
    users.#:          "3" => "1"
    users.1859863974: "charlie" => ""
    users.4123767104: "bob" => "bob"
    users.663665735:  "alice" => ""
```

Here we see it wants only 1 user for that membership resource, and that use is `bob`. Also note that all the `aws_iam_group_membership` are receiving the same `name`, which is used for lookup, further complicating the issue; the names need to be unique (not really the core problem though).

A natural solution would be to separate these memberships by listing the users per group in a tfvars file, but I believe we either do not know, or do not want to know, this information ahead of time and want to use variables so we don't have to edit text files all the time. 

To address this issue we need to do some things with the configuration and variables:

- only create one `aws_iam_group_membership` per `aws_iam_group`
- provide the mapping of _users-to-groups_ on the command line

Here’s the workaround we’ve come up with:

**variables.tf***

```
variable "user_names" {
  description = "User names to create user accounts from"
}

variable "group_names" {
  description = "The group names to create groups from"
}

variable "group_memberships" {
  description = "A mapping of group names to their members."
  type        = "map"

  # required empty default or you’ll get an error on the command line
  default = {}
}
```

**example.tf**

```
provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_user" "user" {
  name  = "${element(split(",", var.user_names), count.index)}"
  path  = "/users/"
  count = "${length(split(",", var.user_names))}"
}

resource "aws_iam_group" "group" {
  name  = "${element(split(",", var.group_names), count.index)}"
  path  = "/groups/"
  count = "${length(split(",", var.group_names))}"
}

resource "aws_iam_group_membership" "mb" {
  name       = "group_membership_${count.index}"
  # one per group name
  count      = "${length(split(",", var.group_names))}"
  group      = "${element(split(",", var.group_names), count.index)}”

  # here we find the group name we’re working on, and lookup it’s corresponding map value
  # we then split that value into the individual names
  users      = ["${split(",", lookup(var.group_memberships, element(split(",", var.group_names), count.index)))}"]
  depends_on = ["aws_iam_group.group", "aws_iam_user.user"]
}
```

**variables on the CLI**

```
-var 'user_names=bob,alice,charlie' -var 'group_names=group1,group2' -var 'group_memberships.group1=bob,alice,charlie' -var 'group_memberships.group2=alice,charlie'
```

In the variables we provide on the command line, we use a dot-notation feature to supply values to a map variable. 

Here’s the plan, apply, plan output:

- https://gist.github.com/catsby/9ca21383d56a0cefaabe641c4fd43132

I hope I’ve explained the issue here and provided an acceptable workaround for you. Please let me know what you think! And again, please accept my apology on taking so long to get to this :smile:

**Comment by rainmanh** [comment] 2016-05-03 14:15
@catsby Thank you so much for the provided workaround. It works perfectly fine as long as you do not use any sort of modules.

Have you got an example on how to get this done also using modules? The values for the mapping gets lost when using modules and I cannot see a simple solution to overcome this issue.

**Comment by catsby** [comment] 2016-05-03 14:34
The workaround suggested won't work with modules, unfortunately. There's another issue that documents the problem here: https://github.com/hashicorp/terraform/issues/1336

This should be addressed in an upcoming release, likely v0.7.0, but I don't have an ETA for that, unfortunately.

**Comment by catsby** [comment] 2016-05-03 15:37
Hey all – 

Another solution that should work with modules can be done by combining the membership information in a single string variable, and splitting on a special delimiter. 

**variables.tf:**
```hcl
variable "user_names" {
  description = "User names to create user accounts from"
}

variable "group_names" {
  description = "The group names to create groups from"
}

variable "group_membership_names" {
  description = "The group membership mapping"
}
```

**example_config.tf:**
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_user" "user" {
  name  = "${element(split(",", var.user_names), count.index)}"
  path  = "/users/"
  count = "${length(split(",", var.user_names))}"
}

resource "aws_iam_group" "group" {
  name  = "${element(split(",", var.group_names), count.index)}"
  path  = "/groups/"
  count = "${length(split(",", var.group_names))}"
}

resource "aws_iam_group_membership" "mb" {
  name       = "group_membership_${count.index}"
  users      = ["${split(",", element(split("|", var.group_membership_names), count.index))}"]
  group      = "${element(split(",", var.group_names), count.index)}"
  count      = "${length(split(",", var.group_names))}"
  depends_on = ["aws_iam_group.group", "aws_iam_user.user"]
}
```

**invocation:**

```
$ terraform plan -var 'user_names=bob,alice,charlie' -var 'group_names=group1,group2' -var 'group_membership_names=bob,alice,charlie|bob,alice'
```

(not the "pipe" `|` separator between `charlie` and `bob`)

Here the `group_membership_names` variable lists the users, separated by `,`, and in the matching order of the groups in `group_names`. The membership is divided by the pipe `|` symbol. The `users` attribute in `aws_iam_group_membership` will split `group_membership_names` on the pipe, and then further split that result into the list of users. 

I believe this should get around the limitation of maps and modules, please try it out and let me know!

**Comment by rainmanh** [comment] 2016-05-03 20:44
your proposed solution works well for the modules @catsby 

I would like to also include an extra for any of those who are trying to automate the inclusion of policies for the groups
for example..:
`````
resource "aws_iam_group_policy" "group_policies" {
    name = "policy_${element(split(",", var.group_names), count.index)}"
    count = "${length(split(",", var.group_names))}"
    group = "${element(split(",", var.group_names), count.index)}"
    policy = "${file(\"policies/${element(split(",", var.group_names), count.index)}/policies.json\")}"
    depends_on = ["aws_iam_group.group"]
}

`````

**Comment by catsby** [comment] 2016-05-04 16:22
Hey all – it looks like the workarounds are viable, so I'm going to close this. If you're using modules, you'll need to use the latter approach until https://github.com/hashicorp/terraform/issues/1336 is resolved.

Thanks!

**Closed by catsby** 2016-05-04 16:22 UTC
Labels: bug, provider/aws, waiting-response

**Comment by gsaslis** [comment] 2017-04-10 03:43
@catsby thanks for the explanation and options suggested - was running into this.
