### ISSUE TITLE
user-data forces new resource when you move from windows to linux

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#8467] opened 2016-08-25 09:36 UTC
Terraform v0.7.1

user-data forces new resource when you move terraform apply from windows to linux and vice versa

When I launch infrastructure on a windows platform and commit to code commit and a colleague on a linux platform pulls down down latest commit, user_data will want to force a new resource. I have verified this also happens from Linux to windows when the apply is done from the linux OS and latest commit pulled down from to windows.

I have ensured the file line endings are CRLF when running in windows and LF in in Linux as I had seen this mentioned as a potential issue.

This is a hindrance as I have to comment out user-data once an environment is launched to allow users on linux platforms platforms to manage the infrastructure without destroying the entire infrastructure with a terraform apply. This has obvious consequences if I ever want to increase the count of my instances since user-data is then commented out.

Anyone seeing this?

**Comment by jamielennox1** [comment] 2016-08-30 14:04
My team is having this issue as well. Passing modules with user-data between MacBooks will cause the SHA to change. To stop this, we just add:
`lifecycle {
  ignore_changes = [ "user_data" ]
}`

**Comment by davyt10** [comment] 2016-08-30 15:25
Tested and working, thanks!

**Comment by mitchellh** [comment] 2016-08-30 21:50
Are you specifying user data as a direct string or via the `file` function call?

**Comment by davyt10** [comment] 2016-08-31 07:31
I am using the file function call.

**Comment by Dchamard** [comment] 2016-09-02 14:36
Having the same problem here in 7.0.1 using template_file resource in userdata.

**Comment by PeteGoo** [comment] 2016-11-14 07:52
Same thing using `template_file` on 0.7.10. Windows users are getting a forced change to e.g. policies. Probably due to git autocrlf.

**Comment by jgeorgeson** [comment] 2017-04-06 20:29
Still seeing this in 0.9.2. @PeteGoo I think it's definitely line endings. When I flip the script file's line endings the checksum once again matches the _before_ side of the `terraform plan` output. But instead of saying nothing to do `plan` now says it has to deploy everything new. :frowning_face:

**Comment by jgeorgeson** [comment] 2017-04-06 20:55
I was able to recover by running `terraform list` and then running `terraform state refresh -target=...` on every resource after fixing the eol on the userdata script. So it wasn't _just_ the eol but that was definitely the instigator.

**Comment by dtelaroli** [comment] 2019-01-25 11:24
Same problem with terraform 1.11.11

**Comment by teamterraform** [comment] 2019-07-17 23:08
Hi all,

Terraform explicitly does _not_ normalize line endings by platform, so you must ensure that nothing else in your workflow is causing line endings to be different by platform. Terraform does not automatically normalize line endings specifically _because_ files loaded in to Terraform are often intended to be submitted to a remote system that may be running a different operating system and thus Terraform cannot predict with certainty which line ending convention would be appropriate.

In particular, it's important to ensure that your version control system is not rewriting line endings when pushing and pulling changes between platforms. For Git, one way to force that is to tell Git to treat the files in question as binary by placing a file called `.gitattributes` in the root of the repository, with content like the following:

```
*.tmpl binary
*.sh binary
```

You can find more details on this in [GitHub's guide to line endings in Git](https://help.github.com/en/articles/configuring-git-to-handle-line-endings).

We're going to close this now because unfortunately Terraform is working as expected here and the problem is with some other system (often Git) making unexpected changes to the files. Terraform itself cannot detect that this has happened or prevent it, so there's unfortunately nothing we can do within Terraform itself to avoid this problem.

Sorry for the long delay in responding. Hopefully the above is helpful to those who have encountered this problem.

**Closed by teamterraform** 2019-07-17 23:08 UTC
Labels: bug, config
