### ISSUE TITLE
aws_iam_policy_attachment removes AWS managed policies from users

### ISSUE THREAD

**Issue by harpermann** [hashicorp/terraform#10592] opened 2016-12-07 23:55 UTC
Hi Hashicorp!

### Terraform Version
**Terraform v0.7.13**

### Affected Resource(s)
- AWS IAM Policies

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# create IAM Roles for instances
resource "aws_iam_role" "gep_jenkins_role" {
    name = "gep-jenkins-role"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

# Create policy attachment
resource "aws_iam_policy_attachment" "gep-jenkins-role-policy-attachment" {
    role = "${aws_iam_role.gep_jenkins_role.name}"
    policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}
```

### Debug Output
aws_iam_role.gep_jenkins_role: Refreshing state... (ID: gep-jenkins-role)
aws_iam_instance_profile.gep_jenkins_profile: Refreshing state... (ID: gep-jenkins-profile)
aws_iam_policy_attachment.test-attach: Refreshing state... (ID: gep-iam-admin-policy)
aws_iam_policy_attachment.test-attach: Destroying...
aws_iam_policy_attachment.test-attach: Destruction complete

### Panic Output
Did not core dump.

### Expected Behavior
Terraform shouldn't "touch" things it hasn't "touched".  We didn't have terraform add the policy to the users so it should have left it attached on destroy.

At least, the documentation should carefully warn policies will be detached from anywhere that uses the policy.

### Actual Behavior
Terraform detached the policy from everything that used the policy

### Steps to Reproduce
1. Add a policy to a user
2. set up a policy attachment using aws_iam_policy_attachment with the same policy as the user has.
3. terraform apply to make the policy attachment.
4. terraform destroy.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?   NO

Does aws_iam_role_policy_attachment work more like we want?  That is, it won't detach a policy from a user that wasn't added with terraform?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For NO

**Comment by catsby** [comment] 2016-12-09 18:53
Hello –

Sorry for the trouble here. `aws_iam_policy_attachment` is a resource that is a bit far-reaching, in that it expects to be the complete source of truth for policies for any role, user, or group that it attaches policies too:

From https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html: 

> NOTE: The aws_iam_policy_attachment resource is only meant to be used once for each managed policy. All of the users/roles/groups that a single policy is being attached to should be declared by a single aws_iam_policy_attachment resource.

Perhaps [`aws_iam_user_policy`](https://www.terraform.io/docs/providers/aws/r/iam_user_policy.html) or [`aws_iam_user_policy_attachment`](https://www.terraform.io/docs/providers/aws/r/iam_user_policy_attachment.html) would work better for your use case? 

I am going to close this issue, as it stands `aws_iam_policy_attachment` behaves as documented/expected. 

If `aws_iam_user_policy` or `aws_iam_user_policy_attachment` don't fit, perhaps you could describe your use case / scenario and we may have an idea. 

Thanks!

**Closed by catsby** 2016-12-09 18:53 UTC
Labels: bug, provider/aws

**Comment by harpermann** [comment] 2016-12-09 18:59
Hi Clint,
Thanks for the quick response.  Our fix is to NOT use policies that already
existed, make a new one and use that one on TF.

We had previously grabbed the existing, managed, Administrator policy so
when TF destroyed the policy attachment, it detached the policy from
everywhere, including our pre-existing IAM administrator Users which we
weren't expecting.

All good.  Thanks!

Cheers
Harper


Harper Mann
510-599-2075 mobile

**Comment by catsby** [comment] 2018-04-26 14:17
Sorry for the trouble @sharath-yml . This behavior is by design and is documented with a prominent warning:

- https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html
