### ISSUE TITLE
base64encode of multi line script not encoded properly

### ISSUE THREAD

**Issue by ryanmckeague** [hashicorp/terraform#20860] opened 2019-03-28 18:24 UTC
### Terraform Version

```
Terraform v0.11.13
```

### Terraform Configuration Files

```
    "customData"                  = "${base64encode(data.template_file.cloudconfig.rendered)}"
  }

  deployment_mode = "Incremental"
}

data "template_file" "cloudconfig" {
  template = "${file("${var.custom_data_loc}")}"
}
variable "custom_data_loc" {
  type        = "string"
  description = "path to custom data .sh file"
}

In .tfvars
custom_data_loc = "path to data.sh"

data.sh

(sensitive data removed, but result is the same)

#!/bin/bash
curl -O https://bootstrap.pypa.io/get-pip.py 
/usr/bin/python get-pip.py --user 
pip install awscli --upgrade --user
aws configure set aws_access_key_id 
aws configure set aws_secret_access_key 
aws configure set default.region us-west-2 
aws s3 cp s3://
aws s3 cp s3://
sudo mkdir /sysinstall 
sudo mkdir /features
sudo mount -t iso9660 -o loop /tmp/ /sysinstall
sudo mount -t iso9660 -o loop /tmp/ /features 
sudo chmod +x /sysinstall/install.sh 
sudo /sysinstall/install.sh
```

### Expected Behavior

data.sh should be read and rendered and then base64encoded for the customData variable

### Actual Behavior

My data.sh file is being read and rendered by data.template_file. If I remove the base64encode() from the customData variable, then I see the script output as expected, however, with the base64encode() in place the script is not properly encoded. 

If I replace the script with a simple '1234' it is properly base64 encoded. 

My full script is 1437 bytes. 

I expect there is some limitation or step I must take for a multi-line file input to be properly encoded?

**Comment by apparentlymart** [comment] 2019-03-28 20:38
Hi @ryanmckeague! Sorry for this strange behavior and thanks for reporting it.

I'm not sure I fully understand what you're seeing here. When you say that the script is "not properly encoded", what exactly do you mean by that? Is the result not valid base64, or is it decoding to something other than what you expect, or something else?

The configuration you shared seems to start in the middle of a block so it's hard to see what exactly is going on here. If you're able to share a minimal valid configuration illustrating the problem that'd be a big help for us to understand what the problem is here.

**Comment by ryanmckeague** [comment] 2019-03-28 21:37
terraform.tf

```
provider "azurerm" {
  version                     = "=1.22.0"
  subscription_id             = "${var.subscription_id}"
  client_id                   = "${var.client_id}"
  client_certificate_path     = "${var.client_certificate_path}"
  client_certificate_password = "${var.client_certificate_password}"
  tenant_id                   = "${var.tenant_id}"
}

resource "azurerm_network_interface" "linux_nic" {
  count               = "${var.count}"
  name                = "${element(var.nic_name, count.index)}"
  location            = "${element(var.location, count.index)}"
  resource_group_name = "${element(var.rg_name, count.index)}"

  ip_configuration {
    name                          = "${element(var.ip_name, count.index)}"
    subnet_id                     = "${element(var.subnet_id, count.index)}"
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_virtual_machine" "linux_vm" {
  count                 = "${var.count}"
  name                  = "${element(var.vm_name, count.index)}"
  location              = "${element(var.location, count.index)}"
  resource_group_name   = "${element(var.rg_name, count.index)}"
  network_interface_ids = ["${element(azurerm_network_interface.linux_nic.*.id, count.index)}"]
  vm_size               = "${var.vm_size}"

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  delete_os_disk_on_termination = true

  # Uncomment this line to delete the data disks automatically when deleting the VM
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "${var.image_publisher}"
    offer     = "${var.image_offer}"
    sku       = "${var.image_sku}"
    version   = "${var.image_version}"
  }

  storage_os_disk {
    name              = "${element(var.os_disk_name, count.index)}"
    os_type           = "Linux"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  storage_data_disk {
    name              = "${element(var.data_disk_name, count.index)}"
    managed_disk_type = "Standard_LRS"
    create_option     = "Empty"
    lun               = 0
    disk_size_gb      = "128"
  }

  os_profile {
    computer_name  = "${element(var.computer_name, count.index)}"
    admin_username = "${element(var.AdminUsername, count.index)}"
    admin_password = "${element(var.AdminPassword, count.index)}"
    custom_data    = "${base64encode(data.template_file.cloudconfig.rendered)}"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
}
data "template_file" "cloudconfig" {
  template = "${file("${var.custom_data_loc}")}"
}
```
variables.tf
```
variable "custom_data_loc" {
  description = "path to custom data .sh file"
}
```
.tfvars

```
custom_data_loc = "/path/to/test.sh"
```
test.sh
```
#!/bin/bash
curl -O https://bootstrap.pypa.io/get-pip.py 
/usr/bin/python get-pip.py --user 
pip install awscli --upgrade --user
pip install awscli --upgrade --user 
aws configure set aws_access_key_id 
aws configure set aws_secret_access_key 
aws configure set default.region us-west-2 
aws s3 cp s3://
aws s3 cp s3://
sudo mkdir /sysinstall 
sudo mkdir /features
sudo mount -t iso9660 -o loop /tmp/ /sysinstall
sudo mount -t iso9660 -o loop /tmp/ /features 
sudo chmod +x /sysinstall/install.sh 
sudo /sysinstall/install.sh
```
Running terraform plan results in:

```
os_profile.2981839690.custom_data:                                  "3ea6bf8b2d579a6dc594d85d3a4187c6799ef07d"
```

Should be:
```
IyEvYmluL2Jhc2gKY3VybCAtTyBodHRwczovL2Jvb3RzdHJhcC5weXBhLmlvL2dldC1waXAucHkgCi91c3IvYmluL3B5dGhvbiBnZXQtcGlwLnB5IC0tdXNlciAKcGlwIGluc3RhbGwgYXdzY2xpIC0tdXBncmFkZSAtLXVzZXIKcGlwIGluc3RhbGwgYXdzY2xpIC0tdXBncmFkZSAtLXVzZXIgCmF3cyBjb25maWd1cmUgc2V0IGF3c19hY2Nlc3Nfa2V5X2lkIAphd3MgY29uZmlndXJlIHNldCBhd3Nfc2VjcmV0X2FjY2Vzc19rZXkgCmF3cyBjb25maWd1cmUgc2V0IGRlZmF1bHQucmVnaW9uIHVzLXdlc3QtMiAKYXdzIHMzIGNwIHMzOi8vCmF3cyBzMyBjcCBzMzovLwpzdWRvIG1rZGlyIC9zeXNpbnN0YWxsIApzdWRvIG1rZGlyIC9mZWF0dXJlcwpzdWRvIG1vdW50IC10IGlzbzk2NjAgLW8gbG9vcCAvdG1wLyAvc3lzaW5zdGFsbApzdWRvIG1vdW50IC10IGlzbzk2NjAgLW8gbG9vcCAvdG1wLyAvZmVhdHVyZXMgCnN1ZG8gY2htb2QgK3ggL3N5c2luc3RhbGwvaW5zdGFsbC5zaCAKc3VkbyAvc3lzaW5zdGFsbC9pbnN0YWxsLnNo
```

Thanks!

**Comment by apparentlymart** [comment] 2019-03-28 22:24
Hi @ryanmckeague!

I took a look at the definition of that `custom_data` attribute in the AzureRM provider and it appears to have [an override for how the data is stored in the state](https://github.com/terraform-providers/terraform-provider-azurerm/blob/3625e6f5b31e2b6bf581cfa7cc84c9837db10a8a/azurerm/resource_arm_virtual_machine.go#L384), which is taking a SHA1 hash of the data. This affects the value seen by references to that value elsewhere in the configuration, but it should still be sent to the remove system as the base64-encoded value.

This practice of storing a hash in the state is an older practice to try to reduce the size of the data shown in the diff, and we generally don't do it for new attributes now because (as you've seen here) it can be confusing, but there are some existing instances of it in providers, such as this one.

I suspect that in spite of the confusing plan here you'll still see the result you want once you apply this, if I'm reading the provider code correctly. You may wish to also open an issue in [the `azurerm` provider repository](https://github.com/terraform-providers/terraform-provider-azurerm) to confirm and to see also if there's the possibility of somehow migrating away from the hashed storage here, though it may require a major release to do since it may turn out to be a breaking change.

Since it seems like Terraform _Core_ is behaving as expected here, I'm going to close this out. If you do open an issue in the AzureRM provider, please feel free to link to this issue (as hashicorp/terraform#20860) as additional context.

**Closed by apparentlymart** 2019-03-28 22:24 UTC
Labels: bug
