### ISSUE TITLE
Terraform init fails when override.tf contains module override without source parameter (v0.12.0-beta1)

### ISSUE THREAD

**Issue by tomtheun** [hashicorp/terraform#20550] opened 2019-03-03 18:00 UTC
### Terraform Version
```
Terraform v0.12.0-beta1
```

### Terraform Configuration Files

main.tf
```hcl
module "foo" {
  source = "./my-module"
}
```
override.tf
```hcl
module "foo" {}
```
my-module/main.tf
```hcl
# Empty
```

### Expected Behavior
No errors when running `terraform init`

### Actual Behavior
The `init` command returns the following error:
```
Initializing modules...
Downloading  for foo...

Error: Failed to download module

Error attempting to download module "foo" (override.tf:1) source code from "":
invalid source string:


Error: Failed to download module

Error attempting to download module "foo" (override.tf:1) source code from "":
invalid source string:
```

### Steps to Reproduce
Just run `terraform init` with the code as stated above.

### Additional Context
Exactly the same setup works with `Terraform v0.11.11`. 

Workaround is to also define the source parameter in override, e.g.:

override.tf
```hcl
module "foo" {
  source = "./my-module"
}
```

**Comment by apparentlymart** [comment] 2019-03-06 00:16
Thanks for reporting this, @tomtheun!

This appears to be a regression caused by some special behavior we added to allow `terraform init` to complete when the configuration contains problems that can be resolved by a subsequent `terraform 0.12upgrade`: it uses the [terraform-config-inspect](https://github.com/hashicorp/terraform-config-inspect) parser instead, because it has support for both the old and new formats, but apparently it doesn't support override files correctly and so the override file's missing `source` is clobbering the one that was set in the non-override file.

This other parser is trying to be liberal and support both 0.11 and 0.12 details, so we may not be able to exactly replicate the main override processing behavior here, but I think we should be able to manage a special case for module `source` since it's already handled as special inside `terraform-config-inspect`.

**Closed** 2019-03-28 11:54 UTC
Labels: bug, config
