### ISSUE TITLE
v0.10.1 panic: nil pointer dereference in client.go

### ISSUE THREAD

**Issue by yangmillstheory** [hashicorp/terraform#15827] opened 2017-08-16 16:19 UTC
### Terraform Version
```
(terraform-plans)
🤔 ~/c/a/t/l/batch_query_human_api (564e50d)|master✓
± [i]: terraform --version
Terraform v0.10.1
```

### Debug Output
https://gist.github.com/yangmillstheory/bc6b2721ab4a8c1586259eb7d80a48ee

### Panic Output

```
aws_api_gateway_method_response.human_api_notifications_401: Refreshing state... (ID: agmr-5tvi4httbh-ihpwkr-POST-401)
aws_security_group.internal_alb_sg: Refreshing state... (ID: sg-cd5deab6)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x17792fc]

goroutine 30204 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).logStderr(0xc420f40e00, 0x417daa0, 0xc42021ca68)
        /private/tmp/terraform-20170815-18271-16pvyh9/terraform-0.10.1/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:750 +0x39c
created by github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).Start
        /private/tmp/terraform-20170815-18271-16pvyh9/terraform-0.10.1/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:544 +0xe2f



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.


When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected Behavior
`terraform plan` is clean (no diff).

### Actual Behavior
`terraform plan` crashed.

**Comment by jbardin** [comment] 2017-08-16 16:35
Duplicate of #15822

**Closed by jbardin** 2017-08-16 16:35 UTC
Labels: crash
