### ISSUE TITLE
Allow selection or filter of element(s) from a set result

### ISSUE THREAD

**Issue by MikeWhittakerRyff** [hashicorp/terraform#26698] opened 2020-10-24 13:27 UTC
When a data source returns a set result, it would be most useful to be able to access the result in some selective manner.
Example below, from the AMI I want to read the device_name, but the *.block_device_mappings is a set, so I cannot do so.

The set cannot be indexed, or selected, so we have no way to filter out or access the value of device_name of the root device.

In this case, I would eg select the element in which ebs is not "{}" - or a synonym element with .root attribute would be handy.

eg

when

```
output "volume_mappings" {
  value = "${local.ami_type.*.block_device_mappings}"
}


```
returns
```
    {
      "device_name" = "/dev/sda1"
      "ebs" = {
        "delete_on_termination" = "true"
        "encrypted" = "false"
        "iops" = "0"
        "snapshot_id" = "snap-0290d1d1b92a0cf6d"
        "volume_size" = "8"
        "volume_type" = "gp2"
      }
      "no_device" = ""
      "virtual_name" = ""
    },
    {
      "device_name" = "/dev/sdb"
      "ebs" = {}
      "no_device" = ""
      "virtual_name" = "ephemeral0"
    },
    {
      "device_name" = "/dev/sdc"
      "ebs" = {}
      "no_device" = ""
      "virtual_name" = "ephemeral1"
    },
  ],
```

**Comment by pkolyvas** [comment] 2020-10-26 12:53
Thanks for the submission @MikeWhittakerRyff. While we aren't planning on working on this is the near term, it would be a valuable addition to Terraform.

I'm going to close this as a duplicate of #19931.

**Closed by pkolyvas** 2020-10-26 12:53 UTC
Labels: config, enhancement
