### ISSUE TITLE
When changing VPC CIDR, state diff crash occured

### ISSUE THREAD

**Issue by Genert** [hashicorp/terraform#20825] opened 2019-03-26 13:29 UTC
### Terraform Version
```
Terraform v0.11.13
```

### Terraform Configuration Files
Following module was used - https://github.com/hashicorp/terraform-aws-consul/tree/master/modules/consul-cluster
```hcl
module "consul_servers" {
  source  = "hashicorp/consul/aws//modules/consul-cluster"
  version = "0.5.0"

  cluster_name  = "consul-server-${var.environment}"
  cluster_size  = "${var.cluster_size}"
  instance_type = "${var.instance_type}"
  spot_price    = ""

  # The EC2 Instances will use these tags to automatically discover each other and form a cluster
  cluster_tag_key   = "consul-cluster"
  cluster_tag_value = "consul-${var.environment}"

  ami_id    = "${data.aws_ami.consul_server.image_id }"
  user_data = "${data.template_file.user_data_server.rendered}"

  vpc_id     = "${var.vpc_id}"
  subnet_ids = "${var.external_subnets}"

  # To make testing easier, we allow Consul and SSH requests from any IP address here but in a production
  # deployment, we strongly recommend you limit this to the IP address ranges of known, trusted servers inside your VPC.
  allowed_ssh_cidr_blocks = ["0.0.0.0/0"]

  allowed_inbound_cidr_blocks = ["0.0.0.0/0"]
  ssh_key_name                = "${var.ssh_key_name}"

  tags = [
    {
      key                 = "Environment"
      value               = "${var.environment}"
      propagate_at_launch = true
    },
  ]
}
```

### Crash Output
```
* module.consul.module.consul_servers.aws_autoscaling_group.autoscaling_group: aws_autoscaling_group.autoscaling_group: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.13
    Resource ID: aws_autoscaling_group.autoscaling_group
    Mismatch reason: attribute mismatch: availability_zones.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"availability_zones.#":*terraform.ResourceAttrDiff{Old:"3", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.1924028850":*terraform.ResourceAttrDiff{Old:"eu-west-1b", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.3953592328":*terraform.ResourceAttrDiff{Old:"eu-west-1a", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.94988580":*terraform.ResourceAttrDiff{Old:"eu-west-1c", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "launch_configuration":*terraform.ResourceAttrDiff{Old:"consul-server-production-2019032400431731850000000d", New:"${aws_launch_configuration.launch_configuration.name}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"launch_configuration":*terraform.ResourceAttrDiff{Old:"consul-server-production-2019032400431731850000000d", New:"consul-server-production-20190326130324016900000003", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.1181613190":*terraform.ResourceAttrDiff{Old:"subnet-008a38183cca8b8cc", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.1286800704":*terraform.ResourceAttrDiff{Old:"", New:"subnet-053d04d97f2c3c555", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.2023865853":*terraform.ResourceAttrDiff{Old:"", New:"subnet-0631581b7985b1c49", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.3062454463":*terraform.ResourceAttrDiff{Old:"subnet-0b24bafecb1a8fb56", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.545527055":*terraform.ResourceAttrDiff{Old:"", New:"subnet-0b4b0bde9fd8eb172", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.8985591":*terraform.ResourceAttrDiff{Old:"subnet-02921d6fa67ff95b4", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```
### Expected Behavior
I changed VPC CIDR block. This destroys all VPC related resources as expected, and spins up everything within new created VPC with desired CIDR.

### Actual Behavior
VPC did not get destroyed, in-fact some resources did end up within dustbin, but most did not. Seems to be problem of dependency between resources? Configuration problem, or issue with Terraform?

### Additional Context
Terragrunt is used as a wrapper. The command was executed locally on Mac OSX (10.14.3).

**Comment by mildwonkey** [comment] 2019-03-26 14:30
Hi @Genert,
I'm sorry you've experienced this issue. Can you please add the full crash log (shared as a gist, with any sensitive information redacted) so we can identify if this problem was caused by the provider, or terraform core? Thanks, and sorry again!

**Comment by mildwonkey** [comment] 2019-04-15 15:32
I am going to close this since there's been no update, but will re-open if necessary. Thanks!

**Closed by mildwonkey** 2019-04-15 15:32 UTC
Labels: bug, crash
