### ISSUE TITLE
Instance is marked as having a change pending but that change is not recorded in the plan. This is a bug in Terraform; please report it.

### ISSUE THREAD

**Issue by rwblokzijl** [hashicorp/terraform#35893] opened 2024-10-23 12:10 UTC
### Terraform Version

```shell
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.3
```

### Terraform Configuration Files

```terraform
resource "null_resource" "resource_name" {
}
data "null_data_source" "data_source_name" {
  # Increase number of resources to increase the changes of error (issue is non-deterministic)
  for_each = toset(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", ])
  lifecycle {
    postcondition {
      # To repoduce
      # Either condition OR error_message must use self.*, true or false result does not matter
      condition = self.outputs == null
      # Must depend on resource not known until apply
      error_message = null_resource.resource_name.id
    }
  }
}
```

### Debug Output

https://gist.github.com/rwblokzijl/6a5aa1acfcc28f5d2451ab0f82a14844

### Expected Behavior

No error.

### Actual Behavior

It non-determisistically errors.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. repeat step 2 until it errors (issue is non-deterministic)

### References

https://github.com/hashicorp/terraform/issues/34310

**Comment by jbardin** [comment] 2024-10-23 12:33
Thanks for the example @rwblokzijl!

Duplicate of #34310

**Closed by jbardin** 2024-10-23 12:33 UTC
Labels: bug, new
