### ISSUE TITLE
The true and false result expressions must have consistent types. The given expressions are object and object, respectively.

### ISSUE THREAD

**Issue by ghostsquad** [hashicorp/terraform#27877] opened 2021-02-23 01:03 UTC
### Terraform Version

```
Terraform v0.13.6
```

### Terraform Configuration Files

`v` is either a number or a complex object

```terraform
locals {
  ports_ = {
    for k,v in var.ports : k =>
      merge(
      { 
        name = k
      },
      can(tonumber(v)) ? { containerPort = v } : merge(
        { containerPort = v.containerPort },
        length(compact([ lookup(v, "name", null) ])) == 0 ? {} : { name = v.name },
        length(compact([ lookup(v, "hostIP", null) ])) == 0 ? {} : { hostIP = v.hostIP },
        length(compact([ lookup(v, "hostPort", null) ])) == 0 ? {} : { hostPort = v.hostPort },
        length(compact([ lookup(v, "protocol", null) ])) == 0 ? {} : { protocol = v.protocol }
      )
    )
  }
}
```

### Expected Behavior

I can create set a value to either a complex variant or a simple variant as needed.

### Actual Behavior

```
Error: Inconsistent conditional result types

  on outputs.tf line 14, in locals:
  14:       can(tonumber(v)) ? { containerPort = v } : merge(
  15:         { containerPort = v.containerPort },
  16:         length(compact([ lookup(v, "name", null) ])) == 0 ? {} : { name = v.name },
  17:         length(compact([ lookup(v, "hostIP", null) ])) == 0 ? {} : { hostIP = v.hostIP },
  18:         length(compact([ lookup(v, "hostPort", null) ])) == 0 ? {} : { hostPort = v.hostPort },
  19:         length(compact([ lookup(v, "protocol", null) ])) == 0 ? {} : { protocol = v.protocol }
  20:       )
    |----------------
    | v.containerPort is 2
    | v.hostIP is "1.1.1.1"
    | v.hostPort is 1
    | v.name is "a-override"
    | v.protocol is "TCP"

The true and false result expressions must have consistent types. The given
expressions are object and object, respectively.        	            	
```

**Comment by ghostsquad** [comment] 2021-02-23 01:23
I also tried this in `0.14.7`

**Comment by alisdair** [comment] 2021-02-23 18:31
Hi @ghostsquad, thanks for reporting this.

This looks like a duplicate of #23364, where the bug here is an unclear diagnostic message. The root problem is that both sides of a ternary expression must have the same type (or types which can be unified). The left side of your expression is type `object({ containerPort: number })`, and I think the right side is `map(string)` (although I may be wrong, the expression is complex).

I'm not completely sure what the use case you have here is, but it seems like it might benefit from [the optional object type attributes experiment](https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes). I would recommend [posting in the Terraform discussion forum](https://discuss.hashicorp.com/c/terraform-core/27) about what you're trying to achieve here, and hopefully someone will be able to help.

Closing as duplicate of #23364.

**Closed by alisdair** 2021-02-23 18:31 UTC
Labels: bug, new
