### ISSUE TITLE
Crash v0.6.12 when user_data is null in aws_launch_configuration

### ISSUE THREAD

**Issue by elisehuard** [hashicorp/terraform#5420] opened 2016-03-02 15:35 UTC
I'm using a (self-generated) json spec.  Crash caused by:

    "aws_launch_configuration" : {
      "master-group" : {
        "name_prefix" : "master-group-",
        "image_id" : "ami-07f1ec6b",
        "instance_type" : "m4.xlarge",
        "user_data" : null,
        "lifecycle" : {
          "create_before_destroy" : true
        },
        "key_name" : "ops-terraboot",
        "security_groups" : [ "${aws_security_group.master-security-group.id}", "${aws_security_group.admin-security-group.id}", "${aws_security_group.allow_elb_master-group.id}" ],
        "ebs_block_device" : {
          "device_name" : "/dev/xvda",
          "volume_size" : 20
        }
      }
    } 

This was obviously a mistake on my part, but since the error message mentions you want to know about crashes, here goes.

**Comment by jen20** [comment] 2016-03-03 15:58
Hi @elisehuard! Thanks for reporting this. We will try to reproduce this and fix it - anything which results in a Terraform crash is definitely a bug.

**Comment by rvandegrift** [comment] 2016-03-10 19:21
Doesn't look AWS-specific - a null value anywhere in a config causes the crash for me.  This is sufficient:
```
{
    "variable": {
        "woo": { "default": null }
    }
}
```

**Comment by jen20** [comment] 2016-03-21 15:00
Thanks for reporting this - I can indeed reproduce. It looks like a bug in HCL, so I'll take a look and get it fixed up!

**Comment by jbardin** [comment] 2016-10-18 19:11
I'm fairly certain this is fixed now. If you have another way to reproduce the crash, feel free to add it and I can reopen the issue.

**Closed by jbardin** 2016-10-18 19:11 UTC
Labels: bug, core, crash
