### ISSUE TITLE
Terraform Crash after upgrading to v0.13.1 in mac machine

### ISSUE THREAD

**Issue by SamaChandra** [hashicorp/terraform#26046] opened 2020-08-28 20:31 UTC
### Terraform Version

v0.13.1
...
```

### Terraform Configuration Files
<!--


-->

```terraform
...
```
panic: not a collection type

goroutine 10909 [running]:
github.com/zclconf/go-cty/cty.Type.ElementType(0x38e45e0, 0xc0041324d0, 0xc000e36478, 0x8)
	github.com/zclconf/go-cty@v1.5.1/cty/collection.go:25 +0xba
github.com/hashicorp/terraform/terraform.createEmptyBlocks(0xc0022114d0, 0x38e45e0, 0xc0041324e0, 0x2efeb80, 0xc009e80d50, 0x38e45e0, 0xc0041325b8, 0x2efeb80, 0xc009e8ce40)
	github.com/hashicorp/terraform/terraform/eval_read_data_plan.go:242 +0x202
github.com/hashicorp/terraform/terraform.dataObjectHasChanges(0xc0022114d0, 0x38e45e0, 0xc0041324e0, 0x2efeb80, 0xc009e80d50, 0x38e45e0, 0xc0041325b8, 0x2efeb80, 0xc009e8ce40, 0x0, ...)
	github.com/hashicorp/terraform/terraform/eval_read_data_plan.go:211 +0x19e
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc00a40e1e0, 0x3926080, 0xc001540270, 0x1, 0x1, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval_read_data_plan.go:107 +0x1238
github.com/hashicorp/terraform/terraform.EvalRaw(0x387c8c0, 0xc00a40e1e0, 0x3926080, 0xc001540270, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc001a61d40, 0x3926080, 0xc001540270, 0x1, 0x1, 0x6, 0xc000baa590)
	github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x387c320, 0xc001a61d40, 0x3926080, 0xc001540270, 0x2eb3460, 0x4b98942, 0x2e12f00, 0xc0078af5f0)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.Eval(0x387c320, 0xc001a61d40, 0x3926080, 0xc001540270, 0xc001a61d40, 0x387c320, 0xc001a61d40, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x32443e0, 0xc0078aeed0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/graph.go:73 +0xc77
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000baa480, 0x32443e0, 0xc0078aeed0, 0xc002000840)
	github.com/hashicorp/terraform/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	github.com/hashicorp/terraform/dag/walk.go:309 +0x11d7

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by nexxai** [comment] 2020-08-31 00:37
This bug has already been fixed [here](https://github.com/hashicorp/terraform/pull/26028) and will be included in v13.2

**Comment by andrei-dascalu** [comment] 2020-08-31 12:29
I don't mean to be rude, but I wonder if there's a TTL for 0.13.2? The impact of the issue is quite painful.

**Comment by jbardin** [comment] 2020-08-31 21:43
Closing as duplicate of #26011

**Closed by jbardin** 2020-08-31 21:43 UTC
Labels: bug, new
