### ISSUE TITLE
Terraform times out since 0.7.13

### ISSUE THREAD

**Issue by jamtur01** [hashicorp/terraform#10354] opened 2016-11-24 21:28 UTC
### Terraform Version

0.7.13

### Affected Resource(s)

All

### Terraform Configuration Files

Any

### Debug Output

Any plan or apply since I upgraded to 0.7.13.

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error refreshing state: 1 error(s) occurred:

* RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on 192.168.1.1:53: read udp 192.168.1.140:49703->192.168.1.1:53: i/o timeout
```

I've tried with and without `skip_credentials_validation`.

`sts.amazonaws.com` resolves fine:

```
nslookup sts.amazonaws.com               5s
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	sts.amazonaws.com
Address: 205.251.243.54
```

I've also used the AWS CLI tool to create instances. I presume its something wrong with my local DNS but I can't see exactly what and the error is suitably cryptic and I presume bubbling up from the AWS GO library.

### Expected Behavior

A plan.

### Actual Behavior

Time out.

### Steps to Reproduce

`terraform plan`

I see:

https://github.com/aws/amazon-ecs-cli/issues/76
https://github.com/hashicorp/terraform/issues/3638
https://github.com/hashicorp/terraform/issues/6535

**Comment by oli-g** [comment] 2016-11-25 10:46
I'm getting the same issue:

```
* RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on 83.103.25.250:53: dial udp 83.103.25.250:53: i/o timeout
2016/11/25 11:36:14 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
```

I never got this before today. Strange enough, I'm still using version `0.7.1`. Inside the full Terraform log I have lines like this too:

```
2016/11/25 11:32:50 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=SOME-SIGNATURE&version=0.7.1: dial tcp: lookup checkpoint-api.hashicorp.com on 83.103.25.250:53: dial udp 83.103.25.250:53: i/o timeout
```

Any clue?

**Comment by mitchellh** [comment] 2016-11-25 20:18
Huh, we always use the latest version to release the latest version and our build scripts use AWS so this means that Terraform was working for our build process... I also can't reproduce this locally, in a VM, or on a remote EC2 instance with a standard AWS set of Terraform files.

Go doesn't use the standard OS X DNS stack so it might be a transient Go issue, but I'm really not sure... without a reproduction I don't think we can fix this.

If you downgrade to 0.7.12 it works suddenly? We didn't change Go versions for 0.7.13 so that is very odd.

**Comment by jamtur01** [comment] 2016-11-25 20:43
It's not 0.7.13. Same error on 0.7.12 and .11 too.

**Comment by CpuID** [comment] 2016-11-25 22:05
The only time I have ever seen errors like this (in other systems written in Go) is when the configured DNS resolver/s have been unavailable, for whatever reason.

Try take a packet capture when it occurs of port 53 and see if it shows any signs of the root cause...

**Comment by mitchellh** [comment] 2016-11-25 23:31
@jamtur01 That's relieving (for sanity reasons on my end, at least). I'm going to close this because I have a strong feelings its unrelated to Terraform itself... but correct me if I'm wrong. If you find something we can update the docs with too let us know and we'll do so.

**Closed by mitchellh** 2016-11-25 23:31 UTC
Labels: bug, core, waiting-response

**Comment by jamtur01** [comment] 2016-11-25 23:52
Sure. I was leaning to DNS too. I must admit though it's a very cryptic error. Is it DNS? Terraform? AWS? It'd be great to capture this somehow and perhaps suggest some idea. I was left scratching my head.

**Comment by mitchellh** [comment] 2016-11-25 23:53
@jamtur01 I agree though its likely that we are far too high level to actually detect. :(

**Comment by jacquescrocker** [comment] 2018-09-26 23:32
Sorry to bring this back up, but I'm seeing this issue right now on terraform 0.11.7

```
> terraform init
Initializing modules...
- module.apps

Initializing the backend...

Error configuring the backend "s3": RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on 10.11.12.109:53: write udp 10.34.16.134:51857->10.11.12.109:53: write: host is down

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

Does anyone have a resolution or workaround?
