### ISSUE TITLE
crash: EvalApplyPre for aws_autoscaling_group.default called with nil Change

### ISSUE THREAD

**Issue by kevinburkemeter** [hashicorp/terraform#26885] opened 2020-11-11 21:21 UTC
### Terraform Version

```
Terraform v0.13.5
```

Is this enough info to reproduce the error? Do you have a way for me to share crash logs with you privately? I hit ctrl+c to stop the apply operation while it was running.

```
panic: close of nil channel
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5:
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: goroutine 819 [running]:
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).stop(0xc0017d9640)
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:201 +0x71
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).Stop(0xc0017d9640, 0x7745c00, 0xc0011ee5d0, 0xc0011ee600, 0xc0017d9640, 0xc0011ee5d0, 0xc00066eba0)
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:215 +0xa1
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_Stop_Handler(0x69e6e00, 0xc0017d9640, 0x7745c00, 0xc0011ee5d0, 0xc0011f2060, 0x0, 0x7745c00, 0xc0011ee5d0, 0x0, 0x0)
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:434 +0x217
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00102c700, 0x7769e40, 0xc000f9cf00, 0xc000774b00, 0xc000afa1e0, 0xad9cb48, 0x0, 0x0, 0x0)
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: google.golang.org/grpc.(*Server).handleStream(0xc00102c700, 0x7769e40, 0xc000f9cf00, 0xc000774b00, 0x0)
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f54ba0, 0xc00102c700, 0x7769e40, 0xc000f9cf00, 0xc000774b00)
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-11T21:13:13.119Z [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x204
2020-11-11T21:13:13.124Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

```
goroutine 15823 [running]:
github.com/hashicorp/terraform/terraform.(*EvalApplyPre).Eval(0xc0007c5d40, 0x392f300, 0xc002150750, 0x1, 0x1, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval_apply.go:350 +0x551
github.com/hashicorp/terraform/terraform.EvalRaw(0x38848e0, 0xc0007c5d40, 0x392f300, 0xc002150750, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0023866e0, 0x392f300, 0xc002150750, 0x1, 0x1, 0x9, 0xc0013bd4c0)
	github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x3884d20, 0xc0023866e0, 0x392f300, 0xc002150750, 0x2ebb180, 0x4ba2761, 0x2e1adc0, 0xc00499a410)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.Eval(0x3884d20, 0xc0023866e0, 0x392f300, 0xc002150750, 0xc0023866e0, 0x3884d20, 0xc0023866e0, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x325e1e0, 0xc00162ef20, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/graph.go:73 +0xc77
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0010855c0, 0x325e1e0, 0xc00162ef20, 0xc0016ea9c0)
	github.com/hashicorp/terraform/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	github.com/hashicorp/terraform/dag/walk.go:309 +0x11d7
```

**Comment by jbardin** [comment] 2020-11-11 22:25
Hi @kevinburkemeter,

Is this something you can reproduce? I don't think the logs will help much here, but you could look for any warnings or errors to be sure.  The first panic is in the provider, but coming from the `github.com/hashicorp/terraform-plugin-go` package. I'm not sure what that's being used for here -- I didn't think it was in any production providers yet. 

The second panic is in core, but I'm not sure how we got a `nil` there. The 0.14 and master branches have refactored that code a bit, and may have caught the issue in the process. Is it possible to try this again with a development version of terraform?

Thanks

**Comment by kevinburkemeter** [comment] 2020-11-11 22:31
I just stopped another build by hitting control+c and did not trigger the error.

**Comment by jbardin** [comment] 2020-11-11 22:58
My guess here is that the provider panicked at a point where terraform wasn't expecting, and we got into an unusual state. Since it doesn't look like we can hit that situation in core any longer in the newer branches, I'm going to close this out on our side.

If this wasn't expected from the provider side, I would report the crash in their repo since that seems to be what started the chain of events.

Thanks!

**Closed by jbardin** 2020-11-11 22:58 UTC
Labels: bug, waiting for reproduction
