### ISSUE TITLE
No data source type named "scaffolding_example" was found in the provider

### ISSUE THREAD

**Issue by freakinhippie** [hashicorp/terraform#34016] opened 2023-10-06 23:59 UTC
### Terraform Version

```shell
Terraform v1.6.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    scaffolding = {
      source = "hashicorp.com/edu/hashicups-pf"
    }
  }
}

data "scaffolding_example" "example" {
  configurable_attribute = "some-value"
}
```

### Debug Output

https://gist.github.com/freakinhippie/f3339ae79b7de7795d91eb72f47ba9a1

### Expected Behavior

The plan should succeed.

### Actual Behavior

╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp.com/edu/hashicups-pf in ../../..
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
╷
│ Error: Data Source Type Not Found
│ 
│   with data.scaffolding_example.example,
│   on data-source.tf line 1, in data "scaffolding_example" "example":
│    1: data "scaffolding_example" "example" {
│ 
│ No data source type named "scaffolding_example" was found in the provider.
╵

### Steps to Reproduce

These steps assume a working `go` installation, and the last step relies on `jq`.

1. `git clone https://github.com/hashicorp/terraform-provider-scaffolding-framework`
2. `mv terraform-provider-scaffolding-framework terraform-provider-hashicups-pf`
3. `cd terraform-provider-hashicups-pf`
4. `go mod tidy`
5. `go build -o terraform-provider-hashicups-pf`
6. `cd examples/data-sources/scaffolding_example/`
7. `echo -e 'provider_installation {\n  dev_overrides {\n    "hashicorp.com/edu/hashicups-pf" = "../../../"\n  }\n  direct {}\n}' | tee development.tfrc`
8. `echo -e 'terraform {\n  required_providers {\n    scaffolding = {\n      source = "hashicorp.com/edu/hashicups-pf"\n    }\n  }\n}' | tee terraform.tf`
9. `export TF_CLI_CONFIG_FILE=development.tfrc`
10. `terraform version`
11. `terraform plan`
12. `terraform providers schema -json | jq '.provider_schemas | to_entries[] | .value.data_source_schemas | keys'`

### Additional Context

The same reproduction steps work properly with terraform v1.5.7.

```sh
> ~/bin/terraform-1.5.7 version
Terraform v1.5.7
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.6.0. You can update by downloading from https://www.terraform.io/downloads.html

> ~/bin/terraform-1.5.7 plan
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp.com/edu/hashicups-pf in ../../..
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
data.scaffolding_example.example: Reading...
data.scaffolding_example.example: Read complete after 0s [id=example-id]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

**Comment by Golvanig** [comment] 2023-10-07 08:20
I do have the same issue with a "provider" (developed with Terraform Plugin Framework) which works with 1.5.7 and cannot find my resources with 1.6

**Comment by dhohengassner** [comment] 2023-10-09 08:02
guess this is a duplicate of https://github.com/hashicorp/terraform/issues/33990

which is continued here: https://github.com/hashicorp/terraform-plugin-framework/issues/853

**Closed** 2023-10-09 14:09 UTC
Labels: bug, new
