### ISSUE TITLE
Terraform show 0.7 panic on lists

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#7080] opened 2016-06-08 16:13 UTC
Hi there,

### Terraform Version
Terraform v0.7.0-rc1 (301da85f30239e87b30db254a25706a6d41c2522)

### Affected Resource(s)
- core

### Terraform Configuration Files
```hcl
resource "aws_instance" "web" {
  count = "2"

  ami           = "ami-db24d8b6"
  instance_type = "t2.micro"

  subnet_id              = "subnet-..."
  vpc_security_group_ids = ["sg-..."]
}

output "public_ip" {
  value = ["${aws_instance.web.*.public_ip}"]
}

output "public_dns" {
  value = ["${aws_instance.web.*.public_dns}"]
}
```

### Debug Output
https://gist.github.com/sethvargo/79b1ec372036d073d29e587f1616a839

### Panic Output
Interestingly, it says panic, but doesn't actually panic.

### Expected Behavior
I should have seen list output at the end of `terraform show`.

### Actual Behavior
I saw a panic message.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform show`

### Important Factoids
- Using output that is a slice

/cc @jen20

**Comment by radeksimko** [comment] 2016-06-08 17:26
I just verified using the config you provided above that this is already fixed in `master`, closing as a duplicate of https://github.com/hashicorp/terraform/issues/6931 which was fixed via https://github.com/hashicorp/terraform/pull/6958 😉

**Closed by radeksimko** 2016-06-08 17:26 UTC
Labels: bug, core
