### ISSUE TITLE
Setting s3 backend objects with metadata

### ISSUE THREAD

**Issue by assafadar** [hashicorp/terraform#26599] opened 2020-10-15 17:20 UTC
### Current Terraform Version
0.12.18

```
...
```

### Use-cases
I would like to set a key in the .tfstate file metadata using s3 backend to point our rather the deployment should be destroyed or not.

### Attempted Solutions
Setting the object metadata using s3api after deployment is completed erases the file due to the fact it's a new version of the s3 object.

### Proposal
Adding key=value pairs into s3 backend .tfstate file for more flexible resource management.

**Comment by jbardin** [comment] 2020-10-15 23:02
appears to be a duplicate of #26600

**Closed by jbardin** 2020-10-15 23:02 UTC
Labels: enhancement, new
