### ISSUE TITLE
rancher_environment does not create kubernetes environment

### ISSUE THREAD

**Issue by tombmurphy** [hashicorp/terraform#13081] opened 2017-03-27 02:22 UTC
Hi,

I have a bug to report.

### Terraform Version
0.9.1

### Affected Resource(s)
- rancher_environment

### Expected Behavior
Create a new environment using "kubernetes" orchestration value. 
The expected behaviour in Rancher is to see the new environment with kubernetes scheduler.

### Actual Behavior
Instead it creates a cattle environment.

### Steps to reproduce it
Using latest rancher/server v1.5.2 
Or try using https://try.rancher.com/ (which is v1.5.3-try2)

**Comment by johnrengelman** [comment] 2017-03-30 02:40
Duplicate of https://github.com/hashicorp/terraform/issues/11392

**Closed** 2017-06-13 20:15 UTC
Labels: bug, provider/rancher
