### ISSUE TITLE
Plan or Show commands are stalling

### ISSUE THREAD

**Issue by dschmidtadv** [hashicorp/terraform#27029] opened 2020-11-25 14:10 UTC
Executing plan or show commands are stalling. The process keeps consuming CPU, but never progresses or errors out. I have tried this on two different computers, so it might be network related. How can I collect further information to troubleshoot. I am on OSX.

```
2020/11/24 15:53:07 [INFO] Terraform version: 0.13.5  
2020/11/24 15:53:07 [INFO] Go runtime version: go1.14.7
2020/11/24 15:53:07 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}
2020/11/24 15:53:07 [DEBUG] Attempting to open CLI config file: /Users/dschmidt/.terraformrc
2020/11/24 15:53:07 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/24 15:53:07 [DEBUG] checking for credentials in "/Users/dschmidt/.terraform.d/plugins"
2020/11/24 15:53:07 [DEBUG] checking for credentials in "/Users/dschmidt/.terraform.d/plugins/darwin_amd64"
2020/11/24 15:53:07 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/24 15:53:07 [DEBUG] will search for provider plugins in /Users/dschmidt/.terraform.d/plugins
2020/11/24 15:53:07 [TRACE] getproviders.SearchLocalDirectory: /Users/dschmidt/.terraform.d/plugins is a symlink to /Users/dschmidt/.terraform.d/plugins
2020/11/24 15:53:07 [DEBUG] ignoring non-existing provider search directory /Users/dschmidt/Library/Application Support/io.terraform/plugins
2020/11/24 15:53:07 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/24 15:53:07 [INFO] CLI command args: []string{"plan"}
2020/11/24 15:53:46 [INFO] Terraform version: 0.13.5  
2020/11/24 15:53:46 [INFO] Go runtime version: go1.14.7
2020/11/24 15:53:46 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}
2020/11/24 15:53:46 [DEBUG] Attempting to open CLI config file: /Users/dschmidt/.terraformrc
2020/11/24 15:53:46 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/24 15:53:46 [DEBUG] checking for credentials in "/Users/dschmidt/.terraform.d/plugins"
2020/11/24 15:53:46 [DEBUG] checking for credentials in "/Users/dschmidt/.terraform.d/plugins/darwin_amd64"
2020/11/24 15:53:46 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/24 15:53:46 [DEBUG] will search for provider plugins in /Users/dschmidt/.terraform.d/plugins
2020/11/24 15:53:46 [TRACE] getproviders.SearchLocalDirectory: /Users/dschmidt/.terraform.d/plugins is a symlink to /Users/dschmidt/.terraform.d/plugins
2020/11/24 15:53:46 [DEBUG] ignoring non-existing provider search directory /Users/dschmidt/Library/Application Support/io.terraform/plugins
2020/11/24 15:53:46 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/24 15:53:46 [INFO] CLI command args: []string{"plan"}
2020/11/24 15:54:50 [INFO] Terraform version: 0.13.5  
2020/11/24 15:54:50 [INFO] Go runtime version: go1.14.7
2020/11/24 15:54:50 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}
2020/11/24 15:54:50 [DEBUG] Attempting to open CLI config file: /Users/dschmidt/.terraformrc
2020/11/24 15:54:50 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/24 15:54:50 [DEBUG] checking for credentials in "/Users/dschmidt/.terraform.d/plugins"
2020/11/24 15:54:50 [DEBUG] checking for credentials in "/Users/dschmidt/.terraform.d/plugins/darwin_amd64"
2020/11/24 15:54:50 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/24 15:54:50 [DEBUG] will search for provider plugins in /Users/dschmidt/.terraform.d/plugins
2020/11/24 15:54:50 [TRACE] getproviders.SearchLocalDirectory: /Users/dschmidt/.terraform.d/plugins is a symlink to /Users/dschmidt/.terraform.d/plugins
2020/11/24 15:54:50 [DEBUG] ignoring non-existing provider search directory /Users/dschmidt/Library/Application Support/io.terraform/plugins
2020/11/24 15:54:50 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
```

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by RyPeck** [comment] 2020-11-25 18:42
@dschmidtadv are you running against the `us-east-1` AWS environment by any chance?

**Comment by dschmidtadv** [comment] 2020-11-30 14:58
@RyPeck No, I am not using AWS directly, I am using https://www.checklyhq.com/docs/integrations/terraform/

**Comment by pselle** [comment] 2020-12-02 23:02
Hi @dschmidtadv,
to better understand the issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - a simplified config to help us reproduce the issue
 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Filling out the issue template gives us more information so that we might be able to reproduce your issue, and thus determine if it is a bug in Terraform and then diagnose+fix as applicable.

**Comment by mildwonkey** [comment] 2021-04-30 15:56
I'm going to close this, since there hasn't been a response, but if you are still experiencing a problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by mildwonkey** 2021-04-30 15:56 UTC
Labels: bug, v0.13, waiting for reproduction, waiting-response
