### ISSUE TITLE
Error: creating Postgresql Flexible Server

### ISSUE THREAD

**Issue by manutvm** [hashicorp/terraform#28878] opened 2021-06-04 10:11 UTC
Hi Team,

We tried to implement the Azure Postgres Flexible Server using terraform resource "azurerm_postgresql_flexible_server". 
```terraform
module.postgres.azurerm_postgresql_flexible_server.postgresql: Creating...
╷
│ Error: creating Postgresql Flexible Server "postgresqldevesg" (Resource Group "ResourceGroupDevESG"): postgresqlflexibleservers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="MissingRequiredParameter" Message="Parameter '' must be specified. This parameter cannot be NULL or empty."
│ 
│   on ../../Modules/FlexiblePostgreSql/main.tf line 20, in resource "azurerm_postgresql_flexible_server" "postgresql":
│   20: resource "azurerm_postgresql_flexible_server" "postgresql" {
│ 
```
I have given all the attributes to the terraform scripts for Azure Flexible Postgres Server. Following are the configurations,
```
Terraform will perform the following actions:

  # module.postgres.azurerm_postgresql_flexible_server.postgresql will be created
  + resource "azurerm_postgresql_flexible_server" "postgresql" {
      + administrator_login           = "psqlfrpadmin"
      + administrator_password        = (sensitive value)
      + backup_retention_days         = 7
      + cmk_enabled                   = (known after apply)
      + delegated_subnet_id           = "/subscriptions/*******/resourceGroups/ResourceGroupNetworkFRP/providers/Microsoft.Network/virtualNetworks/VirtualNetworkFRP/subnets/SubnetFlexibleDBFRP"
      + fqdn                          = (known after apply)
      + id                            = (known after apply)
      + location                      = "westeurope"
      + name                          = "postgresqldevesg"
      + public_network_access_enabled = (known after apply)
      + resource_group_name           = "ResourceGroupDevESG"
      + sku_name                      = "B_Standard_B1ms"
      + storage_mb                    = 32768
      + tags                          = {
          + "cluster" = "Dev"
          + "project" = "ESG"
        }
      + version                       = "12"
      + zone                          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
Following are the terraform provider details,
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.62.0"
    }
    random = {
      source = "hashicorp/random"
      version = "=3.1.0"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "=2.2.0"
    }
  }
}
```
The error message did not says exactly which parameter is missing,
```
Error: Code="MissingRequiredParameter" Message="Parameter '' must be specified. This parameter cannot be NULL or empty."
```
Can someone please help me in resolving the issue.

Regards,
Manoj Kumar R

**Comment by charlspjohn** [comment] 2021-06-04 10:21
Same issue with me as well :(
The terraform apply was working well with azurerm version 2.60.0 until a week ago..

**Comment by t3mi** [comment] 2021-06-04 10:38
Duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/12053

**Comment by jbardin** [comment] 2021-06-04 12:52
This appears to be an issue with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Closed by jbardin** 2021-06-04 12:52 UTC
