### ISSUE TITLE
To allow some limited use of variables in module sources.

### ISSUE THREAD

**Issue by gareth-e** [hashicorp/terraform#34853] opened 2024-03-15 12:16 UTC
### Terraform Version

```shell
1.7.5
```

### Use Cases

I know this type of question has been raised and responded to a few times in the past - for example [here](https://github.com/hashicorp/terraform/issues/30441) and [here](https://discuss.hashicorp.com/t/module-source-attribute/5739). There are many use cases for this.

But here I have a slightly different angle...

Essentially our case (not unusual) is we have around 50 applications (3 or 4 environments each) which all use a standard set of source modules for creating things like AWS VPCs, RDS instances, S3 buckets, etc. Occasionally we modify the source modules but the challenge is how to safely and gradually roll these changes out?
- If we create all these environments from a few (e.g. `for_each`d) module blocks then we can only update them all at once (since they all have the same hard-coded constant source path) 
- If we have separate module blocks for each application/environment then we have a few hundred to update.
- We could aim for something in-between these two, but it's still a lot of repetition.

This I'm guessing is what others have experienced - hence the past questions on this.

The proposal below I hope is more achievable than a general / open variable-driven source path.

### Attempted Solutions

- Having to manage all the resources separately - time-consuming, not DRY, human error, etc.
- Generating the verbose HCL using a script.
- Creating a module that "calls a sub-module of itself" from a version variable. This kinda works, but changes are difficult. And it's a little confusing to read.

### Proposal

I totally get the challenge that @apparentlymart describes [here](https://github.com/hashicorp/terraform/issues/30441) around dependencies etc.
The proposal though is this...
**Would it be feasible to allow variables to be used in sources (or versions) if those variable values were _known at "plan" time_**? I.e. would it be feasible to allow the "init" stage to evaluate these variables in the same way a "plan" does?
I totally get that if we tried something that resulted in this...
```terraform
source = "github.com/.........ref=(known after apply)"
```
...then that's probably **_not_** a route to go down. The idea of sources being retrieved as an apply runs sounds impractical and risky. So that's not the idea here.

However, if we could do:
```terraform
module "example" {
  source = "github.com/.........?ref=${var.source_version}"
...
}
```
...where `source_version` value could be determined at "plan" time (**and was extended to "init" time?**) - then that may be an option? The dependencies could be calculated in advance still.

Does that sound feasible?

### References

This issue is related: https://github.com/hashicorp/terraform/issues/30441
Though this request here is for something more targeted (i.e. to allow a variable here on condition that its value is known **_before_** an apply).

**Comment by jbardin** [comment] 2024-03-15 12:44
Hi @gareth-e,

Thanks for filing the issue. Once Terraform has reached the plan phase, it was far too late to resolve the source of the configuration. Everything must be known during `init` in order to resolve all dependencies.

What you're asking for is basically a templating or macro system. This amounts to filling in static value just as if you had typed them in the configuration yourself. While technically possible, it can create a level of non-determinism in the configuration which makes it much harder to deal with in the long term (there's a reason a lot of programming languages don't support macros). It also makes it unclear how one would test and maintain child modules which could be completely swapped out for other code based on init-time parameters.

This this type of enhancement however, you can follow issue #32041

Thanks!

**Comment by jbardin** [comment] 2024-03-15 12:44
Duplicate of #32041

**Closed by jbardin** 2024-03-15 12:44 UTC
Labels: enhancement, new

**Comment by gareth-e** [comment] 2024-03-15 13:51
Hi @jbardin 
Thanks for the quick reply.
One quick follow-up question... where you mentioned...
> _Everything must be known during init in order to resolve all dependencies._

Is there a reason why the `init` stage could not evaluate variables? Not the "known after apply" type, but anything defined locally in TF_VARS, tfenv or a variable default for example?

That was my line of thinking really - not to resolve the source at `plan` stage but resolve at `init` stage, but by evaluating and using any known variables...?

For example, if I had a file like this:
```terraform
variable "source_version" { 
    type = string
    default = "main"
}

module "example" {
  source = "github.com/.........?ref=${var.source_version}"
...
}
```

Would it be feasible to enhance the `init` stage so it could work with something like that?

**Comment by jbardin** [comment] 2024-03-15 16:03
If the value must be defined during init, then it isn't really a variable, and is acting like a constant regardless of the name. This is what the linked issue is describing. Pretending a variable might be static in some contexts to make it "just work" would require changing how variables are handled internally, since they are treated as is they could always change on any invocation or be unknown. Because you are effectively rewriting the configuration on the proposed `init`, there would need to be a new mechanism to ensure that all other actions taken use the same value otherwise you cannot be sure the configuration is valid, or even meets basic constraints. The change in child modules may have different providers, provider versions, Terraform version, input/output names and types, etc. The consequences of a mis-use of this feature may result in subtle changes that may not be obvious to the operator.
