### ISSUE TITLE
file provisioner requires full path for files, but not for directories

### ISSUE THREAD

**Issue by dev-fd** [hashicorp/terraform#20406] opened 2019-02-21 00:52 UTC
### Terraform Version

```
Terraform v0.11.11
+ provider.null v2.0.0
+ provider.oci v3.15.0
```

### Terraform Configuration Files

```hcl
resource "null_resource" "filecopy" {
  depends_on = ["oci_core_instance.FalconDeployInstance"]
    
  provisioner "file" {
    source      = "./userdata/apache-tomcat-8.5.38.tar.gz"
    destination = "/tmp"
    
    connection {
      agent = true
      timeout = "1m"
      type = "ssh"
      user = "opc"
      host = "${oci_core_instance.FalconDeployInstance.public_ip}"
      private_key = "${var.ssh_private_key}"
    }  
  }
}
```

### Debug Output
```
2019/02/20 19:24:07 [DEBUG] apply: null_resource.filecopy: executing Apply
2019/02/20 19:24:07 [TRACE] root: eval: *terraform.EvalWriteState
2019/02/20 19:24:07 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019-02-20T19:24:07.952-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:07 [DEBUG] connecting to TCP connection for SSH
2019-02-20T19:24:07.973-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:07 [DEBUG] handshaking with SSH
2019-02-20T19:24:08.168-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] Telling SSH config to forward to agent
2019-02-20T19:24:08.168-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] Setting up a session to request agent forwarding
2019-02-20T19:24:08.168-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] opening new ssh session
2019-02-20T19:24:08.289-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [INFO] agent forwarding enabled
2019-02-20T19:24:08.289-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] opening new ssh session
2019-02-20T19:24:08.330-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] Starting remote scp process:  scp -vt /
2019-02-20T19:24:08.358-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] Started SCP session, beginning transfers...
2019-02-20T19:24:08.358-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] Copying input data into temporary file so we can read the length
2019-02-20T19:24:08.402-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] Beginning file upload...
2019-02-20T19:24:08.562-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] SCP session complete, closing stdin pipe.
2019-02-20T19:24:08.562-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [DEBUG] Waiting for SSH session to complete.
2019-02-20T19:24:08.562-0500 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/20 19:24:08 [ERROR] Process exited with status 1
2019/02/20 19:24:08 [ERROR] root: eval: *terraform.EvalApplyProvisioners, err: Upload failed: Process exited with status 1
2019/02/20 19:24:08 [ERROR] root: eval: *terraform.EvalSequence, err: Upload failed: Process exited with status 1
2019/02/20 19:24:08 [TRACE] [walkApply] Exiting eval tree: null_resource.filecopy
2019/02/20 19:24:08 [TRACE] dag/walk: upstream errored, not walking "provider.null (close)"
2019/02/20 19:24:08 [TRACE] dag/walk: upstream errored, not walking "provisioner.file (close)"
2019/02/20 19:24:08 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/02/20 19:24:08 [TRACE] dag/walk: upstream errored, not walking "root"
2019/02/20 19:24:08 [TRACE] Preserving existing state lineage "101fbd5b-a78a-a4b8-2739-496d16d77c87"
```

### Expected Behavior
```
File copied to new instance
```

### Actual Behavior
```
Terraform will perform the following actions:

-/+ null_resource.filecopy (tainted) (new resource required)
      id: "8018089078787334223" => <computed> (forces new resource)


Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.filecopy: Destroying... (ID: 8018089078787334223)
null_resource.filecopy: Destruction complete after 0s
null_resource.filecopy: Creating...
null_resource.filecopy: Provisioning with 'file'...

Error: Error applying plan:

1 error(s) occurred:

* null_resource.filecopy: Upload failed: Process exited with status 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
```
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
```

**Comment by dev-fd** [comment] 2019-02-21 16:34
Anyone seen this behavior? Is there a workaround we can use to avoid this error?

**Comment by dev-fd** [comment] 2019-02-21 18:34
We are able to work around with local-exec to copy the file. provisioner "file" does not work though.

**Comment by jbardin** [comment] 2019-02-21 18:42
Hi @dev-fd,

Sorry you're having an issue with this. Your destination path is missing the filename. So the issue is that the remote scp process is failing to write the file as `/tmp`. 

I'm not sure what `scp` implementation is on that system, but it's not reporting the error in the usual manner. I'll submit a PR to try and catch that.

A small tip as well, you don't need `depends_one` here, since you're already referencing `oci_core_instance.FalconDeployInstance` in the resource configuration.

**Comment by dev-fd** [comment] 2019-02-21 19:01
Thank you @jbardin 

The doc is slightly misleading. Now i read that it works for folders but for files we have to explicitly give the name.
https://www.terraform.io/docs/provisioners/file.html

# Copies the configs.d folder to /etc/configs.d
  provisioner "file" {
    source      = "conf/configs.d"
    destination = "/etc"
  }

**Comment by jbardin** [comment] 2019-02-21 19:11
Thanks @dev-fd, I didn't realize it the communicator would allow that for directories (which is sort of an artifact of the scp protocol itself).

I'll reopen this to unify the behavior or at least document the issue.

**Comment by dev-fd** [comment] 2019-02-21 19:31
Thank you @jbardin 

Appreciate the effort!

**Comment by laurapacilio** [comment] 2021-07-08 13:24
Hi all! I'm going to close this out, as it's been a few years since it's been filed and I imagine things have changed quite a bit. But, please feel free to reopen if it's still needed!

**Closed by laurapacilio** 2021-07-08 13:24 UTC
Labels: documentation, enhancement, provisioner/file
