### ISSUE TITLE
Confusing error message when passing module input variable of incorrect type

### ISSUE THREAD

**Issue by Timboo89** [hashicorp/terraform#27019] opened 2020-11-24 12:16 UTC
I am facing the issue, that once I use a for loop in a locals block, that is referring to variables, I cannot pass it to any module any more. I know this sentence is hard to understand, but I can't find a better way to describe it. I simplified my code as much as possible to produce some speaking test data.

### Terraform Version

```
Terraform v0.13.5
```

#### main.tf 
```terraform
variable "backend_id" {
  type = string
}

variable "frontend_id" {
  type = string
  default = ""
}

variable "some_cidrs" {
  type = list(string)
}

locals {
  static_routes_to_frontend_list = [
    "0.0.0.0/0"
  ]
  static_routes_to_frontend = {
    for cidr in local.static_routes_to_frontend_list : cidr => var.frontend_id != "" ? var.frontend_id : var.backend_id
  }

  static_routes_to_backend_list = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16"
  ]
  static_routes_to_backend = {
    for cidr in local.static_routes_to_backend_list : cidr => var.backend_id
  }

  static_routes = merge(local.static_routes_to_frontend, local.static_routes_to_backend)

  wan_static_routes_helper = {
    for cidr in var.some_cidrs :
    (cidr) => var.backend_id
  }

  route_tables_static_routes = {
    "isolated" = local.static_routes
    "wan"      = local.wan_static_routes_helper
  }


  # The following locals should be computed by a module, so I don't need to copy it all the time
  map_flatten_combine_keys_and_keep_in_inner_map_helper = flatten([
    for key1, values1 in local.route_tables_static_routes :
    [
      for key2, values2 in values1 :
      {
        format("%s%s%s", key1, "-", key2) = {
          "class" = key1,
          "account_alias_vpc_name" = key2,
          "value" = values2
        }
      }
    ]
  ])

  map_flatten_combine_keys_and_keep_in_inner_map = {
      for item in local.map_flatten_combine_keys_and_keep_in_inner_map_helper :
      keys(item)[0] => values(item)[0]
  }
}

module "map_flatten_combine_keys_and_keep_in_inner_map" {
  source      = "./modules/map_flatten_combine_keys_and_keep_in_inner_map"
  map_of_maps    = local.route_tables_static_routes
  outer_key_name = "class"
  inner_key_name = "account_alias_vpc_name"
  value_key_name = "value"
}

output "flattened_map_module" {
    value = module.map_flatten_combine_keys_and_keep_in_inner_map.flattened_map
}

output "flattened_map_locals" {
  value = local.map_flatten_combine_keys_and_keep_in_inner_map
}


```

#### vars.tfvars

```terraform
backend_id = "backend-id"

landingszone_bala_cidr = ["10.0.0.0/8"]
```

#### modules/map_flatten_combine_keys_and_keep_in_inner_map
```terraform
terraform {
  required_version = ">= 0.12.6, < 0.14"

  required_providers {
    aws = ">= 2.57"
  }
}

variable "map_of_maps" {
  type = map(any)
  description = "This map of maps to flatten combining keys. For example view README.md"

  validation {
    condition     = can(values(var.map_of_maps)) && (length(values(var.map_of_maps)) == 0 || can(values(values(var.map_of_maps)[0])))
    error_message = "Please provide a map of maps. Also fine is an empty map and a map of empty maps."
  }
}

variable "seperator" {
  type = string
  description = "The seperator between both keys. NewKey=<key-outer><seperator><key-inner>"
  default = "-"
}

variable "outer_key_name" {
  type = string
  description = "Name of outer key in generated map. For example view README.md"
  default = "outerkey"
}

variable "inner_key_name" {
  type = string
  description = "Name of inner key in generated map. For example view README.md"
  default = "innerkey"
}

variable "value_key_name" {
  type = string
  description = "Name of value in generated map. For example view README.md"
  default = "value"
}

locals {
    flattened = flatten([
        for key1, values1 in var.map_of_maps :
        [
            for key2, values2 in values1 :
            {
                format("%s%s%s", key1, var.seperator, key2) = {
                    (var.outer_key_name) = key1,
                    (var.inner_key_name) = key2,
                    (var.value_key_name) = values2
                }
            }
        ]
    ])

    flattened_map = {
        for item in local.flattened :
        keys(item)[0] => values(item)[0]
    }
}

output "flattened_map" {
    value = local.flattened_map
}


```

### Debug Output

https://gist.github.com/Timboo89/171aaefc9e8299c4568d251ed52c45d9

### Crash Output

```bash
Error: Invalid value for module argument

  on main.tf line 67, in module "map_flatten_combine_keys_and_keep_in_inner_map":
  67:   map_of_maps    = local.route_tables_static_routes

The given value is not suitable for child module variable "map_of_maps"
defined at
.terraform/modules/map_flatten_combine_keys_and_keep_in_inner_map/variables.tf:1,1-23:
object is required.
```

### Expected Behavior

```bash
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

flattened_map_locals = {
  "isolated-0.0.0.0/0" = {
    "account_alias_vpc_name" = "0.0.0.0/0"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "isolated-10.0.0.0/8" = {
    "account_alias_vpc_name" = "10.0.0.0/8"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "isolated-172.16.0.0/12" = {
    "account_alias_vpc_name" = "172.16.0.0/12"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "isolated-192.168.0.0/16" = {
    "account_alias_vpc_name" = "192.168.0.0/16"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "wan-10.0.0.0/8" = {
    "account_alias_vpc_name" = "10.0.0.0/8"
    "class" = "wan"
    "value" = "backend-id"
  }
}
flattened_map_module = {
  "isolated-0.0.0.0/0" = {
    "account_alias_vpc_name" = "0.0.0.0/0"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "isolated-10.0.0.0/8" = {
    "account_alias_vpc_name" = "10.0.0.0/8"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "isolated-172.16.0.0/12" = {
    "account_alias_vpc_name" = "172.16.0.0/12"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "isolated-192.168.0.0/16" = {
    "account_alias_vpc_name" = "192.168.0.0/16"
    "class" = "isolated"
    "value" = "backend-id"
  }
  "wan-10.0.0.0/8" = {
    "account_alias_vpc_name" = "10.0.0.0/8"
    "class" = "wan"
    "value" = "backend-id"
  }
}

```

### Actual Behavior

see crash output

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -var-file vars.tfvars`

### Additional Context

There are several ways of not getting this error:
1. Not use a module but copy the module internals into a plain tf file (what I already did in this test)
2. Not use variables in some of the for loops but static-locals 
3. Use one and the same VALUES for each item in `local.route_tables_static_routes` as soon as the "child"-maps differ from one another it's going to crash

### Make it runnable (for testing)
To get a running version, just comment out the module `map_flatten_combine_keys_and_keep_in_inner_map` and the corresponding output `flattened_map_module`.

### Code versions working
<details><summary>1. Without calling the module</summary>

```terraform
variable "backend_id" {
  type = string
}

variable "frontend_id" {
  type = string
  default = ""
}

variable "some_cidrs" {
  type = list(string)
}

locals {
  static_routes_to_frontend_list = [
    "0.0.0.0/0"
  ]
  static_routes_to_frontend = {
    for cidr in local.static_routes_to_frontend_list : cidr => var.frontend_id != "" ? var.frontend_id : var.backend_id
  }

  static_routes_to_backend_list = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16"
  ]
  static_routes_to_backend = {
    for cidr in local.static_routes_to_backend_list : cidr => var.backend_id
  }

  static_routes = merge(local.static_routes_to_frontend, local.static_routes_to_backend)

  wan_static_routes_helper = {
    for cidr in var.some_cidrs :
    (cidr) => var.backend_id
  }

  route_tables_static_routes = {
    "isolated" = local.static_routes
    "wan"      = local.wan_static_routes_helper
  }


  # The following locals should be computed by a module, so I don't need to copy it all the time
  map_flatten_combine_keys_and_keep_in_inner_map_helper = flatten([
    for key1, values1 in local.route_tables_static_routes :
    [
      for key2, values2 in values1 :
      {
        format("%s%s%s", key1, "-", key2) = {
          "class" = key1,
          "account_alias_vpc_name" = key2,
          "value" = values2
        }
      }
    ]
  ])

  map_flatten_combine_keys_and_keep_in_inner_map = {
      for item in local.map_flatten_combine_keys_and_keep_in_inner_map_helper :
      keys(item)[0] => values(item)[0]
  }
}

# module "map_flatten_combine_keys_and_keep_in_inner_map" {
#   source      = "/Users/tschmidt/Projects/telefonica/ccs/tf-modules/terraform-functions/modules/map_flatten_combine_keys_and_keep_in_inner_map"
#   map_of_maps    = local.route_tables_static_routes
#   outer_key_name = "class"
#   inner_key_name = "account_alias_vpc_name"
#   value_key_name = "value"
# }

# output "flattened_map_module" {
#     value = module.map_flatten_combine_keys_and_keep_in_inner_map.flattened_map
# }

output "flattened_map_locals" {
  value = local.map_flatten_combine_keys_and_keep_in_inner_map
}

```
</details>

<details><summary>2. using static-locals instead of variables</summary>

```terraform

locals {
  frontend_id = ""
  backend_id = "backend-id"
  some_cidrs = ["10.0.0.0/8"]

  static_routes_to_frontend_list = [
    "0.0.0.0/0"
  ]
  static_routes_to_frontend = {
    for cidr in local.static_routes_to_frontend_list : cidr => local.frontend_id != "" ? local.frontend_id : local.backend_id
  }

  static_routes_to_backend_list = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16"
  ]
  static_routes_to_backend = {
    for cidr in local.static_routes_to_backend_list : cidr => local.backend_id
  }

  static_routes = merge(local.static_routes_to_frontend, local.static_routes_to_backend)

  wan_static_routes_helper = {
    for cidr in local.some_cidrs :
    (cidr) => local.backend_id
  }

  route_tables_static_routes = {
    "isolated" = local.static_routes
    "wan"      = local.wan_static_routes_helper
  }


  # The following locals should be computed by a module, so I don't need to copy it all the time
  map_flatten_combine_keys_and_keep_in_inner_map_helper = flatten([
    for key1, values1 in local.route_tables_static_routes :
    [
      for key2, values2 in values1 :
      {
        format("%s%s%s", key1, "-", key2) = {
          "class" = key1,
          "account_alias_vpc_name" = key2,
          "value" = values2
        }
      }
    ]
  ])

  map_flatten_combine_keys_and_keep_in_inner_map = {
      for item in local.map_flatten_combine_keys_and_keep_in_inner_map_helper :
      keys(item)[0] => values(item)[0]
  }
}

module "map_flatten_combine_keys_and_keep_in_inner_map" {
  source      = "/Users/tschmidt/Projects/telefonica/ccs/tf-modules/terraform-functions/modules/map_flatten_combine_keys_and_keep_in_inner_map"
  map_of_maps    = local.route_tables_static_routes
  outer_key_name = "class"
  inner_key_name = "account_alias_vpc_name"
  value_key_name = "value"
}

output "flattened_map_module" {
    value = module.map_flatten_combine_keys_and_keep_in_inner_map.flattened_map
}

output "flattened_map_locals" {
  value = local.map_flatten_combine_keys_and_keep_in_inner_map
}

```
</details>

<details><summary>3. Using the exact same values for each item</summary>

```terraform {.line-numbers}
variable "backend_id" {
  type = string
}

variable "frontend_id" {
  type = string
  default = ""
}

variable "some_cidrs" {
  type = list(string)
}

locals {
  static_routes_to_frontend_list = [
    "0.0.0.0/0"
  ]
  static_routes_to_frontend = {
    for cidr in local.static_routes_to_frontend_list : cidr => var.frontend_id != "" ? var.frontend_id : var.backend_id
  }

  static_routes_to_backend_list = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16"
  ]
  static_routes_to_backend = {
    for cidr in local.static_routes_to_backend_list : cidr => var.backend_id
  }

  static_routes = merge(local.static_routes_to_frontend, local.static_routes_to_backend)

  wan_static_routes_helper = {
    for cidr in var.some_cidrs :
    (cidr) => var.backend_id
  }

  route_tables_static_routes = {
    "isolated" = local.static_routes
    "wan"      = local.static_routes
  }


  # The following locals should be computed by a module, so I don't need to copy it all the time
  map_flatten_combine_keys_and_keep_in_inner_map_helper = flatten([
    for key1, values1 in local.route_tables_static_routes :
    [
      for key2, values2 in values1 :
      {
        format("%s%s%s", key1, "-", key2) = {
          "class" = key1,
          "account_alias_vpc_name" = key2,
          "value" = values2
        }
      }
    ]
  ])

  map_flatten_combine_keys_and_keep_in_inner_map = {
      for item in local.map_flatten_combine_keys_and_keep_in_inner_map_helper :
      keys(item)[0] => values(item)[0]
  }
}

module "map_flatten_combine_keys_and_keep_in_inner_map" {
  source      = "/Users/tschmidt/Projects/telefonica/ccs/tf-modules/terraform-functions/modules/map_flatten_combine_keys_and_keep_in_inner_map"
  map_of_maps    = local.route_tables_static_routes
  outer_key_name = "class"
  inner_key_name = "account_alias_vpc_name"
  value_key_name = "value"
}

output "flattened_map_module" {
    value = module.map_flatten_combine_keys_and_keep_in_inner_map.flattened_map
}

output "flattened_map_locals" {
  value = local.map_flatten_combine_keys_and_keep_in_inner_map
}

```
</details>

**Comment by alisdair** [comment] 2020-11-24 15:12
Hi @Timboo89, thanks for reporting this.

I think the root problem here is probably the incorrect type definition on the `map_of_maps` input variable. The module logic will not work with a `map(any)`. Because it iterates over the values of the outer map, the broadest type it can cope with is a `map(map(any))`. Changing the type to `map(map(any))` fixes the issue for me. Please confirm if this works for you.

That said, the error diagnostic we're seeing is strange and definitely confusing. Part of the confusion is probably caused by the complexity of this example, so I'm going to try to find a reduced case. Once we understand better what's going on with the type unification here, hopefully there's a way we can improve this diagnostic.

**Comment by alisdair** [comment] 2020-11-24 15:54
Here's a reduced error case which I find easier to read:

main.tf:

```hcl
variable "cidrs" {
  type    = list(string)
  default = ["10.0.0.0/8"]
}

locals {
  static_routes = {
    "0.0.0.0/0" : true ? "foobar" : "foobar"
  }

  wan_routes = {
    for cidr in var.cidrs :
    cidr => "foobar"
  }

  routes = {
    "isolated" = local.static_routes
    "wan"      = local.wan_routes
  }
}

module "flatten" {
  source      = "./flatten"
  map_of_maps = local.routes
}

output "flatten" {
  value = module.flatten.flattened_map
}
```

flatten/main.tf:

```hcl
variable "map_of_maps" {
  type = map(any) # comment this out to fix the issue
  # type = map(map(any)) # optionally uncomment this
}

locals {
  flattened = merge(flatten([
    for key1, values1 in var.map_of_maps :
    [
      for key2, values2 in values1 :
      {
        "${key1}-${key2}" = values2
      }
    ]
  ])...)
}

output "flattened_map" {
  value = local.flattened
}
```

After `init`:

```shellsession
$ terraform-0.13.5 plan

Error: Invalid value for module argument

  on main.tf line 24, in module "flatten":
  24:   map_of_maps = local.routes

The given value is not suitable for child module variable "map_of_maps"
defined at flatten/main.tf:1,1-23: object is required.
```

After commenting out the module input variable type declaration (or using the `map(map(any))` type):

```shellsession
$ terraform-0.13.5 apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

flatten = {
  "isolated-0.0.0.0/0" = "foobar"
  "wan-10.0.0.0/8" = "foobar"
}
```

**Comment by Timboo89** [comment] 2020-11-24 23:29
This is very interesting.
@alisdair Can you explain to me, why making it a more distinct type works? Honestly I don't understand that.
The reason why I wanted to use `map(any)` with a custom validation instead of `map(map(any))` is that I cannot put an empty map `{}` into it then. But okay, a problem I can live with.

I love the simplification by using `...` by the way. Didn't understand how to use it until just now.

Thanks!!!

**Comment by alisdair** [comment] 2020-11-25 00:01
I don't have a real answer for you on why a narrower type fixes the issue, except that Terraform's type unification algorithm (which is responsible for these type conversions & validations) is doing a very complex job and there are probably some corner cases that it doesn't quite handle. At the moment I still think this is probably a bug, which is why I'm leaving this issue open. It's good to know there's at least a workaround!

As an aside, I believe that `{}` is a valid value for a variable of type `map(map(any))`—it certainly seems to work in my tests.

**Comment by mildwonkey** [comment] 2021-06-23 13:43
This issue has since been resolved - there's no longer an error in the reproduction case in this issue, so I am going to close this. Thanks!

**Closed by mildwonkey** 2021-06-23 13:43 UTC
Labels: bug, config, confirmed, v0.13
