### ISSUE TITLE
v0.12 - Data sources being evaluated too early resulting in plan error

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20200] opened 2019-02-01 19:05 UTC
### Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

### Terraform Configuration Files

```hcl
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}

variable "compartment_ocid" {}
variable "ssh_public_key" {}

# Choose an Availability Domain
variable "availability_domain" {
  default = "3"
}

variable "instance_image_ocid" {
  type = "map"

  default = {
    // See https://docs.us-phoenix-1.oraclecloud.com/images/
    // Oracle-provided image "Oracle-Linux-7.5-2018.10.16-0"
    us-phoenix-1 = "ocid1.image.oc1.phx.aaaaaaaaoqj42sokaoh42l76wsyhn3k2beuntrh5maj3gmgmzeyr55zzrwwa"

    us-ashburn-1   = "ocid1.image.oc1.iad.aaaaaaaageeenzyuxgia726xur4ztaoxbxyjlxogdhreu3ngfj2gji3bayda"
    eu-frankfurt-1 = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaitzn6tdyjer7jl34h2ujz74jwy5nkbukbh55ekp6oyzwrtfa4zma"
    uk-london-1    = "ocid1.image.oc1.uk-london-1.aaaaaaaa32voyikkkzfxyo4xbdmadc2dmvorfxxgdhpnk6dw64fa3l4jh7wa"
  }
}

variable "instance_shape" {
  default = "VM.Standard2.1"
}

provider "oci" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region           = "${var.region}"
}

# Gets a list of Availability Domains
data "oci_identity_availability_domains" "ADs" {
  compartment_id = "${var.tenancy_ocid}"
}

resource "oci_core_virtual_network" "ExampleVCN" {
  cidr_block     = "10.1.0.0/16"
  compartment_id = "${var.compartment_ocid}"
  display_name   = "TFExampleVCN"
  dns_label      = "tfexamplevcn"
}

resource "oci_core_subnet" "ExampleSubnet" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[var.availability_domain - 1],"name")}"
  cidr_block          = "10.1.20.0/24"
  display_name        = "TFExampleSubnet"
  dns_label           = "tfexamplesubnet"
  security_list_ids   = ["${oci_core_virtual_network.ExampleVCN.default_security_list_id}"]
  compartment_id      = "${var.compartment_ocid}"
  vcn_id              = "${oci_core_virtual_network.ExampleVCN.id}"
  route_table_id      = "${oci_core_virtual_network.ExampleVCN.default_route_table_id}"
  dhcp_options_id     = "${oci_core_virtual_network.ExampleVCN.default_dhcp_options_id}"
}

resource "oci_core_internet_gateway" "ExampleIG" {
  compartment_id = "${var.compartment_ocid}"
  display_name   = "TFExampleIG"
  vcn_id         = "${oci_core_virtual_network.ExampleVCN.id}"
}

resource "oci_core_default_route_table" "ExampleRT" {
  manage_default_resource_id = "${oci_core_virtual_network.ExampleVCN.default_route_table_id}"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${oci_core_internet_gateway.ExampleIG.id}"
  }
}

# Gets a list of vNIC attachments on the instance
data "oci_core_vnic_attachments" "InstanceVnics" {
  compartment_id      = "${var.compartment_ocid}"
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[var.availability_domain - 1],"name")}"
  instance_id         = "${oci_core_instance.TFInstance.id}"
}

# Gets the OCID of the first (default) vNIC
data "oci_core_vnic" "InstanceVnic" {
  vnic_id = "${lookup(data.oci_core_vnic_attachments.InstanceVnics.vnic_attachments[0],"vnic_id")}"
}

resource "oci_core_instance" "TFInstance" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[var.availability_domain - 1],"name")}"
  compartment_id      = "${var.compartment_ocid}"
  display_name        = "TFInstance"
  shape               = "${var.instance_shape}"

  create_vnic_details {
    subnet_id        = "${oci_core_subnet.ExampleSubnet.id}"
    display_name     = "primaryvnic"
    assign_public_ip = true
    hostname_label   = "tfexampleinstance"
  }

  source_details {
    source_type = "image"
    source_id   = "${var.instance_image_ocid[var.region]}"
  }

  metadata = {
    ssh_authorized_keys = "${var.ssh_public_key}"
  }

  /*
  timeouts {
    create = "60m"
  }
  */
}

resource "oci_core_instance_console_connection" "test_instance_console_connection" {
  #Required
  instance_id = "${oci_core_instance.TFInstance.id}"
  public_key  = "${var.ssh_public_key}"
}

output "connect_with_ssh" {
  value = "${oci_core_instance_console_connection.test_instance_console_connection.connection_string}"
}

output "connect_with_vnc" {
  value = "${oci_core_instance_console_connection.test_instance_console_connection.vnc_connection_string}"
}
```

### Debug Output

```
2019/02/01 10:56:55 [DEBUG] Starting graph walk: walkRefresh
2019-02-01T10:56:55.076-0800 [INFO]  plugin: configuring client automatic mTLS
2019-02-01T10:56:55.099-0800 [DEBUG] plugin: starting plugin: path=/Users/alexng/.terraform.d/plugins/terraform-provider-oci args=[/Users/alexng/.terraform.d/plugins/terraform-provider-oci]
2019-02-01T10:56:55.102-0800 [DEBUG] plugin: plugin started: path=/Users/alexng/.terraform.d/plugins/terraform-provider-oci pid=14924
2019-02-01T10:56:55.102-0800 [DEBUG] plugin: waiting for RPC address: path=/Users/alexng/.terraform.d/plugins/terraform-provider-oci
2019-02-01T10:56:55.117-0800 [DEBUG] plugin.terraform-provider-oci: INFO 2019/02/01 10:56:55 log.go:103: logger level set to:  0
2019-02-01T10:56:55.117-0800 [DEBUG] plugin.terraform-provider-oci: 2019/02/01 10:56:55 [INFO] terraform-provider-oci 3.14.0
2019-02-01T10:56:55.120-0800 [INFO]  plugin.terraform-provider-oci: configuring server automatic mTLS: timestamp=2019-02-01T10:56:55.120-0800
2019-02-01T10:56:55.145-0800 [DEBUG] plugin.terraform-provider-oci: plugin address: address=/var/folders/6r/8fk5dmbj4_z3sl0mc_y_fhjw0000gn/T/plugin777580123 network=unix timestamp=2019-02-01T10:56:55.144-0800
2019-02-01T10:56:55.145-0800 [DEBUG] plugin: using plugin: version=5
2019/02/01 10:56:55 [DEBUG] Resource state not found for node "data.oci_identity_availability_domains.ADs", instance data.oci_identity_availability_domains.ADs
2019/02/01 10:56:55 [DEBUG] ReferenceTransformer: "data.oci_identity_availability_domains.ADs" references: []
data.oci_identity_availability_domains.ADs: Refreshing state...
2019/02/01 10:56:55 [DEBUG] Resource state not found for node "data.oci_core_vnic_attachments.InstanceVnics", instance data.oci_core_vnic_attachments.InstanceVnics
2019/02/01 10:56:55 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2019/02/01 10:56:55 [TRACE] Executing graph transform *terraform.TargetsTransformer
2019/02/01 10:56:55 [TRACE] Completed graph transform *terraform.TargetsTransformer (no changes)
2019/02/01 10:56:55 [DEBUG] ReferenceTransformer: "data.oci_core_vnic_attachments.InstanceVnics" references: []
2019/02/01 10:56:55 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
2019/02/01 10:56:55 [DEBUG] ReferenceTransformer: "data.oci_core_vnic.InstanceVnic" references: []
2019/02/01 10:56:55 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
2019/02/01 10:56:55 [TRACE] Executing graph transform *terraform.RootTransformer
2019/02/01 10:56:55 [TRACE] Completed graph transform *terraform.RootTransformer (no changes)
2019/02/01 10:56:55 [TRACE] vertex "data.oci_core_vnic.InstanceVnic": entering dynamic subgraph
2019/02/01 10:56:55 [TRACE] dag/walk: updating graph
2019/02/01 10:56:55 [TRACE] dag/walk: added new vertex: "data.oci_core_vnic.InstanceVnic"
2019/02/01 10:56:55 [ERROR] <root>: eval: *terraform.EvalReadData, err: Invalid index: The given key does not identify an element in this collection value.
2019/02/01 10:56:55 [ERROR] <root>: eval: *terraform.EvalSequence, err: Invalid index: The given key does not identify an element in this collection value.
2019/02/01 10:56:55 [TRACE] [walkRefresh] Exiting eval tree: data.oci_core_vnic.InstanceVnic
2019/02/01 10:56:55 [TRACE] vertex "data.oci_core_vnic.InstanceVnic": visit complete
2019/02/01 10:56:55 [TRACE] vertex "data.oci_core_vnic.InstanceVnic": dynamic subgraph encountered errors

Error: Invalid index

  on /Users/alexng/go/src/github.com/terraform-providers/terraform-provider-oci/docs/examples/compute/console_connection/console_connection.tf line 90, in data "oci_core_vnic" "InstanceVnic":
  90:   vnic_id = "${lookup(data.oci_core_vnic_attachments.InstanceVnics.vnic_attachments[0],"vnic_id")}"
    |----------------
    | data.oci_core_vnic_attachments.InstanceVnics.vnic_attachments is empty list of object

The given key does not identify an element in this collection value.

2019-02-01T10:56:57.447-0800 [WARN]  plugin: plugin failed to exit gracefully
```

### Expected Behavior

In v0.11 Terraform CLI, running `terraform plan` would succeed.

Because of this dependency chain:
"data.oci_core_vnic.InstanceVnic" => "data.oci_core_vnic_attachments.InstanceVnics" => "oci_core_instance.TFInstance"

We expect the TFInstance resource to be created before the data sources can be evaluated.

### Actual Behavior

In v0.12 Terraform CLI, running `terraform plan` results in error.

From the error, it appears that data sources are being evaluated before the TFInstance has been created and so it thinks that the data source is empty.

### Steps to Reproduce

`terraform plan`

### Additional Context

The OCI provider being used is based v0.12 early plugin SDK.

**Comment by apparentlymart** [comment] 2019-02-01 19:13
Hi @alexng-canuck! Thanks for reporting this.

This seems similar to an issue we already fixed in the `master` branch since the alpha4 release. If possible, could you try this again with a build from the latest `master` commit in this repository to see if you see the same behavior? Any differences you see would be interesting to know since even if the issue isn't fully fixed there have definitely been some fixes to data resource lifecycle since alpha4.

To build from the master branch it should be sufficient to run `GO111MODULE=on go install -mod=vendor .` within the root directory of this repository. If possible, please use Go 1.11.5 since we're aware that there were some Go Modules-related bugs fixed recently that may otherwise cause build problems with earlier Go versions.

**Comment by alexng-canuck** [comment] 2019-02-25 19:11
Any updates on this? Using the Terraform CLI from tip of master (commit: e4756ddd52aa72c2cace47bac9a9ea36ae7e982f), I found another similar issue.

When referencing indices of collections that don't yet exist at plan time like this:

```
instance_id     = "${oci_core_instance.TFInstance.*.id[count.index / var.NumParavirtualizedVolumesPerInstance]}"
```

We are getting errors like this after running `terraform plan`:

```
Error: Invalid index

  on block.tf line 15, in resource "oci_core_volume_attachment" "TFBlockAttach":
  15:   instance_id     = "${oci_core_instance.TFInstance.*.id[count.index / var.NumIscsiVolumesPerInstance]}"
    |----------------
    | count.index is 5
    | oci_core_instance.TFInstance is tuple with 3 elements
    | var.NumIscsiVolumesPerInstance is "2"

The given key does not identify an element in this collection value.
```

Again, the above scenario worked fine with v0.11.

**Comment by apparentlymart** [comment] 2019-02-27 00:22
Hi @alexng-canuck,

For the second of these, I think the problem is something different: 5 divided by 2 is 2.5, which is indeed not not a valid index into that list. Terraform 0.11 had a tendency to prefer to convert variable values to integers and thus perform integer division in most cases, but Terraform 0.12 now always does floating point division, requiring explicit rounding down if that is desired, like this:

```hcl
instance_id     = "${oci_core_instance.TFInstance.*.id[floor(count.index / var.NumParavirtualizedVolumesPerInstance)]}"
```

**Comment by alexng-canuck** [comment] 2019-02-27 00:34
@apparentlymart Thanks for the response. 

Since floating point values are never a valid index value; couldn't v0.12 try to convert the floating point to a rounded-down integer (in the same way that v0.11 implicitly did a round down)?

That would help avoid breaking an assumption that was implied with v0.11. I don't believe the migration tool would help with this scenario either.

**Comment by apparentlymart** [comment] 2019-02-27 01:25
Due to our principle of "explicit is better than implicit", I think we'd instead change this to return a more specific error message if you try to index a list with a number that isn't whole, to guide the user to adding the explicit `floor` in this situation, and thus make the resulting configuration explicit about what mode of rounding is happening. (As much as possible, we try to design the language so that even people who aren't experts on Terraform can correctly guess what an expression is doing, by using familiar constructs and minimizing implicit behaviors.)

We did have this on our list of things the upgrade tool might check for, though indeed it would need to be contextual, such as applying the rule only in indexing brackets so we can assume that integer rounding was being relied on in the old configuration. We'll see during the beta process how common this situation is and thus whether it warrants automatic upgrading or whether we can just rely on a more actionable error message about it.

**Comment by alexng-canuck** [comment] 2019-02-27 18:01
Filed a separate github issue #20496  for the floating point issues.

**Comment by aserrallerios** [comment] 2019-02-28 10:39
I've also found this problem while adding additional `subject_alternative_names` to a certificate and then trying to create the corresponding dns records. For example, going from 0 alternative names to 1.

```
resource "aws_acm_certificate" "cert" {
  provider                    = "aws.virginia"
  domain_name                 = "${var.portal_domain}"
  subject_alternative_names   = "${var.portal_alt_names}"
  validation_method           = "DNS"
}

resource "aws_route53_record" "cert_validation" {
  depends_on = ["aws_acm_certificate.cert"]
  count   = "${length(var.portal_alt_names) + 1}"
  name    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_name")}"
  type    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_type")}"
  zone_id = "${var.route53_zone_id}"
  records = ["${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_value")}"]
  ttl     = 300
}
```

The certificate should be updated before the lookup of the route53 records are evaluated. Right now with v0.11.11 it just fails:

```
Error: Error refreshing state: 1 error(s) occurred:
* module.portal.aws_route53_record.cert_validation: 1 error(s) occurred:
* module.portal.aws_route53_record.cert_validation[1]: index 1 out of range for list aws_acm_certificate.cert.domain_validation_options (max 1) in:
${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_value")}
```

I've tried with taint:

`terraform taint -module=portal aws_acm_certificate.cert`

But no luck, got the same error.

So, it's the same problem described here? It's a bug? Any advice/workaround to overcome this?

**Comment by jbardin** [comment] 2019-03-18 22:35
Hi @alexng-canuck,

I haven't been able to reproduce any dependency order issues, but I also can't yet explain what else would cause that particular error.

Would it be possible to test this against the latest master branch of terraform (there have been significant changes since this build), and get a full log output of the test if it still fails?

**Comment by alexng-canuck** [comment] 2019-03-18 23:21
Let me give that a try again with latest master.

**Comment by alexng-canuck** [comment] 2019-03-19 22:44
@jbardin I'm still seeing the same error as of commit https://github.com/hashicorp/terraform/commit/35df450dc0afc0bb7226391532700cd92347a631

[terraform.log](https://github.com/hashicorp/terraform/files/2985823/terraform.log)

**Comment by jbardin** [comment] 2019-03-21 13:06
Hi @alexng-canuck,

Can you verify that you've recompiled the provider against the latest master terraform branch?
I can reproduce this in tests, but only using an older checkout of terraform.

If it's still showing up with the latest, could you provide instructions to help me execute the test? The logs aren't giving me quite enough info to diagnose the issue. Thanks!

**Comment by jbardin** [comment] 2019-03-21 13:15
@alexng-canuck,

There could also be problems if the transitive dependencies from terraform are not updated properly. If you want to point me to the branch you're using, I can verify the go modules are being updated correctly.

**Comment by alexng-canuck** [comment] 2019-03-21 18:25
Hi @jbardin , this is the branch I'm using for the provider: https://github.com/terraform-providers/terraform-provider-oci/tree/v12-beta

I did not recompile the provider with latest master branch, just the CLI.

**Comment by jbardin** [comment] 2019-03-21 18:52
The v12-beta branch is not synced with master. I can only reproduce the issue with the checkout you're using. It's also a good idea to always rebuild the provider when testing too, as some of the changes expect corresponding parts in the core, the sdk, and the dependencies.

**Comment by alexng-canuck** [comment] 2019-03-21 19:11
Hi @jbardin,

Seems like the issue went away for me after moving my provider dependencies to the tip of master or early-sdk-v5.

**Comment by jbardin** [comment] 2019-03-21 19:14
Thanks for confirming @alexng-canuck!

**Closed by jbardin** 2019-03-21 19:14 UTC
Labels: bug, core

**Comment by amarruedo** [comment] 2019-06-27 09:43
Hi there @jbardin , 

I think I'm hitting this same issue, but with different providers. 

I've got a terraform project that creates Vautl `approles` for Gitlab projects, then, it stores in those  projects CI/CD variables, the `role_id` of the newly generated `approle`.

```
Terraform v0.12.3
+ provider.gitlab v2.2.0
+ provider.local v1.2.2
+ provider.vault v2.0.0
```

Here is the Terraform code:

```
terraform {
  required_version = ">= 0.12.0"
}

provider "vault" {
  version = "2.0.0"
  max_lease_ttl_seconds = "3000"
}

provider "gitlab" {
    token = "mytoken"
    base_url = "https://mygitlab.com"
}

resource "vault_approle_auth_backend_role" "project_approle" {
  count = length(var.projects)
  role_name = replace(var.projects[count.index].name,"/","_")
  policies  = [
    for policy in var.projects[count.index].policies:
    replace(policy,"/","_")
  ]
  secret_id_num_uses = 1
  token_ttl = 100
  token_max_ttl = 100
}

data "vault_approle_auth_backend_role_id" "project_roles" {
  count = length(var.projects)
  role_name = replace(var.projects[count.index].name,"/","_")
  depends_on = [
      vault_approle_auth_backend_role.project_approle
    ]
}

resource "gitlab_project_variable" "project_role_id_variables" {
    count = length(var.projects)
    project = var.projects[count.index].id
    key = "ROLE_ID"
    value = data.vault_approle_auth_backend_role_id.project_roles[count.index].role_id
    protected = false
}
```

where `projetcs` represents the Gitlab project list I want to configure:

```
projects = [
    {
        id = "1"
        name= "projectA"
        policies = [
            "secret/read-secretA",
            "secret/read-secretB"
        ]
    },
    {
        id = "2"
        name= "projectB"
        policies = [
            "secret/read-secretA"
            ]
    }
]
```

This used to work on terraform 0.11.* but now, with terraform 0.12.* the plan fails with:

```
Error: Invalid index

  on maint.tf line 48, in resource "gitlab_project_variable" "project_role_id_variables":
  48:     value = data.vault_approle_auth_backend_role_id.project_roles.*.role_id[count.index]
    |----------------
    | count.index is 11
    | data.vault_approle_auth_backend_role_id.project_roles is empty tuple

The given key does not identify an element in this collection value.
```

Doing some tests I've checked that the problem here is that I'm using an array that is populated on the apply stage, since `role_id`s are data that we don't know till we apply. But curiouslly, modifying the configuration to this (creating just one dummy `approle` and using it's `role_id`), works as expected:

```
....

resource "vault_approle_auth_backend_role" "project_approle" {
  role_name = "test-role"
  policies  = [
    "default"
  ]
  secret_id_num_uses = 1
  token_ttl = 100
  token_max_ttl = 100
}

data "vault_approle_auth_backend_role_id" "project_roles" {
  role_name = "test-role"
  depends_on = [
      vault_approle_auth_backend_role.project_approle
    ]
}

resource "gitlab_project_variable" "project_role_id_variables" {
    count = length(var.projects)
    project = var.projects[count.index].id
    key = "TEST_ROLE"
    value = data.vault_approle_auth_backend_role_id.project_roles.role_id
    protected = false
}

....
```

So I guess the problem only occurs (in my use case) when using arrays of computed data.

I'm almost sure that this is no t related to the providers I am using and that must be something telated to Terraform changes from 0.11.* to 0.12.*. On the other hand I'm not sure if I'm trying to do something that's not possible, but taken in account that this was possible in previous version I guess I'm not in that situation.

Any clue on what's going on or how should I proceed to solve this issue? 

Thnaks for your attention.

**Comment by jbardin** [comment] 2019-06-27 13:15
@amarruedo,

This issue turned out to be something unrelated. Please file a new issue, along with the steps to reproduce it. If it looks like a dependency ordering issue, It would be useful to include a gist of the full trace log of the reproduction as well. Thanks!

**Comment by amarruedo** [comment] 2019-06-27 14:33
@jbardin opened new [issue](https://github.com/hashicorp/terraform/issues/21917).

Thanks!
