### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by surjeet-singh-centrica** [hashicorp/terraform#34029] opened 2023-10-09 14:20 UTC
### Terraform Version

```shell
hashicorp/aws v5.20.0 (signed by HashiCorp)
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0xc0008bbf40, 0xc001578330)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:1082 +0x27e
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0006fca50, 0xc001578330)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:421 +0x1413
github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc008664a80, 0xf?, {0x4a?, 0x185?, 0xc000c0c7e0?}, 0xc001578330)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/spec.go:214 +0x1f5
github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc008664990, 0xc008664990?, {0x0, 0x0, 0x0}, 0xc001cea6f0?)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/spec.go:88 +0x1f7
github.com/hashicorp/hcl/v2/hcldec.decode({0x3903ae0, 0xc003175d80}, {0x0, 0x0, 0x0}, 0x0?, {0x3902fb8, 0xc008664990}, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/decode.go:24 +0x10f
github.com/hashicorp/hcl/v2/hcldec.Decode(...)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/public.go:18
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalBlock(0xc00152b320, {0x3903530, 0xc00575f9b0}, 0xc006fbd178?)
	/home/runner/work/terraform/terraform/internal/lang/eval.go:71 +0x1ea
github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc0011d8db0?, {0x3902d18, 0xc0009e0420}, 0xc001aa98c0?, {0x0?, 0x0?}, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...})
	/home/runner/work/terraform/terraform/internal/terraform/eval_context_builtin.go:282 +0x145
github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).validateResource(0xc000d065a0, {0x391fb60, 0xc0010c3260})
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:372 +0x666
github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).Execute(0xc000d065a0, {0x391fb60, 0xc0010c3260}, 0x1?)
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:52 +0x55
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc001c44b40, {0x391fb60, 0xc0010c3260}, {0x7f6cc4f12f28, 0xc000d065a0})
	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x30d81c0, 0xc000d065a0})
	/home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000fee540, {0x30d81c0, 0xc000d065a0}, 0xc001485c00)
	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 14
	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8

### Expected Behavior

Shoud pass like a version before

### Actual Behavior

Crashed

### Steps to Reproduce

terraform init
terraform plan

**Comment by surjeet-singh-centrica** [comment] 2023-10-09 14:25
- Installing hashicorp/aws v5.20.0...
- Installed hashicorp/aws v5.20.0 (signed by HashiCorp)
- Installing datadog/datadog v3.30.0...
- Installed datadog/datadog v3.30.0 (signed by a HashiCorp partner, key ID FB70BE941301C3EA)
- Installing hashicorp/random v3.5.1...
- Installed hashicorp/random v3.5.1 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
Other versions are above

**Comment by surjeet-singh-centrica** [comment] 2023-10-09 14:39
Here's the log @jbardin 
2023-10-09T10:11:19.3560421Z ##[section]Starting: Terraform Plan
2023-10-09T10:11:19.3566021Z ==============================================================================
2023-10-09T10:11:19.3566182Z Task         : Terraform
2023-10-09T10:11:19.3566284Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
2023-10-09T10:11:19.3566479Z Version      : 0.203.0
2023-10-09T10:11:19.3566579Z Author       : Microsoft Corporation
2023-10-09T10:11:19.3566678Z Help         : [Learn more about this task](https://aka.ms/AAf1a0u)
2023-10-09T10:11:19.3566799Z ==============================================================================
2023-10-09T10:11:19.5585436Z [command]/usr/local/bin/terraform providers
2023-10-09T10:11:21.1593144Z 
2023-10-09T10:11:21.1594342Z Providers required by configuration:
2023-10-09T10:11:21.1594842Z .
2023-10-09T10:11:21.1596401Z ├── provider[registry.terraform.io/hashicorp/aws] >= 4.0.0
2023-10-09T10:11:21.1597045Z ├── provider[registry.terraform.io/datadog/datadog]
2023-10-09T10:11:21.1597546Z ├── module.s3
2023-10-09T10:11:21.1653009Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1653341Z ├── module.step-function
2023-10-09T10:11:21.1653665Z │   ├── provider[registry.terraform.io/hashicorp/template]
2023-10-09T10:11:21.1653998Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1654251Z ├── module.iam
2023-10-09T10:11:21.1654545Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1654824Z ├── module.uaa-integration
2023-10-09T10:11:21.1655125Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1655385Z ├── module.dynamo-db
2023-10-09T10:11:21.1655679Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1655957Z ├── module.sns
2023-10-09T10:11:21.1656244Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1656494Z ├── module.sqs
2023-10-09T10:11:21.1656814Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1657131Z ├── module.estimated-meter-reads-exporter
2023-10-09T10:11:21.1657445Z │   ├── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1657769Z │   └── provider[registry.terraform.io/hashicorp/random]
2023-10-09T10:11:21.1658026Z ├── module.kms
2023-10-09T10:11:21.1658309Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1658557Z ├── module.glue
2023-10-09T10:11:21.1658840Z │   ├── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1659158Z │   └── provider[registry.terraform.io/hashicorp/random]
2023-10-09T10:11:21.1659418Z ├── module.ssm
2023-10-09T10:11:21.1659698Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1659947Z ├── module.lambda
2023-10-09T10:11:21.1660245Z │   └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1660509Z └── module.event-bridge
2023-10-09T10:11:21.1660803Z     └── provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1660911Z 
2023-10-09T10:11:21.1661102Z Providers required by state:
2023-10-09T10:11:21.1661194Z 
2023-10-09T10:11:21.1661409Z     provider[registry.terraform.io/datadog/datadog]
2023-10-09T10:11:21.1661520Z 
2023-10-09T10:11:21.1661716Z     provider[registry.terraform.io/hashicorp/aws]
2023-10-09T10:11:21.1661816Z 
2023-10-09T10:11:21.1662019Z     provider[registry.terraform.io/hashicorp/random]
2023-10-09T10:11:21.1662141Z 
2023-10-09T10:11:21.1662342Z     provider[registry.terraform.io/hashicorp/template]
2023-10-09T10:11:21.1662451Z 
2023-10-09T10:11:21.1674533Z [command]/usr/local/bin/terraform plan -var=aws_accountId=*** -var=aws_region=*** -var=aws_stage=v1 -var=lambda_deploy_bucket=nep-dev-deployments -var=aws_environment=dev -var=mule_user_name=muleapiuser-sit -var=sftp_directory=*** -var=sftp_host=*** -var=sftp_port=*** -var=sftp_username=*** -var=sftp_password=*** -var=sftp_lambda_vpc_security_group_id=<group> -var=sftp_lambda_vpc_subnet_ids=subnet-011972a38e47649af,subnet-0f7f083e3f55ec46f -var=dd_api_key=*** -var=dd_app_key=*** -var=dd_api_key=*** -var=dd_app_key=*** -var=datadog_forwarder_arn=arn:aws:lambda:***:***:function:datadog-ForwarderStack-EHW8WYZV12KW-Forwarder-IFIJuT9Fssbv -var=alert_distribution_list=["email@email.com"] -detailed-exitcode
2023-10-09T10:11:24.6811694Z 
2023-10-09T10:11:24.6812641Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-10-09T10:11:24.6813098Z 
2023-10-09T10:11:24.6813571Z Terraform crashed! This is always indicative of a bug within Terraform.
2023-10-09T10:11:24.6815430Z Please report the crash with Terraform[1] so that we can fix this.
2023-10-09T10:11:24.6815738Z 
2023-10-09T10:11:24.6816205Z When reporting bugs, please include your terraform version, the stack trace
2023-10-09T10:11:24.6816980Z shown below, and any additional information which may help replicate the issue.
2023-10-09T10:11:24.6817266Z 
2023-10-09T10:11:24.6817694Z [1]: https://github.com/hashicorp/terraform/issues
2023-10-09T10:11:24.6818069Z 
2023-10-09T10:11:24.6818609Z !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-10-09T10:11:24.6818759Z 
2023-10-09T10:11:24.6818967Z value is marked, so must be unmarked first
2023-10-09T10:11:24.6819288Z goroutine 701 [running]:
2023-10-09T10:11:24.6819524Z runtime/debug.Stack()
2023-10-09T10:11:24.6953669Z 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
2023-10-09T10:11:24.6955160Z runtime/debug.PrintStack()
2023-10-09T10:11:24.6956269Z 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
2023-10-09T10:11:24.6957208Z github.com/hashicorp/terraform/internal/logging.PanicHandler()
2023-10-09T10:11:24.6958098Z 	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
2023-10-09T10:11:24.6959583Z panic({0x2b92ec0?, 0x38c4c30?})
2023-10-09T10:11:24.6961457Z 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
2023-10-09T10:11:24.6964010Z github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
2023-10-09T10:11:24.6965305Z 	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/marks.go:141
2023-10-09T10:11:24.6966682Z github.com/zclconf/go-cty/cty.Value.AsString({{{0x3902720?, 0xc000146bd1?}}, {0x2e1de40?, 0xc0017366f0?}})
2023-10-09T10:11:24.6968241Z 	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_ops.go:1385 +0x47
2023-10-09T10:11:24.6969918Z github.com/zclconf/go-cty/cty.Value.Range({{{0x3902720?, 0xc000146bd1?}}, {0x2e1de40?, 0xc0017366f0?}})
2023-10-09T10:11:24.6971413Z 	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_range.go:53 +0x285
2023-10-09T10:11:24.6973059Z github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc0009d4070, 0xc0017366a8)
2023-10-09T10:11:24.6973678Z 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:745 +0xd35
2023-10-09T10:11:24.6974404Z github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0xc000c9dc20, 0xc0017366a8)
2023-10-09T10:11:24.6976978Z 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:1082 +0x27e
2023-10-09T10:11:24.6977523Z github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0006faa50, 0xc0017366a8)
2023-10-09T10:11:24.6980031Z 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:421 +0x1413
2023-10-09T10:11:24.6982712Z github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc004d43290, 0xc00175acf8?, {0xc002489db0?, 0x9?, 0xc000ca13b0?}, 0xc0017366a8)
2023-10-09T10:11:24.6983999Z 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/spec.go:214 +0x1f5
2023-10-09T10:11:24.6985256Z github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc004d43260, 0xc004d43260?, {0x0, 0x0, 0x0}, 0xc005a1cea0?)
2023-10-09T10:11:24.6986514Z 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/spec.go:88 +0x1f7
2023-10-09T10:11:24.6987779Z github.com/hashicorp/hcl/v2/hcldec.decode({0x3903ae0, 0xc001740320}, {0x0, 0x0, 0x0}, 0x0?, {0x3902fb8, 0xc004d43260}, 0x0)
2023-10-09T10:11:24.6989340Z 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/decode.go:24 +0x10f
2023-10-09T10:11:24.6990525Z github.com/hashicorp/hcl/v2/hcldec.Decode(...)
2023-10-09T10:11:24.6991694Z 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/public.go:18
2023-10-09T10:11:24.6992934Z github.com/hashicorp/terraform/internal/lang.(*Scope).EvalBlock(0xc00170a870, {0x3903530, 0xc0065a3740}, 0xc001111178?)
2023-10-09T10:11:24.6994167Z 	/home/runner/work/terraform/terraform/internal/lang/eval.go:71 +0x1ea
2023-10-09T10:11:24.6995464Z github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc000e7d440?, {0x3902d18, 0xc00083c370}, 0xc00114cde0?, {0x0?, 0x0?}, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...})
2023-10-09T10:11:24.6996896Z 	/home/runner/work/terraform/terraform/internal/terraform/eval_context_builtin.go:282 +0x145
2023-10-09T10:11:24.6998179Z github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).validateResource(0xc000f7a678, {0x391fb60, 0xc000ee0540})
2023-10-09T10:11:24.6999488Z 	/home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:372 +0x666
2023-10-09T10:11:24.7000761Z github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).Execute(0xc000f7a678, {0x391fb60, 0xc000ee0540}, 0x1?)
2023-10-09T10:11:24.7002042Z 	/home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:52 +0x55
2023-10-09T10:11:24.7003611Z github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc003bb4fc0, {0x391fb60, 0xc000ee0540}, {0x7f09daaa6a18, 0xc000f7a678})
2023-10-09T10:11:24.7004902Z 	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
2023-10-09T10:11:24.7006139Z github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x30d81c0, 0xc000f7a678})
2023-10-09T10:11:24.7007358Z 	/home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
2023-10-09T10:11:24.7008612Z github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000e41c80, {0x30d81c0, 0xc000f7a678}, 0xc0024b8a80)
2023-10-09T10:11:24.7009862Z 	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
2023-10-09T10:11:24.7011057Z created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 26
2023-10-09T10:11:24.7012257Z 	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8
2023-10-09T10:11:24.7062224Z ##[error]Error: Terraform Plan failed with exit code: 11
2023-10-09T10:11:24.7071927Z ##[section]Finishing: Terraform Plan

**Comment by jbardin** [comment] 2023-10-09 14:40
Duplicate of #33977

**Closed by jbardin** 2023-10-09 14:40 UTC
Labels: bug, waiting-response, new

**Comment by kahlan-dev** [comment] 2023-10-10 11:14
Is there any other workaround if we don't have control over what Terraform version we can use?  Our other pipelines are running just fine even with the latest TF version but for some reason, it is failing for a specific repository.
