### ISSUE TITLE
Wrong task definition values on ECS fargate

### ISSUE THREAD

**Issue by akramdhiabii** [hashicorp/terraform#29466] opened 2021-08-27 14:22 UTC
Hi there,
I am facing an issue when tried to create an ECS services **_'project-activity-cron'_** and a scheduled task **_'due_date_reminder_run'_** that share the same task definition template with different env variables values.
The problem is when apply these resources, the **_project-activity-cron_** is taking the **_due_date_reminder_run_** task definition!

### Terraform Version
```
Terraform 1.0.4 ( on Github actions - ubuntu latest)
```

### Terraform Configuration Files

```
############ due_date_reminder_run  ##################

data "template_file" "ddrr_container_definitions" {
  template   = file("templates/task.def.json.tpl")

  vars = {
    app_name                      = "due_date_reminder_run"
    app_image                     = var.ecr_image_backend
    pr_id                         = "${local.prefix}"
    log_group_name                = aws_cloudwatch_log_group.ecs_task_logs.name
    log_group_region              = "${local.region_id}"
  }
}

resource "aws_ecs_task_definition" "due_date_reminder_run" {
  family                   = local.prefix == "production" ? "project-activity-cron" : "${local.prefix}-project-activity-cron"
  container_definitions    = data.template_file.ddrr_container_definitions.rendered
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  execution_role_arn = aws_iam_role.task_execution_role.arn
  task_role_arn = aws_iam_role.app_iam_role.arn

  tags = local.common_tags
}

resource "aws_cloudwatch_event_rule" "ddrr_scheduled_task" {
  name                = local.prefix == "production" ? "due-date-reminder-run" : "${local.prefix}-due-date-reminder-run"
  schedule_expression = "cron(0 * * * ? *)"
}

resource "aws_cloudwatch_event_target" "ddrr_scheduled_task" {
  target_id = local.prefix == "production" ? "due-date-reminder-run" : "${local.prefix}-due-date-reminder-run"
  rule      = aws_cloudwatch_event_rule.ddrr_scheduled_task.name
  arn       = aws_ecs_cluster.main.arn
  role_arn  = aws_iam_role.scheduled_task_cloudwatch.arn

  ecs_target {
    task_count          = 1
    task_definition_arn = aws_ecs_task_definition.due_date_reminder_run.arn
    launch_type         = "FARGATE"
    network_configuration {
      subnets          = local.prefix == "production" ? "${lookup(var.private_subnets_ids, terraform.workspace)}" : "${lookup(var.private_subnets_ids, "dev")}"
      assign_public_ip = false
      security_groups  = [aws_security_group.ecs_service.id]
    }
  }
}

############ project activity cron service ##################

data "template_file" "pac_container_definitions" {
  template   = file("templates/task.def.json.tpl")

  vars = {
    app_name                      = "project-activity-cron"
    app_image                     = var.ecr_image_backend
    pr_id                         = "${local.prefix}"
    log_group_name                = aws_cloudwatch_log_group.ecs_task_logs.name
    log_group_region              = "${local.region_id}"
  }
}

resource "aws_ecs_task_definition" "project_activity_cron" {
  family                   = "${local.prefix}-project-activity-cron"
  container_definitions    = data.template_file.pac_container_definitions.rendered
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  execution_role_arn = aws_iam_role.task_execution_role.arn
  task_role_arn = aws_iam_role.app_iam_role.arn

  tags = local.common_tags
}

resource "aws_ecs_service" "project_activity_cron" {
  name            = local.prefix == "production" ? "project-activity-cron" : "${local.prefix}-project-activity-cron"
  cluster         = aws_ecs_cluster.main.name
  task_definition = aws_ecs_task_definition.project_activity_cron.family
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = local.prefix == "production" ? "${lookup(var.private_subnets_ids, terraform.workspace)}" : "${lookup(var.private_subnets_ids, "dev")}"
    security_groups  = [aws_security_group.ecs_service.id]
    assign_public_ip = false
  }
}


```

### Debug Output

```
# data.template_file.ddrr_container_definitions will be read during apply
  # (config refers to values not yet known)
 <= data "template_file" "ddrr_container_definitions"  {
      + id       = (known after apply)
      + rendered = (known after apply)
      + template = jsonencode(
            [
              + {
                  + command          = [
                      + "bin/run",
                      + "${app_name}",
                    ]
                  + environment      = [
                      + {
                          + name  = "ENV"
                          + value = "${pr_id}"
                        },
                      + {
                          + name  = "INSPECT"
                          + value = ""
                        },
                    ]
                  + essential        = true
                  + image            = "${app_image}"
                  + logConfiguration = {
                      + logDriver = "awslogs"
                      + options   = {
                          + awslogs-group         = "${log_group_name}"
                          + awslogs-region        = "${log_group_region}"
                          + awslogs-stream-prefix = "${app_name}"
                        }
                    }
                  + name             = "${app_name}"
                  + portMappings     = [
                      + {
                          + containerPort = 8080
                          + hostPort      = 8080
                        },
                      + {
                          + containerPort = 9229
                          + hostPort      = 9229
                        },
                    ]
                },
            ]
        )
      + vars     = {
          + "app_image"                     = "***:1579-aa247aef"
          + "app_name"                      = "due_date_reminder_run"
          + "log_group_name"                = "1579-logs"
          + "log_group_region"              = "***"
          + "pr_id"                         = "1579"
        }
    }

  # data.template_file.pac_container_definitions will be read during apply
  # (config refers to values not yet known)
 <= data "template_file" "pac_container_definitions"  {
      + id       = (known after apply)
      + rendered = (known after apply)
       + template = jsonencode(
            [
              + {
                  + command          = [
                      + "bin/run",
                      + "${app_name}",
                    ]
                  + environment      = [
                      + {
                          + name  = "ENV"
                          + value = "${pr_id}"
                        },
                      + {
                          + name  = "INSPECT"
                          + value = ""
                        },
                    ]
                  + essential        = true
                  + image            = "${app_image}"
                  + logConfiguration = {
                      + logDriver = "awslogs"
                      + options   = {
                          + awslogs-group         = "${log_group_name}"
                          + awslogs-region        = "${log_group_region}"
                          + awslogs-stream-prefix = "${app_name}"
                        }
                    }
                  + name             = "${app_name}"
                  + portMappings     = [
                      + {
                          + containerPort = 8080
                          + hostPort      = 8080
                        },
                      + {
                          + containerPort = 9229
                          + hostPort      = 9229
                        },
                    ]
                },
            ]
        )
      + vars     = {
          + "app_image"                     = "***:1579-aa247aef"
          + "app_name"                      = "project-activity-cron"
          + "log_group_name"                = "1579-logs"
          + "log_group_region"              = "***"
          + "pr_id"                         = "1579"
        }
    }

....

 # aws_ecs_task_definition.due_date_reminder_run will be created
  + resource "aws_ecs_task_definition" "due_date_reminder_run" {
      + arn                      = (known after apply)
      + container_definitions    = (known after apply)
      + cpu                      = "256"
      + execution_role_arn       = (known after apply)
      + family                   = "1579-project-activity-cron"
      + id                       = (known after apply)
      + memory                   = "512"
      + network_mode             = "awsvpc"
      + requires_compatibilities = [
          + "FARGATE",
        ]
      + revision                 = (known after apply)
      + tags                     = {
          + "Environment" = "1579"
          + "ManagedBy"   = "Terraform"
          + "Owner"       = "dhiabi.akram@gmail.com"
          + "Project"     = "XXXX"
        }
      + task_role_arn            = (known after apply)
    }

  # aws_ecs_task_definition.project_activity_cron will be created
  + resource "aws_ecs_task_definition" "project_activity_cron" {
      + arn                      = (known after apply)
      + container_definitions    = (known after apply)
      + cpu                      = "256"
      + execution_role_arn       = (known after apply)
      + family                   = "1579-project-activity-cron"
      + id                       = (known after apply)
      + memory                   = "512"
      + network_mode             = "awsvpc"
      + requires_compatibilities = [
          + "FARGATE",
        ]
      + revision                 = (known after apply)
      + tags                     = {
          + "Environment" = "1579"
          + "ManagedBy"   = "Terraform"
          + "Owner"       = "dhiabi.akram@gmail.com"
          + "Project"     = "XXXX"
        }
      + task_role_arn            = (known after apply)
    }

```
### Expected Behavior
Every task definition should be created with its correct values as it were separately created.

### Actual Behavior
_**project-activity-cron**_ task definition is the same as the _**due-date-reminder-run**_ task definition -- it could be a caching problem..

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. terraform init
2. terraform plan
3. terraform apply

**Comment by apparentlymart** [comment] 2021-08-27 23:23
Hi @akramdhiabii,

In your plan output I see some string values which contain literal sequences which seem like they were intended to be interpolation syntax:

```
                  + image            = "${app_image}"
                  + logConfiguration = {
                      + logDriver = "awslogs"
                      + options   = {
                          + awslogs-group         = "${log_group_name}"
                          + awslogs-region        = "${log_group_region}"
                          + awslogs-stream-prefix = "${app_name}"
                        }
                    }
```

This suggest that there's something wrong with your template, because it's generating literally the characters `${app_image}` instead of substituting the provided `app_image` variable. Perhaps you've escaped the sequence `$${app_image}`, which tells the template provider that you want to literally write `${app_image}` instead of having it replaced.

You're also using the deprecated `template_file` data source. That continues to exist only for folks using Terraform v0.11 or earlier. You should instead replace that with local values calling [the `templatefile` function](https://www.terraform.io/docs/language/functions/templatefile.html):

```hcl
locals {
  ddrr_container_definitions = templatefile("${path.module}/templates/task.def.json.tpl", {
    app_name         = "due_date_reminder_run"
    app_image        = var.ecr_image_backend
    pr_id            = local.prefix
    log_group_name   = aws_cloudwatch_log_group.ecs_task_logs.name
    log_group_region = local.region_id
  })
  pac_container_definitions = templatefile("${path.module}/templates/task.def.json.tpl", {
    app_name         = "project-activity-cron"
    app_image        = var.ecr_image_backend
    pr_id            = local.prefix
    log_group_name   = aws_cloudwatch_log_group.ecs_task_logs.name
    log_group_region = local.region_id
  })
}
```

You can then replace `data.template_file.ddrr_container_definitions.rendered` with `local.ddrr_container_definitions`, and `data.template_file.pac_container_definitions.rendered` with `local.pac_container_definitions`.

However, if your template syntax _is_ wrong as I described above then it'll still generate the wrong result with `templatefile` too, because the two use the same template syntax. You'll need to make sure your template uses correct Terraform template syntax. If you're not sure what's wrong with it, feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) and share your template contents.

Since the behavior you've seen seems to be caused by an invalid template rather than a Terraform bug, I'm going to close this issue. However, if we do discuss this in the community forum and we find that there is a Terraform bug after all (once you have a correct template) then we can reopen this issue or open a new one.

Thanks!

**Closed by apparentlymart** 2021-08-27 23:23 UTC
Labels: bug, new
