### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by IlonaHancharova** [hashicorp/terraform#34659] opened 2024-02-12 15:13 UTC
### Terraform Version

```shell
1.4.0
```

### Terraform Configuration Files

-

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0xc0025aaf60?)
	/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc00013f400, {0x2ccf8f8, 0xc0008d3e80}, {0x2ccf8f8, 0xc0008d3ec0}, 0xc0008e4360, 0xc0008d3e40)
	/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a

### Expected Behavior

##[error]Terraform command 'plan' failed with exit code '11'.

### Actual Behavior

launch in Azure DevOps. when starting deletion in a planning step, an error occurs in terraform

### Steps to Reproduce

1. Terraform init
2. Terraform validate
3. Terraform plan

**Comment by liamcervante** [comment] 2024-02-12 16:28
Hi @IlonaHancharova, based on the stack trace I think this is a duplicate of https://github.com/hashicorp/terraform/issues/32810. Are you able to upgrade to v1.4.1 and see if this still crashes?

I will close this as a duplicate for now, if upgrading doesn't work then please feel free to reopen! Thanks!

**Closed by liamcervante** 2024-02-12 16:28 UTC
Labels: bug, new
