### ISSUE TITLE
RabbitMQ Provider - Create binding

### ISSUE THREAD

**Issue by jason-archidera** [hashicorp/terraform#12810] opened 2017-03-17 14:27 UTC
Terraform,

I found an issue when creating a queue on RabbitMQ.  

Terraform version: 0.9
RabbitMQ version: 3.5.6

When running `terraform apply`, I receive the following:

_Error applying plan:

1 error(s) occurred:

* rabbitmq_queue.test_queue: 1 error(s) occurred:

* rabbitmq_queue.test_queue: json: cannot unmarshal string into Go struct field DetailedQueueInfo.consumer_utilisation of type float64

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure._

You can recreate with the the config below.  
```
# Configure the RabbitMQ provider
provider "rabbitmq" {
  endpoint = "http://127.0.0.1:15672"
  username = "xxxx"
  password = "xxxxxx"
  insecure = true
}


#CREATE THE VHOST
resource "rabbitmq_vhost" "vhost" {
    name = "BINDING-TEST-DEVELOPMENT"
}

resource "rabbitmq_permissions" "admin_builtin" {
    user = "admin"
    vhost = "BINDING-TEST-DEVELOPMENT"
    permissions {
        configure = ".*"
        write = ".*"
        read = ".*"
    }
}

#CREATE EXCHANGES
resource "rabbitmq_exchange" "test_exchange" {
    depends_on = ["rabbitmq_permissions.admin_builtin"]
    name = "Test"
    vhost = "BINDING-TEST-DEVELOPMENT"
    settings {
        type = "topic"
        durable = true
        auto_delete = false
    }
}

#CREATE QUEUES
resource "rabbitmq_queue" "test_queue" {
    depends_on = ["rabbitmq_permissions.admin_builtin"]
    name = "Test.Queue"
    vhost = "BINDING-TEST-DEVELOPMENT"
    settings {
        durable = true
        auto_delete = false
    }
}

#CREATE BINDINGS
resource "rabbitmq_binding" "test_exchange_to_test_queue" {
    source = "Test"
    vhost = "BINDING-TEST-DEVELOPMENT"
    destination = "Test.Queue"
    destination_type = "queue"
    routing_key = "ANYTHING.#"
    properties_key = "%23"
}

```

**Comment by snowsky** [comment] 2017-03-17 18:26
I didn't reproduce with the exact error code:
```
rabbitmq_vhost.vhost: Creation complete (ID: BINDING-T...ELOPMENT)
Error applying plan:

2 error(s) occurred:

* rabbitmq_permissions.admin_builtin: 1 error(s) occurred:

* rabbitmq_permissions.admin_builtin: Error setting permissions: 400 Bad Request
* rabbitmq_binding.test_exchange_to_test_queue: 1 error(s) occurred:

* rabbitmq_binding.test_exchange_to_test_queue: Error declaring RabbitMQ binding: 401 Unauthorized

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by jason-archidera** [comment] 2017-03-17 18:37
@snowsky, what version of RabbitMQ are you pointing at?  I think I found where the RabbitMQ folks fixed something after 3.5.6 to solve this.  It's probably an issue with that or with the RabbitMQ provider.

**Comment by snowsky** [comment] 2017-03-17 18:41
@jason-archidera It is 3.6.7

**Comment by snowsky** [comment] 2017-03-17 18:44
And it succeeded after running the same command a few times:
```
vagrant@ubuntu-aaas:~/go/src/github.com/hashicorp/terraform/builtin/providers/rabbitmq$ terraform apply
rabbitmq_permissions.admin_builtin: Creating...
  permissions.#:           "" => "1"
  permissions.0.configure: "" => ".*"
  permissions.0.read:      "" => ".*"
  permissions.0.write:     "" => ".*"
  user:                    "" => "admin"
  vhost:                   "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_binding.test_exchange_to_test_queue: Creating...
  destination:      "" => "Test.Queue"
  destination_type: "" => "queue"
  properties_key:   "" => "%23"
  routing_key:      "" => "ANYTHING.#"
  source:           "" => "Test"
  vhost:            "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_vhost.vhost: Creating...
  name: "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_vhost.vhost: Creation complete (ID: BINDING-T...ELOPMENT)
Error applying plan:

2 error(s) occurred:

* rabbitmq_permissions.admin_builtin: 1 error(s) occurred:

* rabbitmq_permissions.admin_builtin: Error setting permissions: 400 Bad Request
* rabbitmq_binding.test_exchange_to_test_queue: 1 error(s) occurred:

* rabbitmq_binding.test_exchange_to_test_queue: Error declaring RabbitMQ binding: 500 Internal Server Error

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
vagrant@ubuntu-aaas:~/go/src/github.com/hashicorp/terraform/builtin/providers/rabbitmq$ terraform apply
rabbitmq_vhost.vhost: Refreshing state... (ID: BINDING-T...ELOPMENT)
rabbitmq_permissions.admin_builtin: Creating...
  permissions.#:           "" => "1"
  permissions.0.configure: "" => ".*"
  permissions.0.read:      "" => ".*"
  permissions.0.write:     "" => ".*"
  user:                    "" => "admin"
  vhost:                   "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_binding.test_exchange_to_test_queue: Creating...
  destination:      "" => "Test.Queue"
  destination_type: "" => "queue"
  properties_key:   "" => "%23"
  routing_key:      "" => "ANYTHING.#"
  source:           "" => "Test"
  vhost:            "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_permissions.admin_builtin: Creation complete (ID: admin@BIN...ELOPMENT)
rabbitmq_exchange.test_exchange: Creating...
  name:                   "" => "Test"
  settings.#:             "" => "1"
  settings.0.auto_delete: "" => "false"
  settings.0.durable:     "" => "true"
  settings.0.type:        "" => "topic"
  vhost:                  "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_queue.test_queue: Creating...
  name:                   "" => "Test.Queue"
  settings.#:             "" => "1"
  settings.0.auto_delete: "" => "false"
  settings.0.durable:     "" => "true"
  vhost:                  "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_exchange.test_exchange: Creation complete (ID: Test@BIND...ELOPMENT)
rabbitmq_queue.test_queue: Creation complete (ID: Test.Queu...ELOPMENT)
Error applying plan:

1 error(s) occurred:

* rabbitmq_binding.test_exchange_to_test_queue: 1 error(s) occurred:

* rabbitmq_binding.test_exchange_to_test_queue: Error declaring RabbitMQ binding: 404 Not Found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
vagrant@ubuntu-aaas:~/go/src/github.com/hashicorp/terraform/builtin/providers/rabbitmq$ terraform apply
rabbitmq_vhost.vhost: Refreshing state... (ID: BINDING-T...ELOPMENT)
rabbitmq_permissions.admin_builtin: Refreshing state... (ID: admin@BIN...ELOPMENT)
rabbitmq_queue.test_queue: Refreshing state... (ID: Test.Queu...ELOPMENT)
rabbitmq_exchange.test_exchange: Refreshing state... (ID: Test@BIND...ELOPMENT)
rabbitmq_binding.test_exchange_to_test_queue: Creating...
  destination:      "" => "Test.Queue"
  destination_type: "" => "queue"
  properties_key:   "" => "%23"
  routing_key:      "" => "ANYTHING.#"
  source:           "" => "Test"
  vhost:            "" => "BINDING-TEST-DEVELOPMENT"
rabbitmq_binding.test_exchange_to_test_queue: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: 
```

**Comment by snowsky** [comment] 2017-03-17 18:45
I created a user named admin before apply commands.

**Comment by snowsky** [comment] 2017-03-17 18:48
Ok, I see where the issue is. The Test queue depends on the binding, but when Terraform is trying to create the queue, the binding was being created.

**Comment by jason-archidera** [comment] 2017-03-17 18:55
Oops, yeah.  I should have added the admin user to the script above, sorry about that.  My environment already has it :)

When I point at RMQ 3.5.6 I get:
```
1 error(s) occurred:

* rabbitmq_queue.test_queue: 1 error(s) occurred:

* rabbitmq_queue.test_queue: json: cannot unmarshal string into Go struct field DetailedQueueInfo.consumer_utilisation of type float64
```

When I point at RMQ 3.6.6, it works fine.  We are planning a RMQ upgrade to 3.6.6 in the coming weeks, so maybe this will go away, but wanted to report since not all organizations will be running the latest.

**Comment by snowsky** [comment] 2017-03-17 19:17
Let me give it a shot for 3.5.6. Are you using the generic version?

**Comment by snowsky** [comment] 2017-03-17 19:24
I reproduced the exact error message you have got. I'll dig in to see where the problem is. Thanks.

**Comment by snowsky** [comment] 2017-03-17 20:20
Rabbitmq 3.6.5 fixed this issue:
http://rabbitmq.docs.pivotal.io/36/relnotes/release-notes-rabbitmq3.6.5.html
search for utilisation

**Comment by michaelklishin** [comment] 2017-03-17 21:14
RabbitMQ 3.6.5 change log can be found on GitHub (arguably in an easier to read form and with issue links): https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_5.

**Comment by michaelklishin** [comment] 2017-03-17 21:17
The issue in question is https://github.com/rabbitmq/rabbitmq-management/issues/26, which was fixed in RabbitMQ 3.5.7: https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_5_7. You are referring to Pivotal RabbitMQ distribution notes which used to have a different release schedule.

**Comment by snowsky** [comment] 2017-03-17 22:38
Thanks @michaelklishin, then @jason-archidera you will run into the other issue mentioned above. Let me put up a fix for it.

**Comment by stack72** [comment] 2017-03-20 10:27
Hi All

Are we saying this isn't a terraform issue?

Paul

**Comment by snowsky** [comment] 2017-03-20 13:56
@stack72 it is an issue of Rabbitmq API and got fixed in Rabbitmq 3.5.7. We can definitely work around this issue but I don't think it is necessary.

**Comment by stack72** [comment] 2017-03-20 13:57
Hi @snowsky 

Is there anything you need on the Terraform side for this?

Paul

**Comment by snowsky** [comment] 2017-03-20 18:02
@stack72 no, thanks.

**Closed** 2017-03-20 18:19 UTC
Labels: bug, provider/rabbitmq
