### ISSUE TITLE
A method to disable module conditionally

### ISSUE THREAD

**Issue by tyrsius** [hashicorp/terraform#18634] opened 2018-08-08 16:16 UTC
It has been over a year since [this issue](https://github.com/hashicorp/terraform/issues/953) was last updated (though its still open). Since it is locked I can't ask for an update in the issue.

The lack of this feature is getting very painful. If not via `count`, have any other methods to disable modules conditionally been developed?

Using `enable` on a module and then `count` internally doesn't work if there are `data` resources, since those resources don't exist.

**Comment by gtmtech** [comment] 2018-08-08 17:15
Agree that its sorely needed. 

In the meantime, I use count on all my resources in my module, including datasources. The only place I cant use count is in outputs (outputs dont support count (there should be another bug about this I feel) )

For places which dont support count, I end up using a locals {} block with a lookup(), providing a default if not existing to achieve the same in an output.

In this way I can make the whole module conditional, but it does involve some tricks. 

Let me know if you want an example.

**Comment by apparentlymart** [comment] 2018-08-09 18:35
Hi @tyrsius and @gtmtech,

No updates have been posted on the other issue because we've not yet got to that work. It's still planned to do, and you can see the initial groundwork for it being discussed in [the recent blog post on _For and For Each_](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each) (the section titled _Module `count` and `for_each`_)

We'll post in #953 again once that work has begun. Until then, since this issue is effectively a duplicate of #953 I'm going to close this one. The comments on that issue were closed because it seemed like useful discussion had concluded and it was just attracting "me too!" comments, which are not needed because we already understand the need and have a plan to address it.

**Closed by apparentlymart** 2018-08-09 18:35 UTC

**Comment by udayanms** [comment] 2019-09-26 00:50
> Agree that its sorely needed.
> 
> In the meantime, I use count on all my resources in my module, including datasources. The only place I cant use count is in outputs (outputs dont support count (there should be another bug about this I feel) )
> 
> For places which dont support count, I end up using a locals {} block with a lookup(), providing a default if not existing to achieve the same in an output.
> 
> In this way I can make the whole module conditional, but it does involve some tricks.
> 
> Let me know if you want an example.

Could you share your idea
