### ISSUE TITLE
aws_route_table doesn't store state for VPC peering connection

### ISSUE THREAD

**Issue by rcostanzo** [hashicorp/terraform#1725] opened 2015-04-29 04:38 UTC
using terraform 0.4.2

When you specify a VPC peering connection as the target of a route, it's final state isn't getting properly stored so terraform thinks it needs to re-add it each time.

Example output:

```
$terraform plan -out=myplan
Refreshing Terraform state prior to plan...

aws_route_table.vpn: Refreshing state... (ID: rtb-XXXX)
...
Path: terraform.tfplan.280415.211724

$terraform apply myplan
~ aws_route_table.vpn
    route.1777249909.cidr_block:                "" => "10.10.0.0/16"
    route.1777249909.gateway_id:                "" => "pcx-XXXX"
    route.1777249909.instance_id:               "" => ""
    route.1777249909.vpc_peering_connection_id: "" => ""
    route.780245749.cidr_block:                 "0.0.0.0/0" => "0.0.0.0/0"
    route.780245749.gateway_id:                 "igw-XXXX" => "igw-XXXX"
    route.780245749.instance_id:                "" => ""
    route.780245749.vpc_peering_connection_id:  "" => ""


Continue with apply? [y/N]y
aws_route_table.vpn: Modifying...
  route.1777249909.cidr_block:                "" => "10.10.0.0/16"
  route.1777249909.gateway_id:                "" => "pcx-XXXX"
  route.1777249909.instance_id:               "" => ""
  route.1777249909.vpc_peering_connection_id: "" => ""
  route.780245749.cidr_block:                 "0.0.0.0/0" => "0.0.0.0/0"
  route.780245749.gateway_id:                 "igw-XXXX" => "igw-XXXX"
  route.780245749.instance_id:                "" => ""
  route.780245749.vpc_peering_connection_id:  "" => ""
aws_route_table.vpn: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.



$terraform plan -out=myplan
Refreshing Terraform state prior to plan...

aws_route_table.vpn: Refreshing state... (ID: rtb-XXXX)
...

Path: terraform.tfplan.280415.211735

$terraform apply myplan
~ aws_route_table.vpn
    route.1777249909.cidr_block:                "" => "10.10.0.0/16"
    route.1777249909.gateway_id:                "" => "pcx-XXXX"
    route.1777249909.instance_id:               "" => ""
    route.1777249909.vpc_peering_connection_id: "" => ""
    route.780245749.cidr_block:                 "0.0.0.0/0" => "0.0.0.0/0"
    route.780245749.gateway_id:                 "igw-XXXX" => "igw-XXXX"
    route.780245749.instance_id:                "" => ""
    route.780245749.vpc_peering_connection_id:  "" => ""


Continue with apply? [y/N]y
aws_route_table.vpn: Modifying...
  route.1777249909.cidr_block:                "" => "10.10.0.0/16"
  route.1777249909.gateway_id:                "" => "pcx-XXXX"
  route.1777249909.instance_id:               "" => ""
  route.1777249909.vpc_peering_connection_id: "" => ""
  route.780245749.cidr_block:                 "0.0.0.0/0" => "0.0.0.0/0"
  route.780245749.gateway_id:                 "igw-XXXX" => "igw-XXXX"
  route.780245749.instance_id:                "" => ""
  route.780245749.vpc_peering_connection_id:  "" => ""
aws_route_table.vpn: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by johnbona** [comment] 2015-05-15 21:17
Same issue but with elastic network interfaces. Using terraform 0.5.1.

**Comment by CpuID** [comment] 2015-09-21 05:18
Pretty sure I am seeing this with vpc_peering_connection_id on aws_route_table, when the aws_route_table resides in a child module.

Example:

```
~ module.childmodule.aws_route_table.non_production
    route.#:                                    "1" => "2"
    route.1282208211.cidr_block:                "0.0.0.0/0" => "0.0.0.0/0"
    route.1282208211.gateway_id:                "igw-xxxxxx" => "igw-xxxxxx"
    route.1282208211.instance_id:               "" => ""
    route.1282208211.network_interface_id:      "" => ""
    route.1282208211.vpc_peering_connection_id: "" => ""
    route.3820181916.cidr_block:                "" => "10.x.0.0/16"
    route.3820181916.gateway_id:                "" => ""
    route.3820181916.instance_id:               "" => ""
    route.3820181916.network_interface_id:      "" => ""
    route.3820181916.vpc_peering_connection_id: "" => "pcx-xxxxxx"
    tags.#:                                     "0" => "1"
    tags.Name:                                  "" => "Non Production Main"
```

When running terraform plan on the child module standalone, no changes appear to require applying for this resource.

**Comment by catsby** [comment] 2015-11-17 16:23
Hey all – I'm unable to reproduce this issue at this time, so I'm going to close this. I used the following configuration and had no issue:

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name = "tf-test-3519"
  }
}

resource "aws_vpc" "bar" {
  cidr_block = "10.1.0.0/16"

  tags {
    Name = "tf-test-3519"
  }
}

resource "aws_internet_gateway" "gw" {
  vpc_id = "${aws_vpc.default.id}"

  tags {
    Name = "tf-test-3519"
  }
}

resource "aws_internet_gateway" "ogw" {
  vpc_id = "${aws_vpc.bar.id}"

  tags {
    Name = "tf-test-3519"
  }
}

resource "aws_vpc_peering_connection" "foo" {
  vpc_id        = "${aws_vpc.default.id}"
  peer_vpc_id   = "${aws_vpc.bar.id}"
  peer_owner_id = "<my account it>"

  tags {
    foo = "bar"
  }

  auto_accept = true
}

resource "aws_route_table" "priv1" {
  vpc_id = "${aws_vpc.default.id}"

  route {
    cidr_block                = "0.0.0.0/0"
    vpc_peering_connection_id = "${aws_vpc_peering_connection.foo.id}"
  }

  tags {
    Name = "aws_route_table"
  }
}
```

If you feel I'm missing something, please modify my example config to demonstrate the issue and I'll take another look.

Thanks!

**Closed by catsby** 2015-11-17 16:23 UTC
Labels: bug, provider/aws
