### ISSUE TITLE
aws_elasticache_cluster does not support AZMode

### ISSUE THREAD

**Issue by silvamerica** [hashicorp/terraform#4438] opened 2015-12-24 02:11 UTC
Per http://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html, you can create an Elasticache cluster in a single AZ or "cross-az", where nodes will be scattered across availability zones.

**Comment by kamatama41** [comment] 2015-12-25 07:32
:+1: I had same problem.

**Comment by radeksimko** [comment] 2015-12-28 09:42
Hi @silvamerica 
isn't this a duplicate of https://github.com/hashicorp/terraform/issues/4361 ?

**Comment by silvamerica** [comment] 2015-12-28 20:06
@radeksimko No it is not. Replication groups are only supported for Redis, not for Memcache. Creating a Replication Group with automatic failover will automatically enable Multi-AZ mode for Redis Elasticache clusters. However for Memcache Clusters (or if you are not doing a Replication Group), you have to set Multi-AZ manually.

**Closed** 2016-01-11 21:46 UTC
Labels: enhancement, provider/aws

**Comment by catsby** [comment] 2016-01-11 21:47
I merged #4631 which should address this, let us know if you need anything else!
