### ISSUE TITLE
terraform apply failed, Error: Can't change variable when applying a saved plan

### ISSUE THREAD

**Issue by FeiWangTyro** [hashicorp/terraform#36183] opened 2024-12-10 00:32 UTC
### Terraform Version

```shell
Run hashicorp/setup-terraform@v3
  with:
    cli_config_credentials_hostname: app.terraform.io
    terraform_version: latest
    terraform_wrapper: true
```

### Terraform Configuration Files

```terraform
...terraform config...
```
we se the value of variable `account_id_development` in the tfvars file, the value in plan and apply are different.

### Debug Output

The variable _`account_id_development`_ cannot be set using the -var and
-var-file options when applying a saved plan file, because a saved plan
includes the variable values that were set when it was created.

### Expected Behavior

terraform should apply the plan

### Actual Behavior

terraform failed to apply, `Error: Can't change variable when applying a saved plan`

### Steps to Reproduce

we set the value of variable `account_id_development` in the tfvars file, the values of the variable in plan and apply are different.

**Comment by liamcervante** [comment] 2024-12-10 07:56
Duplicate of #36177

**Closed by liamcervante** 2024-12-10 07:56 UTC
Labels: bug, new

**Comment by crw** [comment] 2024-12-10 17:05
Thanks for this @FeiWangTyro, turned out to be a new issue discovery. Appreciate the extra effort here!
