### ISSUE TITLE
aws_elastic_ip triggers public_ip change on aws_instance which requires refresh to see

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2585] opened 2015-07-01 11:38 UTC
When using a template to output the public IP of an instance, where the instance is attached to an elastic IP, the wrong IP gets reported:

We have a template thus:

```
template-ssh_config:

Host web-proxy
  Hostname        ${web_proxy_public_ip}
```

And in terraform:

```
resource "template_file" "ssh_config" {
    depends_on = ["aws_eip.web-proxy"]
    filename = "template-ssh_config"
    vars {
        web_proxy_public_ip              = "${aws_instance.web-proxy.public_ip}"
   }
}
```

Notice the depends_on. So I now have my instance web-proxy, and my elastic IP resource.

```
resource "aws_instance" "web-proxy" {
    ...
    associate_public_ip_address = true
    ...
}

resource "aws_eip" "web-proxy" {
    instance = "${aws_instance.web-proxy.id}"
    vpc      = true
}
```

When the template gets written, because of the depends_on, I would expect the template output to have the elastic IP. But the first time terraform apply, it outputs the public_ip, which is quickly overridden in AWS by the elastic IP, and is therefore redundant.

The resource should wait for the elastic IP to be assigned before the template output is output so that it is factually correct and doesn't require a further terraform apply to make it correct.

**Comment by pikeas** [comment] 2015-07-01 23:43
Move the `depends_on` onto the instance, or set `web_proxy_public_ip` to `${aws_eip.web-proxy.pubic_ip}`?

**Comment by gtmtech** [comment] 2015-07-02 14:39
This is still a bug that needs fixing, but thanks for the info @pikeas , as the aws_eip.web-proxy.public_ip is a good workaround for us right now.

**Comment by mitchellh** [comment] 2016-08-22 08:02
Hm, so I've been thinking of this issue and while it feels weird I do think it is working as intended in this specific case. However, I don't disagree that the intended effect is not done.

Terraform only stores the attributes of a resource once they finish running, so while Terraform _is_ reading those values when it is writing the template, it is reading the values from when _that resource_ was created/refreshed, which happens to be before the EIP is assigned and therefore the wrong value.

I don't think there is a good way to solve this because if you generalize the problem it becomes pretty hairy:

> A resource may cause an attribute change in another resource.

This sort of logic is non-trivial to implement. I think if it were to be implemented the ideal way would be that resources could hint to Terraform that after it is created a certain set of resources _if they are managed by Terraform_ should be refreshed. I don't think thats an _insane_ feature request but that certainly changes the nature of this bug.

I'm going to retag this as an enhancement and change the title to reflect this.

**Comment by apparentlymart** [comment] 2018-11-06 21:07
Hi all! Sorry for the long silence here.

As Mitchell explained several years ago, this sort of thing is difficult to model since it violates Terraform's fundamental processing model that processes on resource at a time in dependency graph order.

Given that this sort of situation is rare in practice (based on our experience from building many other resources), increasing the complexity of Terraform's model to accommodate it doesn't seem like the right tradeoff. Instead, this is a constraint that provider developers must keep in mind when designing resources, and in the rare case where a technical solution is impossible -- like this one -- make sure that the unusual interaction is properly documented and offer an alternative approach.

I believe the alternative approach in this case would be to access the IP address via the `aws_eip` resource instead of via the `aws_instance` resource, thus making it explicit that is the elastic IP address that will be used.

I'm going to close this out now, since we don't plan to take any action here for the foreseeable future. If we find a different to way to address this that has some different tradeoffs, we can open a new issue to discuss it later.

**Closed by apparentlymart** 2018-11-06 21:07 UTC
Labels: core, enhancement
