### ISSUE TITLE
terraform v0.9.10 doesn't work on atlas / terraform enterprise

### ISSUE THREAD

**Issue by clarkperkins** [hashicorp/terraform#15438] opened 2017-06-30 00:17 UTC
terraform 0.9.10 consistently crashes during an apply with the following error when running with the atlas backend:

```
Terraform v0.9.10

Downloading remote modules...
plan state and ContextOpts state are not equal
```

### Terraform Version

terraform v0.9.10

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior
What should have happened?

### Actual Behavior

terraform crashed during an apply

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I noticed in the release notes for 0.9.10 that it included a bug fix for the atlas backend, so I figured I should update.  However, after updating I started getting the above error.  I have not tried running an apply locally, just in terraform enterprise.  I was able to downgrade to 0.9.9 for now.

**Comment by apparentlymart** [comment] 2017-06-30 17:15
Thanks for reporting this @clarkperkins, and sorry for the regression.

This seems to be the same issue being discussed in #15433, so I'm going to close this just to consolidate discussion over there. We're actively looking into this and hope to have an explanation and fix soon.

**Closed by apparentlymart** 2017-06-30 17:15 UTC
Labels: atlas, bug

**Comment by clarkperkins** [comment] 2017-06-30 18:32
Ah, thank you - I must have missed that ticket when I initially looked for a report of this bug.
