### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gdoumenc** [hashicorp/terraform#17258] opened 2018-01-31 18:34 UTC
On version 0.11.2, after a refresh :
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb48812]

goroutine 344 [running]:
github.com/hashicorp/terraform/terraform.(*State).Lock(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:95 +0x22
github.com/hashicorp/terraform/terraform.(*State).SameLineage(0x0, 0xc420425980, 0xc42058de00)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:628 +0x34
github.com/hashicorp/terraform/state/remote.(*State).WriteState(0xc42058def0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/state/remote/state.go:37 +0x10a
github.com/hashicorp/terraform/backend/local.(*Local).opRefresh(0xc4205ba0b0, 0x3eb4860, 0xc420014100, 0xc42058ef00, 0xc42058dec0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_refresh.go:115 +0x465
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opRefresh)-fm(0x3eb4860, 0xc420014100, 0xc42058ef00, 0xc42058dec0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:230 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc4205ba0b0, 0xc4205734a0, 0xc420573490, 0x3eb4860, 0xc420014100, 0xc42058ef00, 0xc42058dec0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:254 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:251 +0x18a

**Comment by jbardin** [comment] 2018-01-31 19:00
Thanks for filing the issue!

Duplicate of #17152, and fixed in master.

**Closed by jbardin** 2018-01-31 19:00 UTC
Labels: bug, crash

**Comment by gdoumenc** [comment] 2018-02-01 08:10
Sorry haven't see the duplicate..
