### ISSUE TITLE
objects created by ternary operator change value types to string

### ISSUE THREAD

**Issue by AFriemann** [hashicorp/terraform#33480] opened 2023-07-06 11:17 UTC
### Terraform Version

```shell
Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

### Terraform Configuration Files

```terraform
variable "repository_names" {
  description = "Names of repositories."
  type = map(object({
    replication_regions = optional(set(string))
    scan_on_push        = optional(bool)
    mutable             = optional(bool)
    lambda              = optional(bool)
    allowed_push_arns   = optional(set(string))
    expire_by           = optional(string)
    expire_count        = optional(number)
    expire_age          = optional(number)
    untagged_expire_age = optional(number)
    tags                = optional(map(string))
  }))

  default = {
    web = {}
  }

  validation {
    condition     = alltrue([for repo, config in var.repository_names : try(contains(["age", "count"], config.expire_by), true)])
    error_message = "expire_by must be either 'age' or 'count'."
  }
}

variable "default_expire_age" {
  description = "How old images can be in days by default before they are expired (set to 0 to disable)."
  type        = number
  default     = 0
}

variable "default_expire_count" {
  description = "How much images will be kept if not set individually by repo."
  type        = number
  default     = 300
}

variable "default_untagged_expire_age" {
  description = "Maximum age of untagged images in days."
  type        = number
  default     = 1
}

variable "default_expire_by" {
  description = "Expiry rule for images, either `age` or `count`."
  type        = string
  default     = "age"

  validation {
    condition     = contains(["age", "count"], var.default_expire_by)
    error_message = "default_expire_by must be either 'age' or 'count'."
  }
}

locals {
  expiration_policies = { for repo, config in var.repository_names :
    repo => [
      {
        rulePriority = 1,
        description  = "Delete untagged images after ${var.default_untagged_expire_age} days.",
        selection = {
          tagStatus   = "untagged",
          countType   = "sinceImagePushed",
          countUnit   = "days",
          countNumber = coalesce(config.untagged_expire_age, var.default_untagged_expire_age),
        },
        action = { type = "expire" }
      },
      {
        rulePriority = 2,
        description  = "Expire images by ${coalesce(config.expire_by, var.default_expire_by)}.",
        selection = coalesce(config.expire_by, var.default_expire_by) == "age" ? {
          tagStatus   = "any",
          countType   = "sinceImagePushed",
          countNumber = tonumber(config.expire_age != null ? config.expire_age : var.default_expire_age),
          countUnit   = "days",
          } : {
          tagStatus   = "any",
          countType   = "imageCountMoreThan",
          countNumber = tonumber(config.expire_count != null ? config.expire_count : var.default_expire_count),
        },
        action = { type = "expire" }
      },
    ]
  }
}

resource "aws_ecr_lifecycle_policy" "this" {
  for_each = local.expiration_policies

  repository = each.key
  policy     = jsonencode({ rules = each.value })
}
```

### Debug Output

This is from a bigger module, I can provide a trace log if actually necessary when I get some help identifying the actually relevant parts.

### Expected Behavior

Both `selection` branches should result in something like this

```terraform
  # aws_ecr_lifecycle_policy.this["web"] will be created
  + resource "aws_ecr_lifecycle_policy" "this" {
      + id          = (known after apply)
      + policy      = jsonencode(
            {
              + rules = [
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Delete untagged images after 1 days."
                      + rulePriority = 1
                      + selection    = {
                          + countNumber = 1
                          + countType   = "sinceImagePushed"
                          + countUnit   = "days"
                          + tagStatus   = "untagged"
                        }
                    },
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Expire images by age."
                      + rulePriority = 2
                      + selection    = {
                          + countNumber = 30
                          + countType   = "sinceImagePushed"
                          + countUnit   = "days"
                          + tagStatus   = "any"
                        }
                    },
                ]
            }
        )
      + registry_id = (known after apply)
      + repository  = "web"
    }
```

### Actual Behavior

Instead the `countNumber` value is cast to a string. Note the difference in behaviour between the two objects as well.

```terraform
  # aws_ecr_lifecycle_policy.this["web"] will be created
  + resource "aws_ecr_lifecycle_policy" "this" {
      + id          = (known after apply)
      + policy      = jsonencode(
            {
              + rules = [
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Delete untagged images after 1 days."
                      + rulePriority = 1
                      + selection    = {
                          + countNumber = 1
                          + countType   = "sinceImagePushed"
                          + countUnit   = "days"
                          + tagStatus   = "untagged"
                        }
                    },
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Expire images by age."
                      + rulePriority = 2
                      + selection    = {
                          + countNumber = "30"
                          + countType   = "sinceImagePushed"
                          + countUnit   = "days"
                          + tagStatus   = "any"
                        }
                    },
                ]
            }
        )
      + registry_id = (known after apply)
      + repository  = "web"
    }
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

It took me a while to figure out what was causing this behaviour. After a lot of testing using `tonumber` and different variations of `coalesce` and ternary operators on the individual field, I realized that the cause for this seems to be the ternary operator on the `selection` key that creates the object. Removing the ternary if and only taking one branch results in the `countNumber` field being a number as expected. I tried different variations on this (i.e. moving the ternary operator to the list and creating the entire object based on the `expire_by` variable) but the behaviour seems consistent. Explicitly casting the value using `tonumber` makes no difference.

**Comment by AFriemann** [comment] 2023-07-06 11:55
this seems to function as a workaround:

```terraform
      {
        rulePriority = 2,
        description  = "Expire images by ${coalesce(config.expire_by, var.default_expire_by)}.",
        selection = merge(
          {
            tagStatus   = "any",
            countType   = "sinceImagePushed",
            countNumber = coalesce(config.expire_by, var.default_expire_by) == "age" ? coalesce(config.expire_age, var.default_expire_age) : coalesce(config.expire_count, var.default_expire_count),
          },
          coalesce(config.expire_by, var.default_expire_by) == "age" ? {
            countUnit = "days",
          } : {},
        ),
        action = { type = "expire" }
      }
```

**Comment by jbardin** [comment] 2023-07-06 13:38
Hi @AFriemann,

Because a conditional expression must always evaluate to a single type, both the true and false branches must to have equal types, or be converted to a single unified type. The true and false branches of your conditional expression have different object types, and when Terraform attempts to unify these object types with different attribute sets the only available option is to use a `map(string)`, converting the numbers along the way (the fact that Terraform will freely convert numbers to strings at all is more of a legacy design decision that we need to maintain for compatibility).

If you use the same object type in both cases the conditional evaluation should be able to maintain the type of the attributes:

```
        selection = coalesce(config.expire_by, var.default_expire_by) == "age" ? {
          tagStatus   = "any",
          countType   = "sinceImagePushed",
          countNumber = tonumber(config.expire_age != null ? config.expire_age : var.default_expire_age),
          countUnit   = "days",
          } : {
          tagStatus   = "any",
          countType   = "imageCountMoreThan",
          countNumber = tonumber(config.expire_count != null ? config.expire_count : var.default_expire_count),
          countUnit = tostring(null),
        },
```

(the `tostring` is probably not needed and the `null` type can be inferred, but being extra explicit doesn't hurt here when dealing with structural types).

Since Terraform is working as intended here, this does not represent a bug in the CLI so I'm going to close this out for now. 
If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more users ready to help.

Thanks!

**Closed by jbardin** 2023-07-06 13:38 UTC
Labels: bug, new

**Comment by AFriemann** [comment] 2023-07-06 14:24
Oh wow that makes a lot of sense. Unfortunately your proposed solution doesn't work (that was my initial attempt) since AWS seems to validate the schema of this selection key and the provider apparently sends `countUnit = null` in it's request. I'll open an issue on the AWS provider for that, though.

Thanks for the clear explanation!
