### ISSUE TITLE
Crash while planing, AzureRM provisioner

### ISSUE THREAD

**Issue by edevil** [hashicorp/terraform#6935] opened 2016-05-30 12:44 UTC
### Terraform Version
`Terraform v0.6.16`

### Debug Output

[crash.log.txt](https://github.com/hashicorp/terraform/files/289554/crash.log.txt)

**Comment by stack72** [comment] 2016-05-31 13:18
Hi @edevil 

I am going to consolidate this and #6936 into a single issue as they are exactly the same it seems. Please can you post the terraform config you are using (minus any secrets!)

Please can you also tell me how you generated the AzureRM credentials you are using

Thanks

Paul

**Comment by edevil** [comment] 2016-05-31 14:29
I don't have any specific config besides the credentials which are stored in a separate vars file. I used this guide to generate them: https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/

**Comment by stack72** [comment] 2016-06-02 12:14
Hi @edevil 

I am not sure what you mean by a separate file? Is it that you have the following make up:

```
provider "azurerm" {
  subscription_id = "{var.subscription_id}"
  client_id       = "{var.client_id}"
  client_secret   = "{var.client_secret}"
  tenant_id       = "{var.tenant_id}"
}
```

And then when you are calling `terraform plan` you are passing a variables file?

Paul

**Comment by edevil** [comment] 2016-06-02 13:35
I have a terraform.tfvars file that Terraform automatically loads.

**Comment by stack72** [comment] 2016-06-02 13:37
@edevil and is the way I created the provider block how you did it?

**Comment by edevil** [comment] 2016-06-02 14:08
@stack72 yes

**Comment by stack72** [comment] 2016-06-02 14:29
Hi @edevil 

I cannot reproduce this crash using the variables directly. I have the following in a main.tf file:

```
variable "ARM_SUBSCRIPTION_ID" {}
variable "ARM_CLIENT_ID" {}
variable "ARM_CLIENT_SECRET" {}
variable "ARM_TENANT_ID" {}

provider "azurerm" {
  subscription_id = "${var.ARM_SUBSCRIPTION_ID}"
  client_id       = "${var.ARM_CLIENT_ID}"
  client_secret   = "${var.ARM_CLIENT_SECRET}"
  tenant_id       = "${var.ARM_TENANT_ID}"
}
```

Then I have the associated values in terraform.tfvars:

```
ARM_SUBSCRIPTION_ID = "xxxxx"
ARM_CLIENT_ID = "xxxxxx"
ARM_CLIENT_SECRET = "xxxxxxx"
ARM_TENANT_ID = "xxxxxxx"
```

As this happened with both plan and apply for you (the other issue you opened) then it *has* to be down to the credentials themselves. Please follow the guide we [created in the docs](https://www.terraform.io/docs/providers/azurerm/index.html), called `Creating Credentials` to ensure the correct credentials are created

Thanks

Paul

**Comment by edevil** [comment] 2016-06-02 14:34
This error is not deterministic. Normally I don't get this error, and retrying always fixes the problem for me when it happens. So I guess the bug must be in the retry logic or some error that the Azure API sometimes returns.

**Comment by stack72** [comment] 2016-06-09 22:05
Hi @edevil 

I cannot reproduce this at all - you are seeing something very weird here :(

I have tried everything i can and it just doesn't seem to want to crash for me

If you can, please can you try and recreate this again? 

P.

**Comment by stack72** [comment] 2016-06-25 13:03
Hi @edevil 

I am going to close this out. I can't recreate it I'm afraid and believe that the changes we have made in Terraform 0.7 have fixed the issue

Please do comment if this is not the case

Paul

**Closed by stack72** 2016-06-25 13:03 UTC
Labels: bug, crash, provider/azurerm, waiting-response
