### ISSUE TITLE
have first-class enabled/disabled for modules and resources

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform#24995] opened 2020-05-19 22:03 UTC
### Current Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.50.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Use-cases

Give the user of your module the option to disable creation of certain resources or modules

### Attempted Solutions

Use "count" (or different name) where 0 means disabled, and 1 means enabled. 
This solution works but causes the resource to become a list of resources. Eg
```
resource "abc_type" "something" {
   count = var.enabled ? 0 : 1
   ...
}
```
causes abc_type.something to be a list of length 1 if "enabled" is true. This means everywhere in the code that this single resource is referenced, a '[0]' must be appended. This adds noise to the code and obfuscates intent. 

The usage of "count" meta-variable has worked but it is now time for HCL2 resources to get a proper "enabled" meta-variable. 

### Proposal

HCL2 should support the following syntax: 
```
resource "abc_type" "something" {
   enabled = var.enabled
   ...
}
```

If enabled is false, the resource should not be instantiated.

**Comment by NickMetz** [comment] 2020-05-28 14:15
Hi @schollii,
agree with you, this would be a cool feature. But it seems your request is duplicate of #21953.

**Comment by schollii** [comment] 2020-06-08 23:56
Awesome, thanks for the info I have added my vote.

**Closed** 2021-02-26 14:50 UTC
Labels: enhancement
