### ISSUE TITLE
datasources not expected by 0.12upgrade

### ISSUE THREAD

**Issue by maartenvanderhoef** [hashicorp/terraform#19186] opened 2018-10-24 07:36 UTC
### Terraform Version
```
terraform -v
Terraform v0.12.0
+ provider.aws (unversioned) <- = core-v0.12-alpha1
+ provider.template (unversioned) <- = core-v0.12-alpha1
```

### Terraform Configuration Files
```hcl
data "aws_lb" "main" {
  arn = "${var.lb_arn}"
}
```

### Expected Behavior
When running `terraform 0.12upgrade` I am getting a warning 

```
Warning: Unsupported root block type

  on main.tf line 1, in data "aws_lb" "main":
   1: data "aws_lb" "main" {

The block type "data" is not expected here, so its content was not upgraded.
```

**Comment by apparentlymart** [comment] 2018-10-24 14:35
Hi @maartenvanderhoef! Thanks for reporting this.

The upgrade tool is not yet complete in current master, so this is expected. The tool will be completed before we reach the final v0.12 release.

**Comment by maartenvanderhoef** [comment] 2018-10-24 15:10
Thanks @apparentlymart ! Can't wait :-)

**Comment by minamijoyo** [comment] 2018-10-25 15:17
Hi @maartenvanderhoef @apparentlymart,

I encountered the same problem in the `provider` block.
Would you keep this issue open until the problem is fixed?
It is beneficial for contributors who are participating in the v0.12 test to understand unimplemented features.

**Comment by minamijoyo** [comment] 2018-10-26 01:30
@maartenvanderhoef Thanks!

**Comment by apparentlymart** [comment] 2018-12-18 02:31
In v0.12.0-alpha4 the upgrade tool can pass through most constructs and apply a small number of initial upgrade rules. It's still not ready for general use though: our target is for beta1 to be the first release where we consider the upgrade tool ready to use.

With that said, the tool now has enough functionality to pass through both `provider` and `data` blocks, along with all of the other top-level block types. Its ruleset is not yet complete for details within those blocks but we'll track those with separate issues as we work on them.

I verified the support of `data` and `provider` blocks by upgrading the following configuration:

```hcl
provider "aws" {
  region = "us-west-2"
}

data "aws_lb" "main" {
  arn = "${var.lb_arn}"
}
```

The tool made the following change for this relatively-simple configuration:

```diff
--- data-resource-upgrade.tf.orig	2018-12-17 18:27:39.141737728 -0800
+++ data-resource-upgrade.tf	2018-12-17 18:27:46.833879952 -0800
@@ -3,5 +3,6 @@
 }
 
 data "aws_lb" "main" {
-  arn = "${var.lb_arn}"
+  arn = var.lb_arn
 }
```

Since the particular problems discussed here are now addressed, I'm going to close this out. Thanks for reporting this!

**Closed by apparentlymart** 2018-12-18 02:31 UTC
