### ISSUE TITLE
changing plugin_cache_dir on windows does not stop terraform from downloading providers in the init folder

### ISSUE THREAD

**Issue by dss010101** [hashicorp/terraform#33791] opened 2023-09-03 00:45 UTC
### Terraform Version

```shell
Terraform v1.5.6
on windows_amd64
+ provider registry.terraform.io/azure/azapi v0.4.0
+ provider registry.terraform.io/hashicorp/azurerm v3.71.0
```

### Terraform Configuration Files

NONE

### Debug Output

NONE

### Expected Behavior

NONE

### Actual Behavior

Im following the intructions here: https://developer.hashicorp.com/terraform/cli/config/config-file 
to avoid having to download these huge providers multiple times in each infrastructure folder i create.   

I have created a terraform.rc at %APPDATA%.
I added the following to the file:
`plugin_cache_dir = "$APPDATA\\.terraform.d\\plugin-cache"`

When i do terraform init, i get:
`Error: The specified plugin cache dir C:\Users\user1\AppData\Roaming\.terraform.d\plugin-cache cannot be opened: CreateFile C:\Users\user1\AppData\Roaming\.terraform.d\plugin-cache: The system cannot find the path specified.`

So i create the \.terraform.d\plugin-cache folder manually.  Then do another init from one of my folders with tf files.
Terraform now downloads the provider files in this folder AND the 'plugin_cache_dir' path i specified above in the terraform.rc file.   bit frustrating...what am i doing wrong?

### Steps to Reproduce

terraform init

**Comment by crw** [comment] 2023-09-07 23:02
Thanks for this submission! This may be a bug or it may be an issue of usage. I would recommend also asking in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) if you have not already. There are more people there who could hopefully help answer your question (or help confirm that it is a bug in Terraform). Thanks!

**Comment by tnc-tschmidt** [comment] 2023-10-26 17:21
This is basically a dupe of this bug: https://github.com/hashicorp/terraform/issues/32936

Short answer is you need to have a .terraform.lock.hcl file populated with the hashes in order for the plugin cache to be used. Nope, doesn't make much sense to me either...

**Comment by crw** [comment] 2023-10-26 21:52
Thanks! I will close this as a duplicate of #32936.

**Closed by crw** 2023-10-26 21:52 UTC
Labels: bug, windows, new
