### ISSUE TITLE
Module dependencies

### ISSUE THREAD

**Issue by toddrosner** [hashicorp/terraform#5234] opened 2016-02-20 22:44 UTC
I'm working with nested modules and would like to control the order of some resources through dependencies. There's no problem doing this in a monolith setup, but when breaking the stack into nested modules, the dependencies no longer work and it doesn't seem like there's any way to get this to work using outputs, variables, etc.

Below is a typical plan error I'll receive when creating a dependency on a resource in another module.

```
Error configuring: 1 error(s) occurred:

* aws_network_interface.role: missing dependency: aws_security_group.role.id
```

Is there any way to get dependencies to work across modules?

**Comment by mward29** [comment] 2016-04-06 19:15
+1 - I'm running into this as well.

**Comment by majuscule** [comment] 2016-08-15 18:16
I believe that this is a dupe of issue https://github.com/hashicorp/terraform/issues/1178 (unfortunately unresolved for a year+).

**Comment by mitchellh** [comment] 2016-11-11 06:55
It is a dup, and something I plan on looking at soon!

**Closed by mitchellh** 2016-11-11 06:55 UTC
Labels: core, enhancement
