### ISSUE TITLE
Vendor dependencies (or use some sort of dependency version tool)

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#2964] opened 2015-08-07 17:47 UTC
Not vendoring terraform's dependencies with a tool like `gb` or `godep` makes it very difficult to build any other versions of terraform other than `HEAD` because it is impossible to know what versions the dependencies should be at (there are often incompatibilities).

I saw #1235, but I don't think it is reasonable to wait until Go sorts out its "official" dependency management since this could take at least another 6 months (note that issue was closed almost 5 months ago so it'll have been a year since then that it is addressed). The unreleased Go 1.5 introduces the `-vendor` experiment, but it is unclear how long it would take before it is considered "canonical" or even if the experiment will be successful.

Thus I think it is reasonable to start vendoring now with either the `-vendor` experiment or a tool like `gb` or `godep` and the project can switch over to whatever ends up being the canonical dependency management approach whenever that happens.

Thoughts?

**Comment by phinze** [comment] 2015-08-07 21:36
Hi @jszwedko,

Since `v0.6.0` we do use `godep` to capture and vendor dependencies at release time. They're bundled in the `-src.tar.gz` attached to each release:

https://github.com/hashicorp/terraform/releases

I understand your position completely. I'd really like to get to the point where every Terraform commit is easily built by anybody at any point in the future.

The conflicting issue here is source tree churn. On a highly active project like this (with a highly active tree of dependencies), the current generation of Go dependency management tools inevitably sign us up to spend engineering hours on [issues like this](https://github.com/hashicorp/vault/pull/501).

The position we're taking is that at this point in Terraform's life, those engineering hours are better spent pushing the project forward--at the expense of easily reproducible builds at any commit point--while the Go tooling matures.

We feel like the capture-at-release strategy strikes a nice balance for now between these two conflicting concerns. To that end, I'm going to close this issue, but I'm happy to continue to discuss further with you on this thread.

**Closed by phinze** 2015-08-07 21:36 UTC
Labels: question

**Comment by jszwedko** [comment] 2015-08-07 22:30
@phinze I completely missed that dependencies were being released alongside the source for 0.6.0+ -- that is definitely a step forward. I still think it would be nice to be able to build any given commit, but I understand that it is overhead for the development process given the current of the tooling so this compromise seems reasonable for now.

Thank you for the response!
