### ISSUE TITLE
Unable to deploy Azure Lighthouse using Terraform and ARM

### ISSUE THREAD

**Issue by AmineBenbouzid** [hashicorp/terraform#26255] opened 2020-09-16 09:27 UTC
Hi,

A few days ago I tried to deploy azure lighthouse using ARM and running the template with Terraform.

### Terraform Version

Terraform v0.13.1
provider registry.terraform.io/hashicorp/azurerm v2.0.0

### Terraform Configuration Files

```terraform
# Configure the Azure Provider
provider azurerm {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "2.0.0"
  features {}
}

resource "azurerm_resource_group" "azurelighthousedeploy" {
  name     = "lighthouseRg"
  location = "North Europe"
}
resource "azurerm_template_deployment" "azurelighthousedeployment" {

  name                = "azurelighthousedeployment"
  resource_group_name = azurerm_resource_group.azurelighthousedeploy.name

  template_body = <<DEPLOY

{
    "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "mspName": {
            "value": "Company"
        },
        "mspOfferDescription": {
            "value": "Company - Global Managed Services"
        },
        "managedByTenantId": {
            "value": "yyyyyyy-yyyyyyyy-yyyyyyyyy"
        },
        "authorizations": {
            "value": [
                {        
                "principalId": "yyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyy",
                "principalIdDisplayName": "team1",
                "roleDefinitionId": "yyyyyy-yyyy-yyyy-yyyy-yyyyyyyy"
                },
                {        
                "principalId": "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyy",
                "principalIdDisplayName": "team2",
                "roleDefinitionId": "yyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyy"
                }
            ]
        }
    }
}

DEPLOY


  # these key-value pairs are passed into the ARM Template's `parameters` block
  parameters = {
    "storageAccountType" = "Standard_GRS"
  }

  deployment_mode = "Incremental"
}


```

### Actual Behavior

After the 'terraform apply'

Error: Error Expanding the template_body for Azure RM Template Deployment

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
2. `terraform apply`

**Comment by AmineBenbouzid** [comment] 2020-09-16 09:50
> Hi,
> 
> A few days ago I tried to deploy azure lighthouse using ARM and running the template with Terraform.
> 
> ### Terraform Version
> Terraform v0.13.1
> provider registry.terraform.io/hashicorp/azurerm v2.0.0
> 
> ### Terraform Configuration Files
> ```terraform
> # Configure the Azure Provider
> provider azurerm {
>   # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
>   version = "2.0.0"
>   features {}
> }
> 
> resource "azurerm_resource_group" "azurelighthousedeploy" {
>   name     = "lighthouseRg"
>   location = "North Europe"
> }
> resource "azurerm_template_deployment" "azurelighthousedeployment" {
> 
>   name                = "azurelighthousedeployment"
>   resource_group_name = azurerm_resource_group.azurelighthousedeploy.name
> 
>   template_body = <<DEPLOY
> 
> {
>     "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentParameters.json#",
>     "contentVersion": "1.0.0.0",
>     "parameters": {
>         "mspName": {
>             "value": "Company"
>         },
>         "mspOfferDescription": {
>             "value": "Company - Global Managed Services"
>         },
>         "managedByTenantId": {
>             "value": "yyyyyyy-yyyyyyyy-yyyyyyyyy"
>         },
>         "authorizations": {
>             "value": [
>                 {        
>                 "principalId": "yyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyy",
>                 "principalIdDisplayName": "team1",
>                 "roleDefinitionId": "yyyyyy-yyyy-yyyy-yyyy-yyyyyyyy"
>                 },
>                 {        
>                 "principalId": "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyy",
>                 "principalIdDisplayName": "team2",
>                 "roleDefinitionId": "yyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyy"
>                 }
>             ]
>         }
>     }
> }
> 
> DEPLOY
> 
> 
>   # these key-value pairs are passed into the ARM Template's `parameters` block
>   parameters = {
>     "storageAccountType" = "Standard_GRS"
>   }
> 
>   deployment_mode = "Incremental"
> }
> ```
> 
> ### Actual Behavior
> After the 'terraform apply'
> 
> Error: Error Expanding the template_body for Azure RM Template Deployment
> 
> ### Steps to Reproduce

> 
> 1. `terraform init`
> 2. `terraform plan`
> 3. `terraform apply`

**Comment by alisdair** [comment] 2020-09-17 13:44
[The source of this error is in the AzureRM provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/cffbabbcdf733487b7e926ca0e0fc5d932b2a12c/azurerm/internal/services/resource/resource_arm_template_deployment.go#L296-L302), not Terraform core. As a result I believe the issue here (if any) is in the provider.

However, that code should only fail if your `template_body` is invalid JSON. The configuration you've given here seems to be a valid JSON string, so I don't think it should have failed. Is it possible there was a typo which you corrected before reporting the bug?

As a side note, when creating JSON for resource attributes, we strongly recommend [using the `jsonencode` function](https://www.terraform.io/docs/configuration/functions/jsonencode.html). This allows you to write your data structure in native HCL, have your text editor and Terraform's parser validate it for correctness, and rely on Terraform to encode the JSON string. This allows you to find typos and other mistakes earlier.

I don't believe this is a bug in Terraform core, so I'm going to close it. If you're able to reproduce the same error, [please report the bug in the provider repo](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Bug_Report.md). Thanks!

**Closed by alisdair** 2020-09-17 13:44 UTC
Labels: bug, new
