### ISSUE TITLE
Crash while running Terraform Refresh

### ISSUE THREAD

**Issue by wsmithCTP** [hashicorp/terraform#17194] opened 2018-01-25 12:38 UTC
### Terraform Version

```
Terraform v0.11.2
+ provider.aws v1.7.1
+ provider.template v1.0.0
```

### Terraform Configuration Files

Cannot include these here but it's a moderate size configuration with a single level of nested modules.

### Crash Output

```
Releasing state lock. This may take a few moments...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb64649]

goroutine 585 [running]:
github.com/hashicorp/terraform/terraform.(*State).Lock(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:95 +0x29
github.com/hashicorp/terraform/terraform.(*State).SameLineage(0x0, 0xc0423e7a40, 0xc0424e8400)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:628 +0x3b
github.com/hashicorp/terraform/state/remote.(*State).WriteState(0xc0424e8480, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/state/remote/state.go:37 +0x111
github.com/hashicorp/terraform/backend/local.(*Local).opRefresh(0xc04257c000, 0x3f52700, 0xc04200e0c8, 0xc0425700c0, 0xc0424e8450)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_refresh.go:115 +0x46c
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opRefresh)-fm(0x3f52700, 0xc04200e0c8, 0xc0425700c0, 0xc0424e8450)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:230 +0x59
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc04257c000, 0xc0422c2360, 0xc0422c2350, 0x3f52700, 0xc04200e0c8, 0xc0425700c0, 0xc0424e8450)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:254 +0xa1
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:251 +0x191
```

### Steps to Reproduce

1. `terraform refresh`

### Additional Context

This setup was working last week. It has been giving me a particular error for a kinesis firehose when I run `terraform plan` 
```
aws_kinesis_firehose_delivery_stream.firehose: extended_s3_configuration.0.kms_key_arn: '' expected type 'string', got unconvertible type 'firehose.KMSEncryptionConfig'
```
This is strange because the input is a string in the code and the error still occurs even after the code is removed.

**Comment by jbardin** [comment] 2018-01-25 13:42
Thanks for filing the issue @wsmithCTP!

This is a duplicate of #17152, which is fixed in master.

**Closed by jbardin** 2018-01-25 13:42 UTC
Labels: bug, crash

**Comment by ericpsantos** [comment] 2018-02-02 23:29
@jbardin I am getting this same issue after upgrading to 11.3. Any ideas?

**Comment by jbardin** [comment] 2018-02-02 23:55
Hi @ericpsantos,

Nope, I haven't seen this in 0.11.3.
Can you open a new issue with the stack trace?

Thanks!

**Comment by ericpsantos** [comment] 2018-02-03 00:32
It's actually the same as this https://github.com/terraform-providers/terraform-provider-aws/issues/3133
