### ISSUE TITLE
null value is not treated per docs when passed to modules

### ISSUE THREAD

**Issue by oxplot** [hashicorp/terraform#24142] opened 2020-02-18 10:41 UTC
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

`main.tf`:

```hcl
module mod1 {
  source         = "./mod1"
  optional_input = null
}
```

`mod1/main.tf`:

```hcl
variable optional_input {
  default = 5
}

output foo {
  value = var.optional_input / 5
}
```

### Debug Output

https://pastebin.com/raw/NuxLJi2U

### Expected Behavior

As per [docs](https://www.terraform.io/docs/configuration/expressions.html#null):

> `null`: a value that represents absence or omission. If you set an argument of a resource or **module to null**, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one

### Actual Behavior

An error message is shown saying that the said argument must not be null:

```
  on mod1/main.tf line 6, in output "foo":
   6:   value = var.optional_input / 5
    |----------------
    | var.optional_input is null

Error during operation: argument must not be null.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References
- #22430
- #21702

**Comment by buddhamangler-cbre** [comment] 2020-04-29 21:31
This forces module consumers to have knowledge of the default value for the module and specify the same default in their variable definitions. This really should be fixed.

**Comment by sean-abbott** [comment] 2020-05-15 19:01
Can reproduce in 0.12.25, see comment in #21702

**Comment by apparentlymart** [comment] 2020-06-19 02:03
Hi @oxplot,

I agree that the behavior is inconsistent here, and that's confusing. My sense of the ideal behavior is that if a variable value is set to `null` then the default value should be taken, and that setting a required variable (one without a default) should be an error.

The design challenge in this area is that some modules use `null` as a valid value, and so changes to the behavior must consider that. In the provider schema system that is represented by explicitly marking a variable as "optional" without providing a default. That approach doesn't directly work for input variables because the presence of `default` is overloaded to _imply_ "optional", rather than it being a separate argument.

We could potentially address this by allowing `default = null` as a special way to declare a variable as optional without a default value. That is still inconsistent with the usual meaning of `null` as being equivalent to omitting the argument -- omitting `default` would have a different meaning than setting it to `null` -- but a special case unique to the variable `default` argument is better than one that applies to all input variables, and `default` doesn't accept conditional expressions anyway so there isn't really any other useful meaning of `default = null`.

Unfortunately, given that the current behavior was established in v0.12.0 we cannot just change it now because there will be many modules depending on the current behavior. I'm going to mark this as a breaking change to acknowledge that while it's a valid issue to be addressed we are blocked by finding a responsible way to introduce it that will not cause confusing misbehavior for existing modules. I don't yet know what that approach will be.

In the meantime, I think it'd be best to update [the documentation for module blocks](https://www.terraform.io/docs/configuration/modules.html#calling-a-child-module) to be explicit about this exception to the usual interpretation of `null`, so that the behavior is at least well-defined even if also inconsistent.

Thanks for reporting this!

**Comment by buddhamangler-cbre** [comment] 2020-06-19 05:38
@apparentlymart I think it's important to consider the converse...a default that is non null that a consumer of the module may or may not set, yet the configuration has to allow for it.  This gets even more complex in chained module configurations.

**Comment by nshenry03** [comment] 2020-09-04 03:45
Agreed that this is unexpected behavior, especially considering the documentation for [null](https://www.terraform.io/docs/configuration/expressions.html#null) in the [Expressions](https://www.terraform.io/docs/configuration/expressions.html) documentation.

> null: a value that represents absence or omission. If you set an argument of a resource **<ins>or module</ins>** to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory.

**Comment by 007** [comment] 2021-08-24 17:53
The behavior is inconsistent, but the documentation is not inconsistent, it is _wrong_. Explicitly so.

Fixing the behavior of `null` to match the docs as a breaking change is one answer (which really should have happened for 0.12.x or at least 0.13), but [updating the docs](https://www.terraform.io/docs/language/expressions/types.html#null) would be a much easier solution. Remove `or a module` and document it independently that `null` passed to a module really is `null` and not "absence or omission".

**Comment by rabidscorpio** [comment] 2021-09-07 23:11
@apparentlymart @jbardin So this issue is now a year and a half old and the documentation still hasn't been updated nor has there been any change to make null work the way the documentation says it's supposed to work.

A null should mean `a value that represents absence or omission` for everything, not "an absense" for providers but a valid value for modules. It's not just confusing, it doesn't make sense that modules behave completely different from providers.

What's the work around for this? Am I supposed to know the default value of a variable in a module whenever I call that module? How many modules actually use "null" as a valid value? And why would they do that? Couldn't you just use an empty string?

**Comment by rabidscorpio** [comment] 2021-09-08 13:52
Is there any documentation anywhere that says that a `null` passed in to a module is treated a literal value as opposed to being ignored? Are modules using `null` as a passed in value _**despite**_ documentation that says something completely different?

If modules are ignoring the documentation then this isn't a breaking change, this is a major bug and module maintainers are responsible for using something that completely contradicts documentation.

**Comment by jvkubjg** [comment] 2021-09-20 10:24
Still not updates?

**Comment by vynaloze** [comment] 2021-10-05 09:07
@rabidscorpio 
>  I'm not sure why Hashicorp keeps saying it's a breaking change when it was always intended to work that way.

As per [Terraform v1.0 Compatibility Promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html#the-terraform-language): 
> If the actual behavior of a feature differs from what we explicitly documented as the feature's behavior, we will usually treat that as a bug and change the feature to match the documentation, although we will avoid making such changes if they seem likely to cause broad compatibility problems.

And this is precisely a change which will change the behaviour of countless modules. Modules often contain optional variables with reasonable defaults and a valid use case is to opt out of those defaults in favour of resource's defaults by using `null` as a *normal* value.

> If modules are ignoring the documentation then this isn't a breaking change, this is a major bug and module maintainers are responsible for using something that completely contradicts documentation.

If you would be a maintainer of any module, you'd think otherwise. But hey, the best is to ignore the reality and make it a problem of other people.

@apparentlymart 
Is there a reason why the documentation has not been updated **for over a year**?

**Comment by rabidscorpio** [comment] 2021-10-05 17:13
@vynaloze `null` didn't exist before 0.12 and the documentation was written almost 3 years ago when 0.12 was being introduced so any module that uses `null` as an actual value is doing so *despite* what the documentation says. If you can point me to *any* documentation that says that null can be used as a value for modules, I will admit that I'm wrong about this.

The reality is, though, that you have absolutely no idea how many modules use `null` as an actual value so please refrain from the melodramatic "countless". My guess is that very few are because it goes completely counter to the documentation and doing so runs the risk that Hashicorp will actually fix the bug that this is.

This is a bug and should have always been treated as a bug.

**Comment by buddhamangler-cbre** [comment] 2021-10-06 09:01
I have to agree, this position of you don't know how to unpaint yourselves out of a corner is not an excuse.  Nobody is saying it's an easy fix, what we should agree on is that it is a problem worth solving.  Why is this discussion still a thing, Hashicorp has already admitted the issue, so can we move to a solution please?
________________________________

**Comment by buddhamangler-cbre** [comment] 2021-10-06 09:21
i want to reiterate my previous point that is related here.  If module A defines a variable X with a default of Y and I am designing module B to wrap module A.  I want to supply a variable for X in module B that is passed to module A since it is something I wish the consumer the ability to modify, but this means that this issue kicks in.  If the consumer of module B supplies a value of null for the variable I get an error just as stated in this issue.  If they omit the value, it can work, but only if I replicate the exact same default from module A in module B's variables.  This sucks

**Comment by rabidscorpio** [comment] 2021-10-06 14:53
@vynaloze How can this possibly be "well-established" behavior? It's a bug that's not even documented anywhere. If module authors are using this, they did it at their own risk. Why would anyone build something depending on behavior that directly contradicts documentation?

**Comment by nshenry03** [comment] 2021-10-06 23:49
Anyone can update the documentation.  If you've got the time and want to see this improved, go for it! Simply create a pull request to modify this file: https://github.com/hashicorp/terraform/blob/main/website/docs/language/expressions/types.html.md

There are lots of "This sucks", "Hashicorp should do this", "Hashicorp should have done that" comments.  Anyone complaining actually paying anything for Terraform?  The truth is, this is fairly big change that has the potential to break existing things (which is never good).  Terraform (along w/ the rest of the Hashicorp stack) is a great product that greatly simplifies modern DevSecOps for free (for most anyway)...  I agree, I'd love to see this fixed as much as anyone, but truth is, it's a fairly simple workaround if your writing a new module....


`main.tf`:

```HCL
module "foo" {
  source = "./mod1"
}

module "bar" {
  source = "./mod1"
  optional_input = 10
}

output "foo" {
  value = module.foo.foo
}

output "bar" {
  value = module.bar.foo
}
```


`mod1/main.tf`:

```HCL
variable "optional_input" {
  description = "An optional number... If not specified, the default is 5"
  type        = number
  default     = null
}

locals {
  # If var.optional_input isn't null, use var.optional_input; otherwise, use 5
  # as the default
  optional_input = var.optional_input != null ? var.optional_input : 5
}

output "foo" {
  value = local.optional_input / 5
}
```

Works as needed
```NOFORMAT
hnicholas@hnicholas-a01:/tmp/24142$ tfenv use latest
Switching default version to v1.0.8
Switching completed
hnicholas@hnicholas-a01:/tmp/24142$ terraform init
Initializing modules...
- bar in mod1
- foo in mod1

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
hnicholas@hnicholas-a01:/tmp/24142$ terraform apply -auto-approve

Changes to Outputs:
  + bar = 2
  + foo = 1

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

bar = 2
foo = 1
```

**Closed** 2021-11-01 16:46 UTC
Labels: bug, breaking-change, config, v0.12
