### ISSUE TITLE
0.12 Missing TypeSet in state and attribute still present

### ISSUE THREAD

**Issue by remilapeyre** [hashicorp/terraform#21070] opened 2019-04-22 22:46 UTC
Updating Terraform SDK to 0.12 beta 2 make two acceptance tests break.

### Terraform version

```
github.com/hashicorp/terraform v0.12.0-beta2
```

### Expected behavior

All tests pass, as they did with Terraform 0.11

### Actual behavior

Two tests fail:

```
=== RUN   TestAccConsulKeys_basic
--- FAIL: TestAccConsulKeys_basic (0.15s)
    testing.go:568: Step 1 error: Check failed: Check 4/4 error: Attribute 'remove_one' still present: map[string]string{"datacenter":"dc1", "id":"consul", "key.#":"2", "key.33137035.default":"true", "key.33137035.delete":"false", "key.33137035.flags":"0", "key.33137035.name":"enabled", "key.33137035.path":"test/enabled", "key.33137035.value":"", "key.4021585958.default":"", "key.4021585958.delete":"true", "key.4021585958.flags":"64", "key.4021585958.name":"set", "key.4021585958.path":"test/set", "key.4021585958.value":"acceptanceUpdated", "var.%":"3", "var.enabled":"true", "var.remove_one":"hello", "var.set":"acceptanceUpdated"}
=== RUN   TestAccConsulPreparedQuery_basic
--- FAIL: TestAccConsulPreparedQuery_basic (0.12s)
    testing.go:568: Step 2 error: Check failed: Check 4/7 error: Attribute 'tags.#' not found: map[string]string{"dns.#":"0", "failover.#":"0", "id":"1bc7b66a-1112-9fcf-ae4b-f29f35a530ba", "name":"baz", "near":"", "only_passing":"false", "service":"memcached", "session":"", "stored_token":"", "template.#":"0"}
```

### Steps to reproduce

Get the provider updated with the 0.12 SDK at https://github.com/terraform-providers/terraform-provider-consul/tree/terraform-0.12 and run the acceptance tests:

```
$ consul agent -dev -config-file ./consul_test.hcl
$ export CONSUL_HTTP_ADDR=http://localhost:8500
$ export CONSUL_HTTP_TOKEN=master-token
$ make testacc TEST_ARGS="-count=1"
```

**Comment by jbardin** [comment] 2019-04-23 17:15
Hi @remilapeyre,

Thanks for filing this. It did highlight an SDK bug, and that provider branch will need to be further updated (it's already behind, but the missing fixes don't cover this issue).

The second test just need to be updated because it's not using the `helper/resource` check functions. 
The first test will pass once 21077 is merged, but the resource plan should be fixed to correctly mark computed map so it doesn't cause errors in resources using it.

**Comment by jbardin** [comment] 2019-04-23 17:46
Hi @remilapeyre,

I pushed the terraform-provider-consul updates to a temporary `jbardin/terraform-0.12` branch to not disturb any work you have in your `terraform-0.12` branch. Feel free to merge from there if you like. The fix reverenced here isn't in the main SDK branch yet of course, but the `CustomizeDiff` function fixes the root cause of the failure.

**Closed** 2019-04-23 18:41 UTC
Labels: provider-sdk

**Comment by remilapeyre** [comment] 2019-04-26 15:04
Thanks you so much, this is exactly what I needed 🎉 !
