### ISSUE TITLE
terraform crashed

### ISSUE THREAD

**Issue by cadjai** [hashicorp/terraform#26225] opened 2020-09-12 02:34 UTC
I was running terraform against local provider and module when it crashed. 
Here attached is the crash report. 
I was trying various data type for the *.auto.tfvars. I used the default ini style but then tried to provide the same data as a json formatted file and I believe that is when it crashed or at least that was the change I made and then got the crash. 
[crash.log](https://github.com/hashicorp/terraform/files/5212075/crash.log)

**Comment by alisdair** [comment] 2020-09-14 15:34
This looks like it may be a duplicate of #25709. Can you please try again with Terraform 0.13 to check if it's fixed?

If not, please include a small configuration and tfvars file to help us reproduce the issue.

**Comment by pselle** [comment] 2021-02-12 20:37
Hi there, because this has been open and waiting for reproduction, but does not have one at this point, I'm going to close this.

**Closed by pselle** 2021-02-12 20:37 UTC
Labels: bug, v0.12, waiting for reproduction, waiting-response
