### ISSUE TITLE
TF Describe infrastructure

### ISSUE THREAD

**Issue by ngnix** [hashicorp/terraform#20911] opened 2019-04-03 06:55 UTC
Hello!

Please tell me whether it is planned to add functionality describing the existing infrastructure? 
For example, I have 1500 instances in aws and 1000 in vsphere, and I need to generate .tf config to manage your infrastructure using TF.

**Comment by pkolyvas** [comment] 2020-04-09 16:23
Hi @ngnix,

We realize the `import` features of Terraform are lacking. At this time I can't tell you when Terraform will be able to play more nicely with existing infrastructure.

It is definitely something we're working towards, I just don't have something concrete to communicate at this time. 

I will however close this as a duplicate of #22219.

**Closed by pkolyvas** 2020-04-09 16:23 UTC
Labels: enhancement
