### ISSUE TITLE
Call to function "fileexists" failed: failed to stat

### ISSUE THREAD

**Issue by Poil** [hashicorp/terraform#27985] opened 2021-03-04 21:34 UTC
### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.49.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.18.0
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0

```

### Output
```
Error: Error in function call

  on .terraform/modules/front-door-waf-policy-bo/modules/waf-policy/locals.tf line 16, in locals:
  16:     fileexists(local.custom_waf_custom_block_response_body) ?
    |----------------
    | local.custom_waf_custom_block_response_body is "PCFET0NUWVBFIGh0bWw+CjxodG1sPgogIDxoZWFkPgogICAgPHRpdGxlPkFjY2VzcyBkZW5pZWQhPC90aXRsZT4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxzdHlsZT4KICAgICAgYm9keSB7CiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgICAgIGZvbnQtZmFtaWx5OiAnTm9iaWxlJywgYXJpYWwsIHNlcmlmOwogICAgICAgIGZvbnQtc2l6ZTogMjRweDsKICAgICAgICBjb2xvcjogIzAwMDsKICAgICAgICB0ZXh0LXNoYWRvdzogLTAuMWVtIC0wLjFlbSAwLjFlbSB3aGl0ZTsKICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmOwogICAgICB9CiAgICAgIGEuYnV0dG9uIHsKICAgICAgICBjb2xvcjogI2VlZTsKICAgICAgICBiYWNrZ3JvdW5kOiAjNTU1OwogICAgICAgIHBhZGRpbmc6IDBweCAxMnB4OwogICAgICAgIGJvcmRlci1yYWRpdXM6IDE1cHg7CiAgICAgICAgdGV4dC1zaGFkb3c6IG5vbmU7CiAgICAgIH0KICAgICAgYS5idXR0b246aG92ZXIgewogICAgICAgIGNvbG9yOiAjZmZmOwogICAgICAgIGJhY2tncm91bmQ6ICMwMDA7CiAgICAgIH0KICAgICAgYSB7CiAgICAgICAgY29sb3I6ICM3Nzc7CiAgICAgICAgdGV4dC1kZWNvcmF0aW9uOiBub25lOwogICAgICAgIHRyYW5zaXRpb246IDAuNXM7CiAgICAgIH0KICAgICAgYTpob3ZlciB7CiAgICAgICAgY29sb3I6ICMzMzM7CiAgICAgIH0KICAgICAgdWwgewogICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsKICAgICAgICAqZGlzcGxheTogaW5saW5lOwogICAgICB9CiAgICAgIHVsIGxpIHsKICAgICAgICAgdGV4dC1hbGlnbjogbGVmdDsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2hlYWQ+CiAgPGJvZHk+CiAgICA8aW1nIHNyYz0ibWFpbnRlbmFuY2UuYXhhLWltLmNvbS9sb2dvLnBuZyI+PGJyPjxicj4KICAgIDxoMj48c3BhbiBzdHlsZT0iY29sb3I6IHJlZCI+4oqWPC9zcGFuPiBBY2Nlc3MgZGVuaWVkITwvaDI+CiAgICA8cD5UaGUgcmVxdWVzdCBVUkwgd2FzIHJlamVjdGVkLjwvcD4KICAgIDxwPkZvciBhZGRpdGlvbmFsIGluZm9ybWF0aW9uLCBwbGVhc2UgY29udGFjdCBzdXBwb3J0IGFuZCBwcm92aWRlIHRoZXNlIGluZm9ybWF0aW9uczwvcD4KICAgIDx1bD4KICAgICAgPGxpPkRhdGU6IDxzcGFuIGlkPSJkYXRldGltZSI+PC9zcGFuPjwvbGk+CiAgICAgIDxsaT5VUkw6IDxzcGFuIGlkPSJ1cmwiPjwvc3Bhbj4KICAgIDwvdWw+CiAgICA8Zm9vdGVyPgogICAgICA8YSBjbGFzcz0iYnV0dG9uIiBocmVmPSJqYXZhc2NyaXB0OiBoaXN0b3J5LmJhY2soKTsiPmJhY2s8L2E+CiAgICA8L2Zvb3Rlcj4KICAgIDxzY3JpcHQ+CiAgICAgIHZhciB0b2RheSA9IG5ldyBEYXRlKCk7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJkYXRldGltZSIpLmlubmVySFRNTCA9IHRvZGF5LnRvVVRDU3RyaW5nKCk7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJ1cmwiKS5pbm5lckhUTUwgPSBkb2N1bWVudC5VUkw7CiAgICA8L3NjcmlwdD4KICA8L2JvZHk+CjwvaHRtbD4K"

Call to function "fileexists" failed: failed to stat
PCFET0NUWVBFIGh0bWw+CjxodG1sPgogIDxoZWFkPgogICAgPHRpdGxlPkFjY2VzcyBkZW5pZWQhPC90aXRsZT4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxzdHlsZT4KICAgICAgYm9keSB7CiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgICAgIGZvbnQtZmFtaWx5OiAnTm9iaWxlJywgYXJpYWwsIHNlcmlmOwogICAgICAgIGZvbnQtc2l6ZTogMjRweDsKICAgICAgICBjb2xvcjogIzAwMDsKICAgICAgICB0ZXh0LXNoYWRvdzogLTAuMWVtIC0wLjFlbSAwLjFlbSB3aGl0ZTsKICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmOwogICAgICB9CiAgICAgIGEuYnV0dG9uIHsKICAgICAgICBjb2xvcjogI2VlZTsKICAgICAgICBiYWNrZ3JvdW5kOiAjNTU1OwogICAgICAgIHBhZGRpbmc6IDBweCAxMnB4OwogICAgICAgIGJvcmRlci1yYWRpdXM6IDE1cHg7CiAgICAgICAgdGV4dC1zaGFkb3c6IG5vbmU7CiAgICAgIH0KICAgICAgYS5idXR0b246aG92ZXIgewogICAgICAgIGNvbG9yOiAjZmZmOwogICAgICAgIGJhY2tncm91bmQ6ICMwMDA7CiAgICAgIH0KICAgICAgYSB7CiAgICAgICAgY29sb3I6ICM3Nzc7CiAgICAgICAgdGV4dC1kZWNvcmF0aW9uOiBub25lOwogICAgICAgIHRyYW5zaXRpb246IDAuNXM7CiAgICAgIH0KICAgICAgYTpob3ZlciB7CiAgICAgICAgY29sb3I6ICMzMzM7CiAgICAgIH0KICAgICAgdWwgewogICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsKICAgICAgICAqZGlzcGxheTogaW5saW5lOwogICAgICB9CiAgICAgIHVsIGxpIHsKICAgICAgICAgdGV4dC1hbGlnbjogbGVmdDsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2hlYWQ+CiAgPGJvZHk+CiAgICA8aW1nIHNyYz0ibWFpbnRlbmFuY2UuYXhhLWltLmNvbS9sb2dvLnBuZyI+PGJyPjxicj4KICAgIDxoMj48c3BhbiBzdHlsZT0iY29sb3I6IHJlZCI+4oqWPC9zcGFuPiBBY2Nlc3MgZGVuaWVkITwvaDI+CiAgICA8cD5UaGUgcmVxdWVzdCBVUkwgd2FzIHJlamVjdGVkLjwvcD4KICAgIDxwPkZvciBhZGRpdGlvbmFsIGluZm9ybWF0aW9uLCBwbGVhc2UgY29udGFjdCBzdXBwb3J0IGFuZCBwcm92aWRlIHRoZXNlIGluZm9ybWF0aW9uczwvcD4KICAgIDx1bD4KICAgICAgPGxpPkRhdGU6IDxzcGFuIGlkPSJkYXRldGltZSI+PC9zcGFuPjwvbGk+CiAgICAgIDxsaT5VUkw6IDxzcGFuIGlkPSJ1cmwiPjwvc3Bhbj4KICAgIDwvdWw+CiAgICA8Zm9vdGVyPgogICAgICA8YSBjbGFzcz0iYnV0dG9uIiBocmVmPSJqYXZhc2NyaXB0OiBoaXN0b3J5LmJhY2soKTsiPmJhY2s8L2E+CiAgICA8L2Zvb3Rlcj4KICAgIDxzY3JpcHQ+CiAgICAgIHZhciB0b2RheSA9IG5ldyBEYXRlKCk7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJkYXRldGltZSIpLmlubmVySFRNTCA9IHRvZGF5LnRvVVRDU3RyaW5nKCk7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJ1cmwiKS5pbm5lckhUTUwgPSBkb2N1bWVudC5VUkw7CiAgICA8L3NjcmlwdD4KICA8L2JvZHk+CjwvaHRtbD4K.
```

### Additional Context
I don't understand why it stop to plan/apply it's just a test like on https://www.terraform.io/docs/language/functions/fileexists.html, also it was working in TF 0.12

**Comment by alisdair** [comment] 2021-03-04 22:00
Hi @Poil, thanks for reporting this!

The function is failing here because Go's `os.Stat` is returning an error due to the file name being too long. [Here's a Go playground example showing this error](https://play.golang.org/p/rY7SMslCRzD); you'll have to scroll to the right to see that the error is `…aHRtbD4K: file name too long`.

This seems to me to be reasonable behaviour from Terraform. The function is documented as working only with regular files, and returning an error if used with "a directory, FIFO, or other special mode". Calling the function with a file name which can never be a regular file seems like an error case to me, rather than a case which should return false.

I can also reproduce the same failure on Terraform 0.12, using the following configuration:

```hcl
locals {
  exists = fileexists("PCFET0NUWVBFIGh0bWw+CjxodG1sPgogIDxoZWFkPgogICAgPHRpdGxlPkFjY2VzcyBkZW5pZWQhPC90aXRsZT4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxzdHlsZT4KICAgICAgYm9keSB7CiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgICAgIGZvbnQtZmFtaWx5OiAnTm9iaWxlJywgYXJpYWwsIHNlcmlmOwogICAgICAgIGZvbnQtc2l6ZTogMjRweDsKICAgICAgICBjb2xvcjogIzAwMDsKICAgICAgICB0ZXh0LXNoYWRvdzogLTAuMWVtIC0wLjFlbSAwLjFlbSB3aGl0ZTsKICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmOwogICAgICB9CiAgICAgIGEuYnV0dG9uIHsKICAgICAgICBjb2xvcjogI2VlZTsKICAgICAgICBiYWNrZ3JvdW5kOiAjNTU1OwogICAgICAgIHBhZGRpbmc6IDBweCAxMnB4OwogICAgICAgIGJvcmRlci1yYWRpdXM6IDE1cHg7CiAgICAgICAgdGV4dC1zaGFkb3c6IG5vbmU7CiAgICAgIH0KICAgICAgYS5idXR0b246aG92ZXIgewogICAgICAgIGNvbG9yOiAjZmZmOwogICAgICAgIGJhY2tncm91bmQ6ICMwMDA7CiAgICAgIH0KICAgICAgYSB7CiAgICAgICAgY29sb3I6ICM3Nzc7CiAgICAgICAgdGV4dC1kZWNvcmF0aW9uOiBub25lOwogICAgICAgIHRyYW5zaXRpb246IDAuNXM7CiAgICAgIH0KICAgICAgYTpob3ZlciB7CiAgICAgICAgY29sb3I6ICMzMzM7CiAgICAgIH0KICAgICAgdWwgewogICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsKICAgICAgICAqZGlzcGxheTogaW5saW5lOwogICAgICB9CiAgICAgIHVsIGxpIHsKICAgICAgICAgdGV4dC1hbGlnbjogbGVmdDsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2hlYWQ+CiAgPGJvZHk+CiAgICA8aW1nIHNyYz0ibWFpbnRlbmFuY2UuYXhhLWltLmNvbS9sb2dvLnBuZyI+PGJyPjxicj4KICAgIDxoMj48c3BhbiBzdHlsZT0iY29sb3I6IHJlZCI+4oqWPC9zcGFuPiBBY2Nlc3MgZGVuaWVkITwvaDI+CiAgICA8cD5UaGUgcmVxdWVzdCBVUkwgd2FzIHJlamVjdGVkLjwvcD4KICAgIDxwPkZvciBhZGRpdGlvbmFsIGluZm9ybWF0aW9uLCBwbGVhc2UgY29udGFjdCBzdXBwb3J0IGFuZCBwcm92aWRlIHRoZXNlIGluZm9ybWF0aW9uczwvcD4KICAgIDx1bD4KICAgICAgPGxpPkRhdGU6IDxzcGFuIGlkPSJkYXRldGltZSI+PC9zcGFuPjwvbGk+CiAgICAgIDxsaT5VUkw6IDxzcGFuIGlkPSJ1cmwiPjwvc3Bhbj4KICAgIDwvdWw+CiAgICA8Zm9vdGVyPgogICAgICA8YSBjbGFzcz0iYnV0dG9uIiBocmVmPSJqYXZhc2NyaXB0OiBoaXN0b3J5LmJhY2soKTsiPmJhY2s8L2E+CiAgICA8L2Zvb3Rlcj4KICAgIDxzY3JpcHQ+CiAgICAgIHZhciB0b2RheSA9IG5ldyBEYXRlKCk7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJkYXRldGltZSIpLmlubmVySFRNTCA9IHRvZGF5LnRvVVRDU3RyaW5nKCk7CiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJ1cmwiKS5pbm5lckhUTUwgPSBkb2N1bWVudC5VUkw7CiAgICA8L3NjcmlwdD4KICA8L2JvZHk+CjwvaHRtbD4K")
}
```

Running `terraform plan` results in the same error.

As a result, I think this is not a bug in Terraform, so I'm going to close it for now. If you think I've missed something here I'm happy to discuss further!

**Closed by alisdair** 2021-03-04 22:00 UTC
Labels: bug, new
