### ISSUE TITLE
0.12 TypeList Panic During Eval Diff

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#20084] opened 2019-01-23 02:51 UTC
### Terraform Version

go.mod:

```
github.com/hashicorp/terraform v0.12.0-alpha4.0.20190118003454-565eeac5d104
```

### Terraform Configuration Files

```hcl
data "aws_ami" "test" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn-ami-hvm-*-x86_64-gp2"]
  }
}

resource "aws_launch_template" "test" {
  image_id      = "${data.aws_ami.test.id}"
  instance_type = "t3.micro"
  name          = "test"
}

resource "aws_ec2_fleet" "test" {
  launch_template_config {
    launch_template_specification {
      launch_template_id = "${aws_launch_template.test.id}"
      version            = "${aws_launch_template.test.latest_version}"
    }
  }

  target_capacity_specification {
    default_target_capacity_type = "spot"
    total_target_capacity        = 0
  }
}
```

### Debug Output

Replace TEAMCITY with OSS hostname.

`https://TEAMCITY/repository/download/Aws_ProviderAws/41542:id/debug-aws-c76a9a2-TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId.log`

### Crash Output

```
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version

------- Stderr: -------
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 958 [running]:
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty.Value.HasIndex(0x47c8bc0, 0xc00133a430, 0x0, 0x0, 0x47c8b40, 0xc0000ac96a, 0x409c7e0, 0xc0005f0270, 0x388e9c0, 0xc0005e9e60, ...)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/value_ops.go:738 +0xa7d
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty.IndexStep.Apply(0x47c8b40, 0xc0000ac96a, 0x409c7e0, 0xc0005f0270, 0x47c8bc0, 0xc00133a430, 0x0, 0x0, 0x47c8bc0, 0xc00133a430, ...)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/path.go:152 +0xcc
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty.Path.Apply(0xc0013981e0, 0x5, 0x5, 0x47c8c40, 0xc000943118, 0x388e9c0, 0xc0005f01b0, 0x0, 0x0, 0x47c8c40, ...)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/path.go:75 +0xb6
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc000910d80, 0x47ee880, 0xc00274f380, 0x2, 0x2, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval_diff.go:243 +0x267d
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x47b63a0, 0xc000910d80, 0x47ee880, 0xc00274f380, 0x0, 0x0, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:57 +0x167
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0007ba0c0, 0x47ee880, 0xc00274f380, 0x2, 0x2, 0x7fd6fb56db40, 0x4e)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x47b66c0, 0xc0007ba0c0, 0x47ee880, 0xc00274f380, 0x3884640, 0x7c156a2, 0x3526ac0, 0xc001986c10)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:57 +0x167
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.Eval(0x47b66c0, 0xc0007ba0c0, 0x47ee880, 0xc00274f380, 0xc0007ba0c0, 0x47b66c0, 0xc0007ba0c0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x400c920, 0xc001986210, 0x0, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/graph.go:90 +0x10d1
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000206400, 0x400c920, 0xc001986210, 0xc000bc4880)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag/walk.go:392 +0x373
created by github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag.(*Walker).Update
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag/walk.go:314 +0x9d2
```

### Steps to Reproduce

In AWS provider branch with 0.12 dependencies (e.g. `v0.12-sdk-updates`):

* `TF_ACC=1 go test ./aws -v -timeout 120m -parallel 20 -run=TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version`

### References

Other acceptance tests failing with similar panic (non-exhaustive list):

```
TestAccAWSCodeDeployDeploymentConfig_trafficCanary
TestAccAWSCodeDeployDeploymentConfig_trafficLinear
TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId
TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName
TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version
TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone
TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType
TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority
TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple
TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId
TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity
TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple
```

**Comment by bflad** [comment] 2019-01-23 03:40
Additional acceptance test references (will update here as I find them):

```
TestAccAWSDlmLifecyclePolicy_Full
```

**Comment by apparentlymart** [comment] 2019-01-23 15:46
The relevant portion of code here is trying to match `ForceNew`-inspired "requires replacement" (formerly "forces new resource") indications from the provider with attribute values so that it can understand if they have actually changed (after applying `ignore_changes`, etc).

It seems to be a bug in the upstream `cty` library not correctly handling the absence of something at a certain path. I suspect after we fix that we'll get a different (non-crash) error due to a safety check Terraform itself does:

```
Error: Provider produced invalid plan

Provider "aws" has indicated "requires replacement" on aws_ec2_fleet.test
for a non-existent attribute path foo.bar.baz.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

In spite of the language in the message, with our current setup the bug is much more likely to be in the protocol shims in the SDK, but it'll be easier to determine that root cause once we've fixed the crashing bug in cty and can see exactly which attribute path it's complaining about.

**Comment by bflad** [comment] 2019-01-24 09:06
As of `1592b4aa67ad`, I'm no longer seeing the previous panic: 

```
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version (70.36s)
--- PASS: TestAccAWSDlmLifecyclePolicy_Full (21.14s)
```

I'm good to close this, if you are! 🎉Thanks!

**Comment by apparentlymart** [comment] 2019-01-24 17:09
I think there may still be a `cty` bug here but since Terraform's not hitting it I'll close this out now and we'll open an issue over in `cty` if we encounter it again.

**Comment by bflad** [comment] 2019-01-26 20:52
After doing another full AWS provider acceptance test run yesterday with the below upstream versions and parsing through the various failed tests I was able to find two last instances of this panic. 😅 

```
github.com/hashicorp/terraform@fb0c9714c118
github.com/zcl-conf/go-cty@a385d646c1e9
```

Subtle note: the stacks are the different prior and planned value calls to `path.Apply()` so including both stacks.

**TestAccAWSBatchJobDefinition_updateForcesNewResource**

Relevant links:
* Resource schema: https://github.com/terraform-providers/terraform-provider-aws/blob/5b8ed28c7413fc297542bcff1da6f0cf5488270d/aws/resource_aws_batch_job_definition.go#L21-L91
* Acceptance tests: https://github.com/terraform-providers/terraform-provider-aws/blob/5b8ed28c7413fc297542bcff1da6f0cf5488270d/aws/resource_aws_batch_job_definition_test.go
* Terraform 0.11 debug link on OSS TeamCity: https://HOSTNAME/repository/download/Aws_ProviderAws/42586:id/debug-aws-78c6ea3-TestAccAWSBatchJobDefinition_updateForcesNewResource.log
* Terraform 0.12 debug link on OSS TeamCity: https://HOSTNAME/repository/download/Aws_ProviderAws/42661:id/debug-aws-03c3961-TestAccAWSBatchJobDefinition_updateForcesNewResource.log

Terraform 0.11 plan:

```
DESTROY/CREATE: aws_batch_job_definition.test
  arn:                                "arn:aws:batch:us-west-2:187416307283:job-definition/tf_acctest_batch_job_definition_5386753045108294095:1" => "<computed>"
  container_properties:               "{\"command\":[\"ls\",\"-la\"],\"environment\":[{\"name\":\"VARNAME\",\"value\":\"VARVAL\"}],\"image\":\"busybox\",\"memory\":512,\"mountPoints\":[{\"containerPath\":\"/tmp\",\"readOnly\":false,\"sourceVolume\":\"tmp\"}],\"ulimits\":[{\"hardLimit\":1024,\"name\":\"nofile\",\"softLimit\":1024}],\"vcpus\":1,\"volumes\":[{\"host\":{\"sourcePath\":\"/tmp\"},\"name\":\"tmp\"}]}" => "{\"command\":[\"ls\",\"-la\"],\"environment\":[{\"name\":\"VARNAME\",\"value\":\"VARVAL\"}],\"image\":\"busybox\",\"memory\":1024,\"mountPoints\":[{\"containerPath\":\"/tmp\",\"readOnly\":false,\"sourceVolume\":\"tmp\"}],\"ulimits\":[{\"hardLimit\":1024,\"name\":\"nofile\",\"softLimit\":1024}],\"vcpus\":1,\"volumes\":[{\"host\":{\"sourcePath\":\"/tmp\"},\"name\":\"tmp\"}]}" (forces new resource)
  name:                               "tf_acctest_batch_job_definition_5386753045108294095" => "tf_acctest_batch_job_definition_5386753045108294095"
  parameters.%:                       "2" => "0" (forces new resource)
  parameters.param1:                  "val1" => "" (forces new resource)
  parameters.param2:                  "val2" => "" (forces new resource)
  retry_strategy.#:                   "1" => "0" (forces new resource)
  retry_strategy.0.attempts:          "1" => "0" (forces new resource)
  revision:                           "1" => "<computed>"
  timeout.#:                          "1" => "0" (forces new resource)
  timeout.0.attempt_duration_seconds: "60" => "0" (forces new resource)
  type:                               "container" => "container"
```

Terraform 0.12 panic:

```
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 523 [running]:
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty.Value.HasIndex(0x4b26420, 0xc000f61e10, 0x0, 0x0, 0x4b263a0, 0xc0000ac96a, 0x43e23c0, 0xc001eac210, 0x3b320a0, 0xc001eac180, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/value_ops.go:738 +0xa7d
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty.IndexStep.Apply(0x4b263a0, 0xc0000ac96a, 0x43e23c0, 0xc001eac210, 0x4b26420, 0xc000f61e10, 0x0, 0x0, 0x4b26420, 0xc000f61e10, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/path.go:152 +0xcc
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty.Path.Apply(0xc001eac240, 0x3, 0x3, 0x4b264a0, 0xc001be7a10, 0x3b320a0, 0xc001eac180, 0xc000775660, 0x4b263a0, 0xc0000ac96c, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/zclconf/go-cty/cty/path.go:75 +0xb6
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc000a94f00, 0x4b4ce20, 0xc0009425b0, 0x2, 0x2, 0x0, 0x0)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval_diff.go:243 +0x267d
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x4b13b40, 0xc000a94f00, 0x4b4ce20, 0xc0009425b0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:57 +0x167
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0007751c0, 0x4b4ce20, 0xc0009425b0, 0x2, 0x2, 0x7f711deffe18, 0x59)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x4b13e60, 0xc0007751c0, 0x4b4ce20, 0xc0009425b0, 0x3b27ae0, 0x83036a2, 0x3779b00, 0xc0005c58a0)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:57 +0x167
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.Eval(0x4b13e60, 0xc0007751c0, 0x4b4ce20, 0xc0009425b0, 0xc0007751c0, 0x4b13e60, 0xc0007751c0, 0x0)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x4342b60, 0xc0005c4fb0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform/graph.go:90 +0x10d1
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000f5c680, 0x4342b60, 0xc0005c4fb0, 0xc000d9c980)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag/walk.go:392 +0x373
created by github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/dag/walk.go:314 +0x9d2
```

**TestAccAWSEcsService_withPlacementStrategy**

Relevant references:
* Resource schema: https://github.com/terraform-providers/terraform-provider-aws/blob/5b8ed28c7413fc297542bcff1da6f0cf5488270d/aws/resource_aws_ecs_service.go#L29-L348
* Acceptance tests: https://github.com/terraform-providers/terraform-provider-aws/blob/5b8ed28c7413fc297542bcff1da6f0cf5488270d/aws/resource_aws_ecs_service_test.go
* Terraform 0.11 debug link on OSS TeamCity: https://HOSTNAME/repository/download/Aws_ProviderAws/42586:id/debug-aws-78c6ea3-TestAccAWSEcsService_withPlacementStrategy.log
* Terraform 0.12 debug link on OSS TeamCity: https://HOSTNAME/repository/download/Aws_ProviderAws/42661:id/debug-aws-03c3961-TestAccAWSEcsService_withPlacementStrategy.log

Terraform 0.11 acceptance test plan (Terraform 0.12 panic occurs during plan of first replacement):

```
DESTROY/CREATE: aws_ecs_service.mongo
  cluster:                            "arn:aws:ecs:us-west-2:--OMITTED--:cluster/tf-acc-cluster-svc-w-ps-7yeevlot" => "arn:aws:ecs:us-west-2:--OMITTED--:cluster/tf-acc-cluster-svc-w-ps-7yeevlot"
  deployment_maximum_percent:         "200" => "200"
  deployment_minimum_healthy_percent: "100" => "100"
  desired_count:                      "1" => "1"
  enable_ecs_managed_tags:            "false" => "false"
  iam_role:                           "" => "<computed>"
  launch_type:                        "EC2" => "EC2"
  name:                               "tf-acc-svc-w-ps-7yeevlot" => "tf-acc-svc-w-ps-7yeevlot"
  ordered_placement_strategy.#:       "0" => "1" (forces new resource)
  ordered_placement_strategy.0.field: "" => "memory" (forces new resource)
  ordered_placement_strategy.0.type:  "" => "binpack" (forces new resource)
  platform_version:                   "" => "<computed>"
  scheduling_strategy:                "REPLICA" => "REPLICA"
  task_definition:                    "arn:aws:ecs:us-west-2:--OMITTED--:task-definition/tf-acc-td-svc-w-ps-7yeevlot:1" => "arn:aws:ecs:us-west-2:--OMITTED--:task-definition/tf-acc-td-svc-w-ps-7yeevlot:1"

DESTROY/CREATE: aws_ecs_service.mongo
  cluster:                            "arn:aws:ecs:us-west-2:--OMITTED--:cluster/tf-acc-cluster-svc-w-ps-7yeevlot" => "arn:aws:ecs:us-west-2:--OMITTED--:cluster/tf-acc-cluster-svc-w-ps-7yeevlot"
  deployment_maximum_percent:         "200" => "200"
  deployment_minimum_healthy_percent: "100" => "100"
  desired_count:                      "1" => "1"
  enable_ecs_managed_tags:            "false" => "false"
  iam_role:                           "" => "<computed>"
  launch_type:                        "EC2" => "EC2"
  name:                               "tf-acc-svc-w-ps-7yeevlot" => "tf-acc-svc-w-ps-7yeevlot"
  ordered_placement_strategy.#:       "1" => "1"
  ordered_placement_strategy.0.field: "memory" => "" (forces new resource)
  ordered_placement_strategy.0.type:  "binpack" => "random" (forces new resource)
  platform_version:                   "" => "<computed>"
  scheduling_strategy:                "REPLICA" => "REPLICA"
  task_definition:                    "arn:aws:ecs:us-west-2:--OMITTED--:task-definition/tf-acc-td-svc-w-ps-7yeevlot:1" => "arn:aws:ecs:us-west-2:--OMITTED--:task-definition/tf-acc-td-svc-w-ps-7yeevlot:1"

DESTROY/CREATE: aws_ecs_service.mongo
  cluster:                            "arn:aws:ecs:us-west-2:--OMITTED--:cluster/tf-acc-cluster-svc-w-ps-7yeevlot" => "arn:aws:ecs:us-west-2:--OMITTED--:cluster/tf-acc-cluster-svc-w-ps-7yeevlot"
  deployment_maximum_percent:         "200" => "200"
  deployment_minimum_healthy_percent: "100" => "100"
  desired_count:                      "1" => "1"
  enable_ecs_managed_tags:            "false" => "false"
  iam_role:                           "" => "<computed>"
  launch_type:                        "EC2" => "EC2"
  name:                               "tf-acc-svc-w-ps-7yeevlot" => "tf-acc-svc-w-ps-7yeevlot"
  ordered_placement_strategy.#:       "1" => "2" (forces new resource)
  ordered_placement_strategy.0.field: "" => "memory" (forces new resource)
  ordered_placement_strategy.0.type:  "random" => "binpack" (forces new resource)
  ordered_placement_strategy.1.field: "" => "instanceId" (forces new resource)
  ordered_placement_strategy.1.type:  "" => "spread" (forces new resource)
  platform_version:                   "" => "<computed>"
  scheduling_strategy:                "REPLICA" => "REPLICA"
  task_definition:                    "arn:aws:ecs:us-west-2:--OMITTED--:task-definition/tf-acc-td-svc-w-ps-7yeevlot:1" => "arn:aws:ecs:us-west-2:--OMITTED--:task-definition/tf-acc-td-svc-w-ps-7yeevlot:1"
```

Terraform 0.12 panic:

```
=== CONT  TestAccAWSEcsService_withPlacementStrategy
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 744 [running]:
github.com/zclconf/go-cty/cty.Value.HasIndex(0x571e160, 0xc0007e1ea0, 0x0, 0x0, 0x571e0e0, 0xc0000b696a, 0x4fda560, 0xc002053e60, 0x4733580, 0xc001e46f60, ...)
	/Users/bflad/go/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190124225737-a385d646c1e9/cty/value_ops.go:738 +0xa7d
github.com/zclconf/go-cty/cty.IndexStep.Apply(0x571e0e0, 0xc0000b696a, 0x4fda560, 0xc002053e60, 0x571e160, 0xc0007e1ea0, 0x0, 0x0, 0x571e160, 0xc0007e1ea0, ...)
	/Users/bflad/go/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190124225737-a385d646c1e9/cty/path.go:152 +0xcc
github.com/zclconf/go-cty/cty.Path.Apply(0xc002053f20, 0x3, 0x3, 0x571e1e0, 0xc0005073d0, 0x4733580, 0xc001e46f60, 0x571e0e0, 0xc0000b696b, 0x437ae80, ...)
	/Users/bflad/go/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190124225737-a385d646c1e9/cty/path.go:75 +0xb6
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc0001b5740, 0x5744b60, 0xc0011bc8f0, 0x2, 0x2, 0x0, 0x0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/terraform/eval_diff.go:259 +0x299e
github.com/hashicorp/terraform/terraform.EvalRaw(0x570b680, 0xc0001b5740, 0x5744b60, 0xc0011bc8f0, 0x0, 0x0, 0x0, 0x0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/terraform/eval.go:57 +0x167
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000865760, 0x5744b60, 0xc0011bc8f0, 0x2, 0x2, 0x9f44018, 0x51)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x570b9a0, 0xc000865760, 0x5744b60, 0xc0011bc8f0, 0x4728c60, 0x86ee942, 0x437ae80, 0xc0007e1d60)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/terraform/eval.go:57 +0x167
github.com/hashicorp/terraform/terraform.Eval(0x570b9a0, 0xc000865760, 0x5744b60, 0xc0011bc8f0, 0xc000865760, 0x570b9a0, 0xc000865760, 0x0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x4f3b3e0, 0xc0007e0f10, 0x0, 0x0, 0x0)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/terraform/graph.go:90 +0x10d1
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc001480c00, 0x4f3b3e0, 0xc0007e0f10, 0xc000c4fa40)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/dag/walk.go:392 +0x373
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform@v0.12.0-alpha4.0.20190125004221-fb0c9714c118/dag/walk.go:314 +0x9d2
```

**Closed** 2019-01-31 19:58 UTC
Labels: bug, core, crash
