### ISSUE TITLE
data resources not honoring depends_on

### ISSUE THREAD

**Issue by RyanBowlby-Reflektion** [hashicorp/terraform#8750] opened 2016-09-09 07:30 UTC
Data resources do not appear to honor or make use of the `depends_on` attribute for explicit dependencies. The depends_on should be used to determine if the data resource should be run in the refresh phase or in the apply phase.

**Comment by apparentlymart** [comment] 2016-09-09 15:06
Hi @RyanBowlby-Reflektion! Sorry things aren't working as expected here.

When you say that `depends_on` is not being honored, do you mean that Terraform explicitly rejects that attribute or that it accepts it but then doesn't appear to actually consider it when planning/applying configuration?

If possible, an example of what you're trying, what is happening, and what you expected to happen would be really helpful to understand what issue you are seeing here. `depends_on` is certainly *supposed* to work with data resources, but it is notable that data resources have a *slightly* different lifecycle than managed resources and so dependencies may have a slightly different result.

**Comment by alonbecker** [comment] 2016-09-13 11:59
I am having the same issue, I believe. I am using depends_on on an aws s3 object (aws_s3_bucket_object data resource). It is dependent on an aws_instance. The aws_instance has a remote-exec provisioner that creates the s3 object. But because the object won't exist until after the aws instance is up and running, I am getting a data.aws_s3_bucket_object.OBJECT_NAME: Failed getting s3 object even though it shouldn't run until after aws_instance runs. I am getting it in both terraform apply and plan.

**Comment by apparentlymart** [comment] 2017-04-05 01:03
Hi again @RyanBowlby-Reflektion, and hi @alonbecker. Sorry I let this languish here for so long.

Somewhere along the line since this issue was opened (I don't remember exactly when, sadly) we changed the behavior of data sources so that `depends_on` would cause the read to *always* be deferred to the apply phase, since that's the most conservative behavior. I believe that should've fixed the issue we were discussing here, since Terraform won't try to read the data source during the plan phase any longer.

I'm going to close this under that assumption, though please do let me know if you're still seeing issues of this sort... if so, it'd be helpful to have some configuration examples to reproduce the problem since if it's still failing that suggests that there's something more subtle going on than I've been able to infer from the discussion here.

**Closed by apparentlymart** 2017-04-05 01:03 UTC
Labels: bug, core
