### ISSUE TITLE
Terraform plan crashes - segmentation violation code=0x1 addr=0x28 pc=0x1a1b754]

### ISSUE THREAD

**Issue by kornholjo** [hashicorp/terraform#22133] opened 2019-07-18 22:41 UTC
Happened after some refactoring, can't recover, complex project.

**Info**
macOS: 10.14.5 (18F132)
terraform info: 

**Terraform v0.12.2**
+ provider.null v2.1.2
+ provider.oci v3.33.0
+ provider.template v2.1.2

**crash logs:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a1b754]

goroutine 1009 [running]:
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0014761e0, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0xc00137cc00, 0x0, 0xc000fe6768, 0x3, 0xc000052570, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:95 +0x194
dhcp-10-159-154-42:pod1 $ terraform plan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a1b754]

goroutine 879 [running]:
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0012374a0, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0xc00111f680, 0x0, 0xc001386768, 0x3, 0xc000056f70, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:95 +0x194
dhcp-10-159-154-42:pod1 $ terraform plan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a1b754]

goroutine 944 [running]:
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0008754a0, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0xc0012cea80, 0x0, 0xc000a5e768, 0x3, 0xc000052570, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:95 +0x194
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc000790270, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0x0, 0x0, 0x3ec4c60, 0x5c, 0x2a30f70, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:284 +0x1e4
github.com/hashicorp/terraform/terraform.(*EvalWriteOutput).Eval(0xc000894d20, 0x2e1c120, 0xc000790270, 0x2, 0x2, 0xc00118a000, 0x59)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_output.go:48 +0x153
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8d20, 0xc000894d20, 0x2e1c120, 0xc000790270, 0x44, 0x0, 0x0, 0x44)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc000895200, 0x2e1c120, 0xc000790270, 0x2, 0x2, 0xc000a5eb10, 0x103d4e4)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8ae0, 0xc000895200, 0x2e1c120, 0xc000790270, 0x14, 0xbf445af79be2e2b0, 0x3bb46511, 0x44)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000d46480, 0x2e1c120, 0xc000790270, 0x2, 0x2, 0x1abe1c5, 0x2da8ae0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8c20, 0xc000d46480, 0x2e1c120, 0xc000790270, 0x2663a20, 0x3d9a405, 0x25d0da0, 0xc000862ca0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2da8c20, 0xc000d46480, 0x2e1c120, 0xc000790270, 0xc000d46480, 0x2da8c20, 0xc000d46480, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x282c680, 0xc000a5b860, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0007ffe00, 0x282c680, 0xc000a5b860, 0xc000b87040)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by teamterraform** [comment] 2019-07-18 22:56
Hi @kornholjo! Sorry for this crash, and thank you for reporting it.

In order to understand what Terraform was doing when it crashed, we need to see the trace log that is requested in our issue template. That will includes information about specifically what object in the configuration Terraform was evaluating at the point this happened, and then we can hopefully correlate that back to something that you changed in your refactoring and thus understand what construct Terraform is failing to handle correctly here.

Could you please run this again with the `TF_LOG=trace` environment variable set, and share the result in [a gist](https://gist.github.com/)? We understand that for a complex configuration it isn't practical to share the full configuration, but the information in the trace log should hopefully help us identify a smaller part of the configuration to ask for so we can better understand what happened here. Thanks!

**Comment by kornholjo** [comment] 2019-07-18 23:55
I'm very sorry but I can't share the full logs (company policy) but I can share the very end of the logs, not sure if it's any help:

2019/07/18 16:26:04 [TRACE] module.main_module.module.vms.module.vm_hub: eval: *terraform.EvalLocal
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a1b754]

goroutine 556 [running]:
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc001004460, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0xc000a7aa80, 0x0, 0xc000e1a768, 0x3, 0xc000056f70, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:95 +0x194
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc0009f2680, 0x0, 0x0, 0x2dea2a0, 0x3ee48d8, 0x0, 0x0, 0x3ec4c60, 0x5c, 0x2a30f70, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:284 +0x1e4
github.com/hashicorp/terraform/terraform.(*EvalWriteOutput).Eval(0xc000ca0000, 0x2e1c120, 0xc0009f2680, 0x2, 0x2, 0xc0010cc000, 0x59)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_output.go:48 +0x153
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8d20, 0xc000ca0000, 0x2e1c120, 0xc0009f2680, 0x44, 0x0, 0x0, 0x44)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc000ca0180, 0x2e1c120, 0xc0009f2680, 0x2, 0x2, 0xc000e1ab10, 0x103d4e4)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8ae0, 0xc000ca0180, 0x2e1c120, 0xc0009f2680, 0x14, 0xbf445de335ff9008, 0x3ce6bf5f, 0x44)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000d0d9e0, 0x2e1c120, 0xc0009f2680, 0x2, 0x2, 0x1abe1c5, 0x2da8ae0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2da8c20, 0xc000d0d9e0, 0x2e1c120, 0xc0009f2680, 0x2663a20, 0x3d9a405, 0x25d0da0, 0xc0008452a0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2da8c20, 0xc000d0d9e0, 0x2e1c120, 0xc0009f2680, 0xc000d0d9e0, 0x2da8c20, 0xc000d0d9e0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x282c680, 0xc000c06270, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000731280, 0x282c680, 0xc000c06270, 0xc000b0c300)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

BTW. After a few random changes I'm no longer able to reproduce this problem.

**Comment by teamterraform** [comment] 2019-07-19 00:45
Thanks for following up, @kornholjo!

Unfortunately without being able to tell which configuration constuct this error came from, we can't really learn anything more about what circumstances caused this crash. We _can_ see from the output that it was related to evaluating the expression from an `output` block, but output blocks are generally working so there must be something unusual about this particular one that is causing the crash.

Since you're no longer able to reproduce, unfortunately I don't think we can do anything else here. :confounded: We're going to close this, but we'll look out for similar reports in future to see if we can learn more about what's going on here. Thanks again for reporting this!

**Closed by teamterraform** 2019-07-19 00:45 UTC
Labels: bug, config, crash
