### ISSUE TITLE
setproduct panics if one argument is an empty list

### ISSUE THREAD

**Issue by pasdam** [hashicorp/terraform#28595] opened 2021-05-04 06:09 UTC
### Description

When using `setproduct` with one of the argument being an empty list in the latest version it panics.

Running `terraform plan` using v0.15.1 panics (with the stacktrace posted below), whereas with 0.15.0 it works as expected.

### Terraform Version

```
0.15.1
```

### Crash Output

```
Error: Error in function call
│
│   on main.tf line 3, in resource "null_resource" "cluster":
│    3:     cluster_instance_ids = jsonencode(setproduct(
│    4:       ["a", "b"],
│    5:       []
│    6:     ))
│
│ Call to function "setproduct" failed: panic in function implementation: runtime error: hash of unhashable type cty.ValueMarks
│ goroutine 74 [running]:
│ runtime/debug.Stack(0xc000a5c358, 0x301fa40, 0xc000a164d0)
│ 	runtime/debug/stack.go:24 +0x9f
│ github.com/zclconf/go-cty/cty/function.errorForPanic(...)
│ 	github.com/zclconf/go-cty@v1.8.2/cty/function/error.go:44
│ github.com/zclconf/go-cty/cty/function.Function.Call.func1(0xc000a5cb10, 0xc000a5cb30)
│ 	github.com/zclconf/go-cty@v1.8.2/cty/function/function.go:291 +0x93
│ panic(0x301fa40, 0xc000a164d0)
│ 	runtime/panic.go:965 +0x1b9
│ github.com/zclconf/go-cty/cty.Value.Mark(0x383dd78, 0xc000a164c0, 0x2ee5640, 0xc000a187e0, 0x30cc180, 0x0, 0x339f680, 0xc000269e30, 0x0, 0xc000a187c8)
│ 	github.com/zclconf/go-cty@v1.8.2/cty/marks.go:208 +0x1dc
│ github.com/zclconf/go-cty/cty/function/stdlib.glob..func33(0xc00014cd40, 0x2, 0x2, 0x383dd78, 0xc000a164b0, 0xc000a164b0, 0x0, 0x0, 0x48f52a0, 0x100f301, ...)
│ 	github.com/zclconf/go-cty@v1.8.2/cty/function/stdlib/collection.go:956 +0xf05
│ github.com/zclconf/go-cty/cty/function.Function.Call(0xc0000b9ce0, 0xc00014cd40, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
│ 	github.com/zclconf/go-cty@v1.8.2/cty/function/function.go:295 +0x4a7
│ github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc000636000, 0xc000a186a8, 0x0, 0xc00004e660, 0x1, 0x1, 0x2000, 0x1, 0xc000429bf8)
│ 	github.com/hashicorp/hcl/v2@v2.9.1/hclsyntax/expression.go:442 +0xff6
│ github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0006360f0, 0xc000a186a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
│ 	github.com/hashicorp/hcl/v2@v2.9.1/hclsyntax/expression.go:408 +0x2406
│ github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0xc000150780, 0xc000a186a8, 0x0, 0x8, 0xc000312d88, 0x1, 0x487e050, 0x1, 0x1)
│ 	github.com/hashicorp/hcl/v2@v2.9.1/hclsyntax/expression.go:808 +0x2ac
│ github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc00063f0b0, 0xc0000c91a0, 0x0, 0x0, 0x0, 0xc000a186a8, 0x383dd08, 0xc000058409, 0x0, 0x0, ...)
│ 	github.com/hashicorp/hcl/v2@v2.9.1/hcldec/spec.go:205 +0x2c6
│ github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc00063f020, 0xc0000c91a0, 0x0, 0x0, 0x0, 0xc000a186a8, 0x20, 0x314a1e0, 0x17762fa70000000d, 0x48f7760, ...)
│ 	github.com/hashicorp/hcl/v2@v2.9.1/hcldec/spec.go:79 +0x237
│ github.com/hashicorp/hcl/v2/hcldec.decode(0x383ced0, 0xc00004e600, 0x0, 0x0, 0x0, 0xc000a186a8, 0x383dad8, 0xc00063f020, 0x0, 0x0, ...)
│ 	github.com/hashicorp/hcl/v2@v2.9.1/hcldec/decode.go:21 +0x11b
│ github.com/hashicorp/hcl/v2/hcldec.Decode(...)
│ 	github.com/hashicorp/hcl/v2@v2.9.1/hcldec/public.go:15
│ github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc0000aef00, 0x383c878, 0xc00037b980, 0xc000269cb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
│ 	github.com/hashicorp/terraform/lang/eval.go:67 +0x2ac
│ github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc00056c680, 0x383cb18, 0xc00037b980, 0xc000269cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
│ 	github.com/hashicorp/terraform/terraform/eval_context_builtin.go:273 +0x1ad
│ github.com/hashicorp/terraform/terraform.(*NodeValidatableResource).validateResource(0xc0002a2050, 0x3873af0, 0xc00056c680, 0xc000a1fc50, 0x1007468, 0xc0009c8358)
│ 	github.com/hashicorp/terraform/terraform/node_resource_validate.go:357 +0x499
│ github.com/hashicorp/terraform/terraform.(*NodeValidatableResource).Execute(0xc0002a2050, 0x3873af0, 0xc00056c680, 0xcc44004, 0xc000a1fce8, 0x100d305, 0x3049060)
│ 	github.com/hashicorp/terraform/terraform/node_resource_validate.go:40 +0x5a
│ github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc00057e540, 0x3873af0, 0xc00056c680, 0xcc44048, 0xc0002a2050, 0x0, 0x0, 0x0)
│ 	github.com/hashicorp/terraform/terraform/graph_walk_context.go:127 +0xbf
│ github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x334d260, 0xc0002a2050, 0x0, 0x0, 0x0)
│ 	github.com/hashicorp/terraform/terraform/graph.go:59 +0xbd3
│ github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0001727e0, 0x334d260, 0xc0002a2050, 0xc000063dc0)
│ 	github.com/hashicorp/terraform/dag/walk.go:381 +0x288
│ created by github.com/hashicorp/terraform/dag.(*Walker).Update
│ 	github.com/hashicorp/terraform/dag/walk.go:304 +0x1246
│ .
```

### Expected Behavior

`setproduct` should return empty result when an argument is an empty list [as per the documentation](https://www.terraform.io/docs/language/functions/setproduct.html#examples).

### Actual Behavior

It panics.

### Steps to Reproduce

To reproduce the issue you can simply use this TF file:

```terraform
resource "null_resource" "cluster" {
  triggers = {
    cluster_instance_ids = jsonencode(setproduct(
      ["a", "b"],
      []
    ))
  }
}
```

and run `terraform plan`, using version `0.15.1`.

### Additional Context

I tested it on macOS.

**Comment by jbardin** [comment] 2021-05-04 12:21
Duplicate of #28524

**Closed by jbardin** 2021-05-04 12:21 UTC
Labels: bug, new
