### ISSUE TITLE
Assign a variable to a list (hash to a list)

### ISSUE THREAD

**Issue by johnwards** [hashicorp/terraform#4576] opened 2016-01-08 16:57 UTC
So I've gone around the houses on this, and I can't fathom it out.

So I have the following variable defined

    variable "private_subnets" {
      default = {
        "0" = "10.0.2.0/24"
        "1" = "10.0.4.0/24"
        "2" = "10.0.6.0/24"
      }
    }

And I'd like to assign that to an aws security group cidr_blocks. (This doesn't work, but here is what I thought would work)

    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = "${var.private_subnets}"
    }

I have also tried to get around this by getting the "list" from `aws_subnet` and do it through a string or something..

    cidr_blocks = ["${join(",", aws_subnet.private.*.cidr_block)}"]

I also thought this might work, but no..

    cidr_blocks = "${aws_subnet.private.*.cidr_block}"

So couple of things in this ticket:

1) The ability to pass defined "lists" to resources expecting lists
2) Any workarounds for my problem with the current implementation.

**Comment by johnwards** [comment] 2016-01-08 17:06
A follow up to this, I can't seem to get this to work, and this is the example I've seen when I google. I need a list, but this gets me a string.

    resource "aws_elb" "my-elb" {
        instances = ["${join(",", aws_instance.myinstance.*.id)}"]
        subnets = ["${join(",", aws_subnet.private.*.id)}"]

**Comment by radeksimko** [comment] 2016-01-08 17:21
I'm closing this as a duplicate of https://github.com/hashicorp/terraform/issues/57

In terms of workaround until this is actually implemented:

The best you can probably do atm is to leverage [`split()`](https://terraform.io/docs/configuration/interpolation.html#split_delim_string_) and [`join()`](https://terraform.io/docs/configuration/interpolation.html#join_delim_list_) functions:

```hcl
variable "comma_separated_azs" {
  default = "us-west-2a,us-west-2b,us-west-2c"
}

resource "aws_elb" "bar" {
  name = "foobar-terraform-elb"
  availability_zones = ["${split(",", var.comma_separated_azs)}"]

  listener {
    instance_port = 8000
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
}

output "used_azs" {
  value = "${join(",", aws_elb.bar.availability_zones)}"
}
```

Sorry for the confusions caused.

**Closed by radeksimko** 2016-01-08 17:21 UTC

**Comment by johnwards** [comment] 2016-01-08 19:48
@radeksimko Ah yes I guess it is a duplicate, sorry. Got a bit confused with all the +1'ing :)

Based on your reply I've figured out the maddest work around...

    instances = ["${split(",", join(",", aws_instance.eip-elasticsearch.*.id))}"]
 
It works...but bonkers :)

**Comment by deptno** [comment] 2018-02-09 06:53
@radeksimko @johnwards 

I know it was old thread but,,, I found better(?dsadfad?) way

```
instances = ["${flatten(aws_instance.eip-elasticsearch.*.id)}"]
```

it works...but bonkers :)...
