### ISSUE TITLE
terraform does not respect "count" meta-argument in a "data" resource block with new version 1.6.X. Working OK for 1.3.6

### ISSUE THREAD

**Issue by ivaylo-tsv** [hashicorp/terraform#34197] opened 2023-11-07 12:27 UTC
### Terraform Version

```shell
Terraform v1.6.3
```

### Terraform Configuration Files

data "aws_route53_zone" "hosted_zone" {
  **count = local.domain_name != null ? 1 : 0**
  name  = **"${local.domain_name}."**
}

### Debug Output

https://gist.github.com/ivaylo-tsv/3d00750cbd2f512d35a7668e0442f152

### Expected Behavior

Terraform should respect the "count" argument. In this case, **the value of "local.domain_name" is null, so it should not try to read the data resource.** 

### Actual Behavior

Terraform ignores the count argument and **tries to read the data source even though it should not. I**t ends up with an error which is normal because the same **"local.domain_name" is used in the name argument of the data resource. The name argument is a string and since "local.domain_name" is null, it errors out.**

╷
│ Error: Invalid template interpolation value
│ 
│   on data.tf line 31, in data "aws_route53_zone" "hosted_zone":
│   31:   name  = "${local.domain_name}."
│     ├────────────────
│     │ **local.domain_name is null**
│ 
│ The expression result is null. Cannot include a null value in a string template.

### Steps to Reproduce

Use terraform version 1.3.6 to see it's working and then do the same with version 1.6.X to see it is failing

1. terraform init
2. terraform plan 

### Additional Context

The issue appears after upgrading terraform version from 1.3.6 to 1.6.3

**Comment by jbardin** [comment] 2023-11-07 15:04
Hi @ivaylo-tsv,

Thanks for filing the issue. Do you have a more complete example of the case which is failing for you? The example you are showing here has not changed behavior in any v1 releases when `local.domain_name` is statically known to be `null`, so I suspect you have something slightly different in your configuration.

Terraform is not attempting to read the data source, but it is trying to validate the configuration, where it can see that there is a value which will always be `null` being used in a string template. If the `domain_name` were coming from a variable which could change at some point in the future, then Terraform would not fail this particular validation.

**Comment by ivaylo-tsv** [comment] 2023-11-08 06:33
Hi @jbardin ,
Thanks a lot for your support and quick response.

Following on your thoughts, the `domain_name` is coming from a variable which could change at some point in the future, here's the configuration:

```
locals {
  domain_name     = try(replace(local.input_config_file["custom_domain"]["domain_name"], "{stage}", var.stage), null)
}
```

As I am using this re-using this code to deploy infrastructure in two different accounts, one of them has this route53 hosted zone, while the other one does not. 

What I did is to just change the terraform version from 1.3.6 to 1.6.X and vice versa and run plan without changing anything - for the new version it fails, for the old one it succeeds...

**Comment by jbardin** [comment] 2023-11-08 13:18
Hi, thanks foe the extra context. Is it possible to show a complete example, including any variables referenced by the locals? What you have here still appears to be statically proven to evaluate as `null`, in which case improvements to the runtime may have resulted in more precise validation output. The examples I'm coming up with all seem to work when the `domain_name` data and expressions can produce a meaningful result.

**Comment by ivaylo-tsv** [comment] 2023-11-10 10:27
Hey, sure, I will provide more context: 

The local.domain_name looks for a key-value pair in the main configuration file:


```
locals {
  domain_name     = try(replace(local.input_config_file["custom_domain"]["domain_name"], "{stage}", var.stage), null)
 }
```

The local.input_config_file is a path to a JSON-encoded configuration file where all the values for the variables for the terraform code are stored 

```
locals {
  input_config_file = jsondecode(file("../config.json"))
}
```

And a snippet from the configuration file itself shows that there's a value for the domain name:

```
  "custom_domain": {
    "domain_name": "<value>.click"
  },
```
(I've intentionally hidden the actual values)

I'm running the same terraform code for several accounts and I'm just using a different configuration file.
In one of the accounts, we have a Route53 hosted zone. In a second account, we do not. 
That's why I'm using the following check and it's working for an older terraform version I have (1.3.6):

```
data "aws_route53_zone" "hosted_zone" {
  count = local.domain_name != null ? 1 : 0
  name  = "${local.domain_name}."
}
```

Failing after I attempted to bump the terraform version to 1.6.X though...

**Comment by jbardin** [comment] 2023-11-10 14:51
Thanks @ivaylo-tsv, I see what you are trying to do now. The `file` function is essentially acting as your input data, rather than a variable. Because the `file` is still treated as if it is part of the configuration (because it is expected to be static and cannot change at runtime, just like the rest of the config), terraform is seeing that `local.domain_name` cannot be anything except `null` and returning an error when validating the string template. So essentially what is happening is not related to `count`, but rather the static validation has improved and is catching something it did not catch previously.

The workaround here is going to be to inform terraform that `domain_name` is _not_ static somehow. This could be some a number of ways: pass it through `terraform_data` `input` and `output`, through a module via a variable, or probably the simplest, add any variable at all to the `try` arguments. Using `var.stage` doesn't work here because of the use of `try`, which kind of breaks normal evaluation allowing the expression to fail before we ever get to see `var.stage`.

This will work in the latest release:

```
variable "null" {
  default = null
}
locals {
  domain_name     = try(replace(local.input_config_file["custom_domain"]["domain_name"], "{stage}", var.stage), var.null)
}
```

That probably warrants an extra comment in the code, but what it is doing is making the try result unknown during validation. This is because static validation must account for any possible variable input value, so even though it has a default it is treated as unknown to ensure the config is correct for all values.

**Comment by ivaylo-tsv** [comment] 2023-11-24 08:00
Hi @jbardin , sorry for the late response. Thank you for the explanation, the simple workaround seems reasonable so I will apply it and let you know how it goes :)
Regards

**Comment by jbardin** [comment] 2023-12-07 14:18
Since the overall behavior turns out to be working as intended, and there is a workaround for the edge case presented I'm going to close the issue for now.

**Closed by jbardin** 2023-12-07 14:18 UTC
Labels: bug, waiting-response, new
