### ISSUE TITLE
aws_route53_record NS records do not work with lists of zones

### ISSUE THREAD

**Issue by querry43** [hashicorp/terraform#19338] opened 2018-11-09 18:29 UTC
### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.38.0
```

### Terraform Configuration Files

```hcl
variable "zones" {
  type    = "list"
  default = ["foo", "bar"]
}

resource "aws_route53_zone" "zones" {
  count = "${length(var.zones)}"
  name  = "${var.zones[count.index]}"
}

resource "aws_route53_record" "ns_records" {
  count   = "${length(var.zones)}"
  zone_id = "${aws_route53_zone.zones.*.zone_id[count.index]}"
  name    = ""
  type    = "NS"
  ttl     = "900"

  records = [
    "${aws_route53_zone.zones.*.name_servers.0[count.index]}"
  ]
}
```

### Debug Output

https://gist.github.com/querry43/49af5f33a9139709ba4b23a8ca108145

### Expected Behavior

aws_route53_zone.zones.*.name_servers.0 should be a <computed> value which is collected after creating the zone.

### Actual Behavior

TF is unable to determine the value for the nameservers.  This works is the nameservers are commented out and then added after the zone already exists.  Adding depends_on does not change this behavior.

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

This works is the zone records already exist.  Our current workaround is to comment out the ns records to create the zone, then uncomment and add the records in the second pass.

**Comment by apparentlymart** [comment] 2018-11-13 00:17
Hi @querry43! Sorry for this broken behavior, and thanks for reporting it.

This seems to be the same root problem as #17156, which I've confirmed is already fixed in the master branch. See my comment on the other issue for details on how I confirmed that. The fix will be included in the forthcoming v0.12.0 release.

Since there's already a fix in master, I'm going to close this out. Thanks again for reporting this!

**Closed by apparentlymart** 2018-11-13 00:17 UTC
Labels: bug, config
