### ISSUE TITLE
kubernetes backend: No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by ribbybibby** [hashicorp/terraform#26929] opened 2020-11-16 10:55 UTC
The kubernetes state backend doesn't seem to support the [oidc auth-provider](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator). I get the following error on `terraform init` when attempting to use a kubeconfig file with oidc:
```
$ KUBE_LOAD_CONFIG_FILE=true terraform init .

Initializing the backend...

Error: Failed to get existing workspaces: Failed to configure: No Auth Provider found for name "oidc"
```

I think the auth providers may need to be imported, as in the [terraform provider](https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L17):
```
import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)
```
### Terraform Version
```
Terraform v0.13.5
```

### Terraform Configuration Files
```terraform
terraform {
  backend "kubernetes" {
    secret_suffix = "foobar"
  }
}
```

### Debug Output
```
$ TF_LOG=trace KUBE_LOAD_CONFIG_FILE=true terraform init .
2020/11/16 10:42:38 [INFO] Terraform version: 0.13.5
2020/11/16 10:42:38 [INFO] Go runtime version: go1.14.10
2020/11/16 10:42:38 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init", "."}
2020/11/16 10:42:38 [DEBUG] Attempting to open CLI config file: /Users/robertbest/.terraformrc
2020/11/16 10:42:38 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/16 10:42:38 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/16 10:42:38 [DEBUG] ignoring non-existing provider search directory /Users/robertbest/.terraform.d/plugins
2020/11/16 10:42:38 [DEBUG] ignoring non-existing provider search directory /Users/robertbest/Library/Application Support/io.terraform/plugins
2020/11/16 10:42:38 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/16 10:42:38 [INFO] CLI command args: []string{"init", "."}

Initializing the backend...
2020/11/16 10:42:38 [TRACE] Meta.Backend: built configuration for "kubernetes" backend with hash value 143588881
2020/11/16 10:42:38 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/11/16 10:42:38 [DEBUG] New state was assigned lineage "f8aed3c0-7a49-0e3a-aad3-07383a52f699"
2020/11/16 10:42:38 [TRACE] Meta.Backend: moving from default local state only to "kubernetes" backend
2020/11/16 10:42:38 [INFO] Successfully loaded config file (/Users/robertbest/.kube/config; default context)
2020/11/16 10:42:38 [DEBUG] checking for provisioner in "."
2020/11/16 10:42:38 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/11/16 10:42:38 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2020/11/16 10:42:38 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/11/16 10:42:38 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/11/16 10:42:38 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/11/16 10:42:38 [TRACE] statemgr.Filesystem: read nil snapshot
2020/11/16 10:42:38 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
2020/11/16 10:42:38 [DEBUG] New state was assigned lineage "83a9790a-9701-dbab-e6d6-2d84c4c21ee7"
2020/11/16 10:42:38 [TRACE] Preserving existing state lineage "83a9790a-9701-dbab-e6d6-2d84c4c21ee7"

Successfully configured the backend "kubernetes"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: Failed to configure: No Auth Provider found for name "oidc"
```

### Expected Behavior
Module initializes.

### Actual Behavior
Error is produced:
```
Error: Failed to get existing workspaces: Failed to configure: No Auth Provider found for name "oidc"
```

### Steps to Reproduce
With a file at `~/.kube/config` that uses oidc auth:
1. `KUBE_LOAD_CONFIG_FILE=true terraform init .`

**Comment by jrhouston** [comment] 2020-11-20 17:03
Closing this as it is a dupe of https://github.com/hashicorp/terraform/issues/26479, please track progress in that issue.

**Closed by jrhouston** 2020-11-20 17:03 UTC
Labels: backend/k8s, bug
