### ISSUE TITLE
terraform import fails with Error: Invalid resource instance data in state

### ISSUE THREAD

**Issue by sr-mpamera** [hashicorp/terraform#31131] opened 2022-05-25 20:48 UTC
Terraform import fails with Error: Invalid resource instance data in state

**Expected behaviour**
imported successfully

**Actual behaviour**
```
Error: Invalid resource instance data in state

  on ../../terraform/modules/repository.tf line 1:
   1: resource "github_repository" "repository" {

Instance
module.repository-test.module.repository.github_repository.repository
data could not be decoded from the state: unsupported attribute "branches"
```

**terraform version** 
0.14.10

Editing the state file and pushing works fine. But, is there any other solution apart from manually editing the state file.

**Comment by jbardin** [comment] 2022-05-26 13:05
Duplicate of #30746

**Closed by jbardin** 2022-05-26 13:05 UTC
Labels: bug, new
