### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by josh-padnick** [hashicorp/terraform#11394] opened 2017-01-24 23:54 UTC
I suspect the issue is because I'm using `data.aws_alb` and then looking up properties from that.

### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
My template has many resources, but here are the "delta" resources between "didn't crash" and "crashed":
- aws_security_group_rule
- data.aws_alb

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Here's a relevant snippet:

```hcl
resource "aws_security_group_rule" "allow_inbound_from_alb" {
  count = "${var.num_alb_arns}"
  type = "ingress"
  from_port = "32768"
  to_port = "65535"
  protocol = "tcp"
  source_security_group_id = "${element(element(data.aws_alb.ecs_albs.*.security_groups, count.index), 0)}"
  security_group_id = "${aws_security_group.ecs.id}"
}

resource "aws_security_group_rule" "allow_outbound_from_alb_to_ecs_cluster" {
  count = "${var.num_alb_arns}"
  type = "egress"
  from_port = "32768"
  to_port = "65535"
  protocol = "tcp"
  source_security_group_id = "${aws_security_group.ecs.id}"
  security_group_id = "${element(element(data.aws_alb.ecs_albs.*.security_groups, count.index), 0)}"
}

data "aws_alb" "ecs_albs" {
  count = "${var.num_alb_arns}"
  arn  = "${var.alb_arns}"
}
```

### Debug Output
Didn't capture this.

### Panic Output
https://gist.github.com/josh-padnick/4bb9585602441385326a4f24de52db5a

### Expected Behavior
There should have been no crash.

### Actual Behavior
Terraform crashed.

**Comment by josh-padnick** [comment] 2017-01-24 23:57
I've confirmed the crash is avoided when the `data.aws_alb` resources is removed from the templae.

**Comment by josh-padnick** [comment] 2017-01-24 23:58
Actually, it goes away when I remove the `count` property from `data.aws_alb`. I then got this error:

```
* data.aws_alb.ecs_albs: Error retrieving ALB: ValidationError: 'sg-73d8611a' is not a valid load balancer ARN.
```

**Comment by josh-padnick** [comment] 2017-01-25 00:19
Ok, when I fixed my error of passing in a Security Group ID instead of an ARN, that resolved the issue. Although, I ran into a separate issue around flattening lists of lists (which doesn't appear doable yet in Terraform), it appears this crash is caused by an error in the underlying `data.aws_alb` resource when an invalid ARN is passed in.

**Comment by mitchellh** [comment] 2017-01-25 19:41
I can't reproduce this with your config. Can you please double check your repro?

I tried:

1. Copy and paste example
2. Replace account-specific identifiers with my own
3. Add variables (both type string) for ARN/count
4. `apply`

Worked!

**Comment by josh-padnick** [comment] 2017-01-25 19:45
@mitchellh Thanks for taking a look at this! Did you specify an invalid value such as a Security Group ID for the ARN? Also, I had this code two modules deep as follows:

- A includes Module B.
- B includes Module C.
- Reference code above is in Module C.

Hope that helps. Since I've since fixed this and merged my PR, it'd be cumbersome for me to repro as well at this point!

**Comment by mitchellh** [comment] 2017-01-25 19:48
I did, I tried a valid ID, an invalid ID, and I tried changing the type to a list and passing that in. All were caught in some way or the other and didn't result in a crash. :(

Well, I'll close this for now. If we can get a repro then I'm happy to fix, of course.

**Closed by mitchellh** 2017-01-25 19:48 UTC
Labels: bug, core, crash, waiting-response

**Comment by josh-padnick** [comment] 2017-01-25 19:50
Fair enough. Thanks for such prompt responsiveness on this crash! Also, "what to do now that you've experienced a crash" messaging in Terraform itself was great.

**Comment by mitchellh** [comment] 2017-01-25 19:53
Thanks, sorry I couldn't dig deeper :(
