### ISSUE TITLE
Module Source Interpolation ?

### ISSUE THREAD

**Issue by octravis** [hashicorp/terraform#18063] opened 2018-05-16 16:19 UTC
Hi Support,

I was attempting use interpolation on the module source. Is this allowed ?, seems to pass the string with not interpolation?

```
from variables.tf 
variable "github_location" {
  type = "string"
  default = "https://github.com/xxxxx"
}
from main.tf
module "push_hostfile" {
  source = “${format(“%s%s”, var.github_location, “/vmware_provision”)}”

terraform init
Initializing modules...
- module.deployVM_singlenode
  Getting source "${format(\"%s%s\", var.github_location, \"/vmware_provision\")}"
```

### Terraform Version
Terraform v0.11.7

### Expected Behavior
Initialize the module with the interpolated github_location

### Actual Behavior
Initializing modules...
- module.deployVM_singlenode
  Getting source "${format(\"%s%s\", var.github_location, \"/vmware_provision\")}"

**Comment by jbardin** [comment] 2018-05-16 23:11
Hi @octravis,

Sorry this tripped you up. Interpolations are not allowed in that field, because the module need to be fetched early on before we have a complete config for interpolation.

I just checked though, and it seems this is only called out in passing here: https://www.terraform.io/docs/modules/sources.html#private-github-repos, so we should probably highlight it better in the documentation.

**Comment by dtzar** [comment] 2019-04-02 21:55
It would be very nice to have the ability for interpolation here for allowing easier ability to switch between local development (i.e. .`./`) and people referencing the same code in an external source (i.e. Github).  This becomes a pain point when running a PR/CI system against a module which references an external source.

**Comment by pcj** [comment] 2019-04-02 21:57
Duplicate of https://github.com/hashicorp/terraform/issues/1439

**Comment by apparentlymart** [comment] 2019-04-02 22:35
Indeed, this is the same as #1439, so I'm going to close this out. The other issue has some extensive discussion on why this isn't allowed and what you might do instead for certain use-cases. If you have a use-case that isn't covered by it, please open [a new Feature Request issue](https://github.com/hashicorp/terraform/issues/new?labels=enhancement&template=feature_request.md)  about what you are trying to achieve; your problem will not be solved by supporting arbitrary expressions in the `source` argument, but we can hopefully find some other way to address it that works within the Terraform architecture.

**Closed by apparentlymart** 2019-04-02 22:35 UTC
Labels: documentation

**Comment by dtzar** [comment] 2019-04-02 22:38
This issue was to document that this isn't supported in the upstream documentation...

**Comment by apparentlymart** [comment] 2019-04-02 22:43
The forthcoming Terraform v0.12.0 release includes a specific error message for this case that will be shown if you try to use variables or functions in the `source` argument. 

[The documentation](https://github.com/hashicorp/terraform/issues/new?labels=enhancement&template=feature_request.md) also already reflects that constraint:

> This value must be a literal string with no template sequences; arbitrary expressions are not allowed.

The older documentation for Terraform v0.11 also reflects this, using more v0.11-oriented terminology:

> This value must be a literal string with no template sequences; interpolations are not allowed.

([Templates](https://www.terraform.io/docs/configuration/expressions.html#string-templates) are the extended idea of "interpolations" in v0.12, after conditionals and repetition were added.)
