### ISSUE TITLE
Apply does more than indicated by the plan....and fails

### ISSUE THREAD

**Issue by traeddle** [hashicorp/terraform#25048] opened 2020-05-27 00:51 UTC
### Terraform Version

```
Terraform v0.12.25
 + provider.azurerm v2.11.0
```

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "func_app" {
  name                       = var.function_name
  location                   = var.location
  resource_group_name        = var.resource_group_name
  app_service_plan_id        = data.azurerm_app_service_plan.func_plan.id
  storage_account_name       = var.storage_account_name
  storage_account_access_key = var.storage_account_access_key
  version                    = "~3"
  enable_builtin_logging     = false
  tags = {
    APP_ID        = "2418"
  }
  app_settings = var.app_settings

  lifecycle {
    ignore_changes = [
      site_config.0.ip_restriction
    ]
  }
  
}
```

### Crash Output
Error: Error updating Function App "az-2418-eastus2-audit-dev-func" (Resource Group "az-2418-eastus2-apps-rg"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '8641b997-ec46-483c-9bc8-5e3067e79e98' with object id '8641b997-ec46-483c-9bc8-5e3067e79e98' has permission to perform action 'Microsoft.Web/sites/write' on scope '/subscriptions/2005f8d7-02af-478f-bc2b-bda3dd077553/resourceGroups/az-2418-eastus2-apps-rg/providers/Microsoft.Web/sites/az-2418-eastus2-audit-dev-func'; however, it does not have permission to perform action 'joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/2005f8d7-02af-478f-bc2b-bda3dd077553/resourceGroups/az-2418-eastus2-network-rg/providers/Microsoft.Network/virtualNetworks/tf-az-2418-eastus2-vnet/subnets/tf-az-2418-eastus2-subnet1-subnet' or the linked scope(s) are invalid."

### Expected Behavior
Update according to the plan

### Actual Behavior
It tries to do something with the vnet, which it's not allowed to do

### Steps to Reproduce
1. Provision function app using tf script
2. Put the function app in a vnet via azure portal
3. Adjust an app setting value in the TF script
4. Rerun your terraform script to output plan
5. Check plan you should only see the value change
6. Run the plan. If the credentials your running your script with doesn't have access to the joinViaServiceEndpoint action, it will give the error

### Additional Context
This is currently running as part of a GitLab CI/CD pipeline so there's a lot of custom code, and modules.
The scripts work when the azurerm_function_app resource has no other updates, or if the function is not part of the vnet.

We added the lifecycle block in our desperate attempt to force it to ignore what we believe is the culprit

**Comment by Justin-DynamicD** [comment] 2020-05-27 17:23
By your description, this is intended.

You've modified the azure function in step 2 outside of terraform, therefore when you run it is going to try to revert the change back to the stored config, which is no VNet.  This is the heart of declarative config.

If you really want to allow outside forces to tweak/update a setting without TF attempting to change it back, then you need to tell TF to ignore changes in that setting.  This is done _within_ the resource with a lifecycle block:

```
lifecycle {
    ignore_changes = [subnet, ]
  }
```

(modify the name subnet to the actual app service field name, I don't know it off the top of my head, but you can see it easily enough if you run a `terraform plan` to look at changes)

**Comment by traeddle** [comment] 2020-05-27 23:09
@Justin-DynamicD thank you for your reply.
You are correct and I was expecting to have to do something to remedy the situation, but the plan shows no changes beyond app setting. As you can see in the plan below it's showing FUNCTIONS_EXTENSTION_VERSION is going to be added to the app_settings, and no other changes.

This is a concern as the plan is not properly showing what changes are actually happening, and I've tried adding the below and all variants of it i could think of.  I don't see anything specific for subnet outside of this.

```
lifecycle {
    ignore_changes = [
      site_config.0.ip_restriction
    ]
  }
```

The execution plan
```
An execution plan has been generated and is shown below.
 Resource actions are indicated with the following symbols:
   ~ update in-place
 Terraform will perform the following actions:
   # module.function.azurerm_function_app.func_app will be updated in-place
   ~ resource "azurerm_function_app" "func_app" {
         app_service_plan_id            = "[redacted]"
       ~ app_settings                   = {
             "APPINSIGHTS_INSTRUMENTATIONKEY" = "[redacted]"
           + "FUNCTIONS_EXTENSION_VERSION"    = "~1"
             "FUNCTIONS_WORKER_RUNTIME"       = "dotnet"
             "KeyVaultURI"                    = "blah"
             "MORE"                           = "another value"
             "SCM_DO_BUILD_DURING_DEPLOYMENT" = "false"
             "WEBSITE_NODE_DEFAULT_VERSION"   = "6.5.0"
             "anothervalue"                   = "blah blahb lah"
         }
         client_affinity_enabled        = false
         daily_memory_time_quota        = 0
         default_hostname               = "[redacted]"
         enable_builtin_logging         = false
         enabled                        = true
         https_only                     = false
         id                             = "[redacted]"
         kind                           = "functionapp"
         location                       = "eastus2"
         name                           = "az-2418-eastus2-travistest-dev-func"
         outbound_ip_addresses          = "[redacted]"
         possible_outbound_ip_addresses = "[redacted]"
         resource_group_name            = "az-2418-eastus2-apps-rg"
         site_credential                = [
             {
                 password = "[redacted]"
                 username = "[redacted]"
             },
         ]
         storage_account_access_key     = (sensitive value)
         storage_account_name           = "[redacted]"
         storage_connection_string      = (sensitive value)
         tags                           = {
             "APP_ID"        = "2418"
         }
         version                        = "~3"
         auth_settings {
             additional_login_params        = {}
             allowed_external_redirect_urls = []
             enabled                        = false
             token_refresh_extension_hours  = 0
             token_store_enabled            = false
         }
         identity {
             identity_ids = []
             principal_id = "[redacted]"
             tenant_id    = "[redacted]"
             type         = "SystemAssigned"
         }
         site_config {
             always_on                 = false
             ftps_state                = "AllAllowed"
             http2_enabled             = false
             ip_restriction            = [
                 {
                     ip_address = ""
                     subnet_id  = "[subnet id]"
                 },
             ]
             min_tls_version           = "1.2"
             pre_warmed_instance_count = 0
             use_32_bit_worker_process = true
             websockets_enabled        = false
             cors {
                 allowed_origins     = [
                     "https://functions-next.azure.com",
                     "https://functions-staging.azure.com",
                     "https://functions.azure.com",
                 ]
                 support_credentials = false
             }
         }
         timeouts {}
     }
 Plan: 0 to add, 1 to change, 0 to destroy.
```

Side note:
I don't want outside forces playing with this, but I'm playing the game with the rules I'm given.  :D Thanks again!

**Comment by danieldreier** [comment] 2020-05-29 00:24
Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core. It looks like there's a productive discussion happening here, and I'm appreciative @Justin-DynamicD jumping in here. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is move this discussion to the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug, I need a full standalone reproduction case that I can run on my own workstation, where I don't need to invent any details. The case you posted is helpful, but not quite enough for me to run on my own, because there's variable data I'd need to fill in.

Based on my work so far, I recommend you take this to the community forum for assistance in troubleshooting. I'm going to close this for now, because I think the community forum is the right approach. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you'd rather work up a reproduction case here.

**Comment by jfh-xfer** [comment] 2020-05-29 15:37
@danieldreier thanks for the input.
I do feel like this is a bug, and I'll work on a something to reproduce this. I'll post it here once i have something.

**Comment by traeddle** [comment] 2020-05-29 15:39
Thanks for your reply @danieldreier 
I'll work one a fully standalone reproduction as you suggested, and post here

**Comment by danieldreier** [comment] 2020-05-29 15:45
Thanks @traeddle! I've re-opened the issue.

**Closed** 2020-05-29 17:20 UTC
Labels: provider/azurerm, waiting-response
