### ISSUE TITLE
Defaults function with map objects

### ISSUE THREAD

**Issue by cgperalt-harness** [hashicorp/terraform#31319] opened 2022-06-25 05:20 UTC
Hello,

I defined a variable whose type is a map of objects and I would like to set some default values. For example:

```variable "node_pools" {
  type = map(object({
    name                 = string
    cluster_name         = optional(string)
    location             = optional(string)
    node_config          = object({
      machine_type       = string
      image_type         = string
      labels             = map(string)
      oauth_scopes       = list(string)
      taint              = list(map(string))
      tags               = list(string)
    })
    autoscaling          = object({
      min_node_count     = number
      max_node_count     = number
    })
    management           = object({
      auto_repair        = bool
      auto_upgrade       = bool
    })
    upgrade_settings     = object({
      max_surge          = number
      max_unavailable    = number
    })
  }))
}

locals {
  node_pools = defaults(var.node_pools,{
    cluster_name = "k8s-private"
    location = "us-central1-a"

  })
}
```
However, the values are not getting populated since I'm getting the below error 
```╷
│ Error: Missing required argument
│
│   with module.node_pools.google_container_node_pool.this["primary-nodepool"],
│   on ../modules/gke/nodepool.tf line 5, in resource "google_container_node_pool" "this":
│    5:   cluster = each.value.cluster_name 
│
│ The argument "cluster" is required, but no definition was found.
```

So I was wondering if the defaults function works with `type = map(object({})` ?

Thanks

**Comment by jeheyer** [comment] 2022-06-25 19:39
Same here.  defaults() works great with objects but not sure how to use with maps of objects.  My code:

`
variable "healthchecks" {
  description = "Map of Heath Checks"
  type = map(object({
    port         = optional(number)
    protocol     = optional(string)
    interval     = optional(number)
    timeout      = optional(number)
  }))
  default = {}
}
locals {
  healthchecks = defaults(var.healthchecks, {
    protocol     = "HTTP"
    port         = 80
    interval     = 20
    timeout      = 3
  })
}
module "healthchecks" {
  source       = "../../resources/google_compute_health_check"
  for_each     = var.healthchecks
  name         = each.key
  protocol     = coalesce(each.value.protocol, local.healthchecks.protocol)
}
`

**Comment by alisdair** [comment] 2022-06-27 13:21
Thanks for the issue. The `defaults` function does not work well for some use cases with collections of objects. For this reason, in the upcoming Terraform 1.3 release, we have implemented a different design of optional object attributes with defaults.

We've released this for early testing and feedback in the 1.3 alpha series. [Please see this forum post for more details](https://discuss.hashicorp.com/t/request-for-feedback-optional-object-type-attributes-with-defaults-in-v1-3-alpha/40550).

Part of this change will be to remove the `defaults` function altogether, so I'm marking this as closed, since we won't be changing its behaviour. If you have any feedback around this feature, we'd love to hear it over in the forum thread!

**Closed** 2022-06-27 13:38 UTC
Labels: bug, explained, experiment/module_variable_optional_attrs

**Comment by cgperalt-harness** [comment] 2022-06-27 15:44
@alisdair Thank you for your response! I just tested terraform 1.3 and it works great for my use case.
Thanks.

**Comment by cregkly** [comment] 2022-06-28 04:19
Both of these examples can be made to work with defaults until the 1.3 version is released.

@cgperalt-harness You didn't provide enough code to see where the problem is. Copy the variable, local to a blank root module and test with the terraform console.

@jeheyer This is the fixed code.

```
variable "healthchecks" {
  description = "Map of Heath Checks"
  type = map(object({
    port         = optional(number)
    protocol     = optional(string)
    interval     = optional(number)
    timeout      = optional(number)
  }))
  default = {}
}
locals {
  healthchecks = defaults(var.healthchecks, {
    protocol     = "HTTP"
    port         = 80
    interval     = 20
    timeout      = 3
  })
}
module "healthchecks" {
  source       = "../../resources/google_compute_health_check"
  for_each     = local.healthchecks // This should be the local with the defaults added
  name         = each.key
  protocol     = each.value.protocol
}
```
