### ISSUE TITLE
Terraform state mv not working on remote states

### ISSUE THREAD

**Issue by mateusduboli** [hashicorp/terraform#15815] opened 2017-08-15 17:48 UTC
I have a terraform structure that uses a remote state in S3.

During the refactoring of names to keep consistency of formats. But, when I tried to rename the resources in the state file, I stumbled upon an error that asked the state instead to be local, even though I have the backend configuration in the `.tf` file.

Command:
```
terraform state mv 'module.vpc.aws_resource.resource-name' 'module.vpc.aws_resource.resource_name' # note the switch from - to _
```

Output

```
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.
```

I tried to use `terraform state list` and it worked without any issue.

### Terraform Version
`Terraform v0.10.0`

### Terraform Configuration Files
```hcl
provider "aws" {
  profile = "production"
}

module "prod" {
  region           = "us-east-1"
  source           = "../../modules/vpc"
  env              = "prod"
}

module "data" {
  region           = "us-east-1"
  source           = "../../modules/vpc"
  env              = "data"
}

module "stg" {
  region           = "us-east-1"
  source           = "../../modules/vpc"
  env              = "stg"
}

module "dev" {
  region           = "us-east-1"
  source           = "../../modules/vpc"
  env              = "dev"
}

terraform {
  backend "s3" {
    profile = "production"
    bucket  = "tfstate"
    key     = "terraform.tfstate"
  }
}
```

### Debug Output
[Log](https://gist.github.com/mateusduboli/ff50963fe4303c807cab9acd07e280f7)

### Expected Behavior
Move the resources in the state file in S3

### Actual Behavior
An error message asking to provide a local state

### Steps to Reproduce
`terraform state mv 'module.dev.aws_vpn_gateway_route_propagation.vpn-route' 'module.dev.aws_vpn_gateway_route_propagation.vpn_route'`

### Important Factoids
`terraform state list` works without a problem.

### References

**Comment by apparentlymart** [comment] 2017-08-15 18:53
Hi @mateusduboli! Sorry for this regression.

This seems to be the same problem as was fixed in #15652. This is not yet included in a release, but we are planning to release 0.10.1 very soon to get this and other bug fixes out.

**Closed by apparentlymart** 2017-08-15 18:53 UTC
Labels: bug, cli
