### ISSUE TITLE
Variable within variable

### ISSUE THREAD

**Issue by luckerby** [hashicorp/terraform#27783] opened 2021-02-16 12:02 UTC
I'm trying to use the value of a variable inside a variable. Unlike this to be treated as an error, as it was reported [previously](https://stackoverflow.com/questions/58841060/terraform-variables-within-variables), I get an empty value as a result.

The scenario I'm working on involves creating an Azure assignment for a policy, but I don't think the issue is with the `azurerm` provider, but probably with terraform itself.

As for the details: in the variables file I'm simply using a variable to reference the value of a different one:

```
variable "cust_scope" {
    type = string
    default = "{var.scope}"
}

variable "scope" {
    description = "Scope where the target Azure Policies will apply"
    type = string
    default = "/subscriptions/6506b559-5861-471b-aa74-11b06d0688a3/resourceGroups/AzurePolicies-rg"
}
```

Then in my main file I'm creating a resource that uses the value of the "double-referenced" variable above:
```
resource "azurerm_policy_assignment" "require_tag_on_resources" {
    name = "ap-ng-dev-audit-no-tags-on-resources"
    scope = var.cust_scope
    .....
}
```

Running `terraform apply` looks like below:
![image](https://user-images.githubusercontent.com/31319583/108059356-0f3fac80-705e-11eb-81b0-b57dc2a09993.png)

Trying to move ahead and apply the changes fails, as the `azurerm` provider complains because it sees no subscription (most likely since the value of the `scope` variable is seen as empty)
```
Error: creating/updating Policy Assignment "ap-ng-dev-audit-no-tags-on-resources" (Scope "{var.scope}"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="MissingSubscription" Message="The request did not have a subscription or a valid tenant level resource provider."
```

I know that locals should be used instead for the scenario above, my only question is why doesn't this fail, as opposed to resulting in an empty value.

Terraform is `v0.14.6`.

**Comment by Poil** [comment] 2021-02-16 13:07
missing a $ no? `${var.scope}` ?

**Comment by jbardin** [comment] 2021-02-16 14:07
Hi @luckerby 

Thanks for filing an issue. Variable default require static values, and are not interpolated. The usual option here is to refer to a local value, which is conditionally set based on the variable value itself.

Since Terraform is working as designed, I'm going to close this out for now. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-02-16 14:07 UTC
Labels: bug, new

**Comment by luckerby** [comment] 2021-02-16 14:55
@Poil True, I realized afterwards. Correcting my typo results in the [expected error message](https://stackoverflow.com/questions/58841060/terraform-variables-within-variables).

@jbardin Thank you for your answer.
