### ISSUE TITLE
Terraform hangs under Windows

### ISSUE THREAD

**Issue by toralf** [hashicorp/terraform#28729] opened 2021-05-18 08:00 UTC
Both under a Windows Terminal, Git Bash or Cygwin we do observe, that a `terraform plan` or even a ´terraform version` hangs sporadically:
```
$> terraform --version
Terraform v0.14.11

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html
```
This happened not every time and we do wonder, if this is a network hang at our side or at yours ?
FWIW it does not happened for `terraform` running under WSL2 (Debian), just the windows version is affected.

**Comment by jbardin** [comment] 2021-05-18 12:32
Hi @toralf,

Thanks for filing the issue. If Terraform behaves as expected under WSL2, it would appear that the difference in on your side with the windows host itself. The usual culprits in this area are anti-malware programs, DNS or network configuration.

Since there's no details to work with in this issue, I'm going to close as a duplicate of an existing windows issue #27170.
If you have more information, feel free to add it there. If you have questions, there are more people ready to help in the [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!

**Closed by jbardin** 2021-05-18 12:32 UTC
Labels: bug, new
