### ISSUE TITLE
Unable to set a Json file as Step in EMR

### ISSUE THREAD

**Issue by hdryx** [hashicorp/terraform#21701] opened 2019-06-12 07:39 UTC
I'm building an EMR cluster in Terraform and in the STEP argument i want to load a JSON file that describes the list of steps.

I tried this in my main.tf :

```
ressource "aws_emr" "emr" {
  ...
  ...
  step = "${data.template_file.steps.rendered}"
}

data "template_file" "steps" {
  template = "${file("${path.module}/steps.json")}"
}
```
And this is the JSON file :

```
[
{
    "action_on_failure" : "CONTINUE",
    "name"              : "step_name",
    "hadoop_jar_step" : {
        "jar" : "command-runner.jar",
        "args" : [
            "spark-submit",
            "s3://mybucket/src/pyspark/script1.py",
            "1",
            "68465131321321",
            "s3://mybucket/parquet",
            "s3://mybucket/result",
            "321",
            "65165165468587",
            "654"
        ]
    }
}
]
```
But when i do terraform plan i got this error :

> Inappropriate value for attribute "step": list of object required.

What's the problem ?

Thanks for your help.

**Comment by mildwonkey** [comment] 2019-06-12 13:28
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by hdryx** [comment] 2019-06-12 14:12
> Hi!
> 
> Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

Sorry for that, i though it was a bug ...

**Comment by mildwonkey** [comment] 2019-06-12 14:27
That's entirely possible, and why I didn't close this issue. I just wanted you to know that you might get a faster response from another forum. 

If you believe you are experiencing a bug, we'll need some more information so we can reproduce the issue and identify the cause. Can you please update this ticket with the missing information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? The terraform version and trace logs from the failed plan will be especially helpful. Remove any sensitive information first.

**Comment by john-auld** [comment] 2019-06-12 22:42
This is not a bug.

For an aws_emr_cluster resource, you could use the rendered content of a  template as the value of "configurations_json", because that configuration element expects a string.

However, "step" requires an object and you are providing a string (the rendered json).

You need to configure the resource as described in the resource documentation.

**Closed** 2019-06-14 09:03 UTC
Labels: question
