### ISSUE TITLE
Confusing error message when using splat and for-loop with merge and vars

### ISSUE THREAD

**Issue by iridian-ks** [hashicorp/terraform#25124] opened 2020-06-03 23:06 UTC
### Terraform Version

```
✗ terraform version
Terraform v0.12.26
+ provider.aws v2.54.0
+ provider.bigip v1.1.2
+ provider.consul v2.7.0
+ provider.grafana v1.5.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.rabbitmq v1.3.0
+ provider.rancher2 v1.7.3
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
+ provider.vault v2.11.0

```

### Terraform Configuration Files

I believe the error message actually has all the context needed to understand the issue.

```hcl
✗ terraform apply

Error: Invalid expanding argument value

  on ../../modules/role-kube/main.tf line 203, in locals:
 203:   }, merge([
 204:     for name, instance in local.scm :
 205:     {
 206:       "scm_api_${name}_user" = instance.api.user
 207:       "scm_api_${name}_pass" = instance.api.pass
 208:     }
 209:   ]...))

The expanding argument (indicated by ...) must be of a tuple, list, or set
type.
```

### Expected Behavior

1. Based off of the documentation, I would have expected a list of maps merging into a single map.

2. The error message to tell me why it failed. It says that the type is expected to be a tuple, list, or set. Based off of the source we can see that the type should definitely be a list, but obviously that isn't the case and I don't know how to proceed based off of the error message. I would have expected the error message to tell me what type it did receive.

### Actual Behavior

1. Got an error that results in the plan failing.

2. The error message is a tad vague and unhelpful.

### Steps to Reproduce

My example has a lot of context in it so I created a new plan using null resource to isolate the issue.

```
variable "debug" {
  type = map(string)
  default = {"one" = "two", "three" = "four"}
}

locals {
  debug = merge([
    for i, element in var.debug :
    {
      "${i}" = element
    }
  ]...)
}

resource "null_resource" "debug" {
  for_each = local.debug
  triggers = {
    debug = "${each.key}:${each.value}"
  }
}
```

When we run this plan we see the same error messages:

```
$ terraform init
...
$ terraform apply

Error: Invalid expanding argument value

  on main.tf line 7, in locals:
   7:   debug = merge([
   8:     for i, element in var.debug :
   9:     {
  10:       "${i}" = element
  11:     }
  12:   ]...)

The expanding argument (indicated by ...) must be of a tuple, list, or set
type.

```

### Additional Context

Here's the fun part. If we replace the vars with locals this actually works just fine.

```
locals {
  debug_map = {"one" = "two", "three" = "four"}
  debug = merge([
    for i, element in local.debug_map :
    {
      "${i}" = element
    }
  ]...)
}

resource "null_resource" "debug" {
  for_each = local.debug
  triggers = {
    debug = "${each.key}:${each.value}"
  }
}
```

Running this we get:

```
terraform apply -auto-approve
null_resource.debug["three"]: Creating...
null_resource.debug["one"]: Creating...
null_resource.debug["one"]: Creation complete after 0s [id=2938249967867437483]
null_resource.debug["three"]: Creation complete after 0s [id=3497091563260658580]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```

**Comment by apparentlymart** [comment] 2020-06-03 23:47
Hi @iridian-ks! Thanks for reporting this.

I think this is the same root cause as #22404, so I'm going to close this only to consolidate the discussion there. Thanks again!

**Closed by apparentlymart** 2020-06-03 23:47 UTC
Labels: bug, config, v0.12
