### ISSUE TITLE
Adding possibility to use a variable inside source declaration of a module

### ISSUE THREAD

**Issue by Ikeajoel** [hashicorp/terraform#27624] opened 2021-01-29 07:50 UTC
Hi It would make life a lot easier if you added the possibility to add a variable inside source declaration of a module.

module "example_module" {
  source = "git@${git.repo}=${var.module_version}"
  ...
  }

**Comment by jbardin** [comment] 2021-01-29 14:39
Duplicate of #25587

**Closed by jbardin** 2021-01-29 14:39 UTC
Labels: enhancement, new
