### ISSUE TITLE
PowerDNS API request not compatible with PowerDNS 4

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#7790] opened 2016-07-24 22:31 UTC
Terraform 0.6.16
PowerDNS 4.0.0

see https://github.com/PowerDNS/pdns/issues/3492

They have moved the 'ttl' out of the record into the rrsets array. So the PowerDNS API request is no longer compatible.

example code

```
# Configure the PowerDNS provider
provider "powerdns" {
    api_key = "abcd1234"
    server_url = "http://127.0.0.1:8081/api/v1"
}

# Create a record
resource "powerdns_record" "www2" {
    zone = "example.net"
    name = "www2.example.net."
    type = "A"
    ttl = 300
    records = ["10.10.10.10"]
}
```

Output

```
* powerdns_record.www2: Failed to create PowerDNS Record: Error creating record set: www2.example.net.:::A, reason: "Key 'ttl' not an Integer or not present"
```

**Comment by smuth4** [comment] 2016-07-25 15:21
Hey @gtmtech, this looks like the same issue as https://github.com/hashicorp/terraform/issues/6056. I actually have a fix here: https://github.com/hashicorp/terraform/compare/master...smuth4:pdns-4. I've rebased the branch, and can re-test and open a pull request for at least a review this evening.

**Comment by gtmtech** [comment] 2016-07-25 16:25
Yeah this looks good - we need to get this merged. If you can retest, I can offer to review on terraform. 

You did more than me in my branch, I just abandoned PowerDNS3, and tweaked it to just work for 4!

**Comment by stack72** [comment] 2016-07-26 11:42
Hi @gtmtech 

I am going to close this as the dupe of #6056 

That way we can keep all the conversation regarding the issue / PR there

Paul

**Closed** 2016-07-26 11:43 UTC
Labels: bug, provider/powerdns
