### ISSUE TITLE
Terraform init hangs when etcdv3 backend is misconfigured

### ISSUE THREAD

**Issue by avorima** [hashicorp/terraform#21181] opened 2019-05-02 12:28 UTC
### Terraform Version

```
Terraform v0.11.13

```

### Terraform Configuration Files

```hcl
terraform {
  backend "etcdv3" {
    endpoints = ["some.random.host"]
  }
}
```

### Expected Behavior

Terraform init should fail, because the connection to etcd backend couldn't be established.

### Actual Behavior

Terraform hangs forever.

### Steps to Reproduce

```
terraform init
```

### Additional Context

The etcd client has a dial timeout config option that would prevent this, but terraform doesn't allow setting it.

**Comment by jsok** [comment] 2019-10-08 03:06
Can confirm behaviour - I accidentally mixed up my cacert_path and cert_path and terraform just hung indefinitely.

**Comment by mildwonkey** [comment] 2020-08-27 20:30
This is a duplicate of #19185, so I will close this one to consolidate conversation there. Thanks!

**Closed by mildwonkey** 2020-08-27 20:30 UTC
Labels: backend/etcdv3, bug, v0.11
