### ISSUE TITLE
conditionals does not resolve/interpolate asterisk (*)

### ISSUE THREAD

**Issue by zbikmarc** [hashicorp/terraform#11233] opened 2017-01-17 09:08 UTC
I have two types of resources:
- instance w/ extra disk
- instance w/o  extra disk

I am selecting only one of them depending on `extra_disk_size` variable. If its > 0, there are X instances w/ extra disk created, otherwise X instances w/o extra disk.

Finally I want to ouput their IPs and I wanted to use:
`value = ["${ var.extra_disk_size > 0 ? google_compute_instance.instance-with-disk.*.network_interface.0.address : google_compute_instance.instance-without-disk.*.network_interface.0.address}"]`
However it returns... nothing.

I double checked if conditional is good and changed it to:
`value = ["${ var.extra_disk_size > 0 ? "there are extra disks" : "there are NO extra disks"}"]`
And it worked.

So I decided to check if my interpolation is right and did just:
`value = ["${google_compute_instance.instance-without-disk.*.network_interface.0.address}"]`
and of course it worked flawlessly. Just to be 100% sure that is `*` in conditional not conditional itself I changed `*` to `0` and It also returned mi IP, one IP but it proved it works well.
#10854 looks similar to this issue.

BTW those issues would solve this problem other way: #10182 #7034

**Comment by mitchellh** [comment] 2017-01-24 21:11
This is actually #9080 coming up :( 

The issue is this error message getting swallowed `conditional operator cannot be used with list values`. This is due to a limitation in the interpolation language at the moment and @apparentlymart is looking into removing this limitation. The work is underway. 

Closing for #9080

**Closed by mitchellh** 2017-01-24 21:11 UTC
Labels: bug, core
