### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by LunaticZorr** [hashicorp/terraform#26200] opened 2020-09-10 12:33 UTC
Trying to run `terraform init` and getting the following error message:

```
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching "3.5.0, ~> 3.5.0, ~> 2.53"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints 3.5.0, ~> 3.5.0, ~> 2.53
```

The following are my config files.

**providers.tf**

```
terraform {
  required_version = ">= 0.13"
}

provider "aws" {
  version                 = "~> 3.5.0"
  region                  = "eu-west-2"
  shared_credentials_file = "~/.aws/credentials"
}
```

And **versions.tf**

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.5.0"
    }
  }
}
```

I've searched online for solutions and tried a couple of things from the documentation and git but always get the same error. Any help is appreciated.

**Comment by alisdair** [comment] 2020-09-11 20:08
@LunaticZorr Your provider constraints are unsatisfiable. It looks like you have multiple constraints, probably in several locations in your configuration. `3.5.0` and `~> 3.5.0` are compatible, but, `~> 2.53` basically means `> 2.0.0, < 3.0.0`. As you can imagine, you can't install a provider version which is both equal to `3.5.0` and `< 3.0.0`.

The fix for this is to find which module or file contains the additional version constraint, and update it so that all of them are compatible.

I hope this explains the problem you're seeing. This does not seem to be a bug in Terraform, so I'm going to close this issue.

@jcarlson The plugin cache problem you're seeing seems to be separate, and I can reproduce it. Please report it as another issue so that it can be investigated. Thanks in advance!

**Closed by alisdair** 2020-09-11 20:08 UTC
Labels: bug, new

**Comment by jcarlson** [comment] 2020-09-11 20:19
Opened #26223
