### ISSUE TITLE
ecs task definition diffs change during apply when used together with count and template_file

### ISSUE THREAD

**Issue by mrohland** [hashicorp/terraform#3182] opened 2015-09-07 15:00 UTC
# Bug description
Terraform reports a "diffs didn't match during apply. This is a bug with Terraform and should be reported." when a varaible in a variables.tf.json file gets changed which is used for templating. This happens when a template_file resource is used to update fields in a ECS task definition container definition json file.

# Expected outcome
Only the template which actually contains a change should be reported as to be recreated by planning stage, not the other templates which were rendered earlier and stay the same.

# Test Env
* experienced the same behavior with 0.6.3, 0.6.1 and 0.6.4-dev under os x

# Details

## Scenario Description
Idea is to use terraform to rollout the same service on different ECS clusters in different versions. This would allow to run the same docker image with tag X on cluster A while tag Y runs on cluster B. As most parts of the service and task definition stay the same between all clusters counts and templates are used to have minimal config overhead. 

## TF file
```
...
resource "aws_ecs_task_definition" "xyz-service" {
  family = "xyz-service-${lookup(var.cluster_name, count.index)}"
  count = "${var.cluster.count}"
  container_definitions = "${element(template_file.task_config.*.rendered, count.index)}"
}

resource "aws_ecs_service" "xyz-service" {
  name = "xyz-service"
  count = "${var.cluster.count}"
  cluster = "arn:aws:ecs:eu-west-1:<accountId>:cluster/${lookup(var.cluster_name, count.index)}"
  task_definition = "${element(aws_ecs_task_definition.xyz-service.*.family, count.index)}:${element(aws_ecs_task_definition.xyz-service.*.revision, count.index)}"
  desired_count = "${lookup( var.cluster_desired_count, lookup(var.cluster_name, count.index))}"
}

resource "template_file" "task_config" {
  count = "${var.cluster.count}"
  filename = "container_definition_template.json"
  vars {
    service_version = "${lookup( var.service_version, lookup(var.cluster_name, count.index))}"
    runtime_env = "${lookup( var.runtime_env, lookup(var.cluster_name, count.index))}"
  }
}
...
```
## Variables file
```
{
  "variable": {
    "cluster": {
      "default": {
        "count": 3
      }
    },
    "cluster_desired_count": {
      "default": {
        "clusterA": 1,
        "clusterB": 1,
        "clusterC": 2,
      }
    },
    "cluster_name": {
      "default": {
        "0": "clusterA",
        "1": "clusterB",
        "2": "clusterC",
      }
    },
    "service_version": {
      "default": {
        "clusterA": "version1",
        "clusterB": "version2",
        "clusterC": "version3",
      },
    }
  }
}
```

## template.json

```
[
  {
    "name" : "xyz-service",
    "image" : "private-registry.company/xyz-service:${service_version}",
    "cpu" : 500,
    "memory" : 900,
    "essential" : true
  }
]
```
# Sequence of actions
* 1. create services and task definitions for all three cluster.
* 2. update service version for one cluster and experience the error that all three templates are reported as changed by terraform.

## Generated plan to execute
terraform plan -out service.plan

```
Path: service.plan

~ aws_ecs_task_definition.xyz-service.0
     container_definitions: "3d3f290176d069e947af628c59e54a18695fbe05" => "605af012b7ca39eeda35b4524c4cd29100ed3df8"

 ~ aws_ecs_task_definition.xyz-service.1
     container_definitions: "88602b240af1f16837d14a1e5928b22c490b20f0" => "605af012b7ca39eeda35b4524c4cd29100ed3df8"

 ~ aws_ecs_task_definition.xyz-service.2
     container_definitions: "e6f6a952a44979d3796afc430b1a15e1361803b8" => "605af012b7ca39eeda35b4524c4cd29100ed3df8"


 -/+ template_file.task_config.1
     filename:             "container_definition_template.json" => "container_definition_template.json"
     rendered:             "[\n  {\n    \"name\" : \"xyz-service\",\n    \"image\" : \"private-registry.company/xyz-service:testing\",\n    \"cpu\" : 500,\n    \"memory\" : 900,\n    \"essential\" : true}\n]\n" => "<computed>"
     vars.#:               "1" => "1"
     vars.service_version: "testing" => "newversion" (forces new resource)

```

## Outcome of applied plan

terraform apply service.plan

```
 template_file.task_config.1: Destroying...
 template_file.task_config.1: Destruction complete
 template_file.task_config.1: Creating...
   filename:             "" => "container_definition_template.json"
   rendered:             "" => "<computed>"
   vars.#:               "" => "1"
   vars.service_version: "" => "newversion"
 template_file.task_config.1: Creation complete
 aws_ecs_task_definition.xyz-service.1: Modifying...
   container_definitions: "88602b240af1f16837d14a1e5928b22c490b20f0" => "8ce82178a35184edc96a4e6fab340b45001d894e"
 aws_ecs_task_definition.xyz-service.1: Modifications complete
 Error applying plan:
 
 2 error(s) occurred:
 
 * aws_ecs_task_definition.xyz-service.0: diffs didn't match during apply. This is a bug with Terraform and should be reported.
 * aws_ecs_task_definition.xyz-service.2: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

**Comment by radeksimko** [comment] 2015-09-07 16:16
Reproduced,
The hash is the same for all versions:
```
~ aws_ecs_task_definition.xyz-service.0
     container_definitions: "3d3f290176d069e947af628c59e54a18695fbe05" => "605af012b7ca39eeda35b4524c4cd29100ed3df8"

 ~ aws_ecs_task_definition.xyz-service.1
     container_definitions: "88602b240af1f16837d14a1e5928b22c490b20f0" => "605af012b7ca39eeda35b4524c4cd29100ed3df8"

 ~ aws_ecs_task_definition.xyz-service.2
     container_definitions: "e6f6a952a44979d3796afc430b1a15e1361803b8" => "605af012b7ca39eeda35b4524c4cd29100ed3df8"
```

here's something interesting from a debug log:

```
2015/09/07 17:12:54 [ERROR] aws_ecs_task_definition.xyz-service.1: diffs didn't match
2015/09/07 17:12:54 [ERROR] aws_ecs_task_definition.xyz-service.1: reason: attribute mismatch: container_definitions
2015/09/07 17:12:54 [ERROR] aws_ecs_task_definition.xyz-service.1: diff one: *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"container_definitions":*terraform.ResourceAttrDiff{Old:"73514b515bda0722617d98c07ecf15931d643bce", New:"605af012b7ca39eeda35b4524c4cd29100ed3df8", NewComputed:false, NewRemoved:false, NewExtra:"${element(template_file.task_config.*.rendered, count.index)}", RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
2015/09/07 17:12:54 [ERROR] aws_ecs_task_definition.xyz-service.1: diff two: *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}
```

the second diff seems to be completely empty.
Either way, it's a bug with templates.

**Comment by radeksimko** [comment] 2015-09-08 14:50
I think this could be closed in favour of https://github.com/hashicorp/terraform/issues/2939 @phinze

**Comment by phinze** [comment] 2015-09-08 15:42
Sounds good, @radeksimko. Looks like this might provide a nice repro case for the issue - thanks for putting together all the details so nicely, @mrohland!

**Closed by phinze** 2015-09-08 15:42 UTC
Labels: bug, provider/template

**Comment by ketzacoatl** [comment] 2015-09-09 19:06
@mrohland thank you for your work in compiling the code so for this!

**Comment by mrohland** [comment] 2015-09-10 10:59
Welcome. Hope it helps to fix it, as the only ugly workaround I currently have is to not use a template at all here.

**Comment by ketzacoatl** [comment] 2015-09-18 14:01
My ugly work around is to deploy an environment once, and if I have to change that env, hope that I can deploy a new instance of that environment. That, and don't use templates else for deployments where I cannot do the above..
