### ISSUE TITLE
TERRAFORM CRASH with import 

### ISSUE THREAD

**Issue by jbrunetext** [hashicorp/terraform#25202] opened 2020-06-10 15:50 UTC
terraform import 'module.iam_module_all["gcp_project_dcp_id"].google_project_iam_member.team_dcp_owner' "XXXX-ddp-dcp-dev roles/owner group:XXXXX-ddf-data-component@XXXX.com"

i Faced an issue .... .

Terraform v0.13.0-beta1
+ provider registry.terraform.io/hashicorp/google v3.25.0
+ provider registry.terraform.io/terraform-providers/google-beta v3.25.0

**Comment by danieldreier** [comment] 2020-06-11 00:47
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). 

I'm closing this issue because it doesn't follow the issue template we provide. I would really like to help fix this, and I appreciate you trying the 0.13 beta, but this just doesn't have enough information to reproduce the problem. The "bug" issue template will prompt you for all the details needed.

Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, and then the Terraform maintainers will review it. Thanks!

Beyond using the template, it would help if you could make the following improvements to your issue when you re-file it:

- use GitHub's [text formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax). You can do `markdown` and code formatting to make your code easier to read, which makes it easier for us to understand the issue. Please use markdown to format terraform code like this:
```HCL
resource "null_resource" "example" {
  name = "hello-world"
}
```
- please provide enough terraform config files that I can reproduce your example. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

**Closed by danieldreier** 2020-06-11 00:47 UTC
