### ISSUE TITLE
Invalid Error Message When Using Template File Vars with Null_Resources

### ISSUE THREAD

**Issue by josh-padnick** [hashicorp/terraform#18160] opened 2018-05-31 20:30 UTC
### Terraform Version
```
Terraform v0.11.7
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

**tf-foo/main.tf:**
```hcl
variable "foo" {
  default = "foo"
}

resource "null_resource" "foo" {
  triggers {
    foo = "${var.foo}"
  }

  provisioner "local-exec" {
    command = "echo 'tf-1.foo sleeping for 2 seconds' && sleep 2"
  }
}

variable "foo2" {
  default = "foo"
}

resource "null_resource" "foo2" {
  triggers {
    foo2 = "${var.foo2}"
  }

  provisioner "local-exec" {
    command = "echo 'tf-1.foo2 sleeping for 10 seconds' && sleep 10"
  }
}

output "foo2" {
  value = "${null_resource.foo2.triggers.foo2}"
}

data "template_file" "foo" {
  template = "throwaway-value"

  vars {
    foo = "${null_resource.foo.triggers.foo}"
    foo2 = "${null_resource.foo2.triggers.foo2}"
  }
}

output "foo" {
  value = "${data.template_file.foo.rendered}"
}
```

**tf-bar/main.tf:**
```hcl
variable "bar" {
  default = "foo"
}

resource "null_resource" "bar" {
  triggers {
    bar = "${var.bar}"
  }

  provisioner "local-exec" {
    command = "echo 'tf-2.bar sleeping for 5 seconds' && sleep 5"
  }
}

output "bar" {
  value = "${null_resource.bar.triggers.bar}"
}
```

**tf-modules/main.tf:**
```hcl
module "foo" {
  source = "../tf-foo"
}

module "bar" {
  source = "../tf-bar"

  bar = "${module.foo.foo}"
}
```

### Debug Output
https://gist.github.com/josh-padnick/ef1677c29600abfa1c87ef3060b737d7

### Expected Behavior
Terraform should have just applied my configuration.

### Actual Behavior
```
Error: Error running plan: 1 error(s) occurred:

* module.bar.output.bar: Resource 'null_resource.bar' does not have attribute 'triggers.bar' for variable 'null_resource.bar.triggers.bar'
```

But this error goes away when the `vars` block of `data.template_file.foo` is removed from `tf-foo/main.tf`. Clearly, this error isn't the correct error message.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
Given that [depends_on cannot be used with modules](https://github.com/hashicorp/terraform/issues/10462), I was attempting to hack the module dependencies by making deliberate use of module variables and outputs.

**Comment by apparentlymart** [comment] 2018-10-31 18:19
Hi @josh-padnick! Sorry for this weird behavior, and for the slow response.

I believe the root cause for this problem was a behavior in Terraform v0.11 and prior where if a map contains any unknown value then it was simplified to be an entirely-unknown map. This would then sometimes result in confusing error messages like this where Terraform would fail to take that into account during validation and complain that a particular map key isn't present when it should've just been deferring that whole validation until the map is known.

Both of these problems are now fixed in master as part of the configuration language revamp we've been working on for the forthcoming v0.12.0 release. I verified this by applying your configuration with the v0.12.0-alpha2 prerelease build:

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.bar.null_resource.bar will be created
  + resource "null_resource" "bar" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

  # module.foo.data.template_file.foo will be read during apply
  # (config refers to values not yet known)
 <= data "template_file" "foo"  {
      + id       = (known after apply)
      + rendered = (known after apply)
      + template = "throwaway-value"
      + vars     = {
          + "foo"  = "foo"
          + "foo2" = "foo"
        }
    }

  # module.foo.null_resource.foo will be created
  + resource "null_resource" "foo" {
      + id       = (known after apply)
      + triggers = {
          + "foo" = "foo"
        }
    }

  # module.foo.null_resource.foo2 will be created
  + resource "null_resource" "foo2" {
      + id       = (known after apply)
      + triggers = {
          + "foo2" = "foo"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.foo.null_resource.foo2: Creating...
module.foo.null_resource.foo: Creating...
module.foo.null_resource.foo: Provisioning with 'local-exec'...
module.foo.null_resource.foo2: Provisioning with 'local-exec'...
module.foo.null_resource.foo (local-exec): Executing: ["/bin/sh" "-c" "echo 'tf-1.foo sleeping for 2 seconds' && sleep 2"]
module.foo.null_resource.foo2 (local-exec): Executing: ["/bin/sh" "-c" "echo 'tf-1.foo2 sleeping for 10 seconds' && sleep 10"]
module.foo.null_resource.foo (local-exec): tf-1.foo sleeping for 2 seconds
module.foo.null_resource.foo2 (local-exec): tf-1.foo2 sleeping for 10 seconds
module.foo.null_resource.foo: Creation complete after 2s [id=9152774538089359165]
module.foo.null_resource.foo2: Still creating... [10s elapsed]
module.foo.null_resource.foo2: Creation complete after 10s [id=8670486451413475399]
module.foo.data.template_file.foo: Refreshing state...
module.bar.null_resource.bar: Creating...
module.bar.null_resource.bar: Provisioning with 'local-exec'...
module.bar.null_resource.bar (local-exec): Executing: ["/bin/sh" "-c" "echo 'tf-2.bar sleeping for 5 seconds' && sleep 5"]
module.bar.null_resource.bar (local-exec): tf-2.bar sleeping for 5 seconds
module.bar.null_resource.bar: Creation complete after 5s [id=3100669945697610864]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

Although we can see the symptom of #19234 in that plan output, it _is_ now able to run to completion because the values are able to thread through properly in the plan phase.

This fix is in master ready to be include in the forthcoming v0.12.0 release, so I'm going to close this out. Thanks for reporting this, and sorry again for being slow to respond.

**Closed by apparentlymart** 2018-10-31 18:19 UTC
Labels: bug, config
