### ISSUE TITLE
[Bug] Data sources in modules being evaluated in wrong order 

### ISSUE THREAD

**Issue by rrmistry** [hashicorp/terraform#28610] opened 2021-05-04 21:55 UTC
### Terraform Version

```bash
Terraform v0.15.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0
```

### Terraform Configuration Files

Main Module:
```terraform
# ./vm.tf

provider "azurerm" {
  ...
}

resource "azurerm_resource_group" "app" {
  name     = "MY-APP"
  location = var.az_region
}

module "control_server" {
  source = "../terraform-azurerm-test"

  # Expected this to cause module evaluation to occur after resource group creation
  az_resource_group  = azurerm_resource_group.app.name 

  # Other variables ...
}
```

Dependency Module:
```terraform
# ../terraform-azurerm-test/test.tf
variable "az_resource_group" {
  type = string
}

# Other variables ...

data "azurerm_resource_group" "default" {
  name = var.az_resource_group
}

# Other resources ...
```

### Debug Output
<details>
  <summary>Terraform Debug Output Extract</summary>
  <a href="https://gist.github.com/rrmistry/739fdf4e16eca09a1964e2881fdd2c06">Gist</a>
</details>

### Expected Behavior
```bash
❯ terraform plan

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

...

Plan: XYZ to add, 0 to change, 0 to destroy.

--------------------------------------------------------------------------

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

### Actual Behavior
```bash
❯ terraform plan
╷
│ Error: Error: Resource Group "MY-APP" was not found
│
│   with module.control_server.data.azurerm_resource_group.default,
│   on ..\terraform-azurerm-singlevm-ggy\test.tf line 12, in data "azurerm_resource_group" "default":
│   12: data "azurerm_resource_group" "default" {
│
╵
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue:
1. `terraform init`
2. `terraform plan`

**Comment by rrmistry** [comment] 2021-05-04 22:03
Posting a workaround in case someone else is also stuck

## Workaround
```terraform
# ./vm.tf

provider "azurerm" {
  tenant_id       = "5d3e2773-e07f-4432-a630-1a0f68a28a05"
  subscription_id = "09fa5429-f200-4e40-882b-2cde3f32c8cf"
  features {}
}

resource "azurerm_resource_group" "app" {
  name     = "MY-APP"
  location = "canadacentral"
}

module "control_server" {
  source             = "../terraform-azurerm-test"

  # Expected this to cause module evaluation to occur after resource group creation
  az_resource_group  = azurerm_resource_group.app.name 

  # Other variables ...

  # ###################################
  # ⚠FIX: Add this to force module evaluation in the proper order
  depends_on = [
    azurerm_resource_group.app
  ]
  # ###################################
}
```

Since there is a workaround, there is low confidence that this will be implemented as expected. But would be very nice to have since it is not trivial how or why this happens without some effort.

**Comment by jbardin** [comment] 2021-05-05 12:29
Hi @rrmistry,

What you are seeing here is the expected behavior of the data source. The `az_resource_group ` value you are passing into the module is known statically, so there is no indication that the data source cannot be read immediately during the first planning phase. 

While using `depends_on` does appear to work here, the suggested solution would be to not have both a managed resource and a data source within the configuration representing the same logical resource, and have the module accept whatever values it needs directly from the managed resource. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by jbardin** 2021-05-05 12:29 UTC
Labels: bug, new
