### ISSUE TITLE
Issue with user_data in terraform 14

### ISSUE THREAD

**Issue by MaxIsaev78** [hashicorp/terraform#27168] opened 2020-12-07 15:30 UTC
### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.33.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    openstack = {
      source = "terraform-provider-openstack/openstack"
    }
    template = {
      source = "hashicorp/template"
    }
  }
  required_version = ">= 0.13"
}

provider "openstack" {
  cloud = "openstack"
}


data "template_file" "user_data" {
  template = file("${path.module}/templates/user_data.sh")

  vars = {
    service_name = "test"
  }
}

data "openstack_images_image_v2" "image" {
  name        = "CentOS-7"
}

resource "openstack_compute_servergroup_v2" "server_group" {
  name = "<group_name>"
  policies = ["anti-affinity"]
}


resource "openstack_compute_instance_v2" "vm" {
  name            = "<node_name>"
  flavor_name     = "<flafor>"
  key_pair        = "<key>"
  security_groups = ["default"]
  user_data       = data.template_file.user_data.rendered
  scheduler_hints {
    group = openstack_compute_servergroup_v2.server_group.id
  }

  block_device {
    uuid                  = data.openstack_images_image_v2.image.id
    source_type           = "image"
    volume_size           = 40
    boot_index            = 0
    destination_type      = "volume"
    delete_on_termination = true
  }

  block_device {
    boot_index            = -1
    delete_on_termination = true
    destination_type      = "volume"
    source_type           = "blank"
    volume_size           = 20
  }

  network {
    name = "<network_name>"
  }

}
```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Having created a compute_instance, when changing user_data, terraform tries to recreate the instance:

```
...
      - tags                = [] -> null
      ~ user_data           = "1572796eda29efeb862916b2d84f44cf457fb271" -> "0f2d29b246017672b3ec5e6c27d753d44e7362f9" # forces replacement
...
```
which is expected, in order to work around that, lifecycle ignore_changes is used 

```
...
resource "openstack_compute_instance_v2" "vm" {
  name            = "<node_name>"
  flavor_name     = "<flafor>"
  key_pair        = "<key>"
  security_groups = ["default"]
  user_data       = data.template_file.user_data.rendered
  scheduler_hints {
    group = openstack_compute_servergroup_v2.server_group.id
  }

  block_device {
    uuid                  = data.openstack_images_image_v2.image.id
    source_type           = "image"
    volume_size           = 40
    boot_index            = 0
    destination_type      = "volume"
    delete_on_termination = true
  }

  block_device {
    boot_index            = -1
    delete_on_termination = true
    destination_type      = "volume"
    source_type           = "blank"
    volume_size           = 20
  }

  network {
    name = "<network_name>"
  }
  
  lifecycle {
    ignore_changes = [  user_data ]
  }

}
...
```

after that, running terraform plan shows that - No changes. Infrastructure is up-to-date.

That is what I was getting using terraform 13.5

### Actual Behavior
terraform 14 seems to ignore lifecycle ignore_changes block with user_data (other fields, for example - name are treated correctly by terraform if put in lifecycle ingore_changes), running plan shows that instance is to be recreated 

```
...
      - tags                = [] -> null
      ~ user_data           = "1572796eda29efeb862916b2d84f44cf457fb271" -> "0f2d29b246017672b3ec5e6c27d753d44e7362f9" # forces replacement
...
```

furthermore, returning user_data contents back to the original value shows the following: 

```
openstack_compute_servergroup_v2.server_group: Refreshing state... [id=4d43ef56-a9a6-4662-ba8c-5fb1e3bf7bb1]
openstack_compute_instance_v2.vm: Refreshing state... [id=300f0292-cd9f-40cc-b106-1d7354d55e31]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # openstack_compute_instance_v2.vm must be replaced
-/+ resource "openstack_compute_instance_v2" "vm" {
      ~ access_ip_v4        = "<ip>" -> (known after apply)
      + access_ip_v6        = (known after apply)
      ~ all_metadata        = {} -> (known after apply)
      ~ all_tags            = [] -> (known after apply)
      ~ availability_zone   = "<az>" -> (known after apply)
      ~ flavor_id           = "84609977-5b87-44d4-ba0c-9606b8cde88b" -> (known after apply)
      ~ id                  = "300f0292-cd9f-40cc-b106-1d7354d55e31" -> (known after apply)
      ~ image_id            = "Attempt to boot from volume - no image supplied" -> (known after apply)
      + image_name          = (known after apply)
        name                = "<node_name>"
      ~ region              = "RegionOne" -> (known after apply)
      - tags                = [] -> null
        # (7 unchanged attributes hidden)

      ~ block_device {
            # (6 unchanged attributes hidden)
        }
      ~ block_device {
            # (5 unchanged attributes hidden)
        }

      ~ network {
          ~ fixed_ip_v4    = "<ip>" -> (known after apply)
          + fixed_ip_v6    = (known after apply)
          + floating_ip    = (known after apply)
          ~ mac            = "<mac>" -> (known after apply)
            name           = "<network>"
          + port           = (known after apply)
          ~ uuid           = "f13c6c66-5372-43f4-a55d-ef66fcc801cd" -> (known after apply)
            # (1 unchanged attribute hidden)
        }

      - scheduler_hints {
          - additional_properties = {} -> null
          - different_cell        = [] -> null
          - different_host        = [] -> null
          - group                 = "4d43ef56-a9a6-4662-ba8c-5fb1e3bf7bb1" -> null
          - query                 = [] -> null
          - same_host             = [] -> null
        }
      + scheduler_hints {
          + different_cell = []
          + different_host = []
          + group          = "4d43ef56-a9a6-4662-ba8c-5fb1e3bf7bb1"
          + query          = []
          + same_host      = []
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Nothing seems to cause the replacement. However, in terraform 14 release notes:

```
terraform plan and terraform apply: Added an experimental concise diff renderer. By default, Terraform plans now hide most unchanged fields, only displaying the most relevant changes and some identifying context. 
This experiment can be disabled by setting a TF_X_CONCISE_DIFF environment variable to 0
```

I set TF_X_CONCISE_DIFF=0 and ran terraform plan again

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # openstack_compute_instance_v2.vm must be replaced
-/+ resource "openstack_compute_instance_v2" "vm" {
      ~ access_ip_v4        = "<ip" -> (known after apply)
      + access_ip_v6        = (known after apply)
      ~ all_metadata        = {} -> (known after apply)
      ~ all_tags            = [] -> (known after apply)
      ~ availability_zone   = "<az>" -> (known after apply)
      ~ flavor_id           = "84609977-5b87-44d4-ba0c-9606b8cde88b" -> (known after apply)
        flavor_name         = "<flavor>"
        force_delete        = false
      ~ id                  = "300f0292-cd9f-40cc-b106-1d7354d55e31" -> (known after apply)
      ~ image_id            = "Attempt to boot from volume - no image supplied" -> (known after apply)
      + image_name          = (known after apply)
        key_pair            = "<key>"
        name                = "<node_name>"
        power_state         = "active"
      ~ region              = "RegionOne" -> (known after apply)
        security_groups     = [
            "default",
        ]
        stop_before_destroy = false
      - tags                = [] -> null
        user_data           = "1572796eda29efeb862916b2d84f44cf457fb271" # forces replacement

      ~ block_device {
            boot_index            = 0
            delete_on_termination = true
            destination_type      = "volume"
            source_type           = "image"
            uuid                  = "f7a3c49f-2fc8-4ae4-863a-59badf1fd2f7"
            volume_size           = 40
        }
      ~ block_device {
            boot_index            = -1
            delete_on_termination = true
            destination_type      = "volume"
            source_type           = "blank"
            volume_size           = 20
        }

      ~ network {
            access_network = false
          ~ fixed_ip_v4    = "<ip>" -> (known after apply)
          + fixed_ip_v6    = (known after apply)
          + floating_ip    = (known after apply)
          ~ mac            = "<mac>" -> (known after apply)
            name           = "<name>"
          + port           = (known after apply)
          ~ uuid           = "f13c6c66-5372-43f4-a55d-ef66fcc801cd" -> (known after apply)
        }

      - scheduler_hints {
          - additional_properties = {} -> null
          - different_cell        = [] -> null
          - different_host        = [] -> null
          - group                 = "4d43ef56-a9a6-4662-ba8c-5fb1e3bf7bb1" -> null
          - query                 = [] -> null
          - same_host             = [] -> null
        }
      + scheduler_hints {
          + different_cell = []
          + different_host = []
          + group          = "4d43ef56-a9a6-4662-ba8c-5fb1e3bf7bb1"
          + query          = []
          + same_host      = []
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

For some reason, unchanged user_data causes instance replacement, even though there is a lifecycle block with ignore_changes. The strangest thing is that only if I remove the lifecycle block and run terraform I get 

```
No changes. Infrastructure is up-to-date.
```

### Steps to Reproduce
1. Create openstack_compute_instance_v2 resource with a user_data script
2. Add 
```
lifecycle {
    ignore_changes = [  user_data ]
  }
```
3. terraform plan

**Comment by jbardin** [comment] 2020-12-07 16:23
Duplicate of #27097

**Closed by jbardin** 2020-12-07 16:23 UTC
Labels: bug, new
