### ISSUE TITLE
S3 bucket replication configuration is not idempotent

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#14320] opened 2017-05-09 16:35 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.9.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket

### Terraform Configuration Files

```
resource "aws_s3_bucket" "src" {
  provider = "aws.src"
  bucket = "${var.src_bucket_name}"
  versioning {
    enabled = true
  }
  replication_configuration {
    role = "${aws_iam_role.src.arn}",
    rules = {
      prefix = ""
      status = "Enabled"
      destination {
        bucket = "${aws_s3_bucket.dest.arn}"
      }
    }
  }
}
```

### Debug Output
```
~ aws_s3_bucket.src
    replication_configuration.0.rules.3415946663.destination.#:                       "0" => "1"
    replication_configuration.0.rules.3415946663.destination.312286334.bucket:        "" => "arn:aws:s3:::adsk-test-archive"
    replication_configuration.0.rules.3415946663.destination.312286334.storage_class: "" => ""
    replication_configuration.0.rules.3415946663.id:                                  "" => ""
    replication_configuration.0.rules.3415946663.prefix:                              "" => ""
    replication_configuration.0.rules.3415946663.status:                              "" => "Enabled"
    replication_configuration.0.rules.3557997358.destination.#:                       "1" => "0"
    replication_configuration.0.rules.3557997358.destination.312286334.bucket:        "arn:aws:s3:::adsk-test-archive" => ""
    replication_configuration.0.rules.3557997358.destination.312286334.storage_class: "" => ""
    replication_configuration.0.rules.3557997358.id:                                  "zzzzzzz" => ""
    replication_configuration.0.rules.3557997358.prefix:                              "" => ""
    replication_configuration.0.rules.3557997358.status:                              "Enabled" => ""
```

### Expected Behavior
No output no change..

### Actual Behavior
A configuration is removed and an identical configuration is added.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Nothing comes to mind

**Comment by stack72** [comment] 2017-05-09 16:43
Hi @silvermy 

Thanks for opening the issue here - my apologies this is causing a problem for you. Unfortunately, I am going to close this as a duplicate of https://github.com/hashicorp/terraform/issues/13352

Please use that linked issue for any config updates / issue updates etc

Thanks

Paul

**Closed** 2017-05-09 16:43 UTC
Labels: bug, provider/aws
