### ISSUE TITLE
Couldn't set up logging tempfile: open C:\Windows\terraform-log323951539: Accesso negato.

### ISSUE THREAD

**Issue by lamba92** [hashicorp/terraform#29353] opened 2021-08-11 20:49 UTC
```
Terraform v1.0.3 on windows_amd64
```

Invoking Terraform with current parameters:
```
working dir: D:\projects\pkgs\aws\src\accountSetup\terraform
command line: D:\projects\pkgs\aws\build\terraform\terraform_1.0.3.exe, init, -input=false
environment: TF_DATA_DIR=D:\projects\pkgs\aws\build\terraform\accountSetup\data, AWS_SHARED_CREDENTIALS_FILE=C:\Users\lamba\.aws\credentials
```
errors with:
```
Couldn't set up logging tempfile: open C:\Windows\terraform-log323951539: Accesso negato.
```

It only happens on Windows, Ubuntu WSL and macOs works just fine (only x64 versions tested).

Note that setting `AWS_SHARED_CREDENTIALS_FILE` is needed due to #29352.

Terraform invokation is automated by a [Gradle plugin](https://github.com/JetBrains/jetbrains-gradle-plugins/blob/master/docs/TERRAFORM.md).

**Comment by jbardin** [comment] 2021-08-11 21:00
Hi @lamba92,

It sounds like the windows user does not have a temp or userprofile directory set and is getting `C:\Windows` as a last resort, but does not have write permissions there. 

Can you show the environment variables for the windows user?

**Comment by lamba92** [comment] 2021-08-11 21:02
That's all the user environment. The PC is freshly formatted.
![image](https://user-images.githubusercontent.com/10994011/129102869-70e7e736-1653-4595-8b9f-ffe5109f18e1.png)

**Comment by lamba92** [comment] 2021-08-11 21:05
It might be the same issue with #29352. I'll try to specify it explicitly from environment as for [`TF_DATA_DIR` here](https://github.com/JetBrains/jetbrains-gradle-plugins/blob/88ddcc604be19c7b33016dbcc7f664c7f80e3275/plugins/src/main/kotlin/org/jetbrains/gradle/plugins/terraform/tasks/AbstractTerraformExec.kt#L20-L24)

**Comment by jbardin** [comment] 2021-08-11 21:09
I don't think they're going to be related, but it's worth a try to see what happens. The problem here is that the OS is picking `Windows` as the temp directory for your process, which Terraform does not control. Are you certain that is the same set of environment variables within the gradle process?

**Comment by lamba92** [comment] 2021-08-11 23:21
The workaround works, check the commit above. I also printed `System.getenv()` just to be sure and it does contains `TMP` and `TEMP`. Maybe somehow from inside the Gradle `Exec` task terraform is not able to pick it up. But I still find it very suspicious due to #29352.

**Comment by lamba92** [comment] 2021-08-11 23:30
I set up a repro here: https://github.com/lamba92/terraform-29352-issue

Version `1.0.5` of the plugin with commit [31d19b9](https://github.com/JetBrains/jetbrains-gradle-plugins/commit/31d19b950c6738339cf744bd7fed4d338daea663) fixes the problem.

**Comment by jbardin** [comment] 2021-08-13 14:29
From what I can gather from that example, it appears that this is an issue with the gradle configuration and the environment where terraform is running. I would also bet that 29352 is the same problem, as I cannot reproduce the issue when running the CLI directly. Having no temporary directory is the root problem here, and It seems a missing or altered userprofile directory would account for the other issue.

I don't think there's anything to do within terraform, the location of the temporary directory or the userprofile is returned by the OS, and not configured in terraform.

**Comment by jbardin** [comment] 2021-09-01 21:18
Since this appears to be a problem with the execution environment outside of Terraform's control, I'm going to close the issue. The system paths are not something that Terraform alters, and the paths used by Terraform are only what is returned by the OS. 

Thanks!

**Closed by jbardin** 2021-09-01 21:18 UTC
Labels: bug, waiting-response, new, waiting for reproduction
