### ISSUE TITLE
Line Numbers reporting incorrectly

### ISSUE THREAD

**Issue by QuinnyPig** [hashicorp/terraform#2286] opened 2015-06-09 17:53 UTC
I've built a [demo branch](https://github.com/quinnypig/terraform-example/tree/bug-demo) wherein I've intentionally broken line 94 by removing a comma.

However, when executing "terraform plan," or for that matter any other terraform command, it reports the error to be in line 105, which is incorrect.

    Error loading config: Error parsing /Users/cquinn/src/terraform-example/main.tf: Line 105, column 46: syntax error

Note that it's complaining about line 105 of a 102 line file. 

To replicate this in your environment, 
```
git clone https://github.com/quinnypig/terraform-example
cd terraform-example
git checkout bug-demo
terraform plan
```

**Comment by QuinnyPig** [comment] 2015-06-09 17:59
A quick check of the rest of the files in this repo reveal no combination of line numbers that would sum to an "off by 11" error, so it's not combining the files into a unified master config file and reporting line numbers out of that...

**Comment by phinze** [comment] 2015-06-16 21:28
Thanks for the report. This is a duplicate of #2048, so I'll close this so we can consolidate the conversation over there.

**Closed by phinze** 2015-06-16 21:28 UTC
