### ISSUE TITLE
"panic: not a collection type" terraform crash on plan

### ISSUE THREAD

**Issue by Weltmacht** [hashicorp/terraform#26081] opened 2020-09-01 17:06 UTC
# terraform plan

[crash.log](https://github.com/hashicorp/terraform/files/5157783/crash.log)
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.nsg.data.azurerm_resource_group.rg: Refreshing state...
module.vm.data.azurerm_subnet.subnet: Refreshing state...
module.vm.data.azurerm_resource_group.rg: Refreshing state...

------------------------------------------------------------------------
panic: not a collection type

goroutine 423 [running]:
github.com/zclconf/go-cty/cty.Type.ElementType(0x2ce50a0, 0xc0009378b0, 0xc00079c5f8, 0x8)
        /home/circleci/project/project/vendor/github.com/zclconf/go-cty/cty/collection.go:25 +0xba
github.com/hashicorp/terraform/terraform.createEmptyBlocks(0xc000ac8c00, 0x2ce50a0, 0xc0009378c0, 0x2300040, 0xc0010654a0, 0x2ce50a0, 0xc000937998, 0x2300040, 0xc000e63590)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:242 +0x202
github.com/hashicorp/terraform/terraform.dataObjectHasChanges(0xc000ac8c00, 0x2ce50a0, 0xc0009378c0, 0x2300040, 0xc0010654a0, 0x2ce50a0, 0xc000937998, 0x2300040, 0xc000e63590, 0x0, ...)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:211 +0x19e
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc00057a0f0, 0x2d26860, 0xc000e44340, 0x1, 0x1, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:107 +0x1238
github.com/hashicorp/terraform/terraform.EvalRaw(0x2c7d420, 0xc00057a0f0, 0x2d26860, 0xc000e44340, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000e82f00, 0x2d26860, 0xc000e44340, 0x1, 0x1, 0x6, 0xc00056c710)
        /home/circleci/project/project/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2c7ce80, 0xc000e82f00, 0x2d26860, 0xc000e44340, 0x22b4bc0, 0x3fa2622, 0x2214980, 0xc0010bf250)
        /home/circleci/project/project/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.Eval(0x2c7ce80, 0xc000e82f00, 0x2d26860, 0xc000e44340, 0xc000e82f00, 0x2c7ce80, 0xc000e82f00, 0x0)
        /home/circleci/project/project/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2645300, 0xc0010beab0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:73 +0xc77
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00056c540, 0x2645300, 0xc0010beab0, 0xc000830a00)
        /home/circleci/project/project/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x11d7

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

# terraform version
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0

Receiving same results with v2.25.0(latest) of azurerm as well.

**Comment by jbardin** [comment] 2020-09-01 17:23
Duplicate of #26011

**Closed by jbardin** 2020-09-01 17:23 UTC
