### ISSUE TITLE
AWS: Certificate not found even though it was just created

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#2499] opened 2015-06-25 21:49 UTC
Related: https://github.com/hashicorp/terraform/issues/2490

I deleted the certificate using AWS's cli. The output shows it was created but then when it goes to create the ELB, AWS says that the certificate doesn't exist.

[Here are the logs.](https://gist.github.com/nathanielks/d5cb72646dda9a903a6d)

**Comment by phinze** [comment] 2015-06-26 15:05
Thanks for the report - we've seen this issue in several different places. We'll have to see if there's something we can do after the certificate create to ensure it's ready to be attached to an ELB.

**Comment by nathanielks** [comment] 2015-06-26 15:12
:+1:

**Comment by mitchellh** [comment] 2015-06-29 06:24
I'm playing with this now. The AWS logs say that it can take up to 15 minutes for certificates to propagate, which would indeed be a really sad thing. I'm trying to find a way for us to detect this since the API doesn't seem to expose it.

**Comment by rgabo** [comment] 2015-07-01 14:48
Just ran into the same issue. `awscli` is quite misleading because `aws iam list-server-certificates` immediately lists the certificate that was just created, even though when referenced in other services (ELB in our case), it will throw an error.

**Comment by xuwang** [comment] 2015-07-27 18:13
I have the same issue, one workaroud is to wait for a while in local provisioner :
```
resource "aws_iam_server_certificate" "mycert" {
  name = "mycert"
  certificate_body = "${file("mycert.pem")}"
  private_key = "${file("mycert-key.pem")}"

  provisioner "local-exec" {
    command = <<EOF
        echo # Sleep 10 secends so that mycert is propagated by aws iam service
        echo # See https://github.com/hashicorp/terraform/issues/2499 (terraform ~v0.6.1)
        sleep 10
EOF
  }
}
```
10 seconds wait time seems to work for me. May a terraform function can be introduced to handle the need for external waiting? e.g. depend_on with a waiting time.

**Comment by farridav** [comment] 2015-10-22 12:04
This is affecting me too, and I also got he same output from `aws iam list-server-certificates` ..Just posted on these 2 related issues https://github.com/hashicorp/terraform/issues/3275 and https://github.com/hashicorp/terraform/issues/3412 .. I will try the temporary sleep fix.. but keen to hear if there is a proper solution I can use :+1:

**Comment by catsby** [comment] 2015-11-12 22:24
I've submitted https://github.com/hashicorp/terraform/pull/3898 as a patch for #3275 and #3412. Unfortunately it is largely a bandaid. IAM resources are notoriously eventually consistent for our experiences; API calls return "success" but follow up calls that reference the ARN return 404s :/

**Comment by catsby** [comment] 2015-11-20 20:51
#3898 was merged, so I'm going to close this. 
Let me know if you're still seeing this on the master branch, otherwise the fix will rollout in the next release (should be next week)

**Closed by catsby** 2015-11-20 20:51 UTC
Labels: bug, provider/aws

**Comment by nathanielks** [comment] 2015-11-20 21:37
:+1:

**Comment by nathanielks** [comment] 2015-12-07 18:30
@catsby Finally had the opportunity to test #3898. Having upgraded to 0.6.8, I'm unfortunately still seeing the error. Adding a 10 second sleep to the certificate "resolves" the issue though ¯\_(ツ)_/¯

**Comment by catsby** [comment] 2015-12-07 18:52
> Adding a 10 second sleep to the certificate "resolves" the issue though

Can you elaborate on how you're doing this? The retry logic in #3898 should retry the creation for up to 1 minute, so, I'm not sure _where_ a `sleep` for 10 seconds is helping, that a retry for 1 minute wouldn't also fix. Do you see the warning "[WARN] Error creating ELB Listener with SSL Cert, retrying" in the logs? 

Or is this for deletion? This issue has crossed some wires :smile:

**Comment by nathanielks** [comment] 2015-12-11 15:37
Sure can, @catsby! Here's the whole resources for funzies:
```
resource "aws_iam_server_certificate" "domains" {                                                                                                               
    count = "${var.load_balancer_count}"                                                                                                                        
                                                                                                                                                                
    name = "${var.environment}-${element(split(" ",var.certificate_names), count.index)}"                                                                       
                                                                                                                                                                
    certificate_body = "${file(format("%s/%s/%s.%s", var.certificates_base, var.environment, element(split(" ",var.certificate_names), count.index), "crt"))}"  
    certificate_chain = "${file(format("%s/%s/%s.%s", var.certificates_base, var.environment, element(split(" ",var.certificate_names), count.index), "chain"))}
    private_key = "${file(format("%s/%s/%s.%s", var.certificates_base, var.environment, element(split(" ",var.certificate_names), count.index), "key"))}"       
                                                                                                                                                                
    provisioner "local-exec" {                                                                                                                                  
        command = "sleep 10"                                                                                                                                    
    }                                                                                                                                                           
}                                                                                                                                                               
```

It's on creation. I'm not sure I'll have time to re-run everything, but I'll do that as soon as I can and get back with you on the ELB Listener warning!

**Comment by catsby** [comment] 2015-12-11 22:52
@nathanielks I attempted to reproduce with this:

- https://gist.github.com/catsby/cd0d296c572e65a4a7f0

but I can't. Let me know what I'm missing

**Comment by jurajseffer** [comment] 2017-11-02 14:57
I think I'm hitting this in terraform v0.10.8 when trying to assign a newly saved IAM server certificate to an ALB listener. Terraform gives me an ARN for `aws_iam_server_certificate` but it fails to apply the change to listeners with an AWS error saying the certificate with given ARN cannot be found. When I manually look at the certificates available via AWS console, I can see it being there and subsequent plan and apply works fine so it looks like a problem with eventual consistency.

**Comment by vmendoza** [comment] 2018-01-06 02:55
Yeah, I'm hitting this in terraform v0.10.8 as well. It works on macOS and Ubuntu 16, but fails on Centos/Jenkins running on EC2.

**Comment by mattchilds1** [comment] 2018-04-19 12:50
It seems I'm experiencing the same thing as @jurajseffer . The only different thing I'm doing is pulling the cert in from another AWS account with a separate provider. 

Terraform returns the correct ARN, pass's it into the ELB Listener but then fails with the certificate not found error. 

@catsby

**Comment by saplla** [comment] 2018-05-23 14:51
This also occurs in v0.11.7. Here's my code for creating a cert:
```
provider "aws" {
  alias  = "certificate"
  region = "${module.acc_globals.certificate_region}"
}

resource "aws_acm_certificate" "cert" {
  domain_name       = "*.example.io"
  validation_method = "DNS"

  tags = {
    Owner = "central"
  }

  provider = "aws.certificate"
}

data "aws_route53_zone" "zone" {
  name = "example.io."
  private_zone = false
}

resource "aws_route53_record" "cert_validation" {
  name = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_name}"
  type = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_type}"
  zone_id = "${data.aws_route53_zone.zone.id}"
  records = ["${aws_acm_certificate.cert.domain_validation_options.0.resource_record_value}"]
  ttl = 60
}

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn = "${aws_acm_certificate.cert.arn}"
  validation_record_fqdns = ["${aws_route53_record.cert_validation.fqdn}"]
}

resource "aws_alb_listener" "internet-cluster-alb-listener-https" {
  load_balancer_arn = "${aws_lb.internet-cluster-alb.id}"
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS-1-2-2017-01"
  certificate_arn   = "${aws_acm_certificate_validation.cert.certificate_arn}"

  default_action {
    target_group_arn = "${aws_alb_target_group.internet-cluster-alb-tg.arn}"
    type             = "forward"
  }
}
```
I get an error:
```
* aws_acm_certificate_validation.cert: Error describing certificate: ResourceNotFoundException: Could not find certificate <arn>
```

The certificate with the given arn exists in AWS and is verified. Running `terraform plan` or `terraform apply` repeatedly doesn't fix the issue.
