### ISSUE TITLE
aws_glue_classifier - seems to require QuoteSymbol for CSV

### ISSUE THREAD

**Issue by goochi1** [hashicorp/terraform#24782] opened 2020-04-27 18:51 UTC
Hi the deployment of the classifier is failing and seems to require a pram that is optional in wiki
### Terraform Version

```
...
```

### Terraform Configuration Files

```

resource "aws_glue_classifier" "classifier" {
  name = "classifier"
  csv_classifier {
    contains_header        = "PRESENT"
    delimiter              = ","
  }
}
...
```

### Debug Output

1 error occurred:

	* aws_glue_classifier.classifier: 1 error occurred:

	* aws_glue_classifier.classifier: error creating Glue Classifier (classifier): InvalidParameter: 1 validation error(s) found.

- minimum field size of 1, CreateClassifierInput.CsvClassifier.QuoteSymbol.

**Comment by danieldreier** [comment] 2020-04-28 00:28
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

You should probably also add in the version of terraform and the AWS provider you're using, after the issue is migrated. Without that information they will be unlikely to help you.

**Closed** 2020-04-28 01:20 UTC
Labels: provider/aws
