### ISSUE TITLE
terraform providers mirror command attempts and fails for local modules

### ISSUE THREAD

**Issue by ashwgupt** [hashicorp/terraform#29962] opened 2021-11-17 11:02 UTC
### Terraform Version
```
Terraform v1.0.0
```

### Terraform Configuration Files
**version.tf**
```terraform
terraform {
  backend "s3" {
    key = "advice/terraform.tfstate"
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.63.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "2.1.2"
    }
    random = {
      source  = "hashicorp/random"
      version = "2.1.2"
    }
    template = {
      source  = "hashicorp/template"
      version = "2.1.2"
    }
  }
  required_version = ">= 0.13"
}
```

**.terraformrc**
```terraform
plugin_cache_dir = "/home/.terraform.d/plugin-cache"

provider_installation {
 filesystem_mirror {
    path = "/home/.terraform.d/plugins-mirror-new"
    include = ["registry.terraform.io/hashicorp/aws"]
  }
  direct {
    exclude = ["registry.terraform.io/hashicorp/aws"]
  }
}
```

### Debug Output
N/A

### Expected Behavior
The ```terraform providers mirror``` command should not have bothered about the modules installation and focus only on the ```required_providers``` sections of the terraform ```versions.tf``` file.

### Actual Behavior
For a  fresh TF directory, the command fails when run prior to ```terraform init``` command due to not-installed modules. Below errors are present.

```
│ Error: Module not installed
│
│   on api-gateway.tf line 1:
│    1: module "advice_api_gateway" {
│
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
```

### Steps to Reproduce
1. Go to a terraform directory
2. rm -rf .terraform .terraform.lock.hcl
3. rm -rf /home/.terraform.d/plugins-mirror-new/*
3. terraform providers mirror /home/.terraform.d/plugins-mirror-new
4. Boom!

### Additional Context
For our case, all the modules are local to the code and used so.

### References
None

**Comment by jbardin** [comment] 2021-11-17 14:25
Hi @ashwgupt,

Thanks for filing the issue. Can you expand on your use case here a little more? From the example given, you are removing the local `.terraform` directory, which contains a record of the installed modules. This means that terraform is not going to be able to determine the providers required for `terraform providers mirror` until you again run `terraform init`, which explains the error message you see. 

Thanks!

**Comment by ashwgupt** [comment] 2021-11-22 04:33
Hi @jbardin 

That is exactly the case. I have involved the step to remove `.terraform` folder to mimic a case of new TF folder (one that has never run `init` before). There are at least 2 possible cases when it can be witnessed - 1. In pipeline runs, 2. First or clean run on local for a newly created TF directory.

In such cases, the module information is not known to TF and the mirror command fails but without the mirror command run, even the init command fails since the provided mirror folder does not has the required providers mirrored yet. So, irrespective of which of the commands - `init` or `mirror` one runs for the case of new TF folder, it is bound to fail.

Hope I was able to clarify the case. Please let me know if any further information/clarification required.

**Comment by jbardin** [comment] 2021-12-02 13:49
If you have removed the `.terraform` directory, then `init` is always required if there are modules being called. You cannot determine what providers those modules may require from the root module alone.

I'm going to close this out since Terraform is working as intended here. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-12-02 13:49 UTC
Labels: bug, waiting-response, new

**Comment by ashwgupt** [comment] 2021-12-03 04:09
That is well understood @jbardin. Unfortunately I couldn't make you understand the problem but if you try and run the mirror command in a automated pipeline, you will get to see what I meant.
