### ISSUE TITLE
Escape \" in the string variable don't work

### ISSUE THREAD

**Issue by JJussi** [hashicorp/terraform#30388] opened 2022-01-21 08:40 UTC
### Terraform Version

```
Terraform v1.0.9
on windows_amd64
```

### Terraform Configuration Files

```
output.tf
======
variable "var1" {
  type = string
  default = "This \"string\" have problems!"
}

output "problematic_string" {
  value = "Here: ${var.var1}"
}
```

### Expected Behavior

problematic_string = "Here: This "string" have problems!"

### Actual Behavior

problematic_string = "Here: This \\"string\\" have problems!"

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

Problem is that I "output" commands what user should run after terraform apply. Those command must have "-characters round values of command.  Now there is \"command -c \\"command value\\"\"  what user cannot just copy paste and run.

**Comment by JJussi** [comment] 2022-01-21 09:00
Here is real life example:

`command_to_run_2 = "az postgres flexible-server execute -n audit-nonprod -u npsadmin -p 'werygoodpassword'  -d 'postgres' -q \"alter role audit_user PASSWORD '<some random password>'; alter role filestorage_user PASSWORD '<some random password>';\""`

**Comment by kmoe** [comment] 2022-01-21 09:45
Thanks for the report. I think the Actual Behavior section may have been accidentally copied from Expected Behavior - what I see in this example is 
```
problematic_string = "Here: This \"string\" have problems!"
```

This is expected behaviour for string output values, since the output in `terraform apply` and `terraform output` is intended to be similar to the configuration syntax.

When output values are intended for machine, rather than human, consumption, as in your example, we recommend using `terraform output -raw`. For example:

```
$ terraform output -raw problematic_string
Here: This "string" have problems
```
This should result in a command that users can copy paste and run in the shell.
Let me know if this solves your issue.

**Comment by JJussi** [comment] 2022-01-21 09:56
Not directly... 
Right now, when the user runs the command "terraform apply", all "outputs" come as the last lines of this apply output. From where user can copy&paste them to the same command line where the "terraform apply" command was run.
To use this "terraform output -raw", I need to use some script file that does everything for the user.

**Comment by JJussi** [comment] 2022-01-21 10:09
This of course could be changed to "feature" request then..

output "problematic_string" {
  raw = true
  value = "Here: ${var.var1}"
}

So, if you set "raw" to true (default value false), output would be "raw"...

**Comment by JJussi** [comment] 2022-01-25 06:49
Hi, yes that  \\n at the end of string made difference. Now the result is much practical for "copy&paste" operation.

**Comment by crw** [comment] 2022-02-03 01:29
Thanks for the report @JJussi! I am going to close this as it appears to be working as expected and we seem to have found a work-around for your use case. If you think this is being closed in error, please let me know.

**Closed by crw** 2022-02-03 01:29 UTC
Labels: waiting-response, explained
