### ISSUE TITLE
depends_on in submodule not working?

### ISSUE THREAD

**Issue by SantoDE** [hashicorp/terraform#11224] opened 2017-01-16 15:30 UTC
### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
Ressources in submodules. 

### Terraform Configuration Files
```
site.tf
module "modulea" {
  source             = "./modules/modulea"
  vpc_id             = "${module.shared.vpc_id}"
  aws_region         = "${var.aws_region}"
  rancher_ha_ssl_arn = "${var.rancher_ha_ssl}"
  aws_key_pair_name  = "terraform"
  shared_security_groups_id = "${module.shared.docker_cluster_default_securtiy_group_id}"
 
  # Server config
  server_name     = "XXX"
  server_hostname = "XXX.de"
  sub_domain      = "XXX.de"
 
  # Database
  database_username = "XXX"
  database_password = "XXX"
  database_name     = "XXX"
 
  #ELB Config
  route_zone_id = "XXX"
}
 
./modules/moduleb/rancher.tf
# Create a new Rancher environment
resource "rancher_environment" "default" {
  name = "${var.customer_name}"
  description = "Environment for Customer '${var.customer_name}'"
  depends_on = ["module.modulea"]
  orchestration = "cattle"
}
```

### Expected Behavior
I expected that the "depends_on" command works and that it successfully set's the reference.

### Actual Behavior
`Error loading Terraform: module moduleb.root: 1 error(s) occurred:

* rancher_environment.default: resource depends on non-existent module 'modulea'`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
It happens with all ressources in moduleb

**Comment by derBroBro** [comment] 2017-01-17 11:26
Looks like the same as https://github.com/hashicorp/terraform/issues/10462

**Comment by grubernaut** [comment] 2017-01-17 15:30
Thanks! Closing, duplicate of #10462

**Closed by grubernaut** 2017-01-17 15:30 UTC
