### ISSUE TITLE
`terraform init` redownloads plugins every time

### ISSUE THREAD

**Issue by Minutis** [hashicorp/terraform#27099] opened 2020-12-03 09:28 UTC
Every time you run `terraform init` plugins are beeing reinstalled although u already have them inside your `.terraform` dir locally.

### Terraform Version
```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.13.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.7.0
```

### Expected Behavior
```
Initializing provider plugins...
- Reusing previous version of hashicorp/archive from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of mongodb/mongodbatlas from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html
```

### Actual Behavior
```
Initializing provider plugins...
- Reusing previous version of hashicorp/archive from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of mongodb/mongodbatlas from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file
- Installing hashicorp/random v3.0.0...
- Installed hashicorp/random v3.0.0 (signed by HashiCorp)
- Installing hashicorp/kubernetes v1.13.3...
- Installed hashicorp/kubernetes v1.13.3 (signed by HashiCorp)
- Installing mongodb/mongodbatlas v0.7.0...
- Installed mongodb/mongodbatlas v0.7.0 (signed by a HashiCorp partner, key ID xxxxxxxx)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
- Installing hashicorp/archive v2.0.0...
- Installed hashicorp/archive v2.0.0 (signed by HashiCorp)
- Installing hashicorp/aws v3.13.0...
- Installed hashicorp/aws v3.13.0 (signed by HashiCorp)
- Installing hashicorp/local v2.0.0...
- Installed hashicorp/local v2.0.0 (signed by HashiCorp)


Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html
```

### Steps to Reproduce
1. `terraform init`
2. `terraform init`
3. `terraform init -get-plugins=false`
4. `terraform init -verify-plugins=false`

**Comment by dzirg44** [comment] 2020-12-03 12:03
@Minutis do you use terragrunt? If so - please disable https://terragrunt.gruntwork.io/docs/features/auto-init/#auto-init

**Comment by pkolyvas** [comment] 2020-12-03 14:00
Thanks for reporting this @Minutis, I'm going to close this as a duplicate of #27092.

**Closed by pkolyvas** 2020-12-03 14:00 UTC
Labels: bug, duplicate
