### ISSUE TITLE
Bug on applying azurerm_route

### ISSUE THREAD

**Issue by edevil** [hashicorp/terraform#8787] opened 2016-09-12 10:43 UTC
Error applying plan:

2 error(s) occurred:
- azurerm_route.node_route.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

```
Terraform Version: 0.7.3
Resource ID: azurerm_route.node_route.0
Mismatch reason: attribute mismatch: next_hop_in_ip_address
Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"next_hop_in_ip_address":*terraform.ResourceAttrDiff{Old:"10.0.3.10", New:"${element(azurerm_network_interface.nodeNIC.*.private_ip_address, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}
```

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
- azurerm_route.node_route.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

```
Terraform Version: 0.7.3
Resource ID: azurerm_route.node_route.1
Mismatch reason: attribute mismatch: next_hop_in_ip_address
Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"next_hop_in_ip_address":*terraform.ResourceAttrDiff{Old:"10.0.3.11", New:"${element(azurerm_network_interface.nodeNIC.*.private_ip_address, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}
```

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by mitchellh** [comment] 2016-11-17 00:53
Hello! This should be fixed in later versions of Terraform (0.7.11 at time of writing). 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 00:53 UTC
Labels: bug, provider/azurerm
