### ISSUE TITLE
Creating Azure ARM strage account at the second time fails

### ISSUE THREAD

**Issue by TsuyoshiUshio** [hashicorp/terraform#6412] opened 2016-04-29 06:08 UTC
When I tried to create a storage account using Terraform, it woks fine at the first time. 
It fails at the second time.

I think the problem is the storage account name.  
If I change the storage account name at the second time, it successes. 

I guess that is why Azure Resource Manager has uniqueString function. 
The storage account might be deleted later. 

Azure Resource Manager template generate this code for getting storage account name.

```
"StorageAccount01Name": "[concat('sa01', uniqueString(resourceGroup().id))]",
```
This is a sample code of Azure Resource Manager Template.

https://github.com/TsuyoshiUshio/NomadClusterARM/blob/master/NomadCluster/NomadCluster/Templates/LinuxVirtualMachine.json

Unique string function

https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#uniquestring
 
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)

azurerm_storage_account

### Terraform Configuration Files
```hcl
provider "azurerm" {
  subscription_id = "..."
  client_id       = "..."
  client_secret   = "..."
  tenant_id       = "..."
}
resource "azurerm_resource_group" "test" {
    name = "TerraformResource"
    location = "Japan East"
}

resource "azurerm_storage_account" "test" {
    name = "accsa2016"
    resource_group_name = "${azurerm_resource_group.test.name}"
    location = "Japan West"
    account_type = "Standard_LRS"

    tags {
        environment = "staging"
    }
}

```

### Expected Behavior
It works fine, even when we try "terraform apply" at the second time.

However, I think this might be the matter of Azure architecture. If you could provide an uniqueString
like function,It might solve the problem.

### Actual Behavior
The first time, "terraform apply" works fine. However, the second time, creating storage
account  never ends.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
-> It works fine 
3. `terraform destroy`
4. `terraform apply`

```
azurerm_storage_account.test: Creating...
  account_type:             "" => "Standard_LRS"
  location:                 "" => "japanwest"
  name:                     "" => "accsa2016"
  primary_blob_endpoint:    "" => "<computed>"
  primary_file_endpoint:    "" => "<computed>"
  primary_location:         "" => "<computed>"
  primary_queue_endpoint:   "" => "<computed>"
  primary_table_endpoint:   "" => "<computed>"
  resource_group_name:      "" => "TerraformResource"
  secondary_blob_endpoint:  "" => "<computed>"
  secondary_location:       "" => "<computed>"
  secondary_queue_endpoint: "" => "<computed>"
  secondary_table_endpoint: "" => "<computed>"
  tags.#:                   "" => "1"
  tags.environment:         "" => "staging"
azurerm_storage_account.test: Still creating... (10s elapsed)
azurerm_storage_account.test: Still creating... (20s elapsed)
azurerm_storage_account.test: Still creating... (30s elapsed)
    :  until time out.
```
### Important Factoids

Azure ARM

### References

https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#uniquestring

**Comment by Preskton** [comment] 2016-05-10 18:35
Confirmed, able to reproduce.  Appears that there is a holding period after you destroy a storage account during which you can't reprovision a storage account of the same name.  I'm not sure of the length, but it's less than an hour.

**Comment by TsuyoshiUshio** [comment] 2016-05-17 15:00
I researched the Azure architecture.  I think terraform had better to implement "uniqueString" function to solve this problem. I've got this comment from the development team unofficially. :p

"The length of time is dependent on the amount of data in the storage account, and it is done asynchronously in the background as part of normal garbage collection operations.  As such, there is no set amount of time that it will take, and you should not depend on the same storage account name being available immediately after deleting an account.  You should consider changing the storage account name for each deployment."

**Comment by stack72** [comment] 2016-07-15 16:43
Hi @TsuyoshiUshio 

There is already an interpolation called [uuid](https://www.terraform.io/docs/configuration/interpolation.html#uuid_) for random strings. Terraform has no control over the time to be able to recreate the same storage account after destroying it. If you are going to use something like uuid, then please read the documentation carefully as it may have unintended side effects for you

I am going to close this issue out for now as this is something outside of our control. If there is anything else you think is needed, then please do let us know

Thanks

Paul

**Closed by stack72** 2016-07-15 16:43 UTC
Labels: bug, provider/azurerm
