### ISSUE TITLE
Interpolation not working with module exported variable

### ISSUE THREAD

**Issue by daaru00** [hashicorp/terraform#15687] opened 2017-08-02 10:05 UTC
Hi there,
I have a trouble to use interpolation syntax using module exported variable

### Terraform Version
v0.9.11

### Terraform Configuration Files
```hcl
module "internal-dns" {
    ...
    
    elasticache_endpoint = "${var.elasticache_replica ? module.elasticache.endpoint_group : module.elasticache.endpoint_cluster}"
}
```
```hcl
module "internal-dns" {
    ...
    
    elasticache_endpoint = "${!var.elasticache_replica ? module.elasticache.endpoint_group : module.elasticache.endpoint_cluster}"
}
```
```hcl
module "internal-dns" {
    ...
    
    elasticache_endpoint = "${var.elasticache_replica ? module.elasticache.endpoint_cluster : module.elasticache.endpoint_group }"
}
```
`elasticache_endpoint` result empty
```hcl
module "internal-dns" {
    ...
    
    elasticache_endpoint = "${module.elasticache.endpoint_group}"
}
```
`elasticache_endpoint` variable is correctly valorized.

### Expected Behavior
Expected `elasticache_endpoint` variable valorized with `elasticache.endpoint_cluster` or `elasticache.endpoint_group` value in according with `var.elasticache_replica` boolean value.

### Actual Behavior
`var.elasticache_replica` is set with `elasticache_replica  = true` in terraform.tfvars file, same result setting it with `elasticache_replica  = "true"`.
In all case variable `elasticache_endpoint` is empty.

### Steps to Reproduce
1. `terraform plan`

**Comment by daaru00** [comment] 2017-08-02 11:00
Update: all interpolation not working with output variable from non-existing resources

in elasticache module
```
resource "aws_elasticache_replication_group" "elasticache" {
    count = "${var.replica && var.enable ? 1 : 0}"
    ..
}

resource "aws_elasticache_cluster" "elasticache" {
    count = "${var.replica || !var.enable ? 0 : 1}"
    ...
}

output "endpoint_cluster" {
    value = "${aws_elasticache_cluster.elasticache.cluster_address}"
}

output "endpoint_group" {
    value = "${aws_elasticache_replication_group.elasticache.primary_endpoint_address}"
}
```
in root module
```hcl
module "internal-dns" {
    ...
    
    elasticache_endpoint = "${var.elasticache_replica ? module.elasticache.endpoint_group : module.elasticache.endpoint_cluster}"
}
```
Debugging it using `terraform output -module=elasticache endpoint_cluster`
```
The output variable requested could not be found in the state
file. If you recently added this to your configuration, be
sure to run `terraform apply`, since the state won't be updated
with new output variables until that command is run.
```

How can I check "undefined" variables?

**Comment by jbardin** [comment] 2017-08-02 13:25
Hi @daaru00,

There is no way to check for undefined variables, because in Terraform _all_ variables must be defined. The related issue you're hitting here is that unfortunately outputs can't currently cause errors on their own, so invalid outputs that are't referenced don't end up in the state. You can however at least see the output errors in the debug logs. 

You would need to assign some default value to a variable in order to compare it in a conditional statement. Conditionals also can't short circuit, so all parts of the statement must be resolvable.

Since we already have plans to fix the output issue and improve the interpolation features, I'm going to close this for now. If you still run into other unexpected behavior related to this issue, feel free to reply and we can re-open as necessary.

**Closed by jbardin** 2017-08-02 13:25 UTC
Labels: enhancement
