### ISSUE TITLE
nesteed loop

### ISSUE THREAD

**Issue by zdogan** [hashicorp/terraform#22177] opened 2019-07-23 13:35 UTC
### Current Terraform Version

```
...
```

**Comment by teamterraform** [comment] 2019-07-23 18:05
Hello, to better understand this issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by teamterraform** [comment] 2019-07-23 18:07
Duplicate of https://github.com/hashicorp/terraform/issues/22178

**Closed by teamterraform** 2019-07-23 18:07 UTC
