### ISSUE TITLE
The provider argument name "for_each" is reserved for use by Terraform in a future version.

### ISSUE THREAD

**Issue by Pierre-Alexandre35** [hashicorp/terraform#29840] opened 2021-10-31 08:45 UTC
### Terraform Version

```
1.0.10
```
### Terraform project structure
```
.
├── backend.tf
├── bootstrap
│   ├── backend.tf
│   ├── providers.tf
│   ├── variables.tf
│   └── versions.tf
├── main.tf
├── modules
│   ├── accounts
│   │   ├── locals.tf
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── organizations
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   └── users
│       ├── main.tf
│       └── variables.tf
├── providers.tf
├── secrets.auto.tfvars
├── users.auto.tfvars
├── variables.tf
└── versions.tf
```

### Terraform Configuration Files

versions.tf
```terraform
terraform {
  required_version = ">= 1.0.1"
  required_providers {
    aws = ">= 3.5.0"
  }
}
```
main.tf
```
/**********************************
* ORGANIZATION SPECIFIC RESOURCES
***************************/
module "organizations" {
  source = "./modules/organizations"
}

/**************************
* AWS ACCOUNTS SPECIFIC RESOURCES *
***************************/
module "accounts" {
  users                          = var.dev_team_members
  manager                        = var.sandboxs_manager
  source                         = "./modules/accounts"
  sandbox_organizational_unit_id = module.organizations.sandbox_organizational_unit_id
  pgp_key                        = var.pgp_key
}


/**************************
* AWS IAM USERS SPECIFIC RESOURCES *
***************************/
module "users" {
  source               = "./modules/users"
  sandbox_aws_accounts = module.accounts.sandbox_aws_accounts
}
```
modules/users/variables.tf
```
variable "sandbox_aws_accounts" {
    type = list
}
```
modules/users/main.tf
```
provider "aws" {   
    for_each = var.sandbox_aws_accounts
    region  = "eu-west-3"
    alias = "new_account"    
    assume_role {     
        role_arn     = "arn:aws:iam::${var.sandbox_aws_accounts}:role/OrganizationAccountAccessRole"     
        session_name = "new_account_creation"   
        } 
    }  
resource "aws_s3_bucket" "bucket" {   
    provider = aws.new_account    
    bucket = "new-account-bucket"  
    acl    = "private" 
} 
```
### Expected Behavior
 The modules/accounts.main.tf should create a S3 bucket for each AWS accounts where ```sandbox_aws_accounts```is a list of AWS account IDs 

### Actual Behavior

```
│ Error: Reserved argument name in provider block
│ 
│   on modules/users/main.tf line 2, in provider "aws":
│    2:     for_each = var.sandbox_aws_accounts
│ 
│ The provider argument name "for_each" is reserved for use by Terraform in a future version.
```

**Comment by jbardin** [comment] 2021-11-01 13:49
Hi @Pierre-Alexandre35,

What the error being returned means, is that `for_each` is not supported within `provider` blocks, however we have reserved that keyword for possible future enhancements. Attempting to use `for_each` within a provider is expected to return this error. Since this is not a bug in Terraform, I'm going to close this issue for now.

You may be interested in following the associated enhancement request here: #19932, and the related request to more dynamically pass providers to modules expanded using `for_each` here: #25244

Thanks!

**Closed by jbardin** 2021-11-01 13:49 UTC
Labels: bug, new

**Comment by aaomidi** [comment] 2021-11-22 01:48
Hey there @Pierre-Alexandre35, I came across this problem as well googled around a bit and came across this issue. I think your issue is that you want to have multiple `assume_role`s inside the aws provider, right? In that case something like this might help you out (this example is specific to an lxd provider, but it's going to be the same idea)

```
provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  dynamic "lxd_remote" {
    for_each = [for r in var.remotes : {
      name     = r.name
      scheme   = r.scheme
      address  = r.address
      password = r.password
    }]

    content {
      name     = lxd_remote.value.name
      scheme   = lxd_remote.value.scheme
      address  = lxd_remote.value.address
      password = lxd_remote.value.password
      default  = false
    }
  }
}

```

To be fair I have not tried this with more than one remote yet, but it did work with just one remote being defined in the var file.

**Comment by rjudin** [comment] 2021-11-22 05:27
> Hey there @Pierre-Alexandre35, I came across this problem as well googled around a bit and came across this issue. I think your issue is that you want to have multiple `assume_role`s inside the aws provider, right? In that case something like this might help you out (this example is specific to an lxd provider, but it's going to be the same idea)
> 
> ```
> provider "lxd" {
>   generate_client_certificates = true
>   accept_remote_certificate    = true
> 
>   dynamic "lxd_remote" {
>     for_each = [for r in var.remotes : {
>       name     = r.name
>       scheme   = r.scheme
>       address  = r.address
>       password = r.password
>     }]
> 
>     content {
>       name     = lxd_remote.value.name
>       scheme   = lxd_remote.value.scheme
>       address  = lxd_remote.value.address
>       password = lxd_remote.value.password
>       default  = false
>     }
>   }
> }
> 
> ```
> 
> To be fair I have not tried this with more than one remote yet, but it did work with just one remote being defined in the var file.

It can't work, because that will produce a single provider resource.
For multiple roles resources should be able to use associated provider (role). 
The aws providers differentiated by alias, which is not under "assume_role" block.

**Comment by aaomidi** [comment] 2021-11-22 06:52
@rjudin I see, I thought they just wanted multiple assume roles under just one provider. Well, hopefully what I posted might still be helpful for someone wanting to do that.
