### ISSUE TITLE
Unable to pass workspace to -backend-config

### ISSUE THREAD

**Issue by Maetis** [hashicorp/terraform#32839] opened 2023-03-14 14:04 UTC
### Terraform Version

```shell
1.3.7
```

### Terraform Configuration Files

terraform {
  backend "remote" {}
}

### Debug Output

.

### Expected Behavior

Terraform should accept my workspaces.name variable

### Actual Behavior

Terraform complains that workspaces.name is not expected for the selected backend type

### Steps to Reproduce

terraform init -backend-config="hostname=xxx" -backend-config="organization=yyy" -backend-config="workspaces.name=zzz"

### Additional Context

```
Initializing the backend...
╷
│ Error: Invalid backend configuration argument
│
│ The backend configuration argument "workspaces.name" given on the command line is not expected for the selected backend type.
╵
```

We want to provide Terraform pipeline templates to our dev teams. In this templates the workspace is defined as a variable.

Our workaround for now is to create a backend.hcl file during the pipeline execution.
```
- script: |
          cat > backend.hcl << EOF
          hostname     = "$(tf_backend_hostname)"
          organization = "$(tf_backend_organization)"
          token        = "$(tf_backend_token)"
          workspaces { name = "$(tf_backend_workspace)" }
          EOF
```

### References

#31328

**Comment by jbardin** [comment] 2023-03-14 14:20
Hi @Maetis,

This appears to be a duplicate of the linked issue, which explains that the `workspaces` block cannot be set via the `-backend-config` flag. The `remote` backend however has been replaced by the `cloud` configuration. https://github.com/hashicorp/terraform/issues/31328#issuecomment-1168804507. Because the `remote` backend has been replaced, there are not going to be any changes to how it is configured.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2023-03-14 14:20 UTC
Labels: bug, new

**Comment by Maetis** [comment] 2023-03-14 14:26
Hi @jbardin,

We use the ```remote``` backend because we use Artifactory to store our state.

Have a nice day!
