### ISSUE TITLE
How to split a list of multiple maps into multiple lists of maps

### ISSUE THREAD

**Issue by pranavnateri** [hashicorp/terraform#33122] opened 2023-04-29 17:46 UTC
### Terraform Version

```shell
Terraform v1.4.6
```

### Terraform Configuration Files

How to split a list of multiple maps into multiple lists of maps based on a certain condition.

I have the below list of maps for example

```
[{
domain_name           = "*.xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
},
{
domain_name           = "test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "*.test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "*.dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
},
{
domain_name           = "*.staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
]

```

i want to split this list of maps into 2 lists of maps based on the condition that if domain_name is "xpressplay.net" or "*.xpressplay.net" eventually to become like below

```
[{
domain_name           = "*.xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
},
{
domain_name           = "xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
}
]
```

```
[{
domain_name           = "test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "*.test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "*.dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "*.staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
]

```

Please help

Regards,
Pranav

### Debug Output

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Steps to Reproduce

N/A

**Comment by sushant-kapoor17** [comment] 2023-04-30 07:42
Hello @pranavnateri ,

The input list seems like a list of objects and not map. A list of map will usually contain a format like 
a key => object
For e.g. 
```
[
xpressplay.net = {
domain_name           = "*.xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
}
,
test.expressplay.com = {
domain_name           = "test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
...
```



Terraform documentation is a great resource to look for help and it provides quite a lot of good examples with many scenarios like filtering elements, for complex value types. 
[https://developer.hashicorp.com/terraform/language/expressions/for#filtering-elements](https://developer.hashicorp.com/terraform/language/expressions/for#filtering-elements)

And, for your solution, here's what you will need to do :

I have defined a variable for domains as 

``` javascript
variable "domains" {
  type = list(any)
  default = [{
    domain_name           = "*.xpressplay.net"
    resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
    resource_record_type  = "CNAME"
    resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
    },
    {
      domain_name           = "test.expressplay.com"
      resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
      resource_record_type  = "CNAME"
      resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
    },
    {
      domain_name           = "*.test.expressplay.com"
      resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
      resource_record_type  = "CNAME"
      resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
    },
    {
      domain_name           = "dev.expressplay.com"
      resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
      resource_record_type  = "CNAME"
      resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
    },
    {
      domain_name           = "*.dev.expressplay.com"
      resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
      resource_record_type  = "CNAME"
      resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
    },
    {
      domain_name           = "xpressplay.net"
      resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
      resource_record_type  = "CNAME"
      resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
    },
    {
      domain_name           = "*.staging.expressplay.com"
      resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
      resource_record_type  = "CNAME"
      resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
    },
    {
      domain_name           = "staging.expressplay.com"
      resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
      resource_record_type  = "CNAME"
      resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
    },
  ]
}
```

and then , created two local variables which filters and creates separate lists as desired:
```javascript
locals {  
  xpressplay_domains = [for obj in var.domains : obj
    if obj.domain_name == "xpressplay.net"
    || obj.domain_name == "*.xpressplay.net"
  ]

  non_xpressplay_domains = [for obj in var.domains : obj
    if obj.domain_name != "xpressplay.net"
    && obj.domain_name != "*.xpressplay.net"
  ]
 
}
```

which eventually results in :

``` javascript
non_xpressplay_domains = [
  {
    "domain_name" = "test.expressplay.com"
    "resource_record_name" = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
  },
  {
    "domain_name" = "*.test.expressplay.com"
    "resource_record_name" = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
  },
  {
    "domain_name" = "dev.expressplay.com"
    "resource_record_name" = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
  },
  {
    "domain_name" = "*.dev.expressplay.com"
    "resource_record_name" = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
  },
  {
    "domain_name" = "*.staging.expressplay.com"
    "resource_record_name" = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
  },
  {
    "domain_name" = "staging.expressplay.com"
    "resource_record_name" = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
  },
]
xpressplay_domains = [
  {
    "domain_name" = "*.xpressplay.net"
    "resource_record_name" = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
  },
  {
    "domain_name" = "xpressplay.net"
    "resource_record_name" = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
    "resource_record_type" = "CNAME"
    "resource_record_value" = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
  },
]


```

Hope this helps.

I would also like to request you to please close this issue upon resolution , as this is not a bug/enhancement required within Terraform.

Thanks !

**Comment by jbardin** [comment] 2023-05-01 12:19
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2023-05-01 12:19 UTC
Labels: bug, question, new
