### ISSUE TITLE
State files from projects using TF >=1.5 and the `check` block cannot be loaded as remote state by TF >=1.3, <1.5 

### ISSUE THREAD

**Issue by evan-cleary** [hashicorp/terraform#33770] opened 2023-08-30 19:33 UTC
### Terraform Version

```shell
Terraform v1.4.6
on darwin_amd64
```

### Terraform Configuration Files

https://github.com/evan-cleary/tf1_5-state-compatibility

### Debug Output

https://gist.github.com/evan-cleary/d036479be1c61dc2c09625928c90aec1

### Expected Behavior

We expected that state files generated by the 1.X family would be compatible within the 1.X family.

### Actual Behavior

Terraform state files generated by version >= 1.5 cannot be loaded as remote state data source by terraform configurations `>=1.3, < 1.5` if the source configuration uses check blocks.

Produces error:
`Error: unsupported checkable object kind "check"`
![image](https://github.com/hashicorp/terraform/assets/1305289/56a91228-eec0-496c-a58e-a0b5e8affb7a)

### Steps to Reproduce

Provided repository has an example set of terraform configurations that replicate the seen behavior.

If you have `tfenv` installed on your system you can run `./run_test.sh` to see behavior.

If you do not have `tfenv` installed on your system
1. Download TF 1.4.6, or any version `>=1.3, <1.5`, binary and place `terraform` binary in tf1_X directory
2. Download TF 1.5.X binary and place `terraform` binary in tf1_5 directory
3. Run `./run_test.sh`

### Additional Context

We have multiple terraform configuration in our organizations with varying versions of terraform 1.X throughout. If any one project upgrades to >= 1.5 and uses the new `check` blocks, this would break automation for any configuration that utilizes that projects remote state.

Experimentation has determined that tf >=1.5 state files can be loaded by version `>=1.0, <1.3`

**Comment by crw** [comment] 2023-08-30 22:19
Thanks for this report. Please note that this level of backwards compatibility is explicitly called out as not being supported in the [Terraform v1.x Compatibility Promises](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises#upgrading-and-downgrading). That said, I will leave this issue open as a solution may be possible. Thanks!

**Comment by evan-cleary** [comment] 2023-08-31 00:37
@crw Any reason the state file version was not updated to V5 under this condition? Is compatibility within a state file version not guaranteed?

The current implementation of the check_results section parsing results in a breaking change to state file parsing every time a CheckableKind is added.

Comments around check_result parsing indicates there was, at one point, an intent for forward compatibility.
https://github.com/hashicorp/terraform/blob/9e9a78e96cd242697be58aad39b1cb11e43ca802/internal/states/statefile/version4.go#L648-L653

**Comment by alisdair** [comment] 2023-08-31 12:07
Thanks for reporting this!

This narrow incompatibility was unforeseen, and we'd like to find a way to address it. We're currently looking into options for a fix. I'll update this ticket when we have a decision and a plan.

**Comment by alisdair** [comment] 2023-09-06 14:31
We think we have a narrow compatibility bug fix that we hope to be able to release in 1.4.7 and possibly 1.3.10. Our release pipeline has changed significantly since the 1.3 series, so it's not clear whether or not such a patch release will be possible at this time. We'll announce any patch releases in the usual places once they've been made.

Thanks again for the clear report, and particularly the helpful reproduction code!

**Comment by alisdair** [comment] 2023-09-06 16:18
@evan-cleary Yep, the PR for that is here: https://github.com/hashicorp/terraform/pull/33815

**Comment by alisdair** [comment] 2023-09-14 11:04
This is fixed in the latest patch releases from the 1.5, 1.4, and 1.3 series, as well as the forthcoming 1.6. Thanks again for reporting the bug!

**Closed by alisdair** 2023-09-14 11:04 UTC
Labels: bug, confirmed, v1.3, v1.4

**Comment by rjminchuk** [comment] 2023-10-11 21:04
not sure if this is related to 1.6.0+ release, or this check issue.. but...

```
...
Plan: 0 to add, 0 to change, 129 to destroy.

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]:
https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.aws_account.var.account_email
goroutine 5063 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x164
panic({0x1038ae8a0?, 0x1400cd26090?})
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x26c
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0x1400782cd50, {0x103ee08a8, 0x1400aee94d0}, 0x0?, 0x0, 0x50)
        /Users/runner/work/terraform/terraform/internal/checks/state_report.go:106 +0x2a8
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x103cea720?, {0x103ee08a8?, 0x1400aee94d0?}, 0x14002eb1678?, 0x1?, 0x2503440?)
        /Users/runner/work/terraform/terraform/internal/checks/state_report.go:71 +0xd4
github.com/hashicorp/terraform/internal/terraform.evalVariableValidations({{0x14002c08020, 0x1, 0x1}, {{}, {0x14002503440, 0xd}}}, 0x140013ecd00, {0x103edc090, 0x140000dbec0}, {0x103ef6450, ...})
        /Users/runner/work/terraform/terraform/internal/terraform/eval_variable.go:252 +0x85c
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0x1400ac9c720, {0x103ef6450, 0x1400190bb20}, 0x0?)
        /Users/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:198 +0x2d4
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x140028aa240, {0x103ef6450, 0x1400190bb20}, {0x14d087c08, 0x1400ac9c720})
        /Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xa0
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x103c26a60, 0x1400ac9c720})
        /Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x280
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x1400ac9c7e0, {0x103c26a60, 0x1400ac9c720}, 0x14007890080)
        /Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2a8
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 5671
        /Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xb0c
ERRO[0091] Terraform invocation failed in /Users/Rich/Documents/repo/thing/demo62/.terragrunt-cache/7EHM3r7ped3quRSf6L3WTpPWaMM/zEYsgu7zdBJ9HQk8_DgfFz-gvtU/modules/data_reporting  prefix=[/Users/Rich/Documents/repo/thing/demo62/] 
ERRO[0091] Module /Users/Rich/Documents/repo/thing/demo62/ has finished with an error: 1 error occurred:
        * exit status 11
  prefix=[/Users/Rich/Documents/repo/thing/demo62/] 
ERRO[0091] 1 error occurred:
        * exit status 11
```

```js
# .tfstate
{
  "version": 4,
  "terraform_version": "1.6.1",
  "serial": 10,
  "lineage": "dadf392a-e257-d89c-fff7-xxxxxxxxxx",
  "outputs": {},
  "resources": [
    ...
	],
  "check_results": [
    {
      "object_kind": "var",
      "config_addr": "module.aws_account.var.account_email",
      "status": "pass",
      "objects": [
        {
          "object_addr": "module.aws_account.var.account_email",
          "status": "pass"
        }
      ]
    }
  ]
}
```

I haven't added any checks to our terraform code, but wasn't sure where to bring up this kind of issue..

We've since downgraded to 1.5.7 and we've been able to destroy the necessary resources.

**Comment by alisdair** [comment] 2023-10-11 21:33
@rjminchuk Thanks for the note. Would you mind filing this as a new issue so that we can be sure to address it?

**Comment by liamcervante** [comment] 2023-10-12 07:32
Just closing the loop on the latest comments - we have #34052 tracking the issue seen by @rjminchuk.
