### ISSUE TITLE
Unexpected diff after `import` for schema.TypeMap resource attribute with v0.12.2

### ISSUE THREAD

**Issue by afedorch** [hashicorp/terraform#21737] opened 2019-06-15 00:24 UTC
### Terraform Version

```
0.12.2
```

### Terraform Configuration Files

The behavior is the same for all schema.TypeMap without DiffSuppressFunc, as an example `oci_core_virtual_network` resource:
```hcl
resource "oci_core_virtual_network" "vcn1" {
  cidr_block     = "10.0.0.0/16"
  dns_label      = "vcn1"
  compartment_id = "${var.compartment_ocid}"
  display_name   = "vcn1"
}
```

### Debug Output

```
State file difference: `apply`(create) resource vs `import` resource by Terraform v0.12.2 for schema.TypeMap:
“defined_tags”: {}   |   “defined_tags”: null
“freeform_tags”: {}  |   “freeform_tags”: null

State file is the same for `apply`(create) resource and `import` resource by Terraform v0.11.7 for schema.TypeMap:
“defined_tags.%“: “0”
“freeform_tags.%“: “0”
```

### Expected Behavior

No difference after `apply` and `import` for the resource in the state file. Empty value for schema.TypeMap instead of null

### Actual Behavior

State file value depends on the command for the same configuration, service response and provider:
“freeform_tags”: {}  vs  “freeform_tags”: null

### Additional Context

It looks like `DiffSuppressFunc` could help for these cases, do we need to add it for all schema.TypeMap properties to avoid this behavior? 

### References

https://github.com/terraform-providers/terraform-provider-oci/issues/792
https://github.com/hashicorp/terraform/issues/21266

**Comment by jbardin** [comment] 2019-06-17 15:20
Hi @afedorch,

Thanks for filing this. Because the existing legacy SDK can't always differentiate between unset and empty values, there are some cases like this that simply can't be resolved automatically, but I think this one may be repairable within the provider itself.

What I believe is happening is that the `freeform_tags` attribute is marked as both `Optional` and `Computed`, but I don't see where it is ever computed within the resource. If the value is going to be computed, it needs to be set by the provider at some point if it's not provided in the config.

I think either removing `Computed` from the attribute (if it's not really computed), or having the provider set an empty map if there is no other value will remedy the situation.

**Comment by afedorch** [comment] 2019-06-17 20:18
@jbardin thanks for the fast response!

`freeform_tags` attribute is marked as both `Optional` and `Computed` and the value is set in `setData` for both GET and POST responses for all resources.
I think that the main directions that we need to clarify for v0.12 here are:
- if we are setting empty map in setData we should not have `null` in the state depending on the operation (`Create` vs `Import`), correct?
- if we have `null` as a value for the TypeMap in the state file, it should not be a `diff` for the user's configuration without TypeMap attribute in the configuration, correct?
- do we need to set `default` values for all types in v0.12? Will it be a `diff` for the user if the state has an empty map and the configuration does not have the attribute? Should we handle all these cases with `DiffSuppressFunc`? 
Thanks!

**Comment by afedorch** [comment] 2019-06-17 22:19
@jbardin similar problem with AWS provider [#21266](https://github.com/hashicorp/terraform/issues/21266)

**Comment by jbardin** [comment] 2019-06-17 23:53
From what I can tell so far (at least from my example resources), I think that if the resource is setting the `freeform_tags` attribute, it's being set with a `nil` map which is why it's showing up as `nil` after import. The "flatmap" value like `“freeform_tags.%“` are no longer by terraform, but are still used in the acceptance tests for compatibility with existing providers. If you have a particular test in question, I can take a look at that itself.

If you have a `null` in the state file, and the user has an empty `{}` value in the config, that will result in a diff, as they have different meanings. The existing SDK is not consistent about empty vs missing values, so it would ignore some changes like that, but terraform core is now what creates the initial plan with more type information.

You can think of a default value as a special case of computed that is applied during Plan, but whether you should have that or not is up to your resource. If there's a default, you cannot change it again later during apply. If there is never a new value derived during apply, then it should not be computed. `DiffSuppressFunc` may also help in some cases, but the correct value still needs to be returned from Apply or it may result in incorrect configuration applied to resources that reference the field.

**Comment by afedorch** [comment] 2019-06-18 00:41
We see the same behavior for different resources and for different providers (please take a look at the linked issue). If the implementation for setting an empty map is wrong on providers side (since v0.12) it could be great to check guidelines on how we need to set it for v0.12. Thanks!

Agree. What about the reported user's scenario (please take a look at the linked issue) - it is unexpected diff for the `null` in state file and no `freeform_tags` in the configuration?

Sorry, still unclear to me. Let's take as example 2 users' configurations before v12 for the same resource without `Optional` `Computed` TypeMap attribute: one configuration contains TypeMap attribute the other does not. There is no diff for both users for v0.11 for any service response and any entry in state file (`nil`/`null` and/or `empty map`). Switching to v0.12 at least 1 user will have unexpected diff depending on the value in the state file from service response (`nil` or `empty map`), correct? the only way to avoid the diff for the user is `DiffSuppressFunc`. Do we have any options here for any provider implementation? Thanks!

**Comment by jbardin** [comment] 2019-06-18 01:49
Thanks @afedorch, I'm going to see if I can reproduce more permutations of the linked issue with a map in case I've missed something. In general, if something is `Computed` it needs to be set to a value at some point. If it's `Optional` and `Computed`, it can be set by the configuration of course, and it doesn't need to "reset" in the resource. The behavior here unfortunately is still unclear, because the legacy SDK is internally inconsistent in how it handles some of these things, and often makes no distinction between unset and empty containers.

Seeing how I'm not readily able to replicate the issue, can you verify what version of the SDK you built the provider with? When troubleshooting and issue, using `master` would be best, as there are fixes not yet in a tagged release. The linked terraform issue is similar but not related, and has a pending PR which should remedy it in most cases.

If I understand the example correctly, if the resource is both `Computed` and `Optional`, and only one has an empty map in the config, neither should show a diff if the state contains an empty map.

**Comment by afedorch** [comment] 2019-06-18 18:17
@jbardin oci provider is built with v0.12.0-rc1 vendoring. Switching to the `github.com/hashicorp/terraform v0.12.2` will fix the problem. The state file after the import will contain an empty map and it will be no diff for the configuration without `freeform_tags` after the `import`. We will need to run more tests for the v0.12.2 sdk, could you confirm that it was a fix for this scenario (or is it a side effect)? Thanks!

**Comment by jbardin** [comment] 2019-06-18 23:36
Ah yes, that would explain it. RC1 was very old, and there have been a lot of detailed changes in the SDK shims since then, and that is one of many fixes. Let me know if you have any other questions as you update the provider.

Thanks!

**Closed by jbardin** 2019-06-18 23:36 UTC
Labels: provider-sdk
