### ISSUE TITLE
Always use count index in resource key

### ISSUE THREAD

**Issue by scottrobertson** [hashicorp/terraform#707] opened 2014-12-23 14:57 UTC
Hey,

When storing resources in terraform.tfstate, is there a way of always storing the count in the resource key, even if the count is 1? The reason being is that when you come to increase the count to 2, it deletes all servers. 

With:
```
resource "digitalocean_droplet" "app" {
  count = "1"
  image = "ubuntu-14-04-x64"
  name = "app${count.index}.example.com"
  region = "lon1"
  size = "4gb"
  ssh_keys = ["123"]
}
```

So the resources would be:
```
"resources": {
    "digitalocean_droplet.app.0": {
    }
}
```
Instead of:
```
"resources": {
    "digitalocean_droplet.app": {
    }
}
```

**Comment by mitchellh** [comment] 2015-02-17 18:50
I can't reproduce this. It replaces `digitaloean_droplet.app` with the `.0` variant but it doesn't replace the _physical_ server, only the state. This is working as intended. Or, are you seeing it replace the physical server? I've tried to repro that and I can't, and we also have test cases in place to protect against that.

Closing since I think this is fine. But please prove me wrong!

**Closed by mitchellh** 2015-02-17 18:50 UTC
Labels: waiting-response
