### ISSUE TITLE
Inconsistent local_file vs S3 object behavior

### ISSUE THREAD

**Issue by aryni01** [hashicorp/terraform#27965] opened 2021-03-03 13:32 UTC
tfvar content:
vals = [
  { name = "a" },
  { name = "b" },
  { name = "c" }
]

main.tf content:
variable "vals" {
  type = any
}
provider local {
    version = "~> 1.4"
}
provider template {
    version = "~> 2.1"
}
terraform {
  backend "s3" {
      bucket = "my-test-bucket"
      key    = "terraform/test/test.tfstate"
      region = "us-west-2"
  }
}
data "template_file" "file_names" {
  count    = length(var.vals)
  template = file("./file.tmpl")
  vars = {
    filename = var.vals[count.index]["name"]
  }
}
resource "aws_s3_bucket_object" "allfiles" {
  count = length(data.template_file.file_names.*)
  bucket  = "my-test-bucket"
  key     = format("test/resources/file-%s.txt", var.vals[count.index]["name"])
  content = data.template_file.file_names[count.index].rendered
}

The problem is when I try to remove one of the key/value in the list to make my tfvar file look like following:
vals = [
  { name = "a" },
  { name = "b" }
]

Instead of destroying the third file, it complains (even in plan):
Error: Invalid index

  on main.tf line 33, in resource "aws_s3_bucket_object" "localconfigs":
  33:   key     = format("test/resources/file-%s.txt", var.vals[count.index]["name"])
    |----------------
    | count.index is 2
    | var.vals is tuple with 2 elements

Now if i change the resource as local_file like following:

resource "local_file" "allfiles" {
  count       = length(data.template_file.file_names.*)
  filename    = format("test/resources/file-%s.txt", var.vals[count.index]["name"])
  content     = data.template_file.file_names[count.index].rendered
}

I can add/remove any number of files it just deletes the local file when I remove one or more key/value pair.

Expected behavior: Whether it is local or remote object, I should be able to add/remove resources based on my tfvar

**Comment by aryni01** [comment] 2021-03-03 13:33
forgot to add the file.tmpl file content which is simply as follows:
filename = ${filename}

**Comment by alisdair** [comment] 2021-03-03 13:50
Hello! This doesn't look like a bug in Terraform, but rather a problem with combining `count` across multiple resources. I recommend looking into [the `templatefile`](https://www.terraform.io/docs/language/functions/templatefile.html) function as a replacement for the `template_file` data source.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by alisdair** 2021-03-03 13:50 UTC

**Comment by aryni01** [comment] 2021-03-03 16:33
very nice, why would the inconsistency not be a bug or issue? why two different resources would behave differently, local_file vs aws_s3_bucket_object ??

**Comment by alisdair** [comment] 2021-03-03 16:43
Because `local_file`'s provider schema does not have any `computed` attributes, it can be fully known at plan time. This is not true for `aws_s3_bucket_object`. This is not a bug in Terraform but expected behaviour.

Again, I recommend posting in the community forum for help with the problem you're trying to solve.
