### ISSUE TITLE
TERRAFORM CRASH while doing init 

### ISSUE THREAD

**Issue by PrasenjitChowdhury** [hashicorp/terraform#26193] opened 2020-09-10 02:37 UTC
Command I run : terraform init -backend-config="bucket=storefront-terraform-state" -backend-config="test-v0/terraform.tfstate" 

### Terraform Version

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0

```
...
```
2020/09/10 08:05:47 [INFO] Terraform version: 0.13.0  
2020/09/10 08:05:47 [INFO] Go runtime version: go1.14.2
2020/09/10 08:05:47 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init", "-backend-config=bucket=storefront-terraform-state", "-backend-config=test-v0/terraform.tfstate"}
2020/09/10 08:05:47 [DEBUG] Attempting to open CLI config file: /home/prchowdh/.terraformrc
2020/09/10 08:05:47 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/09/10 08:05:47 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/09/10 08:05:47 [DEBUG] ignoring non-existing provider search directory /home/prchowdh/.terraform.d/plugins
2020/09/10 08:05:47 [DEBUG] ignoring non-existing provider search directory /home/prchowdh/.local/share/terraform/plugins
2020/09/10 08:05:47 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2020/09/10 08:05:47 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2020/09/10 08:05:47 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2020/09/10 08:05:47 [INFO] CLI command args: []string{"init", "-backend-config=bucket=storefront-terraform-state", "-backend-config=test-v0/terraform.tfstate"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1ffcab5]

goroutine 1 [running]:
github.com/hashicorp/terraform/command.(*InitCommand).backendConfigOverrideBody(0xc000317500, 0x26d82cb, 0xf, 0xc00046c200, 0xc000309f80, 0xc0006b6ba0, 0x29, 0x0, 0x203000, 0x17762fa700000018)
	/home/circleci/project/project/command/init.go:862 +0x8b5
github.com/hashicorp/terraform/command.(*InitCommand).initBackend(0xc000317500, 0xc0000f21b0, 0x26d82cb, 0xf, 0xc00046c200, 0x1, 0xc0006b0000, 0x1c, 0x1c, 0xc0000b99c0, ...)
	/home/circleci/project/project/command/init.go:374 +0x4a6
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000317500, 0xc00004c0e0, 0x2, 0x2, 0xc0004780d0)
	/home/circleci/project/project/command/init.go:227 +0xeb1
github.com/mitchellh/cli.(*CLI).Run(0xc00047e280, 0xc00047e280, 0xc00063fd48, 0x1)
	/home/circleci/project/project/vendor/github.com/mitchellh/cli/cli.go:255 +0x1da
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:275 +0xc90
main.realMain(0x0)
	/home/circleci/project/project/main.go:106 +0xde
main.main()
	/home/circleci/project/project/main.go:42 +0x3a

**Comment by pselle** [comment] 2020-09-11 19:48
Hi @PrasenjitChowdhury,

to better understand the issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - a simplified configuration to replicate this issue
 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by pselle** [comment] 2021-02-12 20:38
Hello, because this has been waiting for reproduction and does not yet have one after some time, I'm going to close this.

**Closed by pselle** 2021-02-12 20:38 UTC
Labels: bug, waiting for reproduction, waiting-response
