### ISSUE TITLE
refresh does not destroy local resources it doesn't find

### ISSUE THREAD

**Issue by ajcrites** [hashicorp/terraform#5578] opened 2016-03-11 05:38 UTC
I think I have noticed this with `terraform refresh` in a variety of ways, but one specific occurrence happens if you delete an SQS queue through the console and then `terraform refresh`. You will get an error like:

    Error refreshing state: 1 error(s) occurred:

    * aws_sqs_queue.queue: AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.

I would expect `refresh` to mark this queue as deleted rather than fail because it cannot find the queue. There may be reasons why `refresh` acts the way it does, but in that case there could be a `-force` flag or the like to delete services locally that are known to have been destroyed in the infrastructure itself.

Seemingly `taint` does this, but it also seems like you would have to know the missing service ahead of time and explicitly `taint` each individual service that is found to be missing before refreshing/applying. It would be nice if there were an easier way to destroy local resources.

**Comment by jen20** [comment] 2016-03-11 13:43
Hi! This is a bug in Terraform which we will need to fix - Refresh is supposed to behave as you describe. Thanks for reporting this!

**Comment by vaibhavjain882** [comment] 2016-03-22 05:49
Any resolution yet ?

**Comment by lowesoftware** [comment] 2016-04-13 13:18
This is blocking a use case for me right now. Would be happy to submit a PR if you can point me toward the root cause of this bug.

**Comment by stack72** [comment] 2016-04-27 17:55
A PR has been opened to fix this (#6381) - it will be part of the 0.6.16 release

**Closed** 2016-04-27 19:07 UTC
Labels: bug, provider/aws
