### ISSUE TITLE
HEREDOC no closing marker found

### ISSUE THREAD

**Issue by isilvera-fyrrr** [hashicorp/terraform#31450] opened 2022-07-15 20:31 UTC
Hello!

I have discovered an issue when using HEREDOC variable and it is at the end of the file. If you create a variable like this:

```
my_variable = <<EOF
this 
is my
multiline
var
EOF
```
And EOF is the last line of the file, It gives me the following error:

│ No closing marker was found for the string.

If I add a new line at the end it works correctly. It' s a little bit tricky to figure out this kind of things.

-->

### Terraform Version
```
Terraform v1.2.4
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.2.5. You can update by downloading from https://www.terraform.io/downloads.html

```

### Expected Behavior
Terraform plan should work

### Actual Behavior
╷
│ Error: Unterminated template string
│ 
│   on var_files/test.tfvars line 87:
│   84: this is
│   85: my multiline
│   86: variable
│   87: EOT
│ 
│ No closing marker was found for the string.
### Steps to Reproduce

1. Create a new terraform project
2. Create a new variable using HEREDOC format and be sure that closing marker is the last line of the file.
3. Run a plan

**Comment by jbardin** [comment] 2022-07-18 13:49
Hi @isilvera-fyrrr,

Thanks for filing the issue. The specification for heredoc syntax (linked from [Configuration Syntax](https://www.terraform.io/language/syntax/configuration#configuration-syntax) shown [here](https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#template-expressions)) specifies that the heredoc identifier be followed by a newline character,

Since it is customary to end file with a newline character (most editors insert this automatically), this is not something which regularly comes up.

Since Terraform is working as intended here I'm going to close this out. If you have more questions, feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) for additional assistance.

Thanks!

**Closed by jbardin** 2022-07-18 13:49 UTC
Labels: bug, new
