### ISSUE TITLE
Crash Running Apply

### ISSUE THREAD

**Issue by arlaneenalra** [hashicorp/terraform#26346] opened 2020-09-23 00:44 UTC
### Terraform Version
```
Terraform v0.13.3
+ provider registry.terraform.io/digitalocean/digitalocean v1.22.2
+ provider registry.terraform.io/hashicorp/helm v1.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.1
+ provider registry.terraform.io/hashicorp/local v1.4.0
```

### Terraform Configuration Files

https://drive.google.com/drive/folders/18c1Z3ItIWRKvNaub0oV9ABlcPAOknrbO?usp=sharing

### Debug Output
-- Not sure I can actually get this ...

### Crash Output
Full crash.log in the linked encrypted zip with the rest of the configuration files.

Console output:
```
...
module.dns[4].digitalocean_record.records[1]: Creation complete after 0s [id=114347788]
module.dns[3].digitalocean_record.records[2]: Modifications complete after 0s [id=113901424]
module.dns[1].digitalocean_record.records[2]: Modifications complete after 0s [id=113901430]
module.dns[3].digitalocean_record.records[0]: Modifications complete after 0s [id=113901425]
module.dns[9].digitalocean_record.records[2]: Modifications complete after 1s [id=113901991]
module.dns[7].digitalocean_record.records[0]: Modifications complete after 1s [id=113901546]
module.dns[1].digitalocean_record.records[0]: Modifications complete after 2s [id=113901427]
module.dns[0].digitalocean_record.records[1]: Creation complete after 1s [id=114347795]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x16d08a3]

goroutine 1674 [running]:
github.com/hashicorp/terraform/plans.(*ResourceInstanceChange).Simplify(0x0, 0xc000960001, 0xc000138030)
	github.com/hashicorp/terraform/plans/changes.go:215 +0x33
github.com/hashicorp/terraform/terraform.(*EvalReduceDiff).Eval(0xc0013be5a0, 0x39340e0, 0xc0014ff860, 0x1, 0x1, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval_diff.go:741 +0x46
github.com/hashicorp/terraform/terraform.EvalRaw(0x3889960, 0xc0013be5a0, 0x39340e0, 0xc0014ff860, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc001d56760, 0x39340e0, 0xc0014ff860, 0x1, 0x1, 0x325e220, 0xc000e20680)
	github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x3889a00, 0xc001d56760, 0x39340e0, 0xc0014ff860, 0x25, 0x0, 0x0, 0x25)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc000f45d10, 0x39340e0, 0xc0014ff860, 0x1, 0x1, 0xc001177c01, 0x100000000000000)
	github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x38898e0, 0xc000f45d10, 0x39340e0, 0xc0014ff860, 0x2ebc180, 0x4ba9741, 0x2e1bda0, 0xc001894970)
	github.com/hashicorp/terraform/terraform/eval.go:49 +0xc7
github.com/hashicorp/terraform/terraform.Eval(0x38898e0, 0xc000f45d10, 0x39340e0, 0xc0014ff860, 0xc000f45d10, 0x38898e0, 0xc000f45d10, 0x0)
	github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x325b700, 0xc0005da2a0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/graph.go:73 +0xc77
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000250ea0, 0x325b700, 0xc0005da2a0, 0xc00137b500)
	github.com/hashicorp/terraform/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	github.com/hashicorp/terraform/dag/walk.go:309 +0x11d7



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

### Expected Behavior
Running Terraform apply does not crash ...

### Actual Behavior
Crash along with corrupted state ...

### Steps to Reproduce
I ran `terraform apply` to update an existing state.

**Comment by arlaneenalra** [comment] 2020-09-23 00:50
There are probably issues in those config files, I was in the middle developing the configs...

**Comment by apparentlymart** [comment] 2020-09-24 23:22
Thanks for reporting this, @arlaneenalra! 

I've not had a chance to try for a reproduction yet, but I just wanted to note for future readers that this error seems to suggest that somehow there is a `nil` change in the plan:

https://github.com/hashicorp/terraform/blob/404e3e3e8103583c83fdc805526e39f4eb5b0ae8/plans/changes.go#L213-L215

The `rc.Action` reference here seems to be what is panicking, suggesting that `Simplify` is being called on a `nil` `ResourceInstanceChange`.

Unfortunately the errant value comes from upstream somewhere, so we'll need to do some more digging to understand where it originates -- the previous operations on whatever instance is causing this are not included in the stack trace.

If you _are_ able to share the output of running this with `TF_LOG=trace` I expect that would make the first pass of debugging far easier, because it would hopefully narrow down which of the resource instances the problem relates to and what operations Terraform had already performed against it. Unfortunately I think without either that or a simpler reproduction case it will be hard to replicate the exact circumstances that caused this. :confounded:

**Comment by arlaneenalra** [comment] 2020-09-25 00:29
Yeah, I was afraid you were going to say something like that. Unfortunately, I haven't been able to get the issue to reproduce myself.  I saw it the once and that was it .. If you need to close this out go ahead.

**Comment by mildwonkey** [comment] 2021-03-23 17:27
I will close this, but if you do end up finding a reproduction please open a new issue, and thanks!

**Closed by mildwonkey** 2021-03-23 17:27 UTC
Labels: bug, new, waiting-response
