### ISSUE TITLE
Add function to convert pem private/public keys to jwks

### ISSUE THREAD

**Issue by iwarapter** [hashicorp/terraform#30419] opened 2022-01-26 19:48 UTC
### Current Terraform Version

```
Terraform v1.1.2
on darwin_amd64
```

### Use-cases

Several OAuth2/OpenID Connect integrations make use of JWKS to represent public keys (RFC7517) and several providers can provide keys in PEM encoded format (`aws_kms_key` for example).

### Proposal

Additional hash/crypto function to provide parsing of PEM encoded RSA/EC keys and generate a JWKS representation.

e.g 
```hcl
data "aws_kms_public_key" "example" {
  key_id = "alias/my-key"
}

output "example" {
  value = keyToJwks(data.aws_kms_public_key.example.public_key)
}
```

**Comment by apparentlymart** [comment] 2022-01-28 01:40
Hi @iwarapter! Thanks for sharing this use-case.

Within Terraform itself our convention is that PEM is the canonical form to pass key material between resources, and so provider developers should design the provider API to accept PEM and convert to other formats automatically as necessary, which therefore avoids the need to complicate Terraform configuration with explicit conversions. This is a similar philosophy as the convention that all providers should represent timestamps in RFC 3339 syntax regardless of what the underlying API uses.

However, you showed the call to your hypothetical function as part of an `output` block, and so I'm inferring that your goal is to export a JWKS-formatted key for consumption by some downstream system which is consuming the output values, and which doesn't share the Terraform ecosystem's preference for PEM.

Now that we have an open ecosystem of providers we're being considerably more selective about what functionality we include into the core Terraform language than we were in the area prior to Terraform v0.13, which is where all of the _current_ functions that might be considered "specialized" originate. We're preserving what's already there for backward-compatibility, but not intending to add more.

As things currently stand, achieving this result with a provider would mean implementing a data source which you could then use with a `data` block just like the `data "aws_kms_public_key"` block in your example.

We do understand that using the subjectively-heavy resource block syntax just for a pure function call is non-ideal, and I see you earlier opened #25940 to represent the possibility of providers defining functions. We have an older issue #2771 which is the main one we're using to represent that use-case, and so once I've finished writing here I'm going to close yours as a duplicate of that one. (sorry we missed it being a duplicate the first time!)

However, if you need a solution today then I would suggest implementing a data source for now. Once we do have a viable technical design and implementation for #2771 you'd be able to adapt what you implemented to also be available as a function in your provider, but aside from a different syntax provider-based functions won't be able to do anything that a data source cannot.

Because we are not intending to add any further special-purpose functions to the main Terraform language (we will now focus only on general-purpose functions that are applicable across many domains), I'm going to close this issue. If you're interested in provider-based functions then I suggest following #2771 for any updates, but I want to be up front that nobody on our team is currently actively working on that and it'll need at least one more technical design iteration before we'd be able to start implementing it, and so data sources are the best answer for the moment.

Thanks again!

**Closed by apparentlymart** 2022-01-28 01:40 UTC
Labels: enhancement, new
