### ISSUE TITLE
Crash when targeting a module instance with variables in module block

### ISSUE THREAD

**Issue by socratesx** [hashicorp/terraform#25437] opened 2020-06-30 15:28 UTC
### Terraform Version

```
$ terraform2 version
Terraform v0.13.0-beta2
+ provider registry.terraform.io/hashicorp/aws v2.68.0

```

### Terraform Configuration Files

main.tf
```hcl
variable "lambda_role"{
  type = string
  default = "role"
}

provider "aws" {
  profile = "dev"
  region  = "eu-central-1"

  assume_role {
    role_arn     = "Role"
  }
}

module "lambda1" {
  source = "./modules/lambda_module"

  lambda_function_config = {
    name = "lambda1"
    role = var.lambda_role
    runtime = "python3.7"
    alias_name = "dev"
  }
}

module "lambda2" {
  source = "./modules/lambda_module"

  lambda_function_config = {
    name = "lambda3"
    role = var.lambda_role
    runtime = "python3.7"
    alias_name = "dev"
  }
}
```

modules/lambda_module/main.tf
```hcl
variable lambda_function_config {
  type = map
  description = "Configuration for lambda function"
  default = {}
}

resource "aws_lambda_function" "function" {
  filename          = "files/${var.lambda_function_config.name}.zip"
  function_name     = var.lambda_function_config.name
  role                 = var.lambda_function_config.role
  handler           = "${var.lambda_function_config.name}.lambda_handler"
  runtime           = var.lambda_function_config.runtime
}

resource "aws_lambda_alias" "alias" {
  name             = var.lambda_function_config.alias_name
  description      = "${var.lambda_function_config.alias_name} alias"
  function_name    = aws_lambda_function.function.arn
  function_version = "$LATEST"
}
```

dummy files representing lambda zip packages: `files/lambda1.zip` & `files/lambda2.zip`

### Debug Output

Debug output here:
https://gist.github.com/socratesx/8c5eee4833259f600610108035b80960

### Crash Output

Crash log here:
https://gist.github.com/socratesx/a40ed10841e792bc1ac423c04bc71435

### Expected Behavior

Terraform should have showed only the targeted module lambda_function and alias as below. The output is when I hard-coded the role argument in module blocks.
```bash
$ terraform2 plan -target=module.lambda1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.lambda1.aws_lambda_alias.alias will be created
  + resource "aws_lambda_alias" "alias" {
      + arn              = (known after apply)
      + description      = "dev alias"
      + function_name    = (known after apply)
      + function_version = "$LATEST"
      + id               = (known after apply)
      + invoke_arn       = (known after apply)
      + name             = "dev"
    }

  # module.lambda1.aws_lambda_function.function will be created
  + resource "aws_lambda_function" "function" {
      + arn                            = (known after apply)
      + filename                       = "files/lambda1.zip"
      + function_name                  = "lambda1"
      + handler                        = "lambda1.lambda_handler"
      + id                             = (known after apply)
      + invoke_arn                     = (known after apply)
      + last_modified                  = (known after apply)
      + memory_size                    = 128
      + publish                        = false
      + qualified_arn                  = (known after apply)
      + reserved_concurrent_executions = -1
      + role                           = "role"
      + runtime                        = "python3.7"
      + source_code_hash               = (known after apply)
      + source_code_size               = (known after apply)
      + timeout                        = 3
      + version                        = (known after apply)

      + tracing_config {
          + mode = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Warning: Resource targeting is in effect

You are creating a plan with the -target option, which means that the result
of this plan may not represent all of the changes requested by the current
configuration.
                
The -target option is not for routine use, and is provided only for
exceptional situations such as recovering from errors or mistakes, or when
Terraform specifically suggests to use it as part of an error message.


------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Actual Behavior

Terraform crashes when trying to target one instance of the module definitions. If no targeting is used the command runs normally without error. Running the configuration as it is:
```bash
$ terraform2 plan -target=module.lambda1
panic: no expansion has been registered for module.lambda2

goroutine 72 [running]:
github.com/hashicorp/terraform/instances.(*expanderModule).moduleInstances(0xc00058ecc0, 0xc00046a720, 0x1, 0x1, 0xc000760b50, 0x0, 0x4, 0x4f3078, 0x0, 0x1a)
        /home/circleci/project/project/instances/expander.go:267 +0xb72
github.com/hashicorp/terraform/instances.(*Expander).ExpandModule(0xc00058ece0, 0xc00046a720, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/circleci/project/project/instances/expander.go:116 +0x108
github.com/hashicorp/terraform/terraform.(*nodeExpandModuleVariable).DynamicExpand(0xc000589b00, 0x2d16820, 0xc00120cf70, 0x1, 0x1, 0x1)
        /home/circleci/project/project/terraform/node_module_variable.go:42 +0x94
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2518480, 0xc000589b00, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:84 +0x4d8
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000093e60, 0x2518480, 0xc000589b00, 0xc000518d40)
        /home/circleci/project/project/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x11d7



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce

1. `terraform init`
2. `terraform2 plan -target=module.lambda1`

**Comment by apparentlymart** [comment] 2020-06-30 19:17
Thanks for reporting this, @socratesx!

This seems similar to #25114, which has been fixed in the main branch ready to be included in the next beta, but I've not yet confirmed that they both have the same root cause. 0.13.0-beta3 is expected this week so once that's released we can try this again and see if the problem still occurs.

Thanks again!

**Comment by alisdair** [comment] 2020-06-30 19:25
I was able to reproduce this with 0.13.0-beta2, and it seems to be fixed with a 0.13.0 build.

**Comment by alisdair** [comment] 2020-07-01 19:11
[Terraform 0.13.0-beta3 was released today](https://releases.hashicorp.com/terraform/0.13.0-beta3/), and it should fix this issue, so I'm closing it. If you are able to confirm that the issue is resolved on your end, that would be helpful. Thanks!

**Closed by alisdair** 2020-07-01 19:11 UTC
Labels: bug, config, crash, reproduced, v0.13

**Comment by socratesx** [comment] 2020-07-01 21:06
I confirm that the issue is resolved with beta-3. Thank you!
