### ISSUE TITLE
terraform workspace select is getting "Backend reinitialization required. Please run "terraform init"." error

### ISSUE THREAD

**Issue by batmanhit** [hashicorp/terraform#18237] opened 2018-06-12 14:40 UTC
### Terraform Version
```
0.11.7
```

### Terraform Configuration Files
```
provider "aws" {
  # don't touch below here
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "us-west-2"
}

terraform {
  backend "s3" {
    bucket = "nom-terraform"
    key    = "apps/onboarding/terraform.tfstate"
    region = "us-west-2"
  }
}
...
```

### Debug Output
+ cp terraform/globals/stack.tf cmd/apps/onboarding2/stack.tf
+ cd cmd/apps/onboarding2
+ /usr/local/bin/terraform workspace new test
[0m[0m[1m[33mBackend reinitialization required. Please run "terraform init".[0m
[33mReason: Initial configuration of the requested backend "s3"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.
[0m
[31mFailed to load backend: Initialization required. Please see the error message above.[0m[0m
+ true
+ /usr/local/bin/terraform workspace select test
[0m[0m[1m[33mBackend reinitialization required. Please run "terraform init".[0m
[33mReason: Initial configuration of the requested backend "s3"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.
[0m
[31mFailed to load backend: Initialization required. Please see the error message above.[0m[0m
Build step 'Execute shell' marked build as failure

### Expected Behavior
Should run successfully

### Actual Behavior
terraform init & terraform plan worked fine.
After init & plan, it selects the workspace and it's reporting an error above.

### Additional Context
Terraform is running on Jenkins environment.

### References
https://stackoverflow.com/questions/50819556/terraform-apply-reporting-backend-configuration-error-with-s3-after-terraform-in

**Comment by jbardin** [comment] 2018-06-12 18:42
Hi @batmanhit,

This sounds like a duplicate of #18030. Are you using a directory argument to `init` and `plan`?

**Comment by batmanhit** [comment] 2018-06-12 18:44
I am not using directory argument to init & plan.

**Comment by jbardin** [comment] 2018-06-12 18:56
@batmanhit,

If `init` was run already in the `cmd/apps/onboarding2` directory, then you should not see the message to initialize the backend. Can you provide a complete example, including how you're running `init`?

**Comment by batmanhit** [comment] 2018-06-13 04:41
We have Jenkins job that does 2 things.
1. It checks out the git repo and go to cmd/apps/onboarding2 directory. (it has main.tf file in it)
`terraform init`
`terraform plan`

2. Second job just go to cmd/apps/onboarding2 directory and runs the command below.
`terraform apply`

**Comment by jbardin** [comment] 2018-06-13 12:31
@batmanhit,

That's not showing where exactly you're calling the `workspace` command; is it also failing on `apply`?

If you're getting the message `Backend reinitialization required`, it means the working directory has not been initialized and you must run `init` first. If the stored configuration and plugins are not persisted in the `cmd/apps/onboarding2` directory, then this is the expected error output.

**Comment by batmanhit** [comment] 2018-06-13 12:33
@jbardin 

So what can be the possible reason for that? 
Once the `terraform init` runs, it creates the configurations in `.terraform` file. Correct?

**Comment by jbardin** [comment] 2018-06-13 12:38
Yes, the stored config is in `.terraform/`. The message is indicating that the backend configuration has changed, so if the `.terraform` directory has been left untouched, then another possibility is that the configuration itself has changed between the 2 runs.

**Comment by batmanhit** [comment] 2018-06-13 12:47
![image](https://user-images.githubusercontent.com/30376020/41351767-7613fc02-6f28-11e8-959d-4060a3b3e2df.png)

Actually, I have 2 Jenkins jobs like this ^^ and first, I run `terraform-plan-service` and after that, I run `terraform-apply-service`.
In `terraform-plan-service`, it checkouts the repo from the github and jumps into the terraform directory. After that, it just initiates the terraform module and run `plan` and it works fine.
In `terraform-apply-service`, it checkouts the repo from the github and jumps into the terraform directory. Then, it selects workspace and it reports an error.

The problem is that, it works fine with other modules and folders and for this onboarding2, it was working fine as well.
But it's now reporting an error. That's really weird.

**Comment by batmanhit** [comment] 2018-06-13 18:17
@jbardin Can I try removing the .terraform folder?

**Comment by jbardin** [comment] 2018-06-13 22:39
Yes, you can remove the `.terraform/` directory, but you will still need to call `init` again. If the configuration is not kept in sync with what was present during init, this is probably the most reliable way to handle it. You should also not that when using this method you want to pin providers to a specific version in order to prevent an inadvertent upgrade between plan and apply (though worst case is that the apply fails instructing you to create a new plan).

The stored configuration here is somehow diverging from what was present during `init`. That either needs to be rectified, or `init` needs to be executed every time.

Since things seems to be working as expected, and this isn't a channel for general support, I'm going to close this out. Feel free to reply here if it turns out you have a reproducible case where the same config is requiring backend reinitialization, and we can revisit the issue.

**Closed by jbardin** 2018-06-13 22:39 UTC
Labels: waiting-response
