### ISSUE TITLE
init command should support workspaces block in backend config file

### ISSUE THREAD

**Issue by ToruMakabe** [hashicorp/terraform#25793] opened 2020-08-11 00:42 UTC
### Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

Backend config like official doc
https://www.terraform.io/docs/backends/types/remote.html#using-cli-input

```terraform
workspaces { name = "workspace" }
hostname     = "app.terraform.io"
organization = "company"
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

init backend without error

### Actual Behavior

```
Initializing the backend...

Error: Invalid backend configuration file

The backend configuration file "backend.hcl" given on the command
line must contain key-value pairs only, and not configuration blocks.
```

### Steps to Reproduce

terraform init -backend-config=backend.hcl

### Additional Context

N/A

### References

- #25411

**Comment by raboley** [comment] 2020-08-11 01:50
second. not sure if I am missing updated docs ref, but I started hitting this today as well.

**Comment by yawboateng** [comment] 2020-08-11 23:39
Same, works fine in 0.12.28 as documented but not in 0.13.0

**Comment by alisdair** [comment] 2020-08-13 14:09
I'm able to reproduce this and I think it is indeed a bug. It looks like in #25411 we were overzealous in validating the backend configuration file as purely attributes, when it actually should contain the configuration body for the specified backend. As in the remote backend example, this configuration may include blocks.

We need to remove the attributes-only constraint, but I'm not sure what we can replace it with to help out with the original issue (#24845). Maybe a check that there is no `terraform` block at the top level?

**Comment by ToruMakabe** [comment] 2020-08-14 00:21
@alisdair Thanks. At lease me, I don't put terraform block at the top level in config file.

**Comment by raboley** [comment] 2020-08-15 17:09
Is there a workaround that still lets you use a backend.hcl file, but in a different format?

**Comment by alisdair** [comment] 2020-08-17 15:13
> Is there a workaround that still lets you use a backend.hcl file, but in a different format?

Yes. You can combine the [attributes as blocks alternate syntax](https://www.terraform.io/docs/configuration/attr-as-blocks.html) with HCL as JSON. Instead of this HCL:

```hcl
workspaces { name = "workspace" }
hostname     = "app.terraform.io"
organization = "company"
```

Write this JSON as `backend.hcl.json`:

```json
{
  "workspaces": [
    {
      "name": "workspace"
    }
  ],
  "hostname": "app.terraform.io",
  "organization": "company"
}
```

And run `terraform init -backend-config=backend.hcl.json`.

**Comment by marcincuber** [comment] 2020-08-18 06:44
I can config that JSON syntax is working as fine with terraform 0.13. Is there a plan to add support for previous HCL syntax or is this the final solution going forward?

**Comment by alisdair** [comment] 2020-08-18 14:06
I consider it to be a bug and think it should be fixed. I only suggest the JSON workaround as a temporary way to unblock use of 0.13.0.

**Closed** 2020-08-24 14:14 UTC
Labels: bug, explained
