### ISSUE TITLE
Lots of whitespace since windows color codes are fixed

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#6323] opened 2016-04-25 06:49 UTC
Since color codes in the output have been fixed for windows - not sure if related - after each "Creating..." line in the output 10-20 lines of whitespace are outputted. I'm running the terraform commands from the cygwin bash prompt included in https://chocolatey.org/packages/git.install.
### Terraform Version

Terraform v0.6.15
### Affected Resource(s)

google_compute_instance
template_file.development
### Expected Behavior

At most a single whitespace line should be added.
### Actual Behavior

More than 10 whitespace lines are added between console output log messages.
### Steps to Reproduce
1. change something in your terraform config that forces new items to be created
2. `terraform apply`

**Comment by jen20** [comment] 2016-04-25 15:07
Hi @JorritSalverda! I must admit I had never tested this in Cygwin, and it's quite likely that it was already correctly interpreting the standard ASCII terminal codes. Can you confirm whether this also happens using a normal command prompt (or Powershell) as well?

**Comment by jen20** [comment] 2016-04-25 15:10
As an additional diagnostic step - can you verify whether the same whitepsace occurs if you specify the `-no-color` flag?

**Comment by PetaPetaPeta** [comment] 2016-05-28 20:15
I am experiencing the same issue with cmder(https://github.com/cmderdev/cmder) which is based on ConEmu.
It is not whitespace lines that are being added. By highlighting them I can see the expected text. The issue occurs because the font color of some of the lines are identical with that of the background color. Even if I change the background color the color of the text changes along with it.

**Comment by PetaPetaPeta** [comment] 2016-05-28 20:16
I believe the issue was introduced by this pull request: https://github.com/hashicorp/terraform/pull/5718

**Comment by apparentlymart** [comment] 2017-05-03 00:53
Hi all! Sorry for the long silence here.

I've been trying to reproduce this in various scenarios on Windows but have been unable to. Can someone confirm that this is still occurring on Terraform 0.9? If you're still seeing it, it would help to know what version of Windows you are running... I only have Windows 10 available to test with right now.

**Comment by apparentlymart** [comment] 2017-05-08 22:17
While I was working recently on another Windows-specific Terraform issue I wasn't able to reproduce the problem of text being displayed the same color as the background, at least in the default command prompt with a black background.

I'm going to close this out, since it appears that it got fixed somewhere along the line. Please let me know if anyone is still seeing this issue on recent versions of Terraform (0.9 or above) and is willing to help me try to reproduce this.

**Closed by apparentlymart** 2017-05-08 22:17 UTC
Labels: bug, core, waiting-response, windows
