### ISSUE TITLE
Terraform v1.1.0-alpha20210728 does not unlock statefile within Azure

### ISSUE THREAD

**Issue by cberge908** [hashicorp/terraform#29379] opened 2021-08-16 13:39 UTC
The alpha version of Terraform 1.1.0 is not removing the lease of the state file after successfully executing a command which reads/ writes from/to the state file. This does not happen with the official 1.0.4 release.
### Terraform Version

```
Terraform v1.1.0-alpha20210728
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Terraform state file lease is removed after successful end of last execution
### Actual Behavior

Terraform state file stays in status "leased" after executing an action

![image](https://user-images.githubusercontent.com/42270330/129571642-72b4bb40-c709-4d08-8816-ff05eb2e01eb.png)

Lease needs to be broken manually to execute further commands.

### Steps to Reproduce

1. Execute any terraform action which reads the state file e.g. `terraform add azurerm_mssql_database.test`
2. Execute another terraform action which reads the state file e.g. `terraform add -optional=true azurerm_mssql_database.test`
3. Error is printed that state file is already locked:
```hcl
terraform add -optional=true azurerm_mssql_database.test
╷
│ Error: Error acquiring the state lock
│
│ Error message: state blob is already locked
│ Lock Info:
│   ID:        ***removed***
│   Path:      ***removed***.tfstate
│   Operation: OperationTypeInvalid
│   Who:       ***removed***
│   Version:   1.1.0
│   Created:   2021-08-16 13:19:25.958303 +0000 UTC
│   Info:
│
│
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
╵
```

**Comment by cberge908** [comment] 2021-08-16 14:10
Also happens with v1.1.0-alpha20210811

**Comment by apparentlymart** [comment] 2021-08-18 17:16
Hi @cberge908! Thanks for reporting this.

You mentioned in your writeup here that this works with the v1.0 series, but `terraform add` isn't included in the v1.0 series (it's only been included in the v1.1 alpha releases so far) and so I worry that I'm not understanding fully the problem you are reporting here.

The way you've written up the examples suggests that you've found other commands that also exhibit this problem, but they work correctly in Terraform v1.0. If so, it'd be helpful if you can share an example of that so we can try to reproduce both your success and your error in order to diagnose the problem.

I'm particularly interested to understand what exactly you've seen here (in your testing with v1.0) because I want to understand whether this is a bug in the new `terraform add` command or whether it's the result of a recent change to the Azure backend. In the latter case, we'll need to delegate this to the Azure provider team since they are the ones who maintain that backend, but if it's `terraform add` in particular then that'll be something for the main Terraform team to investigate.

Thanks again!

**Comment by apparentlymart** [comment] 2021-08-18 17:19
For the benefit of others looking at this issue in future: as far as I can tell, the only PR that's landed for the Azure provider since the main branch switched from v1.0 development to v1.1 development was #28181, and so if there _is_ an Azure provider regression here then it might be related to that.

**Comment by cberge908** [comment] 2021-08-19 08:25
Thanks for the reply @apparentlymart - you're right, the `add` command is not part of v1.0
So I would need to rephrase it, so it just happens with `terraform add` from v1.1.0-alpha, not with any other command.
So doing `terraform apply`, `terraform state list` or `terraform destroy` does correctly remove the lease on the state file after successful completion. It feels more likely that this is then bound to the `terraform add` rather than the azurerm provider.

Just let me know in case you need more test cases.

**Comment by apparentlymart** [comment] 2021-08-19 20:33
Thanks! I've relabeled this issue because I agree that based on your information here it seems likely to be a `terraform add` bug rather than a provider bug. Specifically, it appears that `terraform add` isn't always correctly unlocking the state before it exits.

**Closed** 2021-08-20 19:16 UTC
Labels: bug, cli, new, v1.1
