### ISSUE TITLE
0.7rc2 Passing a splat in output from one module to another erroneously claims a Cycle

### ISSUE THREAD

**Issue by wr0ngway** [hashicorp/terraform#7261] opened 2016-06-21 19:43 UTC
### Terraform Version

Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e)
### Affected Resource(s)

terraform core
### Terraform Configuration Files

``` hcl
# main.tf

module "first" {
  source = "mod1"
  input = "foo,bar"
}

module "second" {
  source = "mod2"
  # changing output1 to output2 results in success - so not so much a problem with
  # modules/params/count as it is with using splat with them.
  input = "${module.first.output1}"
}

# The below also works with splat, so not a splat/count issue, but rather a splat/module/count issue
variable "input" {
  default = "foo,bar"
}

resource "null_resource" "run" {
  count = "${length(split(",", var.input))}"

  provisioner "local-exec" {
    command = "echo main: ${element(split(",", var.input), count.index)}"
  }
}

```

``` hcl
# mod1/mod1.tf

variable "input" {
}

resource "null_resource" "run" {
  count = "${length(split(",", var.input))}"

  provisioner "local-exec" {
    command = "echo mod1: ${element(split(",", var.input), count.index)}"
  }
}

output "output1" {
  # null_resource doesn't have any attributes, but for ease in duplicating it should be fine
  # any other resource with real attributes causes the same failure
  value = "${join(",", null_resource.run.*.id)}"
}

output "output2" {
  value = "${join(",", split(",", var.input))}"
}
```

``` hcl
# mod2/mod2.tf
variable "input" {
}

resource "null_resource" "run" {
  count = "${length(split(",", var.input))}"

  provisioner "local-exec" {
    command = "echo mod2: ${element(split(",", var.input), count.index)}"
  }
}
```
### Debug Output

https://gist.github.com/wr0ngway/fb89461bb177c37be0d1625ad242d3ff
### Panic Output

N/A
### Expected Behavior

Should have run the plan without error (or maybe produce a different error)
### Actual Behavior

Reports a Cycle:

```
$ terraform get
Get: file:///Users/mconway/workspace/tf-module-bug/mod1
Get: file:///Users/mconway/workspace/tf-module-bug/mod2

$ terraform plan
Error configuring: 1 error(s) occurred:

* Cycle: module.first.null_resource.run, module.first.output.output1, module.second.var.input, module.second.null_resource.run (destroy), module.first.null_resource.run (destroy)
```
### Steps to Reproduce
1. `terraform get`
2. `terraform plan`
### Important Factoids

N/A
### References
- May be related to GH-6833 - I think my issue was shadowed by this before it was merged
- May be related to GH-7195 - though the error message is different

**Comment by wr0ngway** [comment] 2016-06-21 20:36
Note, I see the same behavior if I use the new list variable types throughout the example (instead of csv/split/join)

**Comment by radeksimko** [comment] 2016-06-30 13:44
@wr0ngway Thanks for the report. Do you agree we can close this as a duplicate of https://github.com/hashicorp/terraform/issues/1497 ?

**Comment by egarbi** [comment] 2016-07-26 12:56
Can be this issue happening to me be related:
https://github.com/egarbi/debugging_terraform

**Comment by nckslvrmn** [comment] 2016-10-07 17:04
+1

**Comment by mitchellh** [comment] 2016-11-22 06:22
This is related to #3888. We'll centralize there.

**Closed by mitchellh** 2016-11-22 06:22 UTC
Labels: bug, core
