### ISSUE TITLE
aws_elasticache_cluster does not allow creation of multi-AZ Redis

### ISSUE THREAD

**Issue by rkulagowski** [hashicorp/terraform#4946] opened 2016-02-01 23:46 UTC
Per the documentation at [https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html](url)

the multi-az option is only available for Memcache. AWS allows for multi-AZ Redis:

[https://aws.amazon.com/blogs/aws/elasticache-redis-multi-az/](url)

**Comment by optimisticanshul** [comment] 2016-02-12 10:19
@rkulagowski with redis it must belong to replication_group we can't add multi-az to redis by setting az-parameter to true

```
:replication_group_id (String) — The ID of the replication group to which this cache cluster should belong. If this parameter is specified, the cache cluster will be added to the specified replication group as a read replica; otherwise, the cache cluster will be a standalone primary that is not part of any replication group.
If the specified replication group is Multi-AZ enabled and the availability zone is not specified, the cache cluster will be created in availability zones that provide the best spread of read replicas across availability zones.

Note: This parameter is only valid if the Engine parameter is redis.
```

**Comment by rkulagowski** [comment] 2016-02-16 20:37
OK, but the replication group that you're discussing still doesn't appear to have any support in aws_elasticache_cluster

Or am I misunderstanding something? Is it possible to create a Redis cluster in multiple AZs yet?

**Comment by optimisticanshul** [comment] 2016-02-18 05:32
Yes it's possible to have multi-az redis. I don't think terraform supports as of now. But i will try to add it on this weekend @rkulagowski

**Comment by Moeser** [comment] 2016-03-25 20:22
I'm running into this same problem.  We're trying to create a fault tolerant redis elasticache cluster through terraform, but replication_group isn't supported.  Terraform supports adding a single node redis cluster, but can you really call it a cluster at that point?

**Comment by guillermo** [comment] 2016-04-06 16:32
:+1:

**Comment by ChloeTigre** [comment] 2016-04-08 14:51
(up)

**Comment by ajlanghorn** [comment] 2016-04-21 09:40
This would be an awesome improvement to Elasticache support in Terraform :)

**Comment by boxrick** [comment] 2016-05-06 13:09
This is a real showstopper and again would be awesome if it could be added!

**Comment by davidfic** [comment] 2016-05-10 03:04
:+1:

**Comment by mbravorus** [comment] 2016-06-08 13:45
really missing multiaz elasticache redis cluster support, adding my voice here

**Comment by simonrondelez** [comment] 2016-06-09 11:56
👍

**Comment by erkolson** [comment] 2016-06-10 13:44
👍 , but backport into 0.6.X 🙏 😄  ?

**Comment by AndrewFarley** [comment] 2016-07-21 08:26
+1 still not possible in terraform

**Comment by mponti** [comment] 2016-07-22 15:16
Could definitely use this!

**Comment by stack72** [comment] 2016-07-27 18:58
Closing this as a duplicate of #4361 

I am going to track the progress on this in that ticket going forward.

**Closed by stack72** 2016-07-27 18:58 UTC
Labels: enhancement, provider/aws

**Comment by agomezvidal** [comment] 2017-02-22 16:15
Hi,

    It is feasible to configure " Multi-AZ enabled read abd write redis cluster"? At this moment looks it is not possible via terraform. Can you provide some feedback?

Thanks in advance

**Comment by mbravorus** [comment] 2017-02-22 16:45
@agomezvidal for 0.8.7, according to https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html it appears that MultiAZ is possible only for memcached clusters so far. So, we are waiting for implementation of the same for Redis.

**Comment by igaskin-gpsw** [comment] 2017-03-17 17:06
@agomezvidal @mbravorus MultiAZ is supported with Redis by using `elasticache-replication-group`.  Support for it was added in https://github.com/hashicorp/terraform/pull/8275.

Check out the docs: https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html

**Comment by jasonkuehl** [comment] 2018-06-05 13:00
@stack72  This ticket is a different issue https://github.com/hashicorp/terraform/issues/4361

Right now if you try to built Redis with Multi-AZ you'll get the following error 

"engine "redis" does not support num_cache_nodes >1 " 

This ticket is now yet resolved.

**Comment by bflad** [comment] 2018-06-06 21:16
@jasonkuehl AWS has some very confusing terminology between the console and API. Terraform implements the API naming as its generally more consistent longterm and translates more easily between the CLI, CloudFormation, and other AWS SDKs.

Its only possible to create a single Redis node with the [`aws_elasticache_cluster` resource](https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html). The naming is unfortunate as "cluster" in the API only refers to singlular Redis nodes but supports multiple Memcached nodes in multi-AZ. The [`aws_elasticache_replication_group` resource](https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html) ("replication group" in the API) is what provides multi-AZ Redis support by enabling multiple Redis "clusters" (again, singular nodes) to talk to each other.

**Comment by jasonkuehl** [comment] 2018-06-07 12:19
@bflad AH ok. Im going to test this out right away. Thanks for the reply!

Jason.

**Comment by rsingh-atlassian** [comment] 2019-08-14 09:09
@bflad - did we have multi-az enabled for elastic cache Redis in terraform yet
