### ISSUE TITLE
Plan with outputs no longer displays "No changes"

### ISSUE THREAD

**Issue by stephenwolfe1** [hashicorp/terraform#32824] opened 2023-03-10 21:32 UTC
### Terraform Version

```shell
Terraform v1.4.0
on darwin_arm64
```

### Terraform Configuration Files

```terraform
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}

output "test" {
  value = "foo"
}
```

### Debug Output

https://gist.github.com/stephenwolfe1/f5fcdee80d3a935767e0f2bead74d1a5

### Expected Behavior

If there are no changes and outputs under `planned_vaules` then the cli should still print:

"No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed."

### Actual Behavior

terraform plan prints no output (with default logging) when there infrastructure matches state but there are outputs

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan`

(repeat without outputs in the configuration)

### Additional Context

The example here has been recreated without any of our wrapper or custom environment configuration

**Comment by jbardin** [comment] 2023-03-10 21:34
Duplicate of https://github.com/hashicorp/terraform/issues/32815

**Closed by jbardin** 2023-03-10 21:34 UTC
Labels: bug, new
