### ISSUE TITLE
Failures to download providers from registry

### ISSUE THREAD

**Issue by jrusz** [hashicorp/terraform#29035] opened 2021-06-25 09:56 UTC
Hi, ever since yesterday we're seeing failures to get aws provider in our CI. I've also noticed failure to get azurerm or openstack provider, but we don't try to get them as often so aws is the most prominent. I apologize for not providing many details, just trying to figure out if there's some issue with the registry...

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

```
Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.27"...
- Installing hashicorp/aws v3.47.0...
- Installed hashicorp/aws v3.47.0 (self-signed, key ID 34365D9472D7468F)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Terraform has been successfully initialized!
```

### Actual Behavior

```
Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.27"...
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/aws:
could not connect to registry.terraform.io: Failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json": dial
tcp 199.232.94.49:443: i/o timeout
Error: Could not load plugin
```
or
```
Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.27"...
- Installing hashicorp/aws v3.47.0...
Error: Failed to install provider
Error while installing hashicorp/aws v3.47.0: Get
"https://releases.hashicorp.com/terraform-provider-aws/3.47.0/terraform-provider-aws_3.47.0_linux_amd64.zip":
dial tcp 199.232.93.183:443: i/o timeout
Error: Could not load plugin
```

**Comment by jbardin** [comment] 2021-06-25 17:46
Hi @jrusz,

Thanks for filing the issue. Being an "i/o timeout", this is probably caused by something outside of terraform itself. Since it appears you have already contacted the registry team to verify issue on the remote side, I'm going to close this out for now. If something arises indicating that the cli itself is part of the problem, please feel free to reply here with more infofmation.

Thanks!

**Closed by jbardin** 2021-06-25 17:46 UTC
Labels: bug, new
