### ISSUE TITLE
Dependency Cycle Issue on Destroy when Using Remote-State as an input to a module 

### ISSUE THREAD

**Issue by bordersquirrel** [hashicorp/terraform#9181] opened 2016-10-03 12:42 UTC
Hi,

I'm a relative novice with Terraform and I'm just starting to refactor some code I wrote to use Modules. Specifically I'm attempting to use a simple module to build EC2 instances.

I'm using terraform v0.7.4 on Ubuntu 16.04.

I have split my plan into two sections;

- create_environment - this builds the VPC/Subnets/SGs and whatnot and saves the details in a remote-state file on AWS (all working fine)
- create-infrastructure - creates the instances (not so much)

My 'terraform plan' and 'terraform apply' in the create_infrastructue plan work fine, pulling in the region, subnet_id and security_groups from the remote-state like so;

```
module "admin_instance" {
    source = "./Modules/Create_Instance"

    aws_region = "${data.terraform_remote_state.environment.region}"
    instance_name = "admin_node"
    instance_count = "1"
    instance_os = "ubuntu16.04"
    instance_type = "t2.micro"
    subnet_id = "${data.terraform_remote_state.environment.public_subnet_id}"
    security_groups = ["${data.terraform_remote_state.environment.default_sg_id}", "${data.terraform_remote_state.environment.out_sg_id}", "${data.terraform_remote_state.environment.admin_sg_id}"]
    key_name = "${aws_key_pair.deployer.key_name}"

    amis = "${var.amis}"

    client = "${var.client}"
    project = "${var.project}"
    environment = "${var.environment}"
    owner = "${var.owner}"
}

```
The module looks like this;

```
variable "aws_region" {}
variable "instance_name" {}
variable "instance_count" {}
variable "instance_os" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "security_groups" {
    type = "list"
}
variable "key_name" {}
variable "amis" {
    type = "map"
}
variable "client" {}
variable "project" {}
variable "environment" {}
variable "owner" {}

resource "aws_instance" "auto_generated_instance" {
    count = "${var.instance_count}"
    ami = "${lookup(var.amis, "${var.aws_region}-${var.instance_type}-${var.instance_os}")}"
    instance_type = "${var.instance_type}"
    subnet_id = "${var.subnet_id}"
    vpc_security_group_ids = ["${var.security_groups}"]
    key_name = "${var.key_name}"
    source_dest_check = false
    tags {
        Name = "${var.client}_${var.project}_${var.environment}_${var.instance_name}${count.index}"
        Client = "${var.client}"
        Project = "${var.project}"
        Environment = "${var.environment}"
        Owner = "${var.owner}"
        Terraform = "True"
    }
}
```

I'm using the Create_Instance module twice in the plan; once for an "admin" node (x1) and once for some "cluster" nodes (x6). All seems pretty straightforward, but when I come to destroy these resources I am seeing a circular dependency which looks to be a dependency on the destroy node for the remote-state.

![image](https://cloud.githubusercontent.com/assets/8168910/19037404/fc3aa79c-896d-11e6-9b5c-1186c10943c3.png)

I could very easily be missing something here. Obviously both the "admin" and "cluster" nodes use the same Resource Name "auto_generated_instance" from the module definition but as I understand it those are in separate namespaces so should not conflict.

Been banging my head off this for a few days now so any help would be greatly appreciated.

Cheers

Dave

**Comment by bordersquirrel** [comment] 2016-10-04 07:41
I've removed the dependency on remote_state by hard-coding the variables pulled from it (region, subnet id and security groups) and this has resolved the issue. The new dependency graph looks like this;

![image](https://cloud.githubusercontent.com/assets/8168910/19065882/1e970c72-8a0e-11e6-957d-5af40d82b0b7.png)

At this point I'm fairly sure this has to be a bug when generating the dependency graph.

Cheers

Dave

**Comment by jbardin** [comment] 2016-10-06 16:14
@bordersquirrel, 

Thanks for the information! I'll mark this as a bug, and we'll look into as soon as we can.

**Comment by bacoboy** [comment] 2016-10-07 18:37
Maybe a dupe of #8461 ?

Still waiting on that fix for some time....

**Comment by bordersquirrel** [comment] 2016-10-13 11:10
@bacoboy it could be the same issue, although in my case I am not using any of the lifecycle statements, which is a slight difference. My suspicion is that this is related to using a single 'data' source to supply input variables to multiple modules. I'll try to work up a more generic failure case if I get chance.

**Comment by jbardin** [comment] 2016-10-13 21:10
Yes, I'm fairly certain that this is a dupe of 8461. I'll close it as such, since that issue has more context. 

Due to how the graph is generated, the underlying issue is quite difficult to fix. We're in the process of implementing what's need to address it.

**Closed by jbardin** 2016-10-13 21:10 UTC
Labels: bug, core
