### ISSUE TITLE
terraform output adds double-quotes on stdout

### ISSUE THREAD

**Issue by Overbryd** [hashicorp/terraform#27332] opened 2020-12-18 11:00 UTC
### Terraform Version

```
$ terraform -v
Terraform v0.14.2
```

### Terraform Configuration Files

```terraform
output foo {
  value = "Here is my output"
}
```

### Debug Output

```console
$ terraform output foo
"Here is my output"
```

### Crash Output

No crash output.

### Expected Behavior

* Terraform should not quote or modify output that is given to stdout

```console
$ terraform output foo
Here is my output
```

That should be default behaviour, as there is already a `-json` option to terraform output that would allow for more advanced use cases, or encodings for complex multi-line outputs that need further processing.

The current behaviour of quoting the output adds unnecessary complexity, standing against the principle of least surprise as well as K-I-S-S.

### Actual Behavior

* Terraform adds quotes to the output that is given to stdout

```console
$ terraform output foo
"Here is my output"
```

### Steps to Reproduce

See above

**Comment by jbardin** [comment] 2020-12-18 13:35
Duplicate of #27100

**Closed by jbardin** 2020-12-18 13:35 UTC
Labels: bug, new
