### ISSUE TITLE
darwin_arm64 build error with tfc-getting-started

### ISSUE THREAD

**Issue by lessc0de** [hashicorp/terraform#29186] opened 2021-07-16 16:39 UTC
I'm trying to follow Terraform Cloud [Getting Started ](https://app.terraform.io/app/getting-started/example)but getting below error on new Apple Macbook with M1 chip

### Terraform Version
```
Terraform v1.0.2
on darwin_arm64
```

### Debug Output
```
tfc-getting-started % ./scripts/setup.sh
...

$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/fakewebservices...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/fakewebservices v0.2.1 does not have a package available for your current platform, darwin_arm64.
│ 

```

 
 
### References
related issue
- #27257

**Comment by jbardin** [comment] 2021-07-16 18:38
Thanks for filing the issue @lessc0de. Since the problem is that the `fakewebservices` provider has not been built for arm64, it's outside of the control of the Terraform project. I see that you already opened and issue in the getting started guide, so I'm going to close this out. That team can decide if they intend to keep the example provider and initiate a release or update the documentation.

Thanks!

**Closed by jbardin** 2021-07-16 18:38 UTC
Labels: bug, new
