### ISSUE TITLE
Terraform apply not working from plan file > v0.12.2

### ISSUE THREAD

**Issue by maxutlvl** [hashicorp/terraform#21801] opened 2019-06-19 12:01 UTC
Hi,
### Terraform Version v0.12.2
Execution scenario:
1. Make terraform plan and save it to plan file:
`terraform plan -out=tfplan.bin`
**Result as expected output saved to plan file.**
2. Run terraform apply from plan file
`terraform apply tfplan.bin`
**Expected result terraform apply changed.**

**Actuall result following errors has been produced:**
##**If I do plan and apply without saving to plan file all works fine** 
`$ terraform apply tfplan.bin`

```Error:Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[4]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.module.destination_buckets.aws_s3_bucket.bucket still has a non-empty state after apply; this is a bug in Terraform



Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[6]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[5]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[8]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.module.destination_buckets.data.aws_ssm_parameter.logging_bucket_name still has a non-empty state after apply; this is a bug in Terraform



Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.module.destination_buckets.aws_s3_bucket_public_access_block.block_public still has a non-empty state after apply; this is a bug in Terraform



Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[1]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[9]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.aws_iam_role_policy.firehose_policy still has a non-empty state after apply; this is a bug in Terraform



Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[7]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[3]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.module.destination_buckets.aws_s3_bucket_policy.policy still has a non-empty state after apply; this is a bug in Terraform



Error: orphan resource module.env.module.env.module.api_gateway_firewalls.aws_wafregional_web_acl.wafregional_acl still has a non-empty state after apply; this is a bug in Terraform



Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.module.destination_buckets.data.aws_ssm_parameter.logging_prefix still has a non-empty state after apply; this is a bug in Terraform



Error: orphan resource module.env.module.env.module.api_gateway_firewalls.aws_wafregional_rule.whitelist still has a non-empty state after apply; this is a bug in Terraform



Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.aws_kinesis_firehose_delivery_stream.stream still has a non-empty state after apply; this is a bug in Terraform



Error: Resource node has no configuration attached

The graph node for
module.env.module.env.module.api_gateway_firewalls.null_resource.waf_redeploy[2]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!


Error: orphan resource module.env.module.env.module.api_gateway_firewalls.aws_wafregional_web_acl_association.waf_to_apigateway still has a non-empty state after apply; this is a bug in Terraform



Error: orphan resource module.env.module.env.module.api_gateway_firewalls.module.kinesis_firehose_stream.aws_iam_role.firehose_role still has a non-empty state after apply; this is a bug in Terraform```

**Comment by simoncocking** [comment] 2019-06-20 02:33
This is a dupe of https://github.com/hashicorp/terraform/issues/21624 and https://github.com/hashicorp/terraform/issues/21515

**Comment by jbardin** [comment] 2019-06-21 16:32
Thanks @maxutlvl and @simoncocking!

Closing as duplicate.

**Closed by jbardin** 2019-06-21 16:32 UTC
