### ISSUE TITLE
Invalid resource instance data in state

### ISSUE THREAD

**Issue by sarathc9** [hashicorp/terraform#25880] opened 2020-08-17 13:47 UTC
Hi, 
I have created the resources in AWS through terraform version v2.7.0 using bitbucket repo. Recently version got upgraded automatically to v3.2.0.
Now am not able to use the same  repository as it showing error in terraform plan:
**Error: Invalid resource instance data in state
  on main.tf line 3545:
3545: resource "aws_api_gateway_method" "main" {
Instance aws_api_gateway_method.main data could not be decoded from the state:
unsupported attribute "request_parameters_in_json".**

This script was executed earlier and resources are created. Please provide me the script to prevent the auto-upgrade or downgrade to previous version.

Thanks in advance.
![terraform_Error](https://user-images.githubusercontent.com/69677741/90403242-4ab4ea80-e0be-11ea-9e1a-115ec57ee68a.png)

**Comment by jbardin** [comment] 2020-08-17 14:16
Thanks @sarathc9,

Duplicate of #25752

**Closed by jbardin** 2020-08-17 14:16 UTC
Labels: bug, new
