### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by seekerofsai** [hashicorp/terraform#35702] opened 2024-09-10 02:25 UTC
### Terraform Version

```shell
Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.14.0
+ provider registry.terraform.io/azure/modtm v0.3.2
+ provider registry.terraform.io/hashicorp/azuread v2.53.1
+ provider registry.terraform.io/hashicorp/azurerm v3.115.0
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/time v0.12.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```
https://github.com/seekerofsai/composable-ai-reference-architectures/tree/aisearch_update/infrastructure/terraform/reference_implementations/secure_aml

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:84 +0x198
panic({0x105343880?, 0x10729b7d0?})
	runtime/panic.go:770 +0x124
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
	github.com/hashicorp/terraform/internal/command/jsonformat/computed/diff.go:54
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.unknownRenderer.RenderHuman({{}, {{0x0?, 0x0?}, 0x4703530?, 0x1?}}, {{0x1058a88d0?, 0x140059557d0?}, 0x1?, 0x0?}, 0x1?, ...)
	github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers/unknown.go:35 +0xd4
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
	github.com/hashicorp/terraform/internal/command/jsonformat/computed/diff.go:54
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.mapRenderer.RenderHuman({{}, 0x14003505f20, 0x0, 0x0, 0x1}, {{0x1058a8970?, 0x1400240fb80?}, 0x4b3ffa8?, 0x40?}, 0x1, ...)
	github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers/map.go:97 +0x620
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
	github.com/hashicorp/terraform/internal/command/jsonformat/computed/diff.go:54
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.blockRenderer.RenderHuman({{}, 0x14003505b00, {0x140041b8180, 0x140041b81b0, 0x140041b81e0, 0x140041b8210, 0x140041b80f0, 0x140041b8120, 0x140041b8150}}, {{0x1058a89e8?, ...}, ...}, ...)
	github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers/block.go:85 +0x5b4
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
	github.com/hashicorp/terraform/internal/command/jsonformat/computed/diff.go:54
github.com/hashicorp/terraform/internal/command/jsonformat.renderHumanDiff({_, _, _}, {{{0x14002e41b60, 0x26}, {0x0, 0x0}, {0x140023aded0, 0x9}, {0x104709021, ...}, ...}, ...}, ...)
	github.com/hashicorp/terraform/internal/command/jsonformat/plan.go:358 +0x32c
github.com/hashicorp/terraform/internal/command/jsonformat.Plan.renderHuman({{0x10470309e, 0x3}, 0x140033b97d0, {0x140049ca000, 0xb0, 0x111}, {0x14004502000, 0x61, 0x88}, {0x14003e83008, ...}, ...}, ...)
	github.com/hashicorp/terraform/internal/command/jsonformat/plan.go:215 +0xad0
github.com/hashicorp/terraform/internal/command/jsonformat.Renderer.RenderHumanPlan({0x1400094de60?, 0x140005fc060?, 0x98?}, {{0x10470309e, 0x3}, 0x140033b97d0, {0x140049ca000, 0xb0, 0x111}, {0x14004502000, ...}, ...}, ...)
	github.com/hashicorp/terraform/internal/command/jsonformat/renderer.go:118 +0x18c
github.com/hashicorp/terraform/internal/command/views.(*OperationHuman).Plan(0x14000b0da30, 0x14004be9540, 0x1400543c320)
	github.com/hashicorp/terraform/internal/command/views/operation.go:130 +0x230
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0x1400070bae0, {0x1058cded0, 0x1400088b040}, {0x1058cded0, 0x1400088b090}, 0x14000595400, 0x14000b1de80)

### Expected Behavior

provisioning successful

### Actual Behavior

crash

### Steps to Reproduce

terraform init
terraform plan

**Comment by liamcervante** [comment] 2024-09-10 06:24
Duplicate of https://github.com/hashicorp/terraform/issues/35630

**Closed by liamcervante** 2024-09-10 06:24 UTC
Labels: bug, new
