### ISSUE TITLE
Google cloud dependencies not working with depends_on

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#3561] opened 2015-10-20 09:41 UTC
When doing a change to a google cloud persistent disk that necessitates a destroy/create terraform doesn't detect that the vm that depends on the disk using depends_on should first be destroyed and afterwards be recreated.

I changed the snapshot the disk is created from which forced the destroy/create. The disk isn't attached to a vm in a normal way, but mounted directly into a docker container by the kubelet daemon running on the vm. This is why I use depends_on.

```
resource "google_compute_disk" "disk1" {
    snapshot = "some-snapshot"
}

resource "google_compute_instance" "vm1" {
    depends_on = ["google_compute_disk.disk1"]
}
```

**Comment by lwander** [comment] 2015-10-20 18:56
The `depends_on` attribute isn't exposed to the provider implementer, so this sounds like more of a core problem. What do you think @catsby?

**Comment by catsby** [comment] 2015-10-30 14:07
Hey all, sorry for the late reply –

@lwander is correct, in that the specifics of the `depends_on` override are not exposed to the resource provider, so this is more of a core issue. I believe I mislabeled it in a hasty triage session :)

The `depends_on` meta-parameter is only concerned with a binary state regarding the dependency; it exists or it does not. Attempting to remove `google_compute_disk.disk1` would cause a validation error, but the recreation does not. As far as Terraform is concerned, it exists (or will), satisfying the dependency. 

Alternatively, if `google_compute_instance.vm1` specifically referenced `google_compute_disk.disk1`, I believe you would get the behavior you’re looking for. By explicitly referencing an attribute of another resource, a dependency is established and then the recreation or updating is deferred to the resource in question. In this example, the resource `google_compute_instance.vm1` has an attribute `disk` that is marked as `ForceNew`, so it would then be recreated with any change to said disk.

Looking at the docs for Google Cloud Platform, it seems you can create a configuration that does the latter for dependencies:

```
resource "google_compute_disk" "disk1" {
    snapshot = "some-snapshot"
}

resource "google_compute_instance" "vm1" {
    […]
    disk {
      name = “${google_compute_disk.disk1.name}”
    }
    […]
}
```

I’m not too familiar with Google Cloud though, does that work for you?

**Comment by JorritSalverda** [comment] 2015-10-30 15:17
That last example actually attaches the drive to the instance. In my particular case I do not want to attach it during creation, because a process on the machine takes care of attaching and mounting it.

**Comment by sparkprime** [comment] 2015-11-10 16:37
depends_on ought to have the same behavior as creating a reference, so this is a core bug in my opinion.  (Actually, I thought this was already fixed, perhaps it is rebroken.)

**Comment by apparentlymart** [comment] 2017-04-04 22:16
Hi all! Sorry for the silence here.

This actually appears to be a duplicate of #2341, so I'm going to close this one to consolidate the discussion (such that it is) over there.

**Closed by apparentlymart** 2017-04-04 22:16 UTC
Labels: bug, core
