### ISSUE TITLE
splat operator doesn't work as expected in data source

### ISSUE THREAD

**Issue by jeffbehl** [hashicorp/terraform#27770] opened 2021-02-14 19:23 UTC
My reading of the [splat operator](https://www.terraform.io/docs/language/expressions/splat.html) seems to indicate 

`[for d in data.aws_elasticsearch_domain.all : d.arn]` 

is identical to

`data.aws_elasticsearch_domain.all[*].arn`

yet  the below does not work (see inline comments):
```teraform  
policy = templatefile(
    "${path.module}/templates/role_policy_collector_es.json.tpl",
    {
      role       = aws_iam_role.logicmonitor_collector,
      # es_domains = [for d in data.aws_elasticsearch_domain.all : d.arn]  # WORKS!
      es_domains = data.aws_elasticsearch_domain.all[*].arn                     # DOES NOT WORK
    }
```

Apologies if this is a mistake on my end.  I tried posting in the community but  it was marked as spam.

### Terraform Version

```
Terraform v0.14.6
```

### Terraform Configuration Files

```terraform
aws_elasticsearch_domain" "all" {
  for_each = toset(local.es_domains)

  domain_name = each.key
}

resource "aws_iam_policy" "logicmonitor_collector_es" {
  name        = "tf-logicmonitor_monitoring_es"
  description = "Used by LogicMonitor to connect to ES"

  policy = templatefile(
    "${path.module}/templates/role_policy_collector_es.json.tpl",
    {
      role       = aws_iam_role.logicmonitor_collector,
      # es_domains = [for d in data.aws_elasticsearch_domain.all : d.arn]  # WORKS!
      es_domains = data.aws_elasticsearch_domain.all[*].arn                     # DOES NOT WORK
    }
  )
}

```

### Debug Output
```
Error: Unsupported attribute

  on ec2_collectors_iam.tf line 61, in resource "aws_iam_policy" "logicmonitor_collector_es":
  61:       es_domains = data.aws_elasticsearch_domain.all[*].arn

This object does not have an attribute named "arn".
```
### Expected Behavior
templatefile should render correctly

### Steps to Reproduce

`terraform apply`

**Comment by apparentlymart** [comment] 2021-02-15 02:07
Hi @jeffbehl,

The subtlety with the splat operator is that it's equivalent to a `for` expression _only_ if the left operand of `[*]` has a list, tuple, or set type. For all other types, it activates the special behavior that applies to the splat operator but not to `for` expressions: it will automatically wrap the non-list value in a single-element tuple before processing it.

From the example you shared it looks like you have `for_each` set on that `data.aws_elasticsearch_domain.all` resource, which means that the value of that expression is a map of objects. Therefore it ends up trying to access this attribute `.arn` as a key in that map (after converting it to a single-element tuple containing that map), rather than as an attribute of each of the objects in the map.

When using maps, a `for` expression is the only correct way to write a projection like this. The example you have in your configuration that worked is exactly what I would've suggested.

Since Terraform seems to be working as intended here (albeit with behavior that is a little confusing unless you read the docs quite carefully), I'm going to close this. Note that folks do monitor the results of the spam filter on the community forum, so misidentified posts will typically show up once someone has reviewed them. There is typically not anyone monitoring that queue on weekends though, so you might find your posts gets approved once folks return to work on Tuesday (since this is a long weekend for US and Canada, where most of the folks who moderate the forum are based). Thanks!

**Closed by apparentlymart** 2021-02-15 02:07 UTC
Labels: bug, new

**Comment by jeffbehl** [comment] 2021-02-16 16:05
thanks for the thorough explanation Martin, much appreciated, and I'll be more patient with the forums next time.
