### ISSUE TITLE
Plan/apply output erroneously showing massive amount of spam for aws_elastic_beanstalk_environment since 0.12

### ISSUE THREAD

**Issue by mrubin** [hashicorp/terraform#26875] opened 2020-11-11 13:33 UTC
### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/-/aws v3.4.0
+ provider registry.terraform.io/-/template v2.1.2
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/aws v3.8.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

### Debug Output

This is just a sample - there is a ton more spam shown for settings that haven't actually changed at all.

```
      - setting {
          - name      = "Unit" -> null
          - namespace = "aws:autoscaling:trigger" -> null
          - value     = "Percent" -> null
        }
      + setting {
          + name      = "Unit"
          + namespace = "aws:autoscaling:trigger"
          + value     = "Percent"
        }
      - setting {
          - name      = "UpdateLevel" -> null
          - namespace = "aws:elasticbeanstalk:managedactions:platformupdate" -> null
          - value     = "patch" -> null
        }
      + setting {
          + name      = "UpdateLevel"
          + namespace = "aws:elasticbeanstalk:managedactions:platformupdate"
          + value     = "patch"
        }
      - setting {
          - name      = "UpperBreachScaleIncrement" -> null
          - namespace = "aws:autoscaling:trigger" -> null
          - value     = "2" -> null
        }
      + setting {
          + name      = "UpperBreachScaleIncrement"
          + namespace = "aws:autoscaling:trigger"
          + value     = "2"
        }
      - setting {
          - name      = "UpperThreshold" -> null
          - namespace = "aws:autoscaling:trigger" -> null
          - value     = "60" -> null
        }
      + setting {
          + name      = "UpperThreshold"
          + namespace = "aws:autoscaling:trigger"
          + value     = "60"
        }
      - setting {
          - name      = "VPCId" -> null
          - namespace = "aws:ec2:vpc" -> null
          - value     = "vpc-d4fdacac" -> null
        }
      + setting {
          + name      = "VPCId"
          + namespace = "aws:ec2:vpc"
          + value     = "vpc-d4fdacac"
        }
```

### Expected Behavior

Resource settings that haven't changed shouldn't be shown in the output.

### Actual Behavior

Resource settings that haven't changed are being shown in the output.

### Steps to Reproduce

Have a `aws_elastic_beanstalk_environment` resource with 1 or more changes to it (vs what's in AWS). Run `plan` or `apply` and look at the output. I would expect that only the changed "setting" would be shown. In reality, all or most of them are shown, which is so much output (especially if you're working on multiple `aws_elastic_beanstalk_environment` resources) that it becomes nearly impossible to see what changes you're actually applying.

### Additional Context

This started happening with 0.12.

**Comment by alisdair** [comment] 2020-11-11 18:23
Hi @mrubin, thanks for reporting this. Unfortunately there isn't quite enough information to allow us to easily reproduce this problem for investigation. Can you please provide a small but complete configuration and the steps to reproduce?

**Comment by mrubinwch** [comment] 2020-12-01 16:29
@alisdair have you tried creating an aws_elastic_beanstalk_environment resource and modifying something on it? This should reproduce the problem. Or are you saying that you do not see the issue?

**Comment by alisdair** [comment] 2020-12-01 17:44
I do not have a working configuration which creates an `aws_elastic_beanstalk_environment` resource. My initial attempts to do so did not succeed, and I only have so much time to dedicate to each issue. Providing a working configuration which reproduces the issue is very helpful when submitting a bug report.

However, [given that the `setting` arguments are implemented with `TypeSet`](https://github.com/hashicorp/terraform-provider-aws/blob/840888e8327f82f8abab32d536d2e7e13d37defa/aws/resource_aws_elastic_beanstalk_environment.go#L113-L118) this appears likely to be a duplicate of #27018. See this comment on the linked issue for an explanation of what is happening here:

> Yes, this can be an unfortunate behavior with this schema combination. In most cases terraform does not show changed elements within a set when constructing the diff output. What is happening is that there must be other "unimportant" change which are not shown here, causing these set elements to change their value. While we have heuristics to elide some lines of these trivial changes, it still causes the entire set value to change which needs to be displayed. The new output in 0.14 should at least present the changes in a sorted order to make them easier to spot.
> 
> The real culprit here is the legacy provider SDK, which cannot handle the full rich type system that is used within terraform. The impedance mismatch often leaks some changes, most often null values being replaced with empty values of the same type, and we work around those to the best of our abilities. There is currently work being done to develop a new SDK, which will have direct access to the same type system, giving providers more control of the data structures they store in the state.
> 
> Since this is primarily caused by the plugin SDK (though providers can sometimes work around it in their side), and there's not much more we can do in terraform core until a new SDK is in use, I'm going to close this out for now.

In line with the conclusion above, I'm going to close this also.

**Closed by alisdair** 2020-12-01 17:44 UTC
Labels: bug, waiting for reproduction
