### ISSUE TITLE
Referencing to a module in a peer directory using relative path with `..\other_module`

### ISSUE THREAD

**Issue by lbustelo** [hashicorp/terraform#16203] opened 2017-09-27 16:57 UTC
### Terraform Version
0.10.6

### Terraform Configuration Files
n/a

### Debug Output
```
Get: git::ssh://git@github.com/org/utils?ref=v0.1.0//to_qualified_name
Get: git::ssh://git@github.com/org/utils?ref=v0.1.0//to_tags
Error loading modules: module tag_qname: invalid source string: ../to_qualified_name
```

### Crash Output
n/a

### Expected Behavior
We have a single git repo that contains a collection of modules that are in subdirectories. The idea is to not have to create a repo for a collection of very small modules that mainly transform input variables into output. Some of these modules use each other, so within these modules, there are references to peer folders. For example:

```
module "tag_qname" {
  source                = "../to_qualified_name"
  environment           = "${var.environment}"
  name                  = "${var.name}"
}
```

In `0.9.x` this was working. In 0.10.x, we now get error above. It seems that terraform is downloading github subdir sources are standalone modules under `.terraform/modules` and no longer can modules that come from a single git repo able to reference each other.

### Actual Behavior
Get the error under `Debug Output`

### Steps to Reproduce
1. Create a repo that contains 2 modules
2. Have module A user module B by sourcing it using relative path `../moduleB`
3. Create an external main.tf that brings in module a from git repo 
```<repo url>?ref=version//moduleA```
4. Do a `terraform get` and see the error about moduleA not able to find `../moduleB`

### Important Factoids
Used to work in 0.9.x!!!

### References
n/a

**Comment by shinzui** [comment] 2017-09-27 21:34
It also used to work in 0.10.2. Is this a regression?

**Comment by PauloMigAlmeida** [comment] 2017-09-28 01:05
I confirm this was working until 0.10.5 version but after some changes on the ```terraform/config/module/tree.go``` it stopped working 

Diff: https://github.com/hashicorp/terraform/compare/refs/tags/v0.10.5...refs/tags/v0.10.6

## Previous behaviour (<= 0.10.5)
Module Source:
```
source = "git@github.com:org/repo.git?ref=v1.1.1//terraform/"
```
.modules folder:
<img width="356" alt="screen shot 2017-09-28 at 1 57 23 pm" src="https://user-images.githubusercontent.com/1011868/30944528-0342a10e-a455-11e7-969d-2127306ac14d.png">

## Actual behaviour (>= 0.10.6)
Module Source:
```
source = "git@github.com:org/repo.git?ref=v1.1.1//terraform/"
```
.modules folder:

<img width="364" alt="screen shot 2017-09-28 at 2 01 28 pm" src="https://user-images.githubusercontent.com/1011868/30944608-9229a7e6-a455-11e7-84f2-72b070978dcd.png">

## Conclusion
Before 0.10.6 it was cloning the entire repo instead of just the folder where the terraform module source resides. This is particularly used when using relative folder references such as:

```
# -- VERSION
output "version"  { value = "${file("${path.module}/../VERSION")}" }
```

**Comment by jbardin** [comment] 2017-09-28 12:42
Thanks for reporting the issue!

This is a duplicate of #16138, already has a patch being tested in master.

**Closed by jbardin** 2017-09-28 12:42 UTC
