### ISSUE TITLE
Stabilize the state snapshot format so that exact Terraform CLI versions are no longer required

### ISSUE THREAD

**Issue by dortort** [hashicorp/terraform#26340] opened 2020-09-22 20:01 UTC
### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

Your version of Terraform is out of date! The latest version
is 0.13.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "***"

    workspaces {
      name = "test"
    }
  }
}

resource "random_id" "id" {
  byte_length = 8
}
```

### Expected Behavior
Should successfully apply first and subsequent plans. (With remote execution mode, local version should be irrelevant.)

### Actual Behavior
First plan succeeds but subsequent attempts to modify or refresh state result in error:
```
Failed to load state: state snapshot was created by Terraform v0.13.3, which is newer than current v0.13.2; upgrade to Terraform v0.13.3 or greater to work with this state
```

### Steps to Reproduce
```
❯ terraform version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

Your version of Terraform is out of date! The latest version
is 0.13.3. You can update by downloading from https://www.terraform.io/downloads.html
❯ terraform apply
Running apply in the remote backend. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

To view this run in a browser, visit:
https://app.terraform.io/app/***/test/runs/run-bzYpZ3mGPcCTuFcf

Waiting for the plan to start...

Terraform v0.13.3
Configuring remote state backend...
Initializing Terraform configuration...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # random_id.id will be created
  + resource "random_id" "id" {
      + b64         = (known after apply)
      + b64_std     = (known after apply)
      + b64_url     = (known after apply)
      + byte_length = 8
      + dec         = (known after apply)
      + hex         = (known after apply)
      + id          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "test"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

random_id.id: Creation complete after 0s [id=jLFpNRvVbpI]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
❯ terraform taint random_id.id
Failed to load state: state snapshot was created by Terraform v0.13.3, which is newer than current v0.13.2; upgrade to Terraform v0.13.3 or greater to work with this state
❯ terraform init

Initializing the backend...
Error refreshing state: state snapshot was created by Terraform v0.13.3, which is newer than current v0.13.2; upgrade to Terraform v0.13.3 or greater to work with this state
```

### Additional Context
![image](https://user-images.githubusercontent.com/1169721/93931494-db4d9e80-fcec-11ea-9966-676c0676cd0a.png)

**Comment by apparentlymart** [comment] 2020-09-24 23:06
Hi @dortort! Thanks for reporting this.

Unfortunately I think this behavior is as intended, because you're using a mixture of both remotely-executing and locally-executing commands here, and so you need to match the local version with the remote version in order to ensure correct operation.

The `terraform taint` command is a local-only operation which modifies the state locally before uploading a new snapshot to the remote system. Therefore it refuses to work with state generated by a newer version as a safety check to ensure that it can't misinterpret the snapshot created by a newer version.

The `terraform init` situation is a little trickier in that here Terraform is trying to analyze the state to decide which plugins to install for local use. If you are working entirely remotely then you may be able to bypass that by running `terraform init -get-plugins=false`, although I must admit I'm not sure off the top of my head if that bypasses fetching the state or if it just skips installing any provider plugins it finds in there.

With all of that said, unfortunately I'm not sure there's anything specific we could do to avoid the exact version requirement in the near future. We are hoping to relax the state format requirements in a future release when the state format is committed stable, but there are several more minor changes to the format planned before we can reach that point.

Since Terraform was working as designed here, even though the current behavior is certainly non-ideal, I'm going to relabel this as an enhancement request for making Terraform no longer require an exact state version, and then we'll use this issue to communicate about changes in that situation in future major releases.

**Comment by dortort** [comment] 2020-09-29 00:43
Understood. Just to give some added context, this issue arrises in a serverless CI environment (GitHub Actions with GitHub's runners), where `terraform init` is systematically run before other commands. Here's an example of such a config:
```yaml
      - name: Deploy
        env:
          TF_IN_AUTOMATION: 'true'
        run: |
          mkdir .terraform && echo "$ENV" > .terraform/environment
          terraform init -input=false
          terraform apply -input=false -auto-approve
```

**Comment by apparentlymart** [comment] 2021-01-13 18:56
Hi again, @dortort!

I'm happy to have some progress to report on this one. As part of our current focus on stabilizing things in preparation for a v1.0 release, we recently committed to the current definition of state snapshot format version 4 as being supported for the foreseeable future, and represented that by loosening the version checks so that new versions of Terraform will accept any state snapshot that fits version 4 of the format, with the caveat that you must complete the upgrade process to v0.13 at least in order to deal with the migration steps that predate this looser definition.

If there is a future change that requires a different state snapshot format then we'll introduce state snapshot format 5 in a Terraform CLI major release, and caution about the "ratchet effect" that would cause that in the upgrade guide for the release.

I think that change has therefore resolved this enhancement request for future Terraform upgrades, and we have no current specific plans to change the state format in a breaking way that would require introducing a state snapshot version 5. Given that, I'm going to close this issue. Thanks again for raising this!

---

The original request here didn't discuss this but for completeness I want to note that this change in behavior only applies to Terraform CLI's own handling of the top-level format. State snapshots also contain data that is provided and interpreted by specific Terraform providers, and so the versioning of those resource-type-specific formats is up to the individual providers to handle. If you upgrade to a newer version of a provider and run `terraform apply` then you might find that your new state snapshot is no longer compatible with earlier versions of the provider. Fortunately this should be less of a problem now that Terraform v0.14 has introduced [the dependency lock file](https://www.terraform.io/docs/configuration/dependency-lock.html), which should help to keep multiple Terraform execution environments synchronized in terms of which specific provider versions they are using.

**Closed by apparentlymart** 2021-01-13 18:56 UTC
Labels: core, enhancement, terraform-cloud
