### ISSUE TITLE
Add config parameter for "minimum terraform version"

### ISSUE THREAD

**Issue by vitroth** [hashicorp/terraform#3382] opened 2015-10-01 21:04 UTC
It would be useful for a terraform config to be able to specify the minimum compatible terraform version for that config.  I had an issue today where user A had previously deployed a config that included and Elastic Network Address, using 0.6.3, but today user B ran terraform 0.6.1 on the same config and didn't notice that (due to a bug in 0.6.1) it was going to delete and re-create the ENI.

This could also be done via the state file, automatically storing the last version used and notifying the user if their terraform version is older (but allowing the user to proceed if they choose).

**Comment by radeksimko** [comment] 2015-10-01 21:11
Hi @vitroth 
isn't this a duplicate of https://github.com/hashicorp/terraform/issues/1400 ?

**Comment by vitroth** [comment] 2015-10-01 21:16
You are correct... Sorry, searching through github issues I didn't see that one.

**Closed** 2015-10-01 21:17 UTC
Labels: core, enhancement, waiting-response
