### ISSUE TITLE
aws_route53_record.internal_domain_ns: diffs didn't match during apply

### ISSUE THREAD

**Issue by mildred** [hashicorp/terraform#8881] opened 2016-09-16 13:32 UTC
### Terraform Version

 Terraform Version: 0.7.3
### Affected Resource(s)
- aws_route53_record
### Terraform Configuration Files

``` hcl
resource "aws_route53_record" "internal_domain_ns" {
  zone_id = "${var.sqsc_primary_zone_id}"
  name    = "${var.environment}.${var.sqsc_customer_name}.${var.internal_domain}"
  type    = "NS"
  ttl     = "30"

  records = [
    "${aws_route53_zone.internal_domain.name_servers.0}",
    "${aws_route53_zone.internal_domain.name_servers.1}",
    "${aws_route53_zone.internal_domain.name_servers.2}",
    "${aws_route53_zone.internal_domain.name_servers.3}",
  ]
}
```

See the rest in the attached encrypted file. This is a .zip file of the AWS lambda containing the terraform binary (stripped) and configuration (with credentials stripped) that triggered the error.

https://www.wetransfer.com/downloads/dac3b2a8825a2d040fee16ad4124792a20160916133159/a6915d2e3434d949fc146ccf629a15fa20160916133159/3230e3

Files (3.01 MB total)
terraform-lambda-bug-report.zip.gpg

Will be deleted on
23 September, 2016
### Debug Output

https://gist.github.com/mildred/08a4c8a37afb18642f88ae99b85334e4

Selected part:

```
* aws_route53_record.internal_domain_ns: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
Please include the following information in your report:
Terraform Version: 0.7.3
Resource ID: aws_route53_record.internal_domain_ns
Mismatch reason: attribute mismatch: records.1369003185
```
### Steps to Reproduce

Didn't reproduce, next run of the exact same thing succeeded.
### Important Factoids

Terraform running from an AWS lambda using selected AWS credentials (not inheriting the credentials from the AWS lambda environment)

**Comment by mitchellh** [comment] 2016-11-17 00:52
Hello! This should be fixed in later versions of Terraform. 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 00:52 UTC
Labels: bug, provider/aws
