### ISSUE TITLE
terraform-0.13beta2 crashes on setunion

### ISSUE THREAD

**Issue by alxrem** [hashicorp/terraform#25418] opened 2020-06-26 20:45 UTC
### Terraform Version

```
$ terraform-0.13 version
Terraform v0.13.0-beta2
```

### Terraform Configuration Files

```hcl
variable "a" {
  default = {
    p = 1
  }
}

locals {
  b = setunion(keys(var.a))
}
```

### Debug Output

https://gist.github.com/alxrem/c66fba87da41705cbfaa9d6ea8e97296

### Expected Behavior

`local.b` gets value `set(["p"])`

### Actual Behavior

Panic

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by alisdair** [comment] 2020-06-26 20:54
Thanks for reporting this! It looks like a duplicate of #25318, which was fixed in #25400. I've verified that your example works as expected on the latest build from the main branch.

**Closed by alisdair** 2020-06-26 20:54 UTC
