### ISSUE TITLE
core: "unknown variable accessed" when doing destroy with target

### ISSUE THREAD

**Issue by kyhavlov** [hashicorp/terraform#8146] opened 2016-08-11 18:32 UTC
I'm getting the following error when trying to run `terraform destroy -target=module.thing1` on the config below:

```
Error configuring: 1 error(s) occurred:

* 1:3: unknown variable accessed: var.count in:

${var.count}
```

This doesn't happen without the -target, so it seems like that's the issue. It could be related to #8098 but I've only seen this error with -target when doing destroy, not apply or plan.
### Terraform Version

```
$ terraform -v
Terraform v0.7.0
```
### Terraform Configuration Files

./main.tf:

``` hcl
module "thing1" {
  source = "./thing"
  count = 3
}
```

./thing/null.tf:

``` hcl
variable "count" {}

resource "null_resource" "thing" {
  count        = "${var.count}"
}
```

**Comment by vaygr** [comment] 2016-08-17 00:22
Same issue here.

**Comment by vaygr** [comment] 2016-08-17 00:36
Same issue here, but it got fixed when I set `default` value for the variable.

**Comment by roboll** [comment] 2016-08-17 18:34
Setting a default for the variable doesn't fix the underlying issue, that the interpolated variable is not being respected properly in the destroy dependency graph. When the destroy executes, it uses the default, which in many cases will cause incorrect behavior.

**Comment by roboll** [comment] 2016-08-17 20:36
This broke sometime between `v0.7.0-rc3` and `v0.7.0`.

**Comment by roboll** [comment] 2016-08-17 20:41
I suspect #6599 may have something to do with this.

**Comment by roboll** [comment] 2016-08-17 23:05
Confirmed removing [this change](https://github.com/hashicorp/terraform/blob/559f017ebb7649d4db425f9f2412c1463a36f97d/terraform/graph_config_node_variable.go#L93-L101) from #6599 fixes the issue from `v0.7.0`.

**Comment by RyanBowlby-Reflektion** [comment] 2016-08-23 04:37
Thanks @vaygr for the temporary hack. After filling in several defaults (that would never be real defaults) I was able to destroy.

Scary to think that the non-default values are not being honored.

**Comment by hazim1093** [comment] 2016-09-16 11:56
Facing the same issue on 0.7.2 and 0.7.3. 
The workaround of adding default value did the trick

**Comment by kyhavlov** [comment] 2016-09-23 20:43
I put up a PR for this: #9021

**Comment by mitchellh** [comment] 2016-11-03 06:07
Since #9021 merged the repro above no longer occurs. Thanks @kyhavlov!

**Closed by mitchellh** 2016-11-03 06:07 UTC
Labels: bug, core

**Comment by vaygr** [comment] 2016-12-20 20:49
Looks like the same issue exists for `apply` in at least **0.8.1**:

```shell
$ terraform plan -target='module.ca_central_1'
```

```
Error running plan: 8 error(s) occurred:

* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
* 1:3: unknown variable accessed: var.aws_region in:

${var.aws_region}
```

while declaring it like this in `main.tf`:

```
module "ca_central_1" {
  source        = "haproxy_ec2"
  aws_region    = "ca-central-1"
  haproxy_count = "2"
}
```

**Comment by progre55** [comment] 2016-12-22 00:53
@mitchellh FYI: this issue is back on `0.8.1` and `0.8.2` with both, `plan` and `apply`. Haven't tried `destroy`, though.

**Comment by mitchellh** [comment] 2016-12-22 01:03
Thanks @progre55 and @vaygr, do you think either of you could put together a small reproduction so we can take a closer look?

**Comment by jesperborgstrup** [comment] 2017-01-17 09:53
FYI, I'm seeing this issue also in `0.8.4`

**Comment by schinivision** [comment] 2017-02-03 10:08
F.Y.I. I am facing that issue in versions 0.8.0, 0.8.4 and 0.8.5 -> 0.7.13 works perfectly

See: https://github.com/hashicorp/terraform/issues/9042

The ´´´-Xlegacy-graph´´´ option helped in 0.8.5 so i can plan again but i don't think this is an intended behaviour

**Comment by eyalzek** [comment] 2017-02-22 14:35
Still seeing this with version 0.8.6. Also, adding `-Xlegacy-graph` to `terraform import` doesn't seem to solve it, so I'm unsure at the moment how to import resources (besides editing the state manually to change the terraform version and doing it again with version 0.7.13...)

**Comment by vaygr** [comment] 2017-02-22 14:40
Yeah, the bug's back.

**Comment by vikas027** [comment] 2017-03-10 10:55
Seeing this in v0.8.8 as well :(

**Comment by gerr1t** [comment] 2017-08-02 14:52
Confirmed this bug in v0.8.8, dummy default values work.
