### ISSUE TITLE
Template File Spacing when using String Template Directives

### ISSUE THREAD

**Issue by jmsuzuki** [hashicorp/terraform#24959] opened 2020-05-15 04:06 UTC
### Terraform Version

```
Terraform v0.12.24
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.vsphere v1.18.1
```

### Terraform Configuration Files

tfvars
```hcl
rancher_cluster_name = "MyClusterName"
is_mgmt_cluster = true
ssh_user = "root"
ssh_password = "root"
```
variables
```hcl
variable "rancher_cluster_name" {
  type = string
  description = "name of the cluster"
}

variable "is_mgmt_cluster" {
  type = bool
  description = "flag to determine which inventory file to build.  mgmt vs sub"
}

variable "ssh_user" {
  type = string
  description = "username to ssh into servers with"
}

variable "ssh_password" {
  type = string
  description = "username to ssh into servers with"
  default = null
}

variable "ssh_private_key" {
  type = string
  description = "password associated with the user for ssh."
  default = null
}
```
main
```hcl
locals {
  mgmt_inventory_file = "${path.module}/../../../ansible/mgmt/inventory-${var.rancher_cluster_name}"
  sub_inventory_file = "${path.module}/../../../ansible/subcluster/inventory-${var.rancher_cluster_name}"
}

data "template_file" "ansible_inventory_file" {
  template = file("${path.module}/templates/inventory.tpl")

  vars = {
    ### SSH
    ssh_user = var.ssh_user
    ssh_password = var.ssh_password

    private_key_enabled = var.ssh_private_key != null ? true : false
    ssh_private_key = var.ssh_private_key
  }
}

resource "null_resource" "generate_ansible_inventory_file" {
  count = var.is_mgmt_cluster ? 1 : 0

  triggers = {
    template_rendered = data.template_file.ansible_inventory_file.rendered
  }

  provisioner "local-exec" {
    command = "echo '${data.template_file.ansible_inventory_file.rendered}' > ${local.mgmt_inventory_file}"
  }
}
```
ansible inventory template file
```hcl
[all:vars]
ansible_connection=ssh
ansible_user=${ssh_user}

%{ if private_key_enabled }
ansible_ssh_private_key_file=${ssh_private_key}
%{ else }
ansible_ssh_pass=${ssh_password}
%{ endif }
```
### Expected Behavior

```
[all:vars]
ansible_connection=ssh
ansible_user=centos

ansible_ssh_pass=root
```

### Actual Behavior

extra lines are in place of directive lines instead of being trimmed.
```
[all:vars]
ansible_connection=ssh
ansible_user=centos


ansible_ssh_pass=root
```

### Steps to Reproduce

1. Create a `data "template_file"` resource
2. use string template directives like as seen above in the example of a templated ansible inventory file.
3. run `terraform init` and `terraform apply` to build the templated file.

**Comment by danieldreier** [comment] 2020-05-18 22:48
Hi! Thanks for reporting this. I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. The code you provided in the terraform configuration files section is not terraform code.

Can you please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies.

**Comment by jmsuzuki** [comment] 2020-05-18 23:06
Hi Daniel,
I completed the configuration code with a flushed out (trimmed) example of my code/module for creating a templated file.

**Comment by danieldreier** [comment] 2020-05-18 23:22
Hi @jmsuzuki thanks for that, that helped me understand what you're looking for. I have two suggestions:

1) you're looking for what are called strip markers - e.g. `%{ if foo ~}`. The `~` makes it so that that line doesn't render as a blank line
2) the `local_file` resource is likely a better approach for you than using `local-exec`. Here's the fixed code snippet that produced the expected result for me:

```hcl
data "template_file" "ansible_inventory_file" {
  template = file("${path.module}/templates/inventory.tpl")

  vars = {
    ### SSH
    ssh_user = var.ssh_user
    ssh_password = var.ssh_password

    private_key_enabled = var.ssh_private_key != null ? true : false
    ssh_private_key = var.ssh_private_key
  }
}

resource "local_file" "inventory-file" {
    content     = data.template_file.ansible_inventory_file.rendered
    filename = "${path.module}/inventory-file"
}
```
inventory.tpl
```
[all:vars]
ansible_connection=ssh
ansible_user=${ssh_user}

%{ if private_key_enabled ~}
ansible_ssh_private_key_file=${ssh_private_key}
%{ else ~}
ansible_ssh_pass=${ssh_password}
%{ endif ~}
```

resulting output:
```
[all:vars]
ansible_connection=ssh
ansible_user=root

ansible_ssh_pass=root
```

That said, we use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

I'm going to close this now, because I believe I've answered your question and confirmed to myself that there's no bug here. If you have any other questions about this, feel free to ask them in the community forum.

**Closed by danieldreier** 2020-05-18 23:22 UTC

**Comment by jmsuzuki** [comment] 2020-05-19 16:32
Hi Daniel, thank you for bringing the `local_file` resource to my attention.
If I were the developer for this piece of code, I would consider this a minor bug.
Under which conditions would anyone ever want the extra whitespace?  It's ugly and should be removed by the parser by default and not a flag.
As a developer, the flag feels like a hacky solution.
