### ISSUE TITLE
module git source with access token env variable in url doesn't work

### ISSUE THREAD

**Issue by Temdegon** [hashicorp/terraform#35239] opened 2024-05-24 22:02 UTC
### Terraform Version

```shell
Terraform version: 1.8.4
```

### Terraform Configuration Files

----

### Debug Output

```
Could not download module "fifo-handler" (main.tf:26) source code from
"git::https://x-token-auth:$GIT_TOKEN@bitbucket.org/coople/fifo-handler.git?ref=0.46":
error downloading
'https://x-token-auth:redacted@bitbucket.org/coople/fifo-handler.git?ref=0.46':
/usr/bin/git exited with 128: Cloning into
.terraform/modules/fifo-handler'...
remote: Invalid credentials
fatal: Authentication failed for
'https://bitbucket.org/coople/fifo-handler.git/'
```

### Expected Behavior

I'm using bitbucket access token in env variable to access another git repos.
Works fine with normal git operations in the same pipeline:
```
git clone https://x-token-auth:$GIT_TOKEN@bitbucket.org/my-org/my-repo.git
```
but in terraform such syntax doesn't work:
```
module my-module {
  source = "git::https://x-token-auth:$GIT_TOKEN@bitbucket.org/my-org/my-repo.git//modules/module.git?ref=0.123"
}
```

### Actual Behavior

fail with error:
```
remote: Invalid credentials
fatal: Authentication failed
```

### Steps to Reproduce

terraform init

**Comment by apparentlymart** [comment] 2024-05-28 16:59
Hi @Temdegon,

Indeed, Terraform does not expect to find environment variable interpolation in this argument. It does allow specifying credentials here as literals, but that's typically not a good idea even if literal because the `source` address should ideally only specify which module to use, and not what credentials to use to fetch it.

The typical approach for authenticating to Git repositories is to configure [Git's own credentials mechanism](https://git-scm.com/docs/gitcredentials) on your system. That is also the approach commonly used for other language ecosystems that support installing dependencies directly from Git, and gives you the most flexibility for where to obtain credentials from.

I would therefore suggest that you remove the `x-token-auth:$GIT_TOKEN@` part of that source address altogether, and instead use Git's credentials mechanisms to specify the appropriate username and password for `https://bitbucket.org`.

Terraform is working as designed here -- environment variables are intentionally not supported in this position -- so I'm going to close this issue. Thanks!

**Closed by apparentlymart** 2024-05-28 16:59 UTC
Labels: bug, new
