### ISSUE TITLE
Terraform targets file 

### ISSUE THREAD

**Issue by smicha** [hashicorp/terraform#17417] opened 2018-02-23 00:13 UTC
### Terraform Version
 v 0.10.8
 
 
### Expected Behavior
 
      Would it be possoble to have a -target-file option instead of having to provide multiple 
       -target options   for terraform plan or destroy
 

### Actual Behavior
 
      -target option is only available .

**Comment by matteomazza91** [comment] 2019-10-03 16:21
duplicate of #17285

**Closed** 2024-06-05 08:53 UTC
Labels: enhancement, cli
