### ISSUE TITLE
Terraform cloud bug v0.12.28 keeps crashing on me

### ISSUE THREAD

**Issue by ranjeetpatilnetsec** [hashicorp/terraform#25809] opened 2020-08-11 18:48 UTC
Hello Hashicorp Support, 
      Terraform cloud has some bug causing it to crash when applying plan. Please see below bug details. 

Terraform v0.12.28
Initializing plugins and modules...
2020/08/11 18:35:00 [DEBUG] Using modified User-Agent: Terraform/0.12.28 TFC/e37a604825
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0x10644e8]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote.(*Remote).Operation(0xc0004b3d90, 0x2468420, 0xc00009c078, 0xc0005b81c0, 0x8709e5, 0x1c8edc0, 0x0)
	/home/circleci/project/project/backend/remote/backend.go:650 +0x98
github.com/hashicorp/terraform/command.(*Meta).RunOperation(0xc0002a3180, 0x7f87c6aec4a0, 0xc0004b3d90, 0xc0005b81c0, 0x1, 0x1, 0x0)
	/home/circleci/project/project/command/meta.go:289 +0x83
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc0002a3180, 0xc0000ae020, 0x3, 0x3, 0xc00004a010)
	/home/circleci/project/project/command/apply.go:203 +0xe7c
github.com/mitchellh/cli.(*CLI).Run(0xc00047a280, 0xc00047a280, 0xc00051fd90, 0x1)
	/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:251 +0xc8a
main.realMain(0x0)
	/home/circleci/project/project/main.go:106 +0xb4
main.main()
	/home/circleci/project/project/main.go:42 +0x3b

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ranjeetpatilnetsec** [comment] 2020-08-11 18:54
looks like tf was down. plan apply went through issue can be resolved for now.

**Comment by danieldreier** [comment] 2020-08-11 18:57
@ranjeetpatilnetsec thank you for reporting this! If you're trying to reach Terraform Cloud support, the best way to reach them is to email tf-cloud@hashicorp.support - this is the open source issue tracker, and so since you're a Terraform Cloud user you're entitled to reach out to them directly and get commercial support. This GitHub issue tracker is for the open source Terraform product.

If you prefer to work with support, please email them, close this issue, and link them to this issue so they can reference it. They will work with you to generate a reproduction case and then escalate this issue internally.

If you prefer to work with us directly, be aware that it's not covered by normal support turnaround times, but we are happy to work with you and generate a reproduction case.

**Closed** 2020-08-20 12:56 UTC
Labels: backend/remote, bug, waiting for reproduction
