### ISSUE TITLE
[data] Passing computed data to a provider

### ISSUE THREAD

**Issue by Zevran** [hashicorp/terraform#12410] opened 2017-03-03 14:27 UTC
Hi,

I would like to fetch vault secrets and pass them to the cloudflare provider on the fly but the cloudflare provider retrieve empty secrets from state which is the correct behavior by the way because vault provider hasn't finished.

Is there a way to do this ? Or do I have to fetch cloudflare credentials via environnement variables ?

```hcl
provider "vault" {
  address = "https://vault.internal.lan:443"
}

data "vault_generic_secret" "cloudflare" {
  path = "secret/internal/production/cloudflare"
}

provider "cloudflare" {
  email = "${data.vault_generic_secret.cloudflare.data.email}"
  token = "${data.vault_generic_secret.cloudflare.data.api_key}"
}
```

Thanks

**Comment by mcanevet** [comment] 2017-03-03 14:29
Same problem as here I think : https://github.com/hashicorp/terraform/issues/11264

**Comment by paddyforan** [comment] 2017-03-03 21:55
Hey @Zevran, just in the interest of keeping things centralised, I'm going to close this as a duplicate of #11264. Feel free to follow along there! But thanks for reporting an issue, and please do keep us informed of any bugs you run into.

**Closed by paddyforan** 2017-03-03 21:55 UTC
Labels: bug, core
