### ISSUE TITLE
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by AlexPolonskiy** [hashicorp/terraform#33058] opened 2023-04-20 13:25 UTC
### Terraform Version

```shell
v1.4.0
```

### Terraform Configuration Files

```
provider "aws" {
  region = var.region
  assume_role {
    role_arn = local.role
  }
}

terraform {
  required_version = ">= 1.4.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.57.1"
    }
  }
}

data "aws_lb" "cc_public_alb" {
  name = "${local.short_region}-${local.alb_current_environment}-cc-hub-public-alb"
}

resource "aws_shield_protection" "public_api_shield_protection" {
  name         = "${local.short_region}-${var.account} Shield for Public APIs"
  resource_arn = data.aws_lb.cc_public_alb.arn
}

resource "aws_route53_health_check" "customer_mw_health_check" {
  fqdn              = local.customer_mw_record
  resource_path     = "/health"
  port              = 443
  type              = "HTTPS_STR_MATCH"
  failure_threshold = "1"
  request_interval  = "30"
  search_string     = "UP"

  # Only deploy to the following 3 regions to narrow the scope of the AWS ranges we allow through WAF
  regions = [
    "us-east-1",
    "us-west-1",
    "us-west-2"
  ]
}

resource "aws_route53_health_check" "share_health_check" {
  fqdn              = local.share_record
  resource_path     = "/health"
  port              = 443
  type              = "HTTPS_STR_MATCH"
  failure_threshold = "1"
  request_interval  = "30"
  search_string     = "UP"

  # Only deploy to the following 3 regions to narrow the scope of the AWS ranges we allow through WAF
  regions = [
    "us-east-1",
    "us-west-1",
    "us-west-2"
  ]
}

resource "aws_route53_health_check" "edge_api_health_check" {
  fqdn              = local.edge_api_record
  resource_path     = "/health"
  port              = 443
  type              = "HTTPS_STR_MATCH"
  failure_threshold = "1"
  request_interval  = "30"
  search_string     = "UP"

  # Only deploy to the following 3 regions to narrow the scope of the AWS ranges we allow through WAF
  regions = [
    "us-east-1",
    "us-west-1",
    "us-west-2"
  ]

}

resource "aws_route53_health_check" "public_api_shield_health_check" {
  type                   = "CALCULATED"
  child_health_threshold = 3

  child_healthchecks = [
    aws_route53_health_check.customer_mw_health_check.id,
    aws_route53_health_check.share_health_check.id,
    aws_route53_health_check.edge_api_health_check.id
  ]
}

resource "aws_shield_protection_health_check_association" "cc_api_shield_health_check_association" {
  health_check_arn     = aws_route53_health_check.public_api_shield_health_check.arn
  shield_protection_id = aws_shield_protection.public_api_shield_protection.id
}

```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
runtime error: invalid memory address or nil pointer dereference
goroutine 43 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
	/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000411860, {0x2ccf8f8, 0xc0001c90[80](https://gitlab.getty.cloud/media-services/infrastructure/custom-content/cc-ecs/-/jobs/10510099#L80)}, {0x2ccf8f8, 0xc0001c9100}, 0xc0008a65a0, 0xc0001c[90](https://gitlab.getty.cloud/media-services/infrastructure/custom-content/cc-ecs/-/jobs/10510099#L90)40)
	/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a

### Expected Behavior

Terraform plan should work fine

### Actual Behavior

Terraform plan failed

### Steps to Reproduce

terraform init
terraform apply

**Comment by liamcervante** [comment] 2023-04-20 14:49
Hi @AlexPolonskiy, thanks for filing this!

Could you try this config with a newer version of Terraform? I think this is a duplicate of https://github.com/hashicorp/terraform/issues/32810 which was fixed in v1.4.1.

I'm going to close this issue as a duplicate, but if you can replicate this in a later version of Terraform then feel free to reopen it and we can investigate.

Thanks again!

**Closed by liamcervante** 2023-04-20 14:49 UTC
Labels: bug, new
