### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by adamgotterer** [hashicorp/terraform#8870] opened 2016-09-15 21:52 UTC
### Terraform Version
0.7.3, same problem happened on 0.7.0

### Affected Resource(s)
Please list the resources as a list, for example:
- core

### Terraform Configuration Files

```hcl
# variables.tf
variable "public_subnets" {
  description = "Comma separated list of public subnets inside the VPC."
  type = "map"
  default = {
    us-east-1a = "10.0.96.0/19"
    us-east-1b = "10.0.128.0/19"
    us-east-1c = "10.0.160.0/19"
  }
}
```

```hcl
# main.tf
resource "aws_subnet" "public" {
  vpc_id = "${aws_vpc.default.id}"

  # !!!!!!!!! This appears to be the line that caused the panic
  cidr_block = "${var.public_subnets[element(keys(var.public_subnets), count.index)]}"
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  availability_zone = "${element(keys(var.public_subnets), count.index)}"
  count = "${length(keys(var.public_subnets))}"
}
```

### Debug Output
https://gist.github.com/adamgotterer/16d875a3d4ebcd07ce42cdd8fdc32efa

### Panic Output
https://gist.github.com/adamgotterer/54b8aca8c70f46419970cfafbc1cbcf6

### Expected Behavior
The goal was to be able to convert the public_subnet keys to a list and loop over them to access each of the values so that I didn't need to store a separate list of the keys.

It does appear that the following will work:

```hcl
cidr_block = "${lookup(var.public_subnets, element(keys(var.public_subnets), count.index))}"
```

### Actual Behavior
Panic!

**Comment by jbardin** [comment] 2016-10-12 21:35
Look like #9282was a duplicate of this, which was just fixed.

**Closed by jbardin** 2016-10-12 21:35 UTC
Labels: bug, core, crash
