### ISSUE TITLE
darwin/arm64 build

### ISSUE THREAD

**Issue by dansimau** [hashicorp/terraform#27257] opened 2020-12-11 11:14 UTC
I didn't see an existing issue, so I thought I'd open an issue to track building an arm64 (Apple Silicon) binary for macOS.

After migrating to a new Mac, I have seen at least one issue using Terraform almost straight away:

```
module.certs_us-east-1["wildcard"].aws_acm_certificate_validation.validation: Still creating... [35m27s elapsed]
module.certs["wildcard"].aws_acm_certificate_validation.validation: Still creating... [34m57s elapsed]
module.certs_us-east-1["wildcard"].aws_acm_certificate_validation.validation: Still creating... [35m37s elapsed]
module.certs["wildcard"].aws_acm_certificate_validation.validation: Still creating... [35m7s elapsed]

assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1053794d8 abi_kind=6 emulation_interval=[0x105464e60,0x105464e74) instruction_interval=[0x105464e4c, 0x105464e74) x86_rip=0x106148c
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)


^C
```

(CTRL-C did not kill it; when I killed the provider processes they became zombies; I had to SIGKILL the main terraform process.)

### Current Terraform Version

```
Terraform v0.14.2
```

### References

* https://github.com/golang/go/issues/38485 (will at least require Go build support for darwin/arm64)

**Comment by apparentlymart** [comment] 2020-12-11 20:17
Hi @dansimau! Thanks for raising this.

There are some things that must happen before we could produce official Terraform releases on arm64 macOS, or before such releases would be practically useful:

* The Go toolchain we use must have production-quality support for that platform. Based on available information, it seems that Go 1.15 (our current version) has only early, experimental support, and that full support is expected in Go 1.16 which is not due until February.
* We will need to acquire hardware with the new CPU in order to verify that all of the platform features we depend on are available in Go's new port to the platform.
* At least the most commonly-used Terraform providers must have at least one release that supports this platform, so that Terraform will be able to install and run those plugins. (A Terraform executable without any provider plugins is not useful.)

    The provider development teams are also constrained by the availability of a suitable Go toolchain and hardware, so they will probably also only be able to do make experimental efforts until Go 1.16 is released, in which case there will be some lag after the Go 1.16 releaase before sufficient providers are available.
* Our policy for Go language upgrades is that we only accept patch-level upgrades in minor releases, and so the earliest we would adopt Go 1.16 is in the forthcoming v0.15 release. Given that the dependencies here include releases of several other pieces of software, it seems that we should not assume that everything lands in the correct order for macOS arm64 support to necessarily be included in v0.15, but it seems like that's the _earliest_ release where we could support it.

Given that Apple's strategy for gradual ecosystem migration is emulation, I feel optimistic that problems in the current version of the emulation layer will be gradually addressed as the Apple team becomes aware of the problems, so hopefully future updates to the arm64 version of macOS will address the problems that are currently causing the assertion failure you saw. We'll monitor Go releases to see if there are any minor release updates to Go 1.15 that might be issued to improve compatibility with Apple's emulator when running x86_64 binaries, in which case we may be able to include them in v0.14.x minor releases.

**Comment by dansimau** [comment] 2020-12-11 21:40
Makes sense.

After using it a bit more, I have concluded that Terraform is basically unusable under emulation on macOS arm64 (Big Sur 11.01).

Here are a sample of some more errors I have been getting:

```
$ terraform import module.auth.aws_security_group.presignup-lambda sg-XXX
module.auth.aws_security_group.presignup-lambda: Importing from ID "sg-XXX"...
module.auth.aws_security_group.presignup-lambda: Import prepared!
  Prepared aws_security_group for import
module.auth.aws_security_group.presignup-lambda: Refreshing state... [id=sg-XXX]

^C
^C^C^C
^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

(Eventually I killed the provider processes).

```
$ terraform import module.auth.aws_iam_role.presignup-lambda cognito-presignup-lambda

Error: Could not load plugin


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to retrieve schema from provider "registry.terraform.io/hashicorp/aws":
rpc error: code = Unavailable desc = connection error: desc = "transport:
authentication handshake failed: context deadline exceeded"
```

(Is the second time I have had to reinit).

```
$ terraform apply

Error: timeout while waiting for plugin to start


assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x104d204d8 abi_kind=6 emulation_interval=[0x104d77908,0x104d7791c) instruction_interval=[0x104d778f4, 0x104d7791c) x86_rip=0x4044049
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)
```

At the moment it's roughly a coin toss as to whether a command will work or not.

**Comment by danieldreier** [comment] 2020-12-15 23:54
@dansimau as it happens, I just got a an M1 Macbook, so I'm able to reproduce this. I did a state import of a security group, and it worked perfectly for me. However, I have my shell set to run under emulation by default, and when I use the default shell, I (on one run, haven't been able to reproduce since then) see the same behavior as you where it hangs waiting for the plugin to start.

Can you try running a shell under rosetta with a command like `arch -x86_64 bash` and then re-run these commands to see if the issue you're seeing still happens running in an emulated shell?

**Comment by dansimau** [comment] 2020-12-16 05:41
@danieldreier I was already running an x86_64 bash (v5), because I was using `/usr/local/bin/bash` from Homebrew that was copied over after running Migration Assistant.

**Comment by dansimau** [comment] 2020-12-16 15:09
Just FWIW, another symptom:

<img width="362" alt="Screenshot 2020-12-16 at 15 57 15" src="https://user-images.githubusercontent.com/203031/102365199-91a4e500-3fb7-11eb-8a82-77b1613425a6.png">

I randomly opened Activity Monitor and found this provider process using 100% CPU. Not even sure where it came from because I stopped running Terraform locally (unless the vscode language server runs it?)

Anyway, I will update to macOS 11.1 and see if there is any change (there is at least [one report](https://github.com/Homebrew/homebrew-core/pull/66166#issuecomment-739258433) of Rosetta bug fixes in 11.1).

Side note, I had a lot of issues with other (non-Terraform) Go binaries compiled for darwin/x86_64 (e.g. my VSCode environment ground to a halt). I compiled Go HEAD for arm64, trashed my $GOHOME and reinstalled/recompiled everything. Now that environment is mostly working and stable (which is to be expected) with the notable exception of anything using cgo.

**Comment by tuannvm** [comment] 2020-12-17 09:06
@dansimau 

> Anyway, I will update to macOS 11.1 and see if there is any change (there is at least one report of Rosetta bug fixes in 11.1).

I had same problem when kubectl & terraform x86 went crazy and ate up a lot of CPU. But upgrade to macOS 11.1 fixed that.

**Comment by dansimau** [comment] 2020-12-17 16:00
Upgraded to 11.1 and it didn't change anything. The first time I ran Terraform it hung with the same symptoms (provider at ~100% CPU).

Here's a sample of the process:
https://gist.github.com/dansimau/b424531d9ad69acd1dcc08f2713341e0

**Comment by steveetm** [comment] 2020-12-18 09:25
For v0.12 users, `terraform plan -out` was crashing me as well but since 11.1 it is fixed.

**Comment by billinghamj** [comment] 2021-01-05 17:22
For anyone who just wants to get on with being able to do their job...

```
# on your Apple Silicon (/opt/homebrew) brew installation, _not_ your Intel (/var/local) brew installation
brew install --build-from-source terraform
```

Make sure your brew bin is in your PATH (e.g. `echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> $HOME/.zprofile`).

Make sure to restart your terminal if you've just changed your PATH or installed terraform to `/opt/homebrew`.

```
git clone https://github.com/hashicorp/terraform-provider-aws.git
cd terraform-provider-aws
git checkout v3.22.0
cd tools
go get -d github.com/pavius/impi/cmd/impi
cd ..
make tools
make build
```

Then copy from `$GOPATH/bin/terraform-provider-aws` to:

```
~/.terraform.d/plugins/registry.terraform.io/hashicorp/aws/3.22.0/darwin_arm64/terraform-provider-aws_v3.22.0_x5
```

Then back in your workspace:

```
rm .terraform.lock.hcl
terraform init
```

It should pick up the arm64 build from your global plugins (https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories)

**Comment by apparentlymart** [comment] 2021-01-05 18:10
The strategy of building the providers locally for unsupported architectures is certainly a possible workaround. Thanks for sharing the instructions, @billinghamj.

One thing I'd add here is that following your instructions exactly will cause the `.terraform.lock.hcl` file to _only_ contain the checksum for your local `darwin_arm64` build, which means that the configuration will therefore _only be usable on that platform: if you have coworkers using other platforms then the installation will fail because the packages for their platform won't be recorded in the lock file.

If you are in an environment where you need to mix both supported and unsupported platforms then probably the best approach would be to review the git diff created by that final `terraform init`, see which checksum it recorded in the lock file, and then `git revert .terraform.lock.hcl` before adding that new checksum _in addition to_ the "official" checksums Terraform learned from the upstream registry. If you commit that result to the repository then that should leave you in a state where both the official packages and your unofficial build are both acceptable.

---

Relatedly, I'm not sure if the local build process described here serves as a _reproducible build_ such that two different people running those steps on their own laptops would end up producing identical binaries. If not, you may run into similar trouble if you have multiple people in your environment that are using this new platform and creating their own builds. To mitigate that, you could produce one "official-within-my-company" build of the provider and share it with all users, thus causing everyone to agree on what the checksum ought to be.

**Comment by billinghamj** [comment] 2021-01-05 18:21
Yeah, in my case I'm just probably not going to commit the modified lock file, and we likely will just share the binaries between each other too.

**Comment by xiazemin** [comment] 2021-02-01 11:59
(pprof) top
assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x101ddf4d8 abi_kind=6 emulation_interval=[0x101e3cb64,0x101e3cb7c) instruction_interval=[0x101e3cb4c, 0x101e3cb7c) x86_rip=0x7fff20392ee4
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)

I have the same problem on mac M1

**Comment by brainstorm** [comment] 2021-02-12 05:27
Today on `master` (instead of the `git checkout v3.22.0`) the build breaks:

```shell
% make tools && make build
cd awsproviderlint && GO111MODULE=on go install .
cd tools && GO111MODULE=on go install github.com/bflad/tfproviderdocs
cd tools && GO111MODULE=on go install github.com/client9/misspell/cmd/misspell
cd tools && GO111MODULE=on go install github.com/golangci/golangci-lint/cmd/golangci-lint
cd tools && GO111MODULE=on go install github.com/katbyte/terrafmt
../../../go/pkg/mod/github.com/hashicorp/terraform-exec@v0.12.0/tfinstall/download.go:12:2: missing go.sum entry for module providing package github.com/hashicorp/go-getter (imported by github.com/hashicorp/terraform-exec/tfinstall); to add:
	go get github.com/hashicorp/terraform-exec/tfinstall@v0.12.0
make: *** [tools] Error 1
```

But even with the local build described by @billinghamj in our environment there are at least 2 other providers requiring attention for the Apple Silicon M1 ("github" and "external" providers in our case):

```
% terraform init .

Initializing the backend...


Initializing provider plugins...
- Finding hashicorp/github versions matching "~> 3.0.0"...
- Finding hashicorp/aws versions matching "~> 3.22.0"...
- Finding latest version of hashicorp/external...
- Installing hashicorp/aws v3.22.0...
- Installed hashicorp/aws v3.22.0 (unauthenticated)

Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/hashicorp/github:
- For users on Terraform 0.13 or greater, this provider has moved to
integrations/github. Please update your source in required_providers.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/github v3.0.0 does not have a package
available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/external v2.0.0 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

So this port needs a concerted effort to test and CI as many plugins as possible for this to be usable in day-to-day devops tasks at this point in time, unfortunately :/

Does @hashicorp have some kind of (public) roadmap for this Apple M1 porting effort somewhere?

**Comment by billinghamj** [comment] 2021-02-12 08:09
I think it's really crazy that Hashicorp are refusing to touch this until Go 1.16 is released. The beta/RC is _drastically_ more stable than running TF in Rosetta, which is what thousands of engineers are now being forced to do.

Brew has already been distributing TF built with 1.16 for M1 and it works perfectly. I really don't think there's any excuse or justification for the current stance :\

**Comment by skyzyx** [comment] 2021-02-13 00:46
Since the providers all communicate with Terraform over gRPC, I anticipate (educated speculation) that Terraform core needs to go first (since everything is driven through that). As long as the other providers aren't _broken_ on arm64 and can run in Rosetta, it seems plausible that they could continue to work via Rosetta since CPU instructions wouldn't _directly_ affect gRPC communication between the provider and Core.

-----

Separately, @brainstorm wrote:

> Does @hashicorp have some kind of (public) roadmap for this Apple M1 porting effort somewhere other than the [Tracking] issues opened by @skyzyx?

I would **love** a centralized resource, but I don't think there's anything requiring Hashicorp to put it together. Any member of the community could put together a dashboard, and ask people to contribute the up-to-date information for the providers they care about. That's all that Hashicorp would be doing if they were to do it themselves, I suspect.

I started filing tickets for the providers I care about. There's nothing preventing others from doing the same and linking them together. I don't have the bandwidth at the moment to _lead_ such an effort, but I'd happily participate since I'm watching those providers pretty closely anyway.

**Comment by billinghamj** [comment] 2021-02-16 20:40
Go 1.16 is out now. Please could this be prioritised reasonably highly so providers can start accepting PRs etc to add arm support?

**Comment by skyzyx** [comment] 2021-02-16 21:04
> Go 1.16 is out now. Please could this be prioritised reasonably highly so providers can start accepting PRs etc to add arm support?

https://golang.org/doc/go1.16#darwin

**Comment by ameeno** [comment] 2021-02-17 23:10
right, so I followed the instructions above, and built 2 providers. that got me past the terraform init stage, but when I tried to terraform apply (using remote backend ) it gives me these errors.


```
Error while installing hashicorp/google v3.4.0: the current package for
registry.terraform.io/hashicorp/google 3.4.0 doesn't match any of the
checksums previously recorded in the dependency lock file


Error: Failed to install provider

Error while installing hashicorp/google-beta v3.5.0: the current package for
registry.terraform.io/hashicorp/google-beta 3.5.0 doesn't match any of the
checksums previously recorded in the dependency lock file```

**Comment by mprimeaux** [comment] 2021-02-18 02:54
Can confirm the same behavior as @ameeno 

```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of hashicorp/template from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file

Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.


Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/aws v3.27.0 does not have a package
available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

make: *** [init] Error 1
```

**Comment by apparentlymart** [comment] 2021-02-23 19:55
Hi all,

I gather that various provider teams at HashiCorp are independently working on building releases with Go 1.16 and then on including `darwin_arm64` support. Each provider is developed independently from the others and they all have other development priorities alongside supporting an entirely new target platform, so they will each get support asynchronously from one another in the near future. You can watch the release notes for the providers you use to see when they each have support. (A few already have compatible releases at the time I'm writing this.)

For Terraform CLI in particular (the only thing that this issue is able to cover directly, due to the other changes not being in the scope of this team), the timing worked out that Go 1.16 landed in time for Terraform v0.15 and so we're intending to ship the v0.15 line of releases with official builds against Go 1.16, and then we'll introduce official `darwin_arm64` releases in a later patch release once we've dealt with the various other bureaucracy required for a successful release (getting the new builds properly notarized so macOS will run them, getting necessary hardware to verify that things are actually working, etc, etc.)

We'll post here again once we have official `darwin_arm64` CLI binaries available. In the meantime, as the provider teams each get their own `darwin_arm64` releases published into the registry you'll find that you can use a locally-created build of Terraform CLI to install and run those, prior to an official Terraform CLI release.

**Comment by billinghamj** [comment] 2021-02-24 22:19
No real need to wait for v0.15 - Homebrew is already distributing `darwin/arm64` binaries on the latest 0.14 release, so as soon as the provider updates are released, it'll work

**Comment by billinghamj** [comment] 2021-02-24 22:39
Opened issues on all the providers we use, may be worth others doing the same. Will see if I can open PRs to kick off the process for some of them

**Comment by ameeno** [comment] 2021-02-25 10:00
yes, well it works locally, but not remotely because, terraform cloud does not like the hash's of self-built providers.

despite tf cloud running on a Linux ubuntu instance, for some reason it cares about the hash's of the providers on my local machine/git repo, that’s really weird huh?

**Comment by billinghamj** [comment] 2021-02-25 10:02
@ameeno Can you include the hashes of both the normal amd64 binaries and your local ones? I'd expect it should work then?

**Comment by ameeno** [comment] 2021-02-25 10:45
Hiya, I don’t really have amd64 providers on my darwin_arm64 machine,

**Comment by billinghamj** [comment] 2021-02-25 11:08
You should be able to get them pretty easily by installing terraform with intel-brew (good to alias as ibrew) then running `/usr/local/bin terraform init`

**Comment by ameeno** [comment] 2021-02-25 11:18
@billinghamj Thanks for that, yes I do have two versions of brew installed (my alias is brewi). so I could do that.

Just seems a bit random that the hash's on a darwin_arm64 unmatching will kill a remote terraform deploy that uses amd64. and I need to have providers not built for my local architecture for remote terraform to do its job,

you would think to terraform remote would have its own providers built-in right?
I mean it does use the web interface.

Once again, thanks for letting me know about amd64 brew in rosetta mode. Actually, honestly, my initial journey on this project involved a rosetta emulated terraform with amd64 providers, but I found it slow and clunky.

The whole point of using arm64_darwin (self-compiled) was to speed up the terraform experience locally.

My intention in contributing to this thread was to let everyone know that even with a remote terraform backend from a local machine if the arm64 hash's don't match the terraform cloud hash table, we get an error.

this should not be the case :)
Thanks again!

**Comment by dimitribrooks** [comment] 2021-02-26 04:31
[v3.30.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.30.0) is out and solved this issue for me! Thank you!

**Comment by lordz-md** [comment] 2021-03-21 15:10
Any chance we will have older builds for like 0.13 or 0.12 for Apple Silicon? Some of us are still locked to those versions but already got M1 based laptops.

**Comment by billinghamj** [comment] 2021-03-21 18:16
Then Rosetta is for you. Support almost certainly won't be backported.

**Comment by billinghamj** [comment] 2021-03-22 18:40
All the k8s-related providers seem to be sorted now

**Comment by yi2020** [comment] 2021-04-14 16:29
@apparentlymart v0.15 just came out but seems to not be using Go 1.16 still?

**Comment by billinghamj** [comment] 2021-04-14 17:21
@yi2020 appears they switched to Go 1.16 in this commit, which is included in the v0.15.0 tag - https://github.com/hashicorp/terraform/commit/e3abe9020d0982c7df30f2f276b157f117bf3992

**Comment by yi2020** [comment] 2021-04-14 17:27
@billinghamj the [go.mod](https://github.com/hashicorp/terraform/blob/main/go.mod) is still using 1.14 though?

**Comment by apparentlymart** [comment] 2021-04-14 17:36
The entry in `go.mod` specifies which version of the Go language Terraform is targeting, not which version of the Go toolchain it's built with. The `.go-version` file is what defines the toolchain version we use for building the release binaries.

The `go` directive in `go.mod` remains a bit hypothetical at this point, but the intent of it is to potentially allow later versions of the Go language to include minor breaking changes that individual modules can opt in to, while allowing other modules in the same program to remain on the old version of the language. But the Go team also tries very hard to avoid breaking changes that would need that, so it hasn't come up a lot so far and, as a result, we don't tend to pay much attention to that entry in our `go.mod` right now.

**Comment by yi2020** [comment] 2021-04-14 18:08
Ah that makes sense. So I'll go ahead and build it now on my own. Do you expect you guys to add it to the [releases directory](https://releases.hashicorp.com/terraform/0.15.0/) anytime soon?

**Comment by apparentlymart** [comment] 2021-04-14 23:20
Due to the requirement that the macOS builds be notarized via HashiCorp's Apple developer credentials that our team doesn't have direct access to, we're relying on support from a centralized release engineering team to add this new platform to the release pipeline. Their schedule is not under our direct control, so I can't say with any certainty when we'll be able to get that included, but on the plus side it's a process step common to all HashiCorp products distributed in this way so I expect that the approach for one will be the approach for all, once it's designed, and there are similar requests pending from all of the other product teams too.

If all of the providers you intend to use have `darwin_arm64` releases available by now though, indeed you can use your own build from the relevant tag in this repository to get a similar effect to what we'd release officially. (The provider teams have been able to get these new packages in place sooner because provider plugins are run only indirectly via Terraform and so they are not subject to the macOS notarization requirement.)

**Comment by billinghamj** [comment] 2021-04-15 07:13
It's available on brew already too: https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb

So don't really need to wait for Hashicorp to post arm64 builds if you don't want

**Comment by andig** [comment] 2021-04-15 07:51
Imho we do need to wait (or compile) since this will require the notarized plugins which are not available yet.

**Comment by billinghamj** [comment] 2021-04-15 10:26
@andig The plugins work fine with the brew version already - they have been working great for a couple of months now, and @apparentlymart seems to have indicated that the plugins do not need to be notarized.

**Comment by andig** [comment] 2021-04-15 10:46
@billinghamj as far as I understand terraform will need to download providers that match the architecture. For that purpose it is not sufficient to have a brew arm64 binary:

```
❯ file $(which terraform)
/opt/homebrew/bin/terraform: Mach-O 64-bit executable arm64

❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/google from the dependency lock file

Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/google v3.61.0 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

**Comment by Tenzer** [comment] 2021-04-15 11:27
I have hacked together a quick way to check which versions of a provider support macOS on arm64:
```bash
PROVIDER="hashicorp/google"
curl --silent https://registry.terraform.io/v1/providers/${PROVIDER}/versions | jq -r '.versions[] | select(.platforms[] | contains({os: "darwin", arch: "arm64"})) | .version'
```
the above would for instance output:
```
3.63.0
3.64.0
```

I haven't found any other obvious way of detecting which platforms each provider version are available as, so this could be handy for figuring out when all the providers you use are available for arm64.

**Comment by billinghamj** [comment] 2021-04-15 11:33
@andig Yeah that's right. A _lot_ of providers have already published arm64/darwin binaries, but indeed some have not yet. It looks like hashicorp/google does as of v3.63.0 though.

But either way, notarization does not appear to be required for plugins - just updating to Go 1.16

**Comment by anthonynsimon** [comment] 2021-04-22 18:53
For those encountering this issue with `hashicorp/template` (I know it's deprecated but some providers depend on it internally):

```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
```

Here's a workaround to run it on darwin/arm64:

- Clone the repo: https://github.com/hashicorp/terraform-provider-template
- Build from source (eg. `go build`).
- Move the resulting binary to the global terraform plugins path: `mv <binary-path> ~/.terraform.d/plugins/registry.terraform.io/hashicorp/template/2.2.0/darwin_arm64/terraform-provider-template_v2.2.0_x5`
-  Give it exec permissions (eg. `chmod +x <path>`).
- Then just do terraform init.

Hope it helps.

**Comment by abhishek-galoda** [comment] 2021-05-14 12:49
> For those encountering this issue with `hashicorp/template` (I know it's deprecated but some providers depend on it internally):
> 
> ```
> │ Error: Incompatible provider version
> │ 
> │ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
> │ 
> ```
> 
> Here's a workaround to run it on darwin/arm64:
> 
> * Clone the repo: https://github.com/hashicorp/terraform-provider-template
> * Build from source (eg. `go build`).
> * Move the resulting binary to the global terraform plugins path: `mv <resulting-binary-path> ~/.terraform.d/plugins/registry.terraform.io/hashicorp/template/2.2.0/darwin_arm64/terraform-provider-template_v2.2.0_x5`
> * Give it exec permissions (eg. `chmod +x <binary-path-above>`).
> * Then just do `terraform init` back in your repo.
> 
> Hope it helps.

Work or me only when file copied to ~/.terraform.d/plugins/registry.terraform.io/hashicorp/template/2.2.0/darwin_arm64/

**Comment by Junkern** [comment] 2021-06-25 12:34
I am working in a lot of different Terraform projects and many of them have pinned providers version to old version. So either they are pre-darwn/arm64 or don't have a pre-compiled binary. After following the workarounds manually every time I decided to write a small CLI to handle all the details: https://github.com/kreuzwerker/m1-terraform-provider-helper

Hope this of help to anyone!

**Comment by apparentlymart** [comment] 2021-07-07 18:31
Hi all,

Terraform v1.0.2 is the first release to include an official build for macOS on arm64.

We've not yet added this new platform to [our supported platforms in the v1.0 compatibility promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html#supported-platforms). Although we have tested this build on our own systems and believe it to work correctly, we'd like to let this new version soak for a release or two before we commit to compatibility with it in the same sense as we have for the other supported platforms, just in case we learn from feedback that something isn't behaving in an ideal way and thus we may need to make adjustments to some details.

With that said, we don't have any specific plans to change or remove that release in the future, and so this is still an official release that we recommend for use, since our testing suggests that it is functioning correctly. We intend to add it as a fully-supported platform in the near future.

If you try it and run into strange behaviors that you didn't previously see with the macOS amd64 releases then please open a new GitHub issue about that and let us know.

The supported platforms for individual providers are decided by the teams who release those providers and so we (the Terraform Core team) can't promise that all providers you use will have matching support for `darwin_arm64` (the internal name for the "macOS on arm64" platform). If you find that a provider you depend on doesn't yet have a `darwin_arm64` release, or if you are not yet ready to upgrade to a newer version that supports that platform, we recommend registering a feature request in the repository for the relevant provider (which you can locate via its entry in [Terraform Registry](https://registry.terraform.io/browse/providers)) and then continue to use the `darwin_amd64` build of Terraform through Apple's official emulation layer until support is available in all of the providers you need.

Thanks for your patience while we worked through getting this implemented. Properly supporting a new platform is not a trivial matter but fortunately it's a relatively rare event! Again, please open a new bug report issue if you encounter problems with the new build, so that we can investigate each distinct problem separately.

**Closed by apparentlymart** 2021-07-07 18:31 UTC
Labels: build, enhancement
