### ISSUE TITLE
Crash when running terraform plan using Docker provider

### ISSUE THREAD

**Issue by inokappa** [hashicorp/terraform#2330] opened 2015-06-13 02:37 UTC
Hi.

When running terraform plan using Docker provider, terraform crashes with the error noted at the following. 

```
(snip)
2015/06/13 02:19:08 terraform-provider-docker:  /opt/gopath/src/github.com/hashicorp/terraform/rpc/server.go:146 +0x1f9
2015/06/13 02:19:08 terraform-provider-docker: github.com/hashicorp/terraform/rpc.func・001()
2015/06/13 02:19:08 terraform-provider-docker:  /opt/gopath/src/github.com/hashicorp/terraform/rpc/server.go:102 +0x265
2015/06/13 02:19:08 terraform-provider-docker: created by github.com/hashicorp/terraform/rpc.(*dispenseServer).ResourceProvider
2015/06/13 02:19:08 terraform-provider-docker:  /opt/gopath/src/github.com/hashicorp/terraform/rpc/server.go:103 +0x107
2015/06/13 02:19:08 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [unexpected EOF]
2015/06/13 02:19:08 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [unexpected EOF]
2015/06/13 02:19:08 [ERROR] root: eval: *terraform.EvalOpFilter, err: Warnings: []. Errors: [unexpected EOF]
2015/06/13 02:19:08 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [unexpected EOF]
2015/06/13 02:19:08 waiting for all plugin processes to complete...
2015/06/13 02:19:08 [DEBUG] /home/vagrant/dev/terraform/terraform-provider-docker: plugin process exited
```
Upload Crashlog to Gist: https://gist.github.com/inokappa/8a5cb324d6bee7662a01

I has just added the following configuration to `ports` resource:

```
# Create a container
resource "docker_container" "foo" {
    image = "${docker_image.centos.centos6}"
    name = "foo"
    command = ["python", "-m", "SimpleHTTPServer", "8888"]
    ports = ["8888"]
}

resource "docker_image" "centos" {
    name = "centos:centos6"
}
```

terraform version:

```
$ terraform version
Terraform v0.5.3
```

Plase confirm.
Thank you.

**Comment by mitchellh** [comment] 2015-06-27 17:51
This is fixed on master. This is caused by an invalid type in the config which we now validate.

**Closed by mitchellh** 2015-06-27 17:51 UTC
Labels: bug, crash, provider/docker
