### ISSUE TITLE
data in module dependencies

### ISSUE THREAD

**Issue by jle35** [hashicorp/terraform#25636] opened 2020-07-22 04:16 UTC
### Terraform Version

```
Terraform v0.13.0-beta3
+ provider registry.terraform.io/hashicorp/google v3.31.0
+ provider registry.terraform.io/hashicorp/google-beta v3.31.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/terraform-providers/postgresql v1.7.0
```

### Terraform Configuration Files

```terraform
module "vpc" {
  source  = "terraform-google-modules/network/google"
  version = "~> 2.3"

  network_name            = "network"
  project_id              = "myproject"
  routing_mode            = "GLOBAL"
  auto_create_subnetworks = true

  subnets = []
}

module "private_service_access" {
  source      = "GoogleCloudPlatform/sql-db/google//modules/private_service_access"
  version     = "3.2.0"
  project_id  = "myproject"
  vpc_network = module.vpc.network_name
}

```

#### private_service_access module

```terraform
data "google_compute_network" "main" {
  name    = var.vpc_network
  project = var.project_id

}

resource "google_compute_global_address" "google-managed-services-range" {
  provider      = google-beta
  project       = var.project_id
  name          = "google-managed-services-${var.vpc_network}"
  purpose       = "VPC_PEERING"
  address       = var.address
  prefix_length = var.prefix_length
  ip_version    = var.ip_version
  labels        = var.labels
  address_type  = "INTERNAL"
  network       = data.google_compute_network.main.self_link
}

# Creates the peering with the producer network.
resource "google_service_networking_connection" "private_service_access" {
  provider                = google-beta
  network                 = data.google_compute_network.main.self_link
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.google-managed-services-range.name]
}
```

### Debug Output

https://gist.github.com/jle35/3920caeb5ff33e53b7ad38634f94b720
### Expected Behavior
apply working

### Actual Behavior
```
Error: "network": required field is not set

  on .terraform/modules/private_service_access/terraform-google-sql-db-3.2.0/modules/private_service_access/main.tf line 41, in resource "google_service_networking_connection" "private_service_access":
  41: resource "google_service_networking_connection" "private_service_access" {
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Hello,
I can make it working by removing `data "google_compute_network" "main" {.. ` and pass directly the network self_link to the module.
I make a lot of destroy/apply, sometimes it is working..

**Comment by jbardin** [comment] 2020-07-23 16:57
Hi @jle35,

You normally would not use a data source to look up resource which you just created, and use the attributes of those resources directly. Since `data.google_compute_network.main` appears to be here only to lookup the identifier of the vpc network you just created, I would expect the `network_self_link` output from the module itself would be the correct way to configure this.

Since the `name` parameter is defined statically in the configuration (you supplied it as `network_name`), there's nothing to indicate that the data source needs to wait until the resource is created to find the correct network. Normally this would result in an error in the data source, but it's possible there's a bug in that particular data source, or there some eventually consistency timing issues that cause the `self_link` to be empty with no error.

If you can reproduce from the start with a new network name, it may be an issue to file with the google provider.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by jbardin** 2020-07-23 16:57 UTC
