### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by const-tmp** [hashicorp/terraform#32507] opened 2023-01-13 11:34 UTC
### Terraform Version

```shell
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/consul v2.17.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
+ provider registry.terraform.io/hashicorp/nomad v1.4.19
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/vault v3.12.0
+ provider registry.terraform.io/tenstad/remote v0.1.1
+ provider registry.terraform.io/vultr/vultr v2.12.0
```

### Terraform Configuration Files

```#root module
...
module "consul_agent_vault" {
  source             = "./modules/consul/client"
  node_name          = "consul-agent-vault"
  private_ip         = vultr_instance.vault_server.internal_ip
  public_ip          = vultr_instance.vault_server.main_ip
  retry_join         = [vultr_instance.consul_server.internal_ip]
  consul_token       = data.vault_generic_secret.vault-consul-agent-token.data.token
}

data "vault_generic_secret" "vault-consul-agent-token" {
  depends_on = [module.vault_consul_acl]

  path = "consul/creds/${module.vault_consul_acl.roles.consul-server.name}"
}
...
#modules/consul/client
locals {
  consul_client_config = templatefile("${path.root}/config/consul/client.hcl",
    {
      node_name    = var.node_name
      private_ip   = var.private_ip
      retry_join   = var.retry_join
      consul_token = var.consul_token
    }
  )
}

resource "null_resource" "configure_consul_client" {
  triggers = {
    consul_client_config = local.consul_client_config
  }

  connection {
    type  = "ssh"
    host  = var.public_ip
    user  = "root"
    agent = true
  }

  provisioner "file" {
    content     = local.consul_client_config
    destination = "/etc/consul.d/consul.hcl"
  }
  provisioner "remote-exec" {
    inline = [
      "systemctl daemon-reload",
      "systemctl enable consul.service",
      "systemctl restart consul.service",
    ]
  }
}

```

### Debug Output

https://gist.github.com/nullc4t/fa4523b1a1846324396bfb370606ad80

### Expected Behavior

module should render config template, provide it via ssh and restart service

### Actual Behavior

terraform crashed

### Steps to Reproduce

1. terraform init
2. terraform apply

### Additional Context

Mac OS 13.0.1 
local backend

**Comment by jbardin** [comment] 2023-01-13 18:34
Hi @nullc4t,

Thanks for filing the issue. I think we may need a little more context to try and sort this out, so you think you could reduce this to minimal, reproducible example? I'm not sure yet how `local.consul_client_config` successfully evaluated the `templatefile`, but we somehow ended up with `content` being `null` in the provisioner configuration.

**Comment by nullc4t** [comment] 2023-01-13 20:28
Unfortunately I tried to make reproduction stand, but crash disappeared

**Comment by crw** [comment] 2024-07-01 18:41
Closing due to lack of reproduction. If something similar comes up in the future, please file a new issue. Thanks!

**Closed by crw** 2024-07-01 18:41 UTC
Labels: bug, provisioner/file, waiting for reproduction, v1.3
