### ISSUE TITLE
Terraform 0.14 dependency lock file unusable because of platform mismatch

### ISSUE THREAD

**Issue by Nosmoht** [hashicorp/terraform#27135] opened 2020-12-04 08:15 UTC
We develop Terraform code mainly on Mac OSX but execute it on Linux systems, therefore provider hashes written to `.terraform.lock.hcl` do not match. Because of this, every Pipeline fails with error message `doesn't match any of the checksums
previously recorded in the dependency lock file`.

### Terraform Version

```
Terraform v0.14.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "= 3.0.0"
    }
  }
  required_version = ">= 0.14"
}

resource "null_resource" "test" {}
```

### Debug Output

Provider hash for `null` provider on Mac OSX
```
provider "registry.terraform.io/hashicorp/null" {
  version     = "3.0.0"
  constraints = "3.0.0"
  hashes = [
    "h1:V1tzrSG6t3e7zWvUwRbGbhsWU2Jd/anrJpOl9XM+R/8=",
  ]
}
```
Provider hash for `null` provider on amd64 Linux system
```
provider "registry.terraform.io/hashicorp/null" {
  version     = "3.0.0"
  constraints = "3.0.0"
  hashes = [
    "h1:ysHGBhBNkIiJLEpthB/IVCLpA1Qoncp3KbCTFGFZTO0=",
    "zh:05fb7eab469324c97e9b73a61d2ece6f91de4e9b493e573bfeda0f2077bc3a4c",
    "zh:1688aa91885a395c4ae67636d411475d0b831e422e005dcf02eedacaafac3bb4",
    "zh:24a0b1292e3a474f57c483a7a4512d797e041bc9c2fbaac42fe12e86a7fb5a3c",
    "zh:2fc951bd0d1b9b23427acc93be09b6909d72871e464088171da60fbee4fdde03",
    "zh:6db825759425599a326385a68acc6be2d9ba0d7d6ef587191d0cdc6daef9ac63",
    "zh:85985763d02618993c32c294072cc6ec51f1692b803cb506fcfedca9d40eaec9",
    "zh:a53186599c57058be1509f904da512342cfdc5d808efdaf02dec15f0f3cb039a",
    "zh:c2e07b49b6efa676bdc7b00c06333ea1792a983a5720f9e2233db27323d2707c",
    "zh:cdc8fe1096103cf5374751e2e8408ec4abd2eb67d5a1c5151fe2c7ecfd525bef",
    "zh:dbdef21df0c012b0d08776f3d4f34eb0f2f229adfde07ff252a119e52c0f65b7",
  ]
}
```

### Expected Behavior

Pipeline does not fail as `.terraform.lock.hcl` contains hashes of the provider for all supported platforms (?)
### Actual Behavior

Pipeline fails on any system other than Mac OSX as provider hashes do not match
### Steps to Reproduce

- Take provided config file
- Run `terraform init` on OSX
- Checkin `.terraform.lock.hcl`
- Checkout the same code on Linux system (or any other)
- Execute `terraform plan`

**Comment by slessardjr** [comment] 2020-12-04 09:37
Use the following command on the directory to generate the lockfile for all platforms. See this documented [here](https://www.terraform.io/docs/commands/providers/lock.html#specifying-target-platforms)

terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64

**Comment by Nosmoht** [comment] 2020-12-04 10:01
Thanks @slessardjr , i didn't saw this.

**Comment by pkolyvas** [comment] 2020-12-04 13:59
@slessardjr - thanks for linking to the docs!

I'm going to close this as a dupe of #27141

Here's a link to Martin's comment in the above issue with some additional explanation: https://github.com/hashicorp/terraform/issues/26901#issuecomment-726447429

**Closed by pkolyvas** 2020-12-04 13:59 UTC
Labels: bug, new

**Comment by shamil** [comment] 2020-12-13 12:14
Same as for @Nosmoht , if I've `TF_PLUGIN_CACHE_DIR`, then lock file populated only with single hash.
But having `TF_PLUGIN_CACHE_DIR` unset causing plugins to be re-downloaded each time I run `init`.

**Comment by pdecat** [comment] 2020-12-14 09:08
@pkolyvas Is setting `TF_PLUGIN_CACHE_DIR` the real cause of the lock file being created with only a single hash ? Is this expected or is this a bug? The documentation does not mention this.

**Comment by pdecat** [comment] 2020-12-14 09:52
If I understand the comment [here](https://github.com/hashicorp/terraform/commit/b3f5c7f1e649def9b4b1fce51a7a4d4b0da91d4b#diff-385ff28969dc6410989718822b4c24e033e3a10d679bdd792fd2d55148c49471R358-R368):

> 					// NOTE: The behavior here is unfortunate when a particular
>					// provider version was already cached on the first time
>					// the current configuration requested it, because that
>					// means we don't currently get the opportunity to fetch
>					// and verify the checksums for the new package from
>					// upstream. That's currently unavoidable because upstream
>					// checksums are in the "ziphash" format and so we can't
>					// verify them against our cache directory's unpacked
>					// packages: we'd need to go fetch the package from the
>					// origin and compare against it, which would defeat the
>					// purpose of the global cache.

Maybe the underlying issue is caused by a pre-filled cache when the lock file was created?
