### ISSUE TITLE
aws_instance cloud-init mutipart encoding, etc. issues.

### ISSUE THREAD

**Issue by ohlol** [hashicorp/terraform#4794] opened 2016-01-22 00:22 UTC
The docs specify that base64_encode is optional for `template_cloudinit_config`, but user_data seems to get encoded automatically in `aws_instance` (https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L356)

It also seems to get compressed without `gzip` parameter, but I'm not sure where that is happening.

Regardless of these, I am having problems using this resource: https://gist.github.com/ohlol/133fa79539c7d40c7adc

If I use `template_file` directly in the aws_instance resource, cloud-init works fine. Any time I use `template_cloudinit_config` as the value for `user_data` in `aws_instance`, it fails with the error shown in the gist.

**Comment by jen20** [comment] 2016-01-25 16:57
Hi @ohlol, thanks for opening the issue. It does appear there is a problem here. My feeling is that we should _not_ automatically encode the user data as base 64 on `aws_instance`, and instead allow people to use the `base64encode` interpolation function if they need to. The issue here is that this will break backwards compatibility. Any thoughts @catsby?

**Comment by martonpe** [comment] 2016-01-29 16:55
There is also something else fishy in `template_cloudinit_config`. 
Here's what happened: When updating an existing instance with regular user data to multipart user data cloud-init failed with the same error @ohlol mentions. But then changing around the `gzip` and `base64_encode` parameters and re-applying at some point it simply succeeded. He are the steps I took:

* existing instance with regular user data
* `gzip = true`, `base64_encode=false` cloud-init FAILS
* `gzip = true`, `base64_encode=true` cloud-init FAILS
* `gzip = false`, `base64_encode=false` terraform FAILS because of size limit
* `gzip = true`, `base64_encode=false` cloud-init SUCCEEDS

My code: https://gist.github.com/martonpe/659898d6e6d0fa4b7e7a

I have a feeling that terraform somehow doesn't always set the metadata for cloud-init correctly based on the current state of terraform.tfstate. Or maybe it has something to do with the resources having the same name?

I'll try to do some more testing and will post an update.

**Comment by boyand** [comment] 2016-03-10 15:04
@martonpe did you manage to get to the bottom of this. We are seeing very similar behaviour where gzipped userdata sporadically fails

**Comment by martonpe** [comment] 2016-03-10 15:47
@boyand not really. I ended up going with another solution to reduce the cloud-init config size.

**Comment by dougneal** [comment] 2016-04-11 16:26
I'm also experiencing some strange behaviour here. Under certain conditions, instances receive corrupt user data. I've been able to reproduce this under the following conditions:

1. Set `gzip=true` and `base64_encode=false`, and run `terraform apply`. The instance receives correct user-data and cloud-init succeeds.
2. Run `terraform apply` again. Terraform wrongly detects that the user-data needs to change, and destroys and reprovisions the instance. This time, the user-data is corrupt and cloud-init fails with a message like this:

```
2016-04-11 15:57:29,435 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'b'\\x1f\\\\ufffd\\x08\\x00\\x00\\tn\\\\ufffd\\x00\\\\ufff'...'
```

A comparison of the gzipped, rendered template in the statefile shows that between step 1 and 2, the encoding of the binary data within the JSON has changed. It seems as though some double-encoding has taken place somewhere, or perhaps the data has been wrongly decoded and re-encoded somewhere along the line, resulting in a corruption.

**Comment by boyand** [comment] 2016-04-12 09:57
This was exactly the behaviour I am seeing as well.

**Comment by martonpe** [comment] 2016-04-12 10:38
Yes, describes my experience very well too.

**Comment by dougneal** [comment] 2016-04-12 13:17
I believe I've isolated the source of this bug. As I suspected, it's due to bad decoding when unmarshalling the gzipped data from the JSON statefile.

On the first run, Terraform generates the gzipped data correctly and submits it to EC2, and also saves it to the statefile, using `json.MarshalIndent`. This escapes the binary data as unicode escape strings. On the subsequent runs, Terraform unmarshals the data in the statefile. The JSON library will only unmarshal a string, rather than a bytestream, and applies Unicode validation to it, this is documented [here|https://golang.org/pkg/encoding/json/#Unmarshal|]:

```
When unmarshaling quoted strings, invalid UTF-8 or invalid UTF-16 surrogate pairs are not treated as an error. Instead, they are replaced by the Unicode replacement character U+FFFD.
```

This process corrupts the bytestream, as we are dealing with a gzip file, not a Unicode string.

I've put together a gist demonstrating this: https://gist.github.com/dougneal/8fdc86516a76b69a51aa33fcadc4fdd1

**Comment by dougneal** [comment] 2016-04-12 13:51
Additionally, switching on `base64_encode` causes a different mode of failure. Although that neatly avoids the unmarshalling problem (and honestly I don't see a way round that; json isn't for storing raw binaries), the file lands on the EC2 instance *in its base64 encoded state*, meaning that it is double-base64 encoded on the way to EC2, as you can see [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L967) - the encoding is indiscriminate:

```
opts.UserData64 = aws.String(base64.StdEncoding.EncodeToString([]byte(d.Get("user_data").(string))))
```

IMHO a fix for this would be to:
* Disallow the combo of `gzip=true` and `base64_encode=false` as there is no way to safely record the state
* In `resource_aws_instance`, check whether the userdata is already base64 encoded, and pass it through as-is if so.

**Comment by dougneal** [comment] 2016-04-12 16:13
The changes in the linked PR are providing an adequate workaround for me at the moment.

**Comment by catsby** [comment] 2016-04-13 15:21
I just merged #6140 as a partial fix here, what issues remain here?

**Comment by dougneal** [comment] 2016-04-13 15:53
Thanks for the merge @catsby. The remaining issue is that the combination of `base64_enable=false` and `gzip=true` results in the binary gzip data being encoded into the JSON statefile in a way that it corrupts when read back out again.

**Comment by dougneal** [comment] 2016-04-13 15:58
Also not sure if this is exactly the same issue as @ohlol's bug report that I've kinda hijacked :)

**Comment by ohlol** [comment] 2016-04-13 16:04
@dougneal @catsby I'm no longer with my previous employer so unfortunately I have no way to verify that this fixes my problem :(

Feel free to close or address otherwise as you feel necessary!

**Comment by kwilczynski** [comment] 2016-05-31 09:26
I have stumbled into the same issue.

**Closed** 2017-06-13 14:53 UTC
Labels: bug, provider/template

**Comment by JimiHFord** [comment] 2018-02-20 16:44
In case other people make the same mistake I did, you get a very similar warning if you forget to start your userdata script with

`#!/usr/bin/env bash`

[documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html#amazon-linux-cloud-init)

That is, of course, only if it is a script and not something like cloud config yaml. I'm not sure what happens in that case but I imagine you would get a similar (unhelpful) warning like this.
