### ISSUE TITLE
diff produced when using `--var-file` and tfvars, auto.tfvars

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform#18748] opened 2018-08-27 22:47 UTC
### Terraform Version
```
Terraform v0.11.7
+ provider.acme v1.0.0
+ provider.aws v1.27.0
+ provider.chef v0.1.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0
+ provider.tls v1.1.0
```

### Terraform Configuration Files
environment.tfvars
```hcl
chef = {
  env = "kamehameha"
}
```
user.auto.tfvars
```hcl
acme = {
  bool = true
}

chef = {
  key  = "~/.chef/_chef_user_.pem"
  user = "_chef_user_"
}

instance = {
  user = "_ssh_user_"
}

rhn = {
  user = "_rhn_user_"
  pass = "_rhn_pass_"
}
```

### Debug Output

- https://gist.github.com/mengesb/d5a48e710663905e4b11b7c82b53416c
- environment_user_tfvars_stderr.log is when i used the environment tfvars and user auto tfvars during plan
- only_auto_tfvars_stderr.log is when i had just the user auto tfvars

The difference is that I pulled out of the user's auto.tfvars file the `chef["env"]` var into it's own tfvars file.

If I specified one file via `--var-file`, I had to specify ALL files.. I had expected the `___.auto.tfvars` file to ALWAYS be picked up.

### Crash Output
N/A

### Expected Behavior
No diff should be reported

### Actual Behavior
Says it would create several resources which already exist

### Steps to Reproduce
1. Create plan
2. Create some `___.auto.tfvars` file with information
3. `terraform init`
4. `terraform apply`
5. Create some `___.tfvars` file with information pulled out of the `___.auto.tfvars` file
6. `terraform plan --var-file ___.tfvars` # <-- fails
7. `terraform plan --var-file ___.auto.tfvars --var-file ___.tfvars` # order doesn't matter
8. diff presented

The only way I can get no diff to show up is if all settings are in either the auto.tfvars or just the tfvars file.

### Additional Context
What I'm trying to do is provide a place where the user-specific content can be placed in a non-committed `auto.tfvars` file for the user, and that each workspace will have the workspace defined non-sensitive information in the `_environment_.tfvars` file to be included in the terraform run. As I understood the `auto.tfvars` setup, it automatically loads those settings, and load is based on file name or system sorting. I don't have conflicts in var settings, however I am setting various maps in different files.

### References
N/A

**Comment by mengesb** [comment] 2018-08-29 18:43
While investigating, I used a different variable -- basically avoiding map merging.

I created a `var.environment` variable which is the only thing in my tfvars file (safe to commit) which doesn't present a complicate with map merging. This results in no diff and expected behavior

**Comment by mildwonkey** [comment] 2018-08-31 21:49
Hi @mengesb, I'm sorry you've run into this confusing behavior. Thanks for reporting it.

I'm going to edit the title of issue to clarify a bit, but please comment if you feel I'm on the wrong track. 

It can also be reproduced by passing a variable: `terraform plan -var 'chef = { env = "kamehameha" }'`
I'll dig into whether this is expected behavior (and our documentation is misleading) or a bug.

**Comment by mengesb** [comment] 2018-09-06 03:40
You're correct. When I'm meeting on the map variable using more than one method of specifying portions of the same map I get terraform reporting a diff.

Any updates?

**Comment by mildwonkey** [comment] 2018-09-06 16:00
Yes! Thanks for reminding me, @mengesb.

This is indeed by design: 

The [apply documentation](https://www.terraform.io/docs/commands/apply.html#var-file-foo) that explicitly states any variable passed in as a `-var-file` or `-var` will override *any* variable from a file.

You and I both found spots in the documentation that made this a bit unclear, so I will flag this as a documentation issue and see if I can grab a few examples of pages where this could be called out much more explicitly. 

Having said that, this is an interesting and specific use-case where you want all the values - those in the auto-loaded files and those passed on the CLI -  _merged_ into the map variable, so I'm also going to tag this as an enhancement that we can revisit. I'm not sure what this might look like; an off-the-cuff idea is a CLI flag that indicates that you'd like variables merged (though, again, that puts the responsibility on the user running `terraform`).

**Comment by mengesb** [comment] 2018-09-06 21:29
I was hoping that override meant it overrides instances that collide, not obliterate the whole data structure in favor of the last incoming data structure.

My interpretation of the documentation is that:
1. Load variables (i.e. variables.tf)
2. Load `terraform.tfvars` if exist
3. Load `*.auto.tfvars` if exist | sort alphabetically
4. Load any `--var-file` in order of argument specified
5. Load any `--var` in order of argument specified

At any point, I had expected that the load wouldn't destroy the data object... such that disparate or even conflicting parts of a map would all be written to complete the whole map

I had expected...
```hcl
variable "chef" {
  default = {
    key1 = "value1"
    key2 = ""
    key3 = "value3"
```
environment.tfvars
```hcl
chef = {
  key2 = "value2"
}
```
user.auto.tfvars
```hcl
chef = {
  key1 = "my_value_1"
}
```
to result in
```hcl
chef = {
  key1 = "my_value_1"
  key2 = "value2"
  key3 = "value3"
}
```

when i run something such as `teraform apply --var-file environment.tfvars` (note not specifying the auto.tfvars because it's suppose to "automatically" load - fails currently RE: item 6 in issue) ; specifying the auto.tfvars file results in the diff ... which baffles me.  theoretically i should be able to use `--var` as well in conjunction but it appears the map is not merging even with 1 overridden key

**Comment by dbilleci-lightstream** [comment] 2018-11-01 20:47
Definitely seems to be a regression issue, just ran into it.  Working code on 0.11.7 no longer works on 0.11.9 due to the auto inclusion of an auto.tfvars file not being read.

Reverting to 0.11.7 fixed it with no other changes.  Haven't tested on latest 0.11.10 yet tho.

**Comment by raymondhoagland** [comment] 2019-03-14 21:13
This definitely seems unclear, I'd expect it to work the same as terraform.tfvars (and other automatically loaded var files) by just merging maps.  What appears to be happening instead is that it will merge the map as specified from the var-file and from variables.tf, while ignoring any changes terraform.tfvars tries to make.

**Comment by mildwonkey** [comment] 2021-07-07 15:28
hi @laurapacilio ! 
The [documentation on input variables](https://www.terraform.io/docs/language/values/variables.html) has changed a lot since this issue was initially opened, so I think it's good to close! We can always open a new issue if something comes up.

**Closed by mildwonkey** 2021-07-07 15:28 UTC
Labels: cli, documentation, enhancement
