### ISSUE TITLE
coalesce not behaving as expected 

### ISSUE THREAD

**Issue by antonosmond** [hashicorp/terraform#16399] opened 2017-10-19 16:10 UTC
### Terraform Version
Terraform v0.10.7

##### MODULE
```hcl
variable "root_domain" {
  default = ""
}

variable "root_domain_account_id" {
  default = ""
}

variable "domain" {}

variable "vpc_id" {
  default = ""
}

variable "tags" {
  default = {}
}

data "aws_caller_identity" "current" {}

data "aws_region" "current" {
  current = true
}

data "aws_route53_zone" "root" {
  count    = "${var.root_domain != "" ? 1 : 0}"
  provider = "aws.root"
  name     = "${var.root_domain}"
}

provider "aws" {
  alias  = "root"
  region = "${data.aws_region.current.name}"

  assume_role {
    role_arn = "arn:aws:iam::${coalesce(var.root_domain_account_id, data.aws_caller_identity.current.accound_id)}:role/terraform"
  }
}

resource "aws_route53_zone" "domain" {
  name   = "${var.domain}"
  vpc_id = "${var.vpc_id}"
  tags   = "${var.tags}"
}

resource "aws_route53_record" "subdomain" {
  count    = "${var.root_domain != "" ? 1 : 0}"
  provider = "aws.root"
  zone_id  = "${data.aws_route53_zone.root.zone_id}"
  name     = "${var.domain}"
  type     = "NS"
  ttl      = "60"
  records  = ["${aws_route53_zone.domain.name_servers}"]
}
```

##### CONSUMER
```
provider "aws" {
  region = "eu-west-1"
}

module "dns_external_zone" {
  source                 = "./dns"
  root_domain            = "mydomain.com"
  root_domain_account_id = "999999999999"
  domain                 = "test.mydomain.com"

  tags {
    environment = "test"
  }
}
```

### Expected Behavior
`coalesce` takes the first non-empty value, in this case, `var.root_domain_account_id`.

### Actual Behavior
It appears to be using `data.aws_caller_identity.current.accound_id` in the provider, despite the fact I'm passing the `root_domain_account_id` to the module.

I expected this to work, however it fails saying `no matching Route53Zone found`, which is because it's using the wrong account ID in the provider due to `coalesce` not behaving as expected. You can prove this by removing the coalesce in the provider in the module and just leaving `var.root_domain_account_id`. Without changing the consumer of the module, when I run a plan, it works and can find the hosted zone. Then I put the coalesce back and run a plan and it fails and can't find the hosted zone. 

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by nathanielks** [comment] 2017-11-29 03:43
I'm experiencing the same issue, but with DB Parameter Groups. I've imported an existing subnet group and have the module set up to create a name if one isn't provided. I'm passing the name of the parameter group directly, but it's still attempting to create a new resource.

```
resource "random_id" "subnet_group" {
  prefix = "${var.name}-${var.environment}-"

  keepers = {
    name        = "${var.name}"
    environment = "${var.environment}"
  }

  byte_length = 4
}

resource "aws_db_subnet_group" "mod" {
  name        = "${coalesce(var.subnet_group_name, random_id.subnet_group.hex)}"
  description = "DB Subnet Group"
  subnet_ids  = ["${var.subnets}"]

  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by mildwonkey** [comment] 2019-04-12 16:40
Hi all,
I'm sorry to those who experienced this issue. I recently did some work on the `coalesce` function and, since I was in the area, tried to reproduce this. I was not able to. It's possible that the issue has been fixed since this was opened, so I will close it.

Having said that, if anyone is still (or newly) experiencing a problem, please open a new issue and fully fill out the issue template so that we can reproduce and fix. Thank you!

**Closed by mildwonkey** 2019-04-12 16:40 UTC
Labels: bug, config
