### ISSUE TITLE
Module executing before parent

### ISSUE THREAD

**Issue by wv-cfromm** [hashicorp/terraform#12585] opened 2017-03-10 14:20 UTC
OK.  I've got a pretty recurrent problem and I cannot determine a solution.  Have a pretty modular codebase that uses alot on consul kv variable, and I keep randomly running into circumstances where the module executes before its "dependencies".  So in the example below the server module executes and there is no VPC created, and then it just gets errors.    The snippet below is not a functional example.

```
resource "aws_vpc" "default" {
    cidr_block = "${data.consul_keys.vpc.var.vpc_cidr}"
    enable_dns_hostnames = true
   
}

resource "aws_subnet" "tier1" {
    vpc_id = "${aws_vpc.default.id}"
    count = 2
    cidr_block = "${cidrsubnet(data.consul_keys.vpc.var.vpc_cidr, 5, count.index+2)}"
    availability_zone = "${data.aws_availability_zones.available.names[count.index %2]}"
   
}


data "consul_keys" "vpc" {
    key {
        name = "vpc_cidr"
        path = "environments/${var.environment}/vpc_cidr"
    }
}

module "server" {
    source  = "../../resources/server"
    tier1_az1 = "${aws_subnet.tier1.0.id}"
    tier1_az2 = "${aws_subnet.tier1.1.id}"
}

```
In this latest attempt to solve, I've added the variable references to the module to try and help the graph.  This gets the error "Resource 'aws_subnet.tier1' not found for variable 'aws_subnet.tier1.1.id' .  Which makes no sense, as the resource is there.  They just must not be planned yet, so they don't have the indexes.

How can I make it process in order?  What am I missing?  Wish I could use depends_on inside of module declaration.

**Comment by wv-cfromm** [comment] 2017-03-23 19:47
I was able to work around by passing indexed as a splat list.  

`module "server" {
    source  = "../../resources/server"
    subnets = ["${aws_subnet.tier1.*.id}"]
}`

**Comment by apparentlymart** [comment] 2017-03-29 23:05
Hi @wv-cfromm! Sorry for the weirdness here, and sorry for taking a while to respond.

I've been trying to reproduce this problem but I can't seem to get my local terraform to do what you described here. So I can continue investigating, some more information would be really helpful:

* What version of Terraform are you running? (The output of `terraform version` is helpful)
* What is the output from `terraform graph`? (Make sure there's nothing sensitive/secret in there)
* What log output do you get if you run `TF_LOG=debug terraform plan`? This will probably be long, so it's best to paste it into a [gist](https://gist.github.com/) and share the link here. (Again, make sure there's nothing sensitive in there)

**Comment by apparentlymart** [comment] 2017-05-02 23:00
Since we weren't able to reproduce this, I'm going to close it. Thanks for reporting this, though!

**Closed by apparentlymart** 2017-05-02 23:00 UTC
Labels: bug, core, waiting-response
