### ISSUE TITLE
Unable to terraform init into terraform modules through gitlab-CI

### ISSUE THREAD

**Issue by vdoodala** [hashicorp/terraform#17878] opened 2018-04-16 22:12 UTC
I am unable to terraform init into terraform module present in another Gitlab repo.

Error code : 
 /usr/bin/git exited with 128: Cloning into '.terraform/modules/0d181246ac803d764c3d413281cee529'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR: Job failed: exit code 1

**Comment by apparentlymart** [comment] 2018-04-16 23:12
Hi @vdoodala,

It sounds like you don't have the gitlab server's host key cached in `~/.ssh/known_hosts`. You should be able to fix this by directly running `ssh` with the same username and hostname given in the git URL, which will cause the SSH client to prompt you to confirm the key fingerprint before writing it to the known hosts file.

**Comment by shederman** [comment] 2018-08-04 21:28
I am getting this same issue. In my case I can confirm that it seems to be because terraform is not correctly handling subdirectories with bitbucket private repos. Specifically:

```
module "my_module" {
  source = "git::git@bitbucket.org:myorg/my_module.git//module_subdir"
}
```

Fails with

```
Error downloading modules: Error loading modules: error downloading 'file:///Users/me/Projects/project/terraform/global/git@bitbucket.org:myorg/my_module.git': /usr/local/bin/git exited with 128: Cloning into '.terraform/modules/8d77758e4649016d7e37a29f0e6e3a7b'...
fatal: '/Users/sean/Projects/zilch/project/global/git@bitbucket.org:my_org/my_module.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

If I run `git clone git@bitbucket.org:my_org/my_module.git//module_subdir`

I get

```
Cloning into 'module_subdir'...
repository does not exist.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The exact same error.

If I run `git clone git@bitbucket.org:my_org/my_module.git`

I get

```
Cloning into 'my_module'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 17 (delta 4), reused 0 (delta 0)
Receiving objects: 100% (17/17), done.
Resolving deltas: 100% (4/4), done.
```

**Comment by mildwonkey** [comment] 2018-08-06 16:52
@shederman: one other thing you might want to check is how the github credentials are configured on the machine that clone is running on. Terraform will automatically use a configured SSH key, but if you are using a username and password for github credentials that must be manually configured (hard-coded in the module source): https://www.terraform.io/docs/modules/sources.html#private-github-repos

**Comment by dimisjim** [comment] 2019-05-20 07:53
@mildwonkey Having this issue as well.

Git terraform modules work fine outside of our gitlab pipeline.

Have also verified that I can successfully clone the very same repo in the before_script section, but still getting 128 when terraform tries to clone.

Here's the gist containing my pipeline output:https://gist.github.com/dimisjim/73c2f802dd0a9a63f23fabb51b96c359

**Comment by shederman** [comment] 2019-05-30 06:10
@mildwonkey we use Bitbucket with SSO, and terraform just does not appear able to handle that scenario

**Comment by edlevin6612** [comment] 2019-06-11 17:28
Ran into this issue as well since our modules are sourced from Gitlab by Terraform via ssh. Solved by:

1. Follow instructions to pass ssh keys to your executor via ssh agent: https://docs.gitlab.com/ee/ci/ssh_keys/
2. Don't forget the step about host key verification! This held me back until I correctly added entries to `~/.ssh/known_hosts`
https://docs.gitlab.com/ee/ci/ssh_keys/#verifying-the-ssh-host-keys

**Comment by teamterraform** [comment] 2019-08-13 15:50
Hi all!

I see at least two distinct problems being discussed here.

One is about the SSH host keys as @apparentlymart mentioned earlier, and which others have shared solutions for.

The other is about source address strings referring to bitbucket:

```
module "my_module" {
  source = "git::git@bitbucket.org:myorg/my_module.git//module_subdir"
}
```

There were some changes to Terraform's address parsing in later releases to address some ambiguities caused by accepting both the scp-style (as above) address form and the URL-style address form, both of which are accepted by `git`. The above should hopefully work in the latest version of Terraform, but if not we'd suggest changing it to the URL-like form, which is the more general form:

```
module "my_module" {
  source = "git::ssh://git@bitbucket.org/myorg/my_module.git//module_subdir"
}
```

Note that in this case the hostname and the path are separated by a slash rather than by a colon, because in a URL the colon signals the start of a port number.

It doesn't seem like there's any specific Terraform change required here, so we're going to close this out. If you have any follow-up questions, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core).

**Closed by teamterraform** 2019-08-13 15:50 UTC
Labels: question
