### ISSUE TITLE
Fileset Function does not correctly identified files when the not match attribute is applied

### ISSUE THREAD

**Issue by confusdcodr** [hashicorp/terraform#24220] opened 2020-02-26 14:36 UTC
### Terraform Version
```
Terraform v0.12.21
```

### Expected Behavior
The fileset function correctly identifies all files and files within subdirectories when the `**` pattern is utilized. It should continue to identify all of the files outside of those that start with the specified character when `[^.]**` is applied

### Actual Behavior
When `[.]**` is applied, it only looks at the files within the current directory. It ignores any files that may exist within a subdirectory. 

### Steps to Reproduce
1. `terraform console`
2. `fileset("./", "[^.]**")`

**Comment by apparentlymart** [comment] 2020-06-19 01:38
Hi @confusdcodr! Thanks for reporting this.

Terraform's `fileset` function is mainly just a thin wrapper around the upstream library [`doublestar`](https://github.com/bmatcuk/doublestar), and so its behavior is whatever that library implements. To change this behavior then, it would be necessary to get the change merged upstream. It's possible that the behavior you want has been implemented in the meantime since the version of `doublestar` Terraform is using (v1.1.5), in which case we could get it just by upgrading.

However, before pursuing that any further I'd like to confirm exactly what you expected a pattern like `[.]**` to do. I need to refer to a working minimum reproduction case that I can run locally on my own machine (so I can test it against different versions of `doublestar`), along with the output you saw when you ran it _and_ the output you expected to see. For this case, that could take the form of an example directory structure you want to run `fileset("./", "[.]**")` against, along with the exact output you saw when you tried it and the output you expected to see.

Whether we will be able to implement the behavior you are requesting will depend on whether the `doublestar` maintainer agrees that it is a correct result. If not, the outcome of this issue will be to update the `fileset` function documentation to more accurately describe the `doublestar` library's behavior.

Thanks!

**Comment by confusdcodr** [comment] 2020-06-19 20:02
@apparentlymart - thank you for responding to this issue. 

Lets say I start with this directory tree as seen below. The directory has 3 terraform files (main.tf, variables.tf, and outputs.tf) along with a hidden file `.secrets.json`. There is also a subdirectory with the same exact files within it. 
.
+-- .secrets.json
+-- main.tf
+-- outputs.tf
+-- subdir
│   +-- .secrets.json
│   +-- main.tf
│   +-- outputs.tf
│   \-- variables.tf
\-- variables.tf

When I use `fileset("./", "**")` from within terraform console I get the output as seen below. As you can see, the output includes the hidden files that start with a `.`. This is what I expect.
[
  ".secrets.json",
  ".terraform.tfstate.lock.info",
  "main.tf",
  "outputs.tf",
  "subdir/.secrets.json",
  "subdir/main.tf",
  "subdir/outputs.tf",
  "subdir/variables.tf",
  "terraform.tfstate",
  "variables.tf",
]

When I change the command to be `fileset("./", "[^.]**")` I expect to get the same results as before but without the hidden files. Instead, I only get the data from within the current directory. The command should continue to grab the data from the subdirectory
[
  "main.tf",
  "outputs.tf",
  "terraform.tfstate",
  "variables.tf",
]

**Comment by apparentlymart** [comment] 2020-06-29 17:27
Thanks for that extra context, @confusdcodr!

I recreated your data structure and then put the following in the `outputs.tf` just so I'd be able to test more easily:

```hcl
output "all_files" {
  value = fileset("./", "**")
}

output "filtered_files_1" {
  value = fileset("./", "[^.]**")
}

output "filtered_files_2" {
  value = fileset("./", "**/[^.]*")
}

output "filtered_files_3" {
  value = fileset("./", "[^.]**/[^.]*")
}

output "filtered_files_4" {
  value = setunion(
    fileset("./", "[^.]**"),
    fileset("./", "[^.]**/[^.]*"),
  )
}
```

These are the output values I got from applying the above:

```
all_files = [
  ".secrets.json",
  ".terraform.tfstate.lock.info",
  ".terraform/modules/modules.json",
  ".terraform/plugins/selections.json",
  "main.tf",
  "outputs.tf",
  "subdir/.secrets.json",
  "subdir/main.tf",
  "subdir/outputs.tf",
  "subdir/variables.tf",
  "terraform.tfstate",
  "terraform.tfstate.backup",
  "variables.tf",
]
filtered_files_1 = [
  "main.tf",
  "outputs.tf",
  "terraform.tfstate",
  "terraform.tfstate.backup",
  "variables.tf",
]
filtered_files_2 = [
  ".terraform/modules/modules.json",
  ".terraform/plugins/selections.json",
  "main.tf",
  "outputs.tf",
  "subdir/main.tf",
  "subdir/outputs.tf",
  "subdir/variables.tf",
  "terraform.tfstate",
  "terraform.tfstate.backup",
  "variables.tf",
]
filtered_files_3 = [
  "subdir/main.tf",
  "subdir/outputs.tf",
  "subdir/variables.tf",
]
filtered_files_4 = [
  "main.tf",
  "outputs.tf",
  "subdir/main.tf",
  "subdir/outputs.tf",
  "subdir/variables.tf",
  "terraform.tfstate",
  "terraform.tfstate.backup",
  "variables.tf",
]
```

I also tried upgrading to doublestar v1.3.1, which is the latest tagged version at the time I'm writing this, and got exactly the same results.

Looking again at the doublestar documentation I see the following in its readme:

> Note that the doublestar must appear as a path component by itself. A pattern such as `/path**` is invalid and will be treated the same as `/path*`, but `/path*/**` should achieve the desired result. Additionally, `/path/**` will match all directories and files under the path directory, but `/path/**/` will only match directories.

This paragraph seems to suggest that the behavior we're observing is the intended behavior: `[^.]**` would, per the above rule, be interpreted the same as `[^.]*`, and that seems to match the result of `filtered_files_1` in my outputs above, which is the pattern you tried for.

It doesn't seem to be possible to get the particular result you were looking for with `doublestar`'s current design. Although my `filtered_files_4` did get the result you requested by using `setunion` to combine to other results, I believe that has only worked because there's only one subdirectory nesting level. If `subdir` itself had a directory inside it then its contents would not be included in `filtered_files_4`.

Given the above, I think one outcome of this issue should be to add a similar paragraph to the one I quoted from doublestar's readme to the documentation for Terraform's `fileset`, to be explicit that `**` is only allowed as a component by itself.

It could also be interesting to raise this use-case upstream in the doublestar repository and see if the doublestar maintainers can either suggest a different formulation that gets the desired result or if they would consider extending the pattern language to meet this use-case.

**Comment by apparentlymart** [comment] 2020-09-29 21:48
In the interests of making this issue be something with a clear definition of "done", let's consider it to represent updating the documentation for `fileset` to include the same information as the underlying `doublestar` docs about the behavior of `**` when not used as an isolated path segment.

Looking again at the `doublestar` repository, I see bmatcuk/doublestar#7 where the author seems to be inviting feedback on how the library ought to behave when `**` is used as only part of a path segment, so if anyone reading this issue would like to pursue this further I'd suggest opening an upstream issue describing the same use-case we discussed here, and then if that discussion leads to a change in `doublestar` we can have a separate Terraform issue to represent incorporating that functionality into Terraform's `fileset` function.

**Comment by lorengordon** [comment] 2020-09-29 22:01
@apparentlymart the workaround described in the upstream comment you provided earlier does seem to work fine...

> A pattern such as /path** is invalid and will be treated the same as /path*, but /path*/** should achieve the desired result

e.g. updating the example from the OP, this lists all non-hidden files in the current directory and subdirectories:
```
$ terraform console
> fileset("./", "[^.]*/**")
```

**Closed** 2021-07-15 16:22 UTC
Labels: bug, config, confirmed, documentation, explained, v0.12
