### ISSUE TITLE
Dynamic block gives unsupported attribute error in reference to local variable and each.key

### ISSUE THREAD

**Issue by CThompso3** [hashicorp/terraform#34646] opened 2024-02-09 18:03 UTC
### Terraform Version

```shell
Terraform v1.7.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.90.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90.0"
    }
  }

  required_version = ">= 1.1.0"
}

provider "azurerm" {
  features {}
}

variable "linux_java_app_services" {
  type = map(object({
    deny_public_access = bool
    deny_scm_public_access = bool
    java_server = string
    java_server_version = string
    java_version = string
    network_restrictions_azure_services = list(object({
      action = string
      is_frontend_rule = bool
      is_scm_rule = bool
      priority = number
      service = string
    }))
  }))
  default = {
    "app1" = {
      deny_public_access = true
      deny_scm_public_access = true
      java_server = "TOMCAT"
      java_server_version = "10.0"
      java_version = "17"
      network_restrictions_azure_services = [{
        action = "Allow"
        is_frontend_rule = false
        is_scm_rule = true
        priority = 100
        service = "AzureCloud"
      }]
    }
  }
}

locals {
  app_service_network_restrictions = {for key, value in var.linux_java_app_services : key => {
    scm_services = [for restriction in value.network_restrictions_azure_services : {
      action = restriction.action
      name = "${restriction.action} ${restriction.service}"
      priority = restriction.priority
      service_tag = restriction.service
    } if restriction.is_scm_rule]
  }}
}

resource "azurerm_linux_web_app" "linux_webapps" {
  for_each = var.linux_java_app_services
  name = "${each.key}"
  location = "East US"
  resource_group_name = "example001"
  service_plan_id = "FakeID"

  site_config {
    application_stack {
      java_server = each.value.java_server
      java_server_version = each.value.java_server_version
      java_version = each.value.java_version
    }
  
    dynamic ip_restriction {
      for_each = each.value.deny_public_access ? [1] : []
      content {
        action = "Deny"
        ip_address = "0.0.0.0/0"
        name = "Deny All"
        priority = 2147483647
      }
    }

    dynamic scm_ip_restriction {
      for_each = each.value.deny_scm_public_access ? [1] : []
      content {
        action = "Deny"
        ip_address = "0.0.0.0/0"
        name = "Deny All"
        priority = 2147483647
      }
    }

###
# Commenting out the block below will allow the code to validate
###
    dynamic "ip_restriction" {
      iterator = "subnet_rule"
      for_each = local.app_service_network_restrictions["${each.key}"].subnets
      content {
        action = subnet_rule.value.action
        name = subnet_rule.value.name
        priority = subnet_rule.value.priority
        virtual_network_subnet_id = subnet_rule.value.virtual_network_subnet_id
      }
    }
###
# End of problem block
###
  }
}

output "app_service_network_restrictions" {
  value = local.app_service_network_restrictions
}
```

### Debug Output

https://gist.github.com/CThompso3/98ea0c2e15801b1f5159a6fd983a515e

### Expected Behavior

Expect dynamic block to access local variable value based on the current key of the resource level `for_each` block.

### Actual Behavior

Validating and planning results in two "Unsupported attribute" errors indicating that the attributes do not exist. One for the local variable and one for the `each.key`.

```
│ Error: Unsupported attribute
│ 
│   on main.tf line 96, in resource "azurerm_linux_web_app" "linux_webapps":
│   96:       for_each = local.app_service_network_restrictions["${each.key}"].subnets
│ 
│ This object does not have an attribute named "app_service_network_restrictions".
╵
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 96, in resource "azurerm_linux_web_app" "linux_webapps":
│   96:       for_each = local.app_service_network_restrictions["${each.key}"].subnets
│ 
│ This object does not have an attribute named "key".
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### Additional Context

This is a far simpler example than the actual code I have, but produces the same error message. Commenting out the dynamic block in my code results in the code validating successfully and plans can then be built and applied.

I've attempted multiple ways to reference the local variable and the `each.key` for the resource level `for_each` in the dynamic block declaration with no success. `each.key` is used successfully elsewhere, and the output for the local variable shows it is generated as expected.

In my actual code, I have multiples of these dynamic blocks defined in an attempt to get around the required naming convention differences when setting `ip_restriction`s for `azurerm_linux_web_app`; however, I don't think this problem is directly connected to the provider.

If I'm missing something obvious, then I apologize, but I have struggled with this for over a day and am still unable to determine why Terraform thinks the attributes do not exist in this specific context.

Sample output of local variable
```
+ app_service_network_restrictions = {
  + app1 = {
      + scm_services = [
          + {
              + action      = "Allow"
              + name        = "Allow AzureCloud"
              + priority    = 100
              + service_tag = "AzureCloud"
            },
        ]
    }
}
```

**Comment by jbardin** [comment] 2024-02-09 18:13
Duplicate of #34188

**Closed by jbardin** 2024-02-09 18:13 UTC
Labels: bug, new

**Comment by CThompso3** [comment] 2024-02-09 19:20
Apologies, that issue did not come up when I searched.
That said...the error message is vastly misleading, and I hope that gets changed.
