### ISSUE TITLE
Loops are hiding errors that might have happened during resource creation

### ISSUE THREAD

**Issue by johnroach** [hashicorp/terraform#18602] opened 2018-08-03 19:19 UTC
Hi,

It looks to me that looping might hide resource creation errors. I talked to @paddycarver about this issue he believed this might be a terraform core issue.

### Terraform Version

```
Terraform v0.11.7
+ provider.github v1.1.0
+ provider.google v1.16.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
resource "google_service_account" "dev_db_dev_service_accounts" {
  count = "${length(data.github_team.devops_guild.members)}"
  account_id   = "dev-db-dev-${data.github_team.devops_guild.members[count.index]}-service-account"
  display_name = "Dev DB ${data.github_team.devops_guild.members[count.index]} Developer Service Account"
  project      = "${google_project.asurint_dev_db.project_id}"
}


output "dev_db_dev_service_accounts" {
  value = "${google_service_account.dev_db_dev_service_accounts.*.email}"
}
```

However, I kept getting the error as follows:

```
Error
• output.dev_db_dev_service_accounts: Resource 'google_service_account.dev_db_dev_service_accounts' does not have attribute 'email' for variable 'google_service_account.dev_db_dev_service_accounts.*.email'
```

During run, no other errors were shown and terraform didn't halt in the run until it reaches the output `dev_db_dev_service_accounts`.

### Debug Output
On closer inspection via debug turned out there were validation errors where the service account name was too long(above 28 characters):

```
2018-08-03T10:59:58.236-0400 [DEBUG] plugin.terraform-provider-google_v1.16.0_x4: 2018/08/03 10:59:58 [DEBUG] Instance Diff is nil in Diff()
2018/08/03 10:59:58 [TRACE] OrphanResourceCount: Starting...
2018/08/03 10:59:58 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["account_id" ("redacted-very-long-name") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"]
2018/08/03 10:59:58 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["account_id" ("redacted-very-long-name") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"]
2018/08/03 10:59:58 [TRACE] OrphanResourceCount: Checking: google_sql_database_instance.keystone01_db
2018/08/03 10:59:58 [TRACE] [walkPlan] Exiting eval tree: google_service_account.dev_db_dev_service_accounts[9]
2018/08/03 10:59:58 [TRACE] root: eval: *terraform.EvalSequence
2018/08/03 10:59:58 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["account_id" ("redacted-very-long-name") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"]
2018/08/03 10:59:58 [TRACE] root: eval: *terraform.EvalGetProvider
2018/08/03 10:59:58 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["account_id" ("redacted-very-long-name") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"]
2018/08/03 10:59:58 [TRACE] root: eval: *terraform.EvalCountCheckComputed
2018/08/03 10:59:58 [TRACE] root: eval: *terraform.EvalInterpolate
2018/08/03 10:59:58 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["account_id" ("redacted-very-long-name") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"]
```

### Crash Output

```
Error
• output.dev_db_dev_service_accounts: Resource 'google_service_account.dev_db_dev_service_accounts' does not have attribute 'email' for variable 'google_service_account.dev_db_dev_service_accounts.*.email'
```

### Expected Behavior

Error should have surfaced when creating resources.

### Actual Behavior

Error happens when showing output

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context
N/A

### References
N/A

**Comment by apparentlymart** [comment] 2018-11-01 00:19
Hi @johnroach! Sorry for this weird behavior, and for the slow response.

This seems to be the same root cause as #18129, so I'm going to close this one just to consolidate the discussion over there. Thanks for reporting this!

**Closed by apparentlymart** 2018-11-01 00:19 UTC
Labels: bug, config
