### ISSUE TITLE
Sensitive output for azure storage connection string has null value at json response

### ISSUE THREAD

**Issue by lemsy** [hashicorp/terraform#30995] opened 2022-05-04 14:07 UTC
I am triying to get the connection string of an azure storage resource as a sensitive output using this Terraform API endpoint `/workspaces/:workspace_id/current-state-version-outputs` (https://www.terraform.io/cloud-docs/api-docs/state-version-outputs),  but I always get null when I call it after applied the creation plan.

### Terraform Version

```
1.1.9
```

### Terraform Configuration Files

I defined the configuration for the resource and output as you can see below

```main.tf
...
resource "azurerm_storage_account" "app-storage" {
  ...
}
...
output "storage_connection_string" {
  value = azurerm_storage_account.app-storage.primary_connection_string
  sensitive = true
}

```

### Expected Behavior

I expected to get the connection string real value instead of null.

### Actual Behavior

I get this json response
```json
{"data":[...,
{"id":"wsout-qZmiHREtnfJcR544",
"type":"state-version-outputs",
"attributes":{"name":"storage_connection_string",
"sensitive":true,
"type":"string",
"value":null},
"links":{"self":"/api/v2/state-version-outputs/wsout-qZmiHREtnfJcR544"}}]}

```

### Additional Context

However, If I use the `nonsensitive` function (https://www.terraform.io/language/functions/nonsensitive), like in the example below, I get the connection string real value.

```terraform
output "storage_connection_string" {
  value = nonsensitive(azurerm_storage_account.app-storage.primary_connection_string)
}

```

**Comment by apparentlymart** [comment] 2022-05-05 13:35
Hi @lemsy! Thanks for reporting this.

I believe what you are describing is the intended behavior of the Terraform Cloud API: today it returns only the subset of output values that are not marked as sensitive, which is consistent with how the Terraform Cloud API typically treats sensitive values in other contexts.

Given that I'm going to reclassify this as a Terraform Cloud feature request, which I understand as you wanting a way to access the sensitive output values externally via the API, while still keeping the other meanings of marking sensitive such as not disclosing them in the normal UI.

On the surface this seems like a reasonable request to me because the meaning of an output being sensitive is that it should be hidden from casual inspection in the UI, not that it should not be retrievable at all. I suspect the current behavior might have emerged from the fact that the API endpoint you indicated is the one used by the Terraform Cloud web UI to show the output values onscreen, and so perhaps the requirement to hide them in that UI also got applied to the API which powers that UI. If that's true then this may require an additional opt-in argument to activate the behavior you are requesting, and perhaps it will require additional permissions on the workspace to do so. However, that will be for the Terraform Cloud teams to decide; I work primarily on open source Terraform and so I am not the one to rule on what the design requirements would be here.

The Terraform Cloud teams do not all routinely monitor the issues in this open source project, so you may wish to also send this request to Terraform Cloud support to help ensure it'll be on the Cloud teams' radars.

Thanks again!

**Comment by qwerty1979bg** [comment] 2022-05-06 16:44
Hi @lemsy,

I think the design decision behind "show state outputs" not showing the sensitive values is exactly what @apparentlymart said.

It is also stated in the [documentation](https://www.terraform.io/cloud-docs/api-docs/state-version-outputs#show-current-state-version-outputs-for-a-workspace):

> Note: Sensitive values are not revealed and will be returned as null. To fetch an output including sensitive values see [Show a State Version Output](https://www.terraform.io/cloud-docs/api-docs/state-version-outputs#show-a-state-version-output).

There is a separate API call that can be used to fetch a single output, that is marked as "sensitive":
https://www.terraform.io/cloud-docs/api-docs/state-version-outputs#show-a-state-version-output

Alternatively, you can use the [show a state version](https://www.terraform.io/cloud-docs/api-docs/state-versions#show-a-state-version) API call with [?include=outputs](https://www.terraform.io/cloud-docs/api-docs#inclusion-of-related-resources) to get all of the outputs in a single call.

I hope this information helps !

**Comment by lemsy** [comment] 2022-05-11 19:58
Hello @apparentlymart and @qwerty1979bg thanks for your comments.

After calling the first endpoint to get the state version output Id , I did  a second call to the endpoint suggested by @qwerty1979bg and I got the connection string value.

However I disagree that the Terraform Cloud API force me to make two calls when I could get the value in the first one.

Best Regards

**Comment by crw** [comment] 2022-05-13 15:49
I believe this issue is answered, and so will close it. @lemsy if there are any outstanding unresolved issues, please let me know!

**Closed by crw** 2022-05-13 15:49 UTC
Labels: enhancement, cloud
