### ISSUE TITLE
aws_route: diffs didn't match during apply

### ISSUE THREAD

**Issue by tomwilkie** [hashicorp/terraform#9967] opened 2016-11-08 19:46 UTC
Config looks like this:
```
resource "aws_instance" "minion" {
    count = "${var.num_minions}"
    ...
}

resource "aws_route" "minion-route" {
    count = "${var.num_minions}"
    route_table_id = "${aws_route_table.main.id}"

    destination_cidr_block = "${cidrsubnet(var.container_cidr_block, 8, 254 - count.index)}"
    instance_id = "${element(aws_instance.minion.*.id, count.index)}"
}
```

Basically, create a route table entry for every minion.

I increased var.num_minions (from 3 to 4), and ran plan / apply.

```
$ teraform plan -out=/var/folders/tm/wkx174nd59j1mh67v56thz_c0000gn/T/tmp.DUmISv9C
...
~ module.infra.aws_elb.main
    instances.#: "" => "<computed>"

+ module.infra.aws_instance.minion.3
    ami:                                            "ami-REDACTED"
    associate_public_ip_address:                    "true"
    availability_zone:                              "us-east-1a"
    ebs_block_device.#:                             "<computed>"
    ephemeral_block_device.#:                       "2"
    ephemeral_block_device.1910755302.device_name:  "/dev/xvdc"
    ephemeral_block_device.1910755302.virtual_name: "ephemeral1"
    ephemeral_block_device.3043895074.device_name:  "/dev/xvdb"
    ephemeral_block_device.3043895074.virtual_name: "ephemeral0"
    iam_instance_profile:                           "kubernetes-minion"
    instance_state:                                 "<computed>"
    instance_type:                                  "c3.4xlarge"
    key_name:                                       "REDACTED"
    network_interface_id:                           "<computed>"
    placement_group:                                "<computed>"
    private_dns:                                    "<computed>"
    private_ip:                                     "<computed>"
    public_dns:                                     "<computed>"
    public_ip:                                      "<computed>"
    root_block_device.#:                            "<computed>"
    security_groups.#:                              "<computed>"
    source_dest_check:                              "false"
    subnet_id:                                      "subnet-REDACTED"
    tags.%:                                         "3"
    tags.KubernetesCluster:                         "kubernetes_dev_2"
    tags.Name:                                      "kubernetes_dev_2-minion"
    tags.Role:                                      "kubernetes_dev_2-minion"
    tenancy:                                        "<computed>"
    vpc_security_group_ids.#:                       "1"
    vpc_security_group_ids.3874088684:              "sg-REDACTED"

~ module.infra.aws_route.minion-route.0
    instance_id: "i-REDACTED" => "${element(aws_instance.minion.*.id, count.index)}"

~ module.infra.aws_route.minion-route.1
    instance_id: "i-REDACTED" => "${element(aws_instance.minion.*.id, count.index)}"

~ module.infra.aws_route.minion-route.2
    instance_id: "i-REDACTED" => "${element(aws_instance.minion.*.id, count.index)}"

+ module.infra.aws_route.minion-route.3
    destination_cidr_block:     "10.244.251.0/24"
    destination_prefix_list_id: "<computed>"
    gateway_id:                 "<computed>"
    instance_id:                "${element(aws_instance.minion.*.id, count.index)}"
    instance_owner_id:          "<computed>"
    nat_gateway_id:             "<computed>"
    network_interface_id:       "<computed>"
    origin:                     "<computed>"
    route_table_id:             "rtb-REDACTED"
    state:                      "<computed>"


Plan: 2 to add, 4 to change, 0 to destroy.


$ terraform apply /var/folders/tm/wkx174nd59j1mh67v56thz_c0000gn/T/tmp.DUmISv9C
...
Note: creating an RDS instance can take a very long time, 15+ minutes.

module.infra.aws_instance.minion.3: Creating...
  ami:                                            "" => "ami-REDACTED"
  associate_public_ip_address:                    "" => "true"
  availability_zone:                              "" => "us-east-1a"
  ebs_block_device.#:                             "" => "<computed>"
  ephemeral_block_device.#:                       "" => "2"
  ephemeral_block_device.1910755302.device_name:  "" => "/dev/xvdc"
  ephemeral_block_device.1910755302.virtual_name: "" => "ephemeral1"
  ephemeral_block_device.3043895074.device_name:  "" => "/dev/xvdb"
  ephemeral_block_device.3043895074.virtual_name: "" => "ephemeral0"
  iam_instance_profile:                           "" => "kubernetes-minion"
  instance_state:                                 "" => "<computed>"
  instance_type:                                  "" => "c3.4xlarge"
  key_name:                                       "" => "REDACTED
  network_interface_id:                           "" => "<computed>"
  placement_group:                                "" => "<computed>"
  private_dns:                                    "" => "<computed>"
  private_ip:                                     "" => "<computed>"
  public_dns:                                     "" => "<computed>"
  public_ip:                                      "" => "<computed>"
  root_block_device.#:                            "" => "<computed>"
  security_groups.#:                              "" => "<computed>"
  source_dest_check:                              "" => "false"
  subnet_id:                                      "" => "subnet-REDACTED"
  tags.%:                                         "" => "3"
  tags.KubernetesCluster:                         "" => "kubernetes_dev_2"
  tags.Name:                                      "" => "kubernetes_dev_2-minion"
  tags.Role:                                      "" => "kubernetes_dev_2-minion"
  tenancy:                                        "" => "<computed>"
  vpc_security_group_ids.#:                       "" => "1"
  vpc_security_group_ids.3874088684:              "" => "sg-REDACTED"
module.infra.aws_instance.minion.3: Still creating... (10s elapsed)
module.infra.aws_instance.minion.3: Still creating... (20s elapsed)
module.infra.aws_instance.minion.3: Creation complete
module.infra.aws_route.minion-route.3: Creating...
  destination_cidr_block:     "" => "10.244.251.0/24"
  destination_prefix_list_id: "" => "<computed>"
  gateway_id:                 "" => "<computed>"
  instance_id:                "" => "i-REDACTED"
  instance_owner_id:          "" => "<computed>"
  nat_gateway_id:             "" => "<computed>"
  network_interface_id:       "" => "<computed>"
  origin:                     "" => "<computed>"
  route_table_id:             "" => "rtb-REDACTED"
  state:                      "" => "<computed>"
module.infra.aws_elb.main: Modifying...
  instances.#:          "3" => "4"
  instances.230587056:  "" => "i-REDACTED"
  instances.2386439039: "i-REDACTED" => "i-REDACTED"
  instances.3712921585: "i-REDACTED" => "i-REDACTED"
  instances.449504464:  "i-REDACTED" => "i-REDACTED"
module.infra.aws_route.minion-route.3: Creation complete
module.infra.aws_elb.main: Modifications complete
Error applying plan:

3 error(s) occurred:

* aws_route.minion-route.2: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.5
    Resource ID: aws_route.minion-route.2
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-e8de5dd8", New:"${element(aws_instance.minion.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.minion-route.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.5
    Resource ID: aws_route.minion-route.1
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-f2df5cc2", New:"${element(aws_instance.minion.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_route.minion-route.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.5
    Resource ID: aws_route.minion-route.0
    Mismatch reason: attribute mismatch: instance_id
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"instance_id":*terraform.ResourceAttrDiff{Old:"i-6c81385c", New:"${element(aws_instance.minion.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by mitchellh** [comment] 2016-11-09 01:03
This was fixed in recent Terraform versions, please give 0.7.9 a try! :)

**Closed by mitchellh** 2016-11-09 01:03 UTC

**Comment by tomwilkie** [comment] 2016-11-10 15:21
@mitchellh just tried with terraform 0.7.9 - it 'worked', but complained about an experiemental feature failure:

```
Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!
```

There is a lot more state after this - I've made a private gist for this - some way I can share this with you privately?

**Comment by mitchellh** [comment] 2016-11-10 15:56
@tomwilkie Sorry to ask you this, but we fixed a number of experimental feature failures in 0.7.10 released yesterday, can you try with that? 

Your error doesn't have enough info for me to know whether we indeed fixed it in 0.7.10 but since you have a lot more state it might be worth you trying it on the new one first. :)

**Comment by tomwilkie** [comment] 2016-11-10 16:06
Sure, give us a minute.

**Comment by tomwilkie** [comment] 2016-11-10 16:13
With terraform 0.7.10 I got:

```
Error applying plan:

1 error(s) occurred:

* aws_route.minion-route.4: Error creating route: IncorrectInstanceState: Instance with state 'pending' is not valid for this operation.
	status code: 400, request id: 1801b4b9-c88d-41d4-bab0-9388f9660d2f

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I got it when increase the minion count from 4->5, but not when going from 5->6.

**Comment by mitchellh** [comment] 2016-11-10 16:15
Great! So this looks like an actual AWS provider issue. Could you open a new issue with your repros and we'll tag that appropriately. It looks like the core issues are cleared out.

**Comment by tomwilkie** [comment] 2016-11-10 16:17
Okay back down I got this:

```
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: /var/folders/tm/wkx174nd59j1mh67v56thz_c0000gn/T/tmp.B4Q8WOwh

~ module.infra.aws_elb.main
    instances.#:          "6" => "4"
    instances.230587056:  "i-93b02a9d" => "i-93b02a9d"
    instances.2386439039: "i-6c81385c" => "i-6c81385c"
    instances.255370489:  "i-38e48636" => ""
    instances.3712921585: "i-e8de5dd8" => "i-e8de5dd8"
    instances.449504464:  "i-f2df5cc2" => "i-f2df5cc2"
    instances.758841449:  "i-e4ee8cea" => ""

- module.infra.aws_instance.minion.4

- module.infra.aws_instance.minion.5

- module.infra.aws_route.minion-route.4

- module.infra.aws_route.minion-route.5


Plan: 0 to add, 1 to change, 4 to destroy.
Do you wish to proceed with the plan? yes

Note: creating an RDS instance can take a very long time, 15+ minutes.

module.infra.aws_route.minion-route.5: Destroying...
module.infra.aws_route.minion-route.4: Destroying...
module.infra.aws_route.minion-route.5: Destruction complete
module.infra.aws_route.minion-route.4: Destruction complete
module.infra.aws_instance.minion.4: Destroying...
module.infra.aws_instance.minion.5: Destroying...
module.infra.aws_instance.minion.4: Still destroying... (10s elapsed)
module.infra.aws_instance.minion.5: Still destroying... (10s elapsed)
module.infra.aws_instance.minion.4: Still destroying... (20s elapsed)
module.infra.aws_instance.minion.5: Still destroying... (20s elapsed)
module.infra.aws_instance.minion.4: Still destroying... (30s elapsed)
module.infra.aws_instance.minion.5: Still destroying... (30s elapsed)
module.infra.aws_instance.minion.4: Destruction complete
module.infra.aws_instance.minion.5: Still destroying... (40s elapsed)
module.infra.aws_instance.minion.5: Destruction complete
module.infra.aws_elb.main: Modifying...
  instances.#:          "6" => "4"
  instances.230587056:  "i-93b02a9d" => "i-93b02a9d"
  instances.2386439039: "i-6c81385c" => "i-6c81385c"
  instances.255370489:  "i-38e48636" => ""
  instances.3712921585: "i-e8de5dd8" => "i-e8de5dd8"
  instances.449504464:  "i-f2df5cc2" => "i-f2df5cc2"
  instances.758841449:  "i-e4ee8cea" => ""
module.infra.aws_elb.main: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 4 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: tfstate

Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!

You can report an issue at: https://github.com/hashicorp/terraform/issues

2 error(s) occurred:

* apply operation: Unknown 'ValidateResource' shadow value for "aws_elb": &errors.errorString{s:"shadow closed"}
* apply operation: Diff "module.infra.aws_elb.main" had unequal states (real, then shadow):

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"tags":[]map[string]interface {}{map[string]interface {}{"KubernetesCluster":"${var.cluster_name}", "kubernetes.io/service-name":"default/frontend"}}, "listener":[]map[string]interface {}{map[string]interface {}{"lb_port":80, "lb_protocol":"tcp", "instance_port":30080, "instance_protocol":"tcp"}, map[string]interface {}{"lb_port":443, "lb_protocol":"tcp", "instance_port":30443, "instance_protocol":"tcp"}}, "health_check":[]map[string]interface {}{map[string]interface {}{"healthy_threshold":2, "unhealthy_threshold":6, "timeout":5, "interval":10, "target":"TCP:30080"}}, "instances":[]interface {}{"${aws_instance.minion.*.id}"}, "name":"${var.elb_name}", "subnets":[]interface {}{"${aws_subnet.main.id}"}, "cross_zone_load_balancing":"false"}, Config:map[string]interface {}{"tags":[]map[string]interface {}{map[string]interface {}{"KubernetesCluster":"kubernetes_dev_2", "kubernetes.io/service-name":"default/frontend"}}, "listener":[]map[string]interface {}{map[string]interface {}{"lb_port":80, "lb_protocol":"tcp", "instance_port":30080, "instance_protocol":"tcp"}, map[string]interface {}{"lb_protocol":"tcp", "instance_port":30443, "instance_protocol":"tcp", "lb_port":443}}, "health_check":[]map[string]interface {}{map[string]interface {}{"timeout":5, "interval":10, "target":"TCP:30080", "healthy_threshold":2, "unhealthy_threshold":6}}, "instances":[]interface {}{"i-6c81385c", "i-f2df5cc2", "i-e8de5dd8", "i-93b02a9d"}, "name":"ab12448b348fa11e69d561228d43a32f", "subnets":[]interface {}{"subnet-b3c31c9e"}, "cross_zone_load_balancing":"false"}, raw:(*config.RawConfig)(0xc4207bb260)}

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"listener":[]map[string]interface {}{map[string]interface {}{"instance_port":30080, "instance_protocol":"tcp", "lb_port":80, "lb_protocol":"tcp"}, map[string]interface {}{"lb_protocol":"tcp", "instance_port":30443, "instance_protocol":"tcp", "lb_port":443}}, "health_check":[]map[string]interface {}{map[string]interface {}{"unhealthy_threshold":6, "timeout":5, "interval":10, "target":"TCP:30080", "healthy_threshold":2}}, "instances":[]interface {}{"${aws_instance.minion.*.id}"}, "name":"${var.elb_name}", "subnets":[]interface {}{"${aws_subnet.main.id}"}, "cross_zone_load_balancing":"false", "tags":[]map[string]interface {}{map[string]interface {}{"KubernetesCluster":"${var.cluster_name}", "kubernetes.io/service-name":"default/frontend"}}}, Config:map[string]interface {}{"health_check":[]map[string]interface {}{map[string]interface {}{"unhealthy_threshold":6, "timeout":5, "interval":10, "target":"TCP:30080", "healthy_threshold":2}}, "instances":[]interface {}{"i-6c81385c", "i-f2df5cc2", "i-e8de5dd8", "i-93b02a9d", "i-38e48636", "i-e4ee8cea"}, "name":"ab12448b348fa11e69d561228d43a32f", "subnets":[]interface {}{"subnet-b3c31c9e"}, "cross_zone_load_balancing":"false", "tags":[]map[string]interface {}{map[string]interface {}{"KubernetesCluster":"kubernetes_dev_2", "kubernetes.io/service-name":"default/frontend"}}, "listener":[]map[string]interface {}{map[string]interface {}{"instance_port":30080, "instance_protocol":"tcp", "lb_port":80, "lb_protocol":"tcp"}, map[string]interface {}{"instance_port":30443, "instance_protocol":"tcp", "lb_port":443, "lb_protocol":"tcp"}}}, raw:(*config.RawConfig)(0xc42052cae0)}

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.
```

**Comment by mitchellh** [comment] 2016-11-10 16:19
Darn, that's a real issue. Thanks, it looks like its resources that aren't in your additional config, do you mind posting that config and if possible the state (redact any private info) so that I can try to reproduce? Thanks!

**Comment by tomwilkie** [comment] 2016-11-10 16:21
The elb config looks like this:

```
resource "aws_elb" "main" {
    name = "${var.elb_name}"
    subnets = ["${aws_subnet.main.id}"]
    cross_zone_load_balancing = "false"

    // The 30xxx ports are defined by the frontend NodePort
    // service in k8s/{dev,prod}/default/frontend-svc.yaml
    listener {
        instance_port = 30080
        instance_protocol = "tcp"
        lb_port = 80
        lb_protocol = "tcp"
    }

    listener {
        instance_port = 30443
        instance_protocol = "tcp"
        lb_port = 443
        lb_protocol = "tcp"
    }

    health_check {
       // The number of checks before the instance is declared healthy.
       healthy_threshold = 2

       // The number of checks before the instance is declared unhealthy.
       unhealthy_threshold = 6

       // In seconds
       timeout = 5

       // In seconds
       interval = 10

       target = "TCP:30080"
    }

    instances = ["${aws_instance.minion.*.id}"]
}
```

**Comment by tomwilkie** [comment] 2016-11-10 16:21
Which bits of the state do you need?  Its a little too big for me to redact by hand :-)

**Comment by mitchellh** [comment] 2016-11-10 16:26
@tomwilkie Just the `aws_elb.main` state, probably. :) Thanks for being so helpful.

**Comment by tomwilkie** [comment] 2016-11-10 16:28
```
        {
            "path": [
                "root",
                "infra"
            ],
            "outputs": {
                "minion_security_group_id": {
                    "sensitive": false,
                    "type": "string",
                    "value": "sg-XXX"
                },
                "subnet_id": {
                    "sensitive": false,
                    "type": "string",
                    "value": "subnet-XXX"
                }
            },
            "resources": {
                "aws_elb.main": {
                    "type": "aws_elb",
                    "depends_on": [
                        "aws_instance.minion",
                        "aws_subnet.main"
                    ],
                    "primary": {
                        "id": "ab12448b348fa11e69d561228d43a32f",
                        "attributes": {
                            "access_logs.#": "0",
                            "availability_zones.#": "1",
                            "availability_zones.3569565595": "us-east-1a",
                            "connection_draining": "false",
                            "connection_draining_timeout": "300",
                            "cross_zone_load_balancing": "false",
                            "dns_name": "ab12448b348fa11e69d561228d43a32f-1004690539.us-east-1.elb.amazonaws.com",
                            "health_check.#": "1",
                            "health_check.0.healthy_threshold": "2",
                            "health_check.0.interval": "10",
                            "health_check.0.target": "TCP:30080",
                            "health_check.0.timeout": "5",
                            "health_check.0.unhealthy_threshold": "6",
                            "id": "ab12448b348fa11e69d561228d43a32f",
                            "idle_timeout": "60",
                            "instances.#": "4",
                            "instances.230587056": "i-93b02a9d",
                            "instances.2386439039": "i-6c81385c",
                            "instances.3712921585": "i-e8de5dd8",
                            "instances.449504464": "i-f2df5cc2",
                            "internal": "false",
                            "listener.#": "2",
                            "listener.1342782350.instance_port": "30080",
                            "listener.1342782350.instance_protocol": "tcp",
                            "listener.1342782350.lb_port": "80",
                            "listener.1342782350.lb_protocol": "tcp",
                            "listener.1342782350.ssl_certificate_id": "",
                            "listener.3536635864.instance_port": "30443",
                            "listener.3536635864.instance_protocol": "tcp",
                            "listener.3536635864.lb_port": "443",
                            "listener.3536635864.lb_protocol": "tcp",
                            "listener.3536635864.ssl_certificate_id": "",
                            "name": "ab12448b348fa11e69d561228d43a32f",
                            "security_groups.#": "1",
                            "security_groups.1215916898": "sg-XXX",
                            "source_security_group": "376248598259/k8s-elb-ab12448b348fa11e69d561228d43a32f",
                            "source_security_group_id": "sg-XXX",
                            "subnets.#": "1",
                            "subnets.4271083790": "subnet-XXX",
                            "tags.%": "2",
                            "tags.KubernetesCluster": "kubernetes_dev_2",
                            "tags.kubernetes.io/service-name": "default/frontend",
                            "zone_id": "Z3DZXE0Q79N41H"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                },
...
```

**Comment by mitchellh** [comment] 2016-11-11 06:06
Thanks @tomwilkie, unfortunately unable to get a repro going over here.... but the error message above is a bit more telling then I suspected and I'm going to see if I can manufacture a reproduction if possible...

**Comment by tomwilkie** [comment] 2016-11-11 11:41
I'll see if I can produce a minimal reproduction I can share with you.
