### ISSUE TITLE
Module outputs changes not saved in state in 0.14.0-beta2

### ISSUE THREAD

**Issue by astorath** [hashicorp/terraform#26789] opened 2020-11-02 19:27 UTC
In 0.14.0-beta2 I have the following behavior:

1. Running `apply` show:
```
Changes to Outputs:
  + tags = {
      + managed = "terraform"
    }
```

2. Running `apply` show:

### Terraform Version
```
Terraform v0.14.0-beta2
+ provider registry.terraform.io/hashicorp/google v2.12.0
+ provider registry.terraform.io/hashicorp/google-beta v2.12.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files

`main.tf`:
```terraform
module "c" {
  source = "./test-module"
}
```

`test-module/outputs.tf`:
```terraform
output "tags" {
  value = {
    managed = "terraform"
  }
}
```

### Debug Output

https://gist.github.com/astorath/1b7d0837fad2a3a9745b689cc4f44b30

### Expected Behavior
Subsequent `terraform apply` should contain no changes

### Actual Behavior
Subsequent `terraform apply` contains all the same `Changes to Outputs`

**Comment by alisdair** [comment] 2020-11-02 21:17
Hi @astorath, thanks for reporting this! I believe this is a duplicate of #26776. I merged a fix in #26784 and it'll be in the next 0.14.0-beta3 release.

**Closed by alisdair** 2020-11-02 21:17 UTC
Labels: bug, new
