### ISSUE TITLE
Allow to use version variable in public module

### ISSUE THREAD

**Issue by chmodrs** [hashicorp/terraform#31001] opened 2022-05-04 22:57 UTC
Hi everyone,

I have a module called mycompany-eks that implement eks and another things like argocd, istio and another features. My custom module will call eks official module ("terraform-aws-modules/eks/aws"). But i need to setup an version variable in my module bringing possible to choose eks module version that i want, because sometimes i need to setup using 16.x.x and other times version and 18.x.x, for example. If i setup manually version = "16.x.x" when i change it directly in module, will break a lot of implementations, so variable implementation here sounds good.

### Terraform Version
```
1.0.11
```

### Terraform Configuration Files

```
eks.tf
...
module "eks-cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = var.eks_module_version

variables.tf
...
variable "eks_module_version" {
  description = "The version of Terraform EKS Module"
  type        = string
  default.    = "16.1.0"
}

```

### Debug Output
```
Error: Variables not allowed                                                                                                                                   
│                                                                                                                                                                
│ On ../../../../../../terraform/modules/mycompany-eks/eks.tf line 10: Variables may not be used here.

│ Error: Unsuitable value type                                                                                                                                   
│                                                                                                                                                                
│ On ../../../../../../terraform/modules/mycompany-eks/eks.tf line 10: Unsuitable value: value must be known 
```
### Expected Behavior

I expected to use variables in version modules

### Actual Behavior

i cannot use variables in version modules

### Steps to Reproduce

1. create a custom module using official terraform eks module:
```
module "eks-cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "16.1.0"
```
2. Update version for an variable
```
  version = "var.eks_module_version"
```
3. Try to use this module setting up an custom module version
```
module "eks-cluster" {
  source             = "../../../../../../terraform/modules/mycompany-eks"
  eks_module_version = "18.x.x"
```

**Comment by jbardin** [comment] 2022-05-05 12:20
Duplicate of #28912

**Closed by jbardin** 2022-05-05 12:20 UTC
Labels: enhancement, new
