### ISSUE TITLE
data.tls_certificate.tls.certificates is empty list of object on tls provide 3.4.0

### ISSUE THREAD

**Issue by kailashsridharan** [hashicorp/terraform#31497] opened 2022-07-22 15:49 UTC
### Terraform Version

```
1.1.4
TLS Provider 4.0.0
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

```
"aws_iam_openid_connect_provider" "openid_connect":
 thumbprint_list = [data.tls_certificate.tls.certificates[0].sha1_fingerprint]
data.tls_certificate.tls.certificates is empty list of object
```

### Expected Behavior

```
The above error should not be seen, openid_connect should be successful
```
### Actual Behavior

```
Error: Invalid index
data.tls_certificate.tls.certificates is empty list of object
```
### Steps to Reproduce

```
data "tls_certificate" "tls" {
  url = aws_eks_cluster.this.identity[0].oidc[0].issuer
}

resource "aws_iam_openid_connect_provider" "openid_connect" {
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.tls.certificates[0].sha1_fingerprint]
  url             = aws_eks_cluster.this.identity[0].oidc[0].issuer
}
```

**Comment by kailashsridharan** [comment] 2022-07-22 15:50
Workaround is to set TLS provider to 3.4.0

**Comment by apparentlymart** [comment] 2022-07-22 16:08
Hi @kailashsridharan,

It seems like you're talking about a behavior of [the `hashicorp/tls` provider](https://registry.terraform.io/providers/hashicorp/tls), in which case I suggest to open an issue in [the provider's own repository](https://github.com/hashicorp/terraform-provider-tls).

Since the current release of the provider is v4.0.0 it seems like the provider team have just made a major release which may contain intentional breaking changes. Therefore what you described might be the intended behavior and I would suggest reviewing the provider's changelog before you open an issue to confirm and to see if there are some migration steps you can follow to avoid the error.

Since the behavior you are describing isn't implemented in _this_ repository, I'm going to close this issue. We use issues in this repository only to represents bugs and feature requests in Terraform CLI and Terraform Core, and not for individual providers that are developed and distributed separately. Thanks!

**Closed by apparentlymart** 2022-07-22 16:08 UTC
Labels: bug, new
