### ISSUE TITLE
terraform fails when an iam user or role is renamed

### ISSUE THREAD

**Issue by justin8** [hashicorp/terraform#7939] opened 2016-08-03 10:51 UTC
When renaming a role/user (probably groups as well, but I haven't tested this). It attempts to delete the old resource without detaching the policies, then returns this:

```
Error applying plan:

1 error(s) occurred:

* aws_iam_user.jenkins-test: Error deleting IAM User jenkins-test: DeleteConflict: Cannot delete entity, must detach all policies first.
    status code: 409, request id: 8c1f8c69-5967-11e6-b3ac-ab2eb361e21c

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

According to https://github.com/hashicorp/terraform/pull/3227 it sounds like this should have already been fixed, but it doesn't seem this way.
### Terraform Version

v0.6.616
### References

https://github.com/hashicorp/terraform/pull/3227

**Comment by jen20** [comment] 2016-08-03 14:01
Hi @justin8! Thanks for opening an issue. I'd definitely consider this a bug. Can you confirm the steps you took here? I _think_ looking at it the following is probably the case:

1. Create an `aws_iam_user` with at least one policy attached
2. Rename the resulting user in the AWS console
3. `terraform plan` and `terraform apply`?

**Comment by justin8** [comment] 2016-08-12 04:49
Sorry for the slow response, I've been travelling recently.

I get the issue without ever touching the user in the AWS console, just creating a new iam user via terraform (and the attached policy is also managed in terraform in the same file) , renaming in the state file and running `terraform plan` shows what you would expect, 1 create, 1 destroy. But `terraform apply` tries to delete the user without detaching policies first.

**Comment by tmatilai** [comment] 2016-09-14 06:59
Duplicate of #5853

**Closed** 2017-06-13 17:43 UTC
Labels: bug, provider/aws
