### ISSUE TITLE
Terraform 0.14 causes API gateway re-deploy with no changes

### ISSUE THREAD

**Issue by charles-dexter-ward** [hashicorp/terraform#27792] opened 2021-02-16 18:34 UTC
### 0.14.6

Using Terraform 0.14.6 on the same terraform.tf file causes the plan to detect a change in the deployment of the API gateway even if no changes are occurred. Using Terraform 0.13.5 it works correctly.
No new APIs are added or deleted and no API methods are changing.

### Terraform Configuration Files

```terraform
resource "aws_api_gateway_stage" "stage" {
  stage_name         = var.env
  rest_api_id        = module.apigateway.id
  deployment_id      = module.api_gateway_deployment.deployment.id
  cache_cluster_size = "0.5"
  # variables = {}
}

resource "aws_api_gateway_deployment" "tsxinstallerdeployment" {
  rest_api_id = var.rest_api.id
  stage_name  = "" #var.env
  triggers = {
    redeployment = sha1(join(",", list(
      jsonencode(var.integration_list),
    )))
    resources = sha1(join(",", list(
      jsonencode(var.resources_list),
    )))
    methods = sha1(join(",", list(jsonencode(var.method_list),)))
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

The plan should not detect any API deployment change. It should work as Terraform 0.13.5.

### Actual Behavior

With Terraform 0.14.6, the plan detects some kind of change in the API and it proposes  an API redeployment.

![image](https://user-images.githubusercontent.com/2855255/108108818-68750380-7091-11eb-91ce-2d3b57ae4ff9.png)

![image](https://user-images.githubusercontent.com/2855255/108108745-509d7f80-7091-11eb-84ac-ed8a589f01f0.png)

**Comment by jbardin** [comment] 2021-02-16 20:19
Hi @charles-dexter-ward 

Thanks for filing the issue. From the partial configuration here, I assume `module.api_gateway_deployment.deployment.id` is referring to the `"aws_api_gateway_deployment" "tsxinstallerdeployment"` resource, which is planned to be replaced.

The plan output indicates the `methods` and `redeployment` values are changing, which means the `var.resources_list` and `var.integration_list` values are changing during plan. Without the complete configuration it's hard to determine why that may be. Is is possible to provide a complete example in order to replicate the situation?

Thanks!

**Comment by charles-dexter-ward** [comment] 2021-02-16 20:41
It's not that simple to provide the compete configuration. However, using the same configuration with Terraform 0.13.5 no changes are detected (and this is right).

The deployment definition is
```terraform
module "api_gateway_deployment" {
  source = "./modules/common/aws/apigateway/deployment"

  rest_api = {
    id               = module.apigateway.id
    root_resource_id = module.apigateway.root_resource_id
  }

  integration_list = concat(module.lambda_enqueue_requests.api_integration[*],
    module.lambda_get_packages_list_by_licenses.api_integration[*],
  module.lambda_get_presigned_urls.api_integration[*])

  resources_list = concat(module.lambda_enqueue_requests.api_resource[*],
    module.lambda_get_packages_list_by_licenses.api_resource[*],
  module.lambda_get_presigned_urls.api_resource[*])


  method_list = concat(module.lambda_enqueue_requests.api_method[*],
    module.lambda_get_packages_list_by_licenses.api_method[*],
  module.lambda_get_presigned_urls.api_method[*])
}
```

and the source for this module is
```terraform
resource "aws_api_gateway_deployment" "tsxinstallerdeployment" {
  rest_api_id = var.rest_api.id
  stage_name  = "" #var.env
  triggers = {
    redeployment = sha1(join(",", list(
      jsonencode(var.integration_list),
    )))
    resources = sha1(join(",", list(
      jsonencode(var.resources_list),
    )))
    methods = sha1(join(",", list(jsonencode(var.method_list),)))
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

Each lambda attached to the API is defined as (this is the definition for one of them):
```terraform
module "lambda_enqueue_requests" {
  source = "./modules/common/aws/apigateway/lambda_proxy_resources"

  # api_id = module.apigateway.id # Vedi output.tf in apigateway

  rest_api = {
    id               = module.apigateway.id
    root_resource_id = module.apigateway.root_resource_id
    path_part        = "enqueue"
    method           = "POST"
    authorization    = "AWS_IAM"
    api_key_required = true
  }

  filename = "./lambdas/enqueue_requests.zip"

  function_name = "enqueue_requests"

  role = module.lambda_exec_role.arn
}
```

and the source for this module is:
```terraform
module "lambda" {
  source        = "./lambda"
  filename      = var.filename
  function_name = var.function_name
  role          = var.role
  timeout       = var.timeout
  layers        = var.layers
}

resource "aws_api_gateway_resource" "lambda_proxy_resources" {
  rest_api_id = var.rest_api.id
  parent_id   = var.rest_api.root_resource_id
  path_part   = var.rest_api.path_part

  depends_on = [var.rest_api]

  lifecycle {
    create_before_destroy = true
  }

}

resource "aws_api_gateway_method" "lambda_proxy_method" {
  rest_api_id      = var.rest_api.id
  resource_id      = aws_api_gateway_resource.lambda_proxy_resources.id
  http_method      = var.rest_api.method
  authorization    = var.rest_api.authorization
  api_key_required = var.rest_api.api_key_required
  depends_on       = [aws_api_gateway_resource.lambda_proxy_resources]
}

resource "aws_api_gateway_integration" "lambda_proxy_integration" {
  rest_api_id             = var.rest_api.id
  resource_id             = aws_api_gateway_resource.lambda_proxy_resources.id
  http_method             = aws_api_gateway_method.lambda_proxy_method.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = module.lambda.invoke_arn
  depends_on              = [aws_api_gateway_resource.lambda_proxy_resources, aws_api_gateway_method.lambda_proxy_method]
}

```

which defines these outputs, used in the deployment triggers above:

```terraform
output "api_integration" {
  #value = aws_apigatewayv2_integration.lambda_proxy_resources
  value = aws_api_gateway_integration.lambda_proxy_integration
}

output "api_resource" {
    value = aws_api_gateway_resource.lambda_proxy_resources
}

output "function_name" {
  value = module.lambda.function_name
}

output "api_method" {
    value =  aws_api_gateway_method.lambda_proxy_method
}
```

**Comment by jbardin** [comment] 2021-02-16 22:19
Thanks for the additional info, unfortunately this still doesn't fully explain what is causing the `aws_api_gateway_deployment.tsxinstallerdeployment` to unexpectedly be replaced. The input to the `redeployment` and `methods` `triggers` is changing somehow, but I'm not seeing anything here to indicate why. Are there no other changes shown in the plan output? If the are no other changes shown here, one possibility is the provider is silently altering some value when refreshing or planning a resource. These could show up as warnings in the logs, and may help.

**Comment by charles-dexter-ward** [comment] 2021-02-17 18:48
Using the same terraform.tf, when planning with Terraform 0.14.6 there are warnings like this

```
2021/02/17 19:19:47 [WARN] Provider "registry.terraform.io/hashicorp/aws" produced an unexpected new value for module.lambda_enqueue_requests.aws_api_gateway_method.lambda_proxy_method during refresh.
      - .operation_name: was null, but now cty.StringVal("")
```

**Comment by jbardin** [comment] 2021-02-23 22:48
Thanks @charles-dexter-ward, though that doesn't appear to help us see why things like `var.integration_list` are changing. 

Perhaps getting the exact values being given to the variable into an output would show what is being changed, and may be more useful to diagnose the problem than a hash. If it's possible to recreate this, removing the hashing entirely so that the entire value can be seen will better show what's changed.

Some other issues that are not necessarily a problem but raise questions here are: 
 - The unnecessary use of `depends_on`. These don't appear to cause problems themselves, but if this is often used indiscriminately, in some cases they can add extra dependencies that are not intended and cause unexpected changes.
 - The use of `[*]` to change single values into a list. This could possibly be hiding or combining values in unexpected ways. You may want to see what each of those individual values is.

**Comment by jbardin** [comment] 2023-11-29 16:41
Hi @bgre033,

The change you are showing would have to be inserted by the provider as it's a change in the computed value of the `aws_api_gateway_deployment`, so if it was unexpected I would suggest filing an issue with the aws provider. Since this issue never got a reproducible example, but looks similar to what you have here, I'll close this out for now.

Thanks!

**Closed by jbardin** 2023-11-29 16:41 UTC
Labels: bug, waiting for reproduction, v0.14
