### ISSUE TITLE
Error reading config: parse error at 1:8: expected "}" but found "x1"

### ISSUE THREAD

**Issue by kjmkznr** [hashicorp/terraform#10597] opened 2016-12-08 04:17 UTC
### Terraform Version
```
$ terraform-0.8.0-dev version
Terraform v0.8.0-dev (134b438c92abfa8c6ea7b82bd9a0470d7ac39ad5)
```
(134b438c92abfa8c6ea7b82bd9a0470d7ac39ad5)

### Terraform Configuration Files
```hcl
variable "1x1" {
  default = "test"
}

output "foo" {
  value = "${var.1x1}"
}
```

### Debug Output
```
$ TF_LOG=debug terraform-0.8.0-dev apply
16/12/08 04:05:12 [INFO] Terraform version: 0.8.0 dev 134b438c92abfa8c6ea7b82bd9a0470d7ac39ad5
2016/12/08 04:05:12 [INFO] CLI args: []string{"/home/kjmkznr/bin/terraform-0.8.0-dev", "apply"}
2016/12/08 04:05:12 [DEBUG] Detected home directory from env var: /home/kjmkznr
2016/12/08 04:05:12 [DEBUG] Detected home directory from env var: /home/kjmkznr
2016/12/08 04:05:12 [DEBUG] Attempting to open CLI config file: /home/kjmkznr/.terraformrc
2016/12/08 04:05:12 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/12/08 04:05:12 [DEBUG] Detected home directory from env var: /home/kjmkznr
2016/12/08 04:05:12 [DEBUG] plugin: waiting for all plugin processes to complete...
Error loading config: Error loading /tmp/test/a.tf: Error reading config for output foo: parse error at 1:8: expected "}" but found "x1"
```

### Expected Behavior

```
$ terraform version
Terraform v0.7.13
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

foo = test
```

### Actual Behavior

```
$ terraform-0.8.0-dev apply
Error loading config: Error loading /tmp/test/a.tf: Error reading config for output foo: parse error at 1:8: expected "}" but found "x1"
```

### Steps to Reproduce

1. `terraform apply`

**Comment by apparentlymart** [comment] 2016-12-08 16:11
Thanks for reporting this, @kjmkznr.

This seems to be a regression in the HIL parser, which was rewritten in 0.8 to support several new operators. It looks like the old version allowed identifiers to begin with digits, while the new parser is treating it as an integer `1` followed by an identifier `x1`.

I filed hashicorp/hil#40 for this. Once that is fixed, this will be fixed too.

**Comment by mitchellh** [comment] 2016-12-08 17:44
Hm, another thing here is that we may have messed up historically.

You can't for example have a resource that starts with a number (I believe). Identifiers in general in various languages are usually not allowed to start with a number. The reasoning for this is to remove some parsing ambiguity. 

So one option here is to actually make this a BC-incompat change in 0.8 That'd be unfortunate this late in the game but 0.8 isn't released yet and technically this didn't work at all through the beta process anyways so its just DOCUMENTED late. :)

I'm going to go with that route...

**Comment by mitchellh** [comment] 2016-12-08 17:46
Actually I'm wrong because the identifier is actually the summation of "var.1x1" which should probably parse fine. Oy.

**Comment by VladRassokhin** [comment] 2016-12-08 21:03
I would repeat my comment from hashicorp/hcl/issues/40 here:
BTW: There's more fun:
```tf
variable "1x1" {
}
variable "-x2" {
}
variable "*x3" {
}
output "x1" {
  value = "${var.1x1}"
}
output "x2" {
  value = "${var.-x2}"
}
output "x3" {
  value = "${var.*x3}"
}
```
All three cases are seem to be valid variable names since `terraform validate` says nothing about them.
If you unquote variable identifiers, e.g.
```tf
variable 1x1 {
}
variable -x2 {
}
variable *x3 {
}
```
Terraform cannot parse that: `Error loading files Error parsing a.tf: At 1:10: expected: IDENT | STRING | ASSIGN | LBRACE got: NUMBER`

I'd suggest to prohibit such 'identifiers'

**Comment by mitchellh** [comment] 2016-12-08 21:32
@VladRassokhin Yeah... let's move the conversation to the HIL issue. I see you already commented there so we can just talk there. :)

**Comment by mitchellh** [comment] 2016-12-09 04:18
The consensus we came to was to disallow variables starting with numbers (hyphens as well). This is something that languages generally don't allow and we were able to continue thinking about how long term this is a bad idea for us. 

Sorry for that backwards incompatibility. We've now documented it and how you can work around it in the PR above.

**Closed by mitchellh** 2016-12-09 04:18 UTC
Labels: bug, core

**Comment by kjmkznr** [comment] 2016-12-09 04:47
Thanks!

**Comment by AswinMN** [comment] 2017-11-30 12:04
Hi,

I am getting the below error can you pls help me out while running terraform main.tf file

Error reading config for google_compute_instance_group_manager[@project.artifactId@]: parse error at 1:36: expected "}" but found invalid sequence "@"



the code is as below

resource "google_compute_instance_template" ["@project.artifactId@"]{
    name_prefix  = "${var.env}-${var.channel}-@project.artifactId@-${var.profile}"
    machine_type = "${var.machine_type}"
    region       = "${var.region}"
    tags         = [ "${var.channel}",
                     "${var.env}",
                     "${var.env}-${var.channel}-@project.artifactId@-${var.profile}" ]

    lifecycle {
        create_before_destroy = true
    }

    disk {
        source_image   = "@gcpImageProjectId@/@imageName@"
        auto_delete    = true
        boot           = true
    }

    network_interface {
        subnetwork_project = "${var.subnetwork_project != "" ? var.subnetwork_project : var.project}"
        subnetwork     = "${var.subnetwork}"
    }
