### ISSUE TITLE
Data sources to optionally not fail if resource is not found

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform#34224] opened 2023-11-12 09:20 UTC
### Terraform Version

```shell
v1.5.0
```

### Use Cases

This StackOverflow question got me thinking: https://stackoverflow.com/q/77462945/3390419 .
Essentially, the user wants to carry out some logic if the data source does not return any value.

Might it make sense to allow a data source to *not fail* if a resource is not found? 
Something like:

```terraform
data "aws_ssm_parameter" "my_parameter" {
  name                    = "this_might_exist_or_maybe_not"
  error_if_not_found      = false
}
```

I think the use case outlined by the user is a valid one.

**Comment by paololazzari** [comment] 2023-11-12 09:25
(I opened the issue here instead of doing so in the aws provider since I think the conversation about this behavior is relevant to all providers)

**Comment by jbardin** [comment] 2023-11-12 17:15
Duplicate of #16380

**Comment by jbardin** [comment] 2023-11-12 17:16
See also #28617 and #30291

**Closed by jbardin** 2023-11-12 17:15 UTC
Labels: enhancement, new

**Comment by paololazzari** [comment] 2023-11-13 07:40
> The sort of dynamic decision-making that is being requested here runs counter to Terraform's design goals, since it makes the configuration a description of what might possibly be rather than what is.

So why even have an `external` data source then? That's not consistent with this line of reasoning.
Perhaps the decision of not addressing this should be revisited, given a few hundred people have expressed an interest in this.

**Comment by jbardin** [comment] 2023-11-13 13:19
Hi @paololazzari, sorry I don't understand what you are referring to with the `external` data source. The protocol already allows what you are asking for, the logic for how to deal with a missing resource is contained within the data source implementation. Terraform cannot determine this, because it can not differentiate between an legitimate error situation and a missing resource. When a data source is meant to represent a single unmanaged remote resource, then it should normally return an error, because the necessary resource is expected to be found. To handle this in the configuration, the data source can be expended with `count` or `for_each` to conditionally have 0 or more instances.
