### ISSUE TITLE
Error in Terraform v0.12.8: Inappropriate value for attribute "route_table_ids": element 0: string required.

### ISSUE THREAD

**Issue by jalajarora** [hashicorp/terraform#22805] opened 2019-09-16 08:54 UTC
### Terraform Version

```
Terraform v0.12.8
+ provider.aws v2.15.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```
resource "aws_vpc_endpoint" "s3" {
  vpc_id            = "${module.vpc.vpc_id}"
  service_name      = "com.amazonaws.eu-west-1.s3"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = ["${module.vpc.private_route_table_ids}"]
}
```
When I use above I get below error on `terraform plan`
### Debug Output
```Error: Incorrect attribute value type

  on report_generator_s3.tf line 11, in resource "aws_vpc_endpoint" "s3":
  11:   route_table_ids   = ["${module.vpc.private_route_table_ids}"]

Inappropriate value for attribute "route_table_ids": element 0: string
required.
```
And, I tried doing below as well:
```resource "aws_vpc_endpoint" "s3" {
  vpc_id            = "${module.vpc.vpc_id}"
  service_name      = "com.amazonaws.eu-west-1.s3"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = "${module.vpc.private_route_table_ids}"
}
```

I get the same error on `terraform plan`

```
Error: Incorrect attribute value type

  on report_generator_s3.tf line 11, in resource "aws_vpc_endpoint" "s3":
  11:   route_table_ids   = "${module.vpc.private_route_table_ids}"

Inappropriate value for attribute "route_table_ids": element 0: string
required.
```

**Comment by kmoe** [comment] 2019-09-16 10:28
Thanks for the report, @jalajarora.

Since the value you want to interpolate, `module.vpc.private_route_table_ids`, is in another module, please include this module in your report, or use a variable to create a minimal reproduction case if it doesn't matter that it's from another module.

**Comment by jalajarora** [comment] 2019-09-16 10:35
Hi @kmoe Thanks for your reply.
[flatten function](https://www.terraform.io/docs/configuration/functions/flatten.html) seems to resolve the issue.
```
  route_table_ids   = flatten(["${module.vpc.private_route_table_ids}"])
```

**Comment by kmoe** [comment] 2019-09-16 11:47
That's great to hear. I don't know what the type of your `module.vpc.private_route_table_ids` variable is, but `route_table_ids` must be a set of strings, and it sounds like using `flatten` produced the correct type.

I'm going to close this issue now as this is not a bug in Terraform Core.

**Closed by kmoe** 2019-09-16 11:47 UTC
