### ISSUE TITLE
Crash: on terraform apply after moving two aws_lb resources into submodules with `terraform state mv`

### ISSUE THREAD

**Issue by mlimotte** [hashicorp/terraform#17483] opened 2018-03-02 03:53 UTC
### Terraform Version

```
Terraform v0.11.3
+ provider.aws v1.9.0
+ provider.template v1.0.0

```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

https://gist.github.com/mlimotte/8ab5e297d4c67f37ccb983bed29f66ea

**Comment by jbardin** [comment] 2018-03-02 14:58
Hi @mlimotte,

Thanks for filing the issue. There's no details to reproduce this here, but it looks like a duplicate of #16633.

**Closed by jbardin** 2018-03-02 14:58 UTC

**Comment by mlimotte** [comment] 2018-03-02 15:36
Looks similar.  More specifically, I think this was my root cause:

`terraform state mv module.qa1.aws_lb.main
 module.qa1.module.insights_dashboard.aws_elb.insights_dashboard`

I wanted to move a resource into a module, but I mistakenly specified
"aws_elb" as the destination resource type (instead of "aws_lb").  After
that, all commands resulted in a crash.  I was able to rectify the
situation with `terraform state rm` to drop the state for the resource
paths involved.

marc
