### ISSUE TITLE
cloudstack_nic - authentication failure when setting ip_address

### ISSUE THREAD

**Issue by landro** [hashicorp/terraform#6760] opened 2016-05-19 07:37 UTC
### Terraform Version

Terraform v0.6.15

### Affected Resource(s)
cloudstack_nic

### Terraform Configuration Files

This works fine

```hcl
    resource "cloudstack_nic" "nhn" {
      count              = "${var.lbnhn_count}"
      network_id         = "${var.nhn_network_id}"
      virtual_machine_id = "${element(cloudstack_instance.lbnhn.*.id, count.index)}"
    }
```

This crashes 

```hcl
    resource "cloudstack_nic" "nhn" {
      count              = "${var.lbnhn_count}"
      network_id         = "${var.nhn_network_id}"
      ip_address         = "lookup(var.nhn_address, element(cloudstack_instance.lbnhn.*.name, count.index))"
      virtual_machine_id = "${element(cloudstack_instance.lbnhn.*.id, count.index)}"
    }
```

with the following exception

* cloudstack_nic.nhn.0: Error creating the new NIC: CloudStack API error 401 (CSExceptionErrorCode: 0): unable to verify user credentials and/or request signature
* cloudstack_nic.nhn.1: Error creating the new NIC: CloudStack API error 401 (CSExceptionErrorCode: 0): unable to verify user credentials and/or request signature

### Important Factoids

We're running this against *Cloudstack 4.5.2* as domain admins, and this is supposed to work ref:
https://cloudstack.apache.org/api/apidocs-4.5/domain_admin/addNicToVirtualMachine.html

**Comment by svanharmelen** [comment] 2016-05-19 07:44
@landro could you share a simple config (so without all the interpolations) that generates the error together with the plan and error output it actually generates?

Then I'll use that to start debugging this problem...

**Comment by larstobi** [comment] 2016-05-19 07:55
@svanharmelen 
The lookup ends up with a single IP-address string, but I'll provide the example with just the IP-address:

```
resource "cloudstack_nic" "nhn" {
      count              = "1"
      network_id         = "${cloudstack_network.app.id}"
      virtual_machine_id = "${cloudstack_instance.lbnhn.0.id}"
}
```
vs
```
resource "cloudstack_nic" "nhn" {
      count              = "1"
      network_id         = "${cloudstack_network.app.id}"
      virtual_machine_id = "${cloudstack_instance.lbnhn.0.id}"
      ipaddress          = "1.2.3.4"
}
```

**Comment by svanharmelen** [comment] 2016-05-19 09:41
@landro thanks... Unfortunately I cannot seem to reproduce the problem using this config:

```
provider "cloudstack" {
    api_url = "xxx"
    api_key = "xxx"
    secret_key = "xxx"
}

resource "cloudstack_instance" "foo" {
  count = "1"
  name = "terraform-server"
  service_offering= "tiny"
  network_id = "46b5555a-468e-4ff8-9422-86c87776c8e7"
  template = "Centos7"
  zone = "ZONE1"
  expunge = true
}

resource "cloudstack_nic" "nic1" {
  count = "1"
  network_id = "23829764-3a5c-462c-9d08-13cb6ec108c2"
  ip_address = "10.1.2.222"
  virtual_machine_id = "${cloudstack_instance.foo.0.id}"
}
```

So could you please share a working (minimal, like above) TF config that I can use to reproduce this? Or can you confirm that using the config I pasted here works for you as well?

If this config gives you the same problem, then please run `export TF_LOG=TRACE` and run `terraform apply` again to gather some more detailed logging. If you then can share the log output I can have a closer look...

**Comment by larstobi** [comment] 2016-05-19 10:37
I was not able to reproduce either with this:
```
variable "default_zone" {
  default = "Digipost H2K9"
}

resource "cloudstack_vpc" "default" {
  name = "terraform-ipaddress"
  cidr = "10.90.0.0/16"
  network_domain = "terraform-ipaddress.cloud"
  vpc_offering = "Default VPC offering"
  zone = "${var.default_zone}"
}


resource "cloudstack_network_acl" "foo" {
  name = "foo network ACL"
  vpc_id = "${cloudstack_vpc.default.id}"
}

resource "cloudstack_network" "foo" {
  name = "foo network"
  vpc_id = "${cloudstack_vpc.default.id}"
  cidr = "10.90.1.0/24"
  network_offering = "DefaultIsolatedNetworkOfferingForVpcNetworksNoLB-tellus"
  zone = "${var.default_zone}"
  acl_id = "${cloudstack_network_acl.foo.id}"
}

resource "cloudstack_instance" "foo" {
  count = "1"
  name = "terraform-server"
  service_offering= "Micro Instance"
  network_id = "${cloudstack_network.foo.id}"
  template = "centos-7-5d51eae"
  zone = "${var.default_zone}"
  expunge = true
}

resource "cloudstack_nic" "nic1" {
  count = "1"
  network_id = "a197a740-7482-4bd0-82ba-d7e53dc5cda5"
  ip_address = "146.192.150.168"
  virtual_machine_id = "${cloudstack_instance.foo.0.id}"
}
```

**Comment by landro** [comment] 2016-05-19 10:50
Oh man - found the error - I was missing the "${xxxxx}" in the interpolation string. Maybe it would make sense to verify the input is a valid ip address?

**Comment by svanharmelen** [comment] 2016-05-19 11:37
Ah! I totally missed that as well :wink: Ah well, glad it's fixed now...

I guess it would make sense to add more sophisticated input checks, but for the time being I'm not going to touch on that. Also because that could be a more generic thing that could be added to Terraform core, instead of only the CloudStack provider.

So closing this one for now, of course let me know if anything else pops up...

**Closed by svanharmelen** 2016-05-19 11:37 UTC
Labels: bug, provider/cloudstack
