### ISSUE TITLE
Modules: Dependency checking when deleting a subnet

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/terraform#16361] opened 2017-10-16 08:48 UTC
This issue was originally opened by @sebastus at https://github.com/terraform-providers/terraform-provider-azurerm/issues/400 - but I'm migrating this to Terraform Core since I believe this is a known core issue

---

### Terraform Version
0.10.7-dev

### Affected Resource(s)
Using the "compute" and "network" modules from azure module registry.

### Terraform Configuration Files
```hcl
module "mycompute" {
  source = "Azure/compute/azurerm"
  resource_group_name = "mycompute"
  location = "East US 2"
  admin_password = "ComplxP@ssw0rd!"
  vm_os_simple = "WindowsServer"
  public_ip_dns = "mywinsrv252"
  remote_port = "3389"
  nb_instances = 2
  vnet_subnet_id = "${module.network.vnet_subnets[0]}"
}

module "network" {
  source = "Azure/network/azurerm"
  location = "East US 2"
  resource_group_name = "mycompute"
}
```

### Expected Behavior
all resources should be deleted cleanly

### Actual Behavior
Got an error message saying that the subnet can't be deleted because of a dependency:

* azurerm_subnet.subnet: network.SubnetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet subnet1 is in use by /subscriptions/743f6ed6-83a8-46f0-822d-ea93b953952d/resourceGroups/mycompute/providers/Microsoft.Network/networkInterfaces/nic0/ipConfigurations/ipconfig0 and cannot be deleted." Details=[]

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` the above HCL (in main.tf)
2. delete contents of main.tf
3. `terraform apply`

**Comment by jbardin** [comment] 2017-11-09 21:29
Hi @tombuildsstuff,

This is working as expected, I'm going to close it because we have a recommended way to make it work going forward.

If you remove the configuration, there is no configuration for the provider to use to know how to access the resources. In the next release, all resources will note the specific provider used to create them, and if you attempt to destroy the resource with no provider config it will error out showing the missing provider, rather than use the wrong provider and failing.

In order to remove an entire module containing a specific provider configuration, the provider must be declared in the parent config and passed in via the new providers mapping in the module block. We'll have documentation for this up with the 0.11 release.

**Closed by jbardin** 2017-11-09 21:29 UTC
Labels: core, modules

**Comment by genevievelesperance** [comment] 2017-12-05 19:43
Hey @jbardin I can't seem to find the recommended way forward and am currently seeing this behavior trying to destroy a subnet. It fails for an `InUseSubnetCannotBeDeleted` by the the application gateway ip configuration.

Would you be able to direct me to an issue or doc discussing this as expected behavior? Is the recommended way forward to use the `depends_on` in the application gateway since it references the subnet id in the `gateway_ip_configuration` block?

**Comment by jbardin** [comment] 2017-12-05 22:16
@genevievelesperance,

I think that the issue as I understood it from Tom may have only been hiding this dependency for me. While you will still need to properly declare provider outside of the modules in order to cleanly remove them from the config (see [Providers Within Modules](https://www.terraform.io/docs/modules/usage.html#providers-within-modules)), or use a targeted destroy, there may be still something else going on. I'll investigate further.

**Comment by genevievelesperance** [comment] 2017-12-05 22:29
Opened it as an issue in the azure provider: https://github.com/terraform-providers/terraform-provider-azurerm/issues/608

**Comment by jbardin** [comment] 2017-12-05 23:07
@genevievelesperance, thanks. After some tests here, that does look like a provider issue.

@tombuildsstuff, I think this might be related to the underlying issue that you can't directly depend on a resource attribute, so if an attribute implicitly represents another resource, it needs to be able to follow the lifecycle of the outer resource exactly. I know AWS has a number of these types of resources that are broken out to their own top-level resources for dependency/lifecycle reasons. If this is working how I think it is, the underlying terraform issue that we don't have a way to represent nested resources, but a fix there is going to be a long way off and providers need to work around it for now.
