### ISSUE TITLE
Terraform crash while removing tainted aws_instance

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#2556] opened 2015-06-29 19:53 UTC
Situation: I tainted an `aws_instance` resource, `terraform plan -out plan`, `terraform apply plan`. Looked up a bit further in the logs and found:

```
2015/06/29 14:46:40 terraform-provider-aws: 2015/06/29 14:46:40 [INFO] Terminating instance: i-c8926336
2015/06/29 14:46:40 [DEBUG] vertex root.aws_route_table_association.public: walking
2015/06/29 14:46:40 [DEBUG] vertex root.aws_route_table_association.public: evaluating
2015/06/29 14:46:40 [DEBUG] root: eval: *terraform.EvalSequence
2015/06/29 14:46:40 [DEBUG] root: eval: terraform.EvalNoop
2015/06/29 14:46:40 [DEBUG] root: eval: *terraform.EvalInstanceInfo
2015/06/29 14:46:40 [DEBUG] root: eval: terraform.EvalNoop
2015/06/29 14:46:40 [DEBUG] root: eval: terraform.EvalNoop
2015/06/29 14:46:40 [DEBUG] root: eval: terraform.EvalNoop
2015/06/29 14:46:40 [DEBUG] root: eval: *terraform.EvalOpFilter
2015/06/29 14:46:40 [DEBUG] root: eval: *terraform.EvalSequence
2015/06/29 14:46:40 [DEBUG] root: eval: *terraform.EvalReadDiff
2015/06/29 14:46:40 [DEBUG] root: eval: *terraform.EvalIf
2015/06/29 14:46:40 [ERROR] root: eval: *terraform.EvalIf, err: early exit
2015/06/29 14:46:40 [ERROR] root: eval: *terraform.EvalSequence, err: early exit
2015/06/29 14:46:40 [ERROR] root: eval: *terraform.EvalOpFilter, err: early exit
2015/06/29 14:46:40 [ERROR] root: eval: *terraform.EvalSequence, err: early exit
2015/06/29 14:46:41 terraform-provider-aws: 2015/06/29 14:46:41 [DEBUG] Waiting for instance (i-c8926336) to become terminated
2015/06/29 14:46:41 terraform-provider-aws: 2015/06/29 14:46:41 [DEBUG] Waiting for state to become: terminated
2015/06/29 14:46:51 terraform-provider-aws: 2015/06/29 14:46:51 [TRACE] Waiting 3s before next try
2015/06/29 14:49:04 terraform-provider-aws: Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2015/06/29 14:49:04 terraform-provider-aws: [signal 0xb code=0x1 addr=0x10 pc=0x133736]
```

[Crash log found here.](https://gist.github.com/nathanielks/fad52b836dff67089ad0)

**Comment by catsby** [comment] 2015-11-17 21:26
Hey @nathanielks – sorry for the silence here. 
This looks like an issue in the `aws` library we were using at that time. 
Because it's been some time, we've moved to the officially supported version, and we've not seen other reports of this issue, I'm going to go ahead and close this for now. 

If by chance you can still reproduce this, please let me know. Thanks!

**Closed by catsby** 2015-11-17 21:26 UTC
Labels: bug, crash, provider/aws

**Comment by nathanielks** [comment] 2015-11-17 21:27
sounds great!
