### ISSUE TITLE
Cannot get the state file to update after doing Terraform plan after defining a resource in code with the latest version "0.15.4"

### ISSUE THREAD

**Issue by hiasad** [hashicorp/terraform#28862] opened 2021-06-02 15:45 UTC
Cannot get the state file to update after doing Terraform plan after defining a resource in code with the latest version "0.15.4". Downgrading to 0.14.10 works perfectly

Here is the code which works with 0.14.10

terraform {
  required_version = "<=0.14.10"

  required_providers {
    aws = ">= 3.36"
  }
}

provider "aws" {
  region = "us-east-1"
}

output "message" {
  value = var.bucket_name
}

resource "aws_s3_bucket" "b" {
  bucket = var.bucket_name
  acl    = "private"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

The same code with the latest version 0.15.4 did not work for me and did not update the local terrform.tfstate file on terraform plan

**Comment by alisdair** [comment] 2021-06-02 15:57
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

In this case you're referring to updating the state file after running `terraform plan`. The plan command does not update state, but only proposes the changes that will be made by `terraform apply`.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by alisdair** 2021-06-02 15:57 UTC
Labels: bug, new

**Comment by hiasad** [comment] 2021-06-02 16:25
@alisdair The issue is that after defining a resource the plan command did not show any changes and thought everything is the same. Doing an apply does not do anything either because it thinks no changes are made.

With only downgrading the version it works just fine.

If you think it should be closed, it is alright with me but I was not able to explain why a lower version works and the latest one does not.

Thank you

**Comment by alisdair** [comment] 2021-06-02 18:46
Are you saying that you have a configuration and state file which has a non-empty plan for Terraform 0.14, but the same configuration and state has an empty plan with Terraform 0.15? If so, that is a bug. However, the reproduction steps you gave didn't show this issue for me.

If you apply the above configuration, then run `terraform-0.14 plan` and `terraform-0.15 plan`, both should show no changes. This would be correct behaviour, as Terraform still understands that this bucket exists.
