### ISSUE TITLE
terraform plan freezes on main.tf creating null resource

### ISSUE THREAD

**Issue by Bowowzahoya** [hashicorp/terraform#29715] opened 2021-10-07 07:09 UTC
### Terraform Version

```
Terraform v1.0.8
on windows_amd64
```

### Terraform Configuration Files

```
No configuration file
```

### Debug Output

https://gist.github.com/Bowowzahoya/e071107dfd39d75cb86ee146489d2cdc

### Crash Output

```
No Crash Output
```

### Expected Behavior

```
terraform plan should have executed normally
```

### Actual Behavior

```
terraform plan froze
```

### Steps to Reproduce

```
terraform init
terraform plan
```

### Additional Context

```
I have been trying to run Terraform apply to create an AWS instance, but it keeps on freezing on terraform apply.
To debug, I reinstalled the latest terraform version, started from an empty folder on a basic main.tf creating only a null resource

Contents of main.tf:

provider "null" {}
resource "null_resource" "null_resource" {}

terraform init executes without problems. Freezing occurs on terraform plan.

I am running Terraform directly from Windows PowerShell

Windows 10 Pro
Version 20H2
Processor: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Ram: 16.0 GB (15.8 GB usable)
64-bit operating system, x64-based processor
```

**Comment by Bowowzahoya** [comment] 2021-10-08 02:51
Hi @jbardin,

Thanks for the suggestions. I disabled my VPN and Firewall but I get the same freeze and trace log. Using the command prompt instead of PowerShell also does not make a difference.

Since you are talking about network limitations, could it be related to my location in China behind the Great Firewall or is that not likely?

Kind regards

**Comment by jbardin** [comment] 2022-04-06 15:15
Since we have not had any reproduction or debugging information for this issue I'm going to close the issue for now. If you do have more information, feel free to reply here, or open a new issue with the info generated by a current Terraform release.

Thanks!

**Closed by jbardin** 2022-04-06 15:15 UTC
Labels: bug, windows, waiting-response, new, waiting for reproduction
