### ISSUE TITLE
Crash when accidentally marking "data" element as a "resource"

### ISSUE THREAD

**Issue by alex** [hashicorp/terraform#22440] opened 2019-08-12 15:07 UTC
### Terraform Version
```
alex@penguin /t/x> ./terraform version
Terraform v0.12.6
+ provider.aws v2.23.0
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-east-2"
  version = "~> 2.14"
}

locals {
	permissions = [
		{ actions = [], resources = [] },
	]
}

resource "aws_iam_policy_document" "foo" {
	dynamic "statement" {
		for_each = local.permissions

		content {
			actions = statement.actions
			resources = statement.resources
		}
	}
}
```

### Debug Output

```
alex@penguin /t/x> env TF_LOG=trace ./terraform validate
2019/08/12 11:05:13 [INFO] Terraform version: 0.12.6  
2019/08/12 11:05:13 [INFO] Go runtime version: go1.12.4
2019/08/12 11:05:13 [INFO] CLI args: []string{"/tmp/x/terraform", "validate"}
2019/08/12 11:05:13 [DEBUG] Attempting to open CLI config file: /home/alex/.terraformrc
2019/08/12 11:05:13 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/08/12 11:05:13 [INFO] CLI command args: []string{"validate"}
2019/08/12 11:05:13 [DEBUG] checking for provider in "."
2019/08/12 11:05:13 [DEBUG] checking for provider in "/tmp/x"
2019/08/12 11:05:13 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/08/12 11:05:13 [DEBUG] found provider "terraform-provider-aws_v2.23.0_x4"
2019/08/12 11:05:13 [DEBUG] found valid plugin: "aws", "2.23.0", "/tmp/x/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.23.0_x4"
2019/08/12 11:05:13 [DEBUG] checking for provisioner in "."
2019/08/12 11:05:13 [DEBUG] checking for provisioner in "/tmp/x"
2019/08/12 11:05:13 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2019/08/12 11:05:13 [TRACE] terraform.NewContext: starting
2019/08/12 11:05:13 [TRACE] terraform.NewContext: resolving provider version selections
2019/08/12 11:05:14 [TRACE] terraform.NewContext: loading provider schemas
2019/08/12 11:05:14 [TRACE] LoadSchemas: retrieving schema for provider type "aws"
2019-08-12T11:05:14.109-0400 [INFO]  plugin: configuring client automatic mTLS
2019-08-12T11:05:14.223-0400 [DEBUG] plugin: starting plugin: path=/tmp/x/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.23.0_x4 args=[/tmp/x/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.23.0_x4]
2019-08-12T11:05:14.224-0400 [DEBUG] plugin: plugin started: path=/tmp/x/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.23.0_x4 pid=7998
2019-08-12T11:05:14.224-0400 [DEBUG] plugin: waiting for RPC address: path=/tmp/x/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.23.0_x4
2019-08-12T11:05:14.288-0400 [INFO]  plugin.terraform-provider-aws_v2.23.0_x4: configuring server automatic mTLS: timestamp=2019-08-12T11:05:14.285-0400
2019-08-12T11:05:14.378-0400 [DEBUG] plugin.terraform-provider-aws_v2.23.0_x4: plugin address: address=/tmp/plugin423002330 network=unix timestamp=2019-08-12T11:05:14.378-0400
2019-08-12T11:05:14.378-0400 [DEBUG] plugin: using plugin: version=5
2019/08/12 11:05:14 [TRACE] GRPCProvider: GetSchema
2019/08/12 11:05:14 [TRACE] GRPCProvider: Close
2019-08-12T11:05:14.671-0400 [DEBUG] plugin: plugin process exited: path=/tmp/x/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.23.0_x4 pid=7998
2019-08-12T11:05:14.671-0400 [DEBUG] plugin: plugin exited
2019/08/12 11:05:14 [TRACE] terraform.NewContext: complete
2019/08/12 11:05:14 [INFO] terraform: building graph: GraphTypeValidate
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.ConfigTransformer
2019/08/12 11:05:14 [TRACE] ConfigTransformer: Starting for path: 
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.ConfigTransformer with new graph:
aws_iam_policy_document.foo - *terraform.NodeValidatableResource
------
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.LocalTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.LocalTransformer with new graph:
aws_iam_policy_document.foo - *terraform.NodeValidatableResource
local.permissions - *terraform.NodeLocal
------
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.OutputTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.OutputTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.OrphanResourceInstanceTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.OrphanResourceInstanceTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.StateTransformer
2019/08/12 11:05:14 [TRACE] StateTransformer: state is empty, so nothing to do
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.StateTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.OrphanOutputTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.OrphanOutputTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.AttachResourceConfigTransformer
2019/08/12 11:05:14 [TRACE] AttachResourceConfigTransformer: attaching to "aws_iam_policy_document.foo" (*terraform.NodeValidatableResource) config from t.tf:12,1-41
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.AttachResourceConfigTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.AttachStateTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.RootVariableTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.RootVariableTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.MissingProvisionerTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.MissingProvisionerTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.ProvisionerTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.ProvisionerTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.ModuleVariableTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.ModuleVariableTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.graphTransformerMulti
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ProviderConfigTransformer
2019/08/12 11:05:14 [TRACE] ProviderConfigTransformer: attaching to "provider.aws" provider configuration from t.tf:1,1-15
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ProviderConfigTransformer with new graph:
aws_iam_policy_document.foo - *terraform.NodeValidatableResource
local.permissions - *terraform.NodeLocal
provider.aws - *terraform.NodeApplyableProvider
------
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.MissingProviderTransformer
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.MissingProviderTransformer (no changes)
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ProviderTransformer
2019/08/12 11:05:14 [TRACE] ProviderTransformer: aws_iam_policy_document.foo is provided by provider.aws or inherited equivalent
2019/08/12 11:05:14 [TRACE] ProviderTransformer: exact match for provider.aws serving aws_iam_policy_document.foo
2019/08/12 11:05:14 [DEBUG] ProviderTransformer: "aws_iam_policy_document.foo" (*terraform.NodeValidatableResource) needs provider.aws
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ProviderTransformer with new graph:
aws_iam_policy_document.foo - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
local.permissions - *terraform.NodeLocal
provider.aws - *terraform.NodeApplyableProvider
------
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.PruneProviderTransformer
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.PruneProviderTransformer (no changes)
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ParentProviderTransformer
2019/08/12 11:05:14 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ParentProviderTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.graphTransformerMulti with new graph:
aws_iam_policy_document.foo - *terraform.NodeValidatableResource
  provider.aws - *terraform.NodeApplyableProvider
local.permissions - *terraform.NodeLocal
provider.aws - *terraform.NodeApplyableProvider
------
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.RemovedModuleTransformer
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.RemovedModuleTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.AttachSchemaTransformer
2019/08/12 11:05:14 [ERROR] AttachSchemaTransformer: No resource schema available for aws_iam_policy_document.foo
2019/08/12 11:05:14 [TRACE] AttachSchemaTransformer: attaching provider config schema to provider.aws
2019/08/12 11:05:14 [TRACE] Completed graph transform *terraform.AttachSchemaTransformer (no changes)
2019/08/12 11:05:14 [TRACE] Executing graph transform *terraform.ReferenceTransformer
2019/08/12 11:05:14 [WARN] no schema is attached to aws_iam_policy_document.foo, so config references cannot be detected
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xddc844]

goroutine 1 [running]:
github.com/hashicorp/terraform/lang/blocktoattr.walkVariables(0x22277c0, 0xc000309c30, 0x0, 0xc0000c2001, 0x22277c0, 0xc000309c30, 0x0, 0x0, 0x0, 0x64)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:34 +0x1b4
github.com/hashicorp/terraform/lang/blocktoattr.ExpandedVariables(...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:24
github.com/hashicorp/terraform/lang.ReferencesInBlock(0x22277c0, 0xc000309c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00056a640)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/references.go:68 +0x66
github.com/hashicorp/terraform/terraform.(*NodeAbstractResource).References(0xc000309ce0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/node_resource_abstract.go:192 +0x300
github.com/hashicorp/terraform/terraform.NewReferenceMap(0xc000ca1d10, 0x3, 0x3, 0x3)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/transform_reference.go:402 +0x24a
github.com/hashicorp/terraform/terraform.(*ReferenceTransformer).Transform(0x334ae00, 0xc00002c050, 0x14, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/transform_reference.go:73 +0x71
github.com/hashicorp/terraform/terraform.(*BasicGraphBuilder).Build(0xc0004bd798, 0x0, 0x0, 0x0, 0x332b140, 0xc0004bd7c8, 0x4e55d0, 0xc0000c2000)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph_builder.go:50 +0x477
github.com/hashicorp/terraform/terraform.(*PlanGraphBuilder).Build(0xc000114a80, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph_builder_plan.go:65 +0xbc
github.com/hashicorp/terraform/terraform.(*Context).Graph(0xc000018000, 0x6, 0xc0004bd81e, 0xc0004bd900, 0x1, 0x1, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:292 +0x1b8
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc000018000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:670 +0xf3
github.com/hashicorp/terraform/command.(*ValidateCommand).validate(0xc0001caa80, 0xc00003e300, 0x6, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/validate.go:114 +0x4f9
github.com/hashicorp/terraform/command.(*ValidateCommand).Run(0xc0001caa80, 0xc0000ac030, 0x0, 0x0, 0xc000150160)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/validate.go:70 +0x6c2
github.com/mitchellh/cli.(*CLI).Run(0xc0003143c0, 0xc0003143c0, 0xc00054fd90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:223 +0xaff
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:36 +0x3b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xddc844]

goroutine 1 [running]:
github.com/hashicorp/terraform/lang/blocktoattr.walkVariables(0x22277c0, 0xc000309c30, 0x0, 0xc0000c2001, 0x22277c0, 0xc000309c30, 0x0, 0x0, 0x0, 0x64)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:34 +0x1b4
github.com/hashicorp/terraform/lang/blocktoattr.ExpandedVariables(...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:24
github.com/hashicorp/terraform/lang.ReferencesInBlock(0x22277c0, 0xc000309c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00056a640)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/lang/references.go:68 +0x66
github.com/hashicorp/terraform/terraform.(*NodeAbstractResource).References(0xc000309ce0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/node_resource_abstract.go:192 +0x300
github.com/hashicorp/terraform/terraform.NewReferenceMap(0xc000ca1d10, 0x3, 0x3, 0x3)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/transform_reference.go:402 +0x24a
github.com/hashicorp/terraform/terraform.(*ReferenceTransformer).Transform(0x334ae00, 0xc00002c050, 0x14, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/transform_reference.go:73 +0x71
github.com/hashicorp/terraform/terraform.(*BasicGraphBuilder).Build(0xc0004bd798, 0x0, 0x0, 0x0, 0x332b140, 0xc0004bd7c8, 0x4e55d0, 0xc0000c2000)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph_builder.go:50 +0x477
github.com/hashicorp/terraform/terraform.(*PlanGraphBuilder).Build(0xc000114a80, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph_builder_plan.go:65 +0xbc
github.com/hashicorp/terraform/terraform.(*Context).Graph(0xc000018000, 0x6, 0xc0004bd81e, 0xc0004bd900, 0x1, 0x1, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:292 +0x1b8
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc000018000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/context.go:670 +0xf3
github.com/hashicorp/terraform/command.(*ValidateCommand).validate(0xc0001caa80, 0xc00003e300, 0x6, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/validate.go:114 +0x4f9
github.com/hashicorp/terraform/command.(*ValidateCommand).Run(0xc0001caa80, 0xc0000ac030, 0x0, 0x0, 0xc000150160)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/validate.go:70 +0x6c2
github.com/mitchellh/cli.(*CLI).Run(0xc0003143c0, 0xc0003143c0, 0xc00054fd90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:223 +0xaff
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:36 +0x3b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Crash Output

https://gist.github.com/alex/f7893e0e44d8a22cdc7b2609fb4d25b7

### Expected Behavior

A clean error message

### Actual Behavior

Crash

### Steps to Reproduce

1. Put the HCL file some place
2. `terraform init`
3. `terraform validate`

**Comment by teamterraform** [comment] 2019-08-13 23:26
Hi @alex! Sorry for this crash and thanks for reporting it.

This seems like a bad interaction between the `dynamic` block feature and [the special attributes as blocks decoding mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html) that some providers are using for backward-compatibility with some legacy patterns in Terraform 0.11 and prior, which seems to be enabled for this `statement` block.

In the mean time while we figure out what exactly is going on here, a possible workaround is to eschew this data source altogether and construct the policy JSON directly instead, using [the `jsonencode` function](https://www.terraform.io/docs/configuration/functions/jsonencode.html):

```hcl
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [ for s in local.permissions: {
      Action = s.actions
      Resource = s.resources
    }]
  })
```

`aws_iam_policy_document` was implemented when Terraform did not have a general JSON encoder function and thus generating policy documents dynamically was difficult to do robustly, but `jsonencode` means it's easier to now do it directly, though of course at the expense of not automatically ensuring that the policy JSON has the expected structure.

**Comment by alex** [comment] 2019-08-13 23:29
To be clear, the correct solution is just to use `data` instead of `resource` for `aws_iam_policy_document`.

**Comment by teamterraform** [comment] 2019-08-13 23:29
Oh, on re-read we notice that this specifically happened when using `resource` instead of `data` here. That's a strange issue! But might be explained if the `aws_iam_policy_document` data source is old enough to have been implemented before the data sources feature existed, in which case it was probably originally implemented as a managed resource and the old compatibility mechanism might still be present for it, though apparently no longer working correctly.

When we dig deeper here we should also see if there _is_ still a compatibility shim in place for that and consider removing it, since it's not been needed since Terraform 0.7.

**Comment by danieldreier** [comment] 2020-06-06 00:49
@alex I just tried to reproduce this on 0.13.0 beta 1, and it installed v2.65.0 of the aws provider, which appears to no longer have the `aws_iam_policy_document` resource type. I'm going to close this because I think that makes this report irrelevant. If I'm reading it wrong, please let me know at ddreier@hashicorp.com and I'm happy to re-open this.

**Closed by danieldreier** 2020-06-06 00:49 UTC
Labels: bug, config, crash, v0.12
