### ISSUE TITLE
Missing resources in backend state

### ISSUE THREAD

**Issue by Frank-stuff** [hashicorp/terraform#24708] opened 2020-04-19 23:42 UTC
### Terraform Version

```
Terraform v0.11.14
* provider.aws: version = "~> 2.33"
* provider.google: version = "~> 2.18"
* provider.google-beta: version = "~> 2.17"
* provider.random: version = "~> 2.2"
```

### Terraform Configuration Files

```
```

### Debug Output

```
+ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_pubsub_topic.aap_notification_topic: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.automation.aap.content)
google_pubsub_topic.stuff_content_cs_asset_saved: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.saved)
google_pubsub_topic.stuff_content_cs_asset_published_unsuccessful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.published.unsuccessful)
google_monitoring_notification_channel.content_email: Refreshing state... (ID: projects/sutff-xxxxxxxxx/notificationChannels/937833330622624881)
google_pubsub_topic.stuff_content_cs_asset_published: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.published)
google_pubsub_topic.stuff_content_cs_asset_synced: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.synced)
google_service_account.pubsub-serviceaccount: Refreshing state... (ID: projects/sutff-xxxxxxxxx/serviceAccou...ff-xxxxxxxxx.iam.gserviceaccount.com)
google_pubsub_topic.stuff_content_cs_asset_saved_unsuccessful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.saved.unsuccessful)
google_pubsub_topic.stuff_content_cs_asset_published_successful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.published.successful)
google_service_account.content-auto-serviceaccount: Refreshing state... (ID: projects/sutff-xxxxxxxxx/serviceAccou...ff-xxxxxxxxx.iam.gserviceaccount.com)
google_pubsub_topic.newslink_topic: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.newslink.image)
google_pubsub_topic.stuff_content_cq_asset_published: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cq.asset.published)
google_pubsub_topic.stuff_content_cs_asset_unsuccessful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.unsuccessful)
google_pubsub_topic.stuff_content_cs_asset_saved_successful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.saved.successful)
google_monitoring_notification_channel.content_pagerduty: Refreshing state... (ID: projects/sutff-xxxxxxxxx/notificationChannels/2167840353144477174)
google_pubsub_topic.stuff_content_cs_asset_successful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.successful)
google_monitoring_notification_channel.content_slack: Refreshing state... (ID: projects/sutff-xxxxxxxxx/notificationChannels/9892942757397067417)
google_pubsub_subscription.stuff_content_cs_asset_published_successful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...sset.published.successful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_published_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ontent.cs.asset.published.subscription)
google_pubsub_subscription.stuff_content_cs_asset_published_unsuccessful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...et.published.unsuccessful.subscription)
google_pubsub_subscription.aap_notification_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...nt.automation.aap.content.subscription)
google_pubsub_subscription.stuff_content_cs_asset_saved_unsuccessful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription....asset.saved.unsuccessful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_saved_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ff.content.cs.asset.saved.subscription)
google_pubsub_subscription.newslink_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...content.cs.newslink.image.subscription)
google_project_iam_binding.pubsub-subscriber: Refreshing state... (ID: sutff-xxxxxxxxx/roles/pubsub.subscriber)
google_project_iam_binding.pubsub-publisher: Refreshing state... (ID: sutff-xxxxxxxxx/roles/pubsub.publisher)
google_pubsub_subscription.stuff_content_cq_asset_published_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ontent.cq.asset.published.subscription)
google_pubsub_subscription.stuff_content_cs_asset_unsuccessful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ent.cs.asset.unsuccessful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_successful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ntent.cs.asset.successful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_synced_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...f.content.cs.asset.synced.subscription)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/10109384079382431271)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/12093212229752334831)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/6153301145429108715)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/13692374978947718144)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/18038107203716740020)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/15234615107287900118)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/7076502772298086010)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/15720098185739684308)
google_pubsub_subscription.stuff_content_cs_asset_saved_successful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...cs.asset.saved.successful.subscription)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + google_pubsub_subscription.stuff_content_cs_asset_saved_successful_subscription
      id:                         <computed>
      ack_deadline_seconds:       "600"
      expiration_policy.#:        <computed>
      labels.%:                   "1"
      labels.name:                "stuff_content_cs_asset_saved_successful_subscription"
      message_retention_duration: "604800s"
      name:                       "stuff.content.cs.asset.saved.successful.subscription"
      path:                       <computed>
      project:                    "sutff-xxxxxxxxx"
      topic:                      "stuff.content.cs.asset.saved.successful"


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

+ terraform state list
google_project_iam_binding.pubsub-publisher
google_project_iam_binding.pubsub-subscriber
google_pubsub_subscription.aap_notification_subscription
google_pubsub_subscription.newslink_subscription
google_pubsub_subscription.stuff_content_cq_asset_published_subscription
google_pubsub_subscription.stuff_content_cs_asset_published_subscription
google_pubsub_subscription.stuff_content_cs_asset_published_successful_subscription
google_pubsub_subscription.stuff_content_cs_asset_published_unsuccessful_subscription
google_pubsub_subscription.stuff_content_cs_asset_saved_subscription
google_pubsub_subscription.stuff_content_cs_asset_saved_successful_subscription
google_pubsub_subscription.stuff_content_cs_asset_saved_unsuccessful_subscription
google_pubsub_subscription.stuff_content_cs_asset_successful_subscription
google_pubsub_subscription.stuff_content_cs_asset_synced_subscription
google_pubsub_subscription.stuff_content_cs_asset_unsuccessful_subscription
google_pubsub_topic.aap_notification_topic
google_pubsub_topic.newslink_topic
google_pubsub_topic.stuff_content_cq_asset_published
google_pubsub_topic.stuff_content_cs_asset_published
google_pubsub_topic.stuff_content_cs_asset_published_successful
google_pubsub_topic.stuff_content_cs_asset_published_unsuccessful
google_pubsub_topic.stuff_content_cs_asset_saved
google_pubsub_topic.stuff_content_cs_asset_saved_successful
google_pubsub_topic.stuff_content_cs_asset_saved_unsuccessful
google_pubsub_topic.stuff_content_cs_asset_successful
google_pubsub_topic.stuff_content_cs_asset_synced
google_pubsub_topic.stuff_content_cs_asset_unsuccessful
google_service_account.content-auto-serviceaccount
google_service_account.pubsub-serviceaccount
module.content-monitoring-alerting.google_monitoring_notification_channel.content_email
module.content-monitoring-alerting.google_monitoring_notification_channel.content_pagerduty
module.content-monitoring-alerting.google_monitoring_notification_channel.content_slack
module.content-monitoring-alerting.module.content-asset-published-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-published-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-published-unsuccessful-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-published-unsuccessful-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-unsuccessful-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-unsuccessful-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
+ terraform apply -auto-approve
google_pubsub_topic.stuff_content_cs_asset_published_unsuccessful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.published.unsuccessful)
google_monitoring_notification_channel.content_email: Refreshing state... (ID: projects/sutff-xxxxxxxxx/notificationChannels/937833330622624881)
google_pubsub_topic.newslink_topic: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.newslink.image)
google_monitoring_notification_channel.content_pagerduty: Refreshing state... (ID: projects/sutff-xxxxxxxxx/notificationChannels/2167840353144477174)
google_pubsub_topic.stuff_content_cs_asset_saved: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.saved)
google_monitoring_notification_channel.content_slack: Refreshing state... (ID: projects/sutff-xxxxxxxxx/notificationChannels/9892942757397067417)
google_service_account.pubsub-serviceaccount: Refreshing state... (ID: projects/sutff-xxxxxxxxx/serviceAccou...ff-xxxxxxxxx.iam.gserviceaccount.com)
google_pubsub_topic.stuff_content_cs_asset_saved_unsuccessful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.saved.unsuccessful)
google_pubsub_topic.aap_notification_topic: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.automation.aap.content)
google_pubsub_topic.stuff_content_cs_asset_successful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.successful)
google_pubsub_topic.stuff_content_cs_asset_synced: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.synced)
google_service_account.content-auto-serviceaccount: Refreshing state... (ID: projects/sutff-xxxxxxxxx/serviceAccou...ff-xxxxxxxxx.iam.gserviceaccount.com)
google_pubsub_topic.stuff_content_cq_asset_published: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cq.asset.published)
google_pubsub_topic.stuff_content_cs_asset_unsuccessful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.unsuccessful)
google_pubsub_topic.stuff_content_cs_asset_published_successful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.published.successful)
google_pubsub_topic.stuff_content_cs_asset_saved_successful: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.saved.successful)
google_pubsub_topic.stuff_content_cs_asset_published: Refreshing state... (ID: projects/sutff-xxxxxxxxx/topics/stuff.content.cs.asset.published)
google_pubsub_subscription.stuff_content_cs_asset_successful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ntent.cs.asset.successful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_saved_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ff.content.cs.asset.saved.subscription)
google_pubsub_subscription.stuff_content_cs_asset_published_unsuccessful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...et.published.unsuccessful.subscription)
google_pubsub_subscription.aap_notification_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...nt.automation.aap.content.subscription)
google_pubsub_subscription.stuff_content_cq_asset_published_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ontent.cq.asset.published.subscription)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/13692374978947718144)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/12093212229752334831)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/6153301145429108715)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/15234615107287900118)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/7076502772298086010)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/10109384079382431271)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/15720098185739684308)
google_pubsub_subscription.stuff_content_cs_asset_unsuccessful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ent.cs.asset.unsuccessful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_synced_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...f.content.cs.asset.synced.subscription)
google_monitoring_alert_policy.num-undelivered-messages: Refreshing state... (ID: projects/sutff-xxxxxxxxx/alertPolicies/18038107203716740020)
google_pubsub_subscription.stuff_content_cs_asset_saved_successful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...cs.asset.saved.successful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_published_successful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...sset.published.successful.subscription)
google_pubsub_subscription.stuff_content_cs_asset_published_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...ontent.cs.asset.published.subscription)
google_project_iam_binding.pubsub-subscriber: Refreshing state... (ID: sutff-xxxxxxxxx/roles/pubsub.subscriber)
google_project_iam_binding.pubsub-publisher: Refreshing state... (ID: sutff-xxxxxxxxx/roles/pubsub.publisher)
google_pubsub_subscription.stuff_content_cs_asset_saved_unsuccessful_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription....asset.saved.unsuccessful.subscription)
google_pubsub_subscription.newslink_subscription: Refreshing state... (ID: projects/sutff-xxxxxxxxx/subscription...content.cs.newslink.image.subscription)
google_pubsub_subscription.stuff_content_cs_asset_saved_successful_subscription: Creating...
  ack_deadline_seconds:       "" => "600"
  expiration_policy.#:        "" => "<computed>"
  labels.%:                   "" => "1"
  labels.name:                "" => "stuff_content_cs_asset_saved_successful_subscription"
  message_retention_duration: "" => "604800s"
  name:                       "" => "stuff.content.cs.asset.saved.successful.subscription"
  path:                       "" => "<computed>"
  project:                    "" => "sutff-xxxxxxxxx"
  topic:                      "" => "stuff.content.cs.asset.saved.successful"
google_pubsub_subscription.stuff_content_cs_asset_saved_successful_subscription: Creation complete after 6s

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

+ terraform state list
google_project_iam_binding.pubsub-publisher
google_project_iam_binding.pubsub-subscriber
google_pubsub_subscription.aap_notification_subscription
google_pubsub_subscription.newslink_subscription
google_pubsub_subscription.stuff_content_cq_asset_published_subscription
google_pubsub_subscription.stuff_content_cs_asset_published_subscription
google_pubsub_subscription.stuff_content_cs_asset_published_successful_subscription
google_pubsub_subscription.stuff_content_cs_asset_published_unsuccessful_subscription
google_pubsub_subscription.stuff_content_cs_asset_saved_subscription
google_pubsub_subscription.stuff_content_cs_asset_saved_unsuccessful_subscription
google_pubsub_subscription.stuff_content_cs_asset_successful_subscription
google_pubsub_subscription.stuff_content_cs_asset_synced_subscription
google_pubsub_subscription.stuff_content_cs_asset_unsuccessful_subscription
google_pubsub_topic.aap_notification_topic
google_pubsub_topic.newslink_topic
google_pubsub_topic.stuff_content_cq_asset_published
google_pubsub_topic.stuff_content_cs_asset_published
google_pubsub_topic.stuff_content_cs_asset_published_successful
google_pubsub_topic.stuff_content_cs_asset_published_unsuccessful
google_pubsub_topic.stuff_content_cs_asset_saved
google_pubsub_topic.stuff_content_cs_asset_saved_successful
google_pubsub_topic.stuff_content_cs_asset_saved_unsuccessful
google_pubsub_topic.stuff_content_cs_asset_successful
google_pubsub_topic.stuff_content_cs_asset_synced
google_pubsub_topic.stuff_content_cs_asset_unsuccessful
google_service_account.content-auto-serviceaccount
google_service_account.pubsub-serviceaccount
module.content-monitoring-alerting.google_monitoring_notification_channel.content_email
module.content-monitoring-alerting.google_monitoring_notification_channel.content_pagerduty
module.content-monitoring-alerting.google_monitoring_notification_channel.content_slack
module.content-monitoring-alerting.module.content-asset-published-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-published-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-published-unsuccessful-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-published-unsuccessful-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-unsuccessful-undelivered-messages-alert.google_monitoring_alert_policy.num-undelivered-messages
module.content-monitoring-alerting.module.content-asset-saved-unsuccessful-undelivered-messages-warning.google_monitoring_alert_policy.num-undelivered-messages
```
### Expected Behavior

Create a new google_pubsub_subscription named as stuff_content_cs_asset_saved_successful_subscription

### Actual Behavior

New recourse created, but can't find it in terraform state file. And it caused the next apply failed. We add the terraform state list after terraform apply, but new recourse didn't show in the state list.

**Comment by danieldreier** [comment] 2020-04-23 23:36
Hi! Thanks for reporting this.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I don't have your terraform config, and so I'm stuck and can't move forward.

I also want to highlight that we are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. We're actively working on Terraform 0.13. I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now.

Would you please try against 0.12.24, and please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies, though I understand that isn't always possible.

**Comment by Frank-auckland** [comment] 2020-05-04 08:37
Hey, I think this cause by google Pubsub subscription auto-deleted after 30 days (if no message sends to it). So if you create a Pubsub subscription and delete it. Then apply the terraform, it will create the Pubsub again but delete it in the state file. So the next terraform apply will fail.

**Comment by danieldreier** [comment] 2020-05-19 23:43
I'm going to close this for now because the information is insufficient to quickly reproduce the problem, and because it was reported against 0.11, which we're no longer fixing issues in. Without a full, ready-to-use reproduction case, this is unlikely to get solved, because there's too much unknown in the missing details.

I do believe you're probably having a legitimate issue and I would like to fix it, but I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

If you would like to put the work into creating a full reproduction case on 0.12, I'm happy to re-open the issue and then try to reproduce it.

**Closed by danieldreier** 2020-05-19 23:43 UTC
