### ISSUE TITLE
Specifying RDS password will cause TF to always recreate the DB instance.

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#782] opened 2015-01-13 14:29 UTC
I have declared one RDS db instance in a module, with a password.
First time i run TF apply, it creates the instance. If i run another TF apply, when it refreshes the data from AWS it gets an empty password(because the API does not return the stored password) and then it thinks it needs to change the password and so it deletes the instance and recreates it. 
The workaround i'm using now is to use an empty password and change the password myself later.

**Comment by adamnbowen** [comment] 2015-01-16 23:53
I believe this is a duplicate of #689

**Comment by mitchellh** [comment] 2015-01-17 00:07
It is. Thanks @adamnbowen

**Closed by mitchellh** 2015-01-17 00:07 UTC
Labels: bug, provider/aws
