### ISSUE TITLE
for_each dynamic attribute creation fails because list is empty

### ISSUE THREAD

**Issue by kviktorman** [hashicorp/terraform#24557] opened 2020-04-03 20:36 UTC
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
// # step-1
// # creates new virtual network at the target space/compartment
resource "oci_core_virtual_network" "oci_test_virtual_network" {
  cidr_block     = var.network.networkCIDR
  compartment_id = var.target_deploy_compartment
  display_name   = var.network.networkDisplayName
}

// # step-2
// # creates new virtual subnet at the target space/compartment
// # dependency: oci_core_virtual_network (<-created in step-1)
resource "oci_core_subnet" "oci_test_virtual_network_subnet" {
  compartment_id      = var.target_deploy_compartment
  vcn_id              = oci_core_virtual_network.oci_test_virtual_network.id
  cidr_block          = var.network.subnetCIDR
  display_name        = var.network.subnetDisplayName
  availability_domain = var.network.subnetAvailabilityZone
}

// # step-2 
// # creates new k8s cluster at the target space/compartment
// # dependency: oci_core_virtual_network (<-created in step-1)
resource "oci_containerengine_cluster" "test_cluster" {
  compartment_id     = var.target_deploy_compartment
  kubernetes_version = var.cluster.kubernetesVersion
  name               = var.cluster.kubernetesClusterName
  vcn_id             = oci_core_virtual_network.oci_test_virtual_network.id
}

// # step-2 
// # queries the subnet list for the virutal network
// # dependency: oci_core_virtual_network (<-created in step-1)
// # (I guess since the network id is available it gets executed 
// # before the virtual subnet is created and gets cached) 
data "oci_core_subnets" "subnet_list" {
  compartment_id = var.target_deploy_compartment
  vcn_id         = oci_core_virtual_network.oci_test_virtual_network.id
}

// # step-3 
// # queries the subnet list for the virutal network
// # dependency-1: oci_core_virtual_network (<-created in step-1)
// # dependency-2: data source 
// # ( I guess the data source is evaluated before the virtual network is created
// #  therefore the list is empty)
resource "oci_containerengine_node_pool" "test_node_pool" {
  cluster_id         = oci_containerengine_cluster.test_cluster.id
  compartment_id     = var.target_deploy_compartment
  kubernetes_version = var.cluster.kubernetesVersion
  name               = var.cluster.kubernetesNodePoolName
  node_shape         = var.cluster.kubernetesNodeShape
  node_config_details {

// *******
// this is the part which is not taking into account the subnets 
// and is failing if the network is created from scratch
    dynamic "placement_configs" {
      for_each = [
        for subnet in data.oci_core_subnets.subnet_list.subnets : {
          availabilityDomain = subnet.availability_domain
          subnetId           = subnet.id
      }]

      content {
        availability_domain = placement_configs.value.availabilityDomain
        subnet_id           = placement_configs.value.subnetId
      }
    }
// *******
    size = var.cluster.kubernetesNodeNumber
  }

  node_source_details {
    image_id    = var.cluster.kubernetesNodeImageOCID
    source_type = "IMAGE"
  }
}

output "debug_output" {
  value = data.oci_core_subnets.subnet_list
}

```

### Debug Output

This is what I see after the first `terraform plan` for the dynamic content
```
      + node_config_details {
          + size = 1

          + placement_configs {
              + availability_domain = (known after apply)
              + subnet_id           = (known after apply)
            }
        }
```

If I comment out the step-3 (node pool creation, depending on subnet)
this is the output  after the run:
```
debug_output = {
  "compartment_id" = "ocid1..."
  "id" = "2020-04-03 20:04:59.549972312 +0000 UTC"
  "subnets" = []
  "vcn_id" = "ocid1..."
}
```
### Crash Output

```
Error: "node_config_details.0.placement_configs": required field is not set

  on main.tf line 59, in resource "oci_containerengine_node_pool" "test_node_pool":
  59: resource "oci_containerengine_node_pool" "test_node_pool" {
```
### Expected Behavior

I think the resource in step-3 should be generated without an error. So the dynamic block should be generated based on the new resource created in step-2

### Actual Behavior

When I run the creation from scratch the node pool resources is not generated. At this point I don't know if this is a terraform bug or a provider bug. Can you please have a look. 

I guess that the reason why I'm facing the issue is, because the data source refresh has priority. Since step-2 resources could be depending on the data source it is retrieved early, then it is cached. And since it is populated the step-3 will use it without updating it. 

I guess if that's the case the fix might be just 
* re-run data source refresh after everything has created in step-2. 
* Or maybe refresh all data sources at every step change 

Can I trigger it somehow within the code?

Thanks, Viktor

### Steps to Reproduce
1. `terraform init`
2. `terraform apply` <- it will throw the error
3. `terraform apply` <- it will create the remaining resource

**Comment by kviktorman** [comment] 2020-04-24 22:01
Hi, 
I have done some code restructuring and I have noticed the following.

# 1. restructuring attempt 

* Module 1:
  * vcn creation
  * vcn subnet creation (vcn referenced)
  * (output): return vcn + vcn subnet list which are linked to vcn
* Module 2:
  * container engine creation (reference vcn)
  * node pool creation (referencing container engine and vcn subnets)
  * (input): Module1.output

Result: Empty array was passed from Module 1 to Module 2. I guess, this is, because the same execution order.

# 2. restructuring attempt

* Module 1:
  * vcn creation
  * vcn subnet creation (vcn referenced)
  * (output): return vcn 
* Module 2:
  * container engine creation (reference vcn)
  * node pool creation (referencing container engine and vcn subnets from "data" queried in this module)
  * (input): Module1.output
  * (data): list all the subnets which are linked to vcn 

Result: The resource was created without any error. When I execute the next "plan" or "apply" command, Terraform tells, that replace is needed, because the order of the subnets has changed. 

I have some questions:
* Is it normal, that every API call returns the subnets in different order? (and I should handle it somehow ?)
* Can I rely on combining the two modules like this or this behaviour is due just network latency? In other words can I trust, that the Module 2 creation will start only after every resource creation has finished in the Module 1?

Cheers, 
Viktor

**Comment by danieldreier** [comment] 2020-04-25 00:49
@kviktorman I'm glad you did a bit more troubleshooting on this one, because I was uncertain how to proceed after reading it a few times. Based on your new information, it looks to me like this is primarily a question for either the [Terraform OCI provider](https://github.com/terraform-providers/terraform-provider-oci) or Oracle themselves. I don't know whether the OCI API returns subnets in a different order, for example - that's outside of the scope of Terraform core and gets into the specifics of the cloud provider. 

On your second question, I think you need `depends_on`, which is addressed in https://github.com/hashicorp/terraform/issues/10462. In short - that will be coming in Terraform 0.13, which is being worked on but doesn't have a release date yet.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core. I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

If you have an Oracle support contract, they may be able to answer what the expected behavior is, and how to design this. They're a HashiCorp Partner and I work with them frequently, they have some great engineers, and I know they care quite a bit about people having a good user experience with Terraform and OCI.

I'm going to close this for now, because I don't think this is a bug, though I am empathetic about why this is confusing.

**Closed by danieldreier** 2020-04-25 00:49 UTC

**Comment by kviktorman** [comment] 2020-04-28 11:21
@danieldreier thanks for the detailed reply and pointing me to the right direction. 
I have created two issues in the oci provider repository for my use case. 

I want to make also one correction in what I wrote before. The "2. restructuring attempt" is not working as well, by accident I included another dependency into the passed message. This is why it was working.
