### ISSUE TITLE
Resource 'aws_instance' does not have attribute 'id'

### ISSUE THREAD

**Issue by anmolnagpal** [hashicorp/terraform#5503] opened 2016-03-08 09:30 UTC
I have to launch e.g. 5 EC2 instances.

```hcl
#################################################################################
#ec2 Instance

resource "aws_instance" "mongo" {
    count                       = "11"
    ami                         = "${var.ami_image}"
    instance_type               = "${var.ec2.mongo_instance_type}"
    #count                       = "${var.ec2.mongo_instance_count}"
    key_name                    = "${var.key_name}"
    security_groups             = ["${aws_security_group.mongo.id}"]
    subnet_id                   = "${aws_subnet.mongo-a.id}"
    associate_public_ip_address = "true"
    placement_group = "${aws_placement_group.live.id}"
    #Volume
    root_block_device {
        volume_type = "${var.ec2.mongo_volume_type}"
        volume_size = "${var.ec2.mongo_volume_size}"
        delete_on_termination = "${var.ec2.mongo_delete_on_termination}"
    }
    tags {
        Name        = "mongo-${var.env}-${count.index}"
        Environment = "${var.env}"
    }
}

#Enable/Disable Elastic IP

#resource "aws_eip" "Test1" {
#    instance = "${aws_instance.Test1.id}"
#    vpc      = true
#}

#ebs Volume
resource "aws_ebs_volume" "mongo" {
    availability_zone = "eu-west-1a"
    size = 2
    tags {
        Name        = "mongo-${var.env}"
        Environment = "${var.env}"
    }
}
#ebs Attachment
resource "aws_volume_attachment" "mongo" {

    device_name = "/dev/sdf"
    volume_id = "${aws_ebs_volume.mongo.id}"
    instance_id = "${aws_instance.mongo.id}"
}

#################################################################################
```
After increasing the count from 1 to 2 (Basically anytime I change the count ), I hit the below error. 
```
12:23:31 › terraform plan
Refreshing Terraform state prior to plan...
Error running plan: 1 error(s) occurred:
* Resource 'aws_instance.mongo' does not have attribute 'id' for variable 'aws_instance.mongo.id'
```

**Comment by radeksimko** [comment] 2016-03-08 09:44
Hi @anmolnagpal 
in cases where you have a resource with `count` above 1, you're effectively creating multiple resources which means you have multiple different attributes. This also needs to be reflected when you're referencing these attributes.

I can't remember from the top of my head whether you can attach the same EBS volume to multiple instances, but I guess you can't. Even if you could, it _probably_ wouldn't be a good idea in your case (nodes of MongoDB).

You need to use `count` in other resources (`aws_ebs_volume` & `aws_volume_attachment`) too.

i.e. your example can be modified roughly to this:

```hcl
#ebs Volume
resource "aws_ebs_volume" "mongo" {
    count = 11
    availability_zone = "eu-west-1a"
    size = 2
    tags {
        Name        = "mongo-${var.env}-${count.index}"
        Environment = "${var.env}"
    }
}
#ebs Attachment
resource "aws_volume_attachment" "mongo" {
    count = 11
    device_name = "/dev/sdf"
    volume_id = "${element(aws_ebs_volume.mongo.*.id, count.index)}"
    instance_id = "${element(aws_instance.mongo.*.id, count.index)}"
}
```

Interpolation & built-in functions (including `element`) are documented here:
https://www.terraform.io/docs/configuration/interpolation.html

Admittedly I have not tested this, but it _should_ work. Let me know if it solves your issue.

**Comment by anmolnagpal** [comment] 2016-03-08 10:19
Hi,
After doing the above chage i am getting below error
```
14:17:58 › terraform plan
Refreshing Terraform state prior to plan...


Error running plan: 2 error(s) occurred:

* Resource 'aws_instance.mongo' does not have attribute 'id' for variable 'aws_instance.mongo.id'
* Resource 'aws_ebs_volume.mongo' does not have attribute 'id' for variable 'aws_ebs_volume.mongo.id'
```

**Comment by anmolnagpal** [comment] 2016-03-08 10:39
Hi,
When I comment the below part and run the count stuff its work's. How can I use count with elb?
```
#ebs Volume
resource "aws_ebs_volume" "mongo" {
    count = 11
    availability_zone = "eu-west-1a"
    size = 2
    tags {
        Name        = "mongo-${var.env}-${count.index}"
        Environment = "${var.env}"
    }
}
#ebs Attachment
resource "aws_volume_attachment" "mongo" {
    count = 11
    device_name = "/dev/sdf"
    volume_id = "${element(aws_ebs_volume.mongo.*.id, count.index)}"
    instance_id = "${element(aws_instance.mongo.*.id, count.index)}"
}
```

**Comment by catsby** [comment] 2016-03-10 23:11
Hey all – I'm going to close this issue now as it doesn't seem to be an issue with the codebase. You can learn more about `count` and it's usage at https://www.terraform.io/docs/configuration/interpolation.html 

For ELBs, I imagine you can reference them like so:

```
resource "aws_elb" "controller" {
  ...
  instances = ["${aws_instance.mongo.*.id}"]
}
```

**Closed by catsby** 2016-03-10 23:11 UTC
Labels: provider/aws, question, waiting-response

**Comment by WesleyCharlesBlake** [comment] 2016-03-24 11:49
To confirm, if you have more than one resource, you need to loop through the resources in your `aws_volume_attachment` definition, eg:

```
resource "aws_volume_attachment" "name" {
  device_name = "/dev/xvdf"
  volume_id = "${element(aws_ebs_volume.ebs-vol-name.*.id, count.index)}"
  instance_id = "${element(aws_instance.aws-instance-name.*.id, count.index)}"
}
```

Not a bug, but interpolation error. @catsby is right though, the interpolation docs are pretty clear in this regard
