### ISSUE TITLE
for_each crashes on null_resource with local-exec provisioner

### ISSUE THREAD

**Issue by adarobin** [hashicorp/terraform#22413] opened 2019-08-09 13:47 UTC
### Terraform Version

```
Terraform v0.12.6
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
variable "test" {
    default = {
        foo = "bar"
    }
}

resource "null_resource" "test" {
    for_each = var.test

    triggers = {
        foo = each.key
    }

    provisioner "local-exec" {
        command = "echo ${each.value}"
    }
}
```

### Debug Output

https://gist.github.com/adarobin/5c7a6449bd6c2a0ace6550f9f64219a7

### Crash Output

https://gist.github.com/adarobin/16994b75a44f3bd8eff8efa9287d4d22

### Expected Behavior

The apply was successful.

### Actual Behavior

Terraform crashed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Interestingly, this works and does not crash
```hcl
variable "test" {
    default = {
        foo = "bar"
    }
}

resource "null_resource" "test" {
    for_each = var.test

    triggers = {
        foo = each.key
    }

    provisioner "local-exec" {
        command = "echo ${var.test[each.key]}"
    }
}
```

**Comment by pselle** [comment] 2019-08-09 19:35
@adarobin Thank you for this report! I believe it's a duplicate of https://github.com/hashicorp/terraform/issues/22289, and there's a fix in master that will go out in the next release of Terraform (0.12.7), and I'll leave this open until that's out to help future reporters. Thank you!

**Comment by xbaran** [comment] 2019-08-21 08:52
Same problem here.

**Comment by FrantisekLee** [comment] 2019-08-21 09:14
The same problem...

**Comment by pselle** [comment] 2019-08-22 21:19
Terraform 0.12.7 (with this fix) is now released! https://github.com/hashicorp/terraform/blob/v0.12.7/CHANGELOG.md

**Closed by pselle** 2019-08-22 21:19 UTC
Labels: bug, config, crash
