### ISSUE TITLE
Terraform destroy destroys more resources than expected

### ISSUE THREAD

**Issue by michalmedvecky** [hashicorp/terraform#15789] opened 2017-08-11 17:46 UTC
### Terraform Version
0.9.11

I cannot test with 0.10.0 because there is a [bug](https://github.com/terraform-providers/terraform-provider-openstack/issues/64) preventing me from creating openstack instances.

Actually I don't believe this is provider-specific, but a problem in dependency calculation.

### Problem description

Trying to destroy only one port out ouf `count` destroys all (unrelated) instances using the same array (is this the correct term?).

### Terraform Configuration Files
```hcl
resource "openstack_networking_network_v2" "net-backend" {
  name = "${var.backend_network}"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "net-backend-subnet" {
  name = "${var.backend_network}"
  network_id = "${openstack_networking_network_v2.net-backend.id}"
  cidr = "${var.backend_network_cidr}"
  dns_nameservers = [ "100.127.70.70" ]
  ip_version = 4
  depends_on = ["openstack_networking_network_v2.net-backend"]
}

resource "openstack_networking_port_v2" "test_port_backend" {
  name = "test${count.index+1}"
  count = "3"
  admin_state_up = "true"
  network_id = "${openstack_networking_network_v2.net-backend.id}"
}

resource "openstack_compute_instance_v2" "test" {
  name = "test${count.index+1}"
  count = "3"
  image_id = "66ae409c-f2ea-4a8c-a25c-3859d79f9f33"
  flavor_name = "m1.small"
  key_pair = "misko"
  availability_zone = "mz"

  network {
    port = "${openstack_networking_port_v2.test_port_backend.*.id[count.index]}"  }

}

variable "backend_network" {
  description = "local network name"
}

variable "backend_network_cidr" {
  description = "local network cidr"
}
```

### Expected Behavior
destroy only one port, and the instance that is referring to it 

### Actual Behavior

All my test instances are destroyed:

```
$ terraform-0.9.11 destroy -var-file=sandbox.tfvars -target openstack_networking_port_v2.test_port_backend[2]
Do you really want to destroy?
  Terraform will delete the following infrastructure:
  	openstack_networking_port_v2.test_port_backend[2]
  There is no undo. Only 'yes' will be accepted to confirm

  Enter a value: yes

openstack_networking_network_v2.net-backend: Refreshing state... (ID: d3ebd619-3f2d-45cb-8e28-86da7cdf4cc5)
openstack_networking_port_v2.test_port_backend.2: Refreshing state... (ID: 267f8d1c-1d71-4c12-856a-e19f031bdc15)
openstack_compute_instance_v2.test.1: Destroying... (ID: 6e967dd3-647d-45ad-8724-c1530bafd827)
openstack_compute_instance_v2.test.2: Destroying... (ID: 8c82978f-fb0b-4d3f-bcfb-8e5020f71622)
openstack_compute_instance_v2.test.0: Destroying... (ID: e2e09783-e31a-4dc0-b67d-d4d9a6e60dd0)
```

### Steps to Reproduce
1. `terraform apply` (create all the resources)
2. `terraform destroy -var-file=sandbox.tfvars -target openstack_networking_port_v2.test_port_backend[2]`
3. `yes`

**Comment by apparentlymart** [comment] 2017-08-11 18:05
Hi @michalmedvecky! Sorry this doesn't work as expected.

This is a consequence of how Terraform currently understands `openstack_networking_port_v2.test_port_backend.*.id`, and is a known limitation. The problem is that this splat reference creates a dependency on _all_ of the port instances, rather than just the one indicated by `count.index`.

This is one of the issues on our list for fixing in a forthcoming round of configuration language improvements. Although the design for that is still in progress, and so this might change before actually being released, the sketch right now is to introduce the following alternative syntax which will then allow Terraform to better understand the intent here:

```hcl
# DRAFT: not yet implemented, may change before release
port = "${openstack_networking_port_v2.test_port_backend[count.index].id}"
```

Note that in general we do not recommend using `-target` except in exceptional circumstances. In this situation I'd recommend instead using `terraform taint` to mark specific resources as needing replacement:

```
terraform taint openstack_networking_port_v2.test_port_backend.2
terraform taint openstack_compute_instance_v2.test.2
```

On the next `plan` Terraform will then include a destroy action for these two resources alone, leaving other resources unaffected. (Taint does not consider dependencies.)

(Once we merge #12289 -- which likely won't be until the next major release, due to it being a breaking change -- this syntax will change to `openstack_networking_port_v2.test_port_backend[2]` for consistency with `-target`. Just noting this here in case someone finds this comment in future, after that's been released, and wonders why the above commands don't work anymore.)

**Comment by jzampieron** [comment] 2017-12-30 21:04
Is there a workaround for this limitation?

**Comment by AdrienneCohea** [comment] 2018-07-25 05:09
Yep, what @apparentlymart said about "this splat reference creates a dependency on all of the port instances" is still true in 0.11.7. [Consider the following configuration](https://github.com/AdrianCohea/uwlsg/tree/master/Projects/private-ca):

```
resource "digitalocean_droplet" "control" {
  count              = "${var.counts["control"]}"
  image              = "ubuntu-18-04-x64"
  size               = "${var.control_size}"
  region             = "sfo1"
  name               = "control${count.index + 1}"
  ssh_keys           = ["${digitalocean_ssh_key.ssh.id}"]
  private_networking = true
  tags               = ["hashicorp", "control"]
}

resource "digitalocean_record" "control_fqdns" {
  count  = "${var.counts["control"]}"
  domain = "${var.domain}"
  type   = "A"
  ttl    = 60
  name   = "${element(digitalocean_droplet.control.*.name, count.index)}"
  value  = "${element(digitalocean_droplet.control.*.ipv4_address, count.index)}"
}
```
If I create this and then issue a ```terraform taint digitalocean_droplet.control.1``` that will result in the following plan (destroys and recreates all DNS records rather than the one for ```digitalocean_droplet.control.1```

```
-/+ digitalocean_droplet.control[1] (tainted) (new resource required)
      id:                   "103245727" => <computed> (forces new resource)
      disk:                 "60" => <computed>
      image:                "ubuntu-18-04-x64" => "ubuntu-18-04-x64"
      ipv4_address:         "107.170.249.159" => <computed>
      ipv4_address_private: "10.134.26.84" => <computed>
      ipv6_address:         "" => <computed>
      ipv6_address_private: "" => <computed>
      locked:               "false" => <computed>
      name:                 "control2" => "control2"
      price_hourly:         "0.02232" => <computed>
      price_monthly:        "15" => <computed>
      private_networking:   "true" => "true"
      region:               "sfo1" => "sfo1"
      resize_disk:          "true" => "true"
      size:                 "s-2vcpu-2gb" => "s-2vcpu-2gb"
      ssh_keys.#:           "1" => "1"
      ssh_keys.0:           "22084294" => "22084294"
      status:               "active" => <computed>
      tags.#:               "2" => "2"
      tags.0:               "hashicorp" => "hashicorp"
      tags.1:               "control" => "control"
      vcpus:                "2" => <computed>

-/+ digitalocean_record.control_fqdns[0] (new resource required)
      id:                   "50930957" => <computed> (forces new resource)
      domain:               "adriennecohea.ninja" => "adriennecohea.ninja"
      fqdn:                 "control1.adriennecohea.ninja" => <computed>
      name:                 "control1" => "control1"
      port:                 "0" => <computed>
      priority:             "0" => <computed>
      ttl:                  "60" => "60"
      type:                 "A" => "A"
      value:                "107.170.249.168" => "${element(digitalocean_droplet.control.*.ipv4_address, count.index)}" (forces new resource)
      weight:               "0" => <computed>

-/+ digitalocean_record.control_fqdns[1] (new resource required)
      id:                   "50930956" => <computed> (forces new resource)
      domain:               "adriennecohea.ninja" => "adriennecohea.ninja"
      fqdn:                 "control2.adriennecohea.ninja" => <computed>
      name:                 "control2" => "control2"
      port:                 "0" => <computed>
      priority:             "0" => <computed>
      ttl:                  "60" => "60"
      type:                 "A" => "A"
      value:                "107.170.249.159" => "${element(digitalocean_droplet.control.*.ipv4_address, count.index)}" (forces new resource)
      weight:               "0" => <computed>

-/+ digitalocean_record.control_fqdns[2] (new resource required)
      id:                   "50930958" => <computed> (forces new resource)
      domain:               "adriennecohea.ninja" => "adriennecohea.ninja"
      fqdn:                 "control3.adriennecohea.ninja" => <computed>
      name:                 "control3" => "control3"
      port:                 "0" => <computed>
      priority:             "0" => <computed>
      ttl:                  "60" => "60"
      type:                 "A" => "A"
      value:                "107.170.247.53" => "${element(digitalocean_droplet.control.*.ipv4_address, count.index)}" (forces new resource)
      weight:               "0" => <computed>


Plan: 4 to add, 0 to change, 4 to destroy.
```

It appears at least for now that tainting a resource that is in a collection will cause the taint to cascade to all elements of the collection rather than the single instance of the resource.

**Comment by vaneyckt** [comment] 2019-07-05 14:54
@apparentlymart do you know if this bug is supposed to be fixed in Terraform 0.12 or is still an ongoing issue?

**Comment by rayuduc** [comment] 2020-02-17 09:00
Hello @AdrienneCohea AdrienneCohea,
Am also facing same issue, If I destroy any VM with Index value its deleting all DNS records. And same case with disk If I destroy one disk destroying all VM's, 
splat reference creates a dependency on all instances, hence deleting all instances
rrdatas = ["${google_compute_instance.node.*.network_interface.0.network_ip[count.index]}"

terraform taint is recreating but we want to completely destroy resource
google provider version- google-beta and google latest
terraform version: 0.12.10
```
implicit dependency on google_compute_instance.
terraform destroy -target=“module.testing-vm.google_compute_instance.node[1]”
terraform destroy -target="module.qarc-gcp-bastion.google_compute_disk.node[0]"
google provider version- google-beta and google latest
terraform version: 0.12.10

module/google_vm/google-compute.tf
count = (var.add_external_ip == true ? var.amount : 0)
resource “google_compute_instance” “node” {
count = var.amount

name = format("%s%02d", var.name, count.index + 1)
machine_type = var.machine_type
project = var.test_project
allow_stopping_for_update = true
zone = element(var.zones, count.index%length(var.zones))
tags = var.tags

DNS records explicit definition
depends_on = [google_dns_record_set.dns_record]
boot_disk {
initialize_params {
image = var.boot_disk_image
size = var.boot_disk_size
}
}
network_interface {
subnetwork = var.subnetwork
}

metadata = {
env = var.res_env
}
}

resource “google_dns_record_set” “dns_record” {
count = var.amount
name = “{format("%s%02d", var.name, count.index + 1)}.{var.dns_zone}”
managed_zone = “{var.dns_name}" type = "{var.dns_record_type}”
ttl = “${var.dns_record_ttl}”

compute implicit definition
rrdatas = ["${google_compute_instance.node.*.network_interface.0.network_ip[count.index]}"]
}

================= above module usage
module “dev-test” {
source = “./module/google_vm”
name = "dev-test
amount = 2
machine_type = var.app_machine
project = var.test-project
subnetwork = google_compute_subnetwork.test1_sub_network.self_link
zones = var.vm_zone
dns_record = true
dns_name = var.dns_name
dns_zone = var.dns_zone
dns_record_ttl = var.dns_record_ttl
dns_record_type = var.dns_record_type
tags = [
“env”,
]
label = “dev-test”
}
```

**Comment by a-abella** [comment] 2021-05-15 06:45
Still here as of
```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/aws v3.36.0
```

In my case I'm not splatting explicitly, I'm passing a map of aws_acm_certificate (created with a map for_each) to the for_each input of a aws_acm_certificate_validation. Destroying one cert with `terraform destroy -target 'module.foo.aws_acm_certificate.bar["baz"]'` then wants to destroy all aws_acm_certificate validations.

```
resource "aws_acm_certificate" "env_cert" {
  for_each = aws_route53_zone.environment
  domain_name = each.value["name"]
  subject_alternative_names = [
    "*.${each.value["name"]}"
  ]
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_acm_certificate_validation" "env_cert" {
  for_each = aws_acm_certificate.env_cert

  certificate_arn = each.value["arn"]
  validation_record_fqdns = [
    aws_route53_record.env_cert_validation[each.key]["fqdn"]
  ]
}
```

**Comment by apparentlymart** [comment] 2021-05-17 22:55
Hi all! I'm sorry I neglected to update this sooner.

During the design phase for Terraform v0.12 we realized that there isn't really any practical solution to this because this is a situation where Terraform is forced to do static analysis because `-target` processing happens before any evaluation can begin.

For that reason, I don't expect `-target` will ever become more precise than it currently is. The best way to think about `-target` is that it applies to relationships between whole `resource` blocks rather than to individual instances of resources, because that's fundamentally how all dependency relationships work in Terraform: Terraform needs to build the dependency graph before evaluating any expressions, but resolving either `count` or `for_each` requires evaluating expressions and thus it's too late to contribute more to the dependency graph.

Since `-target` is already documented as being for exceptional use only, we don't intend to make any changes to its behavior in the foreseeable future, and so I'm going to close this issue now to represent that. Although I didn't yet understand this fully when I wrote my opening comment above, we now consider this to be Terraform working as intended, because `-target` is correctly honoring the dependencies to the extent that Terraform tracks them, which is between `resource` blocks as a whole rather than between individual instances of resources.

For some of the use-cases that might cause someone to try `terraform destroy -target=...` you might find the new `-replace` option added in v0.15.2 could meet the need in a slightly different way:

```
terraform apply -replace='module.foo.aws_acm_certificate.bar["baz"]'
```

The command line shown above asks Terraform to treat a no-op or update plan for that resource instance as a replace instead, which means that if you apply the plan Terraform will destroy the existing object associated with that instance and create a new one to replace it. This assumes that your intention was to ultimately create a new object at that address anyway and so `-replace` can do both the destroy and create in a single step. If your intent is to no longer have an object at that address at all then I would suggest to edit the configuration so that the object is no longer declared, and then run `terraform apply` as normal.

Sorry again that I missed updating this one after we completed Terraform v0.12.

**Closed by apparentlymart** 2021-05-17 22:55 UTC
Labels: config, enhancement
