### ISSUE TITLE
Use variable in provider and store provider in variable

### ISSUE THREAD

**Issue by arcenik** [hashicorp/terraform#32755] opened 2023-02-28 17:51 UTC
### Terraform Version

```shell
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.56.0
```

### Use Cases

The idea is to deploy AWS resources in  multiple region using variable.

```terraform
locals {
  aws_regions = {
    ch = "eu-central-2"
    de = "eu-central-1"
  }
}

provider "aws" {
  for_each = locals.aws_regions

  alias  = each.key
  region = local.aws_regions[each.key]
}

resource "aws_vpc" "example" {
  for_each = local.aws_regions

  provider = local.aws_providers[each.key]
  ...
}
```

### Attempted Solutions

As for_each is not yet supported in provider block

```text
The provider argument name "for_each" is reserved for use by Terraform in a future version.
```

I've tried without but it still does not work

```terraform
locals {
  aws_providers = {
    ch = aws.ch
    de = aws.de
  }
}
```

**Comment by crw** [comment] 2023-03-01 02:02
Thanks for the request! I believe this is a duplicate of one of our most venerable issues: https://github.com/hashicorp/terraform/issues/2430 - what do you think? I'll also run this past the core maintainers to see if it is a duplicate. Thanks!

**Comment by arcenik** [comment] 2023-03-01 08:09
There is three subjects in fact:
1. assign a provider to a variable (may be with a prefix like this)

```
locals {
  bla = provider.aws.test
  blu = provider.aws
}
```

2. use variable in provider

```
provider "aws" {
  alias = "test"
  region = local.region
}
```

3. use loop in provider definition

**Comment by jbardin** [comment] 2023-03-01 14:45
This isn't quite the same as 2430, but it's definitely something we've considered for #25244. Closing this so we can track the overall problem as a single issue.

Thanks!

**Closed by jbardin** 2023-03-01 14:45 UTC
Labels: enhancement, new
