### ISSUE TITLE
openstack_compute_floatingip_v2 fixed_ip: "diffs didn't match during apply" for CloudFlare DNS

### ISSUE THREAD

**Issue by dupuy** [hashicorp/terraform#2011] opened 2015-05-19 11:13 UTC
I am generating CloudFlare DNS records for an OpenStack tenant, and because the **access_ip_v4** attribute (The first detected Fixed IPv4 address or the Floating IP) of the `openstack_compute_instance_v2` resource is returning the floating IP, I am using the **fixed_ip** attribute (The fixed IP address corresponding to the floating IP) of the `openstack_compute_floatingip_v2` resource to generate the DNS records for the internal address, e.g.:
```
resource "cloudflare_record" "webserver" {
    domain = "${var.internal_domain}"
    name = "webserver"
    value = "${openstack_compute_floatingip_v2.webserver.fixed_ip}"
    type = "A"
    ttl = 1
}
```

The first time I run `terraform apply` I get the "diffs didn't match during apply. This is a bug with Terraform and should be reported." error.  Running with TF_LOG=1 and editing for clarity, I see the following two diffs:
```
[ERROR] cloudflare_record.webserver: diff one: *terraform.InstanceDiff
{
    Attributes:map[string]*terraform.ResourceAttrDiff
    {
	"name":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"webserver", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"hostname":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"", NewComputed:true, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"type":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"A", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"value":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"${openstack_compute_floatingip_v2.webserver.fixed_ip}", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"ttl":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"1", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"domain":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"example.net", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	}
    },
    Destroy:false, DestroyTainted:false
}
```
```
[ERROR] cloudflare_record.webserver: diff two: *terraform.InstanceDiff
{
    Attributes:map[string]*terraform.ResourceAttrDiff
    {
	"ttl":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"1", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"domain":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"example.net", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"name":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"webserver", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"hostname":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"", NewComputed:true, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	},
	"type":*terraform.ResourceAttrDiff
	{
	    Old:"", New:"A", NewComputed:false, NewRemoved:false,
	    NewExtra:interface{}(nil), RequiresNew:false, Type:0x0
	}
    },
    Destroy:false, DestroyTainted:false
}
```
The thing that doesn't match is that one of the diffs has the "value" key, and the other does not.

Re-applying the plan a second time works normally, and the CloudFlare domain entry for the fixed IP is created.  If the compute instance is destroyed and re-created (with a new fixed IP), the CloudFlare domain entry for the fixed IP is *not* updated in that `terraform apply` run, but *is* updated with the new fixed IP in the *next* `terraform apply`.

I'm pretty sure this has nothing to do with the CloudFlare provider, and everything to do with the OpenStack one, but it's possible that there is an interaction between the two.

**Comment by jtopjian** [comment] 2015-05-24 02:58
I just had a chance to read this over.

I'm pretty sure the core issue is that the `openstack_compute_floatingip_v2` resource can be thought of as dependent on `openstack_compute_instance_v2`. This may be confusing because in the Terraform config, the relationship is reversed: first you create a floating IP and then you create an instance with the result of the floating IP.

Here's what's actually happening:

1. A floating IP is created (let's say `1.2.3.4`). It's fixed IP value is empty.
2. An instance defined and given a floating IP of `1.2.3.4`
3. The request to create the instance is made. It's successful, and it gets a fixed IP.
4. The floating IP is then attached.
5. Before the `create` function ends, a `read` on the instance is performed. This is why/how all values for the instance are filled in when the `apply` is done.

Note what didn't happen here was a refresh or a read on the floating IP resource _after_ the floating IP was attached to the instance. That's why everything works after a manual refresh.

I'm not sure the best way of handling this situation. It's not an uncommon one, either, as I can see this happening in a lot of different scenarios. Maybe there have been features added to Terraform that account for this and I haven't caught up yet.

As a potential workaround, would it be possible to use this instead?

```
resource "cloudflare_record" "webserver" {
    domain = "${var.internal_domain}"
    name = "webserver"
    value = "${openstack_compute_instance_v2.webserver.network.0.fixed_ip_v4}"
    type = "A"
    ttl = 1
}
```

**Comment by jtopjian** [comment] 2015-10-31 12:58
I just confirmed that the workaround I previously mentioned works.

@phinze Is it possible for a resource to trigger a refresh on another? For this example, the Instance needs the Floating IP resource to refresh in order to have the fixed_ip attribute available.

**Comment by phinze** [comment] 2015-11-30 20:43
@jtopjian we don't currently have a facility for this. Perhaps worth opening a fresh core issue to discuss how a feature like this might work?

**Comment by jtopjian** [comment] 2015-11-30 21:51
@phinze Will do! Thanks!

**Comment by jtopjian** [comment] 2016-06-30 06:15
I'm going to close this issue for two reasons:

1. #4118 captures the core problem.
2. The aforementioned "workaround" is actually more than a workaround -- it's really the best way to declare this type of configuration.

However, if someone would like to discuss further, please reopen!

**Closed by jtopjian** 2016-06-30 06:15 UTC
Labels: bug, provider/openstack
