### ISSUE TITLE
unexpected for_each error with lookup() function with an output value

### ISSUE THREAD

**Issue by z15alall** [hashicorp/terraform#31295] opened 2022-06-22 10:06 UTC
### Terraform Version

```
Terraform v1.2.3
on linux_amd64
```

### Terraform Configuration Files

```terraform
module "pubsub" {
  source  = "terraform-google-modules/pubsub/google"
  version = "~> 3.2.0"

  topic      = "tf-topic"
  project_id = local.gcp_project_id
  push_subscriptions = local.computed_push
  pull_subscriptions = [
    {
      name                    = "pull"                                               // required
      ack_deadline_seconds    = 20                                                   // optional
      dead_letter_topic       = "projects/my-pubsub-project/topics/example-dl-topic" // optional
      max_delivery_attempts   = 5                                                    // optional
      maximum_backoff         = "600s"                                               // optional
      minimum_backoff         = "300s"                                               // optional
      filter                  = "attributes.domain = \"com\""                        // optional
      enable_message_ordering = true                                                 // optional
    }
  ]
}

module "cloudrun" {
  source = "./CR/"
  service_name = "testcr"
  gcp_default_region = local.gcp_default_region 
}


locals {
gcp_project_id = "xxxxxxxx"
gcp_default_region = "europe-west4"

concat_push =  [
    {
      name                       = "push"                                               // required
      ack_deadline_seconds       = 20                                                   // optional
      push_endpoint              = module.cloudrun.url
      dead_letter_topic          = "example-dl1234-topic" // optional
      max_delivery_attempts      = 5                                                    // optional
      maximum_backoff            = "600s"                                               // optional
      minimum_backoff            = "300s"                                               // optional
      filter                     = "attributes.domain = \"com\""                        // optional
      enable_message_ordering    = true                                                 // optional
    }
  ]

computed_push =  [for sub in local.concat_push :
 merge(
      {
        name                       = sub.name
        push_endpoint = lookup(sub, "push_endpoint")
      },
      can(lookup(sub,"dead_letter_topic")) ? {
        dead_letter_topic = "projects/${local.gcp_project_id}/topics/${lookup(sub, "dead_letter_topic")}"
      } : {}
 )
]
}
```

Cloud Run Module (in CR folder) : 
```terraform
resource "google_cloud_run_service" "default" {
  name     = var.service_name
  location = var.gcp_default_region

  template {
    spec {
      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}

variable "gcp_default_region" {
  description = "region for the cloud run service"
  type        = string
}

variable "service_name" {
  description = "name of the cloud run service"
  type        = string
}

output "url" {
  description = "cloud run service url"
  value       = google_cloud_run_service.default.status[0].url
}
```

### Expected Behavior
Using this kind of structure (map, merge, can... witch is simplified for this case comparing of our terraform code), the `terraform plan` failed with the error message in the "Actual Behavior" section.

if we use a explicit value instead of the output value of the cloud run url in the _push_endpoint_  `terraform plan` / `terraform apply` work's

```terraform
push_endpoint              = "https://example.com"
```

instead of 

```terraform
push_endpoint              = module.cloudrun.url
```

by the way if i conserve the _push_endpoint_ with the cloud run url output but i remove the **lookup** function inside the **can** like below `terraform plan` / `terraform apply` work's

```terraform
      can(lookup(sub,"dead_letter_topic")) ? {
        dead_letter_topic = "projects/${local.gcp_project_id}/topics/${lookup(sub, "dead_letter_topic")}"
      } : {},
```
If i remove the lookup inside a can, there is no problem to do a `terraform plan` /  `terraform apply`

```terraform
      can(sub.dead_letter_topic) ? {
        dead_letter_topic = "projects/${local.gcp_project_id}/topics/${lookup(sub, "dead_letter_topic")}"
      } : {},
```

So the question is why terraform cannot predict the value of a map when we use a **lookup** inside a merge with an output value of another module ? 

### Actual Behavior
```terraform
module.pubsub.data.google_project.project: Reading...
module.pubsub.data.google_project.project: Read complete after 1s [id=projects/xxxxxx]
╷
│ Error: Invalid for_each argument
│
│   on .terraform/modules/pubsub/main.tf line 46, in resource "google_pubsub_topic_iam_member" "push_topic_binding":
│   46:   for_each = var.create_topic ? { for i in var.push_subscriptions : i.name => i } : {}
│     ├────────────────
│     │ var.create_topic is true
│     │ var.push_subscriptions is list of map of string with 1 element
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this
│ resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
╵
╷
│ Error: Invalid for_each argument
│
│   on .terraform/modules/pubsub/main.tf line 118, in resource "google_pubsub_subscription" "push_subscriptions":
│  118:   for_each = var.create_subscriptions ? { for i in var.push_subscriptions : i.name => i } : {}
│     ├────────────────
│     │ var.create_subscriptions is true
│     │ var.push_subscriptions is list of map of string with 1 element
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this
│ resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
╵
```

### Steps to Reproduce
1. fill the local _gcp_project_id_ with your gcp project id
2. `terraform init`
3. `terraform plan`

**Comment by kmoe** [comment] 2022-06-24 14:32
Thanks for the issue. I've reproduced the behaviour you described using your config, and must admit it is baffling - I wouldn't expect that combination of `can` and `lookup` to result in an unknown value.

We need to investigate further to see whether there is a bug here, but in the meantime you may be able to rewrite the `computed_push` part of your config as follows, which should achieve the same effect without error:

```hcl
  computed_push = [for sub in local.concat_push :
    merge(
      {
        name          = sub.name
        push_endpoint = lookup(sub, "push_endpoint")
      },
      try({
        dead_letter_topic = "projects/${local.gcp_project_id}/topics/${sub.dead_letter_topic}"
      }, {})
    )
  ]

```

**Comment by nfroidure** [comment] 2022-06-30 10:09
May be linked :
```
│ Error: Invalid template interpolation value
│ 
│   on cloudwatch_filters.tf line 46, in resource "aws_cloudwatch_log_metric_filter" "postData_successfullRequests":
│   46:   pattern        = "{ ($.method = \"POST\") && ( $.resourcePath = \"/v0/data/{mlProject}\") && ( $.parameters.mlProject = \"${lookup(var.ml_projects[each.key], "overridenName", "${each.key}")}\" ) && ( $.type = \"success\")}"
│     ├────────────────
│     │ each.key is "my_ml_project"
│     │ var.ml_projects is map of object with 4 elements
│ 
│ The expression result is null. Cannot include a null value in a string template.

```

It is weird since `lookup` is supposed to fallback if the value is null and `each.key` has a value 🤷.

**Comment by hitesharora-efx** [comment] 2023-04-24 03:52
Possibly hitting the same issue, please help to let us know if we have got the solution for the same.

=============================================================
22:35:15    on ../modules/google-pubsub/main.tf line 80, in resource "google_pubsub_subscription" "pull_subscriptions":
22:35:15    80:   ack_deadline_seconds =  "${each.value.ack_deadline_seconds}"
22:35:15      |----------------
22:35:15      | each.value is map of string with 4 elements
22:35:15  
22:35:15  This map does not have an element with the key "ack_deadline_seconds".

**Comment by jbardin** [comment] 2024-03-11 18:45
Marking a closed as `can` can `try` can now return more precise output in current releases. Note we still do not recommend the use of `can` in most situations:

> Warning: The `can` function is intended only for simple tests in variable validation rules. Although it can technically accept any sort of expression and be used elsewhere in the configuration, we recommend against using it in other contexts. For error handling elsewhere in the configuration, prefer to use `try`.

Thanks!

**Closed by jbardin** 2024-03-11 18:45 UTC
Labels: bug, confirmed, v1.2
