### ISSUE TITLE
Data Sources are throwing error "empty tuple" during terraform plan itself for Azure Provider

### ISSUE THREAD

**Issue by surajmuthreja** [hashicorp/terraform#21916] opened 2019-06-27 12:42 UTC
### Terraform Version
Terraform v0.12.3

```
...

### Terraform Configuration Files

# Create Public IP
resource "azurerm_public_ip" "ip_vm" {
    count							= "${length(var.location)}"
    name							= "PublicIP-${1+count.index}"
    location						= "${element(var.location, count.index)}"
    resource_group_name				= "${element(azurerm_resource_group.rg_test.*.name, count.index)}"
    allocation_method				= "Static"

    tags {
        environment = "TestVM"
    }
}

# Create Virtual Machine
resource "azurerm_virtual_machine" "testVM" {
    count							= "${length(var.location)}"
    name                  			= "VM-${1+count.index}"
    location						= "${element(var.location, count.index)}"
    resource_group_name				= "${element(azurerm_resource_group.rg_test.*.name, count.index)}"
    network_interface_ids 			= ["${element(azurerm_network_interface.nic_1.*.id, count.index)}", "${element(azurerm_network_interface.nic_2.*.id, count.index)}"]
	primary_network_interface_id	= "${element(azurerm_network_interface.nic_1.*.id, count.index)}"
    vm_size               			= "${var.vm_size}"

    storage_os_disk {
        name              = "VM-${1+count.index}_OSDisk"
        caching           = "ReadWrite"
        create_option     = "FromImage"
        managed_disk_type = "Standard_LRS"
    }

    storage_image_reference {
        id="${element(var.image_vm, count.index)}"
    }

    os_profile {
        computer_name  = "${element(var.hostname, count.index)}"
        admin_username = "ubuntu"
        custom_data = "${element(data.template_file.user_data.*.rendered, count.index)}"
    }

    os_profile_linux_config {
        disable_password_authentication = true
        ssh_keys {
            path     = "/home/ubuntu/.ssh/authorized_keys"
            key_data = "${var.ssh_key}"
        }
    }

    boot_diagnostics {
        enabled = "true"
        storage_uri = "${element(azurerm_storage_account.storageaccount.*.primary_blob_endpoint, count.index)}"
    }
	
    tags {
        environment = "TestVM"
    }
}


data "azurerm_public_ip" "pub_ip" {
    count					= "${length(var.location)}"
    name					= "${element(azurerm_public_ip.ip_vm.*.name, count.index)}"
    resource_group_name		= "${element(azurerm_resource_group.rg_test.*.name, count.index)}"
    depends_on				= ["azurerm_virtual_machine.testVM"]
}

output "Management_Public_IP" {
  value = "${data.azurerm_public_ip.pub_ip.*.ip_address[0]}"
}

```

### Expected Behavior
Terraform Plan should succeeded without evaluating data resources. It is working fine with v0.11.8 but failing with v0.12.x

### Actual Behavior
Data resources are being evaluated during plan itself. It should not evaluate during plan.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### References
Similar issue is being fixed for OCI provider. Refre below Bug related to this:
https://github.com/hashicorp/terraform/issues/20200

Seems it is not fixed for Azure Provider.

**Comment by rkst** [comment] 2019-06-27 15:09
Duplicate of #21917 
Hi, we think this is the same issue as the one referenced so we're closing this for now, let us know if you think otherwise.

**Closed by rkst** 2019-06-27 15:09 UTC

**Comment by surajmuthreja** [comment] 2019-06-27 16:00
> Duplicate of #21917
> Hi, we think this is the same issue as the one referenced so we're closing this for now, let us know if you think otherwise.

Please confirm if this Bug for Azure Provider will also be tracked from https://github.com/hashicorp/terraform/issues/21917
