### ISSUE TITLE
fmt command doesn't work with heredoc

### ISSUE THREAD

**Issue by yamamoto-febc** [hashicorp/terraform#20563] opened 2019-03-05 04:51 UTC
### Terraform Version

```
$ terraform -v
Terraform v0.12.0-dev20190216H00
```

### Terraform Configuration Files
```hcl
variable foo {
  type    = "string"
  default = <<EOT
EOT
}

variable bar {
type = "string"
default = "will not formatted"
}
```

### Expected Behavior

the body of `bar` should formatted.

### Actual Behavior

the body of `bar` is not formatted.

### Steps to Reproduce

1. `terraform init`
2. `terraform fmt`

### Additional Context

If heredoc is included in tf file, it will not be formatted after heredoc.

**Comment by mildwonkey** [comment] 2019-03-05 16:37
Hi @yamamoto-febc!
I am sorry you've come across this issue. I suspect this is a duplicate of #20541. Can you try adding an extra newline after your heredoc to see if it works? If so, I will close this issue in favor of the one already created

**Comment by yamamoto-febc** [comment] 2019-03-06 01:59
Hi @mildwonkey!  

I think it is different issue from #20541. 
I tried with following tf file:  

```hcl
variable foo {
  type = "string"

  default = <<EOT

dummy-line

EOT

}

variable bar {
type = "string"
default = "is not formated"
}
```

and I did again `terraform fmt`, but it wasn't formatted.

**Comment by mildwonkey** [comment] 2019-03-06 18:21
Thank you @yamamoto-febc!

**Comment by apparentlymart** [comment] 2019-03-06 20:27
I think this is an issue that @mildwonkey spotted in some earlier testing: for some reason a heredoc seems to confuse the formatter's state and make it "lose" a level of indentation, forcing any following blocks to incorrectly have their first level without leading whitespace.

I expect the work here will be to figure out what exactly is getting set incorrectly after the heredoc and to introduce a special rule to avoid that problem.

**Comment by nvtkaszpir** [comment] 2019-03-14 17:26
try with ```hcl

  default = <<-EOT

  dummy-line

  EOT
```
that little tiny dash ;)

**Comment by yamamoto-febc** [comment] 2019-03-14 23:21
Thank you @nvtkaszpir for suggesting!

Unfortunately, the workaround you suggested didn't work for me.
The lines after `EOT` mark are not formatted yet.

**Closed** 2019-03-15 20:55 UTC
Labels: bug, config

**Comment by chris-brace** [comment] 2019-05-28 18:15
This still appears to happen in the release version of v0.12. As an example:

```resource "helm_release" "nginx_ingress" {
  chart      = "stable/nginx-ingress"
  repository = data.helm_repository.stable.metadata[0].name
  version    = var.helm_versions["nginx-ingress"]
  name       = "nginx-ingress-singleton"
  namespace  = "nginx-ingress"

  // This is the aws alb layer 7 stuff
  // https://github.com/helm/charts/tree/master/stable/nginx-ingress#aws-l7-elb-with-ssl-termination
  values = [<<-CONFIG
rbac:
  create: true
controller:
  service:
    enableHttp: false
    targetPorts:
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${data.aws_iam_server_certificate.wildcard.arn}"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
CONFIG
,
]

depends_on = [kubernetes_cluster_role_binding.tiller]
}

data "kubernetes_service" "nginx_ingress" {
metadata {
name = "nginx-ingress-singleton-controller"

# via https://github.com/terraform-providers/terraform-provider-kubernetes/issues/353#issuecomment-470244036
# https://github.com/terraform-providers/terraform-provider-kubernetes/issues/353
# Data sources together with depends_on delay the evaluation, so we
# introduce an implicit dependency by using the namespace attribute.
namespace = helm_release.nginx_ingress.namespace
}
}
```
