### ISSUE TITLE
Azure provider: Use VM image name instead of label

### ISSUE THREAD

**Issue by dyep49** [hashicorp/terraform#3595] opened 2015-10-22 14:00 UTC
Terraform searches for VM images by label. A label is not unique to an image. As a result, Terraform selects the first image with a matching label. In the case of CoreOS, Terraform selects the oldest image. At the very least, users should have the option to create instances by VM image name. 

Here's a terrible, quick workaround I've been using:

https://github.com/dyep49/terraform/commit/24afd1db0b8b16b2f2721c8373419631a00802f0?diff=split

Ignore the changes to config/lang/y.go

**Comment by xied75** [comment] 2015-11-27 13:15
@apparentlymart I love you, so I just deployed CoreOS Alpha 475.1.0 :)

Apparently searching on label is definitely wrong, this should now be a PR and get merged.

Apparently the bunch who code for Azure are busy on coding TF support of the new ARM mode, yet we still need to carry on to make ASM work.

**Comment by jen20** [comment] 2015-11-27 14:51
Hi @xied75. If you want to submit your diff from above as a pull request I'll look at merging it.

Looking at the diff, could you ensure that changes to `config/lang/y.go` or any other automatically generated code are not included as part of the commits though?

**Comment by xied75** [comment] 2015-12-03 16:34
@jen20 Thanks for supporting. I did a try above, yet need some discussion here before I make another try or PR this.

The issue is that in the above change I removed using "label" altogether, only searching on VM image name. I can see the problem immediately with this approach in the sense all current TF files will break. That end user would need to find out the long unique VM image name and update their TF files. Which might not be ideal.

On the other hand, I wonder how other providers handle this? e.g. in aws people use ami number, which is unique and not user friendly at all but the world is happy with that. So I reckon doing the same in azure should be "correct" too.

If backward compatibility is hugely important, I can propose another try:

1, search on VM image name, (can only find 0/1) if not found 
2, search on OS image name, (can only find 0/1) if not found
3, search on VM image by label, (can find 0+) if not found
4, search on OS image by label, (can find 0+) if not found, err

When >1 found, we can't really do anything to help user here, either choose the first or the last, I would prefer the last.

Although this can be smoother, there are too much assumptions made for the user and it could equally confuse him.

I guess searching on label is really a historic event and frankly it doesn't make any real world sense, it's almost like user wants to pay for a VM "Just pick any CoreOS" for me "I don't care which one you pick"...

p.s. In the new ARM mode, it's publisher plus region stuff, with each image a URN, which is much reasonable design, I would rather settle this asap and switch to work on ARM.

**Closed** 2017-06-13 13:33 UTC
Labels: proposal, provider/azure
