### ISSUE TITLE
Issue accessing data from a resource that used for_each

### ISSUE THREAD

**Issue by MehulChamria** [hashicorp/terraform#25027] opened 2020-05-24 23:18 UTC
### Terraform Version

```
Terraform v0.12.25
+ provider.aws v2.63.0

...
```

### Crash Output
```
Error: Unsupported attribute

  on main.tf line 143, in resource "aws_instance" "node":
 143:     vpc_security_group_ids = aws_security_group.ingress-SG-1.*.id

This object does not have an attribute named "id".
```
The code however worked if I referenced it :
```hcl
vpc_security_group_ids = data.aws_security_group.ingress-SG-1["RDP"].id
```
However I am trying to template it and this will obviously kill the point of templating if I had to reference each of the groups by the name manually.
I think I am not referencing it properly.

### Expected Behavior

Terraform should have referenced the security groups created.

### Actual Behavior
```hcl
provider "aws" {
  #access_key = var.aws_access_key
  #secret_key = var.aws_secret_key
  region     = var.region
}

resource "aws_vpc" "vpc-1" {
  cidr_block       = var.vpcCidr
  instance_tenancy = "default"

  tags = {
    Name = "VPC-1"
  }
}

resource "aws_subnet" "subnets" {
    count                   = length(data.aws_availability_zones.azs.names)
    cidr_block              = cidrsubnet(var.vpcCidr,8,count.index)
    vpc_id                  = aws_vpc.vpc-1.id
    map_public_ip_on_launch = true
    availability_zone       = data.aws_availability_zones.azs.names[count.index]
    tags = {
        Name = "Subnet-${count.index + 1}"
    }
}

resource "aws_internet_gateway" "gw-1" {
  vpc_id = aws_vpc.vpc-1.id

  tags = {
    Name = "IGW-1"
  }
}

resource "aws_default_route_table" "rt-1" {
    default_route_table_id = aws_vpc.vpc-1.default_route_table_id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.gw-1.id
  }

  tags = {
    Name = "rt-1"
  }
}

resource "aws_security_group" "ingress-SG-1" { 
    for_each    = var.securityGroupsIngress
    name        = each.value.name
    description = each.value.description
    vpc_id      = aws_vpc.vpc-1.id

    ingress {
        from_port   = each.value.from_port
        to_port     = each.value.to_port
        protocol    = each.value.protocol
        cidr_blocks = each.value.cidr_blocks
    }
}

resource "aws_instance" "node" {
    count                  = var.instanceCount
    ami                    = var.amiID
    instance_type          = var.instanceType
    subnet_id              = aws_subnet.subnets.*.id[count.index % length(data.aws_availability_zones.azs.names)]
    key_name               = var.key_name
    
    vpc_security_group_ids = aws_security_group.ingress-SG-1.*.id

    tags = {
        name = "Node-${count.index}"
    }
```
### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

**Comment by danieldreier** [comment] 2020-05-29 00:56
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. If I've misunderstood your request here and you're trying to report a bug, please feel free to reach out to me directly at ddreier@hashicorp.com and I'm happy to work together to build a good reproduction case. Thanks!

**Closed by danieldreier** 2020-05-29 00:56 UTC
