### ISSUE TITLE
terraform crashed while running "init" with "-from-module"

### ISSUE THREAD

**Issue by jmiltner** [hashicorp/terraform#23337] opened 2019-11-11 09:04 UTC
### Terraform Version
```
Terraform v0.12.9
```

### Debug Output
https://gist.github.com/jmiltner/8b31bef08793e76b612595a28849a551

### Crash Output
https://gist.github.com/jmiltner/dba081c9c0fccfd0f12e0385d9a9ee93

### Expected Behavior
terraform init should have run through and initialized modules

### Actual Behavior
terraform crashed (and asked me to report this crash)

### Steps to Reproduce
Run `terraform init -from-module <path-to-module>` from a directory other than the root module.
(Note that no additional module directory is given as the direct parameter of the call - not sure whether this is relevant)

### Additional Context
- running on macOS 10.14.6
- no .terraformrc file in home directory
- AWS access key and secret in TV_VAR... environment variables

**Comment by pkolyvas** [comment] 2019-11-11 18:37
Thanks for the report @jmiltner .

I spun up a VM running 10.14.6 and reproduced the issue on both `0.12.9` and `0.12.13`.

**Comment by danieldreier** [comment] 2020-06-05 23:58
@pkolyvas and @jmiltner I tried to reproduce this, and wasn't able to on 0.12.9 or 0.12.26, which makes me think I'm probably following the wrong steps. I tried to script the reproduction steps in https://github.com/danieldreier/terraform-issue-reproductions/tree/master/23337 and would appreciate a PR to help get it to the point where I can reproduce it and escalate it to engineers.

**Comment by danieldreier** [comment] 2020-06-06 00:31
Actually, on further investigation, I think this is the same issue as https://github.com/hashicorp/terraform/issues/23010 so I'm going to close this because I have already reproduced it over there. Please let me know if you think this is incorrect (ddreier@hashicorp.com). Thank you again for reporting this!

**Closed by danieldreier** 2020-06-06 00:31 UTC
Labels: bug, cli, crash, v0.12, waiting-response
