### ISSUE TITLE
Cannot add Tag to root_block_device

### ISSUE THREAD

**Issue by Nerika** [hashicorp/terraform#7573] opened 2016-07-11 06:35 UTC
### Terraform Version
`0.6.15`

### Affected Resource(s)
- aws_instance

We are unable to add tags to root_block_devices. We get the error:
` root_block_device.0: invalid or unknown key: tags`

Can you please add this feature?

**Comment by stack72** [comment] 2016-07-11 15:33
Hi @Nerika 

thanks for requesting the feature here. I am going to close this as a duplicate of #3629 as this is where it was first requested

Thanks

Paul

**Closed** 2016-07-11 15:33 UTC
Labels: enhancement, provider/aws
