### ISSUE TITLE
Terraform[1]: Terraform Crash

### ISSUE THREAD

**Issue by vvvssnarayana** [hashicorp/terraform#33248] opened 2023-05-23 17:54 UTC
### Terraform Version

```shell
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v3.54.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
resource "azurerm_resource_group_template_deployment" "workflow" {
  #   depends_on = [azurerm_logic_app_workflow.logicapp]

  resource_group_name = var.resource_group_name
  parameters_content = jsonencode({
    "workflows_dl_la_fin_dev_email_notification_name" = { value = "dl-la-fin-tfm-dev-email-notification" }
    "connections_azureoffice365_externalid"           = { value = "/subscriptions/18183cc4-798d-441e-8e5a-bad7eca3a0eb/resourceGroups/data_lake_finance_dev/providers/Microsoft.Web/connections/azureoffice365" }
  })

  template_content = file(local.arm_file_path)

  # The filemd5 forces this to run when the file is changed
  # this ensures the keys are up-to-date
  name            = "workflow-${filemd5(local.arm_file_path)}"
  deployment_mode = "Complete"

}

```

### Debug Output

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x154
panic({0x24ce1e0, 0x42b3d40})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0xc000196e10, {0xc0027a0000, 0x1b4d2, 0x1b4d2})
        /home/circleci/project/project/internal/backend/remote-state/azure/client.go:89 +0x5a3
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0xc00097e180)
        /home/circleci/project/project/internal/states/remote/state.go:181 +0x3bd
github.com/hashicorp/terraform/internal/states/statemgr.WriteAndPersist({0x218dcef8a40, 0xc00097e180}, 0xc00097e180)
        /home/circleci/project/project/internal/states/statemgr/helper.go:52 +0x49
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0xc0007beef8, {0x2dd9e38, 0xc0009ab1c0}, {0x2dd9e38, 0xc0009ab200}, 0xc0006597a0, 0xc0009ab180)  
        /home/circleci/project/project/internal/backend/local/backend_apply.go:181 +0xeaa
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:316 +0x445

### Expected Behavior

to run succesfully

### Actual Behavior

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x154
panic({0x24ce1e0, 0x42b3d40})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/backend/remote-state/azure.(*RemoteClient).Put(0xc000196e10, {0xc0027a0000, 0x1b4d2, 0x1b4d2})
        /home/circleci/project/project/internal/backend/remote-state/azure/client.go:89 +0x5a3
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0xc00097e180)
        /home/circleci/project/project/internal/states/remote/state.go:181 +0x3bd
github.com/hashicorp/terraform/internal/states/statemgr.WriteAndPersist({0x218dcef8a40, 0xc00097e180}, 0xc00097e180)
        /home/circleci/project/project/internal/states/statemgr/helper.go:52 +0x49
github.com/hashicorp/terraform/internal/backend/local.(*Local).opApply(0xc0007beef8, {0x2dd9e38, 0xc0009ab1c0}, {0x2dd9e38, 0xc0009ab200}, 0xc0006597a0, 0xc0009ab180)  
        /home/circleci/project/project/internal/backend/local/backend_apply.go:181 +0xeaa
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:316 +0x445

### Steps to Reproduce

terraform apply

**Comment by jbardin** [comment] 2023-05-23 18:10
Hi @vvvssnarayana,

I'm going to mark this as a duplicate of the same crash in #28952, but as with any bug you may want to verify that it's not already fixed in a current release.

Thanks!

**Closed by jbardin** 2023-05-23 18:10 UTC
Labels: bug, new
