### ISSUE TITLE
Terraform Provider Acceptance Tests => After applying this test step, the non-refresh plan was not empty.

### ISSUE THREAD

**Issue by littlejo** [hashicorp/terraform#35685] opened 2024-09-06 16:38 UTC
### Terraform Version

```shell
1.9
```

### Terraform Configuration Files

NA

### Debug Output

```
=== RUN   TestAccCiliumInstallResource
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.22.0"
ℹ️  Using Cilium version 1.14.4
🔮 Auto-detected cluster name: kind-chart-testing
🔮 Auto-detected kube-proxy has been installed
    install_test.go:14: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # cilium.test will be updated in-place
          ~ resource "cilium" "test" {
                id          = "cilium"
                # (9 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
🔥 Deleting pods in cilium-test namespace...
🔥 Deleting cilium-test namespace...
⌛ Waiting for cilium-test namespace to be terminated...
⌛ Waiting to disable Hubble before uninstalling Cilium
--- FAIL: TestAccCiliumInstallResource (25.64s)
```

### Expected Behavior

Test Acceptance passed

### Actual Behavior

Test Acceptance failed

### Steps to Reproduce

https://github.com/littlejo/terraform-provider-cilium/tree/tf-upgrade

GitHub Action

### Additional Context

No problem with:
* Terraform 1.5, 1.6, 1.7, 1.8
* Opentofu 1.6, 1.7, 1.8

One Acceptance passed:
https://github.com/opentofu/opentofu/issues/1795#issuecomment-2222316914
Very similar resource but without:
```
	Attributes: map[string]schema.Attribute{
			"ca": schema.ObjectAttribute{
				AttributeTypes: CaAttributeTypes,
			        Computed:       true,
			        Sensitive:      true,
			},
```

**Comment by crw** [comment] 2024-09-06 17:26
Was this meant to be filed to the Terraform repository? I do not recognize the command output (using some automation wrapper, it looks like) nor the significance of whether or not this test passes (e.g., this may or may not have anything to do with the correctness of Terraform's operation.)

Can you provide more details around the expectations of Terraform here? e.g., a configuration that generates the error behavior, an Expected and Actual behavior that relates to the Terraform executable, a stack trace that shows the error you are experiencing? Thanks!

**Comment by jbardin** [comment] 2024-09-06 17:27
Hi @littlejo,

Thanks for filing the issue. I can't run your tests directly, so we're going to need some more information to try and determine what is going on. First things however, could you verify that you are using the latest patch release? Is it possible for you to try the test using a v1.10 alpha release or build terraform from `main`? It looks like a duplicate of #35424, which was fixed upstream.

Thanks!

**Comment by littlejo** [comment] 2024-09-06 19:48
> Is it possible for you to try the test using a v1.10 alpha release or build terraform from main? 

I tested on v1.10 alpha, the bug is fixed on this version.

**Comment by jbardin** [comment] 2024-09-06 19:51
Thanks for confirming! That upstream fix looked exactly like what was happening here.

**Closed by jbardin** 2024-09-06 19:51 UTC
Labels: bug, waiting-response, new, waiting for reproduction
