### ISSUE TITLE
aws_iam_policy_attachment always marked for update with multiple attachments

### ISSUE THREAD

**Issue by boompig** [hashicorp/terraform#14191] opened 2017-05-03 22:54 UTC
Minimal configuration to reproduce:

- create resources of type `aws_iam_policy` with name `foo-policy`
- create resources of type `iam_role`:
    - with name `r1`
    - with name `r2`
    - with name `r3`

For each role, create a separate resource of type `aws_iam_policy_attachment` that attaches the policy `foo-policy` to that role.

Run:

```
tf plan -out plan
tf apply plan
```

The resources will be created. Now run `tf plan` again. You will see something like:

```
~ aws_iam_policy_attachment.r2-attach
    roles.#:          "3" => "1"
    roles.x: "r1" => ""
    roles.y: "r2 => "r2"
    roles.z:  "r3" => ""

~ aws_iam_policy_attachment.r3-attach
    roles.#:          "3" => "1"
    roles.x: "r1" => ""
    roles.y: "r2" => ""
    roles.z:  "r3" => "r3"

~ aws_iam_policy_attachment.r1-attach
    roles.#:          "3" => "1"
    roles.x: "r1" => "r1"
    roles.y: "r2" => ""
    roles.z:  "r3 => ""
```

And it will never go away no matter how many times you apply the plan.

EDIT: terraform version `Terraform v0.9.4`

**Comment by grubernaut** [comment] 2017-05-04 14:36
Hey @boompig, thanks for the issue!

This, unfortunately, is not a bug. The aws_iam_policy_attachment resource can only be used once PER policy resource, as the resource manages all of the role attachments for that IAM Policy. The best workaround for this issue is to create individual policies for each role attachment that you're wanting to attach.

For example, you would need to create separate `aws_iam_policy` resources, one for each attachment in order to resolve the issue you're experiencing here. 

This will prevent Terraform from "clobbering" the policy attachments as you're seeing above. We do mention this in the documentation for the aws_iam_policy_attachment resource, as it's a commonly discovered issue. Closing for now, but happy to discuss further, thanks!

**Closed by grubernaut** 2017-05-04 14:36 UTC
Labels: provider/aws

**Comment by boompig** [comment] 2017-05-04 18:05
Hey @grubernaut, thanks for your response.

I believe that this use case reflects an AWS best practice: create general policies and reuse those policies as building blocks for different roles. Moreover, specifying which roles the policy should attach-to in a single statement, for example like this:

```
resource "aws_iam_policy_attachment" "a1" {
     name = "a1"
     roles = ["app-1-role", "app-2-role", "app-3-role"]
     policy_arn = "read-from-foo-database"
}
```

would break the natural idea of a policy as a small but reusable component, to be shared among logically different roles (for example representing different applications). If you view a policy as a utility class such as "List", imagine having to declare all classes which use List (like specifying exports) in a single document. The inverse is the common pattern: specify "List" as an import by each class that uses it, in multiple places. I believe the same approach is appropriate here.

I further believe, since as you say "it's a commonly discovered issue", there are others who hope to use roles and policies in this way. I hope you'll consider an implementation that allows for this use case.

**Comment by grubernaut** [comment] 2017-05-04 20:18
Hey @boompig, thanks for your response.

We call this out in the documentation note for the `aws_iam_policy_attachment` resource here https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html.
But each `aws_iam_policy_attachment` resource is only meant to be used once for each managed policy. Effectively telling Terraform to "manage all of the attachments for this policy in place". 
The `aws_iam_role_policy_attachment` would probably serve you better in this case, as it attaches a policy to a role and ensures the role keeps that policy. It is also okay to have multiple uses of the `aws_iam_role_policy_attachment` resources for a single policy. 

Hope this helps, thanks!
