### ISSUE TITLE
Unable to express list of maps as a literal in variables

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#7142] opened 2016-06-12 17:03 UTC
Perhaps this one will be a `wontfix` for 0.7.0, but I wanted to get it recorded.

### Terraform Version

master / 2127466280172a7cd0aa1d863cb932aa0107c986 

### Affected Resource(s)

core

### Terraform Configuration Files
```hcl
variable "sgtags" {
  type = "list"
  default = [
    {zone = "a"},
    {zone = "b"},
    {zone = "c"},
  ]
}

resource "aws_security_group" {
  count = 3
  tags = "${var.sgtags[count.index]}"
}
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

3 SGs each with a zone tag.

### Actual Behavior

```
Error loading config: Error parsing /path/to/main.tf: At 4:5: unexpected token while parsing list: LBRACE
```

**Comment by phinze** [comment] 2016-06-12 17:35
Worth noting that a list of maps _can_ be expressed in both `module` and `resource` declarations by repeating blocks.

Examples:

```tf
module "foo" {
  source = "./foo"
  listofmaps {
    foo = 1
  }
  listofmaps {
    bar = 2
  }
}
```

```tf
resource "aws_instance" "foo" {
  ebs_block_device {
    device = "/dev/xvda"
    # ...
  }
  ebs_block_device {
    # ...
    device = "/dev/xvdb"
  }
}
```

**Comment by phinze** [comment] 2016-06-12 17:49
Related a bit to #7030

**Comment by oillio** [comment] 2016-06-13 22:10
Also duplicate of #7034?

**Closed** 2016-07-11 18:15 UTC
Labels: bug, core, release-0.7

**Comment by joelhandwell** [comment] 2017-03-11 23:25
@phinze Would it be beneficial to mention this in https://www.terraform.io/docs/configuration/interpolation.html ?

**Comment by glenjamin** [comment] 2017-03-23 11:11
This is marked as closed, but I can't seem to figure out what the actual syntax is. This seems to produce only a single map:

```tf
variable "list_of_maps" {
    default {
        id = "747381f4"
        key_permissions = ["get"]
        secret_permissions = ["get"]
    }
    default {
        id = "c411a1534b6e"
        key_permissions = ["get"]
        secret_permissions = ["get"]
    }
}
```

**Comment by jamiel** [comment] 2017-05-10 15:51
Syntax is:

```
variable "list_of_maps" {
   type = "list"
   default = [
      {
          field = "value"
      },
      {
          field = "value"
      }
   ]
}

**Comment by joestump** [comment] 2017-07-19 22:51
@phinze in your example, how would you declare `listofmaps` in the module? Also, what happens if you only declare one `listofmaps`? I looked at your `hcl` PR and it wasn't 100% clear. 

My hope is I can do this:

```hcl
variable "listofmaps" { type = "list" }

module "foo" {
  # This would end up as ${var.listofmaps.0}
  listofmaps {
    bar = "baz"
  }
}

**Comment by phinze** [comment] 2017-07-19 23:28
@joestump yep! the variable inside the module will just be "list" as that's the top-level type

**Comment by gazoakley** [comment] 2017-07-24 11:35
For anyone else trying to figure out how to access an attribute of a specific map, try:

`"${lookup(var.var_name[index], "attribute_name")}"`

**Comment by ericlagergren** [comment] 2017-08-24 23:21
@phinze I'm unable to get your example working. See:

```
0:0 /tmp/a $ tree
.
├── a.tf
└── b
    └── b.tf

1 directory, 2 files
0:0 /tmp/a $ cat a.tf
provider "aws" {
  region = "us-west-2"
}

module "b" {
  source = "b/"

  list_of_maps {
    name = "name1"
  }

  list_of_maps {
    name = "name2"
  }

  list_of_maps {
    name = "name3"
  }
}
0:0 /tmp/a $ cat b/b.tf
variable "list_of_maps" {
  type = "list"
}

resource "aws_ecs_cluster" "c" {
  count = "${length(var.list_of_maps)}"
  name  = "${lookup(element(var.list_of_maps, count.index), "name")}"
}
0:0 /tmp/a $ terraform plan
1 error(s) occurred:

* module.b.var.list_of_maps: variable list_of_maps in module b should be type list, got map
```

Yet if I change `list_of_maps` to be `map`, I get

```
Error asking for user input: 1 error(s) occurred:

* module.b.var.list_of_maps: variable list_of_maps in module b should be type map, got list
```

**Comment by phinze** [comment] 2017-08-24 23:28
Hi @ericlagergren - that looks correct from here! I'd recommend posting your repro as a fresh issue and referencing back to this one.

**Comment by agalazis** [comment] 2017-10-30 11:21
the above is not a solution when you want to concatenate a list of maps to another

**Comment by jakubgs** [comment] 2018-09-07 19:53
I think this is still an issue. I really don't see a way of generating a list of maps from a list.
For example:
```tf
locals {
  ports = [22, 80, 443]
}

resource "digitalocean_firewall" "host" {
  name        = "some_name"
  droplet_ids = ["${digitalocean_droplet.host.*.id}"]
  inbound_rule = [
    {
      protocol   = "tcp"
      port_range = "${local.open_ports.*}"
    }
  ]
}
```
I don't see how currently this is possible.

**Comment by hipertracker2** [comment] 2019-02-20 14:29
Could it work if instead of a very limited HCL template we would use a json file?
