### ISSUE TITLE
Re-create Route 53 zone if it was deleted externally to Terraform

### ISSUE THREAD

**Issue by begriffs** [hashicorp/terraform#1383] opened 2015-04-03 18:39 UTC
I manually deleted a Route 53 zone and hoped that `terraform refresh` would notice and rebuild the zone, but this actually causes refresh to die.

```
Error refreshing state: Request failed, got status code: 404. Response: <?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>NoSuchHostedZone</Code><Message>The specified hosted zone does not exist.</Message></Error><RequestId>f5d4c8e5-da27-11e4-ba9f-117f8f1a2a45</RequestId></ErrorResponse>
```

I'm running v0.3.7.

**Comment by catsby** [comment] 2015-04-03 19:03
Hey @begriffs ! 
Sorry for the trouble here. It seems the code for detecting this (a deleted hosted zone, or no such zone) is wrong, and I've opened pull request #1384 to fix that. 

The "correct" behavior here, or at least intended behavior, is for Terraform to wipe the local state clean of that resource. Strictly speaking then, `refresh` does _not_ rebuild anything. Subsequently invoking `plan` or `apply` would then prompt for rebuilding the zone. 

Let me know if that's not clear, or if you disagree on the behavior we can discuss more. 
Thanks!

**Comment by begriffs** [comment] 2015-04-06 03:29
That makes perfect sense -- refresh updates the state, plan displays what will happen and apply makes it so.

Thanks for the fix!

**Comment by catsby** [comment] 2015-04-06 14:31
Great, glad we're on the same page. 
I'll get #1384 merged as soon as I can.
Thanks for opening the issue!

**Comment by catsby** [comment] 2015-04-06 16:11
#1384 was just merged, thanks again!

**Closed** 2015-04-06 16:11 UTC
Labels: provider/aws
