### ISSUE TITLE
Crash dealing with conditional expression

### ISSUE THREAD

**Issue by katcipis** [hashicorp/terraform#31334] opened 2022-06-28 15:40 UTC
### Terraform Version

```
Terraform v1.2.3
on linux_amd64
```

### Terraform Configuration Files

```terraform
locals {
  ternary_result = true ? [
    {
      field = [{}]
    },
    {
      field = [""]
    },
  ] : [null]
}
```

### Debug Output

https://gist.github.com/katcipis/d085081ce380df9d28bfa10296ac5bcf

### Expected Behavior

Conditional expression should work.

### Actual Behavior

Crashed.

### Steps to Reproduce

1. `terraform validate`

### Additional Context

Nothing that I'm aware, just run `terraform validate` on a terminal and it crashes.

This snippet was extracted from a more complex code that was panicking, I just kept reducing it until I got this, which seems to be the minimal example to reproduce this particular issue.

### References

This seems similar to #31269, but not sure if it is actually a duplicate.

**Comment by jbardin** [comment] 2022-06-28 15:45
Thanks @katcipis, this is a duplicate of #31269.

**Closed by jbardin** 2022-06-28 15:45 UTC
Labels: bug, duplicate
