### ISSUE TITLE
XML syntax error on line 1: illegal character code U+001F

### ISSUE THREAD

**Issue by Mykolaichenko** [hashicorp/terraform#5894] opened 2016-03-29 09:54 UTC
Hi!
I have a very big problem with terraform + vSphere. 
It almost not working. 
Here is more information about problem:
I tried out all versions of this provider, but haven't anything positive result. 
https://github.com/rakutentech/terraform-provider-vsphere/issues/31
If needed, i can describe more information. 
As key, my vSphere 6.0 hosted on OVH, maybe i will mail to them with same issue? 
Thanks a lot,
Oleg.

**Comment by radeksimko** [comment] 2016-03-29 10:31
@Mykolaichenko To clarify - are you using Terraform's built-in vsphere provider or https://github.com/rakutentech/terraform-provider-vsphere as a plugin?

**Comment by Mykolaichenko** [comment] 2016-03-29 10:41
@radeksimko Of course first of all i tried with generic built-in provider, but it isn't working for me. I tried  Terraform v0.6.12 and Terraform v0.6.14, but it isn't working. 
After that i tried  with all that i found in internet :)

**Comment by radeksimko** [comment] 2016-03-29 10:50
In that case (built-in provider) would you mind adding a repro case in the form of Terraform code? I can see the logs in https://github.com/rakutentech/terraform-provider-vsphere/issues/31#issuecomment-202800441 but whoever comes here to eventually fix it needs to be able to reproduce this easily.

**Comment by Mykolaichenko** [comment] 2016-03-29 12:07
Yes, of course.

Here is version: 
```
mykolaichenko:vsphere mukolaich$ terraform -v
Terraform v0.6.14
```

Content of provider.tf:
```
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"
}
```

Content of variables.tf: 
```
variable "vsphere_user" {
	default = "admin"
}
variable "vsphere_password" {
	default = "password"
}
variable "vsphere_server" {
	default = "pcc-ip-address.ovh.com"
}
```

Contents of test.tf:
```
resource "vsphere_virtual_machine" "haproxy" {
    name = "haproxy.bla.private"
    datacenter = "pcc-ip-address_datacenter2233"
    cluster = "Cluster2"
    resource_pool = "m2"
    vcpu = 2
    memory = 4096
    disk {
        datastore = "pcc-number"
        template = "ubuntu-14.04.04-0.4"
    }
    gateway = "10.10.18.1"
    network_interface {
        label = "VLAN18"
        ipv4_address = "10.10.18.101"
        ipv4_prefix_length = "24"
    }
    dns_suffixes = ["bla.private"]
    dns_servers = ["8.8.8.8", "8.8.4.4"]
    domain = "bla.private"
}
```

Here is full trace of command output:  [click](http://paste.ofcode.org/YpgmiB7HvSXBSkjF3mZpDG)

To reproduce this you may create suggested files and run ` "terraform apply"`

Thanks a lot.

**Comment by Mykolaichenko** [comment] 2016-03-31 15:46
Also I have VMware vCenter Server 6. Does Terraform supports it API?

**Comment by chrislovecnm** [comment] 2016-04-15 21:22
@Mykolaichenko yes vsphere 6 is supported, and where is the stack trace?

**Comment by chrislovecnm** [comment] 2016-04-16 20:33
@Mykolaichenko can you reproduce any of this using [govc](https://github.com/vmware/govmomi/tree/master/govc)?

**Comment by chrislovecnm** [comment] 2016-04-19 17:35
@Mykolaichenko please respond otherwise we will close this.  Please feel free to reopen, but I am guessing that you having a api level issue.

**Comment by Mykolaichenko** [comment] 2016-04-20 05:51
@chrislovecnm  i will get you additional info, sorry for stack trace - that service not stored shared code permanently

**Comment by chrislovecnm** [comment] 2016-05-13 13:36
@Mykolaichenko ping

**Comment by chrislovecnm** [comment] 2016-05-17 15:55
@Mykolaichenko we need to close this because of inactivity :)  Please feel free to reopen if this continues to be an issue!

@jen20 @stack72 @phinze can we get this closed

**Comment by chrislovecnm** [comment] 2016-05-23 19:39
@jen20 please close as well ;)

**Closed** 2016-05-23 21:23 UTC
Labels: bug, provider/vsphere
