### ISSUE TITLE
JSON Outputs Encode Ampersands Which Break Output URLs

### ISSUE THREAD

**Issue by martinpeck** [hashicorp/terraform#31756] opened 2022-09-08 07:44 UTC
### Terraform Version

```shell
Terraform v1.1.5
on linux_amd64
```

### Terraform Configuration Files

```terraform
output "connection_uri" {
  value = "http://example.com?foo=bar&hello=world"
}
```

### Debug Output

$ terraform output -json connection_uri
"http://example.com?foo=bar\u0026hello=world"

### Expected Behavior

The following is the expected output (notice that the `&` in the querystring is preserved

```
terraform output -json connection_uri
"http://example.com?foo=bar&hello=world"
```

### Actual Behavior

Notice that the ampersand has been encoded unnecessarily, breaking the URL if used in downstream services.

```
terraform output -json connection_uri
"http://example.com?foo=bar\u0026hello=world"
```

### Steps to Reproduce

Create `main.tf` containing the following...

``` terrform
output "connection_uri" {
  value = "http://example.com?foo=bar&hello=world"
}
```

Perform the following:
1. `terraform init`
2. `terraform apply`
3. `terraform output -json connection_uri`

### Additional Context

I am aware of this closed issue:

https://github.com/hashicorp/terraform/issues/22987

I am also aware that this was previously addressed by adding additional documentation:

https://github.com/hashicorp/terraform/pull/26122

While this encoding is not a problem from a JSON point of view, and is "conservative" in as much as it's performing HTML encoding on top of regular JSON encoding, this behaviour breaks any connection string or url that contains a querystring.

Is there is any possibility of either changing this behaviour, or adding an additional output format (e.g. `-json_strict`) to remove this non-standard JSON encoding, that would be ideal.

**Comment by HariVamsiK** [comment] 2022-09-08 12:52
Hi
I want to work on this issue. Could you please assign it to me, it would be beneficial for my academics too.
Thanks

**Comment by apparentlymart** [comment] 2022-09-08 16:37
Hi @martinpeck! Thanks for reporting this.

I'd like to understand a bit more about what exactly the problem is here. The string that `jsonencode` is producing does seem to be valid JSON, although admittedly not the _most normalized_ possible JSON.

Are you passing this result to some other software whose JSON parser does not handle unicode character escape sequences? Would it be possible to instead correct that software's JSON parser to support JSON as specified?

The current behavior of `jsonencode` is a compatibility constraint for Terraform because existing modules use its result in contexts where any change to the sequence of characters it returns would be disruptive, such as in the `user_data` argument of `aws_instance` where any change would cause the AWS provider to propose entirely replacing the existing EC2 instance. Therefore in order to change its existing results in any way we'd need to have a very strong rationale for making a pragmatic exception to [the v1.0 Compatibility Promises](https://www.terraform.io/language/v1-compatibility-promises).

**Comment by martinpeck** [comment] 2022-09-08 16:56
There's more detail here: https://github.com/microsoft/AzureTRE/issues/2549

The code in question is using a Porter bundle (porter.sh) which, in turn, calls Terraform and then passes back the outputs.

Porter essentially calls `terraform output -json xxxx` for the outputs. You can see this here:

https://github.com/getporter/terraform-mixin/blob/main/pkg/terraform/terraform.go#L56

As you say, this isn't related to direct use of `jsonencode`. It's just the outputs.
But, I guess, if back compat is still a concern then adding an additional `-json-strict` (or something like that) would allow and opt-in approach to pure JSON formatting.

**Comment by apparentlymart** [comment] 2022-09-08 17:02
Thanks for the extra context, @martinpeck.

The code you linked to suggests that this other software is asking Terraform for JSON output but then not actually parsing it as JSON.

Given that, I would suggest one of the following as a way to address this without Terraform changing:
* Pass the `out` buffer to [`json.Unmarshal`](https://pkg.go.dev/encoding/json#Unmarshal) to parse that result as a JSON string. 

    For example:

    ```go
    var outString string
    err := json.Unmarshal(out, &outString)
    ```

    `outString` will then contain the original URL that was JSON encoded.
* Run `terraform output -raw OUTPUTNAME` instead, and then return literally the content of `out` without any further processing.

Consuming Terraform's JSON output with anything other than a JSON parser is not supported, but for output values in particular we have this `-raw` mode as an alternative for use with systems that cannot parse JSON. The Go standard library does have a built-in JSON parser, so there isn't really a strong _need_ to use `-raw` here, but if you know the output will always be a string anyway (which seems to be the case based on existing assumptions about quotes) then there's also no harm in using the raw mode.

**Comment by martinpeck** [comment] 2022-09-08 18:52
The code I linked to isn't in my control. It sits between Terraform and user code (e.g. my code) and simply passes the value back to the caller. In my case, the output is a URL and so this library passes the JSON back to me, but with this unconventional encoding applied.

Keep in mind that this problem is also seen if you do this...

```
terraform output -json
```

i.e. you ask for ALL output values, in a JSON format. This is common if you expect to consume the output programmatically, or you intend to return it as part of an API call. This will also cause this problem.

e.g. if you have this...

``` terraform
output "some_number" {
  value = 1
}

output "some_bool" {
  value = true
}

output "string_that_will_break" {
  value = "Simon & Garfunkel"
}

output "connection_uri" {
  value = "http://example.com?foo=bar&hello=world"
}
```

... and then run this command...

```
$ terraform output -json
```

... you get this JSON output (with the broken URL)...

``` json
{
  "connection_uri": {
    "sensitive": false,
    "type": "string",
    "value": "http://example.com?foo=bar\u0026hello=world"
  },
  "some_bool": {
    "sensitive": false,
    "type": "bool",
    "value": true
  },
  "some_number": {
    "sensitive": false,
    "type": "number",
    "value": 1
  },
  "string_that_will_break": {
    "sensitive": false,
    "type": "string",
    "value": "Simon \u0026 Garfunkel"
  }
}
```

Using `-raw` is not appropriate here, and there's no way I can know whether a given output parameter will need to be patched up because of this HTML-focused view of JSON formatting.

**Comment by martinpeck** [comment] 2022-09-08 18:53
In the above example, what I want to see returned is the following (which is 100% valid JSON):

```json
{
  "connection_uri": {
    "sensitive": false,
    "type": "string",
    "value": "http://example.com?foo=bar&hello=world"
  },
  "some_bool": {
    "sensitive": false,
    "type": "bool",
    "value": true
  },
  "some_number": {
    "sensitive": false,
    "type": "number",
    "value": 1
  },
  "string_that_will_break": {
    "sensitive": false,
    "type": "string",
    "value": "Simon & Garfunkel"
  }
}
```

**Comment by apparentlymart** [comment] 2022-09-09 00:52
Hi @martinpeck,

It seems like we find ourselves in a situation where we're considering changing a specification-permitted behavior in Terraform in order to work around a parser bug in some other software: this other software is asking Terraform to generate JSON but then not actually parsing the result as required by the JSON specification, and that is why you are not getting the result you intended.

We are typically willing to be pragmatic, but it seems like first we should try to exhaust the possibility of that other software becoming a correct implementation of Terraform's existing output format. In particular, this software will also fail to correctly handle _required_ escape sequences like `\n` in a multi-line string, and there's no way we could change Terraform's JSON generator to avoid generating those sequences.

I understand that you do not directly control that software's behavior, but the same can also be said for Terraform and yet we are here discussing the possibility of changing Terraform. :grinning: 

I see that you've already opened getporter/terraform-mixin#94 to discuss the problem upstream and that this codebase had previously been using the `-raw` mode but apparently switched to JSON mode in order to support returning non-string values, as discussed in getporter/terraform-mixin#89. Thanks for starting that discussion!

While I find the signature of that function rather confusing (it seems to return the full JSON data in most cases but trim off the quotes only if it happens to be a string :confused:), I believe there is a way to preserve that behavior while still using an actual JSON parser to handle the string case. I don't have a development environment for this codebase nor the time to learn how to create one but an untested hypothetical example would be:

```go
func (m *Mixin) getOutput(outputName string) ([]byte, error) {
	cmd := m.NewCommand("terraform", "output", "-json", outputName)
	cmd.Stderr = m.Err

	// Terraform appears to auto-append a newline character when printing outputs
	// Trim this character before returning the output
	out, err := cmd.Output()
	if err != nil {
		prettyCmd := fmt.Sprintf("%s %s", cmd.Path, strings.Join(cmd.Args, " "))
		return nil, errors.Wrap(err, fmt.Sprintf("couldn't run command %s", prettyCmd))
	}
	out = bytes.TrimRight(out, "\n")

	// For any JSON string result we'll return the content of the string without
	// any quoting or escaping.
	var outString string
	if err = json.Unmarshal(out, &outString); err == nil {
		return []byte(outString), nil
	}

	// For all other JSON types we'll return the raw JSON syntax directly.
	return out, nil
}
```

Would you mind taking this discussion to the issue you already opened in the other repository for now, and proposing something like the above as a way to address it? I believe this will make the program return the result you want for this URL and for any other string containing valid JSON escape sequences, without affecting the program's interpretation of non-string values.

If there is a strong technical reason why this other program cannot become a correct client of Terraform's JSON format then we may consider changing Terraform's JSON format to accommodate that, but I think it would be prudent to first attempt to make this external client behave correctly first.

**Comment by martinpeck** [comment] 2022-09-09 15:52
Hi @apparentlymart

Thanks for the code. I will continue the conversation with Porter. I'm not sure, however, that I understand how this will fix the situation. Are you saying that the encoding of ampersands only occurs during `json.Unmarshal`, and that the `out` variable will essentially contain the `raw` text (with the ampersand in place)?

However, I have to say that asking Porter to make this change is tactical fix, and a "fall back" for the real fix. 

For me, the real fix is for Terraform to either perform JSON formatting without converting ampersands, or to provide a facility for this formatting (e.g. an additional output format). Converting ampersands is not part of the JSON encoding spec, and isn't required for JSON encoding. This would fix my situation, and all future situations. It would fix the issue I've raised above, where the entire set of outputs are requested using `terraform output -json` and the URLs and strings containing ampersands are return in an incorrect manner.

Out of interest, would you be interested in a PR to address this? If so, which option do you see being best...?

1. Change the current behaviour of the `output` command such that the `-json` format does not encode ampersands in this way
2. Add an additional format, named `-json-strict` that generates JSON using a standard JSON encoding, while `-json` continues to function as it does today (maintaining back compat)

FYI another bug somewhat related to this: #22987

**Comment by apparentlymart** [comment] 2022-09-09 15:55
The bug I am pointing out here is that `terraform output -json` is defined to return JSON and so it's _incorrect_ to parse it with anything other than a valid JSON parser.

The code I wrote above uses Go's JSON parser to, in effect, recover the same result as this codepath would previously have got from `terraform output -raw` even though it's using `terraform output -json`. Instead of taking the raw bytes is it did originally, or doing weird quotes trimming as it does now, it will instead probe to see if the output is a valid JSON string and decode that string if so. If not, it will just return the raw JSON bytes which seems to match the intent of the change which introduced this bug.

**Comment by martinpeck** [comment] 2022-09-09 16:30
Right. Makes sense. I've linked to your comments within https://github.com/getporter/terraform-mixin/issues/94 and, hopefully, a change in that code will fix things.

I appreciate the back and forth on this issue @apparentlymart. It's been really helpful in getting a better understanding of things. 

Thank you for your support!

**Comment by alisdair** [comment] 2022-09-15 13:03
This appears to have been addressed by the getporter/terraform-mixin maintainers, so I'm going to close this issue out. Let me know if I've misunderstood. Thanks for the report!

**Closed by alisdair** 2022-09-15 13:03 UTC
Labels: bug, new

**Comment by martinpeck** [comment] 2022-09-15 13:05
Thanks @alisdair and @apparentlymart.

Yes…this has been addressed in porter. Thanks for the conversation, which really helped my understanding of the underlying issue.

**Comment by martinpeck** [comment] 2022-09-15 13:06
(And apologies for not coming back here and closing it myself)
