### ISSUE TITLE
Ability to ignore changes of parameters in a set of blocks

### ISSUE THREAD

**Issue by PolarPayne** [hashicorp/terraform#31000] opened 2022-05-04 17:47 UTC
### Terraform Version

```
Terraform v1.1.9
on linux_amd64
```

### Terraform Configuration Files

```terraform
resource "aws_cloudfront_distribution" "distribution" {
  # ... omitted ...

  lifecycle {
    ignore_changes = [origin.0.origin_path]
  }

  origin {
    domain_name = var.content_bucket.bucket_domain_name
    origin_id   = "default"
    origin_path = var.path

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.origin_access_identity.cloudfront_access_identity_path
    }
  }
}
```

### Debug Output

```
Error: Cannot index a set value

  on ../modules/cdn/cloudfront.tf line 40, in resource "aws_cloudfront_distribution" "cf_distribution":
  40:     ignore_changes = [origin.0.origin_path]

Block type "origin" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
```

### Expected Behavior

I would expect to be able to somehow ignore changes in a set of blocks.

### Actual Behavior

It is not possible to ignore changes of a set. See [the comment I made in the AWS provider repo](https://github.com/hashicorp/terraform-provider-aws/issues/24546#issuecomment-1117628708) about this issue.

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/24546

**Comment by jbardin** [comment] 2022-05-04 17:52
Duplicate of #26359

**Closed by jbardin** 2022-05-04 17:52 UTC
Labels: bug, new
