### ISSUE TITLE
Terraform Crash - [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"

### ISSUE THREAD

**Issue by AErmie** [hashicorp/terraform#26062] opened 2020-08-31 16:00 UTC
### Terraform Version
```
Terraform version: 0.13.1
Go runtime version: go1.14.7
```

### Terraform Configuration Files

```terraform
[See code repo here](https://github.com/AErmie/Terraform-Real-World-Edition/tree/master/Networking/Deployments/Network-Deployment/Peering-Deploy)
```

### Crash Output

[Crash.log](https://gist.github.com/AErmie/e13791b71d579742c63f1f421b7e1d5e)

PS C:\Users\adine\Desktop\Code\Networking\Deployments\Network-Deployment\Peering-Deploy> terraform plan -var-file='Peering.tfvars' -out Peer.plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.azurerm_virtual_network.ProdVNET: Refreshing state...
data.azurerm_virtual_network.SharedServicesVNET: Refreshing state...
data.azurerm_virtual_network.NonProdVNET: Refreshing state...

------------------------------------------------------------------------
panic: not a collection type

goroutine 344 [running]:
github.com/zclconf/go-cty/cty.Type.ElementType(0x2d39220, 0xc0005ae208, 0xc000540768, 0x8)
        /home/circleci/project/project/vendor/github.com/zclconf/go-cty/cty/collection.go:25 +0xc1
github.com/hashicorp/terraform/terraform.createEmptyBlocks(0xc000d93b90, 0x2d39220, 0xc0005ae230, 0x2355700, 0xc001599530, 0x2d39220, 
0xc000006c28, 0x2355700, 0xc001089ef0)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:242 +0x209
github.com/hashicorp/terraform/terraform.dataObjectHasChanges(0xc000d93b90, 0x2d39220, 0xc0005ae230, 0x2355700, 0xc001599530, 0x2d39220, 0xc000006c28, 0x2355700, 0xc001089ef0, 0x0, ...)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:211 +0x1a5
github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc0015ac000, 0x2d7b6e0, 0xc0015c00d0, 0x1, 0x1, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval_read_data_plan.go:107 +0x123f
github.com/hashicorp/terraform/terraform.EvalRaw(0x2cd1460, 0xc0015ac000, 0x2d7b6e0, 0xc0015c00d0, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval.go:49 +0xce
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000106a60, 0x2d7b6e0, 0xc0015c00d0, 0x1, 0x1, 0x6, 0xc0001ac590)     
        /home/circleci/project/project/terraform/eval_sequence.go:20 +0x104
github.com/hashicorp/terraform/terraform.EvalRaw(0x2cd0ec0, 0xc000106a60, 0x2d7b6e0, 0xc0015c00d0, 0x230aac0, 0x40098a2, 0x226ae60, 0xc000998740)
        /home/circleci/project/project/terraform/eval.go:49 +0xce
github.com/hashicorp/terraform/terraform.Eval(0x2cd0ec0, 0xc000106a60, 0x2d7b6e0, 0xc0015c00d0, 0xc000106a60, 0x2cd0ec0, 0xc000106a60, 0x0)
        /home/circleci/project/project/terraform/eval.go:35 +0x54
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2699c60, 0xc0009980f0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:73 +0xc7e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0001ac3c0, 0x2699c60, 0xc0009980f0, 0xc0002225c0)
        /home/circleci/project/project/dag/walk.go:387 +0x35e
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x11de

### Expected Behavior
Terraform plan file should be created. 

### Actual Behavior
Terraform crash

### Steps to Reproduce
1. `terraform init`
2. `terraform plan -var-file='Peering.tfvars' -out Peer.plan`

### Additional Context

I successfully ran `terraform plan -var-file='Some.tfvars' -out Some.plan` for 2 other executions prior without issue.

**Comment by jbardin** [comment] 2020-09-01 16:14
Duplicate of #26011

**Closed by jbardin** 2020-09-01 16:14 UTC
Labels: bug, new
