### ISSUE TITLE
Redact sensitive input on prompt

### ISSUE THREAD

**Issue by dr4Ke** [hashicorp/terraform#28122] opened 2021-03-17 10:30 UTC
### Current Terraform Version

```
Terraform v0.14.8
```

### Use-cases
When declaring a sensitive input variable, its content is hidden in the plan and apply output and that's great.

However, I think it should be hidden too at the prompt.

### Attempted Solutions
There may be workarounds to not use the prompt, but it's about fixing the prompt.

### Proposal

The idea would be to replace input by `*` chars in the prompt for sensitive inputs.

### References
- #16114
- #26183

**Comment by crw** [comment] 2022-10-05 17:43
Marking as duplicate of #29609. Although that issue is later, the description has a bit more detail in terms of config files etc that make it easier to replicate the issue. Thanks for this!

**Closed by crw** 2022-10-05 17:43 UTC
Labels: enhancement, new
