### ISSUE TITLE
Terraform errors on aws_iam_server_certificate deletion

### ISSUE THREAD

**Issue by bensojona** [hashicorp/terraform#3746] opened 2015-11-04 01:36 UTC
When I try and delete an `aws_iam_server_certificate` resource that's being used by the `aws_elb` resource, I get the below error. This happens both when I do `terraform destroy`'s and when I modify the`aws_elb` or`aws_iam_server_certificate` and it needs to replace the resource.

See [.tf gist here](https://gist.github.com/bensojona/cb65d49e84a136e6b0d8).

Deleting the HTTPS listener that's using the SSL certificate seems to get be past the error, but obviously not a great solution.

![image](https://cloud.githubusercontent.com/assets/2430570/10927129/1b83e9a2-8252-11e5-8336-698ea5275133.png)

```
Terraform v0.6.6

Setting up remote state...
Downloading remote modules...
Refreshing Terraform state prior to plan...
aws_iam_server_certificate.nodejs: Destroying...
Error applying plan:

1 error(s) occurred:

* aws_iam_server_certificate.nodejs: [WARN] Error deleting server certificate: DeleteConflict: Certificate: ASCAINAR4OAMIOW77O5MO is currently in use by arn:aws:elasticloadbalancing:us-east-1:241656615859:loadbalancer/prod-demo-nodejs. Please remove it first before deleting it from IAM.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

and

```
Terraform v0.6.6

Setting up remote state...
Downloading remote modules...
Refreshing Terraform state prior to plan...
aws_iam_server_certificate.nodejs: Destroying...
Error applying plan:

1 error(s) occurred:

* aws_iam_server_certificate.nodejs: [WARN] Error deleting server certificate: DeleteConflict: Certificate: ASCAIHXITBLGNUC4T4H4C is currently in use by arn:aws:elasticloadbalancing:us-east-1:241656615859:loadbalancer/staging-demo-nodejs. Please remove it first before deleting it from IAM.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by farridav** [comment] 2015-11-04 11:52
I think this bug may be a duplicate of https://github.com/hashicorp/terraform/issues/3412, also worth a read is a similar issue but with apply  https://github.com/hashicorp/terraform/issues/3275

**Comment by phinze** [comment] 2015-11-04 18:30
Yep - dup of #3412, but these examples and descriptions are also helpful. :+1:

**Closed by phinze** 2015-11-04 18:30 UTC
Labels: bug, provider/aws
