### ISSUE TITLE
Error: Missing required attribute in 0.12

### ISSUE THREAD

**Issue by osielczakd** [hashicorp/terraform#19468] opened 2018-11-26 19:15 UTC
Hi,

I think there is an issue with handling computed variable values in 0.12.0-alpha2. I'm trying to create a simple module to manage AWS VPCs and hitting an issue. The error points to the closing brackets of the module resource (rather unhelpfully)

### Terraform Version

```
Terraform version: 0.12.0 alpha2
```

### Terraform Configuration Files

```hcl
#Simple VPC creation module

terraform {
  required_version = ">= 0.12.0"
}

# -------------------------- create VPC --------------------------
resource "aws_vpc" "this" {
  cidr_block           = format("%s/%s", var.vpc_cidr_base, var.vpc_cidr_mask)
  instance_tenancy     = var.vpc_instance_tenancy
  enable_dns_support   = var.vpc_enable_dns_support
  enable_dns_hostnames = var.vpc_enable_dns_hostnames
  enable_classiclink   = var.vpc_enable_classiclink
  tags                 = merge(var.global_tags, map("Name", var.vpc_name))
}

# ------------------------- DHCP options -------------------------
resource "aws_vpc_dhcp_options" "this" {
  domain_name          = var.dhcp_options_domain_name
  domain_name_servers  = var.dhcp_options_dns_servers
  ntp_servers          = var.dhcp_options_ntp_servers
  tags                 = merge(var.global_tags, map("Name", var.dhcp_options_name))
}

resource "aws_vpc_dhcp_options_association" "this" {
  vpc_id          = aws_vpc.this.id
  dhcp_options_id = aws_vpc_dhcp_options.this.id
}

Called from:
terraform {
  required_version = ">= 0.12.0"

  backend "consul" {
    address      = "consul.ops.internal:8500"
    path         = "tfstate/operations"
    access_token = "b10ea2ab-070e-fb6f-2622-XXXX"
    lock         = "false" 
  }
}

provider "aws" {
  region = var.aws_region
}

module "vpc" {
  source = "../modules/vpc"

  aws_region    = var.aws_region
  vpc_name      = var.vpc_name
  vpc_cidr_base = var.vpc_cidr_base
  vpc_cidr_mask = var.vpc_cidr_mask
  
  dhcp_options_name        = var.dhcp_options_name
  dhcp_options_domain_name = var.dhcp_options_domain_name
}
```

### Debug Output

```
2018/11/26 15:58:01 [INFO] Terraform version: 0.12.0 alpha2 
2018/11/26 15:58:01 [INFO] Go runtime version: go1.11.1
2018/11/26 15:58:01 [INFO] CLI args: []string{"/opt/terraform/terraform", "plan", "-var-file=operations.tfvars", "-refresh=true"}
2018/11/26 15:58:01 [DEBUG] Attempting to open CLI config file: /home/centos/.terraformrc
2018/11/26 15:58:01 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/11/26 15:58:01 [INFO] CLI command args: []string{"plan", "-var-file=operations.tfvars", "-refresh=true"}
2018/11/26 15:58:01 [INFO] command: backend initialized: *consul.Backend
2018/11/26 15:58:01 [DEBUG] checking for provider in "."
2018/11/26 15:58:01 [DEBUG] checking for provider in "/opt/terraform"
2018/11/26 15:58:01 [DEBUG] found provider "terraform-provider-aws_v1.40.0-6-gb23683732_x4"
2018/11/26 15:58:01 [DEBUG] found provider "terraform-provider-azurerm_v1.17.0-5-ga3b48ba3_x4"
2018/11/26 15:58:01 [DEBUG] found provider "terraform-provider-google_v1.19.1-4-gf3de5334_x4"
2018/11/26 15:58:01 [DEBUG] found provider "terraform-provider-local_v1.1.0-5-ga2df742_x4"
2018/11/26 15:58:01 [DEBUG] found provider "terraform-provider-null_v1.0.0-5-gf54ff98_x4"
2018/11/26 15:58:01 [DEBUG] found provider "terraform-provider-random_v2.0.0-5-g612dff2_x4"
2018/11/26 15:58:01 [DEBUG] found provider "terraform-provider-template_v1.0.0-5-g317c9c9_x4"
2018/11/26 15:58:01 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2018/11/26 15:58:01 [DEBUG] found valid plugin: "template", "1.0.0-5-g317c9c9", "/opt/terraform/terraform-provider-template_v1.0.0-5-g317c9c9_x4"
2018/11/26 15:58:01 [DEBUG] found valid plugin: "aws", "1.40.0-6-gb23683732", "/opt/terraform/terraform-provider-aws_v1.40.0-6-gb23683732_x4"
2018/11/26 15:58:01 [DEBUG] found valid plugin: "azurerm", "1.17.0-5-ga3b48ba3", "/opt/terraform/terraform-provider-azurerm_v1.17.0-5-ga3b48ba3_x4"
2018/11/26 15:58:01 [DEBUG] found valid plugin: "google", "1.19.1-4-gf3de5334", "/opt/terraform/terraform-provider-google_v1.19.1-4-gf3de5334_x4"
2018/11/26 15:58:01 [DEBUG] found valid plugin: "local", "1.1.0-5-ga2df742", "/opt/terraform/terraform-provider-local_v1.1.0-5-ga2df742_x4"
2018/11/26 15:58:01 [DEBUG] found valid plugin: "null", "1.0.0-5-gf54ff98", "/opt/terraform/terraform-provider-null_v1.0.0-5-gf54ff98_x4"
2018/11/26 15:58:01 [DEBUG] found valid plugin: "random", "2.0.0-5-g612dff2", "/opt/terraform/terraform-provider-random_v2.0.0-5-g612dff2_x4"
2018/11/26 15:58:01 [DEBUG] checking for provisioner in "."
2018/11/26 15:58:01 [DEBUG] checking for provisioner in "/opt/terraform"
2018/11/26 15:58:01 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2018/11/26 15:58:01 [INFO] command: backend *consul.Backend is not enhanced, wrapping in local
2018/11/26 15:58:01 [INFO] backend/local: starting Plan operation
2018-11-26T15:58:02.115Z [DEBUG] plugin: starting plugin: path=/opt/terraform/terraform-provider-aws_v1.40.0-6-gb23683732_x4 args=[/opt/terraform/terraform-provider-aws_v1.40.0-6-gb23683732_x4]
2018-11-26T15:58:02.116Z [DEBUG] plugin: plugin started: path=/opt/terraform/terraform-provider-aws_v1.40.0-6-gb23683732_x4 pid=15918
2018-11-26T15:58:02.116Z [DEBUG] plugin: waiting for RPC address: path=/opt/terraform/terraform-provider-aws_v1.40.0-6-gb23683732_x4
2018-11-26T15:58:02.128Z [DEBUG] plugin.terraform-provider-aws_v1.40.0-6-gb23683732_x4: plugin address: network=unix address=/tmp/plugin246848479 timestamp=2018-11-26T15:58:02.128Z
2018-11-26T15:58:02.128Z [DEBUG] plugin: using plugin: version=5
2018-11-26T15:58:02.422Z [WARN]  plugin: plugin failed to exit gracefully
2018-11-26T15:58:02.423Z [DEBUG] plugin: plugin process exited: path=/opt/terraform/terraform-provider-aws_v1.40.0-6-gb23683732_x4 pid=15918 error="signal: killed"

Error: Missing required attribute

  on /home/centos/new_start/infra-provisioning-ops/terraform/operations/main.tf line 26:
  26: }

The attribute "vpc_id" is required, but no definition was found.


Error: Missing required attribute

  on /home/centos/new_start/infra-provisioning-ops/terraform/operations/main.tf line 26:
  26: }

The attribute "dhcp_options_id" is required, but no definition was found.
```

### Expected Behavior
Plan gets created with relevant IDs computed

### Actual Behavior
the command ends with an error

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
Strangly enough, when I remove the offending lines from the module the plan runs but never creates a tfstate.

### References
n/a

**Comment by jbardin** [comment] 2018-12-10 20:05
Hi @osielczakd,

This appears to be fixed in master, but I did have to simplify the config slightly not having all the variable declarations. If this doesn't work for you, feel free to reply here and we can open this back up for further investigation.

**Closed by jbardin** 2018-12-10 20:05 UTC
Labels: bug, config

**Comment by osielczakd** [comment] 2018-12-14 14:19
Unfortunately still fails with the same error using latest build:

```
[centos@ip-10-22-12-60 operations]$ terraform plan -var-file=operations.tfvars -refresh=true

Error: Missing required argument

  on /home/centos/infra-provisioning-ops/terraform/operations/main.tf line 16, in module "vpc":
  16: module "vpc" {

The argument "dhcp_options_id" is required, but no definition was found.


Error: Missing required argument

  on /home/centos/infra-provisioning-ops/terraform/operations/main.tf line 16, in module "vpc":
  16: module "vpc" {

The argument "vpc_id" is required, but no definition was found.

[centos@ip-10-22-12-60 operations]$ terraform --version
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
+ provider.aws v1.40.0-6-gb23683732-dev
```
As for variables declaration, this should help:

`# Variables for the module:

variable "aws_region" {}

variable "vpc_name" {
  default = ""
}

variable "azs" {
  description = "comma separated string of availability zones in order of precedence"
  default = "eu-west-1a, eu-west-1b, eu-west-1c"
}

variable "vpc_cidr_base" {
	description = "The base of VPC in CIDR-notation"
	default = ""
}
variable "vpc_cidr_mask" {
	description = "The mask of VPC in CIDR-notation"
	default = ""
}

variable "vpc_instance_tenancy" {
  default = "default"
}

variable "vpc_enable_dns_support" {
  default = "true"
}

variable "vpc_enable_dns_hostnames" {
  default = "true"
}

variable "vpc_enable_classiclink" {
  default = "false"
}

variable "dhcp_options_name" {
  default = ""
}

variable "dhcp_options_domain_name" {
  default = ""
}

variable "dhcp_options_dns_servers" {
  type    = "list"
  default = ["10.0.0.1", "10.0.0.2", "8.8.8.8"]
}

variable "dhcp_options_ntp_servers" {
  type    = "list"
  default = ["10.0.0.1", "10.0.0.2"]
}

variable "global_tags" {
  description = "AWS tags that will be added to all resources managed herein"
  type = "map"
  default = {
    Poject = "ops"
  }
}
`

**Comment by jbardin** [comment] 2018-12-14 17:33
Hi @osielczakd,

Thanks for the follow up, but I'm still not able to reproduce the issue.
The error indicates that there is a variable called `vpc_id` in the module without a default, which is why it's a required argument in the module block. Can you find where that variable is declared in your configuration?

**Comment by osielczakd** [comment] 2018-12-17 09:45
Yep, you're right @jbardin, adding an empty default to the variable definition fixes that issue. A bit counter-intuitive but I can live with that. Many thanks again.

**Comment by brunodomenici** [comment] 2019-09-13 12:19
Just a follow-up. I started to have this issue when I "divided" my Terraform in modules. If I don't put a default = ""in my vars I got the error.
