### ISSUE TITLE
Terraform plan -target one of a "chain" of resources with count > 1 

### ISSUE THREAD

**Issue by dcosson** [hashicorp/terraform#13544] opened 2017-04-11 17:15 UTC
In some situations I have multiple resources with a count > 1 related to each other in kind of a chain, where the dependency is only the same count.index for each resource. For example a group of `aws_instance`s where each has an `aws_eip`:

```
resource "aws_instance" "instances" {
  # ... parameters
  count = 2
}

resource "aws_eip" "instance_ips" {
  instance = "${element(aws_instance.instances.*.id, count.index)}"
  count = 2 
}
```

If I run `terraform plan -target aws_eip.instance_ips[1]`, it targets both of the aws_instances as dependencies, instead of just aws_instance[1] which is the only actual dependency. It would be cool if terraform could resolve this to only target the one relevant aws_instance.

**Comment by apparentlymart** [comment] 2017-04-11 17:38
Hi @dcosson! Sorry this didn't work as expected.

This looks like the same root cause -- though different effect -- as #3449: Terraform doesn't understand that `element` only looks at the given index, so is forced to conservatively assume that the result depends on the entire list.

The new index syntax `[ ... ]` introduced a while ago should in theory let Terraform understand this, but it doesn't yet. That is what #3449 is effectively about, so I'm going to close this to consolidate the discussion over there. Thanks for sharing this different angle on the problem, though!

**Closed by apparentlymart** 2017-04-11 17:38 UTC
Labels: bug, core

**Comment by dcosson** [comment] 2017-04-11 19:06
Cool, thanks for the links and explanation!
