### ISSUE TITLE
File function  not working while reading local private key

### ISSUE THREAD

**Issue by malikperang** [hashicorp/terraform#24969] opened 2020-05-15 18:26 UTC
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "ap-southeast-1"
}

# IAM Role
resource "aws_iam_role" "opsworks-role" {
  name               = "farizizwancom_opsworks_role"
  assume_role_policy = <<EOF
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "opsworks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

# # IAM Policy
resource "aws_iam_policy" "iam-policy" {
  name        = "OpsWorksFullAccess"
  description = "A Test Policy"
  policy      = file("policies/OpsWorksFull.json")
}

resource "aws_iam_policy_attachment" "opsworks-policy" {
  name       = "FarizOpsWorksFullAccess"
  roles      = [aws_iam_role.opsworks-role.name]
  policy_arn = aws_iam_policy.iam-policy.arn
}

# IAM Instance Profile
resource "aws_iam_instance_profile" "opsworks" {
  role = aws_iam_role.opsworks-role.name
}


resource "aws_opsworks_stack" "farizizwan" {
  name                          = "farizizwan.com"
  region                        = "ap-southeast-1"
  service_role_arn              = aws_iam_role.opsworks-role.arn
  default_instance_profile_arn  = aws_iam_instance_profile.opsworks.arn
  vpc_id                        = "vpc-1ea6bb79"
  default_os                    = "Ubuntu 18.04 LTS"
  default_availability_zone     = "ap-southeast-1a"
  default_subnet_id             = "subnet-0f8d7c47"
  default_ssh_key_name          = "farizizwan.com"
  use_custom_cookbooks          = true
  configuration_manager_version = "12"
  custom_cookbooks_source {
    type    = "git"
    url     = "git@github.com:malikperang/farizizwancom-cookbook.git"
    ssh_key = file("id_rsa")
  }


  tags = {
    Name = "farizizwan.com"
  }
}

resource "aws_opsworks_custom_layer" "farizizwancom" {
  name       = "farizizwancom"
  short_name = "farizizwancom"
  stack_id   = aws_opsworks_stack.farizizwan.id
  custom_setup_recipes = [
    "farizizwancom::default",
    "farizizwancom::setup_october_cms"
  ]
}

output "layer_id" {
  value = aws_opsworks_custom_layer.farizizwancom.id
}

output "layer_arn" {
  value = aws_opsworks_custom_layer.farizizwancom.arn
}

resource "aws_opsworks_instance" "farizizwancom" {
  stack_id          = aws_opsworks_stack.farizizwan.id
  instance_type     = "t3a.nano"
  os                = "Ubuntu 18.04 LTS"
  state             = "running"
  availability_zone = "ap-southeast-1a"
  ebs_optimized     = true
  subnet_id         = "subnet-0f8d7c47"
  hostname          = "farizizwan"
  ssh_key_name      = "farizizwan.com"

  layer_ids = [
    aws_opsworks_custom_layer.farizizwancom.id
  ]

  root_block_device {
    delete_on_termination = false
  }

  ebs_block_device {
    device_name           = "/dev/sda1"
    delete_on_termination = false
  }


}

output "opsworks_id" {
  value = aws_opsworks_stack.farizizwan.id
}


```

### Debug Output

Here the gist https://gist.github.com/malikperang/94b12b63c528f63e70a699eca056881f

### Expected Behavior

Valid openssh key should be accepted for `custom_cookbooks_source` on `aws_opsworks_stack` resource
### Actual Behavior

Error: ValidationException: Custom Cookbooks Source's Ssh Key: is not a private SSH key

### Steps to Reproduce

I did run all of this
`$terraform init
$terraform plan
$terraform apply`

also I try to change the way to call the file also from `file("id_rsa")` to [this workaround](https://www.terraform.io/docs/providers/local/d/file.html)  still no success. :(

### Additional Context

For verification, I did check the validity of the private key file 
`ssh-keygen -y -e -f id_rsa` and yes it's still valid which it return the output as expected.

**Comment by danieldreier** [comment] 2020-05-18 22:06
Hi @malikperang! Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. If you take a look at the log, it shows that this error is coming from the AWS provider, which seems to be returning a message from the `aws-sdk-go` package. It looks to me like the SSH key you're giving it isn't being recognized by `aws-sdk-go` as a real SSH key.

```
2020-05-16T02:20:48.770+0800 [DEBUG] plugin.terraform-provider-aws_v2.61.0_x4: 2020/05/16 02:20:48 [DEBUG] [aws-sdk-go] {"__type":"ValidationException","message":"Custom Cookbooks Source's Ssh Key: is not a private SSH key"}
2020-05-16T02:20:48.770+0800 [DEBUG] plugin.terraform-provider-aws_v2.61.0_x4: 2020/05/16 02:20:48 [DEBUG] [aws-sdk-go] DEBUG: Validate Response opsworks/UpdateStack failed, attempt 0/25, error ValidationException: Custom Cookbooks Source's Ssh Key: is not a private SSH key
2020/05/16 02:20:48 [DEBUG] aws_opsworks_stack.farizizwan: apply errored, but we're indicating that via the Error pointer rather than returning it: ValidationException: Custom Cookbooks Source's Ssh Key: is not a private SSH key
```
I am wondering if this is related to the same root cause as https://github.com/hashicorp/terraform/issues/24970 where ssh-keygen behavior changed. From that:
> If necessary, it is possible to write old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments when generating or updating a key.

That said, this GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. This seems to be an issue outside the core codebase, and I don't think there's anything we can do about it here. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. 

Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Closed** 2020-05-18 22:20 UTC
Labels: provider/aws
