### ISSUE TITLE
terraform apply hangs - TF 0.15beta2

### ISSUE THREAD

**Issue by surfd4wg** [hashicorp/terraform#28331] opened 2021-04-10 00:58 UTC
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
Terraform v0.15.0-beta2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.36.0

```

**Comment by jbardin** [comment] 2021-04-12 14:34
Hi @surfd4wg,

There doesn't seem to be any information here. Can you add the steps you used to reproduce this?

Thanks!

**Comment by jbardin** [comment] 2021-04-13 21:08
Hi @surfd4wg,

I'm going to close this since there is no information provided here to work with.
If you have a reproduction case, feel free to create a new issue. If you have questions about using terraform, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-04-13 21:08 UTC
Labels: bug, new, v0.15, waiting for reproduction, waiting-response
