### ISSUE TITLE
remote config pushes back existing state

### ISSUE THREAD

**Issue by aventurella** [hashicorp/terraform#6311] opened 2016-04-22 22:24 UTC
This was completely unexpected for me. I am managing 2 environments with terraform, a staging and a prod.  Both are setup though Atlas. When I switch between remote configs it looks like it pulls down the state and merges it into the `.terraform/terraform.tfstate` file and pushes it back.  I was definitely not expecting it to push it back up. Also it looks like it just swaps out the remote config, nothing more.

Maybe I am doing something wrong. I would totally prefer a `remote config` just blows away the .terraform/ directory and pulls though vs a pull and a push which just left me in a bad way. Thankfully Atlas does rollbacks.

**Comment by aventurella** [comment] 2016-04-22 22:28
Bonus!  Rollback from the Atlas website doesn't work... the url is not found when attempted.

**Comment by apparentlymart** [comment] 2016-04-23 01:14
Hi @aventurella,

Sorry you've hit this surprise in Terraform. I think this is the same issue that motivated me to propose #4389 and the associated PR #4618 which I haven't yet finished, due to my attention being diverted elsewhere. :worried: 

Unfortunately I don't know much about Atlas so I can't really offer anything except empathy... the Atlas support team may be able to help you recover your old state, though, since I believe Atlas is supposed to preserve old state versions.

**Comment by aventurella** [comment] 2016-04-23 15:22
Since atlas appears to be broken (as of yesterday anyway 2016-04-22 ) you can still browse the previous states thankfully. So I just ticked the serial values and pushed it back up.

The larger, more fun issue was that I did have to manually go back through and rebuild my tfstate from the other env. Unexpected pain on a Friday, you bet! The silver-lining was I got to better understand what the tfstate file was doing and how it wants it's information, so it wasn't a wash, learning things +1!

Regardless though, I still thinks its REALLY unexpected that a `remote config` would pull AND push.. just a pull I'd totally get, and that pull should just do something like like: 

```
Hey I noticed you have an existing terraform.tfstate file in .terraform/, do you want me to overwrite it?
```

unless you do something like:

```
terraform remote config ... -no-prompt
- no-prompt?
```

**Comment by apparentlymart** [comment] 2016-04-23 16:02
The model Terraform is going for here is that when you run `terraform remote config` with a state already present (local or remote), you're "moving" the state to a new location.

It sounds like you're trying to do the same use-cases as I am, where instead you have the same config deployed multiple times to create multiple "instances" of the same config, each with its own state. Deleting the `.terraform/terraform.tfstate` file manually was exactly the workaround I did too.

My proposal #4389 was intended as a short-term thing where at least Terraform explains to you that you're trying to do something it doesn't support, rather than silently destroying your state as happened in your case. Over in #1964 we were collecting some use-cases for a different potential design where the remote state configuration lives within the main configuration files and is controlled by variables, which IMO is the better long-term path.

With all of this said... thanks again for sharing your problem and workarounds here, and again I'm sorry that you've run into these problems. Multiple "environments" is not a use-case Terraform supports well at this time, so workarounds like these are needed. I'm going to close this issue now not because it's not a valid issue -- it most certainly is! -- but because I'd like to keep the ongoing discussion around these issues within the existing issues #1964 and #4389. However, I'm happy to re-open it if you think there's something here that isn't covered by one of those.

**Closed by apparentlymart** 2016-04-23 16:02 UTC
