### ISSUE TITLE
VPC Peering connection Panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by erutherford** [hashicorp/terraform#8392] opened 2016-08-22 17:45 UTC
### Terraform Version
`0.7.1`, I've confirmed that this crash doesn't occur in `0.7.0`

### Affected Resource(s)
- aws_vpc_peering_connection

### Terraform Configuration Files
Here's the module I'm using to setup our networking resources
https://www.dropbox.com/s/if8bwqdm4g03tz0/aws_vpc_complete.tar.gz?dl=0

#### complete crash.log file encrypted with the hashicorp pub key
https://www.dropbox.com/s/9pi8gz4r0yecfbz/terraform_crash_v0.7.1.log.gpg?dl=0
#### gist of the panic
https://gist.github.com/erutherford/2029aef0412ff526d7b7885b59c5bda2

### Expected Behavior
In versions before `0.7.1` this module was working without an issue.

I reverted back to `0.7.0` and I'm able to run `terraform plan` and `terraform apply` without an issue.  

I know there were changes made for peering options, but I'm not sure if that's related (and I don't believe I should have needed to change my config since it's defined as optional) and that the very least it should provide an error for that, not crash.

It should create the resources or leave them alone if nothing as changed.

### Actual Behavior
It's crashing with a panic

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by stack72** [comment] 2016-08-22 17:55
Hi @erutherford 

Thanks for reporting the issue here - we apologise this has happened. Hopefully it hasn't caused any issues for you! We are actively working on getting this fixed #8338 

We hope to have that ready really soon! I am going to close this as a duplicate of #8334 

Paul

**Closed** 2016-08-22 17:55 UTC
Labels: bug, crash, provider/aws

**Comment by erutherford** [comment] 2016-08-22 18:06
@stack72 thanks for the update, sorry I missed the existing issue.

**Comment by stack72** [comment] 2016-08-22 19:16
Nothing to apologise for at all :) just easier to track in 1 place
