### ISSUE TITLE
terraform destroy -target  crash in Terraform v0.13.0-beta2 

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/terraform#25497] opened 2020-07-07 13:39 UTC
### Terraform Version
```
Terraform v0.13.0-beta2
```

### Terraform Configuration Files

```terraform

Inside a main.tf configuration in a module block we created an aws_instance:

provider "aws" {
  alias                   = "milan"
  ...
}

module "bastionaws1" {
  source             = "../../../modules/aws/ec2/ec2_std"

  providers = {
    aws = aws.milan
  }

  tags = {
    Environment = local.env
   }
  ...
}

```

### Debug Output

If you need more Debug Output and tell me where I can find HashiCorp public key, I'll encrypt and I'll send you.

### Crash Output

If you need more Debug Output and tell me where I can find HashiCorp public key, I'll encrypt and I'll send you.

### Expected Behavior
```
terraform destroy -target=module.bastionaws1.aws_instance.instance
```
should destroy resource "module.bastionaws1.aws_instance.instance"

### Actual Behavior

```
terraform destroy -target=module.bastionaws1.aws_instance.instance
```
returns

```
panic: no expansion has been registered for module.eip

goroutine 193 [running]:
github.com/hashicorp/terraform/instances.(*expanderModule).moduleInstances(0xc000b965e0, 0xc0001fff80, 0x1, 0x1, 0xc0011d5b50, 0x0, 0x4, 0x4f3078, 0x0, 0xa)
        /home/circleci/project/project/instances/expander.go:267 +0xb72
github.com/hashicorp/terraform/instances.(*Expander).ExpandModule(0xc000b96600, 0xc0001fff80, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/circleci/project/project/instances/expander.go:116 +0x108
github.com/hashicorp/terraform/terraform.(*nodeExpandModuleVariable).DynamicExpand(0xc0006e5bc0, 0x2d16820, 0xc000a65860, 0x1, 0x1, 0x1)
        /home/circleci/project/project/terraform/node_module_variable.go:42 +0x94
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2518480, 0xc0006e5bc0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:84 +0x4d8
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0004795c0, 0x2518480, 0xc0006e5bc0, 0xc00073fac0)
        /home/circleci/project/project/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x11d7
```

### Additional Context

Using https://github.com/tfutils/tfenv

terraform remote state DynamoDB table lock not released (crashed in between)

**Comment by jbardin** [comment] 2020-07-07 14:39
Hi @Roxyrob 

This appears to be a duplicate of #25114, which is fixed in the latest beta. 

Thanks!

**Closed by jbardin** 2020-07-07 14:39 UTC

**Comment by Roxyrob** [comment] 2020-07-07 15:12
Hi @jbardin ,
you're right... I have only seen now that 0.13.0beta3 is available... beta3 works !

Thanks!
