### ISSUE TITLE
Got a bug report during terraform apply.

### ISSUE THREAD

**Issue by arpit9508** [hashicorp/terraform#21105] opened 2019-04-25 10:50 UTC
Hi, got this message `diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.`. So reporting it here. 

```
Terraform Version: 0.11.13
    Resource ID: aws_cloudfront_distribution.static_website
    Mismatch reason: attribute mismatch: default_cache_behavior.134478860.allowed_methods.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"ordered_cache_behavior.0.lambda_function_association.3038207189.include_body":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.~2798435080.event_type":*terraform.ResourceAttrDiff{Old:"", New:"origin-response", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.cached_methods.#":*terraform.ResourceAttrDiff{Old:"0", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.compress":*terraform.ResourceAttrDiff{Old:"true", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.cached_methods.0":*terraform.ResourceAttrDiff{Old:"", New:"HEAD", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.cached_methods.1":*terraform.ResourceAttrDiff{Old:"", New:"GET", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.lambda_function_association.~2441362934.include_body":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.202465439.cookies.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.~2441362934.event_type":*terraform.ResourceAttrDiff{Old:"", New:"origin-request", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.2737741547.event_type":*terraform.ResourceAttrDiff{Old:"origin-request", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.3038207189.lambda_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-east-1:714049641531:function:coitool-proxy-response-694b221c69c26036:1", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.allowed_methods.1":*terraform.ResourceAttrDiff{Old:"", New:"GET", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.lambda_function_association.#":*terraform.ResourceAttrDiff{Old:"0", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.compress":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.cached_methods.#":*terraform.ResourceAttrDiff{Old:"2", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.lambda_function_association.~2798435080.include_body":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.allowed_methods.0":*terraform.ResourceAttrDiff{Old:"HEAD", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.~2441362934.lambda_arn":*terraform.ResourceAttrDiff{Old:"", New:"${module.proxy.request_lambda_arn}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.lambda_function_association.2737741547.include_body":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.allowed_methods.#":*terraform.ResourceAttrDiff{Old:"2", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.viewer_protocol_policy":*terraform.ResourceAttrDiff{Old:"redirect-to-https", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.allowed_methods.#":*terraform.ResourceAttrDiff{Old:"0", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.~2798435080.event_type":*terraform.ResourceAttrDiff{Old:"", New:"origin-response", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.~2798435080.include_body":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.3038207189.lambda_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-east-1:714049641531:function:coitool-proxy-response-694b221c69c26036:1", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.2737741547.event_type":*terraform.ResourceAttrDiff{Old:"origin-request", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.3038207189.event_type":*terraform.ResourceAttrDiff{Old:"origin-response", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.3038207189.include_body":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.lambda_function_association.2737741547.lambda_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-east-1:714049641531:function:coitool-proxy-request-0ad8a4b609d41fa4:1", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.default_ttl":*terraform.ResourceAttrDiff{Old:"31536000", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.lambda_function_association.~2441362934.event_type":*terraform.ResourceAttrDiff{Old:"", New:"origin-request", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.202465439.query_string":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.viewer_protocol_policy":*terraform.ResourceAttrDiff{Old:"", New:"redirect-to-https", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.~2441362934.include_body":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.field_level_encryption_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.2737741547.include_body":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.min_ttl":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.default_ttl":*terraform.ResourceAttrDiff{Old:"", New:"31536000", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.202465439.cookies.2625240281.forward":*terraform.ResourceAttrDiff{Old:"none", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.202465439.headers.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.202465439.headers.0":*terraform.ResourceAttrDiff{Old:"Host", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.lambda_function_association.~2441362934.lambda_arn":*terraform.ResourceAttrDiff{Old:"", New:"${module.proxy.request_lambda_arn}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.202465439.headers.0":*terraform.ResourceAttrDiff{Old:"", New:"Host", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.~2798435080.lambda_arn":*terraform.ResourceAttrDiff{Old:"", New:"${module.proxy.response_lambda_arn}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.202465439.cookies.2625240281.whitelisted_names.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.lambda_function_association.3038207189.include_body":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.202465439.query_string":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.202465439.cookies.2625240281.forward":*terraform.ResourceAttrDiff{Old:"", New:"none", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.max_ttl":*terraform.ResourceAttrDiff{Old:"31536000", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.3038207189.event_type":*terraform.ResourceAttrDiff{Old:"origin-response", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.min_ttl":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.202465439.cookies.#":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.smooth_streaming":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.max_ttl":*terraform.ResourceAttrDiff{Old:"", New:"31536000", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.forwarded_values.202465439.query_string_cache_keys.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.cached_methods.0":*terraform.ResourceAttrDiff{Old:"HEAD", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.202465439.headers.#":*terraform.ResourceAttrDiff{Old:"0", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.target_origin_id":*terraform.ResourceAttrDiff{Old:"", New:"S3-coitool-static-website-714049641531-36d30e069be3e18b", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.lambda_function_association.#":*terraform.ResourceAttrDiff{Old:"2", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.~2798435080.lambda_arn":*terraform.ResourceAttrDiff{Old:"", New:"${module.proxy.response_lambda_arn}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.~2441362934.include_body":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.smooth_streaming":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.lambda_function_association.~2798435080.lambda_arn":*terraform.ResourceAttrDiff{Old:"", New:"${module.proxy.response_lambda_arn}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.target_origin_id":*terraform.ResourceAttrDiff{Old:"S3-coitool-static-website-714049641531-36d30e069be3e18b", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.field_level_encryption_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.202465439.cookies.2625240281.whitelisted_names.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.~2798435080.include_body":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.lambda_function_association.3038207189.event_type":*terraform.ResourceAttrDiff{Old:"origin-response", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.lambda_function_association.3038207189.lambda_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-east-1:714049641531:function:coitool-proxy-response-694b221c69c26036:1", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.~2441362934.event_type":*terraform.ResourceAttrDiff{Old:"", New:"origin-request", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.lambda_function_association.2737741547.event_type":*terraform.ResourceAttrDiff{Old:"origin-request", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.0.lambda_function_association.2737741547.lambda_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-east-1:714049641531:function:coitool-proxy-request-0ad8a4b609d41fa4:1", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.trusted_signers.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.lambda_function_association.~2798435080.event_type":*terraform.ResourceAttrDiff{Old:"", New:"origin-response", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.cached_methods.1":*terraform.ResourceAttrDiff{Old:"GET", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.~2441362934.lambda_arn":*terraform.ResourceAttrDiff{Old:"", New:"${module.proxy.request_lambda_arn}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.2737741547.lambda_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-east-1:714049641531:function:coitool-proxy-request-0ad8a4b609d41fa4:1", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.allowed_methods.1":*terraform.ResourceAttrDiff{Old:"GET", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.forwarded_values.202465439.query_string_cache_keys.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.~615369033.allowed_methods.0":*terraform.ResourceAttrDiff{Old:"", New:"HEAD", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ordered_cache_behavior.1.lambda_function_association.2737741547.include_body":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cache_behavior.134478860.trusted_signers.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

**Comment by apparentlymart** [comment] 2019-04-25 23:35
Hi @arpit9508! Sorry for this failure.

Could you also share the configuration block for your `aws_cloudfront_distribution.static_website` resource?

The usual cause of this message is a bug in some other resource type that you have referenced inside the configuration of this one, where that other resource type produced an inaccurate plan that was inconsistent with what happened during apply. Seeing the configuration will allow us to determine if that is true in this case and, if so, which provider repository this bug report should be routed to.

Thanks!

**Comment by arpit9508** [comment] 2019-04-26 09:00
Here is the configuration block
```
resource "aws_cloudfront_distribution" "static_website" {
  aliases             = ["${var.fqdn}", "*.${var.fqdn}"]
  comment             = "my static website"
  default_root_object = "index.html"
  enabled             = true
  price_class         = "${var.cloudfront_price_class}"
  web_acl_id          = "${var.cloudfront_web_acl_id}"

  origin {
    domain_name = "${aws_s3_bucket.static_website.bucket_regional_domain_name}"
    origin_id   = "${local.origin_id}"

    s3_origin_config = {
      origin_access_identity = "${aws_cloudfront_origin_access_identity.static_website.cloudfront_access_identity_path}"
    }
  }

  logging_config {
    include_cookies = false
    bucket          = "${aws_s3_bucket.access_logs.bucket_domain_name}"
  }

  default_cache_behavior {
    allowed_methods        = ["HEAD", "GET"]
    cached_methods         = ["HEAD", "GET"]
    compress               = true
    target_origin_id       = "${local.origin_id}"
    viewer_protocol_policy = "redirect-to-https"
    default_ttl            = 31536000

    lambda_function_association {
      event_type   = "origin-request"
      lambda_arn   = "${module.proxy.request_lambda_arn}"
      include_body = false
    }

    lambda_function_association {
      event_type   = "origin-response"
      lambda_arn   = "${module.proxy.response_lambda_arn}"
      include_body = false
    }

    forwarded_values = {
      cookies = {
        forward = "none"
      }

      headers      = ["Host"]
      query_string = false
    }
  }

  ordered_cache_behavior {
    path_pattern           = "/_next/static/*"
    allowed_methods        = ["HEAD", "GET"]
    cached_methods         = ["HEAD", "GET"]
    compress               = true
    target_origin_id       = "${local.origin_id}"
    viewer_protocol_policy = "https-only"
    default_ttl            = 31536000

    lambda_function_association {
      event_type   = "origin-request"
      lambda_arn   = "${module.proxy.request_lambda_arn}"
      include_body = false
    }

    lambda_function_association {
      event_type   = "origin-response"
      lambda_arn   = "${module.proxy.response_lambda_arn}"
      include_body = false
    }

    forwarded_values = {
      cookies {
        forward = "none"
      }

      headers      = ["Host"]
      query_string = false
    }
  }

  ordered_cache_behavior {
    path_pattern           = "/static/*"
    allowed_methods        = ["HEAD", "GET"]
    cached_methods         = ["HEAD", "GET"]
    compress               = true
    target_origin_id       = "${local.origin_id}"
    viewer_protocol_policy = "https-only"
    default_ttl            = 31536000

    lambda_function_association {
      event_type   = "origin-request"
      lambda_arn   = "${module.proxy.request_lambda_arn}"
      include_body = false
    }

    lambda_function_association {
      event_type   = "origin-response"
      lambda_arn   = "${module.proxy.response_lambda_arn}"
      include_body = false
    }

    forwarded_values = {
      cookies {
        forward = "none"
      }

      headers      = ["Host"]
      query_string = false
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags = {
    Name          = "my-static-website"
  }

  viewer_certificate {
    acm_certificate_arn      = "${aws_acm_certificate.cert.arn}"
    minimum_protocol_version = "${var.tls_protocol_version}"
    ssl_support_method       = "sni-only"
  }
}
```

**Comment by apparentlymart** [comment] 2019-04-26 17:30
Thanks for the additional context, @arpit9508!

From looking at the before/after diffs in the error message I think the trigger here was that `module.proxy.request_lambda_arn` was marked for a change in the plan whose new value wasn't yet known, but once the underlying resource was _actually_ applied it turned out to still have the same value from before: `arn:aws:lambda:us-east-1:714049641531:function:coitool-proxy-request-0ad8a4b609d41fa4:1`.

Normally Terraform will ignore an outcome like this, because an unknown value during plan becoming the same value as before during apply is an expected behavior. But it fails in this case because the `aws_cloudfront_distribution` resource type schema represents all of these nested `default_cache_behavior`, `ordered_cache_behavior`, `lambda_function_association` etc blocks as set-of-objects values internally, and so the planned change to just the `lambda_arn` must (due to the definition of a set) be understood as a change to the entire contents of the `default_cache_behavior` or `ordered_cache_behavior` block it is nested inside.

The diff therefore contains lots of no-op changes for arguments like `allowed_methods`, because from Terraform's standpoint that entire block is being removed and another entire block is being added in its place. Once the values are completed during apply and the `lambda_arn` change is now absent, the entire change to `default_cache_behavior` is no longer necessary, and so all of those apparent changes to arguments like `allowed_methods` are no longer present, and Terraform treats that as an inconsistency because _those_ were not marked as "unknown" during planning.

This specific error no longer exists in the master branch for Terraform v0.12, and [its replacement](https://godoc.org/github.com/hashicorp/terraform/plans/objchange#AssertObjectCompatible) now has set-specific accommodations to allow for situations like these; I expect this problem will no longer occur once v0.12.0 is in use. If there _are_ still bugs in this area then the behavior will end up different (due to the entirely-new diff consistency checker), so we'll need to investigate again in a separate issue if any such issues arise. With that said, I'm going to close this out for now because the codepath that caused this problem is no longer present in the master branch, and any remaining problems related to this will have different symptoms and behaviors in v0.12.

In the meantime: usually errors of this type will go away if you re-run Terraform, because on the subsequent run the change to `module.proxy.request_lambda_arn` has already completed successfully and so an accurate empty plan can be created. That is not ideal by any means, but at least this error should not be a blocker, and Terraform will converge on a good final state on a subsequent run.

Thanks again for reporting this!

**Closed by apparentlymart** 2019-04-26 17:30 UTC
Labels: bug, core
