### ISSUE TITLE
Cannot Render Template From Created Resource

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/terraform#26777] opened 2020-11-02 07:09 UTC
### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.13.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

### Terraform Configuration Files

At the top level I have a `main.tf` that uses two modules, one to create vpc and one to export configuration file.  Applicable snippets with full source in gists below:

```terraform
module "vpc" {
  source           = "../modules/eks-vpc"
  name             = var.name
  region           = var.region
  eks_cluster_name = var.eks_cluster_name
}

module "config" {
  source          = "../modules/eksctl-config"
  name            = var.eks_cluster_name
  region          = var.region
  vpc_id          = module.vpc.vpc_id
  instance_type   = "m5.2xlarge"
  public_key_name = "joaquin"
  filename        = "${path.module}/../../eksctl/cluster_config.yaml"
}
```

The eksctl-config module has:

```terraform
data "aws_subnet_ids" "private_subnet_ids" {
  vpc_id = var.vpc_id

  filter {
    name   = "tag:kubernetes.io/cluster/${var.name}"
    values = ["shared"]
  }

  filter {
    name   = "tag:kubernetes.io/role/internal-elb"
    values = [1]
  }
}

data "aws_subnet_ids" "public_subnet_ids" {
  vpc_id = var.vpc_id

  filter {
    name   = "tag:kubernetes.io/cluster/${var.name}"
    values = ["shared"]
  }

  filter {
    name   = "tag:kubernetes.io/role/elb"
    values = [1]
  }
}

data "aws_subnet" "private_subnets" {
  for_each = data.aws_subnet_ids.private_subnet_ids.ids
  id       = each.value
}

data "aws_subnet" "public_subnets" {
  for_each = data.aws_subnet_ids.public_subnet_ids.ids
  id       = each.value
}
```

If needed, the eks-vpc module:
* eks-vpc-config.tf (calls both modules) - https://gist.github.com/darkn3rd/ae76631984c139e5553fbe3cf32fa2a0
* eksctl-config.tf - https://gist.github.com/darkn3rd/b25e61260cc8d0038302270ec8d88182
* eks-vpc.tf https://gist.github.com/darkn3rd/e9a3492540302219bac61252829600d0

### Crash Output

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.vpc.data.aws_availability_zones.available: Refreshing state...

------------------------------------------------------------------------

Error: Invalid for_each argument

  on ../modules/eksctl-config/data.tf line 30, in data "aws_subnet" "private_subnets":
  30:   for_each = data.aws_subnet_ids.private_subnet_ids.ids

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.


Error: Invalid for_each argument

  on ../modules/eksctl-config/data.tf line 35, in data "aws_subnet" "public_subnets":
  35:   for_each = data.aws_subnet_ids.public_subnet_ids.ids

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

### Expected Behavior

I expected that since I create a state, I should be able to use that state to create another resource.  I shouldn't have to run two commands with to provision when there should be a full DAG of the resources created and used.  I wanted to have a modular module (D-R-Y) that can use a supplied `vpc_id`, rather than smashing two concerns into a single module (vpc concern, config concern)

This is something I think I can do with other provisioners, such as Ansible, where you can provision resources, and use those resources provisioned to provision other resources, despite them being packaged into their equivalent of a module called _roles_.

### Actual Behavior

The actual behavior is that I cannot use the output of the resource I created to create another resource if they are packaged up as a module.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan` or `terraform apply`

**Comment by jbardin** [comment] 2020-11-02 14:15
Hi @darkn3rd 

Thanks for filing the issue, but this is the expected behavior for the given configuration.
Terraform must know all `count` and `for_each` values in order to create a complete plan. Since the data source are not known at that time, they cannot be used for `count` or `for_each` values. Some possibilities are breaking up the config into multiple distinct configurations, or using `-target` to bootstrap the necessary resources for the config.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by jbardin** 2020-11-02 14:15 UTC
Labels: bug, new
