### ISSUE TITLE
Terraform wants to destroy resources that have not been removed from configuration and prevent_destroy is true for resources

### ISSUE THREAD

**Issue by michaelseto** [hashicorp/terraform#19270] opened 2018-11-02 19:18 UTC
Terraform v0.11.10
+ provider.azurerm v1.17.0

### Expected Behavior
terraform plan - no changes

### Actual Behavior
terraform stating 2 resources to destroy, even when prevent_destroy is true - and resources are still present in the state file

### Steps to Reproduce
1. Open VS Code
2. az login and az account set
3. terraform plan

I notice there are two resources that terraform says that will be destroyed. However, these resources are still present in the tf files (with prevent_destroy to true, even) and the state file.

**Comment by apparentlymart** [comment] 2018-11-03 00:03
Hi @michaelseto! Sorry for this unexpected behavior.

Unfortunately we can't start to explain what's going on here without a little more information. If you can share an example configuration that demonstrates the problem and the log output from planning against that as requested in [the bug report issue template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md) then hopefully we can figure out why Terraform behaved incorrectly.

**Comment by markush81** [comment] 2018-11-29 15:10
Terraform v0.11.10
+ provider.azurerm v1.19.0


I think i have a related issue, my workflow is following:

There is an existing subnet, which i change with a totally different plan:

```
resource "azurerm_subnet" "subnet" {
  name                 = "${data.azurerm_subnet.subnet.name}"
  resource_group_name  = "${data.azurerm_resource_group.resourcegroup.name}"
  virtual_network_name = "${data.azurerm_virtual_network.network.name}"
  address_prefix       = "${data.azurerm_subnet.subnet.address_prefix}"
  service_endpoints    = ["Microsoft.Sql"]
  "lifecycle" {
    "prevent_destroy" = true
  }
}
```

(the plan includes a lot of other stuff, e.g. an `azurerm_postgresql_server`)

So now executing

```
terraform plan
terraform apply
```

does create everything as intended.

Now i try following:

```
terraform plan -destroy
```

### Actual

```
Error: Error running plan: 1 error(s) occurred:

* module.postgres.azurerm_subnet.subnet: azurerm_subnet.subnet: the plan would destroy this resource, but it currently has lifecycle.prevent_destroy set to true. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or adjust the scope of the plan using the -target flag.
```

### Expected

Destroys everything e.g. `azurerm_postgresql_server`, but should not destroy `azurerm_subnet `.

**Comment by apparentlymart** [comment] 2018-11-29 15:55
Hi @markush81,

What you are describing there is the intended behavior for `prevent_destroy`. To confirm that you want to destroy it, remove the `prevent_destroy` flag before running `terraform destroy`.

The current behavior is there to guarantee that if `terraform destroy` succeeds the state is empty, so that automated systems won't in that case discard a state that still has objects in it. In a future release we intend to change this behavior as part of implementing #4149, where `prevent_destroy = true` would be one more reason why an operation would be deferred, allowing you to see explicitly in the UI that the destroy operation will not fully complete, and thus that automated systems can see that they have not yet completed all of their work. Follow along with that issue if you'd like to see updates on it when we have them.

**Comment by apparentlymart** [comment] 2018-11-29 15:56
@michaelseto,

Since we didn't hear back, I'm going to assume you found a resolution for your issue elsewhere and close this out. If that's not true, please feel free to open a new issue and fill out the issue template fully and we'll try to figure out what's going on. Thanks!

**Closed by apparentlymart** 2018-11-29 15:56 UTC
Labels: bug
