### ISSUE TITLE
Crash during replication instance destroy

### ISSUE THREAD

**Issue by youamara** [hashicorp/terraform#33422] opened 2023-06-23 15:11 UTC
### Terraform Version

```shell
1.3.3
```

### Terraform Configuration Files

```terraform

terraform {
  required_version = "~> 1.3.3"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.62"
    }
  }
  backend "s3" {
    profile        = "***"
    region         = "eu-west-1"
    bucket         = "***"
    key            = "terraform-states/****.tfstate"
    dynamodb_table = "terraform-locks"
  }
}
```

### Debug Output
```
checkable object status report for unexpected checkable object module.landing_zone_dms_tasks.aws_dms_replication_task.dms_task["replication-full-load-agoralive-terraform"]
goroutine 1070 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2bb13e0, 0xc00337f070})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0xc006eebe60, {0x35ee538, 0xc0040440f0}, 0xf48ae0?, 0x0, 0x50)
        /home/circleci/project/project/internal/checks/state_report.go:103 +0x346
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x309fd0e?, {0x35ee538?, 0xc0040440f0?}, 0xc003082080?, 0x1?, 0x54b61?)
        /home/circleci/project/project/internal/checks/state_report.go:68 +0xd0
github.com/hashicorp/terraform/internal/terraform.evalCheckRules(0x35e69d0?, {0xc000e853c0, 0x5, 0xc001ad4230?}, {0x3600638, 0xc0013d80e0}, {0x35ee538, 0xc0040440f0}, {{{{0x0, 0x0}}, ...}, ...}, ...)
        /home/circleci/project/project/internal/terraform/eval_conditions.go:58 +0x417
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc001fd70e0, {0x3600638, 0xc0013d80e0}, 0xc001d736c0, 0x0, 0x0, {0x0, 0x0, 0x0?})
        /home/circleci/project/project/internal/terraform/node_resource_abstract_instance.go:707 +0x4e5
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc0078b90c0, {0x3600638, 0xc0013d80e0})
        /home/circleci/project/project/internal/terraform/node_resource_apply_instance.go:273 +0x7cb
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).Execute(0x0?, {0x3600638?, 0xc0013d80e0?}, 0x40?)
        /home/circleci/project/project/internal/terraform/node_resource_apply_instance.go:140 +0xba
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000dea690, {0x3600638, 0xc0013d80e0}, {0x206ed3c1550, 0xc0078b90c0})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2ff2ae0, 0xc0078b90c0})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000c7c8a0, {0x2ff2ae0, 0xc0078b90c0}, 0xc0078b9ac0)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf65
```

### Expected Behavior

The destruction of a DMS instance

### Actual Behavior

Crash during the destroy (10mns+)

### Steps to Reproduce

1. terraform init --upgrade
2. terraform apply

### Additional Context

The steps of creation
1. Create a DMS S3 target endpoints
2. Create a DMS Tasks with transformations column types created with random-integer module
3. Destroy the DMS S3 endpoints and the DMS tasks with it
4. Recreate a new DMS S3 endpoints and assign it to a DMS Task
5. random-integer rule cannot find the older DMS endpoint which provokes a bug

**Comment by apparentlymart** [comment] 2023-06-23 21:09
Thanks for reporting this, @youamara!

Have you tried this with Terraform v1.5? The concept of custom checks was still quite new in v1.3 and so several bugs in those early releases have been fixed in the meantime, and so this might already be fixed in the latest release.

**Comment by youamara** [comment] 2023-06-26 08:21
There was a bad chain of dependencies which has been resolved by destroying the terraform state of the random integer modules tied to the old DMS Endpoint.
Is it the kind of errors Terraform v1.5 can handle ?

**Comment by jbardin** [comment] 2024-08-28 15:52
Duplicate of #32235

**Closed by jbardin** 2024-08-28 15:52 UTC
Labels: bug, crash, new, v1.3
