### ISSUE TITLE
Feature Request: Verbose option for plan

### ISSUE THREAD

**Issue by calum-github** [hashicorp/terraform#33998] opened 2023-10-06 05:10 UTC
### Terraform Version

```shell
1.3.7
```

### Use Cases

We need to be able to view full plans 
Because of dynamic blocks in our configuration, terraform does not correctly show what its intention is.
This makes it impossible to review the plans and know what is going to happen

### Attempted Solutions

Tried to use the `TF_X_CONCISE_DIFF=0` variable but this has been removed.

### Proposal

re-enable `TF_X_CONCISE_DIFF=0` to allow for full plan diffs

### References

- #27547 
This was closed with no resolution. Incredible.

**Comment by jbardin** [comment] 2023-10-06 13:46
Duplicate of #27547

**Closed by jbardin** 2023-10-06 13:46 UTC
Labels: enhancement, new
