### ISSUE TITLE
Output command of Terraform 1.3.0 shows output variable properties of tfe_output values as null

### ISSUE THREAD

**Issue by dornfeder** [hashicorp/terraform#31883] opened 2022-09-28 08:39 UTC
### Terraform Version

```shell
Terraform v1.3.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.15.0
+ provider registry.terraform.io/hashicorp/tfe v0.36.1
```

### Terraform Configuration Files

**Workspace A**

```terraform
resource "azurerm_resource_group" "example" {
  name     = "MyResourceGroup"
  location = "West Europe"
}

output "rgp" {
  value = {
    id   = azurerm_resource_group.example.id
    name = azurerm_resource_group.example.name
    location = azurerm_resource_group.example.location
  }
}
```

**Workspace B** 
```terraform
data "tfe_outputs" "A" {
  organization = "MyOrg"
  workspace    = "A"
}

output "test1" {
  value = {
    rgp_name = nonsensitive(tfe_outputs.A.values.rgp.name)
    rgp_location = nonsensitive(tfe_outputs.A.values.rgp.location)
  }
}

output "test2" {
  value = nonsensitive(tfe_outputs.A.values.rgp.name)
}

output "test3" {
  value = tfe_outputs.A.values.rgp.location
  sensitive = true
}
```

### Debug Output

https://gist.github.com/dornfeder/fd9104918f5d891fd48b593e4a96d5d2

### Expected Behavior

When running, `terraform output -json`, I would expect all the values of the output variables to be filled properly. 

```json
{
  "test1": {
    "sensitive": false,
    "type": [
      "object",
      {
        "rgp_name": "string",
        "rgp_location": "string"
      }
    ],
    "value": {
      "rgp_name": "MyResourceGroup",
      "rgp_location": "West Europe"
    }
  },
  "test2": {
    "sensitive": false,
    "type": "string",
    "value": "MyResourceGroup"
  },
  "test3": {
    "sensitive": true,
    "type": "string",
    "value": "West Europe"
  },
}
```

### Actual Behavior

When running, `terraform output -json`, only the string output variables are filled correctly. The ones that are properties of an object return `null` instead.

 ```json
{
  "test1": {
    "sensitive": false,
    "type": [
      "object",
      {
        "rgp_name": "string",
        "rgp_location": "string"
      }
    ],
    "value": {
      "rgp_name": null,
      "rgp_location": null
    }
  },
  "test2": {
    "sensitive": false,
    "type": "string",
    "value": "MyResourceGroup"
  },
  "test3": {
    "sensitive": true,
    "type": "string",
    "value": "West Europe"
  },
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform output -json`

### Additional Context

Please note that this behaviour only appeared after upgrading from Terraform `1.2.8` to Terraform `1.3.0`. The `tfe` Provider was NOT updated at any point. This leads me to believe it is a Terraform issue, even though the `tfe` provider is used in the example. 

Also note that using `terraform show`, the values are shown correctly, this seems to be only an issue with the `terraform output` command.

Output of `terraform show`:
```
test1 = {
    rgp_name = "MyResourceGroup"
    rgp_location = "West Europe"
}
test2 = "MyResourceGroup"
test3 = (sensitive value)
```

For `terraform output` without the `-json` flag, the result is similar, but `tostring(null)` is shown instead of `null`. 

Output of `terraform output`: 
```
test1 = {
  "rgp_name" = tostring(null)
  "rgp_location" = tostring(null)
}
test2 = "MyResourceGroup"
test3 = <sensitive>
```

Also, in the UI of Terraform Cloud (which we use only as remote state backend, the plans and applies are executed on local agents), the output variables are displayed correctly as well. 

Pretty sure that all of this is not intended behaviour. With this i have to downgrade back to version 1.2.8 for now.

**Comment by apparentlymart** [comment] 2022-09-28 19:10
Thanks for reporting this, @dornfeder.

I suspect that this difference was caused by #31507. That pull request introduced a new special case where the "cloud" integration implements fetching output values using a Terraform Cloud-specific API designed for that specific purpose, rather than by fetching the entirety of the most recent state snapshot and then extracting just the output values from it. The goal of this change was that it should now be possible to run `terraform output` even if you don't have admin-level access to the remote workspace.

If I'm right about that cause (which I've not yet confirmed) then that would suggest that either that the special output value fetching API is the one returning `null` values here or that the client code for that API in Terraform CLI is incorrect.

@brandonc does the above seem like a plausible theory to you? I'm not really familiar with the Terraform Cloud API that `GetRootOutputValues` accesses, so I can't say whether e.g. the `tfeOutputToCtyValue` function is correct for the shape of value that API returns.

**Comment by brandonc** [comment] 2022-09-28 20:59
@apparentlymart It would appear that in this case the client code for this type of object is incorrect. In particular for this example, the cty type `cty.Object(map[string]cty.Type{"rgp-location":cty.String, "rgp-name":cty.String})` is not appropriate for the go value `map[string]interface {}{"rgp_location":"West Europe", "rgp_name":"MyResourceGroup"}`

**Comment by brandonc** [comment] 2022-09-29 15:38
A fix has been deployed to Terraform Cloud and should be in the next release of Terraform Enterprise. Thank you for reporting it @dornfeder !

**Closed by brandonc** 2022-09-29 15:38 UTC
Labels: bug, confirmed, cloud, v1.3

**Comment by dornfeder** [comment] 2022-10-13 13:20
Just as a conclusive remark, i can reproduce on my side that the behaviour is now as intended, even with Terraform 1.3. Thanks for the quick fix!
