### ISSUE TITLE
Module should support depends_on

### ISSUE THREAD

**Issue by serialx** [hashicorp/terraform#538] opened 2014-11-03 13:30 UTC
When I create a reusable module, it often uses variables that are IDs of the parent's resource. But since module does not support dependency, the parent resource gets created or deleted before the module gets created or deleted. This causes dependency breakage and prevents module reusability.

**Comment by ketzacoatl** [comment] 2015-05-08 04:42
duplicate of #1178, or the other way around (though #1178 has more info at this point)

**Comment by phinze** [comment] 2015-05-26 17:32
Since #1178 caught more recent activity, closing this as the duplicate. But let the record reflect that you were here first, @serialx! :wink:

**Closed by phinze** 2015-05-26 17:32 UTC
Labels: enhancement
