### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by alexmatsuk** [hashicorp/terraform#18018] opened 2018-05-09 22:48 UTC
### Terraform Version
Terraform v0.11.7

ran 'terraform plan' and Terraform crashed

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/hcl/ast.(*ObjectList).Pos(0xc42044bf40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/hcl/ast/ast.go:112 +0x172
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodeString(0xc420219198, 0xc4202a9660, 0x9, 0x37863c0, 0xc42044bf40, 0x2c77d80, 0xc420463180, 0x198, 0x8, 0x18)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:536 +0x8e
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc420219198, 0xc4202a9660, 0x9, 0x37863c0, 0xc42044bf40, 0x2c77d80, 0xc420463180, 0x198, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:106 +0x7f7
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodeStruct(0xc420219198, 0x35df476, 0x4, 0x37863c0, 0xc420460a80, 0x32e9f40, 0xc420463180, 0x199, 0xc420219468, 0x2c77d80)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:697 +0x159f
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc420219198, 0x35df476, 0x4, 0x3786400, 0xc420460a80, 0x32e9f40, 0xc420463180, 0x199, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:108 +0x75b
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.DecodeObject(0x2bd2400, 0xc420463180, 0x3786400, 0xc420460a80, 0x3, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:60 +0x118
github.com/hashicorp/terraform/config.loadVariablesHcl(0xc42044ba20, 0xc420219648, 0x1, 0x1, 0xc42044b9c0, 0x38)
	/opt/gopath/src/github.com/hashicorp/terraform/config/loader_hcl.go:626 +0x502
github.com/hashicorp/terraform/config.(*hclConfigurable).Config(0xc42044b980, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/loader_hcl.go:78 +0xefe
github.com/hashicorp/terraform/config.(*importTree).ConfigTree(0xc42046eb80, 0x7e, 0xc42046eb80, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/import_tree.go:128 +0x49
github.com/hashicorp/terraform/config.LoadFile(0xc420043e80, 0x7e, 0xc420451790, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:56 +0x5f
github.com/hashicorp/terraform/config.LoadDir(0xc420042004, 0x71, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:101 +0x1a3
github.com/hashicorp/terraform/config/module.NewTreeModule(0x0, 0x0, 0xc420042004, 0x71, 0x0, 0xc420219930, 0x2998e04)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:68 +0x39
github.com/hashicorp/terraform/command.(*Meta).Module(0xc42042e680, 0xc420042004, 0x71, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_new.go:46 +0x55
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc42042e680, 0xc420415d40, 0x2, 0x2, 0xc42025d7a0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:77 +0xab3
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202d6500, 0xc4202d6500, 0xc420219d10, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:214 +0xb86
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:99 +0xbb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:35 +0x2e

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

------------------------------------------------------------------------------

crash.log file

2018/05/09 15:38:40 [INFO] Terraform version: 0.11.7  41e50bd32a8825a84535e353c3674af8ce799161
2018/05/09 15:38:40 [INFO] Go runtime version: go1.10.1
2018/05/09 15:38:40 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}
2018/05/09 15:38:40 [DEBUG] Attempting to open CLI config file: /Users/alexm/.terraformrc
2018/05/09 15:38:40 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/05/09 15:38:40 [INFO] CLI command args: []string{"plan"}
2018/05/09 15:38:40 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/hcl/ast.(*ObjectList).Pos(0xc42044bf40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/hcl/ast/ast.go:112 +0x172
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodeString(0xc420219198, 0xc4202a9660, 0x9, 0x37863c0, 0xc42044bf40, 0x2c77d80, 0xc420463180, 0x198, 0x8, 0x18)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:536 +0x8e
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc420219198, 0xc4202a9660, 0x9, 0x37863c0, 0xc42044bf40, 0x2c77d80, 0xc420463180, 0x198, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:106 +0x7f7
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decodeStruct(0xc420219198, 0x35df476, 0x4, 0x37863c0, 0xc420460a80, 0x32e9f40, 0xc420463180, 0x199, 0xc420219468, 0x2c77d80)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:697 +0x159f
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.(*decoder).decode(0xc420219198, 0x35df476, 0x4, 0x3786400, 0xc420460a80, 0x32e9f40, 0xc420463180, 0x199, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:108 +0x75b
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl.DecodeObject(0x2bd2400, 0xc420463180, 0x3786400, 0xc420460a80, 0x3, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl/decoder.go:60 +0x118
github.com/hashicorp/terraform/config.loadVariablesHcl(0xc42044ba20, 0xc420219648, 0x1, 0x1, 0xc42044b9c0, 0x38)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader_hcl.go:626 +0x502
github.com/hashicorp/terraform/config.(*hclConfigurable).Config(0xc42044b980, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader_hcl.go:78 +0xefe
github.com/hashicorp/terraform/config.(*importTree).ConfigTree(0xc42046eb80, 0x7e, 0xc42046eb80, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/import_tree.go:128 +0x49
github.com/hashicorp/terraform/config.LoadFile(0xc420043e80, 0x7e, 0xc420451790, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:56 +0x5f
github.com/hashicorp/terraform/config.LoadDir(0xc420042004, 0x71, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/loader.go:101 +0x1a3
github.com/hashicorp/terraform/config/module.NewTreeModule(0x0, 0x0, 0xc420042004, 0x71, 0x0, 0xc420219930, 0x2998e04)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:68 +0x39
github.com/hashicorp/terraform/command.(*Meta).Module(0xc42042e680, 0xc420042004, 0x71, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta_new.go:46 +0x55
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc42042e680, 0xc420415d40, 0x2, 0x2, 0xc42025d7a0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:77 +0xab3
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202d6500, 0xc4202d6500, 0xc420219d10, 0x1)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:214 +0xb86
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:99 +0xbb
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:35 +0x2e

**Comment by apparentlymart** [comment] 2018-10-30 21:55
Hi @alexmatsuk! Thanks for reporting this and sorry for the slow response.

Since you didn't include an example configuration in your opening comment here I can't say what exactly caused this crash, but we've recently merged in the work from our significant rework of the configuration language handling in Terraform, ready for the forthcoming v0.12.0 release, and the codepath which crashed here is no longer used.

The new configuration decoder uses a schema-driven approach that is far more robust to incorrect input, so I expect that whatever caused this crash will return a more specific error message once v0.12.0 is released.

Because this problem is no longer reproducible, I'm going to close this out. Thanks again for reporting it!

**Closed by apparentlymart** 2018-10-30 21:55 UTC
Labels: bug, config, crash
