### ISSUE TITLE
Terraform user data changes when trying to plan/apply on different machine

### ISSUE THREAD

**Issue by Dineshk77** [hashicorp/terraform#21479] opened 2019-05-28 08:30 UTC
Used a linux machine to perform terraform apply to create ec2 instance
- Instance is successfully created

Rerunning terraform plan/apply on linux machine
- No changes found

Now trying to do terraform plan/apply on windows machine for the same configurations (no changes made to any files)
- Changes detected in user data

Plugins Details:
- (terraform-providers/template) 2.1.2...
- (terraform-providers/aws) 2.12.0...
- (terraform-providers/null) 2.1.2...

Backend Details:
- S3

Terraform version:
- 0.12

**Comment by apparentlymart** [comment] 2019-05-28 15:12
Hi @Dineshk77!

It's hard to say for sure what's going on here without being able to look at the machines in question, but my guess here would be that you are cloning the Terraform configuration from Git and on the Windows system it's configured to automatically convert from Unix-style to Windows-style line endings when cloning, and so a template that you are using to populate `user_data` therefore has different content (different line endings) when closed on Windows.

If that is the cause here, the Git setting [`core.autocrlf`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code) is how to control that setting. The requirement here is to ensure that Terraform running on Windows is seeing byte-for-byte identical files to Terraform running on Linux, so you can either change this setting to `false` and disable Git's automatic newline processing altogether (and make sure anyone editing files on Windows configures their editor properly to generate Unix-style line endings) or you could try setting it to `input` to normalize any files containing Windows-style line endings to Unix-style but not vice-versa.

Another option is to use [`.gitattributes`](https://git-scm.com/docs/gitattributes) inside your repository to tell git that your Terraform source files and any separate template files are to be treated as "binary", and thus not subject to any automatic rewriting of any sort, so that git will preserve them exactly as-is (byte for byte) on Windows systems, regardless of the `autocrlf` setting. You can see some other options on that `.gitattributes` page too, and so you may be able to find other permutations that get the same result; I've not tried all of them, so I can't be sure what will and will not work here.

Terraform does not attempt to normalize this itself because Terraform can be used to configure remote Windows systems too, in which case it is expected for a source template to contain Windows-style line endings and these must be preserved when rendering the template so that the file can be correctly interpreted by the remote Windows system. Therefore unfortunately you must take care to ensure that each file has the appropriate line endings yourself, one way or another.

**Comment by apparentlymart** [comment] 2019-07-11 23:34
Hi @Dineshk77,

We didn't hear from you again after my previous response, so I'm going to close this under the assumption that my previous comment helped you fix the issue.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are more people ready to help. If you are still having problems, please feel free to ask about them in the community forum!

**Closed by apparentlymart** 2019-07-11 23:34 UTC
