### ISSUE TITLE
Cross account VPC peering connections not working after Terraform upgrade

### ISSUE THREAD

**Issue by jjones-smug** [hashicorp/terraform#23938] opened 2020-01-23 22:48 UTC
### Terraform Version

```
Terraform v0.12.16
+ provider.aws v2.37.0
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
# in AWS account #1

resource "aws_vpc_peering_connection" "name1" {
  peer_owner_id = var.account_id["name1"]
  peer_vpc_id   = "vpc-ff00ff00ff00ff00f"
  vpc_id        = "vpc-ff00ff00"
  auto_accept   = true

  tags = {
    Name = "name1 peering"
  }

  requester {
    allow_classic_link_to_remote_vpc = false
    allow_vpc_to_remote_classic_link = false
    allow_remote_vpc_dns_resolution = false
  }

}

# in AWS account #2

resource "aws_vpc_peering_connection_accepter" "name2" {
    vpc_peering_connection_id = "pcx-ee11ee11ee11ee11e"
    auto_accept = true

    tags = {
        Name = "name2"
    }

    accepter {
        allow_classic_link_to_remote_vpc = false
        allow_remote_vpc_dns_resolution  = false
        allow_vpc_to_remote_classic_link = false
    }
}
```

### Crash Output

Terraform does not crash.

### Expected Behavior

- Run "plan/apply" in AWS account #1 to create one end of the VPC peering connection
- Run "plan/apply" in AWS account #2 to accept the VPC peering connection
- Run "plan/apply" in AWS account #1 afterwards to add routing table entries (not shown in configs, but they are trivial)

### Actual Behavior

The final "plan/apply" in AWS account #1 marks the VPC peering point as "tainted" and wants to destroy/recreate it.  That breaks the configuration in AWS account #2, since there's a new VPC peering point id.  As a result there's an endless loop which can only be resolved by "untainting" the VPC peering point once it's connected, then running a "plan/apply" to add the routing table entries in AWS account #1.

### Steps to Reproduce

1. run `terraform init`, `terraform plan` and `terraform apply` in AWS account #1
2. take the `pcx-###` id of the VPC peering point created above and update the configs in AWS account #2
3. run `terraform init`, `terraform plan` and `terraform apply` in AWS account #2
4. run `terraform plan` and `terraform apply` in AWS account #1

### Additional Context

This configuration worked on our v0.11 system and we just recently upgraded.

### References

I don't see any other open issue that seem closely related.

**Comment by teamterraform** [comment] 2020-01-24 01:19
Hi @jjones-smug! Sorry for this change in behavior, and thanks for reporting it.

Since the configuration snippets you shared are partial, we can't follow your reproduction steps exactly here, but we understand that it's often hard to tease apart a problematic part of a very large configuration. We might be able to figure out what's going on here if you're able to share the output from `terraform plan` in your step 4 under "Steps to Reproduce".

Specifically, we'd like to see what exactly Terraform is proposing to do with the objects in your AWS account 1 on that second plan, because we can then hopefully work backwards from that to how Terraform is making that decision, and thus hopefully understand what's different about Terraform 0.12 than Terraform 0.11 in this case.

Thanks!

**Comment by jjones-smug** [comment] 2020-01-24 02:35
[complete-terraform-cycle-cleaned.txt](https://github.com/hashicorp/terraform/files/4106600/complete-terraform-cycle-cleaned.txt)
I've uploaded a redacted screen capture of all the steps listed.

**Comment by apparentlymart** [comment] 2020-02-14 00:45
Thanks for sharing that full output, @jjones-smug! Makes it much easier to understand what's going on.

I think what changed here is that 0.12.0 fixed a bug where errors during a resource creation would sometimes (for certain error types) incorrectly leave an incomplete object in the Terraform state which Terraform would then believe to be valid on future updates. Terraform 0.12.0 and later now correctly mark failed creation as tainted in all cases, so that future runs know not to build on that failed object.

It seems that you developed a workflow on 0.11 that was unfortunately relying on this bug, and so sadly fixing the bug has broken your workflow. Given that this change of behavior was intentional and reverting it would reintroduce incorrect behavior for others, I think the path forward here would be to devise a new approach that doesn't rely on ignoring an error during your initial apply.

---

I'd like to help you find a new approach here, but unfortunately I've not previously used VPC peering. I've done some quick research in the AWS provider documentation just now to see how the parts fit together and one thing stuck out to me in the documentation for `auto_accept` on [`aws_vpc_peering_connection`](https://www.terraform.io/docs/providers/aws/r/vpc_peering_connection.html) (emphasis mine):

> * `auto_accept` - (Optional) Accept the peering **(both VPCs need to be in the same AWS account)**.

The way I understand the broader provider docs is that there are two distinct approaches to setting up VPC peering with Terraform:

1. Use _only_ `aws_peering_connection` with `auto_accept` to both create and accept the peering connection in a single step, relying on the fact that the current AWS credentials have access to call both [`CreateVpcPeeringConnection`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcPeeringConnection.html) and [`AcceptVpcPeeringConnection`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AcceptVpcPeeringConnection.html) by virtue of both of those calls happening against the same AWS account.
2. Use both `aws_peering_connection` and `vpc_peering_connection_accepter` together, _without_ `auto_accept`, to run `CreateVpcPeeringConnection` and `AcceptVpcPeeringConnection` as two separate steps, potentially in different Terraform configurations or against two different AWS accounts used in the same Terraform configuration.

It seems that your configuration is blending both of these approaches, which I don't think is an intended usage model. Presumably it was working for you on 0.11 because although the `AcceptVpcPeeringConnection` call failed in the first configuration, applying the second configuration with `vpc_peering_connection_accepter` called `AcceptVpcPeeringConnection` successfully as if you were using permutation 2 from the list above.

With all of that said, I wonder if removing `auto_accept` from your `aws_vpc_peering_connection` in the first configuration would be enough to make this work. I think that would also simplify the workflow so that the third step of re-applying the first configuration isn't needed, because the `AcceptVpcPeeringConnection` call from the second configuration would be sufficient to move the peering connection from `pending-acceptance` state to `active`.

Does that make sense? I'm probably missing some details since I'm learning this resource type and API on the fly, so if the above isn't sufficient I'd love to hear more about why and hopefully we can iterate towards a viable new approach for you.

**Comment by danieldreier** [comment] 2020-04-28 00:14
@jjones-smug I'm going to close this issue because it's been waiting for a response since February 13th. If you're still having this issue and would like to keep discussing it, please feel free to let us know, and make sure to link this issue if you file a new one so that we have that context. 

If you're not quite sure whether it's a bug or a question, you might post on [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

**Closed by danieldreier** 2020-04-28 00:14 UTC
Labels: bug, core, v0.12, waiting-response

**Comment by bitsofdave** [comment] 2020-05-01 17:33
I can confirm leaving `auto_accept` off on `aws_peering_connection` still results in a tainted state:
```
Error: Unable to modify peering options. The VPC Peering Connection "pcx-<redacted>" is not active. Please set `auto_accept` attribute to `true`, or activate VPC Peering Connection manually.
```

I can't set `auto_accept=true` on a cross-account vpc peering request:
```
Error: Unable to accept VPC Peering Connection: OperationNotPermitted: User <id> cannot accept peering pcx-<redacted>
```

```
$ terraform version
Terraform v0.12.24
+ provider.aws v2.57.0
```

Each `terraform apply` attempts to recreate this peering connection.

Should I file this as a new issue?

**Comment by apparentlymart** [comment] 2020-05-02 00:01
Hi @bitsofdave!

I'm sorry that the suggestion I made earlier didn't work out. It seems that I didn't fully understand the intended usage of these AWS provider resources in my quick research there.

I have a feeling that what you are seeing relates to the warning box at the top of [the `aws_vpc_peering_connection` documentation page](https://www.terraform.io/docs/providers/aws/r/vpc_peering_connection.html) at the time I write this, which I'll quite here for posterity in case that page changes in future:

> **NOTE on VPC Peering Connections and VPC Peering Connection Options:** Terraform provides both a standalone VPC Peering Connection Options and a VPC Peering Connection resource with accepter and requester attributes. Do not manage options for the same VPC peering connection in both a VPC Peering Connection resource and a VPC Peering Connection Options resource. Doing so will cause a conflict of options and will overwrite the options. Using a VPC Peering Connection Options resource decouples management of the connection options from management of the VPC Peering Connection and allows options to be set correctly in cross-account scenarios.

I'm not entirely sure what this is suggesting to do, but I think the options resource type it is referring to is [`aws_vpc_peering_connection_options`](https://www.terraform.io/docs/providers/aws/r/vpc_peering_connection_options.html). The error message you saw directing you to use `auto_accept` [seems to be related to the `requester` and `accepter` blocks](https://github.com/terraform-providers/terraform-provider-aws/blob/7ce1660fd27d4de99793b7c01a56ec98226d0a34/aws/resource_aws_vpc_peering_connection.go#L251-L253), so it seems like you must either use `auto_accept` to create both "sides" of the peering at once (which, as you've seen, is impossible for cross-account peering) or you must specify the options using the separate options resource type instead.

I hope the above is helpful, but I'm well beyond my AWS Provider expertise here. If the above doesn't help you find a working approach, I'd recommend asking in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). I see a couple questions about VPC peering asked and answered there, so it seems like there's some community experience with these features and so hopefully someone there can help find the correct combination of things to make this work.

**Comment by bitsofdave** [comment] 2020-05-04 17:33
Thanks for response @apparentlymart. That warning text does seem relevant because I did have a requester options block that terraform tried to apply, but couldn't because the requester side needed to accept first.
