### ISSUE TITLE
depends_on should wait for template_dir generation

### ISSUE THREAD

**Issue by aosman-tibco** [hashicorp/terraform#23684] opened 2019-12-16 12:28 UTC
### Terraform Version

```
Terraform v0.12.18
+ provider.aws v2.41.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
resource "template_dir" "policies" {
  source_dir      = var.policies
  destination_dir = "${path.cwd}/policies"

  vars = {
    email   = var.recipient_email
    sqs_url = aws_sqs_queue.foo.id
  }
}

resource "aws_s3_bucket_object" "policies" {
  depends_on  = [template_dir.policies]
  for_each    = fileset(template_dir.policies.destination_dir, "**/*")

  bucket      = data.aws_s3_bucket.this.id
  key         = "policies/${each.value}"
  source      = "${template_dir.policies.destination_dir}/${each.value}"
  etag        = filemd5("${template_dir.policies.destination_dir}/${each.value}")

}

```

### Expected Behavior
Templates are generated and aws_s3_bucket_object is aware of them (causing them to be uploaded)

### Actual Behavior
Templates are generated and aws_s3_bucket_object is not aware of them, therefore no action is taken. A second apply is required to upload the generated files.
If the generated files are deleted, the aws_s3_bucket_object detects the source files as missing then then deletes the resources (even if the files are generated again). A second apply is required to upload the generated files.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

- #22036

**Comment by jbardin** [comment] 2019-12-16 15:45
Hi @aosman-tibco,

The purpose of `depends_on` is to add a dependency between resource where there's no way to reference on resource from another. The `depends_on` value you have here is redundant with the `template_dir.policies.destination_dir` references in the config. 

The problem is that because the `template_dir.policies.destination_dir` value is already known, the `fileset` and `filemd5` functions will take the known value and compute it immediately.

Since the referenced issue already covers this feature request in `depends_on should should defer interpolation`, I'm going to tag this for the `template` provider in case it makes sense to fix this specific case by adding a computed attribute to delay interpolation.

**Comment by aosman-tibco** [comment] 2019-12-16 16:10
Thanks @jbardin 

I took a second look at the template provider documentation for `template_dir` and it indicates that it should be populating the directory before another resource consumes it:

```
destination_dir - The destination directory given in configuration. Interpolate this attribute into other resource configurations to create a dependency to ensure that the destination directory is populated before another resource attempts to read it.
```

**Comment by jbardin** [comment] 2019-12-16 16:16
Thanks for catching that @aosman-tibco, that should be fixed. You can see above there we warn against this case in particular:

> Note that it is not safe to use the `file` interpolation function to read files created by this resource, since that function can be evaluated before the destination directory has been created or updated

I'll have this transferred to the provider so the docs can be sorted out at the same time.

**Closed** 2019-12-16 16:20 UTC
Labels: enhancement, provider/template
