### ISSUE TITLE
aws_db_instance issues

### ISSUE THREAD

**Issue by dene14** [hashicorp/terraform#9392] opened 2016-10-16 16:57 UTC
Hi there,
### Terraform Version

$ terraform -v
Terraform v0.7.6
### Affected Resource(s)
- aws_db_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
### Terraform Configuration Files

``` hcl
resource "aws_db_instance" "rds" {
    identifier = "${var.environment}-rds"
    allocated_storage = 300
    engine = "mysql"
    engine_version = "5.6.27"
    instance_class = "db.m4.large"
    storage_type = "gp2"
    final_snapshot_identifier = "${var.environment}-rds"
    username = "admin"
    password = "password"
    parameter_group_name = "${aws_db_parameter_group.rds.id}"
    db_subnet_group_name = "${aws_db_subnet_group.rds.name}"
    maintenance_window   = "mon:02:00-mon:04:00"
    backup_retention_period = 7
    backup_window = "00:00-02:00"
    vpc_security_group_ids = ["${aws_security_group.rds.id}"]
    multi_az = true
    apply_immediately = false
}
```
### Behavior
1. Change of instance identifier is possible as normally for any of the instance attributes within AWS API, however it triggers instance recreation in terraform.
2. `final_snapshot_identifier` is set, not sure if it was actually taken... However all the snapshots related to DB instance purged as soon as `aws_db_instance` resource destroyed...

**Comment by jbardin** [comment] 2016-10-19 20:34
Hi @dene14,

The `identifier` field in the `aws_db_instance` is defined as `ForceNew`, which means any change will destroy the exiting instance, and create e new one. 

While destroying the instance is the expected behavior, the documentation does make it sound like there should be final snapshot.

**Comment by stack72** [comment] 2016-11-03 13:20
Hi @dene14 

I am going to close this as a duplicate of #6080 - this is a long standing feature request. I had an attempt at this before (linked in the other issue) but I think this is something that is going to need a lot of extra thought

Paul

**Closed by stack72** 2016-11-03 13:20 UTC
Labels: bug, provider/aws
