### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by angelosanramon** [hashicorp/terraform#16001] opened 2017-09-02 02:13 UTC
Just tried 0.10.3 and getting the error below. When I switch back to 0.10.2 everything works fine.

### Terraform Version
Terraform v0.10.3

### Terraform Configuration Files
```hcl
module "2b32741c-cf9b-4edb-b1de-9a2f74b99fc6" {
  source                     = "../../modules/create_stack"
  uuid                       = "2b32741c-cf9b-4edb-b1de-9a2f74b99fc6"
  project                    = "${var.project}"
  environment                = "${var.environment}"
  role                       = "${var.role}"
  version                    = "${var.version}"
  hostname_format            = "${var.hostname_format == "" ? format("%s-%s-%s-%s",var.project,var.environment,var.role,var.project == "chariot" ? replace(var.version, ".", "-") : format("%02s%02s%03s", element(split(".", var.version),0), element(split(".", var.version),1), element(split(".", var.version),2))) : var.hostname_format}"
  ami                        = "${var.ami}"
  instance_type              = "${var.instance_type}"
  key_name                   = "${var.key_name}"
  subnet                     = "subnet-6205fc2a"
  security_groups            = "${var.security_groups}"
  health_check_port          = "${var.health_check_port}"
  health_check_type          = "${var.health_check_type}"
  health_check_uri           = "${var.health_check_uri}"
  cloudwatch_alarm_actions   = "${var.cloudwatch_alarm_actions}"
  cloudwatch_alarm_okactions = "${var.cloudwatch_alarm_okactions}"
  route53_hosted_zone_id     = "${var.route53_hosted_zone_id}"
  route53_hosted_zone_domain = "${var.route53_hosted_zone_domain}"
  access_key                 = "${var.access_key}"
  secret_key                 = "${var.secret_key}"
  region                     = "${var.region}"
}

terraform {
  backend "consul" {
    address      = "http://172.17.2.41:8080"
    path         = "terraform/states/chariot-zis-xre-test"
    access_token = "4a657680-724a-11e6-b76d-080027b1f844"
    datacenter   = "kitchen"
  }
}
```

### Debug Output
```
2017/09/01 19:08:47 [INFO] Terraform version: 0.10.3  1511d447e78d8106787875265f96d3a3a03005d5
2017/09/01 19:08:47 [INFO] Go runtime version: go1.9
2017/09/01 19:08:47 [INFO] CLI args: []string{"/Users/asanra001c/bin/terraform", "init", "-get=true"}
2017/09/01 19:08:47 [DEBUG] Attempting to open CLI config file: /Users/asanra001c/.terraformrc
2017/09/01 19:08:47 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/09/01 19:08:47 [INFO] CLI command args: []string{"init", "-get=true"}
2017/09/01 19:08:47 [DEBUG] command: loading backend config file: /Users/asanra001c/workspace/zis-terraform-deployment/configurations/chariot-zis-xre-test
Downloading modules...
Get: file:///Users/asanra001c/workspace/zis-terraform-deployment/modules/create_stack
Get: file:///Users/asanra001c/workspace/zis-terraform-deployment/modules/create_stack

Initializing the backend...
2017/09/01 19:08:47 [TRACE] Preserving existing state lineage "969c0950-5a7a-47e4-8646-9dcb209f6d8f"
2017/09/01 19:08:47 [TRACE] Preserving existing state lineage "969c0950-5a7a-47e4-8646-9dcb209f6d8f"
2017/09/01 19:08:47 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1afb7af]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).clientRaw(0xc42043d520, 0x2deed8d, 0x4, 0x2705600)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:152 +0x3af
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).configure(0xc42043d520, 0x41e9de0, 0xc420464510, 0x270d740, 0xc42045b340)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:116 +0x9f
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).(github.com/hashicorp/terraform/backend/remote-state/consul.configure)-fm(0x41e9de0, 0xc420464510, 0x270d740, 0xc42045b340)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:96 +0x3e
github.com/hashicorp/terraform/helper/schema.(*Backend).Configure(0xc42043d500, 0xc4204640f0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/backend.go:80 +0x186
github.com/hashicorp/terraform/command.(*Meta).backend_C_r_S_unchanged(0xc420001680, 0xc420264b80, 0x41ecb00, 0xc420433680, 0x1c, 0x10979bb, 0xc42000c018, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:1188 +0x1bd
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc420001680, 0xc4201cdae8, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:398 +0xdcc
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc420001680, 0xc420607ae8, 0x28, 0xc42026ae40, 0x28, 0xc42026ae10)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:88 +0x83c
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc420001680, 0xc42000e0e0, 0x1, 0x1, 0xc4201a9fc0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:200 +0xd32
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202377a0, 0xc4202377a0, 0xc4201cdcf8, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:188 +0xac0
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:95 +0xbb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:31 +0x38
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1afb7af]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).clientRaw(0xc42043d520, 0x2deed8d, 0x4, 0x2705600)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:152 +0x3af
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).configure(0xc42043d520, 0x41e9de0, 0xc420464510, 0x270d740, 0xc42045b340)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:116 +0x9f
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).(github.com/hashicorp/terraform/backend/remote-state/consul.configure)-fm(0x41e9de0, 0xc420464510, 0x270d740, 0xc42045b340)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:96 +0x3e
github.com/hashicorp/terraform/helper/schema.(*Backend).Configure(0xc42043d500, 0xc4204640f0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/backend.go:80 +0x186
github.com/hashicorp/terraform/command.(*Meta).backend_C_r_S_unchanged(0xc420001680, 0xc420264b80, 0x41ecb00, 0xc420433680, 0x1c, 0x10979bb, 0xc42000c018, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:1188 +0x1bd
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc420001680, 0xc4201cdae8, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:398 +0xdcc
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc420001680, 0xc420607ae8, 0x28, 0xc42026ae40, 0x28, 0xc42026ae10)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:88 +0x83c
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc420001680, 0xc42000e0e0, 0x1, 0x1, 0xc4201a9fc0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:200 +0xd32
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202377a0, 0xc4202377a0, 0xc4201cdcf8, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:188 +0xac0
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:95 +0xbb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:31 +0x38



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Crash Output
```
2017/09/01 19:08:47 [INFO] Terraform version: 0.10.3  1511d447e78d8106787875265f96d3a3a03005d5
2017/09/01 19:08:47 [INFO] Go runtime version: go1.9
2017/09/01 19:08:47 [INFO] CLI args: []string{"/Users/asanra001c/bin/terraform", "init", "-get=true"}
2017/09/01 19:08:47 [DEBUG] Attempting to open CLI config file: /Users/asanra001c/.terraformrc
2017/09/01 19:08:47 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/09/01 19:08:47 [INFO] CLI command args: []string{"init", "-get=true"}
2017/09/01 19:08:47 [DEBUG] command: loading backend config file: /Users/asanra001c/workspace/zis-terraform-deployment/configurations/chariot-zis-xre-test
2017/09/01 19:08:47 [TRACE] Preserving existing state lineage "969c0950-5a7a-47e4-8646-9dcb209f6d8f"
2017/09/01 19:08:47 [TRACE] Preserving existing state lineage "969c0950-5a7a-47e4-8646-9dcb209f6d8f"
2017/09/01 19:08:47 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1afb7af]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).clientRaw(0xc42043d520, 0x2deed8d, 0x4, 0x2705600)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:152 +0x3af
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).configure(0xc42043d520, 0x41e9de0, 0xc420464510, 0x270d740, 0xc42045b340)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:116 +0x9f
github.com/hashicorp/terraform/backend/remote-state/consul.(*Backend).(github.com/hashicorp/terraform/backend/remote-state/consul.configure)-fm(0x41e9de0, 0xc420464510, 0x270d740, 0xc42045b340)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/consul/backend.go:96 +0x3e
github.com/hashicorp/terraform/helper/schema.(*Backend).Configure(0xc42043d500, 0xc4204640f0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/backend.go:80 +0x186
github.com/hashicorp/terraform/command.(*Meta).backend_C_r_S_unchanged(0xc420001680, 0xc420264b80, 0x41ecb00, 0xc420433680, 0x1c, 0x10979bb, 0xc42000c018, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:1188 +0x1bd
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc420001680, 0xc4201cdae8, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:398 +0xdcc
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc420001680, 0xc420607ae8, 0x28, 0xc42026ae40, 0x28, 0xc42026ae10)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:88 +0x83c
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc420001680, 0xc42000e0e0, 0x1, 0x1, 0xc4201a9fc0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:200 +0xd32
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4202377a0, 0xc4202377a0, 0xc4201cdcf8, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:188 +0xac0
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:95 +0xbb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:31 +0x38
```

### Expected Behavior
Terraform should initialize without error

### Actual Behavior
Got the error above

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init -get=true`

### Important Factoids
None

### References
None

**Comment by jbardin** [comment] 2017-09-05 21:19
Hi @angelosanramon, thanks for the report! This is duplicate of #15972

**Closed by jbardin** 2017-09-05 21:19 UTC
Labels: backend/consul, bug, crash, regression
