### ISSUE TITLE
Crash when list is assigned to string parameter

### ISSUE THREAD

**Issue by choosy** [hashicorp/terraform#2984] opened 2015-08-12 18:21 UTC
Got this crash report.

https://gist.github.com/choosy/a41dde20526671837943

**Comment by apparentlymart** [comment] 2015-08-12 22:16
@choosy it looks like you got this error with a ``aws_route_table_association`` resource. Would you mind sharing the configuration of that object so that it's easier to see how to reproduce this?

**Comment by choosy** [comment] 2015-08-13 08:32
Hi @apparentlymart,

I have put it here:
https://gist.github.com/choosy/2c028c780b23ac65d127

Thank you for your investigation.

**Comment by apparentlymart** [comment] 2015-08-13 17:38
I think the problem here is that you've put a list as the value of ``subnet_id`` (on line 186) but it expects only a single string.

It is a bug in Terraform that this wasn't caught during the configuration validation step and instead blew up inside the diffing logic. However, you can work around that bug by using a separate ``aws_route_table_association`` resource for each pair of ``route_table_id`` and ``subnet_id``, like this:

```js
resource "aws_route_table_association" "rt-assoc-dmz" {
    route_table_id = "${aws_route_table.rt-vpc18-dmz.id}"
    subnet_id = "${aws_subnet.vpc18-dmz-us-east-1b.id}"
}
resource "aws_route_table_association" "rt-assoc-dmz" {
    route_table_id = "${aws_route_table.rt-vpc18-dmz.id}"
    subnet_id = "${aws_subnet.vpc18-dmz-us-east-1c.id}"
}
resource "aws_route_table_association" "rt-assoc-dmz" {
    route_table_id = "${aws_route_table.rt-vpc18-dmz.id}"
    subnet_id = "${aws_subnet.vpc18-dmz-us-east-1d.id}"
}
resource "aws_route_table_association" "rt-assoc-dmz" {
    route_table_id = "${aws_route_table.rt-vpc18-dmz.id}"
    subnet_id = "${aws_subnet.vpc18-dmz-us-east-1e.id}"
}
```

**Comment by choosy** [comment] 2015-08-14 08:21
Hi @apparentlymart ,

That was it. I managed to get passed that using your example.

Thank you!

**Comment by apparentlymart** [comment] 2015-08-15 01:18
Great! I'm glad that worked out. @choosy would you mind changing the title of your issue to "Crash when list is assigned to string parameter"? That should make it easier for folks to find this issue and increase the chance that it'll be fixed.

**Comment by apparentlymart** [comment] 2015-08-15 22:53
I can repro your crash with your exact config but interestingly if I try to simplify it to just the core issue of using a list instead of a string then it ceases to be a crash and instead appears as a regular error:

```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_route_table_association.foo: '' expected type 'string', got unconvertible type '[]interface {}'
```

Here is my simplified config:

```
resource "aws_route_table_association" "foo" {
    route_table_id = "bar"
    subnet_id = ["baz", "foo"]
}
```

Either way this is not a user-friendly error message since it uses Go type system terminology rather than Terraform config language terminology. Feels to me like there's a missing check earlier up the chain that should've caught this in both cases, and it just happens that in one case it gets ``panic``ed and in the other case it gets returned but either way it's a "should never happen"-type situation.

**Comment by apparentlymart** [comment] 2015-08-15 23:53
I made a nicer validation error message in #3009, but that hasn't fixed this crash. It seems that somehow the ``aws_route_table_association`` resource block in @choosy's config is bypassing the ``Validate`` step, since the crash still returns the internal ``mapstructure`` error message and not the new, higher-level message introduced in that other PR.

**Comment by apparentlymart** [comment] 2015-08-16 00:08
I found the trick: because there were interpolations of computed values in the list, the validator skipped validating that field. My updated patch in #3009 now checks for lists even when the list values are computed, so we get the proper error message and not a crash with @choosy's config.

**Closed** 2015-10-23 04:23 UTC
Labels: bug, provider/aws
