### ISSUE TITLE
Can't re-use plan with http backend

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform#28649] opened 2021-05-07 19:17 UTC
### Terraform Version
```
Terraform v0.15.0
on linux_amd64
```

### The problem
I have following in main.tf:

```terraform
terraform {
  required_version = ">=0.14.0"

  required_providers {
...
  }

  backend "http" {
    lock_method    = "POST"
    unlock_method  = "DELETE"
    retry_wait_min = 5
  }

}
```
Then as first step of a pipeline I generate plan:
```
terraform -chdir=${TF_WORK_DIR} init -reconfigure \
      -backend-config address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}" \
      -backend-config lock_address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}/lock" \
      -backend-config unlock_address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}/lock" \
      -backend-config username="gitlab-ci-token" \
      -backend-config password="${CI_JOB_TOKEN}"
terraform -chdir=${TF_WORK_DIR} plan -input=false -out=environment.tfplan
```
After that second step of the pipeline runs apply like this:
```
terraform -chdir=${TF_WORK_DIR} init -reconfigure \
      -backend-config address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}" \
      -backend-config lock_address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}/lock" \
      -backend-config unlock_address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}/lock" \
      -backend-config username="gitlab-ci-token" \
      -backend-config password="${CI_JOB_TOKEN}"
terraform -chdir=${TF_WORK_DIR} apply -auto-approve -input=false environment.tfplan
```
Init and plan go fine. But because ${CI_JOB_TOKEN} from above changes each time pipeline goes a step forward, init and apply fail and I get permission deny. When I use personal static token, issue does not appear. This can mean only one thing - password goes into generated plan, which is not a desired behavior

**Comment by apparentlymart** [comment] 2021-05-10 23:24
Hi @vladimirtiukhtin,

It's by design that the backend configuration is part of the plan, but we also typically recommend specifying only location-related information in the actual backend configuration, and leaving authentication information like the username/password here to be specified out-of-band by other means.

For vendor-specific backends the backend will typically follow the conventions of the platform in question, but since the HTTP backend is generic it has its own convention for out-of-band settings via environment variables. So for example:

```bash
export TF_HTTP_USERNAME=gitlab-ci-token
export TF_HTTP_PASSWORD="${CI_JOB_TOKEN}"
terraform -chdir="${TF_WORK_DIR}" init \
      -backend-config address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}" \
      -backend-config lock_address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}/lock" \
      -backend-config unlock_address="https://gitlab.com/api/v4/projects/XXX/terraform/state/${CI_COMMIT_REF_SLUG}/lock"
```

Notice here that the _location_ information is still given as part of the backend configuration, but the authentication information is provided via environment variables. This should therefore mean that they won't be saved as part of the backend configuration in the plan and thus you can re-set those environment variables differently when you later run `terraform apply`.

This separation between location settings and authentication settings is an intentional design tradeoff to help avoid applying a plan to a state other than what it was created for.

**Comment by mildwonkey** [comment] 2021-06-07 18:00
I am going to close this issue, since there does not appear to be any Terraform work needed. Thanks!

**Closed by mildwonkey** 2021-06-07 18:00 UTC
Labels: bug, new
