### ISSUE TITLE
Enable CloudWatch logging with Kinesis Firehose

### ISSUE THREAD

**Issue by bvingerh** [hashicorp/terraform#8838] opened 2016-09-14 14:19 UTC
Hi there,

I'm setting up an AWS Kinesis Firehose stream and I'd like to enable CloudWatch logging. This is possible with the AWS SDK: http://docs.aws.amazon.com/firehose/latest/APIReference/API_CreateDeliveryStream.html but doesn't seem to be supported by Terraform yet.

Since I needed it quite urgently, I've made a custom build and provide you my changes herewith.
Could you incorporate these changes and/or provide your own implementation to support this functionality? That way I won't have to distribute my custom binaries to everyone involved in the infrastructure I'm setting up.

Pull request: https://github.com/hashicorp/terraform/pull/8837

Thanks in advance,
Bert Vingerhoets

**Comment by vancluever** [comment] 2016-09-15 14:46
Hey @bvingerh - Just a FYI you might want to change this to read **CloudWatch** logging instead of **CloudFront** logging. I came here looking for CloudFront issues and noticed this.

**Comment by bvingerh** [comment] 2016-09-15 17:10
woops; sorry; I'm using both in my project; must have gotten confused ;-)

**Comment by stack72** [comment] 2016-09-21 08:00
Hi @bvingerh 

Thanks for the issue here - I am going to close this as a duplicate of #7152 

Paul

**Closed by stack72** 2016-09-21 08:00 UTC
Labels: enhancement, provider/aws
