### ISSUE TITLE
Terraform test: consider exposing a way to ensure idempotency (no changes in plan)

### ISSUE THREAD

**Issue by matt-FFFFFF** [hashicorp/terraform#35534] opened 2024-08-05 11:51 UTC
### Terraform Version

```shell
Terraform v1.9.3
on linux_amd64
```

### Use Cases

I need to be able to assert that a plan produces no changes (e.g. a configuration is idempotent).

### Attempted Solutions

I have tried comparing outputs between runs, but to achieve what I want I would have to create a composite output with all resources - something that is only required for testing and I don't want in the module

### Proposal

Expose resource changes in terraform test - akin to <https://github.com/hashicorp/terraform-json/blob/main/plan.go#L61>

Though, perhaps `plan.resource_changes` could be a map, to make any assertions simpler?

Assertions can be made, e.g.

- If `length(plan.resource_changes) == 0` then there are no changes
- If `plan.resource_changes["foo_bar.baz"].from.attribute == plan.resource_changes["foo_bar.baz"].to.attribute` then we can assert that this specific attr has not changed.

```terraform
run "apply" {
  command = "apply"
}

run "plan" {
  command = "plan"

  assert {
    condition     = length(plan.resource_changes) == 0
    error_message = "Configuration is not idempotent"
  }
}
```

### References

Implements this functionality from terratest...

https://github.com/gruntwork-io/terratest/blob/5a799830eb197681fcd3a448d9c5ee87eeba2482/modules/terraform/apply.go#L62-L70

**Comment by liamcervante** [comment] 2024-08-05 12:46
Hi @matt-FFFFFF, thanks for filing this. I do think it is a duplicate of https://github.com/hashicorp/terraform/issues/34500. I will close this as a duplicate, but let me know if there's something significantly different here.

Your proposal here does line up fairly closely with how I imagined something like this would work. This issue should be linked from the other issue now, so your suggestion here will definitely be helpful when we get around to discovery. Thanks!

**Closed by liamcervante** 2024-08-05 12:46 UTC
Labels: enhancement, new, terraform test
