### ISSUE TITLE
string split operation - last element overflowing to the beginning

### ISSUE THREAD

**Issue by MartinHoge** [hashicorp/terraform#28249] opened 2021-03-31 15:01 UTC
Hi

I discovered a bug in string operation - split.  Problem is with the last element + 1 of returned collection,
it's value is ending with the beginning of splitted string.

example:
  entry: ABC/DEF/GHJ/KLM
  element(collection,3) is expected to be: KLM - correct
  element(collection,4) is expected to be null, empty 
  reality:  element(x,4) = "ABC"

how to reproduce it, real example with output below ( just copy&paste to main.tf and run TF init+TF plan ):
_please note following: element with index 9 should not exist, it was there by mistake. But that mistake revealed
   this bug, that if we get to the last item of collection and just ask one another element - it should return nothing
  and definitely not beginning of the string._

```
locals { originalpath = "**martin**://prod-24.westeurope.logic.azure.com:443/workflows/f95951326b5f4906828a5b8f123123123/triggers/manual/paths/invoke?sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=dlOJV8tVC"
   splittedPath = split("/",local.originalpath)  
   serviceUrlCalculatedPath = >format("/%s/%s/%s/%s",element(local.splittedPath,6),element(local.splittedPath,7),element(local.splittedPath,8),element(local.splittedPath,9))
}

output "A-original" {
     value = local.originalpath
}

output "B-calculated" {
     value = local.serviceUrlCalculatedPath
}

```

output:

```
Changes to Outputs:
  + A-original   = "martin://prod-24.westeurope.logic.azure.com:443/workflows/f95951326b5f4906828a5b8fac73cb3f/triggers/manual/paths/invoke?api-version=2017-07-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=dlOJV8tVC8f152odR6VZwt1qU5_uXxt4wCU02XztoEg"
  + B-calculated = "/manual/paths/invoke?api-version=2017-07-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=dlOJV8tVC8f152odR6VZwt1qU5_uXxt4wCU02XztoEg/**martin**:"`
```

**Comment by apparentlymart** [comment] 2021-03-31 16:24
Hi @MartinHoge,

What you've described here seems like the intended behavior of [the `element` function](https://www.terraform.io/docs/language/functions/element.html): if you choose an index greater than the largest "real" index in the list then it will use the modulo operation to "wrap" to the first element of the list. Modules commonly use this technique as a way to distribute objects across a smaller set of other objects, such as making a small list of AWS subnets and then assigning a larger number of EC2 instances to them:

```hcl
locals {
  subnet_ids = ["subnet-1", "subnet-2", "subnet-3"]
}

resource "aws_instance" "example" {
  count = 12

  # ...
  subnet_id = element(local.subnet_ids[count.index])
}
```

If you don't want this automatic "wrapping" behavior then it'd be better to use a plain index operation, like this:

```
local.splitted_path[count.index]
```

That will return an error if your list doesn't have enough elements, rather than wrapping around.

You mentioned in your writeup that you wanted it to return `null` rather than an error. Based on the example you shared I don't think that will actually help with what you are trying to do, because it's not possible to interpolate a `null` value into a string, but for completeness I'll also show an example of using [the `try` function](https://www.terraform.io/docs/language/functions/try.html) to concisely provide a fallback value if the index fails:

```
try(local.splitted_path[count.index], null)
```

or, if you want an empty string instead:

```
try(local.splitted_path[count.index], "")
```

Since the behavior you described seems to match what's documented and intended, I'm going to close this. If you have some follow-up questions about the explanations and examples I included above, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where I'd be happy to discuss this more. Thanks!

**Closed by apparentlymart** 2021-03-31 16:24 UTC
Labels: bug, new
