### ISSUE TITLE
Terraform tries to edit DHCP option set instead of creating new

### ISSUE THREAD

**Issue by sladd0175** [hashicorp/terraform#13718] opened 2017-04-17 19:34 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.9.3

### Affected Resource(s)
aws_vpc_dhcp_options.dhcp_opts -- if we taint this resource and then run the apply, it works as expected.

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Too much personally identifiable information in debug output.  Here is the error section:

Error applying plan:

1 error(s) occurred:

* module.vpc_name.aws_vpc_dhcp_options.dhcp_opts: aws_vpc_dhcp_options.dhcp_opts: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.9.3
    Resource ID: aws_vpc_dhcp_options.dhcp_opts
    Mismatch reason: diff RequiresNew; old: false, new: true
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"domain_name_servers.#":*terraform.ResourceAttrDiff{Old:"3", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"domain_name_servers.2":*terraform.ResourceAttrDiff{Old:"10.137.64.2", New:"10.137.64.2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_name_servers.#":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_name_servers.0":*terraform.ResourceAttrDiff{Old:"10.137.64.166", New:"10.137.64.245", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name_servers.1":*terraform.ResourceAttrDiff{Old:"10.137.66.65", New:"10.137.66.51", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name":*terraform.ResourceAttrDiff{Old:"ove.local", New:"ove.local", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:true, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior
delete existing dhcp option set and then create new

### Actual Behavior
It tries to edit the existing dhcp option set and that is not editable in AWS

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
VPC within AWS

**Comment by jbardin** [comment] 2017-04-20 21:57
Hi @sladd0175,

Thanks for filing an issue. Is it possible for you to share the configuration used and the steps to replicate this?

**Comment by jbardin** [comment] 2017-04-20 22:27
Ah, I found a way to reproduce this from the error message.

The problem is that when a TypeList which is ForceNew is determined to be "computed" during plan, it's not marked as RequiresNew. During apply when the values are known to have changed Requires new will be set.

**Comment by jbardin** [comment] 2017-04-21 19:58
@sladd0175,

After you successfully updated the `aws_vpc_dhcp_options`, does running `terraform plan` still return with "No changes"?

I've narrowed down the issue, but I haven't been able to reproduce it yet with a working configuration. Can you share at least the portion of the configuration for `aws_vpc_dhcp_options.dhcp_opts`? I'd like to see how the list is computed.

Thanks

**Closed** 2017-04-21 22:02 UTC
Labels: bug, core
