### ISSUE TITLE
Terraform 1.1.0 crashed when Plan

### ISSUE THREAD

**Issue by clehir35** [hashicorp/terraform#31014] opened 2022-05-06 13:20 UTC
Hi there,

I was trying to replace local resource files with matching modules builds by my company. An then this crash while refreshing state.
Commands are launched in ADO pipeline. 
I try with reverting changes, but i still have this error.

### Terraform Version

```
1.1.0
```

### Debug Output
```
 !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Terraform crashed! This is always indicative of a bug within Terraform.
 Please report the crash with Terraform[1] so that we can fix this.
 
 When reporting bugs, please include your terraform version, the stack trace
 shown below, and any additional information which may help replicate the issue.
 
 [1]: https://github.com/hashicorp/terraform/issues

 !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 4827 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x221d240, 0x3ed5b10})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc003569270, {{}, 0x4d, {0xc0005b5a58, 0x13}, {0xc000b00e50, 0x10}}, {0xc00033ec80, 0x30, 0x4})
/home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x4e, {0xc000aef1e0, 0x0, 0xc000600000}, {{}, 0x4d, {0xc0005b5a58, 0x13}, {0xc000b00e50, 0x10}}, ...)
/home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc000dd2ea0, {0xc000aef1e0, 0x1, 0x1}, {{}, 0x4d, {0xc0005b5a58, 0x13}, {0xc000b00e50, 0x10}}, ...)
/home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc001069320, {{}, {0xc000aef1e0, 0x1, 0x1}, {{}, 0x4d, {0xc0005b5a58, 0x13}, {0xc000b00e50, ...}}})
/home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc0011d9910, {0x2aecc00, 0xc001e04ee0})
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc0011d9910, {0x2aecc00, 0xc001e04ee0})
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc001e04ee0}, 0x90)
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0010b6e00, {0x2aecc00, 0xc001e04ee0}, {0x7fc7d56df9b0, 0xc0011d9910})
/home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc0011d9910})
/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0006928a0, {0x2553ec0, 0xc0011d9910}, 0xc0032318c0)
/home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
/home/circleci/project/project/internal/dag/walk.go:304 +0xf85
 ##[error]Error: Terraform Plan failed with exit code: 11
```

### Expected Behavior

Refreshing state and get normal tf plan

### Actual Behavior

CRASH in PLAN STEP

### Steps to Reproduce

```
1. `terraform init`
2. `terraform plan`
```

Feel free to ask any question if needed

**Comment by alisdair** [comment] 2022-05-06 13:59
This looks like an issue which was fixed in a 1.1 patch release. Please upgrade to 1.1.9 to receive the fix.

I'm closing this issue for now as I believe it has already been fixed, but if you can reproduce the problem with 1.1.9 please respond with details about your configuration and we'll look into it.

**Closed by alisdair** 2022-05-06 13:59 UTC
Labels: bug, new
