### ISSUE TITLE
.12 boolean dynamic typing bug

### ISSUE THREAD

**Issue by wburn-sierra-cedar** [hashicorp/terraform#24465] opened 2020-03-26 00:26 UTC
### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.51.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
variable "foo"
type = bool
default = true

count = var.foo == 1 ? 1 : 0
count = var.foo == true ? 1 : 0

```

### Expected Behavior

Both counts should result in 1
### Actual Behavior

count = var.foo == 1 ? 1 : 0  (results in 0)

count = var.foo == true ? 1 : 0 (results in 1)

**Comment by jbardin** [comment] 2020-03-26 14:11
Hi @wburn-sierra-cedar 

Thanks for filing the issue.  Removing the concept of "truthiness" was a specific design decision made when we updated the configuration language. 

Because `var.foo` is a `bool` it cannot be equal to a `number`. The same is true when comparing strings, as `var.foo == "true"` would also be `false`. It's generally an error to doing a binary comparison on a boolean, and the value should be used directly, either via `var.foo ?` or `!var.foo ?` depending on the desired logic. 

Closing since this is working as designed.

Thanks!

**Closed by jbardin** 2020-03-26 14:11 UTC
