### ISSUE TITLE
Error asking for user input: 1 error occurred: * Cycle:

### ISSUE THREAD

**Issue by cmardonespino** [hashicorp/terraform#22980] opened 2019-10-02 19:09 UTC
### Terraform Version

```
Terraform v0.11.14
```

### Terraform Configuration Files

```hcl
resource "aws_kms_key" "a" {
  description         = "KMS test"
  key_usage           = "ENCRYPT_DECRYPT"
  enable_key_rotation = true

  deletion_window_in_days = 10

  policy = <<EOF
  {
    "Version": "2012-10-17",
    "Id": "key-default-1",
    "Statement": [
        {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::AWS_ACCOUNT_NUMBER:root"
            },
            "Action": "kms:*",
            "Resource": "*"
        },
        {
          "Sid": "Allow Amazon SNS to use this key",
          "Effect": "Allow",
          "Principal": {
              "Service": [
                "sns.amazonaws.com"
              ]
          },
          "Action": [
              "kms:Decrypt",
              "kms:GenerateDataKey*"
          ],
          "Resource": "${aws_kms_alias.a.target_key_arn}",
          "Condition": {
                "ArnEquals": {
                    "aws:SourceArn": "arn:aws:sns:us-west-2:${var.environment_account[terraform.workspace]}:connect-events-connect-test-carlos"
                }
            }
        }
    ]
  }
EOF

  tags = "${local.common_tags}"
}

resource "aws_kms_alias" "a" {
  name          = "alias/my-kms-test"
  target_key_id = "${aws_kms_key.a.key_id}"
}
```

### Debug Output

`Error: Error asking for user input: 1 error occurred: * Cycle: aws_kms_key.a, aws_kms_alias.a`

### Expected Behavior

Fails to update a KMS policy doing reference to the KMS target ARN that are defined as resource in the same file.

### Actual Behavior

Both resources (`aws_kms_key.a` & `aws_kms_alias.a`) they depend on themselves.

### Steps to Reproduce

`terraform apply`

### References

#20384

**Comment by teamterraform** [comment] 2019-10-02 23:01
Hi @cmardonespino!

The error message seems correct in this case: there _is_ a dependency cycle between these two resources because the `aws_kms_alias` contains a reference to the `aws_kms_key` and the `aws_kms_key` contains a reference to the `aws_kms_alias`.

In order to avoid this error, you'll need to find a way to express this configuration such that the `aws_kms_key` configuration does not refer to the `aws_kms_alias` resource. The Terraform Core team isn't familiar enough with KMS to make a specific suggestion here, but if you're not sure we'd recommend asking about it in [the community forum for the AWS provider](https://discuss.hashicorp.com/c/terraform-providers/tf-aws), whether other folks with AWS-specific expertise may be able to offer alternative approaches.

Because Terraform is working as intended in this case, we're going to close this issue out. Sorry we're not able to offer a specific alternative configuration in this case.

**Closed by teamterraform** 2019-10-02 23:01 UTC
