### ISSUE TITLE
Allow wildcards in target

### ISSUE THREAD

**Issue by garrettheel** [hashicorp/terraform#2444] opened 2015-06-23 17:40 UTC
It would be nice to be able to use wildcards in the target command for generating plans and applying changes.

My use case is that I want to roll out changes to my infrastructure in stages based on a naming convention.

For example:

``` bash
terraform plan -target="test-*" > test.plan
```

The current output of this is:

```
Errors:
  * Problem parsing address: "test-*"
```

I do realise that this is possible using sub-directories and generating plans for each, but this solution proves more flexible.

Thanks!

**Comment by vbichov** [comment] 2015-09-06 10:22
The ability the address an entire resource would be greatly appreciated, for example:
`terraform plan -destroy -target=aws_instance`
(which you can't do today - which is kind of strange...)

**Comment by HenryTheHamster** [comment] 2016-02-19 23:52
+1 to this request. Alternatively, an exclude tag for destruction would also be useful. Our use case is wanting to scorch the earth of all our infrastructure except for certain elements such as ELB's to avoid DNS delays.

**Comment by Beldur** [comment] 2016-03-02 12:34
Very useful feature.

**Comment by lazartravica** [comment] 2016-04-08 14:24
+1

**Comment by hazim1093** [comment] 2016-09-22 11:51
It would be nice to add wild cards like these too 
`-target resource.aws_security_group_rule.*`

**Comment by elfenars** [comment] 2016-10-25 09:30
+1

**Comment by catsby** [comment] 2016-11-08 22:29
Hey all – thanks for the suggestion; I'm going to close this a duplicate of https://github.com/hashicorp/terraform/issues/2182

**Closed by catsby** 2016-11-08 22:29 UTC
Labels: core, enhancement
