### ISSUE TITLE
Azure provider unable to delete multiple resources

### ISSUE THREAD

**Issue by andreysabitov** [hashicorp/terraform#2416] opened 2015-06-22 08:37 UTC
I successfully create Azure virtual machine using such configuration file:

```
provider "azure" {
  settings_file = "azure.publishsettings"
}

resource "azure_storage_service" "mi-storage" {
  name = "test2321torage1"
  location = "West US"
  account_type = "Standard_LRS"
}

resource "azure_virtual_network" "mi-vnet" {
  name = "mynet"
  address_space = [ "10.0.0.0/8" ]
  subnet {
    name = "mysubnet"
    address_prefix = "10.0.0.0/24"
  }
  location = "West US"
}

resource "azure_instance" "mi-control" {
  name = "mi-node01"
  image = "RightImage-CentOS-7.0-x64-v14.2.1"
  size = "Small"
  subnet = "mysubnet"
  virtual_network = "mynet"
  storage_service_name = "test2321torage1"

  location = "West US"
  username = "centos"
  password = "P@ssw0rd"

}
```

When I'm trying to delete those resources with `terraform destroy` I get:

```
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

azure_instance.mi-control: Refreshing state... (ID: mi-node01)
azure_virtual_network.mi-vnet: Refreshing state... (ID: mynet)
azure_storage_service.mi-storage: Refreshing state... (ID: test2321torage1)
azure_instance.mi-control: Destroying...
azure_storage_service.mi-storage: Destroying...
azure_virtual_network.mi-vnet: Destroying...
azure_storage_service.mi-storage: Error: 1 error(s) occurred:

* Error whilst issuing deletion of storage service off Azure: Error response from Azure. Code: BadRequest, Message: Storage account test2321torage1 has some active image(s) and/or disk(s), e.g. mi-node01-mi-node01-0-201506220756050483. Ensure these image(s) and/or disk(s) are removed before deleting this storage account.
azure_instance.mi-control: Destruction complete
azure_virtual_network.mi-vnet: Error: 1 error(s) occurred:

* Error waiting for Virtual Network mynet to be deleted: Error response from Azure. Code: BadRequest, Message: Cannot delete or modify virtual network while in use 'mynet'.
Error applying plan:

2 error(s) occurred:

* Error whilst issuing deletion of storage service off Azure: Error response from Azure. Code: BadRequest, Message: Storage account test2321torage1 has some active image(s) and/or disk(s), e.g. mi-node01-mi-node01-0-201506220756050483. Ensure these image(s) and/or disk(s) are removed before deleting this storage account.
* Error waiting for Virtual Network mynet to be deleted: Error response from Azure. Code: BadRequest, Message: Cannot delete or modify virtual network while in use 'mynet'.
```

It seems that terraform is trying to destroy storage and virtual network resources before virtual machines which use them.

**Comment by keymon** [comment] 2015-08-24 10:24
+1

**Comment by aznashwan** [comment] 2015-10-29 23:44
@keymon @andreysabitov: thanks a bunch for the report!

@keymon: you are indeed correct; Terraform keeps an internal record of all resources and the dependency relationships between them and operates on the resources as concurrently as possible.
This is not a bug; but one of Terraform's main features.
Terraform only sequentially deploys/updates/deletes resources which depend on each-other, which is something the user must indicate; either by adding the `*depends_on*` field and listing the dependencies, or by referencing depended resources with `${type.name.field}` syntax in the definition of the depending one.

@andreysabitov: the most straightforward approach here would be to set `virtual_network = "${azure_virtual_network.mi-vnet.name}"` and `storage_service_name = "${azure_storage_service.mi-storage.name}"` in the definition of the instance.

**Comment by xied75** [comment] 2015-11-27 11:38
Looks like not really a bug, but the intended feature, suggest close the issue.

**Closed** 2016-11-08 22:27 UTC
Labels: bug, provider/azure
