### ISSUE TITLE
Terraform Destroy crashes on darwin_arm64 

### ISSUE THREAD

**Issue by sreenathprem** [hashicorp/terraform#32867] opened 2023-03-16 09:55 UTC
### Terraform Version

```shell
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.58.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = var.region
}

resource "aws_instance" "ubuntu" {
  ami           = "ami-0d221cb540e0015f4"
  instance_type = var.instance_type

  tags = {
    Name = var.instance_name
    Owner = var.email
  }
}

```

### Debug Output

```
└──➜ tf destroy                                                                                                 
2023-03-16T10:51:52.786+0100 [INFO]  Terraform version: 1.4.0
2023-03-16T10:51:52.786+0100 [DEBUG] using github.com/hashicorp/go-tfe v1.18.0
2023-03-16T10:51:52.786+0100 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.0
2023-03-16T10:51:52.786+0100 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-03-16T10:51:52.786+0100 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-03-16T10:51:52.786+0100 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-03-16T10:51:52.786+0100 [INFO]  Go runtime version: go1.19.6
2023-03-16T10:51:52.786+0100 [INFO]  CLI args: []string{"terraform", "destroy"}
2023-03-16T10:51:52.786+0100 [TRACE] Stdout is a terminal of width 141
2023-03-16T10:51:52.786+0100 [TRACE] Stderr is a terminal of width 141
2023-03-16T10:51:52.786+0100 [TRACE] Stdin is a terminal
2023-03-16T10:51:52.786+0100 [DEBUG] Attempting to open CLI config file: /Users/sreenath.premnadh/.terraformrc
2023-03-16T10:51:52.786+0100 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-03-16T10:51:52.786+0100 [INFO]  Loading CLI configuration from /Users/sreenath.premnadh/.terraform.d/credentials.tfrc.json
2023-03-16T10:51:52.787+0100 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-03-16T10:51:52.787+0100 [DEBUG] ignoring non-existing provider search directory /Users/sreenath.premnadh/.terraform.d/plugins
2023-03-16T10:51:52.787+0100 [DEBUG] ignoring non-existing provider search directory /Users/sreenath.premnadh/Library/Application Support/io.terraform/plugins
2023-03-16T10:51:52.787+0100 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2023-03-16T10:51:52.787+0100 [INFO]  CLI command args: []string{"destroy"}
2023-03-16T10:51:52.788+0100 [TRACE] Meta.Backend: built configuration for "cloud" backend with hash value 1940033333
2023-03-16T10:51:52.788+0100 [TRACE] Preserving existing state lineage "eef900f8-a858-1a7a-7e60-3fa636c65360"
2023-03-16T10:51:52.788+0100 [TRACE] Preserving existing state lineage "eef900f8-a858-1a7a-7e60-3fa636c65360"
2023-03-16T10:51:52.788+0100 [TRACE] Meta.Backend: working directory was previously initialized for "cloud" backend
2023-03-16T10:51:52.788+0100 [TRACE] Meta.Backend: using already-initialized, unchanged "cloud" backend configuration
2023-03-16T10:51:52.788+0100 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2023-03-16T10:51:52.788+0100 [TRACE] HTTP client GET request to https://app.terraform.io/.well-known/terraform.json
2023-03-16T10:51:53.290+0100 [DEBUG] Service discovery for app.terraform.io aliased as localterraform.com
2023-03-16T10:51:53.938+0100 [TRACE] Meta.Backend: instantiated backend of type *cloud.Cloud
2023-03-16T10:51:53.938+0100 [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2023-03-16T10:51:53.939+0100 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.58.0 for darwin_arm64 at .terraform/providers/registry.terraform.io/hashicorp/aws/4.58.0/darwin_arm64
2023-03-16T10:51:53.939+0100 [TRACE] providercache.fillMetaCache: including .terraform/providers/registry.terraform.io/hashicorp/aws/4.58.0/darwin_arm64 as a candidate package for registry.terraform.io/hashicorp/aws 4.58.0
2023-03-16T10:51:54.150+0100 [DEBUG] checking for provisioner in "."
2023-03-16T10:51:54.150+0100 [DEBUG] checking for provisioner in "/opt/homebrew/bin"
2023-03-16T10:51:54.150+0100 [TRACE] Meta.Backend: backend *cloud.Cloud supports operations
2023-03-16T10:51:54.330+0100 [INFO]  cloud: starting Apply operation
Running apply in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

To view this run in a browser, visit:
https://app.terraform.io/app/sreeprem-org/learn-terraform-cloud/runs/run-vC4SQmNzf3xd4woF

Waiting for the plan to start...

Terraform v1.4.0
on linux_amd64
Initializing plugins and modules...
aws_instance.ubuntu: Refreshing state... [id=i-055645b1b7ab752b7]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 104 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
        /home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000452320, {0x2ccf8f8, 0xc000441b40}, {0x2ccf8f8, 0xc000441b80}, 0xc000b4e5a0, 0xc000441b00)
        /home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
Operation failed: failed running terraform plan (exit 11)
```

### Expected Behavior

Destroy should have went through fine.

### Actual Behavior

Destroy crashed with a stacktrace as described above

### Steps to Reproduce

Firstly, the earlier apply for me errored in the Terraform cloud. However the instances were nevertheless created. That is the EC2 instances were created, but the run in TF Cloud errored.

Subsequently when I run terraform destroy from CLI, I get this error.

**Comment by jbardin** [comment] 2023-03-16 12:17
Duplicate of #32810

**Closed by jbardin** 2023-03-16 12:17 UTC
Labels: bug, new
