### ISSUE TITLE
Same plan file can be executed multiple times on fresh state

### ISSUE THREAD

**Issue by gilesvessey** [hashicorp/terraform#27721] opened 2021-02-09 16:06 UTC
### Terraform Version

```
Terraform v0.14.6
```

### Terraform Configuration Files

```terraform
terraform {
  backend "local" {}
}

terraform {
  required_providers {
    aws = {
      version = "~> 3.00"
    }
  }
}

resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/24"
}
```

### Expected Behavior

terraform should have recognized that the plan file was stale, and prevented execution of the stale plan.

### Actual Behavior

The same plan was applied again, creating new resources and evicting the existing resources from state (original resources are no longer terraform managed and must be destroyed manually)

### Steps to Reproduce

```
> terraform init
> terraform plan -out=plan.bin
> terraform apply "plan.bin"
> terraform apply "plan.bin"
```

### Additional Context

This only happens when the plan was created prior to any existing state. If you were to have some prior state, such as by doing...
```
> terraform apply --auto-approve
> (make some change to your configuration)
> terraform plan -out=plan.bin
> terraform apply "plan.bin"
> terraform apply "plan.bin" # the stale plan is blocked successfully
```

**Comment by jbardin** [comment] 2021-02-09 16:09
Duplicate of #24078

Thanks!

**Closed by jbardin** 2021-02-09 16:09 UTC
Labels: bug, new
