### ISSUE TITLE
Error on terraform apply

### ISSUE THREAD

**Issue by brucemartins** [hashicorp/terraform#8910] opened 2016-09-18 02:36 UTC
I intermittantly receive the below, if I run destory, plan, apply again it typically works, but the below happens periodically 

Error applying plan:

1 error(s) occurred:
- openstack_networking_port_v2.port_1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

```
Terraform Version: 0.7.3
Resource ID: openstack_networking_port_v2.port_1
Mismatch reason: extra attributes: fixed_ip.0.subnet_id
Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"admin_state_up":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "allowed_address_pairs.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "fixed_ip.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"port_1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "security_group_ids.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "device_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "fixed_ip.0.ip_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "device_owner":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tenant_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "network_id":*terraform.ResourceAttrDiff{Old:"", New:"818236ab-14c3-4735-a967-77d3b38bd31e", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "mac_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"name":*terraform.ResourceAttrDiff{Old:"", New:"port_1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "device_owner":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "security_group_ids.230792537":*terraform.ResourceAttrDiff{Old:"", New:"79e54f6d-f5c6-4c2c-b219-967da54da581", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "admin_state_up":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "fixed_ip.0.subnet_id":*terraform.ResourceAttrDiff{Old:"", New:"82a5777d-67aa-41a9-8a8b-f62798fa3f05", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "fixed_ip.0.ip_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "security_group_ids.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "device_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "network_id":*terraform.ResourceAttrDiff{Old:"", New:"818236ab-14c3-4735-a967-77d3b38bd31e", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tenant_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "allowed_address_pairs.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "mac_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "fixed_ip.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
```

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jen20** [comment] 2016-09-20 09:07
Hi @brucemartins! Thanks for opening an issue. Can you also include the configuration blocks relating to the `port_1` resource and it's dependencies to aid debugging? Thanks!

**Comment by brucemartins** [comment] 2016-09-21 17:46
resource "null_resource" "public_subnet_id" {
    provisioner "local-exec" {
        command = "neutron --os-auth-url ${var.auth_url} --os-tenant-name ${var.tenant_name} --os-password ${var.password} --os-username ${var.user_name} net-show ${var.openstack_external_network_public} |grep subnets |cut -d '|' -f3 |sed 's/[[:space:]]//g' |tr -d '\n' > files/temp_pub_sub_id"
    }
}

resource "openstack_networking_port_v2" "port_1" {
  depends_on = ["null_resource.sleepy","null_resource.public_subnet_id"]
  name = "port_1"
  network_id = "${var.openstack_external_network_public}"
  admin_state_up = "true"
  fixed_ip = [{subnet_id = "${file("files/temp_pub_sub_id")}"}]
  security_group_ids = ["${var.ms-security-group-id}"]
}

**Comment by jsravn** [comment] 2016-09-30 09:47
I'm seeing this as well on a null-resource with a count. terraform 0.7.4. It seems to fix itself - when I rerun, the error goes away.

```
Error applying plan:

19 error(s) occurred:

* null_resource.kubelet_volume_enable_auto_io.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.4
    Resource ID: null_resource.kubelet_volume_enable_auto_io.0
    Mismatch reason: diff RequiresNew; old: true, new: false
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"triggers.%":*te
rraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tri
ggers.volume_count":*terraform.ResourceAttrDiff{Old:"19", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive
:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{}, Destroy:fals
e, DestroyTainted:false}
```

Config block:
```
resource "null_resource" "kubelet_volume_enable_auto_io" {
  count = "${var.instance_count}"

  provisioner "local-exec" {
    command = <<EOF
      AWS_ACCESS_KEY_ID=${var.access_key} AWS_SECRET_ACCESS_KEY=${var.secret_key} AWS_DEFAULT_REGION=${var.region} \
      aws ec2 modify-volume-attribute --volume-id ${element(aws_ebs_volume.kubelet_volume.*.id, count.index)} \
        --auto-enable-io
    EOF
  }
}
```

**Comment by mitchellh** [comment] 2016-11-17 00:52
Hello! This should be fixed in later versions of Terraform. 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 00:52 UTC
Labels: bug, provider/openstack
