### ISSUE TITLE
Can't set default value for object in list(object)

### ISSUE THREAD

**Issue by PePoDev** [hashicorp/terraform#25655] opened 2020-07-23 09:24 UTC
### Current Terraform Version
```
Terraform v0.12.28
```

### Terraform Configuration Files
```terraform
module "vpc" {
  source = "../../modules/vpc"

  name        = "example-vpc"
  subnets = [
    {
      name          = "example-subnetwork-1"
      ip_cidr_range = "10.10.0.0/24"
    }
  ]
}

variable "subnets" {
  type = list(object({
    name          = string
    ip_cidr_range = string
    secondary_ip_range = list(object({
      range_name    = string
      ip_cidr_range = string
    }))
    private_ip_google_access = string
    log_config = object({
      aggregation_interval = string
      flow_sampling        = string
      meta_data            = string
    })
  }))
  default = []
}
```

### Expected Behavior
Can run with null value on parameter that not specify

### Actual Behavior
```
Error: Invalid value for module argument

  on main.tf line 14, in module "vpc":
  14:   subnets = [
  15:     {
  16:       name          = "example-subnetwork-1"
  17:       ip_cidr_range = "10.10.0.0/24"
  18:     }
  23:   ]

The given value is not suitable for child module variable "subnets" defined at
../../modules/vpc/variables.tf:42,1-19: element 0: attributes "log_config",
"private_ip_google_access", and "secondary_ip_range" are required.
```

### Additional Context
```terraform
subnets = [
    {
      name          = "example-subnetwork-1"
      ip_cidr_range = "10.10.0.0/24"
      secondary_ip_range       = null
      private_ip_google_access = null
      log_config               = null
    }
  ]
```
This is not error, But we did't specific null on all value that we don't want to change.

Can set missing parameter to Null and self handle on module ?

**Comment by alisdair** [comment] 2020-07-23 17:30
Thanks for reporting this use case! This looks like a duplicate of #19898, so I'm closing this issue in favour of that one. Please add a 👍 reaction on the other ticket or contribute to the discussion over there.

**Closed by alisdair** 2020-07-23 17:30 UTC
