### ISSUE TITLE
Ambiguous error while creating asg with launch config

### ISSUE THREAD

**Issue by arshdeeptinna** [hashicorp/terraform#18262] opened 2018-06-15 13:36 UTC
I have following as part of config in a module to setup an asg. I noticed weird behavior where when i did terraform plan, terraform complained about not being able to find resource names `aws_launch_configuration.this`.  I had already used the module before so this error was unexpected. 

To test a theory I removed launch_configuration variable from aws_autoscaling_group resource and re-ran terraform plan. Plan failed again but this time telling me the real problem which was that my user_data length was  greater than 16384.
### Terraform Version

```
0.11.5
```

### Terraform Configuration Files

```hcl
resource "aws_launch_configuration" "this" {
  name_prefix = "${var.cluster}-${var.environment}"
  image_id = "${var.ami_id}"
  instance_type = "${var.instance_type}"
  security_groups = ["${concat(list(aws_security_group.this.id), var.additional_security_groups)}"]
  associate_public_ip_address = false
  iam_instance_profile = "${aws_iam_instance_profile.kafka.id}"
  user_data = "${var.user_data}"
  key_name = "${var.key_pair}"
  ebs_optimized = true

}
resource "aws_autoscaling_group" "this" {
  name = "${aws_launch_configuration.kafka.name}-asg"
  max_size = "${var.max_instance_count}"
  min_size = "${var.min_instance_count}"
  desired_capacity = "${var.desired_instance_count}"
  force_delete = true
  launch_configuration = "${aws_launch_configuration.this.id}"
  tags = "${var.tags}"


 }



```

### Expected Behavior

If it fails planning launch config resource, it should through a relevant error like 
`Should module.asg.aws_launch_configuration.this: expected length of user_data to be in the range (1 - 16384), got #! /bin/bash`
### Actual Behavior

`resource 'aws_autoscaling_group.this' config: unknown resource 'aws_launch_configuration.this' referenced in variable aws_launch_configuration.this.id`
### Steps to Reproduce

`Use a simple module to create a launch config and asg`
`Create a userdata script with length greater than 16384`
`terraform init`
`terraform plan`

**Comment by bflad** [comment] 2018-06-15 14:40
Potentially similar to https://github.com/hashicorp/terraform/issues/18129?

**Comment by apparentlymart** [comment] 2018-10-31 19:21
Hi @arshdeeptinna! Sorry for the slow response here.

I believe @bflad is correct that this is the same root cause as #18129. I've added that to the v0.12.0 milestone to be addressed before we get to final, and I'm going to close this one just to consolidate the discussion over there.

Thanks for reporting this!

**Closed by apparentlymart** 2018-10-31 19:21 UTC
Labels: bug, config
