### ISSUE TITLE
Can we copy data from server/VM to local machine(created via tf), like reverse providers in terraform

### ISSUE THREAD

**Issue by iamraj007** [hashicorp/terraform#33314] opened 2023-06-05 14:32 UTC
### Terraform Version

```shell
1.4.6 Terraform Cloud
```

### Use Cases

I need to copy Kubernetes cert etc to local as a part of my automation work, else it is too much manual work to make thing work.

So like i do get AKS credentials
Download cluster credentials:
az aks get-credentials --resource-group --name ....

### Attempted Solutions

local-exec will not work and don't see any other way, that is why i am here.

### References

#3379

**Comment by crw** [comment] 2023-06-05 21:56
Hello @iamraj007, I would suggest you ask [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

As this appears to be a duplicate of #3379 (the referenced issue), I am going to close this issue. Please do put an upvote on the original issue. Thanks!

**Closed by crw** 2023-06-05 21:56 UTC
Labels: enhancement, new
