### ISSUE TITLE
Adding Remote Objects to State

### ISSUE THREAD

**Issue by sirantd** [hashicorp/terraform#30557] opened 2022-02-18 16:53 UTC
Hi there,

Since terraform 0.15.4 we have a new behaviour that adds missed objects to the state with `terraform apply`.
I know the reason why it was added but seems it broke more than fixes. It's the "killing feature" of IaC when changes made manually will be overridden by the terraform during the next run. But it's not the behaviour we have now.

### Terraform Version
0.15.4+

### Expected Behavior
When I do `terraform apply` for the resources described in the code I'm expecting that all the changes made manually will be aligned to the state described in the source code.

### Actual Behavior
It shows that actual infrastructure has a drift with the state and adding changes into the state instead of removing them.

### Steps to Reproduce
1. Create AWS security group with terraform
2. Add one more rule to the SG manually
3. Run `terraform plan && terraform apply` - it will show the changes to the current state and will add them into the state.

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_security_group.this_name_prefix[0] has changed
  ~ resource "aws_security_group" "this_name_prefix" {
        id                     = "sg-0cac7527a31bafe0d"
      ~ ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "udp"
              + security_groups  = []
              + self             = false
              + to_port          = 65535
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 22
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
        ]
        name                   = "test-sg-20220218154347848600000001"
        tags                   = {
            "Name"        = "test-sg"
            "created"     = "terraform"
            "environment" = "main"
            "region"      = "us-west-2"
        }
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### References
https://support.hashicorp.com/hc/en-us/articles/4405950960147-New-Feature-Objects-have-changed-outside-of-Terraform-

**Comment by alisdair** [comment] 2022-02-25 15:06
Thanks for reporting this.

What you're seeing is an unfortunate combination of the new UI for detected changes made outside of Terraform, and a [longstanding bug in the AWS provider](https://github.com/hashicorp/terraform-provider-aws/issues/4399). Terraform has always refreshed local state from the remote system, but before the new UI output was added, this was done silently.

I was able to reproduce the behaviour you reported as follows:

1. Create an `aws_security_group` using Terraform with the following configuration:

    ```terraform
    provider "aws" {
      region = "us-east-1"
    }

    resource "aws_security_group" "sg" {
      name        = "sg"
      description = "description"
      vpc_id      = aws_vpc.main.id
    }

    resource "aws_vpc" "main" {
      cidr_block = "10.0.0.0/16"
    }
    ```
2. Use the AWS Console to add an ingress rule to this group
3. Run `terraform plan`

The output of `terraform plan` showed that Terraform detected the ingress rule added using the AWS Console, and is prepared to update the local state to reflect that. Terraform did not propose changes to undo this rule because the local configuration did not specify that there should be no `ingress` rules for this security group.

If we specify `ingress = []`, or add any ingress rules using `ingress { … }` blocks, Terraform correctly plans to update the remote system to match the configuration.

The need to specify an empty list of ingress rules to address this is noted in the linked AWS bug. As a result, there isn't a bug in Terraform here, so I'm going to close this out.

**Closed by alisdair** 2022-02-25 15:06 UTC
Labels: bug, new
