### ISSUE TITLE
Provider aliases not working for non-hashicorp providers with tf 015.0

### ISSUE THREAD

**Issue by woz5999** [hashicorp/terraform#28452] opened 2021-04-19 22:56 UTC
### Terraform Version

```
Terraform v0.15.0
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    auth0 = {
      source  = "alexkappa/auth0"
      version = ">=0.20.0"

      configuration_aliases = [
        auth0.a,
      ]
    }
  }
}

provider "auth0" {
  alias = "a"

  client_id     = "123"
  client_secret = "123"
  domain        = "123"
}

module "m" {
  source = "./module"

  providers = {
    auth0.a = auth0.a
  }
}

# contents of ./module/main.tf:
terraform {
  required_providers {

    auth0 = {
      source = "alexkappa/auth0"
      configuration_aliases = [
        auth0.a,
      ]
    }
  }
}

```

### Debug Output
```
TF_LOG=trace tf init
2021-04-19T15:47:27.787-0700 [DEBUG] Adding temp file log sink: /var/folders/ny/xc92y7xs1szbdr9skq_s7b4h0000gq/T/terraform-log093638068
2021-04-19T15:47:27.788-0700 [INFO]  Terraform version: 0.15.0
2021-04-19T15:47:27.788-0700 [INFO]  Go runtime version: go1.16.2
2021-04-19T15:47:27.788-0700 [INFO]  CLI args: []string{"/usr/local/bin/terraform", "init"}
2021-04-19T15:47:27.788-0700 [TRACE] Stdout is a terminal of width 211
2021-04-19T15:47:27.788-0700 [TRACE] Stderr is a terminal of width 211
2021-04-19T15:47:27.788-0700 [TRACE] Stdin is a terminal
2021-04-19T15:47:27.789-0700 [DEBUG] Attempting to open CLI config file: /Users/jeffwozniak/.terraformrc
2021-04-19T15:47:27.789-0700 [INFO]  Loading CLI configuration from /Users/jeffwozniak/.terraformrc
2021-04-19T15:47:27.791-0700 [DEBUG] Explicit provider installation configuration is set
2021-04-19T15:47:27.791-0700 [TRACE] Selected provider installation method cliconfig.ProviderInstallationDirect with includes [] and excludes []
2021-04-19T15:47:27.793-0700 [INFO]  CLI command args: []string{"init"}
Initializing modules...
2021-04-19T15:47:27.808-0700 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2021-04-19T15:47:27.813-0700 [DEBUG] Module installer: begin m
2021-04-19T15:47:27.814-0700 [TRACE] ModuleInstaller: Module installer: m <nil> already installed in module
2021-04-19T15:47:27.814-0700 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid type for provider module.m.provider["registry.terraform.io/alexkappa/auth0"].overlook
│ 
│   on main.tf line 26, in module "m":
│   26:     auth0.overlook = auth0.overlook
│ 
│ Cannot use configuration from provider["registry.terraform.io/hashicorp/auth0"].overlook for module.m.provider["registry.terraform.io/alexkappa/auth0"].overlook. The given provider configuration is for a
│ different provider type.
╵
```

### Expected Behavior
The project should correctly initialize

### Actual Behavior
The initialization throws an error for an invalid provider type.

### Steps to Reproduce
1. `terraform init`

### Additional Context

The behavior occurs for any non-hashicorp providers I'm using, not just the one used in the example code.

### References

- #27739

**Comment by jbardin** [comment] 2021-04-20 12:53
Duplicate of #28407, closed via #28414

**Closed by jbardin** 2021-04-20 12:53 UTC
Labels: bug, new
