### ISSUE TITLE
Terraform Crash: checkable object status report for unexpected checkable object

### ISSUE THREAD

**Issue by sean-rossignol** [hashicorp/terraform#34052] opened 2023-10-10 21:45 UTC
### Terraform Version

```shell
1.6.0
1.6.1
```

### Terraform Configuration Files

The crash occurs on a variable in an internal module which is a wrapper around some hashicorp aws msk resources.  The variable in question is a string:
```
variable "compression_type" {
  description = "<desc>"
  default = "lz4"
  validation {
    condition = contains(["gzip", "snappy", "lz4", "zstd", "uncompressed", "producer"], var.compression_type)
    error_message = "<error_message>"
  }
}
```

This variable is passed into the `aws_msk_configuration` resource server.properties parameter:
```
resource "aws_msk_configuration" "config" {
  kafka_versions    = [var.msk_kafka_version]
  name              = "<name>"
  server_properties = <<PROPERTIES
    compression.type = ${var.compression_type}
    PROPERTIES

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.msk.var.compression_type
goroutine 8280 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2b94ec0?, 0xc00b40e8f0?})
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0xc0031e3bc0, {0x390a1d0, 0xc004490e40}, 0xc000100000?, 0x0, 0x50)
        /home/runner/work/terraform/terraform/internal/checks/state_report.go:106 +0x345
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x2fcdc40?, {0x390a1d0?, 0xc004490e40?}, 0xc001d516a8?, 0x1?, 0x1?)
        /home/runner/work/terraform/terraform/internal/checks/state_report.go:71 +0xc5
github.com/hashicorp/terraform/internal/terraform.evalVariableValidations({{0xc006699040, 0x1, 0x1}, {{}, {0xc0007a3a70, 0x10}}}, 0xc0009c2820, {0x0, 0x0}, {0x3922940, ...})
        /home/runner/work/terraform/terraform/internal/terraform/eval_variable.go:252 +0xb52
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0xc000dc0cc0, {0x3922940, 0xc000e388c0}, 0x5)
        /home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:198 +0x3f1
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0018eb0e0, {0x3922940, 0xc000e388c0}, {0x4047af7540, 0xc000dc0cc0})
        /home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2f09cc0, 0xc000dc0cc0})
        /home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000dc0d80, {0x2f09cc0, 0xc000dc0cc0}, 0xc003970940)
        /home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 8007
        /home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8
```

### Expected Behavior

This only occurs at destroy time.  I expect the given objects to be destroyed but terraform crashes instead.

### Actual Behavior

Terraform should destroy the managed objects

### Steps to Reproduce

terraform destroy

### Additional Context

We have some projects internally with scheduled builds and tf version constraints set to something like `~> 1.3`.  When one of these projects builds kicked off post 1.6.0 release it started failing with the attached Terraform Crash error.  Builds still have the same crash using tf 1.6.1.  

When I revert to tf version 1.5.7 the destroy completes without issue so this issue seems exclusive to 1.6.* versions.

**Comment by liamcervante** [comment] 2023-10-11 06:30
Hi @sean-rossignol - I think this is a duplicate of #34014.

This is a bug within the earlier 1.3 series, we're planning to temporarily patch 1.6 so that it maintains interoperability with the earlier series for a bit longer but we will eventually need to reintroduce this behaviour, probably within the 1.7 release. I think you maybe using `terraform_remote_state` within the internal projects? This is the source of the crash.

You should make sure your 1.3 versions of Terraform are patched to `v1.3.10` which fixes the issue directly, and is compatible with the 1.6 series. You will need to do this before the 1.7 series is released.

**Comment by liamcervante** [comment] 2023-10-11 07:15
Apologies @sean-rossignol, I don't think this is a duplicate having looked at it more closely. 

How are the 1.3 series and 1.6 series interacting in your setup? Is it the 1.3 series that's crashing or the 1.6 series? Or did you upgrade your 1.3 version to 1.6 to experience the crash?

**Comment by liamcervante** [comment] 2023-10-11 16:25
Thanks for the extra context @sean-rossignol! 

So far, I've been unable this to replicate this. Are you able to provide a minimal example and a set of commands that triggers the crash so I can get a closer look at what's happening? I've tried making a simple configuration with a variable condition, but I can run apply and destroy commands without any problems.

Thanks!

**Comment by mprimeaux** [comment] 2023-10-12 00:23
We are now running into this issue with an ephemeral environment that was formed today with Terraform 1.6.1 and was being destroyed with the same version.  

```shell
Do you really want to destroy all resources in workspace "dev-1"?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.core-infrastructure.module.vpc.var.id_length_limit
goroutine 50360 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x164
panic({0x1072f68a0?, 0x140061ba980?})
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x26c
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0x1400cfb11b8, {0x1079288a8, 0x14005168ff0}, 0x0?, 0x0, 0x50)
	/Users/runner/work/terraform/terraform/internal/checks/state_report.go:106 +0x2a8
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x107732720?, {0x1079288a8?, 0x14005168ff0?}, 0x14007adb678?, 0x1?, 0x1275800?)
	/Users/runner/work/terraform/terraform/internal/checks/state_report.go:71 +0xd4
github.com/hashicorp/terraform/internal/terraform.evalVariableValidations({{0x14002c5aec0, 0x2, 0x2}, {{}, {0x14001275800, 0xf}}}, 0x1400136e340, {0x0, 0x0}, {0x10793e450, ...})
	/Users/runner/work/terraform/terraform/internal/terraform/eval_variable.go:252 +0x85c
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0x1400706b020, {0x10793e450, 0x14002c8a540}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:198 +0x2d4
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14002ed46c0, {0x10793e450, 0x14002c8a540}, {0x110d44188, 0x1400706b020})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xa0
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x10766ea60, 0x1400706b020})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x280
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x1400706b0e0, {0x10766ea60, 0x1400706b020}, 0x14002c5af40)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2a8
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 49630
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xb0c
```

I then attempted to destroy the environment with `1.6.0`, which resulted in the exact same stack trace. I then reverted to Terraform `1.5.7` and was able to successfully able to destroy the environment.

**Comment by liamcervante** [comment] 2023-10-12 06:56
@mprimeaux - are you able to share some minimal configuration that replicates this?

**Comment by liamcervante** [comment] 2023-10-12 13:10
If there's anything else you can think of that might help me replicate this that would be helpful too. Like, is there anything different about the way this variable is referenced, anything about how the module it is in is being loaded, or anything about the particular sequence of commands that leads to this.

I've tried this with many different variations of configurations and so far it has worked for me - I suspect there's an edge case that this is triggering for but I can't find it.

**Comment by aprice-sss** [comment] 2023-10-13 17:57
I am seeing identical behavior applying & destroying with Terraform 1.6.1, but similarly it is a complex setup that I'm not able to disclose publicly and I haven't yet been able to reduce it to a MRE yet. I don't expect it's a surprise given the stack trace, but it doesn't appear to be provider-specific since I'm getting this with Azure resources with nothing in AWS. It happens reliably in 1.6.1, I can't test 1.6.0 because that release was unusable for me due to the signing key change that was reverted in 1.6.1, but I didn't have this issue with 1.5.x and I'm able to work around by reverting to 1.5.7.

```
checkable object status report for unexpected checkable object module.ra_test_cluster.var.disk_size
goroutine 6560 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x164
panic({0x10762a8a0?, 0x14001bd2bd0?})
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x26c
github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult(0x14002dc5200, {0x107c5c8e8, 0x14002e5a4b0}, 0x0?, 0x0, 0x50)
	/Users/runner/work/terraform/terraform/internal/checks/state_report.go:106 +0x2a8
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult(0x107a66760?, {0x107c5c8e8?, 0x14002e5a4b0?}, 0x14001b97678?, 0x1?, 0x16a64e0?)
	/Users/runner/work/terraform/terraform/internal/checks/state_report.go:71 +0xd4
github.com/hashicorp/terraform/internal/terraform.evalVariableValidations({{0x14000d209e0, 0x1, 0x1}, {{}, {0x140016a64e0, 0x9}}}, 0x140016de000, {0x107c58340, 0x140009ac600}, {0x107c72490, ...})
	/Users/runner/work/terraform/terraform/internal/terraform/eval_variable.go:252 +0x85c
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0x14000c16780, {0x107c72490, 0x140016977a0}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:198 +0x2d4
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x140013ccd80, {0x107c72490, 0x140016977a0}, {0x130b9daa8, 0x14000c16780})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xa0
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x1079a2a80, 0x14000c16780})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x280
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14000c16960, {0x1079a2a80, 0x14000c16780}, 0x140028fe2c0)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2a8
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 6741
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xb0c
```

Versions:
```
Terraform v1.6.1
on darwin_arm64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.21.0
+ provider registry.terraform.io/hashicorp/azurerm v3.75.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/strongdm/sdm v6.0.1
```

I can show how that var is defined and used:
```
variable "disk_size" {
  type        = number
  description = "Disk size in megabytes"

  validation {
    condition     = contains([32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608, 16777216, 33553408], var.disk_size)
    error_message = "disk_size must be one of 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608, 16777216 or 33553408"
  }
}

// Only one reference:
resource "azurerm_postgresql_flexible_server" "postgres" {
  // ...
  storage_mb            = var.disk_size
  // ...
}
```

At the module call site, that var is filled with a literal:
```
module "ra_test_cluster" {
  // ...
  disk_size           = 32768
  // ...
}
```

It's pretty much the simplest possible use of a variable: workspace passes a literal to the module, module passes it unaltered to a resource, no manipulation, no indirection, and even the validation is fairly simple.

**Comment by rjminchuk** [comment] 2023-10-14 17:10
I’m also having this issue at destroy time. https://github.com/hashicorp/terraform/issues/33770#issuecomment-1758539135

**Comment by liamcervante** [comment] 2023-10-16 08:17
A quick summary of where I am in my investigation of this.

This crash is originating in one of these [two lines](https://github.com/hashicorp/terraform/blob/main/internal/terraform/eval_variable.go#L249-L253). 

This is essentially when Terraform attempts to report the result of the validation to the state file so that it can be recorded. Before the result is recorded, Terraform is supposed to register all the validations found in the configuration. The crash is happening because the problematic validations are not being registered first. I still don't know why they are not being registered though.

For apply operations, the registrations are supposed to come from the plan which happens [here](https://github.com/hashicorp/terraform/blob/main/internal/terraform/context_walk.go#L128-L138). Looking at all the information I have in this thread, the crash always occurs during the apply stage of the destroy operation (ie. after the plan has been printed and the user has typed "yes" into prompt).

With that in mind, there's two possibilities. First, the plan isn't performing the required checks and just isn't registering or recording them and therefore they're not in the plan file for the apply operation to read when it tries to register them. Second, the validations are in the plan file and the apply operation isn't correctly reading them for some reason.

**Comment by liamcervante** [comment] 2023-10-16 08:19
I have a specific request now, so breaking that into a different comment to highlight it.

Could someone please execute the following with their crashing configuration, and tell me if the problematic validation is recorded in the `checks` section of the plan output?

```bash
terraform plan -destroy -out planfile
terraform show -json planfile
```

It's gonna be easier to read the output of the second command if you push it through `jq` or something similar, eg. `terraform show -json planfile | jq`. The `checks` section will look something like this:

```json
  "checks": [
    {
      "address": {
        "kind": "var",
        "module": "module.local",
        "name": "input",
        "to_display": "module.local.var.input"
      },
      "status": "pass",
      "instances": [
        {
          "address": {
            "module": "module.local",
            "to_display": "module.local.var.input"
          },
          "status": "pass"
        }
      ]
    }
  ]
```

If the problematic validation is not in the `checks` list then we have something wrong with the planning stage, if it is then we have something wrong with the apply stage.

A potentially interesting follow up to this would be if anyone can confirm if there is a difference in behaviour between running `terraform destroy` directly, and running `terraform plan -destroy -out planfile` and `terraform apply planfile` sequentially. Hopefully there is no difference there.

**Comment by liamcervante** [comment] 2023-10-16 12:12
Alright, I think I have a reproduction case or I found a new bug.

```hcl
# ./main.tf

module "local" {
    source = "./local"

    resource_directory = "resource.secondary"
}

provider "tfcoremock" {
    alias = "secondary"

    resource_directory = module.local.resource_directory
}

resource "tfcoremock_simple_resource" "resource" {
    provider = tfcoremock.secondary
}
```

```hcl
# ./local/main.tf

variable "resource_directory" {
    type = string

    validation {
      condition = var.resource_directory == "resource.secondary"
      error_message = "hello"
    }
}

resource "tfcoremock_simple_resource" "simple" {
    string = var.resource_directory
}

output "resource_directory" {
    value = tfcoremock_simple_resource.simple.string
}
```

The above crashes when you try to destroy it. In this case, the trick was having a downstream provider indirectly relying on a variable within a module. Can anyone confirm their configuration is doing something similar so I can say this is the same bug? Or alternatively is there anything else relying on the module outputs in the cases seen here.

Thanks!

**Comment by mprimeaux** [comment] 2023-10-16 15:31
@liamcervante I executed the following as requested...

```shell
terraform plan -destroy -out planfile
terraform show -json planfile 
```

We have approximately 4,000 lines in the `checks` section all with `"status": "unknown"`. Here is an excerpt.

```json
"checks": [
    {
      "address": {
        "kind": "var",
        "module": "module.core-infrastructure.module.autoscaler_role.module.service_account_label",
        "name": "context",
        "to_display": "module.core-infrastructure.module.autoscaler_role.module.service_account_label.var.context"
      },
      "status": "unknown"
    },
    {
      "address": {
        "kind": "var",
        "module": "module.core-infrastructure.module.autoscaler_role.module.service_account_label",
        "name": "id_length_limit",
        "to_display": "module.core-infrastructure.module.autoscaler_role.module.service_account_label.var.id_length_limit"
      },
      "status": "unknown"
    },
    ...
]    
```

Also, `terraform destroy` and (`terraform plan -destroy -out planfile` and `terraform apply planfile`) result in the same exception.

**Comment by liamcervante** [comment] 2023-10-17 08:39
Thanks for the responses! They confirm the issue being that the plan is skipping the variable validations, while the apply operation is applying them.

I've put together a PR that explicitly skips the variable validations for all destroy operations (both plans and applys) which should address the root cause of the issue. This matches the behaviour of the other custom conditions anyway, which also don't execute during destroy operations.

**Closed** 2023-10-18 14:49 UTC
Labels: bug, confirmed, explained

**Comment by sean-rossignol** [comment] 2023-10-18 22:23
@liamcervante I have validated that tf version 1.6.2 fixes this issue for our affected deployments.  Thank you for your prompt investigation and fix for this issue!

**Comment by mprimeaux** [comment] 2023-10-18 22:36
@sean-rossignol Thanks for testing!  I'll test once the brew formula is updated to `1.6.2`.

**Comment by crw** [comment] 2023-10-19 17:53
@mprimeaux Just FYI, the correct way to install Terraform from homebrew is:

```
brew tap hashicorp/tap
brew install hashicorp/tap/terraform
```

The unofficial Terraform brew formula is being deprecated. Thanks!

**Comment by mprimeaux** [comment] 2023-10-19 18:07
Thanks for the `brew` details. I ended up just executing `tfenv install latest`.  As an aside, I can confirm that `1.6.2` addresses this issue. 

Thanks again for your help.
