### ISSUE TITLE
Deprecate DynamoDB Locking in favor of all-in-one S3 backend

### ISSUE THREAD

**Issue by Clete2** [hashicorp/terraform#27105] opened 2020-12-03 11:44 UTC
### Current Terraform Version

```
0.13.5
```

### Use-cases

Currently, S3 backends optionally support a DynamoDB locking table to lock state while operations are being run. This can be simplified.

### Attempted Solutions

N/A

### Proposal

S3 announced yesterday that they support [strong read-after-write consistency](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/), thus allowing for the simplification of the S3 backend. Previously, we used DynamoDB for locking because it can be made to be strongly consistent. Now, we don't need DynamoDB. We can move all locking logic into S3 itself and eliminate the need for a DynamoDB table.

**Comment by jbardin** [comment] 2020-12-03 13:25
Duplicate of #27070

**Closed by jbardin** 2020-12-03 13:25 UTC
Labels: enhancement, new

**Comment by Clete2** [comment] 2020-12-03 13:40
Whoops sorry about that. I searched for issues but apparently I suck at searching! ;)
