### ISSUE TITLE
[Doc] Missing sections

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/terraform#1691] opened 2015-04-27 13:40 UTC
Hello.

We are planing to move all the Sensiolabs infrastructure to TF, but before that, We want to understand correctly the tool. 

So I'm reading the documentation. And I would like to get more information about "best practice".
Of course, there are many blog post about TF, but an official "best pratice" book  supported by the TF team  is always better than random blog posts.

For exemple, I was not able to find answer to theses questions:

* It is better to have 1 big or N small `.tfstate`? ( where N = applicationA + applicationB + monitoring cluster + rabbitmq cluster + ....)
* How to replace just a worker from a cluster? Because it looks like TF destroy the node (or cluster?), then create it. It prefer to first add a new worker, then delete the old one.
* How to change the flavor of the cluster? (I mean, I can find some solution to get ride of this issue, but an official doc would be better)
* Even if you are talking a bit about packer, It would be nice to get a real position about this workflow => something like "Yes, using packer is the best way to leverage TF because ...."
* How to handler "production" / "preproduction" / "qa" / "test" infrastructure?

**Comment by knuckolls** [comment] 2015-04-28 15:30
I'll just drop some of my thoughts in here. These are just my opinions, I'm not sure that many best practices are hammered out just yet.

"It is better to have 1 big or N small .tfstate? ( where N = applicationA + applicationB + monitoring cluster + rabbitmq cluster + ....)"

I prefer to have one big statefile (per environment), but the remote state stuff that has landed / will land soon is interesting. That way one team could manage the servers and another team could handle the containers that ride atop them. 

"How to replace just a worker from a cluster? Because it looks like TF destroy the node (or cluster?), then create it. It prefer to first add a new worker, then delete the old one."

There is the concept of create_before_destroy in the lifecycle block of each resource. If you taint the resource once it's been tagged that way, I believe it will work as you expect.

"How to change the flavor of the cluster? (I mean, I can find some solution to get ride of this issue, but an official doc would be better)"

You mean the instance flavor? I believe this falls under the same category of create_before_destroy after you change the flavor in the tf files. It'll want to roll all the machines. The only complexity is that if it's a stateful cluster then you'll want to make sure you don't accidentally lose blocks in the process. I have a PR in mind for how to handle this, but currently I'll just leave it as there are some complexities involved when you're dealing with stateful services.

"Even if you are talking a bit about packer, It would be nice to get a real position about this workflow => something like "Yes, using packer is the best way to leverage TF because ...."

I believe that it's best to use packer to create your images with everything that need to be pre-installed. Then use terraform to run post-launch responsibilities on the boxes. If you pack everything into a single image, then you will have an additional step of "mutate" wherein you take the "stemcell image" and mutate it into whatever speciality you need it to perform.

"How to handler "production" / "preproduction" / "qa" / "test" infrastructure?"

We have a skeleton-env that represents the structure of what we might consider production. Each environment is going to have differences, like versions of things, ssl certs, secrets, etc. You can use modules that pin to a specific git sha/tag so that your environments truly represent specific points in time in the git history of your skeleton env.

Hope that helps!

**Comment by lyrixx** [comment] 2015-04-28 16:33
@knuckolls Thanks you very much for all these nice answer. I though the same things ;) 
Now, If the maintainer agree, I could send a few PR to enhance the documentation.

**Comment by mitchellh** [comment] 2015-04-29 04:39
@lyrixx Please do send doc updates. I'm not sure where these should go... but we can discuss that after the content exists. Thanks!

**Closed by mitchellh** 2015-04-29 04:39 UTC
