### ISSUE TITLE
Terraform plan doesn't give changes going to get applied and just failed when resource is about to be replaced due to lifecycle.prevent_destroy

### ISSUE THREAD

**Issue by ravick4u** [hashicorp/terraform#34305] opened 2023-11-27 23:29 UTC
### Terraform Version

```shell
Terraform v1.5.5
```

### Terraform Configuration Files

```terraform
...terraform config...
```
Refer to step to reproduce

### Debug Output

Terraform error out like below
```
azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/<subscriptionsid>/resourceGroups/<rgname>]
azurerm_storage_account.example: Refreshing state... [id=/subscriptions/<subscriptionsid>/resourceGroups/<rgname>/providers/Microsoft.Storage/storageAccounts/salifecycleissuetest]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Instance cannot be destroyed
│
│   on main.tf line 53:
│   53: resource "azurerm_storage_account" "example" {
│
│ Resource azurerm_storage_account.example has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan,       
│ either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

### Expected Behavior

Terraform plan should give output on why the resource is about to get destroyed.

### Actual Behavior

Terraform error out like below

```
azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/<subscriptionsid>/resourceGroups/<rgname>]
azurerm_storage_account.example: Refreshing state... [id=/subscriptions/<subscriptionsid>/resourceGroups/<rgname>/providers/Microsoft.Storage/storageAccounts/salifecycleissuetest]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Instance cannot be destroyed
│
│   on main.tf line 53:
│   53: resource "azurerm_storage_account" "example" {
│
│ Resource azurerm_storage_account.example has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan,       
│ either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

### Steps to Reproduce

Run ```terraform init``` and ```terraform apply``` for below terraform code

```
terraform {
  backend "local" {
  }

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.44.1"
    }
  }

}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy    = true
      recover_soft_deleted_key_vaults = true
    }
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

locals {
  default_tags = {
    tag='tagvalue'
  }

  location            = "eastus"
  resource_group_name = "rgname"
  
}

resource "azurerm_resource_group" "rg" {
  name     = local.resource_group_name
  location = local.location

  tags = local.default_tags
}

resource "azurerm_storage_account" "example" {
  name                     = "salifecycleissuetest"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  lifecycle {
    prevent_destroy = true
  }

  tags = local.default_tags
}
```

Once resource is created add below line for ```azurerm_storage_account```

  infrastructure_encryption_enabled = true

Run ```terrafrom apply``` and you will get below error

### Additional Context

nothing

**Comment by jbardin** [comment] 2023-11-29 14:36
Duplicate of #34305

**Closed by jbardin** 2023-11-29 14:36 UTC
Labels: bug, new
