### ISSUE TITLE
Terraform 0.12 does not download module files beginning with "." (dot) on the 2nd+ use of the same source

### ISSUE THREAD

**Issue by kipkoan** [hashicorp/terraform#22934] opened 2019-09-27 18:17 UTC
### Terraform Version
```
Terraform v0.12.9
```

### Terraform Configuration Files
```hcl
module "tf_dotfiles_1" {
  # remote source: DOES NOT WORK in tf 0.12.9 - 2nd module has no dotfile included
  source = "git@github.com:kipkoan/tf-0.12-dotfiles-bug.git//modules/tf_dotfiles"
}

module "tf_dotfiles_2" {
  source = "git@github.com:kipkoan/tf-0.12-dotfiles-bug.git//modules/tf_dotfiles"
}
```

### Expected Behavior
Terraform should download all files in the module, including ones starting with `.` (dot).

### Actual Behavior
Terraform did not download the files starting with `.` (dot) on the 2nd or subsequent instantiations of the module:

```
$ ll .terraform/modules/*/modules/tf_dotfiles/

.terraform/modules/tf_dotfiles_1/modules/tf_dotfiles/:
total 4.0K
-rw-r--r-- 1 kipm kipm 0 Sep 27 17:59 .dotfile
-rw-r--r-- 1 kipm kipm 1 Sep 27 17:59 main.tf
-rw-r--r-- 1 kipm kipm 0 Sep 27 17:59 nodotfile

.terraform/modules/tf_dotfiles_2/modules/tf_dotfiles/:
total 4.0K
-rw-r--r-- 1 kipm kipm 1 Sep 27 17:59 main.tf
-rw-r--r-- 1 kipm kipm 0 Sep 27 17:59 nodotfile
```

### Steps to Reproduce
1. Clone repo: https://github.com/kipkoan/tf-0.12-dotfiles-bug
1. `cd environments/dev`
1. `rm -rf .terraform`
1. `terraform init`
1. `ll .terraform/modules/*/modules/tf_dotfiles/`
1. Notice the missing `.dotfile` in `tf_dotfiles_2`

**Comment by kipkoan** [comment] 2019-09-27 20:46
Same as https://github.com/hashicorp/terraform/issues/22844

**Comment by kmoe** [comment] 2019-09-30 12:08
Thanks for the great reproducible bug report, @kipkoan. I'm closing this as a duplicate of #22844.

**Closed by kmoe** 2019-09-30 12:08 UTC
