### ISSUE TITLE
Rendering template with '@' not functioning

### ISSUE THREAD

**Issue by davidrymkiewicz** [hashicorp/terraform#19566] opened 2018-12-06 15:32 UTC
Hello All,

I'd like to report that this is still an issue. Error return and script component below.

```
Error: Error refreshing state: 1 error(s) occurred:

* data.template_file.template: 1 error(s) occurred:

* data.template_file.template: data.template_file.template: failed to render: parse error at 101:33: expected expression but found invalid sequence "@"
```
Here is the code from the bash script
```
for element in "${sitearray[@]}"
do
    echo $element
done
```

Running terraform:
```
Terraform v0.11.10
+ provider.aws v1.50.0
+ provider.random v2.0.0
+ provider.template v1.0.0
```

**Comment by jbardin** [comment] 2018-12-06 17:53
Hi @davidrymkiewicz,

The string `"${sitearray[@]}"` looks like an HCL interpolation, so terraform attempts to parse it as such, and encounters the invalid `@` character.

In order to escape the `$` characters, you need to double them, as shown in the [template provider](https://www.terraform.io/docs/providers/template/) example.

```
for element in "$${sitearray[@]}"
do
    echo $$element
done
```

**Comment by jbardin** [comment] 2018-12-10 23:19
Closing the issue as resolved.
Feel free to reply here this solution still does not work as expected.

**Closed by jbardin** 2018-12-10 23:19 UTC

**Comment by syquus** [comment] 2020-01-09 11:45
Hello,

I'm experiencing this same problem, in my case this are my components versions:

- Terraform v0.12.18
- provider.aws v2.43.0
- provider.template v2.1.2

I have in a tpl file, line 33:
`for i in "${!DOTENVVARS[@]}"`

But Terraform is complaining that the "@" is not usedd within the language:

> failed to render : <template_file>:33,43-44: Invalid character; This character is not used within the language., and 2 other diagnostic(s)

What would be the proper way of escaping it?

I already tried the suggestion of @jbardin of adding $$, or even $$$, with no success. Same error on all tries.

**Comment by syquus** [comment] 2020-01-09 13:05
Update to my previous post: The parser error reporting mechanisms seems to be the cause of the misunderstanding. It was telling my that the "at sign" ("@") was the problem with this code:

```
for i in "$${!DOTENVVARS[@]}"
do
	sed -i '/^\(${i}=\).*/{s//\1${DOTENVVARS[${i}]}/;:a;n;ba;q}' -i '$a${i}=${DOTENVVARS[${i}]}' $${ENVFILE}
done
```

and after changing it to 
```
for i in "$${!DOTENVVARS[@]}"
do
	sed -i '/^\($${i}=\).*/{s//\1$${DOTENVVARS[$${i}]}/;:a;n;ba;q}' -i '$a$${i}=$${DOTENVVARS[$${i}]}' $${ENVFILE}
done
```

it stopped throwing the error (ABOUT THE "@"!!). So to me it's more a bug in the error message/tracing system that in the source code of the template provider.
