### ISSUE TITLE
Terraform doesn't produce error if parsing of s3 bucket policy json failed

### ISSUE THREAD

**Issue by murat1985** [hashicorp/terraform#7967] opened 2016-08-04 05:25 UTC
Spotted minor bug in behaviour. Terraform produces green success output even s3 bucket policy json parsing is failed:
```
make plan
...
+ aws_s3_bucket.bucket-name
    acceleration_status:      "<computed>"
    acl:                      "private"
    arn:                      "<computed>"
    bucket:                   "bucket-name"
    force_destroy:            "false"
    hosted_zone_id:           "<computed>"
    policy:                   "Error parsing JSON: invalid character '\"' after object key:value pair"
    region:                   "<computed>"
    website.#:                "1"
    website.0.index_document: "index.html"
    website_domain:           "<computed>"
    website_endpoint:         "<computed>"
```

### Terraform Version
```
 >> terraform -v
Terraform v0.7.0
```
### Affected Resource(s)
```
aws_s3_bucket
```

### Terraform Configuration Files

To reproduce make json output invalid, e.g. remove coma before "Condition" key.

```
  policy = <<EOF
{
  "Version": "2008-10-17",
  "Id": "Policy1234567",
  "Statement": [
    {
      "Sid": "AllowGetObject",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::bucket_name"
      "Condition": {
        "IpAdress": {
          "aws:SourceIp": [ "${var.myvar}" ]
        }
      }
    }
  ]
}
EOF
```

### Expected Behavior
Fail terraform plan on json error
```
"Error parsing JSON: invalid character '\"' after object key:value pair"
```

### Actual Behavior
It doesn't fail and produces green output

**Comment by kwilczynski** [comment] 2016-08-04 11:04
Sorry about this!

This could definitely be improved, as per:

[resource_aws_s3_bucket.go#L1313-L1324](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_s3_bucket.go#L1313-L1324)

and

[resource_aws_s3_bucket.go#L438-L455](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_s3_bucket.go#L438-L455)

Which probably could benefit form returning both error and string allowing for marshalling errors to bubble outside of `normalizeJson` function.

Having said that, this might be expected behaviour and/or by design for plan part.

**Comment by jen20** [comment] 2016-08-06 21:35
Hi @murat1985! I definitely agree this is a bug, we'll get it taken care of.

**Comment by kwilczynski** [comment] 2016-08-06 21:38
@jen20 I am having a look at this:

https://github.com/kwilczynski/terraform/commit/278932a5403218d25cddd1761fa34b126b551c55

There is more work to do be done as `normalizeJson` is used all over the place.

**Comment by hamstah** [comment] 2016-08-18 15:36
Hi,
I've had the same issue, but the result is slightly different, see below
```
aws_s3_bucket.audit: Modifying...
  policy: "{\ ... \"}" => "Error parsing JSON: invalid character '\"' after object key:value pair"
aws_s3_bucket.audit: Still modifying... (10s elapsed)
```
It will keep waiting on the creation to succeed

**Comment by kwilczynski** [comment] 2016-09-19 19:53
@murat1985 @hamstah work on this is almost one! Thank you for your patience!

**Comment by stack72** [comment] 2016-09-22 20:00
Closed via all the work added for JSON validation to 0.7.5 by @kwilczynski :)

**Closed by stack72** 2016-09-22 20:00 UTC
Labels: bug, provider/aws

**Comment by hamstah** [comment] 2016-09-23 09:59
Thanks!
