### ISSUE TITLE
VSphere Virtual Machine Taint Error

### ISSUE THREAD

**Issue by DustinChaloupka** [hashicorp/terraform#8082] opened 2016-08-09 21:14 UTC
### Terraform Version

0.7.0
### Affected Resource(s)
- vsphere_virtual_machine
### Terraform Configuration Files

Something like the following:

``` hcl
resource "vsphere_virtual_machine" "machine" {
  count = "1"

  dns_servers = ["10.3.0.53,10.1.1.25,172.24.17.41"]

  name = "test-vsphere-machine.test.com"

  memory = "4096"
  vcpu = "2"

  lifecycle {
    ignore_changes = ["network_interface.0.ipv4_gateway"]
  }

  disk {
    datastore = "vsphere_lun03"
    template = "packer-stemcell-vsphere-1464371835-vm"
  }

  disk {
    datastore = "vsphere_lun03"
    size = "20"
    name = "test-machine"
  }

  network_interface {
    label = "label"
    ipv4_address = "10.211.2.25"
    ipv4_gateway = "10.211.3.254"
    ipv4_prefix_length = "22"
  }

  ...connection and provisioner blocks...
}
```
### Error

<details>
<summary>

Error Output</summary>

```
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.machine: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.0
    Resource ID: vsphere_virtual_machine.machine
    Mismatch reason: extra attributes: enable_disk_uuid, disk.2653470468.template, disk.2653470468.uuid, disk.3320299846.template, disk.3320299846.datastore, network_interface.0.ip_address, disk.3320299846.uuid, network_interface.0.label, time_zone, network_interface.0.ipv4_address, skip_customization, disk.#, disk.3320299846.vmdk, network_interface.0.ipv4_prefix_length, dns_servers.#, linked_clone, disk.2653470468.datastore, disk.2653470468.key, memory_reservation, dns_servers.0, disk.2653470468.size, disk.3320299846.key, network_interface.0.ipv4_gateway, network_interface.0.ipv6_address, network_interface.0.ipv6_prefix_length, disk.2653470468.type, memory, vcpu, domain, network_interface.0.ipv6_gateway, dns_servers.2, network_interface.0.subnet_mask, disk.2653470468.vmdk, disk.3320299846.type, dns_servers.1, disk.2653470468.name, uuid, disk.3320299846.name, network_interface.0.mac_address, network_interface.#, disk.3320299846.controller_type, disk.2653470468.controller_type, name
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"disk.3320299846.size":*terraform.ResourceAttrDiff{Old:"0", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.keep_on_remove":*terraform.ResourceAttrDiff{Old:"false", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.bootable":*terraform.ResourceAttrDiff{Old:"false", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.bootable":*terraform.ResourceAttrDiff{Old:"false", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.iops":*terraform.ResourceAttrDiff{Old:"0", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.iops":*terraform.ResourceAttrDiff{Old:"0", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.keep_on_remove":*terraform.ResourceAttrDiff{Old:"false", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:true}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"disk.3320299846.controller_type":*terraform.ResourceAttrDiff{Old:"", New:"scsi", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.0.ipv4_prefix_length":*terraform.ResourceAttrDiff{Old:"", New:"22", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.iops":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.uuid":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.datastore":*terraform.ResourceAttrDiff{Old:"", New:"vsphere_lun03", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "memory_reservation":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "disk.3320299846.vmdk":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.size":*terraform.ResourceAttrDiff{Old:"", New:"20", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.0.label":*terraform.ResourceAttrDiff{Old:"", New:"VLAN109-app-db", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "disk.3320299846.bootable":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.key":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "uuid":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.type":*terraform.ResourceAttrDiff{Old:"", New:"eager_zeroed", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.0.ipv6_gateway":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.bootable":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.vmdk":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vcpu":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.0.ipv4_address":*terraform.ResourceAttrDiff{Old:"", New:"10.211.2.25", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.name":*terraform.ResourceAttrDiff{Old:"", New:"test-vsphere-machine", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.datastore":*terraform.ResourceAttrDiff{Old:"", New:"vsphere_lun03", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.template":*terraform.ResourceAttrDiff{Old:"", New:"packer-stemcell-vsphere-1464371835-vm", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "dns_servers.0":*terraform.ResourceAttrDiff{Old:"", New:"10.3.0.53", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "disk.2653470468.controller_type":*terraform.ResourceAttrDiff{Old:"", New:"scsi", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.0.ipv4_gateway":*terraform.ResourceAttrDiff{Old:"", New:"10.211.3.254", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.0.mac_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enable_disk_uuid":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "skip_customization":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "disk.2653470468.keep_on_remove":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.uuid":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "dns_servers.#":*terraform.ResourceAttrDiff{Old:"", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "network_interface.0.ip_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain":*terraform.ResourceAttrDiff{Old:"", New:"vsphere.local", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "disk.3320299846.size":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.#":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "dns_servers.2":*terraform.ResourceAttrDiff{Old:"", New:"172.24.17.41", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "network_interface.0.subnet_mask":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"test-vsphere-machine.test.com", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "dns_servers.1":*terraform.ResourceAttrDiff{Old:"", New:"10.1.1.25", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "network_interface.0.ipv6_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "network_interface.0.ipv6_prefix_length":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.key":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.iops":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.3320299846.keep_on_remove":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "linked_clone":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "disk.2653470468.type":*terraform.ResourceAttrDiff{Old:"", New:"eager_zeroed", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "time_zone":*terraform.ResourceAttrDiff{Old:"", New:"Etc/UTC", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "memory":*terraform.ResourceAttrDiff{Old:"", New:"4096", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk.2653470468.template":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:true}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

</details>
### Expected Behavior

Machine is destroyed then recreated when being tained
### Actual Behavior

Crash after the machine is destroyed
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply` a machine
2. Taint the machine resource
3. `terraform apply`

A note: As a work around and maybe an interesting tidbit is that editing the count to 0 to destroy the machine and then back to 1 to bring it up does work.

**Comment by mitchellh** [comment] 2016-11-17 17:48
Hello! This should be fixed in later versions of Terraform (0.7.11 at time of writing). 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 17:48 UTC
Labels: bug, provider/vsphere
