### ISSUE TITLE
terraform crash while trying to specify network for openstack instance

### ISSUE THREAD

**Issue by dupuy** [hashicorp/terraform#1727] opened 2015-04-29 10:58 UTC
Having a mess of trouble trying to get this syntax right, but the following attempt crashed my terraform 0.4.2, so I'm reporting it:

```
resource "openstack_compute_instance_v2" "openvpn" {
    region = "${var.region}"
    name = "vpngw"
    image_name = "Ubuntu 14.04LTS"
    flavor_name = "m1.small"
    floating_ip = "${openstack_compute_floatingip_v2.vpngw.address}"
    network = [ "${openstack_networking_network_v2.dmz.id}" ]
    security_groups = [
	"default",
	"${openstack_compute_secgroup_v2.openvpn.name}"
    ]
}
```

probably relevant extract from `crash.log`:

```
panic: Unknown kind: string
2015/04/29 12:49:33 terraform-provider-openstack:
2015/04/29 12:49:33 terraform-provider-openstack: goroutine 29 [running]:
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/terraform.(*ResourceConfig).get(0xc2081dc8a0, 0xc2082b7830, 0xe, 0xc2081dc900, 0x0, 0x0, 0x19dd00)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/terraform/resource.go:203 +0x6b0
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/terraform.(*ResourceConfig).Get(0xc2081dc8a0, 0xc2082b7830, 0xe, 0x0, 0x0, 0xc2082b7830)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/terraform/resource.go:134 +0xb3
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc2080d8a20, 0xc2082b7830, 0xe, 0xc20807cd10, 0xc2081dc8a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:888 +0x98
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc2080d8a20, 0xc2082b77e0, 0x9, 0xc2080d8900, 0xc2081dc8a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:1014 +0x2fd
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.validateList(0xc2080d8a20, 0x5952b0, 0x7, 0x3f4a20, 0xc2082df1e0, 0xc20807dce0, 0xc2081dc8a0, 0x0, 0x0, 0x0, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:948 +0x78d
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc2080d8a20, 0x5952b0, 0x7, 0x3f4a20, 0xc2082df1e0, 0xc20807dce0, 0xc2081dc8a0, 0x0, 0x0, 0x0, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:1090 +0x121
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc2080d8a20, 0x5952b0, 0x7, 0xc20807dce0, 0xc2081dc8a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:916 +0x7f6
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc2080d8a20, 0x0, 0x0, 0xc2080d8a20, 0xc2081dc8a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:1014 +0x2fd
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.schemaMap.Validate(0xc2080d8a20, 0xc2081dc8a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/schema.go:403 +0x8d
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*Resource).Validate(0xc2080dc9c0, 0xc2081dc8a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:167 +0x6e
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/helper/schema.(*Provider).ValidateResource(0xc2080d90b0, 0xc2082df4a0, 0x1d, 0xc2081dc8a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:111 +0x2ae
2015/04/29 12:49:33 terraform-provider-openstack: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).ValidateResource(0xc20801ef80, 0xc2082deee0, 0xc2081dcc00, 0x0, 0x0)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/rpc/resource_provider.go:294 +0x9b
2015/04/29 12:49:33 terraform-provider-openstack: reflect.Value.call(0x49ea80, 0x549d70, 0x13, 0x57f510, 0x4, 0xc20832ff28, 0x3, 0x3, 0x0, 0x0, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/3rdparty/go/src/reflect/value.go:419 +0x10e5
2015/04/29 12:49:33 terraform-provider-openstack: reflect.Value.Call(0x49ea80, 0x549d70, 0x13, 0xc20832ff28, 0x3, 0x3, 0x0, 0x0, 0x0)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/3rdparty/go/src/reflect/value.go:296 +0xbc
2015/04/29 12:49:33 terraform-provider-openstack: net/rpc.(*service).call(0xc2080dcf00, 0xc2080dcec0, 0xc20800bd00, 0xc208066680, 0xc20801ff40, 0x3e07a0, 0xc2082deee0, 0x16, 0x3e0800, 0xc2081dcc00, ...)
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/3rdparty/go/src/net/rpc/server.go:382 +0x1f7
2015/04/29 12:49:33 terraform-provider-openstack: created by net/rpc.(*Server).ServeCodec
2015/04/29 12:49:33 terraform-provider-openstack: 	/Users/mitchellh/code/3rdparty/go/src/net/rpc/server.go:476 +0x44a
2015/04/29 12:49:33 terraform-provider-openstack:
```

**Comment by cvvs** [comment] 2015-04-29 21:22
Duplicate of #1493 , I believe. If you just need it to work, you can see how I configured the network in my instance.

**Closed** 2015-04-30 03:32 UTC
Labels: provider/openstack
