### ISSUE TITLE
Azure CustomScript Extensions

### ISSUE THREAD

**Issue by clintonm9** [hashicorp/terraform#6117] opened 2016-04-11 01:10 UTC
I was wanting to use the Terraform with Azure, but I would need CustomScripts.
https://github.com/Azure/azure-linux-extensions/tree/master/CustomScript

We use this for install Puppet to all of our new nodes.

Could we add this as an enhancement or someone give me guidance and I can do it with a pull request?

**Comment by stack72** [comment] 2016-04-13 15:09
Hi @clintonm9

I am going to close this as a duplicate of #5820 - this requires the CustomScripts to be in place :) Having 1 place to track it all will be much better
 
It will be taken care of as soon as some bugs are fixed in the VM resource

Thanks

Paul

**Closed by stack72** 2016-04-13 15:09 UTC

**Comment by yougandar** [comment] 2017-10-23 05:45
I want to setup a windows vm extension in terraform oci
