### ISSUE TITLE
DigitalOcean rejects multiple ssh_keys sent by terraform on droplet creation

### ISSUE THREAD

**Issue by plalloni** [hashicorp/terraform#1022] opened 2015-02-22 00:25 UTC
The following configuation:

```
provider "digitalocean" {
    token = "..."
}
resource "digitalocean_droplet" "blabla" {
    image = "10679356"
    name = "blabla"
    region = "nyc3"
    size = "1gb"
    ssh_keys = [647321, 416865]
}
```

When applied, gives:

```
% terraform apply
digitalocean_droplet.blabla: Creating...
  image:                "" => "10679356"
  ipv4_address:         "" => "<computed>"
  ipv4_address_private: "" => "<computed>"
  ipv6_address:         "" => "<computed>"
  ipv6_address_private: "" => "<computed>"
  locked:               "" => "<computed>"
  name:                 "" => "blabla"
  region:               "" => "nyc3"
  size:                 "" => "1gb"
  ssh_keys.#:           "" => "2"
  ssh_keys.0:           "" => "647321"
  ssh_keys.1:           "" => "416865"
  status:               "" => "<computed>"
digitalocean_droplet.blabla: Error: Error creating droplet: Error creating droplet: API Error: unprocessable_entity: 647321,416865 are invalid key identifiers for Droplet creation.
Error applying plan:

1 error(s) occurred:

* Error creating droplet: Error creating droplet: API Error: unprocessable_entity: 647321,416865 are invalid key identifiers for Droplet creation.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Also tried using strings instead of numbers in the ssh_keys array obtaining the same exact result.

FTR: when I put just one key identifier it works as expected.

**Comment by pearkes** [comment] 2015-02-23 17:40
Looks like a duplicate of #561, tracking this bug there. Thanks!

**Comment by plalloni** [comment] 2015-02-23 18:56
@pearkes FWIW the behavior I see is not the same reported in #561. In my case terraform fails while in #561 it only configures the first key in the droplet.

**Comment by pearkes** [comment] 2015-02-23 18:58
@plalloni aha, in that case I'll leave this open. Could still be a related issue but useful for debugging it. Thanks!

**Comment by pearkes** [comment] 2015-02-26 17:18
This should be fixed by switching to sending JSON for creation requests in https://github.com/pearkes/digitalocean/issues/4. Thanks!

**Closed by pearkes** 2015-02-26 17:18 UTC
Labels: bug, provider/digitalocean

**Comment by plalloni** [comment] 2015-02-27 11:48
@pearkes great!
