### ISSUE TITLE
Last commented out line not followed by a new line results in validation error

### ISSUE THREAD

**Issue by demisx** [hashicorp/terraform#21311] opened 2019-05-14 23:24 UTC
If the last line is acommented out and I don't insert a new line after it, `terraform validate` results in an error. Using terraform `v0.12-rc1`

```hcl
# In main.tf
  ...
# }  // <-- Last line and there is no new line after it
```

Error:
```sh
$ terraform validate
---
Error: Invalid character
  on main.tf line 91:
  91: # }
This character is not used within the language.

Error: Argument or block definition required
  on main.tf line 91:
  91: # }
```

**Comment by apparentlymart** [comment] 2019-05-14 23:28
Thanks for reporting this, @demisx!

This seems to be the same root cause as #21269, so I'm going to close this one just to consolidate. Thanks again!

**Closed by apparentlymart** 2019-05-14 23:28 UTC
