### ISSUE TITLE
"Deprecation" key notice within input variables for terraform modules

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform#19138] opened 2018-10-19 21:42 UTC
What do you think of a deprecation notice on input variables for terraform modules?

The use case is if you have a team that creates terraform modules that are reusable for developers, you may want to refactor those modules and eventually simplify or rename certain variables. This would force a lot of communication or would force our devops to PR a lot of repos to refactor code which in our company isn't viable. 

It would be nice when devs run terraform, they see the deprecation notice so they are notified well before we upgrade terraform modules.

```hcl
variable "some_input_var" {
  default = "true"
  description = "If true, this will create 2 ELBs"
  deprecation = "This is no longer being used and will be deprecated in the next release. Please use 'some_input_var2' instead for versions > 0.3.4"
}
```

**Comment by dcfsc** [comment] 2020-08-10 13:22
Agreed. What's the point of using semver if you cannot communicate the upcoming deprecation to the unsuspecting user? Or give a good hint on how to avoid the upcoming breaking change if the new alternative is already there? Devs don't always read the README :)

**Comment by snolan-amount** [comment] 2020-11-18 21:21
Duplicate of https://github.com/hashicorp/terraform/issues/18381

**Closed** 2020-11-20 04:31 UTC
Labels: enhancement
