### ISSUE TITLE
count in module based on variable

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform#25492] opened 2020-07-07 06:50 UTC
### Terraform Version

```
Terraform v0.12.26
...
```

### Terraform Configuration Files

```terraform
variable "policy" {
  description = "Policy JSON"
  type = string
  default = ""
}

resource "aws_iam_role_policy" "lambda_additional" {
  for_each = toset(var.policy == "" ? [] : [var.policy])
  name = ....
  role = ...
  policy = each.value
}
```
or even not using the for_each and instead using count:
```terraform
resource "aws_iam_role_policy" "lambda_additional" {
  count = var.policy == "" ? 0 : 1
  name = ...
  role = ...
  policy = var.policy
}
```

Call to module:
```terraform
module "lambda_function_custom_headers" {
  source = "../lambda_function"
  ...
  policy = ""
}
```
or using the default variable value **""**
```terraform
module "lambda_function_custom_headers" {
  source = "../lambda_function"
  ...
}
```

### Crash Output

```
Error: Invalid for_each argument

  on ../modules/lambda_function/main.tf line 79, in resource "aws_iam_role_policy" "lambda_additional":
  79:   for_each = toset(var.policy == "" ? [] : [var.policy])

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

### Expected Behavior

Should've applied properly as it is empty string, doesn't even reference to other resources.

### Actual Behavior

Stops with the error.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment] 2020-07-07 16:05
Hi @mgzenitech 

Thanks for filing the issue. Unfortunately I'm not able to reproduce this with Terraform 0.12 from the example provided.
If you could create a self-contained example, which could just use simpler resources like `null_resource`, we may be able to better track down the problem. 

If there is a reproducible problem with 0.12, there is a good chance that this has been rectified with 0.13, so I would suggest trying the latest beta release as well.

Thanks!

**Comment by mgzenitech** [comment] 2020-07-08 10:36
Hi @jbardin !
Sure I'll try to provide a small example, however most of my modules (or even all of them) that have string variable value and has conditional count with that fails with the message.

**Comment by mgzenitech** [comment] 2020-07-08 10:54
Hm.. looks like I can not reproduce the problem with 0.13-beta2. So looks like someone fixed this issue already. Thanks.

**Comment by mgzenitech** [comment] 2020-07-10 06:43
Issue started popping up today again when I switched to another workspace. What is interesting is that some modules with this do not experience this issue and some experience. I'll attach full trace log to help finding what's going on.

**Comment by mgzenitech** [comment] 2020-07-10 06:44
One more thing this happens also during `terraform refresh`

**Comment by tgourley01** [comment] 2020-09-03 04:30
I'm seeing this same issue in v12.28
...
resource "aws_ecs_task_definition" "ecs_service_task_definition" {
  count = var.task_definition_id == "" ? 1 : 0
 ...
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

var.task_definition_id is obviously passed into the module so what does it think the undetermined dependency is?
This is a critical bug IMO, I've found no workaround.
I've tried a bunch of ways to hack around this but nothing helps.
Does anyone know of any workarounds?

**Comment by mgzenitech** [comment] 2020-09-14 06:38
Only workaround currently is to pass additional boolean var... Unless this issue was fixed very recently in 0.13.1 or 0.13.2 versions?

**Comment by danieldreier** [comment] 2020-09-30 12:51
@mgzenitech I wanted to follow up and explain what we need in order to help with this. Based on the errors you described, I can't tell from the error alone whether this is a bug or a configuration error. @jbardin asked for a reproduction case using the null resource about three months ago, and that's still what we need in order to move forward on this.

To understand what's going on here, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, James wasn't able to reproduce it, and so we're stuck. I would like to help here, but I'm going to have to close this for lack of a reproduction case because there's no benefit to anyone in having an issue hanging around that we can't act on. I would really appreciate your help with this so that if there is a bug, we can find it and fix it.

Can you please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies.

**Comment by Nuru** [comment] 2020-09-30 18:30
@danieldreier @jbardin As I mentioned, I have a similar issue when I run `terraform console`. It happens with a module chain.

<details><summary>Click to see code</summary>

```hcl

root.tf:
locals {
  config = {
    main = ["red", "white", "blue"]
    alt = ["green", "yellow"]
  }
}

module "x" {
  for_each = local.config
  source = "./x"

  clones = each.value
}

output "combo" {
  value = values(module.x)[*].combo
}

---
./x/x.tf:
variable "clones" {
  type = list(string)
}

module "y" {
  for_each = toset(var.clones)
  source = "../y"

  color = each.value
}

output "combo" {
  value = values(module.y)[*].combo
}

---
./y/y.tf
variable "color" {
  type = string
}

resource "null_resource" "x" {

}
output "combo" {
  value = null_resource.x.id
}

```

</details>

```
$ terraform version
Terraform v0.13.3
$ terraform console

Warning: Due to the problems above, some expressions may produce unexpected results.


>  
Error: Invalid for_each argument

  on x/x.tf line 6, in module "y":
   6:   for_each = toset(var.clones)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

```
(Yes, the warning really is output before the error.)

Maybe fixing the console issue will fix the OP's issue, too.

**Comment by jbardin** [comment] 2021-04-01 19:39
Since we have not seen a reproduction here, and the fact that the "refresh" phase has been removed from terraform entirely, it's likely that this is not longer a relevant issue.

If there is still a problem in the most recent releases, feel free to file a new issue with the necessary information to reproduce the issue. 

Thanks!

**Closed by jbardin** 2021-04-01 19:39 UTC
Labels: bug, config, v0.12, v0.13, waiting for reproduction
