### ISSUE TITLE
Unable to use single backslash in command line var

### ISSUE THREAD

**Issue by timlharrison** [hashicorp/terraform#25860] opened 2020-08-14 19:18 UTC
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

```terraform
module "module123" {
  source              = "../path/to/module"

  json = <<DEPLOY
{
    "var": "${var.password}"
}
DEPLOY
}
```

Test 1
```
terraform apply -var 'password=abc\123'
```
Result: `Error parsing JSON: invalid character '1' in string escape code`

Test 2
```
terraform apply -var 'password=abc\\123'
```
Result: The variable is set to the value `abc\\123` using both backslashes

Test 3
```
terraform apply -var 'password=abc\\\123'
```
Result: `Error parsing JSON: invalid character '1' in string escape code`

Test 4
```
terraform apply -var 'password=abc\\\\123'
```
Result: The variable is set to the value `abc\\\\123` using four backslashes

### Expected Behavior

Test 2 should have escaped the backslash and given me a single backslash in the variable value.

### Actual Behavior

Not escaping the backslash gives an error while escaping the backslash gives me two backslashes. There seems to be no way to use a single backslash (or even an odd number of backslashes).

### Steps to Reproduce

Found above.

### Additional Context

Using terraform linux binary on Windows Subsystem for Linux.

**Comment by danieldreier** [comment] 2020-08-14 19:29
@timlharrison I've tried to reproduced this on OS X using zsh and bash and haven't been able to. I'm using the following HCL to narrow down just to the problem of escaping:
```HCL
variable "example" {
  type = string
}

output "example" {
  value = var.example
}
```

Here's what I get:
```
terraform apply -var 'example=foo\123' -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example = foo\123
```

What happens when you run this? What I'd really need is a full, clear reproduction case, something I can copy-paste and run locally, in order to determine whether there's a bug here or not.

**Comment by alisdair** [comment] 2020-08-14 20:37
I'm not sure without full context, but I think the issue here is that this error is coming from whatever is using your generated JSON: `Error parsing JSON: invalid character '1' in string escape code`. Terraform is working correctly here.

As GitHub syntax highlighting shows, this is an invalid JSON document:

```json
{
    "var": "abc\123"
}
```

What I think you actually want to output is `{"var": "abc\\123"}`, which is a JSON document encoding an object with key-value pair "var" and "abc\123".

Note that Terraform has [a very useful `jsonencode` function](https://www.terraform.io/docs/configuration/functions/jsonencode.html), which would save you from having to deal with these string quoting issues when defining variables. For example, consider this minimal configuration:

```hcl
variable "password" {
  type = string
}

output "json" {
  value = jsonencode(
    {
      password: var.password
    }
  )
}
```

This works as follows:

```shellsession
$ tf apply -var 'password=abc\123'

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

json = {"password":"abc\\123"}
```

I'm closing this because I believe it isn't a bug in Terraform core. If you think it is, please respond with a simple reproduction case as Daniel mentioned above and we can reopen it. I hope this answer is helpful!

**Closed by alisdair** 2020-08-14 20:37 UTC
Labels: bug, new, waiting for reproduction

**Comment by jtarchie** [comment] 2020-08-25 19:55
This sounds like a common issue with git bash for windows. See the [known issues](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues) #4 and #5
