### ISSUE TITLE
Output sensitive parameter cannot be set from variables

### ISSUE THREAD

**Issue by Lasering** [hashicorp/terraform#17679] opened 2018-03-23 14:32 UTC
### Terraform Version
```
0.11.3
```

### Terraform Configuration Files
```hcl
resource "random_integer" "number" {
  max = 0
  min = 10
}

locals {
  boolean = true
  booleanString = "true"
  computedBoolean = "${random_integer.number.result >= 5}"
}

output "output1" {
  value     = "Some secret value"
  sensitive = local.boolean
}
output "output2" {
  value     = "Some secret value"
  sensitive = "${local.boolean}"
}
output "output3" {
  value     = "Some secret value"
  sensitive = "${local.booleanString}"
}
output "output4" {
  value     = "Some secret value"
  sensitive = "${local.computedBoolean}"
}
output "output5" {
  value     = "Some secret value"
  sensitive = "${local.computedBoolean ? true : false}"
}
```

### Expected Behavior
All outputs should work (except maybe output1).

### Actual Behavior

  - output 1 = `Unknown token: 56:15 IDENT local.booleanString`
  - output 2 to 5 = `value for 'sensitive' must be boolean`

**Comment by apparentlymart** [comment] 2018-03-24 00:33
Hi @Lasering,

Unfortunately this is one of those situations where interpolations are not supported because this setting is intended to be usable for static analysis, which is to say that it should be possible to determine if an output is "sensitive" without performing any computations in the configuration.

If you have a real-world use-case to share then we could consider ways to make it possible, but generally-speaking it is not a goal for _everything_ in the Terraform configuration to be dynamically settable since different parts of the configuration must be processed at different stages in Terraform's work.

**Comment by Lasering** [comment] 2018-03-24 01:04
I understand why you would implement it statically, that is, without having to compute it. However the documentation is lacking when it concerns stating what is interpolatable and what is not. The closest I can find is:

> Embedded within **strings** in Terraform, whether you're using the Terraform syntax or JSON syntax, you can interpolate other values.

In other places of the documentation, one finds it has to interpolate a variable containing a list inside a string in order to set a parameter of type list. So it isn't farfetched to assume one can interpolate a variable inside a string to set a parameter of type boolean.

My real-world use-case is as follows:
I'm implementing a Terraform recipe that launches a Consul infrastructure from ground up. In the process of doing so it generates a random value for the Consul encrypt secret key, and a random value for the acl master token. The terraform commands `plan`, `apply` and `destroy` are being executed in a Continuous Integration runner. This runner is used to manage multiple environments for the deployment of Consul (testing, staging, production). The terraform recipe is also aware of the environment. In a testing environment (which is launched for every merge request performed on the repo containing the terraform recipe) I want to output the values of the encrypt secret key and the acl master token. However in staging and in production I don't want to output the values.

Given the current design choice of sensitive not being interpolatable. I've already implemented a solution. Make the output variables always sensitive and then in the CI show them using `output`. Since the CI know the environment it can make the choice whether to show them or not.

**Comment by apparentlymart** [comment] 2018-03-26 16:46
Thanks for sharing that use-case, @Lasering!

In the next major release the error handling for this situation will be improved to report directly that interpolation expressions are not allowed for this argument, rather than the unhelpful errors reported today. This is due to the fact that we are more tightly integrating the structural configuration language (which defines the syntax for blocks and attributes) with the interpolation language, which allows the single parser to have more context and thus produce better error messages.

The workaround you found here is what I would've suggested too. Another workaround, which may be appropriate in some other situations, is to place the main functionality in a module and instantiate it in two different configurations, where one is for the test environment and the other is for the staging and production environments. This then allows the test environment to differ in whatever ways are necessary without duplicating the main functionality encapsulated in the module.

I'm going to leave this open to remember this use-case, and we'll consider it again as we get to the end of the current configuration language project to understand the tradeoffs of making this setting support interpolation expressions. At the moment my feeling is that we'd rather making this attribute static so we can properly honor it in more contexts, but once we've completed some current refactoring work the impact of a change like this will hopefully be more obvious and so we can make a more informed decision.

**Comment by apparentlymart** [comment] 2018-10-30 18:52
Hi again, @Lasering!

Now that we've merged the work to improve the configuration language for the forthcoming v0.12.0 release, I've confirmed that this situation now produces a more reasonable error message:

```
$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Variables not allowed

  on dynamic-sensitive.tf line 8, in output "output1":
   8:   sensitive = var.sensitive

Variables may not be used here.
```

Reflecting on what I'd said before in this issue, I think it's best for us to retain the rule that sensitive must be set to a literal boolean. If we were to make this dynamic then it would introduce a lot of extra complexity to be able to evaluate this expression in all of the different situations where outputs might be shown, where today they can just look directly at the raw configuration to decide.

Since we now have a proper error message for this situation, I'm going to close this out. Thanks for letting us know about this, and sorry for the long silence while we worked on the config language changes.

**Closed by apparentlymart** 2018-10-30 18:52 UTC
Labels: config, enhancement

**Comment by Lasering** [comment] 2018-10-31 11:42
That is definitely an improvement. But from my point of view it still seems like an easy implementation. The state always stores the output variables (otherwise `terraform output` wouldn't show them), the other commands simply transform each output to a string saying its a sensitive according to the sensitive flag.

If the sensitive flag is set from a variable (aka `var.`) then it can be directly computed from the state. The same applies for an expression using variables like ifs or comparisons. If the sensitive flag is set from a local variable (aka `local.`) you can either disallow that for now, since local variables aren't stored in the state. Or you can compute the right hand side (in compilers speak) of the local variable expression and save that in the state.
