### ISSUE TITLE
TERRAFORM CRASH with import v13

### ISSUE THREAD

**Issue by jbrunetext** [hashicorp/terraform#25211] opened 2020-06-11 12:12 UTC
### Terraform Version
```
mon/terraform$ terraform version
Terraform v0.13.0-beta1
+ provider registry.terraform.io/hashicorp/google v3.25.0
+ provider registry.terraform.io/terraform-providers/google-beta v3.25.0

```

### Terraform Configuration Files

```hcl
module "iam_module_datacomponent" {
  source = "./iam_module_datacomponent"
  for_each = lookup(var.gcp_env_datacomponent, terraform.workspace)
  gcp_team_groups = var.gcp_team_groups
  gcp_project_ids = each.value
}
```

### Crash Output
```
2020/06/10 18:14:53 [TRACE] [walkImport] Entering eval tree: provider["registry.terraform.io/hashicorp/google"]
2020/06/10 18:14:53 [TRACE] eval: *terraform.EvalSequence
2020/06/10 18:14:53 [TRACE] vertex "module.iam_module_datacomponent.var.gcp_project_ids (expand)": visit complete
2020/06/10 18:14:53 [TRACE] eval: *terraform.EvalInitProvider
2020/06/10 18:14:53 [TRACE] vertex "var.gcp_env_all": visit complete
panic: no expansion has been registered for module.iam_module_datacomponent

goroutine 155 [running]:
github.com/hashicorp/terraform/instances.(*expanderModule).moduleInstances(0xc0008897e0, 0xc0006bb380, 0x1, 0x1, 0xc000732b50, 0x0, 0x4, 0xc000152060, 0x6, 0x7f7ca37fe108)
	/home/circleci/project/project/instances/expander.go:267 +0xb72
github.com/hashicorp/terraform/instances.(*Expander).ExpandModule(0xc000889800, 0xc0006bb380, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/project/instances/expander.go:116 +0x108
github.com/hashicorp/terraform/terraform.(*nodeExpandModuleVariable).DynamicExpand(0xc000a94140, 0x23ae440, 0xc0006d6b60, 0x1, 0x1, 0x1)
	/home/circleci/project/project/terraform/node_module_variable.go:42 +0x94
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1d18b20, 0xc000a94140, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:84 +0x4d8
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0000df5c0, 0x1d18b20, 0xc000a94140, 0xc000a94c80)
	/home/circleci/project/project/dag/walk.go:387 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x11d7
```

### Expected Behavior
When i try to import my module , i faced an issue ..

### Actual Behavior
```
terraform import 'module.iam_module_all["gcp_project_dcp_id"].google_project_iam_member.team_dcp_owner' "XXXX-ddp-dcp-dev roles/owner group:XXXXX-ddf-data-component@XXXX.com"
```
i Faced an issue .... .in crash.log
### Steps to Reproduce
terraform import in v13

### Additional Context
i need to unlock my terraform state after the crash.
Terraform Team fix the issue  in branch master but 47 commits to master since this release v0.13.0-beta1

Could you please rebuild an new release of v0.13 with the FIx ???

I try to rebuild the binary go from master but i failed....

### References
https://github.com/hashicorp/terraform/issues/25016

**Comment by jbrunetext** [comment] 2020-06-11 12:17
@jbardin
jbardin
validation test with multiple nested modules
9722686
@jbardin
jbardin
variable ModulePath must return configured path
242a916
@jbardin
jbardin
incorrect early return during module transformer
198c632

**Comment by jbardin** [comment] 2020-06-11 13:31
Hi @jbrunetext, Thanks for filing the issue!

This is a duplicate of #25192, which will be closed when the fix is merged.

**Closed by jbardin** 2020-06-11 13:31 UTC
