### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by magic69** [hashicorp/terraform#5287] opened 2016-02-23 23:50 UTC
Here is the crash log: https://gist.github.com/anonymous/c7cd8495b4646873f204

I got this after forgetting to prefix the comment with a "#", in a "resource "aws_route_table" block, once I added the "#" prefix it was fine:

```
    route {
        cidr_block = "0.0.0.0/0"
        nat_gateway_id = "${_hidden_}"
    }
# route to some VPC
    route {
        cidr_block = "${_hidden_}"
        vpc_peering_connection_id = "_hidden_"
    }
```

TERRAFORM CRASH is a pretty scary message !

**Comment by stack72** [comment] 2016-08-24 13:36
Hi @magic69 

apologies for not getting back to you sooner on this - we have made a LOT of changed to HCL 9the library that caused the panic). Please can you let me know if this is still an issue for you? I can't reproduce this using the 0.7.1 release

Thanks

Paul

**Comment by stack72** [comment] 2016-09-03 14:25
ping @magic69 :)

**Comment by mitchellh** [comment] 2016-12-01 14:28
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!

**Closed by mitchellh** 2016-12-01 14:28 UTC
Labels: bug, provider/aws, waiting-response
