### ISSUE TITLE
Parameter must have values error when trying to update an existing cloudformation stack

### ISSUE THREAD

**Issue by rodlogic** [hashicorp/terraform#5560] opened 2016-03-10 16:40 UTC
I have a cloudformation stack created by terraform. After I modified the stack template, terraform apply fails with the following error:
```
aws_cloudformation_stack.IN-NETWORK: ValidationError: Parameters: [DOMAIN, ENVIRONMENT] must have values
```
It seems that when updating a stack it is not resending the associated parameters (note that the parameter values didn't change at all).

**Comment by radeksimko** [comment] 2016-03-12 11:42
Hi @rodlogic ,
thanks for the report, I'm going to close this as a duplicate of https://github.com/hashicorp/terraform/issues/4913

**Closed by radeksimko** 2016-03-12 11:42 UTC
Labels: bug, provider/aws
