### ISSUE TITLE
Provider version transition problem

### ISSUE THREAD

**Issue by dawidpogorzelski** [hashicorp/terraform#27645] opened 2021-01-31 14:11 UTC
Hello, please find the original issue report here, this seems to be a terraform issue rather than a provider issue:
https://github.com/hashicorp/terraform-provider-google/issues/8297

**Comment by jbardin** [comment] 2021-02-01 14:50
Hi @dawidpogorzelski, thanks for the clear explanation in the linked issue.
This appears to be a duplicate of #27065.

Thanks!

**Closed by jbardin** 2021-02-01 14:50 UTC
Labels: bug, new
