### ISSUE TITLE
FR: subcommands for `lock info` and `take lock`

### ISSUE THREAD

**Issue by bukzor-sentryio** [hashicorp/terraform#34453] opened 2023-12-22 20:52 UTC
### Terraform Version

```shell
n/a -- this affects all versions since v0.15.3
```

### Use Cases

It's possible to manually take a terraform lock or manually find the metadata of an already taken terraform lock, but automating this is hard-to-impossible due to limitations of terraform.
Taking a lock:

```
$ terraform console
> ^Z
zsh: suspended  terraform console
exit code: 146
duration: 13.482 seconds

$ jobs
[1]  + suspended  terraform console

$ kill -9 %1
[1]  + killed     terraform console
```

Viewing lock metadata:

```
$ terraform force-unlock -force -- -1
Failed to unlock state: googleapi: Error 412: At least one of the pre-conditions you specified did not hold., conditionNotMet
Lock Info:
  ID:        1111111111111111
  Path:      gs://my-bucket/my-demo/env.buck/dev/slice-0-project/default.tflock
  Operation: OperationTypeInvalid
  Who:       buck@localhost.lan
  Version:   1.6.4
  Created:   2023-12-22 20:12:22.676036 +0000 UTC
  Info:
```

Note that there's an "Info" field that (presumably) was meant to be able to hold some information, but there's no possible way to read nor write this field via the commandline, nor via the (completely `internal`) golang API.

### Attempted Solutions

1. **Creating self-owned tooling*: This was possible prior to v0.15.3, and even had [a working implementation](https://github.com/minamijoyo/tflock), but is no longer possible.  Comments in the terragrunt codebase provide some extra context: [1](https://github.com/gruntwork-io/terragrunt/blob/master/terraform/doc.go#L5-L9) [2](https://github.com/gruntwork-io/terragrunt/blob/master/go.mod#L20-L22)
2. **Void my warranty**: The code I want to link against is  [clistate.NewLocker](https://github.com/hashicorp/terraform/blob/main/internal/command/clistate/state.go#L85), which is notably quite stable as of 2023. I'm happy deal with ensuing difficulties due to using an un-exported API, with explicitly no support from hashicorp team, but I find no way to implement this, technically.
3. **Using `terraform` CLI`**: although the commandline will _incidentally_ take the state lock and _incidentally_ show the lock metadata, there's no explicit command for these actions. It's possible to wrap the terraform CLI to normalize the commandline's behavior but the result is highly dependent on the vaguaries of the current CLI implementation and error behavior. 

I'm currently resigned to using option 3 above in my systems. I'm parsing the stderr of `terraform force-unlock --force -- -1` to implement `terraform-lock-info`, and I've written an expect script to exit `terraform console` ungracefully to implement `terraform-lock-acquire`. I'm now able to automate un-locking via a combination of `terraform-lock-info` and the standard `terraform force-unlock` command.

### Proposal

I have many ideas to improve this situation, but they're all either against current terraform-dev precedent, or technically beyond my grasp and a maintenance nightmaie to boot. 

I hope that you will have a better recommendation than any of mine.

1. **un-`internal`ize the Locker interface**: As far as I can see, this would be the first reversal of the policy implemented in v0.15.3, so I don't imagine this will be acceptable to the maintainers, regardless of how stable the interface is.
2. **add explicit `terraform lock info` and `terraform lock acquire` subcommands**: I know that the state lock is not intended to be used by end-users, so again I imagine this will be unacceptable. However, the fact remains that it's an important part of end-user UI/UX that currently is impossible to automate, and so I request a reconsideration of this policy.
3. **a "contrib" package inside hashicorp/terraform repo**? This would allow for community-maintained tooling that is allowed to link against `github.com/hashicorp/terraform/internal/command/clistate`
4. **a new`terraform-state-lock` provider**? I can imagine terraform resources that implement the lock-acquire and lock-info behaviors, but I can't imagine how automation and scripting would make use of it.
5. **fork/submodule/copy terraform code**: this seems the most maintainable of the workarounds that don't require upstream cooperation but still would be a maintenance burden of indeterminate size and clearly a wart on my systems

**Comment by jbardin** [comment] 2023-12-23 00:06
Duplicate of #30277

**Closed by jbardin** 2023-12-23 00:06 UTC
Labels: enhancement, new
