### ISSUE TITLE
Terraform Chef provisioner enhancement - Check tainted resource on chef server

### ISSUE THREAD

**Issue by acornies** [hashicorp/terraform#4883] opened 2016-01-28 18:08 UTC
When dealing with tainted resources, Terraform destroys the resource before recreating it which makes sense. However, if that resource uses the Chef provisioner (chef server) and fails, it would be nice if Terraform could verify the tainted resources directly on the Chef server and delete it from there as well as deleting the resource from the provider.

I'm always having to delete failed resources/nodes from the chef server before executing terraform again. Since we pass chef client credentials as arguments anyway, why not check to see if the chef server needs to be cleansed of tainted resources as well?

Thanks,
Andrew

**Comment by svanharmelen** [comment] 2016-01-29 10:23
I'll be closing this one as a duplicate of #3605. So please follow #3605 for any discussion and/or changes around this topic...

**Closed by svanharmelen** 2016-01-29 10:23 UTC
Labels: enhancement, provisioner/chef
