### ISSUE TITLE
Detect incorrect directive syntax {% and provide appropriate error message

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#21359] opened 2019-05-19 22:49 UTC
I followed https://www.terraform.io/docs/configuration/expressions.html#directives and came to a conclusion that iterating over maps in templates doesn't seem to be working.

I don't know if it's supposed to be working, but if not then the error message doesn't make it obvious.

### Terraform Version

0.12 master (`f199030739856971c1de542cd35aa52db9a08399`)

### Terraform Configuration Files

```hcl
locals {
  list_var = ["one", "two", "three"]
  map_var = {
    first  = "hello world"
    second = "hi there"
    third  = "woof!"
  }
}

resource "local_file" "vcsa" {
  content = templatefile("${path.module}/example.tpl.txt", {
    list_var = local.list_var
    map_var  = local.map_var
  })
  filename = "${path.module}/example.txt"
}
```

`example.tpl.txt`
```txt
Map:
{% for key, value in map_var }
key = ${key}
value = ${value}
{% endfor ~}

List:
{% for element in list_var }
${element},
{% endfor ~}
```

### Expected Behavior

Created a new file `example.txt` with the following content:

```txt
Map:
key = first
value = hello world
key = second
value = hi there
key = third
value = woof!

List:
one,
two,
three
```

### Actual Behavior

```
Error: Invalid function argument

  on main.tf line 11, in resource "local_file" "vcsa":
  11:   content = templatefile("${path.module}/example.tpl.txt", {
  12:
  13:
  14:
    |----------------
    | local.list_var is tuple with 3 elements
    | local.map_var is object with 3 attributes

Invalid value for "vars" parameter: vars map does not contain key "key",
referenced at ./example.tpl.txt:3,9-12.
```

The snippet in the diagnostic could be improved also (and display code for arguments on lines `12+`), but that's unrelated to this issue, I think.

### Steps to Reproduce

`terraform apply`

**Comment by apparentlymart** [comment] 2019-05-20 00:48
r.e. the diagnostic message: this is the second time we've seen diagnostic messages with missing lines... :thinking: seems like there's a bug in the scanning code that we use to identify lines to show, but I'm not sure what triggers it since it's not happening _every_ time.

**Comment by apparentlymart** [comment] 2019-05-20 01:12
I'm not sure what's going on here yet, but this error comes from [the reference pre-check](https://github.com/hashicorp/terraform/blob/f199030739856971c1de542cd35aa52db9a08399/lang/funcs/filesystem.go#L102-L110), which suggests that `expr.Variables` is not behaving correctly in this situation.

The expected behavior for `Variables` is to return only traversals that access the _root_ scope. Any references to temporary local names created in `for` expressions and `for` template sequences should be excluded.

When participating in a tree walk, `ForExpr` (which is the AST node for both `for` expressions and template `for` sequences) [introduces a `ChildScope` node](https://github.com/hashicorp/hcl2/blob/4b22149b7cef7272799ac85dca150e553d667971/hcl/hclsyntax/expression.go#L1197-L1200) to signal that some names are hidden by a nested scope. It seems like for some reason the reference to `key` inside the block is not being [detected as being hidden](https://github.com/hashicorp/hcl2/blob/4b22149b7cef7272799ac85dca150e553d667971/hcl/hclsyntax/variables.go#L43-L45) by the child scope, which suggests perhaps a tree walk bug.

It'd be interesting to see if this affects `for` expressions in the main language too, since most of the implementation is shared. Terraform itself does a similar pre-check of references before evaluation in order to know what it needs to load from the state, so if this bug were present in `for` expressions I'd expect to see a failure that suggests that the name `key` is being understood as a resource type.

**Comment by radeksimko** [comment] 2019-05-20 14:00
I guess it helps to use the correct syntax. 🤦‍♂ 

I just spotted a typo - swapped `%` and `{` in my example above.

Here's a template which works just fine, for both lists and maps:
```
Map:
%{ for key, value in map_var }
key = ${key}
value = ${value}
%{ endfor ~}

List:
%{ for element in list_var }
${element},
%{ endfor ~}
```

Should I keep this issue open, so we can improve the detection and/or error message?

**Comment by apparentlymart** [comment] 2019-05-20 14:53
Oh, heh... I stared at those examples up and down while thinking about this yesterday too and didn't spot it. :roll_eyes: 

I'm not sure what better we could do in that situation since the user might want to literally generate `{%` in the output, so it wouldn't be reasonable to flag it as an error -- we'd need to provide a way to escape it if you really meant it, etc.

Since HCL would've seen those incorrect template sequences as just literal text rather than AST nodes I don't know that we have enough information even to hint about why `key` would be detected as a variable here. The current error message is showing all of the available information at the point of the check. :thinking: 

I think the main actionable thing here is to see if we can understand why sometimes the diagnostic renderer seems to fail to display some of the source lines. But we don't really have any leads on that yet either, so maybe best to make a fresh issue to track it and then we can look into it more after the initial release (since it seems to be an edge case, and seems to be only cosmetic).

**Comment by apparentlymart** [comment] 2019-06-06 17:25
I have made #21636 to represent the diagnostic printing problem, which I've now seen a few more times intermittently. I'm going to close this one out because unfortunately I can't think of anything specific we could do to improve the detection of this particular class of mistake.

**Closed by apparentlymart** 2019-06-06 17:25 UTC
Labels: config, enhancement
