### ISSUE TITLE
Error: get directory at '': Get "": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by luizfelipefb** [hashicorp/terraform#27698] opened 2021-02-05 19:47 UTC
### Terraform Version

```
0.13.6
```

### Terraform Configuration Files

```terraform
resource "tls_private_key" "default" {
  algorithm = "RSA"
}

resource "acme_registration" "default" {
  account_key_pem = tls_private_key.default.private_key_pem
  email_address   = var.email_address
}

resource "random_password" "default" {
  for_each = var.certificates
  length   = 64
  special  = false
  keepers  = { for value in each.value : value => each.key }
}

resource "acme_certificate" "default" {
  for_each                  = var.certificates
  account_key_pem           = acme_registration.default.account_key_pem
  key_type                  = 2048
  common_name               = each.key
  subject_alternative_names = each.value
  certificate_p12_password  = random_password.default[each.key].result
  min_days_remaining        = var.min_days_remaining

  dns_challenge {
    provider = "godaddy"
  }
}
```

### Debug Output

```
2021-02-05T19:50:01.798Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/random/3.0.1/linux_amd64/terraform-provider-random_v3.0.1_x5 pid=168
2021-02-05T19:50:01.799Z [DEBUG] plugin: plugin exited
2021/02/05 19:50:01 [TRACE] [walkRefresh] Exiting eval tree: provider["registry.terraform.io/hashicorp/random"] (close)
2021/02/05 19:50:01 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/random\"] (close)": visit complete
2021/02/05 19:50:01 [TRACE] GRPCProvider: Close
2021-02-05T19:50:01.804Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-02-05T19:50:01.808Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/tls/3.0.0/linux_amd64/terraform-provider-tls_v3.0.0_x5 pid=177
2021-02-05T19:50:01.808Z [DEBUG] plugin: plugin exited
2021/02/05 19:50:01 [TRACE] [walkRefresh] Exiting eval tree: provider["registry.terraform.io/hashicorp/tls"] (close)
2021/02/05 19:50:01 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/tls\"] (close)": visit complete
2021/02/05 19:50:01 [TRACE] eval: *terraform.EvalReadState
2021/02/05 19:50:01 [TRACE] EvalReadState: reading state for acme_registration.default
2021/02/05 19:50:01 [TRACE] UpgradeResourceState: schema version of acme_registration.default is still 1; calling provider "acme" for any other minor fixups
2021/02/05 19:50:01 [TRACE] GRPCProvider: UpgradeResourceState
2021/02/05 19:50:01 [TRACE] eval: *terraform.EvalRefreshDependencies
2021/02/05 19:50:01 [TRACE] eval: *terraform.EvalRefreshLifecycle
2021/02/05 19:50:01 [TRACE] eval: *terraform.EvalRefresh
2021/02/05 19:50:01 [TRACE] GRPCProvider: ReadResource
2021/02/05 19:50:01 [ERROR] eval: *terraform.EvalRefresh, err: get directory at '': Get "": unsupported protocol scheme ""
2021/02/05 19:50:01 [ERROR] eval: *terraform.EvalSequence, err: get directory at '': Get "": unsupported protocol scheme ""
2021/02/05 19:50:01 [TRACE] [walkRefresh] Exiting eval tree: acme_registration.default
2021/02/05 19:50:01 [TRACE] vertex "acme_registration.default": visit complete
2021/02/05 19:50:01 [TRACE] vertex "acme_registration.default": dynamic subgraph encountered errors
2021/02/05 19:50:01 [TRACE] vertex "acme_registration.default": visit complete
2021/02/05 19:50:01 [TRACE] vertex "acme_registration.default (expand)": dynamic subgraph encountered errors
2021/02/05 19:50:01 [TRACE] vertex "acme_registration.default (expand)": visit complete
2021/02/05 19:50:01 [TRACE] dag/walk: upstream of "acme_certificate.default (expand)" errored, so skipping
2021/02/05 19:50:01 [TRACE] dag/walk: upstream of "output.password (expand)" errored, so skipping
2021/02/05 19:50:01 [TRACE] dag/walk: upstream of "output.pfx_base64 (expand)" errored, so skipping
2021/02/05 19:50:01 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/vancluever/acme\"] (close)" errored, so skipping
2021/02/05 19:50:01 [TRACE] dag/walk: upstream of "root" errored, so skipping

2021-02-05T19:50:01.820Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
Error: get directory at '': Get "": unsupported protocol scheme ""


2021-02-05T19:50:01.824Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/vancluever/acme/2.0.0/linux_amd64/terraform-provider-acme_v2.0.0 pid=159
2021-02-05T19:50:01.824Z [DEBUG] plugin: plugin exited
```

### Expected Behavior

Manage the certificates

### Actual Behavior

```
Error: get directory at '': Get "": unsupported protocol scheme ""
```

### Steps to Reproduce

```
terraform plan
```

**Comment by mildwonkey** [comment] 2021-02-08 14:10
Hi @luizfelipefb ,
I am sorry you've coma across this strange issue! Unfortunately there is not enough information in this ticket for us to troubleshoot it. Can you please update this with a complete configuration which we can use to reproduce the issue, and your entire trace logs (in a gist, please, with any sensitive information removed)?

**Comment by luizfelipefb** [comment] 2021-02-08 14:19
Hello @mildwonkey 

Thanks for the reply, I've just (about 30 minutes ago) found out what the error is. It's missing the provider configuration in the module:

```
provider "acme" {
  server_url = "https://acme-v02.api.letsencrypt.org/directory"
}

...
```

Nevertheless, the error output didn't help at all to find this out. I just had an insight when running just the module alone and it asked me to input the acme registry sever URL.

I'll keep this open in case you want to tackle the error output better, but you can close it if you fell it's best.

tnx.

**Comment by mildwonkey** [comment] 2021-02-08 16:03
Good find, and thanks for the update! That's something the provider itself should be catching and returning and error, but it looks like it is not validating the provider config. 

If you omit the `server_url` parameter entirely, Terraform gives a helpful error message:

```
Error: Missing required argument

  on main.tf line 9, in provider "acme":
   9: provider "acme" {}

The argument "server_url" is required, but no definition was found.
```

If you'd like, you can open an issue with the `acme` provider and let them know about this. There's nothing we can do here - terraform has no way of knowing that an empty string _isn't_ valid - so I am going to close this issue. Thanks!

**Closed by mildwonkey** 2021-02-08 16:03 UTC
Labels: bug, new, waiting-response
