### ISSUE TITLE
how to manage AWS_EBS_VOLUME 

### ISSUE THREAD

**Issue by julienlavergne** [hashicorp/terraform#2043] opened 2015-05-22 10:08 UTC
I have a question: in my AWS infrastructure I want to attach a separated ebs volume (created with AWS_EBS_VOLUME resource) to one EC2 instance (created by AWS_INSTANCE resource); But I don't find any information how to do that; 

The documentation doesn't have an example. Is it already possible?

Thx

**Comment by phinze** [comment] 2015-05-22 13:26
@julienlavergne unless I'm missing something, we don't have support for this yet.

Seems like we could use an `aws_volume_attachment` resource.

@catsby thing you might be able to swoop in to the rescue? Seems like it should be a relatively simple one. Maybe even @cbednarski would like to jump in and take a stab at it. :dancers:

**Comment by julienlavergne** [comment] 2015-05-22 13:31
That would be great and I think it can answer to many simple cases (ensuring ebs resources persistence when you modify the infrastructure).
 

-- 
Julien Lavergne
Sent with Airmail

On May 22, 2015 at 3:26:44 PM, Paul Hinze (notifications@github.com) wrote:

@julienlavergne unless I'm missing something, we don't have support for this yet.

Seems like we could use an aws_volume_attachment resource.

@catsby thing you might be able to swoop in to the rescue? Seems like it should be a relatively simple one. Maybe even @cbednarski would like to jump in and take a stab at it.

**Comment by uxp** [comment] 2015-05-22 16:18
Is this a duplicate of #2019 ?

**Comment by uxp** [comment] 2015-05-22 16:20
I think this is an example of the behavior we're expecting:

```
resource "aws_instance" "example" {
	ami = "ami-0ba6873b"
	instance_type = "t2.medium"
	subnet_id = "${aws_subnet.example.id}"
	key_name = "${aws_key_pair.example.key_name}"
	security_groups = [
		"${aws_security_group.example.id}"
	]
	ebs_block_device = "${aws_ebs_volume.example.id}"
}

resource "aws_ebs_volume" "example" {
	availability_zone = "us-west-2b"
	encrypted = false
	iops = 500
	size = 250
	type = "io1"
}
```

note that `ebs_block_device` within the `aws_instance` resource is invalid syntax against v0.5.1

**Comment by catsby** [comment] 2015-05-22 16:22
@uxp `ebs_block_device` in an `aws_instance` configuration is a block of attributes: 

- https://terraform.io/docs/providers/aws/r/instance.html#block-devices

I'm working on this:

```javascript
resource "aws_instance" "web" {
	ami = "ami-21f78e11"
	instance_type = "t1.micro"
	tags {
		Name = "HelloWorld"
	}
}

resource "aws_ebs_volume" "example" {
	availability_zone = "${aws_instance.web.availability_zone}"
	size = 1
}

resource "aws_volume_attachment" "ebs_att" {
  device_name = "/dev/sdh"
	volume_id = "${aws_ebs_volume.example.id}"
	instance_id = "${aws_instance.web.id}"
}
```

**Comment by uxp** [comment] 2015-05-22 16:24
Oh perfect. Yes. I know the correct syntax, I was trying to convey the behavior one might expect given an `aws_instance` resource and an `aws_ebs_volume` resource, which logically can be paired in some manner.

Looks like I'm late to the party anyways. Thanks, and sorry for the noise.

**Comment by catsby** [comment] 2015-05-22 16:25
not noise, clarity that my approach is what you're expecting :smile:

**Comment by julienlavergne** [comment] 2015-05-22 16:56
Just i talked to phinze and the work is in progress :-)

Thx dev team


Julien

**Comment by julienlavergne** [comment] 2015-05-22 16:56
I read that and that seems perfect as solution ;)

**Comment by julienlavergne** [comment] 2015-05-22 16:57
the @catsby approach is really good

**Comment by julienlavergne** [comment] 2015-05-23 19:56
any commit?

**Comment by catsby** [comment] 2015-05-26 22:03
Closing. Follow #2050 if you're interested :smile:

**Closed by catsby** 2015-05-26 22:03 UTC
Labels: enhancement, provider/aws
