### ISSUE TITLE
terraform login fails on 1.2.5 and previous versions with 'failed to create API client' with windows + powershell

### ISSUE THREAD

**Issue by sebastiangug** [hashicorp/terraform#31438] opened 2022-07-14 11:10 UTC
Steps to reproduce: 

`terraform login`

`yes`

then paste the token and press return. 

result: 
```
Token for app.terraform.io:
  Enter a value:

╷
│ Error: Failed to create API client: Get "https://app.terraform.io/api/v2/ping": net/http: invalid header field value "Bearer \x16" for key Authorization
│
│
╵
```

**Comment by crw** [comment] 2022-07-14 23:47
Thanks for this report.

**Comment by sebastiangug** [comment] 2022-07-15 08:29
Just to add to this -- I've manually created the file at that location and everything works fine -- it just seems it has issues with the creation via CLI, irrelevant if you start it as an administrator or not.

**Comment by LaurenceNairne** [comment] 2022-07-31 15:44
Still present on v1.2.6 though not surprising considering the issue is still open :)

**Comment by kylesmmnsfiserv** [comment] 2022-12-22 18:35
I had the same problem. The powershell terminal inside VSC was not working as expected. So I tried running the same login command in the windows CMD prompt and it worked as expected.

**Comment by tshortess** [comment] 2022-12-26 20:59
@sebastiangug - Can you confirm that you encountered this issue in VS Code (or another IDE) and not Powershell? 

If so, this is not a bug with Terraform. I ran into the same issue with Powershell in VS Code, and it is because of how Powershell in VS Code is configured. With the default configuration, I cannot `Ctrl+v` (paste) into the terminal. Instead, I have to right click in the VS Code terminal after copying the token (see attached image for configuration details of right click in the Powershell terminal in VS Code). When I did that, `terraform login` worked as expected.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/89649790/209582589-2ac84f61-132f-4475-a549-86b649dc08a6.png">

**Comment by balavennela** [comment] 2024-04-19 12:48
It is working. Thankyou

**Comment by crw** [comment] 2024-04-19 20:54
Closing as this appears to be resolved.

**Closed by crw** 2024-04-19 20:54 UTC
Labels: bug, windows, powershell, waiting for reproduction, v1.2
