### ISSUE TITLE
Terraform crashes if related path to nested module exists

### ISSUE THREAD

**Issue by askoriy** [hashicorp/terraform#22973] opened 2019-10-02 14:42 UTC
Terraform crashes if related path between modules specified in source

### Terraform Version

```
Terraform v0.12.9
```

### Terraform Configuration Files

```hcl
$ cat /path-to-module/main.tf
provider "null" {}

module "shared" {
    source = "./shared/"
}

$ cat /path-to-module/shared/sharedmodule.tf
provider "null" {}
```

### Crash Output
```
root@ubuntu-bionic:~/workingdir# terraform init -from-module=/path-to-module/
Copying configuration from "/path-to-module/"...
panic: Rel: can't make /path-to-module/shared relative to

goroutine 1 [running]:
github.com/hashicorp/terraform/internal/initwd.DirFromModule(0x1d94c4d, 0x1, 0xc000400940, 0x12, 0x7ffcd847679d, 0x10, 0xc000411610, 0x21f1de0, 0xc000473260, 0x18, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/internal/initwd/from_module.go:269 +0x364c
github.com/hashicorp/terraform/command.(*Meta).initDirFromModule(0xc0004761c0, 0x1d94c4d, 0x1, 0x7ffcd847679d, 0x10, 0x21f1de0, 0xc000473260, 0x1, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/meta_config.go:252 +0x19a
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0004761c0, 0xc00003a1a0, 0x1, 0x1, 0xc000410fe0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:148 +0x2992
github.com/mitchellh/cli.(*CLI).Run(0xc0003fd7c0, 0xc0003fd7c0, 0xc000221d90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:235 +0xb66
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:36 +0x3b



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected Behavior

Terraform 0.11.14 works fine with this config. Both /path-to-module/main.tf and /path-to-module/shared/sharedmodule.tf files are copied to working directory; correct link from .terraform/modules/ are created.
The same expected from Terraform v0.12.9

### Actual Behavior
/path-to-module/main.tf and /path-to-module/shared/sharedmodule.tf files are copied to working directory, but .terraform/modules/ link is not created.
Terraform crashes. Replacing submodule path to absolute `source = "/path-to-module/shared/"` make Terraform to not crash.

### Steps to Reproduce
1. Create two modules and specify related path to second module as source in first module
2. Run `terraform init -from-module=/path-to-module/` from empty directory

**Comment by anoora17** [comment] 2019-10-04 16:16
terraform-provider-template_v2.1.2_x4
12:14:31  
12:14:31  
12:14:31  
12:14:31  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
12:14:31  
12:14:31  Terraform crashed! This is always indicative of a bug within Terraform.
12:14:31  A crash log has been placed at "crash.log" relative to your current
12:14:31  working directory. It would be immensely helpful if you could please
12:14:31  report the crash with Terraform[1] so that we can fix this.
12:14:31  
12:14:31  When reporting bugs, please include your terraform version. That
12:14:31  information is available on the first line of crash.log. You can also
12:14:31  get it by running 'terraform --version' on the command line.
12:14:31  
12:14:31  [1]: https://github.com/hashicorp/terraform/issues
12:14:31  
12:14:31  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by danieldreier** [comment] 2020-06-06 00:23
I'm going to close this because https://github.com/hashicorp/terraform/issues/23010 seems to be the same issue and I've reproduced it there already. Thank you for reporting this!

**Closed by danieldreier** 2020-06-06 00:23 UTC
Labels: bug, cli, crash, v0.12
