### ISSUE TITLE
Result of sha256 (and other hash functions) should not be sensitive

### ISSUE THREAD

**Issue by mcfedr** [hashicorp/terraform#31583] opened 2022-08-05 12:55 UTC
Basically would be nice if the results of hash functions were never sensitive, regardless of the inputs

At the moment, if you put a sensitive value in the input, the output is also sensitive, this makes sense for most terraform resources/functions - but the whole point of the hash function is that the original value cannot be recovered and we have something that can be safely stored/compared/etc.

### Terraform Version

```
Terraform v1.2.4
```

### Terraform Configuration Files
```terraform
variable "access_token" {
  type      = string
  sensitive = true
}

output "hash" {
  value = sha256(var.access_token)
}
```

### Expected Behavior

Value of `hash` should be displayed in outputs

### Actual Behavior

Its hidden and marked as sensitive

### Additional Context

There is probably a good case to be made that `md5` should not be changed, and probably `sha1` too. But `sha256`, `sha512` and `bcrypt` functions could definitely work in this way, and the matching `base64...` and `file...` functions.

**Comment by jbardin** [comment] 2022-08-05 13:09
Duplicate of #27337

Hi @mcfedr,

Since there is no single global rule as to what constitutes a transformation which can always drop sensitivity (technically even sha512 can be abused when combined with other useful information), functions will always preserve sensitivity by default. The `nonsensitive` function was added to allow the user to explicitly choose when sensitivity should be stripped from a value.

Thanks!

**Closed by jbardin** 2022-08-05 13:09 UTC
Labels: bug, new
