### ISSUE TITLE
Terraform is not supporting Aurora Postgres DB creation

### ISSUE THREAD

**Issue by prabhakar81** [hashicorp/terraform#15803] opened 2017-08-14 15:37 UTC
Hi,

I am trying to create Aurora Postgres database using terraform but I don't see any engine parameter in aws_rds_cluster and if i give any value for that parameter then i keep on getting

Errors:

  * aws_rds_cluster.default: "engine": this field cannot be set

If i don't provide this parameter then it ends up creating Aurora MySQL database.

**Comment by nbering** [comment] 2017-08-14 16:52
Engine is documented as an attributed (read-only computed value), not an argument (parameter).

https://www.terraform.io/docs/providers/aws/r/rds_cluster.html

The AWS documentation shows postgres as a preview feature. I suspect to provider doesn't have this implemented, yet.

Terraform was recently restructured to move providers out of core. I'd suggest raising this at the AWS provider's new home, [terraform-providers/terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws).

**Comment by radeksimko** [comment] 2017-08-15 08:08
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/1412

**Closed by radeksimko** 2017-08-15 08:08 UTC
