### ISSUE TITLE
Inconsistency of Terraform release after 0.12.0-alpha3

### ISSUE THREAD

**Issue by vvitayau** [hashicorp/terraform#19617] opened 2018-12-11 21:59 UTC
The file naming convention of the release started to change and redundant after 
https://releases.hashicorp.com/terraform/0.12.0-alpha3/
and https://releases.hashicorp.com/terraform/0.12.0-alpha4/

compared to the other releases

**Comment by jbardin** [comment] 2018-12-11 22:03
Duplicate of #19588

**Closed by jbardin** 2018-12-11 22:03 UTC
