### ISSUE TITLE
'depends_on' appears to have no effect. What am I doing wrong?

### ISSUE THREAD

**Issue by fligi7** [hashicorp/terraform#24588] opened 2020-04-07 21:48 UTC
### Terraform Version
```
Terraform v0.12.24
+ provider.aws v2.54.0
```

### Terraform Main.tf
```hcl
resource "aws_volume_attachment" "student_linux_data_ebs_attach" {
  count = var.student_instance_count
  instance_id = aws_instance.student_linux[count.index].id
  volume_id = aws_ebs_volume.student_linux_data_ebs[count.index].id
  device_name = var.student_linux_ebs_attach_location
}
```

### Terraform Outputs.tf
```hcl
output student_linux_instances_info {
  depends_on = [aws_volume_attachment.student_linux_data_ebs_attach]
  value = [
    for i in aws_instance.student_linux: {
      "AMI (Source)":i.ami,
      "Instance Type":i.instance_type,
      "Instance ID":i.id,
      "Availability Zone":i.availability_zone,
...
      "Device Info":{
        "Root Device" = {
          "Delete On Termination":i.root_block_device[0].delete_on_termination
          "Volume Type":i.root_block_device[0].volume_type
          "Volume Size":i.root_block_device[0].volume_size
        }
        "EBS Device" = {
          "Delete on Termination":element(tolist(i.ebs_block_device[*].delete_on_termination), 0)
          "Device Name":element(tolist(i.ebs_block_device[*].device_name), 0)
          "Volume Type":element(tolist(i.ebs_block_device[*].volume_type), 0)
          "Volume Size":element(tolist(i.ebs_block_device[*].volume_size), 0)
        }
...
```

### Expected Behavior
Terraform waits for the referenced aws_volume_attachment to complete before attempting to query the volumes attached to the Instance.

### Actual Behavior
Terraform appears to not wait until the EBS volume is attached to the Instance before querying it, thus resulting in the below errors:

```
Error: Error in function call

  on outputs.tf line 57, in output "student_linux_instances_info":
  57:           "Delete on Termination":element(tolist(i.ebs_block_device[*].delete_on_termination), 0)
    |----------------
    | i.ebs_block_device is empty set of object

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on outputs.tf line 58, in output "student_linux_instances_info":
  58:           "Device Name":element(tolist(i.ebs_block_device[*].device_name), 0)
    |----------------
    | i.ebs_block_device is empty set of object

Call to function "element" failed: cannot use element function with an empty
list.

...
```

If I wait a few seconds and issue a `terraform refresh`, all outputs are properly queried and retrieved.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Information
What am I doing wrong here?

**Comment by danieldreier** [comment] 2020-04-08 01:28
Hello @fligi7 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. 

2. Alternatively, if you can provide a simplified, full example here of a terraform config that I can run to reproduce an issue in which explicit output dependencies are ignored, I may be able to confirm that this is a defect in core or the AWS provider and get it on our backlog.

I'm going to close this for now, because I think the community forum is the right approach. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you'd rather work up a repro case here.

**Closed by danieldreier** 2020-04-08 01:28 UTC
