### ISSUE TITLE
v0.13.2 fails to import resources when interpolation is used in provider in module

### ISSUE THREAD

**Issue by demonemia** [hashicorp/terraform#26211] opened 2020-09-10 20:02 UTC
### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.26.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.1
```

### Terraform Configuration Files

[Sample Repo](https://github.com/demonemia/terraform-import-failure)  

### Debug Output

[Log file](https://github.com/demonemia/terraform-import-failure/blob/master/trace.log)  

### Expected Behavior

Terraform should import the existing resource into the state file  

### Actual Behavior

Statefile is not updated, error message is displayed.  

```
> terraform import module.resource_group_1.azurerm_resource_group.resource_group /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group-1

module.resource_group_1.azurerm_resource_group.resource_group: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group-1"...
module.resource_group_1.azurerm_resource_group.resource_group: Import prepared!
  Prepared azurerm_resource_group for import
module.resource_group_1.azurerm_resource_group.resource_group: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group-1]

Error: Invalid provider configuration

  on resource_group_1/resource_group_1.tf line 17:
  17: provider kubernetes {

The configuration for
module.resource_group_1.provider["registry.terraform.io/hashicorp/kubernetes"].kubernetes_cluster
depends on values that cannot be determined until apply.
```

### Steps to Reproduce

`terraform init`  
`terraform import module.resource_group_1.azurerm_resource_group.resource_group /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group-1`  
or
`terraform import module.resource_group_1.null_resource.test_resource test`  

### Additional Context

`terraform plan` works

This was also an issue in terraform v0.13.0.  

### References

#25816

**Comment by kimor79** [comment] 2020-09-14 16:29
i think this is similar to what i'm experiencing in https://github.com/hashicorp/terraform/issues/25574

**Comment by alisdair** [comment] 2020-09-18 16:15
Thanks for reporting this, @demonemia, and thanks for the reproduction repository. I'm able to reproduce the issue with Terraform 0.13.3.

I'm not sure what the cause is, but there are several other similar import bugs due to the import process not fully evaluating the configuration. Possibly related: #26258.

**Comment by jdtommy** [comment] 2020-10-05 21:34
Still going on in 13.4 with AWS and trying to import iam roles and route 53 zones

**Comment by lkwg82** [comment] 2020-10-06 12:55
@jdtommy Did it work?

Is there some workaround?

**Comment by fernandoiury** [comment] 2020-10-07 17:28
I had a similar issue, but with kubernetes provider
```
terraform import module.XXXXXXX.kubernetes_namespace.istio_system istio-system

Error: Invalid provider configuration

  on ../../modules/XXXXXXX/main.tf line 22:
  22: provider "kubernetes" {

The configuration for
module.XXXXXXXXXX.provider["registry.terraform.io/hashicorp/kubernetes"].YYYYYYY
depends on values that cannot be determined until apply.
```

And my workaround was changing the provider from
```
provider "kubernetes" {
  load_config_file = false
  version          = " ~> 1.11.0"

  host                   = "https://${module.XXXXXXXXXX.endpoint}"
  cluster_ca_certificate = base64decode(module.XXXXXXXX.cluster_ca_certificate)
  token                  = module.XXXXXXXXXXX.access_token
}
```
to
```
provider "kubernetes" {
  load_config_file = true
  version          = " ~> 1.11.0"
}
```

the import worked and I switched the code back after.

**Comment by cloud-rocket** [comment] 2020-10-09 17:57
@fernandoiury, same workaround for did not work for me

**Comment by swetli** [comment] 2020-10-14 06:31
Just had the same issue with kubernetes and helm providers. My workaround was to temporarily comment the entire "offending" provider blocks, do the import then uncomment them back.
Normal terraform operations were possible after that.

**Comment by lkwg82** [comment] 2020-10-14 07:29
> Just had the same issue with kubernetes and helm providers. My workaround was to temporarily comment the entire "offending" provider blocks, do the import then uncomment them back.
> Normal terraform operations were possible after that.

This seems to me very suspicious. Is it another bug?

**Comment by swetli** [comment] 2020-10-14 07:45
> This seems to me very suspicious. Is it another bug?

No idea but I did get the errors:
```
The configuration for provider["registry.terraform.io/hashicorp/kubernetes"]
depends on values that cannot be determined until apply.

...

The configuration for provider["registry.terraform.io/hashicorp/helm"]
depends on values that cannot be determined until apply.
```
Both provider use interpolation with the base64decode function for the certificates

**Comment by brikis98** [comment] 2020-10-15 11:51
Same issue here. We have a module `foo` with a nested `provider` block, and that `provider` block depends on a resource (note: code snippet below is simplified):

```hcl
provider "aws" {
  alias  = "logs"
  assume_role {
    role_arn = "arn:aws:iam::${aws_organizations_account.child_accounts["logs"].id}:role/foo"
  }
}
```

We use module `foo` in some code, along with several other modules such as `bar`:

```hcl
module "foo" {
  source = "../foo"
  # ... params ...
}

module "bar" {
  source = "../bar"
  # ... params ...
}
```

`plan` and `apply` work fine. However, when I try to run `import` on _on a resource in `bar`_ (i.e., something totally unrelated to `foo`) with Terraform 0.13.4, I get this error:

```
$ terraform import 'module.bar.aws_iam_user.xxx' 'xxx'
module.bar.aws_iam_user.xxx xxx
module.bar.aws_iam_user.xxx: Importing from ID "xxx"...
module.bar.aws_iam_user.xxx: Import prepared!
  Prepared aws_iam_user for import
module.bar.aws_iam_user.xxx: Refreshing state... [id=xxx]

Error: Invalid provider configuration

  on ../../modules/foo/main.tf line 59:
  59: provider "aws" {

The configuration for
module.foo.provider["registry.terraform.io/hashicorp/aws"].logs
depends on values that cannot be determined until apply.
```

**Comment by brikis98** [comment] 2020-10-15 11:55
BTW, this looks fairly similar to https://github.com/hashicorp/terraform/issues/13018, although it seems 0.13 has made that issue even worse.

**Comment by brikis98** [comment] 2020-10-15 13:27
Note that, as an ugly/hacky workaround for #13018, we added an `aws-provider-patch` command to Terragrunt, [as described here](https://github.com/hashicorp/terraform/issues/13018#issuecomment-685417748). I'm now updating that command to support nested blocks [in this PR](https://github.com/gruntwork-io/terragrunt/pull/1391) as a workaround for the new issue described here.

**Comment by brikis98** [comment] 2020-10-15 13:54
OK, the updated `terragrunt awss-provider-patch` workaround is now available in [v0.25.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.25.4).

**Comment by dalen** [comment] 2020-10-22 11:50
terraform 0.13.5 seems to have fixed this for `plan` & `apply`, but not for `import`

**Comment by katlimruiz** [comment] 2020-11-19 05:00
> I had a similar issue, but with kubernetes provider
> 
> ```
> terraform import module.XXXXXXX.kubernetes_namespace.istio_system istio-system
> 
> Error: Invalid provider configuration
> 
>   on ../../modules/XXXXXXX/main.tf line 22:
>   22: provider "kubernetes" {
> 
> The configuration for
> module.XXXXXXXXXX.provider["registry.terraform.io/hashicorp/kubernetes"].YYYYYYY
> depends on values that cannot be determined until apply.
> ```
> 
> And my workaround was changing the provider from
> 
> ```
> provider "kubernetes" {
>   load_config_file = false
>   version          = " ~> 1.11.0"
> 
>   host                   = "https://${module.XXXXXXXXXX.endpoint}"
>   cluster_ca_certificate = base64decode(module.XXXXXXXX.cluster_ca_certificate)
>   token                  = module.XXXXXXXXXXX.access_token
> }
> ```
> 
> to
> 
> ```
> provider "kubernetes" {
>   load_config_file = true
>   version          = " ~> 1.11.0"
> }
> ```
> 
> the import worked and I switched the code back after.

This workaround worked for me, I was able to import my kubernetes clusters

**Comment by lkwg82** [comment] 2020-11-23 09:12
Has anyone a workaround for aws?

**Comment by katlimruiz** [comment] 2020-11-24 17:59
In the end, the solution I found better was to separate the terraform states across several steps (indeed harder but it does solves many problems).

In summary, it would be to 

1. Generate your first terraform state which contains your kubernetes cluster creation.
2. After the cluster definition, include a local_file generation with the kubernetes config.
3. In your second terraform state, load the file and configure the provider with it.

I will try to create a medium article for it, but in summary these are the steps that I've come up with for a long term solution.

**Comment by jason-huling** [comment] 2020-12-03 06:35
I was able to get a workaround for my scenario in aws, hopefully it will help someone else until this is resolved.

I have a module `aws-account` that provisions new accounts with `aws_organizations_account` and then uses an aws provider with string interpolation for the assume role, taking the account id from `aws_organizations_account`. High level looks something like this:

`module/aws-account` `main.tf` + `providers.tf` contents:
```hcl
resource "aws_organizations_account" "this" {
  # resource content...
}

provider "aws" {
  alias  = "this"
  region = "us-west-2"
  assume_role {
    role_arn = "arn:aws:iam::${aws_organizations_account.this.id}:role/OrganizationAccountAccessRole"
  }
}

# bootstrap some account resources with `aws.this` provider.
```
I can't really comment out this provider or the assume role without effecting other consumers of the module, so I did the following.

1. Initial state
```hcl
# Need to import into 'module.aws_account.aws_organizations_account.this'
module "aws_account" {
  source = "module/aws-account"
  # ...
}
```
2. Comment out the module and define a temporary top level resource for `aws_organizations_account`
```hcl
resource "aws_organizations_account" "temp" {}

# module "aws_account" {
#   source = "module/aws-account"
#   # ...
# }
```
3. Import into the top level resource:
```
terraform import aws_organizations_account.temp xxxxxxxxxxxx
```
4. Move the state from the top level resource into the module:
```
terraform state mv aws_organizations_account.temp module.aws_account.aws_organizations_account.this
```
5. Done, revert code back to step 1

Hope it helps.

**Comment by donPabloNow** [comment] 2021-01-31 21:44
Same issue here - I am using Terraform and Helm to deploy to GoogleCloud, I have got a couple ideas from this thread, thanks for sharing.

```
provider "google" {
  project = var.project
  region  = var.region
}

data "google_client_config" "provider" {}

provider "kubernetes" {
  load_config_file = "false"
  host                   = module.kubernetes.cluster.endpoint
  token                  = data.google_client_config.provider.access_token
  cluster_ca_certificate = base64decode(module.kubernetes.cluster.master_auth[0].cluster_ca_certificate)
}

provider "helm" {
  kubernetes {
    host                   = module.kubernetes.cluster.endpoint
    token                  = data.google_client_config.provider.access_token
    cluster_ca_certificate = base64decode(module.kubernetes.cluster.master_auth[0].cluster_ca_certificate)
  }
}
```

Exception:

```
`Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Error: Unsupported argument

  on providers.tf line 16, in provider "kubernetes":
  16:   load_config_file = "false"

An argument named "load_config_file" is not expected here.

!!
!! terraform failed:
!!      "exit status 1"
!!`
```

**Comment by donPabloNow** [comment] 2021-01-31 21:56
This is working for me!
```
provider "kubernetes" {
  version                = "~> 1.11.1"
  load_config_file       = false
  ...
}
```

**Comment by dilloncwheeler** [comment] 2021-02-26 14:06
This issue is supposed to be fixed in the latest release for what it's worth. 
https://github.com/hashicorp/terraform/issues/13018#issuecomment-786274459

**Comment by jbardin** [comment] 2021-03-23 21:21
Closing as confirmed this case is working in the latest release.

Thanks!

**Closed by jbardin** 2021-03-23 21:21 UTC
Labels: bug, confirmed, import, v0.13
