### ISSUE TITLE
Error while trying to assign multiple provider for aws while creating global dynamodb resource

### ISSUE THREAD

**Issue by shomeprasanjit** [hashicorp/terraform#21286] opened 2019-05-13 20:53 UTC
Hello guys,
              
I am getting below mentioned error, while trying to run terraform `plan` or `apply` from 2nd time onwards.  Meaning, the 1st time when the resource is created, it works like a charm but 2nd time onwards (for updates on existing tables) getting error.  

`Error: Error asking for user input: 1 error(s) occurred:

* module.ABC-stage-subscription.aws_dynamodb_global_table.global-dynamodb-stream-enabled-GSI: configuration for module.ABC-stage-subscription.provider.aws.us-east-1 is not present; a provider configuration block is required for all operations`

Here are my files: 

Location directory Name: **environments/Production**
File Name: **dynamodb_main.tf**

```hcl
module "ABC-stage-subscription" {
  source       = "../../modules/dynamodb/streaming/global/provisioned/single-GSI"
  prefix       = "ABC-stage"

  aws_profile  = "${var.aws_profile}"
  aws_profile1 = "${var.aws_profile1}"

  subnet_ids = [
    "${data.aws_subnet.private01.id}",
    "${data.aws_subnet.private02.id}",
    "${data.aws_subnet.private03.id}"
  ]
  vpc_id           = "${data.aws_vpc.vpc.id}"
  table_name       = "ABC"
  read             = 100
  write            = 100
  hash_key_value   = "id"
  attribute_name   = "id"
  attribute_type   = "S"
  stream_view_type = "NEW_AND_OLD_IMAGES"
  default_tags     = "${merge( var.default_tags, var.backup_tag_gc)}"

  gsi_1_attribute_type = "S"

  gsi_1_name       = "customer_id_index"
  gsi_1_hash_key   = "customer_id"
  gsi_1_write      = 100
  gsi_1_read       = 100

  ptr_value        = "true"
}
```

Module directory location: **dynamodb/streaming/global/provisioned/single-GSI**
Under Module directory: **main.tf** 

```hcl
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
  profile = "${var.aws_profile}"
}

provider "aws" {
  alias  = "eu-central-1"
  region = "eu-central-1"
  profile = "${var.aws_profile1}"
}


resource "aws_dynamodb_table" "global-dynamodb-stream-enabled-GSI-us-east-1" {

  provider         = "aws.us-east-1"
  tags             = "${var.default_tags}"

  name             = "${var.prefix}-${var.table_name}"
  read_capacity    = "${var.read}"
  write_capacity   = "${var.write}"
  hash_key         = "${var.hash_key_value}"

  stream_enabled   = "${var.stream_enabled}"
  stream_view_type = "${var.stream_view_type}"

  server_side_encryption {
    enabled = true
  }

  attribute {
    name = "${var.attribute_name}"
    type = "${var.attribute_type}"
  }

  attribute {
    name = "${var.gsi_1_hash_key}"
    type = "${var.gsi_1_attribute_type}"
  }

  global_secondary_index {
    name               = "${var.gsi_1_name}"
    hash_key           = "${var.gsi_1_hash_key}"
    write_capacity     = "${var.gsi_1_write}"
    read_capacity      = "${var.gsi_1_read}"
    projection_type    = "${var.gsi_1_projection}"
  }

  point_in_time_recovery {
    enabled = "${var.ptr_value}"
  }

  lifecycle {
    ignore_changes = ["read_capacity","write_capacity"]
  }
}

resource "aws_dynamodb_table" "global-dynamodb-stream-enabled-GSI-eu-central-1" {

  provider         = "aws.eu-central-1"
  tags             = "${var.default_tags}"

  name             = "${var.prefix}-${var.table_name}"
  read_capacity    = "${var.read}"
  write_capacity   = "${var.write}"
  hash_key         = "${var.hash_key_value}"

  stream_enabled   = "${var.stream_enabled}"
  stream_view_type = "${var.stream_view_type}"

  server_side_encryption {
    enabled = true
  }

  attribute {
    name = "${var.attribute_name}"
    type = "${var.attribute_type}"
  }

  attribute {
    name = "${var.gsi_1_hash_key}"
    type = "${var.gsi_1_attribute_type}"
  }

  global_secondary_index {
    name               = "${var.gsi_1_name}"
    hash_key           = "${var.gsi_1_hash_key}"
    write_capacity     = "${var.gsi_1_write}"
    read_capacity      = "${var.gsi_1_read}"
    projection_type    = "${var.gsi_1_projection}"
  }

  point_in_time_recovery {
    enabled = "${var.ptr_value}"
  }

  lifecycle {
    ignore_changes = ["read_capacity","write_capacity"]
  }

}

resource "aws_dynamodb_global_table" "global-dynamodb-stream-enabled-GSI" {

  depends_on = ["aws_dynamodb_table.global-dynamodb-stream-enabled-GSI-us-east-1", "aws_dynamodb_table.global-dynamodb-stream-enabled-GSI-eu-central-1"]
  provider   = "aws.us-east-1"

  name       = "${var.prefix}-${var.table_name}"

  replica {
    region_name = "us-east-1"
  }

  replica {
    region_name = "eu-central-1"
  }
}
```

we do have **state file and is getting uploaded in S3** 

Versions which are currently is use are:  

```
Terraform **v0.11.13**
+ provider.aws **v2.10.0**
```

what can be the issue?

**Comment by apparentlymart** [comment] 2019-05-13 21:16
Hi @shomeprasanjit!

It looks like you have the same situation being discussed in #21268. The problem is that you have `provider` blocks in your `ABC-stage-subscription` module, and so if you try to remove or rename that module then the provider configurations are removed along with the resources, and Terraform therefore can't know how to destroy what was removed.

The best approach is to put `provider` blocks only in the root module (`environments/Production`, in your case) and pass them in to the child module using the `providers` argument inside the `module` block, as I was describing in #21268.

Since that issue is covering the same problem, I'm going to close this one just to consolidate the discussion. You can see more details and examples in my comments in the other issue.

**Closed by apparentlymart** 2019-05-13 21:16 UTC

**Comment by shomeprasanjit** [comment] 2019-05-15 06:49
Hello @apparentlymart, thanks for your tip. it works like charm.
