### ISSUE TITLE
Terraform apply crushes on version 1.3.4 and MacOS Ventura (13)

### ISSUE THREAD

**Issue by erez-paraswap** [hashicorp/terraform#32169] opened 2022-11-05 16:03 UTC
### Terraform Version

```shell
Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.36.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v4.0.3
```

### Terraform Configuration Files

```terraform
...terraform config...

I can't really share our TF codebase
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

inconsistent list element types (cty.Object(map[string]cty.Type{"command":cty.List(cty.String), "cpu_percent":cty.Number, "depends_on":cty.List(cty.Object(map[string]cty.Type{"condition":cty.String, "container_name":cty.String})), "docker_build":cty.Object(map[string]cty.Type{"build_args":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "context_path":cty.String, "image_tags":cty.List(cty.String)}), "ephemeral_storage_gb":cty.Number, "extra_environment_variables":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "health_check_command":cty.String, "health_check_http_util":cty.String, "health_check_path":cty.String, "health_check_port":cty.Number, "image":cty.String, "memory_percent":cty.Number, "name":cty.String, "ports":cty.List(cty.Object(map[string]cty.Type{"description":cty.String, "port":cty.Number, "protocol":cty.String, "public":cty.Bool})), "shared_storage_mounts":cty.List(cty.ObjectWithOptionalAttrs(map[string]cty.Type{"path":cty.String, "read_only":cty.Bool}, []string{"read_only"}))}) then cty.Object(map[string]cty.Type{"command":cty.List(cty.String), "cpu_percent":cty.Number, "depends_on":cty.List(cty.Object(map[string]cty.Type{"condition":cty.String, "container_name":cty.String})), "docker_build":cty.Object(map[string]cty.Type{"build_args":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "context_path":cty.String, "image_tags":cty.List(cty.String)}), "ephemeral_storage_gb":cty.Number, "extra_environment_variables":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "health_check_command":cty.String, "health_check_http_util":cty.String, "health_check_path":cty.String, "health_check_port":cty.Number, "image":cty.String, "memory_percent":cty.Number, "name":cty.String, "ports":cty.List(cty.Object(map[string]cty.Type{"description":cty.String, "port":cty.Number, "protocol":cty.String, "public":cty.Bool})), "shared_storage_mounts":cty.List(cty.Object(map[string]cty.Type{"path":cty.String, "read_only":cty.Bool}))}))
goroutine 8423 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        github.com/hashicorp/terraform/internal/logging/panic.go:55 +0x170
panic({0x104419500, 0x14002a5d040})
        runtime/panic.go:884 +0x204
github.com/zclconf/go-cty/cty.ListVal({0x14006239100, 0x2, 0x1?})
        github.com/zclconf/go-cty@v1.12.0/cty/value_init.go:166 +0x454
github.com/zclconf/go-cty/cty.transform({0x0?, 0x0, 0x0}, {{{0x10481e610?, 0x14002424630?}}, {0x104327a20?, 0x14006205b30?}}, {0x104805a80, 0x14002254378})
        github.com/zclconf/go-cty@v1.12.0/cty/walk.go:175 +0xb9c
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
        github.com/zclconf/go-cty@v1.12.0/cty/walk.go:130
github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults).Apply(0x14001e6bb80?, {{{0x10481e610?, 0x14002424630?}}, {0x104327a20?, 0x14006205b30?}})
        github.com/hashicorp/hcl/v2@v2.14.1/ext/typeexpr/defaults.go:38 +0x9c
github.com/hashicorp/terraform/internal/terraform.prepareFinalInputVariableValue({{0x14002aaed00, 0x1, 0x1}, {{}, {0x14002909500, 0xa}}}, 0x140082b1a30, 0x14002c24d00)
        github.com/hashicorp/terraform/internal/terraform/eval_variable.go:140 +0x854
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).evalModuleVariable(0x14003803b60?, {0x104832a38?, 0x14000b04540?}, 0x68?)
        github.com/hashicorp/terraform/internal/terraform/node_module_variable.go:239 +0x3e4
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0x14003803b60, {0x104832a38, 0x14000b04540}, 0x4)
        github.com/hashicorp/terraform/internal/terraform/node_module_variable.go:152 +0x98
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14003a32870, {0x104832a38, 0x14000b04540}, {0x10dbd3520, 0x14003803b60})
        github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:136 +0xa8
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x1045e9080, 0x14003803b60})
        github.com/hashicorp/terraform/internal/terraform/graph.go:74 +0x208
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14003803bc0, {0x1045e9080, 0x14003803b60}, 0x14005898500)
        github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x2e0
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        github.com/hashicorp/terraform/internal/dag/walk.go:304 +0xbf0

### Expected Behavior

It was running on last patch version (1.3.3), so I'd expect it to run on 1.3.4 or maybe this is related to the MacOS upgrade to Ventura I made

### Actual Behavior

I can no longer apply

### Steps to Reproduce

terraform apply with var-file parameter

**Comment by erez-paraswap** [comment] 2022-11-06 09:40
Some more info,
I see it complains on 'inconsistent list element types' while the list objects are totally ok:
debug information shows that it recognizes the 'shared_storage_mounts' sub attribute one time as List of ObjectWithOptionalAttrs and one time as List of Object
See the diff between the following two lines
`	cty.Object(map[string]cty.Type{"command":cty.List(cty.String), "cpu_percent":cty.Number, "depends_on":cty.List(cty.Object(map[string]cty.Type{"condition":cty.String, "container_name":cty.String})), "docker_build":cty.Object(map[string]cty.Type{"build_args":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "context_path":cty.String, "image_tags":cty.List(cty.String)}), "ephemeral_storage_gb":cty.Number, "extra_environment_variables":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "health_check_command":cty.String, "health_check_http_util":cty.String, "health_check_path":cty.String, "health_check_port":cty.Number, "image":cty.String, "memory_percent":cty.Number, "name":cty.String, "ports":cty.List(cty.Object(map[string]cty.Type{"description":cty.String, "port":cty.Number, "protocol":cty.String, "public":cty.Bool})), "shared_storage_mounts":cty.List(cty.ObjectWithOptionalAttrs(map[string]cty.Type{"path":cty.String, "read_only":cty.Bool}, []string{"read_only"}))})
	
	cty.Object(map[string]cty.Type{"command":cty.List(cty.String), "cpu_percent":cty.Number, "depends_on":cty.List(cty.Object(map[string]cty.Type{"condition":cty.String, "container_name":cty.String})), "docker_build":cty.Object(map[string]cty.Type{"build_args":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "context_path":cty.String, "image_tags":cty.List(cty.String)}), "ephemeral_storage_gb":cty.Number, "extra_environment_variables":cty.List(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "health_check_command":cty.String, "health_check_http_util":cty.String, "health_check_path":cty.String, "health_check_port":cty.Number, "image":cty.String, "memory_percent":cty.Number, "name":cty.String, "ports":cty.List(cty.Object(map[string]cty.Type{"description":cty.String, "port":cty.Number, "protocol":cty.String, "public":cty.Bool})), "shared_storage_mounts":cty.List(cty.Object(map[string]cty.Type{"path":cty.String, "read_only":cty.Bool}))})`

**Comment by liamcervante** [comment] 2022-11-07 09:33
Hi @erez-paraswap, thanks for the bug report! I suspect this is a duplicate of https://github.com/hashicorp/terraform/issues/32157.

Without the terraform config I'm probably not going to be able to confirm this 100%, though I am fairly confident. Is there any chance you could create a minimal example from your config files that replicates this and you can share with us?

For the time being I will mark this as a duplicate, but if you can share some config with us I can test it out and verify that is or isn't a duplicate. If it turns out it is not a duplicate I can then reopen this one.

**Closed** 2022-11-07 09:34 UTC
Labels: bug, confirmed, duplicate, v1.3
