### ISSUE TITLE
Using `index` syntax to return list element causes index out of range when count is incremented

### ISSUE THREAD

**Issue by mukund1989** [hashicorp/terraform#18470] opened 2018-07-16 21:42 UTC
### Terraform Version

```
0.10.8
```

### Terraform Configuration Files

Simplifying the configs for the sake of readability...

module_root.tf
```
#lets say foo function exposes/exports the attribute `id`

resource "foo" "x" {
count = "${var.count}" # count can be 0 or more
...
}

locals {
temp_var = "${concat(foo.x.*.id, list(""))}"
}

resource "bar" "y"{
id = "${local.temp_var[count.index]}"
...
}
```

_module_call.tf_
```
module "custom_bar" {
count = 1
...
}
```

### Expected Behavior

When I increase the count from 1 to 2 in module `custom_bar` / _module_call.tf_ , the plan should indicate creation of additional resources. 

### Actual Behavior
```
* module.custom_bar.bar.y: 1 error(s) occurred:

* module.custom_bar.bar.y[1]: index 1 out of range for list local.temp_var (max 1) in:

${local.temp_var[count.index]}
```

### Steps to Reproduce
Increase count in module `custom_bar` / _module_call.tf_ and do tf plan

### Additional Context
Originally, my TF configs looked like below, but using `element` and incrementing count is destroying previously created resource as indicated in #17014 
Hence using index syntax to access the list element

module_root.tf
```
#lets say foo function exposes/exports the attribute `id`

resource "foo" "x" {
count = "${var.count}" # count can be 0 or more
...
}

resource "bar" "y"{
id = "${element(concat(foo.x.*.id, list("")), count.index)}"  
...
}
```

_module_call.tf_
```
module "custom_bar" {
count = 1
...
}
```

### References
#17014

**Comment by apparentlymart** [comment] 2018-07-16 22:20
Thanks for opening this, @mukund1989!

It seems like Terraform here is evaluating the expression against the prior state rather than the planned state, and so the array length is coming back wrong.

I notice you are using Terraform 0.10.8, and I remember there were some count-related bugs in the 0.10 line. Would it be possible for you to give this a try with Terraform 0.11 and see if you still see the problem there?

It'd also be helpful to see the full log output of running `terraform plan` with the `TF_LOG=trace` environment variable set, which should tell us which of Terraform's phases the issue is occurring in. If you are able to share this, please share it as a [gist](https://gist.github.com/) because the log output is usually too verbose to read properly inline within a github comment.

**Comment by mukund1989** [comment] 2018-07-17 15:23
@apparentlymart  Looks like I am facing the same issue with TF v0.11.7 as well.
As mentioned before, my resource definition is pretty complex. Pasting some relevant o/p from the log by enabling TF_LOG [here](https://gist.github.com/mukund1989/e474b0f943ce8059196a5d72f928c446)

**Comment by apparentlymart** [comment] 2018-07-18 16:57
Thanks @mukund1989! The fact that this is happening during the refresh stage and it is an interaction between a module input variable and a local value is an important insight here that should help us get to the bottom of this.

**Comment by apparentlymart** [comment] 2018-10-31 23:51
Hi again, @mukund1989!

With our big configuration language improvements now merged into master I tried out the following configuration on the v0.12.0-alpha2 prerelease build:

```hcl
variable "instance_count" {
  default = 1
}

resource "null_resource" "x" {
  count = var.instance_count
}

locals {
  temp_var = concat(null_resource.x.*.id, list(""))
}

resource "null_resource" "y" {
  count = var.instance_count

  triggers = {
    upstream = local.temp_var[count.index]
  }
}
```

I initially applied this accepting the default count of 1:

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.x[0] will be created
  + resource "null_resource" "x" {
      + id = (known after apply)
    }

  # null_resource.y[0] will be created
  + resource "null_resource" "y" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.x[0]: Creating...
null_resource.x[0]: Creation complete after 0s [id=4210021179012427322]
null_resource.y[0]: Creating...
null_resource.y[0]: Creation complete after 0s [id=1957529371470645641]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

I then applied again with an incremented count:

```
$ terraform apply -var="instance_count=2"
null_resource.x[0]: Refreshing state... [id=4210021179012427322]
null_resource.y[0]: Refreshing state... [id=1957529371470645641]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.x[1] will be created
  + resource "null_resource" "x" {
      + id = (known after apply)
    }

  # null_resource.y[1] will be created
  + resource "null_resource" "y" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.x[1]: Creating...
null_resource.x[1]: Creation complete after 0s [id=2448695963505931943]
null_resource.y[1]: Creating...
null_resource.y[1]: Creation complete after 0s [id=6159941061905823050]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

...and finally I applied again letting the count return to 1, destroying the two instances with index `1`:

```
$ terraform apply
null_resource.x[0]: Refreshing state... [id=4210021179012427322]
null_resource.x[1]: Refreshing state... [id=2448695963505931943]
null_resource.y[1]: Refreshing state... [id=6159941061905823050]
null_resource.y[0]: Refreshing state... [id=1957529371470645641]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # null_resource.x[1] will be destroyed
  - resource "null_resource" "x" {
      - id = "2448695963505931943" -> null
    }

  # null_resource.y[1] will be destroyed
  - resource "null_resource" "y" {
      - id       = "6159941061905823050" -> null
      - triggers = {
          - "upstream" = "2448695963505931943"
        } -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.y[1]: Destroying... [id=6159941061905823050]
null_resource.y[1]: Destruction complete after 0s
null_resource.x[1]: Destroying... [id=2448695963505931943]
null_resource.x[1]: Destruction complete after 0s

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.
```

Out of curiousity, I also simplified the configuration as follows to approximate the other example you gave:

```hcl
variable "instance_count" {
  default = 1
}

resource "null_resource" "x" {
  count = var.instance_count
}

resource "null_resource" "y" {
  count = var.instance_count

  triggers = {
    upstream = null_resource.x[count.index].id
  }
}
```

This one gave exactly the same results.

Since this appears to be fixed in master I'm going to close this out now. The fix will be in the forthcoming v0.12.0 release. Thanks for reporting this, and thanks for your patience while we got to the bottom of it.

**Closed by apparentlymart** 2018-10-31 23:51 UTC
Labels: bug, config

**Comment by mukund1989** [comment] 2018-11-01 14:32
Cool! thanks for the info @apparentlymart !

**Comment by aitorpazos** [comment] 2018-12-05 23:45
For the record, I hit this issue after I got an error on update (not related with the additional resources in the list).
What I had to do is remove the additional resources from the list, make sure the update was fixed and ran correctly and then I could add those new resources in and get them added.
