### ISSUE TITLE
Depedency lock file for module what will be resolved from Terraform registry or own terraform registry

### ISSUE THREAD

**Issue by dosilyoun** [hashicorp/terraform#34275] opened 2023-11-20 13:59 UTC
### Terraform Version

```shell
1.6.1
```

### Terraform Configuration Files

```terraform
module "test" {
  source                                    = "test.jfrog.io/test_test/test/aws"
  version                                   = "1.0.0"
}
```

### Debug Output

.

### Expected Behavior

Dependency lock file contains the modules and providers

### Actual Behavior

Dependency lock file only contains the providers

### Steps to Reproduce

terraform init and see the dependency lock file

### Additional Context

How should you proceed with module checksum verification? Why it can be the same as for providers?

**Comment by jbardin** [comment] 2023-11-20 14:09
Duplicate of #31301

**Closed by jbardin** 2023-11-20 14:09 UTC
Labels: bug, new
