### ISSUE TITLE
The output for the `tomap` function is different from the actual output

### ISSUE THREAD

**Issue by nikpivkin** [hashicorp/terraform#35970] opened 2024-11-08 07:01 UTC
### Terraform Version

```shell
tf version
Terraform v1.9.4
on darwin_arm64
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/functions/tomap

### What is the docs issue?

In the documentation example, calling the following expression: `tomap({“a” = 1, “b” = 2})` returns a map:
```tf
{
  "a" = 1
  "b" = 2
}
```

But in reality, this expression returns the following:
```bash
❯ tf console
> tomap({"a" = 1, "b" = 2})
tomap({
  "a" = 1
  "b" = 2
})
```

**Comment by bschaatsbergen** [comment] 2024-11-08 20:26
Hey @nikpivkin,

Thank you for raising this issue. The [tomap](https://developer.hashicorp.com/terraform/language/functions/tomap) function is indeed evaluated, but the docs don’t accurately reflect the map type as it appears in the Terraform CLI output. Initially, Terraform rendered maps with object syntax without explicit annotations, which was often confusing. We’ve since updated the CLI to use explicit wrappers like tomap(...) to make type distinctions clearer. It appears our documentation hasn’t yet been updated to reflect this change in output.

**Comment by bschaatsbergen** [comment] 2024-11-08 20:28
Closing as duplicate of [#31619](https://github.com/hashicorp/terraform/issues/31619)

**Closed by bschaatsbergen** 2024-11-08 20:28 UTC
Labels: documentation, new
