### ISSUE TITLE
Seeing destroy output for data resources is terrifying

### ISSUE THREAD

**Issue by matschaffer** [hashicorp/terraform#14605] opened 2017-05-18 03:24 UTC
### Terraform Version

0.9.4

### Affected Resource(s)

Please list the resources as a list, for example:
- `data.*`

### Terraform Configuration Files
```hcl
data "aws_vpc" "production" {
  filter {
    name   = "tag:Name"
    values = ["production"]
  }
}
```

### Output

```
> terraform destroy
...
data.aws_vpc.production: Destroying... (ID: vpc-7...2)
data.aws_vpc.production: Destruction complete
...
```

### Expected Behavior

Only things that actually need to be destroyed show in output.

### Actual Behavior

All resources, data included, show destroy output even though (afaik) no action is taken for these resources.

### Steps to Reproduce

1. `terraform apply`
1. `terraform destroy`

This gave me a heart attack the first time I saw it. Would be nice to at least clarify the output or suppress it altogether.

**Comment by grubernaut** [comment] 2017-05-18 13:43
Closing as dupe of #14048, thanks!

**Closed by grubernaut** 2017-05-18 13:43 UTC
Labels: core, enhancement
