### ISSUE TITLE
remote-exec provisioner fails with "Error reading script: EOF" 

### ISSUE THREAD

**Issue by chin2chavda** [hashicorp/terraform#4186] opened 2015-12-07 11:28 UTC
Hi @phinze ,

I am also getting an error during run commands on "remote-exec" in provision section.

Error:

```
aws_instance.test: Creating...
ami: "" => "ami-97d490fd"
availability_zone: "" => ""
ebs_block_device.#: "" => ""
ephemeral_block_device.#: "" => ""
instance_type: "" => "t1.micro"
key_name: "" => "newkvp"
placement_group: "" => ""
private_dns: "" => ""
private_ip: "" => ""
public_dns: "" => ""
public_ip: "" => ""
root_block_device.#: "" => ""
security_groups.#: "" => ""
source_dest_check: "" => "1"
subnet_id: "" => ""
tags.#: "" => "1"
tags.Name: "" => "test_server"
tenancy: "" => ""
vpc_security_group_ids.#: "" => "1"
vpc_security_group_ids.1458656584: "" => "sg-4d5b1f2a"
aws_instance.test: Provisioning with 'file'...
aws_instance.test: Provisioning with 'remote-exec'...
aws_instance.test (remote-exec): Connecting to remote host via SSH...
aws_instance.test (remote-exec): Host: 54.86.117.120
aws_instance.test (remote-exec): User: root
aws_instance.test (remote-exec): Password: false
aws_instance.test (remote-exec): Private key: true
aws_instance.test (remote-exec): SSH Agent: false
aws_instance.test (remote-exec): Connected!
Error applying plan:

1 error(s) occurred:

Failed to upload script: Error reading script: EOF
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Script :
```javascript
provider "aws" {
access_key = "aws_access_key"
secret_key = "aws_secret_key"
region = "us-east-1"
}

resource "aws_instance" "test" {
ami = "ami-97d490fd"
instance_type = "t1.micro"
vpc_security_group_ids = ["sg-4d5b1f2a"]
key_name = "newkvp"
provisioner "file" {
source = "script.sh"
destination = "/tmp/script.sh"
connection {
agent = false
user = "root"
key_file = "newkvp.pem"
}
}

provisioner "remote-exec" {
    inline = [
      "echo 1"
    ]
    connection {
           agent = false
           user = "root"
           key_file = "newkvp.pem"
    }
}

tags {
    Name = "test_server"
}
}
```
Here, AMI I am using is developed by packer with centos6.5, and also tried this code with the different versions(v0.6.6, v0.6.4, v0.6.0) of terraform.

Please provide me any solution regarding this as I am unable to execute any single command to remote resource with terraform.

**Comment by phinze** [comment] 2015-12-07 15:53
Thanks for the report!

I just tried to reproduce this with no luck on Terraform v0.6.8.

Here's the config I used:

https://gist.github.com/phinze/30b33f860cebecb91dd8

Differences from your example - I used an Ubuntu AMI and Terraform and ran from an OSX machine.

A couple of additional questions for you:

 * After the error, is "/tmp/script.sh" present on the remote machine?
 * Are you running Terraform from a Windows box?
 * Can you share the contents of`script.sh`?

**Comment by davehodgson** [comment] 2015-12-07 15:57
This may be unrelated but I have a similar error on 0.6.8 when I didn't before on 0.6.6

I built an environment in 0.6.6 a few days ago and haven't touched since, literally the only changes to the scripts were to upgrade to 0.6.8 and add publish_settings variable (I have them both as per issue XXX). Now when I run refresh or plan I get EOF errors - they appear to originate from my azure_instance resources although I think the security groups are also affected.

Was there a change in 0.6.8 that may have affected how we read config files perhaps?

**Comment by chin2chavda** [comment] 2015-12-09 06:03
* Yes, I can see script.sh on remote machine and also can run it after ssh.
* I am running Terraform  from Ubuntu 12.04.
* As in my script you can see, there is only "echo 1" command in "inline" block of "remote-exec" and also in "script.sh".

**Comment by phinze** [comment] 2015-12-09 20:52
Just tested again on Ubuntu 12.04 and updated the above gist to indicate a few tweaks to make it closer to your reported config. Everything still seems to be working from here.

The only way I can get this error to reproduce is by giving the `inline` parameter just an empty string for a value:

```tf
inline = [ "" ]
```

You see, this error message is coming from a `reader.Peek(2)` that occurs before uploading to double check that Terraform can read the script. An `EOF` error from that function indicates that the file being read has less than 2 bytes of content. So all signs point to there being an empty file somewhere in your config.

Can you double check this on your side? If that doesn't yield any answers, perhaps you can pull down the repro config from the gist above and see if that exhibits similar behavior for you?

**Comment by ericpromislow** [comment] 2015-12-10 02:28
I just ran into this with 0.6.8.  My script has code like this:
```
    # start the clea server
    provisioner "remote-exec" {
        inline = <<EOF
set -e
cid=$(long command....  | tee /tmp/clea.out)
docker network connect yapper $cid
EOF        
    }

    #
    # ikonn
    #

    # start the ikonn server
    provisioner "remote-exec" {
        inline = [
...
```

And the /tmp/terraform script on the server is a mix between bash code and terraform script fragments:
```
#!/bin/sh
set -e
cid=$(long command....  | tee /tmp/clea.out)
docker network connect yapper $cid
EOF
    }

    #
    # ikonn
    #

    # start the ikonn server
    provisioner "remote-exec" {
        inline = [
...
```
None of the text after the EOF, including it, should appear in the script. The result, of course,
is that terraform fails to build.  Reverting back to 0.6.6 for now (we had problems with 0.6.7 as well).

**Comment by chin2chavda** [comment] 2016-01-06 15:07
I am still facing same issue. Can you suggest terraform version, better work with CentOs6.5.

**Comment by phinze** [comment] 2016-01-18 16:59
@chin2chavda Did you try the config I posted above in the Gist? What behavior do you see with that config?

**Comment by chin2chavda** [comment] 2016-02-02 12:07
If you are talking about  this line 
`inline=[" "]`
then behavior remains same

**Comment by travis-bear** [comment] 2016-02-28 02:45
Possibly related:  my comment on https://github.com/hashicorp/terraform/issues/4022

**Comment by rklyne** [comment] 2016-03-21 11:42
I saw a very similar problem to this this morning. The logs showed that the problem was caused by a failure to write to the file /tmp/terraform_nnnn.sh and a subsequent failure to chmod this file.

I was attempting to run the failing provisioner as a non-root user but the file in question already existed and was owned by root. After logging in as root and moving the file out of the way the process continued successfully.

Unfortunately I have no concrete information on how the files got in to this state, but I have been monkeying around a lot, moving things from root to a non-root user.

**Comment by rklyne** [comment] 2016-03-21 13:52
I've managed to reproduce this with these steps:
- Have a remote-exec provisioner configured to run as a non-root user
- I run terraform and the provisioner fails
- The provisioner is then fixed.
- I run terraform again and I see this problem
I'm using CentOS 6.5 on digitalocean, if that matters.

**Comment by phinze** [comment] 2016-03-23 21:13
@rklyne by any chance was your trouble with v0.6.13? That release did have a bug with remote-exec that has been fixed in v0.6.14, so I'd encourage you to double check with the latest release. :+1:

**Comment by rklyne** [comment] 2016-03-24 07:34
My trouble was with 0.6.12 as well.
I have retried the steps I listed above and they did not reproduce the problem this time.
I don't think this is the same problem as was found in 0.6.13 but I can't reproduce so close this one if you like.

**Comment by DustinChaloupka** [comment] 2016-06-24 01:11
I ran into the same problem that @rklyne described (user A owned a `/tmp/terraform_nnnn.sh` script that terraform was trying to create then chmod for user B on a different `terraform apply`). This was on version 0.6.16 of terraform.

Are these remote-exec "random" named scripts not actually random?

**Comment by DustinChaloupka** [comment] 2016-06-24 01:37
A workaround that we have been using for this is to give a `script_path` name that includes the ssh user in it. This way ssh users are only ever trying to chmod scripts with their own ssh username in the filename.

**Comment by phinze** [comment] 2016-06-29 14:00
Wow @DustinChaloupka good call! I looked into the script path code and it is indeed failing to seed its random number source, so the paths are a pseudorandom chain that starts at a deterministic place. 🐛 

Fix incoming!

**Closed** 2016-06-29 15:37 UTC
Labels: bug, provisioner/remote-exec, waiting-response
