### ISSUE TITLE
Terraform crashes while importing aws resources

### ISSUE THREAD

**Issue by PederWaern** [hashicorp/terraform#31963] opened 2022-10-07 11:41 UTC
### Terraform Version

```shell
1.3.1
```

### Terraform Configuration Files

```terraform
...terraform config...
resource "aws_dynamodb_table" "tfstate_lock" {
  name = "se-sl-tf-${var.environment}-tfstate-lock"

  hash_key       = "LockID"
  read_capacity  = 1
  write_capacity = 1
  attribute {
    name = "LockID"
    type = "S"
  }
}
```

### Debug Output

- Failed to serialize resource instance in state: Instance module.greta_datalake.data.aws_iam_policy_document.datalake_policy_document has status ObjectPlanned, which cannot be saved in state.
- Failed to serialize resource instance in state: Instance module.greta_datalake.module.greta_lake_s3.data.aws_iam_policy_document.deny_insecure_transport_policy has status ObjectPlanned, which cannot be saved in state.
- Failed to serialize resource instance in state: Instance module.greta_datalake.module.greta_lake_s3.data.aws_iam_policy_document.combined_policies has status ObjectPlanned, which cannot be saved in state.
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:55 +0x170
panic({0x1030258e0, 0x14003ab5800})
        /usr/local/go/src/runtime/panic.go:890 +0x258
github.com/hashicorp/terraform/internal/states/statefile.StatesMarshalEqual(0x14000af2330, 0x14000d0f8a0)
        /Users/distiller/project/project/internal/states/statefile/marshal_equal.go:31 +0x160
github.com/hashicorp/terraform/internal/states/remote.(*State).PersistState(0x14000afb3e0, 0x0?)
        /Users/distiller/project/project/internal/states/remote/state.go:164 +0x124
github.com/hashicorp/terraform/internal/command.(*ImportCommand).Run(0x14000558b60, {0x1400019a060, 0x2, 0x2})
        /Users/distiller/project/project/internal/command/import.go:265 +0x17e0
github.com/mitchellh/cli.(*CLI).Run(0x14000a00500)
        /Users/distiller/go/pkg/mod/github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x4a8
main.realMain()
        /Users/distiller/project/project/main.go:315 +0x12b0
main.main()
        /Users/distiller/project/project/main.go:58 +0x1c

### Expected Behavior

Expected terraform to import the aws resource

### Actual Behavior

Terraform crashed...

### Steps to Reproduce

terraform import aws_dynamodb_table.<dynamodb-name>

**Comment by jbardin** [comment] 2022-10-10 13:04
Duplicate of #31851

**Closed by jbardin** 2022-10-10 13:04 UTC
Labels: bug, new
