### ISSUE TITLE
Terraform panic on terraform refresh on aws

### ISSUE THREAD

**Issue by bashoKa** [hashicorp/terraform#17634] opened 2018-03-19 21:16 UTC
Hi,

Terraform panic after `terraform refresh`

terraform --version
Terraform v0.11.2
+ provider.aws v1.11.0
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb48812]

goroutine 2054 [running]:
github.com/hashicorp/terraform/terraform.(*State).Lock(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:95 +0x22
github.com/hashicorp/terraform/terraform.(*State).SameLineage(0x0, 0xc4201935c0, 0xc420334800)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:628 +0x34
github.com/hashicorp/terraform/state/remote.(*State).WriteState(0xc4203348a0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/state/remote/state.go:37 +0x10a
github.com/hashicorp/terraform/backend/local.(*Local).opRefresh(0xc42018d8c0, 0x3eb4860, 0xc420010080, 0xc4204a5980, 0xc4203347e0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_refresh.go:115 +0x465
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opRefresh)-fm(0x3eb4860, 0xc420010080, 0xc4204a5980, 0xc4203347e0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:230 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc42018d8c0, 0xc420416870, 0xc420416860, 0x3eb4860, 0xc420010080, 0xc4204a5980, 0xc4203347e0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:254 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:251 +0x18a

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Terraforms crash.log:

2018/03/19 21:11:36 [TRACE] vertex 'root.trail-client.module.trail-client.aws_cloudwatch_metric_alarm.xxxx': walking
2018/03/19 21:11:36 [TRACE] vertex 'root.trail-client.module.trail-client.aws_cloudwatch_metric_alarm.xxxx': evaluating
2018/03/19 21:11:36 [TRACE] [walkRefresh] Entering eval tree: module.trail-client.aws_cloudwatch_metric_alarm.xxxx
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalSequence
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalInterpolate
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalGetProvider
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalValidateResource
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalReadState
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalDiff
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalReadState
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalDiff
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalWriteState
2018/03/19 21:11:36 [TRACE] [walkRefresh] Exiting eval tree: module.trail-client.aws_iam_policy_attachment.cloudtrail_access_policy_attachment
2018/03/19 21:11:36 [TRACE] root.trail-client: eval: *terraform.EvalWriteState
2018/03/19 21:11:36 [TRACE] [walkRefresh] Exiting eval tree: module.trail-client.aws_cloudwatch_metric_alarm.xxxxx
2018/03/19 21:11:36 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2018/03/19 21:11:36 [TRACE] dag/walk: upstream errored, not walking "root"
2018/03/19 21:11:36 [INFO] backend/local: plan calling Plan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb48812]

goroutine 2054 [running]:
github.com/hashicorp/terraform/terraform.(*State).Lock(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:95 +0x22
github.com/hashicorp/terraform/terraform.(*State).SameLineage(0x0, 0xc420193080, 0xc420425400)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:628 +0x34
github.com/hashicorp/terraform/state/remote.(*State).WriteState(0xc4204254d0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/state/remote/state.go:37 +0x10a
github.com/hashicorp/terraform/backend/local.(*Local).opRefresh(0xc42018db80, 0x3eb4860, 0xc420010080, 0xc420371a40, 0xc420425470)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_refresh.go:115 +0x465
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opRefresh)-fm(0x3eb4860, 0xc420010080, 0xc420371a40, 0xc420425470)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:230 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc42018db80, 0xc4203f2e50, 0xc4203f2e40, 0x3eb4860, 0xc420010080, 0xc420371a40, 0xc420425470)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:254 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:251 +0x18a

**Comment by jbardin** [comment] 2018-03-19 21:26
Hi @bashoKa,

Thanks filing the issue. This is a duplicate of #17152.

**Closed by jbardin** 2018-03-19 21:26 UTC
Labels: bug, crash
