### ISSUE TITLE
Terraform 1.2.6_linux_amd64.zip release returning a 404

### ISSUE THREAD

**Issue by andres-carvajal-proagrica** [hashicorp/terraform#31529] opened 2022-07-27 15:46 UTC
### Terraform Version

```
1.2.6
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

When trying to access https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_amd64.zip I should be able to download a tarball.

### Actual Behavior

Got a
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: terraform/1.2.6/terraform_1.2.6_linux_amd64.zip
RequestId: P1F14JB5JTB4BFHX
HostId: PHjKMSqdvQX3iCwuhRFfyr7R3qyxzgdA3dJSJa11Ah1YhlxMJtXtE1uXHUKc6LP3trDIJPV43Ng=

### Additional Context

I tried this from the UK. All other release packages seem to be available

**Comment by bflad** [comment] 2022-07-27 15:49
I can confirm the same issue from Philadelphia, PA, USA. All other release assets download correctly from https://releases.hashicorp.com/terraform/1.2.6.

**Comment by dbteku** [comment] 2022-07-27 15:53
I can confirm from UT, USA. https://releases.hashicorp.com/terraform/1.2.6

**Comment by alisdair** [comment] 2022-07-27 16:09
Thanks for the report! We're investigating this problem now.

**Comment by imishchuk-carbon** [comment] 2022-07-27 16:34
Looks like issue is fixed.
Thank you @alisdair

**Comment by rosstimson** [comment] 2022-07-27 16:35
This is causing an issue for Terrafrom Cloud workspaces that have a fuzzy version set i.e. `~> 1.2.2` which is what we currently have:

```
Operation failed: failed fetching Terraform: failed downloading terraform: failed downloading "https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_amd64.zip": unexpected status code 404
```

**Comment by rosstimson** [comment] 2022-07-27 16:48
Yeah, Terraform Cloud workspaces are fixed now too.  Many thanks.  👍🏻

**Comment by mdeggies** [comment] 2022-07-27 16:52
This was resolved at 9:32am PT, and we have a status page post incoming with the details on status.hashicorp.com. We'll post a link to that once it's available.

**Comment by alisdair** [comment] 2022-07-27 17:21
[The status page update is now published](https://status.hashicorp.com/incidents/1jw0q79c6cd5). Thanks again to all who reported!

**Closed by alisdair** 2022-07-27 17:21 UTC
Labels: bug, confirmed, v1.2
