### ISSUE TITLE
Terraform interpolation should only evaluate one branch of a condition

### ISSUE THREAD

**Issue by giner** [hashicorp/terraform#34366] opened 2023-12-06 10:22 UTC
### Terraform Version

```shell
Terraform v1.5.7
```

### Terraform Configuration Files

```terraform
locals {
  map = {}

  res1 = true || local.map["nonexist"]
  res2 = false && local.map["nonexist"]
}
```

### Debug Output

```terraform
│ Error: Invalid index
│ 
│   on test.tf line 4, in locals:
│    4:   res1 = true || local.map["nonexist"]
│     ├────────────────
│     │ local.map is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on test.tf line 5, in locals:
│    5:   res2 = false && local.map["nonexist"]
│     ├────────────────
│     │ local.map is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
```

### Expected Behavior

Only one branch of a condition should be evaluated

### Actual Behavior

Both branches of a condition are evaluated

### Steps to Reproduce

```
terraform apply
```

### References

#15605

**Comment by jbardin** [comment] 2023-12-06 13:27
Duplicate of #24128

**Closed by jbardin** 2023-12-06 13:27 UTC
Labels: bug, new
