### ISSUE TITLE
Vendored dependencies

### ISSUE THREAD

**Issue by brycekahle** [hashicorp/terraform#1235] opened 2015-03-18 16:26 UTC
Currently it is impossible to reproduce builds for older versions. This is because the dependencies are not vendored and are always updated to the current version automatically. Would you consider using something like `godep`?

**Comment by sethvargo** [comment] 2015-03-18 16:31
Perhaps a duplicate of https://github.com/hashicorp/terraform/issues/882?

**Comment by brycekahle** [comment] 2015-03-18 16:35
@sethvargo somewhat yes, but they didn't deliver on capturing dependency information in the release notes for 0.3.7. I currently want to build 0.3.7 with a minor change, but I am unable to because so many of the deps have changed. I cannot use master because it seems to have introduced a regression regarding a graph cycle (I haven't been able to track it down to file a bug).

**Comment by mitchellh** [comment] 2015-03-18 21:01
The Go core team has finally started to address dependency management. When an official solution is out, we'll adopt it. Until then, we'll wait. It looks like godeps might implement the official solution as it is designed though, in which case I'd be open to adopting it early. But still, the spec isn't done yet. Sorry!

**Closed by mitchellh** 2015-03-18 21:01 UTC
