### ISSUE TITLE
The same code works in eu-west-1 but not in eu-west-2 (empty tuple)

### ISSUE THREAD

**Issue by 80kk** [hashicorp/terraform#27023] opened 2020-11-24 15:23 UTC
Hi,
I have a fairly straight sns module I’d like to deploy in eu-west-2 region. Unfortunately what is working fine in eu-west-1 doesn’t work in eu-west-2. I’m not sure where the problem is and why.

### Terraform Version
```
Terraform v0.12.29
```

### Terraform Configuration Files
```
module sns {
  source                              = "../../modules/sns"
  region                              = var.region
  aws-account                         = var.aws-account
  sns-topic-recipient                 = var.sns-topic-recipient
  sns-subscription-email-address-list = var.sns-subscription-email-address-list
  tags                                = var.tags
}
```
vars:
```
variable "aws-account" {
  type        = string
  description = "AWS account ID"
  default = "1234567890"
}

variable "sns-topic-recipient" {
  type        = list(map(string))
  description = "List of the topic recipients"
  default = [
    {
      name = "recipient1"
    },
    {
      name = "recipient2"
    },
    {
      name = "recipient3"
    }
  ]
}

variable "sns-subscription-email-address-list" {
  type        = list(map(string))
  description = "List of email addresses as a map"
  default = [
    {
      name = "recipient1"
      email-address  = "recipient1@email.com"
    },
    {
      name = "recipient2"
      email-address  = "recipient2@email.com"
    },
    {
      name = "recipient3"
      email-address  = "recipient3@email.com"
    }
  ]
}
```
module's main.tf:
```
resource "aws_sns_topic" "CW-alerts" {
  count = length(var.sns-topic-recipient)
  name  = join("", [var.sns-topic-recipient[count.index].name])
  provisioner "local-exec" {
    command = "./sns_subscription.sh"
    environment = {
      sns_arn = self.arn
      sns_emails = var.sns-subscription-email-address-list[count.index].email-address
    }
  }
  tags  = merge(var.tags, { "Name" = join("", [var.tags.Environment, "-", var.sns-subscription-email-address-list[count.index].name]) })
}

resource aws_sns_topic_policy "CW-alerts-topic-policy" {
  count = length(var.sns-topic-recipient)
  arn   = aws_sns_topic.CW-alerts[count.index].arn
  policy = templatefile(join("", [path.module, "/cw-topic-policy.tpl"]), {
    region = join("", ["arn:aws:sns:", var.region, ":", var.aws-account, ":", var.sns-topic-recipient[count.index].name])
    aws-account = var.aws-account
  })
}
```
module's output.tf:
```
output "sns_topic_arn" {
  value = join("", aws_sns_topic.CW-alerts.*.arn)
}

output "sns-topics-created" {
  value = formatlist(
    "%s: %s",
    var.sns-topic-recipient[*].name,
    aws_sns_topic.CW-alerts[*].id
  )
}

resource "null_resource" "topic-mappings" {
  count = length(var.sns-topic-recipient)

  triggers = {
    name     = var.sns-topic-recipient[count.index].name
    topic-id = aws_sns_topic.CW-alerts[count.index].id
  }
}

output "sns-topics" {
  value = null_resource.topic-mappings.*.triggers
}
```
policy:
```
{
  "Version": "2012-10-17",
  "Id": "SNS-Topic-Policy",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "SNS:Publish",
        "SNS:RemovePermission",
        "SNS:SetTopicAttributes",
        "SNS:DeleteTopic",
        "SNS:ListSubscriptionsByTopic",
        "SNS:GetTopicAttributes",
        "SNS:Receive",
        "SNS:AddPermission",
        "SNS:Subscribe"
      ],
      "Resource": "${region}",
      "Condition": {
        "StringEquals": {
          "AWS:SourceOwner": "${aws-account}"
        }
      }
    }
  ]
}
```
Error:
```
Error: Invalid index

  on ../../modules/sns/main.tf line 18, in resource "aws_sns_topic_policy" "CW-alerts-topic-policy":
  18:   arn   = aws_sns_topic.CW-alerts[count.index].arn
    |----------------
    | aws_sns_topic.CW-alerts is empty tuple
    | count.index is 2

The given key does not identify an element in this collection value.


Error: Invalid index

  on ../../modules/sns/main.tf line 18, in resource "aws_sns_topic_policy" "CW-alerts-topic-policy":
  18:   arn   = aws_sns_topic.CW-alerts[count.index].arn
    |----------------
    | aws_sns_topic.CW-alerts is empty tuple
    | count.index is 0

The given key does not identify an element in this collection value.


Error: Invalid index

  on ../../modules/sns/main.tf line 18, in resource "aws_sns_topic_policy" "CW-alerts-topic-policy":
  18:   arn   = aws_sns_topic.CW-alerts[count.index].arn
    |----------------
    | aws_sns_topic.CW-alerts is empty tuple
    | count.index is 1

The given key does not identify an element in this collection value.


Error: Invalid index

  on ../../modules/sns/outputs.tf line 18, in resource "null_resource" "topic-mappings":
  18:     topic-id = aws_sns_topic.CW-alerts[count.index].id
    |----------------
    | aws_sns_topic.CW-alerts is empty tuple
    | count.index is 2

The given key does not identify an element in this collection value.


Error: Invalid index

  on ../../modules/sns/outputs.tf line 18, in resource "null_resource" "topic-mappings":
  18:     topic-id = aws_sns_topic.CW-alerts[count.index].id
    |----------------
    | aws_sns_topic.CW-alerts is empty tuple
    | count.index is 0

The given key does not identify an element in this collection value.


Error: Invalid index

  on ../../modules/sns/outputs.tf line 18, in resource "null_resource" "topic-mappings":
  18:     topic-id = aws_sns_topic.CW-alerts[count.index].id
    |----------------
    | aws_sns_topic.CW-alerts is empty tuple
    | count.index is 1

The given key does not identify an element in this collection value.
```

### Debug Output
```
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalWriteOutput, err: Invalid function argument: Invalid value for "args" parameter: argument 2 has length 0, which is inconsistent with argument 1 of length 3.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalOpFilter, err: Invalid function argument: Invalid value for "args" parameter: argument 2 has length 0, which is inconsistent with argument 1 of length 3.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalSequence, err: Invalid function argument: Invalid value for "args" parameter: argument 2 has length 0, which is inconsistent with argument 1 of length 3.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalDiff, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalSequence, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalDiff, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalSequence, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalDiff, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalSequence, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalDiff, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalSequence, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalDiff, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalSequence, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalDiff, err: Invalid index: The given key does not identify an element in this collection value.
2020/11/24 11:13:03 [ERROR] module.sns: eval: *terraform.EvalSequence, err: Invalid index: The given key does not identify an element in this collection value.
```
Am I doing something wrong or there is something different in eu-west-2?

**Comment by jbardin** [comment] 2020-11-24 17:13
Hi @80kk 

This appears at first glance to be a problem caused by the refresh phase working with state that does not match the configuration. There's a good chance this particular case will be successfully handled by terraform 0.13, and the possibility of this type of bug eliminated by 0.14 which removes the separate refresh phase.

Do you have a way to test the infrastructure with a more current version of terraform?

**Comment by 80kk** [comment] 2020-11-24 17:21
No, not really. State is kept in common for all modules dynamodb table. Entire infrastructure has been built in 0.12.

**Comment by jbardin** [comment] 2021-04-01 19:58
Closing this out as we do not have a reproduction with the current release.
If this can be reproduced with 0.14 or 0.15, please file a new issue with the necessary information to reproduce it. 

Thanks!

**Closed by jbardin** 2021-04-01 19:58 UTC
Labels: bug, new, v0.12, waiting for reproduction
