### ISSUE TITLE
No Progress Info during plugin downloads

### ISSUE THREAD

**Issue by sanspace** [hashicorp/terraform#25098] opened 2020-06-01 14:18 UTC
### Current Terraform Version

```
Terraform v0.12.26
```

### Use-cases
While `terraform init` ing the first time and using a heavy provider like aws (~200MB), with a slow network, I have no clue what's going on. I'm just looking at the downloading msg without any indication of the download progress, speed or status (how would i know if it's just hanging!?).

```terraform
terraform {
  required_version = ">= 0.12.20"
  required_providers {
    aws = ">= 2.64.0"
    archive = "~> 1.3"
  }
}
```

### Attempted Solutions
NA

### Proposal
I'm not a golang expert. But, I believe you could somehow keep the user informed about the download progress (percentage or X out of Y MBs), speed ( X Mbps) and staus (a progress bar!?).

### References
I couldn't find any. But, if there's already one, please close this one and I'll follow the original.

**Comment by pkolyvas** [comment] 2020-06-01 14:53
Hi @sanspace - thanks for the suggestion. I am going to close it however, as I believe it's a duplicate of https://github.com/hashicorp/terraform/issues/24693

**Closed by pkolyvas** 2020-06-01 14:53 UTC
Labels: enhancement
