### ISSUE TITLE
Make it possible to `state rm` certain resources during `destroy` via the `lifecycle{}` block

### ISSUE THREAD

**Issue by spkane** [hashicorp/terraform#34679] opened 2024-02-14 21:52 UTC
### Terraform Version

```shell
All || N/A
```

### Use Cases

The core idea is to create a way to tell Terraform to remove a resource from the state file during a `destroy` workflow instead of contacting the owning API to delete the object.

This would make it possible to handle nested objects, like `kubernetes_namespace` resources, that exist inside a Kubernetes cluster, which you will destroy in the same workflow, but you do not need Terraform to remove via the owning API.

### Attempted Solutions

Hashicorp would recommend that people use a single Terraform workflow to spin up a k8s cluster and then install things into that cluster in another Terraform workflow.

However, there are many times that at least some bootstrapping will occur in the initial Terraform workflow. This fix would allow users to quickly identify resources that need not be destroyed via their API.

### Proposal

```hcl
lifecycle { 
  # This would cause Terraform to remove the resource from the state file instead of calling the owning API to delete.
  state_only_destroy = true
}
```

**Comment by jbardin** [comment] 2024-02-14 22:57
Duplicate of #15485

Also related to #34439 and possible new features of `removed` blocks.

**Closed by jbardin** 2024-02-14 22:57 UTC
Labels: enhancement, new
