### ISSUE TITLE
Regression 0.7: output with join where underlying count is variable

### ISSUE THREAD

**Issue by darrensony** [hashicorp/terraform#8288] opened 2016-08-18 15:54 UTC
Quick summary (my understanding)

1. Define a variable 
2. Use that variable as "count" in a resource
3. Create csv-like output with Join over resource.*.id
4. Join fails because count doesn't interpolate in output code path.
5. Terraform 0.7 doesn't generate the output, nor does it give an error.

### Terraform Version
Terraform v0.7.0

### Affected Resource(s)
- output

### Terraform Configuration Files
NOTE: Example, not full config

```hcl
## Constants
variable "aznames" {
  default = {
    "0" = "a"
    "1" = "b"
    "2" = "c"
    "3" = "d"
  }
}

## Variables -- Injected by Wrapper
variable "num_az" { default = "3" }
variable "in_region_aws" { default = "us-west-2" }
variable "netblock_cidr" { default = "10.0.0.0/22" }
variable "subnet_netbits" { default = "3" }

## Create "num_az" subnets
resource "aws_subnet" "sn_internal"
{
  count = "${var.num_az}" 
  availability_zone = "${format("%s%s",var.in_region_aws,lookup(var.aznames,count.index))}"
  vpc_id = "${terraform_remote_state.parent_infra.vpc_id}"
  cidr_block = "${cidrsubnet(var.netblock_cidr, var.subnet_netbits, count.index * 2 )}"   
  } 
}   

## !!! THIS "output" IS NOT GENERATED
output "subnets_internal_csv" {
  value = "${join(",", aws_subnet.sn_internal.*.id)}"
}

## [TRACE] Error reading aws_subnet.sn_internal count: 
##     strconv.ParseInt: 
##        parsing "${var.envblock_num_az}": invalid syntax
```

### Debug Output
NOTE: not full debug, just part in question
2016/08/18 08:29:43 [TRACE] [walkPlan] Entering eval tree: output.subnets_internal_csv
2016/08/18 08:29:43 [WARN] Output interpolation "subnets_internal_csv" failed: Error reading aws_subnet.sn_internal count: strconv.ParseInt: parsing "${var.envblock_num_az}": invalid syntax
2016/08/18 08:29:43 [TRACE] [walkPlan] Exiting eval tree: output.subnets_internal_csv

### Expected Behavior
1. It should work like in 0.6.*, aka generate a CSV output value
2. Failure to generate an output should be a fatal error.

### Actual Behavior
The output is not present in the state file. No error or warning was raised.

### Steps to Reproduce
1. `terraform apply`

**Comment by giandvd** [comment] 2016-08-24 19:26
Related to/duplicate of https://github.com/hashicorp/terraform/issues/8124. My testcase is shorter.

**Comment by mitchellh** [comment] 2016-08-31 19:21
Agreed I'm going to use #8124 since the repro case is simpler. Thanks!

**Closed by mitchellh** 2016-08-31 19:21 UTC
Labels: bug, core
