### ISSUE TITLE
Addition of new subnets caused aws_route to have mismatched diffs during apply

### ISSUE THREAD

**Issue by jeffbyrnes** [hashicorp/terraform#8831] opened 2016-09-13 22:54 UTC
Reporting this, as requested by Terraform itself when the error occurred.
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)
- `aws_route`
### Terraform Configuration Files

https://gist.github.com/jeffbyrnes/198617d0b1883fd0951629a7b0949064
### Debug Output

https://gist.github.com/jeffbyrnes/9a9a6e2094350bceba87f15dc7d5166a
### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
### Expected Behavior

Added a set 
### Actual Behavior

The `apply` seemed to fail, but subsequent `apply` runs work fine, and do not report any issues.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
### Important Factoids

Nothing unusual AFAIK
### References

n/a

**Comment by chrisrlong** [comment] 2016-09-14 10:26
Hi,

I have this same error on Terraform 0.7.2 but with an aws_instance:

> 1 error(s) occurred:

* aws_instance.bastion.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.2
    Resource ID: aws_instance.bastion.1
    Mismatch reason: extra attributes: tags.%, vpc_security_group_ids.1517382784, ami, tags.Name, placement_group, public_ip, instance_state, public_dns, private_ip, tenancy, vpc_security_group_ids.601889925, security_groups.#, private_dns, instance_type, key_name, subnet_id, network_interface_id, ebs_block_device.#, vpc_security_group_ids.2405011966, source_dest_check, tags.VPC, vpc_security_group_ids.#, availability_zone, root_block_device.#, ephemeral_block_device.#, vpc_security_group_ids.2955398128
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{}, Destroy:false, DestroyTainted:true}

**Comment by mitchellh** [comment] 2016-11-17 00:53
Hello! This should be fixed in later versions of Terraform (0.7.11 at time of writing). 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 00:53 UTC
Labels: bug, provider/aws

**Comment by Legogris** [comment] 2018-07-23 10:44
@mitchellh I get this too. I have existing EC2 instances that I have imported and I get this when I am attempting my first apply (no new VPCs have actually been added AFAIK):

```
    Terraform Version: 0.11.7
    Resource ID: aws_instance.xchange_cassandra_node.0
    Mismatch reason: extra attributes: vpc_security_group_ids.2939898124, vpc_security_group_ids.#, vpc_security_group_ids.4272543184, vpc_security_group_ids.2856951048, vpc_security_group_ids.629327206
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tags.cassandra_token":*terraform.ResourceAttrDiff{Old:"num_tokens: 256", New:"num_tokens: 256",
NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Service":*terraform.ResourceAttrDiff{Old:"Cassandra", New:"Cassandra", NewComputed:false, NewRemoved:false, NewExtra:int$
rface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.ResourceAttrDiff{Old:"", New:"production", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Ty$
e:0x0}, "tags.Os":*terraform.ResourceAttrDiff{Old:"ubuntu", New:"ubuntu", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Opscenter":*terraform.ResourceAttrDiff{Old:"ma$
n", New:"main", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "iam_instance_profile":*terraform.ResourceAttrDiff{Old:"", New:"cassandra-production-ec2-service", NewComputed$
false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.dc_suffix":*terraform.ResourceAttrDiff{Old:"_cassandra_fast", New:"_cassandra_fast", NewComputed:false, NewRemoved:false, NewExtra:i$terface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.ddmonitoring":*terraform.ResourceAttrDiff{Old:"mainnet", New:"mainnet", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:fa$se, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"DSE - Fast", New:"us-east-1-production-cassandra-1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*ter$aform.ResourceAttrDiff{Old:"7", New:"8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}                                                                                                                                                                                                                                           Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tags.ddmonitoring":*terraform.ResourceAttrDiff{Old:"mainnet", New:"mainnet", NewComputed:false$ NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_security_group_ids.4272543184":*terraform.ResourceAttrDiff{Old:"sg-9b9240ff", New:"", NewComputed:false, NewRemoved:true, NewExtra:interfac$ {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.ResourceAttrDiff{Old:"", New:"production", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x$}, "vpc_security_group_ids.2856951048":*terraform.ResourceAttrDiff{Old:"sg-d49341b0", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Opscenter":*terraform.Resou$ceAttrDiff{Old:"main", New:"main", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"DSE - Fast", New:"us-east-1-production-cassand$
a-1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.cassandra_token":*terraform.ResourceAttrDiff{Old:"num_tokens: 256", New:"num_tokens: 256", NewComputed:false, NewR$moved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.dc_suffix":*terraform.ResourceAttrDiff{Old:"_cassandra_fast", New:"_cassandra_fast", NewComputed:false, NewRemoved:false, NewExtra:interface {}($il), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"7", New:"8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "iam_instance_profi$e":*terraform.ResourceAttrDiff{Old:"", New:"cassandra-production-ec2-service", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Os":*terraform.ResourceAttrDiff{Old:"ubun$u", New:"ubuntu", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Service":*terraform.ResourceAttrDiff{Old:"Cassandra", New:"Cassandra", NewComputed:false, NewRemoved:f$lse, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_security_group_ids.2939898124":*terraform.ResourceAttrDiff{Old:"sg-db4594bf", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), Req$iresNew:false, Sensitive:false, Type:0x0}, "vpc_security_group_ids.#":*terraform.ResourceAttrDiff{Old:"3", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_secur$ty_group_ids.629327206":*terraform.ResourceAttrDiff{Old:"", New:"sg-c7da4d8d", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTa$nted:false, Meta:map[string]interface {}(nil)}
```

**Comment by Legogris** [comment] 2018-07-23 11:14
Update: My issue above arose becaus ethe existing instances had security groups that were not defined in my template. Instructing Terraform to add these security groups to the instances in the template resolved this.
