### ISSUE TITLE
Ignoring lifecycle events based on local variable

### ISSUE THREAD

**Issue by andrei-dascalu** [hashicorp/terraform#32596] opened 2023-01-29 14:34 UTC
### Terraform Version

```shell
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.52.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Terraform Configuration Files

```terraform
locals {
  ignored_lifecycle_events = var.ignore_desired_capacity_change ? ["desired_capacity"] : []
}

resource "aws_launch_template" "cluster" {
...

  lifecycle {
    create_before_destroy = true
    ignore_changes = local.ignored_lifecycle_events
  }
}
```

### Debug Output

https://gist.github.com/andrei-dascalu/8371111bb72989f8d4efaaa20ec13639

### Expected Behavior

configuration should be ok

### Actual Behavior

╷
│ Error: Invalid expression
│ 
│   on asg.tf line 100, in resource "aws_autoscaling_group" "cluster":
│  100:     ignore_changes = local.ignored_lifecycle_events
│ 
│ A static list expression is required.

### Steps to Reproduce

1. `terraform init`

### Additional Context

Now, if I simply pass a variable directly to the `ignore_changes` whether as a list or string that is then placed in a list, all is good

eg (this works):

```
  lifecycle {
    create_before_destroy = true
    ignore_changes = var.ignored_lifecycle_events
  }
```

this doesn't:

```
  lifecycle {
    create_before_destroy = true
    ignore_changes = local.ignored_lifecycle_events
  }
```

even though the local variable is still rather static, based on a boolean variable which results in a hardcoded list or empty list (both which would be valid if passed through a variable).

```
locals {
  ignored_lifecycle_events = var.ignore_desired_capacity_change ? ["desired_capacity"] : []
}
```

**Comment by jbardin** [comment] 2023-01-30 16:24
Hi @andrei-dascalu,

The `ignore_changes` lifecycle attribute takes a list of relative attribute references to the parent object, not strings, so it is not possible to interpolate the local value for that purpose. Since terraform is working as designed here, this does not represent a bug so I'm going to close the issue. If you have more questions is better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. 

Thanks!

**Closed by jbardin** 2023-01-30 16:24 UTC
Labels: bug, new, working as designed
