### ISSUE TITLE
TLS handshake error while apply/plan

### ISSUE THREAD

**Issue by anandmohan8** [hashicorp/terraform#24667] opened 2020-04-14 19:39 UTC
We are getting below TLS exceptions (more often now) when the code is trying to make connection to backend config. This happens the first time we run the deploy job and when we re-run , it does not throw this exception. Do you know why would this exception be thrown for the first time. We use CircleCI for CICD.

data.terraform_remote_state.alb: data.terraform_remote_state.alb: error initializing backend: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: net/http: TLS handshake timeout

2020/03/31 23:35:09 [DEBUG] [aws-sdk-go] DEBUG: Send Request sts/GetCallerIdentity failed, not retrying, error RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: net/http: TLS handshake timeout
2020/03/31 23:35:09 [DEBUG] plugin: waiting for all plugin processes to complete...
Failed to load backend:
Error configuring the backend "s3": RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: net/http: TLS handshake timeout

**Comment by danieldreier** [comment] 2020-04-14 20:29
Hello @anandmohan8! Thanks for reaching out. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

From the information you've posted, it looks to me like for some reason, the S3 backend is unable to reach AWS at the network layer. This seems puzzling, and I imagine it's frustrating, but it's not evidence evidence of a bug in Terraform core.  For what it's worth, we also use CircleCI in our own testing, and have not had similar problems.

I'm going to close this for now, because I think the community forum is the right approach. My recommendation is that when you post there, you include a few full output logs, as well as your terraform backend configuration, and as many details as you can about your CircleCI build environment, so that other community members can help reproduce the issue. If you do end up with evidence of a bug, please come back and report an issue using the standard issue template.

**Closed by danieldreier** 2020-04-14 20:29 UTC
