### ISSUE TITLE
terraform not sync state from s3, apply will create all resources as new

### ISSUE THREAD

**Issue by robertchen** [hashicorp/terraform#24063] opened 2020-02-08 01:41 UTC
Our team save the terraform state on s3, I have the access to this s3. When I do terraform apply or plan, it will apply/plan to create all of the resources as new. 

Plan: 77 to add, 0 to change, 5 to destroy.

### Terraform Version

```
$ terraform -v
Terraform v0.12.13
+ provider.aws v2.48.0
+ provider.helm v1.0.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1

```

### Terraform Configuration Files
```hcl
variable "access_key" {
  default = "****"
}

variable "secret_key" {
  default = "******"
}

terraform {
  required_version = ">= 0.12.0"

  backend "s3" {
    bucket = "terraform-mystate"
    access_key = "*****"
    secret_key = "*****"
    # Please change the name to the appropriate state file
    key = "key1/key2/helm/terraform.tfstate"
    region = "us-west-2"
  }
}

provider "aws" {
  region = var.aws_region
  # Comment out on unix or define in values.rtf
  access_key = var.access_key
  secret_key = var.secret_key
}

```

### Debug Output
There is no specific errors.
.terraform/terraform.tfstate:
```
{
    "version": 3,
    "serial": 1,
    "lineage": "5ca53c54-111b-2f93-38c1-5acc120b1615",
    "backend": {
        "type": "s3",
        "config": {
            "access_key": "****",
            "acl": null,
            "assume_role_policy": null,
            "bucket": "terraform-mystate",
            "dynamodb_endpoint": null,
            "dynamodb_table": null,
            "encrypt": null,
            "endpoint": null,
            "external_id": null,
            "force_path_style": null,
            "iam_endpoint": null,
            "key": "key1/key2/helm/terraform.tfstate",
            "kms_key_id": null,
            "lock_table": null,
            "max_retries": null,
            "profile": null,
            "region": "us-west-2",
            "role_arn": null,
            "secret_key": "*******",
            "session_name": null,
            "shared_credentials_file": null,
            "skip_credentials_validation": null,
            "skip_get_ec2_platforms": null,
            "skip_metadata_api_check": null,
            "skip_region_validation": null,
            "skip_requesting_account_id": null,
            "sse_customer_key": null,
            "sts_endpoint": null,
            "token": null,
            "workspace_key_prefix": null
        },
        "hash": 1405786106
    },
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```
the debug output has many private information, so not put here. But all are Refreshing state... and Terraform will perform the following actions...

### Expected Behavior
Should not create all resources, should get state from the s3

### Actual Behavior
It is not getting state from s3. 

Reference: 
https://github.com/hashicorp/terraform/issues/9089

**Comment by jbardin** [comment] 2020-02-11 15:57
Hi @robertchen,

Sorry you're having an issue here. The plan output of `Plan: 77 to add, 0 to change, 5 to destroy.` indicates that there is some state being accessed, because there are 5 resources that are being destroyed.

Can you provide the exact steps to reproduce the issue? Chances are that you are somehow access different states in each case.

**Comment by danieldreier** [comment] 2020-04-28 00:11
I'm going to close this issue because it's been waiting for a response since February 11th. If you're still having this issue, please feel free to let us know, and make sure to link this issue if you file a new one so that we have that context. 

If you're not quite sure whether it's an bug or a question, you might post on [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

**Closed by danieldreier** 2020-04-28 00:11 UTC
Labels: backend/s3, bug, v0.12, waiting-response
