### ISSUE TITLE
Add debug logging to cloudstack provider

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform#3175] opened 2015-09-06 13:57 UTC
I'm happy to provide a PR for this, I wanted to check on the general policy for debug logging first.

At the moment it can be a little tricky to debug cloudstack failures, as there's nothing in the logs to show which API was called, and with what parameters.

I can see two options here to improve this story
1. Add debug logging capabilities into `go-cloudstack`, based on an environment variable
2. Add debug logging next to every `go-cloudstack` api call in the terraform profider, which would respect `TF_LOG`

The latter would probably be simpler, as it it doesn't require a new way of enabling debug logging. Is there a general policy for what should or shouldn't be included in the TF_LOG output?

**Comment by svanharmelen** [comment] 2015-09-28 01:43
@phinze I don't think there is a policy for this right? As long as common sense is used, it should be fine IMHO...

**Comment by phinze** [comment] 2015-09-28 06:07
Agreed! @glenjamin you can just go ahead with (2) and add debug logging to the provider.

**Comment by svanharmelen** [comment] 2015-10-05 21:58
@glenjamin are you ok with me closing this one? Think your question is answered and your good to go write some logging right?

Also please keep an eye on PR #3380 as it seems that one will be merged shortly and it improves/extends the logging capabilities if TF.

**Comment by glenjamin** [comment] 2015-10-05 22:08
It's vaguely on my todo, might be better off keeping it open in case someone else wants to pick it up?

**Comment by svanharmelen** [comment] 2015-10-05 22:35
Well in that case I'll go ahead and close it off... :wink: With well over 500 open issues I don't think it adds much value to leave this one open as well. Especially since the question in the issue is answered and can be found back for others when searching through the issues.

Thanks!

**Closed by svanharmelen** 2015-10-05 22:35 UTC
Labels: enhancement, provider/cloudstack
