### ISSUE TITLE
Problems with the pound-sign character when feeding local-exec's command with template_file.rendered

### ISSUE THREAD

**Issue by jonapich** [hashicorp/terraform#5151] opened 2016-02-16 20:26 UTC
[EDIT: I originally wrote the issue for the dollar sign, but it is in fact the pound sign. sorry about that.]

I am using a template_file to generate a complex string, and then using the string into a local-exec command:

```
resource "template_file" "config" {
  template = "${region} ${lambda_name} ${uri} ${user} ${password}"
  vars {removed}

  provisioner "local-exec" {
    command = "python ./launch_init.py setconfig ${template_file.config.rendered}"
  }
}
```

The problem is that the password may contain special characters. Among those, the dollar sign doesn't seem to be correctly handled and is passed as-is, gets interpreted by the shell which abruptly ends the command.

Adding just double-quotes to the template fails parsing. Using single quotes doesn't help either. Using \" works, but then the script receives it verbatim and stores the password with the \" stuff.

I have made sure that the script behaves well with this syntax from command line:

`python ./launch_init.py setconfig us-east-1 lambda_name https://server.endpoint masteruser "password$withdollarsign"`

Any way around this?

Does #785 fix this?

**Comment by muikrad** [comment] 2016-02-16 20:40
Something else I tried is to format it at the vars level:

```
resource "template_file" "config" {
  template = "${region} ${lambda_name} ${uri} ${user} ${password}"
  vars { password = "${format("%q", var.janitor_password)}" }
}
```

In that case, the behavior is the same as if I wrote `\"${password}\"` in the template directly. Backslashes are sent to the script.

**Comment by Bowbaq** [comment] 2016-02-16 21:40
I ran into this as well, I was trying to use [indirect references](http://www.tldp.org/LDP/abs/html/ivr.html) and the `eval FOO=\$$BAR` syntax wasn't working out

**Comment by catsby** [comment] 2016-02-16 22:34
Hey @muikrad , are you getting an error message?

I tried this with single `'` marks and it worked as I _think_ you're trying:

```
variable "thing" {}  # Terraform prompts for this, I entered before$after
resource "template_file" "config" {
  template = "${var.thing}"

  provisioner "local-exec" {
    command = "echo hello '${var.thing}'"
  }
}

output "out" {
  value = "${template_file.config.rendered}"
}
```

Here's the output I got:

```
$ terraform apply .
var.thing
  Enter a value: before$after

template_file.config: Refreshing state... (ID: feb54ea74e2388145622a064ca1f00917f8e1f9147018a0fa90015c2f66b2ec0)
template_file.config: Destroying...
template_file.config: Destruction complete
template_file.config: Creating...
  rendered: "" => "<computed>"
  template: "" => "before$after"
template_file.config: Provisioning with 'local-exec'...
template_file.config (local-exec): Executing: /bin/sh -c "echo hello 'before$after'"
template_file.config (local-exec): hello before$after
template_file.config: Creation complete

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

Outputs:

  out = before$after
```

**Comment by Bowbaq** [comment] 2016-02-16 22:50
@catsby here is a quick way to reproduce what I noticed (which I'm pretty sure is related)

```
resource "null_resource" "test" {
  provisioner "local-exec" {
    command = <<COMMAND

    TARGET_ONE="Hello World One"
    TARGET_TWO="Hello World Two"

    for T in "ONE" "TWO"; do
      TARGET_NAME="TARGET_$T"
      eval GREETING=\$$TARGET_NAME
      echo "$GREETING"
    done

COMMAND
  }
}
```

Running `terraform apply`:
```
-> % terraform apply 
null_resource.test: Creating...
null_resource.test: Provisioning with 'local-exec'...
null_resource.test (local-exec): Executing: /bin/sh -c "
null_resource.test (local-exec):     TARGET_ONE="Hello World One"
null_resource.test (local-exec):     TARGET_TWO="Hello World Two"
null_resource.test (local-exec):     for T in "ONE" "TWO"; do
null_resource.test (local-exec):       TARGET_NAME="TARGET_$T"
null_resource.test (local-exec):       eval GREETING=\$TARGET_NAME
null_resource.test (local-exec):       echo "$GREETING"
null_resource.test (local-exec):     done
null_resource.test (local-exec): "
null_resource.test (local-exec): TARGET_ONE
null_resource.test (local-exec): TARGET_TWO
null_resource.test: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
Notice how that `\$$` turned into `\$` and of course the output is wrong, it should be:
```
Hello World One
Hello World Two
```
This script works as intended in bash

**Comment by muikrad** [comment] 2016-02-16 23:37
@catsby you are right, it works and the single quotes don't make it to the script.

The offending character is in fact `&` (sorry about that).

Here's some test code to play with. I can make it work from command line using `python ./setconfig.py test "some&password"`.

foo.tf:
```
resource "template_file" "setconfig" {
  template = "${password}"

  vars {
    password = "some&password"
  }

  provisioner "local-exec" {
    command = "python ./setconfig.py test '${template_file.setconfig.rendered}'"
  }
}
```

setconfig.py:

```
import baker
@baker.command
def test(value):
    print('--> {} <--'.format(value))
    assert value == 'some&password'

baker.run()
```

**Comment by muikrad** [comment] 2016-02-17 02:06
implementing #2342 would let me workaround the issue nicely too.

**Comment by mitchellh** [comment] 2016-11-22 18:35
This should be fixed now!

**Closed by mitchellh** 2016-11-22 18:35 UTC
Labels: bug, provider/template, waiting-response
