### ISSUE TITLE
Glob pattern negating does not work for Terraform Cloud provider

### ISSUE THREAD

**Issue by AndrewDryga** [hashicorp/terraform#28110] opened 2021-03-16 15:04 UTC
`.terraformignore`:
```
*
!rel/deployment/**.*
!rel/deployment
```

Log for `terraform apply`:

```
...
Skipping excluded path: rel/deployment/terraform/modules/talkinto-app
Skipping excluded path: rel/deployment/terraform/modules/talkinto-app/catalog_db_seeds.sql
Skipping excluded path: rel/deployment/terraform/modules/talkinto-app/dns-records.tf
Skipping excluded path: rel/deployment/terraform/modules/talkinto-app/main.tf
Skipping excluded path: rel/deployment/terraform/modules/talkinto-app/outputs.tf
Skipping excluded path: rel/deployment/terraform/modules/talkinto-app/user_permissions.sql
Skipping excluded path: rel/deployment/terraform/modules/talkinto-app/variables.tf
...
```

**Comment by alisdair** [comment] 2021-03-16 17:50
Hi @AndrewDryga, thanks for reporting this.

After investigating this, I think the `.terraformignore` rules you specified might be the source of this problem. I don't think that `**.*` is valid, and if you instead write `**/*.*` I think you'll see the effect you're hoping for.

From [the docs on `.gitignore` files](https://git-scm.com/docs/gitignore), upon which `.terraformignore` is based:

> Two consecutive asterisks ("**") in patterns matched against full pathname may have special meaning:
>
> - A leading "`**`" followed by a slash means match in all directories. For example, "`**/foo`" matches file or directory "`foo`" anywhere, the same as pattern "`foo`". "`**/foo/bar`" matches file or directory "`bar`" anywhere that is directly under directory "`foo`".
>
> - A trailing "`/**`" matches everything inside. For example, "`abc/**`" matches all files inside directory "`abc`", relative to the location of the `.gitignore` file, with infinite depth.
>
> - A slash followed by two consecutive asterisks then a slash matches zero or more directories. For example, "`a/**/b`" matches "`a/b`", "`a/x/b`", "`a/x/y/b`" and so on.
>
> - Other consecutive asterisks are considered regular asterisks and will match according to the previous rules.

As a result of not having a slash after the double-asterisk, I think the pattern is being interpreted as `!rel/deployment/*.*`, which then correctly skips the files in subdirectories.

### Reproduction attempt

Here's what I did to try to reproduce the bug.

1. Create `main.tf`:

    ```hcl
    terraform {
      backend "remote" {
        organization = "alisdair-v2"
        workspaces {
          name = "28110"
        }
      }
    }

    module "c" {
      source = "./a/b/c"
    }
    ```
2. Create a/b/c/d.tf:

    ```hcl
    resource "null_resource" "none" {}
    ```
3. Create .terraformignore:
    ```gitignore
    *
    !main.tf
    !a/b/**/*.*
    ```
4. Run `terraform init` and `terraform apply` to see the run complete including the `null_resource`

(I couldn't figure out how to see the `Skipping excluded path` logs, even with `TF_LOG=trace`. If you can suggest how to do that I'd be grateful!)

I'm marking this as closed for now because I don't think there's a bug here. If I'm mistaken, please point out what to change in my simple reproduction case, and I'd be happy to look into it further. Thanks!

**Closed by alisdair** 2021-03-16 17:50 UTC
Labels: bug, new

**Comment by AndrewDryga** [comment] 2021-03-16 18:45
@alisdair Thank you, I will check this out In a second. The doc how to print that is here: https://www.terraform.io/docs/cli/config/environment-variables.html#tf_ignore

**Comment by AndrewDryga** [comment] 2021-03-16 20:18
@alisdair looks like you right and it works indeed, I must say that there is a separate issue with degraded performance if the project is big. You can test it by adding lots of files that would be ignored and running `terraform apply` for manifests you generated above.

For me it takes ~1 minute to upload less than 500 Kb of Terraform scripts because Terraform still iterates over thousands of files in project. (Especially `node_modules`.)
