### ISSUE TITLE
Cannot use length when referencing values from terraform remote state

### ISSUE THREAD

**Issue by gposton** [hashicorp/terraform#3142] opened 2015-09-01 20:15 UTC
We have a template to create a VPC with a dynamic number of subnets (passed in using a terraform variable)

https://gist.github.com/gposton/eeff5c05be3bbd3dc277

We also have a template that creates a NAT server for each AZ created by the VPC template.

https://gist.github.com/gposton/042460050e5e5b8652ec#file-nat-tf-L91

The VPC outputs a comma-delimited list of AZs and subnet ids.

We want to use this list to determine how many NAT instances to create (1 for each AZ/subnet).

We attempted to use the length parameter (https://gist.github.com/gposton/042460050e5e5b8652ec#file-nat-tf-L91), but get this error:

    Errors:
      * 1 error(s) occurred:
      * module root: 3 error(s) occurred:

        * aws_route_table.route-table-private: resource count can't reference resource variable: terraform_remote_state.vpc.output.availability_zones
        * aws_route_table_association.rt-association-private: resource count can't reference resource variable: terraform_remote_state.vpc.output.availability_zones
        * aws_instance.nat-primary: resource count can't reference resource variable: terraform_remote_state.vpc.output.availability_zones

This error comes from here (https://github.com/hashicorp/terraform/blob/master/config/config.go#L385) in the terraform code base, but I'm unclear on why this is hardcoded to produce an error.

**Comment by pll** [comment] 2016-03-01 22:19
+1

I just tried to do this exact thing.  What's the point of exporting a remote state if I can't actually use anything stored there?

**Comment by radeksimko** [comment] 2016-07-09 14:12
This looks like a duplicate of https://github.com/hashicorp/terraform/issues/1497

@gposton Do you mind if we close this issue in favour of #1497 ?

Paul provides more details about the issue in https://github.com/hashicorp/terraform/issues/1497#issuecomment-105874601

**Comment by mitchellh** [comment] 2016-08-22 21:30
Closing as dup.

**Closed by mitchellh** 2016-08-22 21:30 UTC
Labels: bug, core
