### ISSUE TITLE
Allow usage of output variables within module

### ISSUE THREAD

**Issue by dvega-flexion** [hashicorp/terraform#34085] opened 2023-10-14 23:16 UTC
### Terraform Version

```shell
1.5.5
```

### Use Cases

Defining variables closest to where they are first/most used, I've found myself placing them close to the outputs. However, this seems like a refactoring opportunity

```hcl
resource "google_runtimeconfig_variable" "cloudrun_service_url" {
  provider = google-beta
  parent   = data.google_runtimeconfig_config.runtimeconfig.name

  name = var.service_url_runtimeconfig_var_name
  text = local.service_url
}

locals {

  # FQDN for subtomain for microservice, if none defined, provide the autogenerated URL
  service_url = var.fqdn.subdomain.name != "" ? (
    "https://${var.fqdn.subdomain.prefix}${var.api_service_name}${var.fqdn.subdomain.suffix}-${var.branch == "main"?"":"-${var.branch}"}.${var.fqdn.base_domain}"
  ) : google_cloud_run_service.default.status[0].url
}

output "service_url" {
  value = local.service_url
}
```

### Attempted Solutions

Same as use case. When using that same value for other resources, it technically is a duplicated variable. 

### Proposal

Based on the previous use case / workaround solution. Using the same variable can make sense, plus, it would be more intuitive and functional to use the description field. It would also encourage better maintenance, documentation and use of output variables:

```hcl
resource "google_runtimeconfig_variable" "cloudrun_service_url" {
  provider = google-beta
  parent   = data.google_runtimeconfig_config.runtimeconfig.name

  name = var.service_url_runtimeconfig_var_name
  text = output.service_url
}


output "service_url" {
 description = "FQDN for subtomain for microservice, if none defined, provide the autogenerated URL"
  value = var.fqdn.subdomain.name != "" ? (
    "https://${var.fqdn.subdomain.prefix}${var.api_service_name}${var.fqdn.subdomain.suffix}-${var.branch == "main"?"":"-${var.branch}"}.${var.fqdn.base_domain}"
  ) : google_cloud_run_service.default.status[0].url
}
```

An alternative notation that could also put this feature in perspective would be using a keyword before variable declaration/definition

```hcl
locals {

  # FQDN for subtomain for microservice, if none defined, provide the autogenerated URL
  output service_url = var.fqdn.subdomain.name != "" ? (
    "https://${var.fqdn.subdomain.prefix}${var.api_service_name}${var.fqdn.subdomain.suffix}-${var.branch == "main"?"":"-${var.branch}"}.${var.fqdn.base_domain}"
  ) : google_cloud_run_service.default.status[0].url
}
```
In this later implementation this could simplify usage for cases where the variable is better read as `local.service_url`

**Comment by liamcervante** [comment] 2023-10-16 11:19
Hi @dvega-flexion, thanks for the request. This is a duplicate of https://github.com/hashicorp/terraform/issues/17144, and you can have a look through there to see the discussion so far.

**Closed by liamcervante** 2023-10-16 11:19 UTC
Labels: enhancement, new
