### ISSUE TITLE
terraform lifecycle ignore_changes not ignored

### ISSUE THREAD

**Issue by beparmentier** [hashicorp/terraform#29496] opened 2021-09-01 09:41 UTC
### Terraform Version

```
$ terraform --version
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_linux_virtual_machine_scale_set" "scalesetsemarchy" {
  for_each                        = local.semarchy_instance
  name                            = each.value.scaleset_name
  resource_group_name             = azurerm_resource_group.rgenv[each.key].name
  location                        = azurerm_resource_group.rgenv[each.key].location
  instances                       = each.value.instances
  sku                             = each.value.sku
  admin_username                  = each.value.adminusername
  admin_password                  = random_password.semarchypasswd[each.key].result
  disable_password_authentication = each.value.disable_password_authentication
  zone_balance                    = each.value.zone_balance
  upgrade_mode                    = each.value.upgrade_mode
  custom_data                     = base64encode(local.templatecloudinitconfigsemarchy)
  zones                           = each.value.zones
  source_image_id                 = azurerm_shared_image.image["${each.key}-semarchy"].id
  health_probe_id                 = azurerm_lb_probe.lb-probe-http[each.key].id

  os_disk {
    storage_account_type = each.value.storage_account_type
    disk_size_gb         = each.value.disk_size_gb
    caching              = each.value.caching
  }

  boot_diagnostics {
    storage_account_uri = azurerm_storage_account.storsemarchy[each.key].primary_blob_endpoint
  }

  automatic_instance_repair {
    enabled = true
  }

  automatic_os_upgrade_policy {
    disable_automatic_rollback  = false
    enable_automatic_os_upgrade = true
  }

  network_interface {
    name                          = "nic"
    primary                       = true
    dns_servers                   = []
    enable_accelerated_networking = true
    ip_configuration {
      name                                         = "internal"
      primary                                      = true
      subnet_id                                    = azurerm_subnet.this["${each.key}-${local.env}-${local.semarchy_layer}"].id
      load_balancer_backend_address_pool_ids       = [azurerm_lb_backend_address_pool.backendpool[each.key].id]
    }
  }

  lifecycle {
    ignore_changes = [
      instances,
      network_interface
    ]
  }

  tags       = local.global_tags
  
  depends_on = [
    azurerm_lb_rule.lb-rule-http
  ]
}
```

### Expected Behavior

Ignore the change on `network_interface` block

### Actual Behavior

```hcl
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
  # azurerm_linux_virtual_machine_scale_set.scaleset[MASKED]["westeurope"] has been changed
  ~ resource "azurerm_linux_virtual_machine_scale_set" "scaleset[MASKED]" {
        id                                                = "/subscriptions/[MASKED]/resourceGroups/rg_npr_int_mdm_integ_we/providers/Microsoft.Compute/virtualMachineScaleSets/vmss-npr-int-mdm-[MASKED]-integ"
        name                                              = "vmss-npr-int-mdm-[MASKED]-integ"
        tags                                              = {
            "bu"                = "int"
            "createdby"         = "terraform"
            "domain"            = "mdm"
            "env"               = "integ"
            "meta_environment"  = "npr"
            "platform"          = "digimdm"
            "project"           = "digimdm"
            "service"           = "[MASKED]"
            "status"            = "used"
            "subscription_name" = "sub_npr_int_digimdm"
            "team"              = "infra:sysops"
        }
        # (27 unchanged attributes hidden)
      ~ network_interface {
            name                          = "nic"
            # (4 unchanged attributes hidden)
          ~ ip_configuration {
              + application_gateway_backend_address_pool_ids = []
              + application_security_group_ids               = []
              + load_balancer_inbound_nat_rules_ids          = []
                name                                         = "internal"
                # (4 unchanged attributes hidden)
            }
        }
        # (5 unchanged blocks hidden)
    }
Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
─────────────────────────────────────────────────────────────────────────────
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
  # azurerm_linux_virtual_machine_scale_set.scaleset[MASKED]["westeurope"] must be replaced
-/+ resource "azurerm_linux_virtual_machine_scale_set" "scaleset[MASKED]" {
      ~ computer_name_prefix                              = "vmss-npr-int-mdm-[MASKED]-integ" -> (known after apply)
      - encryption_at_host_enabled                        = false -> null
      - eviction_policy                                   = "" -> null
      ~ id                                                = "/subscriptions/[MASKED]/resourceGroups/rg_npr_int_mdm_integ_we/providers/Microsoft.Compute/virtualMachineScaleSets/vmss-npr-int-mdm-[MASKED]-integ" -> (known after apply)
        name                                              = "vmss-npr-int-mdm-[MASKED]-integ"
      ~ platform_fault_domain_count                       = 5 -> (known after apply)
      - proximity_placement_group_id                      = "" -> null
        tags                                              = {
            "bu"                = "int"
            "createdby"         = "terraform"
            "domain"            = "mdm"
            "env"               = "integ"
            "meta_environment"  = "npr"
            "platform"          = "digimdm"
            "project"           = "digimdm"
            "service"           = "[MASKED]"
            "status"            = "used"
            "subscription_name" = "sub_npr_int_digimdm"
            "team"              = "infra:sysops"
        }
      ~ unique_id                                         = "be41865d-fb80-4506-b16d-61fc46a6fa1d" -> (known after apply)
        # (21 unchanged attributes hidden)
      + extension {
          + auto_upgrade_minor_version = (known after apply)
          + force_update_tag           = (known after apply)
          + name                       = (known after apply)
          + protected_settings         = (sensitive value)
          + provision_after_extensions = (known after apply)
          + publisher                  = (known after apply)
          + settings                   = (known after apply)
          + type                       = (known after apply)
          + type_handler_version       = (known after apply)
        }
      ~ network_interface {
            name                          = "nic"
            # (4 unchanged attributes hidden)
          ~ ip_configuration {
              - application_gateway_backend_address_pool_ids = [] -> null
              - application_security_group_ids               = [] -> null
              - load_balancer_inbound_nat_rules_ids          = [] -> null
                name                                         = "internal"
                # (4 unchanged attributes hidden)
            }
        }
      ~ os_disk {
            # (4 unchanged attributes hidden)
        }
      - rolling_upgrade_policy { # forces replacement
          - max_batch_instance_percent              = 20 -> null
          - max_unhealthy_instance_percent          = 20 -> null
          - max_unhealthy_upgraded_instance_percent = 20 -> null
          - pause_time_between_batches              = "PT0S" -> null
        }
      + terminate_notification {
          + enabled = (known after apply)
          + timeout = (known after apply)
        }
        # (3 unchanged blocks hidden)
    }
Plan: 1 to add, 0 to change, 1 to destroy.
─────────────────────────────────────────────────────────────────────────────
Saved the plan to: terraform_integ.tfplan
To perform exactly these actions, run the following command to apply:
    terraform apply "terraform_integ.tfplan"
```

### Additional Context

Using terraform in a gitlab-ci without any environment variables.

I tried many others syntax to ignore this block or just parameters inside but whatever I tried terraform always want to recreate the object.

**Comment by apparentlymart** [comment] 2021-09-01 16:19
Hi @beparmentier,

From reviewing your plan output, it seems like the provider has proposed to replace this object because you made a change to the configuration inside the `rolling_upgrade_policy` block. `ignore_changes` means to ignore mismatches between the state and the configuration when detecting what's changed, but you haven't included `rolling_upgrade_policy` in the `ignore_changes` set and so any actions the provider proposes based on changes in _there_ will still apply.

Replacing an object means to create an entirely new object based on the current configuration, destroying the previous one, and so there's no way to preserve the existing configuration of the old object in that case, regardless of what you might write in `ignore_changes`.

Given this, Terraform seems to be working as intended here. If you don't wish to replace this object then you'll need to ignore the specific attributes or containing blocks which cause the provider to propose replacing the object, which should then in turn allow for retaining the current settings for other properties of the existing object.

If you believe that it should be possible to change `rolling_upgrade_policy` _without_ forcing the replacement of this object, that'd be a provider behavior change that you'd need to discuss in [the Azure provider repository](https://github.com/hashicorp/terraform-provider-azurerm), though typically provider developers only introduce these requirements in the face of restrictions in the remote API and so it's likely that there's no other way to implement changes to `rolling_upgrade_policy`.

Since Terraform is working as designed here, I'm going to close this issue. Thanks!

**Closed by apparentlymart** 2021-09-01 16:19 UTC
Labels: bug, new

**Comment by beparmentier** [comment] 2021-09-01 16:47
Hi @apparentlymart 

I never add or remove `rolling_upgrade_policy` block in my terraform code.

Seems there is something weird with the default `rolling_upgrade_policy` values or this block is added outside of the resource definition.

I just try to add an `ignore_changes = [rolling_upgrade_policy]` and it works as expected.

I will discuss about that with azure provider community.

Thanks for your answer.
