### ISSUE TITLE
Destroying modules with for_each meta-argument fails on empty 

### ISSUE THREAD

**Issue by pgelinas** [hashicorp/terraform#33948] opened 2023-09-27 18:21 UTC
### Terraform Version

```shell
Terraform v1.4.5 on linux_amd64
```

### Terraform Configuration Files

```terraform
locals {
  map = { foo: "bar" }
}

module "test" {
  for_each = local.map
  source   = "./module"

  input_var = each.key
}

locals {
  local_var = module.test["foo"].output_var
}

output "bar" {
  value = local.local_var
}
```

module:
```terraform
output "output_var" {
  value = var.input_var
}

variable "input_var" {}
```

### Debug Output

```
$ terraform destroy

│ Error: Invalid index
│ 
│   on main.tf line 17, in locals:
│   17:   local_var = module.test["foo"].output_var
│     ├────────────────
│     │ module.test is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
```

### Expected Behavior

The destroy should complete without issue since resources are already destroyed

### Actual Behavior

See error about invalid index

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. `terraform destroy`

### Additional Context

I've found a workaround where I can use the `lookup` function with a default value that respect the module output contract, but the values doesn't matter, just the keys. In the provided configuration example:

```terraform
locals {
  local_var = lookup(module.test, "foo", {output_var: "don't care"}).output_var
}
```

Would work as expected for both plan and destroy. The default value is just there to make terraform happy.

### References

Seems similar to #33682 as the sub module has no for_each key, probably because its outputs are empty (already destroyed).

**Comment by jbardin** [comment] 2023-09-27 19:02
Duplicate of #33218

**Closed by jbardin** 2023-09-27 19:02 UTC
Labels: bug, new

**Comment by pgelinas** [comment] 2023-09-27 22:30
Hmmmm, it's still failing on Terraform 1.4.7 but works on 1.5.7. I'll update to latest then, thanks.
