### ISSUE TITLE
Incorrectly complaining about loadbalancer which already exists

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10837] opened 2016-12-19 16:01 UTC
This is not supposed to happen; it happened when I modified the count variable from 2 to 3, which in turn has an effect on the number of NAT gateways and also on the loadbalancer "foo". The load balancer is already managed by this terraform configuration, it's just that I want to change some aspect of it, not create a whole new one. 

The wait time on the NAT gateways is probably also too short, since I can imagine that AWS is quite slow in bringing those up. 

Terraform version: Terraform v0.8.0-dev (658f048ca4100b30fa6dd928d7f107adea4a4d80)

```
3 error(s) occurred:

* aws_alb.lb: Error creating Application Load Balancer: DuplicateLoadBalancerName: A load balancer with the same name 'foo' exists, but with different settings
        status code: 400, request id: 02f28b37-c603-11e6-b5d9-89305cba6189
* aws_nat_gateway.nat.0: Error waiting for NAT Gateway (nat-0223343294d5eea8d) to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)
* aws_nat_gateway.nat.1: Error waiting for NAT Gateway (nat-0a5d050df6b7ac552) to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by mitchellh** [comment] 2016-12-19 18:00
Can you please show us a reproducible configuration? Or a debug log (may contain sensitive info please scrub)? It is very difficult to determine bugs from output alone which is not meant to be debuggable (from an implementation standpoint) output. Thanks!

**Comment by fdiazydiaz** [comment] 2016-12-20 14:43
I believe this issue is a duplicate of #9045

**Comment by catsby** [comment] 2017-02-01 16:43
Closing as duplicate of #9045

**Closed by catsby** 2017-02-01 16:43 UTC
Labels: bug, provider/aws, waiting-response
