### ISSUE TITLE
'terraform state rm' fails with indexed addresses

### ISSUE THREAD

**Issue by schuettecarsten** [hashicorp/terraform#24990] opened 2020-05-19 06:33 UTC
`terraform state rm` fails when trying to remove a resource with indexed address.

### Terraform Version
```
Terraform v0.12.25
+ provider.azurerm v2.9.0
```

### Actual Behavior

```
terraform state rm module.p1-abc.module.loadbalancer.azurerm_lb_backend_address_pool.backend_pool["vm"]

Error: Index value required

  on  line 1:
  (source code not available)

Index brackets must contain either a literal number or a literal string.
```

**Comment by danieldreier** [comment] 2020-05-19 21:46
I tried to reproduce this and was unable to. I've [scripted a reproduction](https://github.com/danieldreier/terraform-issue-reproductions/tree/master/24990):

```
bash-3.2$ ./run.sh
Initializing modules...
- mymodule in modules/mymodule

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.null: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
null_resource.example["fizz"]: Creating...
null_resource.example["foo"]: Creating...
module.mymodule.null_resource.example-in-module["foo"]: Creating...
module.mymodule.null_resource.example-in-module["fizz"]: Creating...
null_resource.example["fizz"]: Provisioning with 'local-exec'...
null_resource.example["foo"]: Provisioning with 'local-exec'...
module.mymodule.null_resource.example-in-module["fizz"]: Provisioning with 'local-exec'...
module.mymodule.null_resource.example-in-module["fizz"] (local-exec): Executing: ["/bin/sh" "-c" "echo hello fizz"]
null_resource.example["foo"] (local-exec): Executing: ["/bin/sh" "-c" "echo hello foo"]
null_resource.example["fizz"] (local-exec): Executing: ["/bin/sh" "-c" "echo hello fizz"]
module.mymodule.null_resource.example-in-module["foo"]: Provisioning with 'local-exec'...
module.mymodule.null_resource.example-in-module["foo"] (local-exec): Executing: ["/bin/sh" "-c" "echo hello foo"]
module.mymodule.null_resource.example-in-module["foo"] (local-exec): hello foo
null_resource.example["foo"] (local-exec): hello foo
module.mymodule.null_resource.example-in-module["fizz"] (local-exec): hello fizz
null_resource.example["foo"]: Creation complete after 0s [id=4369951880004616872]
module.mymodule.null_resource.example-in-module["fizz"]: Creation complete after 0s [id=3090395275537413617]
module.mymodule.null_resource.example-in-module["foo"]: Creation complete after 0s [id=5340551546629208291]
null_resource.example["fizz"] (local-exec): hello fizz
null_resource.example["fizz"]: Creation complete after 0s [id=118018204451378773]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
Removed null_resource.example["foo"]
Successfully removed 1 resource instance(s).
Removed module.mymodule.null_resource.example-in-module["fizz"]
Successfully removed 1 resource instance(s).
```

It looks to me like this is working as expected. If you're seeing a bug, can you please make a PR against that reproduction case to show me what you're doing that doesn't work?

**Comment by apparentlymart** [comment] 2020-06-26 00:58
Hi @schuettecarsten,

We didn't hear back from you after @danieldreier's recent comment.

Looking at what you originally shared, one thing that I see is that you wrote the resource address directly on the command line, without any escaping of the quotes. Therefore it's likely that your shell has interpreted the quotes, rather than Terraform, and so the result is (from Terraform's perspective) invalid.

If you are using a Unix-based system, like Linux or Mac OS X, you can put the address in single quotes `'` to ensure that the shell will not parse the address before Terraform does:

```
terraform state rm 'module.p1-abc.module.loadbalancer.azurerm_lb_backend_address_pool.backend_pool["vm"]'
```

If you're using the Windows Command Prompt, the convention on Windows is to escape the quotes using backslashes, like this:

```
terraform state rm module.p1-abc.module.loadbalancer.azurerm_lb_backend_address_pool.backend_pool[\"vm\"]
```

Because we didn't hear back from you, I'm going to close this. I hope the above is helpful! If you have more questions, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) and we can discuss more there. Thanks!

**Closed by apparentlymart** 2020-06-26 00:58 UTC
Labels: waiting-response
