### ISSUE TITLE
"diffs didn't match during apply" after instance taint

### ISSUE THREAD

**Issue by cshramko-amadeus** [hashicorp/terraform#8997] opened 2016-09-22 18:01 UTC
### Terraform Version

0.6.16
### Affected Resource(s)

openstack_compute_instance_v2.artifactory-storage
openstack_compute_instance_v2.artifactory-database
openstack_compute_instance_v2.artifactory
### Terraform Configuration Files

https://gist.github.com/cshramko-amadeus/41fee1a920db17533de8497600012b6b
### Debug Output

https://gist.github.com/cshramko-amadeus/41fee1a920db17533de8497600012b6b
### Expected Behavior

delete and recreate four resources
### Actual Behavior

error as displayed
### Steps to Reproduce

see terminal session in 
https://gist.github.com/cshramko-amadeus/41fee1a920db17533de8497600012b6b
### Important Factoids

running in VIO

**Comment by mildwonkey** [comment] 2016-10-12 18:07
I just ran into the same issue with Terraform Version: 0.7.4.
I created 3 instances (using count), tainted the second instance, and ran apply. The instances was deleted, but then the error occurred.
Running terraform apply a second time created the instance as expected.

I'm happy to supply my debug logs if needed.

**Comment by mitchellh** [comment] 2016-11-17 00:47
Hello! This should be fixed in later versions of Terraform. 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 00:47 UTC
Labels: bug, core
