### ISSUE TITLE
Module output variables cannot be used to create a list input

### ISSUE THREAD

**Issue by TheYorkshireDev** [hashicorp/terraform#16916] opened 2017-12-14 16:35 UTC
Hi all,

I cannot seem to pass through a list of strings when the strings are outputs of another module.

### Terraform Version

```
Terraform v0.11.1
```

### Terraform Configuration Files

Module Firewalls `vars.tf`:
```hcl
variable "tags" {
  description = "List of tags to apply to the firewall"
  type        = "list"
}
```
Module Firewalls `main.tf`:
```hcl
resource "digitalocean_firewall" "wall1" {
  name = "FIRE1"

  tags = "${var.tags}"

  ...
 }
```

`root.tf`
```hcl
module "tags" {
  source = "./tags"
}

module "firewalls" {
  source = "./firewalls"
  tags     = ["${module.tags.firewall_tags}"]
}
```
* Module `tags` has the output variable of `firewall_tags` which is type string 
* Module `firewalls` has the input variable `tags` which is of type List

### Expected Behavior

Expected the `["${module.tags.firewall_tags}"]` to be resolved as a string list

### Actual Behavior
```
Error: module.firewalls.digitalocean_firewall.wall1: tags: should be a list
```

### Steps to Reproduce
`terraform plan`

### Important Factoids
I have found two instances where this behaviour does not appear and all is fine:

Hard-Coded List:`root.tf`
```hcl
module "tags" {
  source = "./tags"
}

module "firewalls" {
  source = "./firewalls"
  tags     = ["HARDCODED"]
}
```

Using locals:`root.tf`
```hcl
module "tags" {
  source = "./tags"
}
locals {
   temp = "LOCAL"
}
module "firewalls" {
  source = "./firewalls"
  tags     = ["${local.temp}"]
}
```

**Comment by jbardin** [comment] 2017-12-14 21:59
Hi @TheYorkshireDev,

Can you show the configuration that's generating the `module.tags.firewall_tags` list? A simple hard-coded output works as expected, but there are still some edge cases where type information is list between modules.

I'm not sure if it effects the results you see, but you don't want the square brackets around `"${module.tags.firewall_tags}"` if that is already a list.

**Comment by TheYorkshireDev** [comment] 2017-12-14 22:09
@jbardin I checked the state file and it was just as string, but here is the config.

Module.Tags `main.tf`
```
resource "digitalocean_tag" "firewall" {
  name = "FIREWALL"
}
```

Module.Tags `output.tf`
```
output "firewall_tags" {
  value = "${digitalocean_tag.firewall.name}"
}
```

**Comment by jbardin** [comment] 2017-12-14 22:21
Ah, got it. Yes, it looks like when the value is computed, the fact the square brackets turned it into a list was lost.

**Comment by gvilarino** [comment] 2018-05-31 15:36
Hi, same problem here. Any ETA on this? It's really a tough issue to identify, specially for newcomers like me 😅

**Comment by jspenc72** [comment] 2018-09-18 20:04
Is there a workaround for this?

**Comment by soulrebel** [comment] 2018-10-03 16:01
@jspenc72 csv: join and split everywhere.

**Comment by jspenc72** [comment] 2018-10-03 22:36
@soulrebel can you post an example?

**Comment by jaceq** [comment] 2018-10-04 06:59
I have same issue with list of maps (@soulrebel and join won't work in my case)...
I try to pass to module something like that:
``` [
#                               {
#                                 name = "store.host"
#                                value = "${google_redis_instance.search.host}"
#                               },
                               {
                                 name = "store.port"
                                 value = "${var.store_port}"
                               },
                               {
                                 name = "HOST2"
                                 value = "http://${var.host2}/de"
                               },
                               {
                                 name = "HOST1"
                                 value = "http://${var.host1_name}:8983/"
                               }
                             ]
```

In module I have:
```
env = "${var.env_var}"
```

Basically when I hashout (as it is hashed out on example above) the map which contains output from another module and pass data containing only strings or variables then it works, other wise I get:
```
spec.0.template.0.spec.0.container.0.env: should be a list
```

**Comment by rpatrick00** [comment] 2018-10-17 14:01
This issue really makes the value of modules very limited.  For example, if I create an AWS VPC with subnets in one module and then need to pass the subnet IDs into the module to create my EKS cluster, you can only do it if you hardcode the number of subnets and pass each in a separate output variable.  

If seems that passing an output as a list that is used as input to another module works fine if the list is all hard-coded strings.  As soon as you try to use interpolation syntax--even for the individual list items--it no longer works.  For example, assume you have some code that looks similar to this:

In module A:
output "foo" {
    ...
}

In module B:
variable "bar" {
    type = "list"
}

resource "aws_eks_cluster" {
    ....
    vpc_config {
        subnet_ids = "${var.bar}"
    }
}

In main code:

module "A" {
    ...
}

module "B" {
    ...
    bar = "${module.A.foo}"
}

If the output foo is defined like this (which clearly doesn't help), the code above works as expected:

output "foo" {
    value = [ "subnet-12345678", "subnet-23456789", "subnet-34567890" ]
} 

If if the output foo is defined using interpolation syntax like either of the two examples below, you get the "should be a list" error.

output "foo" {
    value = [ "${aws_subnet.subnet-1.id}", "${aws_subnet.subnet-2.id}", "${aws_subnet.subnet-3.id}" ]
}

or:

output "foo" {
    value = "${list("${aws_subnet.subnet-1.id}", "${aws_subnet.subnet-2.id}", "${aws_subnet.subnet-3.id}")}"
}

I ended up having to abandon the use of well-defined modules for any situation where I need to pass lists of things as outputs that need to be used as inputs to other modules.

I tried the join/split workaround but was unable to get that to work properly either.

**Comment by apparentlymart** [comment] 2018-10-30 01:10
Hi all! Sorry for the long silence here.

This issue has the same root cause as #12263, which has now been fixed in master ready for inclusion in the forthcoming v0.12.0 release. Thanks for reporting it, and thanks for your patience while we figured out what was going on.

**Closed by apparentlymart** 2018-10-30 01:10 UTC
Labels: bug, config
