### ISSUE TITLE
"terraform remote push" conflicts with "terraform push"?

### ISSUE THREAD

**Issue by manojtr** [hashicorp/terraform#6345] opened 2016-04-26 04:21 UTC
Hi there,

When I run `terraform remote push` it conflicts with `terraform push` for some reason and it shows the Usage for `terraform push`. But `terraform remote config` works with the same arguments. See below. 
This is in the case of AWS. I ran the bellow command on Mac 10.11.3 (El Caption) and terraform version is v0.6.14

Is this something to do with my settings or may be used in an incorrect ways? 

```
manoj$ terraform remote config -backend=s3 -backend-config="bucket=test-bucket” -backend-config="key=test_network"
Remote configuration updated
Remote state configured and pulled.

manoj$ terraform remote push -backend=s3 -backend=s3 -backend-config="bucket=test-bucket” -backend-config="key=test_network"
Usage: terraform push [options]

  Uploads the latest state to the remote server.

Options:

  -no-color              If specified, output won't contain any color.

  -force                 Forces the upload of the local state, ignoring any
                         conflicts. This should be used carefully, as force pushing
                         can cause remote state information to be lost.
manoj$
```

best regards
Manoj

**Comment by iroller** [comment] 2016-06-21 21:16
Same issue here. Is there currently a way to run `terraform push -force` to override remote state with local state? Can't get it to work.

**Comment by eherot** [comment] 2017-03-02 16:22
This seems to be a duplicate of #5663

**Comment by apparentlymart** [comment] 2017-04-04 23:53
Hi @manojtr, and everyone else who commented here! Sorry for this strange behavior, and sorry we let this issue languish so long.

In Terraform 0.9 the remote state system was completely overhauled and in particular there is no longer this concept of local state cache, and so no more `terraform remote push` and `terraform remote pull` commands. Instead, Terraform simply reads the state from the remote backend each time it's needed.

I believe the original problem was that the usage of `terraform remote push` was incorrect: it didn't take the same arguments as `terraform remote config`, because in the old architecture the remote configuration was saved in a local file for use by subsequent `terraform remote` subcommands. `terraform remote push` (with no arguments) would've been the correct invocation here.

However, these commands no longer exist so this issue is in some ways a moot point and thus I'm going to close it. If anyone encounters any similar-looking issues in 0.9, I'd encourage opening a fresh new issue since that way we can triage and address it separately. Thanks again!

**Closed by apparentlymart** 2017-04-04 23:53 UTC
Labels: bug, core
