### ISSUE TITLE
Warning/Deprecation Notice at Module Layer

### ISSUE THREAD

**Issue by frugecn** [hashicorp/terraform#34422] opened 2023-12-15 19:07 UTC
### Terraform Version

```shell
1+
```

### Use Cases

Organizations that create modules for teams use for terraform code-sets need some way to indicate deprecation of input variables/output fields of module/modules themselves for their end-users on Init, TF Validate, Plan, Apply similar to existing functionality in the SDKv2 for plug-in development.

[Plugin Development - SDKv2 Deprecations, Removals, and Renames Best Practices | Terraform | HashiCorp Developer](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations)]

### Attempted Solutions

Looking at creating an out of process executable to scan plans to run after execution of one of the plans.  If the pre and post conditions in lifecycle have pass or fail with the warning on only the fail condition.  Adding warning to the documentation.

### Proposal

a couple of ideas:
lifecycle pre/post condition with a warning option
Warning process on variables similar to the exception process
a message sent back from the registry when caching the code from the repo similar to provider deprecation warnings or TF new version available warnings

**Comment by jbardin** [comment] 2023-12-15 19:41
Duplicate of #5949

**Comment by jbardin** [comment] 2023-12-15 19:42
Also, variable deprecation #32594, and output deprecation #18381

**Closed by jbardin** 2023-12-15 19:41 UTC
Labels: enhancement, new
