### ISSUE TITLE
UTF-8 strings are being mangled

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform#36207] opened 2024-12-12 18:31 UTC
### Terraform Version

```shell
Terraform v1.10.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/local v2.5.2
```

### Terraform Configuration Files

```terraform
resource "local_file" "this" {
  content = "並龎"
  filename = "${path.module}/output.txt"
}
```

### Debug Output

https://gist.github.com/lijok/468052dd85e32282a79bbdae066a3e79

### Expected Behavior

The content in the `output.txt` file should be:
`並龎`

hexdump:
`a9ef efb0 99ab`

### Actual Behavior

The content in the `output.txt` file is `並龎`

hexdump:
`b8e4 e9a6 8ebe`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

This is highly problematic as we're trying to upload minified js and the regex patterns inside of it are getting mangled to something that the destination doesn't recognize as utf-8

**Comment by jbardin** [comment] 2024-12-12 19:45
Hi @lijok,

Terraform treats all strings as utf8 input, which is subjected to unicode normalization form C. The 2 CJK Compatibility Ideographs in your string are placeholders for North Korean KPS 10721-2000 characters (they don't even render in my browser), and normalize as the unified ideographs you see in your output ([U+4E26](https://www.compart.com/en/unicode/U+4E26), and [U+9F8E](https://www.compart.com/en/unicode/U+9F8E))

If the byte-exact representation of the string is required, then utf8 strings are not an appropriate mechanism. This is why common resources like `aws_s3_object` have attributes like [`context_base64`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object#content_base64-1) so that raw binary data can be transferred without any assumption about the meaning of the data.

**Comment by jbardin** [comment] 2024-12-12 19:52
If you are actually using `local_file` in your configuration, that also has an equivalent [`content_base64`](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file#content_base64-1) attribute. The following configuration will create the file with the original bytes:

```
resource "local_file" "this" {
  content_base64 = "76mw76uZ"
  filename = "${path.module}/output.xt"
}
```

**Comment by jbardin** [comment] 2024-12-12 21:00
I assume the `RegExp` that is generated there is technically OK for their use case, it is a valid utf8 string.

The discrepancy here is that Terraform tries to deal with strings as a series of glyphs rather than the raw string data. It does that by applying standard normalization to ensure that a string like `"Ç"` (which is U+00C7) is equal to `"Ç"` (which is U+0043 U+0327) which are rendered identically but contain different bytes. Terraform's primary job is handling text-based configuration data, so it's a fair assumption that [`"Ç" == "Ç"` should not be false](https://go.dev/play/p/VBhqC6Nn-LH).

While it's usually a case of raw binary data being corrupted by the utf8 encoding/decoding process, I think the same advice applies to this here as it does to binary data. If the exact byte sequence of the unencoded string matters, the provider should accept it in some binary encoded form like base64.

**Comment by jbardin** [comment] 2024-12-13 14:00
Since Terraform is working as designed here I'm going to close the issue, but if you have more questions we could help with feel free to reply here.

**Closed by jbardin** 2024-12-13 14:00 UTC
Labels: bug, new, working as designed
