### ISSUE TITLE
Tainting ELB fails

### ISSUE THREAD

**Issue by jangrewe** [hashicorp/terraform#10192] opened 2016-11-17 14:09 UTC
I wanted to try if tainting the ELB helps with getting rid of #9289, but this made it only worse...

### Terraform Version
0.7.11

### Affected Resource(s)
- aws_elb

### Terraform Configuration Files
```hcl
resource "aws_elb" "elb" {
  name = "${var.name}-${var.cluster_name}"
  cross_zone_load_balancing = true
  connection_draining = true
  subnets = [
      "${var.elb_subnet_ids}",
  ]
  security_groups = [
      "${aws_security_group.elb.id}",
  ]

  listener {
    instance_port = "${var.port_host}"
    instance_protocol = "http"
    lb_port = "${var.port_elb}"
    lb_protocol = "http"
  }

  listener {
    instance_port = "${var.port_host}"
    instance_protocol = "http"
    lb_port = 443
    lb_protocol = "https"
    ssl_certificate_id = "${var.https_cert_arn}"
  }

  health_check {
    healthy_threshold = 2
    unhealthy_threshold = 2
    timeout = 3
    target = "HTTP:${var.port_host}/monitor/health"
    interval = 5
  }

  access_logs {
    bucket = "ptv-logs-${var.aws_env}"
    bucket_prefix = "${var.name}-${var.cluster_name}"
    interval = 60
  }

  tags {
      Name = "${var.name}_${var.cluster_name}"
      Environment = "${var.aws_env}"
      Project = "ptv"
      BusinessUnit = "beta"
      Tier = "infra"
      Service = "ecs-task"
  }
}
```

### Error Output
```
* aws_elb.elb: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.11
    Resource ID: aws_elb.elb
    Mismatch reason: diff: Destroy; old: false, new: true
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"source_security_group_id":*terraform.ResourceAttrDiff{Old:"sg-032b4e64", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Project":*terraform.ResourceAttrDiff{Old:"ptv", New:"ptv", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.#":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.375021976":*terraform.ResourceAttrDiff{Old:"subnet-b7b6ecc0", New:"subnet-b7b6ecc0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "source_security_group":*terraform.ResourceAttrDiff{Old:"803064921768/elb_api_blue", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.lb_port":*terraform.ResourceAttrDiff{Old:"80", New:"80", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.ssl_certificate_id":*terraform.ResourceAttrDiff{Old:"arn:aws:acm:eu-west-1:803064921768:certificate/6bebc6e3-ce33-4ca1-bb91-0731a6f7d0e9", New:"arn:aws:acm:eu-west-1:803064921768:certificate/6bebc6e3-ce33-4ca1-bb91-0731a6f7d0e9", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"api_blue", New:"api_blue", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"6", New:"6", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.timeout":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "internal":*terraform.ResourceAttrDiff{Old:"false", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.lb_protocol":*terraform.ResourceAttrDiff{Old:"https", New:"https", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "connection_draining":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.#":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.1609415996":*terraform.ResourceAttrDiff{Old:"subnet-12d10176", New:"subnet-12d10176", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.#":*terraform.ResourceAttrDiff{Old:"3", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"api-blue", New:"api-blue", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.healthy_threshold":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.BusinessUnit":*terraform.ResourceAttrDiff{Old:"beta", New:"beta", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Service":*terraform.ResourceAttrDiff{Old:"ecs-task", New:"ecs-task", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.bucket_prefix":*terraform.ResourceAttrDiff{Old:"api-blue", New:"api-blue", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.instance_port":*terraform.ResourceAttrDiff{Old:"81", New:"81", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.unhealthy_threshold":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.lb_port":*terraform.ResourceAttrDiff{Old:"443", New:"443", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.interval":*terraform.ResourceAttrDiff{Old:"60", New:"60", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.instance_protocol":*terraform.ResourceAttrDiff{Old:"http", New:"http", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.instance_port":*terraform.ResourceAttrDiff{Old:"81", New:"81", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.target":*terraform.ResourceAttrDiff{Old:"HTTP:81/monitor/health", New:"HTTP:81/monitor/health", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.enabled":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Tier":*terraform.ResourceAttrDiff{Old:"infra", New:"infra", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "connection_draining_timeout":*terraform.ResourceAttrDiff{Old:"300", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "security_groups.1664717351":*terraform.ResourceAttrDiff{Old:"sg-032b4e64", New:"sg-032b4e64", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.3844765669":*terraform.ResourceAttrDiff{Old:"subnet-151b0a4c", New:"subnet-151b0a4c", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "zone_id":*terraform.ResourceAttrDiff{Old:"Z32O12XQLNTSW2", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instances.#":*terraform.ResourceAttrDiff{Old:"2", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "security_groups.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.bucket":*terraform.ResourceAttrDiff{Old:"ptv-logs-int", New:"ptv-logs-int", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "cross_zone_load_balancing":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.instance_protocol":*terraform.ResourceAttrDiff{Old:"http", New:"http", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.ResourceAttrDiff{Old:"int", New:"int", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.interval":*terraform.ResourceAttrDiff{Old:"5", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.ssl_certificate_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "idle_timeout":*terraform.ResourceAttrDiff{Old:"60", New:"60", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "dns_name":*terraform.ResourceAttrDiff{Old:"api-blue-1171887458.eu-west-1.elb.amazonaws.com", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.lb_protocol":*terraform.ResourceAttrDiff{Old:"http", New:"http", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:true}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"health_check.0.unhealthy_threshold":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.interval":*terraform.ResourceAttrDiff{Old:"60", New:"60", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.instance_protocol":*terraform.ResourceAttrDiff{Old:"http", New:"http", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.lb_port":*terraform.ResourceAttrDiff{Old:"80", New:"80", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.ResourceAttrDiff{Old:"int", New:"int", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Tier":*terraform.ResourceAttrDiff{Old:"infra", New:"infra", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.ssl_certificate_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"api_blue", New:"api_blue", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "source_security_group_id":*terraform.ResourceAttrDiff{Old:"sg-032b4e64", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.lb_port":*terraform.ResourceAttrDiff{Old:"443", New:"443", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.bucket_prefix":*terraform.ResourceAttrDiff{Old:"api-blue", New:"api-blue", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "cross_zone_load_balancing":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.#":*terraform.ResourceAttrDiff{Old:"3", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "internal":*terraform.ResourceAttrDiff{Old:"false", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.ssl_certificate_id":*terraform.ResourceAttrDiff{Old:"arn:aws:acm:eu-west-1:803064921768:certificate/6bebc6e3-ce33-4ca1-bb91-0731a6f7d0e9", New:"arn:aws:acm:eu-west-1:803064921768:certificate/6bebc6e3-ce33-4ca1-bb91-0731a6f7d0e9", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.#":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.lb_protocol":*terraform.ResourceAttrDiff{Old:"http", New:"http", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instances.#":*terraform.ResourceAttrDiff{Old:"2", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "zone_id":*terraform.ResourceAttrDiff{Old:"Z32O12XQLNTSW2", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.timeout":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "connection_draining_timeout":*terraform.ResourceAttrDiff{Old:"300", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"6", New:"6", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Project":*terraform.ResourceAttrDiff{Old:"ptv", New:"ptv", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.enabled":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "connection_draining":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.407933315.instance_port":*terraform.ResourceAttrDiff{Old:"81", New:"81", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "idle_timeout":*terraform.ResourceAttrDiff{Old:"60", New:"60", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Service":*terraform.ResourceAttrDiff{Old:"ecs-task", New:"ecs-task", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"api-blue", New:"api-blue", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "security_groups.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.interval":*terraform.ResourceAttrDiff{Old:"5", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "security_groups.1664717351":*terraform.ResourceAttrDiff{Old:"sg-032b4e64", New:"sg-032b4e64", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.instance_protocol":*terraform.ResourceAttrDiff{Old:"http", New:"http", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.healthy_threshold":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check.0.target":*terraform.ResourceAttrDiff{Old:"HTTP:81/monitor/health", New:"HTTP:81/monitor/health", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.375021976":*terraform.ResourceAttrDiff{Old:"subnet-b7b6ecc0", New:"subnet-b7b6ecc0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.BusinessUnit":*terraform.ResourceAttrDiff{Old:"beta", New:"beta", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "source_security_group":*terraform.ResourceAttrDiff{Old:"803064921768/elb_api_blue", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.lb_protocol":*terraform.ResourceAttrDiff{Old:"https", New:"https", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.#":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.3844765669":*terraform.ResourceAttrDiff{Old:"subnet-151b0a4c", New:"subnet-151b0a4c", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "dns_name":*terraform.ResourceAttrDiff{Old:"api-blue-1171887458.eu-west-1.elb.amazonaws.com", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnets.1609415996":*terraform.ResourceAttrDiff{Old:"subnet-12d10176", New:"subnet-12d10176", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "access_logs.0.bucket":*terraform.ResourceAttrDiff{Old:"ptv-logs-int", New:"ptv-logs-int", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "listener.2481300923.instance_port":*terraform.ResourceAttrDiff{Old:"81", New:"81", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:true, DestroyTainted:true}
```

### Expected Behavior
The ELB should have been destroyed and recreated

### Actual Behavior
The error above.

### Steps to Reproduce
1. `terraform taint aws_elb.elb`
2. `terraform apply`

**Comment by mitchellh** [comment] 2016-11-19 04:50
Hello! I tried your config and steps exactly and wasn't able to reproduce this error. Can you please point me in a direction to try to reproduce this?

**Comment by jrnt30** [comment] 2016-11-21 17:38
I am having the same issue.  One particular piece to note is that the ELB definition is contained in a module, not directly in the config.  I'll see if I can reproduce this regularly via taint (our error occurred when we changed the ELB's name attribute and it was forcing a re-create).

**Comment by jrnt30** [comment] 2016-11-21 21:27
@jangrewe Do you have any resources that use the outputs of your ELB creation that have the 
```
  lifecycle {
    create_before_destroy = true
  }
```

I believe this may be part of my issue.  We have the `lifecycle` block on the `aws_autoscaling_attachment` resource.  This references attributes from the ELB that was created in the module *without* the `lifecycle` block being set on the ELB and behaves exactly as yours does. 

If I set the `lifecycle` block on the underlying ELB (and continue to keep it on the attachment), I do get past this error `Destroy` related error you referenced. 

However I receive a notification about: 

```Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!

You can report an issue at: https://github.com/hashicorp/terraform/issues

1 error(s) occurred:

* apply operation: Error building new graph: 1 error(s) occurred:

* Cycle: module.web_elb.output.elb_id, aws_autoscaling_attachment.elb_attachment, aws_autoscaling_attachment.elb_attachment (destroy), module.web_elb.aws_elb.web_elb (destroy)

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.```

**Comment by jangrewe** [comment] 2016-11-22 13:52
Thanks @jrnt30, i did have `create_before_destroy` set for the ASG and its Launch Configuration. Setting it for the ELB didn't fix it, as TF complained about a duplicate ELB name then, but removing it (or at least commenting it out) in the two ASG resources allowed me to pass the apply.

My Route53 records still get modified with every run, so tainting them and the ELBs didn't fix anything, but at least i got rid of the error now.

**Comment by mitchellh** [comment] 2016-11-29 18:21
Thanks all for the input, but unfortunately I still can't get a reproduction here. I do believe this error is real since it has been reported multiple times, but a clean reproduction so we can fix it still eludes us. Until we can get that, I unfortunately won't be able to do much here...

I'm going to close this for now, but if someone gets a repro for this please just open a new issue and we'll get going ASAP!

**Closed by mitchellh** 2016-11-29 18:21 UTC
Labels: bug, core, waiting-response
