### ISSUE TITLE
Perpetual diff on 1.4

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform#32888] opened 2023-03-20 12:46 UTC
### Terraform Version

```shell
1.4.2
```

### Terraform Configuration Files

```terraform
resource "hcloud_server" "test" {
  name        = "test"
  image       = "debian-11"
  server_type = "cx21"
  location    = "fsn1"
  keep_disk   = true
  user_data = join("", [
    "#cloud-config",
    "\n",
    yamlencode({
      ca_certs = {
        trusted = [
          tls_locally_signed_cert.environment_ca.cert_pem
        ]
      }
      runcmd = [
        ["/bin/bash", "-c", "echo \"export AWS_DEFAULT_REGION=${data.aws_region.current.name}\" > /etc/aws.sh"]
      ]
    })
  ])
  ssh_keys = [
    hcloud_ssh_key.test.name
  ]
  firewall_ids = [
    hcloud_firewall.private.id
  ]
  labels = local.common_tags

  network {
    network_id = module.hcloud_network.vpc_id
  }

}

resource "aws_route53_record" "test" {
  zone_id         = data.aws_route53_zone.default.zone_id
  name            = "test"
  type            = "A"
  records         = [for network in hcloud_server.test.network : network["ip"]]
  ttl             = 300
  allow_overwrite = true
}
```

### Debug Output

  # hcloud_server.test will be updated in-place
  ~ resource "hcloud_server" "test" {
        id                         = "XXXXX"
        name                       = "test"
        # (18 unchanged attributes hidden)

      - network {
          - alias_ips   = [] -> null
          - ip          = "10.103.0.2" -> null
          - mac_address = "86:00:00:3d:af:8e" -> null
          - network_id  = YYYY -> null
        }
      + network {
          + alias_ips   = (known after apply)
          + ip          = (known after apply)
          + mac_address = (known after apply)
          + network_id  = YYYY
        }
    }

### Expected Behavior

No diff shown

### Actual Behavior

Perpetual diff

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

No reproducible on terraform 1.3

**Comment by jbardin** [comment] 2023-03-20 13:05
Hi @vladimirtiukhtin,

Thanks for filing the issue. Can you verify that you have not changes the provider version at all during the upgrade?
Could you also check for any warnings about the provider's behavior by running plan with `TF_LOG_CORE=warn`?

Thanks!

**Comment by vladimirtiukhtin** [comment] 2023-03-20 13:09
Hi @jbardin 

Thanks for the prompt response. No, I have not. For a further proof I've just downgraded terraform back to 1.3.9 and run on exactly the same code base. Terraform 1.3.9 does not display the diff above

**Comment by jbardin** [comment] 2023-03-20 18:28
I see that the value here is referenced from a module output, so I am going to assume for now that this is a duplicate of #32880. If that turns out to be incorrect, we can collect some more debugging information and reevaluate this issue.

Thanks!

**Closed by jbardin** 2023-03-20 18:28 UTC
Labels: bug, waiting-response, new, waiting for reproduction
