### ISSUE TITLE
associate_public_ip_address diff didn't match during apply

### ISSUE THREAD

**Issue by pporada-gl** [hashicorp/terraform#5852] opened 2016-03-25 14:46 UTC
Host: Ubuntu 15.10

```
Linux laptappy 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

TF Version

```
Terraform v0.6.14
```

Plan

```
~ module.nodeapp.aws_instance.alexsnode
    associate_public_ip_address:               "true" => "1"
    root_block_device.0.delete_on_termination: "true" => "1"
    source_dest_check:                         "true" => "1"

+ module.nodeapp.aws_route53_record.app1-priv
    fqdn:      "" => "<computed>"
    name:      "" => "schema.prod.company.int"
    records.#: "" => "<computed>"
    ttl:       "" => "60"
    type:      "" => "A"
    weight:    "" => "-1"
    zone_id:   "" => "Z1DSH1J88YSUGM"

+ module.nodeapp.aws_route53_record.app1-pub
    fqdn:      "" => "<computed>"
    name:      "" => "schema.prod.company.com"
    records.#: "" => "<computed>"
    ttl:       "" => "60"
    type:      "" => "A"
    weight:    "" => "-1"
    zone_id:   "" => "Z2SO3DJTXPGLLI"

+ module.nodeapp.aws_route53_record.app2-priv
    fqdn:      "" => "<computed>"
    name:      "" => "mock.prod.company.int"
    records.#: "" => "<computed>"
    ttl:       "" => "60"
    type:      "" => "A"
    weight:    "" => "-1"
    zone_id:   "" => "Z1DSH1J88YSUGM"

+ module.nodeapp.aws_route53_record.app2-pub
    fqdn:      "" => "<computed>"
    name:      "" => "mock.prod.company.com"
    records.#: "" => "<computed>"
    ttl:       "" => "60"
    type:      "" => "A"
    weight:    "" => "-1"
    zone_id:   "" => "Z2SO3DJTXPGLLI"


Plan: 6 to add, 0 to change, 2 to destroy.
```

Apply error

```
Error applying plan:

1 error(s) occurred:

* aws_instance.alexsnode: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.14
    Resource ID: aws_instance.alexsnode
    Mismatch reason: attribute mismatch: associate_public_ip_address
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"root_block_device.0.delete_on_termination":*terraform.ResourceAttrDiff{Old:"true", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "associate_public_ip_address":*terraform.ResourceAttrDiff{Old:"true", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "source_dest_check":*terraform.ResourceAttrDiff{Old:"true", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

What has changed was me adding ignore_changes to my user_data template and ec2 resource. All I really need to do is add some DNS settings.

**Comment by pporada-gl** [comment] 2016-03-25 15:11
Turns out I needed to ignore_changes on the following before my apply would work.
```
associate_public_ip_address
root_block_device.0.delete_on_termination
source_dest_check
```

Terraform still told me that 6 resources were going to be added and 2 were going to be destroyed. Even though I was only shown 4 resources that were going to be added.

**Comment by phinze** [comment] 2016-03-25 16:28
@pporada-gl thanks for the report - this is definitely odd behavior. Looks like we might have some sort of bug in the boolean field diff handling here.

Can you share the config that's causing this?

**Comment by pporada-gl** [comment] 2016-03-25 16:47
@phinze 
My files are kinda.... verbose. Here you go.

Provider
```
variable "region" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "env" {}
variable "company" {}
variable "company_ip" {}
variable "vpc_cidr" {}
variable "peered_vpc_cidr" {}
variable "azs" {}
variable "private_subnet_cidrs" {}
variable "ssl_cert_arn" {}
variable "ec2_alexsnode_ami" {}
variable "ec2_alexsnode_instance_type" {}
variable "ec2_alexsnode_storage_type" {}
variable "ec2_alexsnode_storage_size" {}
variable "ec2_alexsnode_user" {}
variable "key_name" {}
variable "key_path" {}

resource "terraform_remote_state" "dns" {
	backend = "s3"
	config {
    	region = "us-east-1"
    	bucket = "${var.env}-${var.company}-${var.short_region}-terraform-state"
    	key = "dns/${var.env}.tfstate"
    }
}

resource "terraform_remote_state" "build-vpc" {
	backend = "s3"
	config {
    	region = "us-east-1"
    	bucket = "${var.env}-${var.company}-${var.short_region}-terraform-state"
    	key = "vpc/${var.env}.tfstate"
    }
}

provider "aws" {
    region 		= "${var.region}"
	access_key 	= "${var.aws_access_key}"
    secret_key 	= "${var.aws_secret_key}"
}

module "nodeapp" {
    source          = "../../../../modules/aws/stacks/alexsnode/"
    env             = "${var.env}"
    public_subnet_ids   = "${terraform_remote_state.build-vpc.output.public_subnet_ids}"
    vpc_id          = "${terraform_remote_state.build-vpc.output.vpc_id}"
    vpc_cidr        = "${var.vpc_cidr}"
    ami             = "${var.ec2_alexsnode_ami}"
    instance_type   = "${var.ec2_alexsnode_instance_type}"
    storage_type    = "${var.ec2_alexsnode_storage_type}"
    storage_size    = "${var.ec2_alexsnode_storage_size}"
    shell_username  = "${var.ec2_alexsnode_user}"
    key_name        = "${var.key_name}"
    key_path        = "${var.key_path}"
    peered_vpc_cidr = "${var.peered_vpc_cidr}"
    company_ip      = "${var.company_ip}"
    azs             = "${var.azs}"
    public_zone_id  = "${terraform_remote_state.dns.output.public_zone_id}"
    public_domain   = "${terraform_remote_state.dns.output.public_domain}"
    private_zone_id  = "${terraform_remote_state.dns.output.private_zone_id}"
    private_domain   = "${terraform_remote_state.dns.output.private_domain}"
}

// VPC
output "environment" { value = "${var.env}" }

// Nodeapp
output "nodeapp1_public_url" { value = "${module.nodeapp.public_url_1}" }
output "nodeapp2_public_url" { value = "${module.nodeapp.public_url_2}" }
output "nodeapp1_private_url" { value = "${module.nodeapp.private_url_1}" }
output "nodeapp2_private_url" { value = "${module.nodeapp.private_url_2}" }
```

Module
```
variable "env" {}
variable "ami" {}
variable "azs" {}
variable "instance_type" {}
variable "key_name" {}
variable "key_path" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "peered_vpc_cidr" {}
variable "public_subnet_ids" {}
variable "company_ip" {}
variable "shell_username" {}
variable "public_zone_id" {}
variable "public_domain" {}
variable "private_zone_id" {}
variable "private_domain" {}
variable "storage_type" {}
variable "storage_size" {}

resource "aws_security_group" "nodeapp" {
  name        = "glapp_${var.env}_nodeapp_secgroup"
  vpc_id      = "${var.vpc_id}"
  description = "nodeapp security group"

  tags {
      Name = "glapp_${var.env}_nodeapp_secgroup"
      TERRAFORM = "true"
  }

  ingress {
    protocol    = -1
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["${var.vpc_cidr}", "${split(",", var.peered_vpc_cidr)}"]
  }

  ingress {
    protocol    = "tcp"
    from_port   = 22
    to_port     = 22
    cidr_blocks = ["${var.company_ip}", "${split(",", var.peered_vpc_cidr)}"]
  }

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    protocol    = -1
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "template_file" "alexsnode" {
  	template = "${file("${path.module}/init.sh")}"
    lifecycle {
        ignore_changes = ["template"]
    }
  	vars {
        TERRAFORM_env = "${var.env}"
	}
}

resource "aws_instance" "alexsnode" {
    ami                     = "${var.ami}"
    instance_type           = "${var.instance_type}"
    key_name                = "${var.key_name}"
    subnet_id               = "${element(split(",", var.public_subnet_ids), 1)}"
    vpc_security_group_ids  = ["${aws_security_group.nodeapp.id}"]
    user_data               = "${template_file.alexsnode.rendered}"
    associate_public_ip_address = true

    lifecycle {
        ignore_changes = ["user_data", "associate_public_ip_address","source_dest_check", "root_block_device"]
    }

    root_block_device = {
        volume_type = "${var.storage_type}"
        volume_size = "${var.storage_size}"
    }

    tags {
        Name        = "glapp_${var.env}_alexsnode"
        ENV         = "${var.env}"
        TERRAFORM   = "true"
    }
}

resource "aws_route53_record" "nodeapp1-pub" {
  	zone_id = "${var.public_zone_id}"
  	name = "schema.${var.public_domain}"
    type = "A"
    ttl = "60"
    records = ["${aws_instance.alexsnode.public_ip}"]
}

resource "aws_route53_record" "nodeapp2-pub" {
  	zone_id = "${var.public_zone_id}"
  	name = "mock.${var.public_domain}"
    type = "A"
    ttl = "60"
    records = ["${aws_instance.alexsnode.public_ip}"]
}

resource "aws_route53_record" "nodeapp1-priv" {
  	zone_id = "${var.private_zone_id}"
  	name = "schema.${var.private_domain}"
    type = "A"
    ttl = "60"
    records = ["${aws_instance.alexsnode.private_ip}"]
}

resource "aws_route53_record" "nodeapp2-priv" {
  	zone_id = "${var.private_zone_id}"
  	name = "mock.${var.private_domain}"
    type = "A"
    ttl = "60"
    records = ["${aws_instance.alexsnode.private_ip}"]
}

output "public_ip" { value = "${aws_instance.alexsnode.public_ip}" }
output "public_url_1" { value = "${aws_route53_record.nodeapp1-pub.name}" }
output "public_url_2" { value = "${aws_route53_record.nodeapp2-pub.name}" }

output "private_ip" { value = "${aws_instance.alexsnode.private_ip}" }
output "private_url_1" { value = "${aws_route53_record.nodeapp1-priv.name}" }
output "private_url_2" { value = "${aws_route53_record.nodeapp2-priv.name}" }
```

**Comment by mitchellh** [comment] 2016-10-30 21:52
This has been fixed on master, I can't reproduce it with your config and the error message is identical to what was fixed earlier this week!

**Closed by mitchellh** 2016-10-30 21:52 UTC
Labels: bug, core
