### ISSUE TITLE
aws_elb_attachment should support autoscaling groups as well as instances

### ISSUE THREAD

**Issue by devinsba** [hashicorp/terraform#8688] opened 2016-09-06 17:08 UTC
### Affected Resource(s)
- aws_elb_attachment
### Expected Behavior

I should be able to attach an ELB to an autoscaling group
### Important Factoids

The behavior exists within the autoscaling CLI http://docs.aws.amazon.com/cli/latest/reference/autoscaling/attach-load-balancers.html
It would seem natural that it belongs in this resource but it could be a separate resource.

**Comment by stack72** [comment] 2016-10-31 12:06
Hi @devinsba 

I am going to close this as a dupe of #8755

There is some tracking happening there - including a supporting PR that could fix the issue. Please keep an eye on that issue

Thanks

Paul

**Closed by stack72** 2016-10-31 12:06 UTC
Labels: enhancement, provider/aws
