### ISSUE TITLE
`filebase64sha256` returns `no such file or directory` in combination with `archive_file`

### ISSUE THREAD

**Issue by shoekstra** [hashicorp/terraform#30042] opened 2021-11-28 09:35 UTC
### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

```terraform
resource "local_file" "default" {
  content  = templatefile("${path.cwd}/dummy.txt", {})
  filename = "${path.cwd}/dummy.new"
}

data "archive_file" "default" {
  type        = "zip"
  source_file = local_file.default.filename
  output_path = "${path.cwd}/dummy.zip"
}

resource "null_resource" "default" {
  triggers = {
    hash = filebase64sha256(data.archive_file.default.output_path),
  }
}
```

### Debug Output

https://gist.github.com/shoekstra/edc58ebc5cc9505e1224b90a1e34b106

### Expected Behavior

`filebase64sha256(data.archive_file.default.output_path)` is called after the `data.archive_file.default` resource has created the zip file.

### Actual Behavior

`filebase64sha256(data.archive_file.default.output_path)` is called before the `data.archive_file.default` resource has created the zip file and fails because the file does not exist.

### Steps to Reproduce

1. Create new directory and put above Terraform into `main.tf`
2. `echo dummy > dummy.txt`
3. `terraform apply`

Result:

```
╷
│ Error: Error in function call
│
│   on main.tf line 14, in resource "null_resource" "default":
│   14:     hash = filebase64sha256(data.archive_file.default.output_path),
│     ├────────────────
│     │ data.archive_file.default.output_path is "/Users/shoekstra/git/issue-code/dummy.zip"
│
│ Call to function "filebase64sha256" failed: open /Users/shoekstra/git/issue-code/dummy.zip: no such file or directory.
```

Works as expected if first targeting the data resource:

```
$ terraform apply -target=data.archive_file.default -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.archive_file.default will be read during apply
  # (config refers to values not yet known)
 <= data "archive_file" "default"  {
      + id                  = (known after apply)
      + output_base64sha256 = (known after apply)
      + output_md5          = (known after apply)
      + output_path         = "/Users/shoekstra/git/issue-code/dummy.zip"
      + output_sha          = (known after apply)
      + output_size         = (known after apply)
      + source_file         = "/Users/shoekstra/git/issue-code/dummy.new"
      + type                = "zip"
    }

  # local_file.default will be created
  + resource "local_file" "default" {
      + content              = <<-EOT
            dummy
        EOT
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "/Users/shoekstra/git/issue-code/dummy.new"
      + id                   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
local_file.default: Creating...
local_file.default: Creation complete after 0s [id=f161ebd29699d93411cec0915c5133c0f3229a28]
data.archive_file.default: Reading...
data.archive_file.default: Read complete after 0s [id=74b55fb8a343347f4ffa0b8dc536a4c3824d1755]

$ terraform apply -auto-approve
local_file.default: Refreshing state... [id=f161ebd29699d93411cec0915c5133c0f3229a28]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.default will be created
  + resource "null_resource" "default" {
      + id       = (known after apply)
      + triggers = {
          + "hash" = "8lsT3OXbBC1oUp6skmrMN3N/RCi7fgtuX0n2EXFlLLE="
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.default: Creating...
null_resource.default: Creation complete after 0s [id=5251941669950273077]
```

### References

- #27939 looks related

**Comment by alisdair** [comment] 2021-11-29 15:54
Hi @shoekstra. The cause of the issue here is calling a function with a known argument (as `data.archive_file.default.output_path` is specified by your configuration) which is then immediately evaluated, before the data source is refreshed.

Aside from the `-target` workaround you already found, I think the easiest solution here would be to directly use [the `output_base64sha256` attribute of the data source](https://registry.terraform.io/providers/hashicorp/archive/latest/docs/data-sources/archive_file#attributes-reference) instead of calling `filebase64sha256`. That is:

```terraform
resource "null_resource" "default" {
  triggers = {
    hash = data.archive_file.default.output_base64sha256,
  }
}
```

This then plans and applies correctly:

```shellsession
$ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.archive_file.default will be read during apply
  # (config refers to values not yet known)
 <= data "archive_file" "default"  {
      + id                  = (known after apply)
      + output_base64sha256 = (known after apply)
      + output_md5          = (known after apply)
      + output_path         = "/Users/alisdair/Desktop/repro/30042/dummy.zip"
      + output_sha          = (known after apply)
      + output_size         = (known after apply)
      + source_file         = "/Users/alisdair/Desktop/repro/30042/dummy.new"
      + type                = "zip"
    }

  # local_file.default will be created
  + resource "local_file" "default" {
      + content              = <<-EOT
            hello
        EOT
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "/Users/alisdair/Desktop/repro/30042/dummy.new"
      + id                   = (known after apply)
    }

  # null_resource.default will be created
  + resource "null_resource" "default" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
local_file.default: Creating...
local_file.default: Creation complete after 0s [id=f572d396fae9206628714fb2ce00f72e94f2258f]
data.archive_file.default: Reading...
data.archive_file.default: Read complete after 0s [id=9fe9b36abb7ab54f622478aeb66edbe9a19d82ef]
null_resource.default: Creating...
null_resource.default: Creation complete after 0s [id=5891673584615601693]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

Given this explanation, I don't think there's a bug in Terraform here, so I'm going to close this out. If there's a real-world example that this config is derived from where this suggestion doesn't solve the problem, please respond with some details and I'll look into that. Thanks again for the report!

**Closed by alisdair** 2021-11-29 15:54 UTC
Labels: bug, new

**Comment by shoekstra** [comment] 2021-11-29 23:04
Hi @alisdair, I didn't think to see if `archive_file` had such an output and happy to report this now works as expected. Thanks for the quick response!
