### ISSUE TITLE
0.12 > 0.13 state issues with various objects. 

### ISSUE THREAD

**Issue by bourbonfgiles** [hashicorp/terraform#25941] opened 2020-08-20 15:43 UTC
Hello,

Just upgraded Terraform from 0.12.28 to 0.13.30. On a plan-apply, previously working items seem to fail in reading attributes from the state file (remote, Azure blob storage). 

I've downgraded again to 0.12.28 and the plan-apply works perfectly. 

Thanks. Output from plan-apply below. 

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-kv/key_vault.tf line 105:
 105: resource "azurerm_key_vault" "object" {

Instance module.kv.azurerm_key_vault.object data could not be decoded from the
state: unsupported attribute "sku".

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-kv/key_vault.tf line 105:
 105: resource "azurerm_key_vault" "object" {

Instance module.kv.azurerm_key_vault.object data could not be decoded from the
state: unsupported attribute "sku".

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-kv/key_vault.tf line 105:
 105: resource "azurerm_key_vault" "object" {

Instance module.kv.azurerm_key_vault.object data could not be decoded from the
state: unsupported attribute "sku".

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-kv/key_vault.tf line 105:
 105: resource "azurerm_key_vault" "object" {

Instance module.kv.azurerm_key_vault.object data could not be decoded from the
state: unsupported attribute "sku".

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-vnet/vnet/subnet.tf line 47:
  47: resource "azurerm_subnet" "object" {

Instance module.hub_and_spoke.module.sql_vnet.azurerm_subnet.object data could
not be decoded from the state: unsupported attribute "ip_configurations".

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-vnet/vnet/subnet.tf line 47:
  47: resource "azurerm_subnet" "object" {

Instance module.hub_and_spoke.module.vm_vnet.azurerm_subnet.object data could
not be decoded from the state: unsupported attribute "ip_configurations".

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-vnet/vnet/subnet.tf line 47:
  47: resource "azurerm_subnet" "object" {

Instance module.hub_and_spoke.module.hub_vnet.azurerm_subnet.object data could
not be decoded from the state: unsupported attribute "ip_configurations".

Error: Invalid resource instance data in state

  on ../../../../../terraform/azr-vnet/vnet/subnet.tf line 47:
  47: resource "azurerm_subnet" "object" {

Instance module.hub_and_spoke.module.dmz_vnet.azurerm_subnet.object data could
not be decoded from the state: unsupported attribute "ip_configurations".

**Comment by alisdair** [comment] 2020-08-20 15:49
This looks like a duplicate of #25752, which will be fixed in the next Terraform release. Thanks!

**Closed by alisdair** 2020-08-20 15:49 UTC
Labels: bug, new
