### ISSUE TITLE
Terraform Enterprise : panic: value is marked, so must be unmarked 

### ISSUE THREAD

**Issue by muralijv** [hashicorp/terraform#28817] opened 2021-05-26 16:34 UTC
### Terraform Version

 Terraform required_version = ">= 0.14"

### Debug Output

Terraform v0.15.1
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
panic: value is marked, so must be unmarked first

goroutine 4036 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.2/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2c37160, 0xc0006fa8b0, 0x24e9360, 0xc002c98030, 0x0)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.2/cty/value_ops.go:1050 +0x4f
github.com/hashicorp/terraform/plans/objchange.proposedNewNestedBlock(0xc000c32500, 0x2c37160, 0xc0006fab20, 0x23d1100, 0x3cefe80, 0x2c37160, 0xc0006fa8b0, 0x24e9360, 0xc002c98030, 0xc002c98030, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:217 +0x11cc
github.com/hashicorp/terraform/plans/objchange.proposedNew(0xc0009a41b0, 0x2c37128, 0xc0006fab30, 0x23d1100, 0x3cefe80, 0x2c37128, 0xc0006fa8c0, 0x23fab60, 0xc002452930, 0x90, ...)
	/home/circleci/project/project/plans/objchange/objchange.go:89 +0x33c
github.com/hashicorp/terraform/plans/objchange.PlannedDataResourceObject(0xc0009a41b0, 0x2c37128, 0xc0006fa8c0, 0x23fab60, 0xc002452930, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/project/plans/objchange/objchange.go:64 +0x89
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).planDataSource(0xc002a1e700, 0x2c6cc70, 0xc00231a000, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:1361 +0x7aa
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xc00075e530, 0x2c6cc70, 0xc00231a000, 0x21, 0xc003b0c6c0, 0xc002339c50)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:74 +0x478
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc00075e530, 0x2c6cc70, 0xc00231a000, 0xc000142002, 0xc002339ce8, 0x40bb05, 0x2444540)
	/home/circleci/project/project/terraform/node_resource_plan_instance.go:44 +0x10d
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000b82540, 0x2c6cc70, 0xc00231a000, 0x7fcc30992a00, 0xc00075e530, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbf
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2774800, 0xc00075e530, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00060c600, 0x2774800, 0xc00075e530, 0xc00082db40)
	/home/circleci/project/project/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:304 +0x1246

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.065349563.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.065349563.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 1)
Output: Terraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

State read error: Error loading statefile: open /terraform/terraform.tfplan: no such file or directory

Plan read error: open /terraform/terraform.tfplan: no such file or directory


**Comment by jbardin** [comment] 2021-05-26 17:16
Duplicate of #28535

**Closed by jbardin** 2021-05-26 17:16 UTC
Labels: bug, new
