### ISSUE TITLE
Terraform Crashed When Running terraform plan

### ISSUE THREAD

**Issue by cloudhashicorp** [hashicorp/terraform#22284] opened 2019-08-01 07:10 UTC
### Terraform Version

2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.publicsubnets[2]": visit complete
2019/08/01 17:07:47 [WARN] Provider "aws" produced an invalid plan for module.vpc.aws_subnet.publicsubnets[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .map_public_ip_on_launch: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .assign_ipv6_address_on_creation: planned value cty.False does not match config value cty.NullVal(cty.Bool)
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalCheckPreventDestroy
2019/08/01 17:07:47 [TRACE] [walkPlan] Exiting eval tree: module.vpc.aws_subnet.publicsubnets[1]
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteState
2019/08/01 17:07:47 [TRACE] GetResourceInstance: aws_vpc.projectDTRN is a single instance
2019/08/01 17:07:47 [TRACE] EvalWriteState: writing current state object for module.vpc.aws_subnet.publicsubnets[0]
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.publicsubnets[1]": visit complete
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteDiff
2019/08/01 17:07:47 [WARN] Provider "aws" produced an invalid plan for module.vpc.aws_subnet.applicationsubnets[1], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .assign_ipv6_address_on_creation: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .map_public_ip_on_launch: planned value cty.False does not match config value cty.NullVal(cty.Bool)
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalCheckPreventDestroy
2019/08/01 17:07:47 [TRACE] EvalWriteDiff: recorded Create change for module.vpc.aws_subnet.publicsubnets[0]
2019/08/01 17:07:47 [TRACE] [walkPlan] Exiting eval tree: module.vpc.aws_subnet.publicsubnets[0]
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteState
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.publicsubnets[0]": visit complete
2019/08/01 17:07:47 [TRACE] EvalWriteState: writing current state object for module.vpc.aws_subnet.applicationsubnets[1]
2019/08/01 17:07:47 [TRACE] dag/walk: visiting "root"
2019/08/01 17:07:47 [TRACE] vertex "root": starting visit (terraform.graphNodeRoot)
2019/08/01 17:07:47 [TRACE] vertex "root": visit complete
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.publicsubnets": dynamic subgraph completed successfully
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.publicsubnets": visit complete
2019/08/01 17:07:47 [TRACE] Re-validating config for "module.vpc.aws_subnet.datasubnets[1]"
2019/08/01 17:07:47 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteDiff
2019/08/01 17:07:47 [TRACE] EvalWriteDiff: recorded Create change for module.vpc.aws_subnet.applicationsubnets[1]
2019/08/01 17:07:47 [TRACE] [walkPlan] Exiting eval tree: module.vpc.aws_subnet.applicationsubnets[1]
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.applicationsubnets[1]": visit complete
2019/08/01 17:07:47 [TRACE] dag/walk: visiting "root"
2019/08/01 17:07:47 [TRACE] vertex "root": starting visit (terraform.graphNodeRoot)
2019/08/01 17:07:47 [TRACE] vertex "root": visit complete
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.applicationsubnets": dynamic subgraph completed successfully
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.applicationsubnets": visit complete
2019/08/01 17:07:47 [TRACE] GRPCProvider: PlanResourceChange
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalCheckPreventDestroy
2019/08/01 17:07:47 [WARN] Provider "aws" produced an invalid plan for module.vpc.aws_subnet.datasubnets[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .assign_ipv6_address_on_creation: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .map_public_ip_on_launch: planned value cty.False does not match config value cty.NullVal(cty.Bool)
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalCheckPreventDestroy
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteState
2019/08/01 17:07:47 [TRACE] EvalWriteState: writing current state object for module.vpc.aws_subnet.datasubnets[0]
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteDiff
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalCheckPreventDestroy
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteState
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalCheckPreventDestroy
2019/08/01 17:07:47 [TRACE] EvalWriteState: writing current state object for module.vpc.aws_route_table.publicroutetable[1]
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteState
2019/08/01 17:07:47 [TRACE] EvalWriteState: writing current state object for module.vpc.aws_route_table.publicroutetable[2]
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteDiff
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteDiff
2019/08/01 17:07:47 [TRACE] EvalWriteDiff: recorded Create change for module.vpc.aws_route_table.publicroutetable[1]
2019/08/01 17:07:47 [TRACE] [walkPlan] Exiting eval tree: module.vpc.aws_route_table.publicroutetable[1]
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route_table.publicroutetable[1]": visit complete
2019/08/01 17:07:47 [TRACE] EvalWriteDiff: recorded Create change for module.vpc.aws_subnet.datasubnets[0]
2019/08/01 17:07:47 [TRACE] [walkPlan] Exiting eval tree: module.vpc.aws_subnet.datasubnets[0]
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_subnet.datasubnets[0]": visit complete
2019/08/01 17:07:47 [TRACE] EvalWriteDiff: recorded Create change for module.vpc.aws_route_table.publicroutetable[2]
2019/08/01 17:07:47 [TRACE] [walkPlan] Exiting eval tree: module.vpc.aws_route_table.publicroutetable[2]
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route_table.publicroutetable[2]": visit complete
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteState
2019/08/01 17:07:47 [TRACE] EvalWriteState: writing current state object for module.vpc.aws_route_table.publicroutetable[0]
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteDiff
2019/08/01 17:07:47 [TRACE] EvalWriteDiff: recorded Create change for module.vpc.aws_route_table.publicroutetable[0]
2019/08/01 17:07:47 [TRACE] [walkPlan] Exiting eval tree: module.vpc.aws_route_table.publicroutetable[0]
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route_table.publicroutetable[0]": visit complete
2019/08/01 17:07:47 [TRACE] dag/walk: visiting "root"
2019/08/01 17:07:47 [TRACE] vertex "root": starting visit (terraform.graphNodeRoot)
2019/08/01 17:07:47 [TRACE] vertex "root": visit complete
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route_table.publicroutetable": dynamic subgraph completed successfully
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route_table.publicroutetable": visit complete
2019/08/01 17:07:47 [TRACE] dag/walk: visiting "module.vpc.aws_route.publicroute"
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route.publicroute": starting visit (*terraform.NodePlannableResource)
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route.publicroute": evaluating
2019/08/01 17:07:47 [TRACE] [walkPlan] Entering eval tree: module.vpc.aws_route.publicroute
2019/08/01 17:07:47 [TRACE] module.vpc: eval: *terraform.EvalWriteResourceState
2019/08/01 17:07:47 [TRACE] vertex "module.vpc.aws_route.publicroute": visit complete
panic: not a string

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by lawliet89** [comment] 2019-08-01 09:23
Probably the same issue.

With the following configuration:

```hcl
resource "google_project_service" "workload" {
  for_each = var.api_services

  project = var.project_id
  service = each.key

  disable_on_destroy = false
}

variable "project_id" {
  description = "Project ID"
}

variable "api_services" {
  description = "List of API services to enable"

  default = [
    "compute.googleapis.com",
    "cloudbilling.googleapis.com",
    "iam.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "cloudkms.googleapis.com",
    "container.googleapis.com",
    "servicenetworking.googleapis.com",
    "dns.googleapis.com",
    "logging.googleapis.com",
    "storage-component.googleapis.com",
    "storage-api.googleapis.com",
  ]
}
```

Panic:
```
panic: not a string

goroutine 237 [running]:
github.com/zclconf/go-cty/cty.Value.AsString(...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:1026
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x2228cc0, 0xc000338ea0, 0x19cd420, 0xc000338ec0, 0xe)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.0.1-0.20190708163926-19588f92a98f/cty/value_ops.go:1095 +0x38a
github.com/hashicorp/terraform/terraform.evaluateResourceForEachExpressionKnown(0x2227980, 0xc00035b3e0, 0x225a540, 0xc000bfe000, 0x1f, 0xc00075e150, 0x19f0bc0, 0x0, 0x19f0bc0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_for_each.go:84 +0x5bd
github.com/hashicorp/terraform/terraform.evaluateResourceForEachExpression(0x2227980, 0xc00035b3e0, 0x225a540, 0xc000bfe000, 0x1, 0x1, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_for_each.go:17 +0x5c
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResource).DynamicExpand(0xc000412188, 0x225a540, 0xc000bfe000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:42 +0x280
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1ce35a0, 0xc000412188, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:103 +0x8b1
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000124d00, 0x1ce35a0, 0xc000412188, 0xc000383f40)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

```

**Comment by teamterraform** [comment] 2019-08-01 11:15
Hello, to better understand this issue & make it easier to reproduce for anyone else, please could you add the following details:

 - Terraform version
 - provider version(s)
 - which commands you ran, and their full output (stdout + stderr) (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by kmoe** [comment] 2019-08-02 11:19
It looks like this may be a duplicate of #22305, which is fixed in https://github.com/hashicorp/terraform/pull/22279.

If you see the same behaviour in Terraform v0.12.7 or later, please open a new issue including all the details specified by @teamterraform above.

**Closed by kmoe** 2019-08-02 11:19 UTC
Labels: bug, crash, waiting-response
