### ISSUE TITLE
Apply is successful and subsequent apply fails because resources are already created

### ISSUE THREAD

**Issue by kylegalbraith** [hashicorp/terraform#17666] opened 2018-03-21 19:52 UTC
It would appear that an apply operation on my TF stack is successful. I can confirm this by seeing that the AWS resources are created. However, a subsequent apply fails because the resources cannot be created again (i.e. a S3 bucket). But my understanding is that the apply should check the state, see that the bucket is created, and skip running that piece.
### Terraform Version
```
terraform -v
Terraform v0.11.4
+ provider.aws v1.11.0
```

### Terraform Configuration Files
https://gist.github.com/kylegalbraith/bab98a76a5fef597d23eb730331e72b9

### Debug Output
https://gist.github.com/kylegalbraith/59ce9cccaccc620f34990bd53632ebb3

### Expected Behavior
I would expect the next apply to read the .tfstate and skip trying to create resources that are already present.

### Actual Behavior
Apply tries to create a bucket that is already there and blows away the .tfstate file so that it is now empty.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -var "packagePath=<enter-zip-file>" -var "packageName=<enter-zip-file>"
3. First is successful, verify the tfstate file has resources.
4. `terraform apply -var "packagePath=<enter-zip-file>" -var "packageName=<enter-zip-file>"

### Additional Context
Nothing atypical I am doing here, just running Terraform from a Windows command line.

**Comment by jbardin** [comment] 2018-03-21 19:58
Hi @kylegalbraith,

Sorry you're having an issue with this. This looks like a duplicate of #17620

**Comment by kylegalbraith** [comment] 2018-03-21 20:04
@jbardin It looks eerily similar. Any idea when that will be pushed out to a new version? Should I revert to .3 for now?

**Comment by jbardin** [comment] 2018-03-21 20:07
@kylegalbraith, You can either revert to 0.11.3, or you can try using `-lock=false`, since the problem stems from the way Windows locks files. 

We should have a patch release out shortly to take care of this.

**Comment by jbardin** [comment] 2018-03-21 21:53
Hi @kylegalbraith,

I just released 0.11.5 which covers the Windows regression. 
If the `-lock=false` workaround or 0.11.5 doesn't resolve the issue, feel free to reply here and we can continue to investigate.

**Closed by jbardin** 2018-03-21 21:53 UTC
