### ISSUE TITLE
Terraform Cloud Crash

### ISSUE THREAD

**Issue by ernesto-ops** [hashicorp/terraform#29104] opened 2021-07-06 14:23 UTC
### Terraform Version

```
Terraform v1.0.1 (It works in v1.0.0)
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.19.2
+ provider registry.terraform.io/hashicorp/aws v3.34.0
+ provider registry.terraform.io/hashicorp/helm v2.0.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Crash Output
```go
panic: value is marked, so must be unmarked first

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2cbab70, 0xc0056d9480, 0x25536a0, 0xc004ee15f0, 0x2cbab01)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1050 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc0056fd140, 0x1, 0x1, 0x2cbab70, 0xc0056d9480, 0x25536a0, 0xc004ee15f0, 0x2c84028, 0xc004f1c678, 0xc004ee15f0, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:144 +0x2e8
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x2cbab38, 0xc0056d9690, 0x245fdc0, 0xc0056dba70, 0x2c84028, 0xc004f1c678, 0xc0056fce40, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x2cbab38, 0xc0056d9690, 0x245fdc0, 0xc0056dba70, 0xc00a58c520, 0x1, 0x1, 0x2c1a2c0, 0x1, 0xc00683bc70, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:236 +0xc5
github.com/hashicorp/terraform/internal/command/jsonstate.marshalResources(0xc0087c2570, 0x0, 0x0, 0x0, 0xc005a1f690, 0xc004d2aeb0, 0x1, 0x1, 0xc0078bb458, 0x0)
	/home/circleci/project/project/internal/command/jsonstate/state.go:333 +0xe07
github.com/hashicorp/terraform/internal/command/jsonstate.marshalRootModule(0xc002f24028, 0xc005a1f690, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/internal/command/jsonstate/state.go:200 +0x12d
github.com/hashicorp/terraform/internal/command/jsonstate.(*state).marshalStateValues(0xc008ad1b30, 0xc002f24028, 0xc005a1f690, 0x0, 0x0)
	/home/circleci/project/project/internal/command/jsonstate/state.go:166 +0x14a
github.com/hashicorp/terraform/internal/command/jsonstate.Marshal(0xc0087c20c0, 0xc005a1f690, 0x0, 0x0, 0x0, 0x0, 0x219f5b5)
	/home/circleci/project/project/internal/command/jsonstate/state.go:146 +0xf8
github.com/hashicorp/terraform/internal/command/jsonplan.Marshal(0xc005a0b380, 0xc002f36e60, 0xc0087c20c0, 0xc005a1f690, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/command/jsonplan/plan.go:152 +0x633
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0xc0005cc1c0, 0xc00004c0b0, 0x1, 0x2, 0xc000326ba0)
	/home/circleci/project/project/internal/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc0004743c0, 0xc0005be480, 0x282e5dd, 0x4)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x554
main.main()
	/home/circleci/project/project/main.go:58 +0x25
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
```
Terraform will perform the following actions:

  # kubernetes_deployment.prod_backend_deployment will be created
  + resource "kubernetes_deployment" "prod_backend_deployment" {
      + id               = (known after apply)
      + wait_for_rollout = true

      + metadata {
          ...
        }

      + spec {
          ...
        }
    }

  # kubernetes_ingress.prod_frontend_ingress will be created
  + resource "kubernetes_ingress" "prod_frontend_ingress" {
      + id     = (known after apply)
      + status = (known after apply)

      + metadata {
          ...
        }

      + spec {
          ...
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

**Comment by jbardin** [comment] 2021-07-06 15:26
Duplicate of #29042

**Closed by jbardin** 2021-07-06 15:26 UTC
Labels: bug, new
