### ISSUE TITLE
Unchanged module throwing "This value does not have any indices."

### ISSUE THREAD

**Issue by ianwremmel** [hashicorp/terraform#25768] opened 2020-08-07 05:02 UTC
I'm pretty sure this is a bug, but it may well be as-designed behavior that's not clearly documented. 

For purposes of this issue, my terraform code is laid out something like

```
├── root.tf
└── modules
    ├── other
    │   └── main.tf
    └── load-balancer
        └── main.tf
```

10 days ago, I made changes in `modules/other/main.tf` and `plan` & `apply` completed successfully. Today, I tried to delete several `aws_route53_zone`s defined in `root.tf` and `plan` informed me that that I needed to remove `region` from several `aws_s3_bucket`s. I don't know when that change became necessary, but it was definitely acceptable 10 days ago on the same version of Terraform (based on the historical state files in Terraform cloud). 

I removed the `region` attributes from the buckets in question, and now plan fails with the error below. The error below effectively comes from `modules/load-balancer/main.tf` in the simplified directory structure above. Note that I've made no changes to `modules/load-balancer/main.tf`.

Is this a bug? Can I work around it or do I somehow have to rebuild my entire config from scratch and migrate all the resources?

Does Terraform do some amount of lazy evaluation where it doesn't necessarily check if a module needs to be applied, such that this is something I've been doing wrong for a long time, but didn't get detected because `load-balancer` hasn't been evaluated in my post recent plan/applies?

### Terraform Version

```
Terraform v0.12.29
```

### Terraform Configuration Files

```terraform
variable "target_groups" {
  type = map(list(string))
}

locals {
  tuple_of_maps = [
    for target_group, domains in var.target_groups :
    { for domain in domains : domain => target_group }
  ]

  domains = merge(flatten([local.tuple_of_maps])...)
}

resource "aws_acm_certificate" "this" {
  for_each = var.create_load_balancer ? local.domains : {}

  domain_name       = each.key
  validation_method = "DNS"

  tags = {
    ManagedBy = "Terraform"
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "this" {
  for_each = var.create_load_balancer ? local.domains : {}

  # Since there are no SANs in aws_acm_certificate, we can assume this is always
  # a single-item array
  name    = aws_acm_certificate.this[each.key].domain_validation_options[0].resource_record_name # <-- THIS IS LINE 82 
  type    = aws_acm_certificate.this[each.key].domain_validation_options[0].resource_record_type
  zone_id = var.zone_id
  records = [aws_acm_certificate.this[each.key].domain_validation_options[0].resource_record_value]
  ttl     = 300
}

```

### Debug Output
Plan is executed on Terraform cloud and not 

### Expected Behavior
Plans succeeds

### Actual Behavior

Plans fails with a bunch of errors like 

```
Error: Invalid index

  on modules/util/aws/https-load-balancer/main.tf line 82, in resource "aws_route53_record" "this":
  82:   name    = aws_acm_certificate.this[each.key].domain_validation_options[0].resource_record_name
    |----------------
    | aws_acm_certificate.this is object with 6 attributes
    | each.key is "check-run-reporter.com"

This value does not have any indices.
```

### Additional Context

Terraform is running via Terraform Cloud.

**Comment by danieldreier** [comment] 2020-08-07 15:12
@ianwremmel since you're running on Terraform Cloud, you're eligible for Terraform Cloud support via email at tf-cloud@hashicorp.support. 

There may be a bug at the root of this, and if there is I'm happy to work on a reproduction case together, but as-is this looks like it will require a lot more interactive troubleshooting than we're equipped to do in this forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions and interactive troubleshooting. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help, or Terraform Cloud support when using Terraform via Terraform Cloud. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific documented bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please take this to support, link this issue, and they have an internal escalation process where they will bring this back to us in case they determine it's likely to be a bug in Terraform Core.

**Closed by danieldreier** 2020-08-07 15:12 UTC
Labels: bug, new

**Comment by aseixas-magnolia** [comment] 2020-08-07 18:29
Seems that it's an update to the AWS provider: latest is 3.0, and using, for example, version 2.68 should fix the issue

**Comment by ianwremmel** [comment] 2020-08-08 18:32
Note that rolling back to version 2 fixed the error, but the error doesn't quite align with what seems be the breaking change. The breaking change appears to be that `domain_validation_options` used to be a list, but now it's a set. The error seems to indicate that `domain_validation_options` is undefined.

**Comment by ianwremmel** [comment] 2020-08-08 18:34
Oh, I guess it's not technically wrong, but in "This value does not have any indices.", "This value" is rather ambiguous. Since it follows

```
    | aws_acm_certificate.this is object with 6 attributes
    | each.key is "check-run-reporter.com"
```

it seems like it's saying that `aws_acm_certificate.this` is a value without indices.
