### ISSUE TITLE
[Feature Request] Provide binary build for Linux ppc64le

### ISSUE THREAD

**Issue by runlevel5** [hashicorp/terraform#27647] opened 2021-02-01 12:44 UTC
## Context

Linux ppc64le is quite popular amongst enterprise users and researchers. I think it would be more convenient for adoption if terraform provides the linux ppc64le binary in https://releases.hashicorp.com/terraform/

**Comment by jbardin** [comment] 2021-02-01 14:25
Duplicate of #26522

**Closed by jbardin** 2021-02-01 14:25 UTC
Labels: enhancement, new
