### ISSUE TITLE
Pretty print option for jsonencode

### ISSUE THREAD

**Issue by nl-brett-stime** [hashicorp/terraform#28552] opened 2021-04-29 15:53 UTC
E.g.,

```
jsonencode(local.someVal)

// Produces e.g.,
// {a:1,b:2,c:3}
```

```
locals {
  indentSize = 4
}
...
jsonencode(local.someVal, local.indentSize)

// Produces e.g.,
// {
//     a: 1,
//     b: 2,
//     c: 3
// }
```

### Use-cases
Our use case is that we use TF to produce some systems and output JSON files for hand-off to another team who completes a remote integration. Right now we have a manual step to format the JSON for the other teams' review but sometimes we forget. It'd be nice to have TF output formatted / prett-printed automatically.

### Proposal
I've filed a similar ticket here:
https://github.com/zclconf/go-cty/issues/104

I hope that could be integrated once provided upstream.

### References
https://github.com/zclconf/go-cty/issues/104

**Comment by jbardin** [comment] 2021-04-30 14:13
Duplicate of #27987

**Closed by jbardin** 2021-04-30 14:13 UTC
Labels: enhancement, new
