### ISSUE TITLE
Missing validation causes crash in provider SDK

### ISSUE THREAD

**Issue by dbadola** [hashicorp/terraform#18755] opened 2018-08-29 05:11 UTC
[crash.log](https://github.com/hashicorp/terraform/files/2330737/crash.log)

terraform version
Terraform v0.11.7
+ provider.aws v1.33.0

These are the content  in main.tf file

provider "aws" {
  region                  = "${var.region}"
  shared_credentials_file = "${var.credential}" //Make sure you have credential file here
  profile                 = "${var.profile}"    //Make sure you have this profile in your credential file
}

data "aws_vpcs" "vpc" {
  tags {
    Name = "${var.vpc_tag}"
  }  
}

output "vpc" {
  value = "${data.aws_vpcs.vpc.ids}"
}

data "aws_subnet_ids" "filter1_sec_filter_intf" {
  vpc_id = "${data.aws_vpcs.vpc.ids}"
  tags {
    Name = "${var.filter1_sec_filter_intf_tag}"
  }  
}

**Comment by dbadola** [comment] 2018-08-29 09:37
Hi @bflad  if i would like to get 1 subnet from the list within a vpc how would i do that ?

**Comment by apparentlymart** [comment] 2018-11-01 01:04
Hi @dbadola,

The crash you encountered here had the same root cause as reported in #16902, which is now fixed in master. This fix will be included in the forthcoming v0.12.0 release.

Thanks for reporting this, and sorry for the delay in getting it fixed.

**Closed by apparentlymart** 2018-11-01 01:04 UTC
Labels: bug, config, crash, provider-sdk
