### ISSUE TITLE
Migrating to 0.15.1 shows unneeded update-in-place for sensitive values

### ISSUE THREAD

**Issue by nyurik** [hashicorp/terraform#28593] opened 2021-05-04 00:56 UTC
### Terraform Version

```
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.66.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/vault v2.19.1

```

### Terraform Configuration Files

Using `v0.14.11`, create a simple Vault value:

```terraform
resource "vault_generic_secret" "default" {
  path = "secret/test/nyurik/a"

  data_json = <<EOT
{
  "foo": ${jsonencode("bar")}
}
EOT
}
```
in a subsequent run using the same v0.14.11, add another resource:

```terraform
data "vault_generic_secret" "default" {
  path = "secret/test/nyurik/a"
}

resource "vault_generic_secret" "bar" {
  path = "secret/test/nyurik/b"

  data_json = <<EOT
{
  "foo": ${jsonencode(data.vault_generic_secret.default.data["foo"])}
}
EOT
}
```
now, switch to v0.15.1 and run `terraform plan`.

### Expected Behavior
I should see a noop plan.

### Actual Behavior
```terraform
  # vault_generic_secret.bar will be updated in-place
  ~ resource "vault_generic_secret" "bar" {
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ data_json    = (sensitive value)
        id           = "secret/test/nyurik/b"
        # (3 unchanged attributes hidden)
    }
```

### Steps to Reproduce
1. `terraform init` (using v0.14.11)
1. modify code as shown above to write a secret value to `secret/test/nyurik/a`
1. `terraform apply`
1. modify code as shown above to copy value from `secret/test/nyurik/a` to `secret/test/nyurik/b`
1. `terraform plan` -- observe that the data is already marked as sensitive (see below)
1. `terraform apply`
1. `terraform init` (update to v0.15.1)
1. `terraform plan`

### Notes
Observe that when planning the change to `secret/test/nyurik/b` using 0.14.11, the data is already shown as sensitive:

```terraform
  # vault_generic_secret.bar will be created
  + resource "vault_generic_secret" "bar" {
      + data         = (sensitive value)
      + data_json    = (sensitive value)
      + disable_read = false
      + id           = (known after apply)
      + path         = "secret/test/nyurik/b"
    }
```

**Comment by alisdair** [comment] 2021-05-04 13:24
Hi @nyurik, thanks for reporting this.

I believe this is expected behaviour due to the provider sensitive attributes change introduced in Terraform 0.15. Resource attributes which are designated `sensitive` by the provider schema are now marked as such throughout the Terraform language. As a result, Terraform needs to update the state file to mark these attributes as sensitive there, too, for consistency with other sensitive attributes.

With your example, if you apply the plan and inspect what happens to the state file, you'll see that the only change is in the sensitivity markers:

```diff
$ diff terraform.tfstate.backup terraform.tfstate
4c4
<   "serial": 3,
---
>   "serial": 5,
51c51,58
<           "sensitive_attributes": [],
---
>           "sensitive_attributes": [
>             [
>               {
>                 "type": "get_attr",
>                 "value": "data_json"
>               }
>             ]
>           ],
```

Is this behaviour causing a problem for you, or is it just surprising to see a plan diff?

**Comment by nyurik** [comment] 2021-05-04 23:27
@alisdair thanks for a quick reply! I understand this to be a state change, but this is not how it looks to the user. Internal state changes have happened many times in Terraform history -- every time there is an upgrade, Terraform modified the state without any user notification.

This case is different from the usability perspective. Traditionally every single line in the plan implied some resourcing change -- something that could potentially cause downtime, re-allocations and/or costs. With 0.15+, Terraform plan warns that something internal to the state file will change without any resource changes while using the same reporting mechanism.

Thus it is highly confusing and (IMO) should be fixed -- either by significantly changing the language and exit codes ("there are no changes but the state file will be modified"), or, preferably, by fully removing this as it appears to be just non-consequential messages.

**Comment by ohaibbq** [comment] 2021-05-04 23:35
:+1: I'm looking at a plan for upgrading our project to Terraform v0.15.1 and I see ~60 updates that need to be made. It shocked me at first, as I didn't have a way of validating that if the sensitive values in the plan actually changed, or if Terraform just needed to mark the values as sensitive.

**Comment by alisdair** [comment] 2021-05-05 16:56
Thanks to both of you for the clarification! I think there's probably something that can be done to address this, although it's not completely clear to me what the right approach is.

We can't fully remove this behaviour (i.e. make this a no-op plan) without redesigning how we handle sensitive attributes which also have sensitive values. I want to be up front and say that I don't think that's very likely to happen right now, as doing so would have negative consequences for other use cases. I'll explain a bit further why this is happening, in the hope that helps clarify things a bit.

This configuration example is one where the provider attribute is marked sensitive _and_ (as of 0.15) the attribute value is marked sensitive. When the resource was created in 0.14, only the first of these was true: the use of another resource's sensitive attribute did not result in a sensitive value. Now that you're using 0.15, the referenced value has had the sensitive marks added, which need to be recorded in the state file. This is what results in a planned change which needs to be applied.

The reason that it's important to keep the distinction between sensitive provider attributes and sensitive values is that a new provider version could mark an attribute as no longer sensitive. If we rely on the provider schema sensitivity and drop sensitivity marks for those values, this could lead to them being accidentally revealed in situations like this.

All that said, I think there's scope to improve the diff output to explain what's happening here. I think most one improvement would be to clarify what is happening here: indicate that the attribute value is changing only in that it is being marked sensitive.

The situation is quite complex to explain in UI, so I think we would be best to do this by [changing the `writeSensitivityWarning` function](https://github.com/hashicorp/terraform/blob/1e3a60c7ac00b512dc0b4a89e6a785c500be3932/command/format/diff.go#L1582-L1608) to take new parameters allowing us to detect this exact situation.

Here's an idea of what that output might look like:

```terraform
  # vault_generic_secret.bar will be updated in-place
  ~ resource "vault_generic_secret" "bar" {
      # Note: this sensitive attribute value will be marked as
      # sensitive, but its value is unchanged
      ~ data_json    = (sensitive)
        id           = "secret/test/nyurik/b"
        # (3 unchanged attributes hidden)
    }
```

If implemented, would this somewhat alleviate the problems you're facing?

**Comment by ohaibbq** [comment] 2021-05-05 17:00
Thank you, @alisdair! The suggested improvement is clear and would have prevented my confusion! 🙏

**Comment by nyurik** [comment] 2021-05-05 17:11
Thanks @alisdair. I would improve the language a bit more, e.g. something like (this is very rough too, and needs some polishing)

```
      # Note: this is an internal state file change only,
      # changing sensitive flag, but not its value.
      # This change will not modify any production resources.
```

The two important points that must be stressed:  1) this is NOT a resourcing change, despite being in the plan, and 2) it is not the value that changed, just the sensitivity attribute of the value.

Going forward I think there needs to be a more graceful way of reporting non-production-affecting changes.  Plan output has always implied real resource changes, so I am sure there will be many more people struggling with this issue and reporting it as a bug.  Thanks for looking into it!

**Comment by errogaht** [comment] 2021-05-07 11:14
And what is about this message `this attribute value will be marked as sensitive and will` appears each time when i use terraform apply? I can perform `terraform apply` 100 times without any changes and this message will be displayed for some properties each time, but actually i am not doing any changes.

**Comment by alisdair** [comment] 2021-05-07 11:57
@errogaht That doesn't sound right. If you can report this as a separate issue (with a configuration to reproduce the problem) we can look into it.

**Closed** 2021-05-18 14:49 UTC
Labels: bug, cli, confirmed, experiment/provider_sensitive_attrs, v0.15
