### ISSUE TITLE
Permission denied when running destroy but not when running apply/plan

### ISSUE THREAD

**Issue by gvcgael** [hashicorp/terraform#26719] opened 2020-10-27 16:06 UTC
### Terraform Version
0.13.4

### Expected Behavior
I should be able to call destroy the same way i call apply/plan

### Actual Behavior

When I call `terraform destroy`, I get a fork/exec permission denied on my plugins.

### Steps to Reproduce
 - Run terraform onto virtualbox, from a Shared Folder
 - Apply a plan to instanciate resources
 - Run `terraform destroy` : a fork/exec permission failure is encountered

### References
 - https://github.com/hashicorp/terraform/issues/16756 
 - https://github.com/hashicorp/terraform/issues/20500 
 - https://github.com/hashicorp/terraform/issues/15909

**Comment by alisdair** [comment] 2020-10-27 16:46
This seems like a duplicate of #26281. Unfortunately it looks like the problem is out of Terraform's control, so there isn't much we can do here except recommend _not_ using a VM-shared folder for your Terraform configuration.

The original reporter in #26281 reported success when cloning the folder into /tmp. Can you try something like that and see if it solves the problem for you?

**Comment by gvcgael** [comment] 2020-10-27 17:39
Yes, running this from the user home fixes the problem.

Still, it looks really weird, why could the behaviour differ depending on the terraform command we call ?

**Comment by alisdair** [comment] 2020-10-27 18:12
I'm really not sure! It shouldn't be possible—`apply` and `destroy` are very much overlapping in code paths, especially when it comes to interacting with providers.

As a complete guess, I'd imagine that two subsequent `apply` operations (both of which are doing something) might fail in a similar way. From what we know from previous reports, the underlying issue is related to the host OS changing permissions for the directory where plugins are executed, which may happen after the first Terraform run executes.

**Comment by alisdair** [comment] 2020-10-27 19:59
Oops, I intended to acknowledge that you're able to avoid whatever is going on here by running Terraform from another location. For now I don't think there's much more we can do from the Terraform side to fix this, so I'm going to mark this issue closed. Thanks for confirming that you have a workaround!

**Closed by alisdair** 2020-10-27 19:59 UTC
Labels: bug, new
