### ISSUE TITLE
terraform crash

### ISSUE THREAD

**Issue by cyclingwithelephants** [hashicorp/terraform#24648] opened 2020-04-13 13:18 UTC
### Terraform Version

```
Terraform v0.12.24
+ provider.aiven v1.2.3
+ provider.cloudflare v2.5.1
+ provider.google v3.16.0
+ provider.google-beta v3.16.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Crash Output

I'd prefer to send this logfile to a terraform maintainer directly.

### Actual Behavior

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by danieldreier** [comment] 2020-04-14 00:00
Hi @cyclingwithelephants! Thanks for reporting a crash. I'm happy to have you send me the `crash.log` file directly, but we also need a reproduction case. 

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). Without knowing how you got to this crash, I can't reproduce it locally. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

The ideal here would be a full reproduction case, where you provide a minimal set of terraform configs that I can run without modification on my local workstation to reproduce the crash. Ideally, you would reproduce this with the [null resource](https://www.terraform.io/docs/providers/null/resource.html) rather than real providers in order to reduce external dependencies, but I realize that isn't always feasible.

Without more detail, I will have to close this issue because as-is I just don't have enough information to fix it, even if you send me that crash log.

**Closed** 2020-04-20 08:28 UTC
Labels: waiting-response
