### ISSUE TITLE
Defining provider in module with its parameters as variables does not work

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/terraform#19532] opened 2018-12-02 22:00 UTC
When a Terraform provider has one of its parameters marked as required, it seems that even if the said parameter is injected via modules this doesn't seem to work.

For example, with a module "implementing" the Cloudflare provider and exposing the ability to create DNS records, like so:
```
# module/cloudflare-dns-record/main.tf
variable "cloudflare_account_email" {
  type = "string"
  description = "The Cloudflare account email"
}

variable "cloudflare_account_token" {
  type = "string"
  description = "The Cloudflare account token"
}

variable "cloudflare_record_domain" {
  type = "string"
  description = "The Cloudflare record domain name"
}

variable "cloudflare_record_name" {
  type = "string"
  description = "The Cloudflare record name"
}

variable "cloudflare_record_value" {
  type = "string"
  description = "The Cloudflare record value"
}

variable "cloudflare_record_type" {
  type = "string"
  description = "The Cloudflare record type"
}

variable "cloudflare_record_ttl" {
  type = "string"
  description = "The Cloudflare record TTL (defaults to 300)."
  default = "300"
}



provider "cloudflare" {
  email = "${var.cloudflare_account_email}"
  token = "${var.cloudflare_account_token}"
  version = "1.2.0"  # Note this is not parameterised on purpose as there is no ability to do so at the moment...
}

resource "cloudflare_record" "record" {
  domain = "${var.cloudflare_record_domain}"
  name = "${var.cloudflare_record_name}"
  value = "${var.cloudflare_record_value}"
  type = "${var.cloudflare_record_type}"
  ttl = "${var.cloudflare_record_ttl}"
}
```

And then a module which implements that:
```
# dns-records.tf
variable "cloudflare_account_email" {
  type = "string"
  description = "The Cloudflare account email"
}

variable "cloudflare_account_token" {
  type = "string"
  description = "The Cloudflare account token"
}

module "dns_record_application_entrypoint" {
  source = "./modules/cloudflare-dns-record"

  cloudflare_account_email = "${var.cloudflare_account_email}"
  cloudflare_account_token = "${var.cloudflare_account_token}"

  cloudflare_record_domain = "example.com"
  cloudflare_record_name = "subdomain"
  cloudflare_record_type = "A"
  cloudflare_record_value = "some_ip_address"
}
```

And a `tfvars` which define the vars' value:
```
# vars.tfvars
cloudflare_account_email = "some_email_address"
cloudflare_account_token = "a_token"
```

When running `terraform plan -var-file=vars.tfvars`, Terraform/the provider prompts for the email address, but this has been specified in `vars.tfvars` 🤔 
```
terraform plan -var-file=vars.tfvars

provider.cloudflare.email
  A registered Cloudflare email address.

  Enter a value: ^C
```

Why is that?

I noticed that with other Terraform providers whose parameters are optional (such as i.e. the Google or K8s providers) this doesn't happen.

Is it a case that this is not working *at all* and the fact that the other providers have the parameters optional is masking this making me believe this is working when in reality it's not?

Thank you. 

### Terraform Version
0.11.1

**Comment by mildwonkey** [comment] 2018-12-03 21:42
Hi @walterdolce !

I'm sorry you are experiencing an issue here. I copied the files you provided and was not able to reproduce your issue. Do my environment and directory structure match yours?

```
$ terraform version
Terraform v0.11.1
+ provider.cloudflare v1.2.0

$ tree
.
├── dns-records.tf
├── modules
│   └── cloudflare-dns-record
│       └── main.tf
└── vars.tfvars
```

At the moment there are two things I can think of that might cause an issue like what you're seeing: 
* Invalid syntax somewhere in your `vars.tfvars` file, which tends to get swallowed instead of reported as an error.
* A terraform [overrides file](https://www.terraform.io/docs/configuration/override.html) that's clobbering what you have set in `vars.tfvars` 

Is there anything else in the directory that contains your `dns-records.tf` and `vars.tfvars`? If so, it might be worthwhile for you to test out only the configuration you've shared here in case there's something else. 

If none of this applies, perhaps you could run `TF_LOG=TRACE terraform plan -var-file=vars.tfvars` and share the output (as a gist, with any sensitive information removed) here?

**Comment by apparentlymart** [comment] 2018-12-03 22:39
Since the input prompt is talking about `provider.cloudflare.email` rather than `module.dns_record_application_entrypoint.provider.cloudflare.email` this suggests that there's a Cloudfront resource in the root module and so the provider needs to be configured there instead of in the child module.

Our general recommendation for most cases is for only root modules to contain `provider` blocks and for child modules to be passed them either implicitly (by making no declarations at all and letting the default configurations inherit automatically) or explicitly (using [the `providers` meta-argument](https://www.terraform.io/docs/configuration/modules.html#providers) in the `module` block). This keeps all of the provider declarations together at the root and thus ensures that all modules can get the providers they need without needing to create a separate provider instance for each module.

**Comment by apparentlymart** [comment] 2019-06-06 16:16
Thanks for following up @walterdolce, and sorry we didn't respond here sooner.

From re-reading the discussion here, I think Terraform was working as expected but wasn't explaining itself well. The relevant messaging has changed somewhat in Terraform 0.12, so hopefully things are slightly better now. If not, we'll wait to see feedback about the new 0.12-style messages and work from there, and so I'm going to close this one out now. Thanks again!

**Closed by apparentlymart** 2019-06-06 16:16 UTC
Labels: config, question
