### ISSUE TITLE
ECS unable to assume role and validate the listeners

### ISSUE THREAD

**Issue by toddrosner** [hashicorp/terraform#4609] opened 2016-01-10 19:28 UTC
I'm getting the following error when applying a plan for ECS service:

```
Error applying plan:

1 error(s) occurred:

* aws_ecs_service.node: InvalidParameterException: Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions.
	status code: 400, request id: b0b552b3-b7cd-11e5-acef-a313e3d4fafe
```

The IAM role policy I'm using is one that's generated when setting things up through the console, so it should work.

```
resource "aws_iam_role_policy" "ecs-policy" {
  name = "ecs-policy"
  role = "${aws_iam_role.ecs-role.id}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "elasticloadbalancing:Describe*",
        "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
        "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
        "ec2:Describe*",
        "ec2:AuthorizeSecurityGroupIngress"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
EOF
}
```

It doesn't seem to matter what I do for the IAM permissions, the same error keeps happening. Is there something unique that needs to be done to make this work?

**Comment by radeksimko** [comment] 2016-01-10 21:32
Hi @toddrosner 
thanks for the report, this is (unfortunately) a known issue related to eventually-consistent IAM.
I will close this as a duplicate of https://github.com/hashicorp/terraform/issues/4375

Hopefully https://github.com/hashicorp/terraform/pull/4447 and following PRs will address this.

**Closed by radeksimko** 2016-01-10 21:32 UTC

**Comment by toddrosner** [comment] 2016-01-10 21:50
Thanks for the update @radeksimko. I'll keep an eye out for an updated solution.
