### ISSUE TITLE
Terraform state file upgrade fails when variable embedded in module provider name

### ISSUE THREAD

**Issue by eldondevat** [hashicorp/terraform#22841] opened 2019-09-18 22:08 UTC
### Terraform Version

```
Terraform v0.12.9
+ provider.aws v2.27.0
```

### Terraform Configuration Files

```variable "region" {}
 provider aws {
   alias = "aws_${var.region}"
   region = "${var.region}"
 }
variable organization_email {
  type = "list"
}
 resource "aws_guardduty_member" "member" {
  provider = "aws.aws_${var.region}"
  count = "${length(var.organization_email)}"
  account_id         = "${element(split(":", var.organization_email[count.index]), 0)}"
  detector_id        = "${aws_guardduty_detector.some_detector.id}"
  email              = "${element(split(":", var.organization_email[count.index]),1)}"
  invite             = true
  disable_email_notification = true
  invitation_message = "please accept guardduty invitation"
}

```

### Expected Behavior
Ran `terraform state pull >fixstate` and expected it to pull down a state from the (s3) statefile

### Actual Behavior
Got the following (slightly redacted) output.
Failed to refresh state: State format upgrade failed: Error upgrading state file format from version 3 to version 4: invalid provider config reference "module.guardduty-module-ap-northeast-1.provider.aws.aws_${var.region}" for aws_guardduty_member.member[274]: 2 problems:

- Invalid character: This character is not used within the language.
- Invalid character: Expected an attribute access or an index operator..

### Steps to Reproduce
1) In terraform < 0.12, create a terraform module with a variable, 
2) create a provider inside the module, and 
3) use the variable in the alias to the module.
4) Assign the provider to some resources, 
5) apply to create those resources, and
6) try to upgrade to terraform 0.12.9, or pull down the state

### Additional Context
My misdeeds amounted to creating providers in modules, because I needed a _lot_ of providers. It seemed DRYer to create the modules, and have the module create the provider. I wanted the things intelligently named, so I used the variable in the provider alias. Anyway, this did not work out so well. With 0.12.9 I can't even pull down the state to attempt surgery. I downgraded to 0.11.14, which is happy with the variable there, renamed the provider

**Comment by teamterraform** [comment] 2019-09-19 16:58
Hi @eldondevat,

Terraform 0.11 does _not_ support interpolation in the `provider` address, but it appeared to work for you because Terraform 0.11 also did not validate that the provider alias address was a valid identifier, and so it is using the literal string `aws_${var.region}` as the alias name.

Terraform 0.12 requires that provider aliases be valid identifiers, and so before upgrading you must rename the provider alias to be valid. It sounds like you already figured out that upgrade procedure, and what you did here is what [the `terraform 0.12checklist` command](https://www.terraform.io/upgrade-guides/0-12.html#pre-upgrade-checklist) in Terraform 0.11.14 would've recommended you do before upgrading.

In this case, it doesn't seem like the alias is doing anything useful: you still have only one provider configuration, so it might as well just be the default provider configuration with no alias at all. Aliases are only useful if you need more than one configuration for the same provider in the same module.

Since Terraform is working as intended here (notwithstanding a non-ideal error message that results from this error being detected during state upgrade rather than configuration parsing, because you were using a state-only command rather than a configuration-oriented command), we're going to close this out. The upgrade path described in the upgrade guide was to do this renaming prior to upgrading to Terraform 0.12, and it seems like that approach worked for you once you figured it out.

Thanks for reporting this!

**Closed by teamterraform** 2019-09-19 16:58 UTC

**Comment by eldondevat** [comment] 2019-09-19 18:59
Yes, this was 80% breadcrumbs from my experience for others who may have made similar decisions. Still, I thing failing a `state pull` is not very helpful, especially if someone needs to do state surgery (which is the most common use I have heard of `state pull`).
