### ISSUE TITLE
Untaint command not working on command line

### ISSUE THREAD

**Issue by phanindra2407** [hashicorp/terraform#16976] opened 2017-12-22 20:20 UTC
Hello @ketzacoatl  ,

 I am working with terraform 0.10.7

I am trying to untaint a null resource in my module.
My folder structure as below

Aurora-db
|
|-----aurora_db.tf
modules
|
|----aurora_db.tf

module "aurora" {
  source = "../modules/aurora_db"

}
in module i have a resource as follow

resource "null_resource"  "framework_exec" {

}
it is tainted and run everytime other resources are updated , so i wanted to untaint this resource . I used
sh "terrafor init.............."
 sh "terraform untaint -no-color -module=aurora_db null_resource.framework_exec"
sh "terraform plan ..............."
sh "terraform apply ................."

it gave me the error as

 [31mThe untaint command expects exactly one argument.[0m[0m
[31mUsage: terraform untaint [options] name

Please let me know whatcould be the issue here

**Comment by tombuildsstuff** [comment] 2018-01-03 09:11
Duplicate of #16977 - closing in favour of that issue

**Closed by tombuildsstuff** 2018-01-03 09:11 UTC
