### ISSUE TITLE
Data Source Lifecycle - Not deferring until the "apply" phase

### ISSUE THREAD

**Issue by pedrohdz** [hashicorp/terraform#28786] opened 2021-05-24 12:23 UTC
Terraform is not deferring the interpolations of the data instance attributes.

Should I not be chain the output of a data source directly into a new resource?  Perhaps I have misinterpreted the way it should work?

From the Terraform documentation under  [Data Source Lifecycle](https://www.terraform.io/docs/configuration-0-11/data-sources.html#data-source-lifecycle):

> Data instance arguments may refer to computed values, in which case the attributes of the instance itself cannot be resolved until all of its arguments are defined. In this case, refreshing the data instance will be deferred until the "apply" phase, and all interpolations of the data instance attributes will show as "computed" in the plan since the values are not yet known.

I have tested this out with a variety of versions of Terraform.  It **does seem to work** as expected with `Terraform v0.12.29`.  I was able to `plan` and `apply` cleanly with `v0.12.29`, but not with others.

### Terraform Version

This is failing across multiple versions of Terraform:

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/consul v2.12.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
```

```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/consul v2.12.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
```

```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/consul v2.12.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
```

```
Terraform v0.12.31
+ provider.consul v2.12.0
+ provider.kubernetes v2.2.0
```

### Terraform Configuration Files

```terraform
resource "kubernetes_service_account" "test" {
  metadata {
    name = "test"
  }
}

data "kubernetes_secret" "test" {
  metadata {
    name = kubernetes_service_account.test.default_secret_name
  }
}

resource "consul_acl_auth_method" "consul_server_auth_method" {
  description = "foo description"
  name = "foo-name"
  type = "kubernetes"
  config_json = jsonencode({
    CACert = "fake"
    Host = "host"
    ServiceAccountJWT = data.kubernetes_secret.test.data.token
  })
}
```

### Expected Behavior

This should just apply.

### Actual Behavior

Terraform v0.15.4
```
│ Error: One of 'config' or 'config_json' must be set
│
│   with consul_acl_auth_method.consul_server_auth_method,
│   on main.tf line 25, in resource "consul_acl_auth_method" "consul_server_auth_method":
│   25: resource "consul_acl_auth_method" "consul_server_auth_method" {
│
```

Terraform v0.14.11
```
Error: One of 'config' or 'config_json' must be set

  on main.tf line 13, in resource "consul_acl_auth_method" "consul_server_auth_method":
  13: resource "consul_acl_auth_method" "consul_server_auth_method" {
```

Terraform v0.13.7
```
Error: One of 'config' or 'config_json' must be set

  on main.tf line 13, in resource "consul_acl_auth_method" "consul_server_auth_method":
  13: resource "consul_acl_auth_method" "consul_server_auth_method" {
```

Terraform v0.12.31
```
Error: One of 'config' or 'config_json' must be set

  on main.tf line 13, in resource "consul_acl_auth_method" "consul_server_auth_method":
  13: resource "consul_acl_auth_method" "consul_server_auth_method" {
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`, also fails with `terraform plan`

### References

- [Terraform documentation Data Source Lifecycle](https://www.terraform.io/docs/configuration-0-11/data-sources.html#data-source-lifecycle)

**Comment by jbardin** [comment] 2021-05-24 13:09
Hi @pedrohdz,

Thanks for filing the issue. What you are seeing is not because the data source is failing to be deferred until apply, it is because the consul provider is failing to handle the unknown value when generating a plan. The provider appears to be using the `CustomizeDiff` to add some extra validation, but it is not checking if the value is known at that time.

Since this is not a bug in Terraform itself, I'm going to close this issue. I suggest filing a bug with the provider team in their project repository [here](https://github.com/hashicorp/terraform-provider-consul/issues).

Thanks!

**Closed by jbardin** 2021-05-24 13:09 UTC
Labels: bug, new

**Comment by pedrohdz** [comment] 2021-05-24 13:13
Thank you for taking the time to explain!  It's appreciated!

I was not sure if I should file here or in the Consul provider project.  I will open the issue there.
