### ISSUE TITLE
"Invalid provider configuration alias" error obfuscates error cause

### ISSUE THREAD

**Issue by RulerOf** [hashicorp/terraform#22243] opened 2019-07-29 19:02 UTC
### Terraform Version
```
14:35 $ terraform -v
Terraform v0.12.5
+ provider.aws v2.17.0
+ provider.template v2.1.0
```

### Terraform Configuration Files
In this case, using an invalid alias name is all that is required, a single `main.tf` like this:

```hcl
provider "aws" {
  region = "us-east-1"
  alias  = "aws.acm"
}
```

### Debug Output
Multiple debug runs against a real project give inconsistent results.

First run:
```
14:34 $ TF_LOG=DEBUG terraform init
2019/07/29 14:34:50 [INFO] Terraform version: 0.12.5  
2019/07/29 14:34:50 [INFO] Go runtime version: go1.12.7
2019/07/29 14:34:50 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2019/07/29 14:34:50 [DEBUG] Attempting to open CLI config file: /Users/andrewbobulsky/.terraformrc
2019/07/29 14:34:50 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/07/29 14:34:50 [INFO] CLI command args: []string{"init"}
Initializing modules...
2019/07/29 14:34:50 [DEBUG] Module installer: begin bq-admin
2019/07/29 14:34:50 [DEBUG] Module installer: begin dev_bq-s_com_zone
2019/07/29 14:34:50 [DEBUG] Module installer: begin poc-app-security
2019/07/29 14:34:50 [DEBUG] Module installer: begin solr4
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid provider configuration alias

An alias must be a valid name. A name must start with a letter and may contain
only letters, digits, underscores, and dashes.
```

Second run:
```
14:34 $ TF_LOG=DEBUG terraform init
2019/07/29 14:34:48 [INFO] Terraform version: 0.12.5  
2019/07/29 14:34:48 [INFO] Go runtime version: go1.12.7
2019/07/29 14:34:48 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2019/07/29 14:34:48 [DEBUG] Attempting to open CLI config file: /Users/andrewbobulsky/.terraformrc
2019/07/29 14:34:48 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/07/29 14:34:48 [INFO] CLI command args: []string{"init"}
Initializing modules...
2019/07/29 14:34:48 [DEBUG] Module installer: begin bq-admin
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid provider configuration alias

An alias must be a valid name. A name must start with a letter and may contain
only letters, digits, underscores, and dashes.
```

### Expected Behavior
Terraform should surface the line numbers where the error is occurring.

### Actual Behavior
Terraform gives a generic error and quits.

### Steps to Reproduce
Create a provider with an invalid alias like above, and then `terraform init`

### Additional Context
The error comes from [this line in the source](https://github.com/hashicorp/terraform/blob/3b49028b77b083f355166f1315f1e021d06d7f78/configs/provider.go#L48):
```golang
	Detail:   fmt.Sprintf("An alias must be a valid name. %s", badIdentifierDetail
```

...but modifying it to dump the comparator:
```golang
	Detail:   fmt.Sprintf("Alias %s: An alias must be a valid name. %s", content.Attributes["alias"], badIdentifierDetail),
```

...is enough to locate the cause of my problem:
```
$ $GOPATH/src/github.com/hashicorp/terraform/pkg/darwin_amd64/terraform init
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid provider configuration alias

Alias &{alias %!s(*hclsyntax.TemplateExpr=&{[0xc000bc8ae0] {cloudfront/cdn.tf
{16 12 332} {16 21 341}}}) cloudfront/cdn.tf:16,3-21
cloudfront/cdn.tf:16,3-8}: An alias must be a valid name. A name must start
with a letter and may contain only letters, digits, underscores, and dashes.
```

**Comment by teamterraform** [comment] 2019-07-29 21:08
Hi @RulerOf , thanks for opening this, and I'm sorry about the confusing behavior.
This is a duplicate of #20121 - terraform currently isn't including provider config source when a provider is explicitly configured. I am going to close this in favor of that issue. Thanks again!

**Closed by teamterraform** 2019-07-29 21:08 UTC
