### ISSUE TITLE
GCP reattaches network on Machine when using Lifecycle to ignore boot_disk

### ISSUE THREAD

**Issue by nealmcq** [hashicorp/terraform#17767] opened 2018-04-03 14:57 UTC
### Terraform Version

```
Terraform v0.11.5
+ provider.google v1.8.0
```

### Terraform Configuration Files

```hcl
resource "google_compute_instance" "test" {
  count                     = 1
  name                      = "test${count.index}"
  machine_type              = "f1-micro"
  zone                      = "${var.primary_zone}"
  allow_stopping_for_update = true
  description               = "test instance for Terraform code writing"
  project                   = "${var.project_id}"
  deletion_protection       = false

  lifecycle {
    ignore_changes = "boot_disk.0.initialize_params.0.image"
  }
```

### Debug Output

```bash
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.test.google_compute_instance.test
      network_interface.#:                                 "1" => "1"
      network_interface.0.access_config.#:                 "1" => "1"
      network_interface.0.access_config.0.assigned_test_ip: "x.x.x.68" => <computed>
      network_interface.0.access_config.0.test_ip:          "x.x.x.68" => <computed>
      network_interface.0.address:                         "10.128.0.3" => <computed>
      network_interface.0.name:                            "nic0" => <computed>
      network_interface.0.network:                         "https://www.googleapis.com/compute/v1/projects/pname/global/networks/network-name" => "network-name"
      network_interface.0.network_ip:                      "10.128.0.3" => <computed>
      network_interface.0.subnetwork_project:              "pname" => <computed>
```

### Expected Behavior

The plan should have shown no changes and continued ignoring the boot image param.
```hcl
  lifecycle {
    ignore_changes = "boot_disk.0.initialize_params.0.image"
  }
```

### Actual Behavior

The plan shows network updates that don't seem to have any actual change. Particularly Terraform tries to reattach the network.

This is most apparent when network_interface.0.network will reload the full API path instead of just the string of the network name.

### Steps to Reproduce

terraform init
terraform plan
terraform apply (to see the null changes)

### Additional Context

This only happens in GCP when you ignore the boot disk param in Lifecycle. If you comment out the Lifecycle block, Terraform will correctly try to replace the instance with an updated machine image.

**Comment by jbardin** [comment] 2018-04-03 20:35
Hi @nealmcq,

Sorry you're having an issue here. I don't see offhand what the problem might be, so it might be useful to get the debug logs from a plan to help narrow down what changes terraform thinks it needs to make. Could you provide a more complete configuration showing the `network_interface` and `boot_disk` configurations?

The first clue I see is that in the `network_interface` diff shown, is that the value for `network_interface.0.network` is changing.  While it might not be functionally different, sometime semantics like this are expected to be resolved by the provider, and other times the config needs to be exact. 

While I don't think its causing the issue here, you should note that the `ignore_changes` value of `boot_disk.0.initialize_params.0.image` is not supported in terraform. While it does work much of the time for now, only top level attributes are supposed to be referenced in that field, and there have been cases where it caused unexpected behavior.

**Comment by nealmcq** [comment] 2018-04-04 19:03
I follow so far. The reason we use ```ignore_changes``` on the boot_image param is because we're using a ```data``` resource lookup to find the latest image in a GCP Family. In our case, we're loading the latest Packer image automatically as the boot_image. We do not want Terraform to replace the nodes every time Packer registers a newer image that meets the same ```data``` resource into GCP, so we ignore the boot image param. This allows new nodes to run the latest image, but does not replace non-retired nodes in a Terraform Apply. Why the ``` network_interface.0.network``` keeps flipping between the full https:// and the actual string of the network is still confusing.

```
data "google_compute_image" "test-redhat-7" {
  family  = "test-redhat-7"
  project = "${var.project_id}"
}

resource "google_compute_instance" "test" {
  count                     = 2
  name                      = "test${count.index}"
  machine_type              = "g1-small"
  zone                      = "${var.primary_zone}"
  allow_stopping_for_update = true
  description               = "instance for testing"
  project                   = "${var.project_id}"
  deletion_protection       = false

  lifecycle {
    ignore_changes = "boot_disk.0.initialize_params.0.image"
  }

  //network tag
  tags = ["test", "nat-users"]

  boot_disk {
    auto_delete = true
    device_name = "test${count.index}"

    initialize_params {
      image = "${data.google_compute_image.test-redhat-7.self_link}"
      type  = "pd-ssd"
      size  = "100"
    }
  }

  network_interface {
    network = "${var.vpc_name}"
  }

  metadata {
    ssh-keys = "${var.user_ssh_keys}"
  }

  scheduling {
    preemptible         = false
    on_host_maintenance = "MIGRATE"
    automatic_restart   = true
  }
}
```

**Comment by nealmcq** [comment] 2018-04-04 19:15
Here is a good example of what we're trying to avoid in our writing. CoreOS recently put out a newer image, and there isn't a good reason to replace the entire node because CoreOS automatically patches in our case.

```
      boot_disk.0.initialize_params.0.image:               "https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-stable-1688-4-0-v20180327" => "https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-stable-1688-5-3-v20180403" (forces new resource)
```

**Comment by jbardin** [comment] 2018-04-04 20:06
@nealmcq,

That's what I expected, I just want to make the note about `ignore_changes` path in case it became a problem, and it may need to be updated in the next major release.

As for the `network_interface` diff, that looks like a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/1058

**Comment by nealmcq** [comment] 2018-04-04 20:16
Thanks for teaching on ```ignore_changes```. We'll clean that up.

After reviewing the linked Issue, I would say that is a better explanation of my core problem. 

Thanks!

**Closed** 2018-04-04 20:37 UTC
Labels: waiting-response
