### ISSUE TITLE
[v0.12.6] provider.aws v3.1.0 still shows "Invalid resource instance data in state"

### ISSUE THREAD

**Issue by hacos** [hashicorp/terraform#25827] opened 2020-08-12 18:55 UTC
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v3.1.0
+ provider.template v2.1.2
```

Note: seems like it might still be happening with Terraform v0.13.0? https://github.com/terraform-providers/terraform-provider-aws/issues/14431#issuecomment-671873293

### Terraform Configuration Files

Note: redacted for privacy purposes

```terraform
resource "aws_instance" "standard_instance" {
  count                  = var.instance_count
  ami                    = var.instance_ami
  instance_type          = var.instance_type
  vpc_security_group_ids = var.vpc_security_group_ids
  subnet_id              = var.subnet_ids[count.index % length(var.subnet_ids)]
  key_name               = var.key_name
  iam_instance_profile   = var.iam_instance_profile
  ebs_optimized          = var.ebs_optimized

  user_data = var.instance_user_data

  root_block_device {
    volume_type = var.root_volume_type
    volume_size = var.root_volume_size
    encrypted   = var.encrypted
  }

  dynamic "ebs_block_device" {
    for_each = var.ebs_devices
    content {
      device_name = ebs_block_device.value.device_name
      volume_type = ebs_block_device.value.volume_type
      volume_size = ebs_block_device.value.volume_size
      iops        = lookup(ebs_block_device.value, "iops", null)
      encrypted   = var.encrypted
    }
  }

  dynamic "ephemeral_block_device" {
    for_each = var.ephemeral_devices
    content {
      device_name  = ephemeral_block_device.value.device_name
      virtual_name = ephemeral_block_device.value.virtual_name
    }
  }

  lifecycle {
    ignore_changes = [
      user_data,
      ami,
      ebs_block_device,
      ephemeral_block_device,
      subnet_id
    ]
  }
}
```

### Debug Output

Need to review and scrub before posting

### Expected Behavior

The plan to work. It should have replaced the instance because of a new variable. Interestingly enough, if I run just `terraform plan` instead of using `-target=` the plan outputs properly. Since these aws_instances are being replaced, I'd rather not take down the entire group of them all at once, hence the `-target=` flag.

### Actual Behavior

Got an error similar to https://github.com/terraform-providers/terraform-provider-aws/issues/14431
```
Error: Invalid resource instance data in state

  on ../../../../base_modules/standard_instance/standard_instance.tf line 11:
  11: resource "aws_instance" "standard_instance" {

Instance module.REDACTED.aws_instance.standard_instance[3] data
could not be decoded from the state: unsupported attribute
"network_interface_id".
```

### Steps to Reproduce

```
terraform init
terraform plan -target=module.REDACTED.aws_instance.standard_instance[3]
```

### References

Was told by this comment to log an issue if it's still happening with Terraform v0.12.X (which I am on). https://github.com/terraform-providers/terraform-provider-aws/issues/14431#issuecomment-672947462

**Comment by danieldreier** [comment] 2020-08-12 19:02
Hi! Thanks for reporting this. Based on the error report you showed, I think this is probably a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I don't have your vars, so I'd have to invent some details. Can you please restate your reproduction case such that I can copy-paste it and run it locally? If it's easier to provide via a github repo rather than a copy-paste, you're welcome to make a PR against https://github.com/danieldreier/terraform-issue-reproductions to share it, or provide your own GH repo.

**Comment by hacos** [comment] 2020-08-12 19:47
Hi! I can try but I believe the issue isn't with the variables but with the state itself. In any case, here's the variables.tf and terraform.tfvars file:
```
variable "instance_ami" {}
variable "instance_type" {}
variable "name" {}
variable "vpc_security_group_ids" {
  type = list(string)
}
variable "subnet_ids" {
  type = list(string)
}
variable "instance_user_data" {
  default = ""
}
variable "key_name" {
}
variable "iam_instance_profile" {
  default = ""
}
variable "instance_count" {
  default = 1
}
variable "cluster_tag" {
}
variable "deployment_tag" {
}
variable "ebs_optimized" {
  default = false
}
variable "owner_tag" {
  default = "InfraShared"
}
variable "ebs_devices" {
  type    = list(map(string))
  default = []
}
variable "ephemeral_devices" {
  type    = list(map(string))
  default = []
}
variable "encrypted" {
  default = true
}
variable "root_volume_type" {
  default = "gp2"
}
variable "root_volume_size" {
  default = 64
}
variable "extra_tags" {
  type    = map(string)
  default = {}
}
```

```
instance_ami   = "REDACTED"
instance_type  = "t3.medium"
name           = "terraform-bug-25827"
key_name       = "REDACTED"
cluster_tag    = "terraform-bug"
deployment_tag = "terraform"
```

**Comment by Craigfis** [comment] 2020-08-13 17:53
I'm also hitting this error. In my case it is complaining because my state file contains the obsolete API gateway attribute "request_parameters_in_json".

**Comment by mshkrebtan** [comment] 2020-08-14 12:25
Editing the state file and removing the unsupported attributes helped me.

- Pull the state from the remote location:

   ```bash
   terraform state pull > tf-state.json
   ```
- Edit the state file: remove the unsupported attributes and **increment** the `serial` number.
- Push the state to the remote location:

   ```bash
   terraform state push tf-state.json
   ```
- Run `terraform plan` again.

**Comment by Mikescops** [comment] 2020-08-17 07:49
Scary but it works :fearful:

**Comment by mildwonkey** [comment] 2020-08-20 12:49
👋 Hi! This is a duplicate of https://github.com/hashicorp/terraform/issues/25752 - this issue will be fixed in the next terraform release. Thanks!

**Closed by mildwonkey** 2020-08-20 12:49 UTC
Labels: bug, v0.12, waiting for reproduction
