### ISSUE TITLE
diffs didn't match during apply. (bug which should be reported)

### ISSUE THREAD

**Issue by flypenguin** [hashicorp/terraform#1924] opened 2015-05-12 09:05 UTC
I just got this error message from a terraform apply run.
Here's the information I've got.

OpenStack version: Juno

Terraform file
```
# Configure the OpenStack Provider
provider "openstack" {
    user_name  = "its.me"
    tenant_name = "some-tenant"
    password  = "some-password"
    auth_url  = "http://some.url.here/v2.0"
}


#
#
# create two networks
#

# create my own network
resource "openstack_networking_network_v2" "ab_network_1" {
  name = "ab_network_1_os"
  admin_state_up = "true"
}

# create my own network
resource "openstack_networking_network_v2" "ab_network_2" {
  name = "ab_network_2_os"
  admin_state_up = "true"
}


#
#
# create subnets in the networks
#

# subnet 1 in network 1
# we NEED a subnet for a network to place instances in the network
resource "openstack_networking_subnet_v2" "ab_subnet_1" {
  network_id = "${openstack_networking_network_v2.ab_network_1.id}"
  cidr = "192.168.199.0/24"
  ip_version = 4
}


# subnet 2 in network 1
# let's create two subnets to choose between later.
resource "openstack_networking_subnet_v2" "ab_subnet_2" {
  network_id = "${openstack_networking_network_v2.ab_network_1.id}"
  cidr = "192.168.201.0/24"
  ip_version = 4
}


# subnet 3 in network 2
# let's create two subnets to choose between later.
resource "openstack_networking_subnet_v2" "ab_subnet_3" {
  network_id = "${openstack_networking_network_v2.ab_network_2.id}"
  cidr = "192.168.200.0/24"
  ip_version = 4
}


#
#
# let's create a router with interfaces to the subnets
#

# let's create a router between networks. to make this useful
# we have to add interfaces with the other resource type.
resource "openstack_networking_router_v2" "ab_router_1" {
  name = "ab_router_1_os"
  # external_gateway = "d115eff1-406f-4e99-b8e6-1b8781e0d77f"
}

# here we go with the router's interfaces.
resource "openstack_networking_router_interface_v2" "ab_router_interface_1" {
  router_id = "${openstack_networking_router_v2.ab_router_1.id}"
  subnet_id = "${openstack_networking_subnet_v2.ab_subnet_1.id}"
}
resource "openstack_networking_router_interface_v2" "ab_router_interface_2" {
  router_id = "${openstack_networking_router_v2.ab_router_1.id}"
  subnet_id = "${openstack_networking_subnet_v2.ab_subnet_2.id}"
}
resource "openstack_networking_router_interface_v2" "ab_router_interface_3" {
  router_id = "${openstack_networking_router_v2.ab_router_1.id}"
  subnet_id = "${openstack_networking_subnet_v2.ab_subnet_3.id}"
}


#
#
# create a server in random (?!?) subnet in network 1.
#

# Create a web server
resource "openstack_compute_instance_v2" "ab-test-server" {
  name = "ab-test-server-os"
  image_name = "centos66-cloudinit-puppet"
  flavor_id = "3"
  network {
    # MUST: provide a NETWORK, NOT a SUBNET.
    # QUESTION: how to control the subnet we want to go in,
    #           if the network has multiple subnets?
    uuid = "${openstack_networking_network_v2.ab_network_1.id}"
  }
  metadata {
    this = "that"
  }
  key_pair = "cmddemo"
}
```

Run output
```
tm@localhost ~/Dev/terratest » terraform apply                                                                                                                                                              1 ↵
openstack_networking_network_v2.ab_network_1: Refreshing state... (ID: 2ef66c25-980e-480b-a151-c883927b5ab6)
openstack_networking_router_v2.ab_router_1: Refreshing state... (ID: 989dbe0e-9469-4311-9628-2814a263f6a5)
openstack_compute_instance_v2.ab-test-server: Refreshing state... (ID: 20d64890-511c-4f1f-9905-503f5a15135d)
openstack_networking_subnet_v2.ab_subnet_1: Refreshing state... (ID: 1e44732b-5b5f-49a3-82c3-93b8a814b4f8)
openstack_networking_subnet_v2.ab_subnet_2: Refreshing state... (ID: f7969adb-34db-4ac7-ae2b-ac54124b3b54)
openstack_networking_router_interface_v2.ab_router_interface_1: Refreshing state... (ID: 5099af7b-0522-46cd-bc74-5a6e2c567bdf)
openstack_networking_router_interface_v2.ab_router_interface_2: Refreshing state... (ID: 0a100e5c-5f7d-4326-8555-c2345e95b271)
openstack_networking_router_interface_v2.ab_router_interface_2: Destroying...
openstack_networking_router_interface_v2.ab_router_interface_1: Destroying...
openstack_networking_network_v2.ab_network_2: Creating...
  admin_state_up: "" => "true"
  name:           "" => "ab_network_2_os"
openstack_networking_router_v2.ab_router_1: Modifying...
  admin_state_up: "true" => ""
  tenant_id:      "8d7940ddb7b8415e85563ba5559e4697" => ""
openstack_networking_network_v2.ab_network_2: Creation complete
openstack_networking_subnet_v2.ab_subnet_3: Creating...
  cidr:       "" => "192.168.200.0/24"
  ip_version: "" => "4"
  network_id: "" => "7670a221-8201-440b-ac24-b1a111926156"
openstack_networking_router_interface_v2.ab_router_interface_2: Destruction complete
openstack_networking_subnet_v2.ab_subnet_2: Destroying...
openstack_networking_router_interface_v2.ab_router_interface_1: Destruction complete
openstack_networking_subnet_v2.ab_subnet_1: Destroying...
openstack_networking_router_v2.ab_router_1: Modifications complete
openstack_networking_subnet_v2.ab_subnet_2: Destruction complete
openstack_networking_subnet_v2.ab_subnet_1: Error: 1 error(s) occurred:

* Error deleting OpenStack Neutron Subnet: Expected HTTP response code [202 204] when accessing [DELETE http://10.64.111.117:9696/v2.0/subnets/1e44732b-5b5f-49a3-82c3-93b8a814b4f8], but got 409 instead
{"NeutronError": {"message": "Unable to complete operation on subnet 1e44732b-5b5f-49a3-82c3-93b8a814b4f8. One or more ports have an IP allocation from this subnet.", "type": "SubnetInUse", "detail": ""}}
openstack_networking_router_interface_v2.ab_router_interface_1: Creating...
  router_id: "" => "989dbe0e-9469-4311-9628-2814a263f6a5"
  subnet_id: "" => "1e44732b-5b5f-49a3-82c3-93b8a814b4f8"
openstack_networking_subnet_v2.ab_subnet_3: Creation complete
openstack_networking_router_interface_v2.ab_router_interface_3: Creating...
  router_id: "" => "989dbe0e-9469-4311-9628-2814a263f6a5"
  subnet_id: "" => "0cb9c646-d8c8-4e86-83ef-4d6996574f6a"
openstack_networking_router_interface_v2.ab_router_interface_1: Creation complete
openstack_networking_router_interface_v2.ab_router_interface_3: Creation complete
Error applying plan:

3 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error deleting OpenStack Neutron Subnet: Expected HTTP response code [202 204] when accessing [DELETE http://10.64.111.117:9696/v2.0/subnets/1e44732b-5b5f-49a3-82c3-93b8a814b4f8], but got 409 instead
{"NeutronError": {"message": "Unable to complete operation on subnet 1e44732b-5b5f-49a3-82c3-93b8a814b4f8. One or more ports have an IP allocation from this subnet.", "type": "SubnetInUse", "detail": ""}}
* 1 error(s) occurred:

* openstack_networking_network_v2.ab_network_1: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* 1 error(s) occurred:

* Resource 'openstack_networking_subnet_v2.ab_subnet_2' does not have attribute 'id' for variable 'openstack_networking_subnet_v2.ab_subnet_2.id'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
tm@localhost ~/Dev/terratest »
```

**Comment by dupuy** [comment] 2015-05-18 22:18
While there may be a core Terraform issue, it is triggered by an OpenStack provider "misfeature" here.  The reported problem `openstack_networking_network_v2.ab_network_1: diffs didn't match during apply` is caused by the failure in deleting `openstack_networking_subnet_v2.ab_subnet_1`, and the reason for that is probably because your web-server compute instance is using a port (IP allocation) on the old instance of ab_subnet_1 (I expect you changed its CIDR range).  However, although the compute_instance has an implicit dependency on the ab_network_1 (based on use of `ab_network_1.id`), and ab_subnet_1 has an implicit dependency on ab_network_1 (also based on use of `ab_network_1.id`), there is *no* dependency between the compute instance and the subnet, so Terraform is free to destroy them in any order (or to not destroy the compute instance at all if the subnet changes, but not the network, as in this case).

If you add a `depends_on = ["openstack_networking_subnet_v2.ab_subnet_1", "openstack_networking_subnet_v2.ab_subnet_2"]` then Terraform will destroy the compute instance (and its possibly fixed in code/configuration IP address allocation) before destroying and re-creating the subnets, and then recreate the compute instance.  You may not be excited to have your compute instance(s) destroyed and re-created every time the IP ranges in the subnets change (especially if they have active network interface discovery and use DHCP, and would be totally fine if their IP address changed while running) but Terraform would not be wrong to force this re-creation.  If this is a problem, you could just have a dependency on one subnet, and change it to another one at the same time the subnet CIDR range changes, which *might* avoid the forced re-creation.  However, as you note, there is no way to select a particular subnet (although if you explicitly set the fixed_ip, that might do it).

The Terraform OpenStack provider requires a network ID because the OpenStack API allows a network ID for the network configuration of a compute instance, but it could be a useful improvement for the OpenStack provider to allow use of a subnet ID instead of a network ID, so that you don't need to use `depends_on`.  Perhaps @jtopjian might have some ideas about this.

**Comment by jtopjian** [comment] 2015-05-19 03:37
@dupuy Your analysis sounds correct. Unfortunately OpenStack Networking / Neutron is not my strong point -- I'm more of a nova-network kind of guy -- but I think you're correct that there should be a way to more closely tie an instance to a Neutron subnet without having to make an explicit relationship.

I can look into this when I get some time.

#1789 might also help with this, but I still think a direct relationship between instance and subnet is more intuitive.

**Comment by flypenguin** [comment] 2015-05-19 07:03
Thanks for the effort of looking into this. We were just evaluating Terraform in a protoyping-session, when I ran into this error. It said "this should be reported", so I did. I ended up deleting the whole stack and re-creating it from scratch, which also worked. From my side you can close it if you're working on a solution at another place, I have no real "stakes" in here because this is not (yet) used by us.

**Comment by jtopjian** [comment] 2016-06-30 06:11
I've just reviewed this issue and believe it's now closable. The requirement for explicitly depending on a subnet is now solvable by using the `openstack_networking_port_v2` resource.

If someone feels this is incorrect, please feel free to reopen and I'd be happy to discuss!

**Closed by jtopjian** 2016-06-30 06:11 UTC
Labels: bug, core, provider/openstack
