### ISSUE TITLE
"tomap()" shown in output values when using sort()

### ISSUE THREAD

**Issue by Geartrixy** [hashicorp/terraform#27691] opened 2021-02-05 12:44 UTC
### Terraform Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files

```terraform
locals {
    key_list = ["a", "b", "c"]
    value_list = [1,2,3]
}

output "tomap_not_showing_in_output" {
    value = zipmap(["a", "b", "c"], [1, 2, 3])
}

output "tomap_not_showing_in_output2" {
    value = zipmap(local.key_list, local.value_list)
}

output "tomap_showing_with_sort_in_output" {
    value = zipmap(sort(["a", "b", "c"]), sort([2, 1, 3]))
}

output "tomap_showing_with_sort_in_output2" {
    value = zipmap(sort(local.key_list), sort(local.value_list))
}
```

### Expected Behavior

tomap_not_showing_in_output = {
  "a" = 1
  "b" = 2
  "c" = 3
}
tomap_not_showing_in_output2 = {
  "a" = 1
  "b" = 2
  "c" = 3
}
tomap_showing_with_sort_in_output = {
  "a" = "1"
  "b" = "2"
  "c" = "3"
}
tomap_showing_with_sort_in_output2 = {
  "a" = "1"
  "b" = "2"
  "c" = "3"
}
### Actual Behavior

tomap_not_showing_in_output = {
  "a" = 1
  "b" = 2
  "c" = 3
}
tomap_not_showing_in_output2 = {
  "a" = 1
  "b" = 2
  "c" = 3
}
tomap_showing_with_sort_in_output = tomap({
  "a" = "1"
  "b" = "2"
  "c" = "3"
})
tomap_showing_with_sort_in_output2 = tomap({
  "a" = "1"
  "b" = "2"
  "c" = "3"
})

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by Geartrixy** [comment] 2021-02-05 13:22
Also appears in output with the tomap function

```
output "tomap_shown_in_output" {
    value = tomap({a=1, b=2})
}
```

Behaviour:
```
tomap_shown_in_output= tomap({
  "a" = 1
  "b" = 2
})
```

**Comment by jbardin** [comment] 2021-02-05 13:34
Thanks @Geartrixy 

Duplicate of #27551

**Closed by jbardin** 2021-02-05 13:34 UTC
Labels: bug, new
