### ISSUE TITLE
Error: Unassigned variable

### ISSUE THREAD

**Issue by Meemaw** [hashicorp/terraform#21659] opened 2019-06-08 20:35 UTC
Hi, I'm trying to run atlantis on AWS Fragate through https://github.com/terraform-aws-modules/terraform-aws-atlantis.

I've set up everything but am getting a wierd error. I am fairly sure that the variables are set through environment.

### Crash Output
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/meshwatch/infrastructure/terraform-gsuite/1/default/default.tfplan\"" in "/home/atlantis/.atlantis/repos/meshwatch/infrastructure/terraform-gsuite/1/default": exit status 1

Error: Unassigned variable

The input variable "access_key" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.


Error: Unassigned variable

The input variable "secret_key" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.


Error: Unassigned variable

The input variable "region" has not been assigned a value. This is a bug in
Terraform; please report it in a GitHub issue.
```

**Comment by HammoTime** [comment] 2019-06-10 04:25
Meemaw, this error generally happens when `-input=false` and there are no values for those variables. To troubleshoot, try removing the `-input=false`. If you're prompted for variables, then the variables aren't set correctly.

Can you also do the following:
`echo $TF_VAR_access_key`
`echo $TF_VAR_secret_key`
`echo $TF_VAR_region`.

Please also note that you need to set these variables in addition to any credentials used by Terraform and if they are set as environment variables, they need to be prepended with `$TF_VAR_`.

**Comment by tamccall** [comment] 2019-06-10 13:19
I believe i was also seeing this issue after upgrading terraform to 0.12.

Here is the travis build where we began seeing the errors in our acceptance tests. https://travis-ci.org/nukosuke/terraform-provider-zendesk/jobs/537885423

Diff is here. https://github.com/nukosuke/terraform-provider-zendesk/compare/c417e18b351b...efe81265c25d.

**Comment by jbardin** [comment] 2019-06-11 14:43
HI @Meemaw,

All variables require value, either provided via a default, the cli, a tfvars file, or interactively. If there's no value provided, and you are using `-input=false`, there is no way to set a value for the variable, and you will see the error shown.

**Comment by tamccall** [comment] 2019-06-11 22:48
@jbardin if you look at the build link above you can see that the environment variables being passed to terraform an I can confirm that this only occurs after upgrading to 0.12

**Comment by apparentlymart** [comment] 2019-06-11 22:55
While it's true that all variables do need to be assigned, this error is reporting that variable values are not being passed properly around inside Terraform Core itself. IIRC it arises when `terraform.NewContext` is called without a full complement of variables, because it expects that the frontend code in the `command` package is responsible for properly loading, validating, and preparing variables.

The message suggests that there's a bug in the variable-checking and/or variable-handling code in either the `command` package or in `backend/local`.

**Comment by jbardin** [comment] 2019-06-12 00:47
Hi @tamccall,

Sorry, I didn't see your addition here for some reason. The original error here looks like variables missing from the config or cli, while yours is coming from the plugin test fixture. I that may be more closely related to the issue about `TF_VAR_` variables used in the provider tests here: #21162

**Comment by tamccall** [comment] 2019-06-12 01:17
@jbardin Ill add my links over to that ticket as well since i am passing the variables to terraform via environment variables.

**Comment by CoreyMcDonald** [comment] 2019-07-18 18:57
Experiencing this issue as well - Terraform v0.12.3 + provider.aws v2.19.0. also using Terraform Enterprise.

I have defined access_key and secret_access key within my workspace from the gui. When I call my module, I have a backend.tf file that contains the following -

`terraform {
  backend "remote" {
    hostname     = "ptfe-path"
    organization = "orgname"

    workspaces {
      name = "workspacename"
    }
  }
}

provider "aws" {
  version = "2.16.0"
  region  = "us-east-1"
  access_key = var.access_key
  secret_key = var.secret_key
  }`

**Comment by tibers** [comment] 2019-08-06 19:36
I came here through google, I am having the same problem. I have a key I've generated for an application which has all sorts of fun chars like ( + ] and so on and terraform has been throwing this error. I'm not sure if the contents of the var are related to this problem but it sounds like something is choking along those lines as TF is fine with the rest of my vars.

**Comment by kassyuz** [comment] 2019-08-07 20:59
I do not know if it is related to this bug, but anyway, this is my case:

I have a variable defined as:
```
# var labels
variable "label_inputs" {
  description = "List of label to be used in your module (e.g `name`, `namespace`, `environment`, `team` and `tags` [Tags e.g. `{BusinessUnit = 'XYZ'}`])"

  type = object({
    name        = string
    namespace   = string
    team        = string
    environment = string
    delimiter   = string
    tags        = map(string)
  })
}
```

On my `terraform.tfvars` I am passing some values to my `label_inputs` like this:
```
region = "us-east-1"
label_inputs = {
  name        = "logs"
  namespace   = "test"
  team        = "SRE"
  environment = "prod"
  delimiter   = "."
  tags        = {}
}
```
and I am trying to use those values in my `main.tf`, which is defined as:

```
module "label" {
  source = "../aws/label/"

  name        = var.label_inputs.name
  namespace   = var.label_inputs.namespace
  team        = var.label_inputs.team
  environment = var.label_inputs.environment
  delimiter   = var.label_inputs.delimiter
  tags        = var.label_inputs.tags
}
```

on that scenario when I run `terraform plan` the output is:

```
Terraform has been successfully initialized!
 
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
 
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
 
Error: Unassigned variable
 
The input variable "label_inputs" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.
 
Error: The command exited with status 1
```


Terraform version: 0.12.5

Any clue if is it related or should I convert it to a ticket?

**Comment by nick4fake** [comment] 2019-08-12 14:29
We have the same issue with TF 0.12.6. Terraform ignores TF_VAR_whatever

**Comment by v6** [comment] 2019-08-13 21:22
I'm seeing this, too. 

```
$ ls | grep vars
terraform.auto.tfvars
$ ./terraform plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/DoU-TFE/nathan-ptfe-demo/runs/run-zVESqbDinZDqyhpG

Waiting for the plan to start...

Terraform v0.12.6
Configuring remote state backend...
Initializing Terraform configuration...
2019/08/13 21:16:12 [DEBUG] Using modified User-Agent: Terraform/0.12.6 TFE/5abd315

Error: Unassigned variable

The input variable "aws_region" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.
```

**Comment by v6** [comment] 2019-08-13 21:24
After I add the aws_region variable, and set it to `us-west-2`, I get this: 

```
$ ./terraform plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/DoU-TFE/nathan-ptfe-demo/runs/run-VWoM6ZRmv6LJUQPe

Waiting for the plan to start...

Terraform v0.12.6
Configuring remote state backend...
Initializing Terraform configuration...
2019/08/13 21:19:36 [DEBUG] Using modified User-Agent: Terraform/0.12.6 TFE/5abd315
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider

  on main.tf line 5, in provider "aws":
   5: provider "aws" {
```

**Comment by ryanmaclean** [comment] 2019-09-17 18:12
Just to chime in here, I ran into this error in Azure DevOps with ver. 0.12.8 when I was defining vars via: 
 - `TF_ENV-var` - unassigned (still not working, no root cause found as of yet) 
 - `-var 'variable=value'` - assigned, but not defined

For the second case, it seems the docs (https://www.terraform.io/docs/commands/plan.html) mind need a hand? I was able to get around this by defining them like so: `-var variable='value'`

Specific to Azure DevOps, if anyone's in the same boat: `-var variable=$(VARIABLE)` is what solved it. 

One of the issues I had in troubleshooting was color mode (which I love!) but which was messing a bit with the output: 

```
A variable named &quot;&#x27;variable&quot; was assigned on the command line, but the‌
root module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration.
```

Whereas once I started planning with `-no-color` added as an optional command line argument with the Microsoft-supplied Terraform plugin, all became clear:

```
Error: Value for undeclared variable

A variable named "'variable" was assigned on the command line, but the
root module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration.
```

**Comment by ferdinandosimonetti** [comment] 2019-10-04 13:32
> So there seem to be some pretty big changes to the `remote` backend post HashiConf 2019 that I'll need to work through. But the simple fix for most people in similar scenarios should be changing `terraform.tfvars` to `terraform.auto.tfvars`, or just setting them manually in the Terraform Cloud console. Hopefully this helps other people.
> 
> **UPDATE**
> So I changed my execution mode in TF Cloud for this scope to run locally instead of remote, and 🎉🎉🎉! Fixed all my problems. These changes caught me off guard, so hopefully more people are paying better attention than I am to the HC2019 announcements.
> 
> Just keep in mind -- it seems if you’re using the new TF Cloud free tier and `init` a _new remote backend_, it will default the workspace to use `remote` instead of `local` (but prior existing workspaces are still set to `local`)

You, sir, just saved my day. Thanks (a whole lot of) from Italy. Should you ever come near Genoa, ping me and you'll gain a beer.

**Comment by teamterraform** [comment] 2019-10-07 17:54
Hi all!

Reviewing the discussion here, it seems like there are several different issues all being reported together here.

We're treating this issue as being specifically about the error message covered in the original comment:

```
The input variable "example" has not been assigned a value. This is a bug
in Terraform; please report it in a GitHub issue.
```

If you are having other issues, please check if there's another issue for them already and if not please do feel free to open a new issue. For Terraform Cloud issues in particular it's important to separate them because they will likely be fixed in a different codebase (for Terraform Cloud) and so cannot be resolved along with the bug this issue is about, which is a Terraform CLI bug.

Thanks!

**Comment by apparentlymart** [comment] 2019-10-07 22:53
From my initial investigation here, I've learned that this error arises when input is disabled with `-input=false` or with the equivalent environment variable.

In that case, the processing doesn't happen in quite the right order right now: the initial validation of the variables happens prior to the input step, and it tolerates missing variables on the assumption that the input step will populate them. But when input is then disabled there's no final step to actually check that everything is correct, so it falls through into the internal safety check that is producing the "has not been assigned a value" error message.

Fixing this will require reordering these steps slightly so that the validation step can happen after the (optional) input step to make sure that everything has been populated one way or another before we pass the final set of variables in to the core part of Terraform.

**Comment by binarymist** [comment] 2019-10-08 10:17
New workspaces in Terraform Cloud defaulting to an Execution Mode of Remote cost several hours. Thanks for the pointer @jrsdav

**Closed** 2019-10-10 17:07 UTC
Labels: bug, cli, v0.12

**Comment by apparentlymart** [comment] 2019-10-10 17:12
Hi all!

Terraform 0.12.11 will contain a fix to properly catch this problem (required variables not set but `-input=false` so can't prompt) and return a proper error message for it:

```
Error: No value for required variable

The root module input variable "example" is not set, and has no default value. Use a -var
or -var-file command line argument to provide a value for this variable.
```

If you find that you are seeing the above message in cases where the variable in question _is_ set, please do open a new issue for that and we can investigate what else is going on. There were a lot of different various problems reported in the comments above, so splitting each of them into a separate issue is a better way to give us room to discuss and debug each one separately and figure out what's going on, particularly since some of them seem to be Terraform Cloud issues rather than Terraform CLI issues and would thus require solutions in a different place.
