### ISSUE TITLE
CI Unable to unzip terraform_0.11.14_linux_amd64.zip 

### ISSUE THREAD

**Issue by wviana** [hashicorp/terraform#27869] opened 2021-02-22 17:36 UTC
Hi there, 

Today my CI had broken, I was checking why, and there is an error when trying to unzip terraform. 

The CI runs the follow:

```shell
#!/bin/bash -eo pipefail
FILE=terraform
if [ -f "$FILE" ]; then
    echo "$FILE terraform is cached"
else
    curl https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip -o terraform_0.11.14_linux_amd64.zip
    unzip terraform_0.11.14_linux_amd64.zip && rm terraform_0.11.14_linux_amd64.zip
    chmod +x terraform
fi
```

And I'm getting the follow error

```
Archive:  terraform_0.11.14_linux_amd64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of terraform_0.11.14_linux_amd64.zip or
        terraform_0.11.14_linux_amd64.zip.zip, and cannot find terraform_0.11.14_linux_amd64.zip.ZIP, period.
```

Did something change the file? I've tried to reproduce on my computer, got the same error when trying to unzip.
I'm sure it was working til Friday. Not sure which day after it broke.

**Comment by MehdiZonjy** [comment] 2021-02-22 17:40
Same problem with [0.13.4](https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip).  it seems published pre-built binaries [here](https://releases.hashicorp.com/terraform/) are impacted

**Comment by wviana** [comment] 2021-02-22 17:52
Just tried again, not it worked to unzip. 
Now I'm getting the same error as reported in https://github.com/hashicorp/terraform/issues/27870

**Comment by danieldreier** [comment] 2021-02-22 17:55
Hi! There is an ongoing outage impacting releases.hashicorp.com and registry downloads. I suspect that it is the root cause of what you're seeing - it's the same 403 error other folks have reported. Engineers have a good understanding of what happened and are working on a fix. The best option for you is probably to wait for engineers on our side to fix this.

**Comment by wviana** [comment] 2021-02-22 18:03
![image](https://user-images.githubusercontent.com/1062631/108749826-0bf56680-751f-11eb-9cd2-4e268d5a18e9.png)
Just tried again,
Looks like fixed

**Comment by danieldreier** [comment] 2021-02-22 18:07
Hi! I really appreciate everyone reporting this. The root cause here is an incident in the releases.hashicorp.com and registry infrastructure. I'm going to close this and related issues and consolidate any ongoing discussion into https://github.com/hashicorp/terraform/issues/27872. Please do let us know in that issue if you are still having trouble downloading Terraform or providers.

**Closed by danieldreier** 2021-02-22 18:07 UTC
Labels: bug, new
