### ISSUE TITLE
terraform on apply for application gateway using ssl cert see Call to function "file" failed: contents of test.pfx are not valid UTF-8; use the filebase64 function to obtain the Base64 encoded contents or the other file functions (e.g. filemd5, filesha256) to obtain file hashing results instead. 

### ISSUE THREAD

**Issue by srusru** [hashicorp/terraform#24625] opened 2020-04-09 21:37 UTC
HI,
provider "azurerm" {
version = ">=1.13"
features {}
}

resource "azurerm_resource_group" "appgw-prod-rg" {
name = var.resource_group_name
location = var.resource_group_location
}
resource "azurerm_public_ip" "pip" {
name = var.gateway_public_ip_name
location = var.resource_group_location
resource_group_name = var.resource_group_name
allocation_method = "Dynamic"
domain_name_label = var.domain_name_label

}

resource "azurerm_application_gateway" "network" {
name = var.gateway_name
resource_group_name = var.resource_group_name
location = var.resource_group_location

sku {
name = "Standard_v2"
tier = "Standard_v2"
capacity = 2
}

gateway_ip_configuration {
name = "${var.gateway_name}-ip-configuration"
subnet_id = "####/subnets/ag-test-eus-subnet"
}

ssl_certificate {
name = var.ssh_cert_name
data = "${base64encode(file("test.pfx"))}"
password = var.ssh_cert_passwd
}

frontend_port {
name = "${var.gateway_name}-feport"
port = 443
}

frontend_ip_configuration {
name = "${var.gateway_name}-feip"
public_ip_address_id = "${azurerm_public_ip.pip.id}"
}

backend_address_pool {
name = "${var.gateway_name}-beap"
}

backend_http_settings {
name = "${var.gateway_name}-be-htst"
cookie_based_affinity = "Disabled"
port = 80
protocol = "Http"
request_timeout = 30
}

http_listener {
name = "${var.gateway_name}-httplstn"
frontend_ip_configuration_name = "${var.gateway_name}-feip"
frontend_port_name = "${var.gateway_name}-feport"
protocol = "Https"
ssl_certificate_name = var.ssh_cert_name
}

request_routing_rule {
name = "${var.gateway_name}-rqrt"
rule_type = "Basic"
http_listener_name = "${var.gateway_name}-httplstn"
backend_address_pool_name = "${var.gateway_name}-beap"
backend_http_settings_name = "${var.gateway_name}-be-htst"
}

depends_on = ["azurerm_resource_group.appgw-prod-rg"]
}

I am using λ terraform --version
Terraform v0.12.24

provider.azurerm v2.5.0
when i apply the terraform script i see
on gateway.tf line 43, in resource "azurerm_application_gateway" "network":
43: data = "${base64encode(file("test.pfx"))}"

Call to function "file" failed: contents of test.pfx are not valid UTF-8;
use the filebase64 function to obtain the Base64 encoded contents or the other
file functions (e.g. filemd5, filesha256) to obtain file hashing results
instead.

**Comment by danieldreier** [comment] 2020-04-09 23:20
Hi!

Thanks for reporting this issue with us. I'm closing this issue because it doesn't follow the issue template we provide. Your next step here is to re-open the issue using the provided template.

We provide issue templates because it significantly reduces the amount of work to reproduce the issue and provide assistance when that information is provided in the format we ask for it. This issue is hard to work on, because it doesn't follow that template. 

Beyond the template, it would help if you could make the following improvements to your issue:

- use a short issue description as a title
- use GitHub's [text formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax). You can do `markdown` and code formatting to make your code easier to read, which makes it easier for us to understand the issue. Please use markdown to format terraform code like this:
```HCL
resource "null_resource" "example" {
  name = "hello-world"
}
```
You should also format terminal output for readability, like:
```shellsession
❯ terraform validate
Success! The configuration is valid.
```
- please provide all of the files involved in reproducing your example. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior. In this case, I don't know what the contents of `test.pfx` and so I can't reproduce this locally.

**Closed by danieldreier** 2020-04-09 23:20 UTC
