### ISSUE TITLE
Resource destroy ordering differs to create_before_destroy

### ISSUE THREAD

**Issue by garbetjie** [hashicorp/terraform#21766] opened 2019-06-18 05:30 UTC
Please forgive me if this actually belongs with the `google` provider itself - I'm not 100% sure what the providers are responsible for, and what Terraform core is responsible for.

### Terraform Version

```
Terraform v0.12.2
+ provider.google v2.8.0
```

### Terraform Configuration Files

https://gist.github.com/garbetjie/870433cc13f409a26b0e3950564faa9c

### Debug Output

https://gist.github.com/garbetjie/870433cc13f409a26b0e3950564faa9c#file-output-log (It's not debug output, but it illustrates the bug being reported)

### Expected Behavior

Similar to what happens when recreating a resource, I would have expected the `google_compute_url_map` to be updated before the `google_compute_backend_service` resources is deleted.

### Actual Behavior

Both the `google_compute_backend_service` and `google_compute_url_map` are deleted & updated at the same time, which results in an API error, and requiring an additional plan & run.

### Steps to Reproduce

All steps & files required to reproduce can be found in the gist: https://gist.github.com/garbetjie/870433cc13f409a26b0e3950564faa9c#file-readme-md

### Additional Context

None

### References

None that I'm aware of.

**Comment by phinze** [comment] 2019-06-25 15:24
Thanks for this report. We're going to treat this as a duplicate of #21871 as the tracking issue for `create_before_destroy` bugfix efforts so merging this issue in with that one.

**Closed** 2019-06-25 15:24 UTC
