### ISSUE TITLE
plugin_cache_dir not working

### ISSUE THREAD

**Issue by sdwru** [hashicorp/terraform#24836] opened 2020-05-02 22:10 UTC
v0.12.24 on CE8

/root/.terraformrc
```bash
plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"
disable_checkpoint = true
```
#### Expected behaviour
According to the docs, on the first `terraform init` it should create /root/.terraform.d/plugin-cache/linux_amd64/terraform-provider-vultr_v1.1.5_x4 or whatever provider you are using in your *.tf files. It should also copy the file to the working directory.  In this example that was `/usr/src/learn-terravorm/ws1`

After that, according to the docs, it should only create a symlink of the file in any new working directories so you do not end up with multiple copies of the same provider file.  In this example that second working directory is `/usr/src/learn-terravorm/ws2`.  

However, it still downloads the file and places a new copy in the working directory even though, according to the following debug info, it definitely sees the file in the cache directory.  So the `plugin_cache_dir` feature does not seem to accomplish anything other than creating the cache folder and file.
```
/usr/src/learn-terraform/ws2/terraform init
2020/05/02 14:56:49 [INFO] Terraform version: 0.12.24
2020/05/02 14:56:49 [INFO] Go runtime version: go1.12.13
2020/05/02 14:56:49 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/05/02 14:56:49 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2020/05/02 14:56:49 Loading CLI configuration from /root/.terraformrc
2020/05/02 14:56:49 [INFO] CLI command args: []string{"init"}
Initializing modules...
2020/05/02 14:56:49 [INFO] Checkpoint disabled. Not running.
2020/05/02 14:56:49 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2020/05/02 14:56:49 [DEBUG] Module installer: begin vultr
2020/05/02 14:56:49 [TRACE] ModuleInstaller: Module installer: vultr <nil> already installed in .terraform/modules/vultr
2020/05/02 14:56:49 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Initializing the backend...
2020/05/02 14:56:49 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/05/02 14:56:49 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/05/02 14:56:49 [DEBUG] New state was assigned lineage "a34f0bdf-d984-ffec-80c6-e319561d3eeb"
2020/05/02 14:56:49 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/05/02 14:56:49 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/05/02 14:56:49 [DEBUG] checking for provider in "."
2020/05/02 14:56:49 [DEBUG] checking for provider in "/usr/local/bin"
2020/05/02 14:56:49 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/05/02 14:56:49 [DEBUG] checking for provisioner in "."
2020/05/02 14:56:49 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/05/02 14:56:49 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2020/05/02 14:56:49 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2020/05/02 14:56:49 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/05/02 14:56:49 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/05/02 14:56:49 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/05/02 14:56:49 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/05/02 14:56:49 [TRACE] statemgr.Filesystem: read nil snapshot
2020/05/02 14:56:49 [DEBUG] checking for provider in "."
2020/05/02 14:56:49 [DEBUG] checking for provider in "/usr/local/bin"
2020/05/02 14:56:49 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/05/02 14:56:49 [DEBUG] plugin requirements: "vultr"=""

Initializing provider plugins...
- Checking for available provider plugins...
2020/05/02 14:56:49 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/05/02 14:56:49 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2020/05/02 14:56:50 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/vultr/versions"
2020/05/02 14:56:50 [DEBUG] GET https://registry.terraform.io/v1/providers/-/vultr/versions
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/vultr/versions
2020/05/02 14:56:50 [DEBUG] fetching provider location from "https://registry.terraform.io/v1/providers/terraform-providers/vultr/1.1.5/download/linux/amd64"
2020/05/02 14:56:50 [DEBUG] GET https://registry.terraform.io/v1/providers/terraform-providers/vultr/1.1.5/download/linux/amd64
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/terraform-providers/vultr/1.1.5/download/linux/amd64
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-vultr/1.1.5/terraform-provider-vultr_1.1.5_SHA256SUMS
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-vultr/1.1.5/terraform-provider-vultr_1.1.5_SHA256SUMS.sig
2020/05/02 14:56:50 [DEBUG] verified GPG signature with key from HashiCorp Security <security@hashicorp.com>
2020/05/02 14:56:50 [DEBUG] getting provider "vultr" (terraform-providers/vultr) version "1.1.5"
2020/05/02 14:56:50 [DEBUG] looking for provider vultr 1.1.5 in plugin cache
2020/05/02 14:56:50 [DEBUG] checking for provider in "/root/.terraform.d/plugin-cache/linux_amd64"
2020/05/02 14:56:50 [DEBUG] found provider "terraform-provider-vultr_v1.1.5_x4"
2020/05/02 14:56:50 [DEBUG] installing vultr 1.1.5 to .terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4 from local cache /root/.terraform.d/plugin-cache/linux_amd64/terraform-provider-vultr_v1.1.5_x4
2020/05/02 14:56:50 [DEBUG] looking for the vultr 1.1.5 plugin we just installed
2020/05/02 14:56:50 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/05/02 14:56:50 [DEBUG] found provider "terraform-provider-vultr_v1.1.5_x4"
2020/05/02 14:56:50 [DEBUG] all plugins found discovery.PluginMetaSet{discovery.PluginMeta{Name:"vultr", Version:"1.1.5", Path:"/usr/src/learn-terraform/ws2/.terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4"}:struct {}{}}
2020/05/02 14:56:50 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"vultr", Version:"1.1.5", Path:"/usr/src/learn-terraform/ws2/.terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4"}:struct {}{}}
2020/05/02 14:56:50 [DEBUG] checking for provider in "."
2020/05/02 14:56:50 [DEBUG] checking for provider in "/usr/local/bin"
2020/05/02 14:56:50 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/05/02 14:56:50 [DEBUG] found provider "terraform-provider-vultr_v1.1.5_x4"
2020/05/02 14:56:50 [DEBUG] found valid plugin: "vultr", "1.1.5", "/usr/src/learn-terraform/ws2/.terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4"
- Downloading plugin for provider "vultr" (terraform-providers/vultr) 1.1.5..
```

**Comment by matthewmf** [comment] 2020-05-04 09:54
I have also noticed the same behavior. I have also found that master does not respect the locally stored providers in any of the following locations:

- terraform.d/plugins/<OS>_<ARCH> 
- Same location as the Terraform binary 
- Manually placed in .terraform/plugins/<OS>_<ARCH> before _init_ is ran
- plugin-dir=<PATH> [OPs issue]

...it instead goes straight to the Terraform registry.

**Comment by shoekstra** [comment] 2020-05-05 14:29
> I have noticed the same behaviour. I have also found that master does not respect the locally stored providers in any of the following locations:
> 
> * terraform.d/plugins/_
> * Same location as the Terraform binary
> * Manually placed in .terraform/plugins/_ before _init_ is ran
> * plugin-dir= [OPs issue]
> 
> ...it instead goes straight to the Terraform registry.

Not sure if this should be moved to separate issue but thought I'd tag onto your comment...

I'm in also a position where current master does not find a custom provider in `terraform.d/plugins/linux_amd64` or `~/.terraform.d/plugins/linux_amd64`; running `TF_LOG=trace terraform init` shows it will search those directories but then attempts to fetch the provider from the provider registry and fails to find it.

**Comment by apparentlymart** [comment] 2020-05-13 02:53
Hi all,

Let's focus on the 0.12 behavior for this bug, because the provider installation behavior is intentionally changed for 0.13 (to support installation of third-party providers) and the documentation for that is still in progress so I can't easily link you to the information about what behavior is expected there yet. (That should follow the next few weeks.)

---

Regarding the 0.12 behavior reported in the issue, the log looks like it's doing the right thing to me, albeit with some unclear messaging.

First, it asks the Terraform registry which versions are available for this provider so that it can choose the latest version matching the constraints given in the configuration:

```
2020/05/02 14:56:50 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/vultr/versions"
2020/05/02 14:56:50 [DEBUG] GET https://registry.terraform.io/v1/providers/-/vultr/versions
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/vultr/versions
```

Next, it selects version 1.1.5 as latest and downloads the `SHA256SUMS` file containing the _checksums_ for that release:

```
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/terraform-providers/vultr/1.1.5/download/linux/amd64
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-vultr/1.1.5/terraform-provider-vultr_1.1.5_SHA256SUMS
2020/05/02 14:56:50 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-vultr/1.1.5/terraform-provider-vultr_1.1.5_SHA256SUMS.sig
2020/05/02 14:56:50 [DEBUG] verified GPG signature with key from HashiCorp Security <security@hashicorp.com>
```

Now it's chosen a version and got all of the metadata for that version, it looks into the cache to see if there's a copy of that version already available:

```
2020/05/02 14:56:50 [DEBUG] getting provider "vultr" (terraform-providers/vultr) version "1.1.5"
2020/05/02 14:56:50 [DEBUG] looking for provider vultr 1.1.5 in plugin cache
2020/05/02 14:56:50 [DEBUG] checking for provider in "/root/.terraform.d/plugin-cache/linux_amd64"
2020/05/02 14:56:50 [DEBUG] found provider "terraform-provider-vultr_v1.1.5_x4"
```

It was present in the cache, so it links from the existing copy rather than downloading it from upstream again:

```
2020/05/02 14:56:50 [DEBUG] installing vultr 1.1.5 to .terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4 from local cache /root/.terraform.d/plugin-cache/linux_amd64/terraform-provider-vultr_v1.1.5_x4
```

Finally, it checks to make sure that the installation process (which in this case was just creating a link to an existing local file) produced a discoverable provider plugin in the local directory:

```
2020/05/02 14:56:50 [DEBUG] looking for the vultr 1.1.5 plugin we just installed
2020/05/02 14:56:50 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/05/02 14:56:50 [DEBUG] found provider "terraform-provider-vultr_v1.1.5_x4"
2020/05/02 14:56:50 [DEBUG] all plugins found discovery.PluginMetaSet{discovery.PluginMeta{Name:"vultr", Version:"1.1.5", Path:"/usr/src/learn-terraform/ws2/.terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4"}:struct {}{}}
2020/05/02 14:56:50 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"vultr", Version:"1.1.5", Path:"/usr/src/learn-terraform/ws2/.terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4"}:struct {}{}}
2020/05/02 14:56:50 [DEBUG] checking for provider in "."
2020/05/02 14:56:50 [DEBUG] checking for provider in "/usr/local/bin"
2020/05/02 14:56:50 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/05/02 14:56:50 [DEBUG] found provider "terraform-provider-vultr_v1.1.5_x4"
2020/05/02 14:56:50 [DEBUG] found valid plugin: "vultr", "1.1.5", "/usr/src/learn-terraform/ws2/.terraform/plugins/linux_amd64/terraform-provider-vultr_v1.1.5_x4"
- Downloading plugin for provider "vultr" (terraform-providers/vultr) 1.1.5..
```

I would agree that the log messaging here is not super clear, particularly because the registry API endpoint Terraform has to call to get the location of the checksums file is called "download", which perhaps made you think that was downloading the plugin itself. If you look at that URL you'll see that it's just some JSON metadata, actually:

```json
{
    "protocols": ["4.0", "5.0"],
    "os": "linux",
    "arch": "amd64",
    "filename": "terraform-provider-vultr_1.1.5_linux_amd64.zip",
    "download_url": "https://releases.hashicorp.com/terraform-provider-vultr/1.1.5/terraform-provider-vultr_1.1.5_linux_amd64.zip",
    "shasums_url": "https://releases.hashicorp.com/terraform-provider-vultr/1.1.5/terraform-provider-vultr_1.1.5_SHA256SUMS",
    "shasums_signature_url": "https://releases.hashicorp.com/terraform-provider-vultr/1.1.5/terraform-provider-vultr_1.1.5_SHA256SUMS.sig",
    "shasum": "ff2b809612ed46f8bdf106c061d77a867be9d4151bed53e30b152e38f4a82fc6",
    "signing_keys": {
        "gpg_public_keys": [{
            "key_id": "51852D87348FFC4C",
            "ascii_armor": "-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: GnuPG v1\n\nmQENBFMORM0BCADBRyKO1MhCirazOSVwcfTr1xUxjPvfxD3hjUwHtjsOy/bT6p9f\nW2mRPfwnq2JB5As+paL3UGDsSRDnK9KAxQb0NNF4+eVhr/EJ18s3wwXXDMjpIifq\nfIm2WyH3G+aRLTLPIpscUNKDyxFOUbsmgXAmJ46Re1fn8uKxKRHbfa39aeuEYWFA\n3drdL1WoUngvED7f+RnKBK2G6ZEpO+LDovQk19xGjiMTtPJrjMjZJ3QXqPvx5wca\nKSZLr4lMTuoTI/ZXyZy5bD4tShiZz6KcyX27cD70q2iRcEZ0poLKHyEIDAi3TM5k\nSwbbWBFd5RNPOR0qzrb/0p9ksKK48IIfH2FvABEBAAG0K0hhc2hpQ29ycCBTZWN1\ncml0eSA8c2VjdXJpdHlAaGFzaGljb3JwLmNvbT6JATgEEwECACIFAlMORM0CGwMG\nCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEFGFLYc0j/xMyWIIAIPhcVqiQ59n\nJc07gjUX0SWBJAxEG1lKxfzS4Xp+57h2xxTpdotGQ1fZwsihaIqow337YHQI3q0i\nSqV534Ms+j/tU7X8sq11xFJIeEVG8PASRCwmryUwghFKPlHETQ8jJ+Y8+1asRydi\npsP3B/5Mjhqv/uOK+Vy3zAyIpyDOMtIpOVfjSpCplVRdtSTFWBu9Em7j5I2HMn1w\nsJZnJgXKpybpibGiiTtmnFLOwibmprSu04rsnP4ncdC2XRD4wIjoyA+4PKgX3sCO\nklEzKryWYBmLkJOMDdo52LttP3279s7XrkLEE7ia0fXa2c12EQ0f0DQ1tGUvyVEW\nWmJVccm5bq25AQ0EUw5EzQEIANaPUY04/g7AmYkOMjaCZ6iTp9hB5Rsj/4ee/ln9\nwArzRO9+3eejLWh53FoN1rO+su7tiXJA5YAzVy6tuolrqjM8DBztPxdLBbEi4V+j\n2tK0dATdBQBHEh3OJApO2UBtcjaZBT31zrG9K55D+CrcgIVEHAKY8Cb4kLBkb5wM\nskn+DrASKU0BNIV1qRsxfiUdQHZfSqtp004nrql1lbFMLFEuiY8FZrkkQ9qduixo\nmTT6f34/oiY+Jam3zCK7RDN/OjuWheIPGj/Qbx9JuNiwgX6yRj7OE1tjUx6d8g9y\n0H1fmLJbb3WZZbuuGFnK6qrE3bGeY8+AWaJAZ37wpWh1p0cAEQEAAYkBHwQYAQIA\nCQUCUw5EzQIbDAAKCRBRhS2HNI/8TJntCAClU7TOO/X053eKF1jqNW4A1qpxctVc\nz8eTcY8Om5O4f6a/rfxfNFKn9Qyja/OG1xWNobETy7MiMXYjaa8uUx5iFy6kMVaP\n0BXJ59NLZjMARGw6lVTYDTIvzqqqwLxgliSDfSnqUhubGwvykANPO+93BBx89MRG\nunNoYGXtPlhNFrAsB1VR8+EyKLv2HQtGCPSFBhrjuzH3gxGibNDDdFQLxxuJWepJ\nEK1UbTS4ms0NgZ2Uknqn1WRU1Ki7rE4sTy68iZtWpKQXZEJa0IGnuI2sSINGcXCJ\noEIgXTMyCILo34Fa/C6VCm2WBgz9zZO8/rHIiQm1J5zqz0DrDwKBUM9C\n=LYpS\n-----END PGP PUBLIC KEY BLOCK-----",
            "trust_signature": "",
            "source": "HashiCorp",
            "source_url": "https://www.hashicorp.com/security.html"
        }]
    }
}
```

Having the cache populated caused Terraform to skip downloading the package indicated in `download_url`.

---

Reading between the lines here, I think some of you were expecting that the plugin cache would also prevent fetching the _metadata_, but that's not the intended behavior of the plugin cache, as mentioned in [the Provider Plugin Cache documentation](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache):

> When a plugin cache directory is enabled, the `terraform init` command will still access the plugin distribution server to obtain metadata about which plugins are available, but once a suitable version has been selected it will first check to see if the selected plugin is already available in the cache directory. If so, the already-downloaded plugin binary will be used.

With that said, there are some new features coming in the 0.13 line of releases which will offer some more possibilities here, including a way to explicitly populate a local directory with required providers that can then be used either with the existing `-plugin-dir` option or with some new CLI configuration features offering more specific controls over provider installation methods. More details about those will appear in the docs as we prepare for the 0.13 release. (Some of this may follow in subsequent 0.13.x releases, so please don't be alarmed if you don't see all of what I've described here in 0.13.0.)

---

Given that Terraform 0.12 is behaving as designed here (confusing logging notwithstanding), and given that the codepaths you're describing have been rewritten for 0.13 anyway, I'm going to close this out now. There will be an `0.13.0-beta1` release in the next few weeks which will be accompanied by some documentation about the new features and give an opportunity to try it out before final release. If you find any bugs in 0.13.0-beta1 then we would of course love to hear about them!

**Closed by apparentlymart** 2020-05-13 02:53 UTC
