### ISSUE TITLE
Unexpected loss of state due to OOM-killed file data provider

### ISSUE THREAD

**Issue by ingvarm-gr** [hashicorp/terraform#24828] opened 2020-05-01 08:04 UTC
### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

When an spawned subprocess gets OOM-killed, I expect main terraform to go "oh, this thing that I expect to read data from and started just died, I should stop and signal an error".

### Actual Behavior

As far as we can determine, terraform reacted as if "no external data available".

### Steps to Reproduce

Start a terraform run, kill one or more of the child processes while the run is happening.

### Additional Context

Terraform running as part of a CI system, relying on "non-0 exit status" to signal failure, We were running multiple terraforms in parallel, we have now moved to "run them sequentially".

This is terraform generating ignition configs for nodes in kubernetes clusters, so it is vital that various cryptographic material is preserved between runs.

### References

It seems as if issue #694 may be touching on similar things.

**Comment by danieldreier** [comment] 2020-05-01 20:28
If I'm understanding you correctly, you're saying that while a provider is gathering state data, if it's terminated it returns with a 0 exit code and terraform runs as though the provider had returned no data, successfully. Is that accurate?

I also have to point out that we are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. We're actively working on Terraform 0.13. I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. The immediate next step is to check whether this behavior is still the same in 0.12.24.

To try to reproduce the general case of terraform-provider interaction when the provider is terminated in 0.12.24, I ran an AWS instance provisioning and killed the aws provider mid-run. I tested both the cases of killing it while it was gathering state, and while it was trying to provision a resource. I got exit code 1 and the following:

```
Error: rpc error: code = Unavailable desc = transport is closing
```

Can you please confirm whether I'm understanding the issue correctly, and if so, can you confirm whether this is still happening in 0.12.24 for you?

**Comment by apparentlymart** [comment] 2020-06-26 00:37
Hi @ingvarm-gr,

We didn't hear back from you after @danieldreier's recent comment, so I'm going to close this issue. Let us know if you're still having this problem, as Daniel asked, and we can reopen this if so. If you _are_ still seeing it, we'd like to see some trace log output showing the problem so we can understand better what you are seeing and try to reproduce it on our own systems. Thanks!

**Closed by apparentlymart** 2020-06-26 00:37 UTC
Labels: waiting-response
