### ISSUE TITLE
local_file data source that uses a null_resource's id field gets called before null_resource is instantiated

### ISSUE THREAD

**Issue by srolel** [hashicorp/terraform#27021] opened 2020-11-24 14:04 UTC
### Terraform Version

```
0.12.29
```

### Terraform Configuration Files

```terraform
resource "null_resource" "foo" {
  triggers = {
    version = timestamp()
  }
}

data "local_file" "foo" {
  filename = null_resource.foo.id
}
```

### Expected Behavior
local_file.foo should wait for null_resource.foo to be instantiated

### Actual Behavior
local_file.foo is run before null_resource.foo is instantiated

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan` <- fails on subsequent run due to the file being read before the resource is re-instantiated

### References

I came across this while trying to solve this issue with depends_on: https://github.com/hashicorp/terraform/issues/11806

**Comment by alisdair** [comment] 2020-11-24 14:44
Hi @srolel, thanks for reporting this. I don't quite follow what the behaviour you're expecting here is, because this does exactly what I'd expect.

After fixing the typo, my config is:

```hcl
resource "null_resource" "foo" {
  triggers = {
    version = timestamp()
  }
}

data "local_file" "foo" {
  filename = null_resource.foo.id # not "resource.null_resource.foo.id"
}
```

Then plan works:

```shellsession
$ terraform-0.12.29 plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.local_file.foo will be read during apply
  # (config refers to values not yet known)
 <= data "local_file" "foo"  {
      + content        = (known after apply)
      + content_base64 = (known after apply)
      + filename       = (known after apply)
      + id             = (known after apply)
    }

  # null_resource.foo will be created
  + resource "null_resource" "foo" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

Apply fails, but for good reason, because I don't have a file named as the (pseudo-random) `null_resource.foo.id`:

```shellsession
$ terraform-0.12.29 apply -auto-approve
null_resource.foo: Creating...
null_resource.foo: Creation complete after 0s [id=5023621861369670557]
data.local_file.foo: Refreshing state...

Error: open 5023621861369670557: no such file or directory
```

What is the problem that you're seeing here?

**Comment by srolel** [comment] 2020-11-24 15:32
Thanks @alisdair! In my case, in subsequent runs `plan` fails because the file is attempted to be read before the resource is re-instantiated.

**Comment by alisdair** [comment] 2020-11-24 16:08
Again, I can't reproduce the issue. Starting from the above state, if I create the file and re-plan, Terraform works as I'd expect:

```shellsession
$ echo foo > 5023621861369670557
$ terraform-0.12.29 plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.foo: Refreshing state... [id=5023621861369670557]
data.local_file.foo: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # data.local_file.foo will be read during apply
  # (config refers to values not yet known)
 <= data "local_file" "foo"  {
      + content        = (known after apply)
      + content_base64 = (known after apply)
      + filename       = (known after apply)
      + id             = (known after apply)
    }

  # null_resource.foo must be replaced
-/+ resource "null_resource" "foo" {
      ~ id       = "5023621861369670557" -> (known after apply)
      ~ triggers = {
          - "version" = "2020-11-24T14:43:13Z"
        } -> (known after apply) # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

I appreciate that you've tried to reduce the reproduction case to something very simple, but I'm having trouble understanding what your real use case is here, and what you expect to happen. Can you explain further?

**Comment by srolel** [comment] 2020-11-24 16:16
Ah, don't create the file - the first plan will succeed, the apply will fail but then the second plan will fail as well (I expect it to succeed). My use-case is very similar to the issue I linked (#11806)

**Comment by alisdair** [comment] 2020-11-24 16:23
The apply and subsequent plans are expected to fail, because the file doesn't exist. The `local_file` data source does not create a file, it only reads it. As far as I understand it, Terraform is working as designed here, so I'm going to close the issue.

For more details on how to use the `local_file` data source, please see [this comment from the linked issue](https://github.com/hashicorp/terraform/issues/11806#issuecomment-627600697).

---

The behavior you saw there is as intended, because [the `file` function](https://www.terraform.io/docs/configuration/functions/file.html) is for reading files that exist statically as part of the configuration, not for files that are generated dynamically during a Terraform run. Terraform reads the file proactively during initial configuration decoding so that it can use the result as part of static validation.

Although I'd recommend avoiding generating local files on disk if you can, in unusual situations where you can't avoid it you can read the contents of a file using [the `local_file` data source] instead, which (because it's a data source, rather than an intrinsic function) will take its action during the graph walk, not during initial configuration loading.

```hcl
resource "time_rotating" "rsa1" {
  rotation_minutes = 1
}

resource "null_resource" "create_template_file" {
  triggers = {
    filename = time_rotating.rsa1.unix
  }
  provisioner "local-exec" {
    # I added this because I assume you're intending to run
    # a local command to generate this file. You can refer
    # to self.triggers.filename in the provisioner configuration
    # to get the filename populated above.
  }
}

data "local_file" "generated_template" {
  filename = "${path.module}/${null_resource.create_template_file.triggers.filename}"
}

data "template_file" "result" {
  template = data.local_file.generated_template.content
  vars = {
    id = null_resource.rsa1.id
  }
}
```

If you have any follow-up questions about that, please feel free to create an issue in [the community forum](https://discuss.hashicorp.com/c/terraform-core) and I can follow up with you there.

**Closed by alisdair** 2020-11-24 16:23 UTC
Labels: bug, waiting for reproduction

**Comment by srolel** [comment] 2020-11-24 16:26
@alisdair the comment you linked specifically says `local_file` can be used to read a file dynamically. I'm actually doing exactly that but it doesn't work.

**Comment by alisdair** [comment] 2020-11-24 16:48
`local_file` can only read a file which exists. Your original reproduction steps do not include creating the file. In my follow-up comment I pointed out that if the file exists, Terraform works as designed.

This now sounds like a usage question, which is not suitable GitHub issues. I would recommend [posting a thread in the community forum](https://discuss.hashicorp.com/c/terraform-core) with your use case asking for help.

**Comment by srolel** [comment] 2020-11-24 17:04
The issue here (and the bug), is that the data source has a dependency on the resource (via the `id` property) but does not wait for the resource to be re-instantiated. It doesn't have to do directly with the type of the data source or the existence of the file.

This is exactly the use-case prescribed by @apparentlymart in the comment you linked, but it doesn't work.

**Comment by jbardin** [comment] 2020-11-24 18:06
Hi @srolel 

The behavior here can be confusing, but let me explain what was going on in the example you provided.
In 0.12, if a data source directly referenced a resource, during the initial apply the data source would be deferred to apply. Because the argument here, `null_resource.foo.id` in this case, is not known, the data source configuration could not be used yet. (This also happened implicitly even if the argument was known, as a heuristic that the reference must be because of a side effect of the resource creation. This pattern is not recommended however, and the implicit delay was removed in 0.13).

Once the resource and data source are created however, they both exist in the state, and will both be read during refresh. This is where the failure happens, because the `filename` does not exist. That is the correct and expected behavior for terraform.

Now this is mostly obsolete as far as 0.14 is concerned, because there is no longer a separate refresh phase. Refreshing of resources happens during the planning phase, and hence a data source will not be read until its configuration is wholly known. Since this behavior has changed so significantly over the past releases, I suggest that any new issues about this type of behavior use 0.14 as a starting point. 

See also #26939

Thanks!
