### ISSUE TITLE
Unable to authenticate against TFE/TFC by specifying the token

### ISSUE THREAD

**Issue by pschulz1** [hashicorp/terraform#25288] opened 2020-06-18 13:24 UTC
### Terraform Version
```
Terraform v0.12.24
+ provider.tfe v0.17.0
```

### Terraform Configuration Files

```hcl
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization =  "..."
    token = "..."
    workspaces {
      name = "..."
    }
  }
}
```

### Debug Output

2020/06/18 15:18:58 [INFO] Terraform version: 0.12.24  
2020/06/18 15:18:58 [INFO] Go runtime version: go1.12.13
2020/06/18 15:18:58 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}
2020/06/18 15:18:58 [DEBUG] Attempting to open CLI config file: /Users/patrickschulz/.terraformrc
2020/06/18 15:18:58 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/06/18 15:18:58 [DEBUG] checking for credentials in "/Users/patrickschulz/.terraform.d/plugins"
2020/06/18 15:18:58 [DEBUG] checking for credentials in "/Users/patrickschulz/.terraform.d/plugins/darwin_amd64"
2020/06/18 15:18:58 [INFO] CLI command args: []string{"plan"}
2020/06/18 15:18:58 [TRACE] Meta.Backend: built configuration for "remote" backend with hash value 3394852755
2020/06/18 15:18:58 [TRACE] Preserving existing state lineage "fd9de2c2-3426-919c-73bf-46be5e09dd8b"
2020/06/18 15:18:58 [TRACE] Preserving existing state lineage "fd9de2c2-3426-919c-73bf-46be5e09dd8b"
2020/06/18 15:18:58 [TRACE] Meta.Backend: working directory was previously initialized for "remote" backend
2020/06/18 15:18:58 [TRACE] Meta.Backend: using already-initialized, unchanged "remote" backend configuration
2020/06/18 15:18:58 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2020/06/18 15:18:58 [TRACE] HTTP client GET request to https://app.terraform.io/.well-known/terraform.json
2020/06/18 15:18:59 [DEBUG] Retrieve version constraints for service tfe.v2.1 and product terraform
2020/06/18 15:18:59 [TRACE] HTTP client GET request to https://checkpoint-api.hashicorp.com/v1/versions/tfe.v2.1?product=terraform

Error: Required token could not be found

Run the following command to generate a token for app.terraform.io:
    terraform login

### Expected Behavior
I should have been able to run a terraform plan, without the error and the prompt to use terraform login. 

### Actual Behavior
It seems terraform ignores the token inside my configuration and only attempts to get the one from .terraformrc
Also if I comment the token inside my configuration, the behavior is pretty much the same. 

### Steps to Reproduce
Just do a terraform plan with the given terraform config and NO .terraformrc present.

**Comment by alisdair** [comment] 2020-06-18 18:53
@pschulz1 This looks like a duplicate of #13022. That is, variables are not allowed in backend configuration. If I follow your steps to reproduce, Terraform 0.12.26 shows the errors:

```shellsession
$ terraform-0.12.26 init

Initializing the backend...

Error: Variables not allowed

  on main.tf line 4, in terraform:
   4:     organization =  var.org

Variables may not be used here.


Error: Variables not allowed

  on main.tf line 5, in terraform:
   5:     token = var.token

Variables may not be used here.


Error: Variables not allowed

  on main.tf line 7, in terraform:
   7:       name = var.workspace

Variables may not be used here.
```

Can you check this for me and report back if I'm misunderstanding something about your repro steps?

If I understand your use case, you should be able to use [partial backend configuration flags](https://www.terraform.io/docs/backends/config.html#partial-configuration) to `terraform init`.

**Comment by pschulz1** [comment] 2020-06-18 19:25
Oh my bad and apologies @alisdair 
I've put variables in to redact my token and stuff. I'm not using any variables.
So, could you please give it a try without any variables? Thanks!

**Comment by alisdair** [comment] 2020-06-18 19:32
Ah, I see! However, I still cannot reproduce this exact error. Using Terraform 0.12.26 with this config:

```hcl
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "..." # my organization name
    token        = "..." # valid TFC token
    workspaces {
      name = "tfc-token-test"
    }
  }
}
```

This works:

```shellsession
$ terraform-0.12.26 init

Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Just in case it's somehow the cause, can you try again with Terraform 0.12.26?

**Comment by pschulz1** [comment] 2020-06-18 19:34
Just removed the .terraform dir in my working directory and performed a new init. This seems to have fixed it. Not sure what got stuck under the covers.

**Comment by alisdair** [comment] 2020-06-18 19:39
Great! 🎉 Closing for now.

**Closed by alisdair** 2020-06-18 19:39 UTC
Labels: backend/remote, v0.12, waiting-response
