### ISSUE TITLE
terraform destroy refresh flag does not work

### ISSUE THREAD

**Issue by williamcodes** [hashicorp/terraform#28300] opened 2021-04-07 11:13 UTC
### Terraform Version

```
$ terraform --version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.33.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/helm v2.0.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

Your version of Terraform is out of date! The latest version
is 0.14.9. You can update by downloading from https://www.terraform.io/downloads.html

```

### Terraform Configuration Files

```terraform
```

### Expected Behavior

`terraform destroy -refresh=true` should refresh before destroying resources.
### Actual Behavior

`terraform destroy -refresh=true` does not refresh.
### Steps to Reproduce

```bash
terraform destroy -refresh=true
```

**Comment by jbardin** [comment] 2021-04-07 13:56
Hi @williamcodes,

Thanks for filing the issue. Can you show an example of the problem you are facing? 
The `-refresh` flag default is `true`, so setting that flag is not expected to alter the behavior at all, and managed resources should always be be read before they are destroyed.  If you are dealing with data sources that are not being refreshed, that is likely a duplicate of issue #27172.

**Comment by williamcodes** [comment] 2021-04-07 16:55
Hmm, terraform destroy never refreshes for me, no matter what flags I use.

**Comment by jbardin** [comment] 2021-04-07 17:04
Sorry, you are correct, I was thinking of a different situation.
No resources are going to be read during a full destroy in 0.14, and will require a manual refresh if necessary. 
While #27172 only mentions data sources, the resolution handles all resource types.

Closing as a duplicate of #27172

Thanks!

**Closed by jbardin** 2021-04-07 17:04 UTC
Labels: bug, waiting for reproduction
