### ISSUE TITLE
Terraform resource created using 0.12 version cannot be re-created after upgrading to 0.13 

### ISSUE THREAD

**Issue by rohanvirmani** [hashicorp/terraform#27150] opened 2020-12-04 18:47 UTC
### Terraform Version

```
Version 0.12.26 and version 0.13.5
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
  version                    = "=2.0.0"
  skip_provider_registration = "true"
  features {}
}



resource "azurerm_resource_group" "main" {
  name     = "app508-Rohan-test2-resources"
  location = "East US"
}
```

### Actual Behavior

What actually happened?
Error: Provider configuration not present
```
To work with module.pod_bootstrap.data.azurerm_role_definition.reader its
original provider configuration at provider["registry.terraform.io/-/azurerm"]
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.pod_bootstrap.data.azurerm_role_definition.reader, after which you can
remove the provider configuration again.
```

### Steps to Reproduce

Use TF 0.12.26
1. `terraform init`
2. `terraform apply`

Change Terraform resource name in config to 'main2'.
use TF 0.13.5
Re-run TF apply

### Additional Context

We provision boiler plate infrastructure when running builds for each pod (Dev , QA, perf etc) and we do not always update this unless we absolutely need too.

It is a common scenario for us to re-create some resources especially role assignments in Azure.

I have read the upgrade documentation that says we should be running an empty terraform apply after the .13 update. This is not feasible for us to do for each microservice and environment each time a change like this is done. Any suggestions for alternatives in this situation would be appreciated!

**Comment by jbardin** [comment] 2020-12-04 21:42
Duplicate of #25951

**Closed by jbardin** 2020-12-04 21:42 UTC
Labels: bug, new

**Comment by MarkKharitonov** [comment] 2020-12-05 01:40
@jbardin - The referenced issue does not clarify what we need to do when we have a hundred different TF states. We follow the best practice - each deployed environment is split into components each having its state. So, typically a micro service have 6 environments, i.e. about 25 TF states per micro service. Multiply the number of microservices and you get hundreds of states.

Are we supposed to redeploy all of them or run **terraform state replace-provider** for each of them ?
