### ISSUE TITLE
brew install of Terraform 1.4.4 shows v1.4.3-dev as version

### ISSUE THREAD

**Issue by brsolomon-deloitte** [hashicorp/terraform#33005] opened 2023-04-07 20:03 UTC
### Terraform Version

```shell
$ brew reinstall terraform@1.4
rm /opt/homebrew/bin/terraform
==> Fetching terraform
==> Downloading https://ghcr.io/v2/homebrew/core/terraform/manifests/1.4.4
Already downloaded: /Users/redacted/Library/Caches/Homebrew/downloads/8ff45fd0bdc4ef3894992ac9a3176dff0d43e5727c985959a032d9749f174654--terraform-1.4.4.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:b275c125ecc74f735d4772912df098cde497d7b37f40a79941d1242f51e3cfe6
Already downloaded: /Users/redacted/Library/Caches/Homebrew/downloads/9ea3c47e5f164c715dccec57779426ff1b0cc86b2e3e3827ecb7fb62d8809a5c--terraform--1.4.4.arm64_ventura.bottle.tar.gz
==> Verifying checksum for '9ea3c47e5f164c715dccec57779426ff1b0cc86b2e3e3827ecb7fb62d8809a5c--terraform--1.4.4.arm64_ventura.bottle.tar.gz'
==> Reinstalling terraform
==> Pouring terraform--1.4.4.arm64_ventura.bottle.tar.gz
/usr/bin/env tar --extract --no-same-owner --file /Users/redacted/Library/Caches/Homebrew/downloads/9ea3c47e5f164c715dccec57779426ff1b0cc86b2e3e3827ecb7fb62d8809a5c--terraform--1.4.4.arm64_ventura.bottle.tar.gz --directory /private/tmp/d20230407-36133-3l669x
/usr/bin/env cp -pR /private/tmp/d20230407-36133-3l669x/terraform/. /opt/homebrew/Cellar/terraform
ln -s ../Cellar/terraform/1.4.4/bin/terraform terraform
🍺  /opt/homebrew/Cellar/terraform/1.4.4: 6 files, 67.7MB
==> Running `brew cleanup terraform`...

 ~/dev/deloitte/adhoc/tfc-getting-started -> main
$ terraform version
Terraform v1.4.3-dev
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

n/a

### Debug Output

```
$ TF_LOG=trace terraform version
2023-04-07T16:01:24.323-0400 [INFO]  Terraform version: 1.4.3 dev
2023-04-07T16:01:24.325-0400 [DEBUG] using github.com/hashicorp/go-tfe v1.18.0
2023-04-07T16:01:24.325-0400 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
2023-04-07T16:01:24.325-0400 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-04-07T16:01:24.325-0400 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-04-07T16:01:24.325-0400 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-04-07T16:01:24.325-0400 [INFO]  Go runtime version: go1.20.2
2023-04-07T16:01:24.325-0400 [INFO]  CLI args: []string{"terraform", "version"}
2023-04-07T16:01:24.325-0400 [TRACE] Stdout is a terminal of width 189
2023-04-07T16:01:24.325-0400 [TRACE] Stderr is a terminal of width 189
2023-04-07T16:01:24.325-0400 [TRACE] Stdin is a terminal
2023-04-07T16:01:24.325-0400 [DEBUG] Attempting to open CLI config file: /Users/redacted/.terraformrc
2023-04-07T16:01:24.325-0400 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-04-07T16:01:24.325-0400 [INFO]  Loading CLI configuration from /Users/redacted/.terraform.d/credentials.tfrc.json
2023-04-07T16:01:24.325-0400 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-04-07T16:01:24.325-0400 [DEBUG] ignoring non-existing provider search directory /Users/redacted/.terraform.d/plugins
2023-04-07T16:01:24.325-0400 [DEBUG] ignoring non-existing provider search directory /Users/redacted/Library/Application Support/io.terraform/plugins
2023-04-07T16:01:24.325-0400 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2023-04-07T16:01:24.326-0400 [INFO]  CLI command args: []string{"version"}
Terraform v1.4.3-dev
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Expected Behavior

Version should be 1.4.4.

### Actual Behavior

Version shows as 1.4.3. Can't do anything with Terraform Cloud:

> `An error occurred: Terraform version "1.4.3-dev" does not resolve to a version of Terraform present in Terraform Cloud, or this organization is not permitted to use it.`

### Steps to Reproduce

See above

**Comment by jbardin** [comment] 2023-04-07 20:47
Duplicate of #32963

**Closed by jbardin** 2023-04-07 20:47 UTC
Labels: bug, new
