### ISSUE TITLE
Allow access to provider vars

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#2309] opened 2015-06-10 21:48 UTC
Discussed on IRC, @phinze suggested I open an issue to track this feature.

Use case:
```
resource "aws_instance" "app" {
    ami = "${lookup(var.amis, aws.region)}"
    instance_type = "..."
}
```

This fails with `resource variables must be three parts`. Workaround currently is a redundant `aws_region` var read from `TF_VAR_aws_region`.

**Comment by radeksimko** [comment] 2015-06-10 22:20
Hmm, isn't it duplicate of https://github.com/hashicorp/terraform/issues/1199 ? :smiley_cat:

**Comment by phinze** [comment] 2015-06-10 22:43
Whoops sorry @pikeas I had forgotten that #1199 existed - we can consolidate over there :+1:

**Closed by phinze** 2015-06-10 22:43 UTC
