### ISSUE TITLE
Terraform cloud : Import existing resource

### ISSUE THREAD

**Issue by sujalb** [hashicorp/terraform#24931] opened 2020-05-12 15:32 UTC
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.12.0"

  backend "remote" {
    hostname = "app.terraform.io"
    organization = "foo"

    workspaces {
      name = "bar"
    }
  }
}
```

### Expected Behavior

I am using **terraform cloud** to manage the state of the infrastructure provisioned in AWS.

I am trying to use terraform import to import an existing resource that is currently not managed by terraform.

I understand terraform import is a local only command. I have set up a workspace reference as shown above. 

The AWS credentials are configured in the remote cloud workspace but terraform does not appear to be referencing the AWS credentials from the workspace but instead falls back trying to using the local credentials which points to a different AWS account. I would expect Terraform to use the credentials by referencing the variables in the workspace when I run terraform import.

When I comment out the locally configured credentials, I get the error:

```Error: No valid credential sources found for AWS Provider.```

### Actual Behavior

Expected: Terraform should have used the credentials in the environment variables of the workspace.

**Comment by pkolyvas** [comment] 2020-05-12 16:15
Hi @sujalb, I'm going to close this as a duplicate of #23407

There's a comment there about this [design choice](https://github.com/hashicorp/terraform/issues/23407#issuecomment-555278186).

At the moment it is by design, but I will gladly communicate your request to the terraform-cloud team.

**Closed by pkolyvas** 2020-05-12 16:15 UTC
Labels: enhancement, terraform-cloud
