### ISSUE TITLE
Upgrade to 0.10.0 crash terraform on MacOS

### ISSUE THREAD

**Issue by tata2000** [hashicorp/terraform#15777] opened 2017-08-10 16:17 UTC
After upgrading to terraform 0.10.0 from 0.9.10
Only on MAC the terraform crashes when running without -target.
for commands:
apply, plan

the error is 
 *terraform.EvalRefresh, err: aws_iam_role.role: connection is shut down
the resource is different every time.

It works fine on Linux with no problems with all same configs and tf files.

**Comment by rowleyaj** [comment] 2017-08-10 18:21
@tata2000 not related to Hashicorp in any way, but I saw the title and was concerned. I've been using 0.10.0 on MacOS without issue so I'd guess this is a problem with your environment - especially with the config working on Linux.

Do you have any more steps to reproduce? A sample configuration that you see a crash with or any kind of debug output (https://www.terraform.io/docs/internals/debugging.html).

From the error message I'd guess there is a problem whilst attempting to call refresh on the provider, is it possible you have some kind of custom cached providers in place on the MacOS system?

**Comment by rowleyaj** [comment] 2017-08-11 10:48
Dupe of https://github.com/terraform-providers/terraform-provider-aws/issues/1384

**Comment by tata2000** [comment] 2017-08-13 10:08
Hey @rowleyaj 

Thanks for your prompt response.
I have opened both tickets as i' not sure that the problem is within the provider, but as i search it more - it seems like it is. i have found a resource that fails - but is not the only one (removing this resource still crashed the entire terraform)

But, this resource has a block with EOF


Here is the resource 
```
resource "aws_s3_bucket" "logging" {
    bucket = "${var.s3_logging}"
    acl    = "log-delivery-write"
    policy =<<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AWSCloudTrailAclCheck20150319",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudtrail.amazonaws.com"
      },
      "Action": "s3:GetBucketAcl",
      "Resource": "arn:aws:s3:::${var.s3_logging}"
    },
    {
      "Sid": "Permit access log delivery by AWS ID for Log Delivery service",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::858827067514:root"
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::${var.s3_logging}/logs/*"
    },
    {
      "Sid": "AWSCloudTrailWrite20150319",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudtrail.amazonaws.com"
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::${var.s3_logging}/AWSLogs/${var.account_id}/*",
      "Condition": {
        "StringEquals": {
          "s3:x-amz-acl": "bucket-owner-full-control"
        }
      }
    }
  ]
}
EOF

    lifecycle_rule {
        enabled = true
        prefix = ""

        expiration {
            days = "${var.days_to_expire}"
        }
    }

    logging {
        target_bucket = "${var.s3_logging}"
        target_prefix = "logs/${var.s3_logging}/"
    }

    tags {
        Name = "${var.s3_logging}"
        Environment = "${var.environment}"
    }

}
```

and here is the result:
```
aws_s3_bucket.logging: Refreshing state... (ID: firelayers.cloudtrail-eu)
Error refreshing state: 1 error(s) occurred:

* aws_s3_bucket.logging: 1 error(s) occurred:

* aws_s3_bucket.logging: aws_s3_bucket.logging: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23a327f]
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4:
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: goroutine 129 [running]:
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsS3BucketRead(0xc420190b60, 0x299be00, 0xc42011e800, 0x0, 0x40045e0)
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_s3_bucket.go:787 +0x1b3f
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42033cc00, 0xc4204911d0, 0x299be00, 0xc42011e800, 0xc4205205e8, 0xc4204e5101, 0x0)
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:320 +0x21d
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420126460, 0xc420491180, 0xc4204911d0, 0x4a052c0, 0x0, 0x0)
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4203c3400, 0xc42047a580, 0xc42047ae00, 0x0, 0x0)
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: reflect.Value.call(0xc42039ea80, 0xc4203da3f8, 0x13, 0x2c7773a, 0x4, 0xc420253f20, 0x3, 0x3, 0x0, 0xc420487aa0, ...)
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: reflect.Value.Call(0xc42039ea80, 0xc4203da3f8, 0x13, 0xc420029720, 0x3, 0x3, 0xc420537560, 0x3faf560, 0xc420537740)
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: net/rpc.(*service).call(0xc42020e580, 0xc42020e540, 0xc42010af68, 0xc420110c80, 0xc42010e880, 0x2648b60, 0xc42047a580, 0x16, 0x2648ba0, 0xc42047ae00, ...)
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: created by net/rpc.(*Server).ServeCodec
2017/08/13 13:06:33 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
2017/08/13 13:06:33 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_s3_bucket.logging: unexpected EOF
2017/08/13 13:06:33 [ERROR] root: eval: *terraform.EvalSequence, err: aws_s3_bucket.logging: unexpected EOF
2017/08/13 13:06:33 [TRACE] [walkRefresh] Exiting eval tree: aws_s3_bucket.logging
2017/08/13 13:06:33 [DEBUG] dag/walk: upstream errored, not walking "provider.aws (close)"
2017/08/13 13:06:33 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/08/13 13:06:33 [DEBUG] plugin: /Users/tata/fl/do-provision/terraform/newvpc/.terraform/plugins/darwin_amd64/terraform-provider-aws_v0.1.3_x4: plugin process exited
2017/08/13 13:06:33 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/08/13 13:06:33 [WARN] plugin: error closing client during Kill: connection is shut down
2017/08/13 13:06:33 [DEBUG] plugin: terraform-0.10.0: local-exec-provisioner (internal) 2017/08/13 13:06:33 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/08/13 13:06:33 [DEBUG] plugin: /Users/tata/helpers/terraform-0.10.0: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

hope this helps

**Comment by apparentlymart** [comment] 2017-08-14 18:25
Thanks for the info @tata2000. It does indeed look like a provider issue, so I'm going to close this in favor of terraform-providers/terraform-provider-aws#1384; I left a comment over there because the stack trace above suggests that it's the same root cause as another fix, but let's continue the discussion over there.

**Closed by apparentlymart** 2017-08-14 18:25 UTC
Labels: bug, waiting-response

**Comment by tata2000** [comment] 2017-08-15 12:57
@apparentlymart  
thanks
