### ISSUE TITLE
Inconsistency between plan and apply

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#25090] opened 2020-05-31 05:23 UTC
### Terraform Version

```
Terraform v0.12.25
```

### Terraform Configuration Files

Say I have a resource `foo` with following schema definition:

```go
func resourceFoo() *schema.Resource {
	return &schema.Resource{
		Create: resourceFooCreateOrUpdate,
		Read:   resourceFooRead,
		Update: resourceFooCreateOrUpdate,
		Delete: resourceFooDelete,
		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"age": {
				Type:     schema.TypeInt,
				Optional: true,
			},
			"job": {
				Type:     schema.TypeString,
				Optional: true,
			},
                },
         }
}
```
(You can find a simple implementation of the provider at https://github.com/magodo/terraform-provider-demo)

Then I have following configs:

**config1**

```hcl
resource "demo_resource_foo" "magodo" {
  name = "magodo"
  job  = "gopher"
}

resource "demo_resource_foo" "rr" {
  name   = "rr"
  job = demo_resource_foo.magodo.output_job
  age  = 1
}
```

**config2**

(2 updates)

```hcl
resource "demo_resource_foo" "magodo" {
  name = "magodo"
  job  = "rustcean" # update
}

resource "demo_resource_foo" "rr" {
  name   = "rr"
  job = demo_resource_foo.magodo.output_job
  age  = 2 # update
}
```

### Crash Output

```bash
demo_resource_foo.magodo: Refreshing state... [id=magodo]
demo_resource_foo.rr: Refreshing state... [id=rr]
demo_resource_foo.magodo: Modifying... [id=magodo]
demo_resource_foo.magodo: Modifications complete after 0s [id=magodo]

Error: Provider produced inconsistent final plan

When expanding the plan for demo_resource_foo.rr to include new values learned
so far during apply, provider "registry.terraform.io/-/demo" produced an
invalid new value for .job: was cty.StringVal("gopher"), but now
cty.StringVal("rustacean").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior

Terraform should be able to identify that the change of `job` in `demo_resource_foo.magodo` might results into all the computed attributes to be changed, hence should tell user the `demo_resource_foo.rr` will have a **known after apply** input from `demo_resource_foo.magodo`.

### Actual Behavior

Crashed with inconsistent final plan.

### Steps to Reproduce

1. apply **config1** - succeed
2. apply **config2** - crash

### Additional Context

Though the error message tells this is an issue of provider, however, I think in this case it is a limitation of terraform core.

**Comment by apparentlymart** [comment] 2020-06-03 23:35
Hi @magodo,

It is the responsibility of logic in the provider to produce an accurate plan. If `output_job` changes whenever `job` changes then your provider must implement logic that reflects that.

There are two main ways to achieve that:

1. If changing `name` really means to replace the object altogether and create a new object with a new name, you can set `ForceNew: true` inside the schema for the `name` attribute. The Terraform SDK will then automatically signal to Terraform Core that any change to that argument "requires replacement", creating a `-/+` action instead of a `~` action in the plan, and as a result Terraform Core will automatically mark `output_job` as "known after apply" as it would normally do during a create operation.

2. If `name` can change without replacing the object but this does still cause other argument values to change as side-effects, you'll need to write some custom logic in the resource implementation to describe that interaction. We can do this by populating [the `CustomizeDiff` field](https://www.terraform.io/docs/extend/resources/customizing-differences.html) in the `schema.Resource` object with a function that implements the logic. For example:

    ```go
        CustomizeDiff: func(d *ResourceDiff, meta interface{}) error {
            if d.HasChange("name") {
                d.SetNewComputed("output_job")
            }
        }
    ```

    The Terraform SDK will run your `CustomizeDiff` function during the plan phase. Calling `SetNewComputed` will cause the SDK to tell Terraform Core that `output_job` should appear as "known after apply" in the plan, which will then in turn cause anything other arguments derived from `demo_resource_foo.magodo.output_job` to also be marked as "known after apply", avoiding this "Provider produced inconsistent final plan" error.

The general rule underlying that error is that if the plan for a particular attribute has a known value (anything other than "known after apply") during planning, the value must be _exactly the same_ after the apply phase. If you don't know what the new value will be then you can mark it as "known after apply" (in the SDK's terminology, as "computed") which then gives you the freedom to return any value for that attribute as the result from the apply step.

Because Terraform's logic seems to have worked as intended here, I'm going to close this. However, if you have further questions about `CustomizeDiff` please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where I or someone else can hopefully answer questions about the details of this behavior.

**Closed by apparentlymart** 2020-06-03 23:35 UTC
