### ISSUE TITLE
Unable to debug cycle from error message

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform#35238] opened 2024-05-24 08:55 UTC
### Terraform Version

```shell
Terraform v1.8.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.24.0
+ provider registry.terraform.io/hashicorp/google-beta v5.24.0
```

### Terraform Configuration Files

```terraform
data "google_iam_workload_identity_pool" "svc" {
  workload_identity_pool_id = "${data.google_project.default.name}.svc.id.goog"

  depends_on = [
    module.default_cluster,
  ]
}
```

### Debug Output

Cannot provide due to sensitive information.

### Expected Behavior

Terraform should output "cycle" information in a way that one can actually see - debug the cycle and find solutions.

### Actual Behavior

Output is:

```
Error: Cycle: module.default_cluster.google_container_cluster.main, module.common.var.rules_principal (expand), module.rules.var.svc_identity_pool (expand), module.rules.local.rules_principal (expand), module.rules.output.rules_principal (expand), module.common.var.microservice_principals (expand), module.common.data.google_iam_policy.project, module.common.google_project_iam_policy.project, module.common.output.container_service_identity (expand), data.google_container_engine_versions.europe_west1, module.default_cluster.var.container_engine_version (expand), module.default_cluster (close), data.google_iam_workload_identity_pool.svc
```

### Steps to Reproduce

1. `terraform init`
2. `terraform graph`

**Comment by jbardin** [comment] 2024-05-24 15:17
Duplicate of #26150

**Closed by jbardin** 2024-05-24 15:17 UTC
Labels: bug, new
