### ISSUE TITLE
cloudflare_record does not support import

### ISSUE THREAD

**Issue by cmorent** [hashicorp/terraform#14497] opened 2017-05-15 14:03 UTC
Feature request to support import on the cloudflare_record resource

### Terraform Version

Terraform 0.9.6-dev

### Affected Resource(s)

cloudflare_record

### Expected Behavior

Should import an existing cloudflare record.

### Actual Behavior

Generates an error that import is not supported.

### Steps to Reproduce

run a terraform import cloudflare_record.<resource_name> <cloudflare_record_id>

**Comment by grubernaut** [comment] 2017-05-15 15:48
Hey @cmorent, thanks for both the issue and the PR! 

However, the resource `cloudflare_record` cannot, at this time be imported without some core changes. In order to call `Read` on a `cloudflare_record` we need both `domain` and `id` for the resource to be populated. And imports, currently, only support a single attribute to be specified during the import command. In the `Import` function written in the `PR`, it calls `d.Get("domain")` here: https://github.com/hashicorp/terraform/pull/14500/files#diff-30a33f8cd870a253f0581f72b38f6b65R78. 

During an `import` the supplied `schema.ResourceData` object will only have one field set, `id`. And the `id` field is the string specified on the command line during the import. Thus, `domain` in this case, will always be a `nil` string. 

We've had _several_ internal discussions on how to better handle resources that require multiple attributes set in order to import a resource, but currently don't have any concrete plans to add this yet. 

Thank you so much for taking a stab at this though, myself I've spent a couple hours trying to work out a solution to allow importing a cloudflare record as well :smile:. 

For now, going to close the issue as it's a duplicate of #11219. I'll leave the PR for a while unless you wish to close it out, but for now it's currently unfeasible to add. 
Happy to discuss this and the PR further though. Thanks again!

**Closed by grubernaut** 2017-05-15 15:48 UTC
Labels: enhancement, provider/cloudflare

**Comment by cmorent** [comment] 2017-05-15 15:53
Hey @grubernaut! Thanks for all of the details, it's much more clear for me now ! 

I will close the PR as I don't think I will work on it anymore as you say it is not feasible for now and try to find another way to import our existing cloudfare records (maybe manually or by recreating new DNS records?).

**Comment by grubernaut** [comment] 2017-05-15 16:11
Thanks again @cmorent, the work is greatly appreciated, regardless! 

Once we determine the best path forward for specifying multiple input variables on the command line, importing cloudflare records and numerous other similar resources will be a lot easier. For now though, it's a difficult path. :smile:

**Comment by chbrown** [comment] 2018-10-01 00:15
For anyone else arriving here after Googling "resource cloudflare_record doesn't support import" and clicking the top result, the [example syntax in the official docs](https://www.terraform.io/docs/providers/cloudflare/r/record.html#import) works, but you (like me) may need to upgrade your cloudflare provider version (`1.5.0` is the latest as of this comment):
```HCL
provider "cloudflare" {
  version = "~> 1.5"
}

resource "cloudflare_record" "default" {
  # ...
}
```
And then be sure to `terraform init` again.
