### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alexandrusavin** [hashicorp/terraform#30215] opened 2021-12-20 10:16 UTC
### Terraform Version

```
v1.1.2
```
![image](https://user-images.githubusercontent.com/1612455/146743639-db5d65da-3f1e-44dd-9713-a2781ddf623f.png)

### Terraform Configuration Files

```terraform
...
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:55 +0x154
panic({0x2e24180, 0x4ae90d0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hashicorp/terraform/internal/command.completePredictSequence.Predict(...)
        /Users/distiller/project/project/internal/command/autocomplete.go:32
github.com/posener/complete.(*Command).predict(0xc00026a300, {{0xc0006365d0, 0x1, 0x3}, {0xc0006365d0, 0x0, 0x3}, {0x0, 0x0}, {0xc00005a07e, ...}})
        /Users/distiller/go/pkg/mod/github.com/posener/complete@v1.2.3/command.go:107 +0x5fe
github.com/posener/complete.(*Command).predict(0xc00026a2d0, {{0xc0006365c0, 0x2, 0x4}, {0xc0006365c0, 0x1, 0x4}, {0x0, 0x0}, {0xc00005a07e, ...}})
        /Users/distiller/go/pkg/mod/github.com/posener/complete@v1.2.3/command.go:73 +0x9a5
github.com/posener/complete.(*Command).predict(0xc000495500, {{0xc0006365b0, 0x3, 0x5}, {0xc0006365b0, 0x2, 0x5}, {0x0, 0x0}, {0xc00005a07e, ...}})
        /Users/distiller/go/pkg/mod/github.com/posener/complete@v1.2.3/command.go:73 +0x9a5
github.com/posener/complete.(*Command).Predict(...)
        /Users/distiller/go/pkg/mod/github.com/posener/complete@v1.2.3/command.go:27
github.com/posener/complete.(*Complete).Complete(0xc000495500)
        /Users/distiller/go/pkg/mod/github.com/posener/complete@v1.2.3/complete.go:69 +0x1b9
github.com/mitchellh/cli.(*CLI).Run(0xc00017ef00)
        /Users/distiller/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:184 +0xaa
main.realMain()
        /Users/distiller/project/project/main.go:309 +0x1509
main.main()
        /Users/distiller/project/project/main.go:58 +0x19

```

The error is repeated in a loop. I had to send a SIGTERM to stop it.

### Expected Behavior

should not crash

### Actual Behavior

it crashed

### Steps to Reproduce

I was typing in the shell `terraform workspace select` and it crashed when I pressed TAB to get autocomplete for the list of possible workspaces.

1. `terraform workspace select` - no return (︕⏎ )
2. press `TAB`

### Additional Context

I'm trying to update a repository created with a previous version (0.15).

### References

A search in the issues queue revealed some related ones: 
https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Acrash+sort%3Aupdated-desc+invalid+memory+address+or+nil+pointer+dereference+

**Comment by jbardin** [comment] 2021-12-20 14:34
Thanks for reporting the issue @alexandrusavin!
Duplicate of #30193

**Closed by jbardin** 2021-12-20 14:34 UTC
Labels: bug, new
