### ISSUE TITLE
Terraform 0.13.0 downloading unwanted version for -/azurerm provider

### ISSUE THREAD

**Issue by andrew-sumner** [hashicorp/terraform#25914] opened 2020-08-19 05:49 UTC
Since upgrade to Terraform 0.13.0 terraform is always downloading the latest azurerm provider in addition to the requested version.

### Terraform Version
```
Terraform v0.13.0
+ provider registry.terraform.io/-/azurerm v2.23.0
+ provider registry.terraform.io/hashicorp/azurerm v2.19.0
```

### Terraform Configuration Files
```
terraform {
  backend "azurerm" {
    resource_group_name  = "terraform-rg"
    storage_account_name = "satestterraform"
    container_name       = "tfstate"
    key                  = "function_app"
  }
}

provider "azurerm" {
   version = "=2.19.0"
}
```

### Debug Output
terraform init

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of -/azurerm...
- Finding hashicorp/azurerm versions matching "2.19.0"...
- Using -/azurerm v2.23.0 from the shared cache directory
- Using hashicorp/azurerm v2.19.0 from the shared cache directory

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* -/azurerm: version = "~> 2.23.0"

Terraform has been successfully initialized!

### Expected Behavior
Should only download specified provider version hashicorp/azurerm v2.19.0

### Actual Behavior
Downloaded the requested version and -/azurerm v2.23.0 (latest)

### Steps to Reproduce
1. `terraform init`

### Additional Context
Worked without any issues using terraform 0.12.29

**Comment by TomTucka** [comment] 2020-08-19 10:45
Hey @andrew-sumner!

I think doing `state replace-provider` should fix this issue! You can find more information about this command here: https://www.terraform.io/upgrade-guides/0-13.html

`terraform state replace-provider 'registry.terraform.io/-/azurerm' 'registry.terraform.io/hashicorp/azurerm'`

**Comment by mildwonkey** [comment] 2020-08-19 13:01
I can second @TomTucka 's suggestion, though it's worth noting that it's not going to cause any issues from terraform's perspective. This is a duplicate of #25771; you can see my explanation in [this comment](https://github.com/hashicorp/terraform/issues/25771#issuecomment-671338867). Thanks!

**Closed by mildwonkey** 2020-08-19 13:01 UTC
Labels: bug, new
