### ISSUE TITLE
aws_network_interface forces new resource if private_ips is not assigned

### ISSUE THREAD

**Issue by mikerahmati** [hashicorp/terraform#2827] opened 2015-07-23 05:27 UTC
Using Terraform v0.6.0

It seems aws_network_interface forces new resource if private_ips is not explicitly assigned. 

simply ```terraform apply``` the following :
```
resource "aws_network_interface" "nat_network_interface" {
	subnet_id = "REPLACE_ME"
}
```
and the output: 
```
aws_network_interface.nat_network_interface: Creating...
  security_groups.#: "" => "<computed>"
  subnet_id:         "" => "subnet-37489b40"
aws_network_interface.nat_network_interface: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```
Now if you ```terraform plan -module-depth=-1 ``` again, it results in new resource:
```
-/+ aws_network_interface.nat_network_interface
    private_ips.#:          "1" => "0" (forces new resource)
    private_ips.1213751514: "10.13.29.241" => ""
    security_groups.#:      "1" => "<computed>"
    subnet_id:              "subnet-37489b40" => "subnet-37489b40"
```
Please let me know if you need more details. Many Thanks.

**Comment by jszwedko** [comment] 2015-07-23 06:25
This is a duplicate of #2729

**Comment by phinze** [comment] 2015-07-27 18:29
Yep - closing as dup.

**Closed by phinze** 2015-07-27 18:29 UTC
