### ISSUE TITLE
Unknown variable referenced error too late, unclear

### ISSUE THREAD

**Issue by rainmanh** [hashicorp/terraform#1861] opened 2015-05-08 04:14 UTC
Hi 
I have been reading the release notes for 0.5.0 trying to find an explanation for something a bit strange..
I am using the very same piece of code for 0.4.2 and 0.5.0
while on 0.4.2 seems to work well on 0.5.0 when I run plan terraform I am getting errors variable related such us:
* module.vpc_infrastructure: missing dependency: var.cidr-block-vpc-infrastructure
That is coming from this file: infrastructucture.tf
```
/* Infrastructure  Modules */
module "vpc_infrastructure" {
  source = "modules/network/vpc/infrastructure/"
  cidr-block-vpc-infrastructure = "${var.cidr-block-vpc-infrastructure}"
  region = "${var.region}"
}
```

And the variable has been defined on terraform.tfvars
```
/* cidr vpc infrastructure */
cidr-block-vpc-infrastructure = "50.10.0.0/16"
```
But it is ignored unless I update the variables.tf :
```
variable "cidr-block-infrastructure-backbone-1a" {
	default= "50.10.0.0/16"
}
```

Maybe this is expected all together, but a bit puzzled as on 0.4.2 it never reported those errors and I cannot find the piece of documentation which can explain all that..

Thanks!

**Comment by mitchellh** [comment] 2015-05-08 15:24
This was a  bug thats always just worked prior to 0.5. 0.5 tightens up validation: you now must define the variables before you use them. However, we should still be catching this earlier than this error shows, and I'm unsure why this is the error you see. 

I'm going to tag it as a bug and rename the issue to better reflect.

**Comment by neurogenesis** [comment] 2015-05-26 22:11
we just ran into a similar problem when upgrading from 0.4.2 to 0.5.1 (which reports its version as 0.5.2). The only difference is that the variable is already defined in an upstream common module that is pulled in via "terraform get".

As presently implemented, do all variables referenced in a terraform file have to be defined in a file local to the terraform files is being run? (./*.tf)  Put another way, would this also mean that all variables are locally scoped to the directory/path terraform is run in (can't use variables from imported / common tf files)?

I guess I'm looking for clarification in the documentation on to what extent override behavior works, particularly for cases where common global variables are used, then overridden locally.

I should be able to:

- define a variable in a common area
- use a global variable from common / upstream tf files (via terraform get)
- override global via local variables.tf or terraform.tfvars
- override global via global ~/.terraform (or ~/terraform.tfvars)

For example, we have 3 subdirectories for terraform: common, staging, production. Variables are defined in the common stack in a file called "main.tf", where service / infrastructure templates reside.

Staging and production have their own respective *.tf files that use a mix of their own variables and those defined in the common files. Each environment directory has a "variables.tf"). We also use a "terraform.tfvars" override file for sensitive values we don't want checked into git. What we were trying to do is avoid duplication by moving common variables into upstream / common areas. There are also cases where users have their own provider credentials: sometimes common to all environments, sometimes unique to an environment (if credentials for uat and staging are in different AWS accounts for example).

After playing around with this for a bit, it looks like variables defined outside of the current path are not visible or are out of scope.

**terraform/common/main.tf**
```
variable "chef_validation_key" {}
variable "chef_encrypted_data_bag_secret" {}
...
```

**terraform/staging/terraform.tfvars**
```
chef_validation_key = "REDACTED"
chef_encrypted_data_bag_secret = "REDACTED"
...
```

After running "terraform get" and "terraform plan", we get errors about missing dependencies:

```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 4 error(s) occurred:

* module.aperture-uat-20150306: missing dependency: var.chef_encrypted_data_bag_secret
* module.aperture-uat-20150306: missing dependency: var.chef_validation_key
* module.aperture-staging-20150306: missing dependency: var.chef_encrypted_data_bag_secret
* module.aperture-staging-20150306: missing dependency: var.chef_validation_key
```

The variables are defined, without values, in the common "main.tf" and set later with the override file "terraform.tfvars". Adding the variables, without values, to local "variables.tf" or respective "*.tf" file resolves the errors, with the correct output from "terraform show". Adding those variables to the common / imported tf files won't work.

**terraform/staging/variables.tf**
```
variable "chef_validation_key" {}
variable "chef_encrypted_data_bag_secret" {}
```

**Comment by jmreicha** [comment] 2015-06-24 15:21
Running in to this issue as well.  Just bumped to 0.5.3, is there any update on this?

**Comment by mitchellh** [comment] 2015-06-24 15:22
This might actually be fixed (in master) but I'll have to re-verify.

**Comment by mitchellh** [comment] 2015-06-25 05:32
Confirmed as not fixed, working on this now.

**Comment by jmreicha** [comment] 2015-06-25 15:16
Thanks for looking at it, I tried building binaries from master with no luck so I'm glad it wasn't just me.

**Closed** 2015-06-26 00:50 UTC
Labels: bug, core
