### ISSUE TITLE
aws_elasticsearch_domain keeps reapplying 

### ISSUE THREAD

**Issue by thattommyhall** [hashicorp/terraform#5067] opened 2016-02-09 12:08 UTC
Similar to #3634 

I am using your JSON format to create the aws_elasticsearch_domain

```
"aws_elasticsearch_domain": {
  "logs": {
    "domain_name": "logs",
    "advanced_options": {
      "rest.action.multi.allow_explicit_index": true
    },
    "access_policies": "{\"Version\":\"2012-10-17\",\"Statement\":{\"Action\":\"es:*\",\"Principal\":\"*\",\"Effect\":\"Allow\",\"Condition\":{\"IpAddress\":{\"aws:SourceIp\":[\"${aws_eip.public-a-nat.public_ip}\",\"${aws_eip.public-b-nat.public_ip}\",\"${aws_eip.public-c-nat.public_ip}\"]}}}]}",
    "snapshot_options": {
      "automated_snapshot_start_hour": 23
    }
  }
}
```

It successfully creates, but every time I run it it says it is changing 

```
{
    "Statement": [{
        "Action": "es:*",
        "Condition": {
            "IpAddress": {
                "aws:SourceIp": ["52.48.255.155", "52.48.254.180", "52.48.255.154"]
            }
        },
        "Effect": "Allow",
        "Principal": "*",
        "Resource": "arn:aws:es:eu-west-1:<ID>:domain/logs/*"
    }],
    "Version": "2012-10-17"
}
```

to 

```
{
    "Statement": [{
        "Action": "es:*",
        "Condition": {
            "IpAddress": {
                "aws:SourceIp": ["52.48.255.155", "52.48.254.180", "52.48.255.154"]
            }
        },
        "Effect": "Allow",
        "Principal": "*"
    }],
    "Version": "2012-10-17"
}
```

(ie adding the 'Resource')

If I add the Resource entry after it it created then it no longer re-applies, but obviously I can't do it for creation as I dont know the ARN, also if I lookup the ARN, I get `Self reference: aws_elasticsearch_domain.logs`

This is my first mild snag in ~6 months of using Terraform, it is honestly the best new tech ive used in the last 5y, thanks!

**Comment by radeksimko** [comment] 2016-02-09 13:51
> I can't do it for creation as I dont know the ARN

I think the easiest way we can get around this would be introducing a new resource, something like `aws_elasticsearch_domain_policy` which would depend on `aws_elasticsearch_domain` and would only be responsible to setting the policy.

That way you'd be able to create the domain first and reference the ARN from created domain in the `aws_elasticsearch_domain_policy`.

It is similar pattern to the one we already use for `aws_security_group` & `aws_security_group_rule`. There are some potential issues to be aware of when using this pattern - e.g. we discourage user from setting any rules on the `_group` level when they use `group_rule`. We'd be discouraging them from using `aws_elasticsearch_domain.access_policy` if they want to use (hypothetical) `aws_elasticsearch_domain_policy` here as well.

---------

Longer term I think this will need solving in more wider context, it is also causing similar issues in most IAM policies where user needs to do a lot of self-referencing. See https://github.com/hashicorp/terraform/issues/3267

**Comment by tj** [comment] 2016-02-15 20:44
:+1: unusable right now as-is

**Comment by gposton** [comment] 2016-03-11 05:25
Moving some comments over from #3539.  Hope they're useful.

I'm seeing the same issue.... Looking at the output from the terraform apply, the access_policy is updated despite the fact that it is logically equivalent (no update should be required).

The order of the elements in the access policy json are different. Also, it looks like the Resource ARN is being automatically injected into the access_policy. That explains why terraform see's the diff and triggers the modify. It would probably work to add the resource arn to the policy in the tf template after the initial creation of the ES domain (can't add it at the initial creation because you don't know what it is until after the resource is created).

I can reproduce this on each terraform apply.

Here is the output from the terraform apply:

[ats_dependencies] access_policies: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"es:*\",\"Resource\":\"arn:aws:es:us-west-2:763429161784:domain/ats-prod/*\",\"Condition\":{\"IpAddress\":{\"aws:SourceIp\":[\"52.36.237.75/32\",\"52.32.171.250/32\",\"52.34.208.134/32\",\"50.112.131.3/32\",\"54.201.98.238/32\",\"54.69.54.64/32\",\"52.24.90.172/32\"]}}}]}" => "{\"Statement\":[{\"Action\":\"es:*\",\"Condition\":{\"IpAddress\":{\"aws:SourceIp\":[\"52.36.237.75/32\",\"52.32.171.250/32\",\"52.34.208.134/32\",\"50.112.131.3/32\",\"54.201.98.238/32\",\"54.69.54.64/32\",\"52.24.90.172/32\"]}},\"Effect\":\"Allow\",\"Principal\":\"*\"}],\"Version\":\"2012-10-17\"}"

**Comment by dvalentin** [comment] 2016-03-11 08:59
Same issue here:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
              "AWS": "${aws_iam_role.ecs_instance.arn}",
              "AWS": "${aws_iam_role.kinesis2elasticsearch.arn}"
            },
            "Action": "es:*",
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
              "AWS": "*"
            },
            "Action": "es:*",
            "Condition": {
              "IpAddress": {
                "aws:SourceIp": [
                  "${var.allowed_cidr.office}"
                ]
              }
            },
            "Resource": "*"
        }
     ]
}
`
This policy will be applied on every run (the ressources referenced in that policy, don't change that frequently) and recreates the cluster (not terraforms fault!). 
Making it an own terraform ressource might be a possible fix.

**Comment by gposton** [comment] 2016-03-29 20:47
Workaround is to put the arn in the access policy.  This can be done as the arn follows a known convention.

i.e. 

` access_policies = <<CONFIG
    {
      "Version": "2012-10-17",
      "Statement": [
      {
        "Effect": "Allow",
        "Principal": "*",
        "Action": "es:*",
        "Resource": "arn:aws:es:${var.region}:${var.aws_account_id}:domain/${var.cluster_name}-${var.environment}/*",
        "Condition": {
            "IpAddress": {
              "aws:SourceIp": [
                "${element(formatlist("%s/32", split(",", terraform_remote_state.nat.output.nat_public_ips)), 0)}",
                "${element(formatlist("%s/32", split(",", terraform_remote_state.nat.output.nat_public_ips)), 1)}",
                "${element(formatlist("%s/32", split(",", terraform_remote_state.nat.output.nat_public_ips)), 2)}",
                "${join("\",\"", formatlist("%s/32", split(",", var.source_ips)))}"
              ]
            }
          }
        }
      ]
    }
`

**Comment by rottenbytes** [comment] 2016-04-07 15:23
:+1: on introducing a `aws_elasticsearch_domain_policy` resource type

**Comment by cahlbin** [comment] 2016-04-12 13:46
+1 on introducing `aws_elasticsearch_domain_policy`

**Comment by cahlbin** [comment] 2016-04-13 13:18
I tried the workaround @gposton suggested, to inline the policy and only use predefined vars, but it seems as if terraform still re-applies the access policy on each `terraform apply`, despite the ES cluster already existing since a previous apply and no change in inline policy

**Comment by gposton** [comment] 2016-04-13 13:43
@cahlbin, take a look at the policy diff during terraform plan, and make sure the ordering of the keys in the access policy in the terraform template match what terraform is seeing in AWS.  I'm not sure if the ordering is important or not, but I have a hunch that it might be.

**Comment by daveadams** [comment] 2016-05-02 13:17
My impression from running into this in the past is that the AWS API is returning the JSON document in different equivalent orderings each time, (ie with the keys in a different order). If I run `terraform plan` a dozen times, I might be told nothing needs to change two of those twelve times, and that a change needs to happen the other ten times. The more complex the policy document, the less often `terraform plan` will appear to agree with the existing resource.

I don't think adding an `aws_elasticsearch_domain_policy` resource will help in this case, because applying the policy appears to be the operation that takes 10+ minutes to complete, and that will not change regardless of how the Terraform-side logic is structured.

Instead, I think the resource needs to stop treating the JSON as a meaningless string and applying a change when the AWS API returns a permuted variation of the original, and needs to assume AWS treats equivalent JSON documents equivalently and parse the JSON and compare the resulting data structures for equivalence.

**Comment by n8gard** [comment] 2016-05-29 01:35
I'm having this problem, too. Here is my code. This is a real bummer. I'm going to have to abandon using the ElasticSearch service and build ElasticSearch servers by hand. This makes me very, very sad at Terraform.
```
resource "aws_elasticsearch_domain" "es-elk" {
    domain_name = "es-elk-${var.environment}"
    cluster_config = {
      instance_type = "${var.es_data_node_instance_type}"
      instance_count = "${var.es_data_node_instance_count}"
      dedicated_master_enabled = true
      dedicated_master_type = "${var.es_master_node_instance_type}"
      dedicated_master_count = "${var.es_master_node_instance_count}"
      zone_awareness_enabled = true
    }

    ebs_options = {
      ebs_enabled = true
      volume_type = "gp2"
      volume_size = "${var.es_volume_size}"
    }

    advanced_options {
        "rest.action.multi.allow_explicit_index" = true
    }

    access_policies = <<CONFIG
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "es:*",
            "Principal": "*",
            "Effect": "Allow",
            "Condition": {
                "IpAddress": {
                  "aws:SourceIp": [
                    "${var.cidr_block_elk_one}",
                    "${var.cidr_block_elk_two}",
                    "${var.cidr_block_elk_three}"
                  ]
                }
            }
        }
    ]
}
CONFIG
    snapshot_options {
        automated_snapshot_start_hour = 23
    }
    tags {
      Domain = "${var.environment}"
    }
}
output "es-elk-endpoint" {
    value = "${aws_elasticsearch_domain.es-elk.endpoint}"
}
```

**Comment by briankmc** [comment] 2016-05-29 19:28
@n8gard this is fixable for me by being very careful with the ordering and formatting of `access_policies`.

This gets me a non-cycling `terraform plan` with v0.6.16:

```
resource "aws_elasticsearch_domain" "logs" {
  domain_name = "${var.name}-logs" # must match Resource in access_policies

  access_policies = <<EOF
{
  "Statement": [
    {
      "Action": "es:*",
      "Condition": {
        "IpAddress": {
          "aws:SourceIp": "127.0.0.1/32"
        }
      },
      "Effect": "Allow",
      "Principal": "*",
      "Resource": "arn:aws:es:${var.region}:${var.aws_account_number}:domain/${var.name}-logs/*"
    }
  ],
  "Version": "2012-10-17"
}
EOF

  [...]
}
```

**Comment by n8gard** [comment] 2016-05-30 19:12
@briankmc that worked! Would like to understand why but I'm happy to leave it as esoteric weirdness. Thanks!

**Comment by devinsba** [comment] 2016-10-13 18:41
Even being very careful as @briankmc suggests. If I don't add the ARN it will apply every time.

On the other hand I've added it but now run into `aws_elasticsearch_domain.es: diffs didn't match during apply.` for some reason.

I have a list with 2 statements. This only happens if I have the ARN on the first one. Essentially
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "${role_arn}"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:${region}:${account_id}:domain/${domain_name}/*"  <--- IF I ADD THIS IT FAILS
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:${region}:${account_id}:domain/${domain_name}/*",
      "Condition": {
        "IpAddress": {
          "aws:SourceIp": ${ip_json_list}
        }
      }
    }
  ]
}
```

It will modify every time if it's only on the second one. This has been a huge headache for me this week. Is #8648 still the PR that should get this done?

**Comment by daveadams** [comment] 2016-10-13 19:06
Is that your actual code? I believe you need to prefix the var names with
"var." as in:

    "Resource":
"arn:aws:es:${var.region}:${var.account_id}:domain/${var.domain_name}/*"

**Comment by devinsba** [comment] 2016-10-13 21:03
@daveadams Seems my edit wasn't fast enough to make it in the email. This was doing a rendered template. the workaround works once I remove that abstraction.

**Comment by orlando** [comment] 2016-11-17 00:07
in addition to the @briankmc workaround, there's a data resource called [aws_caller_identity](https://www.terraform.io/docs/providers/aws/d/caller_identity.html) which exposes the account_id. so you can write your resources like

```hcl
data "aws_caller_identity" "current" {}

resource "aws_elasticsearch_domain" "es" {
  domain_name = "${var.domain_name}"
  ...
  access_policies = <<CONFIG
    {
      "Statement": [
        {
          "Action": "es:*",
          "Condition": {
            "IpAddress": {
              "aws:SourceIp": ["127.0.0.1/32"]
            }
          },
          "Effect": "Allow",
          "Principal": "*",
          "Resource": "arn:aws:es:ap-southeast-1:${data.aws_caller_identity.current.account_id}:domain/${var.domain_name}/*"
        }
      ],
      "Version": "2012-10-17"
    }
  CONFIG
  ...
}
```
So you don't need to provide extra variables to get this done

**Comment by mitchellh** [comment] 2016-11-17 18:35
It _appears_ this is fixed by using data sources. If someone can get me a newer version `diff's didn't match` error then I can take a look but I have a strong suspicion that this is resolved in newer versions.

**Comment by orlando** [comment] 2016-11-17 18:46
The problem is that the resource gets reapplied, unless you specify the `"Resource"` key in your access policy. It usable with the workaround, but not sure if this is the expected behaviour

**Comment by mitchellh** [comment] 2016-11-17 19:05
@orlando Ah, I missed that, reopening.

**Closed** 2017-02-08 13:20 UTC
Labels: bug, provider/aws

**Comment by Bjorn121** [comment] 2018-02-06 09:29
I know the issue has been closed, but we are facing the same issue unfortunately.  We are using `aws_elasticsearch_domain_policy` together with `aws_iam_policy_document`.  I don't like inline JSON to construct policies, so we are using a data document

Data block
```hcl
data "aws_iam_policy_document" "ElasticSearchPolicy" {

  statement {
    effect = "Allow"

    actions = [
      "es:ESHttpPost",
      "es:ESHttpPut"
    ]

    principals {
      identifiers = [
        "${var.lambda_fcn_arn}"
      ]

      type = "AWS"
    }

    resources = [
      "${aws_elasticsearch_domain.es.arn}/*"
    ]
  }

  statement {
    effect = "Allow"

    actions = [
      "es:*"
    ]

    condition {
      test = "IpAddress"
      values = [
        "${var.list_one}",
        "${var.list_two}"
      ]

      variable = "aws:SourceIp"
    }
  }

}
```

Domain Policy
```hcl
resource "aws_elasticsearch_domain_policy" "eslogextract" {
  domain_name = "${aws_elasticsearch_domain.es.domain_name}"
  access_policies = "${data.aws_iam_policy_document.ElasticSearchPolicy.json}"
}
```

Every time we run a Terraform apply, it recreates and reapplies the policy to the ElasticSearch domain.  This takes at least 10 minutes every time we run a `terraform apply`

**Comment by willemveerman** [comment] 2018-02-08 10:17
I think this ticket has been closed prematurely.

The issue mentioned by the OP still occurs.

It seems that this ticket was closed because the Hashibot created a corresponding ticket in the **terraform-provider-aws** section. 

However, [that ticket](https://github.com/terraform-providers/terraform-provider-aws/issues/33) refers to a different issue: it's concerned with the policy change _taking a long time._

Moreover, in another [comment elsewhere](https://github.com/hashicorp/terraform/issues/3539#issuecomment-186781732) one of the Terraform teams refers a user to _this_ ticket for updates regarding the ES policy-recycling issue.

Therefore, this ticket shold be re-opened if this issue is not fixed and not covered by any other ticket.
