### ISSUE TITLE
command/meta: `terraform state mv` crashes when backend is uninitialized

### ISSUE THREAD

**Issue by cstruct** [hashicorp/terraform#13506] opened 2017-04-10 15:26 UTC
The Terraform CLI crashes with a `SIGSEGV` when trying to move a module in the state with `terraform state mv module.foo module.bar` when the backend needs initialization.

### Terraform Version
`Terraform v0.9.2`

### Debug Output
Same as [Panic Output](#Panic-Output)

### Panic Output
[crash.log](https://gist.github.com/cstruct/00fd34fd8f2d829f4e7ce36ebd0e58bc).

### Expected Behavior
module being moved from `foo` to `bar` or the CLI printing that `terraform init` needs to be run.

### Actual Behavior
Terraform crashes with `SIGSEGV`

### Steps to Reproduce
Run `terraform state mv` with any resources and a backend that needs to be initialized.

**Comment by jasonarewhy** [comment] 2017-05-02 15:45
Confirmed behavior still exists with terraform 0.9.4. Once I initialized a backend, the same state mv commands succeeded. Not exactly a blocker for me since I was in the process of migrating to backends anyway.

### Panic Output
[crash.log.zip](https://github.com/hashicorp/terraform/files/970978/crash.log.zip)

**Comment by jbardin** [comment] 2017-08-08 13:54
Closed by #15652

**Closed by jbardin** 2017-08-08 13:54 UTC
Labels: core, crash, new-remote-state
