### ISSUE TITLE
jsonencode() converts numeric values of maps nested within a ternary into strings

### ISSUE THREAD

**Issue by krarey** [hashicorp/terraform#29115] opened 2021-07-07 18:10 UTC
### Terraform Version

```
Terraform v1.0.0
on linux_amd64
```

### Expected Behavior
When evaluating the following expression, I would expect `jsonencode()` to preserve the numeric value of `quux`:

```terraform
jsonencode({
  foo = true ? {
    quux = 1
    bar  = "baz"
  } : {})
```

### Actual Behavior
The value of `quux` is converted into a string. If the ternary is removed, `quux` is appropriately parsed as an integer.

```
> jsonencode({foo = true ? { quux = 1, bar = "baz" } : {} })
"{\"foo\":{\"bar\":\"baz\",\"quux\":\"1\"}}"
> jsonencode({foo = { quux = 1, bar = "baz" }})
"{\"foo\":{\"bar\":\"baz\",\"quux\":1}}"
```

### Steps to Reproduce
This can be reproduced in `terraform console` using the sample code in the 'Actual Behavior' section above.

### References

#17033

**Comment by apparentlymart** [comment] 2021-07-07 19:00
Hi @krarey!

What you've observed here is not a behavior of `jsonencode` but rather a behavior of the Terraform language's type inference.

Specifically, Terraform needs to decide what the return type is for the conditional expression, and so it searches the space of possible types for one that both the true and false expressions can convert to. The two expressions you've given have the following types:

1. `object({quux = number, bar = string})`
2. `object({})`

Since object types are defined by their attributes, there is no possible object type that both of these could losslessly convert to. Having eliminated that option, Terraform then tries to see if there's a _map_ type that they can both convert to. I believe it's the taking the following sequence of inferences:

* An object type can only convert to a map type if all of the map elements can convert to the same type, because map types have homogenous element types.
* Type 1 includes both a `number` attribute and a `string` attribute, so Terraform must recursively try to find a common type that both can convert to in order to produce a valid map type.
* `number` can automatically convert to `string`, so `map(string)` is a candidate map type for type 1 to convert two.
* Type 2 includes no attributes at all, so it can convert to a map of _any_ element type. (In a module variable type constraint, we'd write that as `map(any)`.)
* Since `any` can be replaced by any single type, these two candidate map types are both compatible with `map(string)` and so Terraform selects that as the final type resulting from the conditional expression.

I confirmed that this behavior is coming from the conditional operator rather than from `jsonencode` by evaluating the conditional expression alone:

```
> {foo = true ? { quux = 1, bar = "baz" } : {} }
{
  "foo" = tomap({
    "bar" = "baz"
    "quux" = "1"
  })
}
```

Notice that the result here is a map (denoted by `tomap(...)` in the string representation), which confirms my hypothesis above that Terraform is inferring the condition result type as a map of strings. The `jsonencode` conversion rules convert both object types and map types into JSON objects, so that distinction is not typically important for JSON encoding, but it _does_ affect the result in this case because `jsonencode` _does_ differentiate between strings and numbers.

So with all of this said, Terraform is unfortunately behaving as intended here, though I can see that the Terraform language type inference rules are not an ideal fit for the specific problem of generating JSON here. Although the types in Terraform's type system are a superset of JSON, the inference rules are designed primarily to support Terraform's job of producing a correct plan even when some values are not known, and so generating JSON strings is a secondary use-case that won't always be as straightforward as we might like.

It seems like your underlying goal here was to conditionally produce an empty object. If so, I'd suggest the following as a different approach that should work within the type inference rules:

```
> jsonencode({ for k, v in { quux = 1, bar = "baz" } : k => v if true })
"{\"bar\":\"baz\",\"quux\":1}"
> jsonencode({ for k, v in { quux = 1, bar = "baz" } : k => v if false })
"{}"
```

This is a considerably more verbose expression and so is certainly not ideal, but unfortunately this sort of quirk is an inevitable artifact of conversions between different type systems: there will always be edges that don't line up quite right and require some unusual approaches. There might be other ways to get the result you want with less verbosity using some of the Terraform language built-in functions.

Since Terraform is behaving as designed here (and the type inference behavior in question is covered by the [v1.0 compatibility promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html) and thus fixed in its current form), I'm going to close this. I hope the above suggestion helps you get the result you needed. If you have any follow-up questions about this, feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where I'm happy to help work through other related requirements. Thanks!

**Closed by apparentlymart** 2021-07-07 19:00 UTC
Labels: bug, new
