### ISSUE TITLE
Add Support for User Defined Types

### ISSUE THREAD

**Issue by JonathonAnderson** [hashicorp/terraform#32101] opened 2022-10-27 13:30 UTC
### Terraform Version

```shell
Terraform v1.2.6
```

### Use Cases

Large projects with a well-constructed modular design, with potentially many layers of module calls, tend to require large amounts of metadata. Specifying a variable for every piece of metadata is sufficient but can be difficult to read if the number of inputs becomes significant. Custom object types can be useful for creating a JSON type data structure that can contain all of the metadata needed for that module, but if the module is several layers deep, it requires the same object structure to be declared in each parent module. Any updates to the child module inputs requires a change to the data structure in all parent modules, which can make maintenance an initial development difficult.

### Attempted Solutions

This is our top-level data model. It enables us to pass all metadata into our product modules as a single entity. Each major nested data structure is related to a child module with potentially more than one layer of depth. For example, the DNS module we use calls an internal and external DNS child module to handle certain configurations differently. The DNS data structure below needs to be replicated and maintained in the top-level module, the DNS module, the internal module, and the external module. Even within the top level and DNS module, the entire DNS data structure needs to be repeated for the external and internal portion of the structure.

```
variable product {
  type = map(list(object({
    bcdr               = bool
    environment        = string
    serial             = string
    criticality        = string
    az-subscription-id = string
    az-region          = string
    aws-region         = string
    created-by         = string
    create-date        = string
    
    network = object({
      dmz = object({
        address-space = string
        created-by    = string
        create-date   = string
        
        subnets = list(object({
          name = string
          address-prefix = string
        }))
      })
      core = object({
        address-space = string
        created-by    = string
        create-date   = string
        
        subnets = list(object({
          name = string
          address-prefix = string
        }))
      })
    })

    dns = object({
      external = object({
        zone        = string
        created-by  = string
        create-date = string

        mx = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          hosts = list(object({
            preference = number
            exchange   = string
          }))
        }))

        txt = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          values = list(string)
        }))

        a = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          ips = list(string)
        }))

        cname = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          cname = string
        }))
      })

			
      internal   = object({
        zone        = string
        created-by  = string
        create-date = string

        mx = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          hosts = list(object({
            preference = number
            exchange   = string
          }))
        }))

        txt = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          values = list(string)
        }))

        a = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          ips = list(string)
        }))

        cname = list(object({
          normal-ops    = bool
          bcdr-ops      = bool
          name          = string
          ttl           = string
          start-date    = string
          modified-date = string
          created-by    = string
          modified-by   = string

          cname = string
        }))
      })
    })
  })))
```

### Proposal

Support user defined types that can be referenced in other types and variable declarations. This way, we can define and maintain the type in one location, and have the benefit of a consistent data model throughout the application.

```
variable product {
  type = map(list(object({
    bcdr               = bool
    environment        = string
    serial             = string
    criticality        = string
    az-subscription-id = string
    az-region          = string
    aws-region         = string
    created-by         = string
    create-date        = string

    network = network_type
    dns     = {
      external = dns_type
      internal = dns_type
    }
  })))
}
    
type network_type {
  definition = object({
    dmz = object({
      address-space = string
      created-by    = string
      create-date   = string
      
      subnets = list(object({
        name = string
        address-prefix = string
      }))
    })
    core = object({
      address-space = string
      created-by    = string
      create-date   = string
      
      subnets = list(object({
        name = string
        address-prefix = string
      }))
    })
  })
}

type dns_type {
  definition = object({
    zone        = string
    created-by  = string
    create-date = string

    mx = list(object({
      normal-ops    = bool
      bcdr-ops      = bool
      name          = string
      ttl           = string
      start-date    = string
      modified-date = string
      created-by    = string
      modified-by   = string

      hosts = list(object({
        preference = number
        exchange   = string
      }))
    }))

    txt = list(object({
      normal-ops    = bool
      bcdr-ops      = bool
      name          = string
      ttl           = string
      start-date    = string
      modified-date = string
      created-by    = string
      modified-by   = string

      values = list(string)
    }))

    a = list(object({
      normal-ops    = bool
      bcdr-ops      = bool
      name          = string
      ttl           = string
      start-date    = string
      modified-date = string
      created-by    = string
      modified-by   = string

      ips = list(string)
    }))

    cname = list(object({
      normal-ops    = bool
      bcdr-ops      = bool
      name          = string
      ttl           = string
      start-date    = string
      modified-date = string
      created-by    = string
      modified-by   = string

      cname = string
    }))
  })
}
```

**Comment by jbardin** [comment] 2022-10-27 13:49
Duplicate of #27365

**Closed by jbardin** 2022-10-27 13:49 UTC
Labels: enhancement, new
