### ISSUE TITLE
Terraform v0.14 sensitive variables don't work with template_file

### ISSUE THREAD

**Issue by dghubble** [hashicorp/terraform#27342] opened 2020-12-19 00:59 UTC
### Terraform Version

```
v0.14.3
```

### Terraform Configuration Files

```tf
variable "foo" {
  type = string
  default = "foo"
  sensitive = true
}

data "template_file" "bar" {
  template = file("hello.tmpl")
  vars = {
    foo = var.foo
  }
}
```

### Expected Behavior

Template sensitive foo into the data resource.

### Actual Behavior

```
Error: .vars["foo"]: value has marks, so it cannot be serialized
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

I'm aware there is a `templatefile` expression. We've avoided adopting it since its less readable getting it to work with `count` and `template_file` as a data provider is nicer. Although it looks like `templatefile` has its own bug https://github.com/hashicorp/terraform/issues/27336

### Reference

I've seen the many sensitive variables issues and was hoping this was solved in v0.14.3 but not so.

**Comment by alisdair** [comment] 2020-12-19 04:17
I think this is essentially a duplicate of #27333 and will be fixed by the corresponding PR.

**Comment by fatbasstard** [comment] 2020-12-21 13:42
We've got the same issue, but without the variables being marked as "sensitive"

**Comment by schaebo** [comment] 2020-12-21 14:47
This also happens if the values are stored as sensitive vars in Terraform Cloud.

**Comment by fatbasstard** [comment] 2020-12-21 15:17
@schaebo That might explain the error we got.

Validated and can confirm that.

**Comment by TjeuKayim** [comment] 2020-12-23 13:57
I can confirm that building #27335 from source resolves this issue for me. Thanks for the fix!

**Closed** 2021-01-04 18:53 UTC
Labels: bug, confirmed
