### ISSUE TITLE
1.6.0 terraform init reports Permission denied (publickey) on module download from gitHub

### ISSUE THREAD

**Issue by marounik** [hashicorp/terraform#34015] opened 2023-10-06 21:57 UTC
### Terraform Version

```shell
latest/1.6.0
```

### Terraform Configuration Files

N/A

### Debug Output

Could not download module "tribe_vpc" (main.tf:1) source code from
│ "git::ssh://git@github.com/myEnterprise/MyRepo.git?ref=v0.2.4":
│ error downloading
│ 'ssh://git@github.com/myEnterprise/MyRepo.git?ref=v0.2.4':
│ /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/tribe_vpc'...
│ git@github.com: Permission denied (publickey).
│ fatal: Could not read from remote repository.
│ 
│ Please make sure you have the correct access rights
│ and the repository exists.

### Expected Behavior

We are invoking terraform via GitHub actions where we use following installation step (installing latest version):

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
...
      - name: Terraform Install
        id: terraform-install
        uses: hashicorp/setup-terraform@v2

We have a terraform code refers a module on another gitHub repo in following format:
module "tribe_vpc" {
  source = "git@github.com:myEnterprise/MyRepo.git//?ref=v0.2.4"
  ...
}

We expect to module download to succeed

### Actual Behavior

Everything worked properly until 3 days ago, when new version 1.6.0 was published terraform init started to fail on module download

Could not download module "tribe_vpc" (main.tf:1) source code from
│ "git::ssh://git@github.com/myEnterprise/MyRepo.git?ref=v0.2.4":
│ error downloading
│ 'ssh://git@github.com/myEnterprise/MyRepo.git?ref=v0.2.4':
│ /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/tribe_vpc'...
│ git@github.com: Permission denied (publickey).
│ fatal: Could not read from remote repository.
│ 
│ Please make sure you have the correct access rights
│ and the repository exists.

Changing back/pinning terraform to version 1.4.7 fixed the issue:
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
...
      - name: Terraform Install
        id: terraform-install
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.7

### Steps to Reproduce

terraform init

### Additional Context

N/A

**Comment by crw** [comment] 2023-10-06 22:29
Is it possible this is a duplicate of https://github.com/hashicorp/terraform/issues/33985? Thanks!

**Comment by ryandiamond23** [comment] 2023-10-09 14:24
Seeing the same when using terraform:1.6.0 Docker image, looks to be some change in SSH configs. Pinning version to 1.5.7 image resolves the issue.

**Comment by crw** [comment] 2023-10-09 20:14
I believe this is a duplicate of #33985. Please let me know if you think this is in error.

**Closed by crw** 2023-10-09 20:14 UTC
Labels: bug, waiting-response, new
