### ISSUE TITLE
Invalid count argument: migration from 0.12 to 0.13.5

### ISSUE THREAD

**Issue by alk-rniveau** [hashicorp/terraform#26909] opened 2020-11-13 09:34 UTC
### Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.35.0
+ provider registry.terraform.io/hashicorp/dns v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files
```terraform
resource "azurerm_network_interface_application_security_group_association" "vm-if-asg-association-additionnal" {
  count                         = var.azure_asg.asg != null ? var.countvm : 0
  network_interface_id          = element(azurerm_network_interface.vm-if.*.id, count.index)
  application_security_group_id = var.azure_asg.asg.id
}

variable "azure_asg" {
  description = "Module asg"
  type = object({
    asg = object({
      id = string
    })
  })
  default = { asg = null }
}
```

### Expected Behavior
With 0.12.29 version, this code worked fine. I did the migration to 0.13.5 version and now I can't apply this code.

### Actual Behavior
I get the following error:

Error: Invalid count argument

  on modules/vm/network.tf line 52, in resource "azurerm_network_interface_application_security_group_association" "vm-if-asg-association-additionnal":
  52:   count                         = var.azure_asg.asg != null ? var.countvm : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

### Additional Context
I migrate a existant state from 0.12 to 0.13, so every resources already exist.

**Comment by jbardin** [comment] 2020-11-13 13:24
Hi @alk-rniveau 

Sorry you're having trouble with the migration. In order to help here we would need a more complete example. One of the variables in the `count` expression is unknown during plan, but we need to see all the inputs to know why. 

If you can replicate the issue, or provide the full config and logs we may be able to narrow down the problem. If you have an environment where you can test this, the latest 0.14 pre-release may be beneficial to try, as it will be more forgiving of misbehaving data sources that can cause this type of problem. 

Thanks!

**Comment by alk-rniveau** [comment] 2020-11-13 13:49
Not sure it's enough, here is the full output of the apply:

https://gist.github.com/alk-rniveau/b3e2b5e29e8d174ac7ab1eab77a4e1bd

the azure_asg variable come from another module:

```
  azure_asg           = module.asg-alk-services
```

which look like this:

```terraform
resource "azurerm_application_security_group" "asg" {
  count               = var.enable ? 1 : 0
  name                = "${var.workspace_config.prefix}-${var.name}"
  location            = var.workspace_config.location
  resource_group_name = var.azure_rg_name

  tags = {
    env = var.workspace_config.env
  }
}
```

**Comment by jbardin** [comment] 2020-11-13 14:20
Unfortunately that isn't enough to reproduce the issue. It appears all the changes have 2 variables in common though, `var.load_balancer_private.backend_address_pool` and `var.azure_asg.asg`. If there are any changes being planned for the resources referenced by those variables, they would not be valid arguments for `count` or `for_each`. You may be able to make more targeted changes to the config and update those resources that are causing the issue.

Because `count` and `for_each` must be known during planning, they should not contain references to managed resources. This can of course cause the situation you have shown here, but also prevent you from applying the configuration from scratch when those resources have yet to be created.

**Comment by apparentlymart** [comment] 2020-11-16 22:01
Hi @alk-rniveau,

As @jbardin noted, we can't really tell what's going on from the information you've shared so far. However, I'm going to try some deduction based on what you've shared because I suspect the error message you've seen here is not actually the root cause of the problem, but rather just a symptom of the problem.

I'm having to guess a little because I can't see your full configuration, but I'm assuming that `var.azure_asg.asg` is derived from `module.vm-vpn.module.vm-asg.azurerm_application_security_group.asg[0]`, just because I don't see any other application security groups mentioned in the log output.

The error message suggests that the value of `var.azure_asg.asg` isn't known during planning, which in turn suggests that `module.vm-vpn.module.vm-asg.azurerm_application_security_group.asg[0]` isn't known either. One reason why that could be true is if the Azure provider has detected a change to `azurerm_application_security_group.asg[0]` that requires it to be replaced, but we can't easily tell that's true because the error message is preventing us from seeing the plan output for that resource.

With all of that said, you may be able to get closer to the underlying cause here by running `terraform plan` with the `-target` argument so that Terraform will not try to plan the `azurerm_network_interface_application_security_group_association` resource:

```shellsession
terraform plan -target=module.vm-vpn.module.vm-asg.azurerm_application_security_group.asg
```

If my theory is correct then this will either produce a different error message or will produce a plan to replace that ASG object. If you try this and can share the output in full, that will hopefully get closer to the root cause.

**Comment by alk-rniveau** [comment] 2020-11-18 10:28
Arf unfortunately, your theory seem wrong

```bash
terraform plan -target=module.vm-vpn.module.vm-asg.azurerm_application_security_group.asg

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.vm-vpn.azurerm_resource_group.vm-rg[0]: Refreshing state... [id=/subscriptions/-id-/resourceGroups/ppr-aew-vpn]
module.vm-vpn.module.vm-asg.azurerm_application_security_group.asg[0]: Refreshing state... [id=/subscriptions/-id-/resourceGroups/ppr-aew-vpn/providers/Microsoft.Network/applicationSecurityGroups/ppr-aew-vpn]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by apparentlymart** [comment] 2020-11-18 22:11
Thanks for trying that, @alk-rniveau.

The cause you've identified is surprising to me, because the `length(...)` for a resource should always be known at plan time for the same reason that an unknown `count` or `for_each` isn't allowed.

Can you say a little more about how you determined this as the cause? We still need to find a reproduction case for this, which means we need to figure out which parts of your setup are important for the behavior you've seen.

**Comment by alk-rniveau** [comment] 2020-11-19 08:17
> Can you say a little more about how you determined this as the cause?
You know monkey coding :) . I tried to solve my issue by looking the code. I saw this line and I said to myself "maybe it's that", I have removed the length and 🎉

Here is my asg module:

```terraform
resource "azurerm_application_security_group" "asg" {
  count               = var.enable ? 1 : 0
  name                = "${var.workspace_config.prefix}-${var.name}"
  location            = var.workspace_config.location
  resource_group_name = var.azure_rg_name
}

output "asg" {
  value = var.enable ? azurerm_application_security_group.asg[0] : null # here was the length()
}

variable "name" {
  description = "Name"
  type        = string
}

variable "azure_rg_name" {
  description = "Resource group name"
  type        = string
}

variable "enable" {
  description = "Enable this Application Security Group"
  type        = bool
  default     = true
}

variable "workspace_config" {
  description = "Generic config for current workspace"
  type = object({
    alk_env  = string
    location = string
    prefix   = string
  })
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

```


Here is an failing example:

```terraform
module "asg-elasticsearch7" {
  source = "./modules/asg"

  name          = "elasticsearch7"
  azure_rg_name = module.network.rg_name

  enable = lookup(
    {
      "ppr" = false # we do a lookup to know the configuration according the workspace, so for ppr env, we don't have the asg, for others yes
    },
    local.workspace["env"],
    true
  )

  workspace_config = local.workspace
}

module "vm-elasticsearch7-master" {
  source = "./modules/vm"

  profile             = "elasticsearch7-master"
  azure_instance_size = "Standard_D1_v2"
  azure_asg           = module.asg-elasticsearch7
  ansible_groups      = ["elasticsearch7"]

  countvm = lookup(
    {
      "ppr" = 0
    },
    local.workspace["env"],
    3,
  )
}```

**Comment by ChristophShyper** [comment] 2020-12-02 17:12
My simplest example that stopped working after migration to 0.13 is following.
```terraform
data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_default_subnet" "default" {
  count    = length(data.aws_availability_zones.available.names)

  availability_zone       = data.aws_availability_zones.available.names[count.index]
}
```

This error is happening every time I change `source` parameter for Terragrunt, e.g. changing the branch of the module.
After running `apply -target=data.aws_availability_zones.available` it's fixed until I change revision branch again.

**Comment by ChristophShyper** [comment] 2020-12-03 10:33
As it happens often lately most important information can be found in other issues rather than in documentation.
According to https://github.com/hashicorp/terraform/issues/26078#issuecomment-710060287 they abandoned this functionality with 0.13
```
With how Terraform works at present, we consider this sort of configuration to be incorrect. 
Using resource computed outputs as arguments to count and for_each is not recommended. 
Instead, using variables or derived local values which are known at plan time is the preferred approach. 
If you choose to go ahead with using computed values for count/for_each, this will sometimes require you to work around this using -target as illustrated above.
```

**Comment by hgontijo** [comment] 2021-01-22 16:40
Facing the same issue. Our use case is a dependency on data object, which in same cases has 0 entries and it fails.
Running apply -target on the data object does not help when it has count 0.

```
data "template_file" "tenant_and_namespace_pairs_template" {
  count = length(var.namespaces)

  template = join(
    format("=%s\n", var.namespaces[count.index]["namespace"]),
    concat(split(",", var.namespaces[count.index]["tenants"]), [""]),
  )
}

locals {
  tenant_and_namespace_pairs = compact(
    split(
      "\n",
      join(
        "\n",
        data.template_file.tenant_and_namespace_pairs_template.*.rendered,
      ),
    ),
  )
}

resource "kubernetes_role_binding" "namespace-tenant-rbac" {
  count = length(local.tenant_and_namespace_pairs)

  metadata {
    namespace = trimspace(
      element(split("=", local.tenant_and_namespace_pairs[count.index]), 1),
    )
    name = "tenant-${trimspace(
      element(split("=", local.tenant_and_namespace_pairs[count.index]), 0),
    )}-binding"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Role"
    name      = "tenant"
  }

  subject {
    kind = "Group"
    name = "tenant:${trimspace(
      element(split("=", local.tenant_and_namespace_pairs[count.index]), 0),
    )}"
    api_group = "rbac.authorization.k8s.io"
  }
}
```

**Comment by jbardin** [comment] 2021-04-01 19:56
The original issue here appears to have been resolved, so I'm going to close this out.

@hgontijo, Without complete configuration we cannot figure out what may be going wrong there. If you're still having a problem or have questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-04-01 19:56 UTC
Labels: bug, v0.13, waiting for reproduction
