### ISSUE TITLE
Terraform apply crash on deployment

### ISSUE THREAD

**Issue by AaronSaikovski** [hashicorp/terraform#28484] opened 2021-04-22 09:47 UTC
[crash.417636260.log.zip](https://github.com/hashicorp/terraform/files/6357268/crash.417636260.log.zip)

### Terraform Version

```
Terraform v0.15.0
on darwin_arm64
```

### Terraform Configuration Files

```terraform
terraform {
  #backend "pg" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.40"
    }
  }
}

provider "azurerm" {
  features {}
}
```

**Comment by AaronSaikovski** [comment] 2021-04-22 09:48
added crash report

**Comment by jbardin** [comment] 2021-04-22 13:00
Duplicate of #28370

**Closed by jbardin** 2021-04-22 13:00 UTC
Labels: bug, new
