### ISSUE TITLE
terraform init/plan updated remote state 

### ISSUE THREAD

**Issue by shuynh** [hashicorp/terraform#25750] opened 2020-08-05 14:21 UTC
### Terraform Version

```
0.12.2
(attempting to upgrade to 0.12.29)
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

```
 Error: state snapshot was created by Terraform v0.12.24, which is newer than current v0.12.2; upgrade to Terraform v0.12.24 or greater to work with this state
```
### Expected Behavior

Terraform init/plan should not update remote state?

### Actual Behavior

Running `terraform init` locally with a newer version of terraform updated the remote state.

### Steps to Reproduce

We're currently on Terraform 0.12.2 and are trying to upgrade to 0.12.29. Here's what i did locally -- 
1. using `tfswitch`, switch to terraform 0.12.29
2. `terraform init`
3. fix deprecation warnings and errors (interpolation-only expressions, etc) 
4. `terraform init` with no errors (yay!) 

Our Jenkins instance runs 0.12.2, and is now producing this error on terraform runs --
```
Error: state snapshot was created by Terraform v0.12.24, which is newer than current v0.12.2; upgrade to Terraform v0.12.24 or greater to work with this state
```

### References

https://github.com/hashicorp/terraform/issues/23697

**Comment by jbardin** [comment] 2020-08-08 15:23
Hi @shuynh 

Thanks for reporting this. Is it possible for you to restore the state and try this again? The error message does match the steps you’ve provided, since the reported state version is v0.12.24, and not v0.12.29. This looks like another process updated the state to v0.12.24 and it isn’t the result of the init and plan with v0.12.29.

**Comment by shuynh** [comment] 2020-08-10 14:59
@jbardin ah yeah this was what was weird about it -- `init` seemed to upgrade everything to v0.12.24 (not 0.12.29). 
i ran `terraform init` with v0.12.29 and then fixed all of the syntax/interpolation errors. jenkins running v0.12.2 was what produced the errors. i've checked and re-checked all my files and settings and can't seem to figure out what happened. let me know if you need more details!

**Comment by jbardin** [comment] 2020-09-23 22:08
I'm going to close this out for now since we don't have a reproduction.
If this occurs again with a current release, please feel free to add the reproduction case.

Thanks!

**Closed by jbardin** 2020-09-23 22:08 UTC
Labels: bug, v0.12, waiting for reproduction
