### ISSUE TITLE
Crash while releasing state lock

### ISSUE THREAD

**Issue by richard-viney** [hashicorp/terraform#24971] opened 2020-05-16 08:25 UTC
## Terraform Version
```
Terraform v0.12.25
```

### Crash Output
```
...
...
Releasing state lock. This may take a few moments...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1c53490]

goroutine 1393 [running]:
github.com/hashicorp/terraform/backend/remote.(*Remote).retryLogHook(0xc000401e40, 0x1, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/remote/backend.go:492 +0x90
github.com/hashicorp/go-tfe.(*Client).retryHTTPBackoff(0xc00051c540, 0x5f5e100, 0x17d78400, 0x1, 0x0, 0xc0015e47e0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-tfe@v0.3.27/tfe.go:252 +0xd3
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc00041c7e0, 0xc0013482c0, 0xc000044108, 0x1, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.5.2/client.go:440 +0x1c4
github.com/hashicorp/go-tfe.(*Client).do(0xc00051c540, 0x3037ac0, 0xc000044108, 0xc0013482c0, 0x2691c00, 0xc000fc0000, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-tfe@v0.3.27/tfe.go:427 +0x16e
github.com/hashicorp/go-tfe.(*workspaces).Unlock(0xc0001b6148, 0x3037ac0, 0xc000044108, 0xc000158800, 0x13, 0xc000f0a640, 0x10, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-tfe@v0.3.27/workspace.go:539 +0x195
github.com/hashicorp/terraform/backend/remote.(*remoteClient).Unlock(0xc0006d2280, 0xc000562600, 0x24, 0x4e02870, 0xc0006d2280)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/remote/backend_state.go:153 +0x209
github.com/hashicorp/terraform/state/remote.(*State).Unlock(0xc00041c480, 0xc000562600, 0x24, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/state/remote/state.go:223 +0xc3
github.com/hashicorp/terraform/command/clistate.(*locker).Unlock.func1(0x1058ec1, 0x422ae20)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/clistate/state.go:142 +0x45
github.com/hashicorp/terraform/helper/slowmessage.Do.func1(0xc00041c2a0, 0xc000fce060)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/helper/slowmessage/slowmessage.go:20 +0x27
created by github.com/hashicorp/terraform/helper/slowmessage.Do
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/helper/slowmessage/slowmessage.go:19 +0x77
```

I'm not sure how best to redact the `crash.log` or what potentially sensitive information it in fact contains.

### Expected Behavior

No crash.

### Actual Behavior

Crash.

### Steps to Reproduce
This issue did not reproduce. I think the trigger could have been that I closed the lid on my MacBook Pro while the state lock was being released, but am not certain of this.

The Terraform state in question is stored in Terraform Cloud, and it was not updated to correctly reflect the Terraform apply that was run.

Terraform was running on macOS 10.15.4.

**Comment by danieldreier** [comment] 2020-05-18 21:58
@richard-viney thanks for reporting this. We take crashes pretty seriously, but it's effectively impossible to fix a crash without a reproduction case.

I'm going to close this for now because without a reproduction case, and without even being able to reproduce it on your side, there's nothing we can do. If you run into this more, or think you can come up with a reproduction case, feel free to reach out at ddreier@hashicorp.com and we can re-open this.

**Closed by danieldreier** 2020-05-18 21:58 UTC
