### ISSUE TITLE
Vague error message "This value does not have any indices." such as when indexing into a set

### ISSUE THREAD

**Issue by finnbear** [hashicorp/terraform#26366] opened 2020-09-24 17:03 UTC
### Terraform Version

```
Terraform v0.12.23

Your version of Terraform is out of date! The latest version
is 0.13.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files
```terraform
resource "aws_route53_record" "cert" {
  name = aws_acm_certificate.main.domain_validation_options[0].resource_record_name
  type = aws_acm_certificate.main.domain_validation_options[0].resource_record_type
  records = [aws_acm_certificate.main.domain_validation_options[0].resource_record_value]
  ttl = 900
  zone_id = aws_route53_zone.main.id
}

// Fixed (took a while to figure out)
resource "aws_route53_record" "cert" {
  name = tolist(aws_acm_certificate.main.domain_validation_options).0.resource_record_name
  type = tolist(aws_acm_certificate.main.domain_validation_options).0.resource_record_type
  records = [tolist(aws_acm_certificate.main.domain_validation_options).0.resource_record_value]
  ttl = 900
  zone_id = aws_route53_zone.main.id
}
```

### Expected Behavior
```
Error: Invalid index

  on route53.tf line 46, in resource "aws_route53_record" "cert":
  46:   records = [aws_acm_certificate.main.domain_validation_options[0].resource_record_value]

This value (a set of objects) does not have any indices.
```
Or make it possible to index into a set without error

### Actual Behavior
```
Error: Invalid index

  on route53.tf line 46, in resource "aws_route53_record" "cert":
  46:   records = [aws_acm_certificate.main.domain_validation_options[0].resource_record_value]

This value does not have any indices.
```

### Steps to Reproduce
1. Create an acm certificate with DNS validation
2. Use the above configuration to create a route53 record
3. `terraform apply`
### Additional Context
The above config worked until yesterday in 3 other projects.

**Comment by alisdair** [comment] 2020-09-24 20:10
Hi @finnbear, thanks for reporting!

This looks like a duplicate of #26043. Reproducing [my comment for more details on what's going on here](https://github.com/hashicorp/terraform/issues/26043#issuecomment-683119243) below:

---

I believe the change was part of the 3.0.0 release of the AWS provider. [The change in the provider is documented in this very detailed comment from @bflad](https://github.com/terraform-providers/terraform-provider-aws/issues/10098#issuecomment-663562342):

> The `domain_validation_options` attribute is now a `set` type and the resource will attempt to populate the information necessary during the planning phase to handle the above situation in most environments without workarounds. This change also prevents Terraform from showing unexpected differences if the API returns the results in varying order.
> 
> Configuration references to this attribute will likely require updates since sets cannot be indexed (e.g. `domain_validation_options[0]` or the older `domain_validation_options.0.` syntax will return errors). If the `domain_validation_options` list previously contained only a single element like the two examples just shown, it may be possible to wrap these references using the `tolist()` function (e.g. `tolist(aws_acm_certificate.example.domain_validation_options)[0])` as a quick configuration update, however given the complexity and workarounds required with the previous `domain_validation_options` attribute implementation, different environments will require different configuration updates and migration steps.

There are some examples of how to migrate your configuration to adjust to this change in behaviour in the linked comment. If those don't quite meet your needs, I would recommend [posting a question in the discussion forum](https://discuss.hashicorp.com/c/terraform-core/27) for further assistance.

**Closed by alisdair** 2020-09-24 20:10 UTC
Labels: bug, new
