### ISSUE TITLE
Terraform deployment failing in Azure DevOps

### ISSUE THREAD

**Issue by rtk888** [hashicorp/terraform#26981] opened 2020-11-19 16:08 UTC
In the configuration, certain variables' values are specified in Azure DevOps. A storage account and a container will be created using PowerShell via Azure DevOps release pipelines.

By running the below Terraform code in Azure DevOps, I am able to create a resource group, storage account and a container. Deployment fails during the  <terraform init> step. 

### Terraform Version
```
 0.12.3
```

### Terraform Configuration Files
```
terraform {
     required_version = ">=0.12"
backend "azurerm" {
     storage_account_name = "_terraformstorageaccount_"
     container_name       = "terraform"
     key                  = "terraform.tfstate"
access_key = "_storagekey_"
}     
}
provider "azurerm" {
     version= "=2.0.0"
features {}     
}
resource "azurerm_resource_group" "test" {
     name = "PULTerraform"
     location = "Central Canada"
}
resource "azurerm_app_service_plan" "test" {
    name        ="_appserviceplan_"
    location    = azurerm_resource_group.test.location
    resource_group_name = azurerm_resource_group.test.name

    sku {
        tier = "Free"
        size = "F1"
    }
}
```

### Error

```
2020-11-19T16:02:40.6144961Z The Terraform configuration must be valid before initialization so that
2020-11-19T16:02:40.6145794Z Terraform can determine which modules and providers need to be installed.[0m[0m
2020-11-19T16:02:40.6146241Z [31m
2020-11-19T16:02:40.6146648Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6146968Z 
2020-11-19T16:02:40.6147302Z [0m  on webapp.tf line 7, in terraform:
2020-11-19T16:02:40.6147756Z    7: [4m[0m
2020-11-19T16:02:40.6148054Z [0m   8: [4m[0m
2020-11-19T16:02:40.6148313Z [0m
2020-11-19T16:02:40.6148707Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6149761Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6150328Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6151037Z [0m[0m
2020-11-19T16:02:40.6151395Z [31m
2020-11-19T16:02:40.6152805Z [1m[31mError: [0m[0m[1mInvalid string literal[0m
2020-11-19T16:02:40.6153171Z 
2020-11-19T16:02:40.6153600Z [0m  on webapp.tf line 7, in terraform:
2020-11-19T16:02:40.6154024Z    7: [4m[0m
2020-11-19T16:02:40.6154331Z [0m   8: [4m[0m
2020-11-19T16:02:40.6154666Z [0m
2020-11-19T16:02:40.6155017Z This item is not valid in a string literal.
2020-11-19T16:02:40.6155408Z [0m[0m
2020-11-19T16:02:40.6155658Z [31m
2020-11-19T16:02:40.6156040Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6156423Z 
2020-11-19T16:02:40.6156788Z [0m  on webapp.tf line 8, in terraform:
2020-11-19T16:02:40.6157208Z    8: [4m[0m
2020-11-19T16:02:40.6157898Z [0m   9: [4m[0m
2020-11-19T16:02:40.6158206Z [0m
2020-11-19T16:02:40.6158699Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6159472Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6160012Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6160346Z [0m[0m
2020-11-19T16:02:40.6160596Z [31m
2020-11-19T16:02:40.6161143Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6161479Z 
2020-11-19T16:02:40.6161836Z [0m  on webapp.tf line 9, in terraform:
2020-11-19T16:02:40.6162260Z    9: [4m[0m
2020-11-19T16:02:40.6162564Z [0m  10: [4m[0m
2020-11-19T16:02:40.6162850Z [0m
2020-11-19T16:02:40.6163265Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6163861Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6164393Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6164715Z [0m[0m
2020-11-19T16:02:40.6164983Z [31m
2020-11-19T16:02:40.6165409Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6167334Z 
2020-11-19T16:02:40.6168171Z [0m  on webapp.tf line 10, in terraform:
2020-11-19T16:02:40.6168519Z   10: [4m[0m
2020-11-19T16:02:40.6168798Z [0m  11: [4m[0m
2020-11-19T16:02:40.6169037Z [0m
2020-11-19T16:02:40.6169399Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6240653Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6241233Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6241656Z [0m[0m
2020-11-19T16:02:40.6241903Z [31m
2020-11-19T16:02:40.6242289Z [1m[31mError: [0m[0m[1mInvalid string literal[0m
2020-11-19T16:02:40.6242690Z 
2020-11-19T16:02:40.6243034Z [0m  on webapp.tf line 10, in terraform:
2020-11-19T16:02:40.6243457Z   10: [4m[0m
2020-11-19T16:02:40.6243748Z [0m  11: [4m[0m
2020-11-19T16:02:40.6244003Z [0m
2020-11-19T16:02:40.6244694Z This item is not valid in a string literal.
2020-11-19T16:02:40.6246032Z [0m[0m
2020-11-19T16:02:40.6246351Z [31m
2020-11-19T16:02:40.6246698Z [1m[31mError: [0m[0m[1mInvalid block definition[0m
2020-11-19T16:02:40.6246995Z 
2020-11-19T16:02:40.6247365Z [0m  on webapp.tf line 11, in terraform:
2020-11-19T16:02:40.6248074Z    7: [4m[0m
2020-11-19T16:02:40.6248369Z [0m   8: [4m[0m
2020-11-19T16:02:40.6248677Z [0m   9: [4m[0m
2020-11-19T16:02:40.6248952Z [0m  10: [4m[0m
2020-11-19T16:02:40.6249343Z [0m  11:      version= "[4m=[0m2.0.0"
2020-11-19T16:02:40.6249634Z [0m
2020-11-19T16:02:40.6250025Z The equals sign "=" indicates an argument definition, and must not be used
2020-11-19T16:02:40.6250439Z when defining a block.
2020-11-19T16:02:40.6250736Z [0m[0m
2020-11-19T16:02:40.6250967Z [31m
2020-11-19T16:02:40.6251316Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6251700Z 
2020-11-19T16:02:40.6252956Z [0m  on webapp.tf line 11, in terraform:
2020-11-19T16:02:40.6253341Z   11: [4m[0m
2020-11-19T16:02:40.6253678Z [0m  12: [4m[0m
2020-11-19T16:02:40.6253952Z [0m
2020-11-19T16:02:40.6254417Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6254884Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6255274Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6255576Z [0m[0m
2020-11-19T16:02:40.6255765Z [31m
2020-11-19T16:02:40.6257019Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6257315Z 
2020-11-19T16:02:40.6257911Z [0m  on webapp.tf line 12, in terraform:
2020-11-19T16:02:40.6258276Z   12: [4m[0m
2020-11-19T16:02:40.6258617Z [0m  13: [4m[0m
2020-11-19T16:02:40.6258846Z [0m
2020-11-19T16:02:40.6259246Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6259878Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6260401Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6260696Z [0m[0m
2020-11-19T16:02:40.6260927Z [31m
2020-11-19T16:02:40.6261275Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6261554Z 
2020-11-19T16:02:40.6261879Z [0m  on webapp.tf line 13, in terraform:
2020-11-19T16:02:40.6262217Z   13: [4m[0m
2020-11-19T16:02:40.6262509Z [0m  14: [4m[0m
2020-11-19T16:02:40.6262782Z [0m
2020-11-19T16:02:40.6263185Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6263781Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6264298Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6264582Z [0m[0m
2020-11-19T16:02:40.6264816Z [31m
2020-11-19T16:02:40.6265153Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6265523Z 
2020-11-19T16:02:40.6266602Z [0m  on webapp.tf line 14, in terraform:
2020-11-19T16:02:40.6267041Z   14: [4m[0m
2020-11-19T16:02:40.6268672Z [0m  15: [4m[0m
2020-11-19T16:02:40.6268912Z [0m
2020-11-19T16:02:40.6269289Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6269952Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6270500Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6270901Z [0m[0m
2020-11-19T16:02:40.6271119Z [31m
2020-11-19T16:02:40.6271497Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6271837Z 
2020-11-19T16:02:40.6272176Z [0m  on webapp.tf line 15, in terraform:
2020-11-19T16:02:40.6272756Z   15: [4m[0m
2020-11-19T16:02:40.6273271Z [0m  16: [4m[0m
2020-11-19T16:02:40.6273583Z [0m
2020-11-19T16:02:40.6274176Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6274807Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6275387Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6276659Z [0m[0m
2020-11-19T16:02:40.6276943Z [31m
2020-11-19T16:02:40.6277351Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6278121Z 
2020-11-19T16:02:40.6279808Z [0m  on webapp.tf line 16, in terraform:
2020-11-19T16:02:40.6283070Z   16: [4m[0m
2020-11-19T16:02:40.6283705Z [0m  17: [4m[0m
2020-11-19T16:02:40.6284039Z [0m
2020-11-19T16:02:40.6284516Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6285178Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6288054Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6288414Z [0m[0m
2020-11-19T16:02:40.6289284Z [31m
2020-11-19T16:02:40.6289766Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6290184Z 
2020-11-19T16:02:40.6290589Z [0m  on webapp.tf line 17, in terraform:
2020-11-19T16:02:40.6291240Z   17: [4m[0m
2020-11-19T16:02:40.6291579Z [0m  18: [4m[0m
2020-11-19T16:02:40.6291907Z [0m
2020-11-19T16:02:40.6292325Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6292977Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6293491Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6293811Z [0m[0m
2020-11-19T16:02:40.6294154Z [31m
2020-11-19T16:02:40.6294549Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6294882Z 
2020-11-19T16:02:40.6295300Z [0m  on webapp.tf line 18, in terraform:
2020-11-19T16:02:40.6295699Z   18: [4m[0m
2020-11-19T16:02:40.6296076Z [0m  19: [4m[0m
2020-11-19T16:02:40.6296373Z [0m
2020-11-19T16:02:40.6299432Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6300230Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6300808Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6301216Z [0m[0m
2020-11-19T16:02:40.6301494Z [31m
2020-11-19T16:02:40.6301935Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6302303Z 
2020-11-19T16:02:40.6302662Z [0m  on webapp.tf line 19, in terraform:
2020-11-19T16:02:40.6303111Z   19: [4m[0m
2020-11-19T16:02:40.6303447Z [0m  20: [4m[0m
2020-11-19T16:02:40.6303711Z [0m
2020-11-19T16:02:40.6304163Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6319495Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6330992Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6331441Z [0m[0m
2020-11-19T16:02:40.6331671Z [31m
2020-11-19T16:02:40.6332089Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6332419Z 
2020-11-19T16:02:40.6333387Z [0m  on webapp.tf line 20, in terraform:
2020-11-19T16:02:40.6333870Z   20: [4m[0m
2020-11-19T16:02:40.6334223Z [0m  21: [4m[0m
2020-11-19T16:02:40.6335190Z [0m
2020-11-19T16:02:40.6335650Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6336218Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6336681Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6336981Z [0m[0m
2020-11-19T16:02:40.6337244Z [31m
2020-11-19T16:02:40.6337609Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6338137Z 
2020-11-19T16:02:40.6338571Z [0m  on webapp.tf line 21, in terraform:
2020-11-19T16:02:40.6338959Z   21: [4m[0m
2020-11-19T16:02:40.6339250Z [0m  23: [4m[0m
2020-11-19T16:02:40.6339584Z [0m
2020-11-19T16:02:40.6340028Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6340710Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6341259Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6341645Z [0m[0m
2020-11-19T16:02:40.6341878Z [31m
2020-11-19T16:02:40.6342227Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6342570Z 
2020-11-19T16:02:40.6343002Z [0m  on webapp.tf line 23, in terraform:
2020-11-19T16:02:40.6343437Z   23: [4m[0m
2020-11-19T16:02:40.6344069Z [0m  24: [4m[0m
2020-11-19T16:02:40.6344374Z [0m
2020-11-19T16:02:40.6345418Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6350729Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6351315Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6351651Z [0m[0m
2020-11-19T16:02:40.6351938Z [31m
2020-11-19T16:02:40.6352291Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6352598Z 
2020-11-19T16:02:40.6353282Z [0m  on webapp.tf line 24, in terraform:
2020-11-19T16:02:40.6353856Z   24: [4m[0m
2020-11-19T16:02:40.6355371Z [0m  25: [4m[0m
2020-11-19T16:02:40.6355677Z [0m
2020-11-19T16:02:40.6356104Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6356765Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6357310Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6359561Z [0m[0m
2020-11-19T16:02:40.6360073Z [31m
2020-11-19T16:02:40.6360674Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6361083Z 
2020-11-19T16:02:40.6361437Z [0m  on webapp.tf line 25, in terraform:
2020-11-19T16:02:40.6361932Z   25: [4m[0m
2020-11-19T16:02:40.6362255Z [0m  26: [4m[0m
2020-11-19T16:02:40.6362586Z [0m
2020-11-19T16:02:40.6363059Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6363730Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6364363Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6364676Z [0m[0m
2020-11-19T16:02:40.6364967Z [31m
2020-11-19T16:02:40.6367249Z [1m[31mError: [0m[0m[1mInvalid multi-line string[0m
2020-11-19T16:02:40.6367826Z 
2020-11-19T16:02:40.6369551Z [0m  on webapp.tf line 26, in terraform:
2020-11-19T16:02:40.6370349Z   26: [4m[0m
2020-11-19T16:02:40.6370703Z [0m  27: [4m[0m
2020-11-19T16:02:40.6371005Z [0m
2020-11-19T16:02:40.6371387Z Quoted strings may not be split over multiple lines. To produce a multi-line
2020-11-19T16:02:40.6373593Z string, either use the \n escape to represent a newline character or use the
2020-11-19T16:02:40.6374198Z "heredoc" multi-line template syntax.
2020-11-19T16:02:40.6374506Z [0m[0m
2020-11-19T16:02:40.6594792Z ##[error]Error: The process 'C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1
2020-11-19T16:02:40.6681405Z ##[section]Finishing: Terraform : init
```

### Expected Behavior
A resource group, storage account, SQL server and Database will be created.

### Actual Behavior
Deployment failing while initialization

### Steps to Reproduce
```
1)create azure DevOps repo 2)create pipeline CI & CD 3) use hosted agents (2016-2017, mac os) 4) add az cli,az powershell, replace token, install terraform, terraform init,plan,apply tasks in CD
```

**Comment by bytemech** [comment] 2020-11-19 17:11
Hi @rtk888 

Given that line 7 corresponds to your storage account key, are you sure you are not including a string (the key) which contains a disallowed character?

Also, I'd suggest using a [partial configuration](https://www.terraform.io/docs/backends/config.html#partial-configuration) and passing secrets in via command line. 

Check out [this article which may help you](http://jamesrcounts.com/2019/10/14/azdo-safe-terraform-pipelines.html)

Cheers,
BG

**Comment by danieldreier** [comment] 2020-11-23 17:32
Thanks for reporting this. In order to work on this, we need a reproduction case that's independent of Azure DevOps and can run locally. I don't immediately see evidence of a bug in Terraform itself, and we do not support the Azure DevOps integration - you should contact their commercial support if you believe the issue is in their integration.

My suggestion for you would be to run the "env" command in Azure DevOps or otherwise inspect the environment, and then construct a local reproduction case. The resources @bytemech posted may also be useful to you to work around it.

Can you please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies.

Without a reproduction case we can run locally, without the Azure DevOps troubleshooting built into the issue report, we will have to close this issue.

**Comment by ArieHein** [comment] 2020-11-28 14:49
This is not an issue with terraform.

Please follow https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage to see what's needs to be run to create the storage account needed for remote backend tfstate file. AZ CLI would be better because you can use the service connection for authentication, but its your decision.

Make sure you have variable names in the exact name as they appear in the tf files and that the tokenization step that's is run before the terraform  commands. To make it easier, have just the PowerShell script to create it and then add a step to echo it to the log and disable all terraform steps, then run and look at the logs that the expected values are correct.

**Comment by mildwonkey** [comment] 2021-04-30 16:16
There hasn't been a response in awhile, so I am going to close this issue. Please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27) if necessary. Thanks!

**Closed by mildwonkey** 2021-04-30 16:16 UTC
Labels: bug, cli, v0.12, waiting for reproduction
