### ISSUE TITLE
crash during plan

### ISSUE THREAD

**Issue by afeld** [hashicorp/terraform#15955] opened 2017-08-30 01:44 UTC
I was running a `terraform plan`, and Terraform crashed. It worked fine again right after this without any change.

### Terraform Version

v0.10.2

### Terraform Configuration Files

https://github.com/GSA/devsecops-example/tree/c7e8b2c1092d7479d1d1995fcca364d8aed0f107/terraform

### Debug Output

not available

### Crash Output

https://gist.github.com/afeld/6412b2a7816683eed9f6b3e372f0ade8

This is just an example repository/deployment, so no worries about any information in there that would normally be considered sensitive.

### Steps to Reproduce

🤷‍♂️ 

### Important Factoids

none

### References

none

**Comment by jbardin** [comment] 2017-08-30 14:10
Hi @afeld,

Thanks for the bug report!

This is a very peculiar crash, probably resulting from memory corruption, but there shouldn't be any unsafe code leading up to that point. Can you reproduce the crash again running the same command?

This doesn't look like our release binary. If you can reproduce the crash, can you try it with the binary from https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_darwin_amd64.zip?

**Comment by afeld** [comment] 2017-08-30 14:21
It only happened once, with nothing changed beforehand (as I remember) or afterwards. Not sure how to reproduce. This is using Terraform installed via HomeBrew.

**Comment by jbardin** [comment] 2017-08-30 14:57
Thanks for following up.

The crashing being caused by memory corruption, and not being reproducible, points to it likely stemming from a problem at the hardware level (I assume this is a macbook with non-ecc ram).

I'll close this for now, but feel free to reply later if you find find any more information or can reproduce the issue.

**Closed by jbardin** 2017-08-30 14:57 UTC
Labels: bug, core, crash
