### ISSUE TITLE
aws_key_pair depends_on fails

### ISSUE THREAD

**Issue by harkamals** [hashicorp/terraform#11540] opened 2017-01-31 10:43 UTC
### Terraform Version
0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource > local-exec
- aws_key_pair

### Terraform Configuration Files
```hcl
resource "null_resource" "keygen" {
  provisioner "local-exec" {
    command = "ssh-keygen -t rsa -C \"ec2-user\" -P '' -f /keys/ec2-user"
  }
}

resource "aws_key_pair" "my_test" {
  key_name = "ec2-user"
  public_key = "${file("/keys/ec2-user.pub")}"
  depends_on = ["null_resource.keygen"]
}
```

### Expected Behavior
null_resource (local-exec) should run first and aws_key_pair should run later

### Actual Behavior
aws_key_pair runs first, and because there no output from null_resource, it fails. Dependency is set over it.

**Comment by grubernaut** [comment] 2017-01-31 23:08
Thanks for the issue @harkamals! 
However it's a duplicate of #11515, closing. Happy to discuss further if experiencing a different error though.

**Closed by grubernaut** 2017-01-31 23:08 UTC
Labels: bug, core
