### ISSUE TITLE
Error when change is made to aws_launch_configuration

### ISSUE THREAD

**Issue by pfordahl** [hashicorp/terraform#2385] opened 2015-06-17 18:32 UTC
Your stack is build and you make a change to the aws_launch_configuration and you apply the change then the error comes up.

* ResourceInUse: Cannot delete launch configuration terraform-wei3injw2fdc3adjvzzlpeoz74 because it is attached to AutoScalingGroup XXXXX-test
	status code: 400, request id: [962be820-151e-11e5-8088-a1efb38c16d6]
Error applying plan:

2 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* ResourceInUse: Cannot delete launch configuration terraform-wei3injw2fdc3adjvzzlpeoz74 because it is attached to AutoScalingGroup XXXXX-test
	status code: 400, request id: [962be820-151e-11e5-8088-a1efb38c16d6]
* 1 error(s) occurred:

* aws_autoscaling_group.XXXX: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by sheldonh** [comment] 2015-06-23 10:43
Still a problem as at Terraform v0.6.0-dev (ce8baea6ae04d3ab328616beb0a1365345552e20).

**Comment by sheldonh** [comment] 2015-06-23 10:55
Duplicate of #1109.

**Comment by mitchellh** [comment] 2015-06-27 17:47
Agreed that this is a dup of #1109

**Closed by mitchellh** 2015-06-27 17:47 UTC
Labels: bug, provider/aws
