### ISSUE TITLE
target resources using wildcards ?

### ISSUE THREAD

**Issue by earzur** [hashicorp/terraform#17916] opened 2018-04-22 17:04 UTC
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.9.0
+ provider.template v1.0.0
```

We use terraform to provision complex systems such as elasticsearch and rancher clusters, etc...

We sometimes need to target several resources with the same commands, and it would be extremely useful to be able to target resources with wildcard...

things like `terraform apply -target aws_instance.es_cluster.*`, instead of having to use `terraform apply -target aws_instance.es_cluster.0 -target aws_instane.es_cluster.1...` would be very useful.

**Comment by marcosnils** [comment] 2018-04-25 19:59
Dupe of https://github.com/hashicorp/terraform/issues/2182 ?

**Comment by jbardin** [comment] 2018-05-04 15:11
Thanks for finding it @marcosnils!

**Closed by jbardin** 2018-05-04 15:11 UTC
Labels: cli, enhancement
