### ISSUE TITLE
scaleway instance with not default volumes

### ISSUE THREAD

**Issue by webroboteu** [hashicorp/terraform#9254] opened 2016-10-06 13:49 UTC
I have this error with VC1M instance.

With scaleway_volume_attachment i can't resolve the problem.

The properties volumes is not a scaleway_server property

Error applying plan:

1 error(s) occurred:

* scaleway_server.test: StatusCode: 400 Type: invalid_request_error Message:  APIMessage: The sum of volumes sizes of VC1M instances must be between 51GB and 100GB 

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by nicolai86** [comment] 2016-10-07 16:37
Hey @webroboteu,

can you provide a terraform plan which reproduces this error? 
`scaleway_server` does not have a `volumes` property - when you want to attach a separate volume to a `scaleway_server` instance, you need to do the following:

- create a separate `scaleway_volume`
- create a separate `scaleway_server`
- use a `scaleway_volume_attachment` to attach the volume to the server. Note that this requires running `scaleway_server` instances to be restarted.

i.e.

```
resource "scaleway_server" "test" {
  name = "test"
  image = "aecaed73-51a5-4439-a127-6d8229847145"
  type = "C2S"
}

resource "scaleway_volume" "test" {
  name = "test"
  size_in_gb = 20
  type = "l_ssd"
}

resource "scaleway_volume_attachment" "test" {
  server = "${scaleway_server.test.id}"
  volume = "${scaleway_volume.test.id}"
}
```

**Comment by seb2411** [comment] 2016-10-10 14:07
I have the same problem:
```
resource "scaleway_server" "minion" {
    name = "minion"
    image = "15fd0f74-c939-43c3-bf41-ee5f711b3bb4"
    type = "VC1M"
    dynamic_ip_required = true
}

resource "scaleway_volume" "additionalVolume" {
  name = "additionalVolume"
  size_in_gb = 20
  type = "l_ssd"
}


resource "scaleway_volume_attachment" "additionalVolume" {
  server = "${scaleway_server.minion.id}"
  volume = "${scaleway_volume.additionalVolume.id}"
}

```

** scaleway_server.minion: StatusCode: 400 Type: invalid_request_error Message:  APIMessage: The sum of volumes sizes of VC1M instances must be between 51GB and 100GB **

**Comment by nicolai86** [comment] 2016-10-10 18:26
@seb2411 @webroboteu I assume this is a Scaleway API issue, as the above example works with C2S just fine, as does it with VC1. I'll loop in @moul , maybe he has an idea on how to triage this issue.

**Comment by seb2411** [comment] 2016-10-11 07:39
@nicolai86 : Yes. I think it's in relation with the way the extra disk is added for the VC1M and VC1L.
For this 2 if you check in the UI of Scaleway the system add automatically an additional disk. It's not the case for the VC1S and C2*.

**Comment by nicolai86** [comment] 2016-10-15 07:07
the official Scaleway CLI has the same issue:

```
$ scw create --commercial-type=VC1M ubuntu-precise
FATA[0000] cannot execute 'create': The sum of volumes sizes of VC1M instances must be between 51GB and 100GB
```

Digging a little deeper into the request payload, this works:

``` json
{
  "dynamic_ip_required": false,
  "tags": [],
  "commercial_type": "VC1M",
  "volumes": {
    "1": {
      "name": "Volume",
      "volume_type": "l_ssd",
      "size": 50000000000,
      "organization": "a"
    }
  },
  "organization": "a",
  "name": "scw-50ed96",
  "image": "75c28f52-6c64-40fc-bb31-f53ca9d02de9",
  "public_ip": "e6ee2eb1-70c6-49d1-aa17-93f8eaf96529"
}
```

but this doesn't:

```
{
  "dynamic_ip_required": false,
  "tags": [],
  "commercial_type": "VC1M",
  "volumes": {},
  "organization": "a",
  "name": "scw-50ed96",
  "image": "75c28f52-6c64-40fc-bb31-f53ca9d02de9",
  "public_ip": "e6ee2eb1-70c6-49d1-aa17-93f8eaf96529"
}
```

both terraform and the scaleway CLI generate the latter. I'll see if this can be fixed with a payload transformation…

**Comment by nicolai86** [comment] 2016-10-15 07:27
Digging a little deeper it seems that the Scaleway CLI masks the problem by implicitly adding volumes when certain offerings are created, as discussed in https://github.com/scaleway/scaleway-cli/pull/403 .

Since this fix is added outside of the Scaleway SDK we would need to duplicate that same logic, or, alternatively, allow secondary volumes to be defined inside the `scaleway_server` resource, as proposed in https://github.com/hashicorp/terraform/pull/8678.

**Comment by seb2411** [comment] 2016-10-17 07:50
@nicolai86 Thx for the update. Defining the volume inside the scaleway_server resource can be a good idea.

**Comment by stack72** [comment] 2016-10-28 15:33
Hi @webroboteu / @nicolai86 

Is this still an issue?

P.

**Comment by nicolai86** [comment] 2016-10-28 17:34
Hey @stack72 

Yes, this is still an issue. VC1M and VC1L instances require an additional volume to be specified at creation time, which to my best knowledge can not be modelled with two resources; 

I think we need to introduce a new `scaleway_server` attribute, similar to what is proposed in #8678

**Comment by tboerger** [comment] 2016-10-29 11:16
So, this issue is resolved via https://github.com/hashicorp/terraform/pull/9695 :)

**Comment by stack72** [comment] 2016-10-29 11:30
Thanks for the nudge @tboerger 

Closed vis #9695

**Closed by stack72** 2016-10-29 11:30 UTC
Labels: bug, provider/scaleway

**Comment by seb2411** [comment] 2016-10-30 19:51
So the problem will be fixed on Terraform 0.7.8 ?

**Comment by nicolai86** [comment] 2016-10-30 20:32
@seb2411 yup, next release contains a fix for this. see #9695

**Comment by seb2411** [comment] 2016-10-31 08:21
@nicolai86 ok. Perfect Thank you guys for the responsiveness, Nice job.
