### ISSUE TITLE
Templates loaded from file don't interpolate template variables.

### ISSUE THREAD

**Issue by etiennetremel** [hashicorp/terraform#12719] opened 2017-03-15 12:39 UTC
Not sure if I'm doing something wrong, but combining templates with interpolation from count doesn't seem to work as expected.
I followed the [Using Templates with Count](https://www.terraform.io/docs/configuration/interpolation.html#using-templates-with-count) from the documentation, but didn't succeed.

### Terraform Version

Terraform v0.8.8

### Affected Resource(s)
- google_compute_instance
- template_file
- google_compute_disk

Problem seems to be coming from the interpolation [element()](https://www.terraform.io/docs/configuration/interpolation.html#element_list_index_)

### Terraform Configuration Files
```hcl
variable "node_count" {
  default = "3"
}

resource "google_compute_disk" "my_instance" {
  count = "${var.node_count}"
  name = "my-instance-${count.index}-data"
  zone = "europe-west1-c"
}

data "template_file" "my_instance" {
  count = "${var.node_count}"
  template = "${file("template.yml")}"

  vars {
    DATA_PD = "${element(google_compute_disk.my_instance.*.name, count.index)}"
  }
}

resource "google_compute_instance" "my_instance" {
  count = "${var.node_count}"
  name = "my-instance-${count.index}"
  machine_type = "g1-small"
  zone = "europe-west1-c"

  disk {
    image = "https://www.googleapis.com/compute/v1/projects/google-containers/global/images/container-vm-v20160217"
  }

  metadata {
    google-container-manifest = "${element(data.template_file.my_instance.*.rendered, count.index)}"
  }

  depends_on = [
    "google_compute_disk.my_instance"
  ]
}
```
**template.yml:**
```yaml
version: v1
kind: Pod
metadata:
  name: instance
spec:
  containers:
  - name: instance
    image: image:1.2.3
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    gcePersistentDisk:
      pdName: ${DATA_PD}
      fsType: ext4
```

### Expected Behavior

There is no _google-container-manifest.metadata_ displayed in the state.

### Actual Behavior

After running `terraform plan`, here is the output: https://gist.github.com/etiennetremel/15a126081720ecfcffc51b3ec9d1aabf

### Steps to Reproduce

1. `terraform plan`

**Comment by paddyforan** [comment] 2017-03-15 20:06
Hi there! Sorry for the issues.

I reproduced the problem locally, and found what I believe to be a root cause of your problem. Here's the config file I landed on:

```hcl
variable "node_count" {
  default = "3"
}

resource "google_compute_disk" "my_instance" {
  count = "${var.node_count}"
  name  = "my-instance-${count.index}-data"
  zone  = "europe-west1-c"
}

data "template_file" "my_instance" {
  count = "${var.node_count}"

  template = <<EOF
version: v1
kind: Pod
metadata:
  name: instance
spec:
  containers:
  - name: instance
    image: image:1.2.3
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    gcePersistentDisk:
      pdName: $${DATA_PD}
      fsType: ext4
EOF

  vars {
    DATA_PD = "${element(google_compute_disk.my_instance.*.name, count.index)}"
  }
}

resource "google_compute_instance" "my_instance" {
  count        = "${var.node_count}"
  name         = "my-instance-${count.index}"
  machine_type = "g1-small"
  zone         = "europe-west1-c"

  disk {
    image = "https://www.googleapis.com/compute/v1/projects/google-containers/global/images/container-vm-v20160217"
  }

  metadata {
    google-container-manifest = "${element(data.template_file.my_instance.*.rendered, count.index)}"
  }

  depends_on = [
    "google_compute_disk.my_instance",
  ]

  network_interface = {
    network = "default"
  }
}
```

You'll notice some differences:
* a network_interface block was added to the instances, as it's required.* the template was brought inline, instead of being loaded from a file.

That last one is the important one. It appears variable substitution doesn't happen if you load templates from files. According to our docs, this should work. I'm going to retitle the issue and relabel it, so the right people can look at it.

**Comment by boynux** [comment] 2017-06-16 15:44
We have same issue with Terraform, is there any progress?

**Comment by paddycarver** [comment] 2017-08-09 23:57
@boynux Sorry for the long delay in response. Do you happen to have a reproduction handy?

I just tried reproducing this under Terraform 0.10, and it worked as expected:

template.txt:
```
${BAZ}
```

config.tf:
```hcl
data "template_file" "foo" {
  template = "${file("template.txt")}"

  vars {
    BAZ = "hello, world"
  }
}
```

That correctly shows `hello, world` when I run `terraform apply` followed by `echo "data.template_file.foo.rendered" | terraform console`.

**Comment by paddycarver** [comment] 2017-09-06 23:37
Without a reproduction, it's hard to debug this more. Seeing as a few weeks have passed, I'm going to close this out. But if someone runs into this issue, feel free to open a new issue and let us know!

**Closed by paddycarver** 2017-09-06 23:37 UTC
Labels: bug, core
