### ISSUE TITLE
tf apply crashes on aws_instance count 1 => 2 w/ create_before_destroy = true

### ISSUE THREAD

**Issue by dpkp** [hashicorp/terraform#713] opened 2014-12-25 18:56 UTC
test case config:
```
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "us-west-2"
}

resource "aws_instance" "foobar" {
  ami = "ami-5196d561"
  instance_type = "m1.small"
  count = 1
  key_name = "${var.key_name}"
  lifecycle {
    create_before_destroy = true
  }
}
```
apply once, change count to 2, apply again, crash.

output (truncated)
```
aws_instance.foobar.1: Creation complete
aws_instance.foobar: Destroying...
aws_instance.foobar.1: Destroying...
aws_instance.foobar.0: Destroying...
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range
```

doesn't crash if create_before_destroy is false

**Comment by mitchellh** [comment] 2015-02-17 18:45
Thanks, we're going to target this for 0.4.0 since we have a big refactor coming in that we want to repro this onto rather than current master.

**Comment by mitchellh** [comment] 2015-04-18 23:37
Post 0.4.0 (now 0.4.2 and master), I can't reproduce this so I believe its fixed. Closing. Sorry I can't tell you when!

**Closed by mitchellh** 2015-04-18 23:37 UTC
Labels: core, crash

**Comment by dpkp** [comment] 2015-04-19 03:32
thanks!
