### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by therealdoug** [hashicorp/terraform#34268] opened 2023-11-17 16:07 UTC
### Terraform Version

```shell
$ terraform version
Terraform v1.6.0
on windows_386
+ provider registry.terraform.io/ciscodevnet/aci v2.11.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/netascode/utils v0.2.5

Your version of Terraform is out of date! The latest version
is 1.6.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
Providers required by configuration:
.
├── provider[registry.terraform.io/ciscodevnet/aci]
└── module.aci
    ├── provider[registry.terraform.io/ciscodevnet/aci] >= 2.6.1
    ├── provider[registry.terraform.io/netascode/utils] >= 0.2.5
    ├── provider[registry.terraform.io/hashicorp/local] >= 2.3.0
    ├── module.aci_access_spine_interface_policy_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_user
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_dns_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_set_rule
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_spine_interface_selector_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_span_destination_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_interface_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_node_control_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_match_rule
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_redirect_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_smart_licensing
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_inband_node_address
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_interface_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_scheduler
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l2_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_spine_switch_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_leaf_interface_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_spine_switch_policy_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_bgp_address_family_context_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_mcp
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_system_global_gipo
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_switch_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_date_time_format
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_snmp_trap_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_application_profile
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_redirect_health_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_tenant
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_geolocation
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_external_connectivity_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_spine_interface_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_lldp_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_spine_interface_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_vpc_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l3out_node_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_interface_type
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_pod_setup
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_config_export
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_tenant_span_destination_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_leaf_switch_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_external_endpoint_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_qos
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_psu_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_pod_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_tacacs
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_igmp_snooping_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_trust_control_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_aaa
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_oob_external_management_instance
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_error_disabled_recovery
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_l2_mtu
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_route_control_route_map
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_remote_location
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_filter
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_vrf
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_bridge_domain
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l3out_node_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_redirect_backup_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_leaf_switch_policy_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_fex_interface_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_fex_interface_selector_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_pod_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_snmp_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_endpoint_security_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_spine_switch_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_bfd_interface_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_endpoint_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_keyring
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_spine_interface_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_bgp_peer_prefix_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_service_epg_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_bgp_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l2_mtu_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_multicast_route_map
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_port_tracking
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_wide_settings
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_aaep
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_device_selection_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_fex_interface_selector_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_coop_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_bgp_best_path_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_monitoring_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_rogue_endpoint_control
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_spine_switch_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_node_registration
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_vlan_pool
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_health_score_evaluation_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_span_destination_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_cdp_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_dhcp_relay_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_apic_connectivity_preference
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_infra_dscp_translation_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_login_domain
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_ip_sla_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_isis_bfd
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_date_time_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_fex_interface_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_spine_interface_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_span_filter_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_mst_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_vmware_vmm_domain
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_ospf_interface_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_igmp_interface_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_spine_interface_selector_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l4l7_device
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_dhcp_option_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_bgp_timer_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_vspan_destination_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l3out
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_management_access_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_oob_endpoint_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l3out_interface_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_spanning_tree_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_l3out_interface_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_qos_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_oob_contract
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_maintenance_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_switch_policy_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_span_source_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_vpc_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_config_passphrase
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.6.0
    ├── module.aci_contract
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_imported_contract
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_service_graph_template
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_interface_policy_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_routed_domain
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_tenant_span_source_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_syslog_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_port_channel_member_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_interface_selector_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_leaf_switch_profile_manual
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_forwarding_scale_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_endpoint_loop_protection
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_storm_control_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_ip_aging
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_pim_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_firmware_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_vspan_session
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_interface_selector_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_switch_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_spine_switch_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_inband_endpoint_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_spine_switch_policy_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_oob_node_address
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_ptp
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_link_level_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_physical_domain
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_leaf_interface_profile_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_span_source_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_banner
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_mcp_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_access_leaf_interface_selector_sub_auto
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_isis_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_fabric_pod_policy_group
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    ├── module.aci_port_channel_policy
    │   └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
    └── module.aci_ca_certificate
        └── provider[registry.terraform.io/ciscodevnet/aci] >= 2.0.0
```

### Debug Output

<script src="https://gist.github.com/therealdoug/471d36307e6d0fbbcf59d16b8401f11b.js"></script>

### Expected Behavior

Create DEV tenant and basic configurations in lab Environment

### Actual Behavior

Immediately crashes

### Steps to Reproduce

Following this guide:  https://developer.cisco.com/docs/nexus-as-code/#!comprehensive-example

1. git clone https://github.com/netascode/nac-aci-comprehensive-example.git
2. terraform init
3. modify username and password in aci providor in main.tf
4. terraform apply

**Comment by jbardin** [comment] 2023-11-17 16:11
Duplicate of #33977

**Closed by jbardin** 2023-11-17 16:11 UTC
Labels: bug, new
