### ISSUE TITLE
Errant "Changes to Outputs" shown with resource targeting as of 0.13

### ISSUE THREAD

**Issue by mrubinwch** [hashicorp/terraform#26082] opened 2020-09-01 18:48 UTC
### Terraform Version

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/aws v3.4.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

### Expected Behavior

I am applying changes to an `aws_elastic_beanstalk_environment` resource by targeting that particular resource. In the plan which is shown (prior to me having to type "yes"), I expect to see only the relevant targeted resources.

### Actual Behavior

What's shown in the output are the below changes to outputs (some details obfuscated). There are no changes to outputs in my Terraform configuration.

```
Plan: 0 to add, 1 to change, 0 to destroy.

Changes to Outputs:
  - bastion_dns              = [
      - [
          - "bastion-us-east-1a.example.com",
          - "bastion-us-east-1b.example.com",
          - "bastion-us-east-1c.example.com",
        ],
    ] -> null
  - foo_subnet_ids = [
      - [
          - "subnet-0abcdeabcdeed50c3",
          - "subnet-0abcdeabcdeed7167",
          - "subnet-0abcdeabcdeed195f",
        ],
    ] -> null
  - private_subnet_ids       = [
      - [
          - "subnet-abcdefb6",
          - "subnet-abcdef8b",
          - "subnet-abcdef41",
        ],
    ] -> null


Warning: Resource targeting is in effect
```

### Steps to Reproduce

Use `-target` as of Terraform 0.13. This issue did not occur with prior versions.

**Comment by mildwonkey** [comment] 2020-09-09 16:39
Hi! Thank you for reporting this unexpected behavior, and I am sorry that you've experienced it.

We'll need to see your configuration files, or better yet a simplified reproduction case to figure out what's going on here. Can you please update this ticket with all of the information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Remove any sensitive information first.

Thanks again!

**Comment by alisdair** [comment] 2020-09-16 22:37
This looks like a duplicate of #26274, which has a reproduction and an explanation. Closing.

**Closed by alisdair** 2020-09-16 22:37 UTC
Labels: bug, new, waiting for reproduction, waiting-response
