### ISSUE TITLE
Terraform crashed! This is always indicative of a bug within Terraform.

### ISSUE THREAD

**Issue by santhoshnc7** [hashicorp/terraform#32987] opened 2023-04-05 14:22 UTC
### Terraform Version

```shell
1.4.0
```

### Terraform Configuration Files

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0
   
    # Check for terraform version and status
    - name: Terraform Version
      run: terraform -version

    - name: Install Terragrunt v0.36.2
      run: |
        sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.2/terragrunt_linux_amd64"
        sudo chmod +x /bin/terragrunt
    # Check for terragrunt version and status
    - name: Terragrunt Version
      run: terragrunt -v

    # Run terragrunt plan in all folders
    - name: Terragrunt plan
      run: terragrunt run-all plan --terragrunt-non-interactive

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x[40](https://github.com/greenpass-venture/ts-aws-dataplane-infra-automation/actions/runs/4618429331/jobs/8165871717#step:8:41)6fc90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
	/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000a1c000, {0x2ccf8f8, 0xc0005d6580}, {0x2ccf8f8, 0xc0005d65c0}, 0xc0000bb680, 0xc0005d6500)
	/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:316 +0x[44](https://github.com/greenpass-venture/ts-aws-dataplane-infra-automation/actions/runs/4618429331/jobs/8165871717#step:8:45)a

### Expected Behavior

The pipeline should run without any issue. 

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x23441a0, 0x406fc90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
	/home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000a1c000, {0x2ccf8f8, 0xc0005d6580}, {0x2ccf8f8, 0xc0005d65c0}, 0xc0000bb680, 0xc0005d6500)
	/home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
	/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
	/home/circleci/project/project/internal/backend/local/backend.go:[31](https://github.com/greenpass-venture/ts-aws-dataplane-infra-automation/actions/runs/4618429331/jobs/8165871717#step:8:32)6 +0x[44](https://github.com/greenpass-venture/ts-aws-dataplane-infra-automation/actions/runs/4618429331/jobs/8165871717#step:8:45)a

Error: Terraform exited with code 11.

### Steps to Reproduce

terraform init
terragrunt run-all plan --terragrunt-non-interactive

### Additional Context

We are running the Terraform code to create the resources in AWS using Terragrunt. So the provisioning of the resources are working fine. But the destruction of resource is not working as expected.

**Comment by jbardin** [comment] 2023-04-05 15:21
Duplicate of #32810

**Closed by jbardin** 2023-04-05 15:21 UTC
Labels: bug, new
