### ISSUE TITLE
Failed to instantiate provider "registry.terraform.io/hashicorp/null"

### ISSUE THREAD

**Issue by nomadyt** [hashicorp/terraform#27602] opened 2021-01-27 01:44 UTC
### Terraform Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.25.0
+ provider registry.terraform.io/hashicorp/null v3.0.0

Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
resource "null_resource" "test" {
}
```

### Debug Output

https://gist.github.com/nomadyt/48a4cbb97055f0835198ade3c2e4d705

### Expected Behavior

Successful terraform apply

### Actual Behavior

terraform apply failed

### Steps to Reproduce

1. create a null resource 
```
resource "null_resource" "test" {
}
```
2. `terraform apply`
3. delete the null resource
4. `terraform apply`

**Comment by apparentlymart** [comment] 2021-01-28 22:55
Hi @nomadyt,

Based on what you've reported here, this seems likely to be an operational problem within Terraform Cloud rather than directly a Terraform CLI bug: Terraform Cloud is responsible for making sure that all of the plugins that `terraform init` installed for planning will still be available during apply, but Terraform CLI seems to be reporting that this isn't true in your case for some reason.

The team that works in this repository doesn't have access to details about Terraform Cloud accounts, so we aren't empowered to debug this directly. Instead, I'd suggest contacting Terraform Cloud customer support, either via your usual representative (if you have a paid account) or via the general support email at tf-cloud-support@hashicorp.com . If you contact support, be sure to mention your Cloud organization and username so that the support team can potentially access the details for the run that failed to understand better what went wrong.

If the Terraform Cloud team determines that this was caused by a bug in Terraform CLI then they'll let us know internally, and so I'm going to close this for now just to signify that the Terraform Core team doesn't have the necessary access to investigate and reproduce this directly.

**Closed by apparentlymart** 2021-01-28 22:55 UTC
Labels: bug, new
