### ISSUE TITLE
Recreating resources when using count on random_id

### ISSUE THREAD

**Issue by anas-aso** [hashicorp/terraform#13763] opened 2017-04-19 09:31 UTC
### Terraform Version
`Terraform v0.9.3`

### Affected Resource(s)
- google_compute_address

but I am not sure if it affects other resources.

### Terraform Configuration Files
```hcl
variable "count" {
  default = "1"
}

variable "name" {
  default = "test-srv"
}

provider "google" {
  project = "my-project"
  region  = "europe-west1"
}

resource "random_id" "service" {
  count = "${var.count}"

  keepers {
    name          = "${var.name}"
  }

  byte_length = 4
}

resource "google_compute_address" "service" {
  count = "${var.count}"
  name  = "${var.name}-${element(random_id.service.*.hex, count.index)}"
}

```

### Debug Output
it's easily reproducible so I won't put any debug output.

### Expected Behavior
When increasing the count from 1 to 2 (or higher), I was expecting to have new IPs created without any change to the already existing ones.

### Actual Behavior
Terraform recreated (destroy then create) the existing IPs.

### Steps to Reproduce
1. `terraform apply`
2. increase the count from 1 to 2 (or higher)
3. `terraform plan` or `terraform apply` directly.

**Comment by apparentlymart** [comment] 2017-04-19 16:38
Hi @anas-aso! Thanks for reporting this.

I think what you have here is the same issue as described in #3449. The problem is that currently Terraform isn't able to understand that `element` only refers to the `count.index` element of the list, and so it assumes that because the list contains *something* computed the result must itself be computed, causing Terraform to think that the name has updated for *all* of your addresses.

In your case I think you *may* be able to work around this using a `-target` specification to encourage Terraform to focus only on the new addresses:

```
terraform plan -out=tfplan -target=google_compute_address.service[1]
```

If this works you should see a plan output that does *not* describe replacing the existing addresses. You should then be able to safely apply this plan with `terraform apply tfplan`. Unfortunately this workaround doesn't always work due to how `-target` still respects resource dependencies, but from what I can see of your configuration here it seems like it could work for you. Pay careful attention to the plan output to make sure.

If that works, once you've applied the targeted plan Terraform should then be able to see that the existing addresses won't change on a subsequent run of `terraform plan`, because by then the list of `remote_id` resources will have been updated by the previous run.

I hope that helps. Since we already have an existing issue for this I'm going to close this one to consolidate discussion over there, but I do appreciate you taking the time to report this issue.

**Closed by apparentlymart** 2017-04-19 16:38 UTC
Labels: bug, core

**Comment by anas-aso** [comment] 2017-04-20 06:43
Thanks @apparentlymart for the quick answer and for the workaround. I am sorry for the duplicate, I have looked before for similar issue, but failed to find it 😞
Regarding the workaround, I have done what you suggested but with as slight difference 
`terraform plan -out=tfplan -target=random_id.service`. This way I don't have to care about the element index in the array and it can be easily "automated".

**Comment by apparentlymart** [comment] 2017-04-20 16:27
That's a good alternative workaround, @anas-aso. Good idea!

(In case anyone else finds this later and wonders what's going on there, this workaround causes Terraform to work on generating the new random ids first, and then on a subsequent run they are already there and ready to use so we can avoid the `${element(random_id.service.*.hex, count.index)}` expression resolving as "computed".)
