### ISSUE TITLE
Terraform Crash!!!

### ISSUE THREAD

**Issue by ragnardevops** [hashicorp/terraform#33754] opened 2023-08-25 09:26 UTC
### Terraform Version

```shell
0.11.11
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "= 1.5.5"
  backend "gcs" {
    bucket  = "xxx-terraform-state"
    prefix  = "xxx-xxx/kubernetes/preprod-b"
  }
}

module "kubernetes" {
  source = "../../../modules/wc9-kubernetes"

  zone                              = "europe-west2-b"
  network                           = "xxx"
  subnetwork                        = "xxx"
  k8s_name                          = "preprod-b"
  node_count                        = "1"
  min_master_version                = "1.25.9-gke.2300"
  node_version                      = "1.25.9-gke.2300"
  release_channel                   = "None"
  node_disk_type                    = "pd-ssd"
  node_image_type                   = "cos_containerd" 
  node_disk_size_gb                 = "256"
  node_machine_type                 = "n1-highmem-16"
  min_cpu_platform                  = "Intel Skylake"
  node_tags                         = [ "k8s-nodes" ]
  node_auto_upgrade                 = "false"
  cluster_ipv4_cidr                 = "xxx"
  db2_ports                         = [
                                        "50001",
                                        "50002"
                                      ]
  firewall_ssh_allow_external       = [
                                        
                                      ]
  master_authorized_networks_config = [
                                       
                                      ]
}
```

### Debug Output

https://gist.github.com/ragnardevops/c4615fa1e09ef1a474836cca3f8d8cca

### Expected Behavior

Cluster should have deleted

### Actual Behavior

Got a Terraform Crash error message 
[crash.log](https://github.com/hashicorp/terraform/files/12437491/crash.log)

### Steps to Reproduce

terraform refresh
terraform destroy

**Comment by liamcervante** [comment] 2023-08-25 13:44
Hi @ragnardevops, thanks for filing this!

I can see you are using Terraform v0.11.11 which is nearly 5 years old. Would you be able to upgrade to the latest version of Terraform (v1.5.6) and try again? There's a good chance the root cause of this crash has been fixed already.

If this crash hasn't been fixed in the latest version, any fix we did produce would still only be released in the next v1.5 or v1.6 release so you'd have to upgrade at that point anyway to benefit from it.

Given the age of the version you are using I am going to close this issue. If you can reproduce this in the latest version, then please feel free to reopen this issue.

Thanks!

**Closed by liamcervante** 2023-08-25 13:44 UTC
Labels: bug, new
