### ISSUE TITLE
Terraform (0.14) Cloud sensitive variables

### ISSUE THREAD

**Issue by mbevc1** [hashicorp/terraform#27700] opened 2021-02-06 19:37 UTC
### Terraform Version

```
0.14.x
```

### Terraform Configuration Files

```terraform
variable "key" {
  description = "The KEY passed from TerraformCloud variables"
  type        = string
  sensitive   = false
}

```

### Expected Behavior

When marking a variable in TFC as sensitive and passing value down in the code when executing it should obey `sensitive` setting in `variables.tf` .

### Actual Behavior

`sensitive` attribute is overridden and variable marked as sensitive, thus breaking code in `for_each` loops.

### Steps to Reproduce

1. Create a variable in TFC UI on the workspace and mark it as sensitive (we want encryption and no visibility in UI)
2. in the code, variables.tf: use `sensitive = false`
3. use that variable in `for_each` loop
3. Run plan
4. using 0.14 fails due hard limitation using sensitive values in `for_each` loops

### Additional Context

Examining this behaviour and more testing showed even if not using explicit sensitive value it's still masked in `plan` as sensitive value and it should succeed, which it did in previous versions. Is this intended behaviour?

**Comment by chrisarcand** [comment] 2021-02-07 04:32
This is working as intended. The variable sensitivity declared in the configuration defers to Terraform Cloud when variables are marked as sensitive there, with a bias to retain sensitivity. 

The limitations of what you can do with sensitive values, even as they are transformed to something unsensitive, is understandable though - and this may be a use case to note for https://github.com/hashicorp/terraform/pull/27341

**Closed by chrisarcand** 2021-02-07 04:32 UTC
Labels: bug, new

**Comment by mbevc1** [comment] 2021-02-07 18:00
Cool, thanks!
