### ISSUE TITLE
Mutual TLS Authentication for HTTP Backend

### ISSUE THREAD

**Issue by cwiph** [hashicorp/terraform#31618] opened 2022-08-11 09:21 UTC
### Current Terraform Version
```
Terraform v1.2.7
```

### Use-cases
As a terraform user I want to store my state and lock files in HTTP based backend's that require mutual TLS authentication for improved security and compliance reasons. 

### Attempted Solutions
According to the source code of the [HTTP backend](https://github.com/hashicorp/terraform/tree/main/internal/backend/remote-state/http) there is no support for mutual TLS authentication with client certificates.

### Proposal
Extend the HTTP backend to support the following parameters for mutual TLS authentication:

* `TF_HTTP_CA` - path to the CA certificate
* `TF_HTTP_CLIENT_CERTIFICATE` - path to the client certificate
* `TF_HTTP_CLIENT_KEY` - path to the private key of the client certificate

### References
- https://venilnoronha.io/a-step-by-step-guide-to-mtls-in-go
- https://github.com/hashicorp/terraform/tree/main/internal/backend/remote-state/http

**Comment by crw** [comment] 2022-08-11 21:48
Thanks for this enhancement request!

**Comment by kmoe** [comment] 2022-09-01 12:31
https://github.com/hashicorp/terraform/issues/31700 is a duplicate of this. Both issues are well-written, but I'm going to close the older one this time, because the newer one has an associated PR, so it'll be easier to track the work there.

**Closed by kmoe** 2022-09-01 12:31 UTC
Labels: enhancement, backend/http, new
