### ISSUE TITLE
Values for variables without defaults not being passed at destroy time with terraform test - only apply time

### ISSUE THREAD

**Issue by tobydoescode** [hashicorp/terraform#33612] opened 2023-07-31 14:33 UTC
### Terraform Version

```shell
Terraform v1.6.0-alpha20230719
```

### Terraform Configuration Files

```sh
.
|-- main.tf <- run `terraform test` here
`-- tests
    `-- tests.tftest
```

```terraform
# main.tf
variable "file_path" {
  type = string
}

resource "local_file" "test" {
  filename = var.file_path
  content  = "hello"
}
```
```terraform
# tests/tests.tftest
run "test" {
  variables {
    file_path = "./msg.txt"
  }
}
```

### Debug Output

```sh
tests/tests.tftest... pass
  run "test"... pass
Terraform encountered an error destroying resources created while executing tests/tests.tftest.
╷
│ Error: No value for required variable
│ 
│   on main.tf line 2:
│    2: variable "file_path" {
│ 
│ The root module input variable "file_path" is not set, and has no default value. Use a -var or -var-file command line argument to provide a value for this variable.
╵

Terraform left the following resources in state after executing tests/tests.tftest, they need to be cleaned up manually:
  - local_file.test

Success! 1 passed, 0 failed.
```

### Expected Behavior

Terraform tests run and cleanup resources using the variables provided in the "variables" block in the "run" block.

### Actual Behavior

Variables are used for apply but not destroy. Tests pass, however resources are not cleaned up.

### Steps to Reproduce

1. `terraform init`
2. `terraform test`

### Additional Context

As a side note, this is a trivialised example of an issue I am experiencing in a more complicated module.

**Comment by tobydoescode** [comment] 2023-07-31 14:39
As another observation, it appears this is only true when tests are run from the test subject directory and defined in another directory. When I create an empty `main.tf` in `tests/`,  update my tests with a `module` block that points to the subject module and then run terraform from `tests/` directory the issue doesn't occur.

**Comment by liamcervante** [comment] 2023-08-01 07:28
Hi @tobydoescode, thanks for the feedback! We have had reports of this through other channels as well, so you are not alone.

What's happening here is that the variables defined within run blocks are not available during the destroy operation that happens at the end of the test file. This makes more sense when you imagine a test file with multiple run blocks, as how does the test know which of the variable values to apply, but it does apply to a case with a single run block as well.

What we've done is merge this PR: https://github.com/hashicorp/terraform/pull/33561. With the next release, which should be this week, `terraform test` will now check all the required variables are defined at the file level before allowing the test file to execute, and will supply a nicer error message stating this requirement. This should ensure the destroy operation will succeed as the variables will be confirmed as available.

Other options we considered were to take the variables from the first run block, or as in your case if there is only a single run block to use that. Overall we did felt it was better to make test authors be specific and clear about which variable values are going to be used when, and as such just simply saying required variables must have defaults specified at the root level makes everything more clear.

We do recognise this has the potential to be confusing, so we'll make sure this is clarified in the documentation. And from the next release you should see the tests giving the perviously mentioned error message up front.

Given the already merged PR I will close this as already fixed, but we really do appreciate the feedback and reports so please let us know if you find anything else!

Thanks again!

**Closed by liamcervante** 2023-08-01 07:28 UTC
Labels: bug, new

**Comment by liamcervante** [comment] 2023-08-01 07:36
A quick follow up comment on your workaround. What happens when you introduce the `module` block as you have done there is that it creates a separate state object for that run block, and when it is destroyed it does apply the variable values from the specific run block since that state object is unique to that run block.

That approach wouldn't work if you had multiple run blocks that you wanted to operate in sequence as each would then operate independently with their own states.

As hinted at in the original comment, the correct fix would be to place the `variables` block at the file level. These variable values could then be overridden in the specific run blocks to test different behaviours, but the final destroy operation could still succeed as it would have access to the file level values.

**Comment by tobydoescode** [comment] 2023-08-01 07:52
Thanks @liamcervante, sorry I did not see that PR. It makes sense and I also agree that the approach taken is the right one. Less permutations equals less confusing after all.

So a consequence of it is that every variable in a module being tested must have a default value - whether that be by having it in the native module or by using my workaround above with a dummy module. While the former means updating quite a few modules, it also shouldn't be problematic because validation can still be used to ensure that a value is provided by the caller of the module.

**Comment by tobydoescode** [comment] 2023-08-01 07:57
My assumption confirmed:

```sh
tests/reuse.tftest... pass
  run "create_existing_for_reuse"... pass
  run "check_can_reuse"... pass
Terraform encountered an error destroying resources created while executing tests/reuse.tftest.
╷
│ Error: Invalid value for variable
│ 
│   on variables.tf line 2:
│    2: variable "name" {
│     ├────────────────
│     │ var.name is null
│ 
│ Must be alphanumeric or null.
│ 
│ This was checked by the validation rule at variables.tf:11,3-13.
╵

Terraform left the following resources in state after executing tests/reuse.tftest, they need to be cleaned up manually:
  - aws_iam_instance_profile.this[0]
  - aws_iam_role.this[0]

Success! 2 passed, 0 failed.
```

**Comment by tobydoescode** [comment] 2023-08-01 08:05
I misunderstood what you meant by "file level". I've done what you meant and it works as I'd hope. Thanks!

**Comment by tobydoescode** [comment] 2023-08-01 08:06
I misunderstood what you mean by "file level". I've not done what you meant and I have the behaviour I'd expect. Thanks!

**Comment by liamcervante** [comment] 2023-08-01 08:40
Thanks for the additional feedback!

> It would be useful if we could better control the destroy part of the test. Ultimately it doesn't really matter what value it has in most cases (quite possibly all), it just needs a value. After all a useful work around to clean up resources when I have the statefile and not the code it to run terraform against an empty config.

I will pass this on to the product team, and we can see if we can work something out. This is a problem that users face in regular Terraform as well (in that Terraform will ask users for variable values during destroy operations even though in most cases they are not needed). This is a hard problem for Terraform to solve, as it is difficult to work out exactly when the variables are needed. There are definitely cases when the variables are needed (for example in provider configurations) and working that out is not simple. It might be that we can revisit what it would cost to fix this for all Terraform use cases.
