### ISSUE TITLE
Error: Duplicate object key on terraform output during apply states

### ISSUE THREAD

**Issue by Ara4Sh** [hashicorp/terraform#24495] opened 2020-03-29 14:16 UTC
During apply, I got the following error, but after that with changing nothing and run `terraform refresh`
everything will work as expected.
Also, I don't want to use ellipses because my result is not an array and I don't know its a provider issue or not.

### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
output "float_ips" {
    value = {
        for fip in openstack_networking_floatingip_v2.fip:
            fip.fixed_ip => fip.address
    }
}
```

### Expected Behavior
```
float_ips = {
  "192.168.1.3" = "172.16.16.2"
}
```

### Actual Behavior
```
Error: Duplicate object key

  on deploy.tf line 35, in output "float_ips":
  33:
  34:
  35:             fip.fixed_ip => fip.address
  36:
    |----------------
    | fip.fixed_ip is ""

Two different items produced the key "" in this 'for' expression. If
duplicates are expected, use the ellipsis (...) after the value expression to
enable grouping by key.
```

### Steps to Reproduce
```
terraform apply
```

### Additional Context
if you run `terraform refresh` you will get the expected result.

**Comment by danieldreier** [comment] 2020-04-10 23:19
@Ara4Sh it looks like `openstack_networking_floatingip_v2.fip` doesn't have the information you were expecting. In itself, this error doesn't show a bug in terraform core. I don't know enough about the OpenStack provider to tell you what to expect there, though I don't immediately see evidence of a bug in that provider either.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, you could open an issue with the [OpenStack provider](https://github.com/terraform-providers/terraform-provider-openstack). If you do that, please follow their issue template and include more detail of your environment such that they can reproduce it on their end.

I recommend you take this to the community forum for assistance in troubleshooting. I'm going to close this for now, because I think the community forum is the right approach.

**Closed by danieldreier** 2020-04-10 23:19 UTC
