### ISSUE TITLE
getting access denied when trying to download terraform installer

### ISSUE THREAD

**Issue by VigneshPonraj** [hashicorp/terraform#27866] opened 2021-02-22 17:21 UTC
##[error]Error: Failed to download Terraform from url https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_windows_amd64.zip. Error Error: Unexpected HTTP response: 403

Tried manually going to the url 
https://www.terraform.io/downloads.html

**Comment by treyhendon** [comment] 2021-02-22 17:22
Was coming to report.  The HashiCorp Services Status page does not a "report an issue" option, but shows all is well. https://status.hashicorp.com/

**Comment by treyhendon** [comment] 2021-02-22 17:23
Getting similar to this Vagrant issue several years ago: https://github.com/hashicorp/vagrant/issues/6298

**Comment by pcwiek** [comment] 2021-02-22 17:23
Same with the provider registry

```
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file

Error: Failed to install provider

Error while installing hashicorp/aws v3.20.0: could not query provider
registry for registry.terraform.io/hashicorp/aws: failed to retrieve
authentication checksums for provider: 403 Forbidden
```

**Comment by jpke** [comment] 2021-02-22 17:24
dunno if this is related?
```
Error verifying checksum for provider "aws"
The checksum for provider distribution from the Terraform Registry
did not match the source. This may mean that the distributed files
were changed after this version was released to the Registry.
```

**Comment by dsavell** [comment] 2021-02-22 17:24
Getting the same issue. On any download under the folowing:

releases.hashicorp.com/terraform/
403 Forbidden
    Code: AccessDenied
    Message: Access Denied

**Comment by AbirAbbas** [comment] 2021-02-22 17:24
Getting a similar issue, seems like the registry is returning 404 not found

**Comment by kubadawczynski** [comment] 2021-02-22 17:25
There is official info 
![image](https://user-images.githubusercontent.com/16541477/108745391-4e2ca100-753b-11eb-8637-ea29d7e757d5.png)

**Comment by flurdy** [comment] 2021-02-22 17:25
403 Forbidden on download links from https://www.terraform.io/downloads.html. S3 access related perhaps

**Comment by jboero** [comment] 2021-02-22 17:27
Works for me in UK.  This is probably another CDN sync issue.

**Comment by jboero** [comment] 2021-02-22 17:28
I've tried VPNs to USA, 4 EU countries, all work.  Maybe this is regional to APJ?

**Comment by jcollum** [comment] 2021-02-22 17:30
@kubadawczynski please link the page where you found that outage notification

**Comment by jboero** [comment] 2021-02-22 17:31
It won't help providers but installing the binaries can still be done by our RPM/DEB repos:
```
# RPM systemd distros:
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

# APT or DEB systemd distros:
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
```

**Comment by jcf** [comment] 2021-02-22 17:31
Running `terraform init` locally *from the UK* does not work for me. I'm seeing the same issues with checksums and downloading providers on Terraform Cloud.

```
Error: Failed to install provider

Error while installing hashicorp/random v3.1.0: could not query provider
registry for registry.terraform.io/hashicorp/random: failed to retrieve
cryptographic signature for provider: 404 Not Found
```

**Comment by jboero** [comment] 2021-02-22 17:31
> I'm in the US, getting a 404 on https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_darwin_amd64.zip

Strange I'm getting 403 on that.  Hmm

**Comment by ruairidhwm** [comment] 2021-02-22 17:32
Still getting a 404 here in Scotland.

**Comment by jcollum** [comment] 2021-02-22 17:33
@jboero i'm getting 403 via the url but 404 via `tfenv` tool

**Comment by jboero** [comment] 2021-02-22 17:33
Thanks for the update. Browsing works but direct links don't.  Support is on this.

**Comment by CaptainStealthy** [comment] 2021-02-22 17:35
I'm getting 403's galore in Canada... both when downloading binaries directly as well as `terraform init`

**Comment by Fresa** [comment] 2021-02-22 17:43
seems it's coming back now!

**Comment by hinchley2018** [comment] 2021-02-22 17:46
We saw this issue in US as well. Then it seems like its working now glad to see such a quick resolution! 👏

**Comment by cpaggen** [comment] 2021-02-22 17:47
> We saw this issue in US as well. Then it seems like its working now glad to see such a quick resolution! 👏

Well .. the change they introduced in the providers path broke essentially everything. Doesn't get much worse :)

**Comment by danieldreier** [comment] 2021-02-22 18:05
Hi! I really appreciate everyone reporting this. The root cause here is an incident in the releases.hashicorp.com and registry infrastructure. I'm going to close this and related issues and consolidate any ongoing discussion into https://github.com/hashicorp/terraform/issues/27872. Please do let us know in that issue if you are still having trouble downloading Terraform or providers.

**Closed by danieldreier** 2021-02-22 18:05 UTC
