### ISSUE TITLE
Feature Request: Vsphere_Virtual_machine - TAGS

### ISSUE THREAD

**Issue by jare19** [hashicorp/terraform#7753] opened 2016-07-21 18:00 UTC
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)

- vsphere_virtual_machine

I would like to request the ablitly to add vpshere tags via terraform.  This is useful for reporting/stats/logging.

seems like it should be an 'easy' fix/addition, the command is
`New-Tag –Name “jsmith” –Category “Owner”`

**Comment by stack72** [comment] 2016-07-26 22:14
Hi @jare19 

Closing this as a duplicate of #7515 - that way we can track any progress within the same issue

Paul

**Closed by stack72** 2016-07-26 22:14 UTC
Labels: enhancement, provider/vsphere
