### ISSUE TITLE
Terraform crash on branch change

### ISSUE THREAD

**Issue by dtf-cdtrb** [hashicorp/terraform#30907] opened 2022-04-21 07:29 UTC
Hi, 

I developed some feature on a branch and applied the changes to my remote backend. I had to revert the applied changes so moved back to my main and tried to run plan/apply to remove the added resources from the state and i got this error:

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
runtime error: invalid memory address or nil pointer dereferencegoroutine 4491 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x2d7a6a0, 0x4a4ed80})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0x1031c27, {{}, 0x4d, {0xc000841260, 0x25}, {0xc0006005c0, 0x1c}}, {0xc004534780, 0x600, 0x4})
        /home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x24c72b06600, {0xc0002a4760, 0x45, 0x24c4d580a28}, {{}, 0x4d, {0xc000841260, 0x25}, {0xc0006005c0, 0x1c}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc0012f8048, {0xc0002a4760, 0x1, 0x1}, {{}, 0x4d, {0xc000841260, 0x25}, {0xc0006005c0, 0x1c}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc0012f9968, {0xc0002a4740, 0x2, 0x2}, {{}, 0x4d, {0xc000841260, 0x25}, {0xc0006005c0, 0x1c}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc0017250a0, {{}, {0xc0002a4740, 0x2, 0x2}, {{}, 0x4d, {0xc000841260, 0x25}, {0xc0006005c0, ...}}})
        /home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc0021dab70, {0x3658680, 0xc003f4c0e0})
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc0021dab70, {0x3658680, 0xc003f4c0e0})
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x3658680, 0xc003f4c0e0}, 0x80)
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000ef2620, {0x3658680, 0xc003f4c0e0}, {0x24c7292b9c0, 0xc0021dab70})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x30b1fc0, 0xc0021dab70})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000c07200, {0x30b1fc0, 0xc0021dab70}, 0xc003c7f4c0)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf85ject/project/internal/dag/walk.go:304 +0xf85
        
This is my terraform version:

Terraform v1.1.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.6.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0

**Comment by jbardin** [comment] 2022-04-21 13:23
Duplicate of #30110

**Closed by jbardin** 2022-04-21 13:23 UTC
Labels: bug, new
