### ISSUE TITLE
Crash during Terraform Destroy with remote state on non-existent region

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#4008] opened 2015-11-21 15:01 UTC
```
$ AWS_DEFAULT_REGION=us-west-2 terraform destroy
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48ff15]

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0xadb650, 0x19, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:18 +0x1b5
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:128 +0x85
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc2080b0810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:85 +0x61
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc2080b0840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:65 +0xd8
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc208040960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:182 +0xed
github.com/hashicorp/terraform/state/remote.s3Factory(0xc2080b0780, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/state/remote/s3.go:71 +0x988
github.com/hashicorp/terraform/state/remote.NewClient(0xc20802bf88, 0x2, 0xc2080b0780, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/state/remote/remote.go:33 +0x1e2
github.com/hashicorp/terraform/command.remoteState(0xc2080a1c80, 0xc2080dd1e0, 0x1c, 0x9de01, 0xc20802cfc0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/state.go:212 +0x112
github.com/hashicorp/terraform/command.remoteStateFromPath(0xc2080dd1e0, 0x1c, 0x1411e01, 0xc2080414a0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/state.go:275 +0x10c
github.com/hashicorp/terraform/command.State(0xc208041400, 0xc208041400, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/state.go:95 +0xcf1
github.com/hashicorp/terraform/command.(*Meta).State(0xc208058700, 0x0, 0x0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/meta.go:213 +0x8a
github.com/hashicorp/terraform/command.(*Meta).Context(0xc208058700, 0x7fff5fbffc04, 0x3a, 0xacc790, 0x11, 0x100, 0xa, 0x4, 0x0, 0x0, ...)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/meta.go:142 +0x47a
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc208058700, 0xc20800a010, 0x0, 0x0, 0xc208036e58)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/apply.go:103 +0xd51
github.com/mitchellh/cli.(*CLI).Run(0xc20808d810, 0xc2080a15c0, 0x0, 0x0)
    /Users/James/Code/go/src/github.com/mitchellh/cli/cli.go:112 +0x5be
main.wrappedMain(0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/main.go:146 +0xb1c
main.realMain(0x0)
    /Users/James/Code/go/src/github.com/hashicorp/terraform/main.go:82 +0x923
main.main()
    /Users/James/Code/go/src/github.com/hashicorp/terraform/main.go:18 +0x1f

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/Cellar/go14/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/Cellar/go14/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive]:
main.func·014()
    /Users/James/Code/go/src/github.com/hashicorp/terraform/commands.go:134 +0x52
created by main.makeShutdownCh
    /Users/James/Code/go/src/github.com/hashicorp/terraform/commands.go:137 +0x1b4

goroutine 9 [semacquire]:
sync.(*Cond).Wait(0xc2080d83f0)
    /usr/local/Cellar/go14/1.4.2/libexec/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2080d83c0, 0xc2080ef000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go14/1.4.2/libexec/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc20803e1f8, 0xc2080ef000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go14/1.4.2/libexec/src/io/pipe.go:134 +0x5b
bufio.(*Scanner).Scan(0xc20809e700, 0x0)
    /usr/local/Cellar/go14/1.4.2/libexec/src/bufio/scan.go:180 +0x688
github.com/hashicorp/terraform/command.func·006()
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/meta.go:323 +0x3d
created by github.com/hashicorp/terraform/command.(*Meta).flagSet
    /Users/James/Code/go/src/github.com/hashicorp/terraform/command/meta.go:326 +0x5a6



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by apparentlymart** [comment] 2017-04-05 22:46
I've been unable to reproduce this so I'm forced to assume that it was resolved by some of the big refactoring of remote backends that happened in 0.9.

If anyone encounters problems similar to this, I suggest opening a fresh issue for it since the relevant parts of Terraform have changed considerably since whatever version this was (based on the date the issue was opened) and so we'd need to start over with debugging it.

Thanks!

**Closed by apparentlymart** 2017-04-05 22:46 UTC
Labels: bug, core, crash
