### ISSUE TITLE
make a local backup of .tfstate files

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/terraform#13028] opened 2017-03-23 23:12 UTC
Using this backend with TF 0.9.1

```
terraform {
  backend "s3" {
    region = "us-west-2"
    bucket = "foo-bar-tf"
    key = "my-env.tfstate"
    lock_table = "dyno-mite-lock"
  }
}
```

Creating a new environment from scratch.

After `terraform init` a minimal `terraform.tfstate` file is created locally in `.terraform`, along with symlinks to modules.

After `terraform apply` the `.tfstate` file is updated in S3 but not locally.

Please update the local copy after each update to the remote file in the backend.

**Comment by vincentkwok** [comment] 2017-04-05 09:01
Agree. The current practice needs to check s3 every time to check config, especially fix the new AWS config options without recreating resources.

**Comment by apparentlymart** [comment] 2017-04-05 16:24
Hi @FlorinAndrei and @vincentkwok!

It was an intentional change in 0.9 to no longer maintain a local cache of the state, since it tended to cause more bugs and issues than benefit. It is therefore by design that Terraform always talks to the remote backend to get updated state.

We understand that there are use-cases where having local access to the raw state file is useful. To accommodate that, [the `terraform state pull` command](https://www.terraform.io/docs/commands/state/pull.html) will retrieve the state from the backend and write it to stdout, from which you can redirect it to a file. The opposite is also possible: [the `terraform state push` command](https://www.terraform.io/docs/commands/state/push.html) allows you to upload a local state file to the configured remote backend.

Note that while the file in `.terraform` might look like a state file (which we do for transitional reasons) it is *not* actually a state file and you should not try to overwrite it with an actual state file. Instead, use the `terraform state pull` and `terraform state push` commands to ensure that the relevant safety checks are run.

By making this explicit it is possible for Terraform to do more checks and produce better error messages when things are not working as expected, whereas before the implied pulling and pushing would often cause weird situations that were hard to diagnose and resolve.

I hope the above information is useful to support the use-cases you both have for local copies of state. Since this was an intentional design change I'm going to close this. Thank you for taking the time to open this request!

**Closed by apparentlymart** 2017-04-05 16:24 UTC
Labels: enhancement, state/remote/s3
