### ISSUE TITLE
could not query provider registry for registry.terraform.io/hashicorp/vsphere: failed to retrieve authentication checksums for provider: 404 Not Found

### ISSUE THREAD

**Issue by cpaggen** [hashicorp/terraform#27867] opened 2021-02-22 17:24 UTC
### Terraform Version
```
0.14.4
```

### Terraform Configuration Files
```
terraform {
  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = "1.24.3"
    }
  }
}

provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.datacenter_name
}
```

### Debug Output
Terraform v0.14.4
Initializing plugins and modules...

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/vsphere versions matching "1.24.3"...

Error: Failed to install provider

Error while installing hashicorp/vsphere v1.24.3: could not query provider
registry for registry.terraform.io/hashicorp/vsphere: failed to retrieve
authentication checksums for provider: 404 Not Found

Operation failed: failed running terraform init (exit 1)

### More context
This has been running fine for weeks and suddenly stopped. Note that I'm starting my plan from TF cloud; the code is executed on a TF cloud agent. I restarted the agent, rm -rf .terraform.d and that did not help. It just refuses to fetch the checksum for the vsphere provider. The problem started occurring roughly 35 minutes ago (9am PST).

**Comment by dsavell** [comment] 2021-02-22 17:27
Hey, looks like it could be related to this aswell: https://github.com/hashicorp/terraform/issues/27866

**Comment by rrazor** [comment] 2021-02-22 17:29
I'm seeing this for `hashicorp/aws` on at least `3.28.0` and `3.29.0` as well.

**Comment by Lasering** [comment] 2021-02-22 17:30
The urls for providers in the registry were:
```
registry.terraform.io/hashicorp/vsphere
```
But now they are:
```
registry.terraform.io/providers/hashicorp/vsphere
```
Notice the extra `/providers`. This is what is causing the error.

**Comment by igorescobar** [comment] 2021-02-22 17:33
Any workaround? 🤔

**Comment by trinitroglycerin** [comment] 2021-02-22 17:35
Find the provider in a different `.terraform` folder on your machine? :D

**Comment by rrazor** [comment] 2021-02-22 17:39
I worked around things by identifying the most recent provider version I had in my `.terraform.d/plugin-cache` and setting the `version` in `required_providers` to exactly that.

**Comment by cpaggen** [comment] 2021-02-22 17:44
@rrazor - would you kindly share the exact steps to do that? In my case, I'm starting terraform from tfcloud via an agent running on-prem.

**Comment by cpaggen** [comment] 2021-02-22 17:48
Looks like Hashicorp is aware of the issue - [https://status.hashicorp.com/](https://status.hashicorp.com/ )

**Comment by danieldreier** [comment] 2021-02-22 18:05
Hi! I really appreciate everyone reporting this. The root cause here is an incident in the releases.hashicorp.com and registry infrastructure. I'm going to close this and related issues and consolidate any ongoing discussion into https://github.com/hashicorp/terraform/issues/27872. Please do let us know in that issue if you are still having trouble downloading Terraform or providers.

**Closed by danieldreier** 2021-02-22 18:05 UTC
Labels: bug, new
