### ISSUE TITLE
Error download binary package

### ISSUE THREAD

**Issue by robertolabarca** [hashicorp/terraform#25971] opened 2020-08-23 16:20 UTC
![Screenshot_2020-08-23-12-13-03](https://user-images.githubusercontent.com/3769893/90983300-0e104580-e53b-11ea-8392-4c35c969e950.png)

**Comment by danieldreier** [comment] 2020-08-23 16:44
Is this still happening? I just tried and was able to use releases.hashicorp.com

**Comment by danieldreier** [comment] 2020-08-24 18:20
@robertolabarca I'm going to close this because I haven't been able to reproduce it, and I think we would have seen more reports. I suspect that there was a temporary CDN outage. If you or anyone else is still seeing this, please let me know!

**Closed by danieldreier** 2020-08-24 18:20 UTC
Labels: bug, new
