### ISSUE TITLE
DIR paramater for `terraform apply` does not work on Windows

### ISSUE THREAD

**Issue by AndrewSav** [hashicorp/terraform#24701] opened 2020-04-18 05:21 UTC
I attempted to triage this issue at [terraform google groups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/terraform-tool/J8Z00pLRMEc)

### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

`a.tf`:

```hcl
locals {
  hello = "world"
}
```

### Debug Output
<https://gist.github.com/AndrewSav/30f6140cd97fcca5b4297fbc0dc495ac>

### Expected Behavior
`a.tf` should have been processed.

### Actual Behavior
terraform failed to apply

### Steps to Reproduce

```text
E:\tf>terraform init

Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

E:\tf>terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Now cd out of that folder and run terraform apply DIR. Observe the error:

```text
E:\>terraform apply E:\tf

Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: No configuration files

Apply requires configuration to be present. Applying without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run 'terraform destroy' instead.
```

### Additional Context

I'm getting the same error with the mock tf configuration as above and with my actual complex terraform script.

Both [documentation](https://www.terraform.io/docs/commands/apply.html) and built-in command like help suggest that this should work.

**Comment by danieldreier** [comment] 2020-04-24 00:09
hey @AndrewSav I really appreciate all the due diligence you did in verifying this ahead of the bug report. I just tested it on my OS X workstation, and it works here for a relative path, so I'm guessing that this is a Windows-specific issue. You've clearly done your homework here so I'm going to categorize this as a windows-specific CLI bug.

I'm not a very regular Windows user, but I wonder if you could work around this in your scripting by using the Start-Process cmdlet with the -WorkingDirectory parameter as per [this stackoverflow](https://superuser.com/questions/396394/how-do-i-set-an-executables-working-directory-via-the-command-line-prior-to-ex).

**Comment by AndrewSav** [comment] 2020-04-24 00:24
@danieldreier thank you for the work around, and for you work on classifying this as a bug. I'm sure it will be helpful for many people in this situation. 

It has a disadvantage if popping up a new windows. You lose focus, and also, if there is anything you'd care to see in this new window, you won't be able either, because it will be closed on completion. Those things are possible to work around too, with various degree of convenience, but they will take time to put in for anyone faced with this issue.

**Comment by danieldreier** [comment] 2020-04-24 00:31
@AndrewSav I didn't realize that would pop up a new window. How about [Push-Location](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/push-location?view=powershell-7)? I haven't tried, but in your scripting you'd do something like:

```powershell
Push-Location E:\tf
terraform apply
Pop-Location
```

This should take you back to your original location after Terraform finishes without losing output history.

**Comment by AndrewSav** [comment] 2020-04-24 00:47
@danieldreier, thank you, `Push-Location` and `Pop-Location` is what I initially started with. To give you an idea what I ended up with, I'll quote a part of my post from the terraform google group from earlier:

>So I'm using terraform in a powershell provisioning script, that does other stuff too. The script is configure to terminate on errors. I used to `cd` to the terraform directory in a script and that all worked perfectly.

>However if terraform throws a error, I end up at command line at a wrong folder and need to cd manually back which is annoying.

>So I went to consult some people proficient in powershell, to find out how can I restore the current folder automatically.

>And they told me, "dude, do not cd in your script, you are shooting yourself in the foot". And I was like, "but I use some command line tools that work off the current folder!" and they were like "in 2020? Now we are curious, what tool those might be?" And I : "terraform", and the go google a bit about what terraform is and say "here, it accepts dir parameter, problem solved", and I try it, it is not working, and they say. "oh well, if this is a bug in a tool you are using, may be you should report and get it fixed"

So all in all, unfortunately it's not that simple.

I ended up wrapping several parts of my script in try-catches and restoring the directory in the end of each: powershell unfortunately has an [unhappy history](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/1583) of error handing and does not make it easy, there are terminating and not terminating errors, command line and cmdlet errors are processed differently, and those two are different from processing .net thrown exceptions, should you call a .net method. So the immediate problem is solved for me for now. Yet, I'm looking forward for this terraform issue to be fixed eventually.

Once again, thank you for taking it up.

**Comment by danieldreier** [comment] 2020-06-16 00:14
@AndrewSav I've reproduced this on a Windows 10 VM, and noticed that this problem only seems to happen when absolute paths are specified. Using a relative path, it works for me on 0.12.26 and 0.13.0 beta 1. Using an absolute path, I see the same behavior you described. This is interesting because we just, just fixed a different issue around absolute file paths in Windows in https://github.com/hashicorp/terraform/issues/25068.

I just tested the issue you reported against a development build of master that has that fix merged in, and from my testing, the issue you reported now appears to be fixed.

If you want to test it yourself, this will be available in 0.13.0 beta 2 on Wednesday June 17th. Thank you again for reporting this!

**Comment by mildwonkey** [comment] 2020-08-27 15:02
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!

**Closed by mildwonkey** 2020-08-27 15:02 UTC
Labels: bug, cli, powershell, v0.12, waiting-response, windows

**Comment by AndrewSav** [comment] 2020-08-27 20:25
I just tested the steps in OP with 0.13 and they work as expected. thank you for the fix @danieldreier !
