### ISSUE TITLE
Partial default for map variable

### ISSUE THREAD

**Issue by nsmeef** [hashicorp/terraform#16517] opened 2017-11-01 09:27 UTC
I think this would be a nice feature, where we could partially specify overrides for the default values of a `map` and default to the defaults for the non-specified values.

I have a `map` variable defined below.

    variable "cloudwatch" {
      type = "map"

      default = {
        error_evaluation_window_40x = 60
        error_threshold_40x         = 300
        error_evaluation_window_50x = 60
        error_threshold_50x         = 50
      }

      description = "Parameters to define the cloudwatch alarms for 4/50x errors coming out of instances associated with the ELB"
    }

When overriding the defaults of the `map`, it would be nice to partially specify like below.

    cloudwatch = {    
      error_threshold_40x = 100
      error_threshold_50x = 50
    }

The output of that would be -

    error_evaluation_window_40x = 60
    error_threshold_40x         = 100
    error_evaluation_window_50x = 60
    error_threshold_50x         = 50

**Comment by apparentlymart** [comment] 2017-11-01 14:12
Hi @NSmeef! Thanks for this suggestion.

While I can definitely see some use-cases for this, our experience with other features has shown that this sort of "merging" of values is often confusing in practice, since it is not explicit in the configuration (and is thus not obvious to people less familiar with Terraform) and different people have different expectations for which of the sets should take priority, whether merging should be done "deeply", etc.

I would suggest instead to use the "local values" feature to specify the merging behavior explicitly, which then makes it more explicit to readers of the configuration and gives you control over how the merging is performed:

```hcl
variable "cloudwatch" {
  type = "map"
  default = {}
}

locals {
  default_cloudwatch = {
    error_evaluation_window_40x = 60
    error_threshold_40x         = 300
    error_evaluation_window_50x = 60
    error_threshold_50x         = 50
  }
  cloudwatch = "${merge(local.default_cloudwatch, var.cloudwatch)}"
}
```

You can then reference the merged value elsewhere in the module using `${local.cloudwatch}`.

It is admittedly unfortunate that this approach "hides" the default inside the locals block where it can't easily be seen by the caller referring to the `variable "cloudwatch"` block. We could perhaps mitigate that by providing some way to obtain the _default_ value of a variable even when it is overridden by the caller, like this:

```hcl
# DESIGN SKETCH: not actually implemented, may change

variable "cloudwatch" {
  type = "map"
  default = {
    error_evaluation_window_40x = 60
    error_threshold_40x         = 300
    error_evaluation_window_50x = 60
    error_threshold_50x         = 50
  }
}

locals {
  # "default.var.cloudwatch" here is an example of one way we might
  # support referencing the default value of this variable even if overridden.
  cloudwatch = "${merge(default.var.cloudwatch, var.cloudwatch)}"
}
```

I think that approach warrants some more thought before we try to implement it, but hopefully my earlier example above allows you to achieve your goals in the mean time, at the expense of having to document the variable more carefully so the defaults are known.

**Comment by Midacts** [comment] 2018-12-12 20:13
Thanks for the example. Super helpful to figure out how to do partial variables with maps.

**Comment by dolkensp** [comment] 2019-09-05 16:09
Hi @apparentlymart 

When you revisit this, can you also consider deep-merging.

I've been trying to set up a variant of this where we load a `config` object, which is then passed around as necessary, and contains various default settings for different providers.

Inside this object are provider-specific maps, which then contain their own independent default values

The issue I ran into was that we want to, for example, change *just* the region for one of the providers, the merge operation clears all the other values from the nested map.

I attempted to resolve by flattening the structure, using provider prefixes, instead of a provider object, but immediately ran into the same issue when trying to set defaults that had been nested a level deeper (in this case, we may wish to add **additional** app settings depending on the workspace)

**Comment by torbendury** [comment] 2022-11-22 09:00
Hi everyone! I found that this issue is not closed - is this a feature that is being considered for future implementation? It would be great to keep a good set of _defaults_ in our `variables.tf`, and override them partially with another map. This way we could prevent too much duplicated code in staged environments.

However I also understand that this might break existing TF code if users were 'used to' overriding a whole map.

**Comment by apparentlymart** [comment] 2023-05-17 14:16
Hi all,

Given the age of this issue and the syntax used in the early comments, this seems to be talking either about Terraform v0.11 or about v0.12 while still using some legacy syntax that Terraform supported for backward compatibility.

The type constraint `type = "map"` (with the keyword quoted and with no element type specified) is a legacy of Terraform v0.11 and earlier and should not be used in modern Terraform.

Now that modern Terraform has a distinction between map types (an arbitrary number of key/value pairs where all values are of the same type) and object types (a fixed set of attributes that can each have their own type), the answer to this issue depends on which way we interpret the opening example.

If it was intended as a fixed set of attributes that all happen to be of type `number` then indeed optional object attributes could be a plausible answer here:

```hcl
variable "cloudwatch" {
  type = object({
    error_evaluation_window_40x = optional(number, 60)
    error_threshold_40x = optional(number, 300)
    error_evaluation_window_50x = optional(number, 60)
    error_threshold_50x = optional(number, 50)
  })
  default = {}

  description = "Parameters to define the cloudwatch alarms for 4/50x errors coming out of instances associated with the ELB"
}
```

The above type constraint says that all values for this variable should have exactly these four attributes but if the caller doesn't set any of them then Terraform should complete the object by filling in the specified default values. The whole variable's default then becomes `{}`, which Terraform will convert to the specified type by filling in the default attributes, so the whole default is effectively the same as before.

Since all of the values in the example are numbers, another possible interpretation is that this is a map of numbers with arbitrary keys chosen by the caller:

```hcl
variable "cloudwatch" {
  type = map(number)
  default = {}

  description = "Parameters to define the cloudwatch alarms for 4/50x errors coming out of instances associated with the ELB"
}
```

In this case the keys of the map are decided by the value of the variable rather than the type of the variable, so Terraform itself cannot provide automatic insertion of a default set of key/value pairs into the provided value, but you can still use the technique with the explicit call to `merge` as I showed in my earlier comment, updated here for modern syntax:

```hcl
locals {
  default_cloudwatch = {
    error_evaluation_window_40x = 60
    error_threshold_40x         = 300
    error_evaluation_window_50x = 60
    error_threshold_50x         = 50
  }
  cloudwatch = merge(local.default_cloudwatch, var.cloudwatch)
}
```

In practice the second case with maps doesn't seem to arise often enough to justify a built-in language feature, whereas the situation with object types arises each time a new attribute is added to an existing module (which would otherwise be a breaking change) so that justified a built-in feature to manage it.

With all of the above in mind, I'm going to close this. If you find this issue and are trying to achieve a result that neither of my examples above can achieve then please open a new issue to discuss that use-case, and then we can discuss it in terms of modern Terraform rather than the old version that was current when this issue was first opened. Thanks!

**Closed by apparentlymart** 2023-05-17 14:16 UTC
Labels: enhancement, config
