### ISSUE TITLE
module.cloud_router.google_compute_router_nat.nats["nat-dh329"] still contains unknown values during apply

### ISSUE THREAD

**Issue by SmartassSkeleton** [hashicorp/terraform#26262] opened 2020-09-16 14:49 UTC
### Terraform Version

```
Terraform v0.12.29
+ provider.external v1.2.0
+ provider.google v3.35.0
+ provider.google-beta v3.35.0
+ provider.kubernetes v1.13.2
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2

```

### Terraform Configuration Files

```terraform
module "cloud_router" {
  source  = "terraform-google-modules/cloud-router/google"
  version = "~> 0.2"

  name    = "${var.region}-cloud-router"
  project = var.project_id
  region  = var.region
  network = module.vpc.network_self_link
  nats    = [
    {
      name       = "nat-dh329"

      nat_ips                = module.nat-ips[1].self_links
      nat_ip_allocate_option = "MANUAL_ONLY"

      source_subnetwork_ip_ranges_to_nat = "LIST_OF_SUBNETWORKS"

      subnetwork = [
        {
          name = module.vpc.subnets_self_links[3]
          source_ip_ranges_to_nat = ["PRIMARY_IP_RANGE", "LIST_OF_SECONDARY_IP_RANGES"]
          secondary_ip_range_names = [
            "${module.vpc.subnets_names[3]}-services",
            "${module.vpc.subnets_names[3]}-pods",
          ]
        },
      ]
    }
  ]
}
```

### Expected Behavior

Resource created

### Actual Behavior

After `terraform apply` I get the following error:
```
module.network.module.cloud_router.google_compute_router_nat.nats["nat-infra"]: Creating...

Error: configuration for module.network.module.cloud_router.google_compute_router_nat.nats["nat-infra"] still contains unknown values during apply (this is a bug in Terraform; please report it!)
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Additional Context

As default as it gets

**Comment by alisdair** [comment] 2020-09-18 18:31
Hi @SmartassSkeleton, thanks for reporting this. I'm unable to reproduce this bug without a more complete configuration. A simple invocation of the cloud-router module works fine for me with Terraform 0.12.29:

```hcl
provider "google" {
  version = "~> 3.0"
}

module "cloud-router" {
  source  = "terraform-google-modules/cloud-router/google"
  version = "0.2.0"

  name    = "example-router"
  project = "terraform-core-alisdair"
  network = "default"
  region  = "us-central1"
}
```

Please provide a complete, runnable configuration which demonstrates the issue, so that we can determine the cause. This means either simplifying the configuration to remove references to other modules, or including the minimal source of those modules in your report. Thanks!

**Comment by pselle** [comment] 2021-02-12 20:36
Hi there, since this has been open and waiting for a response and reproduction and does not have one, I am going to close it.

**Closed by pselle** 2021-02-12 20:36 UTC
Labels: bug, waiting for reproduction, waiting-response
