### ISSUE TITLE
Provider Developer Override Warning Not Shown in Plan Command

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#27481] opened 2021-01-12 18:13 UTC
### Terraform Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.23.0
```

### Terraform Configuration Files

```hcl
provider_installation {
  dev_overrides {
    "hashicorp/aws" = "/Users/bflad/go/bin"
  }

  filesystem_mirror {
    path = "/Users/bflad/.terraform.d/providers"
  }

  direct {}
}
```

```terraform
terraform {
  required_version = "0.14.4"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.23.0"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

resource "aws_codepipeline" "test" {
  # ... configuration ...
}
```

### Expected Behavior

```console
$ terraform plan

Warning: Provider development overrides are in effect

The following provider development overrides are set in the CLI configuration:
 - hashicorp/aws in /Users/bflad/go/bin

The behavior may therefore not match any released version of the provider and
applying changes may cause the state to become incompatible with published
releases.

aws_iam_role.test: Refreshing state... [id=bflad-testing]
aws_s3_bucket.test: Refreshing state... [id=bflad-testing]
aws_iam_role_policy.test: Refreshing state... [id=bflad-testing:codepipeline_policy]
aws_codepipeline.test: Refreshing state... [id=bflad-testing]

An execution plan has been generated and is shown below.
...
```

### Actual Behavior

The provider is actually using the development override, however, the top warning is not present.

```console
$  terraform plan
aws_iam_role.test: Refreshing state... [id=bflad-testing]
aws_s3_bucket.test: Refreshing state... [id=bflad-testing]
aws_iam_role_policy.test: Refreshing state... [id=bflad-testing:codepipeline_policy]
aws_codepipeline.test: Refreshing state... [id=bflad-testing]

An execution plan has been generated and is shown below.
...
```

Works fine with `apply` command.

```console
$ terraform apply

Warning: Provider development overrides are in effect

The following provider development overrides are set in the CLI configuration:
 - hashicorp/aws in /Users/bflad/go/bin

The behavior may therefore not match any released version of the provider and
applying changes may cause the state to become incompatible with published
releases.

aws_iam_role.test: Refreshing state... [id=bflad-testing]
aws_s3_bucket.test: Refreshing state... [id=bflad-testing]
aws_iam_role_policy.test: Refreshing state... [id=bflad-testing:codepipeline_policy]
aws_codepipeline.test: Refreshing state... [id=bflad-testing]

An execution plan has been generated and is shown below.
...
```

### Steps to Reproduce

1. Setup terraformrc file with development override (setting TF_CLI_CONFIG_FILE environment variable if necessary)
1. `terraform plan`

### References

* https://www.terraform.io/docs/commands/cli-config.html#development-overrides-for-provider-developers

**Comment by apparentlymart** [comment] 2021-01-14 02:08
Thanks for reporting this, @bflad.

Warnings for `terraform plan` typically appear at the _end_ of the output, just after the "Changes to outputs" section (if present), and so I'd expect that warning to appear there rather than at the start as you showed, but indeed I reproduced that it seems to not be shown at all:

```
$ TF_CLI_CONFIG_FILE=cliconfig.tfrc terraform plan
Terraform used the selected providers to generate the following
execution plan. Resource actions are indicated with the following
symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + boop = "boop"

────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so
Terraform can't guarantee to take exactly these actions if you
run "terraform apply" now.
```

I suspect that because that warning emerges from an unusual spot which doesn't typically produce warnings, the call to it in `terraform plan` is not correctly propagating non-error diagnostics through to the end where we show all of the collected warnings. (A somewhat-common mistake is to check if there are errors and exit early if so, but otherwise to proceed on and then incorrectly clobber the diagnostics object with the result of a later operation, causing the warnings from the first call to be lost.)

**Comment by apparentlymart** [comment] 2021-01-14 02:18
It turns out that this one is actually more straightforward than other similar bugs we've seen before: the call to generate that warning is just not present at all in the `terraform plan` command, for some reason.

It also turns out that introducing it in the same way as the other commands handle it makes it an exception to the usual rule about warnings appearing at the end, because this particular warning is handled by the `command` package rather than by the `local` backend, and so it ends up getting printed out just before the general CLI delegates to the selected backend.

I considered trying to make it consistent with the other warnings but it seemed like more work than it was worth, and I think it's actually pretty justified to show this particular warning early anyway, because it might present an explanation for odd behavior that follows it, such as the provider crashing or hanging during the refresh/plan operations.

With that said then, I'm intending to add this warning to the `terraform plan` command in the same way as it is implemented for the other commands that print it, which will then make it appear up top as illustrated in the "Expected Behavior" of the original issue writeup.

**Comment by mildwonkey** [comment] 2021-06-23 13:44
(this issue should have been closed by the linked PR)

**Closed by mildwonkey** 2021-06-23 13:44 UTC
Labels: bug, confirmed, explained, v0.14, v0.15
