### ISSUE TITLE
jsonencode of map variable does not preserve types

### ISSUE THREAD

**Issue by mkochco** [hashicorp/terraform#24867] opened 2020-05-05 14:04 UTC
### Terraform Version

```
$ terraform -v
Terraform v0.12.24
```

### Terraform Configuration Files

`variables.tf` 

```hcl
variable "test" {
  type = map(any)
  default = {
   "int_field" = 1
   "string_field" = "one"
   "boolean_field" = true
  }
}
```

### Expected Behavior

Types of map values should be preserved when running `jsonencode(var.test)`

```
> jsonencode(var.test)
{"boolean_field":true,"int_field":1,"string_field":"one"}
```

### Actual Behavior

Types are coerced into strings
```
jsonencode(var.test)
{"boolean_field":"true","int_field":"1","string_field":"one"}
```
### Steps to Reproduce

In a clean dir create the `variables.tf` described above then
```
$ terraform init
$ terraform console
> jsonencode(var.test)
{"boolean_field":"true","int_field":"1","string_field":"one"}
```

### References

This is appears to be a continuation of a partial fix to the following issue;
- #17033

**Comment by apparentlymart** [comment] 2020-05-13 02:26
Hi @mkochco,

The type constraint on your variable is `map(any)`, which means "map of any single type". Terraform must therefore select a single concrete type to substitute for `any` (because `any` is a placeholder, not a real type), and because your given default object contains a mixture of strings, numbers, and booleans Terraform selects strings as the most general type, resulting in `map(string)` after substitution.

Terraform then converts all of those values to strings so that they match to the selected type. The `jsonencode` call is not relevant here; this would be true regardless of what you do with that variable value.

If you need attributes of different types then what you need is an [object type](https://www.terraform.io/docs/configuration/types.html#structural-types) rather than a map type.

If you know that you always want that particular set of attributes and types, you can write out the object type explicitly:

```hcl
variable "test" {
  type = object({
    int_field     = number
    string_field  = string
    boolean_field = bool
  })
  default = {
   "int_field"     = 1
   "string_field"  = "one"
   "boolean_field" = true
  }
}
```

The default value has exactly the given type, so no conversion is needed and all of these attribute values can be preserved exactly. If you were to pass this result to `jsonencode` then you'd get the result you wanted.

If you need to except arbitrary attributes rather than predefined ones then the only type constraint that can accept that is `any`, which can substitute for anything:

```hcl
variable "test" {
  type = any
  default = {
   "int_field"     = 1
   "string_field"  = "one"
   "boolean_field" = true
  }
}
```

As always with [`any`](https://www.terraform.io/docs/configuration/types.html#dynamic-types-the-quot-any-quot-constraint), Terraform will attempt to select a concrete type that the `any` placeholder can be replaced with. That's easy in this case because there are no constraints at all, and so Terraform will automatically generate an object type based on your default value, which in this case will match the one we wrote explicitly above: `object({ int_field = number, string_field = string, boolean_field = bool })`. But the difference this time is that the caller of this module were to set any other value, Terraform would select a different concrete type based on that value rather than attempting to convert the given value to the specified type.

There are more details about these behaviors on the [Type Constraints](https://www.terraform.io/docs/configuration/types.html) documentation page. The Terraform language is working as designed here, so I'm going to close this issue. If you have follow-up questions about what I describe above, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) and I can follow up with you there.

**Closed by apparentlymart** 2020-05-13 02:26 UTC
