### ISSUE TITLE
apply doesn't guarantee execution of plan with -target

### ISSUE THREAD

**Issue by frankh** [hashicorp/terraform#13999] opened 2017-04-26 16:46 UTC
Terraform version v0.9.3

If you run terraform plan -target "blah", and "blah" has a bunch of dependencies (depends_on), then the plan will include changes to the target's dependencies

If you then apply the plan, only the -target will change, and not its dependencies

### Expected Behavior

`apply` should *always* match `plan`

### Actual Behavior

`apply` doesn't include all the changes from `plan`

**Comment by apparentlymart** [comment] 2017-04-26 17:02
Hi @frankh! Thanks for reporting this. This is definitely _not_ the expected behavior!

I wasn't able to repro this quickly with a small toy example, which makes me think I'm not correctly replicating the steps you followed. If you have time, it would help a lot if you could include a terminal session showing exactly what commands you ran and what the output was (please summarize/redact anything sensitive) and, if you're able, some minimal configuration that illustrates the problem.

**Comment by apparentlymart** [comment] 2017-05-04 17:45
Since we can't reproduce this with the current information, I'm going to close it. However, if someone is able to show a sequence of commands that illustrates this problem -- ideally with the configuration that goes with it, though in this case not necessarily -- then I'm happy to reopen it.

Thanks!

**Closed by apparentlymart** 2017-05-04 17:45 UTC
Labels: bug, core, waiting-response

**Comment by frankh** [comment] 2017-05-04 18:18
sorry @apparentlymart , I tried to reproduce but it appears it's not going to be simple. will giev it another try and re-open when i figure it out.

I've reproduced it multiple time though - it appears to be limited to updates, not creations of resources
