### ISSUE TITLE
Terraform not removing last egress rule

### ISSUE THREAD

**Issue by mminkus** [hashicorp/terraform#6029] opened 2016-04-05 22:30 UTC
Hey @catsby and whoever else worked on terraform egress rules.

We're running terraform 0.6.11 but also tested and confirmed that the same behaviour occurs on terraform 0.6.14.

If you have a security group with ingress and egress rules, and remove the final egress rule in your code:

eg, change:

```
resource "aws_security_group" "saltmaster_instance_sg" {
  name = "saltmaster-instance-sg"
  description = "Security group for saltmaster instance(s)"
  vpc_id = "${var.vpc}"

  # Allow minions on any vpc to connect to the master on ports 4505-4506
  ingress {
    from_port = 4505
    to_port = 4506
    protocol = "tcp"
    cidr_blocks = ["${var.infra_cidr}", "${var.prod_cidr}", "${var.test_cidr}"]
  }

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

to:

```
resource "aws_security_group" "saltmaster_instance_sg" {
  name = "saltmaster-instance-sg"
  description = "Security group for saltmaster instance(s)"
  vpc_id = "${var.vpc}"

  # Allow minions on any vpc to connect to the master on ports 4505-4506
  ingress {
    from_port = 4505
    to_port = 4506
    protocol = "tcp"
    cidr_blocks = ["${var.infra_cidr}", "${var.prod_cidr}", "${var.test_cidr}"]
  }
}
```

1) Terraform silently doesn't change the security group,
2) Terraform doesn't output anything in the plan with regard to the security group,
3) the egress rule stays in AWS,
4) and the state file keeps it!

We've been removing said egress security groups for some time and only just caught this happening today by chance. (Usually we delete the entire security group, but in this case we needed to keep it for an ingress rule.)

Worse yet, if you go to the console and change the egress rule to something else terraform still doesn't remove it but continues to update its statefile to whatever you do in the aws console.

This clearly appears to be a serious bug as terraform is taking aws as the source of truth and not the terraform code base.

We considered adding in an explicit DENY egress rule but after looking at the documentation there does not appear to be such an ability in terraform.

The documentation also clearly states that it will NOT give you a default allow egress rule like AWS does (which is a behaviour we love btw) so it isn't terraform adding in a default allow egress rule unless its going counter to the terraform documentation. Additionally, it doesn't care what the egress rule is specifically (eg: 0.0.0.0/0 or 8.8.8.8/32 or anything else) it keeps it and silently updates its statefile with it.

We're now going to have to go and audit all our security groups because of this issue.

Can we get confirmation that this is unintended behaviour?

**Comment by jszwedko** [comment] 2016-04-20 23:07
To add on to this, this appears to prohibit terraform users from moving from specifying the rules inline to specifying the rules as separate `security_group_rule` resources as Terraform doesn't remove the existing inline rules, causing a conflict on apply.

**Comment by mminkus** [comment] 2016-04-20 23:12
Agreed. We had this happen as well. Had to manually remove the rules using the AWS console.

**Comment by catsby** [comment] 2016-04-21 21:04
Hello all sorry for the silence. This looks like a duplicate of https://github.com/hashicorp/terraform/issues/2047 , and we're trying to fold any dupes into https://github.com/hashicorp/terraform/issues/2151, so I'm going to close this. Please track over there.

Thanks!

**Closed by catsby** 2016-04-21 21:04 UTC
Labels: bug, provider/aws
