### ISSUE TITLE
Terraform keeps crashing running terraform apply even when using a blank workspace

### ISSUE THREAD

**Issue by baniga** [hashicorp/terraform#24950] opened 2020-05-14 09:16 UTC
[crash.log](https://github.com/hashicorp/terraform/files/4627220/crash.log)
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

**Comment by danieldreier** [comment] 2020-05-18 23:05
@baniga thanks for reporting this. I believe this is actually the same issue as was reproduced in #21588 (comment) because the error message is the same and it also occurs in github.com/zclconf/go-cty/cty.ListVal. We actually just merged the fix for this into the 0.13 branch (https://github.com/hashicorp/terraform/issues/21588#issuecomment-630352364) today, and so when that is released you should expect to see this fixed.

In the meantime, please take a look at that discussion thread for possible workarounds. One user reported that:
> We were able to work around it by defining the exact shape of the map that gets passed into the module. I.e. number and type of all key/pairs.

**Closed by danieldreier** 2020-05-18 23:05 UTC
