### ISSUE TITLE
Add Amazon Elastic MapReduce (AWS) support

### ISSUE THREAD

**Issue by cs-dieter-kling** [hashicorp/terraform#2098] opened 2015-05-27 10:18 UTC
In terms of provisioning and managing the AWS PaaS infrastructure, it would be very helpful to have EMR support in Terraform. 

As Andrew Langhorn pointed out, AWS GO SDK (https://github.com/awslabs/aws-sdk-go/tree/master/service/emr) already has support for EMR -
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/terraform-tool/uBMcgr9Azgw

**Comment by scrossan** [comment] 2015-09-11 14:04
+1 to this!

**Comment by meylor** [comment] 2015-09-22 06:28
Is this on the roadmap for 0.3 or 0.4? Are there thoughts as to how this should be implemented since jobs terminate outside of a ```terraform apply``` run?

**Comment by jagatveer** [comment] 2015-10-13 09:34
@harshicorp How far is this thing on your road map? +1 on this one from my end too.

**Comment by sarguru** [comment] 2015-10-13 17:29
+1

**Comment by AndreaCatalucci** [comment] 2015-11-05 12:58
+1

**Comment by apparentlymart** [comment] 2015-11-05 16:46
Looking at [the godoc for the EMR client](https://godoc.org/github.com/aws/aws-sdk-go/service/emr) I see a few different concepts here:

* Cluster (`DescribeCluster`, `ListClusters`)
* Instance Group (`AddInstanceGroups`, `ListInstanceGroups`, `ModifyInstanceGroups`, `ListInstanceGroups`)
* Instance (`ListInstances`, `ListInstancesPages`)
* Job Flow (`DescribeJobFlows`, `RunJobFlow`)
* Step (`DescribeStep`, `ListSteps`)

This API is a little opaque to me because most of the objects above don't have the full set of CRUD operations I usually expect in an AWS API (`Create...`, `Describe...`, `Modify...`, `Delete...`). It seems like there's a special workflow here that isn't obvous from the API functions alone, and that perhaps the modifications to some of these objects are implied by modifications to other objects.

Could someone who is familiar with EMR describe the typical usage patterns so we can understand better what would be an appropriate design for a Terraform integration? By this I mean a use-case and then the set of steps you'd take to achieve that use-case.

Usually Terraform support for a new service starts with the most central one or two resources in that service and then builds from there, so as well as understanding the flows, notes on use-case would also be very helpful to understand the priority of the various concepts above.

**Comment by serainville** [comment] 2015-11-12 16:22
+1

**Comment by kevin-at-reflexion** [comment] 2015-11-19 04:16
Greetings @apparentlymart.

There definitely are two sort of three EMR use cases:

 1. Run some data-processing application once (`AutoTerminate` => true)
 2. Configure a Hadoop cluster running continuously (`AutoTerminate` => false)
 3. Resize an existing EMR Hadoop cluster

I think the second and third use cases are probably what people would like to be able to configure from Terraform.
A sort-of simple first-pass example for an EMR resource might be something like as follows: (by translating the API directly into terraform syntax)

```terraform
resource "aws_emr_cluster" "hadoop" {
    name = "My Cluster"
    release = "emr-4.1.0"

    instance_group {
        instance_count = 1
        instance_role = "MASTER"
        instance_type = "m1.large"
    }

    instance_group {
        instance_count = 1
        instance_role = "CORE"
        instance_type = "m1.large"
    }
}
```

----

A more complete example, ie. something I'd probably end up using might look like:

```terraform
resource "aws_vpc" "main" {
    instance_tenancy = "dedicated"
}

resource "aws_subnet" "main" {
    vpc_id = "${aws_vpc.main.id}"
}

resource "aws_s3_bucket" "storage" {
    bucket = "my-storage"
}

resource "aws_emr_cluster" "hadoop" {
    name = "My Hadoop"
    release = "emr-4.1.0"
    log_uri = "s3://${aws_s3_bucket.storage.bucket}/logs"
    applications = ["hive", "hadoop", "pig", "spark", "hue"]

    # one of these
    instance_attributes {
        ec2_subnet_id = "${aws_subnet.main.id}"
    }

    # it possibly makes sense to break out instance groups into one Master group and many Core groups
    master_group {
        name = "My Master EMR Group" # default "Master Instance Group"
        instance_type = "m1.large"
    }
    core_group {
        name = "My Core EMR Group" # default "Core Instance Group"
        instance_count = 2
        instance_type = "m1.large"
        configuration {
            classification = "spark"
            properties {
              "maximizeResourceAllocation" = true
            }
        }
    }
}
```

The most important settings in there are probably **applications** and **instance_count**.

As for the steps to get there:

  + _Create a cluster_ (no idea how this works; I theorize it is achieved by using `RunJobFlow` with `KeepJobFlowAliveWhenNoSteps => TRUE`).
  + Add some instance groups with `AddInstanceGroup`.  I'm pretty sure that applications are technically configured on this step as well, but the main benefit of EMR is that you don't have to get into the nitty gritty details of which service runs on which node.   In short, almost all nodes run HDFS storage, the `master` node runs YARN and all of the Clients/Frontends and the Slave/Core nodes all run a uniform distribution of MapReduce and other compute services.

The easiest way to understand it is probably to set up a small 2 node (1 Master/1 Core) EMR cluster with the console, and then use the Describe Cluster commands to get all of the configurations back, and reason out how it works from those.

--> hope that was actually useful

**Comment by apparentlymart** [comment] 2015-11-19 07:27
@kevin-at-reflexion wow that is awesome, thanks! Feels much clearer now.

**Comment by proffalken** [comment] 2015-11-20 17:11
+1 for this :)

**Comment by sepulworld** [comment] 2015-12-28 19:31
@hashicorp any roadmap update on this feature/enhancement?

**Comment by nandanrao** [comment] 2016-01-29 15:47
+1 for needing to do pretty much exactly what @kevin-at-reflexion described.

**Comment by zot420** [comment] 2016-02-02 22:57
+1

**Comment by curena** [comment] 2016-02-24 19:08
+1

**Comment by t-pascal** [comment] 2016-03-14 19:57
I am interested in this functionality as well. It is a nice feature to preserve some of the one-time emr configurations I use in development.

Having said that, I think that using data-pipeline ( #4077) is a bit more powerful because one would specify all the other surrounding items that deploy a "real" EMR job. I think that a data pipeline definition (while harder to setup and maintain, possibly) would be far more powerful than a one-off cluster definition.

**Comment by dansteen** [comment] 2016-04-11 16:30
One potential pitfall here (not at all insurmountable, but I just hit it so I thought I'd mention it) is that EMR manages the security groups that are applied to the various boxes, and when you try to delete them in terraform you get a conflict since they each reference each other.

**Comment by andymc904** [comment] 2016-04-18 18:11
+1

**Comment by jumping** [comment] 2016-05-31 07:50
+1

**Comment by blakesmith** [comment] 2016-06-08 17:26
Just wanted to give an update here: I'm working on an initial MVP for this new resource which I'm working on in this branch: https://github.com/blakesmith/terraform/tree/emr_2098

So far I have simple create / delete working with a resource definition that looks something like this:

```terraform
resource "aws_elastic_map_reduce_cluster" "tf-test-cluster" {
  cluster_name = "tf-emr-cluster
  release = "emr-4.7.0"
  applications = ["hive", "hadoop", "pig", "spark", "hue"]
  auto_terminate = true
  instances {
    instance_count = 2
    termination_protected = false
  }
  emr_role = "EMR_DefaultRole"
  ec2_instance_profile = "EMR_EC2_DefaultRole"
}
```

A few challenges still ahead:
1. The API for this AWS resource is a mess. Lots of attributes that are at the wrong level, with differing API resource names depending on whether you're creating. (AKA - You create a `JobFlow` but the fetch information with a `DescribeCluster` call, using the same ID). Clearly this API has some evolutionary history to it, which maybe someone else can comment on. I'm not super familiar with EMR, and so I don't have all the context.
2. The test included successfully creates an EMR Cluster, but never gets past the EC2 provisioning stage. More to debug here, will probably add the S3 logging capability soon to see what's going on.
3. How instances are configured is going to be a challenge. I like @kevin-at-reflexion 's ideas around different granularities of optional instance config, but there are a lot of details to still work out here, and edge cases to handle.
4. Loads more to figure out with subnets and VPC configuration, but that will come soon.

**Comment by blakesmith** [comment] 2016-06-08 17:30
Also still undecided on whether step configuration should be a separate resource or integrated into the cluster resource. Anyone have any strong opinions here?

**Comment by gitlabbin** [comment] 2016-06-21 00:40
Based on our security requirements, and biz cases, our spark EMR TF as following config:

```
resource "aws_emr" "tf-test-cluster" {
  name = "tf-emr-cluster"
  release-label = "emr-4.6.0"
  applications = ["Spark"]
  ec2-attributes {
    KeyName = "user_key"
    SubnetId = "subnet-xxxx"
    AdditionalMasterSecurityGroups = "sg-xxxx"
  }
  instance-type = "m3.xlarge"
  instance-count = 3
  use-default-roles = true
  log-uri = "s3://testbucket/emr-spark-test/"
}
```
Hope it's generic enough to fit all the needs.

**Comment by atward** [comment] 2016-06-21 03:19
First off, resource keys should be snake_case.
`instance-type` and `instance-count` should be replaced with `instance_group` stanzas http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_InstanceGroup.html
If this will only support the old style (easy) configuration then at a minimum it should use `master_instance_type` & `slave_instance_type` (with managed+additional security group options for each group). 

I support kevin's proposal https://github.com/hashicorp/terraform/issues/2098#issuecomment-157946287 (with instance-groups)

**Comment by dansteen** [comment] 2016-06-21 03:20
This looks great so far!  Thanks so much for working on this.  It's something that we really need.   One thing I don't see much about here is any configuration for the "Instance Group" - "Core", "Task", or "Master" (where there is always only one "Master" node,  you can increase "Core" nodes but not decrease them, and you can increase or decrease "Task" nodes, and create multiple named "Task" groups).

Thanks again!

**Comment by endemics** [comment] 2016-06-22 07:21
Hi all, 

I am working with @gitlabbin and he shared with me the configuration snippet he proposed, taking into account @kevin-at-reflexion, @dansteen  and @atward comments.

I have no functional knowledge of EMR/hadoop, but looking at the snippet, I felt that the "instance_group" approach would make the aws_emr too monolithic somehow.

Has anyone any use cases where the cluster would be defined in one place and the tasks defined in another?

In that case, would something like the following make sense?
```
resource "aws_emr" "tf-test-cluster" {
  name          = "tf-emr-cluster"
  release_label = "emr-4.6.0"
  applications  = ["Spark"]

  ec2_attributes {
    key_name                          = "bc_key"
    subnet_id                         = "subnet-xxxx"
    additional_master_security_groups = "sg-xxxx"
  }

  use_default_roles = true
  log_uri           = "s3://iagtestbucket/emr-spark-test/"

   /*
   here we would only care about the master instance type
    unless there is a multi-master setup where we need to define
    the number of masters?
  */
  master_instance_type = "m3.xlarge"
}

/*
 Not too sure if it make sense to have the core group separated or
 if it should live inside the emr cluster definition?
*/
resource "emr_core_group" "foo" {
  cluster_id     = "${aws_emr.tf-test-cluster.id}"
  instance_count = 1
  instance_type  = "m3.xlarge"
}

/*
 Tasks group would be defined and managed individually and reference a cluster id
 Potentially living in different modules and having a life of their own (type, count etc)
*/
resource "emr_task_group" "task1" {
  cluster_id     = "${aws_emr.tf-test-cluster.id}"
  instance_count = 1
  instance_type  = "m3.xlarge"
}

resource "emr_task_group" "task2" {
  cluster_id     = "${aws_emr.tf-test-cluster.id}"
  instance_count = 10
  instance_type  = "m3.large"
}
```

**Comment by pedrodparkes** [comment] 2016-06-22 11:53
+1,
is it actually added?

**Comment by dansteen** [comment] 2016-06-22 14:48
@endemics We actually define Task groups dynamically in some cases, so breaking them out would definitely be beneficial.   I don't think we will be able to have the Core group broken out separately, however, since you can't create the cluster without it.  

As far as resizing goes,  as of EMR 4.1.0 you *can* shrink the Core instance group (contrary to what I said before), however, it will only let you shrink it down to a size that will still maintain consistency in HDFS.  

One additional factor is that all the "resize" requests are treated as "recommendations".  Meaning that EMR will do it's best to comply, but if it can't it may wait for a certain (configurable) amount of time and/or comply as best it can without compromising the cluster.  More specifics about this are located here: http://docs.aws.amazon.com/ElasticMapReduce/latest/ManagementGuide/emr-manage-resize.html

Thanks!

**Comment by gitlabbin** [comment] 2016-06-24 03:05
At the moment, having the EMR Cluster -  basic Resizing function working(only increase size):

https://github.com/IAops/terraform/tree/aws/emr

```
resource "aws_emr" "tf-test-cluster" {
  name = "tf-emr-cluster"
  release_label = "emr-4.6.0"
  applications = ["Spark"]
  ec2_attributes {
    key_name = "xxxx_key"
    subnet_id = "subnet-xxxx"
    additional_master_security_groups = "sg-xxxxx"
  }
  instance_type = "m3.xlarge"
  instance_count = 2
  use_default_roles = true
  log_uri = "s3://testbucket/emr-spark-test/"
  group_type_to_resize = "CORE"
  resize_count = 0
}
```

**Comment by endemics** [comment] 2016-06-29 01:27
Updating what the proposed DSL would look like, taking into account the remarks from @dansteen.

Merging core and master in the cluster definition indeed seems to make more sense since it doesn't seem to be possible to add new core instance group at run time.

```
resource "aws_emr" "tf-test-cluster" {
  name          = "tf-emr-cluster"
  release_label = "emr-4.6.0"
  applications  = ["Spark"]

  ec2_attributes {
    key_name                          = "bc_key"
    subnet_id                         = "subnet-xxxx"
    additional_master_security_groups = "sg-xxxx"
  }

  use_default_roles = true
  log_uri           = "s3://testbucket/emr-spark-test/"

  master_instance_type = "m3.xlarge"
  core_instance_type   = "m3.large"
  core_instance_count  = 1
  
}

/*
 Tasks group are defined and managed individually and reference a cluster id
 Potentially living in different modules and having a life of their own (type, count etc)
*/
resource "emr_task_group" "task1" {
  cluster_id     = "${aws_emr.tf-test-cluster.id}"
  instance_count = 1
  instance_type  = "m3.xlarge"
}

resource "emr_task_group" "task2" {
  cluster_id     = "${aws_emr.tf-test-cluster.id}"
  instance_count = 10
  instance_type  = "m3.large"
}
```

To double-check that assumption, which seemed odd since http://docs.aws.amazon.com/cli/latest/reference/emr/add-instance-groups.html mention that you can specify the InstanceGroupType as CORE or MASTER, we've done a test with @gitlabbin:
```
aws emr add-instance-groups --cluster-id j-XXXXXX --instance-groups InstanceCount=2,InstanceGroupType=core,InstanceType=m3.xlarge
A client error (ValidationException) occurred when calling the AddInstanceGroups operation: Only task instance group may be added at job flow runtime.
```
If we're missing something please let us know!

**Comment by dansteen** [comment] 2016-06-29 15:19
If it helps, this is an actual api command that we use to spin up our spark cluster.  This is run as a "local-exec" inside of terraform.  You can also see what variables we are using:

```
aws emr create-cluster 
  --applications Name=Hadoop 
                        Name=Spark 
  --bootstrap-actions '[{
             "Path": "s3://${var.chef_bootstrap_s3_path}",
             "Args": ["-r ${var.name} -e ${var.env} -d ${var.env_zone}"],
             "Name": "Configure Chef"
         }]'
  --tags 'role=${var.name}' 
            'dns_zone=${var.env_zone}' 
            'env=${var.env}' 
            'Name=${var.name}-${var.env}' 
  --ec2-attributes '{
               "KeyName": "${var.key}",
               "AdditionalSlaveSecurityGroups": [
                              "${var.default_sg}"
               ],
               "InstanceProfile": "${aws_iam_instance_profile.matching-spark.name}",
               "SubnetId": "${var.emr_subnet}",
               "EmrManagedSlaveSecurityGroup": "${aws_security_group.emr_slave.id}",
               "EmrManagedMasterSecurityGroup": "${aws_security_group.emr_master.id}",
               "AdditionalMasterSecurityGroups": [
                              "${var.default_sg}"
               ]
     }'
  --service-role ${aws_iam_role.emr.id} 
  --enable-debugging 
  --release-label emr-4.2.0 
  --log-uri 's3n://traitify-emr-logs/${var.name}-${var.env}/' 
  --name '${var.name}-${var.env}' 
  --instance-groups [
       {
         "InstanceCount": "${var.num_master_instances}",
         "InstanceGroupType": "MASTER",
         "InstanceType": "${var.master_instance_type}",
         "Name": "Master instance group - 1"
       },
       {
         "InstanceCount": "${ consul_keys.matching-spark-count}",
         "InstanceGroupType": "TASK",
         "InstanceType": "${var.task_instance_type}",
         "Name": "Task instance group - 3"
       },
       {
         "InstanceCount": "${var.num_core_instances}",
         "InstanceGroupType": "CORE",
         "InstanceType": "${var.core_instance_type}",
         "Name": "Core instance group - 2"
       }
     ]
  --configurations '${template_file.emr_config.rendered}' 
  --region us-east-1 
  --output json
```

So based on this, it looks like the following items would need to be added:
- bootstrap-actions
- tags
- ec2-attributes
  - EmrManagedMasterSecurityGroup
  - EmrManagedSlaveSecurityGroup
  - AdditionalSlaveSecurityGroups
- service-role
- instance-groups
  - Name (for master, core, task)
  - InstanceType (for master)
- configurations (this is a freeform json value set, that defines a number of initial configuration parameters about your cluster and applications. )
 - region

thanks!

**Comment by gitlabbin** [comment] 2016-07-01 04:00
Take @endemics 's multiple resources idea, split the "task instance group" into a resource type.
@dansteen , thanks for your sample, will add the other missing items soon. 

- Source code: https://github.com/IAops/terraform/commits/aws/emr
- Binary beta release for testing: 
-- Mac OSX 
---  https://github.com/IAops/terraform-beta/raw/master/darwin_amd64.zip
-- Linux 
--- https://github.com/IAops/terraform-beta/raw/master/linux_amd64.zip

**Comment by gitlabbin** [comment] 2016-07-07 06:19
tags and bootstrap-actions  sample:
```
  tags = ["role:${var.name}", "dns_zone:${var.env_zone}", "env:${var.env}", "Name:${var.name}-${var.env}"]

  bootstrap_actions {
    path  ="s3://elasticmapreduce/bootstrap-actions/run-if"
    name  ="runif"
    args  =["instance.isMaster=true","echo running on master node"]
  }
```

**Comment by gitlabbin** [comment] 2016-07-12 02:02
Support "configurations" item as @dansteen description.
* configurations (this is a freeform json value set, that defines a number of initial configuration parameters about your cluster and applications. )

Remote config json file
```
configurations = "http://xxxxxxx/myconfig.json"
```

Or local config json file
```
configurations = "./myconfig.json"
``` 

myconfig.json
```
[
    {
        "Classification": "hadoop-env", 
        "Configurations": [
            {
                "Classification": "export", 
                "Configurations": [], 
                "Properties": {
                    "JAVA_HOME": "/usr/lib/jvm/java-1.8.0"
                }
            }
        ], 
        "Properties": {}
    }, 
    {
        "Classification": "spark-env", 
        "Configurations": [
            {
                "Classification": "export", 
                "Configurations": [], 
                "Properties": {
                    "JAVA_HOME": "/usr/lib/jvm/java-1.8.0"
                }
            }
        ], 
        "Properties": {}
    }
]
```

**Comment by dansteen** [comment] 2016-07-21 13:41
How about a template value for the configurations item?

**Comment by gitlabbin** [comment] 2016-07-22 02:21
@dansteen , 
May we add the embedded json body to meet this,
Check my update from above.

Thanks

**Comment by dansteen** [comment] 2016-08-02 15:37
@gitlabbin ok.  Sorry this took me a while to test.  I had to extract out parts of our config to make sure things would work.   This looks good so far!  Here is a gist containing the command line generated by EMR after spinning up an EMR cluster using both the current way we do it, and the new resource:  https://gist.github.com/dansteen/ec334b8ca76819f8de11a5e4199ec218

The results are almost identical.   It looks like the following items are missing (which prevent the cluster from coming up successfully): 

--service-role (off of the main command)
InstanceProfile (part of the --ec2-attributes flag)

Thanks!

**Comment by gitlabbin** [comment] 2016-08-03 02:26
@dansteen , Thanks for your feedback, made the changes to remove the hardcode,
[x] add "instance_profile" , "service_role"
[x] remove "user_default_roles"
the specs. based on your one:
```
resource "aws_emr" "matching-spark-test" {
  name          = "matching-spark-test-stag"
  release_label = "emr-4.2.0"
  applications  = ["Hadoop", "Spark"]

  ec2_attributes {
    key_name                          = "aws-staging"
    subnet_id                         = "subnet-vvvvvvvv"
    additional_master_security_groups = "sg-xxxxxxx"
    additional_slave_security_groups = "sg-xxxxxxxx"
    emr_managed_master_security_group = "sg-yyyyyyyy"
    emr_managed_slave_security_group = "sg-zzzzzzz"
    #Newly added
    instance_profile = "matching-spark-stag"
  }

  log_uri           = "s3://xxxxx-emr-logs/matching-spark-stag/"

  master_instance_type = "r3.2xlarge"
  core_instance_type   = "c3.2xlarge"
  core_instance_count  = 1

  #Newly added
  service_role = "TODO"

  tags {
        role        = "matching-spark"
        dns_zone    = "XXXXXXXXXXXX"
        env         = "stag"
        Name        = "matching-spark-test2-stag"
  }

  bootstrap_action {
    path  ="s3://chef-bootstrap-files/autoscale-userdata.sh"
    name  ="Configure Chef"
    args  =["-r matching-spark", "-e stag", "-d XXXXXXXXXXX" ]
  }
  configurations = "${template_file.emr_config.rendered}"
}

resource "aws_emr_task_group" "matching-spark-test-task" {
  cluster_id     = "${aws_emr.matching-spark-test.id}"
  instance_count = 3
  instance_type  = "c3.2xlarge"
}

resource "template_file" "emr_config" {
  template = "${file("emr-config.json.tpl")}"

  vars {
    env          = "stag"
    airbrake_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```

**Comment by dansteen** [comment] 2016-08-03 02:30
@gitlabbin Thanks -  Looks great!  I'll give it a test tomorrow.  Is there an updated binary?

**Comment by gitlabbin** [comment] 2016-08-03 02:33
@dansteen , yes, binary updated, please try it out. thanks

**Comment by dansteen** [comment] 2016-08-03 16:30
Ok.  This looks really good!  My cluster comes up successfully, and looks almost identical to the cluster we create manually.  The only differences are:

- Instance Group names
    - We do not seem to have a way to name the instance groups other than the "task" groups.  By default the master group comes up with a name of "master", and the core group comes up with a name of "slave"
- debugging
   - We don't have a way to turn on the --enable-debug option.  This is actually pretty important as you can't effectively debug well without it.

Otherwise it looks great!  The above issues are really minor.

I also ran across a few workflow issues while I was working on this:

- Trying to make any change to instance groups while a cluster is stopped results in:
```
* aws_emr.matching-spark-test: ValidationException: An instance group may only be modified when the cluster is running or waiting.
```

- Attempting to destroy a cluster that failed to start results in the following message:
```
* aws_emr.matching-spark-test: [WARN] Error waiting for EMR Cluster state to be "TERMINATED": unexpected state 'TERMINATED_WITH_ERRORS', wanted target 'TERMINATED'. last error: %!s(<nil>)
```

- Renaming the task group does not take effect (or throw any errors), EMR it just ignores it.

- Destroying a cluster does not pick up that the cluster is destroyed. It continues to display these messages long after the cluster goes into a "Terminated" state:
```
aws_emr.matching-spark-test: Still destroying... (1m40s elapsed)
```
Until it finally hits
```
aws_emr.matching-spark-test: Still destroying... (13m0s elapsed)
```
and registers that it was destroyed.  But it went into a Terminated state after about 2-3 minutes.

**Comment by gitlabbin** [comment] 2016-08-04 01:17
@dansteen , thanks for your testing, I checked aws-sdk-go for your suggestion.
Please read the comments.
 
## Initial 
-  Instance Group names
We do not seem to have a way to name the instance groups other than the "task" groups. By default the master group comes up with a name of "master", and the core group comes up with a name of "slave"

&#x1F534; `aws-sdk-go api no such interface`

- debugging
We don't have a way to turn on the --enable-debug option. This is actually pretty important as you can't effectively debug well without it.
Otherwise it looks great! The above issues are really minor.

&#x1F534; `aws-sdk-go api no such interface`

I also ran across a few workflow issues while I was working on this:

## Destroy and modify

- Trying to make any change to instance groups while a cluster is stopped results in:

```
* aws_emr.matching-spark-test: ValidationException: An instance group may only be modified when the cluster is running or waiting.
```

`aws-sdk-go api does not allow to do anychanges when Cluster is not "Running or Waiting"`

- Attempting to destroy a cluster that failed to start results in the following message:
```
* aws_emr.matching-spark-test: [WARN] Error waiting for EMR Cluster state to be "TERMINATED": unexpected state 'TERMINATED_WITH_ERRORS', wanted target 'TERMINATED'. last error: %!s(<nil>)
```

`aws-sdk-go api does not allow to do anychanges when Cluster is not "Running or Waiting"`

-[ ]  Renaming the task group does not take effect (or throw any errors), EMR it just ignores it.

`aws-sdk-go api no funcation to do rename`

- Destroying a cluster does not pick up that the cluster is destroyed. It continues to display these messages long after the cluster goes into a "Terminated" state:
```
aws_emr.matching-spark-test: Still destroying... (1m40s elapsed)
```

Until it finally hits
```
aws_emr.matching-spark-test: Still destroying... (13m0s elapsed)
```

and registers that it was destroyed. But it went into a Terminated state after about 2-3 minutes.

`This one will get some improvement, if we ignore the security group clean up`

**Comment by gitlabbin** [comment] 2016-08-04 01:45
@dansteen ,
For the last piece, I did update the binary. please try it

**Comment by dansteen** [comment] 2016-08-04 15:34
So, for the workflow issues above, I wasn't really expecting to be able to *do* those things, rather, that terraform should respond differently than it did.

> * Trying to make any change to instance groups while a cluster is stopped results in:
> `aws_emr.matching-spark-test: ValidationException: An instance group may only be modified when the cluster is running or waiting.`

> 🔶 aws-sdk-go api does not allow to do anychange when Cluster is not "Running or Waiting"

Wouldn't the expected behavior be for it to detect that the cluster is Terminated and mark the resource as tainted and recreate it using the new values?  

> *  Attempting to destroy a cluster that failed to start results in the following message:
> `aws_emr.matching-spark-test: [WARN] Error waiting for EMR Cluster state to be "TERMINATED": unexpected state 'TERMINATED_WITH_ERRORS', wanted target 'TERMINATED'. last error: %!s(<nil>)`

> 🔶 aws-sdk-go api does not allow to do anychange when Cluster is not "Running or Waiting"

This is not really an edit of a cluster.  We are trying to destroy it.  Once its in either the "TERMINATED" or "TERMINATED_WITH_ERRORS" state, the cluster is already destroyed.   I would think terraform should detect that and register it as destroyed.

> * Renaming the task group does not take effect (or throw any errors), EMR it just ignores it.

> 🚫aws-sdk-go api no funcation to do rename

Again, this is a behavior thing rather than an expectation that it do the rename.  I would think that terraform would either throw an error, or taint the resource and rebuild it.  Not that it would just ignore the config request.

> * Destroying a cluster does not pick up that the cluster is destroyed. It continues to display these messages long after the cluster goes into a "Terminated" state

 > 📌This one will get some improvement, if we ignore the security group clean up

Is this due to the circular dependencies in the security groups that we talked about above?

**Comment by gitlabbin** [comment] 2016-08-05 00:36
Hi @dansteen ,
Thanks for your information, The last one is exactly as what you talked before about "circular dependencies in the security groups". 

Other's we could tackle it  case by case.
Could you please detail it for each case what kind of behaviour is your expectation?

Thanks.

**Comment by dansteen** [comment] 2016-08-05 13:33
So, to resolve the circular dependencies, I just remove each of the inbound and outbound rules first.  Those are what reference each other, so that removes the dependency.  Then the security groups can be deleted without any trouble.

**Comment by gitlabbin** [comment] 2016-08-08 05:49
@dansteen ,  For case 1 and case 2.
-[x] Code and Binary updated for handle  "TERMINATED" or "TERMINATED_WITH_ERRORS" state.

**Comment by ddcprg** [comment] 2016-08-16 10:15
Will this resource allow EMR with a Master node only (no salves)?

**Comment by gitlabbin** [comment] 2016-08-17 04:31
if you remove the core instance setting, it will be a master node only
```
  #core_instance_type   = "c3.2xlarge"
  #core_instance_count  = 1
```

**Comment by dansteen** [comment] 2016-08-18 19:46
@gitlabbin do you have a version of the binary that includes the latest stuff in v0.7.0?  looks like the consul stuff specifically has not been updated in the binary above...

**Comment by gitlabbin** [comment] 2016-08-19 01:01
will do a merge for you 😄

**Comment by dansteen** [comment] 2016-08-19 17:05
Plan looks good.   I can't run an apply just now, but I'll be able to do it later next week.

**Comment by dansteen** [comment] 2016-08-29 16:29
Ok.  I've tested out the newest push, and things look quite good!   The circular dependency thing is still an issue, but the other items behave in ways that "feel" right.

**Comment by gitlabbin** [comment] 2016-08-30 01:05
@dansteen , I find a way to work around the circular dependency, give you a sample sepc.
The main point is create your own SecurityGroup
```
provider "aws" {
   region = "ap-southeast-2"
}
resource "aws_emr" "tf-test-cluster" {
  name          = "emr-%s"
  release_label = "emr-4.6.0"
  applications  = ["Spark"]
  ec2_attributes {
    subnet_id   = "${aws_subnet.main.id}"
    emr_managed_master_security_group = "${aws_security_group.allow_all.id}"
    emr_managed_slave_security_group = "${aws_security_group.allow_all.id}"
  }
  master_instance_type = "m3.xlarge"
  core_instance_type   = "m3.xlarge"
  core_instance_count  = 1
  tags {
        role        = "rolename"
        dns_zone    = "env_zone"
        env         = "env"
        name        = "name-env"
  }
  bootstrap_action {
    path  ="s3://elasticmapreduce/bootstrap-actions/run-if"
    name  ="runif"
    args  =["instance.isMaster=true","echo running on master node"]
  }
  configurations = "test-fixtures/emr_configurations.json"
  depends_on = ["aws_main_route_table_association.a"]
}
resource "aws_security_group" "allow_all" {
  name        = "allow_all"
  description = "Allow all inbound traffic"
  vpc_id      = "${aws_vpc.main.id}"
  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
    }
  depends_on = ["aws_subnet.main"]
  lifecycle {
        ignore_changes = ["ingress", "egress"]
  }
}
resource "aws_vpc" "main" {
  cidr_block           = "168.31.0.0/16"
  enable_dns_hostnames = true
}
resource "aws_subnet" "main" {
  vpc_id                  = "${aws_vpc.main.id}"
  cidr_block              = "168.31.0.0/20"
#  map_public_ip_on_launch = true
}
resource "aws_internet_gateway" "gw" {
  vpc_id = "${aws_vpc.main.id}"
}
resource "aws_route_table" "r" {
  vpc_id = "${aws_vpc.main.id}"
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.gw.id}"
  }
}
resource "aws_main_route_table_association" "a" {
  vpc_id         = "${aws_vpc.main.id}"
  route_table_id = "${aws_route_table.r.id}"
}
```

**Comment by dansteen** [comment] 2016-08-30 15:10
@gitlabbin, hm.  I actually do create my own security groups:

```
resource "aws_emr" "matching-spark" {
  name          = "${var.name}-${var.env}"
  release_label = "emr-4.2.0"
  applications  = ["Hadoop", "Spark"]

  ec2_attributes {
    key_name                          = "${var.key}"
    subnet_id                         = "${var.emr_subnet}"
    additional_master_security_groups = "${var.default_sg}"
    additional_slave_security_groups = "${var.default_sg}"
    emr_managed_master_security_group = "${aws_security_group.emr_master.id}"
    emr_managed_slave_security_group = "${aws_security_group.emr_slave.id}"
    instance_profile = "${aws_iam_instance_profile.matching-spark.name}"
  }
....
}

resource "aws_security_group" "emr_master" {
  name        = "${var.name} ${var.env} master"
  description = "Ports required by the ${var.name} - ${var.env} master servers - managed by aws"
  vpc_id      = "${var.vpc}"

  tags {
    "Name" = "${var.name} ${var.env} master"
  }
}

resource "aws_security_group" "emr_slave" {
  name        = "${var.name} ${var.env} slave"
  description = "Ports required by the ${var.name} - ${var.env} slave servers - managed by aws"
  vpc_id      = "${var.vpc}"

  tags {
    "Name" = "${var.name} ${var.env} slave"
  }
}

```

**Comment by gitlabbin** [comment] 2016-08-30 23:24
@dansteen , For the sample I tried successfully.
- Having only one `resource "aws_security_group" "allow_all"`,
it will be used by both master and slave,  through this to avoid the circular dependency.

- Add the lifecycle ignore, as the aws sdk will do some magic changes for the security group, actually we don't care.

**Comment by rcoh** [comment] 2016-09-12 18:34
Any idea when this will be in terraform stable?

**Comment by dansteen** [comment] 2016-09-23 14:18
@gitlabbin I see what you are saying.  Since they use the same security group you don't have conflicts.   I suppose that should go into the documentation as a high visibility item as it won't work for some people (though it will probably be fine for most)

**Comment by spanktar** [comment] 2016-09-28 20:39
Pretty please to have this PR soon! I'll send beer and cookies!

**Comment by catsby** [comment] 2016-10-07 20:58
Hello friends! Initial EMR support was added in Terraform v0.7.5. Thanks!

**Closed by catsby** 2016-10-07 20:58 UTC
Labels: enhancement, new-resource, provider/aws

**Comment by ajlanghorn** [comment] 2016-11-16 15:32
By complete and utter fluke, I came across this issue whilst Googling for how to use the `ec2_attributes` argument to `aws_emr_cluster_instance_group`. I hadn't realised it had been raised, or anyone had actually mentioned me and my off-the-cuff post back in May. Anyway, I'm now working on a large project making use of EMR built-out in Terraform, so this is just a THANK YOU for implementing functionality ❤️!
