### ISSUE TITLE
Terraform misleading error message

### ISSUE THREAD

**Issue by timtsoi-crypto** [hashicorp/terraform#26794] opened 2020-11-03 05:10 UTC
### Terraform Version

```
v0.13.5
```

### Terraform Configuration Files

module variable definition
```
variable "config" {
  type = list(object(
    {
      temp = object({
        list1    = list(string)
        list2    = list(string)
      })
      location           = string
    }
))
}
```

variable definition of repo which references the module 
```
variable "config" {
  type = list(object(
    {
      location           = string
    }
))
}
```

.tfvar.json 
```terraform
"config": [
    {
        "location": "us",
        "temp": {
              list1 = ["hello"]
              list2 = []
         }
    }
]
```

### Crash Output

Error: Invalid value for module argument

  on main.tf line 100, in module "xxxxx":
  100:   config = var.config

The given value is not suitable for child module variable "config"
defined at .terraform/modules/xxxxx/variable.tf:11,1-23:
incorrect list element type: attribute "location": string required.

### Expected Behavior

It should remind me to update variable definition of the repo, to match with the module one. 

### Actual Behavior

It says location is list type but indeed it is string type.

### Steps to Reproduce

1. terraform init
2. terraform plan

**Comment by alisdair** [comment] 2020-11-04 15:42
Hi @timtsoit-crypto, thanks for reporting. I can't reproduce this issue with the configuration below, which is basically the same as in your initial report but with some typos in the JSON tfvars file fixed.

main.tf:

```hcl
variable "config" {
  type = list(object(
    {
      location = string
    }
  ))
}

module "mod" {
  source = "./mod"
  config = var.config
}
```

mod/main.tf:

```hcl
variable "config" {
  type = list(object(
    {
      temp = object({
        list1 = list(string)
        list2 = list(string)
      })
      location = string
    }
  ))
}
```

terraform.tfvars.json:

```json
{
  "config": [
      {
          "location": "us",
          "temp": {
                "list1": ["hello"],
                "list2": []
           }
      }
  ]
}
```

Result:

```shellsession
$ terraform plan

Error: Invalid value for module argument

  on main.tf line 11, in module "mod":
  11:   config = var.config

The given value is not suitable for child module variable "config" defined at
mod/main.tf:1,1-18: incorrect list element type: attribute "temp" is required.
```

Can you find a way to modify this configuration to reproduce the issue?

**Comment by mildwonkey** [comment] 2021-04-30 15:55
I'm going to close this, since there hasn't been a response, but if you are still experiencing a problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by mildwonkey** 2021-04-30 15:55 UTC
Labels: bug, v0.13, waiting for reproduction, waiting-response
