### ISSUE TITLE
terraform doesn't see environment variable

### ISSUE THREAD

**Issue by lapots** [hashicorp/terraform#17376] opened 2018-02-17 10:02 UTC
I have `terraform` configuration that looks like this

```
variable "heroku_api_key" {}

provider "heroku" {
    email = "sebastrident@gmail.com"
    api_key = "${var.heroku_api_key}"
}

resource "heroku_app" "default" {
    name = "judge-re"
    region = "us"
}
```
On `travis` I encrypted the security key like this  and in the log I see that it being exported

`$ export TF_VAR_HEROKU_API_KEY=[secure]`

On deploy I execute this script
```
#!/bin/bash

set -o errexit -o nounset

terraform init
terraform plan
terraform apply
```
But it stalls because `terraform` asks for the variable
```
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

var.heroku_api_key
  Enter a value: 
```

The log itself is here [https://travis-ci.org/lapots/judge-rule-engine/builds/342694628](https://travis-ci.org/lapots/judge-rule-engine/builds/342694628)
The project files is here [https://github.com/lapots/judge-rule-engine](https://github.com/lapots/judge-rule-engine)

What is the problem?

**Comment by apparentlymart** [comment] 2018-02-17 23:10
Hi @lapots! Sorry for the confusing behavior here.

I believe the issue is that Terraform matches the environment variables case-sensitively, so you need to name the variable as it is named in the Terraform config:

```hcl
$ export TF_VAR_heroku_api_key=[secure]
```

**Comment by lapots** [comment] 2018-02-18 12:39
oh! Indeed. Guess I missed somewhere in the documentation that variable names are case sensitive

**Comment by apparentlymart** [comment] 2018-02-19 22:21
Thanks for following up, @lapots!

Indeed it seems that the documentation doesn't currently mention that _explicitly_ and instead just implies it by showing lowercase names in the examples.

We're planning a big revamp of the configuration documentation as part of our current efforts to improve the configuration language so we'll revise [the relevant section](https://www.terraform.io/docs/configuration/variables.html#environment-variables) as part of that work, and try to be more explicit about what is required here.

It sounds like you have what you need for now, so I'm going to close this. Sorry the documentation wasn't clearer!

**Closed by apparentlymart** 2018-02-19 22:21 UTC
Labels: cli, question
