### ISSUE TITLE
crash when HOME environment variable is unset

### ISSUE THREAD

**Issue by mikeparisstuff** [hashicorp/terraform#23840] opened 2020-01-12 20:50 UTC
I am trying to configure terraform to run within a bazel build rule and am running into some issues. I have attached the crash.log file that is generated but the symptom is a nil pointer dereference. I suspect this may have something to do with running terraform in a sandbox where it does not have access to some directory that it needs but I am not sure.

### Terraform Version

```
0.12.19
```

### Terraform Configuration Files

I am trying to run `terraform init` from within a bazel build rule. It appears to fail when trying to load the provider plugins (see crash.log).

```hcl
terraform {
  backend "s3" {
    bucket = "my-bucket"
    key = "my-bucket-key"
    region = "us-west-2"
    encrypt = true
  }
}

provider "aws" {
  region = "${var.aws_region}"
  version = "2.43"
}
```

### Debug Output

```
Initializing modules...
- test_pipeline in ../../../external/modules_terraform/service_pipeline
- test_pipeline.update_alias_function in ../../../external/modules_terraform/update_alias_function

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...


!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Crash Output

```
2020/01/12 15:37:27 [INFO] Terraform version: 0.12.19  
2020/01/12 15:37:27 [INFO] Go runtime version: go1.12.13
2020/01/12 15:37:27 [INFO] CLI args: []string{"/private/var/tmp/_bazel_workplace/0da058ed0566077a2411f192070c9a76/sandbox/darwin-sandbox/170/execroot/__main__/bazel-out/host/bin/external/tool_terraform/binary", "init"}
2020/01/12 15:37:27 [ERROR] Error detecting default CLI config file path: user: Current not implemented on darwin/amd64
2020/01/12 15:37:27 [DEBUG] Attempting to open CLI config file: 
2020/01/12 15:37:27 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/01/12 15:37:27 [ERROR] Error finding global config directory: user: Current not implemented on darwin/amd64
2020/01/12 15:37:27 [WARN] Cannot initialize remote host credentials manager: can't locate credentials file: user: Current not implemented on darwin/amd64
2020/01/12 15:37:27 [ERROR] Error finding global config directory: user: Current not implemented on darwin/amd64
2020/01/12 15:37:27 [ERR] Checkpoint setup error: user: Current not implemented on darwin/amd64
2020/01/12 15:37:27 [INFO] CLI command args: []string{"init"}
2020/01/12 15:37:27 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2020/01/12 15:37:27 [DEBUG] Module installer: begin test_pipeline
2020/01/12 15:37:27 [TRACE] ModuleInstaller: test_pipeline is not yet installed
2020/01/12 15:37:27 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/test_pipeline prior to install of test_pipeline
2020/01/12 15:37:27 [TRACE] ModuleInstaller: test_pipeline has local path "../../../external/modules_terraform/service_pipeline"
2020/01/12 15:37:27 [TRACE] ModuleInstaller: test_pipeline uses directory from parent: ../../../external/modules_terraform/service_pipeline
2020/01/12 15:37:27 [DEBUG] Module installer: test_pipeline installed at ../../../external/modules_terraform/service_pipeline
2020/01/12 15:37:27 [DEBUG] Module installer: begin test_pipeline.update_alias_function
2020/01/12 15:37:27 [TRACE] ModuleInstaller: test_pipeline.update_alias_function is not yet installed
2020/01/12 15:37:27 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/test_pipeline.update_alias_function prior to install of test_pipeline.update_alias_function
2020/01/12 15:37:27 [TRACE] ModuleInstaller: test_pipeline.update_alias_function has local path "../update_alias_function"
2020/01/12 15:37:27 [TRACE] ModuleInstaller: test_pipeline.update_alias_function uses directory from parent: ../../../external/modules_terraform/update_alias_function
2020/01/12 15:37:27 [DEBUG] Module installer: test_pipeline.update_alias_function installed at ../../../external/modules_terraform/update_alias_function
2020/01/12 15:37:27 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
2020/01/12 15:37:27 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 1129095130
2020/01/12 15:37:27 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/01/12 15:37:27 [DEBUG] New state was assigned lineage "48023871-1b51-9ff8-b8a6-fac608167554"
2020/01/12 15:37:27 [TRACE] Meta.Backend: moving from default local state only to "s3" backend
2020/01/12 15:37:27 [INFO] Setting AWS metadata API timeout to 100ms
2020/01/12 15:37:28 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2020/01/12 15:37:28 [INFO] AWS Auth provider used: "EnvProvider"
2020/01/12 15:37:28 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2020/01/12 15:37:28 [DEBUG] checking for provider in "."
2020/01/12 15:37:28 [DEBUG] checking for provider in "/private/var/tmp/_bazel_workplace/0da058ed0566077a2411f192070c9a76/sandbox/darwin-sandbox/170/execroot/__main__/bazel-out/host/bin/external/tool_terraform"
2020/01/12 15:37:28 [DEBUG] checking for provisioner in "."
2020/01/12 15:37:28 [DEBUG] checking for provisioner in "/private/var/tmp/_bazel_workplace/0da058ed0566077a2411f192070c9a76/sandbox/darwin-sandbox/170/execroot/__main__/bazel-out/host/bin/external/tool_terraform"
2020/01/12 15:37:28 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2020/01/12 15:37:28 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/01/12 15:37:28 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/01/12 15:37:28 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/01/12 15:37:28 [TRACE] statemgr.Filesystem: read nil snapshot
2020/01/12 15:37:28 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
2020/01/12 15:37:28 [DEBUG] New state was assigned lineage "d4a2153f-27eb-9288-001e-59594c78e068"
2020/01/12 15:37:28 [TRACE] Preserving existing state lineage "d4a2153f-27eb-9288-001e-59594c78e068"
2020/01/12 15:37:29 [TRACE] Meta.Backend: instantiated backend of type *s3.Backend
2020/01/12 15:37:29 [DEBUG] checking for provider in "."
2020/01/12 15:37:29 [DEBUG] checking for provider in "/private/var/tmp/_bazel_workplace/0da058ed0566077a2411f192070c9a76/sandbox/darwin-sandbox/170/execroot/__main__/bazel-out/host/bin/external/tool_terraform"
2020/01/12 15:37:29 [DEBUG] checking for provisioner in "."
2020/01/12 15:37:29 [DEBUG] checking for provisioner in "/private/var/tmp/_bazel_workplace/0da058ed0566077a2411f192070c9a76/sandbox/darwin-sandbox/170/execroot/__main__/bazel-out/host/bin/external/tool_terraform"
2020/01/12 15:37:29 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2020/01/12 15:37:29 [TRACE] Meta.Backend: backend *s3.Backend does not support operations, so wrapping it in a local backend
2020/01/12 15:37:29 [DEBUG] checking for provider in "."
2020/01/12 15:37:29 [DEBUG] checking for provider in "/private/var/tmp/_bazel_workplace/0da058ed0566077a2411f192070c9a76/sandbox/darwin-sandbox/170/execroot/__main__/bazel-out/host/bin/external/tool_terraform"
2020/01/12 15:37:29 [DEBUG] plugin requirements: "aws"="2.43"
2020/01/12 15:37:29 [DEBUG] plugin requirements: "archive"="1.3"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x24bce06]

goroutine 1 [running]:
github.com/hashicorp/terraform/command/cliconfig.(*CredentialsSource).ForHost(0x0, 0x2a92804, 0x15, 0x6, 0xc00027e348, 0x14, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/cliconfig/credentials.go:155 +0x26
github.com/hashicorp/terraform-svchost/disco.(*Disco).CredentialsForHost(...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/terraform-svchost@v0.0.0-20191011084731-65d371908596/disco/disco.go:101
github.com/hashicorp/terraform-svchost/disco.(*Disco).discover(0xc000588960, 0x2a92804, 0x15, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/terraform-svchost@v0.0.0-20191011084731-65d371908596/disco/disco.go:194 +0xfba
github.com/hashicorp/terraform-svchost/disco.(*Disco).Discover(0xc000588960, 0x2a92804, 0x15, 0x0, 0x3, 0xc00005ea70)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/terraform-svchost@v0.0.0-20191011084731-65d371908596/disco/disco.go:146 +0x87
github.com/hashicorp/terraform-svchost/disco.(*Disco).DiscoverServiceURL(0xc000588960, 0x2a92804, 0x15, 0x2a82572, 0xc, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/terraform-svchost@v0.0.0-20191011084731-65d371908596/disco/disco.go:158 +0x43
github.com/hashicorp/terraform/registry.(*Client).Discover(0xc000718220, 0x2a92804, 0x15, 0x2a82572, 0xc, 0x0, 0x10, 0x40)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:65 +0x61
github.com/hashicorp/terraform/registry.(*Client).TerraformProviderVersions(0xc000718220, 0xc0005040a0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:239 +0xc0
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).listProviderVersions(0xc00031e460, 0xc0004e8870, 0x3, 0x2a74f4c, 0x1, 0x2a92804, 0x15, 0x0, 0xc00074cca8, 0x10a8be7)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:477 +0x7e
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).Get(0xc00031e460, 0xc0004e8870, 0x3, 0x2a74f4c, 0x1, 0x2a92804, 0x15, 0xc0006f40a8, 0x1, 0x1, ...)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:125 +0xde
github.com/hashicorp/terraform/command.(*InitCommand).getProviders(0xc0003f5880, 0xc0003143f0, 0xc0006f4010, 0x0, 0xc00062c5a0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:530 +0x4c5
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0003f5880, 0xc0000ca010, 0x0, 0x0, 0xc0003f6fb0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:347 +0x102d
github.com/mitchellh/cli.(*CLI).Run(0xc00011ca00, 0xc00011ca00, 0xc000535d90, 0x1)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:238 +0xc34
main.realMain(0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:102 +0xb4
main.main()
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:38 +0x3b
```

### Expected Behavior

I have debugged a number of steps to get terraform *almost* working within the bazel build rule. I am passing AWS provider creds via environment variables and it looks like some parts of the initialization are working. Bazel sandboxes all the build rules so I am wondering if the provider plugins require access to some directory? I am already trying to set the `TF_PLUGIN_CACHE_DIR` env var via `export TF_PLUGIN_CACHE_DIR=$TMPDIR/rules_terraform/plugin-cache` where the $TMPDIR is provided by bazel.

### Actual Behavior
The init fails with a nil pointer dereference.

**Comment by fivetran-andydreyfuss** [comment] 2020-02-13 01:56
Bazel does in fact appear to break terraform. In a java package built by Bazel, I cannot run terraform init from a Process. However in a java package built directly from the command line (javac) I can. So Bazel's runtime is breaking terraform. I get the same stack trace as here.

**Comment by fivetran-andydreyfuss** [comment] 2020-02-13 02:09
PS: I was able to get around this by having the process set the HOME environment variable. It looks like your error above is "Current not implemented on darwin/amd64" but not sure what that means. Good luck stranger.

**Comment by strottos** [comment] 2020-02-24 16:50
I hit this problem as well by simply running Terraform with a stripped down environment, as mentioned by @fivetran-andydreyfuss above, setting the HOME environment variable fixes this (thanks for the tip).

**Comment by fivetran-andydreyfuss** [comment] 2020-02-25 06:39
Credit goes to @glarwood as the one who figured out what was going on here

**Comment by danieldreier** [comment] 2020-05-13 23:20
I think this is a duplicate of https://github.com/hashicorp/terraform/issues/24420 that hits what looks like the same error in the same place:

24420 crash log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2449596]

goroutine 1 [running]:
github.com/hashicorp/terraform/command/cliconfig.(*CredentialsSource).ForHost(0x0, 0x2a584d5, 0x15, 0x6, 0xc0000c41e8, 0x2a3a8b3, 0x3)
	/private/tmp/terraform-20200319-2773-d1flw8/terraform-0.12.24/src/github.com/hashicorp/terraform/command/cliconfig/credentials.go:155 +0x26
```

**Comment by danieldreier** [comment] 2020-05-13 23:44
I'm pretty sure this is the same as #24520 which states the issue more succinctly, so I'm going to close this. Please let me know (ddreier@hashicorp.com) if you think this is a different issue and I'm happy to re-open it.

**Closed by danieldreier** 2020-05-13 23:44 UTC
Labels: bug, cli, crash, v0.12
