### ISSUE TITLE
Cloudflare Cannot Update DNS Record as it already exists

### ISSUE THREAD

**Issue by ahosking** [hashicorp/terraform#10065] opened 2016-11-11 21:22 UTC
### Terraform Version
Versio 0.7.7 and Version 0.7.10

### Affected Resource(s)
Please list the resources as a list, for example:
- Cloudflare Provider

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "my_record" {
  domain = "<MY_DOMAIN>"
  name = "*.<MY_DOMAIN>"
  value = "<MY_VALUE>"
  type = "CNAME"
  ttl = 1
}

```

### Debug Output
`cloudflare_record.my_record: Creating...
  domain:   "" => "<MY_DOMAIN>"
  hostname: "" => "<computed>"
  name:     "" => "*.<MY_DOMAIN>"
  proxied:  "" => "false"
  ttl:      "" => "1"
  type:     "" => "CNAME"
  value:    "" => "<MY_VALUE>"
  zone_id:  "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* cloudflare_record.my_record: Failed to create record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":81053,\"message\":\"An A, AAAA or CNAME record already exists with that host.\"}],\"messages\":[],\"result\":null}"`

### Expected Behavior
The record should be updated.

### Actual Behavior
Terraform failed and did not update the record

### Steps to Reproduce
1. `terraform plan`

**Comment by mwarkentin** [comment] 2016-12-15 16:45
@ahosking Is this record already managed in terraform, or had you created it manually in Cloudflare ahead of time?

I think cloudflare records need `terraform import` support in order to handle the second case.

**Comment by serdardalgic** [comment] 2016-12-19 10:45
I'm not so sure if this ticket is the place, but +1 from me for the cloudflare records `terraform import` support. This "Can not update as it already exists" error is quite annoying.

**Comment by justinpersaud** [comment] 2016-12-21 00:52
+1 from me as well. Currently facing the same issue mentioned in this issue while trying to manage a zone in CloudFlare that had records created via the UI.

**Comment by ahosking** [comment] 2016-12-21 18:07
@mwarkentin The flow to get to this point was;

- Create record with terraform
- Change record with terraform
- After inconsistent amount of time observe the problem

Terraform import would definitely help here, but it's strange that when created with Terraform it would lose management of itself. I suspect a change was made to it in the GUI that threw Terraform out but can't verify at the moment.

**Comment by joshuajabbour** [comment] 2016-12-23 17:13
Probably a duplicate of #7690

**Comment by stack72** [comment] 2016-12-24 14:38
This is closed via #10910

**Closed by stack72** 2016-12-24 14:38 UTC
Labels: bug, provider/cloudflare

**Comment by bmcintyre21** [comment] 2018-03-08 13:22
This resolved?

**Comment by ofmarconi** [comment] 2018-03-09 13:04
I'm having the same problem, what's the solution ????

**Comment by brafales** [comment] 2018-10-15 14:56
This is still happening in Terraform 0.11.7

**Comment by mihaitodor** [comment] 2018-11-05 13:53
It's happening for me with Terraform v0.11.10 and provider.cloudflare v1.7.0 when I have a 2 type A subdomain entries for 2 different IPs and, for some reason, the IPs change order. I think the provider should detect this situation and not try to apply any changes.

**Comment by lukemurraynz** [comment] 2019-08-15 06:33
I'm having this issue with Terraform 0.12.6 after following: https://www.sergeydotnet.com/using-terraform-with-azure-devops/. Can create new records but when I try and change the value of one of them it can't update it because the record already exists.
