### ISSUE TITLE
terraform fmt adds double quotes to variable, output, module, resource names

### ISSUE THREAD

**Issue by VickyWinner** [hashicorp/terraform#28689] opened 2021-05-12 19:00 UTC
### Terraform Version

```
Terraform v0.14.8
```

### Terraform Configuration Files

```
terraform fmt -recursive
```

### Expected Behavior
Retain the resource/block or variable/output identifiers with their format as terraform 0.12 onwards, double quotes are not required.

### Actual Behavior

variables, outputs, modules, terraform is adding double quotes to all the identifiers.

**Comment by apparentlymart** [comment] 2021-05-12 23:08
Hi @VickyWinner,

What you've observed is the intended behavior of the formatting tool. The quotes around those labels have never been required but they've always been the preferred style shown in our documentation, and `terraform fmt` typically follows the style of the documentation examples, and similarly when Terraform itself generates configuration it will follow the same style.

You find read more background on the design goals and policies for `terraform fmt` in [the `terraform fmt` documentation](https://www.terraform.io/docs/cli/commands/fmt.html).

Since the behavior you have observed is the intended behavior of the command, I'm going to close this. Thanks!

**Closed by apparentlymart** 2021-05-12 23:08 UTC
Labels: bug, new

**Comment by VickyWinner** [comment] 2021-05-13 16:54
can I ask for a feature add with additional option like `-quotes=true`  and `-quotes=false` based on which `terraform fmt` can behave?

**Comment by greeneg** [comment] 2021-05-13 17:52
This is seriously inconsistent. While the documentation has shown double-quoting, I've seen cases with validate that flags things like this as incorrect for style. If the direction is that it should be quoted, please change the parser to enforce this.
