### ISSUE TITLE
Duplicate provider/local value/variable/module call definition when running terraform plan that use modules and shared backend

### ISSUE THREAD

**Issue by lremes** [hashicorp/terraform#30582] opened 2022-02-25 13:14 UTC
### Terraform Version

```
Terraform v1.1.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
```
The issue has been detected also with terraform versions 1.1.3 through 1.1.5

### Terraform Configuration Files

```terraform
variable "aws_region" {
  description = "AWS region"
}

variable "tenant" {
  description = "Tenant name. Used to generate resource names."
}

variable "environment" {
  description = "Environment name. E.g. dev,prod,qa. Used to generate resource names."
}

variable "zone" {
  description = "Zone name. Used to generate resource names."
}

variable "vpc_cidr" {
  description = "Base CIDRs for VPC"
}

variable "availability_zones" {
  description = "List of subnets CIDRs"
  type = list(string)
}

variable "private_subnets" {
  description = "List of subnets CIDRs"
  type = list(string)
}

variable "public_subnets" {
  description = "List of subnets CIDRs"
  type = list(string)
}
```

```terraform
provider "aws" {
  region  = var.aws_region
  
  default_tags {
    tags = {
      Owner = "MYORG"
    }
  }
}

locals {
  id_prefix = join("-", [var.tenant, var.environment])
  eks_cluster_id = join("-", [var.tenant, var.environment, var.zone, "eks"])
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0"

  name = "${local.id_prefix}-vpc"
  cidr = var.vpc_cidr

  azs             = toset(var.availability_zones)
  private_subnets = toset(var.private_subnets)
  public_subnets  = toset(var.public_subnets)

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  enable_flow_log                      = true
  create_flow_log_cloudwatch_iam_role  = true
  create_flow_log_cloudwatch_log_group = true

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.eks_cluster_id}" = "shared"
    "kubernetes.io/role/elb"              = 1
    "Class"                               = "build"
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.eks_cluster_id}" = "shared"
    "kubernetes.io/role/internal-elb"     = 1
  }
}
```

### Debug Output
https://gist.github.com/lremes/483de070674d998c276f085c2069694e

### Expected Behavior
When running terraform locally from CLI, plan should complete without errors.

### Actual Behavior
Terraform reports duplicates for almost all entries.

### Steps to Reproduce
1. On local CLI: `terraform init`
2. On local CLI: `terraform plan`
3. Run `terraform plan` or `terraform apply` in some other environment (CI, terraform cloud, etc.) 
2. On local CLI: `terraform plan` -> local plan is broken

The issue does not occur 100% of the time. Step 3 may not even be necessary.

### Additional Context

We are using terragrunt version v0.36.1 as wrapper for Terraform with Gitlab HTTP backend. The problem also occurs when using plan terraform and Terraform Cloud backend. 

Removing local cache and then re-running init temporarily fixes the problem. When using Terraform Cloud doing "terraform init -reconfigure" also seemed to temporarily fix the problem.

### References
- #29526

**Comment by lremes** [comment] 2022-02-25 13:16
The issue is not module dependent. It seems to be enough that any remote module is included in the configuration.

**Comment by alisdair** [comment] 2022-02-25 14:36
Hi! Thanks for reporting this issue.

I'm unable to reproduce this locally using Terraform 1.1.6 and Terraform Cloud as the backend. Looking at the debug log you provided, it doesn't seem that the backend is relevant, as the errors are generated earlier, when loading the configuration.

The logs are showing that you seem to have multiple copies of your `main.tf` file in your local file system. Error messages include references to `main.tf`, `main 2.tf`, and `main 10.tf`. Perhaps this is caused by Terragrunt, or some other tool which is generating configuration.

Based on this explanation, it doesn't seem that there's a bug in Terraform itself here, as the configuration must be valid when reading all `*.tf` files in the working directory. As a result I'm going to close this issue, but if you find the source of the problem or are able to reproduce the issue with a clean working directory, please do follow up. Thanks!

**Closed by alisdair** 2022-02-25 14:36 UTC
Labels: bug, new

**Comment by lremes** [comment] 2022-02-25 16:50
It seems that duplicate main.tf files are created by iCloud sync. So the issue is not caused by terraform.
The solution seems to be to disable iCloud Sync for the project folders. 
This can be closed.
