### ISSUE TITLE
Vault provider - plan leaks secrets

### ISSUE THREAD

**Issue by MrTrustor** [hashicorp/terraform#11035] opened 2017-01-04 18:20 UTC
### Terraform Version
Terraform v0.8.2

### Affected Resource
- ``vault_generic_secret``

### Terraform Configuration Files
```hcl
resource "aws_iam_user" "foo" {
    name = "foo"
}

resource "aws_iam_access_key" "foo" {
    user = "${aws_iam_user.foo.name}"
}

resource "vault_generic_secret" "foo" {
  path = "secret/shared_pwd/foo/mysecret"

  data_json = <<EOT
{
  "aws_access_key_id":   "${aws_iam_access_key.foo.id}",
  "aws_secret_access_key": "${aws_iam_access_key.foo.secret}"
}
EOT
}
```

### Expected Behavior

``terraform plan`` should not display the secrets stored in Vault (nor should ``terraform apply``). i.e

```
$ terraform plan
[...]
+ vault_generic_secret.foo
    data_json: secure_data
    path:      "secret/shared_pwd/foo/mysecret"

Plan: 1 to add, 0 to change, 0 to destroy.
```
### Actual Behavior

Applying the workaround for #10505, the keys are displayed (for both ``plan`` and ``apply``):

```
$ terraform plan -input=false
[...]
+ vault_generic_secret.foo
    data_json: "{\n  \"aws_access_key_id\":   \"MY_ACCESS_KEY\",\n  \"aws_secret_access_key\": \"MY_SECRET_KEY\"\n}\n"
    path:      "secret/shared_pwd/foo/mysecret"

Plan: 1 to add, 0 to change, 0 to destroy.
```

### References
Also bumping into:
- #10505

**Comment by apparentlymart** [comment] 2017-01-04 19:51
Hi @MrTrustor. Thanks for filing this issue!

This is a known limitation that is mentioned explicitly in several places in the documentation. Addressing it requires Terraform core to get some first-class support for understanding when attributes are sensitive, which it currently lacks. (Currently we support sensitive *outputs*, but can't mark attributes as sensitive nor propagate sensitive-ness through interpolations.)

Therefore I think this issue generalizes to being a duplicate of #8076, and so I'm going to close this to consolidate the discussion over there.

For the moment it is necessary to exercise care when using the Vault provider, and indeed any other resource that deals with secrets (`tls_private_key`, `aws_db_instance` passwords, etc), such as isolating the Vault provider resources into their own Terraform config that gets applied from a more secure environment.

**Closed by apparentlymart** 2017-01-04 19:51 UTC
