### ISSUE TITLE
terraform kubernetes provider 2.0.0 load_config_file deprecation, causing dependency issue

### ISSUE THREAD

**Issue by sanzzz** [hashicorp/terraform#27578] opened 2021-01-23 01:16 UTC
HI ,
I am trying to create a rke management cluster, for that I followed the https://github.com/rancher/terraform-provider-rke/tree/master/examples/aws_ec2 , I am able to create the rke cluster without any issues.
The problem is when I am trying to create namespace on the rke kubernetes cluster (in below code) to deploy an application (rancher), I see problem with terraform 2.0.0 version. 
 Error: could not open kubeconfig "./kube_config_cluster.yml": stat ./kube_config_cluster.yml: no such file or directory.  ——  Looks like namespace is looking for kube_config_cluster.yml  before it is generated.

I am able to create namespace without any issue with 1.13.3 kubernetes provider version, so I am suspecting load_config_file option deprecated in 2.0.0 provider version is causing the problem to resolve dependency. namespace is looking for kube_config_cluster.yml before it being generated in 2.0.0 kubernetes provider version.
-->

### Terraform Version
$ /tmp/terraform -version
Terraform v0.13.5

### Terraform Configuration Files
resource "rke_cluster" "cluster" {
  nodes {
    address = module.nodes.internal_ips[0]
    internal_address = module.nodes.internal_ips[0]
    user    = module.nodes.ssh_username
    ssh_key = module.nodes.private_key
    role    = ["controlplane", "etcd", "worker"]
  }
  nodes {
    address = module.nodes.internal_ips[1]
    internal_address = module.nodes.internal_ips[1]
    user    = module.nodes.ssh_username
    ssh_key = module.nodes.private_key
    role    = ["controlplane", "etcd", "worker"]
  }
  nodes {
    address = module.nodes.internal_ips[2]
    internal_address = module.nodes.internal_ips[2]
    user    = module.nodes.ssh_username
    ssh_key = module.nodes.private_key
    role    = ["controlplane", "etcd", "worker"]
  }

}

resource "local_file" "kube_cluster_yaml" {
  filename = “./kube_config_cluster.yml"
  content  = rke_cluster.cluster.kube_config_yaml
}

provider "kubernetes" {
  load_config_file = true                  —————————————————> deprecated in terraform 2.0.0, might be causing the problem.
  config_path = local_file.kube_cluster_yaml.filename
  config_context = "local"
}

provider "helm" {
  kubernetes {
    config_path = local_file.kube_cluster_yaml.filename
    config_context = "local"
  }
}

resource "kubernetes_namespace" "cattle-system" {
  metadata {
    name = "cattle-system"
  }
}

resource "helm_release" "rancher" {
  name       = "rancher"
  namespace  = "cattle-system"
  repository = "https://releases.rancher.com/server-charts/latest"
  chart      = "rancher"
  set {
    name  = "tls"
    value = "external"
  }
}

### Debug Output
$ /tmp/terraform apply -var-file ../../cluster-properties/aws/pdx/preprod/terraform.tfvar 
module.nodes.data.aws_subnet_ids.selected: Refreshing state...
data.aws_route53_zone.selected: Refreshing state...
module.nodes.data.aws_ami.centos: Refreshing state...
module.nodes.data.aws_security_group.selected: Refreshing state...
data.aws_acm_certificate.issued: Refreshing state...
data.aws_security_group.selected: Refreshing state...
data.aws_subnet_ids.selected: Refreshing state...

Error: could not open kubeconfig "./kube_config_cluster.yml": stat ./kube_config_cluster.yml: no such file or directory

### Expected Behavior
Kubernetes namespace should be created after the kube_config_cluster.yml is generated from resource "local_file" "kube_cluster_yaml" and used in provider "kubernetes" {

### Actual Behavior
Kubernetes namespace is looking for kube_config_cluster.yml prior to ./kube_config_cluster.yml generation.

Is there any way to create dependency on kube_config_cluster.yml for namespace (kubernetes provider)  in the above case?

Steps to reproduce :

https://github.com/rancher/terraform-provider-rke/tree/master/examples/aws_ec2 , terraform init and terraform apply from this directory.

**Comment by pselle** [comment] 2021-01-25 16:39
Hi @sanzzz, could you help making a simple reproduction case to help delineate where your issue is with Terraform Core? It sounds like your issue might be specific to the RKE provider. But I wonder why you opened this issue here, rather on that provider.

**Comment by jbardin** [comment] 2021-01-25 20:18
Hi @sanzzz,

It appears the problem here is the use of the `local_file` resource to create the provider configuration. The configuration file won't be created until the resource have been applied but the [`helm`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs) provider may be expecting the configuration during plan. If this should not be the case, you can file an issue with the provider itself.  

One way to work around this is to create the infrastructure using multiple configurations, so that you can deploy the resource in multiple phases. You may find more help in the [community forum](https://discuss.hashicorp.com/), where there are more users familiar with the details of these providers. 

Since this isn't an issue with terraform itself, I'm going to close this out for now. 

Thanks!

**Closed by jbardin** 2021-01-25 20:18 UTC
Labels: bug, new, waiting-response
