### ISSUE TITLE
Terraform registry: incorrect parsing of required/optional values

### ISSUE THREAD

**Issue by sdebruyn** [hashicorp/terraform#25226] opened 2020-06-12 05:09 UTC
When you set an input variable to have a default value of `null` it is seen as an optional value by Terraform itself. But on the registry page, those variables are marked as required.

**Comment by mildwonkey** [comment] 2020-06-16 12:08
Hi @sdboyer ! This looks like a duplicate of https://github.com/hashicorp/terraform/issues/21417, so I am going to close it. thank you!

**Closed by mildwonkey** 2020-06-16 12:08 UTC
Labels: registry
