### ISSUE TITLE
An option to upgrade to v0.12 configs that are still backwards compatible with v0.11

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20220] opened 2019-02-04 18:54 UTC
### Current Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

### Use-cases

There are many existing v0.11 compatible configurations that may not need new v0.12 language features. There should be an option to upgrade these configurations so that they are both forwards-compatible with v0.12 and backwards compatible with v0.11.

Many enterprise users of Terraform tend to be conservative and will be slow to move to v0.12. Having one configuration that works with both versions allows customers to stay on v0.11 and evaluate v0.12 before fully diving in.

### Attempted Solutions

The `0.12upgrade` option seems to do a good enough job of migrating configs to be v0.12 compatible but it seems to also make other changes that break backwards compatibility with v0.11.

For example:

`${var.MyVariable}` is upgraded to `var.MyVariable`, which is no longer compatible with v0.11.

This is great if you're moving to v0.12 and don't plan to go back; but is problematic if you're evaluating both versions.

### Proposal

Essentially, the proposal here is to extend `0.12upgrade` so that someone can opt for a full upgrade (as it currently does) or a less exhaustive backwards-compatible upgrade.

The backwards-compatible upgrade essentially behaves like a linter so that it only fixes syntax errors that were problematic (but acceptable) in HCL1 and are now unacceptable in HCL2. For example:
- https://github.com/hashicorp/terraform/issues/19325
- https://github.com/hashicorp/terraform/issues/19407

**Comment by apparentlymart** [comment] 2019-02-22 00:03
The tool doesn't implement this because it is not really possible in general to guarantee that the result will be both 0.11 and 0.12 compatible... if the old configuration is using undocumented tricks that were replaced with real features in 0.12 (but with different syntax) then we must decide either to leave them untouched or to update them and render the configuration incompatible with 0.11.

I think perhaps the best compromise here would be a flag to opt out from specifically the "un-quoting" behavior, leaving expressions wrapped in `"${ ... }` even though 0.12 doesn't require that, which would then allow users to opt out of the primary culprit in the result being not-0.11-compatible but the tool would still make 0.11-incompatible changes in the rarer situations where there is no common equivalent between the two due to reliance on undocumented tricks in the input.

---

One detail remains problematic, and is the main reason we didn't attempt this in the first round: 

```hcl
    foo = ["${other.resource.*.id}"]
```

In older versions of Terraform these redundant brackets were required to signal to Terraform that a list was intended. This was made optional in a 0.10 release with the intent of it being phased out, but then this technique re-emerged later as a workaround for a bug in the 0.11 SDK with unknown values. The upgrade tool currently unwraps these expressions if it can prove that the inner expression returns a list and the argument is not defined as expecting a list of lists:

```hcl
    foo = other.resource.*.id
```

The "preserve quoting" flag discussed above would retain is as `"${other.resource.*.id}"`, but would still need to remove the surrounding brackets for 0.12 compatibility. This _should_ work in 0.11, as long as this wasn't an example of working around the aforementioned old SDK bug, in which case it would probably cause the error "a list is required" when running in 0.11.

We'll need to try this with some real-world configurations to see how much of a problem it is in practice.

---

I expect that conservative enterprise users would not be upgrading immediately to Terraform v0.12.0 anyway, so to avoid delaying the final release with this feature I expect we'll leave it out from the initial release and then consider whether adding the flag I mentioned above in a point release would be a helpful addition. Therefore I'm going to remove this from the initial v0.12.0 milestone and we'll re-evaluate it once the initial v0.12 release is complete.

**Comment by bflad** [comment] 2019-02-22 04:17
> The "preserve quoting" flag discussed above would retain is as "${other.resource.*.id}", but would still need to remove the surrounding brackets for 0.12 compatibility. This should work in 0.11, as long as this wasn't an example of working around the aforementioned old SDK bug, in which case it would probably cause the error "a list is required" when running in 0.11.

FYI, even if you go back and add the wrapping `[` and `]` in this scenario, 0.12 will (rightfully) complain about expecting a string as the first element of the list and not a list(string). e.g.

```
        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test226640772/main.tf line 21:
          (source code not available)

        Inappropriate value for attribute "availability_zones": element 0: string
        required.
```

There may be clever workarounds in this scenario, but we opted to temporarily "expand" these arguments to their proper list(string) via `["${TYPE.NAME.*.ATTRIBUTE[0]}", "${TYPE.NAME.*.ATTRIBUTE[1]}"...]` to maintain forwards and backwards compatibility in the Terraform AWS Provider acceptance testing. See also: https://github.com/terraform-providers/terraform-provider-aws/pulls?q=is%3Apr+temporarily+expand+is%3Aclosed

**Comment by apparentlymart** [comment] 2019-02-22 19:39
Yes, it's a good point that the situation for provider testing and the situation for automatic upgrade are different: the upgrade tool can only make changes that are provably safe in all cases (i.e. it's conservative) while our hand-written updates to existing test cases can be tailored to the specific situation, and so we have more options available for working around those situations where existing bugs that are now fixed require some differently-written configuration to work in both 0.11 and 0.12 at the same time.

**Comment by mildwonkey** [comment] 2019-09-06 15:53
Hello! At this point, we don't plan on making any more changes to `terraform 0.12upgrade` (barring a critical bug fix), so I am going to close this issue. Thank you for submitting it!

**Closed by mildwonkey** 2019-09-06 15:53 UTC
Labels: cli, enhancement, partner/oracle
