### ISSUE TITLE
data terraform_remote_state is locked when read??? Causes issues in concurrent applies

### ISSUE THREAD

**Issue by stonefury** [hashicorp/terraform#18761] opened 2018-08-29 21:36 UTC
### Terraform Version

```
...
```

### Terraform Configuration Files

```

data "terraform_remote_state" "network" {
  backend   = "azurerm"
  workspace = "${terraform.workspace}"
  environment = "test"

  config {
    resource_group_name  = "${local.workspace["remote_state_resource_group_name"]}"
    access_key           = "${var.access_key}"
    storage_account_name = "${local.workspace["tfstate_storage_account_name"]}"
    container_name       = "${local.workspace["container_name"]}"
    key                  = "${local.workspace["remote_state_key"]}"
  }
}
```

### Actual Behavior

When multiple terraform apply's are running that are using the same data source I get this error. I guess the remote state is locked when read??  I had to break up my project because it was too large which is why I'm now running terragrunt, which is just like a makefile or script going into my module folders and running terraform apply. They all need to pull data from the same remote state.

Error: Error refreshing state: 1 error(s) occurred:

* data.terraform_remote_state.network: 1 error(s) occurred:

* data.terraform_remote_state.network: data.terraform_remote_state.network: error loading the remote state: failed to lock azure state: storage: service returned error: StatusCode=409, ErrorCode=LeaseAlreadyPresent, ErrorMessage=There is already a lease present.
RequestId:b2c4ec81-c01e-00a8-7cdf-3fe463000000
Time:2018-08-29T21:32:33.1034159Z, RequestInitiated=Wed, 29 Aug 2018 21:32:32 GMT, RequestId=xxxxxxxxx, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
Lock Info:

### Steps to Reproduce

Well I can manually acquire the lease through the azure portal, then run terraform apply, and I get the error, confirming it is obtaining a lock on the state file for terraform_remote_state. :(

**Comment by tombuildsstuff** [comment] 2018-08-30 18:14
Hi @stonefury 

Based on what I can see here this is a duplicate of https://github.com/hashicorp/terraform/issues/17046 which rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of - please subscribe to that for updates :)

Thanks!

**Comment by stonefury** [comment] 2018-08-30 20:26
@tombuildsstuff of course, thanks for doing that.  In my case I'm having issues with the data source terraform_remote_state being locked during reading.  The lock is not broken or stuck, just that it does a lock on the state file to read the data for the data source causes concurrency issues.  Just wanted to clarify.

**Comment by mildwonkey** [comment] 2018-08-31 15:00
Hi @stonefury,

Remote state locking is an important (and fundamental) terraform feature, which you can read about [here](https://www.terraform.io/docs/state/locking.html). Without locking, we could not ensure that concurrent runs are not trying to act on the same resource.

You might also want to read through some of our [Terraform Best Practices](https://www.terraform.io/docs/enterprise/guides/recommended-practices/index.html) documentation - while some of the specifics are designed for Terraform Enterprise customers, many of the best practices apply to all users.

**Comment by stonefury** [comment] 2018-08-31 18:12
@mildwonkey I agree on that, but does that include locking for data sources?  I guess that does make sense.  So in cases where we need to break up our project and want to build components concurrently, is there a method of waiting for the lock to be released?  I think if I just had a timeout option that applied to reading the state file from a data.terraform_remote_state it would probably work, and I could build my project at the top level.  

My work-around now is having a script, which just goes into each subfolder sequentially and runs apply.

Thank you very much for your comment!

**Comment by stonefury** [comment] 2018-09-04 17:02
@tombuildsstuff  could you reconsider re-opening this?  What I'm talking about is the lock that is being acquired on the remote data source, not the lock on the remote state file.

If I could at least have the option to ignore the lock.  I tried --lock=false but it doesn't work for azure data sources.

**Comment by mildwonkey** [comment] 2018-09-04 17:05
Whoops, sorry @stonefury - I've re-opened it. I should have done that sooner, my apologies.

**Comment by tombuildsstuff** [comment] 2018-09-12 11:05
@mildwonkey I may be coming at this from the wrong direction, but since the Data Source is reusing the Backend (which has a known bug around locking https://github.com/hashicorp/terraform/issues/17046, which I believe is the underlying cause here) - I don't believe this issue is specific to the Data Sources (since otherwise we'd be seeing this across other Providers too), and so I believe fixing #17046 will fix this issue - and hence we should treat this as a duplicate?

**Comment by mildwonkey** [comment] 2018-09-12 18:52
@tombuildsstuff I will happily defer to your judgement here. If I recall correctly, I had left this ticket open in a browser for awhile and made some comments (or maybe label changes?) without realizing that you had touched it as well. Sorry!

**Comment by tombuildsstuff** [comment] 2018-10-22 19:30
Taking another look at this - this appears to be the same underlying issue as #17046, rather than having multiple issues open tracking the same thing I'm going to close this in favour of #17046.

Thanks!

**Closed by tombuildsstuff** 2018-10-22 19:30 UTC
Labels: backend/azure

**Comment by rdonkin** [comment] 2018-11-20 16:17
@tombuildsstuff @mildwonkey  Is this really Azure-specific like #17046?  

This seems to be a general question of how Terraform does locking, regardless of provider.

It's reasonable for remote state data access to need to stop any concurrent changes to the target state it is reading, for the duration of the Terraform run - in database terms, this would be a 'read lock', allowing several concurrent readers but disallowing writes.

The current Terraform model appears to take exclusive ('write') locks only, which block all other readers and writers.  This is always correct but reduces concurrency compared to using read locks in the case of a Terraform data source reading remote state.

**Comment by maxbog** [comment] 2019-05-14 08:22
@tombuildsstuff I'm struggling to understand how the #17046 fix will fix this bug. I understand that your fix will help with unlocking the state, but the issue here is that two parallel terraform processes will try to acquire a lease when fetching the remote state. 

I looked at the code a bit and did not find any retry logic for acquiring the lease, so when this problem occurs, terraform crashes. Could you explain a bit how the #17046 fix will also fix this issue?
