### ISSUE TITLE
coalesce returns null argument

### ISSUE THREAD

**Issue by phy1729** [hashicorp/terraform#22290] opened 2019-08-01 14:32 UTC
### Terraform Version
```
Terraform v0.12.6
+ provider.null v2.1.2
```

### Terraform Configuration Files
```hcl
variable "test" {
  type = bool
}

resource "null_resource" "foo" {
  count = var.test ? 1 : 0
}

resource "null_resource" "bar" {
  count = var.test ? 0 : 1
}

output "test" {
  value = coalesce(null_resource.foo[0].id, null_resource.bar[0].id)
}
```

### Debug Output
https://gist.github.com/phy1729/d794e6e08d704b4e174b005be1e6630a

### Expected Behavior
The bar null resource should be created and its ID echoed to the terminal.

### Actual Behavior
The bar null resource was created, but no outputs were echoed.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -var test=false`

**Comment by teamterraform** [comment] 2019-08-01 16:06
Thanks for reporting this, @phy1729! I was easily able to reproduce the issue.

---

As a note to anyone digging into this issue, this was a helpful addition for debugging:

```hcl
output "foo_id" {
  value = format("foo id: %s", null_resource.foo[0].id)
}

output "bar_id" {
  value = format("bar id: %s", null_resource.bar[0].id)
}
```


```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

bar_id = bar id: 7070253155175572176
value_of_test = false
```

**Comment by userhas404d** [comment] 2019-09-19 21:40
running into this same issue. 

test config: 
```
data "null_data_source" "public" {
  count = 1

  inputs = {
    foo = "bar"
  }
}

data "null_data_source" "private" {
  count = 0

  inputs = {
    foo = "baz"
  }
}

output "first_element_not_null" {
  value = coalesce(data.null_data_source.public[0].outputs, data.null_data_source.private[0].outputs)
}

output "first_element_null" {
  value = coalesce(data.null_data_source.private[0].outputs, data.null_data_source.public[0].outputs)
}

output "list_first_element_not_null" {
  value = coalescelist(data.null_data_source.public.*.outputs, data.null_data_source.private.*.outputs)
}

output "list_first_element_null" {
  value = coalescelist(data.null_data_source.private.*.outputs, data.null_data_source.public.*.outputs)
}
```
expected output: 

all outputs should return a value

actual output: 

```
data.null_data_source.public[0]: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

first_element_not_null = {
  "foo" = "bar"
}
list_first_element_not_null = [
  {
    "foo" = "bar"
  },
]
list_first_element_null = [
  {
    "foo" = "bar"
  },
]
```
seems like `coalesce` breaks if the first object being tested is null when a resource or data source is referenced. `coalescelist` seems to work as intended - not sure if that's relevant here but figured I'd include it for completeness.

**Comment by jbardin** [comment] 2021-05-14 13:27
Hello,

This type of error now produces a much more precise error message to help indicate where the problem lies:

```
╷
│ Error: Invalid index
│
│   on main.tf line 14, in output "test":
│   14:   value = coalesce(null_resource.foo[0].id, null_resource.bar[0].id)
│     ├────────────────
│     │ null_resource.foo is empty tuple
│
│ The given key does not identify an element in this collection value.
```

(not that in the terminal the `foo[0].` index is also underlined to highlight that operation).

Since it's no longer possible no longer pass in unexpected null values from invalid arguments, I'm going to close this out.

Thanks!

**Closed by jbardin** 2021-05-14 13:27 UTC
Labels: bug, config, v0.12
