### ISSUE TITLE
crash at terraform plan stage

### ISSUE THREAD

**Issue by PS6** [hashicorp/terraform#27584] opened 2021-01-25 07:12 UTC
[crash.log](https://github.com/hashicorp/terraform/files/5864781/crash.log)

### Terraform Version
Terraform v0.14.5
+ provider registry.terraform.io/terraform-providers/cloudstack v0.3.0
(updated to newer version to see if fixed)
(this is just for information)

```
...
```

### Terraform Configuration Files

```terraform
...
```

### References

[crash-2.log](https://github.com/hashicorp/terraform/files/5864815/crash-2.log)

**Comment by pselle** [comment] 2021-01-25 16:45
Hi @PS6,
to better understand the issue & make it easier to reproduce for anyone else would you mind sharing more details according to the GitHub issue template? e.g.

 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - a simplified config for reproduction
 - expected behavior
 - actual behavior
 - steps to reproduce

Thanks.

**Comment by PS6** [comment] 2021-01-25 16:50
Hi Pam,

It was just for information only, I have ditched all files and created new
one from scratch.
I believe there is some kind of race condition somewhere, but it was too
hard to find out where.

If I get it again I'll try to capture more to replicate.

Regards,
Paul
----
P.Shah
https://shah.pm/tel/#+31654951622

**Comment by pselle** [comment] 2021-01-25 16:58
Thanks for the quick reply -- I looked at the log and pulled out some of the crash (although it would be helpful to see what actual UI error Terraform gave, but I understand you didn't save that)

```
2021/01/25 07:09:13 [TRACE] EvalWriteOutput: Saving value for output.default-egress-ports in state
2021/01/25 07:09:13 [TRACE] vertex "output.default-egress-ports": visit complete
2021-01-25T07:09:14.787Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: panic: interface conversion: interface {} is nil, not string
2021-01-25T07:09:14.787Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 
2021-01-25T07:09:14.788Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: goroutine 25 [running]:
2021-01-25T07:09:14.788Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/cloudstack.applyFilters(0xc000190900, 0xc000359ce0, 0x6, 0x131ba00, 0xc000359ce0)
2021-01-25T07:09:14.788Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/cloudstack/data_source_cloudstack_template.go:162 +0x31a
2021-01-25T07:09:14.788Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/cloudstack.dataSourceCloudstackTemplateRead(0xc00019a070, 0x122d720, 0xc0000b42c0, 0xc00019a070, 0x0)
2021-01-25T07:09:14.788Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/cloudstack/data_source_cloudstack_template.go:87 +0x369
2021-01-25T07:09:14.789Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc0000f8c80, 0xc000206640, 0x122d720, 0xc0000b42c0, 0xc00037bcf8, 0x1, 0x0)
2021-01-25T07:09:14.789Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:390 +0x88
2021-01-25T07:09:14.789Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc0000f9b80, 0xc0003fdac0, 0xc000206640, 0xc000206640, 0x0, 0x0)
2021-01-25T07:09:14.789Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:442 +0x92
2021-01-25T07:09:14.790Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000ca88, 0x15726a0, 0xc0003ff0b0, 0xc00006a2c0, 0xc00000ca88, 0xc0003ff020, 0x11cc160)
2021-01-25T07:09:14.790Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:990 +0x499
2021-01-25T07:09:14.790Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadDataSource_Handler(0x131e260, 0xc00000ca88, 0x15726a0, 0xc0003ff0b0, 0xc00064d310, 0x0, 0x0, 0x0, 0xc00040a0b0, 0xaf)
2021-01-25T07:09:14.790Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3055 +0x23e
2021-01-25T07:09:14.791Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ba000, 0x15787a0, 0xc0004baf00, 0xc000401300, 0xc000114330, 0x201e570, 0x0, 0x0, 0x0)
2021-01-25T07:09:14.791Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc/server.go:966 +0x4a2
2021-01-25T07:09:14.791Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0004ba000, 0x15787a0, 0xc0004baf00, 0xc000401300, 0x0)
2021-01-25T07:09:14.791Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc/server.go:1245 +0xd61
2021-01-25T07:09:14.792Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000032570, 0xc0004ba000, 0x15787a0, 0xc0004baf00, 0xc000401300)
2021-01-25T07:09:14.792Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc/server.go:685 +0x9f
2021-01-25T07:09:14.792Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: created by github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-25T07:09:14.792Z [DEBUG] plugin.terraform-provider-cloudstack_v0.3.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-cloudstack/vendor/google.golang.org/grpc/server.go:683 +0xa1
2021/01/25 07:09:14 [TRACE] vertex "data.cloudstack_template.web4-c83": visit complete
```

The trace looks suspiciously like it lies in the cloudstack provider, so I'll retag this issue to send it that way (since it's under the terraform-providers GitHub org).

**Comment by jbardin** [comment] 2021-01-25 19:31
Hello,

The[cloudstack provider](https://github.com/hashicorp/terraform-provider-cloudstack) has been archived and is no longer maintained (notice its absence in the new terraform provider registry). Looking at the github UI, it appears that there are no public forks that have taken over development. 

Closing here since there is nothing we can do from the terraform project. If this is something you want to fix, I would suggest forking the repo and building a local copy of the provider. 

Thanks!

**Closed by jbardin** 2021-01-25 19:31 UTC
Labels: bug, new, provider/cloudstack
