### ISSUE TITLE
terraform init -backend=true with no terraform backend resource should error out

### ISSUE THREAD

**Issue by goraxe** [hashicorp/terraform#14156] opened 2017-05-02 20:27 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
Remote backend 

### Expected Behavior

When a directory is initialized via 
```
terraform init -backend=true
```
And a terraform backend resource is not present an error or warning should occur.  If local state is being used the backend flag should not be present or false.  Thus a terraform backend resource should be present with sufficient config (or asked for) if the -backend=true flag is present.  

### Actual Behavior
The missing backend is silently ignored, and local state is initialized.  This means a run of terraform apply on an ephemeral build agent will store state locally or not fetch the remote state (causing dupes of resources to be created).   

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. mkdir test; cd test; touch resources.tf
2. `terraform init -backend=true -backend-config=<tfvars file path>`

**Comment by ankitforcode** [comment] 2017-11-08 11:05
https://github.com/hashicorp/terraform/pull/16589

**Comment by apparentlymart** [comment] 2017-12-05 19:00
Hi @goraxe! Sorry for the lack of response here.

Reading between the lines here, it sounds like you're asking for a way to make `terraform init` disable the behavior of defaulting to the local backend and instead generate an error if there is no `backend` block in configuration.

This will never be the _default_ behavior because the local backend default is an important "getting started" feature to allow users to learn about Terraform without forcing them to learn about backends. However, we could permit this as an option.

I'd like to understand better the use-case here, if you're willing. I assume your motivation for asking for this was some sort of accident involving accidental use of the local backend when remote was intended, causing some resources to get "lost" due to never being persisted to remote. Is that right?

I know it's been a long time since you opened this, but any additional context you can recall here would be helpful, such as whether you are running Terraform locally or within some sort of automation, what event prompted you to open this issue, etc. Thanks!

**Comment by goraxe** [comment] 2017-12-29 01:02
Hi @apparentlymart 

Having to scratch my memory a little here.  I believe as you guessed there was an issue where local state existed on a jenkins slave and in some automation.  Things have switch a-roo-ed a little since then however I think the scenario was we believed we had configured terraform with a s3 backend (via a file backend.tf).  We had a s3 config block but had no config options or the config options where coming from var-files (which wouldn't work as it wasn't the backend config file format). 

From the issue I was hoping for a guard against the situation 'I believe I have ya configured for remote state storage but actually I gone goofed and your storing state local please holla at me' . 

 I was suggesting if the user expressly sets -backend=true then expect an explicit backend config block, error out if the config is suspect.  This would imply semantics for the backend flag that when its true == remote ensure there exists a well configured/usable remote backend, false == local with the default being -backend = false so no change to the current status quo.

To me it's just a bit of usability polish, and with a couple of versions on this may actually be the behaviour these days. 

Hope this makes sense

Cheers
Goraxe

**Comment by mildwonkey** [comment] 2019-09-06 13:31
Hi @goraxe !
In the time since you opened this issue, we added a warning from `terraform init` if `-backend-config` was used without a `backend` block:

```
Missing backend configuration

-backend-config was used without a "backend" block in the configuration.

If you intended to override the default local backend configuration,
no action is required, but you may add an explicit backend block to your
configuration to clear this warning:

terraform {
  backend "local" {}
}

However, if you intended to override a defined backend, please verify that
the backend configuration is present and valid.
```

We've specifically chosen do this in place of an error, so I am going to close this issue. Thanks!

**Closed by mildwonkey** 2019-09-06 13:31 UTC
Labels: cli, enhancement
