### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by omame** [hashicorp/terraform#15837] opened 2017-08-17 09:08 UTC
### Terraform Version
0.10.1

### Terraform Configuration Files
https://gitlab.com/gitlab-com/gitlab-com-infrastructure/blob/master/environments/staging/main.tf

### Debug Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x17792fc]

goroutine 8278 [running]:
github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).logStderr(0xc4207ce3f0, 0x416aaa0, 0xc42000cca8)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:750 +0x39c
created by github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin/client.go:544 +0xe2f
```

### Panic Output
```
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="2017/08/17 10:44:29 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/WebStaging/providers/Microsoft.Compute/availabilitySets/WebStaging?api-version=2016-04-30-preview:"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="HTTP/1.1 200 OK"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Transfer-Encoding: chunked"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Cache-Control: no-cache"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Content-Type: application/json; charset=utf-8"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Date: Thu, 17 Aug 2017 08:44:29 GMT"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Expires: -1"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Pragma: no-cache"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Server: Microsoft-HTTPAPI/2.0"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Server: Microsoft-HTTPAPI/2.0"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Strict-Transport-Security: max-age=31536000; includeSubDomains"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="Vary: Accept-Encoding"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Correlation-Request-Id: 8804b6c2-312a-4dfb-9a11-94c713d56094"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Ratelimit-Remaining-Subscription-Reads: 14958"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Request-Id: 9e64900d-48f4-43ef-b4c0-db546d84cc92"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Routing-Request-Id: EASTUS2:20170817T084430Z:8804b6c2-312a-4dfb-9a11-94c713d56094"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry="X-Ms-Served-By: 2dc13929-703a-4ef9-8704-b5a09eacc197_131470844694387370"
2017-08-17T10:44:29.883+0200 [DEBUG] plugin.terraform-provider-azurerm_v0.1.5_x4: log from plugin: entry=
2017-08-17T10:44:29.883+0200 [ERROR] plugin.terraform-provider-azurerm_v0.1.5_x4: error parsing json from plugin: error="json: cannot unmarshal number into Go value of type map[string]interface {}"
```

### Expected Behavior
Successful `plan`.

### Actual Behavior
Terraform crash.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Upgrading from version `0.9.11`.

I'm not sure if it's a bug in the plugin or in core but the error message suggests that it may be a vendoring issue with `go-plugin`.

### References
I couldn't find any.

**Comment by radeksimko** [comment] 2017-08-17 09:14
Hi @omame 
sorry for the crash and any inconvenience caused by it.
I believe it's a duplicate of https://github.com/hashicorp/terraform/issues/15822 which was fixed in https://github.com/hashicorp/go-plugin/pull/43 and [released yesterday](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0102-august-16-2017) as part of `0.10.2`.

With that in mind I will close this issue, but please let us know if you keep experiencing this issue after upgrading to `0.10.2`. Thanks!

**Comment by radeksimko** [comment] 2017-08-17 09:14
Duplicate of #15822

**Closed by radeksimko** 2017-08-17 09:14 UTC
Labels: crash

**Comment by omame** [comment] 2017-08-17 12:54
Thanks @radeksimko!
