### ISSUE TITLE
Local lists don't support interpolation

### ISSUE THREAD

**Issue by salvianreynaldi** [hashicorp/terraform#16856] opened 2017-12-06 10:04 UTC
Terraform said that a local list variable (which elements have interpolations) is not a list

### Terraform Version
```
Terraform v0.11.1
+ provider.aws v1.5.0
+ provider.template v1.0.0
```

### Terraform Configuration Files
```hcl
provider "aws" {
    region = "ap-southeast-1"
}
locals {
  my-variable = "my.${var.input-variable}.is.working"
  my-list-variable = [
    "${local.my-variable}.this.should.work",
    "${local.my-variable}.this should.work.too"
  ]
}
module "my-module" {
  // ...
  a-module-variable = "${local.my-list-variable}"
}

// in my-module
data "aws_iam_policy_document" "a-document" {
    statement {
        effect = "Allow",
        actions = [
            "s3:PutObject"
        ]
        resources = "${var.a-module-variable}"
    }
}

```

### Expected Behavior

The local variable should be interpolated correctly

### Actual Behavior

```
module.my-module.data.aws_iam_policy_document.a-document: statement.1.resources: should be a list
```
If I change `${local.my-variable}` in `${local.my-list-variable}` to literal strings like `abc`, the module can be applied normally. Switching to input variable (+ literals as it doesn't support interpolation) works too

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by salvianreynaldi** [comment] 2017-12-07 04:38
I found another list related issue:
apparently the result of `concat(list("a", "b"), var.a-list-variable)` is not treated as a list either, and replacing `list("a", "b")` above with ["a", "b"] will also throw another error
Is it supposed to be like this?

**Comment by yahooguntu** [comment] 2017-12-11 20:42
I'm seeing the original issue as well. If I remove all interpolated values from the list it works.

**Comment by TheYorkshireDev** [comment] 2017-12-14 13:10
@yahooguntu I see exactly the same behaviour.

@jbardin is this a regression that was introduced in the last few releases? I find it hard to imagine nobody has reported this in the past.

**Comment by jbardin** [comment] 2017-12-15 15:39
Hi @TheYorkshireDev,

Do you have a minimal example of a configuration which doesn't work? The "locals" part of this should work fine, so my only guess is that this is another instance of #16916.

**Comment by TheYorkshireDev** [comment] 2017-12-15 18:47
@jbardin I have tried to reproduce the issue above and cannot. I feel when I was having issues it was related to #16916 

This is the config I used to try and reproduce it and couldn't:

Module (firewalls) `variables.tf`:
```
variable "tags" {
  description = "List of tags to apply to the firewall"
  type        = "list"
}
```
Module (firewalls) `main.tf`:
```
resource "digitalocean_firewall" "FIRE" {
  name = "NAME"

  tags = "${var.tags}"

  ...
}
```

Entry File `root.tf`
```
provider "digitalocean" {
  token = "TOKEN"
}

variable "input_variable1" {
  default = "HOMER"
}

variable "input_variable2" {
  default = "BART"
}

locals {
  my-variable = "my.${var.input_variable1}.is.working"
  my-list-variable = [
    "${local.my-variable}.ONE",
    "${local.my-variable}.TWO"
  ]
}

module "firewalls" {
  source = "./firewalls"
  tags = "${local.my-list-variable}"
}
```

Hope this helps.

**Comment by salvianreynaldi** [comment] 2018-01-12 09:56
@TheYorkshireDev  I found that the interpolation will not work if it contains a data's / resource's value, direct/indirectly; e.g. with your example:
```hcl
locals {
  my-variable = "my.${var.input_variable1}.is.working-${data.aws_region.current.name}"
  my-variable-2 = "my.${var.input_variable1}.is.working"
  my-list-variable = [
    "${local.my-variable}.ONE", # doesn't work
  ]
  my-list-variable-2 = [
    "another.ONE.${aws_s3_bucket.id}", # doesn't work too
  ]
  my-list-variable-3 = [
    "${local.my-variable-2}.ONE", # works
  ]
}
```

Can you test it in your setup? Is this the expected behaviour?

**Comment by paxsonsa** [comment] 2018-02-09 07:26
I am getting similar behavior @salvianreynaldi
 It appear that the interpolation to a list does not happen. I have another scenario where this is happen with a module that takes a list from a resource (e.g. list of ssh key ids based on a ssh key resource in digital ocean provider)

**Comment by binlialfie** [comment] 2018-02-13 15:00
same here

res_list     = "${concat(list(local.res_ENV, local.res_projName))}"

returns error

At column 3, line 1: concat: argument 1 should be type list, got type string in:

triggers (res_list): '' expected type 'string', got unconvertible type '[]interface {}'

**Comment by shawnhwei** [comment] 2018-02-23 10:24
I have also experienced this.

**Comment by mtthoyle** [comment] 2018-02-26 17:51
I have same problem:
locals {
  default_listeners = [
    { instance_port = 443 instance_protocol = "https" lb_port = 443 lb_protocol = "https" ssl_certificate_id = "${aws_iam_server_certificate.mod.arn}" },
    { instance_port = 8081 instance_protocol = "http" lb_port = 8081 lb_protocol = "http" }                                                                                      
  ]
}

Then passing local.default_listeners to my module I get the error:  listener: should be a list 
If I remove the line with ${aws_iam_server_certificate.mod.arn} and only use the other line it works fine.

**Comment by salvianreynaldi** [comment] 2018-03-09 04:33
The issue in the original post can be worked around by using `[]` in the module, i.e.
```hcl
// in my-module
data "aws_iam_policy_document" "a-document" {
    statement {
        effect = "Allow",
        actions = [
            "s3:PutObject"
        ]
        resources = ["${var.a-module-variable}"] # it works
    }
}
```

but the issue with local lists still remain

**Comment by oba11** [comment] 2018-05-17 13:44
I'm having the same issue as well which is strange

module/s3/main.tf
```
locals {
  encryption_config = {
    enabled = [{
      rule = [{
        apply_server_side_encryption_by_default = [{
          kms_master_key_id = "${var.kms_arn}"
          sse_algorithm     = "aws:kms"
        }]
      }]
    }]
    disabled = "${list()}"
  }
}

resource "aws_s3_bucket" "this" {
  bucket        = "foo"
  force_destroy = false
  acl           = "private"
  server_side_encryption_configuration = "${local.encryption_config["${var.encrypted_bucket ? "enabled" : "disabled"}"]}"
}
```

module/s3/var.tf
```
variable "name" {}

variable "kms_arn" {
  default     = "aws/s3"
}
```

a.tf # DOESNT WORKS
```
module "s3_crawler" {
  source           = "module/s3"
  name             = "foo"
  encrypted_bucket = true
  kms_arn          = "${module.kms_crawler.arn}"
}
```

b.tf #WORKS
```
module "s3_crawler" {
  source           = "module/s3"
  name             = "foo"
  encrypted_bucket = true
}
```

c.tf #WORKS
```
module "s3_crawler" {
  source           = "module/s3"
  name             = "foo"
  encrypted_bucket = true
  kms_arn          = "arn:aws:kms:us-east-1:111111111:key/smskmsakkmkds"
}
```

**Comment by jbardin** [comment] 2018-05-17 15:26
Hi @oba11,

That happens to be a different issue. What you're doing is attempting to emulate a configuration block by using a list of maps. While this currently works sometimes due to some implementation details in the current config handlers, it's not intended to work, nor will it work in future versions.

**Comment by oba11** [comment] 2018-05-17 17:14
@jbardin but interestingly works if the value of the variable is not from the output of a  module which is the same thing as the original issue.

**Comment by gvilarino** [comment] 2018-05-31 14:49
Hi, same problem here. Any ETA on this? It's really a tough issue to identify, specially for newcomers like me 😅

**Comment by AvinashReddyVaka** [comment] 2018-08-29 12:33
Hi Guys,

Any update on this issue? I am getting the same error message as "should be a list" when passing module output in a list. Any help/suggestion is highly appreciated.

**Comment by hblanks** [comment] 2018-10-23 12:55
@mitchellh - this issue's been hanging around for a while now. Maybe this could make it into the roadmap?

**Comment by apparentlymart** [comment] 2018-10-30 01:10
Hi all! Sorry for the long silence here.

This issue has the same root cause as #12263, which has now been fixed in master ready for inclusion in the forthcoming v0.12.0 release. Thanks for reporting it, and thanks for your patience while we figured out what was going on.

**Closed by apparentlymart** 2018-10-30 01:10 UTC
Labels: bug, config

**Comment by AvinashReddyVaka** [comment] 2018-11-02 14:03
Can someone let me know the release date for v0.12 version
