### ISSUE TITLE
local-exec cannot run Azure AD powershell module.It throws an error module found but could not be loaded.

### ISSUE THREAD

**Issue by santhoshpcv** [hashicorp/terraform#31477] opened 2022-07-20 11:31 UTC
### Terraform Version

![image](https://user-images.githubusercontent.com/66933280/179971194-ff4cacbe-e4aa-4a4f-afeb-f2f97edf24fd.png)

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by santhoshpcv** [comment] 2022-07-20 14:10
Thanks for replying. I am just trying to create Azure AD APP Proxy as TF resource block is not available using Powershell.

Scenario: 
resource "null_resource" "PowerShellScriptRunFirstTimeOnly" {
    
    provisioner "local-exec" {
        command = "script.ps1"
        interpreter = ["PowerShell", "-File"]    
    }
}

**Powerhsell script will be in same folder and variables are hardcoded just keep it simple.  Script is as follows**

```

$username = "******i@sanswitzerlandoutlook.onmicrosoft.com"
 $password="*********"

$SecurePassword = ConvertTo-SecureString “$password” -AsPlainText -Force

$credentials = New-Object System.Management.Automation.PSCredential($username, $SecurePassword)

Connect-AzureAD -Credential $credentials

New-AzureADApplicationProxyApplication -DisplayName "swisscentralbank" -ExternalUrl "https://hayabusa-sanswitzerlandoutlook.msappproxy.net/" -InternalUrl "http://haya05/"
```

**Comment by santhoshpcv** [comment] 2022-07-22 13:16
Do we have any update on this request? At least an ACK .

**Comment by crw** [comment] 2022-07-27 22:15
Hello @santhoshpcv. I can confirm that we have seen your response. Have you tried asking this question in the [Community Forums](https://discuss.hashicorp.com/c/terraform-core), as suggested above?

You may experience a delayed response on issues with provisioners. Issues with provisioners are not receiving a high priority, as documented in our [Contributing Guide](https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md#provisioners):

> The Terraform team is in the process of building a way forward which continues to decrease reliance on provisioners. In the meantime however, as our documentation indicates, they are a tool of last resort. As such expect that PRs and issues for provisioners are not high in priority.

Looking at the comment thread, it seems we are still waiting for "a complete, reproducible example we can copy to determine the cause." In general, the more information you can put into the originating issue template, the more likely your issue is to receive a prompt response (keeping in mind the information shared regarding the prioritization of provisioners issues).

**Comment by crw** [comment] 2024-07-01 18:26
Going to close this issue due to lack of reproduction case posted. Please let us know if you have such a case and we can reopen. Thanks!

**Closed by crw** 2024-07-01 18:26 UTC
Labels: bug, windows, powershell, waiting for reproduction
