### ISSUE TITLE
Cannot yamldecode cloudformation yaml template but yq tool can

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform#26962] opened 2020-11-18 16:26 UTC
### Terraform Version

```
✗ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/http v2.0.0
```

### Terraform Configuration Files

```terraform
data "http" "stack" {
  url = "https://s3.amazonaws.com/buildkite-aws-stack/v5.0.0/aws-stack.yml"

  request_headers = {
    Accept = "application/yaml"
  }
}

locals {
  stack_body_map = yamldecode(data.http.stack.body)
}
```

### Debug Output

```
Call to function "yamldecode" failed: on line 386, column 7: can't interpret
sequence as !If.
```

on this

```
      !If [ CreateVpcResources, !Ref Vpc, !Ref VpcId ]
```

### Expected Behavior
It should have decoded the yaml correctly

### Actual Behavior
It failed. See error above.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

The idea is to use an existing cloudformation template, convert it to an object, perform transformations, decode it back into yaml, and supply it to the `aws_cloudformation_stack` resource. This allows us to not leave terraform to do the transformations and still allow us to use an upstream stack without having to maintain a forked version of it.

The `yamldecode` error is due to using the cloudformation `!If` directive. As a hack, we can try replacing the `!` symbol, doing transformations, and then replacing the replacement with the `!` symbol again.

```hcl
locals {
  replacement = "WHATEVA_I_DO_WHAT_I_WANT"
  stack_wo_exclamation = replace(data.http.stack.body, "!", local.replacement)
  stack_body_map_wo_exclamation = yamldecode(local.stack_wo_exclamation)
  # ... transformations like merge, etc
  stack_body_map_w_exclamation = replace(local.stack_wo_exclamation, local.replacement, "!")
}
```

However, there are other issues it has as well.

```
Call to function "yamldecode" failed: on line 472, column 1: mapping values
are not allowed in this context.
```

on this mapping

```
        - { Condition : CreateSecurityGroup }
```

A workaround for now, is to simply use the `replace()` function directly on the string `data.http.stack.body` and feed this into `aws_cloudformation_stack`'s `template_body` argument.

### References

The [`yq`](https://github.com/mikefarah/yq) command seems to be able to parse the cloudformation yaml correctly.

```bash
$ wget https://s3.amazonaws.com/buildkite-aws-stack/v5.0.0/aws-stack.yml
$ yq r aws-stack.yml | wc -l
999
$ echo $?
0
```

**Comment by apparentlymart** [comment] 2020-11-20 01:37
Hi @nitrocode!

The `!If` sequence, and other similar sequences starting with a single `!`, are in YAML specification terms "application-specific local tags", and so their meaning is specific to whatever application is parsing them. CloudFormation defines a particular meaning for `!If`, `!Ref`, `!Sub`, etc but those are meaningful only in the context of CloudFormation.

Terraform's `yamldecode` is a generic YAML parser that therefore supports only the standard YAML tags described in [the `yamldecode` documentation](https://www.terraform.io/docs/configuration/functions/yamldecode.html), mapping each one to a corresponding Terraform language type.

With that said then, unfortunately the behavior you've seen here is Terraform behaving as intended: Terraform isn't aware of these CloudFormation-specific YAML extensions, and so it returns an error.

From some experimentation with `yq` it seems that _it_ is handling these unsupported tags by just stripping them out altogether, pretending that they aren't present at all. That allows the parsing operation to succeed, but it also changes the meaning of the input such that subsequently using it with CloudFormation would produce a different result.

For example, I see the following fragment in the YAML file you linked to:

```yaml
Outputs:
  VpcId:
    Value:
      !If [ CreateVpcResources, !Ref Vpc, !Ref VpcId ]
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
```

After passing through `yq` the special tags are entirely lost, causing the `Value` to be a plain list of strings rather than a conditional selection between two possible references:

```yaml
Outputs:
  VpcId:
    Value:
      - CreateVpcResources
      - Vpc
      - VpcId
    Export:
      Name: ${AWS::StackName}-VpcId
```

For that reason, I think Terraform's behavior is better, at least for Terraform's use-cases: it is clear about the fact that it isn't able to understand the CloudFormation-specific extensions, rather than silently corrupting the data as `yq` does.

I think in order to meet your original goal here would require first processing the YAML input with a parser that is aware of the CloudFormation-specific YAML extensions, perhaps converting the result to the equivalent JSON form using a JSON object like `{"Fn::If": [...]}`, and then load _that_ into Terraform using `jsondecode` before passing the result to `aws_cloudformation_stack` with `jsonencode` (rather than `yamlencode`).

With a little research I found [`yaml-cfn`](https://github.com/gristlabs/yaml-cfn) which seems to implement such a conversion, but it's a NodeJS library and so not super convenient to use inside Terraform. The core Terraform language is not an appropriate place to implement a Terraform equivalent of that, because CloudFormation YAML is an AWS-specific language, but _in principle_ [the AWS provider](https://github.com/hashicorp/terraform-provider-aws) could offer a data source for doing such a conversion, perhaps by porting that NodeJS library to Go. I can't say whether the AWS provider team would have an appetite for implementing/maintaining such a thing, but you could perhaps open an issue in the provider's own repository if you want to discuss the possibility with them.

Given all of this, I'm going to close this issue. I understand your use case, but the behavior you need is too specific to CloudFormation to be implemented in the vendor-agnostic Terraform language. Thanks for raising this, and sorry the answer couldn't be more straightforward.

**Closed by apparentlymart** 2020-11-20 01:37 UTC
Labels: bug, new

**Comment by nitrocode** [comment] 2020-11-20 16:48
Thank you for the quick comment!

That's interesting. I don't see the same result from the excerpt above and I'm using the latest version of yq.

```
✗ cat check.yml
Outputs:
  VpcId:
    Value:
      !If [ CreateVpcResources, !Ref Vpc, !Ref VpcId ]
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
✗ yq r check.yml
Outputs:
  VpcId:
    Value: !If [CreateVpcResources, !Ref Vpc, !Ref VpcId]
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
✗ yq --version
yq version 3.4.1
```

Regardless, I see your point. Perhaps we can do our transformations outside of terraform and then feed in the transformed template into terraform.
