### ISSUE TITLE
terraform_remote_state not working on windows

### ISSUE THREAD

**Issue by Ehekatl** [hashicorp/terraform#8832] opened 2016-09-14 04:05 UTC
Hi there,

Using terraform remote state on windows does not refresh state with remote state, however running in linux doesn't have this problem

My OS version is windows 10 annual update
### Terraform Version

0.7.3
### Affected Resource(s)
- terraform_remote_state
### Terraform Configuration Files

``` hcl
data "terraform_remote_state" "vpc" {
    backend = "s3"
    config {
        bucket = "strikingly-terraform-state"
        key = "aws-jp-auxiliary/terraform.tfstate"
        region = "${var.region}"
        profile = "${var.profile}"
    }
}
```
### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
### Expected Behavior

```
Refreshing Terraform state in-memory prior to plan...

The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.terraform_remote_state.vpc: Refreshing state...
....
....
refreshing resource states
Plan: 0 to add, 0 to change, 0 to destroy.
```
### Actual Behavior

```
Refreshing Terraform state in-memory prior to plan...

The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.terraform_remote_state.vpc: Refreshing state...
...
...
a lot of new resources creating
Plan: 33 to add, 0 to change, 0 to destroy.
```
### Steps to Reproduce
1. `terraform plan`

**Comment by chrisrlong** [comment] 2016-09-14 10:29
This sounds similar to what i saw:
aws_db_parameter_group parameter binlog_format not in state file #8818

**Comment by morkot** [comment] 2016-11-26 22:16
It maybe the issue with s3 as back-end, or it is already fixed in next terraform versions. I have no issues with remote state using terraform v0.7.10 on Windows 10 and Artifactory as a back-end.

**Comment by apparentlymart** [comment] 2017-05-03 00:55
Hi @Ehekatl! Sorry for the long silence here.

Are you still seeing this bug on Terraform 0.9? Things have changed quite a bit in this area of Terraform since 0.7.3.

**Comment by apparentlymart** [comment] 2017-05-08 22:19
Given the latest comment here saying that this wasn't reproducible on Terraform 0.7.10, and given that the relevant areas of Terraform were drastically reworked in Terraform 0.9, I'm going to close this.

If anyone is still having problems of this nature in Terraform 0.9 or above, please open a new issue describing it since I expect the details of the problem will be different than this one.

Thanks for reporting this!

**Closed by apparentlymart** 2017-05-08 22:19 UTC
Labels: bug, core, waiting-response, windows
