### ISSUE TITLE
Errors in plan

### ISSUE THREAD

**Issue by chrisrlong** [hashicorp/terraform#10530] opened 2016-12-05 13:36 UTC
Hi there,

### Terraform Version
Terraform v0.8.0-dev (c2041b74882a72fc09657a155ce2c5b70c62522a) Linux amd64/Windows amd64

### Affected Resource(s)
- null_resource
- aws_elb_attachment
- aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_elb_attachment" "mod" {
  count = "${var.instance_count}"
  elb = "${aws_elb.mod.id}"
  instance = "${element(aws_instance.mod.*.id, count.index)}"
  lifecycle {
    create_before_destroy = true
  }
  depends_on = [
    "aws_elb.mod",
    "null_resource.deploy_app",
    "aws_instance.mod"
  ]
}
```

```resource "aws_route53_record" "lb" {
resource "aws_route53_record" "instance" {
  count = "${var.instance_count}"
  zone_id = "${data.terraform_remote_state.vpc.private_zone_id}"
  name = "${var.name}-${format("%02d", count.index + 1)}.${var.vpc}.${var.environment}.foo"
  type = "A"
  ttl = "300"
  records = ["${element(aws_instance.mod.*.private_ip, count.index)}"]
}
```

```
resource "aws_instance" "mod" {
  count = "${var.instance_count}"
  availability_zone = "${var.region}${element(split(",", var.azs), count.index)}"
  ami = "${var.ec2_ami}"
  instance_type = "${var.ec2_instance_type}"
  key_name = "foo"
  iam_instance_profile = "${data.terraform_remote_state.vpc.foo_role_id}"
  subnet_id = "${element(split(",", data.terraform_remote_state.vpc.private_subnets), count.index)}"
  vpc_security_group_ids = [
   ....
  ]
  root_block_device {
    volume_size = "${var.ec2_instance_ebs_size}"
    volume_type = "gp2"
  }
  lifecycle {
    create_before_destroy = true
  }
  connection {
   ...
  }
  provisioner "remote-exec" {
    ....
  }
  provisioner "chef" {
    ...
  }
  tags {
    ...
  }
}
```

```
resource "null_resource" "deploy_app" {
  count = "${var.instance_count}"
  triggers {
    current_ec2_instance_id = "${element(aws_instance.mod.*.id, count.index)}"
  }
  provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "user"
      host = "server.name"
      timeout = "10s"
      agent = true
    }
    inline = [
    ....
    ]
  }
  lifecycle {
    create_before_destroy = true
  }
  depends_on = [
    "aws_instance.mod",
    "aws_route53_record.instance",
  ]
}
```

### Expected Behavior
The **mod.0** resources in the below output should not be in the plan for replacement only mod.1 was tainted.

The mod.0 load-balancer attachment resource was destroyed on an apply, requiring a 2nd apply to be run to recreate it:

```
+ module.marketing_site.aws_elb_attachment.mod.0
    elb:      "marketing-site"
    instance: "i-09932d98f0c85045e"
```

### Actual Behavior

-/+ module.marketing_site.aws_elb_attachment.**mod.0**
    elb:      "marketing-site" => "marketing-site"
    instance: "i-foo" => "<computed>" (forces new resource)

-/+ module.marketing_site.aws_elb_attachment.mod.1
    elb:      "marketing-site" => "marketing-site"
    instance: "i-bar" => "<computed>" (forces new resource)

-/+ module.marketing_site.aws_instance.**mod.1 (tainted)**
    ami:                                       "ami-ff0e758c" => "ami-ff0e758c"
    associate_public_ip_address:               "false" => "<computed>"
    availability_zone:                         "eu-west-1b" => "eu-west-1b"
    ebs_block_device.#:                        "0" => "<computed>"
    ephemeral_block_device.#:                  "0" => "<computed>"
    iam_instance_profile:                      "foo_role" => "foo_role"
    instance_state:                            "running" => "<computed>"
    instance_type:                             "t2.micro" => "t2.micro"
    ...

~ module.marketing_site.aws_route53_record.**instance.0**
    records.#: "" => "<computed>"

~ module.marketing_site.aws_route53_record.instance.1
    records.#: "" => "<computed>"

-/+ module.marketing_site.null_resource.d**eploy_app.0**
    triggers.%:                       "1" => "<computed>" (forces new resource)
    triggers.current_ec2_instance_id: "i-foo" => "" (forces new resource)

-/+ module.marketing_site.null_resource.deploy_app.1
    triggers.%:                       "1" => "<computed>" (forces new resource)
    triggers.current_ec2_instance_id: "i-bar" => "" (forces new resource)

Plan: 5 to add, 2 to change, 5 to destroy.

### Steps to Reproduce
terraform plan

**Comment by jbardin** [comment] 2016-12-07 21:00
Updating with some details, and a standalone reproduction. This is a manifestation of #3449, but I'm going to leave this open for a bit to see if I can some up with a solution for the specific create-before-destroy case shown below. 

This repro is still going to use the aws provider, because it turns out that this bug is specific to resources like `aws_elb_attachment`, where creating is idempotent. 

After applying the config below, if we taint `aws_instance.mod.1` and apply again, the `aws_elb_attachment.mod.0` resource will be missing, requiring another `terraform apply` to restore. What happens is:

- All `aws_elb_attachment` resources are marked for destruction, because they depend on all `aws_instance.mod.*` resources due to the usage of the `*` operator. 
- Because `aws_instance.mod` is marked `create_before_destroy`, all the `aws_elb_attament.mod` resources will be too.
- When the new `aws_elb_attachment.mod.0` is created, nothing happens because `aws_instance.mod.0` isn't changing. 
- Because the new `aws_elb_attachment.mod.0` and the deposed one are pointing to the same resource in aws, when the destroy happens, the only `aws_elb_attachment.mod.0` in aws is destroyed.


```
resource "aws_elb_attachment" "mod" {
  count    = "${var.instance_count}"
  elb      = "${aws_elb.mod.id}"
  instance = "${element(aws_instance.mod.*.id, count.index)}"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_instance" "mod" {
  count                  = "${var.instance_count}"
  availability_zone      = "${var.availability_zone}"
  ami                    = "${var.ec2_ami}"
  instance_type          = "${var.ec2_instance_type}"
  key_name               = "${var.aws_key}"
  subnet_id              = "${var.subnet}"
  vpc_security_group_ids = ["${var.security_group}"]

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_elb" "mod" {
  name = "foobar-terraform-elb"

  security_groups = [
    "${var.security_group}",
  ]

  subnets = ["${var.subnet}"]

  listener {
    instance_port     = 8000
    instance_protocol = "http"
    lb_port           = 80
    lb_protocol       = "http"
  }
}

variable "availability_zone" {}

variable "security_group" {}

variable "subnet" {}

variable "ec2_ami" {}

variable "aws_key" {}

variable "ec2_instance_type" {
  default = "t2.micro"
}

variable "instance_count" {
  default = 2
}
```

**Comment by jbardin** [comment] 2016-12-08 19:22
As we suspected, I don't see any good way to patch this up as a separate issue. I'm going to close this as a dupe of #3449.

**Closed by jbardin** 2016-12-08 19:22 UTC
Labels: bug, core
