### ISSUE TITLE
terraform registry stuck publishing module

### ISSUE THREAD

**Issue by mehulsharma2010** [hashicorp/terraform#30691] opened 2022-03-17 10:28 UTC
Hi, 

While trying to publish my module, It got stuck in publishing state, And when I am trying to republish it then it is showing already published.

I can see error in inspect mode but not able to take any action, could you please check.

Module: https://registry.terraform.io/modules/OT-terraform-azure-modules/sql-complete-module/azure

**Comment by mehulsharma2010** [comment] 2022-03-17 16:53
Stuck with Another one now :(
Link: https://registry.terraform.io/modules/OT-terraform-azure-modules/sql-db/azure

**Comment by mehulsharma2010** [comment] 2022-03-22 12:20
Hi, Is there any update on this ?

**Comment by mehulsharma2010** [comment] 2022-03-22 17:01
Got the same issue for another module now.
Link: https://registry.terraform.io/modules/OT-terraform-azure-modules/public-ip/azure?pollNotifications=true

**Comment by crw** [comment] 2022-03-24 22:28
I am checking in with the Registry team, I will let you know if there is an update.

**Comment by dsfrederic** [comment] 2022-03-28 11:26
Same issue here! 

+ the latest versions are not displaying in already published modules.

**Comment by dsfrederic** [comment] 2022-03-29 06:51
This module does not publish the latest versions.
![image](https://user-images.githubusercontent.com/28486949/160550494-58563f3f-1937-48d6-95c3-868622786d87.png)

This module is stuck on the publishing page. 
![image](https://user-images.githubusercontent.com/28486949/160550802-d4d1ae93-f937-44dc-a574-2ead722aa181.png)

Normally these repos should meet the requirements

@crw any idea about ETA. For us this is quite critical!

**Comment by crw** [comment] 2022-03-29 23:51
@dsfrederic Thanks for the additional information. No ETA but I will keep checking in daily with the Registry team on this issue.

**Comment by dsfrederic** [comment] 2022-03-31 11:37
@crw could it be that these repos do not fulfill the requiremeents?

**Comment by dsfrederic** [comment] 2022-03-31 12:14
Things I've tried without success: 
- Recreating the module 
- Recreating the repository 
- Moving ownership of the repo
- Publishing an empty TF module

**Comment by mehulsharma2010** [comment] 2022-03-31 12:39
HI @dsfrederic, Mine issue got fixed when after removing extra spaces and pushed the different version, And I have also observed that I am not able to publish modules with v0.0.1 tag but when I choose any other tag without changing anything then I publishes then but I am still not sure why this is happening.

Feedback for Registry team is if we can add some correct error messages while we throw the error as it is very difficult to guess every time :)

**Comment by crw** [comment] 2022-03-31 22:54
The Registry team is actively working on this issue, no ETA for a fix at the moment. I've shared the work-around in https://github.com/hashicorp/terraform/issues/30691#issuecomment-1084526381 with the team.

**Comment by robertolopezlopez** [comment] 2022-04-01 12:30
Same problem here

![image](https://user-images.githubusercontent.com/1519467/161263242-e42e222c-da72-4939-9fdf-fef319f86e22.png)
![image](https://user-images.githubusercontent.com/1519467/161263339-9b1b7c5a-81b1-4161-8763-40e5e3436e0e.png)
![image](https://user-images.githubusercontent.com/1519467/161263410-7e6bbd0e-343b-430d-bd0a-24d5ba72ddda.png)

Our last two releases from yesterday and today have not been published in the terraform registry.

**Comment by robertolopezlopez** [comment] 2022-04-06 09:24
> Same problem here
> 
> ![image](https://user-images.githubusercontent.com/1519467/161263242-e42e222c-da72-4939-9fdf-fef319f86e22.png) ![image](https://user-images.githubusercontent.com/1519467/161263339-9b1b7c5a-81b1-4161-8763-40e5e3436e0e.png) ![image](https://user-images.githubusercontent.com/1519467/161263410-7e6bbd0e-343b-430d-bd0a-24d5ba72ddda.png)
> 
> Our last two releases from yesterday and today have not been published in the terraform registry.

This is not an issue any more. We found out that our checksum file was not 100% correct.

**Comment by crw** [comment] 2022-04-12 18:22
So to be clear, @robertolopezlopez' issue seems to be different from the issue reported by @mehulsharma2010 and @dsfrederic, and is resolved.

@dsfrederic @mehulsharma2010 is it confirmed that the work-around of bumping the tag version worked for you? 

@mehulsharma2010 I asked for an update on your issues and both of those repositories are giving us 404s on Github:
https://github.com/cgk-ds-be/terraform-azurerm-keyvault/tags
https://github.com/cgk-ds-be/terraform-azurerm-datafactory/tags

I believe these were working a week ago, so not sure if this is a Github issue or if the repos have been made private.

And previously the repository attached to this module was set to private:
https://registry.terraform.io/modules/OT-terraform-azure-modules/sql-complete-module/azure

**Comment by mehulsharma2010** [comment] 2022-04-13 10:07
Hi @crw , Yes, Work around is working for me as of now, But not sure whenever I do it for first time It throws the error all the time but 2nd tag works.

Thanks.

**Comment by tlindsay42** [comment] 2022-04-19 14:52
Just ran into this for two new modules. Tried the workaround, but no such luck for me.

**Comment by tlindsay42** [comment] 2022-04-19 16:11
Never mind. Discovered that the publishing account has to have admin permissions to the repo at the time of publish.

**Comment by crw** [comment] 2022-05-20 21:05
This thread contains a number of discrete issues, some of which were fixed. I am going to close this particular issue thread. Although the registry team does not check this repo for issues, please feel free to open follow-up issues if you are still encountering issues publishing modules. You can also open a thread on [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) if you are not sure if the behavior is an issue or a misconfiguration. Thanks for your contributions in this thread!

**Closed by crw** 2022-05-20 21:05 UTC
Labels: bug, registry
