### ISSUE TITLE
terraform plan doesn't produce diff if ReadContext emits Warnings

### ISSUE THREAD

**Issue by sharebear** [hashicorp/terraform#27419] opened 2020-12-07 21:28 UTC
### SDK version

```
v2.3.0
```

### Relevant provider source code

```go
func resourceChannelTestingRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	// Read API DATA into `current`

	diags = append(diags, diag.Diagnostic{
		Severity: diag.Warning,
		Summary: "Debug dumping",
		Detail: fmt.Sprintf("%+v", current),
	})

	// Set some properties

	return diags
}

```

### Terraform Configuration Files

```hcl
resource "fpp_channel_testing" "main" {
    enabled = false
    mode = "foo"
}
```

### Expected Behavior

Diff such as the following should be produced.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
2020/12/07 22:05:03 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
  ~ update in-place

2020/12/07 22:05:03 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
Terraform will perform the following actions:

  # fpp_channel_testing.main will be updated in-place
  ~ resource "fpp_channel_testing" "main" {
      ~ enabled = true -> false
        id      = "static"
      ~ mode    = "RGBChase" -> "foo"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

Warning was produced but no diff identified.

```
2020/12/07 22:04:31 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
No changes. Infrastructure is up-to-date.

2020/12/07 22:04:31 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: Debug dumping

{Mode:RGBChase SubMode:RGBChase-RGB CycleMS:1000
ColorPattern:FF000000FF000000FF Color1:<nil> Color2:<nil> Color3:<nil>
Enabled:1 ChannelSet:1-8 ChannelSetType:channelRange}

```

### Steps to Reproduce

1. Create a resource where the ReadContext implementation produces a warning
2. `terraform plan`

### Discussion

This _might_ be intentional behaviour, if it is it should be clearly documented somewhere and I don't see it. The issue from my point of view is that if the ReadContext implementation produces a Warning (something I consider non-fatal) then no diff is identified even if there were changes. The output from plan clearly states "Terraform did not detect any differences between your
configuration and real physical resources that exist" when there were changes identified, it feels wrong to hide this information just because there was a warning.

**Comment by jbardin** [comment] 2021-01-07 18:12
Closing since this is confirmed as fixed in master.

Thanks!

**Closed by jbardin** 2021-01-07 18:12 UTC
