### ISSUE TITLE
aws_efs_file_system moving from reference_name to creation_token results in new resource being created.

### ISSUE THREAD

**Issue by ste-bah** [hashicorp/terraform#9231] opened 2016-10-05 12:34 UTC
I'm not sure if this behaviour is expected or is an unforseen consequence. 

### Terraform Version
Terraform v0.7.4

### Affected Resource(s)
- aws_efs_file_system

### Terraform Configuration Files

original:
```
resource "aws_efs_file_system" "aws-efs" {
  reference_name = "${var.environment}.efs"
  tags {
    Name = "${var.environment}-efs"
    env  = "dev"
  }
}
```
changed:

```
resource "aws_efs_file_system" "aws-efs" {
  creation_token = "${var.environment}.efs"
  tags {
    Name = "${var.environment}-mantl-efs"
    env  = "dev"
  }
}
```

### Expected Behavior
I am assuming this change should be no destructive?

### Actual Behavior
Terraform wishes to create a new resource by destroying the old resource. 

### Steps to Reproduce

`terraform apply`

### Important Factoids
Is it feesible to manually edit the tfstate file and edit  reference_name and replace with creation token following to avoid destroying the current efs which has quite a lot of data:

```
            "resources": {
                "aws_efs_file_system.aws-efs": {
                    "type": "aws_efs_file_system",
                    "depends_on": [],
                    "primary": {
                        "id": "fs-00000000",
                        "attributes": {
                            "id": "fs-00000000",
                            "reference_name": "example.efs",
                            "tags.%": "2",
                            "tags.Name": "example-efs",
                            "tags.env": "testing"
```

**Comment by catsby** [comment] 2016-10-05 16:41
Follow up – I don't think my steps above actually work, sadly, because the `creation_token` isn't read into the state file until #9234. You can manually add an entry to the statefile just below `reference_name` as you've shown your statefile above, adding the `creation_token`, **however** I generally discourage modifying the statefile directly. If possible please wait for the patch to get merged and a new release. `reference_name` can continue to be used safely.

Sorry again for the troubles :/

**Closed** 2016-10-05 18:48 UTC
Labels: provider/aws

**Comment by donnoman** [comment] 2017-01-04 01:50
this just bit me

```
-/+ module.site.aws_efs_file_system.default
    creation_token:   "lh-wordpress-production-terraform-d4pgaokthre7zbrnoi5pi3ao7u" => "lh-wordpress-production" (forces new resource)
    performance_mode: "generalPurpose" => "<computed>"
    reference_name:   "lh-wordpress-production" => "<computed>"
    tags.%:           "3" => "3"
    tags.Name:        "lh-wordpress-production" => "lh-wordpress-production"
    tags.cluster:     "lh-wordpress-production" => "lh-wordpress-production"
    tags.terraform:   "true" => "true"

````

I don't want to lose the volume, just because you guys want to deprecate a variable name.

creation_token != reference_name

this is the snippet responsible for creating it, and it is dynamic based on which stage I'm building

```resource "aws_efs_file_system" "default" {
  reference_name = "lh-wordpress-${var.stage}"
  tags {
    Name = "lh-wordpress-${var.stage}"
    cluster = "lh-wordpress-${var.stage}"
    terraform = "true"
  }
}```

inserting a static creation_token instead of reference_name doesn't work for me.

**Comment by attenda-johnmcmillan** [comment] 2018-11-27 16:30
I'm facing the same issue as @donnoman described.
Maybe my git/google-fu is off - but I can't find a more recent update explaining how to get past what I'm about to describe:

My code was previously... 

`resource "aws_efs_file_system" "file_system" {
  reference_name="${var.name}"
  tags {
    Name = "${var.name}"
    Description = "${var.name} EFS File System"
  }
}
`

Now it's...
`resource "aws_efs_file_system" "file_system" {
  creation_token="${var.name}"
  tags {
    Name = "${var.name}"
    Description = "${var.name} EFS File System"
  }
}
`

i.e. I directly replaced reference_name with creation_token and that was the only change. 
However, judging by the detail in the statefile - terraform has auto calculated creation_token previously. 
So now, it wants to destroy and recreate the resource:

> creation_token: "MyEFSName-terraform-5jnvgaw5pvb7halc3bflussvie" => "MyEFSName" (forces new resource)

This would appear to contradict what's documented at 
https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#resource-aws_efs_file_system

... so is this unexpected behaviour a bug, or is the documentation out of date... or am I missing something?

I'm using terraform 0.11.8
