### ISSUE TITLE
Version 0.0.7 accepts command if the first characters of the string matches with the command

### ISSUE THREAD

**Issue by lucasvasconcelos** [hashicorp/terraform#8017] opened 2016-08-05 20:26 UTC
Hi,

I've found an issue with the 0.0.7 version:
If you run a command passing as argument a string that the first characters matches the command name, terraform will accept it:

```
 $ terraform version
Terraform v0.7.0

 $ terraform planXXXXXX
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.terraform_remote_state.elasticache-subnet-groups: Refreshing state...

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
 ~/dev/automation/terraform/teste (BTW-23)$
```

This behavior does not happen on version 0.6.x:

```
 ~ $ terraform --version
Terraform v0.6.16

Your version of Terraform is out of date! The latest version
is 0.7.0. You can update by downloading from www.terraform.io
 ~ $ terraform plan
Error loading config: No Terraform configuration files found in directory: /Users/Developer
 ~ $ terraform plansdfsdf
usage: terraform [--version] [--help] <command> [<args>]

Available commands are:
    apply       Builds or changes infrastructure
    destroy     Destroy Terraform-managed infrastructure
    fmt         Rewrites config files to canonical format
    get         Download and install modules for the configuration
    graph       Create a visual graph of Terraform resources
    init        Initializes Terraform configuration from a module
    output      Read an output from a state file
    plan        Generate and show an execution plan
    push        Upload this Terraform module to Atlas to run
    refresh     Update local state file against real resources
    remote      Configure remote state storage
    show        Inspect Terraform state or plan
    taint       Manually mark a resource for recreation
    untaint     Manually unmark a resource as tainted
    validate    Validates the Terraform files
    version     Prints the Terraform version

 ~ $
```

PS: Tested only on OSX.

**Comment by kwilczynski** [comment] 2016-08-05 22:22
Duplicate of #7983.

**Comment by stack72** [comment] 2016-08-07 23:43
Hi @lucasvasconcelos 

Thanks for opening the issue here. As @kwilczynski points out, this is a duplicate of #7983 

I am going to close this one and then we can track the issue in #7983 

This just means we have 1 area of information to update

thanks again

Paul

**Closed by stack72** 2016-08-07 23:43 UTC
Labels: bug, core
