### ISSUE TITLE
anytrue() crash

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform#27136] opened 2020-12-04 09:12 UTC
### Terraform Version

```
Terraform v0.14.0
```

### Terraform Configuration Files

```terraform
      for file in fileset(var.build_options.base_dir, "**"):
        filemd5("${var.build_options.base_dir}/${file}")
      if trimprefix(abspath("${var.build_options.base_dir}/${file}"), abspath(local.source_path)) == abspath("${var.build_options.base_dir}/${file}") && !anytrue([
        for ignore_dir in local.ignore_dirs:
          trimprefix(abspath("${var.build_options.base_dir}/${file}"), ignore_dir) != abspath("${var.build_options.base_dir}/${file}")
      ])
```

### Crash Output
```
Call to function "anytrue" failed: panic in function implementation: interface
conversion: interface {} is *cty.unknownType, not bool
goroutine 1046 [running]:
runtime/debug.Stack(0xc0022e1d98, 0x248e480, 0xc002272420)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/zclconf/go-cty/cty/function.errorForPanic(...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/error.go:44
github.com/zclconf/go-cty/cty/function.Function.Call.func1(0xc0022e22e0,
0xc0022e2300)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/function.go:291
+0x95
panic(0x248e480, 0xc002272420)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/zclconf/go-cty/cty.Value.True(0x2c4c5a0, 0xc000058451, 0x2421d80,
0x3d2f080, 0x2c4c5a0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/value_ops.go:364 +0x136
github.com/hashicorp/terraform/lang/funcs.glob..func8(0xc0031b72e0, 0x1, 0x1,
0x2c4c5a0, 0xc000058451, 0xc000d3fc20, 0x2325420, 0xc0031b7540, 0xc002272390,
0xc002272270, ...)
        /home/circleci/project/project/lang/funcs/collection.go:103 +0x259
github.com/zclconf/go-cty/cty/function.Function.Call(0xc00019a2d0,
0xc0031b72e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/function/function.go:295
+0x51a
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0003e70e0,
0xc0031b7200, 0x1, 0xc0000a7710, 0x1, 0x1, 0x0, 0x3d2f080, 0xc000058450)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:412
+0x10c5
github.com/hashicorp/hcl/v2/hclsyntax.(*UnaryOpExpr).Value(0xc000eff400,
0xc0031b7200, 0x2c4c5a0, 0xc000058451, 0x2421d80, 0x3d2f080, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression_ops.go:223
+0x111
github.com/hashicorp/hcl/v2/hclsyntax.(*BinaryOpExpr).Value(0xc0001ee770,
0xc0031b7200, 0xc000566f2c, 0x4, 0xc000cd3dc8, 0xc000d3faf0, 0x2744ea0,
0xc0031b71e0, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression_ops.go:145
+0x1ba
github.com/hashicorp/hcl/v2/hclsyntax.(*ForExpr).Value(0xc000dc5b80,
0xc002e881a0, 0x0, 0x3d314e0, 0x2c4c5a0, 0xc000058450, 0x2c4c5a0,
0xc000058450, 0x23702c0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:1008
+0x3679
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0003e71d0,
0xc002e881a0, 0x0, 0xc0031b70a0, 0x1, 0x1, 0x23702c0, 0xc002921830, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:378
+0x260c
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0003e72c0,
0xc002e881a0, 0x2c4c5a0, 0xc000058450, 0x23702c0, 0x3d314e0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:378
+0x260c
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc0001ee7e0,
0xc002e881a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:517
+0xcb
github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0xc000eff4a0,
0xc002e881a0, 0x0, 0xc001fad800, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:775
+0x27d
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0013068c0,
0x7fe40cfa8398, 0xc000eff4a0, 0x2c4c5e0, 0x3d2f518, 0x0, 0x0, 0x0, 0x0, 0x0,
...)
        /home/circleci/project/project/lang/eval.go:171 +0x1b7
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc000b36ea0,
0x7fe40cfa8398, 0xc000eff4a0, 0x2c4c5e0, 0x3d2f518, 0x0, 0x0, 0x0,
0xc0018ed380, 0xc000067000, ...)
        /home/circleci/project/project/terraform/eval_context_builtin.go:287 +0xbb
github.com/hashicorp/terraform/terraform.(*NodeLocal).Execute(0xc00253bbf0,
0x2c879e0, 0xc000b36ea0, 0xc003e00002, 0x249d600, 0x2623040)
        /home/circleci/project/project/terraform/node_local.go:156 +0x71d
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc0013e8410,
0x2c879e0, 0xc000b36ea0, 0x7fe40ce14a38, 0xc00253bbf0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2623040,
0xc00253bbf0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000f62060,
0x2623040, 0xc00253bbf0, 0xc000f09f00)
        /home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x1246
```

**Comment by danieldreier** [comment] 2020-12-10 16:49
Hi! Thanks for reporting this. This is clearly actually crashing, based on your output, and I think this is probably a valid issue, so I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, this isn't quite a full reproduction case - this shows part of it, but I don't have the relevant variables. I've spent a few minutes trying to construct a reproduction case around this, and haven't found the right set of input variables. What would be ideal from a troubleshooting perspective would be a case with minimal conditionals or variables, where you just have the minimal set of hardcoded strings to trigger this case.

Can you please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider, variable definitions, or outputs as the home for the expression rather than a real provider in order to minimize external dependencies.

**Comment by alisdair** [comment] 2020-12-11 15:40
This looks like a duplicate of #27236. Closing for now. @mgzenitech, if it's not a duplicate and you can provide a reproduction case, please respond and we can reopen.

**Closed by alisdair** 2020-12-11 15:40 UTC
Labels: bug, config, crash, v0.14, waiting for reproduction
