### ISSUE TITLE
aws_route_table resource updated on every plan although it does not change.

### ISSUE THREAD

**Issue by grebois** [hashicorp/terraform#14619] opened 2017-05-18 09:37 UTC
Hi there,

### Terraform Version
0.9.5

### Affected Resource(s)
- aws_route_table

### Terraform Configuration Files
```hcl
#######################################################################
# Default VPC for the account with the new CIRDs block 10.x.x.x.x
#######################################################################
resource aws_vpc default {
  cidr_block           = "10.${var.cidr_block}.0.0/16"
  instance_tenancy     = "default"
  enable_dns_hostnames = true

  lifecycle {
    create_before_destroy = true
  }
}

#######################################################################
# Default security group, for the moment fully open.
#######################################################################
resource "aws_default_security_group" "default" {
  vpc_id = "${aws_vpc.default.id}"

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = -1
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

#######################################################################
# aws_eip adaptor
#######################################################################
resource "aws_eip" "aws_eip" {}

#######################################################################
# Public Subnets & Internet gateway & Public routing table
#######################################################################
resource "aws_internet_gateway" "public" {
  vpc_id = "${aws_vpc.default.id}"

  tags {
    Name = "Public Gateway - Managed By Terraform"
  }
}

resource "aws_route_table" "public" {
  count  = "${var.environment == "prod1" ? 0 : 1 }"
  vpc_id = "${aws_vpc.default.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.public.id}"
  }

  route {
    cidr_block     = "10.1.0.0/16"
    nat_gateway_id = "${aws_vpc_peering_connection.peer.id}"
  }

  tags {
    Name = "Public Route Table - Managed By Terraform"
  }
}

resource "aws_route_table" "public-prod1" {
  count  = "${var.environment == "prod1" ? 1 : 0 }"
  vpc_id = "${aws_vpc.default.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.public.id}"
  }

  tags {
    Name = "Public Route Table - Managed By Terraform"
  }
}

resource "aws_subnet" "public_a" {
  vpc_id                  = "${aws_vpc.default.id}"
  cidr_block              = "10.${var.cidr_block}.0.0/20"
  availability_zone       = "${var.region}a"
  map_public_ip_on_launch = true

  tags {
    Name = "Public Subnet - Managed By Terraform"
  }
}

resource "aws_route_table_association" "public_a" {
  count          = "${var.environment == "prod1" ? 0 : 1 }"
  subnet_id      = "${aws_subnet.public_a.id}"
  route_table_id = "${aws_route_table.public.id}"
}

resource "aws_route_table_association" "public_a-prod1" {
  count          = "${var.environment == "prod1" ? 1 : 0 }"
  subnet_id      = "${aws_subnet.public_a.id}"
  route_table_id = "${aws_route_table.public-prod1.id}"
}

resource "aws_subnet" "public_b" {
  vpc_id                  = "${aws_vpc.default.id}"
  cidr_block              = "10.${var.cidr_block}.16.0/20"
  availability_zone       = "${var.region}b"
  map_public_ip_on_launch = true

  tags {
    Name = "Public Subnet - Managed By Terraform"
  }
}

resource "aws_route_table_association" "public_b" {
  count          = "${var.environment == "prod1" ? 0 : 1 }"
  subnet_id      = "${aws_subnet.public_b.id}"
  route_table_id = "${aws_route_table.public.id}"
}

resource "aws_route_table_association" "public_b-prod1" {
  count          = "${var.environment == "prod1" ? 1 : 0 }"
  subnet_id      = "${aws_subnet.public_b.id}"
  route_table_id = "${aws_route_table.public-prod1.id}"
}

#######################################################################
# Gateway & VPC Peering
#######################################################################
resource "aws_nat_gateway" "aws_nat_gateway" {
  allocation_id = "${aws_eip.aws_eip.id}"

  # Could be also allocated in another zone
  subnet_id = "${aws_subnet.private_a.id}"
}

resource "aws_route_table" "private" {
  count  = "${var.environment == "prod1" ? 0 : 1 }"
  vpc_id = "${aws_vpc.default.id}"

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = "${aws_nat_gateway.aws_nat_gateway.id}"
  }

  tags {
    Name = "Private - Managed By Terraform"
  }
}

resource "aws_vpc_peering_connection" "peer" {
  count         = "${var.environment == "prod1" ? 0 : 1 }"
  vpc_id        = "${aws_vpc.default.id}"
  peer_vpc_id   = "vpc-5de07f35"
  peer_owner_id = "${data.aws_caller_identity.peer.account_id}"
  auto_accept   = true

  requester {
    allow_remote_vpc_dns_resolution = true
  }

  tags {
    Side = "Requester"
    Name = "Managed By Terraform"
  }
}

resource "aws_vpc_peering_connection_accepter" "peer" {
  count                     = "${var.environment == "prod1" ? 0 : 1 }"
  provider                  = "aws.peer"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.peer.id}"
  auto_accept               = true

  accepter {
    allow_remote_vpc_dns_resolution = true
  }

  tags {
    Side = "Accepter"
    Name = "Managed By Terraform"
  }
}

#######################################################################
# Private Subnets
#######################################################################
resource "aws_subnet" "private_a" {
  vpc_id            = "${aws_vpc.default.id}"
  cidr_block        = "10.${var.cidr_block}.64.0/20"
  availability_zone = "${var.region}a"

  tags {
    Name = "Private Subnet - Managed By Terraform"
  }
}

resource "aws_route_table_association" "private_a" {
  count          = "${var.environment == "prod1" ? 0 : 1 }"
  subnet_id      = "${aws_subnet.private_a.id}"
  route_table_id = "${aws_route_table.private.id}"
}

resource "aws_subnet" "private_b" {
  vpc_id            = "${aws_vpc.default.id}"
  cidr_block        = "10.${var.cidr_block}.128.0/20"
  availability_zone = "${var.region}b"

  tags {
    Name = "Private Subnet - Managed By Terraform"
  }
}

resource "aws_route_table_association" "private_b" {
  count          = "${var.environment == "prod1" ? 0 : 1 }"
  subnet_id      = "${aws_subnet.private_b.id}"
  route_table_id = "${aws_route_table.private.id}"
}

#######################################################################
# prod1 network
#######################################################################
resource "aws_route_table" "private-prod1" {
  count  = "${var.environment == "prod1" ? 1 : 0 }"
  vpc_id = "${aws_vpc.default.id}"

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = "${aws_nat_gateway.aws_nat_gateway.id}"
  }

  tags {
    Name = "Private - Managed By Terraform"
  }
}

resource "aws_route_table_association" "private_a-prod1" {
  count          = "${var.environment == "prod1" ? 1 : 0 }"
  subnet_id      = "${aws_subnet.private_a.id}"
  route_table_id = "${aws_route_table.private-prod1.id}"
}

resource "aws_route_table_association" "private_b-prod1" {
  count          = "${var.environment == "prod1" ? 1 : 0 }"
  subnet_id      = "${aws_subnet.private_b.id}"
  route_table_id = "${aws_route_table.private-prod1.id}"
}


```

### Expected Behavior
```
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

Plan: 0 to add, 0 to change, 0 to destroy.

```

### Actual Behavior
```
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ aws_route_table.public
    route.1321869322.cidr_block:                "10.1.0.0/16" => ""
    route.1321869322.egress_only_gateway_id:    "" => ""
    route.1321869322.gateway_id:                "" => ""
    route.1321869322.instance_id:               "" => ""
    route.1321869322.ipv6_cidr_block:           "" => ""
    route.1321869322.nat_gateway_id:            "" => ""
    route.1321869322.network_interface_id:      "" => ""
    route.1321869322.vpc_peering_connection_id: "pcx-7bff5e12" => ""
    route.2418937047.cidr_block:                "0.0.0.0/0" => "0.0.0.0/0"
    route.2418937047.egress_only_gateway_id:    "" => ""
    route.2418937047.gateway_id:                "igw-69332700" => "igw-69332700"
    route.2418937047.instance_id:               "" => ""
    route.2418937047.ipv6_cidr_block:           "" => ""
    route.2418937047.nat_gateway_id:            "" => ""
    route.2418937047.network_interface_id:      "" => ""
    route.2418937047.vpc_peering_connection_id: "" => ""
    route.2665087803.cidr_block:                "" => "10.1.0.0/16"
    route.2665087803.egress_only_gateway_id:    "" => ""
    route.2665087803.gateway_id:                "" => ""
    route.2665087803.instance_id:               "" => ""
    route.2665087803.ipv6_cidr_block:           "" => ""
    route.2665087803.nat_gateway_id:            "" => "pcx-7bff5e12"
    route.2665087803.network_interface_id:      "" => ""
    route.2665087803.vpc_peering_connection_id: "" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Landscape output
```
$ terraform plan -var-file="variables/grebois.tfvars" | landscape
~ aws_route_table.public
    route.1321869322.cidr_block:                  "10.1.0.0/16" => ""
    route.1321869322.vpc_peering_connection_id:   "pcx-7bff5e12" => ""
    route.2665087803.cidr_block:                  "" => "10.1.0.0/16"
    route.2665087803.nat_gateway_id:              "" => "pcx-7bff5e12"

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
1. `terraform apply`

**Comment by catsby** [comment] 2017-05-18 12:07
Hey there @grebois ! I believe this is a duplicate of https://github.com/hashicorp/terraform/issues/9507 . 

Essentially that AWS API is forgiving here, and doesn't fail when you send a `vpc_peering_connection_id` in the `nat_gateway_id` field. It accepts the mismatch, and corrects it on it's end. 

You an see Terraform trying to correct the backend change:

```
    route.1321869322.vpc_peering_connection_id:   "pcx-7bff5e12" => ""
    route.2665087803.nat_gateway_id:              "" => "pcx-7bff5e12"
```

**Closed by catsby** 2017-05-18 12:07 UTC

**Comment by grebois** [comment] 2017-05-18 13:30
@catsby Sorry, I totally overlooked it, thanks for the support. Cheers!

**Comment by catsby** [comment] 2017-05-18 13:46
No worries!
