### ISSUE TITLE
Data source fails during destroy, succeeds during plan/apply

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform#27849] opened 2021-02-20 05:01 UTC
### Terraform Version
Reproduced in 0.13.6 and 0.14.7

### Narrative ###

I am opening this issue without being able to provide a minimal test case because the real-life case is too complex to easily reduce and I am looking for clues and guidance about how to even decide which parts are relevant and which parts are not. This bug is particularly hard to simplify because it only is triggered during `destroy` and requires a configurable provider. I will do what I can to follow guidance to create a simplified test case.

The real-life problem is in a module that provisions multiple AWS resources. It has a provider block like

```hcl
provider "aws" {
  region = var.region

  assume_role {
    role_arn = module.iam_roles.terraform_role_arn
  }
}
```

The short story is that `module.iam_roles.terraform_role_arn` takes a lot of inputs and based on them, looks up the role ARN in a `data "terraform_remote_state"` source completely separate from the workspace being operated on. This works during `apply` and `plan` but fails during `destroy`.

When `-auto-approve` is not set, `destroy` works up to the point where it asks for confirmation, after which, it fails. **The very suspicious part** is that in order to get to the confirmation stage, Terraform has to use the provider to retrieve the current state of AWS resources, and that means it has already successfully evaluated `module.iam_roles.terraform_role_arn`. If I purposefully break that module, Terraform errors out while refreshing state and never gets to asking for confirmation to destroy the resources.

### Terraform Configuration Files

```hcl
data "terraform_remote_state" "remote" {
  count   = local.backend_type == "remote" ? 1 : 0
  backend = "remote"
  # additional config omitted
}
data "terraform_remote_state" "s3" {
  count   = local.backend_type == "s3" ? 1 : 0
  backend = "s3"
  # additional config omitted
}
```

Sometimes `terraform destroy` fails  with
```
Error: Invalid count argument

  on .terraform/modules/iam_roles.account_map/modules/remote-state/s3.tf line 10, in data "terraform_remote_state" "s3":
  10:   count = local.backend_type == "s3" ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

and sometimes it fails with:
```
Error: Invalid index

  on .terraform/modules/iam_roles.account_map/modules/remote-state/main.tf line 24, in locals:
  24:   outputs = local.remote_states[local.backend_type][0].outputs
    |----------------
    | local.backend_type is "s3"
    | local.remote_states is object with 2 attributes

The given key does not identify an element in this collection value.
```
In this latter case, `local.remote_states is object with 2 attributes` is correct, but one of the 2 attributes definitely is `s3` because `local.remote_states` is declared as a map with static keys `s3` and `remote`. 

```hcl
  remote_states = {
    s3     = data.terraform_remote_state.s3
    remote = data.terraform_remote_state.remote
  }
```

The issue appears to be not that there is no key `s3` but rather the value for the key `s3` is `null`. Again, this is unexpected since it had to be correctly evaluated and non-null in order to initialize the provider to refresh the state.

### Expected Behavior

A provider configuration based on remote state should work during `destroy` as well as other phases, given that the data sources being referenced are not affected by the Terraform operation and do not belong to the current state.

**Comment by jbardin** [comment] 2021-02-22 14:55
Hi @Nuru,

Regarding the two cases you've shown here, the first must fail during planning, because the `value depends on resource attributes that cannot be determined until apply`  error is only emitted during plan. In this case we need to figure out why `local.backend_type` may be unknown during plan.

The second case I'm unsure of what could be happening since we know the `"s3"` key exists, but I think it might be a case of the error attributing the incorrect index error as the problem. Since the structure if `local.remote_states` cannot change, it is likely that the `[0]` index is what is failing, with one of the data sources having been updated to contain 0 instances. This would correspond to the possible change in the data source count value.

I'm not sure what could be causing this offhand, but since this could be quite complex as you stated, perhaps we can see if the behavior has changed at all in the current development version. If you have a test environment you can use, the 0.15 alpha (a new beta will be coming soon), or building terraform from the master branch will give you the most recent version to work with. 

If you can share the configuration, it might be useful for us to look through too. The `destroy` case is quite tricky when providers depend on resources which themselves are being destroyed, and seeing the structure of the configuration may help indicate what could be happening when applying the destroy plan.

**Comment by Nuru** [comment] 2021-02-23 11:10
@jbardin I appreciate you taking the time to look into this given the lack a of a test case. Let me clarify some things I'm not sure I conveyed appropriately the first time.

I have seen both of the 2 failure messages when using `destroy` without `-auto-approve`, and in both cases the error message comes after the confirming "yes" is entered. I cannot tell which one I am going to get, but my hunch is that the deciding factor is something in the current `.terraform` directory. 

I tried replacing `count = local.backend_type == "s3" ? 1 : 0` with `count = 1` and the error message changed to something (I forget exactly what) that indicated that `data.terraform_remote_state.s3[0].outputs` was empty. Together I take these to mean that either the configuration data is not getting passed in to `terrraform_remote_state` or the retrieval is not happening.

The providers are not depending on any resources being destroyed. They depend solely on constants, input variables, and the data from `terrraform_remote_state`. 

I do wonder, though, if the issue could be related to incompatible provider versions. If resources are created with provider version 0.1.0 and then later at destroy time the project is using provider version 0.2.0, is there a chance that during destroy, one phase would use a different provider version than the other? What if there were a breaking change between the 2 versions?

One reason I am thinking along these lines is that we had 5 deployments that all had the same problem being destroyed, but since then I have not been able to reproduce the problem. I know they were provisioned with older versions of modules using older versions of providers, and that all seemed to work. What failed was the new module using the new provider that was not in anyway part of the state of the old resources. But now if I provision everything with the new provider and new module, I can destroy everything with no problems.

**Comment by jbardin** [comment] 2021-02-23 14:06
Thanks for the extra info @Nuru. While it's possible that an older provider saved incorrect information to the state, it's more likely that the state was not fully updated to the latest terraform or configuration version. Error like these often arose from the refresh phase, where it is not always possible to reconcile the state and configuration if they have diverged. In newer releases "refresh" is no longer done separately so that all necessary information is available to read the configured resources. 

Since this isn't something you cannot replicate again, I'm going to close this out for now. If you can find a way to trigger this behavior in a current release, please add all the information necessary for us to recreate the issue here.

Thanks!

**Comment by Nuru** [comment] 2021-03-01 05:44
@jbardin I have reproduced this bug a few more times using Terraform v0.15.0-beta1, getting closer to a test case I could submit. I have a case where I can provision (`terraform apply`) and immediately try to destroy and the destroy fails. I could still use some guidance if you have any. 

The issue something like this:
- There is a custom data module that collects and outputs configuration information
- There is another module that takes that configuration information and uses it to find and retrieve a Terraform remote state using a data `terraform_remote_state` module
- The output of both data modules is saved in the Terraform state of the component in question

I thought somehow that the data saved in the component's state is interfering with the modules finding the current state during the `destroy` operation. The first destroy attempt fails with the error that is the subject of this issue, but it succeeds in deleting the saved `data` outputs. But even with the data removed from the state, the destroy still fails.

One possible cause is the [custom provider](https://github.com/cloudposse/terraform-provider-utils) we are using to retrieve the configuration. Is there something a Terraform provider has to do for `destroy` that it does not have to do for `apply`?

**Comment by jbardin** [comment] 2021-03-01 14:08
Sorry, without an example of what is happening we would only be guessing at this point. If you suspect the provider, you can look for warnings in the logs about the provider's responses. It's not possible to avoid warnings in all cases with the legacy SDK, but perhaps something there could offer a clue.

**Comment by Nuru** [comment] 2021-03-04 07:41
@jbardin OK, I have a reproducible case. Sorry it is still a bit complex, but this is the best I've been able to come up with.

Interesting to note that under Terraform 0.14 the fact that the `account_map` module is misconfigured never factors in: we get the same result whether it is properly configured or not. Under Terraform 0.15.0-beta1, `account_map` needs to be properly configured (via `gbl-root.yaml`) to point to a real Terraform S3 remote state, but when it is, it gives an error similar to the one from TF 0.14. So you may want to fix this in TF 0.14 first, since it is easier to set up and reproduce.

Steps to reproduce:
1. Set up AWS credentials to be able to work with S3 buckets
1. `terraform init`
2. `terraform destroy`

Results under Terraform 0.14.7:

```
Error: Invalid count argument

  on .terraform/modules/account_map/modules/remote-state/remote.tf line 6, in data "terraform_remote_state" "remote":
   6:   count = local.backend_type == "remote" ? 1 : 0

The "count" value depends on resource attributes that cannot be determined...

Error: Invalid count argument

  on .terraform/modules/account_map/modules/remote-state/s3.tf line 10, in data "terraform_remote_state" "s3":
  10:   count = local.backend_type == "s3" ? 1 : 0

```

Results under Terraform 0.15.0-beta1:
```
│ Error: Invalid index
│ 
│   on .terraform/modules/account_map/modules/remote-state/main.tf line 30:
│   (source code not available)
│     ├────────────────
│     │ local.backend_type is "s3"
│     │ local.remote_states is object with 2 attributes
│ 
│ The given key does not identify an element in this collection value.
```

Here is the source for the module. Put all these files in the same directory:

<details><summary>default.auto.tfvars</summary>

```hcl
name = "logging"
environment = "uw2"
stage = "dev"
```

</details>
<details><summary>bug.tf</summary>

```hcl
variable "region" {
  type        = string
  description = "AWS region"
}

provider "aws" {
  region = var.region

  assume_role {
    role_arn = module.account_map.outputs.terraform_roles[module.this.stage]
  }
}

module "account_map" {
  source  = "cloudposse/stack-config/yaml//modules/remote-state"
  version = "0.12.0"

  stack_config_local_path = "./"
  component               = "account-map"
  privileged              = false
  environment             = "gbl"
  stage                   = "root"

  context = module.this.context
}


resource "aws_s3_bucket" "default" {
  count         = module.this.enabled ? 1 : 0
  bucket        = module.this.id
  acl                 = "private"
}


terraform {
  required_version = ">= 0.14.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.30.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "2.1.0"
    }
    utils = {
      source  = "cloudposse/utils"
      version = "0.3.1"
    }
  }
}
```

</details>
<details><summary>context.tf</summary>

Note: This file a copy of https://github.com/cloudposse/terraform-null-label/blob/0.24.1/exports/context.tf

```hcl
module "this" {
  source  = "cloudposse/label/null"
  version = "0.24.1" # requires Terraform >= 0.13.0

  enabled             = var.enabled
  namespace           = var.namespace
  environment         = var.environment
  stage               = var.stage
  name                = var.name
  delimiter           = var.delimiter
  attributes          = var.attributes
  tags                = var.tags
  additional_tag_map  = var.additional_tag_map
  label_order         = var.label_order
  regex_replace_chars = var.regex_replace_chars
  id_length_limit     = var.id_length_limit
  label_key_case      = var.label_key_case
  label_value_case    = var.label_value_case

  context = var.context
}

# Copy contents of cloudposse/terraform-null-label/variables.tf here

variable "context" {
  type = any
  default = {
    enabled             = true
    namespace           = null
    environment         = null
    stage               = null
    name                = null
    delimiter           = null
    attributes          = []
    tags                = {}
    additional_tag_map  = {}
    regex_replace_chars = null
    label_order         = []
    id_length_limit     = null
    label_key_case      = null
    label_value_case    = null
  }
  description = <<-EOT
    Single object for setting entire context at once.
    See description of individual variables for details.
    Leave string and numeric variables as `null` to use default value.
    Individual variable settings (non-null) override settings in context object,
    except for attributes, tags, and additional_tag_map, which are merged.
  EOT

  validation {
    condition     = lookup(var.context, "label_key_case", null) == null ? true : contains(["lower", "title", "upper"], var.context["label_key_case"])
    error_message = "Allowed values: `lower`, `title`, `upper`."
  }

  validation {
    condition     = lookup(var.context, "label_value_case", null) == null ? true : contains(["lower", "title", "upper", "none"], var.context["label_value_case"])
    error_message = "Allowed values: `lower`, `title`, `upper`, `none`."
  }
}

variable "enabled" {
  type        = bool
  default     = null
  description = "Set to false to prevent the module from creating any resources"
}

variable "namespace" {
  type        = string
  default     = null
  description = "Namespace, which could be your organization name or abbreviation, e.g. 'eg' or 'cp'"
}

variable "environment" {
  type        = string
  default     = null
  description = "Environment, e.g. 'uw2', 'us-west-2', OR 'prod', 'staging', 'dev', 'UAT'"
}

variable "stage" {
  type        = string
  default     = null
  description = "Stage, e.g. 'prod', 'staging', 'dev', OR 'source', 'build', 'test', 'deploy', 'release'"
}

variable "name" {
  type        = string
  default     = null
  description = "Solution name, e.g. 'app' or 'jenkins'"
}

variable "delimiter" {
  type        = string
  default     = null
  description = <<-EOT
    Delimiter to be used between `namespace`, `environment`, `stage`, `name` and `attributes`.
    Defaults to `-` (hyphen). Set to `""` to use no delimiter at all.
  EOT
}

variable "attributes" {
  type        = list(string)
  default     = []
  description = "Additional attributes (e.g. `1`)"
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Additional tags (e.g. `map('BusinessUnit','XYZ')`"
}

variable "additional_tag_map" {
  type        = map(string)
  default     = {}
  description = "Additional tags for appending to tags_as_list_of_maps. Not added to `tags`."
}

variable "label_order" {
  type        = list(string)
  default     = null
  description = <<-EOT
    The naming order of the id output and Name tag.
    Defaults to ["namespace", "environment", "stage", "name", "attributes"].
    You can omit any of the 5 elements, but at least one must be present.
  EOT
}

variable "regex_replace_chars" {
  type        = string
  default     = null
  description = <<-EOT
    Regex to replace chars with empty string in `namespace`, `environment`, `stage` and `name`.
    If not set, `"/[^a-zA-Z0-9-]/"` is used to remove all characters other than hyphens, letters and digits.
  EOT
}

variable "id_length_limit" {
  type        = number
  default     = null
  description = <<-EOT
    Limit `id` to this many characters (minimum 6).
    Set to `0` for unlimited length.
    Set to `null` for default, which is `0`.
    Does not affect `id_full`.
  EOT
  validation {
    condition     = var.id_length_limit == null ? true : var.id_length_limit >= 6 || var.id_length_limit == 0
    error_message = "The id_length_limit must be >= 6 if supplied (not null), or 0 for unlimited length."
  }
}

variable "label_key_case" {
  type        = string
  default     = null
  description = <<-EOT
    The letter case of label keys (`tag` names) (i.e. `name`, `namespace`, `environment`, `stage`, `attributes`) to use in `tags`.
    Possible values: `lower`, `title`, `upper`.
    Default value: `title`.
  EOT

  validation {
    condition     = var.label_key_case == null ? true : contains(["lower", "title", "upper"], var.label_key_case)
    error_message = "Allowed values: `lower`, `title`, `upper`."
  }
}

variable "label_value_case" {
  type        = string
  default     = null
  description = <<-EOT
    The letter case of output label values (also used in `tags` and `id`).
    Possible values: `lower`, `title`, `upper` and `none` (no transformation).
    Default value: `lower`.
  EOT

  validation {
    condition     = var.label_value_case == null ? true : contains(["lower", "title", "upper", "none"], var.label_value_case)
    error_message = "Allowed values: `lower`, `title`, `upper`, `none`."
  }
}
```

</details>
<details><summary>gbl-root.yaml</summary>

```yaml
vars:
  namespace: bug

terraform:
  vars: {}
  backend_type: s3
  backend:
    s3:
      encrypt: true
      # For Terraform 0.15 `bucket` must point to a real S3 bucket
      # that the user can use as a Terraform state backend
      bucket: "bug-tfstate"
      # For Terraform 0.15 `dynamodb_table` but point to a real
      # table the user can use as a Terraform lock table
      dynamodb_table: "bug-tfstate-lock"
      key: "terraform.tfstate"
      role_arn: null
      acl: "bucket-owner-full-control"
      region: "us-west-2"
    remote:
    vault:

components:
  terraform:
    account-map:
      backend:
        s3:
          # For Terraform 0.15 there needs to be a valid S3 remote state under the
          # workspace prefix `account-map` with a workspace named `gbl-root`.
          # Ideally it should have an output map named `terraform_roles`
          # with a key `dev` and value of a real AWS IAM ARN the user can assume.
          workspace_key_prefix: "account-map"
```

</details>

**Comment by jbardin** [comment] 2021-03-05 18:12
Thanks. There is a lot more information there, but still not quite a standalone reproduction to work with. Is it possible to share the trace logs from this `destroy` operation?

The fact that on 0.14 the count values are unknown and on 0.15 the backend type appears to be unset both lead to `utils_stack_config_yaml`, and see,s like it's returning an unexpected configuration during destroy. In 0.15 but you could try running the destroy with `-refresh=false` to see how that changes the behavior.

**Comment by Nuru** [comment] 2021-03-05 20:38
@jbardin I updated `default.auto.tfvars` [(above)](https://github.com/hashicorp/terraform/issues/27849#issuecomment-790394650) with a missing value, and with that, even though it should not be, the provided example truly is standalone for Terraform 0.14.7. It reproduces the error without out any AWS credentials or resources. It only requires an internet connection to download stuff from the Terraform registry.

I uploaded an encrypted redacted trace log [here](https://gist.github.com/Nuru/755940823d1741fed4d2ca82b8d2e387). It was from a destroy with Terraform 0.15.0-beta1

**Comment by Nuru** [comment] 2021-03-05 22:36
@jbardin Thanks for marking this `confirmed`. Would you mind re-opening the issue please?

**Comment by jbardin** [comment] 2021-03-05 22:46
Thanks @Nuru, the logs got me what I needed there. There is a long chain of events, or on some aspects, non-events that lead to the expansion of the remote state data sources failing to evaluate.

The primary dependency in this case is the aws provider itself, which due to the `module.account_map.outputs.terraform_roles` reference eventually depends on these data sources, which is why they are being re-evaluated during destroy. There however because the aws provider is not actually doing anything here, there is no managed resource dependency during destroy to ensure that the `utils_stack_config_yaml` data source remains in the state long enough to expand the `terraform_remote_state` data sources.

**Comment by Nuru** [comment] 2021-03-05 23:08
@jbardin Thanks for re-opening this.  Some more info for you based on your most recent comment:

If you remove the `resource "aws_s3_bucket" "default"` from `bug.tf` then the `destroy` works, presumably because in that case there is no need to initialized the AWS provider. 

> However because the aws provider is not actually doing anything here, there is no managed resource dependency during destroy to ensure that the utils_stack_config_yaml data source remains in the state long enough to expand the terraform_remote_state data sources.

I am not quite sure what you mean by "managed resource dependency". In the original use case, there was a lot of AWS stuff to destroy, but AFAIK no resources ever depend on `module.account_map.outputs.terraform_roles`, that is only there for the provider configuration. So if I am following you correctly, the bug is that a provider's configuration dependencies are not considered "managed resource dependencies".

**Comment by jbardin** [comment] 2021-03-06 16:38
What I was referring to was really some internal implementation details, which are only of concern to work on the problem at hand. The destroy operation in general is always difficult in Terraform when providers depend on resources (data or managed), because the destroy order for dependencies must be in reverse from the creation, but providers of course need to evaluate their dependencies in order to run the destroy operation. Managed resources store their destroy-time dependencies which are relied upon for their individual destroy ordering, but because there is no managed resource in this situation, the dependencies don't get setup as needed.

**Closed** 2021-03-09 17:59 UTC
Labels: bug, confirmed
