### ISSUE TITLE
`terraform plan` fails when indexing into data source with dependency

### ISSUE THREAD

**Issue by actgardner** [hashicorp/terraform#23996] opened 2020-01-30 19:26 UTC
### Terraform Version

```
20105 $ terraform -v
Terraform v0.12.20
+ provider.google v3.6.0
+ provider.google-beta v3.6.0
```

### Terraform Configuration Files

Using the example under `Example Usage - Binary Authorization Attestor Kms`: https://www.terraform.io/docs/providers/google/r/binary_authorization_attestor.html

### Expected Behavior
`data.google_kms_crypto_key_version.version.public_key[0].pem` should evaluate to the public key for the KMS key when running `terraform plan`.

### Actual Behavior

`terraform plan` fails with:

```
Error: Invalid index

  on attestors.tf line 8, in resource "google_binary_authorization_attestor" "attestor":
 8:         public_key_pem      = data.google_kms_crypto_key_version.version.public_key[0].pem
    |----------------
    | data.google_kms_crypto_key_version.version.public_key is empty list of object

The given key does not identify an element in this collection value.
```

I tried creating the keys first and refreshing, and even applying multiple times.

In `terraform console` it's possible to see the correct value:
```
20599 $ terraform console
> data.google_kms_crypto_key_version.version.public_key[0].pem
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5APdMkaOm4O7ErmieZv/
Y3H7UAkWsmlm8C3TXHz25+R5yzUD0B2y/jew3ENl5SV1oAPoikqt3B96aoR9UX90
AbhZz1o20kOSF5qdMsyHsu1qD34H6nZkEJw1BJdkElI0ROZ8Nw8F/C+cGGysbfQD
FwdzzQMsPmoeRGNMQKfP0Kr/7SIlzw/f1NFA66FAn5gU07CCTCTCHmbUWd/Ln33Q
fG3rVQ4KyfY9jnnKUIZ3FaL7G+Lqm4QO/MhQRZ51P92ovL0R0Und6BXg1cwHPWv4
m9m69HlLhuJduaP+Fs4sHFby3/oeXwt1Vf7j3UJrA0PUekapgO9NbEfoeHd5fdoY
cJ8VeE1p3PiviQjwthtpVXcJaGNsLQGHBKozAfqSkFS7OTWsv+jBZLgfp181+oh9
i79wohKzDLhufMMA0SYZSbiAoJfAan3TMZjQXch8fuWGQAh2b0e4kXx+SUuiybLL
66vuhJHEujV3po7RH6xzpIP7fuFu4kI5tQQ8YIEzkIFMcigdLvPqou4Rxi/PHczj
BE4NcCDO/LXc0jsAGQ146kjfowion63OjWgZub0sHDJUhHBq+YndeFJ20zQa2x0p
UVsid6oYuDRZ31aGRk1ZFsmhb+xOtTAtRD6HT/oKAt74x8c48EE/wA8mU9vtWcrS
Xq2yB+RlJMn4/XyhG7HnmH8CAwEAAQ==
-----END PUBLIC KEY-----
```

### Steps to Reproduce
Create a terraform root with the example code, run `terraform plan`.

**Comment by actgardner** [comment] 2020-01-30 19:28
Changing 
```
data "google_kms_crypto_key_version" "version" {
  crypto_key = google_kms_crypto_key.crypto-key.self_link
}
```

to

```
data "google_kms_crypto_key_version" "version" {
  crypto_key = "<literal path of the key>"
}
```

resolves the issue, so this seems to be an issue with resolving data that depends on a resource.

**Comment by jbardin** [comment] 2020-01-31 17:25
Hi @actgardner,

With the error `data.google_kms_crypto_key_version.version.public_key is empty list of object`, the problem is that the data source is returning an empty list.

This would need to be fixed by the provider, so I'll tag this to be transferred to the google provider repo.

**Closed** 2020-01-31 18:20 UTC
Labels: provider/google
