### ISSUE TITLE
Bug received EOF After Ansible playbook

### ISSUE THREAD

**Issue by Unknow101** [hashicorp/terraform#27163] opened 2020-12-07 13:38 UTC
### Terraform Version

```
v0.14.0

...
```

### Terraform Configuration Files

```terraform
resource "aws_key_pair" "ws01" {
  key_name   = var.ssh_private_key_ws01
  public_key = file("${path.module}/${var.ssh_public_key_ws01}")
}


resource "aws_security_group" "allow_ws01" {
    vpc_id = aws_vpc.default.id

    ingress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
    }

    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
    }
}


resource "aws_instance" "WS01" {

  depends_on = [aws_instance.DC01]
  ami = "ami-0081abcf0bf328e32"
  private_ip = "172.16.2.151"
  instance_type = "t2.large"
  key_name = aws_key_pair.ws01.key_name
  subnet_id = aws_subnet.private_subnet.id
  associate_public_ip_address = false

  vpc_security_group_ids = [aws_security_group.allow_ws01.id]
  tags = {
      Name = "WS01 - Private"
  }
    user_data = <<EOF
    <script>
      @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
      winrm quickconfig -q & winrm set winrm/config @{MaxTimeoutms="1800000"} & winrm set winrm/config/service @{AllowUnencrypted="true"} & winrm set winrm/config/service/auth @{Basic="true"}
    </script>
    <powershell>
      netsh advfirewall firewall add rule name="WinRM in" protocol=TCP dir=in profile=any localport=5985 remoteip=any localip=any action=allow
      # Set Administrator password
      $admin = [adsi]("WinNT://./administrator, user")
      $admin.psbase.invoke("SetPassword", "<redacted>")
    </powershell>
    EOF

  connection {
      host = "172.16.2.151"
      type = "winrm"  
      user = "Administrator"
      password = "<redacted>"
      timeout = "10m"
  }

  provisioner "local-exec" {
    command = "sleep 180"
  }


  provisioner "remote-exec" {
    inline = [
      "netsh interface ip set dns name=\"Ethernet\" static 172.16.2.150"
    ]
  }

  provisioner "remote-exec" {
    inline = [
      "powershell.exe -Command \"Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False\""
    ]
  }

  provisioner "file" {
    source      = "${path.module}/scripts/ConfigureRemotingForAnsible.ps1"
    destination = "C:/Windows/Temp/ConfigureRemotingForAnsible.ps1"
  }

  provisioner "remote-exec" {
    inline = [
      "powershell.exe -Command \"Import-Module C:\\Windows\\Temp\\ConfigureRemotingForAnsible.ps1\""
    ]
  }

  provisioner "local-exec" {
    command = "ansible-playbook -i 172.16.2.151, domainWS01.yml -e \"blablabla\""
  }
}

...
```

### Debug Output

```aws_instance.WS01 (local-exec): PLAY RECAP *********************************************************************
aws_instance.WS01 (local-exec): 172.16.2.151               : ok=7    changed=4    unreachable=0    failed=0

aws_instance.WS01: Creation complete after 7m5s [id=i-0c92788dc1f3d6939]
2020-12-07T08:26:38.652-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-07T08:26:38.656-0500 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.20.0/linux_amd64/terraform-provider-aws_v3.20.0_x5 pid=14514
2020-12-07T08:26:38.656-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-07T08:26:38.656-0500 [DEBUG] plugin: plugin exited
2020-12-07T08:26:40.653-0500 [WARN]  plugin: plugin failed to exit gracefully
^C2020/12/07 08:29:20 [WARN] terraform: Stop called, initiating interrupt sequence
2020/12/07 08:29:20 [WARN] terraform: run context exists, stopping
2020/12/07 08:29:20 [INFO] terraform: waiting for graceful stop to complete
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...
^C2020/12/07 08:29:20 [WARN] running operation was forcefully canceled
2020-12-07T08:29:20.958-0500 [WARN]  plugin: error closing client during Kill: err="rpc error: code = Canceled desc = grpc: the client connection is closing"
2020-12-07T08:29:20.958-0500 [WARN]  plugin: plugin failed to exit gracefully
2020-12-07T08:29:20.959-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-12-07T08:29:20.959-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
Two interrupts received. Exiting immediately. Note that data
```

### Expected Behavior

I except Terraform to just close and print me out the finish message but it just print that erros and hangs until i kill the process on another term.

This config was working until last week-end ... I really don't understand why terraform crash here.
In my projet a DC is set up using ansible juste before this host and all work good for him.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment] 2020-12-07 14:07
Thanks for filing the issue @Unknow101.
This appears to be a bug in the go-plugin package, though I'm going to keep the issue open temporarily for some more debugging first.

**Comment by Unknow101** [comment] 2020-12-07 14:09
Thanks for your quick reply.
So you confirme that the issue is from terraform and not from a misconfiguration?

**Comment by jbardin** [comment] 2020-12-07 14:32
@Unknow101, It does not look like the configuration could be directly causing the issue. I can replicate it with the go-plugin package alone, though I don't yet know what is triggering this to happen in terraform, as the provisioner command appears to execute correctly, while the plugin itself does not exit.

**Comment by Unknow101** [comment] 2020-12-08 08:16
Okay.
Do you have an idea of when Hashicorp will give it a look ?

**Comment by jbardin** [comment] 2020-12-08 15:10
It seems my contrived example is not possible in the real codepath, so I'm not sure how you may have reached this state. 
If you can reproduce this, It would be great if you could supply some more information. I have some more things that could be tried here. Your log output doesn't seem to be complete. Can you provide trace logs around the point of the plugin being stalled?

Another thing you can test, is running the process with `TF_FORK=0`. This will prevent wrapper processes from being started, and all log output will go to the console. If this avoids the problem, we can narrow down the problem space significantly. 

Thanks

**Comment by jbardin** [comment] 2021-04-01 19:53
Since we do not yet have a working reproduction here, I'm going to close this out for now. The upcoming 0.15 release has much better handling of the provisioner processes, so if the error can be reproduced with that version, feel free to reply with the requested information and we can re-evaluate the issue.

Thanks!

**Closed by jbardin** 2021-04-01 19:53 UTC
Labels: bug, waiting for reproduction
