### ISSUE TITLE
Missing context for provider diagnostics

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#20121] opened 2019-01-26 18:06 UTC
### Terraform Version

ae0be75ae09efb191ecd22f27389b16521c771fb (`Thu Jan 24 17:41:30 2019 -0800`)

### Terraform Configuration Files

```hcl
# no provider block

resource "tfe_workspace" "test" {
  name         = "my-workspace-name"
  organization = "radeksimko"
}
```

### Expected Behavior

A diagnostic which gives some hint about where the error is coming from.

### Actual Behavior

```
Error: required token could not be found

  on <empty> line 0:
  (source code not available)

```

### Steps to Reproduce

```
terraform apply
```

### Additional Context

I have compiled TFE provider from [this branch](https://github.com/terraform-providers/terraform-provider-tfe/compare/radeksimko/v0.12-upgrade) (basically just bumped Terraform to `ae0be75ae09efb191ecd22f27389b16521c771fb`).

I am aware that we want to avoid adding too much context to error messages as we expect these to be presented with the snippet of code. This however isn't always possible, as demonstrated in this issue, where provider block is not in the config at all and settings can be provided via ENV variables.

**Comment by apparentlymart** [comment] 2019-01-26 19:10
For this particular case it looks like the error reporting is using an uninitialized `hcl.Range`, whose zero value has an empty filename, line zero, etc.

Hopefully whatever code is generating this diagnostic has enough context to notice that a particular provider has no explicit configuration at all and modify the error message to explain better what's going on here:

```
Error: required token could not be found

Provider "foo" requires explicit configuration. Add a provider "foo" block
to the root module and configure the provider's required arguments
as described in the provider documentation.
```

While this message is not technically 100% accurate -- it is possible to get a provider configuration error for a provider that _doesn't_ require explicit configuration -- I think it's true enough in practice to be reasonable advice, and the reference to the provider's documentation can allow us to describe there any exceptional cases where that advice is not true, such as stating that certain required arguments can be set by environment variables instead.

I'm not totally sure what is currently responsible for generating this error on the Terraform Core side, but I assume it's something in the provider configuration codepath where it should have enough information to know the provider's name and be able to tweak diagnostics being returned over the provider protocol to include this additional note in situations where the provider configuration is implicitly empty.

It looks like the provider itself could do with some better error handling for this case as well. If this is intending to report that the token argument is required but not set, I think we could phrase that better to make more explicit what we're talking about here. If not, it'd at least be nice to clarify where we were looking for this "required token" and where it might be placed in order to allow it to be found.

**Comment by pselle** [comment] 2019-08-06 18:34
This looks like it is either a duplicate of, or outdated by #20794 - what do you think @radeksimko?

**Comment by radeksimko** [comment] 2019-08-06 18:46
@pselle These are likely to be different bugs as the symptoms are different and reasons are different?

We have _no_ provider block in the code and _no_ context (as a result of no provider block), so we'll need to be a bit more creative in resolving this as we cannot just point to LOC which doesn't exist.

In the other linked issue we _have_ diagnostics and we _have_ relevant line of code to point to, it's just pointing to wrong one for some reason. So #20794 is most likely much easier to fix as it "just" needs to return a different code range.

**Comment by pselle** [comment] 2019-08-08 19:24
@radeksimko Thank you for the lead!

**Comment by hazcod** [comment] 2019-10-16 07:35
I see this aswel on https://github.com/hashicorp/terraform/issues/23087

**Closed** 2020-12-11 18:18 UTC
Labels: bug, cli, config, v0.12
