### ISSUE TITLE
Regression: #647 Map override in tfvars gives a syntax error.

### ISSUE THREAD

**Issue by morcmarc** [hashicorp/terraform#4037] opened 2015-11-24 10:07 UTC
I was playing around with the master branch and found that map-type input variables are broken. Apparently this is a regression of #647. Quick example:

variables.tf:
```
variable "amis" {
        default = {}
}

variable "region" {
        default = ""
}
```

main.tf:
```
output "ami" {
  value = "${lookup(var.amis, var.region)}"
}
```

input.tfvars:
```
amis.eu-west-1 = "ami123"
amis.us-east-1 = "ami456"
```

Running `terraform plan -var-file=input.tfvars -var 'region=eu-west-1'` throws:

```
invalid value "input.tfvars" for flag -var-file: Error parsing input.tfvars: At 1:5: expected: IDENT | STRING | ASSIGN | LBRACE got: PERIOD
```

I guess this a problem with Hcl rather than Terraform but since there's a similar issue already I though I'll raise it here.

**Comment by jen20** [comment] 2015-11-24 10:20
Hi @morcmarc! Thanks for reporting this. It appears to be a duplicate of #4023, which is where we're currently tracking it. I'm going to close this issue in favour of keeping the investigation in one place on the first reported instance of the issue. If you think it's not a duplicate and the circumstances are different, please reopen!

**Closed by jen20** 2015-11-24 10:20 UTC
Labels: bug, core
