### ISSUE TITLE
null not working as documented in 0.12

### ISSUE THREAD

**Issue by ljckennedy** [hashicorp/terraform#22430] opened 2019-08-12 05:48 UTC
### Terraform Version

```
Terraform v0.12.6
+ provider.azuread v0.5.1
+ provider.azurerm v1.30.0
+ provider.helm v0.10.2
+ provider.kubernetes v1.8.1
```

### Terraform Configuration Files

```hcl
  network_profile {
    network_plugin = "${length(var.network_plugin) > 1 ? var.network_plugin : var.def_network_plugin }" 
    service_cidr = "${length(var.service_cidr) > 1 ? var.service_cidr : null }"
    dns_service_ip = "${length(var.dns_service_ip) > 1 ? var.dns_service_ip : null}"
    docker_bridge_cidr = "${length(var.docker_bridge_cidr) > 1 ? var.docker_bridge_cidr : null}"
  }
```
NB:  network_plugin is set to kubenet which does not require the other variables to be set.

### Crash Output

Error: Invalid function argument

  on aks.tf line 61, in resource "azurerm_kubernetes_cluster" "aksqse":
  61:     service_cidr = "${length(var.service_cidr) > 1 ? var.service_cidr : null }"
    |----------------
    | var.service_cidr is null

Invalid value for "value" parameter: argument must not be null.

### Expected Behavior

As the manual states:
a value that represents absence or omission. If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.

### Actual Behavior

Errors that the argument must not be null.  This implies the value has been set as opposed to being unset.

### Additional Context

occurs in azurerm_kubernetes_cluster however I do not think this is relevant.

**Comment by teamterraform** [comment] 2019-08-13 00:30
Hi @ljckennedy,

The error message here is complaining that `var.service_cidr` is null, not that the final `service_cidr` value is null. The `length` function does not accept null values for its argument, and so it's failing here.

Some other approaches here would include:

* Making the default value of `var.service_cidr` be an empty string rather than `null`, so that `length(var.service_cidr)` will return zero when it isn't set.

* Using [`coalesce`](https://www.terraform.io/docs/configuration/functions/coalesce.html) to provide a default string value to use if `var.service_cidr` is null.

Because Terraform is working as designed here, we're going to close this out. If you have any further questions, please feel free to start a topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core)!

**Closed by teamterraform** 2019-08-13 00:30 UTC
Labels: question
