### ISSUE TITLE
conditional doesn't support variable interpolation

### ISSUE THREAD

**Issue by tkellen** [hashicorp/terraform#10854] opened 2016-12-20 04:22 UTC
Loving the new ternary conditionals, thanks! I hit a use-case where they aren't functioning correctly. 
```
${var.sometimes_false ? var.other_var : resource.name.property}
```

Here is a contrived example, a `compute` module which provides a default security group but allows overriding.

## module/compute.tf
```hcl
variable "name" { }
variable "sg_id" { default = false }

resource "aws_instance" "host" {
  ami = "ami-40d28157"
  instance_type = "t2.nano"
  vpc_security_group_ids = [
    "${var.sg_id ? var.sg_id : aws_security_group.main.id}"
  ]
}

resource "aws_security_group" "main" {
  name = "${var.name}"
  egress {
    from_port = 0
    to_port = 0
    protocol = -1
    cidr_blocks = [
      "0.0.0.0/0"
    ]
  }
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    cidr_blocks = [
      "0.0.0.0/0"
    ]
  }
}

```

## terraform.tf
```hcl
provider "aws" {
  region = "us-east-1"
}

module "webserver" {
  source = "./compute"
  name = "web"
}

module "dbserver" {
  source = "./compute"
  name = "db"
  sg_id = "${aws_security_group.test.id}"
}

resource "aws_security_group" "test" {
  name = "test"
  egress {
    from_port = 0
    to_port = 0
    protocol = -1
    cidr_blocks = [
      "0.0.0.0/0"
    ]
  }
}
```

...this yields
```
Error applying plan:

1 error(s) occurred:

* __builtin_StringToBool: strconv.ParseBool: parsing "sg-0a784a77": invalid syntax in:

${var.sg_id ? var.sg_id : aws_security_group.main.id}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Am I missing something or is this an oversight?

**Comment by apparentlymart** [comment] 2016-12-20 05:04
Hi @tkellen!

The conditional operator expects its first operand do be either a boolean or a string that converts to one. It looks like what you are passing here is a string that might be empty, in which case you could write the first operand as `var.sg_id != ""` to get a boolean expression for the situation you want here.

**Comment by tkellen** [comment] 2016-12-20 06:27
Thanks @apparentlymart, changing the conditional as you mentioned did solve the issue! I feel like the error message could be a little more clear here, so I'm going to leave this open for the moment.

**Comment by apparentlymart** [comment] 2016-12-20 06:45
Yeah, it seems to just be exposing the raw error from the Go library function it's using to convert from bool to string, which is unhelpful for anyone who isn't familiar with Go.

Agreed that we should fix this message, though that will be an issue in the codebase for the interpolation language parser, so I'll make an issue over there and link it to this one.

**Comment by apparentlymart** [comment] 2016-12-20 06:54
hashicorp/hil#44 captures this bug from HIL's perspective. I'll leave this here to represent the need to update the vendoring of HIL in Terraform once the other issue is closed.

**Comment by thomasbiddle** [comment] 2017-11-27 19:41
>The conditional operator expects its first operand do be either a boolean or a string that converts to one.

@apparentlymart I don't believe that's correct.

```
# Defined in the module...
variable "some_var" {
  default = false
}

module "some_module" {
  some_var = true
}

This will always return false.
${var.some_var == true ? true : false}

module "some_module" {
  some_var = "true"
}
Now with both the variable defined as a string, and checking for a string, it will match.
${var.some_var == "true" ? true : false}
```

**Comment by mildwonkey** [comment] 2019-06-25 15:13
Hi all!
Terraform's handling of both booleans and conditionals has changed quite a bit in terraform 0.12.

I've confirmed that the original example works now. Also (and more importantly), terraform's type checking system is much more robust and gives actionable error messages if, for example, you use `"true"` in place of `true` for a variable of type `boolean`. 

I am going to close this issue, but if you come across any odd behaviors after upgrading to 0.12 please open a new issue. Thanks!

**Closed by mildwonkey** 2019-06-25 15:13 UTC
Labels: bug, config
