### ISSUE TITLE
Support AWS EKS IAM Roles

### ISSUE THREAD

**Issue by guidoffm** [hashicorp/terraform#24567] opened 2020-04-06 06:45 UTC
I want to run Terraform in a pod on AWS Elastic Kubernetes Service (EKS).

Terraform should write the state to S3.

Access rights for S3 should be granted to the pod by a service account that is assigned an IAM Role:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

To get this working a Go AWS SDK with a version of at least 1.23.13 is required according to https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

It seems that this has nothing to do with the Terraform AWS provider. The code is here in this project. Please do not have this issue closed and re-opend in terraform-aws-provider again like #24252

**Comment by pkolyvas** [comment] 2020-04-06 14:10
Hi @guidoffm 

Assigning new rights (and IAM Role) to an S3 bucket, or modifying those rights, would need to be done with the AWS provider. 

Regarding the backend - one can define which role should be assumed when accessing/using the bucket intended for state storage, but you'll need to configure the bucket itself with the Terraform provider.

After reading your issue again however, I believe what you're asking is for to upgrade the Go AWS SDK used within our s3 backend in this codebase. Is that correct?

**Comment by guidoffm** [comment] 2020-04-14 09:45
Hi @pkolyvas 

As far as I found out the code to use S3 as remote state is in the core and not in the AWS provider.

You can use the S3 remote state w/o the AWS provider.

You can find the required version for AWS SDK here:

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by pkolyvas** [comment] 2020-04-14 14:22
Indeed, I believe the ticket I referenced is asking for the same thing, so I'm going to close this one out as a duplicate. Thanks for your contribution. :) 

Duplicate of #24480

**Closed by pkolyvas** 2020-04-14 14:22 UTC
Labels: enhancement
