### ISSUE TITLE
Cycle issue in a simple module when I run terraform plan

### ISSUE THREAD

**Issue by egarbi** [hashicorp/terraform#3686] opened 2015-10-29 15:20 UTC
This is my main.tf:
```
variable "access_key" {}
variable "secret_key" {}
variable "key_path" {}
variable "region" {
    default = "eu-west-1"
}

variable "zones" {
  default = "a,b,c"
}

variable "prefix_cidr" {
    default = "172.31"
}
provider "aws" {
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    region = "${var.region}"
}

resource "aws_subnet" "public" {
    count = "${length(split(",", var.zones))}"
    cidr_block = "${var.prefix_cidr}.${count.index+1}.0/24"
    availability_zone = "${var.region}${element(split(",", var.zones), count.index)}"
    map_public_ip_on_launch = 1
    tags {
        Name = "public ${var.region}${element(split(",", var.zones), count.index)} (default)"
    }
    vpc_id = "vpc-0f7b9c6a"
}

resource "aws_security_group" "grafana" {
    name = "grafanasg"
    description = "Security Group to allow incoming traffic to Grafana instance"

    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        security_groups = ["0.0.0.0/0"]
    }
    vpc_id = "vpc-0f7b9c6a"
}

module "grafana" {
    source = "../apisvc-debug"
    key_name = "something"
    key_path = "${var.key_path}"
    itype = "m1.small"
    subnets = "${join(",", aws_subnet.public.*.id)}"
    sgroups = "${aws_security_group.grafana.id}"
    region = "${var.region}"
}
```
...and this is the module Im calling, from ../apisvc-debug/apisvc.tf
```
resource "aws_instance" "apisvc" {
    ami = "${var.ami}"
    instance_type = "${var.itype}"
    key_name = "${var.key_name}"
    count = "${length(split(",", var.subnets))}"
    subnet_id = "${element(split(",", var.subnets), count.index)}"
    vpc_security_group_ids = ["${split(",", var.sgroups)}"]
}
```
This is the error when I run terraform plan:
```
terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* Cycle: module.grafana.var.subnets, module.grafana.aws_instance.apisvc (destroy), aws_subnet.public (destroy), aws_subnet.public
```

**Comment by egarbi** [comment] 2015-10-29 15:35
BTW, this is not the real module I'm using, just I created a simple one to reproduce the issue

**Comment by jwaldrip** [comment] 2015-11-09 03:38
I am getting a similar error when dealing with template files.

**Comment by davidhoyt** [comment] 2016-01-10 08:34
Am facing cycle issues with template files as well. Problem goes away if I remove the template (but I need the template...).

**Comment by dcarley** [comment] 2016-05-13 13:04
This is probably a duplicate of #2301

**Comment by mitchellh** [comment] 2016-10-27 16:48
This is a dup of #2301 thanks @dcarley

**Closed by mitchellh** 2016-10-27 16:48 UTC
Labels: bug, core

**Comment by vadimslu** [comment] 2018-05-31 17:54
Having the same error when I'm trying to create two different security groups which are whitelisted to each other.

bash-3.2$ terraform -v
Terraform v0.11.7
+ provider.aws v1.21.0

nodes-sg
--------------------------------------------------------------------------------
   ingress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    security_groups = ["${aws_security_group.mgmt-sg.id}"]
  }
--------------------------------------------------------------------------------

mgmt-sg
--------------------------------------------------------------------------------
  ingress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    security_groups = ["${aws_security_group.inetface-sg.id}"]
  }

 ingress {
    from_port = 2376
    to_port = 2376
    protocol = "tcp"
    security_groups = ["${aws_security_group.nodes-sg.id}"]
  }
--------------------------------------------------------------------------------

Error: Error asking for user input: 1 error(s) occurred:

* Cycle: aws_security_group.mgmt-sg, aws_security_group.nodes-sg
