### ISSUE TITLE
Resource updated without showing which param will be updated

### ISSUE THREAD

**Issue by Skull0ne** [hashicorp/terraform#22335] opened 2019-08-05 20:25 UTC
Hi

I'm upgrading from TF 0.11.14 to 0.12.x. I have followed all the steps and running plan/apply with TF 0.11 wasn't showing any modification.

Now with TF 0.12 (I tried 0.12.3, 0.12.4 and 0.12.6) when I run the "plan" it's showing me that my resource needs an update but it's not showing which param generates that : 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.server03 will be updated in-place
  ~ resource "vsphere_virtual_machine" "server03" {
        boot_delay                              = 0
        boot_retry_delay                        = 10000
        boot_retry_enabled                      = false
        change_version                          = "2019-05-29T12:18:08.724629Z"
        cpu_hot_add_enabled                     = true
        cpu_hot_remove_enabled                  = false
        cpu_limit                               = -1
        cpu_performance_counters_enabled        = false
        cpu_reservation                         = 0
        cpu_share_count                         = 8000
        cpu_share_level                         = "normal"
        custom_attributes                       = {
            "101" = "04/08/2019 01:12:21"
        }
        datastore_id                            = "datastore-xxx"
        default_ip_address                      = "x.x.x.x"
        efi_secure_boot_enabled                 = false
        enable_disk_uuid                        = false
        enable_logging                          = false
        ept_rvi_mode                            = "automatic"
        extra_config                            = {}
        firmware                                = "bios"
        folder                                  = "VMs"
        force_power_off                         = true
        guest_id                                = "ubuntu64Guest"
        guest_ip_addresses                      = []
        host_system_id                          = "host-xxx"
        hv_mode                                 = "hvAuto"
        id                                      = "xxxxxxxxxxxxxxxxxxxx"
        latency_sensitivity                     = "normal"
        memory                                  = 4096
        memory_hot_add_enabled                  = true
        memory_limit                            = -1
        memory_reservation                      = 0
        memory_share_count                      = 40960
        memory_share_level                      = "normal"
        migrate_wait_timeout                    = 30
        moid                                    = "vm-xxxx"
        name                                    = "server03"
        nested_hv_enabled                       = false
        num_cores_per_socket                    = 1
        num_cpus                                = 8
        reboot_required                         = false
        resource_pool_id                        = "resgroup-xxx"
        run_tools_scripts_after_power_on        = true
        run_tools_scripts_after_resume          = true
        run_tools_scripts_before_guest_reboot   = false
        run_tools_scripts_before_guest_shutdown = true
        run_tools_scripts_before_guest_standby  = true
        scsi_bus_sharing                        = "noSharing"
        scsi_controller_count                   = 1
        scsi_type                               = "pvscsi"
        shutdown_wait_timeout                   = 3
        swap_placement_policy                   = "inherit"
        sync_time_with_host                     = false
        tags                                    = []
        uuid                                    = "xxxxxxxxxxxxxxxxxxx"
        vapp_transport                          = []
        vmware_tools_status                     = "guestToolsNotRunning"
        vmx_path                                = "server03/server03.vmx"
        wait_for_guest_net_timeout              = 5

        clone {
            linked_clone  = false
            template_uuid = "xxxxxxxxxxxxxxxxxxxxxx"
            timeout       = 30

            customize {
                dns_server_list = [
                    "x.x.x.x",
                    "x.x.x.x",
                ]
                dns_suffix_list = [
                    "dns.com",
                    "dns2.com",
                ]
                ipv4_gateway    = "x.x.x.x"
                timeout         = 10

                linux_options {
                    domain       = "internal.domain"
                    host_name    = "server03"
                    hw_clock_utc = true
                }

                network_interface {
                    dns_server_list = []
                    ipv4_address    = "x.x.x.x"
                    ipv4_netmask    = 24
                    ipv6_netmask    = 0
                }
            }
        }

        disk {
            attach           = false
            datastore_id     = "datastore-xxxx"
            device_address   = "scsi:0:0"
            disk_mode        = "persistent"
            disk_sharing     = "sharingNone"
            eagerly_scrub    = true
            io_limit         = -1
            io_reservation   = 0
            io_share_count   = 1000
            io_share_level   = "normal"
            keep_on_remove   = false
            key              = 2000
            label            = "server03.vmdk"
            path             = "server03/server03.vmdk"
            size             = 10
            thin_provisioned = false
            unit_number      = 0
            uuid             = "xxxxxxxxxxxxxxxxxxxxxx"
            write_through    = false
        }
        disk {
            attach           = false
            datastore_id     = "datastore-xxxx"
            device_address   = "scsi:0:1"
            disk_mode        = "persistent"
            disk_sharing     = "sharingNone"
            eagerly_scrub    = false
            io_limit         = -1
            io_reservation   = 0
            io_share_count   = 1000
            io_share_level   = "normal"
            keep_on_remove   = false
            key              = 2001
            label            = "server03_data.vmdk"
            path             = "server03/server03_1.vmdk"
            size             = 300
            thin_provisioned = true
            unit_number      = 1
            uuid             = "xxxxxxxxxxxxxxxxxxxxxxxxx"
            write_through    = false
        }

        network_interface {
            adapter_type          = "vmxnet3"
            bandwidth_limit       = -1
            bandwidth_reservation = 0
            bandwidth_share_count = 50
            bandwidth_share_level = "normal"
            device_address        = "pci:0:7"
            key                   = 4000
            mac_address           = "xx:xx:xx:xx:xx:xx"
            network_id            = "network-xxx"
            use_static_mac        = false
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

With TF 0.11 it was showing something like that : 
```  
~ resource "vsphere_virtual_machine" "server03" {
[...]
        disk {
            label            = "server03.vmdk"
            path             = "server03/server03.vmdk"
        ~  size             = "10" -> "20"

```

Thanks

**Comment by molleafauss** [comment] 2019-09-05 17:04
I have the same issue upgrading from 0.11.13 to 0.12.8. 

Tried upgrading some simple scripts that manages a fleet of EC2 instances (9 instances), those are a testing environment so they're not so mission .
As per the guide, terraform plan on 0.11 shows no changes to be applied.

I had to tweak a few things in the converted scripts to have terraform 0.12.8 be happy about them (mostly related to concatenating lists properly as with 0.11 we were using the interpolation) and the resulting terraform plan is showing me that only 5 out of the 9 instances need "update in place", but only the name is marked like in the OP output and I didn't see in the tf plan any other field that looked like they needed chaning (might it be the security group order which is fooling it?).

We're looking to upgrade terraform to 0.12 across all our infrastructure but we need to be sure that no changes would be applied, resulting in no possible downtime, but this spurious difference is not reassuring.

**Comment by apparentlymart** [comment] 2022-09-28 02:04
Hi all! Sorry for the long silence here.

I remember us fixing a bug just like this at some point after v0.12 was released. It was caused by some historical baggage where the providers were still using some v0.11-oriented ideas of what values are considered to be equal whereas the Terraform CLI UI was using the new v0.12 type system and its definition of equality. We addressed this later by making the CLI UI include some heuristics to ignore differences that seem to be a result of the providers using legacy SDK code.

I don't have a specific record of what fixed this because it was a long time ago, but the fact that this issue has been quiet for many years leads me to believe it is indeed fixed, and so I'm going to close it just in the interests of tidying up.

If someone finds this after seeing a similar behavior in a more modern version of Terraform, please open a new issue about it! Terraform's internals have changed enough since v0.12 that I expect we'll need to start over with a fresh set of debugging information to explain similar behavior, and it will probably have a different root cause than whatever was causing this in Terraform v0.12.

Thanks!

**Closed by apparentlymart** 2022-09-28 02:04 UTC
Labels: bug, cli, v0.12
