### ISSUE TITLE
Error applying plan: diffs didn't match during apply.

### ISSUE THREAD

**Issue by miguelaferreira** [hashicorp/terraform#16660] opened 2017-11-15 10:12 UTC
I've encountered this error while building a consul cluster using the `consul_cluster` module from https://github.com/hashicorp/terraform-aws-consul/.

In my configuration I create a VPC with a module from the registry.

Here's the error:
```
Error: Error applying plan:

1 error(s) occurred:

* module.consul_cluster.aws_autoscaling_group.autoscaling_group: aws_autoscaling_group.autoscaling_group: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.10.8
    Resource ID: aws_autoscaling_group.autoscaling_group
    Mismatch reason: attribute mismatch: availability_zones.1126047633
2017-11-15T11:05:15.435+0100 [DEBUG] plugin: plugin process exited: path=/Users/miguel/gitlab.com/utilus/nlo-gateway/infrastructure/environments/bug/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.2.0_x4
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tag.1679389794.key":*terraform.ResourceAttrDiff{Old:"", New:"Name", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cooldown":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.1679389794.value":*terraform.ResourceAttrDiff{Old:"", New:"consul-cluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.1679389794.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "termination_policies.0":*terraform.ResourceAttrDiff{Old:"", New:"Default", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "desired_capacity":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "termination_policies.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "max_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "wait_for_capacity_timeout":*terraform.ResourceAttrDiff{Old:"", New:"10m", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.1126047633":*terraform.ResourceAttrDiff{Old:"", New:"eu-central-1a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "force_delete":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_grace_period":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "launch_configuration":*terraform.ResourceAttrDiff{Old:"", New:"${aws_launch_configuration.launch_configuration.name}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_type":*terraform.ResourceAttrDiff{Old:"", New:"EC2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.4144501229.key":*terraform.ResourceAttrDiff{Old:"", New:"consul-cluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.4144501229.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "metrics_granularity":*terraform.ResourceAttrDiff{Old:"", New:"1Minute", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "protect_from_scale_in":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "min_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.#":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.4144501229.value":*terraform.ResourceAttrDiff{Old:"", New:"consul-cluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"force_delete":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.4144501229.key":*terraform.ResourceAttrDiff{Old:"", New:"consul-cluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "launch_configuration":*terraform.ResourceAttrDiff{Old:"", New:"consul-cluster-20171115100339197800000004", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "default_cooldown":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.3362608707":*terraform.ResourceAttrDiff{Old:"", New:"subnet-b33d91d8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.4144501229.value":*terraform.ResourceAttrDiff{Old:"", New:"consul-cluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "min_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "termination_policies.0":*terraform.ResourceAttrDiff{Old:"", New:"Default", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.#":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "protect_from_scale_in":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "desired_capacity":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "metrics_granularity":*terraform.ResourceAttrDiff{Old:"", New:"1Minute", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.1679389794.key":*terraform.ResourceAttrDiff{Old:"", New:"Name", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_grace_period":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "max_size":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.1679389794.value":*terraform.ResourceAttrDiff{Old:"", New:"consul-cluster", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.1679389794.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tag.4144501229.propagate_at_launch":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "termination_policies.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_type":*terraform.ResourceAttrDiff{Old:"", New:"EC2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "wait_for_capacity_timeout":*terraform.ResourceAttrDiff{Old:"", New:"10m", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

### Terraform Version
`Terraform v0.10.8`

### Terraform Configuration Files
```hcl
variable "aws_access_key_id" {}

variable "aws_secret_access_key" {}

variable "aws_region" {
  default = "eu-central-1"
}

provider "aws" {
  region     = "eu-central-1"
  access_key = "${var.aws_access_key_id}"
  secret_key = "${var.aws_secret_access_key}"
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "bug"
  cidr = "10.0.0.0/16"

  azs             = ["eu-central-1"]
  public_subnets  = ["10.0.1.0/24"]
  private_subnets = ["10.0.101.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = false

  enable_dns_support   = true
  enable_dns_hostnames = true
}

variable "consul_ami_id" {
  default = "ami-92de5efd"
}

variable "consul_ssh_public_key_file" {
  default = "consul-id_rsa.pub"
}

resource "aws_key_pair" "consul" {
  key_name   = "consulKey"
  public_key = "${file(var.consul_ssh_public_key_file)}"
}

module "consul_cluster" {
  source = "github.com/hashicorp/terraform-aws-consul//modules/consul-cluster?ref=v0.0.5"

  cluster_name = "consul-cluster"
  cluster_size = 1

  availability_zones = ["eu-central-1a"]

  vpc_id     = "${module.vpc.vpc_id}"
  subnet_ids = "${module.vpc.private_subnets}"

  allowed_inbound_cidr_blocks = ["10.0.101.0/24"]
  allowed_ssh_cidr_blocks     = ["10.0.1.0/24"]

  ami_id        = "${var.consul_ami_id}"
  instance_type = "t2.micro"

  ssh_key_name = "${aws_key_pair.consul.key_name}"

  cluster_tag_key   = "consul-cluster"
  cluster_tag_value = "consul-cluster"

  user_data = <<-EOF
              #!/bin/bash
              /opt/consul/bin/run-consul --server --cluster-tag-key consul-cluster
              EOF

  root_volume_delete_on_termination = true
}

```

### Debug Output
https://gist.github.com/miguelaferreira/a7aee93c44b2c5ccf6286b9c8aed8ac4

### Crash Output
No `crash.log` file.

### Expected Behavior
Terraform terminates without errors and a VPC with a running Consul server should have been created.

### Actual Behavior
Terraform stopped applying the plan due to error.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan -out terraform.tfplan -var-file secrets.tfvars`
3. `terraform apply terraform.tfplan`

### Important factoids
If I run `terraform plan -out terraform.tfplan -var-file secrets.tfvars` followed by `terraform apply terraform.tfplan` again, a new plan is created and applied successfully.

The new plan:
```
Terraform will perform the following actions:

  + module.consul_cluster.aws_autoscaling_group.autoscaling_group
      id:                                 <computed>
      arn:                                <computed>
      default_cooldown:                   <computed>
      desired_capacity:                   "1"
      force_delete:                       "false"
      health_check_grace_period:          "300"
      health_check_type:                  "EC2"
      launch_configuration:               "consul-cluster-20171115100339197800000004"
      max_size:                           "1"
      metrics_granularity:                "1Minute"
      min_size:                           "1"
      name:                               <computed>
      protect_from_scale_in:              "false"
      tag.#:                              "2"
      tag.1679389794.key:                 "Name"
      tag.1679389794.propagate_at_launch: "true"
      tag.1679389794.value:               "consul-cluster"
      tag.4144501229.key:                 "consul-cluster"
      tag.4144501229.propagate_at_launch: "true"
      tag.4144501229.value:               "consul-cluster"
      termination_policies.#:             "1"
      termination_policies.0:             "Default"
      vpc_zone_identifier.#:              "1"
      vpc_zone_identifier.3362608707:     "subnet-b33d91d8"
      wait_for_capacity_timeout:          "10m"


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------
```

**Comment by dhait** [comment] 2017-11-15 15:40
I receive the same error message periodically.

**Comment by jbardin** [comment] 2017-11-16 01:43
This is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/2117 and https://github.com/terraform-providers/terraform-provider-aws/issues/1990.

The diff don't match when setting both the `availability_zones` and `vpc_zone_identifier` for the autoscaling group, which are redundant.

**Closed by jbardin** 2017-11-16 01:43 UTC
Labels: bug, provider/aws

**Comment by miguelaferreira** [comment] 2017-11-20 10:15
@jbardin Thanks for the explanation. Is there a good reason for the consul module to set those two variables?

https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/main.tf#L16
