### ISSUE TITLE
Terraform Not Interpolating values but complains if you use working syntax

### ISSUE THREAD

**Issue by TrueCyberAxe** [hashicorp/terraform#27632] opened 2021-01-29 18:12 UTC
Using terraform 0.14 but pretty sure this was an issue on 0.12 and 0.13 hence why this syntax was used in the first place
 
Any nested map items such as this do not get interpolated if i replace "${sub_name}" with sub_name, it results in a map that has all keys with the name sub_name
 
```
  sub_ranges = distinct(flatten([
    for name, value in local.cidrs : [
      for sub_name, sub_value in value : { "${sub_name}" = sub_value }
    ]
  ]))
```

local.cidrs is a map of the following format

```
cidrs = {
  "app 1" = "0.0.0.0/0"
  "app 2" = {
    "range #1" = "0.0.0.0/0"
    "range #2" = "0.0.0.0/0"
    "range #3" = "0.0.0.0/0"
  }
}
```

Which Results in

```
Warning: Interpolation-only expressions are deprecated

  on .terraform/modules/security_groups/main.tf line 49, in locals:
  49:       for sub_name, sub_value in value : { "${sub_name}" = sub_value }

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
```

**Comment by jbardin** [comment] 2021-01-29 18:17
Thanks for filing the issue @TrueCyberAxe !

Marking as a duplicate of #27037

**Closed by jbardin** 2021-01-29 18:17 UTC
