### ISSUE TITLE
Azure VM creation with enable_accelerated_networking on Standard_L8s_v3 - inconsistent OverconstrainedAllocationRequest error

### ISSUE THREAD

**Issue by VolumezTech** [hashicorp/terraform#33794] opened 2023-09-04 13:41 UTC
### Terraform Version

```shell
Terraform v1.5.5
on linux_amd64
```

### Terraform Configuration Files

```
resource "azurerm_public_ip" "this" {
  count = var.num_of_vm

  sku                 = "Standard"
  name                = "${var.vm_type}-publicIP-${count.index}"
  location            = var.resource_group_location
  resource_group_name = var.resource_group_name
  zones               = [var.zones[count.index % length(var.zones)]]
  allocation_method   = "Static"
}

resource "azurerm_network_interface" "this" {
  count = var.num_of_vm

  name                          = "nic-${var.vm_type}-${count.index}"
  location                      = var.resource_group_location
  resource_group_name           = var.resource_group_name
  enable_accelerated_networking = true

  ip_configuration {
    name                          = "pubConfiguration"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.this["${count.index % var.num_of_vm}"].id
  }

  depends_on = [
    azurerm_public_ip.this
  ]
}

resource "azurerm_linux_virtual_machine" "this" {
  count = var.num_of_vm

  name                         = "${var.vm_type}-${count.index}"
  resource_group_name          = var.resource_group_name
  location                     = var.resource_group_location
  size                         = "Standard_L8s_v3"
  proximity_placement_group_id = var.rdma_mode ? null : var.proximity_pg_group_list[count.index % length(var.zones)]
  availability_set_id          = var.rdma_mode ? var.availability_set_id_list[count.index % length(var.zones)] : null
  source_image_id              =  var.source_image_id
  admin_username               = var.ssh_username
  network_interface_ids = [
    element(azurerm_network_interface.this.*.id, count.index),
  ]

  admin_ssh_key {
    username   = var.ssh_username
    public_key = var.public_key
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  depends_on = [
    azurerm_public_ip.this,
    azurerm_network_interface.this
  ]
}

```

### Debug Output
PLAN:

   + module.media-vm.azurerm_network_interface.this[7] will be created
   resource "azurerm_network_interface" "this" {
       applied_dns_servers           = (known after apply)
       dns_servers                   = (known after apply)
       enable_accelerated_networking = true
       enable_ip_forwarding          = false
       id                            = (known after apply)
       internal_dns_name_label       = (known after apply)
       internal_domain_name_suffix   = (known after apply)
       location                      = "eastus"
       mac_address                   = (known after apply)
       name                          = (known after apply)
       private_ip_address            = (known after apply)
       private_ip_addresses          = (known after apply)
       resource_group_name           = (known after apply)
       virtual_machine_id            = (known after apply)
       ip_configuration {
           gateway_load_balancer_frontend_ip_configuration_id = (known after apply)
           name                                               = "pubConfiguration"
           primary                                            = (known after apply)
           private_ip_address                                 = (known after apply)
           private_ip_address_allocation                      = "Dynamic"
           private_ip_address_version                         = "IPv4"
           public_ip_address_id                               = (known after apply)
           subnet_id                                          = (known after apply)
        }
    }
    
    
   + module.media-vm.azurerm_linux_virtual_machine.this[7] will be created
   resource "azurerm_linux_virtual_machine" "this" {
       admin_username                                         = "adminuser"
       allow_extension_operations                             = true
       bypass_platform_safety_checks_on_user_schedule_enabled = false
       computer_name                                          = (known after apply)
       disable_password_authentication                        = true
       extensions_time_budget                                 = "PT1H30M"
       id                                                     = (known after apply)
       location                                               = "eastus"
       max_bid_price                                          = -1
       name                                                   = (known after apply)
       network_interface_ids                                  = (known after apply)
       patch_assessment_mode                                  = "ImageDefault"
       patch_mode                                             = "ImageDefault"
       platform_fault_domain                                  = -1
       priority                                               = "Regular"
       private_ip_address                                     = (known after apply)
       private_ip_addresses                                   = (known after apply)
       provision_vm_agent                                     = true
       proximity_placement_group_id                           = (known after apply)
       public_ip_address                                      = (known after apply)
       public_ip_addresses                                    = (known after apply)
       resource_group_name                                    = (known after apply)
       size                                                   = "Standard_L8s_v3"
      .
      .
      .

Error: waiting for creation of Linux Virtual Machine: (Name "7684-vm-3meq9-media-4" / Resource Group "7684-vm-3meq9-rg"): Code="OverconstrainedAllocationRequest" Message="Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - Networking Constraints (such as Accelerated Networking or IPv6)\n  - VM Size\n"

  with module.media-vm.azurerm_linux_virtual_machine.this[4],
  on ../../../modules/azure/vm/main.tf line 32, in resource "azurerm_linux_virtual_machine" "this":
  32: resource "azurerm_linux_virtual_machine" "this" {

Error: waiting for creation of Linux Virtual Machine: (Name "7684-vm-3meq9-media-6" / Resource Group "7684-vm-3meq9-rg"): Code="OverconstrainedAllocationRequest" Message="Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - Networking Constraints (such as Accelerated Networking or IPv6)\n  - VM Size\n"

  with module.media-vm.azurerm_linux_virtual_machine.this[6],
  on ../../../modules/azure/vm/main.tf line 32, in resource "azurerm_linux_virtual_machine" "this":
  32: resource "azurerm_linux_virtual_machine" "this" {

### Expected Behavior

Standard_L8s_v3 supports enable_accelerated_networking - I expect successful creation

### Actual Behavior

Inconsistent failures:

Error: waiting for creation of Linux Virtual Machine: (Name "7684-vm-3meq9-media-4" / Resource Group "7684-vm-3meq9-rg"): Code="OverconstrainedAllocationRequest" Message="Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - Networking Constraints (such as Accelerated Networking or IPv6)\n  - VM Size\n"

  with module.media-vm.azurerm_linux_virtual_machine.this[4],
  on ../../../modules/azure/vm/main.tf line 32, in resource "azurerm_linux_virtual_machine" "this":
  32: resource "azurerm_linux_virtual_machine" "this" {

When I change the VM size to Standard_L8as_v3 - this issue is not recreating

### Steps to Reproduce

1. terraform init
2. terraform apply
3. This issue is inconsistent - sometimes it works

**Comment by kmoe** [comment] 2023-09-04 15:51
Thanks for the issue. This seems like it is most likely an issue with the AzureRM provider or the Azure API. Please consider opening an issue on the Azure provider issue tracker (https://github.com/hashicorp/terraform-provider-azurerm) or asking this question on the community forums (https://discuss.hashicorp.com).

That said, I am curious about a couple of things...
1. You mentioned that "When I change the VM size to Standard_L8as_v3 - this issue is not recreating". However, that seems to be the size used throughout the example. Are you saying you have inconsistent results with this VM size, or is there another size you have tried?
2. The two `depends_on` blocks in the configuration seem redundant: Terraform can already work out these dependencies from the references (e.g. `azurerm_linux_virtual_machine.this` depends on `azurerm_network_interface.this.*.id`). They can be removed.

**Comment by VolumezTech** [comment] 2023-09-05 08:46
Hey @kmoe , thanks for your reply. 

1. In my example, I use Standard_L8s_v3 not Standard_L8as_v3, with Standard_L8as_v3 the issue is not recreating. We are working with Standard_L8s_v3 daily; the issue that started to occur using this size is not consistent. When we moved to Standard_L8as_v3 we did not see this issue anymore. I suspect that something is not consistent with Standard_L8s_v3 that fails to support an accelerated network interface.

2. Thanks, I will remove. 
My issue with Terraform in that case is when this error occurs - I'm not able to retry the creation of the environment, error message:

Error: A resource with the ID "/subscriptions/******/resourceGroups/7684-vm-3meq9-rg/providers/Microsoft.Compute/virtualMachines/7684-vm-3meq9-media-4" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_linux_virtual_machine" for more information.

**Comment by kmoe** [comment] 2023-09-05 10:52
Thanks for the reply. 

>I suspect that something is not consistent with Standard_L8s_v3 that fails to support an accelerated network interface.

That does seem like it is the problem. Terraform Core does not behave differently based on these values - they are passed to the provider, so the inconsistent behaviour is located either there or in the Azure cloud itself.

Since this is not a bug in Terraform Core, I am closing this issue.

**Closed by kmoe** 2023-09-05 10:52 UTC
Labels: bug, new
