### ISSUE TITLE
Terraform fmt does not work as expected with comments

### ISSUE THREAD

**Issue by juancarlosjr97** [hashicorp/terraform#30278] opened 2021-12-30 22:05 UTC
# Issue

Terraform does not format correctly a file if contains comments

# Environment

- Terraform v0.12.31 and v1.1.2

# Reproduce

1. Create a file named `test.tfvars` 
2. Enter the following
```
# First group
id         = ""
aws_region = "eu-west-1"

# Second group
id_2         = ""
aws_region_2 = "eu-west-1"
```
3. Run `terraform fmt test.tfvars` and format as follow

```
# First group
id         = ""
aws_region = "eu-west-1"

# Second group
id_2         = ""
aws_region_2 = "eu-west-1"
```

The expected result is 

```
# First group
id           = ""
aws_region   = "eu-west-1"

# Second group
id_2         = ""
aws_region_2 = "eu-west-1"
```

**Comment by sudoforge** [comment] 2021-12-31 21:35
Why would it be useful to remove the newline here? Also, see #21360.

**Comment by juancarlosjr97** [comment] 2021-12-31 21:38
Actually the expected result should be 

```
# First group
id           = ""
aws_region   = "eu-west-1"

# Second group
id_2         = ""
aws_region_2 = "eu-west-1"

```

In opinion it should disregard the comments but keeping them in the formatted code

**Comment by sudoforge** [comment] 2022-01-01 01:20
I'm not following what your goal with this issue is. In your original comment, you state that the following input:

```tf
# First group
id         = ""
aws_region = "eu-west-1"

# Second group
id_2         = ""
aws_region_2 = "eu-west-1"
```

which is already formatted properly, and as such, is ignored by `terraform fmt`.

In your original comment, you state that the expected result is to remove the newline, like so:

```tf
# First group
id           = ""
aws_region   = "eu-west-1"
# Second group
id_2         = ""
aws_region_2 = "eu-west-1"
```

And then, in your second comment, you state that the expected result should instead be:

```tf
# First group
id         = ""
aws_region = "eu-west-1"

# Second group
id_2         = ""
aws_region_2 = "eu-west-1"
```

... which exactly matches what `terraform fmt` does (it leaves the file alone, because it is properly formatted).

Can you please clarify your expected and actual results?

**Comment by sudoforge** [comment] 2022-01-01 01:26
And as of now, you have updated your original comment so that the expected result includes the newline, which means all three code blocks are identical.

**Comment by juancarlosjr97** [comment] 2022-01-01 01:29
Sorry, @sudoforge, I did not want to update my original comment but I think I should have done that initially.

I noticed that terraform does not format if there is a comment in between lines, the blank line was a mistake, the actual point I was trying to do was the alignment of the variables and the `=` to have the look of a table.

Original file

```
# First group
id         = ""
aws_region = "eu-west-1"

# Second group
id_2         = ""
aws_region_2 = "eu-west-1"
```

`terraform fmt` will ignore the file as it appears to be fine but the alignment is not correct.

By deleting the comment the leaving the file as follow

```
id         = ""
aws_region = "eu-west-1"
id_2         = ""
aws_region_2 = "eu-west-1"
```

`terraform fmt` formats to the following

```
id           = ""
aws_region   = "eu-west-1"
id_2         = ""
aws_region_2 = "eu-west-1"
```

Is that clearer?

**Comment by juancarlosjr97** [comment] 2022-01-01 01:33
> And as of now, you have updated your original comment so that the expected result includes the newline, which means all three code blocks are identical.

No, they have different alignment and the correct format should be all the `=` under the same 'column'

**Comment by sudoforge** [comment] 2022-01-01 01:36
> terraform fmt will ignore the file as it appears to be fine but the alignment is not correct.

I think there's a slight misunderstanding here; `terraform fmt` aligns each section independently. In the original file, you have two sections (a "section" is a block of code, with multiple sections being separated by a newline and/or comment).

For example, the following two files _both have two sections_:

```tf
foo = 1
bar = 2

baz  = 3
quux = 4
```

```tf
foo = 1
bar = 2
# some comment
baz  = 3
quux = 4
```

Each section is aligned independently.

---

> No, they have different alignment and the correct format should be all the = under the same 'column'

You're right, I missed that the alignment crossed over both sections. Hopefully the explanation above explains that what you're seeing is intended behavior.

**Comment by juancarlosjr97** [comment] 2022-01-01 01:45
Thank you @sudoforge 

Yes, it does format and aligns by sections separated by comments. However, as the `*.tfvars` are only to define values to variables, I would think that should align all of them under the same structure in my opinion. It is (I think) an improvement of how the terraform formats the `*.tfvars`

**Comment by apparentlymart** [comment] 2022-01-04 01:05
Hi @juancarlosjr97! Thanks for this feedback.

As @sudoforge noted, the intended behavior for `terraform fmt` is to align the equals signs only for _consecutive single-line arguments_, and so anything other than a single-line argument will interrupt the alignment group and cause each group to be separately aligned.

A further example not discussed yet is an a multi-line argument, which also breaks up a group because it introduces its own nested indentation/alignment context:

```hcl
foo       = 1
long_name = 2
short = {
  foo = 3
  a   = 4
}
boop = 5
```

These alignment decisions can never suit everyone's preferences, and so we tend to just make a best effort to produce reasonable results for as many inputs as possible and, in situations where there isn't an obviously right answer, prefer to follow prominent style choices that have been present in Terraform's documentation for many years, so that anyone following the documented examples will typically not see any proposed formatting changes.

While I certainly can see an argument that some `.tfvars` files might benefit from a "global" alignment of equals signs, changing that now doesn't seem consistent with the design principles we outlined in [the `terraform fmt` documentation](https://www.terraform.io/cli/commands/fmt) to minimize unhelpful churn:

> We don't consider new formatting rules in `terraform fmt` to be a breaking change in new versions of Terraform, but we do aim to minimize changes for configurations that are already following the style examples shown in the Terraform documentation.

For that reason, I'm going to close this. If the alignment decision made by `terraform fmt` is a very significant annoyance for you then I would suggest to not use `terraform fmt`, but it's typically most pragmatic to just accept what `terraform fmt` does as the idiomatic style even though it may differ from your personal preferences, just as how Go programmers typically follow the `gofmt` style even though its rules might not have been exactly what they would've chosen.

Thanks again!

**Closed by apparentlymart** 2022-01-04 01:05 UTC
Labels: bug, new
