### ISSUE TITLE
Error: Resource node has no configuration attached

### ISSUE THREAD

**Issue by vanmash** [hashicorp/terraform#32045] opened 2022-10-19 18:30 UTC
### Terraform Version

```shell
Terraform v1.3.2
on windows_amd64
```

### Terraform Configuration Files

azurerm_log_analytics_workspace.log deleted from the configuration

### Debug Output

2022-10-19T18:20:37.0897421Z ##[section]Starting: TerraformTaskV32
2022-10-19T18:20:37.1079607Z ==============================================================================
2022-10-19T18:20:37.1080082Z Task         : Terraform
2022-10-19T18:20:37.1080882Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
2022-10-19T18:20:37.1081446Z Version      : 3.209.19
2022-10-19T18:20:37.1081761Z Author       : Microsoft Corporation
2022-10-19T18:20:37.1082181Z Help         : [Learn more about this task](https://aka.ms/AAf0uqr)
2022-10-19T18:20:37.1082684Z ==============================================================================
2022-10-19T18:20:37.5854318Z [command]C:\a\_tool\terraform\1.3.2\x64\terraform.exe providers
2022-10-19T18:20:38.8644365Z 
2022-10-19T18:20:38.8645193Z Providers required by configuration:
2022-10-19T18:20:38.8645563Z .
2022-10-19T18:20:38.8646112Z ├── provider[registry.terraform.io/hashicorp/azurerm]
2022-10-19T18:20:38.8647788Z └── provider[registry.terraform.io/hashicorp/random]
2022-10-19T18:20:38.8648052Z 
2022-10-19T18:20:38.8648402Z Providers required by state:
2022-10-19T18:20:38.8648796Z 
2022-10-19T18:20:38.8649204Z     provider[registry.terraform.io/hashicorp/azurerm]
2022-10-19T18:20:38.8649450Z 
2022-10-19T18:20:38.8649856Z     provider[registry.terraform.io/hashicorp/random]
2022-10-19T18:20:38.8650090Z 
2022-10-19T18:20:38.8694112Z [command]C:\a\_tool\terraform\1.3.2\x64\terraform.exe apply -no-color -auto-approve C:\a\4\s/terraform/46546.tfplan
2022-10-19T18:20:51.1860395Z 2022-10-19T18:20:51.183Z [ERROR] vertex "azurerm_key_vault_secret.workspace_id" error: Resource node has no configuration attached
2022-10-19T18:20:51.1862597Z 2022-10-19T18:20:51.184Z [ERROR] vertex "azurerm_key_vault_secret.workspace_key" error: Resource node has no configuration attached
2022-10-19T18:20:51.1870730Z azurerm_log_analytics_workspace.log: Destroying... [id=/subscriptions/<>resourceGroups/rg-temp-stage/providers/Microsoft.OperationalInsights/workspaces/log-temp-stage]
2022-10-19T18:20:54.0331825Z azurerm_log_analytics_workspace.log: Destruction complete after 3s
2022-10-19T18:20:55.4054280Z 
2022-10-19T18:20:55.4055136Z Error: Resource node has no configuration attached
2022-10-19T18:20:55.4055376Z 
2022-10-19T18:20:55.4055804Z The graph node for azurerm_key_vault_secret.workspace_id has no configuration
2022-10-19T18:20:55.4056586Z attached to it. This suggests a bug in Terraform's apply graph builder;
2022-10-19T18:20:55.4056877Z please report it!
2022-10-19T18:20:55.4056971Z 
2022-10-19T18:20:55.4057198Z Error: Resource node has no configuration attached
2022-10-19T18:20:55.4057334Z 
2022-10-19T18:20:55.4057577Z The graph node for azurerm_key_vault_secret.workspace_key has no
2022-10-19T18:20:55.4057929Z configuration attached to it. This suggests a bug in Terraform's apply graph
2022-10-19T18:20:55.4058213Z builder; please report it!
2022-10-19T18:20:55.4709589Z ##[error]Error: The process 'C:\a\_tool\terraform\1.3.2\x64\terraform.exe' failed with exit code 1
2022-10-19T18:20:55.4747398Z ##[section]Finishing: TerraformTaskV32

### Expected Behavior

azurerm_log_analytics_workspace.log was removed from the configuration and should be destroyed

### Actual Behavior

terraform apply fails

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

run in Azure DevOps pipeline using Terraform task

Successful on the second run

**Comment by jbardin** [comment] 2022-10-19 21:48
Duplicate of #31850

**Closed by jbardin** 2022-10-19 21:48 UTC
Labels: bug, duplicate

**Comment by vanmash** [comment] 2022-10-20 07:31
Hey James @jbardin, 
#31850 is closed, does it mean it is solved already?

**Comment by jbardin** [comment] 2022-10-20 16:45
Yes, the issue has been closed. You can see the closing PR #31990 linked from the bottom of the issue.
