### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 99** [hashicorp/terraform#32837] opened 2023-03-14 00:44 UTC
### Terraform Version

```shell
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.58.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

### Terraform Configuration Files

```
...terraform config...
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/distiller/project/project/internal/logging/panic.go:55 +0x170
panic({0x107100560, 0x10883ae00})
        /usr/local/go/src/runtime/panic.go:890 +0x258
github.com/mitchellh/colorstring.(*Colorize).Color(0x0, {0x1068aa94c, 0x16})
        /Users/distiller/go/pkg/mod/github.com/mitchellh/colorstring@v0.0.0-20190213212951-d06e56a500db/colorstring.go:81 +0x144
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.renderPrimitiveValue({0x0?, 0x0?}, {{0x0?, 0x0?}}, {0x0, 0x1, 0x0, 0x1, 0x1})
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/primitive.go:56 +0x1b8
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.primitiveRenderer.RenderHuman({{}, {0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}}}, {{0x1074c9bb8?, 0x14004086d50?}, 0x4162d38?, ...}, ...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/primitive.go:39 +0xc0
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/diff.go:51
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.objectRenderer.RenderHuman({{}, 0x14004086cf0?, 0x70?}, {{0x1074c9b90?, 0x14002190b90?}, 0x4163298?, 0x40?}, 0x3, {0x0, 0x1, ...})
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/object.go:86 +0xb70
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/diff.go:51
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.objectRenderer.RenderHuman({{}, 0x14004027d40?, 0xb0?}, {{0x1074c9b90?, 0x140022793b0?}, 0x74b1c40?, 0x1?}, 0x2, {0x0, 0x1, ...})
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/object.go:86 +0xb70
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/diff.go:51
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.primitiveRenderer.renderStringDiffAsJson({{}, {0x106ffd380, 0x14000d93310}, {0x106ffd380, 0x14000d93ae0}, {{0x1074e27a0, 0x140001ae299}}}, {{0x1074c9bb8?, 0x14003cfacf0?}, 0x2000?, ...}, ...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/primitive.go:211 +0x22c
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.primitiveRenderer.renderStringDiff({{}, {0x106ffd380, 0x14000d93310}, {0x106ffd380, 0x14000d93ae0}, {{0x1074e27a0, 0x140001ae299}}}, {{0x1074c9bb8?, 0x14003cfacf0?}, 0x1a5c068?, ...}, ...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/primitive.go:84 +0x15c
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.primitiveRenderer.RenderHuman({{}, {0x106ffd380, 0x14000d93310}, {0x106ffd380, 0x14000d93ae0}, {{0x1074e27a0, 0x140001ae299}}}, {{0x1074c9bb8?, 0x14003cfacf0?}, 0x1a5c1e8?, ...}, ...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/primitive.go:36 +0x4f0
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/diff.go:51
github.com/hashicorp/terraform/internal/command/jsonformat/computed/renderers.blockRenderer.RenderHuman({{}, 0x14003cfabd0, {0x14003cfbe90, 0x14003cfbec0, 0x14003cfbef0, 0x14003cfbf20, 0x14003cfbe00, 0x14003cfbe30, 0x14003cfbe60}}, {{0x1074c9b18?, ...}, ...}, ...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/renderers/block.go:93 +0x10a4
github.com/hashicorp/terraform/internal/command/jsonformat/computed.Diff.RenderHuman(...)
        /Users/distiller/project/project/internal/command/jsonformat/computed/diff.go:51
github.com/hashicorp/terraform/internal/command/jsonformat.State.renderHumanStateModule({{0x10687c0ff, 0x3}, {{0x14000157800, 0xe, 0x10}, {0x0, 0x0}, {0x14000a2ac00, 0xc, 0x10}}, ...}, ...)
        /Users/distiller/project/project/internal/command/jsonformat/state.go:66 +0x7bc
github.com/hashicorp/terraform/internal/command/jsonformat.State.renderHumanStateModule({{0x10687c0ff, 0x3}, {{0x14000157800, 0xe, 0x10}, {0x0, 0x0}, {0x14000a2ac00, 0xc, 0x10}}, ...}, ...)
        /Users/distiller/project/project/internal/command/jsonformat/state.go:77 +0x190
github.com/hashicorp/terraform/internal/command/jsonformat.Renderer.RenderHumanState({0x140008026a8?, 0x14000401ae0?, 0x80?}, {{0x10687c0ff, 0x3}, {{0x14000157800, 0xe, 0x10}, {0x0, 0x0}, ...}, ...})
        /Users/distiller/project/project/internal/command/jsonformat/renderer.go:89 +0x240
github.com/hashicorp/terraform/internal/command/views.(*ShowHuman).Display(0x140001240c0, 0x0?, 0x0?, 0x14001a5d9f8?, 0x1?)
        /Users/distiller/project/project/internal/command/views/show.go:96 +0x178
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0x140003c5a40, {0x140001b2010?, 0x7?, 0xffffffffffffffff?})
        /Users/distiller/project/project/internal/command/show.go:59 +0x23c
github.com/mitchellh/cli.(*CLI).Run(0x140001f4a00)
        /Users/distiller/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x4a8
main.realMain()
        /Users/distiller/project/project/main.go:315 +0x12f0
main.main()
        /Users/distiller/project/project/main.go:58 +0x1c

### Expected Behavior

output from the `terraform show` execution 

### Actual Behavior

the project failed while running ` terraform show`

### Steps to Reproduce

=>terraform init 
=> terraform validate -var-file envs/dev/us-west-2/dev1/vars.tfvars 
 =>terraform show

**Comment by jbardin** [comment] 2023-03-14 12:21
Duplicate of #32833

**Closed by jbardin** 2023-03-14 12:21 UTC
Labels: bug, new
