### ISSUE TITLE
Bug: “runtime error: index out of range” when trying to run `terraform apply`

### ISSUE THREAD

**Issue by alexwlchan** [hashicorp/terraform#20940] opened 2019-04-05 11:43 UTC
I got an error while trying to run `terraform apply`, and the instructions told me to open a bug report. The error doesn’t reproduce if I run the same operation. This is the bit of `terraform apply` that crashed:

```
panic: runtime error: index out of range

goroutine 39981 [running]:
github.com/hashicorp/terraform/terraform.(*EvalWriteStateDeposed).Eval.func1(0xc0031add40, 0xc001d15110, 0xc000099f00)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval_state.go:165 +0x12d
github.com/hashicorp/terraform/terraform.writeInstanceToState(0x484aec0, 0xc000494270, 0xc000099f00, 0x13, 0xc0002bcf00, 0x9, 0xc000eeb020, 0xf, 0x0, 0x0, ...)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval_state.go:210 +0x1a5
github.com/hashicorp/terraform/terraform.(*EvalWriteStateDeposed).Eval(0xc003f77860, 0x484aec0, 0xc000494270, 0x2, 0x2, 0xc00450e480, 0x34)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval_state.go:160 +0xcb
github.com/hashicorp/terraform/terraform.EvalRaw(0x47c23a0, 0xc003f77860, 0x484aec0, 0xc000494270, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0039199a0, 0x484aec0, 0xc000494270, 0x2, 0x2, 0xc0042961c0, 0x34)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x9c
github.com/hashicorp/terraform/terraform.EvalRaw(0x47c21c0, 0xc0039199a0, 0x484aec0, 0xc000494270, 0x5b, 0x0, 0x0, 0x5b)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc0044a0540, 0x484aec0, 0xc000494270, 0x2, 0x2, 0xc004296180, 0x34)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x47c20a0, 0xc0044a0540, 0x484aec0, 0xc000494270, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc003919860, 0x484aec0, 0xc000494270, 0x2, 0x2, 0xc0042960c0, 0x34)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x9c
github.com/hashicorp/terraform/terraform.EvalRaw(0x47c21c0, 0xc003919860, 0x484aec0, 0xc000494270, 0x3a9c020, 0x718d422, 0x37b9b60, 0xc00449b7f0)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.Eval(0x47c21c0, 0xc003919860, 0x484aec0, 0xc000494270, 0xc003919860, 0x47c21c0, 0xc003919860, 0xc00210bdb0)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x3cebf40, 0xc0036f20a0, 0x0, 0x0)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xbab
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0036f0af0, 0x3cebf40, 0xc0036f20a0, 0xc0013cb1c0)
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x33b
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/private/tmp/terraform-20190311-48945-1cw2gue/terraform-0.11.13/src/github.com/hashicorp/terraform/dag/walk.go:310 +0xa4f
```

### Terraform Version

```console
$ tf --version
Terraform v0.11.13
```

I assume that's the latest version, but 0.11.13 doesn't actually appear in the changelog…

### Terraform Configuration Files

See https://github.com/wellcometrust/storage-service/tree/0271bbdeb0fa28f3b6010697592435bfad447373/terraform

### Debug Output

I don't have debug output from a failing operation, but here's the output from `terraform plan` and `terraform apply`: https://gist.githubusercontent.com/alexwlchan/589e7246eb413f5182e1f139b21e8f07/raw/41168fc022ac276092baafd036f31181ed08a0e2/tf%2520plan%2520+%2520tf%2520apply%2520output.txt

### Crash Output

https://gist.github.com/alexwlchan/589e7246eb413f5182e1f139b21e8f07

### Expected Behavior

I run `terraform apply terraform.plan` and it applies my changes without crashing.

### Actual Behavior

It crashed with the attached crash log.

### Steps to Reproduce

I can't reproduce this bug.

**Comment by danieldreier** [comment] 2020-06-17 00:24
@alexwlchan I appreciate you reporting this, and I apologize for not having responded more quickly. We are working through our backlog of crash reports, and have gotten to your report.

Are you still seeing this problem on 0.12.26 or on the 0.13.0 beta?

**Comment by alexwlchan** [comment] 2020-06-17 13:44
> Are you still seeing this problem on 0.12.26 or on the 0.13.0 beta?

I don’t have a repro scenario, so no.

**Comment by danieldreier** [comment] 2020-06-17 21:20
@alexwlchan thanks - I am going to close this out because without a reproduction case, it's super unlikely that this will lead to engineering work, so there's not much point to keeping it open. There are a few other issues open with a similar-looking error:

https://github.com/hashicorp/terraform/issues/24824
https://github.com/hashicorp/terraform/issues/23677

I'm going to assume that those sufficiently capture it, and they are a little closer to the reproduction case and a newer version of TF. If you do run into this again please let us know and link back to this issue.

**Closed by danieldreier** 2020-06-17 21:20 UTC
Labels: bug, core, crash, v0.11
