### ISSUE TITLE
support for GCP regional instance groups

### ISSUE THREAD

**Issue by jaibheem** [hashicorp/terraform#9787] opened 2016-11-01 22:30 UTC
Hello,

I am trying out Terraform for the GCP. how ever I don't see option to create regional instance groups. (This is the Beta feature though)

Resource:
google_compute_instance_group_manager

https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#creating_a_regional_managed_instance_group

is this going to addressed ?

**Comment by cblecker** [comment] 2016-11-01 23:13
duplicate of #8866

**Comment by stack72** [comment] 2016-11-02 15:24
Hi @jaibheem 

Thanks for the report here - as @cblecker has pointed out, this is a duplicate. Please use the other issue for any tracking

Thanks

Paul

**Closed** 2016-11-02 15:24 UTC
Labels: enhancement, provider/google-cloud

**Comment by jaibheem** [comment] 2016-12-08 18:27
hello @stack72 @cblecker I see it is now GA : https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#creating_a_regional_managed_instance_group 

do we have plan for making it available in Terraform?
