### ISSUE TITLE
State getting uploaded to s3 when it shouldn't be

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform#4783] opened 2016-01-21 19:35 UTC
Terraform v0.6.9

```
remote state config -backend-config='name=user/foo' 
remote state config -backend-config='name=user/bar'
``` 

uploads the wrong state file. To make the above work you current have to do 

```
remote state config -backend-config='name=user/foo' 
rm -rf .terraform 
remote state config -backend-config='name=user/bar'
```

**Comment by phinze** [comment] 2016-01-21 19:39
Just chatted w/ @jjshoe in IRC about this.

Basically, the behavior you'd expect when switching between two distinct remote config setups is that you're "reconfiguring" so you should get a clean slate.

The current behavior is that the original state cache ends up being pushed to the newly configure remote,  which is not what you'd expect or want.

We should make it work so that a "reconfigure" ignores the local state cache and pulls a fresh copy from the remote.

**Comment by apparentlymart** [comment] 2016-01-22 03:16
I was working on a related thing over in #4618.

I took a different path there than what you suggested here: I changed the rules to say that it's simply prohibited to switch directly from one state to another via the Terraform commands, so if you want to switch over to a different state it will fail unless you first delete the `.terraform/terraform.tfstate` file. My motivation was to prevent ever overwriting an existing object that is unrelated to the current state, presuming that moving states around was the common case.

However, I can see that this doesn't really help with @jjshoe's issue here since it would make the first case fail with an error.

This ticket is making me reconsider my conclusion that moving states around is the common case. Switching from one remote state to another is presumably common in cases where the config is parameterized to deploy to multiple environments and you want to switch the remote state so that each environment has its own. In which case, I'd do what @phinze described but additionally add a `terraform remote move` command that has the same syntax as `terraform remote config` but yet behaves as follows:

* Read from the *new* remote state backend.
* If data is successfully returned, fail with an error to prevent the existing data at that location being overwritten by the state. Proceed only if the read returned an error.
* Write the state to the *new* remote state backend.
* If that succeeds, delete the state from the old remote state backend so that it won't be accidentally used in future.

This would then allow the *current* state to be moved to a new location, while `terraform remote config` would take on the new role of safely switching from one state to another.

This new approach seems superior and simpler than what I had initially devised. However, I'd still quite like to add the concept of "lineage" to the state even if it's only useful in manually debugging weird cases where states have somehow got mixed up, which has happened to my team a few times.

**Comment by jjshoe** [comment] 2016-02-05 17:33
@phinze @apparentlymart - I'm happy to test off develop any fix for this you might have. This is a common work flow for multiple environment setups with remote state. We're at high risk to keep triggering this.

**Comment by rgabo** [comment] 2016-03-15 18:07
Hello all, glad to see a discussion about the intended behavior. For the time being we are performing an `rm .terraform/terraform.tfstate` before switching between different remote states so that Terraform initializes a blank state and pulls the remote state.

I think the use case is quite common if the same Terraform project is used for identical environments. The same holds for users of Atlas as a remote state. Even if most of the planning and applying happens in Atlas, we should be able to plan and inspect changes locally and for that switching between Atlas environments should be seamless.

Equally nice would be to somehow incorporate Terraform variables into the whole story, but that's outside of this issue's scope.

**Comment by mitchellh** [comment] 2016-10-27 17:19
I'm going to close this issue. I think its a bug but a bigger remote state UX refactor will happen at some point for Terraform 0.9 which will likely throw this on its head. The pull by @apparentlymart above makes it so you at least get an error now which is GREAT, so its not magically going to nuke things (which is NOT GREAT).

**Closed by mitchellh** 2016-10-27 17:19 UTC
Labels: bug, core
