### ISSUE TITLE
depends_on between modules "taints" data sources which forces resource recreation

### ISSUE THREAD

**Issue by zoltan-toth-mw** [hashicorp/terraform#27858] opened 2021-02-22 10:20 UTC
### Terraform Version

```shell
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

module dependent:
```terraform
variable "vpc_name" {
}

data "aws_vpc" "selected" {
  tags = {
    Name = var.vpc_name
  }
}

resource "aws_security_group" "service" {
  name = "demo-sec-group"
  vpc_id = data.aws_vpc.selected.id
}

```

module ecr copy:
```terraform
variable "application_version" {
}

resource "null_resource" "ecr_copy_on_demand" {
  triggers = {
    app_version = var.application_version
  }

  provisioner "local-exec" {
    command = <<EOF
    echo "hello world"
EOF
  }
}

output "action_id" {
  value = null_resource.ecr_copy_on_demand.id
}
```

demo.tf
```terraform
module "demo" {
  source = "./dependent"
  vpc_name = "..." // VPC NAME GOES HERE

  depends_on = [module.ecr_copy.action_id]
}

module "ecr_copy" {
  source = "./ecr_copy"
  // after first successful apply, increase this and the vpc data will be lost
  application_version = "1.0"
}

terraform {

  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~>3.27"
    }
  }
}

```

### Expected Behavior

Only truly changing resources should be updated.

### Actual Behavior

When _dependtant_ module depends on the _ecr_copy_ module and the _ecr_copy_ module changes then data sources in _dependant_ module become lets say tainted, their output value becomes unknown and all the dependent resources are recreated.

Here the VPC id becomes an unknown value and forces the security group recreation. 

```terraform
  # module.demo.data.aws_vpc.selected will be read during apply
  # (config refers to values not yet known)
 <= data "aws_vpc" "selected"  {
      ~ arn                     = "arn:aws:ec2:eu-west-1:CONFIDENTIAL" -> (known after apply)
      ~ cidr_block              = "10.88.0.0/16" -> (known after apply)
      ~ cidr_block_associations = [
          - {
              - association_id = "vpc-cidr-assoc-CONFIDENTIAL"
              - cidr_block     = "10.88.0.0/16"
              - state          = "associated"
            },
        ] -> (known after apply)
      ~ default                 = false -> (known after apply)
      ~ dhcp_options_id         = "dopt-CONFIDENTIAL" -> (known after apply)
      ~ enable_dns_hostnames    = true -> (known after apply)
      ~ enable_dns_support      = true -> (known after apply)
      ~ id                      = "vpc-CONFIDENTIAL" -> (known after apply)
      ~ instance_tenancy        = "default" -> (known after apply)
      + ipv6_association_id     = (known after apply)
      + ipv6_cidr_block         = (known after apply)
      ~ main_route_table_id     = "rtb-CONFIDENTIAL" -> (known after apply)
      ~ owner_id                = "CONFIDENTIAL" -> (known after apply)
      ~ state                   = "available" -> (known after apply)
    }

  # module.demo.aws_security_group.service must be replaced
-/+ resource "aws_security_group" "service" {
      ~ arn                    = "arn:aws:ec2:eu-west-1:CONFIDENTIAL/sg-07bc459b2c2199b30" -> (known after apply)
      ~ id                     = "sg-07bc459b2c2199b30" -> (known after apply)
      ...
      ~ vpc_id                 = "vpc-CONFIDENTIAL" -> (known after apply) # forces replacement
        # (2 unchanged attributes hidden)
    }

  # module.ecr_copy.null_resource.ecr_copy_on_demand must be replaced
-/+ resource "null_resource" "ecr_copy_on_demand" {
      ~ id       = "6809436620957317904" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "app_version" = "1.0" -> "1.1"
        }
    }

Plan: 2 to add, 0 to change, 2 to destroy.

```

### Steps to Reproduce

Provide an existing vpc name for the demo module as an input argument.
```
terraform init
terraform apply
```
Change the _application_version_ argument for module _ecr_copy_
```
terraform plan
```

### Additional Context

If I remove the module dependency then only the truly changing resources are planned for modification.

**Comment by jbardin** [comment] 2021-02-22 14:11
Hi @zoltan-toth-mw,

This is a duplicate of #26383. If a data source uses `depends_on` to reference a resource, and that resource has changes, the data source cannot be updated until after the changes have been applied. 

Thanks!

**Closed by jbardin** 2021-02-22 14:11 UTC
Labels: bug, new
