### ISSUE TITLE
Ambiguous provider error message when provider configuration is missing

### ISSUE THREAD

**Issue by Zawadidone** [hashicorp/terraform#32784] opened 2023-03-06 15:16 UTC
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/dmachard/http-client v0.0.3
+ provider registry.terraform.io/elastic/ec v0.5.1
+ provider registry.terraform.io/elastic/elasticstack v0.5.0
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/google v4.55.0
+ provider registry.terraform.io/hashicorp/google-beta v4.55.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v3.13.0
+ provider registry.terraform.io/integrations/github v5.18.0
+ provider registry.terraform.io/pagerduty/pagerduty v2.2.1

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    pagerduty = {
        source  = "pagerduty/pagerduty"
        version = "~> 2.2.0"
      }
  }
}

#provider "pagerduty" {
#  token = data.vault_generic_secret.pagerduty.data["api_key"]
#}

data "pagerduty_user" "users" {
  email    = "example@example.com
}
```

### Debug Output

.

### Expected Behavior

Terraform should show more context about where the error came from. Preferably the location in the code but at least the relevant provider where the error occured. 

For example

```
╷
│ Error: Missing provider ....
[...]
│ 
│   with provider["registry.terraform.io/pagerduty/pagerduty"],
│   on providers line XXX, in provider "pagerduty":
```

### Actual Behavior

Terraform plan failed because of the not set provider configuration.

```
│ Error: Missing required argument
│ 
│ The argument "token" is required, but was not set.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

This also occurs when using the Github provider. 

It becomes really hard to debug this error without lacking context.

**Comment by alisdair** [comment] 2023-03-06 15:40
Hi @Zawadidone! Thanks for reporting this.

This is a duplicate of issue #28482, which contains an explanation and proposed solution. As a result I'm going to close this one.

**Closed by alisdair** 2023-03-06 15:40 UTC
Labels: bug, new

**Comment by Zawadidone** [comment] 2023-03-06 15:47
Okay thanks!
