### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ninijule** [hashicorp/terraform#24255] opened 2020-03-03 14:39 UTC
### Terraform Version

```
0.12.21
```

### Terraform Configuration Files

```hcl
data "vsphere_datacenter" "dc" {
  name = "Datacenter"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = data.vsphere_datacenter.dc.id
}


data "vsphere_network" "network1" {
  name          = "#####"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network2" {
  name          = "####"
  datacenter_id = data.vsphere_datacenter.dc.id
}


data "vsphere_network" "network3" {
  name          = "####"
  datacenter_id = data.vsphere_datacenter.dc.id
}


data "vsphere_resource_pool" "pool" {}

resource "vsphere_virtual_machine" "vm" {
  name             = "####"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = 1
  num_cores_per_socket = 1
  memory   = 512
  guest_id = "ubuntu64Guest"


network_interface{
network_id = data.vsphere_network.network1.id
use_static_mac = true
mac_address = "####"
adapter_type = "vmxnet3"
}




network_interface{
network_id = data.vsphere_network.network2.id
use_static_mac = true
mac_address = "####"
adapter_type = "vmxnet3"
}

network_interface{
network_id = data.vsphere_network.network3.id
use_static_mac = true
mac_address = "####"
adapter_type = "vmxnet3"
}



disk{
          name = "#######-######.vmdk"

          size = "10"

          thin_provisioned = "true"


   unit_number = 0
}


disk{
datastore_id = data.vsphere_datastore.datastore.id
attach = true
label = "####"
unit_number = "1"
path = "external_disk/#########################"
}


disk{
datastore_id = data.vsphere_datastore.datastore.id
attach = true
label = "####"
unit_number = "2"
path = "external_disk/#######################"
}


disk{
datastore_id = data.vsphere_datastore.datastore.id
attach = true
label = "####"
unit_number = "3"
path = "external_disk/#############################"
}



  cdrom{
  datastore_id = data.vsphere_datastore.datastore.id
  path = "/####################################"
  }

  wait_for_guest_net_timeout = 0
  force_power_off = true
  shutdown_wait_timeout = 1
 
```

### Expected Behavior

Creation of the virtual machine
### Actual Behavior

a crash or a memory corrupted, i don't know 
### Steps to Reproduce

"terraform"

### References

I don't know what happening when i try to launch terraform i got the error "Segmentation fault" i don't know what is this.
I have try terraform 64 bits and 32 bits but nothing change
I'm using Ubuntu Server 18.04.4 LTS on Virtual Machine VMware Pro.

**Comment by jbardin** [comment] 2020-03-04 16:50
Hi @ninijule 

Sorry you're having an issue with this. Is there any output at all when you run terraform with `TF_LOG=trace`?

**Comment by ninijule** [comment] 2020-03-04 17:54
i have try but i don't have any output when i try to just to launch terraform with just : 
./terraform 
i got the error "Segmentation fault" 
i have try to get the log output i have nothing :( i really don't know what is the problem....

**Comment by jbardin** [comment] 2020-03-04 18:52
Hi @ninijule 

If you are getting a segfault immediately before terraform can write any logs to the output, it's likely a compatibility problem with your system itself. Start by making sure you have an official binary, with the correct OS and architecture. You can also try `TF_FORK=0`, which may output more information, or trace the execution to determine what syscalls were being made. 

Since this doesn't look like an issue with terraform itself, I'm going to close this out for now. If you do end up with a reproducible crash, feel free to add the relevant info here so that we can further debug the issue.

**Closed by jbardin** 2020-03-04 18:52 UTC
Labels: bug, crash
