### ISSUE TITLE
Output is not working after upgrade to 0.9.2

### ISSUE THREAD

**Issue by vincentkwok** [hashicorp/terraform#13454] opened 2017-04-07 10:32 UTC
I have been using `output` from v0.8. Recently upgraded to 0.9.2 and set backend, output value could not be not added after applying resources changes. Any idea?

```yml
output "test" {
    value = "12345"
}
```

Thanks

**Comment by jbardin** [comment] 2017-04-07 15:02
Hi @vincentkwok,

Do you mean that the output doesn't show up in the state?
Was there any error during apply?
Does the output show up in `terraform show`?

**Comment by vincentkwok** [comment] 2017-04-10 01:52
@jbardin

No error. It applies complete. Newly defined AWS resources changes are executed properly and tfstate in backend is updated corresponding resources as well. 

`terraform show` only displays the output defined previously. Newly defined output are missing, in both post-apply command console output & the backend state file.

**Comment by jbardin** [comment] 2017-04-25 18:17
@vincentkwok,

Unfortunately I'm not able to reproduce what you're describing here. Can you provide an example configuration that shows the missing output?

**Comment by apparentlymart** [comment] 2017-05-08 22:21
Hi @vincentkwok,

Since we weren't able to reproduce this problem, there is unfortunately nothing we can do here. :confounded:

I'm going to close this now, but please do let us know if you are able to provide more information that might allow us to reproduce the problem and I'm happy to reopen this.

**Closed by apparentlymart** 2017-05-08 22:21 UTC
Labels: core, waiting-response
