### ISSUE TITLE
terraform import command does not import resource within null_resource local-exec in terraform file, unlike  same command imports from shell directly

### ISSUE THREAD

**Issue by kaganmersin** [hashicorp/terraform#30076] opened 2021-12-03 11:00 UTC
### Terraform Version

```
Terraform v1.0.11
on linux_amd64
```

### Terraform Configuration Files

```terraform
resource "null_resource" "apply_state" {
  triggers = {
    build_number = "${timestamp()}"
  }  


  provisioner "local-exec" {
    command = "terraform import module.state.azurerm_resource_group.rg_main /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx"
  }
}
```

### Debug Output

```
null_resource.apply_state (local-exec): {
null_resource.apply_state (local-exec):   "version": 4,
null_resource.apply_state (local-exec):   "terraform_version": "1.0.11",
null_resource.apply_state (local-exec):   "serial": 1,
null_resource.apply_state (local-exec):   "lineage": "xxxxxx-xxxxx-xxxx-xxxxx-xxxxx",
null_resource.apply_state (local-exec):   "outputs": {},
null_resource.apply_state (local-exec):   "resources": [
null_resource.apply_state (local-exec):     {
null_resource.apply_state (local-exec):       "module": "module.state",
null_resource.apply_state (local-exec):       "mode": "managed",
null_resource.apply_state (local-exec):       "type": "azurerm_resource_group",
null_resource.apply_state (local-exec):       "name": "rg_main",
null_resource.apply_state (local-exec):       "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
null_resource.apply_state (local-exec):       "instances": [
null_resource.apply_state (local-exec):         {
null_resource.apply_state (local-exec):           "schema_version": 0,
null_resource.apply_state (local-exec):           "attributes": {
null_resource.apply_state (local-exec):             "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx",
null_resource.apply_state (local-exec):             "location": "westeurope",
null_resource.apply_state (local-exec):             "name": "xxxxxxxxx",
null_resource.apply_state (local-exec):             "tags": {
null_resource.apply_state (local-exec):               "environment": "xxxxxx",
null_resource.apply_state (local-exec):               "managedBy": "terraform"
null_resource.apply_state (local-exec):             },
null_resource.apply_state (local-exec):             "timeouts": {
null_resource.apply_state (local-exec):               "create": null,
null_resource.apply_state (local-exec):               "delete": null,
null_resource.apply_state (local-exec):               "read": null,
null_resource.apply_state (local-exec):               "update": null
null_resource.apply_state (local-exec):             }
null_resource.apply_state (local-exec):           },
null_resource.apply_state (local-exec):           "sensitive_attributes": [],
null_resource.apply_state (local-exec):           "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
null_resource.apply_state (local-exec):         }
null_resource.apply_state (local-exec):       ]
null_resource.apply_state (local-exec):     }
null_resource.apply_state (local-exec):   ]
null_resource.apply_state (local-exec): }
null_resource.apply_state (local-exec): 2021-12-03T13:39:32.834+0300 [DEBUG] Azure Backend Response for https://xxxxxxxxx.blob.core.windows.net/xxxxxxxx/foundation.terraform.tfstate:
null_resource.apply_state (local-exec): HTTP/1.1 201 Created
null_resource.apply_state (local-exec): Content-Length: 0
null_resource.apply_state (local-exec): Content-Md5: xxxxxxxxxx==
null_resource.apply_state (local-exec): Date: Fri, 03 Dec 2021 10:39:32 GMT
null_resource.apply_state (local-exec): Etag: "xxxxxxxxxxxxxx"
null_resource.apply_state (local-exec): Last-Modified: Fri, 03 Dec 2021 10:39:32 GMT
null_resource.apply_state (local-exec): Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
null_resource.apply_state (local-exec): X-Ms-Request-Id: xxxxxx-xxxx-xxxx-xxxx-xxxxx
null_resource.apply_state (local-exec): X-Ms-Request-Server-Encrypted: true
null_resource.apply_state (local-exec): X-Ms-Version: 2018-11-09
null_resource.apply_state (local-exec):
null_resource.apply_state (local-exec): Import successful!
```
### Expected Behavior

Below azurerm_resource_group state appear after execute following command inside shell directly; 
 terraform import module.state.azurerm_resource_group.rg_main /subscriptions/xxxxxxxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/xxxxxxxx
```
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_resource_group",
      "name": "rg_main ",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "/subscriptions/xxxxxx-xxxx-xxxx-xxx-xxxx/resourceGroups/xxxxxxx",
            "location": "xxxxxxx",
            "name": "xxxxxx",
            "tags": {
              "environment": "dev",
              "managedBy": "terraform"
            },
            "timeouts": {
              "create": null,
              "delete": null,
              "read": null,
              "update": null
            }
          },
          "sensitive_attributes": [],
          "private": "xxxxxxxxxxxxxxxxxxx="
        }
      ]
    }

```

### Actual Behavior

There is no resource group state in below state file
```

{
  "version": 4,
  "terraform_version": "1.0.11",
  "serial": 1,
  "lineage": "xxxxxxx-xxxxxx-xxxxx-xxxxx-xxxxx",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "null_resource",
      "name": "apply_state",
      "provider": "provider[\"registry.terraform.io/hashicorp/null\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "xxxxxxxxx",
            "triggers": {
              "build_number": "2021-12-03T10:39:01Z"
            }
          },
          "sensitive_attributes": [],
          "private": "xxxxxxx=="
        }
      ]
    },
    {
      "module": "module.state",
      "mode": "data",
      "type": "azurerm_subscription",
      "name": "subscription",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "display_name": "xxxxxxx",
            "id": "/subscriptions/xxxxxxx-xxxx-xxxx-xxxxx-xxxxxx",
            "location_placement_id": "Public_2014-09-01",
            "quota_id": "EnterpriseAgreement_2014-09-01",
            "spending_limit": "Off",
            "state": "Enabled",
            "subscription_id": "xxxxxxxx-xxxxxxxxx-xxxxx-xxxx-xxxx",
            "tags": {},
            "tenant_id": "xxxxxxx",
            "timeouts": null
          },
          "sensitive_attributes": []
        }
      ]
    },
    {
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_management_lock",
      "name": "rg_main",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": []
    },
    {
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_monitor_diagnostic_setting",
      "name": "sa_diagnostics",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": []
    },
    {
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_monitor_diagnostic_setting",
      "name": "sablob_diagnostics",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": []
    },
    {
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_storage_account",
      "name": "state",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": []
    },
    {
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_storage_account_network_rules",
      "name": "network_rules",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": []
    },
    {
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_storage_container",
      "name": "content",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": []
    },
    {
      "module": "module.state",
      "mode": "managed",
      "type": "azurerm_storage_encryption_scope",
      "name": "storage_encryption",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": []
    }
  ]
}
```

### Steps to Reproduce

```
terraform apply  -auto-approve -lock=false
```

**Comment by jbardin** [comment] 2021-12-03 15:53
Hi @kaganmersin,

Thanks for filing the issue, but Terraform here is working as designed. You cannot safely run multiple instance of terraform concurrently, because the last instance to exit is going to write its state. Using `-lock=false` is bypassing the built-in safety mechanisms to prevent this from occurring, causing the imported data to be lost.

Since Terraform is working as intended here, I'm going to close the issue. We already have open issues for configuration driven import, so if you are interested in the state of that type of feature you can follow #26364.

Thanks!

**Closed by jbardin** 2021-12-03 15:53 UTC
Labels: bug, new
