### ISSUE TITLE
trailing new line in key vault after using heredoc syntax

### ISSUE THREAD

**Issue by sanjeevsharma-1** [hashicorp/terraform#26313] opened 2020-09-21 13:47 UTC
we are trying to create keyvault secret using Terraform at runtime and we after building the code, it looks something like this

resource "azurerm_key_vault_secret" "AggregatorsKeySpaceName" {
name = "AggregatorsKeySpaceName"
value = <<EOT
KV_SECRET_VALUE
EOT
key_vault_id = azurerm_key_vault.keyvault.id
}

the issue is that, heredoc syntax adds a trailing new line at the end of the "value", hence the value is stored something like this

![image](https://user-images.githubusercontent.com/68319188/93774313-bdc1fb80-fc3e-11ea-96fb-66e3f37cd8e6.png)

As you can in the image, the secret value 5 is trailed with new line and it kind of changes the meaning of the secret value in case of passwords and other KV secret stored.

**Comment by apparentlymart** [comment] 2020-09-23 16:15
Hi @sanjeevsharma-1,

What you've observed here is the intended behavior of the multi-line "heredoc" syntax: it produces multi-line strings with a newline at the end of each line.

If you want to produce a string without a trailing newline then the options for doing that are:
* Use the quoted string syntax, like `"KV_SECRET_VALUE"`.
* Use [the `trimspace` function](https://www.terraform.io/docs/configuration/functions/trimspace.html) on the heredoc result to remove the trailing newline (which will also remove any _leading_ whitespace):

    ```hcl
      value = trimspace(
        <<-EOT
          KV_SECRET_VALUE
        EOT
      )
    ```
* Use [the `chomp` function](https://www.terraform.io/docs/configuration/functions/chomp.html), which is a more specialized alternative to `trimspace` that _only_ removes newline characters from the end of the string, leaving other leading and trailing whitespace intact.

    ```hcl
      value = chomp(
        <<-EOT
          KV_SECRET_VALUE
        EOT
      )
    ```

Because the behavior you observed here is the intended behavior, I'm going to close this issue. If you have any follow-up questions about either of the alternative approaches I described above, please feel free to start a topic about it in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!

**Closed by apparentlymart** 2020-09-23 16:15 UTC
Labels: bug, new

**Comment by sanjeevsharma-1** [comment] 2020-09-23 19:29
thank you @apparentlymart 
we could not use the quoted string syntax, like "KV_SECRET_VALUE", as few of the secret value consisted of special characters like & or ` , which started giving issue.
we tried with chomp and trimpspace but our syntax was different when we tried.

we tried something like

 value =  <<-EOT
      chomp(KV_SECRET_VALUE)
    EOT

which actually kind of changed the meaning and we couldn't figure out the best way.

thank you for letting us know the correct syntax of using chomp and trimspace function, this helped us
