### ISSUE TITLE
Getting terraform.ResourceAttrDiff on 1/0 vs true/false when running terraform apply

### ISSUE THREAD

**Issue by hajhatten** [hashicorp/terraform#6152] opened 2016-04-13 09:41 UTC
Hello

I'm running Terraform v0.6.14

Been rewriting my states for a  POP in AWS.
The resources have all been created already, but I wanted to add more variables and couters to my state files.
All the resources parameters should be exactly the same, just defined proceduraly.

However, as i'm doing a terraform apply (with a refresh), it sets my attributes in the state files for booleans as strings, and apply apparently expects integers.

Running the same apply with -refresh=false, and manually setting every "true" / "false" to "1" or "0", runs fine.

For almost every single resource, i see the same error output from apply:

**Old:"true", New:"1",**

`Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"root_block_device.0.delete_on_termination":*terraform.ResourceAttrDiff{Old:"true", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "associate_public_ip_address":*terraform.ResourceAttrDiff{Old:"true", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "source_dest_check":*terraform.ResourceAttrDiff{Old:"true", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}`

Is there a way for me to get around this?

**Comment by robholland** [comment] 2016-04-15 09:35
This is a duplicate of #6005 (same symptom and presumably underlying cause).

**Comment by phinze** [comment] 2016-05-04 16:41
Consolidating with #6005 - see you there!

**Closed by phinze** 2016-05-04 16:41 UTC
Labels: bug, core
