### ISSUE TITLE
Error: fork/exec /vagrant/terraform/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.63.0_x4: permission denied issue

### ISSUE THREAD

**Issue by prakasha4devops** [hashicorp/terraform#25036] opened 2020-05-26 07:41 UTC
Plan: 0 to add, 0 to change, 9 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

Error: fork/exec /vagrant/terraform/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.63.0_x4: permission denied

**Comment by danieldreier** [comment] 2020-05-29 00:53
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). 

I'm closing this issue because it doesn't follow the issue template we provide. Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, and then the Terraform maintainers will review it. Thanks!

Beyond using the template, it would help if you could make the following improvements to your issue when you re-file it:

- use GitHub's [text formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax). You can do `markdown` and code formatting to make your code easier to read, which makes it easier for us to understand the issue. Please use markdown to format terraform code like this:
```HCL
resource "null_resource" "example" {
  name = "hello-world"
}
```
Please format terminal output for readability, like:
```shellsession
❯ terraform validate
Success! The configuration is valid.
```
- please provide all of the files involved in reproducing your example. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

**Closed by danieldreier** 2020-05-29 00:53 UTC
