### ISSUE TITLE
Terraform crashed [v1.3.4]

### ISSUE THREAD

**Issue by mdiianni** [hashicorp/terraform#32376] opened 2022-12-12 12:49 UTC
### Terraform Version

```shell
Terraform v1.3.4
```

### Terraform Configuration Files

I am afraid it is not possible for me to share that here.

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

attempt to write nil state to file
goroutine 91 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2143f40, 0x2b43210})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/states/statefile.writeStateV4(0xc00373da8c?, {0x2b46420?, 0xc003789180?})
/home/circleci/project/project/internal/states/statefile/version4.go:322 +0x15f8
github.com/hashicorp/terraform/internal/states/statefile.Write(0xc00373dc50?, {0x2b46420?, 0xc003789180?})
/home/circleci/project/project/internal/states/statefile/write.go:15 +0x45
github.com/hashicorp/terraform/internal/plans/planfile.Create({0x7ffe21fcdecc?, 0x60?}, {0xc0003ec1a8, 0xc00373de30, 0xc001a43b00, 0xc0041ea340, 0xc0009bb098})
/home/circleci/project/project/internal/plans/planfile/writer.go:103 +0x670
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000a38e60, {0x2b6adb8, 0xc00015ab40}, {0x2b6adb8, 0xc00015ab80}, 0xc0007c3c20, 0xc00015ab00)
/home/circleci/project/project/internal/backend/local/backend_plan.go:138 +0x905
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
/home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
/home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a
Operation failed: failed running terraform plan (exit 11)
```

### Expected Behavior

I was trying to run a destroy plan to clean up a playground environment no longer in use. I was expecting to simply run `terraform destroy` and apply the changes to remove any existing resources.

### Actual Behavior

While running a destroy plan, Terraform crashed showing the above message not able to perform any tasks.

### Steps to Reproduce

1. `terraform init`
2. `terraform destroy`

**Comment by jbardin** [comment] 2022-12-12 13:33
Duplicate of #32186

**Closed by jbardin** 2022-12-12 13:33 UTC
Labels: bug, new
