### ISSUE TITLE
[Feature Request] Add PutDestination and PutDestinationPolicy for CloudWatch Resources

### ISSUE THREAD

**Issue by jrlonan** [hashicorp/terraform#10485] opened 2016-12-02 05:42 UTC
### Use Case
I needed to send my CloudWatch logs on Account A to a Kinesis stream in Account B. AWS provides a guide for this:
http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CrossAccountSubscriptions.html

However, I noticed that Terraform does not have resources corresponding to `put-destination` and`put-destination-policy` as per AWS CLI commands, or a `destination` resource for CloudWatch logs

### Terraform Version
0.7.13

### Affected Resource(s)
AWS CloudWatch resources

### Important Factoids
There are no issues for CloudWatch logs and Kinesis stream in the same account ID. This feature only applies for cross-account situations

### References
AWS Cross-Account Data Sharing guide
http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CrossAccountSubscriptions.html

**Comment by Ninir** [comment] 2016-12-02 08:48
Duplicate of #9930! I started something locally, will keep you up-to-date

**Comment by stack72** [comment] 2016-12-02 11:42
Hi @jrlonan 

Thanks for the issue request - as @Ninir points out, the request exists so i am going to close this out as a duplicate

Please do keep an eye on that other issue though

Paul

**Closed** 2016-12-02 11:42 UTC
Labels: enhancement, provider/aws
