### ISSUE TITLE
cloudwatch log group not destroyed

### ISSUE THREAD

**Issue by ferrandinand** [hashicorp/terraform#14750] opened 2017-05-23 08:51 UTC
**Terraform Version**
Terraform v0.9.4

**Affected Resource(s)**
cloudwatch_log_group

**Terraform Configuration Files**
`resource "aws_cloudwatch_log_group" "vpcflow_log_group" {`
  `name = "vpcflow_log_group"`
`  retention_in_days = "${var.vpc_flow_logs_retention}"`
`}`

**Expected Behavior**
aws_cloudwatch_log_group should be removed when performing a destroy

**Actual Behavior**
Terraform destroy is showing that resource is destroyed but actually is still present.

**Steps to Reproduce**
`
$ terraform destroy
`
`
aws_cloudwatch_log_group.vpcflow_log_group: Refreshing state... (ID: vpcflow_log_group)
aws_cloudwatch_log_group.vpcflow_log_group: Destroying... (ID: vpcflow_log_group)
aws_cloudwatch_log_group.vpcflow_log_group: Destruction complete
`

Got to aws console/aws cli to check it is still there
`aws logs describe-log-groups`

**Comment by Graham-M** [comment] 2017-05-23 09:06
I'm delighted you added this, I've exactly the same issue with VPC flow logs (although lagging on v0.9.3).

This is my suspicion:
- I believe there's some buffering that goes on with flushing of the logs from VPC flow logs to CloudWatch.
- When you delete the log group, there's still some logs still to be flushed from the buffer.
- I have an IAM permission applied to the log groups that allows the `CreateLogGroup` permission.
- Once you delete the log group, this permission kicks back in, thus recreating the log group.

Possible fix, if it's applicable to you:
```resource "aws_iam_role_policy" "flowlogs_to_cloudwatch_policy" {
  name = "flowlogs-to-cloudwatch-policy-${var.vpc_id}"
  role = "${aws_iam_role.flowlogs_to_cloudwatch_role.id}"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
-       "logs:CreateLogGroup",        
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```

**Comment by ferrandinand** [comment] 2017-05-23 09:50
Hi Graham,

Thanks for answering. 
Currently we are already using the same policy you suggested but seems not to fix the issue.

 ```
data "aws_iam_policy_document" "flow_logs_policy" {
  statement {
    actions = [ 
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents",
      "logs:DescribeLogGroups",
      "logs:DescribeLogStreams"
    ]   

    resources = [ 
      "*" 
    ]   
  }
}

```

**Comment by Graham-M** [comment] 2017-05-23 09:58
Hi @ferrandinand, does it fix it if you remove the `"logs:CreateLogGroup",` permission?

**Comment by ferrandinand** [comment] 2017-05-23 11:58
Hi @Graham-M 
Sounds weird, because we need logs:CreateLogGroup permissions to create this, if not it won't be able to do it in terraform apply. isn't it?

How is this managed?

Thanks!

**Comment by Graham-M** [comment] 2017-05-23 12:22
Hi @ferrandinand, it looks like you explicitly create the `aws_cloudwatch_log_group` yourself in your terraform, which is therefore managed by the user which executes `terraform apply`.

All the IAM role which you give to the Flow Logs needs to do is to be able to write to that aforementioned log group, therefore it just needs `CreateLogStream` and `PutLogEvents` to write to the group.

**Comment by catsby** [comment] 2017-05-23 17:57
Hey @ferrandinand – I'm not able to reproduce this unfortunately. Are you able to capture any DEBUG logs (running terraform with `TF_LOG=trace` or similar) and see anything that raises suspicions regarding destroying the log group? 

I was apple to apply and destroy an example log group like you showed with no error, and it was removed. I'm curious if this only happens in a certain situation.

thanks!

**Comment by Graham-M** [comment] 2017-05-24 09:06
Hi @catsby, 

I'm able to reproduce, but I don't think it's a terraform issue, but more due to the nature of AWS and its APIs.  The debug log would simply show the log group being deleted and a clean exit from the `destroy`.

The issue would manifest the next time you came to `apply`.  The log group that you were trying to create would already exist due to logs being buffered and flushed by Flow Logs/CloudWatch, which had am IAM permission to recreate the log group as soon as you destroyed it manually.

**Comment by catsby** [comment] 2017-05-24 11:19
Ah I see, thanks for pointing that out 😄 
I'm going to close this for now, I agree it doesn't seem to be a Terraform issue.

Thanks!

**Closed by catsby** 2017-05-24 11:19 UTC
Labels: bug, provider/aws, waiting-response

**Comment by brandoncole** [comment] 2017-05-24 14:05
Nice @Graham-M!  Helped me too!
