### ISSUE TITLE
terraform.tfvars not being read

### ISSUE THREAD

**Issue by jmreicha** [hashicorp/terraform#2659] opened 2015-07-08 20:02 UTC
Just bumped to v0.6.0 and seeing the following error when attempting to use the `var-file=terrafrom.tfvars` command line flag.

```
here are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* module root: 3 error(s) occurred:

* resource 'aws_instance.terraform-test' config: unknown variable referenced: 'public-1a'. define it with 'variable' blocks
* resource 'aws_instance.terraform-test' config: unknown variable referenced: 'prod_internal'. define it with 'variable' blocks
* resource 'aws_instance.terraform-test' config: unknown variable referenced: 'prod_public'. define it with 'variable' blocks
```

Here is the relevant content of the terraform.tfvars file:

```
prod_public = "XXX"
prod_internal = "XXX"
public-1a = "XXX"
```

Here is the full command I am running:

```
terraform plan -var-file=./terraform.tfvars -input=false
```

I can get this working by creating `variables` blocks in main tf file but was hoping to abstract those variables out so that they could be reused.

**Comment by alexintel** [comment] 2015-07-09 18:35
+1

This is a major regression from the previous versions. terraform.tfvars should be read by default as previously.

**Comment by phinze** [comment] 2015-07-10 05:33
Sorry for the confusing behavior, but this was actually a correction of a bug we'd been harboring for several previous versions. Variables need to be declared with a `variable {}` block somewhere in your config.

The `terraform.tfvars` file will still be read for variable values, but declarations must appear in config.

**Comment by alexintel** [comment] 2015-07-13 17:23
I have variables.tf file with all variable declarations in the same directory as the main *.tf. And behavior for me as described. I though all *.tf files were being read at the same time and then final map is constructed out of those individual files.

Or do we need to put: 
variable "xxx" {}

block in the main *.tf file?

**Comment by phinze** [comment] 2015-07-14 00:45
@alexintel oh interesting! Reopening and I'll try to reproduce and follow up with you.

**Comment by jayjhan8** [comment] 2015-07-20 21:53
You're right @alexintel.  I have been scratching my head about this for a while and it seems like the variables need to be read in first.  What confused me was that terraform was applying fine locally but when I pushed, Atlas wouldn't be able to find these variables... anyway, I hope this helps.

**Comment by phinze** [comment] 2015-07-27 15:14
Hey folks,

Having trouble reproducing this... here'e my test case, perhaps you can point out what I'm missing:

```js
// ==> main.tf <==
resource "aws_vpc" "foo" {
  cidr_block = "${var.cidr}"
}

// ==> terraform.tfvars <==
cidr = "10.11.0.0/16"

// ==> variables.tf <==
variable "cidr" {}
```

With the above (and AWS provider config via env vars), both `terraform plan` and `terraform plan -var-file=./terraform.tfvars` work just fine for me.

**Comment by alexintel** [comment] 2015-07-27 17:32
Try the following:

skip:  terraform.tfvars file


```
// ==> variables.tf <==
variable "cidr" {
  default = "10.11.0.0/16"
}
```

Don't pass: -var-file=./terraform.tfvars on the command line. From what I understand from the documentation terraform.tfvars should be read automatically (and it is, in versions <=0.5.3).

I only use terraform.tfvars for things like AWS keys so I can exclude it from git.

**Comment by phinze** [comment] 2015-07-27 19:47
@alexintel yep that works for me too...

```js
// ==> main.tf <==
resource "aws_vpc" "foo" {
  cidr_block = "${var.cidr}"
}

// ==> variables.tf <==
variable "cidr" {
  default = "10.11.0.0/16"
}
```

Perhaps you're hitting #2613 - which was fixed in 0.6.1?

**Comment by Tanbouz** [comment] 2016-01-26 11:28
Terraform v0.6.9
Ubuntu 15.10 x64

Anyone experiencing inconsistencies? Sometimes it reads the *terraform.tfvars* (~2 out 10 times), other times it won't. Didn't even touch the Terraform project folder while testing it out. The inconsistent behaviour is similar even when using *-var-file=terraform.tfvars*
```
wizard@wonderland:~/projects/terraform$ terraform plan
Refreshing Terraform state prior to plan...**edit: cut**

The Terraform execution plan has been generated ....

Plan: 2 to add, 0 to change, 0 to destroy.


wizard@wonderland:~/projects/terraform$ terraform plan
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: 
```

**terraform.tfvars**
```
aws_access_key = "*****************"
aws_secret_key = "*****************"
aws_region = "eu-central-1"
```

**main.tf**
```
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}

provider "aws" {
    access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    region = "${var.aws_region}"
}
```

**Comment by DavidHooper** [comment] 2016-08-16 15:24
Interpolation doesn't work for default values. So this is an issue if you are loading a file into a variable.

**Comment by mitchellh** [comment] 2016-08-22 20:02
There hasn't been a response on this in quite awhile and I haven't heard of this happening recently in new issues either. Going to close as fixed, perhaps it was just fixed in between at some point. All mentioned issues here are fixed as well.

**Closed by mitchellh** 2016-08-22 20:02 UTC
Labels: bug, core

**Comment by gfisaris** [comment] 2016-10-10 12:47
I am facing the same problem..
Even though i have a terraform.tfvars file on my directory.. Atlas does not "read" it.

GitRepo: https://github.com/gfisaris/iac-terraform-aws-full_stack_template
Variables: https://github.com/gfisaris/iac-terraform-aws-full_stack_template/blob/master/terraform-variables.tf
Predefined Variables Values: https://github.com/gfisaris/iac-terraform-aws-full_stack_template/blob/master/terraform.tfvars

Could please anyone assist ?

**Comment by jmvbxx** [comment] 2016-10-27 17:24
Same problem here. `terraform.tfvars` in the same directory as `*.tf`.

`aws-vpc.tf` looks like this:
```
provider "aws" {
  access_key  = "${var.access_key}"
  secret_key  = "${var.secret_key}"
  region      = "${var.region}"
}
```

And `terraform.tfvars` looks like this:
```
access_key = "ABC..."
secret_key = "123..."
```

Running `terraform plan` generates the following:
```
* provider config 'aws': unknown variable referenced: 'access_key'. define it with 'variable' blocks
* provider config 'aws': unknown variable referenced: 'secret_key'. define it with 'variable' blocks
```

**Comment by mitchellh** [comment] 2016-10-27 17:26
You have to define the variable:

```
variable "access_key" {}
```

In your configuration

**Comment by michalmikolajczyk** [comment] 2016-11-28 00:16
just to clarify what @mitchellh suggested above, because it works:

in your `terraform.tfvars` file, you can have the variables defined, using the `key=value` structure:
```
foo = "bar"
```

but you still need to define the variables in your configuration file, e.g. `infra.tf`:

```
variable "foo" {}

resource "...
```

**Comment by jmvbxx** [comment] 2016-12-10 04:38
Thanks to both @mitchellh and @michalmikolajczyk :-)

**Comment by anilybba** [comment] 2017-01-27 22:01
Please tell me if this belongs somewhere else; I don't want to annoy or do the wrong thing here.

I'm new to terraform and trying it out for the first time, modeling my layout on the best-practices repo somewhat.

I have a terraform.tfvars file in a directory alongside my provider config. Something like:

terraform/
terraform/providers/vcloud/lab/lab.tf
terraform/providers/vcloud/lab/terraform.tfvars
terraform/lab.tf

in terraform/lab.tf I'm including "terraform/providers/vcloud/lab" as a module source. When I run terraform get in that top level directory, I get an error that one of my required variables is unset, even though that variable is defined in the terraform.tfvars file.

To test to see if the terraform.tfvars file was being read, I added a default to the problem variable in the nested tf file in the module and re-ran. Now the error highlights another required variable being unset. So it really seems like the nested terraform.tfvars file isn't being read. Is this expected?

**Comment by awcheng** [comment] 2018-01-22 21:27
This bug is not fixed (as of v0.11.2) and looks like it has been around for awhile.

There are multiple ticket/reference of this issue in different manifestation, see:
https://github.com/hashicorp/terraform/issues/15894
https://github.com/hashicorp/terraform/issues/15733

This workaround is to use -var-file to explicitly state tfvars file

**Comment by AnthonyWC** [comment] 2018-01-22 21:29
This bug is not fixed (as of v0.11.2) and looks like it has been around for awhile; I think ticket should be re-open but I will open another one to reference this one.

There are multiple ticket/reference of this issue in different manifestation, see:
#15894
#15733

This workaround is to use -var-file to explicitly state tfvars file

**Comment by cruftyoldsysadmin** [comment] 2018-02-05 12:01
I am experiencing the same problem as everybody else:

Is terraform really only impossible to set more than one variable in a terraform instance?

```
provider "aws" {
  region                  = "eu-west-1"
  shared_credentials_file = "foo/credentials"
  profile                 = "foo"
}

```
terraform => terraform --version
Terraform v0.11.3
+ provider.aws v1.8.0
+ provider.bitbucket v1.0.0
+ provider.null v1.0.0
```

**Comment by UtkarshYeolekar** [comment] 2018-02-15 14:21
@anilybba: I am also, facing the same issue, did you find any work around for this ?

**Comment by AnthonyWC** [comment] 2018-02-15 15:44
Hi all, so this is actually the expected behavior as the only file names that are automatically loaded are terraform.tfvars or *.auto.tfvars.  I think many people, myself included, were expecting this behaviour but it is by design.

**Comment by rjurney** [comment] 2018-06-28 20:54
I also have this issue.

`dev.tfvars:`

```
aws_profile = "default"
```

`variables.tf:`

```
variable "aws_profile" {
  description = "AWS profile to use for access control"
}
```

`main.tf:`

```
provider "aws" {
  profile = "${var.aws_profile}"
  ...
}
```

`terraform validate:`

```
Error: Required variable not set: aws_profile
```

It is as though tfvars are not working for me at all.

**Comment by v6** [comment] 2019-03-10 05:47
My friend and I both reproduced this issue after following https://www.hashicorp.com/resources/hangout-terraform-azure-for-beginners

Is `.tfvars` deprecated?

**Comment by v6** [comment] 2019-03-12 06:39
My friend and I both reproduced this issue after following https://www.hashicorp.com/resources/hangout-terraform-azure-for-beginners

Is `.tfvars` deprecated?

**Comment by rajetta** [comment] 2019-03-12 23:42
@v6 Make sure you do 'terraform init'

**Comment by apparentlymart** [comment] 2019-03-13 01:55
Hi all,

Whatever problem you are seeing now is something different than what this bug was about because the codepaths in question have changed considerably since 0.6.0. Please open new issues and complete the bug report template in full so we can understand what is going on and whether there is a new bug to fix.

**Comment by v6** [comment] 2019-03-13 23:59
Was it ever fixed?

**Comment by v6** [comment] 2019-03-14 00:00
If so, new issue.

**Comment by appcoreopc** [comment] 2019-07-07 21:32
what about forcing it by passing in an argument when you run terraform, eg.

terraform plan -var-flle="myvariable.tfvar"
terraform appy -var-flle="myvariable.tfvar"
