### ISSUE TITLE
0.6.12 escaping double quotes inside function argument is broken

### ISSUE THREAD

**Issue by eedwardsdisco** [hashicorp/terraform#5550] opened 2016-03-10 02:43 UTC
I believe this is a recurrence of the issue described in #613 but supposedly fixed by #785

this breaks (`parse error: syntax error`):
```
server_list = "${join(",", formatlist("\"%s\"", aws_instance.consul_cluster.*.private_ip))}"
```

this works:
```
server_list = "${join(",", formatlist("%s", aws_instance.consul_cluster.*.private_ip))}"
```

the difference is the `\"` around the `%s`

**Comment by eedwardsdisco** [comment] 2016-03-10 02:53
This is also broken if I try to do it in a .tf.json file instead:

```
"server_list": "${join(\",\", formatlist(\"\"%s\"\", aws_instance.consul_cluster.*.private_ip))}"
```

vs working

```
"server_list": "${join(\",\", formatlist(\"%s\", aws_instance.consul_cluster.*.private_ip))}"
```

**Comment by eedwardsdisco** [comment] 2016-03-10 03:00
For kicks I tried adding an extra backslash `\` and that appears to have worked?

```
server_list = "${join(",", formatlist("\\"%s\\"", aws_instance.consul_cluster.*.private_ip))}"
```

Should it require that?

**Comment by jen20** [comment] 2016-03-10 09:32
Hi @eedwardsdisco! This looks like a bug in HCL, I'll try to reproduce it and fix there.

**Comment by phinze** [comment] 2016-03-10 18:59
I've definitely run into this before - I ended up going with the double backslash route but never circled back to figure out why that was. It does seem like a single backslash should work logically speaking, but we'll have to be careful with BC if we change the behavior.

**Comment by rottenbytes** [comment] 2016-04-08 11:24
hit that bug. If changing behaviour isn't easy/possible, at bit of warning in the docs would be definitely a good thing.

**Comment by kwilczynski** [comment] 2016-05-23 09:31
This needs to be fixed, really. There are way too many use cases where this is valid.

**Comment by eedwardsdisco** [comment] 2016-05-23 16:01
Agreed @kwilczynski 

As noted in #6359 there appears to be MAJOR issues with the underlying HCL parser and escape behavior.

**Comment by ElliotG** [comment] 2016-06-15 07:35
+1 for fixing this :(

**Comment by phinze** [comment] 2016-06-16 17:41
Hi folks! It was indeed a BC concern that was preventing an earlier fix for this issue - I've got a proposed change over on the linked PR which breaks BC on another compatibility feature described there.

So hopefully resolution of this bug 🔜 !

**Closed** 2016-06-20 16:15 UTC
Labels: bug, core

**Comment by apparentlymart** [comment] 2019-01-26 19:13
Hi @tmackness,

Since this bug is so old it's unlikely that you're hitting the same bug even if the symptoms seem similar. I think what you're seeing there is a result of the shell's own handling of quotes, since you are passing quoted strings through the shell to `echo`. In order for that to work you'd also need to escape the quotes for the shell's benefit, so that they can pass both through Terraform _and_ through the shell.

If that explanation doesn't seem right, please [open a new issue](https://github.com/hashicorp/terraform/issues/new?template=bug_report.md) and fill out the bug report template in full so we can try to understand what is going on.
