### ISSUE TITLE
fmt breaks indentation when heredocs contain curly parens

### ISSUE THREAD

**Issue by querry43** [hashicorp/terraform#21950] opened 2019-07-02 00:37 UTC
### Terraform Version

```
Terraform v0.12.3
+ provider.aws v2.17.0
+ provider.fastly v0.8.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
module "es_proxy_service" {
  source = "./modules/container"

  name       = "es-proxy"
  stack_name = var.stack_name
  app_image  = "${data.aws_ecr_repository.es_proxy_repo.repository_url}:${terraform.workspace}"

  app_port     = 443
  app_protocol = "HTTPS"
  cpu_units    = 256
  memory       = 512

  # RESOLVER_IP references the general amazon dns ip
  # https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html#AmazonDNS
  environment = <<EOF
[
  { "name" : "ADMIN_USER", "value" : "${data.aws_ssm_parameter.elasticsearch_admin_user.value}" },
  { "name" : "ADMIN_PASSWORD", "value" : "${data.aws_ssm_parameter.elasticsearch_admin_password.value}" },
  { "name" : "RESOLVER_IP", "value" : "169.254.169.253" },
  { "name" : "SERVICE_URL", "value" : "http://${replace(
aws_elasticsearch_domain.elasticsearch_domain.kibana_endpoint,
"/\\/.*/",
"",
)}" }
]
EOF

  log_retention_days                  = var.gdpr_log_retention_days
  cloudwatch_log_streaming_lambda_arn = module.cloudwatch_log_streaming_lambda.arn
  log_bucket_id                       = module.log_bucket.id
}
```

### Expected Behavior

terraform fmt should properly format the file

### Actual Behavior
terraform fmt loses indentation depth after the heredoc.  everything is incorrectly indented afterwards.

```
module "es_proxy_service" {
  source = "./modules/container"

  name       = "es-proxy"
  stack_name = var.stack_name
  app_image  = "${data.aws_ecr_repository.es_proxy_repo.repository_url}:${terraform.workspace}"

  app_port     = 443
  app_protocol = "HTTPS"
  cpu_units    = 256
  memory       = 512

  # RESOLVER_IP references the general amazon dns ip
  # https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html#AmazonDNS
  environment = <<EOF
[
  { "name" : "ADMIN_USER", "value" : "${data.aws_ssm_parameter.elasticsearch_admin_user.value}" },
  { "name" : "ADMIN_PASSWORD", "value" : "${data.aws_ssm_parameter.elasticsearch_admin_password.value}" },
  { "name" : "RESOLVER_IP", "value" : "169.254.169.253" },
  { "name" : "SERVICE_URL", "value" : "http://${replace(
aws_elasticsearch_domain.elasticsearch_domain.kibana_endpoint,
"/\\/.*/",
"",
)}" }
]
EOF


    log_retention_days                  = var.gdpr_log_retention_days
    cloudwatch_log_streaming_lambda_arn = module.cloudwatch_log_streaming_lambda.arn
    log_bucket_id                       = module.log_bucket.id

# now 4 spaces indented.  additional resources are even more indented.
```

### Steps to Reproduce
terraform fmt

**Comment by jbardin** [comment] 2019-07-03 16:50
Thanks for filing the issue @querry43.
Duplicate of #21434

**Closed** 2019-07-03 16:50 UTC
