### ISSUE TITLE
root_block_device tags support?

### ISSUE THREAD

**Issue by ernoaapa** [hashicorp/terraform#3629] opened 2015-10-25 06:34 UTC
Hi,
is it possible to add a tags to AWS instance `root_block_device`? If not, any plans to support?

**Comment by jimmystewpot** [comment] 2015-11-03 23:47
having an option that will inherit the tags from the instance would also be useful

**Comment by FransUrbo** [comment] 2016-02-18 14:30
+1

**Comment by jfarschman** [comment] 2016-03-04 22:17
+1

**Comment by RyanBowlby-Reflektion** [comment] 2016-04-15 21:59
+1

**Comment by slobodyanyuk** [comment] 2016-08-23 15:55
+1

**Comment by stack72** [comment] 2016-11-14 12:38
Hi @ernoaapa 

Apologies for the late response here - this has already been requested in #3531 - I am going to close this as a duplicate of that so we can track all of the information in a central issue

Thanks again

Paul

**Closed by stack72** 2016-11-14 12:38 UTC
Labels: enhancement, provider/aws
