### ISSUE TITLE
And chaining operation not end evaluation early

### ISSUE THREAD

**Issue by NewbMiao** [hashicorp/terraform#35722] opened 2024-09-13 01:53 UTC
### Terraform Version

```shell
1.9.3
```

### Terraform Configuration Files

```terraform
variable "testObj" {
  type = object({
    name = optional(string, "")
  })
  default = null
}
output "name" {
  value = var.testObj != null && var.testObj.name != null ? var.test.name : "empty"
}

```

### Debug Output

https://gist.github.com/NewbMiao/b3a2677d3507b62f5f05be71d3a19560

### Expected Behavior

`var.testObj != null && var.testObj.name != null` should end evaluation early in `var.testObj != null` since it's already false and no need to check the following operation.

### Actual Behavior

all operation evaluated even it can be end early
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Attempt to get attribute from null value
│ 
│   on main.tf line 8, in output "name":
│    8:   value = var.testObj != null && var.testObj.name != null ? var.testObj.name : "empty"
│     ├────────────────
│     │ var.testObj is null
│ 
│ This value is null, so it does not have any attributes.
```

### Steps to Reproduce

1. terraform init
2. terraform plan

**Comment by jbardin** [comment] 2024-09-13 12:43
Duplicate of #24128

**Closed by jbardin** 2024-09-13 12:43 UTC
Labels: bug, new
