### ISSUE TITLE
route53_record & lifecycle do not remove old record when changing zones

### ISSUE THREAD

**Issue by btobolaski** [hashicorp/terraform#2400] opened 2015-06-18 21:34 UTC
I changed the `zone_id` that an `aws_route53_record` was assigned. The new record was generated correctly but, the record in the old zone was not removed.

Here is the diff on this specific resource

```diff
resource "aws_route53_record" "go-hostname" {
-  zone_id = "${aws_route53_zone.internal.id}"
+  zone_id = "${aws_route53_zone.primary.id}"
   name = "go"
   type = "A"
   ttl = "300"
   records = ["${aws_instance.go_master.public_ip}"]
   lifecycle {
     create_before_destroy = true
   }
 }
```

I'm using terraform 0.5.3

**Comment by radeksimko** [comment] 2015-06-20 19:56
Hi @btobolaski 
If I understand correctly, you're just changing `zone_id` in `aws_route53_record.go-hostname`, right?
Why should Terraform remove any zone in cases where you're just changing assignment?

**Comment by btobolaski** [comment] 2015-06-20 21:12
I'm sorry that I didn't make it clear. I'm not expecting Terraform to remove the old zone. I was trying to move this particular record to a new zone. I went about this by simply changing the `zone_id` to be the new zone's id. Since Terraform created the original record, I would expect a record to be created in the new zone and for the record in the old zone to be deleted. Instead what happened was that the record was created in the new zone and old record remained with no trace of it remaining in the state.

**Comment by radeksimko** [comment] 2015-06-20 22:09
@btobolaski I see, the old record should be removed from the old zone when changing `zone_id`, thanks for the clarification. From my observations, the old record is correctly removed if there's no `lifecycle` specified, so there's something strange happening w/ `lifecycle`.

According to the log, it's trying to remove the record which has been just created.

**Comment by catsby** [comment] 2015-12-02 21:57
Hey friends – sorry for the silence here. 
I'm closing this as "fixed/can't reproduce". I used this config and toggled the `zone_id` and records were added/removed as I expected:

```hcl
provider "aws" {
  region="us-west-2"
}

resource "aws_route53_zone" "primary" {
   name = "tftesting.com"
}

resource "aws_route53_zone" "other" {
   name = "tfothertesting.com"
}

resource "aws_route53_record" "default" {
    #zone_id = "${aws_route53_zone.primary.id}"
    zone_id = "${aws_route53_zone.other.id}"
    name = "www"
    type = "A"
    ttl = "30"
    records = ["127.0.0.1"]
}
```

Thanks!

**Closed by catsby** 2015-12-02 21:57 UTC
Labels: bug, provider/aws
