### ISSUE TITLE
give more descriptive error message for invalid var file

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#1889] opened 2015-05-10 06:19 UTC
I'm trying to specify a different variable file (variables/dev.tf) with the following command:
```terraform plan -state=states/build.tfstate -var-file=dev.tf```

 and am getting hit with this error:

```invalid value "dev.tf" for flag -var-file: root.variable: unknown type to string: ValueTypeObject```

With the only current variables in the dev.tf file being:
     
    variable "access_key" { 
      description = "AWS access key (pulled from command line opts)"
    }

    variable "secret_key" { 
     description = "AWS secret access key (pulled from command line opts)"
    }

If I move this same var file to variables.tf it is picked up and read correctly.  Maybe I'm misunderstanding the usage of the -var-file=some/path/var.tf but this does not seem to work correctly.

**Comment by mitchellh** [comment] 2015-05-10 06:23
Ah, this is just a poor error message. `-var-file` is meant to specify the _values_ for variables, not define them. So it should be in the syntax `foo = "bar"`. This is working as intended but perhaps the error message could improve.

**Comment by mitchellh** [comment] 2015-05-10 06:23
Renaming issue and tagging.

**Comment by mikeyhill** [comment] 2015-05-10 07:19
Thanks - that make much more sense.

**Comment by mikeyhill** [comment] 2015-05-10 18:26
@mitchellh I was going to update this error message and submit it back to you, however not having much exposure to Go I was chasing my tail.  If you want to point me in the right direction I'll update this and a few others I've gotten hung up on.

**Comment by mitchellh** [comment] 2015-06-26 00:50
@mikeyhill Sorry for not responding. Eh, this is a particularly nasty part of Terraform. I'll handle this one, not a great beginner issue to TF. :)

**Comment by mitchellh** [comment] 2015-06-26 00:57
Done, committed directly to master since it is just a wording change.

**Closed by mitchellh** 2015-06-26 00:57 UTC
Labels: bug, core

**Comment by mikeyhill** [comment] 2015-06-26 01:23
@mitchellh - not a problem, your guidance back in May was enough to get me out of a rut.  I searched through the to find the wording (except for where you made your commit apparently).  Thanks.
