### ISSUE TITLE
WinRM connection error after ~25 mins of running provisioner

### ISSUE THREAD

**Issue by johnkratos** [hashicorp/terraform#24408] opened 2020-03-19 00:07 UTC
### Terraform Version

```
_Terraform -v_
Terraform v0.12.0
+ provider.aws v2.53.0
+ provider.null v2.1.2
+ provider.template v2.1.2


...
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

Terraform run should have finished

### Actual Behavior

Terraform spits out this error message after ~25 mins into the provisioner:

null_resource.post_config: Still creating... [24m1s elapsed]
null_resource.post_config: Still creating... [24m11s elapsed]
null_resource.post_config: Still creating... [24m21s elapsed]

**Error: error executing "C:/Temp/terraform_2114901051.cmd": unknown error Post http://10.245.162.87:5985/wsman: read tcp 10.245.160.198:53154->10.245.162.87:5985: wsarecv: An existing connection was forcibly closed by the remote host.**

### Steps to Reproduce

Run a Terraform script that makes a connection via WinRM to the provisioned instance.
That script needs to run longer than ~25 mins after making the connection.

### Additional Context

I used to be able to complete TF runs without any issues. After upgrading to TF v 0.12 I started getting errors when running provisioners over WinRM when the run goes over ~25 mins. 

Is there a timeout that is being set somewhere for TF v0.12?

My terraform run consists of running a set of chef recipes on the provisioned node. I don't see this issue with connections over SSH for Linux boxes I provision.

**Comment by dhekimian** [comment] 2020-06-27 18:16
@johnkratos We were seeing a bunch of WinRM issues after upgrading to 0.12.x earlier this year from 0.11.x. After trying to reproduce the issue with newer Terraform builds, we found that we are unable to reproduce them starting with 0.12.26.

https://github.com/hashicorp/terraform/issues/22006#issuecomment-646155499

Try 0.12.26 or newer to see if this is still an issue.

**Comment by dhekimian** [comment] 2022-07-27 03:34
We're on Terraform v1.2.5 and haven't seen this issue since we upgraded to 0.12.26.

I suggest closing this.

**Comment by crw** [comment] 2022-07-27 23:51
Thanks for the update and all the testing, we very much appreciate it! Based on your results I shall follow your suggestion and close this issue.

**Closed by crw** 2022-07-27 23:51 UTC
Labels: bug, provisioner/winrm, v0.12
