### ISSUE TITLE
String template processing raises syntax errors, yet the code seems valid to me

### ISSUE THREAD

**Issue by amg1127** [hashicorp/terraform#24711] opened 2020-04-20 08:42 UTC
### Terraform Version

```
$ terraform  -v
Terraform v0.12.24
+ provider.local v1.4.0
```

### Terraform Configuration Files

```hcl
# test.tf

resource "local_file" "alpha" {
    count = 2
    content = "I am Alpha."
    filename = "file_alpha_${count.index}.txt"
    file_permission = "0644"
}

resource "local_file" "bravo" {
    content = "I am Bravo."
    filename = "file_bravo.txt"
    file_permission = "0644"
}

resource "local_file" "charlie" {
    content = "I am Charlie."
    filename = "file_charlie.txt"
    file_permission = "0600"
}

resource "local_file" "delta" {
    count = 3
    content = "I am Delta."
    filename = "file_delta_${count.index}.txt"
    file_permission = "0600"
}

locals {
    allFiles = flatten ([ local_file.alpha, local_file.bravo, local_file.charlie, local_file.delta ])
    allFilePermissions = sort(distinct([for f in local.allFiles : f.file_permission]))
}

resource "local_file" "FILELIST" {
    filename = "FILELIST.txt"
    content = <<-CONTENT
    {~% for permission in local.allFilePermissions ~}
    ${permission}:
      {~% for file in local.allFiles ~}
        {~% if permission == file.file_permission ~}
          ${file.filename}
        {~% endif ~}
      {~% endfor ~}
    {~% endfor ~}
    CONTENT
}
```

### Debug Output

https://gist.github.com/amg1127/c5da47c48becb84753a08b996dd002e3

### Crash Output

_(not applicable)_

### Expected Behavior

By applying the example plan file above, a local file named `FILELIST.txt` should be generated with the following content:

````
0600:
      file_charlie.txt
      file_delta_0.txt
      file_delta_1.txt
      file_delta_2.txt
0644:
      file_alpha_0.txt
      file_alpha_1.txt
      file_bravo.txt
````

### Actual Behavior

The output of `terraform apply -auto-approve -no-color` suggests that there are syntax errors in my file:

````
$ terraform apply -auto-approve -no-color

Error: Invalid reference

  on test.tf line 36, in resource "local_file" "FILELIST":
  36:     ${permission}:

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.


Error: Reference to undeclared resource

  on test.tf line 39, in resource "local_file" "FILELIST":
  39:           ${file.filename}

A managed resource "file" "filename" has not been declared in the root module.
````

However, I think that the code that generates the content of the file is correct, according to Terraform documentation: https://www.terraform.io/docs/configuration/expressions.html#directives

> The `for <NAME> in <COLLECTION>` / `endfor` directive iterates over the elements of a given collection or structural value and evaluates a given template once for each element, concatenating the results together:
> 
> ````
> <<EOT
> %{ for ip in aws_instance.example.*.private_ip }
> server ${ip}
> %{ endfor }
> EOT
> ````
> The name given immediately after the `for` keyword is used as a temporary variable name which can then be referenced from the nested template.

### Steps to Reproduce

1. Create an empty directory
2. Copy the plan file above to a new file named `test.tf`
3. Run `terraform init`
4. Run `terraform apply -auto-approve -no-color`

### Additional Context

In my main project, I am trying to generate an Ansible inventory file dynamically, based on the properties of resources that were created by Terraform.

### References

_(not applicable)_

**Comment by danieldreier** [comment] 2020-05-19 23:19
I've tried to simplify this to:
```hcl
resource "local_file" "alpha" {
    content = "I am Alpha."
    filename = "file_alpha.txt"
}

resource "local_file" "bravo" {
    content = "I am Bravo."
    filename = "file_bravo.txt"
}

resource "local_file" "FILELIST" {
    filename = "FILELIST.txt"
    content = <<-CONTENT
    {~% for f in [local_file.alpha, local_file.bravo] ~}
        ${f.filename}
    {~% endfor ~}
    CONTENT
}
```

I'm still seeing the same behavior with the simplified case. @apparentlymart can you chime in here and help explain? I'm unclear whether this is a bug or if working as expected.

**Comment by apparentlymart** [comment] 2020-05-19 23:55
One thing I can see here is that the order of symbols for an opening template directive with a strip marker is `%{~` rather than `{~%`. Changing that would give us the following:

```hcl
resource "local_file" "FILELIST" {
    filename = "FILELIST.txt"
    content = <<-CONTENT
    %{~ for f in [local_file.alpha, local_file.bravo] ~}
        ${f.filename}
    %{~ endfor ~}
    CONTENT
}
```

I think the errors here _are_ related to that, but indeed they are confusing because the result ends up still being valid syntax but with the incorrectly-formatted template directives being interpreted as literal text instead. Since the `for` directive is never evaluated, no local symbol `f` is defined in the scope, and so Terraform thinks that `f.filename` is a reference to a resource declared like `resource "f" "filename"`, because it's being interpreted in the global scope instead.

---

Though not related to the bug at hand, I have a feeling that the example I shared above wouldn't produce the desired result, because putting strip markers on both the start and end of all of the directives will end up removing all of the newlines completely and producing a single run-on line like this:

```
file_alpha.txtfile_bravo.txt
```

The example in the documentation uses strip markers only at the _ends_ of the directives, so that the newline after the nested expression can still be preserved so it can produce newline-separated items:

```hcl
resource "local_file" "FILELIST" {
    filename = "FILELIST.txt"
    content = <<-CONTENT
    %{ for f in [local_file.alpha, local_file.bravo] ~}
    ${f.filename}
    %{ endfor ~}
    CONTENT
}
```

Note that the flush heredoc operator `<<-` already deals with stripping off the leading whitespace here during initial parsing, so we don't need to use the strip markers to deal with that. The result of the above should be the following:

```
file_alpha.txt
file_bravo.txt
```

**Comment by danieldreier** [comment] 2020-05-20 00:05
Thanks, @apparentlymart! I have run this and confirmed that it does indeed work. I believe that this answers @amg1127's question and hopefully allows him to build that ansible inventory file, so I'm going to close this issue.

**Closed by danieldreier** 2020-05-20 00:05 UTC

**Comment by amg1127** [comment] 2020-05-20 05:25
> One thing I can see here is that the order of symbols for an opening template directive with a strip marker is `%{~` rather than `{~%`. Changing that would give us the following:

Thanks so much for your analysis, @apparentlymart . I hadn't noticed that I was using wrong delimiter characters. Sorry about my mistake.

With the correct delimiter, my initial example:

````
# test.tf

resource "local_file" "alpha" {
    count = 2
    content = "I am Alpha."
    filename = "file_alpha_${count.index}.txt"
    file_permission = "0644"
}

resource "local_file" "bravo" {
    content = "I am Bravo."
    filename = "file_bravo.txt"
    file_permission = "0644"
}

resource "local_file" "charlie" {
    content = "I am Charlie."
    filename = "file_charlie.txt"
    file_permission = "0600"
}

resource "local_file" "delta" {
    count = 3
    content = "I am Delta."
    filename = "file_delta_${count.index}.txt"
    file_permission = "0600"
}

locals {
    allFiles = flatten ([ local_file.alpha, local_file.bravo, local_file.charlie, local_file.delta ])
    allFilePermissions = sort(distinct([for f in local.allFiles : f.file_permission]))
}

resource "local_file" "FILELIST" {
    filename = "FILELIST.txt"
    content = <<-CONTENT
    %{~ for permission in local.allFilePermissions ~}
    ${permission}:
      %{~ for file in local.allFiles ~}
        %{~ if permission == file.file_permission ~}
          ${file.filename}
        %{~ endif ~}
      %{~ endfor ~}
    %{~ endfor ~}
    CONTENT
}
````

...produces a local file `FILELIST.txt` with the following content:

````
    0600:
          file_charlie.txt
          file_delta_0.txt
          file_delta_1.txt
          file_delta_2.txt
    0644:
          file_alpha_0.txt
          file_alpha_1.txt
          file_bravo.txt
````

Although the output file is unexpectedly one-level indented, I am happy with the file being generated.

@danieldreier , thanks for closing my not-a-bug report.
