### ISSUE TITLE
compiling fails due to cloudstack go lib (cloudstack_disc, cloudstack_vpc)

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#788] opened 2015-01-14 16:38 UTC
On 
``` 
~/go/src/github.com/hashicorp/terraform ⮀ ⭠ master ● ⮀ sw_vers -productVersion
10.9.5
 ~/go/src/github.com/hashicorp/terraform ⮀ ⭠ master ● ⮀ go version
go version go1.4 darwin/amd64
```

Yields; 
```
 ~/go/src/github.com/hashicorp/terraform ⮀ ⭠ master ● ⮀ make updatedeps
go get -u golang.org/x/tools/cmd/stringer
# Go 1.4 changed the format of `go get` a bit by requiring the
# canonical full path. We work around this and just force.
github.com/hashicorp/terraform (download)
github.com/hashicorp/consul (download)
github.com/hashicorp/go-checkpoint (download)
<snip>
github.com/hashicorp/terraform/builtin/providers/cloudstack
# github.com/hashicorp/terraform/builtin/providers/cloudstack
builtin/providers/cloudstack/resource_cloudstack_disk.go:186: not enough arguments in call to cs.Volume.NewResizeVolumeParams
builtin/providers/cloudstack/resource_cloudstack_vpc.go:127: too many arguments in call to cs.VPC.NewUpdateVPCParams
make: *** [updatedeps] Error 2
```

**Comment by knuckolls** [comment] 2015-01-14 16:49
Looks like I duplicated the issue. More information is included on #789

**Comment by knuckolls** [comment] 2015-01-14 16:49
@svanharmelen ^^

**Comment by pmoust** [comment] 2015-01-14 16:49
Opened https://github.com/xanzy/go-cloudstack/issues/13 for @svanharmelen

**Comment by pmoust** [comment] 2015-01-14 16:52
@knuckolls well the encouraging thing is that it hasn't been more than 2 hours since BC-break and we already got reports coming in. Means there are some hungry Ops guys grabbing bleeding edge ;P

**Comment by mitchellh** [comment] 2015-01-14 16:53
Hah. I think the easiest thing might be to just fix to their API in this case...

**Comment by svanharmelen** [comment] 2015-01-14 16:55
@pmoust @knuckolls @mitchellh working on an update of the CloudStack provider during which I found a small bug in the generation of the go-cloudstack package. While I was fixing the small bug I also updated the go-cloudstack package to be based on the latest v4.4 CloudStack API (the older v4.3 is still available but is called cloudstack43 instead of just cloudstack)

Currently running the ACC tests for the updated CloudStack provider code after will I will push that in and the build will succeed again...

You guys are really quick as I updated the lib less then an hour ago :wink:

**Comment by svanharmelen** [comment] 2015-01-14 16:57
Note to self: Will prep the updates to be done in sync next time preventing this issue from happening again!

**Comment by pmoust** [comment] 2015-01-14 16:59
@svanharmelen I am sure the sysadmin-jinx will manage to get us fetching deps during that small timeframe. I do bet on that.
No worries ofc, edge case

**Comment by knuckolls** [comment] 2015-01-14 17:00
My current workaround is to just remove the cloudstack folders from /builtin/providers/ and /builtin/bins/ until the fix is up. That effectively unblocks me for now. Thanks for the quick response!

**Comment by svanharmelen** [comment] 2015-01-14 17:05
@knuckolls @pmoust @mitchellh to not bother you guys while I'm testing, I reverted the latest changes in go-cloudstack... So you should be good again...

**Comment by knuckolls** [comment] 2015-01-14 17:17
@svanharmelen confirmed that make updatedeps and make dev are working in master again. I appreciate it.

**Comment by svanharmelen** [comment] 2015-01-14 17:24
Cool, thanks for the confirmation. Will close this one now as the issue is solved.

**Closed by svanharmelen** 2015-01-14 17:24 UTC
