### ISSUE TITLE
Terrafrom crash

### ISSUE THREAD

**Issue by KoutilyaGowtham** [hashicorp/terraform#17763] opened 2018-04-03 12:49 UTC
``

### Debug Output
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bflad** [comment] 2018-04-03 13:02
Panic portion of crash log:
```
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: panic: interface conversion: interface {} is string, not map[string]interface {}
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: goroutine 103 [running]:
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readMap(0xc420820870, 0x2ae9a5e, 0x4, 0xc420651680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:170 +0xfcd
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc420820870, 0xc42024a070, 0x1, 0x1, 0xc42000d800, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:113 +0xd72
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc420820870, 0xc42024a070, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0x110
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc42028b5c0, 0xc42024a070, 0x1, 0x1, 0x2aeb55d, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0x12e
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc4201fd7a0, 0xc42024a070, 0x1, 0x1, 0xc42024a012, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:497 +0x16e
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc4201fd7a0, 0x2ae9a5e, 0x4, 0xc420481201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:473 +0x135
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc4201fd7a0, 0x2ae9a5e, 0x4, 0x2ae8795, 0x1, 0xc42048b2b8, 0x5, 0x0)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:450 +0xa5
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffMap(0xc420313470, 0x2ae9a5e, 0x4, 0xc420651680, 0xc42048b610, 0x4753f60, 0xc4201fd7a0, 0x429800, 0x0, 0x0)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:932 +0x115
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc420313470, 0x2ae9a5e, 0x4, 0xc420651680, 0xc42028b4c0, 0x4753f60, 0xc4201fd7a0, 0x0, 0x0, 0x0)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:778 +0x593
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc420313470, 0xc420253810, 0xc420820450, 0x0, 0x26be880, 0xc420011680, 0xc4204d2fc0, 0xc42060ea01, 0x429538)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x24a
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc420643500, 0xc420253810, 0xc420820450, 0x26be880, 0xc420011680, 0x1, 0xc420820600, 0xc420713e00)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:252 +0x187
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc4206fdc70, 0xc4202537c0, 0xc420253810, 0xc420820450, 0x7fefee6d8000, 0x0, 0x18)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:296 +0xa4
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc42071bae0, 0xc42028b000, 0xc4206066e0, 0x0, 0x0)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:538 +0x57
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: reflect.Value.call(0xc4204de780, 0xc42036b980, 0x13, 0x2ae92d6, 0x4, 0xc42060ef20, 0x3, 0x3, 0x403a23, 0xc420030380, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: reflect.Value.Call(0xc4204de780, 0xc42036b980, 0x13, 0xc42002a720, 0x3, 0x3, 0xc42002a720, 0xc42002a728, 0xc4202278c0)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: net/rpc.(*service).call(0xc4204bc6c0, 0xc4207f6e10, 0xc420445618, 0xc4200a4780, 0xc4202ca200, 0x21f6ce0, 0xc42028b000, 0x16, 0x21f6d20, 0xc4206066e0, ...)
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: created by net/rpc.(*Server).ServeCodec
2018-04-03T08:22:43.866-0400 [DEBUG] plugin.terraform-provider-aws_v1.13.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by KoutilyaGowtham** [comment] 2018-04-03 13:20
Yeah,  do have any idea why it was crashing

**Comment by KoutilyaGowtham** [comment] 2018-04-03 15:38
Hi @jbardin do you require anything else from me

**Comment by KoutilyaGowtham** [comment] 2018-04-05 13:56
Hi, do anyone know what happens here

**Comment by jbardin** [comment] 2018-04-05 14:11
Hi @KoutilyaGowtham,

Sorry you're having an problem here. I can take a look at the stack trace soon. In the meantime, if you could provide any configuration related to the resources involved, as well as any steps we might need to recreate the issue, it would help speed things up.

**Comment by danieldreier** [comment] 2020-06-17 00:28
@KoutilyaGowtham the AWS terraform provider is no longer being maintained in this GitHub repository. If you are still having this problem with a newer version of the AWS provider, please report it to https://github.com/terraform-providers/terraform-provider-aws. In the meantime, I'm going to close this issue because it's been more than a year, and it is almost impossible to figure out how to troubleshoot issues of this nature without clear reproduction steps.

**Closed by danieldreier** 2020-06-17 00:28 UTC
Labels: core, crash
