### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by hemmster** [hashicorp/terraform#26531] opened 2020-10-09 14:28 UTC
I ran into an error with the terraform-provider-vsphere_v1.24.1_x4 plugin using terraform version v0.12.24. I upgraded to terraform version v0.13.4 and still the same error. I added a version constraint for the provider back to v1.24.0 and the apply was successful.

Here is the stdout from the error.

---------------------------------------------------------------------------------------------------------------------------
module.app_ESF.null_resource.create_iso["201"]: Creation complete after 1m36s [id=2842156542478917348]
module.app_ESF.vsphere_virtual_machine.vm["201"]: Creating...

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

panic: interface conversion: interface {} is nil, not string
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: goroutine 87 [running]:
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineCreateBare(0xc0001b4f50, 0x1459fe0, 0xc000258500, 0x13c7e40, 0xc0004674a0, 0x0)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:1215 +0xeb7
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineCreate(0xc0001b4f50, 0x1459fe0, 0xc000258500, 0x2, 0x271f600)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:327 +0xa27
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000215800, 0xc00008abe0, 0xc00057ab00, 0x1459fe0, 0xc000258500, 0x148fd01, 0xc00033d3a8, 0xc00027f050)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x365
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00009ac80, 0xc0004738e0, 0xc00008abe0, 0xc00057ab00, 0xc00024c508, 0xc00000e808, 0x1491c40)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e1b0, 0x1b1b560, 0xc00029aa20, 0xc000122780, 0xc00000e1b0, 0xc00029aa20, 0xc0007a1a48)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x171ec40, 0xc00000e1b0, 0x1b1b560, 0xc00029aa20, 0xc000122720, 0x0, 0x1b1b560, 0xc00029aa20, 0xc0001ee000, 0x1528)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000152160, 0x1b27a40, 0xc0005f2600, 0xc0001a8200, 0xc00069c3c0, 0x26e4f60, 0x0, 0x0, 0x0)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc000152160, 0x1b27a40, 0xc0005f2600, 0xc0001a8200, 0x0)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000116350, 0xc000152160, 0x1b27a40, 0xc0005f2600, 0xc0001a8200)
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:710 +0xa1
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-10-09T08:55:03.039-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-10-09T08:55:03.040-0500 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/vsphere/1.24.1/linux_amd64/terraform-provider-vsphere_v1.24.1_x4 pid=11916 error="exit status 2"
2020/10/09 08:55:03 [DEBUG] module.app_ESF.vsphere_virtual_machine.vm["201"]: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/09 08:55:03 [TRACE] EvalMaybeTainted: module.app_ESF.vsphere_virtual_machine.vm["201"] encountered an error during creation, so it is now marked as tainted
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalWriteState
2020/10/09 08:55:03 [TRACE] EvalWriteState: removing state object for module.app_ESF.vsphere_virtual_machine.vm["201"]
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/10/09 08:55:03 [TRACE] EvalApplyProvisioners: vsphere_virtual_machine.vm["201"] has no state, so skipping provisioners
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/09 08:55:03 [TRACE] EvalMaybeTainted: module.app_ESF.vsphere_virtual_machine.vm["201"] encountered an error during creation, so it is now marked as tainted
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalWriteState
2020/10/09 08:55:03 [TRACE] EvalWriteState: removing state object for module.app_ESF.vsphere_virtual_machine.vm["201"]
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalIf
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalIf
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalWriteDiff
2020/10/09 08:55:03 [TRACE] eval: *terraform.EvalApplyPost
2020/10/09 08:55:03 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/10/09 08:55:03 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/10/09 08:55:03 [TRACE] [walkApply] Exiting eval tree: module.app_ESF.vsphere_virtual_machine.vm["201"]
2020/10/09 08:55:03 [TRACE] vertex "module.app_ESF.vsphere_virtual_machine.vm[\"201\"]": visit complete
2020/10/09 08:55:03 [TRACE] dag/walk: upstream of "module.app_ESF.provider[\"registry.terraform.io/hashicorp/vsphere\"] (close)" errored, so skipping
2020/10/09 08:55:03 [TRACE] dag/walk: upstream of "module.app_ESF (close)" errored, so skipping
2020/10/09 08:55:03 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/10/09 08:55:03 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/10/09 08:55:03 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc0008a04b0),
  Bucket: "XXXXXXXXXXXXXXXXXXXXXXX",
  ContentLength: 26328,
  ContentType: "application/json",
  Key: "qual/AA3/terraform.tfstate",
  ServerSideEncryption: "AES256"
}
2020-10-09T08:55:03.304-0500 [DEBUG] plugin: plugin exited
2020-10-09T08:55:03.304-0500 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[terragrunt] 2020/10/09 08:55:03 Hit multiple errors:
exit status 1

---------------------------------------------------------------------------------------------------------------
I could not find the crash.log within the path nor within the file system.
Thanks for your help.

**Comment by apparentlymart** [comment] 2020-10-10 00:00
Hi @hemmster! Sorry for this crash and thanks for reporting it.

The root cause of this error seems to be that the `vsphere` provider has crashed, which therefore broke its connection to Terraform Core and thus caused the "transport is closing" error.

The lines containing `plugin.terraform-provider-vsphere_v1.24.1_x4` are the parts that are of most relevance here. We don't develop that provider in this repository though, so I suggest opening a new issue about this in [the vSphere provider repository](https://github.com/hashicorp/terraform-provider-vsphere). If you include those log lines I indicated then hopefully the vSphere team can quickly determine the location of the bug in the provider's own source code.

Since there isn't anything we could do in _this_ repository to improve the situation, I'm going to close this issue. Thanks again!

**Closed by apparentlymart** 2020-10-10 00:00 UTC
