### ISSUE TITLE
Overriding provider source fails

### ISSUE THREAD

**Issue by dee-kryvenko** [hashicorp/terraform#26683] opened 2020-10-23 00:53 UTC
### Terraform Version

```
Terraform v0.13.5
```

### Terraform Configuration Files

`main.tf`:

```terraform
terraform {
  required_providers {
    tls = {
      version = "~> 2.2"
    }
  }
}

resource "tls_private_key" "my_key" {
  algorithm = "ECDSA"
}

output "my_key" {
  value = tls_private_key.my_key.public_key_pem
}
```

`examples/basic/main.tf`:

```terraform
terraform {
  required_providers {
    somearatls = {
      source  = "someara/tls"
      version = "2.3.0-pre"
    }
  }
}

provider "somearatls" {}

module "test" {
  source = "../.."

  providers = {
    tls = somearatls
  }
}

output "test" {
  value = module.test
}
```

### Debug Output

```
Error: missing provider provider["registry.terraform.io/hashicorp/tls"]
```

See debug log https://gist.github.com/dee-kryvenko/747c78a9c8d24a87836421330bfd52c6

### Expected Behavior

Terraform should have used `someara/tls` version of `tls` provider and passed it's instance downstream to the module.

### Actual Behavior

It fails with the error above.

### Steps to Reproduce

0. `cd examples/basic`
1. `terraform init`
2. `terraform apply`

### Additional Context

So imagine a generic module that uses provider X. Provider might have some bug that has been already fixed in some fork, but wait time to merge and new release may vary. There is no reason to stop the work and wait for this to happen - I need to be able to just override provider source upstream and make my callee module to use this forked implementation.

**Comment by apparentlymart** [comment] 2020-10-23 14:32
Hi @dee-kryvenko,

What you attempted here is unfortunately not allowed. The `providers` argument for modules can only assign a different provider configuration for _the same provider_, not a configuration of a different provider that happens to have the same type name.

If you want to make a release of a temporary fork of someone else's provider, the way that would work is to give it exactly the same name as the upstream provider but assign a version number that includes build metadata to show that it is a local build, like `v1.2.0+yourcompany.1`. You can then distribute the fork build using either a local filesystem or network mirror of that provider that is under your control.

We don't intend to make it possible to substitute one provider for another because Terraform cannot guarantee that two distinct providers will be compatible and so allowing this would create a high risk of becoming trapped in a condition where the only exit is to manually edit the state in order to fix the incompatible data inside. Providers with different full names are therefore always totally distinct as far as Terraform is concerned.

Since Terraform was working as intended here, I'm going to close this. Thanks for reporting it, nonetheless!

**Closed by apparentlymart** 2020-10-23 14:32 UTC
Labels: bug, new

**Comment by dee-kryvenko** [comment] 2020-10-23 15:29
> Terraform cannot guarantee that two distinct providers will be compatible

@apparentlymart I am not sure I understand why Terraform would be required to guarantee that - of course it will be up to the fork maintainer and the user of it, and of course neither of them can guarantee anything as baseline still can make backward incompatible change.

But this to me does not justify the opportunity of not having that flexibility. I much more struggle from the amount of technical debt caused due to not having the ability to use a bugfix straight away - it introduces weird `null_resource`s with `local-exec` provisioners, `external` data sources and other means to delegate to bash/python/aws cli/etc to get the job done. And that is not in the state at all, much more dangerous and asking for trouble.

Please reconsider.

**Comment by dee-kryvenko** [comment] 2020-10-23 15:45
Another way of thinking about it - if I had a chance to modify provider to my needs instead of working around with `local-exec` and `external`, imagine how much contribution that would draw back to the providers. Let's be realistic, majority of us just does their jobs. We all have business challenges to solve, and we can't say to the business that we're gonna wait for some 3rd party release outside of our control. That forces people to workaround stuff on their side, and these contributions will never make it back to the upstream.
But if there was a way to do it right and be able to share instead of the workarounds, here would be a massive incentive for people to contribute back to the open source. If I'd be able to just fork, PR, merge an use right away, with no yak shaving, with no thinking how to build and how to distribute my private build internally - I would be doing only that and abandon workarounds. On scale - that would result into a major bump in OSS contributions. Make it (sharing) easier and more appealing than the alternative.
