### ISSUE TITLE
azurerm_key_vault_access_policy crashes Terraform app service has app_settings marked as sensitive

### ISSUE THREAD

**Issue by blanchak** [hashicorp/terraform#28488] opened 2021-04-22 17:10 UTC
### Terraform Version

```
Terraform v0.15.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0

```

### Terraform Configuration Files

```terraform

terraform {
  # For all Terraform configuration settings, see: https://www.terraform.io/docs/configuration/terraform.html
  required_version = "~> 0.15.0"

  # Lock providers to reduce incompatibility between runs
  required_providers {
    azurerm = {
      # see: https://www.terraform.io/docs/providers/azurerm/
      source  = "hashicorp/azurerm"
      version = "~> 2.56"
    }
  }
}

provider "azurerm" {
  skip_provider_registration = true
  features {}
}


variable "RG" {
  type    = string
  default = "<<REDACTED>>"
}

variable "KeyVaultId" {
  type    = string
  default = "<<REDACTED>>"
}

variable "location" {
  type    = string
  default = "canadacentral"
}

variable "tmp_settings" {
  description = "Addition settings used to merge with app_settings"
  type        = map(string)
  default     = { "Sensitive_Crash_Test" = "Shhh! This is a secret." }
  sensitive   = true # This will cause azurerm_key_vault_access_policy to crash Terraform.
}

resource "azurerm_app_service_plan" "plan_crash" {
  name                = "example-appserviceplan-crash"
  location            = var.location
  resource_group_name = var.RG
  kind                = "linux"
  reserved            = true

  sku {
    tier = "PremiumV2"
    size = "P1v2"
  }
}

resource "azurerm_app_service" "app_crash" {
  name                = "example-app-crash"
  location            = var.location
  resource_group_name = var.RG
  app_service_plan_id = azurerm_app_service_plan.plan_crash.id

  app_settings = var.tmp_settings

  identity {
    type = "SystemAssigned"
  }
}

# This will crash Terraform because the app service has app_settings marked as sensitive.
resource "azurerm_key_vault_access_policy" "main" {
  key_vault_id       = var.KeyVaultId
  tenant_id          = azurerm_app_service.app_crash.identity[0].tenant_id
  object_id          = azurerm_app_service.app_crash.identity[0].principal_id
  secret_permissions = ["get"]
}

```

### Crash Output

```
2021-04-22T14:04:03.458-0300 [TRACE] vertex "azurerm_app_service.app_crash": visit complete
2021-04-22T14:04:03.458-0300 [TRACE] vertex "azurerm_key_vault_access_policy.main": starting visit (*terraform.NodeApplyableResourceInstance)
2021-04-22T14:04:03.458-0300 [TRACE] readDiff: Read Create change from plan for azurerm_key_vault_access_policy.main
2021-04-22T14:04:03.458-0300 [TRACE] readResourceInstanceState: reading state for azurerm_key_vault_access_policy.main
2021-04-22T14:04:03.458-0300 [TRACE] readResourceInstanceState: no state present for azurerm_key_vault_access_policy.main
2021-04-22T14:04:03.458-0300 [TRACE] readDiff: Read Create change from plan for azurerm_key_vault_access_policy.main
2021-04-22T14:04:03.460-0300 [TRACE] vertex "azurerm_key_vault_access_policy.main": visit complete

panic: value is marked, so must be unmarked first

goroutine 185 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.LengthInt(0x29b9fb8, 0xc000e56300, 0x22642e0, 0xc000e02ee8, 0x29b9f01)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1045 +0x56
github.com/zclconf/go-cty/cty.transform(0xc000e57080, 0x1, 0x1, 0x29b9fb8, 0xc000e56300, 0x22642e0, 0xc000e02ee8, 0x2983950, 0xc000e03050, 0xc000e02ee8, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:175 +0x8fb
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x29b9ff0, 0xc000e56970, 0x2175800, 0xc000e2d260, 0x2983950, 0xc000e03050, 0x0, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x29b9ff0, 0xc000e56970, 0x2175800, 0xc000e2d260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:215 +0xcb
github.com/hashicorp/terraform/terraform.markProviderSensitiveAttributes(0xc0012f4570, 0x29b9ff0, 0xc000e56970, 0x2175800, 0xc000e2d260, 0x0, 0x13, 0xc000397b60, 0x9)
	/home/circleci/project/project/terraform/evaluate.go:960 +0xc5
github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc000801e60, 0x4d, 0xc00004b140, 0x13, 0xc000397b60, 0x9, 0xc0003977d0, 0xf, 0x48, 0x18, ...)
	/home/circleci/project/project/terraform/evaluate.go:787 +0x1353
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc000c376d0, 0xc000cdaf90, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30)
	/home/circleci/project/project/lang/eval.go:360 +0x208d
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
	/home/circleci/project/project/lang/eval.go:238
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc000c376d0, 0x29b8ab8, 0xc000d41350, 0xc000ab09f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:51 +0x105
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc0003c6410, 0x29b8d58, 0xc000d41350, 0xc000ab09f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:273 +0x1bb
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).plan(0xc000c56e00, 0x29f0990, 0xc0003c6410, 0xc00087e780, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000397b38, ...)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:577 +0x3df
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc000cc0160, 0x29f0990, 0xc0003c6410, 0x0, 0x0, 0xc0006d9c10)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:235 +0x63d
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).Execute(0xc000cc0160, 0x29f0990, 0xc0003c6410, 0xc00008e001, 0xc0006d9d18, 0x11c06a, 0x21bf5c0)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:129 +0xbc
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc001b17680, 0x29f0990, 0xc0003c6410, 0x1fde63a4858, 0xc000cc0160, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xc6
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x250b460, 0xc000cc0160, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0xbb3
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00090f9e0, 0x250b460, 0xc000cc0160, 0xc000ca1f00)
	/home/circleci/project/project/dag/walk.go:381 +0x2a2
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:304 +0x1246
```

### Expected Behavior

azurerm_key_vault_access_policy created successfully.

### Actual Behavior

azurerm_key_vault_access_policy crashes Terraform because the app service has app_settings marked as sensitive.

### Steps to Reproduce

Run script in configuration section.

**Comment by alisdair** [comment] 2021-04-22 17:37
Hi @blanchak, thanks for reporting this. It looks like a duplicate of #28370, which has been fixed on the main branch and will go out shortly in 0.15.1.

I was able to verify this with a more complete version of your original config:

```hcl
terraform {
  # For all Terraform configuration settings, see: https://www.terraform.io/docs/configuration/terraform.html
  required_version = "~> 0.15.0"

  # Lock providers to reduce incompatibility between runs
  required_providers {
    azurerm = {
      # see: https://www.terraform.io/docs/providers/azurerm/
      source  = "hashicorp/azurerm"
      version = "~> 2.56"
    }
  }
}

provider "azurerm" {
  skip_provider_registration = true
  features {}
}

variable "location" {
  type    = string
  default = "canadacentral"
}

variable "tmp_settings" {
  description = "Addition settings used to merge with app_settings"
  type        = map(string)
  default     = { "Sensitive_Crash_Test" = "Shhh! This is a secret." }
  sensitive   = true # This will cause azurerm_key_vault_access_policy to crash Terraform.
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "rg" {
  name     = "issue-28488-resources"
  location = var.location
}

resource "azurerm_key_vault" "kv" {
  name                = "vault-26959"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku_name            = "standard"
  tenant_id           = data.azurerm_client_config.current.tenant_id

  access_policy {
    tenant_id          = data.azurerm_client_config.current.tenant_id
    object_id          = data.azurerm_client_config.current.object_id
    secret_permissions = ["delete", "get", "set"]
  }
}

resource "azurerm_app_service_plan" "plan_crash" {
  name                = "example-appserviceplan-crash"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "linux"
  reserved            = true

  sku {
    tier = "PremiumV2"
    size = "P1v2"
  }
}

resource "azurerm_app_service" "app_crash" {
  name                = "example-app-crash"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  app_service_plan_id = azurerm_app_service_plan.plan_crash.id

  app_settings = var.tmp_settings

  identity {
    type = "SystemAssigned"
  }
}

# This will crash Terraform because the app service has app_settings marked as sensitive.
resource "azurerm_key_vault_access_policy" "main" {
  key_vault_id       = azurerm_key_vault.kv.id
  tenant_id          = azurerm_app_service.app_crash.identity[0].tenant_id
  object_id          = azurerm_app_service.app_crash.identity[0].principal_id
  secret_permissions = ["get"]
}
```

This crashes after apply with Terraform 0.15.0, and applies successfully with a build from the latest main branch commit.

**Closed by alisdair** 2021-04-22 17:37 UTC
Labels: bug, v0.15
