### ISSUE TITLE
Outputs not displaying as  expected within powershell 

### ISSUE THREAD

**Issue by joshsw2020** [hashicorp/terraform#24919] opened 2020-05-11 19:09 UTC
resource "aws_eip" "newip" {
  vpc= true
}

output "eip" {
  value = "aws_eip.newip.public_ip"
}

resource "aws_s3_bucket" "mys3bucket" {
  bucket = "testtestbucketjosh"
}

output "mys3bucket" {
  value = "aws_s3_bucket.testtestbucketjosh.bucket_domain_name"

CMD return-------------------------------------------------------------------------------------------------

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

eip = aws_eip.newip.public_ip
mys3bucket = aws_s3_bucket.testtestbucketjosh.bucket_domain_name

**Comment by danieldreier** [comment] 2020-05-12 00:44
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). I don't know what output you're getting vs what you expect, and so I can't tell whether this represents a bug or not.

I'm closing this issue because it doesn't follow the issue template we provide. Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, and then the Terraform maintainers will review it. Thanks!

Beyond using the template, it would help if you could make the following improvements to your issue when you re-file it:

- use GitHub's [text formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax). You can do `markdown` and code formatting to make your code easier to read, which makes it easier for us to understand the issue. Please use markdown to format terraform code like this:
```HCL
resource "null_resource" "example" {
  name = "hello-world"
}
```
Please format terminal output for readability, like:
```shellsession
❯ terraform validate
Success! The configuration is valid.
```
- please provide all of the files involved in reproducing your example. I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

**Closed by danieldreier** 2020-05-12 00:44 UTC
