### ISSUE TITLE
Terraform doesn't use the default value of an argument when passing null

### ISSUE THREAD

**Issue by marcelomilera** [hashicorp/terraform#29136] opened 2021-07-09 22:39 UTC
### Terraform Version
I was able to reproduce it on a variety of versions starting from `0.15.4` and up to the latest

### Terraform Configuration Files
I have `module_a` which may or may not receive an argument of type `list(object{...})`. If the argument is not set, then it should use the default value:
```terraform
variable "input_list" {
  type = list(object({
    foo = string
  }))
  default = [{
    foo = "bar"
  }]
}

output "input_list" {
  value = var.input_list
}
```

Also, I have `module_b` which uses `module_a`:
```terraform
module "unsuccessful" {
  source     = "./module_a"
  input_list = null
}

module "successful" {
  source = "./module_a"
}

output "unsuccessful" {
  value = module.unsuccessful.input_list
}

output "successful" {
  value = module.successful.input_list
}
```

If I call `module_a` without passing the argument, Terraform will pick the default value just fine (`successful`).
However, if I pass a null value, Terraform won't use the default value of the argument from `module_a`. Instead, it will be set to `null` (`unsuccessful`).

### Expected Behavior
According to the documentation: 

> If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one...

Reference: https://www.terraform.io/docs/language/expressions/types.html#null

### Actual Behavior
When passing null, Terraform sets the value of `optional_input` to `null`
After applying the plan, this is what I get using the Terraform console:
```
> module.unsuccessful.input_list
tolist(null) /* of object */

> module.successful.input_list
tolist([
  {
    "foo" = "bar"
  },
])
```

### Steps to Reproduce
Use the snippets from above. 
When running `terraform apply` you'll only get the `successful` output. But you can still inspect the value of the `unsuccessful` output using the Terraform console.

### Additional Context
What I'm trying to achieve is the following:
I want to use `module_a` from another module, but I don't know if I'm going to be passing any value for `module_a` arguments. So, I'm expecting that if I pass an argument with a `null` value Terraform will pick the default value specified in the definition of the variable in `module_a`.

**Comment by jbardin** [comment] 2021-07-12 14:31
Duplicate of #24142

**Closed by jbardin** 2021-07-12 14:31 UTC
Labels: bug, new
