### ISSUE TITLE
NewComputed and ForcesNew attr only diffs dropped if ignore_changes used

### ISSUE THREAD

**Issue by dpiddockcmp** [hashicorp/terraform#17855] opened 2018-04-13 10:06 UTC
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.14.1
```

### Terraform Configuration Files
```hcl
variable "ami" {}

provider "aws" {
   region = "us-east-1"
}

resource "aws_launch_configuration" "test" {
  name_prefix   = "test-"
  image_id      = "${var.ami}"
  instance_type = "t2.micro"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "test" {
  availability_zones        = ["us-east-1e"]
  name                      = "${aws_launch_configuration.test.name}"
  max_size                  = 1
  min_size                  = 0
  desired_capacity          = 0
  launch_configuration      = "${aws_launch_configuration.test.name}"

  lifecycle {
    create_before_destroy = true
    ignore_changes = ["desired_capacity"]
  }
}
```

### Debug Output
trace output created by `script`
https://gist.github.com/dpiddockcmp/c4eee7822364f5f737c769e5f810f8f6

### Expected Behavior
Rerunning the plan with a different AMI should cause both the `aws_launch_configuration` and `aws_autoscaling_group` to be recreated.

### Actual Behavior
Second run with different AMI causes only the `aws_launch_configuration` to be marked for recreation. The apply then fails as the `aws_autoscaling_group` is still using the original launch configuration which cannot be deleted.

### Steps to Reproduce
1. `terraform init`
1. `terraform apply -var ami=ami-1853ac65`
1. `terraform apply -var ami=ami-97785bed`

### Additional Context
The presence of the `ignore_changes` lifecycle block causes this issue, even though it is ignoring an attribute that is not being changed. Removing the `ignore_changes` block causes terraform to behave as desired.

I haven't been able to get the `null_resource` to duplicate this issue as it does not set `NewComputed` on the triggers.

My first thought is a bug in `terraform/eval_diff.go`'s `processIgnoreChanges()`. I'll put in a pull request for that soon. Or is the AWS provider behaving incorrectly by setting `NewComputed` on the `name` attribute when it is being specified by the user? I tried using `name_prefix` instead but get the same result as internally it sets `name`.

### References
- #17338 has the same symptoms but does not mention `ignore_changes`
- https://github.com/terraform-providers/terraform-provider-aws/issues/646#issuecomment-317551675

**Comment by ArturZurawski** [comment] 2018-11-19 00:07
Have that same issue in Terraform v0.11.10 .
It's quite annoying since running terraform while desired_capacity is not ignored and has a different value than one described in tf causes down/upscaling on running cluster.

**Comment by toredash** [comment] 2018-11-28 12:44
Experience the same issue, not with `launch_configuration` but with `launch_template`. Equally annoying

**Comment by marcelboettcher** [comment] 2019-01-05 20:40
This issue still exists in v0.11.11. Are there any plans to fix this?

**Comment by marcelboettcher** [comment] 2019-07-16 15:20
The issue seems to be fixed in v0.12.4.

**Comment by barryib** [comment] 2019-08-01 14:22
This issue still exist in Terraform 0.12.6 !

**Comment by mildwonkey** [comment] 2019-08-01 16:25
Hi folks! I'm sorry for the long silence on this issue. 

Please react to the original issue comment with 👍, which we [can and do report on](https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) during prioritization. 

 "+1" comments creates noise for others watching the issue and ultimately doesn't influence our prioritization.  Thank you!

**Comment by blongman-snapdocs** [comment] 2019-11-19 23:22
Same issue on 0.12.10

**Comment by blongman-snapdocs** [comment] 2019-11-19 23:22
👍

**Comment by apparentlymart** [comment] 2020-06-30 22:37
Hi all,

The implementation of `ignore_changes` was rewritten as part of the configuration language revamp in Terraform v0.12. While I don't doubt that some of you are seeing some similar behavior in Terraform v0.12 releases, the v0.12 is so different that the reproduction cases and logs originally supplied from v0.11.7 are no longer helpful to understand what's going on with v0.12.

For that reason, I'm going to close this issue to represent that the v0.11 manifestation of this issue is resolved. If you are still seeing similar behavior in a v0.12 or later release, please [open a new issue](https://github.com/hashicorp/terraform/issues/new?template=bug_report.md) and complete the issue template so we can see a full reproduction case against the current implementation. We'll then investigate what's going on. `ignore_changes` saw further improvements in Terraform 0.12.9, so we'd ideally like to see reproduction information against a more recent 0.12 release to ensure we're reproducing with the latest `ignore_changes` implementation.

Thanks!

**Closed by apparentlymart** 2020-06-30 22:37 UTC
Labels: bug, core, v0.11
