### ISSUE TITLE
Behaviour of `terraform providers schema` command for computed fields

### ISSUE THREAD

**Issue by rahulrj** [hashicorp/terraform#33006] opened 2023-04-07 22:43 UTC
### Terraform Version

```shell
Terraform v1.4.4 on darwin_arm64
terraform-plugin-sdk - v2.24.1
```

### Terraform Configuration Files

This is the schema code for the provider that i am building. As you can see, this is a nested block in the schema

```terraform
"topic_schemas": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"schema": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Kafka topic schema in string format",
						},
						"schema_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Internal schema ID",
						},
					},
				},
			},
```

Here is a more expanded version of the schema. I have only included the relevant fields
https://gist.github.com/rahulrj/8d6d5cf4a5efc18b60b2b6a0fea34eac

### Debug Output

NA

### Expected Behavior

When i run `terraform providers schema -json` on this provider schema, this field should appear under `block_types` section in the JSON schema representation as mentioned here. This is because the nested block fields appear under `block_types` section

https://developer.hashicorp.com/terraform/cli/commands/providers/schema

### Actual Behavior

When i run `terraform providers schema -json` on this provider schema, i get this field in `attributes` section of the JSON file.
I have redacted some fields to just show the relevant section

<img width="658" alt="Screenshot 2023-04-07 at 3 35 27 PM" src="https://user-images.githubusercontent.com/2638816/230687069-b0332a23-e81b-4bd7-9a3f-be5543ba9873.png">

### Steps to Reproduce

Run `terraform providers schema -json` on the provider binary to get the JSON schema representation

### Additional Context

However, when i add `Optional:true` in topic_schemas in the provider code, the generated JSON shows it correctly in `block_types` section. This looks like a bug. Since `topic_schemas` is a nested block, shouldn't it always go into the `block_types` section? Why does `Optional:true` matter here?`

### References

https://developer.hashicorp.com/terraform/cli/commands/providers/schema

**Comment by apparentlymart** [comment] 2023-04-07 23:07
Hi @rahulrj!

What you've described here is a behavior of the plugin SDK, rather than of Terraform CLI. You can see the relevant logic here: https://github.com/hashicorp/terraform-plugin-sdk/blob/7896600a2987b2ca10bc3a935a9fbd765c86d242/helper/schema/core_schema.go#L96-L101

SDKv2 was originally written for much older versions of Terraform with different expectations than modern Terraform, and so there's various logic to make things behave _as close as possible_ to how older versions of Terraform would treat these situations, and this is one example of that.

You can avoid all of these legacy quirks by using the modern [Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework) instead. The modern framework was designed for modern Terraform and so doesn't have any strange shims and rules like this to preserve compatibility for providers that were originally written for very old versions of Terraform.

I see you already reported this in the SDK repository as https://github.com/hashicorp/terraform-plugin-sdk/issues/1186, so I'm going to close this issue. The SDK developers may be able to offer in that issue some more guidance about ways you could get the result you want _without_ switching to the modern framework, but I expect they will tell you that the SDK is working as designed and cannot be changed because existing providers are relying on that behavior.

Thanks!

**Closed by apparentlymart** 2023-04-07 23:07 UTC
Labels: bug, new

**Comment by rahulrj** [comment] 2023-04-08 01:46
> but I expect they will tell you that the SDK is working as designed and cannot be changed because existing providers are relying on that behavior
@apparentlymart looking for some reason of this behavior. I am assuming if its a nested block, it should not come under attributes. This special case with computed and optional is not documented anywhere.

Also, i am not sure if we migrate everything to the Plugin framework, then the generated schema would be correct. So will have to verify that

**Comment by jbardin** [comment] 2023-04-08 13:22
@rahulrj, A block is only a configuration construct, defining a method for how the attributes can be represented in the configuration. If an attribute is only computed it can’t be represented in the config, so it is treated as a normal attribute.
