### ISSUE TITLE
count not working properly with data template_file

### ISSUE THREAD

**Issue by haghabozorgi** [hashicorp/terraform#22386] opened 2019-08-08 04:22 UTC
Not sure if this is a bug or expected behavior in tf12? 

### Terraform Version

```
Terraform v0.12.6
+ provider.template v2.1.2

```

### Terraform Configuration Files
```
data "template_file" "example_file_fail" {
  template = file("file_that_does_not_exist.yaml.tpl")
  count = 0
}

```
### Expected Behavior
Should ignore this block/noop

### Actual Behavior
```
Error: Error in function call

  on file.tf line 2, in data "template_file" "example_file_fail":
   2:   template = file("file_that_does_not_exist.yaml.tpl")

Call to function "file" failed: no file exists at
file_that_does_not_exist.yaml.tpl.
```

### Steps to Reproduce
create a .tf file with the contents of snippet above and run init, apply. you will get the above error

### Additional Context
This works as expected in tf11 using same block adjusted for tf11 syntax differences, e.g
```
data "template_file" "example_file_fail" {
  template = "${file("file_that_does_not_exist.yaml.tpl")}"
  count = 0
}
```

It also works with tf12 if the template is referencing a string as opposed to a file, e.g
```
data "template_file" "example_string" {
  template = "random_string"
  count = 0
}
```

**Comment by apparentlymart** [comment] 2019-08-09 01:07
Hi @haghabozorgi,

As warned in [the `file` documentation](https://www.terraform.io/docs/configuration/functions/file.html), the `file` function is only for files that exist on disk statically as part of the configuration, and it gets evaluated very early on in Terraform's configuration loading so that the configuration can be fully validated. This is the same mechanism by which Terraform would tell you that `1 + {}` is invalid because the types don't match regardless of `count`: every individual expression in the configuration must be valid before any further processing can begin.

Terraform 0.11 would sometimes not catch problems until the plan step because because its validation logic was more limited, but it's intentional that a file not existing is considered an error with `file(...)`, even if `count = 0`, and Terraform 0.11's behavior in this case is incorrect.

If you wish to _dynamically_ read a file (that is, as part of the real Terraform operation where `count` is considered, rather than during configuration loading) then you'll need to use [the `local_file` data source](https://www.terraform.io/docs/providers/local/d/file.html) instead:

```hcl
data "local_file" "example" {
  filename = "file_that_does_not_exist.yaml.tpl"
  count = 0
}

data "template_file" "example" {
  template = data.local_file.example.content
  count = 0
}
```

Because `local_file` is a data source rather than a static configuration construct, Terraform will not call it at all when `count = 0`.

Because the behavior you observed is as intended, I'm going to close this issue now. The `local_file` approach will allow you to read a template file dynamically in unusual situations where that is needed.

**Closed by apparentlymart** 2019-08-09 01:07 UTC
Labels: bug, config

**Comment by haghabozorgi** [comment] 2019-08-09 15:46
Thanks @apparentlymart  for your thorough reply. Apologies, I did not see that spelled out in the doc and notice it is also spelled out in templatefile docs which states when needing to generate dynamic template use template_file, but The snippet you posted as an example seems to also fail, that is 

```
data "local_file" "example" {
  filename = "file_that_does_not_exist.yaml.tpl"
  count = 0
}

data "template_file" "example" {
  template = data.local_file.example.content
  count = 0
}
```

returns 

```
Error: Missing resource instance key

  on file.tf line 7, in data "template_file" "example":
   7:   template = data.local_file.example.content

Because data.local_file.example has "count" set, its attributes must be
accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    data.local_file.example[count.index]
```
