### ISSUE TITLE
for_each key and values are correct but not used as values

### ISSUE THREAD

**Issue by Borrelworst** [hashicorp/terraform#28012] opened 2021-03-08 11:08 UTC
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/carlpett/sops v0.6.0
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.49.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
```

### Use cases
I am trying to get my secrets file (created with sops) to be added to Azure Keyvault. I've created a sops file like this:

```yaml
---
testcase:
    username: password
```
As I don't want to create a resource block for every single entry I am trying to loop over all values and add key and values to keyvault more automatically.

I've created a keyvault secrets block like so:
```terraform
resource "azurerm_key_vault_secret" "testcase" {
  for_each     = yamldecode(data.sops_file.tooling_passwords.raw).testcase
  name         = data.sops_file.my_sops_file.data[each.key]
  value        = data.sops_file.my_sops_file.data[each.value]
  key_vault_id = azurerm_key_vault.kv.id
}
```
When running terraform plan, I am getting the following output:
```terraform
Error: Invalid index

  on 07-secrets.tf line 3, in resource "azurerm_key_vault_secret" "testcase":
   3:   name         = data.sops_file.tooling_passwords.data[each.key]
    |----------------
    | data.sops_file.tooling_passwords.data is map of string with 15 elements
    | each.key is "username"

The given key does not identify an element in this collection value.

Error: Invalid index

  on 07-secrets.tf line 4, in resource "azurerm_key_vault_secret" "testcase":
   4:   value        = data.sops_file.tooling_passwords.data[each.value]
    |----------------
    | data.sops_file.tooling_passwords.data is map of string with 15 elements
    | each.value is "password"

The given key does not identify an element in this collection value.
```
The output of each.key and each.value is correct: This is exactly what I want to add to the keyvault, but it does error with the error _The given key does not identify an element in this collection value._ 

### Additional Context
I am not sure if it is a bug or that I am confused about the for_each module. However, as the values are exactly what I need, it looks like a non-issue that is reported as such.

**Comment by jbardin** [comment] 2021-03-08 14:28
Hi @Borrelworst,

I'm not able to reproduce this from the information given. Can you show what the actual value of `data.sops_file.tooling_passwords.data` is? It may be that the map, keys and values are not formatted in the manner you expect.

While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there may be more users familiar with the `sops` provider, and and can help answer general usage questions.

**Comment by Borrelworst** [comment] 2021-03-15 14:49
Hi jbardin,

This is the actual output from `data.sops_file.tooling_passwords.data`:

```
Changes to Outputs:
  + testoutput = {
      + "testcase.username"              = "password"
```

**Comment by jbardin** [comment] 2021-03-15 15:07
It hard to determine what the complete structure of `data.sops_file.my_sops_file.data` is here, but the `testoutput` here contains a key of `testcase.username` which maps to the password, while you are indexing the data using just `username` and `password`.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by jbardin** 2021-03-15 15:07 UTC
Labels: bug, waiting for reproduction
