### ISSUE TITLE
terraform crashes if provider returns value that does not conform to expected schema

### ISSUE THREAD

**Issue by sebhoss** [hashicorp/terraform#32092] opened 2022-10-27 05:48 UTC
### Terraform Version

```shell
Terraform v1.4.0-dev
on linux_amd64
```

### Terraform Configuration Files

```terraform
# this is a simplified example
resource "example_resource" "testcase" {
  list_of_objects = [
    {
      name = "first"
      dynamic_attribute = 123 # NOTE: this is a dynamic type
    },
    {
      name = "second" # NOTE: dynamic_attribute is missing here
    },
  ]
}
```

### Debug Output

https://gist.githubusercontent.com/sebhoss/ce219211c36bdb647893ddcb8ebfb8f0/raw/8714db3dc95b017aa7f08123c147829eb0d92357/logoutput.txt (crash is at the bottom)

### Expected Behavior

I think Terraform Core should catch this issue sooner and tell the user that there is a problem with the provider rather than crash.

### Actual Behavior

There is a crash in Terraform Core

### Steps to Reproduce

1. `git clone https://github.com/metio/terraform-provider-k8s.git`
2. `cd terraform-provider-k8s`
3. `git switch issue-147`
4. `make terratest TestAppsStatefulSetV1Resource`

Note that the last step builds & installs the provider locally. I've only tested the install step (`make install`) on linux systems and it probably needs adjustments for mac/windows. Let me know if there is something I can do to help..

### Additional Context

- The issue was discovered while trying to implement a dynamic type which is currently NOT supported as explained in https://github.com/hashicorp/terraform-plugin-framework/issues/147
- The reproducible example above runs tests in Terratest but the error remains when using Terraform directly
- I've created a PR at https://github.com/metio/terraform-provider-k8s/pull/45 that triggers this crash
- The code for the custom type is at https://github.com/metio/terraform-provider-k8s/blob/main/internal/utilities/int_or_string.go
- The code for the resource that is involved in the example is at https://github.com/metio/terraform-provider-k8s/blob/main/internal/provider/resource_apps_stateful_set_v1.go
- The example usage of the resource from the log output is at https://github.com/metio/terraform-provider-k8s/blob/issue-147/examples/resources/k8s_apps_stateful_set_v1/resource.tf

### References

https://github.com/hashicorp/terraform-plugin-framework/issues/147

**Comment by sebhoss** [comment] 2022-10-27 06:04
Forgot to add the output of `terraform providers schema -json`: https://gist.github.com/sebhoss/886a7588ffff04aca04f9a88a3748503 contains the schema for the resource in the example. It was created by running:

1. `cd examples/resources/k8s_apps_stateful_set_v1`
2. `terraform providers schema -json | jq '.provider_schemas."localhost/metio/k8s".resource_schemas.k8s_apps_stateful_set_v1' > schema.json`

**Comment by jbardin** [comment] 2022-10-27 12:53
Thanks @sebhoss!

We are tracking the task to write more involved client-side validation in #30669.

Duplicate of #30669

**Closed by jbardin** 2022-10-27 12:53 UTC
Labels: bug, new
