### ISSUE TITLE
Destroy fails planning on partially deployed/destroyed infrastructure

### ISSUE THREAD

**Issue by lemaitre-aneo** [hashicorp/terraform#32452] opened 2023-01-04 09:04 UTC
### Terraform Version

```shell
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.1

Your version of Terraform is out of date! The latest version
is 1.3.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
variable "foo" {
  type = string
  default = "foo"
}

resource "null_resource" "a" {
  count = 1
  triggers = {
    a = var.foo
  }
}

resource "null_resource" "b" {
  triggers = {
    b = var.foo
  }

  provisioner "local-exec" {
    when = destroy
    command = "exit $((RANDOM % 2))"
    interpreter = ["bash", "-c"]
  }
}

output "a" {
  value = null_resource.a[0].triggers.a
}
output "b" {
  value = null_resource.b.triggers.b
}
```

### Debug Output

https://gist.github.com/lemaitre-aneo/37c61983041aaabf86763783b3f8ceeb

### Expected Behavior

Plan destroy should succeed.

### Actual Behavior

```sh
$ terraform apply -destroy
null_resource.b: Refreshing state... [id=7666234309702249871]
╷
│ Error: Invalid index
│
│   on test.tf line 26, in output "a":
│   26:   value = null_resource.a[0].triggers.a
│     ├────────────────
│     │ null_resource.a is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -target=null_resource.b`
3. `terraform destroy`

### Additional Context

This does occur whenever the deployment is neither empty nor complete. In this example, it happens when there is only `null_resource.b`deployed, and not `null_resource.a[0]`.

This can be the case if there were a partial deployement (`terraform apply -target null_resource.b`), a partial destroy (`terraform destroy -target null_resource.a[0]`), or more problematically a failed destroy (`terraform destroy`). The example terraform has a probabilty 0.5 to fail (randomly), so you can just apply and destroy until you see the problem.

Once the destroy has failed once leaving only `null_resource.b`, further destroys will fail *planning*.

As far as I'm aware, this worked fine in 1.2.

**Comment by jbardin** [comment] 2023-01-04 14:13
Hi @lemaitre-aneo,

This appears to be fixed in the current release, most likely a duplicate of #32185

Thanks!

**Closed by jbardin** 2023-01-04 14:13 UTC
Labels: bug, new

**Comment by lemaitre-aneo** [comment] 2023-01-04 14:26
You're right, it does work as expected in 1.3.6. I think I still have similar issues on my real deployment, but I need to investiguate more on the subject. If I get a small reproducible example that does not work in 1.3.6, I will get back to you.

Thank you for your reactivity!
