### ISSUE TITLE
terraform crashed! 

### ISSUE THREAD

**Issue by macthange** [hashicorp/terraform#29329] opened 2021-08-09 11:10 UTC
panic: value is marked, so must be unmarked first

goroutine 2148 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.True(0x37600c0, 0xc00011eaa1, 0x3055de0, 0xc0026286a0, 0x37600c0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/value_ops.go:360 +0x59
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc00018d5e0, 0xc0024c20a0, 0x0, 0x14, 0xc00169b9c0, 0xc00011ea01, 0x37600c0, 0xc00011eaa0, 0x2f33c00)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hclsyntax/expression.go:601 +0xfb0
github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc001844120, 0xc00086f2c0, 0x0, 0x0, 0x0, 0xc0024c20a0, 0x37600c0, 0xc00011eaa0, 0x2f33c00, 0x48559e0, ...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/spec.go:205 +0x2bb
github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc00180fd10, 0xc00086f2c0, 0x0, 0x0, 0x0, 0xc0024c20a0, 0xc000a493c0, 0x20, 0x20, 0xc002628220, ...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/spec.go:79 +0x23b
github.com/hashicorp/hcl/v2/hcldec.decode(0x375f040, 0xc002628220, 0x0, 0x0, 0x0, 0xc0024c20a0, 0x375fe80, 0xc00180fd10, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/decode.go:21 +0x11c
github.com/hashicorp/hcl/v2/hcldec.Decode(...)
        /go/pkg/mod/github.com/hashicorp/hcl/v2@v2.7.2/hcldec/public.go:15
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc0011bdd60, 0x375e8c0, 0xc00249dc50, 0xc00190f050, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)  
        /home/circleci/project/project/lang/eval.go:67 +0x2be
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc00105d860, 0x375e8c0, 0xc00249dc50, 0xc00190f050, 0x0, 0x0, 0x37600c0, 0xc00011ea8f, 0x330bcc0, 0xc00249d230, ...)
        /home/circleci/project/project/terraform/eval_context_builtin.go:280 +0x1bb
github.com/hashicorp/terraform/terraform.(*EvalDiff).Eval(0xc0024b9a98, 0x379c200, 0xc00105d860, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/eval_diff.go:156 +0x27c
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc00238efb0, 0x379c200, 0xc00105d860, 0x0, 0xc002040000)
        /home/circleci/project/project/terraform/node_resource_plan_instance.go:207 +0x5ad
github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc00238efb0, 0x379c200, 0xc00105d860, 0xc0028e6002, 0x2faf140, 0x32be260)
        /home/circleci/project/project/terraform/node_resource_plan_instance.go:39 +0xf1
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000adf520, 0x379c200, 0xc00105d860, 0x25cf1a459a0, 0xc00238efb0, 0x0, 
0x0, 0x0)
        /home/circleci/project/project/terraform/graph_walk_context.go:127 +0xc3
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x32be260, 0xc00238efb0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/graph.go:59 +0x97e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0008ace40, 0x32be260, 0xc00238efb0, 0xc00243bf00)
        /home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /home/circleci/project/project/dag/walk.go:309 +0x1246

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment] 2021-08-09 13:01
Hi @macthange,

Thanks for reporting the crash. This looks like a bug which was fixed in earlier versions of terraform. Can you confirm you are running the latest version, and if so, possibly share the configuration and steps which caused the panic.

Thanks!

**Comment by jbardin** [comment] 2021-08-11 18:50
Since this appears to be an old version of terraform I'm going to close out the issue. If you can reproduce the crash on a current release, please feel free to reply here with the relevant information, or open a new issue.

Thanks!

**Closed by jbardin** 2021-08-11 18:50 UTC
Labels: bug, waiting-response, new, waiting for reproduction
