### ISSUE TITLE
Error with vsphere provider - network not found

### ISSUE THREAD

**Issue by rbriancollins** [hashicorp/terraform#6266] opened 2016-04-20 19:00 UTC
Very new to terraform.  Using version 0.6.14.
### Affected Resource(s)
- vsphere_virtual_machine
### Terraform Configuration Files

``` hcl
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"
  allow_unverified_ssl = "true"
}


resource "vsphere_virtual_machine" "test" {
  name   = "terraform-test2"
  resource_pool = "VBLOCK1"
  vcpu   = 2
  memory = 4096

  network_interface {
    label = "vm63"
    ipv4_address = "10.141.63.239"
    ipv4_prefix_length = "24"
  }

  disk {
    template = "Templates/rhel6_base_tf"
    type = "thin"
    datastore = "VBLOCK_DATA"
  }
}
```
### Debug Output

https://gist.github.com/rbriancollins/8e0308c372f16a2051a98f735ea9d998
### Expected Behavior

terraform creates a new VM from a template
### Actual Behavior

terraform exited with "vsphere_virtual_machine.test: network '*vm63' not found"
### Steps to Reproduce
1. `terraform apply`
### Important Factoids

The VM networks we want to use are on a DV switch under a sub-folder, so:
MD(the datacenter)/VBLOCKVMS01/VBLOCKVSM01/vm63.  I am able to see it with govc:

``` hcl
$ govc ls /MD/network/VBLOCKVSM01/ | egrep 63
/MD/network/VBLOCKVSM01/vm63
```

The first VBLOCKVSM01 is a folder, the second is a DV switch.
If I reference a network directly under the folder, it works.  For example, there is a network called vblock_esx_build, and it is located like so:
MD/VBLOCKVSM01/vblock_esx_build
It is not on a DV switch.

To test further, I put the relative path to vm63 in the config file and managed to crash terraform with:
panic: reflect.Set: value of type mo.DistributedVirtualSwitch is not assignable to type mo.VmwareDistributedVirtualSwitch

**Comment by Shruti29** [comment] 2016-04-21 05:00
+1 on this.

Facing the exact same issue.
My network **test-vm-net** is under a subfolder called **dVS**
I even tried adding the path of the label. It fails either way.

```
  network_interface {
        label = "dVS/test-vm-net"
        ipv4_address = "10.4.1.15"
        ipv4_prefix_length = "255.255.255.0"
    }
```

**Comment by rbriancollins** [comment] 2016-04-21 11:24
Thanks @Shruti29.  I did try that, but terraform crashed when I did it. My network is listed at:
```hcl
$ govc ls /MD/network/VBLOCKVSM01 | grep vm63
/MD/network/VBLOCKVSM01/vm63
```
Changing my config to:
```hcl
  network_interface {
    label = "VBLOCKVSM01/vm63"
    ipv4_address = "10.141.63.239"
    ipv4_prefix_length = "24"
  }
```
Triggers the crash.  I'll post the crash log and link to it shortly.

**Comment by chrislovecnm** [comment] 2016-04-22 15:44
This may be a duplicate issue as we are having some interesting behavior with network search at this point.

@rbriancollins can you look up the network using [govc](https://github.com/vmware/govmomi/tree/master/govc) and get us the results?

cc:  @markpeek @frapposelli we are having some odd results with network lookups.  I believe this is a duplicate of the network bug that I sent you.

**Comment by rbriancollins** [comment] 2016-04-22 18:28
Certainly...
```hcl
$ govc ls /MD/network/VBLOCKVSM01 | egrep vm63
/MD/network/VBLOCKVSM01/vm63
```

**Comment by mikaelfrykholm** [comment] 2017-02-14 09:45
We are having the same issue. 
govc ls /Cloud/network/AC19VSM03/2154\*
/Cloud/network/AC19VSM03/2154-LED-ENV-9-MGMT-IN

Could it be related to the distributed switch is a Cisco_Nexus_1000V ?
Please let me know if I can help troubleshoot.

**Comment by kiketid** [comment] 2017-02-17 12:51
same problem here with terraform version 0.8.5, vmware 5.5 and Distributed Switch Cisco_Nexus_1000v

 govc ls  /DC/network/Nexus1000v 
/DC/network/Nexus1000v/LABONESQL_HBEAT_CERT
/DC/network/Nexus1000v/LABONESQL_HBEAT_PRE
/DC/network/Nexus1000v/LABONESQL_HBEAT_PROD

but using Nexus1000v/LABONESQL_HBEAT_PRE  in the provider results in a crash

**Closed** 2017-06-13 16:52 UTC
Labels: bug, crash, provider/vsphere

**Comment by iahmad-khan** [comment] 2017-08-09 14:49
Hi , 

I just faced the same problem here , when I dont mention the folder name it says , network not found.

But when I mention full path , it crashes.

**Comment by vancluever** [comment] 2017-08-23 00:34
Hey all! If anyone is still watching this issue - please see the linked issue in the split provider repository - I have not been able to reproduce it with a version the vsphere provider built from master, so I think we might have a fix for this in the next release.

Please head on over to terraform-providers/terraform-provider-vsphere#14 and let me know.

Thanks!

**Comment by afortes** [comment] 2018-01-26 19:23
Hey @vancluever,
With the latest version of terraform (0.11.2), vpshere provider (1.2.0) and vmware 5.5 the same issue appears.

`data "vsphere_distributed_virtual_switch" "dvs" {
  name          = "Nexus1000v/Nexus1000v"
  datacenter_id = "${data.vsphere_datacenter.example_datacenter.id}"
}`

`govc ls -l -i /BOECILLO/network/Nexus1000v
DistributedVirtualSwitch:dvs-58 /MYDATACENTER/network/Nexus1000v/Nexus1000v`

`Error: Error refreshing state: 1 error(s) occurred:

* data.vsphere_distributed_virtual_switch.dvs: 1 error(s) occurred:

* data.vsphere_distributed_virtual_switch.dvs: data.vsphere_distributed_virtual_switch.dvs: error fetching distributed virtual switch: network at path "Nexus1000v/Nexus1000v" is not a VMware distributed virtual switch (type DistributedVirtualSwitch)`
