### ISSUE TITLE
terraform chef provisioner installation fails on windows server 2019

### ISSUE THREAD

**Issue by 422158** [hashicorp/terraform#20689] opened 2019-03-14 12:45 UTC
Hello fellas,

I have a problem with installation of a chef on windows server 2019. Chef installation works on win 2016, 2012r2, or ubuntu18.04, but it fails on windows server 2019. 
From the error and after checking the source code of chef provisioner I am able to see in which phase chef installation fails (it is directory preparation), however I am unable to understand why this happens on win server 2019 only.
### Terraform Version

```
v 0.11.13
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

```
Error: Error applying plan:

1 error(s) occurred:
--

* module.vm2-provision.null_resource.chef_installation: error executing  "cmd /c if not exist \"C:/chef\" mkdir \"C:/chef\"": Command has already  been closed


```

### Expected Behavior

Chef should have been succesfuly installed
### Actual Behavior

Chef installation fails

**Comment by mildwonkey** [comment] 2019-03-14 18:23
Hi @422158, I am sorry you are experiencing this issue.
Can you please update this issue, filling out the requested fields (terraform configuration files, debug output, etc) so someone can take a look?

**Comment by 422158** [comment] 2019-03-18 06:34
@mildwonkey I am using vmware provider and a custom template containing windows server 2019, so posting configuration files does not seems to be any use... I will try to reproduce on azure on clean windows server 2019 and post an example so others can take a look....

**Comment by 422158** [comment] 2019-03-19 09:23
ok when replicating an issue on azure I have stumbleded uppon different error, even though it might be related. I am providing you with my configuration which was used to deploy vanilla windows server 2019 datacenter.  Feel free to try it on your own (however you need chef server deployed and configured):

terraform version `v 0.11.10`
provider azurerm `v1.23.0`
provider null `v2.1.0`

```
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  tenant_id = "${var.tenant_id}"
  client_id = "${var.client_id}"
  client_secret = "${var.client_secret}"
}

variable "prefix" {
  default = "chef-tst"
}

resource "azurerm_resource_group" "main" {
  name     = "${var.prefix}-resources"
  location = "West Central US"
}

resource "azurerm_network_interface" "main" {
  name                = "${var.prefix}-nic-${count.index}"
  count		      = 8
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  network_security_group_id = "/subscriptions/1c6c92a0-f729-4d8b-8e75-1d780a05af1b/resourceGroups/terraform-testing/providers/Microsoft.Network/networkSecurityGroups/terraform-spawns-nsg"  

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = "/subscriptions/1c6c92a0-f729-4d8b-8e75-1d780a05af1b/resourceGroups/terraform-managed/providers/Microsoft.Network/virtualNetworks/initial-virtual-network/subnets/initial-subnet"
    private_ip_address_allocation = "Dynamic"
  }
}


resource "azurerm_virtual_machine" "main" {
  name                  = "host-${count.index}"
  location              = "${azurerm_resource_group.main.location}"
  resource_group_name   = "${azurerm_resource_group.main.name}"
  network_interface_ids = ["${azurerm_network_interface.main.*.id[count.index]}"]
  vm_size               = "${count.index > 3 ? "Standard_D4_v3" : "Standard_B2MS"}"
  count			= 8
  # Uncomment this line to delete the OS disk automatically when deleting the VM
  delete_os_disk_on_termination = true


  # Uncomment this line to delete the data disks automatically when deleting the VM
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-Datacenter"
    version   = "latest"
  }
  storage_os_disk {
    name              = "disk-${count.index}"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  os_profile {
    computer_name  = "host-${count.index}"
    admin_username = "testadmin"
    admin_password = "Password1234!"
    custom_data    = "Param($ComputerName = \"host-${count.index}\") ${file("${path.root}/winrm.ps1")}"
  }

  os_profile_windows_config {
    enable_automatic_upgrades = false
    provision_vm_agent        = true

    additional_unattend_config {
      pass         = "oobeSystem"
      component    = "Microsoft-Windows-Shell-Setup"
      setting_name = "AutoLogon"
      content      = "<AutoLogon><Password><Value>Password1234!</Value></Password><Enabled>true</Enabled><LogonCount>1</LogonCount><Username>testadmin</Username></AutoLogon>"
    }

    # Unattend config is to enable basic auth in WinRM, required for the provisioner stage.
    additional_unattend_config {
      pass         = "oobeSystem"
      component    = "Microsoft-Windows-Shell-Setup"
      setting_name = "FirstLogonCommands"
      content      = "${file("${path.root}/FirstLogonCommands.xml")}"
    }
  }
}

resource "null_resource" "chef_client" {
  depends_on = ["azurerm_virtual_machine.main"]
  count      = 8
  connection {
    type     = "winrm"
    user     = "testadmin"
    password = "Password1234!"
    host     = "${azurerm_network_interface.main.*.private_ip_address[count.index]}"
    timeout  = "10m"
    port     = 5985
    https    = false
    insecure = true
  }
  
  provisioner "local-exec" {
    command = "sleep 20"
  }

  provisioner "chef" {
    node_name       = "host-${count.index}"
    version         = "13.8.5"
    server_url      = "https://11.0.1.35/organizations/myorg"
    ssl_verify_mode = "verify_none"
    recreate_client = true
    user_name       = "simonobetko"
    user_key        = "${file("/home/terraform-admin/terraform_configurations/resource_groups/private-resources/private_chef_server/simonobetko.pem")}"
    run_list        = []

    client_options = ["log_location 'C:\\chef\\chef_run.log'",
      "log_level :info",
    ]

    attributes_json = ""
  }
}
```

The error I am getting is 
```
Error: Error applying plan:

1 error(s) occurred:

* null_resource.chef_client[2]: Uploading client.rb failed: Error uploading file to $env:TEMP\winrmcp-13d8feeb-9921-436e-7f5f-3fbb3c50cf6c.tmp: Couldn't create shell: unknown error Post http://11.0.1.15:5985/wsman: read tcp 11.0.1.4:51706->11.0.1.15:5985: read: connection reset by peer
```

If I go deeper into the outputs of terraform to explore issue behind above error I find this (notice the lines indented by `---`. These are the lines of provisioner that failed):
```
---null_resource.chef_client[2] (chef): Connecting to remote host via WinRM...
---null_resource.chef_client[2] (chef):   Host: 11.0.1.15
---null_resource.chef_client[2] (chef):   Port: 5985
---null_resource.chef_client[2] (chef):   User: testadmin
---null_resource.chef_client[2] (chef):   Password: true
---null_resource.chef_client[2] (chef):   HTTPS: false
---null_resource.chef_client[2] (chef):   Insecure: true
---null_resource.chef_client[2] (chef):   NTLM: false
---null_resource.chef_client[2] (chef):   CACert: false
null_resource.chef_client[3] (chef): Downloading Chef Client...
null_resource.chef_client[5] (chef): Installing Chef Client...
null_resource.chef_client[3] (chef): Installing Chef Client...
---null_resource.chef_client[2] (chef): Connected!
---null_resource.chef_client[2] (chef): Cleanup user key...
null_resource.chef_client[0] (chef): Connected!
null_resource.chef_client[1] (chef): Connecting to remote host via WinRM...
null_resource.chef_client[1] (chef):   Host: 11.0.1.13
null_resource.chef_client[1] (chef):   Port: 5985
null_resource.chef_client[1] (chef):   User: testadmin
null_resource.chef_client[1] (chef):   Password: true
null_resource.chef_client[1] (chef):   HTTPS: false
null_resource.chef_client[1] (chef):   Insecure: true
null_resource.chef_client[1] (chef):   NTLM: false
null_resource.chef_client[1] (chef):   CACert: false
null_resource.chef_client[6] (chef): Installing Chef Client...
---null_resource.chef_client[2] (chef): The system cannot find the path specified.
---null_resource.chef_client[2] (chef): WARNING: Failed to cleanup user key on new node: "cd C:/chef && del /F /Q simonobetko.pem" exit status: 1
```

If you look at the outputs, it is visible that terraform is trying to initiate `Cleanup user key` before even downloading or installing chef client. 
Interestingly there is always only single machine (and it is NOT always the same one) that fails. Rest of the machines download install and configure the chef correctly. 

We previously did bigger deployments than 8 machines with windows server 2016 ubuntu or others and it was working. Issue only appears with windows server 2019

Thank you for your help.

**Comment by jcruzfrontline** [comment] 2019-06-06 15:53
I am experiencing this issue with W2016 with the exact same symptoms

**Comment by barracksbuilder** [comment] 2019-09-06 19:14
I run windows server 2016 and 2019 on VMware 6.7U3 and am receiving the same problem

```
Terraform v0.12.7
+ provider.local v1.3.0
+ provider.vsphere v1.12.0
```

```module.test-1.vsphere_virtual_machine.vm (chef): Creating configuration files...
module.test-1.vsphere_virtual_machine.vm (chef): Cleanup user key...
module.test-1.vsphere_virtual_machine.vm (chef): Could Not Find C:\chef\user.pem
module.test-1.vsphere_virtual_machine.vm: Creation complete after 8m54s [id=423e362e-24ac-fde9-e8b1-ca29550e570f]
```

Chef is installed but the node is not bootstrapped.

**Comment by gyamada619** [comment] 2020-02-04 16:59
We are experiencing this same error as well when trying to provision a Windows 2019 server in vSphere:

```
error executing  "cmd /c if not exist \"C:/chef\" mkdir \"C:/chef\"": Command has already  been closed
```

**Comment by darryldunkin** [comment] 2020-05-07 01:10
I can reproduce this consistently between two different images. The "Command has already been closed" error only occurs when there is an existing installation of Chef already on the image.

Without a pre-existing install of Chef, Terraform installs via ChefClient.ps1 and uploading the keys goes fine:
```
2020-05-06T17:57:50.362-0700 [DEBUG] plugin.terraform: chef-provisioner (internal) 2020/05/06 17:57:50 [DEBUG] connecting to remote shell using WinRM
module.vm1.vsphere_virtual_machine.vm (chef): Connected!                                                                                                                                    2020-05-06T17:57:50.572-0700 [DEBUG] plugin.terraform: chef-provisioner (internal) 2020/05/06 17:57:50 [DEBUG] Uploading file to 'C:/Temp/ChefClient.ps1'
2020-05-06T17:57:54.343-0700 [DEBUG] plugin.terraform: chef-provisioner (internal) 2020/05/06 17:57:54 [DEBUG] starting remote command: powershell -NoProfile -ExecutionPolicy Bypass -File
C:/Temp/ChefClient.ps1                                                                                                                                                                      module.vm1.vsphere_virtual_machine.vm (chef): Downloading Chef Client...
module.vm1.vsphere_virtual_machine.vm (chef): Installing Chef Client...                                                                                                                     module.vm1.vsphere_virtual_machine.vm: Still creating... [3m50s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [4m0s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [4m10s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [4m20s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [4m30s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [4m40s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [4m50s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [5m0s elapsed]                                                                                                                     module.vm1.vsphere_virtual_machine.vm: Still creating... [5m10s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [5m20s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [5m30s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [5m40s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [5m50s elapsed]                                                                                                                    module.vm1.vsphere_virtual_machine.vm: Still creating... [6m0s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [6m10s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [6m20s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [6m30s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [6m40s elapsed]                                                                                                                    module.vm1.vsphere_virtual_machine.vm: Still creating... [6m50s elapsed]                                                                                                                    module.vm1.vsphere_virtual_machine.vm: Still creating... [7m0s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [7m10s elapsed]
module.vm1.vsphere_virtual_machine.vm: Still creating... [7m20s elapsed]
2020-05-06T18:01:36.126-0700 [DEBUG] plugin.terraform: chef-provisioner (internal) 2020/05/06 18:01:36 [DEBUG] starting remote command: cmd /c if not exist "C:/chef" mkdir "C:/chef"
module.vm1.vsphere_virtual_machine.vm (chef): Creating configuration files...
2020-05-06T18:01:36.481-0700 [DEBUG] plugin.terraform: chef-provisioner (internal) 2020/05/06 18:01:36 [DEBUG] Uploading file to 'C:/chef/delivery.pem'
2020-05-06T18:01:37.646-0700 [DEBUG] plugin.terraform: chef-provisioner (internal) 2020/05/06 18:01:37 [DEBUG] Uploading file to 'C:/chef/client.rb'
module.vm1.vsphere_virtual_machine.vm: Still creating... [7m30s elapsed]
```

**Comment by izz-linux** [comment] 2020-05-11 16:33
I am seeing the exact same issue as @barracksbuilder 
2012 provisions work, but 2016 do not.
```
vsphere_virtual_machine.wst-q-eng-ci-servers[0] (chef): Cleanup user key...
vsphere_virtual_machine.wst-q-eng-ci-servers[0] (chef): Could Not Find C:\chef\terraform.pem
```
```
Terraform v0.12.10
+ provider.aws v2.50.0
+ provider.vsphere v1.16.1
```
I'm using SSM in AWS for secrets, thus the AWS provider.

**Comment by marioanton** [comment] 2020-08-24 11:23
I guess you have already checked that out but that might be related to the privileges asssigned to the user doing the winrm conn. It can be lack of prvis so would check that out .

**Comment by danieldreier** [comment] 2020-10-15 18:07
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.

**Closed by danieldreier** 2020-10-15 18:07 UTC
Labels: needs-maintainer, provisioner/chef
