### ISSUE TITLE
Using a dynamic block in provisioner block causes segfault

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/terraform#25934] opened 2020-08-20 12:25 UTC
### Terraform Version
I'm running `v0.12.29`.

### Terraform Configuration Files

I'm trying to use the same Terraform module to configure both Linux and Windows hosts - for more details see my [forum post](https://discuss.hashicorp.com/t/is-it-possible-to-make-a-provisioner-block-optional/13111) - because the former needs a `provisioner` block while the latter does not:
```terraform
  provisioner "ansible" {
    dynamic "plays" {
      for_each = var.ps_setup_script == "" ? [1] : []
      content {
        playbook {
          file_path = "${path.cwd}/ansible/bootstrap.yml"
        }
      }
    }
  }
```

### Crash Output
When I try to apply this Terraform fails with a segfault:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdc8327]

goroutine 1009 [running]:
github.com/hashicorp/terraform/lang/blocktoattr.walkVariables(0x22d2280, 0xc0005e62c0, 0x0, 0xc000136001, 0x22d2280, 0xc0005e62c0, 0x0, 0x0, 0x0, 0xa7)
	/build/go/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:34 +0x1b7
github.com/hashicorp/terraform/lang/blocktoattr.ExpandedVariables(...)
	/build/go/src/github.com/hashicorp/terraform/lang/blocktoattr/variables.go:24
github.com/hashicorp/terraform/lang.ReferencesInBlock(0x22d2280, 0xc0005e62c0, 0x0, 0x2, 0x2, 0x17, 0xc00003f3a8, 0x4, 0xc0013c9780)
	/build/go/src/github.com/hashicorp/terraform/lang/references.go:68 +0x65
github.com/hashicorp/terraform/terraform.(*NodeAbstractResource).References(0xc0008351e0, 0x450693, 0xc000e155e7, 0xc0004ef4a0)
	/build/go/src/github.com/hashicorp/terraform/terraform/node_resource_abstract.go:219 +0x4d0
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).References(0xc0008351e0, 0x0, 0x0, 0x0)
	/build/go/src/github.com/hashicorp/terraform/terraform/node_resource_abstract.go:244 +0x2e1
github.com/hashicorp/terraform/terraform.NewReferenceMap(0xc001fb2f30, 0x1, 0x1, 0x1)
	/build/go/src/github.com/hashicorp/terraform/terraform/transform_reference.go:492 +0x24a
github.com/hashicorp/terraform/terraform.(*ReferenceTransformer).Transform(0x3374b00, 0xc00109e5a0, 0x14, 0x0)
	/build/go/src/github.com/hashicorp/terraform/terraform/transform_reference.go:79 +0x71
github.com/hashicorp/terraform/terraform.(*BasicGraphBuilder).Build(0xc002199b30, 0xc000e5b740, 0x1, 0x1, 0x1, 0x4d, 0xc000844d80, 0x17)
	/build/go/src/github.com/hashicorp/terraform/terraform/graph_builder.go:50 +0x476
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResource).DynamicExpand(0xc0008f3f20, 0x2300780, 0xc0012248f0, 0x0, 0x0, 0x0)
	/build/go/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:119 +0x88b
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1d160c0, 0xc0008f3f20, 0x0, 0x0, 0x0)
	/build/go/src/github.com/hashicorp/terraform/terraform/graph.go:103 +0xabf
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000194400, 0x1d160c0, 0xc0008f3f20, 0xc0017c7a40)
	/build/go/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x357
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/build/go/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa8e
```

### Expected Behavior
I'm not really sure if it's even possible to make a `provisioner` block optional.

I saw there's a `when` clause but it doesn't seem to accept conditional expressions.

**Comment by mildwonkey** [comment] 2020-09-04 15:25
I'm so sorry, I don't think I meant to assign this to myself, and I definitely didn't mean to do that and then forget about the issue!

@jakubgs , thank you for reporting this. I tried to write a local reproduction using one of our built-in provisioners, but none of them have a block that could be used with `dynamic` (which is probably how this panic slipped in). I have two requests for you: can you try this again with terraform v0.13, since we have fixed a number of issues, and can you point me to the ansible provisioner that you use so I can write a reproduction? I think I have all the configuration I need, I just want to make sure I have the same provisioner that you are using. 

current attempt at a reproduction case (mostly saving this for myself):

 ```hcl
variable ps_setup_script {
  default = ""
}

data "aws_ami" "ubuntu" {
  most_recent = true
  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "test" {
  ami           = data.aws_ami.ubuntu.id
  instance_type = "t3.micro"

  provisioner "ansible" {
    dynamic "plays" {
      for_each = var.ps_setup_script == "" ? [1] : []
      content {
        playbook {
          file_path = "${path.cwd}/ansible/bootstrap.yml"
        }
      }
    }
  }
}
```

**Comment by jakubgs** [comment] 2020-09-04 19:02
I've been meaning to get around to upgrading to `0.13` for a while now but I'm currently working half-time. I guess I can push back the idea to redo our modules to make use of the new count feature and just upgrade to `0.13` without it. I'll try to do that sometime next week or this weekend. Thanks for checking this out.

**Comment by mildwonkey** [comment] 2020-09-09 16:35
Based on your last comment (and the lack of a reproduction), I'll close this issue, but please comment here if you can help with the reproduction case, and please open a *new* issue if you experience this in 0.13. Thanks, and sorry!

**Closed by mildwonkey** 2020-09-09 16:35 UTC
Labels: bug, new

**Comment by jakubgs** [comment] 2020-09-10 05:52
I have verified this does not happen in `0.13.2`. I can see the provisioner initialize but not run:
```
