### ISSUE TITLE
Cannot use dynamic inside block defined with ConfigModeAttr

### ISSUE THREAD

**Issue by test-in-prod** [hashicorp/terraform#22340] opened 2019-08-05 23:13 UTC
Hello,

Not sure if this was reported already, but I am having trouble following page at: https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each
when it comes to iterating lists that are declared in a `locals` block or those output by a module.

-------

Suppose we have:

```hcl
locals {
 #ip_whitelist = "${module.ip_whitelist.list}"  -- also not working
  ip_whitelist = ["127.0.0.1/32", "192.168.0.0/16"]
}

resource "azurerm_container_registry" "redacted" {
    name                =   "redacted"
    resource_group_name =   "${module.redacted.resource_group_name}"
    location            =   "${module.redacted.location}"
    admin_enabled       =   false
    sku                 =   "Premium"
    tags                =   "${var.tags}"

    georeplication_locations    =   ["East US"]

    network_rule_set        {
        default_action  =   "Deny"

        # dynamic ip_rule block
        dynamic "ip_rule" {
            for_each = local.ip_whitelist   # <--- error here?
            content {
                action  =   "Allow"
                ip_range    =   local.ip_whitelist  # <--- what do you put here when iterating?
            }
        }

        # static ip_rule block
        ip_rule   {
            action      =   "Allow"
            ip_range    =   "192.168.0.0/16"
        }
    }
}
```

This produces the following when running `terraform plan/apply`:

```
Error: Unknown variable

  on poc_acr.tf line 31, in resource "azurerm_container_registry" "redacted":
  31:             for_each = local.ip_whitelist

There is no variable named "local".
```

Same happens if I were to use `module.ip_whitelist.list` directly

----------------

Terraform version output:

```
Terraform v0.12.5
+ provider.azurerm v1.32.0
+ provider.external v1.2.0
+ provider.local v1.3.0
+ provider.random v2.1.2
```

**Comment by CryptonZylog** [comment] 2019-08-06 16:55
Here's another try based on [official documentation](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks).

```hcl 
module "ip_whitelist" {
    source  =   "../../modules/ip_whitelist"
}

resource "azurerm_container_registry" "redacted" {
    name                =   "redacted"
    resource_group_name =   "${module.core_westus.resource_group_name}"
    location            =   "${module.core_westus.location}"
    admin_enabled       =   false
    sku                 =   "Premium"
    tags                =   "${var.tags}"

    georeplication_locations    =   ["East US"]

    network_rule_set        {
        default_action  =   "Deny"

        dynamic "ip_rule" {
            for_each = module.ip_whitelist.ip_whitelist  # the output var here is a *list*

            content {
                action      =   "Allow"
                ip_range    =   ip_rule.value
            }
        }

    }
}
```
λ terraform apply -target azurerm_container_registry.redacted
Acquiring state lock. This may take a few moments...

Error: Unknown variable

  on poc_acr.tf line 24, in resource "azurerm_container_registry" "redacted":
  24:             for_each = module.ip_whitelist.ip_whitelist

There is no variable named "module".
```

**Comment by CryptonZylog** [comment] 2019-08-06 17:10
Tried upgrading to v0.12.6 just now and still seeing the same error. FYI, running on Windows.

**Comment by CryptonZylog** [comment] 2019-08-06 18:03
After some guesswork and fiddling, I found this oddly works:

```hcl
locals {
    acr_combined_wl = concat(module.ip_whitelist.ip_whitelist,module.core_westus.ase_outbound_addresses,module.core_eastus.ase_outbound_addresses) # combined list of all IPs in CIDR format
}

resource "azurerm_container_registry" "redacted" {
    name                =   "redacted"
    resource_group_name =   "${module.core_westus.resource_group_name}"
    location            =   "${module.core_westus.location}"
    admin_enabled       =   false
    sku                 =   "Premium"
    tags                =   "${var.tags}"

    georeplication_locations    =   ["East US"]

    network_rule_set       {
        default_action  =   "Deny"

        ip_rule =   [
            for ip in local.acr_combined_wl: {
                action  = "Allow"
                ip_range = ip
            }
        ]
    }
}
```

This seems to iterate and provide correct `ip_rule` entries.

**Comment by teamterraform** [comment] 2019-08-06 18:19
Hi @CryptonZylog,

Thanks for reporting the issue. That particular version of the azurerm provider is using a special feature in `network_rule_set` and `ip_rule` to allow setting the blocks as individual attributes. It appears as though this is interfering with the `for_each` evaluation and error reporting. 

I don't see those fields in the master branch of the provider any longer, so they may be phasing them out entirely. We'll see if we can get terraform to output a better error here, or or at least hint that attribute syntax may be required.

**Comment by CryptonZylog** [comment] 2019-08-06 19:05
>I don't see those fields in the master branch of the provider any longer, so they may be phasing them out entirely.

Which fields are you thinking will be phased out? The workaround I have discovered or the layout of `network_rule_set->ip_rule` as documented [here](https://www.terraform.io/docs/providers/azurerm/r/container_registry.html)? Just want to know whether the "workaround" I have is what is supposed to work and not something that will go away shortly.

>We'll see if we can get terraform to output a better error here, or or at least hint that attribute syntax may be required.

Thank you!

**Comment by teamterraform** [comment] 2019-08-06 19:56
Those fields don't appear in the master branch of the provider. I'm not sure what the plan is for that resource in general. Your "workaround" is correct for this version of the provider, because those fields are used as attributes, therefore can use the expression syntax.

**Comment by saraogivinay** [comment] 2019-08-15 15:59
I am also facing a similar issue with aws resource. Here is the sample code:

```
locals {
  lifecycle_glacier_rule_enabled = var.glacier_transition_days == -1 ? [] : [""]
  lifecycle_expiry_rule_enabled  = var.expiration_days == -1 ? [] : [""]
}

locals {
  transition_map = {
    GLACIER = {
      enabled         = local.lifecycle_glacier_rule_enabled
      transition_days = var.glacier_transition_days
    }
  }
}

resource "aws_s3_bucket" "bucket" {
  bucket = var.bucket_name
  acl    = "log-delivery-write" #required to enable logging

  versioning {
    enabled = true
  }

  dynamic "lifecycle_rule" {
    # for_each = local.lifecycle_glacier_rule_enabled
    for_each = [for storageclass in local.transition_map : {  # error line, no variable named 'local'
      class = lifecycle_rule.key
      days  = storageclass.value
      }
    if storageclass.enabled.value == true]

    content {
      id      = "auto_glacier"
      enabled = true

      transition {
        storage_class = lifecycle_rule.value.class
        days          = lifecycle_rule.value.day
      }
    }
  }

**Comment by soggycactus** [comment] 2019-11-19 00:08
Can we please get an update on this issue? I'm trying to use dynamic blocks, since we're upgrading from v0.11 to v0.12. Many of the things we used to pass as simple list arguments now have to be provisioned within a block, and the only way to set many blocks from a list variable is to use a dynamic blocking. It's not working.

**Comment by techspeque** [comment] 2019-11-24 03:53
@test-in-prod not knowing your particular use case -- a possible workaround to use of the ACR network filtering is to provision a standalone vnet with a single subnet that is attached to your ACR with the service endpoint as [defined here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-vnet#about-network-rules-for-a-container-registry)

That means that ACR accepts connections only from that subnet. You can then quite easily configure NSGs on the subnet to provide access via network peering. 

I believe what @teamterraform was pointing towards is that the ACR network filtering is currently in Preview and may indeed change before it goes GA. 

Hope that helps.

**Comment by nilic** [comment] 2019-11-29 23:16
Same issue with the VMware vSphere provider 

```
data "vsphere_datacenter" "datacenter" {
  name = "dc"
}

data "vsphere_virtual_machine" "template" {
  name          = "centos7"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

locals {
disks = { 
      for disk in data.vsphere_virtual_machine.template.disks : index(data.vsphere_virtual_machine.template.disks, disk) => disk
    }
} # data.vsphere_virtual_machine.template.disks is a list of maps

resource "vsphere_virtual_machine" "vsphere_vm" {
...
  dynamic "disk" {
    for_each = local.disks
    iterator = "template_disk"
    content {
      label            = "disk${template_disk.key}"
      unit_number      = template_disk.key
      size             = template_disk.value["size"]
      eagerly_scrub    = template_disk.value["eagerly_scrub"]
      thin_provisioned = template_disk.value["thin_provisioned"]
    }
  }
...
}
```

Error returned from `terraform plan`:

```
Error: Unknown variable

There is no variable named "local".
```

If I try feeding the `for disk in data.vsphere_virtual_machine.template.disks ..` iteration directly to `for_each` instead of using a separate `local.disks` value, the error returned is `There is no variable named "data".` 

Issue only appears when iterating over a list inside inside a child module. When modules are not used, everything works without a problem.

**Comment by carcuevas** [comment] 2019-12-06 17:47
Hi,

Also I am running into the same problem, but using the resource `aws_alb_listener` as it can be in the code:

```
resource "aws_alb_listener" "web_app_elb_listener_http" {
  load_balancer_arn = local.web_elb_arn
  port              = 80
  protocol          = "HTTP" 

  dynamic default_action {    
    for_each = lookup( [ var.web_elb_listener_http_actions ], "def_action", [])
      content {
        type = def_action.value.type     
        dynamic fixed_response {
          for_each = lookup(def_action.value, "fixed_response", [])
            content {
              content_type = fixed_response.value.content_type
              status_code  = fixed_response.value.status_code
              message_body = lookup(fixed_response.value, "message_body", "" )
            }      
          }
      }
   }
   
}

```

when doing terraform plan I get :

```
 terraform plan
Error: Unknown variable

  on ../../../modules/cert_domain/elb_listener.tf line 23, in resource "aws_alb_listener" "web_app_elb_listener_http":
  23:     for_each = lookup( [ var.web_elb_listener_http_actions ], "def_actiona", [])

There is no variable named "var".


Error: Reference to undeclared resource

  on ../../../modules/cert_domain/elb_listener.tf line 27, in resource "aws_alb_listener" "web_app_elb_listener_http":
  27:           for_each = lookup(def_action.value, "fixed_response", [])

A managed resource "def_action" "value" has not been declared in
cert_domain_creation.
```

The variable declaration: 

```
variable "web_elb_listener_http_actions" {
  description = "Here we configure the default action for the http listener"
  default = {
    def_action =[
    {    
        type  = "fixed-response"
        fixed_response = [
          {
            content_type = "text/plain"
            message_body = "Fixed response content"
            status_code  = "202"
          }
        ]
      }
    ]
  }
}
```
version is

```
Terraform v0.12.17
+ provider.aws v2.41.0
```

**Comment by carcuevas** [comment] 2019-12-06 22:37
Ohh I realized of my error it is working as it should... sorry for the mistake... it is working like this:

```
resource "aws_alb_listener" "web_app_elb_listener_http" { 
  load_balancer_arn = local.web_elb_arn
  port              = 80
  protocol          = "HTTP"
 
  ### In reality we want always to return 202 for HTTP, but we can configure something else
  default_action {          
    type = var.web_elb_listener_http_actions.def_action.type
    dynamic fixed_response {        
      for_each = [ lookup(var.web_elb_listener_http_actions.def_action, "fixed_response", {}) ]
        content {
          content_type = fixed_response.value.content_type
          status_code  = fixed_response.value.status_code
          message_body = lookup(fixed_response.value, "message_body", "" )
      }
    }    
  }    
}

```

And the variable:

```
variable "web_elb_listener_http_actions" {
  description = "Here we configure the default action for the http listener"
  default ={ 
    def_action = {    
      type  = "fixed-response"
      fixed_response = {
        content_type = "text/plain"
        message_body = ""
        status_code  = "202"
         }
       }
    } 
}
  
```

I realized of my error ... so I am not in this bug...

**Comment by pswalia06** [comment] 2020-02-24 19:26
I am getting the same error , is there a fix in any version ?
There is no variable named "var".


resource "azurerm_container_registry" "container_registry" {
  for_each = var.acr
  name = lookup(each.value, "acr_name", null) == null ? lower(format("%s-acr", each.key)) : lower(format("%s", each.value["acr_name"]))
  resource_group_name = each.value["resource_group_name"]
  location = each.value["location"]
  sku = lookup(each.value, "sku", "Standard")
  admin_enabled = lookup(each.value, "admin_enabled", true)
  georeplication_locations = each.value["georeplication_locations"]

   network_rule_set {

     default_action = "Deny"

     dynamic "ip_rule" {
       for_each = var.acr
        content {
          action  =   "Allow"
          ip_range    = each.value["ip_rule"]
        }
      }
    }
}

acr = {
  acr_2 = {
    acr_name = "testingACR2"
    resource_group_name = "ctc-sandbox-testing-rg-cc"
    admin_enabled = "true"
    georeplication_locations = ["East US",]
    location = "canada central"
    sku = "Premium"
    subnet_id = ["some_id_1234",]
    ip_rule = ["192.168.99.0/24",]
  }
}

**Comment by MeNsaaH** [comment] 2020-07-08 16:18
Same issue on helm provider using `set`
```hcl
  dynamic "set" {
    for_each = [local.tag_keys]
    iterator = "tag"
    content {
      name  = "podLabels[${index(local.tag_keys, tag.key)}]"
      value = "${tag.key}=${lookup(var.tags, tag.key)}"
    }
  }
```
Error
```                                                                                                                                                                                           
Error: Unknown variable                                                                                                                                                                       
                                                                                               
  on ../modules/external_dns/main.tf line 54, in resource "helm_release" "external_dns":                                                                                                      
  54:     for_each = [local.tag_keys]                                                                                                                                                         
                                                                                               
There is no variable named "local".


Error: Invalid expression

  on ../modules/external_dns/main.tf line 55, in resource "helm_release" "external_dns":
  55:     iterator = "tag"
```

**Comment by HighwayofLife** [comment] 2020-08-07 16:44
We were getting this as well on the Azure Container Registry resource, and this is because the `ip_rule` is an attribute and not a block, which is why "dynamic" doesn't work. The documentation doesn't match the code, but I think the code is actually wrong in this case. It's a provider bug I believe, but there is also a bug in Terraform that makes the error very confusing.

**Comment by mbrowne** [comment] 2020-09-08 22:37
The problem seems to be related to `iterator`. I found that when I avoided using `iterator` (and used the default iterator name instead, i.e. the name of the dynamic block), the error went away.

So the error message is definitely wrong.

**Comment by siarhei-karanets-epam** [comment] 2020-10-12 14:26
on ../dlm.tf line 11, in resource "aws_dlm_lifecycle_policy" "this":
  11:       for_each = var.schedules

There is no variable named "var".

**Comment by jbardin** [comment] 2020-10-29 16:16
I renamed the issue to more precisely match the original problem statement.
I ran through a number of the additional configurations presented here, and most seem to be user error, or unrelated issues which have been fixed since 0.12.  The initial report contains sufficient information to reproduce the issue; if you have questions concerning different configurations, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

**Comment by mbrowne** [comment] 2020-10-29 18:30
There's also the issue of the error message itself being incorrect. Unless this has all been fixed in v0.13 (I haven't tried it yet).

**Comment by dj5k** [comment] 2021-01-22 10:28
In a different use case I experience the same problem that the optional iterator argument for dynamic blocks appears broken or bugged.  
I hope this is the appropriate issue.

my code:
``` terraform
resource "aws_ecs_service" "self" {
[...]
  dynamic "capacity_provider_strategy" {
    for_each = var.launch_type == "FARGATE" ? ["FARGATE", var.fargate_spot_usage.spot_use ? "FARGATE_SPOT" : null] : []
    iterator = "capacity_provider"
    content {
      capacity_provider = capacity_provider.value
      weight            = capacity_provider.value == "FARGATE" ? (100 - var.fargate_spot_usage.spot_percentage) : var.fargate_spot_usage.spot_percentage
      base              = capacity_provider.value == "FARGATE" ? var.fargate_spot_usage.non_spot_base : null
    }
  }
[...]
}
```

On `terraform validate` I receive the error message:
```
Error: Invalid expression

  on modules/foo/main.tf line 229, in resource "aws_ecs_service" "self":
 229:     iterator = "capacity_provider"

A single static variable reference is required: only attribute access and
indexing with constant keys. No calculations, function calls, template
expressions, etc are allowed here.
```

According to the docs this is supposed to be a static string
> The iterator argument (optional) sets the name of a temporary variable that represents the current element of the complex value.

So I don't understand what I'm doing wrong or what I could be doing to fix this.

terraform version:
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.25.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

Additionally I tested this with 0.14.5 and it gave the exact same output.

Yes I could just not use the `iterator` argument and that is what I am going to do to work around this issue. But I would like to use it to make the code a little easier to understand.

**Comment by schwarzzz** [comment] 2021-02-05 12:33
Same issue with `azurerm_eventhub_namespace` and a dynamic `virtual_network_rule` block inside the `network_rulesets` block.

**Comment by Vignesh-Seethapathy** [comment] 2021-03-25 17:23
Experiencing the same issue even with `Terraform v14.7` `azurerm provider v=2.52.0` when using dynamic log block in `azurerm_monitor_diagnostic_setting`

My code below
```
 dynamic "log" {
    for_each = lookup(var.diagnostic_object, "log", [])
    content {
      category = log.value[0]
      enabled  = log.value[1]
      dynamic "retention_policy" {
        for_each = length(log.value) > 2 ? [1] : []
        content {
          enabled = log.value[2]
          days    = log.value[3]
        }
      }
    }
  }
```

Input as below
```
diagnostic_object = {
     log = [
                 # ["Category name",  "Diagnostics Enabled(true/false)", "Retention Enabled(true/false)", Retention_period],
                 ["AzureBackupReport", true, true, 100],
                 ["AzureSiteRecoveryJobs", true, true, 20],
         ]
     metric = [
                 #["Category name",  "Diagnostics Enabled(true/false)", "Retention Enabled(true/false)", Retention_period],
                 ["AllMetrics", true, true, 60],
     ]
 }
```
Error Below
```
  15:     for_each = lookup(var.diagnostic_object, "log", [])
There is no variable named "var".
```

**Comment by Nuru** [comment] 2021-05-12 18:29
@jbardin Is there a better issue to track this with? I have some problems with the current state of this issue:

1. I have no idea what `ConfigModeAttr` is or how to know if I am "inside block defined with ConfigModeAttr" or if being able to use "dynamic inside block defined with ConfigModeAttr" is supposed to be supported
2. The error message is not at all helpful. 

I have been getting this error message 
```
There is no variable named "var".
```
from Terrraform v0.14.11 on 10 lines due to a bad resource reference on another dynamic block. I had

```hcl
dynamic "statement" {
for_each = random_password.referer.result
...
```
instead of
```hcl
dynamic "statement" {
for_each = random_password.referer[0].result
...
```
and of course it is fine that Terraform complained about that, but that error message was lost in the sea of `There is no variable name "var"` errors. A better error message might be "Invalid dynamic block" or something, and of course not having an error in one dynamic block propagate to other dynamic blocks.

**Comment by jbardin** [comment] 2021-05-12 21:09
Sorry @Nuru, this is the only issue open. I don't think having another issue about the same incompatibility would help, but perhaps your comment will assist other users with similar problems in finding this in a search.

`SchemaConfigModeAttr` was a temporary workaround given to providers to use when they required being able to assign an empty "block value" to remain backwards compatible with pre-0.12 configurations. This flag should be used sparingly, and document that argument should be used as attribute rather than a block. 

In most cases the solution is to use for expressions instead of `dynamic` to construct and assign the desired attribute value, but since we have to maintain compatibility with the old block format for these attributes, it's hard to devise useful errors from within Terraform.

**Comment by adesca** [comment] 2021-06-10 18:16
I have the same problem as @Vignesh-Seethapathy.
Can we get any insight into why the azurerm_monitor_diagnostic_setting resource doesn't work with dynamic?

**Comment by olenm** [comment] 2021-07-20 20:38
Is there a more generic issue regarding using locals/modules/data? as inputs to a dynamic-block that yields `There is no variable named "local"` or something similar? I am seeing this within `aws_elasticache_parameter_group` and I feel in no way would I be the only one.

**Comment by neironus** [comment] 2021-09-03 17:01
Hi, I got a very similar issue when I am trying to use a local variable in a dynamic block.
### Example:
```
locals {
  list_one      = [1, 2, 3]
  list_two      = [4, 5, 6]
  some_list     = concat(local.list_one, local.list_two)
  some_list_fix = split(",", join(",", local.some_list))
}
```
If using local.some_list in dynamic block I got an error.
I did some research on this question and found the problem. The concat() function creates this problem.
### Solution:
Use **local.some_list_fix** in dynamic block

**Comment by FilBot3** [comment] 2021-10-13 22:05
This seems to be the answer that worked for me.

https://stackoverflow.com/questions/69560891/terraform-dynamic-block-missing-an-argument-or-block-definition

**Comment by gdserkin** [comment] 2021-11-03 17:42
> Same issue on helm provider using `set`
> 
> ```terraform
>   dynamic "set" {
>     for_each = [local.tag_keys]
>     iterator = "tag"
>     content {
>       name  = "podLabels[${index(local.tag_keys, tag.key)}]"
>       value = "${tag.key}=${lookup(var.tags, tag.key)}"
>     }
>   }
> ```
> 
> Error
> 
> ```
> Error: Unknown variable                                                                                                                                                                       
>                                                                                                
>   on ../modules/external_dns/main.tf line 54, in resource "helm_release" "external_dns":                                                                                                      
>   54:     for_each = [local.tag_keys]                                                                                                                                                         
>                                                                                                
> There is no variable named "local".
> 
> 
> Error: Invalid expression
> 
>   on ../modules/external_dns/main.tf line 55, in resource "helm_release" "external_dns":
>   55:     iterator = "tag"
> A single static variable reference is required: only attribute access and
> indexing with constant keys. No calculations, function calls, template
> expressions, etc are allowed here.
> ```

It works if you remove the quotes like this:

iterator = tag

**Comment by tarfeef101** [comment] 2021-12-21 23:57
Seeing the same issue inside `aws_spot_fleet_request` trying to configure the below:
```
dynamic "launch_template_config" {
    for_each = {
      for item in local.some_map : "${item.instance}:${item.subnet}" => item
    }
    iterator = "each"
    content {
      launch_template_specification {
        id      = module.custom_module[each.key].template_id
        version = module.custom_module[each.key].template_version
      }
    }
  }
  ```

if I remove the quotes around my iterator like above, it plans (have yet to apply). If this is **intended**, that's surprising. If not, that's less surprising. In the former case, that should be explicitly documented as users will not assume this, if the latter, then it should (please) be fixed.

**Comment by apparentlymart** [comment] 2022-04-27 23:30
Hi all,

This bug report has been kinda stuck in stasis here because it's discussing a quirk in a shim we introduced in Terraform v0.12 to preserve some unusual behaviors that providers had adopted by relying on quirks of the old Terraform SDK. The goal of introducing this quirk was to buy provider development teams some time to design themselves out of those corners while still allowing us to fix the Terraform language bugs that the providers had inadvertently been relying on side-effects of.

Given that, this mechanism has always just been a best effort shim to allow certain special cases to work, and it was intentionally not well-polished or made totally robust because over time provider teams would stop relying on it, and so the opportunity cost of further investment in it was too high.

Given that the discussion above has already covered the technical interactions that cause this and what to do about it, and given that this is a compatibility shim that we don't intend to invest in further, I'm going to close this issue just because otherwise I expect it will sit here open forever, doing no good to anyone.

To sum up what was discussed above:
* Terraform Core allows providers to, in exceptional cases, opt a particular attribute into a special processing mode called [Attributes as Blocks](https://www.terraform.io/language/attr-as-blocks), which activates some special processing that allows using the nested block syntax to provide a value to an attribute.

    (The SDK refers to this special mode in provider source code as `ConfigModeAttr`, and so that keyword tends to appear when we talk about the technology behind attributes as blocks mode.)
* A provider activating that mode for a particular attribute has various consequences documented on the page linked in the previous point, which requires writing configuration for that attribute in some unusual ways.
* One specific consequence is that the `dynamic` block construct doesn't work properly for those attributes, because they aren't _really_ nested blocks and so Terraform's block expansion produces a data structure that doesn't really make sense for the provider schema.

    Although [it's okay to write out _static_ blocks to populate such an attribute](https://www.terraform.io/language/attr-as-blocks#defining-a-fixed-object-collection-value), if you want to dynamically decide the number of elements to assign then [you need to use normal Terraform expression syntax to construct a collection](https://www.terraform.io/language/attr-as-blocks).
* Due to how the shim for attributes as blocks mode is implemented in Terraform, the error message for trying to use a `dynamic` block in this context is poor. This is unfortunate, but we cannot feasibly improve on it without a heavy redesign of this shimming behavior, and the opportunity cost of doing so for a mechanism that should phase out over time is too high.
* The path forward for this situation is for provider development teams to gradually phase out their use of this compatibility mode. In some cases that represents a breaking change and so provider teams are tackling those only in major releases, which happen infrequently and therefore the process is ongoing and teams are prioritizing the most troublesome situations first. Over time then, there will be future opportunities to encounter this rough edge.

As noted above, I'm going to close this now not with the intention of saying "this is solved" but rather in recognition that we're unlikely to change anything _in this repository_ that will improve the situation. Instead, the importance of this issue should gradually fade away as providers adopt new schema designs.

Thanks to everyone who shared workarounds and context above!

**Closed** 2022-04-27 23:30 UTC
Labels: bug, config, v0.12, confirmed
