### ISSUE TITLE
Provisioning with SSH on AWS times out

### ISSUE THREAD

**Issue by vdemario** [hashicorp/terraform#17140] opened 2018-01-18 15:53 UTC
We've been provisioning machines with SSH on terraform for several months now. Today, for the first time, SSH timed out. I thought, at first, there was something wrong with the network or security group configuration on Amazon, perhaps our IP changed even though it was supposed to be fixed.

None of that happened and I can successfully connect via SSH to the instances created by Terraform. In fact, not only I can connect but if I run the inline commands manually that way everything works as expected.

### Terraform Version

```
Terraform v0.11.2
```

I started experiencing this problem with v0.11.1 and upgraded hoping it would fix it. The first attempt at `terraform apply` with v0.11.2 succeeded. Later I changed the instance_count and the problem happened again.

### Terraform Configuration Files

```hcl
provisioner "remote-exec" {
    connection {
      type        = "ssh"
      agent       = false
      user        = "ubuntu"
      private_key = "${file("~/.ssh/private_key.pem")}"
    }

    inline = [
      # several removed commands
    ]
  }
```

### Expected Behavior

`aws_spot_instance_request.abcd_worker (remote-exec): Login Succeeded` and then the inline commands.

### Actual Behavior

SSH connection never happens and the following log messages loop until the apply command runs for 5 minutes and times out.

```
aws_spot_instance_request.abcd_worker[1] (remote-exec): Connecting to remote host via SSH...
aws_spot_instance_request.abcd_worker[1] (remote-exec):   Host:
aws_spot_instance_request.abcd_worker[1] (remote-exec):   User: ubuntu
aws_spot_instance_request.abcd_worker[1] (remote-exec):   Password: false
aws_spot_instance_request.abcd_worker[1] (remote-exec):   Private key: true
aws_spot_instance_request.abcd_worker[1] (remote-exec):   SSH Agent: false
```

### Steps to Reproduce

`terraform apply` with the remote-exec/ssh provisioner is all we're doing.

### References

I suspected my issue was related to #17117 since it mentions AWS security groups as well but it might not have any connection. I started having these problems on v0.11.1 and the security groups on my terraform configuration are being applied correctly.

**Comment by vdemario** [comment] 2018-01-18 17:58
More info: I ran terraform again on the same configuration, it was supposed to replace 3 instances. The provisioning worked on 2 of them and not on another.

It's possible there's something wrong on my end, perhaps network related. However, I can't explain being able to connect directly but not through terraform.

**Comment by jbardin** [comment] 2018-01-19 21:17
Hi @vdemario,

Sorry you're having an issue here. Is that the extent of the output that you see which is being repeated? Can you get the trace log output from terraform when this happens?

The only situation I can think of is that terraform got the wrong (or empty) information from the provider, but I"m not sure that could happen yet.

**Comment by vdemario** [comment] 2018-01-19 21:38
Hi @jbardin, I do have a trace log at https://drive.google.com/file/d/1OxOND5AOvJnZJG-K2Mouqf38m5PY7piu/view?usp=sharing. I edited a little bit of it in the beginning because I was concerned about credentials then gave up on editing and encrypted with the HashiCorp security public key.

It was generated at the time of my last comment, when provisioning worked for 2 instances and failed on 1.

**Comment by jbardin** [comment] 2018-01-19 23:42
Thanks for the logs!, Unfortunately they weren't very enlightening. What I didn't notice at first glance though is that the `Host` name in the cli output is empty. I'm not sure how that's happening yet, but it at least give me something to pursue.

**Comment by ricardoserradas** [comment] 2018-01-20 01:52
I'm having the same issue. Well, first I was having issues specifying the key_name under the resource.

I was getting the following error:

Error launching source instance: invalidkeypair.notfound the key pair "<keypairname>" does not exist Error 400

But the key pair exists under EC2 Management Console > Network & Security > Key Pairs

I then decided to comment this line. When I did so, the exact same thing happened to me. Terraform trying to connect to the host through SSH until timeout error occurs.

**Comment by ricardoserradas** [comment] 2018-01-20 02:22
@vdemario I experienced the same problem. In my case, the issue was that the security group that was being applied to the instance did not allow SSH connections. Once allowing it from the SG, I could achieve it.

**Comment by vdemario** [comment] 2018-01-22 14:33
That's not the case @ricardoserradas. I could connect directly outside terraform and these are very old security groups that only exist specifically for SSH.

**Comment by marcosinger** [comment] 2018-01-23 13:25
I had the same issue today, so let me add more context to you guys how I _solved_ it:

I changed from spot instances to a normal one (using `aws_instance ` instead of `aws_spot_instance_request`) and it was deployed correctly. I don't know if changing the instance type is a false positive.

Let me know if there is something that I can provide to you guys, like logs or something to help in this case.

**Comment by vdemario** [comment] 2018-01-23 13:37
BTW, @marcosinger works with me so he's talking about the same terraform configuration as me.

@jbardin this reminds me: the empty Host is probably because of the spot instance request. Tags get applied to the spot request instead of the instance so the name is lost when we use spot instances. See https://github.com/hashicorp/terraform/issues/3263.

**Comment by ofrzeta** [comment] 2018-03-09 13:24
I have the same problem. I had a working configuration with regular instances and changed to spot instances. Now Terraform times out trying to connect via SSH. While logging in with SSH from another terminal works fine.

**Comment by ofrzeta** [comment] 2018-03-09 13:51
I found the solution now. For spot instances you need to add "wait_for_fulfillment = true" to make SSH remote exec provisioning work.

**Comment by marcosinger** [comment] 2018-03-09 14:31
@ofrzeta I did the same here and it works. I also added `associate_public_ip_address = true` which is optional, I don't know why.

**Comment by Michael-McD** [comment] 2018-03-22 17:28
Looks like using the *file provisioner* can cause Terraforms "aws_instance" creation to time out.  Interesting this only happens on some of our AWS environments.

Removing the *file provisioner* block and the EC2 instance is created in a few seconds, and accessible using ssh.

**Comment by jbardin** [comment] 2019-12-10 20:53
The original issue here was caused by the `host` field being left unset by the provider. 
This is no longer a concern, because `connection` blocks require a `host` to be explicitly defined in the configuration.

Since there is no further development of 0.11 happening, we can close this out .

**Closed by jbardin** 2019-12-10 20:53 UTC
Labels: bug, provisioner/remote-exec, v0.11
