### ISSUE TITLE
terraform provider docker: parse: invalid character "{" in host name

### ISSUE THREAD

**Issue by haai** [hashicorp/terraform#18416] opened 2018-07-09 10:59 UTC
Terraform complains that it could not parse the docker hostname when the hostname contains a variable substitution, which worked with the old plugin.

### Terraform Version

```
Terraform v0.11.7
+ provider.docker v1.0.0
```

### Expected Behavior
It should work :)

### Actual Behavior
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error refreshing state: 1 error(s) occurred:

* provider.docker: Error initializing Docker client: parse tcp://${var.docker_host}:2375/: invalid character "{" in host name
```

### Steps to Reproduce
Use docker plugin and a provider with
```
provider "docker" {
  host = "tcp://${var.docker_endpoint}/"
}
```

### Notes
It seemed to work with the old plugin
```
Terraform v0.11.7
+ provider.docker v0.1.1
```

**Comment by apparentlymart** [comment] 2018-07-09 22:12
Hi @haai! Sorry for this apparent regression.

It looks like the Docker provider is attempting to process the value of the `host` argument during its validate step here, which isn't correct because validation happens before the expression has been evaluated and so it is trying to use that literal string as a URL.

I'm going to have our bot move this over to the docker provider's repository, since I think the fix here will be in the provider's own code.

**Closed** 2018-07-09 22:20 UTC
Labels: bug, provider/docker, regression

**Comment by haai** [comment] 2018-07-10 09:44
Yeah np. thx for fast resolution.
Is there a way to downgrade the plugin with terraform? or fix the version in the config?
As I can see the `terraform init` is always downloading the newest version, right

**Comment by mavogel** [comment] 2018-07-10 12:15
hi @haai, thank for pointing out the issue. I'll fix it asap and release a new version. 
In the meantime you can tie the version of the provider as follows:
```hcl
provider "docker" {
  version = "~> 0.1.1"
}
```

**Comment by haai** [comment] 2018-07-10 12:37
hi @mavogel 
Thanks for the tip to tie the version... Did a quick check with that and `terraform init` worked as expected
```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "docker" (0.1.1)...

Terraform has been successfully initialized!
```

But that version attribute is not mentioned at the documentation page for the docker provider ,right?
https://www.terraform.io/docs/providers/docker/index.html

**Comment by apparentlymart** [comment] 2018-07-10 16:43
This `version` argument is a special one handled by Terraform itself across all providers, described in [_Provider Versions_](https://www.terraform.io/docs/configuration/providers.html#provider-versions).

**Comment by mavogel** [comment] 2018-08-06 12:41
@haai I could not reproduce: https://github.com/terraform-providers/terraform-provider-docker/issues/78#issuecomment-404059834
