### ISSUE TITLE
`terraform refresh`, AWS, state bugs

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#2465] opened 2015-06-24 16:53 UTC
Hello all!

Overall structure: VPC, ELB, 2 app servers in private subnet, RDS instance with all the subnets, routing tables, and other trimmings. I have a few outputs recorded for simple reference:

```
output "app_1.0.ip" {
  value = "${aws_instance.app_1.0.private_ip}"
}

output "app_2.0.ip" {
  value = "${aws_instance.app_2.0.private_ip}"
}

output "nat.ip" {
  value = "${aws_instance.nat.public_ip}"
}

output "nat.hostname" {
  value = "${aws_instance.nat.public_dns}"
}

output "elb.hostname" {
  value = "${aws_elb.app.dns_name}"
}

output "rbs.hostname" {
  value = "${aws_db_instance.default.address}"
}
```

I left work yesterday with state being a-okay. I returned to work today, ran `terraform show` and noticed that `elb.hostname` and `rds.hostname` were both missing, so I ran `terraform refresh` and now it's inverted: only `elb.hostname` and `rds.hostname` are being output. I inspected `terraform.tfstate` and noticed all my `aws_instance`s and associated subnets are gone, even though they still exist in AWS. The ELB, RDS Instance, and routing tables (even for the app subnets) are still there though.

Any other data I can provide to assist in debuging this?

**Comment by mitchellh** [comment] 2015-06-25 16:29
Hm, this will be hard for us to fix without a reproduction case. The things we'll need, if you can get this to happen again:

1. The state (before and after). Terraform will always save the before state in "<path>.backup" so you should easily be able to get this.

1. The debug log (TF_LOG=1). Please gist this.

1. Your config, if possible, but less necessary potentially for this issue.

Given we run Terraform quite a bit and haven't seen this, I don't feel confident we can reproduce this without the above information. I believe you and I'm sure what you saw is a bug, but I'll have to close this issue without being able to reproduce it otherwise it'll just sit. If you can repro it, please give us the above and I'm confident we can fix it, as this is quite serious. Luckily, since we've only just heard of this, it must be a very edge case.

**Comment by nathanielks** [comment] 2015-07-09 17:45
Alrighty! I've been able to reproduce this, albeit with different resource sets. [Here](https://gist.github.com/nathanielks/a5092615b51c313369ca) are the state files from before and after as well as the logs.

Situation: 1 EC2 instance behind public load balancer and 1 EC2 instance behind internal load balancer. Before running `terraform refresh`, it displayed all the above resources. After, it removed the 2 EC2 instances. Now, the only thing I recall changing was I created an AMI from the second of the 2 instances and now _both_ have been removed. The second _does_ have a different IP address now, which explains why that one would be removed because a new resource was created outside of terraform at some point, but I'm not sure why the first EC2 instance would be removed because it hasn't changed (to my knowledge).

**Comment by phinze** [comment] 2015-07-10 05:36
Reopening so we can take another look!

**Comment by mitchellh** [comment] 2015-07-20 00:46
I'm reasonably confident that although it is manifesting itself in different ways, this is identical to #2598

**Comment by mitchellh** [comment] 2016-10-25 19:23
Closing this since I can't reliably reproduce this, and its likely something like #2598 which can be reliably reproduced.

**Closed by mitchellh** 2016-10-25 19:23 UTC
Labels: bug, core
