### ISSUE TITLE
panic: inconsistent map element types (cty.List(cty.String) then cty.Bool)

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/terraform#25773] opened 2020-08-07 16:22 UTC
### Terraform Version

```
Terraform v0.12.28
+ provider.aws v2.70.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.tfe v0.20.0

Your version of Terraform is out of date! The latest version
is 0.12.29. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
module "foo-user" {
  source        = "../../terraform-aws-user"
  label_context = module.label.context
  name          = "foo-services"
  policies = [
  ]
}
```

`terraform-aws-user` module contents:
```terraform
variable "label_context" {
  type    = map
  default = {}
}
module "label" {
  source  = "cloudposse/label/null"
  version = "0.16.0"

  context = var.label_context
  name    = var.name
}
```

### Debug Output

```
2020/08/07 10:44:56 [TRACE] evalVariableValidations: not active for module.opentelemetry-collector.var.label_context, so skipping
2020/08/07 10:44:56 [TRACE] [walkValidate] Exiting eval tree: module.opentelemetry-collector.var.label_context
2020/08/07 10:44:56 [TRACE] vertex "module.opentelemetry-collector.var.label_context": visit complete
2020/08/07 10:44:56 [TRACE] vertex "module.pa-services-user.var.label_context": visit complete
panic: inconsistent map element types (cty.List(cty.String) then cty.Bool)
```

### Crash Output

```
goroutine 621 [running]:
github.com/zclconf/go-cty/cty.MapVal(0xc0014032e0, 0xc001403200, 0xc0018545d0, 0x4, 0xc000cbc828)
	github.com/zclconf/go-cty@v1.2.1/cty/value_init.go:207 +0x4b3
github.com/zclconf/go-cty/cty/convert.conversionObjectToMap.func2(0x2fd3500, 0xc00049c0c0, 0x2771a60, 0xc00123fe00, 0xc00168afc0, 0x1, 0x1, 0xc000076800, 0x10, 0x10, ...)
	github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion_collection.go:338 +0x552
github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x2fd3500, 0xc00049c0c0, 0x2771a60, 0xc00123fe00, 0x0, 0x0, 0x0, 0xc0014fc7b0, 0xc00168afb0, 0x2fd34c0, ...)
	github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:46 +0x1ab
github.com/zclconf/go-cty/cty/convert.retConversion.func1(0x2fd3500, 0xc00049c0c0, 0x2771a60, 0xc00123fe00, 0xc00168afb0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:179 +0x6b
github.com/zclconf/go-cty/cty/convert.Convert(0x2fd3500, 0xc00049c0c0, 0x2771a60, 0xc00123fe00, 0x2fd34c0, 0xc000581700, 0x0, 0x2fd3500, 0xc00049c0c0, 0x2771a60, ...)
	github.com/zclconf/go-cty@v1.2.1/cty/convert/public.go:51 +0x1aa
github.com/hashicorp/terraform/terraform.(*EvalModuleCallArgument).Eval(0xc000b5c6c0, 0x3005ca0, 0xc0011c00d0, 0x2, 0x2, 0x0, 0xc000557a80)
	github.com/hashicorp/terraform@/terraform/eval_variable.go:77 +0x160
github.com/hashicorp/terraform/terraform.EvalRaw(0x2f8d700, 0xc000b5c6c0, 0x3005ca0, 0xc0011c00d0, 0x2d, 0x0, 0x0, 0x2d)
	github.com/hashicorp/terraform@/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc00123f140, 0x3005ca0, 0xc0011c00d0, 0x2, 0x2, 0x2b95280, 0x10000c020eed4f8)
	github.com/hashicorp/terraform@/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x2f8d740, 0xc00123f140, 0x3005ca0, 0xc0011c00d0, 0x0, 0xc001672d08, 0xc0000b8000, 0x2d)
	github.com/hashicorp/terraform@/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000724000, 0x3005ca0, 0xc0011c00d0, 0x2, 0x2, 0x1b25855, 0x2f8dde0)
	github.com/hashicorp/terraform@/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2f8d8a0, 0xc000724000, 0x3005ca0, 0xc0011c00d0, 0x27622e0, 0x3e3d185, 0x26c6560, 0xc00168a190)
	github.com/hashicorp/terraform@/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2f8d8a0, 0xc000724000, 0x3005ca0, 0xc0011c00d0, 0xc000724000, 0x2f8d8a0, 0xc000724000, 0x0)
	github.com/hashicorp/terraform@/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x29322c0, 0xc00101eb00, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform@/terraform/graph.go:90 +0xf7e
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000c10680, 0x29322c0, 0xc00101eb00, 0xc000da4e00)
	github.com/hashicorp/terraform@/dag/walk.go:392 +0x377
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	github.com/hashicorp/terraform@/dag/walk.go:314 +0xaa7
```

### Expected Behavior

Graceful error exit regarding incompatible input types. Removing the invalid `type=map` declaration cleaned up the behavior.

### Actual Behavior

Panic

### Steps to Reproduce

1. terraform apply

**Comment by danieldreier** [comment] 2020-08-13 16:15
Hi! Thanks for reporting this. This looks like a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. If you could help put together a simplified reproduction case, it would make it easier for us to run locally. Again, I think this is 100% valid, I just could use your help putting together the full reproduction case, e.g. a trivial module with null resources in it. 

Ideally, this would be in a git repository so we can clone it and run it to see the issue. If you need a place to put it, you're welcome to make a PR on https://github.com/danieldreier/terraform-issue-reproductions, or use your own GH repo.

**Comment by mildwonkey** [comment] 2020-08-20 12:56
I'd also like to mention that we've fixed a number of similar-looking issues in terraform v0.13.0, so it would be good to know if your problem is resolved when you upgrade terraform!

**Comment by danieldreier** [comment] 2020-09-28 23:54
@dekimsey have you been able to reproduce this issue on 0.13.x? I would like to get it fixed, but it's tough to do without a reproduction case in the latest Terraform version

**Comment by mildwonkey** [comment] 2020-09-29 12:30
No @danieldreier , we don't have a reproduction for this issue specifically - it's not an uncommon category of panic, and we've fixed many, but without a repro I couldn't tell you if this is one of them. Sorry!

**Comment by mildwonkey** [comment] 2020-12-02 14:20
I'm going to close this issue since there's be no update. If you are still experience a problem with the latest version of terraform, please open a new issue with a complete reproduction case. Thanks!

**Closed by mildwonkey** 2020-12-02 14:20 UTC
Labels: bug, crash, v0.12, waiting for reproduction
