### ISSUE TITLE
Add alias for `terraform state list` as `terraform state ls`

### ISSUE THREAD

**Issue by PolarPayne** [hashicorp/terraform#31688] opened 2022-08-25 08:10 UTC
### Terraform Version

```shell
Terraform v1.2.7
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

The first time I (and most people I know) list the state, I always run `terraform state ls`.

Having removing and moving as `rm` and `mv` respectively, there is already precedent on using the common shell commands for the state subcommands.

### Attempted Solutions

Trying to remember whether terraform uses rm/mv/ls or remove/move/list (I can never remember).

### Proposal

Add an alias for `terraform state list` as `terraform state ls`. This should be a trivial change that does not break any existing workflows.

It would probably be a good idea to also add the following aliases, and to make sure that the help text shows either the long or short forms as the "canonical" ones.

- `remove` -> `rm`
- `move` -> `mv`

**Comment by crw** [comment] 2022-08-26 21:12
Thanks for the feature request!

Duplicate of #20998.

**Closed by crw** 2022-08-26 21:12 UTC
Labels: enhancement, new
