### ISSUE TITLE
wrong ceil calculation

### ISSUE THREAD

**Issue by pangteypiyush** [hashicorp/terraform#29324] opened 2021-08-08 17:09 UTC
### Terraform Version

```
v1.0.4
```

### Terraform Configuration Files

```terraform
output "ceil" {
  value = ceil(12.0)
}
```

### Expected Behavior

`ceil` of `12.0` should be `12`

### Actual Behavior

Using:
1. terraform configuration file: `ceil` of `12.0` is `13`
2. terrform console: `ceil` of `12.0` is `12`

**Comment by jbardin** [comment] 2021-08-09 13:43
Thanks @pangteypiyush,

Duplicate of #29301.

**Closed by jbardin** 2021-08-09 13:43 UTC
Labels: bug, new
