### ISSUE TITLE
Terraform import fails to import more then 1 resource when for_each is used for modules

### ISSUE THREAD

**Issue by dominik-weber** [hashicorp/terraform#31501] opened 2022-07-23 11:34 UTC
### Terraform Version
```
Terraform v1.2.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.14.0
```

### main.tf
```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.14.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  for_each = toset(["asd", "qwe"])
  name     = "test"
  location = "West Europe"
}

module "test" {
  for_each = toset(["asd", "qwe"])
  source   = "./modules/test"

  # this assignment fails when trying to import the second resource group
  name = azurerm_resource_group.test[each.key].id
}
```

### modules/test/variables.tf
(This is just a dummy module without any resources. In our actual use case we have resources in here - the error is the same though)
```terraform
variable "name" {
  type = string
}
```

### Expected Behavior
I should be able to import both resource groups using `terraform import`.

### Actual Behavior
I can import the first resource group, when trying to import the second one `terraform import` fails.

### Steps to Reproduce
Please provide your own importable resources, from my testing (Azure only), any resource will cause the bad behavior. Reproduction with the null provider seems not possible as it does not support importing.
1. `terraform init`
2. `terraform import azurerm_resource_group.test["asd"] /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup`
![image](https://user-images.githubusercontent.com/1771927/180602813-1d7f31ea-775f-4736-8ee5-186d796d9b26.png)

3. `terraform import azurerm_resource_group.test["qwe"] /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup`
![image](https://user-images.githubusercontent.com/1771927/180602857-d8e81f7e-8862-462c-b039-6a32c95bfc17.png)

### Additional Context
I am able to import the resources successfully if I comment out the module block. After importing the resources, I can uncomment the module block and everything seems to be working fine, looks like just the import is broken.

### References
I found this Stackoverflow thread when researching the problem: https://stackoverflow.com/a/68928725/1074014, might be related (although quite old)

**Comment by jbardin** [comment] 2022-07-25 12:39
Duplicate of #30706

**Closed by jbardin** 2022-07-25 12:39 UTC
Labels: bug, duplicate
