### ISSUE TITLE
Terraform remote backend return error when used with workspace name

### ISSUE THREAD

**Issue by SilverXXX** [hashicorp/terraform#23110] opened 2019-10-17 17:35 UTC
Terraform with remote backend gives error when using workspace name
### Terraform Version
```
Terraform v0.12.10
```

### Terraform Configuration Files
```hcl
terraform {
    backend "remote" {
        organization = "test-org"

        workspaces {
            name= "project-demo"
        }
    }
}
```

### Debug Output
https://gist.github.com/SilverXXX/ccc1394d034d7bfd61b16ffa5ea7aebc

### Expected Behavior
It should just select the correct workspace

### Actual Behavior
It gives an error saying that workspaces are not supported

### Steps to Reproduce
1. Set up terraform cloud and main.tf
2. `terraform init`
3. `terraform workspace select project-demo`

Got this error first while using atlantis, but reproduced it locally

**Comment by teamterraform** [comment] 2019-10-17 18:03
Hi @SilverXXX,

Because you have used the `name` argument inside the `workspaces` block, the remote backend is configured in single-workspace mode, and Terraform CLI always calls a single workspace "default", regardless of what it is called remotely in Terraform Cloud.

As described in [the _Workspaces_ section](https://www.terraform.io/docs/backends/types/remote.html#workspaces) of the remote backend documentation, you can enable the multiple-workspace mode by giving all of your related workspaces a common prefix in Terraform Cloud and then configuring that prefix in the backend configuration, rather than the single workspace name:

```hcl
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "company"

    workspaces {
      prefix = "project-"
    }
  }
}
```

With the above configuration, your remote workspace `project-demo` will be called just "demo" in Terraform CLI, because Terraform CLI is scoped to work on the workspaces related to a single project (sharing a common prefix) at a time.

Because you've already run `terraform init` with the single-workspace configuration, if you change the configuration as we described above you should reconfigure it with `terraform init -reconfigure` so that Terraform knows that you intend to just switch to a new configuration, since otherwise it will propose trying to migrate the state from the old workspace to the new workspace and that would be inappropriate here because the two are just different local names for the same remote object.

Since the remote backend is working as designed here, we're going to close this out. If you have further questions, please feel free to start a topic about it on [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!

**Closed by teamterraform** 2019-10-17 18:03 UTC
