### ISSUE TITLE
registry.terraform.io operates on port 80 - no 443 redirect.

### ISSUE THREAD

**Issue by oliver-reload** [hashicorp/terraform#32278] opened 2022-11-23 13:26 UTC
### Terraform Version

```shell
N/A
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

N/A

### Expected Behavior

http requests should redirect to https?

### Actual Behavior

```
oliver@skynet:~$ curl -v registry.terraform.io
*   Trying 199.232.42.49:80...
* Connected to registry.terraform.io (199.232.42.49) port 80 (#0)
> GET / HTTP/1.1
> Host: registry.terraform.io
> User-Agent: curl/7.81.0
```

### Steps to Reproduce

`curl -v registry.terraform.io`
... Or a webbrowser of your choice.

### Additional Context

Stumbled upon this when going through your terraform tutorial and I'm unsure if this is by design.
I couldn't find anything definitive in the terraform repo related to this, but perhaps this also affects any connections made after  declaring providers using the `hashicorp source`. 
Looks like it defaults to HTTP in all references throughout the repo (except explicit documentation).

**Comment by crw** [comment] 2022-11-29 23:41
Thanks for this report! I am going to guess this is intentional, leaving the decision to the user as to whether to incur the SSL overhead but I will check with the registry team. As this is not a bug with the Terraform core language or CLI, I am going to close this issue, but if I get an answer from the Registry team I will update this issue. Thanks!

**Closed by crw** 2022-11-29 23:41 UTC
Labels: bug, new

**Comment by crw** [comment] 2022-11-30 00:23
The official answer: this is the intended behavior for now, but this behavior will be changing in the future with a backend change we will be making. After that change, connections will be redirected to HTTPS. Thanks!
