### ISSUE TITLE
Non-specific error when provider is missing is difficult to troubleshoot

### ISSUE THREAD

**Issue by jimsnab** [hashicorp/terraform#29650] opened 2021-09-24 17:38 UTC
### Terraform Version

```
Terraform v1.0.7
on linux_amd64
+ provider nabancard.com/gcp/nab-gcp v0.1.0
+ provider registry.terraform.io/hashicorp/google v3.85.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.5.0
+ provider registry.terraform.io/hashicorp/vault v2.24.0
```

### Terraform Configuration Files

Several script error possibilities lead to this problem. For example, omit a provider.

### Debug Output

```
...
2021-09-24T13:26:58.647-0400 [TRACE] vertex "module.vault_admin_n.module.vault_keys.nab-gcp_bitwarden_tls_keys.vault_tls_files (expand)": visit complete
2021-09-24T13:26:58.647-0400 [TRACE] vertex "module.vault_admin_n.module.vault_keys (close)": starting visit (*terraform.nodeCloseModule)
2021-09-24T13:26:58.647-0400 [TRACE] vertex "module.vault_admin_n.module.vault_keys (close)": visit complete
2021-09-24T13:26:58.647-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps (expand)": starting visit (*terraform.nodeExpandModule)
2021-09-24T13:26:58.648-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps (expand)": visit complete
2021-09-24T13:26:58.648-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.vault_cluster_config (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2021-09-24T13:26:58.648-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.vault_cluster_config (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.648-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.vault_cluster_config (expand)": entering dynamic subgraph
2021-09-24T13:26:58.648-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.vault_cluster_config": starting visit (*terraform.nodeModuleVariable)
2021-09-24T13:26:58.649-0400 [TRACE] vertex "module.vault_admin_n.provider[\"nabancard.com/gcp/nab-gcp\"] (close)": starting visit (*terraform.graphNodeCloseProvider)
2021-09-24T13:26:58.649-0400 [TRACE] GRPCProvider: Close
2021-09-24T13:26:58.649-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app (expand)": starting visit (*terraform.nodeExpandModule)
2021-09-24T13:26:58.649-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app (expand)": visit complete
2021-09-24T13:26:58.649-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-09-24T13:26:58.650-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/nabancard.com/gcp/nab-gcp/0.1.0/linux_amd64/terraform-provider-nab-gcp pid=140781
2021-09-24T13:26:58.650-0400 [DEBUG] provider: plugin exited
2021-09-24T13:26:58.650-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.region (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2021-09-24T13:26:58.650-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.region (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.650-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.region (expand)": entering dynamic subgraph
2021-09-24T13:26:58.650-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.region": starting visit (*terraform.nodeModuleVariable)
2021-09-24T13:26:58.650-0400 [TRACE] evalVariableValidations: not active for module.vault_admin_n.module.vault_apps.var.region, so skipping
2021-09-24T13:26:58.650-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.region": visit complete
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.region (expand)": dynamic subgraph completed successfully
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.region (expand)": visit complete
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.region (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.region (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.region (expand)": entering dynamic subgraph
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.region": starting visit (*terraform.nodeModuleVariable)
2021-09-24T13:26:58.651-0400 [TRACE] evalVariableValidations: not active for module.vault_admin_n.module.vault_apps.module.vault_app.var.region, so skipping
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.region": visit complete
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.region (expand)": dynamic subgraph completed successfully
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.region (expand)": visit complete
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.zone (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.zone (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.zone (expand)": entering dynamic subgraph
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.zone": starting visit (*terraform.nodeModuleVariable)
2021-09-24T13:26:58.651-0400 [TRACE] evalVariableValidations: not active for module.vault_admin_n.module.vault_apps.var.zone, so skipping
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.zone": visit complete
2021-09-24T13:26:58.651-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.zone (expand)": dynamic subgraph completed successfully
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.zone (expand)": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.zone (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.zone (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.zone (expand)": entering dynamic subgraph
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.zone": starting visit (*terraform.nodeModuleVariable)
2021-09-24T13:26:58.652-0400 [TRACE] evalVariableValidations: not active for module.vault_admin_n.module.vault_apps.module.vault_app.var.zone, so skipping
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.zone": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.zone (expand)": dynamic subgraph completed successfully
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.zone (expand)": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] evalVariableValidations: not active for module.vault_admin_n.module.vault_apps.var.vault_cluster_config, so skipping
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.vault_cluster_config": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.vault_cluster_config (expand)": dynamic subgraph completed successfully
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.vault_cluster_config (expand)": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.project_id (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.project_id (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.project_id (expand)": entering dynamic subgraph
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.project_id": starting visit (*terraform.nodeModuleVariable)
2021-09-24T13:26:58.652-0400 [TRACE] evalVariableValidations: not active for module.vault_admin_n.module.vault_apps.var.project_id, so skipping
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.project_id": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.project_id (expand)": dynamic subgraph completed successfully
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.var.project_id (expand)": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id (expand)": starting visit (*terraform.nodeExpandModuleVariable)
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id (expand)": entering dynamic subgraph
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id": starting visit (*terraform.nodeModuleVariable)
2021-09-24T13:26:58.652-0400 [TRACE] evalVariableValidations: not active for module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id, so skipping
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id (expand)": dynamic subgraph completed successfully
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.var.project_id (expand)": visit complete
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release (expand)": starting visit (*terraform.nodeExpandPlannableResource)
2021-09-24T13:26:58.652-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release (expand)": expanding dynamic subgraph
2021-09-24T13:26:58.653-0400 [TRACE] vertex "module.vault_admin_n.provider[\"nabancard.com/gcp/nab-gcp\"] (close)": visit complete
2021-09-24T13:26:58.653-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release (expand)": entering dynamic subgraph
2021-09-24T13:26:58.653-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release": starting visit (*terraform.NodePlannableResource)
2021-09-24T13:26:58.653-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release": expanding dynamic subgraph
2021-09-24T13:26:58.653-0400 [TRACE] Executing graph transform *terraform.ResourceCountTransformer
2021-09-24T13:26:58.653-0400 [TRACE] ResourceCountTransformer: adding module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release as *terraform.NodePlannableResourceInstance
2021-09-24T13:26:58.653-0400 [TRACE] Completed graph transform *terraform.ResourceCountTransformer with new graph:
  module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release - *terraform.NodePlannableResourceInstance
  ------
2021-09-24T13:26:58.653-0400 [TRACE] Executing graph transform *terraform.OrphanResourceInstanceCountTransformer
2021-09-24T13:26:58.653-0400 [TRACE] Completed graph transform *terraform.OrphanResourceInstanceCountTransformer (no changes)
2021-09-24T13:26:58.653-0400 [TRACE] Executing graph transform *terraform.AttachStateTransformer
2021-09-24T13:26:58.653-0400 [DEBUG] Resource instance state not found for node "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release", instance module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.653-0400 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2021-09-24T13:26:58.653-0400 [TRACE] Executing graph transform *terraform.TargetsTransformer
2021-09-24T13:26:58.653-0400 [TRACE] Completed graph transform *terraform.TargetsTransformer (no changes)
2021-09-24T13:26:58.653-0400 [TRACE] Executing graph transform *terraform.ReferenceTransformer
2021-09-24T13:26:58.653-0400 [INFO]  ReferenceTransformer: reference not found: "path.module"
2021-09-24T13:26:58.653-0400 [INFO]  ReferenceTransformer: reference not found: "var.region"
2021-09-24T13:26:58.653-0400 [INFO]  ReferenceTransformer: reference not found: "var.zone"
2021-09-24T13:26:58.653-0400 [INFO]  ReferenceTransformer: reference not found: "var.project_id"
2021-09-24T13:26:58.653-0400 [DEBUG] ReferenceTransformer: "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release" references: []
2021-09-24T13:26:58.653-0400 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
2021-09-24T13:26:58.653-0400 [TRACE] Executing graph transform *terraform.RootTransformer
2021-09-24T13:26:58.653-0400 [TRACE] Completed graph transform *terraform.RootTransformer (no changes)
2021-09-24T13:26:58.653-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release": entering dynamic subgraph
2021-09-24T13:26:58.653-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release": starting visit (*terraform.NodePlannableResourceInstance)
2021-09-24T13:26:58.654-0400 [TRACE] readResourceInstanceState: reading state for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [TRACE] readResourceInstanceState: no state present for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to prevRunState for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [TRACE] states.SyncState: pruning module.vault_admin_n.module.vault_apps.module.vault_app because it is empty
2021-09-24T13:26:58.654-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to refreshState for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [TRACE] states.SyncState: pruning module.vault_admin_n.module.vault_apps.module.vault_app because it is empty
2021-09-24T13:26:58.654-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [TRACE] NodeAbstractResourceInstance.refresh for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [DEBUG] refresh: module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release: no state, so not refreshing
2021-09-24T13:26:58.654-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to refreshState for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.654-0400 [TRACE] states.SyncState: pruning module.vault_admin_n.module.vault_apps.module.vault_app because it is empty
2021-09-24T13:26:58.654-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:26:58.655-0400 [TRACE] Re-validating config for "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release"
2021-09-24T13:26:58.655-0400 [TRACE] GRPCProvider: ValidateResourceConfig
2021-09-24T13:26:58.656-0400 [TRACE] GRPCProvider: PlanResourceChange
2021-09-24T13:26:58.658-0400 [INFO]  provider.terraform-provider-helm_v2.3.0_x5: 2021/09/24 13:26:58 [DEBUG] [resourceDiff: vault] Start: timestamp=2021-09-24T13:26:58.658-0400
2021-09-24T13:27:00.344-0400 [INFO]  provider.terraform-provider-helm_v2.3.0_x5: 2021/09/24 13:27:00 [DEBUG] [resourceDiff: vault] Got chart: timestamp=2021-09-24T13:27:00.344-0400
2021-09-24T13:27:00.344-0400 [INFO]  provider.terraform-provider-helm_v2.3.0_x5: 2021/09/24 13:27:00 [DEBUG] [resourceDiff: vault] Release validated: timestamp=2021-09-24T13:27:00.344-0400
2021-09-24T13:27:00.344-0400 [INFO]  provider.terraform-provider-helm_v2.3.0_x5: 2021/09/24 13:27:00 [DEBUG] [resourceDiff: vault] Done: timestamp=2021-09-24T13:27:00.344-0400
2021-09-24T13:27:00.347-0400 [WARN]  Provider "registry.terraform.io/hashicorp/helm" produced an invalid plan for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .skip_crds: planned value cty.False for a non-computed attribute
      - .create_namespace: planned value cty.False for a non-computed attribute
      - .max_history: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .render_subchart_notes: planned value cty.True for a non-computed attribute
      - .verify: planned value cty.False for a non-computed attribute
      - .cleanup_on_fail: planned value cty.False for a non-computed attribute
      - .recreate_pods: planned value cty.False for a non-computed attribute
      - .disable_openapi_validation: planned value cty.False for a non-computed attribute
      - .lint: planned value cty.False for a non-computed attribute
      - .disable_crd_hooks: planned value cty.False for a non-computed attribute
      - .reuse_values: planned value cty.False for a non-computed attribute
      - .atomic: planned value cty.False for a non-computed attribute
      - .dependency_update: planned value cty.False for a non-computed attribute
      - .timeout: planned value cty.NumberIntVal(300) for a non-computed attribute
      - .disable_webhooks: planned value cty.False for a non-computed attribute
      - .reset_values: planned value cty.False for a non-computed attribute
      - .wait_for_jobs: planned value cty.False for a non-computed attribute
      - .force_update: planned value cty.False for a non-computed attribute
      - .replace: planned value cty.False for a non-computed attribute
      - .wait: planned value cty.True for a non-computed attribute
2021-09-24T13:27:00.347-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:27:00.347-0400 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:27:00.348-0400 [TRACE] writeChange: recorded Create change for module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release
2021-09-24T13:27:00.348-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release": visit complete
2021-09-24T13:27:00.348-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release": dynamic subgraph completed successfully
2021-09-24T13:27:00.348-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release": visit complete
2021-09-24T13:27:00.349-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release (expand)": dynamic subgraph completed successfully
2021-09-24T13:27:00.349-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app.helm_release.vault_release (expand)": visit complete
2021-09-24T13:27:00.349-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app (close)": starting visit (*terraform.nodeCloseModule)
2021-09-24T13:27:00.349-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps.module.vault_app (close)": visit complete
2021-09-24T13:27:00.349-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps (close)": starting visit (*terraform.nodeCloseModule)
2021-09-24T13:27:00.349-0400 [TRACE] vertex "module.vault_admin_n.module.vault_apps (close)": visit complete
2021-09-24T13:27:00.349-0400 [TRACE] dag/walk: upstream of "module.vault_admin_n (close)" errored, so skipping
2021-09-24T13:27:00.349-0400 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021-09-24T13:27:00.349-0400 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/helm\"] (close)": starting visit (*terraform.graphNodeCloseProvider)
2021-09-24T13:27:00.349-0400 [TRACE] GRPCProvider: Close
2021-09-24T13:27:00.351-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-09-24T13:27:00.391-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/helm/2.3.0/linux_amd64/terraform-provider-helm_v2.3.0_x5 pid=140797
2021-09-24T13:27:00.391-0400 [DEBUG] provider: plugin exited
2021-09-24T13:27:00.391-0400 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/helm\"] (close)": visit complete
2021-09-24T13:27:00.391-0400 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-09-24T13:27:00.391-0400 [INFO]  backend/local: plan operation completed
╷
│ Error: Missing required argument
│ 
│ The argument "address" is required, but was not set.
╵
2021-09-24T13:27:00.391-0400 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021-09-24T13:27:00.391-0400 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-09-24T13:27:00.397-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/vault/2.24.0/linux_amd64/terraform-provider-vault_v2.24.0_x4 pid=140750
2021-09-24T13:27:00.397-0400 [DEBUG] provider: plugin exited
```

### Expected Behavior

The error message should provide context:

```
| The provider "hashicorp/vault" argument "address" is required, but was not set.
| Make sure the provider is properly declared.
```

### Actual Behavior

The error message, in trace above, is non-specific, and the trace level log doesn't help much.

### Steps to Reproduce

There are lots of ways to end up with a non-specific error message. One of them is to take a working Terraform with Helm for Vault and add the following:

```
resource "vault_policy" "example" {
  name = "dev-team"

  policy = <<EOT
path "secret/hello" {
  capabilities = ["update"]
}
EOT
}
```

Because the Vault provider is not declared anywhere, yet is implicitly discovered, Terraform will error in this non-specific way.

**Comment by alisdair** [comment] 2021-12-02 14:44
Duplicate of #28482, tracking this issue over there.

**Closed by alisdair** 2021-12-02 14:44 UTC
Labels: enhancement, config
