### ISSUE TITLE
Terraform state doesn't replace values of local variables but adds them.

### ISSUE THREAD

**Issue by otromp** [hashicorp/terraform#27676] opened 2021-02-03 13:53 UTC
### Terraform Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0
```

### Terraform Configuration Files

```terraform
data "aws_subnet_ids" "selected" {
  vpc_id = "vpc-0eaeff0e5eff4036e"
  filter {
    name = "tag:Type"
    values = ["L2-PUB-GEN-PRD-DE1-OSS"]
  }
}

data "aws_subnet" "filtered" {
  for_each = data.aws_subnet_ids.selected.ids
  id       = each.value
}

locals {
  az_filtered_subnets = [
      for subnet in data.aws_subnet.filtered :{
        subnet_id = subnet.id
        az = subnet.availability_zone
      }
    ]
}

output "az_filtered_subnets" {
  value = local.az_filtered_subnets
}
```

### Expected Behavior
When the filter in data.aws_subnet_ids.selected changes the output should only show the data of the filtered subnets.

### Actual Behavior
The list was expanded with the data of the new filter.

### Steps to Reproduce
1. `terraform init`
```
[otromp@mbp ~/git/nl1-oss-prd/aws_test/bug-report (master *+)]$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v3.26.0...
- Installed hashicorp/aws v3.26.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
2. `terraform apply -auto-approve`
```
[otromp@mbp ~/git/nl1-oss-prd/aws_test/bug-report (master *+)]$ terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

az_filtered_subnets = [
  {
    "az" = "eu-central-1b"
    "subnet_id" = "subnet-03e5bd33172659ab2"
  },
  {
    "az" = "eu-central-1c"
    "subnet_id" = "subnet-08e6b24a1dcb57d2b"
  },
  {
    "az" = "eu-central-1a"
    "subnet_id" = "subnet-0ba8de526380cd177"
  },
]
```
3. `Changed the filter`
```terraform
data "aws_subnet_ids" "selected" {
  vpc_id = "vpc-0eaeff0e5eff4036e"
  filter {
    name = "tag:Type"
    values = ["L4-PRIV-APP-PRD-DE1-OSS]
  }
}
```
The filter was:  values = ["L2-PUB-GEN-PRD-DE1-OSS"]
4. `terraform apply -auto-approve`
```
[otromp@mbp ~/git/nl1-oss-prd/aws_test/bug-report (master *+)]$ terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

az_filtered_subnets = [
  {
    "az" = "eu-central-1b"
    "subnet_id" = "subnet-0207844920afa8f4d"
  },
  {
    "az" = "eu-central-1b"
    "subnet_id" = "subnet-03e5bd33172659ab2"
  },
  {
    "az" = "eu-central-1a"
    "subnet_id" = "subnet-04f61fc1a3abf0b1c"
  },
  {
    "az" = "eu-central-1c"
    "subnet_id" = "subnet-08cf7b0ed6d178eb3"
  },
  {
    "az" = "eu-central-1c"
    "subnet_id" = "subnet-08e6b24a1dcb57d2b"
  },
  {
    "az" = "eu-central-1a"
    "subnet_id" = "subnet-0ba8de526380cd177"
  },
]
```

### Additional Context
What we actually wanted to achieve is an map with the "az" as key and the "subnet_id" as value, like the example below
```terraform
az_filtered_subnets = {
    for subnet in data.aws_subnet.filtered :
      subnet.availability_zone => subnet.id
  }
```

But we stumbled upon this error message after a change in the filter and running `terraform apply` again:
```
[otromp@mbp ~/git/nl1-oss-prd/aws_test/bug-report (master *+)]$ terraform apply -auto-approve

Error: Duplicate object key

  on main.tf line 23, in locals:
  21:   az_filtered_subnets = {
  22:     for subnet in data.aws_subnet.filtered :
  23:       subnet.availability_zone => subnet.id
  24:   }
    |----------------
    | subnet.availability_zone is "eu-central-1a"

Two different items produced the key "eu-central-1a" in this 'for' expression.
If duplicates are expected, use the ellipsis (...) after the value expression
to enable grouping by key.


Error: Duplicate object key

  on main.tf line 23, in locals:
  21:   az_filtered_subnets = {
  22:     for subnet in data.aws_subnet.filtered :
  23:       subnet.availability_zone => subnet.id
  24:   }
    |----------------
    | subnet.availability_zone is "eu-central-1c"

Two different items produced the key "eu-central-1c" in this 'for' expression.
If duplicates are expected, use the ellipsis (...) after the value expression
to enable grouping by key.


Error: Duplicate object key

  on main.tf line 23, in locals:
  21:   az_filtered_subnets = {
  22:     for subnet in data.aws_subnet.filtered :
  23:       subnet.availability_zone => subnet.id
  24:   }
    |----------------
    | subnet.availability_zone is "eu-central-1b"

Two different items produced the key "eu-central-1b" in this 'for' expression.
If duplicates are expected, use the ellipsis (...) after the value expression
to enable grouping by key.
```

When we reverted back to terraform version: `Terraform v0.13.5` terraform behaved as expected.
By using a list in the outputs I could actually demonstrate what was going and see the list grow.

**Comment by jbardin** [comment] 2021-02-03 15:52
Hi @otromp 

Thanks for filing the issue. This appears to be a duplicate of #27617.

**Closed by jbardin** 2021-02-03 15:52 UTC
Labels: bug, new
