### ISSUE TITLE
Can't pass line feed character using command line -var option

### ISSUE THREAD

**Issue by hayden-mumm** [hashicorp/terraform#28795] opened 2021-05-24 19:28 UTC
### Terraform Version

```
0.15.4
```

### Terraform Configuration Files

```terraform
variable "test" {
    type = string
}
```

### Expected Behavior

When passing in a string via the -var argument on the command line it should set that value as "value\nnewline"
### Actual Behavior

The value was set with a literal backslash like this "value\\\\nnewline"
### Steps to Reproduce

terraform apply -var="test=value\nnewline"
Tried this in powershell and bash same issue.

**Comment by apparentlymart** [comment] 2021-05-26 19:08
Hi @hayden-mumm,

When you pass string values on the command line like this, it is your shell rather than Terraform that is responsible for processing them: Terraform just takes exactly the characters your shell provided and uses them.

Therefore I think the behavior you saw is expected because Bash doesn't support `\n` as an escape character in [that sort of quoted string](https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html).

Bash has an extension which its documentation calls "[ANSI-C Quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html)" which _does_ support escape sequences familiar from C, which is also what Terraform's quoted string syntax is (indirectly) inspired by. Therefore if you are using Bash then one way to get a newline there would be to use that alternative style of quote:

```bash
terraform apply -var=$'test=value\nnewline'
```

There are some other possibilities too. For example, if you are typing this command at the command line or in a shell script then you can put a _literal_ newline inside the quotes and bash will preserve it the same way that it preserves spaces in that context:

```bash
terraform apply -var=$'test=value
newline'
```

(If you're at an interactive prompt then Bash will typically display a secondary prompt, like `> `, to prompt you to enter the characters for the next line. I didn't include that above because I'm only showing what you would _type_, or what you'd include in a shell script.)

I tried both of these on my system here and saw them work as expected, and so Terraform seems to be working as intended here.

Unfortunately I'm not familiar enough with PowerShell to suggest a PowerShell way to write this, but I typically recommend against using PowerShell to run Terraform anyway, because PowerShell's mechanism where it parses its own syntax and then tries to generate a non-PowerShell command line to actually run an external program (rather than a cmdlet) typically leads to various sorts of complexity with escaping and quoting which will waste a lot of your time when it comes to passing in more complex variable values with lots of metacharacters in them.

By far the most _robust_ way to get values into Terraform variables is to eschew the `-var` option and use a `.tfvars` file, because then it will be Terraform itself parsing the file rather than your shell, and so the parsing behavior will be consistent across all platforms and shells.

Since Terraform itself seems to be working as designed here (when writing a suitable shell command line that actually includes a newline rather than the literal string `\n`), I'm going to close this issue. If you have further questions about shell escaping for Terraform, feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) to discuss that. Thanks!

**Closed by apparentlymart** 2021-05-26 19:08 UTC
Labels: bug, new
