### ISSUE TITLE
Question: Anyway to use lists and not use count.index?

### ISSUE THREAD

**Issue by lanmalkieri** [hashicorp/terraform#11470] opened 2017-01-27 18:25 UTC
So we are running into an issue where we want to manage users in TF for IAM. 

The problem is if we have a list of users 

variable "users" { default = "user1,user2,user3" }

And we call it like this

resource "aws_iam_user" "user" {
    count = "${length(compact(split(",", var.usernames)))}"
    name = "${element(split(",", var.usernames), count.index)}"
    path = "/"
}

Everytime we remove a user from that comma separated list the entire index updates and will change/remove other users. 

Is there anyway around this? How are others managing IAM users without running into this issue?

Thanks,

**Comment by mitchellh** [comment] 2017-01-27 19:31
There is another bug tracking this, it may be #3449, but I think there is another more specific one as well. This is something we're aware of but unfortunately don't have any exact timeline on a fix since the cause it quite complicated. :(

**Comment by mitchellh** [comment] 2017-01-27 19:31
(Closing for dup)

**Closed by mitchellh** 2017-01-27 19:31 UTC
