### ISSUE TITLE
openstack change floating ip error

### ISSUE THREAD

**Issue by dagnello** [hashicorp/terraform#5790] opened 2016-03-22 19:27 UTC
** Terraform Version: 0.6.13**
    Resource ID: openstack_compute_instance_v2.my_vm.0
    Mismatch reason: attribute mismatch: floating_ip
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"floating_ip":*terraform.ResourceAttrDiff{Old:"15.184.138.128", New:"${element(openstack_networking_floatingip_v2.my_floating_ip.*.address, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

The error happened when I changed my Terraform file to create two floating ip's instead of one.  Before running apply on the already deployed infrastructure, the first VM did not have a floating ip assigned and the second had a floating ip.  

**This is the output from the second run:**
openstack_networking_network_v2.my_net: Refreshing state... (ID: 6dcfb61f-2748-4ae6-abc9-5cb72f72bc43)
openstack_networking_router_v2.my_router: Refreshing state... (ID: 95eb6159-151c-4a43-bcb3-1c50f8446110)
openstack_compute_keypair_v2.my_keypair: Refreshing state... (ID: SSH keypair for Terraform instances)
openstack_compute_secgroup_v2.my_security_group: Refreshing state... (ID: 03f12972-7d3e-4929-b2ad-3fa7728a9e18)
openstack_networking_subnet_v2.my_subnet: Refreshing state... (ID: b5a9e2f4-3012-406e-b251-70ef547c522e)
openstack_networking_router_interface_v2.my_router_interface: Refreshing state... (ID: 85d2a962-fb39-4444-ba28-bedb0ac4b8b6)
openstack_networking_floatingip_v2.my_floating_ip.0: Refreshing state... (ID: 00cb4795-93e3-4d6d-8c60-e5738b52348f)
openstack_compute_instance_v2.my_vm.0: Refreshing state... (ID: b87888fe-f523-45a5-a9bd-d809b5e009c0)
openstack_compute_instance_v2.my_vm.1: Refreshing state... (ID: 5d8261a3-f72c-4d49-b714-575427b53b0c)
openstack_networking_floatingip_v2.my_floating_ip.1: Creating...
  address: "" => "<computed>"
  pool:    "" => "ext-net"
  port_id: "" => "<computed>"
  region:  "" => "region1"
openstack_networking_floatingip_v2.my_floating_ip.1: Creation complete
openstack_compute_instance_v2.my_vm.1: Modifying...
  floating_ip: "15.184.138.128" => "15.184.138.123"
openstack_compute_instance_v2.my_vm.1: Modifications complete

**Terraform file:**
provider "openstack" {
  user_name  = "${var.user_name}"
  tenant_name = "${var.tenant_name}"
  #password  = "${var.password}"
  auth_url  = "${var.auth_url}"
}

resource "openstack_compute_keypair_v2" "my_keypair" {
  name = "SSH keypair for Terraform instances"
  region = "${var.region}"
  public_key = "${file("${var.ssh_key_file}.pub")}"
}

resource "openstack_networking_network_v2" "my_net" {
  name = "my_net"
  region = "${var.region}"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "my_subnet" {
  name = "my_subnet"
  region = "${var.region}"
  network_id = "${openstack_networking_network_v2.my_net.id}"
  cidr = "192.168.50.0/24"
  ip_version = 4
  enable_dhcp = "true"
  dns_nameservers = ["208.67.222.222","208.67.220.220"]
}

resource "openstack_networking_router_v2" "my_router" {
  name = "my_router"
  region = "${var.region}"
  admin_state_up = "true"
  external_gateway = "${var.external_gateway}"
}

resource "openstack_networking_router_interface_v2" "my_router_interface" {
  region = "${var.region}"
  router_id = "${openstack_networking_router_v2.my_router.id}"
  subnet_id = "${openstack_networking_subnet_v2.my_subnet.id}"
}

resource "openstack_networking_floatingip_v2" "my_floating_ip" {
  # implicit dependency
  depends_on = ["openstack_networking_router_interface_v2.my_router_interface"]
  region = "${var.region}"
  pool = "${var.pool}"
  count = "${var.node_count}"
}

resource "openstack_compute_secgroup_v2" "my_security_group" {
  name = "my_security_group"
  region = "${var.region}"
  description = "Security group for the Terraform instances"
  rule {
    from_port = 1
    to_port = 65535
    ip_protocol = "tcp"
    cidr = "0.0.0.0/0"
  }
  rule {
    from_port = 1
    to_port = 65535
    ip_protocol = "udp"
    cidr = "0.0.0.0/0"
  }
  rule {
    ip_protocol = "icmp"
    from_port = "-1"
    to_port = "-1"
    cidr = "0.0.0.0/0"
  }
}

resource "openstack_compute_instance_v2" "my_vm" {
  name = "my_vm_${count.index}"
  region = "${var.region}"
  image_name = "${var.image}"
  flavor_name = "${var.flavor}"
  key_pair = "${openstack_compute_keypair_v2.my_keypair.name}"
  security_groups = [ "${openstack_compute_secgroup_v2.my_security_group.name}" ]
  floating_ip = "${element(openstack_networking_floatingip_v2.my_floating_ip.*.address, count.index)}"

  count = "${var.node_count}"

  network {
    uuid = "${openstack_networking_network_v2.my_net.id}"
  }
}

**Comment by jtopjian** [comment] 2016-03-22 19:39
Thanks for reporting this. Since this involves `count` and `element`, I want to point out #3449 which is a bug that affects all types of computed/interpolated resources. 

However, I'd be happy to try to reproduce this on my end. Can you provide the before and after Terraform configurations? In your description you said "The error happened when I changed my Terraform file" -- can I see both the original and modified versions?

**Comment by dagnello** [comment] 2016-03-22 23:38
no problem @jtopjian.  This was my Terraform file before:

provider "openstack" {
  user_name  = "${var.user_name}"
  tenant_name = "${var.tenant_name}"
  #password  = "${var.password}"
  auth_url  = "${var.auth_url}"
}

resource "openstack_compute_keypair_v2" "my_keypair" {
  name = "SSH keypair for Terraform instances"
  region = "${var.region}"
  public_key = "${file("${var.ssh_key_file}.pub")}"
}

resource "openstack_networking_network_v2" "my_net" {
  name = "my_net"
  region = "${var.region}"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "my_subnet" {
  name = "my_subnet"
  region = "${var.region}"
  network_id = "${openstack_networking_network_v2.my_net.id}"
  cidr = "192.168.50.0/24"
  ip_version = 4
  enable_dhcp = "true"
  dns_nameservers = ["208.67.222.222","208.67.220.220"]
}

resource "openstack_networking_router_v2" "my_router" {
  name = "my_router"
  region = "${var.region}"
  admin_state_up = "true"
  external_gateway = "${var.external_gateway}"
}

resource "openstack_networking_router_interface_v2" "my_router_interface" {
  region = "${var.region}"
  router_id = "${openstack_networking_router_v2.my_router.id}"
  subnet_id = "${openstack_networking_subnet_v2.my_subnet.id}"
}

resource "openstack_networking_floatingip_v2" "my_floating_ip" {
  # implicit dependency
  depends_on = ["openstack_networking_router_interface_v2.my_router_interface"]
  region = "${var.region}"
  pool = "${var.pool}"
}

resource "openstack_compute_secgroup_v2" "my_security_group" {
  name = "my_security_group"
  region = "${var.region}"
  description = "Security group for the Terraform instances"
  rule {
    from_port = 1
    to_port = 65535
    ip_protocol = "tcp"
    cidr = "0.0.0.0/0"
  }
  rule {
    from_port = 1
    to_port = 65535
    ip_protocol = "udp"
    cidr = "0.0.0.0/0"
  }
  rule {
    ip_protocol = "icmp"
    from_port = "-1"
    to_port = "-1"
    cidr = "0.0.0.0/0"
  }
}

resource "openstack_compute_instance_v2" "my_vm" {
  name = "my_vm_${count.index}"
  region = "${var.region}"
  image_name = "${var.image}"
  flavor_name = "${var.flavor}"
  key_pair = "${openstack_compute_keypair_v2.my_keypair.name}"
  security_groups = [ "${openstack_compute_secgroup_v2.my_security_group.name}" ]
  floating_ip = "${openstack_networking_floatingip_v2.my_floating_ip.address}"

  count = "${var.node_count}"

  network {
    uuid = "${openstack_networking_network_v2.my_net.id}"
  }
}

**Comment by jtopjian** [comment] 2016-04-05 05:36
I'm very sorry for the delay. I've just had a chance to confirm that this is indeed the same issue as described in #3449. I'm going to close this issue in favor of it, but please let me know if you have any questions.

**Closed by jtopjian** 2016-04-05 05:36 UTC
Labels: provider/openstack
