### ISSUE TITLE
`for_each` should accept optional maps / optional objects

### ISSUE THREAD

**Issue by ari-becker** [hashicorp/terraform#32372] opened 2022-12-11 13:52 UTC
### Terraform Version

```shell
Terraform v1.3.6
on darwin_arm64
```

### Use Cases

Reducing the cognitive load of learning/teaching how to use `for_each` properly to junior engineers, one of whom didn't understand why he couldn't just pass an `optional(object({...}))` to the `for_each`.

### Attempted Solutions

Using `try(var.optional_object, {})` as a workaround

### Proposal

Currently, `for_each` requires either a `set(string)` or a `map(any)` (and by extension, `object(any)`).
It should also support `optional(map(any))` (and by extension, `optional(object(any))`).
If the `optional` is empty, then the `for_each` does not iterate over the empty optional.
If the `optional` is not empty, then the `for_each` iterates over the fields in the embedded `map` / `object`, same as if that `map` or `object` was passed directly to the `for_each`.

**Comment by jbardin** [comment] 2022-12-12 13:40
Hi @ari-becker,

Thanks for filing the issue. Can you give a more complete example of what exactly you are proposing? There are no `optional` objects or maps -- `optional` can only be used on an attribute in a type constraint, only applied to the defaults and not the runtime type, and does not effect the argument of `for_each` because the type is known at runtime. It may help to explain what the use of `try(var.optional_object, {})` was intended to do, because accessing a variable cannot fail, so the `try` function would not do anything.

Thanks!

**Comment by ari-becker** [comment] 2022-12-12 17:48
Hi @jbardin , I think I was a bit rushed or something when I created the issue, I guess what I wrote is not so clear. Particularly the `try(var.optional_object, {})` part is just flat out wrong. Apologies!

Consider a resource like [`mongodbatlas_alert_configuration`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/alert_configuration) which can be configured with a block (i.e. [`metric_threshold_config`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/alert_configuration#metric-threshold-config-metric_threshold_config)) which is optional. Consider a module author who wants to expose the configuration for this block as a whole. Inside the module,  the resource's block would thus be configured as a `dynamic`, e.g.

```terraform
variable "placeholder" {
  type = optional(object({
    field_a = string
    field_b = string
  }))
}

resource "foo" "this" {
  dynamic "optional_block" {
    for_each = var.placeholder
    content {
      field_a = optional_block.value["field_a"]
      field_b = optional_block.value["field_b"]
    }
  }
}
```

This would fail because `var.placeholder` is not a `set(string)` or a `map`.

Instead, we currently need to use the following boilerplate, which is not intuitive:

```terraform
for_each = var.placeholder != null ? { "enabled" : var.placeholder } : {}
```

It would be more intuitive if Terraform accepted `for_each = var.placeholder`, because it is `optional`.

**Comment by jbardin** [comment] 2022-12-19 14:35
Since a value in Terraform does not carry any sort of "optional" metadata, there doesn't appear to be any possible changes to be made here. I'm going to close this for now, but if you have more questions feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2022-12-19 14:35 UTC
Labels: enhancement, waiting-response, working as designed
