### ISSUE TITLE
show command does not handle sensitive input variables in the default human readable mode

### ISSUE THREAD

**Issue by tanasegabriel** [hashicorp/terraform#28186] opened 2021-03-24 14:29 UTC
### Terraform Version

```
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.33.0
```

Also tested with `Terraform v0.14.8`, which is the latest stable release at the moment of writing this - the issue is still encountered.

### Expected Behavior
`terraform show <bin_file_path>` should redact sensitive values from its output, unless `-json` is passed, indicating machine readable output. According to [the documentation](https://www.terraform.io/docs/cli/commands/show.html):
![image](https://user-images.githubusercontent.com/20187768/112326445-6fa0ba00-8cac-11eb-8ab0-28e556a84df0.png)

This indicates that sensitive data is intended to be redacted when the default human readable output is used, though this might be confusing seeing how `show` handles both a provisional binary plan file and a statefile.
### Actual Behavior
```bash
$ tail -n6 variables.tf
variable "GITHUB_TOKEN" {
  type        = string
  description = "GitHub OAuth token for CodePipeline."
  sensitive   = true
}

$ grep -B1  "var.GITHUB_TOKEN" main.tf
      configuration = {
        OAuthToken = var.GITHUB_TOKEN

$ terraform plan -var="GITHUB_TOKEN=this_is_a_test" -out=/tmp/test_plan.bin | grep -B1 OAuthToken
              ~ configuration    = {
                  ~ "OAuthToken" = (sensitive)

$ terraform show /tmp/test_plan.bin | grep -B1 OAuthToken
              ~ configuration    = {
                  ~ "OAuthToken" = "<previous_token_manually_redacted>" -> "this_is_a_test"
```
### Steps to Reproduce

1.  Create a sensitive input variable and assign it a random value. Reference it as part of a resource
2.  Run `terraform plan -out=<random_file>` and observe that the sensitive variable is redacted from the plan
3. Run `terraform show <random_file>` and observe that the sensitive value is displayed in plain text

**Comment by alisdair** [comment] 2021-03-24 17:14
Hi @tanasegabriel, thanks for reporting this. I believe this is a duplicate of #27577, so I'm closing so we can consolidate the two issues.

**Closed by alisdair** 2021-03-24 17:14 UTC
Labels: bug, new
