### ISSUE TITLE
Feature: Support Route53 CreateVPCAssociationAuthorization

### ISSUE THREAD

**Issue by elconas** [hashicorp/terraform#11174] opened 2017-01-12 07:47 UTC
Hi there,

we are using a multi account AWS Setup (consolidated billing) with unified PRIVATE and PUBLIC DNS Namespace. As transitive routing is not supported, we need to associate PRIVATE Route53 Zones in sibling / project / department accounts to a VPC in a shared services account which hosts some DNS Servers. This allows DNS self service for the users and transparent DNS resolution.

Until now we needed to open a ticket with AWS which takes a lot of time to do the cross account association. Now AWS added API Support for this (woohoo!): 

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs-different-accounts.html

Currently Terraform does not support this. It would be great if this would be added. 

Regards, 
Robert

**Comment by stack72** [comment] 2017-01-12 14:35
Hi @elconas 

Thanks for the feature request here - I am going to close this as a duplicate of #10208 

Thanks

Paul

**Closed by stack72** 2017-01-12 14:35 UTC
