### ISSUE TITLE
Whats going on with the terraform docs?

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform#26934] opened 2020-11-16 16:46 UTC
A bunch of pages seems to be missing and aren't even indexed by google now?

For example I'm looking for documentation for google_storage_bucket_iam_binding and I cant find it anywhere: https://registry.terraform.io/modules/terraform-google-modules/iam/google/modules/storage_buckets_iam

I find what look like copies of the tf docs on these weird other sites like this one: http://man.hubwiz.com/docset/Terraform.docset/Contents/Resources/Documents/docs/providers/google/r/storage_bucket_iam.html

Whats happening here? Is the documentation moving to another place or is there a problem with the website? Recently its been super frustrating to find documentation for some resources.

**Comment by alisdair** [comment] 2020-11-16 17:35
I think the documentation you're looking for is available here: https://registry.terraform.io/modules/terraform-google-modules/iam/google/latest/submodules/storage_buckets_iam

It's possible these URLs have changed recently and a redirect was forgotten. I'm checking with the Terraform Registry team.

Where are you seeing the link to the original URL you mentioned?

**Comment by tpoindessous** [comment] 2020-11-16 17:37
Hi @alisdair 

there is a problem 

If you search on google : google_sql_database_instance site:registry.terraform.io , you can't find this url 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance

since documentation moved to https://registry.terraform.io/ , SEO is quite a problem.

Thanks !

**Comment by alisdair** [comment] 2020-11-16 17:39
@tpoindessous I can't reproduce that issue at all. Here's a search for the term you suggested, which returns the result you were looking for at the top:

https://www.google.com/search?q=google_sql_database_instance+site%3Aregistry.terraform.io&oq=google_sql_database_instance+site%3Aregistry.terraform.io

Am I missing something?

**Comment by tpoindessous** [comment] 2020-11-16 18:00
Yes :)

first result is

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database

for sql_database when the search is for sql_database_instance

Thanks !

**Comment by alisdair** [comment] 2020-11-16 18:17
I see, thanks for pointing that out. I've passed your feedback on to the Terraform Registry team.

**Comment by aicarmic** [comment] 2020-11-16 18:32
@red8888 @tpoindessous Thanks for the reports on this. We had a temporary issue with indexing on some of our provider docs in the Terraform Registry which as been addressed. We are awaiting those changes to propagate, hopefully soon.

**Comment by red8888** [comment] 2020-11-16 23:09
hey thanks for the super quick response! 

As far as SEO goes I do lean on googling the resource names but if its searchable on the site at least thats good enough for me!

**Comment by danieldreier** [comment] 2020-11-16 23:51
@red8888 I'm going to close this because it's been answered, but I appreciate you bringing it up!

**Closed by danieldreier** 2020-11-16 23:51 UTC
Labels: bug, registry
