### ISSUE TITLE
AWS EIP Import is not working in for_each

### ISSUE THREAD

**Issue by Jithinxavi** [hashicorp/terraform#34112] opened 2023-10-18 18:31 UTC
### Terraform Version

```shell
Terraform v1.5.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.21.0
```

### Terraform Configuration Files

```
module "elastic_ip" {
  source           = "<module-path>elastic_ip"

  eip_allocation_ids      = var.eip_allocation_ids
  custom_tags             = local.tags
}
```

Module
```
resource "aws_eip" "elastic_ip" {
  for_each      = toset(var.eip_allocation_ids)
  
  domain            = "vpc"
  tags              = var.custom_tags
  lifecycle {
    ignore_changes = [
      tags["CreatedDate"]
    ]
  }
}
```

### Debug Output

 terragrunt terragrunt import 'module.elastic_ip.aws_eip.elastic_ip["eipalloc-03dxxx"]' eipalloc-03dxxx

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

### Expected Behavior

The allocation ID should have been imported to the state, but the state is empty

### Actual Behavior

Despite successful import of output, state is not imported.

### Steps to Reproduce

terragrunt import 'module.elastic_ip.aws_eip.elastic_ip["eipalloc-03dxxx"]' eipalloc-03dxxx

**Comment by apparentlymart** [comment] 2023-10-18 18:41
Hi @Jithinxavi! Sorry this didn't work as expected.

Can you share more details on what exactly you ran in order to reach the conclusion that the object wasn't imported? Unfortunately with only what you've shared so far I'm not sure how to reproduce what you've reported.

**Comment by Jithinxavi** [comment] 2023-10-19 06:32
@apparentlymart , When I run the terragrunt import command, getting the following output.
```
terragrunt import 'module.elastic_ip.aws_eip.elastic_ip["eipalloc-03dc688994929ba00"]' eipalloc-03xxxx

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
however my state file is empty, I verified that using - terragrunt state list

But for some reason import is working fine if I defined the values in my var.tfvars file,
eip_allocation_ids = ["eipalloc-03xxxx","eipalloc-xxx","eipalloc-xxx"]

```
terragrunt import 'module.elastic_ip.aws_eip.elastic_ip["eipalloc-03xxxx"]' eipalloc-03xxxx
module.elastic_ip.aws_eip.elastic_ip["eipalloc-03xxxx"]: Importing from ID "eipalloc-03xxxx"...
module.elastic_ip.aws_eip.elastic_ip["eipalloc-03xxxx"]: Import prepared!
  Prepared aws_eip for import
module.elastic_ip.aws_eip.elastic_ip["eipalloc-06151ac12a4b0ebdd"]: Refreshing state... [id=eipalloc-03xxxx]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
````

**Comment by apparentlymart** [comment] 2023-10-19 14:45
Thanks for that extra context, @Jithinxavi!

Unfortunately Terragrunt is a third-party wrapper that I'm not intensely familiar with beyond its main plan/apply workflow. Although it seems unlikely to me that Terragrunt is interfering here, could we confirm that by having you try this directly with Terraform CLI instead of using Terragrunt to wrap it?

From what I can tell from the example commands you've shared, I think just replacing "terragrunt" with "terraform" in the command lines you are running might be enough, although that does depend on how exactly you've configured Terragrunt and in particular whether you are relying on any of its code generation behaviors that would not occur if you just run Terraform CLI directly.

My main goal here is to try to reach a point where I can reproduce what you've seen, and so I'm just trying to simplify the situation to the smallest possible reproduction, since of course I don't have access to your Terragrunt configuration or to your AWS account. Thanks!

**Comment by jbardin** [comment] 2023-10-19 17:12
@Jithinxavi, you say it works fine if you add the correct values to `eip_allocation_ids` in your variables file, which is expected because a matching configuration is required to import a resource instance. The fact that this did not produce an error was a flaw in the v1.5 release, and is fixed in the latest releases.

**Comment by jbardin** [comment] 2023-10-26 15:00
Since this appears to be working as expected in the given release version, I'm going to close the issue for now. If you still have problems with the current Terraform release, feel free to add more information here and we can reevaluate the issue.

Thanks!

**Closed by jbardin** 2023-10-26 15:00 UTC
Labels: bug, waiting-response, new, v1.5
