### ISSUE TITLE
Invalid default value for string: string required, but type is a list

### ISSUE THREAD

**Issue by maystreet-its** [hashicorp/terraform#31495] opened 2022-07-22 15:10 UTC
```
$ terraform version
Terraform v1.2.2
on darwin_amd64
```

We're seeing some confusing behavior here, but I'm unsure if this is a result of how Terraform `defaults` works.  (Good news is this "feature" is being replaced with a much more intuitive `optional` second argument in 1.3!)

Here's a use case:

```
terraform {
  experiments = [
    module_variable_optional_attrs
  ]
}

variable "examples" {
  type = map(
    object({
      nested_object = optional(
        object({
          nested_array = list(string)
        })
      )
    })
  )
  default = {}
}

locals {
  examples = {
    for example_key, example in var.examples : example_key => defaults(
      example,
      {
        nested_object = {
          nested_array = ["Example"]
        }
      }
    )
  }
}
```

The idea is we have a map of key to objects, and each object has some defaults.  In this case we want the default for `nested_object` to be an object with `nested_array` equal to a list of strings, consistent with the type specification.

Given this variable:

```
examples = {
  "test" = {
  }
}
```

The goal is that we get a default for `nested_object` (the whole of which is optional) the value 

```
{
          nested_array = ["Example"]
}
```

Simple enough.

But when executing `terraform apply` we see this error, which is quite confusing:

```
│ Error: Invalid function argument
│
│   on example.tf line 24, in locals:
│   22:     for example_key, example in var.examples : example_key => defaults(
│   23:       example,
│   24:       {
│   25:         nested_object = {
│   26:           nested_array = ["Example"]
│   27:         }
│   28:       }
│   29:     )
│
│ Invalid value for "defaults" parameter: .nested_object.nested_array: invalid
│ default value for string: string required.
```

I'm not sure this is a bug; as I said, it might be a quirk of how `defaults` works, but regardless, wanted to verify.

Thanks.

**Comment by apparentlymart** [comment] 2022-07-22 16:05
Hi @maystreet-its!

Indeed, this seems like `defaults` working as intended, even though its intention didn't match your intention. Specifically, it's expecting you to assign to `nested_array` a single value to use when any element of that list is `null`, not a value to use when the list _itself_ is `null`.

Since `defaults` has already been removed and will no longer be present in the v1.3 release anyway, I'm afraid this behavior just is what it is in the experimental form of this feature in earlier versions. If you want to provide a default value for the list as a whole then you'll need to use a different technique to achieve that.

**Closed by apparentlymart** 2022-07-22 16:05 UTC
Labels: bug, new

**Comment by maystreet-its** [comment] 2022-07-22 16:46
> Specifically, it's expecting you to assign to nested_array a single value to use when any element of that list is null, not a value to use when the list itself is null.

That explains the error.   So sounds like there is no way to use nested optional fields in this case?  Thanks much for the clarification!

We're good waiting for 1.3, although will that work a bit more simply? Meaning, just specify optional in a nested way, as in:

```
variable "examples" {
  type = map(
    object({
      nested_object = optional(
        object({
          nested_array = optional(list(string), ["Example"])
        }),
        {}
      )
    })
  )
  default = {}
}
```

**Comment by apparentlymart** [comment] 2022-07-22 17:05
I'm not sure I fully understand your example, but I think you are talking about one of the main differences between the `defaults` function and the new integrated default values support: there is distinct syntax for saying "this whole list attribute is optional and has a default" vs. "the elements of this list attribute contain optional things which have defaults themselves", and so you can do either or both.

If I didn't understand what you were referring to, or if you want to add some other feedback of any sort, I'd suggest posting in [the community forum thread for feedback on the new feature](https://discuss.hashicorp.com/t/request-for-feedback-optional-object-type-attributes-with-defaults-in-v1-3-alpha/40550/34), since that's the main place that we're looking for general, broad feedback (as opposed to specific problems like bug reports) and we'll continue to look there through the rest of the v1.3 development period while there's still room for tweaking the design before it's included in a stable release.

Thanks!

**Comment by maystreet-its** [comment] 2022-07-22 19:06
>  there is distinct syntax for saying "this whole list attribute is optional and has a default" vs. "the elements of this list attribute contain optional things which have defaults themselves", and so you can do either or both.

I was just saying I don't know if there's a way to eliminate the redundancy present in the second example in my most recent posting.  Agreed, though: at this point the conversation belongs elsewhere.  I'll see how the new syntax works for our use cases once 1.3 is released.

**Comment by apparentlymart** [comment] 2022-07-22 19:18
Oh, I see... you have asked a question similar to one someone asked in the forum topic I linked to, so you can see a more complete discussion of it over there, but the short answer is that you don't need to include `nested_array = ["Example"]` in the default value for `nested_object`, because the optional-ness (and associated default) of that nested object type also applies to the automatic type conversion Terraform will perform to make the default value conform to the attribute's type.

**Comment by maystreet-its** [comment] 2022-07-22 19:21
I was hoping that was the case.  Fantastic.  Thanks again for the useful clarifications.
