### ISSUE TITLE
Custom Validation condition accessing other variables

### ISSUE THREAD

**Issue by josh-barker** [hashicorp/terraform#26229] opened 2020-09-14 08:12 UTC
### Current Terraform Version

```
terraform v0.13.2
```

### Use-cases

Hi,

We have situations where we want to create validation rules based on the value of of another variable.

For example, backup policies.

```hcl
variable "frequency" { 
  type = string

  validation {
    condition = contains(["Daily", "Weekly"], var.frequecy)
    error_condition = "Must be Daily or Weekly."
  }
}

variable "retain_daily_backups" {
  type = number
  default = null

  validation {
    condition = var.frequency == "Daily" && var.retain_daily_backups >= 42 && var.retain_daily_backups < 1000
    error_condition = "Must specify daily backup value."
  }
}

variable "retain_weekly_backups" {
  type = number
  default = null

  validation {
    condition = var.frequency == "Weekly" && var.retain_weekly_backups >= 42 && var.retain_weekly_backups < 1000
    error_condition = "Must specify weekly backup value."
  }
}
```

### Proposal

Allow validation block to access other variables apart from itself.

## References

- #23794
- #25624

**Comment by apielasa** [comment] 2021-01-11 12:27
I was just about to create this feature request. Faced the same problem as you did @josh-barker.

**Comment by AswinKakarot** [comment] 2021-01-12 10:49
I would also like to add accessing `locals` from within validation to reduce the complexity of condition statements
Example:
```hcl
locals {
  storage_class = ["MULTI_REGIONAL", "REGIONAL", "NEARLINE", "COLDLINE", "ARCHIVE", "STANDARD", "DURABLE_REDUCED_AVAILABILITY"]
}
```
```hcl
variable "storage_class" {
  type = string
  default = "STANDARD"
  validation {
    condition = contains(local.storage_class, var.storage_class)
    error_message = "Supported values include: MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE, STANDARD, DURABLE_REDUCED_AVAILABILITY."
  }
}
```

rather than writing again and again
```hcl
variable "storage_class" {
  type = string
  default = "STANDARD"
  validation {
    condition = contains(["MULTI_REGIONAL", "REGIONAL", "NEARLINE", "COLDLINE", "ARCHIVE", "STANDARD", "DURABLE_REDUCED_AVAILABILITY"], var.storage_class)
    error_message = "Supported values include: MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE, STANDARD, DURABLE_REDUCED_AVAILABILITY."
  }
}
```

**Comment by imaginarynik** [comment] 2021-03-26 08:55
Is there an update on this?

**Comment by dayglojesus** [comment] 2021-05-13 16:25
The features described in this thread are essential to DRY code.

**Comment by SphenicPaul** [comment] 2022-04-09 10:48
Agree with @AswinKakarot that having this (input) variable, validation functionality able to reference local variables would save a lot of duplication of effort and code... especially where validating (input) variable values against an array/list or map of keys and/or values that are defined as local variables and used in multiple places - I've hit this requirement today. 

This might even be able to extend into using additional, nested resource/module/data output variables as part of the conditions? - Guess there will be some sort of dependency/resolution order to consider, but this sort of functionality might be especially useful if writing modules (obviouslty, wrapping around resources and other modules) and being able to use outputs from those nested resources and modules to validate input into the modules that are wrapping around and/or making use of them - This would prevent/reduce having to make direct/intermediate changes to the wrapper module(s) and allow the output variables to be passed through/up the module dependency chain.

**Comment by joe-a-t** [comment] 2022-05-26 18:41
Mostly duplicate of https://github.com/hashicorp/terraform/issues/25609 so https://github.com/hashicorp/terraform/issues/25609#issuecomment-903021665 is probably the HashiCorp response. The main differentiation I see with this issue is the explicit calling out of allowing the use of locals, which isn't explicitly called out in https://github.com/hashicorp/terraform/issues/25609 but would probably also be solved by the proposed solution

**Comment by apparentlymart** [comment] 2024-05-30 15:33
Hi all,

Indeed, this does seem to be effectively a duplicate of https://github.com/hashicorp/terraform/issues/25609, which is now closed with the solution expected to arrive in the forthcoming Terraform v1.9.0 release.

Thanks!

**Closed by apparentlymart** 2024-05-30 15:33 UTC
Labels: enhancement, new
