### ISSUE TITLE
Using try() with S3 as remote data storage backend does not work as expected

### ISSUE THREAD

**Issue by jeohist** [hashicorp/terraform#28432] opened 2021-04-19 04:32 UTC
### Terraform Version

```
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.37.0
```

### Terraform Configuration Files

```terraform
locals {
  region = "eu-central-1"
}

provider "aws" {
  region = local.region
}

terraform {
  backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~>3.0"
    }
  }

  required_version = "0.15.0"
}

data "terraform_remote_state" "this" {
  backend   = "s3"
  workspace = terraform.workspace

  config = {
    bucket = "bucket-${try("not_exists", "exists")}"
    region = "eu-central-1"
    key    = "terraform.tfstate"
  }
}
```

### Debug Output
https://gist.github.com/jeohist/e85f2cee15e849365206bbd9d5074919

### Expected Behavior
In this situation, there are two S3 buckets: `bucket-exists`, which exists, and `bucket-not_exists`, which does not exist. I expect to be able to use `try()` to get the first bucket that exists, as written in the documentation ("returns the result of the first one that does not produce any errors").

### Actual Behavior
I get an error:

```
Error: Error loading state error

  on main.tf line 26, in data "terraform_remote_state" "this":
  27:   backend   = "s3"

error loading the remote state: S3 bucket does not exist.

The referenced S3 bucket must have been previously created. If the S3 bucket
was created within the last minute, please wait for a minute or two and try
again.

Error: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: ..., host id: ...
```

### Steps to Reproduce
1. `terraform init`
1. `terraform plan`

**Comment by mildwonkey** [comment] 2021-04-19 15:01
Hi @jeohist ,
The `try` function returns the first successful result of the expression _inside the try function itself_. In this example, "not_exists" and "exists" are strings, and so neither would return an error. The `try()` function cannot act on information outside of the function call - `try` itself has no way of knowing that what you are actually trying to determine is if a bucket named `bucket-not-exists` exists. 

Since this is expected behavior, I am going to close this issue. If you have any more questions about this topic, I suggest you post in [the community forum](https://discuss.hashicorp.com/c/terraform-core).

**Closed by mildwonkey** 2021-04-19 15:01 UTC
Labels: bug, new
