### ISSUE TITLE
File provisioner - fails to upload when the path contains ~ with terraform version 1.1.x

### ISSUE THREAD

**Issue by aishwaryabk** [hashicorp/terraform#30632] opened 2022-03-09 07:27 UTC
### Terraform Version
These issues are seen with Terraform versions (1.1.x) only.

```
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/community-terraform-providers/ignition v2.1.2
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.39.0

```

### Debug Output
```
^[[0m^[[1mmodule.prepare.ibm_pi_instance.bastion[0]: Creation complete after 14m57s [id=bc895dc9-f626-41c0-bfd3-94a0d8942a5f/aaac601f-b0d3-4ac5-b8c2-61c129a6fca2]^[[0m
^[[0m^[[1mmodule.prepare.data.ibm_pi_instance_ip.bastion_public_ip[0]: Reading...^[[0m^[[0m
^[[0m^[[1mmodule.prepare.data.ibm_pi_instance_ip.bastion_ip[0]: Reading...^[[0m^[[0m
^[[0m^[[1mmodule.prepare.data.ibm_pi_instance_ip.bastion_ip[0]: Read complete after 1s [id=4ae4b482-dfd4-489b-ba67-29d40ab5c088]^[[0m
^[[0m^[[1mmodule.prepare.data.ibm_pi_instance_ip.bastion_public_ip[0]: Read complete after 3s [id=154cab5a-fb4f-455d-b40a-30b76f426f7e]^[[0m
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0]: Creating...^[[0m^[[0m
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0]: Provisioning with 'remote-exec'...^[[0m^[[0m
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0mConnecting to remote host via SSH...
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  Host: 169.54.112.243
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  User: root
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  Password: false
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  Private key: true
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  Certificate: false
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  SSH Agent: false
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  Checking Host Key: false
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0m  Target Platform: unix
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0mConnected!
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0] (remote-exec):^[[0m ^[[0mroot
^[[0m^[[1mmodule.prepare.null_resource.bastion_init[0]: Provisioning with 'file'...^[[0m^[[0m
╷
│ Error: file provisioner error
│
│   with module.prepare.null_resource.bastion_init[0],
│   on modules/1_prepare/prepare.tf line 134, in resource "null_resource" "bastion_init":
│  134:   provisioner "file" {
│
│ Upload failed: scp: ~/.ssh: No such file or directory
```

### Expected Behavior
```
The private and public key files should have been uploaded to the .ssh folder in the $HOME directory of the deployed VM without errors.
```

### Actual Behavior
```
module.prepare.null_resource.bastion_init[0]: Provisioning with 'file'...
Error: file provisioner error

  with module.prepare.null_resource.bastion_init[0],
  on modules/1_prepare/prepare.tf line 134, in resource "null_resource" "bastion_init":
 134:   provisioner "file" {

Upload failed: scp: ~/.ssh: No such file or directory
```

### Steps to Reproduce
```
provisioner "file" {
    content     = var.private_key
    destination = "~/.ssh/id_rsa"
  }

provisioner "file" {
    content     = var.public_key
    destination = "~/.ssh/id_rsa.pub"
  }
```

### Additional Context
When using the latest Terraform versions (1.1.x), there seems to be some change in the ~ expansion.
There are no errors seen with the Terraform versions (1.0.x).

**Comment by jbardin** [comment] 2022-03-09 14:36
Duplicate of #30243 and #30328

**Closed by jbardin** 2022-03-09 14:36 UTC
Labels: bug, new
