### ISSUE TITLE
Sensitive inputs are visible in terminal

### ISSUE THREAD

**Issue by kamil-wojcik** [hashicorp/terraform#29609] opened 2021-09-19 21:36 UTC
### Terraform Version

```
terraform version
Terraform v1.0.7
on linux_amd64
```

### Terraform Configuration Files

```terraform
variable "secret" {
    sensitive = true
}

variable "plain" {
    sensitive = false
}
```

### Debug Output

```
terraform plan
var.plain
  Enter a value: plain-value

var.secret
  Enter a value: secret-value


No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are
needed.

```

### Expected Behavior

Input for sensitive variables should be masked

### Actual Behavior

When value for sensitive variable is given it is visible on console.

### References

I would be happy to prepare fix for it.

**Comment by patchon** [comment] 2022-03-01 17:11
Took me a couple of hours to get here.
From a personal perspective I think this makes perfect sense. 
If I mark a variable **sensitive = true**, I would expect terraform to mask the input when asking.

**Comment by matthewjdegarmo** [comment] 2022-05-10 18:13
+10000 for this feature.
Would love to see sensitive variables masked when typed in at the console.

**Comment by jhvhs** [comment] 2022-10-05 17:23
Seems like a duplicate of #28122

**Comment by crw** [comment] 2022-10-05 17:42
Agreed, although I am going to retain this issue as I think the description is a bit easier to understand.

**Comment by mbenson** [comment] 2022-12-12 17:41
How is this still open?

**Comment by crw** [comment] 2022-12-16 18:17
Closed by https://github.com/hashicorp/terraform/pull/29520

**Closed by crw** 2022-12-16 18:17 UTC
Labels: enhancement, v1.0
