### ISSUE TITLE
entire zombie deployments can be caused by external failures

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#694] opened 2014-12-18 06:04 UTC
From http://www.terraform.io/docs/internals/lifecycle.html:

> If an error happens at any stage in the lifecycle of a resource, Terraform stores a partial state of the resource. This behavior is critical for Terraform to ensure that you don't end up with any zombie resources: resources that were created by Terraform but no longer managed by Terraform due to a loss of state.

From that I infer that anything that results in a zombie resource is a bug, and I think it's a big one. If Terraform makes resources that it doesn't manage, that could cost me a lot of money and I'd have a bad time with the CFO.

On one of my first runs with Terraform something goofed at AWS, and an EC2 instance that Terraform was creating got stuck in the pending state. Consequently Terraform got stuck waiting for that instance to be created.

Eventually I got bored and gave it a ^C. I got a message along the lines of, "Interrupted. Exiting gracefully". It still didn't exit. Eventually I gave it another ^C which I suspect had about the same effect as a SIGKILL. It exited, but `terraform.tfstate` was not updated, and I was left with an entire zombie cluster of EC2 instances. Fortunately I had the sense to check the web console and terminate them manually, but if I integrate Terraform into an automated deployment pipeline that won't be possible.

Unfortunately I can't repro whatever caused AWS to hang starting my instance, but it's not difficult to create any number of similar situations by introducing any kind of failure as `apply` is underway:
- `iptables -P INPUT DROP`
- SIGKILL the Terraform process
- provoke the OOM killer
- simulate a flaky network with dummynet or similar
- turn off the computer running Terraform

At this point, one might say the bug was that ^C didn't effect a graceful exit. However, I posit that is the _wrong thing_. Looking at the above list, which is only some very small subset of possible failures, only some of them can Terraform act upon. It's impossible to catch a SIGKILL or a power cut or a bug that requires the user to ^C^C the process, so if robustness is the goal, the solution can't be catching failures.

What about updating `terraform.tfstate` transactionally, as the resources are being created? Assume that [the only way for Terraform to terminate is abruptly so](http://lwn.net/Articles/191059/), and be prepared to continue (with correct behavior!) from whatever state that might leave. Since AWS's API isn't itself transactional, it will always be possible that a resource is created but Terraform will never receive the response, however with good design this window can be minimized.

**Comment by armon** [comment] 2015-01-05 19:51
I've spent some time thinking about this problem as well. It is a very nasty problem to say the least. There is a certain class of things we could guard against with transactional state updates (mostly local failures), but most of the resource zombie cases cannot be solved by that. The problem is that TF is operating as part of a larger distributed system that includes the API providers, who themselves often have various consistency bugs as well. Basically we need ALL of the operations TF executions to happen within a transactional block, which for all practical purposes is impossible.

I think the best we can hope to do is to incorporate some type of anti-entropy mechanism that can be used to reconcile the TF state of the world with a providers state. However, even there we don't often have strong enough API support to do this safely. It is very hard for TF to correlate external IDs with it's internal logical IDs, and to separate resources managed by TF from those that are managed externally. Its a tough problem for sure, requires more thought.

My current line of thinking is to try to use idempotent operations where possible (single use tokens with APIs), and simulate that with "tags" or metadata where not directly supported. e.g. each plan file will generate a single use ID. If TF fails mid-plan, we can kick off the anti-entropy and scan for resources matching the token of the failed plan and recover state. Not possible in all cases, but I think it could go far enough.

Still very early stages of my thoughts here...

**Comment by bitglue** [comment] 2015-04-24 19:25
0.4 release post says:

> Continuous state saving. Terraform used to only persist state updates at the end of a Terraform run. If Terraform crashed for any reason before this (computer shut down abruptly, kernel killed it due to memory pressure, etc.), then it would result in a loss of state. Terraform now persists state after every resource change, minimizing the window where state loss can happen.

Also, I haven't encountered this problem in a long while. Let's call it resolved?

**Comment by let4be** [comment] 2016-02-01 22:44
What if ec2 instance is created but connection was terminated before API returned OK?
I was planning to use terraform in automated environment(from code) but looks like i'ts going to cause a  massive zombie apocalypse

**Comment by catsby** [comment] 2016-11-08 16:51
Hello friends – we're going to close this long time issue, please let us know if you still have concerns here.

**Closed by catsby** 2016-11-08 16:51 UTC
Labels: thinking
