### ISSUE TITLE
Can't create routing table with vpc peering connection id

### ISSUE THREAD

**Issue by scalp42** [hashicorp/terraform#2185] opened 2015-06-02 02:39 UTC
Assuming two VPCs peered together (`pcx-e0f00089`):

- 10.69.0.0/16 (vpc1, `peer_vpc_id`, `vpc-3b08a25e`)
- 10.42.0.0/16 (vpc2, `vpc_id`, called `fortytwo`)

```go
resource "aws_vpc_peering_connection" "infra" {
    peer_owner_id = "blabla"
    peer_vpc_id = "vpc-3b08a25e"
    vpc_id = "${aws_vpc.fortytwo.id}"
    tags {
      Name = "VPC1 - fortytwo"
    }
    auto_accept = true
}
```

The following route table will fail:

```go
resource "aws_route_table" "infra_private_0" {
  depends_on = "aws_vpc_peering_connection.infra"
  vpc_id = "${aws_vpc.fortytwo.id}"
  route {
    cidr_block = "10.69.0.0/16"
    vpc_peering_connection_id = "pcx-e0f00089"
  }
}
```

Error:

    aws_route_table.infra_private_0: Error: 1 error(s) occurred:

    * InvalidParameterValue: route table rtb-73011816 and network gateway pcx-e0f00089 belong to different networks

Also, if we try to add the routes by hand, it'll be **removed** by Terraform even with error (which prevents our VPCs to talk to each other on private subnets).

**Comment by mitchellh** [comment] 2015-06-27 04:32
From googling, this appears to be caused by trying to do this route table update prior to both VPCs being connected to an internet gateway. I honestly haven't used this feature of AWS so I have no idea why that is related, but for CloudFormation users AWS support says to add a `depends on` to the routing table to the internet gateway attachments. 

Can you try this, or verify this is the case?

**Comment by catsby** [comment] 2015-11-30 17:01
Hey @scalp42 – I'm going to go ahead and close this now. I attempted to reproduce with this following configuration, but received no errors:

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "default" {
  cidr_block = "10.69.0.0/16"

  tags {
    Name = "tf-test-3519"
  }
}

resource "aws_vpc" "fortytwo" {
  cidr_block = "10.42.0.0/16"

  tags {
    Name = "tf-test-3519"
  }
}

resource "aws_vpc_peering_connection" "foo" {
  vpc_id        = "${aws_vpc.default.id}"
  peer_vpc_id   = "${aws_vpc.fortytwo.id}"
  peer_owner_id = "470663696735"

  tags {
    foo = "bar"
  }

  auto_accept = true
}

resource "aws_route_table" "priv1" {
  vpc_id = "${aws_vpc.fortytwo.id}"

  route {
    cidr_block                = "10.69.0.0/16"
    vpc_peering_connection_id = "${aws_vpc_peering_connection.foo.id}"
  }

  tags {
    Name = "aws_route_table"
  }
}
```

If I'm missing something please let me know!
Thanks

**Closed by catsby** 2015-11-30 17:01 UTC
Labels: bug, provider/aws
