### ISSUE TITLE
TypeList fails to compute value before it's used by another resource 

### ISSUE THREAD

**Issue by oscarDovao** [hashicorp/terraform#23488] opened 2019-11-25 11:26 UTC
### Current Terraform Version

```
Terraform v0.12.16
...
```

### Terraform Configuration Files

```hcl
resource "resource" "foo" {

// parent is a TypeList
  parent {
    property_one = "property_one"
 // parent_id computed
  }
}

// Example 1
resource "child_resource" "foo" {
// also tested this with same result - element(resource.foo.parent, 0).parent_id
  parent_id = resource.foo.parent[0].parent_id

// also tried with depends_on 
//  depends_on = [
//      resource.foo
//  ]

}

// Example 2
resource "child_resource" "foo" {
  count = length(resource.foo.parent)
  parent_id = element(resource.foo.parent, count.index).parent_id
}
...
```

### Expected Behavior

The expectation is that Terraform identifies the dependency between resource and child_resource and computes the value of parent_id before processing the child_resource. 

### Actual Behavior

The dependency is successfully identified only if the block resource.parent exists already. When the resource.parent block is added as the same time as the child_resource, the outcome is the following error:

``` 
// Example 1

Error: Invalid reference

 resource.foo.parent is empty list of object

The given key does not identify an element in this collection value.

// Example 2

Error: "parent_id": required field is not set
...
```

**Comment by jbardin** [comment] 2019-11-25 15:35
Hi @oscarDovao,

This appears to be a problem with a particular provider. If the provider is not communicating that the `parent_id` field is going to be computed, terraform will assume that the configuration value is available for interpolation, in which case it would still be `null` in this example. This provider however also appears to be returning a plan missing the `parent` block entirely, causing the `resource.foo.parent is empty list of object` error you see. 

If you're having an issue with a supported provider, please submit a reproduction case with that provider. If you're developing your own provider, you may be able to get more help in the [the community forum](https://discuss.hashicorp.com/c/terraform-core).

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by jbardin** 2019-11-25 15:35 UTC

**Comment by oscarDovao** [comment] 2019-11-25 17:17
Hi @jbardin,

We are implementing a new component for a official terraform provider (fastly) this is why I can provide you with replication steps.

FYI, the field parent is configured as computed on the resource schema ```Computed:    true,``` and the failure happens before the plan stage, so no plan is shown. Is there anything else we need to do in order to communicate that the property is computed?

Thanks,
