### ISSUE TITLE
Unexpected error for template interpolation with non-required variable 

### ISSUE THREAD

**Issue by markdboyd** [hashicorp/terraform#26714] opened 2020-10-26 21:26 UTC
### Terraform Version

```
Terraform v0.12.12
+ provider.aws v3.9.0
+ provider.null v2.1.2
```

Upgrading to Terraform v.013 did not resolve the issue.

### Terraform Configuration Files

`main.tf`

```
module "module_two" {
  source = "./module_two"

  foo = "value"
}

resource "aws_s3_bucket" "bucket_one" {
  bucket = "my-bucket"
}
```

`module_two/main.tf`

```
variable "foo" {
  type = string
  default = null
}

locals {
  bar = "${var.foo}-random"
}

resource "aws_s3_bucket" "bucket_two" {
  bucket = local.bar
}

```

### Debug Output

https://gist.github.com/markdboyd/637878297460d70ec478e9a85d2ef079

### Expected Behavior

`terraform console` loads without any issue and `terraform import` works without issues

### Actual Behavior

`terraform console` displays this message, but is still functional:

```
Warning: Due to the problems above, some expressions may produce unexpected results.

Error: Invalid template interpolation value

>   on module_two/main.tf line 7, in locals:
   7:   bar = "${var.foo}-random"
    |----------------
    | var.foo is null

The expression result is null. Cannot include a null value in a string
template.
```

I would not expect any error since `var.foo` has a value of `value` that is passed directly into `module_two`. Curiously, if I remove the default value of `null` for the variable definition of `foo`, this error goes away.

`terraform import` displays the same error but is broken as a result.

### Steps to Reproduce

1. `terraform init`
2. `terraform console` OR `terraform import aws_s3_bucket.bucket_one fake-bucket`

### Additional Context

`terraform apply` succeeds without any issues. The issue only appears from `terraform console`/`terraform import` in my testing so far.

**Comment by alisdair** [comment] 2020-10-27 15:03
Thanks for reporting this. I can reproduce with 0.13.4, but the issue is resolved in the 0.14.0 prerelease branch. For more details, see #25890 and #26649.

However, I'm not sure what your goal is with this default value for your variable. If the default value for a variable is invalid, to me that seems like a bug in the module. Perhaps you could take a different approach to work around the bug? For example, using the `?` operator to check for a `null` value, something like:

```hcl
locals {
  bar = var.foo == null ? "unprefixed-random" : "${var.foo}-random"
}
```

**Closed** 2020-10-27 15:03 UTC
Labels: bug, new
