### ISSUE TITLE
the plugin deleted from plugin cache

### ISSUE THREAD

**Issue by txdyzdy** [hashicorp/terraform#29313] opened 2021-08-06 03:43 UTC
### Terraform Version

```
Terraform v0.14.7
```

### Terraform Configuration Files

```terraform
...
```

### Crash Output

![image](https://user-images.githubusercontent.com/10387817/128452025-17b9557c-a20d-4870-a667-c0e26445c5c1.png)

### Steps to Reproduce

1. `terraform init`
2. `rm .terraform/providers/registry.terraform.io/hashicorp/aws/3.53.0/linux_amd64/terraform-provider-aws_v3.53.0_x5`

### Additional Context

We maintain many clusters, so there are many working directories. 

We hope to delete the .terraform directory in the working directory after each execution to free up the space occupied by the provider and get it from the plugin cache the next time. 

When deleting the .terraform directory directly, everything is normal. But when deleting recursively, that is, directly deleting the `.terraform/providers/registry.terraform.io/hashicorp/aws/3.53.0/linux_amd64/terraform-provider-aws_v3.53.0_x5` file, the file in the plugin cache will also be deleted.

**Comment by txdyzdy** [comment] 2021-08-06 03:44
Caching is enabled through environment variables

`TF_PLUGIN_CACHE_DIR=/terraform_file/terraform_plugin_cache`

**Comment by jbardin** [comment] 2021-08-06 13:37
Hi @txdyzdy,

Sorry you are having a problem here. Accessing the internals of the `.terraform` directory directly is not recommended, and what you are doing here is following a symlink from the local directory into the cache directory. Because removing a directory recursively does not descend through symlinks, removing the entire `.terraform` directory leaves the cache files intact.

Since this is working as intended, I'm going to close the issue. If you have more questions, feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!

**Closed by jbardin** 2021-08-06 13:37 UTC
Labels: bug, new

**Comment by txdyzdy** [comment] 2021-08-09 04:30
Thanks, this is very useful for me
