### ISSUE TITLE
should error when -target a non-existing resource

### ISSUE THREAD

**Issue by andyli** [hashicorp/terraform#31294] opened 2022-06-22 08:12 UTC
### Terraform Version

```
% terraform version
Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/random v3.3.1
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
      version = "3.3.1"
    }
  }
}

resource "random_integer" "int" {
    max = 100
    min = 1
}

output "int" {
  value = random_integer.int.result
}

```

### Debug Output

```
% terraform apply -no-color -target random_integer.int_not_exist
...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Full log: https://gist.github.com/andyli/37ba9b4e89ee31c0e2d05cea6df71f7c

### Expected Behavior

`terraform apply` should error when user `-target` a non-existing resource.

### Actual Behavior

`terraform apply` completed with no error.

### Additional Context

From time-to-time, I made typos when using `-target` and I was not aware since there is no error message.

**Comment by jbardin** [comment] 2022-06-22 16:59
Duplicate of #30434

**Closed by jbardin** 2022-06-22 16:59 UTC
Labels: bug, new
