### ISSUE TITLE
Ctrl+C when prompted for blob key during init doesn't shutdown gracefully

### ISSUE THREAD

**Issue by TeamDman** [hashicorp/terraform#27945] opened 2021-02-26 22:24 UTC
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0
```

### Terraform Configuration Files
```terraform
terraform {
  backend "azurerm" {
    resource_group_name  = "redacted"
    storage_account_name = "redacted"
    container_name       = "tfstate"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.48"
    }
  }
}

variable "subscription_ids" {
  type = map(string)
  default = {
    "A"          = "redacted"
    "B"          = "redacted"
    "C" = "redacted"
    "D"    = "redacted"
    "E"       = "redacted"
    "F"       = "redacted"
  }
}

provider "azurerm" {
  features {}
  subscription_id = lookup(
    var.subscription_ids,
    var.subscription_name,
    var.subscription_ids["E"]
  )
}

```

### Debug Output
https://gist.github.com/TeamDman/c91e13c3ddd3aa5ab38ade4a0a56f8af

### Crash Output
https://gist.github.com/TeamDman/eb67f5c1bd12515b2ead47f7ca7a6ce8

### Expected Behavior
graceful shutdown

### Actual Behavior
scary error message
```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.


key
  The blob key.

  Enter a value:  <Ctrl+C>

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x15bfafa]

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Get(0xc0000fc000, 0x4065180, 0xc000810100, 0x2aedf82)
        /home/circleci/project/project/backend/remote-state/azure/client.go:42 +0x17a
github.com/hashicorp/terraform/states/remote.(*State).refreshState(0xc0000a6a20, 0x7, 0x0)
        /home/circleci/project/project/states/remote/state.go:111 +0x3f
github.com/hashicorp/terraform/states/remote.(*State).RefreshState(0xc0000a6a20, 0x0, 0x0)
        /home/circleci/project/project/states/remote/state.go:104 +0x73
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0007601c0, 0xc00007c060, 0x2, 0x2, 0xc0001ade90)
        /home/circleci/project/project/command/init.go:285 +0x12af
github.com/mitchellh/cli.(*CLI).Run(0xc00046d900, 0xc00046d900, 0xc00031fd48, 0x1)
        /go/pkg/mod/github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x1cf
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:304 +0xe85
main.realMain(0x0)
        /home/circleci/project/project/main.go:106 +0xf1
main.main()
        /home/circleci/project/project/main.go:42 +0x45



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce
1. terraform init
2. get prompted for blob key
3. press ctrl+c
4. ungraceful shutdown occurs

### Additional Context

passing in backend options via cli

### References

my quick search revealed no existing issues for this

**Comment by TeamDman** [comment] 2021-02-26 22:46
```powershell
terraform init -backend-config="client_id=""$env:ARM_CLIENT_ID" -backend-config="client_secret=""$env:ARM_CLIENT_SECRET" -backend-config="tenant_id=""$env:ARM_CLIENT_TENANT" -backend-config="key=""test.tfstate""";
```

Looks like I botched the escaping in my init script. I'm missing a bunch of quotes

fixed:
```powershell
terraform init -backend="true" -backend-config="client_id=""$env:ARM_CLIENT_ID""" -backend-config="client_secret=""$env:ARM_CLIENT_SECRET""" -backend-config="tenant_id=""$env:ARM_CLIENT_TENANT""" -backend-config="key=""form-new-resource-group-${env:request_id}""";
```

Likely caused the tfstate to get messed up?

**Comment by jbardin** [comment] 2021-03-01 13:25
Duplicate of #26702

**Closed by jbardin** 2021-03-01 13:25 UTC
Labels: backend/azure, bug, new
