### ISSUE TITLE
Crash report, probably due to aws_route with nat_gateway_id and count

### ISSUE THREAD

**Issue by misham** [hashicorp/terraform#11190] opened 2017-01-13 04:54 UTC
## Short Summary

Seems that using `aws_route` resource with multiple `nat_gateway_id`'s does not work.  Not sure if it's the `count` variable or the fact that it's interpolation with `nat_gateway_id` part though.

### Terraform Version
0.8.4

### Affected Resource(s)
- aws_route
- aws_nat_gateway

Seems like this is due to multiple resources

### Terraform Configuration Files
```hcl
variable "cidr" {
    default = "10.0.0.0/24"
}

variable "availability_zones" {
    type = "list"
    default = [
        "us-west-2a",
        "us-west-2b"
    ]
}

variable "app_subnets" {
    type = "list"
    default = [
        "10.0.0.0/29",
        "10.0.0.8/29"
    ]
}

variable "nat_subnets" {
    type = "list"
    default = [
        "10.0.0.16/29",
        "10.0.0.32/29"
    ]
}

resource "aws_vpc" "main" {
    cidr_block = "${var.cidr}"
    enable_dns_support = true
    enable_dns_hostnames = true
}

resource "aws_internet_gateway" "ig" {
  vpc_id = "${aws_vpc.main.id}"
}

resource "aws_eip" "nat" {
    count = "${length(var.nat_subnets)}"

    vpc = "${aws_vpc.main.id}"
}

resource "aws_nat_gateway" "nat" {
    count = "${length(var.nat_subnets)}"

    allocation_id = "${aws_eip.nat.*.id[count.index]}"
    subnet_id = "${aws_subnet.nat.*.id[count.index]}"

    depends_on = ["aws_internet_gateway.ig"]
}

resource "aws_subnet" "app" {
    count = "${length(var.app_subnets)}"

    vpc_id = "${aws_vpc.main.id}"
    availability_zone = "${var.availability_zones[count.index]}"
    cidr_block = "${var.app_subnets[count.index]}"
    map_public_ip_on_launch = false
}

resource "aws_route" "nat" {
    count = "${var.nat_subnets}"

    route_table_id = "${aws_route_table.app.id}"
    destination_cidr_block = "0.0.0.0/0"
    nat_gateway_id = "${aws_nat_gateway.nat.*.id[count.index]}"
}

resource "aws_route_table_association" "app" {
    count = "${length(var.app_subnets)}"

    subnet_id = "${aws_subnet.app.*.id[count.index]}"
    route_table_id = "${aws_route_table.app.id}"
}
```

### Debug Output
https://gist.github.com/misham/f3f164bffa73cdffaa9340d5fe50c740

### Panic Output
https://gist.github.com/misham/dfc6d2c0dac92ecb3d790dbc90aa8d4a

### Expected Behavior
`terraform plan` should have worked and not crashed

### Actual Behavior
`terraform plan` crashed

### Steps to Reproduce
`terraform plan`

### Important Factoids
N/A

### References
N/A

**Comment by misham** [comment] 2017-01-13 17:02
Hi @jbardin,

Yes, same exact result.  Let me know if want output from that run as well.

**Comment by jbardin** [comment] 2017-01-13 18:43
Thanks @misham,

I was looking in the wrong place. The problem is simply `count = "${var.nat_subnets}"`, where you are assigning a list to a `count`.

This is a bug, and a dupe of #11124

Thanks!

**Closed by jbardin** 2017-01-13 18:43 UTC
Labels: bug, core, crash

**Comment by misham** [comment] 2017-01-13 19:51
Doh, thank you for catching that!
