### ISSUE TITLE
Validation condition of a variable based on another variable

### ISSUE THREAD

**Issue by sankara911** [hashicorp/terraform#33632] opened 2023-08-04 07:23 UTC
### Terraform Version

```shell
terraform version
Terraform v1.3.2
on darwin_arm64
```

### Use Cases

Validation of a variable based on another variable.
Currently, while declaring a variable there is a 
```

variable "somevar"{
type=string
default=""

validation {
condition = var.somevar == "" || var.somevar == "hello"
error = "variable should be either null or hello"
}

```
But, if I use that validation to check another variable as below,
```

variable "somevar"{
type=string
default=""

validation {
condition = var.somevar == "" || var.someothervar == "hello"
error = "variable should be either null or hello"
}
```

I get the error - 

The condition for variable "somevar" can only refer to the variable
│ itself, using var.somevar.

---------------------------------------------

Would be a good addition to enable such a feature.

### Attempted Solutions

But, if I use that validation to check another variable as below,

```
variable "somevar"{
type=string
default=""

validation {
condition = var.somevar == "" || var.someothervar == "hello"
error = "variable should be either null or hello"
}
```

I get the error - 

The condition for variable "somevar" can only refer to the variable
│ itself, using var.somevar

### Proposal

Proposing that a condition in a validation block be allowed to check the validation for another variable and set this one accordingly.

**Comment by jbardin** [comment] 2023-08-04 13:05
Hi @sankara911,

While this is a duplicate of #25609, the overall functionality of validation multiple variables in a single expression can be done with [`check` blocks](https://developer.hashicorp.com/terraform/language/checks).

Thanks!

**Closed by jbardin** 2023-08-04 13:05 UTC
Labels: enhancement, new

**Comment by briceburg** [comment] 2023-08-17 04:42
@jbardin AFAIK the terraform 1.5 `check` blocks are essentially post-apply/postcondition validation, whereas input validation is typically a pre-apply/pre-condition step. is there a way to have `check` blocks fire _before_ a resource attempts application?
