### ISSUE TITLE
Terraform crash initial apply7

### ISSUE THREAD

**Issue by stefano-di-chio** [hashicorp/terraform#34059] opened 2023-10-11 07:51 UTC
### Terraform Version

```shell
Terraform v1.6.0
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.10.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/netascode/utils v0.2.5
```

### Terraform Configuration Files

```terraform
...terraform config...

erraform {
  required_providers {
    aci = {
      source = "CiscoDevNet/aci"
    }
  }
}

provider "aci" {
  username = "admin"
  password = "R0llingStone"
  url      = "https://acilab01"
}

module "aci" {
  source  = "netascode/nac-aci/aci"
  version = "0.7.0"

  yaml_directories = ["data"]

  manage_access_policies    = false
  manage_fabric_policies    = false
  manage_pod_policies       = false
  manage_node_policies      = false
  manage_interface_policies = false
  manage_tenants            = true
}

```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 4662 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2b92ec0?, 0x38c4c30?})
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.AsString({{{0x3902720?, 0xc000012c51?}}, {0x2e1de40?, 0xc0059e6ca8?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_ops.go:1385 +0x47
github.com/zclconf/go-cty/cty.Value.Range({{{0x3902720?, 0xc000012c51?}}, {0x2e1de40?, 0xc0059e6ca8?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_range.go:53 +0x285
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc002402a80, 0xc005756138)
        /home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:745 +0xd35
github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0xc002409540, 0xc005756138)
        /home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:1082 +0x27e
github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc00569ed20, 0xc004520cf8?, {0xc001c5c048?, 0x5?, 0xc002414d00?}, 0xc005756138)
        /home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/spec.go:214 +0x1f5
github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc00569ecf0, 0xc00569ecf0?, {0x0, 0x0, 0x0}, 0xc003016480?)
        /home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/spec.go:88 +0x1f7
github.com/hashicorp/hcl/v2/hcldec.decode({0x3903ae0, 0xc001c6fde0}, {0x0, 0x0, 0x0}, 0x0?, {0x3902fb8, 0xc00569ecf0}, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/decode.go:24 +0x10f
github.com/hashicorp/hcl/v2/hcldec.Decode(...)
        /home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hcldec/public.go:18
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalBlock(0xc00573c240, {0x3903530, 0xc00571db60}, 0xc004521178?)
        /home/runner/work/terraform/terraform/internal/lang/eval.go:71 +0x1ea
github.com/hashicorp/terraform/internal/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc001c68930?, {0x3902d18, 0xc0024128f0}, 0xc001278a80?, {0x0?, 0x0?}, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...})
        /home/runner/work/terraform/terraform/internal/terraform/eval_context_builtin.go:282 +0x145
github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).validateResource(0xc002d26f50, {0x391fb60, 0xc003f46e00})
        /home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:372 +0x666
github.com/hashicorp/terraform/internal/terraform.(*NodeValidatableResource).Execute(0xc002d26f50, {0x391fb60, 0xc003f46e00}, 0x1?)
        /home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:52 +0x55
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0029caa20, {0x391fb60, 0xc003f46e00}, {0x7fba33ff15d8, 0xc002d26f50})
        /home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x30d81c0, 0xc002d26f50})
        /home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc002d01200, {0x30d81c0, 0xc002d26f50}, 0xc001cbb3c0)
        /home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 49
        /home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8

### Expected Behavior

    Apply complete! Resources: 20 added, 0 changed, 0 destroyed.

### Actual Behavior

Terraform Crash

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by liamcervante** [comment] 2023-10-11 09:31
Duplicate of https://github.com/hashicorp/terraform/issues/33977

@stefano-di-chio, if you upgrade to `v1.6.1` this should be fixed for you. Feel free to reopen this ticket, or file a new one, if you are still encountering the crash after upgrading.

Thanks!

**Closed** 2023-10-11 09:35 UTC
Labels: bug, new, duplicate
