### ISSUE TITLE
aws_s3_bucket_object still cannot detect the changes in the source file

### ISSUE THREAD

**Issue by dsantanu** [hashicorp/terraform#27649] opened 2021-02-01 14:48 UTC
Hi there,
I'm running TF v013 and I see `aws_s3_bucket_object` still cannot detect the changes in the file when supplied via `source` parameter. It's an encrypted bucket, hence cannot use `etag` as it clashed with `kms_key_id`. So as a result, say if I change the passphrase of the ssh-key, it fails to detect the changes in the private-key and doesn't upload the new version to S3. any thing I'm missing here?

I looked at #3068 but couldn't figured out what actually was fixed.

### Terraform Version
```
Terraform v0.13.6
```

### Terraform Configuration Files

```terraform
resource "aws_s3_bucket_object" "ssh_keys" {
  for_each   = toset(["pem", "pub"])
  bucket     = local.s3_bucket_names[var.s3_keys_bucket].id
  key        = "access_keys/${local.ssh_key_name}.${each.value}"
  source     = "${local.ssh_key_file}.${each.value}"
  kms_key_id = data.aws_kms_alias.s3_platform_key.target_key_arn
  depends_on = [module.s3_create_buckets]
}
```
### Expected Behavior
Should detect the changes in the content, when file file name is unchanged and update accordingly

### Actual Behavior
Doesn't detect the changes

### References
- #3068

**Comment by apparentlymart** [comment] 2021-02-01 17:56
Hi @dsantanu,

This repository is about Terraform Core/CLI rather than about the AWS provider, so unfortunately there's nothing we could change in this repository to improve the situation you've described here.

With that said, based on my own experiences with the AWS provider (as you saw, back in 2015 we were maintaining it here as part of Terraform) I believe what you've seen here is the provider working as designed: when you tell the provider to refer to a file by name, the provider detects changes based on the filename rather than the contents. It seems like hashicorp/terraform-provider-aws#6668 is the current AWS provider issue related to detecting changes in external files, which is discussing a design approach of introducing a separate hash argument so the provider can see when the file has changed without reading the file itself. If that doesn't seem like it would meet your use-case then you could [open a new feature request in the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws/issues/new?assignees=&labels=enhancement&template=Feature_Request.md).

I'm going to close this issue just because there's nothing we could change in this codebase that would change the behavior you saw here, and so any changes would need to happen in the AWS provider repository instead. Thanks!

**Closed by apparentlymart** 2021-02-01 17:56 UTC
Labels: bug, provider/aws
