### ISSUE TITLE
0.12.0-alpha4 crash in plan diff printer

### ISSUE THREAD

**Issue by querry43** [hashicorp/terraform#19998] opened 2019-01-14 19:48 UTC
### Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
+ provider.aws v1.40.0-6-gb23683732-dev
```

### Terraform Configuration Files

https://github.com/querry43/terraform

### Crash Output

https://gist.github.com/querry43/cc0b63e82ea015b08aff4864329fe04f

### Expected Behavior

It should not crash

### Actual Behavior

It crashed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by apparentlymart** [comment] 2019-01-14 21:52
Thanks for reporting this, @querry43.

```
panic: interface conversion: interface {} is *cty.unknownType, not bool

goroutine 40 [running]:
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty.Value.True(0x38cc820, 0xc0000ae501, 0x2d3a1c0, 0x63ba740, 0x38cc920)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/value_ops.go:297 +0x115
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeNestedBlockDiffs(0xc00133f780, 0xc000215090, 0x10, 0xc0007f72f0, 0x38cc960, 0xc000b56780, 0x343f800, 0xc00109c2a0, 0x38cc960, 0xc000b563e0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:371 +0x1667
github.com/hashicorp/terraform/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc00133f780, 0xc0007ea370, 0x38cc920, 0xc001132c78, 0x2cfa3a0, 0xc001f8c6c0, 0x38cc920, 0xc001132c88, 0x2cfa3a0, 0xc001f8d830, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:195 +0xa26
github.com/hashicorp/terraform/command/format.ResourceChange(0xc000b92800, 0xc0007ea370, 0xc00031cde0, 0xc, 0xc00051a6f8)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format/diff.go:125 +0x52b
github.com/hashicorp/terraform/backend/local.(*Local).renderPlan(0xc000387860, 0xc00032b650, 0xc00023c0c0)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:254 +0x5ba
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc000387860, 0x38cae60, 0xc00030e040, 0x38cae60, 0xc00030e080, 0xc000366380, 0xc00030e000)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_apply.go:111 +0x118b
github.com/hashicorp/terraform/backend/local.(*Local).opApply-fm(0x38cae60, 0xc00030e040, 0x38cae60, 0xc00030e080, 0xc000366380, 0xc00030e000)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:306 +0x66
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc000240520, 0xc000240530, 0xc000240540, 0xc000366380, 0xc000387860, 0xc00030e000, 0xc000240510, 0x38cae60, 0xc00030e040, 0x38cae60, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:357 +0x135
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:341 +0x362
```

Based on the backtrace here, it seems like this is an issue in the diff printer when Terraform is trying render the changeset for approval. Specifically, it seems like the renderer is not correctly handling an unknown boolean value somewhere. We'll take a look at this before final release and get it fixed.

**Comment by radeksimko** [comment] 2019-01-18 13:03
I can confirm this is triggered by unknown `(known after apply)` elements in a set. I managed to reproduce the crash with the following simple set:

```go
			Before: cty.ObjectVal(map[string]cty.Value{
				"id":  cty.StringVal("i-02ae66f368e8518a9"),
				"ami": cty.StringVal("ami-STATIC"),
				"set_field": cty.SetVal([]cty.Value{
					cty.StringVal("aaaa"),
					cty.StringVal("bbbb"),
				}),
			}),
			After: cty.ObjectVal(map[string]cty.Value{
				"id":  cty.UnknownVal(cty.String),
				"ami": cty.StringVal("ami-STATIC"),
				"set_field": cty.SetVal([]cty.Value{
					cty.StringVal("aaaa"),
					cty.UnknownVal(cty.String),
				}),
			}),
```
I will look into a patch and also try adding more tests around unknown values for other types.

**Comment by querry43** [comment] 2019-02-02 21:20
@radeksimko , I am still seeing this on head.

```
matt@v1:~/work/underdogma-terraform$ terraform --version
Terraform v0.12.0-dev
+ provider.aws (unversioned)
```

Terraform:
```
commit d1daa7e5187d0120620f260ec1aed9631b77f6f8 (HEAD -> master, origin/master, origin/HEAD)
Author: Nick Fagerlund <nick.fagerlund@gmail.com>
Date:   Fri Jan 18 18:21:30 2019 -0800

    website: Make 0.11 and 0.12 subsections of 'Configuration Language'
```

AWS:
```
commit 4479658179f30b33b865aea17cf510d633fb4b07 (HEAD -> v0.12-sdk-updates-411dab1dea1a, origin/v0.12-sdk-updates-411dab1dea1a)
Author: Brian Flad <bflad417@gmail.com>
Date:   Thu Jan 31 20:05:07 2019 -0500

    deps: Update github.com/hashicorp/terraform@411dab1dea1a

    ```
    go get github.com/hashicorp/terraform@411dab1dea1a
    go mod tidy
    go mod vendor
    ```
```

**Comment by apparentlymart** [comment] 2019-03-19 23:14
Hi @radeksimko,

We made a few changes in this area just before releasing v0.12.0-beta1. Do you still have the crash-reproducing test you mentioned here, so we can verify whether this is now fixed? Thanks!

**Comment by querry43** [comment] 2019-03-20 04:53
@apparentlymart , I confirm that the diff painter fully prints out the diff and I get the confirmation prompt without error.  The diff itself doesn't look crazy (aside from some data type changes), but I don't currently have an environment where I can safely apply.

**Comment by apparentlymart** [comment] 2019-03-20 19:24
Thanks for checking, @querry43!

Indeed a full apply is not necessary here because the place this was failing was inside the diff _renderer_, and so if there were any follow-on errors during apply they'd be separate issues anyway.

I'm going to close this out, then. If others find different crashers during plan rendering (or indeed, any other weird behaviors), please open fresh issues for them since that way we can track and verify each one separately.

**Closed by apparentlymart** 2019-03-20 19:24 UTC
Labels: bug, cli, crash
