### ISSUE TITLE
Terraform crashed

### ISSUE THREAD

**Issue by guleriagishere** [hashicorp/terraform#24011] opened 2020-02-01 20:47 UTC
Terraform latest version 12.20 and 0.12.18 crashes when using terraform apply or plan command On MacOS.

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.47.0
+ provider.null v2.1.2
```

### Crash Output

2020/02/02 02:10:32 [INFO] Terraform version: 0.12.20
2020/02/02 02:10:32 [INFO] Go runtime version: go1.12.13
2020/02/02 02:10:32 [INFO] CLI args: []string{"/Users/engy/.terraform/terraform", "plan"}
2020/02/02 02:10:32 [DEBUG] Attempting to open CLI config file: /Users/engy/.terraformrc
2020/02/02 02:10:32 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/02/02 02:10:32 [INFO] CLI command args: []string{"plan"}
2020/02/02 02:10:32 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/02/02 02:10:32 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/02/02 02:10:32 [DEBUG] New state was assigned lineage "1809e079-0d57-cefc-d3db-48f8f106e4e4"
2020/02/02 02:10:32 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/02/02 02:10:32 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/02/02 02:10:32 [DEBUG] checking for provider in "."
2020/02/02 02:10:32 [DEBUG] checking for provider in "/Users/engy/.terraform"
2020/02/02 02:10:32 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/02/02 02:10:32 [DEBUG] found provider "terraform-provider-aws_v2.47.0_x4"
2020/02/02 02:10:32 [DEBUG] found provider "terraform-provider-null_v2.1.2_x4"
2020/02/02 02:10:32 [DEBUG] found valid plugin: "aws", "2.47.0", "/Users/engy/OneDrive - DebYum/TMP/terraform-01-27-2020/dev/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.47.0_x4"
2020/02/02 02:10:32 [DEBUG] found valid plugin: "null", "2.1.2", "/Users/engy/OneDrive - DebYum/TMP/terraform-01-27-2020/dev/.terraform/plugins/darwin_amd64/terraform-provider-null_v2.1.2_x4"
2020/02/02 02:10:32 [DEBUG] checking for provisioner in "."
2020/02/02 02:10:32 [DEBUG] checking for provisioner in "/Users/engy/.terraform"
2020/02/02 02:10:32 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2020/02/02 02:10:32 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/hcl/v2/json.(*peeker).Read(...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/peeker.go:20
github.com/hashicorp/hcl/v2/json.parseObject.func1(0x0, 0xc000233a3c, 0x1, 0x390, 0x2a16120, 0x15, 0x89, 0x9, 0x1a3c, 0x89, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:127 +0xb0
github.com/hashicorp/hcl/v2/json.parseObject(0xc000491800, 0xc00015c240, 0xc000421180, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:233 +0xcb2
github.com/hashicorp/hcl/v2/json.parseValue(0xc000491800, 0xc00015c1e0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseObject(0xc000491800, 0xc00015aea0, 0x2a16120, 0x15, 0x87, 0x2b)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:188 +0x43c
github.com/hashicorp/hcl/v2/json.parseValue(0xc000491800, 0xc000491800, 0x3a5, 0x2a16120, 0x15, 0x89)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:45 +0x70b
github.com/hashicorp/hcl/v2/json.parseFileContent(0xc000232000, 0x1bcc, 0x1dcc, 0x2a16120, 0x15, 0x1013c97, 0xc0004c6600, 0x18, 0x100, 0xc0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/parser.go:21 +0x155
github.com/hashicorp/hcl/v2/json.Parse(0xc000232000, 0x1bcc, 0x1dcc, 0x2a16120, 0x15, 0x0, 0x0, 0x6000104, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/json/public.go:21 +0x77
github.com/hashicorp/terraform/command.(*Meta).addVarsFromFile(0xc0004621a0, 0x2a16120, 0x15, 0xc000000046, 0xc0000e8810, 0x0, 0x1, 0x10088a9)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/meta_vars.go:158 +0x5ee
github.com/hashicorp/terraform/command.(*Meta).collectVariableValues(0xc0004621a0, 0xc0001e00a0, 0x0, 0x0, 0xc000531ba0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/meta_vars.go:70 +0xad4
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc0004621a0, 0xc0000b2010, 0x0, 0x0, 0xc0000b56c0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/plan.go:111 +0xc8f
github.com/mitchellh/cli.(*CLI).Run(0xc000104640, 0xc000104640, 0xc00052fd90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:239 +0xc33
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:103 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:39 +0x3b
### Steps to Reproduce
1. terraform init
2. terraform apply
 or 
2. terraform plan

### Additional Context
default setup on macOS

**Comment by teamterraform** [comment] 2020-02-03 22:36
This appears to be a duplicate of #23964

**Closed by teamterraform** 2020-02-03 22:36 UTC
Labels: bug, crash
