### ISSUE TITLE
Terraform Crashed

### ISSUE THREAD

**Issue by Khuzaima05** [hashicorp/terraform#34360] opened 2023-12-05 18:27 UTC
### Terraform Version

```shell
Terraform 1.6.0
```

### Terraform Configuration Files

```terraform
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object 
goroutine 3412 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
[github.com/hashicorp/terraform/internal/logging.PanicHandler()](http://github.com/hashicorp/terraform/internal/logging.PanicHandler())
	/home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2b92ec0?, 0xc002c0ee60?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
[github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult](http://github.com/hashicorp/terraform/internal/checks.(*State).reportCheckResult)(0xc0021af968, {0x39073f0, 0xc002d9f3b0}, 0xc0011e4400?, 0x0, 0x50)
	/home/runner/work/terraform/terraform/internal/checks/state_report.go:106 +0x345
[github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult](http://github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckResult)(0x2fcbc00?, {0x39073f0?, 0xc002d9f3b0?}, 0xc00152f6a8?, 0x1?, 0x1?)
	/home/runner/work/terraform/terraform/internal/checks/state_report.go:71 +0xc5
[github.com/hashicorp/terraform/internal/terraform.evalVariableValidations](http://github.com/hashicorp/terraform/internal/terraform.evalVariableValidations)({{0xc001354c80, 0x1, 0x1}, {{}, {0xc00087ecd0, 0x10}}}, 0xc0009b0270, {0x0, 0x0}, {0x391fb60, ...})
	/home/runner/work/terraform/terraform/internal/terraform/eval_variable.go:252 +0xb52
[github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute](http://github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute)(0xc0009b4840, {0x391fb60, 0xc000d5f5e0}, 0x5)
	/home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:198 +0x3f1
[github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute](http://github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute)(0xc003082480, {0x391fb60, 0xc000d5f5e0}, {0x7fc7fad5c138, 0xc0009b4840})
	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
[github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1](http://github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1)({0x2f07ca0, 0xc0009b4840})
	/home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
[github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex](http://github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex)(0xc0009b4960, {0x2f07ca0, 0xc0009b4840}, 0xc001c06b00)
	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by [github.com/hashicorp/terraform/internal/dag.(*Walker).Update](http://github.com/hashicorp/terraform/internal/dag.(*Walker).Update) in goroutine 3374
	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8}
```

### Debug Output

it is not recognized in it

### Expected Behavior

Terraform init and Terraform plan was to be executed

### Actual Behavior

terraform is getting crashed.

### Steps to Reproduce

Terraform init
Terraform plan

**Comment by jbardin** [comment] 2023-12-05 22:53
Duplicate of #34052

**Closed by jbardin** 2023-12-05 22:53 UTC
Labels: bug, new
