### ISSUE TITLE
`terraform output` writes error to stdout

### ISSUE THREAD

**Issue by pallxk** [hashicorp/terraform#26991] opened 2020-11-20 07:29 UTC
### Terraform Version

```
Terraform v0.13.5
```

This appies to both v0.13 and v0.14-rc1.

### Terraform Configuration Files

No configuration files needed.

### Output in v0.13 & v0.14-rc1

```
$ terraform version
Terraform v0.13.5

$ terraform output a

Warning: No outputs found

The state file either has no outputs defined, or all the defined outputs are
empty. Please define an output in your configuration with the `output` keyword
and run `terraform refresh` for it to become available. If you are using
interpolation, please verify the interpolated value is not empty. You can use
the `terraform console` command to assist.


$ terraform output a 2> /dev/null

Warning: No outputs found

The state file either has no outputs defined, or all the defined outputs are
empty. Please define an output in your configuration with the `output` keyword
and run `terraform refresh` for it to become available. If you are using
interpolation, please verify the interpolated value is not empty. You can use
the `terraform console` command to assist.

```

### Output in v0.12

```
$ terraform version
Terraform v0.12.29

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html

$ terraform output a
The state file either has no outputs defined, or all the defined
outputs are empty. Please define an output in your configuration
with the `output` keyword and run `terraform refresh` for it to
become available. If you are using interpolation, please verify
the interpolated value is not empty. You can use the
`terraform console` command to assist.

$ terraform output a 2> /dev/null
```

### Expected Behavior

Error should be written to stderr, while output to stdout.

### Actual Behavior

Both error and output are written to stdout since v0.13.

### Steps to Reproduce

Run `terraform output a`.

`a` can be any undefined variable.

**Comment by pallxk** [comment] 2020-11-20 07:37
By the way, I think it'd be better if return code could be non-zero when there is an error for `terraform output`.

**Comment by alisdair** [comment] 2020-11-20 15:07
Thanks for reporting this. This behaviour of the `output` subcommand has a bit of history. See these related issues:

- Issue #18975: `terraform output` should not error when no outputs defined
- PR #23008: fix the above issue by setting the exit code to 0 when there are no outputs
- Issue #25956: `terraform output` should not display an error and exit successfully
- PR #26036: correct the diagnostic to be a warning, as intended, so that it lines up with the 0 exit code

In Terraform, warnings are not errors, and are intentionally printed on `stdout`. The messages you're referring to in your issue are considered warnings, so they should not be written to `stderr`.

Some more detail on our thinking here, [from my previous comment](https://github.com/hashicorp/terraform/issues/25956#issuecomment-681990064):

At present, running `terraform output` with an empty state file only reports a UI-level error (rather than a shell error exit code) because it's also valid for a configuration to have no outputs. It's like running `ls` in an empty directory.

Two notes that may be helpful to future people finding this issue and looking for workarounds:

- For automation and scripting, it might be better to use the `-json` flag to Terraform subcommands where possible. At the moment, the `output` subcommand does error on missing state file if you are looking for a specific output **and** you're using JSON output. Example:

    ```shellsession
    $ terraform output nonsense 2>/dev/null || echo error
    $ terraform output -json nonsense 2>/dev/null || echo error
    error
    ```

    The `-json` flag is intended for automation workflows such as the one you're building.

- Alternatively, the `state list` subcommand will error on missing state file, which you could use as a check to see if the state file is present:

    ```shellsession
    $ terraform state list >/dev/null 2>&1 || echo error
    error
    ```

I'm closing this issue as Terraform is working as designed here. If you think there's something I've missed, please let me know—we can always reopen it if there is something not addressed by the above comment. Thanks!

**Closed by alisdair** 2020-11-20 15:07 UTC
Labels: bug, new
