### ISSUE TITLE
Terraform 1.6.0 crash through GitHub Actions

### ISSUE THREAD

**Issue by dms1981** [hashicorp/terraform#33988] opened 2023-10-05 10:39 UTC
### Terraform Version

```shell
1.6.0
```

### Terraform Configuration Files

https://github.com/ministryofjustice/modernisation-platform/tree/refactor/data-platform-apps-and-tools-vpc/terraform/environments/data-platform-apps-and-tools

### Debug Output

https://gist.github.com/dms1981/1b3adb300817fb7fa8fa67b9f933898b

### Expected Behavior

Terraform should complete a `plan` successfully. Running a `plan` with the Terraform version pinned to `1.5.7` completes successfully

### Actual Behavior

Terraform crashes.

### Steps to Reproduce

Code committed to [branch](https://github.com/ministryofjustice/modernisation-platform/tree/refactor/data-platform-apps-and-tools-vpc) on GitHub.
[GitHub Action](https://github.com/ministryofjustice/modernisation-platform/actions/runs/6416996394/workflow?pr=4992) picks up change and runs Terraform through the following approximate steps:

1. `terraform init`
2. `terraform workspace select name-of-workspace`
3. `terraform plan`

### Additional Context

As noted, this code is successfully planned and applied with a version constraint of `1.5.7`. A full `TF_LOG=trace` can be supplied on request.

**Comment by kmoe** [comment] 2023-10-05 11:03
Duplicate of https://github.com/hashicorp/terraform/issues/33977

**Closed by kmoe** 2023-10-05 11:03 UTC
Labels: bug, new
