### ISSUE TITLE
Terraform import azurerm_linux_virtual_machine failed due to platform_fault_domain set to -1

### ISSUE THREAD

**Issue by GTRekter** [hashicorp/terraform#33428] opened 2023-06-24 11:49 UTC
### Terraform Version

```shell
Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.61.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.61.0"
    }
  }
}
provider "azurerm" {
  features {}
}
import {
  id = "/subscriptions/<subscription-id>/resourceGroups/rg-training-swarm-uks-01/providers/Microsoft.Compute/virtualMachines/vm-uks-01"
  to = azurerm_linux_virtual_machine.vm-uks-01
}
```

### Debug Output

https://gist.github.com/GTRekter/36b947494b171b82e97430860e5d50df

### Expected Behavior

When I execute the command `terraform plan -generate-config-out new.tf` I expected the tool to generate a file called new.tf with the configuration o a linux virtual machine.

### Actual Behavior

the generation process fails with the following error:
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Warning: Config generation is experimental
│ 
│ Generating configuration during import is currently experimental, and the
│ generated configuration format may change in future versions.
╵
╷
│ Error: Missing required argument
│ 
│   with azurerm_linux_virtual_machine.vm-uks-01,
│   on new.tf line 22:
│   (source code not available)
│ 
│ "platform_fault_domain": all of
│ `platform_fault_domain,virtual_machine_scale_set_id` must be specified
╵

```

### Steps to Reproduce

```
terraform plan -generate-config-out new.tf
```

### Additional Context

The issue is related to the already know platform_fault_domain default value (-1). In this case, the entire generation is failing because of the default value being set to `-1` instead of `null`

### References

- https://github.com/hashicorp/terraform/issues/30622

**Comment by crw** [comment] 2023-06-27 20:53
Thanks for filing this issue! This may be due to a lack of support in the AzureRM provider. I'll raise in triage to see if it is an bug in the experimental import feature. Thanks!

**Comment by crw** [comment] 2023-06-27 20:56
It may also be a dupe of this issue? https://github.com/hashicorp/terraform/issues/33392 -- let me know if this helps.

**Comment by jbardin** [comment] 2023-06-28 14:19
I think we're going to get a lot of variations on this same theme, so I opened issue #33438 as a placeholder to reference while we work on future improvements to the config generation.

**Closed by jbardin** 2023-06-28 14:19 UTC
Labels: bug, new, plannable-import
