### ISSUE TITLE
Terraform login fails with Okta and AWS Cognito Oauth2 services

### ISSUE THREAD

**Issue by mmmorris1975** [hashicorp/terraform#24849] opened 2020-05-04 19:31 UTC
### Terraform Version
```
Terraform v0.12.23
```

### Terraform Configuration Files
N/A

### Debug Output
https://gist.github.com/mmmorris1975/a8e3af4c99830470ee96abfb4197d2cf

### Crash Output
N/A

### Expected Behavior
Terraform login should successfully authenticate to the external Oauth2 endpoints

### Actual Behavior
`terraform login` fails due to PKCE verification issues

### Steps to Reproduce
`terraform login` against an Okta or AWS Cognito (and others?) Oauth2 endpoint

### Additional Context
Poking around in the source code, this failure appears to happen because the base64 encoding is "standard" URL encoding.  Changing this value use `base64.RawURLEncoding` instead gets this to work.  Verified the issue and fix on 0.13 (master) and 0.12 branches.

An additional note about Okta is that it expects a minimum 43 character long string for the key, as required by [RFC 7636 section 4.1](https://tools.ietf.org/html/rfc7636#section-4.1).  The generated UUID value is 36.  Padding out the UUID used for the key with some extra string data gets past this issue. (REF: https://developer.okta.com/docs/guides/implement-auth-code-pkce/use-flow/)

### References
None

**Comment by danieldreier** [comment] 2020-05-04 22:51
@mmmorris1975 thanks for such a detailed error report! This is great. You said you've confirmed the fix against 0.13 - are you willing to make a PR to fix this?

**Comment by mmmorris1975** [comment] 2020-05-05 00:04
Absolutely! #24858 is for a merge to master (0.13).  The exact same fix works for 0.12, and I can throw together a PR for that branch too

**Comment by danieldreier** [comment] 2020-05-05 01:09
@mmmorris1975 I'm inclined to just target 0.13 for this but if this is causing a big problem for you we could target the fix for 0.12.25 as well. If so, please just open another PR at that branch.

**Comment by mmmorris1975** [comment] 2020-05-05 01:54
So far I don't see anything that makes me feel like 0.13 is going to introduce the kinds of changes that 0.12 did.  I should be OK with targeting 0.13 for now.  If that changes, I can always whip up another PR targeting 0.12.

**Comment by danieldreier** [comment] 2020-05-08 01:39
Awesome! I'm so happy you fixed this. I'm going to close this because #24858 was merged into master.

**Closed by danieldreier** 2020-05-08 01:39 UTC
Labels: bug, cli, v0.12
