### ISSUE TITLE
[Aws] network acl can be linked to many subnet, but TF can not handler that

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/terraform#1717] opened 2015-04-28 22:06 UTC
https://www.terraform.io/docs/providers/aws/r/network_acl.html
=> it's not possible to link **one** network acl to **many** subnet_id, but the API allow that

> Associating a Subnet with a Network ACL

> To apply the rules of a network ACL to a particular subnet, you must associate the subnet with the network ACL. You can associate a network ACL with multiple subnets; however, a subnet can be associated with only one network ACL. Any subnet not associated with a particular ACL is associated with the default network ACL by default.

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_ACLs.html#APIandCLI

**Comment by pforman** [comment] 2015-04-29 23:25
+1.  Furthermore, trying to associate multiples by providing a list to the "subnet_id" parameter causes a Terraform crash.


panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'



I can send a full log and config if necessary, but it's pretty easy to reproduce:

    subnet_id = ["${aws_subnet.public-A.id}","${aws_subnet.public-B.id}"]

**Comment by catsby** [comment] 2015-05-12 13:12
Thanks for the issue. I've marked it as an enhancement, since it's currently a limitation of Terraform.

Terraform is programmed to only handle a single subnet id per Network ACL, so using a list can't work at this time.

This is something I'll look into adding soon, most likely adding a new attribute `subnet_ids` and deprecating the current `subnet_id`.

**Comment by lyrixx** [comment] 2015-05-12 13:21
@catsby Nice. But actually I don't need this feature anymore. 

But don't forget to update the CHANGELOG if you deprecate something ;)

**Comment by catsby** [comment] 2015-05-12 19:09
I implemented this in https://github.com/hashicorp/terraform/pull/1931

**Comment by lyrixx** [comment] 2015-05-12 21:09
@catsby thanks ;)

**Comment by catsby** [comment] 2015-05-15 15:05
Just merged 1931

**Closed by catsby** 2015-05-15 15:05 UTC
Labels: enhancement, provider/aws
