### ISSUE TITLE
Enhancement Request: Fetch Repeat Module Once

### ISSUE THREAD

**Issue by bam0382** [hashicorp/terraform#17088] opened 2018-01-11 18:54 UTC
### Terraform Version

```
Terraform v0.10.2
```

### Terraform Configuration Files

```hcl
module "a" {
  source = "git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test//b?ref=master"
}

module "b" {
  source = "git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test//a?ref=master"
}

# in codecommit: empty files a/main.tf and b/main.tf
```

### Desired Behavior
```
$ terraform get
Get: git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test?ref=master
$
```

### Actual Behavior
```
$ terraform get
Get: git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test?ref=master
Get: git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test?ref=master
$
```

### Additional Context
We have a project with over 40 modules in it and we will continue to add more. #8555 calls this a bug but it's definitely not a bug.

### References

- #8555

**Comment by nbering** [comment] 2018-01-11 19:55
I think this issue might be a duplicate of #14036

**Comment by apparentlymart** [comment] 2018-01-17 23:38
Hi @bam0382! Thanks for this feature request.

As @nbering noted, this does seem to be the same as #14036, and so I'm going to close this to consolidate discussion over there.

This is something we'd like to address eventually to improve the experience for those who have many instances of the same module, but not something we'll be able to do in the short term since our attention is currently focused on integrating an improved parser and interpreter for Terraform configuration.

**Closed by apparentlymart** 2018-01-17 23:38 UTC
