### ISSUE TITLE
Terraform Apply crash on azure key_vault

### ISSUE THREAD

**Issue by david-may-shift** [hashicorp/terraform#34998] opened 2024-04-15 12:22 UTC
### Terraform Version

```shell
terraform is setup on github pipline with the following:

  - name: Terraform - Setup
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_wrapper: false
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

no debug output available - the terraform commands are part of our CI pipeline

### Expected Behavior

the terraform apply should work

### Actual Behavior

we get the following error

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: no expansion has been registered for module.document_service[0].module.key_vault.module.client_config_to_key_vault
goroutine 3196 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:84 +0x18b
panic({0x2e00120?, 0xc00578b230?})
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandAbsModuleCall(0x2f3a180?, {{0xc006c25bc0, 0x2, 0x2}, {{}, {0xc001d71080, 0x1a}}})
	/home/runner/work/terraform/terraform/internal/instances/expander.go:171 +0x265
github.com/hashicorp/terraform/internal/terraform.(*evaluationStateData).GetModule(0xc0022a9950, {{}, {0xc001d71080?, 0x0?}}, {{0xc00121a480, 0x3d}, {0x4, 0x12, 0x68}, {0x4, ...}})
	/home/runner/work/terraform/terraform/internal/terraform/evaluate.go:398 +0x788
github.com/hashicorp/terraform/internal/lang.(*Scope).evalContext(0xc0022a99e0, {0xc004e84788, 0x1, 0x1}, {0x3d64030, 0xc00578b100})
	/home/runner/work/terraform/terraform/internal/lang/eval.go:381 +0x1112
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalReference(0xc0022a99e0, 0xc006a1cd20, {{0x3d75ce0?, 0x5891580?}})
	/home/runner/work/terraform/terraform/internal/lang/eval.go:216 +0x9b
github.com/hashicorp/terraform/internal/terraform.validateDependsOn({0x3d984a8, 0xc004472960}, {0xc0029f4108?, 0xc0048c5770?, 0x5891580?})
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:581 +0x42e
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableOutput).Execute(0xc0011ceb40, {0x3d984a8, 0xc004472960}, 0x70?)
	/home/runner/work/terraform/terraform/internal/terraform/node_output.go:382 +0x791
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc00193bcc0, {0x3d984a8, 0xc004472960}, {0x7f8f4d072918, 0xc0011ceb40})
	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:153 +0xbb
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x32a43c0, 0xc0011ceb40})
	/home/runner/work/terraform/terraform/internal/terraform/graph.go:112 +0x62a
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0011cf560, {0x32a43c0, 0xc0011ceb40}, 0xc0035068c0)
	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 2249
	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xff3
Error: Process completed with exit code 11.
```

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply

### References

possibly related to the following
https://github.com/hashicorp/terraform/issues/34976
https://github.com/hashicorp/terraform/issues/34997

**Comment by jbardin** [comment] 2024-04-15 13:01
Duplicate of #34976

**Closed by jbardin** 2024-04-15 13:01 UTC
Labels: bug, new
