### ISSUE TITLE
"data" resource not available to "resource" on the initial apply

### ISSUE THREAD

**Issue by gek0** [hashicorp/terraform#24333] opened 2020-03-10 10:57 UTC
### Terraform Version

```
Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v2.0.0
```

### Terraform Configuration Files

variables
```hcl
{
  "environment": "prod",
  "rbac_rules": [
    {
      "role_definition_name": "Virtual Machine Contributor",
      "scope_path": "storage/teststorageaccount",
      "principal_type": "group",
      "principal_name": "guest_users"
    }
  ]
}
```

main resources
```hcl
# initialize the providers
provider "azurerm" {
  version = "~> 2"

  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
  features {}
}

provider "azuread" {
  alias = "aad"

  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
}

# get subscription name from ID (used in building state path key)
data "azurerm_subscription" "rbac_target_subscription" {
  subscription_id = var.subscription_id
}

# 2a-b-c. get principal IDs for user/group/service principal
data "azuread_user" "user_id" {
  provider = azuread.aad
  for_each = toset([for k, v in local.env_data_state_rules[var.environment] : k if v.principal_type == "user"])

  user_principal_name = lookup(local.env_data_state_rules[var.environment][each.key], "principal_name", null)
}

data "azuread_group" "group_id" {
  provider = azuread.aad
  for_each = toset([for k, v in local.env_data_state_rules[var.environment] : k if v.principal_type == "group"])

  name = lookup(local.env_data_state_rules[var.environment][each.key], "principal_name", null)
}

data "azuread_service_principal" "service_principal_id" {
  provider = azuread.aad
  for_each = toset([for k, v in local.env_data_state_rules[var.environment] : k if v.principal_type == "service-principal"])

  display_name = lookup(local.env_data_state_rules[var.environment][each.key], "principal_name", null)
}

# 5a. get scope IDs
data "terraform_remote_state" "state_file" {
  for_each = toset(keys(local.rbac_states_principals))

  backend = "azurerm"
  config = {
    tenant_id            = var.tenant_id
    subscription_id      = local.storage_subscription_id
    resource_group_name  = local.state_storage_resource_group
    storage_account_name = local.state_storage_account
    container_name       = var.state_container_name
    key                  = lookup(local.rbac_states_principals[each.key], "state_path_key", null)
  }
}

# 8. apply RBAC on wanted resources (scope = on what, principal = to who)
resource "azurerm_role_assignment" "rbac_assignment" {
  for_each = toset(keys(local.rbac_rules))

  role_definition_name = lookup(local.rbac_rules[each.key], "role_definition_name", null)
  scope                = lookup(local.rbac_rules[each.key], "scope_id", null)
  principal_id         = lookup(local.rbac_rules[each.key], "principal_id", null)
}
```
locals
```hcl
locals {
  # get terraform remote state backend for the running environment
  storage_subscription_id      = var.storage_subscription_id[var.environment]
  state_storage_resource_group = var.state_storage_resource_group[var.environment]
  state_storage_account        = var.state_storage_account[var.environment]

  # 1. create an unique key for each rule to use it as a set later on - escape spaces!
  rules_for_data_state = {
    for rule in var.rbac_rules : format("%s--%s--%s", replace(rule.role_definition_name, " ", ""), rule.scope_path, replace(rule.principal_name, " ", "")) => {
      role_definition_name : rule.role_definition_name
      principal_type : rule.principal_type,
      principal_name : rule.principal_name,
      state_path_key : format("%s/%s/%s/%s",
        data.azurerm_subscription.rbac_target_subscription.display_name,
        var.resource_group_name,
        rule.scope_path,
        var.state_filename
      )
    }
  }

  # 2. flatten the maps per environment - only the selected environment is preset in the map (makes multiple environments dynamic)
  env_data_state_rules = map(var.environment, local.rules_for_data_state)

  # 3. extract principal IDs from data resources and prepare for data merge
  user_principals = {
    for key, value in data.azuread_user.user_id : key => value.object_id
  }
  group_principals = {
    for key, value in data.azuread_group.group_id : key => value.object_id
  }
  service_principals = {
    for key, value in data.azuread_service_principal.service_principal_id : key => value.object_id
  }

  # 4. merge those collections into complete maps - this way we can loop over them to create a single map with principal IDs added
  rbac_principals = merge(
    local.user_principals,
    local.group_principals,
    local.service_principals
  )

  # 5. add those extracted principal IDs to a new map with terraform state file paths - will be used to get scope IDs
  rbac_states_principals = {
    for key, value in local.env_data_state_rules[var.environment] : key => {
      role_definition_name : value.role_definition_name
      principal_id = local.rbac_principals[key],
      state_path_key : value.state_path_key
    }
  }

  # 6. now lets get scope IDs from terraform state files - outputs have to be per our convention "info {}" with at least an "id" attribute
  data_scopes = {
    for key, value in data.terraform_remote_state.state_file : key => [
      for id in flatten([value.outputs.info.id]) : id
    ]
  }

  # 7. create a list of maps with each ID in its own map
  data_scopes_per_id = flatten([
    for key, ids in local.data_scopes : [
      for id in ids : {
        key = key
        id  = id
      }
    ]
  ])

  # 8. now we have to merge two maps to a final one containing everything needed for use in RBAC - map key is updated with IDs instead of names (some resources are modified in bulk - multiple IDs)
  rbac_rules = {
    for key, value in local.data_scopes_per_id : format("%s--%s--%s", replace(lookup(local.rbac_states_principals[value.key], "role_definition_name", null), " ", ""), value.id, lookup(local.rbac_states_principals[value.key], "principal_id", null)) => {
      scope_id : value.id,
      scope_path : split("--", value.key)[1]
      principal_id : lookup(local.rbac_states_principals[value.key], "principal_id", null)
      principal_name : split("--", value.key)[2]
      role_definition_name : lookup(local.rbac_states_principals[value.key], "role_definition_name", null)
    }
  }
}
```

### Expected Behavior

Resource on the bottom should have all the data needed to be created.
I'm using `data` resources to get existing resources ID (converted from names)  but that is not usable before initial apply. I know the `-target` switch but that is not usable in CI/CD environment with Runatlantis and an ugly replacement...

This only works if all the `data` resources are applied before the `resource "azurerm_role_assignment"`

### Actual Behavior

```hcl
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.resource_group: Refreshing state...
module.azure-rbac.data.azurerm_subscription.rbac_target_subscription: Refreshing state...
module.azure-rbac.data.azuread_group.group_id["VirtualMachineContributor--storage/teststorageaccount--guest_users"]: Refreshing state...

------------------------------------------------------------------------

Error: Invalid for_each argument

  on .terraform/modules/azure-rbac/10-main.tf line 61, in resource "azurerm_role_assignment" "rbac_assignment":
  61:   for_each = toset(keys(local.rbac_rules))

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context

All of the resources called with the `data` resource are created before but cannot be used/calculated in the final `resource` used with `for_each`
Tried adding forced `depends_on` but that did not help either
Not sure if I'm doing anything wrong here and any help is appreciated?

**Comment by jbardin** [comment] 2020-03-11 02:26
Hi @gek0 

The issue here is that some value in the chain of expressions that led to  `rbac_rules` is unknown during the plan, but there's a lot of values to walk through here to determine where that might be coming from. 

one clue is that in the output you've provided not all the data sources are shown being read. This would indicate that some part of the remaining data source configuration is unknown (possibly themselves depending on another resource), causing those data sources to be delayed until after apply. Since this is in a module and not all variable inputs are shown, it's hard to tell what may be missing from these configurations. There may be some clues in the trace log as well.

Another thing to note is that `merge` is part of the data chain here, and until recently it was more conservative than necessary, and would return unknown if any part of the arguments was unknown. It doesn't look like this part of the config would be affected, because the for_each isn't relying on those keys specifically, but it's something to watch out for in 0.12. 

If you can reduce the example to find and remove the unknown value, and still end up with an error, please post the complete reproduction here for inspection. 

Thanks!

**Comment by gek0** [comment] 2020-03-17 12:44
I've tested this example and triple-checked the output. Everything works if a remove the last part in main resources file or create a module with the data part and plan/apply it with `-target` argument.
This part is problematic when trying to plan/apply it all at once.

```
# 8. apply RBAC on wanted resources (scope = on what, principal = to who)
resource "azurerm_role_assignment" "rbac_assignment" {
  for_each = toset(keys(local.rbac_rules))

  role_definition_name = lookup(local.rbac_rules[each.key], "role_definition_name", null)
  scope                = lookup(local.rbac_rules[each.key], "scope_id", null)
  principal_id         = lookup(local.rbac_rules[each.key], "principal_id", null)
}
```
So the problem is not in the locals and all those expressions + `merge` function since terraform can easily calculate the data sources and save them to state.
But looks like those data sources, especially `data "terraform_remote_state" "state_file"` one cannot be calculated and used at the same time as the `resource "azurerm_role_assignment" "rbac_assignment"` one.

So, all of the values in the chain of expressions that led to rbac_rules are **known**.
Above every expression, there is an ordinal that helps follow the chain of expression calculation

For now, I've avoided this issue by creating a module that calculates the data sources (plan/applied with `-target`) and then the `resource "azurerm_role_assignment"` is plan/applied out of the module scope when the state already contains those data sources saved.

Interestingly enough, this is only problematic for the first run ever. Any other run - when new variables are added/rbac_rules list updated. Data + resource source can be planned/applied without any dependency error or a race condition met.

**Comment by jbardin** [comment] 2020-03-17 14:29
Hi @gek0 

Sorry if I wasn't clear here, the `azurerm_role_assignment` issue is not really the problem per say, it's the symptom of the `for_each` expressions being unknown.

The `remote_state.state_file` data source cannot be read before the plan (along with `azuread_user.user_id` and `azuread_service_principal.service_principal_id`), because some of its configuration is not known at that time. As you indicated that only the first apply is effected, it furthers the hypothesis that the data sources are depending on the output of a resource, since that can be resolved from state on subsequent plans. 

Without a complete configuration showing the sources of all the input variables, I can't say definitively here that there isn't a bug, but overall this appears to be working normally, so I'm going to close this out for now.

If you can provide a complete example with all the module inputs, none of which are being derived from a resource, please fell free to reply here and we can review the issue further.

Thanks

**Closed by jbardin** 2020-03-17 14:29 UTC
