### ISSUE TITLE
missing provider with alias has wrong source url

### ISSUE THREAD

**Issue by kyeotic** [hashicorp/terraform#27015] opened 2020-11-23 19:33 UTC
### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```

### Terraform Configuration Files

**Root main.tf**
```terraform
terraform {
  required_version = ">= 0.13.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~>3.4"
    }
    null = {
      source = "hashicorp/null"
      version = "~>2.0"
    }
    external = {
      source = "hashicorp/external"
      version = "~>2.0"
    }
  }
}
```

Child module declaration
```terraform
module "region_us" {
  providers = {
    aws          = aws.us
    certificates = aws.us
    dns          = aws.us
  }
  // ..
}
```

grandchild declaration (inside child)

```terraform
provider "aws" {
  region = var.region
  alias  = "certificates"
}

provider "aws" {
  region = var.region
  alias  = "dns"
}

module "cert" {
  source = "github.com/azavea/terraform-aws-acm-certificate?ref=3.0.0"

  providers = {
    aws                 = aws.dns // .. added this line trying to debug, error happens with and without
    aws.acm_account     = aws.certificates
    aws.route53_account = aws.dns
  }

  domain_name                       = var.alt_api_name
  hosted_zone_id                    = data.aws_route53_zone.alt.zone_id
  validation_record_ttl             = "60"
  allow_validation_record_overwrite = true
}
```

### Debug Output

[debug output](https://pastebin.com/khCjEyec)

### Expected Behavior
`terraform plan` should run

### Actual Behavior

Error's on random child module (one per region)

```
Error: missing provider provider["registry.terraform.io/hashicorp/certificates"].ap
```

Note: there is no "certificates" provider. That is the alias of one of the aws providers. **The bug here is that the alias name is being used as the provider name**

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

The child modules regions in a multi-region config. Each region is instantiated as a module, and in turn tries to instantiate this certificate module, passing in two aws providers as needed.

This was working in terraform 0.12.29, and is failing as I upgrade to 0.13.5 after running the upgrade command.

### References

Similar issues

#26354
#26312

**Comment by apparentlymart** [comment] 2020-11-23 23:50
Hi @kyeotic,

The correct syntax for connecting provider configurations in the current module with provider configurations in a child module is to write out the full `provider.alias` reference on both sides of the mapping. In your case, I think that would look like this:

```hcl
module "region_us" {
  providers = {
    aws              = aws.us
    aws.certificates = aws.us
    aws.dns          = aws.us
  }
  // ..
}
```

Terraform returned the error you saw because the syntax you used suggested that you wanted to assign to the configuration for a provider named `certificates` and a provider named `dns`. There happens to be a provider called `hashicorp/dns` which the second one would've mapped to, but there is currently no provider named `hashicorp/certificates` and so Terraform returned an error about that.

Terraform behaved as intended here, so I'm going to close this issue. However, if you have any follow-on questions about what I've said above please do feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core), where we can have a broader discussion about Terraform's behaviors and the implications of different configuration approaches. Thanks!

**Closed by apparentlymart** 2020-11-23 23:50 UTC
Labels: bug, new
