### ISSUE TITLE
Terraform keeps on running forever when creating DynamoDB table and read or write capacity account limit is reached

### ISSUE THREAD

**Issue by drieselliott** [hashicorp/terraform#13802] opened 2017-04-20 14:32 UTC
Hi there,

### Terraform Version
0.9.3

### Affected Resource(s)
- aws_dynamodb_table

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
When reaching the account limit for maximum amount of configured read or write throughput, Terraform fails indicating that it is not able to create the table.

### Actual Behavior
Terraform keeps on running forever trying to create the table, but actually not doing anything (I don't see tables being created in the AWS Console)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a tables until you reach the read or write capacity limit
2. Try to create an additional table using Terraform

### Important Factoids
N/A

**Comment by apparentlymart** [comment] 2017-04-20 16:39
Thanks for this report, @drieselliott!

It sounds like the retry behavior needs an exception for this particular type of error. If you're able to reproduce this again it'd be really useful if you could run Terraform with `TF_LOG=debug` to capture the debug output so we can see exactly what this error message looks like, though no worries if you can't since I assume we can repro this just by putting an obscenely-large value for either of those throughput values in a contrived test config...

**Comment by drieselliott** [comment] 2017-04-24 09:08
I'm sorry, but that might take me some time which I currently don't have. Also with the size of the project I'm working on 600+ Terraform resources, the run will take quite long with tracing enabled. I'll see if I can mash up a smaller test script, but I will probably not be able to do that this week.

**Comment by grubernaut** [comment] 2017-05-16 12:26
Hey @drieselliott, thanks for the issue! 

This is an upstream issue as discussed in #13339, and an issue has been filed with the AWS SDK here: https://github.com/aws/aws-sdk-go/issues/1271.

**Comment by drieselliott** [comment] 2017-05-16 14:37
Thanks for the update. I will be eagerly awaiting a fix from Amazon then :)

**Comment by grubernaut** [comment] 2017-05-18 12:35
Closed via #14571

**Closed by grubernaut** 2017-05-18 12:35 UTC
Labels: bug, provider/aws
