### ISSUE TITLE
Terraform v0.15.0 crashes while trying to change app_settings of azurerm_app_service

### ISSUE THREAD

**Issue by flobeier** [hashicorp/terraform#28419] opened 2021-04-16 19:35 UTC
### Terraform Version

```
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
locals {
  common_app_settings = {
    ASPNETCORE_ENVIRONMENT                          = local.settings.dotnetcore_environment
    ApplicationInsightsAgent_EXTENSION_VERSION      = "~2"
    DiagnosticServices_EXTENSION_VERSION            = "disabled"
    InstrumentationEngine_EXTENSION_VERSION         = "~1"
    SnapshotDebugger_EXTENSION_VERSION              = "~1"
    WEBSITE_ENABLE_SYNC_UPDATE_SITE                 = "true"
    WEBSITE_RUN_FROM_PACKAGE                        = "1"
    XDT_MicrosoftApplicationInsights_Mode           = "recommended"
    XDT_MicrosoftApplicationInsights_BaseExtensions = "disabled"
    XDT_MicrosoftApplicationInsights_PreemptSdk     = "disabled"
  }
  b2c_ui_settings  = local.settings.b2c_tenants_active ? {
    "AzureADB2C:Instance" = "https://${module.azure_b2c.tenant_name}.b2clogin.com/tfp/"
    "AzureADB2C:ClientId" = azuread_application.main_application.application_id
    "AzureADB2C:Domain"   = "${module.azure_b2c.tenant_name}.onmicrosoft.com"
    "AzureADB2C:Scopes:0" = "https://${module.azure_b2c.tenant_name}.onmicrosoft.com/${azuread_application.backend_application.application_id}/user_impersonation"
    "AzureADB2C:Scopes:1" = "offline_access"
  } : {}
}

resource "azurerm_app_service" "ui" {
...
  app_settings = merge(local.common_app_settings, local.b2c_ui_settings, {
    APPINSIGHTS_INSTRUMENTATIONKEY        = azurerm_application_insights.ui.instrumentation_key
    APPLICATIONINSIGHTS_CONNECTION_STRING = "InstrumentationKey=${azurerm_application_insights.ui.instrumentation_key}"
    BACKEND_BASE_URL                      = "https://${azurerm_app_service.api.default_site_hostname}"
    AzureKeyVault__Uri                    = module.key_vault_ui.key_vault.vault_uri
    AzureServicesAuthConnectionString     = "RunAs=App"
  })
}
```

### Debug Output

```console
Terraform will perform the following actions:

  # azurerm_app_service.ui will be updated in-place
  ~ resource "azurerm_app_service" "ui" {
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ app_settings                      = (sensitive)
        id                                = "redacted"
        name                              = "redacted"
        tags                              = redacted
        # (14 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

```log
2021-04-16T18:59:57.880+0200 [DEBUG] provider.terraform-provider-azuread_v1.4.0_x5: 2021/04/16 18:59:57 [DEBUG] AzureAD Client User Agent: Go/go1.16 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v47.1.0 graphrbac/1.6 HashiCorp Terraform/0.15.0 (+https://www.terraform.io) Terraform Plugin SDK/2.3.0 terraform-provider-azuread/dev pid-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
2021-04-16T18:59:57.880+0200 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/azuread\"].b2c": visit complete
2021-04-16T18:59:57.880+0200 [TRACE] vertex "azuread_application.main_application (expand)": starting visit (*terraform.nodeExpandApplyableResource)
2021-04-16T18:59:57.880+0200 [TRACE] vertex "azuread_application.main_application (expand)": expanding dynamic subgraph
2021-04-16T18:59:57.880+0200 [TRACE] vertex "azuread_application.main_application (expand)": entering dynamic subgraph
2021-04-16T18:59:57.880+0200 [TRACE] vertex "azuread_application.backend_application (expand)": starting visit (*terraform.nodeExpandApplyableResource)
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.backend_application (expand)": expanding dynamic subgraph
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.main_application": starting visit (*terraform.NodeApplyableResource)
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.main_application": visit complete
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.main_application (expand)": dynamic subgraph completed successfully
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.main_application (expand)": visit complete
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.backend_application (expand)": entering dynamic subgraph
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.backend_application": starting visit (*terraform.NodeApplyableResource)
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.backend_application": visit complete
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.backend_application (expand)": dynamic subgraph completed successfully
2021-04-16T18:59:57.881+0200 [TRACE] vertex "azuread_application.backend_application (expand)": visit complete
2021-04-16T18:59:57.881+0200 [TRACE] vertex "local.b2c_ui_settings (expand)": starting visit (*terraform.nodeExpandLocal)
2021-04-16T18:59:57.881+0200 [TRACE] vertex "local.b2c_ui_settings (expand)": expanding dynamic subgraph
2021-04-16T18:59:57.881+0200 [TRACE] Expanding local: adding local.b2c_ui_settings as *terraform.NodeLocal
2021-04-16T18:59:57.881+0200 [TRACE] vertex "local.b2c_ui_settings (expand)": entering dynamic subgraph
2021-04-16T18:59:57.881+0200 [TRACE] vertex "local.b2c_ui_settings": starting visit (*terraform.NodeLocal)
2021-04-16T18:59:57.881+0200 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/azuread\"].b2c (close)": starting visit (*terraform.graphNodeCloseProvider)
2021-04-16T18:59:57.881+0200 [TRACE] GRPCProvider: Close
2021-04-16T18:59:57.882+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-16T18:59:57.883+0200 [TRACE] vertex "local.b2c_ui_settings": visit complete
2021-04-16T18:59:57.883+0200 [TRACE] vertex "local.b2c_ui_settings (expand)": dynamic subgraph completed successfully
2021-04-16T18:59:57.883+0200 [TRACE] vertex "local.b2c_ui_settings (expand)": visit complete
2021-04-16T18:59:57.883+0200 [TRACE] vertex "azurerm_app_service.ui": starting visit (*terraform.NodeApplyableResourceInstance)
2021-04-16T18:59:57.885+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azuread/1.4.0/linux_amd64/terraform-provider-azuread_v1.4.0_x5 pid=34287
2021-04-16T18:59:57.885+0200 [DEBUG] provider: plugin exited
2021-04-16T18:59:57.886+0200 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/azuread\"].b2c (close)": visit complete
2021-04-16T18:59:57.887+0200 [TRACE] readDiff: Read Update change from plan for azurerm_app_service.ui
2021-04-16T18:59:57.887+0200 [TRACE] readResourceInstanceState: reading state for azurerm_app_service.ui
2021-04-16T18:59:57.887+0200 [TRACE] upgradeResourceState: schema version of azurerm_app_service.ui is still 0; calling provider "azurerm" for any other minor fixups
2021-04-16T18:59:57.887+0200 [TRACE] GRPCProvider: UpgradeResourceState
2021-04-16T18:59:57.896+0200 [TRACE] readDiff: Read Update change from plan for azurerm_app_service.ui
2021-04-16T18:59:57.899+0200 [TRACE] vertex "azurerm_app_service.ui": visit complete
```

### Crash Output

```log
panic: value is marked, so must be unmarked first

goroutine 785 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2c2e7d0, 0xc000c8ab30, 0x24e3220, 0xc000ae38a8, 0x2c2e701)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1045 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc000c8b9f0, 0x1, 0x1, 0x2c2e7d0, 0xc000c8ab30, 0x24e3220, 0xc000ae38a8, 0x2bf8258, 0xc000ae3998, 0xc000ae38a8, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:175 +0x8f9
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x2c2e808, 0xc000c8b130, 0x23f4a00, 0xc001a534a0, 0x2bf8258, 0xc000ae3998, 0x0, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x2c2e808, 0xc000c8b130, 0x23f4a00, 0xc001a534a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:215 +0xc5
github.com/hashicorp/terraform/terraform.markProviderSensitiveAttributes(0xc0015721e0, 0x2c2e808, 0xc000c8b130, 0x23f4a00, 0xc001a534a0, 0x0, 0x13, 0xc000405778, 0x3)
	/home/circleci/project/project/terraform/evaluate.go:960 +0xbe
github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc001424480, 0x4d, 0xc000133368, 0x13, 0xc000405778, 0x3, 0xc0000511a0, 0xf, 0x63, 0x38, ...)
	/home/circleci/project/project/terraform/evaluate.go:787 +0x1333
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc0013e1630, 0xc000190070, 0xd, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30)
	/home/circleci/project/project/lang/eval.go:360 +0x206d
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
	/home/circleci/project/project/lang/eval.go:238
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc0013e1630, 0x2c2d298, 0xc002119e60, 0xc0015721e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:51 +0xf3
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc001f8e270, 0x2c2d538, 0xc002119e60, 0xc0015721e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:273 +0x1ad
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).plan(0xc001986c40, 0x2c64590, 0xc001f8e270, 0xc000173400, 0xc0003d6360, 0x0, 0x0, 0x0, 0x0, 0xc0004054ac, ...)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:577 +0x3d5
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc001acf100, 0x2c64590, 0xc001f8e270, 0x0, 0x0, 0xc000c3bc10)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:235 +0x63d
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).Execute(0xc001acf100, 0x2c64590, 0xc001f8e270, 0x7ff0d044eb01, 0xc000c3bd18, 0x40bb05, 0x243e3e0)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:129 +0xbc
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc00119c780, 0x2c64590, 0xc001f8e270, 0x7ff0d044eb40, 0xc001acf100, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbf
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x278a1c0, 0xc001acf100, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0xba2
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0009cd980, 0x278a1c0, 0xc001acf100, 0xc001710100)
	/home/circleci/project/project/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:304 +0x1246

```

### Expected Behavior

app_settings will be changed

### Actual Behavior

Terraform crashes

### Steps to Reproduce

I'm not sure how to reproduce the error. Some Web Apps trigger the crash, some were changed without problems.

**Comment by jbardin** [comment] 2021-04-16 19:38
Hi @flobeier, thanks for reporting this!

Duplicate of #28370

**Closed by jbardin** 2021-04-16 19:38 UTC
Labels: bug, new
