### ISSUE TITLE
Use of default_tags results in unexpected cycle

### ISSUE THREAD

**Issue by pauliusmiskinis** [hashicorp/terraform#29920] opened 2021-11-10 19:49 UTC
Using `default_tags` block results in unexpected cycle. 

### Terraform Version

Terraform v1.0.10

### Terraform Configuration Files

```
resource "aws_ssm_parameter" "A" {
  name      = "A"
  type      = "String"
  value     = "A"
  overwrite = true
  provider  = aws.A_provider
}

resource "aws_ssm_parameter" "B" {
  name      = "B"
  type      = "String"
  value     = "B"
  overwrite = true
  provider  = aws.B_provider
}

provider "aws" {
  alias  = "A_provider"
  region = "eu-west-1"
}

provider "aws" {
  alias  = "B_provider"
  region = "eu-west-1"

  default_tags {
    tags = {
      "A" = aws_ssm_parameter.A.value,
    }
  }
}
```
Apply this TF, then modify the value of `aws_ssm_parameter.A`, and taint `aws_ssm_parameter.B`. Attempt to apply again.

### Expected Behavior
Successful apply.

### Actual Behavior
```
Terraform will perform the following actions:

  # aws_ssm_parameter.A will be updated in-place
  ~ resource "aws_ssm_parameter" "A" {
        id        = "A"
        name      = "A"
        tags      = {}
      ~ value     = (sensitive value)
        # (7 unchanged attributes hidden)
    }

  # aws_ssm_parameter.B is tainted, so must be replaced
-/+ resource "aws_ssm_parameter" "B" {
      ~ arn       = "arn:aws:ssm:eu-west-1:107890497002:parameter/B" -> (known after apply)
      ~ data_type = "text" -> (known after apply)
      ~ id        = "B" -> (known after apply)
      + key_id    = (known after apply)
        name      = "B"
      - tags      = {
          - "A" = "A"
        } -> null
      ~ tags_all  = {
          ~ "A" = "A" -> "new_A_value"
        }
      ~ version   = 1 -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

╷
│ Error: Cycle: provider["registry.terraform.io/hashicorp/aws"].B_provider, aws_ssm_parameter.B (destroy), aws_ssm_parameter.A
│ 
│ 
╵
```

### Steps to Reproduce
  - Copy provided example above and apply the TF.
  - Modify the value of `aws_ssm_parameter.A` and taint `aws_ssm_parameter.B`
  - Attempt to apply changes

**Comment by jbardin** [comment] 2021-11-10 21:48
Hi @pauliusmiskinis,

Thanks for the example! This is rather unfortunate, while at first glance the cycle is unexpected since the direct references in the configuration do no constitute a cycle (or else this would have failed validation immediately), the destroy ordering imposes other restrictions, and creates the cycle seen here.

In order to ensure the correct order of operations when updating `aws_ssm_parameter.A`, it must first wait for `aws_ssm_parameter.B` to be destroyed, because a transitive dependency from `aws_ssm_parameter.B` to `aws_ssm_parameter.A` through the provider.

This is one of the reasons a provider should not be referencing a managed resource. In this case, since `aws_ssm_parameter.A.value` is statically known, it wold be better to break that out into a local value or input variable, removing the destroy cycle from the configuration. The only time the resource would need to be referenced to get an attribute would be if it were computed by the resource, but in that case the value would not be known and the `default_tags` could not be planned anyway.

Since this is working as designed I'm going to close the issue, but it serves as another good example for the feature request to provide a better debugging experience for dependency cycles: https://github.com/hashicorp/terraform/issues/26150

Thanks!

**Closed by jbardin** 2021-11-10 21:48 UTC
Labels: bug, new
