### ISSUE TITLE
plugin_cache_dir not working

### ISSUE THREAD

**Issue by techadmin1982** [hashicorp/terraform#27049] opened 2020-11-29 12:19 UTC
Has there been some changes the way Terraform handles the plugin directory ?. Recently i found that when i am running terraform init for the first time , it downloads the plugins to my configured path - all ok up till here. But wait , it then copies the content into the working directory. 

Of course it is not downloading the plugin (132 MB!!) twice from the internet , but why is it taking up disk space ? 
Earlier i remember it used to create soft links (shortcuts in windows). Please help me to understand.

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0
+ provider registry.terraform.io/hashicorp/random v2.3.1

**Comment by jbardin** [comment] 2020-11-30 17:49
Duplicate of #26144

**Closed by jbardin** 2020-11-30 17:49 UTC
Labels: bug, new
