### ISSUE TITLE
Terraform apply produces incorrect update for a set with an unknown empty element

### ISSUE THREAD

**Issue by prashantv** [hashicorp/terraform#30581] opened 2022-02-24 23:59 UTC
In a custom provider, we ran into an issue where "terraform apply" started sending invalid values to the provider, which resulted in some validation issues. Specifically,
 * The provider defined a resource which contained a set called "job" with a nested schema that contains multiple fields
 * In a config with a single job, when a nested field job.namespace was updated, terraform apply send a set with multiple jobs, where the first job was an invalid empty job.

I created a stripped-down, no dependency provider + tf files to reproduce this issue here:
https://github.com/prashantv/terraform-set-null-repro

(The goal of the provider is just to retain some state for TF using a file on disk, and otherwise has a schema that causes the issue).

### Terraform Version
```
Terraform v1.1.6
on darwin_amd64
```

### Terraform Configuration Files

This configuration referes to a dummy resource that was created to repro the issue without any external dependencies.
See https://github.com/prashantv/terraform-set-null-repro for details.

To reproduce the issue, namespace is changed to some other value, and then applied. The apply results in an unexpected job set that contains 2 elements, where one is empty.

```terraform
resource "tftest_service" "s" {
  name    = "svc1"
  job {
    namespace = "NS1"
    search_tags = {
      "foo" = "bar"
    }
  }
}
...
```

### Debug Output

https://gist.github.com/prashantv/b7847ee5e35fa0167b7580cd10598faf

### Expected Behavior

Apply to send the provider a single element in the "job" set.

### Actual Behavior

Apply sends the provider 2 elements in the "job" set, where the first is empty, formatting the panic message:
```
panic: jobSet has more elements than expected: [
  map[namespace: search_tags:map[]]    ## unexpected empty element in set
  map[namespace:NS2 search_tags:map[foo:bar]]
]
```

### Steps to Reproduce

To reproduce this issue, a repository is created with a specific dummy provider (that has no external dependencies), and with exact repro steps,
https://github.com/prashantv/terraform-set-null-repro

The custom provider is required, as this issue requires a specific setup:
 * TypeSet field which contains a nested schema (rather than just a simple primitive like string)
 * In the nested schema, one of the fields is a TypeMap, and the TypeMap has values specified in the .tf file

**Comment by apparentlymart** [comment] 2022-02-25 03:28
Hi @prashantv,

I think what you've seen here seems like a bug in the SDK rather than a bug in Terraform Core. Specifically, I think Terraform Core is sending the provider a new object with only NS2 and then the SDK is trying to represent both the removed object from the prior state and the added object in the new state, which is of course incorrect because the prior object isn't present anymore and so there's no data for it in the request, and it ends up empty.

For this and other problems encountered when developing providers against SDKv2, I'd suggest opening an issue in [the SDK's own repository](https://github.com/hashicorp/terraform-plugin-sdk), since then it will be seen by the team which maintains the SDK. If the SDK team finds that there _is_ a Terraform Core bug at the root of this then they will be able to refer this back to the Terraform Core team internally for further debugging.

I don't think there's anything we can immediately change in this repository to help with this without first understanding why the SDK is behaving how it is, so I'm going to close this issue for now although we can perhaps reopen it if the SDK team finds during debugging that it does not seem to be an SDK bug.

If this is an entirely new provider then you may have better luck developing it with the new [Terraform Plugin Framework](https://github.com/hashicorp/terraform-plugin-framework). It is a newer design which is tailored for modern Terraform, whereas the Terraform SDK was designed against a legacy version of Terraform which worked in a very different way, and so can run into trouble when handling complex interactions between types that older Terraform wouldn't have allowed. I suspect that this interaction between a map nested inside a set is one such limitation. The Plugin Framework is relatively new and not yet as fully-featured as SDKv2, but it has all of the basics and I think it should be able to support the relatively straightforward use-case you're trying to meet with your custom provider.

Thanks!

**Closed by apparentlymart** 2022-02-25 03:28 UTC
Labels: bug, new

**Comment by prashantv** [comment] 2022-02-25 23:04
Thank you for your thorough reply @apparentlymart! I've filed an [issue](https://github.com/hashicorp/terraform-plugin-sdk/issues/895) on terraform-plugin-sdk as suggested.

We actually ran into this issue in an existing provider that is much larger and more complex, I just created a new simple provider to repro the specific issue. That said, I'll keep a lookout on the new Terraform Plugin Framework so we can migrate to it post-1.0. Thanks!
