### ISSUE TITLE
[GCE] diffs didn't match during apply.

### ISSUE THREAD

**Issue by thecodeassassin** [hashicorp/terraform#7843] opened 2016-07-28 06:51 UTC
Hi there,
### Terraform Version

0.7.0
### Affected Resource(s)

Please list the resources as a list, for example:
- google_compute_instance_template
### Terraform Configuration Files

``` hcl
resource "google_compute_instance_template" "next" {

  machine_type = "${lookup(var.next_compute, var.environment)}"
  can_ip_forward = false
  tags = ["next-nodes", "compute-nodes"]

  lifecycle {
      create_before_destroy = true
  }

  depends_on = ["google_compute_instance.consul_server"]

  name_prefix = "next-web-"

  disk {
    source_image = "${var.next_image}"
    type = "pd-ssd"
    disk_size_gb = "${var.general_disk_size}"
    auto_delete = true
    type = "PERSISTENT"
  }

  metadata {
    startup-script = "${template_file.startup.rendered}"
    shutdown-script = "${file("files/shutdown.sh")}"
  }

  service_account {
   scopes = [
     "https://www.googleapis.com/auth/compute.readonly",
     # Admin sql access
     "https://www.googleapis.com/auth/sqlservice.admin"
   ]
 }

  network_interface {
      subnetwork = "${google_compute_subnetwork.website.name}"
      access_config {
          // Ephemeral IP
      }
  }

  scheduling {
    automatic_restart = true
    on_host_maintenance = "MIGRATE"
  }
}

resource "template_file" "startup" {
    template = "${file("files/startup.sh")}"

    vars {
        environment = "${var.environment}"
    }

    lifecycle {
        create_before_destroy = true
    }
}
```
### Debug Output

https://gist.github.com/thecodeassassin/ef81f2d904c6480796032f11a52d01bf
### Expected Behavior

Terraform should have applied
### Actual Behavior

Diff error
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
### Important Factoids

When i ran it again it worked.

**Comment by mitchellh** [comment] 2016-11-17 17:52
Hello! This should be fixed in later versions of Terraform (0.7.11 at time of writing). 

Its hard to know 100% since there isn't a clear reproduction case here, but we've fixed issues with this exact error message (and type) in recent versions. Please try again. Thanks!

**Closed by mitchellh** 2016-11-17 17:52 UTC
Labels: bug
