### ISSUE TITLE
Error: Failed to load state: read .terraform\terraform.tfstate: The process cannot access the file because another process has locked a portion of the file.

### ISSUE THREAD

**Issue by shrwan** [hashicorp/terraform#26145] opened 2020-09-06 08:02 UTC
Hi , 

My terraform script available on window container volume and it is working fine. I am able to create require infra but when i run command "terraform destroy"  then getting below error.
-------------------------------------------------------------------
Error: Error locking state: Error acquiring the state lock: Failed to read state file: The state file could not be read: read terraform.tfstate: The process cannot acce
ss the file because another process has locked a portion of the file.

Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
----------------------------------------------------------------------------
I also tried to store state on S3, but when i try to run "terraform apply" below error get generated.

Error: Failed to load state: read .terraform\terraform.tfstate: The process cannot access the file because another process has locked a portion of the file.

However when i tried with same terraform without container volume (without shared drive), It is working fine.

###
Terraform Version Terraform v0.12.25
provider "azurerm" {
  version = "=2.0.0"
  client_id = "${var.ARM_CLIENT_ID}"
  client_secret = "${var.ARM_CLIENT_SECRET}"
  tenant_id = "${var.ARM_Tenant_ID}"
  subscription_id = "${var.ARM_Subscription_ID}"
  features {}  
  
}

variable "ARM_CLIENT_ID" {
  type    = "string"
}

variable "ARM_CLIENT_SECRET" {
  type    = "string"
}
variable "ARM_Tenant_ID" {
  type    = "string"
}
variable "ARM_Subscription_ID" {
  type    = "string"
}
resource "azurerm_resource_group" "k8s" {
    name     = "${var.cluster_name}-${var.resource_group_name}"
    location = "${var.location}"
}

resource "azurerm_virtual_network" "virtualnet" {
  name                = "${var.virtual_network_name}"
  location            = "${azurerm_resource_group.k8s.location}"
  resource_group_name = "${azurerm_resource_group.k8s.name}"
  address_space       = ["${var.virtual_network_address_prefix}"]

 subnet {
   name           = "${var.aks_subnet_name_1}-1"
   address_prefix = "${var.aks_subnet_address_prefix_1}"
 }

  tags = "${var.tags}"
}

**Comment by shrwan** [comment] 2020-09-06 08:21
Error when run
terraform destroy

Error: Error locking state: Error acquiring the state lock: Failed to read state file: The state file could not be read: read terraform.tfstate: The process cannot acce
ss the file because another process has locked a portion of the file.

Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.

**Comment by apparentlymart** [comment] 2020-09-16 22:30
Hi @shrwan,

Unfortunately the behavior you are seeing seems to be related to some very specific configuration on your system and so we will not be able to reproduce it without understanding how your broader Windows system is configured. GitHub issues doesn't tend to work very well for that sort of open-ended troubleshooting, so I suggest that you start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where we can try to work together to understand the environment where you are running Terraform and what other software outside of Terraform might be interacting here to cause this error.

Once we can find a specific combination of circumstances that lead to the error message you shared we can then open an issue to talk about changes we could potentially make to Terraform to address it, but we won't be able to move forward through the bug process here until we can determine what combination of software on your system is causing the error. For that reason, I'm going to close this issue now with the intent of opening a new issue with more details if investigation on the community forum leads us to identify a bug in Terraform. Thanks!

**Closed by apparentlymart** 2020-09-16 22:30 UTC
Labels: bug, new
