### ISSUE TITLE
Official Linux package manager support

### ISSUE THREAD

**Issue by jasonmoo** [hashicorp/terraform#25324] opened 2020-06-21 05:12 UTC
I am setting up a Linux desktop and getting my tools in order when I come to find there is no official package managed version of Terraform.  

There appears to be a ticket open for 2 years now requesting this for Ubuntu.  https://github.com/hashicorp/terraform/issues/17794

Why is this?  There are macOS (homebrew) and Windows (choco) official packages.  Why not debian or arch?

**Comment by apparentlymart** [comment] 2020-06-25 00:16
Hi @jasonmoo,

The homebrew and chocolatey packages are maintained by members of their respective communities, not by the Terraform team at HashiCorp. A sufficiently-motivated member of the Debian maintainer community could similarly upload a Terraform package, but as far as I know nobody has done that yet.

The Terraform team at HashiCorp does not have the resources to support many different distribution channels at this time. That will likely change in the future as HashiCorp's release engineering team produces more build and release tools that work across _all_ of the HashiCorp products, but the Terraform team doesn't control the roadmap for that, so I can't say when such a thing may become available.

Since this issue is a duplicate of #17794, I'm going to close it to consolidate the discussion.

**Closed by apparentlymart** 2020-06-25 00:16 UTC
Labels: build, enhancement
