### ISSUE TITLE
Unable to create AWS VPC subnet.

### ISSUE THREAD

**Issue by Drewzar** [hashicorp/terraform#1533] opened 2015-04-15 00:24 UTC
I'm having an issue where terraform works on one of my AWS accounts and not the other.

My code: 
```
provider "aws" {
    access_key = "ACCESS_KEY_HERE"
    secret_key = "SECRET_KEY_HERE"
    region = "us-east-1"
}

resource "aws_vpc" "production" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  tags {
    Name = "production"
  }
}

resource "aws_subnet" "production" {
  vpc_id = "${aws_vpc.production.id}"
  cidr_block = "10.0.15.0/24"
}
```

The Plan:
```
drew@drewtopia ~/src/cabin/production> terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_subnet.production
    availability_zone:       "" => "<computed>"
    cidr_block:              "" => "10.0.15.0/24"
    map_public_ip_on_launch: "" => "0"
    vpc_id:                  "" => "${aws_vpc.production.id}"

+ aws_vpc.production
    cidr_block:                "" => "10.0.0.0/16"
    default_network_acl_id:    "" => "<computed>"
    default_security_group_id: "" => "<computed>"
    enable_dns_hostnames:      "" => "1"
    enable_dns_support:        "" => "<computed>"
    main_route_table_id:       "" => "<computed>"
    tags.#:                    "" => "1"
    tags.Name:                 "" => "production"

```

The Apply on the Staging AWS account:
```
drew@drewtopia ~/src/cabin/production> terraform apply
aws_vpc.production: Creating...
  cidr_block:                "" => "10.0.0.0/16"
  default_network_acl_id:    "" => "<computed>"
  default_security_group_id: "" => "<computed>"
  enable_dns_hostnames:      "" => "1"
  enable_dns_support:        "" => "<computed>"
  main_route_table_id:       "" => "<computed>"
  tags.#:                    "" => "1"
  tags.Name:                 "" => "production"
aws_vpc.production: Creation complete
aws_subnet.production: Creating...
  availability_zone:       "" => "<computed>"
  cidr_block:              "" => "10.0.15.0/24"
  map_public_ip_on_launch: "" => "0"
  vpc_id:                  "" => "vpc-8524efe0"
aws_subnet.production: Creation complete

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

The Apply on the Production AWS account:
```
drew@drewtopia ~/src/cabin/production> terraform apply
aws_vpc.production: Creating...
  cidr_block:                "" => "10.0.0.0/16"
  default_network_acl_id:    "" => "<computed>"
  default_security_group_id: "" => "<computed>"
  enable_dns_hostnames:      "" => "1"
  enable_dns_support:        "" => "<computed>"
  main_route_table_id:       "" => "<computed>"
  tags.#:                    "" => "1"
  tags.Name:                 "" => "production"
aws_vpc.production: Creation complete
aws_subnet.production: Creating...
  availability_zone:       "" => "<computed>"
  cidr_block:              "" => "10.0.15.0/24"
  map_public_ip_on_launch: "" => "0"
  vpc_id:                  "" => "vpc-91d78df4"
aws_subnet.production: Error: 1 error(s) occurred:

* Error creating subnet: The vpc ID 'vpc-91d78df4' does not exist
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error creating subnet: The vpc ID 'vpc-91d78df4' does not exist

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Both accounts are using an `Admin` IAM account.

**Comment by phinze** [comment] 2015-04-15 00:37
Hi @Drewzar, it looks like you're running against both AWS accounts from the same directory. After the first run, a `terraform.tfstate` file is produced in which Terraform records the "state of the world" after its operations are completed. Then in your follow-up run, the state file from the other environment is being picked up, so it's expecting the VPC recorded in the state file to exist.

To resolve this, each environment should get its own `tfstate` file. You can do this with the `-state=path` argument to terraform's commands.

I hope this helps to clarify! Let me know if there's anything I can explain further.

**Comment by Drewzar** [comment] 2015-04-15 00:42
Hey @phinze Sorry I should of mentioned that I removed the `terraform.tfstate` and the `terraform.tfstate.backupfile` between test.

**Comment by phinze** [comment] 2015-04-15 00:52
Well that makes things more interesting!

If you can reliably reproduce this, can you capture the output of the failing command with the environment variable `TF_LOG=1` set? This will tell terraform to generate copious debug logs that you can toss into a [gist](https://gist.github.com). (You'll want to pull any sensitive information out of the logs before posting.)

**Comment by Drewzar** [comment] 2015-04-15 01:00
Here's the [gist](https://gist.githubusercontent.com/Drewzar/f25466ea7071fc65531f/raw/f513493209b5cbc1a98a945a075ccfc65054dcb4/debug.log).

**Comment by catsby** [comment] 2015-04-15 14:21
Unfortunately I can't yet reproduce this. I even attempted planning with one set of credentials, and applying with the other, but it worked as expected. 

Any other clues? What version of Terraform are you using?

**Comment by rmenn** [comment] 2015-04-15 14:25
I was unable to reproduce it either, tried it on two different accounts. I replaced my aws vars and ran it on different accounts.

**Comment by catsby** [comment] 2015-04-15 14:26
This block of your gist looks good:

```
2015/04/14 17:54:31 terraform-provider-aws: 2015/04/14 17:54:31 [INFO] VPC ID: vpc-23c89246
2015/04/14 17:54:31 terraform-provider-aws: 2015/04/14 17:54:31 [DEBUG] Waiting for VPC (vpc-23c89246) to become available
2015/04/14 17:54:31 terraform-provider-aws: 2015/04/14 17:54:31 [DEBUG] Waiting for state to become: available
2015/04/14 17:54:31 terraform-provider-aws: 2015/04/14 17:54:31 [TRACE] Waiting 100ms before next try
2015/04/14 17:54:32 terraform-provider-aws: 2015/04/14 17:54:32 [INFO] Modifying enable_dns_support vpc attribute for vpc-23c89246: &ec2.ModifyVPCAttributeRequest{EnableDNSHostnames:(*ec2.AttributeBooleanValue)(0xc208038730), EnableDNSSupport:(*ec2.AttributeBooleanValue)(nil), VPCID:(aws.StringValue)(0xc20839ad70)}
2015/04/14 17:54:32 terraform-provider-aws: 2015/04/14 17:54:32 [DEBUG] Creating tags: []ec2.Tag{ec2.Tag{Key:(aws.StringValue)(0xc20838ff10), Value:(aws.StringValue)(0xc20838ff20)}}
```

It seems the VPC we're expecting is created and then updated, but then we can't find it

```
* Error creating subnet: The vpc ID 'vpc-23c89246' does not exist
2015/04/14 17:54:35 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
```

Are you possibly using IAM credentials that have a policy (or _don't_ have a policy) that prevents the second account from working with Subnets?

**Comment by catsby** [comment] 2015-04-15 14:32
@Drewzar can you try using the latest and greatest Terraform v0.4.2?

**Comment by Drewzar** [comment] 2015-04-15 19:00
Hey @catsby, after upgrading to `v0.4.2` everything is working like a charm! Now to dive in to the diff and see what changed. Thanks for looking in to it everyone!

**Comment by catsby** [comment] 2015-04-15 21:10
We'll close this for now then, thanks for following up. Let us know if you discover something :smile:

**Closed by catsby** 2015-04-15 21:10 UTC
Labels: bug, provider/aws
