### ISSUE TITLE
Support for Terraform Redis Enterprise Provider

### ISSUE THREAD

**Issue by ajeetraina** [hashicorp/terraform#27260] opened 2020-12-11 13:59 UTC
It would be good to have a Terraform Redis Enterprise provider which can help in deploying and managing Redis Enterprise.
References:

- https://github.com/hashicorp/terraform/issues/19607
- https://github.com/hashicorp/terraform/issues/19737

**Comment by jbardin** [comment] 2020-12-11 14:04
Duplicate of #19607

**Closed by jbardin** 2020-12-11 14:04 UTC
Labels: enhancement, new
