### ISSUE TITLE
0.15.0 crashes on apply

### ISSUE THREAD

**Issue by wgebis** [hashicorp/terraform#28386] opened 2021-04-15 15:12 UTC
### Terraform Version

```
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0

```

### Terraform Configuration Files

```terraform
terraform {
  backend "azurerm" {
    storage_account_name = "redacted"
    container_name       = "redacted"
    key                  = "redacted"
  }
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
    }
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
  required_version = ">= 0.13"
}

```

### Crash Output

```

panic: value is marked, so must be unmarked first

goroutine 634 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	github.com/zclconf/go-cty@v1.8.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.ElementIterator(0x3835e60, 0xc000add950, 0x30e8e00, 0xc001850e88, 0x1, 0xc001330070)
	github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1111 +0x4f
github.com/hashicorp/terraform/terraform.getValMarks(0xc00147c300, 0x3835e28, 0xc000adde40, 0x2ff9f60, 0xc00155d2c0, 0x0, 0x0, 0x0, 0x8020105, 0x2, ...)
	github.com/hashicorp/terraform/terraform/evaluate.go:998 +0x748
github.com/hashicorp/terraform/terraform.markProviderSensitiveAttributes(0xc00147c300, 0x3835e28, 0xc000adde40, 0x2ff9f60, 0xc00155d2c0, 0x0, 0x13, 0xc0001b2ef0, 0xf)
	github.com/hashicorp/terraform/terraform/evaluate.go:960 +0x6e
github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc001e84510, 0x4d, 0xc000524a20, 0x13, 0xc0001b2ef0, 0xf, 0xc000056290, 0xf, 0xc6, 0x3b, ...)
	github.com/hashicorp/terraform/terraform/evaluate.go:787 +0x1333
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc001eaa910, 0xc0002d20e0, 0xd, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30)
	github.com/hashicorp/terraform/lang/eval.go:360 +0x206d
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
	github.com/hashicorp/terraform/lang/eval.go:238
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc001eaa910, 0x38348b8, 0xc002152ba0, 0xc00147c300, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform/lang/eval.go:51 +0xf3
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc001b4eea0, 0x3834b58, 0xc002152ba0, 0xc00147c300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform/terraform/eval_context_builtin.go:273 +0x1ad
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).plan(0xc0011828c0, 0x386bd70, 0xc001b4eea0, 0xc000eb8dc0, 0xc00016e5a0, 0x0, 0x0, 0x0, 0x0, 0xc0001b2cf0, ...)
	github.com/hashicorp/terraform/terraform/node_resource_abstract_instance.go:577 +0x3d5
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc001a48160, 0x386bd70, 0xc001b4eea0, 0x0, 0x0, 0xc000093c10)
	github.com/hashicorp/terraform/terraform/node_resource_apply_instance.go:235 +0x63d
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).Execute(0xc001a48160, 0x386bd70, 0xc001b4eea0, 0xc00018e001, 0xc000093d18, 0x100d305, 0x3043880)
	github.com/hashicorp/terraform/terraform/node_resource_apply_instance.go:129 +0xbc
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc0005af740, 0x386bd70, 0xc001b4eea0, 0x2f8c40d0, 0xc001a48160, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/graph_walk_context.go:127 +0xbf
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x33901c0, 0xc001a48160, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/terraform/graph.go:59 +0xba2
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00016d8c0, 0x33901c0, 0xc001a48160, 0xc000d972c0)
	github.com/hashicorp/terraform/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	github.com/hashicorp/terraform/dag/walk.go:304 +0x1246

```

**Comment by jbardin** [comment] 2021-04-15 16:02
Thanks @wgebis!

Duplicate of #28370

**Closed by jbardin** 2021-04-15 16:02 UTC
Labels: bug, new
