### ISSUE TITLE
Dependencies not evaluated properly when for_each used

### ISSUE THREAD

**Issue by kristian-lesko** [hashicorp/terraform#28357] opened 2021-04-14 10:03 UTC
### Terraform Version

```
Terraform v0.14.6
```

When an indexed resource 
(e.g., `module.test.aws_instance.this["hostname01"]`)
is tainted and an apply is run, even resources dependent
on resources with different indexes on the same address are re-created:
```
- 'module.test.aws_instance.this["hostname01"]: Destruction complete after XmYYs'
- 'module.test.aws_eip_association.this["hostname01"]: Destruction complete after 1s'
- 'module.test.aws_eip_association.this["hostname02"]: Destruction complete after 1s'
...
- 'module.test.aws_instance.this["hostname01"]: Creating...'
- 'module.test.aws_eip_association.this["hostname01"]: Creating...'
- 'module.test.aws_eip_association.this["hostname02"]: Creating...'
```

### Terraform Configuration Files

```terraform
locals {
  public_ip = {
    "hostname2" = "1.2.3.4"
  }
  hostnames = toset(["hostname1", "hostname2", "hostname3"])
}

resource "aws_instance" "this" {
  for_each = local.hostnames

  ...
}

data "aws_eip" "this" {
  for_each = {
    for hostname, instance in aws_instance.this:
      hostname => local.public_ip[hostname]
  }

  public_ip = each.value
}

resource "aws_eip_association" "this" {
  for_each = data.aws_eip.this

  instance_id = aws_instance.this[each.key].id
  allocation_id = data.aws_eip.this[each.key].id
}
```

### Expected Behavior

Each resource depending on an indexed resource should be evaluated
as only depending on the specific index at that address, not all of them.

Resources depending on resources at indexes that are not changed
should not be touched.

### Actual Behavior

When a single resource at an address indexed by a `for_each` loop
(e.g., `resource.some_address["index01"]`) is tainted,
even resources depending resources at the other indexes
(e.g., `resource.some_address["index02"]`, `["index03"]` etc.)
are evaluated as being dependent thereon (and re-created
if the depending attribute forces a new resource).

### Steps to Reproduce

1. Create setup as described in config file above
2. `terraform apply`
3. `terraform taint 'aws_instance.this["hostname01"]'`
4. `terraform plan`/`terraform apply`

### Additional Context

We use Terragrunt to execute the aforementioned Terraform code.

This does not seem to be specific to the `aws_instance` resource;
we saw a similar behavior, for example, with `openstack_compute_instance_v2`
resources and with another internal provider.

This doesn't happen in every case such resources are defined in this way,
but a common denominator in all the affected cases is resources being
indexed by a `for_each` loop and another (depending) set of resources
being also indexed by `for_each` that iterates over the former.

**Comment by jbardin** [comment] 2021-04-14 13:04
Hi @kristian-lesko,

From the partial example shown here it sounds like Terraform is working as intended, though it does present a tricky situation when you have data sources which depend directly on managed resources. You are not actually using any computed attributes from `aws_instance.this` within the data source, so what you have here is only a round-about way to add `depends_on`.

Since changes to the `aws_instance.this` resource indicate that the data source must also be updated, that data source cannot be read at all during planning, so any other resources which depend on the data source will also show changes indicating `"known after apply"`. In most cases these will end up becoming no-ops during apply time when terraform can determine that there are no actual changes to be made. 

In order to make the plan more useful, I think creating an indirection from the data source to the managed resource will work in your case. Something like this may work but I have a feeling you are also going to need to reference a computed attribute of the instance within that expression to get the behavior your want, as the data source will not be re-read otherwise from only tainting the resource.

```
locals {
  instances = {
    for hostname, instance in aws_instance.this:
      hostname => local.public_ip[hostname]
  }
}

data "aws_eip" "this" {
  for_each = local.instances
  public_ip = each.value
}
```

The example here is not quite complete, so there may still be other details to consider. You may also want to test out your config with the upcoming 0.15 release which may offer improvements in this area (if you are using this within modules also using `for_each`, there is a related improvement coming in v0.15.1).

As there doesn't appear to be a bug in the behavior here, I'm going to close this out. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) if you have more questions, and where there are more people ready to help.

**Closed by jbardin** 2021-04-14 13:04 UTC
Labels: bug, new
