### ISSUE TITLE
Requesting a module above the current path breaks provider namespacing

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/terraform#27442] opened 2021-01-08 09:40 UTC
### Terraform Version

```
$ terraform version
Terraform v0.14.4
+ provider registry.terraform.io/resinstack/linuxkit v0.0.2
```

### Terraform Configuration Files

A minimal example showing the bug can be obtained from the tf-provider-bug branch of `resinstack/terraform-linuxkit-resinstack`.

### Debug Output

Debug output can be found at this link: https://gist.github.com/the-maldridge/8af7acd11273fb716a56a66fba4d9021

### Expected Behavior

Change directories to the examples/all-in-one path in the provided repo.  Terraform should initialize and pull exactly one provider from the registry from the resinstack namespace.  It should then report that there are no changes to apply as the example case provides no resources, only data sources.  The module should be initialized after `terraform init` returns. 

### Actual Behavior

Terraform correctly retrieves the linuxkit provider from the resinstack namespace, and then produces a phantom provider request for linuxkit from the hashicorp namespace which fails for obvious reasons.

### Steps to Reproduce
1. `git clone -b tf-provider-bug https://github.com/resinstack/terraform-linuxkit-resinstack`
2. `cd terraform-provider-linuxkit/examples/all-in-one`
3. `terraform init`

The following output should result:

```
Initializing modules...
- all_in_one in ../..

Initializing the backend...

Initializing provider plugins...
- Finding resinstack/linuxkit versions matching "0.0.2"...
- Finding latest version of hashicorp/linuxkit...
- Installing resinstack/linuxkit v0.0.2...
- Installed resinstack/linuxkit v0.0.2 (self-signed, key ID 43782574B87B7458)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/linuxkit: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/linuxkit
```

### Additional Context
I'm trying to produce an example showing how to consume the root module, which means that the source points at a path above the workspace but that also includes it.  I don't see any reason this should fail, and indeed moving the `aio.tf` file up two levels and removing the module stanza initializes the correct number of providers.

**Comment by jbardin** [comment] 2021-01-08 13:44
Hi @the-maldridge 

I don't think what you're seeing here is related to the relative path of the module, it appears that your module does not declare the necessary `required_providers` to locate the linuxkit provider. Marking as a duplicate of #27361

Thanks!

**Closed by jbardin** 2021-01-08 13:44 UTC
Labels: bug, new

**Comment by the-maldridge** [comment] 2021-01-08 18:45
Hmm, I guess what is not clear to me from that ticket (and why I did not comment there) is that the meaning of 'default' is unclear.  I assumed that default meant "not aliased" rather than "beyond the hashicorp namespace" but it seems like this is not the case.
