### ISSUE TITLE
Map default merged rather than overridden

### ISSUE THREAD

**Issue by cbarbour** [hashicorp/terraform#8540] opened 2016-08-29 21:54 UTC
### Terraform Version
Terraform v0.7.2

### Affected Resource(s)
Variable handling (core)

### Terraform Configuration Files

```hcl
#terraform.tfvars
mymap={ foo = "bar", baz = "biff" }
```

```hcl
variable "mymap" {
  type = "map"
  default = { "zonk" = "pow" }
}

data "template_file" "test" {
  template = "${data}"

  vars {
    data = "${join(",", formatlist("key: %s, val: %s. ", keys(var.mymap), values(var.mymap)))}"
  }
}

output "test" {
  value = "${data.template_file.test.rendered}"
}
```

### Output
```console
data.template_file.test: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

test = key: baz, val: biff. ,key: foo, val: bar. ,key: zonk, val: pow.
```

### Debug Output
https://gist.github.com/cbarbour/dfabe650fef1918e3f565f712036a677

### Expected Behavior
Map defaults should be overridden when another map is explicitly declared.

### Actual Behavior
Default values merged with override map.

### Steps to Reproduce
1. `terraform apply`
2. Check outputs

**Comment by xpaulz** [comment] 2016-10-12 23:36
is this a bug or a feature?  I thought the documentation used to say explicitly that mappings declared via .tfvars orTF_VAR_name were supposed to be merge() with the default value.

**Comment by jbardin** [comment] 2016-10-18 18:08
Hi,

Yes, merging the maps is the behavior we expected. @mitchellh tagged this as a bug however, so I'll see if he had any ideas for enhancement in mind before closing this.

**Comment by mitchellh** [comment] 2016-10-18 19:00
I was only quickly categorizing and not reading too deeply into the issue. If this is working as designed AND it is clearly documented, I'll close this.

**Closed by mitchellh** 2016-10-18 19:00 UTC
Labels: bug, core

**Comment by cbarbour** [comment] 2016-10-18 20:09
That behavior is documented, but surprising to me. Going forward, I'll use length() and pick() where the map is actually referenced when I need an override rather than a merge.

Honestly, if I wanted a merge, it would have been a lot more straightforward to do it explicitly where the variable is consumed rather than implicitly where the variable is declared.

**Comment by mitchellh** [comment] 2016-10-18 20:59
@cbarbour That's true, and I think its worth looking into the UX here, it seems sensible that single values should be overridable.

**Comment by b-dean** [comment] 2017-07-19 21:54
Interestingly this is **not** the behavior when you use modules:

```hcl
# terraform.tfvars
mymap={ foo = "bar", baz = "biff" }
variable "mymap" {
  type = "map"
  default = { "zonk" = "pow" }
}
```

```hcl
# mymod/test.tf
data "template_file" "test" {
  template = "${data}"

  vars {
    data = "${join(",", formatlist("key: %s, val: %s. ", keys(var.mymap), values(var.mymap)))}"
  }
}

output "test" {
  value = "${data.template_file.test.rendered}"
}
```

```hcl
# mymod.tf
module "mymod" {
  source = "./mymod"
  mymap = {
    "test" = "meh"
  }
}

output "mod_test" { 
  value = "${module.mymod.test}"
}
```

Outputs: 
```
data.template_file.test: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

mod_test = key: test, val: meh.
```

I would actually *like* the default variables in a module to merge with the values I pass in for a map, but it doesn't ¯\\\_(ツ)\_/¯

**Comment by pdecat** [comment] 2019-05-23 16:15
FTR, the behavior [has changed since terraform 0.12, such maps are now overridden instead of merged](https://www.terraform.io/upgrade-guides/0-12.html#map-variables-no-longer-merge-when-overridden).
