### ISSUE TITLE
Provider crashes on plan command

### ISSUE THREAD

**Issue by jantijink** [hashicorp/terraform#33322] opened 2023-06-07 09:47 UTC
### Terraform Version

```shell
tfversion:  Terraform v1.4.4 on linux_amd64 + provider registry.terraform.io/confluentinc/confluent v1.24.0 + provider registry.terraform.io/cyrilgdn/postgresql v1.18.0 + provider registry.terraform.io/databricks/databricks v1.14.3 + provider registry.terraform.io/hashicorp/azuread v2.15.0 + provider registry.terraform.io/hashicorp/azurerm v3.54.0 + provider registry.terraform.io/hashicorp/random v3.5.1 Your version of Terraform is out of date! The latest version is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

We have quite a large repository and it cannot be made public.

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 5848 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/logging/panic.go:55 +0x153
panic({0x227e900, 0x2d48890})
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:890 +0x262
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.True({{{0x2d74140?, 0xc00012e292?}}, {0x2462280?, 0xc003bcf4d0?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/value_ops.go:363 +0x52
github.com/zclconf/go-cty/cty.IndexStep.Apply({{}, {{{0x2d74140?, 0xc00012e291?}}, {0x227e900?, 0xc00316ac80?}}}, {{{0x2d741e8?, 0xc0033d6550?}}, {0x2462280?, 0xc003bce2e8?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/path.go:232 +0x335
github.com/zclconf/go-cty/cty.Path.Apply({0xc0046b5170?, 0x2, 0x40e4e5?}, {{{0x2d74220?, 0xc0033d6d60?}}, {0x2360480?, 0xc004b1cf90?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/path.go:147 +0xad
github.com/hashicorp/terraform/internal/terraform.filterMarks({{{0x2d74220?, 0xc0033d6d60?}}, {0x2360480?, 0xc004b1cf90?}}, {0xc001472680?, 0x4, 0x2360480?})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/marks.go:19 +0x14f
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc004637e00, {0x2d8bfb8, 0xc002ca87e0}, 0x0, 0xc001a07c20, 0x0, {0x0, 0x0, 0x0?})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/node_resource_abstract_instance.go:1084 +0x2d8d
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc002020280, {0x2d8bfb8, 0xc002ca87e0})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/node_resource_plan_instance.go:223 +0xdae
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x2d8bfb8?, 0xc002ca87e0?}, 0xc0?)
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/node_resource_plan_instance.go:60 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc004865b30, {0x2d8bfb8, 0xc002ca87e0}, {0x7f0f5ce8aa10, 0xc002020280})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x26e9960, 0xc002020280})
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/terraform/graph.go:75 +0x315
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000980540, {0x26e9960, 0xc002020280}, 0xc0029d2380)
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/runner/work/_temp/actions-go-build/0.1.7/b712d316a0484806ec3fa2c744c064f8874ceff1/verification/e59d3931dda583b4737ae01e6ee12ac945ba7579c27fd31415e97d6c6680301c/cache/source/terraform/terraform/dbd7ba96fd6cd393b8e895dc4a928d808541bb19/internal/dag/walk.go:304 +0xf65

### Expected Behavior

Terraform plan would produce a plan instead of crashing.

### Actual Behavior

Crash

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

Running from an Azure DevOps pipeline.

**Comment by jbardin** [comment] 2023-06-07 12:47
Duplicate of #32956

**Closed by jbardin** 2023-06-07 12:47 UTC
Labels: bug, new
