### ISSUE TITLE
When using `-target` against a resource whose count is derived from another resource, plan can be incorrect

### ISSUE THREAD

**Issue by robin-norwood** [hashicorp/terraform#27916] opened 2021-02-24 20:30 UTC
When using `-target` against a resource whose count is derived from another resource, plan can be incorrect. Specifically, when applying a change which reduces the count (from `3` to `2`) of a resource (`foo`), and using `-target` to target a resource whose count depends on the number of `foo`s (`bar[2]`), the plan step incorrectly reports that 1 `foo` and 1 `bar` will be destroyed, when only a single `bar` is destroyed upon accepting the plan.

[GitHub Repository with reproduction case](https://github.com/robin-norwood/terraform-target-count).

### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

```terraform
resource "null_resource" "foo" {
  count = var.resource_count
}

resource "null_resource" "bar" {
  count = length(null_resource.foo)
}
```

### Debug Output
[Gist of steps](https://gist.github.com/robin-norwood/4327c0f5dd7ecce724930b2d04e9a666) from [example repo's README.md
](https://github.com/robin-norwood/terraform-target-count/blob/main/README.md)

### Crash Output

n/a

### Expected Behavior

1. Terraform `plan` should report that only the targeted `bar` will be destroyed.
2. Terraform `apply` should do what the plan says will happen.

### Actual Behavior

1. Terraform `plan` reports two resources will be destroyed.
2. Terraform `apply` only destroys one resource.

### Steps to Reproduce

1. Check out repository: `git clone git@github.com:robin-norwood/terraform-target-count.git`
1. Change directory: `cd terraform-target-count`
1. Initialize the repo: `terraform init`
1. Apply config: `terraform apply -auto-approve`
   * Three each of "foo", "bar", and "baz" will be created, as expected.
1. Apply change, targeting the last "bar" resource: `terraform apply -var=resource_count=2 -target=null_resource.bar[2]`
   * Expected result: Only the targeted resource (`null_resource.bar[2]`) will be destroyed.
   * Actual result: The plan says two resources (`null_resource.bar[2] and null_resource.foo[2]`) will be destroyed, but accepting the plan only destroys one resource (`null_resource.bar[2]`).

### Additional Context

I ran into this with a more complex/real world use case. Starting from [an example repo containing a VPC & EC2 instances](https://github.com/hashicorp/learn-terraform-resource-targeting)...

1. Apply the config: `terraform apply`
1. Update the instance count: Add a `terraform.tfvars` with the contents:
    ```
    instance_count = 5
    ```
1. Apply the change: `terraform apply`.
1. Reduce the number of instances to three in `terraform.tfvars`
   ```
   instance_count = 3
   ```
1. Apply the change to only one of the ELB attachments: `terraform apply -target=module.elb_http.module.elb_attachment.aws_elb_attachment.this[4]`
   * What I expect: Only the targeted ELB attachment is planned for destroy.
   * What I see: The targeted ELB attachment and both instances are shown in the plan - but accepting the plan results in only the ELB attachment being destroyed.

### References

- #25836

**Comment by apparentlymart** [comment] 2021-02-24 23:08
Thanks for reporting this, @robin-norwood.

Based on nothing other than thought experiment, I have a theory as to why this is happening:

* For most of the work Terraform does until the actual apply step it's thinking only about entire resources (as opposed to individual resource instances), because handling `count` and `for_each` requires expression evaluation and thus can only happen _during_, rather than _before_ the graph walk. The plan graph in particular only includes whole resources.
* However, during the apply phase we _do_ get an opportunity to filter out the individual instances based on `-target` _just in time_ before taking any actions. I don't believe we actually _intended_ to support targeting individual instances there, but it happens to work out in practice (this quirky behavior notwithstanding) just because the resource address syntax allows for specifying instance indices and the apply-time filter knows how to honor them.

To be honest, I think the behavior here that would most match the current runtime implementation of targeting would be for it to be prohibited to `-target` individual instances at all, and only allow targeting whole resources. That would be a pretty harsh change in behavior given that it has been _more or less_ working though, and so perhaps instead we could consider options that might allow us to tweak the plan after the fact to filter out any actions that won't ultimately match the target at apply time. That would still not be a total solution -- fundamentally, planning is still a whole-resource-oriented operation -- but it would at least make the plan output a more honest description of what will actually happen during the apply step.

Other approaches might be possible too, and it's also possible that my thought experiment is misguided and there's a different root cause here entirely, but hopefully this rambling is somewhat useful for someone who digs deeper into this report.

**Comment by jbardin** [comment] 2021-02-25 13:40
@apparentlymart, your thought experiment is spot on here! This is a slightly different manifestation of the same behavior as #25836. 

I also thought filtering the changes might be able to work, but it would have to be done within the resource expansion so as to not have any secondary effects.

**Comment by jbardin** [comment] 2021-03-01 14:52
Closing as a duplicate of #25836, which also demonstrates the much more hazardous side-effect of running destroy provisioners for resources not being actually destroyed. 

@imaginarynik, What you are describing sounds roughly like how terraform currently operates. The problems you are referring to don't sound related to the issue described here, but feel free to create a thread in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-03-01 14:52 UTC
Labels: bug, core
