### ISSUE TITLE
Feature Request: (aws provider) shared_config_file

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/terraform#14249] opened 2017-05-05 19:13 UTC
I am thinking it would be nice to implement `shared_config_file` in the aws provider stanza in the same way `shared_credentials_file` is already implemented. The primary use case of this that I envision would be to dynamically fetch the default region (if set) for whatever profile is in use.

So for example, instead of something like this:

```
provider "aws" {
  shared_credentials_file = "${pathexpand("~/.aws/credentials")}"
  region                  = "${var.region}"
}
```

...it would instead be possible to do this:

```
provider "aws" {
  shared_credentials_file = "${pathexpand("~/.aws/credentials")}"
  shared_config_file      = "${pathexpand("~/.aws/config")}"
}
```

**Comment by ashb** [comment] 2017-05-12 13:03
Duplicate of #7192 (or possibly an extension of that to allow using a custom shared config file?)

**Closed** 2017-06-13 20:32 UTC
Labels: enhancement, provider/aws
