### ISSUE TITLE
aws_lambda_layer_version always creates new version even though file doesn't change

### ISSUE THREAD

**Issue by RJKeane2000** [hashicorp/terraform#31451] opened 2022-07-15 20:58 UTC
I'm creating an aws_lambda_layer_version resource that is associated to a certificate file. If I run the terraform with a local backend, terraform will create the lambda layer version the first time as expected.  If I apply the terraform a second time, it correctly recognizes that the file has not changed and will not create a new version. 

However, if I use the same terraform (different layer name) but set a tfe backend, tfe will create a new version of the lambda layer version every time I apply the terraform.  I downloaded  the state files in the tfe workspace from back to back runs and compared them. The attributes of the aws_lambda_layer_version instance are identical except for the "version" and the "created_date".  This includes the "source_code_hash" and "source_code_size" being identical values. 

My terraform looks similar to the following (changed sensitive names):

```
data "archive_file" "layer" {
  type        = "zip"
  source_file = local_sensitive_file.sample.filename
  output_path = "${path.module}/layer.zip"
}

resource "aws_lambda_layer_version" "layer" {
  filename            = "${path.module}/layer.zip"
  layer_name          = var.layer_name
  compatible_runtimes = var.compatible_runtimes
  source_code_hash    = data.archive_file.layer.output_base64sha256
}

data "http" "myFile" {
  url = "https://mydomain.com/-/raw/main/myFile.crt"
}

resource "local_sensitive_file" "sample" {
  content  = data.http.myFile.response_body
  filename = "${path.module}/myFile.crt"
}
```

The key to reproducing this issue is to run with Terraform Enterprise (tfe).

Thank you for any help you can provide.

**Comment by apparentlymart** [comment] 2022-07-15 23:11
Hi @RJKeane2000!

Are you using the [remote operations](https://www.terraform.io/cloud-docs/run/remote-operations) feature of Terraform Cloud, where Terraform Core is actually running in a remote agent behind the Terraform Cloud API, rather than locally on your machine?

When you use remote operations, Terraform CLI needs to upload a snapshot of the configuration directory and send it to the remote server to run, and then the remote server extracts that archive into the remote agent's filesystem before running Terraform Core.

I wonder if the process of archiving and then extracting the contents of your working directory is causing the content or the metadata of `myFile.crt` to change for each run, therefore causing `data.archive_file.layer` to generate a different archive and therefore force creation of a new layer version with that new archive.

**Comment by RJKeane2000** [comment] 2022-07-16 03:30
Hi @apparentlymart,

Yes, the execution mode of my tfe workspace is set to remote.  

I see your point on the impact of extracting the archive on a remote agent but wouldn't the new sha of the zip file have been recorded in the state file? All the attributes in the aws_lambda_layer_version instance are the same in the state file from current version of the state file to the previous version other than the "version" and the "created_date".  Because the state file is remote as well, I would think it would reflect the information of the file from the point of view of the remote agent's filesystem assuming that's where the state file is updated from. 

Thank you for such a quick reply.  Please let me know if you'd like me to try anything to help debug this.

**Comment by RJKeane2000** [comment] 2022-07-18 19:11
Should I open this issue under https://github.com/hashicorp/terraform-provider-aws and close it here?

**Comment by apparentlymart** [comment] 2022-07-18 19:45
Hi @RJKeane2000,

It sounds like something about the process of uploading configuration into the remote execution environment of Terraform Cloud is changing the files in a way that affects `archive_file`'s result. I think then what we would need to determine is what exactly the Terraform Cloud upload is changing.

My first idea was that perhaps the last modified time of the files being written to the remote system is the time of extraction of the configuration snapshot, and so it naturally varies between runs. However, I thought that the `hashicorp/archive` provider would intentionally exclude modified timestamp information from the archives it produces in order to avoid this sort of problem, allowing the checksums to be based only on the content.

Is it possible for you to inspect the zip files that `archive_file` is creating and see how they differ from one run to the next? Your current configuration doesn't seem to save the zip file anywhere other than local disk, and so you won't be able to obtain that file from outside the Terraform Cloud execution environment, but I wonder if you could temporarily add a new resource to save the zip file somewhere externally visible, such as an S3 bucket, and then you could run two sequential runs and capture the archive file after each one and check to see if they exactly match, byte-for-byte. If they _don't_ match, then it would be helpful to study each file and see how they differ: for example, are the last-modified times different between the archives, or are the files recorded in a different order in the file, or something else?

I expect this will probably end up leading to a change in [the archive provider's repository](https://github.com/hashicorp/terraform-provider-archive) to make it normalize away whatever is different between the two zip files, but let's keep this issue here for the moment while we're debugging because it might also potentially lead to changing the Terraform Cloud integration in this repository or the Terraform Cloud server code itself, depending on what the cause turns out to be.

Thanks!

**Comment by RJKeane2000** [comment] 2022-07-18 19:54
Great idea @apparentlymart!  I'll load the archive files into an S3 bucket with the runs and let you know what I find. Thank you for the suggestions!

**Comment by apparentlymart** [comment] 2022-07-18 23:20
Hmm, interesting! As far as I can tell, the only thing that would explain two identical files having a different `etag` when stored in S3 is if the `etag` were more than just a checksum of the file. I think I remember that having server-side encryption enabled on an S3 bucket makes that true, and maybe there are other settings that affect how S3 calculates `etag`. Does the bucket you wrote this into have any special settings like server-side encryption turned on, that might therefore make the `etag` not be an MD5 hash of the cleartext?

**Comment by RJKeane2000** [comment] 2022-07-19 13:19
Great catch! Encryption is turned on for that S3 bucket. I'll try writing the files to a S3 bucket without encryption.

**Comment by RJKeane2000** [comment] 2022-07-19 13:43
@apparentlymart I just captured data.archive_file.layer.output_md5 as an output variable and had it write out in the console. It is the same for the back to back runs. Both runs created a new Lambda layer.

**Comment by RJKeane2000** [comment] 2022-07-19 15:13
I checked the other attributes on the data archive_file and they were the same between back to back runs.

file_md5, output_base64sha256, output_sha, output_size

**Comment by RJKeane2000** [comment] 2022-07-19 16:24
Hi @apparentlymart,

I did some experimenting this morning. Instead of creating the local file dynamically, I copied the resulting file into the project and referred to it directly. This created a different output_base64sha256 from the data archive_file.  

Having the file locally instead of dynamically creating it, results in terraform not recreating the aws_lambda_layer_version in back to back runs. 

I noticed with oldside runs, it's the source_code_hash that is triggering the replacement. I also noticed that terraform deletes the local_sensitive_file.cert resource as it comparing current state to stored state. I think local_sensitive_file is deleted because the file it refers to is not part of the project. It seems like creating of "certs.crt" each run results in a different output_base64sha256 from the archive_file.

Oldside:

resource "local_sensitive_file" "certs" {
  content  = data.http.certs.response_body <--- Retrieved file with http call
  filename = "${path.module}/certs.crt"
}

data "archive_file" "layer" {
  type        = "zip"
  source_file = local_sensitive_file.certs.filename  <---- Change here
  output_path = "${path.module}/layer.zip"
}


Newside:
data "archive_file" "layer" {
  type        = "zip"
  source_file = "${path.module}/certs.crt"  <----  Change here
  output_path = "${path.module}/layer.zip"
}

**Comment by RJKeane2000** [comment] 2022-07-19 16:49
This does explain why it doesn't recreate the lambda layer when I ran locally. The dynamically created file would have still existed in the directory so the contents would be overridden but the create_date would remain the same. 

Running tfe would cause the file to always get created fresh because we get a new remote agent each time we run.

**Comment by RJKeane2000** [comment] 2022-07-19 19:37
I was able to reproduce the issue when running locally just by deleting the generated file after running "terraform apply" then running "terraform apply" again.

**Comment by apparentlymart** [comment] 2022-07-19 23:19
Hi @RJKeane2000! Thanks for the additional context.

I'm going to admit that I'm feeling a little lost at this point, since it feels like some of the more recent things you learned conflicted with things we learned earlier in the discussion. For example, you started by saying that this behavior only occurred when using the Terraform Cloud remote operations feature, but your most recent comment says it also happens in local operations mode, and it isn't clear to me what changed along the way which led to the different behavior. :thinking: 

Perhaps I can catch up with your current understanding if you can share the full output of running `terraform apply` twice, where the second one shows Terraform planning a change that shouldn't have needed to happen. The raw plan output and apply output will hopefully allow me to more quickly understand what's going on, since I'm accustomed to interpreting plan output and mapping that backwards to the underlying Terraform behavior that led to it.

In case your configuration or the provider schema causes any of the checksums to be hidden behind `(sensitive value)` placeholders, it would also help if you could let me know which of them are the same and which are different just so I can follow exactly where the difference first arises and where it propagates to from there.

**Comment by RJKeane2000** [comment] 2022-07-20 03:24
Hi @apparentlymart,

Sorry for the confusion.  I'll summarize what I've done so far.

When I ran the terraform with local backend, I was running the terraform on my laptop.  I didn't account for the fact that the file and the zip file was created on my laptop and remained after the terraform ran.  When I ran the 2nd time locally, the files were already there. According to the terraform local_sensitive_file documentation, "If the file already exists, it will be overridden with the given content."  This is different from running with a tfe backend which would always have a pristine environment in which the file and the zip file do not exist when terraform runs. 

Once I realized my environments were different between running locally and running with tfe, I tried to mimic the tfe environment by deleting the created file and the zip file from my laptop in between runs. The result is that it creates the aws_lambda_layer_version each time when running locally just like it does in the tfe environment.  The two environments also behave the same if the file that will be archived exists before the terraform runs. In this case, a new lambda layer version is not created if the file did not change.

I did find something interesting accidently.  I deleted the file that that was created with the local_sensitive_file resource. However I forgot to delete the zip file created by the archive_file data block. 

Terraform creates a new aws_lambda_layer_version if I set the source_hash from the data.archive_file block.  However, If I generated the sha like it showed in the terraform documentation, it does not create a new Lambda layer version.  See example.

```bash
resource "aws_lambda_layer_version" "layer" {
  filename            = "${path.module}/layer.zip"
  layer_name          = var.layer_name
  compatible_runtimes = var.compatible_runtimes
  source_code_hash    = "${filebase64sha256("${path.module}/layer.zip")}"  <--- Doesn't create new lambda layer version
  #source_code_hash    = data.archive_file.layer.output_base64sha256  <--- Creates new lambda layer version 
  depends_on = [local_sensitive_file.certs, data.archive_file.layer]  <-- Dependency is important if doing the filebase64sha256
}
```
Again, the zip file exists between runs but the file created by local_sensitive_file does not. The resulting hash is the same from both techniques. I'm wondering if terraform isn't able to calculate the value of data.archive_file.layer.output_base64sha256 at the point where it's determining whether to create a new version of the lambda layer.

We can't use the filebase64sha256 technique if the zip file does not exist when terraform runs. You showed that in another issue. 

Thanks again for your help!

**Comment by RJKeane2000** [comment] 2022-07-20 15:22
Hi @apparentlymart,

Here is the cleaned up terraform plan. Note that the source_code_hash isn't known until after the apply. I think that is the key to why the lambda layer is always being created. It makes sense to me now that I look at it. Terraform won't know the source code hash on a dynamically created file until it is created so it must assume that it must create the new layer. I think Terraform is behaving as designed. What do you think? 

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # module.layers.data.archive_file.layer will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "archive_file" "layer" {
      + id                  = (known after apply)
      + output_base64sha256 = (known after apply)
      + output_md5          = (known after apply)
      + output_path         = "module/layer.zip"
      + output_sha          = (known after apply)
      + output_size         = (known after apply)
      + source_file         = "module/bundle.crt"
      + type                = "zip"
    }

  # module.layers.aws_lambda_layer_version.layer must be replaced
-/+ resource "aws_lambda_layer_version" "layer" {
      ~ arn                         = "arn:aws:lambda:us-east-1:xxxxxxxxxxxx:layer:self-signed-certs:4" -> (known after apply)
      - compatible_architectures    = [] -> null
      ~ created_date                = "2022-07-20T03:01:41.648+0000" -> (known after apply)
      ~ id                          = "arn:aws:lambda:us-east-1:xxxxxxxxxxxx:layer:self-signed-certs:4" -> (known after apply)
      ~ layer_arn                   = "arn:aws:lambda:us-east-1:xxxxxxxxxxxx:layer:self-signed-certs" -> (known after apply)
      + signing_job_arn             = (known after apply)
      + signing_profile_version_arn = (known after apply)
      ~ source_code_hash            = "H/bsVW3g00x6LFVchhXRi6/bla9CG8t/C1fsInn+flQ=" -> (known after apply) # forces replacement
      ~ source_code_size            = 96040 -> (known after apply)
      ~ version                     = "4" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

  # module.layers.local_sensitive_file.certs will be created
  + resource "local_sensitive_file" "certs" {
      + content              = (sensitive value)
      + directory_permission = "0700"
      + file_permission      = "0700"
      + filename             = "module/bundle.crt"
      + id                   = (known after apply)
    }

Plan: 2 to add, 0 to change, 1 to destroy.
```

**Comment by apparentlymart** [comment] 2022-07-20 20:44
Hi @RJKeane2000!

Indeed, I think you are correct that the `(known after apply)` is the crucial point here. If Terraform cannot prove that the new value is the same as the old value then it must conservatively assume that it will be different in order to present the most thorough plan.

As you say, Terraform does seem to be behaving as designed here, and it did give a little feedback in the plan as to what might be causing this:

```
  # module.layers.data.archive_file.layer will be read during apply
  # (depends on a resource or a module with changes pending)
```

Terraform's analysis for this error message is unfortunately not very detailed at the moment and so it's not able to say exactly _which_ resource or module has changes pending, but from your configuration shared earlier I can see that it depends on `resource "local_sensitive_file" "certs"`, which will always have a "will be created" plan in this case because the `module/bundle.crt` file cannot survive between two runs on different systems. This situation is what the warning callout on [the `local_sensitive_file` documentation](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/sensitive_file) is talking about, although in this case it's more than just "noise" and is actually affecting the behavior, because you have a downstream object that depends on the plan for this one:

> When working with local files, Terraform will detect the resource as having been deleted each time a configuration is applied on a new machine where the file is not present and will generate a diff to re-create it. This may cause "noise" in diffs in environments where configurations are routinely applied by many different users or within automation systems.

At the risk of stepping outside the bounds of what I have recent expertise with, in a previous job when I was using Terraform to deploy lambda functions I found I was able to avoid this troublesome pattern of just-in-time modifying the deployment artifact by placing the Terraform-decided values in another location aside from the actual function source code. The most common pattern I followed was to pass in data as environment variables, and I think that could _potentially_ be okay here if `main.crt` is just a TLS _certificate_, and doesn't contain a private key. If it does contain a private key then IIRC lambda environment variables are not appropriate for that because the Lambda API allows retrieving them in cleartext, and so my backup plan would be to store them in something like AWS SSM Parameter Store and instead pass the parameter name or other similar identifier in as the environment variable, and then have the Lambda function use access conferred by its IAM role to access that external data.

I don't there's anything specific to change about Terraform Core to improve what you encountered here though, since as you said this behavior is a logical consequence of Terraform's normal dependency handling. Given that, I'm going to close this issue though if you have some further questions or want to discuss other possibilities then we could continue in a topic over in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), which is a good place for ongoing discussion that doesn't necessarily have to be associated with a defect in this repository.

Thanks!

**Closed by apparentlymart** 2022-07-20 20:44 UTC

**Comment by RJKeane2000** [comment] 2022-07-21 13:31
Thank you for your time and all your insights @apparentlymart!  Have a great week!

**Comment by hueyyu** [comment] 2022-07-22 14:05
I am having the same issue but I don't think this is a work-as-design.
My terraform script has the sequence below. Both aws_s3_bucket and aws_lambda_layer_version use output of archive_file as hash. When contents of archive source do not change, the aws_s3_bucket will not produce new version on every apply but the aws_lambda_layer_version produce new version on every apply. Since both use output of the same object created at runtime, they should behave the same but they are not.

data "archive_file" "nodejs_layer" {
  type              = "zip"
  source_dir    = "src/node_modules"
  output_path = "node-layer.zip"
}
resource "aws_s3_object" "nodejs_layer" { 
  bucket          = "my_source_bucket"
  key                = "nodejs-layer.zip"
  source           = data.archive_file.nodejs_layer.output_path
  source_hash = data.archive_file.nodejs_layer.output_md5
  depends_on  = [data.archive_file.nodejs_layer]
}
resource "aws_lambda_layer_version" "nodejs_layer" 
{ 
  s3_bucket                  = aws_s3_object.nodejs_layer.bucket
  s3_key                        = aws_s3_object.nodejs_layer.key
  s3_object_version     = aws_s3_object.nodejs_layer.version_id
  source_code_hash    = data.archive_file.nodejs_layer.output_base64sha256
  layer_name                 = "lambda-nodejs-layer"
  compatible_runtimes = ["nodejs12.x"]
  depends_on  = [
    aws_s3_object.nodejs_layer
  ]
}

**Comment by apparentlymart** [comment] 2022-07-22 15:40
Hi @hueyyu,

This issue is now closed, but if you'd like to discuss what's going on with the example you shared here then I would suggest starting a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), which is a better venue for ongoing discussions. Thanks!
