### ISSUE TITLE
Imported terraform modules are containing unnecessary files. 

### ISSUE THREAD

**Issue by PrzemyslawSwiderski** [hashicorp/terraform#26389] opened 2020-09-25 23:35 UTC
Hi,
currently when importing module from git, for example:
```
module "module1" {
  source = "git::https://example.com/modules.git//module?ref=v1.2.0"
}
module "module2" {
  source = "git::https://example.com/modules.git//module2?ref=v1.2.0"
}
```
terraform will clone the whole repository twice (even with `.git` directory) to a `.terraform/modules` catalog.
It leads to storing additional files, not related to module specified in source.
Moreover, some IDEs (ex. Intellij) can detect cloned git repositories what makes a mess in project.

Shouldn't Terraform delete unnecessary files and store only modules pointed in source parameter?

**Comment by waqark3389** [comment] 2020-09-29 16:25
The 2 paths are 2 different repos so it treats them as 2 separate things

I checked locally and I cant see it creating .git - have you checked this in somehow? It doesn't know what is necessary and what isn't

**Comment by danieldreier** [comment] 2020-09-29 17:14
@PrzemyslawSwiderski Thanks for suggesting this - I think that as a feature request this makes sense - to re-use existing previously-cloned git repos if they are actually the same one - but that's not something we currently try to do. Modules exist independently of each other, right now. I'm going to label this as an enhancement request because it seems like an interesting idea, but I'm not considering it a bug because it's not broken and not at odds with the documentation we provide.

**Comment by apparentlymart** [comment] 2020-09-29 21:04
The unit of installation for a module is a so-called "module package", which has a different definition depending on which source type you are working with but for the Git source type is an entire git repository. For `.zip` archives retrieved over HTTP it is the archive itself, as another example.

Terraform's current intended behavior is to detect that both of those addresses have the same source "package", `git::https://example.com/modules.git?ref=v1.2.0`, and then to `git clone` only the first one it encounters, before populating the second one just by deep-copying the first directory to the second location.

The `//module` syntax in the source string allows you to tell Terraform to [look somewhere other than the root of the package](https://www.terraform.io/docs/modules/sources.html#modules-in-package-sub-directories) to find the module you intend to use, but Terraform must still retrieve and install the entire package because a package can potentially contain multiple interdependent modules, such as if the module at `//module` contained a `module` block with `source = "../module2"`.

Terraform also installs the entire contents of the package, rather than just the `.tf` files, because it's common for a Terraform module to refer to other files in its package using functions like [`file`](https://www.terraform.io/docs/configuration/functions/file.html), or resource types like `aws_s3_bucket` that can read files directly from the local filesystem.

---

It is true that Terraform's git module installer could, in principle, export the contents of the latest revision in the repository rather than cloning the entire repository. I know that some authors find it convenient that the directory in `.terraform/modules` contains a functional git repository because they will sometimes, during development/testing, use commands like `git checkout` to switch to other branches that are not yet merged. For that reason, if we were to change the behavior we'd need to consider the impact on those whose workflow is currnetly relying on these directories being git repositories.

Terraform's module installer could also in principle use symlinks rather than deep copies when it notices an opportunity to reuse a module it's already installed. Right since the original introduction of modules in Terraform it has kept the code for each `module` block separately from the others, so switching to a shared model may again have implications for those who have come to rely on them being distinct for a productive development workflow, but it seems technically feasible to try to use symlinks here (in similar vein as for the provider installer) as long as we can do some user research first to develop some confidence that the long-standing current behavior is not crucial to someone's workflow.

**Closed** 2022-06-14 11:46 UTC
Labels: enhancement
