### ISSUE TITLE
terraform providers lock doesn't ignore hashes in .terraform.lock.hcl

### ISSUE THREAD

**Issue by dacut** [hashicorp/terraform#27810] opened 2021-02-17 20:09 UTC
Running `terraform providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=windows_amd64 -platform=darwin_amd64` fails is a `.terraform.lock.hcl` file is already in place. This appears to be contrary to the documentation from `terraform providers lock -help`, which states:

>   The "providers lock" subcommand addresses that by updating the lock file
>   based on the official packages available in the origin registry, **ignoring
>   the currently-configured installation strategy.** 

Instead, it rejects the attempt to add additional providers:

```
Error: Could not retrieve providers for locking

Terraform failed to fetch the requested providers for linux_amd64 in order to
calculate their checksums: some providers could not be installed:
- registry.terraform.io/hashicorp/aws: the current package for
registry.terraform.io/hashicorp/aws 3.20.0 doesn't match any of the checksums
previously recorded in the dependency lock file.
```

This can be worked around by blasting away `.terraform.lock.hcl`: `rm .terraform.lock.hcl`, but ideally I would want it to respect the existing platform hash and just install the new platforms.

This is probably a limitation in the file format for `.terraform.lock.hcl` -- might need separate hash sections for separate platforms.

### Terraform Version
```
Terraform v0.14.6
```

### Terraform Configuration Files
No real config; here's my ~/.terraformrc:
```terraform
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
```

### Debug Output
https://gist.github.com/dacut/88a1f071f0b4bb2363b01660cf50579b

### Expected Behavior
Terraform ignores the constraints in `.terraform.lock.hcl` and updates the file with the new providers.

### Actual Behavior
Terraform errors out with the above error.

### Steps to Reproduce
```
terraform init
terraform providers lock -platform=linux_arm64 -platform=llinux_amd64 -platform=windows_amd64 -platform=darwin_amd64
```

**Comment by mildwonkey** [comment] 2021-02-25 15:33
Hi @dacut , I'm sorry you're running into this issue, thank you for reporting.

I'm unable to reproduce this issue using terraform v0.14.6. Can you share a reproduction configuration and the exact steps you were running ? 

I would also like to point out that while the documentation does say the `providers lock` command ignore the installation strategy, it does *not* ignore the pre-existing lock file and hashes. All that is saying that the lock command queries the registry even if you are using a different plugin installation method. If there was an actual provider checksum mismatch (for whatever reason), it would result in an error.

**Comment by chancez** [comment] 2021-03-03 18:02
I'm hitting this issue too. All I'm trying to do is upgrade from 0.13 and get my lock files created with all platform hashes. I also deleted my `plugin_cache_dir` before running the `terraform init & provider lock` commands.

**Comment by dacut** [comment] 2021-03-05 21:43
Hi @mildwonkey -- I've not abandoned this; will get more detailed instructions to you soonish. Been swamped at work. Thanks!

**Comment by mildwonkey** [comment] 2021-04-30 16:19
I'm going to close this, since we weren't able to get a reproduction yet, but if you are still experiencing a reproducible problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by mildwonkey** 2021-04-30 16:19 UTC
Labels: bug, new, v0.14, waiting for reproduction
