### ISSUE TITLE
Invalid dynamic for_each value

### ISSUE THREAD

**Issue by pkrauss-prot** [hashicorp/terraform#34093] opened 2023-10-16 19:26 UTC
### Terraform Version

```shell
Terraform v1.6.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.55.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Terraform Configuration Files

```
dynamic "admin_ssh_key" {
    for_each = var.ssh_key_value_init != null ? tomap({enabled: true}) : tomap({})

    content {
      username   = var.admin_username_init
      public_key = var.ssh_key_value_init
    }
  }
```

### Debug Output

2023-10-16T15:20:48.587-0400 [ERROR] vertex "module.linux_default.azurerm_linux_virtual_machine.linux_virtual_machine" error: Invalid dynamic for_each value

### Expected Behavior

conditional `for_each` should be treated the same depending on outcome as it did pre 1.6.x

### Actual Behavior

`for_each` is giving errors for valid types.

### Steps to Reproduce

requires a `for_each` dynamic block and terraform version 1.6.x
1. terraform init
2. terraform apply
3. error with conditional `for_each`

### Additional Context

pre terraform version 1.6.x this worked as expected:

```
dynamic "source_image_reference" {
    for_each = var.os_configuration.source_image_id == null ? [1] : []
...
```

post terraform version 1.6.x this no longer works. When used in a conditional, no iterable collection works. However if i swap out the conditional for either `tomap({enabled: true})`  ( or `[1]`) or `tomap({})` (or `[]`) they work fine.

**Comment by jbardin** [comment] 2023-10-16 21:34
Hi @pkrauss-prot,

Thanks for filing the issue. Is there any more context to the error message present in the cli? Also is it possible any of the conditional arguments contains a sensitive value? I suspect this is a duplicate of #29744, however we have discovered that there were cases where the sensitivity was not caught correctly in prior Terraform versions and are only showing up now, albeit with unhelpful error text about incorrect types.

**Comment by alexpilon666** [comment] 2023-10-16 22:26
@jbardin we have the same issue, and in our case the conditional argument does contain sensitive values.

**Comment by alexpilon666** [comment] 2023-10-16 22:39
For context: I've tested every Terraform version from v1.4.6 (the one we currently had installed in our CI/CD pipelines) up to v1.6.1 (where the issue was first detected): From v1.4.6 up until v1.5.7 this works. Starting at v1.6.0 the same exact code starts throwing the errors mentioned above.

**Comment by pkrauss-prot** [comment] 2023-10-17 00:51
> Hi @pkrauss-prot,
> 
> Thanks for filing the issue. Is there any more context to the error message present in the cli? Also is it possible any of the conditional arguments contains a sensitive value? I suspect this is a duplicate of #29744, however we have discovered that there were cases where the sensitivity was not caught correctly in prior Terraform versions and are only showing up now, albeit with unhelpful error text about incorrect types.

I put the value of the conditional in the issue that is throwing "invalid dynamic for_each value", pretty clear there are no sensitive values.

```
for_each = var.ssh_key_value_init != null ? tomap({enabled: true}) : tomap({})
```

This is very easily reproducible you just need a dynamic for_each with a conditional that returns a valid type. The issue mentioned is similar but this is under different circumstance.

**Comment by pkrauss-prot** [comment] 2023-10-17 01:05
@jbardin would it help if I just created a public repo with something using a dynamic block and conditional, that simply can be ran with a `terraform apply`. I can make time tomorrow at work for this as TFC defaults workspaces to the latest 1.6.x release, which put this error front and center.

**Comment by jbardin** [comment] 2023-10-17 13:51
Thanks for verifying @pkrauss-prot!

**Closed by jbardin** 2023-10-17 13:51 UTC
Labels: bug, waiting-response, new
