### ISSUE TITLE
data could not be decoded from the state: a bool is required

### ISSUE THREAD

**Issue by venhow** [hashicorp/terraform#25983] opened 2020-08-25 02:00 UTC
terraform upgrading from 0.12 to 0.13, alicloud, terraform init && terraform apply got an error:

terraform init && terraform apply
Initializing modules...

Initializing the backend...

Successfully configured the backend "oss"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Using previously-installed aliyun/alicloud v1.93.0
- terraform.io/builtin/terraform is built in to Terraform
- Using previously-installed -/alicloud v1.93.0

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* -/alicloud: version = "~> 1.93.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: Invalid resource instance data in state

  on ../../../../modules/kubernetes/main.tf line 39:
  39: resource "alicloud_cs_managed_kubernetes" "k8s" {

Instance module.cluster.alicloud_cs_managed_kubernetes.k8s data could not be
decoded from the state: a bool is required.

**Comment by alisdair** [comment] 2020-08-25 15:39
This issue seems to be a duplicate of #25752, which has a fix merged and will be released as part of 0.13.1. Closing as a duplicate.

**Closed by alisdair** 2020-08-25 15:39 UTC
Labels: bug, new

**Comment by venhow** [comment] 2020-08-26 01:51
okay, thanks.
