### ISSUE TITLE
Expected an attribute value, introduced by an equals sign ("=")

### ISSUE THREAD

**Issue by piersf** [hashicorp/terraform#25363] opened 2020-06-23 22:55 UTC
Hello there,

I'm encountering the below-described error today and I don't see why it's failing. I've spent several hours checking anything I could think of but wasn't able to see or understand why this fails. Hopefully, someone knows what's the issue here.

### Terraform Version

```
I'm using version 0.12.13 
But the issue appears up to the latest stable version 0.12.26
```

### Terraform Configuration Files
I have the below config folder structure:
```
app:
  main.tf
  vars.tf
  modules:
    ebs-volume:
      main.tf
      var.tf
```
I have the below module defined in `app/modules/ebs-volume/main.tf`:
```hcl
resource "aws_ebs_volume" "ebs_volume" {
  for_each = var.volumes
  availability_zone       = lookup(each.value, "availability_zone", null)
  encrypted               = lookup(each.value, "encrypted", null)
  iops                    = lookup(each.value, "iops", null)
  # multi_attach_enabled    = lookup(each.value, "multi_attach_enabled", null)
  size                    = lookup(each.value, "size", null)
  snapshot_id             = lookup(each.value, "snapshot_id", null)
  # outpost_arn             = lookup(each.value, "outpost_arn", null)
  type                    = lookup(each.value, "type", null)
  kms_key_id              = lookup(each.value, "kms_key_id", null)
  tags                    = lookup(each.value, "tags", null)
}
```
with the below variable(structural type) defined in  `app/modules/ebs-volume/vars.tf`:
```hcl
variable "volumes" {
  type = map(object({
    availability_zone     = string,
    encrypted             = bool,
    iops                  = string,
    # multi_attach_enabled  = bool,
    size                  = number,
    snapshot_id           = string,
    # outpost_arn           = string,
    type                  = string,
    kms_key_id            = string,
    tags                  = map(string)
  }))
  default = {
    {
      availability_zone     = "eu-west-1a"
      encrypted             = true
      iops                  = null
      # multi_attach_enabled  = false
      size                  = 30
      snapshot_id           = null
      # outpost_arn           = null
      type                  = "gp2"
      kms_key_id            = null
      tags                  = {"Default" = "NOT_SET"}
    }                                                   <---- line 27 mentioned in the error output below
  }
}
```
From `app/main.tf` I call the above module:
```hcl
module "name_volume" {
  source = "./modules/ebs-volume"
  volumes  = {
    gp2-eu-west-1b = {
      availability_zone = "eu-west-1b", 
      encrypted         = true, 
      size              = 40,   
      type              = "gp2",
      tags              = map("Name", "test")
    }
  }
}
```

When i ran `terraform plan`, it fails with the below error:

```hcl
Initializing modules...

Error: Missing attribute value

On ./modules/ebs-volume/vars.tf line 27: Expected an
attribute value, introduced by an equals sign ("=").


Error: Missing attribute value

On ./modules/ebs-volume/vars.tf line 27: Expected an
attribute value, introduced by an equals sign ("=").
```

### Expected Behavior
The `plan` task should not fail

### Steps to Reproduce
1. Use the above configuration
2. Run `terraform plan`

### Additional Context
If I remove the default value from the variable and pass all key/values that the structural type object requires, it works and it does not fail. So, something's not right with the default value or the way I'm assigning a default value?

I tried also adding the keys in double-quotes as I read somewhere that in `0.12` sometimes this made a difference, but this didn't fix anything.

Any idea/explanation on why is this happening and how can I make it work? What am I missing here?

Thank you in advance!
Cheers

**Comment by apparentlymart** [comment] 2020-06-25 01:23
Hi @piersf,

This error seems to be correct, because the default value for your variable is missing a map key:

```hcl
  default = {
    MAP_KEY_NEEDED_HERE = {
      availability_zone     = "eu-west-1a"
      encrypted             = true
      iops                  = null
      # multi_attach_enabled  = false
      size                  = 30
      snapshot_id           = null
      # outpost_arn           = null
      type                  = "gp2"
      kms_key_id            = null
      tags                  = {"Default" = "NOT_SET"}
    }                                                   <---- line 27 mentioned in the error output below
  }
```

If you want to set a default value for this map, you'll need to decide on a key to use for the element in the map. Alternatively, you could set the default to be `{}` if you want the default to be an _empty_ map, which then avoids the need to set either a key or a value.

Terraform is working as intended here, so I'm going to close this. If you have any follow-up questions about this, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core)! There's several people monitoring that forum and answering questions, including me, and I'm happy to talk some more about the details of this behavior over there if you'd like.

**Closed by apparentlymart** 2020-06-25 01:23 UTC
