### ISSUE TITLE
Another bug during apply

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10371] opened 2016-11-25 17:05 UTC
I am not sure whether this is how you expect your users to use this, but it appears that almost everything I do results in these kinds of issues:

[terraform2.txt](https://github.com/hashicorp/terraform/files/613663/terraform2.txt)

In this case I was removing some subnets out of some AZs. 

`terraform apply` again (two times) did not help. Is it a mistake to use `terraform` considering there are 1442 open issues of which a substantial amount appears to be bugs.

**Comment by cblecker** [comment] 2016-11-25 18:59
Can you please provide more details as to the configuration you were using when you encountered this error (obfuscating any private details)?

**Comment by mitchellh** [comment] 2016-11-25 20:12
@fubarbaz I haven't had a chance to look at your issue yet but to answer your last question:

Perhaps, but is it a mistake to use the Go language since there are ~2,300 issues? Docker cause there are ~1,800? Kubernetes because there are ~4,600? etc. Issue count is a poor measure of project stability. As alternate data points: we only have ~90 core bugs currently open. Or, we've closed over 530 issues in the past 30 days. As you can see, there are many dimensions with which you can judge a project and it isn't so cut and dry. :)

**Comment by mitchellh** [comment] 2016-11-25 20:26
Also, we fixed a case of this exact error message (destroy: old false new true) in 0.7.13 (actually 0.7.12 but .13 is the latest), so its possible that will just fix your issue, but I'm not 100% certain if its identical.

As @cblecker said: do you mind sharing reproduction steps from a clean state?

**Comment by fubarbaz** [comment] 2016-11-25 23:59
OK, I will try with 0.7.13 (I tried to build 0.8.rc* before, but that didn't work) again and report back in a couple of days.

**Comment by mitchellh** [comment] 2016-11-26 00:01
If 0.8 RC didn't work it is unlikely 0.7.13 will work since the former is based on the latter. In that case we simply need a reproduction case and we can certainly fix this. Thanks!

**Comment by mitchellh** [comment] 2016-12-01 14:51
This looks like its fixed with #10455! Thanks!

**Closed by mitchellh** 2016-12-01 14:51 UTC
Labels: bug, core, waiting-response
