### ISSUE TITLE
De-duplicate module sources

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#31422] opened 2022-07-11 23:48 UTC
### Current Terraform Version

```
v1.2.4
```

### Use-cases

We have a single repo that we store all of our shared Terraform modules in. The reason that we do this is to enable us to test and version the modules as a single package where we know everything works together instead of having 500+ different repos that each hold a single modules and having to worry about incompatibility between different versions of different modules. However, I do want to point out that this problem also occurs (although at a smaller scale since the repos would all be smaller) if I had a separate repo for each module.

Right now, any time that we reference one of those modules using git source (including using https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories), it clones down a fresh copy of the entire repo. This means that if I have 100 module calls that use our shared module repo as the source, Terraform will download 100 different copies of the repo, which takes substantial time and wasted effort when Terraform could just clone the repo once, then have all of the modules point to that single cloned repo copy. 

This would be somewhat similar to how Terraform handles local paths on your file system, where `terraform init` just populates a `modules.json` with links to a single copy of the module directory instead of having separate copies of the module directory for each module. 

It would also be extremely similar to how Terraform handles providers, where it only downloads a single copy of the provider (per version) regardless of how many resources or modules use it.

Although I'm talking about this in reference to git source, this would also apply to all other remote module sources.

To put some hard numbers on this, if I use our shared modules repo via git source for 40 different module invocations, it takes ~68 seconds to initialize and results in a 469M `.terraform` directory. If I change all but one of those to use local source, the time goes down to ~16 seconds and results in a 37M `.terraform` directory. So it's basically a 75% reduction in the init time and a 90%+ reduction in disk space used in this example and the gap gets even larger if you have more module invocations.

### Attempted Solutions

We could create developer tooling on our end that clones down the shared modules repo to a single, known location and then have all of the module sources point to that known location assuming that the file system is already populated with it. That however creates caching issues and a bit worse of a developer experience if the want to for example test a git branch, it is a bit more complicated to go from a local path to a git branch from GitHub than using remote git source from the start where you can just add `?ref=<branch>`

### Proposal

At the start of a `terraform init`, Terraform could gather a list of all of the module sources. It could then find all of the unique remote sources by trimming the subdirectory (`//`) part but preserving any `?ref=` parts. For example, `git::ssh://git@example.com/network.git//modules/vpc` would become `git::ssh://git@example.com/network.git` and `git::ssh://git@example.com/network.git//modules/vpc?ref=branch` would become `git::ssh://git@example.com/network.git?ref=branch`.

Once Terraform had the unique list of remote sources, it could clone each of those sources a single time and point to them in the `modules.json` file. This would mean that the organization of the `.terraform` directory would probably be best served by a refactor to have directories by unique source instead of directories by module names. This could be done by sanitizing the remote source URL into something that can be created as a directory, similar to what you already do for plugins in the `~/.terraform.d/plugins` directory. 

This would mean that in the `modules.json` file, it would change from the current 
```json
{
  "Key": "foo",
  "Source": "git::ssh://git@github.com/example/network//modules/vpc",
  "Dir": ".terraform/modules/foo/modules/vpc"
}
```
to
```json
{
  "Key": "foo",
  "Source": "git::ssh://git@github.com/example/network",
  "Dir": ".terraform/modules/github.com/example/network/main/modules/vpc"
}
```

### References

Surprisingly I couldn't find any in the currently open issues list

**Comment by kmoe** [comment] 2022-07-12 14:29
Thanks for the well-written issue. There is an existing issue for the problem caused by creating multiple local directories for the same module source: https://github.com/hashicorp/terraform/issues/29503. While the problem is not exactly the same, the solution would be the same from Terraform's point of view, so we will consider this issue as a duplicate of #29503. Thank you!

**Closed by kmoe** 2022-07-12 14:29 UTC
Labels: enhancement, new
