### ISSUE TITLE
Lock file is created with incorrect mode when running `terraform providers lock`

### ISSUE THREAD

**Issue by steeef** [hashicorp/terraform#27838] opened 2021-02-19 16:50 UTC
### Terraform Version

```
Terraform v0.14.6
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Running the following command:

```
terraform providers lock -platform=linux_amd64 -platform=darwin_amd64
```

Should create a `.terraform.lock.hcl` file with mode `0644`.

### Actual Behavior

Running the following command:

```
terraform providers lock -platform=linux_amd64 -platform=darwin_amd64
```

Creates lock file with mode `0755`. This is later changed to `0644` when running `terraform init` on the same config, generating noise in my commit history.

### Steps to Reproduce

1. `rm -f .terraform.lock.hcl`
2. `terraform providers lock -platform=linux_amd64 -platform=darwin_amd64`
3. `stat -f %A .terraform.lock.hcl`, notice output of `755`.
4. `terraform init`
5. `stat -f %A .terraform.lock.hcl`, notice output of `644`.

### Additional Context

I haven't upraded to `v0.14.7`, but I didn't see anything in the changelog that addressed this issue, so I believe it's still broken.

### References

- https://github.com/hashicorp/terraform/pull/27205 fixes the file mode when running `terraform init`, but it looks like `terraform providers lock` uses a different code path.

**Comment by alisdair** [comment] 2021-02-19 19:50
Hi @steeef, thanks for the report. I'm unable to reproduce this issue on macOS. My umask is 0022. Here's what I tried:

```shellsession
$ cat main.tf
terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
    }
  }
}
$ rm -f .terraform.lock.hcl
$ terraform-0.14.6 providers lock -platform=linux_amd64 -platform=darwin_amd64
- Fetching hashicorp/null 3.1.0 for linux_amd64...
- Obtained hashicorp/null checksums for linux_amd64 (signed by HashiCorp)
- Fetching hashicorp/null 3.1.0 for darwin_amd64...
- Obtained hashicorp/null checksums for darwin_amd64 (signed by HashiCorp)

Success! Terraform has updated the lock file.

Review the changes in .terraform.lock.hcl and then commit to your
version control system to retain the new checksums.

$ stat -f %A .terraform.lock.hcl
644
```

Am I missing something in the reproduction steps? Can you help us to repro what you're seeing?

**Comment by steeef** [comment] 2021-02-19 21:29
Hmm. Let me try to recreate using the exact commands that I believe got me into this:

```
❯ umask
022
❯ (cd terraform/waf/production && rm -rf .terraform && terraform init && rm -f .terraform.lock.hcl && terraform providers lock -platform=linux_amd64 -platform=darwin_amd64)
❯ stat -f %A terraform/waf/production/.terraform.lock.hcl
644
```
Darn, I can't recreated it now either. Maybe the lock file was created from a version of Terraform prior to `v0.14.6`, and then I upgraded prior to running `terraform init` again?

**Comment by alisdair** [comment] 2021-02-19 21:51
That seems plausible! The bug was only backported to 0.14.5 so that would explain it.

I'm going to close this for now since it seems like the bug was fixed, but if you do reproduce it I'll be happy to reopen and investigate. Thanks again for reporting!

**Closed by alisdair** 2021-02-19 21:51 UTC
Labels: bug, waiting for reproduction
