### ISSUE TITLE
`terraform init -chdir` with implicit filesystem mirror in CWD explodes

### ISSUE THREAD

**Issue by jpluscplusm** [hashicorp/terraform#32582] opened 2023-01-26 15:48 UTC
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
```

### Terraform Configuration Files

`chdir-target/provider.tf.json`:
```json
{
    "terraform": {
        "required_providers": {
            "null": {
                "source": "hashicorp/null",
                "version": "3.2.1"
            }
        }
    }
}
```
`chdir-target/.terraform.lock.hcl`:
```terraform
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/null" {
  version     = "3.2.1"
  constraints = "3.2.1"
  hashes = [
    "h1:FbGfc+muBsC17Ohy5g806iuI1hQc4SIexpYCrQHQd8w=",
    "zh:58ed64389620cc7b82f01332e27723856422820cfd302e304b5f6c3436fb9840",
    "zh:62a5cc82c3b2ddef7ef3a6f2fedb7b9b3deff4ab7b414938b08e51d6e8be87cb",
    "zh:63cff4de03af983175a7e37e52d4bd89d990be256b16b5c7f919aff5ad485aa5",
    "zh:74cb22c6700e48486b7cabefa10b33b801dfcab56f1a6ac9b6624531f3d36ea3",
    "zh:78d5eefdd9e494defcb3c68d282b8f96630502cac21d1ea161f53cfe9bb483b3",
    "zh:79e553aff77f1cfa9012a2218b8238dd672ea5e1b2924775ac9ac24d2a75c238",
    "zh:a1e06ddda0b5ac48f7e7c7d59e1ab5a4073bbcf876c73c0299e4610ed53859dc",
    "zh:c37a97090f1a82222925d45d84483b2aa702ef7ab66532af6cbcfb567818b970",
    "zh:e4453fbebf90c53ca3323a92e7ca0f9961427d2f0ce0d2b65523cc04d5d999c2",
    "zh:e80a746921946d8b6761e77305b752ad188da60688cfd2059322875d363be5f5",
    "zh:fbdb892d9822ed0e4cb60f2fedbdbb556e4da0d88d3b942ae963ed6ff091e48f",
    "zh:fca01a623d90d0cad0843102f9b8b9fe0d3ff8244593bd817f126582b52dd694",
  ]
}
```

### Debug Output

`$ TF_LOG=trace terraform -chdir=chdir-target init -no-color`:
```
2023-01-26T15:26:34.672Z [INFO]  Terraform version: 1.3.7
2023-01-26T15:26:34.672Z [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2023-01-26T15:26:34.672Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.15.0
2023-01-26T15:26:34.672Z [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-01-26T15:26:34.672Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2023-01-26T15:26:34.672Z [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-01-26T15:26:34.672Z [INFO]  Go runtime version: go1.19.4
2023-01-26T15:26:34.672Z [INFO]  CLI args: []string{"terraform", "-chdir=chdir-target", "init", "-no-color"}
2023-01-26T15:26:34.672Z [TRACE] Stdout is not a terminal
2023-01-26T15:26:34.672Z [TRACE] Stderr is not a terminal
2023-01-26T15:26:34.672Z [TRACE] Stdin is a terminal
2023-01-26T15:26:34.672Z [DEBUG] Attempting to open CLI config file: /home/username/.terraformrc
2023-01-26T15:26:34.672Z [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-01-26T15:26:34.672Z [DEBUG] will search for provider plugins in terraform.d/plugins
2023-01-26T15:26:34.672Z [WARN]  ignoring file "registry.terraform.io/hashicorp/null/3.2.1.json" as possible package for registry.terraform.io/hashicorp/null: filename lacks expected prefix "terraform-provider-null_"
2023-01-26T15:26:34.673Z [WARN]  ignoring file "registry.terraform.io/hashicorp/null/index.json" as possible package for registry.terraform.io/hashicorp/null: filename lacks expected prefix "terraform-provider-null_"
2023-01-26T15:26:34.674Z [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/null v3.2.1 for linux_amd64 at terraform.d/plugins/registry.terraform.io/hashicorp/null/terraform-provider-null_3.2.1_linux_amd64.zip
2023-01-26T15:26:34.676Z [DEBUG] ignoring non-existing provider search directory /home/username/.terraform.d/plugins
2023-01-26T15:26:34.676Z [DEBUG] ignoring non-existing provider search directory /home/username/.local/share/terraform/plugins
2023-01-26T15:26:34.676Z [DEBUG] ignoring non-existing provider search directory /home/username/.local/share/terraform/plugins
2023-01-26T15:26:34.676Z [DEBUG] ignoring non-existing provider search directory /home/username/.local/share/flatpak/exports/share/terraform/plugins
2023-01-26T15:26:34.676Z [DEBUG] ignoring non-existing provider search directory /var/lib/flatpak/exports/share/terraform/plugins
2023-01-26T15:26:34.676Z [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2023-01-26T15:26:34.676Z [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2023-01-26T15:26:34.676Z [INFO]  CLI command args: []string{"init", "-no-color"}

Initializing the backend...
2023-01-26T15:26:34.677Z [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2023-01-26T15:26:34.677Z [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2023-01-26T15:26:34.677Z [DEBUG] New state was assigned lineage "fc24ff00-8aae-361d-6b52-ac00d7d481a5"
2023-01-26T15:26:34.677Z [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2023-01-26T15:26:34.677Z [TRACE] Meta.Backend: instantiated backend of type <nil>
2023-01-26T15:26:34.678Z [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2023-01-26T15:26:34.678Z [TRACE] getproviders.SearchLocalDirectory: failed to resolve symlinks for .terraform/providers: lstat .terraform: no such file or directory
2023-01-26T15:26:34.678Z [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/providers: cannot search .terraform/providers: lstat .terraform/providers: no such file or directory
2023-01-26T15:26:34.678Z [DEBUG] checking for provisioner in "."
2023-01-26T15:26:34.678Z [DEBUG] checking for provisioner in "/home/username/bin"
2023-01-26T15:26:34.678Z [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2023-01-26T15:26:34.679Z [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-01-26T15:26:34.679Z [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-01-26T15:26:34.679Z [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-01-26T15:26:34.679Z [TRACE] statemgr.Filesystem: read nil snapshot

Initializing provider plugins...
- Reusing previous version of hashicorp/null from the dependency lock file
2023-01-26T15:26:34.679Z [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2023-01-26T15:26:34.679Z [TRACE] getproviders.SearchLocalDirectory: failed to resolve symlinks for .terraform/providers: lstat .terraform: no such file or directory
2023-01-26T15:26:34.679Z [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/providers: cannot search .terraform/providers: lstat .terraform/providers: no such file or directory
- Installing hashicorp/null v3.2.1...
2023-01-26T15:26:34.679Z [TRACE] providercache.Dir.InstallPackage: installing registry.terraform.io/hashicorp/null v3.2.1 from terraform.d/plugins/registry.terraform.io/hashicorp/null/terraform-provider-null_3.2.1_linux_amd64.zip

Error: Failed to install provider

Error while installing hashicorp/null v3.2.1: failed to calculate checksum
for registry.terraform.io/hashicorp/null 3.2.1 package at
terraform.d/plugins/registry.terraform.io/hashicorp/null/terraform-provider-null_3.2.1_linux_amd64.zip:
lstat terraform.d: no such file or directory
```

### Expected Behavior

The [docs](https://developer.hashicorp.com/terraform/cli/config/config-file#implied-local-mirror-directories) (explicitly amended in [PR #31460](https://github.com/hashicorp/terraform/pull/31460) to include this language) state:

> If a terraform.d/plugins directory exists in the current working directory then Terraform will also include that directory, regardless of your operating system. This behavior changes when you use the -chdir option with the init command. In that case, **Terraform checks for the terraform.d/plugins directory in the launch directory and not in the directory you specified with -chdir**. (emphasis added)

Given:

- the 2x config files **in a sub-directory** (`chdir-target`), as detailed above; and
- the `terraform.d` directory contents, as created by `terraform providers mirror terraform.d/plugins`; 

... I expected the following to install the `hashicorp/null` plugin:

```
$ find . -type f
./chdir-target/provider.tf.json
./chdir-target/.terraform.lock.hcl
./terraform.d/plugins/registry.terraform.io/hashicorp/null/terraform-provider-null_3.2.1_linux_amd64.zip
./terraform.d/plugins/registry.terraform.io/hashicorp/null/index.json
./terraform.d/plugins/registry.terraform.io/hashicorp/null/3.2.1.json
$ terraform -chdir=chdir-target init -no-color

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/null from the dependency lock file
- Installing hashicorp/null v3.2.1...

Error: Failed to install provider

Error while installing hashicorp/null v3.2.1: failed to calculate checksum for registry.terraform.io/hashicorp/null
3.2.1 package at
terraform.d/plugins/registry.terraform.io/hashicorp/null/terraform-provider-null_3.2.1_linux_amd64.zip: lstat
terraform.d: no such file or directory
```

Instead, to get things to work, the implicit filesystem mirror directory needs to be sitting relative to the `-chdir` target, directly contradicting the documentation, and rendering a setup using `-chdir` with an implicit filesystem mirror in the current directory **literally unable to complete**. 

```
$ mv terraform.d/ chdir-target/
$ find . -type f
./chdir-target/provider.tf.json
./chdir-target/.terraform.lock.hcl
./chdir-target/terraform.d/plugins/registry.terraform.io/hashicorp/null/terraform-provider-null_3.2.1_linux_amd64.zip
./chdir-target/terraform.d/plugins/registry.terraform.io/hashicorp/null/index.json
./chdir-target/terraform.d/plugins/registry.terraform.io/hashicorp/null/3.2.1.json
$ terraform -chdir=chdir-target init -no-color

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/null from the dependency lock file
- Installing hashicorp/null v3.2.1...
- Installed hashicorp/null v3.2.1 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### Actual Behavior

As per the narrative shell session detailed above, it appears that `-chdir` is totally breaking the `init`.

It *appears* that the pre-chdir code is correctly noticing the implicit filesystem mirror, and figured out that it has a plugin package candidate;  but is then passing an incorrectly not-relative-enough path to the code which actually *fetches* the package, which is resolving things relative to the `-chdir` target.

Thus, regardless of the intended correctness of the docs or not, the mere presence of a candidate package under the current working directory **breaks `terraform init -chdir`**.

### Steps to Reproduce

Create the filesystem mirror and config files as detailed above, and the filesystem hierarchy mentioned in the narrative shell session.

Run `terraform -chdir=chdir-target init`, and observe `lstat terraform.d: no such file or directory` in the error output - indicating that 2 parts of the terraform `init` flow are getting confused about where they should be looking for files.

### References

- #31443
- #31460

**Comment by jpluscplusm** [comment] 2023-01-26 17:27
As a follow-up, I've moved over to using a XDG_DATA_DIR-based implicit plugin mirror, and the 10x perf improvement over the "working" version I posted above leads me to suspect that having the `terraform.d/plugins` directory inside the `-chdir` target *merely* stops the explosion, but doesn't actually cause the mirror's contents to be used.

When using an absolute mirror path, e.g. one implicitly discovered inside `%HOME/.local/share/terraform/plugins`, plugin installation is basically instantaneous.

I believe the "working" version I posted is *still* fetching everything from the upstream registry -- hence my attempt to use a relative filesystem mirror (to save Hashi some CDN bandwidth inside my repetitive and frequent CI tests) would've been pointless, even if it weren't exploding, as per this Issue's core problem.

**Comment by apparentlymart** [comment] 2023-01-26 21:49
Thanks for reporting thism @jpluscplusm.

I've not investigated deeply yet but based purely on the symptoms you described I think this problem is caused by the fact that `-chdir` causes different parts of Terraform to see different working directories:

* The CLI configuration -- which "implied mirror directories" are a part of despite them not actually requiring any syntax in the CLI configuration file -- gets loaded before Terraform handles `-chdir` under the assumption that paths in the CLI configuration are typically not scoped to a particular run of Terraform.

    As part of this Terraform scans the implied mirror directories to see which providers are present there and behaves as if there were a `filesystem_mirror` block in the configuration referring to that directory:

    ```hcl
      filesystem_mirror {
        path    = "terraform.d/plugins"
        include = ["registry.terraform.io/hashicorp/null"]
      }
    ```
* That path gets baked into the plugin installer object exactly as written, which means once Terraform executes `chdir` just before beginning running the given subcommand (`terraform init` in this case) the path in the generated CLI configuration is no longer valid.

If I'm right about this cause then I think what we ought to do to fix it is to make sure that the codepath which generates the implied provider installation configuration based on the implied mirror directories will save the _absolute_ path to the directory it found, thereby ensuring that it will continue to mean the same thing throughout the rest of Terraform's execution even if we do later `chdir` to a different directory.

(A more robust version of that would be for Terraform to `open(...)` the directory during config loading and then do access indirectly via that file descriptor, rather than relying on paths at all, but I don't think that's really viable here both because we're reusing similar code as for explicit CLI configuration and that _does_ work with path strings, and also I don't think the idea of opening a directory and then resolving other paths relative to it is as easy to do in a cross-platform way as calculating an absolute version of a relative path.)

**Closed** 2023-08-11 06:43 UTC
Labels: bug, new, v1.3
