### ISSUE TITLE
Target destroy destroys other indexed resources more than specified

### ISSUE THREAD

**Issue by onedumslack** [hashicorp/terraform#32316] opened 2022-11-30 21:57 UTC
### Terraform Version

```shell
Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.44.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Terraform Configuration Files

```
terraform
provider "aws" {
  region  = "us-east-1"
}

locals {
  buckets = {
    bucket1 = {
      name = "target-destroy-index1-${random_uuid.name.id}"
    }
    bucket2 = {
      name = "target-destroy-index2-${random_uuid.name.id}"
    }
  }
}

resource "random_uuid" "name" {}

resource "aws_s3_bucket" "bucket" {
  for_each = local.buckets
  bucket   = each.value["name"]
}

resource "aws_s3_bucket_lifecycle_configuration" "ssm_patching_s3_bucket" {
  for_each = local.buckets
  bucket   = aws_s3_bucket.bucket[each.key].id
  rule {
    id     = "delete"
    status = "Enabled"
    expiration {
      days = 5
    }
  }
}
```

### Debug Output

https://gist.github.com/onedumslack/9d07692ab8045df1a79db25f4b544bdc#file-gistfile1-txt

### Expected Behavior

It should destroy the bucket and its once dependent lifecycle resource.

### Actual Behavior

It destroys the bucket and both buckets dependent lifecycle resource.

### Steps to Reproduce

terraform destroy --target 'aws_s3_bucket.bucket["bucket2"]'

### Additional Context

When running a targeted terraform destroy on indexed resources that are created with for_each terraform wants to destroy resources of other indexes.

**Comment by jbardin** [comment] 2022-11-30 22:02
Hi @onedumslack,

Thanks fir filing the issue.
Duplicate of #25836

**Closed by jbardin** 2022-11-30 22:02 UTC
Labels: bug, new
