### ISSUE TITLE
Crash when planning

### ISSUE THREAD

**Issue by bahner** [hashicorp/terraform#4798] opened 2016-01-22 15:38 UTC
I imported "everything" from my AWS account with terraforming (https://github.com/dtan4/terraforming) ; did a terraform get and then terraform plan.

This being a large operation I have no specifics.
[crash.log.txt](https://github.com/hashicorp/terraform/files/101026/crash.log.txt)

**Comment by jen20** [comment] 2016-01-22 19:07
Hi @bahner, could you let us know which version of Terraform you were using here? That code hasn't changed for a while and should protect against the kind of error logged here.

**Comment by phinze** [comment] 2016-01-25 17:01
Version shows up in crash log:

> 2016/01/22 16:33:51 [INFO] Terraform version: 0.6.9 fd1c2697a461588010711ab119525182c43a347e

Relevant crash log lines:

```
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x5653fc]
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: 
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: goroutine 138 [running]:
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsNetworkInterfaceRead(0xc8205b7aa0, 0xcedda0, 0xc8202e0000, 0x0, 0x0)
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_network_interface.go:143 +0xb7c
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc8204d2e80, 0xc8201ea930, 0xcedda0, 0xc8202e0000, 0xc8202db5e0, 0x0, 0x0)
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:209 +0x430
2016/01/22 16:33:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc820512330, 0xc8202e4900, 0xc8201ea930, 0xc8201caf01, 0x0, 0x0)
```

**Comment by catsby** [comment] 2016-03-29 18:02
This is identical to https://github.com/hashicorp/terraform/issues/5438, which I recently closed as I couldn't reproduce it. I'm going to close this one as well for now. Please let me know if you're still encountering this, have an example config, or steps to reproduce this.

Sorry for the trouble, and thanks for opening the issue!

**Closed by catsby** 2016-03-29 18:02 UTC
Labels: bug, crash, provider/aws
