### ISSUE TITLE
skip_destroy lifecycle option to un-import a resource on destroy

### ISSUE THREAD

**Issue by alexeyinkin** [hashicorp/terraform#35012] opened 2024-04-17 08:13 UTC
### Terraform Version

```shell
v1.8.0
```

### Use Cases

I need to rely on an external resource to use its properties in other resources. It exists before `terraform apply` and must continue to exist after `terraform destroy`.

### Attempted Solutions

Currently, it should be imported and then removed with `terraform state rm` before `terraform destroy`. While import is now declarative with `import` block, `terraform state rm` is not.

### Proposal

Add `skip_destroy` or `unimport_on_destroy` option to lifecycle block. Default is `false` (the current behavior). If set to `true`, it un-imports the resource when `terraform destroy` is otherwise complete. This way, we can have fully-declarative handling of external resources that must outlive the configuration.

This option should still allow Terraform to update the resource and even destroy and re-create it if triggered. It should be combined with `prevent_destroy` to forbid the latter.

**Comment by jbardin** [comment] 2024-04-17 13:09
Hi @alexeyinkin,

The declarative version of `terraform state rm` is the [`removed` block](https://developer.hashicorp.com/terraform/language/resources/syntax#removing-resources). This however would need to be added to the config before destroying the resource. The ability to forget an instance rather than destroy it is a subset of [this enhancement request](#15485)

Thanks!

**Comment by jbardin** [comment] 2024-04-17 13:09
Duplicate of #15485

**Closed by jbardin** 2024-04-17 13:09 UTC
Labels: enhancement, new
