### ISSUE TITLE
State Path not displayed when remote state is configured

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#13303] opened 2017-04-03 19:14 UTC
Version: Terraform commit c68675bc4
Operating System:  OSX 10.12.3

Following a `terraform apply` with remote state configured, a label for `State Path` is displayed, but no path is displayed:

```
// Output omitted

Apply Complete! Resources: 4 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use  the `terraform show` command.

State path:
```

This should likely be shown as "remote" (minimally) or preferably a string representation of the configured remote state path (e.g. `Manta (Account: jen20, Path: states/dns)`)

**Comment by grubernaut** [comment] 2017-04-03 20:39
Hey @jen20, thanks for the issue! ❤️ 

Closing, as it's a dupe of #13042. Happy to discuss further if need be, or re-open if needed.

**Closed by grubernaut** 2017-04-03 20:39 UTC
