### ISSUE TITLE
No longer able to import module from s3 since version 0.10.3

### ISSUE THREAD

**Issue by jocgir** [hashicorp/terraform#16442] opened 2017-10-24 22:36 UTC
Hi, 

We have code similar to this:

```
module "whatever" {
  source = "mybucket.s3-us-east-1.amazonaws.com/mypath/mykey"
}
```

It was working fine up to version 0.10.2.

But now, we get that error on the terraform init:

```
Error downloading modules: Error loading modules: error downloading 'https://s3-us-east-1.amazonaws.com/cmybucket/mypath/mykey': RequestError: send request failed
caused by: Get https://s3-us-east-1.amazonaws.com/mybucket?prefix=mypath%2Fmykey: dial tcp: lookup s3-us-east-1.amazonaws.com on 192.168.0.1:53: no such host
```

We followed that documentation:
https://www.terraform.io/docs/modules/sources.html

Neither of the two s3 url form is working while both of them are still working with terraform version <=0.10.2.

Regards,

**Comment by apparentlymart** [comment] 2017-10-24 23:31
Sorry for this regression @jocgir, and thanks for reporting it.

It looks like we upgraded the underlying library `go-getter` in 0.10.3 to benefit from its improved support for new archive formats. I'm going to look at the history of that library to see if there was also a change to its S3 support in that release that could account for it.

**Comment by apparentlymart** [comment] 2017-10-24 23:43
It looks like hashicorp/go-getter#68 was introduced within the changeset we adopted during the 0.10.3 release, and it made some changes to how S3 URLs are interpreted to support S3 "workalike" implementations.

I haven't yet identified a specific aspect of that change that would lead to this regression but indeed it looks like when using S3 in the `us-east-1` region it's required to use the hostname `s3.amazonaws.com`. I assume (though haven't yet been able to prove) that prior versions of `go-getter` were normalizing an explicit `us-east-1` to the "regionless" hostname, and that this is no longer true.

If I'm right, it may be possible to work around this by changing the source to not include the region in the hostname, so that the hostname given is actually resolvable in DNS:

```hcl
module "whatever" {
  source = "mybucket.s3.amazonaws.com/mypath/mykey"
}
```

**Comment by jocgir** [comment] 2017-10-25 11:59
Yes, you are right, it is working without the region.

It would be nice to restore the previous behaviour as it is annoying to make a distinction between our different region.

Thank you for your quick reaction.

**Comment by apparentlymart** [comment] 2017-10-25 15:58
Cool... glad the workaround was successful.

Definitely want to restore the previous behavior though, since this was not an intentional change.

**Comment by conlon** [comment] 2020-02-18 22:22
this looks like it's still an issue as of 0.12.18

**Comment by mildwonkey** [comment] 2020-08-27 16:03
The documentation has since been updated to reflect the correct syntax, so I am going to close this issue. Thanks@

**Closed by mildwonkey** 2020-08-27 16:03 UTC
Labels: bug, config, dependencies, regression, v0.10
