### ISSUE TITLE
No attribute `address` for `google_compute_address`

### ISSUE THREAD

**Issue by timfallmk** [hashicorp/terraform#3362] opened 2015-09-30 02:15 UTC
I'm running into a strange error with `google_compute_address` when trying to export an attribute:

My config looks something like:
```hcl
resource "google_compute_address" "client-address" {
  name = "nomad-address-${var.zone}-${var.count}"
  count         = "${var.count}"
}

resource "google_compute_instance" "client" {
  name          = "nomad-client-${count.index}"
  count         = "${var.count}"
  zone          = "${var.zone}"
  disk {
    image       = "${var.image}"
    size        = "${var.size}"
  }
  network_interface {
    network     = "nomad"
    access_config = {
      nat_ip = "${google_compute_address.client-address.address}"
    }
  }
  machine_type  = "n1-standard-2"
  tags          = ["nomad"]
```
However when, I put it into terraform, I get multiple:
```
* Resource 'google_compute_address.server-address' does not have attribute 'address' for variable 'google_compute_address.server-address.address'
```

It seems like I'm not able to reference the exportable attribute for this resource.

**Comment by timfallmk** [comment] 2015-10-01 01:03
Any ideas on this? Makes it hard to get a Nomad cluster up and running.

Can I use the depreciated `network` attribute?

**Comment by lwander** [comment] 2015-10-06 15:50
Which version of Terraform are you running? It works for me on 0.6.4-dev

**Comment by sparkprime** [comment] 2015-10-06 19:48
I don't think that's how you use count.  You want to make each instance depend on the corresponding address.  I'm not sure how to do it though.

**Comment by lwander** [comment] 2015-10-06 20:03
Oh I see what the problem is -

instead of 
```
nat_ip = "${google_compute_address.client-address.address}"
````
you need
```
nat_ip = "${element(google_compute_address.client-address.*.address, count.index)}"
```

Also - you can remove `${count.index}` from the resource names, you can access elements by index using ```resource_name.resource_id.N.attribute``` where `N` is the index you need.

**Comment by timfallmk** [comment] 2015-10-08 00:15
@lwander The `element` listing seems to work, but in order to have each iteration of the compute object be attached to the corresponding address object, they need to be iterated through upon creation at the same index.

@sparkprime 's point is well taken. I can't seem to find a way of creating a one-to-one mapping of address to compute, but still being able to access the whole list to input into a `join` command.

Any ideas?

**Comment by lwander** [comment] 2015-10-08 13:43
> I can't seem to find a way of creating a one-to-one mapping of address to compute,

The `element` call is giving you the 1-1 correspondence. It's mapping the `compute` instance with `count.index = i` to the `i`th `address` element in the list that's expanded. 

> but still being able to access the whole list to input into a `join` command.

You can input the whole list of `address` objects' `address` elements into a `join` command like this
```join(",", google_compute_address.client-address.*.address)```

The example "Using Templates with Count" [here](https://www.terraform.io/docs/configuration/interpolation.html) maps `aws_instances` to `template_file`s in a 1-1 fashion.

**Comment by sparkprime** [comment] 2015-10-18 17:14
@timfallmk did you get it working?

**Comment by dtx** [comment] 2016-03-18 06:52
Shouldn't this be closed? Looks like the solution was posted.

**Comment by lwander** [comment] 2016-03-18 12:44
I was hoping to hear from @timfallmk if it was working before closing this, but I guess it's been long enough.

**Closed by lwander** 2016-03-18 12:44 UTC
Labels: bug, core, provider/google-cloud

**Comment by timfallmk** [comment] 2016-03-21 21:38
@lwander Apologies, I don't recall what testing revealed. It should be fine to close and someone can reopen if it comes back up.

**Comment by lwander** [comment] 2016-03-21 22:07
No worries at all, sounds good to me too.
