### ISSUE TITLE
Include provider information into state and plan output

### ISSUE THREAD

**Issue by stumyp** [hashicorp/terraform#31989] opened 2022-10-11 17:03 UTC
### Terraform Version

```shell
Terraform v1.2.7
```

### Use Cases

In complex projects where multiple instances of the same provider are used, like for example AWS provider for different region or account or role. When creating plan it is impossible to know without looking at the code what provider will be used to create certain resource.  There have been cases where certain change was approved and applied to realize that it wasn't deployed in the proper account or region. 

The same is happening with the state: currently `terraform state show <resource>` does not show what provider was used to create it. Which is making harder to debug the issue. 

### Attempted Solutions

I have no way to solve this except by inspecting the code and making sure specific provder is clearly defined in the resource or module definition.

### Proposal

Please include provider information to the outputs of `terraform plan` and `terraform state show`. This will greatly help with dealing with complex deployments where multiple providers of the same type are used.

**Comment by jbardin** [comment] 2022-10-11 17:09
Duplicate of #27558

**Closed by jbardin** 2022-10-11 17:09 UTC
Labels: enhancement, duplicate

**Comment by stumyp** [comment] 2022-10-11 17:12
Thanks @jbardin , I couldn't find existing issue, so I opened this one. My request was abit wider than the issue you linked to. I also wanted to discuss storing provider information in the state. I guess I can open a separate issue for that.

**Comment by jbardin** [comment] 2022-10-11 17:16
The linked issue would suffice for including the provider information in the plan. Can you show an example of what you mean by storing provider information in the state? Each resource in the state already has a fully qualified provider name.

**Comment by jbardin** [comment] 2022-10-11 17:21
Oh, if you're referring to providers in the supported `-json` output format for the state, then you can reference issue #30798 as well.

**Comment by stumyp** [comment] 2022-10-11 17:22
Oh, so it is already in the state but `terraform state show` doesn't have it in the output.

here is the example of terraform state show for one of the resources:

```hcl
resource "aws_s3_bucket" "yyy-XXX-state" {
    acl                         = "private"
    arn                         = "arn:aws:s3:::yyy-XXX-state"
    bucket                      = "yyy-XXX-state"
    bucket_domain_name          = "yyy-XXX-state.s3.amazonaws.com"
    bucket_regional_domain_name = "yyy-XXX-state.s3.amazonaws.com"
    force_destroy               = false
    hosted_zone_id              = "qqq"
    id                          = "yyy-XXX-state"
    object_lock_enabled         = false
    policy                      = jsonencode(
        {
            Statement = [
                {
                    Action    = "s3:*"
                    Effect    = "Allow"
                    Principal = {
                        AWS = [
                            "yyy"
                        ]
                    }
                    Resource  = [
                        "arn:aws:s3:::yyy-XXX-state/*",
                        "arn:aws:s3:::yyy-XXX-state",
                    ]
                    Sid       = ""
                },
            ]
            Version   = "2012-10-17"
        }
    )
    region                      = "us-east-1"
    request_payer               = "BucketOwner"
    tags                        = {
        "Name" = "yyy-XXX-state"
        "env"  = "qqq"
    }
    tags_all                    = {
        "Name" = "yyy-XXX-state"
        "env"  = "qqq"
    }

    grant {
        id          = "uuuu"
        permissions = [
            "FULL_CONTROL",
        ]
        type        = "CanonicalUser"
    }

    versioning {
        enabled    = true
        mfa_delete = false
    }
}
```

There might be an information in the state itself, but it is not shown. And it is quite cumbersome to work with the raw state file, especially remote one.

**Comment by stumyp** [comment] 2022-10-11 17:24
Thanks @jbardin . Yes this is what I am looking for. both `-json` or plain output of either `state show ` or `show` would be nice. I'll go to the linked issue.

**Comment by ahosking** [comment] 2022-10-12 13:36
I'd like to make my upvote for this request known. 👍
