### ISSUE TITLE
Moving resource state to another provider does not change .tfstate provider

### ISSUE THREAD

**Issue by steveh** [hashicorp/terraform#11372] opened 2017-01-24 04:07 UTC
I'm not sure if this is a bug per se or just something I'm not supposed to do, but here goes.

Moving resource state from one "instance" of a provider to another instance of the same provider requires manually updating the .tfstate file to change the `provider` attribute, to avoid the error `provider foo.bar is not initialized`

### Terraform Version
Terraform v0.8.5 (built from HEAD), also v0.8.4

### Affected Resource(s)
At least AWS provider, presumably others.

### Terraform Configuration Files
Original config:

```hcl
provider "aws" {
  alias  = "sydney"
  region = "ap-southeast-2"
}

resource "aws_instance" "foo" {
   provider = "aws.sydney"
}
```
New module config:
```hcl
variable "region" {}

provider "aws" {
  alias  = "module"
  region = "${var.region}"
}

resource "aws_instance" "main" {
   provider = "aws.module"
}
```
New config:
```
module "foo_instance" {
   source = "./instance"
   region = "ap-southeast-2"
}
```

### Debug Output
`Provider aws.sydney is not initialized`

### Expected Behavior
Instance provider is moved to that of the module provider.
`"provider": "aws.module"`

### Actual Behavior
Instance provider is unchanged
`"provider": "aws.sydney"`

### Steps to Reproduce
1. `terraform state mv aws_instance.foo module.foo_instance.aws_instance.main`
2. `terraform plan`

**Comment by mitchellh** [comment] 2017-01-24 20:11
Thanks for the great bug report. I'm not sure what I'm doing wrong, but I'm following your steps exactly and I'm unable to reproduce this. I can see the incorrect provider in the state after moving it, but it is corrected on graph construction (updating with the latest from the config) to point to the proper provider.

Hm... any other ideas?

**Comment by steveh** [comment] 2017-01-24 20:21
My actual module was a VPC with associated subnets and route tables etc, so I wonder if the problem lies with nested resources. 

Here's an anonymised version of what I really did: https://gist.github.com/steveh/cb5991acb9d617194fa12aace64e8140

**Comment by mitchellh** [comment] 2017-01-25 02:57
Hm, played around with more situations and wasn't able to get the error to trigger. :( 

I believe you there is an issue but I _think_ it is fairly edge case -- as a silver lining. Until we have a solid reproduction case, I'm going to close this issue. I'm sure that someone will open a new issue if this happens again. If you yourself experience it again please let me know. 

I have a feeling it has something to do with counts and being in a module but I just... I couldn't get it to show up. I tried a number of different things. :(

**Closed by mitchellh** 2017-01-25 02:57 UTC
Labels: bug, core, waiting-response

**Comment by steveh** [comment] 2017-01-25 02:58
Thanks for looking!
