### ISSUE TITLE
terraform-bundle: there is no way to override location of the terraform binary

### ISSUE THREAD

**Issue by alexmnyc** [hashicorp/terraform#29069] opened 2021-06-30 17:27 UTC
In the air-gapped environment, we need to override location of the terraform binary. How do we do that? Isn't the whole point of air-gapped solution is to be able to point it outside of hashicorp.com? Also, shouldn't it detect the terraform version is present already and not fetch it?

By default, 

```
terraform {
  # Version of Terraform to include in the bundle. An exact version number
  # is required.
  version = "0.13.7"
}

```
goes out to

Failed to fetch core package from https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_linux_amd64.zip: Get "https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_linux_amd64.zip": EOF

**Comment by apparentlymart** [comment] 2021-06-30 19:44
Hi @alexmnyc! Thanks for sharing this use-case.

The `terraform-bundle` tool was intended to address a specific need of packaging up official releases of Terraform and necessary providers to be able to use them in Terraform Enterprise installations which don't have access to `releases.hashicorp.com`. It might well have occasionally be useful for other purposes, but bundling up _unofficial_ builds is not part of its scope.

If you are already fetching all of the necessary files yourself anyway and just want to archive them into a `.zip` file, you could achieve that by using a normal zip tool. There's nothing particularly special about the archives that `terraform-bundle` creates, it just aims to automate the step of determining the appropriate URL to download each package from.

The `terraform-bundle` tool is now frozen and won't see any further development aside from urgent bug fixes that affect Terraform Enterprise customers. Because of that, I'm going to close this issue. If you need to create a zip file containing a Terraform executable you already have installed then I would suggest to build that using general scripting tools, just copying the files you want to include into a particular directory and then using a tool like `zip` to package them into a zip file.

Thanks!

**Closed by apparentlymart** 2021-06-30 19:44 UTC
Labels: bug, new

**Comment by alexmnyc** [comment] 2021-06-30 20:13
@apparentlymart I do not need to bundle terraform as part of the dependencies bundle. terraform-bundle requires terraform version block be default:

```
terraform {
  # Version of Terraform to include in the bundle. An exact version number
  # is required.
  version = "0.13.7"
}


providers {

  kustomization = {
      source  = "kbst/kustomization"
      versions = ["0.5.0"]
  }
}
```


You cannot use it without it i.e.

```

providers {

  kustomization = {
      source  = "kbst/kustomization"
      versions = ["0.5.0"]
  }
}
```
 It will complain that terraform version must be specified. Once specified the tool goes out to releases.hashicorp.com to download terraform and there is no way to customize its behavior. In air-gapped environemnt to build a terraform bundle i can download dependencies through artifactory proxy and add them to the -plugin-dir, however, there is no way to customize the default downloading of terraform from hashicorp public website.

There has to be a parameter -terraform-binary https://myartifactory.com/releases-hashicorp/.... for things to work for enterprise.

**Comment by apparentlymart** [comment] 2021-06-30 22:03
Hi @alexmnyc,

`terraform-bundle` is intended to be run in a _non-airgapped_ environment in order to prepare a package that will later be used in an air-gapped Terraform Enterprise system. We will not be adding any new capabilities to `terraform-bundle` moving forward, so if you have needs beyond what it currently supports then I suggest to write your own script to retrieve the packages from your artifactory server and package them in whatever way suits your needs.
