### ISSUE TITLE
JSON validation fails with optional fields as required ones.

### ISSUE THREAD

**Issue by uningan** [hashicorp/terraform#31810] opened 2022-09-16 23:39 UTC
### Terraform Version

```shell
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.31.0
```

### Terraform Configuration Files

```json
{
  "resource": {
    "aws_security_group": {
      "jumbox-security-group": {
        "ingress": [
          {
            "cidr_blocks": [
              "0.0.0.0/0"
            ],
            "from_port": 22,
            "protocol": "tcp",
            "to_port": 22
          }
        ],
        "name": "jumpbox-security-group",
        "vpc_id": "vpc-0a5fd33"
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/uningan/42db5ea52232683dcc86862b2aa95913

### Expected Behavior

No errors

### Actual Behavior

Inappropriate value for attribute "ingress": element 0: attributes "description", "ipv6_cidr_blocks", "prefix_list_ids", "security_groups", and "self" are required.

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### References

https://www.terraform.io/language/attr-as-blocks

**Comment by crw** [comment] 2022-09-17 00:17
Hello @uningan,

I believe this validation is an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help.

I am going to leave this open just in case this is a core issue, but you may have a faster answer going to the AWS repo or the forums. Thanks for your submission!

**Comment by uningan** [comment] 2022-09-17 06:59
Thank you for your reply. I'll ask there also. However I fill bug here because same resource definition in HCL works well while in JSON fails.

In any case I'll investigate a bit more with different providers using Attribute-as-block mode (I'm not familiar with other providers using that mode maybe you could point me to someother).

**Comment by jbardin** [comment] 2022-09-19 13:12
Hi @uningan,

Thanks for filing the issue, this is a duplicate of #25711. The `ingress` block within the `aws_security_group` is using a workaround for legacy providers which allows attribute-like access to the block so that a set of rules can be assigned directly. This unfortunately means that outside of the special case of HCL which still allows block syntax, `ingress` will behave like an attribute and require all nested object attributes to be defined.

As providers are updated, they are working towards removing these workarounds, re-defining the blocks or using optional attributes from the new provider framework.

Thanks!

**Closed by jbardin** 2022-09-19 13:12 UTC
Labels: bug, question, provider/aws, new
