### ISSUE TITLE
Terraform v1.3.3 crash: inconsistent map element types

### ISSUE THREAD

**Issue by vladimir-kozyrev** [hashicorp/terraform#32094] opened 2022-10-27 08:14 UTC
### Terraform Version

```shell
v1.3.3
```

### Terraform Configuration Files

`variables.tf`
```terraform
variable "developers" {
  type = map(
    object({
      given_name    = string
      family_name   = string
      primary_email = string
      aliases       = optional(list(string), [])
      developer_info = optional(object({
        teams            = optional(list(string), [])
        github_username  = optional(string)
        github_role      = optional(string, "member")
        github_team_role = optional(string)
      }))
      sendgrid = optional(object({
        role = optional(string)
      }))
      phone              = optional(string)
      personal_email     = optional(string)
      unit               = string
      groups             = optional(map(string))
      gcp_permissions    = optional(map(list(string)))
      in_developers_team = optional(bool, true)
      password           = optional(string)
      hash_function      = optional(string)
    })
  )
  default = {
    "Name1_Surname1" = {
      given_name     = "Name1"
      family_name    = "Surname1"
      primary_email  = "email1@test.com"
      personal_email = "email1@personaltest.com"
      unit           = "/general"
      developer_info = {
        "github_username" = "xxx1"
      }
      in_developers_team = false
    }
    "Name2_Surname2" = {
      given_name    = "Name2"
      family_name   = "Surname2"
      primary_email = "email1@test.com"
      unit          = "/developers"
    }
  }
}
```

`main.tf`
```terraform
locals {
  developers_info = flatten(flatten([
    for user, user_config in var.developers : [
      for key, value in user_config : {
        github_username  = value.github_username
        teams            = value.teams
        github_role      = value.github_role
        github_team_role = value.github_role == "admin" ? "maintainer" : "member"
        email            = user_config["primary_email"]
      } if user_config["developer_info"] != null && key == "developer_info"
    ]
  ]))
}

resource "googleworkspace_user" "this" {
  for_each       = var.developers
  primary_email  = each.value.primary_email
  recovery_email = each.value.personal_email
  recovery_phone = each.value.phone
  name {
    family_name = each.value.family_name
    given_name  = each.value.given_name
  }
  aliases       = each.value.aliases
  password      = each.value.password
  hash_function = each.value.hash_function
  org_unit_path = each.value.unit
  organizations {
    department = "/developers"
    type       = "work"
  }
  lifecycle {
    ignore_changes = [
      change_password_at_next_login,
      phones,
      recovery_email,
      recovery_phone,
    ]
  }
}
```

`provider.tf`
```terraform
terraform {
  required_providers {
    googleworkspace = {
      source  = "hashicorp/googleworkspace"
      version = "0.7.0"
    }
  }
}

provider "googleworkspace" {
  # Use GOOGLEWORKSPACE_CREDENTIALS env
  # More settings: https://registry.terraform.io/providers/hashicorp/googleworkspace/latest/docs
  customer_id = "XXX"
}
```

### Debug Output

https://gist.github.com/vladimir-kozyrev/ea6b381a820f369b7a5e6f570285dd52

### Expected Behavior

`terraform plan` should work without crashing

### Actual Behavior

`terraform plan` crashes

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

I think it may be related to the optional variables because of the diff
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/7099677/198226103-babbfb93-515e-4b80-b1d6-09110cf7e802.png">

### References

[#31962](https://github.com/hashicorp/terraform/issues/31962)

**Comment by jbardin** [comment] 2022-10-27 12:47
Duplicate of #31978

**Closed by jbardin** 2022-10-27 12:47 UTC
Labels: bug, new
