### ISSUE TITLE
Intermittent network errors

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform#25441] opened 2020-06-30 19:56 UTC
### Terraform Version

```
Terraform v0.12.23
```

We're running a drift detection workflow using github actions, which simply runs terraform plan and fails if it outputs anything. This runs on a schedule every hour.
We're getting request errors, causing terraform plan to fail, around 2-3 times a day

Some of the request errors we've so far encountered:

```
Error: RequestError: send request failed
caused by: Get https://cloudfront.amazonaws.com/2019-03-26/origin-access-identity/cloudfront/E26H********: read tcp 10.1.0.4:52046->54.239.29.26:443: read: connection reset by peer
```
---
```
Error: RequestError: send request failed
caused by: Get https://cloudfront.amazonaws.com/2019-03-26/origin-access-identity/cloudfront/E1B3D********: read tcp 10.1.0.4:33408->54.239.29.51:443: read: connection reset by peer
```
---
```
Error: error listing tags for CloudFront Distribution (E24R********): RequestError: send request failed
caused by: Get https://cloudfront.amazonaws.com/2019-03-26/tagging?Resource=arn%3Aaws%3Acloudfront%3A%3A*********%3Adistribution%2FE24********: read tcp 10.1.0.4:56918->54.239.29.65:443: read: connection reset by peer
```
---
```
Error: error getting S3 Bucket website configuration: RequestError: send request failed
caused by: Get https://******.s3.amazonaws.com/?website=: read tcp 10.1.0.4:59070->52.216.20.56:443: read: connection reset by peer
```
---
```
Error: error getting S3 Bucket replication: RequestError: send request failed
caused by: Get https://*******.s3.amazonaws.com/?replication=: read tcp 10.1.0.4:60534->52.216.138.67:443: read: connection reset by peer
```

Most of these seem to be CloudFront and S3

Not sure whether this should be raised under terraform or the aws provider

Thanks

**Comment by apparentlymart** [comment] 2020-07-01 00:15
Hi @lijok,

The requests you've listed here do seem to be made by the AWS provider rather than by Terraform, and so [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) might be a better place to report them.

With that said, this sort of problem tends to be specific to a particular environment, so I'd suggest first making sure there isn't a networking problem on your end which could be causing this. If the problem isn't reliably reproducible regardless of network location then I expect the AWS provider team will not be able to address this. If you'd like some help with troubleshooting you could perhaps start a topic in [the AWS provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33).

Because these requests are being made by the AWS provider rather than Terraform Core it seems like there is no change we could make in this repository to improve the situation, so I'm going to close this. Thanks!

**Closed by apparentlymart** 2020-07-01 00:15 UTC
