### ISSUE TITLE
Bad syntax on variable declaration (missing name) causes a crash

### ISSUE THREAD

**Issue by jasonmcintosh** [hashicorp/terraform#7846] opened 2016-07-28 15:47 UTC
### Terraform Version

0.16.6
### Affected Resource(s)

Variables/syntax
### Terraform Configuration Files

variable {
  name = "test"
  default = "test_value"
  type = "string"
}
### Debug Output

https://gist.github.com/jasonmcintosh/61524b3425e09e79c08b6e1a12c86bc7
### Panic Output

Same as debug output
https://gist.github.com/jasonmcintosh/61524b3425e09e79c08b6e1a12c86bc7
### Actual Behavior

Complete crash until I noticed the bad syntax
### Steps to Reproduce

Create a file with the above stuff, run terraform plan.

**Comment by jen20** [comment] 2016-08-01 14:14
Hi @jasonmcintosh! Thanks for reporting this. I can reproduce it from your code snippet. Having done some investigation, this is _reasonably_ straightforward to fix, but involves a fairly significant change to reading variable blocks from HCL. I have this work prototyped as part of investigating the crash, however since it is somewhat risky and we're gearing up to release Terraform 0.7, I'm going to defer it to a point release. I'll open up a pull request shortly which has the WIP on it and link here.

**Comment by mitchellh** [comment] 2016-11-02 21:59
Fix is in the referenced PR!

**Closed** 2016-11-04 15:47 UTC
Labels: bug, core, crash
