### ISSUE TITLE
odd behaviour for Index function.

### ISSUE THREAD

**Issue by mukundparmar** [hashicorp/terraform#28210] opened 2021-03-26 14:58 UTC
### Terraform Version
  0.14.8
  0.14.4
  0.13.6

```
...
```

### Terraform Configuration Files
I have added TF files in my Github repository https://github.com/mukundparmar/hcl-issue-code

```terraform
...
```

### Expected Behavior
```
  # aws_cloudwatch_dashboard.per-logical-group["RelativityWebServers"] will be created
  + resource "aws_cloudwatch_dashboard" "per-logical-group" {
      + dashboard_arn  = (known after apply)
      + dashboard_body = jsonencode(
            {
              + widgets = [
                  + {
                      + height     = 6
                      + properties = {
                          + metrics = [
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m1+m2)*8)/1024/1024/1024/PERIOD(m1)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m11+m12)*8)/1024/1024/1024/PERIOD(m11)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m21+m22)*8)/1024/1024/1024/PERIOD(m21)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m31+m32)*8)/1024/1024/1024/PERIOD(m31)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m41+m42)*8)/1024/1024/1024/PERIOD(m41)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
======================= Suppressed=================== 
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m91+m92)*8)/1024/1024/1024/PERIOD(m91)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                            ]
                          + period  = 300
                          + region  = "us-east-2"
                          + stacked = false
                          + stat    = "expression"
                          + title   = "InstanceName Network Gb/s-expression"
                        }
                      + type       = "metric"
                      + width      = 12
                      + x          = 12
                      + y          = 14
                    },
                ]
            }
        )
      + dashboard_name = "WebServers"
      + id             = (known after apply)
    }

```

### Actual Behavior
```
  # aws_cloudwatch_dashboard.per-logical-group["RelativityWebServers"] will be created
  + resource "aws_cloudwatch_dashboard" "per-logical-group" {
      + dashboard_arn  = (known after apply)
      + dashboard_body = jsonencode(
            {
              + widgets = [
                  + {
                      + height     = 6
                      + properties = {
                          + metrics = [
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m1+m2)*8)/1024/1024/1024/PERIOD(m1)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m11+m12)*8)/1024/1024/1024/PERIOD(m11)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m221+m22)*8)/1024/1024/1024/PERIOD(m221)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m31+m32)*8)/1024/1024/1024/PERIOD(m31)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m41+m42)*8)/1024/1024/1024/PERIOD(m41)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
======================= Suppressed=================== 
                              + [
                                  + jsonencode(
                                        {
                                          + expression = "((m91+m92)*8)/1024/1024/1024/PERIOD(m91)"
                                          + label      = "InstanceName Network Gb/s"
                                        }
                                    ),
                                ],
                            ]
                          + period  = 300
                          + region  = "us-east-2"
                          + stacked = false
                          + stat    = "expression"
                          + title   = "InstanceName Network Gb/s-expression"
                        }
                      + type       = "metric"
                      + width      = 12
                      + x          = 12
                      + y          = 14
                    },
                ]
            }
        )
      + dashboard_name = "WebServers"
      + id             = (known after apply)
    }
```

### Steps to Reproduce
I have included generic `main.tf` and `variables.tf` files here https://github.com/mukundparmar/hcl-issue-code so steps will be straightforward just try the code against 10 EC2 instances and run `init` and `plan`.
I tried against .13, .14 and latest version but it's still showing the same result.
Code is not finished yet but plan can show you the details.

**Comment by alisdair** [comment] 2021-03-26 17:29
Hi @mukundparmar. I'm sorry, but I can't see what the issue is. Can you edit your report to concisely explain what the behaviour you're seeing is, and what you expected to see? Providing a _small_ and isolated configuration sample which reproduces the issue will help is determine what's happening. Thanks!

**Comment by Tbohunek** [comment] 2021-04-07 08:07
Hi @mukundparmar, I found this quite interesting and I think I found something.

Before I get to it, I personally think that this code that you put together is exact example of what should have never been done in Terraform. The code is crazy complex and heavily prone to error.

I don't know exactly what `m1+m2` should mean, but I see the only difference in those two codes is line `30` where you get `m221+m22` instead of `m21+m22`.
I think this is due to the recurrence in your `replace()` combined with `distinct()` and `regexall()`. Here's the flow:

1. You have `m1+m2`
2. First instance of `distinct(regexall("m(\\d+?)", "m1+m2"))` returns `[m1,m2]`
3. Because this is `length() >0`, the `true` branch is triggered
4. I don't see what `1 + (length(local.target_instances_per_dashboard[k]) * index(local.target_instances_per_dashboard[k], i))` should return, but let's assume it returns `21`. Is that right for the given `k`?
5. So `replace(x "m1", "m21")` turns  `m1+m2` into `m21+m2`.
6. Now the second `replace(x "m2", y)` triggers
7. `distinct(regexall("m(\\d+?)", "m1+m2"))` still returns `[m1,m2]`
8. This is still `length(distinct()) >1` so the `true` branch is triggered
7. The `true` formula still returns `21`,
8. So `replace(x, "m2", "m21")` turns  `m21+m2` into `m221+m21`.
9. Now comes the third `replace(x, "m3", y)` but it does nothing because there's no `m3` so the chains stops here.

@alisdair can you confirm my theory?

**Comment by alisdair** [comment] 2021-04-09 15:22
That makes sense to me. Thanks for digging into this, @Tbohunek! I'm closing this issue for now as it doesn't appear to be a bug in Terraform.

**Closed by alisdair** 2021-04-09 15:22 UTC
Labels: bug, waiting for reproduction
