### ISSUE TITLE
crash - null pointer deref

### ISSUE THREAD

**Issue by fredrik-jansson-se** [hashicorp/terraform#30175] opened 2021-12-15 08:15 UTC
### Terraform Version

```
terraform version
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.65.0
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output
Sorry, reluctant to paste the output here since it's communicating with our AWS account and I'm not sure there is no sensitive material in that log.
```
terraform destroy -auto-approve -parallelism=50

aws_key_pair.deployer: Refreshing state... [id=terraform-20211215075243207400000001]
module.vpc.aws_vpc.this[0]: Refreshing state... [id=vpc-0d04814ea10116377]
module.vpc.aws_eip.nat[1]: Refreshing state... [id=eipalloc-0e8a8d3effa1076a5]
module.vpc.aws_eip.nat[0]: Refreshing state... [id=eipalloc-084147017a03bfe58]
module.vpc.aws_eip.nat[2]: Refreshing state... [id=eipalloc-06e4ad61e2eeb4715]
module.vpc.aws_subnet.public[0]: Refreshing state... [id=subnet-0f97b57182e8e3e2d]
module.vpc.aws_subnet.public[1]: Refreshing state... [id=subnet-0da97df98fff48bfc]
module.vpc.aws_subnet.public[2]: Refreshing state... [id=subnet-038174dfecbb5e1fd]
module.vpc.aws_route_table.public[0]: Refreshing state... [id=rtb-0260ff0d4c61774c1]
module.vpc.aws_subnet.private[0]: Refreshing state... [id=subnet-0768373d8cec99883]
module.vpc.aws_subnet.private[2]: Refreshing state... [id=subnet-038bc577bc9fa3c74]
module.vpc.aws_subnet.private[1]: Refreshing state... [id=subnet-0446aae39ef65f086]
module.vpc.aws_internet_gateway.this[0]: Refreshing state... [id=igw-0211ff6ac5a94d47f]
module.vpc.aws_route_table.private[0]: Refreshing state... [id=rtb-0e445ea1d12be55cd]
module.vpc.aws_route_table.private[2]: Refreshing state... [id=rtb-05e0b39d1ab7264d0]
module.vpc.aws_route_table.private[1]: Refreshing state... [id=rtb-0b2c65fc3023af0ca]
module.security_group.aws_security_group.this_name_prefix[0]: Refreshing state... [id=sg-038c86a2c66af7a71]
module.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-0b1d44844db057d57]
module.vpc.aws_route_table_association.public[2]: Refreshing state... [id=rtbassoc-012be7fb24e5fc4df]
module.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-0eedd851a6fbc9a54]
module.vpc.aws_nat_gateway.this[0]: Refreshing state... [id=nat-085b6ab7a58220a14]
module.vpc.aws_nat_gateway.this[2]: Refreshing state... [id=nat-060be8b64b2a7292e]
module.vpc.aws_nat_gateway.this[1]: Refreshing state... [id=nat-0a43e424835bd7270]
module.vpc.aws_route.public_internet_gateway[0]: Refreshing state... [id=r-rtb-0260ff0d4c61774c11080289494]
module.ec2_site_instance[77].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-6ibpbv8m]
module.ec2_site_instance[85].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-2qdpbr7n]
module.ec2_site_instance[38].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-g2i69w3q]
module.ec2_site_instance[13].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-z4fy9pkq]
module.ec2_site_instance[94].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-2pgyb2zn]
module.ec2_site_instance[40].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-iycy9cdn]
module.ec2_site_instance[33].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-5ewebj1p]
module.ec2_site_instance[84].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-kk9p9akp]
module.ec2_site_instance[78].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-7cn6bpgm]
module.ec2_site_instance[47].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-ckw6a8fm]
module.ec2_site_instance[35].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-5hkp8i4m]
module.ec2_site_instance[83].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-2xfe9tcm]
module.ec2_site_instance[93].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-ia86a6eq]
module.ec2_site_instance[62].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-9q76amnp]
module.ec2_site_instance[63].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-sk8y9qwm]
module.ec2_site_instance[55].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-tdyp8p6q]
module.ec2_site_instance[36].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-bc76axcp]
module.ec2_site_instance[76].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-pqq6a3ip]
module.ec2_site_instance[82].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-nqq69e6n]
module.ec2_site_instance[26].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-mxee8h6q]
module.ec2_site_instance[69].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-zxaebaem]
module.ec2_site_instance[64].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-99rpbinn]
module.ec2_site_instance[52].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-reye8ikp]
module.ec2_site_instance[65].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-hw76azeq]
module.ec2_site_instance[30].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-p14ya53n]
module.ec2_site_instance[54].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-ndry8c1n]
module.ec2_site_instance[49].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-5cq68c5q]
module.ec2_site_instance[95].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-g3jyb31p]
module.ec2_site_instance[45].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-qy3ebytp]
module.ec2_site_instance[41].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-n7ye9nnm]
module.ec2_site_instance[61].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-tq5e8e2m]
module.ec2_site_instance[32].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-cb76bfbn]
module.ec2_site_instance[46].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-kmzy81zm]
module.ec2_site_instance[20].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-egwp9t2m]
module.ec2_site_instance[31].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-tp9ebpjm]
module.ec2_site_instance[18].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-xgmebhfn]
module.ec2_site_instance[44].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-mmneb8kp]
module.ec2_site_instance[59].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-geq69z7p]
module.ec2_site_instance[92].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-4wy6a4xp]
module.ec2_site_instance[98].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-ssze8fzp]
module.ec2_site_instance[56].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-fbzebtmp]
module.ec2_site_instance[70].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-4e7eba8p]
module.ec2_site_instance[68].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-h2ye9f6m]
module.ec2_site_instance[15].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-rjnp876m]
module.ec2_site_instance[66].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-brspafyn]
module.ec2_site_instance[96].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-rbieba4n]
module.ec2_site_instance[99].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-6mjyakxp]
module.ec2_site_instance[74].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-g7ap83kq]
module.ec2_site_instance[67].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-hx8par9m]
module.ec2_site_instance[42].aws_spot_instance_request.this[0]: Refreshing state... [id=sir-gshp9qam]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 4218 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x221d240, 0x3ed5b10})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc004cbb270, {{}, 0x4d, {0xc000125d60, 0x19}, {0xc0006773f8, 0x4}}, {0xc00471cb00, 0x30, 0x4})
        /home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x3e, {0xc000867240, 0x0, 0xc00009c400}, {{}, 0x4d, {0xc000125d60, 0x19}, {0xc0006773f8, 0x4}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc001b439b0, {0xc000867240, 0x1, 0x1}, {{}, 0x4d, {0xc000125d60, 0x19}, {0xc0006773f8, 0x4}}, ...)
        /home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc00132b340, {{}, {0xc000867240, 0x1, 0x1}, {{}, 0x4d, {0xc000125d60, 0x19}, {0xc0006773f8, ...}}})
        /home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc002f0d000, {0x2aecc00, 0xc003460460})
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc002f0d000, {0x2aecc00, 0xc003460460})
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc003460460}, 0x80)
        /home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0012c1880, {0x2aecc00, 0xc003460460}, {0x7f1d797a88e0, 0xc002f0d000})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc002f0d000})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000e813e0, {0x2553ec0, 0xc002f0d000}, 0xc000f81f80)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf85

```

**Comment by elben10** [comment] 2021-12-15 09:04
+1

**Comment by pserrano** [comment] 2021-12-15 10:35
Same error here on apple M1 

```
terraform -v                                                                                                                                                                                                                                                                                                        ─╯
Terraform v1.1.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.57.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 8040 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x88
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x20
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:44 +0xe0
panic({0x102938660, 0x1040e8b10})
	runtime/panic.go:1038 +0x21c
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0x0, {{}, 0x4d, {0x1400118e4e0, 0x19}, {0x140011861c8, 0x4}}, {0x14005054d00, 0x1, 0x4})
	github.com/hashicorp/terraform/internal/instances/expander.go:392 +0x44
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x0, {0x14001067280, 0x0, 0x0}, {{}, 0x4d, {0x1400118e4e0, 0x19}, {0x140011861c8, 0x4}}, ...)
	github.com/hashicorp/terraform/internal/instances/expander.go:387 +0x26c
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x14002d3f608, {0x14001067280, 0x1, 0x1}, {{}, 0x4d, {0x1400118e4e0, 0x19}, {0x140011861c8, 0x4}}, ...)
	github.com/hashicorp/terraform/internal/instances/expander.go:385 +0x204
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0x140024f82e0, {{}, {0x14001067280, 0x1, 0x1}, {{}, 0x4d, {0x1400118e4e0, 0x19}, {0x140011861c8, ...}}})
	github.com/hashicorp/terraform/internal/instances/expander.go:157 +0x11c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0x140026da680, {0x102d9ad60, 0x140040702a0})
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:182 +0x2c0
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0x140026da680, {0x102d9ad60, 0x140040702a0})
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:140 +0x640
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x140026da680, {0x102d9ad60, 0x140040702a0}, 0x2)
	github.com/hashicorp/terraform/internal/terraform/node_resource_plan_orphan.go:49 +0x94
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14002b9a460, {0x102d9ad60, 0x140040702a0}, {0x12bbd5ee0, 0x140026da680})
	github.com/hashicorp/terraform/internal/terraform/graph_walk_context.go:133 +0x9c
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x102c61140, 0x140026da680})
	github.com/hashicorp/terraform/internal/terraform/graph.go:74 +0x244
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x1400393ae40, {0x102c61140, 0x140026da680}, 0x14004986b80)
	github.com/hashicorp/terraform/internal/dag/walk.go:381 +0x31c
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	github.com/hashicorp/terraform/internal/dag/walk.go:304 +0xe0c
Makefile:96: *** [plan] error 11
```

**Comment by yuri-1987** [comment] 2021-12-15 11:44
same here
```
terraform -v                                                                                                                                                                                                                                                                                                        
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/carlpett/sops v0.6.3
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v4.0.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/mumoshu/helmfile v0.14.1
```
---
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 4111 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:44 +0xb5
panic({0x2e20fa0, 0x4ae4070})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc0042fb270, {{}, 0x4d, {0xc000cfe2d0, 0x15}, {0xc00048db27, 0x7}}, {0xc001c66f00, 0x40, 0x4})
	/Users/distiller/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x79, {0xc0006ae6a0, 0x0, 0xc000580000}, {{}, 0x4d, {0xc000cfe2d0, 0x15}, {0xc00048db27, 0x7}}, ...)
	/Users/distiller/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc0005a8918, {0xc0006ae6a0, 0x1, 0x1}, {{}, 0x4d, {0xc000cfe2d0, 0x15}, {0xc00048db27, 0x7}}, ...)
	/Users/distiller/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc001810360, {{}, {0xc0006ae6a0, 0x1, 0x1}, {{}, 0x4d, {0xc000cfe2d0, 0x15}, {0xc00048db27, ...}}})
	/Users/distiller/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc002190430, {0x36f1e20, 0xc00112e2a0})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:204 +0x23b
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc002190430, {0x36f1e20, 0xc00112e2a0})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x36f1e20, 0xc00112e2a0}, 0xc0)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000b982a0, {0x36f1e20, 0xc00112e2a0}, {0x93d9f78, 0xc002190430})
	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x3158c00, 0xc002190430})
	/Users/distiller/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000b01620, {0x3158c00, 0xc002190430}, 0xc0019d8880)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0xf85
```

**Comment by alisdair** [comment] 2021-12-15 15:02
Thanks for the report! Closing as duplicate of #30110, which will be fixed in the next release.

**Closed by alisdair** 2021-12-15 15:02 UTC
Labels: bug, new
