### ISSUE TITLE
RDS: unexpected state 'resetting-master-credentials', wanted target 'available'

### ISSUE THREAD

**Issue by kerr23** [hashicorp/terraform#4588] opened 2016-01-08 23:20 UTC
Getting the following error on first spin up of RDS instance. running terraform apply a second time goes through.

`RDS: unexpected state 'resetting-master-credentials', wanted target 'available'`

I think this is similar to issue #119

**Comment by radeksimko** [comment] 2016-01-25 21:02
Closing as a duplicate of https://github.com/hashicorp/terraform/issues/4477 which has been also fixed in https://github.com/hashicorp/terraform/pull/4490

The bugfix is part the the latest release (`0.6.9`), can you try upgrading to the latest version and check if this works as expected?

If it doesn't work, feel free to reopen or open a new issue.

**Closed by radeksimko** 2016-01-25 21:02 UTC
Labels: bug, provider/aws
