### ISSUE TITLE
terraform cannot download random provider

### ISSUE THREAD

**Issue by christopherlynnsmith** [hashicorp/terraform#20119] opened 2019-01-25 18:19 UTC
Team, 

I need to use a random string while constructing resources

I did not get this error before.   I cannot seem to solve why I get an error downloading 

```
$ terraform init
2019/01/25 13:03:35 [INFO] Terraform version: 0.11.10  17850e9a55d33c43d7c31fd6ac122ba97a51d899
2019/01/25 13:03:35 [INFO] Go runtime version: go1.11.1
2019/01/25 13:03:35 [INFO] CLI args: []string{"C:\\data\\apps\\terraform\\terraform.exe", "init"}
2019/01/25 13:03:35 [DEBUG] Attempting to open CLI config file: C:\Users\chs2573\AppData\Roaming\terraform.rc
2019/01/25 13:03:35 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/01/25 13:03:35 [INFO] CLI command args: []string{"init"}
2019/01/25 13:03:35 [DEBUG] command: loading backend config file: C:\data\development\gitProjects\Ref.Cloud.GCP.Golden.CloudSQLMySQL
Initializing modules...
- module.cloudsql
2019/01/25 13:03:35 [INFO] command: empty terraform config, returning nil
2019/01/25 13:03:35 [DEBUG] command: no data state file found for backend config
2019/01/25 13:03:35 [DEBUG] New state was assigned lineage "62b9c1a0-7d37-cd06-305d-b008e1898e1f"
2019/01/25 13:03:35 [INFO] command: backend initialized: <nil>
2019/01/25 13:03:35 [DEBUG] checking for provider in "."
2019/01/25 13:03:35 [DEBUG] checking for provider in "C:\\data\\apps\\terraform"
2019/01/25 13:03:35 [DEBUG] checking for provider in ".terraform\\plugins\\windows_amd64"
2019/01/25 13:03:35 [DEBUG] found provider "terraform-provider-google_v1.20.0_x4.exe"
2019/01/25 13:03:35 [DEBUG] found valid plugin: "google", "1.20.0", "C:\\data\\development\\gitProjects\\Ref.Cloud.GCP.Golden.CloudSQLMySQL\\.terraform\\plugins\\windows_amd64\\terraform-provider-google_v1.20.0_x4.exe"
2019/01/25 13:03:35 [DEBUG] checking for provisioner in "."
2019/01/25 13:03:35 [DEBUG] checking for provisioner in "C:\\data\\apps\\terraform"
2019/01/25 13:03:35 [DEBUG] checking for provisioner in ".terraform\\plugins\\windows_amd64"
2019/01/25 13:03:35 [INFO] Failed to read plugin lock file .terraform\plugins\windows_amd64\lock.json: open .terraform\plugins\windows_amd64\lock.json: The system cannot find the file specified.
2019/01/25 13:03:35 [INFO] command: backend <nil> is not enhanced, wrapping in local
2019/01/25 13:03:35 [DEBUG] checking for provider in "."
2019/01/25 13:03:35 [DEBUG] checking for provider in "C:\\data\\apps\\terraform"
2019/01/25 13:03:35 [DEBUG] checking for provider in ".terraform\\plugins\\windows_amd64"
2019/01/25 13:03:35 [DEBUG] found provider "terraform-provider-google_v1.20.0_x4.exe"
2019/01/25 13:03:35 [DEBUG] found valid plugin: "google", "1.20.0", "C:\\data\\development\\gitProjects\\Ref.Cloud.GCP.Golden.CloudSQLMySQL\\.terraform\\plugins\\windows_amd64\\terraform-provider-google_v1.20.0_x4.exe"

2019/01/25 13:03:35 [DEBUG] plugin requirements: "google"="~> 1.20"
Initializing provider plugins...
2019/01/25 13:03:35 [DEBUG] plugin requirements: "random"=""
- Checking for available provider plugins on https://releases.hashicorp.com...
2019/01/25 13:03:35 [DEBUG] fetching provider info for random version 2.0.0
- Downloading plugin for provider "random" (2.0.0)...
2019/01/25 13:03:35 [DEBUG] getting provider "random" version "2.0.0"
2019/01/25 13:03:35 [DEBUG] plugin cache is disabled, so downloading random 2.0.0 from https://releases.hashicorp.com/terraform-provider-random/2.0.0/terraform-provider-random_2.0.0_windows_amd64.zip?checksum=sha256:a8b6caeaf29e54e3fb0653a448db350c5992281de46b573e89ff5e54531cd7a3
2019/01/25 13:03:36 [ERROR] 1 error(s) occurred:

* bad response code: 403

2019/01/25 13:03:36 [DEBUG] plugin: waiting for all plugin processes to complete...
Error installing provider "random": bad response code: 403.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/windows_amd64
```

**Comment by apparentlymart** [comment] 2019-01-25 18:33
Hi @christopherlynnsmith! I'm sorry this didn't work as expected.

Unfortunately I was not able to reproduce this problem and was able to download the Windows version of the random provider as expected. :confounded:

Is there anything unusual about your environment, such as a transparent or mandatory proxy between your machine and remote servers?

403 is what tends to get returned for unknown files on that server (an unfortunate side-effect of the configuration of the underlying Amazon S3 bucket) so it could potentially have been the server returning a not found error, but since the `random` provider has been published for five months now I don't know why it would've been temporarily not found. :thinking: 

Is this error persistent, or does retrying change the behavior?

**Comment by christopherlynnsmith** [comment] 2019-01-25 18:35
hmm, it just showed up today after I removed the random provider yesterday.

it seems to be network related, but I am not creating provider resource..

**Comment by enriqueojedalara** [comment] 2019-11-07 03:35
Hi @christopherlynnsmith my two cents:

1) I fixed the same problem installing manually the provider in ~/.terraform.d/plugins/linux_amd64 (I think in your case you should locate the terraform folder and install manually the provider

2) also I found the same issue, pretty weird, but the folder terraform.d/plugins/ did not exists, I created manually the folder and problem fixed.

**Comment by apparentlymart** [comment] 2020-06-30 00:52
Hi @christopherlynnsmith! Sorry for the long silence here.

It sounds like whatever was going on here was transient and has now resolved itself. We've not seen this reported again in the meantime, so unfortunately it seems like we're not going to be able to fully explain what happened here.

As we move into Terraform 0.13, providers are moving into the Terraform Registry instead of the mechanism Terraform 0.11 used, and so it's also likely that whatever caused the problem here will not be around for much longer, and that if something like this were to occur again in future it would appear in a different way and we'd therefore be unlikely to make the connection back to this issue.

With all of that said, I'm going to close this out to represent that there doesn't seem to be any action we could take on it now. If something like this arises again in future then we'll hopefully see a new issue including whatever is the modern equivalent of this error message, and then we can debug it further.

Thanks for reporting this, and sorry we weren't able to explain what happened here.

**Closed by apparentlymart** 2020-06-30 00:52 UTC
Labels: bug, cli, v0.11
