### ISSUE TITLE
Terraform crash on multiple provisioners

### ISSUE THREAD

**Issue by andrew-morris** [hashicorp/terraform#6878] opened 2016-05-25 19:37 UTC
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
Terraform Core (?)

### Terraform Configuration Files
```hcl

	provisioner "remote-exec" {

			inline = [
        "powershell -Command Set-ExecutionPolicy unrestricted",
			]

	connection = {
                type = "winrm"
                user = "${var.admin_user}"
                password = "${var.admin_password}"
                }
  }

	provisioner = "remote-exec" {
			script = "scripts/apply_static_ip.ps1"
	
	connection = {
                type = "winrm"
                user = "${var.admin_user}"
                password = "${var.admin_password}"
                }
	}
}

```

### Debug Output
https://gist.github.com/andrew-morris/c6d2313925ac4171bc8441fd980e3fb5

### Panic Output
https://gist.github.com/andrew-morris/031bd9ce09ccb90ee6b8ba303d5cbe4a

### Expected Behavior
I attempted to execute `terraform plan` or `terraform apply`

### Actual Behavior
Terraform crashed

### Other Notes
When I comment out the second provisioner, the crash doesn't occur
```hcl
	provisioner "remote-exec" {

			inline = [
        "powershell -Command Set-ExecutionPolicy unrestricted",
			]

	connection = {
                type = "winrm"
                user = "${var.admin_user}"
                password = "${var.admin_password}"
                }
  }

#	provisioner = "remote-exec" {
#			script = "scripts/apply_static_ip.ps1"
#	
#	connection = {
#                type = "winrm"
#                user = "${var.admin_user}"
#                password = "${var.admin_password}"
#                }
#	}
#}

**Comment by sl1pm4t** [comment] 2016-05-27 02:14
The problem is not the fact there are multiple provisioners.
Terraform doesn't like the equals ( = ) character in `provisioner = "remote-exec"` in your second provisioner block.
If you delete the equals, the config is parsed OK.

Strangely it doesn't have any issue with the = in `connection = {`

**Comment by jbardin** [comment] 2016-06-22 20:17
Hi,

Just confirming that this is a bug caused by invalid HCL syntax. This will be fixed once hashicorp/hcl#134 is merged and we update the dependency in terraform.

**Comment by jen20** [comment] 2016-06-24 12:08
Yup, just repro'd this and validated it (via HclFmt!) as being fixed by the `=`. I'll update HCL now.

**Comment by jen20** [comment] 2016-06-24 12:31
The error message here is still not ideal with the original content, but the following file works correctly:

```
variable "admin_user" {
  default = "test"
}

variable "admin_password" {
  default = "test"
}

resource "null_resource" "test" {
  provisioner "remote-exec" {
    inline = [
      "powershell -Command Set-ExecutionPolicy unrestricted",
    ]

    connection {
      type     = "winrm"
      user     = "${var.admin_user}"
      password = "${var.admin_password}"
    }
  }

  provisioner "remote-exec" {
    script = "scripts/apply_static_ip.ps1"

    connection {
      type     = "winrm"
      user     = "${var.admin_user}"
      password = "${var.admin_password}"
    }
  }
}
```

**Closed** 2016-06-24 12:31 UTC
Labels: bug, core, release-0.7
