### ISSUE TITLE
Ternary operator evaluates both expressions and returns null if unused part  fails

### ISSUE THREAD

**Issue by forgieee** [hashicorp/terraform#22250] opened 2019-07-30 10:06 UTC
# Terraform Version
```
Terraform v0.12.4
```

### Terraform Configuration Files
```hcl
output "test_panic_true" {
  value = true ?  [] : chunklist([],2)
}

output "test_panic_false" {
  value = false ?  chunklist([],2) : []
}
 # This output is correct and added just to compare
output "test_no_panic" {
  value = false ?  chunklist(["a","b","c","d"],2) : []
```

### Debug Output
https://gist.github.com/forgieee/ad94d309f911b84200a4f8cb52a38919

### Expected Behavior
"test_panic_true" should return []
"test_panic_false" should return []

### Actual Behavior
It seems, that both "test_panic_true" and "test_panic_false" outputs return null, and as a result i see no outputs, except "test_no_panic" one. I'm not sure if ternary returns null or some other strange value type, but it obviously breaks logic. 
```
forgie@forgie-VirtualBox ~/git/terraform/test_inter $ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

test_no_panic = []
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
VirtualBox Version 6.0.4 r128413 (Qt5.6.2)
LinuxMint 18.3
Bash

**Comment by teamterraform** [comment] 2019-07-30 15:19
Hi @forgieee, thank you for submitting this! I was able to reproduce the problem in terraform 0.12.4 and terraform 0.12.5, but it looks like it's already been fixed in master:

Panic in 0.12.4/0.12.5:
```
[/tmp/scratch]# tf version
Terraform v0.12.4
[/tmp/scratch]# tf apply --auto-approve

Error: Error in function call

  on main.tf line 10, in output "chunk":
  10:   value = chunklist([],2)

Call to function "chunklist" failed: panic in function implementation: must
not call ListVal with empty slice
goroutine 13 [running]:
[ ... etc ] 
```

Terraform 0.12.6 (built from master, not released yet): 
```
[/tmp/scratch]# terraform version
Terraform v0.12.5-60-g447fe6298 (447fe629865a81fa139ef7fa7f6115e744053d7d)
[/tmp/scratch]# terraform apply --auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

chunk = []
test_no_panic = []
test_panic_false = []
test_panic_true = []
```

I am going to close this, as it's already fixed in master, but thank you again for opening the issue and the detailed reproduction case.

**Closed by teamterraform** 2019-07-30 15:19 UTC
Labels: bug
