### ISSUE TITLE
null value not working with && operator

### ISSUE THREAD

**Issue by Raghav2211** [hashicorp/terraform#27571] opened 2021-01-22 15:29 UTC
### Terraform Version
 ```
Terraform v0.13.5
 ``` 

### Terraform Configuration Files
 `main.tf`:
 
 ```terraform
 module test {
   source         = "./module1"
 }
 ```
 
 `module1/main.tf`:
 
 ```terraform
 variable test_null {
    type    = number
    default = null
 }

 locals {
    test_null  = var.test_null != null && var.test_null > 0 ? var.test_null : 1
 }
 
 ```
 

 ### Actual Behaviour
  test_null                = var.test_null != null && var.test_null > 0 ? var.test_null : 1
    |----------------
    | var.test_null is null

Error during operation: argument must not be null.
 

 ### Expected Behaviour
 `local.test_null` should be successfully evaluated as 1

**Comment by jbardin** [comment] 2021-01-22 15:40
Thanks @Raghav2211, marking as a duplicate of #24128

**Closed by jbardin** 2021-01-22 15:40 UTC
Labels: bug, new
