### ISSUE TITLE
`terraform add -from-state` shouldn't output computed attributes

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#29219] opened 2021-07-22 02:14 UTC
### Terraform Version

```
Terraform v1.1.0-alpha20210714
on linux_amd64

```

### Expected Behavior

Though there is code to exclude those computed only attributes: https://github.com/hashicorp/terraform/blob/55ebb2708c5c5538555ce21880f2bac4744292f4/internal/command/views/add.go#L150
While the special attributes `id` and `timeouts` are not excluded in this case, which should be avoided in fact.

On the other hand, some nested block are marked with `SchemaConfigModeAttr` will not contain the attribute properties like `Required`, `Optional`, `Comptued`. This results into the `terraform add` command include all the attributes in those block, regardless whether it is `Computed` only or not. One example is the `id` attribute of the `subnet` block in the `azurerm_virtual_network`.

**Comment by magodo** [comment] 2021-07-29 01:11
Kindly ping @mildwonkey :)

**Comment by jbardin** [comment] 2021-08-12 15:05
Hi @magodo, yes, it sounds correct that computed-only attributes should not be included in the output, since they are not valid configuration values. I however have not been able to reproduce this with top-level computed attributes. Do you have a specific example?

Unfortunately the way `SchemaConfigModeAttr` is implemented there is no way to do this as you've mentioned, and any optional attributes stored in this way are going to be shown in their entirety. Since `SchemaConfigModeAttr` was implemented as a workaround for legacy provider behavior, we hope that resources using this will be able to eventually move away from it, especially once the new plugin framework is ready for production use.

**Comment by magodo** [comment] 2021-08-13 01:18
Hey @jbardin, thank you for confirming that `SchemaConfigModeAttr` is not keeping those state properties.

For the top-level computed attributes, I was actually indicating the `id`:

```shell

💤 tf add -from-state azurerm_virtual_network.test
resource "azurerm_virtual_network" "test" {
  address_space       = ["192.0.0.0/16"]
  bgp_community       = ""
  dns_servers         = []
  id                  = "/subscriptions/*-*-*-*/resourceGroups/acceptanceTestResourceGroup2000/providers/Microsoft.Network/virtualNetworks/virtualNetwork1"
  location            = "westus"
  name                = "virtualNetwork1"
  resource_group_name = "acceptanceTestResourceGroup2000"
  subnet = [{
    address_prefix = "192.0.1.0/24"
    id             = "/subscriptions/*-*-*-*/resourceGroups/acceptanceTestResourceGroup2000/providers/Microsoft.Network/virtualNetworks/virtualNetwork1/subnets/subnet1"
    name           = "subnet1"
    security_group = "/subscriptions/*-*-*-*/resourceGroups/cleanupservice/providers/Microsoft.Network/networkSecurityGroups/rg-cleanupservice-nsg1"
  }]
  tags                  = {}
  vm_protection_enabled = false
  timeouts {
    create = null
    delete = null
    read   = null
    update = null
  }
}
```

The `id` is defined as `Computed` + `Optional`, that's why it is output. While it actually shouldn't.

**Comment by jbardin** [comment] 2021-08-13 13:49
Thanks, having `id` be optional would cause it to show up. According to the schema, that attribute is valid to set in the configuration, so we must honor it as optional attribute. While the existence of computed+optional attributes is one of the fundamental problems with attempting to generate configuration from state, I think the idea is to always err on the side of adding those fields when requested, since it's easier to remove the unwanted lines in the generated config than it is to manually lookup the attributes and add them in when they really are needed.

**Comment by magodo** [comment] 2021-08-14 01:59
I might be dumb here, but if I apply/plan a config with `id` defined, terraform will complain that there is no such attribute defined:

```shell
│ Error: Invalid or unknown key
│ 
│   with azurerm_virtual_network.test,
│   on main.tf line 5, in resource "azurerm_virtual_network" "test":
│    5:   id                  = "****"
```

**Comment by magodo** [comment] 2021-08-15 00:43
@jbardin There is another example that causes issues by the O+C attributes:

```shell
.cache/tfy/rg-tfy via 💠 default
💤 tf add -from-state azurerm_storage_account.test > main.tf

.cache/tfy/rg-tfy via 💠 default
💤 cat main.tf
resource "azurerm_storage_account" "test" {
  access_tier               = "Hot"
  account_kind              = "StorageV2"
  account_replication_type  = "GRS"
  account_tier              = "Standard"
  allow_blob_public_access  = false
  enable_https_traffic_only = true
  id                        = "/subscriptions/****/resourceGroups/rg-tfy/providers/Microsoft.Storage/storageAccounts/storageaccountnametfy"
  is_hns_enabled            = false
  large_file_share_enabled  = null
  location                  = "westeurope"
  min_tls_version           = "TLS1_0"
  name                      = "storageaccountnametfy"
  nfsv3_enabled             = false
  resource_group_name       = "rg-tfy"
  tags                      = {}
  blob_properties {
    change_feed_enabled      = false
    default_service_version  = ""
    last_access_time_enabled = false
    versioning_enabled       = false
  }
  network_rules {
    bypass                     = ["AzureServices"]
    default_action             = "Allow"
    ip_rules                   = []
    virtual_network_subnet_ids = []
  }
  queue_properties {
    hour_metrics {
      enabled               = true
      include_apis          = true
      retention_policy_days = 7
      version               = "1.0"
    }
    logging {
      delete                = false
      read                  = false
      retention_policy_days = 0
      version               = "1.0"
      write                 = false
    }
    minute_metrics {
      enabled               = false
      include_apis          = false
      retention_policy_days = 0
      version               = "1.0"
    }
  }
  share_properties {
    retention_policy {
      days = 7
    }
  }
  timeouts {
    create = null
    delete = null
    read   = null
    update = null
  }
}

.cache/tfy/rg-tfy via 💠 default
💤 tf plan
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/azurerm in /home/magodo/go/bin
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
╷
│ Error: Invalid or unknown key
│
│   with azurerm_storage_account.test,
│   on main.tf line 8, in resource "azurerm_storage_account" "test":
│    8:   id                        = "/subscriptions/****/resourceGroups/rg-tfy/providers/Microsoft.Storage/storageAccounts/storageaccountnametfy"
│
╵
╷
│ Error: expected blob_properties.0.default_service_version to be one of [2008-10-27 2009-04-14 2009-07-17 2009-09-19 2011-08-28 2012-02-12 2013-08-15 2014-02-14 2015-02-21 2015-04-05 2015-07-08 2015-12-11 2016-05-31 2017-04-17 2017-07-29 2017-11-09 2018-03-28 2018-11-09 2019-02-02 2019-07-07 2019-12-12 2020-02-10 2020-04-08 2020-06-12], got
│
│   with azurerm_storage_account.test,
│   on main.tf line 19, in resource "azurerm_storage_account" "test":
│   19:     default_service_version  = ""
│
╵
╷
│ Error: expected queue_properties.0.logging.0.retention_policy_days to be in the range (1 - 365), got 0
│
│   with azurerm_storage_account.test,
│   on main.tf line 39, in resource "azurerm_storage_account" "test":
│   39:       retention_policy_days = 0
│
╵
╷
│ Error: expected queue_properties.0.minute_metrics.0.retention_policy_days to be in the range (1 - 365), got 0
│
│   with azurerm_storage_account.test,
│   on main.tf line 46, in resource "azurerm_storage_account" "test":
│   46:       retention_policy_days = 0
│
```

There are several issues in above example:

1. The `id` is not a valid attribute: this is tracked by #29219 
2. The `retention_policy_days` doesn't pass the validation rule defined by the schema
3. The `default_service_version` doesn't pass the validation rule defined by the schema

All the attributes that result into error are optional & computed.

In case of `-from-state`, I feel the end goal here is to make sure the generated config has no plan diff. So how about we simply skipping the attributes that is `Computed`, rather than checking it is neither `Required` or `Optional`? This will makes those O+C attributes being skipped. But since they are O+C, there will be no plan diff.

**Comment by jbardin** [comment] 2021-08-16 18:25
Thanks for the extra info @magodo.

What you are seeing here is all due to inconsistencies within the legacy SDK. The first issue is that `id` is usually implicitly added by the SDK, and while it is a normal attribute as far as Terraform is concerned, it requires special handling on the SDK side that Terraform is not aware of.

For the empty values, the SDK cannot reliably differentiate between unset and zero values, so `0` and `""` will be inserted in many cases where they are not present in the configuration. 

Blocks are a problem as well, because the block itself is not optional are nested blocks are not computed, meaning that they always exist but may contain 0 or more object values in the configuration. Nested, computed block values are not valid, because blocks only exist in the configuration. We still allow these values to pass for backwards compatibility, but usually are flagged as warnings in the core logs. I think this might still work if a "computed" block also marks all attributes as computed, but I'd have to double check.

These are some of the reasons why `terraform add` is intended to be an experimental feature to help guide users when creating a configuration for imported resources, but cannot reliably generate configuration for the majority of existing cases.

**Comment by apparentlymart** [comment] 2021-08-17 01:04
While I was prototyping configuration generation for import I encountered [various quirks](https://github.com/apparentlymart/terrafy/blob/37cb75797fb0a6fda5366a91084523a51a47c75f/docs/quirks.md), many of which are caused by odd behaviors in the SDK or providers and thus can't be addressed by Terraform itself.

`terraform add` has a smaller scope than my prototype (it only generates configuration for a single resource, and _doesn't_ also try to handle `count`/`for_each`/etc) so not all of those quirks apply, but I expect several of them do (and it includes two of the ones discussed above, already).

**Comment by magodo** [comment] 2021-08-17 01:36
@apparentlymart I'm doing the [same thing](https://github.com/magodo/tfy) these days (even the naming of the project :smile: )

**Comment by apparentlymart** [comment] 2022-04-28 01:11
Hi again!

I just noticed that we missed closing this issue when we removed `terraform add` prior to including it in a stable release. Since this command doesn't exist in any released version of Terraform, I'm going to close this.

Thanks for reporting this! Hopefully we'll eventually have a similar feature which will not have a bug like was reported here. :grinning:

**Closed by apparentlymart** 2022-04-28 01:11 UTC
Labels: bug, cli, import
