### ISSUE TITLE
Setting platform_fault_domain to the default value (-1) breaks the plan

### ISSUE THREAD

**Issue by alisson276** [hashicorp/terraform#30622] opened 2022-03-06 09:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.0.5
* AzureRM Provider version: 2.78.0

### Terraform Configuration Files

```json
{
	"provider": {
		"azurerm": {
			"features": {},
			"skip_provider_registration": true,
			"subscription_id": "<SUBSCRIPTION_ID>"
		}
	},
	"resource": {
		"azurerm_linux_virtual_machine": {
			"example-vm": {
				"admin_ssh_key": [{
					"public_key": "<SSH_KEY>",
					"username": "adminuser"
				}],
				"admin_username": "adminuser",
				"allow_extension_operations": true,
				"computer_name": "example-vm",
				"disable_password_authentication": true,
				"extensions_time_budget": "PT1H30M",
				"lifecycle": {
					"prevent_destroy": true
				},
				"location": "West Europe",
				"max_bid_price": -1,
				"name": "example-vm",
				"network_interface_ids": ["/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/example/providers/Microsoft.Network/networkInterfaces/nic-example"],
				"os_disk": [{
					"caching": "ReadWrite",
					"storage_account_type": "Standard_LRS"
				}],
				"platform_fault_domain": -1,
				"priority": "Regular",
				"provision_vm_agent": true,
				"resource_group_name": "example",
				"size": "Standard_D2as_v5",
				"source_image_reference": [{
					"offer": "0001-com-ubuntu-server-focal",
					"publisher": "Canonical",
					"sku": "20_04-lts-gen2",
					"version": "latest"
				}]
			}
		}
	},
	"terraform": {
		"required_providers": {
			"azurerm": {
				"source": "hashicorp/azurerm",
				"version": "2.78.0"
			}
		}
	}
}
```

### Description / Feedback

The plan fails when setting the default value `-1` to platform_fault_domain, saying:
```
Error: Missing required argument
with azurerm_linux_virtual_machine.example-vm,
│   on main.tf.json line 1, in resource.azurerm_linux_virtual_machine.example-vm:
[...]
"platform_fault_domain": all of `platform_fault_domain,virtual_machine_scale_set_id` must be specified
```

Removing the `platform_fault_domain` from the plan the error stopped to happen.

**Comment by jbardin** [comment] 2022-03-07 14:13
Hi @tombuildsstuff,

Can you elaborate on what the expected behavior is here? The error is coming from the plugin SDK, because `platform_fault_domain` specifies `RequiredWith: []string{"virtual_machine_scale_set_id"}`. I think this would mean that `virtual_machine_scale_set_id` must be set to something _other_ than `null` in order to be properly validated.

**Comment by alisson276** [comment] 2022-03-07 15:58
@jbardin , the question is, the `platform_fault_domain = -1` is the default from terraform (according to the documentation), if I set the same value as default it shouldn't raise an error, right?

Let me "transcript" it to HCL and see if the same error happen.

**Comment by jbardin** [comment] 2022-03-07 16:06
@alisson276, That's kind of what I'm trying to clarify here, i.e. what are the expectations from the provider in this case?

The "default" value is different from having it in the configuration, because a default is in essence a type of computed value. The schema validation is stating that neither or both must be declared in the configuration, but I don't think the legacy SDK will be able to correctly use that type of validation with a default value. The initial validation may work with neither set because they won't be supplied via the configuration, but when terraform returns the proposed value including the default in a subsequent plan, I'm not sure the SDK isn't going to be able to differentiate that from an invalid config.

**Comment by alisson276** [comment] 2022-03-07 16:50
Side node: using the HCL format raises the same error:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.78.0"
    }
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true
  subscription_id = "<SUBSCRIPTION_ID>"
}

resource "azurerm_linux_virtual_machine" "example-vm" {
  admin_ssh_key {
    public_key = "<SSH_PUB_KEY>"
    username = "adminuser"
  }

  admin_username = "adminuser"
  allow_extension_operations = true
  computer_name = "example-vm"
  disable_password_authentication = true
  extensions_time_budget = "PT1H30M"

  lifecycle {
    prevent_destroy = true
  }

  location = "West Europe"
  max_bid_price = -1
  name = "example-vm"
  network_interface_ids = ["/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/example/providers/Microsoft.Network/networkInterfaces/nic-example"]
  os_disk {
    caching = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }
  platform_fault_domain = -1
  priority = "Regular"
  provision_vm_agent = true
  resource_group_name = "example"
  size = "Standard_D2as_v5"
  source_image_reference {
    offer = "0001-com-ubuntu-server-focal"
    publisher = "Canonical"
    sku = "20_04-lts-gen2"
    version = "latest"
  }
}

**Comment by jbardin** [comment] 2022-03-07 17:10
The Terraform CLI has no concept of default resource attributes or any information about them from the schema, they are entirely handled within the provider as a plan-time form of computed values. Both the setting of the default and the validation of the values are happening outside of the control of the CLI.

**Comment by alisson276** [comment] 2022-03-07 17:14
Ok. I found the "problem" (not sure if it's a problem): https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/schema.go#L784, here the value for `RequiredWith` is checked, but there is no validation about the default value. Do you think is relevant to open a feature request here (terraform-plugin-sdk) or, in your vision, the current behavior is the correct approach?

**Comment by apparentlymart** [comment] 2022-03-07 20:53
From Terraform Core's perspective, setting something to `null` (or omitting it entirely) is semantically different than setting it to what a provider might've chosen automatically, because if it's unset then the provider has license to change its value in the future, for example if the default value were to change, whereas if you've explicitly set it to `-1` then the provider is required to use exactly that value.

At has already been said, it's ultimately up to the provider plugin to decide what to do in these two cases, and in this case the provider itself (via logic in the SDK) seems to be deciding to treat the default value the same as omitted for validation purposes. I expect it's debatable what logic is "better" here, because the SDK by default doesn't expose to providers the difference between explicitly setting a value that happens to match the default vs. leaving the argument unset: both of those get conflated together in the `ResourceData` abstraction and so providers will often _assume_ that the default value means the argument wasn't set. `RequiredWith` behaving this way might therefore be essential for some existing provider implementations, if e.g. the underlying API itself doesn't distinguish between an unset value and setting it to the default, and might therefore raise the same error one level deeper.

Opening an SDK issue to discuss this is probably the best path forward, but I would also expect it to be difficult to change this behavior retroactively in case existing providers are relying on it. Still worth discussing and thinking through anyway, because it will hopefully lead to improving on this situation in [the new plugin framework](https://github.com/hashicorp/terraform-plugin-framework) if necessary, and if it's a significant problem it may be possible for the legacy SDK to support both behaviors by making the behavior you expected an opt-in that the provider developer can choose on a per-resource-type basis.

**Comment by jbardin** [comment] 2022-04-06 15:23
Since there doesn't appear to be anything further to be dome with the Terraform CLI in this case, I'm going to close the issue. Feel free to follow up with the plugin framework project if there is anything he SDK can do to help with the provider development.

Thanks!

**Closed by jbardin** 2022-04-06 15:23 UTC
Labels: waiting-response, new
