### ISSUE TITLE
templatefile function does not ignore the square brackets in the .tpl templates

### ISSUE THREAD

**Issue by mehulgogri** [hashicorp/terraform#25848] opened 2020-08-13 19:52 UTC
### Terraform Version

```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/terraform-providers/openstack v1.30.0

```

### Terraform Configuration Files

```terraform
template.tf

data "null_data_source" "vip_inventory" {
  inputs = {
    template = templatefile("vip_inventory.tpl", {
      kube_master_ips      = 1.1.1.1
      kube_master_vip      = 2.2.2.2
      kube_master_vip_port = 1234
      availability_zone    = zone1
      resource_network     = net_zone1
      image_ssh_password   = abc123
    })
  }
}

resource "null_resource" "vip_inventory" {
  depends_on = [data.null_data_source.vip_inventory]
  provisioner "local-exec" {
    command = "echo ${data.null_data_source.vip_inventory.outputs["template"]} > vip_inventory.ini"
  }
}




vip_inventory.tpl

#
# These are used by devops code to set up the VIP.
#
[kube_master]
master  ansible_host=${kube_master_ips}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_connection=ssh
ansible_ssh_user=root
ansible_ssh_pass=${image_ssh_password}

VIP_address=${kube_master_vip}
VIP_port=${kube_master_vip_port}
VIP_project=${availability_zone}
VIP_network=${resource_network}
```

### Expected Behavior
Expected behavior is that all the variables are passed into the template and vip_inventory.ini is created with the content of the template.

### Actual Behavior
Empty vip_inventory.ini is created
Also getting following logs::

null_resource.vip_inventory (local-exec): Executing: ["/bin/sh" "-c" "echo #\n# These are used by devops code to set up the VIP.\n#\n[kube_master]\nmaster  ansible_host=10.91.2.232\n\n[all:vars]\nansible_ssh_common_args='-o StrictHostKeyChecking=no'\nansible_connection=ssh\nansible_ssh_user=root\nansible_ssh_pass=toor\n\nVIP_address=\nVIP_port=fa:16:3e:da:2a:ba\nVIP_project=devops\nVIP_network=devops_net > vip_inventory.ini"]

null_resource.vip_inventory (local-exec): /bin/sh: 4: [kube_master]: not found
null_resource.vip_inventory (local-exec): /bin/sh: 5: master: not found
null_resource.vip_inventory (local-exec): /bin/sh: 7: [all:vars]: not found

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
I do not see this issue when rendering the same template using template_file in the data block

**Comment by danieldreier** [comment] 2020-08-13 22:37
Hello @mehulgogri!

Using local-exec for template file generation is not necessary. I tested the following code on terraform 0.13, and it worked:

```hcl
resource "local_file" "vip_inventory" {
  content = templatefile("vip_inventory.tpl", {
      kube_master_ips      = "1.1.1.1"
      kube_master_vip      = "2.2.2.2"
      kube_master_vip_port = "1234"
      availability_zone    = "zone1"
      resource_network     = "net_zone1"
      image_ssh_password   = "abc123"
    })
  filename = "${path.module}/vip_inventory.ini"
}
```

I'm fairly confident this is not a bug, so I'm going to close it. Please let me know if you are confident that this is a bug and would like to work on it further.

**Closed by danieldreier** 2020-08-13 22:37 UTC
Labels: bug, new

**Comment by mehulgogri** [comment] 2020-08-14 13:51
Thanks @danieldreier for your suggestion. 
local_file resource worked out for me as well to render the template and creating this rendered template locally.
