### ISSUE TITLE
Terraform plans to destroy existing resources even though configuration .tf file exists

### ISSUE THREAD

**Issue by UdhavPawar** [hashicorp/terraform#33970] opened 2023-10-03 22:35 UTC
### Terraform Version

```shell
Terraform v1.4.5
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

Below is a sample .tf which simply creates EBS volume and instance. The contents of the .tf file won't matter for this issue as much as presence of file itself.

```
locals {
  instance_type     = "t3.2xlarge"
  instance_ami      = "ami-02a89cbcded39bf14"
  instance_key_pair = "stage"
}

// Create EBS Volume
resource "aws_ebs_volume" "test_ebs_vol" {
  availability_zone = "us-east-1f"
  size              = 60
  type              = "gp2"
  encrypted         = "true"
  tags = {
    Name = "test"
  }
}

// Create Instance
resource "aws_instance" "test_instance" {
  ami                    = local.instance_ami
  instance_type          = local.instance_type
  subnet_id              = "${module.network.out_subnet_public_ids}" [0]
  source_dest_check      = "true"
  iam_instance_profile   = "aws-elasticbeanstalk-ec2-role"
  vpc_security_group_ids = [module.securitygroups.out_security_groups["FeatureEnvironmentsEc2"].id]
  key_name               = local.instance_key_pair
  ebs_optimized          = "true"
  root_block_device {
    volume_size = 120
  }
  tags = {
    Name = "test"
  }
  depends_on = [aws_ebs_volume.ease_fe_ebs_vol]
}
```

### Debug Output

TF plan output which plans to destroy existing EBS volume resource defined in `test.tf`
```
# aws_ebs_volume.test_ebs_vol will be destroyed
# (because aws_ebs_volume.test_ebs_vol is not in configuration)
- resource "aws_ebs_volume" "test_ebs_vol" {
    - type             = "gp2" -> null
    ...
  }
```

### Expected Behavior

1. As `test.tf` exists locally in same directory (along with other local .tf files) where TF is being run.
2. Expect TF to include `test.tf` just like every other file when calculating TF plan and applying it. 

### Actual Behavior

1. Even though `test.tf` exists locally TF simply doesn't see it.
2. Hence upon running TF plan we see that TF plans to destroy all resources defined in `test.tf`.
3. Interestingly this is only happening for that 1 file, rest all resources defined in same directory are intact.

### Steps to Reproduce

1. In our TF initialized dir, create a `.tf` file with any sample config.
2. Create resources with `terraform apply`.
3. Subsequent `terraform plan` should show that it plans to destroy resources even though that file still exists.

### Additional Context

Please note following:
1. Files hierarchy is as follows, just standard setup.
```
├── .terraform/
├── .terraform.lock.hcl
├── provider.tf
├── backend.tf
├── test.tf
└── other.tf
```
2. All resources in the `test.tf` file were originally created via TF.
3. `terraform state show` still shows the existing correct resources.
4. Verified entire dir configuration is valid with `terraform validate`.
5. Even tried refreshing remote state with `terraform refresh`.
6. Everything was operating as expected until few days back when all of sudden one TF plan showed that it planned to destroy resources even though that particular file had no config changes.
7. Solutions tried so far:
- renaming the `test.tf` file.
- dropping resources from state and manually importing them back.
- upgrading TF and aws provider versions.

**Comment by liamcervante** [comment] 2023-10-04 07:39
Hi @UdhavPawar, thanks for filing this!

Is this just the `aws_ebs_volume` resource that is affected? Other resources within `test.tf` do not show up as to-be-destroyed? You mentioned the content of the file doesn't matter, but I see you didn't include the `aws_instance` in the plan output as also being destroyed?

And for clarification, none of your attempted solutions made any difference? The plan output was exactly the same?

Thanks!

**Comment by UdhavPawar** [comment] 2023-10-04 16:06
> Hi @UdhavPawar, thanks for filing this!
> 
> Is this just the `aws_ebs_volume` resource that is affected? Other resources within `test.tf` do not show up as to-be-destroyed? You mentioned the content of the file doesn't matter, but I see you didn't include the `aws_instance` in the plan output as also being destroyed?
> 
> And for clarification, none of your attempted solutions made any difference? The plan output was exactly the same?
> 
> Thanks!

Hey @liamcervante thanks for quick response. Yes, none of the mentioned attempts worked and correct, just to keep things simple took EBS volume as example but all resources in that file are affected. In production version of `test.tf`, I've volume, instance, public ALB, target groups and attaching instance to target groups (113 total resources all planned for deletion).

**Comment by liamcervante** [comment] 2023-10-05 06:12
Thanks for the extra context. I haven't been able to replicate this yet. 

The fact that changing the filename doesn't fix the issue makes me think there must be something in that config file that is 
causing this, but I can't think what.

Some more questions:


  - Is it just AWS resources you have in that file that is being ignored?
    - If so, if you add another resource in there from another provider, something simple like a time_sleep or a local_file, does that make any difference?
  - If you distribute the resources in the bad file between the known good files, does that cause the other files to be ignored or do the resources start working?
  - What's the environment this is is executing in? Is it happening locally, in Terraform Cloud or some other CI/CD pipeline?

> Everything was operating as expected until few days back when all of sudden one TF plan showed that it planned to destroy resources even though that particular file had no config changes.

 - Was there anything else to prompt this change? Like updating Terraform to v1.4.5. 

And just to cover all bases, you don't have a .terraformignore file or a .gitignore file that might be messing with things?

Thanks!

**Comment by UdhavPawar** [comment] 2023-10-06 19:59
Those are some good Qs @liamcervante 

1. Yes that file has all aws resources. Added time_sleep for 5 secs but still same.
```
Initializing provider plugins...
- Finding latest version of hashicorp/time...
- Reusing previous version of hashicorp/template from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (signed by HashiCorp)
- Using previously-installed hashicorp/template v2.2.0
- Using previously-installed hashicorp/aws v4.67.0
```
Resource definition in test.tf:
```
resource "time_sleep" "wait_5_seconds" {
  create_duration = "5s"
}
```
TF plan:
```
# time_sleep.wait_5_seconds will be created
+ resource "time_sleep" "wait_5_seconds" {
  + create_duration = "5s"
  + id              = (known after apply)
}
```
Interestingly, TF plans to add the new resource defined in same `test.tf` which confirms that TF sees the file, initially from symptom of TF planning to delete everything in that file, it gave me the impression that file is somehow invisible to TF.

2. Tried distributing resource definitions inside `test.tf` to other `.tf` files (eg. `dynamodb.tf`) in same dir, but terraform validate failed with `Duplicate resource configuration`
```
│ Error: Duplicate resource "aws_lb_target_group_attachment" configuration
│ 
│   on test.tf line 171:
│  171: resource "aws_lb_target_group_attachment" "test_tg_attachment_custom_ports" {
│ 
│ A aws_lb_target_group_attachment resource named "test_tg_attachment_custom_ports" was already declared at dynamodb.tf:166,1-76. Resource names must be unique per type in each module.
```
3. TF runs on self managed CI server (no TF Cloud) with remote state in S3. But could repro the issue locally as well.
4. Nope, no changes whatsoever. It was running as expected few days back and all of sudden drift was detected.
5. Yep no `.terraformignore` or `.gitignore` or CI server or locally.

**Comment by liamcervante** [comment] 2023-10-09 07:46
Thanks for the additional context. Given that the `time_sleep` doesn't exhibit the same behaviour as the `aws` resources, I wonder if there's something happening in the AWS provider to cause this. Or maybe, we could be seeing two separate bugs one marking the resources for destruction when it shouldn't and then Terraform adding in the wrong explanation as it doesn't understand why the resources are being destroyed.

I've still be unable to replicate this locally. I'll see if anyone in the AWS team here has seen anything similar.

In the meantime, I did notice that in your configuration you had `depends_on = [aws_ebs_volume.ease_fe_ebs_vol]` in your `test_instance` resource definition. Is that referencing something from another file? Has anything happened to the referenced resource?

**Comment by liamcervante** [comment] 2023-10-09 08:03
Sorry, one more follow up.

> Tried distributing resource definitions inside test.tf to other .tf files (eg. dynamodb.tf) in same dir, but terraform validate failed with Duplicate resource configuration

Did you also remove the definition from `test.tf` file? If not, could you try that? It would deal with the duplicate definition issue, and then we'd see if the behaviour of the actual resource is the same regardless of the file that we're in. I think Terraform is still detecting the file, but then marking the resources to be deleted for another reason and then potentially mislabelling that reason.

**Comment by jbardin** [comment] 2023-10-09 13:43
Hi @UdhavPawar,

I think the next step here would be to have a complete reproduction case, which can be run from scratch to others can verify the setup. This means including source and all commands exactly as executed. If you can't replicate this in a fresh environment (which may provide some clue itself as to what the difference might be), the full trace log from the plan would be the first place to continue investigation.

Thanks!

**Comment by UdhavPawar** [comment] 2023-10-11 23:29
@liamcervante 
1. No depends on is for resources in same .tf.
2. Yes did drop definitions from `test.tf` when we added them to other working `.tf` files.

@jbardin sounds like a plan. Only command I'm running is `terraform plan`. Apart from plan with `TF_LOG = DEBUG` and actual `test.tf` file, what other info do we need?

Thank You.

**Comment by jbardin** [comment] 2023-10-12 14:38
@UdhavPawar, for complete information we would want to log `TF_LOG_CORE=trace`. Given the very strange behavior described here something is different from the way everyone else runs Terraform, so any and every detail you can provide would be helpful. It's best to package it up as a completely self-contained and scripted example that can reproduce the issue from a clean environment.

**Comment by UdhavPawar** [comment] 2023-10-13 17:40
> @UdhavPawar, for complete information we would want to log `TF_LOG_CORE=trace`. Given the very strange behavior described here something is different from the way everyone else runs Terraform, so any and every detail you can provide would be helpful. It's best to package it up as a completely self-contained and scripted example that can reproduce the issue from a clean environment.

@jbardin Looking at the symptoms, my suspicion is something is messed up with state for resources in `test.tf`. Given state file has sensitive data, I'm not entirely sure how can we repro the issue because it's not really the configuration itself in .tf from my understanding.

Pls lmk if you have an approach in mind to repro this issue, more than happy to execute it.

**Comment by chriskathumbi** [comment] 2024-03-15 23:04
Hello, this might be due to a reference to an already existing tfstate key in your terraform backend. So terraform tries to read the resources from that backend instead of creating a new one. Because the resources aren't the current tf files, terraform assumes you want to destroy or replace them. 
If you copied the providers, make sure to change the key to the name of your current project.
You can also try to make a backend config file when you make a new tf project. This way you can define macros that add the name of the current project to the config file.
This is because variables aren't allowed when defining providers.

**Comment by kris-felscher** [comment] 2024-06-04 20:26
We just experienced this issue as well. Terraform deleted the entire resource group for our UAT Service Bus instance when the only change was the addition of two subscriptions to a topic.

We are unable to reproduce the issue.

**Comment by varadkarpe** [comment] 2024-08-30 08:26
@rishabhToshniwal 
I am facing the same issue and this has happened after I updated the provider version.

**Comment by jbardin** [comment] 2024-08-30 14:14
Since we have not received a reproduction case I'm going to close the issue. For those claiming to have similar situations, if you have an example to reproduce the problem, please file a new issue with all the necessary information. If this was in conjunction with a change to a provider, any planned replacements are most likely caused by the provider and not by the Terraform CLI, so investigation with that provider would be the first step to take.

**Closed by jbardin** 2024-08-30 14:14 UTC
Labels: bug, waiting for reproduction, v1.4
