### ISSUE TITLE
AWS EC2: user_data (with base64) changes whether it’s deploy from a Linux or a Windows workstation

### ISSUE THREAD

**Issue by gui-don** [hashicorp/terraform#25123] opened 2020-06-03 22:36 UTC
Our client does have linux and Windows machines. They do not have CI/CD. They deploy the code from their workstation with an statefile in an S3 bucket. Not the best practices, but it’s how they do it.

Weirdly, `user_data` for `aws_instance` resource is updated (forcing destroy/recreate) depending on the platform (at least that is my guess).

I know it looks specific to the AWS provider, though I believe the `base64encode` function may be the issue.

### Terraform Version
```
Terraform v0.12.26
+ provider.aws v2.57.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
// Module 1
data "template_file" "user_data" {
  template = "${file("${path.module}/templates/user_data.tmpl")}"
}
output "user_data" {
  value = "${base64encode(data.template_file.user_data.rendered)}"
}
```
```hcl
// Module 2
[…]
module "ec2" {
  […]
  user_data = module.module1.user_data
}
```

### Expected Behavior

The base64 should not depend on the underlaying OS. When preforming `terraform apply`, it should not have no changes if the code didn’t change.

### Actual Behavior

Terraform detects a change for `user_data`.
I performed a base64 decode myself (linux) and the difference shows **nothing**, even though the base64 `user_data` from a Windows station is indeed different from the linux one. I believe it may be related to end of lines…

### Steps to Reproduce
1. Apply a configuration containing a base64 encoded user data on Windows.
2. Apply it again on Windows machine: no changes.
3. Apply the same configuration on linux: base64 `user_data` changed. 

### Additional Context

- I did not perform the test backward (Linux to Windows) because I don’t have access to a Windows machine and I don’t have easy access to a lab environment where I can destroy things freely.
- On linux `filebase64` gives the same result as the `base64encode` showed in the example above.

**Comment by apparentlymart** [comment] 2020-06-04 00:07
Hi @gui-don,

Indeed, I strongly suspect that this is being caused by your Windows users creating files using the conventional Windows line ending sequence `\r\n` while your Linux users are creating files using the conventional Unix line ending sequence `\n`.

`user_data` is defined as being an arbitrary sequence of bytes, so Terraform can't make any assumptions about it being in a particular syntax, such as automatically removing `\n` sequences.

In order to get the desired behavior, you'll need to either ensure that everyone is creating the files in a consistent way or add logic to the Terraform configuration to normalize the input. Normally in this situation I suggest folks look into [Git's `autocrlf` option](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf) as a way to normalize, but in your case where files are being uploaded directly to S3 from the local workstation I fear that anything Git could do here would happen too late to be effective.

Depending on what text editor your Windows users are using, there could be a way to configure it to generate Unix-style line endings even on Windows. Aside from older versions of Windows Notepad I think this has been a pretty typical feature for most text editors. In particular, I know from experience that Visual Studio Code has this option selectable via a UI gadget at the bottom right, which will read either "LF" or "CRLF" depending on what mode is currently selected. Setting it to "LF" will make Visual Studio Code produce Unix-style line endings.

If there is really no way to ensure that these files will always be written consistently, a last resort would be to use [Terraform's `replace` function](https://www.terraform.io/docs/configuration/functions/replace.html) to strip out any `\r` (carriage return) control characters from the file contents before processing them as a template:

```hcl
data "template_file" "user_data" {
    template = replace(file("${path.module}/templates/user_data.tmpl"), "\r\n", "\n")
}
```

As I noted above, there's nothing Terraform or the AWS provider can really do automatically here because it cannot safely assume that `user_data` is line-oriented text, even though it _often_ is. For that reason, I'm going to close this issue. Hopefully the above has given you some ideas for how to address the problem. If you have any further questions on this, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core)!

**Closed by apparentlymart** 2020-06-04 00:07 UTC

**Comment by gui-don** [comment] 2020-06-04 05:18
Hi @apparentlymart, Thanks for your very complete answer, I appreciate it.

I’ll look into the solutions you suggested.
