### ISSUE TITLE
terraform plan: reports blocks as added/removed when in reality they didn't change

### ISSUE THREAD

**Issue by ecerulm** [hashicorp/terraform#26084] opened 2020-09-01 20:04 UTC
### Terraform Version

```
Terraform v0.13.1
+ provider registry.terraform.io/-/aws v3.4.0
+ provider registry.terraform.io/-/helm v1.2.4
+ provider registry.terraform.io/-/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/aws v3.4.0
+ provider registry.terraform.io/hashicorp/helm v1.2.4
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0

```

### Terraform Configuration Files

```terraform
resource "helm_release" "prometheus" {
  name       = "prometheus"
  namespace  = kubernetes_namespace.prometheus.metadata[0].name
  wait       = true
  repository = "https://kubernetes-charts.storage.googleapis.com/"
  chart      = "prometheus"
  version    = var.prometheus_chart_version

  dynamic "set" {
    for_each = var.volumes
    content {
      name  = "${set.key}.persistentVolume.enabled"
      value = "true"
    }
  }

  dynamic "set" {
    for_each = var.volumes
    content {
      name  = "${set.key}.persistentVolume.existingClaim"
      value = kubernetes_persistent_volume_claim.volumeclaims[set.key].metadata[0].name
    }
  }

  set {
    name  = "server.ingress.enabled"
    value = "true"
  }

  set {
    name  = "server.ingress.hosts"
    value = "{prometheus.example.net/*}"
  }

  dynamic "set" {
    for_each = local.ingress_annotations

    content {
      name  = "server.ingress.annotations.${replace(set.key, ".", "\\.")}"
      value = set.value
      type  = "string"
    }
  }

  dynamic "set" {
    for_each = ["server", "alertmanager", "pushgateway"]
    content {
      name  = "${set.value}.service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
      value = "prometheus-${set.value}.example.net."
    }
  }
}


```

### Expected Behavior

`terraform plan` should show only the `set {...}` blocks that actually changed. 

### Actual Behavior

`terraform plan` reported that many (all?) the `set {...}`  blocks have changed: 

```
      - set {
          - name  = "server.persistentVolume.enabled" -> null
          - value = "true" -> null
        }
      + set {
          + name  = "server.persistentVolume.enabled"
          + value = "true"
        }
```
The above change seems to indicate the a `set { ... }` has been deleted and a **new unrelated but identical** set block has been created. This forces me to review all this block changes that are not really changes.

**Comment by andrei-dascalu** [comment] 2020-09-02 07:25
Not sure if related or not, but the same thing happens with Azure role definitions (azurerm_role_assignment), they are always recreated on subsequent applies even if nothing changes.

**Comment by ecerulm** [comment] 2020-09-02 10:52
I don't think it's the same thing. I'm my case it will not recreate if nothing changes. But when there is a change the plan report is a bit misleading showing lots of changes when in facts there is only one change.

**Comment by livingstonjames45** [comment] 2020-09-02 14:28
Similar to what @andrei-dascalu  mentioned, in AWS if you mix inline security group rules and rules declared outside of the security group, AWS recreates them at random. But like you mentioned, you scenario sounds a little different.

Is it possible Terraform reacts similarly in your case, though? Can your dynamic volumes and other resources be declared and created outside of helm_release, or do they have to be declared inside?

**Comment by ecerulm** [comment] 2020-09-02 14:36
You can only use **inline** `set` blocks AFAIK.

I believe that the culprit is that each `set` block "identity" is the position in which it appears. So terraform compares current state with desired state it does by comparing `set.1` with `set.1`, `set.2` with `set.2`, so if you add a new `set` between 1 and 2 then all comparison after that will be off. 

I wish that the reporting could "resync" and notice that  previous state's `set.2` is  now `set.3` in the new desired state. Or that block identity was based on `set.*.name`.

**Comment by mildwonkey** [comment] 2020-09-09 16:42
Hi, @ecerulm , you have it right:
>each set block "identity" is the position in which it appears.

If you add a `set` block anywhere other than the end of that configuration, terraform will show all sets changing (from the index of the `set` block you added on down). The order of blocks inside a resource matters. 

I'm going to close this, since this is expected behavior. Thank you for updating this with what you'd figured out!

**Closed by mildwonkey** 2020-09-09 16:42 UTC
Labels: bug, new
