### ISSUE TITLE
Escaping with $${} not working

### ISSUE THREAD

**Issue by joao-teixeira-cvt** [hashicorp/terraform#28516] opened 2021-04-26 09:19 UTC
### Terraform Version

```
Terraform v0.15.0
```

### Terraform Configuration Files

```terraform
Terragrunt + Terraform modules used here. The provider is aws 3.37.0
```

### Actual Behavior

```terraform
Error: Extra characters after interpolation expression
│
│   on <value for var.inline_policies> line 1:
│   (source code not available)
│
│ Expected a closing brace to end the interpolation expression, but found
│ extra characters.

ERRO[0003] Hit multiple errors:
Hit multiple errors:
exit status 1
```

### Additional Context

```
inline_policies = {
    "policy_name" = { policy = templatefile("${get_terragrunt_dir()}/policy.json", {
      })
    }
 }
```

On the policy, I need to use aws policy variables that has the same sintaxe has terraform for interpolation. I need to declare this on the policy:
```
"StringLike": {
 "ssm:resourceTag/aws:ssmmessages:session-id": "${aws:userid}"
}
```

For that I'm using the escape character:
```
"StringLike": {
 "ssm:resourceTag/aws:ssmmessages:session-id": "$${aws:userid}"
}
```

Unfortunately it's not working giving the error I showed above

If I removed that condition with "StringLike" the resource is created without any errors.
I have tried to use unicode for the second $ but without success

**Comment by alisdair** [comment] 2021-04-26 15:00
Hi @joao-teixeira-cvt, thanks for reporting this. I'm not able to reproduce the problem with a reduced configuration, omitting the Terragrunt specific code. I think this may therefore be an issue in Terragrunt.

Here's what I tried to do to reproduce the problem. Create `main.tf` and `policy.json` files:

```hcl
output "policies" {
  value = {
    policy = templatefile("policy.json", {})
  }
}
```

```json
{
  "StringLike": {
    "ssm:resourceTag/aws:ssmmessages:session-id": "${aws:userid}"
  }
}
```

Run `terraform plan`:

```shellsession
$ terraform plan
╷
│ Error: Error in function call
│
│   on main.tf line 3, in output "policies":
│    3:     policy = templatefile("policy.json", {})
│
│ Call to function "templatefile" failed: policy.json:3,57-58: Extra characters after interpolation
│ expression; Expected a closing brace to end the interpolation expression, but found extra characters..
╵
```

Fix the `policy.json` file to use `$` as a quote character:

```json
{
  "StringLike": {
    "ssm:resourceTag/aws:ssmmessages:session-id": "$${aws:userid}"
  }
}
```

Re-run `terraform plan`:

```shellsession
$ terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + policies = {
      + policy = jsonencode(
            {
              + StringLike = {
                  + ssm:resourceTag/aws:ssmmessages:session-id = "${aws:userid}"
                }
            }
        )
    }
```

As you can see, this works successfully. As a result, I don't think there's a bug in Terraform here, so I'm closing this issue. If you can find a way to update this example to demonstrate the problem without Terragrunt, please let me know how to reproduce and I'll reopen.

**Closed by alisdair** 2021-04-26 15:00 UTC
Labels: bug, v0.15, waiting for reproduction, waiting-response

**Comment by joao-teixeira-cvt** [comment] 2021-04-26 15:04
Hi @alisdair,

Thanks for addressing this. Yes, in fact I tried the same with only terraform and no problem at all. I thought it was related with Terraform, since Terragrunt calls are in fact Terraform calls. I will open the issue on Terragrunt source code repo.
Thanks again!

**Comment by joao-teixeira-cvt** [comment] 2021-04-27 11:09
@alisdair Ok, now I got the point. The problem is using a map with objects as values to define the policy.

Terragrunt code to invoke terraform:
´´´
inline_policies = {
    "test" = {
      policy = templatefile("${get_terragrunt_dir()}/policy.json", {
        region           = local.region
        account_id       = local.account_id
        project_name_u   = local.project_name_u
        application_team = local.application_team
      })
    }
  }
´´´

Terraform role module:
´´´
resource "aws_iam_role_policy" "inlinepolicy" {
  for_each = var.inline_policies

  name = each.key
  role = aws_iam_role.role.id

  policy = each.value["policy"]
}
´´´

Terraform role module variables.tf:
´´´
variable "inline_policies" {
  type = map(object({
    policy = string
  }))
  default = null
}
´´´

If I simple assign to policy argument on aws_iam_role_policy a variable of type string it will work with the json file with an interpolation $${aws:userid}, but with an map(object) it won't. I also tested with set and without success. I have also remove the policy part which has the interpolation $${aws:userid} and the inline policy gets created successfully.

Any ideas how to solve this?
This gaves me a lot of flexibility, because I can specify more than one inline policy rather than having to specify or create a resource aws_iam_role_policy for each inline policy I want to set.

**Comment by alisdair** [comment] 2021-04-27 13:22
I'm sorry, but I can't quite understand what you're asking here. It doesn't sound like a Terraform bug, and more of a usage question. In that case, please [post a thread in the the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help.

When doing so, I'd advise making a self-contained configuration which demonstrates the problem, not using Terragrunt, to make it as easy as possible to understand.

**Comment by joao-teixeira-cvt** [comment] 2021-04-27 14:43
@alisdair solved! Instead of using templatefile() functions on Terragrunt inputs block, I moved the function to Terraform module inside the desired resource, and I'm passing the path and vars using a map(object{}) var type.

resource declaration:
```
resource "aws_iam_role_policy" "inlinepolicy" {
  for_each = var.inline_policies

  #name = each.key
  #role = aws_iam_role.role.id
  #policy = each.value.policy
  role   = aws_iam_role.role.id
  name   = each.key
  policy = templatefile(each.value.policy, each.value.vars)
}
```

variable declaration:
```
variable "inline_policies" {
  type = map(object({
    policy = string
    vars = map(string)
  }))
}
```
variable input:
`inline_policies = {
    "Test" = {
      policy = "${get_terragrunt_dir()}/policy.json"
      vars = {
        account_id       = local.account_id
      }
    }
  }`


You're absolutely right, it was a usage thing. Although, if I do not include the ${aws:userid} AWS interpolation on JSON policy the old way worked like a charm. Probably it's how Terragrunt is passing templatefile function to Terraform, since this last does not allow to specify templatefile function at variable level
