### ISSUE TITLE
terraform get doesn't work with git and ssh

### ISSUE THREAD

**Issue by obvionaoe** [hashicorp/terraform#30678] opened 2022-03-15 15:43 UTC
### Terraform Version

```
Terraform v1.1.4
on linux_amd64
```

### Terraform Configuration Files
```terraform
module "module" {
  source = "git::ssh://git@domain.com:namespace/terraform/modules/x/y?ref=1.0.0"
}
```

### Expected Behavior
`terraform get` should be able to download the repository using git with ssh

### Actual Behavior
`Error: Invalid module source address`

### Steps to Reproduce
1. `terraform get`

### Additional Context
If you remove `ssh://` from the string, it works:

```terraform
module "module" {
  source = "git::git@domain.com:namespace/terraform/modules/x/y?ref=1.0.0"
}
```

**Comment by apparentlymart** [comment] 2022-03-15 15:57
Hi @obvionaoe!

What you've shared seems like an invalid Git URL. [Git SSH URLs can have one of two forms](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_ssh_protocol), mutually exclusive:

* Standard URL syntax: `ssh://git@domain.com/namespace/terraform/modules/x/y` (notice that the path starts with a slash in this case, just as with other URL schemes like `https:`. A colon, if present, represents a port number.)
* "scp-like syntax": `git@domain.com:namespace/terraform/modules/x/y` (in this case, the colon separates the hostname from the path)

Terraform will accept both forms, but you need to be consistent and choose one or the other, because the colon has a different meaning in each case. The following two source strings should work:

```hcl
  source = "git::ssh://git@domain.com/namespace/terraform/modules/x/y?ref=1.0.0"
```
OR
```hcl
  source = "git::git@domain.com:namespace/terraform/modules/x/y?ref=1.0.0"
```

If you are trying to specify a directory inside a repository rather than a whole repository, you will also need to use the [Modules in Package Sub-directories](https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories) syntax to mark the boundary between the repository URL (the "package" in Terraform's terms) and the path within the repository (the "subdirectory").

What you observed here is Terraform behaving as intended, because it understood your "namespace" part as a port number and so failed parsing. Therefore I'm going to close this, but if you have any further questions about Git/SSH-based module sources, please start a topic about it in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Closed by apparentlymart** 2022-03-15 15:57 UTC
Labels: bug, new

**Comment by obvionaoe** [comment] 2022-03-15 17:31
my bad, I missed that, thanks
