### ISSUE TITLE
aws provider info isn't available to grandchild module in 0.6.9

### ISSUE THREAD

**Issue by WillAbides** [hashicorp/terraform#4607] opened 2016-01-10 18:33 UTC
I have a module (network_module) that uses another module (key_pair_module) that creates an aws resource.  As of 0.6.8, I could use network_module from a config that has an aws provider defined and the auth and region from that provider was used when key_pair_module created an aws_key_pair.  Now, with 0.6.9, that no longer works.

Here are some simplified configs that show the problem:

./key_pair_module/main.tf
```hcl
variable "public_key" {}
variable "key_name" {}

resource "aws_key_pair" "key" {
  public_key = "${var.public_key}"
  key_name = "${var.key_name}"
}
```

./network_module/main.tf
```hcl
variable "aws_public_key_path" {}
variable "key_name" {}

module "key_pair" {
  source = "../key_pair_module"
  public_key = "${file(var.aws_public_key_path)}"
  key_name = "${var.key_name}"
}
```

./example_config/main.tf
```hcl
variable "aws_region" {
  default = "us-east-1"
}
variable "aws_access_key" {}
variable "aws_secret_key" {}

provider "aws" {
  region = "${var.aws_region}"
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
}

module "network_module" {
  source = "../network_module"
  aws_public_key_path = "./id_rsa.pub"
  key_name = "test-key-please-ignore"
}
```

./example_config/terraform.tfvars
```
aws_access_key = "SSSHHHHH"
aws_secret_key = "ITSASECRET"
```

This is the output when I run terraform apply with 0.6.9:
```console
 ~/hack/terraform-grandchild-repro/example_config  $  terraform apply
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value:

Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* Error loading credentials for AWS Provider: NoCredentialProviders: no valid providers in chain
```

It shouldn't have prompted for provider.aws.region since that was already defined in the aws provider.

**Comment by WillAbides** [comment] 2016-01-10 18:52
I may have been wrong about this working as I expected in 0.6.8.  I switched back to 0.6.8 and got similar behavior.

**Comment by WillAbides** [comment] 2016-01-10 19:42
I found a workaround.  If I add an aws.key_pair resource to network_module, then the key_pair created in key_pair_module works also.  This even works if I have count=0 on the fake key_pair so that nothing gets created.

I think the graphs of before and after doing that are instructive.

With the fake key_pair resource:
![graph2 0 6 9](https://cloud.githubusercontent.com/assets/233500/12223522/ba9e4afa-b79f-11e5-9be5-60984e2c0c61.png)
Without the fake key_pair resource:
![graph4 0 6 9](https://cloud.githubusercontent.com/assets/233500/12223529/d45787a4-b79f-11e5-9874-1d4220303427.png)
With the fake resource and count=0:
![graph5 0 6 9](https://cloud.githubusercontent.com/assets/233500/12223541/fda07e9a-b79f-11e5-8e3c-fa160a56314b.png)

**Comment by WillAbides** [comment] 2016-01-10 19:43
reopened after accidentally hitting "Close and comment"

**Comment by wholroyd** [comment] 2016-01-12 01:24
Also related to issues #4443, #2832, and #3931.

**Comment by WillAbides** [comment] 2016-01-12 14:34
@wholroyd Thanks. This may be a dupe of #4443, but I'm going to leave it open and let a contributor decide for sure.

**Comment by catsby** [comment] 2016-01-13 20:03
Hey friends – thanks for opening this. We've chatted internally and agree it's a dupe of #4443, so we're going to close. Once again though, thank you for opening the issue :smile: 

#4443 is on our short list, thanks!

**Closed by catsby** 2016-01-13 20:03 UTC
Labels: bug, provider/aws
