### ISSUE TITLE
crash during the removal of NS entry from hosted zone

### ISSUE THREAD

**Issue by kalbasit** [hashicorp/terraform#9025] opened 2016-09-23 21:02 UTC
Hello,

I have a route53 for a subdomain and I am trying to remove the NS entry from this hosted zone

### Terraform Version

```
% terraform --version
Terraform v0.7.4
```

### Affected Resource(s)
- aws_route53_zone
- aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_route53_zone" "getpublica-com-prod" {
  name = "getpublica.com"

  tags {
    env = "prod"
  }
}

resource "aws_route53_record" "getpublica-com-prod-ns-for-staging" {
  zone_id = "${aws_route53_zone.getpublica-com-prod.zone_id}"
  name    = "staging.getpublica.com"
  type    = "NS"
  ttl     = "172800"

  records = [
    "${aws_route53_zone.getpublica-com-staging.name_servers.0}",
    "${aws_route53_zone.getpublica-com-staging.name_servers.1}",
    "${aws_route53_zone.getpublica-com-staging.name_servers.2}",
    "${aws_route53_zone.getpublica-com-staging.name_servers.3}",
  ]
}

resource "aws_route53_zone" "getpublica-com-staging" {
  name   = "staging.getpublica.com"
  vpc_id = "${module.vpc_us-east-1.vpc_id}"

  tags {
    env = "staging"
  }
}

resource "aws_route53_record" "getpublica-com-staging-ns" {
  zone_id = "${aws_route53_zone.getpublica-com-staging.zone_id}"
  name    = "staging.getpublica.com"
  type    = "NS"
  ttl     = "172800"

  records = [
    "${aws_route53_zone.getpublica-com-staging.name_servers.0}",
    "${aws_route53_zone.getpublica-com-staging.name_servers.1}",
    "${aws_route53_zone.getpublica-com-staging.name_servers.2}",
    "${aws_route53_zone.getpublica-com-staging.name_servers.3}",
  ]
}
```

This bug happens when removing `aws_route53_record.getpublica-com-staging-ns`

### Debug Output

https://gist.github.com/kalbasit/bc7c08f18a39a991d0e8ef5868118482

### Panic Output

https://gist.github.com/kalbasit/02e2d2a5d8571a740c2d98f40b3a9513

### Expected Behavior
The NS entries are removed from the hosted zone

### Actual Behavior
Terraform crashed

### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment] 2016-09-26 10:44
Hi @kalbasit

Apologies this has caused some issues for you - I have found the cause and am currently opening a PR for this

This fix will be released as of Terraform 0.7.5

Thanks

Paul

**Closed** 2016-09-28 10:02 UTC
Labels: bug, crash, provider/aws
