### ISSUE TITLE
v0.12: Phantom nil element appear in some configs during AzureRm tests

### ISSUE THREAD

**Issue by katbyte** [hashicorp/terraform#20585] opened 2019-03-06 08:53 UTC
Hello,

We are experiencing some weird panics in the azurerm provider after updating to the latest .12 SDK (master): `github.com/hashicorp/terraform v0.12.0-alpha4.0.20190306001855-b9d8e96e0c7c`

It appears a in a few different places we are getting nil elements inside slices that should by all accounts be empty (as well as some other less clear failures that might be related). The branch and some information can be seen at https://github.com/terraform-providers/terraform-provider-azurerm/pull/2968 but the two obvious instances are:

aks:
```
=== CONT  TestAccAzureRMKubernetesCluster_addAgent
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 622 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm.expandKubernetesClusterAddonProfiles(0xc000a4f5e0, 0xc00181c300)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_kubernetes_cluster.go:752 +0x93f
```
[code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/012/early4/azurerm/resource_arm_kubernetes_cluster.go#L752)
```
profiles := d.Get("addon_profile").([]interface{})
	if len(profiles) == 0 {
		return nil
	}

	profile := profiles[0].(map[string]interface{})
```
and `addon_profile` is not set in [the config](https://github.com/terraform-providers/terraform-provider-azurerm/blob/012/early4/azurerm/resource_arm_kubernetes_cluster_test.go#L600-L621)

the second instance is in a bunch of VM tests:
```
=== CONT  TestAccAzureRMVirtualMachineScaleSet_linuxUpdated
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 847 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm.expandAzureRmVirtualMachineScaleSetNetworkProfile(0xc0018744d0, 0x0)
	/Users/kt/hashi/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine_scale_set.go:1630 +0x1f94
```
[code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/012/early4/azurerm/resource_arm_virtual_machine_scale_set.go#L1630)
```
dnsSettingsConfigs := config["dns_settings"].([]interface{})
		dnsSettings := compute.VirtualMachineScaleSetNetworkConfigurationDNSSettings{}
		for _, dnsSettingsConfig := range dnsSettingsConfigs {
			dns_settings := dnsSettingsConfig.(map[string]interface{})
```

and `dns_settings` is also not set in [the config](https://github.com/terraform-providers/terraform-provider-azurerm/blob/012/early4/azurerm/resource_arm_virtual_machine_scale_set_test.go#L2425)

**Comment by jbardin** [comment] 2019-03-07 00:33
Hi @katbyte,

I'm going to start with just the first example here. You will probably find slightly different behavior with master now, since there was a change just merged that's going to alter the handling of "computed blocks". I'm not sure if it's going to be better or worse, since there isn't any defined behavior for this schema. We're tolerating schemas containing "computed" blocks for now with some limitations, but there's no real way to handle one which also contains required fields.

 I think removing the `Computed: true` field from the `addon_profile` schema will improve the situation. 

I'll follow up with more info on the other cases too.

**Comment by jbardin** [comment] 2019-03-07 23:39
I wasn't able to get the Azure ACC tests running locally, but I managed to create a reproduction of the first issue. The most recent master seems to alleviate the issue, and I haven't been able to replicate any `nil` values in that structure with the new object normalization in place.

**Comment by jbardin** [comment] 2019-03-09 15:05
OK, no need to check master at the moment. The change that removed the panics causes issues with other unusual provider schemas, so I'll find another way to resolve those.

**Comment by katbyte** [comment] 2019-03-11 17:34
Thanks for the updates @jbardin

**Comment by jbardin** [comment] 2019-03-13 22:01
The `TestAccAzureRMVirtualMachineScaleSet_linuxUpdated` now passes locally for me.
I'm not sure about the k8s test (not idea how long that's supposed to take), but I think the cases causing the panics have been cleared up.

**Comment by jbardin** [comment] 2019-03-15 22:26
Ok, had time to verify both tests are passing now with master.

**Closed by jbardin** 2019-03-15 22:26 UTC
Labels: bug, crash, provider-sdk
