### ISSUE TITLE
[lifecycle]: new option "accept_changes"

### ISSUE THREAD

**Issue by ask0n** [hashicorp/terraform#15477] opened 2017-07-05 18:10 UTC
It would be cool to have a new option for lifecycle which would be very same to ignore_changes, but with other logic.
Every plan terraform updates actual state to check actual state of resources. If resource was changed terraform will apply configuration to it, but what to do if we expect resource to be changed and we want to use actual resource state with our configuration?
For example desired_capacity for aws_autoscaling_group could be changed externally by running cluster. If this happens terraform have two options: restore configured value or use lifecycle ignore_changes for desired_capacity. In both cases terraform will know actual value, which we need without willing to change it right now.
Actual variables could be called like var.some_var.actual, by default they are empty or undefined.

**Comment by apparentlymart** [comment] 2017-07-05 20:03
Hi @ask0n,

I saw the discussion about this in the Gitter IM and responded there, but I'll repeat my response here for posterity:

What you describe is actually the intended behavior of `ignore_changes`. If, for example, `ignore_changes` were set to include `desired_capacity` as you discuss here, the following behavior should happen if it is changed outside of Terraform before `terraform plan` is run:

* The "refresh" step will see the updated `desired_capacity` value and write it into the state.
* The diff step will see that the `desired_capacity` attribute in configuration doesn't match what's in state, but will ignore that because `ignore_changes` is set for that attribute.
* Any interpolation of an expression like `${aws_autoscaling_group.foo.desired_capacity}` will _still_ see the update, because it reads from the state rather than from the config. Unless the attributes containing an expression are _also_ marked as `ignore_changes`, a diff should be created as expected.

With that said, it sounds like there may be a bug here if the above isn't working for you. It would be very helpful if you were able to give the above a try (or indeed, confirm that you _already_ tried it) as that would help understand whether this is indeed a bug to be fixed or a new feature to add.

**Comment by ask0n** [comment] 2017-07-06 13:59
Hi @apparentlymart,
Thank you for your clarification.
`${aws_autoscaling_group.foo.desired_capacity}` really gets updated values. Looks like I didn't use `ignore_changes` last time I checked it.
Maybe I missed something and  aws_autoscaling_group resource also could provide actual IP list of running instances?

**Comment by apparentlymart** [comment] 2017-07-06 15:42
That starts to get into AWS-specific issues rather than core but I think in general this resource is shying away from exposing the dynamic state of an autoscaling group because it intentionally changes asynchronously from a Terraform run and so Terraform would only ever see the snapshot of what exists at the time it runs.

I expect there's no _technical_ reason why this information couldn't be exposed, but more that it seems unlikely to be generally useful. However, if you _do_ have a use-case for it I'd encourage opening a feature request issue in [the `aws` provider repo](https://github.com/terraform-providers/terraform-provider-aws) that describes what you're trying to achieve with that.

Since it seems like Terraform is already behaving in the way this feature request is described, I'm going to close this one. We can discuss this separate question further in the AWS provider repository if you like. :grinning:

**Closed by apparentlymart** 2017-07-06 15:42 UTC
Labels: core, enhancement
