### ISSUE TITLE
String/bool type conversions do not match documentation

### ISSUE THREAD

**Issue by atombravo** [hashicorp/terraform#31704] opened 2022-08-29 17:18 UTC
### Terraform Version

```shell
Terraform v0.13.7
```

### Terraform Configuration Files

```
# Example.tf
variable "typeless_variable" {
}

output "typeless_variable" {
    value = (var.typeless_variable == true) ? "TRUTH" : "FICTION"    
}


variable "string_variable" {
    type = string
}

output "string" {
    value = (var.string_variable == true) ? "TRUTH" : "FICTION"    
}

```

```
# config.tfvars

# Pass a string into an typeless variable
typeless_variable = "true"

# Pass a boolean into a string variable
string_variable = true

```

### Debug Output

https://gist.github.com/atombravo/e1e699729471da8061fe819371685ffd

### Expected Behavior

Based on https://www.terraform.io/language/v1.1.x/expressions/types#type-conversion:

> [true](https://www.terraform.io/language/v1.1.x/expressions/types#true) converts to "true", and vice-versa
[false](https://www.terraform.io/language/v1.1.x/expressions/types#false) converts to "false", and vice-versa

Expected output would be:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

string = TRUTH
typeless_variable = TRUTH
```

In other words, I expect that:
* having passed a string "true" to a variable without a type, when tested, that variable would convert and equal `true` (bool) 
* having passed `true` to a string variable, when tested, that string would convert and equal `true` (bool)

### Actual Behavior

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

string = FICTION
typeless_variable = FICTION
```

string_variable ( `true`) != `true`
typeless_variable ("true") != `true`

### Steps to Reproduce

1. terraform init
2. terraform apply -var-file=".\config.tfvars"

### Additional Context

We were caught by this when we had logic testing whether a variable input to a module was `true` (in a "count" with a ternary), but the variable was untyped.  The calling code passed in the string "true" instead of a boolean value.  Skimming the configuration files, we expected an untyped variable with the string value "true" to evaluate as `true`, but discovered it doesn't.

**Comment by apparentlymart** [comment] 2022-08-29 18:11
Hi @atombravo! Thanks for raising this.

I think the trick here is that `var.string_variable == true` is a _comparison_, rather than a type conversion. A string value can never be equal to a boolean value.

If you first convert the string value to a boolean value then I expect it will work as documented:

```hcl
output "string" {
    value = (tobool(var.string_variable) == true) ? "TRUTH" : "FICTION"    
}
```

Or alternatively (and more idiomatically) you can just use the string directly as the condition, in which case Terraform knows that the first operand to `?` must always be boolean and so will perform the type conversion automatically:

```hcl
output "string" {
    value = var.string_variable ? "TRUTH" : "FICTION"    
}
```

The same automatic conversion applies to all of the other boolean-only operators, such as `!var.string_variable` (will convert to bool and then NOT it) and `var.string_variable && var.other` (will convert both to bool and then AND them).

Unfortunately because you used the `==` operator here, which works for values of any type, Terraform was not able to infer the type conversion automatically and therefore just compared the two values directly as given, which returned `false` because the two values were not of the same type.

**Comment by atombravo** [comment] 2022-08-29 20:33
> Unfortunately because you used the `==` operator here, which works for values of any type, Terraform was not able to infer the type conversion automatically and therefore just compared the two values directly as given, which returned `false` because the two values were not of the same type.

 @apparentlymart that makes sense, and when digging into the comparison operator (https://www.terraform.io/language/v1.1.x/expressions/operators#equality-operators) I see there is a explanation/warning there about using == with differing types.  

I've made a PR to update the documentation in the Type Conversion section to include a link and callout to the behavior of the equality operator.  To my mind, it's a fairly notable exception to the overall "Terraform will try to automatically convert" rule.

Thanks!

**Comment by apparentlymart** [comment] 2022-08-29 20:49
This confusion also happens to be the first hazard on my list of ideas over in #29661. I'm not working on that any more right now because my attention is elsewhere, but hopefully we can pick up something like that again someday.

**Comment by jbardin** [comment] 2022-08-29 21:15
One thing to note @atombravo, is that comparison to `true` or `false` varies from unnecessary to incorrect in most languages. In a statically typed language the comparison is always redundant, and dynamically typed situations can lead to ambiguity or surprising behaviors as demonstrated here. In general when faced with a boolean value in a conditional expression, avoid comparing it to a boolean literal.

**Comment by crw** [comment] 2022-08-30 22:28
Thanks for the report, @atombravo! Closing as this is working as intended. Thanks for the PR as well!

**Closed by crw** 2022-08-30 22:28 UTC
Labels: bug, working as designed
