### ISSUE TITLE
Terraform 0.13.1 crashing without much detail

### ISSUE THREAD

**Issue by AtwoodTM** [hashicorp/terraform#26070] opened 2020-09-01 03:16 UTC
Environment: WSL 2.0 with Ubuntu 20.04 on Windows 10 2004
Terraform version 0.13.1
Azurerm provider version 2.25.0

Output:
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by AtwoodTM** [comment] 2020-09-01 03:26
If I could paste the crash.log, I would.  File is 106 MB while github allows for only 10 MB uploads.

**Comment by jbardin** [comment] 2020-09-01 16:06
Hi @AtwoodTM, without a way to reproduce the issue or the stack trace there isn't much we can do here. Seeing how this is using AzreRM, chances are it's a duplicate of #26011. If this isn't the case please file a new issue with the requested information in the issue template.

**Closed by jbardin** 2020-09-01 16:06 UTC
Labels: bug, new
