### ISSUE TITLE
Decode policy json when running show plan

### ISSUE THREAD

**Issue by awallace-r7** [hashicorp/terraform#20776] opened 2019-03-21 16:24 UTC
Some element in the output of terraform show plan -json are not properly decoded, eg policies applied to s3 buckets.

### Current Terraform Version

```
Terraform version: 0.12.0 beta1 

terraform-provider-aws built from:
git rev-parse --short HEAD
a78d31615
```

### Use-cases

Would like to get all the terraform plan output in json format. This is so that we can run Open Policy Agent rules on the output. 

### Attempted Solutions

We have used tfjson to do similar with terraform v0.11. The same problem exists, but we just run a second unmarshal on the encoded string to get correct json.

To solve this from our side, then we would look at marshalling and unmarshalling the output from show plan, but catch the policy element and then run another unmarshal on the contents of the policy element.

Eg, current functionality returns a policy element as per:

```
"policy": "{\n \"Version\": \"2012-10-17\",\n \"Statement\": [\n {\n \"Sid\": \"MySID\",\n \"Effect\": \"Deny\",\n \"Action\": \"s3:*\",\n \"Resource\": [\n \"arn:aws:s3:::mybucket/*\",\n \"arn:aws:s3:::mybucket\"\n ],\n \"Principal\": {\n \"AWS\": \"*\"\n },\n \"Condition\": {\n \"NotIpAddress\": {\n \"aws:SourceIp\": [\n \"1.1.1.1/32\",\n \"2.2.2.2/32\",\n \"3.3.3.3/32\",\n \"4.4.4.4/32\"\n ]\n },\n \"StringNotEquals\": {\n \"aws:SourceVpce\": [],\n \"aws:userid\": [\n \"ABCDEFGHIJKLMNOPQRSTU\",\n \"BCDEFGHIJKLMNOPQRSTUV\",\n \"CDEFGHIJKLMNOPQRSTUVW\",\n \"DEFGHIJKLMNOPQRSTUVWX\"\n ]\n }\n }\n }\n ]\n}"
```

### Proposal

We propose that you pick out json elements that are strings as per above and fully unmarshall them so that they are printed as correct json, without all the extra backslashes and carriage returns.

**Comment by apparentlymart** [comment] 2019-03-22 00:20
Hi @awallace-r7! Thanks for reporting this.

We have already implemented a heuristic to render strings that appear to be JSON in a structural way. Over in #19275 I'd found a similar problem to what you've seen here where that didn't work for some reason, but @radeksimko merged a fix for that so I'm going to assume there's some further tweaking to do here to get this to work more reliably.

Because we're in the prerelease phase of v0.12.0 now we might not be able to get back to this before the initial release, but if not then we'll plan to fix it in a subsequent point release.

**Comment by apparentlymart** [comment] 2019-03-22 00:22
@awallace-r7, if you could share the configuration of the resource that has that `policy` attribute inside of it that'd be a big help to ensure that we can reproduce your input as close as possible when testing/debugging. Thanks!

**Comment by apparentlymart** [comment] 2019-03-27 00:44
Hi again, @awallace-r7!

I didn't notice on the first read that you were asking for a change to the behavior of the `terraform show -json` behavior, rather than the `terraform plan` output.

The intent of the JSON output is to be a faithful, machine-interpretable representation of the resource type schema, which considers these attributes to be strings and thus they are presented as such. We don't intend to change that behavior, because to do so would impose a lossy transform on all users of the JSON output and thus no longer be an accurate description of what Terraform intends to do. It would also make life much more difficult for anyone trying to decode this JSON in a statically-typed language into compound types derived from the schema.

It is the responsibility of the calling program (in your case, your policy helper) to make any further transforms are needed for their use-cases. You may wish to adopt a similar heuristic to that used by the `terraform plan` human-oriented plan renderer, which attempts to parse the string as JSON but interprets is such only if the parse is successful and the result is either an object or an array. Without that additional constraint, you'll see false positives for the cases where strings contain keywords that are valid in both Terraform and JSON, such as `"null"`, `"true"`, and `"false"`. (You may prefer to unwrap those into real null or boolean values for your use-case, if you're sure that this matches the user intent.)

Rather than a general rule of trying to interpret _every_ string as JSON (as Terraform's human-oriented plan renderer is forced to do), you could instead elect to implement special interpretation for certain attributes of certain resource types, such as the `policy` attribute of the various AWS IAM resource types.

Sorry I misunderstood your request on the first read, and I hope the above rationale makes sense for why we don't intend to make the change you've requested. Thanks again for this feature request!

**Closed by apparentlymart** 2019-03-27 00:44 UTC
Labels: bug, cli

**Comment by awallace-r7** [comment] 2019-03-27 08:59
Hi @apparentlymart - yes makes sense. Thanks for the clarification.
