### ISSUE TITLE
Discussion - Do we need nominate terraform version in tf file now.

### ISSUE THREAD

**Issue by SydOps** [hashicorp/terraform#13141] opened 2017-03-28 22:24 UTC
Hi there,

I deal with different terraform versions recently. With the experience from Cloudformation, should we have the same to nominate the version in tf file now?

In AWS Cloudformation (yml)

      AWSTemplateFormatVersion: '2010-09-09' 

Do we need similar setting in terraform configuration? So we can run with latest terraform, but still get the old version of codes works.

**Comment by apparentlymart** [comment] 2017-03-28 22:51
Hi @SydOps! Thanks for this feature request.

CloudFormation is a hosted service, so it's useful for it to be able to run templates from older versions for a while since you (as a user) are not in control of when new versions of CloudFormation are deployed.

Since Terraform is a tool you install locally, it's possible to just keep multiple versions of it installed and run the appropriate version for the codebase you're working on. This way you're guaranteed to get the expected behavior, vs. the risk that a newer version of Terraform would *attempt* to emulate an older version but possibly have bugs in it.

You can use [the `required_version` argument](https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version) in the `terraform` block to constrain a particular configuration to run only with specific versions of Terraform. This can be useful to prevent mistakes in an environment where different configurations are using different versions, since Terraform will refuse to run if the wrong version is accidentally selected.

Installing multiple versions is the recommended approach for now, so I'm going to close this issue. Thanks again for the suggestion!

**Closed by apparentlymart** 2017-03-28 22:51 UTC

**Comment by SydOps** [comment] 2017-03-29 01:49
Thanks, `required_version` is good enough for me. That's what I am looking for.
