### ISSUE TITLE
Terraform init fails to install correct module version when using module + override

### ISSUE THREAD

**Issue by awendt** [hashicorp/terraform#32753] opened 2023-02-28 13:14 UTC
### Terraform Version

```shell
Terraform v1.3.9
on darwin_arm64
```

### Terraform Configuration Files

```terraform
# Please clone https://github.com/awendt/reproduce-terraform-bug
```

### Debug Output

https://gist.github.com/awendt/029cf25e9d79724a84613fd697067d02

### Expected Behavior

`terraform init` succeeds

### Actual Behavior

1. `terraform init` ignores `version = "3.18.0"`
2. Instead, `terraform init` installs latest version of module
3. `terraform init` shows an error:

```
│ Error: Module version requirements have changed
│
│   on foo.tf line 2, in module "vpc":
│    2:   source  = "terraform-aws-modules/vpc/aws"
│
│ The version requirements have changed since this module was installed and the installed version (3.19.0)
│ is no longer acceptable. Run "terraform init" to install all modules required by this configuration.
```

### Steps to Reproduce

1. `terraform init`

**Comment by jbardin** [comment] 2023-02-28 14:05
Duplicate of #32305

**Closed by jbardin** 2023-02-28 14:05 UTC
Labels: bug, new
