### ISSUE TITLE
`terraform graph`/`terraform validate` fail when run on a shared module with provider `configuration_aliases`

### ISSUE THREAD

**Issue by gabriellesc** [hashicorp/terraform#28719] opened 2021-05-17 16:36 UTC
We have several shared modules for which we run `terraform graph` to generate a visual representation of the module, for documentation purposes, and run `terraform validate` to validate the configuration in the module. This works as expected for our shared modules that _don't_ use provider `configuration_aliases`, but gives the error below for the module that does.

### Terraform Version
```
Terraform v0.15.3
on darwin_amd64
```

### Terraform Configuration Files
https://github.com/tophatmonocle/terraform-provider-issue

### Debug Output
https://gist.github.com/gabriellesc/da8bb11be00ed9477cb041b4d583f96f

### Expected Behavior
A graph should be produced.

### Actual Behavior
The following error occurred:
```
╷
│ Error: Provider configuration not present
│
│ To work with aws_vpc.example (expand) its original provider configuration at provider["registry.terraform.io/hashicorp/aws"].ca is required, but it has been removed. This occurs when a provider configuration is removed while objects created by that provider still
│ exist in the state. Re-add the provider configuration to destroy aws_vpc.example (expand), after which you can remove the provider configuration again.
╵
```
No graph was produced. 

### Steps to Reproduce
1. `terraform init`
2. `terraform graph` (or `terraform validate`)

**Comment by jbardin** [comment] 2021-05-17 16:53
Duplicate of #28490

**Closed by jbardin** 2021-05-17 16:53 UTC
Labels: bug, new
