### ISSUE TITLE
Traversing a list of lists that contain a map element - attribute not found

### ISSUE THREAD

**Issue by jimmycal** [hashicorp/terraform#13504] opened 2017-04-10 14:39 UTC
### Terraform Version
Terraform v0.8.8

I have a computed data object that I am using count on to retrieve the state of N number of objects. The result is a list of lists of maps. 

If I use an output variable I can successfully retrieve values from attributes off the map.  
This works - 
output "vnic_ids" {
  value = ["${data.baremetal_core_vnic_attachments.vnics.*.vnic_attachments.0.vnic_id}"]
}

However, when I try to retrieve the same value i
This does not work 
data "baremetal_core_vnic" "vnic" {
   count = 3
   vnic_id = "${element(data.baremetal_core_vnic_attachments.vnics.*.vnic_attachments.0.vnic_id, count.index)}"
}

* Resource 'data.baremetal_core_vnic_attachments.vnics' does not have attribute 'vnic_attachments.0.vnic_id' for variable 'data.baremetal_core_vnic_attachments.vnics.*.vnic_attachments.0.vnic_id'

What is the difference between output, and a data/resource type that would result in this behavior?

**Comment by jbardin** [comment] 2017-04-20 19:56
Hi @jvcalise,

Outputs are currently unusual in that they don't generate errors themselves, which could explain the behavior.

Can you provide the detailed logs or a reduced config to reproduce the issue?

**Comment by jvcalise** [comment] 2017-05-03 17:38
Hey @jbardin 

Thanks for the help!

Updated my Terraform version to 0.9.4 and the issue remains.   

I could share a reproducer, but you will need access to the Oracle Bare Metal Cloud.  Do you have access?  Without reproducing, I have uploaded a TF config that work, and a second that fails, and the corresponding state files to show the created resources.  

The crux of the issue is the ability to traverse a data object that is a list of lists that contain a map.  
Specifically I have 

data "baremetal_core_vnic" "vnic" {
   vnic_id = "${data.baremetal_core_vnic_attachments.vnics.vnic_attachments.0.vnic_id}"
}

In the single instance case, the above works just fine.  However If I have multiple vnic_attachments which is the case when I am using count to create multiple server. I cannot do the following.

data "baremetal_core_vnic" "vnic" {
   count = 2
   vnic_id = "${element(data.baremetal_core_vnic_attachments.vnics.*.vnic_attachments.0.vnic_id, count.index)}"
}

terraform plan will fail with this configuration 
* data.baremetal_core_vnic.vnic[0]: Resource 'data.baremetal_core_vnic_attachments.vnics' does not have attribute 'vnic_attachments.0.vnic_id' for variable 'data.baremetal_core_vnic_attachments.vnics.*.vnic_attachments.0.vnic_id'
* data.baremetal_core_vnic.vnic[1]: Resource 'data.baremetal_core_vnic_attachments.vnics' does not have attribute 'vnic_attachments.0.vnic_id' for variable 'data.baremetal_core_vnic_attachments.vnics.*.vnic_attachments.0.vnic_id'

My assumption based on the documentation is that the use of element flattens the resulting data structure, so there is no way to go any deeper into the next array.

The workaround is to move this into a module, and define an output variable that is the list of vnic IDs, that a parent can easily traverse.  

output "vnic_ids" {
  value = ["${data.baremetal_core_vnic_attachments.vnics.*.vnic_attachments.0.vnic_id}"]
}

[share.zip](https://github.com/hashicorp/terraform/files/974195/share.zip)

**Comment by nshttpd** [comment] 2017-12-21 22:02
@jimmycal .. while trying to abuse Terraform for something similar I think I've come up with a solution that works. A combination of the `data` and `locals` let me add private_ip address ocid's to a route table for setting up routing through a natgw per AD with a `count`. You may not be trying that exact thing, but something similar ..

get the private ip addys for the natgw hosts. 

```
data "oci_core_private_ips" "natgw_ips" {
  depends_on = ["oci_core_instance.natgw_host"]
  count = 3
  subnet_id = "${element(oci_core_subnet.edge_subnet.*.id, count.index)}"  
  ip_address = "${element(oci_core_instance.natgw_host.*.private_ip, count.index)}"
}
```

flatten down the private_ips into a locals var :

```
locals {
  natgwip = "${flatten(data.oci_core_private_ips.natgw_ips.*.private_ips)}"
}
```

use that to feed into the route table definition to have private subnet route through natgw per AD :

```
resource "oci_core_route_table" "natgw" {
  depends_on     = ["oci_core_instance.natgw_host"]
  count          = 3
  compartment_id = "${oci_identity_compartment.vcn_shared.id}"
  vcn_id         = "${oci_core_virtual_network.vcn_shared.id}"
  display_name   = "${format("natgw-%d", count.index + 1)}"

  route_rules {
    # All traffic leaving the subnet needs to go to route target.
    cidr_block = "0.0.0.0/0"
    network_entity_id = "${lookup(local.natgwip[count.index], "id")}"
  }
}
```

**Comment by teamterraform** [comment] 2019-07-17 23:40
Hi all! Sorry for the long silence here.

The splat syntax had a number of unfortunate limitations and quirks in Terraform 0.11 and earlier, and we suspect this is one of the symptoms of that. The codepath that generated this error message in prior versions is no longer present in Terraform 0.12 because the language engine was rewritten, and so this should now behave as expected in recent versions.

In particular, the "splat syntax" is now a first-class operator that can apply to any list, whereas before it was a special case for resources only.

If you're seeing splat-syntax-related issues in Terraform 0.12 or later, please open a new issue so we can capture information relevant to the new implementation. We're going to close this one out now, since this class of issue is no longer present in Terraform 0.12. Thanks!

**Closed by teamterraform** 2019-07-17 23:40 UTC
Labels: config, question
