### ISSUE TITLE
Optional attributes does not respect the type definition

### ISSUE THREAD

**Issue by valentindeaconu** [hashicorp/terraform#32227] opened 2022-11-16 14:02 UTC
### Terraform Version

```shell
Terraform v1.3.4
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "1.3.4"
}

variable "example" {
  type = map(
    object({
      name        = optional(string)
      description = optional(string)
      config = optional(
        object({
          count = number
          other = string
          flag  = optional(bool, true)
        })
      )
    })
  )
  default = {}
}

output "example" {
  value = var.example
}
```

### Expected Behavior

The returned object should set the `config` attribute to null if this attribute is not set.

Assuming that we inject into the input variable the following value:
```
example = {
  "key1" = {
    description = "value"
    name        = "value"
  }
}
```

The output (and of course, the object) should look like:
```
Changes to Outputs:
  + example = {
      + "key1" = {
          + config      = null
          + description = "value"
          + name        = "value"
        }
    }
```
(this is the output from the same code, ran with Terraform v1.3.3)

### Actual Behavior

The returned object contains the config attribute set to a wrong value:

```
Changes to Outputs:
  + example = {
      + "key1" = {
          + config      = {
              + flag = true
            }
          + description = "value"
          + name        = "value"
        }
    }
```

This is wrong on so multiple levels:
- I declared the `config` as `optional(<type>)` and did not provide a default value. I expect it to be `null` if it wasn't manually set;
- The default value injected does not respect the type declared; I expect the `config` attribute to be of type:
  ```terraform
  object({
    count = number
    other = string
    flag  = optional(bool, true)
  })
  ```
  And the returned object has type:
  ```terraform
  object({
    flag = bool
  })
  ```

### Steps to Reproduce

1. Create a `main.tf` file with the following content:
```terraform
terraform {
  required_version = "1.3.4"
}

variable "example" {
  type = map(
    object({
      name        = optional(string)
      description = optional(string)
      config = optional(
        object({
          count = number
          other = string
          flag  = optional(bool, true)
        })
      )
    })
  )
  default = {}
}

output "example" {
  value = var.example
}
```
2. Create an `example.auto.tfvars` file with the following content:
```terraform
example = {
  "key1" = {
    description = "value"
    name        = "value"
  }
}
```
3. `terraform init`;
4. `terraform plan`;
5. Observe the planned changes to the output;
6. Downgrade to Terraform v1.3.3 and repeat the steps, then compare the planned changes to the output.

### Additional Context

This bug appeared in v1.3.4, downgrading to v1.3.3 fixes the issue.

**Comment by jbardin** [comment] 2022-11-16 14:32
Duplicate of #32160

**Closed by jbardin** 2022-11-16 14:32 UTC
Labels: bug, new
