### ISSUE TITLE
Terraform crashed on me

### ISSUE THREAD

**Issue by Degooya** [hashicorp/terraform#34747] opened 2024-02-29 08:38 UTC
### Terraform Version

```shell
Terraform v1.4.0
on windows_amd64
+ provider registry.terraform.io/betr-io/mssql v0.3.0
+ provider registry.terraform.io/hashicorp/azurerm v3.87.0
+ provider registry.terraform.io/hashicorp/http v3.4.1
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2b26240, 0x4879f90})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/plans.(*Plan).CanApply(0x0?)
        /home/circleci/project/project/internal/plans/plan.go:100 +0x18
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc0001f75e0, {0x34c4558, 0xc00052edc0}, {0x34c4558, 0xc00052ee00}, 0xc000a1c240, 0xc00052ed80)
        /home/circleci/project/project/internal/backend/local/backend_plan.go:104 +0x690
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1()
        /home/circleci/project/project/internal/backend/local/backend.go:323 +0xc3
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:316 +0x44a

### Expected Behavior

creating a variety of resources

### Actual Behavior

it crashed.

### Steps to Reproduce

$ terraform plan -var-file=../../variables/dev.tfvars

**Comment by Degooya** [comment] 2024-02-29 08:50
It was caused when I removed  vnet.azurerm_virtual_network_peering resources from my terraform code. I was able to resolve it by terraform state rm module.vnet.azurerm_virtual_network_peering.name

**Comment by liamcervante** [comment] 2024-02-29 12:54
Hi @Degooya, I think this is a duplicate of https://github.com/hashicorp/terraform/issues/32810. Upgrading to Terraform v1.4.1 should fix this for you. 

Please feel free to reopen if you can still replicate this with a later version. Thanks!

**Closed** 2024-02-29 12:54 UTC
Labels: bug, duplicate
