### ISSUE TITLE
cross module dependency

### ISSUE THREAD

**Issue by comozo** [hashicorp/terraform#4603] opened 2016-01-10 08:40 UTC
Hi,

We are trying to reference a module resource from another module but it does not seem to work.

So our directory structure is the following:

```
├── a
│   ├── main.tf
│   └── terraform.tfstate
├── b
│   ├── main.tf
│   └── terraform.tfstate
├── main.tf
└── terraform.tfstate
```

then we have the /main.tf in the root directory

```
module "a" {
    source = "./a"
}

module "b" {
    source = "./b"
}

output "mtmv" {
    value = "${module.a.value}"
}

output "mumv" {
    value = "${module.b.value}"
}
```

Then we have /a/main.tf

```
output "value" {
    value = "aaa"
}
```

Then we have /b/main.tf

```
output "value" {
    value = "bbb"
}

output "mtmv" {
    value = "${module.a.value}"
}
```

When we ran terraform plan we have this error:

```
Error configuring: 1 error(s) occurred:

* output.mtmv: missing dependency: module.a.output.value
```

Thank you for your help,

**Comment by jen20** [comment] 2016-01-10 10:00
Hi @comozo! Thanks for opening this. It looks like you're referring to `${module.a.value}` in a file in a module nested deeper, instead of the input you defined? Is this intentional (which might indicate a need to refactor the modules) or a typo? The problem is in `/b/main.tf`, specifically this section:

```
output "mtmv" {
    value = "${module.a.value}"
}
```

To achieve this you'd need to define a variable in module B and pass the value from module A to it in the composition root. Does that explanation make sense?

**Comment by comozo** [comment] 2016-01-10 10:38
Thank you for the quick reply. 
Yes it is intentional I would to use a resource defined in another module.
I'm sorry I didn't get your explanation.

Thanks

**Comment by nkbt** [comment] 2016-01-11 03:58
I managed to get it working with this sample config:

```
├── a
│   └── main.tf
├── x
│   └── main.tf
└── root.tf
```


### root.tf

```
module "x" {
  source = "./x"
}

module "a" {
  source = "./a"
  XTopic = "${module.x.XTopicArn}"
}
```


### x/main.tf
```
resource "aws_sns_topic" "XTopic" {
  name = "my-x-topic"
}

output "XTopicArn" {
  value = "${aws_sns_topic.XTopic.arn}"
}
```

### a/main.tf

```
variable "XTopic" {
}


resource "aws_sqs_queue" "AQueue" {
  name = "my-a-queue"
}


resource "aws_sns_topic_subscription" "ABucketTopicSubscription" {
  topic_arn = "${var.XTopic}"
  protocol = "sqs"
  endpoint = "${aws_sqs_queue.AQueue.arn}"
}
```

**Comment by artburkart** [comment] 2016-02-28 19:49
@nkbt - This worked for me, thank you!

**Comment by dennybaa** [comment] 2016-07-31 21:33
Cross module dependencies don't work indeed, +1 to have this feature.

**Comment by RomanManz** [comment] 2016-11-12 16:40
@nkbt - Worked, you made my day!

**Comment by mitchellh** [comment] 2016-12-04 00:09
Closing since we have a solution.

**Closed by mitchellh** 2016-12-04 00:09 UTC
Labels: core, question
