### ISSUE TITLE
"is empty tuple" with local declaration

### ISSUE THREAD

**Issue by fnickels** [hashicorp/terraform#26044] opened 2020-08-28 20:13 UTC
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```terraform
locals {
    nlb_ip_addresses =  aws_lb.controlplane_nlb.subnet_mapping.*.private_ipv4_address 
}

resource "aws_route53_resolver_rule" "reverse_10_in_addr_arpa" {
  domain_name          = "10.in-addr.arpa"
  name                 = "10_in_addr_arpa_forward"
  rule_type            = "FORWARD"

  resolver_endpoint_id = aws_route53_resolver_endpoint.outbound.id

  dynamic "target_ip" {
    for_each = local.nlb_ip_addresses

    content {
      ip = target_ip.value
      port = 53
    }
  }
}

resource "aws_route53_resolver_rule" "example_com" {
  domain_name          = "example.com"
  name                 = "example_com_forward"
  rule_type            = "FORWARD"

  resolver_endpoint_id = aws_route53_resolver_endpoint.outbound.id

  dynamic "target_ip" {
    for_each = local.nlb_ip_addresses

    content {
      ip = target_ip.value
      port = 53
    }
  }
}
```

### Expected Behavior

This code works fine almost 98% of the time, but I have run into a case where I got the following error when running `terraform plan`:

```
12:32:36  Error: Unsupported attribute
12:32:36  
12:32:36    on .terraform/modules/controlplane-route53-resolver/locals.tf line 5, in locals:
12:32:36     5:     nlb_ip_addresses =  aws_lb.controlplane_nlb.subnet_mapping.*.private_ipv4_address 
12:32:36      |----------------
12:32:36      | aws_lb.controlplane_nlb is empty tuple
12:32:36  
12:32:36  This value does not have any attributes.
```
I suspect the state file for this case has something out of wack, but I did not investigate further.  

On a hunch, I removed the local and placed the expression in each of the rules.

```terraform
resource "aws_route53_resolver_rule" "reverse_10_in_addr_arpa" {
  domain_name          = "10.in-addr.arpa"
  name                 = "10_in_addr_arpa_forward"
  rule_type            = "FORWARD"

  resolver_endpoint_id = aws_route53_resolver_endpoint.outbound.id

  dynamic "target_ip" {
    for_each = aws_lb.controlplane_nlb.subnet_mapping.*.private_ipv4_address

    content {
      ip = target_ip.value
      port = 53
    }
  }
}

resource "aws_route53_resolver_rule" "example_com" {
  domain_name          = "example.com"
  name                 = "example_com_forward"
  rule_type            = "FORWARD"

  resolver_endpoint_id = aws_route53_resolver_endpoint.outbound.id

  dynamic "target_ip" {
    for_each = aws_lb.controlplane_nlb.subnet_mapping.*.private_ipv4_address

    content {
      ip = target_ip.value
      port = 53
    }
  }
}
```

This cleared up the issue.

I suspect there is a bug in Terraform's static analysis that is somehow being influenced by values found in the state file with the object.

It may be specific to locals that have multi tiered objects such as: `aws_lb.controlplane_nlb.subnet_mapping.*` it might not recognize the dependency on `aws_lb.controlplane_nlb` prior to attempting to resolve the full expression.  

Not sure why the initial code set runs flawlessly most of the time, nor how the state file factors into this.  I was not able to recreate a reproduction of this issue to submit with this ticket.

**Comment by jbardin** [comment] 2020-08-31 22:53
Hi @fnickels,

Thanks for filing the issue. I suspect this is covered by resource evaluation changes made to 0.13. Since we don't have any way to reproduce this at the moment to test with 0.13, there's not much we can work with here. Going to close this for now, but if you do run into this problem with 0.13, please file a new issue.

Thanks!

**Closed by jbardin** 2020-08-31 22:53 UTC
Labels: bug, new
