### ISSUE TITLE
[0.12] Taint of resource with count can't taint all items

### ISSUE THREAD

**Issue by domgoodwin** [hashicorp/terraform#21509] opened 2019-05-29 17:29 UTC
Before in 0.11 I could taint a resource with a count without having to know how many resources there was. Now when I do it need to use the new module reference syntax with [0] on the end to reference a single resource and can't use splat to get all.

### Terraform Version

```
Terraform v0.12.0
```

### Terraform Configuration Files
```hcl
resource "aws_ebs_volume" "volume" {
  count             = 3
  availability_zone = element(var.azs, count.index)
  size              = var.disk_volume_size
  type              = var.volume_type
  encrypted         = var.encrypt_volume
  kms_key_id        = var.kms_key_id
  snapshot_id       = var.data_disk_snapshot_id
}
```

### Expected Behavior
As in terraform 0.11
```terraform taint -module=my-volume aws_ebs_volume.volume```
And all of my volumes with counts would be tainted

### Actual Behavior
Now with the new calling syntax it doesn't allow me taint a group of resources with counts

```terraform taint module.my-volume.aws_ebs_volume.volume```

> Gives me an error saying "No resource instance"

```terraform taint module.my-volume.aws_ebs_volume.volume[0]```

> Works but only for the 1st volume

```terraform taint module.my-volume.aws_ebs_volume.volume[*]```

> Gives me an error saying "Splat expressions ([*]) may not be used here."

**Comment by querry43** [comment] 2019-07-22 22:50
I too depended on this functionality for tainting all of my replica databases when I rebuilt the master.  It is nice if the engineer doing this doesn't have to know how many replicas we have.  Everything else is just copy/paste.

**Comment by mercuriete** [comment] 2020-01-14 11:57
it affects to me as well.

**Comment by StobyWan** [comment] 2020-05-09 13:51
it affects to me as well.

**Comment by pselle** [comment] 2020-11-10 21:26
This issue is absolutely still valid, however I am closing it to consolidate it as a duplicate of https://github.com/hashicorp/terraform/issues/1768

**Closed by pselle** 2020-11-10 21:26 UTC
Labels: bug, cli, confirmed, v0.12
