### ISSUE TITLE
Error removing azurerm infrastructure: "Public IP address can not be deleted"

### ISSUE THREAD

**Issue by sheerun** [hashicorp/terraform#11073] opened 2017-01-06 01:59 UTC
### Terraform Version
Terraform v0.8.2

### Affected Resource(s)
- azurerm_network_interface
- azurerm_subnet
- azurerm_public_ip
- ???

### Terraform Configuration Files
```hcl
resource "azurerm_subnet" "default" {
  name = "${var.prefix}-subnet"
  resource_group_name = "${azurerm_resource_group.default.name}"
  virtual_network_name = "${azurerm_virtual_network.default.name}"
  address_prefix = "10.0.1.0/24"
  route_table_id = "${azurerm_route_table.default.id}"
}

resource "azurerm_network_security_group" "default" {
  name = "${var.prefix}-security-group"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
}

module "master1_network_interface" {
  source = "./network_interface"
  prefix = "${var.prefix}-master1"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  subnet_id = "${azurerm_subnet.default.id}"
  security_group_id = "${azurerm_network_security_group.default.id}"
}
```

```hcl
variable "resource_group_name" {}
variable "security_group_id" {}
variable "location" {}
variable "prefix" {}
variable "subnet_id" {}

resource "azurerm_public_ip" "master" {
  name = "${var.prefix}-ip"
  location = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  public_ip_address_allocation = "static"
}

resource "azurerm_network_interface" "master" {
  name = "${var.prefix}-interface"
  location = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  network_security_group_id = "${var.security_group_id}"
  internal_dns_name_label = "${var.prefix}"

  ip_configuration {
    name = "${var.prefix}-ipconfig"
    subnet_id = "${var.subnet_id}"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id = "${azurerm_public_ip.master.id}"
  }
}

output "network_interface_id" {
  value = "${azurerm_network_interface.master.id}"
}

output "ip_address" {
  value = "${azurerm_public_ip.master.ip_address}"
}
```

### Debug Output
* azurerm_network_security_group.default: network.SecurityGroupsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseNetworkSecurityGroupCannotBeDeleted" Message="Network security group /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkSecurityGroups/api-security-group cannot be deleted because it is in use by the following resources: /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-node2-interface, /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-node1-interface, /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-node3-interface, /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-master1-interface." Details=[]
* azurerm_subnet.default: network.SubnetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet api-subnet is in use by /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-node2-interface/ipConfigurations/api-node2-ipconfig and cannot be deleted." Details=[]
* azurerm_public_ip.master: network.PublicIPAddressesClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/publicIPAddresses/api-node2-ip can not be deleted since it is still allocated to resource /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-node2-interface." Details=[]
* azurerm_public_ip.master: network.PublicIPAddressesClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/publicIPAddresses/api-node1-ip can not be deleted since it is still allocated to resource /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-node1-interface." Details=[]
* azurerm_public_ip.master: network.PublicIPAddressesClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/publicIPAddresses/api-master1-ip can not be deleted since it is still allocated to resource /subscriptions/75da82e8-cf3d-416d-8547-2d9a737611ff/resourceGroups/api/providers/Microsoft.Network/networkInterfaces/api-master1-interface." Details=[]

### Expected Behavior
First network interface is removed, then public ip is removed.

### Actual Behavior
Public ip and network interface is deleted at the same time, leading to an error when deleting public ip that is used in network interface. The same happens to subnet and network security group.

### Steps to Reproduce

1. create azurerm infrastructure with a subnet, and network inferface with at least ip_configuration
2. terraform destroy

### Important Factoids
It seems azurerm fails to track dependencies for few resources. In this case it seems any dependencies  on network interface are not tracked.

**Comment by samirageb** [comment] 2017-01-18 23:18
I am on v0.8.4 and am not running into these dependency issues. In my case, my .tf file has
- No resources imported (clean .tfstate)
- Remote state w/azurerm provider
- Module to provision Resource Group
- Module to provision vnet
- Module to provision subnet
- Module to provision Public IP
- Normally defined azurerm_network_interface
- Normally defined azurerm_virtual_machine

I can confirm that redeploying the virtual machine will appropriately teardown the VM, followed by the NIC, followed by the Public IP.

I wonder if the NIC/Public IP aren't associated properly such that TF can't resolve the dependencies. Seeing the entire problematic .tf, tfvars & relevant modules would be useful...

**Comment by sheerun** [comment] 2017-01-19 10:42
@samirageb I'm sorry you failed to reproduce this issue. It seems `terraform destroy` actually works, but commenting resources and running `terraform apply` fails (this is the most common way to destroy resources when doing sysadmin tasks).

Here are fill terraform files (maybe not minimal) to reproduce this issue:

main.tf
```tf
terraform {
  required_version = ">= 0.8, < 0.9"
}

variable "prefix" { default = "debug" }
variable "location" { default = "West Europe" }

variable "subscription_id" { default = "xxx" }
variable "client_id" { default = "yyy" }
variable "client_secret" { default = "zzz" }
variable "tentant_id" { default = "ttt" }
variable "azure_storage_name" { default = "somethinguniqueasdfasd" }

provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tentant_id}"
}

resource "azurerm_resource_group" "default" {
  name     = "${var.prefix}"
  location = "${var.location}"
}

resource "azurerm_virtual_network" "default" {
  name = "${var.prefix}-net"
  address_space = ["10.0.0.0/16"]
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
}

resource "azurerm_network_security_group" "default" {
  name = "${var.prefix}-security-group"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
}

resource "azurerm_route_table" "default" {
  name = "${var.prefix}-route-table"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"

  route {
    name = "local"
    address_prefix = "10.0.0.0/16"
    next_hop_type = "vnetlocal"
  }

  route {
    name = "internet"
    address_prefix = "0.0.0.0/0"
    next_hop_type = "internet"
  }
}

resource "azurerm_subnet" "default" {
  name = "${var.prefix}-subnet"
  resource_group_name = "${azurerm_resource_group.default.name}"
  virtual_network_name = "${azurerm_virtual_network.default.name}"
  address_prefix = "10.0.1.0/24"
  route_table_id = "${azurerm_route_table.default.id}"
}

resource "azurerm_storage_account" "default" {
  name = "${var.azure_storage_name}"
  resource_group_name = "${azurerm_resource_group.default.name}"

  location = "${var.location}"
  account_kind = "Storage"
  account_type = "Standard_GRS"
  enable_blob_encryption = true
}

resource "azurerm_storage_container" "images" {
  name = "vhds"
  resource_group_name = "${azurerm_resource_group.default.name}"
  storage_account_name = "${azurerm_storage_account.default.name}"
  container_access_type = "private"
}

resource "azurerm_availability_set" "default" {
  name = "${var.prefix}-availability-set"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
}

module "master1_virtual_machine" {
  source = "./virtual_machine"
  prefix = "${var.prefix}-master1"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  subnet_id = "${azurerm_subnet.default.id}"
  security_group_id = "${azurerm_network_security_group.default.id}"
  vhd_uri = "${azurerm_storage_account.default.primary_blob_endpoint}${azurerm_storage_container.images.name}/master1.vhd"
  availability_set_id = "${azurerm_availability_set.default.id}"
}

module "master2_virtual_machine" {
  source = "./virtual_machine"
  prefix = "${var.prefix}-master2"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  subnet_id = "${azurerm_subnet.default.id}"
  security_group_id = "${azurerm_network_security_group.default.id}"
  vhd_uri = "${azurerm_storage_account.default.primary_blob_endpoint}${azurerm_storage_container.images.name}/master2.vhd"
  availability_set_id = "${azurerm_availability_set.default.id}"
}

module "master3_virtual_machine" {
  source = "./virtual_machine"
  prefix = "${var.prefix}-master3"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  subnet_id = "${azurerm_subnet.default.id}"
  security_group_id = "${azurerm_network_security_group.default.id}"
  vhd_uri = "${azurerm_storage_account.default.primary_blob_endpoint}${azurerm_storage_container.images.name}/master3.vhd"
  availability_set_id = "${azurerm_availability_set.default.id}"
}

module "master4_virtual_machine" {
  source = "./virtual_machine"
  prefix = "${var.prefix}-master4"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  subnet_id = "${azurerm_subnet.default.id}"
  security_group_id = "${azurerm_network_security_group.default.id}"
  vhd_uri = "${azurerm_storage_account.default.primary_blob_endpoint}${azurerm_storage_container.images.name}/master4.vhd"
  availability_set_id = "${azurerm_availability_set.default.id}"
}

module "master5_virtual_machine" {
  source = "./virtual_machine"
  prefix = "${var.prefix}-master5"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  subnet_id = "${azurerm_subnet.default.id}"
  security_group_id = "${azurerm_network_security_group.default.id}"
  vhd_uri = "${azurerm_storage_account.default.primary_blob_endpoint}${azurerm_storage_container.images.name}/master5.vhd"
  availability_set_id = "${azurerm_availability_set.default.id}"
}
```

virtual_machine/main.tf
```tf
variable "resource_group_name" {}
variable "security_group_id" {}
variable "location" {}
variable "prefix" {}
variable "subnet_id" {}

variable "availability_set_id" {}
variable "vhd_uri" {}

resource "azurerm_public_ip" "master" {
  name = "${var.prefix}-ip"
  location = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  public_ip_address_allocation = "static"
}

resource "azurerm_network_interface" "master" {
  name = "${var.prefix}-interface"
  location = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  network_security_group_id = "${var.security_group_id}"
  internal_dns_name_label = "${var.prefix}"

  ip_configuration {
    name = "${var.prefix}-ipconfig"
    subnet_id = "${var.subnet_id}"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id = "${azurerm_public_ip.master.id}"
  }
}

resource "azurerm_virtual_machine" "master" {
  name = "${var.prefix}"

  location = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  network_interface_ids = ["${azurerm_network_interface.master.id}"]
  vm_size = "Standard_D2"
  availability_set_id = "${var.availability_set_id}"

  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "Canonical"
    offer = "UbuntuServer"
    sku = "16.04.0-LTS"
    version = "latest"
  }

  storage_os_disk {
    name = "${var.prefix}"
    vhd_uri = "${var.vhd_uri}"
    caching = "ReadWrite"
    create_option = "FromImage"
  }

  os_profile {
    computer_name = "${var.prefix}"
    admin_username = "ubuntu"
    admin_password = "Pass!4dev0ps1"
  }
}

output "network_interface_id" {
  value = "${azurerm_network_interface.master.id}"
}

output "ip_address" {
  value = "${azurerm_public_ip.master.ip_address}"
}
```

Way to reproduce:

```bash
terraform apply
# comment/remove all virtual machines in main.tf
terraform apply
```

**Comment by samirageb** [comment] 2017-01-22 19:14
@sheerun Thanks for this. I'll see if I can simplify this down to a minimal repro.

**Comment by justfortier** [comment] 2017-02-13 18:11
@samirageb any luck with this? I'm also running into this issue with 0.8.5 with Azurerm provider. Just like @sheerun mentioned, destroy works fine, it's simply apply that has troubles destroying. For me it seems like it won't drop the subnet, because the network interface attached to it wasn't destroyed first.

**Comment by StephenWeatherford** [comment] 2017-04-20 20:17
@justfortier @sheerun I tried the repro configuration and steps from Jan 19 (applying, not deleting) multiple times with different variations, and couldn't repro the problem.  I'm using 0.9.3.  Are you still hitting this?  Thx.

**Comment by sheerun** [comment] 2017-04-21 11:17
@StephenWeatherford I cannot reproduce as well no more when running on code from master

**Comment by samirageb** [comment] 2017-04-24 21:43
@justfortier Sorry for the long delay. I cannot repro it anymore. on .9.x Will post back to this thread if anything changes.

**Comment by StephenWeatherford** [comment] 2017-04-28 17:00
Thanks!  
@sheerun, would you mind closing the issue?

**Closed** 2017-04-29 08:33 UTC
Labels: bug, provider/azurerm
