### ISSUE TITLE
Why did terraform create its own aws default provider when I didn't.

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#28483] opened 2021-04-22 07:49 UTC
Closely related to issue https://github.com/hashicorp/terraform/issues/28482

### Terraform Version 0.15.0

The following code works if AWS_DEFAULT_REGION is set to us-east-1

It has no right to work, because aws_caller_identity does not provider a provider of aws.me - and there is no provider without an alias. 

This must mean terraform is inferring a missing provider to try and make the code work, but what settings would it have? It seems that this could lead to nasty outcomes because of accidental missing provider attributes on resources in a codebase with no "default" provider. Far better for terraform to be specific and give an error message that no default aws provider has been defined, than actually it works with unknown settings - and could end up terraforming resources in regions you dont want it to.

## Terraform Configuration Files

```
provider "aws" {
  alias  = "me"
  region = "eu-west-1"
}

data "aws_caller_identity" "current" {}
```

**Comment by jbardin** [comment] 2021-04-22 12:58
Hi @gtmtech,

Terraform has always used a default provider configuration when none was found, so this is not something which has changed in 0.15. When a provider configuration is not found, an empty configuration is always used as the default. If a resource requires a specific provider configuration which is not using the default name, that resource _must_ use the `provider` argument to associate which provider configuration it requires. 

In your example, `data.aws_caller_identity.current` will use a provide config called `aws`, while the provider configuration block you have is referenced as `aws.me`. 

Since what you have here is the intended behavior I'm going to close this issue. We can work on improving the error context as described in the linked issue to help troubleshoot similar problems. 

Thanks!

**Closed by jbardin** 2021-04-22 12:58 UTC
Labels: working as designed

**Comment by gtmtech** [comment] 2021-04-26 13:10
@jbardin Hi - thanks for coming back. 

Is it possible to challenge this as a design decision? It can create problems. 

Suppose I have no default provider, but a default region set to us-east-1; but I want to create a bucket in the eu-west-1 region.

```
resource "aws_s3_bucket" "foo" {
...
```

If I forget the provider (which is easy to do), it will be created in the wrong region because the default provider will fill in for the missing provider. This causes quite a horrible delay as it is not possible in global services to reuse unique keys in another region in a suitably quick time. (I think its order of days to fix this in aws)

In my experience, defaults always lead to eventual unintended consequences, and so it's good to be specific about things and have errors if you're not, (unless you specifically create a default yourself). 

Anyway just putting it out there -  not really expecting it to change after all this time, but maybe worth saying

**Comment by jbardin** [comment] 2021-04-26 13:38
Thanks for the feedback @gtmtech. The idea has been brought up before, but rejected for a few reasons. There are many providers where the defaults a adequate and conflicts are not possible, and many providers do not require any configuration all, so enforcing there to be an empty configuration block for these was deemed undesirable, 

What can be done is for the provider to require the configuration itself, which has essentially be done already with the azurerm provider. It is a broad breaking change that needs to be undertaken carefully, but limiting the extent to a single provider rather than all configuration makes it much easier to manage.
