### ISSUE TITLE
Creating AWS ASG fails because there's no LC

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#5633] opened 2016-03-15 12:44 UTC
When creating an ASG, and the LC was/is tainted, TF is proceeding with the destruction of the LC, **BUT** does not create it again before trying to create the ASG.

```
module.ENVIRONMENT.aws_launch_configuration.INSTANCE: Refreshing state... (ID: ENVIRONMENT-INSTANCE-fgmdpbphpfaw7cnnodpkzbd4vu)
module.ENVIRONMENT.aws_launch_configuration.INSTANCE: Destroying...
module.ENVIRONMENT.aws_autoscaling_group.INSTANCE: Creating...
  [...]
Error applying plan:

1 error(s) occurred:

* aws_autoscaling_group.INSTANCE: Error creating Autoscaling Group: ValidationError: Launch configuration name not found - A launch configuration with the name : ENVIRONMENT-INSTANCE-fgmdpbphpfaw7cnnodpkzbd4vu does not exist
        status code: 400, request id: 2bbb243a-eaab-11e5-9878-21a37fe4eb6f
```

Terraform version: 0.6.11.

**Comment by jrasell** [comment] 2016-03-15 14:48
@FransUrbo what does your Terraform file look like? 

It might be a case of using the 'create_before_destroy' meta-parameter on the LC as detailed here - https://www.terraform.io/docs/configuration/resources.html#create_before_destroy

**Comment by catsby** [comment] 2016-03-15 19:36
Hey @FransUrbo – do you have a configuration that will help me reproduce your case? If you can provide one, please be sure to remove any secret information like access keys and secrets.

**Comment by FransUrbo** [comment] 2016-03-16 09:56
The whole setup is huge, but I can give you the offending file. If this isn't enough, let me know and I'll see if I can create a complete test case to reproduce the problem.

Commenting out the <code>aws_autoscaling_policy</code> and <code>aws_autoscaling_schedule</code> in this "solves" the problem.

```
resource "aws_elb" "INSTANCE" {
  name = "ENVIRONMENT-INSTANCE"
  subnets = [ "${aws_subnet.private.id}" ]
  internal = true

  listener {
    instance_port = 8080
    instance_protocol = "http"
    lb_port = 8080
    lb_protocol = "http"
  }

  health_check {
    healthy_threshold = 2
    unhealthy_threshold = 2
    timeout = 3
    target = "TCP:8080"
    interval = 30
  }

  cross_zone_load_balancing = false
  idle_timeout = 400
  connection_draining = true
  connection_draining_timeout = 400

  tags {
    Name = "ENVIRONMENT-INSTANCE"
  }
}

resource "aws_lb_cookie_stickiness_policy" "INSTANCE" {
      name = "ENVIRONMENT-INSTANCE"
      load_balancer = "${aws_elb.INSTANCE.id}"
      lb_port = 8080
      cookie_expiration_period = 600
}

resource "aws_launch_configuration" "INSTANCE" {
  # omit name so it's generated as a unique value
  name_prefix = "ENVIRONMENT-INSTANCE-"

  image_id = "${var.ami}"
  instance_type = "${var.INSTANCE_instance_type}"

  lifecycle {
    create_before_destroy = true
  }

  associate_public_ip_address = false
  security_groups = ["${aws_security_group.default.id}"]
  key_name = "${aws_key_pair.deployer-ENVIRONMENT.key_name}"
  iam_instance_profile = "${aws_iam_instance_profile.INSTANCE.name}"

  root_block_device {
    volume_type = "standard"
    volume_size = 150
    delete_on_termination = true
  }

  // ======================

  # This file packages the files mentioned on the command line into a embedded tar file used in "user_data" below.
  provisioner "local-exec" {
    command = "./bin/package_files_for_LC.sh ENVIRONMENT:INSTANCE bin/remote:/home/${var.provisioner_user} secrets/provisioner:/home/${var.provisioner_user}.ssh/provisioner tf-files/INSTANCE/salt-minion.tpl:/etc/salt/minion"
  }

  user_data = "${file("./modules/ENVIRONMENT/vm-INSTANCE.sh")}"
}

resource "aws_autoscaling_group" "INSTANCE" {
  # interpolate the LC into the ASG name so it always forces an update
  name = "ENVIRONMENT-INSTANCE"

  availability_zones = ["${var.availability_zone}"]
  min_size = 0
  max_size = 10
  health_check_type = "ELB"
  health_check_grace_period = 300
  force_delete = true
  termination_policies = [ "ClosestToNextInstanceHour", "OldestLaunchConfiguration" ]
  vpc_zone_identifier = [ "${aws_subnet.public.id}", "${aws_subnet.private.id}" ]

  launch_configuration = "${aws_launch_configuration.INSTANCE.name}"

  load_balancers = [ "${aws_elb.INSTANCE.id}" ]
}

resource "aws_autoscaling_policy" "INSTANCE" {
  name = "ENVIRONMENT-INSTANCE"
  scaling_adjustment = 2
  adjustment_type = "ChangeInCapacity"
  cooldown = 900 # 15 minutes - takes a while to take up (+provision) an instance...
  autoscaling_group_name = "${aws_autoscaling_group.INSTANCE.name}"
}

resource "aws_autoscaling_schedule" "INSTANCE-in" {
  scheduled_action_name = "ENVIRONMENT-INSTANCE-in"
  min_size = 0
  max_size = 10
  desired_capacity = 0

  start_time = "2016-12-11T18:00:00Z"
  end_time   = "2016-12-12T06:00:00Z"

  autoscaling_group_name = "${aws_autoscaling_group.INSTANCE.name}"
}

resource "aws_autoscaling_schedule" "INSTANCE-out" {
  scheduled_action_name = "ENVIRONMENT-INSTANCE-out"
  min_size = 3
  max_size = 10
  desired_capacity = 3

  start_time = "2016-12-12T06:00:00Z"
  end_time   = "2016-12-11T18:00:00Z"

  autoscaling_group_name = "${aws_autoscaling_group.INSTANCE.name}"
}
```

**Comment by catsby** [comment] 2016-06-15 16:27
Hello friends –

Very sorry for the silence here. From the original output, it doesn't seem like `create_before_destroy` was in place, as there is no  `creating...` before `destroying...`

That, or perhaps a dependency between the ASG and LC wasn't properly in place... hard to say, I tried with this config:

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_launch_configuration" "foobar" {
  image_id      = "ami-dfc39aef"
  instance_type = "t2.micro"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "bar" {
  availability_zones        = ["us-west-2a"]
  name                      = "foobar3-terraform-test"
  max_size                  = 3
  min_size                  = 1
  health_check_grace_period = 300
  health_check_type         = "ELB"
  desired_capacity          = 1
  launch_configuration      = "${aws_launch_configuration.foobar.name}"
}

```

and tainted/applied, and things worked as expected:

```
$ tf taint aws_launch_configuration.foobar
The resource aws_launch_configuration.foobar in the module root has been marked as tainted!

$ tf plan
[...]

~ aws_autoscaling_group.bar
    launch_configuration: "terraform-j7ar4cwgsbdarch5k6hmizdr7y" => "${aws_launch_configuration.foobar.name}"

-/+ aws_launch_configuration.foobar (tainted)
    associate_public_ip_address: "false" => "false"
    ebs_block_device.#:          "0" => "<computed>"
    ebs_optimized:               "false" => "<computed>"
    enable_monitoring:           "true" => "true"
    image_id:                    "ami-dfc39aef" => "ami-dfc39aef"
    instance_type:               "t2.micro" => "t2.micro"
    key_name:                    "" => "<computed>"
    name:                        "terraform-j7ar4cwgsbdarch5k6hmizdr7y" => "<computed>"
    root_block_device.#:         "0" => "<computed>"


Plan: 1 to add, 1 to change, 1 to destroy.

$ tf apply

aws_launch_configuration.foobar: Creating...
  associate_public_ip_address: "" => "false"
  ebs_block_device.#:          "" => "<computed>"
  ebs_optimized:               "" => "<computed>"
  enable_monitoring:           "" => "true"
  image_id:                    "" => "ami-dfc39aef"
  instance_type:               "" => "t2.micro"
  key_name:                    "" => "<computed>"
  name:                        "" => "<computed>"
  root_block_device.#:         "" => "<computed>"
aws_launch_configuration.foobar: Creation complete
aws_autoscaling_group.bar: Modifying...
  launch_configuration: "terraform-j7ar4cwgsbdarch5k6hmizdr7y" => "terraform-4orz5cemfnhfzbptvsqrglo23a"
aws_autoscaling_group.bar: Modifications complete
aws_launch_configuration.foobar: Destroying...

Apply complete! Resources: 1 added, 1 changed, 0 destroyed.
```


Of course, this issue was filed some time ago, so it's just as likely there was a bug that has since been patched!

If you're still seeing this behavior please let me know, but until then I'm going to close this issue. Terribly sorry for the silence!

**Closed by catsby** 2016-06-15 16:27 UTC
Labels: bug, provider/aws
