### ISSUE TITLE
Shorthand for optional resources 

### ISSUE THREAD

**Issue by ascopes** [hashicorp/terraform#33750] opened 2023-08-25 07:30 UTC
### Terraform Version

```shell
1.5
```

### Use Cases

Clearer and more concise code that is DRY.

### Attempted Solutions

Currently, we use a ternary operator, take this dummy example:

```terraform
resource "wiremock_server" "stub" {
  count = var.stubs_enabled ? 1 : 0
}
```

This is okay, but can become more difficult to read. Especially since now everywhere you reference this, you also need to take into account that it is parameterized.

```
security_group_ids = compact([
  kong_server.security_group_id,
  var.stubs_enabled ? wiremock_server.stub[0].security_group_id : null
])
```

Over time this can become more and more cumbersome and error prone, especially when refactoring.

Another option is to create reusable modules, but this can often become more and more unmaintainable for simpler cases as it adds complexity due to additional layers of indirection and is more verbose as you have to now also declare a bunch of variables and outputs to communicate with the module.

### Proposal

In our codebase, we have lots of places where we want to allow enabling or disabling features based on flags and conditions.

For example, we have a bunch of infrastructure that stubs external integrations that we turn on during platform stress testing to prevent API abuse on the upstream integrations we do not depend on.

To do this, we need the ability to optionally create infrastructure based on conditions, ideally maintaining a clear and readable codebase.

One way that could possibly make this simple to implement is to allow an enabled or count attribute to take a boolean.

```terraform
resource "thing" "this" {
  enabled = var.enable_thing
  // or
  count   = var.enable_thing
}
```

This doesn't help with the issue around noise for dereferencing the attributes of optional infrastructure though, unless we were to allow treating 0-or-1 arrays as either existing or not existing when declared this way.

Another way that might be nicer would be to provide a `check`-like block that could allow nesting multiple resources in bulk.

```terraform
optional {
  condition = var.stubs_enabled

  locals {
    wiremock_version = "xxx"
  }

  resource "aws_ami" "wiremock" {
    ...
  }

  resource "aws_launch_template" "wiremock" {
    ...
    ami_id = aws_ami.wiremock.id
  }
    
  resource "aws_instance" "wiremock" {
    ...
    launch_template = aws_launch_template.wiremock.id
  }
}
```

By doing this, all resources within the block can be treated as if they always exist. Outside, referencing them when they do not exist would be an error.

Stuff like outputs could be wrapped in an optional block with the same condition to dereference them when they do not exist, or a try could be used. A ternary could also be used instead.

```terraform
output "stub_wiremock_instance_id" {
  value = var.stubs_enabled ? aws_instance.wiremock.id : null
}
```

**Comment by jbardin** [comment] 2023-08-25 14:35
Duplicate of #21953

**Closed by jbardin** 2023-08-25 14:35 UTC
Labels: enhancement, new
