### ISSUE TITLE
Value is marked, so must be unmarked first

### ISSUE THREAD

**Issue by rtfpessoa** [hashicorp/terraform#28439] opened 2021-04-19 14:45 UTC
### Terraform Version

```
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.19.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
```

### Terraform Configuration Files

The terraform is a bit big, if you can debug this just with the logs would be great, if not I can try to provide private access to it.

### Debug Output

https://gist.github.com/rtfpessoa/c1788731ff419fa9bbb54369ecd9f726

### Crash Output

https://gist.github.com/rtfpessoa/c1788731ff419fa9bbb54369ecd9f726

### Expected Behavior

Run without errors

### Actual Behavior

Panic

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment] 2021-04-19 15:17
Hi @rtfpessoa,

Sorry, I don't have enough information here to read the logs you've provided.
Guessing from the message, you may have a duplicate of #28370, which we can confirm from the stack trace. If not, at a minimum we will need the stack trace, the error output and the relevant configuration.

Thanks!

**Comment by rtfpessoa** [comment] 2021-04-19 15:20
@jbardin so you cannot open the encrypted logs?
I decided to encrypt them since it was too big to be 100% sure it had no credentials, although I went through and removed some stuff.

Anyway, the stacktrace is:

```
panic: value is marked, so must be unmarked first

goroutine 792 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2c2e840, 0xc001a74da0, 0x24e3220, 0xc000b1f4e8, 0x2c2e801)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1045 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc001a75160, 0x1, 0x1, 0x2c2e840, 0xc001a74da0, 0x24e3220, 0xc000b1f4e8, 0x2bf8258, 0xc000b1f500, 0xc000b1f4e8, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:144 +0x2e8
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x2c2e808, 0xc001a74e40, 0x23f4a00, 0xc001c194a0, 0x2bf8258, 0xc000b1f500, 0x0, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x2c2e808, 0xc001a74e40, 0x23f4a00, 0xc001c194a0, 0xc001cb4c00, 0x1, 0x1, 0x0, 0xc001cb4c00, 0x1, ...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/marks.go:215 +0xc5
github.com/hashicorp/terraform/terraform.markProviderSensitiveAttributes(0xc001671a40, 0x2c2e808, 0xc001a74e40, 0x23f4a00, 0xc001c194a0, 0x0, 0x1c, 0xc0004965f0, 0xc)
	/home/circleci/project/project/terraform/evaluate.go:960 +0xbe
github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc0009a8bd0, 0x4d, 0xc00005bf20, 0x1c, 0xc0004965f0, 0xc, 0xc000138d60, 0x6, 0x7, 0x35, ...)
	/home/circleci/project/project/terraform/evaluate.go:787 +0x1333
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc002e95cc0, 0xc00097e180, 0x18, 0x18, 0x2bfc588, 0xc000921f80, 0x0, 0x0, 0x0, 0x30)
	/home/circleci/project/project/lang/eval.go:360 +0x206d
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
	/home/circleci/project/project/lang/eval.go:238
github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc002e95cc0, 0x2c2d298, 0xc001a54000, 0xc001670720, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:51 +0xf3
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc000b6fd40, 0x2c2d538, 0xc001a54000, 0xc001670720, 0x2bfc588, 0xc000921f80, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:273 +0x1ad
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).evalProvisionerConfig(0xc0002d7880, 0x2c64590, 0xc000b6fd40, 0x2c2d538, 0xc0009af970, 0x2c2e808, 0xc001a63f20, 0x23f4a00, 0xc001932090, 0xc001670720, ...)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:1779 +0x2bd
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).applyProvisioners(0xc0002d7880, 0x2c64590, 0xc000b6fd40, 0xc00013ed20, 0x1, 0xc001656230, 0x1, 0x1, 0x0, 0x0)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:1646 +0x373
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).evalApplyProvisioners(0xc0002d7880, 0x2c64590, 0xc000b6fd40, 0xc00013ed20, 0x1, 0x1, 0x0, 0xd, 0x0)
	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:1575 +0x225
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc0011103c0, 0x2c64590, 0xc000b6fd40, 0x0, 0x0, 0xc001f1ac10)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:289 +0x1105
github.com/hashicorp/terraform/terraform.(*NodeApplyableResourceInstance).Execute(0xc0011103c0, 0x2c64590, 0xc000b6fd40, 0xc0000b2001, 0xc001f1ad18, 0x40bb05, 0x243e3e0)
	/home/circleci/project/project/terraform/node_resource_apply_instance.go:129 +0xbc
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000960000, 0x2c64590, 0xc000b6fd40, 0x7f817f15f910, 0xc0011103c0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbf
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x278a1c0, 0xc0011103c0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0xba2
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00041faa0, 0x278a1c0, 0xc0011103c0, 0xc000f0c640)
	/home/circleci/project/project/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:304 +0x1246
```

**Closed** 2021-04-19 15:23 UTC
Labels: bug, new, waiting for reproduction

**Comment by rtfpessoa** [comment] 2021-04-19 15:27
@jbardin is there some sort of workaround?

**Comment by jbardin** [comment] 2021-04-19 18:05
@rtfpessoa, if you can work out which specific value is causing the problem, you could unmark it with [`nonsensitive`](https://www.terraform.io/docs/language/functions/nonsensitive.html).
