### ISSUE TITLE
Bug in aws_route_table when using network_interface_id/instance_id

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#4311] opened 2015-12-14 16:43 UTC
When setting a `route` entry in the `aws_route_table` resource, you are limited to using one of a variety of options, including `network_interface_id` or `instance_id`.

This works, however, when using one of these options, the state file stores values for both of them (it must resolve one from the other). and subsequent `terraform plans` show changes to be made.

**Comment by dbatwa** [comment] 2015-12-24 05:36
This is particularly problematic when using NAT instances.

**Comment by tkellen** [comment] 2016-01-19 16:58
I'm seeing this as well, in terraform 0.6.9. Would ya'll like a repo with a reproduction of this?

**Comment by jen20** [comment] 2016-01-19 16:59
Hi @tkellen! Yes please, if you have a config which reproduces this it would be great if you could post it!

**Comment by tkellen** [comment] 2016-01-19 17:00
Moment. I'll whip one up! You can see it during runs of http://github.com/tkellen/infrastructure but that's like the furthest thing from an isolated test case.

**Comment by tkellen** [comment] 2016-01-19 17:08
Here ya go!

```
variable "aws_access_key" { }
variable "aws_secret_key" { }

provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region = "us-east-1"
}

resource "aws_vpc" "test" {
  cidr_block = "10.10.0.0/16"
}

resource "aws_route_table" "test" {
  vpc_id = "${aws_vpc.test.id}"
}

resource "aws_subnet" "test" {
  vpc_id = "${aws_vpc.test.id}"
  cidr_block = "10.10.10.0/24"
  availability_zone = "us-east-1a"
}

resource "aws_route" "test" {
  route_table_id = "${aws_route_table.test.id}"
  destination_cidr_block = "0.0.0.0/0"
  instance_id = "${aws_instance.nat.id}"
}

resource "aws_instance" "nat" {
  ami = "ami-184dc970"
  instance_type = "t2.nano"
  subnet_id = "${aws_subnet.test.id}"
}
```

Thanks for all the great work ya'll!

**Comment by jen20** [comment] 2016-01-19 17:32
Thanks @tkellen - that clearly demonstrates the issue. We'll get working on a fix for this.

**Comment by tkellen** [comment] 2016-01-19 17:39
Sweet! If I had more time I'd attempt a patch to fix this myself--seems like a good first PR. Looking forward to seeing what the resolution looks like.

**Comment by conorgil** [comment] 2016-01-25 19:12
Just came to file the same issue. Glad to see it is on the radar. The output always shown in my `terraform plan` calls look like this:

```
~ module.vpc.aws_route.ngw.0
    gateway_id:     "" => "nat-123"
    nat_gateway_id: "nat-123" => ""
```

**Comment by BSick7** [comment] 2016-02-25 14:00
Sorry guys. I created `aws_route` and made a mistake.
I submitted a PR to fix.

**Comment by tkellen** [comment] 2016-02-26 10:05
No need to be sorry @BSick7--thank you for the addition of this functionality, and for the fix!

**Comment by diroussel** [comment] 2016-02-26 11:59
FYI, the PR is https://github.com/hashicorp/terraform/pull/5321

**Comment by stack72** [comment] 2016-03-09 22:28
This has been closed in #5321 :) Thanks for the report @tkellen and thanks for the awesome work @BSick7

**Closed by stack72** 2016-03-09 22:28 UTC
Labels: bug, provider/aws

**Comment by madAndroid** [comment] 2016-03-18 08:46
Awesome :) been waiting on this one for some time now .. thanks!!

**Comment by gozer** [comment] 2016-03-18 13:42
Turns out this is also affecting aws_route's route {} blocks in the same way:
```
variable "aws_access_key" { }
variable "aws_secret_key" { }

provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region = "us-east-1"
}

resource "aws_vpc" "test" {
  cidr_block = "10.10.0.0/16"
}

resource "aws_network_interface" "nat" {
  subnet_id = "${aws_subnet.test.id}"
  source_dest_check = false
  attachment {
      instance = "${aws_instance.nat.id}"
     device_index = 1
    }
}

resource "aws_route_table" "test" {
  vpc_id = "${aws_vpc.test.id}"

  route {
    cidr_block = "0.0.0.0/0"
    network_interface_id = "${aws_network_interface.nat.id}"
  }
}

resource "aws_subnet" "test" {
  vpc_id = "${aws_vpc.test.id}"
  cidr_block = "10.10.10.0/24"
  availability_zone = "us-east-1a"
}

resource "aws_instance" "nat" {
  ami = "ami-184dc970"
  instance_type = "t2.nano"
  subnet_id = "${aws_subnet.test.id}"
}
```

**Comment by stack72** [comment] 2016-03-18 20:35
Hi @gozer,

I am going to link your comment here to the latest open issue for this continual recreation issue:

https://github.com/hashicorp/terraform/issues/4097

Paul
