### ISSUE TITLE
Cyclic dependency error when both the parent and the child module have `moved` block.

### ISSUE THREAD

**Issue by nozaq** [hashicorp/terraform#30208] opened 2021-12-18 01:01 UTC
### Terraform Version

```
Terraform v1.1.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

**./main.tf**

```terraform
module "foo" {
  count  = 1
  source = "./modules/foo"
}

moved {
  from = module.foo
  to   = module.foo[0]
}
```

**./modules/foo/main.tf**

```terraform
resource "null_resource" "this" {
  count = 1
}

moved {
  from = null_resource.this
  to   = null_resource.this[0]
}
```

### Debug Output

[full debug output](https://gist.github.com/nozaq/53fca48ef8d4e57009d5ee9fb72ca16e)

### Expected Behavior

`module.foo.null_resource.this` will be moved to `module.foo[0].null_resource.this[0]`.

### Actual Behavior

When running `terraform plan`, the following error is returned.

```
│ Error: Cyclic dependency in move statements
│
│ The following chained move statements form a cycle, and so there is no final
│ location to move objects to:
│   - main.tf:6,1: module.foo → module.foo[0]
│   - modules/foo/main.tf:5,1: module.foo[*].null_resource.this → module.foo[*].null_resource.this[0]
│   - modules/foo/main.tf:5,1: module.foo[*].null_resource.this → module.foo[*].null_resource.this[0]
│
│ A chain of move statements must end with an address that doesn't appear in
│ any other statements, and which typically also refers to an object still
│ declared in the configuration.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

Not sure if `moved` is supposed to be used simultaneously in multiple levels of module hierarchy though, I guess it's quite possible to both the module owner and the module user separately use `moved` block like this example.

**Comment by apparentlymart** [comment] 2021-12-18 01:15
Hi @nozaq! Thanks for reporting this.

What you've described here does seem like a bug, and I agree that I would've expected the outcome you described when given this input.

The other curious thing here is that a close read of the three dependency edges the error message listed out shows that:
* There doesn't _actually_ appear to be a cycle here: I don't see any edge that leads to any node that was previously mentioned.
* There ought to only be two edges here anyway, because you only have two `moved` blocks, and furthermore the third edge seems to be a duplicate of the second.

I've not yet dug into the details on this, but I have a suspicion that the above two points are related, and that it seems like the _root cause_ here is that for some reason the graph of moves has two entries for your second `moved` block. That may in turn be confusing the algorithm that detects cycles, which is really [Tarjan's strongly connected components algorithm](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm) internally.

I think a good next step for us here would be to write a test case which artificially constructs a move graph similar to the one here, which has a duplicate edge, and see if _removing_ that duplicate edge makes the cycle error go away. If so, we can then try to understand _why_ there are two "copies" of that same edge, and eliminate the duplicate. If it doesn't, then that'll prompt us to seek other theories about why this seemingly non-cyclic graph is being classified as having a cycle in it.

**Comment by nozaq** [comment] 2021-12-18 08:32
@apparentlymart Thanks for confirming the issue!

I quickly looked inside the code, and noticed two potential issues.

## duplicated entries

As you pointed out, the error message contains the following three moved entries, whereas we only have two `moved` block defined.

1. main.tf:6,1: module.foo → module.foo[0]
1. modules/foo/main.tf:5,1: module.foo[*].null_resource.this → module.foo[*].null_resource.this[0]
1. modules/foo/main.tf:5,1: module.foo[*].null_resource.this → module.foo[*].null_resource.this[0]

In [prePlanFindAndApplyMoves()](https://github.com/hashicorp/terraform/blob/main/internal/terraform/context_plan.go#L310), first two entries(1&2) are stored in `explicitMoveStmts` and the third one(3) is stored in `implicitMoveStmts`. `explicitMoveStmts` seems fine given we actually defined two `moved` blocks, but `implicitMoveStmts` should be empty here.

Looking into [impliedMoveStatements()](https://github.com/hashicorp/terraform/blob/main/internal/refactoring/move_statement.go#L87), the third entry was produced [in this line](https://github.com/hashicorp/terraform/blob/main/internal/refactoring/move_statement.go#L152).
It seems strange to call `findMoveStatements` here, I guess this part should instead be `impliedMoveStatements` for recursively searching implicit moves within child cfgs.

After making this change(https://github.com/nozaq/terraform/pull/1/commits/b0102707a5468b01135d60183713b70c166abf40), the error message now contains exactly two entries.

```
│ Error: Cyclic dependency in move statements
│
│ The following chained move statements form a cycle, and so there is no final location to move objects to:
│   - main.tf:6,1: module.foo → module.foo[0]
│   - modules/foo/main.tf:5,1: module.foo[*].null_resource.this → module.foo[*].null_resource.this[0]
│
│ A chain of move statements must end with an address that doesn't appear in any other statements, and which typically also refers to an object
│ still declared in the configuration.
```

## cyclic dependency

Even after eliminating a duplicated entry, cyclic dependency error was still reported as above.

An output from [buildMoveStatementGraph()](https://github.com/hashicorp/terraform/blob/main/internal/refactoring/move_execute.go#L190) contains two nodes and two edges as follows. This graph does contain a cycle between A and B. 

- Node A: `module.foo → module.foo[0]`
- Node B: `module.foo[*].null_resource.this → module.foo[*].null_resource.this[0]`
- Edge 1: A -> B
- Edge 2: B -> A

[statementDependsOn()](https://github.com/hashicorp/terraform/blob/main/internal/refactoring/move_execute.go#L220) returns `true` for both `statementDependsOn(A, B)` and `statementDependsOn(B, A)` when one node is completely nested in another, so causing a cyclic dependency error. I'm guessing we don't need any edges in this case since those two statements can be executed independently.

After adding an extra condition to handle such case(https://github.com/nozaq/terraform/commit/6e81c55c91f3fc372e38490f2775f8030b361c0d), I got the expected output. 

```
Terraform will perform the following actions:

  # module.foo.null_resource.this has moved to module.foo[0].null_resource.this[0]
    resource "null_resource" "this" {
        id = "7985448508287695297"
    }

Plan: 0 to add, 0 to change, 0 to destroy.
```

I put these two changes together in https://github.com/nozaq/terraform/pull/1 for an early review. If it looks the legitimate way to fix this issue, I can prepare unit test cases for this issue and submit a PR. Please let me know if you have any comments, thanks!

**Comment by jbardin** [comment] 2021-12-20 15:37
Thanks for looking at this @nozaq! You were on the right track here, but there's a crucial piece of logic missing. I guess at some point convinced myself that `CanChainFrom` and `NestedWithin` was sufficient for our use case, but that would only be true if all moves were dome from the perspective of a single module, and obviously we allow independent moves from unrelated modules even when nested. While the proposed change fixes the above example, it would miss certain errors we want to catch from combinations of moves where they actually originate outside of the nested module, even though the individual targets are "nested". 

I think we are going to need a third type of comparison here, something like `Contains`, for when the _relative_ source of the `from` and `to` statements is completely contained within an outer module's move statement.

**Comment by jbardin** [comment] 2021-12-21 14:44
Upon review, it appears that the original premise of the `NestedWithin` check still holds true here. While we may logically think of move statements within a module being completely independent of their parent modules, the actual move operations still need to be coordinated within a shared state. The resources to be moved are only going to be found at one address within the state, and what that address may depend on any move operations done by a higher level module.

The cycle shown is because of a particular edge case in our addressing scheme, only presenting itself in the when the index of a module is changed. The problem here is that `module.foo[*].null_resource.this` appears in _both_ the `from` and `to` addresses of the parent's move statements, essentially because `module.foo[*]` matches both `module.foo` and `module.foo[0]`. If you change the example to alter the name of the module instead of the count, the cycle no longer appears.

While we could try and walk through the pairs of move statement address segments to find a module re-index at a higher level which nests the move in question, I think a general solution is a bit easier and the logic looks similar to your attempt above. We can detect the "backwards" edge with condition of `b.From.NestedWithin(a.From) && b.To.NestedWithin(a.From)`, and verify that the module name is not actually changing by confirming that `b.From.NestedWithin(a.To) && To.NestedWithin(a.To)` (and we can skip that last comparison in practice since the first condition already determined b is contained by the move statement).

**Comment by jbardin** [comment] 2021-12-21 15:12
Oops, I may have spoken too soon about a general solution, putting this logic into code shows the problem that we cannot detect the _direction_ we want to eliminate here using `NestedWithin` alone, so we end up with the same type of problem as the first proposal. I guess it is going to come down to a check for the case of an index change, so there is a new comparison type we need, but very specific to `from` and `to` having the same module name.

**Comment by apparentlymart** [comment] 2021-12-21 19:42
One meta-thing I notice here is that we aren't currently including information in the trace log about exactly how the graph is shaped, and so when debugging this we can only see the _input_ to the graph construction (the set of moved statements included in the error message), and not the _result_ of graph construction which would show the cycles.

That's a thing that threw me when I was first looking at this, since I don't yet have muscle memory for debugging problems in this particular subsystem and therefore made some faulty assumptions "guessing" what the resulting graph ought to have looked like.

Of course addressing the problem is the more important thing here, but while we're there I think it could be helpful to make the error branch that leads to this error message also write a string representation of the real graph `g` (which is what we detected the cycles in) so it's easier to spot which extra or missing edges are there in the same way as we typically do for the dependency graphs we use in other contexts. :crossed_fingers:

**Closed** 2021-12-22 21:27 UTC
Labels: bug, config, v1.1
