### ISSUE TITLE
Openstack port range on refresh - expected type 'int', got unconvertible type 'string'

### ISSUE THREAD

**Issue by mattbarrio** [hashicorp/terraform#7406] opened 2016-06-29 07:19 UTC
Running `terraform apply` works fine and the resource is created. When I run `terraform refresh` or `terraform destroy` it exits with an error.
### Terraform Version

Terraform v0.7.0-rc2
### Affected Resource(s)

Please list the resources as a list, for example:
- resource_openstack_networking_secgroup_rule_v2
### Terraform Configuration Files

```
resource "openstack_networking_secgroup_v2" "test_secgroup" {
  name = "test_secgroup"
  description = "security group"
}
resource "openstack_networking_secgroup_rule_v2" "rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  security_group_id = "${openstack_networking_secgroup_v2.test_secgroup.id}"
}
```
### Expected Behavior

running `terraform refresh` should refresh without issue but halts on error 
### Actual Behavior

```Error refreshing state: 1 error(s) occurred:
- openstack_networking_secgroup_v2.secgroup: OpenStack Neutron Security group: 6 error(s) decoding:
- 'security_group.security_group_rules[2].port_range_max' expected type 'int', got unconvertible type 'string'
- 'security_group.security_group_rules[2].port_range_min' expected type 'int', got unconvertible type 'string'```
### Steps to Reproduce
1. `terraform apply`
2. `terraform refresh`
### Important Factoids
### References

**Comment by jtopjian** [comment] 2016-07-02 18:06
@mattbarrio Thank you for reporting this. I've just had a chance to look it over and I can't reproduce the error.

Can you provide any details about your Neutron configuration? For example: what L2 driver are you using (OVS, linuxbridge, etc), is the driver using a non-iptables-based security group plugin/driver?

**Comment by jtopjian** [comment] 2016-10-30 19:49
@mattbarrio I wanted to touch base on this one again. From reviewing the error message you gave, is there more to the sample Terraform configuration required to trigger this issue?

**Comment by mitchellh** [comment] 2016-12-01 14:42
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!

**Closed by mitchellh** 2016-12-01 14:42 UTC
Labels: bug, provider/openstack, waiting-response
