### ISSUE TITLE
create_before_destroy fails with error "port is still in use."

### ISSUE THREAD

**Issue by PetrusHahol** [hashicorp/terraform#21503] opened 2019-05-29 08:52 UTC
Hey. 
I faced a problem with create before destroy with openstack_compute_instance_v2 resource. It happens after tainting. 

* openstack_compute_instance_v2.{object_name}.2: Error creating OpenStack server: Expected HTTP response code [] when accessing [POST https://nova.{host}:8774/v2/a73abaf8717448e69dde2bf789ce2139/servers], but got 409 instead
{"conflictingRequest": {"message": "Port 5ce2378d-d3af-4085-9757-7bc263617a32 is still in use.", "code": 409}}

It seems terraform tries to create new virtual machine with the port which is already connected to the machine which is not deleted yet.

**Comment by apparentlymart** [comment] 2019-05-29 17:15
Hi @PetrusHahol,

`create_before_destroy` is opt-in rather than default because for a number of resource types (including this one) it isn't possible to have two of the object in existence at the same time due to conflicts of unique names, unique port numbers, etc.

I don't know openstack well enough to offer direct advice here, but the general challenge here is to design your system so that multiple generations of the same resource instance can exist at once. That mugh

**Comment by apparentlymart** [comment] 2019-05-29 17:15
Hi @PetrusHahol,

`create_before_destroy` is opt-in rather than default because for a number of resource types (including this one) it isn't possible to have two of the object in existence at the same time due to conflicts of unique names, unique port numbers, etc.

I don't know openstack well enough to offer direct advice here, but the general challenge here is to design your system so that multiple generations of the same resource instance can exist at once. That mugh

**Comment by apparentlymart** [comment] 2019-07-11 23:31
Hi @PetrusHahol,

On revisiting this issue, it seems like there isn't any specific work item associated with it (Terraform is working as intended) and so I'm going to close it out. It may be possible for the `openstack` provider to provide some features to make `create_before_destroy` more convenient to use with this resource type, but that would be a change in that provider and so you may wish to open an issue about that in [the provider's own repository](https://github.com/terraform-providers/terraform-provider-openstack).

**Closed by apparentlymart** 2019-07-11 23:31 UTC
