### ISSUE TITLE
aws_route crash on create: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MikeSchuette** [hashicorp/terraform#5092] opened 2016-02-10 22:19 UTC
[tf-crash.txt](https://github.com/hashicorp/terraform/files/125603/tf-crash.txt)

**Comment by apparentlymart** [comment] 2016-02-10 22:29
This seems to be the most interesting part of the crash log:

```
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x1a1723]
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: goroutine 425 [running]:
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.routeIDHash(0xc8204da120, 0x0, 0x0, 0x0)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160205-18753-13bx7e7/terraform-0.6.11/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:303 +0xa3
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteCreate(0xc8204da120, 0x96c760, 0xc8203ae3c0, 0x0, 0x0)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160205-18753-13bx7e7/terraform-0.6.11/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:161 +0x9bd
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc82079b080, 0xc8204a8060, 0xc8209440a0, 0x96c760, 0xc8203ae3c0, 0x10101, 0x0, 0x0)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160205-18753-13bx7e7/terraform-0.6.11/src/github.com/hashicorp/terraform/helper/schema/resource.go:145 +0x28e
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc820574930, 0xc8207bc000, 0xc8204a8060, 0xc8209440a0, 0x201, 0x0, 0x0)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160205-18753-13bx7e7/terraform-0.6.11/src/github.com/hashicorp/terraform/helper/schema/provider.go:162 +0x1ed
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Apply(0xc820469ea0, 0xc82096e0a0, 0xc8209442c0, 0x0, 0x0)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160205-18753-13bx7e7/terraform-0.6.11/src/github.com/hashicorp/terraform/rpc/resource_provider.go:323 +0x76
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: reflect.Value.call(0xb81b80, 0xe0fd20, 0x13, 0xead010, 0x4, 0xc8208e5ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/usr/local/Cellar/go/1.5.3/libexec/src/reflect/value.go:432 +0x120a
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: reflect.Value.Call(0xb81b80, 0xe0fd20, 0x13, 0xc8208e5ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/usr/local/Cellar/go/1.5.3/libexec/src/reflect/value.go:300 +0xb1
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc82079b980, 0xc82079b940, 0xc8200fa2e0, 0xc820580680, 0xc8203fc7c0, 0x96da20, 0xc82096e0a0, 0x16, 0x96da80, 0xc8209442c0, ...)
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/usr/local/Cellar/go/1.5.3/libexec/src/net/rpc/server.go:383 +0x1c1
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/02/09 11:04:55 [DEBUG] terraform-provider-aws: 	/usr/local/Cellar/go/1.5.3/libexec/src/net/rpc/server.go:477 +0x4ac
```

**Comment by MikeSchuette** [comment] 2016-02-10 22:31
Apologies I don't have a test case.  A subsequent `apply` succeeded.

**Comment by catsby** [comment] 2016-02-17 22:44
Hey all – I think this will be caught in #5155, so I'm going to close this. Please let me know if you're still hitting this or have another reproduction case.

Thanks!

**Closed by catsby** 2016-02-17 22:44 UTC
Labels: bug, crash, provider/aws
