### ISSUE TITLE
panic: Unknown: <invalid reflect.Value> when refreshing aws_organizations_account.account state during plan

### ISSUE THREAD

**Issue by nomadicj** [hashicorp/terraform#21763] opened 2019-06-18 00:31 UTC
Hey, his this plan issue that suddenly brought our development to a halt. It appears to be when evaluating the `aws_organizations_account.account` resource. After that we get a handy `panic: Unknown: <invalid reflect.Value>` error and a stack trace (below).

### Terraform Version

```
0.11.13
```

### Terraform Configuration Files

```hcl
resource "aws_organizations_account" "account" {
  name  = "${var.account-name}"
  email = "${var.email}"
}
```

```hcl
module "base" {
  source       = "../../../modules/base"
  account-name = "${var.account-name}"
  email        = "${var.account-email}"

  providers = {
    aws = "aws.master"
  }
}
```

```hcl
provider "aws" {
  region = "eu-west-2"
  alias  = "master"
}
```

### Debug Output
Available upon request

### Crash Output

https://gist.github.com/nomadicj/766390ef04c83ce41928d87370280fb6

### Expected Behavior
I'd like it to let us plan please.

### Actual Behavior
```
Initializing modules...
- module.base
- module.cloudtrail
- module.global
- module.region-eu-west-2
- module.region-eu-west-1
- module.region-eu-west-1.config
- module.region-eu-west-1.guardduty
- module.region-eu-west-1.logging
- module.region-eu-west-1.networking
- module.global.auth
- module.global.cis
- module.global.modules-iam
- module.global.remove-defaults
- module.region-eu-west-2.config
- module.region-eu-west-2.guardduty
- module.region-eu-west-2.logging
- module.region-eu-west-2.networking
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
The following providers do not have any version constraints in configuration,
so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.
* provider.aws: version = "~> 2.11"
* provider.null: version = "~> 2.1"
* provider.template: version = "~> 2.1"
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
data.terraform_remote_state.networking: Refreshing state...
data.template_file.trust-policy-config: Refreshing state...
data.template_file.policy-lambda: Refreshing state...
[... lines removed here ...]
data.template_file.trust-policy-infra-creator: Refreshing state...
data.template_file.policy-config: Refreshing state...
data.template_file.policy-vpc-endpoint-s3: Refreshing state...
data.template_file.policy-vpc-endpoint-s3: Refreshing state...
aws_organizations_account.account: Refreshing state... (ID: 391635538753)
panic: Unknown: <invalid reflect.Value>
goroutine 27549 [running]:
github.com/hashicorp/terraform/builtin/providers/terraform.flatten(0xc0016c7020, 0xc0024b9a70, 0x25, 0x28ac860, 0xc0028820d0, 0x94)
    /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:48 +0x48d
github.com/hashicorp/terraform/builtin/providers/terraform.flattenMap(0xc0016c7020, 0xc000d7cd00, 0x14, 0x28b8200, 0xc0026fee10, 0x15)
    /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:65 +0x440
github.com/hashicorp/terraform/builtin/providers/terraform.flatten(0xc0016c7020, 0xc000d7cd00, 0x14, 0x28ac860, 0xc0027039d0, 0x194)
    /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:42 +0x38b
github.com/hashicorp/terraform/builtin/providers/terraform.flattenSlice(0xc0016c7020, 0xc000d7ccc0, 0x13, 0x2577b80, 0xc0015dd200, 0x97)
    /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:74 +0x313
github.com/hashicorp/terraform/builtin/providers/terraform.flatten(0xc0016c7020, 0xc0014784e0, 0x12, 0x2577b80, 0xc0015dd200, 0x97)
    /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:44 +0x34c
github.com/hashicorp/terraform/builtin/providers/terraform.remoteStateFlatten(0xc0029a1468, 0xc0029a1468)
    /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:21 +0xb4
github.com/hashicorp/terraform/builtin/providers/terraform.dataSourceRemoteStateRead(0xc001f73f10, 0x0, 0x0, 0xc001f73f10, 0x0)
    /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/terraform/data_source_state.go:520 +0xa3e
github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc000511dc0, 0xc000b12180, 0x0, 0x0, 0xc002c507d8, 0xc001557601, 0xc0006f0730)
    /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:290 +0x88
github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc000511e30, 0xc000d67450, 0xc000b12180, 0x0, 0x4c, 0xc002a7c000)
    /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x92
github.com/hashicorp/terraform/terraform.(*EvalReadDataApply).Eval(0xc001573160, 0x33253a0, 0xc002c50820, 0x2, 0x2, 0xc0012422c0, 0x20)
    /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_read_data.go:122 +0xf9
github.com/hashicorp/terraform/terraform.EvalRaw(0x32ff5a0, 0xc001573160, 0x33253a0, 0xc002c50820, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc001573180, 0x33253a0, 0xc002c50820, 0x2, 0x2, 0xc0021930a0, 0x20)
    /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x9c
github.com/hashicorp/terraform/terraform.EvalRaw(0x32ff6a0, 0xc001573180, 0x33253a0, 0xc002c50820, 0x28ab000, 0x54ec045, 0x25ccc40, 0xc000d69ea0)
    /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/hashicorp/terraform/terraform.Eval(0x32ff6a0, 0xc001573180, 0x33253a0, 0xc002c50820, 0xc001573180, 0x32ff6a0, 0xc001573180, 0x0)
    /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2f1e320, 0xc0000979f0, 0x0, 0x0)
    /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xc45
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc001ca5030, 0x2f1e320, 0xc0000979f0, 0xc001031500)
    /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x367
created by github.com/hashicorp/terraform/dag.(*Walker).Update
    /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x986
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce
`terraform plan -lock-timeout=7m -out <planfile>`

### Additional Context
We are running everything in docker containers using make to initiate them, but no change was being made to that setup. This started while we were doing a reasonable major refactor but nothing was being done with the `aws_organizations_account` resource. It happened a few times over the course of a few hours but was transient. Now it's a hard blocker and nothing can be run... Any assistance would be appreciated.

**Comment by danieldreier** [comment] 2020-06-11 21:13
@nomadicj I want to apologize for how long this has taken to respond to. I appreciate you reporting a crash, and I'm particularly cognizant that you described it as a hard blocker and didn't get a response at all. We have been working through our crash backlog, and are determined to respond to crashes faster in the future.

If you're still running into this crash in 0.12.26 and the 0.13.0 beta, I would like to work up a reproduction case together. I've tried to reproduce it from the code you gave, and cannot, because it references a module whose code I don't have. Without that module, I haven't been able to reproduce the crash.

**Comment by apparentlymart** [comment] 2020-07-14 19:35
Hi @nomadicj,

We didn't hear from you again after @danieldreier's question, and I've reviewed the crash output here and determined that it relates to some code that was rewritten as part of Terraform 0.12's introduction of a new state snapshot serialization format.

Specifically, this crash seems to have occurred when the `terraform_remote_state` data source was attempting to translate data from a stored state snapshot into a suitable format for returning from the data source, which in Terraform 0.11 was constrained to a small number of data types. The new state snapshot format no longer requires this "flattening" transformation (that was one of the goals of the new format), and so the operation that caused this problem is no longer present in Terraform 0.12 and later.

Terraform 0.11 is no longer under development, so unfortunate any bugs remaining in that release will not be addressed. For that reason, I'm going to close this issue. I want to echo @danieldreier's regret at our slow response to this issue, and I hope you were able to find a workaround on your end.

**Closed by apparentlymart** 2020-07-14 19:35 UTC
Labels: bug, crash, v0.11, waiting-response
