### ISSUE TITLE
On Windows 10, terrarform.d/plugins directory is not searched during init

### ISSUE THREAD

**Issue by dprosper** [hashicorp/terraform#23320] opened 2019-11-08 13:37 UTC
### Terraform Version

```
$ terraform -v
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.12.13. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files

```hcl
Not applicable
```

### Debug Output

```
$ TF_LOG=trace terraform init
2019/11/08 08:23:32 [INFO] Terraform version: 0.11.14
2019/11/08 08:23:32 [INFO] Go runtime version: go1.12.4
2019/11/08 08:23:32 [INFO] CLI args: []string{"C:\\Program Files\\Terraform\\terraform.exe", "init"}
2019/11/08 08:23:32 [DEBUG] Attempting to open CLI config file: C:\Users\DProsper\AppData\Roaming\terraform.rc
2019/11/08 08:23:32 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/11/08 08:23:32 [INFO] CLI command args: []string{"init"}
2019/11/08 08:23:32 [DEBUG] command: loading backend config file: C:\dev\tf
Initializing modules...
- module.vpc_admin
  Getting source "./tf_modules/vpc_admin"
2019/11/08 08:23:32 [TRACE] module source: "./tf_modules/vpc_admin"
2019/11/08 08:23:32 [TRACE] detected module source "file://C:/dev/tf/tf_modules/vpc_admin"
2019/11/08 08:23:32 [DEBUG] fetching module from file://C:/dev/tf/tf_modules/vpc_admin
2019/11/08 08:23:32 [DEBUG] fetching "file://C:/dev/tf/tf_modules/vpc_admin" with key "1.vpc_admin;./tf_modules/vpc_admin"
2019/11/08 08:23:32 [DEBUG] found "file://C:/dev/tf/tf_modules/vpc_admin" in ".terraform\\modules\\88616ec51e6a0a8cab987289fbca58de": true
2019/11/08 08:23:32 [TRACE] "file://C:/dev/tf/tf_modules/vpc_admin" stored in ".terraform\\modules\\88616ec51e6a0a8cab987289fbca58de"
2019/11/08 08:23:32 [INFO] command: empty backend config, returning nil
2019/11/08 08:23:32 [DEBUG] command: no data state file found for backend config
2019/11/08 08:23:32 [DEBUG] New state was assigned lineage "d24ee277-2e95-005d-8587-b5587ecf762a"
2019/11/08 08:23:32 [INFO] command: backend initialized: <nil>
2019/11/08 08:23:32 [DEBUG] checking for provider in "."
2019/11/08 08:23:32 [DEBUG] checking for provider in "C:\\Program Files\\Terraform"
2019/11/08 08:23:32 [DEBUG] checking for provisioner in "."
2019/11/08 08:23:32 [DEBUG] checking for provisioner in "C:\\Program Files\\Terraform"
2019/11/08 08:23:32 [INFO] Failed to read plugin lock file .terraform\plugins\windows_amd64\lock.json: open .terraform\plugins\windows_amd64\lock.json: The system cannot find the path specified.
2019/11/08 08:23:32 [INFO] command: backend <nil> is not enhanced, wrapping in local
2019/11/08 08:23:32 [TRACE] module source: "./tf_modules/vpc_admin"
2019/11/08 08:23:32 [DEBUG] checking for provider in "."
2019/11/08 08:23:32 [DEBUG] checking for provider in "C:\\Program Files\\Terraform"

2019/11/08 08:23:32 [DEBUG] plugin requirements: "local"="~> 1.3"
2019/11/08 08:23:32 [DEBUG] plugin requirements: "external"="~> 1.2"
2019/11/08 08:23:32 [DEBUG] plugin requirements: "null"="~> 2.1"
2019/11/08 08:23:32 [DEBUG] plugin requirements: "template"="~> 2.1"


```
### Expected Behavior

According to the documentation [here](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations), plugins on Windows should be installed under the `%APPDATA%\terraform.d\plugins` directory structure, placing the plugin in that directory or `%APPDATA%\terraform.d\plugins\windows-amd64\` it should get picked up when running `terraform init`. 

### Actual Behavior

 It only works when the plugin is located in the same directory as the terraform.exe executable. Looking at the trace output above you can see that the `%APPDATA%` is searched for the `terraform.rc`, but it is never searched for the provider in the `%APPDATA%\terraform.d\plugins` or `%APPDATA%\terraform.d\plugins\windows-amd64` directories. 

### Steps to Reproduce

1. On Windows 10, place a plugin under the ``APPDATA%\terraform.d\plugins` directory as descried in the documentation
2. terraform init

### Additional Context

Running on Windows 10 with Git for Windows installed. Performing these steps in a Git Bash Shell.

**Comment by alisdair** [comment] 2020-02-10 19:16
I'm unable to reproduce this bug. Using Terraform v0.11.14, Windows 10.0.18363, git for Windows 2.25.0, running in git bash:

<details>
<summary><code>terraform init</code> log</summary>
<pre><code>
2020/02/10 11:31:43 [INFO] Terraform version: 0.11.14  
2020/02/10 11:31:43 [INFO] Go runtime version: go1.12.4
2020/02/10 11:31:43 [INFO] CLI args: []string{"C:\\Program Files\\Terraform\\terraform.exe", "init"}
2020/02/10 11:31:43 [DEBUG] Attempting to open CLI config file: C:\Users\alisd\AppData\Roaming\terraform.rc
2020/02/10 11:31:43 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/02/10 11:31:43 [INFO] CLI command args: []string{"init"}
2020/02/10 11:31:43 [DEBUG] command: loading backend config file: C:\Users\alisd\tf-example
2020/02/10 11:31:43 [INFO] command: empty terraform config, returning nil
2020/02/10 11:31:43 [DEBUG] command: no data state file found for backend config
2020/02/10 11:31:43 [DEBUG] New state was assigned lineage "ba9ad26a-10dd-4b1b-706d-80af33d69609"
2020/02/10 11:31:43 [INFO] command: backend initialized: <nil>
2020/02/10 11:31:43 [DEBUG] checking for provider in "."
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Program Files\\Terraform"
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins"
2020/02/10 11:31:43 [WARN] found legacy provider "terraform-provider-example"
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins\\windows_amd64"
2020/02/10 11:31:43 [DEBUG] found valid plugin: "example", "0.0.0", "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins\\terraform-provider-example"
2020/02/10 11:31:43 [DEBUG] checking for provisioner in "."
2020/02/10 11:31:43 [DEBUG] checking for provisioner in "C:\\Program Files\\Terraform"
2020/02/10 11:31:43 [DEBUG] checking for provisioner in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins"
2020/02/10 11:31:43 [DEBUG] checking for provisioner in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins\\windows_amd64"
2020/02/10 11:31:43 [INFO] Failed to read plugin lock file .terraform\plugins\windows_amd64\lock.json: open .terraform\plugins\windows_amd64\lock.json: The system cannot find the path specified.
2020/02/10 11:31:43 [INFO] command: backend <nil> is not enhanced, wrapping in local
2020/02/10 11:31:43 [DEBUG] checking for provider in "."
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Program Files\\Terraform"
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins"
2020/02/10 11:31:43 [WARN] found legacy provider "terraform-provider-example"
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins\\windows_amd64"
2020/02/10 11:31:43 [DEBUG] found valid plugin: "example", "0.0.0", "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins\\terraform-provider-example"
2020/02/10 11:31:43 [DEBUG] plugin requirements: "example"=""
2020/02/10 11:31:43 [DEBUG] checking for provider in "."
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Program Files\\Terraform"
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins"
2020/02/10 11:31:43 [WARN] found legacy provider "terraform-provider-example"
2020/02/10 11:31:43 [DEBUG] checking for provider in "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins\\windows_amd64"
2020/02/10 11:31:43 [DEBUG] found valid plugin: "example", "0.0.0", "C:\\Users\\alisd\\AppData\\Roaming\\terraform.d\\plugins\\terraform-provider-example"
2020/02/10 11:31:43 [DEBUG] checking for provider in ".terraform\\plugins\\windows_amd64"
2020/02/10 11:31:43 [DEBUG] plugin: waiting for all plugin processes to complete...
</code></pre>
</details>

The only explanation I can imagine from your logs is that there was no accessible folder `$APPDATA\terraform.d\plugins` when `terraform init` was run—otherwise it should have been at least logged as a search path.

If this is still happening for you, could you reply with the result of running the following commands in git bash?

- `whoami`
- `echo $APPDATA`
- `ls -ld $APPDATA $APPDATA/terraform.d $APPDATA/terraform.d/plugins`

Since I can't reproduce this issue, I'm going to close it. If you see the same problem after upgrading to 0.12, please open a new issue.

**Closed by alisdair** 2020-02-10 19:16 UTC
Labels: bug, cli, v0.11, windows
