### ISSUE TITLE
crtl-c shows "graceful" shutdown message, then long pause, then terraform still destroys resources

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/terraform#30918] opened 2022-04-22 19:52 UTC
### Terraform Version
v1.1.7

### Screenshot of destruction:
![josh_ip-10-20-11-55__](https://user-images.githubusercontent.com/39473/164784408-a3edc8dc-509d-4850-9c42-954313851ea6.jpg)

### Expected Behavior
not destroyed resources

### Actual Behavior
resources destroyed.  site down. 💥 

### Steps to Reproduce
Press ctrl-c - see graceful message.  wait.

### Additional Context
As noted in the screenshot there was a long pause after the Graceful shutdown message showed up to when it continued on and destroyed resources. That is, it had plenty of time to think about doing things and still didn't shutdown.

Counterintuitively, I'm pretty sure if I **held** ctrl-c down and sent the process 10s or 100s of kill signals it would've died "ungracefully" and the resource would not have been destroyed.  This would've been a much better scenario.

**Comment by josh-m-sharpe** [comment] 2022-04-25 18:43
I ride the lighting -- so, yes, I did run `apply -auto-approve` in this case.

I'm not 100% sure if it had completed planning when I ctrl-c'd.

It would seem that a ctrl-c any time before the operation/execution phase should prevent that phase from starting.

**Comment by apparentlymart** [comment] 2022-04-28 00:13
I think probably what we'll need to do here is _assume_ my theory above is correct for the moment, and find some way to modify the code to simulate that situation by artifically triggering the cancellation sequence as _just the wrong moment_ (after planning has completed all of the network operations but the apply walk hasn't yet started) and see if that causes the cancellation to be ignored.

If it does, that would confirm that my hunch is valid and we can work on figuring out why the cancellation state doesn't survive between the plan phase and the apply phase. (My initial guess: we're creating a new context for each walk and so the fact that the context for the plan walk was cancelled doesn't affect the freshly-created context for the apply walk. But I've not checked that.)

**Comment by jbardin** [comment] 2022-05-02 17:18
The behavior shown here can be explained by the combination of a couple factors.
The "long pause" is the result of aws the provider is not cancelling the operations which are already in progress. While we usually leave decision of how to cancel up to the providers, I believe we do have an open issue to be more forceful in the cancellation of a plan where the result is going to be discarded anyway.

After the plan in cancelled however we hit the root cause of this bug -- the next step where the context is checked in running apply with no prior plan is during the plan confirmation, so when the confirmation is skipped, so is the check for cancellation.

**Closed** 2022-05-02 21:14 UTC
Labels: bug, confirmed
