### ISSUE TITLE
0.13beta crash when running terraform validate

### ISSUE THREAD

**Issue by kuhlman-labs** [hashicorp/terraform#25221] opened 2020-06-11 23:00 UTC
### Terraform Version

```
Terraform v0.13.0-beta1
+ provider registry.terraform.io/hashicorp/azurerm v2.14.0
```

### Terraform Configuration Files

```hcl
  module "network_isolated" {
  source        = "../../modules/network_isolated"
  environment   = var.environment
  region        = var.region
  address_space = var.address_space
  tags          = var.tags
}

###
#  module composition
###

#resource group

module "resource_group" {
  source       = "../../resources/base/resource_group"
  service_name = "network-isolated"
  region       = var.region
  environment  = var.environment
  tags         = var.tags
}

#vnet

module "virtual_network" {
  source         = "../../resources/network/virtual_network"
  resource_group = module.resource_group.name
  region         = module.resource_group.location
  environment    = var.environment
  name_prefix    = "vnet-isolated"
  address_space  = var.address_space
  tags           = var.tags
}


```

### Crash Output

https://gist.github.com/kuhlman-labs/f03d829e11e21a81877582e3c5098ba0

### Expected Behavior

Successful validation

### Actual Behavior

panic: no expansion has been registered for module.network_isolated

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

**Comment by danieldreier** [comment] 2020-06-11 23:07
@kuhlman-labs thanks for reporting this! If you're getting a panic that sounds like there's a bug we need to look at. This reproduction case doesn't have quite enough detail. I've copied your repro case into https://github.com/danieldreier/terraform-issue-reproductions/blob/master/25221/25221.tf and when I run it, I get messages like:
```
Error: Failed to read module directory

Module directory  does not exist or cannot be read.
```
because the modules you're referencing aren't part of this reproduction case. Without knowing what's in them, I'm not sure how to reproduce this. It would be really helpful if you could make a PR to fill in enough details to reproduce this.

**Comment by kuhlman-labs** [comment] 2020-06-11 23:25
@danieldreier These are nested modules in my repo structure
```bash
├── environments
│   ├── test
│   │   ├── main.tf <---- where modules are composed, terraform validate here
├── modules
│   ├── vnet_isolated
│   │   ├── main.tf <---- modules are composed with resources
├── resources
│   ├── network
│   │   ├── main.tf 
```

```hcl

###
#  environment composition
###

  module "network_isolated" {
  source        = "../../modules/network_isolated"
  environment   = var.environment
  region        = var.region
  address_space = var.address_space
  tags          = var.tags
}

###
#  module composition
###

#resource group

module "resource_group" {
  source       = "../../resources/base/resource_group"
  service_name = "network-isolated"
  region       = var.region
  environment  = var.environment
  tags         = var.tags
}

#vnet

module "virtual_network" {
  source         = "../../resources/network/virtual_network"
  resource_group = module.resource_group.name
  region         = module.resource_group.location
  environment    = var.environment
  name_prefix    = "vnet-isolated"
  address_space  = var.address_space
  tags           = var.tags
}

###
#  resource composition
###

resource "azurerm_virtual_network" "base" {
  name                = "${var.name_prefix}-${var.environment}-${var.region}"
  resource_group_name = var.resource_group
  address_space       = var.address_space
  location            = var.region
  dns_servers         = var.dns_servers

  tags = var.tags

}

resource "azurerm_resource_group" "base" {
  name     = "${var.name_prefix}-${var.service_name}-${var.environment}-${var.region}"
  location = var.region
  tags     = var.tags
}
```

**Comment by jbardin** [comment] 2020-06-12 14:07
Thanks for the config @kuhlman-labs, the panic here is `panic: no expansion has been registered for module.network_isolated`, and this looks to be a duplicate of #25114.

Feel free to update this issue here after the next beta release if it's not fixed.

Thanks!

**Closed by jbardin** 2020-06-12 14:07 UTC
Labels: crash, v0.13
