### ISSUE TITLE
Sensitive values from tfe_outputs.remote_state are null with Terraform Cloud

### ISSUE THREAD

**Issue by spanktar** [hashicorp/terraform#31234] opened 2022-06-13 18:00 UTC
### Terraform Version

```
1.1.9
```

### Description

I cannot seem to get a sensitive value passed through remote state (`tfe_outputs`) in Terraform cloud to a separate workspace that needs to consume it. The value always ends up as `null`.

### Terraform Configuration Files

```terraform

## Workspace 1
resource "random_password" "admin_password" {
  length  = 21
}

output "admin_password" {
  value     = random_password.admin_password.result
  sensitive = true
}

## Workspace 2

terraform {
  required_version = "~> 1.1.0"

  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "foo"

    workspaces {
      name = "bar"
    }
  }
}

# Backend Remote State

data "tfe_outputs" "remote_state" {
  organization = "foo"
  workspace    = "foo"
}

output "admin_password" {
   value = data.tfe_outputs.remote_state.values.admin_password
}

```

### Debug Output

When I run `terraform output -json` in Workspace 1, I see the sensitive value (good):
```
  "admin_password": {
    "sensitive": true,
    "type": "string",
    "value": "kwdf4vus7kIS9QW9tcWYe"
  },
```

When I inspect the state file of the consuming Workspace 2, the value is `null`:

```
   {
      "mode": "data",
      "type": "tfe_outputs",
      "name": "remote_state",
      "provider": "provider[\"registry.terraform.io/hashicorp/tfe\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "foo",
            "organization": "foo",
            "values": {
              "value": {
    --->        "admin_password": null
              },
              "type": [
                "object",
                {
    --->          "admin_password": "dynamic"
                }
              ]
            },
            "workspace": "foo"
          },
          "sensitive_attributes": []
        }
      ]
    },
```

### Expected Behavior

The sensitive value should be passed through the remote state.

### Actual Behavior

The value was `null` (and the type was `dynamic`??)

### Steps to Reproduce

Set up two remote states in Terraform cloud with a sensitive output from one, apply.
Examine the state from Workspace 2 (after apply) and note the null value.

The only thing I've found that works right now is to use `nonsensitive()` on the output in Workspace 1, which is not ideal.

**Comment by apparentlymart** [comment] 2022-06-14 14:19
Hi @spanktar! Thanks for reporting this.

I think what you've observed here is a Terraform Cloud API behavior or a `hashicorp/tfe` provider behavior, rather than Terraform Core's behavior. Therefore I suggest reporting this in [the provider's repository](https://github.com/hashicorp/terraform-provider-tfe) so that the team which maintains the provider (which overlaps with teams maintaining the underlying API) can consider it and determine whether this is a bug or an intended behavior.

I don't think there is anything we could change in this repository to get the result you expected, because Terraform Core just takes whatever data the provider returns and exposes it for use elsewhere; Terraform Core doesn't do anything to "null out" sensitive values automatically. Therefore I'm going to close this issue, only because we use issues in this repository to represent problems with save use-cases for Terraform Core and Terraform CLI, rather than for Terraform Cloud and its provider. Thanks!

**Closed by apparentlymart** 2022-06-14 14:19 UTC
Labels: bug, new, cloud

**Comment by spanktar** [comment] 2022-06-14 16:40
Thanks @apparentlymart, you're totally right. I'll file this over there.
