### ISSUE TITLE
Terraform destroys other resources when resources created by Count

### ISSUE THREAD

**Issue by neeleshg** [hashicorp/terraform#18609] opened 2018-08-06 16:22 UTC
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.30.0
+ provider.statuscake v0.2.0
+ provider.template v1.0.0
```
### Problem Description
I have created multiple aws instances with terraform with the help of Count.
When I try to destroy 1 single aws instance, it also deletes the resources related with other instances.

In below example, if I try to delete resource aws_instance.ca[1], it also tries to delete aws_volume_attachment.ca_attach_data_disk[0] along with aws_volume_attachment.ca_attach_data_disk[1].
Similarly for NLB Target Group attachment and CloudWatch monitors.

### Terraform Configuration Files
aws_instance.tf
```hcl
resource "aws_instance" "ca" {
  count                       = "${var.count}"
  key_name                    = "${var.key_name}"
  subnet_id                   = "${var.subnet_ids[0]}"
  availability_zone           = "${var.azs[0]}"
  vpc_security_group_ids      = ["${var.ca_sg_id}"]
  ami                         = "${data.aws_ami.amazon_linux.id}"
  instance_type               = "${var.instance_type}"
  iam_instance_profile        = "${var.instance_profile}"
  associate_public_ip_address = false
  user_data                   = "${data.template_file.userdata_ca.rendered}"
  root_block_device {
    volume_type           = "gp2"
    volume_size           = "${var.root_volume_size}"
    delete_on_termination = true
  }
resource "aws_ebs_volume" "ca_data_disk" {
  count             = "${var.count}"
  availability_zone = "${var.azs[0]}"
  size              = "${var.data_disk_size}"
  encrypted         = true
}

# EBS Volume attachment as data disk
resource "aws_volume_attachment" "ca_attach_data_disk" {
  count       = "${var.count}"
  device_name = "/dev/xvdm"
  volume_id   = "${aws_ebs_volume.ca_data_disk.*.id[count.index]}"
  instance_id = "${aws_instance.ca.*.id[count.index]}"
}
```

### Expected Behavior
```
$ terraform destroy -target=aws_instance.ca[0]
- aws_instance.ca[0]
- aws_volume_attachment.ca_attach_data_disk[0]
- aws_ebs_volume.ca_data_disk[0]
```
### Actual Behavior
```
terraform destroy -target=aws_instance.ca[0]
- aws_instance.ca[0]
- aws_volume_attachment.ca_attach_data_disk[0]
- aws_ebs_volume.ca_data_disk[0]
- aws_volume_attachment.ca_attach_data_disk[1]
```
### Steps to Reproduce
Run
```
terraform destroy -target=aws_instance.ca[0]
```
### Additional Context
I did not use element() to refer instance_id and volume_id as I found issue with them also.
Then I changed my code according to https://github.com/hashicorp/terraform/issues/3449

**Comment by mildwonkey** [comment] 2018-09-19 20:11
hi @neeleshg,

I'm sorry for the long silence, this issue slipped past me. Are you still having this issue, by any chance, or were you able to figure it out?

**Comment by neeleshg** [comment] 2018-09-24 17:41
Hi @mildwonkey 
Thanks for your response.
Yes this issue is still there.
I guess, this is causing due to Dependencies in tfstate file.

Regards
Neelesh

**Comment by michaelkhan3** [comment] 2020-01-17 05:35
Hi @mildwonkey 

What's the status on this issue?

**Comment by mildwonkey** [comment] 2020-08-27 17:55
It's not really possible to comment on this issue without a complete reproduction case and the output of trace logs; our documentation for `count` (including when not to use it, if possible) has been updated quite a bit since this was opened: https://www.terraform.io/docs/configuration/resources.html#when-to-use-for_each-instead-of-count

Several bugs have been fixed since this time as well, so I am going to close this issue, but if anyone is still experiencing a problem while using terraform v0.13, please open a new issue and fill out the issue template entirely.
Thanks!

**Closed by mildwonkey** 2020-08-27 17:55 UTC
Labels: bug, core, v0.11
