### ISSUE TITLE
Provider lock file (.terraform.lock.hcl) is created with too wide permissions (777)

### ISSUE THREAD

**Issue by nantiferov** [hashicorp/terraform#27435] opened 2021-01-07 16:00 UTC
### Terraform Version

```
Terraform v0.14.4
```

Tested as well with v0.14.2, and OS is `macOS 10.15.7`

### Terraform Configuration Files

```terraform
resource "null_resource" "test" {}

```

### Expected Behavior

After `terraform init` or `terraform providers lock` is executed, lock file (.terraform.lock.hcl) should be created with the same permissions as other files (i.e. should depend on umask). By default permissions will be 644.

### Actual Behavior

Instead, it is always created with 777 permissions. Luckily git commits them with 775, but still it's not what expected.
Another unexpected behaviour is that on Windows with WSL this file has 644 permissions (cause FS doesn't support permissions)

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Check `.terraform.lock.hcl` file permissions with `ls -la`, you will got this `-rwxrwxrwx  1 user  user  1002 Jan  7 17:49 .terraform.lock.hcl`
4. Compare to main.tf file: `-rw-r--r--  1 user  user    36 Jan  7 17:49 main.tf`
5. If you have git in this repo, you can check permissions with `git ls-files --stage`, `100755 a778b2ace9651b69ce27111701d2a122f7ccd57e 0	.terraform.lock.hcl`
6. Should be reproducible on any *nix environment.

### Additional Context

None

### References

Nothing related found in issues

**Comment by jbardin** [comment] 2021-01-07 16:07
This is a duplicate of #27116 and #27152, but I'll leave this open as an issue for backporting to 0.14.

Thanks!

**Comment by nantiferov** [comment] 2021-01-07 16:09
Oh, sorry, missed these issues.
Thank you.

**Closed** 2021-01-07 16:28 UTC
Labels: bug, v0.14
