### ISSUE TITLE
 Error: no schema available for cloudflare_ip_list while reading state

### ISSUE THREAD

**Issue by jogarao96** [hashicorp/terraform#34307] opened 2023-11-28 14:04 UTC
### Terraform Version

```shell
Terraform v1.4.6
on linux_amd64
```

### Terraform Configuration Files

```
resource "cloudflare_list" "xyz_allowlist" {
  account_id  = local.account_id
  name        = "xyz_allowlist"
  kind        = "ip"
  description = "List of ips allowed xyz sites"

  dynamic "item" {
    for_each = local.xyz_allowlist
     content {
      value {
        ip = item.key
      }
    }
  }
}
```

### Debug Output

 Error: no schema available for cloudflare_ip_list.cloudflare_ipranges while reading state; this is a bug in Terraform and should be reported

### Expected Behavior

it should read state file and according to update guide updated all cloudflare_ip_list to cloudflare_list which is not recognized by terraform in the given specific version

### Actual Behavior

The ip lists has to be updated with new name from cloudflare_ip_list to just cloudflare_list

### Steps to Reproduce

while updating from cloudflare from 3.x to 4.x version it is unable to update cloud flare ip lists 

terraform init 
terraform validate
terraform plan

**Comment by apparentlymart** [comment] 2023-11-28 16:14
Hi @jogarao96,

From what you described this seems like a problem with the Cloudflare provider rather than with Terraform Core itself, despite the fact that Terraform Core blamed itself in the error message.

I think it's best to start this discussion in the Cloudflare provider repository so that the maintainers who wrote the upgrade guide you are referring to can consider what's going on here. If the provider maintainers conclude that this _is_ caused by a Terraform Core bug then we can bring the discussion back over here with that additional context, but as currently presented we can't really do anything specific with this issue because we are not familiar with the design details of this particular provider.

Specifically, it seems like the new release of the provider has totally removed support for a resource type that was previously supported, which means that there isn't sufficient information to make any sense of what's already stored in your Terraform State. I think therefore it's best to start with the provider team because they will know what their intentions were with making this breaking change and can hopefully clarify the upgrade instructions.

For now, I'm going to close this. We can reopen it if the provider developers decide to treat this as a Terraform Core bug and can explain here how Terraform Core's behavior is differing from what they expected.

Thanks!

**Closed by apparentlymart** 2023-11-28 16:14 UTC
Labels: bug, new
