### ISSUE TITLE
Issue in destroying 0.12 terraform resources with Terraform 0.13

### ISSUE THREAD

**Issue by vbuddi** [hashicorp/terraform#25522] opened 2020-07-08 19:44 UTC
Hi,
 I created a OCI resources using Terraform 0.12.
Now I imported only the terraform state file to another directory and created a provider file. Now I am trying to delete the resources using Terraform 0.13, but I am getting below error
---------------------------------------------------------------------------
To work with oci_database_autonomous_database.test_autonomous_database its
original provider configuration at provider["registry.terraform.io/-/oci"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy.

To work with local_file.autonomous_data_warehouse_wallet_file its original
provider configuration at provider["registry.terraform.io/-/local"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
local_file.autonomous_data_warehouse_wallet_file, after which you can remove
the provider configuration again.
---------------------------------------------------------------------------.
I don't see this issue when I try to delete the Terraform 0.11 resources with Terraform 0.12.

Thanks,
  Viswanath

**Comment by apparentlymart** [comment] 2020-07-08 22:29
Hi @vbuddi,

This is a result of some changes to how Terraform understands the identity of providers in Terraform 0.13. The upgrade process from Terraform 0.12 to 0.13 assumes that you'll run `terraform apply` at least once after upgrading to Terraform 0.13 in order to create a new state snapshot that uses the new provider configuration syntax. Due to how the upgrade process works, it isn't possible to apply with Terraform 0.12 and then immediately destroy with Terraform 0.13 without an intermediate change in Terraform 0.12 first.

If the situation I described above doesn't apply to you (that is, if you've run `terraform apply` at least once with Terraform 0.13 before running `terraform destroy`) then please let me know, and we can investigate further. However, in order to investigate further we will need you to provide all of the information we requested in [the bug report issue template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md), so that we can reproduce the problem in our development environments.

Thanks!

**Comment by vbuddi** [comment] 2020-07-13 06:50
Hi,
   I have tried running terraform apply before running terraform destroy but it didn't work.
Let me explain the scenario.

Step 1: Create a compute instance using **terraform 0.12**
Step 2: Created a project '_resource_delete_' with provider information( attaching for you reference)
Step 3: Copied the _terraform.tfstate_ file created in Step1 to the '_resource_delete_' project
Step 4: Run _terraform destroy_ using **terraform 0.13**
I am getting error as shown in the screen shot attachments.

The same scenario worked fine where I could use terraform 0.12 to delete resources created with terraform 0.11.

Thanks!
[resource_delete.zip](https://github.com/hashicorp/terraform/files/4911022/resource_delete.zip)
![terraform0 13_init](https://user-images.githubusercontent.com/11436582/87278820-08b6e880-c503-11ea-8b4d-cc7203e1bbab.png)
![terrafomr0 13_destroy](https://user-images.githubusercontent.com/11436582/87278841-11a7ba00-c503-11ea-8245-ae8b37d37e93.png)

**Comment by apparentlymart** [comment] 2020-07-13 21:41
Hi @vbuddi,

I just noticed we've been having the same conversation both here and [in the community forum](https://discuss.hashicorp.com/t/issue-in-destroying-0-12-terraform-resources-with-terraform-0-13/11207/4). As I mentioned over there, this behavior is one of the compromises required to make the upgrade from legacy to fully-qualified provider addresses work correctly, and so removing resources from your configuration immediately upgrading, before running `terraform apply` to update their state snapshots, is not a supported upgrade path.

I opened #25563 to add an explicit note about this in the upgrade guide. I'm going to close this issue now, but if you'd like to talk about this some more I'm happy to continue the conversation on the community forum. Thanks!

**Closed by apparentlymart** 2020-07-13 21:41 UTC
