### ISSUE TITLE
Console output shows control characters

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#3278] opened 2015-09-18 11:07 UTC
In Windows, whether I use the command prompt, powershell or bash weird control characters show up in the output when running terraform:

←[0m
←[0m←[1mPlan:←[0m 0 to add, 1 to change, 0 to destroy.←[0m

**Comment by stack72** [comment] 2015-09-18 11:15
@JorritSalverda please can you add what version of terraform you are using

**Comment by JorritSalverda** [comment] 2015-09-18 11:27
$ terraform --version
Terraform v0.6.3

**Comment by JorritSalverda** [comment] 2015-09-18 11:42
Just found the -no-color option. Can I somehow make this permanent so I don't have to set it each time?

**Comment by stack72** [comment] 2015-09-18 11:43
@JorritSalverda on OSX I use a makefile so I guess you could use a .bat / .ps file on windows and have it set in there

**Comment by JorritSalverda** [comment] 2015-09-18 13:08
No environment variables like with packer? See https://www.packer.io/docs/other/environmental-variables.html#PACKER_NO_COLOR

**Comment by apparentlymart** [comment] 2015-09-18 16:17
Given that Windows has no support for VT100 escape codes, it seems like at least Terraform should just force colors off.

It looks like the Windows console doesn't have any equivalent way to embed color codes in-band in the output stream and instead requires functions to be called between writes to the console, so actually supporting colors on Windows would probably require some more significant refactoring.

Perhaps it's reasonable to have a special version of [``Meta.Colorize``](https://github.com/hashicorp/terraform/blob/198e1a5186c264e0a03d7ffc26a175821f8b8dbf/command/meta.go#L87) for Windows builds, which just forces on the ``Disable`` flag regardless of what's set on the command line. Then the ``-no-color`` flag could be documented as having no effect on Windows, though I think I'd still leave it accepted so it's easier to share wrapper scripts between Linux and Windows.

**Comment by jen20** [comment] 2016-03-18 17:29
Fixed in #5718.

**Closed by jen20** 2016-03-18 17:29 UTC
Labels: bug, core, windows

**Comment by IDT-kcrook** [comment] 2018-01-31 17:43
This is not all fixed. We're still seeing this in v0.11.2 on vanilla powershell/command prompt but using ConEmu is a suitable workaround.

**Comment by apparentlymart** [comment] 2018-01-31 19:25
Hi @IDT-kcrook!

This was fixed by making the Windows build filter all output through a post-processor that parses VT100 escape sequences and translates them into equivalent calls to the Windows console API.

This special handling only applies to the `windows_amd64` and `windows_386` builds, so in particular doesn't apply when the Linux build of Terraform is run inside "Windows Subsystem for Linux" on Windows 10.

If you're running one of the native Windows builds and yet still seeing this problem in the built-in Windows shell, please open a new issue and fill out the new issue template so we can try to figure out what's happened here... the fix here went out in v0.6.14, and there were further improvements from #14194 released in v0.9.5, so it's likely that the issue you're seeing has a different root cause than this original report.
