### ISSUE TITLE
Terraform accepts incorrect input and tells me my configuration has no changes on apply

### ISSUE THREAD

**Issue by banani720** [hashicorp/terraform#32223] opened 2022-11-15 21:13 UTC
### Terraform Version

```shell
Terraform v1.3.3
on windows_amd64
```

### Terraform Configuration Files

Terraform config files are not really relevant here

### Debug Output

I ran terraform apply -target `modules.some_module`

### Expected Behavior

I would expect that terraform would tell me that `modules.some_module` is not a valid module or resource or simply tell me it doesn't exist

### Actual Behavior

The following is output to me:

```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply modules.some_module`

### Additional Context

NA

**Comment by jbardin** [comment] 2022-11-15 21:17
Duplicate of #30434

**Closed by jbardin** 2022-11-15 21:17 UTC
Labels: bug, new

**Comment by banani720** [comment] 2022-11-15 21:52
@jbardin While I appreciate the swift marking as duplicate, the other issue you linked seems to have been closed with no resolution and no explanation of why this issue persists through v1.3.3... it would be helpful to get an explanation of a) is this an intended behavior b) if so why? c) if not is there a plan to get it fixed in future versions of terraform.
