### ISSUE TITLE
Provision AWS LB can take a very long time

### ISSUE THREAD

**Issue by ado120** [hashicorp/terraform#24799] opened 2020-04-28 21:25 UTC
### Terraform Version

```
0.12.24

AWS Provider: 2.59.0
```

### Expected Behavior

Spinning up an amazon application load balancer should take no more than 5 minutes

### Actual Behavior

Amazon Load Balancers can sometimes take up to 30 minutes to deploy

### Steps to Reproduce

We've noticed an issue starting with 2.58 and higher (Can't remember if we've had it on older versions to be honest) where spinning up an AWS ALB can take upwards of 30 minutes. On most of our ci/cd runs it takes no more than 5. We've recently turned on DEBUG to trace and have the logs however I can't most it here since there could be potentially sensitive information in those files. Would anyone happen to know the best way to parse this file and see if this is a terraform or aws api issue?

Our load balancer gets applied through a module which has the following resources:
1. data.aws_acm_certificate
2. data_aws_subnet_ids
3. resource.aws_lb
4. resource.aws_lb_target_group
5. resource.aws_lb_target_group_attachment
6. resource.aws_lb_listener

Now I realize with that many resources in the module it is a bit hard to pinpoint exactly what is causing the issue, but I'm hoping either someone has faced the same thing where ALBs can take a long time to provision with a fix or help me in parsing through the debug log to see exactly where the issue is. Thank you so much!

**Comment by danieldreier** [comment] 2020-04-28 22:05
Hello @ado120! 30 minute LB provisioning time sounds excessive indeed. That said, it looks to me like you're asking for help with a Terraform provider, rather than reporting a particular bug. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) or the [the Terraform Core community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do ask your question in the community forum, and then please come back either here or to the Terraform AWS Provider if you find evidence of a bug in either of those tools that's the root cause here.

**Closed by danieldreier** 2020-04-28 22:05 UTC
Labels: question
