### ISSUE TITLE
Unable to enforce (single) quote around yml string value

### ISSUE THREAD

**Issue by t638403** [hashicorp/terraform#22847] opened 2019-09-19 15:07 UTC
# Download Terraform
```
sudo mkdir /opt/terraform
cd /opt/terraform
sudo wget https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip
sudo unzip terraform_0.12.9_linux_amd64.zip
echo "export PATH=\$PATH:/opt/terraform" >> ~/.zshrc
```

### Current Terraform Version
```
Terraform v0.12.9
+ provider.helm v0.10.2
+ provider.kubernetes v1.9.0
````

### Use-cases
I have this terraform release for elasticsearch on kubernetes.
```
resource "helm_release" "elasticsearch" {
    name      = "some name"
    chart     = "elastic/elasticsearch"
    set {
        name = "roles.master"
        value = "true"
    }
...
}
```
The values.yaml for helm renders this as
```
...
roles:
   master: true
...
```
Unfortunately helm is unable to render this into the `statefulset.yaml` template. 
```
Error: rpc error: code = Unknown desc = render error in "elasticsearch/templates/statefulset.yaml": template: elasticsearch/templates/statefulset.yaml:188:17: executing "elasticsearch/templates/statefulset.yaml" at <eq .Values.roles.mas...>: error calling eq: incompatible types for comparison
```
I have tested directly with helm and when I wrap the `true` value in single quotes (`master: 'true'`) helm becomes able to render it into the `statefulset.yaml` template. However I can not find a way to enforce this using terraform `set`.

### Attempted Solutions
I have tried:

1:
```
set {
        name = "roles.master"
        value = "true"
    }
```
which results in `master: true`.

2:
```
set {
        name = "roles.master"
        value = "${true}"
    }
```
which results in `master: true`

3:
```
set {
        name = "roles.master"
        value = "'${true}'"
    }
```
which results in `master: '''true'''`

4:
```
set {
        name = "roles.master"
        value = <<EOF
true
EOF
    }
```
which results in 
```
master: |
    true
```
5:
```
set {
        name = "roles.master"
        value = "\\\\'${var.es_node_roleMaster}\\\\'"
    }
```
which results in `master: \'true\'`

### Proposal
Some function `quote(string)` which will enforce a single quote around the string.

### References
The helm template:
[https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml)

**Comment by teamterraform** [comment] 2019-09-19 16:45
Hi @t638403!

We've asked the bot to consider this a Helm provider bug because the Helm provider seems to be trying to present an abstraction over the YAML but that abstraction is leaking here due to the lack of quoting. Having the Helm provider handle this quoting automatically would then provide the abstraction as intended, avoiding the need for the user to worry about how this value will ultimately be encoded in YAML.

Our bot will close this issue and open a new issue with the same content on your behalf in the Helm provider repository.

**Comment by teamterraform** [comment] 2019-09-19 16:47
(With that said, Terraform already has a function `jsonencode` which can produce a JSON-quoted version of a string value. Since YAML is a superset of JSON, `jsonencode` should be a sufficient workaround for the moment, with the caveat that if this bug is later fixed upstream you'll probably end up with a double-quoted value.)

**Closed** 2019-09-19 17:20 UTC
Labels: bug, provider/helm

**Comment by davidq2q** [comment] 2019-09-20 12:45
try https://www.terraform.io/docs/configuration/functions/format.html

**Comment by t638403** [comment] 2019-09-23 10:50
@teamterraform and @davidq2q thanks for the response!

Finally I was able to use `set_string` in stead of `set`:
```
set_string {
        name = "roles.master"
        value = true   
}
```
