### ISSUE TITLE
Error creating DNS record in GCP 

### ISSUE THREAD

**Issue by ametanchuk** [hashicorp/terraform#24854] opened 2020-05-04 21:33 UTC
google_dns_record_set.system-rr-dns: Creating...

Error: configuration for google_dns_record_set.system-rr-dns still contains unknown values during apply (this is a bug in Terraform; please report it!)

Configuration: 
resource "google_dns_record_set" "system-rr-dns" {
  name = format("${var.instance_name}-${var.regions[0]}.%s.", var.dns_zone)
  type = "A"
  ttl  = 120
  project = var.project_id
  managed_zone = var.managed_zone
  rrdatas = [module.lb_internal[0].ip_address]
}

Output from the module if run without DNS create: 
lb_ip_address = {
  "east" = "10.45.0.100"
}

**Comment by danieldreier** [comment] 2020-05-04 22:30
Hi! Thanks for reporting this. Given the error you got, I think this is probably a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I have a partial code snippet but not a full reproduction case, and so I'm stuck. 

Can you please restate your reproduction case such that I can copy-paste it and run it locally?

**Comment by ametanchuk** [comment] 2020-05-05 10:24
Hi, I'm not sure if I can provide the exact setup to run locally but these are the applicable parts.  Hopefully they can help.  Creating DNS record calls a module and then it fails on setting an address for the load balancer when called rrdatas = [module.lb_internal[0].ip_address]. Maybe that is not the correct way to do it. 

The working output for that IP address is below:
lb_ip_address = {
"east" = "10.45.0.100"
}




variable "regions" {
  default = ["east"]
  description = "Setup region where to deploy instances"
  
}


module "lb_internal" {
  source          = "git::ssh://xxxxxx"
  project_id      = var.project_id
  health_check    = var.health_check
  name_prefix     = "${var.release_type}-${var.deployment_type}-tfs-lb"
  environment     = var.environment
  network_type    = var.network_type
  instance_groups = module.vault_compute.instance_groups
  regions        = var.regions
}





output "lb_ip_address" {
  description = "The internal IP assigned to the regional forwarding rule."
  value       = module.lb_internal.ip_address
}



resource "google_dns_record_set" "lb_records" {
  for_each = (var.dns_managed_zone == null ? [] : local.regions)
  name = format("%s.", replace(
          replace(var.dns_format,"domain", var.dns_managed_zone.dns_name),
           "dc", each.value))
  type = "A"
  ttl = "3600"

  managed_zone = var.dns_managed_zone.name
  project = var.dns_managed_zone.project_id

  rrdatas = [ local.forwarding_rule_ips[each.value] ]
}

**Comment by danieldreier** [comment] 2020-05-08 01:34
Hi @ametanchuk -

I appreciate you providing some additional information, but without a full, ready-to-use reproduction case, this is unlikely to get solved, because there's too much unknown in the missing details, and inventing an example that can make use of the code block provided is an inordinate amount of work.

I'm going to close this for now because the information is insufficient to quickly reproduce the problem. I do believe you're probably having a legitimate issue and I would like to fix it, but I have to be able to run this and reproduce it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

If you would like to put the work into creating a full reproduction case, I'm happy to re-open the issue and then try to reproduce it.

**Closed by danieldreier** 2020-05-08 01:34 UTC
