### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by shrusubra** [hashicorp/terraform#31899] opened 2022-09-29 12:24 UTC
### Terraform Version

```shell
1.3.0
provider - oci
```

### Terraform Configuration Files

```terraform
data "oci_core_drg_route_tables" "drg_route_tables" {
  for_each = var.data_drg_route_tables

  #Required
  drg_id = length(regexall("ocid1.drg.oc1*", each.value.drg_id)) > 0 ? each.value.drg_id : merge(module.drgs.*...)[each.value.drg_id]["drg_tf_id"]
  filter {
    name   = "display_name"
    values = [each.value.values]
  }

}



data "oci_core_drg_route_distributions" "drg_route_distributions" {
  for_each = var.data_drg_route_table_distributions

  #Required
  drg_id = length(regexall("ocid1.drg.oc1*", each.value.drg_id)) > 0 ? each.value.drg_id : merge(module.drgs.*...)[each.value.drg_id]["drg_tf_id"]
  filter {
    name   = "display_name"
    values = [each.value.values]
  }

}
```

### Debug Output

comes when we run terraform import commands.

### Expected Behavior

Import Successfull

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

4 problems:

- Failed to serialize resource instance in state: Instance data.oci_core_drg_route_tables.drg_route_tables["drg_Autogenerated-Drg-Route-Table-for-VCN-attachments"] has status ObjectPlanned, which cannot be saved in state.
- Failed to serialize resource instance in state: Instance data.oci_core_drg_route_tables.drg_route_tables["drg_Autogenerated-Drg-Route-Table-for-RPC--VC--and-IPSec-attachments"] has status ObjectPlanned, which cannot be saved in state.
- Failed to serialize resource instance in state: Instance data.oci_core_drg_route_distributions.drg_route_distributions["drg_Autogenerated-Import-Route-Distribution-for-ALL-routes"] has status ObjectPlanned, which cannot be saved in state.
- Failed to serialize resource instance in state: Instance data.oci_core_drg_route_distributions.drg_route_distributions["drg_Autogenerated-Import-Route-Distribution-for-VCN-Routes"] has status ObjectPlanned, which cannot be saved in state.
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:55 +0x153
panic({0x30a2a60, 0xc014cfefd8})
	runtime/panic.go:890 +0x262
github.com/hashicorp/terraform/internal/states/statefile.StatesMarshalEqual(0xc003b3edd0, 0xc001ae6eb0)
	github.com/hashicorp/terraform/internal/states/statefile/marshal_equal.go:31 +0x191
github.com/hashicorp/terraform/internal/states/statemgr.(*Filesystem).writeState(0xc001acc480, 0xc003b3edd0, 0x0)
	github.com/hashicorp/terraform/internal/states/statemgr/filesystem.go:151 +0xf7
github.com/hashicorp/terraform/internal/states/statemgr.(*Filesystem).WriteState(0xc001acc480, 0x0?)
	github.com/hashicorp/terraform/internal/states/statemgr/filesystem.go:137 +0xae
github.com/hashicorp/terraform/internal/command.(*ImportCommand).Run(0xc0006c36c0, {0xc0000520e0, 0x2, 0x2})
	github.com/hashicorp/terraform/internal/command/import.go:261 +0x1eb5
github.com/mitchellh/cli.(*CLI).Run(0xc000628c80)
	github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x5f8
main.realMain()
	github.com/hashicorp/terraform/main.go:315 +0x15d4
m

### Steps to Reproduce

terraform import command for drg

**Comment by jbardin** [comment] 2022-09-29 12:54
duplicate of #31851

**Closed by jbardin** 2022-09-29 12:54 UTC
Labels: bug, new
