### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#17652] opened 2018-03-20 22:35 UTC
### Terraform Version

```
Terraform v0.11.4
+ provider.aws v1.10.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
...
```

**Comment by jbardin** [comment] 2018-03-20 23:20
Hi @silvermy,

There doesn't seem to be any information in the issue body.
If you meant to file the issue with more information, go ahead and edit and reply and I can review the updated info.

**Comment by silvermy** [comment] 2018-03-20 23:25
[crash.log](https://github.com/hashicorp/terraform/files/1831575/crash.log)

**Comment by jbardin** [comment] 2018-03-21 14:58
Hi @silvermy,

Thanks for the log output.
Do you happen to have the steps you tool to create the crash? There seems to be a lot going on here, multiple deposed resource instances, resource with create_before_destroy, modules removed from the configuration, etc. I'm not quite sure yet how you got to this state to reproduce the issue.

**Comment by apparentlymart** [comment] 2018-11-08 16:44
Hi @silvermy!

It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to open a new issue and complete all of the information requested in the Bug Report template so that we can attempt to understand and reproduce the problem.

Thanks!

**Closed by apparentlymart** 2018-11-08 16:44 UTC
Labels: bug, core, crash
