### ISSUE TITLE
Random failures during terraform plan/apply on M1

### ISSUE THREAD

**Issue by KhimairaCrypto** [hashicorp/terraform#30351] opened 2022-01-13 09:13 UTC
I am not able to find out why executing `terraform plan/apply` will fail on the random bases. This behaviour happen regardless of the complexity of the project. I tried using local and S3 backends and same result. 

**I installed terraform and aws cli using `brew`**, I even run `brew doctor` to verify if something was broken and no issues. 

### Terraform Version

```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### AWS  CLI Version

```                                                        
aws-cli/2.4.10 Python/3.9.9 Darwin/21.2.0 source/x86_64 prompt/off
```
### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">=3.70.0"
    }
  }
}

provider "aws" {
  profile = var.aws_iam_profile
  region  = var.deployment_region
}

resource "aws_s3_bucket" "prod_web" {
  bucket = "superman-batman-yoyo"
  acl    = "private"

  versioning {
    enabled = true
  }
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}

resource "aws_s3_bucket_public_access_block" "prod_web" {
  bucket = aws_s3_bucket.prod_web.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
```

### Debug Output
```
2022-01-12T15:24:29.056+1100 [ERROR] plugin.(*GRPCProvider).ValidateProviderConfig: error="rpc error: code = Canceled desc = context canceled"
2022-01-12T15:24:29.057+1100 [ERROR] vertex "provider[\"registry.terraform.io/hashicorp/aws\"]" error: Request cancelled
2022-01-13T11:03:10.772+1100 [ERROR] vertex "provider[\"registry.terraform.io/hashicorp/aws\"]" error: Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

### Expected Behavior
Stop crashing!

### Actual Behavior
Need to run multiple times terraform plan/terraform apply to deploy the infrastructure :-/

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by jbardin** [comment] 2022-01-13 15:18
Hi @KhimairaCrypto,

Thanks for reporting this. It does not look like the issue is with the Terraform CLI -- the error indicates that the plugin is either exiting immediately after we connect, or is writing invalid data to stdout during the initial handshake.

Does this only happen with the AWS provider? If so, does it only happen with specific versions?

**Comment by KhimairaCrypto** [comment] 2022-01-13 20:47
Hi @jbardin,

Thank you for your quick reply! AWS is the only provided that I use. It has been happening for about a month. Not sure since which version, because I brew keeps my packages up to date. I did not mind to hit enter several times to restart the planning/deployment process. But is not ideal, since time will add up and will become a considerable time waist over time :-(.

**Comment by jbardin** [comment] 2022-01-13 21:52
Thanks @KhimairaCrypto, I'll close this and we can follow the issue in the AWS provider. They may have better idea about what could be corrupting the plugin handshake.

**Closed by jbardin** 2022-01-13 21:52 UTC
Labels: bug, waiting-response, new, waiting for reproduction
