### ISSUE TITLE
Mask console input for sensitive variables

### ISSUE THREAD

**Issue by cberge908** [hashicorp/terraform#28362] opened 2021-04-14 13:22 UTC
### Current Terraform Version

```
v0.14.10
```

### Use-cases

In case a variable is defined, but not declared in the tfvars file, the input of this variable will be requested from standard input. In case this is a sensitive variable (e.g. passwords), the input should be masked. At the moment the sensitive flag just masks the output after "terraform apply" or "terraform plan", but not during the input via console.

I know that key vaults should be used for such use case, but I think that this masking might be a good feature to make Terraform more secure :)

variables.tf:
```hcl
variable "mail-pw" {
  description = "Password of the SMTP user for mail notifications"
  type = string
  sensitive = true
 }
```
Console input during `terraform plan`
Remark: This is not an actual password, just a dummy value.

```hcl
% terraform plan
Acquiring state lock. This may take a few moments...
var.mail-pw
  Password of the SMTP user for mail notifications

  Enter a value: mysupersecretpassword
```
### Proposal

Already stated above.

**Comment by jbardin** [comment] 2021-04-14 13:28
Duplicate of #28122

**Closed by jbardin** 2021-04-14 13:28 UTC
Labels: enhancement, new
