### ISSUE TITLE
Nested JSON deserialisation issue causes panic exception after plan

### ISSUE THREAD

**Issue by steinroe** [hashicorp/terraform#28670] opened 2021-05-11 07:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.66.1
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "<our-org-name>"

    workspaces {
      prefix = "<some-prefix>-"
    }
  }
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

variable "region" {
  type = string
}

variable "project" {
  type    = string
  default = "test"
}

provider "google" {
  region  = var.region
  project = var.project
}

resource "google_container_cluster" "main" {
  name = "main"
  //location         = var.region
  //network          = google_compute_network.vpc.name
  //enable_autopilot = true
}
```

### Debug Output

https://gist.github.com/steinroe/4023c4a3dfb89d6a45236c029dce74f0

### Panic Output

I can't find the log file - neither locally on my system nor do I see an option in TF Cloud to retrieve it.

### Expected Behavior

`terraform plan` should exit successfully.

### Actual Behavior

It crashes despite successfully outputting plan.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I run into this issue on Apple Silicon as well as when running within a GitHub action. Also, this issue does only happen as soon as I use the `google_container_cluster` resource. Other resources work fine. Also, when using a local backend, this error does not occur.

Downstream issue: https://github.com/hashicorp/terraform-provider-google/issues/9103

**Comment by jbardin** [comment] 2021-05-11 12:55
Thanks @steinroe, marking as duplicate of #28631

**Closed by jbardin** 2021-05-11 12:55 UTC
Labels: bug, new
