### ISSUE TITLE
Providers vendored against 0.9.8 missing changes from 0.10.0

### ISSUE THREAD

**Issue by rowleyaj** [hashicorp/terraform#15831] opened 2017-08-16 18:09 UTC
### Terraform Version
Terraform v0.10.0

### Terraform Configuration Files
Any basic config attempting to read state from a non-default workspace key prefix e.g:
```hcl
data "terraform_remote_state" "test" {
  backend     = "s3"
  environment = "test"

  config = {
    bucket  = "state-bucket-name"
    key     = "bucket-key"
    region  = "us-east-1"

    workspace_key_prefix = "workspaces"

    dynamodb_table = "state-lock-table"
  }
}
```

### Debug Output
Only a few relevant lines so pasting here directly:
```
2017/08/16 18:34:55 [DEBUG] plugin: terraform-provider-terraform_v0.1.0_x4: 2017/08/16 18:34:55 [DEBUG] [aws-sdk-go] DEBUG: Request s3/ListObjects Details:
...
2017/08/16 18:34:55 [DEBUG] plugin: terraform-provider-terraform_v0.1.0_x4: GET /?prefix=env%3A%2F HTTP/1.1
...
2017/08/16 18:34:55 [DEBUG] plugin: terraform-provider-terraform_v0.1.0_x4: User-Agent: aws-sdk-go/1.8.34 (go1.8; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.9.8
```

### Expected Behavior
- Terraform would interact with AWS with the user agent set to 10.0.0
- Terraform would use the workspace_key_prefix from the config rather than `env:`

### Actual Behavior
- User agent shows as 0.9.8
- workspace_key_prefix default used `env:`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I believe this is due to vendoring in the terraform providers.
https://github.com/terraform-providers/terraform-provider-terraform/blob/v0.1.0/vendor/github.com/hashicorp/terraform/terraform/version.go#L10

### References
- #15370

The solution to this issue would be to re-release the terraform provider so that the changes from the above PR are included in the vendored code. I've opened this issue here rather than on the provider repo though as it's an issue that could affect other providers due to the way Terraform is vendored within them. What is the process for re-releasing the providers with updated vendored code when new releases of Terraform core are cut?

**Comment by apparentlymart** [comment] 2017-08-16 18:38
Hi @rowleyaj! Sorry for the weird lag here.

@radeksimko has been working on getting the vendoring updated across all the providers. I'll let him comment on the progress there, but indeed the goal is to eventually have new releases of all of them against the latest core code. Fortunately, most providers don't have such deep dependencies on core, so the `terraform` provider is a bit of an outlier here.

**Comment by radeksimko** [comment] 2017-08-18 13:58
Hi @rowleyaj 
I managed to upgrade vendored terraform in all providers except in Arukas (which is unmaintained, so I don't plan to bump it there) and DME - which requires some schema changes to comply with new naming restrictions. I plan to work on DME 🔜 , but for all other providers it's just a matter of cutting a new release and that will already contain Terraform `0.10`.

**Comment by mcg** [comment] 2017-09-13 22:16
Any ETA on this re-release? Bumping into missing `workspace_key_prefix`

**Comment by apparentlymart** [comment] 2017-09-14 01:07
Version 1.0.0 of the `terraform` provider includes v0.10 Terraform code, so should now work with `workspace_key_prefix`.

Most other providers will get gradually updated as part of their normal release cycles, since they don't depend on anything that was new in 0.10. If anyone finds other provider limitations caused by old vendoring, please open an issue in the respective provider repository since that's more likely to get seen by the maintainers of the provider in question.

Since the Terraform provider was the main focus of this issue, I'm going to close this now and we'll just deal with the other providers asynchronously.

Thanks for reporting this, @rowleyaj!

**Closed by apparentlymart** 2017-09-14 01:07 UTC
Labels: question
