### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by visshal** [hashicorp/terraform#31918] opened 2022-09-30 17:47 UTC
### Terraform Version

```shell
terraform -v
Terraform v1.2.1
on linux_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is null
goroutine 1858 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2140e00, 0x2b3db10})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/zclconf/go-cty/cty.Value.LengthInt({{{0x2b667d0?, 0xc002513f10?}}, {0x0?, 0x0?}})
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.11.0/cty/value_ops.go:1066 +0x1e5
github.com/hashicorp/terraform/internal/plans/objchange.assertPlanValid(0xc00024c820, {{{0x2b66840?, 0xc002374870?}}, {0x2218580?, 0xc003788690?}}, {{{0x2b66840?, 0xc0023743a0?}}, {0x2218580?, 0xc003788270?}}, {{{0x2b66840, ...}}, ...}, ...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:105 +0x9e5
github.com/hashicorp/terraform/internal/plans/objchange.assertPlanValid(0xc00024c7d0, {{{0x2b66840?, 0xc002375aa0?}}, {0x2218580?, 0xc003789a70?}}, {{{0x2b66840?, 0xc0023743d0?}}, {0x2218580?, 0xc0037882d0?}}, {{{0x2b66840, ...}}, ...}, ...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:127 +0x2eb8
github.com/hashicorp/terraform/internal/plans/objchange.assertPlanValid(0xc002137380, {{{0x2b66840?, 0xc002375b30?}}, {0x2218580?, 0xc003789b30?}}, {{{0x2b66840?, 0xc002374610?}}, {0x2218580?, 0xc003788480?}}, {{{0x2b66840, ...}}, ...}, ...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:127 +0x2eb8
github.com/hashicorp/terraform/internal/plans/objchange.AssertPlanValid(...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:36
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc002c725a0, {0x2b7ccb8, 0xc000e621c0}, 0x0, 0xc000b29ec0, 0x0, {0x0, 0x0, 0x10?})
	/home/circleci/project/project/internal/terraform/node_resource_abstract_instance.go:843 +0x16fe
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0030a8200, {0x2b7ccb8, 0xc000e621c0})
	/home/circleci/project/project/internal/terraform/node_resource_plan_instance.go:218 +0xd6e
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x2b7ccb8?, 0xc000e621c0?}, 0x40?)
	/home/circleci/project/project/internal/terraform/node_resource_plan_instance.go:60 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0017ae960, {0x2b7ccb8, 0xc000e621c0}, {0x7fe0e0ef0428, 0xc0030a8200})
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x25683a0, 0xc0030a8200})
	/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000759920, {0x25683a0, 0xc0030a8200}, 0xc0030a8b40)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0xf65
```

### Expected Behavior

It should have continued with Terrraform Plan.

### Actual Behavior

Terraform crashed.

### Steps to Reproduce

`terraform plan`
`terraform destroy`

**Comment by visshal** [comment] 2022-09-30 17:51
I am going to try with the latest Terraform version and try to reproduce it.

**Comment by jbardin** [comment] 2022-09-30 20:24
Hi @visshal,

Thanks for reporting the crash! This is a duplicate of #31536, so I'm going to close the issue. It would very helpful if you could add some data to help reproduce the crash and help us trace where this unexpected value is coming from.

Thanks!

**Closed by jbardin** 2022-09-30 20:24 UTC
Labels: bug, new

**Comment by visshal** [comment] 2022-09-30 21:13
Thanks @jbardin for the reply. I'll keep monitoring [#31536.](https://github.com/hashicorp/terraform/issues/31536)
