### ISSUE TITLE
Vsphere: Customization Problem

### ISSUE THREAD

**Issue by eloycoto** [hashicorp/terraform#3562] opened 2015-10-20 09:44 UTC
Hi, 

With this config we are having the following error: 
```
resource "vsphere_virtual_machine" "testb" {
  datacenter = "XXX"
  cluster = "XXX"
  name   = "terraformweb4"
  vcpu   = 1
  memory = 256

  network_interface {
    label = "Staging"
  }

  disk {
    datastore = "datastore_XXX"
    template =  "x_template"
    size=10
  }
}
```

With this we got the following error in this line: 

https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L1039

```
Error applying plan:
2015/10/20 10:29:05 [DEBUG] vertex provider.vsphere (close), got dep: vsphere_virtual_machine.testb
2015/10/20 10:29:05 [DEBUG] vertex root, got dep: provider.vsphere (close)
2015/10/20 10:29:05 [DEBUG] vertex root, got dep: provisioner.chef
2015/10/20 10:29:05 [DEBUG] vertex root, got dep: provisioner.file
2015/10/20 10:29:05 [DEBUG] vertex root, got dep: provisioner.local-exec
2015/10/20 10:29:05 [DEBUG] vertex root, got dep: provisioner.remote-exec
2015/10/20 10:29:05 [DEBUG] waiting for all plugin processes to complete...

1 error(s) occurred:

* vsphere_virtual_machine.testb: Customization of the guest operating system 'debian6_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated 2015/10/20 10:29:05 [DEBUG] /Users/eloy/.go/bin/terraform-provisioner-remote-exec: plugin process exited
2015/10/20 10:29:05 [DEBUG] /Users/eloy/.go/bin/terraform-provisioner-file: plugin process exited
2015/10/20 10:29:05 [DEBUG] /Users/eloy/.go/bin/terraform-provider-vsphere: plugin process exited
2015/10/20 10:29:05 [DEBUG] /Users/eloy/.go/bin/terraform-provisioner-chef: plugin process exited
2015/10/20 10:29:05 [DEBUG] /Users/eloy/.go/bin/terraform-provisioner-local-exec: plugin process exited
with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

If I deleted the `Customization` [on the VirtualMachineCloneSpec](
https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L1027) works ok. Any idea? 

Cheers

**Comment by eloycoto** [comment] 2015-10-21 13:54
Hi, 

Quick Update on this. [Debian is not available in the VSphere Customizations](http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf) so maybe the terraform should have a workaround to unsupported servers. 

Using Debian template if you don't send the customizations works ok, but DNS/Timezone/Hostname can't be set directly from guest. 

What is the best way to handle this?

Regards.

**Comment by mkuzmin** [comment] 2015-10-21 14:45
I'd look at [cloud-init](http://cloudinit.readthedocs.org/en/latest/).

**Comment by chrislovecnm** [comment] 2015-11-11 23:21
@eloycoto can you not use open vm tools?  You will need open-vm-tools, perl, and deployPkg?  I am using open-vm-tools with Centos, and it is working like a champ.

**Comment by chrislovecnm** [comment] 2015-11-28 02:29
@eloycoto let us know if we can help, but this is kinda a VMware thing, not a terraform related issue. Can we please close this?

**Comment by eloycoto** [comment] 2015-12-09 14:15
Hey @chrislovecnm

Sorry, very busy weeks. Yes, is Vmware thing, maybe we need to add this into Vsphere doc? What do you think?

If not people are going to use debian, and they will report issues, etc.. 

Regards

**Comment by chrislovecnm** [comment] 2015-12-11 16:03
@eloycoto Please update the docs! only VMware supported Linux versions. Something like that?

**Comment by chrislovecnm** [comment] 2016-04-15 21:08
@eloycoto can we get this documented or close this issue??

**Comment by chrislovecnm** [comment] 2016-04-19 17:56
@stack72 this is not a bug, but a documentation need 😄 

Please do as you please.  BTW APPRECIATE THE HELP!!!!!!!!

**Comment by eloycoto** [comment] 2016-04-22 16:14
Hey @chrislovecnm, 

Sorry my fault! I'll document this during the weekend. 

Regards.

**Comment by chrislovecnm** [comment] 2016-04-22 16:17
@eloycoto no worries!! Appreciate the help.

**Comment by thetuxkeeper** [comment] 2016-04-26 16:12
Hi,

since we ran into the same problem, I implemented a "skip_customization" setting which makes it possible to skip that part. We tested it with our CoreOS deployment (described in the pull request).

Regards

**Closed** 2016-04-29 18:00 UTC
Labels: bug, provider/vsphere
