### ISSUE TITLE
core: regression in 0.7: a problem with passing interpolated parameters to modules

### ISSUE THREAD

**Issue by modax** [hashicorp/terraform#7002] opened 2016-06-03 09:21 UTC
Hi,

I believe I found a bug in latest terraform 0.7 build which is not present in 0.6.16. This is a regression since terraform is no longer able to parse tf files which it used to parse before. It is probably related to support of lists and maps in the module parameters.

### Terraform Version
Build from git v0.7.0-rc1-53-gfcb952d

### Affected Resource(s)
Tested only with the following since it was the easiest:

* template_file

But I think it is a terraform core problem (see below).

### Terraform Configuration Files

mod/mod.tf
```hcl
variable "param" {}
```
test.tf
```hcl
resource "template_file" "tmpl" {
  count = "0"
  template = "abc"
}

module "mod" {
  source = "mod"
  param = "${join(",", template_file.tmpl.*.rendered)}"
}
```
### Expected Behavior
This is what terraform 0.6.16 returns when you run plan:
```
Refreshing Terraform state prior to plan...


No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

### Actual Behavior
This is what happens with terraform v0.7.0-rc1-53-gfcb952d
```
Error configuring: 1 error(s) occurred:

* At column 3, line 1: join: argument 1 should be TypeList, got TypeString in:

${join(",", template_file.tmpl.*.rendered)}
```

### Steps to Reproduce

1. `terraform get`
2. `terraform plan`

### Important Factoids
If you comment out module and add the following to the bottom of `test.tf`, everything works as expected. So it seems to be a problem with module parameters in particular.

```hcl
output "out" {
  value = "${join(",", template_file.tmpl.*.rendered)}"
}
```

What is more, `count` value does not seem to have any possible effect on this failure. `terraform plan` still fails in the same way.

**Comment by jen20** [comment] 2016-06-03 20:25
Hi @modax! This is indeed a regression - I found it personally via another means and will have it fixed shortly. Thanks for opening the issue and the detailed repro, I'm going to use this as the basis for the fix.

**Comment by jen20** [comment] 2016-06-03 20:27
(FWIW here the key to the repro is the count of 0 and the splat resource)

**Comment by modax** [comment] 2016-06-04 09:14
Are you sure about count = 0? Just retested with count = 1 and still fails the same way

**Comment by jen20** [comment] 2016-06-11 12:33
Hi @modax! It will fail with any count < 2, because of a missing conditional (previously everything was a string so it was never an issue). I have a fix in the works for this shortly.

**Comment by jen20** [comment] 2016-06-12 12:03
Hi @modax! I opened a PR which fixes this for the count = 0 case. I'll follow up with a fix for the count = 1 shortly.

**Comment by jen20** [comment] 2016-06-12 15:15
Closed this by accident.

**Comment by jen20** [comment] 2016-06-12 16:14
Hi @modax! It turns out that after the `count = 0` bug was fixed, the only remaining error (with count 1) is with the repro config:

```
resource "template_file" "tmpl" {
  count = "0"
  template = "abc"
}

module "mod" {
  source = "mod"
  param = "${join(",", template_file.tmpl.*.rendered)}"
}
```

The error message:

```
* At column 3, line 1: join: argument 1 should be TypeList, got TypeString in:
 ```

is actually correct: the signature for `join` is `list -> string`. Removing the join interpolation function leaves a different error message:

```
* module 'mod': use of the splat ('*') operator must be wrapped in a list declaration
```

Which is correct. Wrapping the value for `param` in `[ ]` braces then works correctly regardless of count.

Thanks for providing a clear repro of the count issue!

**Closed by jen20** 2016-06-12 16:14 UTC
Labels: bug, core, release-0.7

**Comment by modax** [comment] 2016-06-12 20:12
@jen20 I didn't fully understand your explanation about count=1. But whatever, I retested the snippet above with count=0, count=1, count=2 on current HEAD and it works! What's more, my production codebase works as well (which is where I noticed the problem initially). Thanks for fixing this! Looking forward to 0.7 in order to remove those joins and splits!
