### ISSUE TITLE
aws_cloudformation_stack: template_body not interpolated?

### ISSUE THREAD

**Issue by alsonkemp** [hashicorp/terraform#5462] opened 2016-03-04 21:31 UTC
I'm on 0.6.12.  I have the following resource:

    resource "aws_cloudformation_stack" "app_cloudfront" { 
      name = "app_cloudfront" 
      template_body = "${template_file.web_app_cloudfront.rendered}" 
    } 

I'm getting JSON errors, so I added a debug printf to terraform's normalizeJson to see how I had messed up the JSON.  The printf yielded the following:

    Results in: 2016/03/04 12:18:23 [DEBUG] terraform-provider-aws: 2016/03/04 12:18:23 [DEBUG] JSON STRING: ${template_file.web_app_cloudfront.rendered} 

So it appears that the template_body was not interpolated?

**Comment by phinze** [comment] 2016-03-04 23:06
Hi @alsonkemp - sorry for the trouble here.

I just did a quick local test and was unable to reproduce the uninterpolated template_body on my first couple of tries. Here's the test config I'm working with:

```tf
resource "template_file" "networkstack" {
	template = <<STACK
{
  "Resources" : {
    "MyVPC": {
      "Type" : "AWS::EC2::VPC",
      "Properties" : {
        "CidrBlock" : "10.0.0.0/16",
        "Tags" : [
          {"Key": "Name", "Value": "Primary_CF_VPC"}
        ]
      }
    }
  },
  "Outputs" : {
    "DefaultSgId" : {
      "Description": "The ID of default security group",
      "Value" : { "Fn::GetAtt" : [ "MyVPC", "DefaultSecurityGroup" ]}
    },
    "VpcID" : {
      "Description": "The VPC ID",
      "Value" : { "Ref" : "MyVPC" }
    }
  }
}
STACK
}

resource "aws_cloudformation_stack" "network" {
  name          = "tf-networking-stack"
  template_body = "${template_file.networkstack.rendered}"
}
```

Do you see any differences between that test config and yours that might be key to reproducing this bug?

**Comment by alsonkemp** [comment] 2016-03-05 00:32
@phinze The thick plottens...  I have the same error when running your sample.  FWIW, I'm on Debian Testing (and fairly up-to-date).  See below.

```
/tmp/terraform-test
alson@tortugita : 04:28 PM : $ cat test.tf 
# Configure the AWS Provider
provider "aws" {
    access_key = "access"
    secret_key = "secret"
    region = "us-east-1"
}


resource "template_file" "networkstack" {
    template = <<STACK
{
  "Resources" : {
    "MyVPC": {
      "Type" : "AWS::EC2::VPC",
      "Properties" : {
        "CidrBlock" : "10.0.0.0/16",
        "Tags" : [
          {"Key": "Name", "Value": "Primary_CF_VPC"}
        ]
      }
    }
  },
  "Outputs" : {
    "DefaultSgId" : {
      "Description": "The ID of default security group",
      "Value" : { "Fn::GetAtt" : [ "MyVPC", "DefaultSecurityGroup" ]}
    },
    "VpcID" : {
      "Description": "The VPC ID",
      "Value" : { "Ref" : "MyVPC" }
    }
  }
}
STACK
}

resource "aws_cloudformation_stack" "network" {
  name          = "tf-networking-stack"
  template_body = "${template_file.networkstack.rendered}"
}



/tmp/terraform-test
alson@tortugita : 04:28 PM : $ terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_cloudformation_stack.network
    name:          "" => "tf-networking-stack"
    outputs.#:     "" => "<computed>"
    parameters.#:  "" => "<computed>"
    policy_body:   "" => "<computed>"
    template_body: "" => "Error parsing JSON: invalid character '$' looking for beginning of value"

+ template_file.networkstack
    rendered: "" => "<computed>"
    template: "" => "{\n  \"Resources\" : {\n    \"MyVPC\": {\n      \"Type\" : \"AWS::EC2::VPC\",\n      \"Properties\" : {\n        \"CidrBlock\" : \"10.0.0.0/16\",\n        \"Tags\" : [\n          {\"Key\": \"Name\", \"Value\": \"Primary_CF_VPC\"}\n        ]\n      }\n    }\n  },\n  \"Outputs\" : {\n    \"DefaultSgId\" : {\n      \"Description\": \"The ID of default security group\",\n      \"Value\" : { \"Fn::GetAtt\" : [ \"MyVPC\", \"DefaultSecurityGroup\" ]}\n    },\n    \"VpcID\" : {\n      \"Description\": \"The VPC ID\",\n      \"Value\" : { \"Ref\" : \"MyVPC\" }\n    }\n  }\n}\n"


Plan: 2 to add, 0 to change, 0 to destroy.

/tmp/terraform-test
alson@tortugita : 04:28 PM : $ terraform version
Terraform v0.6.12

```

**Comment by alsonkemp** [comment] 2016-03-05 00:42
I'll try this in the Vagrant VM...

**Comment by alsonkemp** [comment] 2016-03-05 01:25
I had the same failure in the Vagrant VM.  

```
vagrant@terraform:~$ cd /opt/gopath/src/github.com/hashicorp/terraform/
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make quickdev
vagrant@terraform:/tmp/terraform-test$ vi test.tf
vagrant@terraform:/tmp/terraform-test$ terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_cloudformation_stack.network
    name:          "" => "tf-networking-stack"
    outputs.#:     "" => "<computed>"
    parameters.#:  "" => "<computed>"
    policy_body:   "" => "<computed>"
    template_body: "" => "Error parsing JSON: invalid character '$' looking for beginning of value"

+ template_file.networkstack
    rendered: "" => "<computed>"
    template: "" => "{\n  \"Resources\" : {\n    \"MyVPC\": {\n      \"Type\" : \"AWS::EC2::VPC\",\n      \"Properties\" : {\n        \"CidrBlock\" : \"10.0.0.0/16\",\n        \"Tags\" : [\n          {\"Key\": \"Name\", \"Value\": \"Primary_CF_VPC\"}\n        ]\n      }\n    }\n  },\n  \"Outputs\" : {\n    \"DefaultSgId\" : {\n      \"Description\": \"The ID of default security group\",\n      \"Value\" : { \"Fn::GetAtt\" : [ \"MyVPC\", \"DefaultSecurityGroup\" ]}\n    },\n    \"VpcID\" : {\n      \"Description\": \"The VPC ID\",\n      \"Value\" : { \"Ref\" : \"MyVPC\" }\n    }\n  }\n}\n"


Plan: 2 to add, 0 to change, 0 to destroy.
```

**Comment by radeksimko** [comment] 2016-03-06 10:55
I was able to reproduce this and I have a strong feeling (admittedly I can't confirm) it can be solved via https://github.com/hashicorp/terraform/pull/4961

**Comment by alsonkemp** [comment] 2016-03-07 23:14
@radeksimko Might be a race condition, but, across 3 machines, I've hit it on 100% of runs.  Do you know of any workarounds?

On a second note, why does aws_cloudformation_stack swallow the template error?

**Comment by alsonkemp** [comment] 2016-03-09 02:09
@phinze Can you provide any indications of where the bug might be?  I'm not a golang-nut, but I might be able to help.

**Comment by phinze** [comment] 2016-03-25 21:18
Still no repro here - @alsonkemp can you confirm you hit this on 0.6.14 as well?

**Comment by alsonkemp** [comment] 2016-03-25 21:35
@phinze You were not able to get my repro from https://github.com/hashicorp/terraform/issues/5462#issuecomment-192543760 to work?  I have not re-tried against 0.6.14.  I will do so soon.

**Comment by alsonkemp** [comment] 2016-03-25 21:45
Still seeing the same error.   

```
~/projects/terraform-test
alson@tortugita : 02:43 PM : $ cat test.tf 
# Configure the AWS Provider
provider "aws" {
    access_key = "###"
    secret_key = "###"
    region = "us-east-1"
}


resource "template_file" "networkstack" {
    template = <<STACK
{
  "Resources" : {
    "MyVPC": {
      "Type" : "AWS::EC2::VPC",
      "Properties" : {
        "CidrBlock" : "10.0.0.0/16",
        "Tags" : [
          {"Key": "Name", "Value": "Primary_CF_VPC"}
        ]
      }
    }
  },
  "Outputs" : {
    "DefaultSgId" : {
      "Description": "The ID of default security group",
      "Value" : { "Fn::GetAtt" : [ "MyVPC", "DefaultSecurityGroup" ]}
    },
    "VpcID" : {
      "Description": "The VPC ID",
      "Value" : { "Ref" : "MyVPC" }
    }
  }
}
STACK
}

resource "aws_cloudformation_stack" "network" {
  name          = "tf-networking-stack"
  template_body = "${template_file.networkstack.rendered}"
}


~/projects/terraform-test
alson@tortugita : 02:43 PM : $ terraform version
Terraform v0.6.14


~/projects/terraform-test
alson@tortugita : 02:43 PM : $ terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_cloudformation_stack.network
    name:          "" => "tf-networking-stack"
    outputs.#:     "" => "<computed>"
    parameters.#:  "" => "<computed>"
    policy_body:   "" => "<computed>"
    template_body: "" => "Error parsing JSON: invalid character '$' looking for beginning of value"

+ template_file.networkstack
    rendered: "" => "<computed>"
    template: "" => "{\n  \"Resources\" : {\n    \"MyVPC\": {\n      \"Type\" : \"AWS::EC2::VPC\",\n      \"Properties\" : {\n        \"CidrBlock\" : \"10.0.0.0/16\",\n        \"Tags\" : [\n          {\"Key\": \"Name\", \"Value\": \"Primary_CF_VPC\"}\n        ]\n      }\n    }\n  },\n  \"Outputs\" : {\n    \"DefaultSgId\" : {\n      \"Description\": \"The ID of default security group\",\n      \"Value\" : { \"Fn::GetAtt\" : [ \"MyVPC\", \"DefaultSecurityGroup\" ]}\n    },\n    \"VpcID\" : {\n      \"Description\": \"The VPC ID\",\n      \"Value\" : { \"Ref\" : \"MyVPC\" }\n    }\n  }\n}\n"


Plan: 2 to add, 0 to change, 0 to destroy.

```

**template_body:** "" => "Error parsing JSON: invalid character '$' looking for beginning of value"**

**Comment by radeksimko** [comment] 2016-03-25 22:52
See https://github.com/hashicorp/terraform/issues/3076 which I believe is caused by the same bug.

**Comment by comerford** [comment] 2016-05-09 19:18
Can confirm that I am seeing this with 0.6.15 too - plan errors parsing the JSON but the apply succeeds and is using the correct policy

**Comment by mitchellh** [comment] 2016-10-28 23:49
This is fixed on master as I also can't reproduce the exact copy/paste example above (even using the deprecated template_file resource). Closing!

**Closed by mitchellh** 2016-10-28 23:49 UTC
Labels: bug, core

**Comment by puttagunta** [comment] 2018-03-22 16:46
I found this issue today, when I'm trying to populate "template_body" of the resource, "azurerm_template_deployment", with the rendered content of a template. The plan failed with the message, "Error parsing JSON: invalid character '$' looking for beginning of value", but the apply succeded.
Terraform version: 0.11.4
