### ISSUE TITLE
Import fails when countable module is present, despite import resource not being in countable module

### ISSUE THREAD

**Issue by Zordrak** [hashicorp/terraform#25854] opened 2020-08-14 14:07 UTC
### Terraform Version

```
0.13.0
```

### Details

Command:

`terraform import module.bs_iam.aws_iam_user.matrix[\"username@domain\"] username@domain`

Importing an existing user called username@domain into a for_each resource called aws_iam_user.matrix in the module "bs_iam".

Code is perfectly fine during plan/apply.

Import graph constructor fails when trying to enumerate an unrelated countable module called module.bs_gr.module.bs_gr_r_ap-northeast-1 which uses count to enable or disable the module.

```
Terraform has been successfully initialized!
module.bs_iam.aws_iam_user.matrix["username@domain"]: Importing from ID "username@domain"...
module.bs_iam.aws_iam_user.matrix["username@domain"]: Import prepared!
  Prepared aws_iam_user for import
module.bs_iam.aws_iam_user.matrix["username@domain"]: Refreshing state... [id=username@domain]

Error: Invalid count argument

  on ../../modules/bs-gr/module_bs_gr_r_ap-northeast-1.tf line 11, in module "bs_gr_r_ap-northeast-1":
  11:   count = contains(local.multiball_multiball_multiball, "ap-northeast-1") == true ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

Commenting out the unrelated countable module allows the import to succeed.

**Comment by Zordrak** [comment] 2020-08-14 14:17
`terraform console` generates the same error

**Comment by danieldreier** [comment] 2020-08-14 17:57
@Zordrak I'm wondering if this is a similar issue to https://github.com/hashicorp/terraform/issues/25816 - it looks to me like you're trying to index `module.bs_iam.aws_iam_user.matrix` on `username@domain` rather than on a number, which is what count expects.

**Comment by danburkhol** [comment] 2020-08-14 21:44
I can confirm this behavior as well

Command
`terraform import module.develop.module.cloudwatch_alarms.aws_cloudwatch_metric_alarm.foobar alarm-foobar`

Output
```
module.develop.module.cloudwatch_alarms.aws_cloudwatch_metric_alarm.foobar: Importing from ID "alarm-foobar"...
module.develop.module.cloudwatch_alarms.aws_cloudwatch_metric_alarm.foobar: Import prepared!
  Prepared aws_cloudwatch_metric_alarm for import
module.develop.module.cloudwatch_alarms.aws_cloudwatch_metric_alarm.foobar: Refreshing state... [id=alarm-foobar]

Error: Invalid count argument

  on terraform/phonism/networking/networking.tf line 105, in module "frontend_listener_rules":
 105:   count = length(module.frontend_listeners.listener_arns)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```


`terraform apply` or `terraform plan` contiunes to work correctly

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.develop.module.cloudwatch_alarms.aws_cloudwatch_metric_alarm.foobar will be created
  + resource "aws_cloudwatch_metric_alarm" "foobar" {
      + actions_enabled                       = true
      + alarm_description                     = "This metric monitors ec2 cpu utilization"
      + alarm_name                            = "develop-us-tg-phone-request-anomaly"
      + arn                                   = (known after apply)
      + comparison_operator                   = "GreaterThanOrEqualToThreshold"
      + evaluate_low_sample_count_percentiles = (known after apply)
      + evaluation_periods                    = 2
      + id                                    = (known after apply)
      + metric_name                           = "RequestCountPerTarget"
      + namespace                             = "AWS/EC2"
      + period                                = 60
      + statistic                             = "Sum"
      + threshold                             = 80
      + treat_missing_data                    = "missing"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

**Comment by mildwonkey** [comment] 2020-08-19 14:40
This does appear to be a duplicate of #25816, so I will label it as such and close it. If this turns out to be incorrect we can re-open it. Thanks!

**Closed** 2020-08-19 14:40 UTC
Labels: bug, duplicate, new
