### ISSUE TITLE
unlink_dependency argument for template_file from aws_instance

### ISSUE THREAD

**Issue by meylor** [hashicorp/terraform#3298] opened 2015-09-22 06:43 UTC
The `aws_instance` resource has the argument `user_data` which takes a `template_file` ID. The template_file gets included in the dependency graph during a `terraform plan` or `terraform apply`. Within AWS `user_data` is data that is passed in at provisioning time; I would think that if the `user_data` changes, this should not necessarily require a resource to be destroyed/created. 

I was wondering if it would make sense to add an argument such as `unlink_dependency = "true"` that would disassociate the `template_file` from the `aws_instance` that references it. My use case is that I want to be able to modify the user_data script and only get the changes when an aws_instance is newly created. 

```
resource "template_file" "web" {
  unlink_dependency = "true"
  filename = "user_data"
  vars {
    node = "web"
    region = "${var.region}"
    env = "dev"
  }
}

resource "aws_instance" "web" {
    ami = "${lookup(var.ami, "web")}"
    vpc_security_group_ids = ["${aws_security_group.web.id}"]
    instance_type = "${lookup(var.instance-type, "web")}"
    key_name = "${var.key_name}"
    subnet_id = "${aws_subnet.web.id}"
    iam_instance_profile = "web"
    tags = {
        Name = "web"
    }
    user_data = "${template_file.web.rendered}"
}
```

**Comment by apparentlymart** [comment] 2015-09-24 18:43
I guess the assumption here is that changing the ``user_data`` of an already-running instance would not have any effect, so therefore it's logical that if you changed it you'd want to restart the machine to make use of it.

It sounds like you have a use-case for changing the user_data without restarting... could you elaborate a little on what that is? The thing that sprang to my mind was that you might have something outside of Terraform rebooting your instances periodically and you want the ``user_data`` change to take place only at that reboot.

One possible workaround is to use a ``remote-exec`` provisioner instead of ``user_data`` to do whatever startup actions you want to do. By design Terraform provisioners happen only on initial resource creation and are ignored for already-existing instances, so assuming you don't have anything outside of Terraform messing with your machines that should be (largely) functionally equivalent to having a ``user_data`` that doesn't restart the instance. I guess the main difference is that cloud-init (the usual user of ``user_data``) runs pretty early in the boot process, whereas provisioners will run at a less-predictable later time once the system has booted enough to have ``sshd`` running.

**Comment by apparentlymart** [comment] 2015-09-24 18:45
Oh, and addressing your proposal directly: I think it would fit better into Terraform's model for the attribute to be on the instance rather than the template, so you'd tell the instance to ignore ``user_data`` changes (however they get set) after the resource is created.

However, AFAIK that sort of functionality doesn't really fit into the "schema" structure that these resources use, where a given attribute either *always* forces a new resource or  *never* does, decided at provider initialization time. It would require some refactoring to support an attribute that only forces a new resource conditionally based on the value of another attribute.

**Comment by apparentlymart** [comment] 2018-11-06 23:16
Hi @meylor! Sorry for the long silence here.

(When I commented before I was a community contributor to Terraform, but these days I work full time on the Terraform Core team.)

In the mean time we've added support for the `ignore_changes` lifecycle setting to allow for use-cases like this:

```hcl
resource "aws_instance" "web" {
  ami = "${lookup(var.ami, "web")}"
  vpc_security_group_ids = ["${aws_security_group.web.id}"]
  instance_type = "${lookup(var.instance-type, "web")}"
  key_name = "${var.key_name}"
  subnet_id = "${aws_subnet.web.id}"
  iam_instance_profile = "web"
  tags = {
    Name = "web"
  }
  user_data = "${template_file.web.rendered}"

  lifecycle {
    ignore_changes = ["user_data"]
  }
}
```

When an argument name is given in `ignore_changes`, Terraform will use the configuration value during create but will always take the prior value from state during subsequent planning, which effectively prevents the default behavior of re-creating an instance when its `user_data` changes.

Since this use-case now has a solution, I'm going to close this out. Sorry for leaving this unclosed for so long.

**Closed by apparentlymart** 2018-11-06 23:16 UTC
Labels: config, enhancement
