### ISSUE TITLE
Inconsistent list element types

### ISSUE THREAD

**Issue by cyrus-mc** [hashicorp/terraform#21688] opened 2019-06-11 15:52 UTC
### Terraform Version

```
› terraform -v
Terraform v0.12.1
+ provider.aws v2.14.0
```

### Terraform Configuration Files
```hcl
resource aws_subnet "main" {
  count = 2

  vpc_id = "vpc-xxxxxxxx"
  cidr_block = format("10.150.%d.0/16", (count.index + 1))
}

module "unit-test01" {
  source = "../"

  resource_share = [
    {
      name = "SomeShare"
      allow_external_principals = false
      principal_arn = "arn:aws:organizations::xxxxxxx:ou/o-ji0wv1xxxxx/ou-qm6z-yxxxxx"
      resource_arn  = [ "arn:aws:ec2:us-west-2:xxxxxxx:subnet/subnet-7732xxxx",
                        "arn:aws:ec2:us-west-2:xxxxxxx:subnet/subnet-5a30xxxx" ]
    },
    {
      name = "SomeShare2"
      allow_external_principals = true
      principal_arn = "11111"
      resource_arn = aws_subnet.main.*.arn
    }
  ]
}
```

### Crash Output

```
panic: inconsistent list element types (cty.Object(map[string]cty.Type{"allow_external_principals":cty.Bool, "name":cty.String, "principal_arn":cty.String, "resource_arn":cty.Tuple([]cty.Type{cty.String, cty.String})}) then cty.Object(map[string]cty.Type{"allow_external_principals":cty.Bool, "name":cty.String, "principal_arn":cty.String, "resource_arn":cty.DynamicPseudoType}))
```

### Expected Behavior

You should be able to set a complex type that includes both static and interpolated values. 

### Actual Behavior

Terraform crashes due to inconsistent list element types.

**Comment by jbardin** [comment] 2019-06-20 19:48
Thanks for filing this @cyrus-mc,
It appears to be a duplicate of #21588, so I"ll close this to track the issue in one place.

**Closed by jbardin** 2019-06-20 19:48 UTC
Labels: bug, config, crash
