### ISSUE TITLE
Crash: terraform init with AWS provider as only module

### ISSUE THREAD

**Issue by ding44** [hashicorp/terraform#24387] opened 2020-03-16 20:00 UTC
### Terraform Version

```
Terraform v0.12.23
```

### Terraform Configuration Files

```hcl
#main.tf

provider "aws" {
  region = "us-east-1"
}
```

### Crash Output

2020/03/16 19:53:49 [INFO] Terraform version: 0.12.23  
2020/03/16 19:53:49 [INFO] Go runtime version: go1.12.13
2020/03/16 19:53:49 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/03/16 19:53:49 [DEBUG] Attempting to open CLI config file: /home/ec2-user/.terraformrc
2020/03/16 19:53:49 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/03/16 19:53:49 [INFO] CLI command args: []string{"init"}
2020/03/16 19:53:49 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/03/16 19:53:49 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/03/16 19:53:49 [DEBUG] New state was assigned lineage "6b7d9858-f525-deb2-ef1f-7b552a3baacd"
2020/03/16 19:53:49 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/03/16 19:53:49 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/03/16 19:53:49 [DEBUG] checking for provider in "."
2020/03/16 19:53:49 [DEBUG] checking for provider in "/usr/local/bin"
2020/03/16 19:53:49 [DEBUG] checking for provisioner in "."
2020/03/16 19:53:49 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/03/16 19:53:49 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2020/03/16 19:53:49 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/03/16 19:53:49 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/03/16 19:53:49 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/03/16 19:53:49 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/03/16 19:53:49 [TRACE] statemgr.Filesystem: read nil snapshot
2020/03/16 19:53:49 [DEBUG] checking for provider in "."
2020/03/16 19:53:49 [DEBUG] checking for provider in "/usr/local/bin"
2020/03/16 19:53:49 [DEBUG] plugin requirements: "aws"=""
2020/03/16 19:53:49 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/03/16 19:53:49 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2020/03/16 19:53:49 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/aws/versions"
2020/03/16 19:53:49 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/aws/versions
2020/03/16 19:54:00 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/aws/versions
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd0c90a]

goroutine 1 [running]:
github.com/hashicorp/terraform/registry.maxRetryErrorHandler(0x0, 0x232e4e0, 0xc00056fda0, 0x2, 0x3, 0x3, 0x232e4e0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:422 +0xea
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc00049cd80, 0xc0004f0670, 0x1e8df81, 0x13, 0xc0000d5528)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.5.2/client.go:452 +0x706
github.com/hashicorp/terraform/registry.(*Client).TerraformProviderVersions(0xc000508980, 0xc00044e4b0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:305 +0x467
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).listProviderVersions(0xc0004d8690, 0xc000446930, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0xc000052570, 0xc000052500, 0xc000548ca8)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:477 +0x7e
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).Get(0xc0004d8690, 0xc000446930, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0x3523918, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:125 +0xde
github.com/hashicorp/terraform/command.(*InitCommand).getProviders(0xc000505880, 0xc0004d87e0, 0x0, 0x0, 0xc000448300, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:530 +0x4c5
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000505880, 0xc00000c090, 0x0, 0x0, 0xc0004422b0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:347 +0x102d
github.com/mitchellh/cli.(*CLI).Run(0xc0004d4280, 0xc0004d4280, 0xc000231d90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:239 +0xc33
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:103 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:39 +0x3b

### Expected Behavior

Terraform initializes the directory and installs AWS provider

### Actual Behavior

Terraform crashed.

### Steps to Reproduce

`terraform init`

**Comment by paultyng** [comment] 2020-03-17 12:54
Duplicate of #24384

**Closed by paultyng** 2020-03-17 12:54 UTC
Labels: bug, crash
