### ISSUE TITLE
config: Crash in version 0.9.5 in interpolationWalker.Primitive

### ISSUE THREAD

**Issue by vamsirede** [hashicorp/terraform#15319] opened 2017-06-16 16:57 UTC
Crash occurred when i tried the below  code:

```hcl
resource "aws_vpc" "main" {
  cidr_block = "${var.cidr_range}"
  tags { 
    "${var.key}" = "${var.value}"
  }
}
output "vpc_id" {
    value = "${aws_vpc.main.id}"
}
variable "cidr_range" {}
variable "key" {
  type = "map"
}
variable "value" {
  type = "map"
}
module "vpc" {
  source     = "../modules/vpc/" 
  cidr_range = "10.200.0.0/16"
  key {
    a = "cost-allocation"
    b = "Name" 
  }
  value {
    a = "example1"
    b = "example_vpc"
  }
}
```

```
panic: reflect.Value.SetMapIndex: value of type map[string]interface {} is not assignable to type string

goroutine 619 [running]:
reflect.Value.assignTo(0x4761180, 0xc4208678f0, 0x15, 0x51825fa, 0x19, 0x4405400, 0x0, 0x4405400, 0xc420186740, 0x98)
	/opt/go/src/reflect/value.go:2175 +0x307
reflect.Value.SetMapIndex(0x4761180, 0xc4208d01d8, 0x195, 0x4761180, 0xc4208678f0, 0x15, 0x46a4c40, 0xc420186750, 0x94)
	/opt/go/src/reflect/value.go:1468 +0xb4
github.com/hashicorp/terraform/config.(*interpolationWalker).Primitive(0xc420872540, 0x4405400, 0xc420186740, 0x98, 0xc420872540, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/config/interpolate_walk.go:189 +0x38a
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkPrimitive(0x4405400, 0xc420186740, 0x98, 0x4d33560, 0xc420872540, 0x3d094f4cc00, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:240 +0x80
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x4405400, 0xc420186740, 0x98, 0x4d33560, 0xc420872540, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:171 +0x23f
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkMap(0x4761180, 0xc4208d01d8, 0x195, 0x4d33560, 0xc420872540, 0x3d094f4cc00, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:213 +0x270
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x4761180, 0xc4208d01d8, 0x195, 0x4d33560, 0xc420872540, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:174 +0x2f8
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkSlice(0x438f280, 0xc4207bdd20, 0x97, 0x4d33560, 0xc420872540, 0x97, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:272 +0x202
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x46a4c40, 0xc4201866b0, 0x94, 0x4d33560, 0xc420872540, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:177 +0x4e8
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkMap(0x4761180, 0xc420867260, 0x15, 0x4d33560, 0xc420872540, 0x3d094f4cc00, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:222 +0x2d2
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walk(0x4761180, 0xc420867260, 0x15, 0x4d33560, 0xc420872540, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:174 +0x2f8
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.Walk(0x4761180, 0xc420867260, 0x4d33560, 0xc420872540, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk/reflectwalk.go:84 +0x131
github.com/hashicorp/terraform/config.(*RawConfig).interpolate(0xc4207eed20, 0xc420757eb0, 0xc4207eed58, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/raw_config.go:233 +0xea
github.com/hashicorp/terraform/config.(*RawConfig).Interpolate(0xc4207eed20, 0xc420866ff0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/raw_config.go:138 +0xe5
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).Interpolate(0xc4206fc000, 0xc4207eed20, 0xc420245720, 0x0, 0x0, 0x32)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:304 +0x10f
github.com/hashicorp/terraform/terraform.(*EvalInterpolate).Eval(0xc4207bda40, 0x7af2c20, 0xc4206fc000, 0x2, 0x2, 0xc420757a08, 0x8)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_interpolate.go:14 +0x4b
github.com/hashicorp/terraform/terraform.EvalRaw(0x7ac0300, 0xc4207bda40, 0x7af2c20, 0xc4206fc000, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc4207bda60, 0x7af2c20, 0xc4206fc000, 0x2, 0x2, 0xc4207579d0, 0x8)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/hashicorp/terraform/terraform.EvalRaw(0x7ac05c0, 0xc4207bda60, 0x7af2c20, 0xc4206fc000, 0x46a0740, 0xc420757638, 0x4405400, 0xc4207579b0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.Eval(0x7ac05c0, 0xc4207bda60, 0x7af2c20, 0xc4206fc000, 0xc4207bda60, 0x7ac05c0, 0xc4207bda60, 0x200000003)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x4ea8f80, 0xc4208d0050, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xd4d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc420271420, 0x4ea8f80, 0xc4208d0050, 0xc4208012c0)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x392
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x9ca
```

**Comment by jbardin** [comment] 2017-06-30 14:59
Hi @vamsirede,

I'm working on reproducing this bug, but it relies on the content of your vpc module. Can you share that config as well?

**Comment by jbardin** [comment] 2017-06-30 15:09
@vamsirede 

Thanks for filing the issue, along with your configuration. I've been able to reproduce this in both the 0.9 branch as well as 0.10.

**Comment by vamsirede** [comment] 2017-06-30 15:23
@jbardin 
tags { 
    "${var.key}" = "${var.value}"
 }
the above code caused the crash.

**Comment by jbardin** [comment] 2017-06-30 17:31
Thanks, I missed that the first time around. 
Yes, interpolating a map as the key ins't going to work, but shouldn't crash.

We'll work on mitigating this.

**Comment by apparentlymart** [comment] 2018-11-20 01:40
Hi @vamsirede! Sorry for the long silence here.

The problem that caused the crash here was that the variables `key` and `value` both have `type = "map"`, and so when Terraform attempted to assign the tag value from `"${var.value}"` it got a map instead of a string. It should've returned a type mismatch error here rather than crashing.

Another problem in this configuration is that Terraform v0.11 and prior did not support dynamically-built map keys like `"${var.key}"`. Had this not crashed, Terraform would've attempted to create a tag literally called `${var.key}`, which would then have failed with a tag name syntax error from AWS.

Finally, `var.key` itself is typed as a map rather than a string, so if Terraform _had_ tried to construct that map with a dynamic key it would've failed anyway because the map key is not a string.

In the master branch, ready for the forthcoming v0.12.0 release, we have a proper error message for the first problem and we now have support for arbitrary expressions as map keys for the second problem. There's also validation that the map key must be a string, which is the first problem I saw verifying against the v0.12.0-alpha2 prerelease build:

```
$ terraform plan

Error: Incorrect key type

  on dynamic-map-keys-crash.tf line 8, in resource "aws_vpc" "main":
   8:     "${var.key}" = "${var.value}"
    |----------------
    | var.value is map of number with 1 element

Can't use this value as a key: string required.
```

I fixed the issues above to create the following similar configuration:

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "main" {
  cidr_block = "${var.cidr_range}"
  tags = {
    "${var.key}" = "${var.value}"
  }
}

output "vpc_id" {
  value = "${aws_vpc.main.id}"
}

variable "cidr_range" {
  default = "10.1.0.0/16"
}

variable "key" {
  default = "foo"
}

variable "value" {
  default = "bar"
}
```

With this configuration I was able to plan the operation successfully, with tags `"foo" = "bar"` because of the default values I chose here.

By changing the `value` variable temporarily back to a map I was able to verify also that I got a proper error message about the type mismatch rather than a crash.

Since the crashing bug is fixed in master, I'm going to close this out. Thanks for reporting this, and sorry for the delay in getting it fixed.

**Closed by apparentlymart** 2018-11-20 01:40 UTC
Labels: bug, config, crash
