### ISSUE TITLE
Terraform output when resource count 0

### ISSUE THREAD

**Issue by akdasari** [hashicorp/terraform#22266] opened 2019-07-31 10:18 UTC
trying to output as below
```
output "aspResourceID" {
  value = "${lookup(azurerm_template_deployment.app_service_plan.outputs, "aspResourceID", "No ASP")}"
}
```

when creating resource I can see "azurerm_template_deployment.app_service_plan" resource and can get output. But when destroying this resource I get  empty resource and the above condition fails.
---------------
when provisioned: statefile looks like 
```
"{
            "path": [
                "root",
                "appServicePlan"
            ],
            "outputs": {
                "aspResourceID": {
                    "sensitive": false,
                    "type": "string",
                    "value": "/subscriptions/de308a5c-0624-4334-8ff8-8dfe9fd43783/resourceGroups/my-resource-group/providers/Microsoft.Web/serverfarms/sandbox"
                }
            },
            "resources": {
                "azurerm_template_deployment.app_service_plan": {
                    "type": "azurerm_template_deployment",
                    "depends_on": [
                        "data.template_file.deployASP",
                        "local.asp_name"
                    ],
                    "primary": { ......
```
---------------------------------------

when delete resource -  state file contains as follows
--------------------
```
"{
            "path": [
                "root",
                "appServicePlan"
            ],
            "outputs": {
                "aspResourceID": {
                    "sensitive": false,
                    "type": "string",
                    "value": "No ASP"
                }
            },
            "resources": {},
            "depends_on": []
        },
```
-------------------------
How to pass terraform apply successfully in both cases

**Comment by teamterraform** [comment] 2019-07-31 14:28
Hi @akdasari !
I edited your comment, but only to fix formatting (it works better when you have new lines before and after the backticks).

To better understand this issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.
 - version of terraform used (`terraform -version`)
 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by akdasari** [comment] 2019-08-01 09:26
I found an issue similar to mine
https://github.com/hashicorp/terraform/issues/18026
as mentioned above 
"terraform_version": "0.11.7"

**Comment by teamterraform** [comment] 2019-08-01 11:04
There is a workaround for #18026 that may help you since you're using Terraform 0.11.7: https://github.com/hashicorp/terraform/issues/18026#issuecomment-446472197

Since this issue looks like a duplicate of #18026, I'm going to close it for now. Please reopen it and add the details requested above if you think this is not the same problem.

**Closed by teamterraform** 2019-08-01 11:04 UTC
