### ISSUE TITLE
datadog_monitor attrib include_tags = false does not uncheck include_tags

### ISSUE THREAD

**Issue by Gary-Armstrong** [hashicorp/terraform#10881] opened 2016-12-21 16:02 UTC
Using `include_tags = false` is not actually unchecking the box on the GUI [`Include triggering tags in notification title`] and I still must suffer through the unwanted tags in alert titles.  This affects both old and new monitors, meaning that it doesn't alter existing monitors nor create new ones properly.

### Terraform Version
0.7.7 & 0.8.1

### Affected Resource(s)
- datadog_monitor

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "dd-agent_reporting" {
  name = "Datadog Agent Not Reporting {{host.name}} [TF]"
  type = "service check"
  query = "query.stuff"
  notify_no_data = true
  no_data_timeframe = 2
  renotify_interval = 20
  thresholds { }
  include_tags = false
  message = <<EOF
stuff
EOF
}
```

### Debug Output
Let me know what you want to see here.  TF happily reports no errors.

### Expected Behavior
I expect that DD will not `Include triggering tags in notification title`

### Actual Behavior
DD does `Include triggering tags in notification title`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Nothing that I am aware of.  I'd like to know what is important and impactful in this scenario.

**Comment by ojongerius** [comment] 2017-02-21 02:31
AFAICS this is a duplicate of https://github.com/hashicorp/terraform/issues/10264

**Closed** 2017-02-22 17:37 UTC
Labels: bug, provider/datadog
