### ISSUE TITLE
Count Attribute in Resource  → Import always success

### ISSUE THREAD

**Issue by MB175** [hashicorp/terraform#32499] opened 2023-01-11 16:58 UTC
### Terraform Version

```shell
Terraform v1.3.7
```

### Terraform Configuration Files

resource "client_xy" "client_ab" {
name = "test"
count = 1
}

### Debug Output

No Errors 

### Expected Behavior

│ Error: Ciddas client_xy: 1234 error: 204 No Content, 204
│ 
│ 

### Actual Behavior

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

### Steps to Reproduce

terraform init
terraform import client_xy.client_ab 1234

### Additional Context

Tried on multiple providers, using the count attribute in a resource and trying to import will lead to a crash in the sdk which results in an always successful import with empty state

**Comment by jbardin** [comment] 2023-01-11 17:01
Duplicate of #32329

**Closed by jbardin** 2023-01-11 17:01 UTC
Labels: bug, new
