### ISSUE TITLE
Panic: interface conversion: interface {} is string, not map[string]interface {}

### ISSUE THREAD

**Issue by erlarson85** [hashicorp/terraform#15855] opened 2017-08-18 15:37 UTC
# PROVIDER ISSUES

**PLEASE NOTE:** Terraform has split out the builtin Providers into their own repositories. For any Provider issues, please open all issues and pull requests in the corresponding repository. An index of supported Providers can be found here:

- https://github.com/terraform-providers

All other issues (that appear to affect multiple or all providers) may be an issue with Terraform's core, and should be opened here. 

------

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v.0.9.8 v0.10.0 v0.10.2

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here 
There are 19 files, trying to figure out a way to scrub and upload, specific files can be put up easily.


```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
[https://gist.github.com/erlarson85/c3cb2d5ef0233f350c2e520ee8bb9937#file-crash-log](url)
Panic Console:
[https://gist.github.com/erlarson85/8b9c610e90604ce4c646339b924705c5](url)

### Expected Behavior
$terraform plan should run and complete

### Actual Behavior
1 Specific config file is causing this crash across the versions I have check. I have attempted to comment out bits of the file, and the entire file.

This file causes the crash (www-haproxy-2.tf):
`resource "aws_launch_configuration" "www_haproxy_2" {
  name_prefix                 = "${var.www_tag_prefix}-haproxy-"
  image_id                    = "${var.www_haproxy_2_ami_id}"
  instance_type               = "m3.medium"
  iam_instance_profile        = "Web"
  key_name                    = "asuwwwvpc"
  security_groups             = ["${aws_security_group.www_haproxy.id}"]
  associate_public_ip_address = false

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "www_haproxy_2" {
  name                      = "${var.www_tag_prefix}-haproxy-2"
  min_size                  = 1
  max_size                  = 2
  desired_capacity          = 2
  health_check_type         = "ELB"
  health_check_grace_period = 300
  launch_configuration      = "${aws_launch_configuration.www_haproxy_2.name}"
  load_balancers            = ["${aws_elb.www_haproxy_2.name}"]
  vpc_zone_identifier       = ["${data.aws_subnet.private.*.id}"]
  enabled_metrics           = ["GroupMinSize", "GroupMaxSize", "GroupDesiredCapacity", "GroupInServiceInstances", "GroupPendingInstances", "GroupStandbyInstances", "GroupTerminatingInstances", "GroupTotalInstances"]

  lifecycle {
    create_before_destroy = true
  }

  tags = ["${merge(module.tags.tags, map("Name", "${var.www_tag_prefix}-haproxy", "AnsibleManaged", "true", "propagate_at_launch", true))}"]
}

resource "aws_elb" "www_haproxy_2" {
  name            = "${var.www_tag_prefix}-haproxy-2"
  subnets         = ["${data.aws_subnet.public.*.id}"]
  security_groups = ["${aws_security_group.www_haproxy.id}"]

  listener {
    instance_port     = 80
    instance_protocol = "http"
    lb_port           = 80
    lb_protocol       = "http"
  }

  listener {
    instance_port      = 443
    instance_protocol  = "https"
    lb_port            = 443
    lb_protocol        = "https"
    ssl_certificate_id = "arn:aws:iam::XXXXXXXXXXXXXXX:server-certificate/www_cert"
  }

  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 3
    target              = "HTTP:80/themes/headers.xml?elb"
    interval            = 30
  }

  cross_zone_load_balancing   = true
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400

  tags = ["${merge(module.tags.tags, map("Name", "${var.www_tag_prefix}-haproxy", "AnsibleManaged", "true"))}"]
}
`
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by apparentlymart** [comment] 2017-08-18 16:56
Hi @erlarson85! Sorry for this crash and thanks for reporting it.

It seems that the links you shared for the panic output are not working for me... I'm getting a github 404 when following them. Could you check them? I expect the stack trace in the debug log will be the most useful thing to help figure out where this crash is coming from.

**Comment by erlarson85** [comment] 2017-08-18 17:10
<script src="https://gist.github.com/erlarson85/8b9c610e90604ce4c646339b924705c5.js"></script>
Hmm, strange, the url is getting changed on click. 

https://gist.github.com/erlarson85/c3cb2d5ef0233f350c2e520ee8bb9937
https://gist.github.com/erlarson85/8b9c610e90604ce4c646339b924705c5

**Comment by erlarson85** [comment] 2017-08-18 18:12
Root cause is [ ] in ELB tags. I have updated my local and it is functioning properly.

**Comment by apparentlymart** [comment] 2017-08-18 18:26
Thanks for the updated links and the root cause, @erlarson85!

Looks like there's some missing validation there that's allowing a list to get assigned to a map attribute and then crashing later. My bet is that we don't catch this because the `module.tags.tags` variable is unknown at the time of validation and so `tags` is being ignored, assuming that it'll get validated later once know, but then that "later" never comes.

We'll take a look at this. Thanks for reporting it, and I'm glad you found the fix for your config in the mean time.

---

```
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: panic: interface conversion: interface {} is string, not map[string]interface {}
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: goroutine 258 [running]:
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readMap(0xc4209a7ef0, 0x20a58db, 0x4, 0xc4205fb680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:170 +0x4d8
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc4209a7ef0, 0xc420788ca0, 0x1, 0x1, 0xc42078e700, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:113 +0x9f6
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc4209a7ef0, 0xc420788ca0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20a58db, ...)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0xe3
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc420414dc0, 0xc420788ca0, 0x1, 0x1, 0x20a735e, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0xef
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc4203639d0, 0xc420788ca0, 0x1, 0x1, 0xc420788c12, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:475 +0x13a
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc4203639d0, 0x20a58db, 0x4, 0x401201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:451 +0x135
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc4203639d0, 0x20a58db, 0x4, 0x20a46b4, 0x1, 0xc42067f268, 0x5, 0xc4207befa0)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:428 +0x61
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffMap(0xc4206bbce0, 0x20a58db, 0x4, 0xc4205fb680, 0xc42067f618, 0xc4203639d0, 0x200d400, 0x0, 0x0)
2017-08-17T12:45:17.960-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:838 +0x11a
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc4206bbce0, 0x20a58db, 0x4, 0xc4205fb680, 0xc420414c80, 0xc4203639d0, 0x0, 0x0, 0x0)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:689 +0x516
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc4206bbce0, 0xc42047fc70, 0xc4209a7a70, 0x0, 0x0, 0x28)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:389 +0x1c2
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc4205b97a0, 0xc42047fc70, 0xc4209a7a70, 0x7, 0xc4204f94e0, 0x1)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:217 +0x15b
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc420363ea0, 0xc42047fc20, 0xc42047fc70, 0xc4209a7a70, 0x7fd5ae33e4b0, 0x0, 0x0)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:255 +0x84
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc420479340, 0xc420414400, 0xc42068d0b0, 0x0, 0x0)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:499 +0x57
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: reflect.Value.call(0xc42035c780, 0xc42000c978, 0x13, 0x20a5153, 0x4, 0xc420390f20, 0x3, 0x3, 0x0, 0x0, ...)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: reflect.Value.Call(0xc42035c780, 0xc42000c978, 0x13, 0xc420508720, 0x3, 0x3, 0xc4202f3ce0, 0x0, 0x0)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: net/rpc.(*service).call(0xc420685b00, 0xc420685ac0, 0xc4204bbb20, 0xc4206c1b80, 0xc4203b3200, 0x1a6c940, 0xc420414400, 0x16, 0x1a6c980, 0xc42068d0b0, ...)
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: created by net/rpc.(*Server).ServeCodec
2017-08-17T12:45:17.961-0700 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
```

**Comment by apparentlymart** [comment] 2018-10-29 21:29
Hi @erlarson85! Sorry for the long silence here.

We've now got the changes for Terraform v0.12 merged in to master and released the v0.12.0-alpha1 release for initial testing. One of the changes is to retain type information for unknown values so that we can do more precise validation and thus avoid this crash bug.

Since the fix is in master, I'm going to close this out now. This will also be included in the v0.12.0 final release. Thanks again for reporting this!

**Closed by apparentlymart** 2018-10-29 21:29 UTC
Labels: bug, config, crash

**Comment by crysyn** [comment] 2019-02-14 17:59
I am able to recreate .. a version of this bug? on v0.11.11 using the example TF/JSON in the documentation: https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html

`panic: interface conversion: interface {} is string, not map[string]interface {}`

and if I remove the [] characters (and one of the entries) in the json I get
`Error: aws_ecs_task_definition.hydra-rabbitmq: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal object into Go value of type []*ecs.ContainerDefinition`

**Comment by crysyn** [comment] 2019-02-15 00:44
This error still occurs in v0.12.0-alpha4 found at https://releases.hashicorp.com/terraform/0.12.0-alpha4/

**Comment by apparentlymart** [comment] 2019-02-15 01:19
Hi @crysyn! Thanks for pointing that out. It does indeed look like there's still some gap that's allowing this panics to occur, though the relevant code in Terraform Core is now quite different after the 0.12 refactoring. If you wouldn't mind, it'd be very helpful if you could open a new top-level issue with that stack trace along with all of the other information requested in the GitHub issue template, since that'll hopefully help us narrow down how the bug is being triggered in the new version.

Terraform 0.12.0-alpha4 is quite old at this point, so the bug may well have been fixed in master in the mean time, but I'd like to see exactly how you're getting that panic so we can check to make sure, and fix it if not.

Thanks again!
