### ISSUE TITLE
Passing ignore_changes into a module

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#21546] opened 2019-05-31 20:50 UTC
Is there a way to pass `ignore_changes` into a module. I.E. I want to ignore `aws_instance.ami` only for some instances of a module. I tried adding `ignore_changes` as a new module variable, but getting:

```
aws_instance.instance: lifecycle ignore_changes cannot contain interpolations
``` 

```tf
# in module
lifecycle {
    ignore_changes = [
      "${var.ignore_changes}",
    ]
  }
```

**Comment by sworisbreathing** [comment] 2019-07-10 05:17
I've just run into this same issue. in my case I've got AWS CodePipeline doing CI/CD for a lambda function in my dev account, and I don't want terraform to overwrite the version deployed in dev, but in prod I want to lock it down and be more explicit about which version I'm running. So I want to do something like:

```hcl
lifecycle {
  ignore_changes = "${var.environment == "prod" ? list() : list("s3_key")}"
}
```

**Comment by sworisbreathing** [comment] 2019-07-10 05:38
This issue appears to be a duplicate of #3116 (or at least, I'm assuming it will work once that issue is fixed)

**Comment by jaksky** [comment] 2020-05-27 10:32
Is there any update on this or workaround?

**Comment by LukeCarrier** [comment] 2020-10-22 13:33
The other issue with locking the other discussion is that we can't add our 👍 to the issue, thus I'm not sure we have an accurate number of how many folks are being bitten by this. Could the issue be unlocked, maybe?

**Comment by debu99** [comment] 2021-04-07 09:41
any update?

**Comment by ekristen** [comment] 2021-04-14 14:38
@apparentlymart this seems to be a fairly hot issue that's been around for 3+ years now when looking at the locked issue. I too have run into the issue of not being able to dynamically control the lifecycle rules, this is important for me as I'm writing modules and sometimes inputs change but we want to ignore things dynamically instead of globally for the module.

Any chance this can get some attention?

**Comment by viion** [comment] 2021-04-19 13:27
I am also running into this and kind of shocked it isn't already a thing, this feels like a basic feature.

Lifecycles should be passed to modules.

**Comment by joelgaria** [comment] 2021-06-18 20:07
I've got the same problem. Generating the modules myself this creates several problems for me. For the moment I fixed it by creating the resources with a module and managing it once changed with another equal with the lifecycle. Anyone have any other better ideas?

**Comment by MindAwakeBodyAsleep** [comment] 2021-11-21 09:53
This feature would make the modules more flexible ( for example: enabling application autoscaling in AWS forced to add ignore_changes for desired_count parameter.)

**Comment by fmarrero** [comment] 2022-01-11 17:31
I have a custom module that uses "terraform-aws-modules/ec2-instance/aws" but if the user_data changes which is based on some inputs, it would destroy the existing ec2s. I wanted to ignore changes for user_data at the community module level which would allow me to create different versions of the custom module based on different user data parameters.

**Comment by AndrewBenedyk** [comment] 2022-01-14 13:51
Wow, for some reason I was thinking that **ignore_changes** for input parameters in modules already implemented, as part of lifecycle. Anyway, this feature would add more flexibility.

**Comment by jfletcher93** [comment] 2022-01-19 17:08
Ran into this problem myself today - sounds like an essential feature for people to be able to truly consume community modules.

**Comment by yves-vogl** [comment] 2022-02-09 09:25
Another use case would be for writing a module for Azure Application Gateway which could optionally managed by an Kubernetes Ingress Controller.

**Comment by codycodes** [comment] 2022-02-16 17:27
As a workaround (albeit not optimal), we can hardcode the values into `ignore_changes` on the module scope and then use `count` with a variable e.g. `create_resource_with_ignore_changes = 1` to get our resource provisioned with `ignore_changes` from the module scope. I know this isn't what the issue requested, instead this is hardcoding `ignore_changes` into the module and provisioning it via a count switch, so I'm putting our use cases of `ignore_changes` here:

Two more uses helpful in the context of deploying a module that creates an Azure App Service:

1. Ignoring changes to the Docker image which is changed by application code deployment pipelines (dynamically creating images with unique tags)
2. Ignoring changes to App Settings, which are handled via application code deployment pipelines & utilize Azure Key Vault References to create App Settings from a Key Vault instead.

---

These are necessary to ensure Terraform isn't conflicting with values which are changed outside of its lifecycle. Not being able to use modules with this will mean some decisions need to be made on our side (either the workaround above, or not using modules for these resources).

**Comment by jobwat-servian** [comment] 2022-09-13 00:46
Duplicate of https://github.com/hashicorp/terraform/issues/27360

Please go add your upvote (👍 ) to the above issue / feature request 🙏

**Comment by crw** [comment] 2022-09-16 22:56
Thanks for finding that. It is a duplicate, I am going to close in favor of #27360 as it currently has the greater weight of votes and comments. Thanks again!

**Closed by crw** 2022-09-16 22:56 UTC
Labels: enhancement, duplicate
