### ISSUE TITLE
AzureRM 2.0 - Error creating Azure Functions

### ISSUE THREAD

**Issue by shouseba** [hashicorp/terraform#24536] opened 2020-04-02 16:04 UTC
### Terraform Version

```
Terraform v0.12.24
+ provider.azurerm v2.0.0
...
```

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "***-***-preprod" {	
  name                      = "***-***-***"	
  location                 	= data.azurerm_resource_group.***.location
  resource_group_name      	= data.azurerm_resource_group.***.name
  app_service_plan_id      	= data.azurerm_app_service_plan.***.id
  storage_connection_string = azurerm_storage_account.***.primary_connection_string	
}
```

**Comment by danieldreier** [comment] 2020-04-03 00:54
@shouseba this issue report doesn't provide sufficient information for us to identify the cause of your issue, or to help route it correctly. Would you please complete the rest of the issue template?

**Comment by danieldreier** [comment] 2020-04-28 00:16
I'm going to close this issue because it's been waiting for a response for 25 days and lacks enough context for us to work on it. If you're still having this issue, please feel free to let us know, and make sure to link this issue if you file a new one so that we have that context. 

If you're not quite sure whether it's a bug or a question, you might post on [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

**Closed by danieldreier** 2020-04-28 00:16 UTC
Labels: waiting-response
