### ISSUE TITLE
Iterating using templatefile() in JSON

### ISSUE THREAD

**Issue by leonardoauribe** [hashicorp/terraform#33187] opened 2023-05-11 21:06 UTC
### Terraform Version

```shell
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/f5networks/bigip v1.17.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
```

### Terraform Configuration Files

Main.tf
```
locals {
  site_name = "lab"
}
#TERRAFORM BACKEND
terraform {
  required_version = "~>1.3.0"
  backend "s3" {...}

  required_providers {
    bigip = {
      source  = "F5Networks/bigip"
      version = "1.17.0"
    }
    local = {
      source = "hashicorp/local"
    }
  }
}

provider "bigip" {
  address    = "ltm-lab"
  username   = "admin"
  password   = ""
  validate_certs_disable = true 
  trusted_cert_path      = "/path/"
}

resource "bigip_do" "ltm__tmpl_do" {
  timeout = 15
  do_json = templatefile("../templates/ltm_lab_DO_VARS.json", {
    HOSTNAME                 = "ltm1-${local.site_name}"
    NAME_SERVERS             = ["8.8.8.8", "8.8.4.4"]
    INT_VIPS_1_SELFIP_IP     = "10.169.21.10/24"
    INT_VIPS_2_SELFIP_IP     = "10.169.22.10/24"
    INT_VIPS_3_SELFIP_IP     = "10.169.23.10/24"
    EXT_VIPS_1_SELFIP_IP     = "10.169.24.10/24"
    EXT_VIPS_2_SELFIP_IP     = "10.169.25.10/24"
    EXT_VIPS_3_SELFIP_IP     = "10.169.26.10/24"
    TRAFFIC_SELFIP_IP        = "10.169.27.70/27"
    REMOTE_ACCESS_ALLOW_LIST = ["1.1.1.1/24", "2.2.2.2/24"]
    SNMP_ALLOW_LIST = [
      "127.0.0.0/8",
      "10.169.117.216",
      "1.1.1.1/24", 
      "2.2.2.2/24"
    ]
    VPC_CIDR_BLOCK = ["10.169.21.0/19", "10.179.32.0/20"]
  })
}
```

JSON Template File
```
${jsonencode ({
        "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/1.37.0/base.schema.json",
        "schemaVersion": "1.37.0",
        "class": "Device",
        "async": true,
        "Common": {
            "class": "Tenant",
            "System": {
                "class": "System",
                "hostname": HOSTNAME,
                "mgmtDhcpEnabled": false,
                "autoCheck": false,
                "autoPhonehome": true
            },
            "Provision": {
                "class": "Provision",
                "ltm": "dedicated"
            },
            "NTP": {
                "class": "NTP",
                "servers": NAME_SERVERS
            },
            "DNS": {
                "class": "DNS",
                "nameServers": NAME_SERVERS,
                "search": [
                    "ops.sfdc.net"
                ]
            },
            "EXT-VIPS-1-VLAN": {
                "class": "VLAN",
                "tag": 102,
                "interfaces": [
                    {
                        "name": "1.2",
                        "tagged": false
                    }
                ]
            },
            "EXT-VIPS-2-VLAN": {
                "class": "VLAN",
                "tag": 103,
                "interfaces": [
                    {
                        "name": "1.3",
                        "tagged": false
                    }
                ]
            },
            "EXT-VIPS-3-VLAN": {
                "class": "VLAN",
                "tag": 104,
                "interfaces": [
                    {
                        "name": "1.4",
                        "tagged": false
                    }
                ]
            },
            "INT-VIPS-1-VLAN": {
                "class": "VLAN",
                "tag": 105,
                "interfaces": [
                    {
                        "name": "1.5",
                        "tagged": false
                    }
                ]
            },
            "INT-VIPS-2-VLAN": {
                "class": "VLAN",
                "tag": 106,
                "interfaces": [
                    {
                        "name": "1.6",
                        "tagged": false
                    }
                ]
            },
            "INT-VIPS-3-VLAN": {
                "class": "VLAN",
                "tag": 107,
                "interfaces": [
                    {
                        "name": "1.7",
                        "tagged": false
                    }
                ]
            },
            "TRAFFIC-VLAN": {
                "class": "VLAN",
                "tag": 101,
                "interfaces": [
                    {
                        "name": "1.1",
                        "tagged": false
                    }
                ]
            },
            "INT-VIPS-1-SELFIP": {
                "class": "SelfIp",
                "address": INT_VIPS_1_SELFIP_IP,
                "vlan": "INT-VIPS-1-VLAN",
                "trafficGroup": "traffic-group-local-only",
                "allowService": "none"
            },
            "INT-VIPS-2-SELFIP": {
                "class": "SelfIp",
                "address": INT_VIPS_2_SELFIP_IP,
                "vlan": "INT-VIPS-2-VLAN",
                "trafficGroup": "traffic-group-local-only",
                "allowService": "none"
            },
            "INT-VIPS-3-SELFIP": {
                "class": "SelfIp",
                "address": INT_VIPS_3_SELFIP_IP,
                "vlan": "INT-VIPS-3-VLAN",
                "trafficGroup": "traffic-group-local-only",
                "allowService": "none"
            },
            "EXT-VIPS-1-SELFIP": {
                "class": "SelfIp",
                "address": EXT_VIPS_1_SELFIP_IP,
                "vlan": "EXT-VIPS-1-VLAN",
                "trafficGroup": "traffic-group-local-only",
                "allowService": "none"
            },
            "EXT-VIPS-2-SELFIP": {
                "class": "SelfIp",
                "address": EXT_VIPS_2_SELFIP_IP,
                "vlan": "EXT-VIPS-2-VLAN",
                "trafficGroup": "traffic-group-local-only",
                "allowService": "none"
            },
            "EXT-VIPS-3-SELFIP": {
                "class": "SelfIp",
                "address": EXT_VIPS_3_SELFIP_IP,
                "vlan": "EXT-VIPS-3-VLAN",
                "trafficGroup": "traffic-group-local-only",
                "allowService": "none"
            },
            "TRAFFIC-SELFIP": {
                "class": "SelfIp",
                "address": TRAFFIC_SELFIP_IP,
                "vlan": "TRAFFIC-VLAN",
                "trafficGroup": "traffic-group-local-only",
                "allowService": "default"
            },
            "VPC-ROUTE": [
            %{ for CIDR in VPC_CIDR_BLOCK
                }
                "class": "Route",
                "gw": "10.169.96.65",
                "network": CIDR,
            %{ endfor
                }
            ],
          "Snmp": {
                "class": "SnmpAgent",
                "allowList": SNMP_ALLOW_LIST
            },
            "SSHD": {
                "class": "SSHD",
                "allow": REMOTE_ACCESS_ALLOW_LIST
            },
            "HTTPD": {
                "class": "HTTPD",
                "allow": REMOTE_ACCESS_ALLOW_LIST
            }
        }
    })
}
```

### Debug Output

https://gist.github.com/leonardoauribe/6ace3fcf1a248c1c49798039a7a64e74

### Expected Behavior

Expecting the creation of a "VPC-ROUTE" object per cidr in the vpc_cidr_block list.  

### Actual Behavior

Error: Error in function call
...
│ Call to function "templatefile" failed: ../templates/ltm_lab_DO_VARS.json:171,13-14: Invalid expression; Expected the start of an expression, but found an invalid expression token..

### Steps to Reproduce

1. 'terraform init'
2. 'terraform plan'
3. 'terraform apply'

### References

Used [issue](https://github.com/hashicorp/terraform/issues/23282) along with [templatefile](https://developer.hashicorp.com/terraform/language/functions/templatefile#generating-json-or-yaml-from-a-template) documentation as a guide with no success.

**Comment by apparentlymart** [comment] 2023-05-11 22:41
Hi @leonardoauribe,

You seem to be using the template `for` syntax in a context that is expecting expression syntax, so this error is correct that your syntax is invalid.

If your goal is to make a JSON array with one element per element of your `VPC_CIDR_BLOCK` collection then you can use a normal `for` expression, instead of a template `for` directive, like this:

```
"VPC-ROUTE": [
  for cidr in VPC_CIDR_BLOCK : {
    class   = "Route"
    gw      = "10.169.96.65"
    network = cidr
  }
]
```

Note also that it's conventional in Terraform to use lowercase names for variables, and to use plural names for variables that are of collection types, so `vpc_cidr_blocks` would be a more idiomatic name than `VPC_CIDR_BLOCK`. I preserved your current name choice in the example above, though.

Does this new example produce the result you were intending?

**Comment by leonardoauribe** [comment] 2023-05-11 23:11
I'm getting an actual plan with what is pretty close to what I'm looking for. The only issue is that we would need unique keys for each route. Below are a few examples of what I'm looking for. Similar to how terraform resources are uniquely identifiable by index or key when using count and for_each expressions. 

Current Output
```
                  + VPC-ROUTE                = [
                      + {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.169.96.0/19"
                        },
                      + {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.179.128.0/20"
                        },
]
```

Desired Output (example 1)
```
                  + VPC-ROUTE[10.169.21.0/19]  = [
                      + {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.169.21.0/19"
                        }
]
                   + VPC-ROUTE[10.179.22.0/20] = [
                           {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.179.22.0/20"
                        },
]
```

Desired Output (example 2)
```
                  + VPC-ROUTE-1  = [
                      + {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.169.21.0/19"
                        }
]
                   + VPC-ROUTE-2= [
                           {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.179.22.0/20"
                        },
]
```

Desired Output (example 3)
```
                  + VPC-ROUTE-"key1"  = [
                      + {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.169.21.0/19"
                        }
]
                   + VPC-ROUTE-"key2"  = [
                           {
                          + class   = "Route"
                          + gw      = "10.169.96.65"
                          + network = "10.179.22.0/20"
                        },
]
```

**Comment by apparentlymart** [comment] 2023-05-12 00:39
Hi @leonardoauribe,

From what you shared it seems that this `VPC_CIDR_BLOCK` variable is just a list of strings, so there isn't any separate value to use as a key here, but I think what you're saying is that whatever software is parsing this JSON expects each of these keys to refer to exactly one object, and not to an array of objects as I originally suspected.

This does unfortunately make things a little more complicated because with this requirement we must merge the dynamically-constructed object in with the hand-written object, which requires a more invasive change to how you structured this expression and so I'll need to write out the whole thing to show the context:

```
${jsonencode({
  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/1.37.0/base.schema.json",
  "schemaVersion": "1.37.0",
  "class": "Device",
  "async": true,
  "Common": merge(
    {
      "class": "Tenant",
      "System": {
        "class": "System",
        "hostname": HOSTNAME,
        "mgmtDhcpEnabled": false,
        "autoCheck": false,
        "autoPhonehome": true
      },
      "Provision": {
        "class": "Provision",
        "ltm": "dedicated"
      },
      "NTP": {
        "class": "NTP",
        "servers": NAME_SERVERS
      },
      "DNS": {
        "class": "DNS",
        "nameServers": NAME_SERVERS,
        "search": [
          "ops.sfdc.net",
        ]
      },
      "EXT-VIPS-1-VLAN": {
        "class": "VLAN",
        "tag": 102,
        "interfaces": [
          {
            "name": "1.2",
            "tagged": false
          },
        ]
      },
      "EXT-VIPS-2-VLAN": {
        "class": "VLAN",
        "tag": 103,
        "interfaces": [
          {
            "name": "1.3",
            "tagged": false
          }
        ]
      },
      "EXT-VIPS-3-VLAN": {
        "class": "VLAN",
        "tag": 104,
        "interfaces": [
          {
            "name": "1.4",
            "tagged": false
          }
        ]
      },
      "INT-VIPS-1-VLAN": {
        "class": "VLAN",
        "tag": 105,
        "interfaces": [
          {
            "name": "1.5",
            "tagged": false
          }
        ]
      },
      "INT-VIPS-2-VLAN": {
        "class": "VLAN",
        "tag": 106,
        "interfaces": [
          {
            "name": "1.6",
            "tagged": false
          }
        ]
      },
      "INT-VIPS-3-VLAN": {
        "class": "VLAN",
        "tag": 107,
        "interfaces": [
          {
            "name": "1.7",
            "tagged": false
          }
        ]
      },
      "TRAFFIC-VLAN": {
        "class": "VLAN",
        "tag": 101,
        "interfaces": [
          {
            "name": "1.1",
            "tagged": false
          }
        ]
      },
      "INT-VIPS-1-SELFIP": {
        "class": "SelfIp",
        "address": INT_VIPS_1_SELFIP_IP,
        "vlan": "INT-VIPS-1-VLAN",
        "trafficGroup": "traffic-group-local-only",
        "allowService": "none"
      },
      "INT-VIPS-2-SELFIP": {
        "class": "SelfIp",
        "address": INT_VIPS_2_SELFIP_IP,
        "vlan": "INT-VIPS-2-VLAN",
        "trafficGroup": "traffic-group-local-only",
        "allowService": "none"
      },
      "INT-VIPS-3-SELFIP": {
        "class": "SelfIp",
        "address": INT_VIPS_3_SELFIP_IP,
        "vlan": "INT-VIPS-3-VLAN",
        "trafficGroup": "traffic-group-local-only",
        "allowService": "none"
      },
      "EXT-VIPS-1-SELFIP": {
        "class": "SelfIp",
        "address": EXT_VIPS_1_SELFIP_IP,
        "vlan": "EXT-VIPS-1-VLAN",
        "trafficGroup": "traffic-group-local-only",
        "allowService": "none"
      },
      "EXT-VIPS-2-SELFIP": {
        "class": "SelfIp",
        "address": EXT_VIPS_2_SELFIP_IP,
        "vlan": "EXT-VIPS-2-VLAN",
        "trafficGroup": "traffic-group-local-only",
        "allowService": "none"
      },
      "EXT-VIPS-3-SELFIP": {
        "class": "SelfIp",
        "address": EXT_VIPS_3_SELFIP_IP,
        "vlan": "EXT-VIPS-3-VLAN",
        "trafficGroup": "traffic-group-local-only",
        "allowService": "none"
      },
      "TRAFFIC-SELFIP": {
        "class": "SelfIp",
        "address": TRAFFIC_SELFIP_IP,
        "vlan": "TRAFFIC-VLAN",
        "trafficGroup": "traffic-group-local-only",
        "allowService": "default"
      },
      "Snmp": {
        "class": "SnmpAgent",
        "allowList": SNMP_ALLOW_LIST
      },
      "SSHD": {
        "class": "SSHD",
        "allow": REMOTE_ACCESS_ALLOW_LIST
      },
      "HTTPD": {
        "class": "HTTPD",
        "allow": REMOTE_ACCESS_ALLOW_LIST
      }
    },
    {
      for index, cidr in VPC_CIDR_BLOCK : "VPC-ROUTE-${index}" => {
        class   = "Route"
        gw      = "10.169.96.65"
        network = cidr
      }
    },
  })
}
```

This one is more awkward because rather than just dynamically generating the value of one of the properties in the object we need to now dynamically generate the object itself, so that the set of property names it includes can vary based on how many elements of `VPC_CIDR_BLOCK` are presented. The above example achieves that by using [the `merge` function](https://developer.hashicorp.com/terraform/language/functions/merge) to combine the first object which is just written out literally with a second object that is generated dynamically using a `for` expression.

Since I wasn't sure what was a good property name to use for each of these (you have various different examples) I just arbitrarily chose to use the index in the list, so this would generate property names like `VPC-ROUTE-0`, `VPC-ROUTE-1`, `VPC-ROUTE-2`. If you want to use the CIDR address in the key instead then you could replace "VPC-ROUTE-${index}" with a template including `cidr`, such as `"VPC-ROUTE[${cidr}]"` to produce `VPC-ROUTE[10.169.21.0/19]` as in your second example.

We only use issues in this repository to represent bugs or feature requests in Terraform, and what you described in the original opening comment was Terraform behaving as designed when given a template containing invalid expression syntax. Therefore I'm going to close this issue now, but if the example I showed above isn't sufficient to get the result you want I'd encourage you to start a topic in [our community forum](https://discuss.hashicorp.com/c/terraform-core/27), where there are various members of the community ready to help with questions, and I also monitor the forum myself when I have time so I might well reply to your topic there too, if someone else doesn't get there first!

Thanks!

**Closed by apparentlymart** 2023-05-12 00:39 UTC
Labels: bug, waiting-response, new

**Comment by leonardoauribe** [comment] 2023-05-12 16:36
This is exactly what I was looking for. This is great! Thanks for the quick response and detailed explanation.

**Comment by leonardoauribe** [comment] 2023-05-12 16:37
This is exactly what I was looking for. This is great! Thanks for the quick response and detailed explanation.
