### ISSUE TITLE
terraform cloud "terraform crash issue"

### ISSUE THREAD

**Issue by abhijitsingamaneni** [hashicorp/terraform#24386] opened 2020-03-16 19:59 UTC
Hi,

I am having following issue in terraform cloud.

Terraform v0.12.23
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 2): <nil>

Output:
2020/03/16 19:55:23 [DEBUG] Using modified User-Agent: Terraform/0.12.23 TFC/74ac95694d
Initializing modules...
Downloading app.terraform.io/ucsf/bigfix/aws 1.0.3 for bigfix...
- bigfix in .terraform/modules/bigfix

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd0c90a]

goroutine 1 [running]:
github.com/hashicorp/terraform/registry.maxRetryErrorHandler(0x0, 0x232e4e0, 0xc00071c450, 0x2, 0x3, 0x3, 0x232e4e0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:422 +0xea
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc0001bd980, 0xc00004da50, 0x1e8df81, 0x13, 0xc0007a7268)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.5.2/client.go:452 +0x706
github.com/hashicorp/terraform/registry.(*Client).TerraformProviderVersions(0xc00020d260, 0xc000715b80, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/registry/client.go:305 +0x467
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).listProviderVersions(0xc0000e6a80, 0xc00013edd6, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0xc00004e070, 0xc00004e000, 0xc000786ca8)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:477 +0x7e
github.com/hashicorp/terraform/plugin/discovery.(*ProviderInstaller).Get(0xc0000e6a80, 0xc00013edd6, 0x3, 0x1e7474c, 0x1, 0x1e92a34, 0x15, 0x3523918, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/plugin/discovery/get.go:125 +0xde
github.com/hashicorp/terraform/command.(*InitCommand).getProviders(0xc000475a40, 0xc0005340e0, 0xc000444b60, 0x0, 0xc0002388c0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:530 +0x4c5
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000475a40, 0xc00003a1a0, 0x1, 0x1, 0xc0004424d0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/command/init.go:347 +0x102d
github.com/mitchellh/cli.(*CLI).Run(0xc000318280, 0xc000318280, 0xc000521d90, 0x1)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:239 +0xc33
main.realMain(0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:103 +0xb4
main.main()
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/main.go:39 +0x3b



**Comment by paultyng** [comment] 2020-03-17 12:54
Duplicate of #24384

**Closed by paultyng** 2020-03-17 12:54 UTC
Labels: bug, crash

**Comment by abhijitsingamaneni** [comment] 2020-03-17 23:22
@paultyng now it is working fine
