### ISSUE TITLE
terraform-0.12.24, cannot set set name to AWS API Gateway

### ISSUE THREAD

**Issue by selfieblue** [hashicorp/terraform#24902] opened 2020-05-08 15:02 UTC
### Terraform Version

```
...
```

**Comment by danieldreier** [comment] 2020-05-12 01:03
Hi there! I think you must have made a mistake when filling this out, because the issue is empty. I'm going to close it, but please do recreate it using our standard issue template and I'd be happy to try and help.

**Closed by danieldreier** 2020-05-12 01:03 UTC
