### ISSUE TITLE
Add optional block syntax

### ISSUE THREAD

**Issue by astorath** [hashicorp/terraform#21717] opened 2019-06-13 17:28 UTC
### Current Terraform Version
```
Terraform v0.12.2
+ provider.external v1.1.2
+ provider.google v2.7.0
```

### Use-cases
- some resources define blocks (not arguments) that make a difference whether they are present or not (e.g. `access_config` in `google_compute_instance`)
- I want to make a (boolean) module variable to switch those blocks on/off

E.g.:
```hcl
variable "ext_ip" {
  default = false
  type    = bool
}

resource "google_compute_instance" "vm" {
  name         = "vm"
  machine_type = "f1-micro"
  zone         = "us-east4-a"

  boot_disk {
    initialize_params {
      image = "centos-cloud/centos-7"
    }
  }
  network_interface {
    subnetwork = "default"
    access_config = var.ext_ip ? {} : null
  }
}
```

### Attempted Solutions
1. Use dynamic block ver1:
```hcl
resource "google_compute_instance" "vm" {
  network_interface {
    dynamic "access_config" {
      for_each = var.ext_ip ? [""] : []
      content {}
    }
  }
}
```

2. Use dynamic block ver2
```hcl
resource "google_compute_instance" "vm" {
  network_interface {
    dynamic "access_config" {
      for_each = [for i in [""]: i if var.ext_ip]
      content {}
    }
  }
}
```
3.  Before 0.12 we used a workaround, that is prohibited in 0.12 (assigning values to blocks)
```hcl
access_config = "${var.access_config}"
```

### Proposal
Options are:
1. Allow assigning values to blocks:
```hcl
resource "google_compute_instance" "vm" {
  network_interface {
    access_config = var.ext_ip ? map() : null
  }
}
```
2. Add `if` prefix / posfix expression in **dynamic** blocks:
```hcl
resource "google_compute_instance" "vm" {
  network_interface {
    dynamic "access_config" {
      if var.ext_ip
      content {}
    }
  }
}
resource "google_compute_instance" "vm" {
  network_interface {
    dynamic "access_config" {
      content {}
      if var.ext_ip
    }
  }
}
```
3. Make boolean a 1/0 sized list by default:
```hcl
resource "google_compute_instance" "vm" {
  network_interface {
    dynamic "access_config" {
      for_each = var.ext_ip
      content {}
    }
  }
}
```
here we assume `false == []` and `true = [true]`

**Comment by apparentlymart** [comment] 2019-06-13 18:23
Hi @astorath! Thanks for opening this feature request.

You listed two things under "attempted solutions" which should've worked. Did you encounter an error when you tried them?

**Comment by astorath** [comment] 2019-06-14 10:18
@apparentlymart Hey! Yes, these solutions do work, but they're quite ugly IMHO: both solutions take several lines of code and include "magic" literal (array with some value) with no obvious reason. 

The proposal is to add another syntax for such case. 

New block syntax breaks backwards compatibility (before 0.12 it was possible to assign values to blocks), not sure if it is intended.

**Comment by apparentlymart** [comment] 2019-06-14 15:15
It was indeed intentional that treating blocks as map values no longer works: it only ever worked in 0.11 and prior due to a bug, and didn't work reliably (lots of issues here have that as a root cause), so the `dynamic` block is the intended replacement that preserves the invariants about nested blocks that Terraform and the SDK are expecting. In particular, it ensures that all of the argument names in the block are specified directly so that Terraform and the providers can validate them, whereas before Terraform or providers would often produce confusing errors like "should be a list" because they were seeing values that ought to have been impossible.

Usually when generating dynamic blocks we're expecting to insert some dynamic values inside, which makes the formulation as an iterator more intuitive because the iterator value will itself contain the values to include inside the block.

The `access_config` block here is pretty unusual in that its mere presence is enough to cause a difference in behavior, even if nothing is set inside of it. Indeed the `dynamic` block does feel strange in that case, because what is more naturally a boolean value is projected into the presence or absence of a block.

The usual suggestion in situations like these is to more directly represent the underlying provider representation in the input variables -- by using an object or list of objects to represent the blocks -- but since the underlying representation in the resource is unusual here, I'd agree that a boolean flag is the more natural representation for what you are trying to model.

This is an unusual situation though, and so I don't think that adding further features to the language (increasing the amount of concepts someone needs to understand to read/write Terraform configuration) for this unusual schema is a tradeoff we'd want to take here. While I agree it _is_ verbose, the language is designed around the most common situations and (as is often the case with language design) some awkwardness for unusual constructs is expected.

Your first attempted solution is essentially how I'd write this, although for consistency with how this sort of thing is usually formulated (as a list of objects) I'd probably use an empty object as the placeholder value for iteration, so it feels more like a logical representation of the empty block it's going to produce:

```hcl
resource "google_compute_instance" "vm" {
  network_interface {
    dynamic "access_config" {
      for_each = var.ext_ip ? [{}] : []
      content {}
    }
  }
}
```

We'll continue to keep an eye out for other unusual provider schemas that lead to situations like this, and see if they have enough in common to warrant a new language feature to accommodate it, or whether they might be better addressed by changing the provider schema to be more "conventional". For now though, I'm going to close this to represent that we don't currently have specific plans to change the language to accommodate _this_ unusual case.

Thanks for opening this feature request, and drawing our attention to this interesting provider schema design!

---

It may be worth also opening an issue in the GCP provider repository to discuss whether there might be a more explicit and intuitive representation of requesting an external IP address for a compute instance.

Even when written statically as `access_config {}` it is unfortunate that this block has an important effect that isn't actually stated explicitly anywhere in it. The reader presumably needs to be a GCP expert to understand that it is the presence of this block that makes the instance publicly addressible.

If it were formulated as an explicit boolean flag instead, it would be easier for a non-expert reader to understand the meaning _and_ the representation as an expression deriving from a variable (as you wanted to do in your module here) might also be more intuitive.

**Closed by apparentlymart** 2019-06-14 15:15 UTC
Labels: enhancement
