### ISSUE TITLE
declaring proxy provider configurations

### ISSUE THREAD

**Issue by dmrzzz** [hashicorp/terraform#17191] opened 2018-01-24 23:46 UTC
I'm a huge fan of being able to explicitly pass providers to child modules, and I have a small suggestion to make it even better.

As of TF v0.11.1, using the example from https://www.terraform.io/docs/modules/usage.html#passing-providers-explicitly, the problem with writing

```hcl
provider "aws" {
  alias = "src"
}
```

in the child module is that if the parent module _doesn't_ pass any "aws.src" in the `providers` map, this configuration block within the child module which I had intended as a mere proxy suddenly becomes a fully-fledged provider on its own, perhaps prompting the user to enter a region manually

```bash
$ terraform plan
provider.aws.src.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: 
```

or perhaps silently reading AWS_DEFAULT_REGION and continuing as if nothing were out of the ordinary.

What I'd like (as the child module author) is to declare that this provider block is only a proxy for a provider which MUST be passed in by the parent.  If the parent author forgets to pass it in, that's like forgetting a required argument, and Terraform should raise a similar error message to let them know:
```
Error: module "tunnel": missing required provider "aws.src"
```

I'm envisioning something along the lines of

```hcl
provider "aws" {
  alias = "src"
  proxy_only = true
}
```

**Comment by grimm26** [comment] 2018-01-25 04:42
Thank you for writing this before I did. I completely agree.

**Comment by jbardin** [comment] 2018-01-25 15:34
Hi @dmrzzz, thanks for opening the issue here.

This is something we are aware of, though it would be nice to solve it without another backwards incompatible change to the provider configuration block. 

Rather than adding a new flag to the provider block, this will be grouped into the proposal #16835. 

We also want to take into consideration the ability to possibly specify the location of a provider, which runs into the same issue of overloading the provider configuration block. 

Closing this one just so we can track the feature in one location.

**Closed by jbardin** 2018-01-25 15:34 UTC
Labels: config, enhancement, modules

**Comment by patrick-webs** [comment] 2019-10-22 18:15
Hello, I followed this request to #16835, but I don't see anything in the final implementation there that implemented support for the proposed "proxy_only" or an equivalent. 

I have a reusable module I'm developing that expects to have 2 AWS providers passed to it, and the documentation at https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly only says

> The subdirectory ./tunnel must then contain proxy configuration blocks like the following, to declare that it requires configurations to be passed with these from the providers block in the parent's module block

There doesn't seem to be any way that I can declare that these proxy configuration blocks are only intended for use as proxies, and when I run `terraform validate` in my reusable module it prints an error about a missing required `region` argument for the AWS provider, which seems to indicate terraform doesn't understand they are only proxies and shouldn't be considered full providers. Is this expected behavior or could it make sense to file a new enhancement request?
