### ISSUE TITLE
Terraform state migration to TF Cloud failing due to local tfstate

### ISSUE THREAD

**Issue by sysadmiral** [hashicorp/terraform#29009] opened 2021-06-22 12:13 UTC
### Terraform Version

```
$ terraform version
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.43.0
```

### Terraform Configuration Files

```terraform
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "foo"

    workspaces {
      name = "bar"
    }
  }
```

### Expected Behavior
I'm migrating state from a local copy to a new workspace in Terraform Cloud. This process has worked without issue on other repositories I've done this for.

I followed the instructions here: https://www.terraform.io/docs/cloud/migrate/index.html

I have local tfstate working and in `.terraform` I only have the provider:

```
$ tree -a .terraform
.terraform
└── providers
    └── registry.terraform.io
        └── hashicorp
            └── aws
                └── 3.43.0
                    └── linux_amd64 -> /home/amo/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/3.43.0/linux_amd64
```

When I add the backend config at the start of this issue and run `terraform init` I expect the config to be copied to Terraform Cloud and a `terraform plan` should show that the run is happening remotely and that there are no changes pending.

### Actual Behavior
At the point of adding the backend config and running `terraform init` I get prompted to copy state and reply `yes` and get `Terraform has been successfully initialized!`. It seems that Terraform creates a tfstate file under `.terraform`:

```
.terraform
├── providers
│   └── registry.terraform.io
│       └── hashicorp
│           └── aws
│               └── 3.43.0
│                   └── linux_amd64 -> /home/amo/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/3.43.0/linux_amd64
└── terraform.tfstate

6 directories, 1 file
```

And now when I run `terraform plan` I get an error:

```
Waiting for the plan to start...

Terraform v1.0.0
on linux_amd64

------------ Terraform Cloud System Message ------------

Terraform Cloud detected a terraform.tfstate file in your working
directory: ./terraform.tfstate

The presence of this file causes a state migration error which prevents
Terraform from running successfully. To fix this error please migrate
your local terraform.tfstate to Terraform Cloud and make sure the
the file is deleted.

For step by step instructions on how to migrate your terraform.tfstate
file from Terraform Open Source to Terraform Cloud, please see:

   https://www.terraform.io/docs/enterprise/migrate/index.html

--------------------------------------------------------

Setup failed: Terraform Cloud detected a terraform.tfstate file
```

### Steps to Reproduce

1. Add remote backend config for Terraform Cloud new workspace
2. `terraform init` (say "yes")
3. `terraform plan`

I'm not really sure what else I can add because as I say I ran this process in other repositories without issue. AFAIK there is nothing special about the repository I am working in. It's structure follows the pattern we use for most of our terraform code.

I tried asking on gitter before opening an issue but didn't get any responses.

**Comment by jbardin** [comment] 2021-06-22 12:47
Hi @sysadmiral,

Thanks for filing the issue. I am also not sure how you arrived in this situation, but if the state is stored correctly in the cloud service, then you have no need for the local `terraform.tfstate` file. The easiest way to test this is to rename the state file and see of the plan works as expected.  Since it's unclear how this happened, I'm going to close this for now. If you find more information or can reproduce the issue, please feel free to follow up here.

I'm not aware of anyone using gitter, but [our community forums](https://discuss.hashicorp.com/c/terraform-core) are quite active, and there are a lot more users there who can help. 

Thanks!

**Closed by jbardin** 2021-06-22 12:47 UTC
Labels: bug, new
