### ISSUE TITLE
Terraform does not handle references to resources that use count or for_each in modules correctly when you run destroy

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#25878] opened 2020-08-17 13:35 UTC
### Terraform Version

```
v0.12.24
```

### Terraform Configuration Files

The original code where I was hitting these errors is fairly complicated and I can't share it. Below is the simplest repro I've been able to create so far that creates a very similar error. 

In `/tmp/repro/module/main.tf`, create the following Terraform code:

```terraform
variable "should_create" {
  type    = bool
}

resource "null_resource" "normal" {
  provisioner "local-exec" {
    command = "echo normal"
  }
}

resource "null_resource" "count" {
  count = var.should_create ? 1 : 0

  provisioner "local-exec" {
    command = "echo count"
  }
}

resource "null_resource" "for_each" {
  for_each = var.should_create ? toset(["foo"]) : toset([])

  provisioner "local-exec" {
    command = "echo for_each"
  }
}

locals {
  id = null_resource.normal.id
  count_id = null_resource.count[0].id
  for_each_id = null_resource.for_each["foo"].id
}

output "normal" {
  value = local.id
}

output "count" {
  value = local.count_id
}

output "for_each" {
  value = local.for_each_id
}
```

Then, in `/tmp/repro/main.tf`, use the module above as follows:

```hcl
module "foo" {
  source = "./module"

  should_create = true
}

output "normal" {
  value = module.foo.normal
}

output "count" {
  value = module.foo.count
}

output "for_each" {
  value = module.foo.for_each
}
```

### Expected Behavior

You can run `apply` and `destroy` multiple times without errors.

### Actual Behavior

If you  run `apply` and then run `destroy` **twice**, on the second `destroy`, you get the error:

```
Error: Invalid index

  on module/main.tf line 29, in locals:
  29:   count_id = null_resource.count[0].id
    |----------------
    | null_resource.count is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on module/main.tf line 30, in locals:
  30:   for_each_id = null_resource.for_each["foo"].id
    |----------------
    | null_resource.for_each is object with no attributes

The given key does not identify an element in this collection value.
```

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`
1. `terraform destroy`
1. `terraform destroy`

### Additional Context

In my real use case, I get the exact same sort of error on the **first** `destroy`. I can't find a simple repro case to showcase that, but the structure is the same: 

1. A module that contains a resource `foo.bar` that uses `count` or `for_each`... 
1. A reference to `foo.bar[0]` or `foo.bar["some key"]` in a `local` or `output` variable. 
    1. Note that the *exact* same reference within another resource works just fine.
    1. Note also that references to resources that don't use `count` or `for_each` work fine too.
1. Works totally fine on `apply`.
1. On `destroy` , you get "The given key does not identify an element in this collection value" errors.

**Comment by apparentlymart** [comment] 2020-08-19 22:24
Hi @brikis98! Thanks for reporting this.

One way we've seen symptoms similar to this arise before is if some objects in the remote system are deleted outside of Terraform in a way that makes the configuration un-refreshable due to the required order of operations during evaluation. Terraform is usually able to automatically detect and respond to that sort of drift, but because intermediate objects like input variables, output values, and local values sometimes need to be resolved prior to planning there are some out-of-band deletion cases that Terraform can't currently handle, which we're hoping to address in a future release by merging the "refresh" and "plan" operations into a single combined step.

With all of that said, do you think it's possible that in your original case (the one that was too complicated to share) there was some deletion drift in a remote system?

I ask this because while it's indeed incorrect that running `terraform destroy` when everything is already destroyed would return an error, I would consider that as something separate from the problem of not fully handling deletion drift, because the former seems to be entirely within Terraform itself (it would ideally detect that those configuration constructs are irrelevant during destroy anyway) but the latter is caused by an unexpected result from the remote system, and so fixing exactly what you reported here might not address the original problem you saw.

Thanks again!

**Comment by brikis98** [comment] 2020-08-20 08:37
> With all of that said, do you think it's possible that in your original case (the one that was too complicated to share) there was some deletion drift in a remote system?

As far as I know, no, there isn't any drift. 

> I ask this because while it's indeed incorrect that running `terraform destroy` when everything is already destroyed would return an error, I would consider that as something separate from the problem of not fully handling deletion drift, because the former seems to be entirely within Terraform itself (it would ideally detect that those configuration constructs are irrelevant during destroy anyway) but the latter is caused by an unexpected result from the remote system, and so fixing exactly what you reported here might not address the original problem you saw.

Yea, as best as I can tell, this is 100% within Terraform itself. Some combination of (a) complicated dependency graph with lots of modules nested in modules, (b) `local` and `output` vars, (c) references to a resource that uses `count` or `for_each` leads to a failure on the first `destroy`. Unfortunately, I can't find a simplified example that repros this, except with two calls to `destroy`.

**Comment by danieldreier** [comment] 2020-09-29 20:57
@brikis98 I've put your reproduction case in a git repo at https://github.com/danieldreier/terraform-issue-reproductions/tree/master/25878 but when I run it against 0.13.3 I am unable to reproduce this and get the expected destroy behavior. Can you take a look and see if you're still running into this problem with 0.13.3? I'm not sure whether the actual problem is fixed in 0.13.x or if I've just reproduced it incorrectly.

**Comment by brikis98** [comment] 2020-10-06 07:43
@danieldreier I'm no longer able to repro with 0.13.4 on this simple use case. Not sure on the more complicated one, as I haven't had a chance to try that one again.

**Comment by jbardin** [comment] 2020-10-06 14:13
Thanks @brikis98,

The error encountered by running destroy multiple times would have been fixed with changes to the handling of expanded resources in the state that came with 0.13. Since the state is no longer responsible for recording the each mode of the resource, there shouldn't be a situation where the evaluation and the state can disagree in this manner. 

While the same error message could theoretically arise from other circumstances, I suspect the original case is also fixed, so am going to close this for now. If this bug comes up again, I suggest we start a new issue with more information.

Thanks!

**Closed by jbardin** 2020-10-06 14:13 UTC
Labels: bug, config, v0.12, waiting for reproduction
