### ISSUE TITLE
v1.1 crash - invalid memory address or nil pointer dereferencegoroutine 4773

### ISSUE THREAD

**Issue by detredwings02** [hashicorp/terraform#30162] opened 2021-12-14 13:53 UTC
Hi,

I'm running in TFC, when new workspaces created with v1.1, my code fails with this error.  When I use any v1.0.x it works fine.  This is during the plan phase.

----

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 4773 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x221d240, 0x3ed5b10})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc002529270, {{}, 0x4d, {0xc000b3dba0, 0x19}, {0xc000131ac0, 0x5}}, {0xc0036ee680, 0x40, 0x4})
/home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x51, {0xc0000de740, 0x0, 0xc00035ac00}, {{}, 0x4d, {0xc000b3dba0, 0x19}, {0xc000131ac0, 0x5}}, ...)
/home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc003230c18, {0xc0000de740, 0x1, 0x1}, {{}, 0x4d, {0xc000b3dba0, 0x19}, {0xc000131ac0, 0x5}}, ...)
/home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc002d19b20, {{}, {0xc0000de740, 0x1, 0x1}, {{}, 0x4d, {0xc000b3dba0, 0x19}, {0xc000131ac0, ...}}})
/home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc002616bb0, {0x2aecc00, 0xc0021097a0})
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:204 +0x23b
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc002616bb0, {0x2aecc00, 0xc0021097a0})
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc0021097a0}, 0x20)
/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000c9d260, {0x2aecc00, 0xc0021097a0}, {0x7f4d4f8a6870, 0xc002616bb0})
/home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc002616bb0})
/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0023a4960, {0x2553ec0, 0xc002616bb0}, 0xc003e15b00)
/home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
/home/circleci/project/project/internal/dag/walk.go:304 +0xf85

----

I have read other issues and seen that downgrading and waiting for v1.1.1 is likely the way to go.

Thanks,
Andrew

**Comment by ahamstra** [comment] 2021-12-14 21:30
Same issue on v1.1 just started occuring

**Comment by crw** [comment] 2021-12-15 18:35
Thanks for the report! We believe this to be a duplicate of https://github.com/hashicorp/terraform/issues/30110 - please test in v1.1.1 when it is released and feel free to re-open if you continue to have the issue, or you think this is being closed duplicate in error.

**Closed by crw** 2021-12-15 18:35 UTC
