### ISSUE TITLE
Creating aws_customer_gateway silently reuses existing CGW if peer IP and ASN match

### ISSUE THREAD

**Issue by dcondomitti** [hashicorp/terraform#9153] opened 2016-09-30 19:42 UTC
### Terraform Version
0.7.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_customer_gateway

### Terraform Configuration Files
```hcl
resource "aws_vpn_gateway" "vpn_gateway" {
    vpc_id = "${var.vpc_id}"
    count = "${lookup(var.enabled_lookup, var.enabled)}"

    tags = {
      "Name" = "vgw-${var.name}"
    }
}

resource "aws_customer_gateway" "customer_gateway" {
    bgp_asn = "${var.bgp_asn}"
    ip_address = "${var.vpn_peer_ip}"
    type = "ipsec.1"
    count = "${lookup(var.enabled_lookup, var.enabled)}"

    tags = {
      "Name" = "cgw-${var.name}"
    }
}
```

```
bgp_asn = 65000
vpn_peer_ip = "10.0.0.1"
name = "test-vpn"
vpc_id = "vpc-a0a0a0a0" # needs to be different from the VPC ID attached to the existing CGW
```

```
$ aws ec2 describe-customer-gateways
{
    "CustomerGateways": [
        {
            "Tags": [
                {
                    "Value": "existing-name",
                    "Key": "Name"
                }
            ],
            "Type": "ipsec.1",
            "State": "available",
            "CustomerGatewayId": "cgw-XXX",
            "BgpAsn": "65000",
            "IpAddress": "10.0.0.1"
        },
```

### Debug Output
Will submit sanitized output later

### Expected Behavior
Before reading the documentation for the [CreateCustomerGateway](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateCustomerGateway.html) API resource I expected this to create a new CGW.

I would expect a warning or an error stating that the desired resource conflicts with an existing CGW. This is documented in the EC2 API but not in the Terraform docs. I spoke with @kwilczynski and determined that querying the API to ensure that a conflicting CGW doesn't exist would be reasonable.

### Actual Behavior
When I created a new CGW using a peer IP and ASN that conflicted with an existing CGW the existing resource is silently returned as described in the documentation linked above.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create CGW in EC2 with ASN of 65000 and Peer IP of 1.2.3.4
2. Create CGW through Terraform with matching ASN but different VPC ID
3. `terraform apply`

### Important Factoids
I'm slowly replacing a CloudFormation-managed VPC and its components with Terraform but as I didn't explicitly import the resource I don't expect Terraform to take over management of it.

### References
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateCustomerGateway.html

**Comment by stack72** [comment] 2016-10-01 19:22
Hi @dcondomitti 

I am going to replace this as a duplicate of https://github.com/hashicorp/terraform/issues/7492

I have had to raise this as a bug with AWS as this is the behaviour of their API and CLI

P.

**Comment by dcondomitti** [comment] 2016-10-01 19:24
Oh wow, not sure how I missed that. I'll follow that, thanks!

**Closed** 2016-10-01 19:23 UTC
Labels: bug, provider/aws
