### ISSUE TITLE
Terraform init crashed

### ISSUE THREAD

**Issue by soniadas0210** [hashicorp/terraform#32760] opened 2023-03-01 12:27 UTC
### Terraform Version

```shell
Terraform v1.3.9

Azurem Provider v3.45.0
```

### Terraform Configuration Files

Not specific to any configuration file

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
interface conversion: interface {} is int, not string
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
[github.com/hashicorp/terraform/internal/logging.PanicHandler()](http://github.com/hashicorp/terraform/internal/logging.PanicHandler())
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x225d240, 0xc000def9b0})
	/usr/local/go/src/runtime/panic.go:890 +0x262
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).getChild(0x2b723b0?, {0x21449a0?, 0xc000a5d5c0?})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:145 +0x125
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).applyAsSlice(0x2b723b0?, {{{0x2b723b0?, 0xc000e40060?}}, {0x20f6480?, 0xc000e40078?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:116 +0x111
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).apply(0xc0000a95c0, {{{0x2b723b0?, 0xc000e40060?}}, {0x20f6480?, 0xc000e40078?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:62 +0x2b2
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).applyAsMap(0x2b72340?, {{{0x2b72340?, 0xc000e2cef0?}}, {0x221f940?, 0xc000def080?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:130 +0x174
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).apply(0xc0000a95e0, {{{0x2b72340?, 0xc000e2cef0?}}, {0x221f940?, 0xc000def080?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:85 +0x575
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).applyAsMap(0x2b72340?, {{{0x2b72340?, 0xc000e2cf00?}}, {0x221f940?, 0xc000def0e0?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:130 +0x174
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).apply(0xc0000a9620, {{{0x2b72340?, 0xc000e2cf00?}}, {0x221f940?, 0xc000def0e0?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:85 +0x575
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).applyAsMap(0x2b72340?, {{{0x2b72340?, 0xc000e2cf10?}}, {0x221f940?, 0xc000def140?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:130 +0x174
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).apply(0xc0000a9680, {{{0x2b72340?, 0xc000e2cf10?}}, {0x221f940?, 0xc000def140?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:85 +0x575
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).applyAsSlice(0x2b723b0?, {{{0x2b723b0?, 0xc000e40090?}}, {0x20f6480?, 0xc000e400a8?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:117 +0x1f0
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).apply(0xc0000a96a0, {{{0x2b723b0?, 0xc000e40090?}}, {0x20f6480?, 0xc000e400a8?}})
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:62 +0x2b2
[github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults](http://github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults)).Apply(...)
	/home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.16.0/ext/typeexpr/defaults.go:42
[github.com/hashicorp/terraform/internal/configs.decodeVariableBlock](http://github.com/hashicorp/terraform/internal/configs.decodeVariableBlock)(0xc000dc9c70, 0x0)
	/home/circleci/project/project/internal/configs/named_values.go:148 +0xc05
[github.com/hashicorp/terraform/internal/configs.(*Parser](http://github.com/hashicorp/terraform/internal/configs.(*Parser)).loadConfigFile(0xc00056b500, {0xc000c8b290?, 0x10?}, 0x0?)
	/home/circleci/project/project/internal/configs/parser_config.go:119 +0xda5
[github.com/hashicorp/terraform/internal/configs.(*Parser](http://github.com/hashicorp/terraform/internal/configs.(*Parser)).LoadConfigFile(...)
	/home/circleci/project/project/internal/configs/parser_config.go:22
[github.com/hashicorp/terraform/internal/configs.(*Parser](http://github.com/hashicorp/terraform/internal/configs.(*Parser)).loadFiles(0x12?, {0xc00082b700?, 0xa, 0x0?}, 0x0)
	/home/circleci/project/project/internal/configs/parser_config_dir.go:77 +0x125
[github.com/hashicorp/terraform/internal/configs.(*Parser](http://github.com/hashicorp/terraform/internal/configs.(*Parser)).LoadConfigDir(0xc000a5ef88?, {0x25bb02e, 0x1})
	/home/circleci/project/project/internal/configs/parser_config_dir.go:37 +0xb3
[github.com/hashicorp/terraform/internal/configs/configload.(*Loader](http://github.com/hashicorp/terraform/internal/configs/configload.(*Loader)).LoadConfig(0xc000aa8eb0, {0x25bb02e?, 0x42?})
	/home/circleci/project/project/internal/configs/configload/loader_load.go:22 +0x33
[github.com/hashicorp/terraform/internal/command.(*Meta](http://github.com/hashicorp/terraform/internal/command.(*Meta)).loadConfig(0x0?, {0xc00005c0f4?, 0x0?})
	/home/circleci/project/project/internal/command/meta_config.go:47 +0x98
[github.com/hashicorp/terraform/internal/command.(*InitCommand](http://github.com/hashicorp/terraform/internal/command.(*InitCommand)).Run(0xc0005831e0, {0xc000120170, 0x1, 0x1})
	/home/circleci/project/project/internal/command/init.go:207 +0x13bd
[github.com/mitchellh/cli.(*CLI](http://github.com/mitchellh/cli.(*CLI)).Run(0xc000174640)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.realMain()
	/home/circleci/project/project/main.go:315 +0x15d4
main.main()
	/home/circleci/project/project/main.go:58 +0x19
```

### Expected Behavior

NA

### Actual Behavior

Terraform init is throwing the error with "TERRAFORM CRASHED"

### Steps to Reproduce

`terraform init`

**Comment by jbardin** [comment] 2023-03-01 13:49
Duplicate of #32752

**Closed by jbardin** 2023-03-01 13:49 UTC
Labels: bug, new
