### ISSUE TITLE
terraform plan returns a weird output

### ISSUE THREAD

**Issue by JustLolo** [hashicorp/terraform#31677] opened 2022-08-22 18:42 UTC
### Terraform Version

```shell
Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.27.0
```

### Terraform Configuration Files

```terraform

data "aws_subnet" "selected" {
  id = var.subnet_id
}

data "aws_security_groups" "test" {
  filter {
    name   = "group-id"
    values = [var.sg_id]
  }
}


```

### Debug Output

data.aws_subnet.selected: Reading...
data.aws_security_groups.test: Reading...
data.aws_subnet.selected: Read complete after 0s [id=subnet-xxxx]
data.aws_security_groups.test: Read complete after 1s [id=us-east-1]

### Expected Behavior

data.aws_security_groups.test: Read complete after 1s [id=us-east-1] 
the line above should return the sg-id instead of the region

### Actual Behavior

data.aws_security_groups.test: Read complete after 1s [id=us-east-1]

### Steps to Reproduce

terraform plan

**Comment by apparentlymart** [comment] 2022-08-22 23:35
Hi @JustLolo!

The behavior you are describing is implemented by the AWS provider rather than by Terraform Core: providers can specify whichever value they like for `id` and Terraform CLI will just show it without any knowledge about what it really represents in a remote system.

With that said, it sounds like the `aws_security_groups` data source is a plural data source returning more than one security group and so I guess there probably isn't a single ID to return (there could be many) and so perhaps the provider developers chose to use the region name as the most "unique ID" available for that query, if this data source represents a set of security groups belonging to a particular region.

If you'd like to share this feedback with the AWS provider team then you could open an issue about it in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws). However, I can see in hashicorp/terraform-provider-aws#15896 that selecting the region here seems to have been intentional (it was mentioned specifically in the changelog update text) and so I expect the provider team would consider this to be a feature request (changing the intended behavior to meet a new use-case) rather than a bug (changing the code so that it matches the intended behavior).

Because we use issues in this repository only to represent bugs and feature requests for Terraform Core and not for providers, I'm going to close this issue. Thanks!

**Closed by apparentlymart** 2022-08-22 23:35 UTC
Labels: bug, new
