### ISSUE TITLE
Fine-grained dependency graph for `for_each` and `count`

### ISSUE THREAD

**Issue by XieGuochao** [hashicorp/terraform#32077] opened 2022-10-25 09:19 UTC
### Terraform Version

```shell
Terraform v1.3.3
on linux_amd64
+ provider registry.terraform.io/oracle/oci v4.96.0
```

### Use Cases

Basically, I am trying to get a more fine-grained dependency for `for_each`. Let's see the following example on OCI (which can also be ported to AWS):

```
variable "region" {
  default = "us-phoenix-1"
}

variable "config_file_profile" {
  default = "DEFAULT"
}

variable "compartment_id" {
  type = string
}

locals {
  vcns = {
    "n1" = {}
    "n2" = {}
  }
}

resource "oci_core_vcn" "internal" {
  for_each       = local.vcns
  dns_label      = "internal"
  cidr_block     = "172.16.0.0/20"
  compartment_id = var.compartment_id
  display_name   = each.key
}

resource "oci_core_subnet" "dev" {
  for_each                   = oci_core_vcn.internal
  vcn_id                     = each.value.id
  cidr_block                 = "172.16.1.0/24"
  compartment_id             = var.compartment_id
  display_name               = each.key
  prohibit_public_ip_on_vnic = true
  dns_label                  = "dev"
}

provider "oci" {
  region              = var.region
  config_file_profile = var.config_file_profile
}

terraform {
  required_providers {
    oci = {
      source = "oracle/oci"
    }
  }
}

```

We create 2 virtual cloud networks and one subnet for each of the VCN. In the `for_each` creating subent, we pass in the VCN resource so that we don't duplicate resource blocks.There are many other use cases, like creating multiple instances on multiple subnets, creating multiple api gateways for lambda functions... In many scenarios, `for_each` seems to be a proper choice.

However, if we create the graph of the plan's result, such fine-grained dependency does not preserve anymore.

```
terraform plan -out=plan.bin
terraform graph -plan=plan.bin | dot -Tsvg > graph_plan.svg
```

We will see the following graph:
![graph_plan](https://user-images.githubusercontent.com/35591503/197731704-ea673b18-52ba-491f-af36-4b0d239dbad2.svg)
and this is the dot file:

```
digraph {
	compound = "true"
	newrank = "true"
	subgraph "root" {
		"[root] oci_core_subnet.dev (expand)" [label = "oci_core_subnet.dev", shape = "box"]
		"[root] oci_core_subnet.dev[\"n1\"]" [label = "oci_core_subnet.dev", shape = "box"]
		"[root] oci_core_subnet.dev[\"n2\"]" [label = "oci_core_subnet.dev", shape = "box"]
		"[root] oci_core_vcn.internal (expand)" [label = "oci_core_vcn.internal", shape = "box"]
		"[root] oci_core_vcn.internal[\"n1\"]" [label = "oci_core_vcn.internal", shape = "box"]
		"[root] oci_core_vcn.internal[\"n2\"]" [label = "oci_core_vcn.internal", shape = "box"]
		"[root] provider[\"registry.terraform.io/oracle/oci\"]" [label = "provider[\"registry.terraform.io/oracle/oci\"]", shape = "diamond"]
		"[root] var.compartment_id" [label = "var.compartment_id", shape = "note"]
		"[root] var.config_file_profile" [label = "var.config_file_profile", shape = "note"]
		"[root] var.region" [label = "var.region", shape = "note"]
		"[root] oci_core_subnet.dev (expand)" -> "[root] oci_core_vcn.internal[\"n1\"]"
		"[root] oci_core_subnet.dev (expand)" -> "[root] oci_core_vcn.internal[\"n2\"]"
		"[root] oci_core_subnet.dev[\"n1\"]" -> "[root] oci_core_subnet.dev (expand)"
		"[root] oci_core_subnet.dev[\"n2\"]" -> "[root] oci_core_subnet.dev (expand)"
		"[root] oci_core_vcn.internal (expand)" -> "[root] local.vcns (expand)"
		"[root] oci_core_vcn.internal (expand)" -> "[root] provider[\"registry.terraform.io/oracle/oci\"]"
		"[root] oci_core_vcn.internal[\"n1\"]" -> "[root] oci_core_vcn.internal (expand)"
		"[root] oci_core_vcn.internal[\"n1\"]" -> "[root] var.compartment_id"
		"[root] oci_core_vcn.internal[\"n2\"]" -> "[root] oci_core_vcn.internal (expand)"
		"[root] oci_core_vcn.internal[\"n2\"]" -> "[root] var.compartment_id"
		"[root] provider[\"registry.terraform.io/oracle/oci\"] (close)" -> "[root] oci_core_subnet.dev[\"n1\"]"
		"[root] provider[\"registry.terraform.io/oracle/oci\"] (close)" -> "[root] oci_core_subnet.dev[\"n2\"]"
		"[root] provider[\"registry.terraform.io/oracle/oci\"]" -> "[root] var.config_file_profile"
		"[root] provider[\"registry.terraform.io/oracle/oci\"]" -> "[root] var.region"
		"[root] root" -> "[root] provider[\"registry.terraform.io/oracle/oci\"] (close)"
	}
}
```

As we can see, Terraform creates an `expand` node for the subnet and both subnets will wait for the two vcns to be both created. However, a fine-grained dependency like the following is what we expect.
![graph_plan](https://user-images.githubusercontent.com/35591503/197732240-1e2ad0d2-5a4e-44d5-9a10-4ba044499e74.svg)

From what I see, I observe that the `subnet (expand)` node will be blocked until all vcns nodes are created, and the two `subnet` nodes will be blocked until the `subnet (expand)` node is ready. However, the better is to have a more fine-grained dependency for the elements created with `for_each`.

The `count` expression is similar.

This feature would be influential for the following use case:
1. Enhance parallel execution performance.
2. Enhance visualization for the configuration using `for_each`.

### Attempted Solutions

To bypass the current limitation, one solution is to ask the user does not use `for_each` and `count`. Or they have to tolerate a coarse graph. 

### Proposal

This feature might need to change significantly the terraform execution engine on how to handle `count` and `for_each`. Another challenge is to handle the type of the resources created by `for_each`: these resources are a map of a specific resource instead of an arbitary map/object.

When interpolating `each.key` and `each.value`, we can resolve the dependency using the object **with index**.

However, I cannot estimate the complexity of implementing this feature.

**Comment by jbardin** [comment] 2022-10-25 12:47
Hi @XieGuochao,

Thanks for filing the issue. We are tracking this request in #23735 (all the linked issue can be reduced to the same primary requirement). The underlying architecture of Terraform relies on tracking dependencies between resources as a whole, so it would be major undertaking to rewrite how these dependencies are handled. Some research was done prior to v1.0 to determine feasibility, but it was a much larger rewrite of core behavior than could be accomplished in the given amount of time.

Duplicate of #23735

Thanks!

**Closed by jbardin** 2022-10-25 12:47 UTC
Labels: enhancement, new
