### ISSUE TITLE
Google provider: Use GOOGLE_APPLICATION_CREDENTIALS environment file

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/terraform#12626] opened 2017-03-12 23:15 UTC
Most Google client code uses the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to designate a path to the credentials JSON file to open.  

Examples:

* https://developers.google.com/identity/protocols/application-default-credentials#howtheywork
* https://github.com/google/google-api-ruby-client/blob/v0.10/samples/cli/README.md
* https://github.com/google/google-auth-library-php

Terraform should be able to use it too. 

(Note that this is separate from the existing support for the `GOOGLE_CREDENTIALS` environment variable, in which the *actual* JSON must be placed, as opposed to a path to a file containing it.  I'm curious about the history behind that; it's very unusual to place JSON -- especially JSON containing secrets -- in an environment variable.)

**Comment by paddyforan** [comment] 2017-03-15 19:25
Hi! Thanks for reporting the issue. On the one hand, I'm reluctant to continue to add environment variable options, just because they seem to be ever expanding and I'm terrified of bloat.

On the other hand, historically we have shown a disposition to try and match the official tools in terms of which environment variables we accept.

(As for why the `GOOGLE_CREDENTIALS` environment variable requires the contents and not the path, I can't say; I can't find any discussion around it to elucidate the reasoning. If I had to guess, I'd say it's to match other providers, where credentials aren't JSON, so they're mostly just supplied as environment values, not a path. I'd imagine this makes it easier for multi-provider tooling, but don't quote me on this, as it's all guesswork. If you're uncomfortable about placing secrets in an environment variable, I'm a big fan of using the [vault_generic_secret data source](https://www.terraform.io/docs/providers/vault/d/generic_secret.html) to configure my providers.)

**Comment by mfischer-zd** [comment] 2017-03-15 19:43
> historically we have shown a disposition to try and match the official tools in terms of which environment variables we accept.

I think it would also be consistent with user expectations.

I am sympathetic to concerns about bloat, but it's important to maintain perspective.  Bloat is problematic when it fails to serve a purpose, but if excessive configurability options are there due to reasons outside your control, there's little that can be done about it.

**Comment by paddyforan** [comment] 2017-03-15 20:13
> I am sympathetic to concerns about bloat, but it's important to maintain perspective.

Agreed. I'm leaning towards implementing this, I just want to talk a bit more with Google to git a bit more perspective and hear more thoughts on it. I expect that to happen tomorrow. I just didn't want to leave you hanging with no word on this. :)

>  I'm as big a fan of Vault as anyone, but I wouldn't ask anyone to learn it and maintain it for this purpose alone; and we can't make it a requirement to use Terraform for GCP.

Agreed. That wasn't meant to be construed as general advice or a requirement; Terraform certainly does and should continue to work without anyone using Vault. The only reason I mentioned it was because you seem concerned about the security implications of environment variables, and it seemed relevant to share one of the lesser-known but more-secure ways to connect to Terraform. Apologies for not putting that aside in better context.

**Comment by paddyforan** [comment] 2017-03-16 22:59
So after talking to @danawillow to get some better perspective on this one, it sounds like something we'd like to support. I'll tackle this once 0.9.1 is out. Thanks for bringing it up. :)

**Comment by danawillow** [comment] 2017-04-03 16:57
So I was just looking through some of the GCP IAM docs / terraform authentication code and it looks like if credentials aren't specified in terraform, it _should_ look for the application default credentials. I just did a quick check and I was able to create resources without specifying `provider.google.credentials` (I'm logged in with gcloud). Can someone else verify?

**Comment by chiefy** [comment] 2017-04-03 17:18
@danawillow I can confirm - using `0.9.2`, new GCP account with *no* projects. 

```
cloud auth application-default login
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=....

Credentials saved to file: [/Users/xxxxx/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests
Application Default Credentials.
```
TF plan seems to execute just fine.

**Comment by danawillow** [comment] 2017-04-03 17:47
Cool! I'm going to go ahead and close this since it seems to be working already. @mfischer-zd, feel free to reopen if you're seeing something different.

**Comment by paddyforan** [comment] 2017-04-03 19:20
I think we may be talking about two different things here.

I think @danawillow and @chiefy are talking about Terraform automatically picking up credentials from (on Linux/macOS) `~/.config/gcloud/credentials`, which it sounds like it does.

I think @mfischer-zd is talking about how to _override_ that location, which `GOOGLE_APPLICATION_CREDENTIALS` as an env var does for the official libraries.

Is that a good summary?

**Comment by mfischer-zd** [comment] 2017-04-03 19:39
@paddyforan that is correct.  However, I cannot reopen this issue as I don't have permissions to do so.

**Comment by paddyforan** [comment] 2017-04-03 19:41
I have that happy power! I'll reopen to track adding the environment variable.

**Comment by danawillow** [comment] 2017-04-03 20:52
ohhhh that makes sense. Thanks for the explanation!

**Comment by paddycarver** [comment] 2017-04-28 23:20
So, funny story, the environment variable has actually been supported for a while now. By my estimation, since at least December 14th. IT just was part of the OAuth2 library we're using, so it was never documented. But my tests show it works.

I've opened #14084 to add the information to the website. I'll close this out now. If you have any questions or if I'm missing something, feel free to comment and we'll reopen this.

**Closed by paddycarver** 2017-04-28 23:20 UTC
Labels: enhancement, provider/google-cloud
