### ISSUE TITLE
terraform plan errors out with: "Error: Invalid depends_on reference"

### ISSUE THREAD

**Issue by mnowrot** [hashicorp/terraform#25975] opened 2020-08-24 07:44 UTC
I'm using terraform 0.13 with terraform-aws-modules/eks/aws to set up a EKS cluster in AWS. I'd like to defer any modules that are supposed to install Kubernetes objects to the point in time in which EKS is fully initialized and running. Hence my output.tf is as follows:

```hcl
output "outval" {
  value = local.local_val

  # define explicit depends on, as jobs on eks are run even before workers are up and running
  depends_on = [module.terraform_eks.aws_autoscaling_group.workers]
}
```

Expected behavior:
Terraform plan executes w/o issues. Terraform apply respects the dependency given above

Actual behavior:
Terraform plan fails with:
```
Error: Invalid depends_on reference

  on aws-services/eks/outputs.tf line 21, in output "outval":
  21:   depends_on = [module.terraform_eks.aws_autoscaling_group.workers]

References in depends_on must be to a whole object (resource, etc), not to an
attribute of an object.
```

The point is, according to: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf
workers IS the whole object (it is a resource with a count).

Below is my configuration that was working in 0.12 (notice the [0] index - in 0.13 it stops with the same error):
```hcl
output "outval" {
  value = local.local_val

  # define explicit depends on, as jobs on eks are run even before workers are up and running
  depends_on = [module.terraform_eks.aws_autoscaling_group.workers[0]]
}
```

**Comment by mildwonkey** [comment] 2020-08-25 19:38
Hi @mnowrot ! I'm sorry you're experiencing this unexpected behavior; thank you for opening this issue.

This is the expected behavior: the documentation states that the dependency must be from a resource [in the same module](https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies). 

We had never intended to allow references to other modules inside a resource's depends_on block, which is why this change wasn't easy to find in the changelog - it's in there as a bug fix: https://github.com/hashicorp/terraform/pull/25261
I suspect that it never really "worked" as expected: terraform 0.12 may have simply taken that as a dependency on a non-existent output. 

Sorry for the unsatisfying answer, but there's no bug here so I am going to close this issue. 

If you need any suggestions on refactoring your module I suggest asking in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!

**Closed by mildwonkey** 2020-08-25 19:38 UTC
Labels: explained
