### ISSUE TITLE
Error: Could not satisfy plugin requirements when destroying `random_id` resource

### ISSUE THREAD

**Issue by mcaballeropinto** [hashicorp/terraform#25736] opened 2020-08-03 22:18 UTC
### Terraform Version

```
Terraform v0.12.29
+ provider.google v3.32.0
+ provider.random v2.3.0
```

### Terraform Configuration Files

I had this resource before, now I am trying to remove it
```terraform
resource "random_id" "name_suffix" {
  byte_length = 4
}
```

### Debug Output

https://gist.github.com/mcaballeropinto/bab067680e16255d99426e4b5e807c9f

### Expected Behavior

Then running `terraform apply`, the resource `random_id.name_suffix` is destroyed successfuly.

### Actual Behavior

These error is presented:
```
Error: Could not satisfy plugin requirements


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".



Error: provider.random: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
```

### Steps to Reproduce

1. Add a `random_id` resource.
1. Apply the changes 
1. Remove the resource
1. Apply the changes

### Additional Context

- When I run `terraform plan` the operation is run successfully
- Running `terraform init` as suggested by the error does not fix the issue

### References

N/A

**Comment by danieldreier** [comment] 2020-08-13 16:41
Hi @mcaballeropinto! I have tried to reproduce this, and was not able to. I created a reproduction case at https://github.com/danieldreier/terraform-issue-reproductions/tree/master/25736 to show that this is successful. I've tried it on 0.12.29, and 0.13.0. If you're still running into this, can you please make a PR against that reproduction case to show how to reproduce it?

**Comment by mcaballeropinto** [comment] 2020-08-24 23:12
@danieldreier One difference between your repro and my scenario is that I used the generated id for naming a resource, then tried to delete that resource and the random_id one. Maybe that is why you do not reproduce.

**Comment by apparentlymart** [comment] 2021-01-13 19:05
Hi @mcaballeropinto! Sorry for the delay in getting back to you here.

After reviewing the trace log you shared, it looks to me like what you experienced is a behavioral quirk specific to Terraform Cloud, where there's an additional implementation detail that the plan and apply happen on different transient machines. It seems like for some reason the installed providers didn't correctly propagate from the plan phase to the apply phase.

The Terraform Core team doesn't have the necessary access to debug a Terraform Cloud operational issue like that, so if you still have a similar problem I'd suggest contacting the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you let them know your Terraform Cloud username, organization name, and workspace name in your request then they will be in a better position to look more closely at specifically what happened in your case and hopefully suggest a fix.

Since it doesn't seem like the Terraform Core team will be able to take any action based on this without more information, I'm going to close this issue for now. If it does turn out to have a root cause in Terraform CLI then the Cloud support team will send any additional information they've learned to us on the Terraform Core team so we can take a fresh look at it.

Thanks, and sorry again for being slow to respond here.

**Closed by apparentlymart** 2021-01-13 19:05 UTC
Labels: backend/remote, bug, terraform-cloud, v0.12, waiting for reproduction
