### ISSUE TITLE
Unable to add entire variable to dynamic content block

### ISSUE THREAD

**Issue by mcaulifn** [hashicorp/terraform#27600] opened 2021-01-26 17:21 UTC
I am attempting to set dynamic `lifecycle_rules` for an s3 bucket. Most attributes are optional. 

### Terraform Version
```
Terraform v0.14.2
```

### Terraform Configuration Files
```terraform
locals {
  lifecycle_rules = [
    {
      id = "test1"
      abort_incomplete_multipart_upload_days = 7

    }
  ]
}

resource "aws_s3_bucket" "action_dist" {
  bucket        = var.distribution_bucket_name
  acl           = "private"
  force_destroy = true
  tags          = var.tags

  dynamic "lifecycle_rule" {
    for_each = local.lifecycle_rules

    content {
        lifecycle_rule.value
    }
  }

}
```

### Expected Behavior
A `lifecycle_rule` block is created for each rule with the content of that rule.

### Actual Behavior
```
Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
```

### Steps to Reproduce
`terraform plan`

### Additional Context
I also tried the this but it errors out if an attribute is not included:
```terraform
content {
        id = lifecycle_rule.value.id != null ? lifecycle_rule.value.id : null
        prefix = lifecycle_rule.value.prefix != null ? lifecycle_rule.value.prefix : null
        tags = lifecycle_rule.value.tags != null ? lifecycle_rule.value.tags : {}
        enabled = lifecycle_rule.value.enabled != null ? lifecycle_rule.value.enabled : true
        abort_incomplete_multipart_upload_days = lifecycle_rule.value.abort_incomplete_multipart_upload_days != null ? lifecycle_rule.value.abort_incomplete_multipart_upload_days : null
        expiration = lifecycle_rule.value.expiration != null ? lifecycle_rule.value.expiration : null
        transition = lifecycle_rule.value.transition != null ? lifecycle_rule.value.transition : null
        noncurrent_version_expiration = lifecycle_rule.value.noncurrent_version_expiration != null ? lifecycle_rule.value.noncurrent_version_expiration : null
        noncurrent_version_transition = lifecycle_rule.value.noncurrent_version_transition != null ? lifecycle_rule.value.noncurrent_version_transition : null
    }
```

### References
Possibly similar to #26701

**Comment by apparentlymart** [comment] 2021-01-28 22:46
Hi @mcaulifn,

With the language as currently designed, Terraform is working as intended here: nested blocks are fixed structures with a required set of arguments, not a dynamic data structure you can just assign a value to.

With that in mind, I've relabeled this as a feature request. Restating your report as a use-case, I understand it as follows:

I want to be able to dynamically populate a nested block from the contents of an object value, without having to specify each of the arguments independently.

Terraform's current design is this way because it allows Terraform to verify that all of the expected arguments are set. If it were dynamic then there would be situations where that validation would need to be deferred until the apply step (because the values aren't know yet during planning) and would therefore create more risk of an apply failing partway through. However, that doesn't mean we can't investigate the tradeoff of accepting that risk in return for making it more convenient to populate a block, and also possibly investigate other strategies such as using a different configuration model for `lifecycle_rule` if it's _common_ for it to be set dynamically, and so we'll use this issue to represent that research and design work.

**Comment by frimik** [comment] 2022-05-04 21:34
Not sure if this is exactly the same, but seems quite related when reading your explanation @apparentlymart . Any unknown value inside of dynamic blocks makes the entire block "disappear" it seems.

I'm attempting to dynamically populate a security group with security group rules in one module, based on output from one or several other modules which create resources, including this security group.

So right now it requires **two runs of terraform**, one to let the security group get created so the security group id is known, followed by the next run then where the dynamic block(s) will be properly included in the plan and apply.

I understand it language wise, but it's a bit of a gotcha too because the entire object I want to use in the dynamic block is right there, fully visible if you include it in an `output` value, except that the security_group element is `(known after apply)`...


@apparentlymart 
I'm not straining it too much to have initially expected this to to work rather than silently disappear from the dynamic block where I'm trying to use it, right?

I guess my feature request would be simplified as the statement: Let **me** (the operator) take responsibility for the potential failure rather than "helping" me by preventing it altogether.

Thanks!


```hcl
resource "aws_security_group" "node_extra" {
  name        = "${var.cluster_name}-node-extra"
  description = "${var.cluster_name} Node Extra Security Group"
  vpc_id      = var.aws_account.vpc_id

  dynamic "ingress" {
    for_each = [
      for i in var.node_security_group_rules : {
        cidr_blocks     = i.cidr_blocks
        description     = i.description
        from_port       = i.from_port
        protocol        = i.protocol
        # security_groups = i.security_groups
        # above will make this entire block "disappear" silently from the plan
        # because of unknown value until the second run of terraform where value will be known
        
        # Having the value known will make this block "appear" ...:
        security_groups = ["foo-bar"]
        to_port         = i.to_port
        self            = i.self
      }
    ]

    content {
      cidr_blocks     = ingress.value.cidr_blocks
      description     = ingress.value.description
      from_port       = ingress.value.from_port
      protocol        = ingress.value.protocol
      security_groups = ingress.value.security_groups
      to_port         = ingress.value.to_port
      self            = ingress.value.self
    }
  }
```

**Comment by apparentlymart** [comment] 2022-05-05 13:24
Hi @frimik,

The behavior you are describing with unknown values is not familiar to me as you've described it here. I think it would be best to start a new issue for it and complete the issue template so we can see more about what's going on there and how to reproduce it. If it does turn out to be a restatement of this feature request then we can always merge the topics back together later. (If you do create an issue, please link to this one from the issue template section that calls for references to other relevant issues, so we can see the connection between the two.)

Thanks!

**Comment by pfif** [comment] 2023-05-16 09:42
Hello! Hope you are all doing fine.

I was wondering if there was any news on the implementation of this feature request?

Thank you!

**Comment by apparentlymart** [comment] 2023-05-16 14:25
Hi all,

The current treatment of nested blocks cannot change because lots of existing provider logic relies on the guarantee that a nested block will always appear as a known value with a specific data structure. Therefore this feature request is infeasible to meet and so I'm going to close it.

Newer providers written with the Terraform plugin framework have the option to ignore the nested block concert entirely and use normal arguments for everything, including objects and collections of objects. This allows the more general treatment this issue wanted, but in a way that a provider opts into by using the new framework features. This avoids breaking older providers because they can continue to rely on the existing guarantees for blocks.

This is the best we can achieve within Terraform's compatibility promises to providers. Providers will gradually transition to using the new framework and its features.

**Closed by apparentlymart** 2023-05-16 14:25 UTC
Labels: enhancement, config
