### ISSUE TITLE
Terraform 0.14 plan breaks filebase64sha256 behavior(?)

### ISSUE THREAD

**Issue by fumantsu** [hashicorp/terraform#27939] opened 2021-02-26 16:05 UTC
### Terraform Version

```
v0.14.5
```

### Terraform Configuration Files

```data "archive_file" "cloudwatch_collector" {

  type        = "zip"
  source_dir  = "${path.module}/src/cloudwatch_collector"
  output_path = "/tmp/cloudwatch_collector.zip"

}

resource "aws_lambda_function" "cloudwatch_collector" {

  filename         = data.archive_file.cloudwatch_collector.output_path

  function_name    = "Cloudwatch_Collector"
  timeout          = 120
  memory_size      = 128
  handler          = "main.lambda_handler"
  source_code_hash = filebase64sha256(data.archive_file.cloudwatch_collector.output_path)
  runtime          = "python3.8"
  depends_on       = [data.archive_file.cloudwatch_collector]
...
```

### Expected Behavior

During terraform plan, ignore or read later the zip file hash

### Actual Behavior

```
Call to function "filebase64sha256" failed: no file exists at
/tmp/cloudwatch_collector.zip; this function works only with files that are
distributed as part of the configuration source code, so if this file will be
created by a resource in this configuration you must instead obtain this
result from an attribute of that resource.
```

### Steps to Reproduce

terraform plan

### Additional Context

The different behavior in plan is started after upgrade from 0.13 to 0.14.
The scenario is that Lambda Layer resource can't work nicely with other than filebase64sha256 because otherwise every time updates the sha, destroy the resource and create new even if there is no update in the code.

**Comment by jbardin** [comment] 2021-02-26 16:36
Hi @fumantsu,

There were no changes to the `filebase64sha256` function in the 0.14 release, so what you're seeing here is probably the result of other differences in 0.14. Because the argument to `filebase64sha256` is a data source,  and 0.14 made large changes in the handling of data sources to improve how they are evaluated during planning, it is likely the behavior of `data.archive_file.cloudwatch_collector.output_path` that has changed. In most cases this is to prevent the data source from supplying "stale" data which would not be correctly evaluated from what used to be the refresh operation. 

Can you supply a more complete example that demonstrates your issue?

**Comment by fumantsu** [comment] 2021-03-01 19:56
Hi @jbardin, I understand your point. 
As I said with 0.13 I was using the `filebase64sha256 `with argument the `data archive_file` `output path` in a `aws_lambda_layer_version` resource because it was the only way the hash to be pre-evaluated and supplied to the `source_code_hash` and NOT cause the resource to be destroyed. Any other way and especially using  `data archive_file` `output_base64sha256`  is causing the `aws_lambda_layer_version` resource to be destroyed first
Now with 0.14 during planning I can't use it if I haven't create some dummy file first or the file isn't created before, `filebase64sha256` is complain and anything else works as usual negative regarding the lambda layer.
I getting that I use a workaround for the stupid(?) behavior of `aws_lambda_layer_version` but I don't see also something that will be help my case.

**Comment by jbardin** [comment] 2021-03-01 21:41
Thanks for the info @fumantsu, but what we need here is the your configuration, or an equivalent reproduction of the problem you are having. The difference is not in the `filebase64sha256` function itself, but in the fact that the data source could not be evaluated during planning. In order to determine what changes between 0.13 and 0.14 might be impacting you, we need to see why the data source is not being evaluated in 0.14.

The following is an example of using the data source as you describe, and will plan and execute correctly in 0.14:

```
data "archive_file" "zip" {
  type = "zip"
  source_file = "main.tf"
  output_path = "./out.zip"
}

resource "null_resource" "a" {
  triggers = {
    hash = filebase64sha256(data.archive_file.zip.output_path),
  }
}
```

**Comment by fumantsu** [comment] 2021-03-10 19:18
Hi,
So I tried the suggestion as it was and no issues with plan.
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.a will be created
  + resource "null_resource" "a" {
      + id       = (known after apply)
      + triggers = {
          + "hash" = "eOb4loI/cyPlQtFtIoXokFkNX9+m467SeiAG3vLWG5g="
        }
    }
```

Plan: 1 to add, 0 to change, 0 to destroy.

I started to add something close to my case like path.module and source_dir and again no issue.

```
data "archive_file" "zip" {
  type = "zip"
  source_dir = "${path.module}/test"
  output_path = "${path.module}/out.zip"
}

resource "null_resource" "a" {
  triggers = {
    hash = filebase64sha256(data.archive_file.zip.output_path),
  }
}
```

**Comment by fumantsu** [comment] 2021-03-10 19:36
@jbardin The test is with null_resource. I mention that my issue with using similar way with the `aws_lambda_function` which of course I still have problem if I don't create manual the output file.
I guessing that they are not behaving the same even if they should.

**Comment by jbardin** [comment] 2021-03-10 19:47
Sorry @fumantsu, I must have misunderstood the last reply. The resources are evaluated the same regardless of the provider, so the structure of the configuration is more important than the actual resource types in this situation. Since there is no change to the `filebase64sha256` behavior itself, it appears that you have something in your configuration which is preventing the data source from being evaluated during the plan. 

We are gong to need some way to reproduce the issue you're seeing in order to offer any more insight.

Thanks!

**Comment by jbardin** [comment] 2021-04-01 20:22
We don't yet have a reproduction for this issue, so I'm going to close it back out.
The error here indicates that the file name argument to `filebase64sha256` does not exist. Since that function has not changed, nor does it behave differently for different resources, there must be some other issue in the config as a whole.

If you can create a complete configuration to reproduce the error, feel free to add the information here or file a new issue. You may also want to try with the upcoming 0.15 release, as it may provide better feedback about the error itself.

Thanks!

**Closed by jbardin** 2021-04-01 20:22 UTC
Labels: bug, v0.14, waiting for reproduction
