### ISSUE TITLE
Wrong provider version downloaded with pessimistic constraint operator "~>"

### ISSUE THREAD

**Issue by kevinscholz** [hashicorp/terraform#25762] opened 2020-08-06 14:34 UTC
### Terraform Version

```
Terraform v0.12.29
+ provider.aws v3.0.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = var.region
  version = "~> 2"
}
```

### Debug Output

https://gist.github.com/kevinscholz/0dedc77e0894eda838bab82da4cc6603

### Expected Behavior

We set the AWS provider version via pessimistic constraint operator: `version = "~> 2"`. It should then download (currently) v.2.70.0 on `terraform init`.

### Actual Behavior

`terraform init` downloads version 3.0.0 which should not happen. When the version constraint is set to `version = ">= 2, < 3"`, the correct version (2.70.0) is downloaded. The `terraform.required_version` setting shows the same behaviour.

### Steps to Reproduce

1. AWS provider in main.tf as mentioned above.
2. `terraform init`

**Comment by jdorothy** [comment] 2020-08-07 01:15
Just ran into this as well - I can confirm the same behavior on v12.28.

**Comment by danieldreier** [comment] 2020-08-07 14:18
I have reproduced this on 0.13.0 RC1 as well. One possible short-term workaround is that setting `version = "< 3"` works as expected.

**Comment by jbardin** [comment] 2020-08-08 01:43
Hello,

The pessimistic operator is intended to apply to the last segment of the provided version. The [documented example](https://www.terraform.io/docs/configuration/modules.html#module-versions)  for this is

- `~> 1.2.0`: any non-beta version `>= 1.2.0` and `< 1.3.0`, e.g. `1.2.X`
- `~> 1.2`: any non-beta version `>= 1.2.0` and `< 2.0.0`, e.g. `1.X.Y`

However because of this implied constraint based in the number of segments provided, only having the first segment doesn't make much sense in this case and should probably result in a warning or error.

**Comment by apparentlymart** [comment] 2020-08-18 22:03
I'm not able to reproduce this on Terraform v0.13.0:

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 2.*"...
- Installing hashicorp/aws v2.70.0...
- Installed hashicorp/aws v2.70.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

The string rendering of the constraint in the output is a little confused (it's showing the minor part as `*` rather than as `0`) but otherwise it seems to be behaving the way it was intended to behave, which is that `~> 2` is just a synonym for `~> 2.0`.

We changed the library used to parse these constraints in v0.13, so I'm not surprised to see that the behavior changed for the better compared to v0.12 but I was surprised to hear that it reproduced in v0.13.0-rc1 because AFAIK we didn't change the version constraints library between RC1 and final release. So I tried v0.13.0-rc1 and indeed I can't reproduce it there either: the output is identical to the v0.13.0 final output I showed above.

With all of that said, I suspect this bug was fixed as a side-effect of other changes to the version handling in v0.13. @kevinscholz , could you also give this a try with the v0.13.0 release and let me know if you see the same result I did? As long as you only run `terraform init` with v0.13.0 you will be able to keep using Terraform v0.12 after this as long as you remove the `.terraform` directory and re-run `terraform init` with v0.12, to revert the local plugin cache directory back to the old v0.12-style directory structure.

**Comment by danieldreier** [comment] 2020-08-19 23:40
Interesting - I also just ran this on 0.13.0 GA, and again on 0.13.0 RC1 as a sanity check, and I am also now unable to reproduce it. I now get aws v2.7.0 just like Martin did.

**Comment by danieldreier** [comment] 2020-09-15 16:55
I'm removing confirmed from this, because Martin wasn't able to reproduce it

**Comment by apparentlymart** [comment] 2021-01-14 02:35
Hi again,

Since this no longer seems reproducible in 0.13, and we have a plausible theory for why that would be (we changed the version constraint parser implementation in that release), I'm going to close this now.

If someone finds this issue in future after encountering what seems like a similar bug, please open a new issue for it so we can capture a new set of reproduction steps and see how they differ from what we tried here.

Thanks for reporting this!

**Closed by apparentlymart** 2021-01-14 02:35 UTC
Labels: bug, explained, v0.12, v0.13
