### ISSUE TITLE
Unsupported argument on Destroy. Validate, Plan, Apply if OK!

### ISSUE THREAD

**Issue by MrTolerant** [hashicorp/terraform#24379] opened 2020-03-16 11:32 UTC
Hi! When i'm trying to destroy test infra i'll get Errors:
```
$ terraform destroy -var="user=${VCD_USER}" -var="password=${VCD_PASS}" -auto-approve -input=false
 Error: Unsupported argument
   on modules.tf line 3, in module "test1_make_vms":
    3:     vcd_url              = var.vcd_url
 An argument named "vcd_url" is not expected here.
 Error: Unsupported argument
   on modules.tf line 4, in module "test1_make_vms":
    4:     user                 = var.user
 An argument named "user" is not expected here.
 Error: Unsupported argument
   on modules.tf line 5, in module "test1_make_vms":
    5:     password             = var.password
 An argument named "password" is not expected here.
 Error: Unsupported argument
   on modules.tf line 6, in module "test1_make_vms":
    6:     org                  = var.org
 An argument named "org" is not expected here.
 Error: Unsupported argument
   on modules.tf line 7, in module "test1_make_vms":
    7:     vdc                  = var.vdc
 An argument named "vdc" is not expected here.
 Error: Unsupported argument
   on modules.tf line 8, in module "test1_make_vms":
    8:     catalog_name         = var.catalog_name
 An argument named "catalog_name" is not expected here.
 Error: Unsupported argument
   on modules.tf line 9, in module "test1_make_vms":
    9:     template_name        = var.template_name
 An argument named "template_name" is not expected here.
 Error: Unsupported argument
   on modules.tf line 10, in module "test1_make_vms":
   10:     vapp_names           = var.test1_vapp_names
 An argument named "vapp_names" is not expected here.
 Error: Unsupported argument
   on modules.tf line 11, in module "test1_make_vms":
   11:     vm_map               = var.test1_vapp_vms
 An argument named "vm_map" is not expected here.
```
Gitlab_CI :
```
image:
  name: hashicorp/terraform
  entrypoint: [""]

stages:
  - validate
  - plan
  - apply
  - destroy

before_script:
  - terraform -v
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate
  tags:
    - terraform

plan:
  stage: plan
  artifacts:
    untracked: true
    expire_in: 1 week
  script:
    terraform plan -var="user=${VCD_USER}" -var="password=${VCD_PASS}" -out=planfile -input=false
  tags:
    - terraform
  when: manual

apply:
  stage: apply
  dependencies: 
    - plan
  script:
    terraform apply -parallelism=4 planfile
  tags:
    - terraform
  when: manual

destroy:
  stage: destroy
  script:
    terraform destroy -var="user=${VCD_USER}" -var="password=${VCD_PASS}" -auto-approve -input=false
  tags:
    - terraform
  when: manual 
```

**Comment by MrTolerant** [comment] 2020-03-16 11:35
modules.tf
```
module "test1_make_vms" {
    source               = "git::https://gitlab.company.ru/pvllebedev/terraform-vcd-infra.git"
    vcd_url              = var.vcd_url
    user                 = var.user
    password             = var.password
    org                  = var.org
    vdc                  = var.vdc
    catalog_name         = var.catalog_name
    template_name        = var.template_name
    vapp_names           = var.test1_vapp_names
    vm_map               = var.test1_vapp_vms
}

module "test2_make_vms" {
    source               = "git::https://gitlab.company.ru/pvllebedev/terraform-vcd-infra.git"
    vcd_url              = var.vcd_url
    user                 = var.user
    password             = var.password
    org                  = var.org
    vdc                  = var.vdc
    catalog_name         = var.catalog_name
    template_name        = var.template_name
    vapp_names           = var.test2_vapp_names
    vm_map               = var.test2_vapp_vms
}
```
default_vars.tf
```
variable "vcd_url" {}
variable "org" {}
variable "vdc" {}
variable "user" {}
variable "password" {}
variable "power_on" {}
variable "template_name" {}
variable "catalog_name" {}

variable "test1_vapp_names" {default = []}
variable "test1_vapp_vms" {}

variable "test2_vapp_names" {default = []}
variable "test2_vapp_vms" {}
```
var_test1.auto.tfvars

```
test1_vapp_names    = [
                  "test1_nlp-engine",
                  "test1_nginx",
]

test1_vapp_vms = {
                  "test1_nginx" = {
                      vapp_name          = "test1_nginx"
                      count              = 8
                      catalog_name       =   "Terraform"
                      template_name      =   "Terraform"
                      cpus               = 1
                      cpu_cores          = 1
                      memory             = 512
                      network_name       = "devops_internal"
                  }
                  "test1_nlp-engine" = {
                      vapp_name          = "test1_nlp-engine"
                      count              = 8
                      cpus               = 1
                      cpu_cores          = 1
                      memory             = 512
                      ip_subnet          = "10.0.0.96/29"
                      network_name       = "devops_internal"
                  }
}
```

**Comment by MrTolerant** [comment] 2020-03-16 11:37
provider.tf
```
terraform {
  required_version = ">= 0.12.23"

   backend "s3" {
     bucket   = "terraform"
     skip_credentials_validation = true
     key      = "terraform.tfstate"
     endpoint = "http://ceph.company.ru"
     region = "us-east-1"
   }
}

provider "vcd" {
  user                 = var.user
  password             = var.password
  org                  = var.org
  vdc                  = var.vdc
  url                  = var.vcd_url
  max_retry_timeout    = 30
  allow_unverified_ssl = true
  logging              = true
}
```
var_main.auto.tfvars
```
vcd_url       = "https://vcd.company.ru/api"
org           =   "company_2"
vdc           =   "company_2_VDC01"
catalog_name  =   "Templatecompany"
template_name =   "templatecompany"
power_on      =   true
```

**Comment by MrTolerant** [comment] 2020-03-16 11:41
main module for VCD vcloud.tf:
```
terraform
resource "vcd_vapp" "vapp" {
  for_each         = toset(var.vapp_names)
  name             = each.value
  power_on         = true
  
  # lifecycle {
  #   prevent_destroy = true
  # }
}

locals {
  vm_list_flat = flatten([
    for vm_name, vm_params in var.vm_map : [
      for index in range(lookup(vm_params, "count", 1)) : {
        index              = index
        vapp_name          = vm_params.vapp_name
        vm_name            = vm_name
        catalog_name       = lookup(vm_params, "catalog_name", var.catalog_name)
        template_name      = lookup(vm_params, "template_name", var.template_name)
        memory             = vm_params.memory
        cpus               = vm_params.cpus
        cpu_cores          = vm_params.cpu_cores
        power_on           = lookup(vm_params, "power_on", var.power_on)
        network_name       = vm_params.network_name
        ip                 = lookup(vm_params, "ip_subnet", null) != null ? cidrhost(lookup(vm_params, "ip_subnet", null), index) : null
      }
    ]
  ])
}

resource "vcd_vapp_vm" "vapp_vm" {
  for_each = {
    for vm in local.vm_list_flat : format("%s-%02d", vm.vm_name, vm.index + 1) => vm
  }

  vapp_name        = each.value.vapp_name
  name             = each.key
  catalog_name     = each.value.catalog_name
  template_name    = each.value.template_name
  memory           = each.value.memory
  cpus             = each.value.cpus
  cpu_cores        = each.value.cpu_cores
  power_on         = tobool(each.value.power_on)
  accept_all_eulas = true

  customization {
    # admin_password         = ""
    enabled                = true
    force                  = true
    # auto_generate_password = false
    initscript             = templatefile("init.sh", { ip = each.value.ip != null ? each.value.ip : "10.0.0.200" })
  }

  network {
    type               = "org"
    name               = each.value.network_name
    ip                 = each.value.ip
    ip_allocation_mode = each.value.ip != null ? "MANUAL" : "POOL"
    is_primary         = true
  }

  depends_on = [vcd_vapp.vapp]

  # lifecycle {
  #   prevent_destroy = true
  # }
}
```

**Comment by jbardin** [comment] 2020-03-17 16:18
Hi @MrTolerant 

The module configuration you've shown doesn't have any variable declarations. I'm not sure how you would get the the destroy step without those, as that would make the configuration invalid, but this is the error that would be shown as a result.

Can you verify that the module and config shown can be applied in isolation outside of the CICD pipeline? If you could edit the previous comments to include all the files and show the structure of the configuration, so we know which files are in which directory.

Thanks

**Comment by MrTolerant** [comment] 2020-03-18 07:11
VCD PROJECT files
______
```
.gitlab-ci.yml 
default_vars.tf 
provider.tf
init.sh
modules.tf
provider.tf
var_main.auto.tfvars
var_test2.auto.tfvars
var_test1.auto.tfvars 
var_test2.auto.tfvars
```
____

VCD MODULE (used in modules.tf) files:
___
```
variables.tf
vcloud.tf
```
___

**Comment by MrTolerant** [comment] 2020-03-18 07:42
I solve this problem running 

```terraform destroy -var="user=${VCD_USER}" -var="password=${VCD_PASS}" -auto-approve -input=false -var-file="var_test1.auto.tfvars" -var-file="var_test2.auto.tfvars" -var-file="var_main.auto.tfvars"```

**Comment by danieldreier** [comment] 2020-04-10 01:42
@MrTolerant I've looked at this a few times, and I'm not sure how to dig into it further without a full reproduction case. I don't have access to your `test1_make_vms` module, and so I don't know what input variables it's supposed to accept.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand what is causing this. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug, please help by providing full details about an environment I can set up locally to reproduce this failure more. If you can, I may be able get it on our backlog. The ideal here would be a full github repository that I can clone and run a reproduction case, with everything I need to reproduce it locally. [Another user on the issue you linked made a similar request that has gone unanswered for 22 days](https://github.com/terraform-providers/terraform-provider-vcd/issues/474#issuecomment-601085717).

Based on what I'm seeing so far, I recommend you take this to the community forum for assistance in troubleshooting. You could also take it up with that other user on the linked issue who offered to help. I'm going to close this for now, because I think the community forum is the right approach, and I don't see any evidence of a terraform core bug. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you'd rather work up a reproduction case here.

**Closed by danieldreier** 2020-04-10 01:42 UTC
