### ISSUE TITLE
Diffs didn't match during apply when modifying aws_instance tags

### ISSUE THREAD

**Issue by RoeiA** [hashicorp/terraform#6845] opened 2016-05-24 10:39 UTC
Hello,

First i'd like to thank you all for this wonderful tool.
I'm running terraform 0.6.16 and have a case of _diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue._

i'm trying to modify tags on aws_instances. my terraform config is:

```
variable "subnet_ids" {}
variable "instance_count" {}
variable "instance_type" {}
variable "ami" {}
variable "security_groups" {}
variable "instance_name" {}
variable "is_public_address" {}
variable "userdata_scripts" {}
variable "dns_zone_id" {}
variable "dummy_dep" {}
variable "key_name" {}

resource "aws_instance" "component_instance" {
  ami                         = "${var.ami}"
  count                       = "${var.instance_count}"
  instance_type               = "${var.instance_type}"
  subnet_id                   = "${element(split(",", var.subnet_ids), count.index % 2)}"
  security_groups             = ["${split(",", var.security_groups)}"]
  key_name                    = "${var.key_name}"
  associate_public_ip_address = "${var.is_public_address}"
  user_data                   = "${element(split(",", var.userdata_scripts), count.index)}"

  lifecycle {
    ignore_changes = [ "security_groups" ]
    create_before_destroy = true
  }

  tags {
    Name = "${var.instance_name}${count.index}"
    depends_id = "${var.dummy_dep}"
  }
}

output "ips" {
  value = "${join(",", aws_instance.component_instance.*.private_ip)}"
}
```

when I add a tag, or change the name of an existing tag I get the following:
_* aws_instance.component_instance.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue._

if I run a second apply I get the same thing, where in other cases it somehow helped.

Thanks for any help.

**Comment by catsby** [comment] 2016-06-16 15:47
Hey @RoeiA thanks for reporting this. 
Unfortunately I'm not able to reproduce this. 

I attempted with this config:

```hcl
variable "instance_name" {}

variable "instance_count" {}

resource "aws_instance" "tf_test" {
  count         = "${var.instance_count}"
  ami           = "ami-dfc39aef"
  instance_type = "t2.nano"

  tags {
    Name    = "tf_test_instance"
    Count   = "tag-${count.index}"
    NewName = "${var.instance_name}${count.index}"
  }
}
```

I tried various combinations of create, modify, etc, but wasn't able to trigger a _diffs didn't match_ error (using v0.6.16). Is there any more information you can give me to help reproduce this? Are you doing a plan to file, then executing that plan? Or just directly applying your changes? 

Thanks!

**Comment by catsby** [comment] 2016-07-20 19:35
Hello – I'm going to close this for now, please let us know if you're still hitting this issue in the latest version of Terraform (v0.6.16 at time of writing)

**Closed by catsby** 2016-07-20 19:35 UTC
Labels: bug, provider/aws, waiting-response

**Comment by ryanking** [comment] 2016-07-28 22:52
@catsby have you tried reproducing with the ignore_changes? I've seen similar problems (sorry don't have the crash output anymore) when using ignore_changes.
