### ISSUE TITLE
Resources being resolved to state instead of to-be-applied version

### ISSUE THREAD

**Issue by theCalcaholic** [hashicorp/terraform#22685] opened 2019-09-04 16:28 UTC
### Terraform Version

```
Terraform v0.12.7
+ provider.local v1.3.0
```

### Terraform Configuration Files

```hcl
locals {
  names = ["file1", "file2", "file3"]
}

resource "local_file" "my-test-files" {
  count = length(local.names)
  filename = local.names[count.index]
}

output "test-output" {
  value = index( local_file.my-test-files.*.filename, local.names[0] )
}
```

### Debug Output
This is the result of `TF_LOG=trace terraform apply` (see **Steps to Reproduce** -> 4.): 
https://gist.github.com/theCalcaholic/87873b271b04196747be784f1d9681b9

### Expected Behavior
Terraform should always resolve resource properties to their value after changes have been applied.

### Actual Behavior
If a resource does not exist, terraform resolves resource properties as expected. However, if it exists in the state, but will be changed in the ongoing apply process, terraform resolves to the (outdated) values in the state.

### Steps to Reproduce
On the hcl code above:
1. `terraform init`
2. `terraform apply`
3. Change the value of local.names[0], e.g. to "my-file-1"
4. `terraform apply` => results in an error, because, during the `index` call, terraform is trying to find "my-file-1" in local_file.my-test-files.*.filename as saved to the state (and thus not taking into account the changes to be applied)

**Comment by jbardin** [comment] 2020-10-23 23:57
This type off error during refresh is no longer possible, primarily because there is no longer a separate refresh phase, which is where these incongruities can arise.

Confirmed fixed in the 0.14 branch.

Thanks!

**Closed by jbardin** 2020-10-23 23:57 UTC
Labels: bug, core, pending project, v0.12
