### ISSUE TITLE
Support for objects of objects variables

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [hashicorp/terraform#23025] opened 2019-10-08 10:46 UTC
Terraform 0.12 introduced richer value types which enhance data type validation and, specifically, the type *object*.  But it seems you can't declare objects within objects.

In example, I have the following variable which I want to validate:
```HCL
project_config = {
  name = "example_project"
  environments = {
    production = {
      aws_role = "arn:aws:iam::[redacted role]"
      cidr_block = "10.2.0.0/16"
      public_subnet_a_cidr_block = "10.2.11.0/24"
      dns_config = {
        domain = "pro"
        parent = "my.example.com"
      }
    }
    development = {
      aws_role = "arn:aws:iam::[redacted role]"
      cidr_block = "10.1.0.0/16"
      public_subnet_a_cidr_block = "10.1.11.0/24"
      dns_config = {
        domain = "dev"
        parent = "my.example.com"
      }
    }
  }
}
```
Thus, I tried the following (notice the object-within-object definition):
```HCL
variable "project_config" {
  description = "Map presenting a project's data"

  type = object({
    name = string,
    environments = object({
      aws_role = string,
      cidr_block = string,
      public_subnet_a_cidr_block = string,
      dns_config = object({
        domain = string,
        parent = string,
      })
    })
  })
}
```

But then, it fails, i.e.:
```
$ terraform apply -var-file="production.tfvars"

Error: Invalid value for input variable

  on production.tfvars line 1:
   1: project_config = {
   2:   name = "example_project"
   3:   environments = {
   4:     production = {
   5:       aws_role = "arn:aws:iam::[redacted role]"
   6:       cidr_block = "10.2.0.0/16"
   7:       public_subnet_a_cidr_block = "10.2.11.0/24"
   8:       dns_config = {
   9:         domain = "pro"
  10:         parent = "my.example.com"
  11:       }
  12:     }
  13:     development = {
  14:       aws_role = "arn:aws:iam::[redacted role]"
  15:       cidr_block = "10.1.0.0/16"
  16:       public_subnet_a_cidr_block = "10.1.11.0/24"
  17:       dns_config = {
  18:         domain = "dev"
  19:         parent = "my.example.com"
  20:       }
  21:     }
  22:   }
  23: }

The given value is not valid for variable "project_config": attribute "name":
string required.

```

Carefully reading the relevant documentation I noticed that within *structural types* the ability to allow other *structural types* is not granted (but it's not negated, either) and it seems that, in fact, only *primitive* and *collection* types are allowed, but not other *structural* types (object or tuple).

### Current Terraform Version

```
Terraform v0.12.9
```

### Use-cases

The idea is, of course, for complex data types to be properly validated and, at the same time, for the variable definition to act as self-documentation of the expected structure.

### Attempted Solutions
First I thought I was failing to properly define my variables (as I'm quite novice on Terraform) but then, after I tested quite some combinations and observing what worked and what didn't, I realized where my problem was.

### Proposal

I have no proposal to do at this time except for a meagre *"I think my example above should work"*.

In the meantime, maybe [the related doc](https://www.terraform.io/docs/configuration/types.html#structural-types) could be updated to explicitly state that *structural types* are not supported within *structural types* (I know it would have saved me some few hours).

### References

On value types: https://www.hashicorp.com/blog/terraform-0-12-rich-value-types

**Comment by teamterraform** [comment] 2019-10-08 16:31
Hi @next-jesusmanuelnavarro!

Nested structural types _are_ supported, and indeed at first glance it seems like what you tried here should've worked.

The error message doesn't seem to be about your nested object type at all:

```
The given value is not valid for variable "project_config": attribute "name":
string required.
```

This is referring to the top-level `name` attribute, which is declared as requiring a string and seems to be assigned a string `"example_project"` in the expression that Terraform is complaining about here. It's not clear to us right now why Terraform rejected that expression, since indeed it seems correct per the type constraint.

We've relabeled this as being a bug report because Terraform doesn't seem to be behaving as intended or as documented here. In order to continue investigating, it'd be very useful if you could refer to [our bug report issue template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md) and share the additional information that the bug report template requests. In particular, we'd like to see the trace log as described under "Debug Output" and, if possible, a full configuration that we could run on our own machines in order to reproduce the problem for further debugging.

Thanks for reporting this, and sorry that Terraform didn't behave as expected here.

**Comment by next-jesusmanuelnavarro** [comment] 2019-10-08 17:17
> Hi @next-jesusmanuelnavarro!
> We've relabeled this as being a bug report because Terraform doesn't seem to be behaving as intended or as documented here. In order to continue investigating, it'd be very useful if you could refer to [our bug report issue template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md) and share the additional information that the bug report template requests. In particular, we'd like to see the trace log as described under "Debug Output" and, if possible, a full configuration that we could run on our own machines in order to reproduce the problem for further debugging.

I'll try to offer a debug output tomorrow, but that problem appears even in the simplest case.

Just the tfvars above, the variable definition and the simplest main.tf triggers this behaviour, i.e.:

```HCL
output "hello_world" {
  value = "Hello, World!"
}
```

**Comment by jiajie-chen-havas** [comment] 2019-10-25 19:15
@next-jesusmanuelnavarro It seems like there's an error in your variable definition. Your tfvars has `environments = map(object({ ... }))` but your variable definition defines the type as `environments = object({ ... })`.

This seems like the correct definition:
```hcl
variable "project_config" {
  description = "Map presenting a project's data"

  type = object({
    name = string,
    environments = map(object({
      aws_role = string,
      cidr_block = string,
      public_subnet_a_cidr_block = string,
      dns_config = object({
        domain = string,
        parent = string,
      })
    }))
  })
}
```

When I run `terraform plan` with the above schema, I get:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

But if I run the original schema, I get:
```
Error: Invalid value for input variable

  on terraform.tfvars line 1:
   1: project_config = {
   2:   name = "example_project"
   3:   environments = {
   4:     production = {
   5:       aws_role = "arn:aws:iam::[redacted role]"
   6:       cidr_block = "10.2.0.0/16"
   7:       public_subnet_a_cidr_block = "10.2.11.0/24"
   8:       dns_config = {
   9:         domain = "pro"
  10:         parent = "my.example.com"
  11:       }
  12:     }
  13:     development = {
  14:       aws_role = "arn:aws:iam::[redacted role]"
  15:       cidr_block = "10.1.0.0/16"
  16:       public_subnet_a_cidr_block = "10.1.11.0/24"
  17:       dns_config = {
  18:         domain = "dev"
  19:         parent = "my.example.com"
  20:       }
  21:     }
  22:   }
  23: }

The given value is not valid for variable "project_config": attribute "name":
string required.
```

This seems related to #22324, where Terraform will correctly reject the invalid variable, but provide an incorrect reason for why it's invalid.

**Comment by MarkPerry24** [comment] 2020-04-29 10:54
> Hi @next-jesusmanuelnavarro!
> 
> Nested structural types _are_ supported, and indeed at first glance it seems like what you tried here should've worked.
> 
> The error message doesn't seem to be about your nested object type at all:
> 
> ```
> The given value is not valid for variable "project_config": attribute "name":
> string required.
> ```
> 
> This is referring to the top-level `name` attribute, which is declared as requiring a string and seems to be assigned a string `"example_project"` in the expression that Terraform is complaining about here. It's not clear to us right now why Terraform rejected that expression, since indeed it seems correct per the type constraint.
> 
> We've relabeled this as being a bug report because Terraform doesn't seem to be behaving as intended or as documented here. In order to continue investigating, it'd be very useful if you could refer to [our bug report issue template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md) and share the additional information that the bug report template requests. In particular, we'd like to see the trace log as described under "Debug Output" and, if possible, a full configuration that we could run on our own machines in order to reproduce the problem for further debugging.
> 
> Thanks for reporting this, and sorry that Terraform didn't behave as expected here.

I see this issue if I define my complex type like this:
type        = map(object(
        {
            product = string
            project = string
            location = string
            tags = map(string)
            optional_parameters = map(string)
            resources = list(
                object(
                    {
                        type = string
                        resource_number = string
                        parameters = map(string)
                        child_resources = list(
                            object(
                                {
                                    type = string
                                    resource_number = string
                                }
                            )
                        )
                    }
                )
            )
        }
    ))

This will FAIL with 'element "xyzsvc": attribute "product": string required'

This WORKS (kinda) by just removing "resource_number = string" so presumably my child_resource list resource is able to coerce the object into list(string) but cannot use an object due to some nesting issue.  So not ideal so in order to get over this problem I now define child_resources as:

child_resources = string

and abuse jsonencode to get my list of objects which I got inspiration from here:
https://github.com/hashicorp/terraform/issues/21838

**Comment by jbardin** [comment] 2021-03-31 13:58
Hello,

The original issue here appears to be working as intended once the original type definitions were cleared up, so I'm going to close this out. [Optional attributes](https://www.terraform.io/docs/language/functions/defaults.html) have since been added to the language, which should help with the remaining use cases around missing required attributes in objects.

If anyone has remaining questions, we use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2021-03-31 13:58 UTC
Labels: bug, config, v0.12
