### ISSUE TITLE
Empty gap in terraform plan for hidden blocks

### ISSUE THREAD

**Issue by Porkepix** [hashicorp/terraform#30325] opened 2022-01-10 15:18 UTC
### Terraform Version
1.1.2

The usual template isn't relevant here, considering it could be considered as normal, which is the reason it's not followed. As you can see on the below screenshot, there are situations where there are hidden blocks causing a big empty gap in the terraform plan. Is this considered as a normal output, or should it just be a single line like it is for the hidden elements as visible on the same screenshot?

This gap is surprising at first so I was wondering if this was considered as normal or not.

Here's the screenshot in question: 
![Screenshot 2022-01-10 at 16 08 14](https://user-images.githubusercontent.com/709500/148790194-d9948f89-c534-449e-a1dd-1c149978d0be.png)

**Comment by alisdair** [comment] 2022-01-11 15:48
Hi @Porkepix, thanks for the report. This is a bug in the plan renderer, and a duplicate of #28217. We haven't been able to find a clean fix for this cosmetic issue just yet; see #29037 for the most recent attempt.

Closing this as a duplicate.

**Closed** 2022-01-11 15:48 UTC
Labels: bug, new, plan-renderer
