### ISSUE TITLE
terraform keeps crashing even after getting updated version

### ISSUE THREAD

**Issue by rumetix** [hashicorp/terraform#29283] opened 2021-08-01 21:14 UTC
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by rumetix** [comment] 2021-08-01 21:28
[crash.533240070.log](https://github.com/hashicorp/terraform/files/6913451/crash.533240070.log)

**Comment by jbardin** [comment] 2021-08-02 12:48
Duplicate of #29041

**Closed by jbardin** 2021-08-02 12:48 UTC
Labels: bug, new

**Comment by jbardin** [comment] 2021-08-02 13:19
Hello @rumetix,

I see you also submitted #29276, but neither of these have any information on recreating the issue, so there's not much we can do to help. The discussion in the original issue may offer some guidance, and the fix has since been backported to the v1.0 branch. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
