### ISSUE TITLE
Crash running `terraform show -json plan.tfplan `

### ISSUE THREAD

**Issue by mikesir87** [hashicorp/terraform#29113] opened 2021-07-07 16:54 UTC
### Terraform Version

```
Terraform v1.0.1
on darwin_amd64
```

### Terraform Configuration Files

Not really sure what part is relevant or not and have a lot of Terraform being used. I've tried to make a smaller scoped project to reproduce the bug, but have had trouble doing so.

### Debug Output
https://gist.github.com/mikesir87/42b665d10ea14605ad7f6116293bb5b1

### Crash Output
Looks mostly the same as the debug output, but here you go...

https://gist.github.com/mikesir87/baead99ece361545479f829593af8e39

### Expected Behavior
The command to work successfully

### Actual Behavior
We get an error indicating `panic: value is marked, so must be unmarked first`, which is hard to diagnose.

### Steps to Reproduce

Hard to know, as it seems to be only one of our pipelines.

### Additional Context

- We do NOT get the error when using 0.15.5 but do on either of the current 1.0.x releases.
- Running `terraform show plan plan.tfplan` without the JSON flag exits successfully

### References

Not sure yet. I took a look at #28903, but that doesn't appear to be exactly related. And it still occurs in the 1.0.1 release which includes the MR fixing it.

**Comment by jbardin** [comment] 2021-07-07 17:24
Duplicate of #29042

**Closed by jbardin** 2021-07-07 17:24 UTC
Labels: bug, new

**Comment by mikesir87** [comment] 2021-07-07 17:59
Ah and thank you! I did some searching, but apparently didn't find that one. Thanks @jbardin!
