### ISSUE TITLE
Terraform : Failed to save state: storage: service returned error: StatusCode=404

### ISSUE THREAD

**Issue by Roshanpatel90** [hashicorp/terraform#21572] opened 2019-06-03 16:52 UTC
While execution of the terraform script, we are getting the error of below.

Failed to save state: storage: service returned error: StatusCode=404, ErrorCode=ResourceNotFound, ErrorMessage=The specified resource does not exist.
RequestId:f6157c9b-701e-009b-6629-1a251f000000
Time:2019-06-03T16:30:49.6122150Z, RequestInitiated=Mon, 03 Jun 2019 16:30:49 GMT, RequestId=f6157c9b-701e-009b-6629-1a251f000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=

The script is referencing to the correct storage account(blob), but still appears the execution is failing. Please advise.

**Comment by apparentlymart** [comment] 2019-06-03 22:50
Hi @Roshanpatel90,

We use [an issue template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md) in order to ensure that bug reports have all of the information required for us to start debugging a problem. Could you please copy the issue template into your original comment and complete it, so we can see more about what you are trying?

In particular, you didn't mention here which backend you are using. When you complete the issue template, please be sure to include the `backend` block from your configuration so we can see ho you have the backend configured.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by apparentlymart** [comment] 2019-07-11 23:12
Hi again @Roshanpatel90,

Since we didn't hear more from you, I'm going to close this out. If you still have this problem, please open a new issue and be sure to answer all of the questions in the issue template so we can have the best possible chance of being able to understand what you were trying to do and how we might reproduce the problem in order to debug and fix it.

**Closed by apparentlymart** 2019-07-11 23:12 UTC
