### ISSUE TITLE
Conditional expression not working as expected when using OR logic

### ISSUE THREAD

**Issue by daniel-butler-irl** [hashicorp/terraform#32641] opened 2023-02-08 10:09 UTC
### Terraform Version

```shell
Terraform v1.3.7                                                                                                                
on darwin_amd64
```

### Terraform Configuration Files

```terraform
# Example distilled to its simplest form
variable "test" {
  type = list(string)
  default = null
}

locals {
  myvar = var.test == null || length(var.test) == 0 ? ["no value"] : var.test
}
```

### Debug Output

```bash
❯ terraform plan
╷
│ Error: Invalid function argument
│ 
│   on main.tf line 8, in locals:
│    8:   myvar = var.test == null || length(var.test) == 0 ? ["no value"] : var.test
│     ├────────────────
│     │ while calling length(value)
│     │ var.test is null
│ 
│ Invalid value for "value" parameter: argument must not be null.
```

### Expected Behavior

After evaluating `var.test == null` is true the or is satisfied so `myvar` should be set to `["no value"]`

### Actual Behavior

Tries to evaluate length on a null object unnecessarily.

### Steps to Reproduce

1. `terraform plan`

### Additional Context

After evaluating the first condition the `OR` is satisfied, no need to evaluate the other conditions. There are workarounds but this format should work.

**Comment by jbardin** [comment] 2023-02-08 13:54
Duplicate of #24128

**Closed by jbardin** 2023-02-08 13:54 UTC
Labels: bug, new
