### ISSUE TITLE
Error handling on non-existent file (Template)

### ISSUE THREAD

**Issue by dene14** [hashicorp/terraform#4737] opened 2016-01-19 16:26 UTC
Error:
```
1 error(s) occurred:
* template_file.task_test: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

produced by definition like this:
```
resource "template_file" "task_test" {
  template = "files/test.json"

  vars {
    template_test_value   = "TEST_VALUE"
  }
}
```

when `files/test.json` doesn't exist.

I think it worth to get any better warning here to save some time for others. Thanks!

**Comment by jen20** [comment] 2016-01-19 16:50
Hi @dene14! Thanks for opening this issue. I tried to reproduce this - could you confirm which version of Terraform you are using? Newer versions of Terraform (since 0.6.7 I believe) use `template` to contain the actual text of the template rather than the contents, so this doesn't apply there:

```
$ cat main.tf
resource "template_file" "task_test" {
  template = "files/test.json"

  vars {
    template_test_value   = "TEST_VALUE"
  }
}
```

```
$ terraform apply
template_file.task_test: Creating...
  rendered:                 "" => "<computed>"
  template:                 "" => "files/test.json"
  vars.#:                   "" => "1"
  vars.template_test_value: "" => "TEST_VALUE"
template_file.task_test: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

```
$ terraform apply
template_file.task_test: Refreshing state... (ID: 611dd6f81a517a407e39a69bfbac8e06c8d707a29d505624c241851313510512)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

If I modify the configuration to the newer Terraform syntax:

```
$ cat main.tf
resource "template_file" "task_test" {
  template = "${file("files/test.json")}"

  vars {
    template_test_value   = "TEST_VALUE"
  }
}
```

And upon `terraform plan` this fails.

```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * file: open files/test.json: no such file or directory in:

${file("files/test.json")}
```

I suspect this has already been fixed by virtue of dropping the template file loading the file itself - so I'll close this issue for now. If you have any further background that might help us reproduce this please feel free to reopen it !

**Closed by jen20** 2016-01-19 16:50 UTC

**Comment by dene14** [comment] 2016-01-19 19:33
Well, probably I haven't provided enough details...

```
terraform --version
Terraform v0.6.9
```

Template object is in use by aws_ecs_task_definition like so:
```
resource "aws_ecs_task_definition" "task_test" {
  family                = "test"
  container_definitions = "${template_file.task_test.rendered}"
}
```

From what I see in my AWS account it has been rendered properly and works well. Even if my code is incorrect there might be another bug coz our expectations seems a bit different :)
