### ISSUE TITLE
Allow provider to be dynamic (for_each or count) not working for provider aws = 4.30.0

### ISSUE THREAD

**Issue by VikramPunnam** [hashicorp/terraform#31772] opened 2022-09-12 12:28 UTC
### Terraform Version

```shell
4.30.0
```

### Use Cases

Allow provider to be dynamic (for_each or count) not working

### Attempted Solutions

Update the provider block with count/for_each

**Comment by jbardin** [comment] 2022-09-12 12:59
Hi @VikramPunnam,

There are no versions of Terraform which can expand provider blocks into multiple instances. If you want to track this feature in the future, the relevant issue is #16967.

Thanks!

**Comment by jbardin** [comment] 2022-09-12 12:59
Duplicate of #16967

**Closed by jbardin** 2022-09-12 12:59 UTC
Labels: enhancement, new
