### ISSUE TITLE
aws_iam_instance_profile accepts roles[] but should only accept role

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#3551] opened 2015-10-19 17:58 UTC
aws_iam_instance_profiles accepts a roles[] array, indicating attaching 2 roles, but:

http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html

indicates that you can only have 1 role attached to an instance_profile.

**Comment by johnrengelman** [comment] 2015-12-01 17:43
That's only a default maximum. I believe AWS can increase that limit at your request.

**Comment by simonvanderveldt** [comment] 2016-03-02 10:03
This is a duplicate of #3851

**Comment by stack72** [comment] 2016-07-27 00:43
Closing as a duplicate of #3851 - there is a lot of discussion in that issue that can be kept track of

**Closed by stack72** 2016-07-27 00:43 UTC
Labels: bug, provider/aws
