### ISSUE TITLE
Terraform Module Registry is down

### ISSUE THREAD

**Issue by likwid** [hashicorp/terraform#25236] opened 2020-06-12 19:04 UTC
Sorry, this isn't exactly a Terraform bug report, but the Terraform Module Registry is down in Dallas/Fort Worth (at least). All monitoring https://status.hashicorp.com, https://status.fastly.com/ indicates everything is working, but that is objectively not correct.

My concern is that yall don't even know about it if is a localized problem.  I also mentioned this in the Gitter channel for Terraform.

I am just surfacing this in case no one realizes its an issue.

**Comment by danieldreier** [comment] 2020-06-12 19:05
I'm on it - I will escalate this internally

**Comment by danieldreier** [comment] 2020-06-12 19:10
@likwid I just ran the following code and was able to download a module:
```hcl
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.39.0"
  # insert the 12 required variables here
}
```

When I ran `terraform init`, I got:
```
Initializing modules...
Downloading terraform-aws-modules/vpc/aws 2.39.0 for vpc...
- vpc in .terraform/modules/vpc/terraform-aws-vpc-2.39.0

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 2.53"...
- Installing hashicorp/aws v2.66.0...
- Installed hashicorp/aws v2.66.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Can you tell me what evidence you're seeing of it being down? I believe you that you're having a problem, but it's hard to even escalate when I don't see a failure myself and our monitoring isn't reporting problems.

**Comment by danieldreier** [comment] 2020-06-12 19:11
Actually - I take that back. I'm seeing internal discussion of an outage. I don't know yet why this is working for me and not others.

**Comment by danieldreier** [comment] 2020-06-12 19:12
https://status.heroku.com/incidents/2045 is where updates about this incident are being posted

**Comment by danieldreier** [comment] 2020-06-12 19:14
I believe that the registry is up again and that's why I wasn't able to reproduce this. Please let me know if you're still having problems and I can escalate further internally.

There is a public statement about the outage at https://hashicorp.statuspage.io/incidents/hwzngv8y9kwd 

I'm going to close this issue because I believe this issue is resolved. Thank you for bringing this to our attention!

**Closed by danieldreier** 2020-06-12 19:14 UTC
