### ISSUE TITLE
v0.12: Tests are seeing unexpected plan diffs caused by data sources

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20986] opened 2019-04-11 00:54 UTC
### Terraform Version

```
v0.12.0-alpha4.0.20190410151648-50660032848d
```

### Terraform Configuration Files

```hcl
data "oci_audit_events" "audit_events" {
  compartment_id = "${var.compartment_ocid}"
  start_time = "${timeadd(timestamp(), "-1m")}"

  end_time = "${timestamp()}"
}
```

### Expected Behavior

In v0.11, we have tests that apply a single datasource.

The test passes.

### Actual Behavior

In v0.12, the plan after apply detects that the data source has been updated even though it hasn't changed. The left-hand side values are all seemingly empty for the data source.

```
--- FAIL: TestAuditAuditEventResource_basic (0.64s)
    testing.go:568: Step 0 error: After applying this step and refreshing, the plan was not empty:
        
        DIFF:
        
        UPDATE: data.oci_audit_events.test_audit_events
          audit_events:   "" => "<computed>"
          compartment_id: "" => "<REDACTED>"
          end_time:       "" => "<computed>"
          filter.#:       "" => "0"
          id:             "" => "<computed>"
          limit:          "" => "1"
          start_time:     "" => "<computed>"
        
        
        
        STATE:
        
        <no state>
```

**Comment by alexng-canuck** [comment] 2019-04-11 19:02
This behavior seems to be related to having interpolation syntax in the input fields for `start_time` and `end_time` of the resource.

If I hardcode those values, the plan diff seems to go away. Is this new behavior in v0.12?

**Comment by alexng-canuck** [comment] 2019-04-12 00:23
This sounds like desirable behavior that data source should result in plan diff if the input values are computed and can change. But would like confirmation that this is intended behavior in v0.12.

That said, I still think the diff should more clearly spell out what caused the diff to occur. The current diff output makes it hard to discern which input field necessitated a rerun of the datasource.

**Comment by apparentlymart** [comment] 2019-04-12 00:31
Hi @alexng-canuck,

I think what's going on here is that the use of the `timestamp` function is blocking the resolution of this data source during the refresh phase, because in Terraform v0.12 we defer evaluating timestamps until apply time to ensure that the time recorded is the time applied, not the time planned. In Terraform v0.11 this would've populated the time when the data source was _refreshed_, and thus allowed the plan to converge.

Thus this _is_ intended behavior, though the situation you've found here is an interesting one. If this is for acceptance testing purposes, I'd suggest instead having the test code generate a timestamp and insert it into the generated test code, since that will ensure it remains constant throughout the test, and avoid the problem you've encountered here.

I'll also think about what, if anything, we'll want to say about this in the upgrade guide. So far this is the only case we've seen of this particular interaction, but we'll spend some time thinking about other possible consequences of this behavior when combined with data resources.

**Comment by alexng-canuck** [comment] 2019-04-12 00:37
Thanks @apparentlymart . The way I've worked around this for now is to use `ExpectNonEmptyPlan` in tests that exhibit this use case.

**Comment by apparentlymart** [comment] 2019-04-17 15:19
Thanks for confirming, @alexng-canuck!

On some reflection, we're going to elect not to mention this explicitly in the upgrade guide for now, since it seems like something that is relatively rare to hit and is only really a significant problem in acceptance tests. We may revisit that decision if we see other questions about it during the remaining prerelease cycles, but we're trying to be selective about what details are in the upgrade guide so that it stays at a digestible length.

With that said, I'm going to close this out for now, and we'll revisit in a separate issue if we decide to add an upgrade guide note after all.

**Closed by apparentlymart** 2019-04-17 15:19 UTC
Labels: provider-sdk
