### ISSUE TITLE
google_sql_database.users: operationInProgress error on `terraform apply`

### ISSUE THREAD

**Issue by maryamklabib** [hashicorp/terraform#9018] opened 2016-09-23 18:36 UTC
Hi there,

We're seeing `google_sql_database.users: Error, failed to insert database [name] into instance [name]: googleapi: Error 403: Operation failed because another operation was already in progress., operationInProgress` very frequently but not always. We see it only on google_sql_database.users, but terraform applying other resources reliably works.
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- google_sql_database.users
### Terraform Configuration Files

``` hcl
resource "google_sql_database_instance" "master" {
  region = "${var.sql_region}"
  settings {
    tier = "${var.google_sql_db_tier}"
   }

  count = "${var.google_sql_instance_count}"
}

resource "google_sql_database" "users" {
  name = "${var.env_name}-db"
  instance = "${google_sql_database_instance.master.name}"

  count = "${var.google_sql_instance_count}"
}

resource "google_sql_user" "users" {
  name = "${var.google_sql_db_username}"
  password = "${var.google_sql_db_password}"
  instance = "${google_sql_database_instance.master.name}"
  host     = "${var.google_sql_db_host}"

  count = "${var.google_sql_instance_count}"
}
```
### Debug Output

https://gist.github.com/maryamklabib/5681f634691f2e09782df962cf016ce8
### Steps to Reproduce
1. `terraform apply`
### Important Factoids

We're creating First Generation GoogleSQL users

**Comment by danawillow** [comment] 2017-01-25 00:34
Hi @maryamklabib, sorry it took so long to get to this!

I took a quick look, and I'm not sure whether there's anything we can do in terraform itself to prevent against this, but adding an explicit depends_on from either the user or the database to the other should prevent the two of them from conflicting.

**Comment by ctavan** [comment] 2017-05-11 07:42
@danawillow I have the same issue. While the `depends_on` workaround works for me I still think terraform could maybe handle this better.

How do you feel about wrapping the insert call in a retry loop as it's already being done for storage bucket creation, see: https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_storage_bucket.go#L129-L143 ?

Fortunately the error message from the Google is pretty expressive. Do you have any idea of how stable these error messages are and whether checking for `operationInProgress` could be a reliable way of determining if the request is retriable?

**Comment by samstarling** [comment] 2017-05-28 19:15
@maryamklabib @ctavan Did you ever find a solution to this? I'm having the exact same problem.

**Comment by danawillow** [comment] 2017-05-31 15:53
@samstarling the linked PR should fix this issue once it's merged and released.

**Comment by moxli** [comment] 2018-05-25 12:51
@danawillow 

I am facing a similar issue with the google_sql_user resource right now.

`terraform -v
Terraform v0.11.7
provider.google v1.13.0`

I am using the following syntax to create nine users:
```hcl
resource "google_sql_user" "users" {
  count      = 9
  instance   = "${var.instance}"
  name       = "${element(var.subenvs, count.index)}-${var.product_short}.${element(var.usernames, count.index)}"
}
```

Subenv and usernames are both a list of strings defined in a separate variables.tf file.

I also create two cloud sql instances:

```hcl
resource "google_sql_database_instance" "mysql" {
  name = "${var.name}"
  region = "${var.region}"
  database_version = "${var.database_version}"
  master_instance_name = "${var.master_instance_name}"

  settings {
    tier = "${var.tier}"
    disk_size = "${var.disk_size}"
    disk_type = "${var.disk_type}"
    disk_autoresize = "${var.disk_autoresize}"

    database_flags = "${var.flags}"

    backup_configuration {
      binary_log_enabled = "${1 - var.failover_node}"
      enabled = "${1 - var.failover_node}"
      start_time = "${var.start_time}"
    }

    ip_configuration {
      ipv4_enabled = true
      authorized_networks = "${var.authorized_networks}"
    }
    maintenance_window {
      day = "${var.maintenance_day}"
      hour = "${var.maintenance_hour}"
    }
  }

  replica_configuration = "${local.failover_value}"
}
````

and three databases:

```hcl
resource "google_sql_database" "databases" {
  count = 3
  name      = "${element(var.subenvs, count.index)}-${var.product}"
  project = "${var.project}"
  instance  = "${var.instance}"
  charset   = "${var.charset}"
  collation = "${var.collation}"
}
```

Usually terraform apply handles everything fine, until the databases and the users are created.
They fail with the following error: 

`google_sql_database.users: Error, failed to insert database [name] into instance [name]: googleapi: Error 403: Operation failed because another operation was already in progress., operationInProgress`

If I run terraform apply again everything works just fine and the users are created successfully.

A similar error happens with terraform destroy:

`module.sql_users.google_sql_user.users[1] (destroy): 1 error(s) occurred:
google_sql_user.users.1: Error, failure waiting for deletion of [user name] in [instance name]:
module.sql_users.google_sql_user.users[0] (destroy): 1 error(s) occurred:
google_sql_user.users.0: Error, failure waiting for deletion of [user name] in [instance name]:`

If I run terraform destroy again everything works just fine and the users are deleted successfully.

**Comment by chroto** [comment] 2018-07-19 00:58
@danawillow I think there may have been a regression in a recent version of terraform or provider-google.  I also started to see the same behavior again where terraform is trying to create many cloudsql instances at the same time.

```
resource "google_sql_database_instance" "replicas" {
  count                = 2
  name                 = "foo-${element(var.replica_zones, count.index)}"
  master_instance_name = "${google_sql_database_instance.primary.name}"

  settings {
    tier = "db-f1-micro"

    location_preference {
      zone = "us-west1-${element(var.replica_zones, count.index)}"
    }

    replica_configuration {
      failover_target = false
    }
  }
}
```


```
$ terraform -v Terraform v0.11.7  provider.google v1.16.1
```

```
2018/07/18 16:21:37 [DEBUG] apply: google_sql_database_instance.replicas: executing Apply
2018-07-18T16:21:37.987-0700 : 2018/07/18 16:21:37 [DEBUG] Google API Request Details:
2018-07-18T16:21:37.987-0700 : ---[ REQUEST ]---------------------------------------
2018-07-18T16:21:37.987-0700 : POST /sql/v1beta4/projects/xxxxxxxxx/instances?alt=json HTTP/1.1
2018-07-18T16:21:37.987-0700 : Host: www.googleapis.com
2018-07-18T16:21:37.987-0700 : User-Agent: google-api-go-client/0.5 Terraform/0.11.7 (+https://www.terraform.io)
2018-07-18T16:21:37.987-0700 : Content-Length: 613
2018-07-18T16:21:37.987-0700 : Content-Type: application/json
2018-07-18T16:21:37.987-0700 : Accept-Encoding: gzip
2018-07-18T16:21:37.987-0700 :
2018-07-18T16:21:37.987-0700 :
2018-07-18T16:21:37.987-0700 : -----------------------------------------------------
2018-07-18T16:21:37.987-0700 : 2018/07/18 16:21:37 [DEBUG] Google API Request Details:
2018-07-18T16:21:37.987-0700 : ---[ REQUEST ]---------------------------------------
2018-07-18T16:21:37.987-0700 : POST /sql/v1beta4/projects/xxxxxxxxxxx/instances?alt=json HTTP/1.1
2018-07-18T16:21:37.987-0700 : Host: www.googleapis.com
2018-07-18T16:21:37.987-0700 : User-Agent: google-api-go-client/0.5 Terraform/0.11.7 (+https://www.terraform.io)
2018-07-18T16:21:37.987-0700 : Content-Length: 635
2018-07-18T16:21:37.987-0700 : Content-Type: application/json
2018-07-18T16:21:37.987-0700 : Accept-Encoding: gzip
```

```
2018-07-18T16:21:37.987-0700 : -----------------------------------------------------
2018-07-18T16:21:39.476-0700 : 2018/07/18 16:21:39 [DEBUG] Google API Response Details:
2018-07-18T16:21:39.476-0700 : ---[ RESPONSE ]--------------------------------------
2018-07-18T16:21:39.476-0700 : HTTP/2.0 200 Ok
2018-07-18T16:21:39.476-0700 : {
2018-07-18T16:21:39.476-0700 :  "kind": "sql#operation",
2018-07-18T16:21:39.476-0700 :  "targetProject": "xxxxxxxxxx",
2018-07-18T16:21:39.476-0700 :  "targetId": "foo-a",
2018-07-18T16:21:39.476-0700 :  "operationType": "CREATE_REPLICA",
2018-07-18T16:21:39.476-0700 :  "status": "PENDING",
2018-07-18T16:21:39.476-0700 : }
2018-07-18T16:21:39.476-0700 :
2018-07-18T16:21:39.476-0700 : -----------------------------------------------------
2018-07-18T16:21:39.476-0700 : 2018/07/18 16:21:39 [DEBUG] Waiting for state to become: [DONE]
```

```
2018-07-18T16:21:39.521-0700 : 2018/07/18 16:21:39 [DEBUG] Google API Response Details:
2018-07-18T16:21:39.521-0700 : ---[ RESPONSE ]--------------------------------------
2018-07-18T16:21:39.521-0700 : HTTP/2.0 409 Conflict
2018-07-18T16:21:39.521-0700 :
2018-07-18T16:21:39.521-0700 : {
2018-07-18T16:21:39.521-0700 :  "error": {
2018-07-18T16:21:39.521-0700 :   "errors": [
2018-07-18T16:21:39.521-0700 :    {
2018-07-18T16:21:39.521-0700 :     "domain": "global",
2018-07-18T16:21:39.521-0700 :     "reason": "operationInProgress",
2018-07-18T16:21:39.521-0700 :     "message": "Operation failed because another operation was already in progress."
2018-07-18T16:21:39.521-0700 :    }
2018-07-18T16:21:39.521-0700 :   ],
2018-07-18T16:21:39.521-0700 :   "code": 409,
2018-07-18T16:21:39.521-0700 :   "message": "Operation failed because another operation was already in progress."
2018-07-18T16:21:39.521-0700 :  }
2018-07-18T16:21:39.521-0700 : }
```

**Comment by danawillow** [comment] 2018-07-19 19:49
@chroto actually it's a slightly different use case! The fix was on the database/users resources because they referenced a specific instance, but we didn't think of instances that reference other instances (in the case of replicas). I'll get a fix out for that shortly.

**Closed** 2018-07-19 20:20 UTC
Labels: bug, provider/google-cloud
