### ISSUE TITLE
Unable to create another postgres role within AWS Redshift database.

### ISSUE THREAD

**Issue by xvillanuOM** [hashicorp/terraform#11639] opened 2017-02-02 17:12 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.7.10

### Affected Resource(s)
Please list the resources as a list, for example:
- postgresql_role

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
module.database-sync.postgresql_role.service_user: Creating...
  encrypted: "" => "false"
  login:     "" => "true"
  name:      "" => "dbsync-test"
  password:  "" => "dbsync-pswd"
2017/02/02 16:49:58 [DEBUG] root.database-sync: eval: *terraform.EvalWriteState
2017/02/02 16:49:58 [DEBUG] root.database-sync: eval: *terraform.EvalApplyProvisioners
2017/02/02 16:49:58 [DEBUG] root.database-sync: eval: *terraform.EvalIf
2017/02/02 16:49:58 [DEBUG] root.database-sync: eval: *terraform.EvalWriteState
2017/02/02 16:49:58 [DEBUG] root.database-sync: eval: *terraform.EvalWriteDiff
2017/02/02 16:49:58 [DEBUG] root.database-sync: eval: *terraform.EvalApplyPost
2017/02/02 16:49:58 [ERROR] root.database-sync: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* postgresql_role.service_user: Error creating role: pq: syntax error at or near "ROLE"
2017/02/02 16:49:58 [ERROR] root.database-sync: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* postgresql_role.service_user: Error creating role: pq: syntax error at or near "ROLE"
2017/02/02 16:49:58 [ERROR] root.database-sync: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* postgresql_role.service_user: Error creating role: pq: syntax error at or near "ROLE"
2017/02/02 16:49:58 [ERROR] root.database-sync: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* postgresql_role.service_user: Error creating role: pq: syntax error at or near "ROLE"
2017/02/02 16:49:58 [DEBUG] vertex "module.database-sync.postgresql_database.service", got dep: "module.database-sync.postgresql_role.service_user"
2017/02/02 16:49:58 [DEBUG] vertex "module.database-sync.postgresql_database.service", got dep: "var.dbsync_postgres_db_name"
2017/02/02 16:49:58 [DEBUG] vertex "root", got dep: "module.database-sync.postgresql_database.service"
2017/02/02 16:49:58 [DEBUG] vertex "root", got dep: "var.env_cidr"
2017/02/02 16:49:58 [DEBUG] vertex "provider.module.database-sync.postgresql (close)", got dep: "module.database-sync.postgresql_database.service"
2017/02/02 16:49:58 [DEBUG] vertex "provider.module.database-sync.postgresql (close)", got dep: "module.database-sync.postgresql_role.service_user"
2017/02/02 16:49:58 [DEBUG] vertex "root", got dep: "provider.module.database-sync.postgresql (close)"

### Expected Behavior
Should be similar to adding a new role within AWS RDS postgres.

### Actual Behavior
* postgresql_role.service_user: Error creating role: pq: syntax error at or near "ROLE"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Try to add another role into AWS Redshift DB.

**Comment by pbthorste** [comment] 2017-02-07 13:34
same issue as https://github.com/hashicorp/terraform/issues/11362

**Comment by grubernaut** [comment] 2017-02-07 19:52
Hi @xvillanuOM, thanks for the issue!

Closing, duplicate of #11362. Happy to discuss further if it's different, however.

**Comment by xvillanuOM** [comment] 2017-02-23 20:44
@grubernaut, I don't see this as a duplicate of #11362 since I'm able to create role with password for RDS.  This issue relates solely to being able to do the same within RedShift.

**Comment by sean-** [comment] 2017-05-25 02:51
@xvillanuOM is this still an issue?  I wonder if RedShift is puking on the optional token `WITH` in the `CREATE ROLE` string.  ?  LMK.  If there's a doc page related to RedShift's `CREATE ROLE` syntax, that'd be helpful.

**Closed** 2017-06-13 19:28 UTC
Labels: bug, provider/postgresql
