### ISSUE TITLE
coalesce documentation does not explain that its arguments should be of the same type, and will be unified if not

### ISSUE THREAD

**Issue by dogmatic69** [hashicorp/terraform#26219] opened 2020-09-11 13:57 UTC
### Terraform Version
```
15:51 $ docker run --rm -it hashicorp/terraform -- --version
Terraform v0.13.2
```

### Terraform Configuration Files
n/a

### Debug Output
```
$ docker run --rm -it hashicorp/terraform console
// no string
> coalesce(false) == false ? 1 : 0
1
> coalesce("", null, false) == false ? 1 : 0
0
> tobool(coalesce("", null, false)) == false ? 1 : 0
1
> tobool(coalesce(false)) == false ? 1 : 0
1
// no string
> coalesce(null, false) == false ? 1 : 0
1

```

### Expected Behavior

Should not need to cast a boolean return value to boolean

This should output 1
```
> coalesce("", null, false) == false ? 1 : 0
0
```
but instead need to cast it:
```
> tobool(coalesce(false)) == false ? 1 : 0
1
```

### Actual Behavior
boolean is returned as string resulting in comparisons failing.

### Steps to Reproduce
see above

### Additional Context
n/a

### References
n/a

**Comment by alisdair** [comment] 2020-09-11 19:44
Thanks for submitting this report!

I believe that `coalesce` is acting as designed here, and there is a bug in the documentation. `coalesce` is expected to receive arguments of the same type, or at least compatible types. It therefore unifies all of its arguments to the same type before returning the first non-null, non-empty-string value.

The behaviour you're seeing here is caused by passing both boolean and string values to `coalesce`, resulting in unification to `string`. If you try passing incompatible types, you'll see a clear error:

```
$ echo 'coalesce(false, {b = 1})' | terraform console

Error: Error in function call

  on <console-input> line 1:
  (source code not available)

Call to function "coalesce" failed: all arguments must have the same type.
```

This behaviour is not made clear [in the documentation for `coalesce`](https://www.terraform.io/docs/configuration/functions/coalesce.html), and I think updating that is the way forward for this issue. I don't believe that we'll change the behaviour of `coalesce` to support returning an unconverted `bool` when passed both `bool` and `string` arguments, as the Terraform language is designed to know the type of values as early as possible, and does not support sum types.

Thanks again for reporting, and I hope I've explained what's happening here! I'll retitle this issue to explain that the docs should be fixed.

**Comment by dogmatic69** [comment] 2020-09-14 12:50
Makes sense, I've worked around my issue by returning a known string rather than the `false`. :+1:

**Closed** 2020-11-18 16:03 UTC
Labels: bug, documentation, explained
