### ISSUE TITLE
Augmenting count.index within a Math function does not evaluate correctly (Terraform 0.12)

### ISSUE THREAD

**Issue by sidewaiise** [hashicorp/terraform#22158] opened 2019-07-22 01:29 UTC
### Terraform Version

```
0.12.5
```

### Terraform Configuration Files

```hcl
resource "aws_route" "aws_services" {
  count = length(var.service-ips) * var.az-count * var.dx_applications[terraform.workspace]
  provider = aws.peer

  destination_cidr_block = var.service-ips[ceil((count.index / 2))
  nat_gateway_id = count.index > -1 ? aws_nat_gateway.nat-proxy[max((count.index % 2))].id : ""
  route_table_id = count.index > -1 ? aws_route_table.private_proxy[max((count.index % 2))].id : ""
}
```

### Debug Output

```
Error: Invalid index

  on dx-proxy-integration.tf line 1035, in resource "aws_route" "aws_services":
1035:   destination_cidr_block = var.service-ips[ceil((count.index / 2))]
    |----------------
    | count.index is 69
    | var.service-ips is tuple with 35 elements

The given key does not identify an element in this collection value.
```

### Crash Output

```
Error: Invalid index

  on dx-proxy-integration.tf line 1035, in resource "aws_route" "aws_services":
1035:   destination_cidr_block = var.service-ips[ceil((count.index / 2))]
    |----------------
    | count.index is 69
    | var.service-ips is tuple with 35 elements

The given key does not identify an element in this collection value.
```

### Expected Behavior

ceil(count.index / 2) should have evaluated first.

### Actual Behavior

terraform flagged count.index as outside the range of the list, ONLY based on count.index value

### Additional Context

No

**Comment by sidewaiise** [comment] 2019-07-22 03:46
Using `floor()` instead of `ceil()` seemed to evaluate differently.

**Comment by teamterraform** [comment] 2019-08-02 13:22
Hi @sidewaiise! Thank you for reporting this odd behavior.

There is some additional information that would be interesting to see: can you add this to your configuration and share the output (commenting out whatever you have to): 
```
locals {
 count = length(var.service-ips) * var.az-count * var.dx_applications[terraform.workspace]
}
output "ceil" {
  value = ceil((local.count / 2))
}

output "ip" {
var.service-ips[ceil((local.count / 2))]
```

So far I was able to reproduce a bug in the error messages, but not the bug you are reporting. Hopefully you can help us reproduce what you've seen.

 In this example, my list has 3 elements and the output of ceil(var.number/3) is 4, but the error message only shows the value of var.number:

```hcl
variable "list" {
  default = ["cat", "dog", "lizard"]
}

variable "number" {
  default = 11
}

output "list_item" {
  value = var.list[ceil(var.number/3)]
}

output "ceil" {
  value = ceil((var.number/3))
}
```

Output:
```

Error: Invalid index

  on main.tf line 10, in output "list_item":
  10:   value = var.list[ceil(var.number/3)]
    |----------------
    | var.list is tuple with 3 elements
    | var.number is 11

The given key does not identify an element in this collection value.
```

I can prove the value of ceil(var.number/3) by commenting out the first output:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

ceil = 4
```

**Comment by teamterraform** [comment] 2019-08-28 22:30
Hi again @sidewaiise!

We didn't hear back, but we looking at this again with fresh eyes it looks like Terraform was behaving correctly here.

If `count.index` is `69` then `ceil((count.index / 2))` is 35. If `var.service_ips` has 35 elements then the valid indices to use for it range from zero to 34. Therefore `ceil((count.index / 2))` _is_ out of range, and this error is correct.

As you saw, `floor` works out here. The reason why that is true is that it'll round _down_, so `floor((count.index / 2))` is 34 and thus the last element in the list. When rounding to the nearest list index we should always round down because the first element is element zero, and so for `count.index` of 1 that would produce `0.5` which rounds down to zero.

Since it seems like Terraform's behavior here was correct, we're going to close this out. Hopefully the above is helpful to explain what's going on here!

The error messages use some heuristics to try to guess what information might be helpful to solve a particular problem, but it can't always guess correctly. In cases like this where the result of a _computation_ is the important thing, you can try using `terraform console` to evaluate certain expressions and see how they behave outside of the context of a larger expression:

```
$ terraform console
> ceil((69 / 2))
35
> floor((69 / 2))
34
```

Thanks!

**Closed by teamterraform** 2019-08-28 22:30 UTC
Labels: bug, config, v0.12, waiting-response
