### ISSUE TITLE
Terraform 0.13.0 "count" value depends on resource attributes that cannot be determined while using length(list)

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform#25815] opened 2020-08-12 10:32 UTC
Hi there,

with Terraform 0.13.0, `terraform plan` and `terraform apply` failed when using count = length(of_list) on a resource. For example:

A module "compute" returns a list of network interface ids:

```
output "network_interface_ids" {
  description = "The ids of the network interfaces of the vms"
  value       = azurerm_network_interface.main.*.id
}

```
In the root module, i using this list to create associations with a azure application security group:
```
resource "azurerm_network_interface_application_security_group_association" "vms_to_asg" {
  count                         = length(module.compute_vm.network_interface_ids)
  network_interface_id          = module.compute_vm.network_interface_ids[count.index]
  application_security_group_id = azurerm_application_security_group.asg.id
}
```

Terraform fails with the message:

> 
> Error: Invalid count argument
> 
> The "count" value depends on resource attributes that cannot be determined
> until apply, so Terraform cannot predict how many instances will be created.
> To work around this, use the -target argument to first apply only the
> resources that the count depends on.

I have this error on multiple resources, also when i pass a list as module parameter and using the length of this with count in a module resource. Same error.

**Comment by danieldreier** [comment] 2020-08-12 19:19
Hello @paleeak!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

In this case, I think that what you're running into here is that terraform functions (like length) run at the very beginning of parsing, before we know how the results of the plan. This is an expected, although counter-intuitive behavior. I've been tracking examples of this non-obviousness at https://github.com/hashicorp/terraform/issues/25162.

In your particular case, I think what you're looking to do is to create a resource for the compute VMs. You should be able to do this using the new module [for_each](https://learn.hashicorp.com/tutorials/terraform/for-each?in=terraform/configuration-language) functionality, rather than count, because that won't require invoking a function.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. If the answer I've given here doesn't quite work, or you want to talk it through more, please do feel free to ask your question in the community forum.

**Comment by paleeak** [comment] 2020-08-12 20:08
@danieldreier I understand this place is for bugs. Iam using this code since Terraform 0.12.21 and it always works very well. So from my point, its a bug.

I dont see how for_each helps me out here. My "compute_vm" module returns a list of network_interface_ids and i just using this list to create assoications with count inside the root module.

I can try to use foreach instead of count in the azurerm_network_interface_application_security_group_association resource, but why terraform 0.13.0 works now different then terraform  0.12.x. I dont see a relevant change in the changelog on this.

**Comment by danieldreier** [comment] 2020-08-12 21:23
Thanks! I didn't understand. I've put it back in the queue for triage, because it seems like my understanding was wrong.

**Comment by paleeak** [comment] 2020-08-13 06:45
@danieldreier 

no problem. Iam sure my english is quite not the best.

I have try it with for_each, but i have to convert the network_interface_ids before, because its not a list, its a tuple. my mistake. So it results in the same problem:
```
Error: Invalid for_each argument

  on associations.tf line 34, in resource "azurerm_network_interface_application_security_group_association" "vm_to_asg":
  34:   for_each                      = toset(module.compute_vm.network_interface_ids)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

iam using the compute module from microsoft (or a near 1:1 copy). So  i cant change there the format of the output, because i use this tuple also in a seperate loadbalancer module and other modules.

https://github.com/Azure/terraform-azurerm-compute/blob/master/outputs.tf

And yes as i said, i have always used count (or for_each) depending on the length of something which is not static in its amount, since terraform 0.12.21. And iam quite sure, i have see this on many code from other poeple too, who write modules. Because many times the count resources depends by the count of other resources.  Like in my case:

A vm can have multiple network interface ids. So you have a "compute" module who compute vms and returning the network interface_ids. Then you want to assign this network interface ids to a application security group (which is a firewall on application level in azure). The amount of associations you need for this, depends on the amout of network interface ids of your vm.

For me, using count or for_each by invoking with length, is a so common usecase in many modules for monthes. But terraform 0.13.0 breaks this. Yes of course i can implement this different, but for me this looks like a unexplained workaround, because before 0.13.0, everything works fine.

**Comment by JanKoppe** [comment] 2020-08-20 14:29
I can confirm this bug. It's even happening while not changing anything. It's completely non-deterministic behaviour in our case. If I go ahead and target just the depending resource, sometimes it works after one targeted run, sometimes only after a few, sometimes never.

This is really bad and breaking some critical code for us.

**Comment by orbital112** [comment] 2020-08-20 15:52
I have the same issue @danieldreier @jbardin can you reopen this issue ticket?

**Comment by danieldreier** [comment] 2020-08-20 15:56
Sure! The original reporter closed it, not someone on the core team, so I'll re-open and let it run through the process. If any of the folks asking want to help, what we'd really need is a clear reproduction case that is easy for an engineer here to copy and paste without inventing any details. Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies.

**Comment by JanKoppe** [comment] 2020-08-21 08:55
main.tf
```
resource "null_resource" "a" {
  count = 5
}

data "null_data_source" "b" {
  inputs = {
    for a in null_resource.a : a.id => a.id
  }
}

resource "null_resource" "c" {
  count = length(data.null_data_source.b.outputs)
}
```

output:
```
$ terraform --version                                                                         
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/null v2.1.2

$ terraform apply

Error: Invalid count argument

  on main.tf line 12, in resource "null_resource" "c":
  12:   count = length(data.null_data_source.b.outputs)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

**Comment by JanKoppe** [comment] 2020-08-21 08:57
Version with for_each instead of count:

foreach.tf
```
resource "null_resource" "a" {
  count = 5
}

data "null_data_source" "b" {
  inputs = {
    for a in null_resource.a : a.id => a.id
  }
}

resource "null_resource" "c" {
  for_each = toset(data.null_data_source.b.outputs)
}
```
output:
```
$ terraform --version                                                                         
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/null v2.1.2

$ terraform apply
Error: Invalid for_each argument

  on foreach.tf line 12, in resource "null_resource" "c":
  12:   for_each = toset(data.null_data_source.b.outputs)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

**Comment by remche** [comment] 2020-08-25 08:00
Same here, using a `null_ressource` but not so minimal : 
https://travis-ci.com/github/remche/terraform-openstack-rke

Note that switching to `for_each` throws an error, too

```
Error: Invalid for_each argument

  on modules/rke/main.tf line 2, in resource "null_resource" "wait_for_master_ssh":
   2:   for_each = var.master_nodes

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```
Seems linked too #25851

**Comment by remche** [comment] 2020-08-25 15:17
I wrote a minimal case using only `null_resource` : 
https://github.com/remche/tf0.13-count-foreach

Terraform 0.12.x -> OK
Terraform 0.13.0 -> KO

**Comment by JanKoppe** [comment] 2020-08-27 06:48
Very interesting. remches testcase is reproducable for me with 0.13.0. If I use 0.13.1, the test case works fine again, but the issue that I'm seeing in our codebase still persists.

Wasn't able yet to build a minimal testcase that reproduces my issue.

**Comment by remche** [comment] 2020-08-28 12:59
0.13.1 fixes the test case. In our real case, first `apply` operation is successful but not the second :astonished: 

Anyway, `for_each` way is still broken : remche/tf0.13-count-foreach@caf950e

**Comment by jbardin** [comment] 2020-09-02 11:58
Thanks for the example, but the error from your `for_each` example is correct. You're attempting to use the attributes from the `module/one` nodes as the input to the `for_each` expression, which are unknown until apply.

**Comment by remche** [comment] 2020-09-02 13:20
oops, you're right ;)
I switched everything to `for_each` in our real case and everything run smoothly now. At least this `count` bug makes me switch to better practices :grin:

**Comment by kingsleyadam** [comment] 2020-09-03 09:43
@remche , do you have an example of how you fixed this?

I have a very similar situation as you. I'm not quite sure how to work around it. To me this is a bug. Pre 0.13.x this worked without issues for quite some time.

```
variable "load_balancers" {
  description = "Which load balancers to attach the servers to"
  type        = list(string)
}

data "azurerm_lb" "load_balancers" {
  for_each = {
    for index, value in var.load_balancers : index => value
  }
  name                = "${var.lb_prefix}-${var.realm}-${each.value}"
  resource_group_name = var.resource_group.name
}
```

```
Error: Invalid for_each argument

  on modules/virtual_machines/data.tf line 30, in data "azurerm_lb_backend_address_pool" "lb_backend_address_pools":
  30:   for_each = {
  31:     for index, value in data.azurerm_lb.load_balancers : index => value
  32:   }

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

**Comment by remche** [comment] 2020-09-03 10:15
@kingsleyadam the second `for_each` loop depends on a apply-time computed value. may be you could use a local variable to build a map ?

In my case I changed the output of a module to give the failing `for_each` a map where index can be computed before `apply`.
See remche/terraform-openstack-rke@bff90c05

**Comment by kingsleyadam** [comment] 2020-09-03 15:26
Thanks @remche. I have tried using a local variable, but it produces the same result. I was able to work around this by using the same variable `var.load_balancers` in my second for each.

```
data "azurerm_lb_backend_address_pool" "lb_backend_address_pools" {
  for_each = {
    for index, value in var.load_balancers : index => value
  }
  name            = "BackEndAddressPool"
  loadbalancer_id = data.azurerm_lb.load_balancers[each.index]
}
```

But then I received the same eror further down the line when I try to assign the backend pool to a list of VM's. The list of VM's is detirmined by a `var.vm_count` variable.

Also, sometimes I can get the entire plan to work when I target a non-related resource. And re-run the plan.

**Comment by kingsleyadam** [comment] 2020-09-03 20:46
I was able to resolve my issues so I'm posting in case someone else comes across this. The error is very misleading, I was under the impression that terraform couldn't come up with the list of items to be created based on my for_each.

```
...Terraform cannot predict how many instances will be created....
```

The real issue was that I was using an unknown value for they **key** of the for each. I was using the id of the resource that was to be created, which it didn't know during apply.

The fix was to use my own configured values for the key, now all my issues are resolved.

This did work in 0.12.x. Hope this helps someone.

**Comment by jbardin** [comment] 2020-09-22 12:56
There hasn't been any additional reproductions of the bug, and things seem to be working as intended here, so we're going to re-close the issue.

Thanks!

**Closed by jbardin** 2020-09-22 12:56 UTC
Labels: bug, new, v0.13, waiting for reproduction
