### ISSUE TITLE
Chef provisioner does not properly handle non-UTF-8 output from Chef

### ISSUE THREAD

**Issue by JustLeo** [hashicorp/terraform#22856] opened 2019-09-19 19:39 UTC
### Terraform Version

```
Terraform v0.12.9
+ provider.aws v2.24.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
Nothing relevant, just running chef provisioner and calling some recipes. They work without any problem outside Terraform.
```

### Debug Output

https://gist.github.com/JustLeo/d063c3d924d11591f3f97de0d20554ea
### Expected Behavior

Deploy chef recipe without any error

### Actual Behavior

I'm getting "Error: rpc error: code = Internal desc = grpc: error while marshaling: proto: field "tfplugin5.ProvisionResource.Response.Output" contains invalid UTF-8"

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
### Additional Context

When trying to debug this problem, I started running the recipe over and over again and sometimes, with no good reason, it worked without the error message.

**Comment by teamterraform** [comment] 2019-09-19 20:39
Hi @JustLeo! Thanks for reporting this.

The Terraform language and protocols consider strings to be unicode and thus requires strings arriving via wire protocols to be UTF-8 encoded, so unfortunately it's by design that non-UTF-8 strings cannot be returned here, but since this seems to just be general progress output emitted by the provisioner, it is probably okay for the provisioner to pre-sanitize these strings to replace non-UTF-8 sequences with the replacement character so that the rest of the message is still readable.

The Chef provisioner doesn't currently have a maintainer, so unfortunately it's unlikely that this issue can be addressed in the very near future except via community contribution. :confounded: If you or anyone else has the time and motivation to implement it, and have a Chef system to run the tests against, we'd be happy to review a PR so long as the solution is relatively straightforward and thus possible to review without Chef expertise.

In the meantime, a workaround would be to ensure that Chef does not produce any non-UTF-8 characters, which would involve analyzing whatever output Terraform is trying to send here by running Chef directly and changing whatever is producing this output.

**Comment by JustLeo** [comment] 2019-09-20 12:34
Ok, thanks for the quick response. I'll try to find another way to accomplish what I need without using chef provisioner. I guess we can close this ticket.

**Closed** 2019-09-20 12:34 UTC
Labels: bug, provisioner/chef, v0.12
