### ISSUE TITLE
Crash on apply

### ISSUE THREAD

**Issue by ch3pjw** [hashicorp/terraform#15555] opened 2017-07-14 16:30 UTC
### Terraform Version
v0.9.11

### Terraform Configuration Files
If you comment, I can give you read access to my private git repo.

### Debug Output, Panic Output
https://gist.github.com/ch3pjw/fbc4e57b99bf1a935ce7e08646e8eb23

### Expected Behavior
I expected terraform to deploy my heroku app successfully, as it had done a number of times previously.

### Actual Behavior
The linked panic.

### Steps to Reproduce
`terraform apply -state ../terraform_state/terraform.tfstate`

Happy to answer anything else you like, I'm fairly new to all this!

**Comment by grubernaut** [comment] 2017-07-14 19:15
Hey @ch3pjw, thanks for the issue! 

This is actually a duplicate of https://github.com/terraform-providers/terraform-provider-heroku/issues/2, closing in favor of the provider-level issue. 
Thanks!

**Closed by grubernaut** 2017-07-14 19:15 UTC

**Comment by ch3pjw** [comment] 2017-07-15 00:33
Given that the original issue is over a year old, is this likely to get looked at? Do you have any pointers on how I can diagnose/work around my issue? Cheers!

**Comment by ch3pjw** [comment] 2017-10-15 23:37
Thanks for fixing this - it dropped off my radar for a while, but I'm back to needing it again and the latest release works brilliantly :star:
