### ISSUE TITLE
null_resource : triggers->build_number always executed even if count = 0

### ISSUE THREAD

**Issue by mldmld68** [hashicorp/terraform#24581] opened 2020-04-07 09:28 UTC
Hi
I have the exact need as described in this issue  : https://github.com/hashicorp/terraform/issues/20458

### Expected behavior

variable "execute-build" {
  default = 1
}

resource "null_resource" "build_project" {
  count = "${var.execute-build}"

  triggers {
    build_number = "${timestamp()}"
  }

  provisioner "local-exec" {
    command = "date"
  }
}

$ terraform apply -var 'execute-build=0'

The null_resource -> build_project is omitted.

I would like to be able to 
- recreate the resource each time terraform apply is done when count > 0
- destroy the resource or ignore each time terraform apply is done when count = 0

### Actual behavior

$ terraform apply -var 'execute-build=0'

Command of the null_resource -> build_project is executed.

Thank you

Terraform version : Terraform v0.12.24

**Comment by danieldreier** [comment] 2020-04-09 01:02
I tried to reproduce this:

First case:
```terraform
variable "execute-build" {
  default = 1
}

resource "null_resource" "build_project" {
  count = var.execute-build

  triggers = {
    build_number = timestamp()
  }

  provisioner "local-exec" {
    command = "date"
  }
}
```

```
❯ terraform apply
null_resource.build_project[0]: Refreshing state... [id=8756226720612015071]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # null_resource.build_project[0] must be replaced
-/+ resource "null_resource" "build_project" {
      ~ id       = "8756226720612015071" -> (known after apply)
      + triggers = (known after apply) # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.build_project[0]: Destroying... [id=8756226720612015071]
null_resource.build_project[0]: Destruction complete after 0s
null_resource.build_project[0]: Creating...
null_resource.build_project[0]: Provisioning with 'local-exec'...
null_resource.build_project[0] (local-exec): Executing: ["/bin/sh" "-c" "date"]
null_resource.build_project[0] (local-exec): Wed Apr  8 17:57:09 PDT 2020
null_resource.build_project[0]: Creation complete after 0s [id=3268021168137867498]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
src/repro/gh-24581 took 6s
❯ terraform apply
null_resource.build_project[0]: Refreshing state... [id=3268021168137867498]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # null_resource.build_project[0] must be replaced
-/+ resource "null_resource" "build_project" {
      ~ id       = "3268021168137867498" -> (known after apply)
      ~ triggers = {
          - "build_number" = "2020-04-09T00:57:09Z"
        } -> (known after apply) # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.build_project[0]: Destroying... [id=3268021168137867498]
null_resource.build_project[0]: Destruction complete after 0s
null_resource.build_project[0]: Creating...
null_resource.build_project[0]: Provisioning with 'local-exec'...
null_resource.build_project[0] (local-exec): Executing: ["/bin/sh" "-c" "date"]
null_resource.build_project[0] (local-exec): Wed Apr  8 17:57:11 PDT 2020
null_resource.build_project[0]: Creation complete after 0s [id=225379457799658618]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

When I change the default value of `execute-build` to 0, the first `terraform apply` returns:
```terraform
terraform apply                                                                                                  ✔  1295  17:58:14
null_resource.build_project[0]: Refreshing state... [id=225379457799658618]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # null_resource.build_project[0] will be destroyed
  - resource "null_resource" "build_project" {
      - id       = "225379457799658618" -> null
      - triggers = {
          - "build_number" = "2020-04-09T00:57:11Z"
        } -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.build_project[0]: Destroying... [id=225379457799658618]
null_resource.build_project[0]: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
src/repro/gh-24581 took 13s
```

Subsequent `terraform apply` runs return the expected result:
```
❯ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
src/repro/gh-24581
❯ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
src/repro/gh-24581
```

Please note that I used the 0.12upgrade tool on your example and made minor syntax fixes. With those fixes, I think it works as expected; I'm not able to reproduce the failure mode you're describing.

**Comment by apparentlymart** [comment] 2020-06-26 00:34
Hi @mldmld68!

We didn't hear back from you after @danieldreier's reply, so I'm going to close this. If you're still seeing the problem and can show a configuration example that we can run to see it fail the same way as you are describing, please let us know and we can reopen this issue. Thanks!

**Closed by apparentlymart** 2020-06-26 00:34 UTC
Labels: waiting-response
