### ISSUE TITLE
Error message without details

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#33331] opened 2023-06-08 03:50 UTC
### Terraform Version

```shell
1.4.6
```

### Terraform Configuration Files

-

### Debug Output

-

### Expected Behavior

Succeeded run

### Actual Behavior

An error that I can not diagnose:

```none
module.deployment-domain.module.deployment-domain-int.aws_acm_certificate_validation.cert[0]: Refreshing state... [id=0001-01-01 00:00:00 +0000 UTC]
╷
│ Error: Missing required argument
│
│ The argument "password" is required, but was not set.
╵
╷
│ Error: Missing required argument
│
│ The argument "username" is required, but was not set.
╵
╷
│ Error: Missing required argument
│
│ The argument "endpoint" is required, but was not set.
╵
> Terraform failed
```

### Steps to Reproduce

I don't know how to reproduce the error because I don't know where the error is.

### Additional Context

I'm trying to delete the deployment but TF fails and I don't know where.

**Comment by jbardin** [comment] 2023-06-08 13:51
Hi @speller,

It looks like there an error path which didn't get any context added in, but I'm not sure why either. Can capture the trace log for the plan to see if that has any messages which correlate to the failure?

**Comment by jbardin** [comment] 2023-06-08 15:07
Thanks @speller,

If you removed a provider from the configuration, but there are resources which still require that provider, then that provider still needs to be run to deal with the remaining resources. If Terraform can guess the provider type, then it will try to initialize the provider with no configuration assuming it is not required.

This is duplicate of #28482, though I'm not sure why you didn't get the `No configuration found for provider["registry.terraform.io/hashicorp/aws"]` error to help diagnose the missing provider, perhaps because it was an older provider version?

**Closed by jbardin** 2023-06-08 15:07 UTC
Labels: bug, waiting-response, new

**Comment by speller** [comment] 2023-06-09 02:04
@jbardin 
Terraform v1.4.6
Using hashicorp/aws v5.1.0
Using cyrilgdn/rabbitmq v1.8.0 <-- This is the provider that was required
