### ISSUE TITLE
Cannot ssh into instances created byTerraform ( Permission denied (publickey,gssapi-keyex,gssapi-with-mic )

### ISSUE THREAD

**Issue by dibyajyotiron** [hashicorp/terraform#25727] opened 2020-08-02 18:09 UTC
### Terraform Version

```
Terraform v0.12.29
```

Local Operating System : `Windows 10 build 19041.421`

### Terraform Configuration Files

- provider.tf

> ```
> provider "aws" {
>   access_key = var.AWS_ACCESS_KEY
>   secret_key = var.AWS_SECRET_KEY
>   region     = var.AWS_REGION
> }
> ```

- vars.tf

> ```
> variable "TF_LOG" {
>   default = null
> }
> variable "AWS_ACCESS_KEY" {
>   default = null
> }
> variable "AWS_SECRET_KEY" {
>   default = null
> }
> variable "AWS_REGION" {
>   default = "ap-south-1"
> }
> variable "KEY_NAME" {
>   type = string
> }
> variable "AMIS" {
>   type = map(string)
>   default = {
>     ap-south-1 = "ami-0ebc1ac48dfd14136"
>   }
> }
> variable "sg_ingress_ssh" {
>   type = list(object({
>     from_port   = number
>     to_port     = number
>     protocol    = string
>     cidr_block  = list(string)
>     description = string
>   }))
>   default = [
>     {
>       from_port   = 22
>       to_port     = 22
>       protocol    = "tcp"
>       cidr_block  = ["<my_ip>/32"]
>       description = "ssh_my_ip"
>   }]
> }
> variable "sg_ingress_nodejs_mongo" {
>   type = list(object({
>     from_port   = number
>     to_port     = number
>     protocol    = string
>     cidr_block  = list(string)
>     description = string
>   }))
>   default = [
>     {
>       from_port   = 3000
>       to_port     = 3000
>       protocol    = "tcp"
>       cidr_block  = ["<my_ip>/32"]
>       description = "nodejs_myip"
>     },
>     {
>       from_port   = 27017
>       to_port     = 27017
>       protocol    = "tcp"
>       cidr_block  = ["<my-ip>/32"]
>       description = "mongo_myip"
>     }
>   ]
> }
> ```
> 

- instance.tf 

> ```
> resource "aws_instance" "nodejs" {
>   ami           = var.AMIS[var.AWS_REGION]
>   instance_type = "t2.micro"
>   key_name      = var.KEY_NAME
>   tags = {
>     Name = "Nodejs test"
>   }
>   vpc_security_group_ids = [aws_security_group.node_mongo_ssh.id]
> 
> 
> }
> output "instance_ip" {
>   description = "The public ip for ssh access"
>   value       = aws_instance.nodejs.public_ip
> }
> 
> 
> ```
> 

- terraform.tfvars

> ```
> AWS_ACCESS_KEY = "abcdef"
> AWS_SECRET_KEY = "ghijklmno"
> KEY_NAME       = "terraform"
> ```
> 

- security_group.tf

> ```
> resource "aws_security_group" "node_mongo_ssh" {
>   name        = "node_mongo_ssh"
>   description = "Security group for adding my ip for node and mongo and ssh"
>   tags = {
>     Name = "Node_Mongo_SSH"
>   }
> }
> 
> resource "aws_security_group_rule" "node_mongo" {
>   count = length(var.sg_ingress_nodejs_mongo)
> 
>   type        = "ingress"
>   from_port   = var.sg_ingress_nodejs_mongo[count.index].from_port
>   to_port     = var.sg_ingress_nodejs_mongo[count.index].to_port
>   protocol    = var.sg_ingress_nodejs_mongo[count.index].protocol
>   cidr_blocks = var.sg_ingress_nodejs_mongo[count.index].cidr_block
>   description = var.sg_ingress_nodejs_mongo[count.index].description
> 
>   security_group_id = aws_security_group.node_mongo_ssh.id
> }
> 
> resource "aws_security_group_rule" "ssh" {
>   count = length(var.sg_ingress_ssh)
> 
>   type        = "ingress"
>   from_port   = var.sg_ingress_ssh[count.index].from_port
>   to_port     = var.sg_ingress_ssh[count.index].to_port
>   protocol    = var.sg_ingress_ssh[count.index].protocol
>   cidr_blocks = var.sg_ingress_ssh[count.index].cidr_block
>   description = var.sg_ingress_ssh[count.index].description
> 
>   security_group_id = aws_security_group.node_mongo_ssh.id
> 
> }
> ```

### Debug Output
```
aws_security_group.node_mongo_ssh: Creating...
aws_security_group.node_mongo_ssh: Creation complete after 2s [id=sg-0a42d37d3b5efca66]
aws_security_group_rule.ssh[0]: Creating...
aws_security_group_rule.node_mongo[0]: Creating...
aws_security_group_rule.node_mongo[1]: Creating...
aws_instance.nodejs: Creating...
aws_security_group_rule.ssh[0]: Creation complete after 1s [id=sgrule-3913484728]
aws_security_group_rule.node_mongo[0]: Creation complete after 2s [id=sgrule-671293375]
aws_security_group_rule.node_mongo[1]: Creation complete after 4s [id=sgrule-2745365589]
aws_instance.nodejs: Still creating... [10s elapsed]
aws_instance.nodejs: Still creating... [20s elapsed]
aws_instance.nodejs: Creation complete after 24s [id=i-0db05b98b9f8c149c]

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

Outputs:

instance_ip = 13.127.97.212
```
### Expected Behavior
Once the instance is created I should be able to ssh into the instance.

### Actual Behavior
Instead, it throws me  `Permission denied (publickey,gssapi-keyex,gssapi-with-mic)` error when I try to ssh using terraform.pem.
If I create the instance in aws, it works like charm, no issues, but with terraform I'm getting this issue. terraform.pem was created by using aws, I tried using 
```
 resource "aws_key_pair" "key_pair" {
   key_name   = var.KEY_NAME
   public_key = file("ssh_keys/terraform.pub") (this file exists in my project, was generated by ssh-keygen with rsa 4096)
 }
```
and changed the instance key name in the instance.tf but that also didn't work. The same error is always thrown.

### Steps to Reproduce

1. Created a pem file named terraform.pem in aws ec2 and download it locally. Then move it to the $project_dir/ssh_keys/terraform.pem. 

2. `terraform apply -auto-approve`

### Additional Context
Using terraform.exe in windows, no docker image.
This entire flow works correctly but If I try to provision a file that times out eventually, even I can't ssh into the created instance, gives this error, but creating the instance manually with the same key gives me access to the instance through ssh.

**Comment by dibyajyotiron** [comment] 2020-08-02 18:16
TF_LOG is set to default i.e trace. Here I forgot to paste it.

**Comment by alisdair** [comment] 2020-08-14 15:56
I'm unable to reproduce this issue. With the configuration you specified, I'm able to SSH into the Terraform-created instance using `ssh -i ./terraform.pem ec2-user@<ip>`

Can you please upload the logs of the Terraform session and the last few lines of running `ssh -vvv`?

**Comment by pselle** [comment] 2021-02-12 20:40
Hello, since this has been open for some time and does not yet have a reproduction, I'm going to close this issue.

**Closed by pselle** 2021-02-12 20:40 UTC
Labels: bug, v0.12, waiting for reproduction, waiting-response, windows
