### ISSUE TITLE
Terraform 1.8 crashes with "no expansion has been registered"

### ISSUE THREAD

**Issue by lucasmo** [hashicorp/terraform#35002] opened 2024-04-15 18:01 UTC
### Terraform Version

```shell
Terraform v1.8.0
```

### Terraform Configuration Files

Confidential

### Debug Output

I can't enable this in our environment

### Expected Behavior

Terraform apply shouldn't have crashed.

### Actual Behavior

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: no expansion has been registered for module.xyz.module.abc.module.zyx_execute_shell_script_that_waits
goroutine 4418 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/runner/work/terraform/terraform/internal/logging/panic.go:84 +0x18b
panic({0x2e00120?, 0xc012c301d0?})
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandAbsModuleCall(0x2f3a180?, {{0xc011322580, 0x2, 0x2}, {{}, {0xc00081b060, 0x1a}}})
	/home/runner/work/terraform/terraform/internal/instances/expander.go:171 +0x265
github.com/hashicorp/terraform/internal/terraform.(*evaluationStateData).GetModule(0xc01bcbe900, {{}, {0xc00081b060?, 0xc0000135f9?}}, {{0xc002a3e4c0, 0x35}, {0x4, 0x12, 0xc8}, {0x4, ...}})
	/home/runner/work/terraform/terraform/internal/terraform/evaluate.go:398 +0x788
github.com/hashicorp/terraform/internal/lang.(*Scope).evalContext(0xc01bcbe990, {0xc01bcba170, 0x1, 0x1}, {0x3d64030, 0xc012c13ef0})
	/home/runner/work/terraform/terraform/internal/lang/eval.go:381 +0x1112
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalReference(0xc01bcbe990, 0xc01bf95c00, {{0x3d75ce0?, 0x5891580?}})
	/home/runner/work/terraform/terraform/internal/lang/eval.go:216 +0x9b
github.com/hashicorp/terraform/internal/terraform.validateDependsOn({0x3d984a8, 0xc002ea93b0}, {0xc0016be510?, 0xc00e0c3770?, 0x5891580?})
	/home/runner/work/terraform/terraform/internal/terraform/node_resource_validate.go:581 +0x42e
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableOutput).Execute(0xc006607860, {0x3d984a8, 0xc002ea93b0}, 0x70?)
	/home/runner/work/terraform/terraform/internal/terraform/node_output.go:382 +0x791
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc005b4e640, {0x3d984a8, 0xc002ea93b0}, {0x7fa963de0d58, 0xc006607860})
	/home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:153 +0xbb
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x32a43c0, 0xc006607860})
	/home/runner/work/terraform/terraform/internal/terraform/graph.go:112 +0x62a
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc006607920, {0x32a43c0, 0xc006607860}, 0xc01bf97900)
	/home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 1450
	/home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xff3
```

### Steps to Reproduce

Init and apply.

### Additional Context

This happens during the execution of `terraform apply` on a plan generated by `terraform plan`.

**Comment by jbardin** [comment] 2024-04-15 19:39
Duplicate of #34976

**Closed by jbardin** 2024-04-15 19:39 UTC
Labels: bug, new
