### ISSUE TITLE
`terraform init -upgrade` doesn't always upgrade to latest acceptable provider version

### ISSUE THREAD

**Issue by TV4Fun** [hashicorp/terraform#22773] opened 2019-09-11 20:32 UTC
### Terraform Version

```
Terraform v0.12.8
+ provider.google v2.12.0
+ provider.google-beta v2.12.0
```

### Terraform Configuration Files

```hcl
provider "google" {
  project = "***"
  version = "~> 2.0"
  region  = "us-central1"
  zone    = "us-central1-c"
}

provider "google-beta" {
  project = "***"
  version = "~> 2.0"
  region  = "us-central1"
  zone    = "us-central1-c"
}
```

### Debug Output

https://gist.github.com/TV4Fun/4722dce9a6bf7e97132d7035d026b4b7

### Expected Behavior

The latest version of the `google` and `google-beta` providers is 2.14.0. The installed version was 2.12.0. Terraform should have upgraded to the latest version.

### Actual Behavior

Terraform did not upgrade and kept the `2.12.0` providers

### Steps to Reproduce

1.
```hcl
provider "google" {
  project = "***"
  version = "2.12.0"
  region  = "us-central1"
  zone    = "us-central1-c"
}

provider "google-beta" {
  project = "***"
  version = "2.12.0"
  region  = "us-central1"
  zone    = "us-central1-c"
}
```
2. `terraform init`

3.
```hcl
provider "google" {
  project = "***"
  version = "~> 2.0"
  region  = "us-central1"
  zone    = "us-central1-c"
}

provider "google-beta" {
  project = "***"
  version = "~> 2.0"
  region  = "us-central1"
  zone    = "us-central1-c"
}
```
4. `terraform init -upgrade`

### Additional Context

I was able to force an upgrade by setting my provider string to `>= 2.14, < 3`, but I shouldn't have to do this.

**Comment by apparentlymart** [comment] 2021-10-06 00:33
Hi @TV4Fun! Thanks for opening this issue, and sorry we apparently didn't catch it at the time.

With that said, we entirely rewrote the provider installer as part of Terraform v0.13 to introduce the hierarchical provider namespace and installation of third-party providers from registries, and so the code that caused the behavior you saw here is no longer present in modern Terraform.

I'm going to close this to represent that. The current intended behavior is that Terraform will remember in [the dependency lock file](https://www.terraform.io/docs/language/dependency-lock.html) which version of each provider was selected by the most recent `terraform init`, and then the `-upgrade` option to `terraform init` takes on the new meaning of ignoring those locks and just taking the latest available version. The set of plugins installed in the local cache directory (`.terraform/providers`, by default) is no longer considered by Terraform when deciding what to install, because the dependency lock file has taken over that role as being the source of truth for selections.

If you or anyone else is still seeing behavior similar to what you described here in the latest version of Terraform, please open a new issue so we can capture an updated set of configuration examples, logs, and reproductions steps against the new provider installer implementation.

Thanks again!

**Closed by apparentlymart** 2021-10-06 00:33 UTC
Labels: bug, cli, v0.12
