### ISSUE TITLE
0.12 empty dynamic blocks are still getting added

### ISSUE THREAD

**Issue by marcb1** [hashicorp/terraform#22403] opened 2019-08-08 21:56 UTC
This is much similar to this issue: https://github.com/hashicorp/terraform/issues/21373
Though I don't think it's been fixed, or I'm doing something wrong.

I have the following in a module:
```
resource "google_container_cluster" "simple-cluster-template" {
  dynamic "database_encryption" {
    for_each = var.database_encryption == null ? [] : [for n in var.database_encryption: {
      state = n.encryption_state
      key = n.encryption_key
    }]
    content {
      state    = database_encryption.value.state
      key_name = database_encryption.value.key
    }
...
[MORE STUFF IN MODULE THAT'S IRRELEVANT]
}
```

with the following variable definition:
```
variable "database_encryption" {
  type = list(object({
    encryption_state = string
    encryption_key = string
  }))
  default = null
}
```

The `database_encryption` block is only available in the `google-beta` provider, docs are here https://www.terraform.io/docs/providers/google/r/container_cluster.html#database_encryption

When using the module described above, we set the provider to `google-beta` and set `database_encryption` like so:
```
module "test-cluster" {
  source = "../modules/test-module"
  providers = {
    google = "google-beta"
  }
  database_encryption = [{
    encryption_state = "ENCRYPTED"
    encryption_key = "test_key"
  }]
[MORE STUFF OMITTED, IRRELEVANT]
}
```

The problem is for clusters that don't use the google beta provider and don't set `database_encryption`, I get the following error:
```
in resource "google_container_cluster" "simple-cluster-template":
 115:   dynamic "database_encryption" {

Blocks of type "database_encryption" are not expected here.
```

Though this shouldn't happen, since `database_encryption` defaults to `null`, and shouldn't create the `database_encryption` block. I think the error is that the block is getting created and the `google` provider (non-beta) does not expect that block. Not sure why this is happening, or if something is wrong with my syntax.
I'm using the latest version of terraform:
```
./terraform version
Terraform v0.12.6
+ provider.aws v2.23.0
+ provider.google v2.12.0
+ provider.google-beta v2.12.0
```

**Comment by marcb1** [comment] 2019-08-12 21:42
To follow up, looks like the `dynamic` block is properly omitted when it is empty. Though the `database_encryption` block is only available in `google-beta`. When using the non-beta version of the `google` provider, TF throws an error because it is not expecting that module. Would be nice if this is fixed i.e only throw an error if `database_encryption` is non-empty and non-beta version of provider is used

**Comment by teamterraform** [comment] 2019-08-13 00:23
Hi @marcb1!

Terraform's validation step checks that the configuration is _statically_ valid, which is to say that the configuration arguments and blocks must be consistent with the schema regardless of what values might be set dynamically during planning.

In this case, Terraform is reporting that you can't have a `dynamic "database_encryption"` block because that _could_ (for certain values of `var.database_encryption`) produce one or more blocks that are not valid per the schema. This is roughly analogous to if you were using a general-purpose programming language with a static type system and you tried to assign `null` to a field that was added to a class or structure in a later version of a library than you are currently using: in most languages, the compiler would reject it just based on its presence in your code, without considering what value you've assigned to it.

Sadly, even if this check were not failing the following is also invalid here (but masked by the other error):

```hcl
  providers = {
    google = "google-beta"
  }
```

The `providers` map can only be used to assign between aliases or default configurations of the _same_ provider. It's not valid to substitute `google-beta` for `google` because from Terraform's standpoint those are two completely unrelated providers, even though in practice they have a lot of schema in common.

With all of that said, unfortunately the current design of the `google` vs. `google-beta` providers means that the two are not interchangeable in this way and a module must be written for either one provider or the other. A module _can_ use both of them together, but each resource would still depend on a specific one; there is no way to dynamically choose one or the other, because provider-to-resource relationships are static in Terraform.

If the module is exposing beta-only features then it must itself use the `google-beta` provider on the relevant resources, which then encapsulates that decision inside the module and avoids the need for the caller to know about it. If that feature becomes stable in future, you can then change the module to use the `google` provider in a later change without any need to change the callers.

Since Terraform is working as designed here, we're going to close this out. If you have further questions about the above, feel free to start a discussion topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!

**Closed by teamterraform** 2019-08-13 00:23 UTC
Labels: config, question

**Comment by marcb1** [comment] 2019-08-13 14:47
@teamterraform thanks for the thorough explanation!
