### ISSUE TITLE
Slash gets replace by the current directory when importing a resource into the state

### ISSUE THREAD

**Issue by DenWin** [hashicorp/terraform#28288] opened 2021-04-06 11:13 UTC
Hi,

when I try to execute:
`terraform import azurerm_resource_group.rg /subscriptions/000000-0000-0000-0000-000000000000/resourceGroups/prtl-mo-rg` it the leading slash before "subscription" gets replace by the current path I'm in.

![image](https://user-images.githubusercontent.com/13867326/113698815-218cad00-96d5-11eb-871c-74855d5240a4.png)

This specific behavior only occurs when I execute this in Bash for Windows.
If I run it in Linux everything works fine.
If I run it in Powershell on Windows: Works

But running it in Bash for Windows causes this odd behavior.

My terraform file:
```
terraform {
    required_providers {
        azurerm = {
            source = "hashicorp/azurerm"
            version = "<=2.53.0"
        }
    }
}

provider "azurerm" {
    # Configuration options
    features {}
}

resource azurerm_resource_group rg {
    name = "prtl-mo-rg"
}
```

I was able to boil it down to the fact, that it seems to already be read in improperly by Go according to the output in the TRACE Log:
```
2021/04/06 12:33:31 [INFO] Terraform version: 0.14.7  
2021/04/06 12:33:31 [INFO] Go runtime version: go1.15.6
2021/04/06 12:33:31 [INFO] CLI args: []string{"C:\\ProgramData\\chocolatey\\lib\\terraform\\tools\\terraform.exe", "import", "azurerm_resouce_group.rg", "C:/Program Files/Git/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/prtl-mo-rg"}
```

The corresponding lines in Terraform in main.go (line 142-146):
```
	log.Printf(
		"[INFO] Terraform version: %s %s",
		Version, VersionPrerelease)
	log.Printf("[INFO] Go runtime version: %s", runtime.Version())
	log.Printf("[INFO] CLI args: %#v", os.Args)
```

I'm not 100% sure, whether this is a something to be tracked here and forwarded into the Go-Issue board, or whether it should be entered there directly.
At the very least, if someone has the same issue with Terraform here is why.

**Comment by jbardin** [comment] 2021-04-06 12:46
Hi @DenWin,

I'm not familiar with running bash on windows, but the behavior here is not something that terraform do in this case, because as you've shown in the log output, the argument that terraform sees has already been modified to become an absolute file path. 

The usual remedy for unwanted shell interpolation is to wrap the argument in single quotes, which is generally the standard practice in order to prevent any other special shell characters, quotes, whitespace, etc. from being interpolated. Since terraform is working as intended I'm going to close this out, but feel free tor to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) if you have more questions, and where there may be other that have experience using the same windows environment.

Thanks!

**Closed by jbardin** 2021-04-06 12:46 UTC
Labels: bug, new

**Comment by DenWin** [comment] 2021-04-06 12:49
same issue with single quotes, double quotes and escaped quotes ( $'   ' ) as well as escaping the letters.
