### ISSUE TITLE
Recreating a google_compute_instance removes it from instance groups

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform#10896] opened 2016-12-21 23:36 UTC
**To reproduce:**

* Run example in https://github.com/hashicorp/terraform/pull/10844 with `terraform apply`
* Make a change to `startup.sh`
* Run `terraform apply` again

**Expected result:**

* Instances are deleted and recreated, and re-added to their instance groups

**Actual result:**

* Instances are deleted and recreated but not re-added to their instance groups.

@evandbrown let's go over this tomorrow

**Comment by zbikmarc** [comment] 2017-01-27 13:16
I have exact same problem. Any progress on this?

**Comment by danawillow** [comment] 2017-01-27 15:13
No progress yet- I'll take a look next week and see if I can figure out what's going on.

**Comment by danawillow** [comment] 2017-02-03 00:49
I looked over this a bit more but still don't have a good answer. I think I understand what's going on, at least: since the instances are deleted and recreated, they have the same self_link as before the recreation. When terraform goes to check the diff for the instance group, it doesn't see any diff because the list of instances is the same.

Here's a smaller repro than the example:
```
resource "google_compute_instance" "instance" {
  name = "instance"
  machine_type = "f1-micro"
  zone         = "us-central1-a"
  disk {
    image = "debian-cloud/debian-8"
  }

  network_interface {
    subnetwork = "my-custom-subnet"
    access_config {
    }
  }

  metadata_startup_script = "echo 'hey'"
}

resource "google_compute_instance_group" "ig" {
  name = "ig"
  instances = [
    "${google_compute_instance.instance.self_link}"
  ]

  zone = "us-central1-a"
}
```
where my-custom-subnet was one that I already had in my project.

@paddyforan, any ideas? This seems like something more relevant to terraform core rather than the google provider.

**Comment by zbikmarc** [comment] 2017-02-03 07:43
I think the problem is order of operations:
1. destroy instances
2. create new instances
3. remove instances from group

In my opinion proper order of operations should be:
1. remove marked instances from group
1. destroy instances
1. create new instances
1. reassign instances to group

Regarding to this:
> I think I understand what's going on, at least: since the instances are deleted and recreated, they have the same self_link as before the recreation. When Terraform goes to check the diff for the instance group, it doesn't see any diff because the list of instances is the same.

Please look at #11511 Different self_links makes things even worse, because Terraform tries to remove non existing instances from group and it fails of course.

**Comment by danawillow** [comment] 2017-02-03 16:24
Sure, but it's not terraform that's removing the instances from the group- it's happening by GCE itself on deletion. I'm not sure there's a way to do it manually in terraform since the `instance` resource doesn't know that the `instance_group` depends on it.

I haven't looked at your issue yet, I'll try to take a look next week if nobody else has gotten to it by then.

**Closed** 2017-06-13 19:20 UTC
Labels: bug, provider/google-cloud
