### ISSUE TITLE
Latest Release is marked as v0.11.15 instead of v0.15.1

### ISSUE THREAD

**Issue by WhiteFruit** [hashicorp/terraform#28528] opened 2021-04-27 14:55 UTC
This isn't actually a bug, but I'm not sure where else to report this.

Thanks for your time.

**Comment by jbardin** [comment] 2021-04-27 16:53
Marking as a duplicate of #28530 to see if there is any way to influence what the GitHub UI returns for `latest`

**Closed by jbardin** 2021-04-27 16:53 UTC
Labels: bug, new
