### ISSUE TITLE
Ability to use Provider Alias with for_each Meta Argument

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform#32738] opened 2023-02-23 00:51 UTC
### Terraform Version

```shell
Terraform v1.3.9
on linux_amd64
```

### Use Cases

There are a great deal of situations where a duplicate resource is deployed to many regions, regardless of cloud (azure/aws/gcloud etc).  In these situations, currently a lot of copy/paste boilerplate is required to copy/paste the resource and edit the `provider` meta argument to that resource.

It would be beneficial to be able to condense this into 1 resource, utilizing a for_each, and potentially a local or a way to call a provider with many alias (such as multiple provider blocks for aws with different region configs and alias' for them).

### Attempted Solutions

After much research and attempting to use for_each with a local type list of Strings with each alias value, and providing the alias value to the `provider` meta argument and failing, I learned that currently terraform cannot facilitate this.

### Proposal

There are two ways this could be handled.

Either allow `for_each` to take an argument of providers such as:

`for_each = provider.aws` with `each.key` being the full provider name, so that `provider = each.key` would be valid for example:

```hcl
resource "some_resource" "some_name" {
  for_each = provider.aws
  provider = each.key
}
```

OR

Allow `provider` to take a string in a `for_each` resource, so I could create a local such as:

```hcl
locals {
  regions = ["us-east-1","us-east-2"]
}

resource "some_resource" "some_name" {
  for_each = toset(local.regions)
  provider = aws[each.key]
}
```

**Comment by jiba21** [comment] 2023-02-24 14:46
Welcome to the party 🚀 
https://github.com/hashicorp/terraform/issues/19932

**Comment by crw** [comment] 2023-02-24 22:00
Closing as a duplicate of https://github.com/hashicorp/terraform/issues/19932. If you believe this to be in error (e.g., this is describing a distinct use case), please let me know.

**Closed by crw** 2023-02-24 22:00 UTC
Labels: enhancement, new
