### ISSUE TITLE
Take into account "depends_on" when doing "create_before_destroy"

### ISSUE THREAD

**Issue by LarsNeR** [hashicorp/terraform#22411] opened 2019-08-09 09:56 UTC
### Current Terraform Version

```
Terraform v0.11.14
```

### Use-cases

We have resource A and resource B. Resource B `depends_on` resource A. Both resources are always updated in the same `terraform apply`. But when updating B, resource A needs to be there in the old version and in the new version.

Concrete example: AWS Sagemaker Endpoint Configuration and AWS Sagemaker Endpoint. When updating the Endpoint the old Endpoint Configuration has to exist and the new Endpoint configuration otherwise it says 

> aws_sagemaker_endpoint.sagemaker_endpoint: error updating SageMaker Endpoint (my-endpoint): ValidationException: Could not find endpoint configuration "arn:aws:sagemaker:eu-central-1:asdf:endpoint-config/my-old-endpointconfig

### Attempted Solutions

I already tried 
`  lifecycle {
    create_before_destroy = true
  }`

but that alone does not solve the problem.

### Proposal

When doing `terraform apply` it should consider the dependencies when 
`  lifecycle {
    create_before_destroy = true
  }`
is set. In my example above that would mean, that:
1. Resource A_new is created
2. Resource B is updated
3. Resource A_old is destroyed

or in the concrete example:
1. New `sagemaker_endpoint_config` is created
2. `sagemaker_endpoint` is updated to use the new `sagemaker_endpoint_config` (for this step the old `sagemaker_endpoint_config` still needs to exist)
3. Old `sagemaker_endpoint_config` is destroyed

**Comment by jbardin** [comment] 2020-07-03 16:46
Hi @LarsNeR,

This should be working as described in the next release. You can try out the latest 0.13 beta if you want to test.

Thanks!

**Comment by bugok** [comment] 2020-11-09 08:18
@jbardin: It's great to hear that this is coming.  I see the issue is still open - does that mean that the fix hasn't been merged? 

I have a similar use case. 

I'm creating an `aws_acm_certificate`, and then pass its `.arn` that to a `helm_release` resource of nginx ingress controller`. Under the hood, nginx is configured to use that certificate. 
When I update the certificate (which has the `create_before_destroy` setting), `terraform apply` fails, because terraform can't delete the old cert, as it's being actively used by nginx. Therefore, taking the proposed approach would work for me: 
1. Creating the new cert (updating resource A)
2. Updating the nginx `helm_release` resource (update resource B)
3. Delete the old cert (delete old resource A)

Thank you!

**Comment by jbardin** [comment] 2020-11-09 14:13
Hi @bugok 

The change here was merged into the initial 0.13 release, but I forgot to tag this to be closed after confirmation.
Since we're in the process of release 0.14 now, I'll close this issue out. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Closed by jbardin** 2020-11-09 14:13 UTC
Labels: core, enhancement
