### ISSUE TITLE
aws_db_instance create read replica error: MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by arcadiatea** [hashicorp/terraform#11891] opened 2017-02-12 08:53 UTC
Trying to create read replica in same region and cross region. Both function works on the version 0.8.5 and 0.7.13 but error out on v0.8.6

Error message 

```bash
* aws_db_instance.default_readonly: Error creating DB Instance: MissingRegion: could not find region configuration
* aws_db_instance.default_readonly_cr: Error creating DB Instance: MissingRegion: could not find region configuration
```

main.tf
```bash
# the master database setting
resource "aws_db_instance" "default_master" {
  identifier                  = "${module.naming.aws_db_instance}"
  vpc_security_group_ids      = ["${module.networks.security_group}","${module.onprem-networks.security_group}","${aws_security_group.default.id}"]
  db_subnet_group_name        = "${module.networks.rds_subnet_group}"
  parameter_group_name        = "${aws_db_parameter_group.default_master.name}"

  engine                      = "postgres"
  engine_version              = "${var.db_engine_version}"
  port                        = "5432"
  allocated_storage           = "${var.db_allocated_storage}"
  storage_type                = "${var.db_storage_type}"
  iops                        = "${var.db_iops}"
  instance_class              = "${var.db_instance_class}"
  name                        = "${var.db_name}"
  username                    = "${var.db_username}"
  password                    = "${var.db_password}"
  multi_az                    = "${var.db_multi_az}"
  backup_retention_period     = "${var.db_backup_retention_period}"
  backup_window               = "${var.db_backup_window}"
  maintenance_window          = "${var.db_maintenance_window}"
  auto_minor_version_upgrade  = "${var.db_minor_version_upgrade}"
  allow_major_version_upgrade = "${var.db_major_version_upgrade}"
  apply_immediately           = "${var.db_apply_immediately}"
  snapshot_identifier         = "${var.db_snapshot_identifier}"
  final_snapshot_identifier   = "${module.naming.aws_db_instance}-final"
  copy_tags_to_snapshot       = "${var.db_copy_tags_to_snapshot}"
  skip_final_snapshot         = "${var.db_skip_final_snapshot}"

}


# Create read replica in same region

resource "aws_db_instance" "default_readonly" {
  count                          = "${var.db_ro_slave_count}"
  identifier                     = "${module.naming.aws_db_instance}-ro${count.index + 1}"
  vpc_security_group_ids         = ["${module.networks.security_group}"]
  db_subnet_group_name           = "${module.networks.rds_subnet_group}"
  parameter_group_name           = "${aws_db_parameter_group.default_ro.name}"
  port                           = "5432"
  storage_type                   = "${var.db_ro_storage_type}"
  iops                           = "${var.db_ro_iops}"
  instance_class                 = "${var.db_ro_instance_class}"

  copy_tags_to_snapshot          = "${var.db_ro_copy_tags_to_snapshot}"
  # Slave can have different favor on auto minor version upgrade.
  auto_minor_version_upgrade     = "${var.db_ro_minor_version_upgrade}"
  apply_immediately              = "${var.db_ro_apply_immediately}"
  replicate_source_db           = "${aws_db_instance.default_master.arn}"

}

# Here is the setting or cross region read replica

resource "aws_db_instance" "default_readonly_cr" {
  # Use different provider to deploy to cross region
  provider                       = "aws.readonly"
  count                          = "${var.db_cr_slave_count}"
  identifier                     = "${module.naming.aws_db_instance}-cro${count.index + 1}"
  vpc_security_group_ids         = ["${module.networks_readonly.security_group}"]
  db_subnet_group_name           = "${module.networks_readonly.rds_subnet_group}"
  parameter_group_name           = "${aws_db_parameter_group.default_cr.name}"
  port                           = "5432"
  storage_type                   = "${var.db_cr_storage_type}"
  iops                           = "${var.db_cr_iops}"
  instance_class                 = "${var.db_cr_instance_class}"
  copy_tags_to_snapshot          = "${var.db_cr_copy_tags_to_snapshot}"
  auto_minor_version_upgrade     = "${var.db_cr_minor_version_upgrade}"
  apply_immediately              = "${var.db_cr_apply_immediately}"
  replicate_source_db            = "${aws_db_instance.default_master.arn}"

}

```

I am using dual provider

```bash
provider "aws" {
  region  = "${var.aws_region}"
  profile = "${var.aws_profile}"
}

provider "aws" {
  alias = "readonly"
  region  = "us-west-2"
  profile = "${var.aws_profile}"
}

```

**Comment by stack72** [comment] 2017-02-12 19:58
Closing as duplicate of #11797

**Closed by stack72** 2017-02-12 19:58 UTC
