### ISSUE TITLE
"cluster_identifier": required field is not set... invalid or unknown key: cluster_identifer

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#3750] opened 2015-11-04 11:35 UTC
I'm trying to define an RDS Aurora cluster as follows:

```
resource "aws_rds_cluster_instance" "rds_cluster_instance" {
  count = "${var.db_instances}"
  cluster_identifer = "${aws_rds_cluster.default.id}"
  instance_class = "db.r3.large"
}

resource "aws_rds_cluster" "default" {
  cluster_identifier = "rds-cluster-${var.vpc_name}-${var.stack}"
  availability_zones = ["${split(",", var.availability_zones)}"]
  database_name = "${var.db_name}"
  master_username = "${var.db_username}"
  master_password = "${var.db_password}"
}
```

With `db_instances` set to 3, when I run `terraform apply`, I get the following error:

```
  * aws_rds_cluster_instance.rds_cluster_instance #0: "cluster_identifier": required field is not set
  * aws_rds_cluster_instance.rds_cluster_instance #0: : invalid or unknown key: cluster_identifer
  * aws_rds_cluster_instance.rds_cluster_instance #2: "cluster_identifier": required field is not set
  * aws_rds_cluster_instance.rds_cluster_instance #2: : invalid or unknown key: cluster_identifer
  * aws_rds_cluster_instance.rds_cluster_instance #1: "cluster_identifier": required field is not set
  * aws_rds_cluster_instance.rds_cluster_instance #1: : invalid or unknown key: cluster_identifer
```

Not sure what to do from here. I'm on Terraform v0.6.4.

**Comment by brikis98** [comment] 2015-11-04 11:41
I just tried the example directly from the [documentation](https://www.terraform.io/docs/providers/aws/r/rds_cluster_instance.html):

```
resource "aws_rds_cluster_instance" "cluster_instances" {
  count = 2
  identifier = "aurora-cluster-demo"
  cluster_identifer = "${aws_rds_cluster.default.id}"
  instance_class = "db.r3.large"
}

resource "aws_rds_cluster" "default" {
  cluster_identifier = "aurora-cluster-demo"
  availability_zones = ["us-west-2a","us-west-2b","us-west-2c"]
  database_name = "mydb"
  master_username = "foo"
  master_password = "bar"
}
```

I still get the same type of error:

```
  * aws_rds_cluster_instance.cluster_instances #1: "cluster_identifier": required field is not set
  * aws_rds_cluster_instance.cluster_instances #1: : invalid or unknown key: cluster_identifer
  * aws_rds_cluster_instance.cluster_instances #0: "cluster_identifier": required field is not set
  * aws_rds_cluster_instance.cluster_instances #0: : invalid or unknown key: cluster_identifer
```

**Comment by josh-padnick** [comment] 2015-11-09 03:05
I can confirm the steps outlined by @brikis98 do in fact generate this bug.  This is currently a blocker for us on a project where we'd like to use RDS/Aurora.

**Comment by brikis98** [comment] 2015-11-23 03:55
Anyone have any thoughts on this one?

**Comment by catsby** [comment] 2015-11-23 22:29
Hello friends – sorry for the silence here. It looks like this is a typo in the documentation, it's `cluster_identifier`, not `cluster_identifer`. It was fixed in https://github.com/hashicorp/terraform/pull/3795 , I must have failed to deploy the updated docs until just now with the v0.6.7 release  :frowning: 

Sorry for the trouble, let me know if you're hitting something else

**Closed by catsby** 2015-11-23 22:29 UTC
Labels: bug, provider/aws

**Comment by brikis98** [comment] 2015-11-23 22:46
Ah, fantastic, thank you!

**Comment by catsby** [comment] 2015-11-24 19:58
Sorry for the trouble
