### ISSUE TITLE
Failed to decode resource from state in v1.3.5 and v1.3.6

### ISSUE THREAD

**Issue by ogind-bdhavale** [hashicorp/terraform#32331] opened 2022-12-05 11:25 UTC
### Terraform Version

```shell
$ terraform version
Terraform v1.3.6
on linux_amd64
```

### Terraform Configuration Files

```
module "test4" {
  source = "git::git@github.com:<repo URL>"
  providers = {
    aws        = aws
    statuscake = statuscake
  }
}
```

### Debug Output

NA

### Expected Behavior

terraform plan should be executed without any error

### Actual Behavior

I ran `terraform init` and all went well

When running the plan to destroy with below command:
`terraform plan -destroy -target module.test4 -out destroy.tfplan`

I get an error below:

```
Error: Failed to decode resource from state
Error decoding module.demo.aws_lb_listener_rule.customer_host_routing from previous state: unsupported attribute "field"

```

### Steps to Reproduce

1. `export export AWS_PROFILE=...`
2. `saml2aws -a ${AWS_PROFILE} login`
3. `terraform init`
4. `terraform plan -destroy -target module.test4 -out destroy.tfplan`

**Comment by jbardin** [comment] 2022-12-05 14:29
Duplicate of #31052

**Closed by jbardin** 2022-12-05 14:29 UTC
Labels: bug, new

**Comment by ogind-bdhavale** [comment] 2022-12-05 15:53
As mentioned in #31052 I tried to execute `terraform init --upgrade`  but received below error.

```
│ Error: Error accessing remote module registry
│ Failed to retrieve a download URL for app.terraform.io/opengov/name/aws 0.2.0 from app.terraform.io: module
│ "app.terraform.io/orgname/name/aws" version "0.2.0" not found
```
