### ISSUE TITLE
Provider needed should be configured through specific attributes by users, not  opinionated yourself.

### ISSUE THREAD

**Issue by bretagne-peiqi** [hashicorp/terraform#31004] opened 2022-05-05 15:00 UTC
https://github.com/hashicorp/terraform/issues/31002

**Comment by bretagne-peiqi** [comment] 2022-05-05 15:01
this will cause big problem for users.

**Comment by apparentlymart** [comment] 2022-05-05 15:03
Hi @bretagne-peiqi!

I'm afraid I'm not sure what you intend this bug to represent. Could you please copy [the bug report template](https://raw.githubusercontent.com/hashicorp/terraform/main/.github/ISSUE_TEMPLATE/bug_report.md) into a new comment and provide the information it requests, so that we can learn more about what problem you're describing? Thanks!

**Comment by maxb** [comment] 2022-05-08 08:33
I believe this is just a terse objection to the previous issue, #31002, being closed. I've commented on the previous issue and believe this one can be closed as a duplicate.

**Comment by apparentlymart** [comment] 2022-05-09 15:09
Closing as a duplicate of the other issue.

**Closed by apparentlymart** 2022-05-09 15:09 UTC
Labels: bug, new
