### ISSUE TITLE
The "count" value depends on resource attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by yohanuta** [hashicorp/terraform#28962] opened 2021-06-15 15:15 UTC
### Terraform Version

```
1.0.0
```

### main.tf

```terraform
resource "random_id" "random_label" {
  byte_length = 2
}

module "a" {
  source    = "./child"
  name      = "a"
  //  label = null
  label = random_id.random_label.hex
}


output "main-test-out" {
  value = random_id.random_label.id
}
```

###child/main.tf
```terraform
variable "name" {
  type = string
}

variable "label" {
  type = string
  default = null
}

resource "null_resource" "x" {
  count = var.label == null ? 1 : 0
  //depends_on = [var.label,]
}

output "ids" {
  value = null_resource.x.*.id
}

```

### Crash Output

Error: Invalid count argument

   on child/main.tf line 11, in resource "null_resource" "x":
   11:   count = var.label == null ? 1 : 0

 The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.

### Explaination
I built a minimal example to show the problem I have. Is there any way to give a random label to a module, which uses this to decide whether to create a resource or not (using `count`)?

### Expected Behavior

I expect that `random_label` gets created first and then `count` is applied.  
### Actual Behavior

Apparantly, `count` is applied first. Since `random_label` is needed to decide whether a resource is to be created or not, an error is thrown. 

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### References

I believe this is the same issue as https://github.com/hashicorp/terraform/issues/26078

**Comment by apparentlymart** [comment] 2021-06-15 15:25
Hi @yohanuta,

What you've seen here is the intended behavior of Terraform. An important purpose of creating a Terraform plan is to see how many objects will be created, and so Terraform has a rule that the `count` and `for_each` arguments must be determined only from values defined directly in the configuration, not from values that a provider will generate during the apply phase.

The random provider is a little unusual here in that it doesn't actually interact with a remote system and so in principle it could generate its random values during the plan step, but it seems to be designed to behave similarly to a more typical resource type that represents a remote API, where often the resulting values won't be known until the provider actually makes the call to create the corresponding object, and therefore those results would not be suitable to use with `count` or `for_each`.

To make this work will require designing your configuration to derive `count` and `for_each` only from values defined statically in the documentation. Since your example here seems to be a contrived one just to illustrate the situation I won't try to show an example here, but if you have a real situation where you'd like to discuss other designs that fit within the language rules then please start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), where we can discuss your specific situation in more detail.

Since what you described is Terraform's intended behavior, I'm going to close this. Thanks!

**Closed by apparentlymart** 2021-06-15 15:25 UTC
Labels: bug, new
