### ISSUE TITLE
Unable to create an aws_launch_configuration with an instance store AMI

### ISSUE THREAD

**Issue by omribahumi** [hashicorp/terraform#8732] opened 2016-09-08 11:31 UTC
### Terraform Version

```
$ terraform --version
Terraform v0.7.3
```
### Affected Resource(s)
- aws_launch_configuration
### Terraform Configuration Files

``` hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_launch_configuration" "test-launch-config" {
  image_id = "ami-01f69916" // us-east-1 ubuntu 12.04 amd64 hvm instance-store
  instance_type = "c3.large"
}
```
### Debug Output

```
$ terraform apply
aws_launch_configuration.test-launch-config: Creating...
  associate_public_ip_address: "" => "false"
  ebs_block_device.#:          "" => "<computed>"
  ebs_optimized:               "" => "<computed>"
  enable_monitoring:           "" => "true"
  image_id:                    "" => "ami-01f69916"
  instance_type:               "" => "c3.large"
  key_name:                    "" => "<computed>"
  name:                        "" => "<computed>"
  root_block_device.#:         "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* aws_launch_configuration.test-launch-config: [WARN] Error finding Root Device Name for AMI (ami-01f69916)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
### Expected Behavior

Launch config should have been created.
When using the same AMI without block devices on a `aws_instance` resource, everything works fine.
### Actual Behavior

Fails with an error:
`Error finding Root Device Name for AMI (ami-01f69916)`
### Steps to Reproduce

`terraform apply`

**Comment by Dnile** [comment] 2016-09-20 19:26
getting the same with terraform `0.7.4` , when trying to create launch_configuration for an `i2` instance.

` [WARN] Error finding Root Device Name for AMI (ami-08128d1f)`

**Comment by jbussdieker** [comment] 2016-09-22 07:47
Has anyone found a workaround for this yet?

**Comment by tpounds** [comment] 2016-09-27 18:15
We are experiencing the same issue. This behavior change was introduced by commit 391a7f85 and affects all Terraform versions >= v0.7.x.

**Comment by tpounds** [comment] 2016-09-27 18:32
The problem is due to the code not understanding that some AMIs root devices are backed by the instance store. Compare the output from the official Amazon Linux AMIs

```
$ aws ec2 describe-images --region us-east-1 --image-ids ami-6869aa05
{
    "Images": [
        {
            "VirtualizationType": "hvm", 
            "Name": "amzn-ami-hvm-2016.03.3.x86_64-gp2", 
            "Hypervisor": "xen", 
            "ImageOwnerAlias": "amazon", 
            "SriovNetSupport": "simple", 
            "ImageId": "ami-6869aa05", 
            "State": "available", 
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda", 
                    "Ebs": {
                        "DeleteOnTermination": true, 
                        "SnapshotId": "snap-25dd2ac1", 
                        "VolumeSize": 8, 
                        "VolumeType": "gp2", 
                        "Encrypted": false
                    }
                }
            ], 
            "Architecture": "x86_64", 
            "ImageLocation": "amazon/amzn-ami-hvm-2016.03.3.x86_64-gp2", 
            "RootDeviceType": "ebs", 
            "OwnerId": "137112412989", 
            "RootDeviceName": "/dev/xvda", 
            "CreationDate": "2016-06-22T06:10:37.000Z", 
            "Public": true, 
            "ImageType": "machine", 
            "Description": "Amazon Linux AMI 2016.03.3 x86_64 HVM GP2"
        }
    ]
}

$ aws ec2 describe-images --region us-east-1 --image-ids ami-dc6aa9b1
{
    "Images": [
        {
            "VirtualizationType": "hvm", 
            "Name": "amzn-ami-hvm-2016.03.3.x86_64-s3", 
            "Hypervisor": "xen", 
            "ImageOwnerAlias": "amazon", 
            "SriovNetSupport": "simple", 
            "ImageId": "ami-dc6aa9b1", 
            "State": "available", 
            "BlockDeviceMappings": [], 
            "Architecture": "x86_64", 
            "ImageLocation": "amzn-ami-us-east-1/amzn-ami-hvm-2016.03.3.x86_64.manifest.xml", 
            "RootDeviceType": "instance-store", 
            "OwnerId": "137112412989", 
            "CreationDate": "2016-06-22T06:04:58.000Z", 
            "Public": true, 
            "ImageType": "machine", 
            "Description": "Amazon Linux AMI 2016.03.3 x86_64 HVM S3"
        }
    ]
}
```

**Comment by tpounds** [comment] 2016-09-27 21:58
I have a preliminary fix in https://github.com/tpounds/terraform/commit/e1e864a3dd87aab14e060b5b0df0c30b38083344 which seems to fix the issue. I'll submit a pull request once I do some more verification and add a few acceptance tests.

**Comment by michael-henderson** [comment] 2016-11-27 08:33
@tpounds Any idea on an ETA for this getting merged?  Thanks for the fix! :)

**Closed** 2016-12-01 13:53 UTC
Labels: bug, provider/aws

**Comment by clebio** [comment] 2018-06-11 17:25
Hello, I seem to have hit this error just now, and am not sure why -- has it resurfaced, or something else?

```
data "aws_ami" "main" {
  most_recent = true
  owners = ["137112412989"]
  filter {
    name   = "name"
    values = ["amzn-ami-hvm-*"]
  }
}
```

```
$ terraform version
Terraform v0.11.7
+ provider.aws v1.22.0
```

Apply yields:
```
* module.jenkins.aws_launch_configuration.main: 1 error(s) occurred:

* aws_launch_configuration.main: Expected to find a Root Device name for AMI (ami-40ce433f), but got none```
Thoughts?

**Comment by sgargan** [comment] 2018-08-07 12:56
@clebio saw a similar issue which turned out to be the persmissions on the target ami making it public got me around this. Could be ^ is being incorrectly reported as a catchall for any kind of issue with the ami

**Comment by mildwonkey** [comment] 2018-08-07 13:58
Hi all,

Issues with the terraform aws provider should be opened in the [aws provider repository](https://github.com/terraform-providers/terraform-provider-aws).

Because this closed issue is generating notifications for subscribers, I am going to lock it and encourage anyone experiencing issues with the aws provider to open tickets [there](https://github.com/terraform-providers/terraform-provider-aws). (The other provider repositories are under the [terraform-provider](https://github.com/terraform-providers) org).

Please continue to open issues here for any other terraform issues you encounter, and thanks!
