### ISSUE TITLE
Provide linux arm64 docker image

### ISSUE THREAD

**Issue by runlevel5** [hashicorp/terraform#29895] opened 2021-11-08 04:58 UTC
It would be great if linux/arm64 docker image is supported officially. We've been running our CI/CD pipeline with custom built docker image for few months and everything works great.

**Comment by crw** [comment] 2021-11-16 00:41
Hi @runlevel5, thanks for the report! I have relayed this request to the release engineering team. I will update this ticket when I have more information to share.

**Comment by crw** [comment] 2021-12-09 23:31
I cannot promise a delivery date, but we (HashiCorp) are working on new release tooling that, when released, will build these images automatically "for free." I'll keep this issue open to track the request. Thanks again for the request!

**Comment by crw** [comment] 2022-01-05 23:24
Dupe of issue https://github.com/hashicorp/terraform/issues/25571

**Closed by crw** 2022-01-05 23:24 UTC
Labels: enhancement
