### ISSUE TITLE
massive destroy performance degradation with 1.3.x

### ISSUE THREAD

**Issue by rafabu** [hashicorp/terraform#32234] opened 2022-11-17 09:22 UTC
### Terraform Version

```shell
`Terraform v1.3.4
on windows_amd64
+ provider registry.terraform.io/azure/azapi v1.1.0
+ provider registry.terraform.io/databricks/databricks v1.6.5
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/azuread v2.30.0
+ provider registry.terraform.io/hashicorp/azurerm v3.31.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/microsoft/azuredevops v0.3.0`
```

### Terraform Configuration Files

```
terraform {
  backend "azurerm" {}

  required_version = ">= 1.2.9"

  required_providers {
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.2"
    }
    azapi = {
      source  = "azure/azapi"
      version = "~> 1.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.30"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "~> 0.3"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.31"
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = "~> 2.2"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.6"
    }
    external = {
      source  = "hashicorp/external"
      version = "~> 2.2"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.4"
    }
    time = {
      source  = "hashicorp/time"
      version = "~> 0.9"
    }
  }
}

provider "azurerm" {
  environment = "public"
  # if any of the STOR has key access disabled, the provider must switch to using AzureAD
  storage_use_azuread = local.azurerm_storage_use_azuread_core
  subscription_id     = local.core_subscription_id
  tenant_id           = local.core_tenant_id
  features { }
}
provider "azuread" {
  tenant_id = local.core_tenant_id
}
provider "azapi" {
  environment     = "public"
  subscription_id = local.core_subscription_id
  tenant_id       = local.core_tenant_id
}

provider "azurerm" {
  alias       = "prod"
  environment = "public"
  # if any of the STOR has key access disabled, the provider must switch to using AzureAD
  storage_use_azuread = local.azurerm_storage_use_azuread_prod
  subscription_id     = local.prod_subscription_id
  tenant_id           = local.prod_tenant_id
  features {}
}
provider "azuread" {
  alias     = "prod"
  tenant_id = local.prod_tenant_id
}
provider "azapi" {
  alias           = "prod"
  environment     = "public"
  subscription_id = local.prod_subscription_id
  tenant_id       = local.prod_tenant_id
}

provider "azurerm" {
  alias       = "int"
  environment = "public"
  # if any of the STOR has key access disabled, the provider must switch to using AzureAD
  storage_use_azuread = local.azurerm_storage_use_azuread_int
  subscription_id     = local.int_subscription_id
  tenant_id           = local.int_tenant_id
  features {}
}
provider "azuread" {
  alias     = "int"
  tenant_id = local.int_tenant_id
}
provider "azapi" {
  alias           = "int"
  environment     = "public"
  subscription_id = local.int_subscription_id
  tenant_id       = local.int_tenant_id
}

provider "azurerm" {
  alias       = "test"
  environment = "public"
  # if any of the STOR has key access disabled, the provider must switch to using AzureAD
  storage_use_azuread = local.azurerm_storage_use_azuread_test
  subscription_id     = local.test_subscription_id
  tenant_id           = local.test_tenant_id
  features {}
}
provider "azuread" {
  alias     = "test"
  tenant_id = local.test_tenant_id
}
provider "azapi" {
  alias           = "test"
  environment     = "public"
  subscription_id = local.test_subscription_id
  tenant_id       = local.test_tenant_id
}

provider "azurerm" {
  alias       = "dev"
  environment = "public"
  # if any of the STOR has key access disabled, the provider must switch to using AzureAD
  storage_use_azuread = local.azurerm_storage_use_azuread_dev
  subscription_id     = local.dev_subscription_id
  tenant_id           = local.dev_tenant_id
  features {}
}
provider "azuread" {
  alias     = "dev"
  tenant_id = local.dev_tenant_id
}
provider "azapi" {
  alias           = "dev"
  environment     = "public"
  subscription_id = local.dev_subscription_id
  tenant_id       = local.dev_tenant_id
}
```

### Debug Output

Debug output of both a 1.3.4 and 1.2.9 operation has been collected and can be provided upon request (sensitivity)

### Expected Behavior

Destroy using 1.3 should not take longer than with 1.2 versions.

### Actual Behavior

Executing `terraform destroy` with version 1.3.4 takes up to _six times as long_ during its planning phase compared to running against the same state with 1.2.x releases.

Sample measurement planning with 356 resources
`1.2.9`:    **7 minutes**
 `1.3.4`:   **40 minutes**

- No performance degradation is observed during `terraform plan` and `terraform apply`.
- The destruction phase (after confirming the destroy) also seems to be affected with a longer delay before destroying of resources on the cloud sets in. However, the actual operation succeeds.
- Same behaviour both on Ubuntu and Windows
- executing `terraform apply -refresh-only -destroy` does not seem to improve the situation
- I wasn't able to spot much improvement when going through the various 1.3 versions (e.g. regarding #32060 and #32071)

Happening on a rather complex terraform deployment involving:
- relatively large number of modules (many for_each ed)
- mainly AzureRM with an AzureRM remote backend
- named instances of providers exist to configure different subscriptions

### Steps to Reproduce

1. `terraform destroy` against a successfully deployed environment both with version `1.2.9` and `1.3.4`.
2. measure the time it takes until the result of the planning phase is displayed (_Do you really want to destroy all resources?_).

### Additional Context

Terraform is normally run as part of a PowerShell CD script. Both interactively as well as in release pipelines.
When it comes to destroy, those are often executed manually but the behaviour is the same on test-pipelines which create, test and immediately afterwards destroy environments.
After briefly looking at the debug output, most of the delay time seems to be happening with `DestroyEdgeTransformer` operations.

### References

- #32060
- #32071

**Comment by jbardin** [comment] 2022-11-17 14:26
Hi @rafabu,

Thanks for filing the issue. More work does need to be done in preparing to destroy instances now, but so far the impact has been minimal. Given the significant extra time, I suspect watching the trace logs is sufficient to see where the time is spent. If it is primarily between `DestroyEdgeTransformer` lines, then I think we have our culprit. You could try planning with `-refresh-false`, and while that will speed it up a bit, it's probably not taking the bulk of the time.

It also unfortunate that we have to pay this twice right now, once while validating the plan, and once again while building the apply graph, which of course is doubling the penalty.

**Comment by rafabu** [comment] 2022-11-17 20:52
You are spot on @jbardin - according to the logs a total of 36 minutes are now spent in two long runs of `*terraform.DestroyEdgeTransformer`. While the 1.2.9 logs only showed a delay of roughly 2 seconds.

**Comment by rafabu** [comment] 2022-12-01 23:01
Update due to the release of `1.3.6` (same initial phase of a full terraform destroy)

1.2.9: 7 minutes
1.3.4: 40 minutes
1.3.6: 18 minutes

@jbardin I am not sure if #32272 had made it into 1.3.6 or not but the situation has improved significantly now.

**Comment by jbardin** [comment] 2022-12-02 15:38
Thanks for confirming @rafabu!

That PR was backported already, so is what made up the the bulk of the time difference. The apparent doubling of time from 1.2 is kind of expected, as a configuration with this many interdependent providers is quite complex to process, so the apply graph validation which now happens during plan is going to duplicate a considerable portion of the plan work. Finding a better way to optimize the planning process is something we need to work on for future release, so since this is working as intended at this point, I'm going to close it for now.

Thanks!

**Closed by jbardin** 2022-12-02 15:38 UTC
Labels: bug, core, v1.3
