### ISSUE TITLE
fmt: multi-line declaration inconsistency in v0.12.1

### ISSUE THREAD

**Issue by garthk** [hashicorp/terraform#21600] opened 2019-06-05 01:20 UTC
### Terraform Version

```
Terraform v0.12.1
```

### Terraform Configuration Files

```hcl
resource "aws_subnet" "public_subnet" {
  vpc_id = aws_vpc.vpc.id
  count  = length(var.availability_zones)
  cidr_block = cidrsubnet(
    var.environment_cidr[var.environment],
    var.subnet_bits["public"] - 16,
    count.index + 128,
  )
  availability_zone       = element(var.availability_zones, count.index)
  map_public_ip_on_launch = true
```

### Debug Output

```
2019/06/05 11:12:36 [INFO] Terraform version: 0.12.1  
2019/06/05 11:12:36 [INFO] Go runtime version: go1.12.5
2019/06/05 11:12:36 [INFO] CLI args: []string{"/usr/local/opt/terraform/bin/terraform", "fmt", "modules/network/main.tf"}
2019/06/05 11:12:36 [DEBUG] Attempting to open CLI config file: /Users/self/.terraformrc
2019/06/05 11:12:36 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/06/05 11:12:36 [INFO] CLI command args: []string{"fmt", "modules/network/main.tf"}
2019/06/05 11:12:36 [TRACE] terraform fmt: Formatting modules/network/main.tf
```

### Expected Behavior

* Blank lines between the assignments with different indentation levels, or
* The same indentation level for each assignment

### Actual Behavior

* `cidr_block` more indented than `count` in the previous line, with no blank line separator
* `availability_zone` more indented than `cidr_block`, with no blank line separator

### Steps to Reproduce

* `terraform fmt modules/network/main.tf`

### Additional Context

None that I can think of.

### References

While also in `fmt` and similarly not prevented by tests, I'm not sure this is the same as either:

* #21434
* #20910

**Comment by apparentlymart** [comment] 2019-06-05 14:27
Hi @garthk,

This difference in behavior is intended: an argument whose expression uses some sort of bracket to split the expression over multiple lines is ignored for the purposes of aligning equals signs.

This is, like with all `terraform fmt` rules, a subjective and ultimately pretty arbitrary decision. We found through experimentation with various real-world configurations that this approach looks "better" in more cases, particularly in situations where the name of the argument that is multi-line-specified is _shorter_ than the preceding indentation level:

```hcl
  map_public_ip_on_launch = true
  cidr_block              = cidrsubnet(
    var.environment_cidr[var.environment],
    var.subnet_bits["public"] - 16,
    count.index + 128,
  )
```

We found that (subjectively) this seems to de-emphasize the `cidrsubnet(` portion and make it harder to see in scanning -- the eye seems drawn primarily to the indented portion. This decision was then confirmed by noting that `go fmt` makes a similar decision when deciding how to align struct fields.

Your example is a case where that readability concern doesn't apply, but the `terraform fmt` command prefers simple rules over complicated heuristics, and so it applies the same general rule of skipping equals alignment for any multi-line argument.

As I say, these things are of course subjective and no formatting decision is going to be everyone's favorite. We believe that a simple, consistent set of formatting rules is important, even though everyone has something they'd probably write a little differently if _they_ were responsible for formatting, and so we don't intent to change this rule.

We've seen that some authors (myself included) prefer to add blank lines around these multi-line arguments anyway, to make it easier to scan over them as a single unit, similar to how we'd treat a block declaration. The formatter doesn't currently do that itself because for the moment it is focused primarily on "horizontal" formatting, leaving vertical formatting largely up to the author. We may introduce formatting rules for vertical formatting in the future, but have no short-term plans to do so.

**Comment by apparentlymart** [comment] 2019-07-11 23:10
Hi again @garthk,

Re-visiting this issue a while later, it seems like this isn't tracking any specific work item for the Terraform team (since the current behavior is working as intended), and so I'm going to close it. Since there is no one "correct" answer to what `terraform fmt` should do, for the foreseeable future we're going to stick to reasonably simple rules that do not significantly alter the input but that help humans avoid tedious space-counting for manual alignment, since there is no behavior of this tool that will please everyone.

Thanks again for raising this!

**Closed by apparentlymart** 2019-07-11 23:10 UTC
