### ISSUE TITLE
DevOps azuredevops_variable_group behaviour for version 1.4 onwards

### ISSUE THREAD

**Issue by DKGreg** [hashicorp/terraform#33658] opened 2023-08-10 11:54 UTC
### Terraform Version

```shell
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/azure/azapi v0.1.1
+ provider registry.terraform.io/grafana/grafana v2.2.0
+ provider registry.terraform.io/hashicorp/azurerm v3.68.0
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/tfe v0.30.2
+ provider registry.terraform.io/microsoft/azuredevops v0.3.0
```

### Terraform Configuration Files

# versions.tf
```
terraform {
  required_version = ">=1.2.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.0.0"
    }
    azapi = {
      source = "azure/azapi"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = "0.3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.3.1"
    }
    tfe = {
      version = "~> 0.30.2"
    }
    grafana = {
      source  = "grafana/grafana"
      version = ">=1.21.0"
    }
  }
  cloud {}
}
```

### Debug Output

.

### Expected Behavior

Hello

Using terraform version 1.3.X or lower trying to create a resource "azuredevops_variable_group" it shows correctly the variable wanted to add but if the version is 1.4.X or greater it says [# At least one attribute in this block is (or was) sensitive,  # so its contents will not be displayed.] even if it's the first time creating the resource and it isn't a secret

Tested changing azuredevops to latest version and the behaviour is the same

```
  # module.projectinit.azuredevops_variable_group.general_variable_group will be created
  + resource "azuredevops_variable_group" "general_variable_group" {
      + allow_access = true
      + description  = "Global variables"
      + id           = (known after apply)
      + name         = "project-global-variables3"
      + project_id   = "XXXXXXXXXXXXXXXXXXXXXXXXX"

      + variable {
          + content_type = (known after apply)
          + enabled      = (known after apply)
          + expires      = (known after apply)
          + is_secret    = false
          + name         = "azdvEnvironmentStatus-dev"
          + value        = "true"
        }
```

### Actual Behavior

The variable dosen't show like in the expected behaviour
```
  # module.projectinit.azuredevops_variable_group.general_variable_group will be created
  + resource "azuredevops_variable_group" "general_variable_group" {
      + allow_access = true
      + description  = "Global variables"
      + id           = (known after apply)
      + name         = "project-global-variables"
      + project_id   = "XXXXXXXXXXXXXXXXXXXXXXXXX"

      + variable {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
```

### Steps to Reproduce

We use Azure DevOps pipelines TerraformCLI@0 tasks to launch terraform linked to Terraform Cloud

**Comment by jbardin** [comment] 2023-08-10 13:16
Duplicate of #33112

**Closed by jbardin** 2023-08-10 13:16 UTC
Labels: bug, new
