### ISSUE TITLE
"bufio.Scanner: token too long" when provider log contains long line

### ISSUE THREAD

**Issue by bentterp** [hashicorp/terraform#20325] opened 2019-02-13 09:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.0-dev (built from master, last commit Mon Feb 11 18:53:33 2019 -0800)
+ provider.azurerm v1.17.0-5-ga3b48ba3-dev (from the last alpha)

### Affected Resource(s)

N/A
* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
locals {
  prefix = "bugtest"
}
  
resource "azurerm_resource_group" "test" {
  name     = "${local.prefix}-rgp-test"
  location = var.region

  tags = {
    "name" = "${local.prefix}-rgp-test"
  }
}
```

### Debug Output
https://gist.github.com/bentterp/8fc08509ebb8329b004fc278c875e6eb
### Expected Behavior
A plan for creating a resource group

### Actual Behavior
The process freezes totally:
```sh
PS H:\Documents\azure_devops\folksamcloudcoe\bugtest> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...
Two interrupts received. Exiting immediately. Note that data
loss may have occurred.

Error: operation canceled


PS H:\Documents\azure_devops\folksamcloudcoe\bugtest>
```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by bentterp** [comment] 2019-02-13 09:33
Curioser and curioser, I went back and tested some older builds that used to work, but they generate the same error.

I can change the key and rerun terraform init and then terraform apply - a new statefile is created and locked (Leased as it is AzureRM backend) so it looks like my credentials are still valid at least.

**Comment by apparentlymart** [comment] 2019-02-13 17:32
Thanks for reporting this, @bentterp!

At first I thought this might be something related to hashicorp/terraform#20242 due to the similar symptom, but on closer inspection it seems to be the same problem in a different location.

Specifically, it looks like the `azurerm` provider plugin is generating a particularly-long line as part of its output, and then Terraform Core is trying to parse out the separate lines in the output to copy them into its own logs but is failing to do so because the line is too long to fit into the line buffer.

It makes sense that this would also affect other versions of Terraform because the problem is triggered by the dynamic output from the plugin, which was presumably not so long on previous runs due to different input.

Since the copying of logs from the provider stderr into Terraform's main log is a "best effort" debugging sort of thing, it's very unfortunate that a failure here would cause the whole run to halt. I think we should investigate whether we can make this more of a soft failure (e.g. write as much of the line as we were able to buffer and then continue the rest of the line as a separate log item).

That won't fix the behavior of this plugin in previous releases of Terraform though, so I think existing releases effectively mean that providers are blocked from producing long log lines if they are to be compatible with Terraform 0.10 and 0.11, and so perhaps we can also investigate having the SDK configure the Go logger in a special way where it will split long lines on the plugin side, thus allowing new releases of the provider to still work with older versions of Terraform that will always have the line length constraint.

**Comment by bentterp** [comment] 2019-02-14 08:19
Thank you @apparentlymart !

Meanwhile, do you have any suggestions for a workaround? Other than reverting to 0.11.x....
I'm working on a demo to show people here at work just how much better Terraform is than ARM templates, and of course the improved handling of maps are a big part of making it look good :-D

**Comment by apparentlymart** [comment] 2019-02-14 17:49
Unfortunately it looks like the long log line here is the AzureRM provider trying to log the body of an HTTP response, and thus the content of that is under the control of the Azure API servers and not Terraform itself. I'm not sure how to inspire it to be shorter.

However, your latest comment about reverting to 0.11 makes me question my understanding of your original message: when you said you "tested some old builds that used to work", were you talking about v0.12.0 builds? I was assuming you mean 0.11.x builds, but if not then that's better because it suggests that this new failure is a regression in v0.12.0 rather than a long-standing bug, and so we can hopefully fix it before v0.12.0 final release and avoid the backward-compatibility issues I was worried about in my previous comment.

I'm going to pre-emptively label this as a 0.12.0 issue now just so we don't lose it, but please let me know if my understanding above is correct, since it'll affect how we try to mitigate the problem here.

**Comment by bentterp** [comment] 2019-02-18 10:44
I've tried this with the 0.11.11 release and that worked fine - with both the 0.12-alpha4 release of the azurerm provider and the latest release of the provider 1.22.1.

But when I just try with the alpha4 release and the provider that is bundled with it , then the bug is back. 
So it seems to me to be a 0.12 bug

**Comment by bentterp** [comment] 2019-02-19 06:24
Had a "shower Eureka" moment this morning :-)
The error message is to be interpreted quite literally: "token too long":
```
~/.azure$ ls -go *json
-rw------- 1 18374 Feb 19 07:14 accessTokens.json
-rw-rw-rw- 1     5 Feb 15 08:22 az.json
-rw-rw-rw- 1 12574 Feb 19 07:14 azureProfile.json
~/.azure$ wc accessTokens.json azureProfile.json
    0   121 18374 accessTokens.json
    0   896 12574 azureProfile.json
    0  1017 30948 total
~/.azure$ az account list --all -o tsv | wc -l
46
~/.azure$
```

There was some reorganising of our AD and I ended up with access to lots more subscriptions, and **that** was when the problems started! Easy enough to see now, in retrospective.

**Comment by bentterp** [comment] 2019-02-19 13:07
Now I'm only in 2 subscriptions, but the problem persists

```
~$ ls -go .azure/*json
-rw------- 1 11024 Feb 19 14:03 .azure/accessTokens.json
-rw-rw-rw- 1     5 Feb 19 14:03 .azure/az.json
-rw-rw-rw- 1   618 Feb 19 14:03 .azure/azureProfile.json
~$ wc .azure/*json
    0    69 11024 .azure/accessTokens.json
    0     1     5 .azure/az.json
    0    43   618 .azure/azureProfile.json
    0   113 11647 total
~$ az account list -o tsv | wc -l
2
~$
```

**Comment by jbardin** [comment] 2019-02-19 22:15
This is a result of some changes to the go-plugin package, and partly dues to the transition to structured logging. 

The logs are sent over stderr, and the logging package expected structured messages to be line-delimited. The line length needs some sort of limit since we don't want to buffer output indefinitely, and the default max scan token size of 64k is sufficient for most use cases. 

We'll update go-plugin with a scanner that doesn't completely error out when it reaches MaxScanTokenSize.

**Closed** 2019-02-20 16:04 UTC
Labels: bug, dependencies, provider-sdk

**Comment by bentterp** [comment] 2019-02-25 07:42
Just a quick note to say that the unwanted behaviour is now gone with a new build so I confirm that this is fixed.
Thank you both @jbardin and @apparentlymart  🥇 indeed!
