### ISSUE TITLE
Terraform's apply graph builder

### ISSUE THREAD

**Issue by omarelsaid** [hashicorp/terraform#32049] opened 2022-10-20 15:27 UTC
### Terraform Version

```shell
Terraform v1.3.2
on darwin_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

N/A

### Expected Behavior

Changes get applied successfully.

### Actual Behavior

Changes got applied, but following was output also:

The graph node for aws_cloudwatch_event_target.lamdba-event-target-toggle-round has no configuration attached to it. This suggests a bug in Terraform's apply graph builder; please report it!

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

The graph node for aws_cloudwatch_event_target.lamdba-event-target-toggle-round has no configuration attached to it. This suggests a bug in Terraform's apply graph builder; please report it!

**Comment by jbardin** [comment] 2022-10-20 16:41
Duplicate of #31850

**Closed by jbardin** 2022-10-20 16:41 UTC
Labels: bug, new, duplicate
