### ISSUE TITLE
Provider fields not being set/read, despite being hard-coded or interpolated.

### ISSUE THREAD

**Issue by daytonpa** [hashicorp/terraform#18675] opened 2018-08-14 20:19 UTC
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.31.0
+ provider.cloudflare v1.2.0
```

##### `providers.tf`:
```
provider "aws" {
  access_key            = "${var.aws_access_key}"
  secret_key            = "${var.aws_secret_key}"
  region                = "us-east-1"
  allowed_account_ids   = ["123456789011"]
  alias                 = "us-east-1"
}
provider "aws" {
  access_key            = "${var.aws_access_key}"
  secret_key            = "${var.aws_secret_key}"
  region                = "us-west-1"
  allowed_account_ids   = ["123456789011"]
  alias                 = "us-west-1"
}
provider "cloudflare" {
  email                 = "${var.cloudflare_account["email"]}"
  token                 = "${var.cloudflare_account["token"]}"
  alias                 = "main"
}
```

##### `variables.tf`:
```
variable "aws_region" {
  default = "us-west-1"
}
variable "cloudflare_account" {
  type          = "map"
  description   = "Login credentials for our CloudFlare account"
  default = {
    "email"     = "terraform@company.org"
    "token"     = "big-ol-token"
  }
}
```

##### `terraform.tfvars`:
```
cloudflare_account = {
  "email"                     = "terraform@company.org"
  "token"                     = "big-ol-token"
}
```

### Expected Behavior
Everything should run.  All variable values are set, and some fields hard-coded.

### Actual Behavior

```
Starting build of new infrastructure...

Error: provider.aws: "region": required field is not set

Error: provider.cloudflare: "email": required field is not set

Error: provider.cloudflare: "token": required field is not set

There were issues creating infrastructure in us-west-1...
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -input=false -auto-approve -var-file=terraform.tfvars -var "aws_region=us-west-1"`

### Additional Context
Terraform is running inside of a custom bash script that exists in the same directory as all of my `.tf` files.  I have tried using older versions of provider plugins as well, but the same error appears.

#### Additional ADDITIONAL Context
I reinstalled Terraform and rebooted.  Same errors are occurring.

**Comment by jholloway7** [comment] 2019-08-21 19:05
Is this the same "documentation bug" described in #13789 due to all of your aws providers having aliases, but not specifying provider = "<alias>" on the resources?

**Comment by teamterraform** [comment] 2019-08-24 00:22
Hello,

This appears to be an issue with configuration not shown in this example, as the provided config on its own will validate correctly. This is likely a duplicate of #13789 as @jholloway7 suggested.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Closed by teamterraform** 2019-08-24 00:22 UTC
Labels: bug, config
