### ISSUE TITLE
Escaping dollar character with `$$` fails to avoid interpolation of `${BASH_VARIABLE}` in `template_file` resource

### ISSUE THREAD

**Issue by nhooey** [hashicorp/terraform#24616] opened 2020-04-09 15:54 UTC
### Terraform Version
```
Terraform v0.12.24
```

### Expected Behavior
There should be a way to escape any character in `${BASH_VARIABLE}` in a `template_file` to avoid erroneously referencing a template variable `BASH_VARIABLE`.

### Actual Behavior
All of the following escaping methods fail to avoid interpolating the variable:
1. `$${BASH_VARIABLE}`
2. `\${BASH_VARIABLE}`
3. `\$${BASH_VARIABLE}`

Renders a message like this or similar:
```
Error: failed to render : <template_file>:21,9-32: Unknown variable; There is no variable named "BASH_VARIABLE"
```

All of the following methods get interpreted literally:
1. `$\{BASH_VARIABLE\}`

### References
* #1942 Template variables and bash substitution/array
* Incorrect documentation: [Configuration Language > 0.12 and Newer > Expressions > String Literals](https://www.terraform.io/docs/configuration/expressions.html#string-literals)

**Comment by danieldreier** [comment] 2020-04-09 17:26
Hi @nhooey! I'm sorry you've been having frustrations with escaping in templates. We're currently recommending people use the `templatefile()` function rather than the older `template_file` resource, so I've tried to reproduce this using `templatefile`. Good news - I was able to get this escaping working the way the docs say. The [key bit](https://www.terraform.io/docs/configuration/expressions.html#string-literals) is:
```
To include these sequences literally without beginning a template sequence, double the leading character: $${ or %%{.
```

Here's my example showing it working:

`repro.tf`:
```terraform
resource "local_file" "example_file" {
    content     = templatefile("${path.module}/example.tmpl", {})
    filename = "/tmp/example.txt"
}
```

`example.tmpl`:
```
fizzbuzz
$${BASH_VARIABLE}
```

Output:
```shell
❯ terraform apply -auto-approve && cat /tmp/example.txt
local_file.example_file: Refreshing state... [id=7ab2461d54728d9b56ff24fb192d9d3b0aeba993]
local_file.example_file: Destroying... [id=7ab2461d54728d9b56ff24fb192d9d3b0aeba993]
local_file.example_file: Destruction complete after 0s
local_file.example_file: Creating...
local_file.example_file: Creation complete after 0s [id=a65a4e19985a75e411a02a71cabcb51095cb9270]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
fizzbuzz
${BASH_VARIABLE}
```

I'm going to close this because I'm fairly confident that this will resolve your issue, and that our documentation is accurate based on my own experimentation here. Please let me know or re-open this issue if I've misunderstood the issue you reported.

**Closed by danieldreier** 2020-04-09 17:26 UTC

**Comment by shmileee** [comment] 2020-04-27 00:09
`template_file` allows you to generate content inline, without necessity to create additional files and writing boilerplates. +1 for proper escaping and not using workaround.
