### ISSUE TITLE
aws_subnet: diffs didn't match during apply.

### ISSUE THREAD

**Issue by BlueDragonX** [hashicorp/terraform#13606] opened 2017-04-12 21:52 UTC
Hello. I'm receiving the error `Error applying plan ... diffs didn't match during apply` when attempting to execute changes for some `aws_subnet` resources.

`terraform plan` outputs:
```
~ aws_subnet.proxies.0
    tags.Name:    "ZD-UW2A-NET-FleetPublic" => "ZD-UW2A-NET-Proxies"
    tags.Network: "fleet-public" => "proxies"

~ aws_subnet.services.0
    tags.Name:    "ZD-UW2A-NET-FleetPrivate" => "ZD-UW2A-NET-Services"
    tags.Network: "fleet-private" => "services"
```

`terraform apply` outputs:
```
Error applying plan:

2 error(s) occurred:

* aws_subnet.services[0]: aws_subnet.services.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.9.2
    Resource ID: aws_subnet.services.0
    Mismatch reason: diff RequiresNew; old: false, new: true
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tags.Name":*terraform.ResourceAttrDiff{Old:"ZD-UW2A-NET-FleetPrivate", New:"ZD-UW2A-NET-Services", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Network":*terraform.ResourceAttrDiff{Old:"fleet-private", New:"services", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tags.Zone":*terraform.ResourceAttrDiff{Old:"", New:"us-west-2a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"", New:"ZD-UW2A-NET-Services", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "assign_ipv6_address_on_creation":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.ResourceAttrDiff{Old:"", New:"zd", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "map_public_ip_on_launch":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_id":*terraform.ResourceAttrDiff{Old:"", New:"vpc-b0c467d4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ipv6_cidr_block_association_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zone":*terraform.ResourceAttrDiff{Old:"", New:"us-west-2a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "cidr_block":*terraform.ResourceAttrDiff{Old:"", New:"10.48.208.0/24", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tags.Network":*terraform.ResourceAttrDiff{Old:"", New:"services", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_subnet.proxies[0]: aws_subnet.proxies.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.9.2
    Resource ID: aws_subnet.proxies.0
    Mismatch reason: diff RequiresNew; old: false, new: true
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"tags.Network":*terraform.ResourceAttrDiff{Old:"fleet-public", New:"proxies", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"ZD-UW2A-NET-FleetPublic", New:"ZD-UW2A-NET-Proxies", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"cidr_block":*terraform.ResourceAttrDiff{Old:"", New:"10.48.200.0/24", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"", New:"ZD-UW2A-NET-Proxies", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_id":*terraform.ResourceAttrDiff{Old:"", New:"vpc-b0c467d4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "availability_zone":*terraform.ResourceAttrDiff{Old:"", New:"us-west-2a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ipv6_cidr_block_association_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Environment":*terraform.ResourceAttrDiff{Old:"", New:"zd", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "map_public_ip_on_launch":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "assign_ipv6_address_on_creation":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Zone":*terraform.ResourceAttrDiff{Old:"", New:"us-west-2a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Network":*terraform.ResourceAttrDiff{Old:"", New:"proxies", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

The configuration which generates the above resources:
```
resource "aws_subnet" "services" {
    count = "${length(data.aws_availability_zones.all.names)}"
    vpc_id = "${aws_vpc.vpc.id}"
    cidr_block = "${cidrsubnet(aws_vpc.vpc.cidr_block, 8, 208+count.index)}"
    availability_zone = "${element(data.aws_availability_zones.all.names, count.index)}"

    tags {
        Name = "${module.zenreach.zone_prefix[element(data.aws_availability_zones.all.names, count.index)]}NET-Services"
        Environment = "${var.env}"
        Network = "services"
        Zone = "${element(data.aws_availability_zones.all.names, count.index)}"
    }
}

resource "aws_subnet" "proxies" {
    count = "${length(data.aws_availability_zones.all.names)}"
    vpc_id = "${aws_vpc.vpc.id}"
    cidr_block = "${cidrsubnet(aws_vpc.vpc.cidr_block, 8, 200+count.index)}"
    availability_zone = "${element(data.aws_availability_zones.all.names, count.index)}"
    map_public_ip_on_launch = true

    tags {
        Name = "${module.zenreach.zone_prefix[element(data.aws_availability_zones.all.names, count.index)]}NET-Proxies"
        Environment = "${var.env}"
        Network = "proxies"
        Zone = "${element(data.aws_availability_zones.all.names, count.index)}"
    }
}
```

Current state of those resources:
```
"aws_subnet.services": {
    "type": "aws_subnet",
    "depends_on": [],
    "primary": {
        "id": "subnet-ee854698",
        "attributes": {
            "assign_ipv6_address_on_creation": "false",
            "availability_zone": "us-west-2a",
            "cidr_block": "10.48.208.0/24",
            "id": "subnet-ee854698",
            "map_public_ip_on_launch": "false",
            "tags.%": "4",
            "tags.Environment": "zd",
            "tags.Name": "ZD-UW2A-NET-FleetPrivate",
            "tags.Network": "fleet-private",
            "tags.Zone": "us-west-2a",
            "vpc_id": "vpc-b0c467d4"
        },
        "meta": {},
        "tainted": false
    },
    "deposed": [],
    "provider": "aws"
},
"aws_subnet.services.1": {
    "type": "aws_subnet",
    "depends_on": [],
    "primary": {
        "id": "subnet-02c66866",
        "attributes": {
            "assign_ipv6_address_on_creation": "false",
            "availability_zone": "us-west-2b",
            "cidr_block": "10.48.209.0/24",
            "id": "subnet-02c66866",
            "map_public_ip_on_launch": "false",
            "tags.%": "4",
            "tags.Environment": "zd",
            "tags.Name": "ZD-UW2B-NET-Services",
            "tags.Network": "services",
            "tags.Zone": "us-west-2b",
            "vpc_id": "vpc-b0c467d4"
        },
        "meta": {},
        "tainted": false
    },
    "deposed": [],
    "provider": "aws"
},
"aws_subnet.services.2": {
    "type": "aws_subnet",
    "depends_on": [],
    "primary": {
        "id": "subnet-7f332126",
        "attributes": {
            "assign_ipv6_address_on_creation": "false",
            "availability_zone": "us-west-2c",
            "cidr_block": "10.48.210.0/24",
            "id": "subnet-7f332126",
            "map_public_ip_on_launch": "false",
            "tags.%": "4",
            "tags.Environment": "zd",
            "tags.Name": "ZD-UW2C-NET-Services",
            "tags.Network": "services",
            "tags.Zone": "us-west-2c",
            "vpc_id": "vpc-b0c467d4"
        },
        "meta": {},
        "tainted": false
    },
    "deposed": [],
    "provider": "aws"
},
"aws_subnet.proxies": {
    "type": "aws_subnet",
    "depends_on": [],
    "primary": {
        "id": "subnet-e1854697",
        "attributes": {
            "assign_ipv6_address_on_creation": "false",
            "availability_zone": "us-west-2a",
            "cidr_block": "10.48.200.0/24",
            "id": "subnet-e1854697",
            "map_public_ip_on_launch": "true",
            "tags.%": "4",
            "tags.Environment": "zd",
            "tags.Name": "ZD-UW2A-NET-FleetPublic",
            "tags.Network": "fleet-public",
            "tags.Zone": "us-west-2a",
            "vpc_id": "vpc-b0c467d4"
        },
        "meta": {},
        "tainted": false
    },
    "deposed": [],
    "provider": "aws"
},
"aws_subnet.proxies.1": {
    "type": "aws_subnet",
    "depends_on": [
        "aws_vpc.vpc",
        "aws_vpc.vpc",
        "data.aws_availability_zones.all",
        "data.aws_availability_zones.all",
        "module.zenreach"
    ],
    "primary": {
        "id": "subnet-01c66865",
        "attributes": {
            "assign_ipv6_address_on_creation": "false",
            "availability_zone": "us-west-2b",
            "cidr_block": "10.48.201.0/24",
            "id": "subnet-01c66865",
            "map_public_ip_on_launch": "true",
            "tags.%": "4",
            "tags.Environment": "zd",
            "tags.Name": "ZD-UW2B-NET-Proxies",
            "tags.Network": "proxies",
            "tags.Zone": "us-west-2b",
            "vpc_id": "vpc-b0c467d4"
        },
        "meta": {},
        "tainted": false
    },
    "deposed": [],
    "provider": ""
},
"aws_subnet.proxies.2": {
    "type": "aws_subnet",
    "depends_on": [
        "aws_vpc.vpc",
        "aws_vpc.vpc",
        "data.aws_availability_zones.all",
        "data.aws_availability_zones.all",
        "module.zenreach"
    ],
    "primary": {
        "id": "subnet-7c332125",
        "attributes": {
            "assign_ipv6_address_on_creation": "false",
            "availability_zone": "us-west-2c",
            "cidr_block": "10.48.202.0/24",
            "id": "subnet-7c332125",
            "map_public_ip_on_launch": "true",
            "tags.%": "4",
            "tags.Environment": "zd",
            "tags.Name": "ZD-UW2C-NET-Proxies",
            "tags.Network": "proxies",
            "tags.Zone": "us-west-2c",
            "vpc_id": "vpc-b0c467d4"
        },
        "meta": {},
        "tainted": false
    },
    "deposed": [],
    "provider": ""
},
```

These resource did already exist in AWS. I imported them using `terraform import` and wrote the appropriate configuration. As you can see I'm using `count`. Only the first (`count.index == 0`) resource causes this error. The changes were successfully applied to the other resources (`count.index > 0`).

**Comment by jbardin** [comment] 2017-04-26 02:25
Hi @BlueDragonX,

Thanks for the detailed bug report!

I have a local reproduction here, and confirmed that it's not fixed by a similar issue in the upcoming release.

If you need an immediate workaround, the underlying issue seems to be that the Name tag value is forcing the subnet to be "computed", and hard-coding the value should work.

**Comment by jbardin** [comment] 2017-04-27 03:19
ok, I didn't get to a solution today, but put together a much smaller reproduction case, and a path to investigate.

After applying the config,

```
data "aws_availability_zones" "all" {}

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "services" {
	count = "${length(data.aws_availability_zones.all.names)}"
	vpc_id = "${aws_vpc.vpc.id}"
	cidr_block = "${cidrsubnet(aws_vpc.vpc.cidr_block, 8, 100+count.index)}"
	availability_zone = "${element(data.aws_availability_zones.all.names, count.index)}"
}
```

adding a single static tag value to the subnet will cause the same diff mismatch (hopefully for the same reason). 

The culprit is the computed count value; with a pre-defined count the previous procedure succeeds.

**Comment by jbardin** [comment] 2017-04-27 15:36
I see now that this is only happening around the `[0]` indexes, and we just merged a change that will have plan handle the 0 index boundary the same as apply. 

This should be fixed in the next release.

Thanks again for the detailed issue!

**Closed by jbardin** 2017-04-27 15:36 UTC
Labels: bug, core
