### ISSUE TITLE
lock for consul backend not clearing as expected

### ISSUE THREAD

**Issue by domofactor** [hashicorp/terraform#13445] opened 2017-04-07 03:56 UTC
### Terraform Version
0.9.2

### Affected Resource(s)
Consul Backend

### Terraform Configuration Files
```hcl
{
  "terraform": {
    "backend": {
      "consul": {}
    }
  }
}
```

### Expected Behavior
I was expecting the .lock file in consul to be cleared after a successful `terraform plan` or `terraform  apply`.

### Actual Behavior
the lock for that specific path in consul, and thus the .lock file sticks around even after a successful `terraform plan` or `terraform apply`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init -backend-config=path=<path to key> -backend-config=address=<my-consul-cluster>`
2. `terraform plan`
3. Empty state file and .lock is written to Consul
4. `terraform apply`
5. state file is written to Consul, and .lock file still exists

### References
I think somebody also posted about this over in the [Terraform Google group](https://groups.google.com/forum/#!topic/terraform-tool/s4ATUHZUwiE)

**Comment by apparentlymart** [comment] 2017-04-07 16:44
Hi @domofactor! Sorry for the Consul detritus here, and thanks for reporting this.

I think this is the same issue that @jbardin was aiming to fix with #13430, and this fix should be included in the next release of Terraform that will be released soon.

**Closed by apparentlymart** 2017-04-07 16:44 UTC
Labels: bug, state/remote/consul

**Comment by domofactor** [comment] 2017-04-12 03:01
thanks @apparentlymart, i'll wait for that release then. :)

**Comment by curratore** [comment] 2017-04-19 14:59
Hello, 
I think that I have the same issue 

### Terraform version

0.9.3

### Terraform configuration files

```
terraform {
  backend "consul" {
    address = "consul.backend"
    path    = "tfstate/tfstate-test.tfstate"
    lock    = true
  }
}
```
### Expected behavior
I was expecting the .lock file in consul to be cleared after a successful terraform apply.

### Actual behavior
There are 2 files on KV, `.lock` and `.lockinfo`

```
Apply complete! Resources: 42 added, 0 changed, 0 destroyed.

Error releasing the state lock!
Error message: consul lock was lost
```

### Steps to reproduce
- `terraform init` Getting the values from environment variables.
- `terraform apply` Launching the apply creating `tfstate-test.tfstate` file and `.lock` and `.lockinfo`  and finishing the apply successfully but with the releasing error.
- Check the consul backend and finding `tfstate-test.tfstate`, `.lock`and `.lockinfo` 

### References 
[Terraform Google Group](https://groups.google.com/forum/#!topic/terraform-tool/s4ATUHZUwiE)
[#13430](https://github.com/hashicorp/terraform/pull/13430)

**Comment by jbardin** [comment] 2017-04-19 18:43
@curratore 

I'm not sure what's going on, but your issue doesn't seem related. 
The error message: `Error message: consul lock was lost` is of concern here, since that means the consul client no longer had a lock at the time it was released (which is why the cleanup wasn't done).

Can you open a new issue with any info you may have on how to reproduce this?
Thanks!
