### ISSUE TITLE
Terraform will destroy all host group volume attachment when using “-target” and “for_each”

### ISSUE THREAD

**Issue by AlexandreGaltierKadiska** [hashicorp/terraform#32098] opened 2022-10-27 10:47 UTC
### Terraform Version

```shell
Terraform v1.3.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/time v0.9.0
+ provider registry.terraform.io/ovh/ovh v0.22.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.49.0
```

### Terraform Configuration Files

```terraform
vms = { 0: { name = vm0 },
        1: { name = vm1 },
        2: { name = vm2 },}
## VM ##
resource "openstack_compute_instance_v2" "vm_instance" {
  for_each = var.vms
  provider = openstack.ovh
  name = "vm_${each.value.name}"
  image_name = "debian"
  flavor_name = "s1-2"
}

## VOLUMES ##
resource "openstack_blockstorage_volume_v3" "vm_volume" {
  for_each = var.vms
  provider = openstack.ovh
  name = "vm_${each.value.name}_volume"
  size = 10
  volume_type = "classic"
}

# ## ATTACH VOLUMES ##
resource "openstack_compute_volume_attach_v2" "vm_attach" {
  for_each = var.vms
  provider = openstack.ovh
  instance_id = openstack_compute_instance_v2.vm[each.key].id
  volume_id   = openstack_blockstorage_volume_v3.vm_volume[each.key].id
}
```

### Debug Output

```sh
❯ terraform apply -destroy -target='openstack_compute_instance_v2.vm_instance["2"]'
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # openstack_compute_instance_v2.vm_instance["2"] will be destroyed
  - resource "openstack_compute_instance_v2" "vm_instance" {
[...]
      - id                  = "wxc" -> null
[...]
      - name                = "vm_vm2" -> null
   }

  # openstack_compute_volume_attach_v2.vm_attach["0"] will be destroyed
  - resource "openstack_compute_volume_attach_v2" "vm_attach" {
[...]
    }

  # openstack_compute_volume_attach_v2.vm_attach["1"] will be destroyed
  - resource "openstack_compute_volume_attach_v2" "vm_attach" {
[...]
    }

  # openstack_compute_volume_attach_v2.vm_attach["2"] will be destroyed
  - resource "openstack_compute_volume_attach_v2" "vm_attach" {
      - device      = "/dev/sdb" -> null
      - id          = "wxc/*********" -> null
      - instance_id = "wxc" -> null
      - region      = "****" -> null
      - volume_id   = "********" -> null
    }

Plan: 0 to add, 0 to change, 4 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
```

### Expected Behavior

Only destroy attachment of targeted instance ressource 

like 

```sh
❯ terraform apply -destroy -target='openstack_compute_instance_v2.vm_instance["2"]'
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # openstack_compute_instance_v2.vm_instance["2"] will be destroyed
  - resource "openstack_compute_instance_v2" "vm_instance" {
[...]
      - id                  = "wxc" -> null
[...]
      - name                = "vm_vm2" -> null
   }

  # openstack_compute_volume_attach_v2.vm_attach["2"] will be destroyed
  - resource "openstack_compute_volume_attach_v2" "vm_attach" {
      - device      = "/dev/sdb" -> null
      - id          = "wxc/*********" -> null
      - instance_id = "wxc" -> null
      - region      = "****" -> null
      - volume_id   = "********" -> null
    }

Plan: 0 to add, 0 to change, 4 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
```

### Actual Behavior

Destroy all attachment of my for_each group

### Steps to Reproduce

1. terraform init -upgrade
2. terraform apply
3. terraform apply -destroy -target='openstack_compute_instance_v2.vm_instance["2"]'

### References

- #29116
- #22631

**Comment by jbardin** [comment] 2022-10-27 12:56
Thanks @AlexandreGaltierKadiska!

We are tracking this in #25836

Duplicate of #25836

**Closed by jbardin** 2022-10-27 12:56 UTC
Labels: bug, new
