### ISSUE TITLE
Chef cookbook does not run completely from a runList in tfvars file with the error http response error: 401 - invalid content type

### ISSUE THREAD

**Issue by jeremytanyz** [hashicorp/terraform#27961] opened 2021-03-03 04:46 UTC
### Terraform Version

```
...
Terraform v0.12.26
+ provider.azurerm v2.20.0
+ provider.null v3.0.0

```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
Terraform a VM and running my chef cookbooks successfully from a runlist defined in the tfvars file

### Actual Behavior
Able to terraform a VM but the running of my cookbook will run and stop halfway with the following error 
Error: error executing "cmd /c chef-client -j \"C:/chef/first-boot.json\" -E \"_default\"": http response error: 401 - invalid content type

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
In general the following steps are how one can reproduce the issue
1. Create a chef cookbook with 2 recipes.
The 1st recipe will 
- Mount an azure fileshare to copy files to the VM
- Execute CIS OS hardening script(CIS Microsoft Windows Server 2019 RTM (Release 1809) Benchmark) --> I am running MS-L1 and User-L1

The 2nd recipe will 
- Change some rules in the Group Policy through secedit 

The rules that are changed is 
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\LegalNoticeCaption
MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\LegalNoticeText
SeDenyNetworkLogonRight
SeDenyRemoteInteractiveLogonRight

2. Terraform a VM (windows 2019) with a chef provisioner and the following cookbook defined in the runlist defined in the tfvars via terraform apply

### Additional Context
VM gets terraformed but the running of cookbooks is will only run halfway. Where it will display the following error 
Error: error executing "cmd /c chef-client -j \"C:/chef/first-boot.json\" -E \"_default\"": http response error: 401 - invalid content type

I am able to run the same exact cookbook to the provisioned VM successfully if I run it from a chef workstation instead of from defining it in a runlist in the tfvars.

**Comment by pselle** [comment] 2021-03-08 20:15
Hi @jeremytanyz,

Could you provide some more reproduction information w.r.t. the error/trouble you're having?

> Error: error executing "cmd /c chef-client -j "C:/chef/first-boot.json" -E "_default"": http response error: 401 - invalid content type

This error alone is not enough information to help us find out if Terraform is the source of the issue. Could you provide a simplified configuration and some reproduction steps, as well as the full error message you're encountering?

**Comment by pselle** [comment] 2021-03-09 15:06
@jeremytanyz I'm reading a few things in your post, please correct me if I have not understood:

- You are using the chef provisioner
- On windows

The chef provisioner was deprecated and has been removed from future versions of Terraform -- it (and other vendor-specific provisioners) were unmaintained for a long while, and the actions. [Chef has a provider that is one of the recommended ways to use Chef+Terraform together](https://docs.chef.io/terraform/#chef-infra-provider).

Please let me know if I've misunderstood what you've described, and you believe it to be a bug in Terraform. If you want to find more help with the issue you have, I suggest leveraging the [community resources](https://discuss.hashicorp.com/c/terraform-core/27).

**Comment by jeremytanyz** [comment] 2021-03-10 01:59
> @jeremytanyz I'm reading a few things in your post, please correct me if I have not understood:
> 
> * You are using the chef provisioner
> * On windows
> 
> The chef provisioner was deprecated and has been removed from future versions of Terraform -- it (and other vendor-specific provisioners) were unmaintained for a long while, and the provider model provides much more reliable creation of infrastructure. [Chef has a provider that is one of the recommended ways to use Chef+Terraform together](https://docs.chef.io/terraform/#chef-infra-provider).
> 
> Please let me know if I've misunderstood what you've described, and you believe it to be a bug in Terraform. If you want to find more help with the issue you have, I suggest leveraging the [community resources](https://discuss.hashicorp.com/c/terraform-core/27).


@pselle 
To my understanding,
1) I am using a chef provisioner (below is a snippet) of a resource that is defined in the main.tf

resource "null_resource" "chef" {
  depends_on = [azurerm_virtual_machine.execute]
  provisioner "chef" {


2) The VM that I am attempting to terraform is a windows 2019 VM. I am running my terraform from a ubuntu machine.

I am not sure if the bug is coming for terraform or not. But as terraform is providing integration with chef via chef providers at least in this version of terraform that I am using and 

1) There is no indication of what is throwing the error (ie terraform?)
2) The same cookbook I am able to run successfully through a chef workstation to a successfully terraformed VM
3) This issue only occurs if I were to run the cookbook through terraform via the chef provisioner 

I am more inclined to think that the point of failure is more towards the terraform integration with chef

**Comment by danieldreier** [comment] 2021-03-10 15:56
Hi @jeremytanyz - I'm the engineering manager for this team. You are absolutely right that the experience here isn't great, and the error messaging isn't great. I haven't reproduced this issue, but I wouldn't be surprised if you're right and this is a bug in the Chef provisioner. 

This is exactly the type of issue that prompted us to remove the Chef provisioner from Terraform 0.15: we have tried, and have not been able to deliver a consistent, high-quality experience in vendor-specific provisioners. The integration surface area is simply too big and complex, and continuing to leave them in set people up to encounter hard-to-troubleshoot issues like this. 

I'm going to close this issue because we have decided that switching away from vendor-specific provisioning approaches is the best way to provide a good user experience, and so we're not going to continue working on known issues in vendor-specific provisioners that we decided to remove.

You should switch to an approach to running Chef that does not rely on the Chef provisioner. If you can, I encourage you to use CloudInit to Chef to run when the machine boots in the first place (and maybe bake Chef into the image using Packer to avoid installing it at boot time), or use the remote-exec provisioner if you have to run it via Terraform. There are [provisioning tutorials on learn](https://learn.hashicorp.com/collections/terraform/provision?utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS.) As we say in the docs, [provisioners are a last resort](https://www.terraform.io/docs/language/resources/provisioners/syntax.html).

If you absolutely do need to continue using the Chef provisioner, you could extract it from the Terraform codebase, fix this issue, and repackage it as a plugin. This is work you'd need to do on your end, but we will continue supporting plugin provisioners for some time.

**Closed by danieldreier** 2021-03-10 15:56 UTC
Labels: bug, provisioner/chef, v0.12, waiting for reproduction, windows

**Comment by jeremytanyz** [comment] 2021-03-11 05:43
@danieldreier

Noted. 
May explore some of the work around that you have suggested. Thanks
