### ISSUE TITLE
Declare a variable with a resource type

### ISSUE THREAD

**Issue by jfirebaugh** [hashicorp/terraform#25466] opened 2020-07-02 16:21 UTC
### Current Terraform Version
```
0.12.28
```

### Use-cases

I have a module which needs to accept a variable whose value is a resource, in order to use that resource in a `depends_on` list:

```hcl
variable "dependency" {
  type = ??
}

resource "module_resource" "name" {
  ...
  depends_on = [var.dependency]
}
```

I'd like to supply a `type` for this variable, to ensure it is passed correctly. But there is currently no ability to declare that a variable must be a resource of a certain type.

### Proposal

```
variable "dependency" {
  type = resource_type // e.g. aws_instance
}
```

**Comment by apparentlymart** [comment] 2020-07-06 16:43
Thanks for sharing this use-case, @jfirebaugh!

Our current model is intended to create only a _loose_ coupling between a variable type and a resource type, so that a module can accept either a resource object _or_ a manually-constructed object containing the subset of the object type attributes that the module actually needs.

For example, if you have a module that works with an `aws_instance` then it's unlikely that you depend on the _whole_ of the `aws_instance` object. Maybe your specific module will only use the `id`, `arn` and `private_ip` attributes, in which case you can define a type constraint like this:

```hcl
variable "instance" {
  type = object({
    id         = string
    arn        = string
    private_ip = string
  })
}
```

Now the calling module can choose whether to assign an `aws_instance` object it created or to construct a synthetic object that contains the same information, perhaps obtained from a configuration store like AWS SSM Parameter Store:

```hcl
resource "aws_instance" "example" {
  # ...
}

module "example" {
  source = "./modules/example"

  instance = aws_instance.example
}
```

```hcl
data "aws_ssm_parameter" "example" {
  name = "instance_elsewhere"
}

module "example" {
  source = "./modules/example"

  instance = jsondecode(data.aws_ssm_parameter.example.value)
}
```

Providers also tend to define their data sources to be partially compatible with their resource types when practical, in which case you can use a data resource object in the same way as a managed resource object as long as the module only depends on the common subset of attributes:

```hcl
variable "aws_instance_id" {
  type = string
}

data "aws_instance" "example" {
  instance_id = var.instance_id
}

module "example" {
  source = "./modules/example"

  instance = data.aws_instance.example
}
```

We chose not to allow modules to use resource types directly as type constraints in order to allow this sort of flexibility: most resource types have quite complex schemas and most modules only use a small part of a given resource type schema, so by having a module developer be intentional in selecting which subset of the schema the module needs we can better support [dependency inversion](https://www.terraform.io/docs/modules/composition.html#dependency-inversion) techniques.

With that said, I'd be interested to hear if you've encountered situations where the above design assumptions don't hold. For example, if you've found a need to write a module that _does_ depend on the entire schema of a particular resource type, or at least a very large portion of it.

---

A compromise we might consider is a tool to generate a type constraint that is equivalent to a particular resource type which you could then copy-paste into your module and remove the parts you don't need, which might make it less onerous to correctly reproduce the subset of the schema you are interested in but still meet the flexibility goal.

Although it was relatively easy to write a schema for the above subset of `aws_instance` which consists only of a small number of string attributes, it can be harder to figure out what types are appropriate for some more complex situations, particularly when the module needs information from a list or set of nested blocks.

Technically there's enough functionality in Terraform CLI to support implementing a tool like this in a separate program outside of Terraform -- it could run `terraform providers schema` to find the schema and then only be responsible for formatting the result as a Terraform language type constraint -- but if such an external tool were successful and commonly used then we could consider bringing the functionality into the main Terraform CLI too, perhaps as a suite of other commands that deal with code generation.

**Comment by jfirebaugh** [comment] 2020-07-13 18:13
> I'd be interested to hear if you've encountered situations where the above design assumptions don't hold. For example, if you've found a need to write a module that does depend on the entire schema of a particular resource type, or at least a very large portion of it.

Yes, a module which needs to `depends_on` an externally-supplied resource. AFAICT, that can't be done via accepting a "resource-alike" object with a subset of the properties. A data resource object won't work either: because the very purpose of `depends_on` is to ensure the right construction order, the module cannot assume the existence of the resource in question at the time the data resource object would be constructed.

**Comment by apparentlymart** [comment] 2020-07-14 22:06
Hi @jfirebaugh,

Ahh, with that clarification I now understand your original example better. Thanks!

When I've shared that technique of having variables that are used only for transitive dependencies I've typically just shown it with `type = any` because that means it can accept anything that `depends_on` might normally accept, which isn't necessarily a specific resource type:

```hcl
variable "example_depends_on" {
  type = any
}

resource "example" "example" {
  depends_on = [var.example_depends_on]
}
```

In your original example you proposed using `aws_instance` in particular, which I suppose might look like this:

```hcl
variable "example_depends_on" {
  type = aws_instance
}
```

...but in that case, I'm not really sure why you'd want to constrain it to be `aws_instance` in particular, if the child module only cares about this as a means of passing dependencies. If the module isn't accessing any of the attributes of the object, and if the intent is for the caller to be able to specify additional dependencies, what would be the reason to constrain it to be only a single `aws_instance` object?

**Comment by jfirebaugh** [comment] 2020-07-17 17:03
In my case, the variable does in fact need to be a resource of a particular type, specifically `aws_lb`. The module is creating an `aws_ecs_service`, which does use directly use any attributes of the `aws_lb`, but which will fail to be created if the load balancer does not exist (this is something that's enforced by the underlying AWS API). So I would like to constrain the type in order to enforce a requirement that the module relies on. Isn't this exactly the purpose of types?

**Comment by apparentlymart** [comment] 2020-07-22 22:50
Hi @jfirebaugh,

I'm not very familiar with ECS and ALB so I had to study up a bit to understand what you mean, and I just wanted to state my understanding in the hope that you can confirm I'm understanding the use-case correctly:

For an application load balancer we have both the load balancer itself and one or more target groups. The target groups don't directly depend on the load balancer, but are instead connected together after the fact by a "listener", `aws_lb_listener`, which depends on both a load balancer and one or more target groups.

However, ECS (when using an ALB, rather than an ELB) takes a target group ID and has a hidden requirement, enforced on the server side, that the target group must already be associated with a load balancer (indirectly via a listener) before it will be accepted as valid by the ECS API.

The upshot of that is that from Terraform's perspective the ECS service appears to only depend on the target group, but the ECS service actually also has a hidden dependency on the listener. Therefore you want to give the caller a way to pass in the dependency on the listener so that your module can declare the hidden dependency with `depends_on` and thus ensure that the target group is already associated with a load balancer before trying to register the ECS service.

You then, further, want to use Terraform's type system to enforce that the dependency is on a load balancer listener in particular, rather than allowing a dependency on anything at all.

Does that seems like a good representation of the use-case?

**Comment by pbzdyl** [comment] 2020-10-02 12:45
> Thanks for sharing this use-case, @jfirebaugh!
> 
> Our current model is intended to create only a _loose_ coupling between a variable type and a resource type, so that a module can accept either a resource object _or_ a manually-constructed object containing the subset of the object type attributes that the module actually needs.
> 
> For example, if you have a module that works with an `aws_instance` then it's unlikely that you depend on the _whole_ of the `aws_instance` object. Maybe your specific module will only use the `id`, `arn` and `private_ip` attributes, in which case you can define a type constraint like this:
> 
> ```terraform
> variable "instance" {
>   type = object({
>     id         = string
>     arn        = string
>     private_ip = string
>   })
> }
> ```
> 
> Now the calling module can choose whether to assign an `aws_instance` object it created or to construct a synthetic object that contains the same information, perhaps obtained from a configuration store like AWS SSM Parameter Store:
> 
> ```terraform
> resource "aws_instance" "example" {
>   # ...
> }
> 
> module "example" {
>   source = "./modules/example"
> 
>   instance = aws_instance.example
> }
> ```
> 

Thank you @apparentlymart, I wasn't aware it is possible to pass whole resource objects to variables that expect objects with fewer attributes. I really think this should be part of the documentation. Would it be possible to include the above in the documentation?

**Comment by apparentlymart** [comment] 2020-10-02 16:23
Hi @pbzdyl!

This type conversion rule is documented in the [Conversion of Complex Types](https://www.terraform.io/docs/configuration/types.html#conversion-of-complex-types) section of the type constraints page. We could certainly consider mentioning it in other locations, though. Do you recall where in the documentation you looked when you were trying to learn about this?

**Comment by pbzdyl** [comment] 2020-10-02 17:56
Hi @apparentlymart. I was mainly looking into the [Modules](https://www.terraform.io/docs/configuration/modules.html) and [Creating Modules](https://www.terraform.io/docs/modules/index.html) documentation and I'm not sure how I missed the section you have linked. It seems I wasn't careful enough to go check other top level sections like the Type Constraints you have linked and it clearly states:

> A map (or a larger object) can be converted to an object if it has at least the keys required by the object schema.

Thank you for the pointer!

**Comment by LouieMiddleHawkeye** [comment] 2022-01-26 11:36
Hi @apparentlymart 

> Therefore you want to give the caller a way to pass in the dependency on the listener so that your module can declare the hidden dependency with depends_on and thus ensure that the target group is already associated with a load balancer before trying to register the ECS service.

Thanks for all the info you've given so far. The use case you describe here is exactly one I have right now. I keep getting this error on my deployments `the target group with targetGroupArn does not have an associated load balancer.` 

I have a share terraform modules repository that I then use in various deployments. I create an ALB module and modules for each of my ecs services. For services that need to be public facing I add a load balancer target group. 

I've tried to add a dependency to the load balancer target group resource on the load balancer. When creating my load balancer target group I pass in the load balancer as an input variable with type `any`. Terraform then throws this error `References in depends_on must be to a whole object (resource, etc), not to an attribute of an object.`

I figured using type `any` would allow this, but I might've mistaken something? Any help would be appreciated :)

**Comment by crw** [comment] 2022-01-27 00:00
Hi @LouieMiddleHawkeye, thanks for your question! Although it is related to the previous discussion, can you please open this as a forum discussion at https://discuss.hashicorp.com/? I would suggest in the [AWS](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) category, as this question seems to be less about Terraform's core implementation and more around the details of the AWS provider. 

I am also closing this issue, as I believe we provided satisfactory work-arounds for the original issue use case. Please comment if this is not the case.

**Closed by crw** 2022-01-27 00:00 UTC
Labels: enhancement, config
