### ISSUE TITLE
azurerm_automation_module failing - unexpected state 'Failed', wanted target 'Succeeded'. last error: %!s(<nil>

### ISSUE THREAD

**Issue by mansing2** [hashicorp/terraform#24872] opened 2020-05-06 09:00 UTC
### Terraform Version
```
Terraform v0.11.14
+ provider.azuread v0.8.0
+ provider.azurerm v1.44.0
+ provider.null v2.1.1
+ provider.template v2.1.1
```

### Terraform Configuration Files
```
resource "azurerm_automation_module" "Azure" {
  name                    = "Azure"
  resource_group_name     = "${module.apprg.resource_group_name}"
  automation_account_name = "${var.automation_account_name}"

  module_link {
    uri = "https://www.powershellgallery.com/api/v2/package/Azure/5.3.0"
  }
}
```
### Crash Output

1 error occurred:
        * azurerm_automation_module.AzureRMResources: 1 error occurred:
        * azurerm_automation_module.AzureRMResources: Error waiting for Module "AzureRM.Resources" (Automation Account "ama-use-test" / Resource Group "RGP-TEST") to finish provisioning: unexpected state 'Failed', wanted target 'Succeeded'. last error: %!s(<nil>)

### Expected Behavior
Ideally should create a module under the said automation account.

### Actual Behavior

Getting an error on terraform apply, we tried with the different module link and the same error occurs. 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by danieldreier** [comment] 2020-05-08 01:26
We are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. We're actively working on Terraform 0.13. I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now.

This looks like it's probably an issue related to the AzureRM provider, but I'm hesitant to refer it over to them because we no longer support terraform 0.11. Can you please try and reproduce this on 0.12.24?

**Comment by mansing2** [comment] 2020-05-13 05:09
@danieldreier - Thanks for the response. We have no immediate plan to go for 0.12 so I wanted to check if any workaround.

**Comment by danieldreier** [comment] 2020-05-18 23:35
@mansing2 I really can't help with an 0.11 issue at this point. You may be able to get answers from other 0.11 AzureRM users at [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers).

I'm going to close this because we're no longer supporting 0.11. I hope you're able to upgrade soon - we have 0.13 right around the corner.

**Closed by danieldreier** 2020-05-18 23:35 UTC

**Comment by mansing2** [comment] 2020-05-19 08:55
ok. Thank you.
