### ISSUE TITLE
Consul lock lost with tf 0.10.2

### ISSUE THREAD

**Issue by jantman** [hashicorp/terraform#16098] opened 2017-09-14 14:30 UTC
With terraform 0.10.2, we're still experiencing the "consul lock was lost" errors.

### Terraform Version

``0.10.2``

### Terraform Configuration Files

Many, but can reproduce this with many, many different terraform projects. The common factor seems to be AWS API call time... the longer a terraform run takes, the more likely it is for this error to happen.

I'm working on trying to come up with a reliable way of reproducing this, and will update when I find one.

### Debug Output

So far we've been unable to obtain this; our production Terraform projects (wrapped in Rake, running in Jenkins) don't have a way to set TF_LOG, and we've experienced hanging jobs when we set it to TRACE.

### Expected Behavior

Consul lock would be released normally, and run would be successful.

### Actual Behavior

Run failed with an error about consul lock not being released. Outputs were never shown. Worse, on some TF versions, the statefile was never updated.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

* Consul 0.8.3 cluster in AWS, behind ELB with idle_timeout set to "90" (seconds).
* Tried to get Consul debug logs as [recommended in 14312](https://github.com/hashicorp/terraform/issues/14312#issuecomment-327251534); used `consul monitor -log-level=DEBUG` but I don't see anything that looks relevant...

### References

- #15545
- #14312 
- #13445

**Comment by jbardin** [comment] 2017-09-15 13:34
Hi @jantman,

Sorry you're still encountering this. There's not much I can do without at least the log output, so please update this when you can.

The root cause for the known cases of this is the consul network connection being closed. This is usually caused by running consul behind a network load balancer or proxy that times out the blocking lock requests. To work around this configuration, Terraform immediately starts retrying the lock with the existing session, and if that fails it creates a new session and tries to re-create the lock. There's obviously small windows in that scenario, even when it's going to success, where the connection could be gone at the moment the execution ends and the lock is being released. Terraform can only provide a best effort in the case of network errors, and notify the user if there was a problem.

**Comment by jantman** [comment] 2017-09-15 14:10
@jbardin Apologies for leaving this open so long without updating it. I can get the Consul lock output, though I haven't seen anything that looks interesting in it. Terraform is a bit more difficult... I'm going to have to just keep trying to reproduce it, since none of our actual production jobs where we run this can run with TF_LOG=trace.

I hope to be able to get logs and a better likelihood of reproducing it either today or Monday.

**Comment by jantman** [comment] 2017-09-25 14:30
@jbardin I've finally got logs for this!

They're quire large. Is there a secure way I can send the unmodified logs to you? There's nothing _terribly_ sensitive in them, but I'd prefer not to have them posted publicly...

**Comment by jbardin** [comment] 2017-09-25 14:47
Hi @jantman,

If direct email is secure enough for you, feel free to send it to the email in my profile. 

If you want to encrypt it, I'm on keybase as `jbardin`, or you can gpg encrypt it with the Hashicorp gpg key here: https://www.hashicorp.com/security/ and email or link the file here. 

Thanks!

**Comment by jantman** [comment] 2017-09-25 15:01
Sent. Thanks so much!

**Comment by jbardin** [comment] 2017-09-25 17:25
Hi @jantman,

Can you verify that the ELB timeout is actually 90 seconds? 
The logs indicate that the lock was lost exactly 30s after creation, which looks like a timeout closing the network connection used for the lock. 30s happens to be the ELB default, and it's also the default for the network keepalives, so if this doesn't happen 100% of the time it's probably from those conditions racing each other. 

After the timeout Terraform tried to re-acquire the lock, but failed once due to the lock grace period which can be expected in this case, and the process ended shortly thereafter, but I suspect that the lock would have been reacquired soon.  Does this ever succeed on longer runs, maybe in the 40-50sec time period?

So, if there is actually a 30s network timeout in effect here, and if the lock would have been re-acquired had the run taken a few seconds longer, then everything is working as expected.

**Comment by jbardin** [comment] 2017-09-25 19:13
Sorry, the wording "as expected" wasn't very good, since you're right; it is expected to "just work". What I meant was "as I expect", or that the order of events was logical based on my understanding of the consul lock internals, so I can be sure my base assumptions were correct when troubleshooting this further. Even if it turned out that the timeout value was at fault, it's still a bug that needs to be covered. 

However, since it doesn't appear to be the load balancer that's at fault, and every other segment should be a direct TCP connection, I'm not sure what is causing the lock failure. I'm going to attempt to setup a test harness to replicate this. 

I'll provide some of the implementation details if you're interested:

From the consul lock side, consul requires liveness to hold the lock, so as soon as there's break in the network connection it reports that the lock is lost. The client will attempt to immediately reclaim that lock, and usually does, so I'm not exactly sure why it didn't in this case.

The lock is protected during this period by the "Lock Delay", which prevents any other session from claiming the lock until that expires. Once the consul client gives up re-trying the lock, Terraform will create a new session and attempt to create a new lock. This is what outputs the `could not reacquire lock`, which is expected until the lock delay expires, but we try not to get to this point, because once the delay expires Terraform is in a race to reclaim the lock before some other process might.

The "Lock ID" itself is simply metadata for Terraform's consumption. Because the lock implementation is in consul, it's entirely up to the consul server what Terraform can do with the locks. If Terraform were simply using a consistent value as a lock, it could do as it wished, but the intent here was to be compatible with the consul lock api for other integrations. While the integration is nice, and tools like `consul lock` work as expected with Terraform, another idea I've had is to provide an alternate "lock mode", which breaks compatibility but provides a simpler implementation in Terraform.

**Comment by jantman** [comment] 2017-09-25 20:13
@jbardin Ok, thanks James. Apologies if that was too hasty, I guess I read your response as "everything's fine here, move along" but that's probably more because of my lack of understanding of how the locking works.

I think that consul requiring liveness (of connection) is what was tripping us up at first when looking at this. Most of the people on my end who I've pulled in for other opinions, were (as I was) pretty shocked that the Consul locks expect a continuous uninterrupted connection, as opposed to some variety of "ping back to Consul every N seconds to keep it alive".

Thank you so much for that explanation. I really haven't used Consul locking aside from via Terraform (though we're pretty heavy users of Consul for KV), so I suppose that my lack of familiarity with such locking systems (and my usual assumption that any persistent network connection will fail a statistically significant amount of the time) confused me. Regarding the "Lock ID", I guess that's another bit of the Consul internals that I didn't grasp; I'd assumed that it was essentially a session token of some sort, and that a client could just come back and "claim" that session & its associated locks (in essence, I'd assumed that a Lock ID was specifically designed for this case - to reclaim your lock when a connection dropped).

I'll be more than happy to assist troubleshooting however I can. My Go knowledge is barely extant, but I can try to work on a more reliable reproduction of the problem if it helps... or go back through the (admittedly not debug or trace) output of previous failures and see if I can find anything else that sticks out in them.

**Closed** 2017-10-17 19:32 UTC
Labels: backend/consul, bug
