### ISSUE TITLE
Terraform Crashes

### ISSUE THREAD

**Issue by gurrie** [hashicorp/terraform#5618] opened 2016-03-14 12:24 UTC
Hi,

I am receiving the following crash.log running terraform. 

My terraform version is 0.6.12

Regards
Brian
[crash.txt](https://github.com/hashicorp/terraform/files/171912/crash.txt)

**Comment by stack72** [comment] 2016-03-14 13:28
Hi @gurrie,

Thanks for submitting the report. I can see the following from the crash log:

```
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x181c8c]
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: 
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: goroutine 357 [running]:
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: panic(0xcea400, 0xc82000a0d0)
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: 	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsNetworkInterfaceRead(0xc82060ede0, 0xa0c360, 0xc82028e200, 0x0, 0x0)
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_network_interface.go:143 +0xb7c
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc82026f6c0, 0xc82047c300, 0xa0c360, 0xc82028e200, 0xc8202790d0, 0x0, 0x0)
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/helper/schema/resource.go:209 +0x43a
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc82020ef60, 0xc82012db00, 0xc82047c300, 0xc820559001, 0x0, 0x0)
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1da
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0xc8204f8120, 0xc8204a3410, 0xc8204a36f0, 0x0, 0x0)
2016/03/14 12:21:48 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/rpc/resource_provider.go:345 +0x6a

```

This suggests that a subnet_id is not being set back to the state. Can you please share a sample of terraform configuration (minus secrets) that would help us track this down?

Paul

**Comment by catsby** [comment] 2016-03-17 15:08
closing as dupe of 5438, thanks!

**Closed by catsby** 2016-03-17 15:08 UTC
Labels: bug, crash, provider/aws, waiting-response

**Comment by catsby** [comment] 2016-03-17 15:11
Hey @gurrie one quick question though, do you have a sample config for this?

**Comment by gurrie** [comment] 2016-03-21 22:35
Which config are you looking for? Not sure if it helps or not, but I generate the terraform scripts using terraform-inventory.
