### ISSUE TITLE
aws_ecs_service diffs didn't match during apply.

### ISSUE THREAD

**Issue by opteemister** [hashicorp/terraform#7642] opened 2016-07-14 12:14 UTC
Hello. We've got an error:
Sending the log which it was provided:

Error applying plan:

1 error(s) occurred:

* aws_ecs_service.service_hello: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.16
    Resource ID: aws_ecs_service.service_hello
    Mismatch reason: extra attributes: iam_role, load_balancer.#, cluster
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"load_balancer.1391274493.elb_name":*terraform.ResourceAttrDiff{Old:"service-hello-elb", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "load_balancer.1391274493.container_name":*terraform.ResourceAttrDiff{Old:"hello", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "load_balancer.1391274493.container_port":*terraform.ResourceAttrDiff{Old:"80", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "load_balancer.55464537.container_name":*terraform.ResourceAttrDiff{Old:"", New:"hello-service", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "load_balancer.55464537.container_port":*terraform.ResourceAttrDiff{Old:"", New:"8082", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "load_balancer.55464537.elb_name":*terraform.ResourceAttrDiff{Old:"", New:"service-hello-service-elb", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"service-hello-tf", New:"service-hello-service-tf", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"load_balancer.55464537.elb_name":*terraform.ResourceAttrDiff{Old:"", New:"service-hello-service-elb", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "cluster":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:ecs:us-west-2:034120525017:cluster/cluster-ecs-tf", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "load_balancer.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "load_balancer.55464537.container_port":*terraform.ResourceAttrDiff{Old:"", New:"8082", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "iam_role":*terraform.ResourceAttrDiff{Old:"", New:"arn:aws:iam::034120525017:role/ecs-service-role-tf", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"service-hello-service-tf", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "load_balancer.55464537.container_name":*terraform.ResourceAttrDiff{Old:"", New:"hello-service", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}}, Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by stack72** [comment] 2016-07-14 15:25
Hi @opteemister 

thanks for reporting the issue. Sorry this is causing an error  for you. In order to help us identify the issue, please could you post a copy of the configuration you are using (without secrets) and the steps you took, I.e. terraform apply config a, made change to x, terraform apply config b etc

thanks

Paul

**Comment by stack72** [comment] 2016-07-26 22:31
Closing as a duplicate of #7788 

There is code in #7788 that will help us recreate this

**Closed by stack72** 2016-07-26 22:31 UTC
Labels: bug, provider/aws, waiting-response
