### ISSUE TITLE
Terraform for_each gets stuck in infinite loop with the same single value repeating itself

### ISSUE THREAD

**Issue by Moolman** [hashicorp/terraform#27495] opened 2021-01-13 14:30 UTC
Hi

I'm having this issue now for days. 

My Terraform directory structure is as follows:

- tags [direcotry]
-- _file_name_.yaml [800 yaml files]
- main.tf

## Terraform Version
![image](https://user-images.githubusercontent.com/7881187/104461260-c6f12280-55b7-11eb-8792-7978b89a345f.png)

Initially I used version 0.14.4, thus I downgraded and still giving the same problem. 

## The only piece of code I have is:
```
data "template_file" "tags" {
  for_each    = fileset("tags/","*.yaml")
  template    = file("tags/${each.value}")
}
```

## Expected output:
Loop through all the files and stuck at any particular file. 

## Issue that occurs:
When applying Terraform plan -out=staging.tfplan. The job starts off great, and somewhere along the line, it starts recapping the same step over and over. I have left it through the night to see if it will continue but it doesn't. I then have to force stop it. 

There are times that it goes through which is very slim.

## Debug Output:
Full debug output is attached.  I need to force stop the terraform job as the same file being processed falls in an endless loop. This problem only occurs after 100's of files have already been processed after running terraform plan. 

Full Debug output file: [terraform.txt](https://github.com/hashicorp/terraform/files/5809351/terraform.txt)

```
2021/01/13 13:03:36 [TRACE] EvalReadData: Re-validating config for data.template_file.tags["filename0.yaml"]
2021/01/13 13:03:36 [TRACE] GRPCProvider: ValidateDataSourceConfig
2021/01/13 13:03:37 [TRACE] dag/walk: vertex "root" is waiting for "data.template_file.tags[\"filename1.yaml\"]"
2021/01/13 13:03:38 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/template\"] (close)"
2021/01/13 13:03:38 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/template\"] (close)" is waiting for "data.template_file.tags (expand)"
2021/01/13 13:03:42 [TRACE] dag/walk: vertex "root" is waiting for "data.template_file.tags[\"filename1.yaml\"]"
2021/01/13 13:03:43 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/template\"] (close)"
2021/01/13 13:03:43 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/template\"] (close)" is waiting for "data.template_file.tags (expand)"
2021/01/13 13:03:47 [TRACE] dag/walk: vertex "root" is waiting for "data.template_file.tags[\"filename1.yaml\"]"
2021/01/13 13:03:48 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/template\"] (close)"
2021/01/13 13:03:48 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/template\"] (close)" is waiting for "data.template_file.tags (expand)"
2021/01/13 13:03:52 [TRACE] dag/walk: vertex "root" is waiting for "data.template_file.tags[\"filename1.yaml\"]"
2021/01/13 13:03:53 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/template\"] (close)"
2021/01/13 13:03:53 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/template\"] (close)" is waiting for "data.template_file.tags (expand)"
2021/01/13 13:03:57 [TRACE] dag/walk: vertex "root" is waiting for "data.template_file.tags[\"filename1.yaml\"]"
2021/01/13 13:03:58 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/template\"] (close)"
```

## Steps to Reproduce

1. `terraform init`
2. `terraform plan`
I have tried apply as well and same problem. 

## Additional Context
I'm using default code without any customization.

**Comment by mildwonkey** [comment] 2021-01-14 17:32
Hi @Moolman , thanks for reporting this unfortunate behavior.

In order to look into this issue, we need to reproduce it. Can you provide a working configuration that we can use to reproduce this issue? Perhaps a modified version of your actual configuration, with only the data resource?

**Comment by Moolman** [comment] 2021-01-19 07:01
Hi @mildwonkey, Thank you for your response. Please see git repo below. There is sometimes (very little) that the for_each does complete. 

You can refer to terraform.txt file in the repo for the existing log and the endless loop that occurs in the bottom of the log. 

Link to Git Repo: [https://github.com/Moolman/terraform-for-ech-mock-issue](https://github.com/Moolman/terraform-for-ech-mock-issue)

I'm excited to know what the issue is and how I can fix it.

Please note I had to force stop ```Terraform plan```

**Comment by mildwonkey** [comment] 2021-01-19 13:46
Thank you for the reproduction repo @Moolman ! 

This is very interesting. I have not been able to reproduce your issue on my laptop using this configuration and running `TF_LOG=TRACE tf plan -out=staging.tfplan`. Can you tell me more about the workstation you are running terraform on? I can see from your debug log that it's a windows binary, so I'd like to see if I can reproduce this on the same OS you are running, in case it's platform specific.

**Comment by mildwonkey** [comment] 2021-01-19 17:09
update: I was also unable to reproduce this in a windows 10 virtualbox vm in powershell so I will definitely need more information to continue troubleshooting this.

**Comment by Moolman** [comment] 2021-01-21 13:22
Hi @mildwonkey 

I appreciate the effort. It seems like a computer issue. I have tried to reproduce the issue on another computer and succeeded every time thus far. I will have a look at what is wrong with my computer. Next time I know first to test another computer.

**Comment by mildwonkey** [comment] 2021-01-22 13:48
Thanks for the update! I'll close this issue, but if you get any new information, or a better reproduction example, please feel free to open a new one.

**Closed by mildwonkey** 2021-01-22 13:48 UTC
Labels: bug, waiting for reproduction
