### ISSUE TITLE
Strange output behaviour

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform#26773] opened 2020-11-02 03:07 UTC
### Terraform Version

```
Terraform v0.13.5
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "= 0.13.5"
}

terraform {
  backend local {}
}

resource random_password this { length = 40 }

output something { value = "test" }
```

### Expected Behavior

```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # random_password.this will be created
  + resource "random_password" "this" {
      + id          = (known after apply)
      + length      = 40
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + result      = (sensitive value)
      + special     = true
      + upper       = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + something = null -> "test"

...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

something = test
```

### Actual Behavior

No changes to outputs in plan

### Steps to Reproduce

```
1. `terraform init`
2. `terraform apply -target random_password.this`
```

### Additional Context

When using targeted applies, outputs have a strange unintuitive behaviour.
If I run a targeted apply right after running init for the first time, the output wont be created unless it has a direct relationship to the target being applied
If I run a generic apply, the output gets created
If I run a targeted apply when there is an existing output, which does not have a relationship to the target, terraform will perpetually show the output being removed in the plan output

Couldn't find any documentation on this strange behaviour

**Comment by jbardin** [comment] 2020-11-02 13:28
Hi @lijok 

This appears to be a duplicate of #26274.
Thanks!

**Closed by jbardin** 2020-11-02 13:28 UTC
Labels: bug, new
