### ISSUE TITLE
Terraform init on sshfs using git modules results in error: Your local changes to the following files would be overwritten by checkout

### ISSUE THREAD

**Issue by dee-kryvenko** [hashicorp/terraform#30318] opened 2022-01-09 00:50 UTC
### Terraform Version

```
1.1.2
```

### Terraform Configuration Files

```terraform
module "test" {
  source = "github.com/foo/bar?ref=v1.2.3"
}
```

### Expected Behavior

Should succeed.

### Actual Behavior

Fails with

```
│ Error: Failed to download module
│ 
│ Could not download module "some_sub_module" (.terraform/modules/test/foo.tf:1) source code from
│ "git::https://github.com/foo/some-sub-module.git?ref=v0.1.2": error downloading
│ 'https://github.com/foo/some-sub-module.git?ref=v0.1.2': /usr/bin/git exited with 1: error:
│ Your local changes to the following files would be overwritten by checkout:
│       go.mod
│ Please commit your changes or stash them before you switch branches.
│ Aborting
```

This seems to be random - every time the names of the files and submodules it complains about vary. If I keep trying long enough - eventually it succeeds, but then starts failing again.

### Steps to Reproduce

1. Mount remote dir using `sshfs`
2. `terraform init`

**Comment by apparentlymart** [comment] 2022-01-10 16:06
Hi @dee-kryvenko! Sorry for this strange behavior.

Unfortunately this error message is coming from Git rather than from Terraform, and so our ability to change what Git is doing here may be limited. However, it would still be good to try to understand what exactly is going on here.

Since Git is talking about "checkout" I assume you are running `terraform init` in a directory that was already initialized previously, and so it already has a `.terraform/modules/test` directory with possibly an older version of `https://github.com/foo/some-sub-module.git` in it. In that case, Terraform would ask Git to update the already-existing directory, which should be a local git work tree, to refer to the newly-selected ref.

Specifically, for this command I believe Terraform is running the following command in that directory:

```
git checkout v0.1.2
```

During that process, Git seems to be detecting that there are local changes to the `go.mod` file and therefore refusing to perform the operation in order to avoid data loss. It could be helpful to confirm that by switching into that directory yourself and inspecting the Git status:

```
cd .terraform/modules/test
git status
```

You mentioned that this error is intermittent, and so you may need to run `git status` multiple times to see it, but I'd expect that at least some of these runs should report that there's a local change to `go.mod` not yet committed.

I don't yet have a theory as to why `sshfs` would cause Git to incorrectly detect changes in files you haven't changed, but if you can reproduce it with direct git operations then that at least allows for the possibility of more debugging. For example, you could run `git diff` to see if Git will tell you what exactly it thinks has changed about that file, which might then give a clue as to what is going on.

I will caveat here that I have no experience with `sshfs` and so I may be missing something about its behavior that seems obvious to you. If you know of any limitations `sshfs` has in terms of e.g. what file operations it is and is not able to support when compared to a "normal" filesystem then that might help narrow this down.

As I mentioned at the top, there is only so much we can do to influence Git's behavior here because Terraform is just running Git the same way you might at the command line, and so I don't know that we will necessarily be able to change anything in Terraform to make this work better, but if we can at least understand why it is happening we might learn about additional `git checkout` command line options that could help, or perhaps learn that you could add something additional to your local Git configuration to tell Git to treat this directory a bit differently.

**Comment by dee-kryvenko** [comment] 2022-01-10 16:56
Hey @apparentlymart, thanks for getting back to me. I realized it might not be a TF issue, but as there are so many tools involved and because it seems to be a race condition - I am trying to get as much help/info as I can.

I get this error in the clean directory (with no `.terraform` folder). I think TF always does `git clone` from default branch, and as `ref` is specified - it does `checkout` after initial `clone.

If I `cd` into the `.terraform` module directory after `terraform init` fails - `git status` doesn't show any changes. Which to me proves that the issue stemming from `sshfs` - by the time I manually `cd` into the directory, file system mount catching up and becomes consistent. I think sequential `git clone` -> `git checkout` with no delay is what causing this issue.

I am able to reproduce this with a simple `git clone https://github.com/foo/bar.git && (cd bar && git checkout v0.1.4)`. If I do `git clone https://github.com/foo/bar.git && (cd bar && git diff)` - it shows random files being voided:

```
$ git clone https://github.com/foo/bar.git && (cd bar && echo ">>> First diff" && git status && git diff && sleep 5s && echo ">>> Second diff" && git status && git diff)
Cloning into 'bar'...
remote: Enumerating objects: 271, done.
remote: Counting objects: 100% (271/271), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 271 (delta 125), reused 251 (delta 114), pack-reused 0
Receiving objects: 100% (271/271), 59.01 KiB | 397.00 KiB/s, done.
Resolving deltas: 100% (125/125), done.
>>> First diff
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   VERSION

no changes added to commit (use "git add" and/or "git commit -a")
diff --git a/VERSION b/VERSION
index 49d5957..e69de29 100644
--- a/VERSION
+++ b/VERSION
@@ -1 +0,0 @@
-0.1
>>> Second diff
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Note that the files appears to be `modified`, not `deleted` - so the files are there, just empty.

To give more context - I am using Rancher Desktop, which in turn install lima-vm on my Mac with a containerd and K3s. Lima is essentially a WSL for Mac, and Rancher Desktop uses it to provide similar experience as you can get with Docker for Desktop. I am then running a Terraform container in K3s, with a `hostPath` which is a VM path to a `sshfs` mount from my host Mac. Corresponding issue: https://github.com/lima-vm/lima/pull/538.

While this seems like a `sshfs` or a `sshfs` configuration issue, I think TF might consider adding some logic to maybe pause and retry on NFS-like file systems with cache in case of any inconsistencies?

**Comment by fbrousse** [comment] 2022-01-28 11:32
same issue here, for the same reason and same usage - Mac colima / rancher desktop and terraform in docker. Any workaround ? for the moment I switch the local docker context to "Docker Desktop".

**Comment by apparentlymart** [comment] 2022-01-28 19:11
Thanks for sharing that additional information, @dee-kryvenko, and also sorry for the delay in getting back to you.

Given what you observed here, I think it would be best to pursue this with git maintainers, since git is in a much better position here to differentiate between different kinds of errors and interact directly with the underlying filesystem to potentially gather more data on what state this filesystem is in, and thus decide whether it would be productive to retry or not. Terraform's interactions here are far more coarse and in particular it can only tell whether the git operations succeeded or failed, and not any details about _how_ it failed. Our goal is to try to use git in as "normal" a way as is reasonable given the UI we've built on top of it, so that we can support typical situations that Git would support and impose as few additional constraints as possible.

However, if it's running multiple git commands in series that exacerbates this problem then a short-term workaround (until this can be addressed upstream in Git) might be to set the query argument `depth=1` in your source address, like `github.com/foo/bar?ref=v1.2.3&depth=1`. In the current implementation it happens that Terraform implements shallow clone mode by running `git clone --depth=1 --branch=v1.2.3`, which avoids the need for the separate checkout step _although_ I don't recall off the top of my head whether Git will accept what looks like a tag name as a valid `--branch=` in this context, or whether it specifically requires a `refs/heads/...` reference.

(Note that the different cloning behavior for shallow mode is an implementation detail rather than a contract, and in particular earlier versions of Terraform had some different logic to deal with it, so I'm suggesting it only as a way to make things work in the short term, not as a substitute for reporting this bug to upstream git, or changing your approach to use git only in ways it can reliably support.)

It doesn't seem like there's any reasonable path to us improving this within Terraform itself, since the problem is upstream of Terraform, and so I'm going to close this. Unfortunately the Git project doesn't seem to have an explicit public issue tracker, so I wasn't able to confirm quickly if this is an already-known issue, but perhaps some discussion in [the Git community channels](https://git-scm.com/community) would be productive.

Thanks for reporting this, and sorry the problem is at a different layer!

**Closed by apparentlymart** 2022-01-28 19:11 UTC
Labels: bug, waiting-response, new

**Comment by dee-kryvenko** [comment] 2022-01-29 22:39
Totally agree that this issue has nothing to do with TF. It would be nice to have a workaround built into TF as I don't believe such an edge case low priority issue will get much progress in the Git community, not to mention sshfs is really not the best for that kind of things, but I totally understand why you wouldn't want to take on this technical debt. I think this is now ultimately at hands of Lima and Rancher Desktop to replace sshfs with something better and more stable, which [they already had intention to do](https://github.com/lima-vm/lima/issues/20).
