### ISSUE TITLE
Terraform import fails for modules on dynamic interpolation

### ISSUE THREAD

**Issue by cynful** [hashicorp/terraform#26475] opened 2020-10-02 20:21 UTC
### Terraform Version
```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/google v3.39.0
+ provider registry.terraform.io/hashicorp/google-beta v3.39.0
```

### Terraform Configuration Files

modules for bigtable instance and bigtable table with output for instance name
```terraform
# ../../modules/bigtable_instance/main.tf
resource "google_bigtable_instance" "this" {
  name          = var.name
  instance_type = var.instance_type

  dynamic "cluster" {
    for_each = var.cluster
    content {
      cluster_id   = cluster.value.cluster_id
      zone         = cluster.value.zone
      storage_type = cluster.value.storage_type != null ? cluster.value.storage_type : "SSD"
      num_nodes    = var.instance_type == "DEVELOPMENT" ? null : lookup(cluster.value, "num_nodes", 1)
    }
  }

  deletion_protection = var.deletion_protection

  lifecycle {
    prevent_destroy = true
  }
}

output "name" {
  value = google_bigtable_instance.this.name
}

# ../../modules/bigtable_table/main.tf
resource "google_bigtable_table" "table" {
  name          = var.name
  instance_name = var.instance_name

  dynamic "column_family" {
    for_each = var.column_families

    content {
      family = column_family.value.family
    }
  }
}
```
Config for reproducing failure:
```terraform
module "bigtable-instance" {
  count = 1

  source        = "../../modules/bigtable_instance"
  name          = "tf-instance"
  instance_type = "DEVELOPMENT"

  cluster = [
    {
      cluster_id   = "tf-instance-cluster"
      zone         = "us-central1-a"
      storage_type = "SSD"
    }
  ]
}

module "bigtable-table" {
  count = 1

  source        = "../../modules/bigtable_table"
  name          = "tf-table"
  instance_name = module.bigtable-instance.0.name

  column_families = [
    { family = "data" }
  ]
}

module "bigtable-instance-2" {
  count = 1

  source        = "../../modules/bigtable_instance"
  name          = "tf-instance-2"
  instance_type = "DEVELOPMENT"

  cluster = [
    {
      cluster_id   = "tf-instance-2-cluster"
      zone         = "us-central1-a"
      storage_type = "SSD"
    }
  ]
}
```

### Expected Behavior
I should be able to import a dynamic module when using interpolation for other non-related dynamic modules.

### Actual Behavior
When trying to import a dynamic module, the import walk bombs when interpolating other non-related dynamic modules. This happens even though terraform plan, apply, and state rm all succeed for the same dynamic module.

### Steps to Reproduce
Steps to reproduce failure:
1. `terraform init`
2. `terraform apply`
3. `terraform state list`
4. `terraform state rm 'module.bigtable-instance-2[0].google_bigtable_instance.this'`
5. `terraform import 'module.bigtable-instance-2[0].google_bigtable_instance.this' tf-instance-2`

```
Error: Invalid index

  on /Users/.../bigtable.tf line 22, in module "bigtable-table":
  22:   instance_name = module.bigtable-instance.0.name
    |----------------
    | module.bigtable-instance is empty tuple

The given key does not identify an element in this collection value.
```
When trying to import this dynamic module (tf-instance-2), the import fails on trying to interpret `tf-instance.0.name` which is the first instance's output; completely unrelated to the import of tf-instance-2.

Steps to reproduce workaround:
```terraform
module "bigtable-table" {
  count = 1

  source        = "../../modules/bigtable_table"
  name          = "tf-table"
  # change the interpolation to a string literal
  # instance_name = module.bigtable-instance.0.name
  instance_name = "tf-instance"

  column_families = [
    { family = "data" }
  ]
}
```
1. `terraform import 'module.bigtable-instance-2[0].google_bigtable_instance.this' tf-instance-2`

### Additional Context
This also fails when using
`instance_name = module.bigtable-instance[count.index].name`

### References
I believe this is related to https://github.com/hashicorp/terraform/issues/26258
and also stems from this change https://github.com/hashicorp/terraform/pull/25890/files

**Comment by lyderX05** [comment] 2020-10-03 21:49
Problem is within the script you have written: first, there is no dependencies between each of module so which module will run first will have no idea and therefore you will not be able to plan the resources and get the "instance_name" value. even if you use depends_on method it will fail because planning will not able to get value unless "bigtable_instance" module is applied so it fails.

Only work around is:
Plan the bigtable_instance module first and apply it  and then call the whole plan file and apply the source, Through this tfstate will able to get value of your "bigtable_instance" and you will be able to apply second module.

**Comment by cynful** [comment] 2020-10-05 16:27
@lyderX05 I think you're confused about my use case, please read the reproduction steps.

I can plan and apply perfectly fine. It fails when I try to `terraform import` a completely separate bigtable_instance.
Terraform import should not complain on this import because the resource being imported does not have any dependencies.

**Comment by pselle** [comment] 2020-10-05 18:36
@cynful I see you mentioned https://github.com/hashicorp/terraform/issues/26258 in your issue -- reading both, I'm feeling like this is a duplicate of that issue, because you're talking about how a particular addressing of a module when using `import` fails. What's the differentiation between these two issues/where does "dynamic interpolation" come into play?

**Comment by cynful** [comment] 2020-10-09 23:31
@pselle yes its likely a duplicate? The difference between `count` and `for_each` is pretty minor.
`.0.name` still works when reference for a count instance

**Comment by pselle** [comment] 2020-10-12 14:59
It appears the other issue was closed by https://github.com/hashicorp/terraform/pull/26490, which will go out in 0.14 (and the upcoming beta thereof).

**Closed by pselle** 2020-10-12 14:59 UTC
Labels: bug, new
