### ISSUE TITLE
Preserving object key order in jsonencode

### ISSUE THREAD

**Issue by mxxk** [hashicorp/terraform#27880] opened 2021-02-23 05:58 UTC
When converting a Terraform block into a JSON object, `jsonencode` sorts the object keys:

```
$ echo 'jsonencode({ b = "b", a = "a" })' | terraform console
"{\"a\":\"a\",\"b\":\"b\"}"
```

Usually the sorting is not a problem, but sometimes leads to behavior different than what is expected. This difference may result in an error when using `jsonencode` to express AWS IAM policies, as the example below demonstrates.

Though the example below is AWS-specific, the issue is opened in the main Terraform repository because it pertains to `jsonencode` and affects other providers. In time, other places where key sorting is problematic would hopefully become visible in the form of comments on this issue.

### Terraform Version

```
Terraform v0.14.7
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27"
    }
  }
}

provider "aws" {
  region  = "us-west-2"
}

resource "aws_iam_policy" "some-policy" {
  name = "some-policy"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = {
      Action   = "*"
      Effect   = "Deny"
      Resource = "*"
    }
  })
}
```

### Expected Behavior

If `jsonencode` has an option to preserve the order of JSON object keys, that may be the easiest and most obvious fix.

### Actual Behavior

```
Error: Error creating IAM policy some-policy: MalformedPolicyDocument: The policy failed legacy parsing
	status code: 400, request id: 9aed5d9d-caa6-46fd-8dcc-d5c78ef4718c
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -auto-approve`

### Additional Context

- According to [IAM JSON policy elements: Version](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_version.html),

    > To use all of the available policy features, include the following `Version` element before the `Statement` element in all of your policies.
    >
    >     "Version": "2012-10-17"
    
    However, `jsonencode` sorts the keys such that the `Version` element appears _after_ the `Statement` element, resulting in the "policy failed legacy parsing" error.

- Outside of Terraform, the error "policy failed legacy parsing" can be reproduced in attempting to create the IAM policy below:

    ```json
    {
      "Statement": {
        "Action": "*",
        "Effect": "Deny",
        "Resource": "*"
      },
      "Version": "2012-10-17"
    }
    ```

    Placing `Version` above `Statement` makes the policy above valid (for version `2012-10-17`).

- Using a list instead of an object for the `Statement` element, as in

    ```
    "Statement": [ ... ]
     ```

    would make the policy compatible with the legacy policy version and misleadingly hide the version mismatch error.

- The IAM policy examples using `jsonencode` prominently featured on the AWS provider docs (e.g. [aws_iam_policy](https://registry.terraform.io/providers/hashicorp/aws/3.29.0/docs/resources/iam_policy)) do not encounter this issue for the reason above, but still harbor the same version mismatch.

    It may be useful to open another issue for the AWS provider documentation after there is a resolution to this one.

**Comment by alisdair** [comment] 2021-02-24 15:20
Hi @mxxk. Thanks for reporting this unfortunate issue.

I've labelled this as an enhancement rather than a bug, because it is by design that all objects and maps are iterated in lexicographical key order. This includes generating JSON from these values (and others). Changing Terraform to address the AWS problem you describe would require preserving object/map key order, which is quite a significant change at the language level.

**Comment by mxxk** [comment] 2021-02-24 17:34
Thanks for the triage and context @alisdair.  Hopefully, instances where lexicographical iteration of objects/maps causes issues is limited to only a few niche cases like AWS IAM described here.

**Comment by alisdair** [comment] 2021-02-24 17:42
I think the most likely resolution of this issue would come from the AWS provider. It might be possible to extend the provider to allow you to specify the policy as an object value instead of a string, and have the provider custom-generate the JSON according to the AWS requirements.

If that makes sense to you, I'd recommend [opening an issue on the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws/issues/new/choose) to discuss it, referencing this issue.

As a workaround, you could specify the policy as a JSON string using a heredoc:

```hcl
resource "aws_iam_policy" "some-policy" {
  name = "some-policy"
  policy = <<<JSON
{
  "Version": "2012-10-17",
  "Statement": {
    "Action": "*",
    "Effect": "Deny",
    "Resource": "*"
  }
}
JSON
}
```

**Comment by mxxk** [comment] 2021-02-24 18:52
It makes sense, but I was wondering if the core Terraform team would be open to seeing this issue as more than being confined to the AWS provider. Temporarily putting aside how much work it would take to customize the lexicographical iteration behavior, it would be great to hear your input on the reasoning below. 🙂

Looks like lexicographical iteration is core to the [HCL syntax](https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md)

> For object and map types, the key is the string attribute name or element key, and the value is the attribute or element value. The elements are visited in the order defined by a lexicographic sort of the attribute names or keys.

and both Terraform and its providers work well together with that expectation. Would that not make it an implementation detail, albeit a significant one?

On the one hand, if a cloud provider's API is sensitive to a JSON input's object key order, the corresponding Terraform provider could easily "do the right thing", even if the original Terraform configuration block was parsed according to HCL rules (thus hiding the implementation detail). This is what [iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/3.29.0/docs/data-sources/iam_policy_document) does.

On the other hand, Terraform may not know in advance where _opaque_ structured data (e.g. JSON produced with `jsonencode`) will be used, and wouldn't be able to make just-in-time corrections as with the API example earlier. In this case, would it not be unreasonable to allow the user to help Terraform out by filling in those details (i.e. the correct object key order for the given data), thus hiding the implementation detail as well?

At the same time, I completely understand that with the ready workarounds available, this enhancement would hardly be considered pressing unless more folks chime in with other cases where `jsonencode` object key order matters.

---

For others stumbling upon this issue, here are some more workarounds:

1. Using [iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/3.29.0/docs/data-sources/iam_policy_document) (an example of )

    ```tf
    data "aws_iam_policy_document" "deny" {
      statement {
        # `version` defaults to "2012-10-17"
        actions   = ["*"]
        effect    = "Deny"
        resources = ["*"]
      }
    }

    resource "aws_iam_policy" "some-policy" {
      name   = "some-policy"
      policy = data.aws_iam_policy_document.deny.json
    }
    ```


1. Almost exactly identical to https://github.com/hashicorp/terraform/issues/27880#issuecomment-785252728, except with a small readability improvement using an [indented heredoc](https://www.terraform.io/docs/language/expressions/strings.html#indented-heredocs):

    ```tf
    resource "aws_iam_policy" "some-policy" {
      name   = "some-policy"
      policy = <<-JSON
      {
        "Version": "2012-10-17",
        "Statement": {
          "Action": "*",
          "Effect": "Deny",
          "Resource": "*"
        }
      }
      JSON
    }
    ```

**Comment by apparentlymart** [comment] 2021-02-24 19:15
Hi @mxxk,

If I'm understanding your explanation correctly, I think what you're saying here matches our typical design principles for things like this: Terraform (both core and the official providers) has a number of situations where we've established a conventional way to serialize something that can potentially be serialized in many ways without any loss of meaning, because resulting configurations are typically more readable if we can worry only about data flowing from one resource/provider to another without lots of distracting mechanical conversions.

An existing common example of that is timestamps, where Terraform conventionally uses RFC 3339 timestamp syntax and we generally consider it a provider's responsibility to map from that syntax into whatever syntax the remote API expects, as long as that conversion is possible without a mismatch of information level. (For example, if a particular remote system wanted to work with tzdata-based timezone names which imply daylight savings rules, rather than UTC offsets, then we might elect to diverge from the usual convention, because RFC 3339 only deals in UTC offsets.)

As far as I know we've not yet encountered a situation where a remote system considered the ordering of JSON properties significant, and so there's no existing precedent for that sort of thing. Given that JSON libraries in many programming languages aside from Terraform have the same assumption that object property order is insignificant -- often for the same reasons that Terraform does, due to the behaviors of the language's native dictionary/mapping type -- I feel inclined to say that this is an AWS-specific oddity that would ideally therefore be handled by the AWS provider for the same reasons as for the timestamp convention I described above: so that it's easier to compose together data from different sources that might not be aware of this IAM-specific serialization oddity.

Of course, there may be technical constraints I'm not aware of that make it difficult for the provider to handle this. From the outside looking in it seems reasonable in principle to have the provider rewrite the given JSON source code into the ordering that IAM expects, rather than treating it just as an opaque string, but given how commonly IAM policies appear throughout AWS APIs and thus throughout AWS provider resources, it might not be practically to do that rewriting holistically and so working with the `aws_iam_policy_document` data source (which understands the IAM JSON format in particular) might have to be the compromise to get something that IAM will accept.

With that said, I agree with @alisdair that the best path forward here would seem to be to discuss this in the AWS provider repository. I find it unlikely that we would totally redesign Terraform's type system so it had order-preserving object types just to work around a strange anomaly with one particular cloud vendor, since a change like that could have pretty severe consequences for various existing Terraform modules assuming the current definition of objects.

**Comment by apparentlymart** [comment] 2022-02-26 00:28
Hi again all,

I'm going to close this one out for now, because so far it seems reasonable for the Terraform language to continue treating map elements as unordered (applying a lexical ordering by key whenever used in a context where an ordering is required), and for any specific resource types that require a different behavior to handle it in a custom way, such as by automatically rewriting the value into a suitable form for the remote system as an implementation detail of the provider.

A `jsonencode` function that can preserve ordering would be a significantly different design than the current one that just directly maps all of Terraform's data types into their closest JSON equivalents, and so that would be a last resort if we can't find any suitable resolution at the provider level. In that case, the relevant provider teams will pass that feedback on to us directly, and we can either reopen this issue or open a new one to capture whatever new information we've learned to prompt doing so.

Thanks again for reporting this!

**Closed by apparentlymart** 2022-02-26 00:28 UTC
Labels: enhancement
