### ISSUE TITLE
google_storage_bucket_acl: allow setting object default permissions

### ISSUE THREAD

**Issue by dasch** [hashicorp/terraform#14031] opened 2017-04-27 12:14 UTC
It looks like it's currently only possible to set permissions for the bucket itself – I would like to set the "object default permissions", which apply to all new objects created in the bucket.

**Comment by paddycarver** [comment] 2017-04-27 22:19
I'm pretty sure this is a duplicate of #12481, I'm going to close it out and consolidate conversation there. Please feel free to comment if you think these are distinct issues. Thanks!

**Closed by paddycarver** 2017-04-27 22:19 UTC
Labels: enhancement, provider/google-cloud

**Comment by dasch** [comment] 2017-04-28 08:15
:+1: I just didn't find it with my search keywords.

**Comment by paddycarver** [comment] 2017-04-28 16:45
No worries! I just happened to remember looking at it the other day, that's the only way I connected them. :)
