### ISSUE TITLE
1.4 - Plan with no changes is not reported

### ISSUE THREAD

**Issue by alex-shafer-1002** [hashicorp/terraform#32823] opened 2023-03-10 16:29 UTC
### Terraform Version

```shell
Terraform v1.4.0
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.27.0
+ provider registry.terraform.io/datadog/datadog v3.20.0
+ provider registry.terraform.io/fivetran/fivetran v0.6.13
+ provider registry.terraform.io/hashicorp/aws v4.32.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/newrelic/newrelic v3.15.0
+ provider registry.terraform.io/opsgenie/opsgenie v0.6.20
+ provider registry.terraform.io/pagerduty/pagerduty v1.11.0
+ provider registry.terraform.io/snowflake-labs/snowflake v0.58.0
```

### Terraform Configuration Files

```terraform
# this is from a large, complicated configuration, providing it is infeasible
```

### Debug Output

Prefer not to provide due to sensitive information

### Expected Behavior

Terraform should report `No changes. Your infrastructure matches the configuration.` or similar if the plan does not make any changes, as in 1.3.9 and prior.

### Actual Behavior

No such report is output after upgrading to Terraform 1.4.0

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment] 2023-03-10 16:47
Duplicate of #32815

**Closed by jbardin** 2023-03-10 16:47 UTC
Labels: bug, new
