### ISSUE TITLE
Add .terraformignore support  to terraform CLI  

### ISSUE THREAD

**Issue by KhimairaCrypto** [hashicorp/terraform#30358] opened 2022-01-16 00:31 UTC
I would love to be able to have a .terraformignore and disable some of the .tf files that I have in my project. This is very helpful specially if I am debugging some sections. Right now I have to play with git branches and remove components. This sucks! having .terrafomignore will make my day! 

Just for the record I do not use terraform cloud!

**Comment by auroat** [comment] 2022-01-19 14:05
@KhimairaCrypto - hi, are you planning to work on that yourself? Or that was a request for the community in general? :)

**Comment by KhimairaCrypto** [comment] 2022-01-19 21:00
It was a request! Did I missed something to make a formal request?

**Comment by crw** [comment] 2022-02-03 00:30
Hi @KhimairaCrypto, thanks for the feature request! I am going to close this as it is more-or-less a duplicate of this closed issue (https://github.com/hashicorp/terraform/issues/13021). See [this comment](https://github.com/hashicorp/terraform/issues/13021#issuecomment-294592721) on that issue for a list of strategies to use for managing specific resources. Also, I found [the following StackOverflow exchange](https://stackoverflow.com/questions/51447912/exclude-a-file-in-terraform-module-source), it may also be useful to you. 

If you think this feature is still required having reviewed the previous links, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further. Thanks again for your request!

**Closed by crw** 2022-02-03 00:30 UTC
Labels: enhancement, new
