### ISSUE TITLE
Google cloud wants to mod target pools on every plan/apply

### ISSUE THREAD

**Issue by Markbnj** [hashicorp/terraform#13168] opened 2017-03-29 18:06 UTC
### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
- google_compute_target_pool

### Terraform Configuration Files
```hcl
resource "google_compute_target_pool" "jabber-target-pool" {
  name = "jabber-target-pool"

  instances = ["${module.jabber-nodeset.self_links}"]
  health_checks = ["${google_compute_http_health_check.jabber-health-check.name}"]
}
```
### Debug Output
N/A
### Panic Output
N/A
### Expected Behavior
Terraform plan reports the need for modifications to a target pool. The modifications appear to be a reordering, and so it's likely they are unnecessary. Here is the plan for the target pool:
```
~ module.jabber-prod.google_compute_target_pool.jabber-target-pool
    instances.0: "us-central1-a/jabber1" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber1"
    instances.1: "us-central1-a/jabber2" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber2"
    instances.2: "us-central1-a/jabber3" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber3"
```
The modifications were applied:
```
module.jabber-prod.google_compute_target_pool.jabber-target-pool: Modifying... (ID: jabber-target-pool)
  instances.0: "us-central1-a/jabber1" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber1"
  instances.1: "us-central1-a/jabber2" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber2"
  instances.2: "us-central1-a/jabber3" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber3"
...
module.jabber-prod.google_compute_target_pool.jabber-target-pool: Modifications complete (ID: jabber-target-pool)
```
At this point we expect the plan to no longer show the pending modifications.
### Actual Behavior
However after applying successfully plan still shows the modifications as pending:
```
~ module.jabber-prod.google_compute_target_pool.jabber-target-pool                                                                                                                                   [18/6584]
    instances.0: "us-central1-a/jabber1" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber1"
    instances.1: "us-central1-a/jabber2" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber2"
    instances.2: "us-central1-a/jabber3" => "https://www.googleapis.com/compute/v1/projects/.../instances/jabber3"
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### References
This feels like the same root issue we reported recently for google_compute_instance_groups and which was fixed in 0.9.2 
- #12213

**Comment by danawillow** [comment] 2017-03-30 17:48
Duplicate of #9121 (there's a workaround in there if you'd like to give that a try; I know it's not perfect but it at least will get your config working)

**Closed by danawillow** 2017-03-30 17:48 UTC
Labels: bug, provider/google-cloud

**Comment by Markbnj** [comment] 2017-03-30 18:24
Thanks, Dana! Should have searched first. Sorry for the dupe. And thanks
for fixing that instance-groups bug so quickly :). That removed a ton of
spam from our plans.

Regards,
Mark Betz
Olark

**Comment by danawillow** [comment] 2017-03-30 18:29
No worries! Glad I could help on that one :)
