### ISSUE TITLE
Variable Expansion Error - The expanding argument (indicated by ...) must be of a tuple, list, or set

### ISSUE THREAD

**Issue by patpicos** [hashicorp/terraform#24869] opened 2020-05-05 21:00 UTC
### Terraform Version
```
tf -v
Terraform v0.12.24
+ provider.azurerm v2.8.0
...
```

### Terraform Configuration Files
Intent: I perform cidr math to allocate as many IP ranges to a Private subnet. I include the locals section below.
Input:
`base_cidr_block = "10.0.0.0/21"`

In the code below, I added comments where the issue rise. basically, doing `pow(2,2)` works, but `pow(2,local.exponent)` where exponent = 2 fails.
```hcl
locals {
        cidr_num = tonumber(regex("/(\\d+)",var.base_cidr_block)[0])
        // TODO: Add validation to prevent networks larger than /21. cidr_num < 21
        small_subnet_bits = 26-local.cidr_num
        service_subnet_bits = 24-local.cidr_num
        subnet_array = cidrsubnets(var.base_cidr_block, 
                local.small_subnet_bits,
                local.small_subnet_bits,
                local.small_subnet_bits,
                local.small_subnet_bits,
                local.service_subnet_bits, 
        )
        //Need to generate an array with the remaining IP ranges from the base_cidr_block
        // 10.0.0.0/20 will lose from 10.0.0.0 to 10.0.1.255 for first 5 subnets
        // need to assign 10.0.3.0 to 10.0.15.255 to Private
      
        // Array that contains the number of "newbits" for all /24 within up to a /20 CIDR range (Azure doesnt recommend CIDRs larger than /21)
        // This array will be reduced down based on the size of the CIDR range.
        slicer_array = [
                local.service_subnet_bits,
                local.service_subnet_bits,
                local.service_subnet_bits,
                local.service_subnet_bits,
                local.service_subnet_bits,
                local.service_subnet_bits,
                local.service_subnet_bits,
                local.service_subnet_bits]

        exponent = 24 - local.cidr_num - 1     // value is 2
        slash_count = pow(2,local.exponent)    // doesnt work

        // Generate all /24 networks within the base_cidr_block
        # all_24 = cidrsubnets(var.base_cidr_block, slice(local.slicer_array,0,pow(2,2))...)  //works
        all_24 = cidrsubnets(var.base_cidr_block, slice(local.slicer_array,0,local.slash_count)...)  //works

        // Remove the first two since they are used by the other 5 subnets (4x /26 and 1x /24)
        // Effectively, the first /23 gets chewed up. I want to take all the remaining /24 and allocated to the larger subnet.
        sub_all_24 = slice(local.all_24,2, local.slash_count )

}
...
```
Error:
```hcl
Error: Invalid expanding argument value

  on main.tf line 40, in locals:
  40:         all_24 = cidrsubnets(var.base_cidr_block, slice(local.slicer_array,0,local.slash_count)...)  //works
    |----------------
    | local.slicer_array is tuple with 8 elements

The expanding argument (indicated by ...) must be of a tuple, list, or set
type.
```
Interestingly, if I introspect the values in `terraform console`, the locals get populated with the appropriate values:

```json
terraform console

> Warning: Experimental feature "variable_validation" is active

  on ../azure_naming/variables.tf line 2, in terraform:
   2:   experiments = [variable_validation]

Experimental features are subject to breaking changes in future minor or patch
releases, based on feedback.

If you have feedback on the design of this feature, please open a GitHub issue
to discuss it.

> 

> local.exponent
2
> local.slash_count
4
> local.all_24
[
  "10.0.0.0/24",
  "10.0.1.0/24",
  "10.0.2.0/24",
  "10.0.3.0/24",
]
> local.sub_all_24
[
  "10.0.2.0/24",
  "10.0.3.0/24",
]
```

### Crash Output

No crash

### Steps to Reproduce

terraform plan 

### Additional Context

No special env context.

**Comment by patpicos** [comment] 2020-05-05 21:09
it feels like a bug in the validation process.

**Comment by patpicos** [comment] 2020-05-05 21:25
I solved the issue by doing a for loop and use cidrsubnet instead
```hcl
all_24 = [
                for num in range(0,local.slash_count):
                cidrsubnet(var.base_cidr_block,local.service_subnet_bits,num)
        ]
```

**Comment by patpicos** [comment] 2020-05-05 21:26
I will leave it open since I still think the validation behavior seems wrong.

**Comment by danieldreier** [comment] 2020-05-19 22:43
Thanks for reporting it! I've [reproduced](https://github.com/danieldreier/terraform-issue-reproductions/tree/master/24869) this behavior.

**Comment by patpicos** [comment] 2020-05-19 22:58
Thanks Daniel. Glad I am not going crazy.

**Comment by apparentlymart** [comment] 2020-06-03 23:45
Hi @patpicos! Thanks for reporting thos.

I think this is the same root cause as #22404, so I'm going to close this only to consolidate the discussion there. Thanks again!

**Closed by apparentlymart** 2020-06-03 23:45 UTC
Labels: bug, reproduced
