### ISSUE TITLE
MOD on large numbers can have negative results or > modulus 

### ISSUE THREAD

**Issue by mweissbacher** [hashicorp/terraform#26365] opened 2020-09-24 16:47 UTC
### Terraform Version

```
Terraform v0.13.3
```

### Crash Output

No crash

### Expected Behavior

Using parseint on hashes, then running MOD. The output of `MOD n` should be in the range 0 - (n-1).

### Actual Behavior

Result larger than modulus

```
> (parseint("a970486ab0715fcb573a3e65e97d46eb65d801", 16)) % 15
17
```

Negative result

```
> parseint("a970486ab0715fcb573a3e65e97d46eb65d80b1b", 16) % 15
-5
```

Parseint provides a positive result

```
> parseint("a970486ab0715fcb573a3e65e97d46eb65d80b1b", 16)
9.673234321205151e+47
```

Even with `abs` however the MOD result is negative

```
> abs(parseint("a970486ab0715fcb573a3e65e97d46eb65d80b1b", 16)) % 15
-5
```

### Steps to Reproduce

`terraform console` and run the commands above. I was able to reproduce the same with a different installation of TF.

I was only able to reproduce this behavior with large numbers, lower numbers seem to work fine.

### Additional Context

Purely running `terraform console`

**Comment by apparentlymart** [comment] 2020-09-24 22:12
Thanks for reporting this, @mweissbacher.

I was able to reproduce it in a development build of Terraform 0.14, so I've marked it as confirmed in both releases.

Digging in a little to _why_ it behaves in this way leads to [the underlying library that Terraform uses to implement that modulo operation](https://github.com/zclconf/go-cty/blob/36785d4dc4ac7d38d1a930390a805d23d63a99da/cty/value_ops.go#L671-L676). As the comment there notes, it's doing something pretty awkward in order to deal with the fact that the underlying arbitrary-precision float library doesn't have a native modulo function.

I think the sequence of operations it's doing there is equivalent to the following primitive arithmetic operations (this is not intended to be Terraform expression notation):

> modulo(_a_, _b_) = (floor(_a_ / _b_) * _b_) - _a_

At first it seemed that things were get off on the wrong foot from the first operation here:

```
> 967323432120515089486873574508975134568969931547 / 15
6.448822880803433929912490496726500897126466210313333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333e+46
> format("%f", 967323432120515089486873574508975134568969931547 / 15)
"64488228808034339299124904967265008971264662103.133333"
> floor(967323432120515089486873574508975134568969931547 / 15)
-9.223372036854775808e+18
> floor(64488228808034339299124904967265008971264662103.133333)
-9.223372036854775808e+18
```

[The `floor` function implementation](https://github.com/zclconf/go-cty/blob/36785d4dc4ac7d38d1a930390a805d23d63a99da/cty/function/stdlib/number.go#L395-L404) seems to be trying to constrain only to what is in range for a `float64`, but I suspect it's not actually succeeding and is instead producing an incorrect answer in that case.

However, the `floor` in the modulo function is not actually the `floor` function as Terraform sees it, so I think that other bug is a red herring. The modulo function is using [`big.Float.Int`](https://godoc.org/math/big#Float.Int) to compute "floor", which shouldn't have that range limit, but it seems plausible that some similar range-related problem is arising along the way somehow, because the behavior is similar even if not exactly the same.

We'll need to do some more detailed debugging to fully get to the bottom of this, but since the problem seems to be in an upstream library rather than directly in the Terraform codebase I'm going to add our label to indicate that.

**Comment by mildwonkey** [comment] 2020-12-14 16:25
I have an alternative interpretation @apparentlymart: `parseint` is casting the result to a cty.NumberVal - a float : https://github.com/zclconf/go-cty/blob/36785d4dc4ac7d38d1a930390a805d23d63a99da/cty/function/stdlib/number.go#L539

If you change that line to return a `NumberIntVal`, the results from `terraform console` line up with the results you would get with straight go code:

Here's the go-playground example (TL;DR: same results as below): https://play.golang.org/p/GUTDgdyk2ju

And here's the results of `terraform console` using my modified go-cty library:

```
> (parseint("a970486ab0715fcb573a3e65e97d46eb65d801", 16)) % 15
2
> parseint("a970486ab0715fcb573a3e65e97d46eb65d80b1b", 16) % 15
-3
```

I think this change lines up well with the intended results from `parseint`; we'll see! It does change the result of (only) one test case. I will open a PR in go-cty, with this explanation, and we can decide if this was the right track there.

**Comment by mildwonkey** [comment] 2020-12-15 16:30
I just learned that this PR also fixes this specific issue, but hasn't been pulled into terraform yet: https://github.com/zclconf/go-cty/pull/75

my pr may be relevant to some general issues but it's not the thing that fixes this. (I'm not sure if this distinction matters right now, but it may be useful context in the future)

**Closed** 2020-12-17 19:24 UTC
Labels: bug, config, confirmed, dependencies, v0.13, v0.14
