### ISSUE TITLE
client_elb: unexpected EOF panic: interface conversion: interface {} is string, not map[string]interface {}

### ISSUE THREAD

**Issue by shahamit2** [hashicorp/terraform#16263] opened 2017-10-05 05:10 UTC
Hi there,

### Terraform Version
Terraform v0.10.6

### Crash Output
If the console output indicates that Terraform crashed, please share a link to a GitHub Gist containing the output of the `crash.log` file.
[crash.log.gz](https://github.com/hashicorp/terraform/files/1358099/crash.log.gz)

### Actual Behavior
Terraform crashed with messages related to client_elb in crash file.

module.client-es-asg.aws_elb.client_elb: unexpected EOF panic: interface conversion: interface {} is string, not map[string]interface {}

### Steps to Reproduce
`terraform apply`

[crash.log.gz](https://github.com/hashicorp/terraform/files/1358099/crash.log.gz)

**Comment by radeksimko** [comment] 2017-10-05 06:57
Hi @shahamit2 ,
Thanks for the report.
Clipping out the interesting part of crash log:

```
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: panic: interface conversion: interface {} is string, not map[string]interface {}
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: goroutine 233 [running]:
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readMap(0xc4216505d0, 0x208c714, 0x4, 0xc42158e870, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:170 +0xfb3
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc4216505d0, 0xc42082d230, 0x1, 0x1, 0xc42111b400, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:113 +0xd72
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc4216505d0, 0xc42082d230, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0x110
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc420e4eda0, 0xc42082d230, 0x1, 0x1, 0x208dffc, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:31 +0x12e
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc4201bdb20, 0xc42082d230, 0x1, 0x1, 0xc42082d212, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:491 +0x16e
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc4201bdb20, 0x208c714, 0x4, 0x1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:467 +0x135
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc4201bdb20, 0x208c714, 0x4, 0x208b585, 0x1, 0xc420b41350, 0x5, 0x0)
2017-10-05T01:00:03.756Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:444 +0xa5
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diffMap(0xc421547ec0, 0x208c714, 0x4, 0xc42158e870, 0xc420b416a0, 0xc4201bdb20, 0x0, 0x0, 0x0)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:850 +0x10c
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc421547ec0, 0x208c714, 0x4, 0xc42158e870, 0xc420e4eca0, 0xc4201bdb20, 0x7fd658f9bc00, 0x0, 0x0)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:701 +0x4e9
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc421547ec0, 0xc420c62d20, 0xc4203c4630, 0x0, 0x0, 0xc42168d194)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:390 +0x1cb
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc42156db00, 0xc420c62d20, 0xc4203c4630, 0x7, 0xc420ecc758, 0xc420fc6d01)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:218 +0x15b
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc4201cc0e0, 0xc420c62cd0, 0xc420c62d20, 0xc4203c4630, 0x7fd658fcb6c8, 0x0, 0x1000)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:272 +0x8d
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc420fd45a0, 0xc420be7fe0, 0xc4208698a0, 0x0, 0x0)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:499 +0x57
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: reflect.Value.call(0xc4200570e0, 0xc42111a728, 0x13, 0x208bffc, 0x4, 0xc420049f20, 0x3, 0x3, 0x0, 0x0, ...)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x906
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: reflect.Value.Call(0xc4200570e0, 0xc42111a728, 0x13, 0xc42002cf20, 0x3, 0x3, 0x0, 0x0, 0x0)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: net/rpc.(*service).call(0xc42069e280, 0xc420a8e1e0, 0xc4207b0478, 0xc42096b580, 0xc420bf5120, 0x1a1a400, 0xc420be7fe0, 0x16, 0x1a1a440, 0xc4208698a0, ...)
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: created by net/rpc.(*Server).ServeCodec
2017-10-05T01:00:03.757Z [DEBUG] plugin.terraform-provider-aws_v1.0.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

This looks like a duplicate of https://github.com/hashicorp/terraform/issues/15442 or https://github.com/hashicorp/terraform/issues/15855

Do you mind providing related Terraform configs, at least for `module.client-es-asg.aws_elb.client_elb` so we can confirm this?

**Comment by paddycarver** [comment] 2017-11-20 23:06
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, or continue to have the problem described, please feel free to reply to this issue and we'll reopen it. Thanks!

**Closed by paddycarver** 2017-11-20 23:06 UTC
Labels: bug, crash, waiting-response
