### ISSUE TITLE
Poor formatting for terraform plan/apply 

### ISSUE THREAD

**Issue by Caspain** [hashicorp/terraform#18176] opened 2018-06-02 13:48 UTC
Currently when the plan command is run, the output indicating changes are scary and confusing, is there any work being done to create a more pretty and less confusing display. Something such as mysql table output would work just fine.

ingress.288196859.self:                "false" => "false"
      ingress.288196859.to_port:             "1514" => "1514"
      ingress.3224597687.cidr_blocks.#:      "1" => "0"
      ingress.3224597687.cidr_blocks.0:      "0.0.0.0/0" => ""
      ingress.3224597687.description:        "" => ""
      ingress.3224597687.from_port:          "80" => "0"
      ingress.3224597687.ipv6_cidr_blocks.#: "1" => "0"
      ingress.3224597687.ipv6_cidr_blocks.0: "::/0" => ""
      ingress.3224597687.protocol:           "tcp" => ""
      ingress.3224597687.security_groups.#:  "0" => "0"
      ingress.3224597687.self:               "false" => "false"
      ingress.3224597687.to_port:            "80" => "0"
      ingress.4269942136.cidr_blocks.#:      "1" => "1"
      ingress.4269942136.cidr_blocks.0:      "0.0.0.0/0" => "0.0.0.0/0"
      ingress.4269942136.description:        "" => ""
      ingress.4269942136.from_port:          "4500" => "4500"
      ingress.4269942136.ipv6_cidr_blocks.#: "0" => "0"
      ingress.4269942136.protocol:           "udp" => "udp"
      ingress.4269942136.security_groups.#:  "0" => "0"
      ingress.4269942136.self:               "false" => "false"
      ingress.4269942136.to_port:            "4500" => "4500"

**Comment by jbardin** [comment] 2018-06-04 13:36
Duplicate of #15180

**Closed by jbardin** 2018-06-04 13:36 UTC
