### ISSUE TITLE
Same old sudo issue with chef provisioner.  Tried Terraform 0.11.11, 0.11.14, 0.12.10

### ISSUE THREAD

**Issue by i255d** [hashicorp/terraform#23130] opened 2019-10-19 21:04 UTC
### Terraform Version

```
Terraform v0.12.10
+ provider.azurerm v1.35.0
```

### Terraform Configuration Files

```hcl
THIS IS SOME FRUSTRATING CRAP!  I HAVE BEEN WORKING ON THIS FOR 6 DAYS, 
AND TRYING TO GET SOME HELP, INCLUDING USING THE SLACK CHANNEL, BOTH 
TERRAFORM AND CHEF, AND I CAN'T GET ANY STRAIGHT ANSWERS.  IT WAS THE 
MANY USERS AT THE CHEF CONF THAT USE TERRAFORM THAT CONVINCED ME TO 
GIVE IT A TRY, IT SEEMS THAT TERRAFORM WORKING WITH CHEF SHOULD BE A 
PRETTY COMMON USE CASE.
PLEASE HELP ME TO GET THIS WORKING, OR TAKE IT OFF YOUR WEB SITE AS AN OPTION!!!

    provisioner "chef" {
    environment     = "_default"
    use_policyfile  = false
    run_list        = ["recipe[rhel7_default]"]
    node_name       =  local.vm_name
    server_url      = "https://chef-server.env.dom.ca/organizations/ours"
    user_name       = "${var.admin_username}"
    user_key        = "${file("C://01servers//dir//prod//chef-repo//.chef//user_admin.pem")}"
    client_options  = ["chef_license 'accept'"]
    ssl_verify_mode = ":verify_none"
    recreate_client = true
    os_type         = "linux"
    version         = "14.13.11"
  }
  connection {
    type     = "ssh"
    user     =  var.admin_username
    password =  var.admin_password
    host     =  local.fqdn
  }
```

### Crash Output

```
data.azurerm_subnet.data_subnet: Refreshing state...
module.vserver.data.azurerm_network_security_group.data_nsg: Refreshing state...
data.azurerm_resource_group.data_rg: Refreshing state...
module.vserver.data.azurerm_storage_account.daiglog: Refreshing state...
module.vserver.azurerm_network_interface.nic: Creating...
module.vserver.azurerm_network_interface.nic: Creation complete after 1s [id=/subscriptions/2f7f6596-b431-4828-914d-50327c699c40/resourceGroups/uat-dji-tst1/providers/Microsoft.Network/networkInterfaces/testg.env.dom.ca-nic]
module.vserver.azurerm_virtual_machine.vm: Creating...
module.vserver.azurerm_virtual_machine.vm: Still creating... [10s elapsed]
module.vserver.azurerm_virtual_machine.vm: Still creating... [1m10s elapsed]
module.vserver.azurerm_virtual_machine.vm: Still creating... [2m30s elapsed]
module.vserver.azurerm_virtual_machine.vm: Provisioning with 'chef'...
module.vserver.azurerm_virtual_machine.vm (chef): Connecting to remote host via SSH...
module.vserver.azurerm_virtual_machine.vm (chef):   Host: testg.env.dom.ca
module.vserver.azurerm_virtual_machine.vm (chef):   User: user_admin
module.vserver.azurerm_virtual_machine.vm (chef):   Password: true
module.vserver.azurerm_virtual_machine.vm (chef):   Private key: false
module.vserver.azurerm_virtual_machine.vm (chef):   Certificate: false
module.vserver.azurerm_virtual_machine.vm (chef):   SSH Agent: false
module.vserver.azurerm_virtual_machine.vm (chef):   Checking Host Key: false
module.vserver.azurerm_virtual_machine.vm (chef): Connected!

module.vserver.azurerm_virtual_machine.vm (chef): We trust you have received the usual lecture from the local System
module.vserver.azurerm_virtual_machine.vm (chef): Administrator. It usually boils down to these three things:

module.vserver.azurerm_virtual_machine.vm (chef):     #1) Respect the privacy of others.
module.vserver.azurerm_virtual_machine.vm (chef):     #2) Think before you type.
module.vserver.azurerm_virtual_machine.vm (chef):     #3) With great power comes great responsibility.

module.vserver.azurerm_virtual_machine.vm (chef): [sudo] password for user_admin:
module.vserver.azurerm_virtual_machine.vm: Still creating... [2m40s elapsed]
module.vserver.azurerm_virtual_machine.vm: Still creating... [4m20s elapsed]
module.vserver.azurerm_virtual_machine.vm: Still creating... [7m30s elapsed]

module.vserver.azurerm_virtual_machine.vm (chef): Cleanup user key...

module.vserver.azurerm_virtual_machine.vm (chef): We trust you have received the usual lecture from the local System
module.vserver.azurerm_virtual_machine.vm (chef): Administrator. It usually boils down to these three things:

module.vserver.azurerm_virtual_machine.vm (chef):     #1) Respect the privacy of others.
module.vserver.azurerm_virtual_machine.vm (chef):     #2) Think before you type.
module.vserver.azurerm_virtual_machine.vm (chef):     #3) With great power comes great responsibility.

module.vserver.azurerm_virtual_machine.vm (chef): [sudo] password for user_admin:
module.vserver.azurerm_virtual_machine.vm: Still creating... [7m40s elapsed]
module.vserver.azurerm_virtual_machine.vm: Still creating... [9m30s elapsed]
module.vserver.azurerm_virtual_machine.vm: Still creating... [12m30s elapsed]

module.vserver.azurerm_virtual_machine.vm (chef): WARNING: Failed to cleanup user key on new node: error executing "sudo rm -f /etc/chef/user_admin.pem": Process exited with status 1

Error: error executing "sudo curl -LO https://omnitruck.chef.io/install.sh": Process exited with status 1

```
### Expected Behavior

```
 I expect the new server being built by Terraform to connect to the Chef server, register the node name, download the chef-client, check into the chef server and get and run the first recipe.  It should connect to the node via ssh.  
```

### Actual Behavior

```
It appears to be connecting to the node, it looks like it is trying to run a sudo command and it hangs up because it doesn't seem to be able too.  It tries 3 or 4 times and then times out and outputs it can't clean up cert or run a curl command.  
```

### Steps to Reproduce

```
In an effort to control which version of Terraform I am running, I have been running the command with a literal path from my Windows 10 desktop.  (C:\01servers\tf\terraform12\terraform.exe --version)  I have a VPN connection to the azure network the node is being built on.  
C:\01servers\tf\terraform12\terraform.exe init -input=false -reconfigure
C:\01servers\tf\terraform12\terraform.exe get
C:\01servers\tf\terraform12\terraform.exe apply -var-file="$custKeyPath" `
                                        -var-file="$custEnvVarPath" `
                                        -var-file="$custConfigPath" `
                                        -auto-approve
```

### Additional Context

```
I have seen the previous bug reports on this from June of 2016.
https://github.com/hashicorp/terraform/issues/6967
I opened a response to that 5 days ago:
https://github.com/hashicorp/terraform/issues/23075

I have tried editing the sudoers file on the server and running the apply:
user_adminALL=(ALL) NOPASSWD: ALL
sudo sudoedit -e /etc/sudoers
This did not seem to have any impact.  
I have tried on several versions Terraform 0.11.11, 0.11.14, and 0.12.10, I continue to get 
module.vserver.azurerm_virtual_machine.vm (chef): [sudo] password for user_admin:

I have just tried to run this with 
prevent_sudo    = true
And it went a little farther.  Eliminating more connectivity issues. 
Below it starts to fail with this:
module.vserver.azurerm_virtual_machine.vm (chef): error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
This seems like a root-level access issue. 

module.vserver.azurerm_virtual_machine.vm: Still creating... [1m20s elapsed]
module.vserver.azurerm_virtual_machine.vm: Still creating... [1m30s elapsed]
module.vserver.azurerm_virtual_machine.vm: Provisioning with 'chef'...
module.vserver.azurerm_virtual_machine.vm (chef): Connecting to remote host via SSH...
module.vserver.azurerm_virtual_machine.vm (chef):   Host: testg.env.dom.ca
module.vserver.azurerm_virtual_machine.vm (chef):   User: user_admin
module.vserver.azurerm_virtual_machine.vm (chef):   Password: true
module.vserver.azurerm_virtual_machine.vm (chef):   Private key: false
module.vserver.azurerm_virtual_machine.vm (chef):   Certificate: false
module.vserver.azurerm_virtual_machine.vm (chef):   SSH Agent: false
module.vserver.azurerm_virtual_machine.vm (chef):   Checking Host Key: false
module.vserver.azurerm_virtual_machine.vm (chef): Connected!
module.vserver.azurerm_virtual_machine.vm (chef):   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
module.vserver.azurerm_virtual_machine.vm (chef):                                  Dload  Upload   Total   Spent    Left  Speed
module.vserver.azurerm_virtual_machine.vm (chef):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
module.vserver.azurerm_virtual_machine.vm (chef):  10 23103   10  2391    0     0   2641      0  0:00:08 --:--:--  0:00:08  2641
module.vserver.azurerm_virtual_machine.vm (chef): 100 23103  100 23103    0     0  25212      0 --:--:-- --:--:-- --:--:-- 25221
module.vserver.azurerm_virtual_machine.vm (chef): el 7 x86_64
module.vserver.azurerm_virtual_machine.vm (chef): Getting information for chef stable 14.13.11 for el...
module.vserver.azurerm_virtual_machine.vm (chef): downloading https://omnitruck.chef.io/stable/chef/metadata?v=14.13.11&p=el&pv=7&m=x86_64
module.vserver.azurerm_virtual_machine.vm (chef):   to file /tmp/install.sh.1355/metadata.txt
module.vserver.azurerm_virtual_machine.vm (chef): trying wget...
module.vserver.azurerm_virtual_machine.vm (chef): sha1  b6659fb2443e112a3367ce9b172d74716a981bd3
module.vserver.azurerm_virtual_machine.vm (chef): sha256        0099be9a928c988472075361626b5632ef32c600fb5350dc91bc575fdc22b12e
module.vserver.azurerm_virtual_machine.vm (chef): url   https://packages.chef.io/files/stable/chef/14.13.11/el/7/chef-14.13.11-1.el7.x86_64.rpm
module.vserver.azurerm_virtual_machine.vm (chef): version       14.13.11
module.vserver.azurerm_virtual_machine.vm (chef): downloaded metadata file looks valid...
module.vserver.azurerm_virtual_machine.vm (chef): downloading https://packages.chef.io/files/stable/chef/14.13.11/el/7/chef-14.13.11-1.el7.x86_64.rpm
module.vserver.azurerm_virtual_machine.vm (chef):   to file /tmp/install.sh.1355/chef-14.13.11-1.el7.x86_64.rpm
module.vserver.azurerm_virtual_machine.vm (chef): trying wget...
module.vserver.azurerm_virtual_machine.vm (chef): Comparing checksum with sha256sum...
module.vserver.azurerm_virtual_machine.vm (chef): Installing chef 14.13.11
module.vserver.azurerm_virtual_machine.vm (chef): installing with rpm...
module.vserver.azurerm_virtual_machine.vm (chef): warning: /tmp/install.sh.1355/chef-14.13.11-1.el7.x86_64.rpm: Header V4 DSA/SHA1 
Signature, key ID 83ef826a: NOKEY
module.vserver.azurerm_virtual_machine.vm: Still creating... [1m40s elapsed]
module.vserver.azurerm_virtual_machine.vm (chef): error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
module.vserver.azurerm_virtual_machine.vm (chef): Installation failed
module.vserver.azurerm_virtual_machine.vm (chef): Cleanup user key...

module.vserver.azurerm_virtual_machine.vm (chef): Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
module.vserver.azurerm_virtual_machine.vm (chef): Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
module.vserver.azurerm_virtual_machine.vm (chef): More Chef support resources can be found at https://www.chef.io/support

module.vserver.azurerm_virtual_machine.vm (chef): Please include as many details about the problem as possible i.e., how to reproduce
module.vserver.azurerm_virtual_machine.vm (chef): the problem (if possible), type of the Operating System and its version, etc.,   
module.vserver.azurerm_virtual_machine.vm (chef): and any other relevant details that might help us with troubleshooting.

Error: error executing "bash ./install.sh -v \"14.13.11\" -c stable": Process exited with status 1
```

### References

```
#23075
#6967
```

**Comment by i255d** [comment] 2019-10-19 21:14
Do not close this issue.

**Comment by jbardin** [comment] 2019-10-21 19:49
Hi @i255d,

The output here looks like it's blocked asking for a sudo password, but a provisioner has no way to prompt a user for a password. If the configured user can't sudo, it's not going to be able to fully execute the provisioner. 

Unfortunately because the `sudo` calls are from within the chef installer, there's no way for the provisioner to force it to fail immediately. 

The [provisioner documentation](https://www.terraform.io/docs/provisioners/index.html#provisioners-are-a-last-resort) has some guidance on provisioners that may be relevant here, like using `custom_data` to help bootstrap the instances.

**Comment by i255d** [comment] 2019-10-21 22:00
Wouldn't it be better if we added property to the provisioner that would accept that sudo password and then it would have a reply to the prompt for sudo, or it could be added to the sudo command.  Or, we could create the provisioner so it can accept a tar package that included the chef-client, so it would not have to be downloaded and there could be a script that passes the info switch to sudo and then run the commands.  It could get the package using file and get it local, or from blob storage with a key.

**Comment by i255d** [comment] 2019-10-22 04:53
The default for Chef Cookbooks is that they are run as root, since this bootstrap won't work without admin privilege's, it should have the same default.  That reminds me that there is a prevent_sudo  parameter, it would make you think the default is running everything as sudo.

**Comment by jbardin** [comment] 2019-10-22 12:48
We cannot enter the password via stdin, because that would entail changing the sudo call to accept a password via stdin, and the problematic one is in the Chef installer itself not the provisioner code (not to mention, parsing the output stream for a sudo prompt is not a very robust solution itself) . The `prevent_sudo` option is precisely for the reason you cite, you can run it as root and you don't want to invoke `sudo`

Other architectural changes may not be out of the ream of possibility, but as mentioned in the documentation linked above, provisioners cover a few common cases and not meant to solve all problems. There are too many things provisioners _could_ do, and it's usually better to solve them in other ways with more control and better customization fo the process. 

Since the initial issue here appears to be working as intended, I'm going to close this out. While we do plan to reevaluate how community provisioners can be managed, and the role of provisioners in general, out focus is elsewhere at the moment and their execution model isn't going to change in the near future. 

Thanks!

**Closed by jbardin** 2019-10-22 12:48 UTC
Labels: bug, provisioner/chef

**Comment by i255d** [comment] 2019-10-23 10:50
You guys are pretty quick to close these out.  What do you mean it can be run as root?  Is that how we can make this provisioner work is to change     user_name = "${var.admin_username}" to user_name = "root".  Because as this stands right now, this does not work, so it should be taken down.  Who did write this provisioner?  Can I reach out to them?  As I see the documentation, right now you don't have a working model of this provisioner.   And because your previous references to this, #6967 say it was fixed in the next version, it is even more misleading and time-wasting.  

How can you say the initial issue here works as intended when it stops at:
     module.vserver.azurerm_virtual_machine.vm (chef): [sudo] password for user_admin:
     module.vserver.azurerm_virtual_machine.vm: Still creating... [2m40s elapsed]
     module.vserver.azurerm_virtual_machine.vm: Still creating... [4m20s elapsed]
     module.vserver.azurerm_virtual_machine.vm: Still creating... [7m30s elapsed]
and does not do anyting but fail???

**Comment by i255d** [comment] 2019-10-23 11:05
You guys are pretty quick to close these out.  What do you mean, the provisioner can be run as root?  Is that how we can make this provisioner work is to change user = "${var.admin_username}" to user_name = "root" in the connection block and use prevent_sudo, it will work?.  Because as this stands right now, this does not work, so it should be taken down.  Who did write this provisioner?  Can I reach out to them?  As I see the documentation, right now, you don't have a working model of this provisioner.   And because your previous references to this, #6967 say it got fixed in the next version, it is even more misleading and time-wasting. 

How can you say the initial issue here works as intended when it stops at:
     module.vserver.azurerm_virtual_machine.vm (chef): [sudo] password for user_admin:
     module.vserver.azurerm_virtual_machine.vm: Still creating... [2m40s elapsed]
     module.vserver.azurerm_virtual_machine.vm: Still creating... [4m20s elapsed]
     module.vserver.azurerm_virtual_machine.vm: Still creating... [7m30s elapsed]
and does not do anyting but fail???

Don’t you think this should be take off the website since it doesn’t work?  

At the very least, can you help me to work out a solution that makes sense and works?

**Comment by jbardin** [comment] 2019-10-23 15:19
Since the installer needs to be run non-interactively, the provisioner needs to assume that the user has permission to do so. That could mean running as root, or in the normal case as a user with proper permissions and the ability to execute passwordless-sudo during installation. This may take some bootstrap configuration on the node itself.

The recommended method for bootstrapping an instance on azure is to use `custom_data`, in which case one normally would add the chef configuration to that as well, alleviating the need for a terraform provisioner in general. That also provides other paths to allow the storage of sensitive information like password and private keys outside of terraform.
