### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17decc5]

### ISSUE THREAD

**Issue by rquadling** [hashicorp/terraform#28792] opened 2021-05-24 16:16 UTC
### Terraform Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
n/a
```

### Debug Output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17decc5]

goroutine 1639 [running]:
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).planDestroy(0xc001001dc0, 0x38eee80, 0xc000fe88c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/terraform/node_resource_abstract_instance.go:402 +0x185
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc0028f4f80, 0x38eee80, 0xc000fe88c0, 0x100a908, 0x33fbf20, 0xc00264ec50)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:126 +0x538
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0xc0028f4f80, 0x38eee80, 0xc000fe88c0, 0xe470202, 0xc00264ece8, 0x100b805, 0x30a8180)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0xb3
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000abcc30, 0x38eee80, 0xc000fe88c0, 0xe470290, 0xc0028f4f80, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:129 +0xbf
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1(0x33fbf20, 0xc0028f4f80, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/terraform/graph.go:59 +0xbd3
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000e09bc0, 0x33fbf20, 0xc0028f4f80, 0xc000ce84c0)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x288
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0x1246
```

### Expected Behavior

For the deposed resource to be removed from state. (I don't know at the moment how to recreate the scenario.)

### Actual Behavior

It looks like Terraform attempts to find additional information relating to an orphan/deposed resource and crashes.

### Steps to Reproduce

Have a tfstate that contains a non existent resource and try to plan.

### Additional Context

Running `terraform show` presents:

```
$ terraform show
# module.api_asg.aws_lb.network_lb[0]:
# module.api_asg.aws_lb.network_lb[0]: (deposed object 2121c4ee)
resource "aws_lb" "network_lb" {
}
```

Manually removing the orphan from state:
```
$ terraform state list 'module.api_asg.aws_lb.network_lb[0]'
module.api_asg.aws_lb.network_lb[0]

$ terraform state show 'module.api_asg.aws_lb.network_lb[0]'
No instance found for the given address!

This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify 
the address to reference a specific instance.

$ terraform state rm 'module.api_asg.aws_lb.network_lb[0]'
Removed module.api_asg.aws_lb.network_lb[0]
Successfully removed 1 resource instance(s).
```

Once removed the plan was generated successfully.

**Comment by jbardin** [comment] 2021-05-24 16:56
Thanks for reporting this @rquadling! Duplicate of #28763

**Closed by jbardin** 2021-05-24 16:56 UTC
Labels: bug, new
