### ISSUE TITLE
skip_schema_creation should also skip table and index creation

### ISSUE THREAD

**Issue by psevestre** [hashicorp/terraform#25708] opened 2020-07-30 17:20 UTC
Regarding this code:

https://github.com/hashicorp/terraform/blob/bcc3af817398fed718b12a24815694ab611a1909/backend/remote-state/pg/backend.go#L75

I'd like to use multiple database users with this backend, so people can also run terraform from their workstations. However, when running the **terraform init** command using a different user PostgreSQL complains because it is not the "owner" of the already existing table.

So, I think that this flag should make the initialization code skip also the _create table_ and _create index_ statements.

**Comment by alisdair** [comment] 2020-07-30 18:51
Thanks for reporting this! I think that this is an issue to be addressed in the PostgreSQL Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the PostgreSQL provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by psevestre** [comment] 2020-07-31 17:21
Hi, just complementing: I _can_ use multiple users with the "pg" remote provider, using a common role that is the owner of the tables and then granting this role to every user that will use it.

However, some shops have a "no-ddl" policy for user accounts, so I think it would still be useful if this option did what I thought at first: just skip all schema creation statements, which include creating the schema, table and index.

regards,

**Comment by danieldreier** [comment] 2020-08-06 15:05
@psevestre the postgresql state backend [currently doesn't have a maintainer](https://github.com/hashicorp/terraform/blob/master/CODEOWNERS). If you, or other folks who are reading this issue are interested in picking up maintainership for that backend, I'd be happy to talk about what that involves. The pg backend was [originally added as a community contribution](https://github.com/hashicorp/terraform/pull/19070) by @mars. The issue is that the core team doesn't have the necessary deep domain knowledge in postgresql to evaluate what changes are breaking, widely useful, performant, etc, so absent a maintainer with that knowledge, it's difficult for us to evaluate whether proposed changes are a good idea or not.

**Comment by remilapeyre** [comment] 2020-10-12 20:48
I agree with @psevestre here that it makes sense to expect this option to disable all DDL requests, or to have an option that does. Changing `skip_schema_creation` to skip the creation of the table and the index too would be a breaking change for users relying on the current behavior, in order to avoir that the PR I wrote introduces two new options specifically to skip the creation of the table and the index.

**Closed** 2020-10-14 17:36 UTC
Labels: backend/pg, needs-maintainer, v0.12
